### ISSUE TITLE
[华农兄弟] 华农兄弟公鹅太多了不要那么多宰一只去河边烤很香哦 - https://youtu.be/bHYzD6Sou0E

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1000]
https://youtu.be/bHYzD6Sou0E
<p>&#35270;&#39057;&#21457;&#24067;&#20110; May 2, 2020 at 09:55PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/bHYzD6Sou0E

#华农兄弟：公鹅太多了，不要那么多，宰一只去河边烤，很香哦
#Huanong Brothers: There are too many ganders. I don't need so many. We grill one on the riverside. Nice!

0:00:00.400,0:00:02.860
# 大家好  你看  兄弟送了一些西紅杮哦
Hi everyone! Look! My buddy has given me some tomatoes.

0:00:03.080,0:00:04.580
# 這西紅杮好像有點爛啦
The tomatoes seem to be a bit rotten.

0:00:05.080,0:00:06.060
# 給了菜葉子
Together with these veggie leaves,

0:00:06.760,0:00:08.140
# 給我家的那個鵝一起吃
I'll give them to our geese here.

0:00:10.560,0:00:12.180
# 鵝頭都伸出來啦
The geese are already peeping out their heads.

0:00:13.920,0:00:15.200
# 快點啦  好吃的
C'mon! Here's some good food.

0:00:18.620,0:00:19.480
# 這也不要   (註︰這個「也」和下面的「都」一樣，沒有「再次」的意思，只是強調，英文似乎沒有這說法，所以我改了一下變成問句以增強語氣)
Why don't they want it?

0:00:26.200,0:00:27.980
# 菜葉子  你看  有好吃的
Veggie leaves. Look! They're really tasty.

0:00:31.240,0:00:32.600
# 不吃菜葉子怎麼行
Good geese should have plenty of veggie leaves.

0:00:35.060,0:00:36.380
# 給它們吃它們都不吃
Why aren't they eating at all?

0:00:42.700,0:00:44.840
# 我去把它趕過來  可能沒看到
I'm gonna drive them here. Perhaps they can't see the food.

0:01:30.300,0:01:32.920
# 它好像  它好像是隻母的  這個
This one, it seems, it seems to be female.

0:01:33.660,0:01:34.440
# 抓一個公的來
Let me catch a male.

0:01:52.960,0:01:54.460
# 那個  那個  這個  這個
That one, that one! This one, this one!

0:02:01.160,0:02:02.860
# 那隻  那隻  那邊那個
That one, that one! That one over there.

0:02:17.580,0:02:20.120
# 你看  抓子半天才把它抓到
Look! It took us forever to catch it.

0:02:20.780,0:02:21.840
# 這個是公的哦
This is a male, you know

0:02:22.960,0:02:23.920
# 不要那麼多公的
I don't need so many males.

0:02:24.600,0:02:25.720
# 留一隻公的就行了
One is all what I need.

0:02:26.320,0:02:27.580
# 給它菜葉子它都不吃
I give it veggie leaves, but it's not eating at all.

0:02:28.780,0:02:30.120
# 好久都沒去過河邊了
It has been a long time since my last trip to the riverside.

0:02:31.380,0:02:32.040
# 今天
But today,

0:02:32.620,0:02:33.620
# 今天就帶它去
today, I'll going with it,

0:02:34.600,0:02:35.140
# 河邊
to the riverside.

0:02:59.860,0:03:02.100
# 你看  這個鵝  殺好啦
Look! The goose, has been processed.

0:03:02.600,0:03:03.940
# 拿到河邊  這邊來烤哦
I take it to the riverside, and grill it here.

0:03:05.080,0:03:06.000
# 就直接這樣烤
It can be grilled right away.

0:03:10.060,0:03:11.160
# 把它內臟去一下
Let me remove the guts.

0:03:39.180,0:03:42.520
# 把這個  這個  這個鵝肉  要稍微切一下哦  
Here, here, the meat here, needs to be sliced a few times.

0:03:44.420,0:03:45.920
# 要不然太大塊了  烤不熟
It can never be fully cooked otherwise. It's too big and thick.

0:04:00.640,0:04:01.620
# 給它捶一下背
Let me give it a back massage.

0:04:13.440,0:04:14.420
# 嗯  好啦
Um! Alright!

0:04:15.500,0:04:16.940
# 先去腌 去腌一下哦
I'll marinate, marinate it first.

0:04:18.780,0:04:20.060
# 加點  這個料酒
Put some, this is cooking wine.

0:04:22.520,0:04:23.220
# 不加那麼多
Not too much

0:04:25.560,0:04:26.320
# 加點油
Put some oil.

0:04:31.560,0:04:32.140
# 加一點
Put some,

0:04:33.940,0:04:35.060
# 這個醬油
this is soy sauce.

0:04:47.780,0:04:49.080
# 再加點  鹽
And also some, salt

0:05:00.060,0:05:01.800
# 再搞幾塊生薑下去
Let me get a few pieces of ginger as well.

0:05:02.880,0:05:03.720
# 生薑
Ginger

0:05:06.840,0:05:07.820
# 削下去
Slice it into pieces.

0:05:25.800,0:05:27.000
# 好啦  攪拌一下
Alright! Mix it well.

0:05:40.380,0:05:43.980
# 好啦  再腌個半小時  把那炭燒出來
Alright! Marinate it for half an hour. I'll light the charcoal first.

0:05:46.760,0:05:49.000
# 像這樣子  再腌一下先
It's fine now. Marinate it for a while first.

0:05:51.180,0:05:52.080
# 炭燒好來
Let me light the charcoal.

0:06:16.800,0:06:18.180
# 你看  剛好這裡
Look! It fits very well.

0:06:19.000,0:06:20.000
# 鵝就睡在這裡
I'll let the goose sleep here.

0:06:21.380,0:06:23.060
# 彈簧床  很舒服的哦
Spring bed. It's super comfy you know.

0:06:26.320,0:06:26.820
# 好啦
Alright!

0:06:27.740,0:06:28.300
# 生火
Set the fire.

0:06:29.100,0:06:30.040
# 先把火生起來
Let's set the fire first.

0:07:30.860,0:07:32.160
# 炭全部一起燒掉
Let me burn all the charcoal.

0:08:06.240,0:08:07.740
# 誒好  剛剛好
Aya! Perfect!

0:08:08.300,0:08:09.720
# 這火候剛剛好
And the fire is awesome.

0:08:10.080,0:08:11.460
# 把它翅肪給卸了
I've chopped off the wings.

0:08:12.260,0:08:12.920
# 要不然
Otherwise,

0:08:13.220,0:08:14.220
# 拍它擋在那裡  (註︰不明白，照字面翻譯算了)
they might get stuck there.

0:08:23.620,0:08:25.080
# 這兩個翅肪第一下來烤
I'll grill these two wings in a while.

0:09:01.500,0:09:02.620
# 啊  這樣可以
Ah! It's nice!

0:09:03.620,0:09:04.280
# 不要這個啦
I don't need this one anymore.

0:09:05.520,0:09:06.280
# 太難烤了
It made things too difficult.

0:10:30.700,0:10:31.540
# 鴨爪  (鵝爪)  (註︰他這視頻不只一次鴨鵝不分，我尊重海洋哥的澄清吧)
Duck foot (goose foot)

0:11:26.460,0:11:27.480
# 把它倒出來
Let it drop it out.

0:11:29.440,0:11:30.460
# 中間烤不到
The middle part can't get grilled.

0:11:45.140,0:11:46.600
# 嗯  好香啊
Um! It smells really nice!

0:11:55.160,0:11:56.260
# 嘗一下熟了沒有
Let me have a try and see if it's done.

0:12:27.140,0:12:28.020
# 好香啊
It smells so good!

0:12:40.780,0:12:42.240
# 我再割一點下來吃
Let me cut one more piece and have a bite,

0:12:42.860,0:12:43.820
# 看熟了沒有
to see if it's done now.

0:12:47.800,0:12:48.360
# 嗯
Um!

0:12:48.780,0:12:49.340
# 好肥(註︰他之後又說「全是瘦肉」，所以這裡的「肥」應該是指多肉而已，我避用"fat"了)
Meaty!

0:12:52.560,0:12:53.460
# 嗯   熟啦
Um! It's done now.

0:12:58.820,0:12:59.380
# 我們
Let's,

0:13:01.240,0:13:02.540
# 邊拍  邊吃
film while eating.

0:13:06.160,0:13:07.180
# 這塊肉你吃一下
Try this piece,

0:13:11.260,0:13:12.280
# 看看味道怎麼樣
and see how it tastes.

0:13:22.920,0:13:23.660
# 好香啊
It smells really nice!

0:13:25.340,0:13:26.340
# 幫你搞個大腿吃
Let me get a leg for you.

0:13:49.960,0:13:51.860
# 嗯  這個蠻好吃的哦
Um! This is rather tasty!

0:13:55.940,0:13:57.400
# 誒呀  翻掉啦
Eya! It's flipped over.

0:14:01.260,0:14:03.040
# 誒呦  呼  想跑
Ayo! Huu! You wanna run away?

0:14:03.760,0:14:05.140
# 煮熟的鴨子想跑
How can a cooked duck run away?

0:14:05.540,0:14:06.840
# 這個  這個大腿還沒熟
The, the leg needs a bit more time.

0:14:09.920,0:14:11.220
# 這個把它卸下來才行
I think I need to chop it off.

0:14:13.120,0:14:14.000
# 別跑啦
Don't run away!

0:14:20.160,0:14:20.820
# 這大腿
The leg

0:14:30.240,0:14:31.760
# 哇  這一塊
Wa! What a nice piece!

0:14:32.540,0:14:35.940
# 你看這個肉 這個一坨坨肉  熟啦
Look at this meat, this bunches of meat. It's done now.

0:14:37.780,0:14:38.320
# 嗯
Um!

0:14:39.120,0:14:39.740
# 好香  (註︰這只是一個驚嘆，簡單的"Nice"似乎更合情景)
Nice!

0:14:44.700,0:14:45.480
# 全是瘦肉
There's only lean meat.

0:14:52.540,0:14:53.700
# 你看  這個鴨(鵝)腿  (註︰海洋哥又替他澄清了，我配合)
Look! This duck (goose) leg

0:15:02.480,0:15:05.180
# 最好吃的這個  肉又多
It tastes the best. And it's meaty too.

0:15:38.920,0:15:41.040
# 好啦  今天的視頻到這裡啦
Alright! The video ends here.

0:15:45.280,0:15:45.880
# 這個好吃
It's so tasty!

0:15:48.780,0:15:49.480
# 拜拜
Bye!

0:16:09.940,0:16:10.580
# 好啦
Alright!
