### ISSUE TITLE
【美食作家王刚】懒人盐酥花生米 - https://youtu.be/mZfzksOruPQ

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1008]
**视频链接**：https://youtu.be/mZfzksOruPQ

视频时长2:24，预计发布时间为北京时间5月8日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“懒人盐酥花生米”的零食加工厂做法，香脆可口好吃得停不下来

简介
同学们好，今天和大家分享“懒人盐酥花生米”，但是此懒人非彼懒人，并不是简单易做，而是做好之后吃起来真的停不下来，就想一直懒洋洋的吃😊并且自己来做盐酥花生非常健康，可以自己控制辅料调味，不会担心有添加剂香精等问题，做好之后需放入密闭罐子中保存以免返潮回软。喜欢花生类小零食的朋友一定不要错过，十分推荐！

本期菜品【懒人盐酥花生米】
【主料】
花生米（1000克）
【辅料】
八角（几颗）
香叶（几片）
桂皮（适量）
花椒（适量）
干辣椒（几个）
【调味料】
食用盐（700克）

字幕
0:00:00.320,0:00:01.420
哈喽大家好 我是王刚

0:00:01.420,0:00:03.140
本期视频我给大家分享一道小吃

0:00:03.560,0:00:04.800
懒人花生米

0:00:04.900,0:00:06.960
首先我们准备花生米1000克（2斤）

0:00:08.100,0:00:09.800
下一步我们开始准备香料

0:00:10.000,0:00:11.925
碗中加入双份八角几颗

0:00:12.200,0:00:13.575
加入几片香叶

0:00:13.900,0:00:15.325
加入适量的桂皮

0:00:15.650,0:00:17.050
加入适量的花椒

0:00:17.800,0:00:19.250
再加入几个干辣椒

0:00:19.675,0:00:22.375
最后再准备食用盐700克倒入碗中备用

0:00:24.150,0:00:25.450
下一步开始制作

0:00:25.450,0:00:27.625
首先我们在锅中加入适量的清水

0:00:29.625,0:00:31.875
冷水将准备好的花生米下锅

0:00:32.650,0:00:34.400
再加入1份准备好的香料

0:00:34.925,0:00:37.350
然后转中小火将花生米煮5分钟

0:00:37.375,0:00:39.575
这一步的目的是去除花生米的生味

0:00:41.350,0:00:43.400
5分钟之后倒出沥干水份备用

0:00:47.250,0:00:48.500
下一步开始制作

0:00:48.675,0:00:50.225
首先我们把锅烧热

0:00:52.150,0:00:55.050
锅烧热之后将准备好的食用盐和香料下锅

0:00:56.325,0:00:58.775
然后转小火将食用盐炒至100度

0:01:00.300,0:01:02.925
盐炒热之后加入处理好的花生米下锅

0:01:02.925,0:01:04.400
然后翻炒10分钟

0:01:04.550,0:01:07.950
第一阶段的时候食用盐会因为水份粘连在花生米上面

0:01:07.950,0:01:10.750
这时候的花生米非常咸请勿试吃

0:01:14.275,0:01:17.875
第二阶段的时候食用盐开始慢慢地脱落且变得干燥

0:01:17.950,0:01:21.525
此时的花生米开始慢慢地变香口感略微的发干

0:01:23.900,0:01:26.625
在第三阶段的时候食用盐开始变得发黄

0:01:26.650,0:01:28.825
这时候的花生米变得又脆又香

0:01:28.825,0:01:31.400
同学们切记全过程都必须开小火

0:01:31.450,0:01:33.500
否则花生米容易变得有糊味

0:01:36.225,0:01:38.725
10分钟之后我们关火再翻炒5分钟

0:01:38.725,0:01:41.125
这一步的目的是让花生米变得更脆

0:01:44.275,0:01:46.675
5分钟之后用漏勺筛除食用盐即可

0:01:46.675,0:01:48.775
待花生米冷却之后即可食用

0:01:55.180,0:01:58.040
一道香脆爽口的懒人花生米就制作完成

0:02:05.180,0:02:23.840
下面开始技术总结
第一，有条件的同学可以多加一些食用盐，这样更容易操作
且食用盐反复使用越炒越香，如香料变黑捡出丢弃即可
第二，全过程必须小火慢炒否则口感不脆
第三，花生米需要冷却之后口感才会达到最佳
懒人花生米的技术总结完毕


```

**Comment by archerdominique** [comment]
bot, please upload
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“懒人盐酥花生米”的零食加工厂做法，香脆可口好吃得停不下来
Chef Wang Gang shows you the factory recipe of salted crunchy peanuts for the lazy ones- can't stop eating them!

简介
同学们好，今天和大家分享“懒人盐酥花生米”，但是此懒人非彼懒人，并不是简单易做，而是做好之后吃起来真的停不下来，就想一直懒洋洋的吃😊并且自己来做盐酥花生非常健康，可以自己控制辅料调味，不会担心有添加剂香精等问题，做好之后需放入密闭罐子中保存以免返潮回软。喜欢花生类小零食的朋友一定不要错过，十分推荐！
Hello friends! Today I share with you "The Lazy One's salted crunchy peanuts". This time by "lazy" I don't mean that this recipe is simple, but when this dish is ready, you won't do anything else but munching down the peanuts like a idler. Moreover, home-cooked salted peanuts without artificial additives are healthier, and you can adjust the taste by changing the amount of seasoning ingredients. Cooked salted peanuts need to be seal in a jar to prevent it from getting damp and losing its crunchy texture. Don't miss this recipe if you really fancy peanut snacks. Strongly recommended!

本期菜品【懒人盐酥花生米】
【主料】
Main ingredients
花生米（1000克）
Peanuts (1kg)
【辅料】
(Other ingredients)
八角（几颗）
Star anises (A few)
香叶（几片）
Bay leaves (A few)
桂皮（适量）
Cinnamon bark (to need)
花椒（适量）
Sichuan Peppercorns (to need)
干辣椒（几个）
Dried Chilli Peppers (a few)
【调味料】
Seasoning ingredients
食用盐（700克）
Salt (700g)

字幕
0:00:00.320,0:00:01.420
哈喽大家好 我是王刚
Hi guys this is Wang Gang

0:00:01.420,0:00:03.140
本期视频我给大家分享一道小吃
In today's video I'll share with you a snack recipe

0:00:03.560,0:00:04.800
懒人花生米
Salted Peanuts for the Lazy Ones

0:00:04.900,0:00:06.960
首先我们准备花生米1000克（2斤）
First we get 1kg peanuts (2 Jin)

0:00:08.100,0:00:09.800
下一步我们开始准备香料
Next we prepare the spices

0:00:10.000,0:00:11.925
碗中加入双份八角几颗
A few star anises into two bowls

0:00:12.200,0:00:13.575
加入几片香叶
A few bay leaves

0:00:13.900,0:00:15.325
加入适量的桂皮
Cinnamon barks to need

0:00:15.650,0:00:17.050
加入适量的花椒
Some Sichuan peppercorn

0:00:17.800,0:00:19.250
再加入几个干辣椒
And a few dried chilli peppers

0:00:19.675,0:00:22.375
最后再准备食用盐700克倒入碗中备用
And finally, 700g of salt pour into the bowl for later use

0:00:24.150,0:00:25.450
下一步开始制作
Next let's start cooking

0:00:25.450,0:00:27.625
首先我们在锅中加入适量的清水
First, we pour a proper amount of water into the wok

0:00:29.625,0:00:31.875
冷水将准备好的花生米下锅
When the water is still cool, drop the peanuts in

0:00:32.650,0:00:34.400
再加入1份准备好的香料
With a bowl of prepared spices

0:00:34.925,0:00:37.350
然后转中小火将花生米煮5分钟
Turn to medium-low heat and cook the peanuts for 5 minutes

0:00:37.375,0:00:39.575
这一步的目的是去除花生米的生味
The purpose is to remove the raw smell of the peanuts

0:00:41.350,0:00:43.400
5分钟之后倒出沥干水份备用
After 5 minutes take out the peanuts and let them drip until dry

0:00:47.250,0:00:48.500
下一步开始制作
Then we start the actual cooking of peanuts (为了和上一个开始制作相区别

0:00:48.675,0:00:50.225
首先我们把锅烧热
First we heat up the wok

0:00:52.150,0:00:55.050
锅烧热之后将准备好的食用盐和香料下锅
Salt and the spices into the wok

0:00:56.325,0:00:58.775
然后转小火将食用盐炒至100度
Turn to low heat, stir and fry the salt until it reaches 100 °C

0:01:00.300,0:01:02.925
盐炒热之后加入处理好的花生米下锅
When the salt is heated up, drop in the peanuts

0:01:02.925,0:01:04.400
然后翻炒10分钟
Stir and fry for 10 minutes

0:01:04.550,0:01:07.950
第一阶段的时候食用盐会因为水份粘连在花生米上面
At the first stage, the salt would stick to the surface of peanuts because of the remaining moisture

0:01:07.950,0:01:10.750
这时候的花生米非常咸请勿试吃
Now the peanuts are extremely salty. Remember not to taste them

0:01:14.275,0:01:17.875
第二阶段的时候食用盐开始慢慢地脱落且变得干燥
At the second stage, the salt gradually turns dry and drop away from the peanuts

0:01:17.950,0:01:21.525
此时的花生米开始慢慢地变香口感略微的发干
Now the peanuts slowly give out the aroma, and its texture turns dry

0:01:23.900,0:01:26.625
在第三阶段的时候食用盐开始变得发黄
At the third stage, the salt begins to turn yellow

0:01:26.650,0:01:28.825
这时候的花生米变得又脆又香
Now the peanuts taste crunchy and flavourful

0:01:28.825,0:01:31.400
同学们切记全过程都必须开小火
Remember to use low heat in the whole cooking process

0:01:31.450,0:01:33.500
否则花生米容易变得有糊味
Or the peanuts get burned easily

0:01:36.225,0:01:38.725
10分钟之后我们关火再翻炒5分钟
after 10 minutes, we turn off the heat, stir and fry for another 5 minutes

0:01:38.725,0:01:41.125
这一步的目的是让花生米变得更脆
The purpose is to make the peanuts even more crunchy

0:01:44.275,0:01:46.675
5分钟之后用漏勺筛除食用盐即可
After 5 minutes, use a sieve to remove the salt and the dish is done

0:01:46.675,0:01:48.775
待花生米冷却之后即可食用
Wait until the peanuts cool down, and they are ready to eat

0:01:55.180,0:01:58.040
一道香脆爽口的懒人花生米就制作完成
The crunchy and aromatic peanuts for the lazy ones are now finished

0:02:05.180,0:02:23.840
下面开始技术总结
第一，有条件的同学可以多加一些食用盐，这样更容易操作
且食用盐反复使用越炒越香，如香料变黑捡出丢弃即可
第二，全过程必须小火慢炒否则口感不脆
第三，花生米需要冷却之后口感才会达到最佳
懒人花生米的技术总结完毕
Technical summaries:
First, you can use a bit more salt if you can, which can make the cooking easier. The salt would become more and more aromatic as you stir and fry it. If the spices turn black, just pick up and dispose them. 
Second, you should use low heat in the whole process of cooking peanuts, or they will not taste crunchy.
Third, only when they cool down you get the best taste and texture of peanuts.
That's all for the technical summaries
