### ISSUE TITLE
[华农兄弟] 华农兄弟今年的萢子熟了搞点来尝一下很美味哦 - https://youtu.be/5BboRh2TjeQ

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1009]
https://youtu.be/5BboRh2TjeQ
<p>&#35270;&#39057;&#21457;&#24067;&#20110; May 5, 2020 at 09:18PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/5BboRh2TjeQ

#华农兄弟：今年的萢子熟了，搞点来尝一下，很美味哦
#Huanong Brothers: The berries this year are now ripe. We pick some and have a try. Tasty!

0:00:00.200,0:00:03.140
# 今天我們去摘點那個萢子  就在那上面一點點
Today, we gonna pick some berries. They're just a tiny little bit up there.

0:00:03.580,0:00:04.800
# 應該現在快熟啦
I think they will be ripe very soon.

0:00:06.960,0:00:08.660
# 你看  現開始始種田了
Look! They've already started farming.

0:00:09.140,0:00:10.480
# 全部田都已經打好啦 (註︰不懂種田，不明白，是不是翻土的意思)
The soil has all been plowed.

0:00:11.780,0:00:13.100
# 坐等插秧  (註︰又不懂，有人懂種田的嗎？)
The next step is transplanting the seedlings.

0:00:21.740,0:00:23.740
# 你看  這個萢子  這種
Look! This berry, this type...

0:00:25.760,0:00:26.500
# 嗯
Um!

0:00:27.460,0:00:28.420
# 好香啊
It smells really nice!

0:00:29.500,0:00:30.460
# 淡淡的香味
It's a subtle fragrance.

0:00:31.700,0:00:32.640
# 草莓的味道
It tastes like strawberries,

0:00:33.120,0:00:34.500
# 比草莓的香味還香
but the fragrance is more significant than strawberries.

0:00:36.580,0:00:37.200
# 就是
Only,

0:00:37.900,0:00:39.000
# 缺點就是太小啦
if they could have been bigger.

0:00:40.660,0:00:41.780
# 你看  這裡有一個
Look! Here is one!

0:00:42.540,0:00:43.380
# 挺漂亮的哦
It's rather pretty, isn't it?

0:00:44.600,0:00:45.100
# 你看
Look!

0:00:45.520,0:00:47.100
# 這就是小時候最歡吃的
These used to be my most favourite snacks when I was a kid.

0:00:49.240,0:00:50.500
# 我記得還小的時候
I still remember when I was a kid,

0:00:52.560,0:00:54.160
# 天天  天天都去摘這個
we went to pick these berries every, every day.

0:00:55.720,0:00:57.080
# 早上一起來就去摘哦
We needed to come really early.

0:00:58.440,0:01:00.480
# 要不然  冕去一點就沒有了
Otherwise, if we came just a bit late, nothing would be left.

0:01:05.240,0:01:05.920
# 還可以哦
It's not bad.

0:01:06.760,0:01:07.260
# 這種 
It's,

0:01:07.980,0:01:09.120
# 這種跟草莓差不多
it's not so much different from strawberries.

0:01:09.420,0:01:10.280
# 不過這個有籽
But it has seeds,

0:01:10.580,0:01:11.560
# 草莓是沒籽的
while strawberries don't have any seeds.

0:01:14.180,0:01:15.540
# 味道比草莓還好吃
It tastes even better than strawberries.

0:01:16.940,0:01:17.880
# 就是少了一點
But there'are not too many of them.

0:01:18.360,0:01:19.240
# 少了一點
not too many.

0:01:20.000,0:01:22.220
# 你看這個  是最漂亮的哦  最大的
Have a look at this one! This is the pretties, and the biggest.

0:01:22.480,0:01:24.040
# 跟我的腳趾頭那麼大的
It's as big as the tip of my toe.

0:01:28.480,0:01:30.160
# 好甜啊這種大的
This kind of big one is really sweet.

0:01:30.460,0:01:31.800
# 就是找不到那麼
But there just aren't too many.

0:01:32.300,0:01:34.560
# 可能  一趟下來就找個幾個
Perhaps, I might get a few every time I come here.

0:01:34.960,0:01:37.520
# 剛剛有幾個  拍都沒拍就被我吃掉了
There were a few over there. But I'm already put them in my mouth before starting the camera.

0:01:38.400,0:01:39.960
# 現在再去找一下  看還有沒有
Let's search again, and see if there are any more.

0:01:41.960,0:01:42.460
# 哎呀
Aya!

0:01:43.140,0:01:45.160
# 好過癮啊  這一大片都是
It's so cool! Here the berries are everywhere.

0:01:46.000,0:01:47.440
# 本來說拿個袋子來裝的
I wanted to come with a bag.

0:01:47.860,0:01:48.360
# 算了
Forget it.

0:01:49.320,0:01:50.600
# 放在嘴巴上快一點
Putting them right into the mouth saves much time.

0:01:55.300,0:01:56.100
# 特別那種
Especially the ones,

0:01:56.840,0:01:58.480
# 紅得發黑的那種才好吃
the dark red ones, they're really delicacy.

0:01:59.060,0:02:00.480
# 好香啊  這種
It smells really good, this one.

0:02:02.140,0:02:02.640
# 你看
Look!

0:02:03.220,0:02:04.680
# 這個  啊  這個
This one, ah! This one,

0:02:06.300,0:02:08.200
# 長得太急啦  你看  長那麼大
it's too eager to grow. Look! It's so big.

0:02:09.880,0:02:11.140
# 這個壞的 不要
It's rotten. Pass!

0:02:12.360,0:02:14.300
# 哎呀  這粒好大的哦
Aya! This one is really big!

0:02:17.620,0:02:19.100
# 一片一片的
They're in bunches.

0:02:21.580,0:02:22.520
# 這個小的
Here's a small one.

0:02:30.100,0:02:30.940
# 真舒服
Cool!

0:02:32.560,0:02:33.400
# 特別這個
Especially this one,

0:02:35.860,0:02:37.040
# 這個是最香的
it's fragrance is the most significant.

0:02:47.860,0:02:48.860
# 你看  這個
Look! This one,

0:02:49.920,0:02:50.940
# 這還不是很熟
it's still a bit green.

0:02:52.800,0:02:53.600
# 要挑大的
I want the big ones.

0:02:58.640,0:02:59.220
# 這裡有
Here,

0:03:00.500,0:03:01.140
# 這兩顆
here are two.

0:03:03.880,0:03:04.400
# 你看
Look!

0:03:04.740,0:03:06.660
# 吃這種萢子要這樣子吃才爽
Let me show you the most exciting way to enjoy these berries.

0:03:12.060,0:03:12.880
# 嗯~
Um~

0:03:13.580,0:03:14.680
# 太美味啦
Best of the best!

0:03:16.860,0:03:18.320
# 看下還有沒有  再找一下
Let's search again, and see if there are any more.

0:03:19.880,0:03:20.740
# 都不過癮
It's far from enough.

0:03:22.520,0:03:23.560
# 這個大小啦  這個
This is too small, this one.

0:03:26.300,0:03:28.260
# 好啦  今天的視頻到這裡啦
Alright! The video ends here.

0:03:28.680,0:03:29.920
# 肚腩都吃出來啦
My tummy is already coming out.

0:03:29.960,0:03:30.460
# 哎呦
Ayo!

0:03:30.620,0:03:31.280
# 吃太飽啦
I've eaten too much.
