### ISSUE TITLE
【美食作家王刚】上棚扫竹叶 - https://youtu.be/KApR6idARE8

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1015]
**视频链接**：https://youtu.be/KApR6idARE8

视频时长4:40，预计发布时间为北京时间5月9日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
第一次上棚顶打扫竹叶，虽然比较恐高但是也很快适应了，以后交给徒弟来干！

简介
大家好，当初做这个棚子的时候就知道会有这么一天，竹叶不落在地上当然就落在棚上了，所以决定投资一个梯子以后方便上棚子来扫竹叶，我先以身作则上去试一试，有经验以后再交给徒弟来干 @馋小漆  。大家放心，当初设计和制作这个棚子的时候特地咨询过师父关于扫叶子的情况，只要踩在钢架上没有任何问题，上面可以承重几个人，不过为了安全还是不推荐大家上自己家屋顶，切记！

自从祖屋门口的梨树越长越高，很少能吃到果子，这次做棚子正好可以爬上去给梨子装袋子，到时候就能吃到了，很期待！

字幕
0:00:00.350,0:00:01.250
哈喽 大家好

0:00:01.275,0:00:03.150
最近我们这里装了一个棚

0:00:03.291,0:00:08.085
但是虽然说阳光也遮住了

0:00:08.261,0:00:10.104
这哈子没得以前嫩晒的了哈

0:00:11.234,0:00:12.649
这哈子晒不到了

0:00:12.649,0:00:14.964
就是上面的竹叶多得很

0:00:15.436,0:00:18.069
就是有一个问题竹叶老是掉到上面

0:00:18.365,0:00:20.219
才十多天你看

0:00:21.130,0:00:22.227
就跟黑黢黢的样

0:00:22.720,0:00:25.474
所以现在我们想办法把它弄下来

0:00:25.858,0:00:27.811
我还特意买了一个梯子

0:00:29.215,0:00:33.033
买了一个这个铝合金的梯子

0:00:33.527,0:00:34.854
本来是想借来用一下

0:00:34.854,0:00:37.542
我想到反正要经常打扫 就直接买了一个

0:00:38.804,0:00:40.460
买这个花了好几百块钱

0:00:42.995,0:00:43.971
这样子扎实得多

0:00:44.465,0:00:45.375
帮我扶到哈嘛

0:00:45.660,0:00:46.483
你上嘛

0:00:47.339,0:00:49.369
只是说它要横着跑 四伯爷你要注意到

0:00:49.917,0:00:52.331
横起跑不到

0:00:53.329,0:00:54.810
你才好重点哦

0:00:55.831,0:00:57.575
我还是有100多斤哈

0:01:04.816,0:01:06.637
指到那个钢架桥上踩哦

0:01:10.861,0:01:11.497
上来了

0:01:12.704,0:01:14.898
拿扫把上来是不

0:01:15.172,0:01:15.644
啊

0:01:20.548,0:01:22.194
不要朝两面滑就行了

0:01:22.194,0:01:23.214
晓得

0:01:24.498,0:01:26.143
干脆你们两个都上去整要快当点

0:01:26.308,0:01:27.613
我们两个上去整啥子哦

0:01:27.613,0:01:28.370
我给你扶着

0:01:31.398,0:01:32.737
你怕还撑不起啊

0:01:33.055,0:01:34.338
不是的 这上面吓人得很

0:01:34.371,0:01:37.531
有啥子吓人（腿）张开踩着2根条条（钢架）

0:01:39.539,0:01:40.186
站起来都

0:01:40.614,0:01:41.784
吓啥子嘛吓

0:01:48.403,0:01:49.116
开始扫了

0:01:49.555,0:01:50.246
扫嘛扫

0:02:44.040,0:02:45.338
二娃 这哈害不害怕哦

0:02:45.523,0:02:46.227
安

0:02:46.339,0:02:48.303
这哈整了这么久不害怕了噻

0:02:49.193,0:02:50.621
这哈子不是很害怕了

0:03:13.123,0:03:15.274
我们现在这个就搞好了

0:03:16.867,0:03:21.738
大家可以看一下我们这个梨树都结了果了

0:03:22.724,0:03:24.414
这个梨子非常香

0:03:24.800,0:03:26.018
可以长很大

0:03:26.619,0:03:30.656
但是如果不保护好的话 它这个鸟会来吃

0:03:36.329,0:03:37.426
你看你这还套起得

0:03:38.109,0:03:38.702
套是套起

0:03:38.702,0:03:39.283
好好好

0:03:39.283,0:03:40.704
我这哈把这里解了都

0:03:44.430,0:03:45.779
好多花花哦 小心点

0:03:47.024,0:03:49.437
我们上去到上面去弄了

0:03:49.437,0:03:52.454
上面因为是有点半透明的特别吓人

0:03:52.824,0:03:55.150
就是刚刚上去腿都会发抖

0:03:55.441,0:03:57.570
但是走几圈之后就不害怕了

0:03:58.767,0:04:01.817
我们家这个梨树结了很多果

0:04:02.581,0:04:06.508
可能再过三四个月吧 就可以吃了

0:04:06.759,0:04:07.340
特别的甜

0:04:07.915,0:04:10.866
四伯爷 这个梨子拿个口袋把它罩到哦

0:04:11.201,0:04:11.903
可以安

0:04:12.923,0:04:13.899
二回来

0:04:13.899,0:04:15.424
这会儿还小个的嘛

0:04:16.739,0:04:18.224
现在我们正好有这个棚

0:04:18.224,0:04:20.656
到时候上去装那个袋子是很方便的

0:04:20.656,0:04:21.303
嘎 很方便

0:04:21.303,0:04:22.170
嗯 这哈就方便

0:04:22.875,0:04:27.025
好 到时候我们摘梨子下来吃

0:04:27.100,0:04:28.225
不过要保护哈

0:04:28.400,0:04:30.660
肯定要保护哈 不保护哈你弄不到吃安

0:04:30.680,0:04:31.740
麻雀都要吃完

0:04:32.540,0:04:33.940
好了 本期视频就到这里

0:04:34.260,0:04:38.040
到时候把梨子保护一下 有梨就可以吃了


```

**Comment by Xuyuan0919** [comment]
认领

**Comment by Xuyuan0919** [comment]
0:00:00.350,0:00:01.250
哈喽 大家好
Hello everyone
0:00:01.275,0:00:03.150
最近我们这里装了一个棚
We installed a shed here recently
0:00:03.291,0:00:08.085
但是虽然说阳光也遮住了
Even though the sun was shaded
0:00:08.261,0:00:10.104
这哈子没得以前嫩晒的了哈
The sun was not as strong as before now, right
0:00:11.234,0:00:12.649
这哈子晒不到了
Yeah, it’s not too much sun now
0:00:12.649,0:00:14.964
就是上面的竹叶多得很
But there are a lot of bamboo leaves on the top  
0:00:15.436,0:00:18.069
就是有一个问题竹叶老是掉到上面
There is a problem that the bamboo leaves always drop on the shed
0:00:18.365,0:00:20.219
才十多天你看
See, only more than 10 days
0:00:21.130,0:00:22.227
就跟黑黢黢的样
Just like dark
0:00:22.720,0:00:25.474
所以现在我们想办法把它弄下来
So now we are planning to clean it
0:00:25.858,0:00:27.811
我还特意买了一个梯子
I bought a ladder
0:00:29.215,0:00:33.033
买了一个这个铝合金的梯子
I bought this aluminum alloy ladder
0:00:33.527,0:00:34.854
本来是想借来用一下
I thought of just borrow one to use once at first
0:00:34.854,0:00:37.542
我想到反正要经常打扫 就直接买了一个
And then I thought of I always need to clean it, so I bought one
0:00:38.804,0:00:40.460
买这个花了好几百块钱
Spend a few hundred RMB on this 
0:00:42.995,0:00:43.971
这样子扎实得多
This is more sturdy
0:00:44.465,0:00:45.375
帮我扶到哈嘛
Give me a hand
0:00:45.660,0:00:46.483
你上嘛
Go ahead
0:00:47.339,0:00:49.369
只是说它要横着跑 四伯爷你要注意到
It will slide to sideways, you have to notice, uncle
0:00:49.917,0:00:52.331
横起跑不到
It will not slide to sideways
0:00:53.329,0:00:54.810
你才好重点哦
You are so light
0:00:55.831,0:00:57.575
我还是有100多斤哈
I still over 100 jin 
0:01:04.816,0:01:06.637
指到那个钢架桥上踩哦
You should step on those steel strips
0:01:10.861,0:01:11.497
上来了
I came up
0:01:12.704,0:01:14.898
拿扫把上来是不
Bring a broom, right
0:01:15.172,0:01:15.644
啊
yes
0:01:20.548,0:01:22.194
不要朝两面滑就行了
Just don’t slide to sideways
0:01:22.194,0:01:23.214
晓得
I know
0:01:24.498,0:01:26.143
干脆你们两个都上去整要快当点
Why don’t you both get up there to clean, that will be faster
0:01:26.308,0:01:27.613
我们两个上去整啥子哦
What can we do up there
0:01:27.613,0:01:28.370
我给你扶着
I’ll give you a hand
0:01:31.398,0:01:32.737
你怕还撑不起啊
Are you afraid of it can’t support you
0:01:33.055,0:01:34.338
不是的 这上面吓人得很
No, it’s so scary up here
0:01:34.371,0:01:37.531
有啥子吓人（腿）张开踩着2根条条（钢架）
Nothing to scared, just step on two strips (steels)
0:01:39.539,0:01:40.186
站起来都
I stood up
0:01:40.614,0:01:41.784
吓啥子嘛吓
Nothing to scared
0:01:48.403,0:01:49.116
开始扫了
I’ll begin to sweep
0:01:49.555,0:01:50.246
扫嘛扫
Just do it
0:02:44.040,0:02:45.338
二娃 这哈害不害怕哦
Erwa are you scared now
0:02:45.523,0:02:46.227
安
uh
0:02:46.339,0:02:48.303
这哈整了这么久不害怕了噻
You‘re not scared after all this time, right
0:02:49.193,0:02:50.621 
这哈子不是很害怕了
It’s not so scared now
0:03:13.123,0:03:15.274
我们现在这个就搞好了
We now have done this
0:03:16.867,0:03:21.738
大家可以看一下我们这个梨树都结了果了
You guys can see that our pear tree is fruiting
0:03:22.724,0:03:24.414
这个梨子非常香
These pears are smell and taste very good
0:03:24.800,0:03:26.018
可以长很大
They can grow pretty big
0:03:26.619,0:03:30.656
但是如果不保护好的话 它这个鸟会来吃
But if we don’t protect them, there will some birds to eat them
0:03:36.329,0:03:37.426
你看你这还套起得
Can it still be harnessed
0:03:38.109,0:03:38.702
套是套起
Yes, it can
0:03:38.702,0:03:39.283
好好好
okay
0:03:39.283,0:03:40.704
我这哈把这里解了都
I’ll untie this
0:03:44.430,0:03:45.779
好多花花哦 小心点
Too many flowers, be careful
0:03:47.024,0:03:49.437
我们上去到上面去弄了
We’ve already cleaned up there
0:03:49.437,0:03:52.454
上面因为是有点半透明的特别吓人
It’s so scared because is translucent up there
0:03:52.824,0:03:55.150
就是刚刚上去腿都会发抖
My legs were shaking when I just went up
0:03:55.441,0:03:57.570
但是走几圈之后就不害怕了
But it’s not scared when I walk around a few circles
0:03:58.767,0:04:01.817
我们家这个梨树结了很多果
Our pear tree has fruiting a lot of pears 
0:04:02.581,0:04:06.508
可能再过三四个月吧 就可以吃了
They will be eaten maybe after three or four months
0:04:06.759,0:04:07.340
特别的甜
They will be pretty sweet
0:04:07.915,0:04:10.866
四伯爷 这个梨子拿个口袋把它罩到哦
Uncle, we should use the pocket to cover those pears
0:04:11.201,0:04:11.903
可以安
Yeah, okay
0:04:12.923,0:04:13.899
二回来

0:04:13.899,0:04:15.424
这会儿还小个的嘛
It’s still small now
0:04:16.739,0:04:18.224
现在我们正好有这个棚
Now we have this shed
0:04:18.224,0:04:20.656
到时候上去装那个袋子是很方便的
So it’s will be pretty convenient when we fill the bag up there
0:04:20.656,0:04:21.303
嘎 很方便
Yes, Very convenient
0:04:21.303,0:04:22.170
嗯 这哈就方便
Yeah, it’s pretty convenient right now
0:04:22.875,0:04:27.025
好 到时候我们摘梨子下来吃
Okay, we’ll pick some pear to eat then
0:04:27.100,0:04:28.225
不过要保护哈
But we should protect them
0:04:28.400,0:04:30.660
肯定要保护哈 不保护哈你弄不到吃安
Of course, you can’t get them to eat if you don’t protect
0:04:30.680,0:04:31.740
麻雀都要吃完
The sparrows will eat up
0:04:32.540,0:04:33.940
好了 本期视频就到这里
Alright, that’s it for this video
0:04:34.260,0:04:38.040
到时候把梨子保护一下 有梨就可以吃了
We will have pears to eat, but we will protect them first
