### ISSUE TITLE
[华农兄弟] 华农兄弟去河里放地笼抓点鱼来养刚好兄弟有个鱼缸不要了 - https://youtu.be/z_tRZnKWmLY

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1017]
https://youtu.be/z_tRZnKWmLY
<p>&#35270;&#39057;&#21457;&#24067;&#20110; May 8, 2020 at 11:31AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/z_tRZnKWmLY

#华农兄弟：去河里放地笼，抓点鱼来养，刚好兄弟有个鱼缸不要了
#Huanong Borhters: We put a trap into the river to catch some fish. It just so happens that our buddy has an extra fish tank.

0:00:00.000,0:00:02.180
# 大家好  我們來放  放地籠
Hi everyone! We're put, putting the traps,

0:00:02.320,0:00:05.120
# 抓點魚回去那個我們家的那個池子里面養
to catch some fish to the, I mean, the pond at ours site.

0:00:05.720,0:00:07.860
# 我們家的池子裡面魚都沒有啦
There's is no more fish in our pond now,

0:00:08.580,0:00:09.360
# 一條都沒有
not even one.

0:00:10.660,0:00:12.960
# 全部  全  全部都被吃完啦
They've, they, they've all been eaten up.

0:00:13.720,0:00:15.700
# 現在到河裡面來  抓一點魚去
So we're coming to the river, to catch some fish back home.

0:00:20.340,0:00:21.240
# 就這裡
Right here

0:00:25.380,0:00:28.840
# 帶了點餌料  給它吃  把那魚騙進去
I have some bait, for the fish, to deceive them into the traps.

0:00:30.300,0:00:31.700
# 沒東西吃它不進的
They won't go into the traps otherwise.

0:00:40.700,0:00:41.920
# 你看  加下去
Look! I put the bait here,

0:00:43.320,0:00:44.820
# 一個地籠加一點點
a tiny little bit into each trap.

0:00:50.000,0:00:51.900
# 把這個地籠放在這邊
Let me put this trap here,

0:00:52.200,0:00:53.620
# 這邊水比較深一點
as the water is deeper here.

0:00:57.580,0:00:59.400
# 來來來來 有好吃的啦
C'mon, c'mon, c'mon! Here is some good food!

0:01:00.260,0:01:01.740
# 這裡的東西很好吃的哦
The food here is really tasty, you know.

0:01:02.560,0:01:04.000
# 哇  這個誰的魚釣
Wa! Whose fishing hook is it?

0:01:04.760,0:01:06.760
# 肯定是你們的  又去釣魚
It must be one of you guys. You went fishing again,

0:01:07.600,0:01:08.320
# 沒釣到
but couldn't catch any.

0:01:12.340,0:01:13.620
# 這裡還有個大的
Here's another one, a big one.

0:01:14.620,0:01:15.600
# 專抓大魚  (註︰原字幕缺失)
It's specially designed for big fish.

0:01:19.140,0:01:20.500
# 加一點配料下去  (註︰配料.....不管了，照翻譯吧)
Let me put some side ingredients.

0:01:58.820,0:02:02.140
# 現在那個網已經放下去了 我們明天早上再過來收
So now we've put the two traps there. Let's come again tomorrow and get them back.

0:02:02.640,0:02:03.140
# 現在
Now,

0:02:03.520,0:02:04.980
# 現在我們準備回去啦
now we're getting ready to go back.

0:02:06.840,0:02:07.680
# 第二天
The next day

0:02:07.920,0:02:09.960
# 今天我來收過個網  昨天放下去的
Today we're getting back the traps, that we put yesterday.

0:02:10.280,0:02:11.160
# 不知道有沒有魚
Let's see if there are any fish.

0:02:12.960,0:02:14.000
# 就在這前面這裡
It's right here in the front.

0:02:34.020,0:02:35.940
# 哇  好多啊
Wa! A lot!

0:02:37.200,0:02:37.700
# 你看
Look!

0:02:39.820,0:02:40.840
# 一大籠都是
It's full of fish!

0:02:41.840,0:02:42.820
# 不過就是小的
But they're are all small.

0:02:43.460,0:02:44.100
# 泥鰍
Loaches,

0:02:44.540,0:02:45.060
# 小魚
and small fish

0:02:49.940,0:02:51.380
# 哇  全是泥鰍
Wa! All are loaches.

0:02:51.660,0:02:52.920
# 這些泥鰍也是靚哦
These loaches are really beautiful.

0:02:56.980,0:02:58.000
# 拿桶裝點水去
Let me get some water with the bucket.

0:03:10.140,0:03:11.140
# 哎呀  有魚
Aya! Fish!

0:03:11.920,0:03:12.980
# 這裡就看得到魚啦
I can already see the fish here.

0:03:13.640,0:03:14.600
# 有泥鰍
Loaches,

0:03:16.280,0:03:18.100
# 這泥鰍怎麼好多鑽這裡來
why did so many loaches squeez in?

0:03:23.380,0:03:24.260
# 你看這泥鰍
Have a look at these loaches!

0:03:29.020,0:03:29.780
# 哇
Wa!

0:03:31.240,0:03:32.500
# 好大的蛇頭魚呦
What a huge snakehead fish!

0:03:33.120,0:03:35.360
# 有  有  有   有  三條
Not, not, not, not one but three!

0:03:36.940,0:03:37.440
# 你看
Look!

0:03:38.480,0:03:39.300
# 又有泥鰍
Loeaches,

0:03:40.300,0:03:41.120
# 又有鯽魚
"ji yu" (local carps)

0:03:44.600,0:03:45.380
# 這蛇頭魚
And this is a snakehead fish.

0:03:46.080,0:03:47.260
# 這個蛇頭魚夠大啦
This snakehead fish is really big.

0:03:50.860,0:03:51.780
# 放到簍子上去
Put them onto the basket.

0:03:53.680,0:03:54.380
# 哇
Wa!

0:03:55.000,0:03:55.560
# 你看
Look!

0:03:56.560,0:03:57.220
# 夠大啦
Big, aren't they?

0:04:00.380,0:04:01.420
# 好大  這個
It's, really big!

0:04:03.800,0:04:04.740
# 這條最大
And this is the biggest.

0:04:06.180,0:04:06.980
# 放在這裡來
Let me put them here.

0:04:08.180,0:04:09.460
# 你看  收獲滿滿
Look! A fruitful day

0:04:10.380,0:04:11.380
# 這個桶沒白帶
My effort of bringing this bucket is well paid,

0:04:12.860,0:04:13.540
# 那麼一大桶
by such a huge bucket of fish.

0:04:14.660,0:04:15.600
# 好啦  回去啦
Alright! Let's go back.

0:04:25.280,0:04:28.080
# 剛好兄弟家的魚缸  他不要啦
It just so happens that my buddy has a fish tank and he doesn't want it anymore.

0:04:34.460,0:04:35.620
# 這是山泉水哦
This is spring water.

0:04:36.820,0:04:38.260
# 把那水引下來
I'm catching the water to the tank,

0:04:38.980,0:04:40.600
# 讓魚喝上山泉水
so that the fish can enjoy the spring water.

0:04:42.280,0:04:44.580
# 增加它的肉質  更鮮美
This can enhance their texture, and taste.

0:04:58.620,0:05:00.140
# 等裝滿水了把魚放上來
I'll bring the fish here after filling up the tank.

0:05:09.540,0:05:13.980
# 嗯  你看  留了這個竹節啊  它可以把這個泥巴過瀘掉
Um, look! Keeping the bamboo joint here can filter out the mud.

0:05:15.040,0:05:17.280
# 到時候我們換一下再把這個丬乾淨就行啦
Then we can simply replace it, and rinse it.

0:05:17.540,0:05:19.740
# 這樣泥巴就不會掉  直接掉到那裡去
So the mud won't be falling, falling into the tank directly.

0:05:23.000,0:05:24.120
# 把這個魚放進去
Let me put the fish into the tank.

0:05:24.840,0:05:26.180
# 蛇頭魚  放裡面去
Snakehead fish, into the tank

0:05:27.080,0:05:27.680
# 哇
Wa!

0:05:29.520,0:05:30.640
# 爽不爽  這個
Cool, isn't it?

0:05:31.020,0:05:31.960
# 大房間哦
Is it big room!

0:05:33.620,0:05:34.540
# 這裡也有條
Here's another one.

0:05:41.060,0:05:42.620
# 這三條都放到這裡面
I'll put all these three here.

0:05:46.840,0:05:48.100
# 再放一些小魚
Some small fish too

0:05:54.540,0:05:55.540
# 你看  那麼多小魚
Look! So many small fish

0:05:56.380,0:05:57.400
# 我放在魚缸裡面
Let me put them into the tank,

0:05:58.020,0:05:59.120
# 讓它們生活在一起
so that they can live together.

0:05:59.860,0:06:00.980
# 來  你們自由啦
C'mon! You're free now.

0:06:06.800,0:06:08.280
# 你看  好多這小魚哦
Look! A lot of this kind of small fish

0:06:16.780,0:06:17.600
# 發脾氣啦
It's angry.

0:06:18.900,0:06:20.460
# 這麼好的地方你們不要
Why don't you like this place? It's so nice!

0:06:26.640,0:06:28.100
# 那麼多食物哦
Here's a lot of food.

0:06:40.980,0:06:41.480
# 你看
Look!

0:06:42.340,0:06:43.800
# 你這轉來轉去的  它們
They're going round and round and round here.

0:06:44.040,0:06:44.900
# 很喜歡這裡哦
They love this place.

0:06:48.640,0:06:49.700
# 這裡有鬥魚
Here are fighting fish,

0:06:50.520,0:06:51.460
# 有花鯽魚
"hua ji yu" (local carps)

0:06:52.320,0:06:53.340
# 有蛇頭魚
snakehead fish,

0:06:53.580,0:06:54.340
# 有泥鰍
and loaches.

0:07:06.200,0:07:08.720
# 你看  這個蛇頭魚呀  它喜歡吃肉的
Look! This snakehead fish, it loves eat.

0:07:09.280,0:07:11.220
# 它就只吃肉的  它不吃素的
It doesn't eat any veggies, only meat,

0:07:11.740,0:07:13.020
# 很喜歡吃不魚的
small fish, in particular.

0:07:13.660,0:07:18.080
# 你看  這些泥鰍啊  這些鯽魚  可能都是變成了它們的盤中餐 (註︰不想再注音鯽魚了)
Look! These loaches, together with other small fish, may become their meals.

0:07:18.960,0:07:20.420
# 我們也很喜歡吃肉
We love meat too.

0:07:22.720,0:07:23.360
# 那麼快
So fast

0:07:31.900,0:07:33.720
# 搞了一個這個遮陰  遮陰網
I've fetched a shade, a shading net.

0:07:34.080,0:07:36.060
# 來蓋一下它們  要不然它們全跑了
I'll cover them up. Otherwise, they would all run away.

0:07:46.180,0:07:47.960
# 先把下面這一個先蓋一下
Let me cover this lower one first.

0:08:32.660,0:08:33.540
# 嗯  可以
Um! Alright!

0:08:34.740,0:08:35.240
# 你看
Look!

0:08:35.680,0:08:38.720
# 它們過得很開心哦  這樣子  又有山泉水喝
They can now live merrily here. I mean, they can enjoy the spring water.

0:08:39.920,0:08:42.700
# 下次我們吃魚的就跑來  在這裡抓
Next time when we want a fish for our meal, we can simply come here, and catch one.

0:08:43.680,0:08:44.260
# 多好啊
Nice!

0:08:46.560,0:08:48.500
# 好啦  今天的視頻到這裡了
Alright! The video ends here.
