### ISSUE TITLE
【美食作家王刚】肥肠鱼 - https://youtu.be/opSiomnDEQo

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1019]
**视频链接**：https://youtu.be/opSiomnDEQo

视频时长11:40，预计发布时间为北京时间5月10日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：川渝爆款“肥肠鱼”的做法，鱼和肥肠的美味兼得，真的过瘾！

简介
朋友们好，今天和大家分享一道“肥肠鱼”， 顾名思义，这道菜的主料就是肥肠和鱼，将两种看起来非常不一样的食材完美的融合。这样做出来的肥肠鱼色香味俱全，肥肠软嫩，鱼肉细腻嫩滑，并且香辣麻特别突出，简直就是四川人最喜爱的味道。并且一锅将鱼和肥肠兼得，快乐就是这么简单，一道好菜即可！

字幕
0:00:00.266,0:00:00.998
嗨喽大家好

0:00:01.171,0:00:05.392
今天我伯爷去卖肉 剩了一个

0:00:05.552,0:00:06.511
不是剩噶 留噶

0:00:06.511,0:00:07.909
专门给你留的

0:00:08.042,0:00:09.387
留了一笼这个肥肠

0:00:09.786,0:00:13.288
所以我在想这个肥肠平时我们炒啊烧啊

0:00:13.328,0:00:14.434
已经吃得有点腻了

0:00:14.474,0:00:16.458
然后今天做一个肥肠鱼

0:00:17.137,0:00:19.027
我把这个油啊这些把它撕完了要得不

0:00:19.547,0:00:22.077
还是要有点油 没得油在上面不好吃

0:00:23.541,0:00:25.472
我们这个肥肠我以前做过实验的

0:00:25.472,0:00:29.720
反正这十斤肥肠处理得干干净净的出来的话只有三斤半

0:00:33.115,0:00:34.567
抓住它就把它撕掉了

0:00:39.547,0:00:41.398
 肥肠鱼这个菜特别香

0:00:41.944,0:00:44.260
煮出来的话比单纯的水煮鱼要香

0:00:44.274,0:00:46.165
但是处理这个肥肠是很麻烦的

0:00:47.190,0:00:49.414
有好多都喜欢吃这个东西

0:00:49.427,0:00:51.585
吃这个东西就是麻烦得很

0:00:52.809,0:00:56.364
现在我们这个肥肠直接倒到里面加一大把盐

0:00:57.669,0:00:59.547
然后再倒一点这个白醋

0:01:00.652,0:01:01.491
陈醋也可以

0:01:01.531,0:01:03.195
但是陈醋有那个颜色

0:01:03.901,0:01:06.138
先给它来初洗几遍

0:01:11.398,0:01:15.006
我们直接先把这个肥肠抓到非常粘手

0:01:15.019,0:01:16.564
把它的那个黏液抓出来

0:01:16.564,0:01:19.840
然后再用大量的清水把它清洗干净

0:01:30.106,0:01:31.663
多洗几遍这个大肠

0:01:42.303,0:01:44.274
好 我们开始腌这个肥肠

0:01:45.366,0:01:46.324
先倒点白酒

0:01:50.013,0:01:51.664
然后还是再放点盐

0:01:52.143,0:01:53.004
少一点这次就

0:01:54.101,0:01:55.885
然后我们倒一点这个小苏打

0:01:56.870,0:01:58.375
大约倒个10多克吧

0:01:59.693,0:02:00.745
然后给它抓一下

0:02:01.105,0:02:05.472
加小苏打进去的话就是为了破坏这个肥肠的肌纤维

0:02:05.472,0:02:09.786
让它可以在短时间可以把它煮熟 煮来咬得动

0:02:11.238,0:02:15.472
如果你们喜欢吃一点都没有油的肥肠

0:02:16.005,0:02:19.494
用完小苏打抓完之后再来撕这个油

0:02:19.693,0:02:23.515
可以把油撕得干干净净的 一点都可以不用留下

0:02:25.379,0:02:27.976
你这个油不要撕干净很了 留点在上面

0:02:27.976,0:02:29.480
不是不好吃 没得油气得

0:02:30.572,0:02:31.078
是不哦

0:02:31.225,0:02:31.704
是啊

0:02:31.810,0:02:32.330
要得

0:02:33.515,0:02:37.629
过于撕干净很了还有点朦朦 有啥子吃头呢

0:02:39.547,0:02:42.077
好 那我们这个就不撕那么干净

0:02:42.862,0:02:45.286
就这样吧 现在我去杀鱼

0:02:46.338,0:02:47.430
让它腌一会儿

0:02:58.535,0:03:01.890
热了点吃这个吃起你害不害怕上火哦

0:03:02.583,0:03:07.523
哎呀 反正上火的（食材）少整点在里头 这天气大了

0:03:13.515,0:03:16.284
这点鱼片硬是拿给你片得好

0:03:18.202,0:03:18.894
一般

0:05:55.837,0:05:57.610
好了 我们这个肥肠就煮好了

0:05:58.377,0:05:59.402
煮好了之后

0:05:59.573,0:06:01.024
因为我们加了小苏打

0:06:01.120,0:06:04.449
现在我们这个肥肠用手都可以掐得穿 你看

0:06:05.133,0:06:09.167
然后我们把剩下的这个肥肠斩成小块

0:06:12.529,0:06:12.988
好

0:06:13.959,0:06:14.706
诶呀 好多哦

0:06:16.456,0:06:18.185
下面我们就可以直接煮鱼了

0:06:22.200,0:06:25.159
锅中加入适量的菜籽油

0:06:27.225,0:06:28.772
少倒点诶

0:06:29.871,0:06:30.448
安

0:06:30.480,0:06:31.750
倒好多油哦

0:06:32.155,0:06:32.796
不得多

0:06:35.931,0:06:41.475
 油温5成热之后加入切好的姜蒜泡椒末   

0:06:43.005,0:06:46.269
再加入红油豆瓣酱炒香炒出红油

0:06:51.502,0:06:55.751
然后将切好的火锅底料下锅炒香炒化

0:06:59.792,0:07:04.093
底料炒香之后加入腌制好的鱼骨头

0:07:09.222,0:07:13.316
鱼骨头炒香之后加入适量的清水

0:07:15.600,0:07:20.200
然后将准备好的配菜下锅

0:07:30.149,0:07:32.694
锅中加入食用盐2勺

0:07:34.925,0:07:36.894
 鸡精2勺

0:07:39.186,0:07:41.243
白糖1小勺

0:07:41.813,0:07:44.145
适量的胡椒粉

0:07:58.900,0:08:02.500
配菜煮好之后捞出倒入盆中垫底备用

0:08:07.096,0:08:10.496
然后将处理好的肥肠下锅

0:08:19.276,0:08:23.176
将腌制好的鱼片依次下入锅中

0:08:42.008,0:08:47.008
将煮熟的肥肠和鱼片捞出倒入盆中

0:08:53.800,0:08:57.300
再把烧开得汤汁倒入盆中

0:09:00.200,0:09:02.100
下一步开始泼油

0:09:05.500,0:09:07.600
锅中加入适量的菜籽油

0:09:23.200,0:09:26.400
油温4成热之后加入青花椒和姜蒜末

0:09:36.900,0:09:40.496
然后将爆香的配料均匀的泼在鱼片上面

0:09:41.546,0:09:42.860
撒点葱花就可以吃了

0:09:47.902,0:09:48.877
好 可以了

0:09:49.131,0:09:50.154
四伯爷 尝哈看

0:09:50.154,0:09:50.911
告哈看嘛

0:09:50.974,0:09:51.694
看好不好吃

0:09:51.694,0:09:52.415
你吃肥肠嘛

0:09:52.521,0:09:55.148
我吃肥肠 我喜欢吃这个

0:09:58.813,0:10:00.958
嗯 好吃

0:10:00.958,0:10:01.406
入不入味

0:10:01.440,0:10:02.266
入了味的

0:10:06.843,0:10:07.457
伯娘

0:10:08.474,0:10:10.953
好吃 我不敢吃肥肠

0:10:11.249,0:10:12.499
我吃块鱼

0:10:12.499,0:10:16.292
这个没斩断 连起滴滴儿的

0:10:20.720,0:10:23.453
嗯 这个鱼好嫩哦

0:10:24.110,0:10:26.080
跟我上次做的差不多撒

0:10:26.631,0:10:29.351
这个还好干（吃）点

0:10:29.406,0:10:29.934
还好吃点

0:10:29.934,0:10:30.226
是不哦

0:10:30.464,0:10:30.696
嗯

0:10:30.880,0:10:31.636
这回做的好吃点啊

0:10:31.865,0:10:33.473
这回做的还比头回好干

0:10:37.140,0:10:40.396
上一次我跟我四伯做了一次水煮鱼片

0:10:40.602,0:10:41.520
水煮鱼

0:10:42.400,0:10:43.746
  因为上一次没有加肥肠

0:10:43.818,0:10:47.046
这一次加肥肠煮完了之后这个汤特别香

0:10:47.999,0:10:49.680
安逸 好吃

0:10:51.009,0:10:52.213
来得到火 这个菜

0:10:55.009,0:10:55.736
肥肠鱼

0:10:56.025,0:10:56.388
嗯

0:10:57.379,0:10:58.959
头次的没有加肥肠的嘛

0:10:59.009,0:10:59.435
嗯

0:11:01.216,0:11:04.476
现在这个鱼才安逸哟我给你说

0:11:04.614,0:11:06.169
嘿嘿 多吃点撒

0:11:06.883,0:11:09.065
这个鱼是最安逸的吃起

0:11:11.072,0:11:11.974
肥肠你都咬得动啊

0:11:12.188,0:11:12.601
咬得动

0:11:12.965,0:11:15.084
是啊 咋个整的哦

0:11:15.761,0:11:16.877
咋个整的

0:11:17.805,0:11:19.385
加了那个小苏打

0:11:19.761,0:11:20.300
哦

0:11:24.288,0:11:27.134
如果没有小苏打的话可以加点食用碱

0:11:29.868,0:11:31.511
好了 本期视频就先到这里 

0:11:32.476,0:11:33.567
我还有几个菜要炒

0:11:34.996,0:11:36.363
你去炒你的嘛 我干我的

0:11:36.363,0:11:37.454
诶呀 我尽（全部）干

0:11:38.461,0:11:39.059
我等一哈（吃）


```

**Comment by Kevinzheng5** [comment]
认领

**Comment by Kevinzheng5** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：川渝爆款“肥肠鱼”的做法，鱼和肥肠的美味兼得，真的过瘾！
Chef Wang shares with you: Popular dish in Sichuan and Chongqing “Fish with Pork Intestine”. Enjoy the fish and intestine at the same time. So good!

简介
朋友们好，今天和大家分享一道“肥肠鱼”， 顾名思义，这道菜的主料就是肥肠和鱼，将两种看起来非常不一样的食材完美的融合。这样做出来的肥肠鱼色香味俱全，肥肠软嫩，鱼肉细腻嫩滑，并且香辣麻特别突出，简直就是四川人最喜爱的味道。并且一锅将鱼和肥肠兼得，快乐就是这么简单，一道好菜即可！
Hi everyone, today I’m going to share a dish “Fish with Pork Intestine”. As its name says, the major ingredients are the pork intestine and fish. The dish looks great, smells delicious and tastes amazing. The intestine is soft and juicy and the fish is smooth and tender. The spicy taste and savory stands out as the most beloved Sichuan style. Enjoy the fish and pork intestine in the same dish! 

字幕
0:00:00.266,0:00:00.998
嗨喽大家好
Hi guys

0:00:01.171,0:00:05.392
今天我伯爷去卖肉 剩了一个
Today my uncle went selling pork and there left a…

0:00:05.552,0:00:06.511
不是剩噶 留噶
Not left, you saved this one, huh?

0:00:06.511,0:00:07.909
专门给你留的
Just for you

0:00:08.042,0:00:09.387
留了一笼这个肥肠
A basket of intestines

0:00:09.786,0:00:13.288
所以我在想这个肥肠平时我们炒啊烧啊
Usually we stir fry it or sauté it

0:00:13.328,0:00:14.434
已经吃得有点腻了
And we got a bit tired of those

0:00:14.474,0:00:16.458
然后今天做一个肥肠鱼
So we’ll make a fish with pork intestine today

0:00:17.137,0:00:19.027
我把这个油啊这些把它撕完了要得不
Let’s rip off the fat from the intestine

0:00:19.547,0:00:22.077
还是要有点油 没得油在上面不好吃
Leave some fat on, otherwise it’s too dry

0:00:23.541,0:00:25.472
我们这个肥肠我以前做过实验的
I did experiments on the intestines before

0:00:25.472,0:00:29.720
反正这十斤肥肠处理得干干净净的出来的话只有三斤半
If you clean it really well, you get 3 pounds and a half out of 10 pounds

0:00:33.115,0:00:34.567
抓住它就把它撕掉了
You nip it and rip it off like this

0:00:39.547,0:00:41.398
 肥肠鱼这个菜特别香
The dish is really savory and delicious

0:00:41.944,0:00:44.260
煮出来的话比单纯的水煮鱼要香
More savory than the mere hot chili oil fish

0:00:44.274,0:00:46.165
但是处理这个肥肠是很麻烦的
But it’s really a hassle 

0:00:47.190,0:00:49.414
有好多都喜欢吃这个东西
Lots of people like pork intestines

0:00:49.427,0:00:51.585
吃这个东西就是麻烦得很
It just takes lots of time 

0:00:52.809,0:00:56.364
现在我们这个肥肠直接倒到里面加一大把盐
Now we pour the intestines here and season with salt

0:00:57.669,0:00:59.547
然后再倒一点这个白醋
Then some white vinegar

0:01:00.652,0:01:01.491
陈醋也可以
The brown vinegar can do it too

0:01:01.531,0:01:03.195
但是陈醋有那个颜色
Despite the color

0:01:03.901,0:01:06.138
先给它来初洗几遍
First we wash it a few times

0:01:11.398,0:01:15.006
我们直接先把这个肥肠抓到非常粘手
Until the intestines feel very sticky

0:01:15.019,0:01:16.564
把它的那个黏液抓出来
That’s the mucus coming out

0:01:16.564,0:01:19.840
然后再用大量的清水把它清洗干净
Then use a lot of water to clean it

0:01:30.106,0:01:31.663
多洗几遍这个大肠
Wash it for a few more times

0:01:42.303,0:01:44.274
好 我们开始腌这个肥肠
Alright, let’s marinate the intestines

0:01:45.366,0:01:46.324
先倒点白酒
Some baijiu

0:01:50.013,0:01:51.664
然后还是再放点盐
Then some salt again

0:01:52.143,0:01:53.004
少一点这次就
A little bit less this time

0:01:54.101,0:01:55.885
然后我们倒一点这个小苏打
Then some baking soda

0:01:56.870,0:01:58.375
大约倒个10多克吧
About 10 grams or so (half an ounce)

0:01:59.693,0:02:00.745
然后给它抓一下
Then mix it well

0:02:01.105,0:02:05.472
加小苏打进去的话就是为了破坏这个肥肠的肌纤维
The soda is to break the intestine muscle fibers

0:02:05.472,0:02:09.786
让它可以在短时间可以把它煮熟 煮来咬得动
To make it cooked in less time and has a soft texture

0:02:11.238,0:02:15.472
如果你们喜欢吃一点都没有油的肥肠
If you prefer lean intestines

0:02:16.005,0:02:19.494
用完小苏打抓完之后再来撕这个油
Season with baking soda and then rip the fat off

0:02:19.693,0:02:23.515
可以把油撕得干干净净的 一点都可以不用留下
Then we can rip the fat completely off

0:02:25.379,0:02:27.976
你这个油不要撕干净很了 留点在上面
Leave some on

0:02:27.976,0:02:29.480
不是不好吃 没得油气得
Otherwise there’s no creamy taste

0:02:30.572,0:02:31.078
是不哦
Right?

0:02:31.225,0:02:31.704
是啊
Yeah

0:02:31.810,0:02:32.330
要得
Alright then

0:02:33.515,0:02:37.629
过于撕干净很了还有点朦朦 有啥子吃头呢
Too lean makes it dry

0:02:39.547,0:02:42.077
好 那我们这个就不撕那么干净
Alright then we’ll leave some fat on

0:02:42.862,0:02:45.286
就这样吧 现在我去杀鱼
This should be good. Now let’s prepare the fish

0:02:46.338,0:02:47.430
让它腌一会儿
Marinate the intestines for a while

0:02:58.535,0:03:01.890
热了点吃这个吃起你害不害怕上火哦
Isn’t the weather a little bit warm for the dish?

0:03:02.583,0:03:07.523
哎呀 反正上火的（食材）少整点在里头 这天气大了
Make it less spicy for the weather then

0:03:13.515,0:03:16.284
这点鱼片硬是拿给你片得好
The fish is filleted so well

0:03:18.202,0:03:18.894
一般
It’s okay

0:05:55.837,0:05:57.610
好了 我们这个肥肠就煮好了
Alright now the intestines are cooked

0:05:58.377,0:05:59.402
煮好了之后
After it’s done

0:05:59.573,0:06:01.024
因为我们加了小苏打
Because the soda in it

0:06:01.120,0:06:04.449
现在我们这个肥肠用手都可以掐得穿 你看
We can poke it through with our fingers

0:06:05.133,0:06:09.167
然后我们把剩下的这个肥肠斩成小块
We cut the intestines to little pieces

0:06:12.529,0:06:12.988
好
Like this

0:06:13.959,0:06:14.706
诶呀 好多哦
It’s a lot

0:06:16.456,0:06:18.185
下面我们就可以直接煮鱼了
Now we can cook the fish

0:06:22.200,0:06:25.159
锅中加入适量的菜籽油
Canola oil in the wok

0:06:27.225,0:06:28.772
少倒点诶
Hey, not that much

0:06:29.871,0:06:30.448
安
Okay

0:06:30.480,0:06:31.750
倒好多油哦
That’s so much oil

0:06:32.155,0:06:32.796
不得多
It’s okay

0:06:35.931,0:06:41.475
 油温5成热之后加入切好的姜蒜泡椒末
Bring the oil to about 150 degrees C(300 F) and add the chopped green onions, ginger and pickled chili     

0:06:43.005,0:06:46.269
再加入红油豆瓣酱炒香炒出红油
Then some chili oil doubanjiang and stir fry the red chili oil out

0:06:51.502,0:06:55.751
然后将切好的火锅底料下锅炒香炒化
Add the sliced hot pot soup base and stir fry 

0:06:59.792,0:07:04.093
底料炒香之后加入腌制好的鱼骨头
After the aroma comes out, add the marinated fish bones

0:07:09.222,0:07:13.316
鱼骨头炒香之后加入适量的清水
Stir fry the fish bones and add some water

0:07:15.600,0:07:20.200
然后将准备好的配菜下锅
Then add the other ingredients

0:07:30.149,0:07:32.694
锅中加入食用盐2勺
Two spoons of salt

0:07:34.925,0:07:36.894
 鸡精2勺
Two spoons of chicken bouillon powder

0:07:39.186,0:07:41.243
白糖1小勺
One spoon of sugar

0:07:41.813,0:07:44.145
适量的胡椒粉
Some pepper

0:07:58.900,0:08:02.500
配菜煮好之后捞出倒入盆中垫底备用
Boil the ingredients and lay them on the bottom of the bowl

0:08:07.096,0:08:10.496
然后将处理好的肥肠下锅
Intestines in the wok

0:08:19.276,0:08:23.176
将腌制好的鱼片依次下入锅中
Then the marinated fish fillets

0:08:42.008,0:08:47.008
将煮熟的肥肠和鱼片捞出倒入盆中
Boil the intestines and fish, then get them out in the bowl

0:08:53.800,0:08:57.300
再把烧开得汤汁倒入盆中
Bring the sauce to boil and pour in the bowl

0:09:00.200,0:09:02.100
下一步开始泼油
Then let’s splash oil on the dish

0:09:05.500,0:09:07.600
锅中加入适量的菜籽油
Canola oil in the wok

0:09:23.200,0:09:26.400
油温4成热之后加入青花椒和姜蒜末
Bring it to about 120 degrees Celsius (250 F) and add the green peppercorn, ginger and garlic

0:09:36.900,0:09:40.496
然后将爆香的配料均匀的泼在鱼片上面
Then splash the oil evenly on the fish

0:09:41.546,0:09:42.860
撒点葱花就可以吃了
Splash some green onions and it’s ready

0:09:47.902,0:09:48.877
好 可以了
Alright

0:09:49.131,0:09:50.154
四伯爷 尝哈看
Uncle, have a try

0:09:50.154,0:09:50.911
告哈看嘛
Come on

0:09:50.974,0:09:51.694
看好不好吃
Have a taste

0:09:51.694,0:09:52.415
你吃肥肠嘛
Do you like intestines?

0:09:52.521,0:09:55.148
我吃肥肠 我喜欢吃这个
Yes, I do

0:09:58.813,0:10:00.958
嗯 好吃
It’s good

0:10:00.958,0:10:01.406
入不入味
Is the taste inside?

0:10:01.440,0:10:02.266
入了味的
Yes it is

0:10:06.843,0:10:07.457
伯娘
Auntie

0:10:08.474,0:10:10.953
好吃 我不敢吃肥肠
Smells good but I don’t eat intestines

0:10:11.249,0:10:12.499
我吃块鱼
Let me have a piece of fish

0:10:12.499,0:10:16.292
这个没斩断 连起滴滴儿的
This one wasn’t cut

0:10:20.720,0:10:23.453
嗯 这个鱼好嫩哦
The fish has such a juicy texture

0:10:24.110,0:10:26.080
跟我上次做的差不多撒
Like the one I made last time

0:10:26.631,0:10:29.351
这个还好干（吃）点
This one is even better

0:10:29.406,0:10:29.934
还好吃点
Yeah it’s a little better

0:10:29.934,0:10:30.226
是不哦
Serious?

0:10:30.464,0:10:30.696
嗯
Yeah

0:10:30.880,0:10:31.636
这回做的好吃点啊
Better this time

0:10:31.865,0:10:33.473
这回做的还比头回好干
I can have more this time

0:10:37.140,0:10:40.396
上一次我跟我四伯做了一次水煮鱼片
I made my uncle some red chili oil fish last time

0:10:40.602,0:10:41.520
水煮鱼
Red chili oil fish

0:10:42.400,0:10:43.746
  因为上一次没有加肥肠
And we didn’t have intestines the last time

0:10:43.818,0:10:47.046
这一次加肥肠煮完了之后这个汤特别香
The soup is extra delicious this time with the intestines

0:10:47.999,0:10:49.680
安逸 好吃
Nice! Delicious!

0:10:51.009,0:10:52.213
来得到火 这个菜
This dish is nice

0:10:55.009,0:10:55.736
肥肠鱼
Fish with pork intestines

0:10:56.025,0:10:56.388
嗯
Right

0:10:57.379,0:10:58.959
头次的没有加肥肠的嘛
We missed the intestines last time

0:10:59.009,0:10:59.435
嗯
Yeah

0:11:01.216,0:11:04.476
现在这个鱼才安逸哟我给你说
This dish is the one. So nice

0:11:04.614,0:11:06.169
嘿嘿 多吃点撒
Haha, have some more

0:11:06.883,0:11:09.065
这个鱼是最安逸的吃起
So nice!

0:11:11.072,0:11:11.974
肥肠你都咬得动啊
Can you chew the intestines?

0:11:12.188,0:11:12.601
咬得动
Yeah

0:11:12.965,0:11:15.084
是啊 咋个整的哦
How did you cook it so well?

0:11:15.761,0:11:16.877
咋个整的
The trick is

0:11:17.805,0:11:19.385
加了那个小苏打
the baking soda

0:11:19.761,0:11:20.300
哦
Oh

0:11:24.288,0:11:27.134
如果没有小苏打的话可以加点食用碱
If you don’t have baking soda around, use the soda ash

0:11:29.868,0:11:31.511
好了 本期视频就先到这里
Alright, that’s it for this episode

0:11:32.476,0:11:33.567
我还有几个菜要炒
I need to make a few other dishes

0:11:34.996,0:11:36.363
你去炒你的嘛 我干我的
You go ahead. I eat my own

0:11:36.363,0:11:37.454
诶呀 我尽（全部）干
Aha I can finish the dish

0:11:38.461,0:11:39.059
我等一哈（吃）
I’ll wait a second on that
