### ISSUE TITLE
[华农兄弟] 华农兄弟这只鸭整天幸灾乐祸这样下去不行的拿去河烤了 - https://youtu.be/l-pWz9p7AvU

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1022]
https://youtu.be/l-pWz9p7AvU
<p>&#35270;&#39057;&#21457;&#24067;&#20110; May 9, 2020 at 11:39AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/l-pWz9p7AvU

#华农兄弟：这只鸭整天“幸灾乐祸”，这样下去不行的，拿去河边烤了
#Huanong Brothers: This duck is always showing its Schadenfreude. This will be a problem. Let
s grill it on the riverside.

0:00:00.560,0:00:01.100
# 大家好
Hi everyone!

0:00:01.760,0:00:04.800
# 剛好今天天氣比較好哦  我去看一下那個鴨子
The weather today is much better. Let's have a look at the ducks.

0:00:05.320,0:00:06.020
# 在上面一點
They're up there.

0:00:06.700,0:00:07.580
# 看它們過的好不好
Let's see if they're happy with their new life here.

0:00:19.000,0:00:19.600
# 你看
Look!

0:00:20.060,0:00:20.700
# 那個鴨子
That duck,

0:00:21.280,0:00:23.220
# 上次我抓鵝的時候  它老是笑我
it kept laughing at me when I was catching the goose last time.

0:00:23.440,0:00:23.940
# 你看
Look!

0:00:24.200,0:00:24.940
# 現在還在笑
It's still laughing now.

0:00:30.520,0:00:31.220
# 抓隻過來
Let me catch one.

0:01:32.000,0:01:32.620
# 還笑
Are you still laughing?

0:01:33.760,0:01:34.980
# 等下讓你笑不出來
I'm gonna put an end to your laughter very soon.

0:01:40.140,0:01:40.840
# 這鴨子
This duck,

0:01:41.840,0:01:43.120
# 上次我買回來都胖的
It was fatter when I bought it,

0:01:43.360,0:01:44.080
# 很胖的哦
very fat, you know.

0:01:44.540,0:01:45.700
# 現在都瘦了一點
And it gets a bit skinny now.

0:01:48.120,0:01:48.640
# 鴨子
Ducky!

0:01:49.660,0:01:51.300
# 小鴨子  上次我抓鵝的時候
Ducky, you didn't stop laughing,

0:01:52.600,0:01:53.920
# 你一直在笑是不是
when I was catching the goose last time, did you?

0:01:55.220,0:01:56.240
# 你笑鴨還是笑我
Were you laughing at the goose or at me?

0:01:59.780,0:02:01.140
# 今天就輪到你啦
It's your turn today.

0:02:02.400,0:02:03.360
# 走  帶你去
Go! Come with me!

0:02:04.140,0:02:04.900
# 帶你去河邊
Come with me to the riverside!

0:02:17.580,0:02:19.120
# 明天就把你宰啦
You'll be my dish tomorrow.

0:02:20.460,0:02:21.240
# 不叫的
It's not yelping.

0:02:22.820,0:02:24.460
# 騙了那麼久都不肯叫的
I've spent so much time deceiving it, but it doesn't yelp.

0:02:32.660,0:02:33.880
# 是不是聲音叫的不夠大
Is it because my yelp is not loud enough?

0:02:58.060,0:02:58.720
# 這鴨子
This duck,

0:02:59.620,0:03:00.260
# 宰好啦
has now been processed.

0:03:00.840,0:03:03.240
# 好像有點毛  可能有點毛有點多
There seems to be some feather. Perhaps a bit, it has a bit more feather.

0:03:03.800,0:03:04.300
# 沒事
No worries.

0:03:04.740,0:03:06.740
# 等下烤一下烤一下這個毛就把它烤掉啦
When we grill it, grill it, the feather will be burnt away.

0:03:09.320,0:03:09.940
# 不介意
I don't mind.

0:03:10.500,0:03:11.300
# 你看這是
Look! It is,

0:03:12.200,0:03:12.880
# 幾個月的
a couple of months old.

0:03:13.780,0:03:15.320
# 年齡不是很大  這鴨子
It's not very old, this duck.

0:03:15.880,0:03:16.500
# 應該很嫩
It should be very tender.

0:03:19.500,0:03:20.780
# 帶你去河邊
I'm taking you to the riverside.

0:03:21.080,0:03:21.800
# 然後烤了
And then have you grilled.

0:03:55.800,0:03:56.940
# 這個要挖個洞
I gotta dig a hole here.

0:04:21.660,0:04:22.360
# 差不多了
It should be fine.

0:04:22.820,0:04:23.840
# 就是這個模型
That's exactly the model I want.

0:04:34.380,0:04:35.660
# 再把這個堆高一點
I'm making it higher.

0:04:36.640,0:04:37.380
# 然後才能
Then I can...

0:04:49.320,0:04:51.200
# 這種小石扔到下面去
I throw these small rocks to the bottom,

0:04:51.780,0:04:52.960
# 填一下這個小洞
to fill this small hole.

0:05:02.920,0:05:03.420
# 你看
Look!

0:05:04.080,0:05:05.040
# 現在就像樣了
It now looks like what it should be.

0:05:06.000,0:05:06.820
# 就直接這樣子搞
Then we can start right away.

0:05:11.880,0:05:12.780
# 把火生在這裡
I'll set the fire here.

0:05:14.120,0:05:14.620
# 然後
Then,

0:05:15.820,0:05:16.320
# 這
this one...

0:05:17.480,0:05:18.640
# 你看  還可以這樣子
Look! I can even put it here.

0:05:23.880,0:05:24.800
# 絕對OK
Absolutely OK!

0:05:28.820,0:05:29.980
# 怎麼還會不雨的
Why is it still raining?

0:05:55.080,0:05:56.220
# 再  加一把火
Let me, light it up once more.

0:06:11.820,0:06:13.360
# 先把這個鴨子清理一下
I'll clear the guts from the duck first.

0:06:35.640,0:06:36.480
# 加點料酒
Put some cooking wine.

0:06:38.600,0:06:39.540
# 來 喝點酒
C'mon! Have some wine!

0:06:40.240,0:06:40.840
# 沒那麼痛苦
You're gonna feel less pain.

0:06:45.380,0:06:46.780
# 料酒先放旁邊
Put the cooking wine aside first.

0:06:47.560,0:06:48.240
# 再搞點
Let's also have some,

0:06:48.900,0:06:49.580
# 這葱
spring onions.

0:06:50.820,0:06:52.740
# 去兄弟家  路過兄弟家的菜地
We went to, we passed by our buddy's veggie farm.

0:06:53.360,0:06:54.560
# 拔了兩根葱下來
So we've taken some spring onions there.

0:07:01.360,0:07:03.260
# 這個是  這個是油哦
This is, this is oil.

0:07:04.300,0:07:05.040
# 搞點油給你
Let me give you some oil.

0:07:12.720,0:07:13.840
# 再搞點鹽
And also some, salt

0:07:17.020,0:07:17.600
# 夠了
Enough!

0:07:18.700,0:07:19.420
# 加點醬油
Put some soy sauce.

0:07:26.000,0:07:26.540
# 好啦
Alright!

0:07:27.020,0:07:27.640
# 薑呢
Where's the ginger?

0:07:28.580,0:07:29.080
# 沒有帶
I didn't bring it?

0:07:31.620,0:07:32.180
# 好啦
Fine!

0:07:35.340,0:07:35.920
# 辣椒
Chilli

0:07:38.360,0:07:39.280
# 辣椒裡面有薑  (註︰其實我聽到他說「辣醬」的)
There's ginger in the chilli sauce.

0:07:40.080,0:07:41.040
# 薑都忘記帶了
I've even forgotten to bring ginger.

0:07:41.240,0:07:42.500
# 這辣椒裡面有薑哦
The's ginger in this chilli sauce.

0:07:43.760,0:07:44.540
# 來 搞點來
Alright! Put some here.

0:07:45.700,0:07:46.260
# 太多啦
Too much!

0:07:53.180,0:07:55.140
# 要腌一下啊  給它洗一下
It needs to be marinated. Let me give it a bath.

0:08:04.000,0:08:04.700
# 舒服吧
Cool, isn't it?

0:08:05.820,0:08:06.500
# 給你洗個
I'm giving you a,

0:08:07.320,0:08:08.040
# 洗個澡
giving you a bath.

0:08:13.020,0:08:13.680
# 就讓它這樣
So I just leave it here,

0:08:14.180,0:08:14.920
# 先腌一下
and marinate it for a while first.

0:08:17.600,0:08:18.300
# 太熱啦
It's too hot.

0:08:18.780,0:08:20.280
# 我去搞根那個  竹竹同
I'm gonna make a, you know, a bamboo bucket.

0:08:21.000,0:08:21.580
# 喝一下這個
And have some,

0:08:22.120,0:08:22.820
# 肥仔快樂水
Chubby Happy Drink.

0:08:35.300,0:08:37.200
# 誒 刀都搞  搞壞啦
Aya! It, it broke my knife.

0:08:48.400,0:08:50.240
# 生活需要儀式感  (註︰這句話出處是<<小王子>>，我見一般的引用都是法語原文，而且使用法語也突顯他突然引經據典的語調變化)
Il faut des rites, dit le renard.

0:08:50.740,0:08:51.760
# 這就是儀式感
Et nous disons, c'est notre rite.

0:08:55.840,0:08:56.500
# 誒呀
Aya!

0:09:13.260,0:09:14.040
# 再來一杯
One more!

0:09:30.080,0:09:30.940
# 好爽啊
So cool!

0:09:37.100,0:09:37.660
# 好啦
Alright!

0:09:40.780,0:09:42.140
# 嘿  你看它動不了啦
Hay! Look! It can no longer move now.

0:09:58.000,0:09:59.120
# 沒個水車做得好
This waterwheel is really well made.

0:10:17.820,0:10:19.260
# 剛才在我們那邊找了一個這個
I've just discovered this funny thing at our site.

0:10:20.420,0:10:22.320
# 還沒用過這個呢  這個噴油的
I've never tried it before. It's for spraying oil.

0:10:23.340,0:10:24.740
# 哎呀  用了就更靚
Aya! It makes the duck much more beautiful!

0:11:29.060,0:11:30.620
# 你看  這是草珠子哦  你看  (註︰不知是甚麼，照字面翻譯)
Look! This is a grass bead, look!

0:11:32.940,0:11:35.500
# 它長在這裡  從上游沖下游長到這裡
It's growing here. It was washed here from the upstream and it's rooted here now.

0:11:36.380,0:11:36.880
# 壓起來
Stabilize it.

0:11:37.020,0:11:38.560
# 壓下這裡會長起來的
It will grow if it's stabilized here.

0:11:43.100,0:11:45.000
# 愛護植物  人人有責
Taking care of plants is a responsibility of everyone.

0:11:54.160,0:11:55.360
# 要尊重生命
We need to pay respect to lives.

0:12:53.100,0:12:54.220
# 搞個雞翅來吃  (註︰與上次指鵝為鴨一樣，這次指鴨為雞同樣不澄清)
Let me get a chicken wing.

0:12:56.800,0:12:57.580
# 熟啦熟啦
It's done, it's done.

0:13:05.880,0:13:06.700
# 夾著來
I got it.

0:13:12.340,0:13:13.960
# 嗯  好香啊
Um! It smells so good!

0:13:21.660,0:13:22.980
# 哇  真的很好吃誒
Wa! It's really tasty!

0:13:24.020,0:13:24.760
# 不騙你們
No kidding.

0:13:35.260,0:13:36.300
# 有竹子的香味
There's the scent of bamboo.

0:13:38.300,0:13:39.760
# 這鴨子抱著竹子來烤
The duck was grabbing the bamboo when it was gilled.

0:13:40.860,0:13:41.440
# 嗯
Um!

0:13:42.540,0:13:43.560
# 味道真的不錯
It tastes really not bad.

0:14:02.520,0:14:04.140
# 就這樣站好哇  別動
Stand still here! Freeze!

0:14:06.820,0:14:07.660
# 不聽話
Naughty!

0:14:16.760,0:14:17.540
# 哇  真的
Wa! It's really...

0:14:18.760,0:14:19.660
# 現在放了辣椒
Now I've put some chilli,

0:14:20.700,0:14:21.200
# 有那
So there's,

0:14:21.560,0:14:22.420
# 辣椒的味道
the taste of chilli.

0:14:24.780,0:14:25.640
# 放的剛好夠辣
The spiciness of just right.

0:14:27.900,0:14:30.120
# 嗯  真的  這鴨子好吃
Um! Really, the duck is so tasty.

0:14:30.800,0:14:31.520
# 可能在我們
Perhaps we've,

0:14:33.540,0:14:34.980
# 在那個養殖場養了那麼久
we've been keeping it at our site for such a long time,

0:14:37.200,0:14:38.280
# 肉質全部改變啦
that the texture is completely changed.

0:14:40.440,0:14:41.180
# 完全
It's nothing,

0:14:42.980,0:14:44.400
# 完全不像買的鴨子一樣
nothing like a duck bought outside.

0:15:11.380,0:15:12.380
# 給它鬆綁
Let me untie it.

0:15:14.560,0:15:15.660
# 啊  你自由啦
Oh! You're free now

0:15:27.820,0:15:28.320
# 嗯~
Um~

0:15:29.700,0:15:30.200
# 乾啦
It's dried out.

0:15:31.900,0:15:32.800
# 拿回去餵小狗
I'll take back for the doggies.

0:15:41.040,0:15:43.120
# 好辣  攝影小哥肯定吃不了
It's so spicy! There's no way that Mr. Cameraman can stand it.

0:15:44.320,0:15:45.060
# 直接咬算了
So I'll just bite it right away.

0:15:48.860,0:15:49.360
# 你看
Look!

0:15:51.200,0:15:51.880
# 脆皮鴨
Crispy duck

0:15:57.540,0:15:58.180
# 嗯~
Um~

0:16:00.620,0:16:01.340
# 好香啊
It smells so good!

0:16:11.060,0:16:12.580
# 你看  全熟啦
Look! It's well done now.

0:16:19.200,0:16:19.720
# 好啦
Alright!

0:16:20.700,0:16:21.960
# 今天的視頻到這裡啦
The video ends here.

0:16:25.740,0:16:26.960
# 嗯  好辣
Um! It's really spicy.

0:16:31.340,0:16:32.180
# 滅一下火
Let's put out the fire.
