### ISSUE TITLE
【美食作家王刚】 百天宴 - https://youtu.be/V-7RL7nlcj0

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1024]
**视频链接**：https://youtu.be/V-7RL7nlcj0

视频时长6:36，预计发布时间为北京时间5月11日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
儿子满百天，一家人围满一桌吃饭庆祝，幸福莫过如此。在这里也祝大家平平安安，阖家幸福，厨艺精进！

简介
大家好，时间过的真快，一转眼沺沺的小弟弟都百天了，今天就来下厨给家人们做顿饭菜。孩子出生在疫情期间，其实感触颇多，意识到最重要的是家人，骨子里还是想要稳稳地幸福。在这里也真心祝福一直以来支持我的朋友们平平安安，阖家幸福，厨艺精进！

字幕
0:04:51.650,0:04:52.600
哈喽 大家好

0:04:52.656,0:04:56.328
今天我就放个假做一桌菜

0:04:57.038,0:04:58.478
大家一家人聚到一起

0:04:59.043,0:05:01.603
其实平时我老爸老妈跟我哥他们都在

0:05:01.621,0:05:03.125
只是他们不喜欢上镜而已

0:05:04.218,0:05:06.223
然后今天都上镜了

0:05:06.587,0:05:09.266
因为我们家小宝宝满100天

0:05:09.649,0:05:11.799
因为他满月的时候因为疫情嘛

0:05:11.799,0:05:14.578
所以也没有给他摆个酒什么的

0:05:14.633,0:05:17.248
今天简简单单的我们一家人吃个饭

0:05:18.341,0:05:19.107
来嘛 吃

0:05:20.200,0:05:21.248
来来来

0:05:25.612,0:05:26.387
来 干杯

0:05:27.298,0:05:28.619
我要吃多宝鱼

0:05:28.619,0:05:30.086
吃多宝鱼啊 来爸爸给你夹

0:05:30.314,0:05:31.772
你帮我夹个菜菜幺儿

0:05:38.578,0:05:39.471
人家家用大碗喝

0:05:40.993,0:05:42.150
还喝酒

0:05:43.708,0:05:44.339
来来来喝点酒

0:05:44.428,0:05:46.852
哦哟 这白酒哦 喝得不哦

0:05:49.840,0:05:50.496
喝酒喝酒

0:05:50.505,0:05:51.444
干杯干杯

0:05:53.111,0:05:55.216
那个酒没得味道的

0:05:59.927,0:06:01.321
来嘛 我们来喝一个

0:06:03.043,0:06:04.610
好不容易一起来上镜的

0:06:05.184,0:06:06.171
你们平时都不上镜

0:06:06.332,0:06:06.988
来嘛来嘛

0:06:08.537,0:06:10.757
干杯干杯

0:06:10.806,0:06:11.845
来干杯

0:06:15.872,0:06:16.729
要干哈 

0:06:29.526,0:06:30.485
 人家是水

0:06:32.439,0:06:33.410
慢点哦


```

**Comment by siyusun6918** [comment]
认领

**Comment by siyusun6918** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
儿子满百天，一家人围满一桌吃饭庆祝，幸福莫过如此。在这里也祝大家平平安安，阖家幸福，厨艺精进！
My son’s 100th-day celebration. The whole family celebrated together. Nothing is happier than this. I hope you and your family all be blessed with peace and happiness, and make progress in cooking skills!

简介
大家好，时间过的真快，一转眼沺沺的小弟弟都百天了，今天就来下厨给家人们做顿饭菜。孩子出生在疫情期间，其实感触颇多，意识到最重要的是家人，骨子里还是想要稳稳地幸福。在这里也真心祝福一直以来支持我的朋友们平平安安，阖家幸福，厨艺精进！
Hello! Time flies. Tiantian’s younger brother is 100 days old. Today, I will cook a meal for the family. He was born during the outbreak. I have a lots of deep feelings, which I realized family is the most important thing. In my bones, I want settled happiness. I truly wish friends who support me along the way be blessed with peace and happiness, and also make progress in cooking skills!

字幕
0:04:51.650,0:04:52.600
哈喽 大家好
Hello

0:04:52.656,0:04:56.328
今天我就放个假做一桌菜
I’m taking a break today and cooking a meal 

0:04:57.038,0:04:58.478
大家一家人聚到一起
The whole family gather here

0:04:59.043,0:05:01.603
其实平时我老爸老妈跟我哥他们都在
Actually my parent and my brother are usually around

0:05:01.621,0:05:03.125
只是他们不喜欢上镜而已
They just don’t like being on camera

0:05:04.218,0:05:06.223
然后今天都上镜了
And they are all on camera today 

0:05:06.587,0:05:09.266
因为我们家小宝宝满100天
Because it’s the 100th day since my baby was born

0:05:09.649,0:05:11.799
因为他满月的时候因为疫情嘛
When he was one month old 

0:05:11.799,0:05:14.578
所以也没有给他摆个酒什么的
We didn’t celebrate because of the outbreak 

0:05:14.633,0:05:17.248
今天简简单单的我们一家人吃个饭
Today, my whole family is going to eat together (to celebrate)

0:05:18.341,0:05:19.107
来嘛 吃
Come on, let’s eat 

0:05:20.200,0:05:21.248
来来来
Come on 

0:05:25.612,0:05:26.387
来 干杯
Come on, Cheers!

0:05:27.298,0:05:28.619
我要吃多宝鱼
I want to eat turbot

0:05:28.619,0:05:30.086
吃多宝鱼啊 来爸爸给你夹
You want turbot? Let me help you with that 

0:05:30.314,0:05:31.772
你帮我夹个菜菜幺儿
Can you help me get some of that dish, Yao er

0:05:38.578,0:05:39.471
人家家用大碗喝
They use big bowls for drinking 

0:05:40.993,0:05:42.150
还喝酒
Drink alcohol?

0:05:43.708,0:05:44.339
来来来喝点酒
Come on, let’s drink some 

0:05:44.428,0:05:46.852
哦哟 这白酒哦 喝得不哦
Oh this is Baijiu? I can’t handle it

0:05:49.840,0:05:50.496
喝酒喝酒
Let’s drink

0:05:50.505,0:05:51.444
干杯干杯
Cheers

0:05:53.111,0:05:55.216
那个酒没得味道的
That Baijiu doesn’t taste like alcohol

0:05:59.927,0:06:01.321
来嘛 我们来喝一个
Come on, raise your drinks 

0:06:03.043,0:06:04.610
好不容易一起来上镜的
Finally you are all on camera

0:06:05.184,0:06:06.171
你们平时都不上镜
You don’t usually on camera 

0:06:06.332,0:06:06.988
来嘛来嘛
Come on

0:06:08.537,0:06:10.757
干杯干杯
Cheers

0:06:10.806,0:06:11.845
来干杯
Cheers

0:06:15.872,0:06:16.729
要干哈 
Need to drink it all 

0:06:29.526,0:06:30.485
 人家是水
That’s water

0:06:32.439,0:06:33.410
慢点哦
Eat slowly
