### ISSUE TITLE
【美食作家王刚】茶叶蛋 - https://youtu.be/9hyV27g9YFk

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1025]
**视频链接**：https://youtu.be/9hyV27g9YFk

视频时长8:08，预计发布时间为北京时间5月12日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“茶叶蛋”的家常电饭锅做法，非常简单但味道很赞，推荐！

简介
大家好，四伯爷找出了家里被“遗忘”的一包红茶，直接喝茶可能味道不够好了，丢了有会觉得可惜，最好解决过期老茶叶的方法那莫过于做一锅茶叶蛋了，做法非常简单。在这里教大家一个小技巧，在煮茶叶蛋的时候加入一些可乐，除了代替白糖提鲜并且还可以有效的帮助蛋更快的入味，但不可以加入过多以免味道偏甜。

字幕
0:00:00.275,0:00:01.125
哈喽 大家好

0:00:01.400,0:00:05.925
我伯爷他从自己家里面搜了一包红茶茶叶出来

0:00:06.225,0:00:07.275
这是好久的茶叶哦

0:00:07.550,0:00:12.200
这包茶叶放在我的柜子里头我放忘记了

0:00:12.600,0:00:14.200
不晓得好久还有包茶叶

0:00:14.200,0:00:17.425
都三四年这包茶叶 不晓得发没发霉都不晓得

0:00:18.500,0:00:20.275
没有发霉 这个茶叶放了几年

0:00:20.475,0:00:22.775
应该是这个保存得好

0:00:22.775,0:00:23.800
这个包装好

0:00:23.800,0:00:25.441
嗯 这个包装不容易坏

0:00:25.800,0:00:26.875
搞忘记了

0:00:26.900,0:00:28.000
被遗忘的茶叶

0:00:28.050,0:00:32.175
今天我们用这个遗忘的茶叶来煮一碗这个茶叶蛋

0:00:32.400,0:00:34.825
然后今天我还准备了一个特殊的东西

0:00:34.825,0:00:36.350
加点可乐进去煮

0:00:37.175,0:00:37.869
吃过没有四伯爷

0:00:37.869,0:00:38.369
没有

0:00:38.705,0:00:40.482
我相信你吃过茶叶蛋 

0:00:40.482,0:00:41.503
茶叶蛋我是吃过

0:00:41.791,0:00:43.290
可乐茶叶蛋你没吃过噶

0:00:43.305,0:00:44.275
没有没有

0:00:44.275,0:00:44.559
好

0:00:45.584,0:00:47.317
那就准备哈这个

0:00:49.706,0:00:54.026
我们煮这个茶叶蛋 大家都是用铁锅进去煮

0:00:54.176,0:00:57.112
其实做茶叶蛋最好是用这个电饭锅

0:00:57.532,0:00:59.586
电饭锅做出来的茶叶蛋

0:00:59.820,0:01:02.536
因为它这个火力是比较均匀 

0:01:02.536,0:01:04.231
慢慢煮的 更加的入味

0:01:04.683,0:01:06.347
好 拿到那边去煮

0:01:06.745,0:01:07.790
我先把它煮熟

0:01:07.835,0:01:08.321
好

0:01:08.851,0:01:10.294
我先把蛋弄来煮了哈

0:01:10.397,0:01:10.957
要的

0:01:16.097,0:01:18.085
这个水刚好没过鸡蛋就可以了

0:01:20.486,0:01:22.488
等下我们的茶叶要用

0:01:22.562,0:01:25.434
你经常喝茶 你第一道茶是丢了的噶

0:01:25.611,0:01:27.414
第一道茶反正没得嫩好喝得

0:01:27.437,0:01:28.232
有点苦

0:01:28.453,0:01:29.838
二开茶是最安逸的

0:01:30.309,0:01:33.387
所以我们用茶叶也同样的道理

0:01:33.431,0:01:35.095
用第二泡来放进去煮

0:01:35.876,0:01:37.334
就是第一下放水

0:01:37.334,0:01:38.987
头一开茶

0:01:39.160,0:01:39.941
那个水不要

0:01:40.147,0:01:40.986
没得好好喝得

0:01:42.091,0:01:43.932
还有一个茶叶蛋不能多吃四伯爷

0:01:44.683,0:01:46.391
我少吃这个东西

0:01:46.480,0:01:46.995
嗯 是

0:01:47.334,0:01:49.072
所以这回都只煮了十多个安

0:01:49.072,0:01:49.558
嗯

0:01:50.250,0:01:52.356
那个茶叶蛋久不久（时不时）吃一回还是可以

0:01:52.488,0:01:53.107
多香噶

0:01:53.107,0:01:53.519
嗯

0:01:53.917,0:01:55.552
我们这个茶叶蛋不能多吃 

0:01:55.581,0:01:57.849
因为这个毕竟对身体不是特别好

0:01:58.910,0:02:01.296
好啦 现在我们这个蛋已经煮熟了

0:02:02.032,0:02:04.005
把它捞出来 过一下凉水

0:02:05.081,0:02:07.231
透一下凉水的话它就更好剥

0:02:09.278,0:02:11.369
好 现在我们稍微冰凉一下

0:02:11.855,0:02:13.490
轻轻地敲一下

0:02:18.085,0:02:20.014
好了 现在我们重新加水

0:02:22.223,0:02:24.197
这一次加的水可以稍微多一点点

0:02:27.039,0:02:28.821
然后放点这个香料

0:02:29.145,0:02:30.206
丢2颗八角

0:02:30.824,0:02:32.017
丢一小块桂皮

0:02:32.400,0:02:33.608
我们四川喜欢吃辣椒

0:02:33.608,0:02:36.067
就放几个干辣椒进去

0:02:36.966,0:02:38.114
再放两片香叶

0:02:39.190,0:02:40.692
然后加点老抽调色

0:02:42.930,0:02:45.846
调色我们先搅一下 看一下这个颜色怎么样

0:02:48.748,0:02:49.455
可以了

0:02:49.499,0:02:51.237
嗯 颜色没什么问题

0:02:51.929,0:02:53.843
好 现在我们来准备一下这个茶叶

0:02:54.359,0:02:55.184
好了吗

0:02:56.008,0:02:57.717
可以了可以了

0:02:58.291,0:03:01.148
这里大概只有10克都不到的样子

0:03:02.223,0:03:02.916
可以了

0:03:04.595,0:03:08.615
然后我们用这个开水 用八九十度的开水

0:03:08.895,0:03:13.328
给它泡一下 第一遍的不要

0:03:14.477,0:03:15.066
搅一下

0:03:15.478,0:03:17.393
你不盖着 第一轮它泡不到嘎

0:03:17.731,0:03:19.587
一会儿的 就是第一遍这个水不要

0:03:19.734,0:03:20.810
好 现在可以了

0:03:20.810,0:03:21.914
把这个茶叶加进去

0:03:26.288,0:03:28.144
好 最后我们来放点盐

0:03:28.542,0:03:30.397
盐的话可以稍微重一些

0:03:31.914,0:03:33.328
因为水也比较多嘛

0:03:35.169,0:03:36.995
最后我们来加点这个可乐

0:03:37.010,0:03:40.073
这个是上次做懒人排骨剩的是不

0:03:40.073,0:03:40.574
嗯

0:03:41.899,0:03:44.636
好了嘛 这个电饭锅都满了

0:03:44.636,0:03:46.229
好 稍微加一点

0:03:46.539,0:03:48.100
所以我们这个就不用加糖了

0:03:48.215,0:03:50.399
可乐里面都有一点甜味了

0:03:50.978,0:03:51.961
然后给它盖上

0:03:53.448,0:03:54.120
重新烧开

0:03:56.194,0:03:59.638
现在这烧开了之后  继续让它煮一会儿

0:04:00.117,0:04:02.007
煮完之后最重要的一个东西就是

0:04:02.301,0:04:05.434
让它浸泡 浸泡4个小时才更容易入味

0:04:06.997,0:04:07.383
四伯爷 

0:04:08.468,0:04:12.312
啷个嘛 还吃点可乐啊

0:04:12.886,0:04:13.299
啊

0:04:14.079,0:04:15.228
又在冒泡子了

0:04:15.935,0:04:17.496
哦哟

0:04:17.952,0:04:18.792
我喝这点

0:04:18.895,0:04:19.381
好

0:04:23.210,0:04:23.976
诶呀 安逸

0:04:25.287,0:04:25.817
可以嘎

0:04:25.920,0:04:26.391
好喝

0:04:28.483,0:04:31.620
现在我们这个茶叶蛋已经在这个电饭锅里面

0:04:31.782,0:04:33.796
用煨的方式 煮饭的方式

0:04:33.843,0:04:35.036
已经煮了40分钟了

0:04:35.508,0:04:39.160
这个时候我先拿2个我们吃一下来试哈看哈

0:04:39.322,0:04:40.044
可以安

0:04:40.088,0:04:41.575
这个颜色都出来了哒

0:04:41.752,0:04:42.857
剩下的继续

0:04:43.107,0:04:45.774
现在就把火关了 让它泡

0:04:45.774,0:04:46.907
再泡几个小时

0:04:47.452,0:04:48.056
尝一哈看嘛四伯爷

0:04:48.056,0:04:48.689
有点烫

0:04:51.045,0:04:52.047
诶呀 真的很烫

0:04:55.375,0:04:57.363
你看这样颜色都已经出来了

0:04:58.321,0:04:59.882
你看我这个才安逸

0:05:00.029,0:05:00.515
嗯

0:05:01.443,0:05:05.419
这个茶叶蛋就是现在还不是特别入味

0:05:05.949,0:05:07.054
好烫哦

0:05:07.422,0:05:08.365
我来给你弄

0:05:09.145,0:05:10.810
转到一哈就给它逮（剥）开了

0:05:13.343,0:05:14.933
给它滚一哈 自己就掉了

0:05:15.964,0:05:16.524
是不是

0:05:18.689,0:05:19.587
我先尝哈看

0:05:19.867,0:05:20.824
烫

0:05:24.359,0:05:25.360
等它冷哈都

0:05:25.640,0:05:27.054
太烫了

0:05:27.820,0:05:28.689
还可以

0:05:30.471,0:05:32.017
但是中间现在还没有味道

0:05:34.374,0:05:35.198
很香

0:05:35.832,0:05:37.599
闻起来已经有茶叶的香味 

0:05:37.628,0:05:41.045
已经有那个清香味了

0:05:41.163,0:05:42.842
但是说中间还没有入味

0:05:45.640,0:05:46.980
烫哦四伯爷

0:05:47.717,0:05:49.293
少少的吃撒

0:05:52.533,0:05:54.094
还没咋个入味

0:05:54.094,0:05:54.565
嗯

0:05:54.565,0:05:57.216
再隔几个小时来吃差不多

0:05:58.335,0:06:00.265
好 我们再等4个小时再来

0:06:00.265,0:06:02.002
现在已经 大家可以看一下

0:06:02.960,0:06:04.948
已经浸泡进去了

0:06:06.141,0:06:06.715
慢慢来

0:06:11.119,0:06:13.151
嗯 不要掉

0:06:31.892,0:06:35.674
现在我们这个鸡蛋 这个茶叶蛋

0:06:36.058,0:06:38.902
可乐茶叶蛋已经放了好几个小时了

0:06:39.731,0:06:41.097
现在捞一个出来

0:06:41.097,0:06:41.970
四伯爷你吃一个不

0:06:41.970,0:06:42.575
我不要

0:06:42.822,0:06:43.337
你不要啊

0:06:43.337,0:06:44.837
不要了 刚才吃了饭安

0:06:44.904,0:06:45.755
要的

0:06:46.271,0:06:47.981
我们这个是早上开始做的

0:06:47.981,0:06:49.858
现在已经到下午2点钟了

0:06:50.615,0:06:51.526
也应该入味了

0:06:51.981,0:06:53.047
我来尝哈就晓得了

0:06:53.512,0:06:54.697
好多个小时了嘛

0:06:55.137,0:06:57.153
你看 这个颜色的话就要比

0:06:57.458,0:06:58.851
这个颜色就变得多了

0:06:58.851,0:07:00.769
比上午更加要深一点

0:07:02.541,0:07:03.811
嗯 入味了现在

0:07:04.422,0:07:05.302
现在比较入味

0:07:09.004,0:07:09.786
不错不错

0:07:12.559,0:07:13.622
这个蛋我们捞出来吃

0:07:13.622,0:07:15.882
味道够了的时候就把蛋捞出来

0:07:17.825,0:07:19.975
捞出来就可以了 不用再继续泡了

0:07:20.818,0:07:22.711
然后这个汤汁的话

0:07:23.127,0:07:24.544
嗯 还可以卤一次

0:07:25.033,0:07:26.182
最好就不要超过3次

0:07:26.182,0:07:27.965
超过3次的话这个味道就不香了

0:07:31.545,0:07:33.365
但这个可能放不得哦噶

0:07:33.793,0:07:34.453
放不到好久

0:07:36.102,0:07:38.781
三两天可以放在冰箱头

0:07:38.781,0:07:40.158
最好是当天做当天吃

0:07:41.527,0:07:43.604
是整多了的话

0:07:43.604,0:07:44.300
煮多了的话 

0:07:44.312,0:07:46.817
放在保鲜室里头可能保一两天没得问题的哈

0:07:46.841,0:07:47.831
一两天没得问题的

0:07:48.931,0:07:51.679
好了 大家如果是想吃的话可以尝试一下

0:07:51.679,0:07:52.559
特别的简单

0:07:52.865,0:07:54.099
就跟懒人排骨一样

0:07:54.282,0:07:56.029
也不用加太多的东西

0:07:57.080,0:07:58.973
本期视频就到这里 拜拜

0:07:59.315,0:08:00.000
拜拜

0:08:03.237,0:08:04.679
真的可以你不要笑

0:08:05.229,0:08:05.876
吃一个嘛

0:08:06.328,0:08:07.367
我刚才吃了饭


```

**Comment by Summer0208** [comment]
认领

**Comment by Summer0208** [comment]
https://www.youtube.com/watch?v=9hyV27g9YFk&feature=youtu.be
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“茶叶蛋”的家常电饭锅做法，非常简单但味道很赞，推荐！
Chef Wang Gang shows you how to make tea eggs using instant pot. It’s easy but delicious, highly recommend! 
简介
大家好，四伯爷找出了家里被“遗忘”的一包红茶，直接喝茶可能味道不够好了，丢了有会觉得可惜，最好解决过期老茶叶的方法那莫过于做一锅茶叶蛋了，做法非常简单。在这里教大家一个小技巧，在煮茶叶蛋的时候加入一些可乐，除了代替白糖提鲜并且还可以有效的帮助蛋更快的入味，但不可以加入过多以免味道偏甜。
Hey guys, my uncle found a bag of forgotten black tea. it doesn’t taste good if we drink it directly. But it’s such a waste if we throw it away. the best solution is to use this black tea to make a pot of tea egg. Simple recipe. Here is a tip: add some coke while boiling the egg. It not only takes place of sugar, also helps the egg to get flavor faster. Don’t put too much or it will get over sweet though.   
字幕
0:00:00.275,0:00:01.125
哈喽 大家好
Hello guys, 
0:00:01.400,0:00:05.925
我伯爷他从自己家里面搜了一包红茶茶叶出来
My uncle found a bag of black tea at his house. 
0:00:06.225,0:00:07.275
这是好久的茶叶哦
How long have you put it?  
0:00:07.550,0:00:12.200
这包茶叶放在我的柜子里头我放忘记了
I've put it in the drawer and forgot about it. 
0:00:12.600,0:00:14.200
不晓得好久还有包茶叶
Don’t know how long there’s still a bag of tea. 
0:00:14.200,0:00:17.425
都三四年这包茶叶 不晓得发没发霉都不晓得
For about three or four years, I’m not sure if it gets moldy or not.  
0:00:18.500,0:00:20.275
没有发霉 这个茶叶放了几年
It’s not moldy. Although it’s been so long, 
0:00:20.475,0:00:22.775
应该是这个保存得好
it got well saved. 
0:00:22.775,0:00:23.800
这个包装好
The package is good. 
0:00:23.800,0:00:25.441
嗯 这个包装不容易坏
The package helps it to last longer. 
0:00:25.800,0:00:26.875
搞忘记了
I forgot about it. 
0:00:26.900,0:00:28.000
被遗忘的茶叶
A forgotten tea. 
0:00:28.050,0:00:32.175
今天我们用这个遗忘的茶叶来煮一碗这个茶叶蛋
Today, we are going to use this forgotten tea to make tea eggs.  
0:00:32.400,0:00:34.825
然后今天我还准备了一个特殊的东西
I prepared something special for today. 
0:00:34.825,0:00:36.350
加点可乐进去煮
I will put some coke to boil. 
0:00:37.175,0:00:37.869
吃过没有四伯爷
Have you tried it, uncle? 
0:00:37.869,0:00:38.369
没有
Nope. 
0:00:38.705,0:00:40.482
我相信你吃过茶叶蛋 
I know you have tea eggs before. 
0:00:40.482,0:00:41.503
茶叶蛋我是吃过
I had tea eggs. 
0:00:41.791,0:00:43.290
可乐茶叶蛋你没吃过噶
You never tried coke tea egg, though. 
0:00:43.305,0:00:44.275
没有没有
NO no no. 
0:00:44.275,0:00:44.559
好
Okay. 
0:00:45.584,0:00:47.317
那就准备哈这个
Let’s prepare for this, 
0:00:49.706,0:00:54.026
我们煮这个茶叶蛋 大家都是用铁锅进去煮
People usually use an iron pot to boil the tea egg. 
0:00:54.176,0:00:57.112
其实做茶叶蛋最好是用这个电饭锅
Actually, the best way is to use an instant pot. 
0:00:57.532,0:00:59.586
电饭锅做出来的茶叶蛋
The tea egg cooked by instant pot is, 
0:00:59.820,0:01:02.536
因为它这个火力是比较均匀 
the heats are more equal; 
0:01:02.536,0:01:04.231
慢慢煮的 更加的入味
slowly boiled, more flavor penetrated. 
0:01:04.683,0:01:06.347
好 拿到那边去煮
Okay, put it there to boil. 
0:01:06.745,0:01:07.790
我先把它煮熟
We hard boil it first. 
0:01:07.835,0:01:08.321
好
Right. 
0:01:08.851,0:01:10.294
我先把蛋弄来煮了哈
I boil the egg first. 
0:01:10.397,0:01:10.957
要的
Yes, 
0:01:16.097,0:01:18.085
这个水刚好没过鸡蛋就可以了
We need enough water to slightly cover the egg. 
0:01:20.486,0:01:22.488
等下我们的茶叶要用
We are going to use the tea...
0:01:22.562,0:01:25.434
你经常喝茶 你第一道茶是丢了的噶
You drink tea a lot, Do you drink the first drink?  
0:01:25.611,0:01:27.414
第一道茶反正没得嫩好喝得
The first drink doesn’t taste good.  
0:01:27.437,0:01:28.232
有点苦
It’s bitter. 
0:01:28.453,0:01:29.838
二开茶是最安逸的
The second drink is the most tasteful. 
0:01:30.309,0:01:33.387
所以我们用茶叶也同样的道理
So we are going to make this tea the same way, 
0:01:33.431,0:01:35.095
用第二泡来放进去煮
using the second drink. 
0:01:35.876,0:01:37.334
就是第一下放水

0:01:37.334,0:01:38.987
头一开茶
Throw the water
0:01:39.160,0:01:39.941
那个水不要
you put at the first. 
0:01:40.147,0:01:40.986
没得好好喝得
It’s not tasty. 
0:01:42.091,0:01:43.932
还有一个茶叶蛋不能多吃四伯爷
One more thing, don’t eat too much tea eggs, uncle. 
0:01:44.683,0:01:46.391
我少吃这个东西
I need to have it less. 
0:01:46.480,0:01:46.995
嗯 是
Right. 
0:01:47.334,0:01:49.072
所以这回都只煮了十多个安
So I only made about ten eggs. 
0:01:49.072,0:01:49.558
嗯
okay. 
0:01:50.250,0:01:52.356
那个茶叶蛋久不久（时不时）吃一回还是可以
It’s okay to have it once in a while. 
0:01:52.488,0:01:53.107
多香噶
It tastes good. 
0:01:53.107,0:01:53.519
嗯
yes. 
0:01:53.917,0:01:55.552
我们这个茶叶蛋不能多吃 
Don’t eat tea egg too much, 
0:01:55.581,0:01:57.849
因为这个毕竟对身体不是特别好
it’s not good for health. 
0:01:58.910,0:02:01.296
好啦 现在我们这个蛋已经煮熟了
Alright, the egg is hard-boiled already. 
0:02:02.032,0:02:04.005
把它捞出来 过一下凉水
Put them in the cold water. 
0:02:05.081,0:02:07.231
透一下凉水的话它就更好剥
It ’s better to peel it with cold water
0:02:09.278,0:02:11.369
好 现在我们稍微冰凉一下
Now we cold the egg a little bit. 
0:02:11.855,0:02:13.490
轻轻地敲一下
Slightly knock it. 
0:02:18.085,0:02:20.014
好了 现在我们重新加水
Done. Now we refill some water. 
0:02:22.223,0:02:24.197
这一次加的水可以稍微多一点点
You can add more water this time. 
0:02:27.039,0:02:28.821
然后放点这个香料
And put some spices.
0:02:29.145,0:02:30.206
丢2颗八角
Two star anises, 
0:02:30.824,0:02:32.017
丢一小块桂皮
a small piece of cinnamon
0:02:32.400,0:02:33.608
我们四川喜欢吃辣椒
We love spice in Sichuan, 
0:02:33.608,0:02:36.067
就放几个干辣椒进去
So put a few dried chili peppers. 
0:02:36.966,0:02:38.114
再放两片香叶
two bay leaf, 
0:02:39.190,0:02:40.692
然后加点老抽调色
and some dark soy sauce to make it looks good. 
0:02:42.930,0:02:45.846
调色我们先搅一下 看一下这个颜色怎么样
We mixed it first to see the color. 
0:02:48.748,0:02:49.455
可以了
That’s enough. 
0:02:49.499,0:02:51.237
嗯 颜色没什么问题
Yes, it’s the right color. 
0:02:51.929,0:02:53.843
好 现在我们来准备一下这个茶叶
Now let’s prepare the tea.  
0:02:54.359,0:02:55.184
好了吗
Is it enough? 
0:02:56.008,0:02:57.717
可以了可以了
That’s enough. 
0:02:58.291,0:03:01.148
这里大概只有10克都不到的样子
There are about 10 grams of tea. 
0:03:02.223,0:03:02.916
可以了
That’s good. 
0:03:04.595,0:03:08.615
然后我们用这个开水 用八九十度的开水
Now we use boiling water, about 80 to 90 degrees. 
0:03:08.895,0:03:13.328
给它泡一下 第一遍的不要
seak it in, throw away the first time’s water. 
0:03:14.477,0:03:15.066
搅一下
mix it up. 
0:03:15.478,0:03:17.393
你不盖着 第一轮它泡不到嘎
The flavor won’t come out if you don’t cover it. 
0:03:17.731,0:03:19.587
一会儿的 就是第一遍这个水不要
It’s okay, we just don’t need the water from the first time.  
0:03:19.734,0:03:20.810
好 现在可以了
Now, it’s okay. 
0:03:20.810,0:03:21.914
把这个茶叶加进去
We put the tea into the pot. 
0:03:26.288,0:03:28.144
好 最后我们来放点盐
Lastly, we add some salt. 
0:03:28.542,0:03:30.397
盐的话可以稍微重一些
We can put more salt in it,  
0:03:31.914,0:03:33.328
因为水也比较多嘛
because there’s more water. 
0:03:35.169,0:03:36.995
最后我们来加点这个可乐
Lastly, we add some coke. 
0:03:37.010,0:03:40.073
这个是上次做懒人排骨剩的是不
This is the leftover from cooking the pork ribs, right?
0:03:40.073,0:03:40.574
嗯
Yes. 
0:03:41.899,0:03:44.636
好了嘛 这个电饭锅都满了
That’s enough, the pot is almost full. 
0:03:44.636,0:03:46.229
好 稍微加一点
right, just adds a little bit. 
0:03:46.539,0:03:48.100
所以我们这个就不用加糖了
So there is no need to add sugar. 
0:03:48.215,0:03:50.399
可乐里面都有一点甜味了
Coke is already sweet. 
0:03:50.978,0:03:51.961
然后给它盖上
Cover it up. 
0:03:53.448,0:03:54.120
重新烧开
Reboli it. 
0:03:56.194,0:03:59.638
现在这烧开了之后  继续让它煮一会儿
Now it’s boiling, let it keep boil for a bit. 
0:04:00.117,0:04:02.007
煮完之后最重要的一个东西就是
the most important thing after boiling
0:04:02.301,0:04:05.434
让它浸泡 浸泡4个小时才更容易入味
 is to let it soak for four hours, to get flavor penetration. 
0:04:06.997,0:04:07.383
四伯爷 
Uncle, 
0:04:08.468,0:04:12.312
啷个嘛 还吃点可乐啊
What? Drink some coke?
0:04:12.886,0:04:13.299
啊
yes, 
0:04:14.079,0:04:15.228
又在冒泡子了
It’s getting bubble. 
0:04:15.935,0:04:17.496
哦哟

0:04:17.952,0:04:18.792
我喝这点
I will finish this. 
0:04:18.895,0:04:19.381
好
Yeah, 
0:04:23.210,0:04:23.976
诶呀 安逸
nice. 
0:04:25.287,0:04:25.817
可以嘎
Good? 
0:04:25.920,0:04:26.391
好喝
So good. 
0:04:28.483,0:04:31.620
现在我们这个茶叶蛋已经在这个电饭锅里面
Now the egg has been put in the pot 
0:04:31.782,0:04:33.796
用煨的方式 煮饭的方式
simmering
0:04:33.843,0:04:35.036
已经煮了40分钟了
for 40 minutes. 
0:04:35.508,0:04:39.160
这个时候我先拿2个我们吃一下来试哈看哈
Let’s take two and try them first. 
0:04:39.322,0:04:40.044
可以安
Alright. 
0:04:40.088,0:04:41.575
这个颜色都出来了哒
The color changed
0:04:41.752,0:04:42.857
剩下的继续
leave the rest of them alone. 
0:04:43.107,0:04:45.774
现在就把火关了 让它泡
Now turn off the heat, let them soak. 
0:04:45.774,0:04:46.907
再泡几个小时
Soak for a few hours. 
0:04:47.452,0:04:48.056
尝一哈看嘛四伯爷
Try a piece, uncle. 
0:04:48.056,0:04:48.689
有点烫
A little bit hot. 
0:04:51.045,0:04:52.047
诶呀 真的很烫
It’s really hot. 
0:04:55.375,0:04:57.363
你看这样颜色都已经出来了
Look the color stick in. 
0:04:58.321,0:04:59.882
你看我这个才安逸
Look at mine, 
0:05:00.029,0:05:00.515
嗯
Right. 
0:05:01.443,0:05:05.419
这个茶叶蛋就是现在还不是特别入味
The egg is not flavor penetration now. 
0:05:05.949,0:05:07.054
好烫哦
It’s so hot. 
0:05:07.422,0:05:08.365
我来给你弄
Let me help you. 
0:05:09.145,0:05:10.810
转到一哈就给它逮（剥）开了
Peel it this way. 
0:05:13.343,0:05:14.933
给它滚一哈 自己就掉了
Let it roll so the eggshell will get off. 
0:05:15.964,0:05:16.524
是不是
Right? 
0:05:18.689,0:05:19.587
我先尝哈看
Let me try it first. 
0:05:19.867,0:05:20.824
烫
Hot. 
0:05:24.359,0:05:25.360
等它冷哈都
Cool it down a little bit. 
0:05:25.640,0:05:27.054
太烫了
too hot. 
0:05:27.820,0:05:28.689
还可以
It’s quite ok. 
0:05:30.471,0:05:32.017
但是中间现在还没有味道
The middle part is not flavor penetration, though. 
0:05:34.374,0:05:35.198
很香
Smells so good. 
0:05:35.832,0:05:37.599
闻起来已经有茶叶的香味 
You can smell the tea flavor already. 
0:05:37.628,0:05:41.045
已经有那个清香味了
It has a clear smell from tea. 
0:05:41.163,0:05:42.842
但是说中间还没有入味
But the middle part is not flavored. 
0:05:45.640,0:05:46.980
烫哦四伯爷
It’s hot, uncle. 
0:05:47.717,0:05:49.293
少少的吃撒
Just try a little bit. 
0:05:52.533,0:05:54.094
还没咋个入味
It’s not flavor penetrated yet. 
0:05:54.094,0:05:54.565
嗯
yes. 
0:05:54.565,0:05:57.216
再隔几个小时来吃差不多
It will get better after soaking for a couple of hours. 
0:05:58.335,0:06:00.265
好 我们再等4个小时再来
Alright, Let’s wait for four more hours. 
0:06:00.265,0:06:02.002
现在已经 大家可以看一下
Now, as you guys can see, 
0:06:02.960,0:06:04.948
已经浸泡进去了
the eggs have soaked in. 
0:06:06.141,0:06:06.715
慢慢来
Take it slowly. 
0:06:11.119,0:06:13.151
嗯 不要掉
Don’t drop it. 
0:06:31.892,0:06:35.674
现在我们这个鸡蛋 这个茶叶蛋
Now our tea egg, 
0:06:36.058,0:06:38.902
可乐茶叶蛋已经放了好几个小时了
our coke tea eggs have been put for hours. 
0:06:39.731,0:06:41.097
现在捞一个出来
Let’s get one out. 
0:06:41.097,0:06:41.970
四伯爷你吃一个不
Uncle, you want to try one? 
0:06:41.970,0:06:42.575
我不要
No...
0:06:42.822,0:06:43.337
你不要啊
You don’t want one? 
0:06:43.337,0:06:44.837
不要了 刚才吃了饭安
No, just finished a meal. 
0:06:44.904,0:06:45.755
要的
Right. 
0:06:46.271,0:06:47.981
我们这个是早上开始做的
We made it this morning, 
0:06:47.981,0:06:49.858
现在已经到下午2点钟了
Now it’s about 2 PM. 
0:06:50.615,0:06:51.526
也应该入味了
It should get the flavor. 
0:06:51.981,0:06:53.047
我来尝哈就晓得了
We will see after a taste. 
0:06:53.512,0:06:54.697
好多个小时了嘛
It’s been a couple of hours. 
0:06:55.137,0:06:57.153
你看 这个颜色的话就要比
Look, the color changed. 
0:06:57.458,0:06:58.851
这个颜色就变得多了
The color changed darker
0:06:58.851,0:07:00.769
比上午更加要深一点
than the one in the morning. 
0:07:02.541,0:07:03.811
嗯 入味了现在
It gets flavor penetration now. 
0:07:04.422,0:07:05.302
现在比较入味
Now it’s flavorful. 
0:07:09.004,0:07:09.786
不错不错
Nice. 
0:07:12.559,0:07:13.622
这个蛋我们捞出来吃
When we want to eat it, 
0:07:13.622,0:07:15.882
味道够了的时候就把蛋捞出来
We eat it when the egg gets flavor. 
0:07:17.825,0:07:19.975
捞出来就可以了 不用再继续泡了
Just take them out, no need for soaking. 
0:07:20.818,0:07:22.711
然后这个汤汁的话
And for the gravy, 
0:07:23.127,0:07:24.544
嗯 还可以卤一次
We can use it to make the tea egg again. 
0:07:25.033,0:07:26.182
最好就不要超过3次
But no more than three times. 
0:07:26.182,0:07:27.965
超过3次的话这个味道就不香了
If it uses more than three time, it’s not flavored anymore. 
0:07:31.545,0:07:33.365
但这个可能放不得哦噶
But the gravy can’t last o]long. 
0:07:33.793,0:07:34.453
放不到好久
It doesn’t last long. 
0:07:36.102,0:07:38.781
三两天可以放在冰箱头
You can put it in the refrigerator for about two or three days. 
0:07:38.781,0:07:40.158
最好是当天做当天吃
The best way is to finish it by the day. 
0:07:41.527,0:07:43.604
是整多了的话
If you made more, 
0:07:43.604,0:07:44.300
煮多了的话 
if you cooked more, 
0:07:44.312,0:07:46.817
放在保鲜室里头可能保一两天没得问题的哈
You can put it in the refrigerator for about two or three days.
0:07:46.841,0:07:47.831
一两天没得问题的
the egg could last for one to two days. 
0:07:48.931,0:07:51.679
好了 大家如果是想吃的话可以尝试一下
Alright, if you guys want to eat tea egg, you can try this method. 
0:07:51.679,0:07:52.559
特别的简单
It’s very simple. 
0:07:52.865,0:07:54.099
就跟懒人排骨一样
Just like the easy pork rib. 
0:07:54.282,0:07:56.029
也不用加太多的东西
And you don’t need to add too much material.  
0:07:57.080,0:07:58.973
本期视频就到这里 拜拜
That’s it for today’s video, bye-bye. 
0:07:59.315,0:08:00.000
拜拜
Bye-bye. 
0:08:03.237,0:08:04.679
真的可以你不要笑
It could work, don’t laugh. 
0:08:05.229,0:08:05.876
吃一个嘛
Want to try one? 
0:08:06.328,0:08:07.367
我刚才吃了饭
I just ate.
