### ISSUE TITLE
[华农兄弟] 华农兄弟鱼缸里的鱼太少了再去放几个地笼多抓点回来 - https://youtu.be/MBAQtBCZjZE

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1029]
https://youtu.be/MBAQtBCZjZE
<p>&#35270;&#39057;&#21457;&#24067;&#20110; May 11, 2020 at 11:33AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/MBAQtBCZjZE

#华农兄弟：鱼缸里的鱼太少了，再去放几个地笼，多抓点回来
#Huanong Brothers: There are too few fish in our tank. Let's place some traps and catch some fish.

0:00:00.020,0:00:02.360
# 這個魚缸那麼大  魚又那麼少
This fish tank is so big, but there are so few fish.

0:00:04.180,0:00:04.880
# 我去搞點
Let me get,

0:00:05.700,0:00:06.780
# 再搞點回來
get some more fish.

0:00:07.820,0:00:09.100
# 太少啦  不好看
Too few, it doesn't look nice.

0:00:22.880,0:00:24.620
# 這種地方很多那個蛇頭魚的哦
There are a lot of snakehead fish in this kind of ponds, you know.

0:00:26.300,0:00:27.580
# 把那草割一下
Let me cut away the grass,

0:00:27.700,0:00:29.240
# 我們好放個地籠下去
so that I can drop a trap here.

0:00:33.560,0:00:35.520
# 這麼多草  地籠都放不下去
It's not possible to put the trap with so much grass.

0:00:40.160,0:00:41.780
# 這個小地籠
This is a small trap.

0:00:43.320,0:00:44.660
# 這裡放個小地籠
I'm gonna put a small trap here.

0:00:45.700,0:00:46.840
# 加點料下去
Let me put some bait.

0:00:48.900,0:00:50.620
# 這個料是我祖傳秘方哦
The formula of the bait is my ancestral secret.

0:01:02.660,0:01:04.640
# 等它可以進去下裡面吃得去  (註︰是我中文不好嗎？沒聽懂沒看懂)
The fish can get in, go down inside and eat and whatever.

0:01:08.120,0:01:09.740
# 你看  剛好沉下去啦  這樣
Look! It sinks to the bottom, you see.

0:01:12.340,0:01:13.780
# 準備一個大地籠
Let me get a big trap ready.

0:01:14.480,0:01:15.840
# 這草要搞乾淨
The grass needs to be cleared away.

0:01:16.860,0:01:18.020
# 不然放不下去
There are no rooms for the trap otherwise.

0:01:23.980,0:01:25.480
# 誒  怎麼還是小的
Eh? Why is it still a small one?

0:01:25.860,0:01:27.820
# 有大的  裡面還有大的  還有兩個大的
There are big ones, there are big ones inside, two big ones.

0:01:28.180,0:01:30.280
# 沒  就4個  我剛放掉了
No, I have only four. I've already put them down.

0:01:31.560,0:01:32.760
# 再帶了兩個過來
I've brought two more here.

0:01:33.380,0:01:34.040
# 你在哪裡放掉了
Where did you put them down?

0:01:34.200,0:01:34.700
# 車裡
Inside the car

0:01:36.560,0:01:37.540
# 就用這個小的
So I'll just use this small one.

0:01:38.840,0:01:39.620
# 有貨的話
My love depends of the result,

0:01:41.120,0:01:42.280
# 小的也是愛
not the size.

0:02:05.360,0:02:08.320
# 已經放好兩個啦  就這麼小的潭有兩個夠啦
I've already put two. Two would be enough for such a small pond.

0:02:08.640,0:02:09.840
# 我們還放下面
Let's put more down there,

0:02:10.400,0:02:11.900
# 放下面放兩個下去
down there, two more down there.

0:02:14.080,0:02:15.360
# 你看  就那個水潭
Look! That pond,

0:02:16.000,0:02:16.620
# 去那裡
we'er going there.

0:02:17.180,0:02:18.240
# 肯定有魚
There must be fish.

0:03:35.540,0:03:36.080
# 好啦
Alright!

0:03:37.100,0:03:38.260
# 這個地籠放好啦
So the trap is placed.

0:03:39.040,0:03:40.320
# 我們明天再過來看
Let's come again tomorrow.

0:03:41.440,0:03:42.600
# 肯定有魚的這裡
There will certainly be fish.

0:03:51.200,0:03:52.900
# 這個垃圾處理一下
We need to take care of the garbage.

0:03:58.580,0:03:59.980
# 好啦  先回去
Alright! Let's go back first.

0:04:02.940,0:04:04.280
# 第二天
The next day

0:04:04.280,0:04:07.360
# 今天過來收一下地籠哦  就在那下面  看一下有沒有魚
We're coming to get back the traps today. They're right down there. Let's see if there are any fish.

0:04:08.480,0:04:10.280
# 按道理來說  應該有魚
There should be fish, theoretically.

0:04:11.780,0:04:12.840
# 不然沒道理呀
It doesn't make sense otherwise.

0:04:22.820,0:04:23.820
# 吃都沒吃
The bait is still there, untouched.

0:04:24.740,0:04:26.560
# 你看 都沒有哦
Look! There's nothing.

0:04:26.680,0:04:27.600
# 那麼奇怪
It's strange!

0:04:30.400,0:04:30.980
# 放回去
Put it back.

0:04:31.720,0:04:32.680
# 我就不信
There must be fish.

0:04:33.660,0:04:34.520
# 沒有魚
I know it.

0:04:35.660,0:04:36.340
# 好息
It stinks!

0:04:48.200,0:04:49.860
# 誒  有  有兩條
Eh? Here, here are two!

0:04:50.700,0:04:52.060
# 一條  有一條蛇頭魚
One, one of them is a snakehead fish.

0:04:52.680,0:04:53.180
# 有
Yup!

0:04:54.840,0:04:55.820
# 你看  這有
Look! Here are...

0:04:56.780,0:04:57.840
# 哇  好多小魚
Wa! A lot of small fish.

0:05:01.000,0:05:01.580
# 你看
Look!

0:05:02.220,0:05:03.440
# 一條蛇頭魚喲
Here's a snakehead fish.

0:05:05.140,0:05:06.240
# 把它放桶裡面
Let me put it into the bucket.

0:05:06.280,0:05:07.180
# 誒  這裡還有
Eh? Here are still more.

0:05:20.920,0:05:22.020
# 哎呀  可以喲
Aya! Not bad!

0:05:24.320,0:05:25.680
# 還有一條那大的泥鰍
Here's also a really big loach.

0:05:26.640,0:05:28.560
# 哇  夠大吧  這泥鰍
Wa! It's a huge loach, isn't it?

0:05:30.800,0:05:32.280
# 把它這個網放回去
Let me put the net back.

0:05:32.280,0:05:33.360
# 我把它放回去啦
I've put it back already.

0:05:34.260,0:05:35.860
# 我們看一下明天有沒有貨
Let's see if we can have anything tomorrow.

0:05:37.200,0:05:37.700
# 好啦
Alright!

0:05:38.040,0:05:39.280
# 上  上面還有兩個籠
There, there are two more traps up there.

0:05:39.940,0:05:40.720
# 去看一下
Let's have a look.

0:05:41.900,0:05:43.520
# 還有兩個地籠那邊放著
There are two more traps on that side.

0:05:43.540,0:05:44.460
# 現在下去
Let's go down there now.

0:05:44.880,0:05:46.640
# 要從這個懸崖峭壁上
We need to walk slowly,

0:05:47.020,0:05:48.240
# 慢慢的走下去
along this sheer cliff.

0:05:57.320,0:05:58.860
# 你看  那個魚在動
Look! That fish, it's moving!

0:05:59.280,0:06:00.000
# 哇
Wa!

0:06:00.500,0:06:01.540
# 大收獲哇
It's a fruitful day!

0:06:10.620,0:06:12.300
# 哈哈  兩條哦
Haha! Two fish,

0:06:12.820,0:06:14.480
# 又看到兩條魚在這裡
I see two fish here!

0:06:18.340,0:06:19.200
# 哈哈哈
Hahaha!

0:06:19.560,0:06:20.380
# 想跑
Wanna run away?

0:06:21.180,0:06:22.180
# 沒那麼容易
Nothing can be more difficult.

0:06:29.060,0:06:29.640
# 你看
Look!

0:06:30.640,0:06:31.840
# 夠大吧  這兩條
These two are huge, aren't they?

0:06:31.840,0:06:33.700
# 你看  這條就夠大吧  這條
Look! This one is enormous, isn't it?

0:06:34.600,0:06:35.420
# 這有一條
Here's one more.

0:06:36.340,0:06:37.400
# 不要這些S的  (註︰是不是國內都忌諱「死」字？)
I don't want the dead ones.

0:06:38.720,0:06:39.860
# 這還活著的
And these are still alive.

0:06:42.120,0:06:42.720
# 不要
Not this one

0:06:47.960,0:06:50.200
# 你看  我把它這籠子再放回去
Look! I'm gonna put this trap back again.

0:06:50.800,0:06:52.520
# 還有的  不止那麼一點點
There are more fish, more than the tiny little bit here.

0:06:59.360,0:07:00.740
# 我去看一下別外一個地籠
Let me take a look at the other trap.

0:07:02.500,0:07:03.540
# 滿收獲哦
Fruitful, fruitful!

0:07:04.160,0:07:04.740
# 3條
Three fish!

0:07:05.420,0:07:06.680
# 看有沒有第4條啊
Let's see if fourth fish is there.

0:07:07.320,0:07:09.000
# 哎  額  一條蛇
Ay! Ey! There's a snake!

0:07:09.400,0:07:10.280
# 好大條哇
It's very big.

0:07:12.820,0:07:14.820
# 你看  那一條蛇哦  怎麼搞
Look! There's a snake. What should I do?

0:07:18.880,0:07:19.800
# 小魚就有
Only small fish

0:07:24.100,0:07:25.920
# 有蛇哦  也有蛇頭魚
There are snake, and snakehead fish.

0:07:26.600,0:07:27.560
# 把那蛇放出來
Let me get the snake out.

0:07:32.660,0:07:33.520
# 太厲害啦
Amazing!

0:07:34.240,0:07:36.040
# 一冕就搞到那麼多蛇頭魚
I can have some many snakehead fish in just one night!

0:07:45.340,0:07:46.480
# 出來  出來  出來
Get out, get out, get out!

0:07:48.900,0:07:50.040
# 蛇  你快點出來
Come out, snake!

0:07:53.380,0:07:54.200
# 快點走哦
Go 'way!

0:07:54.400,0:07:55.040
# 出去喲
C'mon, get out!

0:07:56.420,0:07:57.260
# 不然的話
Otherwise,

0:07:57.960,0:07:59.180
# 等下帶回你去
I'll take you home.

0:08:08.360,0:08:09.540
# 哇  這條蛇頭魚
Wa! This snakehead fish...

0:08:12.860,0:08:14.760
# 這條蛇頭魚  稍微小一點
This snakehead fish, it's a bit smaller.

0:08:28.400,0:08:30.340
# 這  這種地方很多那個蛇頭魚的
There, there are a lot of snakehead fish in this kind of ponds.

0:08:31.420,0:08:32.020
# 放回去
Put it back.

0:08:36.480,0:08:37.220
# 這樣放著
Leave it here.

0:08:37.780,0:08:38.820
# 明天又有貨
Tomorrow is another fruitful day.

0:08:41.840,0:08:42.460
# 洗一下手
Wash my hands.

0:08:45.780,0:08:46.840
# 今天 你看
Today, look!

0:08:47.100,0:08:48.020
# 那麼多魚
We have so many fish.

0:08:51.000,0:08:52.180
# 你看  把它倒出來
Look! Let me pour them out.

0:08:53.480,0:08:54.160
# 哇
Wa!

0:08:56.800,0:08:57.860
# 又搞了那麼多條
We have so many fish again.

0:09:01.900,0:09:03.580
# 這個泥鰍才大  看到沒
This loach is enormous. Can you see it?

0:09:04.600,0:09:06.380
# 我都沒見過那麼大的泥鰍
It's the biggest loach that I've ever seen.

0:09:06.960,0:09:07.820
# 這蛇頭魚
This snakehead fish

0:09:09.320,0:09:11.140
# 哇  這兩條可以  這個是
Wa! These two fish are not bad. This is,

0:09:12.040,0:09:14.240
# 應該是母的這條  那麼大的肚子
this should be female. It has such a big belly.

0:09:16.140,0:09:17.860
# 把它放到那個魚缸裡面去養
Let's put them into that tank and keep them there.

0:09:18.340,0:09:20.100
# 那麼[SIC]蛇頭魚不能放下去
I'm not gonna put the snakehead fish here.

0:09:20.860,0:09:22.460
# 放下去的話等下會跑啦
They would run away otherwise.

0:09:23.840,0:09:25.160
# 把這些小的放下去
I'm gonna put these small ones here.

0:09:29.320,0:09:30.300
# 你們自由啦
You're free now.

0:09:42.020,0:09:44.600
# 嘴巴好像  嘴巴這裡都有點受傷啦
The mouth seems, the mouth is a bit wounded here.

0:09:46.820,0:09:47.840
# 這樣沒辦法
Well, anyway

0:09:49.600,0:09:51.020
# 它撞籠子撞的
Cuz it crushed onto the trap.

0:09:54.420,0:09:56.100
# 你看  它這身上
Look! Its body,

0:09:56.880,0:09:57.580
# 好靚哦
is really beautiful!

0:09:58.860,0:10:00.640
# 它這個應該是  母的
I think it should be, female.

0:10:01.420,0:10:02.760
# 養起來 讓它下崽
Let's keep it, and let it give birth to babies.

0:10:07.940,0:10:11.320
# 剛好看到我老媽在這裡打田  我也過來幫忙打一下  (註︰「老媽」這個說法較粗俗，要對應一下)
I just come across my ma and she's ploughing. Let me help her.

0:10:11.860,0:10:14.420
# 然後  然後再把那個秧子  扔下去
Then, then we'll take the rice seedlings, and shoot them onto the field.

0:10:15.140,0:10:17.300
# 直接扔下去就可以了  拋秧苗
We can shoot them right away. It's called seedlings shooting.

0:11:05.080,0:11:06.280
# 這個  要把它
These seedlings, need to be,

0:11:07.740,0:11:08.740
# 一棵一棵
shot onto the field,

0:11:09.380,0:11:10.380
# 往那邊丟
one by one.

0:11:12.000,0:11:12.920
# 搞準一點
I need to aim well.

0:11:21.060,0:11:23.140
# 以前要插秧的 現在不用插啦
We needed to plant the seedlings in the past. But it's no more necessary.

0:11:23.760,0:11:24.620
# 現在直接這樣
Now we can simply,

0:11:25.380,0:11:26.060
# 丟就成啦
shoot them right away.

0:11:27.800,0:11:28.460
# 扔不準
I aim bad.

0:11:53.260,0:11:55.040
# 我扔不準  很難扔哦
I can't aim well. It's really hard.

0:11:59.620,0:12:00.700
# 一扔就歪啦
It never goes straight.

0:12:01.580,0:12:03.660
# 這個要有點技術的哦  不是
It needs some techniques, you know. You want to do it,

0:12:04.660,0:12:06.160
# 不是想扔就扔得準的
doesn't mean you can do it.

0:12:07.700,0:12:09.620
# 我扔的都有點歪歪的
And I'm not doing it very well.

0:12:13.840,0:12:15.140
# 這水有點深
The water here is a bit deep.

0:12:16.420,0:12:17.520
# 這樣不要緊的
Never mind.

0:12:23.360,0:12:25.380
# 丟  丟順手了就很  很好丟了
It becomes much, much easier once you know the tricks.

0:12:27.140,0:12:28.600
# 丟了也比較直一點了
And the seedlings are standing upright,

0:12:29.180,0:12:30.400
# 不會東倒西歪了
instead of swinging here and there.

0:12:33.960,0:12:35.660
# 扔的越遠  丟的越準
The further I shoot, the better I aim.

0:12:46.580,0:12:47.920
# 哇  真是的
Wa! It really works.

0:12:51.440,0:12:53.900
# 這樣一天應該也扔不了多久
I don't think I can spend a long time doing it a day,

0:12:53.920,0:12:55.420
# 扔不了多少畝吧
I mean I can't cover a large area in a day,

0:12:56.060,0:12:57.080
# 應該一畝地
only about one "mu" (666.7 square metres)

0:12:58.220,0:12:59.720
# 最快都是一畝地
at most one "mu".

0:13:02.700,0:13:03.680
# 這乾農活
This job,

0:13:05.580,0:13:07.360
# 這樣的速度  好累呀
together with this speed, it's really tiring.

0:13:07.960,0:13:09.660
# 應該買  買一個插秧機回來
I should have, I should have bought a planting machine.

0:13:10.980,0:13:13.120
# 但是我們這邊的田全是丘陵
But our fields here are all along the hills.

0:13:14.600,0:13:15.860
# 不是丘陵  就是
Not exactly hills, it's like,

0:13:17.540,0:13:19.280
# 每  每一塊地都是很小的
each, each piece of land is a tiny one.

0:13:20.220,0:13:21.920
# 插  插秧機使不上勁
The, the planing machines can't help much.

0:13:23.120,0:13:25.100
# 全靠人工的  種  種下去
So they're plant, planted, all by hands.

0:13:26.120,0:13:26.940
# 所以這個
So, it's a,

0:13:27.720,0:13:29.080
# 很辛苦的哦  種田
it's a really tough job, I mean farming.

0:13:32.300,0:13:33.960
# 但是  也要種一點啊
But, we need to do it, though we don't do much.

0:13:35.820,0:13:38.000
# 這些稻子都是  每年都是我們
The rice here is, every year, we

0:13:39.260,0:13:40.240
# 自家耕的田
we plant on our own fields.

0:13:41.520,0:13:42.420
# 種一點稻子
We plant some rice,

0:13:43.880,0:13:44.920
# 到時候就不用買了
then there's no need to buy.

0:13:47.160,0:13:48.160
# 自己想要多少米
Whenever we want rice,

0:13:48.720,0:13:49.300
# 直接用
we can ah,

0:13:50.100,0:13:50.660
# 直接去 
I mean we can simply,

0:13:51.280,0:13:52.340
# 碾出來就行了
mill however much we want right away.

0:13:53.280,0:13:53.780
# 好啦
Alright!

0:13:54.500,0:13:55.320
# 沒這個秧子了
I've run out of seedlings now.

0:13:55.740,0:13:57.180
# 我去看一下那個地籠
Let me take a look at the traps,

0:13:57.720,0:13:58.800
# 看下地籠有沒有魚
and see if there are any fish in the traps.

0:13:59.620,0:14:00.400
# 準備回去了
Let's get ready to go back.

0:14:07.680,0:14:09.280
# 哇  又一條蛇哦
Wa! Snake again!

0:14:18.860,0:14:20.020
# 哎呀  一條泥鰍
Aya! A loach,

0:14:20.480,0:14:21.160
# 小魚
and small fish

0:14:22.760,0:14:24.220
# 全是小魚跟一條蛇
All are small fish, and a snake,

0:14:26.200,0:14:27.620
# 還有一條小蚄蟹  誒呀
and a small crab too, eya!

0:14:28.520,0:14:29.560
# 把蛇放出來
Let me get the snake out.

0:14:31.100,0:14:32.260
# 這個蛇是沒毒的
This snake is not venomous.

0:14:40.020,0:14:41.380
# 快點  出來  出來  出來
C'mon! Get out, get out, get out!

0:14:41.980,0:14:42.880
# 你自由啦
You're free now.

0:14:46.020,0:14:47.420
# 往下面走哇
Go downwards!

0:14:47.600,0:14:48.340
# 不走等下
Just go! Otherwise...

0:14:49.240,0:14:50.160
# 放到桶裡面來
Let me put it into the bucket.

0:14:54.180,0:14:56.040
# 這個蛇笨的要死
It's a goddamn stupid snake.

0:14:56.420,0:14:58.060
# 那麼笨  下去耶
Get down! Stupid!

0:14:59.240,0:15:00.620
# 快點下去
C'mon, hurry up!

0:15:01.740,0:15:02.760
# 為甚麼不下去
Why isn't it going down?

0:15:03.520,0:15:05.120
# 不下去我把你帶回家的哦
If you are not going, I'll take you home, you know?

0:15:09.140,0:15:09.960
# 快點出去
Get out! Now!

0:15:10.720,0:15:11.820
# 它蛇頭在這裡
It's head is here.

0:15:14.760,0:15:16.500
# 你自由啦  還不快點出
You're free now. Why don't you just go?

0:15:16.500,0:15:18.480
# 不出的話  等下我帶回去家裡去哦
Go before I change my mind! Otherwise I'll take you home.

0:15:22.160,0:15:23.280
# 又搞了一些魚
So I still have some more fish,

0:15:24.340,0:15:25.560
# 只是不多而已
just not too many.

0:15:28.240,0:15:29.480
# 我們再放 明天
Put it here again. Tomorrow,

0:15:29.860,0:15:31.380
# 再過來看一下  看有沒有
let's come again and see if there are any.

0:15:36.240,0:15:37.240
# 去上面看一下
Let's have a look up there.

0:15:37.720,0:15:38.940
# 那邊還有兩個地籠
There are two more traps.

0:15:45.000,0:15:45.840
# 看一下還沒有
Let me see.

0:15:49.340,0:15:51.160
# 全是小魚  那麼小不要啦
All are small fish. I don't want them. They're too small.

0:15:51.380,0:15:52.340
# 明天再過來看
Let's come again tomorrow.

0:15:52.760,0:15:53.760
# 再放一晚上
Leave it here for another night.

0:15:55.900,0:15:56.640
# 有就有
This is the last time,

0:15:57.900,0:15:58.920
# 沒有就沒有
no matter we have anything tomorrow or not.

0:16:00.560,0:16:01.820
# 額  沒有
Eh, nothing.

0:16:02.400,0:16:03.700
# 肯定白天它不出來
They must be hiding themselves in daylight.

0:16:04.040,0:16:05.540
# 我今天早上看了一下
I came here and took a look this morning,

0:16:05.940,0:16:07.080
# 抓了幾條回去
and have caught some fish back home.

0:16:07.840,0:16:08.540
# 要晚上
At night,

0:16:09.460,0:16:10.620
# 要過一冕上看一下
leave it here one more night and have a look.

0:16:10.660,0:16:11.600
# 如果明天沒有就  
If we still can't get anything tomorrow,

0:16:12.280,0:16:13.300
# 把這網起啦
we're gonna get back the net,

0:16:13.480,0:16:14.520
# 換另外一個地方
and place it at another place.

0:16:23.360,0:16:23.880
# 好啦
Alright!

0:16:24.200,0:16:24.720
# 回去啦
Let's go back!

0:16:26.100,0:16:27.800
# 空軍  一條都沒有
Empty-handed! Not even one fish.
