### ISSUE TITLE
【美食作家王刚】厨房冷知识：海里面的鱼 - https://youtu.be/B6ORd_OztwI

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1031]
**视频链接**：https://youtu.be/B6ORd_OztwI

视频时长3:18，预计发布时间为北京时间5月14日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨房冷知识：“海里面的鱼”为什么不是咸的？什么鱼淡水咸水都能活？

简介
大家好，尝试一个新的节目，暂时命名为“厨房冷知识”，给大家总结分享一些平常大家可能没太注意的关于食材后厨厨艺的冷知识。希望可以通过这样一种形式让更多人了解背后的故事，从而更加喜爱做菜，也能增加一些平常和朋友家人的谈资。当然自己不是专业深究事物的原理的，所以不免会出错，所以十分欢迎大家指正或讨论，大家有什么想问的问题也可以留言告诉我。

字幕
0:00:00.350,0:00:01.850
哈喽 大家好 我是王刚

0:00:02.120,0:00:03.942
最近有一个粉丝给我发私信

0:00:04.021,0:00:07.725
问那个海水里面的鱼为什么海水那么咸

0:00:08.043,0:00:08.929
这个鱼不咸

0:00:09.178,0:00:10.572
四伯爷  你晓得是为啥子不嘛

0:00:10.940,0:00:11.488
不晓得

0:00:11.488,0:00:14.753
海里头的鱼你想像它是咸的是淡的

0:00:15.798,0:00:17.580
海里的鱼应该说是咸的

0:00:17.580,0:00:18.257
是咸的啊

0:00:18.257,0:00:18.646
嗯

0:00:19.442,0:00:22.588
就是说像我伯爷是在四川这边

0:00:22.817,0:00:24.449
没有在海边待太久

0:00:24.778,0:00:26.281
所以他觉得海水是咸的

0:00:26.281,0:00:27.635
所以里面的鱼也是咸的

0:00:28.003,0:00:28.999
其实不是的

0:00:29.407,0:00:30.871
海水里面的鱼

0:00:31.090,0:00:33.230
为什么说它的肉不是咸的呢

0:00:33.509,0:00:36.273
是因为它的腮里面有一种特殊的细胞

0:00:36.273,0:00:38.168
可以过滤这个海盐

0:00:38.417,0:00:39.591
除了它的鱼鳃

0:00:39.591,0:00:40.398
还有它的肾

0:00:40.667,0:00:42.150
还有通过它的排尿系统

0:00:42.150,0:00:43.753
把多余的盐分排出去

0:00:44.011,0:00:45.684
所以它的肉里面的话

0:00:45.993,0:00:47.157
不是咸的

0:00:47.157,0:00:48.730
要不然就是变成咸鱼了

0:00:49.340,0:00:52.414
还有一个奇怪的现象就是说

0:00:52.801,0:00:54.212
四伯爷 我先问你嘛

0:00:54.212,0:00:55.926
你晓不晓得有一种鱼哈

0:00:56.203,0:00:59.445
如果是我们的草鱼放到海里去它会不会死

0:00:59.605,0:01:00.495
它可能要遭（死）

0:01:00.571,0:01:01.184
肯定要遭（死）嘎

0:01:01.192,0:01:01.705
肯定遭

0:01:01.705,0:01:02.091
为啥子

0:01:02.402,0:01:04.065
它的这个水性就养不活

0:01:04.241,0:01:06.039
嗯 这一点我伯爷说对了

0:01:06.215,0:01:10.021
淡水的鱼它没有办法过滤盐分 所以它会死掉

0:01:10.037,0:01:11.994
海水里面的鱼放在淡水里面来的话

0:01:12.356,0:01:15.405
可能因为这个水的性质也会死掉

0:01:15.405,0:01:16.656
但是有一种鱼很特殊

0:01:17.068,0:01:21.234
比如说是鲈鱼 还有那个鳗鱼

0:01:21.419,0:01:22.704
还有那个刀鱼

0:01:22.906,0:01:25.350
这些鱼的话它有比较特殊的一个功能

0:01:25.367,0:01:28.097
就是在咸水里面它可以去适应环境

0:01:28.374,0:01:29.659
去过滤盐分

0:01:29.987,0:01:31.507
如果是在淡水里面的话

0:01:31.507,0:01:34.052
它又可以改变自身的一些东西

0:01:34.052,0:01:35.758
它又可以在淡水里面生活

0:01:36.026,0:01:37.538
就是特别的奇怪

0:01:37.933,0:01:40.310
我还在我们农村这个稻田里面

0:01:40.621,0:01:42.721
田里面你知道吗 钓过鲈鱼

0:01:42.973,0:01:44.829
所以我觉得这个特别好玩

0:01:44.947,0:01:47.156
这个你晓不晓得我是咋子晓得的这个

0:01:47.257,0:01:48.131
我不晓得

0:01:48.744,0:01:51.331
是因为我以前在海边嘛

0:01:51.356,0:01:53.557
我从小就去外地了在海边

0:01:53.817,0:01:55.279
别人说海水是咸的

0:01:55.783,0:01:57.236
我就尝了一下 确实很咸

0:01:57.236,0:01:58.219
而且咸得发苦

0:01:58.891,0:02:01.218
所以我长大了之后做了厨师

0:02:01.596,0:02:03.452
然后在学厨的这个过程中

0:02:03.771,0:02:07.316
就学了很多比较冷门的一些知识吧

0:02:07.526,0:02:08.987
所以我就晓得这些

0:02:10.231,0:02:14.145
为啥子咋个鱼蛋那

0:02:14.783,0:02:18.068
在我们这边又繁殖得起来嘛在广州运回来的

0:02:18.420,0:02:19.109
鱼蛋

0:02:19.176,0:02:19.504
嗯

0:02:19.538,0:02:19.966
啥子蛋

0:02:20.394,0:02:25.025
这次你幺舅公就在珠海的堰塘

0:02:25.963,0:02:26.677
弄的鱼苗是不

0:02:26.677,0:02:28.399
嗯鱼种 鱼蛋

0:02:29.071,0:02:30.970
他弄到这边来再孵化嘛

0:02:31.180,0:02:33.532
弄到这边来养撒

0:02:34.699,0:02:35.926
这个正常

0:02:36.421,0:02:39.277
所以说我们很多鱼啊 比如说鲈鱼

0:02:39.538,0:02:41.218
从广东运过来到四川 

0:02:41.747,0:02:43.712
放到那个淡水里面养 也养得活

0:02:45.392,0:02:47.265
然后就是我们这个淡水鱼

0:02:47.719,0:02:50.894
淡水鱼的话 其实鱼里面也是有盐分的

0:02:50.978,0:02:53.372
它是通过在淡水里面吸收盐分

0:02:53.624,0:02:55.002
让自己保持一个平衡

0:02:55.732,0:02:57.286
好了 本期视频就到这里

0:02:57.698,0:02:59.445
然后后续的话会给跟大家分享

0:02:59.445,0:03:00.672
更多的冷门知识

0:03:01.604,0:03:03.712
我个人觉得是比较冷门的

0:03:04.124,0:03:05.989
然后可能大家都不怎么了解

0:03:06.241,0:03:07.861
后续我会继续跟大家分享

0:03:07.971,0:03:09.920
好吧就到这里 拜拜

0:03:09.920,0:03:11.297
拜拜

0:03:11.827,0:03:14.313
这个鱼这个东西拿给你研究得很彻底

0:03:14.598,0:03:16.430
开玩笑 我做了好多年的鱼哦


```

**Comment by Hackerry** [comment]
认领

**Comment by Hackerry** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨房冷知识：“海里面的鱼”为什么不是咸的？什么鱼淡水咸水都能活？
Kitchen Fun Facts: Why saltwater fish doesn't taste salty? What fish live in both fresh water and salt water?

简介
大家好，尝试一个新的节目，暂时命名为“厨房冷知识”，给大家总结分享一些平常大家可能没太注意的关于食材后厨厨艺的冷知识。希望可以通过这样一种形式让更多人了解背后的故事，从而更加喜爱做菜，也能增加一些平常和朋友家人的谈资。当然自己不是专业深究事物的原理的，所以不免会出错，所以十分欢迎大家指正或讨论，大家有什么想问的问题也可以留言告诉我。
Hello everyone! We are experimenting with a new series called "Kitchen Fun Facts". I'll bring some fun facts about food and cooking techniques. I hope you can get enthusiastic about cooking and also learn some useful small talk topics. I'm certainly not a science person so there will be mistakes and inaccuracies. Corrections and discussions are highly welcome. You can also leave comments about your questions down below.

字幕
0:00:00.350,0:00:01.850
哈喽 大家好 我是王刚
Hello, everyone. I'm Wang Gang.

0:00:02.120,0:00:03.942
最近有一个粉丝给我发私信
Recently a fan messaged me,

0:00:04.021,0:00:07.725
问那个海水里面的鱼为什么海水那么咸
asking why salt water

0:00:08.043,0:00:08.929
这个鱼不咸
doesn't make saltwater fish salty?

0:00:09.178,0:00:10.572
四伯爷  你晓得是为啥子不嘛
Do you know why, uncle?

0:00:10.940,0:00:11.488
不晓得
I have no clue

0:00:11.488,0:00:14.753
海里头的鱼你想像它是咸的是淡的
You can imagine that saltwater fish they live in ocean...

0:00:15.798,0:00:17.580
海里的鱼应该说是咸的
I think fish in ocean should be salty

0:00:17.580,0:00:18.257
是咸的啊
Should be salty, huh?

0:00:18.257,0:00:18.646
嗯
Yes

0:00:19.442,0:00:22.588
就是说像我伯爷是在四川这边
You know my uncle lives in Sichuan

0:00:22.817,0:00:24.449
没有在海边待太久
He didn't spend much of his life near ocean

0:00:24.778,0:00:26.281
所以他觉得海水是咸的
So he thinks ocean water, which is salty,

0:00:26.281,0:00:27.635
所以里面的鱼也是咸的
should make the fish salty too.

0:00:28.003,0:00:28.999
其实不是的
Well, it's not.

0:00:29.407,0:00:30.871
海水里面的鱼
Saltwater fish

0:00:31.090,0:00:33.230
为什么说它的肉不是咸的呢
The reason why their meat is not salty,

0:00:33.509,0:00:36.273
是因为它的腮里面有一种特殊的细胞
is because they have a special cell in their gills

0:00:36.273,0:00:38.168
可以过滤这个海盐
that can filter out the salt.

0:00:38.417,0:00:39.591
除了它的鱼鳃
Besides their gills,

0:00:39.591,0:00:40.398
还有它的肾
their kidneys also help by

0:00:40.667,0:00:42.150
还有通过它的排尿系统
pumping out excessive salt

0:00:42.150,0:00:43.753
把多余的盐分排出去
through the urinary system.

0:00:44.011,0:00:45.684
所以它的肉里面的话
So the meat inside

0:00:45.993,0:00:47.157
不是咸的
is not salty.

0:00:47.157,0:00:48.730
要不然就是变成咸鱼了
Otherwise it will just be salted fish

0:00:49.340,0:00:52.414
还有一个奇怪的现象就是说
Another interesting fact.

0:00:52.801,0:00:54.212
四伯爷 我先问你嘛
Uncle, let me ask you first.

0:00:54.212,0:00:55.926
你晓不晓得有一种鱼哈
It's about a type of fish.

0:00:56.203,0:00:59.445
如果是我们的草鱼放到海里去它会不会死
You know if we put a grass carp into the ocean, will it live?

0:00:59.605,0:01:00.495
它可能要遭（死）
It will be dead.

0:01:00.571,0:01:01.184
肯定要遭（死）嘎
Certainly dead right?

0:01:01.192,0:01:01.705
肯定遭
Of course

0:01:01.705,0:01:02.091
为啥子
What's your reasoning?

0:01:02.402,0:01:04.065
它的这个水性就养不活
The water is hostile to its survival

0:01:04.241,0:01:06.039
嗯 这一点我伯爷说对了
Yes. Uncle gets it right.

0:01:06.215,0:01:10.021
淡水的鱼它没有办法过滤盐分 所以它会死掉
Freshwater fish can't filter out salt, so it will die.

0:01:10.037,0:01:11.994
海水里面的鱼放在淡水里面来的话
Vice versa, if we put saltwater fish in fresh water,

0:01:12.356,0:01:15.405
可能因为这个水的性质也会死掉
it will also most likely die because of the water condition.

0:01:15.405,0:01:16.656
但是有一种鱼很特殊
But there is a special type of fish,

0:01:17.068,0:01:21.234
比如说是鲈鱼 还有那个鳗鱼
including bass, eel

0:01:21.419,0:01:22.704
还有那个刀鱼
and Chinese tapertail anchovy.

0:01:22.906,0:01:25.350
这些鱼的话它有比较特殊的一个功能
These fish has a special capability.

0:01:25.367,0:01:28.097
就是在咸水里面它可以去适应环境
They can adjust to the saline environment in salt water

0:01:28.374,0:01:29.659
去过滤盐分
and be able to filter out salt.

0:01:29.987,0:01:31.507
如果是在淡水里面的话
If instead in fresh water,

0:01:31.507,0:01:34.052
它又可以改变自身的一些东西
they can adjust their body compositions,

0:01:34.052,0:01:35.758
它又可以在淡水里面生活
to be able to live in fresh water.

0:01:36.026,0:01:37.538
就是特别的奇怪
It's very strange.

0:01:37.933,0:01:40.310
我还在我们农村这个稻田里面
I once fished a bass here

0:01:40.621,0:01:42.721
田里面你知道吗 钓过鲈鱼
right in this rice field.

0:01:42.973,0:01:44.829
所以我觉得这个特别好玩
So I find it's very interesting.

0:01:44.947,0:01:47.156
这个你晓不晓得我是咋子晓得的这个
Do you know how I came to know this?

0:01:47.257,0:01:48.131
我不晓得
I don't

0:01:48.744,0:01:51.331
是因为我以前在海边嘛
I used to live near the ocean

0:01:51.356,0:01:53.557
我从小就去外地了在海边
I moved to a coastal city when I was little

0:01:53.817,0:01:55.279
别人说海水是咸的
People said sea water is salty

0:01:55.783,0:01:57.236
我就尝了一下 确实很咸
So I had a taste. It was indeed salty.

0:01:57.236,0:01:58.219
而且咸得发苦
Salty and bitter

0:01:58.891,0:02:01.218
所以我长大了之后做了厨师
So when I grew up and became a chef,

0:02:01.596,0:02:03.452
然后在学厨的这个过程中
and during my apprenticeship,

0:02:03.771,0:02:07.316
就学了很多比较冷门的一些知识吧
I learnt many similar fun facts.

0:02:07.526,0:02:08.987
所以我就晓得这些
That's how I came understand these facts

0:02:10.231,0:02:14.145
为啥子咋个鱼蛋那
Then why do people bring fish eggs

0:02:14.783,0:02:18.068
在我们这边又繁殖得起来嘛在广州运回来的
from Guangzhou and they can incubate them here.

0:02:18.420,0:02:19.109
鱼蛋
Fish eggs?

0:02:19.176,0:02:19.504
嗯
Yes.

0:02:19.538,0:02:19.966
啥子蛋
What fish eggs?

0:02:20.394,0:02:25.025
这次你幺舅公就在珠海的堰塘
My uncle lives at Yantang, Zhuhai.

0:02:25.963,0:02:26.677
弄的鱼苗是不
He got some juvenile fish?

0:02:26.677,0:02:28.399
嗯鱼种 鱼蛋
Yes. Both that and fish eggs.

0:02:29.071,0:02:30.970
他弄到这边来再孵化嘛
He wanted to incubated them here?

0:02:31.180,0:02:33.532
弄到这边来养撒
Incubate and raise them

0:02:34.699,0:02:35.926
这个正常
That is normal

0:02:36.421,0:02:39.277
所以说我们很多鱼啊 比如说鲈鱼
So it seems many fish, like bass,

0:02:39.538,0:02:41.218
从广东运过来到四川 
transported from Guangdong

0:02:41.747,0:02:43.712
放到那个淡水里面养 也养得活
can also be raised here in fresh water.

0:02:45.392,0:02:47.265
然后就是我们这个淡水鱼
Freshwater fish

0:02:47.719,0:02:50.894
淡水鱼的话 其实鱼里面也是有盐分的
actually have salt.

0:02:50.978,0:02:53.372
它是通过在淡水里面吸收盐分
They absorb salt from surrounding water

0:02:53.624,0:02:55.002
让自己保持一个平衡
to maintain a body fluid balance.

0:02:55.732,0:02:57.286
好了 本期视频就到这里
OK. That's all for this episode.

0:02:57.698,0:02:59.445
然后后续的话会给跟大家分享
Later I will keep sharing

0:02:59.445,0:03:00.672
更多的冷门知识
more fun facts with you.

0:03:01.604,0:03:03.712
我个人觉得是比较冷门的
I think they are quite novel

0:03:04.124,0:03:05.989
然后可能大家都不怎么了解
You may not have heard about them before

0:03:06.241,0:03:07.861
后续我会继续跟大家分享
I'll keep sharing

0:03:07.971,0:03:09.920
好吧就到这里 拜拜
That's it. Bye bye.

0:03:09.920,0:03:11.297
拜拜
Bye bye.

0:03:11.827,0:03:14.313
这个鱼这个东西拿给你研究得很彻底
You seem to know everything about fish

0:03:14.598,0:03:16.430
开玩笑 我做了好多年的鱼哦
You must be joking. I've been cooking fish for so many years.
