### ISSUE TITLE
[老饭骨] 二伯炸酱面 - https://youtu.be/iCFTNH4MlAg

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1037]
**视频链接**：https://youtu.be/iCFTNH4MlAg

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【國宴大師•二伯炸醬面】醬香油潤、家常易學的地道老北京炸醬面！有二伯這秘方，炸醬再也不會寡干！|老飯骨

简介
小友們好，都說這炸醬面的靈魂都在這炸醬裏，二伯今天就教大家醬香油潤、家常易學的地道老北京炸醬該怎麽做！
二伯這炸醬的做法不用水澥，改用黃酒，這樣做出來的炸醬才能潤。
這炸醬夠潤，我們炸出來才不會又寡又干，這樣做出來口感才更柔！
炸醬裏的蔥也很有講究，我們分三次下蔥，具體哪個時間下，小友們快來視頻裏看看咯！
P.S多的油可不要浪費，拿來炒菜吃，倍兒香！

字幕
1
00:00:00,000 --> 00:00:01,360
炸酱你看有的人加水

2
00:00:01,360 --> 00:00:03,880
咱们一点水不澥 这叫润

3
00:00:03,880 --> 00:00:04,840

4
00:00:04,840 --> 00:00:06,080
好香啊

5
00:00:06,080 --> 00:00:07,400

6
00:00:07,400 --> 00:00:09,080
我炸酱的时候用三种酱

7
00:00:09,080 --> 00:00:10,480
这是干黄酱

8
00:00:10,480 --> 00:00:11,520
你闻闻这个

9
00:00:11,520 --> 00:00:13,280
这个（黄豆）酱呢 非常甜

10
00:00:13,280 --> 00:00:17,120
这个甜度大 当什么使 当糖使

11
00:00:17,120 --> 00:00:18,640
咱就不用放糖了

12
00:00:18,640 --> 00:00:20,360
咱就都放里边 行了

13
00:00:20,360 --> 00:00:21,600
咱就别给人糟践了

14
00:00:21,600 --> 00:00:24,720
这儿还有一种酱 这个也香

15
00:00:24,720 --> 00:00:27,800
这三种酱合一

16
00:00:27,800 --> 00:00:31,480
我拿黄酒 我师父这就不一样了

17
00:00:31,480 --> 00:00:33,760
加的黄酒 黄酒澥

18
00:00:33,760 --> 00:00:37,200
要咱家的料酒行不行 料酒不好

19
00:00:37,200 --> 00:00:38,760
料酒它有点那个味道

20
00:00:38,760 --> 00:00:40,560
还不如不放 你要放料酒

21
00:00:40,560 --> 00:00:43,920
就买那不到十块钱的花雕酒就完全可以

22
00:00:43,920 --> 00:00:45,640
朝晖再拿点酱油来

23
00:00:45,640 --> 00:00:47,360
普通酱油 咱来澥一澥

24
00:00:47,360 --> 00:00:49,880
倒进去没事儿

25
00:00:49,880 --> 00:00:51,280
倒了稀稠合适就行

26
00:00:51,280 --> 00:00:53,840

27
00:00:53,840 --> 00:00:55,480
这就差不多了

28
00:00:55,480 --> 00:00:57,880
你看有好多 炸出酱来

29
00:00:57,880 --> 00:00:59,520
炸到什么份上了

30
00:00:59,520 --> 00:01:02,080
炸的真跟黑了吧唧的 干的

31
00:01:02,080 --> 00:01:04,840
那就不对 也就不好吃了

32
00:01:04,840 --> 00:01:06,520
因为炸的酱首先要润

33
00:01:06,520 --> 00:01:08,440
这基本就差不多了

34
00:01:08,440 --> 00:01:12,200
网友们 看看稀稠度啊 稀稠度 行了

35
00:01:12,200 --> 00:01:14,080
咱就开始开火

36
00:01:14,080 --> 00:01:15,840
师父这个火调多大

37
00:01:15,840 --> 00:01:19,000
大点 越大越好 好嘞 大火啊

38
00:01:19,000 --> 00:01:21,320
你说为什么加这黄豆酱

39
00:01:21,320 --> 00:01:24,400
这个酱 如果说要没有糖的甜度

40
00:01:24,400 --> 00:01:30,280
这酱吃起来 寡 干 干咸干咸的

41
00:01:30,280 --> 00:01:31,720
吃起来不柔

42
00:01:31,720 --> 00:01:33,040
炸出来酱就不好吃 你知道吗

43
00:01:33,920 --> 00:01:36,240
锅热了师父 锅热了没事儿

44
00:01:36,240 --> 00:01:38,720
就这点油吧 够了

45
00:01:38,720 --> 00:01:40,280
这简单说一下

46
00:01:40,280 --> 00:01:43,320
这为什么说 这个酒店要炸的好吃呢

47
00:01:43,320 --> 00:01:45,960
我们用的油 是不用这种油

48
00:01:45,960 --> 00:01:47,720
用什么油做 你知道吗

49
00:01:47,720 --> 00:01:49,480
用葱烧海参的葱油

50
00:01:49,480 --> 00:01:52,480
然后用这葱油 炸这酱 煸这肉

51
00:01:52,480 --> 00:01:53,880
一听就香

52
00:01:53,880 --> 00:01:55,480
今天咱就不再做葱油了

53
00:01:55,480 --> 00:01:57,160
因为这做葱油 做了好几回了

54
00:01:57,160 --> 00:01:59,120
网友也知道怎么做了

55
00:01:59,120 --> 00:02:01,840

56
00:02:01,840 --> 00:02:03,400
能搁多少搁多少

57
00:02:03,400 --> 00:02:05,160
都搁里头得了

58
00:02:05,160 --> 00:02:07,320
好家伙 这多少肉啊

59
00:02:07,320 --> 00:02:09,440
就爱吃炸酱里边的肉

60
00:02:09,440 --> 00:02:13,440
炸酱里边就得有肥肉 要不然不香

61
00:02:13,440 --> 00:02:15,280
这肉呢 多煸煸它

62
00:02:15,280 --> 00:02:19,080
让它把这水气出来 这香气就过来了

63
00:02:19,080 --> 00:02:22,240
你看到了没有 这里边有水 是吧

64
00:02:22,240 --> 00:02:24,960
你要这样炒出酱来 肯定就发闷

65
00:02:24,960 --> 00:02:26,400
这肉就不好吃了 不香

66
00:02:26,400 --> 00:02:28,680
它必须把这水气出去

67
00:02:28,680 --> 00:02:31,640
水气出去 这个猪油也熬出来了

68
00:02:31,640 --> 00:02:33,200
熬出来了它香啊

69
00:02:33,200 --> 00:02:36,160
师姐您在家做炸酱吗

70
00:02:36,160 --> 00:02:40,240
做啊 这是我们家的传统保留节目

71
00:02:40,240 --> 00:02:42,400
这个可以一锅多炸点

72
00:02:42,400 --> 00:02:45,560
然后分瓶装了以后搁冰箱里存着

73
00:02:45,560 --> 00:02:48,120
想吃的时候 微波炉一热

74
00:02:48,120 --> 00:02:49,840
这肉就差不多了 咱可以了

75
00:02:49,840 --> 00:02:51,160
师父您再说说

76
00:02:51,160 --> 00:02:54,400
这个炸到什么情况下算是好了

77
00:02:54,400 --> 00:02:56,200
你看这油 油清亮了

78
00:02:56,200 --> 00:02:59,400
这肉四边已经有小的焦质了

79
00:02:59,400 --> 00:03:02,240
但是里边还是嫩的

80
00:03:02,240 --> 00:03:04,880
第一遍葱 这咱们第一遍葱

81
00:03:04,880 --> 00:03:07,440
咱们第一遍葱弄大点

82
00:03:07,440 --> 00:03:09,200

83
00:03:09,200 --> 00:03:12,160
这要是拿葱油炸的话就更香了

84
00:03:12,160 --> 00:03:16,080
因为葱油里边含有香菜啊 还有香料

85
00:03:16,080 --> 00:03:18,800
师父 这会儿咱们下酱吗  可以下了

86
00:03:18,800 --> 00:03:23,000
这葱味的香气就出来了 不能炸糊了

87
00:03:23,000 --> 00:03:29,320
因为它还有一个过程呢 真地道

88
00:03:29,320 --> 00:03:31,080
你看这颜色

89
00:03:32,560 --> 00:03:35,320
为什么我说这酱不能加水吧

90
00:03:35,320 --> 00:03:36,760
加酱油都没事

91
00:03:36,760 --> 00:03:39,400
把整个这个酱香味都给弄出来了

92
00:03:40,520 --> 00:03:44,760
这得推四十分钟呢 推稠了它

93
00:03:44,760 --> 00:03:47,000
香味出来了

94
00:03:47,000 --> 00:03:49,560
这个香味跟平时炸酱香味不一样

95
00:03:49,560 --> 00:03:52,840
师父这个酱咱们炸了半个小时了

96
00:03:52,840 --> 00:03:53,840
也差不多了

97
00:03:53,840 --> 00:03:57,360
咱们把多的油  这是肉里边的油

98
00:03:57,360 --> 00:04:01,320
一会咱炒菜使 这炒菜香啊

99
00:04:01,320 --> 00:04:03,520
师父这个葱咱们是一会再放是吧

100
00:04:03,520 --> 00:04:05,200
咱们第一次下葱了吧

101
00:04:05,200 --> 00:04:07,600
你看 这师父的窍门儿

102
00:04:07,600 --> 00:04:11,080
第二次下葱 最后还有第三次

103
00:04:11,080 --> 00:04:12,600
我是三次下葱

104
00:04:13,880 --> 00:04:15,440
再开大点火

105
00:04:16,840 --> 00:04:19,600
看看 这火 稍微开大点

106
00:04:21,080 --> 00:04:24,080
你看 香气都出来了是吧

107
00:04:24,080 --> 00:04:26,560
稠度也够了

108
00:04:26,560 --> 00:04:28,720
这个可以下第三次葱了

109
00:04:28,720 --> 00:04:32,480

110
00:04:32,480 --> 00:04:34,000
一开始还是清香的

111
00:04:34,000 --> 00:04:36,240
现在就是这种醇厚的酱香

112
00:04:36,240 --> 00:04:39,200
有点扒锅的感觉那种味道出来了

113
00:04:39,200 --> 00:04:42,080
是吧 香气都带出来了

114
00:04:42,080 --> 00:04:44,520
咱这就差不多了啊

115
00:04:44,520 --> 00:04:46,360
好嘞 关火

116
00:04:47,520 --> 00:04:50,080
师父您㨤一勺慢慢往下流

117
00:04:50,080 --> 00:04:50,800
我照照这感觉

118
00:04:50,800 --> 00:04:54,360
哎呦喂 好 太棒了

119
00:04:54,360 --> 00:04:57,960
这叫润 是不是照照就知道了

120
00:04:57,960 --> 00:05:00,080

121
00:05:00,080 --> 00:05:01,280
好香啊

122
00:05:01,280 --> 00:05:03,760

123
00:05:03,760 --> 00:05:06,760
咱们今天因为时间原因 面咱就不吃了

124
00:05:06,760 --> 00:05:07,960
但是咱有

125
00:05:07,960 --> 00:05:10,080

126
00:05:10,080 --> 00:05:12,400
哈喇子都快流出来了

127
00:05:12,400 --> 00:05:14,680
给你俩一人来一筷子

128
00:05:14,680 --> 00:05:16,640
师姐 好嘞谢谢

129
00:05:16,640 --> 00:05:18,040

130
00:05:18,040 --> 00:05:20,760
上来就弄一大肉丁啊

131
00:05:21,480 --> 00:05:24,200
你们得尝尝这肉怎么回事

132
00:05:25,400 --> 00:05:27,880
肉炸到什么份上 这是关键

133
00:05:27,880 --> 00:05:30,680
包括肉的嫩度的感觉 那个香气

134
00:05:30,680 --> 00:05:33,840
这个酱 它是不可分开的

135
00:05:33,840 --> 00:05:35,360
师父一会儿我打包啊

136
00:05:35,360 --> 00:05:37,840
这个可以了 惦记半天了

```

**Comment by iamatrollatrollisme** [comment]
认领

**Comment by iamatrollatrollisme** [comment]
请翻译以下全部内容
标题（翻译主要意思即可，不要超过 100 个字符）
【國宴大師•二伯炸醬面】醬香油潤、家常易學的地道老北京炸醬面！有二伯這秘方，炸醬再也不會寡干！|老飯骨
State Banquet Masterchef - Homestyle easy Beijing Fried Black Bean Sauce noodles

简介
小友們好，都說這炸醬面的靈魂都在這炸醬裏，二伯今天就教大家醬香油潤、家常易學的地道老北京炸醬該怎麽做！
二伯這炸醬的做法不用水澥，改用黃酒，這樣做出來的炸醬才能潤。
這炸醬夠潤，我們炸出來才不會又寡又干，這樣做出來口感才更柔！
炸醬裏的蔥也很有講究，我們分三次下蔥，具體哪個時間下，小友們快來視頻裏看看咯！
P.S多的油可不要浪費，拿來炒菜吃，倍兒香！

Introduction
Hello everyone, people say that the soul of the Fried Bean Sauce noodles is the sauce, today, ErBai has a recipe that use Huangjiu(chinese yellow rice wine) instead of water to dilute the sauce, so the sauce will be runny and thin
The sauce needs to be moist so it won’t be blend and dry, and the texture will be softer
Frying the sauce, we need to be careful with scallions too, we are adding the scallions in 3 different batches. What are the good time to add them, let's watch the video to find out.

P.S. We can utilize the extra scallion oil to make stir fries, smell and taste very good.


字幕
1
00:00:00,000 --> 00:00:01,360
炸酱你看有的人加水
Fried the bean sauce, some people will add water when they are frying it

2
00:00:01,360 --> 00:00:03,880
咱们一点水不澥 这叫润
We are not adding any water, just thinning the sauce with other ingredients 

3
00:00:03,880 --> 00:00:04,840

4
00:00:04,840 --> 00:00:06,080
好香啊
Smells amazing

5
00:00:06,080 --> 00:00:07,400

6
00:00:07,400 --> 00:00:09,080
我炸酱的时候用三种酱
When I fry the black bean sauce I use 3 different kinds of sauces

7
00:00:09,080 --> 00:00:10,480
这是干黄酱
This is dry yellow fermented bean Sauce

8
00:00:10,480 --> 00:00:11,520
你闻闻这个
You smell this one

9
00:00:11,520 --> 00:00:13,280
这个（黄豆）酱呢 非常甜
This (bean) sauce is very sweet

10
00:00:13,280 --> 00:00:17,120
这个甜度大 当什么使 当糖使
It is so sweet that we can use it as sugar

11
00:00:17,120 --> 00:00:18,640
咱就不用放糖了
Now we don’t need to add sugar

12
00:00:18,640 --> 00:00:20,360
咱就都放里边 行了
We just add them all in there

13
00:00:20,360 --> 00:00:21,600
咱就别给人糟践了
Let’s not waste too much of the sauce


14
00:00:21,600 --> 00:00:24,720
这儿还有一种酱 这个也香
Here is another sauce, also smells very good

15
00:00:24,720 --> 00:00:27,800
这三种酱合一
We mix all these 3 kinds of sauce together

16
00:00:27,800 --> 00:00:31,480
我拿黄酒 我师父这就不一样了
I am adding Huangjiu. Master is cooking it differently

17
00:00:31,480 --> 00:00:33,760
加的黄酒 黄酒澥
We added Huangjiu to thin it down

18
00:00:33,760 --> 00:00:37,200
要咱家的料酒行不行 料酒不好
Can we add regular cooking wine? Cooking wine is not good

19
00:00:37,200 --> 00:00:38,760
料酒它有点那个味道
Cooking wine has a special taste

20
00:00:38,760 --> 00:00:40,560
还不如不放 你要放料酒
If you have regular cooking wine, I rather not to add any of it

21
00:00:40,560 --> 00:00:43,920
就买那不到十块钱的花雕酒就完全可以
Just add the cheap Huadiao rice wine which is less than 10 cny

22
00:00:43,920 --> 00:00:45,640
朝晖再拿点酱油来
Chaohui bring me more soy sauce

23
00:00:45,640 --> 00:00:47,360
普通酱油 咱来澥一澥
Just regular soy sauce, add some to thin it down

24
00:00:47,360 --> 00:00:49,880
倒进去没事儿
Just add it in, it’s fine

25
00:00:49,880 --> 00:00:51,280
倒了稀稠合适就行
Thin it down to certain consistency

26
00:00:51,280 --> 00:00:53,840

27
00:00:53,840 --> 00:00:55,480
这就差不多了
This is about it

28
00:00:55,480 --> 00:00:57,880
你看有好多 炸出酱来
You know there are a lot of recipes

29
00:00:57,880 --> 00:00:59,520
炸到什么份上了
They fry for how long you know?

30
00:00:59,520 --> 00:01:02,080
炸的真跟黑了吧唧的 干的
They fry until the sauce is black and dry

31
00:01:02,080 --> 00:01:04,840
那就不对 也就不好吃了
It is wrong and it is not going to taste good

32
00:01:04,840 --> 00:01:06,520
因为炸的酱首先要润
Frying the sauce, first we need to make the sauce thin and moist

33
00:01:06,520 --> 00:01:08,440
这基本就差不多了
We are almost done


34
00:01:08,440 --> 00:01:12,200
网友们 看看稀稠度啊 稀稠度 行了
Guys let’s see this consistency, the consistency is right here

35
00:01:12,200 --> 00:01:14,080
咱就开始开火
Let’s turn on the heat

36
00:01:14,080 --> 00:01:15,840
师父这个火调多大
Master how hot should it be

37
00:01:15,840 --> 00:01:19,000
大点 越大越好 好嘞 大火啊
Hot, the hotter the better

38
00:01:19,000 --> 00:01:21,320
你说为什么加这黄豆酱
You know why we need to add (bean) sauce


39
00:01:21,320 --> 00:01:24,400
这个酱 如果说要没有糖的甜度
This sauce, if there is no certain sweetness in the sauce

40
00:01:24,400 --> 00:01:30,280
这酱吃起来 寡 干 干咸干咸的
It will taste blend and dry, dey and salty

41
00:01:30,280 --> 00:01:31,720
吃起来不柔
It is not soft and smooth when you eat it

42
00:01:31,720 --> 00:01:33,040
炸出来酱就不好吃 你知道吗
Fry the sauce that way is not going to taste good you know?

43
00:01:33,920 --> 00:01:36,240
锅热了师父 锅热了没事儿
The wok is hot now master. Wok is hot, cool

44
00:01:36,240 --> 00:01:38,720
就这点油吧 够了
Just add these oil will be enough

45
00:01:38,720 --> 00:01:40,280
这简单说一下
I just gonna elaborate a little

46
00:01:40,280 --> 00:01:43,320
这为什么说 这个酒店要炸的好吃呢
Do you know why the restaurant fries better sauce

47
00:01:43,320 --> 00:01:45,960
我们用的油 是不用这种油
The oil we using is not regular oil

48
00:01:45,960 --> 00:01:47,720
用什么油做 你知道吗
Do you know what oil we use？

49
00:01:47,720 --> 00:01:49,480
用葱烧海参的葱油
We use oil fried with scallion and sea cucumber 

50
00:01:49,480 --> 00:01:52,480
然后用这葱油 炸这酱 煸这肉
And the fried the sauce and the meat with that oil

51
00:01:52,480 --> 00:01:53,880
一听就香
It sound very tasty 

52
00:01:53,880 --> 00:01:55,480
今天咱就不再做葱油了
Today we are not going to make scallion oil

53
00:01:55,480 --> 00:01:57,160
因为这做葱油 做了好几回了
Because we have made this scallion oil multiple times

54
00:01:57,160 --> 00:01:59,120
网友也知道怎么做了
Audiences know how to make it already

55
00:01:59,120 --> 00:02:01,840

56
00:02:01,840 --> 00:02:03,400
能搁多少搁多少
We will add as much as we can

57
00:02:03,400 --> 00:02:05,160
都搁里头得了
Well might as well add them all

58
00:02:05,160 --> 00:02:07,320
好家伙 这多少肉啊
Oh well this is a lot of meat

59
00:02:07,320 --> 00:02:09,440
就爱吃炸酱里边的肉
I love the meat from the fried bean sauce

60
00:02:09,440 --> 00:02:13,440
炸酱里边就得有肥肉 要不然不香
And there must be some fat meat, otherwise it won’t smell good

61
00:02:13,440 --> 00:02:15,280
这肉呢 多煸煸它
We are going to fry this meat for a bit longer

62
00:02:15,280 --> 00:02:19,080
让它把这水气出来 这香气就过来了
Fry all the water out of the sauce, then it will smell really good

63
00:02:19,080 --> 00:02:22,240
你看到了没有 这里边有水 是吧
You see now, there is  water in it, right?

64
00:02:22,240 --> 00:02:24,960
你要这样炒出酱来 肯定就发闷
If you going to fry the sauce with this it will not taste good

65
00:02:24,960 --> 00:02:26,400
这肉就不好吃了 不香
The meat will not taste good, and will not smell good

66
00:02:26,400 --> 00:02:28,680
它必须把这水气出去
We must vaporize the water

67
00:02:28,680 --> 00:02:31,640
水气出去 这个猪油也熬出来了
When we fry the water out of it, we also fry the oil out of the meat

68
00:02:31,640 --> 00:02:33,200
熬出来了它香啊
Fry them long enough, the aromatic of the ingredients all comes out
 

69
00:02:33,200 --> 00:02:36,160
师姐您在家做炸酱吗
Sister do you fry sauce at home?

70
00:02:36,160 --> 00:02:40,240
做啊 这是我们家的传统保留节目
Yeah definitely, this is the tradition in our family

71
00:02:40,240 --> 00:02:42,400
这个可以一锅多炸点
We can fry a little bit more sauce in the wok

72
00:02:42,400 --> 00:02:45,560
然后分瓶装了以后搁冰箱里存着
And then split them into several bottles and put them in the refrigerator 

73
00:02:45,560 --> 00:02:48,120
想吃的时候 微波炉一热
When you feel like having it, just heat it up with microwave

74
00:02:48,120 --> 00:02:49,840
这肉就差不多了 咱可以了
The meat is almost done, we are almost finished

75
00:02:49,840 --> 00:02:51,160
师父您再说说
Master can you elaborate more

76
00:02:51,160 --> 00:02:54,400
这个炸到什么情况下算是好了
How to tell when it is done?

77
00:02:54,400 --> 00:02:56,200
你看这油 油清亮了
You look at the oil, the oil is clear

78
00:02:56,200 --> 00:02:59,400
这肉四边已经有小的焦质了
The meat is browning around the edges

79
00:02:59,400 --> 00:03:02,240
但是里边还是嫩的
But still tender on the inside

80
00:03:02,240 --> 00:03:04,880
第一遍葱 这咱们第一遍葱
Now let’s add the first round of scallions

81
00:03:04,880 --> 00:03:07,440
咱们第一遍葱弄大点
First round let’s add a larger amount 

82
00:03:07,440 --> 00:03:09,200

83
00:03:09,200 --> 00:03:12,160
这要是拿葱油炸的话就更香了
If we are using the scallion oil it will smell better

84
00:03:12,160 --> 00:03:16,080
因为葱油里边含有香菜啊 还有香料
Because the scallion oil has cilantro and other herb

85
00:03:16,080 --> 00:03:18,800
师父 这会儿咱们下酱吗  可以下了
Master, can we add the sauce now? Yes we can

86
00:03:18,800 --> 00:03:23,000
这葱味的香气就出来了 不能炸糊了
Now you can smell the aromatic of the scallion, we can not over fry it

87
00:03:23,000 --> 00:03:29,320
因为它还有一个过程呢 真地道
Because there is still a procedure later. Very authentic 

88
00:03:29,320 --> 00:03:31,080
你看这颜色
You look at this color

89
00:03:32,560 --> 00:03:35,320
为什么我说这酱不能加水吧
This is why I said that we couldn’t add water

90
00:03:35,320 --> 00:03:36,760
加酱油都没事
It’s okay if you add soy sauce

91
00:03:36,760 --> 00:03:39,400
把整个这个酱香味都给弄出来了
We are extracting all the flavor out of the sauce

92
00:03:40,520 --> 00:03:44,760
这得推四十分钟呢 推稠了它
We need to mix it for 40 mins, thicken the sauce a little 

93
00:03:44,760 --> 00:03:47,000
香味出来了
Now we can smell the aromatic

94
00:03:47,000 --> 00:03:49,560
这个香味跟平时炸酱香味不一样
This fragrance is different from normal regular sauce

95
00:03:49,560 --> 00:03:52,840
师父这个酱咱们炸了半个小时了
We have been frying for 30mins

96
00:03:52,840 --> 00:03:53,840
也差不多了
We are almost there

97
00:03:53,840 --> 00:03:57,360
咱们把多的油  这是肉里边的油
Now we are putting away these extra oil from meat

98
00:03:57,360 --> 00:04:01,320
一会咱炒菜使 这炒菜香啊
We will use it to stir fry dishes, it will very tasty

99
00:04:01,320 --> 00:04:03,520
师父这个葱咱们是一会再放是吧
Master are we putting the scallions in later?

100
00:04:03,520 --> 00:04:05,200
咱们第一次下葱了吧
You see we have put the first round of scallions in previously


101
00:04:05,200 --> 00:04:07,600
你看 这师父的窍门儿
Look at my technique

102
00:04:07,600 --> 00:04:11,080
第二次下葱 最后还有第三次
This is the second batch of scallion, later we are adding the third batch

103
00:04:11,080 --> 00:04:12,600
我是三次下葱
I am adding scallions in 3 separate times

104
00:04:13,880 --> 00:04:15,440
再开大点火
Turn the heat up a little bit

105
00:04:16,840 --> 00:04:19,600
看看 这火 稍微开大点
See, we are turning the heat up a little bit

106
00:04:21,080 --> 00:04:24,080
你看 香气都出来了是吧
You see we can smell the aromatic

107
00:04:24,080 --> 00:04:26,560
稠度也够了
Thickness is good

108
00:04:26,560 --> 00:04:28,720
这个可以下第三次葱了
Now we can add the third batch of scallions

109
00:04:28,720 --> 00:04:32,480

110
00:04:32,480 --> 00:04:34,000
一开始还是清香的
At first it is refreshing fragrance

111
00:04:34,000 --> 00:04:36,240
现在就是这种醇厚的酱香
Now it is thick sauce aromatic

112
00:04:36,240 --> 00:04:39,200
有点扒锅的感觉那种味道出来了
The sauce is thickened and have a feeling of sticking to the wok 

113
00:04:39,200 --> 00:04:42,080
是吧 香气都带出来了
Right, bring out the aromatic

114
00:04:42,080 --> 00:04:44,520
咱这就差不多了啊
We are almost done

115
00:04:44,520 --> 00:04:46,360
好嘞 关火
Alright now, turn off the heat

116
00:04:47,520 --> 00:04:50,080
师父您㨤一勺慢慢往下流
Master you pick up a scoop and let it fall down slowly

117
00:04:50,080 --> 00:04:50,800
我照照这感觉
Let me film this

118
00:04:50,800 --> 00:04:54,360
哎呦喂 好 太棒了
Great

119
00:04:54,360 --> 00:04:57,960
这叫润 是不是照照就知道了
This is moisture, you can tell from the look

120
00:04:57,960 --> 00:05:00,080

121
00:05:00,080 --> 00:05:01,280
好香啊
Smells so good

122
00:05:01,280 --> 00:05:03,760

123
00:05:03,760 --> 00:05:06,760
咱们今天因为时间原因 面咱就不吃了
Today we don’t have much time, so we are not having it with noodles

124
00:05:06,760 --> 00:05:07,960
但是咱有
But we have(cucumber)

125
00:05:07,960 --> 00:05:10,080

126
00:05:10,080 --> 00:05:12,400
哈喇子都快流出来了
Saliva is coming out

127
00:05:12,400 --> 00:05:14,680
给你俩一人来一筷子
I will give you each a big scoop

128
00:05:14,680 --> 00:05:16,640
师姐 好嘞谢谢
Sister Great Thanks

129
00:05:16,640 --> 00:05:18,040

130
00:05:18,040 --> 00:05:20,760
上来就弄一大肉丁啊
Here is a big scoop of diced meat

131
00:05:21,480 --> 00:05:24,200
你们得尝尝这肉怎么回事
You need to taste the meat

132
00:05:25,400 --> 00:05:27,880
肉炸到什么份上 这是关键
To what extent we need to fry the meat, that’s the key

133
00:05:27,880 --> 00:05:30,680
包括肉的嫩度的感觉 那个香气
And how tender the meat is, how to bring out the aromatic

134
00:05:30,680 --> 00:05:33,840
这个酱 它是不可分开的
This sauce, they are inseparable 

135
00:05:33,840 --> 00:05:35,360
师父一会儿我打包啊
Master I am going to take it to go 

136
00:05:35,360 --> 00:05:37,840
这个可以了 惦记半天了
Okay, you have been thinking about it don’t you
