### ISSUE TITLE
[雪鱼] 【字幕少】抠门大饼（烙馍） - https://youtu.be/JFcPaJ6JJ0U

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#1039]
**视频链接**：https://youtu.be/JFcPaJ6JJ0U

视频时长：4min
发布日期：北京时间5月13日 21:00

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
江苏“抠门”大饼，仅1毫米厚，2张饼加1个蛋卖5元，一早上能卖600张

简介
江苏徐州特色小吃，烙馍！烙馍是非常薄的饼，只有1毫米的厚度，擀制这种馍需要长时间的操作经验，新手很难胜任，一般在街头巷尾的小摊上还有人制作这种馍。馍的吃法多种多样，从早餐到晚餐都有不同的方法。比如早餐时刻，2张馍放在一起加一个鸡蛋，可以叫做塌烙馍（见视频，塌是一种烹饪方法，如山东塌煎饼），塌好的烙馍口感脆爽，早上吃一个烙馍，再来一碗辣汤，早餐就非常完整了。其他时间，还可以用烙馍卷馓子吃，口感是双重脆感，很多人也喜欢；徐州的炸串、烧烤也非常发达，不管是烧烤还是炸串，都可以用烙馍包裹着来吃，既方便又有饱腹感。
-----如下部分建议直接复制到上文翻译的后方-----
地址：江苏省徐州市王陵路49号陈家老味沓馍
营业时间：6:30～只卖早餐
🐟
▶雪鱼已走过近100个城市，查看当地小吃美食，请关注我的Youtube频道。
I have traveled to nearly 100 cities, check local snacks, please follow my Youtube channel.
https://bit.ly/2rdIi3G
▶我也经常在这里出现哦！Instagram：https://www.instagram.com/xueyu_foodtravel/

#烙馍 #早餐  #面食
#中国美食
#ChineseFood
字幕
1
00:00:02,150 --> 00:00:05,850
一直看街上有卖的 但是从来不知道怎么做的

2
00:00:05,850 --> 00:00:07,800
怎么形成的不知道

3
00:00:08,100 --> 00:00:08,800
对

4
00:00:11,925 --> 00:00:14,100
要擀成1毫米的厚度

5
00:00:22,850 --> 00:00:25,875
擀得跟纸一样 

6
00:00:32,375 --> 00:00:35,675
雪鱼现在在徐州 待会我们要解决一下自己的早餐问题

7
00:00:36,000 --> 00:00:40,050
在徐州当地 有一种比较特色的主食 面食 烙馍

8
00:00:40,325 --> 00:00:43,250
这个名字听了好久了 我待会呢 打算就是

9
00:00:43,300 --> 00:00:47,175
吃一个沓烙馍 用烙馍加上鸡蛋来吃

10
00:00:47,450 --> 00:00:49,700
去看看这种特色的美食是什么样的吧

11
00:00:53,125 --> 00:00:56,100
我们今天的目的地是在一个小院子里

12
00:01:31,275 --> 00:01:34,175
一饼一蛋5块钱 一饼两蛋6块钱

13
00:01:34,575 --> 00:01:35,950
两个饼一个蛋的

14
00:01:36,550 --> 00:01:38,600
辣椒要不要  我要微辣的

15
00:01:38,850 --> 00:01:40,150
在这儿吃

16
00:01:40,225 --> 00:01:41,550
来 给美女送去

17
00:01:43,525 --> 00:01:44,950
还没找到地方呢

18
00:01:45,450 --> 00:01:46,900
屋里面 屋里面有地方

19
00:02:06,450 --> 00:02:08,375
烙馍都是提前做好的

20
00:02:08,450 --> 00:02:09,850
客人点完就可以吃到

21
00:02:10,425 --> 00:02:14,025
咱们这个是两个饼一个蛋6块钱

22
00:02:15,375 --> 00:02:17,700
刚做出来的沓馍是又薄又脆的

23
00:02:17,950 --> 00:02:20,175
吃一口渣渣掉的哪里都是

24
00:02:25,225 --> 00:02:27,875
咱们里面是加了葱花和一点点的辣椒的

25
00:02:27,975 --> 00:02:30,675
这么一尝 是有点油酥饼的意思的

26
00:02:30,675 --> 00:02:33,250
不过会比它更脆 因为更薄嘛

27
00:02:37,525 --> 00:02:39,200
我在这里吃烙馍没有要汤

28
00:02:39,300 --> 00:02:40,650
刚才阿姨进来的时候说

29
00:02:40,825 --> 00:02:42,950
要不要喝的 我帮你免费盛一碗

30
00:02:43,125 --> 00:02:44,750
真是太感谢阿姨了

31
00:02:48,300 --> 00:02:52,150
这就是烙馍 徐州的 只有徐州有

32
00:02:52,650 --> 00:02:54,950
其他地方有类似的小吃 叫法不一样

33
00:02:59,200 --> 00:03:02,570
徐州吃煎饼也蛮多的

34
00:03:05,350 --> 00:03:08,025
 大哥说 下次我来的时候 给我做一个超脆的

35
00:03:08,250 --> 00:03:10,825
我说 超脆的和普通的有什么样的区别

36
00:03:11,075 --> 00:03:13,050
他说 超脆的是3个饼皮

37
00:03:16,750 --> 00:03:19,700
像这样的饼就是3张饼皮 超脆

38
00:03:23,525 --> 00:03:24,900
这样的厚一点

39
00:03:29,375 --> 00:03:31,800
这边最忙的时候 能卖多少馍

40
00:03:32,075 --> 00:03:35,375
换算成饼 800多张吧

41
00:03:36,250 --> 00:03:38,325
光馍800多张

42
00:03:38,675 --> 00:03:40,800
做成的话就是不到400份

43
00:03:40,925 --> 00:03:42,325
400份吧

44
00:03:42,325 --> 00:03:44,825
没有四百份 三四百份

45
00:03:44,950 --> 00:03:48,025
平时用60多斤烙馍

46
00:03:48,625 --> 00:03:52,075
一斤有10张烙馍 做好卖300多份

47
00:03:52,875 --> 00:03:53,700
时间很短

48
00:03:54,100 --> 00:04:00,825
大哥做烙馍 切开的时候一定要像搭积木这样放吗

49
00:04:01,100 --> 00:04:02,575
立起来放的原因是 这样有利于通风

50
00:04:02,850 --> 00:04:04,050
通风里面才会脆

51
00:04:04,925 --> 00:04:08,075
把里面的热气排出来以后 它就会脆了

52
00:04:09,475 --> 00:04:11,350
这是最重要的

53
00:04:11,350 --> 00:04:14,550
只有脆的馍才能立起来 立起来的也会更脆

54
00:04:30,250 --> 00:04:32,350
  大哥不仅在介绍自己的烙馍

55
00:04:32,425 --> 00:04:34,200
还向我们介绍徐州的其它小吃

56
00:04:34,500 --> 00:04:36,450
比如说蛙鱼 把子肉 等等

57
00:04:38,150 --> 00:04:40,750
中午是把子肉和各种炒菜

58
00:04:42,000 --> 00:04:45,200
晚上在徐州就是吃羊肉串

59
00:04:45,900 --> 00:04:47,775
蛮厉害

60
00:04:47,900 --> 00:04:49,775
都是美味


```

**Comment by shuaisoserious** [comment]
认领

**Comment by shuaisoserious** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
江苏“抠门”大饼，仅1毫米厚，2张饼加1个蛋卖5元，一早上能卖600张
“Stingy” flatbread in jiangsu, only a mil meter thin, two flat bread and an egg only for 5 yuan, sold out 600 flatbreads in every morning 

简介
江苏徐州特色小吃，烙馍！烙馍是非常薄的饼，只有1毫米的厚度，擀制这种馍需要长时间的操作经验，新手很难胜任，一般在街头巷尾的小摊上还有人制作这种馍。馍的吃法多种多样，从早餐到晚餐都有不同的方法。比如早餐时刻，2张馍放在一起加一个鸡蛋，可以叫做塌烙馍（见视频，塌是一种烹饪方法，如山东塌煎饼），塌好的烙馍口感脆爽，早上吃一个烙馍，再来一碗辣汤，早餐就非常完整了。其他时间，还可以用烙馍卷馓子吃，口感是双重脆感，很多人也喜欢；徐州的炸串、烧烤也非常发达，不管是烧烤还是炸串，都可以用烙馍包裹着来吃，既方便又有饱腹感。
Street food in Xuzhou, Jiangsu, “lao mo” is very thin flatbread, only one millimeter thick, it requires long time cooking experience to make flatbread and the learner can not hold it. Usually people make it as street food, it have plenty ways to eat “Lao mo” from breakfast to dinner, for example, eat two “Lao mo” and an egg in the morning called “ta Lao mo”(in video, “ta” is a way to cook, like” Shan dong ta Jian bing”). “ta Lao mo” are in crispy and good texture, eat a “Lao mo” and a bowl of spicy soup make you a fully breakfast. In other time, you also can eat “Lao mo” with “ San zi” with double crispy texture, many people like it too. “Zha chuan” and BBQ is also popular in xuzhou, people usually use “lao mo” wrap and eat it. Instantly and make you full.
-----如下部分建议直接复制到上文翻译的后方-----
地址：江苏省徐州市王陵路49号陈家老味沓馍
营业时间：6:30～只卖早餐
🐟
▶雪鱼已走过近100个城市，查看当地小吃美食，请关注我的Youtube频道。
I have traveled to nearly 100 cities, check local snacks, please follow my Youtube channel.
https://bit.ly/2rdIi3G
▶我也经常在这里出现哦！Instagram：https://www.instagram.com/xueyu_foodtravel/

#烙馍 #早餐  #面食
#中国美食
#ChineseFood
字幕
1
00:00:02,150 --> 00:00:05,850
一直看街上有卖的 但是从来不知道怎么做的
Always saw it sale on street, but don’t know how to make it
2
00:00:05,850 --> 00:00:07,800
怎么形成的不知道
I don’t know how to make it
3
00:00:08,100 --> 00:00:08,800
对
Yeah
4
00:00:11,925 --> 00:00:14,100
要擀成1毫米的厚度
Rolled it into one millimeter thick 
5
00:00:22,850 --> 00:00:25,875
擀得跟纸一样 
Like paper
6
00:00:32,375 --> 00:00:35,675
雪鱼现在在徐州 待会我们要解决一下自己的早餐问题
Xueyu are in xuzhou now, we need eat some breakfast now
7
00:00:36,000 --> 00:00:40,050
在徐州当地 有一种比较特色的主食 面食 烙馍
There is a famous staple food in xuzhou called “lao mo”
8
00:00:40,325 --> 00:00:43,250
这个名字听了好久了 我待会呢 打算就是
I heard this name a lot times, I will 
9
00:00:43,300 --> 00:00:47,175
吃一个沓烙馍 用烙馍加上鸡蛋来吃
Eat a “ta lao mo” which is “lao mo” with egg
10
00:00:47,450 --> 00:00:49,700
去看看这种特色的美食是什么样的吧
Let’s take a look 
11
00:00:53,125 --> 00:00:56,100
我们今天的目的地是在一个小院子里
We come to a small yard now
12
00:01:31,275 --> 00:01:34,175
一饼一蛋5块钱 一饼两蛋6块钱
A “lao mo” with an egg is 5 yuan, and a “lao mo” with two eggs is 6 yuan
13
00:01:34,575 --> 00:01:35,950
两个饼一个蛋的
Two “lao mo” with an egg
14
00:01:36,550 --> 00:01:38,600
辣椒要不要  我要微辣的
Do you want spicy pepper? A little spicy is fine
15
00:01:38,850 --> 00:01:40,150
在这儿吃
Eat there
16
00:01:40,225 --> 00:01:41,550
来 给美女送去
Give it to beautiful lady
17
00:01:43,525 --> 00:01:44,950
还没找到地方呢
We haven’t find our seats yet
18
00:01:45,450 --> 00:01:46,900
屋里面 屋里面有地方
There are seats in room
19
00:02:06,450 --> 00:02:08,375
烙馍都是提前做好的
“Lao mo” are precooked
20
00:02:08,450 --> 00:02:09,850
客人点完就可以吃到
They can eat it immediately after order it
21
00:02:10,425 --> 00:02:14,025
咱们这个是两个饼一个蛋6块钱
Two “lao mo” and an egg is 6 yuan
22
00:02:15,375 --> 00:02:17,700
刚做出来的沓馍是又薄又脆的
Fresh “ta Lao mo” is thin and crispy
23
00:02:17,950 --> 00:02:20,175
吃一口渣渣掉的哪里都是

24
00:02:25,225 --> 00:02:27,875
咱们里面是加了葱花和一点点的辣椒的
There is some chopped green onion and few spicy pepper in it
25
00:02:27,975 --> 00:02:30,675
这么一尝 是有点油酥饼的意思的
It taste like “ you su bing”
26
00:02:30,675 --> 00:02:33,250
不过会比它更脆 因为更薄嘛
But with more crispy because it is thinner
27
00:02:37,525 --> 00:02:39,200
我在这里吃烙馍没有要汤
I didn’t ask soup for “lao mo”
28
00:02:39,300 --> 00:02:40,650
刚才阿姨进来的时候说
That’s why aunt ask me
29
00:02:40,825 --> 00:02:42,950
要不要喝的 我帮你免费盛一碗
If I want drink soup, she can give me for free
30
00:02:43,125 --> 00:02:44,750
真是太感谢阿姨了
Thanks for her
31
00:02:48,300 --> 00:02:52,150
这就是烙馍 徐州的 只有徐州有
This is “lao mo” only in xuzhou
32
00:02:52,650 --> 00:02:54,950
其他地方有类似的小吃 叫法不一样
Other city have similar street food like this but with different name
33
00:02:59,200 --> 00:03:02,570
徐州吃煎饼也蛮多的
“Jian bing” also popular in xuzhou
34
00:03:05,350 --> 00:03:08,025
 大哥说 下次我来的时候 给我做一个超脆的
Big brother said he gonna make me a super crispy “lao mo” if I come here next time
35
00:03:08,250 --> 00:03:10,825
我说 超脆的和普通的有什么样的区别
I ask, what’s the differences?
36
00:03:11,075 --> 00:03:13,050
他说 超脆的是3个饼皮
He said super crispy is three layers
37
00:03:16,750 --> 00:03:19,700
像这样的饼就是3张饼皮 超脆
Like this, super crispy
38
00:03:23,525 --> 00:03:24,900
这样的厚一点
This are thicker
39
00:03:29,375 --> 00:03:31,800
这边最忙的时候 能卖多少馍
How many “lao mo” sale most everyday?
40
00:03:32,075 --> 00:03:35,375
换算成饼 800多张吧
About 800 slices 
41
00:03:36,250 --> 00:03:38,325
光馍800多张
About 800 “lao mo”?
42
00:03:38,675 --> 00:03:40,800
做成的话就是不到400份
About less 400 copy
43
00:03:40,925 --> 00:03:42,325
400份吧
About 400
44
00:03:42,325 --> 00:03:44,825
没有四百份 三四百份
300 to 400
45
00:03:44,950 --> 00:03:48,025
平时用60多斤烙馍
About 60 pound doughs
46
00:03:48,625 --> 00:03:52,075
一斤有10张烙馍 做好卖300多份
A pound of dough can make 10 slices”lao mo”
47
00:03:52,875 --> 00:03:53,700
时间很短
In a short time
48
00:03:54,100 --> 00:04:00,825
大哥做烙馍 切开的时候一定要像搭积木这样放吗
Big brother do you have to build it as blocks after you slice it?
49
00:04:01,100 --> 00:04:02,575
立起来放的原因是 这样有利于通风
The reason to put it stand is good for making air through
50
00:04:02,850 --> 00:04:04,050
通风里面才会脆
Air make it crispy 
51
00:04:04,925 --> 00:04:08,075
把里面的热气排出来以后 它就会脆了
It get crispy after inside hot air come out
52
00:04:09,475 --> 00:04:11,350
这是最重要的
This is the most important step
53
00:04:11,350 --> 00:04:14,550
只有脆的馍才能立起来 立起来的也会更脆
Only crispy “lao mo” can stand, and stand make it more crispy
54
00:04:30,250 --> 00:04:32,350
  大哥不仅在介绍自己的烙馍
Big brother not just introduce his “lao mo”
55
00:04:32,425 --> 00:04:34,200
还向我们介绍徐州的其它小吃
He also introduce us other street foods in xuzhou
56
00:04:34,500 --> 00:04:36,450
比如说蛙鱼 把子肉 等等
Like salmon, “ba zi rou “ and so on
57
00:04:38,150 --> 00:04:40,750
中午是把子肉和各种炒菜
“Ba zi rou: and plenty of stir fry dishes at afternoon
58
00:04:42,000 --> 00:04:45,200
晚上在徐州就是吃羊肉串
kebab in the night in xuzhou 
59
00:04:45,900 --> 00:04:47,775
蛮厉害
Very good
60
00:04:47,900 --> 00:04:49,775
都是美味
All delicious 
#我蛮困的，可能有些翻译的不是特别准确，麻烦多多包涵
