### ISSUE TITLE
[华农兄弟] 华农兄弟去兄弟家看一下我们以前养的香猪已经肥的不成样了 - https://youtu.be/mupG4f7TptI

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1041]
https://youtu.be/mupG4f7TptI
<p>&#35270;&#39057;&#21457;&#24067;&#20110; May 13, 2020 at 12:18PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/mupG4f7TptI

#华农兄弟：去兄弟家看一下我们以前养的香猪，已经肥的不成样了
#Huanong Brothers: We go to our buddy and see the pigs that used to be with us. They are ridiculously fat now.

0:00:00.780,0:00:01.420
# 小狗
Doggy!

0:00:03.700,0:00:06.380
# 大家好  今天帶大家去看一下我們家的小豬
Hi everyone! Today, we're gonna take you guys to see our piggies.

0:00:06.780,0:00:09.340
# 好久都沒看  過完 過完年到現在都沒看過
I haven't seen them, haven't seen them for a long time, since, since the Chinese New Year.

0:00:09.760,0:00:11.440
# 這全部都搬到兄弟家這邊來啦
They have all moved to my buddy's site here.

0:00:12.220,0:00:15.260
# 我們那邊老是被  老是跑出去拱那個  (註︰「拱」字他發音不準)
At our site, they always ran away and snoo,

0:00:15.700,0:00:20.240
# 呃 我們 養在我們那邊老是喜歡去拱  拱那個
I mean, us, at our site, they liked going out and snout the, you know,

0:00:20.540,0:00:21.800
# 農戶的那個白菜呀
the cabbages,

0:00:22.100,0:00:23.680
# 白菜呀  包菜全部被它拱掉啦  (註︰不想太詳述是甚麼菜，又cabbage又Chinese cabbage反而欠流暢)
cabbages and other veggies of the farmers, were snouted.

0:00:24.000,0:00:24.760
# 所以我們全部
So we keep them all,

0:00:25.360,0:00:26.480
# 搞到兄弟家這邊來養
at our buddy's site here.

0:00:27.180,0:00:28.400
# 叫兄弟幫我們養
I ask my buddy to take care of them.

0:00:32.040,0:00:33.980
# 狗狗狗 狗狗狗狗狗狗
Doggy doggy, doggy doggy doggy doggy!

0:00:35.280,0:00:36.540
# 我們都那麼熟悉呀
We already know each other well enough.

0:00:37.340,0:00:38.800
# 自己人  不要咬哦
I'm your friend. Don't bite!

0:00:43.160,0:00:44.760
# 你看  這隻狗又長大啦
Look! This dog has grown up again.

0:00:45.680,0:00:46.520
# 以前還小的
He used to be very small.

0:00:46.700,0:00:48.360
# 你看  現在那麼大啦
Look! He's so big now.

0:00:50.480,0:00:52.540
# 這只狗很聽話的哦  那隻狗
This dog is a very good boy, this dog.

0:00:52.960,0:00:54.620
# 被兄弟拴起來啦
My buddy has put him on the tether.

0:00:57.080,0:00:58.700
# 呃  你不認識我了嗎
Eh! Can't you recognize me?

0:01:01.720,0:01:02.540
# 可以喲
Not bad

0:01:08.520,0:01:09.620
# 你看  這小豬
Look! This piggy,

0:01:10.540,0:01:12.660
# 我都不認識它啦  你看  肥成這樣
I can't even recognize it. Look! It's already that fat now.

0:01:13.160,0:01:14.060
# 變成這樣
It's that fat now.

0:01:15.460,0:01:16.060
# 小胖豬
Chubby piggy!

0:01:20.760,0:01:22.960
# 呵呵  全部掉毛了  哈哈~
Hmhm! They're all shedding hair, haha~

0:01:23.400,0:01:26.040
# 你看  上次抓過來還那麼小的
Look! It was still very small when I took it here last time.

0:01:26.400,0:01:26.940
# 現在
But now,

0:01:27.640,0:01:29.780
# 呵呵  不敢去抱啦  那麼大啦
Hmhm. I dare not take it anymore. It's so big now.

0:01:30.100,0:01:31.820
# 你看 這個  上次我們
Look! This one, when we,

0:01:32.640,0:01:35.840
# 我們  在我們那裡的時候瘦的  瘦的皮包骨一樣
us, when it was with us, it was really skinny, just like a skeleton.

0:01:35.880,0:01:36.540
# 你看  現在
Look! It's now,

0:01:37.180,0:01:38.240
# 變成這樣子啦
is already that fat now.

0:01:38.760,0:01:41.460
# 天左給它餵吃飼料  吃的好飽哇
They have fodder every day and are always stuffed with food.

0:01:43.720,0:01:44.260
# 小豬
Piggy!

0:01:45.140,0:01:46.900
# 小豬  還認不認識我
Piggy! Can you still recognize me?

0:01:48.640,0:01:49.560
# 都不理我啦
It's not answering me.

0:01:49.560,0:01:50.140
# 你看
Look!

0:01:50.640,0:01:51.140
# 這個
These are,

0:01:52.160,0:01:54.280
# 山上的野豬下來雜交出來的   (註︰他是說野豬下來的，我只好照譯)
bred from the boars coming down from the hill.

0:02:00.260,0:02:01.200
# 好尖嘴呀
They have really sharp snouts.

0:02:02.420,0:02:04.660
# 你看  它的嘴巴有點歪歪的那個
Look! This is the one whose snout is not really that straight.

0:02:04.860,0:02:06.680
# 現在都胖成這樣子啦
It's already that fat now.

0:02:07.380,0:02:08.060
# 你看  這個
Look! This is,

0:02:09.160,0:02:11.620
# 白腳的那個豬  變成這樣子啦
the pig with white feet. It's already that fat now.

0:02:12.940,0:02:13.920
# 吃太多啦
It eats too much.

0:02:14.720,0:02:15.920
# 你看  這個就是
Look! These are,

0:02:16.440,0:02:17.420
# 巴拿馬香豬  (註︰他又双叒叕說錯了，為保障我國肉品品牌和實現文化輸出的重要任務，我決定破例更正)
Bama pigs.

0:02:18.240,0:02:19.820
# 嗯 嗯  有點不像一樣
Um? Um? But they look a bit different.

0:02:21.240,0:02:22.220
# 嘴巴怎麼那麼尖
Why are their snouts so shapr?

0:02:24.920,0:02:26.220
# 這些豬都好肥啊
These pigs are all so fat,

0:02:27.300,0:02:28.600
# 胖成甚麼樣子了
that I don't even know how to describe.

0:02:30.220,0:02:31.260
# 還會喝水的哦
They can drink water here too.

0:02:31.320,0:02:32.040
# 在我們那裡
They didn't even have water,

0:02:32.980,0:02:33.880
# 水都沒得喝
when they were with us.

0:02:36.240,0:02:37.660
# 你看  這邊都被挖平啦
Look! The area here has already been flattened.

0:02:38.240,0:02:39.860
# 兄弟準備再做一個廠房
My buddy is going to build a new site here,

0:02:39.980,0:02:41.280
# 把豬養多一點
to keep more pigs.

0:02:44.280,0:02:45.140
# 好大啊  那裡
It's really big over there,

0:02:45.620,0:02:46.840
# 上千平方都有
up to a thousand square metres.

0:02:47.760,0:02:49.900
# 豬看完了哦  我們準備回去啦
So that's all with the pigs. We're getting ready to go back.

0:02:50.500,0:02:52.200
# 從這裡上去  就直接回去啦
We walk up from here, then we can go back right away.

0:02:56.800,0:02:58.860
# 你看  這些白鴨好漂亮哦
Look! These white ducks are really pretty.

0:03:00.040,0:03:00.860
# 來都來啦
I'm already here,

0:03:02.300,0:03:03.380
# 裝一個鴨子回去
let me catch a duck back home.

0:03:22.280,0:03:23.220
# 這裡一個網
Here's a net.

0:03:27.020,0:03:28.200
# 趕過來  走過來
Drive them here! You come here!

0:03:28.780,0:03:29.840
# 不用趕  就這隻
No, no need. Catch this one!

0:03:29.840,0:03:30.700
# 嗯  你走過來
Um! You walk towards me.

0:03:31.300,0:03:32.320
# 慢慢的走過來
Walk towards me, slowly.

0:03:53.240,0:03:54.540
# 搞了一個七八十斤
This one is almost forty kilograms,

0:03:55.080,0:03:55.860
# 七八斤
I mean almost four kilograms

0:03:56.820,0:03:57.980
# 回去啦  回去啦
Let's go! Let's go!

0:03:59.500,0:04:01.280
# 那裡還有哦  下次再來
There are some more. I'll come again next time.

0:04:21.060,0:04:23.940
# 這個比鵝還更大的鴨子 這隻白鴨來的
This duck is even larger than a goose. It's a white duck.

0:04:26.280,0:04:27.040
# 把它放下
I put it down.

0:04:27.680,0:04:29.960
# 呃  以後這裡就是你的家了啊
Eh! This is your home from now on.

0:04:31.000,0:04:31.700
# 減一下肥
Let me put you on a diet.

0:04:32.040,0:04:32.820
# 太胖啦
You're too fat.

0:04:33.240,0:04:34.020
# 下不了口
I don't wanna put you into my mouth.

0:04:35.600,0:04:37.600
# 摸一下你  怎麼這樣子
I'm just petting you. What does your response mean?

0:04:40.880,0:04:42.600
# 你看  這就是你的小伙伴
Look! These are your little buddies.

0:04:42.880,0:04:43.680
# 看到沒
Can you see them?

0:04:44.480,0:04:45.140
# 把它放啦
Okay, I let it go.

0:04:50.800,0:04:51.820
# 比鵝還更大呀
It's even bigger than the geese.

0:05:09.640,0:05:10.640
# 比鵝還更大
It's even bigger than the geese.

0:05:12.060,0:05:13.440
# 太小啦  這些鴨子
They're too small, these ducks.

0:05:14.440,0:05:16.080
# 看上去這些鴨子好小呀
These ducks look really small.

0:05:19.080,0:05:19.640
# 好啦
Alright

0:05:20.740,0:05:21.760
# 讓它們這鴨子
I'm gonna leave them alone,

0:05:22.340,0:05:23.560
# 自由自在的活著
and have their worriless life here.

0:05:24.320,0:05:25.700
# 多好哇  是不是
Awesome, isn't it?

0:05:26.060,0:05:27.400
# 你們是夠幸福的啦
You guys are really privileged, you know.

0:05:28.280,0:05:29.860
# 其它鴨子全部都進啦
The other ducks are all in the,

0:05:30.060,0:05:30.980
# 進了市場
in the market,

0:05:31.820,0:05:32.920
# 變成了白條
and have become steamed ducks.

0:05:33.920,0:05:35.340
# 你看一下你們 是啊
Compare with yourselves, see?

0:05:37.280,0:05:38.680
# 個個都活著多好哇
You're so blessed to be all alive.

0:05:41.960,0:05:44.400
# 好啦  今天的視頻就到  就到這裡啦
Alright! The video ends, ends here.

0:05:44.420,0:05:45.280
# 要等它們下蛋
I need to wait for their eggs.

0:05:46.600,0:05:48.460
# 應該差不多有蛋下啦  那麼久啦
I think they should be laying eggs very soon. They've been here long enough.
