### ISSUE TITLE
【美食作家王刚】泡椒腰花 - https://youtu.be/1KmoBNSNEc0

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1044]
**视频链接**：https://youtu.be/1KmoBNSNEc0

视频时长4:14，预计发布时间为北京时间5月16日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“泡椒腰花”的简单刀工做法，味道巴适，超级下饭

简介
同学们好，今天教大家一道“泡椒腰花”的简单家常做法，很多朋友看过之前的腰花料理都觉得刀功劝退，切起来实在太难，本期视频就教大家一种特别简单的方法，只需要直刀就可以轻松切出腰花，虽说卖相不如斜刀但的确容易很多，并且味道和口感上并无明显区别。如果想学更加进阶的刀工可以点击之前的视频教学，链接在此：https://www.youtube.com/watch?v=xuJJpTHfiu8&t=41s

本期菜品【泡椒腰花】
【主料】
猪腰（一对）
【辅料】
干淀粉（适量）
红泡椒（30克）
大蒜（15克）
生姜（1小块）
大葱（几根）
藿香叶（适量）
植物油（适量）
水淀粉（适量）
【调味料】
食用盐（少许）
胡椒粉（适量）
料酒（2克）
生抽酱油（5克）
老抽（少许）
红油豆瓣酱（3克）
鸡精（1克）
白糖（少许）

字幕
0:00:00.000,0:00:01.400
哈喽大家好我是王刚

0:00:01.400,0:00:03.320
本期视频我跟大家分享一道家常菜

0:00:03.740,0:00:04.900
泡椒腰花

0:00:05.100,0:00:06.900
首先我们准备猪腰1对

0:00:06.900,0:00:09.875
从中间片开之后再小心翼翼地去除腰骚

0:00:10.025,0:00:12.075
一般来说菜刀越薄越好切

0:00:22.734,0:00:24.749
去除腰骚之后下一步开始改刀

0:00:25.052,0:00:27.119
这里跟大家分享一个最简单的切法

0:00:27.233,0:00:29.311
首先我们将腰花竖着切进三分之二

0:00:29.405,0:00:31.336
每一刀之间间隔3毫米即可

0:00:31.659,0:00:33.037
同学们切记不要切断

0:00:33.475,0:00:36.263
然后转过来横着以同样的方式切进三分之二

0:00:36.649,0:00:38.340
再切到第二刀的时候切断

0:00:42.045,0:00:43.966
猪腰切好之后下一步放入碗中

0:00:44.519,0:00:47.317
再加入适量的清水清洗几遍去除血水和骚味

0:00:52.724,0:00:55.574
清洗干净之后捞出挤干水分下一步开始腌制

0:00:55.939,0:00:58.152
首先我们在碗中加入少许的食用盐（约0.3克）

0:00:58.820,0:01:00.114
加入一小半勺胡椒粉

0:01:00.699,0:01:01.753
加入料酒2克

0:01:03.141,0:01:04.436
加入生抽酱油2克

0:01:05.334,0:01:06.805
加入少许的老抽调色

0:01:08.705,0:01:10.626
最后加入几勺干淀粉搅拌均匀

0:01:10.803,0:01:12.787
同学们料汁最好调成略微干一些

0:01:12.901,0:01:14.258
这样能防止脱浆

0:01:22.567,0:01:25.313
然后加入洗干净的腰花轻轻的搅拌均匀备用

0:01:28.580,0:01:31.273
同学们切记下手别太重防止把腰花抓烂

0:01:35.929,0:01:37.244
下一步开始准备辅料

0:01:38.089,0:01:39.937
准备红泡椒30克切碎备用

0:01:44.008,0:01:46.242
准备大蒜15克拍散之后切碎备用

0:01:52.212,0:01:53.903
准备生姜1小块剁碎备用

0:02:02.609,0:02:05.041
准备大葱几根从中间破开之后切碎备用

0:02:14.728,0:02:16.680
最后准备适量的藿香叶切碎备用

0:02:17.014,0:02:20.814
没有藿香的同学可以根据个人口味用香菜或者紫苏代替

0:02:24.759,0:02:25.845
下一步开始制作

0:02:26.461,0:02:27.860
首先我们把锅烧热

0:02:28.215,0:02:30.000
锅烧热之后加入适量的底油（35克左右）

0:02:31.701,0:02:34.551
油温烧至5成热之后将腌制好的腰花下锅滑散

0:02:34.947,0:02:37.286
同学们腰花下锅之前最好先再次拌匀

0:02:47.275,0:02:49.603
腰花滑散之后加入切好的辅料爆香（生姜，大蒜，泡椒）

0:02:57.056,0:02:58.893
中途加入红油豆瓣酱3克

0:03:04.060,0:03:07.025
豆瓣酱炒香之后再加入生抽酱油3克从锅边淋入

0:03:09.206,0:03:10.375
然后开始调味

0:03:10.699,0:03:12.045
锅中加入鸡精1克

0:03:13.100,0:03:14.342
加入少许白糖

0:03:15.125,0:03:17.630
调好味之后加入适量的水淀粉离火勾芡

0:03:24.227,0:03:26.054
再加入切好的大葱翻炒几下

0:03:32.014,0:03:34.989
最后加入切好藿香叶翻炒均匀即可出锅装盘

0:03:50.500,0:03:52.920
一道非常美味的泡椒腰花就制作完成

0:03:55.740,0:04:13.600
下面开始技术总结
第一，为了保证腰花不被抓烂，必须先把调料拌匀化开再搅拌
第二，小煎小炒一锅成菜属于自贡著名炒法，底油可以适量的大一些
第三，没有藿香的同学可以用香菜，芹菜叶，或者紫苏代替
泡椒猪腰的技术总结完毕

```

**Comment by Yibing-Du** [comment]
bot, please upload
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“泡椒腰花”的简单刀工做法，味道巴适，超级下饭
Chef Wang Teaches You: Pork Kidney with Pickled Chili, No Knife Skill and Great with Rice

简介
Introduction
同学们好，今天教大家一道“泡椒腰花”的简单家常做法，很多朋友看过之前的腰花料理都觉得刀功劝退，切起来实在太难，本期视频就教大家一种特别简单的方法，只需要直刀就可以轻松切出腰花，虽说卖相不如斜刀但的确容易很多，并且味道和口感上并无明显区别。如果想学更加进阶的刀工可以点击之前的视频教学，链接在此：https://www.youtube.com/watch?v=xuJJpTHfiu8&t=41s
Hello everyone! Today I'm teaching an easy, everyday dish, Pork Kidney with Pickled Chili. Many of you who've watched previous episodes about pork kidney find it too hard to cut it nicely, so this time we'll make it simple. Just cut it the normal way, which doesn't quite look as nice but is much easier and tastes the same. If you want to learn advanced knife skills, here's the link: https://www.youtube.com/watch?v=xuJJpTHfiu8&t=41s

本期菜品【泡椒腰花】
Dish in this episode: Pork Kidney with Pickled Chili
【主料】
Main ingredients
猪腰（一对）
Pork kidney (a pair)
【辅料】
Side ingredients
干淀粉（适量）
Starch (some)
红泡椒（30克）
Red pickled chili (30g)
大蒜（15克）
Garlic (15g)
生姜（1小块）
Ginder (a small piece)
大葱（几根）
Green onions (a few)
藿香叶（适量）
Huoxiang leaves (some)
植物油（适量）
Vegetable oil (some)
水淀粉（适量）
Water starch (some)
【调味料】
Seasonings
食用盐（少许）
Salt (some)
胡椒粉（适量）
Ground pepper (some)
料酒（2克）
Chinese cooking wine (2g)
生抽酱油（5克）
Light soy sauce (5g)
老抽（少许）
Dark soy sauce (a little)
红油豆瓣酱（3克）
Chili oil doubanjiang (3g)
鸡精（1克）
Chicken bouillon powder (1g)
白糖（少许）
Sugar (a little)

字幕
0:00:00.000,0:00:01.400
哈喽大家好我是王刚
Hello everyone, I'm Wang Gang
0:00:01.400,0:00:03.320
本期视频我跟大家分享一道家常菜
In this video, I'll share the recipe of an everyday dish
0:00:03.740,0:00:04.900
泡椒腰花
Pork Kidney with Pickled Chili
0:00:05.100,0:00:06.900
首先我们准备猪腰1对
First, we prepare a pair of pork kidneys
0:00:06.900,0:00:09.875
从中间片开之后再小心翼翼地去除腰骚
Slice it open in the middle and carefully remove the extra parts
0:00:10.025,0:00:12.075
一般来说菜刀越薄越好切
The thinner your knife is, the easier it is to cut it
0:00:22.734,0:00:24.749
去除腰骚之后下一步开始改刀
After removing the extra parts, start cutting it
0:00:25.052,0:00:27.119
这里跟大家分享一个最简单的切法
Now I'll share the easiest way to do it
0:00:27.233,0:00:29.311
首先我们将腰花竖着切进三分之二
First we cut through 2/3 of it
0:00:29.405,0:00:31.336
每一刀之间间隔3毫米即可
And make sure there's 3mm between each cut 
0:00:31.659,0:00:33.037
同学们切记不要切断
Make sure don't cut it all the way through
0:00:33.475,0:00:36.263
然后转过来横着以同样的方式切进三分之二
Then turn it arround and cut through 2/3 in the same way
0:00:36.649,0:00:38.340
再切到第二刀的时候切断
At the second cut, cut it through
0:00:42.045,0:00:43.966
猪腰切好之后下一步放入碗中
After we're done cutting, put it in the bowl
0:00:44.519,0:00:47.317
再加入适量的清水清洗几遍去除血水和骚味
Add some water to rinse it several times to remove the blood and the smell
0:00:52.724,0:00:55.574
清洗干净之后捞出挤干水分下一步开始腌制
After cleansing, get rid of the water and start marinating
0:00:55.939,0:00:58.152
首先我们在碗中加入少许的食用盐（约0.3克）
First we add some salt to the bowl (around 0.3g)
0:00:58.820,0:01:00.114
加入一小半勺胡椒粉
Add half a teaspoon of ground pepper
0:01:00.699,0:01:01.753
加入料酒2克
Add 2g of Chinese cooking wine
0:01:03.141,0:01:04.436
加入生抽酱油2克
Add 2g of light soy sauce
0:01:05.334,0:01:06.805
加入少许的老抽调色
Add some dark soy sauce for the color
0:01:08.705,0:01:10.626
最后加入几勺干淀粉搅拌均匀
Finally add a few teaspoons of starch and mix it
0:01:10.803,0:01:12.787
同学们料汁最好调成略微干一些
It'll be the best if the marinade is not too diluted
0:01:12.901,0:01:14.258
这样能防止脱浆
So that it doesn't come off
0:01:22.567,0:01:25.313
然后加入洗干净的腰花轻轻的搅拌均匀备用
Then add the cleaned pork kidneys and gently stir
0:01:28.580,0:01:31.273
同学们切记下手别太重防止把腰花抓烂
Remember to be gentle or the pork kidneys would fall apart
0:01:35.929,0:01:37.244
下一步开始准备辅料
Now let's prepare the minor ingredients
0:01:38.089,0:01:39.937
准备红泡椒30克切碎备用
Prepare 30g of red pickled chili and mince them
0:01:44.008,0:01:46.242
准备大蒜15克拍散之后切碎备用
Prepare 15g of garlic and mince it
0:01:52.212,0:01:53.903
准备生姜1小块剁碎备用
Prepare a small piece of ginger and mince it
0:02:02.609,0:02:05.041
准备大葱几根从中间破开之后切碎备用
Prepare a few green onions, slice it in the middle, and mince it
0:02:14.728,0:02:16.680
最后准备适量的藿香叶切碎备用
Finally prepare some Huoxiang leaves and mince it
0:02:17.014,0:02:20.814
没有藿香的同学可以根据个人口味用香菜或者紫苏代替
If you don't have it, you can use cilantro or Perilla
0:02:24.759,0:02:25.845
下一步开始制作
Next start making the dish
0:02:26.461,0:02:27.860
首先我们把锅烧热
First we heat up the wok
0:02:28.215,0:02:30.000
锅烧热之后加入适量的底油（35克左右）
After it's heated, add some base oil (35g)
0:02:31.701,0:02:34.551
油温烧至5成热之后将腌制好的腰花下锅滑散
When it's 150 degrees, add the marinated pork kidneys
0:02:34.947,0:02:37.286
同学们腰花下锅之前最好先再次拌匀
It's the best to mix them again beforehand
0:02:47.275,0:02:49.603
腰花滑散之后加入切好的辅料爆香（生姜，大蒜，泡椒）
After they're no longer sticking together, add the minor ingredients to stir fry together (ginger, garlic, pickled chili)
0:02:57.056,0:02:58.893
中途加入红油豆瓣酱3克
Add 3g of chili oil doubanjiang
0:03:04.060,0:03:07.025
豆瓣酱炒香之后再加入生抽酱油3克从锅边淋入
After you start to smell it, add 3g of light soy sauce from the side
0:03:09.206,0:03:10.375
然后开始调味
Then start seasoning
0:03:10.699,0:03:12.045
锅中加入鸡精1克
Add 1g of Chicken bouillon powder to the wok
0:03:13.100,0:03:14.342
加入少许白糖
Add some sugar
0:03:15.125,0:03:17.630
调好味之后加入适量的水淀粉离火勾芡
After seasoning, add some water starch and remove the wok from the stove
0:03:24.227,0:03:26.054
再加入切好的大葱翻炒几下
Add minced green onions and mix it
0:03:32.014,0:03:34.989
最后加入切好藿香叶翻炒均匀即可出锅装盘
Finally add the cutted Huoxiang leaves and mix it properly. Now it's ready
0:03:50.500,0:03:52.920
一道非常美味的泡椒腰花就制作完成
We've made a very delicious dish: Pork Kidney with Pickled Chili
0:03:55.740,0:04:13.600
下面开始技术总结
第一，为了保证腰花不被抓烂，必须先把调料拌匀化开再搅拌
第二，小煎小炒一锅成菜属于自贡着名炒法，底油可以适量的大一些
第三，没有藿香的同学可以用香菜，芹菜叶，或者紫苏代替
泡椒猪腰的技术总结完毕
Now let's summarize the key techniques
First, to make sure the pork kidney doesn't fall apart in the marinade, make sure we mix the marinade properly
Secondly, mildly stir-frying in one wok is a famous technique in Zigong, and we can add slightly more base oil
Thirdly, if you don't have Huoxiang leaves, you can use cilantro, celery, or Perilla
Above is all techniques for Pork Kidney with Pickled Chili
