### ISSUE TITLE
【美食作家王刚】脆皮花生豆 - https://youtu.be/oIqrNujoE08

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1048]
**视频链接**：https://youtu.be/oIqrNujoE08

视频时长3:43，预计发布时间为北京时间5月17日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“脆皮花生豆”的零食加工厂做法，香辣酥脆，果仁的经典做法，可以衍生出各种味道

简介
同学们好，今天和大家分享一道经典传统小吃“脆皮花生豆”，将花生裹在调过味的面中，再经过宽油炸制，使花生米增加了更多的风味，并且特别的酥脆。大家在超市买到的各种口味的脆皮花生基本上也都是用此方法制作而成，大家学会这种方法之后可以尝试各种口味，比如加入芥末粉或者糖来调味，做出自己喜欢的风味。

本期菜品【脆皮花生米】
【主料】
花生米（500克）
【辅料】
鸡蛋（2个）
面粉（适量）
植物油（适量）
【调味料】
食用盐（约3克）
花椒面（1克）
辣椒面（适量）
五香粉（一勺）

字幕
0:00:00.340,0:00:01.420
哈喽大家好我是王刚

0:00:01.420,0:00:03.000
本期视频我跟大家分享

0:00:03.880,0:00:05.060
脆皮花生米

0:00:05.540,0:00:08.320
首先我们准备花生米500克放入盆中

0:00:08.500,0:00:11.325
然后加入适量的清水将其浸泡10分钟备用

0:00:11.350,0:00:14.200
这一步的目的是去除杂质和发涨花生皮

0:00:24.450,0:00:27.000
10分钟之后将花生米捞出沥干水分备用

0:00:28.425,0:00:30.100
下一步开始调味上糊

0:00:30.625,0:00:32.625
首先在盆中加入鸡蛋2个

0:00:36.250,0:00:37.750
加入食用盐2勺（约3克）

0:00:39.500,0:00:41.025
加入花椒面1克

0:00:41.500,0:00:42.925
加入适量的辣椒面

0:00:43.025,0:00:45.000
不能吃麻辣的同学可以不加

0:00:45.125,0:00:46.600
加入五香粉1勺（约2克）

0:00:47.300,0:00:48.725
然后搅拌均匀

0:00:51.825,0:00:54.275
搅拌均匀之后开始分多次加入面粉

0:00:54.400,0:00:56.500
同学们切记必须分多次加入

0:00:56.550,0:00:59.000
直到花生米每一粒都颗粒分明即可

0:00:59.000,0:01:01.775
这一步的目的是给花生米穿上一层脆皮衣

0:01:02.000,0:01:04.875
如果不喜欢太多脆皮可以减少鸡蛋和面粉

0:01:47.025,0:01:49.250
最后再将多余的小面团筛除即可

0:01:58.425,0:01:59.775
下一步开始制作

0:01:59.825,0:02:01.350
首先我们把锅烧热

0:02:01.550,0:02:03.150
锅烧热之后加入宽油

0:02:11.000,0:02:13.350
油温烧至5成热之后开始转小火

0:02:15.400,0:02:17.050
再下入处理好的花生米

0:02:20.875,0:02:22.750
然后开中小火炸4分钟

0:02:29.150,0:02:31.675
中途的时候用细漏去除脱落的细渣

0:02:31.675,0:02:34.000
这一步的目的是保护宽油的二次使用

0:02:39.200,0:02:43.025
同学们炸制的时候必须随时推动花生米使其均匀受热

0:02:53.600,0:02:56.000
当花生米炸至略香之后即可捞出

0:02:56.175,0:02:59.800
因为花生米的内部有强烈的预热会继续自熟

0:03:00.100,0:03:03.200
如果在锅中刚好够脆则说明已经炸制过火

0:03:03.200,0:03:06.100
炸制过火的花生米出锅冷却之后容易变糊

0:03:06.300,0:03:08.600
4分钟之后捞出凉透即可食用

0:03:14.900,0:03:18.020
一道香脆可口的脆皮花生米就制作完成

0:03:26.160,0:03:42.800
下面开始技术总结
第一，不能吃辣的同学可以不加辣椒面和花椒
第二，最后上粉必须达到每一颗花生米颗粒分明
第三，新手在炸的过程中可以不断的捞出花生米尝口感，但必须小心花生米烫嘴
脆皮花生米的技术总结完毕


```

**Comment by Kevinzheng5** [comment]
认领

**Comment by Kevinzheng5** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“脆皮花生豆”的零食加工厂做法，香辣酥脆，果仁的经典做法，可以衍生出各种味道
Chef Wang shares with you: Snack style “Crispy Peanuts”, crispy, spicy and delicious. Classic way to cook nuts and it can be twisted into more tastes.

简介
同学们好，今天和大家分享一道经典传统小吃“脆皮花生豆”，将花生裹在调过味的面中，再经过宽油炸制，使花生米增加了更多的风味，并且特别的酥脆。大家在超市买到的各种口味的脆皮花生基本上也都是用此方法制作而成，大家学会这种方法之后可以尝试各种口味，比如加入芥末粉或者糖来调味，做出自己喜欢的风味。
Hey guys, today I’ll share a traditional snack “Crispy Peanuts” with you. Coat the peanuts with seasoned flour and fry it. It adds a lot flavor into the peanuts and makes it extra crispy. The peanuts we can get from the supermarkets are also usually cooked in this way. Adding some wasabi or sugar can add different twists to the flavor and give you the best one you’d like!

本期菜品【脆皮花生米】
【主料】
[Ingredients]
花生米（500克）
Peanuts(500 grams or about a pound)
【辅料】
[Other ingredients]
鸡蛋（2个）
Eggs(2)
面粉（适量）
Some flour
植物油（适量）
Vegetable oil
【调味料】
[Seasoning]
食用盐（约3克）
Salt
花椒面（1克）
Peppercorn powder
辣椒面（适量）
Red chili powder
五香粉（一勺）
Five-spices powder

字幕
0:00:00.340,0:00:01.420
哈喽大家好我是王刚
Hi y’all, it’s Wang Gang

0:00:01.420,0:00:03.000
本期视频我跟大家分享
In this episode, I’ll share

0:00:03.880,0:00:05.060
脆皮花生米
A snack called crispy peanuts

0:00:05.540,0:00:08.320
首先我们准备花生米500克放入盆中
First we prepare about 500 grams of peanuts into a bowl

0:00:08.500,0:00:11.325
然后加入适量的清水将其浸泡10分钟备用
Add some water to soak them for 10 minutes

0:00:11.350,0:00:14.200
这一步的目的是去除杂质和发涨花生皮
This is to rinse the peanuts and soften their skins

0:00:24.450,0:00:27.000
10分钟之后将花生米捞出沥干水分备用
After 10 minutes, get them out and dry

0:00:28.425,0:00:30.100
下一步开始调味上糊
Next it’s the seasoning and coating

0:00:30.625,0:00:32.625
首先在盆中加入鸡蛋2个
First, two eggs in the bowl

0:00:36.250,0:00:37.750
加入食用盐2勺（约3克）
Add about 2 spoons of salt

0:00:39.500,0:00:41.025
加入花椒面1克
One spoon of peppercorn powder

0:00:41.500,0:00:42.925
加入适量的辣椒面
Also some red chili powder

0:00:43.025,0:00:45.000
不能吃麻辣的同学可以不加
If you don’t handle hot food well, hold the peppercorn and chili powder

0:00:45.125,0:00:46.600
加入五香粉1勺（约2克）
Then a spoon and five-spices powder

0:00:47.300,0:00:48.725
然后搅拌均匀
Mix them well

0:00:51.825,0:00:54.275
搅拌均匀之后开始分多次加入面粉
After it’s well mixed, add flour in successively

0:00:54.400,0:00:56.500
同学们切记必须分多次加入
It’s really important that we add the flour in steps

0:00:56.550,0:00:59.000
直到花生米每一粒都颗粒分明即可
Until every peanut gets evenly coated

0:00:59.000,0:01:01.775
这一步的目的是给花生米穿上一层脆皮衣
This process is to make a crispy coat for the peanuts

0:01:02.000,0:01:04.875
如果不喜欢太多脆皮可以减少鸡蛋和面粉
If you like the coats lighter, hold the eggs and flour

0:01:47.025,0:01:49.250
最后再将多余的小面团筛除即可
At last, pick the redundant flour out

0:01:58.425,0:01:59.775
下一步开始制作
Now let’s cook the peanuts

0:01:59.825,0:02:01.350
首先我们把锅烧热
First we heat up the wok

0:02:01.550,0:02:03.150
锅烧热之后加入宽油
Then add Kuan You (broad oil) in the wok

0:02:11.000,0:02:13.350
油温烧至5成热之后开始转小火
When the oil is about 150 degrees Celsius (300 degrees F), turn down the burner

0:02:15.400,0:02:17.050
再下入处理好的花生米
Drop the peanuts in

0:02:20.875,0:02:22.750
然后开中小火炸4分钟
Fry at mid-low temperature for 4 minutes

0:02:29.150,0:02:31.675
中途的时候用细漏去除脱落的细渣
Filter out the dropping scums during frying

0:02:31.675,0:02:34.000
这一步的目的是保护宽油的二次使用
So that we can still use the oil later

0:02:39.200,0:02:43.025
同学们炸制的时候必须随时推动花生米使其均匀受热
It’s important that we stir the peanuts during frying to make them evenly cooked

0:02:53.600,0:02:56.000
当花生米炸至略香之后即可捞出
When the aroma comes out, we can get the peanuts out of the wok

0:02:56.175,0:02:59.800
因为花生米的内部有强烈的预热会继续自熟
The high temperature inside the peanuts will continue cooking themselves

0:03:00.100,0:03:03.200
如果在锅中刚好够脆则说明已经炸制过火
If it’s already crispy out of the wok, it’s overcooked

0:03:03.200,0:03:06.100
炸制过火的花生米出锅冷却之后容易变糊
Then it will become dark and bitter as it cools down

0:03:06.300,0:03:08.600
4分钟之后捞出凉透即可食用
After 4 minutes, peanuts out of the wok and they will be ready once they cool down

0:03:14.900,0:03:18.020
一道香脆可口的脆皮花生米就制作完成
And our crispy peanuts are done!

0:03:26.160,0:03:42.800
下面开始技术总结
第一，不能吃辣的同学可以不加辣椒面和花椒
第二，最后上粉必须达到每一颗花生米颗粒分明
第三，新手在炸的过程中可以不断的捞出花生米尝口感，但必须小心花生米烫嘴
脆皮花生米的技术总结完毕
Now it’s the technical conclusion
First, if you don’t like the peanuts to be too hot, hold the red chili and peppercorn powder
Second, Make sure the peanuts are evenly coated
Third, as noobs, you can constantly taste the peanuts during frying to see the texture changing but be careful when they are hot!
That’s it for the conclusion of our “Crispy Peanuts”!
