### ISSUE TITLE
[华农兄弟] 华农兄弟去小河里抓点螃蟹来烤又香又脆很好吃哦 - https://youtu.be/kXitln8OnfI

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1049]
https://youtu.be/kXitln8OnfI
<p>&#35270;&#39057;&#21457;&#24067;&#20110; May 15, 2020 at 11:30AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/kXitln8OnfI

#华农兄弟：去小河里抓点螃蟹来烤，又香又脆，很好吃哦
#Huanong Brothers: We go to the river and catch some crabs. We then grill them. Crispy and tasty!

0:00:00.000,0:00:02.180
# 大家好  我們去摘點那個螃蟹來吃
Hi everyone! We're gonna pick some crabs.

0:00:02.360,0:00:03.000
# 哦  不是
Ah, no!

0:00:03.540,0:00:04.640
# 摘萢子  說錯了
Pick berries. I mixed them up.

0:00:05.280,0:00:06.520
# 抓螃蟹  摘萢子
Catch the crabs, pick the berries.

0:00:07.360,0:00:09.620
# 這個路邊上的這個萢子  很好吃的哦
The berries on the, well, on the road, are really tasty, you know.

0:00:09.960,0:00:12.580
# 你看這些農村  農村的好多地方的萢子
Look! These are the berries, these are the berries which grow in many places in the villages.

0:00:13.280,0:00:14.300
# 都沒人摘來吃
But nobody picks them.

0:00:15.340,0:00:16.000
# 太浪費啦
What a waste!

0:00:18.780,0:00:19.940
# 我來消滅它們
Let me tackle them.

0:00:22.380,0:00:23.840
# 這種萢子就熟透啦  這種
This kind of berries are fully ripe, this one.

0:00:24.180,0:00:24.940
# 烏黑發亮
It's shiny dark.

0:00:28.100,0:00:28.600
# 啊~
Ah~

0:00:29.220,0:00:30.320
# 你看  這路邊上
Look! The peaches are everywhere,

0:00:31.100,0:00:32.280
# 到處都是桃子
on the side of the path.

0:00:32.880,0:00:34.400
# 好多啊  一樹都是
A lot! All over the tree

0:00:35.140,0:00:36.640
# 沒熟  等熟了時候
They're still green. I'll ask my buddy to come with me,

0:00:37.480,0:00:38.480
# 我叫兄弟過來一起
when they become ripe.

0:00:39.840,0:00:41.180
# 兄弟很喜歡吃桃子的哦
My buddy loves peaches, you know.

0:00:47.440,0:00:49.400
# 你看  有好多這個  萢子
Look! Here are a lot of this kind of, berries.

0:00:51.940,0:00:52.820
# 又好又紅
Big and red

0:00:55.860,0:00:56.360
# 誒呀
Eya!

0:00:57.560,0:00:58.540
# 這樣吃才過癮
This is the best way to enjoy the berries.

0:01:01.240,0:01:02.780
# 上次我們吃把它串起來吃
We skewed them up last time.

0:01:04.320,0:01:05.220
# 這樣子走  
But I think make,

0:01:05.720,0:01:07.300
# 走  走那個形式不好啊
make, making too much gimmick is not my style.

0:01:07.600,0:01:08.700
# 直接摘來吃就好了
I prefer simply picking it and putting it into my mouth.

0:01:10.300,0:01:11.960
# 串來 串起來還不是一樣吃
Skew, skewing them up makes no difference.

0:01:14.440,0:01:15.380
# 啊  這個
Ah! This is...

0:01:15.720,0:01:16.480
# 誒  壞的
Eh? It's rotten.

0:01:16.960,0:01:17.620
# 太熟了
It's too ripe.

0:01:21.660,0:01:22.380
# 你看這個
Have a look at this one.

0:01:23.120,0:01:23.960
# 烏黑發亮
It's shiny dark!

0:01:26.540,0:01:27.740
# 用嘴巴一吸
Suck it with the mouth,

0:01:28.780,0:01:29.280
# 就
then,

0:01:30.620,0:01:31.340
# 就吃掉啦
then it's swallowed.

0:01:32.800,0:01:33.320
# 你看
Look!

0:01:34.040,0:01:34.680
# 這一些
These are...

0:01:38.480,0:01:39.160
# 這個壞的
This is rotten.

0:01:40.320,0:01:41.220
# 好多啦
There are too many.

0:01:45.160,0:01:47.040
# 嗯  剛好看到一個臭屁蟲
Um! I just saw a stink bug.

0:01:48.180,0:01:50.360
# 從這裡走過  有點臭  臭屁蟲的味道
It just passed by. So this one is a bit stinky, with the smell of a stink bug.

0:01:50.540,0:01:51.040
# 不要啦
Pass!

0:01:54.660,0:01:56.420
# 哇  這上面好多啊
Wa! There are a lot up there!

0:01:58.080,0:01:59.780
# 甚麼都不搞那麼快  哎呀
There's nothing urgent. Aya!

0:02:00.120,0:02:01.120
# 先吃飽再行動
Let's fill up our stomachs first.

0:02:06.400,0:02:07.420
# 這裡的全都壞的
These here are all rotten.

0:02:28.800,0:02:29.300
# 嗯
Um!

0:02:30.540,0:02:31.120
# 不好吃
No good.

0:02:31.920,0:02:32.660
# 好酸吶
It's so sour.

0:02:34.000,0:02:35.300
# 這裡面的品種不一樣
The species here is different.

0:02:42.240,0:02:43.140
# 好啦  不要啦
Alright! That's it!

0:02:44.240,0:02:45.360
# 留給後面的人來摘
I leave them to those after us.

0:02:49.500,0:02:50.020
# 你看
Look!

0:02:50.440,0:02:50.960
# 這一個
This is,

0:02:51.860,0:02:52.380
# 這一個是
this is a,

0:02:52.780,0:02:54.380
# 萢子王一樣的  那麼大
it's like a Berry King. It's so big!

0:02:58.940,0:02:59.600
# 啊
Ah!

0:03:01.660,0:03:02.340
# 可以
Not bad!

0:03:07.120,0:03:09.040
# 你看  兄弟家的牛哦
Look! These are my buddy's cattle.

0:03:11.960,0:03:12.600
# 小牛
Cowy!

0:03:13.600,0:03:14.580
# 還認不認識我
Can you still recognize me?

0:03:17.300,0:03:18.740
# 肚子那麼大  它的肚子
It has a big belly, its belly.

0:03:21.540,0:03:22.440
# 吃得太飽了
It has eaten too much.

0:03:34.320,0:03:35.640
# 你看  它理都不理我
Look! It ignores me completely,

0:03:36.800,0:03:37.700
# 理都不理我
ignores me completely.

0:03:38.060,0:03:39.140
# 下次我叫兄弟
Next time, I'll ask my buddy,

0:03:40.260,0:03:41.120
# 把你賣給我
to sell you to me.

0:03:43.340,0:03:44.140
# 看你還敢不敢
I'll see if you would behave!

0:03:45.000,0:03:46.020
# 我要把你養大
I'm gonna bring you up.

0:03:46.760,0:03:48.580
# 養大之後來呀  把你 吃你的肉
When you grow up, I'll, I'll put your beef onto my dish.

0:03:56.660,0:03:58.840
# 哇  你看  這個河水
Wa! Look! The water in this river,

0:03:59.400,0:04:00.500
# 好乾淨的哦
is so clean, you know.

0:04:23.500,0:04:25.080
# 你看  搬一下這裡  看有沒有
Look! I'll lift the rock and see if there are any,

0:04:25.700,0:04:26.600
# 螃蟹
crabs.

0:04:33.920,0:04:34.660
# 一個都沒有
Not even one!

0:05:30.900,0:05:31.820
# 你看  這個
Look! This rock,

0:05:32.360,0:05:33.720
# 這個石頭應該是有的
I think there's something under this rock.

0:05:34.440,0:05:35.600
# 哇  有一個
Wa! A crab!

0:05:36.500,0:05:38.100
# 看一下  那麼大的螃蟹
Look! What a big crab!

0:05:44.820,0:05:46.880
# 你看  那麼兇悍
Look! It's so fierce!

0:05:50.580,0:05:51.380
# 有一兩重哦
It weighs about 50 grams.

0:06:05.920,0:06:08.200
# 你看這個  這個石頭應該是  這個石頭應該
Look! This, this rock should be, this rock must be...

0:06:10.160,0:06:12.000
# 誒  毛剛剛看到啦  啊  這裡這裡
Eh? I just saw it. Ah! Here, here!

0:06:12.960,0:06:13.460
# 一個
A crab

0:06:19.020,0:06:20.040
# 又找了一個
So one more.

0:06:24.860,0:06:26.380
# 那些石頭上壓著肯定有
Whenever there's a rock, there are always crabs underneath.

0:06:28.360,0:06:30.280
# 好像  有的樣子哦  (註︰這句很難又準確又自然的翻譯，有想過"It seems that here are crabs"，但太勉強了)
I would be surprised if there are no crabs here.

0:06:42.360,0:06:42.980
# 沒有
Really no

0:07:18.600,0:07:21.380
# 你看  這不是在勾引我嗎？
Look! Isn't it seducing me?

0:07:21.840,0:07:23.000
# 就長在河邊
It just grows on the riverside,

0:07:25.100,0:07:26.000
# 長得又大
and it's big,

0:07:26.640,0:07:27.300
# 又紅
and red.

0:07:30.940,0:07:31.660
# 哇
Wa!

0:07:36.160,0:07:37.300
# 嗯 好吃
Um! Tasty!

0:07:38.300,0:07:39.340
# 長到河邊來啦
They're growing onto the riverside.

0:07:43.840,0:07:45.360
# 你看  這個石頭下面應該有
Look! There should be, should be a crab,

0:07:45.800,0:07:46.920
# 應該會有一個
under this rock.

0:07:48.340,0:07:49.280
# 哎呀  看到沒有
Aya! Can you see it?

0:07:51.100,0:07:51.700
# 它在這裡
It's here.

0:07:56.800,0:07:57.540
# 還想著走
It still wants to run away.

0:08:00.580,0:08:01.240
# 夠大吧
Big, isn't it?

0:08:02.680,0:08:03.300
# 三個啦
Three now

0:08:24.140,0:08:27.420
# 你看  這個水潭好深啊  要從這裡鑽過來
Look! This pond is really deep. So we have to detour along this side.

0:08:28.980,0:08:30.060
# 鑽的過去嗎
Is it really possible?

0:08:54.960,0:08:56.280
# 這麼大的石頭  (註︰沒有原字幕)
What a big rock!

0:09:01.880,0:09:03.180
# 站得高望得遠 (註︰Climb high see wide，是香港一所中學的校訓，中文是「登高見博」XD)
Climb high, see wide

0:09:07.240,0:09:08.160
# 休息一下
Take a rest!

0:09:10.280,0:09:11.800
# 抓子半天抓了一隻
We've been here for the whole afternoon, only to have caught just three.

0:09:12.900,0:09:13.940
# 前面就很多啦
There are a lot in front of us.

0:09:26.480,0:09:27.720
# 哇 這裡有一個
Wa! Here's one!

0:09:29.080,0:09:29.580
# 這裡
Here!

0:09:31.160,0:09:32.440
# 誒  這裡還有一個
Eh? Here's another one!

0:09:36.220,0:09:37.120
# 它們小兩口
They're a young couple.

0:09:38.320,0:09:40.120
# 這是公的  這個是母的
This is male, and this is female.

0:09:41.740,0:09:42.720
# 不知道它們在乾嘛
I wonder what they're doing.

0:09:44.120,0:09:45.000
# 兩個把你抓起來
I'll capture both of you.

0:09:48.020,0:09:49.780
# 兩個人躲在一個屋子里面
They were hiding themselves from the world, under the same roof.

0:09:54.020,0:09:54.980
# 這裡有一個
Here's one.

0:09:57.120,0:09:58.420
# 誒  跑了嗎
Ey? It ran away?

0:09:58.840,0:09:59.480
# 小魚
A small fish

0:10:02.280,0:10:03.940
# 誒呦  那麼小就夾人的
Eyo! It pinches though it's so small.

0:10:07.860,0:10:08.780
# 嗯  這裡有一個
Um! Here's one.

0:10:10.720,0:10:11.220
# 嘿
Hey!

0:10:14.500,0:10:15.000
# 你看
Look!

0:10:17.120,0:10:18.800
# 螃蟹兒子  那麼小
Crab Jr., it's so small.

0:10:21.120,0:10:21.660
# 怕不怕我
Are you scared of me?

0:10:22.480,0:10:23.240
# 兩個螃蟹
Two crabs,

0:10:24.080,0:10:25.780
# 不是兩個螃蟹  兩個鉗子
I mean to pincers, not two crabs.

0:10:26.420,0:10:28.100
# 張開想夾我 是不是
Both are open. It wants to pinch me, right?

0:10:29.000,0:10:30.800
# 你還嫩了一點 還小
You're still too green. You're still small.

0:10:31.940,0:10:33.840
# 哎呀算了  把你放走了那麼小
Aya! Alright! I let you go. You're so small.

0:10:34.520,0:10:35.720
# 都不夠我一口吃掉
You're too small even for a single bite.

0:10:37.360,0:10:38.180
# 你自由啦
You're free now!

0:10:39.420,0:10:40.120
# 長大一點
Be a big crab!

0:10:40.360,0:10:41.720
# 可以叫你老爸老父媽出來
You can ask your dad and your mom to come.

0:10:44.180,0:10:44.680
# 你看
Look!

0:10:45.160,0:10:46.540
# 這個石頭下面不知道有沒有
Let's see if there are any crabs under this rock.

0:10:47.620,0:10:48.600
# 誒 有一隻
Eh! One!

0:10:51.220,0:10:52.780
# 現在的螃蟹都那麼大啦
The crabs are all that big now.

0:10:53.580,0:10:55.420
# 小的我都看到好幾個  好小
I've seen a couple of small ones. They're really small.

0:10:57.440,0:10:58.140
# 差不多夠了
It's almost enough.

0:11:00.700,0:11:01.540
# 這裡藏了
Here are...

0:11:08.900,0:11:10.840
# 好多這些田螺  就這種小的
Here are a lot of this kind of river snails. They're this kind of very small ones,

0:11:11.500,0:11:12.140
# 小石螺
small snails.

0:11:13.060,0:11:14.420
# 我們這個叫山坑螺 (註︰沒有原字幕)
They're called "stream snails" here.

0:11:15.500,0:11:17.080
# 山坑裡面才有這個 (註︰沒有原字幕)
They can only be found in small streams.

0:11:23.880,0:11:26.660
# 你看  這下面肯定有  那麼大的石頭
Look! There must be crabs under this rock.It's huge!

0:11:27.200,0:11:28.040
# 搬不動它
But I can't lift it.

0:11:42.640,0:11:45.280
# 你看  兄弟家  我去他家坐一坐
Look! My buddy lives there. I'm gonna have a cup of tea.

0:12:13.440,0:12:15.600
# 你看  兄弟家  大門緊閉
Look! My buddy's house. The door is tightly closed.

0:12:16.040,0:12:18.040
# 他還搞了一個鎖頭鎖著他家廚房
He has even put a lock there to lock up his kitchen.

0:12:19.260,0:12:19.760
# 回去
Let's go!

0:12:21.460,0:12:24.460
# 這個是昨天抓的螃蟹  今天帶它去
These are the crabs that we caught yesterday. Today, we're taking them,

0:12:24.920,0:12:26.440
# 河邊  把它烤啦
to the riverside. We'll grill them there.

0:12:49.220,0:12:50.000
# 就這裡了
Here is good.

0:12:50.620,0:12:51.760
# 剛好這裡有個小島
The small island here is just right.

0:12:54.620,0:12:56.320
# 好這裡  我去檢點柴火來
Let's get started here. I'm gonna pick some firewood,

0:12:56.720,0:12:57.680
# 把火生起來
and set the fire.

0:13:38.640,0:13:40.680
# 把這個柴先 搞斷它
This branch, let me chop it up first.

0:13:51.880,0:13:53.000
# 要裝點水哦
I need to get some water.

0:13:54.040,0:13:56.920
# 裝點水燒點  燒點開水燙一下那個螃蟹
I get some water and boil, boil some water and then boil the crabs for a while.

0:14:01.920,0:14:03.660
# 夠了  一點點就夠了  不要那麼多
Enough. A tiny little bit is enough. I don't need that much.

0:14:24.500,0:14:26.440
# 哎呀  三個串  下去
Aya! Three in a row, get down!

0:14:34.720,0:14:35.460
# 一鍋煮啦
Boil them all together.

0:14:36.400,0:14:37.980
# 先燙一下  不是煮
I just boil them for a while first, I'm not cooking them.

0:14:38.920,0:14:41.180
# 先燙一下  把它
I boil them for a while, so that,

0:14:43.280,0:14:44.360
# 燙S它來  (註︰我不想用"kill it"之類的字，怕惹來聖母婊，容我稍作修飾)
they don't move anymore.

0:14:48.880,0:14:49.640
# 還會動哦
They're still moving.

0:14:51.260,0:14:52.600
# 等它水開啦  就可以了
I only need to wait till the water boils.

0:14:55.640,0:14:57.120
# 你看  它們都紅了
Look! They've all become red.

0:14:59.360,0:15:00.040
# 再等一下
A few more moments

0:15:00.500,0:15:02.720
# 等它水沸騰了  我們就把它取出來
We're gonna take them out when the water boils.

0:15:10.140,0:15:11.140
# 好啦  差不多啦
Alright! It's almost there.

0:15:25.800,0:15:27.200
# 煮了好燙的水啊
The water is burning hot.

0:15:27.880,0:15:28.680
# 把水倒掉
I pour the water away.

0:15:34.140,0:15:35.440
# 裝點那裡的冷水來
Let me get some cold water there,

0:15:40.100,0:15:40.960
# 先給它泡 
and soak them.

0:15:50.220,0:15:51.500
# 蟹黃都出來了
The glans are already leaking out.

0:15:53.540,0:15:54.580
# 金黃色的哦
It's golden yellow, you know.

0:15:56.020,0:15:57.600
# 要把這個蓋子裡面
I need to remove the guts,

0:15:58.420,0:15:59.560
# 內臟要把它去一下
inside the shell.

0:16:00.580,0:16:02.400
# 這個  這些都不能吃的
This, these are inedible.

0:16:16.000,0:16:16.500
# 好啦
Alright!

0:16:17.160,0:16:19.300
# 這些洗乾淨之後我們把蓋子蓋上去
We'll put the shells back to cover them after they're washed and cleaned.

0:16:21.720,0:16:22.720
# 然後就直接這樣烤
And then they can be grilled right away.

0:16:23.360,0:16:24.180
# 烤螃蟹
Grilled crabs

0:16:41.700,0:16:42.200
# 可以
Alright!

0:16:43.300,0:16:44.540
# 你看  又搞一個
Look! One more is done.

0:16:52.660,0:16:55.680
# 一二三四五六七八
One, two, three, four, five, six, seven, eight,

0:16:56.000,0:16:56.700
# 九
nine

0:16:57.280,0:16:57.880
# 最後一個了
This is the last one.

0:17:04.600,0:17:05.400
# 螃蟹
Crabs

0:17:06.920,0:17:08.780
# 先把它們一個一個擺好
I first put them nicely and tidily one by one.

0:17:12.500,0:17:13.560
# 大的在中間
The big ones are in the middle,

0:17:14.600,0:17:15.940
# 小的在旁邊
while the small ones are on the sides.

0:17:16.880,0:17:17.980
# 這樣子剛剛好
They're well fitted on the net.

0:17:18.940,0:17:21.020
# 這個瞉一個個把它蓋上去
I put the shells back one by one.

0:17:22.680,0:17:24.040
# 應該是這樣子烤吧
I think I'm grilling in the right way.

0:17:26.560,0:17:27.060
# 可以了
It's fine now.

0:17:28.120,0:17:28.620
# 好啦
Alright!

0:17:29.940,0:17:31.280
# 先給它們洗一下
Let me wash them first.

0:17:31.740,0:17:32.620
# 晾在這裡先
Leave them here first.

0:17:33.120,0:17:34.060
# 我搞點醬料來
I'm gonna make some sauce.

0:17:39.800,0:17:41.060
# 多下點薑下去
Put more ginger.

0:17:46.260,0:17:46.840
# 夠了
Enough,

0:17:47.940,0:17:49.120
# 薑夠了
enough ginger

0:17:50.040,0:17:51.680
# 再加點這個鹽
Then some, some salt.

0:17:53.440,0:17:54.520
# 加點鹽
Put some salt.

0:17:56.560,0:17:57.620
# 加點料酒
Put some cooking wine.

0:18:01.320,0:18:02.600
# 加點醬油
Put some soy sauce.

0:18:11.160,0:18:12.120
# 加點油
Put some oil

0:18:24.560,0:18:26.140
# 搞點 辣椒醬
Get some, chilli sauce!

0:18:33.920,0:18:35.080
# 再搞點大蒜
And put some garlic as well.

0:18:46.800,0:18:47.600
# 攪拌一下
Shake them well.

0:19:02.800,0:19:04.400
# 搞點醬汁  搞點大蒜
Put some sauce, and some garlic.

0:19:09.600,0:19:10.360
# 反過來烤
Grill them upside down.

0:19:12.240,0:19:13.320
# 你看  這樣可以
Look! It's alright now!

0:19:14.200,0:19:15.160
# 先中間
In the middle first...

0:19:19.880,0:19:20.660
# 粘一點這個
Dip it into the, you know...

0:19:22.780,0:19:24.140
# 你看  這樣就很靚了
Look! It's really beautiful now!

0:19:30.640,0:19:32.620
# 它的  在它蓋子上蓋點
Its, on it's shell, I put some,

0:19:33.900,0:19:35.580
# 蓋點醬油  蓋點這個
put some sauce, and some, you know,

0:19:36.100,0:19:37.720
# 然後再沾一點這個料
and then dip into the ingredients.

0:19:39.520,0:19:40.720
# 啊  它味道
Ah! The taste is,

0:19:41.880,0:19:42.720
# 通通都給反過來
absolutely okay!

0:19:48.060,0:19:49.560
# 你看  把它們的頭對頭  尾對尾
I turn them all upside down.

0:19:57.800,0:20:00.660
# 鉗子對鉗子
Look! They're now head to head, tail to tail,

0:20:02.640,0:20:03.680
# 剛剛好
pincer to pincer.

0:20:04.320,0:20:05.040
# 烤  上烤架
Perfect!

0:20:07.140,0:20:08.620
# 你看  噴點油
Yea! Onto the grill!

0:20:16.020,0:20:17.160
# 你看
Look! I spray some oil.

0:20:48.460,0:20:49.000
# 這都
Look!

0:20:49.840,0:20:50.400
# 直接開啦
They're all,

0:20:51.600,0:20:52.560
# 瞉
already opened.

0:20:55.900,0:20:56.400
# 掀掉了
The shell,

0:20:57.360,0:20:58.220
# 不掀掉烤不熟
have already been taken off.

0:20:59.160,0:21:00.260
# 現在熟啦
Otherwise it would take forever to grill them.

0:21:04.200,0:21:05.020
# 嘗一下
Now it's done.

0:21:05.640,0:21:06.360
# 要從鉗子
Let me try,

0:21:07.980,0:21:09.320
# 燙
starting from, the pincer.

0:21:09.900,0:21:10.400
# 先要從鉗子開刀
Hot!

0:21:11.660,0:21:13.180
# 嗯  熟啦
I'll start from its pincer.

0:21:19.820,0:21:20.560
# 嗯  很鮮哦  這個
Um! It's done!

0:21:32.900,0:21:34.460
# 螃蟹就是螃蟹
Um! It's so fresh and tasty.

0:21:35.580,0:21:36.600
# 怪不得那麼多人喜歡吹
Crabs mean crabs.

0:21:37.060,0:21:38.300
# 就是有那種
No wonder it is a favourite food of so many people.

0:21:40.120,0:21:41.080
# 那種鮮味
It's because of the,

0:21:41.980,0:21:42.960
# 這全部腳
the taste of freshness and savory.

0:21:45.840,0:21:46.580
# 我們這邊的螃蟹  腳吃不了的
These are all legs.

0:21:47.060,0:21:48.980
# 只能吃它的肉
The legs of the crabs here are inedible.

0:21:49.940,0:21:50.840
# 肉又沒多少
Only the meat is edible.

0:21:57.600,0:21:58.520
# 只有鉗子好吃
But there's not so much meat.

0:21:59.880,0:22:01.000
# 你看  這個鉗子  鉗子的肉
Only the pincers are tasty.

0:22:14.180,0:22:16.020
# 嗯
Look! This is a pincer, meat in a pincer.

0:22:19.360,0:22:19.860
# 一點點
Um!

0:22:21.620,0:22:22.240
# 嗯  就是一種味 很鮮  很鮮美
A tiny little bit

0:22:29.360,0:22:32.580
# 這裡面還有一點點肉
Um! It's the taste of, freshness, and savory.

0:22:40.540,0:22:41.820
# 好啦  今天的視頻就到這裡啦
There's still a tiny little bit of meat inside.

0:22:58.800,0:23:00.900
# 把那火滅一下
Alright! The video ends here.

0:23:01.620,0:23:02.500
# 
Let's put off the fire.
