### ISSUE TITLE
[雪鱼] 牛肉拉面 - https://youtu.be/hNQWrb-FKk0

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#1050]
**视频链接**：https://youtu.be/hNQWrb-FKk0

视频时长：5min
发布时间：北京时间5月17日 21:00
# 请翻译以下全部内容

```
字幕
1
00:00:01,920 --> 00:00:05,000
江苏·邳州

2
00:00:06,560 --> 00:00:08,920
咱们今天来吃的是牛肉拉面

3
00:00:08,920 --> 00:00:13,520
没想到正好赶上饭点 这屋子里的人是乌央乌央的

4
00:00:35,800 --> 00:00:39,840
来两个小碗 再来一个凉拌牛肉

5
00:00:39,840 --> 00:00:41,120
20块钱牛肉行吗  行

6
00:00:41,120 --> 00:00:41,880
一共40块钱

7
00:00:41,880 --> 00:00:42,640
能吃辣椒吗

8
00:00:42,640 --> 00:00:45,440
能吃辣椒 稍微放点就行

9
00:00:45,440 --> 00:00:47,400
40块钱是吧

10
00:01:44,080 --> 00:01:46,800
刚才没有问 牛肉多少钱一斤了

11
00:01:46,800 --> 00:01:50,840
没想到 10块钱的小碗竟然有这么多的牛肉

12
00:01:50,840 --> 00:01:53,040
量特别足

13
00:01:53,040 --> 00:01:57,280
除了牛肉拉面之外呢 我们还要了一份凉拌牛肉

14
00:01:58,080 --> 00:02:03,840
一看上去就是辣椒 香菜 还有大片的牛肉

15
00:02:04,680 --> 00:02:08,920
牛肉拉面嘛 咱们先尝一尝这边的牛肉

16
00:02:08,920 --> 00:02:13,160
牛肉都是切成大片的

17
00:02:17,600 --> 00:02:21,840
就是常温的牛肉 放在拉面里

18
00:02:22,440 --> 00:02:25,720
加了一些的辣椒 好下饭

19
00:02:27,560 --> 00:02:30,320
我感觉面条里面可能也是加了盐

20
00:02:30,320 --> 00:02:34,080
因为整体的拉面吃起来都是咸的

21
00:02:34,120 --> 00:02:39,360
面馆里 满屋子都是吸溜面条的声音

22
00:02:43,040 --> 00:02:46,480
拉面的汤 是微辣 微咸和微香

23
00:02:46,480 --> 00:02:50,840
里面泡的牛肉 比凉拌的牛肉是更加软嫩的

24
00:02:50,840 --> 00:02:52,600
因为牛肉泡了一些汤汁嘛

25
00:02:52,600 --> 00:02:55,720
这么吃起来就是 毫不费力

26
00:03:14,480 --> 00:03:17,120
大叔 您怎么想到做牛肉拉面呢

27
00:03:17,120 --> 00:03:21,200
牛肉拉面 甘肃吃牛肉拉面

28
00:03:21,200 --> 00:03:23,480
我就跟甘肃学的

29
00:03:23,480 --> 00:03:27,120
就是引进了甘肃牛肉拉面的做法

30
00:03:27,120 --> 00:03:30,400
做的味道适合咱们本地人的口味

31
00:03:30,400 --> 00:03:33,240
兰州拉面到我们这地方干不起来

32
00:03:33,240 --> 00:03:35,040
毕竟口味不同

33
00:03:35,040 --> 00:03:37,000
口味 我们做的是地方口味

34
00:03:37,000 --> 00:03:39,920
这边除了卖拉面还有什么

35
00:03:39,920 --> 00:03:41,500
就一样拉面 别的什么都没有

36
00:03:41,560 --> 00:03:43,560
只有一种牛肉 一种面就是拉面

37
00:03:46,840 --> 00:03:49,520
每天都这么热闹吗

38
00:03:49,520 --> 00:03:50,960
全都这么热闹

39
00:03:50,960 --> 00:03:54,840
天凉比现在还热闹 天冷比这更热闹

40
00:03:54,840 --> 00:03:56,480
一年到头都干吗

41
00:03:56,480 --> 00:03:59,000
夏天三个月不干

42
00:03:59,000 --> 00:04:00,160
夏天为什么三个月不干

43
00:04:00,160 --> 00:04:03,680
夏天我这里面热 夏天太热了 受不了 没法开空调

44
00:04:03,720 --> 00:04:05,680
没法安空调

45
00:04:05,680 --> 00:04:07,960
这个时候吃完饭 都是脑门子上直冒汗

46
00:04:07,960 --> 00:04:09,600
过几天天气更热

47
00:04:09,600 --> 00:04:12,760
吃完拉面可能就是一种酣畅淋漓的状态了

48
00:04:12,760 --> 00:04:14,680
后面是刚熬完辣椒油

49
00:04:14,680 --> 00:04:19,200
站在这么远的地方 还能够闻到呛鼻辣椒的味道

50
00:04:19,200 --> 00:04:22,480
别看只是一口小锅在这个地方熬辣椒油

51
00:04:22,480 --> 00:04:25,760
还能吸引一大帮子人在这个地方看热闹

52
00:04:29,280 --> 00:04:32,520
这真不错 酒厂拉面谁不知道

53
00:04:32,520 --> 00:04:34,320
你经常来吃这个拉面吗

54
00:04:34,320 --> 00:04:36,800
嗯 经常来

55
00:04:40,720 --> 00:04:44,160
在这儿吃多少年了

56
00:04:44,160 --> 00:04:47,280
十几年了

57
00:04:48,200 --> 00:04:50,640
我都30了

58
00:05:02,600 --> 00:05:04,400
刚才和师傅聊天的时候 他说

59
00:05:04,400 --> 00:05:08,640
这边牛肉拉面的做法是从甘肃引进过来 学习过来的

60
00:05:08,640 --> 00:05:10,920
但是它们的口味还是有很大的不同的

61
00:05:10,920 --> 00:05:13,720
听了这个 我倒是很想去甘肃这边看一看

62
00:05:13,720 --> 00:05:16,240
那边的牛肉拉面是什么样子的呢

63
00:05:32,880 --> 00:05:35,600
关 注
雪 鱼 探 店


```

**Comment by shuaisoserious** [comment]
认领

**Comment by shuaisoserious** [comment]
1
00:00:01,920 --> 00:00:05,000
江苏·邳州
Pizhou. Jiangsu
2
00:00:06,560 --> 00:00:08,920
咱们今天来吃的是牛肉拉面
Today we gonna have beef hand-pulled noodles
3
00:00:08,920 --> 00:00:13,520
没想到正好赶上饭点 这屋子里的人是乌央乌央的

4
00:00:35,800 --> 00:00:39,840
来两个小碗 再来一个凉拌牛肉
I want two bowls of hand-pulled noodle and a beef in sauce
5
00:00:39,840 --> 00:00:41,120
20块钱牛肉行吗  行
20 yuan of beef? Okay
6
00:00:41,120 --> 00:00:41,880
一共40块钱
40 yuan total
7
00:00:41,880 --> 00:00:42,640
能吃辣椒吗
Can you eat spicy oil?
8
00:00:42,640 --> 00:00:45,440
能吃辣椒 稍微放点就行
Yeah, a little bit
9
00:00:45,440 --> 00:00:47,400
40块钱是吧
40 yuan right?
10
00:01:44,080 --> 00:01:46,800
刚才没有问 牛肉多少钱一斤了
I forget to ask, how much beef is each half a kilo
11
00:01:46,800 --> 00:01:50,840
没想到 10块钱的小碗竟然有这么多的牛肉
I didn’t expect    there is so many beef in the 10 yuan bowls                 
12
00:01:50,840 --> 00:01:53,040
量特别足
With large amounts of beef
13
00:01:53,040 --> 00:01:57,280
除了牛肉拉面之外呢 我们还要了一份凉拌牛肉
We ordered a beef in sauce besides hand-pulled beef noodles
14
00:01:58,080 --> 00:02:03,840
一看上去就是辣椒 香菜 还有大片的牛肉
With spicy pepper, Chinese parsley, and big slices of beef
15
00:02:04,680 --> 00:02:08,920
牛肉拉面嘛 咱们先尝一尝这边的牛肉
Let’s try beef first 
16
00:02:08,920 --> 00:02:13,160
牛肉都是切成大片的
They sliced beef into large slices
17
00:02:17,600 --> 00:02:21,840
就是常温的牛肉 放在拉面里
Just homeothermy beef in hand-pulled noodle
18
00:02:22,440 --> 00:02:25,720
加了一些的辣椒 好下饭
Good to eat with some spicy pepper, 
19
00:02:27,560 --> 00:02:30,320
我感觉面条里面可能也是加了盐
I think they add salts in the noodle
20
00:02:30,320 --> 00:02:34,080
因为整体的拉面吃起来都是咸的
Because it taste salty 
21
00:02:34,120 --> 00:02:39,360
面馆里 满屋子都是吸溜面条的声音
Whole restaurant with sounds of sucking noodle
22
00:02:43,040 --> 00:02:46,480
拉面的汤 是微辣 微咸和微香
The soup of noodle is with lighter spicy, lighter salty and lighter fragments
23
00:02:46,480 --> 00:02:50,840
里面泡的牛肉 比凉拌的牛肉是更加软嫩的
The beef in the soup is softer and tender than the beef in sauce
24
00:02:50,840 --> 00:02:52,600
因为牛肉泡了一些汤汁嘛
Because there’s soup in the beef
25
00:02:52,600 --> 00:02:55,720
这么吃起来就是 毫不费力
Very easy to eat
26
00:03:14,480 --> 00:03:17,120
大叔 您怎么想到做牛肉拉面呢
Uncle, how do you start the hand-pulled beef noodles?
27
00:03:17,120 --> 00:03:21,200
牛肉拉面 甘肃吃牛肉拉面
Hand-pulled beef noodle is popular in Gansu
28
00:03:21,200 --> 00:03:23,480
我就跟甘肃学的
I learned it in Gansu
29
00:03:23,480 --> 00:03:27,120
就是引进了甘肃牛肉拉面的做法
Import Gansu hand-pulled beef noodle style
30
00:03:27,120 --> 00:03:30,400
做的味道适合咱们本地人的口味
And changed it to fit local flavor 
31
00:03:30,400 --> 00:03:33,240
兰州拉面到我们这地方干不起来
Local people don’t like Lanzhou hand-pulled noodle style
32
00:03:33,240 --> 00:03:35,040
毕竟口味不同
Because it is different 
33
00:03:35,040 --> 00:03:37,000
口味 我们做的是地方口味
We make local flavor 
34
00:03:37,000 --> 00:03:39,920
这边除了卖拉面还有什么
What else you have except hand-pulled noodle?
35
00:03:39,920 --> 00:03:41,500
就一样拉面 别的什么都没有
Just hand-pulled noodle, nothing else
36
00:03:41,560 --> 00:03:43,560
只有一种牛肉 一种面就是拉面
Only a type of beef and a type of noodle which is hand-pulled noodle
37
00:03:46,840 --> 00:03:49,520
每天都这么热闹吗
Is it as crowded every day?
38
00:03:49,520 --> 00:03:50,960
全都这么热闹
Yeah, it is
39
00:03:50,960 --> 00:03:54,840
天凉比现在还热闹 天冷比这更热闹

40
00:03:54,840 --> 00:03:56,480
一年到头都干吗
Are you work whole year?
41
00:03:56,480 --> 00:03:59,000
夏天三个月不干
Not three month of summer
42
00:03:59,000 --> 00:04:00,160
夏天为什么三个月不干
Why don’t?
43
00:04:00,160 --> 00:04:03,680
夏天我这里面热 夏天太热了 受不了 没法开空调
Because it's too hot in summer, can not stand it without air conditioning 
44
00:04:03,720 --> 00:04:05,680
没法安空调
Can not have air conditioning 
45
00:04:05,680 --> 00:04:07,960
这个时候吃完饭 都是脑门子上直冒汗
Sweat all over head after you finish eat in summer
46
00:04:07,960 --> 00:04:09,600
过几天天气更热
It’s get hotter after couple days
47
00:04:09,600 --> 00:04:12,760
吃完拉面可能就是一种酣畅淋漓的状态了

48
00:04:12,760 --> 00:04:14,680
后面是刚熬完辣椒油
Just finish cook chili oil at back
49
00:04:14,680 --> 00:04:19,200
站在这么远的地方 还能够闻到呛鼻辣椒的味道
You still can smell chili even if you stand so far
50
00:04:19,200 --> 00:04:22,480
别看只是一口小锅在这个地方熬辣椒油

51
00:04:22,480 --> 00:04:25,760
还能吸引一大帮子人在这个地方看热闹

52
00:04:29,280 --> 00:04:32,520
这真不错 酒厂拉面谁不知道
This is good, who don’t know winery hand-pulled noodle
53
00:04:32,520 --> 00:04:34,320
你经常来吃这个拉面吗
Do you come often?
54
00:04:34,320 --> 00:04:36,800
嗯 经常来
Yeah, always
55
00:04:40,720 --> 00:04:44,160
在这儿吃多少年了
How many years you eat here?
56
00:04:44,160 --> 00:04:47,280
十几年了
More than ten years
57
00:04:48,200 --> 00:04:50,640
我都30了
I’m 30 years old
58
00:05:02,600 --> 00:05:04,400
刚才和师傅聊天的时候 他说
The master said that 
59
00:05:04,400 --> 00:05:08,640
这边牛肉拉面的做法是从甘肃引进过来 学习过来的
The way to make hand-pulled noodle is import from Gansu
60
00:05:08,640 --> 00:05:10,920
但是它们的口味还是有很大的不同的
With huge difference of flavor 
61
00:05:10,920 --> 00:05:13,720
听了这个 我倒是很想去甘肃这边看一看
I want to go to Gansu and take a look 
62
00:05:13,720 --> 00:05:16,240
那边的牛肉拉面是什么样子的呢
What does it look like?
63
00:05:32,880 --> 00:05:35,600
关 注
雪 鱼 探 店
