### ISSUE TITLE
[华农兄弟] 华农兄弟河边的桑果熟了一树都是摘一点来吃 - https://youtu.be/bHOQ7pmiWPk

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1059]
https://youtu.be/bHOQ7pmiWPk
<p>&#35270;&#39057;&#21457;&#24067;&#20110; May 17, 2020 at 11:40AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/bHOQ7pmiWPk

#华农兄弟：河边的桑果熟了，一树都是，摘一点来吃
#Huanong Brothers: The mulberries on the river side are already ripe. They are all over the trees. Let's pick some.

0:00:00.000,0:00:02.580
# 上次我在河邊溜達的時候  看到那個
Last time, when I was strolling along the riverside, I saw that the,

0:00:02.960,0:00:03.620
# 桑果啊
the mulberries,

0:00:04.120,0:00:04.800
# 熟了哦
had become ripe.

0:00:05.280,0:00:06.500
# 現在我們去摘一點
We're gonna pick some now,

0:00:06.800,0:00:07.580
# 帶了這個
together with this thing.

0:00:11.180,0:00:12.840
# 哇  有枇杷果哦
Wa! Loquats!

0:00:18.420,0:00:19.560
# 你看  這些枇杷
Look! These loquats,

0:00:20.380,0:00:23.380
# 那麼黃的枇杷都沒人吃  怎麼搞的
they're already golden yellow now but nobody picks them? What happened?

0:00:25.320,0:00:27.640
# 哎喲  又大又黃哦
Ayo! They're so big and golden yellow.

0:00:29.500,0:00:30.540
# 你看  這些
Look! These are,

0:00:31.280,0:00:32.500
# 我到都流口水
mouthwatering.

0:00:33.020,0:00:34.420
# 肉都是紅的  這個肉
The pulp is red, the pulp.

0:00:36.040,0:00:37.080
# 晶瑩剔透
Crystal clear

0:00:39.480,0:00:40.160
# 嗯嗯
Um um!

0:00:45.480,0:00:46.380
# 不知道誰家的
I have no ideas whose they are.

0:00:48.020,0:00:49.940
# 我都不知道這裡有一棵枇杷樹
I never knew that a loquat tree is here.

0:00:55.400,0:00:56.680
# 嗯  不好吃  好酸
Um! No good. It's so sour.

0:01:02.940,0:01:04.420
# 把那個相机拆下來
Take the camera out.

0:01:05.540,0:01:07.760
# 哎呀  這個來 扣下來
Aya! I pull them down, using it.

0:01:09.620,0:01:10.840
# 哪有摘不到的
There's nothing that I can't pick.

0:01:18.040,0:01:19.960
# 啊  這個好熟啦  這個都是
Ah! This is very ripe and this one too,

0:01:20.940,0:01:21.900
# 特別是這兩個
especially these two.

0:01:22.420,0:01:23.360
# 來 給你吃
C'mon! They're yours.

0:01:25.640,0:01:26.560
# 透明的哦
They're jelly clear, you know.

0:01:36.880,0:01:37.600
# 可以
Not bad!

0:01:43.560,0:01:45.580
# 吃枇杷是  這樣是最快的
Here's the fastest way to eat a loquat.

0:01:48.040,0:01:48.540
# 這樣
Let me show you.

0:01:49.960,0:01:51.840
# 不算  這個不算  這個有點壞啦
No, not this one. This one is a bit rotten.

0:01:57.260,0:01:58.700
# 把這稍微撕一下
Slightly peel it here,

0:01:59.980,0:02:01.060
# 然後一擠
and then squeeze.

0:02:06.100,0:02:06.820
# 這樣才快
That's the fastest.

0:02:08.220,0:02:08.900
# 所以
So,

0:02:09.740,0:02:12.220
# 吃東西要吃快來  要不然吃的很少的
when you eat, eat fast. Otherwise you would only have a pitiful share.

0:02:13.620,0:02:15.100
# 想要吃多點就要吃快一點
Always eat fast, if you want to eat more.

0:02:21.500,0:02:22.240
# 在上面
Up there

0:02:24.680,0:02:25.880
# 這個不要啦  放這裡
This one is no longer needed. Put it here.

0:02:32.580,0:02:33.600
# 路都沒啦
There isn't even a path.

0:02:41.380,0:02:42.680
# 要走水路的哦
We need to walk on the stream,

0:02:43.960,0:02:45.080
# 沒有大路走
as there's no proper path.

0:02:49.520,0:02:51.420
# 你看  這還有香蕉的哦
Look! Here are bananas too.

0:02:51.980,0:02:52.720
# 那麼小
They're so small.

0:02:53.460,0:02:54.360
# 小香蕉
Tiny bananas

0:02:55.120,0:02:56.500
# 迷你小香蕉
Mini tiny bananas

0:03:06.240,0:03:07.520
# 要從這裡上去
We need to go up from here.

0:03:12.400,0:03:13.020
# 你看
Look!

0:03:13.780,0:03:15.320
# 這個 很靚的哦
This is, beautiful, you know.

0:03:19.580,0:03:21.720
# 雖然小了一點  但是味道
Though it's a bit small, but it tastes,

0:03:22.460,0:03:23.180
# 很不錯
really not bad.

0:03:24.600,0:03:25.840
# 你看  手都紅的
Look! My hands are already red.

0:03:26.420,0:03:27.100
# 看到沒有
Can you see it?

0:03:27.780,0:03:28.460
# 一捏就
Squeeze it, and then,

0:03:29.940,0:03:30.680
# 紅的
it's red.

0:03:32.840,0:03:34.220
# 嗯  小的最好吃
Um! The small one taste the best.

0:03:35.780,0:03:36.320
# 嗯
Um!

0:03:42.360,0:03:42.940
# 你看
Look!

0:03:43.400,0:03:44.060
# 這麼
They're,

0:03:44.960,0:03:47.100
# 這麼熟了都沒人  沒人來摘
they're already so ripe now. But nobody, nobody picked them.

0:03:48.180,0:03:49.460
# 那不是天助我也
Isn't it a blessing from the God?

0:03:50.580,0:03:51.500
# 就快沒了哦
There are not so many left.

0:03:54.340,0:03:55.120
# 哎呀
Aya!

0:03:59.120,0:04:01.200
# 再來遲幾天的話  可能都掉啦
They would all fall down if we came a couple of days later.

0:04:06.460,0:04:07.600
# 啊  直接吃算啦
Ah! Let's enjoy them here right away.

0:04:09.240,0:04:09.740
# 嗯
Um!

0:04:11.720,0:04:14.440
# 這才過癮  這種就是不是很熟的  但是酸的
It's so much fun. These are not really that ripe, but a bit sour.

0:04:15.840,0:04:16.340
# 嗯
Um!

0:04:17.500,0:04:18.500
# 好酸不要
Very sour! Pass!

0:04:19.700,0:04:20.880
# 有熟的都不摘
Why not just pick the ripe ones?

0:04:22.320,0:04:23.460
# 還要吃紅的
I want the red ones too.

0:04:24.960,0:04:26.180
# 帶來這簍子又多
Bringing this sieve is com,

0:04:27.020,0:04:27.920
# 多此一舉啦
completely pointless.

0:04:32.800,0:04:33.940
# 你看  那裡好多
Look! There are a lot!

0:04:35.340,0:04:36.060
# 你要不要哦
You want some?

0:04:36.300,0:04:37.280
# 再不吃就沒啦
Now or never.

0:04:45.460,0:04:46.440
# 這個太小啦
These are too small.

0:04:55.620,0:04:56.660
# 這邊  這邊也有
Here, some more here.

0:05:00.980,0:05:01.720
# 你看  這種
Look! These are,

0:05:06.140,0:05:08.400
# 我們來遲啦  應該來早一點點
We are too late. We should have come a tiny little bit earlier.

0:05:09.700,0:05:11.700
# 來早一點  它剛好熟透
If we came earlier, they would be perfectly ripe.

0:05:12.840,0:05:13.500
# 現在是
Now they're,

0:05:15.420,0:05:16.180
# 就快掉啦
already about to fall,

0:05:17.460,0:05:18.540
# 更熟更透
more than just ripe.

0:05:20.760,0:05:21.560
# 這種很靚的
These are really beautiful!

0:05:25.360,0:05:26.720
# 以前我們還小的時候
In the past, when we were kids,

0:05:28.260,0:05:29.600
# 都是提了一個籃子來摘
we always picked them carrying a basket.

0:05:32.780,0:05:33.760
# 摘回  摘回去
We picked, picked them back,

0:05:34.840,0:05:35.720
# 一家人吃
for the whole family.

0:05:37.140,0:05:39.320
# 現在還沒  沒多少了現在一點點
Now it's still, there are not too many now, just a tiny little bit.

0:05:40.120,0:05:41.080
# 所以就算啦
So now it's no longer possible

0:05:42.460,0:05:43.540
# 自己吃飽就好啦
It's only enough feed myself.

0:05:47.280,0:05:48.380
# 這裡還有  這裡還有一棵
Here as well, here's another branch.

0:05:54.620,0:05:56.060
# 原先河裡面很多的
There used to be a lot by the river.

0:05:56.840,0:05:57.900
# 現在麼[SIC]多少啦
But not so many remain now.

0:05:59.080,0:05:59.980
# 不知道怎麼回事
I have no ideas what happened.

0:06:00.620,0:06:01.320
# 可能被
Perhaps they were,

0:06:03.160,0:06:04.880
# 被割  砍掉了吧
they were cut, chopped away.

0:06:05.760,0:06:07.360
# 這個現在  沒人吃
They're, now, nobody wants them.

0:06:08.900,0:06:10.840
# 人家現在都不喜歡吃這樣的東西啦
People don't like these kinds of stuffs nowadays,

0:06:11.000,0:06:11.740
# 就我們吃
we are the exceptions.

0:06:16.240,0:06:16.820
# 應該
I should,

0:06:17.900,0:06:18.700
# 挖點回去
dig out some of them back home.

0:06:20.080,0:06:21.420
# 我們養殖廠裡面種著
We can plant them at our site.

0:06:23.240,0:06:24.560
# 到時候想吃就吃
Then I can have mulberries whenever I want,

0:06:25.500,0:06:27.200
# 想甚麼時候吃就甚麼時候吃
every day, every minute, every second.

0:06:30.980,0:06:32.600
# 就這種  那麼小
These are, so small.

0:06:34.800,0:06:36.720
# 可能現在人看不上這種東西啦
They look so miserable to the people nowadays.

0:06:39.540,0:06:40.100
# 但是
But,

0:06:41.760,0:06:42.580
# 還可以喲
they're not bad.

0:06:45.360,0:06:46.900
# 反正我就喜歡這種味道
Anyway, it's the taste that I like.

0:06:49.860,0:06:52.060
# 那種  酸酸甜甜的
It's like, sweet and sour.

0:06:54.740,0:06:56.000
# 哎呀  那棵樹上
Aya! In that tree...

0:07:07.940,0:07:08.440
# 你看
Look!

0:07:09.540,0:07:10.280
# 整個是
These are all,

0:07:10.880,0:07:11.840
# 野桑果
wild mulberries.

0:07:12.820,0:07:13.560
# 正宗的
Authentic,

0:07:14.720,0:07:15.560
# 土貨
and locally grown.

0:07:20.740,0:07:21.460
# 可以喲
Not bad

0:07:21.840,0:07:22.680
# 味道還可以
They taste not bad.

0:07:26.040,0:07:27.140
# 明年的時候我們也
Next year, we need to,

0:07:27.580,0:07:28.440
# 來早一點
come earlier.

0:07:29.760,0:07:30.840
# 才能吃到更多
So that we can have even more.

0:07:31.180,0:07:32.200
# 現在都快沒啦
Not so many are left now.

0:07:37.360,0:07:38.800
# 好啦  我們去前面看一下
Alright! Let's have a look in the front.

0:07:40.180,0:07:41.020
# 全部搞定
Done here!

0:07:43.940,0:07:44.840
# 還不過癮
But I'm still craving.

0:07:47.080,0:07:48.140
# 你看  我的手
Look! My hands,

0:07:49.180,0:07:50.260
# 都變成這樣子啦
are already dyed.

0:07:54.300,0:07:56.300
# 哇  你看  這棵樹才多
Wa! Looks! This tree has the most!

0:08:06.560,0:08:08.020
# 坐下樹底下吃
Enjoying the fruits while sitting under the tree,

0:08:08.580,0:08:10.020
# 那才是最爽的
makes me the King of the World.

0:08:11.180,0:08:11.740
# 你看
Look!

0:08:13.620,0:08:15.300
# 站在藍天白雲下
Standing under the blue sky and white clouds,

0:08:18.040,0:08:19.220
# 吃著這個桑果
I'm enjoying the mulberries.

0:08:24.800,0:08:25.400
# 不知道
I'm running out,

0:08:26.760,0:08:28.500
# 沒詞形容  不會形容
running out of adjectives. I dunno how I can describe.

0:08:29.760,0:08:30.880
# 反正就是好吃
Tasty. That's it.

0:08:44.740,0:08:45.420
# 好啦
Alright!

0:08:46.900,0:08:48.120
# 今天的視頻就到這裡啦
The video ends here.

0:08:49.680,0:08:50.460
# 不能吃太多
It's not good to have too many.

0:08:51.600,0:08:53.100
# 我現在可能吃了有點多啦
I think I've already eaten a bit too many.

0:08:54.520,0:08:55.460
# 想上廁所
I wanna go to toilet.

0:09:16.260,0:09:16.980
# 這個
These are,

0:09:17.760,0:09:18.540
# 就像那麼
they look like,

0:09:19.220,0:09:21.300
# 吊燈萢一樣的  但是這個不能吃的哦
look like the wild berries. But they're inedible.

0:09:22.340,0:09:24.540
# 反正我就沒吃過  看上去就是是
I've never tried them. They look like,

0:09:25.680,0:09:27.740
# 很想吃的樣子  但是不敢吃
they look very tasty. But I don't dare to try.

0:09:28.380,0:09:29.260
# 不要中毒啦
I don't wanna get poisoned.

0:09:33.540,0:09:36.380
# 你看  兄弟種的這個李子樹  就長了一個的
Look! This is my buddy's plum tree. And this is the only single plum.

0:09:37.320,0:09:38.240
# 笑死我啦
I'm about to suffocate from laughing.

0:09:41.580,0:09:42.320
# 做個記號
Let me leave a marking.

0:09:44.380,0:09:45.380
# 就一個的
But here's just one.

0:09:46.600,0:09:48.340
# 做記號應該就不用了吧
I don't think I need any markings.

0:09:50.760,0:09:52.100
# 把這個遮一下
Let me cover it,

0:09:53.420,0:09:54.620
# 讓別人看不到
to hide it from other people.

0:09:54.740,0:09:56.960
# 這個李子刻字的話會把它刻傷的
I would damage the plum if I craft on it.

0:09:57.640,0:09:58.720
# 給它穿個衣服
Let me give it clothes.

0:10:03.080,0:10:04.060
# 遮風檔雨
A shelter

0:10:06.220,0:10:07.480
# 多靚啊 哦
It's so beautiful, isn't it?

0:10:08.340,0:10:11.060
# 你看  這樣一看它就是一個葉子  甚麼都看不到
Look! Now you see just a leaf, and nothing else.

0:10:12.220,0:10:13.420
# 到時候我們就來摘它
We can then come and pick it later.
