### ISSUE TITLE
[老饭骨] 炒疙瘩 - https://youtu.be/udVWvKrKBa0

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1064]
**视频链接**：<https://youtu.be/udVWvKrKBa0>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•炒疙瘩】地道老北京面食，最香是家常，大爷做的不仅是菜，更是家的味道 |老饭骨

简介
小友们好，今天大爷要教大家一个家常的——炒疙瘩。这炒疙瘩颜色黄绿相间，吃起来软糯有嚼劲，越嚼越香，色香味俱全!
不知道炒疙瘩是不是许多小友们家里的味道，大爷大妈也希望远在海外的朋友们，自个儿在家里炒菜做饭，也能吃到家乡的味道，过上幸福的生活！

字幕
1
00:00:00,000 --> 00:00:04,000
今天大爷还做一个家庭版的

2
00:00:04,000 --> 00:00:05,360
炒疙瘩

3
00:00:05,360 --> 00:00:08,800
我先把面和上 和这面要硬一些

4
00:00:08,800 --> 00:00:12,080
基本跟面条面是一样的

5
00:00:12,080 --> 00:00:13,600
面就用我们的

6
00:00:13,600 --> 00:00:16,720
标准粉也行 高筋粉也行

7
00:00:16,720 --> 00:00:18,320
有的爱吃粗粮的

8
00:00:18,320 --> 00:00:20,520
可以用棒子面 玉米面

9
00:00:20,520 --> 00:00:21,960
我要提醒的就是什么呢

10
00:00:21,960 --> 00:00:23,800
一定用开水烫一下（棒子面）

11
00:00:23,800 --> 00:00:26,320
烫的硬一些 然后搁上

12
00:00:26,320 --> 00:00:29,320
三分之一或者四分之一的白面

13
00:00:29,320 --> 00:00:31,560
里边适当的少搁一点盐

14
00:00:31,560 --> 00:00:33,680
面和好了 好了

15
00:00:33,680 --> 00:00:35,840
我看这面有点多

16
00:00:35,840 --> 00:00:39,000
面和好了 我们饧一饧 盖块小屉布

17
00:00:39,000 --> 00:00:41,720
下一项咱们备小料

18
00:00:41,720 --> 00:00:47,320
来点五花肉 根据自己的喜好可多可少

19
00:00:47,320 --> 00:00:49,720
把肉切成肉丁

20
00:00:49,720 --> 00:00:53,400
这肉丁切小点 借味

21
00:00:53,400 --> 00:00:55,840
肉切好了

22
00:00:55,840 --> 00:01:03,720
青蒜 豌豆 胡萝卜 葱头

23
00:01:03,720 --> 00:01:09,680
肉丁 香菇 葱姜

24
00:01:09,680 --> 00:01:12,720
爱吃什么放什么 挺随意的

25
00:01:12,720 --> 00:01:15,560
这面呢 也饧好了

26
00:01:15,560 --> 00:01:19,640
刚才我趁大妈没注意 我给揉了揉

27
00:01:19,640 --> 00:01:23,120
特别滋润 又挺硬

28
00:01:23,120 --> 00:01:27,120
这个面有两种成型方式

29
00:01:27,120 --> 00:01:30,600
一种擀的厚一点 再切丁

30
00:01:30,600 --> 00:01:33,800

31
00:01:33,800 --> 00:01:35,760
切成厚片

32
00:01:35,760 --> 00:01:38,240
我们拖点面

33
00:01:38,240 --> 00:01:40,520
但是擀它显得瓷实

34
00:01:40,520 --> 00:01:43,320
这个显得松软 省事儿这个

35
00:01:43,320 --> 00:01:45,600
这个不能太大了

36
00:01:45,600 --> 00:01:47,280
太大了有时候煮的不好熟

37
00:01:47,280 --> 00:01:49,160
吃的时候也费劲

38
00:01:49,160 --> 00:01:51,880

39
00:01:51,880 --> 00:01:54,560
准备一盆 要干

40
00:01:54,560 --> 00:01:59,080
还有一种 就跟擀面条一样

41
00:01:59,080 --> 00:02:03,480
在家里做饭就是玩儿  什么玩儿呢

42
00:02:03,480 --> 00:02:04,920
你看跟过家家似的

43
00:02:04,920 --> 00:02:07,160

44
00:02:07,160 --> 00:02:13,200
要是大家没有时间 其实超市有卖的

45
00:02:13,200 --> 00:02:16,840
那个买回来煮的时候得多煮一会儿

46
00:02:16,840 --> 00:02:18,400
它那特别硬

47
00:02:19,200 --> 00:02:20,040

48
00:02:20,040 --> 00:02:23,400
这家里头有个大厨

49
00:02:23,400 --> 00:02:26,120
他就是幸福 幸福极了

50
00:02:26,120 --> 00:02:28,520

51
00:02:30,040 --> 00:02:31,760
撒点干面 摇

52
00:02:31,760 --> 00:02:33,400

53
00:02:33,400 --> 00:02:35,600
下锅了啊 开了

54
00:02:35,600 --> 00:02:38,640
煮完了煮的时间稍微长一点

55
00:02:38,640 --> 00:02:40,320
比面条要长一点

56
00:02:40,320 --> 00:02:43,320
面疙瘩马上就出锅了

57
00:02:43,320 --> 00:02:46,120
咱们现在开始炒菜 炒这料

58
00:02:46,120 --> 00:02:48,360
还是一个 热锅凉油

59
00:02:48,360 --> 00:02:50,960
这个时候的油稍微多一点 它香

60
00:02:50,960 --> 00:02:53,360
先煸肉丁

61
00:02:53,360 --> 00:02:55,360

62
00:02:55,360 --> 00:02:58,520
如果家里有老人这肉丁得浆一下

63
00:02:58,520 --> 00:03:01,480
但是一般咱们吃就不用浆了

64
00:03:01,480 --> 00:03:06,600
为什么 主要我们要肥瘦肉

65
00:03:06,600 --> 00:03:09,520
也是有增香的一种效果

66
00:03:09,520 --> 00:03:13,160
肉煸出点油来 葱姜也（出香味了）

67
00:03:13,160 --> 00:03:18,600
胡萝卜 豌豆 出下水 焯了一下

68
00:03:18,600 --> 00:03:20,240
煸炒

69
00:03:20,240 --> 00:03:21,280

70
00:03:21,280 --> 00:03:22,640
放材料

71
00:03:22,640 --> 00:03:26,480
酱油 这个色也是随着自己

72
00:03:26,480 --> 00:03:28,360
黄酒

73
00:03:28,360 --> 00:03:30,680
大爷搁盐还是猛

74
00:03:30,680 --> 00:03:32,120
别那么猛

75
00:03:32,120 --> 00:03:36,200
一勺两勺 得三勺 两勺半

76
00:03:36,200 --> 00:03:40,160
把葱头下去 葱头后下

77
00:03:42,360 --> 00:03:45,280
太晚了也不行 下早了也不行

78
00:03:45,280 --> 00:03:51,040
太早了它就炒老了  炒老了就不好吃了

79
00:03:51,040 --> 00:03:54,560
搁点蚝油 胡椒粉

80
00:03:55,160 --> 00:03:58,000
这个料炒得了

81
00:03:58,000 --> 00:04:02,560
大妈稍微给看着一点 我捞面

82
00:04:02,560 --> 00:04:07,120
二厨也扒拉两下 瞧瞧咱们挺专业的吧

83
00:04:07,120 --> 00:04:09,480

84
00:04:09,480 --> 00:04:11,920
火大点儿没事

85
00:04:11,920 --> 00:04:14,880
好了 这可太多了

86
00:04:16,440 --> 00:04:18,120
青蒜

87
00:04:18,120 --> 00:04:19,000

88
00:04:19,480 --> 00:04:23,240
搁点果仁行不行啊 可以 那才香啊

89
00:04:23,240 --> 00:04:26,560
搁点花生碎 撒点芝麻

90
00:04:26,560 --> 00:04:29,520
这个在锅里边稍微炒一炒

91
00:04:29,520 --> 00:04:33,880
因为它有面的淀粉

92
00:04:33,880 --> 00:04:36,120
炒的时候黏黏糊糊的

93
00:04:36,120 --> 00:04:41,520
然后最好锅底火大一点还带点嘎巴

94
00:04:41,520 --> 00:04:44,960
关火了 熟了

95
00:04:44,960 --> 00:04:46,520
装盘

96
00:04:46,520 --> 00:04:51,480
让大家看看 这是效果

97
00:04:51,480 --> 00:04:54,040
这行了吧 可以了

98
00:04:54,040 --> 00:04:56,840
大厨拿着是不是

99
00:04:57,800 --> 00:05:00,600
家有大厨 就是幸福

100
00:05:00,600 --> 00:05:02,760
谢谢大爷

101
00:05:02,760 --> 00:05:04,720

102
00:05:06,920 --> 00:00:01,960

103
00:05:08,680 --> 00:00:02,000

**Comment by Xuyuan0919** [comment]
认领

**Comment by Xuyuan0919** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•炒疙瘩】地道老北京面食，最香是家常，大爷做的不仅是菜，更是家的味道 |老饭骨
State Banquet Master Chef - “ChaoGeDa” homestyle old Peking dough food
简介
小友们好，今天大爷要教大家一个家常的——炒疙瘩。这炒疙瘩颜色黄绿相间，吃起来软糯有嚼劲，越嚼越香，色香味俱全!
不知道炒疙瘩是不是许多小友们家里的味道，大爷大妈也希望远在海外的朋友们，自个儿在家里炒菜做饭，也能吃到家乡的味道，过上幸福的生活！
Hello friends! Today Daye teaches you a homestyle dish-” ChaoGeDa” ChaoGeDa looks yellow and green, tastes soft and glutinous, more fragrant when you chew more. It’s excellence in color, aroma, and taste!
I don’t know if it’s the taste from your home, Daye and Dama hope our overseas friends can also cook at home so that you can enjoy the taste of your hometown, have a happy life!
字幕
1
00:00:00,000 --> 00:00:04,000
今天大爷还做一个家庭版的
Today Daye is going to cook a homestyle
2
00:00:04,000 --> 00:00:05,360
炒疙瘩
ChaoGeDa(Fried dough drops)
3
00:00:05,360 --> 00:00:08,800
我先把面和上 和这面要硬一些
First of all, Kneading dough, the dough need to a bit harder
4
00:00:08,800 --> 00:00:12,080
基本跟面条面是一样的
Almost same as the dough for making noodle
5
00:00:12,080 --> 00:00:13,600
面就用我们的
You can use either
6
00:00:13,600 --> 00:00:16,720
标准粉也行 高筋粉也行
Plain flour or bread flour
7
00:00:16,720 --> 00:00:18,320
有的爱吃粗粮的
Someone would like to eat coarse grain
8
00:00:18,320 --> 00:00:20,520
可以用棒子面 玉米面
So you can use cornflour
9
00:00:20,520 --> 00:00:21,960
我要提醒的就是什么呢
What I want to remind you is 
10
00:00:21,960 --> 00:00:23,800
一定用开水烫一下（棒子面）
Remember to use boiling water when mixing flour (corn flour)
11
00:00:23,800 --> 00:00:26,320
烫的硬一些 然后搁上
Mix until a bit hard, and then
12
00:00:26,320 --> 00:00:29,320
三分之一或者四分之一的白面
Add ⅓ or ¼ of wheat flour
13
00:00:29,320 --> 00:00:31,560
里边适当的少搁一点盐
Add a little bit salt
14
00:00:31,560 --> 00:00:33,680
面和好了 好了
Is the dough kneaded already? Yes 
15
00:00:33,680 --> 00:00:35,840
我看这面有点多
I think the dough is a little bit too much
16
00:00:35,840 --> 00:00:39,000
面和好了 我们饧一饧 盖块小屉布
Rest the dough after kneaded, cover a piece of cloth
17
00:00:39,000 --> 00:00:41,720
下一项咱们备小料
Next, let’s prepare some ingredients
18
00:00:41,720 --> 00:00:47,320
来点五花肉 根据自己的喜好可多可少
Pork belly, meats ration depends on your preference
19
00:00:47,320 --> 00:00:49,720
把肉切成肉丁
Cut the meat into fine dice
20
00:00:49,720 --> 00:00:53,400
这肉丁切小点 借味
Cut the dices a little smaller, so that lends flavor
21
00:00:53,400 --> 00:00:55,840
肉切好了
The meat was cut
22
00:00:55,840 --> 00:01:03,720
青蒜 豌豆 胡萝卜 葱头
Green garlic, pea, carrot, onion
23
00:01:03,720 --> 00:01:09,680
肉丁 香菇 葱姜
Meat dice, shiitake mushroom, scallion and ginger
24
00:01:09,680 --> 00:01:12,720
爱吃什么放什么 挺随意的
Just feel free to add what you like
25
00:01:12,720 --> 00:01:15,560
这面呢 也饧好了
The dough has rested already
26
00:01:15,560 --> 00:01:19,640
刚才我趁大妈没注意 我给揉了揉
I just kneaded it again when DaMa didn’t notice
27
00:01:19,640 --> 00:01:23,120
特别滋润 又挺硬
Very glutinous, and hard
28
00:01:23,120 --> 00:01:27,120
这个面有两种成型方式
This dough has two ways of forming
29
00:01:27,120 --> 00:01:30,600
一种擀的厚一点 再切丁
One is roll out thicker and cut it into dice
30
00:01:30,600 --> 00:01:33,800

31
00:01:33,800 --> 00:01:35,760
切成厚片
Cut into thick slice
32
00:01:35,760 --> 00:01:38,240
我们拖点面
Let’s cover some flour
33
00:01:38,240 --> 00:01:40,520
但是擀它显得瓷实
It will be solid if we roll it
34
00:01:40,520 --> 00:01:43,320
这个显得松软 省事儿这个
And this way will be soft, and easy
35
00:01:43,320 --> 00:01:45,600
这个不能太大了
Don’t cut too big
36
00:01:45,600 --> 00:01:47,280
太大了有时候煮的不好熟
It’s hard to cooked if it’s too big
37
00:01:47,280 --> 00:01:49,160
吃的时候也费劲
Also hard to eat
38
00:01:49,160 --> 00:01:51,880

39
00:01:51,880 --> 00:01:54,560
准备一盆 要干
One basin of dry dough dices
40
00:01:54,560 --> 00:01:59,080
还有一种 就跟擀面条一样
the other way just like make noodles
41
00:01:59,080 --> 00:02:03,480
在家里做饭就是玩儿  什么玩儿呢
It’s fun to cook at home
42
00:02:03,480 --> 00:02:04,920
你看跟过家家似的
Like playing house
43
00:02:04,920 --> 00:02:07,160

44
00:02:07,160 --> 00:02:13,200
要是大家没有时间 其实超市有卖的
If you don’t have time to make a dough, you can buy it in the supermarket
45
00:02:13,200 --> 00:02:16,840
那个买回来煮的时候得多煮一会儿
But if you buy it in the supermarket, you need to cook longer 
46
00:02:16,840 --> 00:02:18,400
它那特别硬
Because it’s tough
47
00:02:19,200 --> 00:02:20,040

48
00:02:20,040 --> 00:02:23,400
这家里头有个大厨
It’s so happy, super happy
49
00:02:23,400 --> 00:02:26,120
他就是幸福 幸福极了
To have a chef at home
50
00:02:26,120 --> 00:02:28,520

51
00:02:30,040 --> 00:02:31,760
撒点干面 摇
Sprinkle with some flour, shake it
52
00:02:31,760 --> 00:02:33,400

53
00:02:33,400 --> 00:02:35,600
下锅了啊 开了
Put in the pot
54
00:02:35,600 --> 00:02:38,640
煮完了煮的时间稍微长一点
Cook a little longer
55
00:02:38,640 --> 00:02:40,320
比面条要长一点
longer than cook noodles
56
00:02:40,320 --> 00:02:43,320
面疙瘩马上就出锅了
Dough dices almost cooked
57
00:02:43,320 --> 00:02:46,120
咱们现在开始炒菜 炒这料
Now we begin to fry the ingredients
58
00:02:46,120 --> 00:02:48,360
还是一个 热锅凉油
Add oil after heat up the wok
59
00:02:48,360 --> 00:02:50,960
这个时候的油稍微多一点 它香
We need a little more oil, assist aroma
60
00:02:50,960 --> 00:02:53,360
先煸肉丁
Stir-fry the meat dice first
61
00:02:53,360 --> 00:02:55,360

62
00:02:55,360 --> 00:02:58,520
如果家里有老人这肉丁得浆一下
mash the meat if have old people at home
63
00:02:58,520 --> 00:03:01,480
但是一般咱们吃就不用浆了
But we don’t need to mash
64
00:03:01,480 --> 00:03:06,600
为什么 主要我们要肥瘦肉
Because the pork belly
65
00:03:06,600 --> 00:03:09,520
也是有增香的一种效果
Can assist flavor
66
00:03:09,520 --> 00:03:13,160
肉煸出点油来 葱姜也（出香味了）
Stir fry the meat with oil, and scallion and ginger also have aroma
67
00:03:13,160 --> 00:03:18,600
胡萝卜 豌豆 出下水 焯了一下
Parboil the carrot and peas
68
00:03:18,600 --> 00:03:20,240
煸炒
stir-fry
69
00:03:20,240 --> 00:03:21,280

70
00:03:21,280 --> 00:03:22,640
放材料
Add seasoning
71
00:03:22,640 --> 00:03:26,480
酱油 这个色也是随着自己
Soy sauce, this color also according to your preference.
72
00:03:26,480 --> 00:03:28,360
黄酒
Huangjiu rice wine
73
00:03:28,360 --> 00:03:30,680
大爷搁盐还是猛
Daye love to add strong salt
74
00:03:30,680 --> 00:03:32,120
别那么猛
Don’t add too much
75
00:03:32,120 --> 00:03:36,200
一勺两勺 得三勺 两勺半
Two and a half spoon of salt
76
00:03:36,200 --> 00:03:40,160
把葱头下去 葱头后下
And then put onion, put onion later
77
00:03:42,360 --> 00:03:45,280
太晚了也不行 下早了也不行
But don’t too late also don’t too early 
78
00:03:45,280 --> 00:03:51,040
太早了它就炒老了  炒老了就不好吃了
It will be too old if you put early, then it will not delicious
79
00:03:51,040 --> 00:03:54,560
搁点蚝油 胡椒粉
Some oyster sauce,some pepper
80
00:03:55,160 --> 00:03:58,000
这个料炒得了
And we done the ingredient
81
00:03:58,000 --> 00:04:02,560
大妈稍微给看着一点 我捞面
Dama will help me to look out, I’ll get some GeDa
82
00:04:02,560 --> 00:04:07,120
二厨也扒拉两下 瞧瞧咱们挺专业的吧
Second chef also join the cook, look, we are professional, right
83
00:04:07,120 --> 00:04:09,480

84
00:04:09,480 --> 00:04:11,920
火大点儿没事
It’s okay to the heat a little higer
85
00:04:11,920 --> 00:04:14,880
好了 这可太多了
Okay. This is too much
86
00:04:16,440 --> 00:04:18,120
青蒜
Green garlic
87
00:04:18,120 --> 00:04:19,000

88
00:04:19,480 --> 00:04:23,240
搁点果仁行不行啊 可以 那才香啊
Can we put some nut? Of course
89
00:04:23,240 --> 00:04:26,560
搁点花生碎 撒点芝麻
You can put some crushed peanut, or sesame
90
00:04:26,560 --> 00:04:29,520
这个在锅里边稍微炒一炒
Stir-fry in the pot
91
00:04:29,520 --> 00:04:33,880
因为它有面的淀粉
Because the starch of the dough
92
00:04:33,880 --> 00:04:36,120
炒的时候黏黏糊糊的
It’s glutinous when you fry
93
00:04:36,120 --> 00:04:41,520
然后最好锅底火大一点还带点嘎巴
And better to a bit heat up.
94
00:04:41,520 --> 00:04:44,960
关火了 熟了
Okay we done
95
00:04:44,960 --> 00:04:46,520
装盘
Serve
96
00:04:46,520 --> 00:04:51,480
让大家看看 这是效果
Everyone look at it, this is result
97
00:04:51,480 --> 00:04:54,040
这行了吧 可以了
All set? yes
98
00:04:54,040 --> 00:04:56,840
大厨拿着是不是
Chef should hold it
99
00:04:57,800 --> 00:05:00,600
家有大厨 就是幸福
It’s happy to have a chef at home
100
00:05:00,600 --> 00:05:02,760
谢谢大爷
Thank you, Daye
101
00:05:02,760 --> 00:05:04,720

102
00:05:06,920 --> 00:00:01,960

103
00:05:08,680 --> 00:00:02,000
