### ISSUE TITLE
【美食作家王刚】香葱蛋炒饭 - https://youtu.be/hgYXRuQcniw

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1065]
**视频链接**：https://youtu.be/hgYXRuQcniw

视频时长5:44，预计发布时间为北京时间5月21日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“香葱蛋炒饭”的家常做法，满满的“锅气”，松散干香！

简介
大家好，看过我之前教大家的炒饭视频的朋友们肯定知道一个秘诀，就是分开蛋清蛋黄来炒，炒出蛋黄油，这样最终炒饭就会有金色银色的鸡蛋颗粒，不仅美观并且很香，但是家里做可能就会觉得有些复杂，不够家常。所以今天就来教大家一个特别家常的炒法“香葱煎蛋炒饭”，将鸡蛋两面煎香之后放入辅料炒香再加入冷饭，最后调味炒出“锅气”出锅即可，非常快捷方便。特别推荐大家可以根据个人口味加入“二荆条”辣椒，本身没有多少辣味，但清香味十足和香葱的香搭配相得益彰，十分安逸！如果有兴趣想看我之前的炒饭的朋友可以点击链接：蛋炒饭 https://www.youtube.com/watch?v=EvE5cYNXufY&t=1s 酱油炒饭 https://www.youtube.com/watch?v=1Q-5eIBfBDQ&t=30s

字幕
0:00:00.247,0:00:00.902
哈喽大家好

0:00:01.044,0:00:04.796
我伯爷昨天饭煮多了放在冰箱里面冻得比较硬

0:00:05.309,0:00:07.292
这个冷饭只有拿来炒饭哦

0:00:07.292,0:00:09.132
做蛋炒饭

0:00:09.203,0:00:10.938
然后准备了一些鸡蛋

0:00:11.309,0:00:16.283
再加一些这个辣椒来做一个香葱版本的蛋炒饭吧

0:00:16.619,0:00:20.159
我们这个鸡蛋的话打进去不用搅它

0:00:22.672,0:00:24.318
直接下锅煎就可以了

0:00:26.495,0:00:27.699
煎香了再用来炒

0:00:29.309,0:00:30.495
这个鸡蛋就打好了

0:00:30.831,0:00:33.168
这个辣椒我们直接切成颗粒就好了

0:00:35.150,0:00:36.672
其实也不是很辣噶这个辣椒

0:00:36.725,0:00:37.663
 这个辣椒不辣

0:00:42.159,0:00:44.796
再切一个大红椒配一下颜色

0:00:45.592,0:00:47.309
同样的也是切成颗粒

0:00:47.504,0:00:48.867
辣椒籽也不要浪费了

0:00:49.026,0:00:50.831
其实辣椒籽炒在里面很香的

0:00:51.964,0:00:53.415
这个又不辣的

0:00:54.035,0:00:56.442
我们在酒店里面做的话这个辣椒籽是不要得

0:00:56.460,0:00:58.230
因为影响美观

0:01:01.646,0:01:03.362
我们最后再切点小葱

0:01:04.070,0:01:05.008
就多放一点

0:01:05.716,0:01:07.398
我四伯爷喜欢吃葱

0:01:10.584,0:01:12.088
放在一边

0:01:13.522,0:01:14.513
好 可以了

0:01:16.017,0:01:17.292
你来帮我拿一下鸡蛋

0:01:17.451,0:01:17.964
好嘛 好

0:01:58.686,0:02:02.212
我们这个鸡蛋下锅不要去搅散直接这样煎

0:02:03.975,0:02:05.120
煎到它香为止

0:02:09.567,0:02:11.993
然后煎香了之后把它翻过来

0:02:56.897,0:03:00.164
  四伯爷这样炒的比你柴火灶炒的更好吃哦

0:03:00.211,0:03:03.313
当然哦火要大就大要小就小

0:03:44.512,0:03:45.123
好了 

0:03:49.118,0:03:50.458
诶呀 好香哦

0:03:56.639,0:03:58.824
看到没四伯爷锅里都还有锅气

0:04:03.219,0:04:04.065
来四伯爷

0:04:04.183,0:04:04.770
吃饭

0:04:05.381,0:04:07.920
尝哈看我给你炒的炒饭

0:04:08.601,0:04:10.129
这是你的碗 我给你舀起

0:04:10.152,0:04:11.116
来嘛伯娘

0:04:15.746,0:04:17.696
你先尝一下看吃得惯不

0:04:18.895,0:04:19.482
来伯爷

0:04:21.104,0:04:22.491
嗯 好香哦

0:04:24.794,0:04:25.381
该好吃噶

0:04:25.828,0:04:26.204
嗯

0:04:33.043,0:04:34.195
辣不辣哦 四伯爷

0:04:34.312,0:04:35.346
不辣 一点儿都不辣

0:04:35.346,0:04:39.600
这个蛋炒饭比上次去成都吃的那个更好吃

0:04:39.764,0:04:41.786
这个青椒的清香味才安逸

0:04:42.726,0:04:44.794
我们自己在家里面吃蛋炒饭

0:04:44.864,0:04:46.204
这个鸡蛋不用搅

0:04:46.204,0:04:48.225
直接给它慢慢煎香了再来炒

0:04:49.988,0:04:55.370
然后炒蛋炒饭最重要的一个就是火要散得开

0:04:55.511,0:04:57.320
然后不要太大的冲劲

0:04:57.438,0:05:01.339
就是让这个铁锅保持有锅气

0:05:01.410,0:05:03.243
然后这个饭在里 面炒

0:05:04.747,0:05:07.168
炒饭如果没有锅气就不会香

0:05:09.823,0:05:15.088
所以我敢说这个炒饭的话比四伯爷在土灶上面炒的更香

0:05:15.229,0:05:15.863
嗯

0:05:15.981,0:05:20.188
还有就是我们蛋炒饭不要拿热饭去炒

0:05:20.352,0:05:22.326
热饭的话炒出来不香

0:05:22.397,0:05:24.911
必须是冷饭

0:05:25.499,0:05:27.849
而且这个冷饭还要偏硬一点点

0:05:27.920,0:05:29.024
太软了也不行

0:05:31.022,0:05:33.936
软了煎起不散酥都嘛

0:05:34.077,0:05:35.229
就是坨坨货

0:05:36.733,0:05:38.307
好啦本期视频就到这里

0:05:39.153,0:05:40.775
喜欢的可以在家里面试一下

0:05:41.175,0:05:41.668
拜拜


```

**Comment by Yingzhang1122** [comment]
#标题（翻译主要意思即可，不要超过 100 个字符）
#厨师长分享：“香葱蛋炒饭”的家常做法，满满的“锅气”，松散干香！
Chef Wang shares: Home-style cooking of 'Fried rice with egg and spring onion'. Full of 'wok hei', dry, loose, and delicious!

#简介
#大家好，看过我之前教大家的炒饭视频的朋友们肯定知道一个秘诀，就是分开蛋清蛋黄来炒，炒出蛋黄油，这样最终炒饭就会有金色银色的鸡蛋颗粒，不仅美观并且很香，但是家里做可能就会觉得有些复杂，不够家常。所以今天就来教大家一个特别家常的炒法“香葱煎蛋炒饭”，将鸡蛋两面煎香之后放入辅料炒香再加入冷饭，最后调味炒出“锅气”出锅即可，非常快捷方便。特别推荐大家可以根据个人口味加入“二荆条”辣椒，本身没有多少辣味，但清香味十足和香葱的香搭配相得益彰，十分安逸！如果有兴趣想看我之前的炒饭的朋友可以点击链接：蛋炒饭 https://www.youtube.com/watch?v=EvE5cYNXufY&t=1s 酱油炒饭 https://www.youtube.com/watch?v=1Q-5eIBfBDQ&t=30s
Hi everyone! If you have watched my videos about fried rice, you should know about this trick: stir-fry the egg white and yolk separately to draw the lipid out of the yolk, such that the fried rice comes with golden and silver egg granules. In this way, the dish looks beautiful and tastes great, but you may feel it too complicated to follow it in home cooking. So today I'm going to teach you the home-style cooking of 'fried rice with egg and spring onion'. First, fry both sides of the egg. Add other ingredients into the wok, stir-fry them, and add cold rice into the wok. Finally, season the dish, stir-fry it until 'wok hei' appears, and it's ready to serve! It's very simple and fast to cook this dish. I would also specially recommend you to add 'Erjingtiao' chili pepper, which is not too spicy, but rich in aroma and matches well with the spring onion. If you are interested in my previous fried rice recipes, please follow the links here: Fried rice with egg https://www.youtube.com/watch?v=EvE5cYNXufY&t=1s Fried rice with light soy sauce https://www.youtube.com/watch?v=1Q-5eIBfBDQ&t=30s

#字幕
0:00:00.247,0:00:00.902
#哈喽大家好
Hi everyone

0:00:01.044,0:00:04.796
#我伯爷昨天饭煮多了放在冰箱里面冻得比较硬
My uncle cooked much rice yesterday, which was put in the fridge and is now frozen hard

0:00:05.309,0:00:07.292
#这个冷饭只有拿来炒饭哦
The cold rice can only be used to cook fried rice

0:00:07.292,0:00:09.132
#做蛋炒饭
Fried rice with egg

0:00:09.203,0:00:10.938
#然后准备了一些鸡蛋
I also prepared some eggs

0:00:11.309,0:00:16.283
#再加一些这个辣椒来做一个香葱版本的蛋炒饭吧
Let's cook 'fried rice with egg and spring onion' with the chili pepper here

0:00:16.619,0:00:20.159
#我们这个鸡蛋的话打进去不用搅它
We don't need to stir the egg now

0:00:22.672,0:00:24.318
#直接下锅煎就可以了
Just fry it in the wok

0:00:26.495,0:00:27.699
#煎香了再用来炒
When the egg smells good, we can use it for stir-frying

0:00:29.309,0:00:30.495
#这个鸡蛋就打好了
The eggs are done

0:00:30.831,0:00:33.168
#这个辣椒我们直接切成颗粒就好了
Simply cut the chili pepper into dices

0:00:35.150,0:00:36.672
#其实也不是很辣噶这个辣椒
This chili is actually not spicy, huh?

0:00:36.725,0:00:37.663
#这个辣椒不辣
No, not spicy

0:00:42.159,0:00:44.796
#再切一个大红椒配一下颜色
Cut a red bell pepper for the color

0:00:45.592,0:00:47.309
#同样的也是切成颗粒
Similarly, cut into dices

0:00:47.504,0:00:48.867
#辣椒籽也不要浪费了
Don't throw away the seeds

0:00:49.026,0:00:50.831
#其实辣椒籽炒在里面很香的
Actually the dish smells very nice with the seeds

0:00:51.964,0:00:53.415
#这个又不辣的
This is not spicy at all

0:00:54.035,0:00:56.442
#我们在酒店里面做的话这个辣椒籽是不要得
In restaurants, we usually discard the seeds

0:00:56.460,0:00:58.230
#因为影响美观
Because the dish doesn't look good with them

0:01:01.646,0:01:03.362
#我们最后再切点小葱
Finally, cut some spring onion

0:01:04.070,0:01:05.008
#就多放一点
Let me add more spring onion

0:01:05.716,0:01:07.398
#我四伯爷喜欢吃葱
Because my uncle likes it

0:01:10.584,0:01:12.088
#放在一边
Put aside

0:01:13.522,0:01:14.513
#好 可以了
Ok. Done

0:01:16.017,0:01:17.292
#你来帮我拿一下鸡蛋
Please take the egg

0:01:17.451,0:01:17.964
#好嘛 好
Ok. Sure

0:01:58.686,0:02:02.212
#我们这个鸡蛋下锅不要去搅散直接这样煎
Don't stir the egg after you add it into the wok. Just fry it like this

0:02:03.975,0:02:05.120
#煎到它香为止
Until you can smell the aroma

0:02:09.567,0:02:11.993
#然后煎香了之后把它翻过来
Flip the egg when it smells nice

0:02:56.897,0:03:00.164
#四伯爷这样炒的比你柴火灶炒的更好吃哦
Uncle, the dish cooked here will taste better than those cooked on your wood stove

0:03:00.211,0:03:03.313
#当然哦火要大就大要小就小
Of course. You can easily tune the heat

0:03:44.512,0:03:45.123
#好了 
Done

0:03:49.118,0:03:50.458
#诶呀 好香哦
Wow. Smells great

0:03:56.639,0:03:58.824
#看到没四伯爷锅里都还有锅气
See it, uncle? There's still 'wok hei' (smoke) in the wok

0:04:03.219,0:04:04.065
#来四伯爷
Come on, uncle

0:04:04.183,0:04:04.770
#吃饭
Time for meal!

0:04:05.381,0:04:07.920
#尝哈看我给你炒的炒饭
Try the fried rice that I cooked for you

0:04:08.601,0:04:10.129
#这是你的碗 我给你舀起
This is your bowl. Let me scoop some for you

0:04:10.152,0:04:11.116
#来嘛伯娘
Come on, aunt

0:04:15.746,0:04:17.696
#你先尝一下看吃得惯不
Just take a bite first to see if you are used to it

0:04:18.895,0:04:19.482
#来伯爷
This is yours, uncle

0:04:21.104,0:04:22.491
#嗯 好香哦
Umm. Delicious

0:04:24.794,0:04:25.381
#该好吃噶
Tasty indeed, huh?

0:04:25.828,0:04:26.204
#嗯
Yes

0:04:33.043,0:04:34.195
#辣不辣哦 四伯爷
Is it spicy, uncle?

0:04:34.312,0:04:35.346
#不辣 一点儿都不辣
Nope. Not at all

0:04:35.346,0:04:39.600
#这个蛋炒饭比上次去成都吃的那个更好吃
This fried rice is even better than the one that I had in Chengdu last time

0:04:39.764,0:04:41.786
#这个青椒的清香味才安逸
The clear aroma of the green chili pepper is really nice

0:04:42.726,0:04:44.794
#我们自己在家里面吃蛋炒饭
When cooking fried rice at home

0:04:44.864,0:04:46.204
#这个鸡蛋不用搅
You don't actually need to stir the egg

0:04:46.204,0:04:48.225
#直接给它慢慢煎香了再来炒
Just fry it first. Then stir-fry other ingredients

0:04:49.988,0:04:55.370
#然后炒蛋炒饭最重要的一个就是火要散得开
In addition, the most important point in cooking fried rice is that, the heat should be uniform

0:04:55.511,0:04:57.320
#然后不要太大的冲劲
Avoid sudden temperature change #请检查这里

0:04:57.438,0:05:01.339
#就是让这个铁锅保持有锅气
That is, to keep the 'wok hei' in the wok

0:05:01.410,0:05:03.243
#然后这个饭在里 面炒
Such that you can stir-fry the rice

0:05:04.747,0:05:07.168
#炒饭如果没有锅气就不会香
Without the 'wok hei', the rice won't be delicious

0:05:09.823,0:05:15.088
#所以我敢说这个炒饭的话比四伯爷在土灶上面炒的更香
So I bet this fried rice is better than those cooked on my uncle's wood stove

0:05:15.229,0:05:15.863
#嗯
Yep

0:05:15.981,0:05:20.188
#还有就是我们蛋炒饭不要拿热饭去炒
One more thing, don't use hot rice for cooking fried rice

0:05:20.352,0:05:22.326
#热饭的话炒出来不香
Hot rice won't taste good after stir-frying

0:05:22.397,0:05:24.911
#必须是冷饭
It has to be cold rice

0:05:25.499,0:05:27.849
#而且这个冷饭还要偏硬一点点
Also the cold rice should be relatively hard

0:05:27.920,0:05:29.024
#太软了也不行
It won't work if it's too soft

0:05:31.022,0:05:33.936
#软了煎起不散酥都嘛
Soft rice won't be loose like this

0:05:34.077,0:05:35.229
#就是坨坨货
The rice will aggregate into balls

0:05:36.733,0:05:38.307
#好啦本期视频就到这里
Ok. That's the end of this video

0:05:39.153,0:05:40.775
#喜欢的可以在家里面试一下
If you like it, please try at your home

0:05:41.175,0:05:41.668
#拜拜
Bye-bye!
