### ISSUE TITLE
【美食作家王刚】“泥虫”的清蒸做法 - https://youtu.be/WxgmHXPR6l4

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1070]
**视频链接**：https://youtu.be/WxgmHXPR6l4

视频时长7:20，预计发布时间为北京时间5月23日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：天然味精“泥虫”的清蒸做法，口感爽脆味道鲜美（四伯差点没敢吃😂）

简介
大家好，今天给大家介绍一个可能内地朋友不太知道的美食“泥虫”，这种生物在不同的地区还叫“泥丁”“土笋”“土钉”等等，在东南沿海尤其是福建广东广西非常受欢迎，虽说看起来让人提不起食欲来，但吃起来却很鲜美，清蒸小炒做汤都是不错的选择，并且有“天然味精之称”。不过经过亲测要说的是新鲜的泥虫要比冰冻过的鲜美很多，有条件的朋友可以直接去沿海城市体验。

字幕
0:00:00.200,0:00:00.925
哈喽大家好

0:00:00.975,0:00:03.725
我朋友上次给我送的血蛤吃完了之后呢

0:00:03.875,0:00:05.525
这次给我寄了一些泥虫过来

0:00:05.925,0:00:08.629
我四伯爷说这个泥虫翻过来就像什么

0:00:08.700,0:00:10.650
像蚯蚓那种大蚯蚓

0:00:10.900,0:00:12.100
这个是不是肠子哦

0:00:12.425,0:00:14.400
这个不是肠子 是它的肚子

0:00:14.975,0:00:16.450
肚子里面翻过来的

0:00:17.025,0:00:18.475
我们这个泥虫啊

0:00:18.925,0:00:22.000
我四伯从来没吃过 这个属于一个海鲜吧

0:00:22.100,0:00:24.925
属于泥沙里面的一个东西

0:00:26.200,0:00:29.125
他给我寄过来的时候就已经是处理好了

0:00:29.225,0:00:31.875
就是已经帮我们翻洗过了

0:00:31.875,0:00:37.175
就是说我把它解完冻了之后直接都可以做了

0:00:38.850,0:00:42.775
这个泥虫营养特别的丰富

0:00:42.900,0:00:47.075
就是说特别适合你们这种老人吃

0:00:49.000,0:00:51.375
我看见这种就感觉多脏一样

0:00:51.500,0:00:52.050
脏吗

0:00:52.850,0:00:54.850
不是得 是它颜色就是这样子的

0:00:54.850,0:00:58.475
这个须须是它的肚子

0:00:59.250,0:01:01.025
这个是处理干净了的 四伯爷

0:01:01.575,0:01:06.900
哎呀 反正就是说我就觉得多脏没吃过这些东西

0:01:08.325,0:01:10.625
这个营养好得很 我给你说嘛

0:01:12.775,0:01:15.325
这次我准备用来做成清蒸

0:01:15.675,0:01:17.275
吃下它的本味

0:01:17.600,0:01:18.750
做清蒸就可以了

0:01:18.875,0:01:22.250
因为这个处理好了现在我来切点辅料

0:01:23.000,0:01:26.025
这个泥虫我们就按照广东的做法来做

0:01:26.075,0:01:28.350
给它切点姜丝到里面

0:01:33.075,0:01:33.900
放到这里面

0:01:33.950,0:01:35.575
然后再切点葱

0:01:37.450,0:01:39.025
这会儿才说整这些来吃

0:01:39.025,0:01:44.050
以前老年人看到这种他会整来吃啊

0:01:44.525,0:01:46.925
这个是看到脏吃起来好吃得很

0:01:47.050,0:01:48.400
它长得不好看

0:01:50.400,0:01:52.375
长得丑也不是它的错

0:01:52.625,0:01:54.393
好吃就行了 是不是嘛

0:01:55.450,0:01:57.400
 然后我们这个再放点盐

0:02:02.075,0:02:03.225
这个是蒸吗

0:02:03.225,0:02:04.125
嗯 用蒸

0:02:04.325,0:02:08.425
这个放了盐之后呢 我们把它拌匀

0:02:13.375,0:02:16.300
然后拌匀了之后再加点油进去拌一下

0:02:18.100,0:02:19.568
加这个油拌一下的话

0:02:19.600,0:02:21.875
蒸出来就更嫩口感就更好

0:02:22.500,0:02:24.375
这个蒸出来比较清甜

0:02:25.375,0:02:27.275
好啦 就这样子

0:02:27.400,0:02:29.075
马上蒸起就可以吃了

0:02:29.125,0:02:30.375
这个可能蒸不到好久

0:02:30.550,0:02:31.450
3分钟

0:02:31.925,0:02:32.650
哦

0:02:32.925,0:02:33.950
那可以

0:03:05.250,0:03:07.323
我们这个泥虫千万不要蒸太久

0:03:07.375,0:03:08.470
3分钟就够了

0:03:08.500,0:03:10.300
如果蒸的时间太长的话

0:03:10.325,0:03:13.300
它就变得不脆了就比较老

0:04:10.050,0:04:11.350
好 差不多了

0:04:18.150,0:04:18.600
诶呀

0:04:19.700,0:04:20.550
好烫哦

0:04:21.225,0:04:22.850
好 来吃四伯爷

0:04:27.500,0:04:28.425
四伯爷尝哈看

0:04:29.350,0:04:33.912
我尝哈看嘛 这东西看起有点脏咋吃得下去哦

0:04:33.912,0:04:36.194
这个你看这条跟蚂蟥一样你尝哈这条

0:04:36.653,0:04:39.046
我另外夹我另外选都要的

0:04:39.371,0:04:41.744
你这个东西我没吃过吃起还有（点害怕）

0:04:43.103,0:04:44.563
这口感特别脆

0:04:44.787,0:04:46.105
吃起还有点怕

0:04:50.081,0:04:51.987
都是一样的随便夹一条嘛

0:04:52.089,0:04:53.732
我找一条好点的看

0:05:01.744,0:05:03.346
没得怪味的呀

0:05:04.908,0:05:05.659
没得怪味得噶

0:05:06.551,0:05:07.058
香不香

0:05:07.829,0:05:08.864
诶 还可以

0:05:09.695,0:05:11.115
是不是有股清甜的味道

0:05:11.217,0:05:11.744
嗯

0:05:12.434,0:05:16.004
我们这个泥虫不要蒸太久了3分钟就够了

0:05:16.024,0:05:20.669
然后吃起来它有种脆脆的有股清甜味

0:05:20.669,0:05:22.048
然后很香

0:05:22.150,0:05:23.509
嘿 还可以

0:05:23.894,0:05:26.774
先前看到还吃不下去

0:05:33.367,0:05:34.705
有一股姜葱的香味

0:05:34.807,0:05:35.172
嗯

0:05:35.882,0:05:37.444
还有就是有股清甜味

0:05:38.194,0:05:38.519
是

0:05:39.574,0:05:44.685
不放葱姜丝的话就没的味得

0:05:45.456,0:05:45.801
是

0:05:47.917,0:05:50.817
然后这个泥虫的话在我们四川是没有的 

0:05:51.926,0:05:56.470
它是在沿海地区才会有

0:05:56.693,0:05:59.716
所以如果你们想试一下的话可以在网上买

0:06:00.669,0:06:04.665
要是我们这边办宴席那些老年人看着这种他不会吃

0:06:06.876,0:06:08.620
他没吃过也没看到过

0:06:10.142,0:06:11.785
这个营养很好 四伯爷

0:06:12.352,0:06:13.955
伯娘呢 叫伯娘来吃

0:06:14.462,0:06:15.131
这有筷子

0:06:18.052,0:06:18.803
啥子东西哦

0:06:18.803,0:06:19.269
诶呀

0:06:20.304,0:06:22.535
好吓人哦 跟蛇一样吃得下去不哦

0:06:23.184,0:06:23.632
不是的

0:06:23.632,0:06:25.192
先前我看到都害怕

0:06:25.212,0:06:25.821
吃嘛

0:06:25.902,0:06:27.180
我都吃不下去

0:06:27.728,0:06:28.843
那是虫啊

0:06:28.924,0:06:29.817
跟蚯蚓一样

0:06:29.939,0:06:31.703
泥虫海里的

0:06:31.724,0:06:35.659
四伯爷说这个像是大蚯蚓

0:06:35.699,0:06:37.281
我看见就跟大蚯蚓一样

0:06:37.383,0:06:37.991
好不好吃嘛

0:06:38.499,0:06:40.000
你吃一个嘛

0:06:40.223,0:06:40.851
你吃嘛

0:06:40.851,0:06:42.332
好吓人哦好恐怖

0:06:42.799,0:06:43.833
好恐怖哦

0:06:46.328,0:06:47.565
没得怪味得撒

0:06:48.722,0:06:50.283
你说看着很恐怖啊

0:06:52.920,0:06:54.807
 我先前看着还吃不来

0:06:57.423,0:06:59.513
你都敢吃我就敢吃怕什么怕

0:06:59.634,0:07:00.791
怕啥子怕

0:07:00.993,0:07:04.108
家里面如果有老人的话可以蒸来给老人吃

0:07:04.108,0:07:05.618
因为这个也可以降血压

0:07:09.208,0:07:11.095
好啦 本期视频就到这里啦

0:07:11.135,0:07:11.561
拜拜

0:07:12.576,0:07:14.056
伯娘可以多吃点

0:07:14.665,0:07:14.969
诶呀

0:07:16.348,0:07:17.139
你不要害怕

0:07:17.200,0:07:17.748
不怕


```

**Comment by Yingzhang1122** [comment]
#标题（翻译主要意思即可，不要超过 100 个字符）
#厨师长分享：天然味精“泥虫”的清蒸做法，口感爽脆味道鲜美（四伯差点没敢吃😂）
Chef Wang shares: Steamed 'natural MSG' (Peanut worm), crunchy and tasty (but uncle almost dared not eat it)!

#简介
#大家好，今天给大家介绍一个可能内地朋友不太知道的美食“泥虫”，这种生物在不同的地区还叫“泥丁”“土笋”“土钉”等等，在东南沿海尤其是福建广东广西非常受欢迎，虽说看起来让人提不起食欲来，但吃起来却很鲜美，清蒸小炒做汤都是不错的选择，并且有“天然味精之称”。不过经过亲测要说的是新鲜的泥虫要比冰冻过的鲜美很多，有条件的朋友可以直接去沿海城市体验。
Hi everyone, today I'm introducing you a type of delicious food, 'Ni chong' (Peanut worm), which may be strange to friends living inland. This species is also named as 'Ni ding', 'Tu sun', 'Tu ding', etc. in different areas and is really popular in the southeast coast of China, especially in Fujian, Guangdong, and Guangxi Provinces. Though its outlook may not agitate your appetite, it tastes really good and is suitable for various ways of cooking, such as steam, stir-fry, and boil. It also has a nickname of 'natural MSG'. However, I have to say that fresh peanut worms are much better than frozen ones. Please just go to coastal cities and have a try!

#字幕
0:00:00.200,0:00:00.925
#哈喽大家好
Hi everyone

0:00:00.975,0:00:03.725
#我朋友上次给我送的血蛤吃完了之后呢
After I finished the blood clams sent by my friend last time

0:00:03.875,0:00:05.525
#这次给我寄了一些泥虫过来
He sent me some peanut worms

0:00:05.925,0:00:08.629
#我四伯爷说这个泥虫翻过来就像什么
My uncle says that it looks like...

0:00:08.700,0:00:10.650
#像蚯蚓那种大蚯蚓
Earthworm. Big earthworms

0:00:10.900,0:00:12.100
#这个是不是肠子哦
Are these intestines?

0:00:12.425,0:00:14.400
#这个不是肠子 是它的肚子
Nope. It's the stomach #听了几遍感觉应该是胃，不是腹部的意思？

0:00:14.975,0:00:16.450
#肚子里面翻过来的
Flipped-over stomach

0:00:17.025,0:00:18.475
#我们这个泥虫啊
The peanut worm here...

0:00:18.925,0:00:22.000
#我四伯从来没吃过 这个属于一个海鲜吧
My uncle never had it. It's a kind of seafood...

0:00:22.100,0:00:24.925
#属于泥沙里面的一个东西
that lives in mud and sand

0:00:26.200,0:00:29.125
#他给我寄过来的时候就已经是处理好了
My friend has dealt with it before sending it to me

0:00:29.225,0:00:31.875
#就是已经帮我们翻洗过了
He rinsed it for us

0:00:31.875,0:00:37.175
#就是说我把它解完冻了之后直接都可以做了
That means we can cook it directly after unfreezing

0:00:38.850,0:00:42.775
#这个泥虫营养特别的丰富
The peanut worm is very nutritious 

0:00:42.900,0:00:47.075
#就是说特别适合你们这种老人吃
Thus it's suitable for elderly people like you

0:00:49.000,0:00:51.375
#我看见这种就感觉多脏一样
I think it looks really dirty

0:00:51.500,0:00:52.050
#脏吗
Dirty?

0:00:52.850,0:00:54.850
#不是得 是它颜色就是这样子的
It's not dirty actually. It just looks like this

0:00:54.850,0:00:58.475
#这个须须是它的肚子
This 'string' is the stomach

0:00:59.250,0:01:01.025
#这个是处理干净了的 四伯爷
They have been cleaned up, uncle

0:01:01.575,0:01:06.900
#哎呀 反正就是说我就觉得多脏没吃过这些东西
Hmm. Anyway I think it looks dirty and I had never eaten this before

0:01:08.325,0:01:10.625
#这个营养好得很 我给你说嘛
Come on! This is really nutritious

0:01:12.775,0:01:15.325
#这次我准备用来做成清蒸
This time I'm gonna steam it

0:01:15.675,0:01:17.275
#吃下它的本味
To taste its original taste

0:01:17.600,0:01:18.750
#做清蒸就可以了
Steaming is the best choice

0:01:18.875,0:01:22.250
#因为这个处理好了现在我来切点辅料
Since this has been prepared, I'm cutting some other ingredients

0:01:23.000,0:01:26.025
#这个泥虫我们就按照广东的做法来做
I'll cook the peanut worm in the Cantonese style

0:01:26.075,0:01:28.350
#给它切点姜丝到里面
Shred some ginger...

0:01:33.075,0:01:33.900
#放到这里面
and put into the plate

0:01:33.950,0:01:35.575
#然后再切点葱
And some green onion

0:01:37.450,0:01:39.025
#这会儿才说整这些来吃
Now people are beginning to eat such things...

0:01:39.025,0:01:44.050
#以前老年人看到这种他会整来吃啊
Which old man would eat this in the past?

0:01:44.525,0:01:46.925
#这个是看到脏吃起来好吃得很
It just looks dirty... But tastes really good

0:01:47.050,0:01:48.400
#它长得不好看
Ok. It's not good-looking

0:01:50.400,0:01:52.375
#长得丑也不是它的错
But being ugly is not its fault

0:01:52.625,0:01:54.393
#好吃就行了 是不是嘛
Being tasty is enough. Isn't it?

0:01:55.450,0:01:57.400
#然后我们这个再放点盐
Add some salt as well

0:02:02.075,0:02:03.225
#这个是蒸吗
Are we steaming it?

0:02:03.225,0:02:04.125
#嗯 用蒸
Yep. Steam it

0:02:04.325,0:02:08.425
#这个放了盐之后呢 我们把它拌匀
Mix everything well after adding salt

0:02:13.375,0:02:16.300
#然后拌匀了之后再加点油进去拌一下
Then add some oil, and mix again

0:02:18.100,0:02:19.568
#加这个油拌一下的话
With some oil here

0:02:19.600,0:02:21.875
#蒸出来就更嫩口感就更好
It will taste tenderer after steaming

0:02:22.500,0:02:24.375
#这个蒸出来比较清甜
Actually it tastes a bit sweet after steaming

0:02:25.375,0:02:27.275
#好啦 就这样子
Ok. Just like this

0:02:27.400,0:02:29.075
#马上蒸起就可以吃了
Steam it and ready to serve!

0:02:29.125,0:02:30.375
#这个可能蒸不到好久
It may not take very long?

0:02:30.550,0:02:31.450
#3分钟
3 minutes

0:02:31.925,0:02:32.650
#哦
Oh

0:02:32.925,0:02:33.950
#那可以
Sounds good

0:03:05.250,0:03:07.323
#我们这个泥虫千万不要蒸太久
Please never steam the peanut worm for too long

0:03:07.375,0:03:08.470
#3分钟就够了
3 minutes is just long enough

0:03:08.500,0:03:10.300
#如果蒸的时间太长的话
If steamed for too long

0:03:10.325,0:03:13.300
#它就变得不脆了就比较老
It'll no longer be tender, but becomes chewy

0:04:10.050,0:04:11.350
#好 差不多了
Ok. Almost done

0:04:18.150,0:04:18.600
#诶呀
Ouch

0:04:19.700,0:04:20.550
#好烫哦
It's so hot

0:04:21.225,0:04:22.850
#好 来吃四伯爷
Ok. Come and taste it, uncle

0:04:27.500,0:04:28.425
#四伯爷尝哈看
Uncle, just have a try

0:04:29.350,0:04:33.912
#我尝哈看嘛 这东西看起有点脏咋吃得下去哦
Let me try. But it looks dirty... How could I swallow it?

0:04:33.912,0:04:36.194
#这个你看这条跟蚂蟥一样你尝哈这条
Look. This one looks like a leech. Taste it?

0:04:36.653,0:04:39.046
#我另外夹我另外选都要的
Let me do it. Let me choose one for myself

0:04:39.371,0:04:41.744
#你这个东西我没吃过吃起还有（点害怕）
I've never had this stuff before so I'm a bit (afraid)

0:04:43.103,0:04:44.563
#这口感特别脆
It's very crunchy

0:04:44.787,0:04:46.105
#吃起还有点怕
I am a bit afraid of eating this

0:04:50.081,0:04:51.987
#都是一样的随便夹一条嘛
They are all the same. Just randomly pick one

0:04:52.089,0:04:53.732
#我找一条好点的看
Let me find a good-looking one

0:05:01.744,0:05:03.346
#没得怪味的呀
It doesn't taste weird

0:05:04.908,0:05:05.659
#没得怪味得噶
Not weird, huh?

0:05:06.551,0:05:07.058
#香不香
Is it delicious?

0:05:07.829,0:05:08.864
#诶 还可以
Hmm. It's ok

0:05:09.695,0:05:11.115
#是不是有股清甜的味道
Is it a bit sweet?

0:05:11.217,0:05:11.744
#嗯
Yep

0:05:12.434,0:05:16.004
#我们这个泥虫不要蒸太久了3分钟就够了
Don't steam the peanut worm for too long. 3 minutes would be enough

0:05:16.024,0:05:20.669
#然后吃起来它有种脆脆的有股清甜味
At this time, it is crunchy and tastes a bit sweet

0:05:20.669,0:05:22.048
#然后很香
Delicious indeed

0:05:22.150,0:05:23.509
#嘿 还可以
Hey. It's good

0:05:23.894,0:05:26.774
#先前看到还吃不下去
Previously I couldn't even swallow it

0:05:33.367,0:05:34.705
#有一股姜葱的香味
It also has the flavor of ginger and green onion

0:05:34.807,0:05:35.172
#嗯
Yes

0:05:35.882,0:05:37.444
#还有就是有股清甜味
And the sweet flavor

0:05:38.194,0:05:38.519
#是
You're right

0:05:39.574,0:05:44.685
#不放葱姜丝的话就没的味得
Without the ginger and green onion, it'll be plain

0:05:45.456,0:05:45.801
#是
Yes

0:05:47.917,0:05:50.817
#然后这个泥虫的话在我们四川是没有的 
We don't have such peanut worms here in Sichuan Province

0:05:51.926,0:05:56.470
#它是在沿海地区才会有
It only lives in coastal areas

0:05:56.693,0:05:59.716
#所以如果你们想试一下的话可以在网上买
So if you wanna have a try, you can buy some on the internet

0:06:00.669,0:06:04.665
#要是我们这边办宴席那些老年人看着这种他不会吃
If this is served on a banquet here, the old people won't eat it at all

0:06:06.876,0:06:08.620
#他没吃过也没看到过
They never had it nor seen it

0:06:10.142,0:06:11.785
#这个营养很好 四伯爷
This is really nutritious, uncle

0:06:12.352,0:06:13.955
#伯娘呢 叫伯娘来吃
Where's aunt? Let's ask her to try this

0:06:14.462,0:06:15.131
#这有筷子
Chopsticks here

0:06:18.052,0:06:18.803
#啥子东西哦
What's this?

0:06:18.803,0:06:19.269
#诶呀
Wow

0:06:20.304,0:06:22.535
#好吓人哦 跟蛇一样吃得下去不哦
Looks terrifying. Who can eat this snake-like stuff?

0:06:23.184,0:06:23.632
#不是的
Nope

0:06:23.632,0:06:25.192
#先前我看到都害怕
Previously even I was afraid of this

0:06:25.212,0:06:25.821
#吃嘛
Just have one

0:06:25.902,0:06:27.180
#我都吃不下去
I dared not eat it

0:06:27.728,0:06:28.843
#那是虫啊
Is that a worm?

0:06:28.924,0:06:29.817
#跟蚯蚓一样
Looks like an earthworm

0:06:29.939,0:06:31.703
#泥虫海里的
This is peanut worm. It's from the sea

0:06:31.724,0:06:35.659
#四伯爷说这个像是大蚯蚓
Uncle said this was like a big earthworm

0:06:35.699,0:06:37.281
#我看见就跟大蚯蚓一样
It looks like so

0:06:37.383,0:06:37.991
#好不好吃嘛
Is it delicious?

0:06:38.499,0:06:40.000
#你吃一个嘛
Just have a try

0:06:40.223,0:06:40.851
#你吃嘛
Try it!

0:06:40.851,0:06:42.332
#好吓人哦好恐怖
It's so scary. Terrifying

0:06:42.799,0:06:43.833
#好恐怖哦
Terrifying?

0:06:46.328,0:06:47.565
#没得怪味得撒
No weird flavor, right?

0:06:48.722,0:06:50.283
#你说看着很恐怖啊
You said it looks terrifying?

0:06:52.920,0:06:54.807
#我先前看着还吃不来
I didn't think I could eat this before

0:06:57.423,0:06:59.513
#你都敢吃我就敢吃怕什么怕
You dare, I dare. I'm not afraid

0:06:59.634,0:07:00.791
#怕啥子怕
There's nothing to be afraid of

0:07:00.993,0:07:04.108
#家里面如果有老人的话可以蒸来给老人吃
If you live with your older families, you can steam this for them

0:07:04.108,0:07:05.618
#因为这个也可以降血压
Because it can lower your blood pressure

0:07:09.208,0:07:11.095
#好啦 本期视频就到这里啦
Ok. That's the end of this video

0:07:11.135,0:07:11.561
#拜拜
Bye-bye!

0:07:12.576,0:07:14.056
#伯娘可以多吃点
Aunt, you can have some more

0:07:14.665,0:07:14.969
#诶呀
Ok

0:07:16.348,0:07:17.139
#你不要害怕
Don't be afraid

0:07:17.200,0:07:17.748
#不怕
I'm not
