### ISSUE TITLE
[老饭骨] 鲫鱼汤 - https://youtu.be/4r-HsmBhoFE

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1071]
**视频链接**：https://youtu.be/4r-HsmBhoFE

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【國宴大師•鯽魚湯】鯽魚湯更奶白更鮮的秘訣！大爺手把手教做家常版鯽魚湯，營養滋補超鮮美！520還不進來吃“狗糧”嗎？！|老飯骨

简介
小友們好，今天是520，大爺大媽為大家帶來一道家常版的蘿蔔絲鯽魚湯！
從處理魚開始，大爺手把手教大家，這樣做出的鯽魚湯才不會腥。
視頻里面的“大油”就是豬油的意思，用豬油煎出來這湯還白！
喜歡吃魚的小友可以把鱖魚片成片兒，在鍋裏燙一下。
要想知道這鯽魚湯更奶白更鮮的秘訣，小友們可要把視頻看仔細咯，都是細節！
520的恩愛大家感受到了嗎，暖暖的奶白鯽魚湯，快學起來做給妳的那個TA！

字幕
1
00:00:00,680 --> 00:00:03,280
你看看这样一刮就下来了

2
00:00:03,280 --> 00:00:04,440
真白

3
00:00:04,440 --> 00:00:06,240

4
00:00:06,240 --> 00:00:07,640
萝卜丝鲫鱼汤

5
00:00:07,640 --> 00:00:10,120

6
00:00:10,120 --> 00:00:13,280
你看我打鳞的时候也没打的那么干净

7
00:00:13,280 --> 00:00:15,440
为什么 还有个小处理

8
00:00:15,440 --> 00:00:18,240
这鱼上边有很多黑膜

9
00:00:18,240 --> 00:00:21,440
熬出这汤是灰的 咱们处理一下

10
00:00:21,440 --> 00:00:24,360
开开的水 小窍门

11
00:00:24,360 --> 00:00:25,480
先烫鱼头

12
00:00:25,480 --> 00:00:28,120

13
00:00:28,120 --> 00:00:29,960
再烫鱼尾

14
00:00:29,960 --> 00:00:33,000
你看一烫它就变色 发白了吧

15
00:00:33,000 --> 00:00:34,360
 翻一身儿

16
00:00:35,000 --> 00:00:38,600

17
00:00:38,600 --> 00:00:39,840
再烫这头

18
00:00:39,840 --> 00:00:42,040

19
00:00:42,040 --> 00:00:44,360
今天这好 现买的活鱼

20
00:00:44,360 --> 00:00:48,600
刚才蹦蹦蹦直跳呢 马上冲凉

21
00:00:48,600 --> 00:00:50,560

22
00:00:52,160 --> 00:00:55,440
你看看 这样一刮就下来了

23
00:00:55,440 --> 00:00:57,360
因为要赶快冲凉

24
00:00:57,360 --> 00:00:59,640
因为这鱼你烫大了也不行

25
00:00:59,640 --> 00:01:01,040
烫大了这皮破了

26
00:01:01,040 --> 00:01:05,640
所以瞬间要给它冲凉

27
00:01:05,640 --> 00:01:09,480
说这鱼的汤有土腥味是哪儿啊

28
00:01:09,480 --> 00:01:11,880
发苦 土腥味大 你看这黑膜

29
00:01:11,880 --> 00:01:14,240
这得拿手都给处理干净

30
00:01:14,240 --> 00:01:16,600
更重要的一点 这个鱼鳍

31
00:01:16,600 --> 00:01:20,960
划水 尾边的摆水  前面的鳍

32
00:01:20,960 --> 00:01:23,560
都得给弄干净了 为什么呢

33
00:01:23,560 --> 00:01:26,880
不弄干净它腥啊 上边（有）粘液

34
00:01:26,880 --> 00:01:30,480
你看照这边 看干净吧

35
00:01:30,480 --> 00:01:31,880
颜色也好看了

36
00:01:31,880 --> 00:01:35,480
那会儿煲出那汤来 倍儿白

37
00:01:35,480 --> 00:01:37,360
两条

38
00:01:37,360 --> 00:01:40,000
你看我们这个辅料是什么

39
00:01:40,000 --> 00:01:43,520
海米用开水泡上 先洗干净后泡

40
00:01:43,520 --> 00:01:45,480
这水要要的

41
00:01:45,480 --> 00:01:50,960
葱 姜 香菜 处理的还行吧

42
00:01:50,960 --> 00:01:52,800
这炖出这汤倍儿白

43
00:01:52,800 --> 00:01:55,720
萝卜丝鲫鱼汤

44
00:01:55,720 --> 00:01:58,600
这也是淮扬菜的老菜

45
00:01:58,600 --> 00:01:59,560

46
00:02:00,280 --> 00:02:01,800
这是淮扬菜啊

47
00:02:01,800 --> 00:02:04,800
瞧瞧 这大爷

48
00:02:04,800 --> 00:02:06,440
点火

49
00:02:06,440 --> 00:02:07,360

50
00:02:07,360 --> 00:02:10,080
这个锅一定要烧热

51
00:02:10,080 --> 00:02:13,440
我们常说的叫热锅凉油

52
00:02:13,440 --> 00:02:15,600
但是鲫鱼汤要好

53
00:02:15,600 --> 00:02:20,240
原本的最传统的搁点大油

54
00:02:20,240 --> 00:02:22,120
出来这汤还白的

55
00:02:22,120 --> 00:02:23,600

56
00:02:23,600 --> 00:02:25,960
油温得热一点儿

57
00:02:25,960 --> 00:02:27,680
大妈稍微远一点

58
00:02:27,680 --> 00:02:29,320

59
00:02:32,680 --> 00:02:34,680
这个鱼不用腌

60
00:02:34,680 --> 00:02:36,960

61
00:02:36,960 --> 00:02:40,640
不用动它啊 别动它一动皮破了

62
00:02:40,640 --> 00:02:44,640
没搁多少油就是煎

63
00:02:44,640 --> 00:02:44,840

64
00:02:44,840 --> 00:02:48,600
翻身了 再翻一下

65
00:02:48,600 --> 00:02:53,320
皮也没破吧 前期处理的好

66
00:02:53,320 --> 00:02:57,600
这时候我们要把葱姜随手就放进去了

67
00:02:57,600 --> 00:02:59,480
就可以了

68
00:02:59,480 --> 00:03:05,880
放水（热水） 大火

69
00:03:05,880 --> 00:03:09,840
黄酒 海米

70
00:03:09,840 --> 00:03:12,440
这得炖多长时间

71
00:03:12,440 --> 00:03:15,480
应该说是在一刻钟到二十分钟

72
00:03:15,480 --> 00:03:20,960
说去腥的方法很多 搁上几粒花椒

73
00:03:20,960 --> 00:03:25,080
开了 这个就用大火煮 大火熬鱼炖鱼

74
00:03:25,080 --> 00:03:28,360
为什么要把那汤给没过鱼了

75
00:03:28,360 --> 00:03:30,240
它得炖一会儿

76
00:03:30,240 --> 00:03:33,920
把它移到这火 同时进行

77
00:03:35,240 --> 00:03:37,640
胡椒 白胡椒

78
00:03:37,640 --> 00:03:39,280
盐待会再放

79
00:03:39,280 --> 00:03:42,080
盐早放它这个鱼就不爱烂

80
00:03:42,080 --> 00:03:47,560
出白汤的就慢 行 这个先慢慢炖着

81
00:03:47,560 --> 00:03:51,000
锅热了 这油不用要太多

82
00:03:51,000 --> 00:03:55,840
炒萝卜丝 去萝卜的臭味

83
00:03:55,840 --> 00:03:57,720
你看再照照那个

84
00:03:57,720 --> 00:04:01,040
那有点要白吧 白了已经起白了

85
00:04:01,040 --> 00:04:03,720
一放萝卜还白

86
00:04:03,720 --> 00:04:07,560
（萝卜丝）就是煸煸 花椒煸出味来就行

87
00:04:07,560 --> 00:04:10,560

88
00:04:10,560 --> 00:04:12,840
搁点水

89
00:04:12,840 --> 00:04:13,160

90
00:04:14,960 --> 00:04:19,760
这个还是要这样大的火

91
00:04:19,760 --> 00:04:22,800
这还要处理一下 把这浮沫给打出来

92
00:04:23,840 --> 00:04:25,960
一会它一开锅还有沫子呢

93
00:04:25,960 --> 00:04:27,480
那沫子是油沫

94
00:04:27,480 --> 00:04:32,200
把那油给打干净 这萝卜丝就没有臭味了

95
00:04:32,200 --> 00:04:34,720
我做这个就特别拿手

96
00:04:34,720 --> 00:04:38,960
原来在饭店的时候 有些老领导

97
00:04:38,960 --> 00:04:42,720
就爱吃大爷这个萝卜丝鲫鱼汤

98
00:04:42,720 --> 00:04:45,240
一种方式就是喝汤

99
00:04:45,240 --> 00:04:48,640
再一种方式在这也跟网友说一声

100
00:04:48,640 --> 00:04:53,400
想吃鱼 别吃鲫鱼 买条鳜鱼

101
00:04:53,400 --> 00:04:57,120
鳜鱼片成片 在这锅里边一烫

102
00:04:57,120 --> 00:05:02,400
鳜鱼的鱼片 汤必须是鲫鱼的

103
00:05:02,400 --> 00:05:07,200
萝卜丝已经好了 咱把它捞出来

104
00:05:07,200 --> 00:05:12,240
捞到这里头 继续滚

105
00:05:12,240 --> 00:05:16,000
换成那边 关火

106
00:05:16,000 --> 00:05:17,600

107
00:05:17,600 --> 00:05:19,240
你看更白了

108
00:05:19,240 --> 00:05:22,360
这汤白了这火稍微小一点

109
00:05:22,360 --> 00:05:25,440
因为火大就是要翻这个汤要白

110
00:05:25,440 --> 00:05:28,200
白了以后就不要再大了

111
00:05:28,200 --> 00:05:32,360
就时候二次调味 盐

112
00:05:32,360 --> 00:05:34,920
还搁什么啊 什么都不搁了

113
00:05:34,920 --> 00:05:38,560
味精都不搁 你看一会你喝吧

114
00:05:38,560 --> 00:05:40,400

115
00:05:45,480 --> 00:05:49,440
这个萝卜丝到什么程度 入口要即化

116
00:05:49,440 --> 00:05:51,440

117
00:05:51,440 --> 00:05:52,680
大爷先吃了

118
00:05:52,680 --> 00:05:55,440

119
00:05:55,440 --> 00:05:57,680
盛到砂锅里头

120
00:05:57,680 --> 00:06:04,760

121
00:06:04,760 --> 00:06:07,240
葱姜拣干净

122
00:06:07,240 --> 00:06:11,360
香菜 真好

123
00:06:11,360 --> 00:06:14,920
展示一下成品

124
00:06:14,920 --> 00:06:16,000
你瞧瞧

125
00:06:16,000 --> 00:06:17,800
大爷真稳当

126
00:06:17,800 --> 00:06:20,880

127
00:06:20,880 --> 00:00:02,000


```

**Comment by Petitcolza** [comment]
认领

**Comment by Petitcolza** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【國宴大師•鯽魚湯】鯽魚湯更奶白更鮮的秘訣！大爺手把手教做家常版鯽魚湯，營養滋補超鮮美！520還不進來吃“狗糧”嗎？！|老飯骨
State Banquet Master Chef – “Crucian carp soup” The secret of more milk-white and fresher soup.
简介
小友們好，今天是520，大爺大媽為大家帶來一道家常版的蘿蔔絲鯽魚湯！
Hello friends, Today is 20th May, Da Ye and Da Ma bring us a homestyle Crucian Carp and Shredded radish Soup!
從處理魚開始，大爺手把手教大家，這樣做出的鯽魚湯才不會腥。
From the beginning of the processing of fish, Da Ye will show us step-by-step, so that the soup without any gamey taste.
視頻里面的“大油”就是豬油的意思，用豬油煎出來這湯還白！
The word "Large oil" in the video means lard, Soup with lard will be whiter.
喜歡吃魚的小友可以把鱖魚片成片兒，在鍋裏燙一下。
Our friends who like to eat fish could slice the mandarin fish and put it in boiling water and take it out quickly.
要想知道這鯽魚湯更奶白更鮮的秘訣，小友們可要把視頻看仔細咯，都是細節！
If you want to know the secret of more milk-white and more fresh soup, our friend have to watch this vedio carefully, the details!
520的恩愛大家感受到了嗎，暖暖的奶白鯽魚湯，快學起來做給妳的那個TA！
Loving from happy couple in 520(20th Mai), could you feel it?  Warm milk-white Crucian Carp Soup, learn it quickly for the one!
字幕
1
00:00:00,680 --> 00:00:03,280
你看看这样一刮就下来了
You see you can scrape it off like this

2
00:00:03,280 --> 00:00:04,440
真白
It's so white
3
00:00:04,440 --> 00:00:06,240

4
00:00:06,240 --> 00:00:07,640
萝卜丝鲫鱼汤
Crucian Carp and Shredded Radish Soup
5
00:00:07,640 --> 00:00:10,120

6
00:00:10,120 --> 00:00:13,280
你看我打鳞的时候也没打的那么干净
You see I didn't shave the scales so clean
7
00:00:13,280 --> 00:00:15,440
为什么 还有个小处理
Why? Because there is another step to do
8
00:00:15,440 --> 00:00:18,240
这鱼上边有很多黑膜
Many black membranes on the skin of the fish
9
00:00:18,240 --> 00:00:21,440
熬出这汤是灰的 咱们处理一下
The fish soup cook this way will be grey, so we will handle it
10
00:00:21,440 --> 00:00:24,360
开开的水 小窍门
Tip: with boiling water
11
00:00:24,360 --> 00:00:25,480
先烫鱼头
Scald it from the head
12
00:00:25,480 --> 00:00:28,120

13
00:00:28,120 --> 00:00:29,960
再烫鱼尾
then the tail
14
00:00:29,960 --> 00:00:33,000
你看一烫它就变色 发白了吧
You see it turns white after scald it

15
00:00:33,000 --> 00:00:34,360
 翻一身儿
turn it over
16
00:00:35,000 --> 00:00:38,600

17
00:00:38,600 --> 00:00:39,840
再烫这头
scald this side in same way
18
00:00:39,840 --> 00:00:42,040

19
00:00:42,040 --> 00:00:44,360
今天这好 现买的活鱼
Today we prepared live fish
20
00:00:44,360 --> 00:00:48,600
刚才蹦蹦蹦直跳呢 马上冲凉
It was jumping up and down a few minutes ago; Wash it immediately with cold water
21
00:00:48,600 --> 00:00:50,560

22
00:00:52,160 --> 00:00:55,440
你看看 这样一刮就下来了
You see it is easy to Scrape off the scales
23
00:00:55,440 --> 00:00:57,360
因为要赶快冲凉
It must be washed at once
24
00:00:57,360 --> 00:00:59,640
因为这鱼你烫大了也不行
Because too much scald won't work either
25
00:00:59,640 --> 00:01:01,040
烫大了这皮破了
Too many scalds will break its skin
26
00:01:01,040 --> 00:01:05,640
所以瞬间要给它冲凉
So shower it immediately
27
00:01:05,640 --> 00:01:09,480
说这鱼的汤有土腥味是哪儿啊
which part cause the soup with gamey tasty?
28
00:01:09,480 --> 00:01:11,880
发苦 土腥味大 你看这黑膜
It is Here, bitter, gamey tasty, look at these black membrane
29
00:01:11,880 --> 00:01:14,240
这得拿手都给处理干净
All of them should be removed by hand
30
00:01:14,240 --> 00:01:16,600
更重要的一点 这个鱼鳍
More importantly, the fin
31
00:01:16,600 --> 00:01:20,960
划水 尾边的摆水  前面的鳍
All of fins
32
00:01:20,960 --> 00:01:23,560
都得给弄干净了 为什么呢
Should be cleaned up, why?
33
00:01:23,560 --> 00:01:26,880
不弄干净它腥啊 上边（有）粘液
Because it is fishy, there are many mucus on it
34
00:01:26,880 --> 00:01:30,480
你看照这边 看干净吧
Look at this side, how clean!
35
00:01:30,480 --> 00:01:31,880
颜色也好看了
The color looks better, too
36
00:01:31,880 --> 00:01:35,480
那会儿煲出那汤来 倍儿白
The soup what we cook later will be quite white
37
00:01:35,480 --> 00:01:37,360
两条
 two fishes
38
00:01:37,360 --> 00:01:40,000
你看我们这个辅料是什么
Look at our other ingredient
39
00:01:40,000 --> 00:01:43,520
海米用开水泡上 先洗干净后泡
Clean some dried shrimps then soak them in boiling water
40
00:01:43,520 --> 00:01:45,480
这水要要的
Keep the water
41
00:01:45,480 --> 00:01:50,960
葱 姜 香菜 处理的还行吧
Onion, ginger and cilantro, not bad, right?
42
00:01:50,960 --> 00:01:52,800
这炖出这汤倍儿白
The soup will be particularly white
43
00:01:52,800 --> 00:01:55,720
萝卜丝鲫鱼汤
Crucian Carp and Shredded Radish Soup
44
00:01:55,720 --> 00:01:58,600
这也是淮扬菜的老菜
It is also a typical dishes of Huaiyang cuisine 
45
00:01:58,600 --> 00:01:59,560

46
00:02:00,280 --> 00:02:01,800
这是淮扬菜啊
Is this Huaiyang cuisine?
47
00:02:01,800 --> 00:02:04,800
瞧瞧 这大爷
Look at ours Da Ye
48
00:02:04,800 --> 00:02:06,440
点火
turn on the stove
49
00:02:06,440 --> 00:02:07,360

50
00:02:07,360 --> 00:02:10,080
这个锅一定要烧热
Until the wok is hot
51
00:02:10,080 --> 00:02:13,440
我们常说的叫热锅凉油
This is what we often say that heat the empty wok and then add oil
52
00:02:13,440 --> 00:02:15,600
但是鲫鱼汤要好
But if you want the soup to be tasty
53
00:02:15,600 --> 00:02:20,240
原本的最传统的搁点大油
The most traditional method should have used lard
54
00:02:20,240 --> 00:02:22,120
出来这汤还白的
that soup should be more white
55
00:02:22,120 --> 00:02:23,600

56
00:02:23,600 --> 00:02:25,960
油温得热一点儿
The oil temperature should be a little higher
57
00:02:25,960 --> 00:02:27,680
大妈稍微远一点
Da ma goes a little bit farther

58
00:02:27,680 --> 00:02:29,320

59
00:02:32,680 --> 00:02:34,680
这个鱼不用腌
The fish does not need to be marinate
60
00:02:34,680 --> 00:02:36,960

61
00:02:36,960 --> 00:02:40,640
不用动它啊 别动它一动皮破了
Don't touch it, or its skin will break
62
00:02:40,640 --> 00:02:44,640
没搁多少油就是煎
Do not put too much oil in it, just fry it

63
00:02:44,640 --> 00:02:44,840

64
00:02:44,840 --> 00:02:48,600
翻身了 再翻一下
turn it over, Turn it again
65
00:02:48,600 --> 00:02:53,320
皮也没破吧 前期处理的好
The skin is not broken, because we did a good preparation
66
00:02:53,320 --> 00:02:57,600
这时候我们要把葱姜随手就放进去了
Now, add the spring Onions and ginger
67
00:02:57,600 --> 00:02:59,480
就可以了
That's it
68
00:02:59,480 --> 00:03:05,880
放水（热水） 大火
Put water (hot water) in it, high heat
69
00:03:05,880 --> 00:03:09,840
黄酒 海米
Huangjiu rice wine, small dried Shrimps
70
00:03:09,840 --> 00:03:12,440
这得炖多长时间
How long time does it need to be stewed?
71
00:03:12,440 --> 00:03:15,480
应该说是在一刻钟到二十分钟
It should be stew between 15-20 mins
72
00:03:15,480 --> 00:03:20,960
说去腥的方法很多 搁上几粒花椒
Speak of there are a lot of ways to remove fishy smell, put a few Sichuan peppercorn
73
00:03:20,960 --> 00:03:25,080
开了 这个就用大火煮 大火熬鱼炖鱼
It’s boiling. It should be cooked with high heat for braising fish, stewing fish
74
00:03:25,080 --> 00:03:28,360
为什么要把那汤给没过鱼了
Why is soup over the fish?
75
00:03:28,360 --> 00:03:30,240
它得炖一会儿
It has to be stewed for a while
76
00:03:30,240 --> 00:03:33,920
把它移到这火 同时进行
Move it to this side stove, cooking together on both side
77
00:03:35,240 --> 00:03:37,640
胡椒 白胡椒
Pepper, White pepper
78
00:03:37,640 --> 00:03:39,280
盐待会再放
Salt, put it in later
79
00:03:39,280 --> 00:03:42,080
盐早放它这个鱼就不爱烂
Putting salt early could make fish rubbery
80
00:03:42,080 --> 00:03:47,560
出白汤的就慢 行 这个先慢慢炖着
Could make soup turn to white slower. Ok. Let it stew slowly
81
00:03:47,560 --> 00:03:51,000
锅热了 这油不用要太多
The wok is hot. don’t need too much oil
82
00:03:51,000 --> 00:03:55,840
炒萝卜丝 去萝卜的臭味
Fry shredded radish remove radish smelly
83
00:03:55,840 --> 00:03:57,720
你看再照照那个
You film that again
84
00:03:57,720 --> 00:04:01,040
那有点要白吧 白了已经起白了
It turns to be white. It was white already
85
00:04:01,040 --> 00:04:03,720
一放萝卜还白
It will be whiter after put radish in
86
00:04:03,720 --> 00:04:07,560
（萝卜丝）就是煸煸 花椒煸出味来就行
(shredded radish) Just fry, fry to the smell of Sichuan peppercorn come out
87
00:04:07,560 --> 00:04:10,560

88
00:04:10,560 --> 00:04:12,840
搁点水
Put in some water
89
00:04:12,840 --> 00:04:13,160

90
00:04:14,960 --> 00:04:19,760
这个还是要这样大的火
Cooking still with this high heat
91
00:04:19,760 --> 00:04:22,800
这还要处理一下 把这浮沫给打出来
This need to be done, scum the bubbles
92
00:04:23,840 --> 00:04:25,960
一会它一开锅还有沫子呢
Later, there still have more bubbles when it boils
93
00:04:25,960 --> 00:04:27,480
那沫子是油沫
The bubbles are bubbles of oil.
94
00:04:27,480 --> 00:04:32,200
把那油给打干净 这萝卜丝就没有臭味了
Scum all the bubbles, then there’ll not have peculiar smell of radish
95
00:04:32,200 --> 00:04:34,720
我做这个就特别拿手
I’m very good at making this soup
96
00:04:34,720 --> 00:04:38,960
原来在饭店的时候 有些老领导
When I worked at restaurant, there were some old leaders
97
00:04:38,960 --> 00:04:42,720
就爱吃大爷这个萝卜丝鲫鱼汤
especially love to eat Daye’s Crucian Carp and Shredded Radish Soup
98
00:04:42,720 --> 00:04:45,240
一种方式就是喝汤
One of the way to eat is only eat the soup
99
00:04:45,240 --> 00:04:48,640
再一种方式在这也跟网友说一声
Another way to eat, I’d like to say to netizens
100
00:04:48,640 --> 00:04:53,400
想吃鱼 别吃鲫鱼 买条鳜鱼
Want to eat fish, don’t eat crucian, buy a mandarin fish
101
00:04:53,400 --> 00:04:57,120
鳜鱼片成片 在这锅里边一烫
Mandarin fish, cut into slices, put it in boiling water and take it out quickly
102
00:04:57,120 --> 00:05:02,400
鳜鱼的鱼片 汤必须是鲫鱼的
Making fillet fish with mandarin fish, making fish soup must with crucian
103
00:05:02,400 --> 00:05:07,200
萝卜丝已经好了 咱把它捞出来
Shredded Radish is ready, let’s take them out
104
00:05:07,200 --> 00:05:12,240
捞到这里头 继续滚
Take them into here, keep boiling
105
00:05:12,240 --> 00:05:16,000
换成那边 关火
Move to that side, turn off the heat
106
00:05:16,000 --> 00:05:17,600

107
00:05:17,600 --> 00:05:19,240
你看更白了
You see it’s more white
108
00:05:19,240 --> 00:05:22,360
这汤白了这火稍微小一点
The soup is white, turn the heat down a little
109
00:05:22,360 --> 00:05:25,440
因为火大就是要翻这个汤要白
Because high heat is for soup boil to white
110
00:05:25,440 --> 00:05:28,200
白了以后就不要再大了
When it turns to white, no need to use high heat
111
00:05:28,200 --> 00:05:32,360
就时候二次调味 盐
Now second time to seasoning, salt
112
00:05:32,360 --> 00:05:34,920
还搁什么啊 什么都不搁了
Anything else to put in? Nothing
113
00:05:34,920 --> 00:05:38,560
味精都不搁 你看一会你喝吧
No MSG even, you just taste it later
114
00:05:38,560 --> 00:05:40,400

115
00:05:45,480 --> 00:05:49,440
这个萝卜丝到什么程度 入口要即化
The shredded radish will be cooked till what degree? Till it could melt in your mouth
116
00:05:49,440 --> 00:05:51,440

117
00:05:51,440 --> 00:05:52,680
大爷先吃了
Da ye eat it first
118
00:05:52,680 --> 00:05:55,440

119
00:05:55,440 --> 00:05:57,680
盛到砂锅里头
Put it into crock pot
120
00:05:57,680 --> 00:06:04,760

121
00:06:04,760 --> 00:06:07,240
葱姜拣干净
Pick onion and ginger out
122
00:06:07,240 --> 00:06:11,360
香菜 真好
Coriander, very good
123
00:06:11,360 --> 00:06:14,920
展示一下成品
Show the dish that has been done
124
00:06:14,920 --> 00:06:16,000
你瞧瞧
You see
125
00:06:16,000 --> 00:06:17,800
大爷真稳当
Da ye is so steady
126
00:06:17,800 --> 00:06:20,880

127
00:06:20,880 --> 00:00:02,000
