### ISSUE TITLE
【美食作家王刚】凉拌绿豆芽 - https://youtu.be/AzsbP0Y5KZ4

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1075]
**视频链接**：https://youtu.be/AzsbP0Y5KZ4

视频时长2:52，预计发布时间为北京时间5月25日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“凉拌绿豆芽”的费时做法，慢工出细活，口感爽脆味道很赞

简介
同学们好，今天和大家分享一道夏日好菜“凉拌绿豆芽”，由于绿豆芽头尾略有苦涩味，所以这道菜的最佳做法就是将头尾去除，而去除豆芽头尾只能一根一根来掐掉，导致了这是一道特别费时费工的菜品，非常考验大家的耐心，不建议没有耐心的朋友来尝试这道菜。

本期菜品【凉拌豆芽】
【主料】
绿豆芽（1000克）
【辅料】
干辣椒（几个）
大蒜（30克）
【调味料】
白糖（约1克）
蚝油（2克）
生抽酱油（3克）
白醋（约2克）
食用盐（约5克）
植物油（适量）

字幕
0:00:00.240,0:00:01.240
哈喽大家好 我是王刚

0:00:01.240,0:00:02.980
本期视频我给大家分享

0:00:03.180,0:00:04.540
凉拌绿豆芽

0:00:04.760,0:00:06.700
首先我们准备绿豆芽1000克

0:00:06.891,0:00:08.847
然后将豆芽的两头掐掉备用

0:00:09.119,0:00:11.075
豆芽的头尾都会有一股涩味

0:00:11.295,0:00:13.678
去掉头尾的豆芽身价可以上升数倍

0:00:13.963,0:00:17.720
这一步的目的不仅去除了苦涩味而且还留下了豆芽的爽脆

0:00:19.507,0:00:22.694
1000克绿豆芽经过掐头去尾之后只剩下500克左右

0:00:23.264,0:00:25.362
清理干净之后加入清水清洗干净

0:00:26.373,0:00:29.196
同学们处理这个菜的时候必须赋予足够的耐心

0:00:29.326,0:00:31.774
处理2斤绿豆芽大约需要40分钟左右

0:00:32.564,0:00:34.417
清洗干净之后捞出控干水分

0:00:34.663,0:00:35.945
下一步开始准备辅料

0:00:36.424,0:00:39.624
准备几个干辣椒清洗干净之后用剪刀剪成辣椒丝备用

0:00:39.909,0:00:41.437
不能吃辣的同学可以不加

0:00:56.308,0:00:57.940
准备大蒜30克剁碎备用

0:00:57.953,0:00:59.935
同学们大蒜应该剁得越细越好

0:00:59.999,0:01:02.474
这样在凉拌的时候才能够吸附在豆芽上面

0:01:03.950,0:01:05.012
下一步开始调味

0:01:05.272,0:01:06.645
碗中加入适量的白糖（约1克）

0:01:06.904,0:01:07.966
加入蚝油2克

0:01:08.743,0:01:10.038
加入生抽酱油3克

0:01:11.411,0:01:12.629
加入少许白醋（约2克）

0:01:13.873,0:01:15.518
调好味之后搅拌均匀即可

0:01:16.450,0:01:17.512
下一步开始制作

0:01:17.875,0:01:19.909
首先我们在锅中加入适量的清水

0:01:23.173,0:01:25.349
开大火烧开之后加入食用盐2大勺（约5克）

0:01:29.417,0:01:30.764
再加入适量的植物油

0:01:35.090,0:01:37.668
然后将处理好的绿豆芽下锅焯水煮至断生（水开2秒即可）

0:01:41.606,0:01:43.264
豆芽断生之后倒出控水

0:01:44.922,0:01:46.528
然后放入凉开水中透凉

0:01:46.735,0:01:48.613
这一步的目的是让豆芽保持脆度

0:01:50.854,0:01:52.396
然后我们再次把锅烧热

0:01:53.173,0:01:55.401
锅烧热之后加入适量的油烧至6成热

0:01:56.178,0:01:59.702
油温6成热之后倒入装辣椒丝的碗中把辣椒炝香

0:02:01.036,0:02:03.005
然后再倒入蒜蓉汁中搅拌均匀

0:02:07.124,0:02:08.976
豆芽透凉之后倒出沥干水分

0:02:10.582,0:02:13.536
最后将调好的料汁倒入盆中搅拌均匀即可装盘

0:02:20.340,0:02:22.700
一道口感爽脆的凉拌绿豆芽就制作完成

0:02:31.380,0:02:51.320
下面开始技术总结
第一，去除豆芽头尾的目的是减少涩味，嫌麻烦的同学可以忽略
第二，豆芽下锅焯水不能煮太久否则不脆
第三，焯水的时候可以多放一下盐，后期凉拌的时候可以不加盐
第四，此菜原料虽成本不高，但极具考验每一位美食家的耐心
凉拌豆芽的技术总结完毕


```

**Comment by Koi111** [comment]
认领

**Comment by Koi111** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“凉拌绿豆芽”的费时做法，慢工出细活，口感爽脆味道很赞
Chef Wang teaches you: Bean Sprouts Salad, time-consuming recipe, crunchy texture & amazing taste

简介
同学们好，今天和大家分享一道夏日好菜“凉拌绿豆芽”，由于绿豆芽头尾略有苦涩味，所以这道菜的最佳做法就是将头尾去除，而去除豆芽头尾只能一根一根来掐掉，导致了这是一道特别费时费工的菜品，非常考验大家的耐心，不建议没有耐心的朋友来尝试这道菜。
Hi guys, I’m going to share a recipe of Bean Sprouts Salad today, a wonderful dish for summer. Since the upper ends and the root parts are a bit bitter and astringent, the best way to make this dish is to remove both ends. However, the step to remove both ends has to be done one by one, which causes the dish needs a lot of time and energy. This would require patience from you guys, I don’t recommend friends who don’t have much patience to try this dish.

本期菜品【凉拌豆芽】

【主料】
Main ingredient
绿豆芽（1000克）
bean sprouts (1000g)
【辅料】
Other ingredients
干辣椒（几个）
dried chili pepper (a few)
大蒜（30克）
garlic (30g)
【调味料】
Seasoning
白糖（约1克）
white sugar (about 1g)
蚝油（2克）
oyster sauce (2g)
生抽酱油（3克）
light soy sauce (3g)
白醋（约2克）
white vinegar (about 2g)
食用盐（约5克）
salt (about 5g)
植物油（适量）
vegetable oil (appropriate amount)

字幕
0:00:00.240,0:00:01.240
哈喽大家好 我是王刚
Hello guys, I am Wang Gang

0:00:01.240,0:00:02.980
本期视频我给大家分享
For today’s video, I am going to share the recipe of

0:00:03.180,0:00:04.540
凉拌绿豆芽
Bean Sprouts Salad

0:00:04.760,0:00:06.700
首先我们准备绿豆芽1000克
First, let’s prepare 1000g of bean sprouts

0:00:06.891,0:00:08.847
然后将豆芽的两头掐掉备用
Then remove both ends by pinching it

0:00:09.119,0:00:11.075
豆芽的头尾都会有一股涩味
The upper ends and the roots are a bit astringent

0:00:11.295,0:00:13.678
去掉头尾的豆芽身价可以上升数倍
Bean sprouts without both ends have higher price

0:00:13.963,0:00:17.720
这一步的目的不仅去除了苦涩味而且还留下了豆芽的爽脆
This step can remove the bitterness and remain the crunchy texture of bean sprouts

0:00:19.507,0:00:22.694
1000克绿豆芽经过掐头去尾之后只剩下500克左右
After removing both ends, there is 500g of bean sprouts left

0:00:23.264,0:00:25.362
清理干净之后加入清水清洗干净
Add some water to rinse the bean sprouts

0:00:26.373,0:00:29.196
同学们处理这个菜的时候必须赋予足够的耐心
Please have enough patience while preparing this dish

0:00:29.326,0:00:31.774
处理2斤绿豆芽大约需要40分钟左右
Preparing 2 jin (1kg) of bean sprouts requires around 40 min

0:00:32.564,0:00:34.417
清洗干净之后捞出控干水分
Drain out the water after rinsing it

0:00:34.663,0:00:35.945
下一步开始准备辅料
Next step, prepare the other ingredients

0:00:36.424,0:00:39.624
准备几个干辣椒清洗干净之后用剪刀剪成辣椒丝备用
Rinse a few dried chili peppers and cut them into strips with scissors

0:00:39.909,0:00:41.437
不能吃辣的同学可以不加
You can exclude them if you don’t enjoy spiciness

0:00:56.308,0:00:57.940
准备大蒜30克剁碎备用
Mince 30g of garlic and set it aside

0:00:57.953,0:00:59.935
同学们大蒜应该剁得越细越好
The garlic pieces should be as small as possible

0:00:59.999,0:01:02.474
这样在凉拌的时候才能够吸附在豆芽上面
so that it would coat on the bean sprouts easily

0:01:03.950,0:01:05.012
下一步开始调味
Then, let’s prepare the seasoning

0:01:05.272,0:01:06.645
碗中加入适量的白糖（约1克）
Add around 1g of white sugar into the bowl

0:01:06.904,0:01:07.966
加入蚝油2克
Then add 2g of oyster sauce

0:01:08.743,0:01:10.038
加入生抽酱油3克
Next is 3g of light soy sauce

0:01:11.411,0:01:12.629
加入少许白醋（约2克）
Add 2g of white vinegar

0:01:13.873,0:01:15.518
调好味之后搅拌均匀即可
Stir well after you finished adding the seasoning

0:01:16.450,0:01:17.512
下一步开始制作
Next step, start cooking

0:01:17.875,0:01:19.909
首先我们在锅中加入适量的清水
Firstly, add a suitable amount of water into the wok

0:01:23.173,0:01:25.349
开大火烧开之后加入食用盐2大勺（约5克）
Boil it with high heat and add 2 spoonsful of salt (around 5g)

0:01:29.417,0:01:30.764
再加入适量的植物油
Then add some vegetable oil

0:01:35.090,0:01:37.668
然后将处理好的绿豆芽下锅焯水煮至断生（水开2秒即可）
Next, blanch the prepared bean sprouts until they are cooked (2 seconds after the water boils)

0:01:41.606,0:01:43.264
豆芽断生之后倒出控水
Drain the excess water after the bean sprouts are cooked

0:01:44.922,0:01:46.528
然后放入凉开水中透凉
Then soak them in cold water to cool

0:01:46.735,0:01:48.613
这一步的目的是让豆芽保持脆度
The purpose of this is to remain the crunchiness of the bean sprouts

0:01:50.854,0:01:52.396
然后我们再次把锅烧热
Then, heat up the wok again

0:01:53.173,0:01:55.401
锅烧热之后加入适量的油烧至6成热
Add some oil and heat it until 180°C

0:01:56.178,0:01:59.702
油温6成热之后倒入装辣椒丝的碗中把辣椒炝香
Add the oil into the bowl with the dried chilli peppers to bring out the aroma

0:02:01.036,0:02:03.005
然后再倒入蒜蓉汁中搅拌均匀
Then add it into the minced garlic sauce and mix well

0:02:07.124,0:02:08.976
豆芽透凉之后倒出沥干水分
Once the bean sprouts are cool, drain off the water

0:02:10.582,0:02:13.536
最后将调好的料汁倒入盆中搅拌均匀即可装盘
Lastly, pour the sauce and mix it with the bean sprouts then you can serve it

0:02:20.340,0:02:22.700
一道口感爽脆的凉拌绿豆芽就制作完成
A plate of bean sprouts salad with crunchy texture is served

0:02:31.380,0:02:51.320
下面开始技术总结
Below is the technical summary for today’s video:
第一，去除豆芽头尾的目的是减少涩味，嫌麻烦的同学可以忽略
First, removing both ends of bean sprouts is to reduce the astringent taste, you can ignore this if you think it’s too troublesome.
第二，豆芽下锅焯水不能煮太久否则不脆
Secondly, don’t blanch the bean sprouts for too long or they will lose the crunchiness.
第三，焯水的时候可以多放一下盐，后期凉拌的时候可以不加盐
Thirdly, you can add more salt when you are blanching them, this way you don’t need to add salt in the sauce.
第四，此菜原料虽成本不高，但极具考验每一位美食家的耐心
Fourthly, the cost for this dish isn’t high, but it requires a lot of patience.
凉拌豆芽的技术总结完毕
This is it for the technical summary.
