### ISSUE TITLE
[馋小漆] 懒人排骨 - https://www.youtube.com/watch?v=J0FyL0xI8a0

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1076]
**视频链接**：https://www.youtube.com/watch?v=J0FyL0xI8a0

# 请翻译以下全部内容

```
字幕
0:00:00.250,0:00:03.225
这里刀的这个尖角

0:00:03.675,0:00:08.711
这样子稍微用点力把这些膜撕破皮

0:00:08.711,0:00:12.713
然后用手这样子慢慢这样子刮

0:00:13.255,0:00:13.744
好

0:00:13.903,0:00:14.893
才撕它得下来

0:00:16.078,0:00:17.751
嗨 大家好 我是漆二娃

0:00:17.947,0:00:20.097
今天我要做一个懒人排骨

0:00:20.342,0:00:23.115
现在我要把这层油给它撕掉

0:00:30.824,0:00:34.331
慢点 不要慌 等会撕不完

0:00:34.331,0:00:35.809
好大一层油哦这个

0:00:37.263,0:00:38.289
是这样子撕的嘎四伯爷

0:00:38.362,0:00:40.671
嗯 对对对看嘛 那块油

0:00:41.832,0:00:44.459
哦哟喂  这块油起码都有2两

0:00:45.009,0:00:47.733
这样子就全部可以看到那瘦的了撒

0:00:48.259,0:00:50.995
膜膜一蒙起你就看不到那瘦的

0:00:51.496,0:00:53.091
好安逸这 可以了嘎四伯爷

0:00:53.105,0:00:54.157
可以了可以了

0:00:54.185,0:00:54.883
我把它洗哈

0:00:58.314,0:01:00.210
看嘛 这点油拿来有什么用嘛

0:01:00.799,0:01:02.063
把它切点来喂狗

0:01:07.737,0:01:09.219
四伯爷这个从哪儿下刀哦

0:01:09.553,0:01:10.584
咋个下刀

0:01:10.933,0:01:13.109
你把那个肉留不留在上面吗

0:01:13.109,0:01:14.896
肉不留在上面就拼下来撒

0:01:15.779,0:01:17.617
要留在上面 要不你来砍嘛

0:01:17.617,0:01:19.171
你才砍得来排骨 教哈我

0:01:19.658,0:01:22.288
好嘛好嘛 这个很简单的

0:01:22.302,0:01:25.158
我教你一回看你下次你搞得会不

0:01:32.444,0:01:33.476
菜板有点高嘎

0:01:33.781,0:01:35.423
那不是咋个安

0:01:36.723,0:01:37.893
哦 这样子

0:01:37.893,0:01:38.416
哦 晓得了

0:01:43.022,0:01:45.521
专业的是不一样嘎 经常宰到排骨得

0:01:46.211,0:01:51.739
哦 好简单哦这样子一哈都砍出来了

0:01:55.510,0:01:56.331
好 就这样子

0:01:56.905,0:02:00.339
要得 懒人排骨的嘛就懒点

0:02:00.339,0:02:01.264
整长节点

0:02:01.540,0:02:02.085
要得

0:02:03.603,0:02:05.695
先切点柠檬

0:02:07.177,0:02:07.881
切片

0:02:09.822,0:02:11.187
你要泡水喝不嘛四伯爷

0:02:11.245,0:02:11.674
安

0:02:12.001,0:02:12.742
泡水喝不

0:02:13.476,0:02:13.781
喝过安

0:02:13.781,0:02:15.016
你要不要尝一哈四伯爷

0:02:15.292,0:02:15.873
喝过

0:02:16.767,0:02:17.319
尝一坨嘛

0:02:18.467,0:02:19.150
你尝 

0:02:19.273,0:02:23.348
那会儿我都整来怎么吃的呢 整来腌白糖

0:02:27.838,0:02:28.674
啊

0:02:29.306,0:02:31.522
哎呀 好酸哦

0:02:31.921,0:02:33.817
挑战无表情吃柠檬

0:02:34.275,0:02:36.236
不吃不吃 吃不得

0:02:37.057,0:02:38.438
只有腌白糖吃 好吃

0:02:39.077,0:02:40.116
现在切点姜

0:02:43.988,0:02:45.041
 整几根小葱

0:02:50.446,0:02:50.955
可乐

0:02:54.515,0:02:55.045
好了

0:02:55.583,0:02:57.370
然后加点盐巴

0:02:57.384,0:02:58.133
 一会就跟开水一样 是嘛

0:02:58.737,0:02:59.197
哇

0:02:59.404,0:02:59.857
 该是嘎

0:02:59.857,0:03:01.940
跟它深水炸弹样嘎

0:03:03.256,0:03:04.713
再加点白糖

0:03:05.999,0:03:06.747
糖多一点

0:03:07.666,0:03:08.562
好可以了

0:03:09.349,0:03:10.167
这个不要撒

0:03:10.432,0:03:11.055
不要

0:03:11.912,0:03:12.637
 好可以了

0:03:15.535,0:03:18.854
首先在锅中加入适量的清水

0:03:19.446,0:03:21.316
再把排骨放下去

0:03:22.142,0:03:25.485
我感觉这个排骨比我的排骨都大

0:03:25.882,0:03:27.534
然后加入料酒

0:03:29.380,0:03:30.775
开大火烧开

0:03:33.759,0:03:34.592
去浮沫

0:03:40.202,0:03:42.547
再把排骨捞出来

0:03:46.490,0:03:48.297
下面把锅烧热

0:03:48.757,0:03:52.333
加入准备好的可乐倒入锅中

0:03:54.328,0:03:56.629
再放入焯好水的排骨

0:03:57.397,0:04:00.459
再加两颗八角两片香叶

0:04:06.778,0:04:08.889
烧开之后又去浮沫

0:04:12.169,0:04:15.512
因为伯爷牙齿不好需要烧很久

0:04:16.174,0:04:17.966
所以再加点可乐

0:04:22.727,0:04:24.892
开小火烧半个小时

0:04:27.869,0:04:31.235
再把柠檬 姜片 小葱夹出来

0:04:33.735,0:04:35.216
再开大火收汁儿

0:04:35.769,0:04:41.807
这懒人排骨真的很简单就是烧的时间会比较长一点

0:04:42.485,0:04:43.615
如果你牙口好

0:04:44.137,0:04:46.996
烧个ten minutes也是可以的

0:04:53.252,0:04:53.930
移过来点嘛

0:04:54.164,0:04:54.616
要得啊

0:04:54.663,0:04:55.792
吃嘛 夹来吃撒

0:04:55.792,0:04:57.460
夹来吃四伯爷 伯娘

0:04:57.460,0:04:57.904
好

0:04:57.904,0:04:59.696
这次咬得动 肯定很耙活

0:05:00.670,0:05:01.503
脱骨的了

0:05:01.503,0:05:02.508
肉是肉 骨头是骨头

0:05:02.508,0:05:04.480
真的这回可能是整耙了安

0:05:05.251,0:05:06.139
这个骨头不要了

0:05:09.061,0:05:09.404
哎呀

0:05:10.564,0:05:11.609
我夹一坨大的

0:05:12.029,0:05:12.746
好耙

0:05:13.774,0:05:14.709
这伯爷咬得动

0:05:15.037,0:05:15.863
一抿就烂了

0:05:16.283,0:05:16.610
是啊

0:05:19.127,0:05:20.218
因为炖了很久

0:05:20.997,0:05:21.971
嗯可以

0:05:24.293,0:05:27.744
这中午的懒人排骨硬是拿给你整耙了

0:05:29.533,0:05:32.733
整来跟你师父的相差不远了

0:05:33.756,0:05:34.572
相差不远了

0:05:34.572,0:05:34.948
嗯

0:05:35.090,0:05:36.101
打得到好多分嘛

0:05:36.515,0:05:37.681
打得到98分

0:05:38.264,0:05:39.391
98分啊

0:05:39.624,0:05:41.541
100分你是达不到的 

0:05:44.235,0:05:45.816
我好开心哦

0:05:45.984,0:05:47.435
我要上天了

0:05:47.551,0:05:49.753
你不要太骄傲了撒你

0:05:51.917,0:05:55.893
给你们说了这个懒人排骨只有懒人才做的出来

0:05:57.681,0:05:58.627
还可以

0:05:59.041,0:05:59.391
可以

0:05:59.468,0:06:00.155
 好吃

0:06:00.570,0:06:02.823
这中午的这个懒人排骨拿给你整巴适了的

0:06:03.860,0:06:04.779
多吃点四伯爷

0:06:05.336,0:06:06.476
好吃就多吃点

0:06:06.722,0:06:07.629
好嘛好嘛

0:06:08.095,0:06:09.132
我都吃了几坨了

0:06:10.349,0:06:12.253
这次你做的这个懒人排骨安

0:06:13.186,0:06:14.507
我还是夸你一哈

0:06:15.142,0:06:17.875
不愧是懒人做的懒人排骨

0:06:18.199,0:06:20.129
这是在夸我呢还是在

0:06:22.279,0:06:23.704
懒人做的排骨就

0:06:23.704,0:06:24.326
在夸你

0:06:24.987,0:06:28.005
我怎么听出了其他的意思呢四伯爷

0:06:28.082,0:06:33.367
不是的 懒人做的排骨今中午就不造假了

0:06:34.611,0:06:36.761
四伯爷还在强调懒人做的排骨

0:06:37.279,0:06:38.782
懒人做的排骨就可以

0:06:38.873,0:06:43.899
嗯 开心 今天我觉得这个懒人排骨做的还可以

0:06:44.119,0:06:47.810
颜色啊 各方面啊 味道那些啊

0:06:47.979,0:06:48.924
都还不错

0:06:49.365,0:06:52.239
懒人排骨懒人做的他就要用心点晓得不嘛

0:06:52.239,0:06:53.471
给我自己比一个

0:06:54.585,0:06:55.233
GOOD

0:06:57.513,0:07:00.362
这个菜做得好不是因为我是懒人

0:07:00.362,0:07:01.450
是我真的做得好

0:07:02.914,0:07:05.103
这个勤快人也一定会做得好的

0:07:05.505,0:07:07.253
然后本期视频就到这里了哟

0:07:07.487,0:07:09.728
拜拜

0:07:10.906,0:07:12.590
放到等会吃饭的时候一起吃
```

**Comment by immoonancient** [comment]
@Katvava 请前来认领

**Comment by Katvava** [comment]
认领

**Comment by Katvava** [comment]
字幕
0:00:00.250,0:00:03.225
这里刀的这个尖角
Here is the sharp cutting edge of the knife

0:00:03.675,0:00:08.711
这样子稍微用点力把这些膜撕破皮
Just like this, cut the membrane a little bit hard

0:00:08.711,0:00:12.713
然后用手这样子慢慢这样子刮
And then tear it away by your fingers slowly
 
0:00:13.255,0:00:13.744
好
Got it

0:00:13.903,0:00:14.893
才撕它得下来
In this way you can tear it away

0:00:16.078,0:00:17.751
嗨 大家好 我是漆二娃
Hi there, this is Qi Er Wa (Second baby in Qi Family)

0:00:17.947,0:00:20.097
今天我要做一个懒人排骨
Today I will cook a Lazy Man Pork Rib

0:00:20.342,0:00:23.115
现在我要把这层油给它撕掉
Now let me tear the oil tissue away 

0:00:30.824,0:00:34.331
慢点 不要慌 等会撕不完
Take your time, no rush, or you can’t clean it thoroughly 

0:00:34.331,0:00:35.809
好大一层油哦这个
How heavy the oil tissue is here!

0:00:37.263,0:00:38.289
是这样子撕的嘎四伯爷
Am I doing alright? Si Bai Ye

0:00:38.362,0:00:40.671
嗯 对对对看嘛 那块油
Absolutely, you are right, see the oil tissue on your hand

0:00:41.832,0:00:44.459
哦哟喂  这块油起码都有2两
OMG, this pork fat should have at least a weight of 100g

0:00:45.009,0:00:47.733
这样子就全部可以看到那瘦的了撒
Just like this, you can see all the lean pork meat 

0:00:48.259,0:00:50.995
膜膜一蒙起你就看不到那瘦的
You can’t see the lean pork meat if the pork fat covered on it 

0:00:51.496,0:00:53.091
好安逸这 可以了嘎四伯爷
Awesome! We are done, right? Si Bai Ye

0:00:53.105,0:00:54.157
可以了可以了
Sure, sure

0:00:54.185,0:00:54.883
我把它洗哈
Let me clean it a little bit

0:00:58.314,0:01:00.210
看嘛 这点油拿来有什么用嘛
See, how to deal with such a small piece of pork fat?
0:01:00.799,0:01:02.063
把它切点来喂狗
Cut it and feed dog

0:01:07.737,0:01:09.219
四伯爷这个从哪儿下刀哦
Si Bai Ye, Where should I start cutting? 

0:01:09.553,0:01:10.584
咋个下刀
How to start cutting?

0:01:10.933,0:01:13.109
你把那个肉留不留在上面吗
Will you leave the meat on the bone?

0:01:13.109,0:01:14.896
肉不留在上面就拼下来撒
If not, just scrape the meat off bone

0:01:15.779,0:01:17.617
要留在上面 要不你来砍嘛
The meat is on the bone, how about you chop it?

0:01:17.617,0:01:19.171
你才砍得来排骨 教哈我
You are good at chopping pork rib, could you show me how to do it?

0:01:19.658,0:01:22.288
好嘛好嘛 这个很简单的
Alright, alright, this is very easy

0:01:22.302,0:01:25.158
我教你一回看你下次你搞得会不
Let me show you, and see whether you can do it by yourself next time

0:01:32.444,0:01:33.476
菜板有点高嘎
The cutting board is a little bit high, ah?

0:01:33.781,0:01:35.423
那不是咋个安
Yeah, isn’t it?

0:01:36.723,0:01:37.893
哦 这样子
Oh, it’s like this

0:01:37.893,0:01:38.416
哦 晓得了
Oh, I got it

0:01:43.022,0:01:45.521
专业的是不一样嘎 经常宰到排骨得
Professional and impressive, as you chop pork rib a lot

0:01:46.211,0:01:51.739
哦 好简单哦这样子一哈都砍出来了
Oh, looks so easy and you get it done so quickly

0:01:55.510,0:01:56.331
好 就这样子
Alright, just like this is good enough

0:01:56.905,0:02:00.339
要得 懒人排骨的嘛就懒点
Sure, we are cooking Lazy Man Pork Rib, just be lazy

0:02:00.339,0:02:01.264
整长节点
Let the pork rib piece be longer

0:02:01.540,0:02:02.085
要得
Sounds good

0:02:03.603,0:02:05.695
先切点柠檬
Firstly, cut some lemon 

0:02:07.177,0:02:07.881
切片
Cut a slice

0:02:09.822,0:02:11.187
你要泡水喝不嘛四伯爷
Do you wanna make some lemon water? Si Bai Ye

0:02:11.245,0:02:11.674
安
Hmm?

0:02:12.001,0:02:12.742
泡水喝不
Wanna make lemon water?


0:02:13.476,0:02:13.781
喝过安
I had it before

0:02:13.781,0:02:15.016
你要不要尝一哈四伯爷
Do you wanna try it? Si Bai Ye

0:02:15.292,0:02:15.873
喝过
I had it

0:02:16.767,0:02:17.319
尝一坨嘛
Just taste one piece?

0:02:18.467,0:02:19.150
你尝 
You do

0:02:19.273,0:02:23.348
那会儿我都整来怎么吃的呢 整来腌白糖
How did I eat lemon previously? I cured lemon by sugar  

0:02:27.838,0:02:28.674
啊
Ah

0:02:29.306,0:02:31.522
哎呀 好酸哦
Oh my, how sour it is

0:02:31.921,0:02:33.817
挑战无表情吃柠檬
Challenge eating lemon without a grimace  

0:02:34.275,0:02:36.236
不吃不吃 吃不得
No no, I can’t eat it 

0:02:37.057,0:02:38.438
只有腌白糖吃 好吃
I can only eat it if cured by sugar, that’s yum

0:02:39.077,0:02:40.116
现在切点姜
Now cut some ginger

0:02:43.988,0:02:45.041
 整几根小葱
Process some green onion

0:02:50.446,0:02:50.955
可乐
Coke

0:02:54.515,0:02:55.045
好了
Alright

0:02:55.583,0:02:57.370
然后加点盐巴
And then add some salt

0:02:57.384,0:02:58.133
 一会就跟开水一样 是嘛
It will be like boiling water later, right?

0:02:58.737,0:02:59.197
哇
Wow

0:02:59.404,0:02:59.857
 该是嘎
Yeah, it is

0:02:59.857,0:03:01.940
跟它深水炸弹样嘎
Ah it’s like a depth bomb

0:03:03.256,0:03:04.713
再加点白糖
Add some sugar

0:03:05.999,0:03:06.747
糖多一点
A little bit more sugar

0:03:07.666,0:03:08.562
好可以了
Alright, that’s all

0:03:09.349,0:03:10.167
这个不要撒
Do you need this one?


0:03:10.432,0:03:11.055
不要
No

0:03:11.912,0:03:12.637
 好可以了
Alright

0:03:15.535,0:03:18.854
首先在锅中加入适量的清水
Firstly, add moderate water in wok

0:03:19.446,0:03:21.316
再把排骨放下去
And then put the pork rib in it

0:03:22.142,0:03:25.485
我感觉这个排骨比我的排骨都大
I feel the pork rib is bigger than mine

0:03:25.882,0:03:27.534
然后加入料酒
And then add some rice wine

0:03:29.380,0:03:30.775
开大火烧开
Boil the water on high heat

0:03:33.759,0:03:34.592
去浮沫
Remove the foam

0:03:40.202,0:03:42.547
再把排骨捞出来
Then take the pork rib out


0:03:46.490,0:03:48.297
下面把锅烧热
Next, heat the wok

0:03:48.757,0:03:52.333
加入准备好的可乐倒入锅中
Pour the preprocessed Coke into the wok

0:03:54.328,0:03:56.629
再放入焯好水的排骨
Then put the pork rib scalded by boiling water

0:03:57.397,0:04:00.459
再加两颗八角两片香叶
Then put two star anises and two pieces of bay leaves

0:04:06.778,0:04:08.889
烧开之后又去浮沫
After the water boiling again, remove foam

0:04:12.169,0:04:15.512
因为伯爷牙齿不好需要烧很久
Because Bai Ye can’t chew a lot we have to braise it longer

0:04:16.174,0:04:17.966
所以再加点可乐
So add more Coke

0:04:22.727,0:04:24.892
开小火烧半个小时
Boil it for half hour on low heat 

0:04:27.869,0:04:31.235
再把柠檬 姜片 小葱夹出来
And then take the lemon, ginger and green onion out 

0:04:33.735,0:04:35.216
再开大火收汁儿
Then turn to high heat until the sauce is absorbed

0:04:35.769,0:04:41.807
这懒人排骨真的很简单就是烧的时间会比较长一点
The Lazy Man Pork Rib is really easy, you just need to braise it for a longer time 
0:04:42.485,0:04:43.615
如果你牙口好
If your teeth conditio is good

0:04:44.137,0:04:46.996
烧个ten minutes也是可以的
You probably just need to braise it for 10 minutes

0:04:53.252,0:04:53.930
移过来点嘛
Move it closer

0:04:54.164,0:04:54.616
要得啊
Sure

0:04:54.663,0:04:55.792
吃嘛 夹来吃撒
Try, nip it

0:04:55.792,0:04:57.460
夹来吃四伯爷 伯娘
Nip it, Si Bai Ye, Bai Niang

0:04:57.460,0:04:57.904
好
Okey

0:04:57.904,0:04:59.696
这次咬得动 肯定很耙活
This time you can chew it easily, must be very soft

0:05:00.670,0:05:01.503
脱骨的了
The meat and bone are separated

0:05:01.503,0:05:02.508
肉是肉 骨头是骨头
Here is the Pork meat, and here is the bone

0:05:02.508,0:05:04.480
真的这回可能是整耙了安
Looks like the pork rib is really soft this time

0:05:05.251,0:05:06.139
这个骨头不要了
Throw this bone away

0:05:09.061,0:05:09.404
哎呀
Ah!

0:05:10.564,0:05:11.609
我夹一坨大的
Let me nip a large one

0:05:12.029,0:05:12.746
好耙
How soft it is

0:05:13.774,0:05:14.709
这伯爷咬得动
Bai Ye can chew it easily

0:05:15.037,0:05:15.863
一抿就烂了
Melt in the mouth


0:05:16.283,0:05:16.610
是啊
Yeah

0:05:19.127,0:05:20.218
因为炖了很久
Because we braise it a long time

0:05:20.997,0:05:21.971
嗯可以
Hmm, good

0:05:24.293,0:05:27.744
这中午的懒人排骨硬是拿给你整耙了
The Lazy Man pork rib you made this noon is really soft  

0:05:29.533,0:05:32.733
整来跟你师父的相差不远了
Close to your master’s

0:05:33.756,0:05:34.572
相差不远了
Close

0:05:34.572,0:05:34.948
嗯
Yeah

0:05:35.090,0:05:36.101
打得到好多分嘛

How would you grade it 

0:05:36.515,0:05:37.681
打得到98分
I can give you 98

0:05:38.264,0:05:39.391
98分啊
Ah, 98

0:05:39.624,0:05:41.541
100分你是达不到的 
It’s still not good enough for 100

0:05:44.235,0:05:45.816
我好开心哦
I am so happy

0:05:45.984,0:05:47.435
我要上天了
I am flattered

0:05:47.551,0:05:49.753
你不要太骄傲了撒你
Don’t be overly proud

0:05:51.917,0:05:55.893
给你们说了这个懒人排骨只有懒人才做的出来
Only lazy man can make this lazy pork ribs

0:05:57.681,0:05:58.627
还可以
Not bad

0:05:59.041,0:05:59.391
可以
Good

0:05:59.468,0:06:00.155
 好吃
Yummy

0:06:00.570,0:06:02.823
这中午的这个懒人排骨拿给你整巴适了的
You did a good job on the lazy man pork ribs this noon

0:06:03.860,0:06:04.779
多吃点四伯爷
Have more, Si Bai Ye

0:06:05.336,0:06:06.476
好吃就多吃点
Have more if you like it

0:06:06.722,0:06:07.629
好嘛好嘛
Fine, fine

0:06:08.095,0:06:09.132
我都吃了几坨了
I had several ribs

0:06:10.349,0:06:12.253
这次你做的这个懒人排骨安
The lazy man chop ribs you made this time

0:06:13.186,0:06:14.507
我还是夸你一哈
I have to praise you

0:06:15.142,0:06:17.875
不愧是懒人做的懒人排骨
Lazy man made lazy man pork ribs indeed
 
0:06:18.199,0:06:20.129
这是在夸我呢还是在
Is this praise or

0:06:22.279,0:06:23.704
懒人做的排骨就
Lazy man made ribs

0:06:23.704,0:06:24.326
在夸你
It’s a praise

0:06:24.987,0:06:28.005
我怎么听出了其他的意思呢四伯爷
Why I heard something else, Si Bai Ye

0:06:28.082,0:06:33.367
不是的 懒人做的排骨今中午就不造假了
No, it is a real lazy man made authentic Lazy Man Pork Rib this noon

0:06:34.611,0:06:36.761
四伯爷还在强调懒人做的排骨
Si Bai Ye is keeping emphasizing it is a lazy man made the ribs

0:06:37.279,0:06:38.782
懒人做的排骨就可以
The ribs are good if it is a lazy man cook it

0:06:38.873,0:06:43.899
嗯 开心 今天我觉得这个懒人排骨做的还可以
Emm, I’m happy, I feel the Lazy Man Pork Rib is well made

0:06:44.119,0:06:47.810
颜色啊 各方面啊 味道那些啊
Colors, tastes, etc.

0:06:47.979,0:06:48.924
都还不错
Quit good

0:06:49.365,0:06:52.239
懒人排骨懒人做的他就要用心点晓得不嘛
Lazy man would pay more attention when making Lazy Man Pork Rib

0:06:52.239,0:06:53.471
给我自己比一个
Give myself a big thumbs up
0:06:54.585,0:06:55.233
GOOD

0:06:57.513,0:07:00.362
这个菜做得好不是因为我是懒人
This dish is well made is not because I am lazy

0:07:00.362,0:07:01.450
是我真的做得好
I did a really good job

0:07:02.914,0:07:05.103
这个勤快人也一定会做得好的
So diligent man can do it well for sure

0:07:05.505,0:07:07.253
然后本期视频就到这里了哟
This video clip will end here 

0:07:07.487,0:07:09.728
拜拜
Bye

0:07:10.906,0:07:12.590
放到等会吃饭的时候一起吃
Will have it later in lunch time
