### ISSUE TITLE
[老饭骨] 将军排骨- https://youtu.be/1K495_8FTy8

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1082]
**视频链接**：https://youtu.be/1K495_8FTy8

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【國宴大師•將軍排骨】好吃到尖叫的將軍排骨！外酥裏嫩味道超贊！二伯帶妳解鎖排骨新吃法！|老飯骨

简介
小友們好，今天二伯帶給大家一道好吃到尖叫的將軍排骨！
二伯教給大家了一個去腥味的小竅門，大家學會了嗎？
這將軍排骨加入香料先燉得爛爛乎乎，和上粉子，把排骨炸得酥脆！
最後加入辣椒、花生、麻花一起翻炒！
小友們快點擊視頻學起來，大口吃肉、大口喝酒，痛快！

字幕
1
00:00:00,000 --> 00:00:04,160
据说这是将军菜是吧 将军排骨

2
00:00:04,160 --> 00:00:06,040
你看整个沾上粉子

3
00:00:06,040 --> 00:00:07,880
它炸出来就是酥香酥香的

4
00:00:07,880 --> 00:00:08,960
必须得裹匀了它

5
00:00:08,960 --> 00:00:10,240

6
00:00:10,240 --> 00:00:12,320
你闻这香味 太有食欲了

7
00:00:12,320 --> 00:00:20,360

8
00:00:20,360 --> 00:00:24,080
先把排骨焯了 小魏加点酒 料酒

9
00:00:24,080 --> 00:00:26,400
这个排骨我跟你讲 最好是什么

10
00:00:26,400 --> 00:00:30,800
拿水泡一下 把血水拔拔

11
00:00:30,800 --> 00:00:32,280
这样还可以去腥味

12
00:00:32,280 --> 00:00:34,760
然后这个焯透了就行了

13
00:00:34,760 --> 00:00:36,640
其实通过气味的变化

14
00:00:36,640 --> 00:00:39,360
(腥味)还是出不去 缺少香料的味

15
00:00:39,360 --> 00:00:42,320
比如做蒜泥白肉 或者做酸菜白肉

16
00:00:42,320 --> 00:00:45,480
人说这酸菜白肉不能吃料香味

17
00:00:45,480 --> 00:00:46,920
但是我提前就搁一大料

18
00:00:46,920 --> 00:00:49,040
这大料我在三分之一的时间

19
00:00:49,040 --> 00:00:51,800
我把大料就择出去了

20
00:00:51,800 --> 00:00:54,880
然后再往下炖它就没有大料味了

21
00:00:54,880 --> 00:00:57,720
但是这种料香气味直接就进去了

22
00:00:57,720 --> 00:00:59,120
它没有任何料味

23
00:00:59,120 --> 00:01:00,960
所以说这就是一个窍门

24
00:01:00,960 --> 00:01:02,200
该煸锅了吧

25
00:01:02,200 --> 00:01:05,840

26
00:01:05,840 --> 00:01:09,640
葱姜 整料就进去了

27
00:01:09,640 --> 00:01:13,880
亮子给点豆瓣酱 小魏你攉拢着

28
00:01:13,880 --> 00:01:18,160
让它煸 煸香了它 煸酥了它

29
00:01:18,160 --> 00:01:20,680

30
00:01:20,680 --> 00:01:23,320
泡椒也是整个

31
00:01:23,320 --> 00:01:25,200
小魏你看 香气出来了吧

32
00:01:25,200 --> 00:01:27,120
料酒 小亮 搁

33
00:01:27,120 --> 00:01:28,640

34
00:01:28,640 --> 00:01:30,040
小亮可以搁水了

35
00:01:30,040 --> 00:01:32,240

36
00:01:32,240 --> 00:01:34,720
可以搁没事儿 红红火火

37
00:01:34,720 --> 00:01:37,720

38
00:01:37,720 --> 00:01:40,960
咱们弄点红曲水 搁进去吧

39
00:01:40,960 --> 00:01:43,880
你看这颜色更红

40
00:01:43,880 --> 00:01:45,040
调味吧

41
00:01:45,040 --> 00:01:46,840
加点糖

42
00:01:46,840 --> 00:01:49,280
（白）胡椒粉

43
00:01:49,280 --> 00:01:51,280
再搁点酱油

44
00:01:51,280 --> 00:01:53,400
别搁太多因为这颜色就够了

45
00:01:53,400 --> 00:01:56,760
这就起一调味作用

46
00:01:56,760 --> 00:01:58,760
把这个肉捞出来搁这里边

47
00:01:58,760 --> 00:02:01,560
给它挑出来 炖上

48
00:02:01,560 --> 00:02:02,680

49
00:02:02,680 --> 00:02:07,200
香叶 桂皮 大料瓣 小火炖着吧

50
00:02:07,200 --> 00:02:11,800
你看这颜色多漂亮 多红亮

51
00:02:11,800 --> 00:02:13,880

52
00:02:14,920 --> 00:02:17,640
你看搁点香料这味儿立马就变了

53
00:02:17,640 --> 00:02:19,880
肉香味儿出来

54
00:02:19,880 --> 00:02:21,720
过去你看湘菜红煨

55
00:02:21,720 --> 00:02:22,280

56
00:02:23,000 --> 00:02:26,520
你看蒜不能煸 不能吃出蒜味

57
00:02:26,520 --> 00:02:31,240
搁了蒜子以外 咱们现在搁一把尖椒

58
00:02:31,240 --> 00:02:33,400
就有一种特殊的蔬菜味

59
00:02:33,400 --> 00:02:36,760
尖椒是鲜的还是干的 鲜的啊

60
00:02:36,760 --> 00:02:39,520
所以说这个肉单独的

61
00:02:39,520 --> 00:02:41,000
就有一种特殊的香味

62
00:02:41,000 --> 00:02:43,120
有一种清香气

63
00:02:43,120 --> 00:02:47,200
你看咱这颜色 加了红曲米的颜色

64
00:02:47,200 --> 00:02:50,400
看这汤 清澈 红红的

65
00:02:50,400 --> 00:02:52,560
排骨的颜色也很自然

66
00:02:52,560 --> 00:02:56,840
这个炖出来我们可以直接就吃了

67
00:02:56,840 --> 00:03:01,280
辣椒 花椒 哗一呲 上边顶着

68
00:03:01,280 --> 00:03:02,880
小魏怎么样 又是一道菜

69
00:03:02,880 --> 00:03:04,640
方法是一样的 就看你怎么去做了

70
00:03:04,640 --> 00:03:06,400

71
00:03:06,400 --> 00:03:08,080
这样咱就炖它一会

72
00:03:08,080 --> 00:03:09,440
实际上通过您这一道菜

73
00:03:09,440 --> 00:03:11,320
我能联想起很多菜

74
00:03:11,320 --> 00:03:14,960
就这个菜的做法可以延展很宽

75
00:03:14,960 --> 00:03:18,160
排骨啊 你看炖熟了

76
00:03:18,160 --> 00:03:20,920
你看这个颜色是吧 挑出来就行了

77
00:03:20,920 --> 00:03:24,080

78
00:03:24,080 --> 00:03:28,920
烂烂乎乎 关键是味道 烂是一方面

79
00:03:28,920 --> 00:03:31,480
我把您这个做法学会了

80
00:03:31,480 --> 00:03:35,640
回去我拿羊排做去 羊排做也好吃

81
00:03:35,640 --> 00:03:38,080
没毛病 拍粉子吧师父

82
00:03:38,440 --> 00:03:40,360
（红薯淀粉）

83
00:03:40,360 --> 00:03:42,120
你看整个沾上粉子

84
00:03:42,120 --> 00:03:43,760
它炸出来就是酥香酥香的

85
00:03:43,760 --> 00:03:45,040
必须得裹匀了它

86
00:03:45,040 --> 00:03:47,800

87
00:03:47,800 --> 00:03:49,000
你看裹不匀就不行

88
00:03:49,000 --> 00:03:52,440
要不然炸出来就柴 必须得全裹透了

89
00:03:52,440 --> 00:03:55,160
这边粉子浮着呢师父

90
00:03:55,160 --> 00:03:57,560
非常香 这已经就炖的很香了

91
00:03:57,560 --> 00:03:59,840
油温可以了

92
00:03:59,840 --> 00:04:02,960
咱们做的有点多 多来点吧

93
00:04:02,960 --> 00:04:07,000

94
00:04:07,000 --> 00:04:08,520
这就差不多

95
00:04:08,520 --> 00:04:09,560

96
00:04:09,560 --> 00:04:14,880
哄一下油 让它更加酥脆 外酥里嫩

97
00:04:14,880 --> 00:04:16,160

98
00:04:17,440 --> 00:04:18,440
出锅喽

99
00:04:18,440 --> 00:04:23,720

100
00:04:23,720 --> 00:04:25,320
来点油

101
00:04:25,320 --> 00:04:27,720
芽菜 这儿呢 芽菜

102
00:04:27,720 --> 00:04:30,120
芽菜必须得洗一下啊

103
00:04:30,120 --> 00:04:31,600
你看料酒

104
00:04:31,600 --> 00:04:34,280

105
00:04:37,440 --> 00:04:38,760
芽菜香了

106
00:04:38,760 --> 00:04:42,920
排骨 搁辣椒

107
00:04:42,920 --> 00:04:46,400
花生倒么 花生倒 麻花都搁进去

108
00:04:46,400 --> 00:04:48,440
小魏 麻辣鲜露

109
00:04:48,440 --> 00:04:53,160

110
00:04:54,720 --> 00:04:57,040
你闻这香味 小魏 太有食欲了

111
00:04:57,040 --> 00:04:59,320

112
00:04:59,320 --> 00:05:02,720
你看这上边 麻花

113
00:05:02,720 --> 00:05:05,040
排骨做好了师父 将军排骨

114
00:05:05,040 --> 00:05:08,040
咱就武吃呗 我也来一块

115
00:05:08,920 --> 00:05:11,000
味道非常特殊

116
00:05:11,000 --> 00:05:13,120

117
00:05:13,120 --> 00:05:15,600
外边焦的 里边嫩的

118
00:05:15,600 --> 00:05:17,640
这还有一种特殊气味

119
00:05:17,640 --> 00:05:19,760
回口特别好吃 有点麻味儿吧

120
00:05:19,760 --> 00:05:22,400
师父您也吃一块

121
00:05:22,400 --> 00:05:23,320
好吃 真好吃师父

122
00:05:25,000 --> 00:05:27,480
这是酒菜 要喝酒的话绝了

123
00:05:27,480 --> 00:05:30,080


```

**Comment by Kevinzheng5** [comment]
认领

**Comment by Kevinzheng5** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【國宴大師•將軍排骨】好吃到尖叫的將軍排骨！外酥裏嫩味道超贊！二伯帶妳解鎖排骨新吃法！|老飯骨
State Banquet Master Chef – General Ribs. Crispy and tender with amazing taste!

简介
小友們好，今天二伯帶給大家一道好吃到尖叫的將軍排骨！
二伯教給大家了一個去腥味的小竅門，大家學會了嗎？
這將軍排骨加入香料先燉得爛爛乎乎，和上粉子，把排骨炸得酥脆！
最後加入辣椒、花生、麻花一起翻炒！
小友們快點擊視頻學起來，大口吃肉、大口喝酒，痛快！
Hey guys, today Erbai will share a great dish called General’s Ribs!
The trick is how to season the ribs.
We first season and stew the ribs. Then we coat the ribs and fry them!
Finally we stir fry the ribs with chili, peanuts and dough twists!
Have a try yourself! The dish goes great with a drink!

字幕
1
00:00:00,000 --> 00:00:04,160
据说这是将军菜是吧 将军排骨
The dish is called the general’s ribs. 

2
00:00:04,160 --> 00:00:06,040
你看整个沾上粉子
We coat the ribs well

3
00:00:06,040 --> 00:00:07,880
它炸出来就是酥香酥香的
It will be so crispy with aroma after frying

4
00:00:07,880 --> 00:00:08,960
必须得裹匀了它
The coat must be even

5
00:00:08,960 --> 00:00:10,240

6
00:00:10,240 --> 00:00:12,320
你闻这香味 太有食欲了
Smell the aroma, so appetizing

7
00:00:12,320 --> 00:00:20,360
将军排骨辅料：香脆椒，原味小麻花，郫县豆瓣酱，椒盐花生米，泡辣椒，芽菜，红曲米
Ingredients: chilis, fried dough twists, Pixian bean paste, peanuts, preserved chilis, preserved mustard greens, fermented red rice

8
00:00:20,360 --> 00:00:24,080
先把排骨焯了 小魏加点酒 料酒
Boil the ribs first with some Chinese cooking wine

9
00:00:24,080 --> 00:00:26,400
这个排骨我跟你讲 最好是什么
One trick for cooking ribs,

10
00:00:26,400 --> 00:00:30,800
拿水泡一下 把血水拔拔
Soak them first to get the blood and scum off

11
00:00:30,800 --> 00:00:32,280
这样还可以去腥味
That will get rid of the fishy smell

12
00:00:32,280 --> 00:00:34,760
然后这个焯透了就行了
Boil until they are cooked

13
00:00:34,760 --> 00:00:36,640
其实通过气味的变化
You can know from the smell

14
00:00:36,640 --> 00:00:39,360
(腥味)还是出不去 缺少香料的味
That the ribs are still a bit fishy. They need seasoning

15
00:00:39,360 --> 00:00:42,320
比如做蒜泥白肉 或者做酸菜白肉
For dishes like the garlic white pork and the pickled Chinese cabbage white pork

16
00:00:42,320 --> 00:00:45,480
人说这酸菜白肉不能吃料香味
We don’t season the pork too much

17
00:00:45,480 --> 00:00:46,920
但是我提前就搁一大料
But for this dish, we can boil the ribs with a star anise

18
00:00:46,920 --> 00:00:49,040
这大料我在三分之一的时间
About one third of the boiling time

19
00:00:49,040 --> 00:00:51,800
我把大料就择出去了
We take the star anise off

20
00:00:51,800 --> 00:00:54,880
然后再往下炖它就没有大料味了
So that the bitter taste stay away

21
00:00:54,880 --> 00:00:57,720
但是这种料香气味直接就进去了
But the aroma of the star anise goes into the ribs

22
00:00:57,720 --> 00:00:59,120
它没有任何料味
It doesn’t have the bitter taste of the herbs

23
00:00:59,120 --> 00:01:00,960
所以说这就是一个窍门
That’s one trick

24
00:01:00,960 --> 00:01:02,200
该煸锅了吧
It’s time to sauté the herbs

25
00:01:02,200 --> 00:01:05,840

26
00:01:05,840 --> 00:01:09,640
葱姜 整料就进去了
Drop big chunks of green onions and gingers in the wok

27
00:01:09,640 --> 00:01:13,880
亮子给点豆瓣酱 小魏你攉拢着
Then some bean paste. Keep stirring the wok

28
00:01:13,880 --> 00:01:18,160
让它煸 煸香了它 煸酥了它
Stir fry them well to get the aroma out and the herbs crispy

29
00:01:18,160 --> 00:01:20,680

30
00:01:20,680 --> 00:01:23,320
泡椒也是整个
Drop the preserved chili in big chunks too 

31
00:01:23,320 --> 00:01:25,200
小魏你看 香气出来了吧
Smell the aroma

32
00:01:25,200 --> 00:01:27,120
料酒 小亮 搁
Then some Chinese cooking wine

33
00:01:27,120 --> 00:01:28,640

34
00:01:28,640 --> 00:01:30,040
小亮可以搁水了
Then we can add some water and bring it to boil

35
00:01:30,040 --> 00:01:32,240

36
00:01:32,240 --> 00:01:34,720
可以搁没事儿 红红火火
It’s fine. Looks great! 

37
00:01:34,720 --> 00:01:37,720

38
00:01:37,720 --> 00:01:40,960
咱们弄点红曲水 搁进去吧
Get some sauce from the preserved red rice and add in the wok

39
00:01:40,960 --> 00:01:43,880
你看这颜色更红
It will turn the color more bright and red

40
00:01:43,880 --> 00:01:45,040
调味吧
Then let’s season the dish

41
00:01:45,040 --> 00:01:46,840
加点糖
Some sugar

42
00:01:46,840 --> 00:01:49,280
（白）胡椒粉
Pepper

43
00:01:49,280 --> 00:01:51,280
再搁点酱油
Some soy sauce

44
00:01:51,280 --> 00:01:53,400
别搁太多因为这颜色就够了
Hold the soy sauce because the color is enough

45
00:01:53,400 --> 00:01:56,760
这就起一调味作用
Only some for the taste

46
00:01:56,760 --> 00:01:58,760
把这个肉捞出来搁这里边
Get the ribs out and drop in the seasoned soup

47
00:01:58,760 --> 00:02:01,560
给它挑出来 炖上
Drop and stew the ribs

48
00:02:01,560 --> 00:02:02,680

49
00:02:02,680 --> 00:02:07,200
香叶 桂皮 大料瓣 小火炖着吧
Add some bay leaves, cinnamon and star anise pieces. Turn the burner lower and stew

50
00:02:07,200 --> 00:02:11,800
你看这颜色多漂亮 多红亮
Look at the color. So bright and red

51
00:02:11,800 --> 00:02:13,880

52
00:02:14,920 --> 00:02:17,640
你看搁点香料这味儿立马就变了
The herbs changes the taste right away

53
00:02:17,640 --> 00:02:19,880
肉香味儿出来
The aroma of the pork comes out

54
00:02:19,880 --> 00:02:21,720
过去你看湘菜红煨
There’s a trick from Hunan style simmering

55
00:02:21,720 --> 00:02:22,280

56
00:02:23,000 --> 00:02:26,520
你看蒜不能煸 不能吃出蒜味
Garlics should be added after the stir frying. Then the garlic taste stays veiled

57
00:02:26,520 --> 00:02:31,240
搁了蒜子以外 咱们现在搁一把尖椒
Besides the garlic, drop some pepper in the wok too

58
00:02:31,240 --> 00:02:33,400
就有一种特殊的蔬菜味
Adds some vegetable smell in there

59
00:02:33,400 --> 00:02:36,760
尖椒是鲜的还是干的 鲜的啊
Fresh or dried pepper? Fresh ones

60
00:02:36,760 --> 00:02:39,520
所以说这个肉单独的
What the peppers do to the ribs 

61
00:02:39,520 --> 00:02:41,000
就有一种特殊的香味
Is to add another dimension of smell

62
00:02:41,000 --> 00:02:43,120
有一种清香气
Makes it more fresh and light

63
00:02:43,120 --> 00:02:47,200
你看咱这颜色 加了红曲米的颜色
Look at the color with the preserved red rice sauce

64
00:02:47,200 --> 00:02:50,400
看这汤 清澈 红红的
The soup is clear and red

65
00:02:50,400 --> 00:02:52,560
排骨的颜色也很自然
The color of the ribs are natural

66
00:02:52,560 --> 00:02:56,840
这个炖出来我们可以直接就吃了
We can eat the ribs directly after stewing

67
00:02:56,840 --> 00:03:01,280
辣椒 花椒 哗一呲 上边顶着
Or put some chili and peppercorn at the top, with hot oil splitting

68
00:03:01,280 --> 00:03:02,880
小魏怎么样 又是一道菜
It will generate another dish

69
00:03:02,880 --> 00:03:04,640
方法是一样的 就看你怎么去做了
The ribs are the same and it depends on how you like them

70
00:03:04,640 --> 00:03:06,400

71
00:03:06,400 --> 00:03:08,080
这样咱就炖它一会
Let’s stew the ribs

72
00:03:08,080 --> 00:03:09,440
实际上通过您这一道菜
Through this dish

73
00:03:09,440 --> 00:03:11,320
我能联想起很多菜
I can remind of many different dishes

74
00:03:11,320 --> 00:03:14,960
就这个菜的做法可以延展很宽
The process of this dish can have many different twists

75
00:03:14,960 --> 00:03:18,160
排骨啊 你看炖熟了
Now the ribs are ready

76
00:03:18,160 --> 00:03:20,920
你看这个颜色是吧 挑出来就行了
The color is so good. Get the ribs out

77
00:03:20,920 --> 00:03:24,080

78
00:03:24,080 --> 00:03:28,920
烂烂乎乎 关键是味道 烂是一方面
The texture is very soft but the key is the taste

79
00:03:28,920 --> 00:03:31,480
我把您这个做法学会了
The way to cook the ribs is very general

80
00:03:31,480 --> 00:03:35,640
回去我拿羊排做去 羊排做也好吃
I can also try with lamb and I believe it’s good too

81
00:03:35,640 --> 00:03:38,080
没毛病 拍粉子吧师父
Alright, let’s coat the ribs

82
00:03:38,440 --> 00:03:40,360
（红薯淀粉）
Sweet potato starch

83
00:03:40,360 --> 00:03:42,120
你看整个沾上粉子
Coat the ribs evenly well

84
00:03:42,120 --> 00:03:43,760
它炸出来就是酥香酥香的
After frying, it will be delicious and crispy

85
00:03:43,760 --> 00:03:45,040
必须得裹匀了它
The key is to make the coating even

86
00:03:45,040 --> 00:03:47,800

87
00:03:47,800 --> 00:03:49,000
你看裹不匀就不行
Look at the missing spot

88
00:03:49,000 --> 00:03:52,440
要不然炸出来就柴 必须得全裹透了
That’s where the hot oil will get in and make the ribs dry

89
00:03:52,440 --> 00:03:55,160
这边粉子浮着呢师父
Another missing spot here too master

90
00:03:55,160 --> 00:03:57,560
非常香 这已经就炖的很香了
The smell is so good

91
00:03:57,560 --> 00:03:59,840
油温可以了
The oil is ready

92
00:03:59,840 --> 00:04:02,960
咱们做的有点多 多来点吧
We have a large portion here so we got much oil

93
00:04:02,960 --> 00:04:07,000

94
00:04:07,000 --> 00:04:08,520
这就差不多
It’s about right

95
00:04:08,520 --> 00:04:09,560

96
00:04:09,560 --> 00:04:14,880
哄一下油 让它更加酥脆 外酥里嫩
Get the ribs out for a sec. Bring the oil hotter and re-fry, so that the coat is extra crispy

97
00:04:14,880 --> 00:04:16,160

98
00:04:17,440 --> 00:04:18,440
出锅喽
Get the ribs out!

99
00:04:18,440 --> 00:04:23,720

100
00:04:23,720 --> 00:04:25,320
来点油
Some oil in the wok

101
00:04:25,320 --> 00:04:27,720
芽菜 这儿呢 芽菜
Where’s the preserved mustard green? In the pan

102
00:04:27,720 --> 00:04:30,120
芽菜必须得洗一下啊
Make sure you clean the preserved mustard green well

103
00:04:30,120 --> 00:04:31,600
你看料酒
Some Chinese cooking wine in the wok

104
00:04:31,600 --> 00:04:34,280

105
00:04:37,440 --> 00:04:38,760
芽菜香了
I can smell the preserved mustard green

106
00:04:38,760 --> 00:04:42,920
排骨 搁辣椒
Drop the ribs and chili

107
00:04:42,920 --> 00:04:46,400
花生倒么 花生倒 麻花都搁进去
Peanuts now? Yeah peanuts along with the dough twists

108
00:04:46,400 --> 00:04:48,440
小魏 麻辣鲜露
Some Chinese liquid seasoning in the wok

109
00:04:48,440 --> 00:04:53,160

110
00:04:54,720 --> 00:04:57,040
你闻这香味 小魏 太有食欲了
Whoa the smell is so appetizing

111
00:04:57,040 --> 00:04:59,320

112
00:04:59,320 --> 00:05:02,720
你看这上边 麻花
The dough twists looks really nice in the dish

113
00:05:02,720 --> 00:05:05,040
排骨做好了师父 将军排骨
The general’s ribs are ready!

114
00:05:05,040 --> 00:05:08,040
咱就武吃呗 我也来一块
I can’t wait for the chopsticks. Let me try one first

115
00:05:08,920 --> 00:05:11,000
味道非常特殊
The smell is phenomenal 

116
00:05:11,000 --> 00:05:13,120

117
00:05:13,120 --> 00:05:15,600
外边焦的 里边嫩的
It’s crispy on the exterior but still tender inside

118
00:05:15,600 --> 00:05:17,640
这还有一种特殊气味
There’s also a special aroma 

119
00:05:17,640 --> 00:05:19,760
回口特别好吃 有点麻味儿吧
The taste stays in your month, a little bit numbing too

120
00:05:19,760 --> 00:05:22,400
师父您也吃一块
Have a piece master

121
00:05:22,400 --> 00:05:23,320
好吃 真好吃师父
It’s really good

122
00:05:25,000 --> 00:05:27,480
这是酒菜 要喝酒的话绝了
The dish goes great with alcohol. It will be amazing if you have this with a drink. 

123
00:05:27,480 --> 00:05:30,080

**Comment by immoonancient** [comment]
误操作了，修改意见还没有整合进去
整合完了再上传
