### ISSUE TITLE
【美食作家王刚】苦瓜酿肉 - https://youtu.be/5bSatykuR08

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1083]
**视频链接**：https://youtu.be/5bSatykuR08

视频时长10:14，预计发布时间为北京时间5月28日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：夏日去火好菜“苦瓜酿肉”的家常做法，四伯第一次尝试感觉很满意

简介
大家好，最近四川天气很热并且四伯吃了太多漆二娃做的菜有些上火，所以决定做一道夏日去火好菜“苦瓜酿肉”。此菜为经典湘菜，荤素搭配，营养丰富，但做法略复杂，如果想具体学习如何制作此菜可以观看我之前发布的后厨教学视频，里面有更加详细步骤介绍和烹饪技巧，链接在此：https://www.youtube.com/watch?v=PTqX405aepU&t=109s

字幕
0:00:00.200,0:00:01.050
哈喽大家好

0:00:01.375,0:00:04.058
今天我跟我伯爷做一个苦瓜吃

0:00:04.058,0:00:07.194
我们先把它的头去掉然后直接切成圈圈

0:00:10.500,0:00:12.150
如果大家能够吃苦的话

0:00:12.150,0:00:13.850
这个中间不用去得太干净

0:00:14.225,0:00:16.800
如果不能吃苦的话就用刀把它刮干净一点

0:00:17.075,0:00:20.425
苦瓜的苦味大部分是源自于这个里面

0:00:20.625,0:00:22.925
这一层薄膜

0:00:24.725,0:00:26.575
其实苦瓜的籽是不苦的

0:00:26.900,0:00:29.600
主要是这一层白色的东西苦

0:00:29.775,0:00:31.425
这个东西热天吃了好

0:00:31.700,0:00:36.175
就是啊 吃的苦的话就不用整那么干净这个是下火的

0:00:36.850,0:00:37.600
清热

0:00:38.400,0:00:38.800
是

0:00:42.875,0:00:44.425
好 这个我们就挖好了

0:00:44.600,0:00:46.625
但是这个苦瓜要先焯一下水

0:00:46.875,0:00:49.500
焯完水之后放在凉水里面先泡一下

0:00:49.675,0:00:51.825
就是让它去除一些苦味

0:00:51.950,0:00:53.975
还有就是让它更绿不变色

0:00:54.350,0:00:55.400
我先拿去煮一下

0:00:56.175,0:00:56.800
要的

0:01:24.950,0:01:26.750
好啦 这个我们已经焯过水啦

0:01:26.825,0:01:29.550
直接把它放到凉水里面去泡一下

0:01:30.975,0:01:35.575
这样泡着它才不会变黄

0:01:36.150,0:01:38.325
好啦 现在我们来切点肉

0:01:40.525,0:01:43.250
这个是五花肉先把它的皮去掉

0:01:45.600,0:01:48.050
然后我们把这个猪肉先切碎

0:01:48.450,0:01:52.450
切碎了之后再来剁成肉末

0:01:53.550,0:01:56.585
我们现在换双刀一起来把它剁一下

0:01:57.525,0:02:00.575
剁得稍微细一些

0:02:01.500,0:02:03.750
我们这个肉还是最好用刀来剁

0:02:03.825,0:02:08.450
刀剁出来的会比料理机搅碎的要好一些

0:02:11.400,0:02:13.450
好啦 我们这个肉就已经剁好啦

0:02:13.850,0:02:16.950
现在把它拿出来码一下味

0:02:18.100,0:02:19.275
加一点点盐

0:02:20.300,0:02:21.575
然后加点胡椒粉

0:02:23.075,0:02:24.650
再加一点酱油

0:02:26.400,0:02:27.800
然后加一点蚝油

0:02:31.425,0:02:33.400
再来加一点老抽调一下色

0:02:36.000,0:02:38.050
好啦 加了这些之后把它拌匀

0:02:40.962,0:02:43.600
让这个盐充分的融合进去

0:02:43.850,0:02:45.400
打出一些胶质出来

0:02:46.900,0:02:49.400
好 这个上劲了之后我们打一个鸡蛋进去

0:02:52.875,0:02:56.050
打鸡蛋的话就让这个肉更嫩更有质感

0:02:57.175,0:02:57.950
给它拌匀

0:03:02.450,0:03:02.775
好

0:03:05.075,0:03:06.950
然后我们再放一点淀粉

0:03:09.025,0:03:11.950
这个淀粉可以稍微的多一点点

0:03:13.000,0:03:16.325
因为要让这个肉重新回到一个粘手的一个状态

0:03:18.050,0:03:20.375
你看嘛 马上就粘手了

0:03:21.650,0:03:22.025
是不是

0:03:22.550,0:03:23.025
是啊

0:03:25.375,0:03:26.625
好 我们这个搅好啦

0:03:26.625,0:03:29.400
然后我们把这个苦瓜倒出来沥一下水

0:03:31.175,0:03:34.375
好啦现在我们来上一下干淀粉

0:03:34.650,0:03:36.875
我们先把这个干淀粉往中间抹一抹

0:03:37.250,0:03:40.825
它这个待会儿就可以很轻松的把肉粘上去了

0:03:45.800,0:03:48.175
所说我们农村人整的东西没得那么好吃的

0:03:48.275,0:03:49.825
你看你这个好麻烦哦

0:03:51.100,0:03:53.775
然后这个盆里面的淀粉我们不要丢

0:03:54.725,0:03:57.050
给它再放一点进去铺一下下面

0:03:57.875,0:03:59.000
给它铺在底下

0:04:00.250,0:04:01.523
然后这下又反过来

0:04:01.523,0:04:03.450
看嘛 看好麻烦嘛

0:04:03.700,0:04:05.550
反过来又放肉进去

0:04:05.625,0:04:06.200
是啊

0:04:06.825,0:04:07.375
这样子

0:04:07.875,0:04:09.825
肉拿起来往中间放

0:04:11.075,0:04:11.825
往中间放

0:04:12.400,0:04:17.250
放了肉之后再粘点淀粉

0:04:19.650,0:04:21.650
两边都粘上淀粉就可以了

0:04:21.900,0:04:23.400
粘好了就这样放下去

0:04:23.800,0:04:26.150
为什么这下面我要垫粉呢

0:04:26.175,0:04:29.100
就是因为这样放下去了之后就不会粘盘子

0:04:29.575,0:04:30.850
就是这个原因

0:04:31.650,0:04:33.275
我整一个来试一下

0:04:33.275,0:04:34.625
嗯 可以啊 

0:04:38.625,0:04:39.250
怎么样嘛

0:04:40.300,0:04:41.900
这边再给它撒点淀粉

0:04:42.500,0:04:43.375
好 抹一下

0:04:44.800,0:04:47.400
嗯 四伯爷做的不错

0:04:47.800,0:04:49.825
这边感觉淀粉少了点

0:04:49.975,0:04:51.875
少了不关事这下面还垫得有

0:04:51.975,0:04:52.300
要得呀

0:04:52.425,0:04:52.800
不关事

0:04:53.225,0:04:57.975
四伯爷除了杀猪那些还是多做些美食撒

0:04:58.250,0:05:02.200
我一个杀猪匠又何尝不想当个美食家嘛

0:05:02.450,0:05:06.175
我当个美食家的话我出去卖肉都要好卖点

0:05:06.225,0:05:08.675
给别人说这个肉该怎么做来吃

0:05:08.825,0:05:10.125
那个肉该怎么做来吃

0:05:10.500,0:05:11.775
我的肉都要好卖得多

0:05:12.525,0:05:13.400
嗯 就是

0:05:14.350,0:05:16.750
好啦 现在我们来调一个汁 简单的

0:05:17.250,0:05:19.560
放一点点盐 盐不能太多一点点就可以了

0:05:19.775,0:05:21.125
然后再放一点白糖

0:05:21.425,0:05:22.450
放一点点胡椒粉

0:05:24.375,0:05:25.575
再放一点点料酒

0:05:26.225,0:05:28.650
还要放一点生抽酱油

0:05:30.400,0:05:32.275
最后加一点蚝油

0:05:36.025,0:05:37.800
我们再加一点清水

0:05:39.750,0:05:41.800
最后加一点淀粉搅拌一下

0:05:42.025,0:05:44.200
这个汁就调好了

0:05:45.200,0:05:49.000
待会儿我们这个苦瓜两边煎熟了之后

0:05:49.000,0:05:51.300
直接倒这个进去收汁就可以出菜了

0:05:51.350,0:05:52.900
特别简单的一道菜

0:06:24.356,0:06:26.475
我们到这一步的时候就慢慢给它煎

0:06:27.425,0:06:31.900
煎到这一面熟了之后再用筷子把它翻过来再煎另一面

0:06:39.025,0:06:42.300
好 这面煎香了之后我们用筷子把它翻过来

0:06:53.900,0:06:56.150
好 翻过来之后我们又继续煎

0:06:56.975,0:06:59.175
煎到它熟香为止

0:07:08.300,0:07:11.725
好啦 感觉到这个有点焦香焦香的时候

0:07:11.825,0:07:14.125
然后我们再给它翻过来看一下

0:07:17.000,0:07:18.625
哇 已经煎得金黄了

0:07:21.025,0:07:22.100
再给它翻一下

0:07:28.375,0:07:30.725
好啦 我们最后再煎2分钟

0:07:35.775,0:07:37.075
我们这个已经完全煎好啦

0:07:37.225,0:07:39.175
现在把多余的油倒一点出来

0:07:45.775,0:07:49.700
然后我们把这个汁倒下去

0:07:58.275,0:08:01.650
还是继续小火把这个汁水收浓就可以了

0:08:08.675,0:08:11.225
好 轻轻的翻一下就可以了

0:08:13.700,0:08:15.150
 好 可以上菜啦

0:08:20.075,0:08:22.525
看着摆起是安逸

0:08:23.250,0:08:24.450
亮增增的

0:08:24.650,0:08:25.800
香味你闻到没

0:08:26.050,0:08:26.850
闻到了

0:08:31.400,0:08:32.525
夹嘛 四伯爷

0:08:32.650,0:08:34.750
这种做法你在哪里学到的啊

0:08:35.050,0:08:37.600
在外面跑江湖的时候学到的

0:08:38.025,0:08:42.027
哦 以后我还是出去跑哈江湖看学得到这些技术不哦

0:08:43.126,0:08:43.500
可以啊

0:08:46.784,0:08:48.748
嗯 还有一点甜

0:08:48.915,0:08:49.267
是不哦

0:08:49.527,0:08:49.879
是啊

0:08:50.138,0:08:51.955
我还说苦 没想到还有点甜

0:08:53.734,0:08:54.717
加了点白糖都嘛

0:08:55.162,0:08:56.218
也有点苦

0:08:57.738,0:08:59.351
其实这样做的话比较香

0:08:59.369,0:09:00.389
煎出来的更香

0:09:00.834,0:09:03.632
但是在我们饭店里面一般是直接下去炸

0:09:03.948,0:09:05.505
或者是放到蒸柜里面蒸

0:09:06.042,0:09:08.248
如果是蒸的话就颜色特别好看

0:09:08.248,0:09:10.417
但是不香很苦

0:09:11.751,0:09:13.382
我们这个煎出来的虽然说

0:09:13.642,0:09:14.717
有点黄黄的

0:09:15.106,0:09:18.665
但是吃起来绝对很香绝对下饭

0:09:19.388,0:09:21.853
嗯 安逸好香哦

0:09:23.076,0:09:24.986
这种做法我还是第一次吃

0:09:24.986,0:09:26.061
你吃在嘴里是什么感受嘛

0:09:26.246,0:09:27.303
哎呀吃起安逸

0:09:28.044,0:09:29.341
那个味道说不出来

0:09:31.288,0:09:32.048
说不出来

0:09:32.103,0:09:32.493
嗯

0:09:33.215,0:09:34.309
又有点甜

0:09:35.143,0:09:36.292
又有点苦

0:09:36.292,0:09:37.572
就是好吃嘛

0:09:37.812,0:09:38.776
又有点香

0:09:39.239,0:09:43.039
嘿嘿 还不好总结这个味道

0:09:46.376,0:09:47.062
安逸

0:09:47.284,0:09:48.693
这个苦瓜吃起还有点脆

0:09:48.730,0:09:49.657
嗯 

0:09:51.473,0:09:53.456
这个吃了好下火的

0:09:53.549,0:09:55.662
我晓得这个苦瓜吃了好

0:09:56.867,0:09:58.164
我这个才漂亮

0:09:59.518,0:09:59.833
看嘛

0:09:59.870,0:10:01.000
这个是你做的

0:10:01.241,0:10:02.187
看好安逸嘛

0:10:04.911,0:10:06.227
好 本期视频就到这里啦

0:10:06.339,0:10:06.784
拜拜

0:10:08.489,0:10:09.712
好吃 我去添饭


```

**Comment by Yingzhang1122** [comment]
#标题（翻译主要意思即可，不要超过 100 个字符）
#厨师长分享：夏日去火好菜“苦瓜酿肉”的家常做法，四伯第一次尝试感觉很满意
Chef Wang shares: Home-style dish 'Bitter gourd stuffed with meat'. Uncle loves it at his first try!

#简介
#大家好，最近四川天气很热并且四伯吃了太多漆二娃做的菜有些上火，所以决定做一道夏日去火好菜“苦瓜酿肉”。此菜为经典湘菜，荤素搭配，营养丰富，但做法略复杂，如果想具体学习如何制作此菜可以观看我之前发布的后厨教学视频，里面有更加详细步骤介绍和烹饪技巧，链接在此：https://www.youtube.com/watch?v=PTqX405aepU&t=109s
Hi everyone! It's been really hot in Sichuan these days. Also, my uncle is suffering from 'internal heat' because he ate too many dishes cooked by Qi Erwa. Therefore, I decided to cook a dish 'Bitter gourd stuffed with meat', which removes the 'internal heat' in the human body in summer. It is a classic, nutritious Hunan Cuisine made with both meat and vegetable, but a bit complicated to cook. If you are interested in learning how to cook it, please watch my previous video taken in the professional kitchen, in which I introduced more detailed steps and cooking tricks. Please follow this link: https://www.youtube.com/watch?v=PTqX405aepU&t=109s

#字幕
0:00:00.200,0:00:01.050
#哈喽大家好
Hi everyone

0:00:01.375,0:00:04.058
#今天我跟我伯爷做一个苦瓜吃
Today I'm gonna cook a dish with the bitter gourd for my uncle

0:00:04.058,0:00:07.194
#我们先把它的头去掉然后直接切成圈圈
Firstly we chop its head and cut it into rings directly

0:00:10.500,0:00:12.150
#如果大家能够吃苦的话
If you are OK with bitter food

0:00:12.150,0:00:13.850
#这个中间不用去得太干净
You don't have to remove all these at the center

0:00:14.225,0:00:16.800
#如果不能吃苦的话就用刀把它刮干净一点
Otherwise, you can scrape it with a knife

0:00:17.075,0:00:20.425
#苦瓜的苦味大部分是源自于这个里面
Most of the bitterness comes from this

0:00:20.625,0:00:22.925
#这一层薄膜
The membrane here

0:00:24.725,0:00:26.575
#其实苦瓜的籽是不苦的
Actually, the seeds of the bitter gourd are not bitter

0:00:26.900,0:00:29.600
#主要是这一层白色的东西苦
It's the 'white membrane' that is bitter

0:00:29.775,0:00:31.425
#这个东西热天吃了好
It's good to eat this in hot days

0:00:31.700,0:00:36.175
#就是啊 吃的苦的话就不用整那么干净这个是下火的
That's right. If you eat bitter food, you don't need to remove it completely as it clears your 'internal heat'

0:00:36.850,0:00:37.600
#清热
Clears the heat

0:00:38.400,0:00:38.800
#是
Yep

0:00:42.875,0:00:44.425
#好 这个我们就挖好了
Ok. We are done with this

0:00:44.600,0:00:46.625
#但是这个苦瓜要先焯一下水
But we still need to blanch the bitter gourd first

0:00:46.875,0:00:49.500
#焯完水之后放在凉水里面先泡一下
After blanching, soak it in cold water for a while

0:00:49.675,0:00:51.825
#就是让它去除一些苦味
to remove some of the bitterness

0:00:51.950,0:00:53.975
#还有就是让它更绿不变色
Also, this step keeps it green in the following cooking

0:00:54.350,0:00:55.400
#我先拿去煮一下
Let me blanch it first

0:00:56.175,0:00:56.800
#要的
Sure

0:01:24.950,0:01:26.750
#好啦 这个我们已经焯过水啦
Ok. We've blanched this

0:01:26.825,0:01:29.550
#直接把它放到凉水里面去泡一下
Let's soak it in cold water now

0:01:30.975,0:01:35.575
#这样泡着它才不会变黄
In this way, it doesn't turn yellow

0:01:36.150,0:01:38.325
#好啦 现在我们来切点肉
Ok. Now let's cut some meat

0:01:40.525,0:01:43.250
#这个是五花肉先把它的皮去掉
Remove the skin of the pork belly first

0:01:45.600,0:01:48.050
#然后我们把这个猪肉先切碎
Then cut the pork into slices first

0:01:48.450,0:01:52.450
#切碎了之后再来剁成肉末
and mince it later

0:01:53.550,0:01:56.585
#我们现在换双刀一起来把它剁一下
Let's use two cleavers together to chop it

0:01:57.525,0:02:00.575
#剁得稍微细一些
Mince into fine pieces

0:02:01.500,0:02:03.750
#我们这个肉还是最好用刀来剁
It's better to mince the meat with cleavers

0:02:03.825,0:02:08.450
#刀剁出来的会比料理机搅碎的要好一些
The meat minced with cleavers is better than that minced with a grinder

0:02:11.400,0:02:13.450
#好啦 我们这个肉就已经剁好啦
Ok. Now we've minced the meat

0:02:13.850,0:02:16.950
#现在把它拿出来码一下味
It's time to season it

0:02:18.100,0:02:19.275
#加一点点盐
Add a bit salt

0:02:20.300,0:02:21.575
#然后加点胡椒粉
Some ground pepper

0:02:23.075,0:02:24.650
#再加一点酱油
Some light soy sauce

0:02:26.400,0:02:27.800
#然后加一点蚝油
Then some oyster sauce

0:02:31.425,0:02:33.400
#再来加一点老抽调一下色
And some dark soy sauce for the color

0:02:36.000,0:02:38.050
#好啦 加了这些之后把它拌匀
Done. Mix it up after adding all these

0:02:40.962,0:02:43.600
#让这个盐充分的融合进去
To let the salt dissolve into the meat

0:02:43.850,0:02:45.400
#打出一些胶质出来
Stir it until you feel some gel-like stuff #请检查这里

0:02:46.900,0:02:49.400
#好 这个上劲了之后我们打一个鸡蛋进去
Ok. After the meat becomes sticky, add an egg into the bowl #这里上劲感觉不仅是粘，但是如果翻译成tough或者elastic之类好像也有点怪

0:02:52.875,0:02:56.050
#打鸡蛋的话就让这个肉更嫩更有质感
Adding an egg makes the meat more tender and textured

0:02:57.175,0:02:57.950
#给它拌匀
Mix it up again

0:03:02.450,0:03:02.775
#好
Done

0:03:05.075,0:03:06.950
#然后我们再放一点淀粉
Then add some starch

0:03:09.025,0:03:11.950
#这个淀粉可以稍微的多一点点
We can add a bit more starch

0:03:13.000,0:03:16.325
#因为要让这个肉重新回到一个粘手的一个状态
Because we need to make the meat sticky again

0:03:18.050,0:03:20.375
#你看嘛 马上就粘手了
See? It becomes sticky immediately

0:03:21.650,0:03:22.025
#是不是
Right?

0:03:22.550,0:03:23.025
#是啊
Yeah

0:03:25.375,0:03:26.625
#好 我们这个搅好啦
Ok. Now we are done with the mixing job

0:03:26.625,0:03:29.400
#然后我们把这个苦瓜倒出来沥一下水
Then let's pour out the bitter gourd and drain the water

0:03:31.175,0:03:34.375
#好啦现在我们来上一下干淀粉
Ok. Now apply some dry starch

0:03:34.650,0:03:36.875
#我们先把这个干淀粉往中间抹一抹
Firstly apply some dry starch into the middle

0:03:37.250,0:03:40.825
#它这个待会儿就可以很轻松的把肉粘上去了
Such that we can easily stuff the meat later

0:03:45.800,0:03:48.175
#所说我们农村人整的东西没得那么好吃的
That's why the food in the countryside is not so delicious

0:03:48.275,0:03:49.825
#你看你这个好麻烦哦
Look. Your dish is so complicated

0:03:51.100,0:03:53.775
#然后这个盆里面的淀粉我们不要丢
Also, don't throw away the starch in this bowl

0:03:54.725,0:03:57.050
#给它再放一点进去铺一下下面
Add some more starch to cover its bottom

0:03:57.875,0:03:59.000
#给它铺在底下
Cover the bottom with the starch

0:04:00.250,0:04:01.523
#然后这下又反过来
Then we exchange these two bowls

0:04:01.523,0:04:03.450
#看嘛 看好麻烦嘛
See? So complicated

0:04:03.700,0:04:05.550
#反过来又放肉进去
Exchange them and stuff the meat into the gourd

0:04:05.625,0:04:06.200
#是啊
Yep

0:04:06.825,0:04:07.375
#这样子
Like this

0:04:07.875,0:04:09.825
#肉拿起来往中间放
Take some meat and stuff into the center

0:04:11.075,0:04:11.825
#往中间放
Stuff into the center

0:04:12.400,0:04:17.250
#放了肉之后再粘点淀粉
After stuffing, apply some more starch

0:04:19.650,0:04:21.650
#两边都粘上淀粉就可以了
Apply starch to both sides

0:04:21.900,0:04:23.400
#粘好了就这样放下去
Then just leave it there like this

0:04:23.800,0:04:26.150
#为什么这下面我要垫粉呢
Why did I put some starch here?

0:04:26.175,0:04:29.100
#就是因为这样放下去了之后就不会粘盘子
In this way, the meat won't stick to the plate

0:04:29.575,0:04:30.850
#就是这个原因
That's the reason

0:04:31.650,0:04:33.275
#我整一个来试一下
Let me have a try

0:04:33.275,0:04:34.625
#嗯 可以啊 
Ok. Sure

0:04:38.625,0:04:39.250
#怎么样嘛
How is it?

0:04:40.300,0:04:41.900
#这边再给它撒点淀粉
Apply some starch on this side

0:04:42.500,0:04:43.375
#好 抹一下
Ok. Smear it

0:04:44.800,0:04:47.400
#嗯 四伯爷做的不错
Good job, uncle

0:04:47.800,0:04:49.825
#这边感觉淀粉少了点
I think the starch on this side is not enough

0:04:49.975,0:04:51.875
#少了不关事这下面还垫得有
Don't worry. There's more at the bottom

0:04:51.975,0:04:52.300
#要得呀
Ok

0:04:52.425,0:04:52.800
#不关事
It doesn't matter

0:04:53.225,0:04:57.975
#四伯爷除了杀猪那些还是多做些美食撒
Uncle, besides butchering pigs, what about cooking more delicious food?

0:04:58.250,0:05:02.200
#我一个杀猪匠又何尝不想当个美食家嘛
As a butcher, why would I refuse to be a connoisseur?

0:05:02.450,0:05:06.175
#我当个美食家的话我出去卖肉都要好卖点
Were I a connoisseur, I'd be able to sell more pork

0:05:06.225,0:05:08.675
#给别人说这个肉该怎么做来吃
I'd tell my customers how to cook this cut of pork

0:05:08.825,0:05:10.125
#那个肉该怎么做来吃
and how to cook that cut of pork

0:05:10.500,0:05:11.775
#我的肉都要好卖得多
My pork will definitely sell better

0:05:12.525,0:05:13.400
#嗯 就是
Yeah. Sure

0:05:14.350,0:05:16.750
#好啦 现在我们来调一个汁 简单的
Ok. Now let's make a sauce. A simple one

0:05:17.250,0:05:19.560
#放一点点盐 盐不能太多一点点就可以了
A bit salt. Don't add too much; a little salt will do the job

0:05:19.775,0:05:21.125
#然后再放一点白糖
Then add some sugar

0:05:21.425,0:05:22.450
#放一点点胡椒粉
A bit ground pepper

0:05:24.375,0:05:25.575
#再放一点点料酒
Some Chinese cooking wine

0:05:26.225,0:05:28.650
#还要放一点生抽酱油
And some light soy sauce

0:05:30.400,0:05:32.275
#最后加一点蚝油
And some oyster sauce

0:05:36.025,0:05:37.800
#我们再加一点清水
Add some water as well

0:05:39.750,0:05:41.800
#最后加一点淀粉搅拌一下
Finally, add some starch and stir it

0:05:42.025,0:05:44.200
#这个汁就调好了
The sauce is ready to go

0:05:45.200,0:05:49.000
#待会儿我们这个苦瓜两边煎熟了之后
After frying both sides of the bitter gourd

0:05:49.000,0:05:51.300
#直接倒这个进去收汁就可以出菜了
Pour this sauce into the wok, thicken it, and the dish is ready to serve!

0:05:51.350,0:05:52.900
#特别简单的一道菜
This dish is really simple

0:06:24.356,0:06:26.475
#我们到这一步的时候就慢慢给它煎
At this stage, fry it slowly

0:06:27.425,0:06:31.900
#煎到这一面熟了之后再用筷子把它翻过来再煎另一面
When one side is well cooked, flip it with chopsticks and fry the other side

0:06:39.025,0:06:42.300
#好 这面煎香了之后我们用筷子把它翻过来
Ok. Now this side smells good. Let's flip them with chopsticks 

0:06:53.900,0:06:56.150
#好 翻过来之后我们又继续煎
Ok. Continue frying the other side

0:06:56.975,0:06:59.175
#煎到它熟香为止
Until it is well cooked and smells nice

0:07:08.300,0:07:11.725
#好啦 感觉到这个有点焦香焦香的时候
Ok. When you smell a pleasant burnt scent

0:07:11.825,0:07:14.125
#然后我们再给它翻过来看一下
Flip it over again and take a look

0:07:17.000,0:07:18.625
#哇 已经煎得金黄了
Wow. It now looks gold

0:07:21.025,0:07:22.100
#再给它翻一下
Flip it again

0:07:28.375,0:07:30.725
#好啦 我们最后再煎2分钟
Okay. Fry for the last two more minutes

0:07:35.775,0:07:37.075
#我们这个已经完全煎好啦
This is now completely done

0:07:37.225,0:07:39.175
#现在把多余的油倒一点出来
Now let's pour out some excess oil

0:07:45.775,0:07:49.700
#然后我们把这个汁倒下去
Then add the sauce into the wok

0:07:58.275,0:08:01.650
#还是继续小火把这个汁水收浓就可以了
Still, use low heat to thicken the sauce

0:08:08.675,0:08:11.225
#好 轻轻的翻一下就可以了
Ok. Just flip it again

0:08:13.700,0:08:15.150
#好 可以上菜啦
Yeah. Ready to serve!

0:08:20.075,0:08:22.525
#看着摆起是安逸
Looks nice when you present them on the plate!

0:08:23.250,0:08:24.450
#亮增增的
Shiny and bright

0:08:24.650,0:08:25.800
#香味你闻到没
Can you smell the aroma?

0:08:26.050,0:08:26.850
#闻到了
Yeah

0:08:31.400,0:08:32.525
#夹嘛 四伯爷
Pick one up, uncle

0:08:32.650,0:08:34.750
#这种做法你在哪里学到的啊
Where did you learn how to cook this?

0:08:35.050,0:08:37.600
#在外面跑江湖的时候学到的
When I was traveling around and trying to make a living out there

0:08:38.025,0:08:42.027
#哦 以后我还是出去跑哈江湖看学得到这些技术不哦
Oh. I think I also need to travel around and see if I can learn these skills

0:08:43.126,0:08:43.500
#可以啊
Sure

0:08:46.784,0:08:48.748
#嗯 还有一点甜
Hmm. It's even a bit sweet

0:08:48.915,0:08:49.267
#是不哦
Isn't it?

0:08:49.527,0:08:49.879
#是啊
Yes

0:08:50.138,0:08:51.955
#我还说苦 没想到还有点甜
I thought it would be bitter, but didn't expect to be sweet

0:08:53.734,0:08:54.717
#加了点白糖都嘛
I added some sugar

0:08:55.162,0:08:56.218
#也有点苦
A little bitter too

0:08:57.738,0:08:59.351
#其实这样做的话比较香
Actually it tastes better in this way

0:08:59.369,0:09:00.389
#煎出来的更香
Tastes better if fried slowly

0:09:00.834,0:09:03.632
#但是在我们饭店里面一般是直接下去炸
But in restaurants, we usually just deep-fry it

0:09:03.948,0:09:05.505
#或者是放到蒸柜里面蒸
Or steam it in a steamer

0:09:06.042,0:09:08.248
#如果是蒸的话就颜色特别好看
It looks really nice if steamed

0:09:08.248,0:09:10.417
#但是不香很苦
But not tasty. It'll be very bitter

0:09:11.751,0:09:13.382
#我们这个煎出来的虽然说
The fried dish...

0:09:13.642,0:09:14.717
#有点黄黄的
though looks brown in color

0:09:15.106,0:09:18.665
#但是吃起来绝对很香绝对下饭
But is absolutely tasty and goes well with rice

0:09:19.388,0:09:21.853
#嗯 安逸好香哦
Hmm. Nice! So tasty

0:09:23.076,0:09:24.986
#这种做法我还是第一次吃
This is my first time to taste it

0:09:24.986,0:09:26.061
#你吃在嘴里是什么感受嘛
How do you like it?

0:09:26.246,0:09:27.303
#哎呀吃起安逸
Damn good. So nice

0:09:28.044,0:09:29.341
#那个味道说不出来
I can't describe the flavor precisely

0:09:31.288,0:09:32.048
#说不出来
Can't describe?

0:09:32.103,0:09:32.493
#嗯
Yes

0:09:33.215,0:09:34.309
#又有点甜
It's a bit sweet

0:09:35.143,0:09:36.292
#又有点苦
and a little bitter

0:09:36.292,0:09:37.572
#就是好吃嘛
Anyway, it's delicious

0:09:37.812,0:09:38.776
#又有点香
And somewhat tasty

0:09:39.239,0:09:43.039
#嘿嘿 还不好总结这个味道
Well. It's hard to summarize the taste

0:09:46.376,0:09:47.062
#安逸
Nice!

0:09:47.284,0:09:48.693
#这个苦瓜吃起还有点脆
The bitter gourd is a little crunchy

0:09:48.730,0:09:49.657
#嗯 
Yeah

0:09:51.473,0:09:53.456
#这个吃了好下火的
This dish is healthy. It will clear out your 'internal heat'

0:09:53.549,0:09:55.662
#我晓得这个苦瓜吃了好
I know it's good for the health

0:09:56.867,0:09:58.164
#我这个才漂亮
This one here is beautiful

0:09:59.518,0:09:59.833
#看嘛
Look

0:09:59.870,0:10:01.000
#这个是你做的
Yeah. You made this one

0:10:01.241,0:10:02.187
#看好安逸嘛
Look. It's so nice

0:10:04.911,0:10:06.227
#好 本期视频就到这里啦
Ok. That's the end of this video

0:10:06.339,0:10:06.784
#拜拜
Bye-bye!

0:10:08.489,0:10:09.712
#好吃 我去添饭
Tasty. Let me get some rice
