### ISSUE TITLE
【美食作家王刚】泥鳅豆腐汤 - https://youtu.be/Lq6ZQE46uq0

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1085]
**视频链接**：https://youtu.be/Lq6ZQE46uq0

视频时长7:27，预计发布时间为北京时间5月29日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“泥鳅豆腐汤”的浓白做法，味道鲜美营养丰富，学习起来

简介
大家好，今天来做一个“泥鳅豆腐汤”，非常鲜美，并且营养丰富。做鱼汤就一定要浓白，其中的秘诀就是煎鱼，并且像泥鳅这类脂肪非常少的鱼在煎的时候加入一些猪油可以使汤更加的浓白（其中原因是由于油脂的乳化反应）大家掌握好这个小技巧一定在家也能做出像酒店一样浓郁鲜美的鱼汤。如果想看后厨教学版本的朋友可以点击链接：https://www.youtube.com/watch?v=phD1ZfMaFJ8&t=10s

字幕
0:00:00.350,0:00:01.050
哈喽大家好

0:00:01.275,0:00:03.175
 我伯爷今天肉没有卖完

0:00:03.225,0:00:06.500
然后用他的猪肉去换了泥鳅

0:00:07.100,0:00:09.025
换了1斤泥鳅

0:00:09.225,0:00:11.075
拿1斤肉换1斤泥鳅

0:00:11.175,0:00:12.075
我没吃亏

0:00:12.100,0:00:15.825
上次用猪脚换甲鱼我吃了点亏

0:00:15.825,0:00:18.625
这次我换的就过称两头价

0:00:19.400,0:00:22.475
这个泥鳅我伯爷从来没有吃过泥鳅汤

0:00:22.700,0:00:24.450
所以今天准备1块豆腐

0:00:24.648,0:00:26.023
这块豆腐是人家送我的

0:00:26.375,0:00:27.225
煮一个汤

0:00:28.525,0:00:30.225
好我们现在来处理这个泥鳅

0:00:31.050,0:00:32.425
把泥鳅给它抓出来

0:00:32.500,0:00:33.450
轻轻的放下去

0:00:34.200,0:00:35.675
然后稍微按它一下

0:00:36.150,0:00:37.525
把它的头剁掉

0:00:38.900,0:00:40.750
剁掉了头之后它就不会动了

0:00:41.075,0:00:44.100
然后我们用刀压住它的尾巴

0:00:45.150,0:00:46.925
这样子用刀压住它的尾巴

0:00:47.475,0:00:49.900
 这样子给它往前面挤

0:00:50.425,0:00:51.025
挤压

0:00:51.350,0:00:58.350
通过挤压它里面的肠子和胆就会掉出来

0:00:58.650,0:00:59.625
这样子就可以啦

0:01:00.525,0:01:02.450
这样子就是它的内脏

0:01:04.175,0:01:05.750
好 我们来看一下第二条

0:01:06.675,0:01:07.775
再杀一条看一下

0:01:09.825,0:01:11.450
把它的头剁掉

0:01:12.225,0:01:15.500
然后用刀压住它的尾巴

0:01:17.275,0:01:17.925
就可以啦

0:01:18.625,0:01:20.425
挤出来的蛋的话就不要吧

0:01:20.500,0:01:21.204
要不要这个蛋

0:01:21.250,0:01:22.875
不要 没有多少点

0:01:23.200,0:01:24.050
一点点不要了

0:01:25.825,0:01:27.425
好 我们来看一下第三条

0:01:29.425,0:01:31.600
首先不要动它

0:01:32.175,0:01:33.300
让它安静下来

0:01:33.425,0:01:34.850
然后切掉它的头

0:01:38.325,0:01:39.600
它好像有一点不安

0:01:40.250,0:01:42.175
还有点顽固这条泥鳅

0:01:44.200,0:01:44.980
切掉它的头

0:01:44.980,0:01:48.600
然后这边用菜刀压住它的尾巴

0:01:49.050,0:01:50.325
这样子往前面挤

0:01:53.325,0:01:53.950
可以啦

0:01:54.425,0:01:57.275
然后没有挤出来的我们再压住这里

0:01:58.450,0:01:59.450
这样一拉就掉了

0:01:59.825,0:02:01.225
我觉得这个籽还是要到

0:02:01.225,0:02:03.100
不要 你这点不好吃

0:02:03.700,0:02:06.175
要到嘛万一多呢

0:02:06.225,0:02:07.525
要得也可以啊

0:02:15.443,0:02:17.600
好啦 我们这个泥鳅就处理好啦

0:02:17.800,0:02:20.625
本来说不要这个蛋的结果每一条好像都有蛋

0:02:20.625,0:02:21.925
然后我就把它留起来了

0:02:22.250,0:02:23.800
现在来准备一些辅料

0:02:25.500,0:02:26.350
先切一块姜

0:02:29.400,0:02:33.775
然后我们再准备几根小葱

0:02:34.325,0:02:35.625
把它挽起来就可以了

0:02:35.800,0:02:39.550
到时候汤煮好了之后就把这个葱捞出来就行了

0:02:43.275,0:02:45.125
然后我们来把这块豆腐切了

0:02:45.550,0:02:46.375
好大哦这块豆腐

0:02:46.500,0:02:47.425
估计有1斤多

0:02:48.050,0:02:49.225
肯定是1斤多

0:02:50.775,0:02:52.250
切成厚片就可以

0:02:57.825,0:02:59.650
切好大一块的哦

0:03:00.225,0:03:02.100
煮汤的要久煮一会儿

0:03:02.200,0:03:04.500
要的啊 这样吃起爽口点

0:03:05.875,0:03:08.300
我们这个豆腐还是选老豆腐好一点

0:03:08.575,0:03:09.800
老豆腐更香

0:03:12.500,0:03:13.600
好 现在可以了

0:03:13.850,0:03:15.550
帮我拿下葱嘛 可以煮了

0:03:16.600,0:03:17.425
可以开工了

0:03:21.900,0:03:25.205
我们一般煮这个鱼汤先准备开水

0:03:25.500,0:03:27.775
煮鱼汤就成功一半了

0:05:10.028,0:05:10.896
可以了四伯爷

0:05:13.326,0:05:15.104
诶呀 这个汤好白哦

0:05:15.159,0:05:17.338
加不加鸡精呢

0:05:17.531,0:05:18.379
不加鸡精

0:05:25.284,0:05:26.711
最后再撒一点葱花

0:05:28.621,0:05:28.910
好

0:05:30.260,0:05:32.092
来了 汤来了

0:05:34.214,0:05:36.837
这汤看这个颜色估计喝起安逸哦

0:05:37.357,0:05:39.247
我们这个汤是黄的

0:05:39.556,0:05:45.091
是为什么呢 是因为这个汤里面有泥鳅的蛋

0:05:45.458,0:05:47.753
下锅煎了就变黄了

0:05:48.023,0:05:50.279
如果是平时的话我们这个汤应该是白的

0:05:50.665,0:05:52.131
所以这个也不影响

0:05:54.792,0:05:56.277
品尝哈这个汤看

0:05:57.704,0:05:58.997
烫哦 小心

0:06:00.115,0:06:01.002
刚刚煮出来的

0:06:03.298,0:06:04.551
舌头给你烫个泡

0:06:05.265,0:06:05.805
好喝

0:06:06.788,0:06:07.830
就是太烫了

0:06:09.951,0:06:10.838
嗯 可以

0:06:10.858,0:06:12.671
这个汤的话稍微淡一点点

0:06:13.269,0:06:15.988
如果大家比较介意的话可以放咸一点

0:06:16.624,0:06:17.145
鲜撒

0:06:17.415,0:06:18.495
吃起不晓得好安逸

0:06:19.614,0:06:20.520
伯爷（汤）鲜不鲜

0:06:20.520,0:06:25.728
鲜 我就是说下面拿这个汤冒起才安逸

0:06:25.805,0:06:28.968
我们四川人只要是好喝的汤都可以拿来下面条

0:06:29.199,0:06:30.067
鲜就可以了

0:06:33.230,0:06:37.878
还有我们这个泥鳅豆腐汤特别适合一些体质比较虚弱的人喝

0:06:38.032,0:06:39.961
这个特别的好

0:06:40.135,0:06:41.832
这个汤的营养价值非常高

0:06:42.892,0:06:47.444
如果是做泥鳅豆腐汤的话我不建议大家用盐去把泥鳅腌死

0:06:47.483,0:06:48.775
或者是用开水烫死

0:06:49.623,0:06:54.580
就直接是这样下去把它那层粘液煎香

0:06:54.754,0:06:56.142
煎香了之后再放开水下去煮

0:06:56.682,0:06:57.704
好烫哦

0:06:58.129,0:06:59.845
你喝那么快咋子嘛

0:07:00.617,0:07:01.504
太烫了

0:07:02.352,0:07:03.278
你好慌啊

0:07:03.683,0:07:04.358
我去端饭过来

0:07:07.174,0:07:08.196
哎呀 喝起安逸

0:07:14.889,0:07:16.394
烫得很 我都整出汗水了

0:07:17.087,0:07:19.633
你还是慢慢喝嘛不要急嘛

0:07:20.366,0:07:23.201
你看到我喝那么快你还是跟着喝那么快

0:07:23.722,0:07:25.033
还有这里

0:07:25.188,0:07:26.653
晓得还有半瓷盆


```

**Comment by WuStevenShengyang** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“泥鳅豆腐汤”的浓白做法，味道鲜美营养丰富，学习起来
Chef Wang shares: Loach Tofu Soup. Delicous and nutritious white broth.

简介
大家好，今天来做一个“泥鳅豆腐汤”，非常鲜美，并且营养丰富。做鱼汤就一定要浓白，其中的秘诀就是煎鱼，并且像泥鳅这类脂肪非常少的鱼在煎的时候加入一些猪油可以使汤更加的浓白（其中原因是由于油脂的乳化反应）大家掌握好这个小技巧一定在家也能做出像酒店一样浓郁鲜美的鱼汤。如果想看后厨教学版本的朋友可以点击链接：https://www.youtube.com/watch?v=phD1ZfMaFJ8&t=10s
Hi, let's make a loach tofu soup today. It is delicious, fragrant, and nutritious. Fish broth has to be white. The key is searing the fish. Loach typically contains little fat, so we can add some lard to make the soup white. If you can master this skill you can make out-of-the-restaurant fish soup at home. If you want to see me in the kitchen, click on the link.

字幕
0:00:00.350,0:00:01.050
哈喽大家好
Hey guys,

0:00:01.275,0:00:03.175
 我伯爷今天肉没有卖完
My uncle had some spare meat today at his butcher shop.

0:00:03.225,0:00:06.500
然后用他的猪肉去换了泥鳅
So he used some pork to trade for some loach.

0:00:07.100,0:00:09.025
换了1斤泥鳅
I got 1 jin (0.5kg) of loach.

0:00:09.225,0:00:11.075
拿1斤肉换1斤泥鳅
1 jin (0.5kg) of pork for the same amount of loach.

0:00:11.175,0:00:12.075
我没吃亏
I am happy with that.

0:00:12.100,0:00:15.825
上次用猪脚换甲鱼我吃了点亏
Last time trading pork legs with soft-shelled turtles was not a smart choice.

0:00:15.825,0:00:18.625
这次我换的就过称两头价
But this time, they are even in price.

0:00:19.400,0:00:22.475
这个泥鳅我伯爷从来没有吃过泥鳅汤
My uncle had never tried loach soup before.

0:00:22.700,0:00:24.450
所以今天准备1块豆腐
We need a chunk of tofu.

0:00:24.648,0:00:26.023
这块豆腐是人家送我的
A friend gave this tofu to me.

0:00:26.375,0:00:27.225
煮一个汤
We will use this to make our soup.

0:00:28.525,0:00:30.225
好我们现在来处理这个泥鳅
Now let's process this loach.

0:00:31.050,0:00:32.425
把泥鳅给它抓出来
We need to take it out.

0:00:32.500,0:00:33.450
轻轻的放下去
Lay it down gently.

0:00:34.200,0:00:35.675
然后稍微按它一下
And press on it.

0:00:36.150,0:00:37.525
把它的头剁掉
Chop off its head.

0:00:38.900,0:00:40.750
剁掉了头之后它就不会动了
Now it's not moving anymore.

0:00:41.075,0:00:44.100
然后我们用刀压住它的尾巴
Then, we press on its tail with our knife.

0:00:45.150,0:00:46.925
这样子用刀压住它的尾巴
Like this.

0:00:47.475,0:00:49.900
 这样子给它往前面挤
and push forward.

0:00:50.425,0:00:51.025
挤压
Push and squeeze.

0:00:51.350,0:00:58.350
通过挤压它里面的肠子和胆就会掉出来
We will be able to squeeze out the guts.

0:00:58.650,0:00:59.625
这样子就可以啦
Like this.

0:01:00.525,0:01:02.450
这样子就是它的内脏
Those are its guts.

0:01:04.175,0:01:05.750
好 我们来看一下第二条
Now let's move on to the next one.

0:01:06.675,0:01:07.775
再杀一条看一下
Let's do it one more time.

0:01:09.825,0:01:11.450
把它的头剁掉
Chop off the head,

0:01:12.225,0:01:15.500
然后用刀压住它的尾巴
push on the tail,

0:01:17.275,0:01:17.925
就可以啦
and it's done.

0:01:18.625,0:01:20.425
挤出来的蛋的话就不要吧
What about the eggs that just came out.

0:01:20.500,0:01:21.204
要不要这个蛋
Do we need them?

0:01:21.250,0:01:22.875
不要 没有多少点
No, since there are not much.

0:01:23.200,0:01:24.050
一点点不要了
That little amount are not important.

0:01:25.825,0:01:27.425
好 我们来看一下第三条
Now, let's move on to the third one.

0:01:29.425,0:01:31.600
首先不要动它
Don't touch it initially.

0:01:32.175,0:01:33.300
让它安静下来
Just wait for it to rest.

0:01:33.425,0:01:34.850
然后切掉它的头
And then chop off its head.

0:01:38.325,0:01:39.600
它好像有一点不安
It seems a little agitated.

0:01:40.250,0:01:42.175
还有点顽固这条泥鳅
It's stubborn.

0:01:44.200,0:01:44.980
切掉它的头
Chop off its head.

0:01:44.980,0:01:48.600
然后这边用菜刀压住它的尾巴
Press on its tail with the knife.

0:01:49.050,0:01:50.325
这样子往前面挤
And squeeze forward.

0:01:53.325,0:01:53.950
可以啦
Done!

0:01:54.425,0:01:57.275
然后没有挤出来的我们再压住这里
If there are still guts remain, we can squeeze it again.

0:01:58.450,0:01:59.450
这样一拉就掉了
And pull it.

0:01:59.825,0:02:01.225
我觉得这个籽还是要到
I feel like we still need those eggs.

0:02:01.225,0:02:03.100
不要 你这点不好吃
Actually no, that little are not good.

0:02:03.700,0:02:06.175
要到嘛万一多呢
What if there are a lot.

0:02:06.225,0:02:07.525
要得也可以啊
Then we can use them.

0:02:15.443,0:02:17.600
好啦 我们这个泥鳅就处理好啦
So we are down processing the loachs.

0:02:17.800,0:02:20.625
本来说不要这个蛋的结果每一条好像都有蛋
I said not to use the eggs, but seems like there are eggs in every loach.

0:02:20.625,0:02:21.925
然后我就把它留起来了
So I collected them.

0:02:22.250,0:02:23.800
现在来准备一些辅料
Now let's prepare some other ingredient.

0:02:25.500,0:02:26.350
先切一块姜
First, we will slice a chunk of ginger.

0:02:29.400,0:02:33.775
然后我们再准备几根小葱
And some green onions.

0:02:34.325,0:02:35.625
把它挽起来就可以了
Just twist the green onions like this.

0:02:35.800,0:02:39.550
到时候汤煮好了之后就把这个葱捞出来就行了
We will take it out after the soup is done.

0:02:43.275,0:02:45.125
然后我们来把这块豆腐切了
Now, let's slice the tofu.

0:02:45.550,0:02:46.375
好大哦这块豆腐
This tofu is huge.

0:02:46.500,0:02:47.425
估计有1斤多
It's like 1 jin (0.5kg).

0:02:48.050,0:02:49.225
肯定是1斤多
For sure.

0:02:50.775,0:02:52.250
切成厚片就可以
We can just slice the tofu into thick slices.

0:02:57.825,0:02:59.650
切好大一块的哦
That's big.

0:03:00.225,0:03:02.100
煮汤的要久煮一会儿
The soup needs to be cooked for a long time.

0:03:02.200,0:03:04.500
要的啊 这样吃起爽口点
So it will taste better.

0:03:05.875,0:03:08.300
我们这个豆腐还是选老豆腐好一点
As for the tofu, we better use firm tofu.

0:03:08.575,0:03:09.800
老豆腐更香
It's more fragrant.

0:03:12.500,0:03:13.600
好 现在可以了
Ok, we are done.

0:03:13.850,0:03:15.550
帮我拿下葱嘛 可以煮了
Can you hand me the green onions. We can start cooking.

0:03:16.600,0:03:17.425
可以开工了
Let's do it.

0:03:21.900,0:03:25.205
我们一般煮这个鱼汤先准备开水
Typically, we use boiling water to make fish soup.

0:03:25.500,0:03:27.775
煮鱼汤就成功一半了
Now we are half way to success.

0:05:10.028,0:05:10.896
可以了四伯爷
Uncle, it's good.

0:05:13.326,0:05:15.104
诶呀 这个汤好白哦
This soup is so white.

0:05:15.159,0:05:17.338
加不加鸡精呢
Do we need chicken bouillon powder.

0:05:17.531,0:05:18.379
不加鸡精
No.

0:05:25.284,0:05:26.711
最后再撒一点葱花
Now let's sprinkle some chopped green onions on top.

0:05:28.621,0:05:28.910
好
Done!

0:05:30.260,0:05:32.092
来了 汤来了
Here comes the soup.

0:05:34.214,0:05:36.837
这汤看这个颜色估计喝起安逸哦
I can tell this soup is going to be tasty just from its color.

0:05:37.357,0:05:39.247
我们这个汤是黄的
It's kind of yellow.

0:05:39.556,0:05:45.091
是为什么呢 是因为这个汤里面有泥鳅的蛋
Why? Because we added the eggs.

0:05:45.458,0:05:47.753
下锅煎了就变黄了
After we seared the eggs they turn yellow.

0:05:48.023,0:05:50.279
如果是平时的话我们这个汤应该是白的
It would have been white without the eggs.

0:05:50.665,0:05:52.131
所以这个也不影响
But it's not a big deal.

0:05:54.792,0:05:56.277
品尝哈这个汤看
Try it.

0:05:57.704,0:05:58.997
烫哦 小心
Oh, it's hot.

0:06:00.115,0:06:01.002
刚刚煮出来的
Freshly out of the pot.

0:06:03.298,0:06:04.551
舌头给你烫个泡
It almost burned by tougue

0:06:05.265,0:06:05.805
好喝
Delicious.

0:06:06.788,0:06:07.830
就是太烫了
But it's just too hot.

0:06:09.951,0:06:10.838
嗯 可以
Em, that's good.

0:06:10.858,0:06:12.671
这个汤的话稍微淡一点点
The taste is a little light.

0:06:13.269,0:06:15.988
如果大家比较介意的话可以放咸一点
If you want, you can add more salt.

0:06:16.624,0:06:17.145
鲜撒
So good.

0:06:17.415,0:06:18.495
吃起不晓得好安逸
Feels good.

0:06:19.614,0:06:20.520
伯爷（汤）鲜不鲜
Uncle, isn't it tasty and fresh.

0:06:20.520,0:06:25.728
鲜 我就是说下面拿这个汤冒起才安逸
Yea, it will be even better to serve this soup with some noodles.

0:06:25.805,0:06:28.968
我们四川人只要是好喝的汤都可以拿来下面条
In Sichuan, we love noodle soup.

0:06:29.199,0:06:30.067
鲜就可以了
Fresh is good.

0:06:33.230,0:06:37.878
还有我们这个泥鳅豆腐汤特别适合一些体质比较虚弱的人喝
This soup is also good for people with weaker health.

0:06:38.032,0:06:39.961
这个特别的好
So good.

0:06:40.135,0:06:41.832
这个汤的营养价值非常高
This soup is highly nutritious.

0:06:42.892,0:06:47.444
如果是做泥鳅豆腐汤的话我不建议大家用盐去把泥鳅腌死
I don't suggest using salt to kill the loach,

0:06:47.483,0:06:48.775
或者是用开水烫死
nor using boiling water.

0:06:49.623,0:06:54.580
就直接是这样下去把它那层粘液煎香
Just put it in like this and sear until fragrant.

0:06:54.754,0:06:56.142
煎香了之后再放开水下去煮
Then we add water.

0:06:56.682,0:06:57.704
好烫哦
It's so hot.

0:06:58.129,0:06:59.845
你喝那么快咋子嘛
Why are you drinking so fast.

0:07:00.617,0:07:01.504
太烫了
It's really hot.

0:07:02.352,0:07:03.278
你好慌啊
You are in such a rush.

0:07:03.683,0:07:04.358
我去端饭过来
I will go get a bowl of rice.

0:07:07.174,0:07:08.196
哎呀 喝起安逸
Oh, so good.

0:07:14.889,0:07:16.394
烫得很 我都整出汗水了
It's hot. I'm even sweating.

0:07:17.087,0:07:19.633
你还是慢慢喝嘛不要急嘛
Slow it down man.

0:07:20.366,0:07:23.201
你看到我喝那么快你还是跟着喝那么快
You are drinking so fast because you see me drinking fast.

0:07:23.722,0:07:25.033
还有这里
There are more here.

0:07:25.188,0:07:26.653
晓得还有半瓷盆
I know. There are still like half a bowl left.
