### ISSUE TITLE
【美食作家王刚】苦瓜烧鸭 - https://youtu.be/RKGXMv9KYm0

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1090]
**视频链接**：https://youtu.be/RKGXMv9KYm0

视频时长7:12，预计发布时间为北京时间5月30日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“苦瓜烧鸭子”的家常做法，自己喂了一年多的鸭子就是又肥又香！

简介
大家好，自从上次吃了苦瓜酿肉之后四伯一直觉得还想吃苦瓜，虽说苦是有一点苦，但是何尝不是另一种美味！这次来做一道“苦瓜烧鸭”，苦瓜和水禽鸭子都是去火消暑的好食材，特别适合闷热的夏天，也十分推荐给大家。

字幕
0:00:00.362,0:00:01.075
哈喽 大家好

0:00:01.371,0:00:04.673
这个鸭子是我们去年没修房子之前买的鸭苗

0:00:05.068,0:00:05.858
喂到现在

0:00:05.880,0:00:06.659
喂了好久了安四伯爷

0:00:06.725,0:00:09.825
喂了一年多了 去年栽秧子的时候买的嘛

0:00:09.825,0:00:14.550
吃了我们很多粮食长到了应该有五六斤了嘎

0:00:14.550,0:00:15.325
嗯

0:00:15.325,0:00:16.250
五六斤是有的

0:00:16.350,0:00:18.200
就把它宰了 还剩下一半

0:00:18.550,0:00:22.700
这一次我们这半只鸭子用这个苦瓜来烧

0:00:22.937,0:00:26.267
我四伯上次吃那个苦瓜酿肉他觉得挺好吃的

0:00:26.337,0:00:28.767
然后就又用这个苦瓜来烧鸭子

0:00:28.951,0:00:29.659
现在把它剁了

0:00:33.630,0:00:34.989
砍大坨点吗砍小坨点

0:00:34.989,0:00:37.058
大坨点嘛 弄来咋个吃的嘛

0:00:37.363,0:00:39.026
给你烧苦瓜的嘛

0:00:39.310,0:00:40.953
要得 一会烧得耙不哦

0:00:41.622,0:00:42.778
烧得耙

0:00:43.488,0:00:46.531
我们这个上面没得点（鸭）绒毛的

0:00:47.018,0:00:48.336
打整得干干净净的

0:00:48.620,0:00:49.411
香嘎

0:00:49.553,0:00:50.060
是安

0:00:51.987,0:00:54.523
你看这冒油  我们这鸭子你看

0:00:54.929,0:00:56.592
它这个皮里面都在冒油

0:00:58.438,0:01:00.933
鸭肝鸭心一起放进去

0:01:01.683,0:01:04.077
好 我们现在来切这三条苦瓜

0:01:04.279,0:01:05.841
这苦瓜特别的新鲜

0:01:06.146,0:01:08.640
大家可以看一下这个（蒂）感觉是现摘下来的

0:01:08.924,0:01:12.839
应该摘下来只有一天 两天都不到

0:01:14.590,0:01:16.295
这个不是我们的本地苦瓜嘎

0:01:16.295,0:01:16.863
不是的

0:01:17.152,0:01:17.656
好大哦

0:01:18.990,0:01:20.537
这热天吃了苦瓜是最安逸的

0:01:20.625,0:01:21.722
吃了降火嘎

0:01:21.869,0:01:23.920
是啊 这个是清热的

0:01:24.245,0:01:26.154
我们用手就可以把这个抓下来

0:01:27.460,0:01:30.959
如果你们不能吃苦的话这个可以用勺子刮干净一点

0:01:31.288,0:01:33.493
能吃苦的就可以不用刮得那么干净

0:01:34.346,0:01:37.034
有时候苦反而是一种美味 嘎四伯爷

0:01:37.405,0:01:38.109
是安

0:01:38.368,0:01:41.946
我们这个苦瓜既然是烧鸭子这么大坨 那就切大一点

0:01:45.597,0:01:48.248
好 我们现在再切点泡椒

0:01:48.785,0:01:50.398
泡椒是我伯爷自己泡的

0:01:51.306,0:01:53.005
你这个海椒有点辣哦嘎

0:01:53.030,0:01:53.809
当然了

0:01:54.587,0:01:57.664
这个烧苦瓜就是它本身比较苦

0:01:58.035,0:01:59.481
就要多放点辣椒

0:02:00.185,0:02:02.391
烧东西就离不得那姜蒜

0:02:03.595,0:02:06.339
直接给它切成颗粒

0:02:06.876,0:02:07.803
稍微可以大一点

0:02:08.100,0:02:09.786
大蒜一开二就可以了

0:02:12.266,0:02:15.509
最后我们来再准备一块小小的火锅底料

0:02:16.978,0:02:17.942
上一下底味

0:02:20.166,0:02:24.467
如果没有火锅底料的朋友可以放点豆瓣酱加猪油

0:02:24.652,0:02:26.376
一样的可以起到这个效果

0:02:27.692,0:02:29.786
好 四伯爷帮我端哈

0:02:29.786,0:02:30.120
走嘛

0:02:30.139,0:02:30.806
直接弄来烧起

0:02:30.843,0:02:31.288
好

0:02:32.900,0:02:36.607
 首先我们这个鸭子给它放点水进去焯一下

0:02:37.701,0:02:39.277
给它冷水下锅焯一下水

0:02:41.334,0:02:42.724
然后再放一点料酒

0:02:46.802,0:02:50.787
四伯爷你看嘛这个焯水出来这个泡沫要把它打了啦

0:02:55.495,0:02:57.015
这样子都焯好了

0:03:11.102,0:03:12.752
这样子慢慢的给它煎

0:03:13.549,0:03:15.438
把那个鸭子的油给它煎出来

0:03:16.441,0:03:18.572
然后差不多了就放姜蒜在里面

0:03:20.222,0:03:21.278
还有这个泡海椒

0:03:25.690,0:03:27.803
好 现在我们已经差不多要爆香了

0:03:28.470,0:03:30.250
加这个火锅底料下去炒化

0:03:35.069,0:03:36.218
诶呀 好香哦

0:03:37.590,0:03:39.499
加点这个老抽调哈颜色

0:03:40.685,0:03:41.797
颜色给它调深点

0:03:45.208,0:03:46.784
然后我们再放点酱油

0:03:50.954,0:03:52.456
最后再放半瓶啤酒

0:03:57.034,0:03:58.424
再放一点水进去

0:04:02.502,0:04:05.097
然后烧开了火稍微小点

0:04:06.116,0:04:07.247
这样子烧它半小时

0:04:11.825,0:04:14.847
好了 现在我们这个已经烧了40分钟了

0:04:15.384,0:04:16.939
把这个苦瓜放进去了

0:04:19.369,0:04:20.963
苦瓜放进去的时候就开始调味

0:04:22.354,0:04:23.466
少放一点盐

0:04:25.227,0:04:26.246
再放一点白糖

0:04:27.006,0:04:27.803
差不多了

0:04:29.749,0:04:32.381
我们这个苦瓜把它烧熟了大概需要3分钟

0:04:32.808,0:04:35.069
如果你们怕苦的话可以焯一下水

0:04:35.069,0:04:37.182
 这个油烟子好熏人哦

0:04:37.553,0:04:38.331
熏到你了啊

0:04:42.020,0:04:43.985
今天这个苦瓜我就把它烧软一点

0:04:44.448,0:04:45.486
我伯爷他牙口不好

0:04:46.431,0:04:49.564
要是说普通人吃的话现在都可以出锅了

0:04:49.564,0:04:52.326
这个油烟子熏起眼泪都要熏出来

0:04:52.993,0:04:53.938
马上就好了哈

0:04:54.383,0:04:55.532
站远点的

0:04:58.202,0:05:01.075
好 差不多了 可以了

0:05:02.724,0:05:03.484
好香啊

0:05:05.783,0:05:07.191
但是苦瓜烧肉我吃过

0:05:07.636,0:05:12.455
下次给你整个苦瓜汤给你喝 要得不

0:05:12.455,0:05:14.479
苦瓜汤整起害怕苦的要命安

0:05:15.155,0:05:17.642
不得 苦瓜排骨汤好喝得很

0:05:18.976,0:05:19.831
尝哈看嘛四伯爷

0:05:20.582,0:05:21.968
我试哈看烧耙没有

0:05:22.525,0:05:23.886
我先吃一个苦瓜尝一下

0:05:24.287,0:05:26.839
我先整这个大的鸭肉

0:05:27.655,0:05:28.782
苦瓜有点苦哦伯娘

0:05:29.158,0:05:29.844
嗯 不怕

0:05:30.064,0:05:31.722
我没焯水的直接放下去

0:05:33.445,0:05:37.707
嗯 整耙了的 还不苦安这个鸭肉

0:05:38.497,0:05:39.507
但是苦瓜苦哦

0:05:39.507,0:05:40.207
苦瓜苦哦

0:05:41.399,0:05:42.253
鸭肉不苦

0:05:42.305,0:05:43.212
吃坨苦瓜嘛

0:05:43.860,0:05:45.090
我尝一个鸭子看一下

0:05:46.152,0:05:46.787
有点苦

0:05:51.204,0:05:56.570
我们这个苦瓜虽然说很苦 但是吃起来的话比较开胃

0:05:57.349,0:06:02.149
就是苦瓜还有莴笋稍微带点苦的食材

0:06:02.279,0:06:03.762
是非常开胃下饭的

0:06:05.968,0:06:06.524
好吃

0:06:08.804,0:06:09.230
可以

0:06:09.930,0:06:10.393
可以噶 

0:06:10.393,0:06:11.161
苦瓜吃了好得很

0:06:11.713,0:06:12.613
伯娘都晓得

0:06:13.109,0:06:16.469
苦瓜这热天吃了是相当好的它是清热的嘛

0:06:17.287,0:06:17.764
嗯

0:06:18.937,0:06:20.818
很多人都喜欢吃这个苦瓜热天

0:06:23.078,0:06:25.119
所以我们这个鸭子嘛

0:06:26.145,0:06:29.236
鸭子属于水禽然后再烧这个苦瓜

0:06:29.737,0:06:32.193
是相当的开胃 还有比较降火

0:06:36.957,0:06:38.485
好 本期视频就到这里

0:06:38.680,0:06:44.276
大家可以在家里尝试一下用苦瓜煮汤 烧肉 烧鸭子

0:06:45.033,0:06:45.962
还可以烧鸡

0:06:46.756,0:06:48.613
比较开胃 虽然苦

0:06:49.077,0:06:50.849
但是有时候苦也是一种美味嘛

0:06:51.154,0:06:51.912
是不是嘛四伯爷

0:06:53.879,0:06:56.127
本期视频就到这里啦 拜拜

0:06:56.139,0:06:57.067
这个苦瓜也不算很苦

0:06:58.033,0:07:01.759
要那种小个小个的硬的那种才苦

0:07:02.003,0:07:08.185
秋苦瓜 要秋苦瓜烧起更苦 那会儿的又安逸安

0:07:08.283,0:07:09.395
我给你舀饭嘛伯娘

0:07:10.861,0:07:11.606
我给你舀饭


```

**Comment by archerdominique** [comment]
bot, please upload
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“苦瓜烧鸭子”的家常做法，自己喂了一年多的鸭子就是又肥又香！
Chef Wang Gang share with you: Home-style dish "Braised Duck with Bitter Gourd" using the fleshy and flavourful home-raised duck

简介
大家好，自从上次吃了苦瓜酿肉之后四伯一直觉得还想吃苦瓜，虽说苦是有一点苦，但是何尝不是另一种美味！这次来做一道“苦瓜烧鸭”，苦瓜和水禽鸭子都是去火消暑的好食材，特别适合闷热的夏天，也十分推荐给大家。
Hello guys, since last time we had meat-stuffed bitter gourd, my uncle has been looing for more dishes with bitter gourd. A little bitterness is a different kind of enjoyable taste, isn't it? This time I'll make "Braised Duck with Bitter Gourd". Both can help clearing the "internal heat" in our body and avoiding heatstroke, thus extremely ideal in the smotheringly hot summer, and I would recommend you try and cook this dish.

字幕
0:00:00.362,0:00:01.075
哈喽 大家好
Hello guys

0:00:01.371,0:00:04.673
这个鸭子是我们去年没修房子之前买的鸭苗
This duck was once the little duckling we bought last year before we built this house

0:00:05.068,0:00:05.858
喂到现在
It has been feeded until now

0:00:05.880,0:00:06.659
喂了好久了安四伯爷
Uncle, it's been feeded quite a while, right? 

0:00:06.725,0:00:09.825
喂了一年多了 去年栽秧子的时候买的嘛
It's more than a year. Didn't we buy it last year when we planted the seedlings?

0:00:09.825,0:00:14.550
吃了我们很多粮食长到了应该有五六斤了嘎
It has eaten lots of our grains. It should weigh about 5 or 6 "Jin" ("Jin":500g)

0:00:14.550,0:00:15.325
嗯
Um

0:00:15.325,0:00:16.250
五六斤是有的
Should have 5 to 6 Jin, it's weight

0:00:16.350,0:00:18.200
就把它宰了 还剩下一半
when we decided to cook it. We have a half left now

0:00:18.550,0:00:22.700
这一次我们这半只鸭子用这个苦瓜来烧
This time we braise this half of duck with the bitter gourd

0:00:22.937,0:00:26.267
我四伯上次吃那个苦瓜酿肉他觉得挺好吃的
Last time my uncle had the meat-stuffed bitter gourd, he found it quite delicious

0:00:26.337,0:00:28.767
然后就又用这个苦瓜来烧鸭子
So we use bitter gourd again, to braise the duck

0:00:28.951,0:00:29.659
现在把它剁了
Now I chop it into pieces

0:00:33.630,0:00:34.989
砍大坨点吗砍小坨点
Larger lumps or smaller?

0:00:34.989,0:00:37.058
大坨点嘛 弄来咋个吃的嘛
Bigga, how ya gonna cook it? （俺试图翻方言，要是怪怪的就改掉吧哈哈哈哈

0:00:37.363,0:00:39.026
给你烧苦瓜的嘛
To braise the bitter gourd for you

0:00:39.310,0:00:40.953
要得 一会烧得耙不哦
I'd like it. Can it be braised soft and tneder?

0:00:41.622,0:00:42.778
烧得耙
Definitely

0:00:43.488,0:00:46.531
我们这个上面没得点（鸭）绒毛的
We ain't got any feather or hair on this

0:00:47.018,0:00:48.336
打整得干干净净的
So neat and tidy

0:00:48.620,0:00:49.411
香嘎
Flavourful, isn't it?

0:00:49.553,0:00:50.060
是安
Yea

0:00:51.987,0:00:54.523
你看这冒油  我们这鸭子你看
You see this fat, our duck, see

0:00:54.929,0:00:56.592
它这个皮里面都在冒油
Inside its skin the fat is coming out

0:00:58.438,0:01:00.933
鸭肝鸭心一起放进去
Together with the liver and heart

0:01:01.683,0:01:04.077
好 我们现在来切这三条苦瓜
Ok, now I cut these three bitter gourd

0:01:04.279,0:01:05.841
这苦瓜特别的新鲜
They are very fresh

0:01:06.146,0:01:08.640
大家可以看一下这个（蒂）感觉是现摘下来的
You see this stem, it looks freshly-picked

0:01:08.924,0:01:12.839
应该摘下来只有一天 两天都不到
It should be only one day since it's picked, less than two days

0:01:14.590,0:01:16.295
这个不是我们的本地苦瓜嘎
This is not our local product?

0:01:16.295,0:01:16.863
不是的
Nah

0:01:17.152,0:01:17.656
好大哦
It's large

0:01:18.990,0:01:20.537
这热天吃了苦瓜是最安逸的
It's best to eat bitter gourd in this hot weather

0:01:20.625,0:01:21.722
吃了降火嘎
It brings down the "internal heat"

0:01:21.869,0:01:23.920
是啊 这个是清热的
Yeah, this clears the heat

0:01:24.245,0:01:26.154
我们用手就可以把这个抓下来
We can remove this just by our hands

0:01:27.460,0:01:30.959
如果你们不能吃苦的话这个可以用勺子刮干净一点
If you dislike the bitterness you may scrape it all away with a spoon

0:01:31.288,0:01:33.493
能吃苦的就可以不用刮得那么干净
If you like, you don't need to remove it so carefully

0:01:34.346,0:01:37.034
有时候苦反而是一种美味 嘎四伯爷
Sometimes the bitterness is a kind of good taste, isn't it uncle?

0:01:37.405,0:01:38.109
是安
Indeed!

0:01:38.368,0:01:41.946
我们这个苦瓜既然是烧鸭子这么大坨 那就切大一点
Since we're gonna braise the bitter gourd with these large lumps of duck, I cut them into larger pieces

0:01:45.597,0:01:48.248
好 我们现在再切点泡椒
Okay, now we cut some pickled chili

0:01:48.785,0:01:50.398
泡椒是我伯爷自己泡的
My uncle made the pickled chili by himself

0:01:51.306,0:01:53.005
你这个海椒有点辣哦嘎
Your chili is pretty spicy, isn't it?

0:01:53.030,0:01:53.809
当然了
Of course

0:01:54.587,0:01:57.664
这个烧苦瓜就是它本身比较苦
This braised bitter gourd, it taste bitter itself

0:01:58.035,0:01:59.481
就要多放点辣椒
which needs more chili pepper

0:02:00.185,0:02:02.391
烧东西就离不得那姜蒜
Garlic and ginger are indispensable in braised stuff

0:02:03.595,0:02:06.339
直接给它切成颗粒
Cut it directly into pieces

0:02:06.876,0:02:07.803
稍微可以大一点
A bit larger

0:02:08.100,0:02:09.786
大蒜一开二就可以了
Cut the garlic into just two

0:02:12.266,0:02:15.509
最后我们来再准备一块小小的火锅底料
Finally we get a small lump of hot pot soup base

0:02:16.978,0:02:17.942
上一下底味
For the basic taste

0:02:20.166,0:02:24.467
如果没有火锅底料的朋友可以放点豆瓣酱加猪油
If you don't have the base you may use some Doubanjiang (Sichuan bean paste) with pork lard instead

0:02:24.652,0:02:26.376
一样的可以起到这个效果
It will work the same

0:02:27.692,0:02:29.786
好 四伯爷帮我端哈
Okay, uncle help me carry some

0:02:29.786,0:02:30.120
走嘛
Let's go

0:02:30.139,0:02:30.806
直接弄来烧起
directly to cook

0:02:30.843,0:02:31.288
好
Good

0:02:32.900,0:02:36.607
 首先我们这个鸭子给它放点水进去焯一下
First we parboil the duck 

0:02:37.701,0:02:39.277
给它冷水下锅焯一下水
Drop it into the wok when the water is still cool

0:02:41.334,0:02:42.724
然后再放一点料酒
With a little Chinese cooking wine

0:02:46.802,0:02:50.787
四伯爷你看嘛这个焯水出来这个泡沫要把它打了啦
Uncle you see, the scum needs to be removed

0:02:55.495,0:02:57.015
这样子都焯好了
Now the parboiling is done

0:03:11.102,0:03:12.752
这样子慢慢的给它煎
Fry the duck leisurely

0:03:13.549,0:03:15.438
把那个鸭子的油给它煎出来
Until the fat comes out

0:03:16.441,0:03:18.572
然后差不多了就放姜蒜在里面
When it's almost done, drop the garlic and ginger in

0:03:20.222,0:03:21.278
还有这个泡海椒
And this pickled chili

0:03:25.690,0:03:27.803
好 现在我们已经差不多要爆香了
Okay, it's becoming aromatic

0:03:28.470,0:03:30.250
加这个火锅底料下去炒化
Add in the hotpot base, stir and fry until it melts

0:03:35.069,0:03:36.218
诶呀 好香哦
Aiya, it smells so good

0:03:37.590,0:03:39.499
加点这个老抽调哈颜色
A little dark soy sauce for the colour

0:03:40.685,0:03:41.797
颜色给它调深点
Colour it a bit darker

0:03:45.208,0:03:46.784
然后我们再放点酱油
And some light soy sauce

0:03:50.954,0:03:52.456
最后再放半瓶啤酒
Half a can of beer at last

0:03:57.034,0:03:58.424
再放一点水进去
and a few water

0:04:02.502,0:04:05.097
然后烧开了火稍微小点
When it's boiling, lower the heat

0:04:06.116,0:04:07.247
这样子烧它半小时
Braise it for half an hour

0:04:11.825,0:04:14.847
好了 现在我们这个已经烧了40分钟了
Okay, now our dish has been braised for 40 minutes

0:04:15.384,0:04:16.939
把这个苦瓜放进去了
Drop in the bitter gourd

0:04:19.369,0:04:20.963
苦瓜放进去的时候就开始调味
At the same time start seasoning

0:04:22.354,0:04:23.466
少放一点盐
A little bit salt

0:04:25.227,0:04:26.246
再放一点白糖
A bit sugar

0:04:27.006,0:04:27.803
差不多了
Almost done

0:04:29.749,0:04:32.381
我们这个苦瓜把它烧熟了大概需要3分钟
The bitter gourd, it takes about 3 minutes to braise

0:04:32.808,0:04:35.069
如果你们怕苦的话可以焯一下水
If you dislike the bitterness you can parboil it in advance

0:04:35.069,0:04:37.182
 这个油烟子好熏人哦
The soot is quite irritating

0:04:37.553,0:04:38.331
熏到你了啊
It chokes you, didn't it?

0:04:42.020,0:04:43.985
今天这个苦瓜我就把它烧软一点
Today I'm gonna braise the bitter gourd to tender and soft

0:04:44.448,0:04:45.486
我伯爷他牙口不好
My uncle's teeth are not pretty good

0:04:46.431,0:04:49.564
要是说普通人吃的话现在都可以出锅了
If for ordinary people, the dish is ready to serve now

0:04:49.564,0:04:52.326
这个油烟子熏起眼泪都要熏出来
This choking soot, it almost choke my tears out

0:04:52.993,0:04:53.938
马上就好了哈
It's finished in a second

0:04:54.383,0:04:55.532
站远点的
Keep a distance

0:04:58.202,0:05:01.075
好 差不多了 可以了
Okay, almost there, it's done

0:05:02.724,0:05:03.484
好香啊
It smells so nice

0:05:05.783,0:05:07.191
但是苦瓜烧肉我吃过
But I've tasted meat braised with bitter gourd

0:05:07.636,0:05:12.455
下次给你整个苦瓜汤给你喝 要得不
What about next time I cook a bitter gourd soup for you

0:05:12.455,0:05:14.479
苦瓜汤整起害怕苦的要命安
I'm afraid the soup would be too bitter

0:05:15.155,0:05:17.642
不得 苦瓜排骨汤好喝得很
Nah, bitter gourd soup cooked with pork rib is really tasty

0:05:18.976,0:05:19.831
尝哈看嘛四伯爷
Have a try, uncle

0:05:20.582,0:05:21.968
我试哈看烧耙没有
Let me see if it's braised soft enough

0:05:22.525,0:05:23.886
我先吃一个苦瓜尝一下
I'll first try the bitter gourd

0:05:24.287,0:05:26.839
我先整这个大的鸭肉
I get this large lump of duck

0:05:27.655,0:05:28.782
苦瓜有点苦哦伯娘
Aunt, the gourd is a bit bitter

0:05:29.158,0:05:29.844
嗯 不怕
Um, nevermind

0:05:30.064,0:05:31.722
我没焯水的直接放下去
I didn't parboil the bitter gourd, dropped it directly in

0:05:33.445,0:05:37.707
嗯 整耙了的 还不苦安这个鸭肉
Um, it's tender, and this duck is not bitter at all

0:05:38.497,0:05:39.507
但是苦瓜苦哦
But the bitter gourd is

0:05:39.507,0:05:40.207
苦瓜苦哦
The bitter gourd taste bitter

0:05:41.399,0:05:42.253
鸭肉不苦
And the duck does not

0:05:42.305,0:05:43.212
吃坨苦瓜嘛
Try a lump of bitter gourd, won't you?

0:05:43.860,0:05:45.090
我尝一个鸭子看一下
I'll taste a piece of duck

0:05:46.152,0:05:46.787
有点苦
A little bitterness

0:05:51.204,0:05:56.570
我们这个苦瓜虽然说很苦 但是吃起来的话比较开胃
The bitter gourd is quite bitter though, but it really brings up your appetite

0:05:57.349,0:06:02.149
就是苦瓜还有莴笋稍微带点苦的食材
Those ingredients with a little bitter taste

0:06:02.279,0:06:03.762
是非常开胃下饭的
Can really whet your appetite

0:06:05.968,0:06:06.524
好吃
Delicious

0:06:08.804,0:06:09.230
可以
Good

0:06:09.930,0:06:10.393
可以噶 
Not bad

0:06:10.393,0:06:11.161
苦瓜吃了好得很
Bitter gourds really benefits your health

0:06:11.713,0:06:12.613
伯娘都晓得
Aunt knows this

0:06:13.109,0:06:16.469
苦瓜这热天吃了是相当好的它是清热的嘛
It's extremely good for you to have bitter gourd in such a hot weather, since it helps clearing the "internal heat"

0:06:17.287,0:06:17.764
嗯
Um

0:06:18.937,0:06:20.818
很多人都喜欢吃这个苦瓜热天
Quite a few people love this bitter gourd, in the hot weather

0:06:23.078,0:06:25.119
所以我们这个鸭子嘛
So this duck

0:06:26.145,0:06:29.236
鸭子属于水禽然后再烧这个苦瓜
The duck is water-grown, and braised with this bitter gourd

0:06:29.737,0:06:32.193
是相当的开胃 还有比较降火
Very appetite-stimulating, and also

0:06:36.957,0:06:38.485
好 本期视频就到这里
Okay, that's all for today's video

0:06:38.680,0:06:44.276
大家可以在家里尝试一下用苦瓜煮汤 烧肉 烧鸭子
You can try at home, using bitter gourd to cook soup, braise meat or duck

0:06:45.033,0:06:45.962
还可以烧鸡
Also chicken

0:06:46.756,0:06:48.613
比较开胃 虽然苦
It raises your appetite, despite its bitter taste

0:06:49.077,0:06:50.849
但是有时候苦也是一种美味嘛
which is sometimes an enjoyable taste as well

0:06:51.154,0:06:51.912
是不是嘛四伯爷
Isn't it, uncle?

0:06:53.879,0:06:56.127
本期视频就到这里啦 拜拜
That's all, bye~

0:06:56.139,0:06:57.067
这个苦瓜也不算很苦
The bitterness is not very strong

0:06:58.033,0:07:01.759
要那种小个小个的硬的那种才苦
Those smaller ones, stiff ones, have a very strong bitter taste

0:07:02.003,0:07:08.185
秋苦瓜 要秋苦瓜烧起更苦 那会儿的又安逸安
Autumn bitter gourds are more bitter, which is also nice

0:07:08.283,0:07:09.395
我给你舀饭嘛伯娘
Let me get some rice for you, aunt

0:07:10.861,0:07:11.606
我给你舀饭
Have some rice
