### ISSUE TITLE
[手工耿] 手工耿Useless Edison打造移動廁所摩托車Install Toilets on Motorcycles. - https://youtu.be/4Z9_YNmfSt0

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1091]
https://youtu.be/4Z9_YNmfSt0
<p>&#35270;&#39057;&#21457;&#24067;&#20110; May 27, 2020 at 09:00PM</p>
<p>&#26631;&#39064;<br>
&#25163;&#24037;&#32831;&bull;Useless Edison&#12305;&#25171;&#36896;&#31227;&#21205;&#24257;&#25152;&#25705;&#25176;&#36554;&#65281;Install Toilets on Motorcycles.</p>
<p>&#31616;&#20171;<br>
&#25163;&#24037;&#32831;&#20170;&#26085;&#33258;&#35069;&#30446;&#37636;&#65306; &#38647;&#31070;&#20043;&#37656;&#26012;&#25358;&#21253; &#26059;&#36681;&#38632;&#20632; &#20415;&#25884;&#26495;&#20979; &#25913;&#35037;&#25705;&#25176; &#33258;&#35069;&#34718;&#34481; &mdash;&mdash; &#21029;&#20154;&#31505;&#25105;&#22826;&#30219;&#30322;&#65292;&#31505;&#23436;&#30219;&#30322;&#31505;&#25105;&#38289;&#12290; &#22823;&#23478;&#22909;&#65292;&#25105;&#26159;&#25163;&#24037;&#32831;&#65292;&#22914;&#26524;&#20320;&#21916;&#27489;&#25105;&#30340;&#35222;&#38971;&#65292;&#27489;&#36814;&#40670;&#25802;&#35330;&#38321;&#12290; #&#25163;&#24037;&#32831; #UselessEdison #&#32831;&#24101; #ChineseEdison #shougonggeng #handicraft #diy #&#25163;&#24037; #&#30828;&#26680; #&#33258;&#35069;&#27231;&#22120;&#20154; #inventions #&#20013;&#22283;&#30332;&#26126; #&#20013;&#22283;&#24859;&#36842;&#29983; #&#24290;&#26612;&#24859;&#36842;&#29983; #&#25630;&#31505;&#30332;&#26126;</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/113772413d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by p1ach** [comment]
认领

**Comment by p1ach** [comment]
0:00:00.300,0:00:02.300
Mjölnir bag

0:00:03.375,0:00:06.445
I made a Mjölnir bag

0:00:09.575,0:00:10.575
take a look

0:00:11.955,0:00:13.275
you can open it here

0:00:16.665,0:00:18.855
there's a box that can hold

0:00:18.855,0:00:20.375
lighter

0:00:21.525,0:00:22.525
phone

0:00:24.235,0:00:25.425
tissue

0:00:27.205,0:00:28.900
wallet, and other stuff

0:00:48.900,0:00:50.200
swiveling umbrella

0:00:51.425,0:00:54.195
the season of rain is coming

0:00:54.195,0:00:56.675
when there're two people under the same umbrella

0:00:56.955,0:01:00.215
one of them may have a wet shoulder due to the size of the umbrella

0:01:00.265,0:01:02.445
you won't experience this anymore

0:01:02.445,0:01:05.535
because I have invented a swiveling umbrella

0:01:06.235,0:01:09.215
look, there's a small button here, and if you press it

0:01:09.215,0:01:10.215
look, there's a small button here, and if you press it

0:01:11.065,0:01:15.300
it will start swiveling swiftly. With the help of centrifugal force, it can throw the waterdrops away

0:01:15.365,0:01:18.215
so that you won't get wet in your shoulder

0:01:18.215,0:01:19.375
if you love it, press the good button.

0:01:19.375,0:01:21.255
 I'll show you when it's rainy

0:01:22.835,0:01:25.655
let me show you how it functions on a rainy day

0:01:25.675,0:01:26.675
let me show you how it functions on a rainy day

0:01:31.475,0:01:32.375
see?

0:01:32.875,0:01:35.975
it's like...

0:01:36.295,0:01:37.795
doesn't wet your shoulder

0:01:38.900,0:01:40.500
portable stool

0:01:41.425,0:01:43.535
when we're waiting for the bus

0:01:43.535,0:01:44.805
or subways

0:01:44.805,0:01:47.225
we'll be worried about 

0:01:47.225,0:01:49.715
not being able to find a seat. These days

0:01:49.715,0:01:52.975
I've been researching on a new stool 

0:01:52.975,0:01:55.135
it doesn't look like a stool in appearance

0:01:55.135,0:01:57.505
let me show you how it works

0:01:58.365,0:02:00.845
insert the elastic bands

0:02:02.225,0:02:04.075
then put in your feet

0:02:06.345,0:02:09.395
this is how it looks on your feet

0:02:09.395,0:02:12.425
doesn't affect walking, and when you feel tired

0:02:12.425,0:02:13.685
just sit on it

0:02:14.155,0:02:17.245
it will take off most of your strength and

0:02:17.245,0:02:19.605
you won't feel tired no matter how long you sit

0:02:19.605,0:02:22.215
you can sit wherever you go

0:02:22.215,0:02:25.645
when you want to sit you won't even need to get up

0:02:25.715,0:02:26.715
see?

0:02:32.425,0:02:34.845
like this, super convenient

0:02:34.845,0:02:38.175
if you like it, press the good button! thanks

0:02:38.175,0:02:40.175
modified motorbike

0:02:41.285,0:02:43.765
take a look at my modified motorbike

0:02:44.275,0:02:47.255
look like an ordinary motorbike

0:02:47.355,0:02:50.285
but if you open its seat

0:02:52.565,0:02:53.605
you will find that

0:02:54.005,0:02:55.305
it's a toilet seat!

0:02:56.965,0:02:58.355
you can even flush it

0:03:02.745,0:03:03.745
let me

0:03:04.145,0:03:05.595
show you guys

0:03:05.595,0:03:06.915


0:03:07.900,0:03:09.900
eating the locust

0:03:23.125,0:03:24.125

**Comment by p1ach** [comment]
0:00:00.300,0:00:02.300
雷神之锤斜挎包
Mjölnir bag

0:00:03.375,0:00:06.445
做了一个雷神锤的斜挎包
I made a Mjölnir bag

0:00:09.575,0:00:10.575
看一下
take a look

0:00:11.955,0:00:13.275
它这里可以打开
you can open it here

0:00:16.665,0:00:18.855
里面有个盒子，可以装一些
there's a box that can hold

0:00:18.855,0:00:20.375
打火机
lighter

0:00:21.525,0:00:22.525
手机啊
phone

0:00:24.235,0:00:25.425
卫生纸
tissue

0:00:27.205,0:00:28.900
钱包之类的
wallet, and other stuff

0:00:48.900,0:00:50.200
旋转雨伞
swiveling umbrella

0:00:51.425,0:00:54.195
雨季马上就要到了，平时我们下雨打伞
the season of rain is coming

0:00:54.195,0:00:56.675
尤其是2个人打一把伞的时候，由于雨伞面积的原因
when there're two people under the same umbrella

0:00:56.955,0:01:00.215
经常会打湿我们的肩膀
one of them may have a wet shoulder due to the size of the umbrella

0:01:00.265,0:01:02.445
现在不会了
you won't experience this anymore

0:01:02.445,0:01:05.535
我发明的这种可以旋转的雨伞
because I have invented a swiveling umbrella

0:01:06.235,0:01:09.215
看到没，这里有个小按钮，只要你轻轻地一按
look, there's a small button here, and if you press it

0:01:09.215,0:01:10.215
看到没，这里有个小按钮，只要你轻轻地一按 （这句话说了很长，所以我做了2个字幕，效果是一样的，就是一句话保持比较长）
look, there's a small button here, and if you press it

0:01:11.065,0:01:15.300
因为离心力的缘故，它就会快速地转动
it will start swiveling swiftly. With the help of centrifugal force, it can throw the waterdrops away

0:01:15.365,0:01:18.215
这样就不会打湿自己的肩膀
so that you won't get wet in your shoulder

0:01:18.215,0:01:19.375
希望红心点点，关注一下
if you love it, press the good button.

0:01:19.375,0:01:21.255
下雨的时候给大家演示
I'll show you when it's rainy

0:01:22.835,0:01:25.655
给大家看看这个雨伞在下雨天的时候是什么样的
let me show you how it functions on a rainy day

0:01:25.675,0:01:26.675
给大家看看这个雨伞在下雨天的时候是什么样的（做2条理由同上）
let me show you how it functions on a rainy day

0:01:31.475,0:01:32.375
看到没有
see?

0:01:32.875,0:01:35.975
也没有说，特别，转得特别干嘛
it's like...

0:01:36.295,0:01:37.795
也打湿不了肩膀
doesn't wet your shoulder

0:01:38.900,0:01:40.500
便携板凳
portable stool

0:01:41.425,0:01:43.535
平时我们在等公交
when we're waiting for the bus

0:01:43.535,0:01:44.805
或地铁的时候
or subways

0:01:44.805,0:01:47.225
经常为找不到
we'll be worried about 

0:01:47.225,0:01:49.715
一个座位而发愁犯难
not being able to find a seat. These days

0:01:49.715,0:01:52.975
所以说这几天我一直在研究一个小板凳
I've been researching on a new stool 

0:01:52.975,0:01:55.135
它的外表很难看出是一个小板凳来
it doesn't look like a stool in appearance

0:01:55.135,0:01:57.505
下面我给大家演示一下怎么用
let me show you how it works

0:01:58.365,0:02:00.845
首先把松紧带放进去
insert the elastic bands

0:02:02.225,0:02:04.075
然后再穿进去就可以了
then put in your feet

0:02:06.345,0:02:09.395
这就是穿好的样子
this is how it looks on your feet

0:02:09.395,0:02:12.425
也不会影响我们走路，当你累的时候
doesn't affect walking, and when you feel tired

0:02:12.425,0:02:13.685
直接蹲下就可以
just sit on it

0:02:14.155,0:02:17.245
它会卸掉人体大部分的力量
it will take off most of your strength and

0:02:17.245,0:02:19.605
而且坐多久都不会觉得累
you won't feel tired no matter how long you sit

0:02:19.605,0:02:22.215
这样你就可以走在哪里坐在哪里
you can sit wherever you go

0:02:22.215,0:02:25.645
当你想找个地方坐的时候甚至都不用起身
when you want to sit you won't even need to get up

0:02:25.715,0:02:26.715
看到没有
see?

0:02:32.425,0:02:34.845
就想这样非常方便
like this, super convenient

0:02:34.845,0:02:38.175
如果喜欢的话点个红心
if you like it, press the good button! thanks

0:02:38.175,0:02:40.175
改装摩托
modified motorbike

0:02:41.285,0:02:43.765
给大家看一下我刚改好的摩托车
take a look at my modified motorbike

0:02:44.275,0:02:47.255
外表跟普通的摩托车差不多
look like an ordinary motorbike

0:02:47.355,0:02:50.285
但是说你打开它的坐垫
but if you open its seat

0:02:52.565,0:02:53.605
你就发现
you will find that

0:02:54.005,0:02:55.305
它是一个马桶
it's a toilet seat!

0:02:56.965,0:02:58.355
还可以冲水
you can even flush it

0:03:02.745,0:03:03.745
我给大家
let me

0:03:04.145,0:03:05.595
试一下
show you guys

0:03:05.595,0:03:06.915


0:03:07.900,0:03:09.900
吃蚂蚱
eating the locust

0:03:23.125,0:03:24.125
