### ISSUE TITLE
【美食作家王刚】 如何成为一名合格的厨师 - https://youtu.be/aaZ5u7cLdjM

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1096]
**视频链接**：https://youtu.be/aaZ5u7cLdjM

视频时长2:26，预计发布时间为北京时间5月31日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“如何成为一名合格的厨师”，用自己早期后厨经历来现身说法

简介
大家好，今天和大家分享一下从我自己早期的经历来总结的一些小经验，如果想走上厨师这条路我们怎样如何成为一名合格的厨师。不仅仅是吃苦耐劳把本职工作做好一步步来，也要学会把握机会争取机会，因为可能就是一次普通上灶的机会就给你带来更大的平台。还有就是学会看事儿 @馋小漆  大师傅当然愿意来教你。

字幕
0:00:00.400,0:00:01.875
哈喽大家好我是王刚

0:00:02.225,0:00:06.825
这些年有很多粉丝问我如何才能够成为一个合格的厨师

0:00:07.150,0:00:10.275
现在我就用我的早期经历跟大家分享一下

0:00:10.775,0:00:15.625
刚开始的时候作为一个什么都不懂的学徒一个门外汉来说

0:00:15.750,0:00:20.550
看到打荷，配菜和灶上炒菜的师傅们各有各的技巧

0:00:20.650,0:00:26.275
一开始都特别的渴望早日能成为一个什么都懂而且技术好的师傅

0:00:26.350,0:00:29.700
所以就比较特别的着急和彷徨

0:00:29.725,0:00:31.350
不知所措特别的迷茫

0:00:31.550,0:00:37.275
所以在这个视频我会跟大家快速分享一下如何正确的走上厨师长的道路

0:00:37.850,0:00:40.000
我记得我刚开始出来的时候比较小 

0:00:40.275,0:00:42.546
差不多也就是14-15岁的样子吧

0:00:43.375,0:00:48.025
就算给我一个炒锅让我马上上去炒菜我又能炒什么呢

0:00:48.225,0:00:50.825
这个时候我连最基本的东西都不知道

0:00:51.200,0:00:57.750
所以说越着急越没有用急功近利会事得其反

0:00:58.250,0:01:04.400
首先让自己变得有功底那就是沉下心来把杂工的本职工作干好

0:01:04.550,0:01:07.925
能够吃苦耐劳脏活累活抢着干

0:01:08.075,0:01:12.700
只有这样师傅才能够喜欢你愿意去带你

0:01:13.575,0:01:18.625
这样才能够有更多的机会学习打荷，切菜，摆盘

0:01:18.775,0:01:21.350
只有把刀功练好把炒锅练好

0:01:21.600,0:01:23.525
好要会一些像样的摆盘

0:01:23.775,0:01:28.175
在合适的时间和地点再找上灶的机会

0:01:28.975,0:01:32.175
要懂的不怕脏不怕累多付出汗水

0:01:32.625,0:01:36.225
一旦有炒菜的机会来了要把握好

0:01:36.500,0:01:39.175
必须拿这个基本功练扎实

0:01:39.425,0:01:42.550
比如说翻锅和调味

0:01:42.625,0:01:45.425
还有掌握油温这些基本的常识

0:01:45.475,0:01:49.025
最后呢我建议大家就是做人不要太木讷

0:01:49.150,0:01:50.350
要会看事儿

0:01:50.500,0:01:56.000
比如说师傅渴了就给他端点水送点茶之类的

0:01:56.275,0:02:00.775
比如说师傅炒完菜当然是很累了马上下来了之后呢

0:02:00.900,0:02:03.175
就接过他手中的卫生去搞干净

0:02:03.575,0:02:07.775
但是前提是自己的本质工作提前完成的情况下

0:02:07.950,0:02:11.900
要不然自己的事情都没有做好又怎么去帮被人呢

0:02:12.025,0:02:13.450
这样只会添乱

0:02:13.925,0:02:15.575
好了本期视频就到这里

0:02:15.725,0:02:18.975
下期视频我会为大家分享更多的厨师专业

0:02:19.125,0:02:22.500
或者是美食作家王刚的美食小技巧

0:02:22.800,0:02:24.475
就到这里啦 拜拜


```

**Comment by Yingzhang1122** [comment]
#标题（翻译主要意思即可，不要超过 100 个字符）
#厨师长分享：“如何成为一名合格的厨师”，用自己早期后厨经历来现身说法
Chef Wang shares: 'How to become a qualified chef?' Demonstrations with my own experience!

#简介
#大家好，今天和大家分享一下从我自己早期的经历来总结的一些小经验，如果想走上厨师这条路我们怎样如何成为一名合格的厨师。不仅仅是吃苦耐劳把本职工作做好一步步来，也要学会把握机会争取机会，因为可能就是一次普通上灶的机会就给你带来更大的平台。还有就是学会看事儿 @馋小漆  大师傅当然愿意来教你。
Hi everyone! Today I'm gonna share my experience based on what I went through in the past, and talk about how to become a qualified chef. Firstly, you need to do your job with great diligence and take one step at a time. You also need to learn to catch as well as strive for opportunities, because a normal chance of working at the cooking stove may raise you to a greater platform. Moreover, it's also important to be observant and proactive @馋小漆 so that the master chef would be very willing to teach you.

#字幕
0:00:00.400,0:00:01.875
#哈喽大家好我是王刚
Hi everyone, I'm Wang Gang

0:00:02.225,0:00:06.825
#这些年有很多粉丝问我如何才能够成为一个合格的厨师
In these years, many fans have been asking me how to become a qualified cook

0:00:07.150,0:00:10.275
#现在我就用我的早期经历跟大家分享一下
Now I want to share my experiences in my early years with you

0:00:10.775,0:00:15.625
#刚开始的时候作为一个什么都不懂的学徒一个门外汉来说
At the very beginning, as a new apprentice, or a noob, who knows nothing at all

0:00:15.750,0:00:20.550
#看到打荷，配菜和灶上炒菜的师傅们各有各的技巧
You may notice that distributors, choppers, and stove cooks master their own skills #这里打荷不知道具体怎么翻译，查了一下感觉distributor比较合适？

0:00:20.650,0:00:26.275
#一开始都特别的渴望早日能成为一个什么都懂而且技术好的师傅
And you'll be longing for becoming a skillful and knowledgeable master chef as soon as possible

0:00:26.350,0:00:29.700
#所以就比较特别的着急和彷徨
So you'll be worried and hesitated

0:00:29.725,0:00:31.350
#不知所措特别的迷茫
You may also get lost and don't know what to do

0:00:31.550,0:00:37.275
#所以在这个视频我会跟大家快速分享一下如何正确的走上厨师长的道路
So I'm gonna share with you rapidly about how to get on the right track to a master chef

0:00:37.850,0:00:40.000
#我记得我刚开始出来的时候比较小
I remember that I was relatively young when I started my career

0:00:40.275,0:00:42.546
#差不多也就是14-15岁的样子吧
At that time, I was about 14-15 years old

0:00:43.375,0:00:48.025
#就算给我一个炒锅让我马上上去炒菜我又能炒什么呢
Even if I was immediately given the chance of cooking with a wok, what could I cook?

0:00:48.225,0:00:50.825
#这个时候我连最基本的东西都不知道
I didn't even know the most basic knowledge

0:00:51.200,0:00:57.750
#所以说越着急越没有用急功近利会事得其反
So it is completely useless to be worried. Being eager to achieve quick success only ruins everything

0:00:58.250,0:01:04.400
#首先让自己变得有功底那就是沉下心来把杂工的本职工作干好
The very first thing to do is to accumulate some skills, that is, be patient and do your job well as a busboy

0:01:04.550,0:01:07.925
#能够吃苦耐劳脏活累活抢着干
You need to endure hardships and be active to do all dirty and tiring jobs

0:01:08.075,0:01:12.700
#只有这样师傅才能够喜欢你愿意去带你
Only in this way will the master chefs like you and teach you

0:01:13.575,0:01:18.625
#这样才能够有更多的机会学习打荷，切菜，摆盘
In this way, you'll have more chances to learn to distribute, chopping, and presenting food

0:01:18.775,0:01:21.350
#只有把刀功练好把炒锅练好
You need to practice and master cutting and wok-tossing skills

0:01:21.600,0:01:23.525
#好要会一些像样的摆盘
Also, you should have some knowledge of decent food presentation

0:01:23.775,0:01:28.175
#在合适的时间和地点再找上灶的机会
Then, you can wait for a chance to cook at the stove at an appropriate time and place

0:01:28.975,0:01:32.175
#要懂的不怕脏不怕累多付出汗水
Don't be afraid of getting dirty and tired. Make painstaking efforts

0:01:32.625,0:01:36.225
#一旦有炒菜的机会来了要把握好
Once you have the chance to show yourself at the cooking stove, seize it

0:01:36.500,0:01:39.175
#必须拿这个基本功练扎实
You must have solid basic skills

0:01:39.425,0:01:42.550
#比如说翻锅和调味
Such as tossing the wok and seasoning

0:01:42.625,0:01:45.425
#还有掌握油温这些基本的常识
As well as knowing basics such as determining oil temperature

0:01:45.475,0:01:49.025
#最后呢我建议大家就是做人不要太木讷
At last, I would recommend you not to be shy and dull

0:01:49.150,0:01:50.350
#要会看事儿
You need to be observant and proactive

0:01:50.500,0:01:56.000
#比如说师傅渴了就给他端点水送点茶之类的
For example, if your master is thirsty, get him a drink

0:01:56.275,0:02:00.775
#比如说师傅炒完菜当然是很累了马上下来了之后呢
Or, when he just finishes cooking and gets exhausted

0:02:00.900,0:02:03.175
#就接过他手中的卫生去搞干净
You should take over his cleaning job

0:02:03.575,0:02:07.775
#但是前提是自己的本质工作提前完成的情况下
Of course, you must have done your own job

0:02:07.950,0:02:11.900
#要不然自己的事情都没有做好又怎么去帮被人呢
Otherwise, you won't help others out

0:02:12.025,0:02:13.450
#这样只会添乱
but cause new troubles

0:02:13.925,0:02:15.575
#好了本期视频就到这里
Ok. That's the end of this video

0:02:15.725,0:02:18.975
#下期视频我会为大家分享更多的厨师专业
I'll share with you more professional skills in my next video

0:02:19.125,0:02:22.500
#或者是美食作家王刚的美食小技巧
Or useful tricks of cooking

0:02:22.800,0:02:24.475
#就到这里啦 拜拜
That's all. Bye-bye!
