### ISSUE TITLE
【美食作家王刚】逛果园 - https://youtu.be/pwFKQW08J98

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1104]
**视频链接**：https://youtu.be/pwFKQW08J98

视频时长6:15，预计发布时间为北京时间6月2日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
难得的休息，带家人一起逛果园，摘了好多蓝莓和西红柿，真甜！

简介
大家好，今天休息，和家人一起去休闲一下。果园是个不错的全家人出来玩的选择，不仅可以亲自采摘好吃的瓜果蔬菜，还能特别好的让孩子亲近了解自然，了解农民伯伯们的劳作。看到不少朋友留言说家里的弟弟长大了没，今天就来出个镜，还依然胖乎乎的，很乖，感谢大家的关心。

字幕
0:00:10.375,0:00:11.025
哈喽 大家好

0:00:11.175,0:00:14.325
今天天气稍微好一点了 我就给自己放一天假

0:00:14.675,0:00:16.750
带我女儿来这个

0:00:16.975,0:00:17.975
这儿叫啥子场呢

0:00:18.875,0:00:20.225
不晓得 果园嘛

0:00:20.225,0:00:25.100
（我们来）到果园这边来摘一点蓝莓呀 看看葡萄西红柿这些

0:00:25.575,0:00:26.525
对吧宝贝

0:00:26.600,0:00:27.050
嗯

0:00:27.100,0:00:30.125
你看 要不摘一个这个没熟的葡萄尝一下

0:00:33.349,0:00:34.625
不能摘 还没熟吧

0:00:34.825,0:00:37.192
摘一颗没事 来尝一下吧

0:00:39.701,0:00:40.866
酸的是不是

0:00:41.005,0:00:42.030
诶 你别吐呀

0:00:42.827,0:00:43.972
爸爸也可以吃呀

0:00:44.390,0:00:44.738
走吧

0:00:45.067,0:00:45.913
走 我们去里面

0:00:47.277,0:00:47.794
好吃

0:00:48.272,0:00:48.670
甜吗

0:00:49.347,0:00:50.492
等下摘一点回去

0:00:50.542,0:00:51.747
睡着了你看

0:00:52.115,0:00:54.853
爸爸 这下面有几个蓝莓

0:00:55.400,0:00:56.595
这都是蓝莓呀 来

0:00:56.625,0:00:57.053
这都是

0:00:57.103,0:00:57.551
过来吧

0:00:57.570,0:00:58.944
拿个篮子过去摘嘛

0:00:59.671,0:01:02.220
挑大的 大的 对

0:01:03.743,0:01:05.704
 对了 选大的来摘呀

0:01:05.783,0:01:06.182
嗯

0:01:07.018,0:01:10.333
蓝莓自己掉在了我自己的篮子里面了 

0:01:10.423,0:01:10.801
嗯

0:01:12.215,0:01:13.449
我也想吃

0:01:13.897,0:01:14.524
我摘一个给你

0:01:20.089,0:01:21.373
多摘点我也想吃哦

0:01:21.403,0:01:21.821
好

0:01:21.821,0:01:22.787
给妈妈也摘一点啊

0:01:23.115,0:01:23.554
嗯

0:01:24.250,0:01:24.569
对

0:01:25.664,0:01:28.003
哇 你不要弄到地上了 宝贝

0:01:28.501,0:01:30.612
接着 我给你拿 我给你接着

0:01:31.309,0:01:32.404
摘吧 这里

0:01:34.574,0:01:35.709
诶呀 你好暴力啊

0:01:36.884,0:01:37.939
沺沺你好暴力啊

0:01:39.333,0:01:43.106
这个蓝莓老板说一定要摘

0:01:43.145,0:01:43.474
诶

0:01:43.882,0:01:44.757
摘下那颗吧

0:01:45.067,0:01:45.704
等一下啊

0:01:46.371,0:01:48.770
这个蓝莓老板说一定要摘大的要摘黑的

0:01:49.118,0:01:50.169
要不然不甜

0:01:50.169,0:01:51.637
要摘黑色的 越黑的越好

0:01:52.254,0:01:53.011
嗯 比较甜

0:01:53.036,0:01:54.856
爸爸 这个好大呀

0:01:54.868,0:01:55.894
这个就像葡萄一样

0:01:57.202,0:01:59.731
大家可以看一下这个一串一串的像葡萄一样

0:02:00.305,0:02:01.795
我以前没有见过蓝莓树

0:02:02.052,0:02:05.192
今天现场摘一下

0:02:12.742,0:02:15.369
这个蓝莓我们看一下上面有一层灰

0:02:15.846,0:02:18.802
老板说是果粉 这个营养价值特别好

0:02:23.628,0:02:24.813
摘这种大颗的

0:02:25.632,0:02:27.318
 这一串好多哦

0:02:29.566,0:02:31.508
这个像葡萄一样你看这个

0:02:32.131,0:02:36.408
但是不黑的、有颜色的、青的都不摘

0:02:37.568,0:02:38.900
老婆摘黑色的啊

0:02:39.890,0:02:42.064
不黑的不甜而且也还没熟

0:02:42.125,0:02:43.970
爸爸 我摘得更多

0:02:45.094,0:02:46.182
你摘了多少了

0:02:46.536,0:02:47.452
这么多呀

0:02:48.100,0:02:49.431
像这种你们过来看

0:02:49.639,0:02:50.397
看看看

0:02:51.166,0:02:51.704
上面那个

0:02:51.936,0:02:53.439
啊 这种很甜

0:02:56.627,0:02:59.047
哇 这一串特别多

0:02:59.303,0:03:01.722
这个熟的稍微动一下就掉下来了

0:03:03.848,0:03:06.035
妈妈过来 这儿很大的呢

0:03:06.035,0:03:07.391
好的 你摘吧

0:03:10.018,0:03:10.751
摘多少

0:03:10.885,0:03:11.960
我摘了这么一点

0:03:12.021,0:03:14.318
太多了 我都不知道怎么下手了

0:03:15.027,0:03:15.552
你看嘛

0:03:16.566,0:03:17.532
沺沺你的呢

0:03:18.020,0:03:20.293
才摘那么一点 还不如我摘得多 你看

0:03:20.574,0:03:22.419
沺沺 快点

0:03:23.127,0:03:23.787
还在摘啊

0:03:24.117,0:03:24.679
对

0:03:25.949,0:03:28.332
宝贝出来出来 我看你摘了多少

0:03:29.627,0:03:31.117
小心小心 过来

0:03:31.215,0:03:32.645
沺沺都比我摘得多

0:03:32.657,0:03:33.988
她都要比你多摘一点

0:03:34.160,0:03:35.430
还大个一点呢她摘得

0:03:35.430,0:03:37.988
我们应该目前摘了一斤多吧

0:03:37.996,0:03:38.668
有没得一斤哦

0:03:38.912,0:03:39.999
有一哈有一斤

0:03:41.037,0:03:42.185
这是你的 拿好啊

0:03:42.541,0:03:44.434
嗯 沺沺你摘了一个酸的

0:03:45.167,0:03:47.649
走吧 我们去看一下其它的

0:03:47.754,0:03:48.782
你吃一下这个 沺沺

0:03:50.580,0:03:51.095
甜吗

0:03:51.932,0:03:53.093
干嘛 酸的是不是

0:03:53.093,0:03:54.571
酸的你别吐啊 浪费了

0:03:55.205,0:03:55.452
走 

0:03:55.750,0:03:56.091
走嘛

0:04:01.750,0:04:02.711
走吧走吧

0:04:04.015,0:04:06.498
沺沺 沺沺

0:04:07.478,0:04:10.647
现在让我老婆来摘一下 我来抱一下孩子

0:04:11.845,0:04:12.607
他睡着了

0:04:13.577,0:04:17.887
刚才一直在那里笑 笑着笑着就睡着了

0:04:21.179,0:04:23.168
你们摘呀 我抱着弟弟看你们摘

0:04:23.168,0:04:23.501
好

0:04:24.900,0:04:26.508
沺沺摘大一点的

0:04:26.517,0:04:27.145
红的 你看

0:04:27.659,0:04:28.439
好不好玩

0:04:28.458,0:04:28.943
好玩

0:04:29.115,0:04:30.922
等下回去煎鸡蛋给你吃好不好

0:04:31.598,0:04:32.007
鸡蛋

0:04:32.150,0:04:32.483
嗯

0:04:32.711,0:04:33.196
好

0:04:33.196,0:04:33.672
就煎鸡蛋吃

0:04:34.443,0:04:35.432
这个更甜

0:04:35.632,0:04:36.127
哪个

0:04:36.327,0:04:37.107
我来摘嘛

0:04:37.944,0:04:38.725
我来给它摘了

0:04:39.010,0:04:39.533
这是不

0:04:39.876,0:04:41.303
哇 好透明哦

0:04:41.303,0:04:42.759
沺沺 你也摘呀

0:04:45.813,0:04:46.888
来嘛 我擦一下给你吃

0:04:49.048,0:04:49.476
甜不甜

0:04:50.038,0:04:50.399
嗯

0:04:52.007,0:04:53.358
我们这里以前没有这种的

0:04:54.062,0:04:54.862
那干嘛呢

0:04:55.176,0:04:56.622
这个应该是后面培育出来的

0:04:56.917,0:04:59.628
培育 我看到有那种子卖啊

0:05:01.113,0:05:02.978
之前我买了很多给我妈妈种 

0:05:02.978,0:05:04.529
我们也买点回去种呗

0:05:06.260,0:05:06.660
可以

0:05:13.006,0:05:14.300
你摘了一篮子啊

0:05:14.652,0:05:14.985
对

0:05:16.165,0:05:18.059
妈妈可以给我一点小的吗

0:05:18.068,0:05:19.105
差不多了 我们去称一下吧

0:05:19.219,0:05:19.552
嗯

0:05:19.800,0:05:20.152
走

0:05:20.285,0:05:20.656
走嘛

0:05:21.655,0:05:23.101
看谁摘得多

0:05:23.273,0:05:24.862
叫奶奶一起 沺沺

0:05:37.117,0:05:38.078
边走边吃啊

0:05:38.639,0:05:39.153
好吃吗

0:05:39.400,0:05:40.076
好吃

0:05:40.142,0:05:41.170
下次我们又来摘嘛

0:05:41.427,0:05:41.902
好

0:05:42.464,0:05:45.480
今天小孩子已经满了四个月

0:05:45.480,0:05:46.489
带他们出来玩一下

0:05:47.973,0:05:50.846
不出来我都不知道原来我们富顺还有这种好地方

0:05:53.824,0:05:54.196
好啦

0:05:54.500,0:06:00.418
以后要是你们有时间的话都多带孩子家人出来玩一下

0:06:01.027,0:06:05.233
因为一辈子不可能就只有工作嘛

0:06:05.233,0:06:06.822
好甜呀 好甜呀 妈妈

0:06:09.029,0:06:10.142
过几天又可以摘了 葡萄

0:06:10.608,0:06:12.540
妈妈 好甜呀 

0:06:12.540,0:06:13.149
还要吃吗

0:06:13.691,0:06:14.167
还要


```

**Comment by Hackerry** [comment]
认领

**Comment by Hackerry** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
难得的休息，带家人一起逛果园，摘了好多蓝莓和西红柿，真甜！
Precious day off. Brought family to a fruit picking farm. We picked sweet blueberries and tomatoes.

简介
大家好，今天休息，和家人一起去休闲一下。果园是个不错的全家人出来玩的选择，不仅可以亲自采摘好吃的瓜果蔬菜，还能特别好的让孩子亲近了解自然，了解农民伯伯们的劳作。看到不少朋友留言说家里的弟弟长大了没，今天就来出个镜，还依然胖乎乎的，很乖，感谢大家的关心。
Hello, everyone. I took one day off and decided to have a trip to a nearby fruit farm. It's a perfect place for children to immerse in nature and to experience farmers' daily work, besides eating freshly-picked fruits and vegetables. I received many comments asking our little brother. Today I brought him in front of the camera. Still chubby and very adorable. Thanks for all the attentiveness from everyone.

字幕
0:00:10.375,0:00:11.025
哈喽 大家好
Hello, everyone.

0:00:11.175,0:00:14.325
今天天气稍微好一点了 我就给自己放一天假
It's a nice day today. I decided to take a day off

0:00:14.675,0:00:16.750
带我女儿来这个
and take my daughter to this...

0:00:16.975,0:00:17.975
这儿叫啥子场呢
What do we call this place?

0:00:18.875,0:00:20.225
不晓得 果园嘛
Not sure. A fruit farm?

0:00:20.225,0:00:25.100
（我们来）到果园这边来摘一点蓝莓呀 看看葡萄西红柿这些
(We) came to pick some blueberries, grapes and tomatoes.

0:00:25.575,0:00:26.525
对吧宝贝
Right, darling?

0:00:26.600,0:00:27.050
嗯
Um

0:00:27.100,0:00:30.125
你看 要不摘一个这个没熟的葡萄尝一下
Look. Do you want to try an unripened grape?

0:00:33.349,0:00:34.625
不能摘 还没熟吧
Don't pick. It's not ripe yet.

0:00:34.825,0:00:37.192
摘一颗没事 来尝一下吧
One won't hurt. Let's have a taste.

0:00:39.701,0:00:40.866
酸的是不是
Sour isn't it?

0:00:41.005,0:00:42.030
诶 你别吐呀
Eh, don't spit on the ground.

0:00:42.827,0:00:43.972
爸爸也可以吃呀
I can eat it.

0:00:44.390,0:00:44.738
走吧
Let's go.

0:00:45.067,0:00:45.913
走 我们去里面
Let's go inside.

0:00:47.277,0:00:47.794
好吃
Tastes good.

0:00:48.272,0:00:48.670
甜吗
Is it sweet?

0:00:49.347,0:00:50.492
等下摘一点回去
We can take some home.

0:00:50.542,0:00:51.747
睡着了你看
Well someone has fallen asleep.

0:00:52.115,0:00:54.853
爸爸 这下面有几个蓝莓
Daddy, I can see some blueberries down here.

0:00:55.400,0:00:56.595
这都是蓝莓呀 来
Those are all blueberries. Come.

0:00:56.625,0:00:57.053
这都是
They are all blueberries.

0:00:57.103,0:00:57.551
过来吧
Come here.

0:00:57.570,0:00:58.944
拿个篮子过去摘嘛
Take a basket and go pick some.

0:00:59.671,0:01:02.220
挑大的 大的 对
Pick the larger ones. Yes.

0:01:03.743,0:01:05.704
 对了 选大的来摘呀
Good. Choose the large ones.

0:01:05.783,0:01:06.182
嗯
Um.

0:01:07.018,0:01:10.333
蓝莓自己掉在了我自己的篮子里面了 
Blueberries they fall into my (own) basket.

0:01:10.423,0:01:10.801
嗯
Um.

0:01:12.215,0:01:13.449
我也想吃
I want to eat too.

0:01:13.897,0:01:14.524
我摘一个给你
Let me pick one for you.

0:01:20.089,0:01:21.373
多摘点我也想吃哦
Go pick some more for mommy.

0:01:21.403,0:01:21.821
好
Um.

0:01:21.821,0:01:22.787
给妈妈也摘一点啊
Have some for mommy, OK?

0:01:23.115,0:01:23.554
嗯
Um.

0:01:24.250,0:01:24.569
对
Good.

0:01:25.664,0:01:28.003
哇 你不要弄到地上了 宝贝
Whoa, don't let it fall on the ground, sweetie.

0:01:28.501,0:01:30.612
接着 我给你拿 我给你接着
Use a basket. Let me hold the basket.

0:01:31.309,0:01:32.404
摘吧 这里
Go on. Here are some more.

0:01:34.574,0:01:35.709
诶呀 你好暴力啊
Whoa, you are savage.

0:01:36.884,0:01:37.939
沺沺你好暴力啊
Tian Tian you are savage.

0:01:39.333,0:01:43.106
这个蓝莓老板说一定要摘
The owner says,

0:01:43.145,0:01:43.474
诶
Eh.

0:01:43.882,0:01:44.757
摘下那颗吧
Can we pick that one?

0:01:45.067,0:01:45.704
等一下啊
Just a second.

0:01:46.371,0:01:48.770
这个蓝莓老板说一定要摘大的要摘黑的
The owner says the large and black ones are the best.

0:01:49.118,0:01:50.169
要不然不甜
They are the sweet ones.

0:01:50.169,0:01:51.637
要摘黑色的 越黑的越好
Pick the black ones.

0:01:52.254,0:01:53.011
嗯 比较甜
Um. Very sweet.

0:01:53.036,0:01:54.856
爸爸 这个好大呀
Daddy, this one is huge.

0:01:54.868,0:01:55.894
这个就像葡萄一样
They look like grapes.

0:01:57.202,0:01:59.731
大家可以看一下这个一串一串的像葡萄一样
You can see they grow like grapes in bunches.

0:02:00.305,0:02:01.795
我以前没有见过蓝莓树
I've never seem blueberry bushes before.

0:02:02.052,0:02:05.192
今天现场摘一下
Today we experience picking blueberries live.

0:02:12.742,0:02:15.369
这个蓝莓我们看一下上面有一层灰
See, the blueberries are coated with a layer of powder.

0:02:15.846,0:02:18.802
老板说是果粉 这个营养价值特别好
The owner says it's called bloom and very nutritious.

0:02:23.628,0:02:24.813
摘这种大颗的
Pick those large ones.

0:02:25.632,0:02:27.318
 这一串好多哦
This is a large bunch.

0:02:29.566,0:02:31.508
这个像葡萄一样你看这个
They just look like grapes.

0:02:32.131,0:02:36.408
但是不黑的、有颜色的、青的都不摘
We leave those colored and green ones.

0:02:37.568,0:02:38.900
老婆摘黑色的啊
Honey, pick those black ones.

0:02:39.890,0:02:42.064
不黑的不甜而且也还没熟
The non-black ones aren't sweet.

0:02:42.125,0:02:43.970
爸爸 我摘得更多
Daddy, I picked a lot.

0:02:45.094,0:02:46.182
你摘了多少了
How many do you have?

0:02:46.536,0:02:47.452
这么多呀
This many!

0:02:48.100,0:02:49.431
像这种你们过来看
Come and have a look.

0:02:49.639,0:02:50.397
看看看
Look, look!

0:02:51.166,0:02:51.704
上面那个
That one.

0:02:51.936,0:02:53.439
啊 这种很甜
Aye, this kind is sweet.

0:02:56.627,0:02:59.047
哇 这一串特别多
Wow, look at this bunch of blueberries.

0:02:59.303,0:03:01.722
这个熟的稍微动一下就掉下来了
Ripe and ready to be plucked.

0:03:03.848,0:03:06.035
妈妈过来 这儿很大的呢
Mommy, come! I have very large ones here.

0:03:06.035,0:03:07.391
好的 你摘吧
Good. Go pick them.

0:03:10.018,0:03:10.751
摘多少
How many do you have?

0:03:10.885,0:03:11.960
我摘了这么一点
Only this many.

0:03:12.021,0:03:14.318
太多了 我都不知道怎么下手了
There are so many of them. I don't know what to pick.

0:03:15.027,0:03:15.552
你看嘛
See?

0:03:16.566,0:03:17.532
沺沺你的呢
Tian Tian where are yours?

0:03:18.020,0:03:20.293
才摘那么一点 还不如我摘得多 你看
Only that few. Not so many as mine. Look.

0:03:20.574,0:03:22.419
沺沺 快点
Tian Tian, hurry.

0:03:23.127,0:03:23.787
还在摘啊
Still picking?

0:03:24.117,0:03:24.679
对
Yes.

0:03:25.949,0:03:28.332
宝贝出来出来 我看你摘了多少
Come here, darling. Let me see how many you've got.

0:03:29.627,0:03:31.117
小心小心 过来
Careful. Come.

0:03:31.215,0:03:32.645
沺沺都比我摘得多
Tian Tian has more than I do.

0:03:32.657,0:03:33.988
她都要比你多摘一点
Even she has more than you do.

0:03:34.160,0:03:35.430
还大个一点呢她摘得
And larger.

0:03:35.430,0:03:37.988
我们应该目前摘了一斤多吧
We should have about 1 Jin (500g).

0:03:37.996,0:03:38.668
有没得一斤哦
We have that much?

0:03:38.912,0:03:39.999
有一哈有一斤
Yes. Around that.

0:03:41.037,0:03:42.185
这是你的 拿好啊
This is yours. Take it.

0:03:42.541,0:03:44.434
嗯 沺沺你摘了一个酸的
Um. Tian Tian you've picked a sour one.

0:03:45.167,0:03:47.649
走吧 我们去看一下其它的
Let's go explore other places.

0:03:47.754,0:03:48.782
你吃一下这个 沺沺
Try this, Tian Tian.

0:03:50.580,0:03:51.095
甜吗
Is it sweet?

0:03:51.932,0:03:53.093
干嘛 酸的是不是
What? Sour, right?

0:03:53.093,0:03:54.571
酸的你别吐啊 浪费了
Don't spit on the ground. It's a waste.

0:03:55.205,0:03:55.452
走 
Let's go.

0:03:55.750,0:03:56.091
走嘛
Um.

0:04:01.750,0:04:02.711
走吧走吧
Let's go.

0:04:04.015,0:04:06.498
沺沺 沺沺
Tian Tian. Tian Tian.

0:04:07.478,0:04:10.647
现在让我老婆来摘一下 我来抱一下孩子
I want to relieve my wife from cradling our son and let her have some fun.

0:04:11.845,0:04:12.607
他睡着了
He's asleep.

0:04:13.577,0:04:17.887
刚才一直在那里笑 笑着笑着就睡着了
He was smiling all the time before he fell asleep.

0:04:21.179,0:04:23.168
你们摘呀 我抱着弟弟看你们摘
You guys pick while I and little brother watch.

0:04:23.168,0:04:23.501
好
OK.

0:04:24.900,0:04:26.508
沺沺摘大一点的
Tian Tian, go for the big ones.

0:04:26.517,0:04:27.145
红的 你看
Red, see?

0:04:27.659,0:04:28.439
好不好玩
Isn't this fun?

0:04:28.458,0:04:28.943
好玩
Yes.

0:04:29.115,0:04:30.922
等下回去煎鸡蛋给你吃好不好
You want some fried eggs when we get home?

0:04:31.598,0:04:32.007
鸡蛋
Eggs?

0:04:32.150,0:04:32.483
嗯
Um.

0:04:32.711,0:04:33.196
好
Sure.

0:04:33.196,0:04:33.672
就煎鸡蛋吃
Just fried eggs.

0:04:34.443,0:04:35.432
这个更甜
These ones are sweeter.

0:04:35.632,0:04:36.127
哪个
Which ones?

0:04:36.327,0:04:37.107
我来摘嘛
Let me pick.

0:04:37.944,0:04:38.725
我来给它摘了
Let me pick them.

0:04:39.010,0:04:39.533
这是不
These ones?

0:04:39.876,0:04:41.303
哇 好透明哦
Wow, it looks translucent.

0:04:41.303,0:04:42.759
沺沺 你也摘呀
Tian Tian, pick some more.

0:04:45.813,0:04:46.888
来嘛 我擦一下给你吃
Come, I wiped it.

0:04:49.048,0:04:49.476
甜不甜
Sweet?

0:04:50.038,0:04:50.399
嗯
Um.

0:04:52.007,0:04:53.358
我们这里以前没有这种的
This kind of tomatoes must be newly planted.

0:04:54.062,0:04:54.862
那干嘛呢
What do you mean?

0:04:55.176,0:04:56.622
这个应该是后面培育出来的
It is bred recently.

0:04:56.917,0:04:59.628
培育 我看到有那种子卖啊
It can't be. I saw people sell seeds before.

0:05:01.113,0:05:02.978
之前我买了很多给我妈妈种 
I even bought some for my mom to plant.

0:05:02.978,0:05:04.529
我们也买点回去种呗
We can also plant some.

0:05:06.260,0:05:06.660
可以
Sure.

0:05:13.006,0:05:14.300
你摘了一篮子啊
You have a basket full?

0:05:14.652,0:05:14.985
对
Yes.

0:05:16.165,0:05:18.059
妈妈可以给我一点小的吗
Mommy, can I get some smaller ones?

0:05:18.068,0:05:19.105
差不多了 我们去称一下吧
That's quite enough. Let's go weigh how much we got.

0:05:19.219,0:05:19.552
嗯
Um.

0:05:19.800,0:05:20.152
走
Let's go.

0:05:20.285,0:05:20.656
走嘛
Um.

0:05:21.655,0:05:23.101
看谁摘得多
Look who's got more.

0:05:23.273,0:05:24.862
叫奶奶一起 沺沺
Call grandma, Tian Tian.

0:05:37.117,0:05:38.078
边走边吃啊
Can't stop eating even when walking?

0:05:38.639,0:05:39.153
好吃吗
How is it?

0:05:39.400,0:05:40.076
好吃
Good.

0:05:40.142,0:05:41.170
下次我们又来摘嘛
We can come again if you want.

0:05:41.427,0:05:41.902
好
OK.

0:05:42.464,0:05:45.480
今天小孩子已经满了四个月
Our son is four month old today.

0:05:45.480,0:05:46.489
带他们出来玩一下
I want to bring them out and have some fun.

0:05:47.973,0:05:50.846
不出来我都不知道原来我们富顺还有这种好地方
We'd never know there's such fun place here at Fu Shun if we stayed at home.

0:05:53.824,0:05:54.196
好啦
Ok.

0:05:54.500,0:06:00.418
以后要是你们有时间的话都多带孩子家人出来玩一下
Bring your family out if you have time.

0:06:01.027,0:06:05.233
因为一辈子不可能就只有工作嘛
Because life isn't all about work.

0:06:05.233,0:06:06.822
好甜呀 好甜呀 妈妈
Sweet. It's sweet, mommy!

0:06:09.029,0:06:10.142
过几天又可以摘了 葡萄
Those grapes are to be picked soon.

0:06:10.608,0:06:12.540
妈妈 好甜呀 
Mommy, it's sweet!

0:06:12.540,0:06:13.149
还要吃吗
You want more?

0:06:13.691,0:06:14.167
还要
More!
