### ISSUE TITLE
[华农兄弟] 华农兄弟外出几天菜长起来了猪也回来了狗也长大了 - https://youtu.be/rUoL7KdeuYM

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1109]
https://youtu.be/rUoL7KdeuYM
<p>&#35270;&#39057;&#21457;&#24067;&#20110; May 31, 2020 at 06:00PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/rUoL7KdeuYM

#华农兄弟：外出几天，菜长起来了，猪也回来了，狗也长大了
#Huanong Brothers: We were out for the few days. The veggies are coming out, the pig is back and the dogs have grown up.

0:00:00.800,0:00:03.860
# 大家好  我們剛從北京回來 都出差出了
Hi everyone! We're just back from Beijing. We had been on a business trip for a,

0:00:04.420,0:00:05.580
# 將近一個多禮拜啊
for almost a week.

0:00:05.840,0:00:08.420
# 你看 回來 這個魚缸都變成這樣子了
Look! Back home, the fish tank has already become this piece of mess.

0:00:10.100,0:00:11.100
# 還有幾條龍蝦
There are still some crayfish.

0:00:11.440,0:00:12.240
# 幸存者
The survivors

0:00:12.660,0:00:13.600
# 其他全沒啦
The rest are all gone.

0:00:14.660,0:00:16.020
# 你看  這個龍蝦
Look! This crayfish,

0:00:16.960,0:00:20.520
# 現在都  睡在地上  耍賴啊  它要  要離開這裡
They're all, laying on the ground, shamelessly. They wanna leave this place.

0:00:22.000,0:00:25.840
# 好啦  我回來了  給你接水了 現在就有水來了
Alright! I'm now back. I'm catching water for you. The water is coming right away.

0:00:27.220,0:00:29.940
# 現在管子掉子 沒沒了  這裡都乾了
Now the pipe is gone. Here's no more water and it's already dried here.

0:00:30.640,0:00:32.300
# 魚也還有哦  還有幾條魚
There are still some fish, a couple of fish.

0:00:32.980,0:00:33.700
# 還活著
They survived.

0:00:34.300,0:00:35.500
# 到時條清洗一下
I'm gonna wash the tank later.

0:00:37.200,0:00:39.360
# 草就是長得  到處都是
And the weed is growing everywhere.

0:00:39.800,0:00:40.980
# 長滿了野草
The weed is everywhere.

0:00:47.440,0:00:51.180
# 你看  這個雞  雞鴨現在還在  那鵝也還在
Look! The chicks, the chicks and the ducks are still here, and the geese too.

0:00:51.920,0:00:53.920
# 我以為快餓扁了嘞  沒餓扁
I thought they were starved to death, but not yet.

0:01:05.040,0:01:05.860
# 又胖了
They get fat again.

0:01:12.040,0:01:14.340
# 全部過來啦  今天早上我餵了它們一下
They're all coming. I fed them something this morning.

0:01:19.920,0:01:21.400
# 這鴨子越來越漂亮啦
The ducks are getting prettier day by day,

0:01:22.820,0:01:23.780
# 這個鵝也是
and the geese too.

0:01:27.420,0:01:29.720
# 現在都沒那麼胖啦  都很結實
They're no longer that fat now, and are really firm instead.

0:01:31.580,0:01:33.360
# 誒  那公雞  那公雞
Ey? The rooster, the rooster,

0:01:34.280,0:01:35.360
# 公雞跑哪裡去了
where has the rooster fled to?

0:01:46.660,0:01:48.540
# 你看  這箱蜜蜂好像也跑了
Look! The bees in the box seem to have run away too.

0:01:49.040,0:01:50.020
# 沒蜂蜜了
There's no more honey,

0:01:50.640,0:01:51.660
# 都沒蜜蜂了  (註︰他經常把「蜂蜜」和「蜜蜂」說錯，這裡稍為配合一下)
no more honey bees.

0:01:59.980,0:02:01.060
# 不知道跑哪裡去了
I wonder where they are now.

0:02:02.080,0:02:02.860
# 還有蜂蜜
Here's still some honey.

0:02:04.160,0:02:05.160
# 哦  還有一點點
Oh? Here's still a tiny little bit.

0:02:05.900,0:02:07.220
# 它們肯定這兩天跑了
They must have run away in this couple of days.

0:02:07.820,0:02:08.700
# 看到我不在了
They ran away,

0:02:09.220,0:02:10.960
# 看到我不在這裡它就跑了
ran away, seeing that I was not here.

0:02:14.580,0:02:16.800
# 等下它們  不知道它們會不會到這裡來
I wonder, who knows if they're coming back here.

0:02:34.280,0:02:36.040
# 你看  這個象草那麼高啦
Look! The elephant grass is that tall now.

0:02:36.480,0:02:38.300
# 給(註︰我聽到「割」)點給鵝吃  看它吃不吃
Let me cut some for the geese, and see if they like it.

0:02:44.520,0:02:45.440
# 那麼嫩
It's so tender.

0:02:49.400,0:02:50.380
# 它們看到都怕
The presence is already enough to scare them.

0:03:01.360,0:03:03.320
# 來都不來  不吃象草
They're not even coming. They don't like elephant grass.

0:03:08.640,0:03:09.640
# 你看  這個
Look! This is,

0:03:10.360,0:03:11.760
# 這個果子全熟啦
these fruits are all ripe now.

0:03:15.720,0:03:16.800
# 像藍莓一樣
It's like blueberries.

0:03:18.680,0:03:19.940
# 有種怪怪的味道
There's a funny taste.

0:03:22.200,0:03:23.360
# 可能我口味比較重
Perhaps because of my preference to strong tastes,

0:03:24.220,0:03:26.440
# 我們吃不下  我怎麼覺得那麼好吃
it tastes somehow rather nice to me. But they all can't stand it.

0:03:26.840,0:03:28.380
# 還小的時候我們吃了好多這個
I ate a lot of this stuff when I was a kid.

0:03:38.040,0:03:39.260
# 好啦  不能吃那麼多
Alright! More doesn't always mean better.

0:03:44.420,0:03:46.940
# 好  我下去把那個草先割一下這個草
Good! I'm going down there and have the weed, and clear the weed first.

0:03:47.320,0:03:49.020
# 到處都是那個野草都長滿了
Everywhere is the weed. It's growing,

0:03:49.680,0:03:50.740
# 長滿了那個野草
growing everywhere.

0:03:50.980,0:03:51.800
# 我們走的時候
By the time we left,

0:03:52.060,0:03:54.200
# 就那麼高一點點  現在都那麼高啦
they reached not higher than this. But they have become that tall now,

0:03:54.580,0:03:55.380
# 才一個禮拜
in just one week.

0:03:56.100,0:03:57.700
# 長得好快的  很茂盛
They grow really fast, and very well.

0:03:58.180,0:03:58.780
# 這個葉子
The leaves,

0:03:59.820,0:04:01.000
# 營養很豐富的
are very nutritious.

0:04:01.300,0:04:03.400
# 下次我去兄弟家牽一頭羊回來
Next time I'll take a goat here, from my buddy's place.

0:04:03.760,0:04:04.640
# 給它吃一下
Let it have a try,

0:04:05.780,0:04:06.900
# 嘗一下這里的味道
try the flavour here.

0:04:08.100,0:04:08.900
# 很好吃的哦
It's really tasty, you know.

0:04:10.500,0:04:12.720
# 你看  這紫色的也是長得那麼漂亮啦
Look! The violet ones are also so pretty now.

0:04:30.080,0:04:32.760
# 你看這個攀蒲  這是攝影小哥奶奶種的哦
Have a look at the "panpu" (pumpkins). They were planted by Mr. Cameraman's grandma.

0:04:33.300,0:04:34.560
# 我們走的時候只有
By the time we left, they were only,

0:04:34.960,0:04:36.720
# 只有 只有三十公分左右
only, only about thirty centimetres.

0:04:37.700,0:04:38.900
# 現在  現在都
Now, now they're,

0:04:39.420,0:04:40.240
# 三四米啦
already three or four metres.

0:04:40.760,0:04:41.600
# 長得好快呀
They grow really fast.

0:04:43.440,0:04:44.020
# 這草
The weed...

0:04:49.660,0:04:51.880
# 這個攀蒲一個都可以長二三十斤哦
The "panpu" can be up to ten to fifteen kilograms each.

0:04:52.540,0:04:53.480
# 把肥料搞好來
If they're well fertilised,

0:04:54.080,0:04:54.800
# 就可以長
they can even,

0:04:55.060,0:04:57.180
# 長個四五十斤都有可能長得出來
even be up to twenty or twenty five kilograms.

0:04:58.820,0:05:00.300
# 到時候我們就有攀蒲吃啦
We'll have panpu by that time.

0:05:05.840,0:05:06.740
# 太高啦
It's too tall!

0:05:07.980,0:05:09.400
# 這草長得好快的
The weed is growing really fast.

0:05:15.100,0:05:15.860
# 看一下西瓜
Let's have a look at the watermelons.

0:05:16.840,0:05:17.640
# 西瓜在這上面
The watermelons are up there.

0:05:24.960,0:05:26.020
# 你看這個西瓜
Look! The watermelons,

0:05:26.420,0:05:28.500
# 我走的時候就那麼長一點  現在都那麼長啦
By the time I left, they were not longer than this. But they're that long now.

0:05:29.680,0:05:30.800
# 長得好快啊
They grow really fast.

0:05:38.740,0:05:39.700
# 那邊還有
More over there

0:05:40.560,0:05:42.280
# 這個西瓜長那麼長啦
This watermelon, is that long now.

0:05:42.860,0:05:43.680
# 還有一個百香果
And here's a passion fruit.

0:05:44.200,0:05:46.400
# 啊  這個百香果  草都那麼
Ah! This passion fruit, the weed is so,

0:05:47.380,0:05:48.120
# 那麼長
so long!

0:05:51.180,0:05:51.920
# 你看這個薑
Have a look at the ginger!

0:05:52.320,0:05:53.920
# 上次我們走的時候都還沒出來
They were still under the earth when we left.

0:05:53.920,0:05:55.100
# 你看現在長那麼快
Look! They're growing so fast now.

0:05:55.680,0:05:56.460
# 全出來了
They've all come out.

0:05:57.860,0:05:58.500
# 長得好快啊
They grow really fast.

0:05:59.840,0:06:00.540
# 這邊也是
This side too

0:06:03.100,0:06:03.840
# 就一點點
Just a tiny little bit

0:06:07.180,0:06:08.120
# 你看這個西紅杮
Have a look at the tomatoes!

0:06:08.400,0:06:11.620
# 這是豬種的哦  那條大公豬  那些小豬  跟大豬
They were planted by the pigs, I mean that big boar and those piggies, and the big ones.

0:06:11.900,0:06:12.900
# 一起種的西紅杮
They planted the tomatoes together.

0:06:13.660,0:06:14.860
# 現在長那麼茂盛啦
They're growing so well now.

0:06:16.240,0:06:17.360
# 到時我們就可以摘啦
We can pick them later.

0:06:24.320,0:06:26.160
# 現在我們插播一個小廣告
Now we're embedding an advertisement here.

0:06:26.780,0:06:30.360
# 你看  這個就是我們逢年過節都會吃的  這個月亮巴
Look! This is a snack that we all enjoy during festivals and celebrations. It's called "yue liang ba" (lit: moon crust)

0:06:31.520,0:06:33.100
# 我們土話叫  ****  (註︰這真是原字幕的寫法)
In our native dialect, it's called **** (untranslatable and untrasliterable)

0:06:33.480,0:06:37.060
# 你看  有黃豆的  有花生的
Look! Some are with soybeans, some are with peanuts.

0:06:37.780,0:06:40.040
# 逢年過節都會做點來吃
They always have a place on the table during festivals and celebrations.

0:06:40.540,0:06:42.200
# 現在你看  這個包裝還可以哦
And now, look! The packaging is not bad.

0:06:43.420,0:06:44.300
# 它的優點就是
The plus is,

0:06:45.460,0:06:45.960
# 很好吃
that it's really tasty.

0:06:46.840,0:06:49.000
# 缺點  就是吃多了會上火
The minus is, that eating too many may give you a sore throat.

0:06:51.160,0:06:52.720
# 給大家看一下  這個
Let me show you, this is,

0:06:53.380,0:06:54.280
# 不怎麼油膩哦
it's not that oily.

0:06:55.060,0:06:56.040
# 是烤出來的
Cuz it's roasted.

0:06:57.160,0:06:57.760
# 很香
It smells really good!

0:07:00.580,0:07:02.180
# 肚子餓了  可以吃一點
You can have some, whenever you're hungry.

0:07:03.740,0:07:07.300
# 特別是去  去外面玩的時候  多帶點這個
Especially when you're having an outing, taking more of this snack with you,

0:07:08.820,0:07:09.580
# 可以充饑
can alleviate your hunger.

0:07:13.980,0:07:15.560
# 好啦  我們去看一下那個小狗
Alright! Let's have a look at the doggies.

0:07:16.160,0:07:17.240
# 你看  大公豬回來啦
Look! The big boar is back.

0:07:18.360,0:07:18.860
# 來
C'mon!

0:07:19.180,0:07:19.680
# 吃點這個
Eat some!

0:07:22.700,0:07:24.760
# 搞了一點點飼料給它們  兩下就吃光啦
I've fetched them a tiny little bit of fodder. They finished everything in just a second.

0:07:25.400,0:07:26.680
# 看來它肚子真的餓啦
It seems that it's really hungry.

0:07:33.160,0:07:34.100
# 你看它的豬耳朵
Have a look at its pig ears.

0:07:34.880,0:07:36.240
# 它的豬耳朵肯定好吃
Its pig eats must be very tasty.

0:07:37.360,0:07:39.640
# 這個肉  我再去摘點飼料給它
The pork... I'm gonna fetch more fodder.

0:07:44.340,0:07:45.660
# 你看  現在好溫順啊
Look! It's so nice and gentle now.

0:07:48.540,0:07:50.180
# 走開先  走開先  等一下來
Go 'way, go 'way first. It's not yet your turn.

0:07:56.880,0:07:57.580
# 這狗在這裡
The dog is here,

0:07:57.960,0:07:59.340
# 想要我安慰它一樣
he seems to be asking for my comfort.

0:07:59.900,0:08:01.480
# 老是伸  把脖子伸過來
He keeps on stretch, stretching his neck towards me.

0:08:02.060,0:08:03.380
# 想要我給它按摩
He wants me to give him a massage.

0:08:03.600,0:08:04.320
# 好啦好啦好啦
Alright, alright, alright!

0:08:05.180,0:08:05.680
# 誒呦
Eyo?

0:08:06.020,0:08:06.600
# 弄痛你啦
Did I hurt you?

0:08:10.780,0:08:11.340
# 下去一點
Get away a bit!

0:08:15.160,0:08:16.080
# 哇  這個毛
Wa! The hair,

0:08:16.580,0:08:17.900
# 好  好硬啊
is so, so stiff.

0:08:26.440,0:08:27.320
# 再去搞點給你吃
I'm gonna give you more.

0:08:31.640,0:08:32.620
# 這個母狗
This mother,

0:08:33.180,0:08:34.160
# 三年多啦
is more than three years old.

0:08:35.480,0:08:38.340
# 它的子孫後代都不知道有多少  我都數不出來啦
She now has countless children and grand children. I've already lost the count.

0:08:45.220,0:08:47.520
# 你的毛怎麼這樣子啦  你又不胖啦
What happened to your coat? You're not chubby anymore.

0:08:51.240,0:08:52.720
# 過兩天我帶你去洗澡  去不去
Let me take you to have a bath a few days later, shall I?

0:08:53.800,0:08:55.920
# 誒呀  站一站  我看一下你身上
Eya! Stand up! Let me have a look at your body.

0:08:57.120,0:08:57.900
# 變成這樣子啦
You've changed so much!

0:09:09.140,0:09:10.240
# 跑到我老家來啦
It comes to my home.

0:09:20.820,0:09:22.360
# 這裡種了幾個桃樹哦
I've planted some peach trees here,

0:09:23.240,0:09:24.160
# 就在我家門口
right in front of my door.

0:09:25.820,0:09:28.700
# 到時候有桃子的時候我就把它做個籬笆  把它圍起來
When there are peaches, I'll, I'll make a fence, and fence up this area.

0:09:30.740,0:09:31.380
# 多好啊
So nice!

0:09:32.000,0:09:33.220
# 現在還小  這個桃樹
They're still small, the peach trees.

0:09:35.960,0:09:36.800
# 你看  那個雞
Have a look at that chicken.

0:09:37.720,0:09:39.380
# 專吃草的  太壞啦
It eats grass, and only grass. Bad guy!

0:09:40.980,0:09:42.920
# 這個放  以前種了那個草皮的哦
Here's tur, here used to be turfed, you know.

0:09:43.080,0:09:44.340
# 現在被它吃成這樣子啦
But it looks like this now, because of the chicken.

0:09:45.440,0:09:47.540
# 到時候要把雞關起來  不能把它放出來啦
I'll lock up all the chicks later. They shouldn't be allowed to run around.

0:09:48.380,0:09:50.340
# 帶到下面  帶到下面去養
I'll bring them down there, keep them down there.

0:10:02.460,0:10:03.120
# 不要走哦
Don't run away.

0:10:03.900,0:10:05.080
# 以前跟著豬混
He loved mingling with the pigs.

0:10:05.880,0:10:07.220
# 現在跟豬混不下去啦
But now he can no longer mingle with the pigs.

0:10:07.540,0:10:08.380
# 就跟我混啦
So he mingles with me.

0:10:10.500,0:10:11.100
# 是不是
Am I right?

0:10:11.740,0:10:12.960
# 豬都不給你東西吃
The pigs were not giving you any food.

0:10:13.020,0:10:14.620
# 它也不割點肉給你吃哦
They didn't cut their pork for you.

0:10:15.240,0:10:16.960
# 看一下  我經常給肉給你吃
Have a look! I always give you meat.

0:10:17.860,0:10:19.420
# 我是經常給豬肉給你吃哦
I always give you pork, right?

0:10:26.260,0:10:26.880
# 現在都
He's now,

0:10:27.380,0:10:28.060
# 很聽話啦
a very good boy.

0:10:35.240,0:10:37.020
# 你看  看一捏它它就  享受 (註︰這裡的享受是多了)
Look! Once I start pinching him, he,

0:10:37.520,0:10:38.100
# 享受
he enjoys.

0:10:38.440,0:10:38.940
# 看到沒有
See?

0:10:39.360,0:10:39.860
# 跟它
I give him a,

0:10:40.360,0:10:41.000
# 頸椎按  (註︰我好像聽到「脊椎」)
a spinal mass,

0:10:41.360,0:10:42.280
# 頸椎按摩 
spinal massage,

0:10:42.800,0:10:43.660
# 脖子按摩啊
a neck massage.

0:10:47.540,0:10:49.640
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.
