### ISSUE TITLE
【美食作家王刚】 豆腐煎肉末 - https://youtu.be/R4jxabZObJI

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1110]
**视频链接**：https://youtu.be/R4jxabZObJI

视频时长4:18，预计发布时间为北京时间6月3日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“豆腐煎肉末”“肉馅豆腐夹”的家常做法，汁鲜味浓，特别下饭

简介
同学们好，今天给大家分享一道“夹豆腐”，属鲁菜系，山东传统名菜，汁鲜味浓，特别下饭。并且蛋、肉、豆腐多种蛋白质结合，营养丰富，小孩子特别喜欢。此菜重点在于煎的过程中一定要保持小火并且煎满14分钟，这样才能保证豆腐里面的肉末熟透。

本期菜品【豆腐煎肉末】【肉馅豆腐夹】
【主料】
瘦肉（2小块）
豆腐（1小块）
【辅料】
生姜（1小块）
小蒜头（适量）
干淀粉（适量）
鸡蛋（几个）
植物油（适量）
葱花（适量）
【调味料】
食用盐（2克）
胡椒粉（少许）
蚝油（3克）
生抽酱油（5克）
老抽酱油（2克）

字幕
0:00:00.160,0:00:01.320
哈喽大家好我是王刚

0:00:01.320,0:00:03.540
本期视频我给大家分享一道家常菜

0:00:03.820,0:00:05.060
豆腐煎肉末

0:00:05.340,0:00:07.260
首先我们准备瘦肉2小块

0:00:07.393,0:00:08.954
切成小片之后剁碎备用

0:00:09.145,0:00:11.192
同学们最好选择略带肥油的瘦肉

0:00:11.222,0:00:12.754
这样口感和香味更佳

0:00:14.889,0:00:17.290
肉末剁好之后放入碗中下一步开始调味

0:00:17.378,0:00:19.057
准备生姜1小块剁碎备用

0:00:21.045,0:00:22.783
准备适量的小葱头剁碎备用

0:00:26.259,0:00:27.805
碗中加入食用盐1克

0:00:28.114,0:00:29.248
加入少许胡椒粉

0:00:30.088,0:00:31.413
加入生抽酱油2克

0:00:32.827,0:00:34.653
然后搅拌至粘稠上劲即可

0:00:36.627,0:00:38.203
下一步开始准备处理豆腐

0:00:38.689,0:00:40.589
准备豆腐1小块切成薄片备用

0:00:40.618,0:00:42.194
同学们最好选择老豆腐

0:00:42.238,0:00:43.961
这样切的时候才不容易碎

0:00:47.010,0:00:49.617
豆腐切好之后再加入适量的肉末夹在中间

0:01:00.029,0:01:02.754
夹好肉末之后在整个豆腐周围涂抹上干淀粉

0:01:02.886,0:01:05.743
这一步的目的是防止豆腐下锅煎的时候散开

0:01:13.387,0:01:14.860
最后再撒上剩余的淀粉

0:01:16.141,0:01:17.437
下一步开始调料汁

0:01:17.555,0:01:19.027
碗中加入食用盐1克

0:01:19.587,0:01:21.060
加入生抽酱油3克

0:01:22.076,0:01:23.210
加入蚝油3克

0:01:24.683,0:01:25.935
加入老抽2克

0:01:30.515,0:01:32.061
调好味之后搅拌均匀

0:01:32.871,0:01:34.904
中途再加入适量的干淀粉拌匀

0:01:41.192,0:01:43.019
最后准备鸡蛋几个搅散备用

0:01:49.882,0:01:51.030
下一步开始制作

0:01:51.222,0:01:52.636
首先我们把锅烧热

0:01:53.593,0:01:55.522
锅烧热之后加入适量的油滑锅

0:01:55.905,0:01:59.219
同学们这一步不能马虎否则豆腐下锅必粘

0:02:00.854,0:02:03.070
热油倒出之后再加入少许的底油

0:02:04.241,0:02:05.419
下一步开始煎豆腐

0:02:06.774,0:02:08.733
首先我们将豆腐均匀地裹上鸡蛋液

0:02:08.983,0:02:11.944
这一步的目的是让豆腐与豆腐之间连接得更紧密

0:02:25.066,0:02:27.746
豆腐摆好形状之后调微小火煎制10分钟

0:02:27.893,0:02:29.852
同学们这一步必须微小火慢煎

0:02:29.896,0:02:31.664
否则豆腐中间的肉不熟

0:02:38.335,0:02:40.942
煎制8分钟之后将剩余的蛋液下锅

0:02:51.134,0:02:53.240
然后继续转微小火煎至定型

0:03:01.340,0:03:03.976
煎制10分钟之后反过来再继续煎4分钟

0:03:08.954,0:03:11.163
煎制4分钟之后将豆腐饼倒出备用

0:03:13.991,0:03:17.304
然后我们在锅中加入事先调好的料汁开中小火烧开

0:03:26.023,0:03:27.997
当汁水浓稠之后先盛出一半

0:03:30.088,0:03:32.459
然后将豆腐下锅均匀地粘上汤汁即可

0:03:44.786,0:03:46.774
最后撒上适量的葱花即可上菜

0:03:47.680,0:03:50.160
一道非常美味的豆腐煎肉末就制作完成

0:03:59.220,0:04:17.000
下面开始技术总结
第一，最好选择紧实一些的老豆腐，这样不容易碎
第二，料汁可以适量的多一些，在出菜的时候才能均匀的挂上汤汁以保证足味
第三，煎豆腐必须小火煎够14分钟，否则中间的肉末不熟
豆腐煎鸡蛋的技术总结完毕


```

**Comment by siyusun6918** [comment]
认领

**Comment by siyusun6918** [comment]
厨师长教你：“豆腐煎肉末”“肉馅豆腐夹”的家常做法，汁鲜味浓，特别下饭
Chef Wang teaches you: Homestyle “Fried Stuffed Tofu”, with a delicious sauce, goes well with rice

简介
同学们好，今天给大家分享一道“夹豆腐”，属鲁菜系，山东传统名菜，汁鲜味浓，特别下饭。并且蛋、肉、豆腐多种蛋白质结合，营养丰富，小孩子特别喜欢。此菜重点在于煎的过程中一定要保持小火并且煎满14分钟，这样才能保证豆腐里面的肉末熟透。

本期菜品【豆腐煎肉末】【肉馅豆腐夹】
【主料】
瘦肉（2小块）
豆腐（1小块）
【辅料】
生姜（1小块）
小蒜头（适量）
干淀粉（适量）
鸡蛋（几个）
植物油（适量）
葱花（适量）
【调味料】
食用盐（2克）
胡椒粉（少许）
蚝油（3克）
生抽酱油（5克）
老抽酱油（2克）

Hello! Today I’m going to share with you a “Fried Stuffed Tofu”, which is a famous dish in Shandong cuisine, with a delicious sauce and goes well with rice. Also, with egg, meat, and tofu, multiple proteins were used to enrich the nutrition, and children love it. The key to this dish is to maintain a low heat for at least 14 minutes during the frying process in order to ensure the ground meat stuffed in the tofu is cooked through. 

For today’s dish [Fried Stuffed Tofu] [Fried Tofu Sandwich]
[Main Ingredients]
Lean meat (two small pieces)
Tofu (one small piece)
[Other Ingredients]
Ginger (one piece)
Shallot (some)
Dry starch (some)
Eggs (a few)
Vegetable oil (some)
Chopped green onion (some)
[Seasoning]
Salt (2 grams)
White pepper powder (a little)
Oyster sauce (3 grams)
Light soy sauce (5 grams)
Dark soy sauce (2 grams)


字幕
0:00:00.160,0:00:01.320
哈喽大家好我是王刚
Hello, I am Chef Wang

0:00:01.320,0:00:03.540
本期视频我给大家分享一道家常菜
For today’s video, I’m going to share with you a homestyle dish

0:00:03.820,0:00:05.060
豆腐煎肉末
Fried stuffed tofu

0:00:05.340,0:00:07.260
首先我们准备瘦肉2小块
First, prepare two pieces of lean meat

0:00:07.393,0:00:08.954
切成小片之后剁碎备用
Slice and then chop them 

0:00:09.145,0:00:11.192
同学们最好选择略带肥油的瘦肉
It’s better to choose lean meat with a little fat on it

0:00:11.222,0:00:12.754
这样口感和香味更佳
The texture and the flavor is better 

0:00:14.889,0:00:17.290
肉末剁好之后放入碗中下一步开始调味
Put the chopped meat in a bowl, and start seasoning

0:00:17.378,0:00:19.057
准备生姜1小块剁碎备用
Chop a small piece of ginger

0:00:21.045,0:00:22.783
准备适量的小葱头剁碎备用
Chop some shallot

0:00:26.259,0:00:27.805
碗中加入食用盐1克
Add one gram of salt in the bowl

0:00:28.114,0:00:29.248
加入少许胡椒粉
Add some white pepper powder

0:00:30.088,0:00:31.413
加入生抽酱油2克
Add 2 grams of light soy sauce

0:00:32.827,0:00:34.653
然后搅拌至粘稠上劲即可
Mix it until tense and sticky 

0:00:36.627,0:00:38.203
下一步开始准备处理豆腐
Next step, prepare the tofu

0:00:38.689,0:00:40.589
准备豆腐1小块切成薄片备用
Prepare the tofu into thin slices

0:00:40.618,0:00:42.194
同学们最好选择老豆腐
Firm tofu is the best choice

0:00:42.238,0:00:43.961
这样切的时候才不容易碎
It’s less easy to break while slicing

0:00:47.010,0:00:49.617
豆腐切好之后再加入适量的肉末夹在中间
Apply some meat stuffing in between the sliced tofu

0:01:00.029,0:01:02.754
夹好肉末之后在整个豆腐周围涂抹上干淀粉
Cover the tofu with dry starch after stuffing

0:01:02.886,0:01:05.743
这一步的目的是防止豆腐下锅煎的时候散开
This step is to prevent tofu from breaking apart while frying

0:01:13.387,0:01:14.860
最后再撒上剩余的淀粉
Last, spread the remaining starch 

0:01:16.141,0:01:17.437
下一步开始调料汁
Next step, prepare the sauce

0:01:17.555,0:01:19.027
碗中加入食用盐1克
Add one gram of salt in the bowl

0:01:19.587,0:01:21.060
加入生抽酱油3克
Add three grams of light soy sauce

0:01:22.076,0:01:23.210
加入蚝油3克
Add three grams of oyster sauce

0:01:24.683,0:01:25.935
加入老抽2克
Add two grams of dark soy sauce

0:01:30.515,0:01:32.061
调好味之后搅拌均匀
Mix well after seasoning

0:01:32.871,0:01:34.904
中途再加入适量的干淀粉拌匀
Add some dry starch, continue mixing

0:01:41.192,0:01:43.019
最后准备鸡蛋几个搅散备用
Last, whip a few eggs

0:01:49.882,0:01:51.030
下一步开始制作
Next, start cooking

0:01:51.222,0:01:52.636
首先我们把锅烧热
First, heat up the wok

0:01:53.593,0:01:55.522
锅烧热之后加入适量的油滑锅
Use some oil to rinse the wok

0:01:55.905,0:01:59.219
同学们这一步不能马虎否则豆腐下锅必粘
DO NOT skip this step, or the tofu will stick to the wok

0:02:00.854,0:02:03.070
热油倒出之后再加入少许的底油
Pull out the hot oil, then add some base oil

0:02:04.241,0:02:05.419
下一步开始煎豆腐
Next step, fry the tofu

0:02:06.774,0:02:08.733
首先我们将豆腐均匀地裹上鸡蛋液
First, we coat the tofu with egg wash

0:02:08.983,0:02:11.944
这一步的目的是让豆腐与豆腐之间连接得更紧密
In order to tighten up between tofu

0:02:25.066,0:02:27.746
豆腐摆好形状之后调微小火煎制10分钟
After placing the tofu, change to low heat and fry for 10 minutes

0:02:27.893,0:02:29.852
同学们这一步必须微小火慢煎
It must be fried with a low heat

0:02:29.896,0:02:31.664
否则豆腐中间的肉不熟
Or the meat stuffing between the tofu won’t cook through

0:02:38.335,0:02:40.942
煎制8分钟之后将剩余的蛋液下锅
Add the rest of the egg wash after 8 minutes

0:02:51.134,0:02:53.240
然后继续转微小火煎至定型
Then keep frying with low heat until the shape is settled

0:03:01.340,0:03:03.976
煎制10分钟之后反过来再继续煎4分钟
After 10 minutes, flip over and fry for another 4 minutes

0:03:08.954,0:03:11.163
煎制4分钟之后将豆腐饼倒出备用
Take the tofu pancake out after 4 minutes

0:03:13.991,0:03:17.304
然后我们在锅中加入事先调好的料汁开中小火烧开
Then, pull the prepared sauce in the wok and simmer it to a boil

0:03:26.023,0:03:27.997
当汁水浓稠之后先盛出一半
After the sauce has thickened, pull out half of it 

0:03:30.088,0:03:32.459
然后将豆腐下锅均匀地粘上汤汁即可
Put the tofu back to the wok, and coat it evenly with the sauce

0:03:44.786,0:03:46.774
最后撒上适量的葱花即可上菜
Last, decorate with some chopped green onion

0:03:47.680,0:03:50.160
一道非常美味的豆腐煎肉末就制作完成
A very delicious fried stuffed tofu is done

0:03:59.220,0:04:17.000
下面开始技术总结
第一，最好选择紧实一些的老豆腐，这样不容易碎
第二，料汁可以适量的多一些，在出菜的时候才能均匀的挂上汤汁以保证足味
第三，煎豆腐必须小火煎够14分钟，否则中间的肉末不熟
豆腐煎鸡蛋的技术总结完毕
Conclusion
Firstly, it’s better to use firm tofu, it’s less easy to break apart
Secondly, the sauce should be a little more than enough to coat the tofu evenly to ensure the flavor
Thirdly, the tofu has to be fried with low heat for at least 14 minutes, otherwise, the meat stuffing in between might not be cooked through
That’s all for the conclusion for “fried stuffed tofu”
