### ISSUE TITLE
【美食作家王刚】 油温 - https://youtu.be/caG9Ndm6ykM

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1114]
**视频链接**：https://youtu.be/caG9Ndm6ykM

视频时长7:52，预计发布时间为北京时间6月4日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享厨房知识：“油温”是什么，“高低油温”的特殊使用方法，干货技巧，举一反三

简介
同学们好，今天咱们来聊聊“油温”，相信经常看我视频的朋友肯定是知道中式厨房中一般以“成”来界定油温，“一成”等于30摄氏度，以此类推。而相对的低油温和高油温在烹饪过程中有着不一样的作用和使用方法，今天就来列举几种特殊的使用方法来供大家参考，在以后的烹饪过程中可以举一反三，来根据食材的性状和特性来掌握相对的油温。

字幕
0:00:00.405,0:00:03.686
哈喽 大家好 今天我们拍一个不做菜的视频

0:00:03.730,0:00:07.323
拍一个测试油温的一个视频

0:00:07.438,0:00:11.442
这个是我们准备的豆腐 有鱼有茄子

0:00:11.848,0:00:14.404
四伯爷 那你晓得啥子油温炒啥子菜不哦

0:00:14.850,0:00:17.170
我清不到你啥子油温炒啥子菜

0:00:17.914,0:00:22.061
我就是管你对不对 反正在锅里烧热就可以煎

0:00:23.177,0:00:27.049
假如这个茄子哈如果是低油温下去的话是不是要吸很多油

0:00:27.283,0:00:27.809
嗯

0:00:28.439,0:00:32.400
我伯爷都知道这个低油温下锅茄子是百分百吸油的

0:00:32.473,0:00:33.985
它会把这个吸得很饱满

0:00:34.300,0:00:37.946
然后高油温下去它是在往外面排斥

0:00:38.035,0:00:42.271
所以我们炒茄子用高油温一直炒的话它不会吸油

0:00:42.954,0:00:45.626
然后就是我们这个鱼 还有这个鱼

0:00:46.377,0:00:50.438
鱼下锅煎的话一定要高油温一下子把鱼皮给它煎熟

0:00:50.490,0:00:53.559
如果慢慢煎很大概率会粘锅

0:00:53.559,0:00:56.022
第一个是粘锅 第二个是容易把鱼煎烂

0:00:56.064,0:00:58.768
不管是煎草鱼鲤鱼还是鲫鱼

0:00:59.081,0:01:00.688
都要用高油温来煎

0:01:00.866,0:01:02.755
等会我们煎点豆腐给你看一下嘛

0:01:03.061,0:01:03.385
要的啊

0:01:03.389,0:01:04.805
给你做个示范打个样

0:01:05.489,0:01:08.164
好 那我们现在就到锅上面去操作这个东西

0:01:09.125,0:01:09.903
给你们看一下

0:01:11.232,0:01:17.331
好 现在我们来简单用一个低油温来炸一个花生米

0:01:17.759,0:01:18.613
先倒油

0:01:21.104,0:01:22.708
这个是我们准备的花生米

0:01:23.019,0:01:24.344
直接下锅

0:01:24.639,0:01:27.511
四伯爷 你晓得花生米为什么要冷油下锅去炸不

0:01:28.527,0:01:32.299
拿下去炸它才炸得泡撒

0:01:33.357,0:01:34.315
如果是高油温安

0:01:34.683,0:01:35.758
高油温不得行

0:01:36.097,0:01:36.671
不得行嘎

0:01:36.951,0:01:37.923
高油温要炸糊

0:01:38.409,0:01:39.985
嗯 然后中间还是生的

0:01:40.147,0:01:41.089
嗯 对对对

0:01:42.091,0:01:47.216
我们炸这个花生米就是冷油下去随着油温的加热

0:01:47.378,0:01:49.042
花生米中间也开始热

0:01:49.234,0:01:52.709
如果这个花生米你在锅里拿出来吃已经可以了

0:01:53.019,0:01:54.801
拿出来放一会儿它自己会熟

0:01:56.921,0:02:03.652
所以我们像类似炸这个核桃啊花生米啊腰果呀这些

0:02:03.799,0:02:05.463
必须用低油温下锅

0:02:07.511,0:02:10.409
好 现在这个油温大概已经升到了5成

0:02:11.178,0:02:14.182
我们转中小火保持这个油温

0:02:15.243,0:02:18.291
然后炸这个花生米就是我们很典型的

0:02:18.674,0:02:21.060
3成油温左右就下花生米

0:02:21.148,0:02:23.711
或者是冷油直接下都可以

0:02:24.595,0:02:26.494
千万不要把油温烧得太热了

0:02:27.231,0:02:29.558
油温的话每一成30度

0:02:30.162,0:02:37.670
那我们经常能够用得到就是4成5成6成7成就可以了

0:02:37.670,0:02:38.869
34567

0:02:39.720,0:02:40.677
好像可以了

0:02:47.025,0:02:50.176
那我们现在来煎一个豆腐

0:02:53.873,0:02:55.346
现在是属于一个高油温

0:02:55.405,0:02:57.142
大概是6成油温下的豆腐

0:02:59.852,0:03:04.683
我们油温高一点的话这个豆腐不会煎烂

0:03:05.994,0:03:08.556
你看 这样子翻都没事

0:03:10.368,0:03:11.266
看到没有四伯爷

0:03:12.106,0:03:16.892
油温高它下去表面马上就有一层金黄金黄的

0:03:18.026,0:03:20.765
好 我们把这块拿出来

0:03:20.868,0:03:22.916
然后下一个试一下低油温

0:03:31.443,0:03:33.387
我们这个是低油温下去煎

0:03:33.947,0:03:35.405
这个豆腐现在是低油温

0:03:35.625,0:03:38.335
如果说油温比较低的情况下我们去翻它

0:03:38.910,0:03:40.058
看到没就烂了

0:03:41.649,0:03:42.562
这个时候就烂了

0:03:43.151,0:03:46.229
所以这里我们做一个实验就可以看得出来这个豆腐

0:03:46.966,0:03:50.721
低油温煎 像这样子没有煎出锅巴出来

0:03:50.736,0:03:53.637
没有煎出黄黄的东西出来豆腐非常容易碎

0:03:56.524,0:03:57.658
而且还粘勺子

0:03:59.823,0:04:01.237
好 我们把它拿出来

0:04:01.708,0:04:04.005
下一个我们油温稍微高一点来煎鱼

0:04:08.954,0:04:11.222
好 油冒烟了 6成热了

0:04:17.113,0:04:19.410
我们大家记住了这个时候鱼不能动

0:04:19.646,0:04:21.561
一动它的话它的皮就会烂掉

0:04:22.813,0:04:25.228
OK 现在我们给它翻过来

0:04:25.522,0:04:29.440
它的鱼皮有可能会表面的那一层皮有可能会烂掉

0:04:29.440,0:04:31.207
但是它的肉是不可能会烂的

0:04:31.310,0:04:32.636
我现在翻过来给大家看一下

0:04:36.023,0:04:36.922
大家可以看一下

0:04:37.746,0:04:39.175
煎得金黄金黄的

0:04:39.175,0:04:42.312
这一面就没有怎么烂

0:04:45.640,0:04:46.627
然后我们接着煎

0:04:50.854,0:04:53.063
OK 我们这个鱼可以看得到

0:04:54.315,0:04:56.730
煎得比较脆 表皮比较脆

0:04:56.745,0:05:02.474
然后是没有烂的 这个形状保持的比较好

0:05:02.989,0:05:04.992
我们下面一个来低油温试一下

0:05:10.603,0:05:12.709
这一次油温就稍微低一些

0:05:16.023,0:05:19.499
油温低的情况下 我们煎完了翻过来看一下

0:05:21.811,0:05:23.694
大家可以看一下 鱼肉它这里烂了

0:05:24.109,0:05:24.948
鱼肉已经烂了

0:05:30.000,0:05:31.148
再看一下另外一面

0:05:32.444,0:05:36.141
这边肉也在开始烂 而且也同样的粘勺子

0:05:37.260,0:05:40.633
现在我拿刚才高油温煎的这条鱼来对比一下

0:05:41.855,0:05:43.019
我们可以对比一下

0:05:43.151,0:05:47.702
油温低的这条已经爆开了 肉它慢慢的会爆开

0:05:47.732,0:05:50.913
然后高油温下去马上煎定型的这个金黄金黄的

0:05:50.913,0:05:53.225
这个皮也没怎么烂 肉也不会爆

0:05:53.240,0:05:54.123
大家可以看一下

0:05:54.433,0:05:56.450
鱼比较完整 这条已经烂了

0:05:57.540,0:05:58.571
已经碎了这个肉

0:05:59.779,0:06:00.707
可以看一下这边

0:06:01.060,0:06:01.973
这边也碎了

0:06:02.533,0:06:05.198
好 下一个我们来试一下低油温茄子

0:06:07.643,0:06:10.147
我们现在这个油温大概是不到100℃

0:06:10.147,0:06:11.428
现在下茄子试一下

0:06:14.550,0:06:16.377
好 其实这个已经差不多够了

0:06:16.656,0:06:17.496
四伯爷你看这个茄子

0:06:17.967,0:06:19.278
看到没这个里面好多油

0:06:20.162,0:06:20.633
是安

0:06:20.633,0:06:22.857
我现在用这个勺子能够挤出油来

0:06:24.757,0:06:28.070
所以我们茄子下锅油温低了直接就吸油

0:06:28.070,0:06:31.443
跟海绵一样把油都吸走了

0:06:32.444,0:06:33.740
现在我来试一下高油温

0:06:36.701,0:06:38.924
好 现在油温烧到了六七成了

0:06:38.954,0:06:40.235
同样下茄子

0:06:42.282,0:06:44.948
大家可以看一下 这样的茄子它是没有吸油

0:06:45.007,0:06:47.085
它的泡泡是不停的往外面冒

0:06:48.586,0:06:50.662
你看我们的油温稍微高一点下去

0:06:51.531,0:06:54.801
它这个茄子直接炸得金黄金黄的

0:06:55.198,0:06:56.406
我们现在捞出来看一下

0:06:58.762,0:06:59.823
好 我现在关火

0:07:01.428,0:07:04.418
我们看一下2个茄子同样的都是炸

0:07:04.639,0:07:06.951
这一个里面吸得油很多

0:07:07.010,0:07:09.469
这个也吸了油但是没有这个这么多

0:07:09.631,0:07:12.047
这个里面炸出来的茄子中间是很嫩的

0:07:12.253,0:07:14.064
这个吃起来的话中间是很老的

0:07:14.330,0:07:18.218
所以我们茄子下锅不拍淀粉的情况下

0:07:18.645,0:07:21.885
高油温下去一下子就把它的水份逼出来

0:07:21.988,0:07:23.475
不让它（有）吸油的机会

0:07:23.505,0:07:27.938
如果是说不喜欢吃油腻的给它拍层淀粉下去

0:07:28.409,0:07:31.413
它阻断了茄子吸油的这个面

0:07:31.575,0:07:33.799
 本期视频就简单的说到这里

0:07:33.947,0:07:35.836
然后大家如果感兴趣的话

0:07:35.836,0:07:37.507
以后我会做一期更加详细

0:07:38.713,0:07:42.654
涉及到3成4成5成6成7成8成油温

0:07:42.958,0:07:45.040
这是我们炒菜经常能够用到的油温

0:07:46.204,0:07:48.562
下次再跟你们分享更完整的视频

0:07:49.119,0:07:50.945
本期视频就到这里了 拜拜


```

**Comment by Yibing-Du** [comment]
bot, please upload
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享厨房知识：“油温”是什么，“高低油温”的特殊使用方法，干货技巧，举一反三
Chef Wang Sharing Knowledge: What's Oil Temperature and How to Use It Well
简介
Introduction
同学们好，今天咱们来聊聊“油温”，相信经常看我视频的朋友肯定是知道中式厨房中一般以“成”来界定油温，“一成”等于30摄氏度，以此类推。而相对的低油温和高油温在烹饪过程中有着不一样的作用和使用方法，今天就来列举几种特殊的使用方法来供大家参考，在以后的烹饪过程中可以举一反三，来根据食材的性状和特性来掌握相对的油温。
Hi guys, today let's talk about oil temperature. I'm sure many of you know that Chinese chefs usually use "percentage" to define oil temperature (10% = 30 celsius degrees). Since low and high temperatures have different usage in cooking, we'll list a few special ways so that you can apply these techniques in the future depending on the features of your ingredients. 

字幕
0:00:00.405,0:00:03.686
哈喽 大家好 今天我们拍一个不做菜的视频
Hi everyone! Today's video won't be about cooking
0:00:03.730,0:00:07.323
拍一个测试油温的一个视频
We're shooting a video about testing oil temperature
0:00:07.438,0:00:11.442
这个是我们准备的豆腐 有鱼有茄子
Here we've prepared tofu, fish, and eggplant
0:00:11.848,0:00:14.404
四伯爷 那你晓得啥子油温炒啥子菜不哦
Si Boye, do you know about oil temperature in cooking?
0:00:14.850,0:00:17.170
我清不到你啥子油温炒啥子菜
I'm not sure how you decide on oil temperature when you cook
0:00:17.914,0:00:22.061
我就是管你对不对 反正在锅里烧热就可以煎
I don't know much other than heating up the wok before we start pan-frying
0:00:23.177,0:00:27.049
假如这个茄子哈如果是低油温下去的话是不是要吸很多油
If we add this eggplant when the temperature is low, it'll need more oil
0:00:27.283,0:00:27.809
嗯
Yes
0:00:28.439,0:00:32.400
我伯爷都知道这个低油温下锅茄子是百分百吸油的
See, my uncle knows that adding eggplant with low temperature would need more oil
0:00:32.473,0:00:33.985
它会把这个吸得很饱满
It'll absorb a lot of oil
0:00:34.300,0:00:37.946
然后高油温下去它是在往外面排斥
If it's high temperature, the eggplant actually repels the oil
0:00:38.035,0:00:42.271
所以我们炒茄子用高油温一直炒的话它不会吸油
So if we stir-fry it with high temperature, it'll keep the oil out
0:00:42.954,0:00:45.626
然后就是我们这个鱼 还有这个鱼
Then look at this fish, and this
0:00:46.377,0:00:50.438
鱼下锅煎的话一定要高油温一下子把鱼皮给它煎熟
If you pan-fry the fish, you need high temperature to immediately get the fish skin ready
0:00:50.490,0:00:53.559
如果慢慢煎很大概率会粘锅
If you pan-fry for a long time, it's likely that it'll burn
0:00:53.559,0:00:56.022
第一个是粘锅 第二个是容易把鱼煎烂
First it'll stick on the pot, secondly the fish is likely going to fall apart
0:00:56.064,0:00:58.768
不管是煎草鱼鲤鱼还是鲫鱼
No matter which type of fish it is
0:00:59.081,0:01:00.688
都要用高油温来煎
You need high oil temperature
0:01:00.866,0:01:02.755
等会我们煎点豆腐给你看一下嘛
Now let's pan-fry some tofu and show you this
0:01:03.061,0:01:03.385
要的啊
Go ahead
0:01:03.389,0:01:04.805
给你做个示范打个样
Show you an example
0:01:05.489,0:01:08.164
好 那我们现在就到锅上面去操作这个东西
Ok, now we move to the wok for the next step
0:01:09.125,0:01:09.903
给你们看一下
To show you
0:01:11.232,0:01:17.331
好 现在我们来简单用一个低油温来炸一个花生米
Cool, now we show a simple trick of frying peanuts with low temperature
0:01:17.759,0:01:18.613
先倒油
First pour theo il
0:01:21.104,0:01:22.708
这个是我们准备的花生米
These are the peanuts we prepared
0:01:23.019,0:01:24.344
直接下锅
Add it to the wok immediately
0:01:24.639,0:01:27.511
四伯爷 你晓得花生米为什么要冷油下锅去炸不
Si Boye, do you know why we add it before the oil heats up?
0:01:28.527,0:01:32.299
拿下去炸它才炸得泡撒
If you fry it now, it'll become puffy
0:01:33.357,0:01:34.315
如果是高油温安
If it's high temperature
0:01:34.683,0:01:35.758
高油温不得行
That won't work
0:01:36.097,0:01:36.671
不得行嘎
Won't work
0:01:36.951,0:01:37.923
高油温要炸糊
It'll burn
0:01:38.409,0:01:39.985
嗯 然后中间还是生的
Yes, and the middle part would still be raw
0:01:40.147,0:01:41.089
嗯 对对对
Yep yep
0:01:42.091,0:01:47.216
我们炸这个花生米就是冷油下去随着油温的加热
When we fry the peanuts, we add it when the oil is cold and as it heats up, 
0:01:47.378,0:01:49.042
花生米中间也开始热
the peanuts heat up from the middle too
0:01:49.234,0:01:52.709
如果这个花生米你在锅里拿出来吃已经可以了
If you taste it and it's almost done
0:01:53.019,0:01:54.801
拿出来放一会儿它自己会熟
You can take it all and let it rest
0:01:56.921,0:02:03.652
所以我们像类似炸这个核桃啊花生米啊腰果呀这些
So frying walnuts, peanuts, and cashew nuts are all the same
0:02:03.799,0:02:05.463
必须用低油温下锅
You need to add it at low temperature
0:02:07.511,0:02:10.409
好 现在这个油温大概已经升到了5成
Ok now the oil has increased to 50%
0:02:11.178,0:02:14.182
我们转中小火保持这个油温
We turn to medium low heat to keep it that way
0:02:15.243,0:02:18.291
然后炸这个花生米就是我们很典型的
See frying the peanuts is very representative
0:02:18.674,0:02:21.060
3成油温左右就下花生米
You add it at 30% temperature
0:02:21.148,0:02:23.711
或者是冷油直接下都可以
Or even when it's cold
0:02:24.595,0:02:26.494
千万不要把油温烧得太热了
Don't over heat it
0:02:27.231,0:02:29.558
油温的话每一成30度
The temperature transltates to 30 degrees for every 10%
0:02:30.162,0:02:37.670
那我们经常能够用得到就是4成5成6成7成就可以了
So what we usually use is 40% to 70%
0:02:37.670,0:02:38.869
34567
3, 4, 5, 6, 7
0:02:39.720,0:02:40.677
好像可以了
It's ready
0:02:47.025,0:02:50.176
那我们现在来煎一个豆腐
Then now we pan-fry some tofu
0:02:53.873,0:02:55.346
现在是属于一个高油温
Now we have high heat
0:02:55.405,0:02:57.142
大概是6成油温下的豆腐
We add the tofu at around 60%
0:02:59.852,0:03:04.683
我们油温高一点的话这个豆腐不会煎烂
If the temperature is high, tofu won't fall apart
0:03:05.994,0:03:08.556
你看 这样子翻都没事
See, you can even flip it like this
0:03:10.368,0:03:11.266
看到没有四伯爷
See that, Si Boye? 
0:03:12.106,0:03:16.892
油温高它下去表面马上就有一层金黄金黄的
When the temperature is high, you immediately see it turns golden
0:03:18.026,0:03:20.765
好 我们把这块拿出来
Ok, now we take it out
0:03:20.868,0:03:22.916
然后下一个试一下低油温
Then add another to try low temperature
0:03:31.443,0:03:33.387
我们这个是低油温下去煎
Now we pan-fry at low temperature
0:03:33.947,0:03:35.405
这个豆腐现在是低油温
Now the tofu is at low temperature
0:03:35.625,0:03:38.335
如果说油温比较低的情况下我们去翻它
If we flip it now
0:03:38.910,0:03:40.058
看到没就烂了
See, it breaks apart
0:03:41.649,0:03:42.562
这个时候就烂了
It breaks just now
0:03:43.151,0:03:46.229
所以这里我们做一个实验就可以看得出来这个豆腐
So we've done this experiment and we can see that the tofu
0:03:46.966,0:03:50.721
低油温煎 像这样子没有煎出锅巴出来
When fried at low temperature, wouldn't form the golden layer 
0:03:50.736,0:03:53.637
没有煎出黄黄的东西出来豆腐非常容易碎
Without the golden layer, it tends to fall apart
0:03:56.524,0:03:57.658
而且还粘勺子
And stick on our utensil
0:03:59.823,0:04:01.237
好 我们把它拿出来
Ok, let's take it out
0:04:01.708,0:04:04.005
下一个我们油温稍微高一点来煎鱼
Next we'll pan-fry the fish at slightly higher temperature
0:04:08.954,0:04:11.222
好 油冒烟了 6成热了
Ok some smoke is coming out, we're at 60%
0:04:17.113,0:04:19.410
我们大家记住了这个时候鱼不能动
Remember you can't touch the fish now
0:04:19.646,0:04:21.561
一动它的话它的皮就会烂掉
If you touch it, the skin will break apart
0:04:22.813,0:04:25.228
OK 现在我们给它翻过来
Ok, now we flip it
0:04:25.522,0:04:29.440
它的鱼皮有可能会表面的那一层皮有可能会烂掉
The fish skin (the first layer) might fall apart
0:04:29.440,0:04:31.207
但是它的肉是不可能会烂的
But the meat won't
0:04:31.310,0:04:32.636
我现在翻过来给大家看一下
Now we flip it to take a look
0:04:36.023,0:04:36.922
大家可以看一下
You can see
0:04:37.746,0:04:39.175
煎得金黄金黄的
It's golden
0:04:39.175,0:04:42.312
这一面就没有怎么烂
This side didn't break
0:04:45.640,0:04:46.627
然后我们接着煎
We continue to pan-fry
0:04:50.854,0:04:53.063
OK 我们这个鱼可以看得到
Ok, we can see
0:04:54.315,0:04:56.730
煎得比较脆 表皮比较脆
the fish is quite crispy, the surface
0:04:56.745,0:05:02.474
然后是没有烂的 这个形状保持的比较好
And it hasn't fall apart, it's in good shape
0:05:02.989,0:05:04.992
我们下面一个来低油温试一下
Now we try it with low temperature
0:05:10.603,0:05:12.709
这一次油温就稍微低一些
Now the temperature is slightly lower
0:05:16.023,0:05:19.499
油温低的情况下 我们煎完了翻过来看一下
With low temperature, we flip it after a while
0:05:21.811,0:05:23.694
大家可以看一下 鱼肉它这里烂了
You can see how the meat is falling apart
0:05:24.109,0:05:24.948
鱼肉已经烂了
It's fallen apart
0:05:30.000,0:05:31.148
再看一下另外一面
Now look at the other side
0:05:32.444,0:05:36.141
这边肉也在开始烂 而且也同样的粘勺子
This side too, and it's also sticky
0:05:37.260,0:05:40.633
现在我拿刚才高油温煎的这条鱼来对比一下
Now compare it with the fish that's pan-fried with high temperature
0:05:41.855,0:05:43.019
我们可以对比一下
Let's compare
0:05:43.151,0:05:47.702
油温低的这条已经爆开了 肉它慢慢的会爆开
This one under low temperature has fallen apart gradually
0:05:47.732,0:05:50.913
然后高油温下去马上煎定型的这个金黄金黄的
The other one that immediately formed shape in high temperature is golden
0:05:50.913,0:05:53.225
这个皮也没怎么烂 肉也不会爆
And its skin and meat aren't apart
0:05:53.240,0:05:54.123
大家可以看一下
You can take a look
0:05:54.433,0:05:56.450
鱼比较完整 这条已经烂了
This fish looks good, the other not great
0:05:57.540,0:05:58.571
已经碎了这个肉
Its meat has come apart
0:05:59.779,0:06:00.707
可以看一下这边
Look at this side
0:06:01.060,0:06:01.973
这边也碎了
It's not held together
0:06:02.533,0:06:05.198
好 下一个我们来试一下低油温茄子
Ok next we'll try eggplants in low temperature
0:06:07.643,0:06:10.147
我们现在这个油温大概是不到100℃
Now the temperature is probably below 100 degrees
0:06:10.147,0:06:11.428
现在下茄子试一下
Now add the eggplant and try
0:06:14.550,0:06:16.377
好 其实这个已经差不多够了
Ok, actually this is enough
0:06:16.656,0:06:17.496
四伯爷你看这个茄子
Si Boye, look at the eggplant
0:06:17.967,0:06:19.278
看到没这个里面好多油
See, a lot of oil
0:06:20.162,0:06:20.633
是安
Yeah
0:06:20.633,0:06:22.857
我现在用这个勺子能够挤出油来
We can see the oil come out if we press it
0:06:24.757,0:06:28.070
所以我们茄子下锅油温低了直接就吸油
So if we add the eggplant at low temperature, it immediately absorbs the oil
0:06:28.070,0:06:31.443
跟海绵一样把油都吸走了
Like a sponge
0:06:32.444,0:06:33.740
现在我来试一下高油温
Now let's test with high temperature
0:06:36.701,0:06:38.924
好 现在油温烧到了六七成了
Ok, now it's reaching 60% or 70%
0:06:38.954,0:06:40.235
同样下茄子
We also add eggplants
0:06:42.282,0:06:44.948
大家可以看一下 这样的茄子它是没有吸油
As you can see, the eggplant doesn't absorb the oil
0:06:45.007,0:06:47.085
它的泡泡是不停的往外面冒
You see the bubbles coming out
0:06:48.586,0:06:50.662
你看我们的油温稍微高一点下去
See if we add it when the temperature is a bit higher
0:06:51.531,0:06:54.801
它这个茄子直接炸得金黄金黄的
It immediately turns golden
0:06:55.198,0:06:56.406
我们现在捞出来看一下
Let's take it out to take a look
0:06:58.762,0:06:59.823
好 我现在关火
Ok, I'm turning off the stove
0:07:01.428,0:07:04.418
我们看一下2个茄子同样的都是炸
Let's look at the two eggplants, both fried
0:07:04.639,0:07:06.951
这一个里面吸得油很多
This has lots of oil
0:07:07.010,0:07:09.469
这个也吸了油但是没有这个这么多
The other too, but not as much
0:07:09.631,0:07:12.047
这个里面炸出来的茄子中间是很嫩的
This one is soft in the middle
0:07:12.253,0:07:14.064
这个吃起来的话中间是很老的
The other one is not
0:07:14.330,0:07:18.218
所以我们茄子下锅不拍淀粉的情况下
So if we don't cover it with corn starch
0:07:18.645,0:07:21.885
高油温下去一下子就把它的水份逼出来
High temperature will let the water out immediately
0:07:21.988,0:07:23.475
不让它（有）吸油的机会
So that it doesn't absorb the oil
0:07:23.505,0:07:27.938
如果是说不喜欢吃油腻的给它拍层淀粉下去
If you don't like the greasy taste, add some starch
0:07:28.409,0:07:31.413
它阻断了茄子吸油的这个面
It prevents the eggplant from absorbing from the surroundings
0:07:31.575,0:07:33.799
 本期视频就简单的说到这里
This is the end of today's video
0:07:33.947,0:07:35.836
然后大家如果感兴趣的话
If you're interested
0:07:35.836,0:07:37.507
以后我会做一期更加详细
I'll make another one to explain in more details
0:07:38.713,0:07:42.654
涉及到3成4成5成6成7成8成油温
About temperatures ranging from 30% to 80%
0:07:42.958,0:07:45.040
这是我们炒菜经常能够用到的油温
Which are the ones we usually use when cooking
0:07:46.204,0:07:48.562
下次再跟你们分享更完整的视频
I'll see you again in our next video
0:07:49.119,0:07:50.945
本期视频就到这里了 拜拜
See you!

**Comment by immoonancient** [comment]
YouTube 上被别人做了，质量也还不错，就不要覆盖了
本字幕作废
