### ISSUE TITLE
[华农兄弟] 兄弟家的水果 - https://youtu.be/2C8RuvPuw6s

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1116]
https://youtu.be/2C8RuvPuw6s
<p>&#35270;&#39057;&#21457;&#24067;&#20110; June 2, 2020 at 11:45AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/2C8RuvPuw6s

#华农兄弟：兄弟家的水果熟了，看着就很好吃，摘一点回去
#Huanong Brothers: My buddy's fruits are ripe now. They look really tasty. Let's pick some.

0:00:00.300,0:00:03.240
# 大家好  今天來看一下家的三華李  熟了沒有
Hi everyone! Today we're gonna take a look at our buddy's Sanhua plums, and see if they are ripe.

0:00:06.500,0:00:07.380
# 熟了沒有
Are they ripe?

0:00:08.700,0:00:09.540
# 這個
This is,

0:00:10.140,0:00:10.820
# 這個楊梅
this bayberry,

0:00:11.660,0:00:12.820
# 這是半熟的
it is half-ripe.

0:00:13.460,0:00:14.340
# 這個是贈品來的
And it's a giveaway.

0:00:15.800,0:00:16.420
# 怎麼吃都行
I can feel free to enjoy it.

0:00:17.680,0:00:18.320
# 嗯~
Um~

0:00:22.260,0:00:23.140
# 你看這個楊梅
Have a look at the bayberries!

0:00:24.700,0:00:25.360
# 這個是
This is,

0:00:26.640,0:00:27.960
# 這個是比較大的楊梅啦
this is a relatively bigger bayberry.

0:00:28.560,0:00:29.140
# 還沒熟 null
It's still green.

0:00:30.120,0:00:31.520
# 還  差一點點就熟啦
It's almost ripe. It needs, only a tiny little bit of time.

0:00:33.120,0:00:33.620
# 你看
Look!

0:00:33.860,0:00:34.360
# 這個
These are,

0:00:35.100,0:00:35.720
# 這個熟啦
these are ripe now.

0:00:36.660,0:00:37.820
# 這樣子是  全紅的
This one is, completely red.

0:00:40.080,0:00:41.760
# 還可以哦  味道  很有楊梅味
It's not bad, the taste, a rich flavour of bayberries.

0:00:43.400,0:00:44.760
# 在樹在摘的比較新鮮
They're rather fresh as they're picked directly from the tree.

0:00:49.040,0:00:51.520
# 上樹上再摘幾個  樹頂上的比較好
Let me climb to the top of the tree and pick some there. The better ones are at the top of the tree.

0:00:54.480,0:00:58.280
# 哎呀  在這裡有一個那麼大  那麼大條的人在這裡  (註︰「一條人」是量詞的固意誤用以將人動物化，英語沒有量詞，所以改為把「人」物種化，藉以弱化「人」的概念)
Aya! Here is such a big, such a big human is here.

0:00:58.280,0:00:58.880
# 等會等會
A moment, a moment!

0:00:59.840,0:01:01.760
# 等一下你要  等你要把我搞下去
You need to, you need to take me down in a while.

0:01:03.660,0:01:04.420
# 你看這個兩個
Look at these two!

0:01:05.560,0:01:06.180
# 哎呀
Aya!

0:01:11.120,0:01:11.620
# 可以喲
Not bad!

0:01:13.740,0:01:17.100
# 這個楊梅  長大了  它就不酸啦  沒那麼酸
The bayberries are not sour, not that sour, when they grow up.

0:01:21.160,0:01:22.220
# 那裡有好大的
There's a very big one!

0:01:24.680,0:01:25.440
# 哎呀  這個
Aya! This is,

0:01:27.000,0:01:28.240
# 這個太大啦
this is simply too big!

0:01:29.300,0:01:29.940
# 你看
Look!

0:01:30.900,0:01:31.400
# 這個
This is,

0:01:32.340,0:01:33.200
# 又大又紅
big and red.

0:01:34.280,0:01:35.060
# 肯定很好吃
It must taste very good!

0:01:37.240,0:01:37.920
# 嗯~
Um~

0:01:40.160,0:01:41.800
# 等下我拿個桶來 裝點回去吃
I'm gonna get a bucket, and bring some back home.

0:01:42.120,0:01:43.060
# 拿來曬那個
I can dry them under the sun, and you know,

0:01:43.480,0:01:44.360
# 曬那個楊梅乾
and make some dried bayberries.

0:01:45.360,0:01:47.300
# 我來摘點那個李子    那個李子熟啦
Let's pick some plums. The plums are ripe now.

0:01:48.320,0:01:48.920
# 三華李
Sanhua plums

0:01:50.680,0:01:53.000
# 哇  這裡  好多啊  這裡
Wa! Here, so many here!

0:01:53.460,0:01:54.520
# 又大又紅
Big and red!

0:01:56.740,0:01:57.300
# 哇
Wa!

0:01:58.520,0:01:59.020
# 你看
Look!

0:02:00.300,0:02:00.800
# 這個
This is,

0:02:02.280,0:02:02.840
# 夠大吧
big, isn't it?

0:02:05.540,0:02:06.240
# 搓兩下
Rub it

0:02:06.640,0:02:07.480
# 先吃再說
Let me finish it first.

0:02:13.520,0:02:14.380
# 全是紅的
It's all red.

0:02:17.540,0:02:18.340
# 你看這裡
Have a look here!

0:02:19.320,0:02:19.840
# 這個
This is,

0:02:20.320,0:02:21.300
# 多紅啊  這個
really red, this one.

0:02:22.860,0:02:24.020
# 摘的話要摘大的
Pick only the big ones.

0:02:25.440,0:02:26.860
# 專門桃  大的摘
Look for the big ones, and pick only the big ones.

0:02:30.920,0:02:32.340
# 很靚的  這個三華李
They're so beautiful, these Sanhua plums.

0:02:36.280,0:02:37.320
# 差點就掉
They almost fell.

0:02:37.840,0:02:39.520
# 差點就掉到溝裡面去了
They almost fell into the pit.

0:02:40.240,0:02:41.060
# 把它摘掉
Let me pick them.

0:02:41.720,0:02:44.040
# 要不然一下兩的話掉到溝裡面去就麻煩啦
Otherwise it would be too bad if they all fall into the pit when the rain comes.

0:02:44.680,0:02:47.360
# 你看這些  這都是超級大  這些
Have a look at these! They're super big, all these.

0:02:48.580,0:02:49.300
# 夠大
It's so big.

0:02:51.160,0:02:51.840
# 把這個
Let me,

0:02:52.020,0:02:52.880
# 大的摘掉
pick the big ones.

0:02:55.640,0:02:56.220
# 你看這種
Have a look at this one.

0:02:56.760,0:02:57.740
# 這種就很好吃的
This type is really tastey.

0:03:02.700,0:03:03.340
# 你看這個
Have a look at this one!

0:03:04.220,0:03:04.720
# 擦一下
Rub it

0:03:04.860,0:03:05.520
# 反光
Shiny!

0:03:10.500,0:03:11.100
# 這個
These plums,

0:03:12.740,0:03:14.840
# 不要太熟  太熟了就只有甜味啦
shouldn't be too ripe. There's only sweetness if they're too ripe.

0:03:15.480,0:03:17.100
# 就像這樣酸酸甜甜的
Now it's like sweet and sour.

0:03:18.840,0:03:19.760
# 而且很脆
And it's really crunchy.

0:03:24.500,0:03:25.100
# 你看
Look!

0:03:27.200,0:03:28.500
# 三十稍就摘了那麼多
I've picked so many in just thirty seconds.

0:03:29.400,0:03:30.260
# 一樹都是
They're all over the trees.

0:03:34.520,0:03:36.660
# 你看這一個 那麼大這個
Have a look at this one! This one is so big!

0:03:37.600,0:03:38.540
# 好大的  這個
It's really big, this one.

0:03:39.000,0:03:40.460
# 搞得我直接說客家了
So big that it makes me speak in Hakka dialect right away.

0:03:45.280,0:03:46.680
# 看下好不好吃  嘗一下
Let me see if it's tasty. I have a try.

0:03:50.020,0:03:50.520
# 嗯
Um~

0:03:51.520,0:03:52.300
# 最少一兩
It weighs at least half a kilogram.

0:03:58.720,0:03:59.520
# 血紅色的
It's bloody red.

0:04:13.720,0:04:16.860
# 你看這個桃子  那麼小的樹都長那麼多個出來
Have a look at the peaches. It's such a small tree but there are so many peaches.

0:04:17.860,0:04:20.420
# 肯定在想  不長那麼多個出來的話
It must be thinking, that its owner would chop it down,

0:04:20.740,0:04:22.360
# 它的主人肯定把它砍掉
if it has any less peaches.

0:04:23.620,0:04:24.280
# 所以你看
So, you see!

0:04:24.680,0:04:26.220
# 長了幾個又大又紅的
It has some big and red ones.

0:04:27.540,0:04:28.560
# 你別看它那麼小
Don't judge it by its small size.

0:04:29.380,0:04:30.460
# 但是很甜的哦
It's really sweet, you know.

0:04:31.900,0:04:33.140
# 果  那個肉甜
The fruit, I mean the pulp is sweet.

0:04:34.660,0:04:35.480
# 這毛太多啦
It's too furry.

0:04:38.480,0:04:39.380
# 好多啊  你看
A lot! Look!

0:04:40.080,0:04:41.600
# 那麼小的樹長幾十個出來  
There are dozens of them in such a small tree.

0:04:43.800,0:04:45.600
# 那個裡面還有  我們看一下
There are more inside. Let's take a look!

0:04:47.440,0:04:48.860
# 你看  這裡還有一個小西瓜
Look! Here's also a tiny watermelon.

0:04:49.180,0:04:49.840
# 還沒熟哦
It's not yet ripe.

0:04:50.720,0:04:51.460
# 那麼一點點
It's just a tiny little one.

0:04:54.620,0:04:56.660
# 就一個啊  那麼多棵西瓜樹  
Just one? Here are so many watermelon trees.

0:05:00.440,0:05:01.280
# 就長了一個
That's the only one.

0:05:07.100,0:05:08.020
# 你看  這裡有一個
Look! Here's one!

0:05:09.080,0:05:10.140
# 那麼大顆  這個
It's so big, this one.

0:05:11.800,0:05:12.700
# 好紅啊  這個
It's so red, this one.

0:05:22.200,0:05:23.300
# 它的果肉好好吃啊
Its pulp is really tasty.

0:05:23.500,0:05:24.420
# 把它的皮削掉
Peal it,

0:05:24.620,0:05:25.160
# 很好吃的
and it's really tasty.

0:05:27.240,0:05:27.980
# 忘記帶刀了
I've left my knife behind.

0:05:32.600,0:05:33.200
# 你看
Look!

0:05:33.980,0:05:34.520
# 肉都可以
The pulp can be,

0:05:35.260,0:05:36.100
# 肉都快紅啦
the pulp is turning red.

0:05:37.560,0:05:38.360
# 快熟了是吧
It's almost ripe, isn't it?

0:05:38.560,0:05:39.060
# 嗯
Um!

0:05:40.560,0:05:42.000
# 剛剛好  剛剛好
Just right, just right.

0:05:43.400,0:05:45.780
# 你看這種桃子  好紅啊
Look! These peaches, they're so red.

0:05:47.000,0:05:47.740
# 白裡透紅
Rosy white,

0:05:48.640,0:05:49.140
# 粉紅
or pink.

0:05:53.040,0:05:54.460
# 又掉了一個小的  這個
Another one drops down, this one.

0:05:55.180,0:05:55.720
# 有點
It's a bit,

0:05:56.080,0:05:56.580
# 本來
originally,

0:05:56.960,0:05:57.620
# 應該是
it should be,

0:05:58.760,0:06:01.240
# 跟鷹嘴桃有點像  但是又不是鷹嘴桃
it should look a bit like an acorn peach, but it's not really an acorn peach.

0:06:05.020,0:06:05.940
# 剝都剝不開
I can't crack it open.

0:06:08.620,0:06:09.500
# 你看  這個肉
Look! The pulp,

0:06:11.360,0:06:12.260
# 這個肉很好吃的
the pulp is really tasty.

0:06:21.240,0:06:22.540
# 沒辦法  只能這樣咬了
I can only just bite, no other choices.

0:06:33.580,0:06:34.500
# 你看  這個李子
Look! These plums,

0:06:35.220,0:06:36.180
# 還不是很紅
are still not really that red.

0:06:37.140,0:06:39.740
# 但是這個可以吃的  你看這個  這個就很靚的  這個
But this one is already edible. Have a look at this one! This one is really beautiful, this one.

0:06:43.520,0:06:46.360
# 摘這個的時候有一點紅就可以啦  不用太紅
They can be picked when they're only a bit red. They don't need to be too red.

0:06:47.160,0:06:49.660
# 這個拿回去  一兩天就把它廿 這個很好吃的
Take them back, I can finish them in a day or two. They're really tasty.

0:06:53.640,0:06:54.280
# 那麼大
It's so big!

0:06:54.860,0:06:55.360
# 你看
Look!

0:06:56.300,0:06:56.880
# 很靚哦
Beautiful, aren't they?

0:07:03.860,0:07:05.900
# 剛好兄弟 兄弟他們也過來啦
Just now our buddies, our buddies are here.

0:07:06.240,0:07:09.300
# 讓他們幫忙裝  等一下一人  一人拿兩箱
I let them help with the packing. Each, each of them is gonna carry two.

0:07:09.900,0:07:12.720
# 多的  多的拿回去 送兄弟姐妹
The extra, the extra, will be given to our brothers and sisters,

0:07:12.980,0:07:13.620
# 叔叔阿姨
uncles and aunties,

0:07:14.780,0:07:15.440
# 大哥大妹
sirs and madams.

0:07:15.920,0:07:17.840
# 應該可能再一箱  剛剛好  (註︰這句沒看懂，照字面翻譯吧)
I think each of them can have one more box, perfect!
