### ISSUE TITLE
【美食作家王刚】猛火灶的流动水 - https://youtu.be/uTSsXQ-9bnQ

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1120]
**视频链接**：https://youtu.be/uTSsXQ-9bnQ

视频时长7:52，预计发布时间为北京时间6月6日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长解答：“猛火灶的流动水不关”，不仅仅是“浪费水”这么简单，后厨解密

简介
大家好，因为经常看到有朋友留言说为什么“不关水龙头，感觉很浪费”，其实真的冤枉😂，虽说之前解释过多次，这次还是单独出一期视频来用实验的形式来给大家解答一下为什么专业猛火灶一定要有流水。流动水是极佳的降温材料，就像是最简单的一套水冷系统，可以让猛火灶满功率工作几个小时还不至于温度过高，来提高使用寿命。

字幕
0:00:00.250,0:00:01.800
哈喽大家好我是王刚

0:00:02.000,0:00:03.982
就是我们的视频我看了一下

0:00:04.050,0:00:09.375
最近100个视频都有粉丝的弹幕在说这个水呀

0:00:09.550,0:00:11.675
我们这个水为什么要让它流起来

0:00:12.325,0:00:15.325
为什么在炒菜的时候不把它关掉呢

0:00:15.350,0:00:17.375
其实今天我就跟大家解释一下

0:00:17.675,0:00:19.075
其实这个炉灶的话

0:00:19.550,0:00:21.700
这里面的水必须要保证它是冷水

0:00:21.800,0:00:25.350
因为我们在炒菜的时候有的时候要加冷水下锅

0:00:25.750,0:00:26.925
所以就不能是热水

0:00:27.000,0:00:28.500
如果一旦把这个关掉

0:00:29.075,0:00:32.725
然后它下面的这个炉膛这里有一个洞过来

0:00:32.725,0:00:34.500
这个热气从这里出去

0:00:34.550,0:00:36.825
然后这个地方里面的水就会

0:00:37.375,0:00:40.100
如果长时间没有新的冷水进来

0:00:40.100,0:00:41.675
这里面的水就会烧开

0:00:42.000,0:00:44.225
我们如果想这样子洗一下手

0:00:44.975,0:00:47.450
就肯定是不行的开水肯定是不行嘛

0:00:47.950,0:00:51.175
然后的话就是如果我们把它关掉

0:00:51.325,0:00:53.150
里面的水用完了之后

0:00:54.350,0:00:57.900
用完了之后这个盆就是这样子 可以活动地拿出来的

0:00:58.100,0:01:00.275
这个盆的话会直接烧黑

0:01:00.550,0:01:04.375
然后这边上这些高温泥它会掉

0:01:04.675,0:01:05.450
会被烧掉

0:01:05.875,0:01:11.500
最后就会烧到里面的一些线路老化

0:01:11.700,0:01:13.250
这样子就会非常的危险

0:01:14.175,0:01:17.675
本期视频呢我就准备了一个这个

0:01:18.100,0:01:23.000
我就直接不开水流着就这样烧

0:01:23.075,0:01:25.475
烧出来给你们看一下是什么效果

0:01:25.575,0:01:27.700
第一个烧就是这里不开水

0:01:27.775,0:01:28.975
这里面是有水的

0:01:29.675,0:01:31.975
从冷水变成开水要多久

0:01:32.225,0:01:38.025
然后呢我就再用这个里面不放水干烧会变成什么样子

0:01:38.525,0:01:40.950
首先我们把锅里面的水加满

0:01:41.250,0:01:43.425
因为这个锅不可以干烧

0:01:46.875,0:01:48.975
然后我们把里面的水放满

0:01:52.700,0:01:55.050
好啦现在我们就把这个水给关掉了

0:01:55.525,0:01:56.775
关掉就这样烧

0:01:58.300,0:02:00.140
我们可以摸一下用手摸一下这里

0:02:00.140,0:02:01.775
现在已经很烫了

0:02:02.725,0:02:07.300
就干烧这么大概10几秒钟下面就已经开始很烫了

0:02:17.725,0:02:20.800
现在的水温在逐步增加

0:02:21.750,0:02:25.675
 但是我们这边锅里面的水已经快开了

0:02:32.450,0:02:34.500
好 里面的水开始慢慢热了

0:02:44.200,0:02:47.400
我们现在这个盆里面的（井）水大概有10℃左右了

0:02:49.650,0:02:52.075
像我们经常炒菜的话

0:02:52.750,0:02:56.350
1个灶炒个1个小时2个小时是很正常的

0:03:01.475,0:03:04.450
现在这个盆里面的水大概是30℃的样子

0:03:11.796,0:03:13.300
差不多有40℃了

0:03:14.425,0:03:16.850
说真的我还从来没有这样子烧过开水

0:03:17.595,0:03:18.481
因为也不敢

0:03:18.675,0:03:21.125
师傅看到会骂的

0:03:21.950,0:03:24.625
然后老板看到的话也会扣工资

0:03:25.600,0:03:27.175
这应该是我第一次这么干

0:03:29.800,0:03:31.750
现在有一点点烫手了

0:03:41.925,0:03:44.700
我们这个水可能有70℃-80℃了

0:03:51.925,0:03:54.951
这个水在慢慢的开始变浑

0:03:54.951,0:03:56.975
而且有点要开的感觉了

0:04:04.775,0:04:07.725
好啦现在经过我们差不多半个小时的烧

0:04:08.350,0:04:10.550
这个没有放水进去现在已经变成了

0:04:11.350,0:04:13.425
几乎变成了开水

0:04:15.150,0:04:16.900
用来炒菜的话是用不了的

0:04:16.975,0:04:18.200
有的菜我们要用冷水

0:04:18.800,0:04:22.325
好 现在我们来把这个水给它倒出来

0:04:33.875,0:04:37.250
大家可以看一下干烧的时候我们这个水分已经烧干了

0:04:37.750,0:04:39.400
我估计这样子来得非常快

0:04:39.400,0:04:44.325
不要5分钟这个（装水的）锅就会被烧黑

0:04:49.875,0:04:52.500
好 我们这个不锈钢已经变形了现在

0:04:56.550,0:04:58.250
来 我关火给大家看一下

0:04:59.250,0:05:02.900
如果我现在放冷水进去肯定会冒出很多白烟出来

0:05:05.075,0:05:06.350
听到没这个声音

0:05:18.775,0:05:19.725
这个水已经烫了

0:05:20.175,0:05:23.475
也就是说我们这个里面不放水干烧的话

0:05:23.475,0:05:26.550
这个会烧黑 已经烧黑了

0:05:26.750,0:05:30.750
这个是我们刚才故意干烧的一个结果

0:05:30.775,0:05:32.050
我们看一下这个

0:05:32.375,0:05:34.875
我们这个是经常放水烧的

0:05:35.800,0:05:36.550
对比一下

0:05:37.050,0:05:41.700
这个的话如果不放水就会烧干烧焦

0:05:42.000,0:05:48.425
正规厨房来说的话这个地方它是一个流动水

0:05:48.550,0:05:49.700
然后在这个地方

0:05:50.075,0:05:52.250
这里我们不动它

0:05:52.275,0:05:53.100
就感觉这里

0:05:54.700,0:05:55.975
这里还会放一个盆

0:05:56.825,0:05:59.550
我们这里面的水是用来洗锅用的

0:05:59.550,0:06:01.525
这里面的水是用来炒菜用的

0:06:01.975,0:06:06.350
所以我们这个会一直把它开起来

0:06:06.450,0:06:08.000
作为一个流动水

0:06:11.975,0:06:14.100
好啦今天的实验就到这里

0:06:14.400,0:06:16.300
今天浪费了一大半瓶煤气

0:06:17.000,0:06:20.000
通过这个实验我们得出来了一个结论

0:06:20.075,0:06:25.150
就是这个必须开水一直给它流动起来

0:06:25.500,0:06:27.900
不然这里面的水会变得非常烫

0:06:28.450,0:06:30.525
就是说我们炒菜嘛用不上

0:06:31.600,0:06:34.700
然后我们这个盆里面必须要有足够的水

0:06:34.800,0:06:37.125
如果没有水的话会把这个烧坏

0:06:37.425,0:06:41.000
把这一片温度过高烧坏了之后

0:06:41.975,0:06:43.700
里面的高温泥会掉

0:06:43.875,0:06:46.250
掉了之后的话这个边也会掉

0:06:46.450,0:06:47.950
慢慢的这个灶就会塌

0:06:48.225,0:06:50.825
所以的话我们必须放水

0:06:51.650,0:06:54.050
以后大家就不要再说浪费这个事情了

0:06:54.250,0:06:55.625
好啦 本期视频到这里

0:06:55.875,0:06:56.400
拜拜


```

**Comment by Petitcolza** [comment]
认领

**Comment by Petitcolza** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长解答：“猛火灶的流动水不关”，不仅仅是“浪费水”这么简单，后厨解密
Chef explain: fluid water on high fire stove, it’s not waste, demystify restaurant kitchen.
简介
intro
大家好，因为经常看到有朋友留言说为什么“不关水龙头，感觉很浪费”，其实真的冤枉😂，虽说之前解释过多次，这次还是单独出一期视频来用实验的形式来给大家解答一下为什么专业猛火灶一定要有流水。流动水是极佳的降温材料，就像是最简单的一套水冷系统，可以让猛火灶满功率工作几个小时还不至于温度过高，来提高使用寿命。
Hello. I always notice that our friends leave messages ask about why not close water faucet and it’s wasted water. Actually I feel so being wronged. Although I explained it many times before. I’d like to release a individual video that explain by doing an experiment the question why I use fluid water on high fire stove. Fluid water is very good for reducing temperature. Like a simple water-cooling system, it could make a high fire stove used of full power for several hours isn’t in high temperature, increasing its service life.
字幕
0:00:00.250,0:00:01.800
哈喽大家好我是王刚
Hello, everyone. I’m Wang Gang.
0:00:02.000,0:00:03.982
就是我们的视频我看了一下
I had a look at our videos.
0:00:04.050,0:00:09.375
最近100个视频都有粉丝的弹幕在说这个水呀
There were some fans talk about the water in recently 100 videos 
0:00:09.550,0:00:11.675
我们这个水为什么要让它流起来
Why we let the water flow?
0:00:12.325,0:00:15.325
为什么在炒菜的时候不把它关掉呢
Why not turn it off while cooking?
0:00:15.350,0:00:17.375
其实今天我就跟大家解释一下
Today, I’m going to explain it.
0:00:17.675,0:00:19.075
其实这个炉灶的话
Actually, This stove.
0:00:19.550,0:00:21.700
这里面的水必须要保证它是冷水
It must have cold water in it.
0:00:21.800,0:00:25.350
因为我们在炒菜的时候有的时候要加冷水下锅
Because we have to put cold water in the wok during cooking.
0:00:25.750,0:00:26.925
所以就不能是热水
Can’t be warm.
0:00:27.000,0:00:28.500
如果一旦把这个关掉
If we turn it off.
0:00:29.075,0:00:32.725
然后它下面的这个炉膛这里有一个洞过来
There is a hole in the stove.
0:00:32.725,0:00:34.500
这个热气从这里出去
The heat through it go out.
0:00:34.550,0:00:36.825
然后这个地方里面的水就会
Then the water in here will…
0:00:37.375,0:00:40.100
如果长时间没有新的冷水进来
If there is no coming cold water add in for a long time.
0:00:40.100,0:00:41.675
这里面的水就会烧开
The water in here will be boil.
0:00:42.000,0:00:44.225
我们如果想这样子洗一下手
If we would like wash hands like this.
0:00:44.975,0:00:47.450
就肯定是不行的开水肯定是不行嘛
It can’t work. It’s boiling water.
0:00:47.950,0:00:51.175
然后的话就是如果我们把它关掉
If we turn it off.
0:00:51.325,0:00:53.150
里面的水用完了之后
The water inside is run out.
0:00:54.350,0:00:57.900
用完了之后这个盆就是这样子 可以活动地拿出来的
It looks like this when it’s empty, it could be taken out.
0:00:58.100,0:01:00.275
这个盆的话会直接烧黑
The basin could be scorched.
0:01:00.550,0:01:04.375
然后这边上这些高温泥它会掉
The high temperature resistance material could be burn out.
0:01:04.675,0:01:05.450
会被烧掉
Could be burn out
0:01:05.875,0:01:11.500
最后就会烧到里面的一些线路老化
Finally, it could make aging electrical.
0:01:11.700,0:01:13.250
这样子就会非常的危险
That would be very dangerous.
0:01:14.175,0:01:17.675
本期视频呢我就准备了一个这个
In this vide, I prepared an (experiment)
0:01:18.100,0:01:23.000
我就直接不开水流着就这样烧
I don’t turn on the faucet, and heat it.
0:01:23.075,0:01:25.475
烧出来给你们看一下是什么效果
You see what is the effect.
0:01:25.575,0:01:27.700
第一个烧就是这里不开水
First one. Don’t turn on the faucet.
0:01:27.775,0:01:28.975
这里面是有水的
There is water inside.	
0:01:29.675,0:01:31.975
从冷水变成开水要多久
How long times the cold water become boiling water.
0:01:32.225,0:01:38.025
然后呢我就再用这个里面不放水干烧会变成什么样子
The other one. I let it be heated when it is empty. See what is it going to look like.
0:01:38.525,0:01:40.950
首先我们把锅里面的水加满
First of all. we fill the wok up with water.
0:01:41.250,0:01:43.425
因为这个锅不可以干烧
Because it is can’t be heated when it’s empty.
0:01:46.875,0:01:48.975
然后我们把里面的水放满
Then we fill it up.
0:01:52.700,0:01:55.050
好啦现在我们就把这个水给关掉了
Ok. We turn it off.
0:01:55.525,0:01:56.775
关掉就这样烧
Just heat it.
0:01:58.300,0:02:00.140
我们可以摸一下用手摸一下这里
We could touch it here.
0:02:00.140,0:02:01.775
现在已经很烫了
It feels hot.
0:02:02.725,0:02:07.300
就干烧这么大概10几秒钟下面就已经开始很烫了
It was heated for only 10 seconds, the bottom is hot.
0:02:17.725,0:02:20.800
现在的水温在逐步增加
The water temperature is increasing gradually. 
0:02:21.750,0:02:25.675
 但是我们这边锅里面的水已经快开了
But the water in the wok is going to boil.
0:02:32.450,0:02:34.500
好 里面的水开始慢慢热了
Ok. The water inside is getting warmer.
0:02:44.200,0:02:47.400
我们现在这个盆里面的（井）水大概有10℃左右了
The water temperature of the basin is around 10 degree.
0:02:49.650,0:02:52.075
像我们经常炒菜的话
Like us, always cook.
0:02:52.750,0:02:56.350
1个灶炒个1个小时2个小时是很正常的
It’s normal, we cook for 1 or 2 hours on 1 stove.
0:03:01.475,0:03:04.450
现在这个盆里面的水大概是30℃的样子
Now the water temperature of the basin is like 30 degree.
0:03:11.796,0:03:13.300
差不多有40℃了
Almost 40 degree.
0:03:14.425,0:03:16.850
说真的我还从来没有这样子烧过开水
Honestly, I never heat water like this.
0:03:17.595,0:03:18.481
因为也不敢
Because I’m afraid.
0:03:18.675,0:03:21.125
师傅看到会骂的
Master would scold me.
0:03:21.950,0:03:24.625
然后老板看到的话也会扣工资
And boss would deduct pay, if he see it.
0:03:25.600,0:03:27.175
这应该是我第一次这么干
It was like the first time I did it.
0:03:29.800,0:03:31.750
现在有一点点烫手了
Now it’s burning hand.
0:03:41.925,0:03:44.700
我们这个水可能有70℃-80℃了
It might be 70-80 degree.
0:03:51.925,0:03:54.951
这个水在慢慢的开始变浑
The water becoming muddy gradually.
0:03:54.951,0:03:56.975
而且有点要开的感觉了
And it’s about to boil.
0:04:04.775,0:04:07.725
好啦现在经过我们差不多半个小时的烧
Ok. After about 30 mins heating it.
0:04:08.350,0:04:10.550
这个没有放水进去现在已经变成了
Without adding water, now it becomes
0:04:11.350,0:04:13.425
几乎变成了开水
Almost boiling water.
0:04:15.150,0:04:16.900
用来炒菜的话是用不了的
It can’t be use for cooking.
0:04:16.975,0:04:18.200
有的菜我们要用冷水
We need cold water some dishes. 
0:04:18.800,0:04:22.325
好 现在我们来把这个水给它倒出来
Ok. We pour away the water.
0:04:33.875,0:04:37.250
大家可以看一下干烧的时候我们这个水分已经烧干了
You could see, the water boil away when the basin is empty.
0:04:37.750,0:04:39.400
我估计这样子来得非常快
I estimate it will(be scorched) come very soon.
0:04:39.400,0:04:44.325
不要5分钟这个（装水的）锅就会被烧黑
The basin will be scorched less than 5 mins.
0:04:49.875,0:04:52.500
好 我们这个不锈钢已经变形了现在
Ok. The stainless steel deformed.
0:04:56.550,0:04:58.250
来 我关火给大家看一下
Ok. I turn off the heat to show you.
0:04:59.250,0:05:02.900
如果我现在放冷水进去肯定会冒出很多白烟出来
If I put cold water in it right now, there must come out white smoke.

0:05:05.075,0:05:06.350
听到没这个声音
Do you hear this sound?
0:05:18.775,0:05:19.725
这个水已经烫了
The water is already hot.
0:05:20.175,0:05:23.475
也就是说我们这个里面不放水干烧的话
In other words, if we do not put water in it,
0:05:23.475,0:05:26.550
这个会烧黑 已经烧黑了
It will be scorched.  Already scorched.
0:05:26.750,0:05:30.750
这个是我们刚才故意干烧的一个结果
This is the result of our deliberate dry burning.
0:05:30.775,0:05:32.050
我们看一下这个
Let us take a look at this.
0:05:32.375,0:05:34.875
我们这个是经常放水烧的
This is the basin we usually put water in.
0:05:35.800,0:05:36.550
对比一下
Make a Comparison
0:05:37.050,0:05:41.700
这个的话如果不放水就会烧干烧焦
This one, if we do not put water in, it will be scorched.
0:05:42.000,0:05:48.425
正规厨房来说的话这个地方它是一个流动水
In a standard kitchen, this place has a fluid water.
0:05:48.550,0:05:49.700
然后在这个地方
Then at this place
0:05:50.075,0:05:52.250
这里我们不动它
We do not move it.
0:05:52.275,0:05:53.100
就感觉这里
Use here only.
0:05:54.700,0:05:55.975
这里还会放一个盆
There will have another basin here.
0:05:56.825,0:05:59.550
我们这里面的水是用来洗锅用的
The water in here is use for washing woks.
0:05:59.550,0:06:01.525
这里面的水是用来炒菜用的
The water in here is use for cooking.
0:06:01.975,0:06:06.350
所以我们这个会一直把它开起来
So we always make it open
0:06:06.450,0:06:08.000
作为一个流动水
Be a fluid water.
0:06:11.975,0:06:14.100
好啦今天的实验就到这里
OK. The experiment is done.
0:06:14.400,0:06:16.300
今天浪费了一大半瓶煤气
It wasted more than a half of tank of gas.
0:06:17.000,0:06:20.000
通过这个实验我们得出来了一个结论
Though the experiment, we draw a conclusion.
0:06:20.075,0:06:25.150
就是这个必须开水一直给它流动起来
It is that this water must be fluid. 
0:06:25.500,0:06:27.900
不然这里面的水会变得非常烫
If not, the water inside will be very hot.
0:06:28.450,0:06:30.525
就是说我们炒菜嘛用不上
That means we can’t use it when we cook.
0:06:31.600,0:06:34.700
然后我们这个盆里面必须要有足够的水
Then the basin must have enough water in it.
0:06:34.800,0:06:37.125
如果没有水的话会把这个烧坏
If not, empty basin will be scorched.
0:06:37.425,0:06:41.000
把这一片温度过高烧坏了之后
After the part be burned course of high heat.
0:06:41.975,0:06:43.700
里面的高温泥会掉
The high temperature resistance material inside will be burned out.
0:06:43.875,0:06:46.250
掉了之后的话这个边也会掉
After that, the edge of this part will be burned out either.
0:06:46.450,0:06:47.950
慢慢的这个灶就会塌
This stove will be broken gradually.
0:06:48.225,0:06:50.825
所以的话我们必须放水
So we have to put water in.
0:06:51.650,0:06:54.050
以后大家就不要再说浪费这个事情了
After today, we don’t talk about wasting.
0:06:54.250,0:06:55.625
好啦 本期视频到这里
Ok. This video finish here.
0:06:55.875,0:06:56.400
拜拜
Bye!
