### ISSUE TITLE
[手工耿] 噴火龍頭盔 - https://youtu.be/YSdOfKjfCpY

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1125]
https://youtu.be/YSdOfKjfCpY
<p>&#35270;&#39057;&#21457;&#24067;&#20110; June 4, 2020 at 08:00PM</p>
<p>&#26631;&#39064;<br>
&#12304;&#25163;&#24037;&#32831;&bull;Useless Edison&#12305;&#33258;&#35069;&#22132;&#28779;&#40845;&#38957;&#30420;&#65292;&#36538;&#30528;&#20063;&#33021;&#29138;&#28900;&#22826;&#26041;&#20415;&#21862;&#65281;</p>
<p>&#31616;&#20171;<br>
&#25163;&#24037;&#32831;&#20170;&#26085;&#33258;&#35069;&#30446;&#37636;&mdash;&mdash; &#32937;&#22352;&#26885;&#65306;&#35731;&#25105;&#20497;&#25179;&#36215;&#32937;&#19978;&#30340;&#25812;&#23376;&#65281; &#38748;&#38748;&#24125;&#65306;&#38568;&#26178;&#38568;&#22320;&#65292;&#24819;&#38748;&#23601;&#38748;&#65281; &#40845;&#38957;&#28900;&#20018;&#65306;&#31449;&#30528;&#36538;&#30528;&#37117;&#33021;&#29138;&#28900;&#65281; &mdash;&mdash; &#21029;&#20154;&#31505;&#25105;&#22826;&#30219;&#30322;&#65292;&#31505;&#23436;&#30219;&#30322;&#31505;&#25105;&#38289;&#12290; &#22823;&#23478;&#22909;&#65292;&#25105;&#26159;&#25163;&#24037;&#32831;&#65292;&#22914;&#26524;&#20320;&#21916;&#27489;&#25105;&#30340;&#35222;&#38971;&#65292;&#27489;&#36814;&#40670;&#25802;&#35330;&#38321;&#12290; #&#25163;&#24037;&#32831; #UselessEdison #&#32831;&#24101; #ChineseEdison #shougonggeng #handicraft #diy #&#25163;&#24037; #&#30828;&#26680; #&#33258;&#35069;&#27231;&#22120;&#20154; #inventions #&#20013;&#22283;&#30332;&#26126; #&#20013;&#22283;&#24859;&#36842;&#29983; #&#24290;&#26612;&#24859;&#36842;&#29983; #&#25630;&#31505;&#30332;&#26126;</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/113772413d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by Kevinzheng5** [comment]
认领

**Comment by Kevinzheng5** [comment]
标题
【手工耿】自制喷火龙头盔，躺着也能烧烤太方便啦
【Useless Edison】Dragon Head Grill

简介
手工耿今日自制自录---肩座椅：让我们扛起肩上的担子！静静帽：随时随地，想静就静！龙头烤串：站着躺着都能烧烤！---别人笑我太疯癫，笑完疯癫笑我闲。大家好，我是手工耿，如果你喜欢我的视频，欢迎点击订阅。
Useless Edison makes: Shoulder seat: Let’s carry our burdens! Alone hat: Alone space anywhere you want! Dragon head grill: Having a grill even lying down! Others tease at my madness, and so much leisure time I have. Hi guys, I’m useless Edison. If you like my video, please click subscribe!

字幕
0:00:00.000,0:00:02.000
(肩座椅)
(Shoulder Seat)

0:00:02.260,0:00:05.220
作为男人，有时候就要肩负起整个家庭
As men, we need to carry our families on our shoulders sometimes

0:00:05.280,0:00:07.495
扛起你的爱人或你的孩子
Like your wife and kids

0:00:07.500,0:00:09.760
但是说直接扛的话会特别疼
But it can hurt if you carry them directly

0:00:09.780,0:00:12.160
他们会情不自禁地揪你的头发
They will pull your hair sometimes

0:00:12.435,0:00:14.895
所以说我做了一个肩坐椅
So I made a shoulder seat

0:00:15.220,0:00:16.280
就是这个
Ta-da

0:00:18.780,0:00:21.280
纯手工，量身定做
Hand crafted and customized

0:00:21.280,0:00:24.325
使它像一副铠甲一样穿在身上
Worn like an armor

0:00:24.325,0:00:26.165
你不会感到一丝不适
No discomfort at all

0:00:26.165,0:00:29.515
反而会给你带来许多男儿阳刚之气
On the contrary, it really boosts your manhood

0:00:31.015,0:00:33.415
靠背还有扶手的设计
The designed seatback and armrest 

0:00:33.415,0:00:36.825
让坐在肩上的人更加安全，更加舒适
Offers safety and comfort to users sitting on it

0:00:36.840,0:00:40.940
也解决了他情不自禁薅你头发的问题
And it prevents them from pulling your hair

0:00:55.260,0:00:57.160
(静静帽)
（Alone Hat）

0:00:57.500,0:01:00.100
过度的劳累巨大的压力
Life comes with struggling hard work and huge pressures

0:01:00.220,0:01:02.480
还有生活中大大小小的烦心事
Not to mention all sorts of trouble

0:01:02.500,0:01:04.140
每当我们面对它们的时候
Every time they hit

0:01:04.140,0:01:05.820
都想找一个地方静一静
We just want to be alone somewhere and calm down

0:01:06.380,0:01:08.600
但是说这个能让我们静一静的地方
However, the places for us to be alone 

0:01:08.700,0:01:09.860
却非常少
Are really limited and few

0:01:10.100,0:01:11.720
有时候还经常会被人打扰
And we get disturbed too often at those few places

0:01:12.100,0:01:13.500
所以说这几天
So these days

0:01:13.500,0:01:14.340
通过研究
After some research

0:01:14.340,0:01:16.680
我做了一个静静帽
I made an alone hat

0:01:18.060,0:01:22.000
戴上它之后跟我们普通穿的连帽衫外观差不多
The appearance of it is very similar to a hoodie

0:01:22.500,0:01:26.220
也不会给我们的生活和工作带来不便
Doesn’t bother our life or work

0:01:26.220,0:01:27.900
当你想静静的时候
When you want to be alone

0:01:27.900,0:01:29.440
只需要把这个拉下来就行
Just pull this cover down

0:01:29.800,0:01:32.820
它能快速的给你一个安静封闭的空间
It quickly offers you a quiet and close space

0:01:33.085,0:01:35.695
不受时间地点和空间的约束
Anytime and anywhere you want

0:01:39.120,0:01:41.960
当你玩手机，想静静的时候
When you are checking your phone and want to be alone

0:01:48.200,0:01:50.860
当你上厕所，想静静的时候
When you are in the bathroom and want to be alone

0:01:58.700,0:02:01.560
当你骑自行车，想静静的时候
When you are bicycling and want to be alone

0:02:04.700,0:02:07.885
它能让你想静静，就能够静静
It gives you the space to be alone, whenever you want

0:02:07.885,0:02:10.660
静的快速，静的彻底
Quickly and completely

0:02:27.660,0:02:29.680
(龙头烤串)
(Dragon Head Grill)

0:02:29.940,0:02:33.440
快要夏天了，大家都喜欢去外边吃点烧烤
Almost summer down here, everybody enjoys a barbecue outside

0:02:33.440,0:02:34.240
喝点啤酒
Maybe a couple of beers with it

0:02:34.240,0:02:35.440
我认为自己做
I enjoy having a barbecue myself

0:02:35.440,0:02:37.700
才能真正体会到烧烤的乐趣
So that I can have the real fun of a barbecue

0:02:37.705,0:02:40.605
为了让烧烤的过程更加有趣和炫酷
To make the barbecue extra fun and cool 

0:02:40.605,0:02:43.675
我准备做一个龙头烧烤器
I’m going to make a dragon head grill

0:03:56.955,0:03:59.415
这台龙头烤肉器外观炫酷
It looks zazzy 

0:04:03.580,0:04:04.960
操作方便
And it’s easy to operate

0:04:05.080,0:04:10.180
（危险操作请勿模仿）
(Dangerous, don’t copy)

0:04:10.340,0:04:11.340
烤串儿
Kabobs!

0:04:12.505,0:04:13.965
站着烤累了之后
If you are tired standing

0:04:14.355,0:04:15.385
还可以躺着烤
You can also lie down with it

0:04:32.365,0:04:34.665
而且我做的这款龙头圣器
Also, this dragon head grill

0:04:34.665,0:04:36.340
已经在龙之怒吼手游里了
Is in the app game called “Roar of dragons”

0:04:36.340,0:04:39.600
在游戏里你也可以带上这款炫酷的龙头
You can wear it in the game too

0:04:39.600,0:04:42.180
去烤一些小龙虾啊，考一些串儿之类的
You can grill some crayfish and kabobs

0:04:42.325,0:04:45.695
在游戏里还有其他各式各样炫酷的龙
There are also other sorts of dragons in the game, too

0:04:45.795,0:04:48.345
我做的这款官方说也会送给大家
The app announced that this dragon head grill will be offered to you guys

0:04:48.345,0:04:49.745
大家可以去看一看
Go check it out
