### ISSUE TITLE
[雪鱼] 西安卤汁凉粉 - https://youtu.be/SJusp6fcZAo

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#1126]
**视频链接**：https://youtu.be/SJusp6fcZAo

发布日期：2020年6月5日 20:00

# 请翻译以下全部内容

```


字幕
1
00:00:01,160 --> 00:00:03,160
陕西 西安

2
00:00:22,340 --> 00:00:24,340
色香俱全

3
00:00:32,640 --> 00:00:34,160
走在回民街的巷子里

4
00:00:34,160 --> 00:00:36,520
正好遇见大叔在这个地方熬卤汁

5
00:00:36,520 --> 00:00:40,400
看来今天的午饭有着落了 吃一份卤汁凉粉

6
00:01:27,360 --> 00:01:30,080
来吃卤汁凉粉的时候

7
00:01:30,080 --> 00:01:33,120
一人给一个碗 还给了我们一点馍

8
00:01:40,800 --> 00:01:46,000
掰成黄豆粒大小 我每次掰 都感觉掰大了

9
00:01:50,800 --> 00:01:53,480
这个（掰馍的大小）是羊肉泡馍的馍

10
00:01:53,480 --> 00:01:56,880
掰这么大就行 再掰大一点

11
00:02:05,040 --> 00:02:08,080
掰了三分钟 掰好了

12
00:02:08,920 --> 00:02:10,440
叔 帮我弄一下吧

13
00:02:10,440 --> 00:02:11,960
可以

14
00:02:12,360 --> 00:02:14,720
我知道 你吃辣椒不吃

15
00:02:14,720 --> 00:02:15,880
都吃

16
00:02:15,880 --> 00:02:17,180
好来

17
00:02:17,300 --> 00:02:19,300
要加黑白蛋（黑色是松花蛋 白色是煮鸡蛋）

18
00:02:19,680 --> 00:02:21,680
要吃美食届的泥石流

19
00:02:21,680 --> 00:02:22,400
是

20
00:02:24,280 --> 00:02:27,120
这是好多朋友给我们家起的

21
00:02:27,560 --> 00:02:30,400
一种是黑暗料理

22
00:02:30,400 --> 00:02:32,880
一种是泥石流

23
00:02:32,880 --> 00:02:36,360
因为要吃的时候 （发出这种声音）

24
00:02:36,360 --> 00:02:40,480
像泥石流的声音

25
00:02:50,180 --> 00:02:52,180
加蒜蓉

26
00:02:56,220 --> 00:02:58,220
加芥末

27
00:03:29,000 --> 00:03:33,600
再加一个溏心的松花蛋

28
00:03:34,680 --> 00:03:37,160
哇 好重的芥末味

29
00:03:38,080 --> 00:03:40,320
有时候呛的我眼睛都睁不开

30
00:03:47,080 --> 00:03:48,000
好 谢谢

31
00:03:48,000 --> 00:03:49,880
顺着边刨着吃

32
00:03:49,880 --> 00:03:52,840
好的 好的 好的

33
00:03:52,840 --> 00:03:54,320
走吧

34
00:04:05,840 --> 00:04:10,720
这个就是号称 西安美食届的黑暗料理

35
00:04:10,760 --> 00:04:14,640
不过看颜色还挺好看的 不知道味道怎么样

36
00:04:14,760 --> 00:04:17,560
这里面就是 下面是馍 上面是凉粉

37
00:04:17,560 --> 00:04:22,560
浇了卤汁 辣子 放了溏心的松花蛋和白蛋

38
00:04:24,240 --> 00:04:28,080
叔说 得顺着碗沿吃 不能翻

39
00:04:34,960 --> 00:04:38,800
吃的时候 还有点不知所措呢

40
00:04:42,880 --> 00:04:47,480
不仅芥末汁辣眼睛 可能我吃的样子也有点辣眼睛

41
00:04:51,160 --> 00:04:53,680
有点辣

42
00:04:53,680 --> 00:04:56,200
蛋就直接这么吃吗

43
00:05:04,240 --> 00:05:08,360
其实我感觉 卤汁凉粉就是不同食材的搭配

44
00:05:08,360 --> 00:05:11,760
溏心的松花蛋 白蛋

45
00:05:11,760 --> 00:05:14,760
热的卤子 凉粉

46
00:05:14,760 --> 00:05:18,560
还有呢 就是加了辣子和蒜汁的混合味道

47
00:05:18,560 --> 00:05:20,600
麻酱味很浓郁

48
00:05:20,600 --> 00:05:25,440
吃着吃着还有些小惊喜 比如说馍的嚼劲

49
00:05:25,440 --> 00:05:27,640
这一碗就是（调料）该加的都加了

50
00:05:27,640 --> 00:05:29,880
味道呢 酸甜苦辣咸

51
00:05:29,880 --> 00:05:31,640
吃得惯的 可能觉得很美味

52
00:05:31,640 --> 00:05:35,000
吃不惯的 也不要勉强自己

53
00:05:35,000 --> 00:05:38,240
你看 每一个进来的人 来到之后就会被发一个碗

54
00:05:38,240 --> 00:05:40,520
大家就开始在这个地方掰馍

55
00:05:40,520 --> 00:05:43,720
感觉吃个饭 都很有仪式感

56
00:05:49,640 --> 00:05:51,920
能吃惯吗

57
00:05:51,920 --> 00:05:55,280
大部分人 基本上都能吃惯

58
00:05:55,280 --> 00:06:00,640
有一小部分人 他就感觉有芝麻酱 蒜蓉 芥末

59
00:06:00,640 --> 00:06:03,480
他平时又不吃这个

60
00:06:03,480 --> 00:06:06,680
吃不了重口的

61
00:06:06,680 --> 00:06:11,160
有的人 一吃不得了 特别香

62
00:06:11,160 --> 00:06:14,480
适合他那个口味

63
00:06:14,480 --> 00:06:16,120
隔三差五地慢慢 慢慢来

64
00:06:16,120 --> 00:06:20,680
他还把其他的朋友带来

65
00:06:20,680 --> 00:06:24,160
有的外地朋友来了之后 他真的吃不惯

66
00:06:24,160 --> 00:06:27,880
因为这个调料 佐料是比较偏重的

67
00:06:27,880 --> 00:06:33,040
西安人 本身吃这个调料 比如说羊肉泡馍 卤汁凉粉

68
00:06:33,040 --> 00:06:37,040
这都是比较重的一个口味

69
00:06:37,560 --> 00:06:41,720
外地人来了以后 接受不了 一下子接受不了

70
00:06:41,720 --> 00:06:46,360
吃过几次的时候 慢慢慢慢就吃习惯了

71
00:06:46,360 --> 00:06:49,600
这一习惯 不得了

72
00:06:50,680 --> 00:06:51,560
来了

73
00:06:51,560 --> 00:06:54,080
你看 这都是我们家的老粉丝

74
00:06:54,080 --> 00:06:56,840
老顾客了 老吃家了

75
00:07:35,040 --> 00:07:38,280
一大早呢吃了大家传说当中的 黑暗料理

76
00:07:38,280 --> 00:07:43,240
其实并没有想象当中的那么 难以接受

77
00:07:43,720 --> 00:07:47,000
好了 今天的视频就到这儿 拜拜


```

**Comment by shuaisoserious** [comment]
认领

**Comment by shuaisoserious** [comment]
字幕
1
00:00:01,160 --> 00:00:03,160
陕西 西安
Xi’an, Shanxi
2
00:00:22,340 --> 00:00:24,340
色香俱全
Full of flavor and fragment
3
00:00:32,640 --> 00:00:34,160
走在回民街的巷子里
Walking in the alley of khui khui street
4
00:00:34,160 --> 00:00:36,520
正好遇见大叔在这个地方熬卤汁
Just met uncle oiling gravy in this place
5
00:00:36,520 --> 00:00:40,400
看来今天的午饭有着落了 吃一份卤汁凉粉
It’s our today’s lunch, eat a bean jelly with gravy
6
00:01:27,360 --> 00:01:30,080
来吃卤汁凉粉的时候
When we are ready to eat a bean jelly with gravy
7
00:01:30,080 --> 00:01:33,120
一人给一个碗 还给了我们一点馍
We have an empty bowl and a steamed bun
8
00:01:40,800 --> 00:01:46,000
掰成黄豆粒大小 我每次掰 都感觉掰大了
We need breaking it into the size of soybeans, but i think i breaking it into bigger pieces every time
9
00:01:50,800 --> 00:01:53,480
这个（掰馍的大小）是羊肉泡馍的馍
The size of breaking steamed bun are same as lamb paomo
10
00:01:53,480 --> 00:01:56,880
掰这么大就行 再掰大一点
Breaking into size like this, a little bigger
11
00:02:05,040 --> 00:02:08,080
掰了三分钟 掰好了
It took me 3 minutes to finish it
12
00:02:08,920 --> 00:02:10,440
叔 帮我弄一下吧
Uncle, help me please
13
00:02:10,440 --> 00:02:11,960
可以
sure
14
00:02:12,360 --> 00:02:14,720
我知道 你吃辣椒不吃
I know, do you want spicy pepper?
15
00:02:14,720 --> 00:02:15,880
都吃
Im fine
16
00:02:15,880 --> 00:02:17,180
好来
okay
17
00:02:17,300 --> 00:02:19,300
要加黑白蛋（黑色是松花蛋 白色是煮鸡蛋）
Black or white egg?(black egg is century egg, white egg is boiled egg)
18
00:02:19,680 --> 00:02:21,680
要吃美食届的泥石流
You have to try “debris flow” in Gastronomy
19
00:02:21,680 --> 00:02:22,400
是
What’s that?
20
00:02:24,280 --> 00:02:27,120
这是好多朋友给我们家起的
That’s how our customers call us 
21
00:02:27,560 --> 00:02:30,400
一种是黑暗料理
First is wicked cuisine
22
00:02:30,400 --> 00:02:32,880
一种是泥石流
And “debris  flow”
23
00:02:32,880 --> 00:02:36,360
因为要吃的时候 （发出这种声音）
Because it sounds like debris flow
24
00:02:36,360 --> 00:02:40,480
像泥石流的声音
When they eat it
25
00:02:50,180 --> 00:02:52,180
加蒜蓉
Add mashed garlic
26
00:02:56,220 --> 00:02:58,220
加芥末
Add black mustard seed
27
00:03:29,000 --> 00:03:33,600
再加一个溏心的松花蛋
Add an century egg with soft yolk
28
00:03:34,680 --> 00:03:37,160
哇 好重的芥末味
Wow, pretty strong flavor of black mustard seed 
29
00:03:38,080 --> 00:03:40,320
有时候呛的我眼睛都睁不开
Sometimes I can’t even open my eyes
30
00:03:47,080 --> 00:03:48,000
好 谢谢
Okay, thank you
31
00:03:48,000 --> 00:03:49,880
顺着边刨着吃
Eat along the side 
32
00:03:49,880 --> 00:03:52,840
好的 好的 好的
okay
33
00:03:52,840 --> 00:03:54,320
走吧
Let’s go
34
00:04:05,840 --> 00:04:10,720
这个就是号称 西安美食届的黑暗料理
This is called wicked cuisine of Xi’an Gastronomy
35
00:04:10,760 --> 00:04:14,640
不过看颜色还挺好看的 不知道味道怎么样
The color are not bad, i don’t know how it taste
36
00:04:14,760 --> 00:04:17,560
这里面就是 下面是馍 上面是凉粉
Steamed bun at bottom in the bowl and bean jelly on it
37
00:04:17,560 --> 00:04:22,560
浇了卤汁 辣子 放了溏心的松花蛋和白蛋
With topping of gravy, spicy pepper, both century egg and boiled egg with soft yolk
38
00:04:24,240 --> 00:04:28,080
叔说 得顺着碗沿吃 不能翻
Uncle said we should eat along the side of the bowl, not just mixed it up
39
00:04:34,960 --> 00:04:38,800
吃的时候 还有点不知所措呢
I don’t know about it before when i eat it
40
00:04:42,880 --> 00:04:47,480
不仅芥末汁辣眼睛 可能我吃的样子也有点辣眼睛
Not just black mustard seed make my eyes sting, 
41
00:04:51,160 --> 00:04:53,680
有点辣
A little spicy
42
00:04:53,680 --> 00:04:56,200
蛋就直接这么吃吗
Just eat them straightly 
43
00:05:04,240 --> 00:05:08,360
其实我感觉 卤汁凉粉就是不同食材的搭配
Actually i think bean jelly with gravy is mixed with different ingredients 
44
00:05:08,360 --> 00:05:11,760
溏心的松花蛋 白蛋
Century egg and boiled egg both with soft yolk
45
00:05:11,760 --> 00:05:14,760
热的卤子 凉粉
Hot gravy and bean jelly
46
00:05:14,760 --> 00:05:18,560
还有呢 就是加了辣子和蒜汁的混合味道
And the mixed of spicy pepper and garlic sauce taste
47
00:05:18,560 --> 00:05:20,600
麻酱味很浓郁
And strong flavor of sesame sauce 
48
00:05:20,600 --> 00:05:25,440
吃着吃着还有些小惊喜 比如说馍的嚼劲
The texture of steamed buns surprised me
49
00:05:25,440 --> 00:05:27,640
这一碗就是（调料）该加的都加了
All mixed of condiments in the bowl of bean jelly
50
00:05:27,640 --> 00:05:29,880
味道呢 酸甜苦辣咸
With flavors of sweetness, sourness, bitter, spicy and salty
51
00:05:29,880 --> 00:05:31,640
吃得惯的 可能觉得很美味
People who used with it might think it’s delicious
52
00:05:31,640 --> 00:05:35,000
吃不惯的 也不要勉强自己
Don’t force yourself to do it if you’re not used to it
53
00:05:35,000 --> 00:05:38,240
你看 每一个进来的人 来到之后就会被发一个碗
Look, everyone who come in will get an empty bowl
54
00:05:38,240 --> 00:05:40,520
大家就开始在这个地方掰馍
Everyone start breaking their steamed buns in this place
55
00:05:40,520 --> 00:05:43,720
感觉吃个饭 都很有仪式感
it feels a sense of ritual when they gonna eat
56
00:05:49,640 --> 00:05:51,920
能吃惯吗
Can you get used to it?
57
00:05:51,920 --> 00:05:55,280
大部分人 基本上都能吃惯
mostly
58
00:05:55,280 --> 00:06:00,640
有一小部分人 他就感觉有芝麻酱 蒜蓉 芥末
A few people don’t like sesame sauce, garlic sauce, and black mustard seed 
59
00:06:00,640 --> 00:06:03,480
他平时又不吃这个
He not eat this usually
60
00:06:03,480 --> 00:06:06,680
吃不了重口的
Can not eat salty food
61
00:06:06,680 --> 00:06:11,160
有的人 一吃不得了 特别香
Someone like this
62
00:06:11,160 --> 00:06:14,480
适合他那个口味
It fit his food behavior
63
00:06:14,480 --> 00:06:16,120
隔三差五地慢慢 慢慢来
He start to come here often
64
00:06:16,120 --> 00:06:20,680
他还把其他的朋友带来
And he bring his friends as well
65
00:06:20,680 --> 00:06:24,160
有的外地朋友来了之后 他真的吃不惯
After some friends who from other city came and really couldn’t get used to it
66
00:06:24,160 --> 00:06:27,880
因为这个调料 佐料是比较偏重的
Because the condiments in pretty strong flavors
67
00:06:27,880 --> 00:06:33,040
西安人 本身吃这个调料 比如说羊肉泡馍 卤汁凉粉
People who from Xi’an used to 
68
00:06:33,040 --> 00:06:37,040
这都是比较重的一个口味
Pretty strong flavor 
69
00:06:37,560 --> 00:06:41,720
外地人来了以后 接受不了 一下子接受不了
People who from other city not used at first time
70
00:06:41,720 --> 00:06:46,360
吃过几次的时候 慢慢慢慢就吃习惯了
After eating it a few times, they gradually get used to it
71
00:06:46,360 --> 00:06:49,600
这一习惯 不得了
It never stop after they get used to it
72
00:06:50,680 --> 00:06:51,560
来了
here
73
00:06:51,560 --> 00:06:54,080
你看 这都是我们家的老粉丝
Look, they all are our fans
74
00:06:54,080 --> 00:06:56,840
老顾客了 老吃家了
Old customers, and old foodies
75
00:07:35,040 --> 00:07:38,280
一大早呢吃了大家传说当中的 黑暗料理
Eat the “wicked cuisine” people called at the morning
76
00:07:38,280 --> 00:07:43,240
其实并没有想象当中的那么 难以接受
Actually it’s not what i thought it hard to acceptable
77
00:07:43,720 --> 00:07:47,000
好了 今天的视频就到这儿 拜拜
Okay, today’s video is done. Bye.
