### ISSUE TITLE
[老饭骨] 大爷炸酱面 - https://youtu.be/VgXbZspMnd8

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1128]
**视频链接**：https://youtu.be/VgXbZspMnd8

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【國宴大師•大爺炸醬麵】大媽專屬炸醬麵，大爺料理四十年，關鍵在麵碼，老北京炸醬麵究竟有幾種麵碼？|老飯骨

简介
小友們好，今兒個輪到大爺給大家做炸（塞）醬（狗）面（糧）了。這老北京炸醬麵每家做法都不一樣，大爺家做的呢，是大媽專屬炸醬麵，大爺這一做就做了四十年，可謂是見證了大爺大媽這四十多年來的恩恩愛愛。
所以家庭和睦的關鍵秘訣是什麼？大爺可教你們了，小友們還等什麼呢？趕緊學會了做給最愛的人吃吧！
PS. 前段時間二伯也做了炸醬麵，比大爺的要複雜一些，奉上地址，大家都可以學習。
https://www.youtube.com/watch?v=iCFTNH4MlAg&t=59s

字幕
1
00:00:00,000 --> 00:00:02,000
说老北京炸酱面什么特点

2
00:00:02,000 --> 00:00:04,560
关键在面码 就是一种酱

3
00:00:04,560 --> 00:00:06,880
我就爱吃 不但你爱吃

4
00:00:06,880 --> 00:00:08,560
你吃了四十年了 对

5
00:00:08,560 --> 00:00:11,120
家庭版的 炸酱面

6
00:00:11,120 --> 00:00:12,400
我不知道你还有印象吗

7
00:00:12,400 --> 00:00:14,840
四十年前我第一次上家去

8
00:00:14,840 --> 00:00:16,400
我们现在这老岳母

9
00:00:16,400 --> 00:00:18,200
说今儿中午别走了

10
00:00:18,200 --> 00:00:19,920
吃个炸酱面吧

11
00:00:19,920 --> 00:00:21,440
老太太这儿咕嘟咕嘟咕嘟

12
00:00:21,440 --> 00:00:22,840
咕嘟得有半个多小时

13
00:00:22,840 --> 00:00:24,760
酱炸得特别的香

14
00:00:24,760 --> 00:00:28,000
过了一会端上了一桌子面码

15
00:00:28,000 --> 00:00:32,040
大盘小盘小碗 十二种面码

16
00:00:32,040 --> 00:00:34,560
和好了 还要饧一饧

17
00:00:34,560 --> 00:00:36,600
咱拿个小布给它盖上

18
00:00:36,600 --> 00:00:38,840
所以咱们结婚这么多年

19
00:00:38,840 --> 00:00:41,040
每次我炸酱的时候

20
00:00:41,040 --> 00:00:45,320
一直没断了 老是惦记着

21
00:00:45,320 --> 00:00:47,320
五花 肥瘦相间

22
00:00:47,320 --> 00:00:50,160
一会煸的时候先煸这肥的

23
00:00:50,160 --> 00:00:54,240
今天咱们也得按照标准来 肥的单切

24
00:00:54,240 --> 00:00:58,320
说四十多年 大爷对大妈那么好

25
00:00:58,320 --> 00:01:01,080
就是做顿饭吃呗 那不一样

26
00:01:01,080 --> 00:01:04,760
那是代表着好多情感

27
00:01:04,760 --> 00:01:08,080
又出汗了 卖力气 这是力气活

28
00:01:08,080 --> 00:01:10,760
家里头 是做饭的活儿

29
00:01:10,760 --> 00:01:13,760
绝对是大爷

30
00:01:13,760 --> 00:01:17,000
咱看看这叫骰子块是吗 骰子丁

31
00:01:17,000 --> 00:01:18,160
咱切点小料

32
00:01:18,160 --> 00:01:21,120
搁点姜搁点葱 去掉这肉的腥味

33
00:01:21,120 --> 00:01:24,160
葱花切大点 一会儿一煸小了

34
00:01:24,160 --> 00:01:25,040
开始炸酱

35
00:01:25,040 --> 00:01:29,040
这锅得先烧一烧 热锅凉油

36
00:01:29,040 --> 00:01:32,280
先放肥的肉 先放肥肉

37
00:01:32,280 --> 00:01:35,320
然后再煸出它的油来

38
00:01:35,320 --> 00:01:37,120

39
00:01:37,120 --> 00:01:39,000
你看这个油快出来了

40
00:01:39,000 --> 00:01:40,640
但是你看这油不亮

41
00:01:40,640 --> 00:01:44,560
说明它有水气 肉就容易腥

42
00:01:44,560 --> 00:01:49,400
这油变清亮了 就说明这肉煸透了

43
00:01:49,400 --> 00:01:53,000
我准备点虾 以前没见你搁过虾啊

44
00:01:53,000 --> 00:01:56,160
没虾啊 四十年前哪儿有虾啊

45
00:01:56,160 --> 00:02:00,320
那阵儿买肉都买不起 还要肉票呢

46
00:02:00,320 --> 00:02:03,680
差不多了 葱姜放进去

47
00:02:03,680 --> 00:02:06,960
酱 我们用北京的黄酱

48
00:02:06,960 --> 00:02:11,000
就一般的酱就行 有什么酱使什么酱

49
00:02:11,000 --> 00:02:14,000
要加点水

50
00:02:14,000 --> 00:02:18,000
酱够咸 咱们不加其它东西了

51
00:02:18,000 --> 00:02:21,800
加点酱油 要它那颜色

52
00:02:21,800 --> 00:02:24,720
一是颜色 另外也稀释这个酱

53
00:02:24,720 --> 00:02:28,840
过去老北京炸酱面咸香

54
00:02:28,840 --> 00:02:32,760
有的还炸素酱 蘑菇酱鸡蛋酱

55
00:02:32,760 --> 00:02:35,120
这个不能用大火

56
00:02:35,120 --> 00:02:37,400
不能大火 小火咕嘟着

57
00:02:37,400 --> 00:02:39,400
大妈你看这油多吗

58
00:02:39,400 --> 00:02:41,240
看见油了吗 看不出来了吧

59
00:02:41,240 --> 00:02:43,160
油都跑酱里头去了

60
00:02:43,160 --> 00:02:46,160
待会再搁上半小时以后

61
00:02:46,160 --> 00:02:48,480
看看这油还会渗透出来

62
00:02:48,480 --> 00:02:50,080
着急一点的（炸）二十分钟

63
00:02:50,080 --> 00:02:52,080
不着急的话得照着四十分钟（炸）

64
00:02:52,080 --> 00:02:55,080
多咕嘟会儿 越咕嘟越香

65
00:02:55,080 --> 00:02:57,600
别把它炸得太干了

66
00:02:57,600 --> 00:03:00,640
你看现在稀稠度合适

67
00:03:00,640 --> 00:03:05,120
什么都不搁 就搁点酱油搁点水

68
00:03:05,120 --> 00:03:08,600
吃酱的原味 吃肉的香味

69
00:03:08,600 --> 00:03:11,360
说老北京炸酱面什么特点

70
00:03:11,360 --> 00:03:15,440
关键在面码和后边的调味

71
00:03:15,440 --> 00:03:16,760
我觉得这咱们做到了

72
00:03:16,760 --> 00:03:21,360
香气已经出来了 就快好了

73
00:03:21,360 --> 00:03:25,000
大妈给看着点 我再切点葱花

74
00:03:25,000 --> 00:03:27,040
再放葱

75
00:03:27,040 --> 00:03:30,280
关火 这就行了

76
00:03:30,280 --> 00:03:32,360
鸡精 味精 其它调料

77
00:03:32,360 --> 00:03:34,000
什么糖什么都没放

78
00:03:34,000 --> 00:03:39,680
我还是就喜欢大爷做的这个炸酱面

79
00:03:39,680 --> 00:03:40,920

80
00:03:43,160 --> 00:03:48,600
够溜的啊 水开了 下面条

81
00:03:48,600 --> 00:03:50,720
煮面水要宽

82
00:03:50,720 --> 00:03:53,960
把酱拿过来 来着

83
00:03:53,960 --> 00:03:57,000
这个酱刚才大爷说了

84
00:03:57,000 --> 00:04:00,120
慢慢的这油还能浸出来

85
00:04:00,120 --> 00:04:02,800
现在看出来了 大爷捞面

86
00:04:02,800 --> 00:04:08,360
想半天了 过水别过太凉 因为是炸酱面

87
00:04:08,360 --> 00:04:10,280
拿碗

88
00:04:10,280 --> 00:04:12,120

89
00:04:12,120 --> 00:04:14,600
吃炸酱面给人挑面的时候要注意

90
00:04:14,600 --> 00:04:16,440
别给挑一大碗面

91
00:04:16,440 --> 00:04:19,280
你是让人家吃呢是让人家吃呢

92
00:04:19,280 --> 00:04:21,440
还是不让人吃

93
00:04:21,440 --> 00:04:24,280
就这么多

94
00:04:24,280 --> 00:04:25,320
放面码也得讲究

95
00:04:25,320 --> 00:04:28,720
颜色（胡萝卜） 黄瓜 豆芽

96
00:04:28,720 --> 00:04:35,360
小萝卜 圆白菜 青蒜 绿的

97
00:04:35,360 --> 00:04:38,360
香椿往中间搁 隆重

98
00:04:38,360 --> 00:04:40,120
芹菜

99
00:04:40,120 --> 00:04:43,240
再搁上酱

100
00:04:43,240 --> 00:04:45,080
咱该说什么来着

101
00:04:45,080 --> 00:04:49,480
家有大厨 就是幸福

102
00:04:49,480 --> 00:04:52,160
现在还多了一句话呢

103
00:04:52,160 --> 00:04:56,840
一起热爱 就现在

1
00:00:00,000 --> 00:00:05,005
有网友问 老北京传统炸酱面的面码都有什么

2
00:00:05,005 --> 00:00:06,840
其实最好吃的大白菜

3
00:00:07,240 --> 00:00:09,009
有芹菜 芹菜末

4
00:00:09,309 --> 00:00:11,044
有的有扁豆

5
00:00:11,044 --> 00:00:11,745
豆芽

6
00:00:12,379 --> 00:00:13,680
黄瓜

7
00:00:13,847 --> 00:00:14,914
冬天的心里美

8
00:00:14,914 --> 00:00:17,550
这季节呢 还可以搁点香椿

9
00:00:17,884 --> 00:00:19,986
春天可以搁点香椿

10
00:00:20,120 --> 00:00:23,490
一半凑够八种面码就够了

11
00:00:23,490 --> 00:00:25,492
这八种都是自己喜欢什么就加什么么

12
00:00:25,492 --> 00:00:26,459
不是

13
00:00:26,459 --> 00:00:28,161
但是基本有一个定位

14
00:00:28,161 --> 00:00:33,566
你比如说像白菜啊 茄丝 黄瓜丝啊 芹菜啊

15
00:00:33,967 --> 00:00:36,603
芹菜切丁

16
00:00:36,603 --> 00:00:38,405
还有青蒜

17
00:00:38,405 --> 00:00:40,373
还有青豆

18
00:00:40,373 --> 00:00:43,710
青豆嘴儿 绿豆嘴儿 黄豆芽

19
00:00:43,710 --> 00:00:45,845
二伯回答问题很全面

**Comment by GogoZoe** [comment]
认领

**Comment by GogoZoe** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【國宴大師•大爺炸醬麵】大媽專屬炸醬麵，大爺料理四十年，關鍵在麵碼，老北京炸醬麵究竟有幾種麵碼？|老飯骨
Zhajiangmian (Fried sauce noodles), 40-year-old recipe from Da Ye, the importance of the accompaniments

简介
小友們好，今兒個輪到大爺給大家做炸（塞）醬（狗）面（糧）了。這老北京炸醬麵每家做法都不一樣，大爺家做的呢，是大媽專屬炸醬麵，大爺這一做就做了四十年，可謂是見證了大爺大媽這四十多年來的恩恩愛愛。
所以家庭和睦的關鍵秘訣是什麼？大爺可教你們了，小友們還等什麼呢？趕緊學會了做給最愛的人吃吧！
PS. 前段時間二伯也做了炸醬麵，比大爺的要複雜一些，奉上地址，大家都可以學習。
https://www.youtube.com/watch?v=iCFTNH4MlAg&t=59s

Hello ! Today it’s Da Ye’s turn to show how to do Zhajiangmian. In Beijing, every family has they own way to cook. This time, Da Ye shows how does he cook Zhajiangmian for Da Ma. Da Ye has been cooked this dish for 40 years. This dish is also a witness of the 40 year’s love between Da Ye and Da Ma.
So what’s the secret of having a harmony family ? Da Ye will teach you, what are you waiting for ? Learn this dish and cook it for your lover !
PS. Er Bai has also cooked Zhajiangmian some time ago, his recipe is a little harder, here’s the address : 
https://www.youtube.com/watch?v=iCFTNH4MlAg&t=59s

字幕
1
00:00:00,000 --> 00:00:02,000
说老北京炸酱面什么特点
What’s the specialty of the Zhajiangmian of Beijing

2
00:00:02,000 --> 00:00:04,560
关键在面码 就是一种酱
The importance is the accompaniments, it’s kind of sauce

3
00:00:04,560 --> 00:00:06,880
我就爱吃 不但你爱吃
I love it. Yeah I know it well

4
00:00:06,880 --> 00:00:08,560
你吃了四十年了 对
You have been eating this for 40 years ! Yes !

5
00:00:08,560 --> 00:00:11,120
家庭版的 炸酱面
The family version Zhajiangmian 

6
00:00:11,120 --> 00:00:12,400
我不知道你还有印象吗
I don’t know if you still remember 

7
00:00:12,400 --> 00:00:14,840
四十年前我第一次上家去
40 years ago, the first time that I met your family 

8
00:00:14,840 --> 00:00:16,400
我们现在这老岳母
Your mum, my mother in law now

9
00:00:16,400 --> 00:00:18,200
说今儿中午别走了
She said: Don’t go this noon 

10
00:00:18,200 --> 00:00:19,920
吃个炸酱面吧
We eat Zhajiangmian together

11
00:00:19,920 --> 00:00:21,440
老太太这儿咕嘟咕嘟咕嘟
Your mum cooked the fried sauce

12
00:00:21,440 --> 00:00:22,840
咕嘟得有半个多小时
She had been cooking for 30 min

13
00:00:22,840 --> 00:00:24,760
酱炸得特别的香
The sauce smelled so good

14
00:00:24,760 --> 00:00:28,000
过了一会端上了一桌子面码
A while later, she brought so many accompaniments

15
00:00:28,000 --> 00:00:32,040
大盘小盘小碗 十二种面码
There were some big dishes, small dishes, small bols, 12 accompaniments

16
00:00:32,040 --> 00:00:34,560
和好了 还要饧一饧
Finish mixing, put it aside to wait a moment 

17
00:00:34,560 --> 00:00:36,600
咱拿个小布给它盖上
Cover it with a little fabrics

18
00:00:36,600 --> 00:00:38,840
所以咱们结婚这么多年
So many years that we have been through 

19
00:00:38,840 --> 00:00:41,040
每次我炸酱的时候
Every time I make the fried sauce

20
00:00:41,040 --> 00:00:45,320
一直没断了 老是惦记着
I always remember that

21
00:00:45,320 --> 00:00:47,320
五花 肥瘦相间
Pork belly

22
00:00:47,320 --> 00:00:50,160
一会煸的时候先煸这肥的
Later I will roast firstly the fat part

23
00:00:50,160 --> 00:00:54,240
今天咱们也得按照标准来 肥的单切
Today we still follow the standard, cut the fat part apart

24
00:00:54,240 --> 00:00:58,320
说四十多年 大爷对大妈那么好
40 years ! Da Ye has been so nice to Da Ma

25
00:00:58,320 --> 00:01:01,080
就是做顿饭吃呗 那不一样
It’s just a meal. No it’s different

26
00:01:01,080 --> 00:01:04,760
那是代表着好多情感
That represents so much emotion 

27
00:01:04,760 --> 00:01:08,080
又出汗了 卖力气 这是力气活
Sweat again ! This is a physical job

28
00:01:08,080 --> 00:01:10,760
家里头 是做饭的活儿
In our home, the cooking job

29
00:01:10,760 --> 00:01:13,760
绝对是大爷
It has to be Da Ye

30
00:01:13,760 --> 00:01:17,000
咱看看这叫骰子块是吗 骰子丁
It looks like the dices 

31
00:01:17,000 --> 00:01:18,160
咱切点小料
Chop something for seasoning

32
00:01:18,160 --> 00:01:21,120
搁点姜搁点葱 去掉这肉的腥味
Add some ginger and green onion, to cover the gamey taste

33
00:01:21,120 --> 00:01:24,160
葱花切大点 一会儿一煸小了
The green onion is a little big. It will be smaller when I cook 

34
00:01:24,160 --> 00:01:25,040
开始炸酱
Start to cook the fried sauce

35
00:01:25,040 --> 00:01:29,040
这锅得先烧一烧 热锅凉油
Firstly, heat the pan, hot pan with cold oil

36
00:01:29,040 --> 00:01:32,280
先放肥的肉 先放肥肉
Put the fat part first 

37
00:01:32,280 --> 00:01:35,320
然后再煸出它的油来
Heat it till the grease goes out

38
00:01:35,320 --> 00:01:37,120

39
00:01:37,120 --> 00:01:39,000
你看这个油快出来了
Look the grease is coming out

40
00:01:39,000 --> 00:01:40,640
但是你看这油不亮
But take a look, the oil is not shiny 

41
00:01:40,640 --> 00:01:44,560
说明它有水气 肉就容易腥
It means there’s still water inside, the meat will have the gamey taste

42
00:01:44,560 --> 00:01:49,400
这油变清亮了 就说明这肉煸透了
Now the oil becomes shiny, it means that the meat is well roasted

43
00:01:49,400 --> 00:01:53,000
我准备点虾 以前没见你搁过虾啊
I prepare some shrimps. You didn’t put shrimps before 

44
00:01:53,000 --> 00:01:56,160
没虾啊 四十年前哪儿有虾啊
There was no shrimps, Nowhere to find shrimps 40 years ago in Beijing

45
00:01:56,160 --> 00:02:00,320
那阵儿买肉都买不起 还要肉票呢
Even the meat we couldn’t afford it,  we had to buy with the tickets

46
00:02:00,320 --> 00:02:03,680
差不多了 葱姜放进去
Almost done, put the ginger and green onion in

47
00:02:03,680 --> 00:02:06,960
酱 我们用北京的黄酱
The paste, this is the yellow soybean paste that we use in Beijing 

48
00:02:06,960 --> 00:02:11,000
就一般的酱就行 有什么酱使什么酱
In fact the normal paste is fine, you can use any paste that you have

49
00:02:11,000 --> 00:02:14,000
要加点水
Add some water

50
00:02:14,000 --> 00:02:18,000
酱够咸 咱们不加其它东西了
The sauce is salty enough, so we don’t put other seasoning 

51
00:02:18,000 --> 00:02:21,800
加点酱油 要它那颜色
Add some soy sauce, to bring the color

52
00:02:21,800 --> 00:02:24,720
一是颜色 另外也稀释这个酱
Not only for the color, also for diluting the sauce

53
00:02:24,720 --> 00:02:28,840
过去老北京炸酱面咸香
The Zhajiangmian of Beijing was salty and fragrant in the past

54
00:02:28,840 --> 00:02:32,760
有的还炸素酱 蘑菇酱鸡蛋酱
There are also Zhajiangmian vegetarian, the fried sauce with mushroom or eggs

55
00:02:32,760 --> 00:02:35,120
这个不能用大火
The fire shouldn’t be too strong 

56
00:02:35,120 --> 00:02:37,400
不能大火 小火咕嘟着
Yeah, use the small fire to keep it boiling 

57
00:02:37,400 --> 00:02:39,400
大妈你看这油多吗
Da Ma take a look there’s too much oil ?

58
00:02:39,400 --> 00:02:41,240
看见油了吗 看不出来了吧
You can’t see the oil anymore  

59
00:02:41,240 --> 00:02:43,160
油都跑酱里头去了
because the oil is going into the sauce

60
00:02:43,160 --> 00:02:46,160
待会再搁上半小时以后
A moment later like 30 min

61
00:02:46,160 --> 00:02:48,480
看看这油还会渗透出来
The oil will going out

62
00:02:48,480 --> 00:02:50,080
着急一点的（炸）二十分钟
If you are in hurry, boil it for 20 min

63
00:02:50,080 --> 00:02:52,080
不着急的话得照着四十分钟（炸）
If you have time, boil it for 40 min

64
00:02:52,080 --> 00:02:55,080
多咕嘟会儿 越咕嘟越香
The more it boils, the better it tastes  

65
00:02:55,080 --> 00:02:57,600
别把它炸得太干了
Don’t boil it too dry anyway 

66
00:02:57,600 --> 00:03:00,640
你看现在稀稠度合适
Have a look, it’s prefect sticky 

67
00:03:00,640 --> 00:03:05,120
什么都不搁 就搁点酱油搁点水
Don’t need other thing, just some soy sauce and water

68
00:03:05,120 --> 00:03:08,600
吃酱的原味 吃肉的香味
We can still taste the flavor of the yellow bean paste and the meat

69
00:03:08,600 --> 00:03:11,360
说老北京炸酱面什么特点
Talking about the specialty of the Zhajiangmian

70
00:03:11,360 --> 00:03:15,440
关键在面码和后边的调味
The importance is the accompaniments and the seasoning

71
00:03:15,440 --> 00:03:16,760
我觉得这咱们做到了
I think we have made it

72
00:03:16,760 --> 00:03:21,360
香气已经出来了 就快好了
The aroma is coming out, it’s almost done

73
00:03:21,360 --> 00:03:25,000
大妈给看着点 我再切点葱花
Da Ma you monitor the pan, I chop some green onion

74
00:03:25,000 --> 00:03:27,040
再放葱
Put more green onion

75
00:03:27,040 --> 00:03:30,280
关火 这就行了
Turn off the fire, done !

76
00:03:30,280 --> 00:03:32,360
鸡精 味精 其它调料
Chicken bouillon powder, MSG, and other seasoning 

77
00:03:32,360 --> 00:03:34,000
什么糖什么都没放
No sugar or anything else

78
00:03:34,000 --> 00:03:39,680
我还是就喜欢大爷做的这个炸酱面
I really like Da Ye’s Zhajiangmian

79
00:03:39,680 --> 00:03:40,920

80
00:03:43,160 --> 00:03:48,600
够溜的啊 水开了 下面条
Nice, the water is boiling, noodles in

81
00:03:48,600 --> 00:03:50,720
煮面水要宽
The noodles must be boiling in a lot of water

82
00:03:50,720 --> 00:03:53,960
把酱拿过来 来着
Bring the sauce, here you are

83
00:03:53,960 --> 00:03:57,000
这个酱刚才大爷说了
Da Ye said just now

84
00:03:57,000 --> 00:04:00,120
慢慢的这油还能浸出来
The oil will slowly come out

85
00:04:00,120 --> 00:04:02,800
现在看出来了 大爷捞面
Now we can see the oil, Da Ye takes the noodles out 

86
00:04:02,800 --> 00:04:08,360
想半天了 过水别过太凉 因为是炸酱面
I have been thinking this for a long time, don’t let it be too cool, because it’s for Zhajiangmian

87
00:04:08,360 --> 00:04:10,280
拿碗
Bring the blow 

88
00:04:10,280 --> 00:04:12,120

89
00:04:12,120 --> 00:04:14,600
吃炸酱面给人挑面的时候要注意
You have to pay attention when you serve the noodles  

90
00:04:14,600 --> 00:04:16,440
别给挑一大碗面
Don’t put too much noodles

91
00:04:16,440 --> 00:04:19,280
你是让人家吃呢是让人家吃呢
So that the person can finish it 

92
00:04:19,280 --> 00:04:21,440
还是不让人吃
otherwise the person can’t finish

93
00:04:21,440 --> 00:04:24,280
就这么多
Like this is OK

94
00:04:24,280 --> 00:04:25,320
放面码也得讲究
And pay attention to the accompaniments

95
00:04:25,320 --> 00:04:28,720
颜色（胡萝卜） 黄瓜 豆芽
The color (carrot), cucumber, soy sprout

96
00:04:28,720 --> 00:04:35,360
小萝卜 圆白菜 青蒜 绿的
Reddish, napa cabbage, green garlic

97
00:04:35,360 --> 00:04:38,360
香椿往中间搁 隆重
Put xiangchun （Chinese Toon) in the middles, gorgeous !

98
00:04:38,360 --> 00:04:40,120
芹菜
Chinese celery

99
00:04:40,120 --> 00:04:43,240
再搁上酱
Then put the sauce

100
00:04:43,240 --> 00:04:45,080
咱该说什么来着
What should we say

101
00:04:45,080 --> 00:04:49,480
家有大厨 就是幸福
It’s great to have a chief at home

102
00:04:49,480 --> 00:04:52,160
现在还多了一句话呢
There’s another sentence now

103
00:04:52,160 --> 00:04:56,840
一起热爱 就现在
Share the passion, right now 

1
00:00:00,000 --> 00:00:05,005
有网友问 老北京传统炸酱面的面码都有什么
Some friends want to know, what are the accompaniments for Zhajiangmian

2
00:00:05,005 --> 00:00:06,840
其实最好吃的大白菜
In fact the best is the cabbage

3
00:00:07,240 --> 00:00:09,009
有芹菜 芹菜末
Chinese celery, chop it in small cube 

4
00:00:09,309 --> 00:00:11,044
有的有扁豆
Some use the hyacinth beans

5
00:00:11,044 --> 00:00:11,745
豆芽
Soy sprouts

6
00:00:12,379 --> 00:00:13,680
黄瓜
Cucumber

7
00:00:13,847 --> 00:00:14,914
冬天的心里美
Chinese roseheart radish 

8
00:00:14,914 --> 00:00:17,550
这季节呢 还可以搁点香椿
In this season, you can put some xiangchun

9
00:00:17,884 --> 00:00:19,986
春天可以搁点香椿
Yeah in sprint we put the xiangchun

10
00:00:20,120 --> 00:00:23,490
一半凑够八种面码就够了
Normally 8 accompaniments are enough

11
00:00:23,490 --> 00:00:25,492
这八种都是自己喜欢什么就加什么么
So the choice of these 8 accompaniments depends on yourself ?

12
00:00:25,492 --> 00:00:26,459
不是
No

13
00:00:26,459 --> 00:00:28,161
但是基本有一个定位
But there is a standard 

14
00:00:28,161 --> 00:00:33,566
你比如说像白菜啊 茄丝 黄瓜丝啊 芹菜啊
For example the cabbage, the sliced eggplant，the sliced cucumber and Chinese celery 

15
00:00:33,967 --> 00:00:36,603
芹菜切丁
Chop the celery in cube

16
00:00:36,603 --> 00:00:38,405
还有青蒜
And green garlic

17
00:00:38,405 --> 00:00:40,373
还有青豆
And green peas

18
00:00:40,373 --> 00:00:43,710
青豆嘴儿 绿豆嘴儿 黄豆芽
Green peas, green beans，soy sprouts

19
00:00:43,710 --> 00:00:45,845
二伯回答问题很全面 
Er Bai’s answer is very complete
