### ISSUE TITLE
[华农兄弟] 华农兄弟称一下狗子多重再看下兄弟养的兔子顺便泡一下温泉 - https://youtu.be/UHeeMS0TQD8

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1130]
https://youtu.be/UHeeMS0TQD8
<p>&#35270;&#39057;&#21457;&#24067;&#20110; June 6, 2020 at 11:41AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/UHeeMS0TQD8

#华农兄弟：称一下狗子多重，再看下兄弟养的兔子，顺便泡一下温泉
#Huanong Brothers: We weigh the doggies and have a look at our buddy's bunnies, then spend a few moments at the hot spring on the way home.

0:00:00.000,0:00:02.660
# 大家好  今天又下雨啦  天天下雨
Hi everyone! It rains again today. It rains everyday.

0:00:03.140,0:00:04.800
# 我秤一下那個狗  看一下多重啦
Let me weigh the dogs, and see how heavy they are.

0:00:05.200,0:00:06.080
# 我先秤一下我
I weigh myself first.

0:00:08.520,0:00:10.160
# 秤不對的 怎麼那麼重
Something's wrong? Why am I so heavy?

0:00:17.920,0:00:18.660
# 胖啦
I've put on weight.

0:00:19.400,0:00:21.100
# 你看  現在109啦
Look! I'm now 109.
(Note: The unit is "jin, where 1 "jin" = 500 grams)

0:00:21.100,0:00:21.760
# (沒字幕)
(Note: The unit is "jin, where 1 "jin" = 500 grams)

0:00:21.760,0:00:22.600
# 公斤秤
The reading is in kilograms.
(Note: The unit is "jin, where 1 "jin" = 500 grams)

0:00:24.160,0:00:28.080
# 我來秤一下這個  這個  這個鬆獅一樣的
Let me weigh this one, which, which looks like a Chow Chow.

0:00:29.000,0:00:31.520
# 大胖狗過來  稱一下你多重啦
Big chubby dog. Let me see how heavy you are.

0:00:32.640,0:00:34.900
# 哎呀  那麼重它
Aya! He's so heavy!

0:00:35.600,0:00:38.300
# 70 71
70, 71

0:00:38.760,0:00:40.020
# 71公斤
71 kilograms.

0:00:42.640,0:00:44.080
# 108 71
108, 71...

0:00:55.520,0:00:58.820
# 計算機多快呀  108減71
How convenient a calculator is. 108 minus 71

0:00:59.660,0:01:00.340
# 不是哦
Ah, no!

0:01:01.000,0:01:01.800
# 錯啦
I got it wrong.

0:01:02.280,0:01:06.160
# 71乘以2等於142減108
71 times 2 is 142, minus 108...

0:01:07.840,0:01:09.080
# 誒 34斤
Eh? 34 "jin"

0:01:11.600,0:01:12.440
# 看一下小黑
Let's see Blacky.

0:01:13.240,0:01:16.220
# 小黑 小黑  小黑我秤一下你啊
Blacky, Blacky, I'm gonna weigh you.

0:01:17.180,0:01:17.680
# 來
C'mon!

0:01:19.160,0:01:20.960
# 哎呀  好重
Aya! Heavy!

0:01:24.000,0:01:25.940
# 76 76斤
76, 76 "jin"

0:01:27.500,0:01:28.480
# 76斤   (註︰這裡他說錯了，是76公斤，不過我不為他澄清了)
76 "jin"

0:01:29.720,0:01:30.300
# 哎喲
Ayo!

0:01:33.520,0:01:35.360
# 76乘以2
76 times 2

0:01:36.720,0:01:39.220
# 152減去108
152 minus 108

0:01:40.180,0:01:41.080
# 44斤
44 "jin"

0:01:42.280,0:01:42.840
# 你看
Look!

0:01:43.540,0:01:44.800
# 它那麼小就那麼重
He's so small, but is already that heavy.

0:01:48.800,0:01:50.020
# 小黑它都懷孕啦
Blacky is now pregnant.

0:01:53.000,0:01:54.180
# 這大母狗也壞孕啦
This big mom is also pregnant.

0:01:54.720,0:01:56.860
# 這大母狗就不秤它啦  肚子那麼大
I'm not gonna weigh the big mom. Her belly is so big now.

0:01:57.960,0:01:59.040
# 嘿 秤一下你的
Hey! Let me weigh you.

0:02:01.200,0:02:02.000
# 嘿喲
Heyo!

0:02:05.860,0:02:06.980
# 最不聽話的那條
He's the naughtiest!

0:02:07.620,0:02:08.260
# 跑啦
Gone!

0:02:10.560,0:02:11.280
# 秤一下這條
Let me weigh this one.

0:02:13.020,0:02:13.960
# 跑那麼快
She runs so fast!

0:02:15.300,0:02:18.340
# 秤一下你  你看  今天  今天跑去淋雨啦
Let me wiegh you. Look! Today, today she went into the rain.

0:02:22.040,0:02:22.880
# 1斤7兩
1.7

0:02:23.820,0:02:25.580
# 公斤3斤4兩
in kilograms, so 3.4 "jin"

0:02:26.440,0:02:27.780
# 可以喲  跟竹鼠那麼大
No bad. She's as big as a bamboo rat.

0:02:31.820,0:02:33.860
# 你看  本來很白的這個
Look! She should be very white, this puppy.

0:02:34.200,0:02:37.000
# 你看  跑出外面去淋一下雨  又粘了一點泥土回來
Look! She ran outside and went into the rain. Then some mud has stuck on her.

0:02:38.500,0:02:39.280
# 就這樣子啦
And she's so dirty now.

0:02:42.700,0:02:43.640
# 你看  給你
Look! Take her,

0:02:44.380,0:02:45.000
# 一起玩
and have fun with her.

0:02:48.840,0:02:49.540
# 還有一條呢
Where's the last one?

0:02:50.380,0:02:51.300
# 把它摞出來
I'm gonna draw her out.

0:02:54.960,0:02:57.700
# 這條  這條應該最瘦  最小
This one, this one should be the skinniest, and the smallest.

0:02:58.460,0:02:59.340
# 又瘦又小
Skinny and small

0:03:00.460,0:03:02.200
# 1斤7兩哦 跟那個一樣的
1.7, the same as that one.

0:03:02.820,0:03:03.720
# 看上去那麼大
She looks so big.

0:03:04.580,0:03:05.600
# 體重都是一樣的
But there's no difference in the weights,

0:03:06.320,0:03:07.320
# 跟它一樣小
as small as her.

0:03:09.120,0:03:10.400
# 我怎麼那麼重
How did I become so heavy?

0:03:15.540,0:03:18.520
# 一百  零八
A hundred, and, eight

0:03:19.040,0:03:20.100
# 斤2兩
point two "jin"

0:03:22.320,0:03:23.680
# 還有一條大公狗不知道跑哪裡去啦
There's one big boy. But he's gone to who-knows-somewhere.

0:03:23.680,0:03:24.780
# 它那條是最壯的
He's the most bulky one.

0:03:25.340,0:03:26.080
# 抓不到它
I can't catch him.

0:03:26.620,0:03:27.360
# 下次來秤
I'll weigh him next time.

0:03:28.780,0:03:31.340
# 兄弟家還養了幾隻兔子  我們去看一下
My buddy is keeping some bunnies at his place. Let's go and have a look.

0:03:31.660,0:03:32.740
# 他家兔子很靚的
His bunnies are really beautiful.

0:03:33.440,0:03:34.880
# 這個是兄弟家的秤
This is my buddy's balace.

0:03:35.040,0:03:36.160
# 給它還回去
Let me return it to him.

0:03:41.260,0:03:43.200
# 算啦  不還啦  放到這裡來
Forget it. I'm not returning it. Let me keep it here.

0:03:43.500,0:03:44.240
# 下次來還
I'll return it next time.

0:04:16.060,0:04:17.660
# 你看  這個小兔子
Look! This little bunny

0:04:21.640,0:04:23.400
# 吃飽了哈  肚子那麼大
It has eaten a lot. Its belly is so big.

0:04:24.360,0:04:25.020
# 哎喲
Ayo!

0:04:26.020,0:04:28.580
# 這裡 這裡也有 這裡一個誒
Here, here too, here's one, eh!

0:04:29.360,0:04:30.120
# 這個黑的
This one is black,

0:04:31.380,0:04:32.780
# 黑的小兔子  看到沒
a black bunny, see?

0:04:34.060,0:04:35.620
# 好可愛啊  肚子好大
It's lovely! The belly is so big.

0:04:36.440,0:04:37.020
# 還小
It's still small.

0:04:37.340,0:04:39.540
# 這個灰的  這個灰的最可愛
This grey one, this grey one is the loveliest.

0:04:42.520,0:04:44.460
# 這個灰兔子看到沒  哦
It's a grey bunny, see? Oh!

0:04:45.640,0:04:46.500
# 中間還有
There's a bunch of hair,

0:04:46.980,0:04:47.820
# 一坨毛
in the middle,

0:04:49.020,0:04:49.580
# 白的
and is white.

0:04:50.820,0:04:52.800
# 哎喲  爪人的
Ayo! It scratched me!

0:04:53.760,0:04:54.540
# 哎喲
Ayo!

0:04:55.700,0:04:56.780
# 打扁你去
I beat you hard!

0:04:58.240,0:05:00.220
# 這個兔就像我們以前那個兔子
The bunny looks like the one that used to be with us.

0:05:02.760,0:05:04.140
# 好靚哦  這個兔子  你看
It's so beautiful, this bunny. Look!

0:05:05.300,0:05:05.960
# 有點像
It's a bit like,

0:05:06.880,0:05:08.280
# 有點像我以前那個兔子
looks a bit like the bunny that used to be with me.

0:05:10.980,0:05:12.000
# 它會吃稻草
They eat straw.

0:05:12.660,0:05:15.300
# 再加點這個  香蕉葉  香蕉葉給它們吃
Let me give them some, you know, banana leaves, some banana leaves as well.

0:05:16.160,0:05:17.900
# 它們很喜歡吃香蕉葉的哦
They love banana leaves, you know.

0:05:20.400,0:05:21.080
# 小兔子
Little bunnies!

0:05:21.660,0:05:22.360
# 小兔子
Little bunnies!

0:05:23.080,0:05:24.040
# 去不去我家玩
You wanna go home with me?

0:05:24.480,0:05:25.400
# 要不要去面玩
You wanna have fun upstairs?

0:05:25.880,0:05:26.520
# 去不去
Do you?

0:05:32.160,0:05:33.380
# 好害羞啊 它們
They're very shy.

0:05:33.420,0:05:34.420
# 你看  這隻
Look! This one,

0:05:35.580,0:05:36.400
# 小兔子
this little bunny

0:05:39.080,0:05:40.480
# 好可愛呀  這些
They're really lovely.

0:05:42.080,0:05:44.700
# 它這個是寵物兔來的哦  長不大的
They're pet bunnies and they won't get big.

0:05:45.340,0:05:46.380
# 就那麼小一點
They're always that tiny.

0:05:49.120,0:05:51.760
# 天天給它葉葉子給它吃  你看  吃這個香蕉葉
They're given veggie leaves every day. Look! They're eating the banana leaves.

0:05:51.880,0:05:54.000
# 這邊都還藏了幾個哦  看到沒
A few more are hiding here, see?

0:05:56.600,0:05:57.840
# 躲到這裡來吃
They're having their meal, hiding here.

0:06:00.180,0:06:01.560
# 害羞  是不是
Shy, aren't you?

0:06:03.140,0:06:04.380
# 你看  這個就像
Look! This one is like,

0:06:05.180,0:06:06.780
# 這就像  那個甚麼
it's like, I mean, you know,

0:06:07.560,0:06:08.640
# 現偶一樣的
like a doll.

0:06:09.580,0:06:10.760
# 你看  這個兔子
Look! This bunny,

0:06:11.140,0:06:12.220
# 它都紅眼哦
its eyes have turned red.

0:06:16.640,0:06:20.860
# 它現在肚子餓啦  想吃菜葉子 這個香蕉葉來的
Now they're hungry and want some veggie leaves. These are banana leaves.

0:06:21.580,0:06:23.280
# 特意搞了點香蕉葉給它吃
I've fetched some banana leaves, exclusively for them.

0:06:24.300,0:06:26.140
# 一摸它它就不動啦  是啊
It's like a statue once a pet it, yea.

0:06:28.100,0:06:29.200
# 很乖的哦  這個
It's a good bunny, this one.

0:06:30.180,0:06:30.880
# 繼續吃
Go on eating!

0:06:32.860,0:06:34.340
# 呵呵  動都不敢動
Ho ho! It dares not move an inch.

0:06:35.140,0:06:36.080
# 不要怕啊
Fear not!

0:06:42.480,0:06:43.500
# 這灰兔子
This grey bunny,

0:06:48.940,0:06:51.420
# 這沒尾巴  它尾巴那麼一點點
it doesn't have a tail. Its tail is just a tiny little bit here.

0:06:53.620,0:06:57.220
# 我一動它  它就躺著那裡 享受是不是
Once I pet it, it lies here and is, enjoying, isn't it?

0:06:59.780,0:07:00.940
# 不敢動是不是
You dare not move, right?

0:07:05.560,0:07:08.100
# 這個兔子要蓋起來啊 不蓋起來它要
The bunnies need to be covered up. Otherwise, they're gonna,

0:07:09.040,0:07:09.880
# 它要跑
gonna run away.

0:07:13.460,0:07:14.500
# 它會跳走
They can jump out from the cell.

0:07:20.740,0:07:22.360
# 好啦  看一下那個溫泉
Look! Let's have a look at the hot spring.

0:07:22.880,0:07:25.400
# 現在下雨應該很乾淨  去那泡一下腳
It's raining now so it must be very clean there. Let me soak my feet.

0:07:29.340,0:07:31.680
# 這兩隻都是以前那個母狗生的
These two dogs are children of the big mom.

0:07:32.380,0:07:34.960
# 你看 現在都玩沙子它
Look! He's now playing with the sand.

0:07:35.540,0:07:38.400
# 來 給你小石頭給你  哈哈哈  好吃的
C'mon! I give you a small rock! Ha ha ha! It's tasty.

0:07:56.640,0:07:59.880
# 你看  這個溫泉 天氣熱都沒人泡  這裡
Look! This hot spring, it's hot and so nobody's here now.

0:08:04.400,0:08:05.080
# 泡一下腳
Let me soak my feet.

0:08:05.640,0:08:06.320
# 太熱啦
It's too hot.

0:08:11.860,0:08:13.000
# 哎喲
Ayo!

0:08:22.280,0:08:25.160
# 這個天氣隨便一泡下就上來
With this weather, a second or two is already enough.

0:08:32.280,0:08:32.920
# 好啦
Alright!

0:08:33.460,0:08:34.280
# 泡好啦
Enough!

0:08:35.480,0:08:37.500
# 泡一下就很燙啦
Just a second and it's already boiling.

0:08:50.260,0:08:51.920
# 這個時候不適合泡
It's not a good season for hot spring.

0:08:52.680,0:08:53.560
# 太熱啦
It's too hot.

0:08:59.840,0:09:01.060
# 冬天的時候就爽
It's really nice in winter.

0:09:01.300,0:09:02.540
# 冬天的時候泡在這裡
Soaking in the hot spring in winter,

0:09:03.120,0:09:03.980
# 多暖和哇
it's so warm!
