### ISSUE TITLE
【美食作家王刚】懒人卤料包的使用 - https://youtu.be/OoBVeeYpYl8

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1132]
**视频链接**：https://youtu.be/OoBVeeYpYl8

视频时长7:43，预计发布时间为北京时间6月8日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“懒人卤料包”使用方法，只需加水就能轻松卤制美味（买不到料包的朋友不好意思，评论中附上不用料包做卤味的链接）

简介
大家好，今天和大家分享一个我最新研制的一款“懒人卤料包”，来解决一些喜欢吃卤味又没办法买到所有香料的朋友，其中用到的香料有：草果，香果，肉桂，丁香，小茴，香叶，碧波，白纸，木香，灵香草，排草，红曲米，辣椒，花椒，三奈，八角，枝子，红扣等。并且还加入了井盐冰糖酱油等调味料，做卤味的时候只需要一包即可，不需要再添加其他的味道。其中颜色是通过红曲米，冰糖，和部分香料出色，属于天然着色剂，大家大可放心使用。并且千万不要用一次就丢掉，将卤水自然放凉之后放入冰箱可以重复使用多次。

买不到料包的朋友不好意思，在这里附上我之前做过的卤味视频链接，这些都是比较简单家常的做法，香料较少比较容易买齐，大家可以用来做参考：
卤猪头 https://www.youtube.com/watch?v=FrCJM_WC6VI
卤水肥肠 https://www.youtube.com/watch?v=gy7NZ8lQQM8&t=27s
麻辣卤鸭三宝 https://www.youtube.com/watch?v=hSldGpK0Cck

字幕
0:00:00.482,0:00:01.130
哈喽 大家好

0:00:01.404,0:00:05.792
今天我让我伯爷留了2根猪后脚回来卤

0:00:06.330,0:00:08.041
这个猪脚杆有好重安

0:00:09.007,0:00:10.883
五斤多6斤的样子

0:00:12.495,0:00:14.777
这个我伯爷已经把它烧了 烧了也洗干净了

0:00:14.832,0:00:16.719
本来是说他要拿去卖掉的

0:00:16.785,0:00:18.606
你不打电话我都卖了

0:00:18.815,0:00:21.097
你把这个勾哈嘛  你来

0:00:23.159,0:00:23.488
诶呀

0:00:24.640,0:00:26.330
你不专业的话你还勾不掉

0:00:27.065,0:00:30.400
嗯 这是我伯爷的专业

0:00:34.701,0:00:35.271
慢点哦

0:00:35.754,0:00:39.824
不关事 这个刀未必还难得到我呀

0:00:43.664,0:00:44.410
划断吗

0:00:45.189,0:00:46.659
嗯 划断嘛划断

0:00:48.612,0:00:49.040
好  

0:00:49.171,0:00:49.588
可以了

0:00:50.663,0:00:53.571
这个猪脚没有抽筋噶

0:00:53.713,0:00:55.787
没有抽筋这不是那根大筋呀

0:00:55.918,0:00:58.387
这个筋在这里 这个筋大家看一下

0:00:59.111,0:00:59.626
扯得出来不

0:01:00.241,0:01:02.249
扯得出来 好生点划到手

0:01:02.336,0:01:04.278
这个筋像那个葱白一样

0:01:04.421,0:01:06.911
像葱一样 是不是跟葱葱一样

0:01:06.977,0:01:07.515
嗯

0:01:08.381,0:01:10.839
今天这是用我们自己这个卤料来

0:01:11.826,0:01:14.843
我们这个卤料直接卤就行了

0:01:16.357,0:01:20.252
一包卤料的话加三斤这个东西（食材）

0:01:20.252,0:01:24.300
所以我们6斤多的猪脚弄2包

0:01:24.498,0:01:25.364
刚好差不多

0:01:27.032,0:01:30.268
有很多粉丝之前在问这个卤料包买回去怎么用

0:01:30.718,0:01:32.517
现在这一期视频就跟大家分享

0:01:33.373,0:01:36.401
我们打开了这个之后要检查一下这个线这里

0:01:36.873,0:01:38.683
不要让它流出来

0:01:39.561,0:01:40.493
然后给它放好

0:01:42.227,0:01:42.841
吃得辣不

0:01:43.763,0:01:46.396
这天气大了就少整点海椒撒

0:01:46.428,0:01:47.811
这个海椒不是很辣

0:01:48.326,0:01:49.533
不是很辣 那就可以

0:01:50.170,0:01:51.113
我们把它倒进去

0:01:52.704,0:01:53.033
好

0:01:53.691,0:01:56.577
然后这个卤料包拆出来把辣椒这些倒出来

0:01:56.950,0:01:57.838
就放到一起

0:01:59.056,0:02:00.021
切点姜片

0:02:01.272,0:02:03.379
切长一点 2根葱就可以了

0:02:04.904,0:02:06.867
然后就差不多了就可以用了

0:02:07.087,0:02:12.331
然后我们卤这个东西的时候就只要加这个就行了

0:02:12.353,0:02:13.230
盐都不用放

0:02:13.647,0:02:15.589
然后一包卤料放4斤水

0:02:16.324,0:02:18.771
2包的话就放8斤水

0:02:19.078,0:02:21.349
然后慢慢地去卤这个猪脚

0:02:22.676,0:02:23.982
来嘛 四伯爷帮我端嘛

0:02:25.057,0:02:28.612
好 卤之前先把猪脚焯下水

0:02:31.431,0:02:33.187
把这个猪脚冷水下锅焯水

0:02:40.877,0:02:43.587
你看 这个全是血沫

0:03:07.558,0:03:09.544
我们这个姜葱油炒香了之后

0:03:09.687,0:03:11.102
把姜葱炒香了开始放水

0:03:11.442,0:03:14.371
水的话大概放个8斤多都可以

0:03:14.865,0:03:16.050
8斤9斤都可以

0:03:17.531,0:03:18.815
因为这个要卤很久

0:03:18.902,0:03:21.993
所以如果放9斤的话就可以弥补一下

0:03:22.238,0:03:24.914
等下煮的时候蒸发的水份

0:03:26.450,0:03:27.766
好 可以放水了

0:03:35.922,0:03:40.481
我们先把猪脚放下去 放上这个水漫过这个猪脚

0:03:40.945,0:03:42.020
好 差不多了

0:03:42.632,0:03:45.134
然后再把我们的这个卤料包放下去

0:03:48.063,0:03:48.767
辣椒

0:03:49.342,0:03:53.438
我们这个卤料包里面盐还有颜色都是配好的

0:03:53.438,0:03:55.848
大家可以看一下这个出来的颜色

0:03:58.943,0:04:00.500
然后我们这个烧开了之后

0:04:00.500,0:04:03.206
就开小火慢慢卤它40分钟

0:04:03.577,0:04:05.709
卤40分钟就可以拿出来吃了

0:04:05.875,0:04:08.519
这中间不有加盐不用加糖

0:04:08.526,0:04:09.786
什么都不用加

0:04:09.935,0:04:12.789
就只要水和姜葱 加点油

0:04:13.271,0:04:15.662
然后就可以放原材料下去卤了

0:04:15.792,0:04:18.740
然后卤味这个烧开了之后 卤水烧开之后

0:04:18.758,0:04:21.797
也要打一下这个血沫

0:04:26.506,0:04:28.971
这个可以卤鸡鸭

0:04:29.972,0:04:31.084
所有东西都可以卤

0:04:31.121,0:04:36.451
可以卤牛肉 卤猪 卤鸡鸭兔都可以卤

0:04:36.451,0:04:38.245
只要你想得出来卤的都可以丢下去卤

0:04:40.283,0:04:41.261
这个颜色都出来了

0:04:42.627,0:04:46.265
好了 我们这个已经卤了40分钟

0:04:46.265,0:04:48.706
然后小火卤了40分钟

0:04:49.498,0:04:51.746
刚才已经泡了大概20分钟了

0:04:51.746,0:04:56.014
现在我把它重新烧开了就可以捞出来了这个猪脚

0:04:58.302,0:05:02.716
大家可以看一下这个颜色 颜色非常的漂亮

0:05:03.249,0:05:03.508
诶呀

0:05:07.817,0:05:11.018
然后剩下的卤水我们把它的渣全部捞干净

0:05:12.823,0:05:15.329
然后凉了之后可以放到冰箱里面

0:05:15.739,0:05:17.494
下一次又可以卤

0:05:18.359,0:05:21.382
可以反复卤个两三次没问题这个卤水

0:05:23.144,0:05:23.937
好 关火

0:05:24.333,0:05:26.103
好了 现在我们来试一下

0:05:26.362,0:05:29.789
用刀割点下来尝一下味道怎么样

0:05:30.727,0:05:32.910
我给你割一坨肥一点哈四伯爷

0:05:33.209,0:05:36.289
要得啊 小坨点 割大坨了

0:05:38.714,0:05:40.274
来嘛 这里有碗

0:05:41.172,0:05:43.080
 我来给你割你尝哈看

0:05:48.326,0:05:49.660
嗯 卤耙了

0:05:50.218,0:05:50.760
耙了是不

0:05:50.760,0:05:51.164
嗯

0:05:55.780,0:06:00.117
我们这个所有的卤味啊卤出来了之后

0:06:00.125,0:06:03.120
家庭操作的卤味拿出来了之后

0:06:03.644,0:06:05.204
它会受到氧化

0:06:05.623,0:06:07.335
然后颜色会变得深一些

0:06:07.592,0:06:09.809
如果你炒糖色掌握得不好的话

0:06:10.437,0:06:12.131
用糖色卤出来一会儿就会

0:06:12.131,0:06:13.672
你这个大了我来割

0:06:14.329,0:06:14.995
你来割啊 来嘛

0:06:15.699,0:06:17.602
我来割坨小点的

0:06:19.495,0:06:20.466
就用手抓着吃

0:06:20.961,0:06:23.815
如果我们家庭里面炒糖色的

0:06:23.891,0:06:28.515
控制不好糖色的成色 卤出来一会就要黑这个

0:06:29.562,0:06:30.456
黑了也很正常

0:06:30.780,0:06:32.169
来嘛 你吃这个蹄筋嘛

0:06:32.949,0:06:33.549
蹄筋呀这个是

0:06:33.663,0:06:34.957
那不是蹄筋咋子

0:06:36.403,0:06:37.374
又脆有香

0:06:39.305,0:06:40.494
真的是很脆

0:06:40.494,0:06:43.263
是啊 那个蹄筋安逸得很

0:06:45.119,0:06:46.194
这个皮子还多安逸

0:06:46.869,0:06:47.278
是不

0:06:47.412,0:06:47.783
 是啊

0:06:52.740,0:06:54.177
这个皮子很香

0:06:56.327,0:06:59.505
我们这个卤料包你看是像这个样子的

0:07:00.523,0:07:04.386
卤了之后把它捞出来放凉了之后放到冰箱里面

0:07:04.633,0:07:05.908
第二次可以接着卤

0:07:07.792,0:07:09.924
你看这个水 里面的这个香料都还多香

0:07:09.924,0:07:11.008
还可以卤一两次

0:07:13.349,0:07:15.657
 就是跟它整那个懒人排骨差不多嘎

0:07:15.657,0:07:16.418
哦喔有点像

0:07:16.478,0:07:20.013
拿这个袋子放在里面

0:07:20.270,0:07:22.031
这些放在里面就可以卤了

0:07:22.691,0:07:24.287
这个效果的话其实还（不错）

0:07:24.287,0:07:25.534
效果还是很好

0:07:25.640,0:07:26.609
效果还是不错

0:07:27.645,0:07:29.122
好了 本期视频就到这里

0:07:29.314,0:07:30.396
这个很方便的

0:07:30.455,0:07:33.516
跟大家推荐这个懒人卤料

0:07:35.105,0:07:37.256
懒人卤料 硬是懒人卤料

0:07:38.021,0:07:39.452
好啦 就到这里了 拜拜

0:07:39.630,0:07:40.488
好方便嘛


```

**Comment by immoonancient** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“懒人卤料包”使用方法，只需加水就能轻松卤制美味（买不到料包的朋友不好意思，评论中附上不用料包做卤味的链接）
Chef Wang shares: "Lazy Man's Master Stock Bag", braise delicious food with ease

简介
大家好，今天和大家分享一个我最新研制的一款“懒人卤料包”，来解决一些喜欢吃卤味又没办法买到所有香料的朋友，其中用到的香料有：草果，香果，肉桂，丁香，小茴，香叶，碧波，白纸，木香，灵香草，排草，红曲米，辣椒，花椒，三奈，八角，枝子，红扣等。并且还加入了井盐冰糖酱油等调味料，做卤味的时候只需要一包即可，不需要再添加其他的味道。其中颜色是通过红曲米，冰糖，和部分香料出色，属于天然着色剂，大家大可放心使用。并且千万不要用一次就丢掉，将卤水自然放凉之后放入冰箱可以重复使用多次。
Hello everyone, today I'm gonna share my new product, "Lazy Man's Master Stock Bag", to help our friends who love braised food but find it hard to buy all the spices. Spices included: taso-ko, sichuan lovage fruits, cinnamon, cloves, fennel seeds, bay leaves, long pepper, baizhi, Lady Banks' rose roots, lingxiangcao, paicao, red yeast rice, chili peppers, sichuan peppercorns, sand gingers, star anise, zhizi, hongkou and etc. We also added condiment like salt, white rock sugar, soy sauce and etc, so that we can just cooking with the bag without adding any other condiment. The coloring is given by red yeast rice, rock sugar and other spices, which is natural and safe. And don't throw it away after using, it can be refregerated and reused for a few times.

译者注：香料名称翻译我尽力了...

买不到料包的朋友不好意思，在这里附上我之前做过的卤味视频链接，这些都是比较简单家常的做法，香料较少比较容易买齐，大家可以用来做参考：
卤猪头 https://www.youtube.com/watch?v=FrCJM_WC6VI
卤水肥肠 https://www.youtube.com/watch?v=gy7NZ8lQQM8&t=27s
麻辣卤鸭三宝 https://www.youtube.com/watch?v=hSldGpK0Cck
My apologies to those who can't buy it. Below are my previous braised food video, which are all in simple and homestyle recipes, and do not use too many kinds of spices. Please use them as references:
- Pork head: https://www.youtube.com/watch?v=FrCJM_WC6VI
- Pork intestine: https://www.youtube.com/watch?v=gy7NZ8lQQM8&t=27s
- Spicy duck head, feet and wings: https://www.youtube.com/watch?v=hSldGpK0Cck

译者注：四伯的对话我尝试故意用一些常见的不正式拼写、句法，请检查是否观感良好

字幕
0:00:00.482,0:00:01.130
哈喽 大家好
Hello everyone

0:00:01.404,0:00:05.792
今天我让我伯爷留了2根猪后脚回来卤
Today, I asked my uncle to leave me two pork hind legs for braising

0:00:06.330,0:00:08.041
这个猪脚杆有好重安
How heavy are these pork legs?

0:00:09.007,0:00:10.883
五斤多6斤的样子
More than 5 jin, about 6 jin-ish (1 jin = 500 grams)

0:00:12.495,0:00:14.777
这个我伯爷已经把它烧了 烧了也洗干净了
Uncle has already burned it. Burned it and cleaned it

0:00:14.832,0:00:16.719
本来是说他要拿去卖掉的
He was supposed to sell them

0:00:16.785,0:00:18.606
你不打电话我都卖了
They're sold if you didn't call me

0:00:18.815,0:00:21.097
你把这个勾哈嘛  你来
Could you hook it away?

0:00:23.159,0:00:23.488
诶呀
Eh-ya

0:00:24.640,0:00:26.330
你不专业的话你还勾不掉
You can't hook it away if you ain't professional

0:00:27.065,0:00:30.400
嗯 这是我伯爷的专业
Yeah, that's my uncle's professionalism

0:00:34.701,0:00:35.271
慢点哦
Careful

0:00:35.754,0:00:39.824
不关事 这个刀未必还难得到我呀
Doesn't matter. Dis knife ain't a problem

0:00:43.664,0:00:44.410
划断吗
Cut it through?

0:00:45.189,0:00:46.659
嗯 划断嘛划断
Hmm, cut it through

0:00:48.612,0:00:49.040
好
Alright

0:00:49.171,0:00:49.588
可以了
Good

0:00:50.663,0:00:53.571
这个猪脚没有抽筋噶
We haven't remove the trotter tendon?

0:00:53.713,0:00:55.787
没有抽筋这不是那根大筋呀
Nope. Ain't dat da big tendon?

0:00:55.918,0:00:58.387
这个筋在这里 这个筋大家看一下
This is the tendon. Let's take a look

0:00:59.111,0:00:59.626
扯得出来不
Can we pull it out?

0:01:00.241,0:01:02.249
扯得出来 好生点划到手
Pull it out. Be careful, don't hurt your hand

0:01:02.336,0:01:04.278
这个筋像那个葱白一样
The tondon is like a scallion white

0:01:04.421,0:01:06.911
像葱一样 是不是跟葱葱一样
Like a scallion... Isn't it like a scallion?

0:01:06.977,0:01:07.515
嗯
Hmm

0:01:08.381,0:01:10.839
今天这是用我们自己这个卤料来
Today, we're gonna use our master stock bag

0:01:11.826,0:01:14.843
我们这个卤料直接卤就行了
We can stew directly with it

0:01:16.357,0:01:20.252
一包卤料的话加三斤这个东西（食材）
One master stock bag is good for cooking 3 jin (of ingredients)

0:01:20.252,0:01:24.300
所以我们6斤多的猪脚弄2包
So for 6 jin of trotters, we use 2 bags

0:01:24.498,0:01:25.364
刚好差不多
Dat's about right

0:01:27.032,0:01:30.268
有很多粉丝之前在问这个卤料包买回去怎么用
Many followers bought this bag, and asked how to use it

0:01:30.718,0:01:32.517
现在这一期视频就跟大家分享
So we're gonna share it in this video

0:01:33.373,0:01:36.401
我们打开了这个之后要检查一下这个线这里
After opening, we need to check the thread here

0:01:36.873,0:01:38.683
不要让它流出来
Don't let it go out

0:01:39.561,0:01:40.493
然后给它放好
Then set them aside

0:01:42.227,0:01:42.841
吃得辣不
Can you eat spicy?

0:01:43.763,0:01:46.396
这天气大了就少整点海椒撒
Da weather is hot, less chili

0:01:46.428,0:01:47.811
这个海椒不是很辣
These chili peppers are not too chili

0:01:48.326,0:01:49.533
不是很辣 那就可以
Not too chili? Good

0:01:50.170,0:01:51.113
我们把它倒进去
Let's pour it in

0:01:52.704,0:01:53.033
好
Alright

0:01:53.691,0:01:56.577
然后这个卤料包拆出来把辣椒这些倒出来
So we open the package, and pour out the chili

0:01:56.950,0:01:57.838
就放到一起
And put them together

0:01:59.056,0:02:00.021
切点姜片
Chop some ginger

0:02:01.272,0:02:03.379
切长一点 2根葱就可以了
Chop longer chunks. Two scallions are enough

0:02:04.904,0:02:06.867
然后就差不多了就可以用了
Then it's enough. Good to go

0:02:07.087,0:02:12.331
然后我们卤这个东西的时候就只要加这个就行了
Later when we braise, we just need to add this

0:02:12.353,0:02:13.230
盐都不用放
No salt is needed

0:02:13.647,0:02:15.589
然后一包卤料放4斤水
And for each bag, we add 4 jin of water

0:02:16.324,0:02:18.771
2包的话就放8斤水
For two bag, 8 jin of water

0:02:19.078,0:02:21.349
然后慢慢地去卤这个猪脚
And then simmer the trotters

0:02:22.676,0:02:23.982
来嘛 四伯爷帮我端嘛
Come on. Help me take it, uncle

0:02:25.057,0:02:28.612
好 卤之前先把猪脚焯下水
Alright. Before braising, we need to parboil the trotters

0:02:31.431,0:02:33.187
把这个猪脚冷水下锅焯水
Parboil the trotters in cold water

0:02:40.877,0:02:43.587
你看 这个全是血沫
Look, it's full of blood scum

0:03:07.558,0:03:09.544
我们这个姜葱油炒香了之后
Now we've make the ginger and scallion oil aromatic

0:03:09.687,0:03:11.102
把姜葱炒香了开始放水
Add water after it's aromatic

0:03:11.442,0:03:14.371
水的话大概放个8斤多都可以
We add about 8 jin of water

0:03:14.865,0:03:16.050
8斤9斤都可以
8 jin or even 9, doesn't matter

0:03:17.531,0:03:18.815
因为这个要卤很久
Because it takes a long time to cook

0:03:18.902,0:03:21.993
所以如果放9斤的话就可以弥补一下
If we add 9 jin, it's going to compensates

0:03:22.238,0:03:24.914
等下煮的时候蒸发的水份
the water vaporized during cooking

0:03:26.450,0:03:27.766
好 可以放水了
Alright, water in

0:03:35.922,0:03:40.481
我们先把猪脚放下去 放上这个水漫过这个猪脚
We put in the trotters, and add water to cover them

0:03:40.945,0:03:42.020
好 差不多了
Alright, good

0:03:42.632,0:03:45.134
然后再把我们的这个卤料包放下去
Then we put in the master stock bags

0:03:48.063,0:03:48.767
辣椒
Chili pepper

0:03:49.342,0:03:53.438
我们这个卤料包里面盐还有颜色都是配好的
We have salt and coloring in the bag. Everything well prepared

0:03:53.438,0:03:55.848
大家可以看一下这个出来的颜色
We can take a look at the color it gives

0:03:58.943,0:04:00.500
然后我们这个烧开了之后
And after it's brought to a boil

0:04:00.500,0:04:03.206
就开小火慢慢卤它40分钟
We simmer it for 40 minutes

0:04:03.577,0:04:05.709
卤40分钟就可以拿出来吃了
Simmer for 40 minutes, then it's good to serve

0:04:05.875,0:04:08.519
这中间不有加盐不用加糖
No salt, no sugar added while cooking

0:04:08.526,0:04:09.786
什么都不用加
Nothing to add

0:04:09.935,0:04:12.789
就只要水和姜葱 加点油
other than water, ginger, scallion and some oil

0:04:13.271,0:04:15.662
然后就可以放原材料下去卤了
Then we can put in the ingredients to braise

0:04:15.792,0:04:18.740
然后卤味这个烧开了之后 卤水烧开之后
After the stock is boiling,

0:04:18.758,0:04:21.797
也要打一下这个血沫
skim off the blood scum again

0:04:26.506,0:04:28.971
这个可以卤鸡鸭
Dis works for chicken, duck

0:04:29.972,0:04:31.084
所有东西都可以卤
Works for everything

0:04:31.121,0:04:36.451
可以卤牛肉 卤猪 卤鸡鸭兔都可以卤
Works for beef, pork, chicken, duck, rabbit, everything

0:04:36.451,0:04:38.245
只要你想得出来卤的都可以丢下去卤
Everything you can think of, dump it in and braise

0:04:40.283,0:04:41.261
这个颜色都出来了
We've brought out the color

0:04:42.627,0:04:46.265
好了 我们这个已经卤了40分钟
Alright, we've cooked for 40 minutes

0:04:46.265,0:04:48.706
然后小火卤了40分钟
Simmered for 40 minutes

0:04:49.498,0:04:51.746
刚才已经泡了大概20分钟了
And soaked for about 20 minutes

0:04:51.746,0:04:56.014
现在我把它重新烧开了就可以捞出来了这个猪脚
Now I'm gonna re-boil it, then we can take out the trotters

0:04:58.302,0:05:02.716
大家可以看一下这个颜色 颜色非常的漂亮
Let's take a look at the color, which is very pretty

0:05:03.249,0:05:03.508
诶呀
Eh-ya

0:05:07.817,0:05:11.018
然后剩下的卤水我们把它的渣全部捞干净
And then we scoop out all the residue in the master stock

0:05:12.823,0:05:15.329
然后凉了之后可以放到冰箱里面
After it cools down, we can store it refrigerated

0:05:15.739,0:05:17.494
下一次又可以卤
And use it next time

0:05:18.359,0:05:21.382
可以反复卤个两三次没问题这个卤水
The master stock can be reused for a couple of times

0:05:23.144,0:05:23.937
好 关火
Alright, fire off

0:05:24.333,0:05:26.103
好了 现在我们来试一下
Alright, now let's have a try

0:05:26.362,0:05:29.789
用刀割点下来尝一下味道怎么样
Slice a bit and see how it tastes

0:05:30.727,0:05:32.910
我给你割一坨肥一点哈四伯爷
Let me give you a fatty slice, uncle?

0:05:33.209,0:05:36.289
要得啊 小坨点 割大坨了
Yup. Smaller, dat's too big!

0:05:38.714,0:05:40.274
来嘛 这里有碗
Here you are. We have a bowl here

0:05:41.172,0:05:43.080
我来给你割你尝哈看
Let me slice it for you. Have a try

0:05:48.326,0:05:49.660
嗯 卤耙了
Hmm, it's braised soft

0:05:50.218,0:05:50.760
耙了是不
Is it soft?

0:05:50.760,0:05:51.164
嗯
Yeah

0:05:55.780,0:06:00.117
我们这个所有的卤味啊卤出来了之后
After cooking finishes, all the braised food

0:06:00.125,0:06:03.120
家庭操作的卤味拿出来了之后
All the home-version braised food, after cooking

0:06:03.644,0:06:05.204
它会受到氧化
It gets oxidized

0:06:05.623,0:06:07.335
然后颜色会变得深一些
And the color turns darker

0:06:07.592,0:06:09.809
如果你炒糖色掌握得不好的话
Say if we haven't fully mastered making caramelized sugar

0:06:10.437,0:06:12.131
用糖色卤出来一会儿就会
Food braised with the caramelized sugar will...

0:06:12.131,0:06:13.672
你这个大了我来割
You got it too big, gimme da knife

0:06:14.329,0:06:14.995
你来割啊 来嘛
OK, you slice it

0:06:15.699,0:06:17.602
我来割坨小点的
I'll make a smaller slice

0:06:19.495,0:06:20.466
就用手抓着吃
Eat it with your hands

0:06:20.961,0:06:23.815
如果我们家庭里面炒糖色的
So if we make caramalized sugar at home

0:06:23.891,0:06:28.515
控制不好糖色的成色 卤出来一会就要黑这个
and fail to control its quality, the food turns dark very soon

0:06:29.562,0:06:30.456
黑了也很正常
It turns dark, which is normal

0:06:30.780,0:06:32.169
来嘛 你吃这个蹄筋嘛
C'mon, have dis tonden

0:06:32.949,0:06:33.549
蹄筋呀这个是
Is this a tendon?

0:06:33.663,0:06:34.957
那不是蹄筋咋子
Ain't it a tendon?

0:06:36.403,0:06:37.374
又脆有香
Crunchy and flavorful

0:06:39.305,0:06:40.494
真的是很脆
That's really very crunchy

0:06:40.494,0:06:43.263
是啊 那个蹄筋安逸得很
Yeah, dat tendon is very nice

0:06:45.119,0:06:46.194
这个皮子还多安逸
Da skin is so nice

0:06:46.869,0:06:47.278
是不
Is it?

0:06:47.412,0:06:47.783
是啊
Yeah

0:06:52.740,0:06:54.177
这个皮子很香
Da skin is very flavorful

0:06:56.327,0:06:59.505
我们这个卤料包你看是像这个样子的
The master stock bag. This is what is looks after after cooking

0:07:00.523,0:07:04.386
卤了之后把它捞出来放凉了之后放到冰箱里面
After cooking, we can take it out, cool it down, and store it refrigerated

0:07:04.633,0:07:05.908
第二次可以接着卤
And use it next time

0:07:07.792,0:07:09.924
你看这个水 里面的这个香料都还多香
Look at the water. The spices are still so aromatic

0:07:09.924,0:07:11.008
还可以卤一两次
Can be reused for a couple of times

0:07:13.349,0:07:15.657
就是跟它整那个懒人排骨差不多嘎
It's like da "Lazy Man's Pork Rib"?

0:07:15.657,0:07:16.418
哦喔有点像
Oh, yeah

0:07:16.478,0:07:20.013
拿这个袋子放在里面
Just put a bag there

0:07:20.270,0:07:22.031
这些放在里面就可以卤了
Put things in da bag, then you can cook

0:07:22.691,0:07:24.287
这个效果的话其实还（不错）
The results are acually... (good)

0:07:24.287,0:07:25.534
效果还是很好
Da results are very good

0:07:25.640,0:07:26.609
效果还是不错
The results are pretty good

0:07:27.645,0:07:29.122
好了 本期视频就到这里
Alright, that's all for this video

0:07:29.314,0:07:30.396
这个很方便的
Dis is very convenient

0:07:30.455,0:07:33.516
跟大家推荐这个懒人卤料
I recommend this "Lazy Man's Master Stock Bag" to you guys

0:07:35.105,0:07:37.256
懒人卤料 硬是懒人卤料
Lazy man's bag... What a lazy man's bag

0:07:38.021,0:07:39.452
好啦 就到这里了 拜拜
Alright, that's all. Bye bye

0:07:39.630,0:07:40.488
好方便嘛
So convenient
