### ISSUE TITLE
【美食作家王刚】看望外婆 - https://youtu.be/SbQjJrzhss0

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1133]
**视频链接**：https://youtu.be/SbQjJrzhss0

视频时长4:19，预计发布时间为北京时间6月9日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
外婆最爱喝酒，今天去看外婆给她带点酒，老人年级大了最缺的是陪伴

简介
大家好，今天去看望我的外婆，不小心居然爆料了不少外婆小时候的故事😂，真的是家有一老如有一宝（大家不要学我外婆啊😂）。其实老粉丝可能知道我的外公是老军人，小时候和他一起长大，有着军事化的管理，对我的影响非常的大，我一年多前拍过一期我回忆外公和去看望外婆的视频，大家如果感兴趣的话也可以去看一看，链接在此：https://www.youtube.com/watch?v=XwelRzrUK7Y

字幕
0:00:00.350,0:00:01.050
哈喽大家好

0:00:01.325,0:00:04.450
今天我托我朋友送了一个东西过来

0:00:04.450,0:00:05.050
就是这个

0:00:05.675,0:00:07.950
是一壶酒有5斤

0:00:08.600,0:00:09.525
给我外婆带过来

0:00:09.650,0:00:13.400
然后我今天带着我妈来看一下我妈妈的妈妈

0:00:14.750,0:00:20.600
我妈给外婆买了一些西瓜鸡蛋面包还有蓝莓

0:00:21.150,0:00:23.450
因为我外婆牙齿都掉的差不多了

0:00:24.225,0:00:25.500
吃不了太硬的水果

0:00:25.550,0:00:29.375
只能吃一些西瓜呀蓝莓呀或者是香蕉之类的

0:00:29.375,0:00:29.775
走嘛

0:00:37.350,0:00:40.275
真的敲错门了敲到人家的门了

0:00:40.325,0:00:41.875
我是感觉哪里在敲

0:00:43.275,0:00:43.875
外婆呢

0:00:44.275,0:00:45.025
在这边

0:00:45.725,0:00:46.450
妈

0:00:46.675,0:00:47.225
外婆

0:00:47.275,0:00:48.550
你得睡午觉啊

0:00:49.425,0:00:50.375
在看电视

0:00:50.400,0:00:51.825
给你提点西瓜来

0:00:54.075,0:00:57.000
还有点土鸡蛋小芬专门给你买的

0:00:58.275,0:01:00.250
现在一顿饭喝（酒）得到好多哦

0:01:02.875,0:01:04.500
1两多酒

0:01:04.675,0:01:10.225
我外婆以前要抽烟喝酒偶尔打打麻将

0:01:10.475,0:01:13.350
现在的话她眼睛有点不对

0:01:13.450,0:01:14.625
耳朵有点背

0:01:15.350,0:01:18.300
但是打麻将的时候又很灵活

0:01:19.350,0:01:21.950
就是上次我给你拿的那个粮食酒 

0:01:22.150,0:01:26.975
这个是我朋友自家生产的这个酒

0:01:27.625,0:01:30.050
我外婆说喝了有什么

0:01:30.425,0:01:32.700
你上次喝了说有什么感觉呢

0:01:32.800,0:01:34.775
这瓶拿去试一下嘛

0:01:35.875,0:01:38.250
还是有一个这个瓶子啊

0:01:38.250,0:01:38.875
嗯

0:01:39.725,0:01:41.550
这种瓶子一次就喝这么多

0:01:41.650,0:01:44.250
你一回喝这么多 这瓶子估计没得1两得

0:01:45.425,0:01:47.900
我倒在杯子里要倒半杯

0:01:50.250,0:01:52.450
这是我朋友小熙家的酒

0:01:52.700,0:01:56.750
我外婆说喝了有小时候酿的酒的感觉

0:01:56.875,0:02:01.506
所以我朋友又给我送了5斤

0:02:01.875,0:02:03.850
你年轻时候好久开始喝酒的

0:02:04.075,0:02:05.125
你肯定晓得撒

0:02:05.675,0:02:06.825
我晓得她什么时候喝酒

0:02:06.950,0:02:09.225
人家当姑娘（没嫁人）的时候就开始喝酒了

0:02:10.725,0:02:13.050
抽烟也是当姑娘就开始抽烟

0:02:13.100,0:02:14.025
好多岁开始抽烟的哦

0:02:14.050,0:02:17.100
小学就开始抽烟开始喝酒

0:02:20.900,0:02:22.625
那会儿还劝我们喝酒

0:02:23.616,0:02:24.532
不劝 喝酒不劝

0:02:24.803,0:02:26.595
只说没有劝我们抽烟劝我们喝酒

0:02:27.150,0:02:30.750
反正一倒酒出来就喊大家喝

0:02:31.625,0:02:35.525
每晚上你外公就要喊我拿碗去舀酒都嘛

0:02:36.775,0:02:40.775
3桌人客厅一桌工人一桌厨房一桌

0:02:40.825,0:02:45.575
那会儿你们富有喝得起酒所以没有多大就学会了

0:02:46.525,0:02:48.825
我说你没有大就学会了喝酒抽烟

0:02:48.950,0:02:49.975
12岁

0:02:50.425,0:02:51.500
12岁就开始喝酒

0:02:51.775,0:02:54.375
那一年还没满12岁

0:02:55.550,0:02:57.425
你看不管我妈年纪多大

0:02:57.500,0:02:59.225
不管你是50岁还是60岁

0:02:59.500,0:03:01.600
在妈妈面前永远都是小孩子

0:03:02.775,0:03:05.725
然后今天拍这个视频主要就是

0:03:05.975,0:03:07.250
跟大家分享一下

0:03:07.450,0:03:11.100
家里有老人的不管自己有多忙多陪一下

0:03:11.325,0:03:16.050
1天2两 5斤你都只喝得到好久哦

0:03:16.675,0:03:20.325
我在你们六舅那边我自己出钱打的

0:03:21.125,0:03:26.150
喝了20斤

0:03:26.150,0:03:26.900
1个月啊

0:03:27.025,0:03:27.525
不是的

0:03:27.725,0:03:28.475
8个月

0:03:28.930,0:03:30.006
8个月20斤

0:03:33.182,0:03:34.880
这样子你1个月才喝2斤多撒

0:03:35.051,0:03:35.992
要喝好多啊

0:03:39.315,0:03:41.734
我去打牌还是要喝酒

0:03:42.504,0:03:43.799
喝了酒去打牌

0:03:45.326,0:03:47.220
我说你捉麻麻鱼（炸胡）的快来哦

0:03:47.318,0:03:48.735
我说我喝了酒的哦

0:03:54.111,0:03:59.352
前天我去打牌走起路累得不得了我说我不去了

0:04:08.698,0:04:10.360
好啦本期视频就到这里啦

0:04:10.824,0:04:11.227
拜拜

0:04:12.535,0:04:13.854
拜拜外婆

0:04:14.160,0:04:16.811
跟所有的朋友说拜拜


```

**Comment by brainshawn** [comment]
认领

**Comment by brainshawn** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
外婆最爱喝酒，今天去看外婆给她带点酒，老人年级大了最缺的是陪伴
taking wines to visit grandmother, who likes drinking and needs company

简介
大家好，今天去看望我的外婆，不小心居然爆料了不少外婆小时候的故事😂，真的是家有一老如有一宝（大家不要学我外婆啊😂）。其实老粉丝可能知道我的外公是老军人，小时候和他一起长大，有着军事化的管理，对我的影响非常的大，我一年多前拍过一期我回忆外公和去看望外婆的视频，大家如果感兴趣的话也可以去看一看，链接在此：https://www.youtube.com/watch?v=XwelRzrUK7Y
Hello everyone, today we visted my grandmother and disclosed quite a few stories of when she was a child -- I want to say that it's really good to have an older person in a family (but please don't mimic her ;)). As most senior fans have already known, my grandfather was a soldier and brang me up with military discipline, which has made a huge impact to me. One year ago I uploaded a video in which I recalled my grandfather and visited my grandmother, so if you are interested you could take a look at https://www.youtube.com/watch?v=XwelRzrUK7Y.

字幕
0:00:00.350,0:00:01.050
哈喽大家好
Hello everyone

0:00:01.325,0:00:04.450
今天我托我朋友送了一个东西过来
Today I received a package from my friend

0:00:04.450,0:00:05.050
就是这个
here it is

0:00:05.675,0:00:07.950
是一壶酒有5斤
a pot of wine, about 5 jin (2.5kg)

0:00:08.600,0:00:09.525
给我外婆带过来
for my grandmother

0:00:09.650,0:00:13.400
然后我今天带着我妈来看一下我妈妈的妈妈
soon I will visit my grandmother with my mother

0:00:14.750,0:00:20.600
我妈给外婆买了一些西瓜鸡蛋面包还有蓝莓
my mother bought a few watermelons, eggs, breads and blueberries

0:00:21.150,0:00:23.450
因为我外婆牙齿都掉的差不多了
as my grandmother only has few teech left now

0:00:24.225,0:00:25.500
吃不了太硬的水果
unable to eat hard fruits

0:00:25.550,0:00:29.375
只能吃一些西瓜呀蓝莓呀或者是香蕉之类的
can only eat soft fruits like watermelons, blueberries and bananas

0:00:29.375,0:00:29.775
走嘛
let's go

0:00:37.350,0:00:40.275
真的敲错门了敲到人家的门了
it seems we knocked at a wrong door

0:00:40.325,0:00:41.875
我是感觉哪里在敲
I feel someone knocking somewhere

0:00:43.275,0:00:43.875
外婆呢
where is grandmother

0:00:44.275,0:00:45.025
在这边
she is here

0:00:45.725,0:00:46.450
妈
mum

0:00:46.675,0:00:47.225
外婆
grandmother

0:00:47.275,0:00:48.550
你得睡午觉啊
I supposed you are taking a noon nap

0:00:49.425,0:00:50.375
在看电视
I am watching TV

0:00:50.400,0:00:51.825
给你提点西瓜来
here are some watermelons for you

0:00:54.075,0:00:57.000
还有点土鸡蛋小芬专门给你买的
and a few free range chicken, bought by Xiao Fen

0:00:58.275,0:01:00.250
现在一顿饭喝（酒）得到好多哦
how much wine shall we drink for a meal nowadays

0:01:02.875,0:01:04.500
1两多酒
1 liang (50g)

0:01:04.675,0:01:10.225
我外婆以前要抽烟喝酒偶尔打打麻将
long times ago my grandmother often smoked, drank and played Mahjong

0:01:10.475,0:01:13.350
现在的话她眼睛有点不对
but now there's something wrong with her eyes

0:01:13.450,0:01:14.625
耳朵有点背
and her ears

0:01:15.350,0:01:18.300
但是打麻将的时候又很灵活
however, she is still smart when palying Mahjong

0:01:19.350,0:01:21.950
就是上次我给你拿的那个粮食酒 
the same as the grain wine I gave you last time

0:01:22.150,0:01:26.975
这个是我朋友自家生产的这个酒
it was made in my friend's factory

0:01:27.625,0:01:30.050
我外婆说喝了有什么
my grandmother is asking what's the feeling after drinking it

0:01:30.425,0:01:32.700
你上次喝了说有什么感觉呢
what did you feel last time

0:01:32.800,0:01:34.775
这瓶拿去试一下嘛
just try with it

0:01:35.875,0:01:38.250
还是有一个这个瓶子啊
do you mean there's another bottle like this one

0:01:38.250,0:01:38.875
嗯
yes

0:01:39.725,0:01:41.550
这种瓶子一次就喝这么多
you should always drink so much for such bottle

0:01:41.650,0:01:44.250
你一回喝这么多 这瓶子估计没得1两得
if you drink so much each time, there would be less thant 1 liang (50g) left in the bottle

0:01:45.425,0:01:47.900
我倒在杯子里要倒半杯
it takes half a cup

0:01:50.250,0:01:52.450
这是我朋友小熙家的酒
this is from my friend Xiao Xi

0:01:52.700,0:01:56.750
我外婆说喝了有小时候酿的酒的感觉
my grandmother once said it feels like the homemade wine of when she was a child

0:01:56.875,0:02:01.506
所以我朋友又给我送了5斤
so this time my friend gave me 5 jin (2.5 kg) more

0:02:01.875,0:02:03.850
你年轻时候好久开始喝酒的
when did you begin to drink when you were young

0:02:04.075,0:02:05.125
你肯定晓得撒
you must know it

0:02:05.675,0:02:06.825
我晓得她什么时候喝酒
indeed I know

0:02:06.950,0:02:09.225
人家当姑娘（没嫁人）的时候就开始喝酒了
she began to drink even before married

0:02:10.725,0:02:13.050
抽烟也是当姑娘就开始抽烟
the same for smoking

0:02:13.100,0:02:14.025
好多岁开始抽烟的哦
when did you start smoking

0:02:14.050,0:02:17.100
小学就开始抽烟开始喝酒
both smoking and drinking were started when I was in primary school

0:02:20.900,0:02:22.625
那会儿还劝我们喝酒
at that time she also asked us to drink together

0:02:23.616,0:02:24.532
不劝 喝酒不劝
no, not for drinking

0:02:24.803,0:02:26.595
只说没有劝我们抽烟劝我们喝酒
she just said she didn't ask us to smoke and drink

0:02:27.150,0:02:30.750
反正一倒酒出来就喊大家喝
anyway, she always suggest to drink together when the wine is out of bottle

0:02:31.625,0:02:35.525
每晚上你外公就要喊我拿碗去舀酒都嘛
every evening your grandfather asked me to fetch some wine with a bowl

0:02:36.775,0:02:40.775
3桌人客厅一桌工人一桌厨房一桌
3 tables: 1 in living room, 1 for workers, and 1 in kitchen

0:02:40.825,0:02:45.575
那会儿你们富有喝得起酒所以没有多大就学会了
you were so rich to affort drinking, that you were used to it soon afterwards

0:02:46.525,0:02:48.825
我说你没有大就学会了喝酒抽烟
I meant you started to smoke and drink when you were very young

0:02:48.950,0:02:49.975
12岁
12 years old

0:02:50.425,0:02:51.500
12岁就开始喝酒
began to drink since 12 years old

0:02:51.775,0:02:54.375
那一年还没满12岁
even a little before 12 years old

0:02:55.550,0:02:57.425
你看不管我妈年纪多大
you see, no matter how old my mother is

0:02:57.500,0:02:59.225
不管你是50岁还是60岁
no matter 50 or 60 years old

0:02:59.500,0:03:01.600
在妈妈面前永远都是小孩子
she is always a child in front of my grandmother

0:03:02.775,0:03:05.725
然后今天拍这个视频主要就是
we took this video today

0:03:05.975,0:03:07.250
跟大家分享一下
just to share with others

0:03:07.450,0:03:11.100
家里有老人的不管自己有多忙多陪一下
that we should accompany the older people no matter how busy we are

0:03:11.325,0:03:16.050
1天2两 5斤你都只喝得到好久哦
5 liang (250 g) everyday, so it would take a long time to drink 5 jin (2.5 kg)

0:03:16.675,0:03:20.325
我在你们六舅那边我自己出钱打的
I paid myself when I was living with your 6th uncle

0:03:21.125,0:03:26.150
喝了20斤
I drank 20 jin (10 kg)

0:03:26.150,0:03:26.900
1个月啊
within a month?

0:03:27.025,0:03:27.525
不是的
no

0:03:27.725,0:03:28.475
8个月
8 months

0:03:28.930,0:03:30.006
8个月20斤
20 jin (10 kg) in 8 months

0:03:33.182,0:03:34.880
这样子你1个月才喝2斤多撒
so you only drank more than 2 jin (1 kg) every month

0:03:35.051,0:03:35.992
要喝好多啊
so much to drink

0:03:39.315,0:03:41.734
我去打牌还是要喝酒
shall I play cards or drink wine?

0:03:42.504,0:03:43.799
喝了酒去打牌
drink wine before playing cards

0:03:45.326,0:03:47.220
我说你捉麻麻鱼（炸胡）的快来哦
I would expect that ZhuoMaMaYu (winning) would come sooner

0:03:47.318,0:03:48.735
我说我喝了酒的哦
I would say I have drunk

0:03:54.111,0:03:59.352
前天我去打牌走起路累得不得了我说我不去了
2 days ago I felt so tired while walking that I told them I wouldn't join

0:04:08.698,0:04:10.360
好啦本期视频就到这里啦
okay, it's time to say goodbye

0:04:10.824,0:04:11.227
拜拜
bye

0:04:12.535,0:04:13.854
拜拜外婆
bye, my grandmother

0:04:14.160,0:04:16.811
跟所有的朋友说拜拜
say bye to everyone

**Comment by brainshawn** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
外婆最爱喝酒，今天去看外婆给她带点酒，老人年级大了最缺的是陪伴
Visited grandmother with wine, who likes drinking and needs company

简介
大家好，今天去看望我的外婆，不小心居然爆料了不少外婆小时候的故事😂，真的是家有一老如有一宝（大家不要学我外婆啊😂）。其实老粉丝可能知道我的外公是老军人，小时候和他一起长大，有着军事化的管理，对我的影响非常的大，我一年多前拍过一期我回忆外公和去看望外婆的视频，大家如果感兴趣的话也可以去看一看，链接在此：https://www.youtube.com/watch?v=XwelRzrUK7Y
Hello everyone, today we visted my grandmother and disclosed quite a few stories of when she was a child -- I want to say that it's really good to have an older person in a family (but please don't mimic her ;)). As most senior fans have already known, my grandfather was a soldier and brang me up with military discipline, which has made a huge impact to me. One year ago I uploaded a video in which I recalled my grandfather and visited my grandmother, so if you are interested you could take a look at https://www.youtube.com/watch?v=XwelRzrUK7Y.

字幕
0:00:00.350,0:00:01.050
哈喽大家好
Hello everyone

0:00:01.325,0:00:04.450
今天我托我朋友送了一个东西过来
today I received a package from my friend

0:00:04.450,0:00:05.050
就是这个
here it is

0:00:05.675,0:00:07.950
是一壶酒有5斤
a pot of wine, about 5 jin (2.5kg)

0:00:08.600,0:00:09.525
给我外婆带过来
for my grandmother

0:00:09.650,0:00:13.400
然后我今天带着我妈来看一下我妈妈的妈妈
soon I will visit my grandmother with my mother

0:00:14.750,0:00:20.600
我妈给外婆买了一些西瓜鸡蛋面包还有蓝莓
my mother bought a few watermelons, eggs, breads and blueberries

0:00:21.150,0:00:23.450
因为我外婆牙齿都掉的差不多了
as my grandmother only has few teech left now

0:00:24.225,0:00:25.500
吃不了太硬的水果
unable to eat hard fruits

0:00:25.550,0:00:29.375
只能吃一些西瓜呀蓝莓呀或者是香蕉之类的
can only eat soft fruits like watermelons, blueberries and bananas

0:00:29.375,0:00:29.775
走嘛
let's go

0:00:37.350,0:00:40.275
真的敲错门了敲到人家的门了
we knocked at a wrong door

0:00:40.325,0:00:41.875
我是感觉哪里在敲
I felt someone was knocking

0:00:43.275,0:00:43.875
外婆呢
where is grandmother

0:00:44.275,0:00:45.025
在这边
she is here

0:00:45.725,0:00:46.450
妈
mum

0:00:46.675,0:00:47.225
外婆
grandmother

0:00:47.275,0:00:48.550
你得睡午觉啊
are you sleeping

0:00:49.425,0:00:50.375
在看电视
I am watching TV

0:00:50.400,0:00:51.825
给你提点西瓜来
we braught some watermelons for you

0:00:54.075,0:00:57.000
还有点土鸡蛋小芬专门给你买的
and a few eggs of free range chicken, bought by Xiao Fen

0:00:58.275,0:01:00.250
现在一顿饭喝（酒）得到好多哦
how much wine do you drink in a meal nowadays

0:01:02.875,0:01:04.500
1两多酒
a bit more than 1 liang (50g)

0:01:04.675,0:01:10.225
我外婆以前要抽烟喝酒偶尔打打麻将
long times ago my grandmother often smoked and drank, also played Mahjong occasionally

0:01:10.475,0:01:13.350
现在的话她眼睛有点不对
but now there's something wrong with her eyes

0:01:13.450,0:01:14.625
耳朵有点背
and her ears

0:01:15.350,0:01:18.300
但是打麻将的时候又很灵活
however, she is still very smart while palying Mahjong

0:01:19.350,0:01:21.950
就是上次我给你拿的那个粮食酒 
this is the same as the grain wine I gave you last time

0:01:22.150,0:01:26.975
这个是我朋友自家生产的这个酒
it was made in my friend's home

0:01:27.625,0:01:30.050
我外婆说喝了有什么
my grandmother told me that after drinking it she felt...

0:01:30.425,0:01:32.700
你上次喝了说有什么感觉呢
what did you feel last time

0:01:32.800,0:01:34.775
这瓶拿去试一下嘛
how about drinking this

0:01:35.875,0:01:38.250
还是有一个这个瓶子啊
shall I drink with such a bottle

0:01:38.250,0:01:38.875
嗯
yes

0:01:39.725,0:01:41.550
这种瓶子一次就喝这么多
I can only drink so little with such a bottle

0:01:41.650,0:01:44.250
你一回喝这么多 这瓶子估计没得1两得
you drinks so little everytime, I guess the bottle contains less thant 1 liang (50g) wine 

0:01:45.425,0:01:47.900
我倒在杯子里要倒半杯
the bottle is about half a cup

0:01:50.250,0:01:52.450
这是我朋友小熙家的酒
this is from my friend Xiao Xi

0:01:52.700,0:01:56.750
我外婆说喝了有小时候酿的酒的感觉
my grandmother once said it feels like the homemade wine of when she was a child

0:01:56.875,0:02:01.506
所以我朋友又给我送了5斤
so this time my friend gave me 5 jin (2.5 kg)

0:02:01.875,0:02:03.850
你年轻时候好久开始喝酒的
when did you begin to drink when you were young

0:02:04.075,0:02:05.125
你肯定晓得撒
you must know it

0:02:05.675,0:02:06.825
我晓得她什么时候喝酒
I definitely know

0:02:06.950,0:02:09.225
人家当姑娘（没嫁人）的时候就开始喝酒了
she drank even before married

0:02:10.725,0:02:13.050
抽烟也是当姑娘就开始抽烟
and the same for smoking

0:02:13.100,0:02:14.025
好多岁开始抽烟的哦
when did you start smoking

0:02:14.050,0:02:17.100
小学就开始抽烟开始喝酒
I started to smoke and drink when I was in primary school

0:02:20.900,0:02:22.625
那会儿还劝我们喝酒
she also persuaded us to drink at that time

0:02:23.616,0:02:24.532
不劝 喝酒不劝
should not persuade others to drink

0:02:24.803,0:02:26.595
只说没有劝我们抽烟劝我们喝酒
she didn't persuad us to smoke, but indeed persuaded us to drink

0:02:27.150,0:02:30.750
反正一倒酒出来就喊大家喝
anyway, she always asked us to drink as long as wine is poured out from the bottle

0:02:31.625,0:02:35.525
每晚上你外公就要喊我拿碗去舀酒都嘛
every evening your grandfather asked me to fetch some wine with a bowl

0:02:36.775,0:02:40.775
3桌人客厅一桌工人一桌厨房一桌
there were people around 3 tables: 1 in living room, 1 for workers, and 1 in kitchen

0:02:40.825,0:02:45.575
那会儿你们富有喝得起酒所以没有多大就学会了
you were so rich to affort drinking, that you learned how to drink when very young

0:02:46.525,0:02:48.825
我说你没有大就学会了喝酒抽烟
I said you started to smoke and drink even when you were very young

0:02:48.950,0:02:49.975
12岁
12 years old

0:02:50.425,0:02:51.500
12岁就开始喝酒
began to drink since 12 years old

0:02:51.775,0:02:54.375
那一年还没满12岁
even a little before 12 years old

0:02:55.550,0:02:57.425
你看不管我妈年纪多大
you see, no matter how old my mother is

0:02:57.500,0:02:59.225
不管你是50岁还是60岁
no matter 50 or 60 years old

0:02:59.500,0:03:01.600
在妈妈面前永远都是小孩子
she is always a child in front of my grandmother

0:03:02.775,0:03:05.725
然后今天拍这个视频主要就是
we made this video today

0:03:05.975,0:03:07.250
跟大家分享一下
just to share with all

0:03:07.450,0:03:11.100
家里有老人的不管自己有多忙多陪一下
that we should accompany older people no matter how busy we are

0:03:11.325,0:03:16.050
1天2两 5斤你都只喝得到好久哦
5 liang (250 g) everyday, so it would take a long time to drink 5 jin (2.5 kg)

0:03:16.675,0:03:20.325
我在你们六舅那边我自己出钱打的
I paid myself when I was at your 6th uncle's home

0:03:21.125,0:03:26.150
喝了20斤
I drank 20 jin (10 kg)

0:03:26.150,0:03:26.900
1个月啊
in a month?

0:03:27.025,0:03:27.525
不是的
no

0:03:27.725,0:03:28.475
8个月
8 months

0:03:28.930,0:03:30.006
8个月20斤
20 jin (10 kg) in 8 months

0:03:33.182,0:03:34.880
这样子你1个月才喝2斤多撒
so you only drank more than 2 jin (1 kg) every month

0:03:35.051,0:03:35.992
要喝好多啊
that's already so much

0:03:39.315,0:03:41.734
我去打牌还是要喝酒
shall I play cards or drink wine

0:03:42.504,0:03:43.799
喝了酒去打牌
drink wine before playing cards

0:03:45.326,0:03:47.220
我说你捉麻麻鱼（炸胡）的快来哦
I would say ZhuoMaMaYu (winning) comes as soon as possible

0:03:47.318,0:03:48.735
我说我喝了酒的哦
because I have drunk

0:03:54.111,0:03:59.352
前天我去打牌走起路累得不得了我说我不去了
2 days ago I felt so tired while walking that I told them I wouldn't join

0:04:08.698,0:04:10.360
好啦本期视频就到这里啦
okay, it's time to say goodbye

0:04:10.824,0:04:11.227
拜拜
bye

0:04:12.535,0:04:13.854
拜拜外婆
say bye, grandmother

0:04:14.160,0:04:16.811
跟所有的朋友说拜拜
say bye to all friends
