### ISSUE TITLE
【美食作家王刚】再给四伯做椒盐虾 - https://youtu.be/L4-AscjhIvw

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1139]
**视频链接**：https://youtu.be/L4-AscjhIvw

视频时长6:42，预计发布时间为北京时间6月10日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长再给四伯做“椒盐虾”，上次吃漆二娃做的没吃爽，这次特地买虾来点名要吃

简介
大家好，上次漆二娃给四伯做了一道“椒盐虾”，四伯很喜欢这款味道，但是由于漆二娃虾处理的不好，把四伯爷的嘴都扎出血了...所以四伯这次又看到虾就买了些来，点名要我再给他做一次，这次一定要吃巴适。这次用了我之前炒好的椒盐，如果大家想具体学习自制椒盐的做法可以参考我之前的视频，视频连接在此：椒盐虾 https://www.youtube.com/watch?v=bl5E6lx8HRY&vl=zh-Hans

字幕
0:00:00.583,0:00:01.248
哈喽 大家好

0:00:01.694,0:00:05.093
上次我伯爷说漆二娃把那个虾没有做好吃

0:00:05.129,0:00:09.230
这次我伯爷自己买了一斤多 一哈好多哦四伯爷

0:00:09.567,0:00:13.241
斤多 75块钱 50一斤

0:00:13.387,0:00:15.537
我喊他让了一块钱 74块钱

0:00:15.560,0:00:17.294
上次漆二娃整的不好吃 

0:00:17.364,0:00:20.751
这次我喊你整来看好不好吃点

0:00:22.184,0:00:23.976
 好 我们现在来开始做吧

0:00:25.075,0:00:26.797
四伯爷 我把这个虾枪弄来剪了

0:00:26.913,0:00:28.485
免得它戳到你的嘴巴哈

0:00:28.647,0:00:30.924
头次漆二娃整的就是把嘴巴给我戳出血了

0:00:30.924,0:00:34.520
我还没发现是咋个整到的都不晓得

0:00:34.763,0:00:37.907
我们这个虾枪最好是把它剪了 非常的尖

0:00:38.508,0:00:42.173
家里有小孩子或者是老人家的话一定不要这个

0:00:42.265,0:00:48.346
这个插到嘴巴有毒 会肿这个戳到嘴巴

0:00:50.219,0:00:55.641
好啦 最后一个我们剪了15分钟了这里的嘎

0:00:56.450,0:00:56.855
是安

0:00:56.867,0:00:59.283
OK 好啦我们这个虾就剪好了

0:00:59.919,0:01:02.485
我们这个剪下来的虾枪是不要的

0:01:02.855,0:01:04.566
以前我拿来喂过我家的猫

0:01:04.578,0:01:06.000
结果猫吃了都吐了

0:01:06.832,0:01:07.849
你还要跑

0:01:08.069,0:01:08.705
抓它回来

0:01:10.057,0:01:10.947
跑你跑得掉呀

0:01:11.213,0:01:12.855
这个不要拿给猫吃 四伯爷

0:01:13.132,0:01:13.930
倒了撒

0:01:14.104,0:01:15.248
嗯这个必须倒了

0:01:15.815,0:01:17.433
四伯爷 这个海椒你在哪里摘得哦

0:01:17.803,0:01:21.236
我土里撒 第一批海椒 最先栽

0:01:21.410,0:01:23.780
这个辣椒我们把它切成小粒

0:01:26.601,0:01:27.526
一样一个都够了

0:01:36.046,0:01:38.404
我们把这个辣椒籽去掉

0:01:39.826,0:01:42.127
然后我们来把这个辣椒全部切成小颗粒

0:01:42.127,0:01:44.265
你把它切小颗很了夹都不好夹

0:01:45.005,0:01:46.612
这个是做配菜的

0:01:47.098,0:01:51.352
然后我们再切一点洋葱 就这么一片就够了

0:02:00.404,0:02:01.826
这葱葱也是你栽的哦四伯爷

0:02:02.208,0:02:06.323
那还用说啊 农村人葱子都没得还有啥子干的

0:02:07.086,0:02:10.023
我们农村最多的就是葱 蒜苗 芹菜

0:02:10.832,0:02:12.300
这些东西不用去外面买

0:02:12.658,0:02:13.826
自己家里就可以满足了

0:02:14.034,0:02:14.658
是安

0:02:15.780,0:02:16.751
好 准备好了

0:02:17.421,0:02:20.578
然后这里是我上次炒的椒盐

0:02:20.809,0:02:24.069
再不用的话就回潮了 这次正好把它用了嘎

0:02:24.196,0:02:24.890
走嘛

0:02:27.364,0:02:28.878
 我们先把这个虾焯一下水

0:02:33.306,0:02:34.543
这个虾子还要焯哈水啊

0:02:34.820,0:02:35.375
要哦

0:02:36.358,0:02:39.537
我们这个虾焯一下水的话更好炸一些

0:02:40.612,0:02:43.722
还有就是我们焯虾子的水一定要水开了再下去

0:02:46.092,0:02:47.248
好 下锅

0:02:49.502,0:02:50.936
然后加点料酒

0:02:56.046,0:02:58.703
拿下去就变红了嘎

0:02:58.751,0:03:00.913
啊 可以撒

0:03:01.052,0:03:01.491
可以

0:03:02.231,0:03:07.317
好 我们焯到它腰有点变弯就把它捞起来

0:03:15.976,0:03:17.271
好 倒宽油

0:03:20.173,0:03:22.497
放好多油哦

0:03:23.237,0:03:26.358
没得好多得 最多有六七斤

0:03:26.820,0:03:33.699
啊  虾子才斤多点 油放六七斤

0:03:34.312,0:03:37.086
这会抓点粉子（淀粉）给它上点粉

0:03:39.121,0:03:41.063
有这个粉子它炸出来就是脆的

0:03:41.491,0:03:42.809
它才粘得上面

0:03:42.994,0:03:43.537
安

0:03:43.583,0:03:45.005
粘在上面炸得泡

0:03:45.017,0:03:45.768
哦喔

0:03:46.369,0:03:48.184
OK 7成油温了

0:03:50.543,0:03:51.757
这样子给它抖下去

0:03:53.872,0:03:55.826
小心哦这个有点爆（油）哦

0:04:03.953,0:04:05.375
好了 我们这个虾差不多了

0:04:05.375,0:04:06.138
把它捞起来

0:04:11.167,0:04:12.531
然后把这个油沥干净

0:04:17.433,0:04:19.410
这个时候我们油就要少加一点了

0:04:21.421,0:04:23.144
锅中加入洋葱、青红辣椒爆香

0:04:24.381,0:04:25.526
把这个弄来给它爆香

0:04:25.526,0:04:27.849
爆香加这个（虾） 再加椒盐粉

0:04:28.335,0:04:30.774
最后加点葱葱就可以了

0:04:32.323,0:04:33.676
放虾

0:04:34.254,0:04:35.942
椒盐 

0:05:01.167,0:05:02.184
来 四伯爷尝哈看

0:05:02.323,0:05:02.947
试哈看嘛

0:05:03.549,0:05:04.289
这个很脆

0:05:07.132,0:05:08.947
这个我还咬得动 还是脆的

0:05:09.063,0:05:12.381
嗯 我们把虾枪去了就不怕

0:05:13.456,0:05:13.895
安逸

0:05:13.988,0:05:15.086
就不怕戳到嘴巴了噶

0:05:15.086,0:05:15.445
嗯

0:05:20.774,0:05:22.057
其实做这个菜很简单 

0:05:22.057,0:05:25.213
就是唯一一点不好就是要用宽油来炸

0:05:26.115,0:05:28.763
而且炸这个虾子的话 

0:05:29.375,0:05:32.277
这个油炸虾子炸不了几次这个油就会报废

0:05:32.300,0:05:33.583
最多3次就会报废

0:05:34.739,0:05:36.316
四伯爷 炸这个虾子

0:05:36.316,0:05:38.369
炸这个虾子很费油嘎

0:05:38.809,0:05:41.294
这个油里面要吸收这个虾子味道

0:05:42.439,0:05:43.838
炸了这个油

0:05:44.369,0:05:45.294
油要变味

0:05:45.306,0:05:46.554
嗯 就是油要变味

0:05:46.878,0:05:49.132
四伯爷很懂了这个 已经很懂行了

0:05:51.849,0:05:53.352
你慢慢都要变成行家了

0:05:55.075,0:05:59.930
那些东西日常生活中你都可以试出来的

0:06:01.526,0:06:06.543
唯一的有点不好就是我炒的那个椒盐粉回潮了

0:06:07.329,0:06:09.063
没得以前那么香得了

0:06:10.531,0:06:14.358
所以我们这个椒盐粉的话最好是现炒现用

0:06:14.578,0:06:15.144
嗯

0:06:15.965,0:06:17.398
最好就不要超过半个月

0:06:17.653,0:06:21.676
因为这个放太久了 四川我们这里比较潮湿

0:06:21.745,0:06:24.046
盐都起坨坨了嘎

0:06:25.017,0:06:28.034
下次少炒点就是撒 用完了又炒撒

0:06:34.843,0:06:36.173
好了 本期视频就到这里

0:06:40.358,0:06:40.867
接着吃


```

**Comment by moodswinnngs** [comment]
认领

**Comment by moodswinnngs** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长再给四伯做 "椒盐虾" ，上次吃漆二娃做的没吃爽，这次特地买虾来点名要吃
Uncle bought shrimp and asked Chef Wang to cook pepper-salt shrimp for him again. 

简介
大家好，上次漆二娃给四伯做了一道 "椒盐虾" ，四伯很喜欢这款味道，但是由于漆二娃虾处理的不好，把四伯爷的嘴都扎出血了...所以四伯这次又看到虾就买了些来，点名要我再给他做一次，这次一定要吃巴适。这次用了我之前炒好的椒盐，如果大家想具体学习自制椒盐的做法可以参考我之前的视频，视频连接在此：椒盐虾 
https://www.youtube.com/watch?v=bl5E6lx8HRY&vl=zh-Hans
Intro
Hello Everyone, Qi Erwa made "pepper-salt shrimp" for my uncle last time, my uncle loved the flavour. But Qi Erwa didn't fix the shrimp well, and it ended up hurting my uncle's mouth… So this time my uncle bought more shrimps and asked me to cook this for him again, this time is going to be excellent. I used the pepper-salt mixture that I made from last time. If you want to learn how to make home make pepper-salt mixture, please watch my previous video, here's the link: https://www.youtube.com/watch?v=bl5E6lx8HRY&vl=zh-Hans

字幕
0:00:00.583,0:00:01.248
哈喽 大家好
Hello, everyone

0:00:01.694,0:00:05.093
上次我伯爷说漆二娃把那个虾没有做好吃
My uncle is complaining about Qi Erwa didn't make tasty shrimps last time

0:00:05.129,0:00:09.230
这次我伯爷自己买了一斤多 一哈好多哦四伯爷
So he bought over one jin (750g) shrimps himself this time. Uncle, how much was one jin?

0:00:09.567,0:00:13.241
斤多 75块钱 50一斤
I bought 75 yuan of shrimps; one jin was 50 yuan

0:00:13.387,0:00:15.537
我喊他让了一块钱 74块钱
I bargained with him to get a 1 yuan discount, so I spent 74 yuan

0:00:15.560,0:00:17.294
上次漆二娃整的不好吃 
Last time Qi Erwa didn't make it good

0:00:17.364,0:00:20.751
这次我喊你整来看好不好吃点
So this time I want you to make it better 

0:00:22.184,0:00:23.976
 好 我们现在来开始做吧
OK, now let's start 

0:00:25.075,0:00:26.797
四伯爷 我把这个虾枪弄来剪了
Uncle, let me fix the sharp edge of these shrimps

0:00:26.913,0:00:28.485
免得它戳到你的嘴巴哈
So it wouldn't hurt your mouth

0:00:28.647,0:00:30.924
头次漆二娃整的就是把嘴巴给我戳出血了
Last time the shrimp Qi Erwa cook made my mouth bleed

0:00:30.924,0:00:34.520
我还没发现是咋个整到的都不晓得
I didn't even realize how it happened

0:00:34.763,0:00:37.907
我们这个虾枪最好是把它剪了 非常的尖
We better cut off the sharp edge of the shrimp, it's very sharp

0:00:38.508,0:00:42.173
家里有小孩子或者是老人家的话一定不要这个
Especially If there's kids or elders at home

0:00:42.265,0:00:48.346
这个插到嘴巴有毒 会肿这个戳到嘴巴
If the sharp edge poked your lip, it would get your mouth poisoned and make them lips swollen

0:00:50.219,0:00:55.641
好啦 最后一个我们剪了15分钟了这里的嘎
OK, Last one. It took us 15 minutes to cut the shrimps

0:00:56.450,0:00:56.855
是安
Yea

0:00:56.867,0:00:59.283
OK 好啦我们这个虾就剪好了
OK, Now we have finished preparing the shrimp. 

0:00:59.919,0:01:02.485
我们这个剪下来的虾枪是不要的
We will not keep the sharp edge part

0:01:02.855,0:01:04.566
以前我拿来喂过我家的猫
I used to use them to feed my cat

0:01:04.578,0:01:06.000
结果猫吃了都吐了
Even my cat spitted it out 

0:01:06.832,0:01:07.849
你还要跑
Still trying to run?

0:01:08.069,0:01:08.705
抓它回来
Grab it 

0:01:10.057,0:01:10.947
跑你跑得掉呀
You can't run 

0:01:11.213,0:01:12.855
这个不要拿给猫吃 四伯爷
Don't give this to the cat, uncle 

0:01:13.132,0:01:13.930
倒了撒
Just throw them?

0:01:14.104,0:01:15.248
嗯这个必须倒了
Yes we have to throw this

0:01:15.815,0:01:17.433
四伯爷 这个海椒你在哪里摘得哦
Uncle, Where did you get this pepper?

0:01:17.803,0:01:21.236
我土里撒 第一批海椒 最先栽
I planted them, these are the first batch

0:01:21.410,0:01:23.780
这个辣椒我们把它切成小粒
Let's cut these peppers into small pieces

0:01:26.601,0:01:27.526
一样一个都够了
One from each type is enough 

0:01:36.046,0:01:38.404
我们把这个辣椒籽去掉
Let's get rid of the seeds

0:01:39.826,0:01:42.127
然后我们来把这个辣椒全部切成小颗粒
Now let's cut all the peppers into small pieces

0:01:42.127,0:01:44.265
你把它切小颗很了夹都不好夹
If you cut it too small, it would be hard to pick up with chopsticks

0:01:45.005,0:01:46.612
这个是做配菜的
This 

0:01:47.098,0:01:51.352
然后我们再切一点洋葱 就这么一片就够了
Then let's cut a bit of onion, just one slice is enough 

0:02:00.404,0:02:01.826
这葱葱也是你栽的哦四伯爷
Uncle, did you plant these green onions too? 

0:02:02.208,0:02:06.323
那还用说啊 农村人葱子都没得还有啥子干的
Of course, can't live without green onions 

0:02:07.086,0:02:10.023
我们农村最多的就是葱 蒜苗 芹菜
In our village, we planted a lot of green onions, garlic sprouts and Chinese celery

0:02:10.832,0:02:12.300
这些东西不用去外面买
You don't need to buy these outsides

0:02:12.658,0:02:13.826
自己家里就可以满足了
What you planted at home can support your needs 

0:02:14.034,0:02:14.658
是安
Yea

0:02:15.780,0:02:16.751
好 准备好了
OK now we are ready

0:02:17.421,0:02:20.578
然后这里是我上次炒的椒盐
Here is the pepper-salt powder I made from last time

0:02:20.809,0:02:24.069
再不用的话就回潮了 这次正好把它用了嘎
If we don't use it, it's going to be damp, let's use it this time

0:02:24.196,0:02:24.890
走嘛
Let’s go

0:02:27.364,0:02:28.878
 我们先把这个虾焯一下水
Let's parboil the shrimps first

0:02:33.306,0:02:34.543
这个虾子还要焯哈水啊
Do we need to do that? 

0:02:34.820,0:02:35.375
要哦
yea

0:02:36.358,0:02:39.537
我们这个虾焯一下水的话更好炸一些
It will be easier to fry them if you parboil the shrimps first

0:02:40.612,0:02:43.722
还有就是我们焯虾子的水一定要水开了再下去
Also, we have to wait for the water to boil before we put these shrimps in 

0:02:46.092,0:02:47.248
好 下锅
OK now put them in

0:02:49.502,0:02:50.936
然后加点料酒
Then add some cooking wine

0:02:56.046,0:02:58.703
拿下去就变红了嘎
Now they have become red

0:02:58.751,0:03:00.913
啊 可以撒
Ah good

0:03:01.052,0:03:01.491
可以
great

0:03:02.231,0:03:07.317
好 我们焯到它腰有点变弯就把它捞起来
OK, wait till the shrimps bend to take them out

0:03:15.976,0:03:17.271
好 倒宽油
OK, pour Kuan You (Broad oil*) 

0:03:20.173,0:03:22.497
放好多油哦
That's a lot of oil

0:03:23.237,0:03:26.358
没得好多得 最多有六七斤
That's not that much, 6 – 7 jin ( 1 jin = 500g) the most 

0:03:26.820,0:03:33.699
啊  虾子才斤多点 油放六七斤
Ah? The shrimps are an only bit over one jin (1 jin= 500g), but you put 6-7 jin oil. 

0:03:34.312,0:03:37.086
这会抓点粉子（淀粉）给它上点粉
Now put a handful of potato starch to mix with the shrimp

0:03:39.121,0:03:41.063
有这个粉子它炸出来就是脆的
The starch makes the shrimps crispy after fried 

0:03:41.491,0:03:42.809
它才粘得上面
It will stick on to the shrimp

0:03:42.994,0:03:43.537
安
Great

0:03:43.583,0:03:45.005
粘在上面炸得泡
The starch makes shrimp's surface bubbly when frying

0:03:45.017,0:03:45.768
哦喔
ohh

0:03:46.369,0:03:48.184
OK 7成油温了
OK, the oil is 70% heated. 

0:03:50.543,0:03:51.757
这样子给它抖下去
Keep it shaky while putting the shrimps down 

0:03:53.872,0:03:55.826
小心哦这个有点爆（油）哦
Be careful this oil is about to jump out

0:04:03.953,0:04:05.375
好了 我们这个虾差不多了
OK We are almost done

0:04:05.375,0:04:06.138
把它捞起来
Take the shrimps out

0:04:11.167,0:04:12.531
然后把这个油沥干净
Now drain the remainders from the oil 

0:04:17.433,0:04:19.410
这个时候我们油就要少加一点了
Now we put less oil into the wok

0:04:21.421,0:04:23.144
锅中加入洋葱、青红辣椒爆香
Then add in onions and peppers to stir-fry 

0:04:24.381,0:04:25.526
把这个弄来给它爆香
After stir-frying for a bit

0:04:25.526,0:04:27.849
爆香加这个（虾） 再加椒盐粉
Add the shrimps and some pepper-salt powder

0:04:28.335,0:04:30.774
最后加点葱葱就可以了
Then add some green onion at the end

0:04:32.323,0:04:33.676
放虾
Put the shrimps in

0:04:34.254,0:04:35.942
椒盐 
Put in pepper-salt mixture

0:05:01.167,0:05:02.184
来 四伯爷尝哈看
Come on, try it uncle 

0:05:02.323,0:05:02.947
试哈看嘛
Let me try

0:05:03.549,0:05:04.289
这个很脆
It's very crispy 

0:05:07.132,0:05:08.947
这个我还咬得动 还是脆的
My teeth can handle this too, and it's very crispy 

0:05:09.063,0:05:12.381
嗯 我们把虾枪去了就不怕
Yea, especially without the sharp edges of the shrimps

0:05:13.456,0:05:13.895
安逸
Nice

0:05:13.988,0:05:15.086
就不怕戳到嘴巴了噶
Won't hurt your mouth again

0:05:15.086,0:05:15.445
嗯
yea

0:05:20.774,0:05:22.057
其实做这个菜很简单 
It's easy to make this dish

0:05:22.057,0:05:25.213
就是唯一一点不好就是要用宽油来炸
The only con is you need Kuan you ( broad oil*) to fry it

0:05:26.115,0:05:28.763
而且炸这个虾子的话 
And after frying shrimps

0:05:29.375,0:05:32.277
这个油炸虾子炸不了几次这个油就会报废
You can't reuse the oil many times

0:05:32.300,0:05:33.583
最多3次就会报废
Three times the most

0:05:34.739,0:05:36.316
四伯爷 炸这个虾子
Uncle, to fry these shrimps 

0:05:36.316,0:05:38.369
炸这个虾子很费油嘎
Needs a lot of oil

0:05:38.809,0:05:41.294
这个油里面要吸收这个虾子味道
The oil will absorb the taste of the shrimp

0:05:42.439,0:05:43.838
炸了这个油
After you fried the shrimps with the oil

0:05:44.369,0:05:45.294
油要变味
The oil will go bad

0:05:45.306,0:05:46.554
嗯 就是油要变味
Yes exactly 

0:05:46.878,0:05:49.132
四伯爷很懂了这个 已经很懂行了
Uncle is very cultured about this 

0:05:51.849,0:05:53.352
你慢慢都要变成行家了
You are becoming professional 

0:05:55.075,0:05:59.930
那些东西日常生活中你都可以试出来的
You can try and learn these things from daily life experience 

0:06:01.526,0:06:06.543
唯一的有点不好就是我炒的那个椒盐粉回潮了
The only con is the pepper-salt powder I made is a bit damped

0:06:07.329,0:06:09.063
没得以前那么香得了
Not as good as before

0:06:10.531,0:06:14.358
所以我们这个椒盐粉的话最好是现炒现用
The best time to use the pepper-salt powder is right after you made it

0:06:14.578,0:06:15.144
嗯
yea

0:06:15.965,0:06:17.398
最好就不要超过半个月
Do not leave it over for half a month 

0:06:17.653,0:06:21.676
因为这个放太久了 四川我们这里比较潮湿
Because this has been made for a while and we have humid weather in Sichuan

0:06:21.745,0:06:24.046
盐都起坨坨了嘎
The salt has been damped

0:06:25.017,0:06:28.034
下次少炒点就是撒 用完了又炒撒
Next time just make less of it, you can always make more later 

0:06:34.843,0:06:36.173
好了 本期视频就到这里
OK this is the end of the video

0:06:40.358,0:06:40.867
接着吃
Let's keep eating
