### ISSUE TITLE
[华农兄弟] 华农兄弟看一下兄弟养的七彩山鸡很漂亮哦抓几只来吃 - https://youtu.be/aDzQw3gCGdU

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1140]
https://youtu.be/aDzQw3gCGdU
<p>&#35270;&#39057;&#21457;&#24067;&#20110; June 8, 2020 at 03:56PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/aDzQw3gCGdU

#华农兄弟：看一下兄弟养的七彩山鸡，很漂亮哦，抓几只来吃
#Huanong Brothers: We have a look at our buddy's pheasants. They're so pretty. We catch some and grill them.

0:00:00.000,0:00:02.860
# 大家好  今天來兄弟家的這個山彩山雞場啊
Hi everyone! Today we come to our buddy's pheasant farm,

0:00:03.280,0:00:04.100
# 來看一下
and have a look around.

0:00:05.000,0:00:06.720
# 兄弟都走了  不知道他跑哪裡去了
My buddy has already left. God knows where he is.

0:00:06.720,0:00:09.000
# 剛剛還打電話還說在在在在  現在就跑了
He just said, "yea, yea, yea, yea, I'm here" on the phone. But now he has run away.

0:00:09.760,0:00:10.800
# 我進去看一下
Let me have a look inside.

0:00:11.560,0:00:13.380
# 防疫區域   閑人免進
Epidemic control area. No unauthorised entry.

0:00:14.880,0:00:17.320
# 跟他說了  他說叫我們可以進
I've talked with him. He said that we can get in.

0:00:18.480,0:00:20.880
# 這消一下毒  這有消毒嗎
We need to be sanitised. Here's the sanitiser.

0:00:27.900,0:00:30.760
# 叫兄弟抓一隻山雞來  兄弟不在
I asked my buddy to catch me a pheasant. But he's not around.

0:00:31.240,0:00:33.020
# 叫他們的工人來抓
So I asked his workers to catch me one.

0:00:34.960,0:00:36.000
# 好多啊  這裡
Really a lot, here.

0:00:51.400,0:00:53.140
# 這些山雞全部都戴了眼鏡
These pheasant are all wearing eye shields,

0:00:53.580,0:00:54.700
# 這它們不要打架
to prevent them from fighting.

0:00:56.140,0:00:57.440
# 它現在就看不到前面
Now they can't see the front.

0:00:58.100,0:01:00.040
# 看不 看不到前面就不會那個
When they can't, can't see the front, they won't, you know,

0:01:00.520,0:01:01.780
# 不會你啄我我啄你
they won't perk each other all the time.

0:01:04.600,0:01:06.560
# 那裡有一條門  這邊也有一條門
There's a door. And here's another door.

0:01:10.140,0:01:11.200
# 你看  這個
Look! These,

0:01:12.180,0:01:15.220
# 這個雞都戴了那個眼鏡的哦  都是後面戴上去的
these pheasants are all wearing that kind of eye shields. They were put on from the back.

0:01:15.460,0:01:16.280
# 這個快掉了
This one is falling off.

0:01:18.320,0:01:19.100
# 還想啄我
You wanna perk me?

0:01:22.560,0:01:24.740
# 它應該看不到  它應該看不到前面
They shouldn't be able, shouldn't be able to see the front.

0:01:29.980,0:01:30.740
# 那麼乖
Good pheasants!

0:01:32.980,0:01:35.920
# 這個會飛的哦這個  一跑出去就抓不到了都
They can fly, you know. It's impossible to catch them once they're outside.

0:01:40.200,0:01:40.980
# 踩著它
It's stepping on it.

0:01:45.440,0:01:46.080
# 你看
Look!

0:01:47.680,0:01:49.840
# 應該可以進去哦  我們進去看一下
I think I can get in. Let's have a look inside.

0:01:56.180,0:01:59.700
# 你看  這一棟 這幾個棚裡面應該有幾千隻
Look! I think there are thousands of pheasants in this lodge, in this couple of sheds

0:01:59.700,0:02:02.060
# 那麼多 他這裡有幾棟哦
So many. He has dozens of lodges here.

0:02:02.440,0:02:06.580
# 究竟多少棟我也不知道  最少  最少有三四十棟  這樣的
I've no ideas how many exactly. But I think there are at least, at least thirty or forty lodges, sort of.

0:02:09.660,0:02:10.900
# 加起來應該有
Together, there should be,

0:02:12.160,0:02:14.560
# 五六萬七八萬都有 七八萬隻啦
fifty, sixty or seventy, or even eighty thousand pheasants, yea, up to eighty thousand.

0:02:16.200,0:02:17.240
# 這一個規模
This scale is,

0:02:18.100,0:02:18.600
# 夠大
huge.

0:02:35.420,0:02:37.600
# 那麼乖的  那麼聽話
What a good, nice and gentle pheasant.

0:02:38.480,0:02:39.820
# 去不去  帶你去
Are you coming with me? I'll take you to,

0:02:40.680,0:02:41.440
# 帶你去那個
take you to, you know,

0:02:42.660,0:02:43.860
# 帶你去  帶你去玩
take you to, take you to have some fun.

0:02:46.300,0:02:48.140
# 有一點濕  剛才下過雨
It's a bit wet. It has just rained.

0:02:53.500,0:02:55.080
# 你看  那屋頂上都站了有
Look! Some are standing on the roof beam there.

0:02:55.320,0:02:56.580
# 它們那麼調皮
They're so naughty.

0:02:57.240,0:02:58.360
# 抓都抓不到它們
It's simply impossible to catch them.

0:03:03.240,0:03:04.580
# 好啦  回去啦回去啦
Alright! Let's go, let's go.

0:03:15.740,0:03:17.980
# 你看  這邊也有  那邊也有
Look! Here are some lodges, and there too,

0:03:18.340,0:03:21.220
# 那後面也有  這邊也有一大片哦
and at our back too, and this side too, the whole area.

0:03:23.620,0:03:25.420
# 將近上萬隻哦  這裡
Here are almost ten thousand pheasants, here.

0:03:26.380,0:03:27.280
# 那麼多
So many

0:04:00.060,0:04:04.240
# 你看  這些都是母的哦 小母雞  那個漂亮一點的就是公的
Look! There are all female, you know, little hens. Those prettier ones are male.

0:04:07.260,0:04:10.260
# 兄弟還搞了另外一個場所哦  比這裡大幾倍哦
My buddy has started another site, which is a few times larger than this one.

0:04:10.800,0:04:13.820
# 上那邊  上次我去看過  但是還沒建成
It's over there. I went there last time, but it was still under construction.

0:04:14.420,0:04:15.860
# 現在也開始在動工啦
Now the construction work has already commenced.

0:04:15.860,0:04:18.420
# 這個七彩山雞  那個肉質很好吃的哦
The pheasant, their meat, the texture of their meat, is really tasty.

0:04:18.880,0:04:20.880
# 上次兄弟送了幾個給我吃了一下
My buddy gave me a couple of them last time.

0:04:20.880,0:04:23.440
# 嘖  搞的我回味無窮  今天又來啦
It's a taste that I can never forget. That's why I'm here again today.

0:04:23.980,0:04:25.000
# 我們再搞一個來
Let's get one more.

0:04:27.920,0:04:29.380
# 兄弟也太客氣啦
My buddy is just too nice to me.

0:04:29.800,0:04:31.080
# 就給了那麼一點給我
He gave me this little bit here.

0:04:35.640,0:04:36.160
# 哎呀
Aya!

0:04:36.620,0:04:37.120
# 可以
Fine!

0:04:39.040,0:04:39.580
# 你看
Look!

0:04:40.680,0:04:41.480
# 殺好啦
It's now ready.

0:04:43.400,0:04:45.160
# 好有肉哇  雞肉
It's really meaty, pheasant meat.

0:04:47.260,0:04:49.980
# 把內臟取一下  然後再放點油鹽腌一下
Let me take out the guts. And then marinate it with some oil and salt.

0:04:50.560,0:04:51.980
# 你看  這個公的哦
Look! This is male.

0:04:52.380,0:04:55.160
# 還有蛋的看到沒有  留起來等一下一人一個
It has balls, see? Leave them here and we can have one each.

0:04:56.080,0:04:57.520
# 我要刮一下它的這個
I need to scratch it, I mean,

0:04:58.520,0:04:59.320
# 割它幾刀
slice it a few times.

0:05:00.160,0:05:00.960
# 更入味
It will be more flavourful.

0:05:04.320,0:05:05.740
# 你看  這個  這個雞
Look! This, this pheasant,

0:05:06.320,0:05:07.480
# 身上都沒有肥肉的哦
has hardly any fat on its body.

0:05:08.500,0:05:10.600
# 有一點點  你看  幾乎都沒有
Perhaps a bit. Look! But almost none.

0:05:14.180,0:05:15.140
# 這個塞回去
I stuff it back inside.

0:05:16.660,0:05:17.440
# 把它腳
Its feet...

0:05:19.680,0:05:20.540
# 拗過來
Twist them

0:05:25.980,0:05:28.220
# 先腌一下它  所以把它
Marinate it first. So I have to,

0:05:28.860,0:05:29.460
# 裹起來
wrap it up.

0:05:32.660,0:05:35.260
# 然後就  這樣把它裹起一團
And then, wrap it up into a ball,

0:05:36.560,0:05:37.280
# 再來燒
then cook it.

0:05:38.460,0:05:39.440
# 絕對美味
Good taste is guaranteed.

0:05:44.080,0:05:46.260
# 好啦  拿一個盤子來把它腌一下
Alright! I take a pot here and marinate it for a while.

0:05:48.480,0:05:49.440
# 切的慢
I chop too slowly.

0:05:51.520,0:05:52.940
# 生薑加大蒜
Ginger with garlic,

0:05:55.300,0:05:56.400
# 放到你身上
onto your body

0:05:58.940,0:06:00.480
# 嗯  再加點料酒
Um! Then put some cooking wine.

0:06:02.840,0:06:03.500
# 還有一點點
There's still a tiny little bit.

0:06:04.900,0:06:05.580
# 夠啦  夠啦
Enough, enough

0:06:06.940,0:06:09.220
# 下次去兄弟家搞幾瓶過來
I'll get a few bottles from my buddy next time.

0:06:11.780,0:06:13.900
# 現在攝影小哥越來越吃辣椒啦
Now Mr. Cameraman can have more and more chilli.

0:06:15.160,0:06:16.300
# 口味越來越重
He's becoming a fanatic of intense flavour.

0:06:17.920,0:06:18.980
# 放點辣椒下去
Put some chilli.

0:06:24.020,0:06:24.560
# 醬油
Soy sauce

0:06:29.240,0:06:31.200
# 加點油下去 如果不加油的話
Let me put some oil. Without oil,

0:06:31.740,0:06:32.980
# 到時候會燒焦的
it would get burnt.

0:06:36.560,0:06:37.140
# 鹽呢
Where's the salt?

0:06:38.200,0:06:38.700
# 加點
Put some,

0:06:40.880,0:06:41.660
# 加點鹽
put some salt.

0:06:44.560,0:06:45.380
# 差不多夠啦
It should be enough.

0:06:46.340,0:06:47.720
# 就是那麼小的雞
It's only a small pheasant.

0:06:50.540,0:06:51.640
# 給它搓一搓
Let me rub it over the body.

0:07:01.840,0:07:02.580
# 讓這個
Let it,

0:07:03.120,0:07:04.260
# 讓這個薑汁
let the ginger juice,

0:07:05.120,0:07:06.000
# 在他身上
to be sprayed evenly,

0:07:08.640,0:07:09.760
# 塗抹均勻
on its body.

0:07:12.220,0:07:13.080
# 按一下摩
Give it a massage

0:07:15.520,0:07:17.460
# 這樣肉質很好吃的哦
Then the texture would be really wonderful.

0:07:18.740,0:07:20.480
# 養了已經超過8個月啦
My buddy has been raising this pheasant for more than eight months.

0:07:22.160,0:07:24.000
# 等一下我們做個叫花雞
Let's make a Beggar's Pheasant in a while.

0:07:26.860,0:07:28.200
# 去搞點荷葉回來
Let's go and fetch some lotus leaves.

0:07:31.240,0:07:33.820
# 等下我去  叫兄弟家拿幾個香菇過來
I'm gonna, gonna ask my buddy bring me some shiitake mushrooms from his place.

0:07:34.520,0:07:35.380
# 我家的香菇
My mushrooms,

0:07:36.100,0:07:36.880
# 不在這裡
are not here.

0:07:41.980,0:07:43.840
# 裹起來  用荷葉把它裹起來
Wrap it up, wrap it up with lotus leaves,

0:07:44.420,0:07:45.500
# 然後再來烤
and then we can grill it.

0:07:46.820,0:07:48.380
# 味道一定很鮮美
It must be very flavourful and savoury.

0:07:48.660,0:07:51.480
# 好啦  把它放回  放到桌子上去
Alright! Let me put it back, onto the table.

0:07:52.260,0:07:54.500
# 等下被這個小狗給吃啦
I can't let the doggies take it.

0:07:55.080,0:07:56.000
# 那虧大啦
It would be too bad.

0:07:58.300,0:07:59.940
# 你看  這是我兄弟家哦
Look! This is my buddy's home.

0:08:00.580,0:08:02.360
# 那有狗  有條狗守在那裡
There's a dog. A dog is guarding the place.

0:08:05.160,0:08:07.040
# 他家的荷葉就是這裡
His lotus leaves are right here.

0:08:11.740,0:08:13.120
# 哎喲  好兇哦
Aya! So fierce

0:08:14.800,0:08:16.600
# 你看  這狗擋住道路啦
Look! The dog is blocking the way.

0:08:17.140,0:08:18.000
# 好兇的
So fierce

0:08:19.900,0:08:21.240
# 好狗  好狗
Good dog, good dog!

0:08:22.440,0:08:24.280
# 到那邊去拗  不著急喲
I'm picking on that side. No hurry,

0:08:25.380,0:08:26.380
# 這邊也有啊
Here are also some lotus leaves.

0:08:42.040,0:08:43.700
# 好啦  夠啦  不要摘那麼多
Alright! Enough! Not too many

0:08:44.140,0:08:46.460
# 我摯穹點那個黃泥回來 就在那裡
I'm gonna dig some mud. It's right over there,

0:08:46.900,0:08:47.680
# 很近的
not far at all.

0:08:54.200,0:08:55.520
# 挖一點黃泥
Dig some mud.

0:08:57.040,0:08:57.920
# 一鋤頭
Put down the hoe,

0:08:58.880,0:08:59.780
# 可以挖好多
and a lot of mud comes down.

0:09:03.140,0:09:04.140
# 好啦 可以啦
Alright! It's enough.

0:09:04.900,0:09:06.600
# 一下子搞一大盆
A whole pot of mud is here in seconds.

0:09:07.700,0:09:09.200
# 哎喲 哎喲  好重
Ayo, ayo! So heavy!

0:09:15.440,0:09:16.220
# 這個黃泥
The mud,

0:09:16.920,0:09:17.520
# 很新
is so fresh,

0:09:18.940,0:09:20.680
# 你看  這個黃泥很新鮮哦
Look! The mud is really fresh, isn't it?

0:09:22.580,0:09:24.260
# 這個黃泥加點水
Put some water, into the mud.

0:09:24.760,0:09:26.760
# 要把它攪拌  攪拌均勻
I need to mix it, mix it well.

0:09:27.140,0:09:28.140
# 然後要把它
And then I'll need to,

0:09:28.560,0:09:29.180
# 搞成
make it,

0:09:32.100,0:09:33.800
# 搞成那個  黏笘的那一種啊
make it into, something like, sticky.

0:09:37.860,0:09:38.620
# 等下就
I'm gonna,

0:09:39.280,0:09:40.520
# 把你給煮啦
have you cooked very soon.

0:10:04.720,0:10:06.160
# 這裡還有五六隻雞喲
Here are still half a dozen of pheasants.

0:10:07.200,0:10:07.940
# 放在這裡
I leave them here,

0:10:08.640,0:10:09.520
# 慢慢烤
and grill them all,

0:10:10.740,0:10:11.600
# 一天烤一個
 gradually, one per day.

0:10:17.300,0:10:17.800
# 好啦
Alright!

0:10:18.440,0:10:20.980
# 可以啦  等下把這黃泥塗上去就好啦
Alright! Then I only need to paste the mud in a while.

0:10:21.600,0:10:22.420
# 先洗個手
Let me wash my hands first,

0:10:23.360,0:10:24.420
# 把那雞裹好來
and then wrap up the pheasant.

0:10:36.720,0:10:37.920
# 把它放到這裡來
Put it here.

0:10:39.260,0:10:40.300
# 把這個香菇
Stuff the shiitake mushrooms,

0:10:40.780,0:10:41.740
# 塞到它
into its,

0:10:42.520,0:10:43.260
# 肚子裡面
its belly.

0:10:48.680,0:10:50.160
# 然後  這個醬汁
And then, here's the sauce

0:10:50.980,0:10:51.860
# 不要浪費
Don't waste it.

0:10:53.200,0:10:53.980
# 倒進去
Pour it inside.

0:11:04.540,0:11:05.520
# 裹著它
Wrap it up.

0:11:10.360,0:11:11.340
# 這樣就
Then it's,

0:11:13.940,0:11:15.980
# 就靚哦  在[SIC]裹一層
really beautiful. One more layer

0:11:34.440,0:11:35.840
# 要把它壓緊一點
I need to press it tight.

0:11:37.420,0:11:38.980
# 要結實一點
It needs to be firm.

0:11:40.320,0:11:42.340
# 這樣它才跑不了
Only then can it never run away.

0:11:54.080,0:11:55.080
# 嗯  好啦
Um! Alright!

0:11:55.840,0:11:57.200
# 我們裹點黃泥上去
Let's wrap it with some mud.

0:11:59.260,0:12:00.300
# 去  看一下 (註︰沒有原字幕)
Alright! Let's go and see what's next.

0:12:05.200,0:12:08.980
# 你看  外面下雨  沒苏法啦  只能在家裡烤
Look! It's raining outside and we have no choice but grilling it at home.

0:12:14.100,0:12:15.140
# 我要先把它那個
I'm gonna put the,

0:12:16.560,0:12:17.860
# 雞放到這上面去
pheasant here on top first.

0:12:21.440,0:12:22.960
# 這底下要鋪層泥喲
There needs to be a layer of mud at the bottom.

0:12:24.600,0:12:26.800
# 鋪層泥等下一燒的話就剛剛好
A layer of mud will make it just perfect once we start grilling.

0:12:37.000,0:12:37.620
# 好啦
Alright!

0:12:38.120,0:12:40.220
# 把這個雞放到這裡來
Let me put the pheasant here.

0:12:43.760,0:12:45.460
# 慢慢的把這個泥粘上去
Then I paste the mud onto it bit by bit.

0:12:46.100,0:12:46.920
# 這樣就不用
Then I don't need to,

0:12:47.620,0:12:48.760
# 不用動啦
I don't need to move it.

0:12:59.520,0:13:01.820
# 要不要給你玩  胡韦汝來
You wanna play with it? Come, Hu Weiru!

0:13:02.420,0:13:03.740
# 做那個  你看
I can make a, look,

0:13:05.200,0:13:06.620
# 做這個糍粑哦  你看
make this mud cake, look!

0:13:07.380,0:13:08.660
# 那麼好玩 你不玩
It's so much fun! Why don't you want it?

0:13:10.920,0:13:13.160
# 還小的時候我們玩具都沒有  就玩這個
We didn't even have a single piece of toy when we were kids. And this was our toy.

0:13:22.040,0:13:24.420
# 那個袋子掉下去啦
That bag fell onto the ground.

0:13:24.420,0:13:25.260
# 沒事
No worries

0:13:25.780,0:13:29.740
# 是它看到  看到我們把它的同  同伴
It's because, it sees that we're, turning its companion,

0:13:30.700,0:13:31.980
# 變成了一個蛋
into an egg,

0:13:33.000,0:13:34.540
# 所以它就怕
That's why it's scared.

0:13:36.660,0:13:38.780
# 好啦  明天來  明天就輪到它啦
Alright! Tomorrow, tomorrow will be its turn.

0:13:41.100,0:13:41.720
# 你看
Look!

0:13:42.120,0:13:43.340
# 把它搞成一個蛋一樣
I've turned it into something like an egg.

0:13:45.860,0:13:46.740
# 開始點火
Let's start the fire.

0:14:35.380,0:14:36.940
# 它們的炭都燒著啦
Their charcoal has been lighted.

0:14:59.220,0:15:00.420
# 這下雨天
In a rainy day,

0:15:01.000,0:15:03.120
# 太難 這個火太難點啦
it's super hard, super hard to set a fire.

0:15:03.180,0:15:05.380
# 直接抱了把稻草下來
So I've taken some straw down here right away.

0:15:26.280,0:15:27.820
# 現在多加點炭下去
Now I put a bit more charcoal.

0:15:31.920,0:15:33.220
# 現在又下雨啦
It rains again now.

0:15:33.880,0:15:36.940
# 天天下雨  搞很河邊去都去不了
It rains every day. There's no way to go to the riverside.

0:15:38.540,0:15:39.560
# 逼在家裡
We can only stay at home.

0:15:40.080,0:15:42.700
# 在河邊的話我們大火來燒它
We could grill it with a strong fire if we could go to the riverside.

0:15:44.920,0:15:45.440
# 這也
Anyway,

0:15:46.700,0:15:47.700
# 也沒辦法
we have no choice.

0:15:48.640,0:15:50.640
# 你看  這個天又出太陽啦
Look! The sun is shinning in the sky once again.

0:15:50.800,0:15:53.620
# 剛剛還下大雨  你看  等下那片烏雲又飛過來啦
It was still raining heavily a few moments ago. Look! That dark cloud will be coming here in a while.

0:15:54.100,0:15:56.600
# 又啪啦一降  降  降一個大水下來
Then "pala"! The, the rain pours again.

0:15:57.600,0:15:59.160
# 啊  看一下  這個好啦
Ah! Let's have a look. It's alright now.

0:16:00.040,0:16:01.540
# 你看  這個  差不多快好了哦
Look! This is, almost done, I suupose.

0:16:01.860,0:16:02.460
# 那麼多
So much,

0:16:02.760,0:16:05.120
# 四  四面八方都是炭  圍著它
the charcoal from every, every direction, is surrounding it.

0:16:09.920,0:16:11.180
# 在[SIC]煮一個小時
One more hour

0:16:14.500,0:16:15.320
# 全是狗
All are dogs

0:16:16.600,0:16:18.760
# 就小黑有名字  其它都沒名字
Only Blacky has a name. All others are nameless.

0:16:25.400,0:16:27.780
# 你看  現在都紅啦  
Look! It's red now, wa!

0:16:28.740,0:16:29.740
# 應該熟啦
It should be done now.

0:16:32.680,0:16:33.680
# 拿這個鋤頭來
I take this hoe.

0:16:48.480,0:16:50.260
# 哇  你看  終於搞起來啦
Wa! Look! We pick it up finally.

0:16:50.900,0:16:51.780
# 上上面去
Let's go up there,

0:16:52.200,0:16:53.500
# 上面去看一下熟了沒有
go up there and see if it's done.

0:17:04.520,0:17:05.540
# 還熟啦
It's done!

0:17:06.340,0:17:07.580
# 哎呦  下大雨啦
Ayo! The rain pours again.

0:17:08.420,0:17:10.720
# 哎呀  別  別  別那個
Aya! Don't, don't, don't, I mean,

0:17:11.980,0:17:13.340
# 別沖走就麻煩啦
don't wash it away. It would be too bad.

0:17:19.600,0:17:21.480
# 你看  這荷葉都燒焦啦
Look! Even the lotus leaves are burnt.

0:17:24.160,0:17:25.060
# 哎呀
Aya!

0:17:26.100,0:17:27.380
# 看上去就好吃
The appearance is already confirming the taste.

0:17:28.660,0:17:30.080
# 看上去就好吃
The appearance is already confirming the taste.

0:17:32.220,0:17:33.700
# 輕輕的撕開
Tear it open lightly.

0:17:34.440,0:17:35.500
# 撕開裡面
Tear the inside open.

0:17:40.720,0:17:41.800
# 好香啊
It smells so good!

0:17:44.960,0:17:45.900
# 哎喲
Ayo!

0:17:51.560,0:17:52.260
# 有刀
Here's a knife.

0:17:56.100,0:17:57.920
# 嗯  熟啦
Um! It's done!

0:18:01.340,0:18:03.460
# 熟啦 熟啦  熟啦  全部熟啦
Done, done, done, well done.

0:18:05.140,0:18:05.840
# 嗯
Um!

0:18:07.640,0:18:08.400
# 可以喲
It's not bad!

0:18:08.680,0:18:10.080
# 嘿 等一下來
Hey! A moment!

0:18:11.360,0:18:13.200
# 等一下來  等我吃完再說
A moment! Let me finish first.

0:18:15.600,0:18:17.160
# 剛才不是還有塊骨頭嗎
Didn't you get a piece of bone just now?

0:18:18.440,0:18:20.080
# 全部狗都來啦
All dogs are coming here.

0:18:21.420,0:18:23.020
# 它們在排隊  等一下哦
They're queuing up. A moment, okay?

0:18:39.700,0:18:40.900
# 這還那麼多肉
There's still plenty of meat.

0:18:45.660,0:18:46.580
# 這還有一個雞腿
Here's still a leg.

0:18:48.240,0:18:49.640
# 等一下留給攝影小哥吃
I'll leave for Mr. Cameraman in a while.

0:18:51.360,0:18:53.160
# 攝影小哥不喜歡吃這樣的
Mr. Cameraman doesn't like this kind of stuff.

0:18:54.540,0:18:55.460
# 他喜歡吃那個
He likes the...

0:18:56.120,0:18:57.380
# 他喜歡吃這兩個蛋
He likes these two balls.

0:19:00.020,0:19:00.740
# 哪裡去啦
Where are they?

0:19:03.640,0:19:04.260
# 在這裡
Here

0:19:12.660,0:19:13.680
# 可以喲
It's not bad.

0:19:15.600,0:19:16.820
# 一點怪怪的味道
It tastes a bit funny.

0:19:18.400,0:19:19.860
# 額  小狗慢慢吃
Eh! Doggy! No rush!

0:19:20.240,0:19:20.980
# 還有一個
One more

0:19:25.520,0:19:27.300
# 雞腿不好吃  這個才好吃
It tastes much better than the leg, which doesn't taste good at all.

0:19:29.780,0:19:31.780
# 哎  算啦  留給攝影小哥補一補
Ay! Forget. I leave it for Mr. Cameraman to enhance his power.

0:19:36.700,0:19:37.900
# 沒吃過癮它們
They're still craving.

0:19:43.400,0:19:45.080
# 留一個雞眼給攝影小哥就行啦
Leaving a leg to Mr. Cameraman is everything that's needed.

0:19:56.420,0:19:57.100
# 給你吃
It's yours.

0:20:03.960,0:20:04.520
# 好啦
Alright!

0:20:06.000,0:20:06.880
# 今天的視頻
The video,

0:20:07.500,0:20:08.000
# 就到
ends,

0:20:08.520,0:20:09.100
# 這裡啦
here.

**Comment by vincenthychow** [comment]
已發佈
