### ISSUE TITLE
【美食作家王刚】酸辣白菜 - https://youtu.be/ehBjgCBmSt4

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1150]
**视频链接**：https://youtu.be/ehBjgCBmSt4

视频时长4:34，预计发布时间为北京时间6月12日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“酸辣大白菜”的家常做法，轻松炒出金边，口感爽脆多汁

简介
大家好，今天和大家分享一道“酸辣大白菜”，本次使用的是家常做法，白菜手撕成小片，停火调味，家常味十足，而后厨专业做法会不太一样，但重点都是不可以使白菜过早出水导致不香，最后爆炒炝出锅气使白菜形成“金边”，如果想学后厨专业做法的朋友可以点击链接：酸辣大白菜 https://www.youtube.com/watch?v=RY-KAQQB4ik&vl=zh-Hans

字幕
0:00:00.422,0:00:01.150
哈喽 大家好

0:00:01.457,0:00:03.720
这次我伯爷买了一个白菜

0:00:04.445,0:00:05.767
说让我做个白菜给他吃

0:00:06.423,0:00:09.794
我伯爷说农村的柴火灶炒不出那种效果

0:00:10.013,0:00:12.118
所以让我用这个炒一下

0:00:12.145,0:00:13.202
炒个酸辣大白菜

0:00:14.514,0:00:15.708
一哈呀 四伯爷这

0:00:15.717,0:00:16.492
一哈嘛

0:00:17.230,0:00:19.845
一哈炒有点多不多了

0:00:20.492,0:00:25.594
本来这个白菜我拿回来做成2顿吃的 给你说嘛

0:00:26.542,0:00:27.881
中间的那个芯芯弄来煮汤

0:00:28.419,0:00:29.813
这个边边就弄来炒来吃

0:00:31.343,0:00:32.364
撕碎点

0:00:35.088,0:00:36.182
大块大块的都可以

0:00:36.227,0:00:38.697
大块大块的吃起卡喉咙的

0:00:39.362,0:00:43.544
所以趁人还没老赶紧多学点做点好吃的先吃了再说

0:00:45.658,0:00:47.088
我们这个白菜撕出来了 

0:00:47.161,0:00:49.020
 洗一下 一定要把水份沥干了再炒

0:00:49.439,0:00:53.476
要不然的话这个里面有水炒出来了水哒哒的

0:00:53.476,0:00:55.025
水汤汤多得很

0:00:56.519,0:00:57.776
那跟煮的白菜汤一样

0:00:58.369,0:00:58.715
是

0:00:59.671,0:01:02.168
好 下面准备一点干辣椒

0:01:03.599,0:01:04.929
剪一点干辣椒

0:01:05.521,0:01:06.514
可以多剪2个嘛

0:01:07.416,0:01:08.519
多剪2个那样子就

0:01:09.384,0:01:10.441
这个海椒不辣

0:01:11.790,0:01:13.722
我们今天用的这个辣椒是子弹头

0:01:14.842,0:01:18.742
颜色好看 就是辣度的话一般般

0:01:19.079,0:01:20.109
辣度就不够

0:01:21.667,0:01:22.624
好 差不多了

0:01:22.624,0:01:23.189
够了够了

0:01:23.398,0:01:23.726
够了

0:01:24.276,0:01:26.016
然后再抓几颗青花椒下去

0:01:28.564,0:01:29.011
可以了嘎

0:01:29.239,0:01:29.539
可以

0:01:31.061,0:01:34.469
一般外地人的话就不要加青花椒你们吃不惯的话

0:01:34.760,0:01:37.959
花椒加进去又小颗一下子就吃到嘴里去

0:01:44.273,0:01:45.011
就差不多了嘛

0:01:45.020,0:01:48.574
就是放点蒜 干海椒 花椒 再加白菜

0:01:48.719,0:01:49.138
要的啊

0:01:49.202,0:01:50.697
再加点陈醋

0:01:51.107,0:01:51.726
要得要得

0:01:51.726,0:01:52.027
要得

0:01:52.218,0:01:53.266
可以了 走嘛

0:01:55.070,0:01:57.567
好啦 我们炒这个大白菜啊

0:01:58.013,0:01:59.626
一定要把这个锅烧得很烫

0:02:00.218,0:02:01.448
然后把油温烧高一点

0:02:02.751,0:02:04.482
这个火候要掌握好哦

0:02:04.674,0:02:05.120
啊

0:02:05.412,0:02:08.646
不要像漆二娃那样子炒糊了

0:02:09.658,0:02:10.578
蒜

0:02:10.870,0:02:11.945
辣椒

0:02:13.931,0:02:15.435
白菜

0:02:15.690,0:02:16.583
然后开大火

0:02:26.533,0:02:32.309
盐 白糖 陈醋 酱油

0:02:41.740,0:02:42.405
吃哈看嘛

0:02:42.842,0:02:43.289
尝哈看

0:02:46.113,0:02:49.514
这个黑是加的陈醋的颜色 还有酱油

0:02:49.514,0:02:51.462
这个不是炒黑的

0:02:52.938,0:02:53.293
怎么样 

0:02:53.576,0:02:53.959
可以

0:02:55.272,0:02:57.628
我们炒这个白菜就是油稍微多一点

0:02:57.776,0:02:59.027
然后火大一点

0:02:59.469,0:03:00.324
直接翻炒

0:03:00.824,0:03:04.079
炒到8成熟开始调味

0:03:04.913,0:03:07.233
然后这个盐要比平时炒菜多一些

0:03:07.233,0:03:08.193
因为加了醋

0:03:09.220,0:03:11.459
醋会抵消一部分的咸味

0:03:12.093,0:03:14.478
然后调盐味一定要最后面来

0:03:14.502,0:03:17.316
如果太早放盐下去这个白菜会出水

0:03:17.760,0:03:19.021
然后就不脆了就软了

0:03:19.498,0:03:21.236
现在我们这个白菜是脆的 很脆

0:03:23.565,0:03:23.961
好吃 

0:03:24.494,0:03:24.826
嗯

0:03:26.273,0:03:29.102
我们这个唯一的不好就是油稍微要重一些

0:03:29.102,0:03:30.897
如果不重的话就不能够开大火

0:03:31.293,0:03:31.867
肯定的撒

0:03:31.867,0:03:33.637
油不重开大火炒就要糊

0:03:34.866,0:03:36.903
不但要糊 那个味道也不好

0:03:37.299,0:03:37.720
嗯

0:03:38.577,0:03:41.875
我这次用的火候是用的中大火

0:03:42.352,0:03:44.478
油的话稍微重一点点

0:03:45.060,0:03:47.267
然后前期就是放下去翻炒翻炒

0:03:48.892,0:03:50.363
你不要手软 一定要开大火

0:03:53.266,0:03:56.418
漆二娃炒菜她手上没得力的翻炒都

0:03:57.041,0:03:57.938
翻炒都成问题嘎

0:03:57.938,0:04:03.540
她手脚慢了 所以说有些东西炒久了炒糊了安

0:04:03.831,0:04:04.228
嗯

0:04:05.715,0:04:07.219
酸辣大白菜一定要火够大

0:04:08.722,0:04:11.552
还有包菜也是跟这个原理差不多

0:04:11.875,0:04:16.006
就是不能加水 炒白菜记住一定不能焯水

0:04:16.475,0:04:19.280
焯了水的白菜炒起就是要

0:04:19.531,0:04:20.088
不好吃

0:04:20.355,0:04:21.382
水咂砸的

0:04:21.455,0:04:23.354
水汪汪的跟煮的白菜汤一样

0:04:23.557,0:04:24.422
啊 就是

0:04:25.594,0:04:26.839
好了本期视频就到这里

0:04:28.278,0:04:28.601
拜拜

0:04:31.148,0:04:31.964
下饭撒 这个

0:04:32.223,0:04:32.675
可以


```

**Comment by archerdominique** [comment]
bot, please upload
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“酸辣大白菜”的家常做法，轻松炒出金边，口感爽脆多汁
Master Chef share with you: home-made, crunchy and juicy "Sour-and-Spicy Napa Cabbage"

简介
大家好，今天和大家分享一道“酸辣大白菜”，本次使用的是家常做法，白菜手撕成小片，停火调味，家常味十足，而后厨专业做法会不太一样，但重点都是不可以使白菜过早出水导致不香，最后爆炒炝出锅气使白菜形成“金边”，如果想学后厨专业做法的朋友可以点击链接：酸辣大白菜 https://www.youtube.com/watch?v=RY-KAQQB4ik&vl=zh-Hans
Hi guys, today I'm gonna share with you the homemade "Sour-and-Spicy Nappa Cabbage". Use your hand to tear the cabbage into small pieces and season it after cooking. It taste just like home! The professional or restaurant way is different, but the point is the same - in order to enhance its aroma, you need to keep the cabbage fluid from flowing out too early. At last stir and fry on high heat until the smoke comes out and the cabbage leaves get a golden rim of sauce. If you wanna learn the professional restaurant way, check the link:https://www.youtube.com/watch?v=RY-KAQQB4ik&vl=zh-Hans

字幕
0:00:00.422,0:00:01.150
哈喽 大家好
Hello guys

0:00:01.457,0:00:03.720
这次我伯爷买了一个白菜
This time my uncle has bought a napa cabbage

0:00:04.445,0:00:05.767
说让我做个白菜给他吃
He asked me to cook it for him

0:00:06.423,0:00:09.794
我伯爷说农村的柴火灶炒不出那种效果
But he said that the firewood stove in countryside cannot get the right taste

0:00:10.013,0:00:12.118
所以让我用这个炒一下
So he wants me to cook with this stove

0:00:12.145,0:00:13.202
炒个酸辣大白菜
To stir and fry a "Sour-and-Spicy Napa Cabbage"

0:00:14.514,0:00:15.708
一哈呀 四伯爷这
All in one dish, uncle?

0:00:15.717,0:00:16.492
一哈嘛
Together

0:00:17.230,0:00:19.845
一哈炒有点多不多了
Will it not be too much?

0:00:20.492,0:00:25.594
本来这个白菜我拿回来做成2顿吃的 给你说嘛
I took it back for two meals, (给你说嘛是在说啥?)

0:00:26.542,0:00:27.881
中间的那个芯芯弄来煮汤
Its stem for cooking soup

0:00:28.419,0:00:29.813
这个边边就弄来炒来吃
And leaves for stir-frying

0:00:31.343,0:00:32.364
撕碎点
Smaller pieces

0:00:35.088,0:00:36.182
大块大块的都可以
It will do with larger ons

0:00:36.227,0:00:38.697
大块大块的吃起卡喉咙的
Larger pieces would stuck in by throat

0:00:39.362,0:00:43.544
所以趁人还没老赶紧多学点做点好吃的先吃了再说
So take the time when you are not too old to learn and cook more tasty stuff. Enjoy the food first!

0:00:45.658,0:00:47.088
我们这个白菜撕出来了 
We've just finished preparing the cabbage

0:00:47.161,0:00:49.020
 洗一下 一定要把水份沥干了再炒
Wash it a while. The water has to be completely removed before cooking

0:00:49.439,0:00:53.476
要不然的话这个里面有水炒出来了水哒哒的
Otherwise with the fluid and water the dish would become too watery

0:00:53.476,0:00:55.025
水汤汤多得很
Water, fluid, too much in it

0:00:56.519,0:00:57.776
那跟煮的白菜汤一样
Like napa cabbage soup

0:00:58.369,0:00:58.715
是
Indeed

0:00:59.671,0:01:02.168
好 下面准备一点干辣椒
Ok, next prepare some dried chilli pepper

0:01:03.599,0:01:04.929
剪一点干辣椒
cut a few dried chilli pepepr

0:01:05.521,0:01:06.514
可以多剪2个嘛
You will cut 2 more, won't you?

0:01:07.416,0:01:08.519
多剪2个那样子就
2 more then

0:01:09.384,0:01:10.441
这个海椒不辣
The chilli pepper is not really spicy

0:01:11.790,0:01:13.722
我们今天用的这个辣椒是子弹头
Today we use the chilli called "Zidantou Chilli Pepper" (lit. bullet-head chilli pepepr)

0:01:14.842,0:01:18.742
颜色好看 就是辣度的话一般般
It has beautiful colour, but the spicy taste is not very strong

0:01:19.079,0:01:20.109
辣度就不够
It is not spicy enough

0:01:21.667,0:01:22.624
好 差不多了
Okay, almsot there

0:01:22.624,0:01:23.189
够了够了
Enough, enough

0:01:23.398,0:01:23.726
够了
Good

0:01:24.276,0:01:26.016
然后再抓几颗青花椒下去
Then grab a few green Sichuan peppercorns

0:01:28.564,0:01:29.011
可以了嘎
Okay?

0:01:29.239,0:01:29.539
可以
Ok

0:01:31.061,0:01:34.469
一般外地人的话就不要加青花椒你们吃不惯的话
Normally if non-local don't really eat green peppercorns you don't need to put them in

0:01:34.760,0:01:37.959
花椒加进去又小颗一下子就吃到嘴里去
Peppercorns are so small and they slip into your mouth

0:01:44.273,0:01:45.011
就差不多了嘛
Almost done

0:01:45.020,0:01:48.574
就是放点蒜 干海椒 花椒 再加白菜
Just some garlic, chilli peppers, peppercorns, and then drop in the napa cabbage

0:01:48.719,0:01:49.138
要的啊
Good

0:01:49.202,0:01:50.697
再加点陈醋
And some vinegar

0:01:51.107,0:01:51.726
要得要得
Nice!

0:01:51.726,0:01:52.027
要得
Nice

0:01:52.218,0:01:53.266
可以了 走嘛
Okay, let's go

0:01:55.070,0:01:57.567
好啦 我们炒这个大白菜啊
Ok, now we stir and fry this napa cabbage

0:01:58.013,0:01:59.626
一定要把这个锅烧得很烫
You must heat this wok very really scalding (我不太确定用词？

0:02:00.218,0:02:01.448
然后把油温烧高一点
And keep a higher oil temperature

0:02:02.751,0:02:04.482
这个火候要掌握好哦
You shall control the heat well

0:02:04.674,0:02:05.120
啊
Ahm

0:02:05.412,0:02:08.646
不要像漆二娃那样子炒糊了
Don't overcook it like Qi Erwa

0:02:09.658,0:02:10.578
蒜
Garlic

0:02:10.870,0:02:11.945
辣椒
Pepper

0:02:13.931,0:02:15.435
白菜
and napa cabbage

0:02:15.690,0:02:16.583
然后开大火
Turn to high heat

0:02:26.533,0:02:32.309
盐 白糖 陈醋 酱油
Salt, sugar, vinegar, soy sauce

0:02:41.740,0:02:42.405
吃哈看嘛
I'll have a try

0:02:42.842,0:02:43.289
尝哈看
help yourself

0:02:46.113,0:02:49.514
这个黑是加的陈醋的颜色 还有酱油
The dark bit is the colour of vinegar, and soy sauce as well

0:02:49.514,0:02:51.462
这个不是炒黑的
Not because it's overcooked

0:02:52.938,0:02:53.293
怎么样 
How is it?

0:02:53.576,0:02:53.959
可以
Nice!

0:02:55.272,0:02:57.628
我们炒这个白菜就是油稍微多一点
We cook this napa cabbage, it needs a bit more oil

0:02:57.776,0:02:59.027
然后火大一点
and the heat higher

0:02:59.469,0:03:00.324
直接翻炒
Head straight to stir-frying

0:03:00.824,0:03:04.079
炒到8成熟开始调味
When it's 80% cooked, we can start seasoning

0:03:04.913,0:03:07.233
然后这个盐要比平时炒菜多一些
And use a bit more salt than usual

0:03:07.233,0:03:08.193
因为加了醋
because of the vinegar

0:03:09.220,0:03:11.459
醋会抵消一部分的咸味
will counter some taste of salt

0:03:12.093,0:03:14.478
然后调盐味一定要最后面来
Salt must be added at last

0:03:14.502,0:03:17.316
如果太早放盐下去这个白菜会出水
If it's put in too early the cabbage fluid would flow out

0:03:17.760,0:03:19.021
然后就不脆了就软了
And the leaves are not crunchy anymore, they become soft

0:03:19.498,0:03:21.236
现在我们这个白菜是脆的 很脆
Now our cabbage is, very crunchy

0:03:23.565,0:03:23.961
好吃 
Delicious

0:03:24.494,0:03:24.826
嗯
Hm

0:03:26.273,0:03:29.102
我们这个唯一的不好就是油稍微要重一些
The only shortcoming of this dish, the oil is a bit "broad"

0:03:29.102,0:03:30.897
如果不重的话就不能够开大火
But if you don't have enough oil, you can't get the high heat

0:03:31.293,0:03:31.867
肯定的撒
Of course

0:03:31.867,0:03:33.637
油不重开大火炒就要糊
If the oil is not enough, stir-frying in high heat will burn the cabbage

0:03:34.866,0:03:36.903
不但要糊 那个味道也不好
Not only is it burned, but its taste is spoiled

0:03:37.299,0:03:37.720
嗯
Um

0:03:38.577,0:03:41.875
我这次用的火候是用的中大火
I used a medium-high heat this time

0:03:42.352,0:03:44.478
油的话稍微重一点点
The oil is just a bit "broader"

0:03:45.060,0:03:47.267
然后前期就是放下去翻炒翻炒
And the first stage is just, drop in the cabbage, stir and fry

0:03:48.892,0:03:50.363
你不要手软 一定要开大火
Don't be hesitate, the high heat is a must

0:03:53.266,0:03:56.418
漆二娃炒菜她手上没得力的翻炒都
Qi Erwa's cooking, her arms are not so strong that the stir-frying

0:03:57.041,0:03:57.938
翻炒都成问题嘎
she has some problems in stir-frying

0:03:57.938,0:04:03.540
她手脚慢了 所以说有些东西炒久了炒糊了安
She's sometimes less deft, and things are cooked too long and burned

0:04:03.831,0:04:04.228
嗯
Um

0:04:05.715,0:04:07.219
酸辣大白菜一定要火够大
Sour-and-Spicy napa cabbage, the heat has to be high enough

0:04:08.722,0:04:11.552
还有包菜也是跟这个原理差不多
And cabbage, it's the same way

0:04:11.875,0:04:16.006
就是不能加水 炒白菜记住一定不能焯水
The only thing is, you must not put any water in it. No need to parboil the cabbage when you're gonna stir and fry it

0:04:16.475,0:04:19.280
焯了水的白菜炒起就是要
Parboiled cabbage in stir-frying dish

0:04:19.531,0:04:20.088
不好吃
It's just not tasty

0:04:20.355,0:04:21.382
水咂砸的
watery and mashy

0:04:21.455,0:04:23.354
水汪汪的跟煮的白菜汤一样
like cabbage stew

0:04:23.557,0:04:24.422
啊 就是
Ah, indeed

0:04:25.594,0:04:26.839
好了本期视频就到这里
Okay, that's all for today's video

0:04:28.278,0:04:28.601
拜拜
Bye!

0:04:31.148,0:04:31.964
下饭撒 这个
Appetite-arousing, this dish

0:04:32.223,0:04:32.675
可以
Nice
