### ISSUE TITLE
[雪鱼] 粉蒸肉 - https://youtu.be/2ZoWfpxxThI

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#1152]
**视频链接**：https://youtu.be/2ZoWfpxxThI

视频时长：6min
发布时间：6月10日 20:00

# 请翻译以下全部内容

字幕
虽然说听粉蒸肉的名字已经很久了
但是尝它的味道还是头一次
还是满心的期待呀
陕西 西安
我要个大份的（粉蒸肉）带走
大份多少钱
23元
这是粉蒸肉的精华-肥油
这一盆的牛肉 切的都是这么大块的
这开始加入调味的料汁了
这个粉蒸肉是用面粉做的
有的地方使用米粉做的
（用的粉是不同点）
搅拌均匀 然后就可以准备上笼了
现在是盖了一层的肥肉
蒸熟后 口感会更加滑润 味道会更香
现在是六笼 待会蒸2个小时就可以吃了
这个粉蒸肉就是传统的 西安回坊的宵夜食品
以前售卖时候 把灯点亮了才卖这个东西（天黑时候）
咱这叫西安回坊的宵夜
特色就在这个点上
这个粉蒸肉的油份比较大
喝茶的好处是一个是解油腻 一个是便于消化
一口茶 一口肉 一口蒜
吃着具有一种独特的味道
2小时后
你好
坐下来了 发现了蒜
我们的粉蒸肉已经上来了
麽麽哒（没问题）
我确实得先喝点了 真的是太渴了
天气太热了
茶 蒜 粉蒸肉每一个单拿出来都是一种味道
但是把3个配在一起吃 还是第一次尝试
先尝尝单个的味道
刚吃大叔说 粉蒸肉里面比肉好吃 先来一口
真的是这个面已经把牛肉和调料的味道都吸收进来了
来口蒜吧
这个肥肉真是一抿就化啊
我的蒜呢
第一次对蒜这么情有独钟
嘴上有种麻麻的感觉 让你越吃越想吃
吃粉蒸肉不仅可以白口吃
还可以夹在荷叶饼里来吃
顾客：多给点面吧
我喜欢吃这个面
给点肥的要不要
来点吧
吃得满足了
也告别了可爱的小姐姐
今天的视频就到这 拜拜

```

**Comment by shuaisoserious** [comment]
认领

**Comment by shuaisoserious** [comment]
字幕
虽然说听粉蒸肉的名字已经很久了
Although it’s been a long time since I’ve heard the name of “steamed rice powder and pork”
但是尝它的味道还是头一次
But this is my first time to taste it
还是满心的期待呀
And I’m very looking forward it
陕西 西安
Xi’an, Shanxi
我要个大份的（粉蒸肉）带走
I want take out a large steamed rice powder and pork 
大份多少钱
How much?
23元
23 yuan
这是粉蒸肉的精华-肥油
This is the essence of “steamed rice powder and meat”-fatty oil
这一盆的牛肉 切的都是这么大块的
All beef in the pot were chopped into big pieces
这开始加入调味的料汁了
They start adding seasoning sauce 
这个粉蒸肉是用面粉做的
The steamed rice powder and meat are made with flour
有的地方使用米粉做的
It made with rice powder in some other city
（用的粉是不同点）
Different flour
搅拌均匀 然后就可以准备上笼了
Stir well and ready to put on the steamer
现在是盖了一层的肥肉
They use fatty meat cover the top of the pot
蒸熟后 口感会更加滑润 味道会更香
After steaming, the taste will be smoother and more fragrant
现在是六笼 待会蒸2个小时就可以吃了
Now it’s six steamers of steamed pork, it ready to serve after steamed two hours
这个粉蒸肉就是传统的 西安回坊的宵夜食品
This steamed pork is traditional snack food in Xi'an Huifang
以前售卖时候 把灯点亮了才卖这个东西（天黑时候）
They used to sell steamed pork when the light was on (in night)
咱这叫西安回坊的宵夜
Let's call it Xi'an Huifang's midnight food
特色就在这个点上
This is the special
这个粉蒸肉的油份比较大
The steamed rice powder and pork are oily
喝茶的好处是一个是解油腻 一个是便于消化
The benefit of drinking tea is that it is greasy and easy to digest
一口茶 一口肉 一口蒜
A bite of tea, a bite of meat, a bite of garlic
吃着具有一种独特的味道
Eating with a unique taste
2小时后
After two hours
你好
hi
坐下来了 发现了蒜
We sit down and find garlic 
我们的粉蒸肉已经上来了
Our steamed rice powder and pork are on the table
麽麽哒（没问题）
No problem
我确实得先喝点了 真的是太渴了
I need to drink something first because i am so thirsty
天气太热了
Weather are too hot
茶 蒜 粉蒸肉每一个单拿出来都是一种味道
Tea, garlic, steamed meat, every single one is a single taste
但是把3个配在一起吃 还是第一次尝试
It’s my first time to try eat them together
先尝尝单个的味道
Let’s taste single taste
刚吃大叔说 粉蒸肉里面比肉好吃 先来一口
Just heard the uncle said that the inside steamed meat is better than the meat.
真的是这个面已经把牛肉和调料的味道都吸收进来了
The rice powder has absorbed the taste of beef and seasoning
来口蒜吧
Let me have a bite of garlic
这个肥肉真是一抿就化啊
This fatty meat melts in a sip
我的蒜呢
Where is my garlic?
第一次对蒜这么情有独钟
I love the garlic that much at first time
嘴上有种麻麻的感觉 让你越吃越想吃
There is a feeling of numbness in my mouth, making you want to eat more 
吃粉蒸肉不仅可以白口吃

还可以夹在荷叶饼里来吃
You can also eat it in a heye flatbread
顾客：多给点面吧
Customer :”may i have more rice powder?”
我喜欢吃这个面
I like eat it
给点肥的要不要
How about some fatty?
来点吧
okay
吃得满足了
Im stuffed
也告别了可爱的小姐姐
Also said goodbye to the lovely young lady
今天的视频就到这 拜拜
Here is today’s video, bye

**Comment by okiamnewhere** [comment]
1
00:00:02,175 --> 00:00:04,075
虽然说听粉蒸肉的名字已经很久了

2
00:00:04,175 --> 00:00:06,175
但是尝它的味道还是头一次

3
00:00:07,500 --> 00:00:09,225
还是满心的期待呀

4
00:00:10,250 --> 00:00:11,400
陕西 西安

5
00:00:13,150 --> 00:00:15,325
我要个大份的（粉蒸肉）带走

6
00:00:20,200 --> 00:00:21,375
大份多少钱

7
00:00:21,375 --> 00:00:22,825
23元

8
00:00:28,350 --> 00:00:30,775
这是粉蒸肉的精华-肥油

9
00:00:41,225 --> 00:00:43,925
这一盆的牛肉 切的都是这么大块的

10
00:00:46,700 --> 00:00:49,450
这开始加入调味的料汁了

11
00:01:45,175 --> 00:01:47,000
这个粉蒸肉是用面粉做的

12
00:01:47,300 --> 00:01:49,125
有的地方使用米粉做的

13
00:01:49,700 --> 00:01:51,450
（用的粉是不同点）

14
00:02:16,400 --> 00:02:20,350
搅拌均匀 然后就可以准备上笼了

15
00:02:47,500 --> 00:02:49,250
现在是盖了一层的肥肉

16
00:02:49,500 --> 00:02:54,750
蒸熟后 口感会更加滑润 味道会更香

17
00:03:12,425 --> 00:03:17,450
现在是六笼 待会蒸2个小时就可以吃了

18
00:03:18,950 --> 00:03:25,072
这个粉蒸肉就是传统的 西安回坊的宵夜食品

19
00:03:25,450 --> 00:03:31,000
以前售卖时候 把灯点亮了才卖这个东西（天黑时候）

20
00:03:31,725 --> 00:03:34,100
咱这叫西安回坊的宵夜

21
00:03:34,225 --> 00:03:37,400
特色就在这个点上

22
00:03:37,525 --> 00:03:40,225
这个粉蒸肉的油份比较大

23
00:03:40,675 --> 00:03:45,325
喝茶的好处是一个是解油腻 一个是便于消化

24
00:03:45,825 --> 00:03:48,100
一口茶 一口肉 一口蒜

25
00:03:48,325 --> 00:03:50,750
吃着具有一种独特的味道

26
00:03:51,150 --> 00:03:52,700
2小时后

27
00:03:53,250 --> 00:03:54,750
你好

28
00:03:57,200 --> 00:04:00,250
坐下来了 发现了蒜

29
00:04:08,925 --> 00:04:11,525
我们的粉蒸肉已经上来了

30
00:04:11,950 --> 00:04:13,800
麽麽哒（没问题）

31
00:04:14,350 --> 00:04:16,975
我确实得先喝点了 真的是太渴了

32
00:04:16,975 --> 00:04:18,775
天气太热了

33
00:04:22,000 --> 00:04:27,375
茶 蒜 粉蒸肉每一个单拿出来都是一种味道

34
00:04:27,625 --> 00:04:31,625
但是把3个配在一起吃 还是第一次尝试

35
00:04:33,075 --> 00:04:35,150
先尝尝单个的味道

36
00:04:35,375 --> 00:04:42,425
刚吃大叔说 粉蒸肉的面比肉好吃 先来一口

37
00:04:46,275 --> 00:04:50,750
真的是这个面已经把牛肉和调料的味道都吸收进来了

38
00:04:51,375 --> 00:04:53,575
来口蒜吧

39
00:04:59,175 --> 00:05:03,200
这个肥肉真是一抿就化啊

40
00:05:11,625 --> 00:05:13,850
我的蒜呢

41
00:05:16,800 --> 00:05:19,725
第一次对蒜这么情有独钟

42
00:05:28,400 --> 00:05:31,575
嘴上有种麻麻的感觉 让你越吃越想吃

43
00:05:31,875 --> 00:05:34,300
吃粉蒸肉不仅可以白口吃

44
00:05:34,450 --> 00:05:38,100
还可以夹在荷叶饼里来吃

45
00:05:48,000 --> 00:05:49,525
顾客：多给点面吧

46
00:05:52,475 --> 00:05:55,075
我喜欢吃这个面

47
00:05:55,275 --> 00:05:57,100
给点肥的要不要

48
00:05:58,275 --> 00:05:59,500
来点吧

49
00:06:05,925 --> 00:06:07,200
吃得满足了

50
00:06:07,225 --> 00:06:08,700
也告别了可爱的小姐姐

51
00:06:08,800 --> 00:06:11,875
今天的视频就到这 拜拜

**Comment by immoonancient** [comment]
bot, please upload on behalf of the assignee

0:00:02.175,0:00:04.075
# 虽然说听粉蒸肉的名字已经很久了
Although it’s been a long time since I’ve heard the name of “steamed rice powder and pork”

0:00:04.175,0:00:06.175
# 但是尝它的味道还是头一次
But this is my first time to taste it

0:00:07.500,0:00:09.225
# 还是满心的期待呀
And I’m very looking forward it

0:00:10.250,0:00:11.400
# 陕西 西安
Xi’an, Shanxi

0:00:13.150,0:00:15.325
# 我要个大份的（粉蒸肉）带走
I want take out a large steamed rice powder and pork

0:00:20.200,0:00:21.375
# 大份多少钱
How much?

0:00:21.375,0:00:22.825
# 23元
23 yuan

0:00:28.350,0:00:30.775
# 这是粉蒸肉的精华-肥油
This is the essence of “steamed rice powder and meat”-fatty oil

0:00:41.225,0:00:43.925
# 这一盆的牛肉 切的都是这么大块的
All beef in the pot were chopped into big pieces

0:00:46.700,0:00:49.450
# 这开始加入调味的料汁了
They start adding seasoning sauce

0:01:45.175,0:01:47.000
# 这个粉蒸肉是用面粉做的
The steamed rice powder and meat are made with flour

0:01:47.300,0:01:49.125
# 有的地方使用米粉做的
It made with rice powder in some other city

0:01:49.700,0:01:51.450
# （用的粉是不同点）
Different flour

0:02:16.400,0:02:20.350
# 搅拌均匀 然后就可以准备上笼了
Stir well and ready to put on the steamer

0:02:47.500,0:02:49.250
# 现在是盖了一层的肥肉
They use fatty meat cover the top of the pot

0:02:49.500,0:02:54.750
# 蒸熟后 口感会更加滑润 味道会更香
After steaming, the taste will be smoother and more fragrant

0:03:12.425,0:03:17.450
# 现在是六笼 待会蒸2个小时就可以吃了
Now it’s six steamers of steamed pork, it ready to serve after steamed two hours

0:03:18.950,0:03:25.072
# 这个粉蒸肉就是传统的 西安回坊的宵夜食品
This steamed pork is traditional snack food in Xi'an Huifang

0:03:25.450,0:03:31.000
# 以前售卖时候 把灯点亮了才卖这个东西（天黑时候）
They used to sell steamed pork when the light was on (in night)

0:03:31.725,0:03:34.100
# 咱这叫西安回坊的宵夜
Let's call it Xi'an Huifang's midnight food

0:03:34.225,0:03:37.400
# 特色就在这个点上
This is the special

0:03:37.525,0:03:40.225
# 这个粉蒸肉的油份比较大
The steamed rice powder and pork are oily

0:03:40.675,0:03:45.325
# 喝茶的好处是一个是解油腻 一个是便于消化
The benefit of drinking tea is that it is greasy and easy to digest

0:03:45.825,0:03:48.100
# 一口茶 一口肉 一口蒜
A bite of tea, a bite of meat, a bite of garlic

0:03:48.325,0:03:50.750
# 吃着具有一种独特的味道
Eating with a unique taste

0:03:51.150,0:03:52.700
# 2小时后
After two hours

0:03:53.250,0:03:54.750
# 你好
hi

0:03:57.200,0:04:00.250
# 坐下来了 发现了蒜
We sit down and find garlic

0:04:08.925,0:04:11.525
# 我们的粉蒸肉已经上来了
Our steamed rice powder and pork are on the table

0:04:11.950,0:04:13.800
# 麽麽哒（没问题）
No problem

0:04:14.350,0:04:16.975
# 我确实得先喝点了 真的是太渴了
I need to drink something first because i am so thirsty

0:04:16.975,0:04:18.775
# 天气太热了
Weather are too hot

0:04:22.000,0:04:27.375
# 茶 蒜 粉蒸肉每一个单拿出来都是一种味道
Tea, garlic, steamed meat, every single one is a single taste

0:04:27.625,0:04:31.625
# 但是把3个配在一起吃 还是第一次尝试
It’s my first time to try eat them together

0:04:33.075,0:04:35.150
# 先尝尝单个的味道
Let’s taste single taste

0:04:35.375,0:04:42.425
# 刚吃大叔说 粉蒸肉的面比肉好吃 先来一口
Just heard the uncle said that the inside steamed meat is better than the meat.

0:04:46.275,0:04:50.750
# 真的是这个面已经把牛肉和调料的味道都吸收进来了
The rice powder has absorbed the taste of beef and seasoning

0:04:51.375,0:04:53.575
# 来口蒜吧
Let me have a bite of garlic

0:04:59.175,0:05:03.200
# 这个肥肉真是一抿就化啊
This fatty meat melts in a sip

0:05:11.625,0:05:13.850
# 我的蒜呢
Where is my garlic?

0:05:16.800,0:05:19.725
# 第一次对蒜这么情有独钟
I love the garlic that much at first time

0:05:28.400,0:05:31.575
# 嘴上有种麻麻的感觉 让你越吃越想吃
There is a feeling of numbness in my mouth, making you want to eat more

0:05:31.875,0:05:34.300
# 吃粉蒸肉不仅可以白口吃
(placeholder)

0:05:34.450,0:05:38.100
# 还可以夹在荷叶饼里来吃
You can also eat it in a heye flatbread

0:05:48.000,0:05:49.525
# 顾客：多给点面吧
Customer :”may i have more rice powder?”

0:05:52.475,0:05:55.075
# 我喜欢吃这个面
I like eat it

0:05:55.275,0:05:57.100
# 给点肥的要不要
How about some fatty?

0:05:58.275,0:05:59.500
# 来点吧
okay

0:06:05.925,0:06:07.200
# 吃得满足了
Im stuffed

0:06:07.225,0:06:08.700
# 也告别了可爱的小姐姐
Also said goodbye to the lovely young lady

0:06:08.800,0:06:11.875
# 今天的视频就到这 拜拜 
Here is today’s video, bye
