### ISSUE TITLE
[老饭骨] 酱香咸菜丝 - https://youtu.be/32Gf4DAnpJg

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1153]
**视频链接**：https://youtu.be/32Gf4DAnpJg

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【國宴大師•醬香鹹菜絲】比肉還香，在家就能做的小菜，夾火燒、夾饅頭，喝粥、拌麵條，都是絕配！|老飯骨
简介
小友們好，今天我們的大師姐要給大家做一道家常小菜——醬香鹹菜絲，據說比肉還香呢！
這醬香鹹菜絲的關鍵還是要先把鹹菜絲沖水，洗盡所有鹽味，再把所有水擠乾淨嘍。正所謂有味使其出，無味使其入，烹飪的原理真是妙嘞！
另外視頻最後大爺為大家解答的問題：軟炸糊到底怎麼調合適？
出處來自軟炸魚條這期視頻，小友們可以去複習一下！⬇️
https://www.youtube.com/watch?v=Rev4LJsvpfo

字幕
1
00:00:00,000 --> 00:00:02,160
早上起来熬一锅棒子碴粥

2
00:00:02,160 --> 00:00:06,520
把咸菜往火烧里一夹 这就是生活

3
00:00:06,520 --> 00:00:08,880
特别家常的酱香咸菜丝

4
00:00:08,880 --> 00:00:10,760

5
00:00:11,560 --> 00:00:12,760
香么 香

6
00:00:12,760 --> 00:00:16,040

7
00:00:16,040 --> 00:00:17,720
咸菜疙瘩就这个

8
00:00:17,720 --> 00:00:20,840
然后咱们就把咸菜疙瘩切成丝就行

9
00:00:20,840 --> 00:00:23,200
我是我师父收的第一个女徒弟

10
00:00:23,200 --> 00:00:24,520
所以在这行业里边

11
00:00:24,520 --> 00:00:26,080
他们都管我叫大师姐

12
00:00:26,080 --> 00:00:28,200
你看干活多快啊 麻利

13
00:00:28,200 --> 00:00:31,800
瞧这刀工 听这声儿

14
00:00:31,800 --> 00:00:34,160

15
00:00:34,160 --> 00:00:37,520
关键步骤 得冲水

16
00:00:37,520 --> 00:00:39,560
得多冲几遍 换水

17
00:00:39,560 --> 00:00:43,880
没有咸味了 就是一点咸味不能有了

18
00:00:43,880 --> 00:00:45,880
我每次做这道菜的时候

19
00:00:45,880 --> 00:00:47,400
我给我徒弟也讲

20
00:00:47,400 --> 00:00:49,560
这是你们师爷 我师父教我的

21
00:00:49,560 --> 00:00:52,720
有味使其出 无味使其入

22
00:00:52,720 --> 00:00:56,400
这你师父从来没露过这句话

23
00:00:56,400 --> 00:01:00,280
把咸菜的咸味给它洗出去

24
00:01:00,280 --> 00:01:03,040
有的咸菜还犯点酸和臭味

25
00:01:03,040 --> 00:01:06,560
它那个发酵的快 它必须得弄出去

26
00:01:06,560 --> 00:01:08,760
你准备料吧 这儿我给你看着

27
00:01:08,760 --> 00:01:09,800
桂皮 大料

28
00:01:09,800 --> 00:01:11,760
这个还真不是桂皮 这是肉桂

29
00:01:11,760 --> 00:01:13,800
咱家里使桂皮就行 辣椒

30
00:01:13,800 --> 00:01:16,200
这个蒜拍一下 出味

31
00:01:16,200 --> 00:01:18,280
它的黏液的全给拍出来了

32
00:01:18,280 --> 00:01:20,600
料很大 下味足

33
00:01:20,600 --> 00:01:22,720
这是您教我的我都记着呢

34
00:01:22,720 --> 00:01:25,280
葱段姜片大蒜

35
00:01:25,280 --> 00:01:27,840
泡这差不多了

36
00:01:27,840 --> 00:01:31,480
咱们到关键的一步 大家看好

37
00:01:31,480 --> 00:01:33,160
有味使其出 无味使其入

38
00:01:33,160 --> 00:01:34,720
这就是烹饪原理

39
00:01:34,720 --> 00:01:38,880
咱们得把咸菜的水给挤出去

40
00:01:38,880 --> 00:01:40,560
我跟您说为什么挤这水

41
00:01:40,560 --> 00:01:41,520
如果不挤这水

42
00:01:41,520 --> 00:01:43,600
就是咱们平时的炒咸菜疙瘩

43
00:01:43,600 --> 00:01:45,640
外边的味儿进不去 里边的味儿出不来

44
00:01:45,640 --> 00:01:46,560

45
00:01:47,640 --> 00:01:51,600
它吸外来的味更加饱满充分

46
00:01:51,600 --> 00:01:52,960
你给我照我给你挤得了

47
00:01:52,960 --> 00:01:54,600
换师父来 你得照师父

48
00:01:54,600 --> 00:01:55,920

49
00:01:55,920 --> 00:02:01,000
师父就是师父 老厉害了

50
00:02:01,000 --> 00:02:05,720
行了可以了 别一夸您就使劲大了

51
00:02:05,720 --> 00:02:08,400
挤完以后咸菜就变成这样了

52
00:02:08,400 --> 00:02:10,480
成了干咸菜丝了

53
00:02:10,480 --> 00:02:13,120
这个嚼起来比较有韧性了 有嚼头了

54
00:02:13,120 --> 00:02:16,000
这么多你看没了 看着多做出来就少了

55
00:02:16,000 --> 00:02:18,640
咸味儿也没了 筋道了

56
00:02:18,640 --> 00:02:21,120
师父师伯咱们开始炒咸菜

57
00:02:21,120 --> 00:02:24,080
这得多搁油 因为它吸油

58
00:02:24,080 --> 00:02:27,960
咱把蒜子 姜下去

59
00:02:27,960 --> 00:02:29,840
葱姜蒜炒香了

60
00:02:29,840 --> 00:02:31,800
如果家里边您要是有葱油的话

61
00:02:31,800 --> 00:02:34,320
直接使葱油炒也行 葱油更好啊

62
00:02:34,320 --> 00:02:36,760
大料桂皮干辣椒

63
00:02:36,760 --> 00:02:40,400
它出的是什么味 出的是肉香味

64
00:02:40,400 --> 00:02:42,560
咱们在家炒的时候一定给它炒透了

65
00:02:42,560 --> 00:02:46,080
再补点油 这一炸料的油 它吃

66
00:02:46,080 --> 00:02:48,720
所以这油还要补一点

67
00:02:48,720 --> 00:02:50,200
这香味出来了

68
00:02:50,200 --> 00:02:52,360
你看这辣椒还不能是糊

69
00:02:52,360 --> 00:02:54,200
糊辣味就不对了

70
00:02:54,200 --> 00:02:56,600
它得慢慢的沁炸

71
00:02:56,600 --> 00:02:59,000
让它香味逐步的释放出来

72
00:02:59,000 --> 00:03:01,400
料香味 葱香味 姜香味

73
00:03:01,400 --> 00:03:05,360
各种的味道全部出来 现在正合适的时候

74
00:03:05,360 --> 00:03:07,600
咸菜丝下锅 下锅了

75
00:03:07,600 --> 00:03:10,400
炒的多干松啊 整个油都包裹在上面

76
00:03:10,400 --> 00:03:13,760
现在拌匀了以后关小点火

77
00:03:13,760 --> 00:03:15,720
记住这个是不搁盐的

78
00:03:15,720 --> 00:03:19,160
千万别搁盐 搁盐就咸了

79
00:03:19,160 --> 00:03:23,280
咱们首先是 搁酱油就行了

80
00:03:23,280 --> 00:03:26,320
一百七十克

81
00:03:26,320 --> 00:03:29,040
然后冰糖老抽是必须的

82
00:03:29,040 --> 00:03:31,920
这颜色必须得够

83
00:03:31,920 --> 00:03:37,960
得一百克左右 出来这个颜色红亮红亮的

84
00:03:37,960 --> 00:03:39,320
黄酒来一点

85
00:03:39,320 --> 00:03:41,360
再加点酱油

86
00:03:41,360 --> 00:03:43,280
刚才是生抽老抽  这回是酱油

87
00:03:43,280 --> 00:03:46,360
然后白糖再来八十克

88
00:03:47,920 --> 00:03:50,560
别瞧这么多糖 但是它吃不出糖味儿来

89
00:03:50,560 --> 00:03:52,040
为什么使这冰糖老抽

90
00:03:52,040 --> 00:03:56,680
因为它出来以后成菜颜色好看 它红亮

91
00:03:56,680 --> 00:03:58,960
这烹饪的绝学在哪儿 你看

92
00:03:58,960 --> 00:04:02,080
挤干净了 缩了没味儿了

93
00:04:02,080 --> 00:04:05,640
让它慢慢的把这汤汁里的味再吸进去

94
00:04:05,640 --> 00:04:09,640
一会儿咱们有一步也很关键

95
00:04:09,640 --> 00:04:13,000
还要放锅上蒸 盛出来

96
00:04:13,000 --> 00:04:14,840
咱们拿保温膜把它给包上

97
00:04:14,840 --> 00:04:17,600
咱们这保鲜膜是可以高温的

98
00:04:17,840 --> 00:04:20,840
为了让水蒸气免得流进去

99
00:04:20,840 --> 00:04:23,320
咱们这开锅得蒸半个小时

100
00:04:23,320 --> 00:04:25,760
这会咱把这芝麻炒了

101
00:04:25,760 --> 00:04:27,120
锅里什么都不用搁

102
00:04:27,120 --> 00:04:30,880
就直接把芝麻倒进去 小火慢慢炒

103
00:04:30,880 --> 00:04:31,640
最好买生的

104
00:04:31,640 --> 00:04:35,600
因为生芝麻炒出来以后现焙 特别香

105
00:04:35,600 --> 00:04:37,400
好嘞关火

106
00:04:37,400 --> 00:04:40,760
一定得炒出香味来 这个芝麻油够大的

107
00:04:40,760 --> 00:04:43,800
这咸菜蒸了将近三十分钟

108
00:04:43,800 --> 00:04:45,680

109
00:04:49,000 --> 00:04:51,280
香么 香 太香了

110
00:04:51,280 --> 00:04:56,440
您看看放完冰糖老抽 这颜色多漂亮

111
00:04:56,440 --> 00:04:58,280
这个料头挑挑

112
00:04:58,280 --> 00:05:02,160
搁在一边给它晾凉了 装一罐里边封着

113
00:05:02,160 --> 00:05:05,520
吃个一礼拜都没事儿  半个月都没事儿

114
00:05:05,520 --> 00:05:11,920
然后香菜 切中间连梗带叶的地儿

115
00:05:11,920 --> 00:05:15,280
这咸菜凉了 芝麻多放点

116
00:05:15,280 --> 00:05:17,440
芝麻也是吃的时候再拌

117
00:05:17,440 --> 00:05:22,360
然后香菜也是吃的时候 现吃现拌

118
00:05:22,360 --> 00:05:25,120
这太香了大爷

119
00:05:25,120 --> 00:05:27,440
油亮儿 为什么开始的时候

120
00:05:27,440 --> 00:05:29,520
咱们的油得下够了

121
00:05:31,880 --> 00:05:33,480
这是空心的

122
00:05:35,600 --> 00:05:37,280
我师父说了先给大爷

123
00:05:37,280 --> 00:05:39,800
谢谢 谢谢 我先来一口

124
00:05:40,920 --> 00:05:43,000
我的天 你看大爷吃的香

125
00:05:43,000 --> 00:05:44,720

126
00:05:44,720 --> 00:05:46,920
这咔嚓你看 这一大口

127
00:05:46,920 --> 00:05:49,200
我再给我师父来一个

128
00:05:49,200 --> 00:05:51,640
清晨早晨起来 熬一锅棒子碴粥

129
00:05:51,640 --> 00:05:54,680
把咸菜往火烧里一夹

130
00:05:54,680 --> 00:05:55,880
这就是生活

131
00:05:55,880 --> 00:05:58,680

1
00:00:00,000 --> 00:00:02,400
上回您做了一个软炸鱼条

2
00:00:02,680 --> 00:00:05,640
他想问这个小苏打可不可以不加

3
00:00:05,880 --> 00:00:08,840
没有小苏打可以用泡打粉代替吗

4
00:00:08,960 --> 00:00:09,520
可以

5
00:00:09,520 --> 00:00:11,320
有些地方没有小苏打

6
00:00:12,080 --> 00:00:13,920
用泡打粉也可以

7
00:00:13,920 --> 00:00:16,160
泡打粉是属于一个膨胀的作用

8
00:00:16,720 --> 00:00:20,040
小苏打是起外酥 坚挺

9
00:00:20,160 --> 00:00:23,480
你看我兑这个软炸糊的时候

10
00:00:23,560 --> 00:00:24,840
我又加了点淀粉

11
00:00:24,840 --> 00:00:27,480
在这方面有很多网友也有一些质疑

12
00:00:27,880 --> 00:00:29,640
说软炸糊不加淀粉

13
00:00:30,240 --> 00:00:31,000
不是这样的

14
00:00:31,000 --> 00:00:34,800
因为我们在烹调当中根据不同的原料

15
00:00:34,800 --> 00:00:36,760
（原料）不同含的水分

16
00:00:36,760 --> 00:00:40,680
我们在调糊当中要采取不同的方法来对应

17
00:00:41,160 --> 00:00:43,600
这样出来的效果才能达到饱满

18
00:00:43,960 --> 00:00:46,240
加面粉也好 加淀粉也好

19
00:00:46,400 --> 00:00:48,960
您不信您可以试一试

20
00:00:49,240 --> 00:00:52,160
这些东西绝对不是一成不变的 是绝对的东西

21
00:00:52,560 --> 00:00:54,000
你就是玉米淀粉

22
00:00:54,440 --> 00:00:56,920
你就不加面粉完全使玉米淀粉

23
00:00:57,120 --> 00:00:58,880
你加上合适的鸡蛋

24
00:01:00,080 --> 00:01:01,680
你再加上油封起来

25
00:01:01,800 --> 00:01:04,520
这个软炸糊一定很酥 也很脆

26
00:01:04,800 --> 00:01:05,640
也很好吃

27
00:01:05,640 --> 00:01:07,200
就这三样东西就能解决了

28
00:01:07,360 --> 00:01:09,600
只是这个配比关系要合适

29
00:01:09,600 --> 00:01:10,600
一点问题没有

30
00:01:11,200 --> 00:01:11,800
要灵活

31
00:01:11,800 --> 00:01:12,920
不加面粉都行

32
00:01:13,546 --> 00:01:14,920
要灵活运用

**Comment by brainshawn** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【國宴大師•醬香鹹菜絲】比肉還香，在家就能做的小菜，夾火燒、夾饅頭，喝粥、拌麵條，都是絕配！|老飯骨
[State Banquet Master Chef: Salted turnip julienne with soy sauce aroma] - All-match side dish at home, yummier than meat!

简介
小友們好，今天我們的大師姐要給大家做一道家常小菜——醬香鹹菜絲，據說比肉還香呢！
這醬香鹹菜絲的關鍵還是要先把鹹菜絲沖水，洗盡所有鹽味，再把所有水擠乾淨嘍。正所謂有味使其出，無味使其入，烹飪的原理真是妙嘞！
另外視頻最後大爺為大家解答的問題：軟炸糊到底怎麼調合適？
出處來自軟炸魚條這期視頻，小友們可以去複習一下！⬇️
https://www.youtube.com/watch?v=Rev4LJsvpfo

Hello friends, today our senior sister is presenting a home-made side dish “salted turnip julienne with soy sauce aroma”, even yummier than meat! The most critical step of this dish is to wash the salted turnip julienne thoroughly -- getting rid of its saline taste and then squeezing water off it, so called “clear food’s original taste if it has; add new taste if it doesn’t”. The principle of cuisine is really wonderful!
At the end of this video Da Ye will answer a question: what is the best way to fry soft paste? This question comes from a previous video “golden and crispy soft fried fish fingers”. You could review it via this link: https://www.youtube.com/watch?v=Rev4LJsvpfo.

字幕
1
00:00:00,000 --> 00:00:02,160
早上起来熬一锅棒子碴粥
After getting up in the morning, boil a pot of corn congee

2
00:00:02,160 --> 00:00:06,520
把咸菜往火烧里一夹 这就是生活
And put some salted vegetables into a Huo Shao -- this is the life

3
00:00:06,520 --> 00:00:08,880
特别家常的酱香咸菜丝
Very home-made salted turnip julienne with soy sauce

4
00:00:08,880 --> 00:00:10,760

5
00:00:11,560 --> 00:00:12,760
香么 香
Can you smell aroma? Yes

6
00:00:12,760 --> 00:00:16,040

7
00:00:16,040 --> 00:00:17,720
咸菜疙瘩就这个
This a salted turnip

8
00:00:17,720 --> 00:00:20,840
然后咱们就把咸菜疙瘩切成丝就行
Then we just need to cut it into juliennes

9
00:00:20,840 --> 00:00:23,200
我是我师父收的第一个女徒弟
I am the first female disciple of my master

10
00:00:23,200 --> 00:00:24,520
所以在这行业里边
So in the cooking industry

11
00:00:24,520 --> 00:00:26,080
他们都管我叫大师姐
They all call me “senior sister”

12
00:00:26,080 --> 00:00:28,200
你看干活多快啊 麻利
Look, she is so proficient and deft

13
00:00:28,200 --> 00:00:31,800
瞧这刀工 听这声儿
Look at the knife skill, and listen

14
00:00:31,800 --> 00:00:34,160

15
00:00:34,160 --> 00:00:37,520
关键步骤 得冲水
Here comes the critical step, washing

16
00:00:37,520 --> 00:00:39,560
得多冲几遍 换水
You have to wash several times and change the water

17
00:00:39,560 --> 00:00:43,880
没有咸味了 就是一点咸味不能有了
Make sure it’s not salty anymore, not even a little bit

18
00:00:43,880 --> 00:00:45,880
我每次做这道菜的时候
Every time I cook this dish

19
00:00:45,880 --> 00:00:47,400
我给我徒弟也讲
I always tell my apprentices

20
00:00:47,400 --> 00:00:49,560
这是你们师爷 我师父教我的
My master once taught me that

21
00:00:49,560 --> 00:00:52,720
有味使其出 无味使其入
“clear food’s original taste if it has; add new taste if it doesn’t”

22
00:00:52,720 --> 00:00:56,400
这你师父从来没露过这句话
I’ve never heard this from your master

23
00:00:56,400 --> 00:01:00,280
把咸菜的咸味给它洗出去
Get rid of the saline taste from the salted turnip

24
00:01:00,280 --> 00:01:03,040
有的咸菜还犯点酸和臭味
Some salted turnip even tastes a bit sour and fetid

25
00:01:03,040 --> 00:01:06,560
它那个发酵的快 它必须得弄出去
Salted turnip ferments fast, so we must clear its bad taste

26
00:01:06,560 --> 00:01:08,760
你准备料吧 这儿我给你看着
You could prepare the seasoning now, I will wash it for you

27
00:01:08,760 --> 00:01:09,800
桂皮 大料
Cinnamon, star anise


28
00:01:09,800 --> 00:01:11,760
这个还真不是桂皮 这是肉桂
Actually this is not cinnamon, but cassia

29
00:01:11,760 --> 00:01:13,800
咱家里使桂皮就行 辣椒
Cinnamon is also okay for cooking at home, dried chili pepper

30
00:01:13,800 --> 00:01:16,200
这个蒜拍一下 出味
Crush the garlic to make its taste out

31
00:01:16,200 --> 00:01:18,280
它的黏液的全给拍出来了
All its mucus has been crushed out

32
00:01:18,280 --> 00:01:20,600
料很大 下味足
Bigger chunk makes taste more sufficient

33
00:01:20,600 --> 00:01:22,720
这是您教我的我都记着呢
This was taught by you, and I still remember it

34
00:01:22,720 --> 00:01:25,280
葱段姜片大蒜
Spring onion segments, ginger slices, and garlic chunks

35
00:01:25,280 --> 00:01:27,840
泡这差不多了
The soaking time is enough

36
00:01:27,840 --> 00:01:31,480
咱们到关键的一步 大家看好
Here comes the most critical step, pay attention please

37
00:01:31,480 --> 00:01:33,160
有味使其出 无味使其入
Clear food’s original taste if it has; add new taste if it doesn’t

38
00:01:33,160 --> 00:01:34,720
这就是烹饪原理
This is the principle of cuisine

39
00:01:34,720 --> 00:01:38,880
咱们得把咸菜的水给挤出去
We have to get rid of the water from the salted turnips

40
00:01:38,880 --> 00:01:40,560
我跟您说为什么挤这水
Let me tell you the reason

41
00:01:40,560 --> 00:01:41,520
如果不挤这水
If we don’t do this

42
00:01:41,520 --> 00:01:43,600
就是咱们平时的炒咸菜疙瘩
Then the dish would become an ordinary fried salted turnip

43
00:01:43,600 --> 00:01:45,640
外边的味儿进不去 里边的味儿出不来
Because the outer taste can’t go inside, and the inner taste can’t go outside

44
00:01:45,640 --> 00:01:46,560

45
00:01:47,640 --> 00:01:51,600
它吸外来的味更加饱满充分
It will absorb more taste from outside

46
00:01:51,600 --> 00:01:52,960
你给我照我给你挤得了
You take photos for me, and let me help you squeeze it

47
00:01:52,960 --> 00:01:54,600
换师父来 你得照师父
Now it’s my master’s turn; remember to take photos for your master

48
00:01:54,600 --> 00:01:55,920

49
00:01:55,920 --> 00:02:01,000
师父就是师父 老厉害了
Master is really master, very awesome

50
00:02:01,000 --> 00:02:05,720
行了可以了 别一夸您就使劲大了
That’s enough, don’t work so hard because of the applause

51
00:02:05,720 --> 00:02:08,400
挤完以后咸菜就变成这样了
Look how the salted turnip juliennes become after squeezing

52
00:02:08,400 --> 00:02:10,480
成了干咸菜丝了
They have been dried

53
00:02:10,480 --> 00:02:13,120
这个嚼起来比较有韧性了 有嚼头了
This makes it  tougher and more enjoyable to chew

54
00:02:13,120 --> 00:02:16,000
这么多你看没了 看着多做出来就少了
So few now, they seem to be much less than before

55
00:02:16,000 --> 00:02:18,640
咸味儿也没了 筋道了
And also there’s no saline taste now, they are more crunchy

56
00:02:18,640 --> 00:02:21,120
师父师伯咱们开始炒咸菜
Master and mater’s brother, let’s begin cooking

57
00:02:21,120 --> 00:02:24,080
这得多搁油 因为它吸油
Add more oil than usual, as the ingredient absorbs oil

58
00:02:24,080 --> 00:02:27,960
咱把蒜子 姜下去
Add garlic and ginger

59
00:02:27,960 --> 00:02:29,840
葱姜蒜炒香了
Cook until you can smell the aroma

60
00:02:29,840 --> 00:02:31,800
如果家里边您要是有葱油的话
If you have scallion oil	 at home

61
00:02:31,800 --> 00:02:34,320
直接使葱油炒也行 葱油更好啊
You could use it as the oil; scallion oil is even better

62
00:02:34,320 --> 00:02:36,760
大料桂皮干辣椒
star anise, cinnamon, and dried chilli pepper

63
00:02:36,760 --> 00:02:40,400
它出的是什么味 出的是肉香味
What does it smell like? The aroma of meat

64
00:02:40,400 --> 00:02:42,560
咱们在家炒的时候一定给它炒透了
We have to cook it thoroughly when cooking at home

65
00:02:42,560 --> 00:02:46,080
再补点油 这一炸料的油 它吃
Now we add a little more oil, it has absorbed a lot of oil

66
00:02:46,080 --> 00:02:48,720
所以这油还要补一点
So we have to add a little more


67
00:02:48,720 --> 00:02:50,200
这香味出来了
The aroma has come out

68
00:02:50,200 --> 00:02:52,360
你看这辣椒还不能是糊
Don't overcook the chilli peppers

69
00:02:52,360 --> 00:02:54,200
糊辣味就不对了
It’s wrong to have burnt taste

70
00:02:54,200 --> 00:02:56,600
它得慢慢的沁炸
We need to fry them slowly

71
00:02:56,600 --> 00:02:59,000
让它香味逐步的释放出来
To let its taste get out gradually

72
00:02:59,000 --> 00:03:01,400
料香味 葱香味 姜香味
The mixed aroma of star anises, spring onions and gingers

73
00:03:01,400 --> 00:03:05,360
各种的味道全部出来 现在正合适的时候
All kinds of taste have come out, so now it’s the perfect time

74
00:03:05,360 --> 00:03:07,600
咸菜丝下锅 下锅了
Add salted turnip juliennes

75
00:03:07,600 --> 00:03:10,400
炒的多干松啊 整个油都包裹在上面
So dry and soft, that they are all wrapped by oil


76
00:03:10,400 --> 00:03:13,760
现在拌匀了以后关小点火
Mix they thoroughly and then turn down the heat


77
00:03:13,760 --> 00:03:15,720
记住这个是不搁盐的
Remember no salt

78
00:03:15,720 --> 00:03:19,160
千万别搁盐 搁盐就咸了
Never add salt, otherwise it become salty finally

79
00:03:19,160 --> 00:03:23,280
咱们首先是 搁酱油就行了
Firstly add some soy sauce

80
00:03:23,280 --> 00:03:26,320
一百七十克
170g

81
00:03:26,320 --> 00:03:29,040
然后冰糖老抽是必须的
Then necessarily some white rock sugar and dark soy sauce

82
00:03:29,040 --> 00:03:31,920
这颜色必须得够
The color must be enough

83
00:03:31,920 --> 00:03:37,960
得一百克左右 出来这个颜色红亮红亮的
About 100g, to make the color red and bright finally

84
00:03:37,960 --> 00:03:39,320
黄酒来一点
A little huangjiu rice wine

85
00:03:39,320 --> 00:03:41,360
再加点酱油
A little soy sauce

86
00:03:41,360 --> 00:03:43,280
刚才是生抽老抽  这回是酱油
Note that we have added light and dark soy sauces, but this time it’s soy sauce

87
00:03:43,280 --> 00:03:46,360
然后白糖再来八十克
80g soft sugar

88
00:03:47,920 --> 00:03:50,560
别瞧这么多糖 但是它吃不出糖味儿来
Even though the quality looks large, actually it doesn’t taste sugary at all

89
00:03:50,560 --> 00:03:52,040
为什么使这冰糖老抽
Why add white rock sugar and dark soy sauce?

90
00:03:52,040 --> 00:03:56,680
因为它出来以后成菜颜色好看 它红亮
Because it makes the dish look better, red and bright

91
00:03:56,680 --> 00:03:58,960
这烹饪的绝学在哪儿 你看
So where is the secret of cuisine, take a look

92
00:03:58,960 --> 00:04:02,080
挤干净了 缩了没味儿了
Dryly squeezed, shrinked and tasteless

93
00:04:02,080 --> 00:04:05,640
让它慢慢的把这汤汁里的味再吸进去
To make the ingredient absorb taste from the soup slowly

94
00:04:05,640 --> 00:04:09,640
一会儿咱们有一步也很关键
There’s another important step later

95
00:04:09,640 --> 00:04:13,000
还要放锅上蒸 盛出来
We will steam the dish; take it out

96
00:04:13,000 --> 00:04:14,840
咱们拿保温膜把它给包上
Wrap the dish with a piece of cling wrap


97
00:04:14,840 --> 00:04:17,600
咱们这保鲜膜是可以高温的
This cling wrap is heat resisting

98
00:04:17,840 --> 00:04:20,840
为了让水蒸气免得流进去
It’s to isolate the vapor out

99
00:04:20,840 --> 00:04:23,320
咱们这开锅得蒸半个小时
We need to steam for half an hour

100
00:04:23,320 --> 00:04:25,760
这会咱把这芝麻炒了
We could cook some sesames in the meanwhile

101
00:04:25,760 --> 00:04:27,120
锅里什么都不用搁
Add nothing in the pot

102
00:04:27,120 --> 00:04:30,880
就直接把芝麻倒进去 小火慢慢炒
Just pour the sesames in, and cook them slowly

103
00:04:30,880 --> 00:04:31,640
最好买生的
Better to use unripe sesames

104
00:04:31,640 --> 00:04:35,600
因为生芝麻炒出来以后现焙 特别香
Because unripe sesames has strong aroma after baking

105
00:04:35,600 --> 00:04:37,400
好嘞关火
Okay, let’s turn off the heat

106
00:04:37,400 --> 00:04:40,760
一定得炒出香味来 这个芝麻油够大的
We must cook enough time until the aroma comes out; so much sesame oil

107
00:04:40,760 --> 00:04:43,800
这咸菜蒸了将近三十分钟
We have steamed about 30 mimutes

108
00:04:43,800 --> 00:04:45,680

109
00:04:49,000 --> 00:04:51,280
香么 香 太香了
Does it smell good? Yes, very much!

110
00:04:51,280 --> 00:04:56,440
您看看放完冰糖老抽 这颜色多漂亮
The color is so wonderful after adding the white rock sugar and dark soy sauce

111
00:04:56,440 --> 00:04:58,280
这个料头挑挑
Pick the condiments out

112
00:04:58,280 --> 00:05:02,160
搁在一边给它晾凉了 装一罐里边封着
After cooling down, if we store the dish in a container

113
00:05:02,160 --> 00:05:05,520
吃个一礼拜都没事儿  半个月都没事儿
We could eat it for one week, or even half a month

114
00:05:05,520 --> 00:05:11,920
然后香菜 切中间连梗带叶的地儿
Then some cilantro, only keep the middle part with stem and some leaves

115
00:05:11,920 --> 00:05:15,280
这咸菜凉了 芝麻多放点
Now it’s already cool, we could add more sesames

116
00:05:15,280 --> 00:05:17,440
芝麻也是吃的时候再拌
Mix sesames just before eating

117
00:05:17,440 --> 00:05:22,360
然后香菜也是吃的时候 现吃现拌
The same for cilantro, mix just before eating

118
00:05:22,360 --> 00:05:25,120
这太香了大爷
This smells really good, Da Ye

119
00:05:25,120 --> 00:05:27,440
油亮儿 为什么开始的时候
The oil looks bright, that is why initially

120
00:05:27,440 --> 00:05:29,520
咱们的油得下够了
We had to add enough oil

121
00:05:31,880 --> 00:05:33,480
这是空心的
The Huo Shao is hollow

122
00:05:35,600 --> 00:05:37,280
我师父说了先给大爷
My master said, let Da Ye eat first

123
00:05:37,280 --> 00:05:39,800
谢谢 谢谢 我先来一口
Thanks, I will taste first

124
00:05:40,920 --> 00:05:43,000
我的天 你看大爷吃的香
My god, look how satisfied Da Ye is

125
00:05:43,000 --> 00:05:44,720

126
00:05:44,720 --> 00:05:46,920
这咔嚓你看 这一大口
Look, such a big bite

127
00:05:46,920 --> 00:05:49,200
我再给我师父来一个
One more for my master

128
00:05:49,200 --> 00:05:51,640
清晨早晨起来 熬一锅棒子碴粥
After getting up in the morning, boil a pot of corn congee

129
00:05:51,640 --> 00:05:54,680
把咸菜往火烧里一夹
And put some salted vegetables into a Huo Shao

130
00:05:54,680 --> 00:05:55,880
这就是生活
This is the life

131
00:05:55,880 --> 00:05:58,680

1
00:00:00,000 --> 00:00:02,400
上回您做了一个软炸鱼条
Last time you soft fried some fish pastes

2
00:00:02,680 --> 00:00:05,640
他想问这个小苏打可不可以不加
People want to ask whether it’s possible not to add baking soda

3
00:00:05,880 --> 00:00:08,840
没有小苏打可以用泡打粉代替吗
Can we use baking powder instead in case of a lack of baking soda?

4
00:00:08,960 --> 00:00:09,520
可以
Sure

5
00:00:09,520 --> 00:00:11,320
有些地方没有小苏打
If there’s no baking soda in your place

6
00:00:12,080 --> 00:00:13,920
用泡打粉也可以
You can use baking powder instead

7
00:00:13,920 --> 00:00:16,160
泡打粉是属于一个膨胀的作用
Baking powder is for inflation

8
00:00:16,720 --> 00:00:20,040
小苏打是起外酥 坚挺
Baking soda is to make food crispy

9
00:00:20,160 --> 00:00:23,480
你看我兑这个软炸糊的时候
You see when I made the paste for soft fry

10
00:00:23,560 --> 00:00:24,840
我又加了点淀粉
I also added some starch

11
00:00:24,840 --> 00:00:27,480
在这方面有很多网友也有一些质疑
Many people might argue

12
00:00:27,880 --> 00:00:29,640
说软炸糊不加淀粉
That we shouldn’t add starch for soft fry paste

13
00:00:30,240 --> 00:00:31,000
不是这样的
It’s not true

14
00:00:31,000 --> 00:00:34,800
因为我们在烹调当中根据不同的原料
Because in cooking, according to different ingredients

15
00:00:34,800 --> 00:00:36,760
（原料）不同含的水分
With different moisture

16
00:00:36,760 --> 00:00:40,680
我们在调糊当中要采取不同的方法来对应
We need to use different approaches when making paste

17
00:00:41,160 --> 00:00:43,600
这样出来的效果才能达到饱满
To make the final result plump

18
00:00:43,960 --> 00:00:46,240
加面粉也好 加淀粉也好
No matter flour or starch

19
00:00:46,400 --> 00:00:48,960
您不信您可以试一试
You could simply have a try if that’s not convincing to you

20
00:00:49,240 --> 00:00:52,160
这些东西绝对不是一成不变的 是绝对的东西
The cooking technical is not an absolute thing

21
00:00:52,560 --> 00:00:54,000
你就是玉米淀粉
For example, if you even use corn starch

22
00:00:54,440 --> 00:00:56,920
你就不加面粉完全使玉米淀粉
Without any flour

23
00:00:57,120 --> 00:00:58,880
你加上合适的鸡蛋
But with proper quantity of eggs

24
00:01:00,080 --> 00:01:01,680
你再加上油封起来
And then wrap with some oil

25
00:01:01,800 --> 00:01:04,520
这个软炸糊一定很酥 也很脆
The soft fried paste must still be crispy

26
00:01:04,800 --> 00:01:05,640
也很好吃
And also delicious

27
00:01:05,640 --> 00:01:07,200
就这三样东西就能解决了
We can make it just with the three things above

28
00:01:07,360 --> 00:01:09,600
只是这个配比关系要合适
As long as the proportion is proper

29
00:01:09,600 --> 00:01:10,600
一点问题没有
There’s no any problem

30
00:01:11,200 --> 00:01:11,800
要灵活
Cooking is flexible

31
00:01:11,800 --> 00:01:12,920
不加面粉都行
It’s also okay without flour

32
00:01:13,546 --> 00:01:14,920
要灵活运用
We must cook flexibly
