### ISSUE TITLE
【美食作家王刚】 沺沺5岁生日 - https://youtu.be/J0N0a9QRDkU

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1155]
**视频链接**：https://youtu.be/J0N0a9QRDkU

视频时长6:44，预计发布时间为北京时间6月13日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
沺沺5岁啦，做几道菜来庆祝一下！翻出女儿的照片回忆满满，我的小棉袄！

简介
大家好，沺沺不知不觉都5岁了，现在都当姐姐了，真的长大了很多，大家看是不是越来越可爱！其实翻出之前的照片的时候才发现，自己其实也错过了很多，她2岁的时候正是我创业最忙的时候，每天不仅要正常上班还要熬夜拍视频剪视频，所以以至于2岁多的照片都找不到一张，说来真是惭愧，以后再忙也要有陪家人的时间。

字幕
0:00:01.420,0:00:02.600
哈喽大家好

0:00:03.240,0:00:04.200
打个招呼宝贝

0:00:05.080,0:00:06.620
你说哈喽大家好你是谁

0:00:06.860,0:00:09.440
哈喽大家好我是沺沺

0:00:09.600,0:00:10.700
嗯沺沺

0:00:19.380,0:00:21.780
出生第一天

0:00:24.320,0:00:26.320
三个月

0:00:28.960,0:00:30.960
十一个月

0:00:33.960,0:00:36.420
一岁

0:00:38.680,0:00:52.940
三岁半

0:00:53.400,0:01:22.360
四岁

0:01:23.200,0:01:27.200
四岁半

0:01:28.620,0:01:32.500
五岁

0:01:33.300,0:01:33.860
哈喽 大家好

0:01:34.066,0:01:38.922
今天又请个假做一个我女儿喜欢吃的几个菜

0:01:39.514,0:01:40.737
这个是什么宝贝

0:01:40.815,0:01:41.514
多宝鱼

0:01:41.912,0:01:42.815
是什么多宝鱼

0:01:43.747,0:01:45.281
你最喜欢怎么做这个

0:01:46.097,0:01:48.986
我最喜欢弄番茄酱做

0:01:49.223,0:01:52.407
番茄酱做 你说的是那个吧

0:01:52.893,0:01:53.922
那个松鼠鱼对不对

0:01:54.106,0:01:56.310
这个我们做多宝鱼 清蒸多宝鱼

0:01:56.902,0:01:59.970
今天我们做一个清汤牛肉丸

0:02:00.213,0:02:04.155
然后做一个清蒸多宝鱼 还有一个姜葱花甲

0:02:04.155,0:02:07.893
然后再炒一些孩子比较喜欢吃的素菜

0:02:08.533,0:02:10.669
今天是我女儿满5岁的生日

0:02:10.708,0:02:15.932
所以请个假 简简单单的做一个菜 做来今天中午吃

0:02:17.941,0:02:20.262
我先切碎 沺沺等一下要不要来试一下

0:02:20.902,0:02:21.310
要

0:02:21.932,0:02:22.291
算了吧

0:02:22.310,0:02:26.165
你也来试 你敢切吗 那个刀很利的哦

0:02:27.689,0:02:31.067
你不是跟爸爸说你长大了要当厨师吗

0:02:34.067,0:02:34.582
是不是

0:02:34.951,0:02:35.446
是

0:02:36.728,0:02:38.504
那等你长大了我教你好不好

0:02:38.504,0:02:39.116
好

0:02:45.747,0:02:47.262
我们站到这里看好不好

0:02:47.504,0:02:50.165
不要 葱妈妈也会伤心的

0:02:50.233,0:02:51.844
还有葱妈妈

0:02:51.844,0:02:56.174
你的意思是爸爸切了葱 葱妈妈要伤心是吗

0:02:56.320,0:02:58.650
不是 葱宝宝这个是

0:02:58.650,0:02:59.631
哦 这个是葱宝宝

0:02:59.825,0:03:00.320
嗯

0:03:01.582,0:03:03.359
爸爸 这是姜妈妈

0:03:03.436,0:03:06.948
嗯 我会切得它很舒服的 它不会感到痛苦

0:03:10.912,0:03:13.660
这是多宝鱼宝宝 它也会伤心的

0:04:43.274,0:04:45.429
沺沺 过来吃饭了 来

0:04:48.439,0:04:48.944
吃什么 沺沺

0:04:48.944,0:04:50.071
多宝鱼

0:04:50.071,0:04:52.082
多宝鱼是不 爸爸给你弄

0:04:53.518,0:04:54.450
吃撒吃撒

0:04:54.553,0:04:54.963
吃嘛

0:04:59.606,0:05:00.153
这个好吃噶

0:05:03.950,0:05:05.190
原先腥的你吃不来噶

0:05:06.678,0:05:09.491
沺沺 你知道你今天多少岁了吗

0:05:09.559,0:05:09.970
知道

0:05:10.209,0:05:10.953
你今天几岁

0:05:11.389,0:05:11.885
5岁

0:05:12.142,0:05:12.680
5岁啊

0:05:13.416,0:05:14.963
5岁了是不是都长大了

0:05:15.109,0:05:15.681
嗯

0:05:16.323,0:05:17.426
长大了还要不要吃糖

0:05:20.701,0:05:21.966
你说长大了不吃糖了

0:05:22.077,0:05:23.198
以后还要不要吃糖

0:05:24.437,0:05:25.130
少吃糖

0:05:25.472,0:05:26.233
要少吃点

0:05:28.088,0:05:29.516
说她吃糖她心头不高兴

0:05:29.679,0:05:30.782
等下给你切蛋糕好不好

0:05:32.321,0:05:32.663
好

0:05:32.663,0:05:33.099
要不要吃

0:05:33.364,0:05:33.766
要

0:05:34.861,0:05:36.588
沺沺祝你生日快乐 宝贝

0:05:37.546,0:05:38.033
谢谢爸爸

0:05:39.170,0:05:40.359
沺沺生日快乐哦

0:05:41.564,0:05:42.684
祝你生日快乐 沺沺

0:05:42.684,0:05:43.625
谢谢奶奶啊

0:05:43.625,0:05:44.189
谢谢

0:05:51.372,0:05:52.449
多吃点哦沺沺

0:05:53.980,0:05:54.340
好

0:06:12.380,0:06:14.080
菜籽是什么

0:06:14.460,0:06:18.860
菜籽就是我们炒菜会用到的菜籽油

0:06:19.460,0:06:21.120
因为爸爸是厨师

0:06:22.540,0:06:24.480
你喜不喜欢爸爸做的菜

0:06:24.480,0:06:27.180
喜欢 爸爸有100个香

0:06:27.220,0:06:29.300
哦 炒的菜有100个香啊

0:06:29.300,0:06:30.080
嗯

0:06:31.380,0:06:35.340
等爸爸妈妈老了我就会洗碗还会炒菜

0:06:36.500,0:06:37.800
哦 真棒


```

**Comment by 3yearsyoung** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
沺沺5岁啦，做几道菜来庆祝一下！翻出女儿的照片回忆满满，我的小棉袄！
Cooking some dishes to celebrate 5th birthday for my daughter Tian Tian! Full of incredible memories!

简介
大家好，沺沺不知不觉都5岁了，现在都当姐姐了，真的长大了很多，大家看是不是越来越可爱！其实翻出之前的照片的时候才发现，自己其实也错过了很多，她2岁的时候正是我创业最忙的时候，每天不仅要正常上班还要熬夜拍视频剪视频，所以以至于2岁多的照片都找不到一张，说来真是惭愧，以后再忙也要有陪家人的时间。
Hello everyone, in the blink of an eye, my daughter Tian Tian has turned 5 years old. She’s been growing up so much and is now an older sister. Isn’t she more and more lovely? Looking at some of the photos previously taken, I realise that I have actually missed a lot. I was so occupied starting my own business when she was 2, and I had to spend extra time at night filming and editing videos after coming back from my day job. As a result, I can’t find any photo of Tian Tian at 2 years old and that is such a shame. I must always spend some time with my family in the future no matter how busy I will be.

字幕
0:00:01.420,0:00:02.600
哈喽大家好
Hello everyone

0:00:03.240,0:00:04.200
打个招呼宝贝
Say ‘hello’, my sweetheart

0:00:05.080,0:00:06.620
你说哈喽大家好你是谁
Tell them who you are

0:00:06.860,0:00:09.440
哈喽大家好我是沺沺
Hello everyone, I’m Tian Tian

0:00:09.600,0:00:10.700
嗯沺沺
Good job, Tian Tian

0:00:19.380,0:00:21.780
出生第一天
On the day of birth

0:00:24.320,0:00:26.320
三个月
Three months old

0:00:28.960,0:00:30.960
十一个月
Eleven months old

0:00:33.960,0:00:36.420
一岁
One year old

0:00:38.680,0:00:52.940
三岁半
Three and a half years old

0:00:53.400,0:01:22.360
四岁
Four years old

0:01:23.200,0:01:27.200
四岁半
Four and a half years old

0:01:28.620,0:01:32.500
五岁
Five years old

0:01:33.300,0:01:33.860
哈喽 大家好
Hello everyone

0:01:34.066,0:01:38.922
今天又请个假做一个我女儿喜欢吃的几个菜
I took another leave today to cook some of my daughter’s favourite dishes

0:01:39.514,0:01:40.737
这个是什么宝贝
What’s this, my sweetheart?

0:01:40.815,0:01:41.514
多宝鱼
It’s turbot

0:01:41.912,0:01:42.815
是什么多宝鱼
How shall I cook it?

0:01:43.747,0:01:45.281
你最喜欢怎么做这个
What’s your favourite version of turbot?

0:01:46.097,0:01:48.986
我最喜欢弄番茄酱做
My favourite is the one made with ketchup

0:01:49.223,0:01:52.407
番茄酱做 你说的是那个吧
Made with ketchup? You are talking about…

0:01:52.893,0:01:53.922
那个松鼠鱼对不对
The squirrel fish, right?

0:01:54.106,0:01:56.310
这个我们做多宝鱼 清蒸多宝鱼
But this is turbot, and we will steam it

0:01:56.902,0:01:59.970
今天我们做一个清汤牛肉丸
Today, we will make beef meatball bouillon

0:02:00.213,0:02:04.155
然后做一个清蒸多宝鱼 还有一个姜葱花甲
Steamed turbot, stir-fried clams with ginger and spring onion

0:02:04.155,0:02:07.893
然后再炒一些孩子比较喜欢吃的素菜
And some sautéed vegetables that my daughter loves to eat

0:02:08.533,0:02:10.669
今天是我女儿满5岁的生日
Today is my daughter’s 5th birthday

0:02:10.708,0:02:15.932
所以请个假 简简单单的做一个菜 做来今天中午吃
So I took the leave and I’m going to cook some simple dishes for lunch

0:02:17.941,0:02:20.262
我先切碎 沺沺等一下要不要来试一下
I’m mincing the beef first. Do you want to have a try later, Tian Tian?

0:02:20.902,0:02:21.310
要
Yes

0:02:21.932,0:02:22.291
算了吧
No, you don’t

0:02:22.310,0:02:26.165
你也来试 你敢切吗 那个刀很利的哦
Are you brave enough to have a try? That knife is very sharp

0:02:27.689,0:02:31.067
你不是跟爸爸说你长大了要当厨师吗
Haven’t you told dad that you want to be a chef when you grow up?

0:02:34.067,0:02:34.582
是不是
Yes?

0:02:34.951,0:02:35.446
是
Yes

0:02:36.728,0:02:38.504
那等你长大了我教你好不好
Then I will teach you how to use the knife once you grow up, deal?

0:02:38.504,0:02:39.116
好
Deal

0:02:45.747,0:02:47.262
我们站到这里看好不好
Shall we stand here and watch?

0:02:47.504,0:02:50.165
不要 葱妈妈也会伤心的
No, the ‘mom spring onion’ will be sad

0:02:50.233,0:02:51.844
还有葱妈妈
There is a ‘mom spring onion’?

0:02:51.844,0:02:56.174
你的意思是爸爸切了葱 葱妈妈要伤心是吗
You mean that the ‘mom spring onion’ will be sad if dad chops it?

0:02:56.320,0:02:58.650
不是 葱宝宝这个是
No, this is the ‘baby spring onion’

0:02:58.650,0:02:59.631
哦 这个是葱宝宝
Ok, this is the ‘baby spring onion’

0:02:59.825,0:03:00.320
嗯
Correct

0:03:01.582,0:03:03.359
爸爸 这是姜妈妈
Dad, this is the ‘mom ginger’

0:03:03.436,0:03:06.948
嗯 我会切得它很舒服的 它不会感到痛苦
Alright, I will make it comfortable and it won’t feel any pain when I cut it

0:03:10.912,0:03:13.660
这是多宝鱼宝宝 它也会伤心的
This is the ‘baby turbot’, and it will also be sad

0:04:43.274,0:04:45.429
沺沺 过来吃饭了 来
Come and eat lunch, Tian Tian

0:04:48.439,0:04:48.944
吃什么 沺沺
What do you want to eat, Tian Tian?

0:04:48.944,0:04:50.071
多宝鱼
Turbot

0:04:50.071,0:04:52.082
多宝鱼是不 爸爸给你弄
Good choice. Let dad grab some for you

0:04:53.518,0:04:54.450
吃撒吃撒
Help yourselves, guys

0:04:54.553,0:04:54.963
吃嘛
Sure

0:04:59.606,0:05:00.153
这个好吃噶
It tastes delicious

0:05:03.950,0:05:05.190
原先腥的你吃不来噶
You are not used to eating fish with strong flavour

0:05:06.678,0:05:09.491
沺沺 你知道你今天多少岁了吗
Tian Tian, do you know how old you are today?

0:05:09.559,0:05:09.970
知道
Of course

0:05:10.209,0:05:10.953
你今天几岁
How old are you?

0:05:11.389,0:05:11.885
5岁
Five

0:05:12.142,0:05:12.680
5岁啊
Five years old

0:05:13.416,0:05:14.963
5岁了是不是都长大了
Are you a grown-up now at five?

0:05:15.109,0:05:15.681
嗯
Yes

0:05:16.323,0:05:17.426
长大了还要不要吃糖
Do you still want to eat candies if you are a grown-up?

0:05:20.701,0:05:21.966
你说长大了不吃糖了
Tell him that you won’t candies because you’ve grown up

0:05:22.077,0:05:23.198
以后还要不要吃糖
Do you still want to eat candies in the future?

0:05:24.437,0:05:25.130
少吃糖
Eat less maybe

0:05:25.472,0:05:26.233
要少吃点
Yes, eat less

0:05:28.088,0:05:29.516
说她吃糖她心头不高兴
She’s not happy when we’re accusing her of eating candies

0:05:29.679,0:05:30.782
等下给你切蛋糕好不好
I will serve you the birthday cake in a minute, alright?

0:05:32.321,0:05:32.663
好
Alright

0:05:32.663,0:05:33.099
要不要吃
Do you want to eat the cake?

0:05:33.364,0:05:33.766
要
Yes

0:05:34.861,0:05:36.588
沺沺祝你生日快乐 宝贝
Happy birthday to you, Tian Tian, my sweetheart

0:05:37.546,0:05:38.033
谢谢爸爸
Thanks, dad

0:05:39.170,0:05:40.359
沺沺生日快乐哦
Happy birthday, Tian Tian

0:05:41.564,0:05:42.684
祝你生日快乐 沺沺
Happy birthday to you, Tian Tian

0:05:42.684,0:05:43.625
谢谢奶奶啊
Say ‘thank you, grandma’

0:05:43.625,0:05:44.189
谢谢
Thank you

0:05:51.372,0:05:52.449
多吃点哦沺沺
Have some more, Tian Tian

0:05:53.980,0:05:54.340
好
Ok

0:06:12.380,0:06:14.080
菜籽是什么
What’s rapeseed?

0:06:14.460,0:06:18.860
菜籽就是我们炒菜会用到的菜籽油
Rapeseed is used to make the rapeseed oil we use for cooking

0:06:19.460,0:06:21.120
因为爸爸是厨师
As dad is a chef

0:06:22.540,0:06:24.480
你喜不喜欢爸爸做的菜
Do you like the dishes dad cooks?

0:06:24.480,0:06:27.180
喜欢 爸爸有100个香
Yes, dad can make 100 kinds of aroma

0:06:27.220,0:06:29.300
哦 炒的菜有100个香啊
Oh, my dishes have 100 kinds of aroma?

0:06:29.300,0:06:30.080
嗯
Yes

0:06:31.380,0:06:35.340
等爸爸妈妈老了我就会洗碗还会炒菜
I will do the dishes and cook for you when mom and dad become old

0:06:36.500,0:06:37.800
哦 真棒
That’s fantastic, sweetheart
