### ISSUE TITLE
[老饭骨] 炙子炒面 - https://youtu.be/p9rEI5ezxQQ

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1159]
**视频链接**：https://youtu.be/p9rEI5ezxQQ

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•】好吃到可以摆地摊儿的炙子炒面！酱香浓郁、用料超足，撒上孜然，吃面比吃肉还香！|老饭骨

简介
小友们好，最近国内很流行摆地摊儿。老饭骨们也教大家一道夜市美食——炙子炒面，小友们学会也有摆摊儿的手艺咯！
炙子炒面是在炙子烤肉上加以创新的一道菜，面这么做出来，比肉还好吃！
这道菜用料丰富，虽然是面条，但还有牛肉垫底儿，当宵夜来吃妥妥的。
要注意的是，牛肉要想做的嫩，还得做好这几个细节，小友们快点击视频学起来！

字幕
1
00:00:00,000 --> 00:00:01,720
太漂亮了

2
00:00:01,720 --> 00:00:03,480
那叫一个地道

3
00:00:03,480 --> 00:00:05,280
一磨这个香味

4
00:00:05,280 --> 00:00:08,120
这面比这牛肉好吃

5
00:00:08,120 --> 00:00:09,640
炙子炒面 大爷

6
00:00:09,640 --> 00:00:12,880

7
00:00:12,880 --> 00:00:16,280
牛肉 牛外脊 顶刀切

8
00:00:16,280 --> 00:00:18,360
这个牛肉给它拍一下

9
00:00:18,360 --> 00:00:20,960
更容易入味了

10
00:00:20,960 --> 00:00:25,600
而且它把肉的质地给它拍松了

11
00:00:25,600 --> 00:00:27,240
它在传热的时候

12
00:00:27,240 --> 00:00:29,280
它不会（缩）再回不来了

13
00:00:29,280 --> 00:00:32,000
所以比较松 大爷说的太对了

14
00:00:32,000 --> 00:00:33,840
而且肉质特别嫩

15
00:00:33,840 --> 00:00:36,080
葱姜水来点

16
00:00:36,080 --> 00:00:39,120
黄酒 葱姜酒水

17
00:00:39,120 --> 00:00:40,800

18
00:00:40,800 --> 00:00:43,480
搁点盐 胡椒粉

19
00:00:43,480 --> 00:00:46,920
搁点鲜味汁 这牛肉更加鲜

20
00:00:46,920 --> 00:00:48,880
再来点蚝油 正好

21
00:00:48,880 --> 00:00:50,760
多了咸了 入味提鲜

22
00:00:50,760 --> 00:00:53,120
它有一定的黏度 包裹在一起

23
00:00:53,120 --> 00:00:56,120
食用小苏打 两克

24
00:00:56,120 --> 00:00:58,600
搁苏打起嫩的

25
00:00:58,600 --> 00:01:02,160
非常嫩了 如果说再腌上半个小时更嫩

26
00:01:02,160 --> 00:01:05,720
先给它上浆 来点香油 抓黏糊了

27
00:01:05,720 --> 00:01:11,160
葱姜酒水 多打点水没事 就这么让它往上抓

28
00:01:11,160 --> 00:01:13,080
抓完了还能吃

29
00:01:13,080 --> 00:01:15,160
再来点儿

30
00:01:15,160 --> 00:01:16,360
吃饱了再吃

31
00:01:16,360 --> 00:01:18,440
蛋清少许

32
00:01:18,440 --> 00:01:20,400
上了劲儿以后弄上淀粉

33
00:01:20,400 --> 00:01:23,280
放点玉米淀粉 锁住水分

34
00:01:23,280 --> 00:01:25,320
再给你封点油

35
00:01:27,440 --> 00:01:29,200
封上油就润了

36
00:01:29,200 --> 00:01:31,320
切点辅料 洋葱别太少了

37
00:01:31,320 --> 00:01:32,480
胡萝卜

38
00:01:32,480 --> 00:01:35,360
这葱丝来点 您这配料可不少啊

39
00:01:35,360 --> 00:01:37,680
这个咱就来源于炙子烤肉

40
00:01:37,680 --> 00:01:40,600
先把孜然给它焙一下 指着这个出香味

41
00:01:40,600 --> 00:01:42,560
小火慢慢焙 焙香了

42
00:01:42,560 --> 00:01:44,200
直接倒蒜臼子里

43
00:01:44,200 --> 00:01:46,360
这就比机器打出来的香啊

44
00:01:46,360 --> 00:01:48,400
看这一打直冒烟儿

45
00:01:48,400 --> 00:01:50,120
一磨这个香味

46
00:01:50,120 --> 00:01:51,080
熟芝麻

47
00:01:51,080 --> 00:01:53,520

48
00:01:53,520 --> 00:01:56,680
滑牛肉 锅必须得烧热了 已经冒烟了

49
00:01:56,680 --> 00:01:58,760
涮锅

50
00:01:58,760 --> 00:02:00,200
给倒回去

51
00:02:00,200 --> 00:02:02,920
润锅 润锅很重要

52
00:02:02,920 --> 00:02:05,560
即便是原来的油也得加上凉油

53
00:02:05,560 --> 00:02:07,160
多搁点牛肉片吧 喜兴

54
00:02:07,160 --> 00:02:08,480

55
00:02:08,480 --> 00:02:10,440
先别动 一点都没粘

56
00:02:10,440 --> 00:02:13,440
一抖落就开了 火候到了

57
00:02:13,440 --> 00:02:14,400

58
00:02:14,400 --> 00:02:16,400
这么大牛肉块 肯定香

59
00:02:16,400 --> 00:02:18,560
大爷你看它这肉还真嫩

60
00:02:18,560 --> 00:02:21,160
炙子 这是关键

61
00:02:21,160 --> 00:02:22,800
没炙子有这大铁板也行

62
00:02:22,800 --> 00:02:25,360
没铁板用砂锅也行

63
00:02:25,360 --> 00:02:28,920
没砂锅咱就炒完了搁盘儿里也一样

64
00:02:28,920 --> 00:02:31,000
关小火了

65
00:02:31,000 --> 00:02:35,000
放点油 烧的热热的 不热出不来香味

66
00:02:35,000 --> 00:02:38,160
再来点香油 二合油可香啊

67
00:02:38,160 --> 00:02:41,320
洋葱 现加这些不够咱再加

68
00:02:41,320 --> 00:02:43,400
先煸葱头

69
00:02:43,400 --> 00:02:46,640
胡萝卜也可以先加上 真香

70
00:02:46,640 --> 00:02:49,160
这时候牛肉搁进去

71
00:02:49,160 --> 00:02:52,280
来点酱油 入一下味

72
00:02:52,280 --> 00:02:53,840
这个菜绝对好吃

73
00:02:53,840 --> 00:02:56,560
胡椒粉

74
00:02:56,560 --> 00:03:00,000
为了口感 掐菜来点儿

75
00:03:00,000 --> 00:03:03,160
拌完油以后蒸二十分钟的面 提前蒸的

76
00:03:03,160 --> 00:03:05,480
千万别打盖儿 打盖儿就蒸呲了

77
00:03:05,480 --> 00:03:07,800
来点老抽

78
00:03:07,800 --> 00:03:09,240
市场买的切面

79
00:03:09,240 --> 00:03:11,840
在家都能做出酒店的味出来

80
00:03:11,840 --> 00:03:15,480
您说这两条 这个面绝对好吃 干香

81
00:03:15,480 --> 00:03:18,440
它有肉啊 我好几天都没吃着肉了

82
00:03:18,440 --> 00:03:20,000
还得加点 来点老抽

83
00:03:20,000 --> 00:03:21,880
不放盐

84
00:03:21,880 --> 00:03:25,400
鲜味汁来一点 这颜色好啊

85
00:03:25,400 --> 00:03:26,800
少来点香油

86
00:03:26,800 --> 00:03:27,800

87
00:03:29,240 --> 00:03:31,560
孜然粒多来点

88
00:03:31,560 --> 00:03:33,800
孜然跟芝麻 刚才捶好了的

89
00:03:33,800 --> 00:03:39,440
辣椒面 您看着面条 盖了帽儿了

90
00:03:39,440 --> 00:03:42,160

91
00:03:44,000 --> 00:03:46,760
整个都加进去吧 这才好吃呢

92
00:03:46,760 --> 00:03:48,200
这面条

93
00:03:49,680 --> 00:03:51,680
赶紧照相赶紧照相

94
00:03:51,680 --> 00:03:54,480
来着 关火关火

95
00:03:54,480 --> 00:03:55,720
太漂亮了这个

96
00:03:55,720 --> 00:03:57,840
那叫一个地道

97
00:03:57,840 --> 00:03:59,960

98
00:04:01,600 --> 00:04:05,560
我可吃了 您吃 您给多提意见大爷

99
00:04:05,560 --> 00:04:07,720

100
00:04:07,720 --> 00:04:10,600
刚强 真香

101
00:04:10,600 --> 00:04:15,080
二伯 这面比这牛肉好吃

102
00:04:15,080 --> 00:04:16,600
炒面一定油要大

103
00:04:16,600 --> 00:04:20,000
而且它的孜然辣椒面加的好

104
00:04:20,000 --> 00:04:22,280

105
00:04:22,280 --> 00:04:24,400
干香 牛肉这嫩

106
00:04:24,400 --> 00:04:29,920
这面这孜然辣椒面加的好

107
00:04:29,920 --> 00:04:32,160
这是一大创举

108
00:04:32,160 --> 00:04:33,760
大爷为什么今天戴着帽子

109
00:04:33,760 --> 00:04:37,200

110
00:04:37,200 --> 00:04:38,880
你知道什么意思吗

111
00:04:38,880 --> 00:04:40,720
我们俩用我们的行动来表扬你

112
00:04:40,720 --> 00:04:41,840
你的产品接地气儿

113
00:04:41,840 --> 00:04:43,520

114
00:04:43,520 --> 00:04:45,320
真香 太好吃了

115
00:04:45,320 --> 00:04:48,360

116
00:04:48,360 --> 00:04:50,240

117
00:04:57,320 --> 00:05:00,480
番茄酱和番茄沙司的区别

118
00:05:00,480 --> 00:05:01,800
区别大了

119
00:05:01,800 --> 00:05:03,800
因为番茄沙司是

120
00:05:03,800 --> 00:05:08,000
通过番茄酱进一步的进行调味

121
00:05:08,000 --> 00:05:09,960
形成一种调味品

122
00:05:09,960 --> 00:05:12,840
你看我们在 M记 开封菜

123
00:05:12,840 --> 00:05:15,960
吃的薯条 或者一些干炸食品

124
00:05:15,960 --> 00:05:19,320
大家蘸上番茄沙司吃 就很有味道

125
00:05:19,320 --> 00:05:21,760
但是我们做菜 用的番茄酱

126
00:05:21,760 --> 00:05:24,280
我们用一般不用番茄沙司

127
00:05:24,280 --> 00:05:26,880
我不知道他调的味道有什么变化

128
00:05:26,880 --> 00:05:29,280
所以番茄酱里面是没有味道的

129
00:05:29,280 --> 00:05:31,960
该加盐加盐 该加糖加糖

130
00:05:31,960 --> 00:05:32,920
该加醋加醋

131
00:05:32,920 --> 00:05:35,280
不管是做大甜酸 小甜酸

132
00:05:35,280 --> 00:05:37,960
包括果汁的一些菜肴

133
00:05:37,960 --> 00:05:39,840
特别恰到好处

134
00:05:39,840 --> 00:05:42,560
所以这个番茄酱和番茄沙司的区别

135
00:05:42,560 --> 00:05:45,200
就是一个调好味了 一个没调好味

136
00:05:45,200 --> 00:05:47,560
就自己在调制一些糖醋汁的话

137
00:05:47,560 --> 00:05:49,760
或者有一些手法的话

138
00:05:49,760 --> 00:05:52,600
它适当的少量的加一些番茄酱

139
00:05:52,600 --> 00:05:54,280
他为了中和一下这颜色

140
00:05:54,280 --> 00:05:57,920
但又不破坏味道

141
00:05:57,920 --> 00:06:01,880
后续的味道去自己加去

142
00:06:01,880 --> 00:06:03,520
行 下一个

143
00:06:03,520 --> 00:01:06,720
还有
```

**Comment by Losskywalker** [comment]
认领

**Comment by Losskywalker** [comment]
bot, please upload
_________________________

【国宴大师•】好吃到可以摆地摊儿的炙子炒面！酱香浓郁、用料超足，撒上孜然，吃面比吃肉还香！|老饭骨
[State Banquet MasterChef] fried noodles cooked on cast iron plate. So delicious that you can open a street food stall with it.

简介
小友们好，最近国内很流行摆地摊儿。老饭骨们也教大家一道夜市美食——炙子炒面，小友们学会也有摆摊儿的手艺咯！
炙子炒面是在炙子烤肉上加以创新的一道菜，面这么做出来，比肉还好吃！
这道菜用料丰富，虽然是面条，但还有牛肉垫底儿，当宵夜来吃妥妥的。
要注意的是，牛肉要想做的嫩，还得做好这几个细节，小友们快点击视频学起来！

Introduction
Dear fans, recently it is encouraged to set up your own street stalls in many Chinese cities. We are sharing a popular street food dish: fried noodles cooked on a cast iron plate. This is good enough for your own street food stall.
This fried noodle is based on the traditional cast iron BBQ and it tastes even better than the meat dish.
Indeed, we are cooking a noodle dish, but we have a lot of other ingredients such as beef. It is perfect for the midnight snacking.
We are also sharing some secret details to make sure that the beef is nice and tender.


字幕
1
00:00:00,000 --> 00:00:01,720
太漂亮了
Gorgeous

2
00:00:01,720 --> 00:00:03,480
那叫一个地道
That is how it should be.

3
00:00:03,480 --> 00:00:05,280
一磨这个香味
The fragrance bursts out after grinding

4
00:00:05,280 --> 00:00:08,120
这面比这牛肉好吃
The noodles are going to taste better than the meat.

5
00:00:08,120 --> 00:00:09,640
炙子炒面 大爷
Daye, we are making the fried noodles on the cast iron plate.

6
00:00:09,640 --> 00:00:12,880

7
00:00:12,880 --> 00:00:16,280
牛肉 牛外脊 顶刀切
Here is our beef short loin and we are slicing it against the grain

8
00:00:16,280 --> 00:00:18,360
这个牛肉给它拍一下
Let’s pound it a bit

9
00:00:18,360 --> 00:00:20,960
更容易入味了
For a better marination

10
00:00:20,960 --> 00:00:25,600
而且它把肉的质地给它拍松了
It also tenderizes the meat

11
00:00:25,600 --> 00:00:27,240
它在传热的时候
It prevents it from shrinking

12
00:00:27,240 --> 00:00:29,280
它不会（缩）再回不来了
When it hits the heat

13
00:00:29,280 --> 00:00:32,000
所以比较松 大爷说的太对了
So it stays loose (Daye is right)

14
00:00:32,000 --> 00:00:33,840
而且肉质特别嫩
And tender

15
00:00:33,840 --> 00:00:36,080
葱姜水来点
We need some ginger-spring onion water

16
00:00:36,080 --> 00:00:39,120
黄酒 葱姜酒水
That is, ginger and spring onion soaked in water and Huangjiu rice wine	

17
00:00:39,120 --> 00:00:40,800

18
00:00:40,800 --> 00:00:43,480
搁点盐 胡椒粉
Salt and pepper

19
00:00:43,480 --> 00:00:46,920
搁点鲜味汁 这牛肉更加鲜
A bit of umami seasoning to enhance the taste.

20
00:00:46,920 --> 00:00:48,880
再来点蚝油 正好
Some oyster sauce, perfect.

21
00:00:48,880 --> 00:00:50,760
多了咸了 入味提鲜
Just enough to bring more umami, if you put too much it will get salty.

22
00:00:50,760 --> 00:00:53,120
它有一定的黏度 包裹在一起
It also provides some stickiness.

23
00:00:53,120 --> 00:00:56,120
食用小苏打 两克
A bit of baking soda, about 2 grams

24
00:00:56,120 --> 00:00:58,600
搁苏打起嫩的
It further tenderizes the meat

25
00:00:58,600 --> 00:01:02,160
非常嫩了 如果说再腌上半个小时更嫩
It is already very tender, and it will keep tenderizing if you marinate it for another 30 minutes.

26
00:01:02,160 --> 00:01:05,720
先给它上浆 来点香油 抓黏糊了
Give it a good mix with some sesame oil

27
00:01:05,720 --> 00:01:11,160
葱姜酒水 多打点水没事 就这么让它往上抓
Then the garlic-spring onion water. It’s fine to add a bit more while you keep mixing it.

28
00:01:11,160 --> 00:01:13,080
抓完了还能吃
The meat can absorb even more water.

29
00:01:13,080 --> 00:01:15,160
再来点儿
Let’s add some more.

30
00:01:15,160 --> 00:01:16,360
吃饱了再吃
When the water was absorbed by the meat.

31
00:01:16,360 --> 00:01:18,440
蛋清少许
A little bit of egg white.

32
00:01:18,440 --> 00:01:20,400
上了劲儿以后弄上淀粉
Once the meat becomes sticky, we will add the starch.

33
00:01:20,400 --> 00:01:23,280
放点玉米淀粉 锁住水分
We are using corn starch to lock the moisture in the meat.

34
00:01:23,280 --> 00:01:25,320
再给你封点油
Then we add some oil

35
00:01:27,440 --> 00:01:29,200
封上油就润了
Look now juicy it is.

36
00:01:29,200 --> 00:01:31,320
切点辅料 洋葱别太少了
Now, we will chop some onions for the garnish.

37
00:01:31,320 --> 00:01:32,480
胡萝卜
Carrots

38
00:01:32,480 --> 00:01:35,360
这葱丝来点 您这配料可不少啊
Leek (that’s quite some garnish)

39
00:01:35,360 --> 00:01:37,680
这个咱就来源于炙子烤肉
This dish was inspired by the cast iron BBQ meat.

40
00:01:37,680 --> 00:01:40,600
先把孜然给它焙一下 指着这个出香味
Let’s roast the cumin first to extract the aroma.

41
00:01:40,600 --> 00:01:42,560
小火慢慢焙 焙香了
Bake it on low heat

42
00:01:42,560 --> 00:01:44,200
直接倒蒜臼子里
Pour it in the motar and grind

43
00:01:44,200 --> 00:01:46,360
这就比机器打出来的香啊
This is better than using an electronic grinder.

44
00:01:46,360 --> 00:01:48,400
看这一打直冒烟儿
Look at that “smoke”

45
00:01:48,400 --> 00:01:50,120
一磨这个香味
The aroma bursts out once you start grinding.

46
00:01:50,120 --> 00:01:51,080
熟芝麻
Cooked sesame

47
00:01:51,080 --> 00:01:53,520

48
00:01:53,520 --> 00:01:56,680
滑牛肉 锅必须得烧热了 已经冒烟了
Now let’s quickly fry the beef. The wok needs to be smoking hot.

49
00:01:56,680 --> 00:01:58,760
涮锅
Coat the wok with some oil.

50
00:01:58,760 --> 00:02:00,200
给倒回去
Pour this out

51
00:02:00,200 --> 00:02:02,920
润锅 润锅很重要
It’s very important it completely coat the wok with oil.

52
00:02:02,920 --> 00:02:05,560
即便是原来的油也得加上凉油
We must put a little bit cold oil into the warm oil.

53
00:02:05,560 --> 00:02:07,160
多搁点牛肉片吧 喜兴
Let’s cook more beef, it looks better.

54
00:02:07,160 --> 00:02:08,480

55
00:02:08,480 --> 00:02:10,440
先别动 一点都没粘
Don’t move it just yet, it won’t stick.

56
00:02:10,440 --> 00:02:13,440
一抖落就开了 火候到了
See how it separates once you shake it? It’s cooked perfectly.

57
00:02:13,440 --> 00:02:14,400

58
00:02:14,400 --> 00:02:16,400
这么大牛肉块 肯定香
Large pieces tastes so much better.

59
00:02:16,400 --> 00:02:18,560
大爷你看它这肉还真嫩
Look, Da Ye, the beef is really tender.

60
00:02:18,560 --> 00:02:21,160
炙子 这是关键
The cast iron plate is the key to this dish

61
00:02:21,160 --> 00:02:22,800
没炙子有这大铁板也行
Any metal plate will do

62
00:02:22,800 --> 00:02:25,360
没铁板用砂锅也行
Or a clay pot

63
00:02:25,360 --> 00:02:28,920
没砂锅咱就炒完了搁盘儿里也一样
If you don’t have any, then just fry it in your wok and plate it.

64
00:02:28,920 --> 00:02:31,000
关小火了
Turn the heat down

65
00:02:31,000 --> 00:02:35,000
放点油 烧的热热的 不热出不来香味
Let’s heat up the oil. You need hot oil to get the aroma out.

66
00:02:35,000 --> 00:02:38,160
再来点香油 二合油可香啊
Mix it with some sesame oil.

67
00:02:38,160 --> 00:02:41,320
洋葱 现加这些不够咱再加
Onions in. We have more if we need them.

68
00:02:41,320 --> 00:02:43,400
先煸葱头
Spring onion

69
00:02:43,400 --> 00:02:46,640
胡萝卜也可以先加上 真香
Now let’s put the carrots in. (smells good)

70
00:02:46,640 --> 00:02:49,160
这时候牛肉搁进去
Now it’s time for the beef.

71
00:02:49,160 --> 00:02:52,280
来点酱油 入一下味
Some soy sauce to bring up the flavor.

72
00:02:52,280 --> 00:02:53,840
这个菜绝对好吃
This is going to taste so good.

73
00:02:53,840 --> 00:02:56,560
胡椒粉
Pepper powder.

74
00:02:56,560 --> 00:03:00,000
为了口感 掐菜来点儿
Some bean sprouts for the texture.

75
00:03:00,000 --> 00:03:03,160
拌完油以后蒸二十分钟的面 提前蒸的
We mixed the noodles with some oil and steamed them for 20 mins in advance.

76
00:03:03,160 --> 00:03:05,480
千万别打盖儿 打盖儿就蒸呲了
Don’t put the lids on, otherwise the noodles may get soggy.

77
00:03:05,480 --> 00:03:07,800
来点老抽
Some dark soy sauce.

78
00:03:07,800 --> 00:03:09,240
市场买的切面
The noodles are freshly made.

79
00:03:09,240 --> 00:03:11,840
在家都能做出酒店的味出来
You can replicate the tastes from a restaurant.

80
00:03:11,840 --> 00:03:15,480
您说这两条 这个面绝对好吃 干香
You are right, this is going to turn out to be so delicious.

81
00:03:15,480 --> 00:03:18,440
它有肉啊 我好几天都没吃着肉了
Look at the beef. I haven’t eaten any meat for days.

82
00:03:18,440 --> 00:03:20,000
还得加点 来点老抽
We need some more soy sauce.

83
00:03:20,000 --> 00:03:21,880
不放盐
We don’t need any extra salt.

84
00:03:21,880 --> 00:03:25,400
鲜味汁来一点 这颜色好啊
We also need a bit more umami sauce. Look at the color.

85
00:03:25,400 --> 00:03:26,800
少来点香油
A bit of sesame oil.

86
00:03:26,800 --> 00:03:27,800

87
00:03:29,240 --> 00:03:31,560
孜然粒多来点
We need more cumin

88
00:03:31,560 --> 00:03:33,800
孜然跟芝麻 刚才捶好了的
Cumin grinded with sesame

89
00:03:33,800 --> 00:03:39,440
辣椒面 您看着面条 盖了帽儿了
Chili flakes in. Look at the noodles, how amazing is that!

90
00:03:39,440 --> 00:03:42,160

91
00:03:44,000 --> 00:03:46,760
整个都加进去吧 这才好吃呢
Just put them all in there for the flavor.

92
00:03:46,760 --> 00:03:48,200
这面条
Look at this noodle.

93
00:03:49,680 --> 00:03:51,680
赶紧照相赶紧照相
Quick, take a shot of this.

94
00:03:51,680 --> 00:03:54,480
来着 关火关火
Here we go, off the heat.

95
00:03:54,480 --> 00:03:55,720
太漂亮了这个
This is beautiful.

96
00:03:55,720 --> 00:03:57,840
那叫一个地道
That’s how it’s supposed to be.

97
00:03:57,840 --> 00:03:59,960

98
00:04:01,600 --> 00:04:05,560
我可吃了 您吃 您给多提意见大爷
May I? (Sure, let me know your feedbacks)

99
00:04:05,560 --> 00:04:07,720

100
00:04:07,720 --> 00:04:10,600
刚强 真香
It tastes wonderful.

101
00:04:10,600 --> 00:04:15,080
二伯 这面比这牛肉好吃
Er Bai, you know what, the noodles taste better than the beef.

102
00:04:15,080 --> 00:04:16,600
炒面一定油要大
To fry the noodles properly, you will need enough oil.

103
00:04:16,600 --> 00:04:20,000
而且它的孜然辣椒面加的好
And a perfect amount of cumin and chili flakes.

104
00:04:20,000 --> 00:04:22,280

105
00:04:22,280 --> 00:04:24,400
干香 牛肉这嫩
The beef is crispy, fragrant and tender.

106
00:04:24,400 --> 00:04:29,920
这面这孜然辣椒面加的好
With the cumin and chili flakes.

107
00:04:29,920 --> 00:04:32,160
这是一大创举
It’s a good innovation.

108
00:04:32,160 --> 00:04:33,760
大爷为什么今天戴着帽子
Why is Da Ye wearing a hat?

109
00:04:33,760 --> 00:04:37,200

110
00:04:37,200 --> 00:04:38,880
你知道什么意思吗
You know why?

111
00:04:38,880 --> 00:04:40,720
我们俩用我们的行动来表扬你
This is to complement you.

112
00:04:40,720 --> 00:04:41,840
你的产品接地气儿
The dish is also very down-to-earth.

113
00:04:41,840 --> 00:04:43,520

114
00:04:43,520 --> 00:04:45,320
真香 太好吃了
It is so delicious.

115
00:04:45,320 --> 00:04:48,360

116
00:04:48,360 --> 00:04:50,240

117
00:04:57,320 --> 00:05:00,480
番茄酱和番茄沙司的区别
What’s difference between tomato ketchup and tomato sauce?

118
00:05:00,480 --> 00:05:01,800
区别大了
Quite a large difference.

119
00:05:01,800 --> 00:05:03,800
因为番茄沙司是
Tomato sauce
120
00:05:03,800 --> 00:05:08,000
通过番茄酱进一步的进行调味
Is basically tomato ketchup with some further seasoning.

121
00:05:08,000 --> 00:05:09,960
形成一种调味品
It’s a type of seasoning sauce

122
00:05:09,960 --> 00:05:12,840
你看我们在 M记 开封菜
When we go to McDonalds or KFC

123
00:05:12,840 --> 00:05:15,960
吃的薯条 或者一些干炸食品
When we order some deep-fried food like French fries

124
00:05:15,960 --> 00:05:19,320
大家蘸上番茄沙司吃 就很有味道
It tastes better with the tomato sauce

125
00:05:19,320 --> 00:05:21,760
但是我们做菜 用的番茄酱
But we usually use tomato ketchup for cooking

126
00:05:21,760 --> 00:05:24,280
我们用一般不用番茄沙司
We hardly use tomato sauce

127
00:05:24,280 --> 00:05:26,880
我不知道他调的味道有什么变化
Because we do not know what extra seasoning is in the sauce.

128
00:05:26,880 --> 00:05:29,280
所以番茄酱里面是没有味道的
There is no extra seasoning in the tomato ketchup

129
00:05:29,280 --> 00:05:31,960
该加盐加盐 该加糖加糖
So we can control the amount of salt, sugar

130
00:05:31,960 --> 00:05:32,920
该加醋加醋
Or vinegar

131
00:05:32,920 --> 00:05:35,280
不管是做大甜酸 小甜酸
When we make the sweet-sour dishes

132
00:05:35,280 --> 00:05:37,960
包括果汁的一些菜肴
Or some dishes with fruits.

133
00:05:37,960 --> 00:05:39,840
特别恰到好处
It is better to use tomato ketchup.

134
00:05:39,840 --> 00:05:42,560
所以这个番茄酱和番茄沙司的区别
So, the difference between the two

135
00:05:42,560 --> 00:05:45,200
就是一个调好味了 一个没调好味
One is seasoned, one is not.

136
00:05:45,200 --> 00:05:47,560
就自己在调制一些糖醋汁的话
So when you are making some sweet-sour sauce

137
00:05:47,560 --> 00:05:49,760
或者有一些手法的话
Or some other cooking methods,

138
00:05:49,760 --> 00:05:52,600
它适当的少量的加一些番茄酱
You can add some tomato ketchup

139
00:05:52,600 --> 00:05:54,280
他为了中和一下这颜色
It adds a bit of the color

140
00:05:54,280 --> 00:05:57,920
但又不破坏味道
Without affecting the seasoning

141
00:05:57,920 --> 00:06:01,880
后续的味道去自己加去
So that you can control the seasoning yourself.

142
00:06:01,880 --> 00:06:03,520
行 下一个
OK next

143
00:06:03,520 --> 00:01:06,720
还有
What’s next
