### ISSUE TITLE
【美食作家王刚】新工作室 - https://youtu.be/REF7okx-gb4

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1160]
**视频链接**：https://youtu.be/REF7okx-gb4

视频时长5:17，预计发布时间为北京时间6月14日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
原工作室面积受限制决定换更大的厨房，初步计算毛坯装修中，大家敬请期待！

简介
大家好，为了能有更多更好的作品呈现给大家，最近一直在研究更换更大的后厨工作室，所以找到了一个郊区的厨房来作为新的工作室，大家敬请期待！在原来的工作室拍了几百个视频，说实在话其实是有感情的，但是人还是要往前看，为了更好的内容！大家如果对我现在的后厨工作室感兴趣的朋友可以看我之前拍过的一期揭秘视频：https://www.youtube.com/watch?v=SX9B7i8yG8g&vl=zh-Hans

字幕
0:00:01.167,0:00:02.046
哈喽 大家好

0:00:02.543,0:00:07.965
今天我们开车去一个离我们富顺有半个多小时的一个地方

0:00:08.520,0:00:10.208
准备增加一个工作室

0:00:11.040,0:00:14.936
现在这个工作室不够宽

0:00:15.225,0:00:19.768
后面想加一些其它的拍摄的一些菜加不了

0:00:20.901,0:00:22.855
所以今天去看一个大一点的厨房

0:00:23.930,0:00:25.664
是以前一个农家乐

0:00:26.416,0:00:27.514
农家乐的一个厨房

0:00:27.537,0:00:29.757
现在去把它租下来

0:00:29.849,0:00:32.809
然后拍更多的美食

0:00:35.248,0:00:39.410
这里什么都好位置也够宽也够大也够高

0:00:39.930,0:00:43.144
唯一一点就是太远有点偏僻

0:00:44.462,0:00:47.560
其实也好 拍的时候也不吵

0:00:48.127,0:00:50.115
就像我们现在工作室一样随时

0:00:50.578,0:00:55.421
门口有叫卖凉糕啊 凉面呀叫得很大声

0:00:55.606,0:00:59.971
他叫卖的时候我们就只有停下来等他走了我们再拍

0:01:00.080,0:01:02.334
所以这样也是挺麻烦的

0:01:04.138,0:01:05.930
越是到农村这个空气就越是好

0:01:20.658,0:01:24.739
就是按照酒店里面那种地板砖防滑的

0:01:24.832,0:01:29.260
要求有些啥子 技术方面呀或者

0:01:29.283,0:01:30.057
没得啥子要求的啊

0:01:30.057,0:01:31.734
就是把它铺平就可以了

0:01:33.653,0:01:36.080
就是这个这里如果是地板砖铺起来了

0:01:36.080,0:01:38.520
这个可能要往上面提

0:01:38.716,0:01:39.838
这个要把它垫起来

0:01:41.653,0:01:43.826
就相当于以这个为台子样

0:01:43.826,0:01:47.073
其它有啥子（要求）打灶啊这些

0:01:48.150,0:01:51.514
这上面帮我涂黑色的漆

0:01:52.439,0:01:53.491
上面涂黑的

0:01:56.265,0:01:57.526
黑油漆刷

0:01:57.618,0:01:58.670
嗯就是过刷

0:01:58.843,0:01:59.930
这个墙要弄起

0:01:59.965,0:02:00.797
墙不弄

0:02:00.878,0:02:02.462
墙上面喷不喷漆的话

0:02:05.664,0:02:07.364
你刷的时候注意到

0:02:07.468,0:02:09.560
餐厅这黑一坨 那儿花的（不好看）

0:02:09.664,0:02:13.144
你先刷中间撒 然后边边

0:02:18.739,0:02:22.739
这儿可能有接近一百个平方

0:02:24.531,0:02:26.635
这里是6米 我拉过的

0:02:27.445,0:02:28.138
这边是6米

0:02:28.248,0:02:29.838
这边好像

0:02:30.173,0:02:31.144
数砖嘛数砖

0:02:31.144,0:02:32.416
哦 数砖都数得出来

0:02:35.583,0:02:39.468
6米多 可能有6米3

0:02:41.271,0:02:44.728
你这个掉不掉哦

0:02:44.786,0:02:45.641
哪个哦

0:02:46.716,0:02:47.919
那水泥起缝了

0:02:48.138,0:02:49.317
它掉不掉下来嘛

0:02:49.653,0:02:51.317
害怕给它敲了

0:02:52.462,0:02:55.306
反正给它算工程嘛 算一哈

0:02:56.289,0:02:57.410
包工包料

0:03:01.028,0:03:03.317
你是整这地方做啥子安

0:03:03.341,0:03:06.670
我就是拍炒菜那个位置小了

0:03:06.728,0:03:10.104
宽度不够 这里6米就够了撒

0:03:10.150,0:03:13.237
我那边才3米多点 太窄了

0:03:19.953,0:03:20.705
4吨水泥

0:03:22.335,0:03:23.167
4吨噶

0:03:23.237,0:03:23.710
嗯

0:03:26.508,0:03:27.687
河沙10 吨啊

0:03:27.722,0:03:28.219
嗯

0:03:35.306,0:03:38.277
这哈是砖 砖130张

0:03:39.075,0:03:40.277
130张啊

0:03:41.803,0:03:43.710
1250 1300张嘛

0:03:43.710,0:03:44.393
1350

0:03:44.427,0:03:45.664
1350就是

0:03:46.138,0:03:47.098
油漆等会我去问了来

0:03:47.109,0:03:50.057
那个也不晓得要得到好多大概

0:03:50.901,0:03:54.497
100个平方的油漆给他说看要得到好多量

0:03:55.028,0:03:58.115
就这个人工费

0:04:00.023,0:04:01.572
人工好多

0:04:01.988,0:04:03.653
人工费这个要40一个平方

0:04:03.907,0:04:05.884
40嘎 100个就是4000块钱是不是

0:04:08.531,0:04:10.786
水泥500左右撒

0:04:11.237,0:04:13.028
500一吨噶

0:04:13.028,0:04:14.728
500加点油费

0:04:15.479,0:04:16.543
他包运哒

0:04:17.248,0:04:19.710
哪里要包运哦 不得

0:04:20.578,0:04:22.924
500 4吨

0:04:23.641,0:04:24.809
四五二千

0:04:25.317,0:04:26.196
2300嘛

0:04:28.104,0:04:29.391
2300拿得到撒

0:04:29.491,0:04:30.439
300块钱（油费）差不多

0:04:31.167,0:04:34.612
刚才我舅舅叫的2个师傅在这里看了一下

0:04:34.716,0:04:37.641
这里总共有90个平方

0:04:37.641,0:04:42.323
加上地板砖加上人工所有算下来大概一万五左右

0:04:42.416,0:04:43.664
就是材料什么的

0:04:43.768,0:04:47.826
这里以前是一个山庄的厨房

0:04:48.057,0:04:50.786
他们的厨房经营不下去了就没有做了

0:04:50.947,0:04:53.387
然后这里可以看一下这个厨具

0:04:53.526,0:04:56.208
已经荒废了很久了都已经生锈了

0:04:56.208,0:04:58.427
然后还有一些衣服不要的

0:04:59.433,0:05:03.953
其它的还好这里投入一点精力来打理一下

0:05:04.034,0:05:05.630
隔壁还有餐厅

0:05:05.791,0:05:07.861
餐厅的话下期视频给你们看一下

0:05:08.023,0:05:13.826
然后这里就等着师父明天买材料进来就可以做了

0:05:14.115,0:05:16.127
好了 本期视频就到这里了 拜拜


```

**Comment by WuStevenShengyang** [comment]
认领

**Comment by WuStevenShengyang** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
原工作室面积受限制决定换更大的厨房，初步计算毛坯装修中，大家敬请期待！
Switching to a new kitchen studio! Still decorating, coming soon!

简介
大家好，为了能有更多更好的作品呈现给大家，最近一直在研究更换更大的后厨工作室，所以找到了一个郊区的厨房来作为新的工作室，大家敬请期待！在原来的工作室拍了几百个视频，说实在话其实是有感情的，但是人还是要往前看，为了更好的内容！大家如果对我现在的后厨工作室感兴趣的朋友可以看我之前拍过的一期揭秘视频：https://www.youtube.com/watch?v=SX9B7i8yG8g&vl=zh-Hans
Hello everyone! In order to provide you with the best quality contents, I have been looking for a larger kitchen studio. Here I am, in a new studio! Although I have been filming hundreds of videos in the old studio, we have to look forward. If you are interestd in this new studio you can check my previous video: https://www.youtube.com/watch?v=SX9B7i8yG8g&vl=zh-Hans

字幕
0:00:01.167,0:00:02.046
哈喽 大家好
Hey, guys!

0:00:02.543,0:00:07.965
今天我们开车去一个离我们富顺有半个多小时的一个地方
Today we are driving to a place half an hour away from Fushun.

0:00:08.520,0:00:10.208
准备增加一个工作室
We are planning to open a new studio.

0:00:11.040,0:00:14.936
现在这个工作室不够宽
Our current studio is not wide enough.

0:00:15.225,0:00:19.768
后面想加一些其它的拍摄的一些菜加不了
We were unable to cook certain dishes in this studio.

0:00:20.901,0:00:22.855
所以今天去看一个大一点的厨房
So today I will show you a bigger kitchen studio.

0:00:23.930,0:00:25.664
是以前一个农家乐
It used to be an agritainment.

0:00:26.416,0:00:27.514
农家乐的一个厨房
One of its kitchens.

0:00:27.537,0:00:29.757
现在去把它租下来
And we rented it,

0:00:29.849,0:00:32.809
然后拍更多的美食
so we can make more videos.

0:00:35.248,0:00:39.410
这里什么都好位置也够宽也够大也够高
It's big and wide.

0:00:39.930,0:00:43.144
唯一一点就是太远有点偏僻
But it is a little too remote.

0:00:44.462,0:00:47.560
其实也好 拍的时候也不吵
It's not a big deal actually. It's quite.

0:00:48.127,0:00:50.115
就像我们现在工作室一样随时
Unlike our current studio,

0:00:50.578,0:00:55.421
门口有叫卖凉糕啊 凉面呀叫得很大声
always has people selling and yelling outside.

0:00:55.606,0:00:59.971
他叫卖的时候我们就只有停下来等他走了我们再拍
When people were yelling, we have to wait until they left.

0:01:00.080,0:01:02.334
所以这样也是挺麻烦的
It is annoying.

0:01:04.138,0:01:05.930
越是到农村这个空气就越是好
Air is pretty clean in the countryside.

0:01:20.658,0:01:24.739
就是按照酒店里面那种地板砖防滑的
Just like in the hotel, the ground will be paved with non-slippery tiles.

0:01:24.832,0:01:29.260
要求有些啥子 技术方面呀或者
Do you have any other technical requirements?

0:01:29.283,0:01:30.057
没得啥子要求的啊
Not really.

0:01:30.057,0:01:31.734
就是把它铺平就可以了
Just make them flat.

0:01:33.653,0:01:36.080
就是这个这里如果是地板砖铺起来了
The only thing is that after paving the tiles,

0:01:36.080,0:01:38.520
这个可能要往上面提
you might want to lift this up as well.

0:01:38.716,0:01:39.838
这个要把它垫起来
Lift this up.

0:01:41.653,0:01:43.826
就相当于以这个为台子样
So we basically take this as a platform.

0:01:43.826,0:01:47.073
其它有啥子（要求）打灶啊这些
Any other requirements on things like the kitchen stove?

0:01:48.150,0:01:51.514
这上面帮我涂黑色的漆
Paint the ceiling with black.

0:01:52.439,0:01:53.491
上面涂黑的
Black on top.

0:01:56.265,0:01:57.526
黑油漆刷
Black?

0:01:57.618,0:01:58.670
嗯就是过刷
Yes, just paint it in black.

0:01:58.843,0:01:59.930
这个墙要弄起
What about the walls.

0:01:59.965,0:02:00.797
墙不弄
Just leave them as they were.

0:02:00.878,0:02:02.462
墙上面喷不喷漆的话
You don't want to paint the walls?

0:02:05.664,0:02:07.364
你刷的时候注意到
Otherwise,

0:02:07.468,0:02:09.560
餐厅这黑一坨 那儿花的（不好看）
it has both black and other colors, which doesn't look good.

0:02:09.664,0:02:13.144
你先刷中间撒 然后边边
So you just paint the middle first, then the sides...

0:02:18.739,0:02:22.739
这儿可能有接近一百个平方
This place is about a hundred square meters.

0:02:24.531,0:02:26.635
这里是6米 我拉过的
Here is six meters. I have measured it.

0:02:27.445,0:02:28.138
这边是6米
Yea, six meters.

0:02:28.248,0:02:29.838
这边好像
And here,

0:02:30.173,0:02:31.144
数砖嘛数砖
you can just count the tiles.

0:02:31.144,0:02:32.416
哦 数砖都数得出来
Oh yes! I can just count the tiles.

0:02:35.583,0:02:39.468
6米多 可能有6米3
About six meters, maybe six meters and thirty centimeters.

0:02:41.271,0:02:44.728
你这个掉不掉哦
Will those fall off?

0:02:44.786,0:02:45.641
哪个哦
Which one?

0:02:46.716,0:02:47.919
那水泥起缝了
The concrete is cracking.

0:02:48.138,0:02:49.317
它掉不掉下来嘛
It will fall off.

0:02:49.653,0:02:51.317
害怕给它敲了
We will replace it.

0:02:52.462,0:02:55.306
反正给它算工程嘛 算一哈
It's part of the work.

0:02:56.289,0:02:57.410
包工包料
Including labors and materials.

0:03:01.028,0:03:03.317
你是整这地方做啥子安
What do you want to do in this place?

0:03:03.341,0:03:06.670
我就是拍炒菜那个位置小了
I am just filming cooking videos. The old studio is too small.

0:03:06.728,0:03:10.104
宽度不够 这里6米就够了撒
It's not wide enough. Here, six meters is enough.

0:03:10.150,0:03:13.237
我那边才3米多点 太窄了
The old studio is only three meters wide, which is way too narrow.

0:03:19.953,0:03:20.705
4吨水泥
Four tons of concrete.

0:03:22.335,0:03:23.167
4吨噶
Four tons?

0:03:23.237,0:03:23.710
嗯
Yea.

0:03:26.508,0:03:27.687
河沙10 吨啊
Sand, ten tons?

0:03:27.722,0:03:28.219
嗯
Yes.

0:03:35.306,0:03:38.277
这哈是砖 砖130张
130 pieces of tiles.

0:03:39.075,0:03:40.277
130张啊
130 tiles?

0:03:41.803,0:03:43.710
1250 1300张嘛
About 1250, 1300 tiles.

0:03:43.710,0:03:44.393
1350
1350.

0:03:44.427,0:03:45.664
1350就是
Yes, 1350.

0:03:46.138,0:03:47.098
油漆等会我去问了来
As for the paints, I will ask them later.

0:03:47.109,0:03:50.057
那个也不晓得要得到好多大概
I am not sure how much we need.

0:03:50.901,0:03:54.497
100个平方的油漆给他说看要得到好多量
I asked how much paint we need for a 100 square meter's room.

0:03:55.028,0:03:58.115
就这个人工费
And the cost of labor,

0:04:00.023,0:04:01.572
人工好多
is a lot.

0:04:01.988,0:04:03.653
人工费这个要40一个平方
It's like 40 RMB per square meter.

0:04:03.907,0:04:05.884
40嘎 100个就是4000块钱是不是
40? 100 square meter will cost 4000 RMB.

0:04:08.531,0:04:10.786
水泥500左右撒
The concrete is about 500 RMB.

0:04:11.237,0:04:13.028
500一吨噶
500 RMB per ton.

0:04:13.028,0:04:14.728
500加点油费
500 plus shipping fee.

0:04:15.479,0:04:16.543
他包运哒
Isn't it free shipping?

0:04:17.248,0:04:19.710
哪里要包运哦 不得
No, absolutely not.

0:04:20.578,0:04:22.924
500 4吨
500 RMB, 4 tons.

0:04:23.641,0:04:24.809
四五二千
Four times five-hundred makes two thousand.

0:04:25.317,0:04:26.196
2300嘛
2300 RMB?

0:04:28.104,0:04:29.391
2300拿得到撒
Can we get them for 2300 RMB though?

0:04:29.491,0:04:30.439
300块钱（油费）差不多
300 RMB shipping fee should be enough.

0:04:31.167,0:04:34.612
刚才我舅舅叫的2个师傅在这里看了一下
Earlier, my uncle let two masters to come check this place.

0:04:34.716,0:04:37.641
这里总共有90个平方
We have 90 squre meters here.

0:04:37.641,0:04:42.323
加上地板砖加上人工所有算下来大概一万五左右
Plus tiles and labors we need about 15 thousand RMB.

0:04:42.416,0:04:43.664
就是材料什么的
Like materials and other stuff.

0:04:43.768,0:04:47.826
这里以前是一个山庄的厨房
This place used to be a restaurant's kitchen.

0:04:48.057,0:04:50.786
他们的厨房经营不下去了就没有做了
But then the restaurant closed down.

0:04:50.947,0:04:53.387
然后这里可以看一下这个厨具
We can see those cooker

0:04:53.526,0:04:56.208
已经荒废了很久了都已经生锈了
have already gotten rusty.

0:04:56.208,0:04:58.427
然后还有一些衣服不要的
And some clothings.

0:04:59.433,0:05:03.953
其它的还好这里投入一点精力来打理一下
We need some time to decorate this place.

0:05:04.034,0:05:05.630
隔壁还有餐厅
There is also an restaurant next door.

0:05:05.791,0:05:07.861
餐厅的话下期视频给你们看一下
I will show you the restaurant in the next video.

0:05:08.023,0:05:13.826
然后这里就等着师父明天买材料进来就可以做了
And here we will just wait for the master to get all the materials.

0:05:14.115,0:05:16.127
好了 本期视频就到这里了 拜拜
That's all for this video, see you!
