### ISSUE TITLE
【美食作家王刚】炭烤兔子 - https://youtu.be/oacBFqRz4uU

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1161]
**视频链接**：https://youtu.be/oacBFqRz4uU

视频时长5:57，预计发布时间为北京时间6月15日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
过生日犒劳自己，碳烤两只兔子，四伯说味道很赞！(听说我兄弟要养兔子了，下次去弄两只回来)

简介
大家好，过生日那天给自己和家人烤了两只兔子，了解的朋友可能知道四川对兔子很钟爱，有非常多的吃法，其中炭火慢烤是我最喜欢的之一，可以完全激发出了食材本身的香味，再加上香辣调味非常安逸。有机会尝试的朋友一定不要错过，十分推荐！

字幕
0:00:01.172,0:00:04.874
今天我过生日就烤2个兔子简简单单的烤一下

0:00:05.343,0:00:06.572
这个兔子我已经改好刀了

0:00:07.809,0:00:11.244
现在准备一下姜葱把兔子腌一下

0:00:11.697,0:00:13.969
稍微腌几分钟就够了

0:00:16.079,0:00:17.768
切两三根大葱

0:00:21.139,0:00:22.506
大葱像这样不切断

0:00:23.177,0:00:24.664
切开就可以更容易入味

0:00:24.664,0:00:26.289
如果切碎了等下很难挑

0:00:33.853,0:00:37.890
我们现在只倒了料酒跟酱油

0:00:38.336,0:00:40.179
我觉得这样都差不多够了

0:00:40.258,0:00:44.091
因为待会我边烤的时候会再边刷酱料上去

0:00:47.991,0:00:50.263
这个肉我们大概腌了几分钟了

0:00:50.507,0:00:51.845
直接把它上烤架吧

0:00:52.251,0:00:56.815
因为我们这边吃兔子的话不喜欢腌得很咸

0:00:56.815,0:01:00.811
腌淡一点 待会再上麻辣味 再上咸味

0:01:02.028,0:01:03.002
这样子就可以了

0:01:03.529,0:01:04.705
放下去慢慢烤

0:01:04.888,0:01:06.288
 先干烤一会

0:01:06.490,0:01:11.920
干烤得表面有点熟了再刷其他的酱料

0:01:12.170,0:01:13.286
你估计要烤好久 四伯爷

0:01:14.239,0:01:15.943
烤一个多小时

0:01:16.430,0:01:19.979
个多小时啊 我估计也要差不多

0:01:29.208,0:01:31.298
你扇我扇是一样的撒

0:01:31.359,0:01:31.947
我给你扇

0:01:32.008,0:01:33.874
哎呀 我享受啊

0:01:34.117,0:01:34.726
啊

0:01:34.726,0:01:36.227
好嘛 我享受哈

0:01:40.527,0:01:43.488
我四伯爷说他要用这个尖刀划一下

0:01:43.488,0:01:45.455
这里都熟了你看 贴上去了这个

0:01:45.517,0:01:46.227
这个已经熟了

0:01:49.492,0:01:56.146
就放点酱油这个底味啊已经有百分之四五十了吧

0:02:00.466,0:02:03.306
哎呀 好烫 OK

0:02:04.604,0:02:06.916
现在我们这个烤起来就更快了

0:02:22.190,0:02:24.178
你那个还要烤一哈哦

0:02:24.178,0:02:25.943
这个肯定还没好撒

0:02:26.795,0:02:28.113
等会夹在上面烧

0:02:28.417,0:02:29.371
嗯 夹在上面烤

0:02:29.371,0:02:32.839
现在我们这个腰子已经快熟了 但是还差一点

0:02:33.245,0:02:36.024
我们这个兔子已经烤了一个小时了嘎

0:02:36.024,0:02:36.592
一个小时多点了

0:02:36.592,0:02:38.194
我们烤了一个小时了这个兔子

0:02:38.235,0:02:39.553
可以看一下这个颜色

0:02:40.385,0:02:42.210
这个颜色特别的漂亮

0:02:42.515,0:02:46.632
大概烤个十来分钟就可以刷我们的料

0:02:46.653,0:02:47.728
撒料就可以上（桌）了

0:02:47.910,0:02:51.243
待会直接把它倒出来用手把它撕开

0:02:51.257,0:02:52.657
撕开之后就可以吃了

0:02:52.920,0:02:55.922
非烫的你咋个撕哦 冷会儿来撕

0:02:55.943,0:02:57.484
筷子给它戳撒

0:02:58.965,0:03:00.709
我感觉这个兔子挺好吃的

0:03:02.494,0:03:04.198
这样子烤起肯定安逸哦

0:03:04.239,0:03:04.827
肯定好吃哦

0:03:05.070,0:03:06.835
你看这个颜色真的很漂亮

0:03:07.241,0:03:07.728
噶

0:03:07.790,0:03:08.336
嗯

0:03:08.965,0:03:09.756
很漂亮哦

0:03:10.689,0:03:14.543
下次去我兄弟家弄他2只兔子来烤一下

0:03:14.543,0:03:20.791
他最近不是开了一个兔子养殖场 好像是

0:03:21.298,0:03:22.900
下次去他家抓2只兔子

0:03:29.553,0:03:32.677
好了 我们这个兔子啊已经可以了

0:03:32.738,0:03:34.077
现在撒一点料上去

0:03:36.551,0:03:38.012
我先撒孜然粉哦四伯爷 

0:03:38.458,0:03:40.486
稍微少点的

0:03:40.588,0:03:44.726
孜然粉不关事可以稍微多点 这个是上味的

0:03:45.030,0:03:46.592
撒这个海椒面

0:03:46.713,0:03:48.154
少点少点这个东西

0:03:48.154,0:03:50.811
这个是要弄盐味的不关事

0:03:51.217,0:03:51.866
这个不辣 

0:03:52.150,0:03:53.549
这个不辣 等会辣很了

0:03:53.590,0:03:54.482
这个是不辣的

0:03:55.699,0:03:58.640
拿个放拿一个不放嘛等会是不是

0:03:58.640,0:03:59.087
要得啊

0:04:02.109,0:04:03.387
好 那个就不放了

0:04:04.239,0:04:05.354
芝麻

0:04:08.194,0:04:08.661
好

0:04:10.283,0:04:12.230
我怀疑我一筷子都可以把它夹出来

0:04:12.738,0:04:13.549
可以安

0:04:15.943,0:04:17.545
差点掉到地上了

0:04:19.513,0:04:22.026
哇塞 这个好脆啊

0:04:22.089,0:04:22.778
好脆哦噶

0:04:22.900,0:04:23.549
嗯

0:04:24.198,0:04:26.004
都听到这个脆的感觉了

0:04:28.580,0:04:29.675
四伯爷夹来试哈看

0:04:32.657,0:04:34.239
我用手撕哦

0:04:35.212,0:04:36.450
果然特别香

0:04:38.985,0:04:43.062
我再撒一点辣椒面上去

0:04:43.874,0:04:45.375
这个是我自己调的一个辣椒面

0:04:47.281,0:04:49.553
这样更加够味 里面的话也有味道

0:04:50.324,0:04:51.663
你还是整的兔腿腿呀

0:04:51.663,0:04:52.210
嗯

0:04:53.002,0:04:55.051
嗯 好香哦 好吃

0:04:55.233,0:04:56.369
哎呀 真的整得好吃

0:04:56.430,0:04:58.012
我是在那儿都整饿了

0:04:59.533,0:05:00.527
太好吃了

0:05:02.677,0:05:04.807
还安逸 我的牙口不好都整得动

0:05:04.928,0:05:05.517
是不 

0:05:05.618,0:05:06.227
是啊

0:05:06.653,0:05:07.728
真的还整得安逸

0:05:07.728,0:05:09.736
这个撕开 一撕就撕得开了

0:05:10.567,0:05:13.306
然后这只兔子我加了很多花椒

0:05:14.482,0:05:15.780
这一只的话就没有加

0:05:16.835,0:05:18.417
待会这只给我老婆带回去吃

0:05:24.097,0:05:25.111
这兔肉啊

0:05:25.111,0:05:25.557
嗯

0:05:26.795,0:05:27.302
可以 

0:05:27.484,0:05:28.012
好不好吃

0:05:28.012,0:05:28.498
好吃

0:05:30.365,0:05:32.576
好了本期视频就到这里 拜拜

0:05:32.718,0:05:33.245
拜拜

0:05:33.569,0:05:36.004
如果可以尝试的话 自己去烤一下

0:05:36.490,0:05:38.255
这个真的比（猪）肉还便宜

0:05:39.350,0:05:40.162
 好吃

0:05:42.129,0:05:46.267
又香又脆 我牙口不好的我都整得动

0:05:51.582,0:05:55.294
真的这个兔子这样子烤起安逸


```

**Comment by immoonancient** [comment]
@Katvava 请在这里认领

**Comment by Katvava** [comment]
认领

**Comment by Katvava** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
过生日犒劳自己，碳烤两只兔子，四伯说味道很赞！(听说我兄弟要养兔子了，下次去弄两只回来)

Reward myself on my birthday, BBQ two rabbits on the charcoal grill, uncle appraised the taste is awesome! (I heard that my brother will raise rabbit soon, I will take some back next time) 

简介
大家好，过生日那天给自己和家人烤了两只兔子，了解的朋友可能知道四川对兔子很钟爱，有非常多的吃法，其中炭火慢烤是我最喜欢的之一，可以完全激发出了食材本身的香味，再加上香辣调味非常安逸。有机会尝试的朋友一定不要错过，十分推荐！

Hi everyone, I grilled two rabbits on my birthday for myself and family. Some of you may know that Sichuan people are keen on rabbit meat. There are various ways of cooking rabbit, among which, BBQ rabbit on charcoal grill is my favorite. It totally releases the flavor of the ingredients, and the taste is amazing with the chilli and spices. Don’t miss it! If you have a chance, just try it. I highly recommend it!


字幕
0:00:01.172,0:00:04.874
今天我过生日就烤2个兔子简简单单的烤一下
I will grill two rabbits simply as today is my birthday

0:00:05.343,0:00:06.572
这个兔子我已经改好刀了
These are cut well

0:00:07.809,0:00:11.244
现在准备一下姜葱把兔子腌一下
Now let’s prepare some green onion and ginger and cure the rabbit a little bit

0:00:11.697,0:00:13.969
稍微腌几分钟就够了
Curing a couple of mins is enough

0:00:16.079,0:00:17.768
切两三根大葱
Cut two or three leeks 

0:00:21.139,0:00:22.506
大葱像这样不切断
The leek is not cut off like this 

0:00:23.177,0:00:24.664
切开就可以更容易入味
The cutted leek would release more flavour
 
0:00:24.664,0:00:26.289
如果切碎了等下很难挑
It’s hard to pick them out if they are fully cut off

0:00:33.853,0:00:37.890
我们现在只倒了料酒跟酱油
So far we only added cooking wine and soy sauce

0:00:38.336,0:00:40.179
我觉得这样都差不多够了
I think it’s good for now

0:00:40.258,0:00:44.091
因为待会我边烤的时候会再边刷酱料上去
Because I will brush some spice on it when grilling

0:00:47.991,0:00:50.263
这个肉我们大概腌了几分钟了
We have cured this meat for a couple of mins

0:00:50.507,0:00:51.845
直接把它上烤架吧
Directly put it on the grill net

0:00:52.251,0:00:56.815
因为我们这边吃兔子的话不喜欢腌得很咸
Because we don’t like curing rabbit to be too salty

0:00:56.815,0:01:00.811
腌淡一点 待会再上麻辣味 再上咸味
Cure it with less salt. Add spice and salt later

0:01:02.028,0:01:03.002
这样子就可以了
Just like this is OK

0:01:03.529,0:01:04.705
放下去慢慢烤
Put it down and grill it slowly

0:01:04.888,0:01:06.288
 先干烤一会
Firstly grill it without any spice

0:01:06.490,0:01:11.920
干烤得表面有点熟了再刷其他的酱料
After the surface was grilled well, brush the spices
0:01:12.170,0:01:13.286
你估计要烤好久 四伯爷
Can you estimate how long we need to grill it? Uncle.

0:01:14.239,0:01:15.943
烤一个多小时
One hour or a little bit more

0:01:16.430,0:01:19.979
个多小时啊 我估计也要差不多
More than one hour? I guess the same

0:01:29.208,0:01:31.298
你扇我扇是一样的撒
Fanning by you or by myself is the same

0:01:31.359,0:01:31.947
我给你扇
Let me fan you

0:01:32.008,0:01:33.874
哎呀 我享受啊
Aya, How enjoyable I am

0:01:34.117,0:01:34.726
啊
Ah

0:01:34.726,0:01:36.227
好嘛 我享受哈
Alright, I’d like to enjoy it

0:01:40.527,0:01:43.488
我四伯爷说他要用这个尖刀划一下
My uncle said he will use this sharp knife to cut it a little bit

0:01:43.488,0:01:45.455
这里都熟了你看 贴上去了这个
See this is cooked well, the one stick on the grill net

0:01:45.517,0:01:46.227
这个已经熟了
This one is grilled well

0:01:49.492,0:01:56.146
就放点酱油这个底味啊已经有百分之四五十了吧
The soy sauce let it contain about forty or fifty percent of foundation flavor

0:02:00.466,0:02:03.306
哎呀 好烫 OK
Aya so hot OK

0:02:04.604,0:02:06.916
现在我们这个烤起来就更快了
Now the grilling would be faster

0:02:22.190,0:02:24.178
你那个还要烤一哈哦
This one has to be grilled a little bit more

0:02:24.178,0:02:25.943
这个肯定还没好撒
This one is not cooked thoroughly

0:02:26.795,0:02:28.113
等会夹在上面烧
We can put it in the net to grill it

0:02:28.417,0:02:29.371
嗯 夹在上面烤
Right, put it in the net

0:02:29.371,0:02:32.839
现在我们这个腰子已经快熟了 但是还差一点
Now the kidney is almost good to eat, but still underdone a little bit  

0:02:33.245,0:02:36.024
我们这个兔子已经烤了一个小时了嘎
We have grilled these rabbits for about one hour, right?

0:02:36.024,0:02:36.592
一个小时多点了
A little bit more than one hour

0:02:36.592,0:02:38.194
我们烤了一个小时了这个兔子
We have grilled these rabbits for one hour already

0:02:38.235,0:02:39.553
可以看一下这个颜色
Look at the color

0:02:40.385,0:02:42.210
这个颜色特别的漂亮
The color is so pretty



0:02:42.515,0:02:46.632
大概烤个十来分钟就可以刷我们的料
We can brush our spice after 10 mins

0:02:46.653,0:02:47.728
撒料就可以上（桌）了
It is ready for eat once added the spice

0:02:47.910,0:02:51.243
待会直接把它倒出来用手把它撕开
Take it out and shred it by hand later

0:02:51.257,0:02:52.657
撕开之后就可以吃了
It’s ready for eat after shredded

0:02:52.920,0:02:55.922
非烫的你咋个撕哦 冷会儿来撕
It’s too hot to shred it by hand. Let’s do it after cooling down a little bit

0:02:55.943,0:02:57.484
筷子给它戳撒
Use chopsticks to shred it

0:02:58.965,0:03:00.709
我感觉这个兔子挺好吃的
I feel the rabbit meat must be yummy

0:03:02.494,0:03:04.198
这样子烤起肯定安逸哦
It must be very tasty as grilling it like this

0:03:04.239,0:03:04.827
肯定好吃哦
Must be tasty

0:03:05.070,0:03:06.835
你看这个颜色真的很漂亮
You see the color is really beautiful 

0:03:07.241,0:03:07.728
噶
Yeah

0:03:07.790,0:03:08.336
嗯
Yeah

0:03:08.965,0:03:09.756
很漂亮哦
Very beautiful 

0:03:10.689,0:03:14.543
下次去我兄弟家弄他2只兔子来烤一下
I will take two rabbits from my brother and grill them next time

0:03:14.543,0:03:20.791
他最近不是开了一个兔子养殖场 好像是
He opened a rabbit farm recently, it seems like

0:03:21.298,0:03:22.900
下次去他家抓2只兔子
Take two rabbits from him next time

0:03:29.553,0:03:32.677
好了 我们这个兔子啊已经可以了
All right, our rabbit is grilled thoroughly

0:03:32.738,0:03:34.077
现在撒一点料上去
Put some spices on it

0:03:36.551,0:03:38.012
我先撒孜然粉哦四伯爷 
I will firstly add some cumin powder, Uncle

0:03:38.458,0:03:40.486
稍微少点的
Just a little bit

0:03:40.588,0:03:44.726
孜然粉不关事可以稍微多点 这个是上味的
We can put more cumin powder, as it can enrich the flavor

0:03:45.030,0:03:46.592
撒这个海椒面
Add some chili powder

0:03:46.713,0:03:48.154
少点少点这个东西
Much less chili powder 

0:03:48.154,0:03:50.811
这个是要弄盐味的不关事
This is for making it salty and doesn’t matter

0:03:51.217,0:03:51.866
这个不辣
This one won’t by spicy  

0:03:52.150,0:03:53.549
这个不辣 等会辣很了
This is not spicy? It would become very spicy soon

0:03:53.590,0:03:54.482
这个是不辣的
This one is not spicy

0:03:55.699,0:03:58.640
拿个放拿一个不放嘛等会是不是
Just put chili powder in one rabbit, the other one is non-spicy, ok?

0:03:58.640,0:03:59.087
要得啊
Sure

0:04:02.109,0:04:03.387
好 那个就不放了
All right, I won’t put chili powder in that one

0:04:04.239,0:04:05.354
芝麻
Sesame

0:04:08.194,0:04:08.661
好
All right

0:04:10.283,0:04:12.230
我怀疑我一筷子都可以把它夹出来
I wonder whether I can take it out merely by chopstick in one time

0:04:12.738,0:04:13.549
可以安
Good job

0:04:15.943,0:04:17.545
差点掉到地上了
Nearly fell on the floor

0:04:19.513,0:04:22.026
哇塞 这个好脆啊
Wow this is so crispy

0:04:22.089,0:04:22.778
好脆哦噶
Very crispy

0:04:22.900,0:04:23.549
嗯
Yep


0:04:24.198,0:04:26.004
都听到这个脆的感觉了
I hear the scrispy sound

0:04:28.580,0:04:29.675
四伯爷夹来试哈看
Uncle, come and try it

0:04:32.657,0:04:34.239
我用手撕哦
I will use hand to shred it

0:04:35.212,0:04:36.450
果然特别香
It is really tasty 

0:04:38.985,0:04:43.062
我再撒一点辣椒面上去
I will put more chili powder on it

0:04:43.874,0:04:45.375
这个是我自己调的一个辣椒面
This is a chili powder mixed with other spices by myself

0:04:47.281,0:04:49.553
这样更加够味 里面的话也有味道
This can enrich the flavor, and the inside of meat can absorb more flavor

0:04:50.324,0:04:51.663
你还是整的兔腿腿呀
You are eating the rabbit leg

0:04:51.663,0:04:52.210
嗯
Yes

0:04:53.002,0:04:55.051
嗯 好香哦 好吃
Yeah, smells great, yummy

0:04:55.233,0:04:56.369
哎呀 真的整得好吃
Aya, it’s delicious

0:04:56.430,0:04:58.012
我是在那儿都整饿了
I am hungry while waiting for it

0:04:59.533,0:05:00.527
太好吃了
Tastes heavenly

0:05:02.677,0:05:04.807
还安逸 我的牙口不好都整得动
Though I have a chewing difficulty I can chew it easily, great

0:05:04.928,0:05:05.517
是不
Really 

0:05:05.618,0:05:06.227
是啊
Yes

0:05:06.653,0:05:07.728
真的还整得安逸
It’s really yummy

0:05:07.728,0:05:09.736
这个撕开 一撕就撕得开了
Shred this, just use your finger to shred it

0:05:10.567,0:05:13.306
然后这只兔子我加了很多花椒
I put a lot Sichuan pepper in this rabbit

0:05:14.482,0:05:15.780
这一只的话就没有加
And no Sichuan pepper in that one

0:05:16.835,0:05:18.417
待会这只给我老婆带回去吃
I will take that one to my wife

0:05:24.097,0:05:25.111
这兔肉啊
This rabbit meat, hmm

0:05:25.111,0:05:25.557
嗯
Yeah

0:05:26.795,0:05:27.302
可以
Good

0:05:27.484,0:05:28.012
好不好吃
Tasty?

0:05:28.012,0:05:28.498
好吃
Tasty

0:05:30.365,0:05:32.576
好了本期视频就到这里 拜拜
All right, the video ends here. Bye bye

0:05:32.718,0:05:33.245
拜拜
Bye Bye

0:05:33.569,0:05:36.004
如果可以尝试的话 自己去烤一下
If you get a chance, try to grill it

0:05:36.490,0:05:38.255
这个真的比（猪）肉还便宜
This is even cheaper than pork 

0:05:39.350,0:05:40.162
 好吃
Yummy

0:05:42.129,0:05:46.267
又香又脆 我牙口不好的我都整得动
It is crispy and full of aromatic, I can chew it even though my teeth condition is not good 

0:05:51.582,0:05:55.294
真的这个兔子这样子烤起安逸
Indeed, grilling rabbit in this way is amazing
