### ISSUE TITLE
[华农兄弟] 华农兄弟十天半个月都在下雨放几个地笼去看能不能装到鱼 - https://youtu.be/-gBo-P_TKgc

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1166]
https://youtu.be/-gBo-P_TKgc
<p>&#35270;&#39057;&#21457;&#24067;&#20110; June 13, 2020 at 10:40PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/-gBo-P_TKgc

#华农兄弟：十天半个月都在下雨，放几个地笼去，看能不能装到鱼
#Huanong Brothers: It has been raining for a fortnight. We place some traps, and see if we can catch any fish.

0:00:00.000,0:00:02.700
# 大家好  現在十天半個月都在下水
Hi everyone! The rain has been pouring for ten days or a fortnight recently.

0:00:03.380,0:00:05.620
# 現在都發大水了  這邊都一大片
And it's now flooding. The whole area here,

0:00:06.240,0:00:07.000
# 被淹掉了
is now underwater.

0:00:08.300,0:00:09.160
# 看一下有沒有魚
Let's see if there are any fish.

0:00:12.360,0:00:14.960
# 你看那裡  那個就是我們烤雞的地方
Have a look! There's where we roasted the pheasant.

0:00:15.440,0:00:17.620
# 幸好把那個爐子搬回來啦  要不然
Fortunately, we have taken the oven back. Otherwise,

0:00:17.980,0:00:19.400
# 爐子都不知道沖哪裡去啦
only God knows where it would be washed to.

0:00:20.620,0:00:22.580
# 再去看一下  看一下有沒有魚
Let's have a look again, and see if there are any fish,

0:00:23.120,0:00:24.620
# 有沒有魚抓  抓兩條上來
see if we can catch any, and catch a couple of them.

0:00:27.360,0:00:28.500
# 發那麼大的水
It's flooding so fiercely.

0:00:30.080,0:00:31.480
# 這下面肯定很多魚的
There must be a lot of fish down there.

0:00:32.160,0:00:32.900
# 抓不到啊
But I can't catch them.

0:00:40.860,0:00:43.860
# 我去看一下那個李子有沒有熟  兄弟家的李子 有幾個
I'm gonna see if the plums over there are ripe. These are my buddy's plums. There are a couple of them.

0:00:44.140,0:00:45.580
# 上次蓋了那個葉子的
I covered it with a leaf last time.

0:00:46.160,0:00:46.980
# 應該熟啦
I think they should be ripe now.

0:00:48.460,0:00:48.960
# 你看
Look!

0:00:49.320,0:00:50.380
# 上次我蓋了蓋子的
I gave it a cover last time.

0:00:50.760,0:00:51.400
# 就這個
It's this one.

0:00:52.260,0:00:53.880
# 它現在  不是很熟
It's now, not too ripe.

0:00:56.900,0:00:58.840
# 有點紅了 看到沒有
It's a bit red, see?

0:01:03.920,0:01:04.660
# 好脆呀
It's so crunchy!

0:01:05.380,0:01:06.840
# 還沒沒沒  不是很熟
It's still, still, still, not too ripe.

0:01:08.840,0:01:09.560
# 就還一一個
Just one here

0:01:13.760,0:01:14.580
# 這裡還有一個哦
Here's another one.

0:01:19.140,0:01:21.580
# 你看  這個都  都開裂啦
Look! This has already, already cracked open.

0:01:23.540,0:01:25.080
# 一半開裂  一般[SIC]沒開裂
Half has cracked open, but not the other half.

0:01:25.080,0:01:26.380
# 我吃這半沒開裂的
I'll have the other half.

0:01:29.080,0:01:29.920
# 這個好吃
It's tasty.

0:01:33.740,0:01:34.260
# 嗯
Um!

0:01:38.420,0:01:41.020
# 這個李子我們這邊叫 豬血李
We call this type of plums "pig blood plums" here.

0:01:46.500,0:01:48.380
# 跟那三華李不一樣的哦  你看
They're not the same as the Sanhua plums, look!

0:01:48.960,0:01:49.800
# 這個脆肉
This is crunchy.

0:01:51.980,0:01:53.160
# 三華李是軟肉
But Sanhua plums are soft.

0:01:54.400,0:01:55.040
# 這裡有一個
Here's another one.

0:01:57.340,0:01:58.780
# 爆掉啦  真的是
It's cracked. What a shame!

0:01:59.840,0:02:00.520
# 看一下還有沒有
Let me see if there are any more.

0:02:02.380,0:02:03.720
# 一個也是愛呀
Even just one is a sign of love.

0:02:10.760,0:02:11.560
# 一個都沒了
Not even one

0:02:17.120,0:02:19.660
# 看一下其它樹上  這棵樹上還有沒有
Let's see if there are any more in other trees, in this tree.

0:02:22.160,0:02:23.300
# 樹就那麼多
Tress are plenty.

0:02:26.500,0:02:29.080
# 你看  這個是我們以前經常烤東西的地方哦
Look! This is where we used to come grilling.

0:02:29.580,0:02:30.740
# 現在都被水沖啦
It's now flooded.

0:02:31.440,0:02:33.300
# 江乾淨一點  下次再來烤
Let the flood cleanse the place. We'll come grilling again next time.

0:02:35.380,0:02:37.420
# 今天早上水還更大  現在還好
The flood this morning was even more fierce. It's not too bad now.

0:02:38.080,0:02:39.620
# 退了一點  不然更大嘞
The flood has gone away a bit. Otherwise it would be much more fierce.

0:02:40.880,0:02:43.060
# 我回去拿幾個地籠來  放一下地籠
Let me go back and get some traps. I'm gonna put some traps here.

0:02:43.460,0:02:44.640
# 看能不能抓到一些魚
Let's see if we can catch some fish.

0:02:45.600,0:02:47.280
# 那麼大的水應該有魚
The flood is so fierce. There must be some big fish.

0:02:51.340,0:02:52.600
# 你看這個板栗
Have a look at the chestnuts here!

0:02:53.040,0:02:54.460
# 今年肯定很多板栗的
There must be a lot of chestnuts this year.

0:02:56.160,0:02:57.840
# 那麼小的樹就長那麼多板栗
There are so many chestnuts in such a small tree.

0:02:59.720,0:03:00.720
# 一樹都是哦
All over the tree

0:03:01.500,0:03:03.220
# 秋天就是收獲的季節
Autumn will be the harvesting season.

0:03:04.900,0:03:06.060
# 以後我們就來摘
We can come and pick them later.

0:03:17.120,0:03:18.460
# 把這個刀磿一下
I'm now sharpening the knife.

0:03:21.520,0:03:23.460
# 剛沒那個  沒有誘餌哦
I've just run out of, you know, run out of baits.

0:03:23.860,0:03:25.440
# 蚯蚓現在下雨又挖不到
And it's not possible to catch any earthworms in rainy days.

0:03:26.380,0:03:30.440
# 剛好上面有鴨子  把那個鴨子  割點它的肉來  做誘餌
It just so happens that there are ducks up there. Let me cut off some meat, from a duck, to be my bait.

0:03:32.280,0:03:36.440
# 吃肉的  吃肉的魚  它會進那個  就會騙進地籠裡面去
The carnivorous, carnivorous fish, are gonna, I mean, will be deceived into the traps.

0:03:36.780,0:03:37.560
# 把它抓起來
Then I can catch them.

0:03:39.480,0:03:42.600
# 黃鱔啊  蛇頭魚呀 鯰魚呀
The eels, the snakehead fish, the catfish,

0:03:43.200,0:03:45.800
# 還有那些小魚呀  它們都會進去吃
and also the small fish, they'll be going into the traps,

0:03:46.800,0:03:47.580
# 吃鴨肉的
for the duck meat.

0:03:50.360,0:03:51.880
# 等下我去抓個鴨子上來
I'm gonna catch a duck.

0:03:56.780,0:03:57.360
# 你看
Look!

0:03:58.180,0:04:00.000
# 這個鴨子  現在越來越瘦
This duck, is now getting skinny day by day.

0:04:00.940,0:04:04.360
# 鴨肉我吃膩啦  我換點魚肉來  一樣的其實
I get tired of duck. So now I exchange it for some fish. It's the same, actually.

0:04:05.660,0:04:07.100
# 這個鴨肉砍好(註︰沒有原字幕)
The duck has now been chopped up.

0:04:09.300,0:04:11.020
# 取了那麼一點點  剩下的
I just take a tiny little bit here. The rest,

0:04:11.440,0:04:12.180
# 我自己吃
is for me.

0:04:18.080,0:04:19.420
# 拿個袋子來裝起來
Let me put them into a bag.

0:04:28.440,0:04:30.360
# 這個鴨子  一半都去了
The duck, half of it is gone.

0:04:30.640,0:04:33.060
# 這裡還有2個地籠  一直都在這裡
Here are two more traps. They've always been here.

0:04:47.460,0:04:48.640
# 刀也帶過去
I'll take the knife as well.

0:05:12.440,0:05:14.980
# 這個水都漲了一半多  那麼深啦
The water here is raised by a half. It's so deep now.

0:05:15.700,0:05:17.800
# 等下我要  脫鞋子下去才行啦
I'll need to, I have to take off my shoes.

0:05:18.480,0:05:19.200
# 這裡還有
Here as well

0:05:20.540,0:05:22.420
# 放點肉  放點肉下去
Put some meat, put some meat into the trap.

0:05:25.120,0:05:26.420
# 它們才會進來玩
Then they'll have fun in the trap.

0:05:27.340,0:05:29.260
# 不放點肉下去它們不進來
They won't be coming in if there isn't any meat.

0:05:32.000,0:05:32.760
# 夠了
Enough

0:05:53.340,0:05:54.200
# 綁住這個
Tie it here.

0:05:59.860,0:06:02.420
# 我們去上面  上面放地籠
Let's go up there, put some traps up there.

0:06:03.920,0:06:05.060
# 上面還有個地方
There are more place up there.

0:06:06.220,0:06:09.660
# 褲子都濕啦  沒事  等下回去就洗澡
My pants have got wet. No worries. I'm gonna take a shower when I get back.

0:06:09.900,0:06:11.560
# 你看  就是那個水潭
Look! It's the pond over there.

0:06:12.260,0:06:13.880
# 那水潭肯定很多蛇頭魚的
There must be a lot of snakehead fish in that pond.

0:06:34.900,0:06:38.520
# 你看  這裡搞的 搞的像  像  像個雨林一樣
Look! It has become, become something like, like, like a rain forest here.

0:06:54.260,0:06:55.260
# 這個最大的
This is the largest one,

0:06:56.160,0:06:58.240
# 最大的  給它丟中間
the largest one. Put it right in the middle.

0:07:05.840,0:07:07.960
# 這一個  一個就放滿啦
Just one, one, and it fills up the pond.

0:07:20.340,0:07:21.940
# 這裡  這裡也放一個
Here, let me put one here as well.

0:07:22.760,0:07:23.880
# 這裡那麼深
The water is so deep here.

0:07:41.160,0:07:43.220
# 哎  夠啦  大塊吃肉啊
Ay! Enough! Have a big piece of meat!

0:07:43.900,0:07:46.060
# 這一塊給它  大塊肉給你們吃
Leave them this piece. I'm gonna give you guys big pieces of meat.

0:07:51.880,0:07:53.160
# 可以  肉
Alright! No more,

0:07:53.980,0:07:54.620
# 沒啦
meat.

0:08:00.140,0:08:01.240
# 這一個放在這裡
I'm gonna put this one here.

0:08:15.120,0:08:18.960
# 等下搞了個大貨  大魚  跑了怎麼辦嘞
It would be too bad if I have a big one, a big fish and it runs away.

0:08:27.120,0:08:29.420
# 明天  明天再過來看
Tomorrow, let's come again tomorrow.

0:08:30.040,0:08:32.480
# 看明天  肯定有魚的
Let's see. There must be fish tomorrow.

0:08:33.640,0:08:35.460
# 現在發了大水  魚都喜歡出來玩
When it floods, the fish will come out to have fun.

0:08:37.020,0:08:38.540
# 出來玩它就看到這個食物
When they come out to have fun, they'll see the food.

0:08:38.840,0:08:40.760
# 看到這個食物它就很想吃
When they see the food, they'll crave for it.

0:08:42.100,0:08:43.620
# 很想吃它就進來籠子
And when they crave for it, they'll get into the traps.

0:08:44.060,0:08:44.760
# 剛剛好
Perfect!

0:08:45.980,0:08:46.940
# 第二天
The next day

0:08:46.960,0:08:49.300
# 你看  今天天晴啦 我去收一下地籠
Look! It's sunny today. We're gonna get back the traps.

0:08:49.800,0:08:52.980
# 借了兄弟的這個  這個  這個水  水衣
I've borrowed the, this is, this water, water jacket from the buddy.

0:09:00.780,0:09:01.820
# 全副武裝
Full gear!

0:09:05.640,0:09:07.260
# 誒呀  好像看到螃蟹啦
Eya! It seems that I see some crabs.

0:09:08.740,0:09:10.240
# 你看  螃蟹
Look! Crabs,

0:09:11.240,0:09:12.280
# 好幾個螃蟹哦
a couple of crabs.

0:09:15.160,0:09:17.900
# 你看  好多這個螃蟹  看看一二三四
Look! A lot of this kind of crabs. See? One, two, three, four.

0:09:18.900,0:09:19.800
# 等會我帶回去
Let me take them back.

0:09:24.400,0:09:25.180
# 這個有沒有
Are there any here?

0:09:31.980,0:09:32.760
# 全是小魚
All are small fish,

0:09:33.460,0:09:34.340
# 沒有大魚
no big fish

0:09:35.340,0:09:36.520
# 難搞哦  這個
It's, no good.

0:09:37.820,0:09:38.320
# 你看
Look!

0:09:38.860,0:09:41.140
# 螃蟹 小魚  好多
A lot of crabs, small fish...

0:09:41.480,0:09:42.880
# 看一下  最後一副網
Let's see, how the last trap is doing.

0:09:53.880,0:09:54.380
# 沒有
Nothing

0:09:55.520,0:09:58.360
# 我們把這個帶回去  這個一條魚都沒有的   這裡
Let's take it back. Here's, here's not even one fish.

0:10:20.120,0:10:22.900
# 嗯  這些魚不喜歡吃鴨肉  是不是
Um! I bet that these fish don't like duck meat at all, right?

0:10:27.500,0:10:28.660
# 就幾條泥鰍
Just a few loaches

0:10:31.860,0:10:32.820
# 虧大了
Too bad!

0:10:34.100,0:10:35.680
# 你看  一隻鴨子搞下去
Look! I've invested one whole duck,

0:10:38.040,0:10:39.160
# 一條魚都沒搞到
but I have not even one fish in return.

0:10:41.360,0:10:42.500
# 這個有點大哦
This one is a bit too big.

0:10:44.820,0:10:46.580
# 哇  這個魚就小蠻的  你看
Wa! Here are quite a lot of fish, look!

0:10:47.360,0:10:47.940
# 有一條
Here's a,

0:10:48.800,0:10:50.400
# 有一條鯰魚  還有螃蟹
a catfish, and some crabs.

0:10:51.780,0:10:53.120
# 看一下  還有一個籠子
Let's have a look! There' still one more trap.

0:10:58.380,0:10:59.460
# 哎呀  有魚有魚
Aya! Fish, fish!

0:11:07.080,0:11:08.400
# 額  有一條蛇頭魚
Eh! Here's a snakehead fish,

0:11:09.100,0:11:10.100
# 還有一個鯰魚
and also a catfish.

0:11:12.680,0:11:13.680
# 這個可以呦
It's not bad!

0:11:14.480,0:11:15.320
# 搞了三條
So we have three fish,

0:11:16.320,0:11:17.160
# 三條大的
three big fish.

0:11:19.840,0:11:20.980
# 把這個  收一下
Let me, pack them up.

0:11:25.340,0:11:27.140
# 你看  我用這個來裝  裝這個魚
Look! I'm gonna put, put the fish into this pot.

0:11:38.700,0:11:39.940
# 這  有魚
Yea, fish here.

0:11:49.260,0:11:50.060
# 蛇頭魚
Snakehead fish

0:11:53.240,0:11:54.280
# 這條夠大  這個
This is really big, this one.

0:11:57.160,0:11:58.140
# 還有小魚嘞
And also some small fish

0:12:03.520,0:12:04.500
# 有螃蟹
Some crabs here

0:12:27.760,0:12:28.840
# 搞的肉都搞了
The meat, I've taken,

0:12:29.420,0:12:31.640
# 搞了兩斤  魚就搞了那麼一點點
I've taken a kilogram of meat, only to have just a tiny little bit of fish here.

0:12:35.620,0:12:36.860
# 把這個網曬一下
I'm gonna dry the traps under the sun.

0:12:38.300,0:12:39.220
# 一天打魚
One day fishing,

0:12:40.120,0:12:41.100
# 三天都在曬網
then three days drying the traps

0:12:43.120,0:12:43.640
# 曬乾
Dry them,

0:12:44.280,0:12:45.260
# 下次我們繼續
and let's go again next time.

0:12:52.060,0:12:53.520
# 你看  這幾條就養著
Look! I'll keep these couple of fish here.

0:12:54.480,0:12:56.460
# 像這樣的蛇頭魚我就把它養著
It's a good snakehead fish. So I'm gonna keep it here.

0:13:00.340,0:13:01.020
# 這個也是
And this one too

0:13:03.520,0:13:05.180
# 誒  不聽話啊  這條
Ey! It's naughty, this fish.

0:13:05.920,0:13:07.180
# 來  到這裡來
C'mon! Come here!

0:13:08.340,0:13:09.120
# 還有一條
One more

0:13:14.020,0:13:17.140
# 這些小魚  全部用來  把它全部煎掉它去
These small fish, are all... I'm gonna fry them all.

0:13:18.220,0:13:19.180
# 這些魚很好吃的呦
These fish are really tasty.

0:13:20.500,0:13:21.880
# 味道還是很OK的
The taste is quite okay.

0:13:24.280,0:13:27.040
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.
