### ISSUE TITLE
【美食作家王刚】 看新工作室全貌 - https://youtu.be/UjFJekjW40Q

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1170]
**视频链接**：https://youtu.be/UjFJekjW40Q

视频时长6:29，预计发布时间为北京时间6月17日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
带大家看全新工作室的完整面貌，加起来共有800多平方米，期待以后能发挥出它最大的能量

简介
大家好，新工作室已经动工了，正式开始翻新装修，如果一切顺利很快就可以完工，这次带大家看看全貌。因为这个地方原来是用作为农家乐，所以基本的设备都还齐全，整体环境很满意，不过问题还是有不少的，慢慢一个个克服，不过暂时还没有打算对外营业，先专心做好内容，大家敬请期待！

字幕
0:00:36.500,0:00:38.904
哈喽大家好 最近很开心

0:00:39.412,0:00:41.691
 租了一个以前旧的山庄

0:00:41.698,0:00:44.397
这个山庄放了两三年一直没有打理

0:00:44.865,0:00:48.282
所以我现在把它接(手）过来做些事情

0:00:48.810,0:00:50.924
这里可以看一下环境还很不错

0:00:51.398,0:00:54.560
只不过就是荒废了一段时间杂草丛生 

0:00:54.861,0:00:56.373
到时候我们再修整一下

0:00:56.692,0:01:00.358
正好今天厨房的师傅已经过来放地板砖

0:01:00.391,0:01:01.913
放完地板砖就可以进场

0:01:02.314,0:01:03.990
好 我带你们看一下这里面

0:01:06.132,0:01:08.236
一进来这里是一个桥

0:01:08.728,0:01:12.255
桥下面有很多金鱼 这里面有很多金鱼

0:01:12.419,0:01:14.833
而且我刚才看到有一条金鱼可能有一两斤

0:01:15.389,0:01:16.619
黄色的金鱼很大

0:01:19.544,0:01:23.535
然后进来了之后这里是一个前庭 很宽

0:01:24.209,0:01:25.430
看起来比较舒服

0:01:28.091,0:01:29.922
这个大厅层高非常的高啊

0:01:30.359,0:01:32.528
就是现在大夏天的话都一点都不热

0:01:33.075,0:01:36.646
然后这个是玻璃的透光性特别好

0:01:37.321,0:01:39.817
然后这里原先的老板他设计得很好

0:01:39.863,0:01:41.849
他这边是进风口 一个水冷的

0:01:41.849,0:01:44.063
然后那边后面有抽风机

0:01:44.419,0:01:46.873
唯一的一个不好的就是这里面的

0:01:47.005,0:01:49.275
以前的花花草草 现在都变成了大树了

0:01:49.858,0:01:53.193
我们来看一下这是什么树 具体我也不知道

0:01:53.193,0:01:54.405
应该是观赏树吧

0:01:57.011,0:01:58.653
因为这里面层高特别高

0:01:58.678,0:02:00.922
所以它的灯没有说从上面吊下来 

0:02:00.922,0:02:02.259
全部是做的这种路灯

0:02:02.964,0:02:05.688
这种路灯看起来感觉也不错

0:02:06.683,0:02:08.616
然后真正吃饭的厅在这里面

0:02:09.277,0:02:11.856
这里面可以摆差不多十几二十张桌子

0:02:12.517,0:02:13.977
还有边上的一些卡座

0:02:14.130,0:02:18.212
总共加起来可能 可以摆上三到四十桌

0:02:18.641,0:02:23.007
然后大家看一下这里有条沟

0:02:23.508,0:02:27.039
这条沟是他们设计来养鱼的

0:02:27.061,0:02:29.059
到时候这里我也把它水放起来

0:02:29.429,0:02:33.992
放起来养一些我们餐厅到时候能够做菜的鱼

0:02:33.992,0:02:35.953
全部就养在这个里面 再养一些金鱼

0:02:38.300,0:02:39.288
然后看一下这边

0:02:39.309,0:02:43.516
这个有2468 有8个抽风机

0:02:44.104,0:02:45.673
大家看一下这些桌子

0:02:46.400,0:02:47.766
其实都是挺好的

0:02:48.245,0:02:54.072
我们做餐厅的这些东西虽然说你看着这是旧的很旧

0:02:54.108,0:02:55.510
如果你去买的话 特别贵

0:02:55.924,0:02:59.404
比如这几张桌子凳子这里要花很多钱

0:03:00.886,0:03:01.939
这里有个亭子

0:03:03.312,0:03:05.325
这个亭子应该是用来做观赏的

0:03:07.540,0:03:12.212
然后这条沟从那边一直到这边有很长一截

0:03:14.021,0:03:16.462
这个厅大概有500个平方

0:03:16.789,0:03:19.615
有500个平方 层高应该有六七米

0:03:20.421,0:03:23.501
就是进来了之后不会感觉压抑

0:03:23.857,0:03:25.085
现在我带大家看一下厨房

0:03:27.184,0:03:28.383
看一下我们这里面

0:03:29.059,0:03:31.689
师父现在涂这个墙已经涂到这边来了

0:03:32.546,0:03:35.343
然后那边的师傅在负责放砖

0:03:35.445,0:03:38.641
这里大概全部弄下来要两三天吧

0:03:39.041,0:03:42.738
要两三天 地砖放好了之后还要让它干两三天

0:03:43.450,0:03:45.174
然后我们这些设备才可以运进来

0:03:45.426,0:03:46.509
这里还有一套厨具

0:03:47.039,0:03:50.061
这套厨具也是以前剩下的

0:03:50.374,0:03:53.745
看起来是很旧 但是这个不是很旧

0:03:54.471,0:03:57.406
看起来旧而已 只是长时间不用有的生锈了

0:03:57.620,0:04:01.245
到时候我们烧一点烧碱把那些锈就可以把它除掉

0:04:01.416,0:04:04.417
然后也可以用 我已经试过了这个灶是没有问题的

0:04:05.114,0:04:06.657
我带大家去看一下二楼

0:04:06.657,0:04:09.378
这个厨房的话面积有差不多100个平方米

0:04:09.778,0:04:10.795
然后去看一下二楼

0:04:12.822,0:04:17.624
这些东西都是上一任老板留下来的锅碗瓢盆

0:04:19.433,0:04:20.319
这边是厕所

0:04:25.223,0:04:26.531
然后我们上二楼看一下

0:04:29.509,0:04:31.551
这个二楼非常的大

0:04:32.037,0:04:33.294
就是下面是厨房

0:04:33.352,0:04:36.040
这里是二楼 有个棚

0:04:36.556,0:04:39.825
这上面应该用不上 地方太大了

0:04:40.697,0:04:43.182
总共加起来这里有厨房

0:04:43.182,0:04:47.286
加这个二楼加厅总共差不多有800个平方

0:04:47.875,0:04:50.061
然后我们还有其他地方

0:04:50.643,0:04:52.045
然后大家可以看一下这边

0:04:52.444,0:04:57.551
这边很宽的一块土 大概有一亩地

0:04:58.176,0:05:00.109
然后我们也准备把它租下来

0:05:00.196,0:05:03.167
因为租金也不贵 一年也就几百块钱吧

0:05:03.312,0:05:04.562
租下来种一点东西

0:05:06.451,0:05:09.153
我们这边就是把它做成一个中餐厅

0:05:09.771,0:05:14.929
就暂时不对外营业 我先自己尝试一下

0:05:14.994,0:05:16.810
就是自己先弄一下

0:05:17.181,0:05:20.839
到时候的话可能也许会在这边拍一些视频也可以

0:05:20.839,0:05:23.328
然后接待一下粉丝也可以

0:05:23.770,0:05:26.303
这边因为这个厨房宽度够宽

0:05:26.760,0:05:28.394
以前我那个工作室嘛

0:05:28.704,0:05:31.693
因为地震了之后有一些风险

0:05:31.693,0:05:34.712
就是它不怎么稳了 然后也比较小

0:05:34.825,0:05:36.438
所以我想换一个大一点的地方

0:05:37.530,0:05:40.663
才能够更好地跟大家呈现一些好的内容

0:05:41.848,0:05:44.687
我们这边外面的话还有个篮球场

0:05:45.308,0:05:48.769
有停车场 篮球场 还有养鱼的地方

0:05:49.080,0:05:53.204
然后这后面的话 四处环绕的都是果园

0:05:53.465,0:05:56.237
有很多水果 这里环境非常好

0:05:56.522,0:05:59.185
然后从这里出去了之后是一个釜溪河

0:05:59.244,0:06:02.662
围绕着这个这个山庄 围绕着这个果场

0:06:02.973,0:06:04.519
这个果场总共是400亩

0:06:04.939,0:06:06.837
然后正好我们在这个中间

0:06:07.081,0:06:10.306
中间的位置非常的好

0:06:11.969,0:06:14.968
之前的话他们是因为这个地方太偏了

0:06:15.338,0:06:19.159
然后又加上这个路也不好走

0:06:19.159,0:06:21.047
开车开进来也要开半个小时

0:06:21.502,0:06:23.459
所以这里是一直放了几年

0:06:23.666,0:06:27.594
现在我这边就把它接过来做一些我喜欢做的事情


```

**Comment by Chuwanggangsiqiu** [comment]
认领

**Comment by Chuwanggangsiqiu** [comment]
带大家看全新工作室的完整面貌，加起来共有800多平方米，期待以后能发挥出它最大的能量
Brought everyone to see the full image of the new studio, the studio is more than 800 square meters, looking forward to seeing it exerts maximum effort in production  
简介
大家好，新工作室已经动工了，正式开始翻新装修，如果一切顺利很快就可以完工，这次带大家看看全貌。因为这个地方原来是用作为农家乐，所以基本的设备都还齐全，整体环境很满意，不过问题还是有不少的，慢慢一个个克服，不过暂时还没有打算对外营业，先专心做好内容，大家敬请期待！
Hello everyone, our new studio has started its renovation, should be finished soon if everything goes well, so this time I’m going to show everyone the whole picture of the studio. Since this place was used as agritourism before, therefore it contains all basic facilities, and I’m happy about the whole surroundings. Although there are still some issues, but we will figure it out one by one. We haven’t planning open to the public, and we will be focused on our content first, please stay tuned!
字幕
0:00:36.500,0:00:38.904
哈喽大家好 最近很开心
Hello everyone, I’m very happy lately
0:00:39.412,0:00:41.691
 租了一个以前旧的山庄
I have rented a very old resort
0:00:41.698,0:00:44.397
这个山庄放了两三年一直没有打理
This resort has been sitting here for 2~3 years without maintenance
0:00:44.865,0:00:48.282
所以我现在把它接(手）过来做些事情
So, I have taken it over to do something
0:00:48.810,0:00:50.924
这里可以看一下环境还很不错
You can see the surroundings are great
0:00:51.398,0:00:54.560
只不过就是荒废了一段时间杂草丛生 
Just have been overgrown and deserted for a while
0:00:54.861,0:00:56.373
到时候我们再修整一下
We will trim it a bit by the time
0:00:56.692,0:01:00.358
正好今天厨房的师傅已经过来放地板砖
Right on today, Shifu have come over and start to tile the floor in the kitchen
0:01:00.391,0:01:01.913
放完地板砖就可以进场
We can walk in there after they have completed the tile work
0:01:02.314,0:01:03.990
好 我带你们看一下这里面
Alright, Let’s have a look inside
0:01:06.132,0:01:08.236
一进来这里是一个桥
There is a bridge right after you walk in
0:01:08.728,0:01:12.255
桥下面有很多金鱼 这里面有很多金鱼
Many golden fish under the bridge, Plenty of golden fish in there
0:01:12.419,0:01:14.833
而且我刚才看到有一条金鱼可能有一两斤
And I just saw one of the golden fish might have two to three jin
0:01:15.389,0:01:16.619
黄色的金鱼很大
The yellow golden fish is very large
0:01:19.544,0:01:23.535
然后进来了之后这里是一个前庭 很宽
And here is the front space, pretty wide
0:01:24.209,0:01:25.430
看起来比较舒服
Looks very comfortable 
0:01:28.091,0:01:29.922
这个大厅层高非常的高啊
This lobby ceiling is very tall
0:01:30.359,0:01:32.528
就是现在大夏天的话都一点都不热
It’s not hot here at all, even during scorcher
0:01:33.075,0:01:36.646
然后这个是玻璃的透光性特别好
And this is made of glass as it has perfect transmittance 
0:01:37.321,0:01:39.817
然后这里原先的老板他设计得很好
The prior landlord had designed this place very well 
0:01:39.863,0:01:41.849
他这边是进风口 一个水冷的
Here is a water-cooling ventilation system
0:01:41.849,0:01:44.063
然后那边后面有抽风机
And we have exhaust fans on the back
0:01:44.419,0:01:46.873
唯一的一个不好的就是这里面的
Only drawback here is that 
0:01:47.005,0:01:49.275
以前的花花草草 现在都变成了大树了
Previous bushes had grown up to trees 
0:01:49.858,0:01:53.193
我们来看一下这是什么树 具体我也不知道
Let’s see what kind of tree this is, I don’t know what exactly it is 
0:01:53.193,0:01:54.405
应该是观赏树吧
Should be an ornamental tree 
0:01:57.011,0:01:58.653
因为这里面层高特别高
Because the ceiling is way too high
0:01:58.678,0:02:00.922
所以它的灯没有说从上面吊下来 
So that the lamp didn’t hang from the top 
0:02:00.922,0:02:02.259
全部是做的这种路灯
All used with this type of streetlight
0:02:02.964,0:02:05.688
这种路灯看起来感觉也不错
The lamp looks great, too
0:02:06.683,0:02:08.616
然后真正吃饭的厅在这里面
And the actual dining hall is right here
0:02:09.277,0:02:11.856
这里面可以摆差不多十几二十张桌子
It can be hold up to around ten to twenty tables 
0:02:12.517,0:02:13.977
还有边上的一些卡座
Then some booths at the side
0:02:14.130,0:02:18.212
总共加起来可能 可以摆上三到四十桌
Add up to a total of thirty to forty tables 
0:02:18.641,0:02:23.007
然后大家看一下这里有条沟
And here is a ditch 
0:02:23.508,0:02:27.039
这条沟是他们设计来养鱼的
This ditch is designed to keep fish
0:02:27.061,0:02:29.059
到时候这里我也把它水放起来
I will fill up the water by that time 
0:02:29.429,0:02:33.992
放起来养一些我们餐厅到时候能够做菜的鱼
Put some fish that can be used for cooking 
0:02:33.992,0:02:35.953
全部就养在这个里面 再养一些金鱼
All of them will be kept in here, plus some golden fish
0:02:38.300,0:02:39.288
然后看一下这边
And look at that side 
0:02:39.309,0:02:43.516
这个有2468 有8个抽风机
2,4,6,8 there are total of eight exhaust fans 
0:02:44.104,0:02:45.673
大家看一下这些桌子
You can see these tables
0:02:46.400,0:02:47.766
其实都是挺好的
are still good to use 
0:02:48.245,0:02:54.072
我们做餐厅的这些东西虽然说你看着这是旧的很旧
Although these dinning tables are looks very old
0:02:54.108,0:02:55.510
如果你去买的话 特别贵
But still will be very expensive when you purchase it outside 
0:02:55.924,0:02:59.404
比如这几张桌子凳子这里要花很多钱
For example, these tables and chairs will be costing a lot of money
0:03:00.886,0:03:01.939
这里有个亭子
Here is a pavilion
0:03:03.312,0:03:05.325
这个亭子应该是用来做观赏的
This pavilion should be used for ornamentation
0:03:07.540,0:03:12.212
然后这条沟从那边一直到这边有很长一截
And this ditch has long connected from the other side
0:03:14.021,0:03:16.462
这个厅大概有500个平方
This lobby is about 500 square meters
0:03:16.789,0:03:19.615
有500个平方 层高应该有六七米
Building height is about six to seven meters 
0:03:20.421,0:03:23.501
就是进来了之后不会感觉压抑
You won’t feel oppressive after you walked in
0:03:23.857,0:03:25.085
现在我带大家看一下厨房
Next, we are going to see the kitchen 
0:03:27.184,0:03:28.383
看一下我们这里面
Have a look inside 
0:03:29.059,0:03:31.689
师父现在涂这个墙已经涂到这边来了
Shifu has already painted over to this side 
0:03:32.546,0:03:35.343
然后那边的师傅在负责放砖
The Shifu over that side is responsible for floor paving
0:03:35.445,0:03:38.641
这里大概全部弄下来要两三天吧
It takes about two to three days to finish the pavement   
0:03:39.041,0:03:42.738
要两三天 地砖放好了之后还要让它干两三天
Must let it dry for two more days after paved the floor
0:03:43.450,0:03:45.174
然后我们这些设备才可以运进来
Then our equipments can be moved in
0:03:45.426,0:03:46.509
这里还有一套厨具
Here is a set of cook stove
0:03:47.039,0:03:50.061
这套厨具也是以前剩下的
It has been left by the last owner
0:03:50.374,0:03:53.745
看起来是很旧 但是这个不是很旧
Looks very old, but it’s not that old
0:03:54.471,0:03:57.406
看起来旧而已 只是长时间不用有的生锈了
Just looks old, have a bit rusted after it has been sitting there for a while
0:03:57.620,0:04:01.245
到时候我们烧一点烧碱把那些锈就可以把它除掉
We will use caustic soda to clean it off 
0:04:01.416,0:04:04.417
然后也可以用 我已经试过了这个灶是没有问题的
Then it will be able to use, this stove is still functioning well the last time that I tried it
0:04:05.114,0:04:06.657
我带大家去看一下二楼
Now, let’s have a look at the second floor
0:04:06.657,0:04:09.378
这个厨房的话面积有差不多100个平方米
This kitchen area is about 100 square meters 
0:04:09.778,0:04:10.795
然后去看一下二楼
We are going to see the second floor 
0:04:12.822,0:04:17.624
这些东西都是上一任老板留下来的锅碗瓢盆
These pots and pans are left by the last owner
0:04:19.433,0:04:20.319
这边是厕所
Here is the washroom
0:04:25.223,0:04:26.531
然后我们上二楼看一下
And we are walking up to the second floor
0:04:29.509,0:04:31.551
这个二楼非常的大
The second floor is very wide
0:04:32.037,0:04:33.294
就是下面是厨房
And the kitchen is below
0:04:33.352,0:04:36.040
这里是二楼 有个棚
The second floor have a roof 
0:04:36.556,0:04:39.825
这上面应该用不上 地方太大了
This place is too large, I don’t think we are going to use it
0:04:40.697,0:04:43.182
总共加起来这里有厨房
Plus the kitchen below 
0:04:43.182,0:04:47.286
加这个二楼加厅总共差不多有800个平方
And the second floor, tot up to approximately 800 square meters 
0:04:47.875,0:04:50.061
然后我们还有其他地方
And we have other places too
0:04:50.643,0:04:52.045
然后大家可以看一下这边
Everyone can have a look at this side
0:04:52.444,0:04:57.551
这边很宽的一块土 大概有一亩地
There is a piece of wide land, area is about one mu
0:04:58.176,0:05:00.109
然后我们也准备把它租下来
And we going to lease it as well
0:05:00.196,0:05:03.167
因为租金也不贵 一年也就几百块钱吧
Doesn’t cost much, a few hundred RMB per year
0:05:03.312,0:05:04.562
租下来种一点东西
Rent it for planting 
0:05:06.451,0:05:09.153
我们这边就是把它做成一个中餐厅
We are going to make this place into a Chinese restaurant
0:05:09.771,0:05:14.929
就暂时不对外营业 我先自己尝试一下
It’s not opening to public for now, I will try it first
0:05:14.994,0:05:16.810
就是自己先弄一下
Just used for other things first 
0:05:17.181,0:05:20.839
到时候的话可能也许会在这边拍一些视频也可以
Maybe we can shoot some films in here 
0:05:20.839,0:05:23.328
然后接待一下粉丝也可以
or can be used to host our fans 
0:05:23.770,0:05:26.303
这边因为这个厨房宽度够宽
Because this kitchen has enough space 
0:05:26.760,0:05:28.394
以前我那个工作室嘛
The studio that I used have 
0:05:28.704,0:05:31.693
因为地震了之后有一些风险
Have been at risk after the earthquake 
0:05:31.693,0:05:34.712
就是它不怎么稳了 然后也比较小
It’s not that stabilized, and relatively small too
0:05:34.825,0:05:36.438
所以我想换一个大一点的地方
So, I want to switch to a bigger place
0:05:37.530,0:05:40.663
才能够更好地跟大家呈现一些好的内容
We can present some better contents in this way 
0:05:41.848,0:05:44.687
我们这边外面的话还有个篮球场
And We have a basketball court right out there
0:05:45.308,0:05:48.769
有停车场 篮球场 还有养鱼的地方
There are parking lot, basketball court, and a fishpond, too
0:05:49.080,0:05:53.204
然后这后面的话 四处环绕的都是果园
And in the back, are surrounded by orchards
0:05:53.465,0:05:56.237
有很多水果 这里环境非常好
Got plenty of fruits, and environment here is pretty well 
0:05:56.522,0:05:59.185
然后从这里出去了之后是一个釜溪河
And there is a Fuxi river after you walk out here
0:05:59.244,0:06:02.662
围绕着这个这个山庄 围绕着这个果场
The resort and this orchard are surrounded by the river
0:06:02.973,0:06:04.519
这个果场总共是400亩
The area of the orchard is a total of 400 mu
0:06:04.939,0:06:06.837
然后正好我们在这个中间
And we are right at the center part
0:06:07.081,0:06:10.306
中间的位置非常的好
The central location is excellent
0:06:11.969,0:06:14.968
之前的话他们是因为这个地方太偏了
Because this place is too remote, 
0:06:15.338,0:06:19.159
然后又加上这个路也不好走
And plus, it’s very hard to get through this road
0:06:19.159,0:06:21.047
开车开进来也要开半个小时
It takes half hour to get in here
0:06:21.502,0:06:23.459
所以这里是一直放了几年
That’s why this place has been sitting here for a few years already
0:06:23.666,0:06:27.594
现在我这边就把它接过来做一些我喜欢做的事情
Now, I ‘m going to take it over and do something I like
