### ISSUE TITLE
[老饭骨] 担担面 - https://youtu.be/p14_3HovbyI

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1173]
**视频链接**：https://youtu.be/p14_3HovbyI

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【國宴大師•擔擔麵】四川名小吃擔擔麵老配方，二伯再現近乎失傳技藝，做法簡單，味道巴適得板！| 在家炒菜如何控制火候 |老飯骨

简介
小友們好，今天二伯帶着擔擔麵的老配方來了！擔擔麵是四川地區著名的麵食小吃，二伯做的呢是當初他在力力餐廳實習時，著名面點老師傅都國良的版本。這做法簡單，味道卻不一般，其中紅油可謂是擔擔麵的靈魂，大傢伙兒可要看仔細嘍！
本期視頻末尾還有大爺二伯為小友們答疑解惑：在家炒菜如何控制火候，一定不要錯過哦！

字幕
1
00:00:00,000 --> 00:00:02,480
我的天这担担面有食欲啊

2
00:00:02,480 --> 00:00:03,280

3
00:00:03,280 --> 00:00:05,400
还真挺地道的

4
00:00:05,400 --> 00:00:07,400
这个担担面 我可以这么说

5
00:00:07,400 --> 00:00:09,600
比他们做的简单多了

6
00:00:09,600 --> 00:00:10,680
但是比那还要好

7
00:00:10,680 --> 00:00:12,520
担担面

8
00:00:12,520 --> 00:00:14,440

9
00:00:14,440 --> 00:00:17,160
一定要买正宗的四川宜宾芽菜

10
00:00:17,160 --> 00:00:20,320
把这咸味洗洗 老的传统做法

11
00:00:20,320 --> 00:00:21,840
洗干净就行了

12
00:00:21,840 --> 00:00:24,680
但是这味儿又不能完全洗掉了

13
00:00:24,680 --> 00:00:26,480
把水挤净了

14
00:00:26,480 --> 00:00:27,920

15
00:00:27,920 --> 00:00:30,280
为了让它更香点 制点葱油

16
00:00:30,280 --> 00:00:33,120
好的花生油 差不多够了吧

17
00:00:33,120 --> 00:00:36,840
你看大料 小茴香 桂皮 砂仁 豆蔻

18
00:00:36,840 --> 00:00:38,720
洗一下它不容易糊

19
00:00:38,720 --> 00:00:42,640
把它洗干净了 慢慢沁炸 油不要太热

20
00:00:42,640 --> 00:00:45,720
顺便搁点葱 有香味

21
00:00:45,720 --> 00:00:49,240
要切点姜 拍一下

22
00:00:49,240 --> 00:00:51,520
还得来点这个 葱绿

23
00:00:51,520 --> 00:00:54,760
这就慢慢的沁炸 没什么可复杂的

24
00:00:54,760 --> 00:00:56,880
辣椒面我们可以搁点香油

25
00:00:56,880 --> 00:00:58,840
它出来更有香味

26
00:00:58,840 --> 00:01:02,000
咱们拌一拌 不容易一下就糊了

27
00:01:02,000 --> 00:01:03,840

28
00:01:03,840 --> 00:01:05,680
以前都是拌水啊师父

29
00:01:05,680 --> 00:01:09,920
对拌水也可以  今天又学一招

30
00:01:09,920 --> 00:01:12,520
过去讲二合油炒菜香啊

31
00:01:12,520 --> 00:01:15,440
搁点猪油 你闻这气味

32
00:01:15,440 --> 00:01:17,880
这个担担面 你看简单

33
00:01:17,880 --> 00:01:19,040
它跟别人做法不一样

34
00:01:19,040 --> 00:01:21,120
这是力力餐厅的一道名菜

35
00:01:21,120 --> 00:01:23,800
我们上学的时候都在那实习

36
00:01:23,800 --> 00:01:26,240
然后当时那师傅很厉害

37
00:01:26,240 --> 00:01:28,120
有一个面点师傅叫都国良

38
00:01:28,120 --> 00:01:31,080
那在四川是非常有名望的

39
00:01:31,080 --> 00:01:33,200
这是传承他的担担面

40
00:01:33,200 --> 00:01:35,080
非常简单 而且你看还好吃

41
00:01:35,080 --> 00:01:36,560
咱给它捞出来

42
00:01:36,560 --> 00:01:38,600
这就行了 温度行了

43
00:01:38,600 --> 00:01:42,360
一下（下多了）就糊了 这可以慢慢加

44
00:01:42,360 --> 00:01:47,280
这样油热点 它糊不了

45
00:01:47,280 --> 00:01:50,240
一次次加热

46
00:01:50,240 --> 00:01:51,680
你看我为什么这么试呢

47
00:01:51,680 --> 00:01:53,840
就让网友学这个他有把握

48
00:01:53,840 --> 00:01:56,680
油耗完了 现在调汁 我煮面

49
00:01:56,680 --> 00:01:57,720
这个东西很简单

50
00:01:57,720 --> 00:02:00,080
小葱花 不能切成葱末

51
00:02:00,080 --> 00:02:04,000
这个芽菜可以搁点 让它香

52
00:02:04,000 --> 00:02:08,400
味精其实对人体没有害 沏出来没问题

53
00:02:08,400 --> 00:02:10,680
因为这个温度不够 它到不了八十五度

54
00:02:10,680 --> 00:02:12,920
可以搁点猪油 提提香

55
00:02:12,920 --> 00:02:14,600
要没有也没关系

56
00:02:14,600 --> 00:02:17,360
这一碗酱油

57
00:02:17,360 --> 00:02:21,160
然后还有一样重要的东西 这个师父

58
00:02:21,160 --> 00:02:24,360
灵魂 灵魂就是红油

59
00:02:24,360 --> 00:02:27,960
安逸 巴适得很

60
00:02:27,960 --> 00:02:30,000
说话有水平啊

61
00:02:30,000 --> 00:02:32,640
要的 煮面喽

62
00:02:32,640 --> 00:02:35,760
这个就是普通的切面 细切面

63
00:02:35,760 --> 00:02:38,360
过去是用好鸡汤

64
00:02:38,360 --> 00:02:40,040
我们今天不用鸡汤

65
00:02:40,040 --> 00:02:43,760
我们就用这原汤 也一样

66
00:02:43,760 --> 00:02:44,880
也还原这味道

67
00:02:44,880 --> 00:02:48,040
简单当中它不是我的味道不好

68
00:02:48,040 --> 00:02:49,280
如果说你要炒了

69
00:02:49,280 --> 00:02:52,840
这芽菜的味道就会失去了很多

70
00:02:52,840 --> 00:02:54,800
炒完了这个味道马上就变了

71
00:02:54,800 --> 00:02:55,920
就不好吃了

72
00:02:55,920 --> 00:02:57,800
这个担担面 我可以这么说

73
00:02:57,800 --> 00:03:00,480
比他们做的简单多了

74
00:03:00,480 --> 00:03:01,960
但是比那还要好吃

75
00:03:01,960 --> 00:03:05,800
这个技艺几乎没了 我今天还原给你们

76
00:03:05,800 --> 00:03:08,160
熟了 再烫个油菜心

77
00:03:08,160 --> 00:03:11,000

78
00:03:11,000 --> 00:03:12,080
还有一个什么呢

79
00:03:12,080 --> 00:03:14,080
冲一下汤 为什么得先冲汤

80
00:03:14,080 --> 00:03:15,400
必须开锅冲这汤

81
00:03:15,400 --> 00:03:17,760
如果你要后加 把面条搁上再冲汤

82
00:03:17,760 --> 00:03:19,320
这香气就出不来

83
00:03:19,320 --> 00:03:21,600
你看它这东西就这么怪

84
00:03:21,600 --> 00:03:25,720

85
00:03:25,720 --> 00:03:26,680
太有食欲了

86
00:03:26,680 --> 00:03:29,080
我的天呐这担担面有食欲啊

87
00:03:29,080 --> 00:03:34,040
既简单又好吃 家里又能操作的

88
00:03:34,040 --> 00:03:36,000
来点汤

89
00:03:36,000 --> 00:03:37,360

90
00:03:37,360 --> 00:03:40,600
这怎么样 够不够小魏 咸味

91
00:03:40,600 --> 00:03:43,000
芽菜的香味儿 辣味

92
00:03:43,000 --> 00:03:46,000
包括红油跟面的这种碰撞

93
00:03:46,000 --> 00:03:47,680

94
00:03:47,680 --> 00:03:51,560
这一站就到四川啦 巴适得很

95
00:03:51,560 --> 00:03:53,560
你吃一口尝尝

96
00:03:53,560 --> 00:03:56,600
你干了二十年老面点师了

97
00:03:57,600 --> 00:03:59,600
师父也不是干面点的

98
00:03:59,600 --> 00:04:01,440
再喝口汤

99
00:04:01,440 --> 00:04:05,080

100
00:04:05,080 --> 00:04:09,680
这真挺地道的 真挺好吃的

101
00:04:09,680 --> 00:04:12,320
它吃完了没有麻酱糊嘴的味儿

102
00:04:12,320 --> 00:04:14,360
这个汤就得烫点 越烫越好

103
00:04:14,360 --> 00:04:17,480
再来点 多吃点儿

104
00:04:17,480 --> 00:04:18,440

105
00:00:00,120 --> 00:00:01,040

**Comment by Yingzhang1122** [comment]
#标题（翻译主要意思即可，不要超过 100 个字符）
#【國宴大師•擔擔麵】四川名小吃擔擔麵老配方，二伯再現近乎失傳技藝，做法簡單，味道巴適得板！| 在家炒菜如何控制火候 |老飯骨
# Traditional recipe of a famous Sichuan snack: Dan Dan Noodles! Er Bai presents the cooking skills that are nearly lost. Simple but extremely delicious! 

#简介
#小友們好，今天二伯帶着擔擔麵的老配方來了！擔擔麵是四川地區著名的麵食小吃，二伯做的呢是當初他在力力餐廳實習時，著名面點老師傅都國良的版本。這做法簡單，味道卻不一般，其中紅油可謂是擔擔麵的靈魂，大傢伙兒可要看仔細嘍！
#本期視頻末尾還有大爺二伯為小友們答疑解惑：在家炒菜如何控制火候，一定不要錯過哦！
# Hi everyone! Today Er Bai comes with the traditional recipe of Dan Dan Noodles, a famous snack in Sichuan. He learned this recipe from a famous Chinese pastry chef, Master Du Guoliang, during his internship at Li Li Restaurant. The recipe is simple, but produces an amazing flavor. In particular, the red chili oil is the soul of this dish. Please take a good look!
# At the end of this video, Da Ye and Er Bai will also introduce you how to control the temperature when cooking at home. Be sure not to miss it!

#字幕
1
00:00:00,000 --> 00:00:02,480
#我的天这担担面有食欲啊
My god. This dish is so appetizing

2
00:00:02,480 --> 00:00:03,280

3
00:00:03,280 --> 00:00:05,400
#还真挺地道的
It's indeed authentic

4
00:00:05,400 --> 00:00:07,400
#这个担担面 我可以这么说
The Dan Dan Noodles here... I would rather say

5
00:00:07,400 --> 00:00:09,600
#比他们做的简单多了
... is much simpler than how they cook it

6
00:00:09,600 --> 00:00:10,680
#但是比那还要好
But is even better

7
00:00:10,680 --> 00:00:12,520
#担担面
Dan Dan Noodles

8
00:00:12,520 --> 00:00:14,440

9
00:00:14,440 --> 00:00:17,160
#一定要买正宗的四川宜宾芽菜
You must buy authentic 'Ya Cai' (Sichuan preserved mustard greens) from Yibin, Sichuan

10
00:00:17,160 --> 00:00:20,320
#把这咸味洗洗 老的传统做法
Wash away the salty taste. This is the traditional way

11
00:00:20,320 --> 00:00:21,840
#洗干净就行了
Wash it clean would be fine

12
00:00:21,840 --> 00:00:24,680
#但是这味儿又不能完全洗掉了
You shouldn't remove the taste entirely

13
00:00:24,680 --> 00:00:26,480
#把水挤净了
Squeeze out the water

14
00:00:26,480 --> 00:00:27,920

15
00:00:27,920 --> 00:00:30,280
#为了让它更香点 制点葱油
To make it more aromatic, prepare some scallion oil

16
00:00:30,280 --> 00:00:33,120
#好的花生油 差不多够了吧
High-quality peanut oil. Almost enough

17
00:00:33,120 --> 00:00:36,840
#你看大料 小茴香 桂皮 砂仁 豆蔻
See? Star anise, fennel seeds, cinnamon, amomum, and cardamom

18
00:00:36,840 --> 00:00:38,720
#洗一下它不容易糊
Wash them so they don't get burnt easily

19
00:00:38,720 --> 00:00:42,640
#把它洗干净了 慢慢沁炸 油不要太热
Wash it clean. Soak-fry it slowly. The oil shouldn't be too hot

20
00:00:42,640 --> 00:00:45,720
#顺便搁点葱 有香味
Add some scallion as well. It's aromatic

21
00:00:45,720 --> 00:00:49,240
#要切点姜 拍一下
Cut some ginger. Smash it

22
00:00:49,240 --> 00:00:51,520
#还得来点这个 葱绿
We also need some of this. Scallion leaves

23
00:00:51,520 --> 00:00:54,760
#这就慢慢的沁炸 没什么可复杂的
Simply soak-fry it. Nothing complicated

24
00:00:54,760 --> 00:00:56,880
#辣椒面我们可以搁点香油
Add some seasome oil in the chili pepper powder

25
00:00:56,880 --> 00:00:58,840
#它出来更有香味
so that it smells more aromatic

26
00:00:58,840 --> 00:01:02,000
#咱们拌一拌 不容易一下就糊了
Mix it up so that it doesn't get burnt immediately

27
00:01:02,000 --> 00:01:03,840

28
00:01:03,840 --> 00:01:05,680
#以前都是拌水啊师父
We used to mix it with water, master

29
00:01:05,680 --> 00:01:09,920
#对拌水也可以  今天又学一招
- Yeah, mixing with water is also ok. - That's another new trick today

30
00:01:09,920 --> 00:01:12,520
#过去讲二合油炒菜香啊
We used to say that the mixed oil gives great aroma for a dish

31
00:01:12,520 --> 00:01:15,440
#搁点猪油 你闻这气味
Add some pork lard. Smell it

32
00:01:15,440 --> 00:01:17,880
#这个担担面 你看简单
This recipe of Dan Dan Noodles... You see, it's simple

33
00:01:17,880 --> 00:01:19,040
#它跟别人做法不一样
But different from how other people cooks it

34
00:01:19,040 --> 00:01:21,120
#这是力力餐厅的一道名菜
It's a famous dish of Li Li Restaurant

35
00:01:21,120 --> 00:01:23,800
#我们上学的时候都在那实习
When we were studying cooking, we did our internship there

36
00:01:23,800 --> 00:01:26,240
#然后当时那师傅很厉害
At that time, the master chef was awesome

37
00:01:26,240 --> 00:01:28,120
#有一个面点师傅叫都国良
There was a pastry chef named Du Guoliang

38
00:01:28,120 --> 00:01:31,080
#那在四川是非常有名望的
He was very famous and prestigious in Sichuan

39
00:01:31,080 --> 00:01:33,200
#这是传承他的担担面
This recipe is inherited from him

40
00:01:33,200 --> 00:01:35,080
#非常简单 而且你看还好吃
Very simple. And delicious

41
00:01:35,080 --> 00:01:36,560
#咱给它捞出来
Let's haul it out

42
00:01:36,560 --> 00:01:38,600
#这就行了 温度行了
This is ok. At the right temperature

43
00:01:38,600 --> 00:01:42,360
#一下（下多了）就糊了 这可以慢慢加
Add the oil one-off, it'll be burnt. We can do it slowly

44
00:01:42,360 --> 00:01:47,280
#这样油热点 它糊不了
So that it doesn't get burnt even if the oil is too hot

45
00:01:47,280 --> 00:01:50,240
#一次次加热
Heat it several times

46
00:01:50,240 --> 00:01:51,680
#你看我为什么这么试呢
Why am I doing this?

47
00:01:51,680 --> 00:01:53,840
#就让网友学这个他有把握
Because I want our audiences to learn the details well

48
00:01:53,840 --> 00:01:56,680
#油耗完了 现在调汁 我煮面
I've used up the oil. Now prepare the sauce and boil some noodles

49
00:01:56,680 --> 00:01:57,720
#这个东西很简单
This is really simple

50
00:01:57,720 --> 00:02:00,080
#小葱花 不能切成葱末
Cut the scallion in this way. Don't mince it

51
00:02:00,080 --> 00:02:04,000
#这个芽菜可以搁点 让它香
Add some 'Ya Cai' (Sichuan preserved mustard green) to make it aromatic

52
00:02:04,000 --> 00:02:08,400
#味精其实对人体没有害 沏出来没问题
MSG is acutally not harmful to our health, at least in this way

53
00:02:08,400 --> 00:02:10,680
#因为这个温度不够 它到不了八十五度
Since the temperature is not high enough. It hasn't reached 85 degrees Celcius

54
00:02:10,680 --> 00:02:12,920
#可以搁点猪油 提提香
We can add some lard to enhance the aroma

55
00:02:12,920 --> 00:02:14,600
#要没有也没关系
It's ok if you don't have it

56
00:02:14,600 --> 00:02:17,360
#这一碗酱油
And the soy sauce here

57
00:02:17,360 --> 00:02:21,160
#然后还有一样重要的东西 这个师父
One other important thing. This one, master

58
00:02:21,160 --> 00:02:24,360
#灵魂 灵魂就是红油
The soul. The red chili oil is the soul

59
00:02:24,360 --> 00:02:27,960
#安逸 巴适得很
Nice. This is really amazing

60
00:02:27,960 --> 00:02:30,000
#说话有水平啊
That's the right way to say it

61
00:02:30,000 --> 00:02:32,640
#要的 煮面喽
Okay! Boil the noodles

62
00:02:32,640 --> 00:02:35,760
#这个就是普通的切面 细切面
These are just normal noodles. Thin cut noodles

63
00:02:35,760 --> 00:02:38,360
#过去是用好鸡汤
In the past we used decent chicken broth

64
00:02:38,360 --> 00:02:40,040
#我们今天不用鸡汤
Today we don't use chicken broth

65
00:02:40,040 --> 00:02:43,760
#我们就用这原汤 也一样
Use the noodle water here. It's equivalent

66
00:02:43,760 --> 00:02:44,880
#也还原这味道
It can also reproduce the best taste

67
00:02:44,880 --> 00:02:48,040
#简单当中它不是我的味道不好
In short, it's not that it tastes bad

68
00:02:48,040 --> 00:02:49,280
#如果说你要炒了
Instead, if you stir-fry it

69
00:02:49,280 --> 00:02:52,840
#这芽菜的味道就会失去了很多
Most of the flavor in 'Ya Cai' will be gone

70
00:02:52,840 --> 00:02:54,800
#炒完了这个味道马上就变了
It tastes different immediately after frying

71
00:02:54,800 --> 00:02:55,920
#就不好吃了
and it goes bad

72
00:02:55,920 --> 00:02:57,800
#这个担担面 我可以这么说
This recipe of Dan Dan Noodles, I would say

73
00:02:57,800 --> 00:03:00,480
#比他们做的简单多了
is much simpler than how other people cook it

74
00:03:00,480 --> 00:03:01,960
#但是比那还要好吃
But tastes even better

75
00:03:01,960 --> 00:03:05,800
#这个技艺几乎没了 我今天还原给你们
This recipe is almost lost. I reproduce it for you here now 

76
00:03:05,800 --> 00:03:08,160
#熟了 再烫个油菜心
It's done. Boil some choy sum

77
00:03:08,160 --> 00:03:11,000

78
00:03:11,000 --> 00:03:12,080
#还有一个什么呢
What else?

79
00:03:12,080 --> 00:03:14,080
#冲一下汤 为什么得先冲汤
Add the hot noodle water into the bowl. Why do this first?

80
00:03:14,080 --> 00:03:15,400
#必须开锅冲这汤
We must use the hot noodle water to make the 'soup'

81
00:03:15,400 --> 00:03:17,760
#如果你要后加 把面条搁上再冲汤
If you are doing it later, say put the noodles on the sauce and add water later

82
00:03:17,760 --> 00:03:19,320
#这香气就出不来
The aroma is not going out

83
00:03:19,320 --> 00:03:21,600
#你看它这东西就这么怪
It is indeed interesting

84
00:03:21,600 --> 00:03:25,720

85
00:03:25,720 --> 00:03:26,680
#太有食欲了
So appetizing

86
00:03:26,680 --> 00:03:29,080
#我的天呐这担担面有食欲啊
My god. The Dan Dan Noodles are so appetizing

87
00:03:29,080 --> 00:03:34,040
#既简单又好吃 家里又能操作的
Simple and delicious. You can easily do this at home

88
00:03:34,040 --> 00:03:36,000
#来点汤
Add some soup

89
00:03:36,000 --> 00:03:37,360

90
00:03:37,360 --> 00:03:40,600
#这怎么样 够不够小魏 咸味
What do you think? Is it salty enough, Wei?

91
00:03:40,600 --> 00:03:43,000
#芽菜的香味儿 辣味
The aroma of 'Ya Cai', the spicy flavor

92
00:03:43,000 --> 00:03:46,000
#包括红油跟面的这种碰撞
And the collision between the red chili oil and noodles

93
00:03:46,000 --> 00:03:47,680

94
00:03:47,680 --> 00:03:51,560
#这一站就到四川啦 巴适得很
I feel I'm already in Sichuan. Tastes amazing

95
00:03:51,560 --> 00:03:53,560
#你吃一口尝尝
Take a bite

96
00:03:53,560 --> 00:03:56,600
#你干了二十年老面点师了
You've been a pastry chef for 20 years

97
00:03:57,600 --> 00:03:59,600
#师父也不是干面点的
I am not a pastry chef myself

98
00:03:59,600 --> 00:04:01,440
#再喝口汤
Try the soup?

99
00:04:01,440 --> 00:04:05,080

100
00:04:05,080 --> 00:04:09,680
#这真挺地道的 真挺好吃的
This is so authentic. Delicious indeed

101
00:04:09,680 --> 00:04:12,320
#它吃完了没有麻酱糊嘴的味儿
You don't have the 'sticky' feeling of seasame sauce after eating

102
00:04:12,320 --> 00:04:14,360
#这个汤就得烫点 越烫越好
The soup should be hot. The hotter, the better

103
00:04:14,360 --> 00:04:17,480
#再来点 多吃点儿
Have some more!

104
00:04:17,480 --> 00:04:18,440

105
00:00:00,120 --> 00:00:01,040

#以下字幕暂时没有时间轴，请直接审核文字
#有网友问 说家里的火没有饭店里那么旺
Some fans say that the cooking stoves in their homes are not as powerful as those in restaurants
#所以在家炒菜的时候怎么能够控制火候
and they wonder how to control the temperature when cooking at home
#有什么技巧
and if there are some tricks
#在家里边 火比较弱
Generally the heaters in home are not powerful enough
#尽量让它温度稍微高一点
So you should try to use a slightly higher temperature
#然后这量呢
and the amount of food...
#你如果说在家里边炒菜量要太大
If you are cooking a lot of food for one dish in your home
#也不行
that's not gonna work
#根本不行
not at all
#这量适当的合适
The amount of food should be moderate
#你要说够一盘吃的
Say, if the amount is about one plate
#那基本就没问题
Basically it'll be fine
#所以在炒的这过程当中
During the cooking process
#一是我们把油温升高 把锅温升高
Firstly, enhance the temperatures of the oil and the wok
#炒菜当中要采取其它一些措施
Some other measures should be taken while cooking
#如果说要炒菜 还有一个方法
If you are stir-frying, there is another trick
#要把它分类炒开了
Stir-fry each ingredient separately
#能用碗汁的 我们兑个碗汁
For example, if 'bowl-sauce' (prepare all condiments in one bowl in advance) is applicable, you can make one
#比如说荤料的东西我们先滑了
Slightly fry the meat before cooking
#滑好以后捞出来
Fish the meat out of the oil
#刷完锅我们再升温炒一些配料
Rinse the wok, raise the temperature and stir-fry some other ingredients
#这样把它分段给解开了
In this way, the dish is separated into several 'sections'
#分解开了再一块投进去
Finally, mix every ingredient together in the wok
#你这样下碗汁之后先别急着扒拉
Add the 'bowl-sauce', but don't stir the food immediately
#让它凝固一下
Let it condense for a while
#你这样再翻
And then you can toss the wok
#相对来讲就解决了这个问题
Such that this problem can be fixed
#火的问题就解决了
the temperature loss problem due to low power heater
#明白了吧
You get it?

**Comment by immoonancient** [comment]
被人抢先做了...
