### ISSUE TITLE
【美食作家王刚】茄子拌土豆 - https://youtu.be/IUJB6JqwczY

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1174]
**视频链接**：https://youtu.be/IUJB6JqwczY

视频时长2:02，预计发布时间为北京时间6月18日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“茄子拌土豆”的家常做法，味道很赞特别下饭，学习起来

简介
大家好，今天和大家分享一道简单下饭的拌菜“茄子拌土豆”，听说在东北流传着一句“茄子拌土豆，吃撑老爷子”，可见这道菜受欢迎的程度，不过今天这个做法用了香辣红油更偏四川风味。如果想吃正宗的东北风味，需要在蒸茄子和土豆的同时再蒸上一小碗“东北大酱”，在酱中拌上一些辣青椒，这样就能得到一碗东北青椒熟酱，取一部分代替香辣红油拌入就是正宗东北风味了。

本期菜品【茄子拌土豆】【东北乱拌茄子土豆】
【主料】
土豆（1个）
茄子（1条）
【辅料】
大蒜（几颗）
小葱头（几根）
【调味料】
香辣红油（适量）
白醋（适量）
蚝油（4克）
生抽酱油（5克）
白糖（少许）

字幕
0:00:00.300,0:00:01.420
哈喽大家好 我是王刚

0:00:01.420,0:00:03.360
本期视频我给大家分享一道家常菜

0:00:03.800,0:00:05.080
土豆拌茄子

0:00:05.420,0:00:08.140
处理食材之前首先我们准备1盆清水

0:00:09.225,0:00:11.600
然后在清水中加入适量的白醋

0:00:12.300,0:00:14.125
准备好之后放一边备用

0:00:14.375,0:00:16.900
准备土豆1个去皮之后切成小颗粒备用

0:00:17.225,0:00:19.950
嫌麻烦的同学也可以切成4毫米左右的片

0:00:20.198,0:00:22.286
这一步的目的是让土豆更容易成熟

0:00:25.177,0:00:27.223
切好之后放入白醋水中浸泡备用

0:00:27.588,0:00:30.187
准备茄子1条对半切开之后切成小块备用

0:00:30.501,0:00:33.121
同学们茄子大约切成土豆的3倍大小即可

0:00:35.469,0:00:36.972
然后放入盆中浸泡备用

0:00:37.411,0:00:40.208
加醋浸泡土豆和茄子可以防止其氧化变黑

0:00:40.354,0:00:42.453
但是同学们切记土豆不能泡太久（60分钟以上）

0:00:42.734,0:00:44.676
否则土豆将会变软口感不好

0:00:46.106,0:00:49.425
然后我们将土豆茄子和醋水直接上锅蒸25分钟左右

0:00:49.770,0:00:52.202
这样能够最大限度的保证茄子的紫色

0:00:52.526,0:00:53.945
下一步开始准备料汁

0:00:54.613,0:00:56.576
准备大蒜几颗拍散之后剁碎备用

0:01:01.054,0:01:02.620
准备小葱头几根切碎备用

0:01:04.895,0:01:06.273
碗中加入蚝油4克

0:01:07.223,0:01:08.810
加入生抽酱油12克

0:01:10.135,0:01:11.200
加入少许白糖（约1克）

0:01:12.317,0:01:14.895
搅拌均匀之后加入适量的香辣红油拌匀即可

0:01:15.146,0:01:16.847
不能吃辣的同学也可以不加

0:01:22.682,0:01:26.064
25分钟之后将蒸熟软的茄子和土豆捞出沥干水分

0:01:29.519,0:01:31.357
待稍微凉一会之后倒入盘中

0:01:32.912,0:01:34.937
最后将调好的料汁淋在上面即可

0:01:36.520,0:01:39.380
一道非常开胃下饭的土豆拌茄子就制作完成

0:01:44.840,0:02:01.520
下面开始技术总结
第一，土豆不能切太大否则不能熟透，茄子应切大块些这样才能久蒸
第二，原料泡在水里面蒸可以有效防止营养流失
第三，此菜必须将水份沥干再淋料汁，否则口味容易冲淡
土豆拌茄子的技术总结完毕


```

**Comment by Yibing-Du** [comment]
bot, please upload
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“茄子拌土豆”的家常做法，味道很赞特别下饭，学习起来
Chef Wang Teaches You: "Eggplant and Potato Cold Dish," Delicious and Great with Rice, Let's Learn It

简介
Introduction
大家好，今天和大家分享一道简单下饭的拌菜“茄子拌土豆”，听说在东北流传着一句“茄子拌土豆，吃撑老爷子”，可见这道菜受欢迎的程度，不过今天这个做法用了香辣红油更偏四川风味。如果想吃正宗的东北风味，需要在蒸茄子和土豆的同时再蒸上一小碗“东北大酱”，在酱中拌上一些辣青椒，这样就能得到一碗东北青椒熟酱，取一部分代替香辣红油拌入就是正宗东北风味了。
Hi everyone, today I'd like to share a simple "Eggplant and Potato Cold Dish" that is great with rice. I heard in northeastern China, there's an old saying: "Eggplant with potato, old men are full and satisfied." This is how popular this dish is, though today we'll make a Sichuan-style version with tasty red chili oil. If you want to try it in the northeastern-Chinese-style, you need to steam not just eggplants and potatos but also a small bowl of "Northeastern-style bean paste" and mix it with some spicy green chili pepper. This Northeastern-style green pepper sauce can replace some red chili oil in our cold dish. 

本期菜品【茄子拌土豆】【东北乱拌茄子土豆】
Dish: Eggplant and Potato Cold Dish, or Northeastern-style Casual Mix of Eggplant and Potato
【主料】
Main Ingredients
土豆（1个）
Potato (1)
茄子（1条）
Eggplant (1)
【辅料】
Other Ingredients
大蒜（几颗）
Garlic (a few)
小葱头（几根）
Green onions (a few)
【调味料】
Sauce
香辣红油（适量）
Red chili oil (some)
白醋（适量）
Rice vinegar (some)
蚝油（4克）
Oyster sauce (4g)
生抽酱油（5克）
Light soy sauce (5g)
白糖（少许）
Sugar (a little)

字幕
0:00:00.300,0:00:01.420
哈喽大家好 我是王刚
Hi everyone, this is Wang Gang
0:00:01.420,0:00:03.360
本期视频我给大家分享一道家常菜
In this video I will share an everyday dish
0:00:03.800,0:00:05.080
土豆拌茄子
Eggplant and Potato Cold Dish
0:00:05.420,0:00:08.140
处理食材之前首先我们准备1盆清水
Before we preprocess the ingredients, prepare a basin of water
0:00:09.225,0:00:11.600
然后在清水中加入适量的白醋
Then add some rice vinegar to the water
0:00:12.300,0:00:14.125
准备好之后放一边备用
Then set it aside
0:00:14.375,0:00:16.900
准备土豆1个去皮之后切成小颗粒备用
Prepare a potato, remove the skin, and dice it
0:00:17.225,0:00:19.950
嫌麻烦的同学也可以切成4毫米左右的片
If that's too much for you, you can cut it into 4mm-thick slices
0:00:20.198,0:00:22.286
这一步的目的是让土豆更容易成熟
This is to make the potato easier to be cooked
0:00:25.177,0:00:27.223
切好之后放入白醋水中浸泡备用
Having cut the potatos, put it in the water with rice vinegar
0:00:27.588,0:00:30.187
准备茄子1条对半切开之后切成小块备用
Prepare an eggplant, slice it in half, and cut it to small pieces
0:00:30.501,0:00:33.121
同学们茄子大约切成土豆的3倍大小即可
These pieces should be 3 times as large as the potato ones
0:00:35.469,0:00:36.972
然后放入盆中浸泡备用
Then put them in the basin too
0:00:37.411,0:00:40.208
加醋浸泡土豆和茄子可以防止其氧化变黑
Adding vinegar and placing the potato and eggplant in the mixture can prevent them from oxidizing and turning dark
0:00:40.354,0:00:42.453
但是同学们切记土豆不能泡太久（60分钟以上）
But keep in mind, we can't leave them there for too long (more than 60 minutes)
0:00:42.734,0:00:44.676
否则土豆将会变软口感不好
Or the potato will soften and can't have the same texture
0:00:46.106,0:00:49.425
然后我们将土豆茄子和醋水直接上锅蒸25分钟左右
Then we steam the potato and eggplant in the mixture for 25 minutes
0:00:49.770,0:00:52.202
这样能够最大限度的保证茄子的紫色
This will keep the purple color of the eggplant from fading as much as possible
0:00:52.526,0:00:53.945
下一步开始准备料汁
Next, prepare the sauce
0:00:54.613,0:00:56.576
准备大蒜几颗拍散之后剁碎备用
Prepare a few garlic cloves, break them up, and mince them
0:01:01.054,0:01:02.620
准备小葱头几根切碎备用
Prepare a few green onions and mince them
0:01:04.895,0:01:06.273
碗中加入蚝油4克
Add 4g of oyster sauce to the bowl
0:01:07.223,0:01:08.810
加入生抽酱油12克
Add 12g of light soy sauce
0:01:10.135,0:01:11.200
加入少许白糖（约1克）
Add a little bit of sugar (around 1g)
0:01:12.317,0:01:14.895
搅拌均匀之后加入适量的香辣红油拌匀即可
Mix them, add some red chili oil, and mix again
0:01:15.146,0:01:16.847
不能吃辣的同学也可以不加
If you don't like spicy food, you can skip this step
0:01:22.682,0:01:26.064
25分钟之后将蒸熟软的茄子和土豆捞出沥干水分
After 25 minutes, take the softened eggplant and potato out and remove the moisture
0:01:29.519,0:01:31.357
待稍微凉一会之后倒入盘中
Let them rest till they turn cold and place them in a plate
0:01:32.912,0:01:34.937
最后将调好的料汁淋在上面即可
Finally pour the sauce over the veggies
0:01:36.520,0:01:39.380
一道非常开胃下饭的土豆拌茄子就制作完成
A really appetizing dish that's great with rice, Eggplant and Potato Cold Dish, is ready to be served
0:01:44.840,0:02:01.520
下面开始技术总结
第一，土豆不能切太大否则不能熟透，茄子应切大块些这样才能久蒸
第二，原料泡在水里面蒸可以有效防止营养流失
第三，此菜必须将水份沥干再淋料汁，否则口味容易冲淡
土豆拌茄子的技术总结完毕
Now let's summarize the techniques
First, the potato can't be diced into large pieces or they won't be fully cooked, while the eggplant pieces can be larger so that they don't shrink too much when being steamed
Secondly, steaming the veggies in water can keep most of the nutritient
Thirdly, you need to remove the water before pouring the sauce, or the flavor will be diluted
Above are all the techniques for the Eggplant and Potato Cold Dish
