### ISSUE TITLE
【美食作家王刚】 添置新厨具 - https://youtu.be/SnkbHXw9T_8

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1182]
**视频链接**：https://youtu.be/SnkbHXw9T_8

视频时长5:16，预计发布时间为北京时间6月20日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
新厨房整修基本完工，添置的新厨具已到，3台猛火灶，3个打荷台，2台大冰箱，就等水电到位！

简介
大家好，我定购的新厨具到了！3台猛火灶，3个打荷台，2台大冰箱，1台6火眼煤气灶，还有新的砧板和一些零碎的厨房用具，渐渐地厨房已经有了我想象的样子。相信不少朋友知道我的梦想是想拥有自己的餐厅自己的后厨，因为我是真的喜爱的行业，也可以说这就是我的兴趣，真的很期待！也祝愿大家也能找到以为之奋斗的兴趣，感谢大家一直以来的支持，没有大家的支持也就没有我的今天。

字幕
0:01:05.075,0:01:06.163
哈喽 大家好 

0:01:06.163,0:01:10.850
今天这个灶 冰箱 打荷台都到了

0:01:11.250,0:01:13.925
现在刚刚卸完货特别热

0:01:13.950,0:01:16.550
我们那个旧的灶可能有800多斤

0:01:16.775,0:01:20.325
很难抬 七八个人抬着要轻松一点

0:01:20.325,0:01:22.700
我们今天只有5个人所以抬着比较累

0:01:23.325,0:01:26.625
现在就等师傅再拉一车过来 再卸完这个

0:01:26.875,0:01:30.350
然后就可以摆进去了 现在我们地板已经装好了

0:01:30.350,0:01:31.650
你看一下

0:01:35.725,0:01:38.825
冰箱 灶  打荷台都到了

0:01:40.475,0:01:44.975
我们砧板都换了 不用那个松木的现在用这个皂木的

0:01:45.250,0:01:50.300
这个厚度是10公分的  直径应该是40多（厘米）接近50厘米 

0:01:51.075,0:01:53.425
有五六十斤吧这个

0:01:55.275,0:02:00.025
这个相对于松木来说木质更硬一些 然后不容易发霉

0:02:00.125,0:02:03.700
但是颜色花纹可能没有那么好看

0:02:03.900,0:02:06.725
然后就是比松木要耐用一点 贵也要贵很多

0:02:08.950,0:02:10.700
这个的花纹要更好看一些

0:02:11.475,0:02:16.350
因为它这个芯在这个地方 这一台的话它的芯偏了一点点

0:02:16.500,0:02:20.075
偏了大概5公分左右 所以就没有这个那么好

0:02:20.650,0:02:24.050
现在我们这个灶跟以前的灶有一点不太一样

0:02:24.375,0:02:27.594
现在这个是主气 这个是火种 

0:02:27.975,0:02:30.150
然后这里有一个风门开关

0:02:31.475,0:02:34.750
所以就不用另外去接一个开关  现在这个很方便

0:02:35.550,0:02:37.625
然后这里还有一个这个打开

0:02:37.625,0:02:39.285
上面可以流水下来洗这个灶

0:02:39.285,0:02:40.425
自动清洗这个叫

0:02:41.225,0:02:45.575
而且现在这种灶大概只有600多斤吧

0:02:45.575,0:02:51.100
然后我们以前的 比如说后面这一台灶大概有800多斤

0:02:51.100,0:02:52.375
要重很多

0:02:53.800,0:02:55.850
现在我们就把灶抬进来

0:02:55.850,0:03:01.121
然后等到明天的时候水电工过来把这里的线 水接好之后

0:03:01.121,0:03:02.575
就把这个装上去

0:03:03.400,0:03:05.575
装上去了之后再撕这个膜

0:03:05.775,0:03:08.150
撕完这个膜的话就基本上差不多了

0:03:08.150,0:03:12.350
再一个就是这个冰箱水电 还有排水系统这方面的

0:03:12.525,0:03:15.000
大概搞这个要花3天左右吧

0:03:15.200,0:03:17.125
现在地板都已经铺好了

0:03:24.750,0:03:25.700
OK

0:04:01.475,0:04:03.375
你这块板没有装好吧

0:04:08.200,0:04:09.525
锅没拿

0:04:10.000,0:04:11.925
你该给我拿几个锅撒

0:04:12.200,0:04:13.050
啊

0:04:13.050,0:04:14.400
至少都要拿2个锅

0:04:16.925,0:04:19.175
锅啊 炒锅啊

0:04:19.175,0:04:20.050
我晓得

0:04:21.600,0:04:22.425
没拿过来

0:04:22.425,0:04:23.875
没写进去还是说

0:04:24.050,0:04:25.025
没写

0:04:25.025,0:04:26.100
没写是吧

0:04:26.100,0:04:27.900
那你下单嘛 帮我下

0:04:28.625,0:04:30.000
店里有

0:04:30.375,0:04:31.375
店里有是吧

0:04:31.375,0:04:31.975
有

0:04:34.525,0:04:37.525
我就说好像少了一点什么东西这个灶上面

0:04:37.525,0:04:38.950
原来是没有买锅

0:04:39.225,0:04:46.074
要6个锅 还有炒勺 锅铲 还有那个宽油盆 漏勺之类的

0:04:46.575,0:04:48.750
今天我们这个就差不多了

0:04:48.775,0:04:54.925
3台灶 3个打荷台 2台冰箱 还有一个6眼的灶

0:04:55.175,0:04:57.900
这些最基本的东西已经进来了

0:04:58.225,0:05:00.150
今天就先搞到这里 今天也搞累了

0:05:00.150,0:05:02.675
光抬这些东西抬得腰酸背痛的

0:05:02.925,0:05:04.300
嗯 这些灶都很重

0:05:04.750,0:05:07.600
然后下一步就等着水电一装好

0:05:07.825,0:05:13.900
然后就把其它的该买的一些零部件就全部给它一次性弄到位

0:05:13.900,0:05:16.125
好啦 本期视频就到这里 拜拜


```

**Comment by Summer0208** [comment]
认领

**Comment by Summer0208** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
新厨房整修基本完工，添置的新厨具已到，3台猛火灶，3个打荷台，2台大冰箱，就等水电到位！
The new kitchen is basically built up.  All the new kitchen utensils have arrived, three cookstoves, three kitchen workbenches, and two refrigerators.  Everything will be done after the water and electric system to set up. 
简介
大家好，我定购的新厨具到了！3台猛火灶，3个打荷台，2台大冰箱，1台6火眼煤气灶，还有新的砧板和一些零碎的厨房用具，渐渐地厨房已经有了我想象的样子。相信不少朋友知道我的梦想是想拥有自己的餐厅自己的后厨，因为我是真的喜爱的行业，也可以说这就是我的兴趣，真的很期待！也祝愿大家也能找到以为之奋斗的兴趣，感谢大家一直以来的支持，没有大家的支持也就没有我的今天。
Hello guys, new kitchen utensils have arrived: three cookstoves, three kitchen workbenches, and two refrigerators. The cookstove with six fireplace, and brand new cutting board; and some random kitchen stuff. The kitchen is set up as I wish for. I know some of my friends know that my dream is to have my own restaurant and kitchen. Because I really love this field, and it is my interest. I’m looking forward to it. I wish that you could find your own interests and fight for it. Thank you all for your support, I cannot achieve this without you guys. 
字幕
0:01:05.075,0:01:06.163
哈喽 大家好 
Hello everyone. 
0:01:06.163,0:01:10.850
今天这个灶 冰箱 打荷台都到了
The cookstove, refrigerator, and kitchen workbench arrived today. 
0:01:11.250,0:01:13.925
现在刚刚卸完货特别热
We just offloaded them, and it’s so hot today. 
0:01:13.950,0:01:16.550
我们那个旧的灶可能有800多斤 
The old cookstove is about 800 jin (400 kg). 
0:01:16.775,0:01:20.325
很难抬 七八个人抬着要轻松一点
It is so hard to move, maybe it could easier if seven or eight people lift it together. 
0:01:20.325,0:01:22.700
我们今天只有5个人所以抬着比较累
But we only have 5 people here today which made the work tiring. 
0:01:23.325,0:01:26.625
现在就等师傅再拉一车过来 再卸完这个
Now we are waiting for another truck of stuff. And after offloading this, 
0:01:26.875,0:01:30.350
然后就可以摆进去了 现在我们地板已经装好了
we could bring everything in and the floor is done already. 
0:01:30.350,0:01:31.650
你看一下
look at this, 
0:01:35.725,0:01:38.825
冰箱 灶  打荷台都到了
refrigerator, cookstove, kitchen workbench are all arrived. 
0:01:40.475,0:01:44.975
我们砧板都换了 不用那个松木的现在用这个皂木的
We changed the cutting board. we got ride of the pine one and using the soapwood now. 
0:01:45.250,0:01:50.300
这个厚度是10公分的  直径应该是40多（厘米）接近50厘米 
This one is about 10 centimeters high, and 40, close to 50 centimeters wide,
0:01:51.075,0:01:53.425
有五六十斤吧这个
about 50 to 60 jin (25-30kg). 
0:01:55.275,0:02:00.025
这个相对于松木来说木质更硬一些 然后不容易发霉
Compare with the pine cutting board, this one is firmer and less easy to get mold. 
0:02:00.125,0:02:03.700
但是颜色花纹可能没有那么好看
But the pattern may not look so pretty. 
0:02:03.900,0:02:06.725
然后就是比松木要耐用一点 贵也要贵很多
And this one lasts longer than pine wood, and much expensive. 
0:02:08.950,0:02:10.700
这个的花纹要更好看一些
The pattern on this one looks better. 
0:02:11.475,0:02:16.350
因为它这个芯在这个地方 这一台的话它的芯偏了一点点
Because the middle point is right here, but it is a little bit off on this one. 
0:02:16.500,0:02:20.075
偏了大概5公分左右 所以就没有这个那么好
It is off for about 5 cm, so not perfectly good. 
0:02:20.650,0:02:24.050
现在我们这个灶跟以前的灶有一点不太一样
And this cooker is a little bit different than the one we used to have. 
0:02:24.375,0:02:27.594
现在这个是主气 这个是火种 
This one uses gas and this one uses fire. 
0:02:27.975,0:02:30.150
然后这里有一个风门开关
and there is a fan switch here. 
0:02:31.475,0:02:34.750
所以就不用另外去接一个开关  现在这个很方便
so you don’t have to connect another switch, this is so convenient.  
0:02:35.550,0:02:37.625
然后这里还有一个这个打开
and here is another thing, you can open it, 
0:02:37.625,0:02:39.285
上面可以流水下来洗这个灶
so you can wash the cookstove with water from up here. 
0:02:39.285,0:02:40.425
自动清洗这个叫
this is called an auto cleaner. 
0:02:41.225,0:02:45.575
而且现在这种灶大概只有600多斤吧
and this cookstove is only about 600 jin(300kg). 
0:02:45.575,0:02:51.100
然后我们以前的 比如说后面这一台灶大概有800多斤
and the one we used to have, like the one on the back is about 800 jin(400 kg), 
0:02:51.100,0:02:52.375
要重很多
which is much heavier. 
0:02:53.800,0:02:55.850
现在我们就把灶抬进来
now we move the cookstove in. 
0:02:55.850,0:03:01.121
然后等到明天的时候水电工过来把这里的线 水接好之后
And the plumber will come tomorrow to connect the line. 
0:03:01.121,0:03:02.575
就把这个装上去
After that, we will build this up, 
0:03:03.400,0:03:05.575
装上去了之后再撕这个膜
and then we tear the cover off, 
0:03:05.775,0:03:08.150
撕完这个膜的话就基本上差不多了
and after that, we are basically done. 
0:03:08.150,0:03:12.350
再一个就是这个冰箱水电 还有排水系统这方面的
Another one is to build up hydropower for refrigerator, and the drainage system. 
0:03:12.525,0:03:15.000
大概搞这个要花3天左右吧
It could cost about three days. 
0:03:15.200,0:03:17.125
现在地板都已经铺好了
Now the floor is all done, 
0:03:24.750,0:03:25.700
OK
ok, 
0:04:01.475,0:04:03.375
你这块板没有装好吧
Did you build this piece correctly? 
0:04:08.200,0:04:09.525
锅没拿
Forgot to bring the pots.  
0:04:10.000,0:04:11.925
你该给我拿几个锅撒
Could you bing me few pots? 
0:04:12.200,0:04:13.050
啊
ahh, 
0:04:13.050,0:04:14.400
至少都要拿2个锅
We need at least two pots. 
0:04:16.925,0:04:19.175
锅啊 炒锅啊
pans, like pry pans, 
0:04:19.175,0:04:20.050
我晓得
I know. 
0:04:21.600,0:04:22.425
没拿过来
I didn’t bring them. 
0:04:22.425,0:04:23.875
没写进去还是说
You didn’t write it done or what? 
0:04:24.050,0:04:25.025
没写
I forgot to write it. 
0:04:25.025,0:04:26.100
没写是吧
Didn’t write it done, right? 
0:04:26.100,0:04:27.900
那你下单嘛 帮我下
Make the order for me, then.  
0:04:28.625,0:04:30.000
店里有
We have then at the store, 
0:04:30.375,0:04:31.375
店里有是吧
There are some at the store? 
0:04:31.375,0:04:31.975
有
Yes.  
0:04:34.525,0:04:37.525
我就说好像少了一点什么东西这个灶上面
I knew there is something missing on the cooker. 
0:04:37.525,0:04:38.950
原来是没有买锅
We forgot to buy pots. 
0:04:39.225,0:04:46.074
要6个锅 还有炒勺 锅铲 还有那个宽油盆 漏勺之类的
we need six pots, wok, the kuanyou bowl, and things like colanders. 
0:04:46.575,0:04:48.750
今天我们这个就差不多了
That’s about it today. 
0:04:48.775,0:04:54.925
3台灶 3个打荷台 2台冰箱 还有一个6眼的灶
Three cookstoves, three kitchen workbench, two refrigerators, and a cooker with 6 fire spots. 
0:04:55.175,0:04:57.900
这些最基本的东西已经进来了
All that basic stuff has arrived. 
0:04:58.225,0:05:00.150
今天就先搞到这里 今天也搞累了
That is for today, everyone is tired. 
0:05:00.150,0:05:02.675
光抬这些东西抬得腰酸背痛的
Lifting just those things could cost low back pain.  
0:05:02.925,0:05:04.300
嗯 这些灶都很重
Yeah, all of them are heavy. 
0:05:04.750,0:05:07.600
然后下一步就等着水电一装好
And the next step is to wait for the hydropower to be set up. 
0:05:07.825,0:05:13.900
然后就把其它的该买的一些零部件就全部给它一次性弄到位
Then we will buy some parts and finish everything one time. 
0:05:13.900,0:05:16.125
好啦 本期视频就到这里 拜拜
Okay, that’s it for today’s video, bye-bye.
