### ISSUE TITLE
[华农兄弟] 蜂蜜烤鸡 - https://youtu.be/IMlWdKWpbzc

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1184]
https://youtu.be/IMlWdKWpbzc
<p>&#35270;&#39057;&#21457;&#24067;&#20110; June 18, 2020 at 02:08PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/IMlWdKWpbzc

#华农兄弟：拉了一车蜂蜜回来，搞1瓶去兄弟家烤鸡，味道还可以哟
#Huanong Brothers: We've taken a lorry of honey back. We take a jar and grill a chicken with at my buddy's place. It's not bad.

0:00:00.000,0:00:03.760
# 大家好 你看  今天這個  卸的  卸的是那個助農產品哦
Hi everyone! Look! Today, this is, we're unloading, unloading the agricultural products from our poverty alleviation project.

0:00:03.760,0:00:05.960
# 兄弟家的蜂蜜  都拉去檢測了
My buddy's honey, was sent for quality inspection.

0:00:06.080,0:00:09.380
# 你看這個  合格証書  全都檢測合格
Look! These are, certificates of approval. All have passed the inspection.

0:00:10.620,0:00:12.680
# 這個  滿滿的一車啊
Here is, a whole lorry.

0:00:14.020,0:00:16.300
# 現在幫忙搬一下  太多啦  一大車
Now I'm gonna help them. There are too many, one whole lorry.

0:00:16.300,0:00:17.760
# 這一箱差不多有60斤重
Each box weighs almost 30 kilograms.

0:00:20.820,0:00:21.760
# 差不多60斤
Almost 30 kilograms

0:00:24.360,0:00:25.780
# 誒呦  那麼重的
Eyo! It's so heavy!

0:00:36.340,0:00:38.080
# 不要太高  太高了不好下
Not too high! You can't unload them if it's too high.

0:00:38.160,0:00:39.560
# 等下  會翻掉的哦
It might, even flip over, you know.

0:00:39.700,0:00:40.620
# 這車不好啦的
Pulling this cart is no easy task.

0:00:42.120,0:00:42.780
# 啊~
Ah~

0:00:43.840,0:00:44.840
# 這差不多五六十斤
It's twenty five or even thirty kilograms.

0:00:45.560,0:00:46.220
# 那麼重
So heavy

0:00:48.960,0:00:50.880
# 兄弟都  都是從農戶手上收的
My buddies have, these are all collected from the farmers.

0:00:52.200,0:00:54.040
# 要不是他收了 農戶就不好賣
The farmers have very limited channels to sell their products if my buddy is not collecting from them.

0:00:55.280,0:00:57.080
# 好快哦 一車馬上就卸掉了
It doesn't take long! We're about to have one whole lorry unloaded.

0:01:02.200,0:01:04.380
# 裝多一車就夠了  先把它拉進去
One more turn will end our job. Let's pull it inside first.

0:01:09.220,0:01:12.180
# 聽說兄弟家養了很多土雞土鴨還有土鵝
I heard that my buddy is keeping a lot of free range poultry here, like, chicks, ducks and geese as well.

0:01:13.160,0:01:14.320
# 更多的是那個魚
What's even more are the fish.

0:01:14.600,0:01:16.800
# 一池塘都是魚  搞一瓶蜂蜜
The whole pond is filled with fish. I've taken a jar of honey with me.

0:01:17.500,0:01:19.220
# 送兄弟 他家就在這裡
I'm gonna give it to my buddy. Here's his place.

0:01:20.880,0:01:22.540
# 你看 蓮花 哎呀
Look! Lotus! Aya!

0:01:23.360,0:01:26.120
# 這種  這個  有一個蓮子 可以吃的哦  這個蓮子
This is, this one, there's a lotus seed. The lotus seed is edible, you know.

0:01:27.220,0:01:28.100
# 很好吃的
And it's really tasty.

0:01:29.080,0:01:29.840
# 絕對OK
Absolutely OK!

0:01:42.800,0:01:44.480
# 掉下去啦  別以為我不要你
It fell. Don't think that I'm letting you go.

0:01:45.680,0:01:47.200
# 掉下去我也要把你檢回來
I'm gonna pick you up, even you fell.

0:01:56.720,0:01:58.360
# 這個蓮子  有肉哦
This lotus seed, the inner part is edible.

0:01:58.940,0:02:00.840
# 剛剛好大的哦  很嫩的  這種蓮子
It's just huge! This kind of lotus seed is really young and tender.

0:02:02.460,0:02:03.240
# 一點都不苦
It's not bitter at all.

0:02:08.340,0:02:09.060
# 還有好多啊
There are still a lot!

0:02:10.860,0:02:12.340
# 等一下來 等一下
Later, I'll come again later.

0:02:14.200,0:02:15.300
# 先找一下兄弟
Let me figure out my buddy's whereabouts first.

0:02:16.680,0:02:17.720
# 問他去哪裡啦
I'm gonna ask them where he is.

0:03:04.280,0:03:06.940
# 兄弟又不在 把這個蜂蜜一下在這裡
My buddy is not around. Let me leave the honey here in a while.

0:03:07.500,0:03:08.460
# 這是他家的魚塘
This is his pond.

0:03:08.980,0:03:09.740
# 好大呀
It's huge!

0:03:10.880,0:03:12.120
# 應該有幾十畝哦
There should be several hectares.

0:03:12.600,0:03:13.600
# 那裡面還有
It's all the way over there.

0:03:14.240,0:03:16.140
# 我去看一下他的雞  我的雞就養在那裡面
I'm gonna have a look at his chicks. He's keeping his chicks there inside.

0:03:16.660,0:03:17.400
# 看一下
Let me see,

0:03:18.160,0:03:18.940
# 好不好吃了
if they taste good.

0:03:20.580,0:03:21.540
# 蜂蜜放到這裡先
I leave the honey here first.

0:03:31.700,0:03:33.220
# 你看  這兄弟的大門
Look! This is my buddy's gate.

0:03:34.700,0:03:38.040
# 這也能網雞 連我都網不住  還能網雞
Does he think that it can fence up the chicks? It can't even fence me off, let alone the chicks.

0:03:43.700,0:03:45.520
# 你看  這裡有山胡椒的果子哦
Look! Here are the fruits of wild pepper.

0:03:46.300,0:03:47.020
# 好香的
It smells so good!

0:03:49.100,0:03:50.020
# 神清氣爽
Refreshing!

0:03:58.080,0:04:00.520
# 你看  兄弟家的雞  就在這裡哦
Look! My buddy's chicks, are right here.

0:04:01.080,0:04:01.840
# 終於看到啦
I can see them finally.

0:04:05.020,0:04:06.640
# 沒帶東西  拍抓不到
Without any tools, I wonder if I can catch them.

0:04:07.560,0:04:09.260
# 抄網都沒有這裡
Here's not even a catch net.

0:04:09.740,0:04:10.780
# 怎麼抓嘞
How can I catch them?

0:04:12.340,0:04:13.740
# 你看  還有這個抄網
Look! Here's still a catch net.

0:04:14.360,0:04:16.840
# 沒這個抄網的話  怎麼抓都抓不到
There's simply no way to catch them without the catch net.

0:04:20.360,0:04:20.860
# 你看
Look!

0:04:21.640,0:04:22.240
# 在那裡
Over there!

0:04:23.480,0:04:26.720
# 不要走  這裡有好吃的  快點過來
Don't run away! Here's some very good food! Come here!

0:04:27.720,0:04:29.100
# 快點過來呦
Come here, guys!

0:04:32.440,0:04:34.260
# 你以為  你以為你跑很掉嗎
You think, you think that you can run away from me?

0:04:36.740,0:04:37.600
# 翻山越嶺
Over the mountains and the sea,

0:04:39.380,0:04:40.400
# 把你抓起來
I'm gonna catch you!

0:04:48.300,0:04:49.660
# 這雞跑的好快呀
These chicks run really fast.

0:04:50.680,0:04:51.500
# 抓都抓不到
I can't catch them.

0:04:56.580,0:04:57.600
# 到這裡肯定跑不了
There's no escape here.

0:04:58.620,0:04:59.220
# 你看
Look!

0:05:00.140,0:05:01.280
# 抓到它雞窩裡面啦
They've run into the roost.

0:05:02.220,0:05:03.380
# 把它趕到雞窩裡面啦
I've chased them off back to the roost.

0:05:04.000,0:05:05.220
# 現在就跑不了啦
There's no escape now.

0:05:07.020,0:05:08.080
# 老公雞
Old rooster

0:05:08.740,0:05:10.440
# 老閹雞  嘿嘿
Old capon, hay hay!

0:05:23.200,0:05:23.900
# 誒呀
Eya!

0:05:24.460,0:05:25.080
# 那麼重
It's so heavy!

0:05:25.800,0:05:27.220
# 你看  這個是閹雞來的
Look! This is a capon.

0:05:28.020,0:05:28.800
# 閹雞才好吃
Capon tastes the best.

0:05:28.800,0:05:30.920
# 差不多五六斤  七八斤都可能有
It almost three, or even four kilograms.

0:05:31.560,0:05:32.060
# 那麼重
It's so heavy.

0:05:32.880,0:05:33.660
# 很結實的哦
It's muscular, you know.

0:05:40.880,0:05:43.100
# 打你兩下  追了那麼就[SIC]才追到你
Beat you hard! You made me chase after you for such a long time!

0:05:45.100,0:05:45.640
# 閉嘴
Shut up!

0:05:46.180,0:05:48.260
# 別叫啦  沒人來救你的
Stop yelping! No one's gonna help you.

0:05:57.760,0:05:59.060
# 叫叫叫叫叫
Yelp, yelp, yelp and yelp

0:06:00.060,0:06:00.780
# 誒呀
Eya!

0:06:01.580,0:06:02.460
# 這裡有雞蛋哦
Here are some eggs!

0:06:04.060,0:06:04.820
# 這種雞蛋
These eggs,

0:06:06.260,0:06:08.220
# 還可以的這個  五黑雞
are not bad. These are, laid by,

0:06:08.800,0:06:09.400
# 下的蛋
black chickens.

0:06:10.360,0:06:11.720
# 就叫五黑雞蛋
So they're called, black chicken eggs.

0:06:13.820,0:06:15.100
# 誒呀  那麼多刺
Eya! So many spikes

0:06:33.220,0:06:35.560
# 你看  把這個雞抓回來啦  在在籠子上
Look! I've now taken the chicken back and it's now in the cage.

0:06:35.880,0:06:37.040
# 我看到它好孤單啊
It seems very lonely to me.

0:06:38.040,0:06:39.660
# 搞個鴨子給它做飯
Let me fetch it a duck, to cook for it.

0:06:40.300,0:06:41.460
# 在這裡有抄網
Here's a catch net.

0:06:41.800,0:06:42.960
# 鴨子這裡有幾隻
And there are a couple of ducks.

0:06:46.080,0:06:46.940
# 你看 鴨子
Look! Ducks!

0:07:34.480,0:07:35.960
# 誒呀  搞得一身都是水
Eya! It made me wet all over the body.

0:07:50.580,0:07:54.080
# 你看  雞跟鴨在一起 它們有伴啦  也不叫啦
Look! The chicken and duck are now together. They have a companion now and so they're not yelping anymore.

0:07:55.680,0:07:57.800
# 好 等一下我去看一下有沒有魚釣
Alright! Let me see if I can catch a fish in a while.

0:07:59.160,0:08:01.400
# 在那邊  那邊應該有魚
Over there. There must be fish.

0:08:02.220,0:08:05.180
# 你看  這兄弟的  兄弟這個玉米
Look! These are my buddy's, my buddy's corns.

0:08:06.120,0:08:07.460
# 搞點他的玉米來釣一下
I'm gonna fish with his corns.

0:08:15.580,0:08:16.840
# 這裡好多大魚的
Here are a lot of very big fish.

0:08:24.700,0:08:25.740
# 我也不怎會釣魚
I'm not really that good at fishing.

0:08:26.560,0:08:27.600
# 攝影小哥才會
Mr. Cameraman is the real master.

0:08:33.000,0:08:34.120
# 好啦  奶遠啦
Good! It's far enough.

0:08:37.300,0:08:41.680
# 釣魚要有耐心的哦 如果沒有耐心的話釣不到的
Patience is essential for fishing. Without patience, there's no chance of catching any fish.

0:08:44.560,0:08:45.360
# 釣到一條
I got one,

0:08:46.000,0:08:46.880
# 不知道甚東西
but only God knows what it is.

0:08:47.380,0:08:48.340
# 你看  它一直在拉
Look! It keeps on pulling.

0:08:48.560,0:08:51.380
# 我一扔下去它就咬到啦  我還以為沒沉到底那
It bit the hook soon after I had threw out the hook. I even thought that the hook was still floating.

0:08:52.200,0:08:53.780
# 這個是甚麼東西 你看
What is it? Look!

0:08:54.440,0:08:56.400
# 好大的力氣啊  杆子都彎啦
It's pulling so hard! The pole is already bent.

0:09:01.800,0:09:02.660
# 過來過來過來
Come here, come here, come here

0:09:06.060,0:09:09.700
# 誒呦  可以  過來過來過來 過來 過來
Eya! Yea! Come here, come here, come here. Here, here!

0:09:12.440,0:09:13.140
# 這甚麼魚
What fish is it?

0:09:13.140,0:09:14.480
# 青魚  青草魚
Green, green grass carp

0:09:14.480,0:09:16.480
# 這種比草魚  肉要緊
Its meat is, firmer that that of grass carps.

0:09:17.840,0:09:18.980
# 嘿  別動  別動
Hey! Don't move, don't move!

0:09:19.360,0:09:20.740
# 我們那邊叫石草魚
It's called rock grass carp at my place.

0:09:21.240,0:09:22.080
# 吞進去啦
Has it swallowed the hook?

0:09:22.780,0:09:24.100
# 鈎都掉了
The hook is gone!

0:09:25.060,0:09:26.200
# 它咬著不放
It's not spitting it out.

0:09:27.360,0:09:28.220
# 這個拿回去
Let's take it back.

0:09:28.520,0:09:30.180
# 拿回去  這個拿來加餐
Take it back. We'll have an extra dish.

0:09:30.580,0:09:32.220
# 你看  這個兄弟貢獻的炭哦
Look! This is the charcoal, contributed by my buddy.

0:09:33.780,0:09:35.180
# 他說給一箱炭給我
He said that he's giving me a box of charcoal.

0:09:35.560,0:09:36.500
# 這個炭是
This charcoal is,

0:09:36.920,0:09:37.840
# 最便直的
the cheapest one.

0:09:39.060,0:09:40.340
# 他說  他說贊助我
He said, he said that he would sponsor me.

0:09:40.940,0:09:43.500
# 雞也不讚助一個  鴨也不贊助一個
But he sponsors me neither a chicken, nor a duck.

0:09:49.620,0:09:50.180
# 哎喲
Ayo!

0:09:51.960,0:09:52.940
# 燒了一下我
I got burnt.

0:09:57.300,0:09:59.640
# 你看  這個雞和鴨都已經處理好啦
Look! The chicken and the duck have already been processed.

0:10:00.920,0:10:01.580
# 把它先
Let me first,

0:10:02.080,0:10:02.720
# 先這
I mean,

0:10:03.580,0:10:06.260
# 要先砍碎一點 要不然等下烤不  烤不了的
I need to chop it a few times first. Otherwise, it wouldn't be possible to grill it.

0:10:06.540,0:10:07.120
# 這個
I ah,

0:10:07.840,0:10:08.740
# 多割一下
slice it a few more times.

0:10:12.600,0:10:15.000
# 好啦  姿劫要擺好來
Alright! The posture is important.

0:10:19.080,0:10:20.980
# 腳指卡在這裡就行啦
I think I can simply hinge the toe here.

0:10:26.980,0:10:28.960
# 嘿  搞定  你看
Hey! Done! Look!

0:10:29.380,0:10:30.400
# 這個姿勢好
It's a nice posture.

0:10:33.000,0:10:35.280
# 沒有兩個夾子  有兩個夾子就
It's too bad that I don't have another grilling net. If I had another net, I would,

0:10:35.520,0:10:37.320
# 左手一隻雞  右手一隻鴨
have a chicken on my left hand, and a duck on my right hand.

0:10:38.620,0:10:40.060
# 現在只能一個一個烤
But now I can only grill them one by one.

0:10:48.780,0:10:49.940
# 哇  好香啊
Wa! It smells so good!

0:10:50.460,0:10:51.540
# 好香味出來啦
I can already smell it.

0:10:57.260,0:10:58.300
# 站的好累呀
Standing is really tiring.

0:10:59.280,0:10:59.960
# 著火啦
It's on fire.

0:11:06.440,0:11:07.180
# 好燙啊
It so hot!

0:11:17.980,0:11:18.760
# 刷點油
Spray some oil

0:11:20.880,0:11:22.020
# 燙的更香
It smells much better.

0:11:22.400,0:11:23.780
# 這火太大啦  這個
The fire is too strong, here.

0:11:35.140,0:11:37.300
# 哎呀  就燒黑啦
Aya! So it's burnt.

0:11:39.620,0:11:40.580
# 放到這裡來
Put it on this side.

0:11:41.200,0:11:43.280
# 太快啦  一下子就燒黑啦  太多油啦
It caught me off guard. It got burnt all of a sudden. There was too much oil.

0:11:43.800,0:11:45.280
# 你看  這個  黑掉啦
Look! Here, it's burnt.

0:11:47.420,0:11:49.620
# 誒呀  烤東西不好烤哦
Eya! Grilling is never an easy task.

0:11:55.500,0:11:57.660
# 哎喲  這個蜂蜜來咯
Ayo! Here comes the honey!

0:11:58.480,0:11:59.340
# 加點蜂蜜
Put some honey.

0:12:00.700,0:12:01.840
# 香香甜甜
It's sweet with a scent of honey,

0:12:02.300,0:12:04.300
# 酸  香甜苦辣都有
so there's sourness, fragrance, sweetness, bitterness and spiciness, everything.

0:12:17.060,0:12:19.440
# 哇  下雨啦  要不要這樣子啊
Wa! It rains! C'mon, it's not nice!

0:12:19.960,0:12:21.960
# 我鴨子都還沒烤  魚也還沒烤
I've not yet grilled the duck, nor the fish.

0:12:22.260,0:12:23.720
# 都直接用那個
Let's simply use the,

0:12:25.880,0:12:28.460
# 直接去煮算啦  不能  不能烤啦
I mean, cook them right away. No more, no more grilling.

0:12:29.760,0:12:32.020
# 蜜汁燒雞  煮好啦
Honey grilled chicken. Done!

0:12:40.880,0:12:42.440
# 來  搞點孜然粉
Yea, put some, cummin powder.

0:12:43.220,0:12:44.440
# 味道杠杠的
C'est délicieux!

0:12:46.180,0:12:47.360
# 好  先看一下
Alright! Let me see,

0:12:47.900,0:12:48.600
# 好不好吃
if it taste good.

0:12:55.640,0:12:56.940
# 哇  真的不錯耶
Wa! It's really not bad!

0:12:58.240,0:12:59.160
# 味道還可以喲
It tastes rather good.

0:13:00.620,0:13:01.300
# 這個不是
It's no,

0:13:02.100,0:13:03.060
# 不是騙人的
no kidding.

0:13:05.720,0:13:06.880
# 下雨啦  下雨啦
It rains, it rains!

0:13:07.820,0:13:08.980
# 趕快收 趕快收
Hurry up! Grab everything!

0:13:09.180,0:13:10.680
# 等下  等下想吃
Don't let, don't,

0:13:12.600,0:13:13.740
# 雞都沒得吃啦
don't let the rain spoil the chicken.

0:13:17.200,0:13:18.200
# 先把雞搞走先
Let me take the chicken away first.

0:13:21.460,0:13:23.620
# 剛剛下了大雨  又起了大風
The rain just poured and the wind blew heavily.

0:13:23.680,0:13:25.660
# 幸好把這個雞搶  搶回來啦
Fortunately, I've grabbed, grabbed the chicken back.

0:13:25.880,0:13:27.120
# 要不然都淋雨啦
Otherwise it would be soaked.

0:13:28.760,0:13:29.560
# 嘗一下這個
Let me try the,

0:13:30.000,0:13:31.420
# 雞腿 看一下怎麼樣
chicken leg, and see how it is.

0:13:32.600,0:13:33.200
# 你看  全熟啦
Um!

0:13:35.780,0:13:37.180
# 那個鴨子跟魚就沒辦烤啦
Look! It's well done.

0:13:39.980,0:13:41.920
# 直接煮啦
There's to way to grill the duck and the fish.

0:13:43.380,0:13:44.220
# 煮了之後  (註︰這句和之後兩句有點語無倫次，所以隨便找點差不多的字就算了)
We'll simply cook them.

0:13:45.700,0:13:46.500
# 就直接
Cooking them,

0:13:47.220,0:13:47.960
# 紅燒魚
it means,

0:13:48.860,0:13:49.640
# 哎  搞一個雞腿吃一下
braised fish.

0:13:51.500,0:13:52.980
# 哎喲  可以喲
Ya! Let me have a chicken leg.

0:13:58.040,0:13:59.440
# 熟啦
Aya! Not bad!

0:14:02.560,0:14:03.240
# 就是有點黑
It's done.

0:14:03.960,0:14:05.060
# 有點難看
It's just a bit burnt,

0:14:06.320,0:14:07.180
# 嗯
and a bit ugly.

0:14:11.440,0:14:12.120
# 可以喲
Um!

0:14:12.900,0:14:13.740
# 特別好吃
Not bad!

0:14:15.000,0:14:15.940
# 刮風又大 下  又刮風又下雨
It's exceptionnaly good!

0:14:16.680,0:14:18.880
# 刷了蜂蜜特別好吃  真的
Strong wind is, rain, the wind and the rain comes again.

0:14:20.760,0:14:22.240
It tastes exceptionally good with the honey. No kidding.
