### ISSUE TITLE
【美食作家王刚】包粽子 - https://youtu.be/BnwtIj-JMlU

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1185]
**视频链接**：https://youtu.be/BnwtIj-JMlU

视频时长8:58，预计发布时间为北京时间6月21日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
王刚第一次尝试自己包粽子，让红案厨师做白案还需更多学习，味道不错，但米没泡够

简介
大家好，过端午了，所以决定尝试一下自己来包粽子。在这里给大家介绍一个中式厨师的概念“红白案”，一般做厨师会分为这两种。其中“红案”为各种菜肴的烹饪，包括从选材，材料加工，配菜，烹饪，摆盘等等。而“白案”以米面点为主，馒头，花卷，水饺，包子，面条等等，其中也包括粽子。理论上红白案可以互补或独立，各有所攻所长，大家肯定看得出来我就是一个彻头彻尾的“红案”厨师，所以“白案”功夫有限，还需更多的学习，努力充实自己，学无止境。最后祝大家端午节快乐！

字幕
0:00:00.570,0:00:03.130
哈喽 大家好 现在快要到端午节了

0:00:03.139,0:00:04.253
我们今天弄一点粽子

0:00:04.747,0:00:08.078
这个粽子（米）我四伯爷已经泡了两三个小时了嘎

0:00:08.078,0:00:09.514
两三个小时是有的

0:00:09.514,0:00:11.919
这里是4斤糯米

0:00:12.017,0:00:14.091
然后一斤这个

0:00:14.196,0:00:15.518
饭米饭米

0:00:15.737,0:00:19.724
那我们包啥子安 有蛋黄有那个香肠腊肉

0:00:20.513,0:00:22.292
就包香肠腊肉的好吃点

0:00:22.673,0:00:23.630
包香肠腊肉的啊

0:00:23.634,0:00:27.854
嗯 包蛋的麻烦得很 就包那个简单点的

0:00:28.782,0:00:32.521
我们这个蛋黄老人家胆固醇比较高

0:00:32.521,0:00:33.282
所以就

0:00:33.882,0:00:36.964
反正我四伯爷也喜欢吃肉嘛就包香肠腊肉就行了

0:00:37.630,0:00:38.848
然后现在还差个粽叶

0:00:39.248,0:00:40.161
走嘛 我们去摘粽叶

0:00:40.666,0:00:42.188
走嘛 就到我们背后去摘

0:00:42.188,0:00:45.385
我那儿有我栽的笋竹的竹叶很大片一个

0:00:45.689,0:00:46.327
好 要得

0:00:46.498,0:00:47.421
就摘点来包

0:00:47.507,0:00:47.840
好

0:00:49.105,0:00:50.009
就是那个是不

0:00:51.389,0:00:51.826
诶呀

0:00:52.359,0:00:53.168
那里的大片点

0:00:53.691,0:00:54.138
哦

0:00:55.061,0:00:56.879
这里好多嘛你看

0:01:12.216,0:01:12.540
好

0:01:13.225,0:01:13.577
好

0:01:13.948,0:01:14.348
够了

0:01:14.462,0:01:14.804
可以了

0:01:17.402,0:01:17.811
诶呀

0:01:20.104,0:01:22.626
我们这里漫山遍野都是包粽子的材料

0:01:22.816,0:01:24.843
这个粽叶就这么大了

0:01:27.174,0:01:28.506
这片还好 这片

0:01:29.172,0:01:30.218
诶 这片颜色好看

0:01:30.304,0:01:30.799
嗯

0:01:31.436,0:01:31.931
走嘛

0:01:34.005,0:01:35.176
到处都是

0:01:36.765,0:01:38.496
现在我们这个粽叶就已经摘回来了

0:01:38.953,0:01:40.466
但是这个粽叶的话

0:01:40.675,0:01:42.492
摘回来不能直接用来包

0:01:42.863,0:01:44.005
大家可以看一下这个上面

0:01:44.709,0:01:45.252
油虫卵

0:01:45.280,0:01:46.508
很多虫卵嘎

0:01:46.774,0:01:51.208
这个上面有虫卵 所以我们要烧开水把这个放到开水里面去煮一下

0:01:51.674,0:01:53.929
煮完了之后再洗干净了再用来包

0:01:54.072,0:01:55.861
这样更安全嘎

0:01:55.975,0:01:58.154
通过高温的（煮）这个（虫卵）就遭了撒

0:01:58.506,0:01:59.638
就把它烫死了撒

0:01:59.895,0:02:00.704
要得 我拿得蒸锅里去煮哈

0:02:01.370,0:02:02.397
煮了再洗干净了

0:02:02.502,0:02:04.043
煮了来洗干净来包

0:02:05.318,0:02:07.231
好了这个粽叶我们已经煮好了

0:02:07.231,0:02:09.857
煮完了之后又洗干净了 现在先放一边

0:02:10.228,0:02:12.692
我切点香肠跟腊肉

0:02:13.244,0:02:16.679
这个香肠的话我们就切颗粒 切大一点的颗粒

0:02:18.106,0:02:20.104
大点的颗粒吃起要上口点

0:02:20.228,0:02:20.589
哦喔

0:02:25.404,0:02:29.838
先把它对半切这种条 然后再切成长粒

0:02:31.760,0:02:33.672
腊肉的话我们就稍微切小一点

0:02:34.034,0:02:36.156
因为这个腊肉切大了咬不动

0:02:37.916,0:02:40.218
我切成片片嘛这个嘎

0:02:40.371,0:02:40.904
可以按

0:02:45.271,0:02:46.346
切成厚片就可以

0:02:46.403,0:02:49.343
你切这么大坨包起粽子好大个

0:02:57.982,0:02:59.438
好现在我们来和这个米

0:03:00.628,0:03:02.074
调一下味简单的

0:03:03.016,0:03:06.865
我们这个米的话可以不用搞得太复杂放点酱油就行了

0:03:06.945,0:03:07.802
调个底味

0:03:10.142,0:03:14.266
大概倒个三四两酱油就可以了

0:03:14.605,0:03:17.716
然后再放一点点老抽调下这个颜色 

0:03:20.513,0:03:21.332
好 可以了

0:03:21.703,0:03:26.346
我们的香肠和腊肉都比较咸 所以就不加盐了就加这个就够了

0:03:27.364,0:03:32.549
加点酱油加点老抽有点颜色有点底味就可以了

0:03:34.662,0:03:36.993
我这个粽子啊因为做的比较少

0:03:37.107,0:03:41.550
我都是现跟前辈请教怎么包

0:03:41.550,0:03:43.577
今天就包一个最简单的四角粽

0:03:44.072,0:03:47.183
粽子有三角 有圆角 有四角

0:03:47.183,0:03:48.201
四角是最简单的

0:03:49.857,0:03:51.893
好 现在粽叶我们已经弄好了

0:03:52.293,0:03:53.349
米也弄好了

0:03:53.472,0:03:55.547
香肠腊肉也好了 我们来包一下

0:03:57.583,0:04:00.532
第一次尝试来包啊 包得不好

0:04:02.388,0:04:03.444
两头给它剪掉

0:04:04.253,0:04:08.696
然后这个粽叶背靠背给它靠起来

0:04:09.162,0:04:10.218
然后对折一下

0:04:11.018,0:04:15.280
对折过来之后这边给它这样子折一下

0:04:15.794,0:04:17.611
折起来了这边就可以打开

0:04:17.706,0:04:18.905
打开米就不会掉下去

0:04:20.418,0:04:21.998
好 现在我们放点米

0:04:23.844,0:04:24.700
放点糯米

0:04:26.888,0:04:29.324
再放点这个香肠和腊肉

0:04:29.324,0:04:30.085
再放点糯米

0:04:31.103,0:04:33.320
包小一点 反正我们这个粽叶也不大

0:04:33.853,0:04:35.432
然后这样子给它对折一下

0:04:36.308,0:04:38.820
对折的时候两边手就给它捏紧

0:04:39.648,0:04:40.266
捏一下

0:04:41.408,0:04:45.195
捏下了之后这两边给它弄下去

0:04:46.165,0:04:46.489
好 

0:04:47.012,0:04:48.924
然后再用这个线给它缠起来

0:04:50.485,0:04:51.693
从头缠到尾

0:04:53.777,0:04:56.441
好 我们这个粽子小是小了点

0:04:56.612,0:05:01.589
嗯 虽然说不是很漂亮  但是都是自己做的嘛吃起来更放心

0:05:01.979,0:05:02.816
来嘛 继续

0:05:06.336,0:05:07.821
我包的你看越来越更好看了

0:05:09.895,0:05:12.169
你越来越整的好撒 说明你做好了撒

0:05:14.900,0:05:16.432
又成一个

0:05:17.773,0:05:18.163
可以

0:05:18.629,0:05:21.189
哈哈哈

0:05:21.303,0:05:22.578
哈哈哈

0:05:22.997,0:05:24.890
哈哈哈

0:05:25.004,0:05:28.097
四伯爷的模仿好像哦 模仿还多像

0:05:29.143,0:05:30.190
包得还可以 剪了

0:05:30.742,0:05:33.644
好了 经过半个小时的包啊 他们都不包了

0:05:33.729,0:05:35.927
现在只留我跟伯娘两个人在这里

0:05:37.421,0:05:38.525
这个肉抓进去

0:05:39.505,0:05:39.800
嗯

0:05:40.409,0:05:41.284
捏住它

0:05:41.417,0:05:44.624
这个做这个白案 做这个粑粑很多学问

0:05:50.199,0:05:51.855
好 可以了现在

0:05:52.359,0:05:54.500
我就一个人慢慢包了 不等他们了

0:05:57.497,0:05:59.609
把须须剪了的

0:05:59.762,0:06:00.295
须须啊

0:06:00.846,0:06:01.141
嗯

0:06:01.179,0:06:02.255
剪不剪都可以

0:06:03.568,0:06:06.451
好了 我们这个粽子大的大小的小

0:06:07.354,0:06:10.761
总之我觉得前面包的不怎么样 后面包的还可以

0:06:11.322,0:06:12.940
大家可以看一下这个是我包的

0:06:13.701,0:06:14.433
这是我包的

0:06:15.252,0:06:16.089
这个是哪个包的哦

0:06:16.707,0:06:17.497
漆二娃包的

0:06:17.564,0:06:18.068
诶呀

0:06:19.695,0:06:21.979
好了这次我们的直接用来蒸

0:06:22.607,0:06:25.261
反正做厨子这一行嘛

0:06:25.299,0:06:29.400
白案跟红案的话 虽然说白案不怎么熟可以学着来做一下

0:06:29.714,0:06:30.456
嘎四伯爷

0:06:30.694,0:06:33.092
可以安 可以尝试哈撒

0:06:33.387,0:06:35.328
反正自己吃的没那么讲究

0:06:39.391,0:06:41.465
好 现在我们就把它放下去蒸一下

0:06:45.651,0:06:47.773
那个（线）对这那个（线）

0:06:47.773,0:06:48.430
这样子的啊

0:06:48.458,0:06:49.162
对对对

0:06:52.369,0:06:54.481
好 现在我们就要蒸3个小时

0:07:04.795,0:07:06.593
好了我们这个已经差不多了

0:07:08.601,0:07:09.305
我先关火嘛

0:07:09.334,0:07:12.911
我们这个粽子已经蒸了有三四个小时了

0:07:13.139,0:07:14.633
这个水都烧干了2次了

0:07:14.985,0:07:18.392
因为没有包得很紧所以就蒸

0:07:19.096,0:07:20.447
煮的话怕全部漏出来

0:07:21.589,0:07:22.312
哇噻

0:07:24.890,0:07:26.717
你闻哈看 都闻到酒米的那个香味了

0:07:27.259,0:07:27.754
嗯

0:07:27.935,0:07:28.620
是不

0:07:28.991,0:07:31.417
这个生蒸的这个肯定是安逸点了

0:07:33.901,0:07:36.365
诶呀 好香哦

0:07:36.964,0:07:38.363
我还选得到我包的

0:07:39.153,0:07:41.408
你包的这个 这个就是你包的

0:07:41.446,0:07:41.998
那不是咋子

0:07:42.045,0:07:43.254
没有包紧这个

0:07:45.747,0:07:47.412
 拿这个整得盘子头

0:07:48.125,0:07:49.866
看到很烫

0:07:49.933,0:07:52.274
很烫啊先吃一个小的嘛

0:07:52.407,0:07:54.395
我解开来冷一哈都

0:07:54.472,0:07:55.004
吃撒

0:07:55.052,0:07:56.051
冷一哈安

0:07:58.544,0:07:59.657
好了的 你看嘛这

0:07:59.657,0:08:01.522
好了的 蒸了这么久还没好

0:08:03.587,0:08:07.621
嗯 你看我包的有坨香肠 有坨腊肉

0:08:07.878,0:08:09.015
你硬是吃你的那个啊

0:08:09.015,0:08:09.372
嗯

0:08:09.467,0:08:12.188
他认到自己包的那个吃

0:08:13.311,0:08:13.863
嗯

0:08:16.765,0:08:17.221
可以啊

0:08:17.773,0:08:18.639
可以 好香哦

0:08:18.896,0:08:19.429
嗯

0:08:21.141,0:08:21.922
颜色还可以

0:08:22.378,0:08:22.711
可以

0:08:22.845,0:08:24.862
唯一的没整到位就是不是很糯

0:08:25.975,0:08:26.972
泡时间短了噶

0:08:26.983,0:08:28.354
哦 泡时间短了

0:08:29.096,0:08:32.226
总结一下我们这个粽子

0:08:32.588,0:08:36.374
米泡的时间不够长 下一次的话可能头一天给它泡上

0:08:38.002,0:08:40.110
然后再用来包 米没有完全发涨

0:08:40.133,0:08:41.151
所以有一点硬

0:08:43.339,0:08:44.129
熟是熟了的

0:08:45.271,0:08:46.270
这个当真的抵饿安

0:08:47.031,0:08:47.355
嗯

0:08:48.277,0:08:49.781
好了 本期视频就到这里 拜拜

0:08:51.103,0:08:52.816
快到端午节了自己做点来吃

0:08:53.073,0:08:55.157
这一次做得不够好 下一次再继续改进


```

**Comment by Hackerry** [comment]
认领

**Comment by Hackerry** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
王刚第一次尝试自己包粽子，让红案厨师做白案还需更多学习，味道不错，但米没泡够
Wang Gang tries making Zongzi for the first time. A culinary chef's attempt at making staple food.

简介
大家好，过端午了，所以决定尝试一下自己来包粽子。在这里给大家介绍一个中式厨师的概念“红白案”，一般做厨师会分为这两种。其中“红案”为各种菜肴的烹饪，包括从选材，材料加工，配菜，烹饪，摆盘等等。而“白案”以米面点为主，馒头，花卷，水饺，包子，面条等等，其中也包括粽子。理论上红白案可以互补或独立，各有所攻所长，大家肯定看得出来我就是一个彻头彻尾的“红案”厨师，所以“白案”功夫有限，还需更多的学习，努力充实自己，学无止境。最后祝大家端午节快乐！
Hello, everyone. The Dragon Boat Festival is drawing near so we tried making Zongzi. Chinese chefs usually are split into two kinds - "Hong An" (literally "red board") and "Bai An" (literally "white board"). "Hong An" chefs are responsible for preparing, processing, cooking and presenting dishes. "Bai An" chefs are skilled at cooking rice dishes and dough food such as Mantou (Chinese steamed buns), dumplings, and noodles, including Zongzi. In theory, one chef can be both or two top chefs in both areas work in complement. I'm a total "Hong An" chef not so skilled in "Bai An" work. I'll keep on learning new things. Wish you all a happy Dragon Boat Festival!

字幕
0:00:00.570,0:00:03.130
哈喽 大家好 现在快要到端午节了
Hello, everyone. It's almost the Dragon Boat Festival.

0:00:03.139,0:00:04.253
我们今天弄一点粽子
We want to try making some Zongzi

0:00:04.747,0:00:08.078
这个粽子（米）我四伯爷已经泡了两三个小时了嘎
Uncle has soaked this glutinous rice for about 2 to 3 hours

0:00:08.078,0:00:09.514
两三个小时是有的
At least 2 to 3 hours

0:00:09.514,0:00:11.919
这里是4斤糯米
Here we have 4 Jin (2kg) glutinous rice,

0:00:12.017,0:00:14.091
然后一斤这个
and 1 Jin (0.5kg)

0:00:14.196,0:00:15.518
饭米饭米
white rice.

0:00:15.737,0:00:19.724
那我们包啥子安 有蛋黄有那个香肠腊肉
What do we have for the filling? We have duck egg yolk, sausage and salted pork.

0:00:20.513,0:00:22.292
就包香肠腊肉的好吃点
I like sausage and salted pork

0:00:22.673,0:00:23.630
包香肠腊肉的啊
Sausage and salted pork?

0:00:23.634,0:00:27.854
嗯 包蛋的麻烦得很 就包那个简单点的
Yes. Egg yolk is a mess to deal with. Let's go with the easier ones.

0:00:28.782,0:00:32.521
我们这个蛋黄老人家胆固醇比较高
Egg yolk is rich in cholesterol, which is not so healthy for the senior,

0:00:32.521,0:00:33.282
所以就
so let's...

0:00:33.882,0:00:36.964
反正我四伯爷也喜欢吃肉嘛就包香肠腊肉就行了
Anyway, since uncle likes meat, we will go with sausage and salted pork.

0:00:37.630,0:00:38.848
然后现在还差个粽叶
Now we need the leaves to wrap with

0:00:39.248,0:00:40.161
走嘛 我们去摘粽叶
Let's go pick some

0:00:40.666,0:00:42.188
走嘛 就到我们背后去摘
Let's go. Just around the corner.

0:00:42.188,0:00:45.385
我那儿有我栽的笋竹的竹叶很大片一个
Those bamboo I've planted have really large leaves

0:00:45.689,0:00:46.327
好 要得
Good. That's great.

0:00:46.498,0:00:47.421
就摘点来包
Go pick some

0:00:47.507,0:00:47.840
好
OK

0:00:49.105,0:00:50.009
就是那个是不
Is it over there?

0:00:51.389,0:00:51.826
诶呀
Aiyah

0:00:52.359,0:00:53.168
那里的大片点
(Leaves) over there are larger

0:00:53.691,0:00:54.138
哦
Oh

0:00:55.061,0:00:56.879
这里好多嘛你看
Look at those many large leaves

0:01:12.216,0:01:12.540
好
Good

0:01:13.225,0:01:13.577
好
Good

0:01:13.948,0:01:14.348
够了
That's enough

0:01:14.462,0:01:14.804
可以了
Good enough

0:01:17.402,0:01:17.811
诶呀
Aiyah

0:01:20.104,0:01:22.626
我们这里漫山遍野都是包粽子的材料
We have everything we need to make Zongzi here

0:01:22.816,0:01:24.843
这个粽叶就这么大了
These leaves are not so wide

0:01:27.174,0:01:28.506
这片还好 这片
This piece is better. This one.

0:01:29.172,0:01:30.218
诶 这片颜色好看
Ei. It has a nice color.

0:01:30.304,0:01:30.799
嗯
Yes

0:01:31.436,0:01:31.931
走嘛
Let's go

0:01:34.005,0:01:35.176
到处都是
(Bamboo leaves) are everywhere

0:01:36.765,0:01:38.496
现在我们这个粽叶就已经摘回来了
Now we have the bamboo leaves

0:01:38.953,0:01:40.466
但是这个粽叶的话
But we can't

0:01:40.675,0:01:42.492
摘回来不能直接用来包
use them directly

0:01:42.863,0:01:44.005
大家可以看一下这个上面
You can see under the leaves there are

0:01:44.709,0:01:45.252
油虫卵
aphid larvae.

0:01:45.280,0:01:46.508
很多虫卵嘎
Many larvae

0:01:46.774,0:01:51.208
这个上面有虫卵 所以我们要烧开水把这个放到开水里面去煮一下
There are insect larvae. So we must boil the leaves

0:01:51.674,0:01:53.929
煮完了之后再洗干净了再用来包
and wash thoroughly before using.

0:01:54.072,0:01:55.861
这样更安全嘎
It's safer this way

0:01:55.975,0:01:58.154
通过高温的（煮）这个（虫卵）就遭了撒
(Boiling under) high temperature can kill them (larvae)

0:01:58.506,0:01:59.638
就把它烫死了撒
Can kill them

0:01:59.895,0:02:00.704
要得 我拿得蒸锅里去煮哈
Good. I'll boil them and later

0:02:01.370,0:02:02.397
煮了再洗干净了
wash thoroughly.

0:02:02.502,0:02:04.043
煮了来洗干净来包
Boil and wash

0:02:05.318,0:02:07.231
好了这个粽叶我们已经煮好了
OK. Now the leaves are boiled

0:02:07.231,0:02:09.857
煮完了之后又洗干净了 现在先放一边
and cleaned. We leave them aside for now.

0:02:10.228,0:02:12.692
我切点香肠跟腊肉
Let me prepare the sausage and salted pork

0:02:13.244,0:02:16.679
这个香肠的话我们就切颗粒 切大一点的颗粒
We can cut sausage into dice. Large dice.

0:02:18.106,0:02:20.104
大点的颗粒吃起要上口点
Larger dice are more chewy

0:02:20.228,0:02:20.589
哦喔
Yes

0:02:25.404,0:02:29.838
先把它对半切这种条 然后再切成长粒
First cut lengthwise into slim pieces and then into chunks

0:02:31.760,0:02:33.672
腊肉的话我们就稍微切小一点
We can cut salted pork into small pieces

0:02:34.034,0:02:36.156
因为这个腊肉切大了咬不动
because it's difficult to chew.

0:02:37.916,0:02:40.218
我切成片片嘛这个嘎
I'm going to cut into slices

0:02:40.371,0:02:40.904
可以按
Sure

0:02:45.271,0:02:46.346
切成厚片就可以
This thickness should be fine

0:02:46.403,0:02:49.343
你切这么大坨包起粽子好大个
We'll definitely be making large Zongzi since those pieces are so large

0:02:57.982,0:02:59.438
好现在我们来和这个米
Now we mix the two kinds of rice

0:03:00.628,0:03:02.074
调一下味简单的
and add some flavor.

0:03:03.016,0:03:06.865
我们这个米的话可以不用搞得太复杂放点酱油就行了
We keep it simple and only add some soy sauce

0:03:06.945,0:03:07.802
调个底味
to make a base flavor.

0:03:10.142,0:03:14.266
大概倒个三四两酱油就可以了
About 3 or 4 Liang (150-200g) soy sauce

0:03:14.605,0:03:17.716
然后再放一点点老抽调下这个颜色
Then a little bit of dark soy sauce to add some color

0:03:20.513,0:03:21.332
好 可以了
Good enough

0:03:21.703,0:03:26.346
我们的香肠和腊肉都比较咸 所以就不加盐了就加这个就够了
Sausage and salted pork are salty enough so we leave out the salt

0:03:27.364,0:03:32.549
加点酱油加点老抽有点颜色有点底味就可以了
These two sauces are enough for the flavor and color

0:03:34.662,0:03:36.993
我这个粽子啊因为做的比较少
I've rarely made any Zongzi,

0:03:37.107,0:03:41.550
我都是现跟前辈请教怎么包
so I just learned how to make them from experienced seniors right before this.

0:03:41.550,0:03:43.577
今天就包一个最简单的四角粽
Today we will make the easiest four-corner Zongzi

0:03:44.072,0:03:47.183
粽子有三角 有圆角 有四角
Zongzi can come with three corners, round corners or four corners

0:03:47.183,0:03:48.201
四角是最简单的
Four-corner Zongzi is the easiest to make

0:03:49.857,0:03:51.893
好 现在粽叶我们已经弄好了
Good. Now we have the bamboo leaves,

0:03:52.293,0:03:53.349
米也弄好了
rice and

0:03:53.472,0:03:55.547
香肠腊肉也好了 我们来包一下
meat ready, let's try making one.

0:03:57.583,0:04:00.532
第一次尝试来包啊 包得不好
This is my first time making Zongzi. It may not turn out good.

0:04:02.388,0:04:03.444
两头给它剪掉
Scissor both sides

0:04:04.253,0:04:08.696
然后这个粽叶背靠背给它靠起来
and attach the underside of both leaves.

0:04:09.162,0:04:10.218
然后对折一下
Then fold in half

0:04:11.018,0:04:15.280
对折过来之后这边给它这样子折一下
and seal one side by folding slightly inward.

0:04:15.794,0:04:17.611
折起来了这边就可以打开
Now we can open from the other side

0:04:17.706,0:04:18.905
打开米就不会掉下去
without rice falling through once added.

0:04:20.418,0:04:21.998
好 现在我们放点米
Good. Now we add rice.

0:04:23.844,0:04:24.700
放点糯米
Some glutinous rice,

0:04:26.888,0:04:29.324
再放点这个香肠和腊肉
some sausage and salted pork,

0:04:29.324,0:04:30.085
再放点糯米
and then more glutinous rice.

0:04:31.103,0:04:33.320
包小一点 反正我们这个粽叶也不大
We'll make a small Zongzi since the leaves are not so big

0:04:33.853,0:04:35.432
然后这样子给它对折一下
Then fold like this

0:04:36.308,0:04:38.820
对折的时候两边手就给它捏紧
while holding tight on both sides of the opening.

0:04:39.648,0:04:40.266
捏一下
Squeeze tightly

0:04:41.408,0:04:45.195
捏下了之后这两边给它弄下去
Cover the opening on both sides

0:04:46.165,0:04:46.489
好 
Nice

0:04:47.012,0:04:48.924
然后再用这个线给它缠起来
Now we wrap the string around,

0:04:50.485,0:04:51.693
从头缠到尾
from head to tail.

0:04:53.777,0:04:56.441
好 我们这个粽子小是小了点
OK. Our Zongzi is rather small

0:04:56.612,0:05:01.589
嗯 虽然说不是很漂亮  但是都是自己做的嘛吃起来更放心
and less appealing but it's safer since everything passes our hands and inspection. (...but it's the effort that matters在想这样翻，怕外国人理解不了“为什么别人做就不放心”，不过这算意译了)

0:05:01.979,0:05:02.816
来嘛 继续
Come. Let's continue.

0:05:06.336,0:05:07.821
我包的你看越来越更好看了
See? I'm becoming better at this.

0:05:09.895,0:05:12.169
你越来越整的好撒 说明你做好了撒
Better means you are trying your best

0:05:14.900,0:05:16.432
又成一个
Another one

0:05:17.773,0:05:18.163
可以
Nice

0:05:18.629,0:05:21.189
哈哈哈
Hahaha

0:05:21.303,0:05:22.578
哈哈哈
(Uncle imitating) Hahaha

0:05:22.997,0:05:24.890
哈哈哈
(Everyone) Hahaha

0:05:25.004,0:05:28.097
四伯爷的模仿好像哦 模仿还多像
That was a really impressive imitation, uncle. Really lively.

0:05:29.143,0:05:30.190
包得还可以 剪了
Nice wrapping. Cut here.

0:05:30.742,0:05:33.644
好了 经过半个小时的包啊 他们都不包了
OK. After half an hour of work, they both quit.

0:05:33.729,0:05:35.927
现在只留我跟伯娘两个人在这里
Now only aunt and I are left

0:05:37.421,0:05:38.525
这个肉抓进去
Get those meat in

0:05:39.505,0:05:39.800
嗯
En

0:05:40.409,0:05:41.284
捏住它
Squeeze it

0:05:41.417,0:05:44.624
这个做这个白案 做这个粑粑很多学问
(Uncle from afar) To be a "Bai An" chef and good at making dough food is not easy

0:05:50.199,0:05:51.855
好 可以了现在
Good. Good enough.

0:05:52.359,0:05:54.500
我就一个人慢慢包了 不等他们了
I'll keep on going. There's no need to wait for them.

0:05:57.497,0:05:59.609
把须须剪了的
You should cut those dangling strings

0:05:59.762,0:06:00.295
须须啊
Those strings?

0:06:00.846,0:06:01.141
嗯
En

0:06:01.179,0:06:02.255
剪不剪都可以
Either way is fine

0:06:03.568,0:06:06.451
好了 我们这个粽子大的大小的小
OK. Now we have various size Zongzi

0:06:07.354,0:06:10.761
总之我觉得前面包的不怎么样 后面包的还可以
I think the last few I made was much better than the first ones

0:06:11.322,0:06:12.940
大家可以看一下这个是我包的
You can see this one is from me

0:06:13.701,0:06:14.433
这是我包的
I made this

0:06:15.252,0:06:16.089
这个是哪个包的哦
Who made this one?

0:06:16.707,0:06:17.497
漆二娃包的
Qi Erwa

0:06:17.564,0:06:18.068
诶呀
Aiyah

0:06:19.695,0:06:21.979
好了这次我们的直接用来蒸
Good. Now we steam.

0:06:22.607,0:06:25.261
反正做厨子这一行嘛
Although chef has two kinds,

0:06:25.299,0:06:29.400
白案跟红案的话 虽然说白案不怎么熟可以学着来做一下
"Bai An" and "Hong An", one can still try learning and doing things from the other side.

0:06:29.714,0:06:30.456
嘎四伯爷
Right, uncle?

0:06:30.694,0:06:33.092
可以安 可以尝试哈撒
Indeed. Try doing unfamiliar things.

0:06:33.387,0:06:35.328
反正自己吃的没那么讲究
They are not for sale. It's fine they don't look as good.

0:06:39.391,0:06:41.465
好 现在我们就把它放下去蒸一下
OK. Now we steam.

0:06:45.651,0:06:47.773
那个（线）对这那个（线）
Align (the two seams)

0:06:47.773,0:06:48.430
这样子的啊
Like this?

0:06:48.458,0:06:49.162
对对对
Yes. Good.

0:06:52.369,0:06:54.481
好 现在我们就要蒸3个小时
OK. Now we wait 3 hours.

0:07:04.795,0:07:06.593
好了我们这个已经差不多了
OK. Now it's good enough

0:07:08.601,0:07:09.305
我先关火嘛
Let me cut the gas first

0:07:09.334,0:07:12.911
我们这个粽子已经蒸了有三四个小时了
It has been steamed for 3 to 4 hours

0:07:13.139,0:07:14.633
这个水都烧干了2次了
We've added water twice after it dried out

0:07:14.985,0:07:18.392
因为没有包得很紧所以就蒸
We choose to steam because the wrappings are not tight,

0:07:19.096,0:07:20.447
煮的话怕全部漏出来
and fillings might come out if we chose to boil.

0:07:21.589,0:07:22.312
哇噻
Wow!

0:07:24.890,0:07:26.717
你闻哈看 都闻到酒米的那个香味了
Have a smell. The aroma of glutinous rice.

0:07:27.259,0:07:27.754
嗯
En

0:07:27.935,0:07:28.620
是不
Smelt it?

0:07:28.991,0:07:31.417
这个生蒸的这个肯定是安逸点了
Steamed (Zongzi) is definitely better

0:07:33.901,0:07:36.365
诶呀 好香哦
Aiyah. Smells so good.

0:07:36.964,0:07:38.363
我还选得到我包的
I can see which one I made

0:07:39.153,0:07:41.408
你包的这个 这个就是你包的
You made this one?

0:07:41.446,0:07:41.998
那不是咋子
Of course

0:07:42.045,0:07:43.254
没有包紧这个
Not very tightly wrapped

0:07:45.747,0:07:47.412
 拿这个整得盘子头
Put this in a pan

0:07:48.125,0:07:49.866
看到很烫
Careful. Very hot.

0:07:49.933,0:07:52.274
很烫啊先吃一个小的嘛
Hot? Choose smaller ones then.

0:07:52.407,0:07:54.395
我解开来冷一哈都
I'll open it up and let it cool

0:07:54.472,0:07:55.004
吃撒
Go on.

0:07:55.052,0:07:56.051
冷一哈安
Let it cool first

0:07:58.544,0:07:59.657
好了的 你看嘛这
They are well cooked. Here, see?

0:07:59.657,0:08:01.522
好了的 蒸了这么久还没好
Of course. They've been steamed for so long.

0:08:03.587,0:08:07.621
嗯 你看我包的有坨香肠 有坨腊肉
En. You see the one I made has one piece of sausage and one piece of salted pork.

0:08:07.878,0:08:09.015
你硬是吃你的那个啊
You are eating the one you made? (这句感觉意思有点把捏不到位)

0:08:09.015,0:08:09.372
嗯
En

0:08:09.467,0:08:12.188
他认到自己包的那个吃
He recognizes that one

0:08:13.311,0:08:13.863
嗯
En

0:08:16.765,0:08:17.221
可以啊
Good?

0:08:17.773,0:08:18.639
可以 好香哦
Nice. Very delicious.

0:08:18.896,0:08:19.429
嗯
En

0:08:21.141,0:08:21.922
颜色还可以
The color is just right

0:08:22.378,0:08:22.711
可以
Good

0:08:22.845,0:08:24.862
唯一的没整到位就是不是很糯
The only thing is the rice isn't soft enough

0:08:25.975,0:08:26.972
泡时间短了噶
It need more time soaking

0:08:26.983,0:08:28.354
哦 泡时间短了
Oh. Longer time soaking.

0:08:29.096,0:08:32.226
总结一下我们这个粽子
A summary about our Zongzi:

0:08:32.588,0:08:36.374
米泡的时间不够长 下一次的话可能头一天给它泡上
Rice isn't well-soaked. Next time should start soaking one day ahead

0:08:38.002,0:08:40.110
然后再用来包 米没有完全发涨
before using. Rice isn't bloating, so

0:08:40.133,0:08:41.151
所以有一点硬
it's a little bit hard,

0:08:43.339,0:08:44.129
熟是熟了的
although well-cooked.

0:08:45.271,0:08:46.270
这个当真的抵饿安
This is really satisfying

0:08:47.031,0:08:47.355
嗯
En

0:08:48.277,0:08:49.781
好了 本期视频就到这里 拜拜
OK. That's all for this episode. Bye bye.

0:08:51.103,0:08:52.816
快到端午节了自己做点来吃
You can cook some for the upcoming Dragon Boat Festival

0:08:53.073,0:08:55.157
这一次做得不够好 下一次再继续改进
Next time can only improve if you fail the first time
