### ISSUE TITLE
【美食作家王刚】给长辈送粽子 - https://youtu.be/PVTjEsgc3HM

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1190]
**视频链接**：https://youtu.be/PVTjEsgc3HM

视频时长8:13，预计发布时间为北京时间6月22日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
给家里长辈们去送端午节礼物，传统习俗不能忘，祝大家端午节安康！

简介
大家好，端午节就快到了，去拜访一下家里的长辈们。自己包的粽子卖相不是很好有点送不出去手，还是定一些专业包好了的，接下来会去杭州出差，可能会有视频更新不及时的情况，请大家见谅。

字幕
0:00:01.400,0:00:02.025
哈喽大家好

0:00:02.281,0:00:05.529
过两天就快要到端午节了

0:00:05.946,0:00:09.369
今天跟我四伯爷还有我的亲戚送点这个粽子

0:00:09.773,0:00:12.461
这个是我自己定的粽子

0:00:12.816,0:00:14.648
就是这种礼盒装的一盒是6个

0:00:15.076,0:00:16.151
拿4份去送

0:00:16.640,0:00:18.362
然后还有一箱这个凉糕

0:00:18.961,0:00:21.698
一箱凉糕是30多盒就是1件

0:00:25.436,0:00:30.164
然后我妈买了一些土鸡蛋给我外婆拿去

0:00:31.423,0:00:32.131
这个是啥子哦

0:00:32.999,0:00:33.622
这是李子嘎

0:00:33.622,0:00:33.879
嗯

0:00:34.575,0:00:35.809
还摘了一些李子

0:00:37.031,0:00:38.216
还有一些香蕉

0:00:41.050,0:00:42.907
今天休息一下去看我外婆

0:00:45.668,0:00:46.206
自驾游

0:00:46.548,0:00:47.183
走嘛 上车

0:00:51.301,0:00:52.547
空调你不要指到吹撒

0:00:52.559,0:00:53.756
指到吹一会儿你头要痛

0:01:01.185,0:01:02.431
诶呀 都撒尿了

0:01:05.363,0:01:05.754
别动

0:01:07.416,0:01:09.248
脖子上毛都磨掉了

0:01:11.582,0:01:11.997
别动

0:01:19.071,0:01:19.584
好乖哦

0:01:23.372,0:01:24.740
这狗特别的热情

0:01:27.183,0:01:29.456
这狗的年纪比我儿子还大一个月

0:01:31.130,0:01:32.266
比你的孙子都还大一个月

0:01:32.913,0:01:34.062
现在有半岁了

0:01:36.249,0:01:36.554
四伯爷

0:01:37.788,0:01:42.064
又遭了哦可能又要封场（赶集）了哦

0:01:46.377,0:01:47.330
我给你拿了口罩来

0:01:47.733,0:01:49.602
今天我在街上听到说

0:01:50.885,0:01:56.933
他们拿回来的冻肉都不准卖了

0:01:58.411,0:01:58.814
这街上

0:02:02.553,0:02:05.436
口罩现在也比较难买只拿到10个给你

0:02:05.607,0:02:06.560
要得

0:02:06.817,0:02:09.175
你赶场的时候人多你就戴起

0:02:09.248,0:02:10.164
好嘛 好

0:02:10.372,0:02:11.875
反正你赶场没得问题的

0:02:11.924,0:02:13.036
给你拿一盒粽子来

0:02:13.414,0:02:15.394
哎呀

0:02:15.858,0:02:16.750
还有凉糕呢

0:02:17.312,0:02:18.876
又拿粽子来

0:02:23.579,0:02:24.984
拿这么多凉糕来

0:02:25.043,0:02:27.181
放在冰箱里冻了再吃

0:02:27.413,0:02:28.488
放在保鲜室都嘛

0:02:28.537,0:02:29.319
嗯 保鲜室

0:02:30.736,0:02:31.506
我帮你吃一盒嘛

0:02:35.660,0:02:36.222
伯娘呢

0:02:36.600,0:02:37.407
吃凉糕伯娘

0:02:40.278,0:02:43.906
一会儿我还要给舅婆他们提一些去

0:02:44.786,0:02:45.556
她在屋头撒

0:02:46.069,0:02:47.498
在屋头 还是带这些东西啊

0:02:47.669,0:02:48.244
嗯

0:02:48.427,0:02:50.797
给她拿粽子跟凉糕

0:02:51.628,0:02:52.825
明天我要出去学习

0:02:53.570,0:02:55.244
走哪里嘛 走杭州啊

0:02:55.574,0:02:55.928
嗯

0:02:56.356,0:02:58.995
出去还是把口罩戴好

0:02:59.349,0:03:00.180
必须的撒

0:03:01.096,0:03:02.562
要得四伯爷你慢慢吃

0:03:02.917,0:03:04.688
我送下一家 我走了哈

0:03:04.908,0:03:05.336
好

0:03:05.959,0:03:07.902
狗儿就不去了撒 你要跟着去啊

0:03:08.464,0:03:09.062
等它去啊

0:03:09.294,0:03:09.966
那走嘛

0:03:22.917,0:03:23.442
舅公

0:03:28.073,0:03:29.343
幺舅你还在宰鱼啊

0:03:31.958,0:03:35.965
给你拿点粽子还有凉糕

0:03:36.405,0:03:37.627
你在这边吃饭噶

0:03:38.726,0:03:40.876
不坐 我们一会儿就要走

0:03:41.817,0:03:44.346
坐会儿撒 坐会儿多

0:03:44.395,0:03:45.458
吃西瓜

0:03:45.629,0:03:46.521
不坐了

0:03:47.694,0:03:50.150
你拿西瓜来切哈我去宰完了来

0:03:50.394,0:03:52.227
我舅公他们是养鱼的

0:03:52.911,0:03:55.269
专门在这里喂鱼你看这里全是鱼饲料

0:03:56.649,0:03:58.971
他多的时候仓库里面

0:03:59.423,0:04:00.644
几十吨的这个鱼饲料

0:04:00.693,0:04:02.149
他一买都是买几十吨

0:04:02.428,0:04:04.505
这里几口鱼塘全是他们的

0:04:05.201,0:04:08.280
现在鲢鱼还小要给它宰一下

0:04:08.635,0:04:10.821
你多久都没下来吃鱼了你不下来吃鱼了啊

0:04:11.982,0:04:12.508
下次嘛

0:04:14.096,0:04:14.499
下次

0:04:15.928,0:04:17.834
要得我就先回去了嘛我还要看外婆

0:04:19.471,0:04:20.388
舅婆我就先走了哦

0:04:20.400,0:04:21.548
你外婆现在在哪里哦

0:04:21.744,0:04:22.758
在我舅舅那里

0:04:24.713,0:04:25.654
我去看哈我外婆

0:04:26.106,0:04:27.462
这块（西瓜）给娃娃带回去嘛

0:04:27.572,0:04:28.097
不拿

0:04:29.502,0:04:33.534
这个是老家种的嘛你再买得多都没有这个好撒

0:04:34.853,0:04:35.501
拿去

0:04:35.660,0:04:36.380
我们走了舅婆

0:04:36.710,0:04:37.419
真的不拿

0:04:46.851,0:04:48.317
好啦 现在到我外婆家了

0:04:48.696,0:04:49.331
提点粽子

0:04:49.759,0:04:53.497
我外婆虽然牙口不好吃这个粽子还是吃得了的

0:04:53.570,0:04:55.293
然后拿了点凉糕

0:04:55.586,0:04:56.552
还有鸡蛋

0:04:57.822,0:04:59.093
青菜跟西瓜

0:05:04.554,0:05:05.079
外婆

0:05:07.547,0:05:08.793
我给你拿点粽子

0:05:09.209,0:05:12.336
这个凉糕我知道你牙齿不好给你拿了几盒凉糕

0:05:15.733,0:05:19.704
我头发都没梳钢夹也没扎你给我照的相像什么样啊

0:05:20.815,0:05:22.844
人家都说你长得很漂亮

0:05:23.845,0:05:24.908
我还漂亮啊

0:05:24.945,0:05:25.287
嗯

0:05:25.519,0:05:27.046
老都老了还漂亮

0:05:29.380,0:05:31.298
不老啊 你心态不老都嘛

0:05:31.836,0:05:34.597
人老心不老花有几样红

0:05:34.865,0:05:35.562
哦对头

0:05:35.647,0:05:36.625
哈哈哈

0:05:38.225,0:05:39.936
买些这些东西来

0:05:39.985,0:05:43.687
不是买的这个你外孙自己做的

0:05:46.289,0:05:48.391
这是我们厂里自己做的不是买的

0:05:48.586,0:05:50.357
在外面都是5块钱1盒

0:05:50.394,0:05:52.043
我们这个才卖3块钱1盒

0:05:52.288,0:05:53.289
里面有糖啊

0:05:53.473,0:05:54.548
一会儿我给你放嘛

0:06:01.438,0:06:02.966
你钢夹呢拿来别到

0:06:03.381,0:06:05.495
在屋里你去给我拿嘛

0:06:07.217,0:06:09.710
以前我都弄这些来卖过

0:06:10.467,0:06:12.691
我都卖过这起的我自己弄

0:06:13.216,0:06:16.038
自己拿米来泡起自己磨的

0:06:17.211,0:06:18.079
我给你压得来不哦

0:06:25.837,0:06:26.753
吃嘛 吃凉糕

0:06:27.755,0:06:30.638
人家要笑我 我不吃

0:06:30.724,0:06:32.165
没得人笑你的

0:06:32.569,0:06:34.120
你看到他就想笑你啊

0:06:35.818,0:06:38.470
我这么脏一个人照起像什么嘛

0:06:38.506,0:06:40.339
哪里嘛大家都说你长得很美

0:06:41.316,0:06:42.208
我还美啊

0:06:42.978,0:06:44.187
以前是个美女

0:06:48.500,0:06:49.954
你年轻的时候是个大美女

0:06:50.113,0:06:51.188
都晓得

0:06:51.909,0:06:54.475
难怪以前你外公那么稀奇我哦

0:06:59.667,0:07:00.999
在我脸上摸一把

0:07:01.414,0:07:02.868
我说你摸我做什么

0:07:04.029,0:07:06.594
她说我打了粉的结果没得

0:07:07.682,0:07:09.820
难怪得你二哥那么爱你哦

0:07:09.844,0:07:11.738
硬是粉白粉白的

0:07:15.012,0:07:17.578
外婆你就在屋头你自己整来吃

0:07:17.614,0:07:19.142
（粽子）蒸一哈就可以吃了

0:07:19.447,0:07:20.412
这个打开也可以吃

0:07:20.424,0:07:21.805
这个一会儿放在冰箱里面

0:07:22.245,0:07:23.027
冻哈更好吃

0:07:23.051,0:07:23.821
放在冰箱里就是

0:07:24.481,0:07:25.861
然后我们下次再来看你哈

0:07:26.057,0:07:28.574
西瓜你口干了就拿来吃

0:07:28.598,0:07:29.869
鸡蛋也可以煮

0:07:30.198,0:07:32.862
要得外婆我们就先回去了

0:07:33.057,0:07:35.024
要得 麻烦了你们哦

0:07:35.330,0:07:37.895
外婆你说这些咋子 我都是你带大的

0:07:37.895,0:07:40.730
给我拿这么多东西来我又要吃好久嘛

0:07:40.901,0:07:41.732
慢慢吃

0:07:42.880,0:07:43.662
好我们先走了

0:07:44.310,0:07:45.397
不送不送

0:07:46.411,0:07:47.071
你坐到就是

0:07:48.415,0:07:49.698
我都要出去耍了

0:07:50.443,0:07:50.773
要得

0:07:54.707,0:07:56.527
晓得嘛 打会儿麻将嘛

0:07:57.749,0:07:59.410
下次过端午早点过来陪你打麻将

0:07:59.410,0:08:00.620
我外婆特别喜欢打麻将

0:08:00.864,0:08:02.110
过端午就陪你打麻将

0:08:02.844,0:08:04.126
要得 你们慢慢走

0:08:04.187,0:08:04.920
好 拜拜

0:08:05.507,0:08:06.863
要得你回去坐到嘛

0:08:08.134,0:08:09.539
你们先走嘛

```

**Comment by Petitcolza** [comment]
认领

**Comment by Petitcolza** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
给家里长辈们去送端午节礼物，传统习俗不能忘，祝大家端午节安康！
Visit and give gifts of Dragon Boat Festival to our elders. Don’t forget traditional customs. Wish everyone have a happiness fete.
简介
Intro
大家好，端午节就快到了，去拜访一下家里的长辈们。自己包的粽子卖相不是很好有点送不出去手，还是定一些专业包好了的，接下来会去杭州出差，可能会有视频更新不及时的情况，请大家见谅。
Hello. Dragon Boat Festival is coming. We are going to visit our elders. It’s not good to give the zongzis that I made are not look perfect. I ordered some specialized and well-packed zongzis for them. Over next days, I will have a business trip in Hangzhou. I might can’t update my video on time. Hope everyone could excuse me.
字幕
0:00:01.400,0:00:02.025
哈喽大家好
Hello! Everyone.
0:00:02.281,0:00:05.529
过两天就快要到端午节了
The Dragon Boat Festival is coming in the next couple of days.
0:00:05.946,0:00:09.369
今天跟我四伯爷还有我的亲戚送点这个粽子
I will give the zongzis to my uncle and my relatives.
0:00:09.773,0:00:12.461
这个是我自己定的粽子
They are I ordered.
0:00:12.816,0:00:14.648
就是这种礼盒装的一盒是6个
There are 6 zongzis packed in a gift box.
0:00:15.076,0:00:16.151
拿4份去送
I will give away 4 of them.
0:00:16.640,0:00:18.362
然后还有一箱这个凉糕
There is a case of lianggaos.
0:00:18.961,0:00:21.698
一箱凉糕是30多盒就是1件
More than 30 boxes in one case.
0:00:25.436,0:00:30.164
然后我妈买了一些土鸡蛋给我外婆拿去
And my mother bought some free-range eggs for my grandma.
0:00:31.423,0:00:32.131
这个是啥子哦
What is it?	
0:00:32.999,0:00:33.622
这是李子嘎
These are plums.
0:00:33.622,0:00:33.879
嗯
Ok.
0:00:34.575,0:00:35.809
还摘了一些李子
And we picked some plums.
0:00:37.031,0:00:38.216
还有一些香蕉
Some bananas then.
0:00:41.050,0:00:42.907
今天休息一下去看我外婆
Take today off to visit my grandma.
0:00:45.668,0:00:46.206
自驾游
A road trip.
0:00:46.548,0:00:47.183
走嘛 上车
Let’s go. Get in.
0:00:51.301,0:00:52.547
空调你不要指到吹撒
Don’t face to the wind of air conditioning.
0:00:52.559,0:00:53.756
指到吹一会儿你头要痛
Or you will feel headache.
0:01:01.185,0:01:02.431
诶呀 都撒尿了
It peeing.
0:01:05.363,0:01:05.754
别动
Stay!
0:01:07.416,0:01:09.248
脖子上毛都磨掉了
The hair of neck worn off.
0:01:11.582,0:01:11.997
别动
Stay!
0:01:19.071,0:01:19.584
好乖哦
How clever!
0:01:23.372,0:01:24.740
这狗特别的热情
It’s very passionate.
0:01:27.183,0:01:29.456
这狗的年纪比我儿子还大一个月
It’s one month older than my son.
0:01:31.130,0:01:32.266
比你的孙子都还大一个月
One month older than your grandson.
0:01:32.913,0:01:34.062
现在有半岁了
It’s 6 months.
0:01:36.249,0:01:36.554
四伯爷
Uncle.
0:01:37.788,0:01:42.064
又遭了哦可能又要封场（赶集）了哦
Have to go to the market again.
0:01:46.377,0:01:47.330
我给你拿了口罩来
I bring you some masks.
0:01:47.733,0:01:49.602
今天我在街上听到说
I heard from the street
0:01:50.885,0:01:56.933
他们拿回来的冻肉都不准卖了
that frozen meat isn’t allowed to sell.
0:01:58.411,0:01:58.814
这街上
On the street.
0:02:02.553,0:02:05.436
口罩现在也比较难买只拿到10个给你
I only bring you 10 masks because it’s hard to buy them now.
0:02:05.607,0:02:06.560
要得
Ok.
0:02:06.817,0:02:09.175
你赶场的时候人多你就戴起
You use it when people crowed around in the market.
0:02:09.248,0:02:10.164
好嘛 好
Ok.
0:02:10.372,0:02:11.875
反正你赶场没得问题的
No problem you go to the market.
0:02:11.924,0:02:13.036
给你拿一盒粽子来
A box of zongzis for you.
0:02:13.414,0:02:15.394
哎呀
Aw.
0:02:15.858,0:02:16.750
还有凉糕呢
And some lianggaos.
0:02:17.312,0:02:18.876
又拿粽子来
You bring zongzis again.
0:02:23.579,0:02:24.984
拿这么多凉糕来
And a lot of lianggaos.
0:02:25.043,0:02:27.181
放在冰箱里冻了再吃
Eat them after cool them in the fridge.
0:02:27.413,0:02:28.488
放在保鲜室都嘛
Put in refrigerator compartment.
0:02:28.537,0:02:29.319
嗯 保鲜室
Yes. Refrigerator compartment.
0:02:30.736,0:02:31.506
我帮你吃一盒嘛
I will help you to eat one.
0:02:35.660,0:02:36.222
伯娘呢
Where is aunt?
0:02:36.600,0:02:37.407
吃凉糕伯娘
Aunt, have some lianggaos.
0:02:40.278,0:02:43.906
一会儿我还要给舅婆他们提一些去
Later，I’m going to send some to the aunt(The sister of Wanggang’s mother).
0:02:44.786,0:02:45.556
她在屋头撒
She is in the house?
0:02:46.069,0:02:47.498
在屋头 还是带这些东西啊
In the house. Bring same stuff as these? 
0:02:47.669,0:02:48.244
嗯
Yes.
0:02:48.427,0:02:50.797
给她拿粽子跟凉糕
Bring some zongzis and lianggaos.
0:02:51.628,0:02:52.825
明天我要出去学习
I will go to study tomorrow.
0:02:53.570,0:02:55.244
走哪里嘛 走杭州啊
Where? Hangzhou?
0:02:55.574,0:02:55.928
嗯
Yes.
0:02:56.356,0:02:58.995
出去还是把口罩戴好
Well wearing a mask when you go out.
0:02:59.349,0:03:00.180
必须的撒
I must.
0:03:01.096,0:03:02.562
要得四伯爷你慢慢吃
Take your time to eat. Uncle.
0:03:02.917,0:03:04.688
我送下一家 我走了哈
I’m leaving for send the next.
0:03:04.908,0:03:05.336
好
Ok.
0:03:05.959,0:03:07.902
狗儿就不去了撒 你要跟着去啊
Doggie, you stay. You want to go with me?
0:03:08.464,0:03:09.062
等它去啊
Let’s go.
0:03:09.294,0:03:09.966
那走嘛
Go.
0:03:22.917,0:03:23.442
舅公
Uncle.
0:03:28.073,0:03:29.343
幺舅你还在宰鱼啊
You are killing fish.
0:03:31.958,0:03:35.965
给你拿点粽子还有凉糕
Give you some zongzis and lianggaos.
0:03:36.405,0:03:37.627
你在这边吃饭噶
You stay and have meal with us.
0:03:38.726,0:03:40.876
不坐 我们一会儿就要走
We don’t stay. We will leave later.
0:03:41.817,0:03:44.346
坐会儿撒 坐会儿多
Have a seat and stay for a while.
0:03:44.395,0:03:45.458
吃西瓜
Have some watermelon.
0:03:45.629,0:03:46.521
不坐了
No need to sit.
0:03:47.694,0:03:50.150
你拿西瓜来切哈我去宰完了来
You bring some watermelon and I will come back after I finish the job.
0:03:50.394,0:03:52.227
我舅公他们是养鱼的
My uncle and aunt are fish farmers.
0:03:52.911,0:03:55.269
专门在这里喂鱼你看这里全是鱼饲料
All of these are fodder specialized for fish.
0:03:56.649,0:03:58.971
他多的时候仓库里面
Sometime there are 
0:03:59.423,0:04:00.644
几十吨的这个鱼饲料
Over ten tons fish fodder in the storage.
0:04:00.693,0:04:02.149
他一买都是买几十吨
He buys more than ten tons every time.
0:04:02.428,0:04:04.505
这里几口鱼塘全是他们的
They own several fish ponds.
0:04:05.201,0:04:08.280
现在鲢鱼还小要给它宰一下
The silver carp is small. Have to kill.
0:04:08.635,0:04:10.821
你多久都没下来吃鱼了你不下来吃鱼了啊
How long time you didn’t come to eat fish?
0:04:11.982,0:04:12.508
下次嘛
Next time.
0:04:14.096,0:04:14.499
下次
Next.
0:04:15.928,0:04:17.834
要得我就先回去了嘛我还要看外婆
I’m going. I have to visit my grandma.
0:04:19.471,0:04:20.388
舅婆我就先走了哦
Aunt, I’m leaving.
0:04:20.400,0:04:21.548
你外婆现在在哪里哦
Where is your grandmother live?
0:04:21.744,0:04:22.758
在我舅舅那里
My uncle’s (the brother of Wanggang’s mother) home.
0:04:24.713,0:04:25.654
我去看哈我外婆
I’m going to see my grandma.
0:04:26.106,0:04:27.462
这块（西瓜）给娃娃带回去嘛
Take this to the kid.
0:04:27.572,0:04:28.097
不拿
No.
0:04:29.502,0:04:33.534
这个是老家种的嘛你再买得多都没有这个好撒
This is what we grew. It’s better than what you buy.
0:04:34.853,0:04:35.501
拿去
Take it.
0:04:35.660,0:04:36.380
我们走了舅婆
Aunt, we are off.
0:04:36.710,0:04:37.419
真的不拿
No need.
0:04:46.851,0:04:48.317
好啦 现在到我外婆家了
Ok. We are arriving at my grandma’s home.
0:04:48.696,0:04:49.331
提点粽子
Bring some zongzis.
0:04:49.759,0:04:53.497
我外婆虽然牙口不好吃这个粽子还是吃得了的
Although she had bad teeth, she can eat zongzi.
0:04:53.570,0:04:55.293
然后拿了点凉糕
And then bring some lianggaos.
0:04:55.586,0:04:56.552
还有鸡蛋
And eggs.
0:04:57.822,0:04:59.093
青菜跟西瓜
Green vegetable and watermelon.
0:05:04.554,0:05:05.079
外婆
Grandma.
0:05:07.547,0:05:08.793
我给你拿点粽子
I bring you some zongzis.
0:05:09.209,0:05:12.336
这个凉糕我知道你牙齿不好给你拿了几盒凉糕
This is lianggao. I know you had bad teeth.
0:05:15.733,0:05:19.704
我头发都没梳钢夹也没扎你给我照的相像什么样啊
My hair hasn’t been brushed and hasn’t be tied up by hairpin. It doesn’t look good on the camera.
0:05:20.815,0:05:22.844
人家都说你长得很漂亮
People said you are beautiful.
0:05:23.845,0:05:24.908
我还漂亮啊
I’m beautiful?
0:05:24.945,0:05:25.287
嗯
Yes.
0:05:25.519,0:05:27.046
老都老了还漂亮
Too old to be beautiful.
0:05:29.380,0:05:31.298
不老啊 你心态不老都嘛
Not old. Your mind attitude is young.
0:05:31.836,0:05:34.597
人老心不老花有几样红
Old but keep young attitude in mind just like beautiful flowers.
0:05:34.865,0:05:35.562
哦对头
Yes!
0:05:35.647,0:05:36.625
哈哈哈
Hahaha.
0:05:38.225,0:05:39.936
买些这些东西来
Bought these things.
0:05:39.985,0:05:43.687
不是买的这个你外孙自己做的
It’s made by your grandson. Not bought.
0:05:46.289,0:05:48.391
这是我们厂里自己做的不是买的
It’s made by our food factory. Not bought.
0:05:48.586,0:05:50.357
在外面都是5块钱1盒
It costs 5 yuan par box.
0:05:50.394,0:05:52.043
我们这个才卖3块钱1盒
Ours, 3 yuan par box.
0:05:52.288,0:05:53.289
里面有糖啊
Is there some sugar inside?
0:05:53.473,0:05:54.548
一会儿我给你放嘛
I will put some in for you later.
0:06:01.438,0:06:02.966
你钢夹呢拿来别到
Where is your hairpin? Put it on.
0:06:03.381,0:06:05.495
在屋里你去给我拿嘛
In the room, you go bring it.
0:06:07.217,0:06:09.710
以前我都弄这些来卖过
I sold them before.
0:06:10.467,0:06:12.691
我都卖过这起的我自己弄
I sold them that I made.
0:06:13.216,0:06:16.038
自己拿米来泡起自己磨的
I soaked and grinded rice by myself.
0:06:17.211,0:06:18.079
我给你压得来不哦
I put it on for you.
0:06:25.837,0:06:26.753
吃嘛 吃凉糕
Come on. Have it.
0:06:27.755,0:06:30.638
人家要笑我 我不吃
No. People will laugh at me. 
0:06:30.724,0:06:32.165
没得人笑你的
Nobody laughs at you.
0:06:32.569,0:06:34.120
你看到他就想笑你啊
You saw he wanted to laugh at you?
0:06:35.818,0:06:38.470
我这么脏一个人照起像什么嘛
I’m in a mess. What is for filming?
0:06:38.506,0:06:40.339
哪里嘛大家都说你长得很美
People said you are beautiful.
0:06:41.316,0:06:42.208
我还美啊
I’m beautiful!?
0:06:42.978,0:06:44.187
以前是个美女
You were a beauty.
0:06:48.500,0:06:49.954
你年轻的时候是个大美女
When you young, you were a gorgeous beautiful woman.
0:06:50.113,0:06:51.188
都晓得
Everyone knew.
0:06:51.909,0:06:54.475
难怪以前你外公那么稀奇我哦
No wonder your grandfather loved me so much before.
0:06:59.667,0:07:00.999
在我脸上摸一把
（One of my friends）Touched my face.
0:07:01.414,0:07:02.868
我说你摸我做什么
I said what is that for?
0:07:04.029,0:07:06.594
她说我打了粉的结果没得
She said she want to see if I used face powder or not. And I didn’t.
0:07:07.682,0:07:09.820
难怪得你二哥那么爱你哦
“No wander your husband loves you so much.”
0:07:09.844,0:07:11.738
硬是粉白粉白的
My skin was pink and bright.
0:07:15.012,0:07:17.578
外婆你就在屋头你自己整来吃
Grandma, you could cook it(zongzi) by yourself.
0:07:17.614,0:07:19.142
（粽子）蒸一哈就可以吃了
Steam it before eat.
0:07:19.447,0:07:20.412
这个打开也可以吃
This one， open it and you could eat.
0:07:20.424,0:07:21.805
这个一会儿放在冰箱里面
Put them in fridge later.
0:07:22.245,0:07:23.027
冻哈更好吃
They are taste better.
0:07:23.051,0:07:23.821
放在冰箱里就是
Put them in fridge.
0:07:24.481,0:07:25.861
然后我们下次再来看你哈
We will see you next time.
0:07:26.057,0:07:28.574
西瓜你口干了就拿来吃
When you thirsty you could have some watermelon. 
0:07:28.598,0:07:29.869
鸡蛋也可以煮
The eggs, you could boil.
0:07:30.198,0:07:32.862
要得外婆我们就先回去了
Grandma, we are leaving.
0:07:33.057,0:07:35.024
要得 麻烦了你们哦
I troubled you.
0:07:35.330,0:07:37.895
外婆你说这些咋子 我都是你带大的
Don’t say that. You have taken care of me during my whole childhood.
0:07:37.895,0:07:40.730
给我拿这么多东西来我又要吃好久嘛
I will eat a long time for these things. 
0:07:40.901,0:07:41.732
慢慢吃
Take your time.
0:07:42.880,0:07:43.662
好我们先走了
We are off.
0:07:44.310,0:07:45.397
不送不送
Don’t have to see us off.
0:07:46.411,0:07:47.071
你坐到就是
Just sit.
0:07:48.415,0:07:49.698
我都要出去耍了
I’m about to go outside.
0:07:50.443,0:07:50.773
要得
Ok.
0:07:54.707,0:07:56.527
晓得嘛 打会儿麻将嘛
I know. Play mahjong for a while.
0:07:57.749,0:07:59.410
下次过端午早点过来陪你打麻将
Next Dragon Boat Festival, we will be here earlier to accompany you playing mahjong.
0:07:59.410,0:08:00.620
我外婆特别喜欢打麻将
My grandma likes playing mahjong very much.
0:08:00.864,0:08:02.110
过端午就陪你打麻将
Play mahjong with you on Dragon Boat Festival.
0:08:02.844,0:08:04.126
要得 你们慢慢走
Good. Take care.
0:08:04.187,0:08:04.920
好 拜拜
Bye bye.
0:08:05.507,0:08:06.863
要得你回去坐到嘛
You go back to sit.
0:08:08.134,0:08:09.539
你们先走嘛
You go first.
