### ISSUE TITLE
[雪鱼] 西安猪蹄 - https://youtu.be/QWqEcCYwOAo

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#1200]
**视频链接**：<https://youtu.be/QWqEcCYwOAo>
# 请翻译以下全部内容

``

字幕
1
00:00:01,920 --> 00:00:07,040
陕西·西安

2
00:00:23,560 --> 00:00:27,200
不是 4点开门吗   是他家吗

3
00:00:32,200 --> 00:00:34,400
看来不仅是我们要找这份猪蹄

4
00:00:34,400 --> 00:00:37,440
很多人都会早来 等这份猪蹄的

5
00:00:37,440 --> 00:00:39,560
因为比平时要晚开门

6
00:00:39,560 --> 00:00:43,280
所以呢 门口的队伍就会稍显得壮大一点

7
00:00:43,480 --> 00:00:48,000
看看这样的长度 好像得等一段时间才能够买得到

8
00:00:48,680 --> 00:00:50,800
分拣猪蹄和肘子
边捞边卖

9
00:01:00,800 --> 00:01:03,280
这用筷子一插就透了

10
00:01:03,280 --> 00:01:06,880
不透的 还得再煮一会儿

11
00:02:13,600 --> 00:02:14,880
切了

12
00:02:26,800 --> 00:02:28,960
给我稍微放一点点汤

13
00:02:29,800 --> 00:02:34,000
肘子的话 吃的时候 把汤倒里面

14
00:02:35,680 --> 00:02:37,320
加热的时候倒里面

15
00:02:37,320 --> 00:02:40,400
但是你别倒完 你这汤多 倒完咸了

16
00:02:40,400 --> 00:02:41,600
适量

17
00:02:42,160 --> 00:02:44,640
猪蹄多少钱一斤了

18
00:02:45,000 --> 00:02:46,440
猪蹄40块钱一斤

19
00:02:46,440 --> 00:02:47,840
给我拿两个

20
00:02:47,840 --> 00:02:48,400
切不切

21
00:02:48,400 --> 00:02:48,960
切

22
00:02:49,560 --> 00:02:51,440
两个猪蹄切开

23
00:03:05,360 --> 00:03:06,960
给我放点汤

24
00:03:07,640 --> 00:03:08,800
汤到里面

25
00:03:08,800 --> 00:03:10,160
可以

26
00:03:11,720 --> 00:03:13,880
好大个

27
00:03:20,640 --> 00:03:22,520
要了点汤 还是很重的

28
00:03:22,520 --> 00:03:25,200
咱们这次没有要肘子 只是要了猪蹄

29
00:03:25,200 --> 00:03:27,200
猪蹄是40块钱一斤

30
00:03:27,200 --> 00:03:30,640
我看大家都要汤 所以 我也要了一些

31
00:03:30,640 --> 00:03:33,440
在那边排队的时候你会发现 刚出来的肉

32
00:03:33,440 --> 00:03:36,240
是粉扑扑的 兜着一股可爱的劲儿

33
00:03:36,800 --> 00:03:38,960
肉一旦有了着陆点

34
00:03:38,960 --> 00:03:42,240
它的浑身都会颤三颤

35
00:03:43,920 --> 00:03:47,640
排队的时候 看肘子和猪蹄最爽的时候就是

36
00:03:47,640 --> 00:03:51,360
小哥把肘子的骨头从里面抽出来

37
00:03:51,400 --> 00:03:56,440
感觉这块骨头就是卤肉里的卧底 根本不属于这个队伍

38
00:04:00,720 --> 00:04:03,880
肉能看出来 炖的软烂

39
00:04:03,880 --> 00:04:06,640
这么吃是稍微有点咸的

40
00:04:07,920 --> 00:04:09,600
是 比较咸

41
00:04:09,600 --> 00:04:14,000
直接吃是比较咸 我觉得夹馍拌饭是更合适的

42
00:04:16,800 --> 00:04:18,160
133块钱

43
00:04:19,720 --> 00:04:22,240
288元

44
00:04:22,240 --> 00:04:24,640
171

45
00:04:27,720 --> 00:04:31,600
顾客来买猪蹄和肘子  一般都是100块钱起步

46
00:04:31,600 --> 00:04:36,560
你能看到 大家拿着猪蹄和肘子都是成袋成袋朝外面走

47
00:04:36,560 --> 00:04:41,120
即使一天准备200斤的肉 几个小时也就卖光了

```

**Comment by shuaisoserious** [comment]
认领

**Comment by shuaisoserious** [comment]
字幕
1
00:00:01,920 --> 00:00:07,040
陕西·西安
Xian, Shaanxi
2
00:00:23,560 --> 00:00:27,200
不是 4点开门吗 是他家吗
Is the restaurant open at 4 pm? Is that the restaurant we are looking for?
3
00:00:32,200 --> 00:00:34,400
看来不仅是我们要找这份猪蹄
Not just us are looking for the trotter
4
00:00:34,400 --> 00:00:37,440
很多人都会早来 等这份猪蹄的
A lot people will come earlier and waiting for the trotter
5
00:00:37,440 --> 00:00:39,560
因为比平时要晚开门
Because it open later than regular time
6
00:00:39,560 --> 00:00:43,280
所以呢 门口的队伍就会稍显得壮大一点
So the waiting lines are longer than usual
7
00:00:43,480 --> 00:00:48,000
看看这样的长度 好像得等一段时间才能够买得到
We will wait longer time to buy it because of there are so many people before us
8
00:00:48,680 --> 00:00:50,800
分拣猪蹄和肘子
Split trotters and pork knuckles
边捞边卖
selling while splitting
 
 
9
00:01:00,800 --> 00:01:03,280
这用筷子一插就透了
It is easy to penetrate with a chopstick
10
00:01:03,280 --> 00:01:06,880
不透的 还得再煮一会儿
Not yet, need longer time to cook it
11
00:02:13,600 --> 00:02:14,880
切了
Chopped it
12
00:02:26,800 --> 00:02:28,960
给我稍微放一点点汤
I want some soup
13
00:02:29,800 --> 00:02:34,000
肘子的话 吃的时候 把汤倒里面
Eat it with the soup when you eat the pork knuckle 
14
00:02:35,680 --> 00:02:37,320
加热的时候倒里面
Pour it in when you heating it up
15
00:02:37,320 --> 00:02:40,400
但是你别倒完 你这汤多 倒完咸了
Don’t pour too much soup, it will get too salty
16
00:02:40,400 --> 00:02:41,600
适量
In moderate amount
17
00:02:42,160 --> 00:02:44,640
猪蹄多少钱一斤了
How much for the trotter?
18
00:02:45,000 --> 00:02:46,440
猪蹄40块钱一斤
40 yuan per catty 
19
00:02:46,440 --> 00:02:47,840
给我拿两个
Can i have two trotters
20
00:02:47,840 --> 00:02:48,400
切不切
Chopped it?
21
00:02:48,400 --> 00:02:48,960
切
yeah
22
00:02:49,560 --> 00:02:51,440
两个猪蹄切开
Chopped the two trotters
23
00:03:05,360 --> 00:03:06,960
给我放点汤
May I have some soup?
24
00:03:07,640 --> 00:03:08,800
汤到里面
Pour the soup in the bag?
25
00:03:08,800 --> 00:03:10,160
可以
sure
26
00:03:11,720 --> 00:03:13,880
好大个
So big
27
00:03:20,640 --> 00:03:22,520
要了点汤 还是很重的
The bag is heavy with soup in it
28
00:03:22,520 --> 00:03:25,200
咱们这次没有要肘子 只是要了猪蹄
We didn’t order pork knuckle this time, just the trotters
29
00:03:25,200 --> 00:03:27,200
猪蹄是40块钱一斤
Trotters are 40 yuan per catty
30
00:03:27,200 --> 00:03:30,640
我看大家都要汤 所以 我也要了一些
I asked some soup because everyone did
31
00:03:30,640 --> 00:03:33,440
在那边排队的时候你会发现 刚出来的肉
You will find that the meat is pink and cute
32
00:03:33,440 --> 00:03:36,240
是粉扑扑的 兜着一股可爱的劲儿
When you line up
33
00:03:36,800 --> 00:03:38,960
肉一旦有了着陆点
Once the pork fall somewhere
34
00:03:38,960 --> 00:03:42,240
它的浑身都会颤三颤
It shakes
35
00:03:43,920 --> 00:03:47,640
排队的时候 看肘子和猪蹄最爽的时候就是
The best part of watching pork knuckle and trotter when you line up is
36
00:03:47,640 --> 00:03:51,360
小哥把肘子的骨头从里面抽出来
Watching brother draw out the bone from the pork knuckle
37
00:03:51,400 --> 00:03:56,440
感觉这块骨头就是卤肉里的卧底 根本不属于这个队伍
The bone is like spy in the pork knuckle, and belongs nowhere
38
00:04:00,720 --> 00:04:03,880
肉能看出来 炖的软烂
We can see the pork is very soft 
39
00:04:03,880 --> 00:04:06,640
这么吃是稍微有点咸的
It taste salty when you eat it
40
00:04:07,920 --> 00:04:09,600
是 比较咸
Yeah, a little bit salty
41
00:04:09,600 --> 00:04:14,000
直接吃是比较咸 我觉得夹馍拌饭是更合适的
I think eat it with buns or rice is better
42
00:04:16,800 --> 00:04:18,160
133块钱
133 yuan
43
00:04:19,720 --> 00:04:22,240
288元
288 yuan
288 yuan
44
00:04:22,240 --> 00:04:24,640
171
171 yuan
45
00:04:27,720 --> 00:04:31,600
顾客来买猪蹄和肘子 一般都是100块钱起步
Customers will buy at least 100 yuan of pork knuckle and trotter
46
00:04:31,600 --> 00:04:36,560
你能看到 大家拿着猪蹄和肘子都是成袋成袋朝外面走
You can see everyone take a lot of bags of pork knuckle/ trotter and go
47
00:04:36,560 --> 00:04:41,120
即使一天准备200斤的肉 几个小时也就卖光了
It sold very soon even they prepare 200 catties of pork knuckles and trotters
