### ISSUE TITLE
[老饭骨] 豌豆糕 - https://youtu.be/F9QyaaA6QQ0

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1201]
**视频链接**：https://youtu.be/F9QyaaA6QQ0

YouTube 视频发布前请参考抖音视频：
- https://v.douyin.com/J8hpBTu/
- https://v.douyin.com/J8hyW3Y/
 
# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【國宴大師•豌豆糕】夏日必備！老式甜品開啟一整個夏天的清涼，是你記憶中的味道嗎？大爺大媽的愛情故事(3) |老飯骨

简介
小友們好，今天要教給大傢伙兒的是一道中式傳統甜品豌豆糕，豌豆去皮煮成豌豆沙，再配上白糖、梔子水、柿子餅、桂花醬，絕對是夏天裡清熱又解暑、香甜又可口的一道美味小吃，老少皆宜！
ps.大爺大媽的愛情故事持續更新中……

字幕
1
00:00:00,000 --> 00:00:03,480
你看这跟豌豆黄截然不同是吧

2
00:00:03,480 --> 00:00:04,760

3
00:00:04,760 --> 00:00:08,520
这要夏天 来这么一块 爽

4
00:00:08,520 --> 00:00:09,680
做一个豌豆糕

5
00:00:09,680 --> 00:00:13,360

6
00:00:13,360 --> 00:00:14,800
大爷你看这柿子

7
00:00:14,800 --> 00:00:17,520
这个是没泡之前的

8
00:00:17,520 --> 00:00:19,840
然后这个是刚才把那洗干净了 泡一下

9
00:00:19,840 --> 00:00:22,520
今天我一看这柿饼我就爱吃

10
00:00:23,440 --> 00:00:26,400
你这是去皮豌豆 去皮豌豆用的

11
00:00:26,400 --> 00:00:30,640
面点一般要的去皮的多 洗透亮了

12
00:00:30,640 --> 00:00:34,280

13
00:00:34,960 --> 00:00:38,440
慢慢煮上它 凉水下锅师父

14
00:00:38,440 --> 00:00:40,240
煮多长时间 煮二十分钟

15
00:00:40,240 --> 00:00:42,640
二十分钟要不够就半个小时

16
00:00:44,000 --> 00:00:47,520
咱们看自己家的火 放点碱

17
00:00:47,520 --> 00:00:50,200
过去老的手法都放点碱

18
00:00:50,200 --> 00:00:54,360
不放碱还不好吃 大约有四克的碱

19
00:00:54,360 --> 00:00:57,680
有的现在人胃不好 产生胃酸吃豆

20
00:00:57,680 --> 00:01:01,120
放了碱就不胃酸了 酸碱中和了

21
00:01:01,120 --> 00:01:04,640
第二条就是容易烂

22
00:01:04,640 --> 00:01:06,040
它还有那种特殊的香味

23
00:01:06,040 --> 00:01:11,680
碱特殊的香味跟豆融在一起 非常香

24
00:01:11,680 --> 00:01:16,480
在这我跟网友普及一下煮豆的技巧

25
00:01:16,480 --> 00:01:20,640
我们煮豆的时候适当地放点碱 少放水

26
00:01:20,640 --> 00:01:24,640
比如熬一个豆粥 我需要一锅水

27
00:01:24,640 --> 00:01:27,360
但是我刚开始不要放一锅水

28
00:01:27,360 --> 00:01:30,400
放三分之一锅的水

29
00:01:30,400 --> 00:01:32,760
一开锅了我就点点儿凉水

30
00:01:32,760 --> 00:01:34,160
开锅了就点点儿凉水

31
00:01:34,160 --> 00:01:38,320
一直点到最后 我需要的水就够了

32
00:01:38,320 --> 00:01:42,960
这时候的豆经过冷激热煮

33
00:01:42,960 --> 00:01:45,200
它迅速的开花儿

34
00:01:45,200 --> 00:01:48,920
所以碱的作用非常好

35
00:01:48,920 --> 00:01:51,880
这儿泡的是栀子水 栀子

36
00:01:51,880 --> 00:01:54,800
过箩 这是为了给它调一下色

37
00:01:54,800 --> 00:01:56,680
大爷你看到没有 黄黄的水

38
00:01:56,680 --> 00:01:59,880

39
00:01:59,880 --> 00:02:04,000
现在这豌豆已经开锅了 现在变成小火

40
00:02:04,000 --> 00:02:07,480
一边煮着豆我一边切柿饼 切成丝儿

41
00:02:07,480 --> 00:02:09,480

42
00:02:09,480 --> 00:02:13,600
咱们把它码上 码成一图案码上一花儿

43
00:02:13,600 --> 00:02:17,320
它里面一般还放一些果脯 什锦果脯

44
00:02:17,320 --> 00:02:18,840
这个蜜饯果脯

45
00:02:18,840 --> 00:02:23,160
在我们做食材的时候用的很广泛

46
00:02:23,160 --> 00:02:27,920
八宝饭 还有其它一些馅儿心

47
00:02:27,920 --> 00:02:32,760
好了 这个待用 这个待会拌在豆里

48
00:02:32,760 --> 00:02:34,520

49
00:02:36,560 --> 00:02:39,040
这要过箩么 不过箩大爷

50
00:02:40,560 --> 00:02:45,240
要吃有颗粒状的 这个吃法有劲

51
00:02:45,240 --> 00:02:47,880
这会儿我倒点刚才泡的栀子水

52
00:02:47,880 --> 00:02:49,320
稍微来一点点

53
00:02:49,320 --> 00:02:50,680

54
00:02:50,680 --> 00:02:55,520
豌豆一般 咱只要泡了之后

55
00:02:55,520 --> 00:02:57,320
第二天蒸可不爱烂了

56
00:02:57,320 --> 00:03:00,360
而且就得现加碱现熬

57
00:03:00,360 --> 00:03:02,440
稍微的这会儿点一点糖

58
00:03:02,440 --> 00:03:08,680
这会儿点糖 先放了糖它也不爱烂

59
00:03:08,680 --> 00:03:12,600
先放糖有时候糖一渍 我感觉不爱烂

60
00:03:12,600 --> 00:03:15,800
把果料放进去

61
00:03:15,800 --> 00:03:19,360
其实这可以放很多不少的料是吧

62
00:03:19,360 --> 00:03:24,120
主要是它得有青梅 腌的青梅

63
00:03:24,120 --> 00:03:26,040
没有 没买着

64
00:03:26,040 --> 00:03:27,440
行了

65
00:03:28,040 --> 00:03:32,240
我把这个 桂花酱 糖桂花

66
00:03:32,240 --> 00:03:36,240
抹这一层 增加花香气

67
00:03:36,240 --> 00:03:40,680
而且它那甜口也特别润

68
00:03:40,680 --> 00:03:44,640
擓到里边 这豌豆一定不要熬太干

69
00:03:44,640 --> 00:03:49,600

70
00:03:49,600 --> 00:03:55,120
刮平 你看这跟豌豆黄截然不同

71
00:03:55,120 --> 00:03:57,280
能吃到豆的口感

72
00:03:57,280 --> 00:03:59,000

73
00:03:59,000 --> 00:04:02,840
行了晾凉了下冰箱 歇会儿吧

74
00:04:02,840 --> 00:04:04,680
定好了

75
00:04:04,680 --> 00:04:06,920

76
00:04:06,920 --> 00:04:12,160
这在家里边 炎热的夏天吃上一块

77
00:04:12,160 --> 00:04:13,680
尤其那小朋友

78
00:04:13,680 --> 00:04:24,520

79
00:04:24,520 --> 00:04:30,040
好吃 它跟豌豆黄有截然不同的口感

80
00:04:30,040 --> 00:04:31,520
那个是属于细腻

81
00:04:31,520 --> 00:04:33,880
这个虽然是粗

82
00:04:33,880 --> 00:04:38,160
但是它有吃豆的那种感觉 沙

83
00:04:38,160 --> 00:04:40,600
还有淡淡的桂花的香气

84
00:04:40,600 --> 00:04:46,880

85
00:04:46,880 --> 00:04:50,480
我告诉你这要夏天 来这么一块 爽

86
00:04:50,480 --> 00:04:52,480

87
00:05:00,680 --> 00:05:02,160
晚上我把所有的兜

88
00:05:02,160 --> 00:05:03,600
都掏出来

89
00:05:03,600 --> 00:05:06,720
那是同事凑份子啊

90
00:05:06,720 --> 00:05:07,720
最多五毛钱

91
00:05:07,720 --> 00:05:08,720
最少两毛钱

92
00:05:08,720 --> 00:05:11,400
一共掏下来147.6毛钱

93
00:05:11,400 --> 00:05:13,160
我说这是咱们

94
00:05:13,160 --> 00:05:16,520
今天开始过日子的家底

95
00:05:16,520 --> 00:05:18,240
是我们今天生活的开始

96
00:05:18,240 --> 00:05:20,480
大妈呢就是 我可不管这事

97
00:05:20,480 --> 00:05:22,040
全是你管

98
00:05:22,040 --> 00:05:22,920
从这开始

99
00:05:22,920 --> 00:05:24,800
我就开始管家 治家

100
00:05:24,800 --> 00:05:28,360
我要求我们跟双方父母有一种约定

101
00:05:28,360 --> 00:05:30,520
比如我们有钱多给

102
00:05:30,520 --> 00:05:33,640
那时候我们双方家长每月给5块钱

103
00:05:33,640 --> 00:05:35,560
我们俩人的工资总额

104
00:05:35,560 --> 00:05:37,000
77块钱

105
00:05:37,000 --> 00:05:39,600
所以给双方家长拿出10块钱

106
00:05:39,600 --> 00:05:42,040
应该说我挺有难度的

107
00:05:42,040 --> 00:05:44,520
因为我说都有小孩了

108
00:05:44,520 --> 00:05:45,800
我再没有钱

109
00:05:45,800 --> 00:05:48,040
我只能说有钱多给

110
00:05:48,040 --> 00:05:49,080
没钱少给

111
00:05:49,080 --> 00:05:50,240
再没钱我不给

112
00:05:50,240 --> 00:05:51,640
但是我希望

113
00:05:51,640 --> 00:05:53,320
你们双方的老人

114
00:05:53,320 --> 00:05:53,840
是吧

115
00:05:53,840 --> 00:05:55,000
千万别在这个问题上

116
00:05:55,000 --> 00:05:56,440
特别纠结

117
00:05:56,440 --> 00:05:58,040
我也有难度

118
00:05:58,040 --> 00:05:59,040
因为我们俩人嘛

119
00:05:59,040 --> 00:06:00,680
在家里头都行大

120
00:06:00,680 --> 00:06:03,520
我们还要给弟弟妹妹们

121
00:06:03,520 --> 00:06:04,920
做出一些榜样

122
00:06:04,920 --> 00:06:07,480
所以双方老家

123
00:06:07,480 --> 00:06:08,880
还对我们还是很谅解的

124
00:06:08,880 --> 00:06:10,880
确实我们有孩子以后

125
00:06:10,880 --> 00:06:12,080
我们就不给钱

126
00:06:12,080 --> 00:06:12,960
但是我要求

127
00:06:12,960 --> 00:06:14,960
不管回谁的家

128
00:06:14,960 --> 00:06:16,480
一定要给老人

129
00:06:16,480 --> 00:06:18,320
因为那边还有个奶奶吗

130
00:06:18,320 --> 00:06:20,360
一定要给奶奶也好

131
00:06:20,360 --> 00:06:21,280
给家里人也好

132
00:06:21,280 --> 00:06:23,120
哪怕买两块钱的东西

133
00:06:23,120 --> 00:06:25,120
但是两块钱那时候也是钱

134
00:06:25,120 --> 00:06:26,880
能买好多东西

135
00:06:26,880 --> 00:06:28,200
你要买苹果

136
00:06:28,200 --> 00:06:29,160
两块钱一斤

137
00:06:29,160 --> 00:06:30,640
能买十斤苹果

138
00:06:30,640 --> 00:06:32,160
但是家里人也知道

139
00:06:32,160 --> 00:06:34,640
我们过日子也比较不容易

140
00:06:34,640 --> 00:06:36,720
能拿回4块钱的东西回来

141
00:06:36,720 --> 00:06:39,280
什么拿点带鱼

142
00:06:39,280 --> 00:06:40,440
拿点什么

143
00:06:40,440 --> 00:06:41,800
包子

144
00:06:41,800 --> 00:06:43,520
反正有一些常吃

145
00:06:43,520 --> 00:06:44,520
常用的东西

146
00:06:44,520 --> 00:06:45,480
八一年以后

147
00:06:45,480 --> 00:06:48,400
我就开始到外边去闯了

148
00:06:48,400 --> 00:06:52,000
曾经也是因为挣工资少

149
00:06:52,000 --> 00:06:54,000
因为那阵要涨一级工资

150
00:06:54,000 --> 00:06:56,520
当时我跟领导的关系没有处理好

151
00:06:56,520 --> 00:06:58,680
这一级工资就没给我涨了

152
00:06:58,680 --> 00:07:02,120
那阵一级工资6块钱

153
00:07:02,120 --> 00:07:03,720
应该说对我的打击还是挺大的

154
00:07:03,720 --> 00:07:05,960
6块钱也是不容易

155
00:07:05,960 --> 00:07:06,640
是吧

156
00:07:06,640 --> 00:07:08,160
6块钱相当于一个人的

157
00:07:08,160 --> 00:07:09,480
一个月的生活费

158
00:07:09,480 --> 00:07:10,800
我特别的失落

159
00:07:10,800 --> 00:07:12,000
也不想再干什么了

160
00:07:12,000 --> 00:07:13,680
也闹了一些情绪

161
00:07:13,680 --> 00:07:15,680
但是我有好多好朋友

162
00:07:15,680 --> 00:07:16,520
是吧

163
00:07:16,520 --> 00:07:18,520
就劝我 说你好好的

164
00:07:18,520 --> 00:07:20,520
学好厨艺

165
00:07:20,520 --> 00:07:22,760
等你长了本事了

166
00:07:22,760 --> 00:07:23,920
你到哪都挣钱

167
00:07:23,920 --> 00:07:25,600
所以这位老哥哥

168
00:07:25,600 --> 00:07:27,160
对我的启发特别大

169
00:07:27,160 --> 00:07:29,560
我就开始重新打鼓另开张

170
00:07:29,560 --> 00:07:31,520
就认真的学厨艺

171
00:07:31,520 --> 00:07:33,360
正好在中央党校里边

172
00:07:33,360 --> 00:07:34,480
办一烹饪学校

173
00:07:34,480 --> 00:07:35,760
让我去上课

174
00:07:35,760 --> 00:02:42,520
说一天能给30块钱

**Comment by Yingzhang1122** [comment]
#标题（翻译主要意思即可，不要超过 100 个字符）
#【國宴大師•豌豆糕】夏日必備！老式甜品開啟一整個夏天的清涼，是你記憶中的味道嗎？大爺大媽的愛情故事(3) |老飯骨
State Banquet Master Chef - Wan Dou Gao (Pea cake), a must-have dessert in summer! Da Ye and Da Ma's love story (3)

#简介
#小友們好，今天要教給大傢伙兒的是一道中式傳統甜品豌豆糕，豌豆去皮煮成豌豆沙，再配上白糖、梔子水、柿子餅、桂花醬，絕對是夏天裡清熱又解暑、香甜又可口的一道美味小吃，老少皆宜！
#ps.大爺大媽的愛情故事持續更新中……
Hello friends! Today we share a traditional Chinese dessert, 'Wan Dou Gao' (pea cake). Uncoated peas are boiled into a paste, which is accompanied by sugar, gardenia water, dried persimmon, and sweet osmanthus jam. It's absolutely a sweet and delicious snack that clears out your internal heat in this hot summer, suitable for both the elderly and kids!
Ps. The love story of Da Ye and Da Ma is still being updated!

字幕
1
00:00:00,000 --> 00:00:03,480
#你看这跟豌豆黄截然不同是吧
See? This is totally different from the 'Wan Dou Huang' pea cake, right?

2
00:00:03,480 --> 00:00:04,760

3
00:00:04,760 --> 00:00:08,520
#这要夏天 来这么一块 爽
It's absolutely cool to have such a piece in the hot summer

4
00:00:08,520 --> 00:00:09,680
#做一个豌豆糕
Let's make a 'Wan Dou Gao' pea cake

5
00:00:09,680 --> 00:00:13,360

6
00:00:13,360 --> 00:00:14,800
#大爷你看这柿子
Da Ye, look at the dried persimmon

7
00:00:14,800 --> 00:00:17,520
#这个是没泡之前的
This one is not soaked

8
00:00:17,520 --> 00:00:19,840
#然后这个是刚才把那洗干净了 泡一下
This one has been washed and soaked for a while

9
00:00:19,840 --> 00:00:22,520
#今天我一看这柿饼我就爱吃
I already love this snack just because of the dried persimmon

10
00:00:23,440 --> 00:00:26,400
#你这是去皮豌豆 去皮豌豆用的
-These are uncoated peas. -We are using uncoated peas today

11
00:00:26,400 --> 00:00:30,640
#面点一般要的去皮的多 洗透亮了
We usually use uncoated peas to make pastries. Wash them until clean and shiny

12
00:00:30,640 --> 00:00:34,280

13
00:00:34,960 --> 00:00:38,440
#慢慢煮上它 凉水下锅师父
Let's boil it slowly. I'm gonna put the peas into the wok with cold water, master

14
00:00:38,440 --> 00:00:40,240
#煮多长时间 煮二十分钟
-For how long are you going to boil it? -20 minutes

15
00:00:40,240 --> 00:00:42,640
#二十分钟要不够就半个小时
If not enough, boil it for half an hour then

16
00:00:44,000 --> 00:00:47,520
#咱们看自己家的火 放点碱
The time depends on your cooking stove. Add some soda

17
00:00:47,520 --> 00:00:50,200
#过去老的手法都放点碱
In classic protocols, soda is often used under such situations

18
00:00:50,200 --> 00:00:54,360
#不放碱还不好吃 大约有四克的碱
-It'll taste bad without soda. -This is about 4 grams of soda

19
00:00:54,360 --> 00:00:57,680
#有的现在人胃不好 产生胃酸吃豆
Some people may suffer from too much stomach acid after eating peas

20
00:00:57,680 --> 00:01:01,120
#放了碱就不胃酸了 酸碱中和了
-This problem can be settled by adding soda. -Soda can neutralize acid #这里化学上说是不对的...不过neutralize也可以有抵消的意思

21
00:01:01,120 --> 00:01:04,640
#第二条就是容易烂
What else, the peas become mushy faster (with soda)

22
00:01:04,640 --> 00:01:06,040
#它还有那种特殊的香味
Also it gives a special aroma

23
00:01:06,040 --> 00:01:11,680
#碱特殊的香味跟豆融在一起 非常香
The special aroma of soda fuses well with that of peas and smells awesome

24
00:01:11,680 --> 00:01:16,480
#在这我跟网友普及一下煮豆的技巧
Here I want to introduce you guys the tricks of boiling beans

25
00:01:16,480 --> 00:01:20,640
#我们煮豆的时候适当地放点碱 少放水
When boiling beans, you can add a moderate amount of soda, but add less water

26
00:01:20,640 --> 00:01:24,640
#比如熬一个豆粥 我需要一锅水
For example, you may need a whole pot of water when cooking a bean congee

27
00:01:24,640 --> 00:01:27,360
#但是我刚开始不要放一锅水
But don't add that much water in the beginning

28
00:01:27,360 --> 00:01:30,400
#放三分之一锅的水
Just fill one-third of a whole pot

29
00:01:30,400 --> 00:01:32,760
#一开锅了我就点点儿凉水
When it boils, add some cold water

30
00:01:32,760 --> 00:01:34,160
#开锅了就点点儿凉水
When it boils again, add some cold water

31
00:01:34,160 --> 00:01:38,320
#一直点到最后 我需要的水就够了
Repeat this step until the end, and there'll be enough water in the congee

32
00:01:38,320 --> 00:01:42,960
#这时候的豆经过冷激热煮
In this way, the beans are chilled and boiled repeatedly

33
00:01:42,960 --> 00:01:45,200
#它迅速的开花儿
They'll 'blossom' (become stewed and soft) very fast

34
00:01:45,200 --> 00:01:48,920
#所以碱的作用非常好
So the soda plays an important role here

35
00:01:48,920 --> 00:01:51,880
#这儿泡的是栀子水 栀子
-Here is some gardenia water. -Gardenia

36
00:01:51,880 --> 00:01:54,800
#过箩 这是为了给它调一下色
Filter it. This is for the color

37
00:01:54,800 --> 00:01:56,680
#大爷你看到没有 黄黄的水
You see that, Da Ye? The water becomes yellow

38
00:01:56,680 --> 00:01:59,880

39
00:01:59,880 --> 00:02:04,000
#现在这豌豆已经开锅了 现在变成小火
Now the peas are boiling. Turn it to low heat now

40
00:02:04,000 --> 00:02:07,480
#一边煮着豆我一边切柿饼 切成丝儿
While boiling the peas, let me cut the dried persimmon into slices

41
00:02:07,480 --> 00:02:09,480

42
00:02:09,480 --> 00:02:13,600
#咱们把它码上 码成一图案码上一花儿
Let's tile them here. Tile the slices into a pattern

43
00:02:13,600 --> 00:02:17,320
#它里面一般还放一些果脯 什锦果脯
Generally we use some preserved fruit in this dish. Mixed preserved fruit

44
00:02:17,320 --> 00:02:18,840
#这个蜜饯果脯
The preserved fruit...

45
00:02:18,840 --> 00:02:23,160
#在我们做食材的时候用的很广泛
is widely used in all kinds of dishes

46
00:02:23,160 --> 00:02:27,920
#八宝饭 还有其它一些馅儿心
Such as in 'Ba Bao Fan' (eight-treasure rice pudding), and in some other kinds of stuffings

47
00:02:27,920 --> 00:02:32,760
#好了 这个待用 这个待会拌在豆里
Ok. This is ready for use. We'll mix it with peas

48
00:02:32,760 --> 00:02:34,520

49
00:02:36,560 --> 00:02:39,040
#这要过箩么 不过箩大爷
-Are you going to sift it? -No, Da Ye

50
00:02:40,560 --> 00:02:45,240
#要吃有颗粒状的 这个吃法有劲
-We are going to eat with these granules. -That's interesting

51
00:02:45,240 --> 00:02:47,880
#这会儿我倒点刚才泡的栀子水
Now I'm adding some gardenia water that we prepared

52
00:02:47,880 --> 00:02:49,320
#稍微来一点点
Just a little bit

53
00:02:49,320 --> 00:02:50,680

54
00:02:50,680 --> 00:02:55,520
#豌豆一般 咱只要泡了之后
Generally... If you soak the peas in advance

55
00:02:55,520 --> 00:02:57,320
#第二天蒸可不爱烂了
They won't become soft if you steam them for a long time on the second day

56
00:02:57,320 --> 00:03:00,360
#而且就得现加碱现熬
You need to boil it on time with soda

57
00:03:00,360 --> 00:03:02,440
#稍微的这会儿点一点糖
Now add some sugar

58
00:03:02,440 --> 00:03:08,680
#这会儿点糖 先放了糖它也不爱烂
Add sugar now. The peas won't turn mushy easily if sugar is added too early

59
00:03:08,680 --> 00:03:12,600
#先放糖有时候糖一渍 我感觉不爱烂
If sugar is added in the beginning, it'll 'pickle' the peas, which will become tough

60
00:03:12,600 --> 00:03:15,800
#把果料放进去
Add the fruits now

61
00:03:15,800 --> 00:03:19,360
#其实这可以放很多不少的料是吧
Actually we can add a lot of stuff here, right?

62
00:03:19,360 --> 00:03:24,120
#主要是它得有青梅 腌的青梅
Well, the most important ingredient should be ome fruit. Pickled ome fruit

63
00:03:24,120 --> 00:03:26,040
#没有 没买着
But we don't have it here. We couldn't find it anywhere

64
00:03:26,040 --> 00:03:27,440
#行了
Done

65
00:03:28,040 --> 00:03:32,240
#我把这个 桂花酱 糖桂花
Let me add the sweet osmanthus jam. Sugar osmanthus jam

66
00:03:32,240 --> 00:03:36,240
#抹这一层 增加花香气
Smear it like this to enhance the aroma of flowers

67
00:03:36,240 --> 00:03:40,680
#而且它那甜口也特别润
Also it is 'nourishly' sweet

68
00:03:40,680 --> 00:03:44,640
#擓到里边 这豌豆一定不要熬太干
Scoop it inside. The pea paste must not be too dry

69
00:03:44,640 --> 00:03:49,600

70
00:03:49,600 --> 00:03:55,120
#刮平 你看这跟豌豆黄截然不同
Flatten it. See? This is totally different from 'Wan Dou Huang' pea cake

71
00:03:55,120 --> 00:03:57,280
#能吃到豆的口感
as you can feel the texture of the peas

72
00:03:57,280 --> 00:03:59,000

73
00:03:59,000 --> 00:04:02,840
#行了晾凉了下冰箱 歇会儿吧
Ok. When it cools down, put it into the fridge. Let's have a rest

74
00:04:02,840 --> 00:04:04,680
#定好了
Now it becomes solid

75
00:04:04,680 --> 00:04:06,920

76
00:04:06,920 --> 00:04:12,160
#这在家里边 炎热的夏天吃上一块
If you have a piece of this at home, in the hot summer

77
00:04:12,160 --> 00:04:13,680
#尤其那小朋友
Kids will definitely love it

78
00:04:13,680 --> 00:04:24,520

79
00:04:24,520 --> 00:04:30,040
#好吃 它跟豌豆黄有截然不同的口感
Delicious. It has a totally different texture from 'Wan Dou Huang' pea cake

80
00:04:30,040 --> 00:04:31,520
#那个是属于细腻
'Wan Dou Huang' has a more silky texture

81
00:04:31,520 --> 00:04:33,880
#这个虽然是粗
Though this one is rougher

82
00:04:33,880 --> 00:04:38,160
#但是它有吃豆的那种感觉 沙
-It gives you a feeling of eating peas. -Mushy

83
00:04:38,160 --> 00:04:40,600
#还有淡淡的桂花的香气
Also with a light fragrance of sweet osmanthus

84
00:04:40,600 --> 00:04:46,880

85
00:04:46,880 --> 00:04:50,480
#我告诉你这要夏天 来这么一块 爽
I bet it's absolutely cool to have such a piece in the hot summer

86
00:04:50,480 --> 00:04:52,480

87
00:05:00,680 --> 00:05:02,160
#晚上我把所有的兜
At night, I searched through

88
00:05:02,160 --> 00:05:03,600
#都掏出来
all my pockets

89
00:05:03,600 --> 00:05:06,720
#那是同事凑份子啊
That was the wedding gift money from my colleagues

90
00:05:06,720 --> 00:05:07,720
#最多五毛钱
The largest amount was 0.5 yuan

91
00:05:07,720 --> 00:05:08,720
#最少两毛钱
The smallest amount, 0.2 yuan

92
00:05:08,720 --> 00:05:11,400
#一共掏下来147.6毛钱
In total, 147.6 yuan

93
00:05:11,400 --> 00:05:13,160
#我说这是咱们
I said, 'this is the...'

94
00:05:13,160 --> 00:05:16,520
#今天开始过日子的家底
'initial funds of our family, which starts from today'

95
00:05:16,520 --> 00:05:18,240
#是我们今天生活的开始
'It is the beginning of our life'

96
00:05:18,240 --> 00:05:20,480
#大妈呢就是 我可不管这事
Da Ma was like, 'I won't manage that'

97
00:05:20,480 --> 00:05:22,040
#全是你管
'This is all your business'

98
00:05:22,040 --> 00:05:22,920
#从这开始
From that time

99
00:05:22,920 --> 00:05:24,800
#我就开始管家 治家
I started to take care of my family

100
00:05:24,800 --> 00:05:28,360
#我要求我们跟双方父母有一种约定
I decided that, we had a promise with both families

101
00:05:28,360 --> 00:05:30,520
#比如我们有钱多给
For example, we send them more money if we have some extra

102
00:05:30,520 --> 00:05:33,640
#那时候我们双方家长每月给5块钱
At that time, we sent 5 yuan per month to both of our families

103
00:05:33,640 --> 00:05:35,560
#我们俩人的工资总额
The total amount of our salaries

104
00:05:35,560 --> 00:05:37,000
#77块钱
was 77 yuan

105
00:05:37,000 --> 00:05:39,600
#所以给双方家长拿出10块钱
So it was hard for us

106
00:05:39,600 --> 00:05:42,040
#应该说我挺有难度的
to give them 10 yuan per month

107
00:05:42,040 --> 00:05:44,520
#因为我说都有小孩了
But when we had a kid

108
00:05:44,520 --> 00:05:45,800
#我再没有钱
We couldn't spare more money

109
00:05:45,800 --> 00:05:48,040
#我只能说有钱多给
So I could only say that, we send them more money if we have extra

110
00:05:48,040 --> 00:05:49,080
#没钱少给
Otherwise, we send less

111
00:05:49,080 --> 00:05:50,240
#再没钱我不给
If it's worse, we don't send money to them

112
00:05:50,240 --> 00:05:51,640
#但是我希望
But I was hoping that

113
00:05:51,640 --> 00:05:53,320
#你们双方的老人
Our parents...

114
00:05:53,320 --> 00:05:53,840
#是吧
Right?

115
00:05:53,840 --> 00:05:55,000
#千万别在这个问题上
I hoped that they didn't...

116
00:05:55,000 --> 00:05:56,440
#特别纠结
...feel bad about this issue (not sending enough money)

117
00:05:56,440 --> 00:05:58,040
#我也有难度
Because it was really difficult for me

118
00:05:58,040 --> 00:05:59,040
#因为我们俩人嘛
Both of us...

119
00:05:59,040 --> 00:06:00,680
#在家里头都行大
were the first kid in our families

120
00:06:00,680 --> 00:06:03,520
#我们还要给弟弟妹妹们
So we had to be good role models

121
00:06:03,520 --> 00:06:04,920
#做出一些榜样
for our younger brothers and sisters

122
00:06:04,920 --> 00:06:07,480
#所以双方老家
So both of our families

123
00:06:07,480 --> 00:06:08,880
#还对我们还是很谅解的
were very forgiving on us

124
00:06:08,880 --> 00:06:10,880
#确实我们有孩子以后
Indeed, after we had a kid

125
00:06:10,880 --> 00:06:12,080
#我们就不给钱
We stopped giving them money regularly

126
00:06:12,080 --> 00:06:12,960
#但是我要求
But I insisted that

127
00:06:12,960 --> 00:06:14,960
#不管回谁的家
No matter which family we visited

128
00:06:14,960 --> 00:06:16,480
#一定要给老人
We must ...

129
00:06:16,480 --> 00:06:18,320
#因为那边还有个奶奶吗
Because her grandma was still there

130
00:06:18,320 --> 00:06:20,360
#一定要给奶奶也好
We must buy something when visiting them...

131
00:06:20,360 --> 00:06:21,280
#给家里人也好
no matter for her grandma, or for the family

132
00:06:21,280 --> 00:06:23,120
#哪怕买两块钱的东西
even if we could only afford 2-yuan gifts

133
00:06:23,120 --> 00:06:25,120
#但是两块钱那时候也是钱
However, 2 yuan worthed a lot back then

134
00:06:25,120 --> 00:06:26,880
#能买好多东西
You could buy a lot of stuff with 2 yuan

135
00:06:26,880 --> 00:06:28,200
#你要买苹果
For example, if you buy apples

136
00:06:28,200 --> 00:06:29,160
#两块钱一斤
Apples were 0.2 yuan/jin (0.4 yuan/kg) at that time #这里我觉得应该是两毛？

137
00:06:29,160 --> 00:06:30,640
#能买十斤苹果
You could buy 10 jin (5 kg) of apples

138
00:06:30,640 --> 00:06:32,160
#但是家里人也知道
But our families knew

139
00:06:32,160 --> 00:06:34,640
#我们过日子也比较不容易
that we were living a hard life

140
00:06:34,640 --> 00:06:36,720
#能拿回4块钱的东西回来
So we could actually return with 4-yuan stuff

141
00:06:36,720 --> 00:06:39,280
#什么拿点带鱼
such as some beltfish

142
00:06:39,280 --> 00:06:40,440
#拿点什么
or ...

143
00:06:40,440 --> 00:06:41,800
#包子
Steamed buns

144
00:06:41,800 --> 00:06:43,520
#反正有一些常吃
Anyway, like some common food

145
00:06:43,520 --> 00:06:44,520
#常用的东西
or things that you would usually use

146
00:06:44,520 --> 00:06:45,480
#八一年以后
After 1981

147
00:06:45,480 --> 00:06:48,400
#我就开始到外边去闯了
I started to make a living outside

148
00:06:48,400 --> 00:06:52,000
#曾经也是因为挣工资少
It was because I couldn't make much money (at my job)

149
00:06:52,000 --> 00:06:54,000
#因为那阵要涨一级工资
At that time, my salary was about to be promoted by one level

150
00:06:54,000 --> 00:06:56,520
#当时我跟领导的关系没有处理好
But I wasn't going on well with my leader

151
00:06:56,520 --> 00:06:58,680
#这一级工资就没给我涨了
So my salary was not promoted

152
00:06:58,680 --> 00:07:02,120
#那阵一级工资6块钱
One level of promotion was 6 yuan per month

153
00:07:02,120 --> 00:07:03,720
#应该说对我的打击还是挺大的
It was indeed a heavy blow on me

154
00:07:03,720 --> 00:07:05,960
#6块钱也是不容易
6 yuan was a lot of money

155
00:07:05,960 --> 00:07:06,640
#是吧
Right?

156
00:07:06,640 --> 00:07:08,160
#6块钱相当于一个人的
6 yuan was equivalent to ...

157
00:07:08,160 --> 00:07:09,480
#一个月的生活费
One man's living expenses for one month

158
00:07:09,480 --> 00:07:10,800
#我特别的失落
I was extremely frustrated

159
00:07:10,800 --> 00:07:12,000
#也不想再干什么了
and I didn't want to carry on

160
00:07:12,000 --> 00:07:13,680
#也闹了一些情绪
I was also in a bad mood

161
00:07:13,680 --> 00:07:15,680
#但是我有好多好朋友
But I had a lot of good friends

162
00:07:15,680 --> 00:07:16,520
#是吧
Right?

163
00:07:16,520 --> 00:07:18,520
#就劝我 说你好好的
They persuaded me to keep calm

164
00:07:18,520 --> 00:07:20,520
#学好厨艺
and focus on studying cooking

165
00:07:20,520 --> 00:07:22,760
#等你长了本事了
Such that when I become skillful

166
00:07:22,760 --> 00:07:23,920
#你到哪都挣钱
I could make money everywhere

167
00:07:23,920 --> 00:07:25,600
#所以这位老哥哥
So that old pal...

168
00:07:25,600 --> 00:07:27,160
#对我的启发特别大
He inspired me a lot

169
00:07:27,160 --> 00:07:29,560
#我就开始重新打鼓另开张
And I decided to get back on the track

170
00:07:29,560 --> 00:07:31,520
#就认真的学厨艺
To study cooking hard

171
00:07:31,520 --> 00:07:33,360
#正好在中央党校里边
There happened to be a cooking school

172
00:07:33,360 --> 00:07:34,480
#办一烹饪学校
held in the Party School of the Central Committee of CPC

173
00:07:34,480 --> 00:07:35,760
#让我去上课
They recruited me as a teacher #如果我没有理解错的话应该是当老师

174
00:07:35,760 --> 00:02:42,520
#说一天能给30块钱
with a salary of 30 yuan per day
