### ISSUE TITLE
[华农兄弟] 炸南瓜花 - https://youtu.be/fpmwIn768ac

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1202]
https://youtu.be/fpmwIn768ac
<p>&#35270;&#39057;&#21457;&#24067;&#20110; June 24, 2020 at 02:19PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, pleas upload
#https://youtu.be/fpmwIn768ac

#华农兄弟：最近没什么菜吃，摘点南瓜花来炸，味道还可以哟
#Huanong Brothers: We're running out of food recently. We pick some pumpkin flowers and fry them. It tastes not bad.

0:00:00.000,0:00:02.800
# 大家好  今天去兄弟家的瓜地裡面看一下  (註︰英文沒有「瓜」這個概念，所以寫成菜地算了)
Hi everyone! Today we're gonna have a look at our buddy's veggie farm.

0:00:03.340,0:00:06.720
# 你看  這裡  他家的  他家的那個攀蒲開了好多花呀
Look! Here! His, the "panpu" (pumpkin) at his place are now blooming.

0:00:08.080,0:00:09.300
# 摘那個花回去
Let's pick some those flowers back.

0:00:09.780,0:00:10.280
# 你看
Look!

0:00:10.540,0:00:13.020
# 這個就是母花  有果的這個母花
This is female. Those with fruits are female.

0:00:13.300,0:00:15.500
# 這個公的就是 沒果子的
And this is male. It has, like, no fruits.

0:00:16.420,0:00:16.920
# 這就是
It's ah,

0:00:17.500,0:00:18.000
# 公的
it's male.

0:00:18.900,0:00:20.200
# 把它摘的就摘這個
That's exactly what we wanna pick now.

0:00:22.520,0:00:24.060
# 你看  這固就是傳播花粉的
Look! They're for spreading the pollen.

0:00:24.480,0:00:25.320
# 這花粉在這裡
The pollen is here.

0:00:26.360,0:00:27.680
# 我們主要就要這個
In fact, that's what we need.

0:00:29.060,0:00:31.460
# 裹上面粉  用油炸一下
I'll coat it with flour, and then fry it.

0:00:32.820,0:00:33.740
# 很好吃的哦  這個
It's really tasty, you know.

0:00:34.940,0:00:35.620
# 摘了一朵
So now I have one.

0:00:36.960,0:00:37.840
# 這還有一棵
Here's another one.

0:00:39.260,0:00:40.440
# 用刀來  把它割回去
Let me cut it off, with a knife.

0:00:44.740,0:00:45.660
# 這裡也有一棵
And here's another one.

0:00:47.840,0:00:50.040
# 這公花 不摘掉也會浪費的
The male flowers, would become a waste even if they're left here.

0:00:50.280,0:00:51.900
# 太多公的了  不用那麼多的
They're are simply too many male. We don't need that many.

0:00:52.920,0:00:54.380
# 去搞幾個母的就行啦  (註︰這句應該是不完整的，所以不太明白)
With a few female, that's it!

0:00:59.840,0:01:01.240
# 這些都是沒用的
These are all useless.

0:01:03.420,0:01:04.300
# 留在這裡
Their sole purpose here,

0:01:05.720,0:01:07.140
# 只能用來傳播花粉
is spreading pollen.

0:01:13.480,0:01:15.880
# 這公的要一個就夠啦 傳播花粉
One single male is everything that's needed. It spreads the pollen,

0:01:16.400,0:01:19.160
# 兩個就把它傳  傳  傳過去啦
it spreads, spreads, spreads in no time.

0:01:21.880,0:01:25.120
# 你看  這還有一個黃色的哦 這個誰噠  這個
Look! Here's also a yellow one. Whose is it, this one?

0:01:27.700,0:01:29.000
# 順便摘一個回去
Why not take one with me?

0:01:29.620,0:01:30.340
# 兄弟家的
It's my buddy's.

0:01:30.660,0:01:31.760
# 昨天我還跟他說過了
I talked with him yesterday.

0:01:32.380,0:01:33.820
# 說  摘一個攀蒲給我
I've asked him, to give me a "panpu".

0:01:36.100,0:01:37.100
# 現在要摘花啦
I'm gonna pick the flowers now.

0:01:53.240,0:01:55.700
# 長了很多南瓜哦  這裡有個大南瓜
Here are a lot of pumpkins. And here's a big pumpkin.

0:02:03.020,0:02:04.320
# 你看  這一朵它還
Look! This flower is still,

0:02:05.140,0:02:06.000
# 藏在這裡
hiding here.

0:02:07.520,0:02:08.900
# 直接就把你擰下來
I twist you off right away.

0:02:09.920,0:02:11.280
# 管你願不願意
You like it or not, I don't care.

0:02:14.600,0:02:16.120
# 有點毛  回去洗一下就好了
It's a bit furry. I'll wash it.

0:02:18.860,0:02:19.360
# 嗯
Um!

0:02:20.180,0:02:20.760
# 有點香
It smells quite good.

0:02:22.100,0:02:23.940
# 你看  兄弟家這裡還種了茄子哦
Look! My buddy also has eggplants here.

0:02:24.360,0:02:26.000
# 這茄子都已經超大了
The eggplants are already oversized.

0:02:26.440,0:02:27.060
# 他都不摘
But he didn't pick them.

0:02:28.320,0:02:28.960
# 我幫它
Let me help him.

0:02:29.760,0:02:32.860
# 你看  它茄子了這個  不知道還能不能吃
Look! It's an old eggplant. I wonder if it's still edible.

0:02:33.880,0:02:37.040
# 摘  摘  摘幾個回去
Let me pick, pick, pick some back home.

0:02:38.180,0:02:42.340
# 不要摘那麼多  這個  摘去 不知道好不好吃
I'm not picking too many. I'll, take them with me. But I wonder if they taste good.

0:02:43.400,0:02:45.580
# 你看  來一趟  是不是
Look! A trip here, isn't it,

0:02:46.920,0:02:48.100
# 收獲滿滿的
fruitful?

0:02:50.260,0:02:51.420
# 還有沒有其它的
Is there anything else?

0:02:51.960,0:02:54.240
# 西瓜他又不種  種西瓜多好啊
He doesn't grow any watermelons. Watermelons would be wonderful.

0:02:55.540,0:02:56.620
# 又可以吃上幾天了
These can feed me in the next few days.

0:02:59.600,0:03:00.520
# 下次再來
Let's come again next time.

0:03:03.020,0:03:05.800
# 現在回來啦  天氣  太熱啦  它這
So now we're back. It's ah, it's too hot now.

0:03:06.640,0:03:07.940
# 把這心挖出來
We scratch out the heart,

0:03:09.160,0:03:10.320
# 把它的心挖出來
scratch out its heart.

0:03:10.920,0:03:12.340
# 然後再把它撕開
And then we spread it open.

0:03:12.740,0:03:13.900
# 這樣就容易洗一點
So that I can wash it more easily.

0:03:14.300,0:03:16.240
# 不然會有小蟲子藏在裡面的
Otherwise, some small bugs might be hiding inside.

0:03:20.400,0:03:21.740
# 鮮黃色的
Golden yellow.

0:03:27.560,0:03:29.280
# 這個壞的  臭的
This one is rotten, and stinky.

0:03:30.480,0:03:32.020
# 壞的就攝影小哥摘的
The rotten ones are all picked by Mr. Cameraman.

0:03:33.420,0:03:36.300
# 你看一條蟲  跟我搶吃的
Look! A bug! Aya, you wanna take the food away from me?

0:03:37.060,0:03:38.200
# 把它洗一下
Let me wash it.

0:03:38.680,0:03:39.700
# 好多花粉
There's a lot of pollen.

0:03:52.780,0:03:53.280
# 好啦
Alright!

0:03:54.660,0:03:56.400
# 拿面粉來  裹上面
Take some flour. Coat it with flo..

0:03:56.920,0:03:58.640
# 面粉  然後用油炸一下
with the flour. And then fry it.

0:04:00.120,0:04:02.680
# 把它撕成一小塊一小塊
Tear it up into small pieces.

0:04:03.220,0:04:04.740
# 太大塊了一下那個
They would cling together if, I mean,

0:04:06.060,0:04:07.060
# 粘在一起
they're in big pieces.

0:04:08.260,0:04:10.440
# 這個撕成小塊是  最好的
So, tearing them up into small pieces, is the best way.

0:04:14.060,0:04:14.980
# 好香啊
It smells so good!

0:04:16.540,0:04:18.240
# 多放點鹽  進到這
Put some salt, into the bowl.

0:04:21.640,0:04:23.960
# 摘一下這個  要不然沒甚味道  (註︰他重覆了一次「要不然」但原字幕沒出現，我翻譯跟著重覆了)
Yea, put some... It would, it would be tasteless otherwise.

0:04:26.220,0:04:27.680
# 鹽怎麼不出來
Why isn't the salt coming out?

0:04:32.100,0:04:32.620
# 可以
Alright!

0:04:39.440,0:04:42.160
# 嗯  拌均勻啦  把這個面粉
Um! It's well stirred now. The flour,

0:04:43.560,0:04:44.620
# 搞一點去
put some here.

0:04:46.280,0:04:48.660
# 這是我們這邊的蕉芋粉  不是面粉哦
It's in fact the Indian shot starch here, not really flour.

0:04:55.420,0:04:56.560
# 加點這個辣椒粉
Put some chilli powder.

0:04:57.300,0:04:57.980
# 搞多一點  (註︰沒有原字幕)
More!

0:04:58.760,0:05:00.640
# 要不然 沒甚麼味道
Otherwise, it wouldn't taste anything.

0:05:01.640,0:05:03.380
# 最近的口味越來越重啦
I'm craving for stronger and stronger tastes recently.

0:05:04.180,0:05:06.200
# 點吃辣椒就沒那重的口味  (註︰不太明白)
Some chilli can reduce a lot of other flavourings.

0:05:10.740,0:05:14.620
# 好啦  搞過去 用油炸一下  就可以出鍋啦
Alright! We take it over there, and fry it. Then that's it.

0:05:18.100,0:05:20.120
# 放顆蛋去  更香一點
Put an egg. The aroma would be more significant.

0:05:28.640,0:05:29.880
# 這樣好看哦
It looks really nice.

0:05:35.600,0:05:36.200
# 好啦
Alright!

0:06:23.320,0:06:25.480
# 它的顏色看起來好鮮豔哦
The colour is so bright and attractive.

0:06:28.460,0:06:29.680
# 看上去就好吃
It looks really tasty.

0:06:33.260,0:06:35.320
# 可以啦  一會就好了
Alright! It doesn't take long.

0:06:43.500,0:06:44.860
# 看上去就好吃
It looks really tasty,

0:06:45.080,0:06:46.380
# 像個燒餅一樣  (註︰不想太多注釋甚麼是燒餅，這不是重點，反正就是金黃色煎炸扁平狀的食品吧)
just like a pancake.

0:06:54.600,0:06:55.340
# 很靚哦
Beautiful!

0:06:56.660,0:06:58.020
# 太燙啦  等一下來吃
It's too hot! I'll enjoy it in a while.

0:07:06.160,0:07:07.900
# 你看  這個油炸好啦
Look! So I've fried them.

0:07:09.100,0:07:10.160
# 看上去就很有食欲
It looks really appetising.

0:07:10.540,0:07:11.600
# 金黃金黃的
Golden yellow

0:07:12.840,0:07:13.520
# 嗯
Um~

0:07:15.660,0:07:17.440
# 很不錯哦 好香啊
It's really not bad. It smells so good!

0:07:18.820,0:07:21.100
# 你看  香味把小狗都吹過來啦
Look! The smell is bringing the doggies here.

0:07:22.500,0:07:24.160
# 這是素食  沒肉的
It's veggie. There's no meat.

0:07:24.420,0:07:25.160
# 你不要的
You don't like it.

0:07:26.480,0:07:28.940
# 這個不知道甚味道  沒吃過
It's ah... How should I describe the taste? It's new to me.

0:07:29.460,0:07:30.260
# 吃起來就是
It's like,

0:07:31.380,0:07:32.100
# 很香
it smells good.

0:07:37.360,0:07:39.420
# 嗯  雞蛋味
Um! There's the taste of eggs,

0:07:41.160,0:07:42.320
# 也有攀蒲花的味
and of pumpkin flowers as well,

0:07:43.840,0:07:44.640
# 還有油味
and of oil too.

0:07:46.740,0:07:48.400
# 給一塊給你吃  看你要不要
I give you one. See if you like it.

0:07:49.600,0:07:50.460
# 好不好吃
Does it taste good?

0:07:53.360,0:07:54.900
# 可以哦  這小狗會吃哦
Not bad. This doggy eats it.

0:07:59.320,0:08:00.620
# 嗯  那條就不吃
Um! That one is not eating.

0:08:02.140,0:08:03.360
# 那條狗不是好狗
That dog is not a good dog.

0:08:09.060,0:08:09.960
# 你也不吃
You don't like it neither.

0:08:11.160,0:08:12.540
# 就小黑吃  來
Nobody likes it but Blacky. C'mon!

0:08:13.840,0:08:14.500
# 小黑 來
Blacky, c'mon!

0:08:16.380,0:08:17.580
# 它會接的哦  這狗
She can catch the food, this dog, you know.

0:08:21.720,0:08:22.480
# 還想不想吃
You want more?

0:08:24.020,0:08:24.940
# 小黑懷孕了
Blacky is pregnant.

0:08:26.540,0:08:27.460
# 肚子那麼大
Her belly is so big now.

0:08:27.460,0:08:29.940
# 好啦  今天的視頻到這裡啦
Alright! The video ends here.

0:08:31.800,0:08:32.840
# 準備吃午飯了
It's lunch time now.
