### ISSUE TITLE
[华农兄弟] 华农兄弟今天天气很好约兄弟去钓鱼钓得鱼炸起来就是香 - https://youtu.be/jCSskEWPk_o

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1205]
https://youtu.be/jCSskEWPk_o
<p>&#35270;&#39057;&#21457;&#24067;&#20110; June 25, 2020 at 11:51AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/jCSskEWPk_o

#华农兄弟：今天天气很好，约兄弟去钓鱼，钓得鱼炸起来就是香
#Huanong Bothers: The weather is really nice today. We go fishing with our buddy. Fried fish is always nice!

0:00:00.000,0:00:02.780
# 今天不會下雨 而且天很晴的哦
It's not gonna rain today. And it will a beautiful sunny day, you know.

0:00:03.340,0:00:06.480
# 很適合釣魚  兄弟  去挖點蚯蚓  等下我們去釣魚
It's a good day for fishing. Buddy! Go and dig some earthworms. Let's go fishing in a while.

0:00:07.460,0:00:08.280
# 好啊  可以
Sure! Good idea!

0:00:08.800,0:00:12.260
# 去那邊  那邊好多  我去  我去找一下那個魚竿
Over there. There are a lot. Let me, let me find the, I mean, the fishing rod.

0:00:14.820,0:00:16.080
# 你看  這裡有一個魚竿哦
Look! Here's fishing rod.

0:00:17.000,0:00:17.800
# 不知道是誰的
Who knows whose it is.

0:00:18.800,0:00:20.720
# 竟然想釣我家池塘裡面的魚
Somebody dares to catch the fish in my pond.

0:00:21.660,0:00:22.460
# 沒收了
It's confiscated.

0:00:23.060,0:00:23.840
# 剛好用這個
Perfect timing. I can,

0:00:24.720,0:00:26.240
# 這個魚竿去釣魚就行了
I can use it for our fishing today.

0:00:28.280,0:00:29.260
# 兄弟  有沒有挖到
Buddy! Any earthworms?

0:00:29.460,0:00:30.100
# 很多啊
A lot

0:00:30.380,0:00:30.880
# 很多
A lot?

0:00:31.100,0:00:32.160
# 對呀  過來過來過來
Yea! Come here, come here, come here.

0:00:32.320,0:00:33.600
# 抓幾個就夠了 不要那麼多
A couple of them is enough, not too many

0:00:35.600,0:00:36.540
# 哎呀  太多了
Aya! It's too many!

0:00:40.440,0:00:41.260
# 抓起來
Catch them!

0:00:41.880,0:00:42.700
# 等一下來嘛
A moment

0:00:48.320,0:00:49.220
# 夠了  夠了
Enough, enough

0:00:51.340,0:00:52.100
# 夠了  夠了
Enough, enough

0:00:52.620,0:00:53.180
# 夠了
Enough

0:00:54.620,0:00:58.420
# 你看  桶又沒找到  找了一個鍋  這個鍋也可以裝魚的
Look! The bucket is no where to be found. Here's a pot. It can carry fish too.

0:00:59.400,0:01:00.360
# 去  去河邊釣
Let's go, to the riverside.

0:01:01.140,0:01:02.540
# 我們這邊很多魚釣的哦
There are of fish here at our place, you know.

0:01:04.380,0:01:05.680
# 河裡面的魚都是我放的  (註︰這個「都」字有「這些魚都是我的」的暗示，英文沒法表達出來，只有明示算了)
These are my fish. I put them into the river.

0:01:16.540,0:01:19.140
# 你看  上次我們抽水的時候看到有條大魚
Look! I saw a big fish when we were pluming out the water last time.

0:01:19.400,0:01:23.100
# 沒抓到  現在我拿魚鈎來  把它  看能不能把它勾起來
But we couldn't catch them. So I'm now coming with a hook. I'm gonna... Let's see if I can catch it.

0:01:24.140,0:01:25.240
# 看誰先釣到哦
Let's see who's gonna catch the first fish,

0:01:25.880,0:01:26.840
# 看誰先釣到
who's gonna catch the first fish.

0:01:34.680,0:01:36.100
# 這裡很多魚的哦  這裡
Here's a lot of fish, here.

0:02:12.880,0:02:14.120
# 咬啦  咬啦  快點 快點
It's biting, it's biting! C'mon, c'mon!

0:02:14.480,0:02:15.160
# 哪個 你的
Which one?
Yours

0:02:15.520,0:02:17.020
# 我的  已經在這裡來啦
Mine?
It's already here.

0:02:19.140,0:02:19.840
# 是不是
Are you sure?

0:02:20.020,0:02:20.560
# 等會 等會
A moment, a moment!

0:02:20.940,0:02:23.440
# 我把我的先拿走  不要  搞掉了
Let me take away mine first. I don't wanna, drop it.

0:02:24.860,0:02:26.080
# 哎呦  好像是咬了哦
Ayo! Seems that it's biting.

0:02:29.080,0:02:30.320
# 誒 是不是
Ey? Is it,

0:02:30.540,0:02:32.300
# 勾到草去了  勾到草上去了
getting hooked onto the grass, hooked onto the grass?

0:02:34.680,0:02:36.400
# 我看到它是從那邊過來
I saw it coming here from that side.

0:02:39.240,0:02:40.060
# 拉不過來
I can't pull it to me.

0:02:40.380,0:02:41.080
# 我來幫你弄
Let me give you a hand.

0:02:41.820,0:02:42.440
# 小心點哦
Be careful!

0:02:43.200,0:02:45.220
# 是魚  是魚  看到沒有  浮起來啦  看到沒有
It's a fish, really a fish! See? It's floating, see?

0:02:45.860,0:02:46.580
# 我沒看到
I can't see anything.

0:02:46.720,0:02:48.260
# 那不是嗎  浮起來了
Isn't that one a fish? It's floating.

0:02:49.740,0:02:51.080
# 拉綫啊  拉綫
Pull the line, pull it!

0:02:52.240,0:02:53.940
# 拉綫  扯不過來
Pull the line! It doesn't work.

0:02:55.340,0:02:56.100
# 來啦  來啦  來啦
It's coming, it's coming, it's coming!

0:02:56.300,0:02:57.180
# 誒呦  一條鯉魚
Eyo! It's a carp.

0:03:02.420,0:03:03.300
# 快點  別跑啦
Hurry up! Don't it be run away.

0:03:03.540,0:03:04.520
# 這裡這裡這裡  找到啦
Here, here, here. I got it.

0:03:05.440,0:03:08.020
# 你看  這條  小鯉魚
Look! It's a, small carp.

0:03:08.240,0:03:08.940
# 裝好水啦
I've filled the water.

0:03:09.580,0:03:11.260
# 別搞那麼多哦  等下抬不回去
Don't get too much water. You won't be able to take it back.

0:03:11.660,0:03:12.260
# 抬得回
Yes, I can.

0:03:14.740,0:03:15.740
# 哎呀  挺漂亮的
Aya! It's rather pretty.

0:03:16.880,0:03:19.420
# 回家啦回家啦  一條夠吃啦  不要那麼多
Let's go, let's go. One is enough for us. We don't need too many.

0:03:24.360,0:03:25.740
# 可以  你的技術比我的好
Not bad. You're more skilful than me.

0:03:26.540,0:03:27.460
# 收工  收工
Go, go, go!

0:03:29.320,0:03:31.360
# 這魚竿 收回去
This fishing rod. Let's take it back.

0:03:33.360,0:03:34.300
# 一人抬一個
Let's take one handle each.

0:04:10.280,0:04:11.340
# 這個刀老是
This knife is always,

0:04:11.840,0:04:13.000
# 很快就鈍掉了
it gets blunt very soon.

0:04:15.400,0:04:17.760
# 你看  兄弟 今天要吃你的
Look! Buddy, you'll be our meal today.

0:04:20.900,0:04:22.020
# 這是公的  這個魚
It's male, this fish.

0:04:23.460,0:04:25.000
# 哎呀  不好意思啊
Aya! I'm sorry.

0:04:32.000,0:04:33.420
# 我都還沒吃  你們想吃
Don't think of eating before me!

0:04:34.680,0:04:36.320
# 慢慢來  後面排隊
Not now, a moment. Line up behind me.

0:04:39.100,0:04:40.040
# 我要打點花
I'm gonna slice it a few times.

0:04:44.200,0:04:45.400
# 更入味哦  這樣就
It would be, more flavourful.

0:04:47.400,0:04:49.940
# 好啦  可以啦  不要割那麼多花
Alright! It's fine now. Not too many times.

0:04:51.040,0:04:52.180
# 割的差不多就行了
It's fine when it's enough.

0:04:56.840,0:04:58.320
# 這裡有一根筋的  這裡
Here's a tendon, here.

0:05:00.020,0:05:02.040
# 找不到  管它  就這樣吃
Can't find it. Never mind. Forget it!

0:05:04.820,0:05:06.580
# 好啦  我拿個盆子把它腌一下
Alright! I'm gonna get a pot and marinate it for a while.

0:05:06.980,0:05:08.760
# 腌一下就  下油鍋啦
Marinate it, and then, fry it.

0:05:12.060,0:05:13.680
# 誒呦  還想跑
Eyo! You still wanna run away?

0:05:18.920,0:05:19.960
# 加點鹽
Put some salt

0:05:21.260,0:05:22.280
# 鹽都結塊了
The salt is clumping.

0:05:23.380,0:05:24.080
# 好了  夠了
Alright. It's enough.

0:05:24.760,0:05:25.860
# 不下那麼多鹽
Not too much salt

0:05:26.660,0:05:27.640
# 加點料酒
Put some cooking wine

0:05:28.760,0:05:29.960
# 黑呦 沒啦
Heyo! No more?

0:05:32.040,0:05:32.900
# 加點油
Put some oil

0:05:38.780,0:05:41.160
# 加點油  讓它肌膚更滑
Put some oil, so that it has a smoother skin.

0:05:42.340,0:05:44.760
# 加點薑  去它的腥味
Put some ginger, to get rid of the fishy smell,

0:05:45.320,0:05:47.600
# 去它的腥味  加點醬油
get rid of the fishy smell. Put some soy sauce,

0:05:49.060,0:05:50.180
# 讓它更美味
so that it tastes even better.

0:05:51.900,0:05:52.480
# 好啦
Alright!

0:05:53.960,0:05:55.000
# 給你按一下摩
Give you a massage.

0:06:01.300,0:06:02.820
# 肚子上搞點生薑下去 (註︰他應該是說搞點生薑「給你」)
Put some ginger into your belly.

0:06:04.020,0:06:06.860
# 生薑生薑  從肚子裡面生出來的薑  (註︰這兩個騷話太難了，若有更好的翻譯，請建議)
Ginger, ginger, from the belly it was born and there it has its oriGIN,

0:06:08.000,0:06:08.980
# 叫生薑
that's why it's called GINger.

0:06:10.440,0:06:12.080
# 嘴巴上也塞一兩塊給你
Let me stuff some ginger into your mouth,

0:06:16.180,0:06:17.760
# 去下你的口臭
to get rid of your bad breath.

0:06:23.680,0:06:25.280
# 嗯  搓兩下
Um! Rub it over

0:06:32.500,0:06:34.380
# 好啦  腌個半個小時
Alright! Marinate it for half an hour,

0:06:35.340,0:06:36.120
# 直接
then,

0:06:36.720,0:06:37.640
# 下油鍋啦
fry it right away.

0:06:39.620,0:06:41.560
# 搞點油來  搞多一點
Put some oil, more oil

0:06:47.600,0:06:48.160
# 可以
Alright!

0:06:53.420,0:06:54.260
# 這條魚
This fish...

0:07:18.900,0:07:21.160
# 這個魚炸的  炸到它尾巴都斷啦
The fish, its tail has come off.

0:07:22.820,0:07:23.900
# 拿它尾巴
Let me take the tail.

0:07:26.300,0:07:27.540
# 肯定很香的哦
I'm sure that it's nice.

0:07:27.840,0:07:28.800
# 唉呦  好燙啊
Eyo! It's burning hot!

0:07:32.860,0:07:33.580
# 嗯~
Um~

0:07:35.120,0:07:35.840
# 很好吃哦
It's really tasty!

0:07:44.280,0:07:45.180
# 應該快熟啦
It should be done very soon.

0:07:49.880,0:07:50.820
# 把它撩起來
Let me scoop it up.

0:07:51.900,0:07:52.860
# 已經熟透啦
It's well done now.

0:08:03.260,0:08:03.960
# 好靚
Beautiful!

0:08:04.840,0:08:05.820
# 尾巴被我吃掉啦
I've already eaten the tail.

0:08:06.240,0:08:08.220
# 等一下  叫兄弟一起來吃
I'm gonna, ask my buddy to enjoy it with me.

0:08:09.180,0:08:10.280
# 你看  這個魚可以吧
Look! This fish is quite good, isn't it?

0:08:11.260,0:08:12.020
# 還不錯
Not bad

0:08:12.320,0:08:13.220
# 原生態的
It's natural and organic.

0:08:15.600,0:08:16.440
# 來來來
C'mon, c'mon, c'mon!

0:08:17.820,0:08:18.480
# 太燙啦
It's too hot!

0:08:19.460,0:08:20.820
# 小黑  來來來來
Blacky! C'mon, c'mon! Here, here!

0:08:22.440,0:08:23.480
# 趴到你身上去
She's gonna hop on you.

0:08:28.360,0:08:32.040
# 老是  老是弄我家的魚  手藝  手藝都變好了
You're, you're a much better cook now, after endless, endless practice using my fish.

0:08:32.600,0:08:34.900
# 拿你家的  魚來練手藝
I practise, using your, your fish.

0:08:35.880,0:08:38.600
# 下次  下次  你家  你
Next time, next time, your, your,

0:08:38.760,0:08:40.700
# 你家那個鵝可以拿來烤一下嘛
can we grill one of your geese?

0:08:41.020,0:08:41.580
# 可以
Sure!

0:08:42.440,0:08:42.940
# 好吃哦
Good, isn't it?

0:08:43.560,0:08:44.620
# 是好吃啊  特別香
Indeed.
It smells exceptionally good.

0:08:48.300,0:08:49.720
# 就是太燙了 你知道吧
It's just too hot, you know.

0:08:49.820,0:08:50.320
# 沒事
No worries

0:08:56.760,0:08:58.180
# 啊 太燙啦
Ah! It's too hot!

0:09:00.420,0:09:02.600
# 好啦  今天的視頻到這裡啦
Alright! The video ends here.

0:09:07.800,0:09:09.500
# 還有個魚頭  給你
Here's still a fish head. It's yours.
