### ISSUE TITLE
【美食作家王刚】上棚包梨子 - https://youtu.be/qZWkbAnOiWA

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1207]
**视频链接**：https://youtu.be/qZWkbAnOiWA

视频时长6:28，预计发布时间为北京时间6月28日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
老家的梨树结了非常多果子，决定上棚用纸袋包起来防止鸟儿来偷吃

简介
大家如果之前看过我做户外厨房和搭棚子的视频就知道特地留下了这颗梨树，当时就说等梨子长大些就爬上来装袋，因为梨大了变甜了之后非常容易被鸟吃掉。上到棚上发现不少树枝因为结了梨被压下来了，梨碰到棚子就烂掉了，不知道大家有没有什么好办法可以解决这个问题？暂时就拿了些竹子把树枝撑起来，希望能有些帮助，很期待再过段时间梨的收获！

字幕
0:00:00.025,0:00:01.025
哈喽 大家好

0:00:01.105,0:00:03.872
今天我要上去弄一下上面的竹叶

0:00:04.171,0:00:08.790
然后再把我们那个梨 已经这么大了用纸包起来

0:00:09.218,0:00:11.976
要不然那些小鸟几下就给它吃掉了

0:00:23.066,0:00:24.310
第一次上去还多害怕

0:00:24.310,0:00:25.276
扫不扫哦

0:00:26.082,0:00:27.078
要扫

0:00:29.148,0:00:31.348
既然上去了肯定要扫了

0:00:36.973,0:00:38.934
吓我一跳 差点滑了

0:00:39.472,0:00:43.812
现在终于上来了 用我四伯爷给我的这个袋子

0:00:44.181,0:00:45.624
然后把这个梨全部套起来

0:00:46.550,0:00:49.268
这个鸟啊 梨小的时候它不吃

0:00:49.397,0:00:52.931
就是专门等到它长到半大不熟的时候吃得干干净净的

0:00:53.877,0:00:56.207
上都上来了然后我先把这个竹叶扫一下

0:00:56.884,0:00:59.233
这个竹叶太多了

0:01:29.069,0:01:32.444
打击看一下这个梨 这个已经很大个了

0:01:34.474,0:01:36.117
已经这么大了

0:01:37.222,0:01:39.382
这现在就是小鸟要吃的时候了

0:01:40.149,0:01:42.757
这个已经被梨压下来了 等一下我用一个（袋子）

0:01:45.943,0:01:46.650
掉了一个

0:01:48.232,0:01:49.517
都已经这么大太可惜了

0:01:49.785,0:01:50.960
待会儿用个东西把它撑起来

0:01:52.782,0:01:54.634
这个掉在上面已经烂了这个

0:01:56.137,0:01:57.162
太可惜了

0:01:58.705,0:01:59.522
这个都已经烂了

0:02:00.209,0:02:02.010
梨太多了把这个压垮了

0:02:25.564,0:02:28.123
废了九牛二虎之力把这个上面又扫了

0:02:28.143,0:02:30.960
我估计十天半个月之后又是一层

0:02:31.169,0:02:32.742
现在我来包一下这个梨

0:02:33.180,0:02:36.107
有没有懂行的 来教我一下

0:02:42.389,0:02:42.996
这个位置

0:02:47.396,0:02:48.531
嗯 可以了

0:02:48.810,0:02:50.462
有没有懂行的教我一下这个怎么弄

0:02:52.334,0:02:54.285
在我没学会之前先让它这样子吧

0:03:01.413,0:03:03.484
这个撑哪里 撑这里差不多

0:03:06.421,0:03:06.779
可以

0:03:11.956,0:03:13.578
这边再给它撑一个就差不多了

0:03:15.052,0:03:15.291
好

0:03:16.764,0:03:18.795
这个给它打开

0:03:22.608,0:03:25.216
这给它打开 然后把这个果子放进去

0:03:28.461,0:03:32.234
然后这样子收这个 收收收

0:03:33.389,0:03:35.002
收到这里的时候这有一根铁丝

0:03:35.470,0:03:39.920
把它这样子捆起来捏紧就可以了 特别简单

0:03:41.582,0:03:47.536
一次装它两个 让它们有伴 稍微捏一下就可以了

0:03:48.521,0:03:52.374
这样鸟儿就不知道里面有梨 它就吃不到了

0:03:53.668,0:03:54.275
这里还有

0:03:54.783,0:03:58.845
大家可以看一下这里上面有2个 这就是被鸟儿吃掉的

0:03:59.163,0:04:03.026
可能说这个鸟儿想留着下一次来吃其它的

0:04:03.822,0:04:04.728
我这次就把它包起来

0:04:06.600,0:04:09.009
哇这个上面 一枝上面结4个

0:04:10.144,0:04:11.408
这个你搞得我好为难啊

0:04:12.682,0:04:13.429
我这么接呢

0:04:15.022,0:04:17.650
它们4个包在一起 4兄弟很棒

0:04:18.725,0:04:20.826
去年这个（树）上面都只长了几个

0:04:21.612,0:04:23.494
刚好要吃的时候就被鸟吃了

0:04:24.519,0:04:25.793
今年给它保护一下

0:04:31.956,0:04:33.718
这个是掉在那个（雨棚）上面 

0:04:34.086,0:04:39.900
被掉下来的竹叶捂在一起捂烂了 太可惜了丢掉

0:04:42.220,0:04:43.474
把这个没烂的也包一下

0:04:46.689,0:04:47.227
OK

0:04:48.272,0:04:51.209
这边可能它会烂就留点给鸟吃

0:04:58.795,0:05:00.169
这几个特别漂亮

0:05:02.588,0:05:03.394
先包这两个

0:05:11.607,0:05:13.340
然后再包这两个

0:05:21.911,0:05:23.165
哟 还包不住它啊

0:05:25.774,0:05:26.530
OK 可以了

0:05:28.760,0:05:30.950
好 那些包不到的不整了 不关事

0:05:31.319,0:05:33.499
那儿不好弄得 我逮要把它逮下来

0:05:44.161,0:05:45.206
我看一下拉不拉得下来

0:05:54.295,0:05:55.679
我四伯爷说的就这三个

0:06:03.504,0:06:06.042
哎呦 包的不是很好 希望鸟吃不到

0:06:08.561,0:06:10.482
看一下 我给你们看一下这个被鸟吃掉的

0:06:12.145,0:06:15.560
看到没这个给它吃空了

0:06:16.545,0:06:17.481
这边是很好看的

0:06:18.148,0:06:18.656
浪费

0:06:20.099,0:06:22.070
好 本期视频就到这里 拜拜

0:06:22.239,0:06:22.847
我要下去了


```

**Comment by immoonancient** [comment]
@iamatrollatrollisme 请前来认领

**Comment by iamatrollatrollisme** [comment]
认领

**Comment by iamatrollatrollisme** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
老家的梨树结了非常多果子，决定上棚用纸袋包起来防止鸟儿来偷吃
Pear tree in hometown grew many pears, cover them up to prevent bird thieves

简介
大家如果之前看过我做户外厨房和搭棚子的视频就知道特地留下了这颗梨树，当时就说等梨子长大些就爬上来装袋，因为梨大了变甜了之后非常容易被鸟吃掉。上到棚上发现不少树枝因为结了梨被压下来了，梨碰到棚子就烂掉了，不知道大家有没有什么好办法可以解决这个问题？暂时就拿了些竹子把树枝撑起来，希望能有些帮助，很期待再过段时间梨的收获！

If you have seen my videos about outdoor kitchen and the shed, you would know I purposely kept the pear tree, I said that when the pears grow bigger, we will come up here to cover them up with bags. Because when pears get ripe, they become very sweet. Then they will attract birds to come eat them. When I get up on the roof of the shed, I found that many branches cannot carry the weight of the pears and got pulled down, when pears touched the roof of the shed, they will rot. I wonder if you have a good solution to solve this? For now, I am holding the branches up with some bamboo, hope it helps. I am very looking forward to the harvest of pears later. 

字幕
0:00:00.025,0:00:01.025
哈喽 大家好
Hello everyone.

0:00:01.105,0:00:03.872
今天我要上去弄一下上面的竹叶
Today I am going up there to clean up the bamboo leaves

0:00:04.171,0:00:08.790
然后再把我们那个梨 已经这么大了用纸包起来
And then take our pears, they are like this big now, I am covering them up with paper bags.

0:00:09.218,0:00:11.976
要不然那些小鸟几下就给它吃掉了
Otherwise the birds will eat the pears very quickly.

0:00:23.066,0:00:24.310
第一次上去还多害怕
I was a little scared the first time I climbed up here.

0:00:24.310,0:00:25.276
扫不扫哦
Are we sweeping the roof?

0:00:26.082,0:00:27.078
要扫
Yes.

0:00:29.148,0:00:31.348
既然上去了肯定要扫了
Of course, he is sweeping it, he climbed up there after all.

0:00:36.973,0:00:38.934
吓我一跳 差点滑了
I almost slipped and got scared a little.

0:00:39.472,0:00:43.812
现在终于上来了 用我四伯爷给我的这个袋子
Now that I am up here, using the bags my uncle gave me,

0:00:44.181,0:00:45.624
然后把这个梨全部套起来
To cover all the pears.

0:00:46.550,0:00:49.268
这个鸟啊 梨小的时候它不吃
These birds do not eat the pears when they are small.

0:00:49.397,0:00:52.931
就是专门等到它长到半大不熟的时候吃得干干净净的
Birds purposely wait until the pears grow half way through, then they will eat all the pears.

0:00:53.877,0:00:56.207
上都上来了然后我先把这个竹叶扫一下
Since I am up here, I am going to sweep the bamboo leaves.

0:00:56.884,0:00:59.233
这个竹叶太多了
There are too many bamboo leaves up here.

0:01:29.069,0:01:32.444
打击看一下这个梨 这个已经很大个了
Take a look at this pear, it is pretty big now.

0:01:34.474,0:01:36.117
已经这么大了
It has grown a lot.

0:01:37.222,0:01:39.382
这现在就是小鸟要吃的时候了
This is the time when birds are going to eat the pears.

0:01:40.149,0:01:42.757
这个已经被梨压下来了 等一下我用一个（袋子）
Now the weight of the pears is pulling the branch down, I am going to use (a bag to collect them)

0:01:45.943,0:01:46.650
掉了一个
One fell off

0:01:48.232,0:01:49.517
都已经这么大太可惜了
It grew pretty big, what a pity. 

0:01:49.785,0:01:50.960
待会儿用个东西把它撑起来
I am going to find something up hold it up.

0:01:52.782,0:01:54.634
这个掉在上面已经烂了这个
When it fell, it got rotten on the roof.

0:01:56.137,0:01:57.162
太可惜了
Such a waste.

0:01:58.705,0:01:59.522
这个都已经烂了
This one rotted.

0:02:00.209,0:02:02.010
梨太多了把这个压垮了
There are too many pears up here and the weight is holding down the branches.

0:02:25.564,0:02:28.123
废了九牛二虎之力把这个上面又扫了
It took so much effort to sweep the roof again.

0:02:28.143,0:02:30.960
我估计十天半个月之后又是一层
I think after a couple of weeks later it will be full of bamboo leaves again.

0:02:31.169,0:02:32.742
现在我来包一下这个梨
Now I am going to cover the pears.

0:02:33.180,0:02:36.107
有没有懂行的 来教我一下
Is there any expert, can you teach me a little?

0:02:42.389,0:02:42.996
这个位置
Put it here?

0:02:47.396,0:02:48.531
嗯 可以了
Yes, sure.

0:02:48.810,0:02:50.462
有没有懂行的教我一下这个怎么弄
Is there any expert, please teach me how to do this?

0:02:52.334,0:02:54.285
在我没学会之前先让它这样子吧
Before I learned how to handle it, I will just leave it like this.

0:03:01.413,0:03:03.484
这个撑哪里 撑这里差不多
Where do I put this one? Should I put it here?

0:03:06.421,0:03:06.779
可以
Okay this is good.

0:03:11.956,0:03:13.578
这边再给它撑一个就差不多了
Then I will put another one here, it should fine now.

0:03:15.052,0:03:15.291
好
Okay

0:03:16.764,0:03:18.795
这个给它打开
Now I am opening this bag.

0:03:22.608,0:03:25.216
这给它打开 然后把这个果子放进去
Open the bag then put the pear into the bag.

0:03:28.461,0:03:32.234
然后这样子收这个 收收收
And then wrap it up and pinch together the edges.

0:03:33.389,0:03:35.002
收到这里的时候这有一根铁丝
At the end I will tie it up with iron wire.

0:03:35.470,0:03:39.920
把它这样子捆起来捏紧就可以了 特别简单
Wrap up the edge and pinch the wire, then I am done. Very simple. 

0:03:41.582,0:03:47.536
一次装它两个 让它们有伴 稍微捏一下就可以了
I am bagging these two together, so they can keep each other company, just slightly pinch it. 

0:03:48.521,0:03:52.374
这样鸟儿就不知道里面有梨 它就吃不到了
This way, the birds do not know there are pears in there, they cannot eat them

0:03:53.668,0:03:54.275
这里还有
There are more here.

0:03:54.783,0:03:58.845
大家可以看一下这里上面有2个 这就是被鸟儿吃掉的
Let take a look at the two up there, the birds ate them. 

0:03:59.163,0:04:03.026
可能说这个鸟儿想留着下一次来吃其它的
May the birds want to come back and eat other pears.

0:04:03.822,0:04:04.728
我这次就把它包起来
But I will cover the pears this time.

0:04:06.600,0:04:09.009
哇这个上面 一枝上面结4个
Wow there are 4 pears on this branch.

0:04:10.144,0:04:11.408
这个你搞得我好为难啊
What should I do with it?

0:04:12.682,0:04:13.429
我这么接呢
How do I cover it?

0:04:15.022,0:04:17.650
它们4个包在一起 4兄弟很棒
I will jut bag four of them together, four siblings, very nice.

0:04:18.725,0:04:20.826
去年这个（树）上面都只长了几个
Last year, this(tree) only had a few pears.

0:04:21.612,0:04:23.494
刚好要吃的时候就被鸟吃了
Birds ate most of the pears when they were about to ripe.

0:04:24.519,0:04:25.793
今年给它保护一下
This year I am providing protection for the pears.

0:04:31.956,0:04:33.718
这个是掉在那个（雨棚）上面 
This one fell on top of that(shed).

0:04:34.086,0:04:39.900
被掉下来的竹叶捂在一起捂烂了 太可惜了丢掉
These pears were covered by the bamboo leaves fallen from trees and got rotten, I have to throw them away, what a waste.

0:04:42.220,0:04:43.474
把这个没烂的也包一下
I am going to cover this one that is not rotten.

0:04:46.689,0:04:47.227
OK
Okay

0:04:48.272,0:04:51.209
这边可能它会烂就留点给鸟吃
If it is partially rotten, then I will just leave it to birds.

0:04:58.795,0:05:00.169
这几个特别漂亮
These pears look very nice.

0:05:02.588,0:05:03.394
先包这两个
I am covering these two.

0:05:11.607,0:05:13.340
然后再包这两个
Then covering these two.

0:05:21.911,0:05:23.165
哟 还包不住它啊
Oops, it does not fit the pear.

0:05:25.774,0:05:26.530
OK 可以了
Okay, this is good.

0:05:28.760,0:05:30.950
好 那些包不到的不整了 不关事
The ones are too far to reach, you do not need to cover them.

0:05:31.319,0:05:33.499
那儿不好弄得 我逮要把它逮下来
It is not easy to reach the, I will try to pull them down.

0:05:44.161,0:05:45.206
我看一下拉不拉得下来
Let me see if I can get it down.

0:05:54.295,0:05:55.679
我四伯爷说的就这三个
These are the three my uncle was talking about.

0:06:03.504,0:06:06.042
哎呦 包的不是很好 希望鸟吃不到
I did not cover it well so I hope the birds cannot reach it.

0:06:08.561,0:06:10.482
看一下 我给你们看一下这个被鸟吃掉的
Here, let me show you the one that got eaten by the birds.

0:06:12.145,0:06:15.560
看到没这个给它吃空了
Can you the inside is hollow, all eaten by the birds.

0:06:16.545,0:06:17.481
这边是很好看的
On this side, it looks nice. 

0:06:18.148,0:06:18.656
浪费
Wasteful

0:06:20.099,0:06:22.070
好 本期视频就到这里 拜拜
Okay this is the end of the video, bye bye.

0:06:22.239,0:06:22.847
我要下去了
I am going down now.
