### ISSUE TITLE
[手工耿] 不銹鋼口罩 - https://youtu.be/2fBwZjsnhBQ

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1208]
https://youtu.be/2fBwZjsnhBQ
<p>&#35270;&#39057;&#21457;&#24067;&#20110; June 25, 2020 at 08:00PM</p>
<p>&#26631;&#39064;<br>
手工耿自製目錄——<br>
1、不鏽鋼口罩<br>
2、手機散熱器<br>
<br>
—— 別人笑我太瘋癲，笑完瘋癲笑我閑。<br>
大家好，我是手工耿，如果你喜歡我的視頻，歡迎點擊訂閱。</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/113772413d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by WuStevenShengyang** [comment]
0:00:02.560,0:00:05.020
最近我们这口罩不是特别好买
Recently, it has been difficult to buy masks in our region.

0:00:05.140,0:00:07.580
所以说自己准备做一个
So, I decided to make one for myself.

0:01:40.595,0:01:42.945
这个铁口罩，已经做完了
This iron mask is finished.

0:01:43.425,0:01:45.025
这是全封闭式的
This mask is fully sealed.

0:01:45.480,0:01:47.160
通气的来源
The venting 

0:01:47.160,0:01:49.460
是我身后的这个小氧气瓶
comes from this oxygen bottle.

0:01:49.960,0:01:52.400
美观而又方便
It is both convenient and aesthetic.

0:01:52.580,0:01:53.700
可以随身携带
And it is portable.

0:01:54.680,0:01:57.780
下面我们用烟雾测试一下它的封闭性
Let's use smoke to test out its sealing abiltiy.

0:01:58.720,0:02:01.180
可以看出我在烟雾中挺淡定
See, I look quite calm in the smoke.

0:02:02.160,0:02:03.440
烟雾越来越浓
As the smoke gets strong,

0:02:03.580,0:02:05.580
但是我依然这么淡定
I still remain calm.

0:02:05.740,0:02:07.740
连声咳嗽都没有咳嗽
I didn't even cough.

0:02:08.600,0:02:12.320
这足以证明，它的封闭性是非常的强的
This is enough to prove how sealed this mask is.

0:02:12.680,0:02:17.340
有了这个铁口罩，我们就可以减少粉尘和细菌的危害
With this mask, we can reduce the harm caused by dust and bacteria.

0:02:19.600,0:02:21.100
老弟玩游戏的时候
When my younger brother was playing video games,

0:02:21.100,0:02:22.380
手机发热比较严重
his phone gets hot quite seriously.

0:02:22.540,0:02:24.880
所以我准备给老弟做一个手机散热器
So I have decided to make a cooling device for him.

0:03:45.165,0:03:47.165
下面为大家演示一下这个怎么用
Let me show you how to use this.

0:03:47.165,0:03:49.965
首先把手机放在这个上面来
First, we need to put our phone on top.

0:03:50.115,0:03:52.295
把这个肩键安装上
And put those two buttons on.

0:03:59.435,0:04:00.745
然后
Then,

0:04:01.525,0:04:03.905
打开开关
open the switch.

0:04:07.880,0:04:11.000
安装到背部
And put this on the back.

0:04:18.365,0:04:21.485
然后把循环泵也插上
Finally, we will plug in the pump.

0:04:23.125,0:04:26.335
加上水的冷却，加上风冷
With both water cooling and wind cooling,

0:04:26.335,0:04:28.705
这样我们玩手机的时候
his phone

0:04:29.775,0:04:32.225
就不会
won't

0:04:32.225,0:04:33.865
手机就不会发烫了
get hot when playing video games.

0:04:35.675,0:04:38.295
下面我让老弟体验一下效果怎么样
Now, I will let my brother try this new cooling device.

0:04:59.260,0:05:00.700
用的怎么样，老弟？
How is it?

0:05:00.700,0:05:02.500
感觉不错，非常完美
It's perfect!
