### ISSUE TITLE
【美食作家王刚】包梨+发电机 - https://youtu.be/CMl6BOx-1sE

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1217]
**视频链接**：https://youtu.be/CMl6BOx-1sE

视频时长10:02，预计发布时间为北京时间6月30日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
把老家梨树结的果子包起来防止鸟儿来偷吃！偶遇停电怎么办？居然还能继续剪视频！

简介
大家如果之前看过我做户外厨房和搭棚子的视频就知道特地留下了这颗梨树，当时就说等梨子长大些就爬上来装袋，因为梨大了变甜了之后非常容易被鸟吃掉。上到棚上发现不少树枝因为结了梨被压下来了，梨碰到棚子就烂掉了，不知道大家有没有什么好办法可以解决这个问题？暂时就拿了些竹子把树枝撑起来，希望能有些帮助，很期待再过段时间梨的收获！富顺偶遇停电，打乱了拍摄计划，不过想到之前放在老家了一台发电机，这次居然用上了，不过带不起来空调，还是有些难受。最近由于忙新工作室和拍摄方面的升级，所以比较少拍做菜教学的视频，请大家谅解，硬核教学很快就会回归！

字幕
0:00:00.025,0:00:01.025
哈喽 大家好

0:00:01.105,0:00:03.872
今天我要上去弄一下上面的竹叶

0:00:04.171,0:00:08.790
然后再把我们那个梨 已经这么大了用纸包起来

0:00:09.218,0:00:11.976
要不然那些小鸟几下就给它吃掉了

0:00:23.066,0:00:24.310
第一次上去还多害怕

0:00:24.310,0:00:25.276
扫不扫哦

0:00:26.082,0:00:27.078
要扫

0:00:29.148,0:00:31.348
既然上去了肯定要扫了

0:00:36.973,0:00:38.934
吓我一跳 差点滑了

0:00:39.472,0:00:43.812
现在终于上来了 用我四伯爷给我的这个袋子

0:00:44.181,0:00:45.624
然后把这个梨全部套起来

0:00:46.550,0:00:49.268
这个鸟啊 梨小的时候它不吃

0:00:49.397,0:00:52.931
就是专门等到它长到半大不熟的时候吃得干干净净的

0:00:53.877,0:00:56.207
上都上来了然后我先把这个竹叶扫一下

0:00:56.884,0:00:59.233
这个竹叶太多了

0:01:29.069,0:01:32.444
打击看一下这个梨 这个已经很大个了

0:01:34.474,0:01:36.117
已经这么大了

0:01:37.222,0:01:39.382
这现在就是小鸟要吃的时候了

0:01:40.149,0:01:42.757
这个已经被梨压下来了 等一下我用一个（袋子）

0:01:45.943,0:01:46.650
掉了一个

0:01:48.232,0:01:49.517
都已经这么大太可惜了

0:01:49.785,0:01:50.960
待会儿用个东西把它撑起来

0:01:52.782,0:01:54.634
这个掉在上面已经烂了这个

0:01:56.137,0:01:57.162
太可惜了

0:01:58.705,0:01:59.522
这个都已经烂了

0:02:00.209,0:02:02.010
梨太多了把这个压垮了

0:02:25.564,0:02:28.123
废了九牛二虎之力把这个上面又扫了

0:02:28.143,0:02:30.960
我估计十天半个月之后又是一层

0:02:31.169,0:02:32.742
现在我来包一下这个梨

0:02:33.180,0:02:36.107
有没有懂行的 来教我一下

0:02:42.389,0:02:42.996
这个位置

0:02:47.396,0:02:48.531
嗯 可以了

0:02:48.810,0:02:50.462
有没有懂行的教我一下这个怎么弄

0:02:52.334,0:02:54.285
在我没学会之前先让它这样子吧

0:03:01.413,0:03:03.484
这个撑哪里 撑这里差不多

0:03:06.421,0:03:06.779
可以

0:03:11.956,0:03:13.578
这边再给它撑一个就差不多了

0:03:15.052,0:03:15.291
好

0:03:16.764,0:03:18.795
这个给它打开

0:03:22.608,0:03:25.216
这给它打开 然后把这个果子放进去

0:03:28.461,0:03:32.234
然后这样子收这个 收收收

0:03:33.389,0:03:35.002
收到这里的时候这有一根铁丝

0:03:35.470,0:03:39.920
把它这样子捆起来捏紧就可以了 特别简单

0:03:41.582,0:03:47.536
一次装它两个 让它们有伴 稍微捏一下就可以了

0:03:48.521,0:03:52.374
这样鸟儿就不知道里面有梨 它就吃不到了

0:03:53.668,0:03:54.275
这里还有

0:03:54.783,0:03:58.845
大家可以看一下这里上面有2个 这就是被鸟儿吃掉的

0:03:59.163,0:04:03.026
可能说这个鸟儿想留着下一次来吃其它的

0:04:03.822,0:04:04.728
我这次就把它包起来

0:04:06.600,0:04:09.009
哇这个上面 一枝上面结4个

0:04:10.144,0:04:11.408
这个你搞得我好为难啊

0:04:12.682,0:04:13.429
我这么接呢

0:04:15.022,0:04:17.650
它们4个包在一起 4兄弟很棒

0:04:18.725,0:04:20.826
去年这个（树）上面都只长了几个

0:04:21.612,0:04:23.494
刚好要吃的时候就被鸟吃了

0:04:24.519,0:04:25.793
今年给它保护一下

0:04:31.956,0:04:33.718
这个是掉在那个（雨棚）上面

0:04:34.086,0:04:39.900
被掉下来的竹叶捂在一起捂烂了 太可惜了丢掉

0:04:42.220,0:04:43.474
把这个没烂的也包一下

0:04:46.689,0:04:47.227
OK

0:04:48.272,0:04:51.209
这边可能它会烂就留点给鸟吃

0:04:58.795,0:05:00.169
这几个特别漂亮

0:05:02.588,0:05:03.394
先包这两个

0:05:11.607,0:05:13.340
然后再包这两个

0:05:21.911,0:05:23.165
哟 还包不住它啊

0:05:25.774,0:05:26.530
OK 可以了

0:05:28.760,0:05:30.950
好 那些包不到的不整了 不关事

0:05:31.319,0:05:33.499
那儿不好弄得 我逮要把它逮下来

0:05:44.161,0:05:45.206
我看一下拉不拉得下来

0:05:54.295,0:05:55.679
我四伯爷说的就这三个

0:06:03.504,0:06:06.042
哎呦 包的不是很好 希望鸟吃不到

0:06:08.561,0:06:10.482
看一下 我给你们看一下这个被鸟吃掉的

0:06:12.145,0:06:15.560
看到没这个给它吃空了

0:06:16.545,0:06:17.481
这边是很好看的

0:06:18.100,0:06:18.775
浪费

0:06:19.925,0:06:20.554
我要下去了

0:06:21.400,0:06:26.325
本身想拍摄新影片，但第二天居然停电了！

0:06:26.635,0:06:29.179
就是我们去年买了一个发电机

0:06:29.546,0:06:32.710
放了整整差不多一年了 今天终于派上用场了

0:06:33.270,0:06:34.922
因为我们县城现在停电

0:06:35.481,0:06:37.658
所以我要把这个发电机拿上去

0:06:38.532,0:06:41.014
把这个电给供上 然后我们才可以剪视频

0:06:41.320,0:06:42.631
我来先试一下这个行不行

0:06:53.680,0:06:58.593
还可以 用得了 没想到放这么久也还可以

0:06:59.406,0:07:01.154
还有桶油 油把它拿着

0:07:03.034,0:07:05.210
把这个油也给它带上

0:07:15.630,0:07:18.016
这发电机可能不轻 有一百斤吧应该有

0:07:18.418,0:07:19.948
然后把这个楼梯也带上

0:07:24.336,0:07:25.796
这应该没问题 掉不下来

0:07:26.915,0:07:30.848
楼梯 发电机 灯差不多了

0:07:36.268,0:07:40.263
还有最重要的线都没拿 等一下拿去估计要翻车啊

0:07:47.430,0:07:49.432
这线我们配的是50米的

0:07:53.278,0:07:54.791
还有把这些设备也拿上去

0:08:12.387,0:08:13.243
差不多了 走嘛

0:08:15.131,0:08:16.888
好了 现在我们要回富顺了

0:08:16.888,0:08:20.359
就是回去把这个发电机装上

0:08:20.359,0:08:22.643
然后继续剪我的视频

0:08:23.960,0:08:28.409
还有就是这段时间在忙新工作室这边的事情

0:08:28.409,0:08:29.703
很少拍做菜的视频

0:08:30.673,0:08:33.637
这里兄弟姐妹们先谅解一下

0:08:34.117,0:08:36.347
过段时间就可以拍了

0:08:37.352,0:08:38.812
应该三五几天吧

0:08:45.516,0:08:47.902
好了 我们终于把这个弄上来了

0:08:47.920,0:08:51.556
现在来把它卸下来 把线牵上去就可以了

0:08:59.895,0:09:00.236
好了

0:09:17.631,0:09:20.131
可以了先将就着用

0:09:25.612,0:09:27.369
这个终于接上电了

0:09:28.584,0:09:30.359
这个发电机功率应该不够

0:09:30.385,0:09:33.995
可能我们拖空调拖不起 只能拖几台电脑

0:09:35.228,0:09:36.014
不过也够了

0:09:37.693,0:09:38.497
来电没

0:09:39.939,0:09:40.647
来了电没

0:09:43.978,0:09:45.840
来了的 那样子可以了嘎

0:09:54.764,0:09:57.736
好 可以了电脑开了可以剪视频了

0:09:58.287,0:09:59.948
好了 本期视频到这里 拜拜


```

**Comment by immoonancient** [comment]
@iamatrollatrollisme 请前来认领接着做后面的部分

**Comment by iamatrollatrollisme** [comment]
认领

**Comment by iamatrollatrollisme** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
把老家梨树结的果子包起来防止鸟儿来偷吃！偶遇停电怎么办？居然还能继续剪视频！
Covering pears with bags to prevent birds! How to edit video during power outage!

简介
大家如果之前看过我做户外厨房和搭棚子的视频就知道特地留下了这颗梨树，当时就说等梨子长大些就爬上来装袋，因为梨大了变甜了之后非常容易被鸟吃掉。上到棚上发现不少树枝因为结了梨被压下来了，梨碰到棚子就烂掉了，不知道大家有没有什么好办法可以解决这个问题？暂时就拿了些竹子把树枝撑起来，希望能有些帮助，很期待再过段时间梨的收获！富顺偶遇停电，打乱了拍摄计划，不过想到之前放在老家了一台发电机，这次居然用上了，不过带不起来空调，还是有些难受。最近由于忙新工作室和拍摄方面的升级，所以比较少拍做菜教学的视频，请大家谅解，硬核教学很快就会回归！
If you have seen my videos about outdoor kitchen and the shed, you would know I purposely kept the pear tree. I said that when the pears grew bigger, we would come up here to cover them up with bags. Because when pears are getting ripe, they are becoming very sweet. Then they will attract birds to come eat them. When I got up on the roof of the shed, I found that many branches couldn’t carry the weight of the pears and got pulled down, when the pears touched the roof of the shed, they would rot. I wonder if you have a good solution to solve this? For now, I am holding the branches up with some bamboo, hope it helps. I am very much looking forward to the harvest of pears later. All of sudden there was a power outage in Fushun, messing up the filming schedule. But I recalled that I put a regenerator here in my hometown and I was able to utilize it. But it was not strong enough to power the AC, so it was not very comfortable. Lately I have been busy building my new studio and upgrading my film gadgets, so I will make less recipe videos, sorry about this and hope you can understand. The comprehensive cooking videos will return soon!

字幕
0:00:00.025,0:00:01.025
哈喽 大家好
Hello everyone

0:00:01.105,0:00:03.872
今天我要上去弄一下上面的竹叶
Today I am going up there to clean up the bamboo leaves

0:00:04.171,0:00:08.790
然后再把我们那个梨 已经这么大了用纸包起来
And then take our pears, they are like this big now, I am covering them up with paper bags

0:00:09.218,0:00:11.976
要不然那些小鸟几下就给它吃掉了
Otherwise the birds will eat the pears very quickly

0:00:23.066,0:00:24.310
第一次上去还多害怕
I was a little scared the first time I climbed up here

0:00:24.310,0:00:25.276
扫不扫哦
Are we sweeping the roof?

0:00:26.082,0:00:27.078
要扫
Yes

0:00:29.148,0:00:31.348
既然上去了肯定要扫了
Of course, he is sweeping it, he climbed up there after all

0:00:36.973,0:00:38.934
吓我一跳 差点滑了
I almost slipped and got scared a little

0:00:39.472,0:00:43.812
现在终于上来了 用我四伯爷给我的这个袋子
Finally I am up here now, using the bags my uncle gave me

0:00:44.181,0:00:45.624
然后把这个梨全部套起来
To cover all the pears

0:00:46.550,0:00:49.268
这个鸟啊 梨小的时候它不吃
These birds do not eat the pears when they are small

0:00:49.397,0:00:52.931
就是专门等到它长到半大不熟的时候吃得干干净净的
Birds purposely wait until the pears grow half way through, then they will eat all the pears

0:00:53.877,0:00:56.207
上都上来了然后我先把这个竹叶扫一下
Since I am up here, I am going to sweep the bamboo leaves

0:00:56.884,0:00:59.233
这个竹叶太多了
There are too many bamboo leaves up here

0:01:29.069,0:01:32.444
打击看一下这个梨 这个已经很大个了
Take a look at this pear, it is pretty big now

0:01:34.474,0:01:36.117
已经这么大了
It has grown a lot

0:01:37.222,0:01:39.382
这现在就是小鸟要吃的时候了
This is the time when birds are going to eat the pears

0:01:40.149,0:01:42.757
这个已经被梨压下来了 等一下我用一个（袋子）
Now the weight of the pears is pulling the branch down, I am going to use (a bag to collect them)

0:01:45.943,0:01:46.650
掉了一个
One fell off

0:01:48.232,0:01:49.517
都已经这么大太可惜了
It grew pretty big, what a pity

0:01:49.785,0:01:50.960
待会儿用个东西把它撑起来
I am going to find something up hold it up

0:01:52.782,0:01:54.634
这个掉在上面已经烂了这个
When it fell, it got rotten on the roof

0:01:56.137,0:01:57.162
太可惜了
What a waste

0:01:58.705,0:01:59.522
这个都已经烂了
This one is rotten

0:02:00.209,0:02:02.010
梨太多了把这个压垮了
There are too many pears up here and the weight is holding down the branches

0:02:25.564,0:02:28.123
废了九牛二虎之力把这个上面又扫了
It took so much effort to sweep the roof again

0:02:28.143,0:02:30.960
我估计十天半个月之后又是一层
I estimate that after a couple of weeks, it will be another layer of bamboo leaves again

0:02:31.169,0:02:32.742
现在我来包一下这个梨
Now I am going to cover the pears

0:02:33.180,0:02:36.107
有没有懂行的 来教我一下
Is there any expert here that can teach me something about this?

0:02:42.389,0:02:42.996
这个位置
Put it here?

0:02:47.396,0:02:48.531
嗯 可以了
Yes, this is good

0:02:48.810,0:02:50.462
有没有懂行的教我一下这个怎么弄
Is there any professional here that can teach me how to get this done?

0:02:52.334,0:02:54.285
在我没学会之前先让它这样子吧
I will just leave it like this before I learn how to handle it

0:03:01.413,0:03:03.484
这个撑哪里 撑这里差不多
Where do I put this one? Should I put it here?

0:03:06.421,0:03:06.779
可以
Okay this is good

0:03:11.956,0:03:13.578
这边再给它撑一个就差不多了
Then I will put another one here, it should fine now

0:03:15.052,0:03:15.291
好
Okay

0:03:16.764,0:03:18.795
这个给它打开
Now I am opening this bag

0:03:22.608,0:03:25.216
这给它打开 然后把这个果子放进去
Open the bag then put the pear into the bag

0:03:28.461,0:03:32.234
然后这样子收这个 收收收
And then wrap it up and pinch together the edge

0:03:33.389,0:03:35.002
收到这里的时候这有一根铁丝
At the end I will tie it up with iron wire

0:03:35.470,0:03:39.920
把它这样子捆起来捏紧就可以了 特别简单
Wrap up the edge and pinch the wire, then I am done. Very simple

0:03:41.582,0:03:47.536
一次装它两个 让它们有伴 稍微捏一下就可以了
I am bagging these two together, so they can keep each other company, just slightly pinch it

0:03:48.521,0:03:52.374
这样鸟儿就不知道里面有梨 它就吃不到了
This way, the birds do not know there are pears in there, they cannot eat them

0:03:53.668,0:03:54.275
这里还有
There are more here

0:03:54.783,0:03:58.845
大家可以看一下这里上面有2个 这就是被鸟儿吃掉的
Let us take a look at the two up there, these are the ones that birds ate

0:03:59.163,0:04:03.026
可能说这个鸟儿想留着下一次来吃其它的
Maybe the birds wanted to come back and eat other pears

0:04:03.822,0:04:04.728
我这次就把它包起来
But I will cover the pears this time

0:04:06.600,0:04:09.009
哇这个上面 一枝上面结4个
Wow look at this, there are 4 pears on this branch

0:04:10.144,0:04:11.408
这个你搞得我好为难啊
What should I do with it?

0:04:12.682,0:04:13.429
我这么接呢
How do I cover it?

0:04:15.022,0:04:17.650
它们4个包在一起 4兄弟很棒
I will jut bag four of them together, four siblings, very nice

0:04:18.725,0:04:20.826
去年这个（树）上面都只长了几个
Last year, this(tree) only had a few pears

0:04:21.612,0:04:23.494
刚好要吃的时候就被鸟吃了
Birds ate most of the pears when the pears were about to ripe

0:04:24.519,0:04:25.793
今年给它保护一下
This year I am providing protection for the pears

0:04:31.956,0:04:33.718
这个是掉在那个（雨棚）上面
This one fell on top of that(shed)

0:04:34.086,0:04:39.900
被掉下来的竹叶捂在一起捂烂了 太可惜了丢掉
These pears were covered by the bamboo leaves fallen from trees and got rotten, I have to throw them away, what a waste

0:04:42.220,0:04:43.474
把这个没烂的也包一下
I am going to cover this one that is not rotten

0:04:46.689,0:04:47.227
OK
OK

0:04:48.272,0:04:51.209
这边可能它会烂就留点给鸟吃
If it is partially rotten, then I will just leave it to the birds

0:04:58.795,0:05:00.169
这几个特别漂亮
These pears look very nice

0:05:02.588,0:05:03.394
先包这两个
Then covering these two

0:05:11.607,0:05:13.340
然后再包这两个
Then covering these two

0:05:21.911,0:05:23.165
哟 还包不住它啊
Oops, it does not fit the pear

0:05:25.774,0:05:26.530
OK 可以了
Okay, this is good

0:05:28.760,0:05:30.950
好 那些包不到的不整了 不关事
The ones are too far to reach, you do not need to cover them

0:05:31.319,0:05:33.499
那儿不好弄得 我逮要把它逮下来
It is not easy to reach them, I will try to pull them down

0:05:44.161,0:05:45.206
我看一下拉不拉得下来
Let me see if I can get it down

0:05:54.295,0:05:55.679
我四伯爷说的就这三个
These are the three my uncle was talking about

0:06:03.504,0:06:06.042
哎呦 包的不是很好 希望鸟吃不到
I did not cover it well so I hope the birds cannot reach it

0:06:08.561,0:06:10.482
看一下 我给你们看一下这个被鸟吃掉的
Here, let me show you the one that got eaten by the birds

0:06:12.145,0:06:15.560
看到没这个给它吃空了
Can you see that the inside is hollow, all eaten by the birds

0:06:16.545,0:06:17.481
这边是很好看的
On this side, it looks nice

0:06:18.100,0:06:18.775
浪费
Wasteful

0:06:19.925,0:06:20.554
我要下去了
I am going down now

0:06:21.400,0:06:26.325
本身想拍摄新影片，但第二天居然停电了！
I wanted to film new video, but we had a power outage the next day

0:06:26.635,0:06:29.179
就是我们去年买了一个发电机
We bought a regenerator last year

0:06:29.546,0:06:32.710
放了整整差不多一年了 今天终于派上用场了
We put it there for almost one whole year, finally we get to utilize it

0:06:33.270,0:06:34.922
因为我们县城现在停电
Because the county is experiencing power outage

0:06:35.481,0:06:37.658
所以我要把这个发电机拿上去
So I am taking this regenerator up

0:06:38.532,0:06:41.014
把这个电给供上 然后我们才可以剪视频
So it can provide power for us to edit the video

0:06:41.320,0:06:42.631
我来先试一下这个行不行
Let me try to see if it works

0:06:53.680,0:06:58.593
还可以 用得了 没想到放这么久也还可以
Okay, it works. It is surprising that it still works after all these time being put aside

0:06:59.406,0:07:01.154
还有桶油 油把它拿着
Oh and the gas, I need to take the gas with me

0:07:03.034,0:07:05.210
把这个油也给它带上
I need to take the gas as well

0:07:15.630,0:07:18.016
这发电机可能不轻 有一百斤吧应该有
The regenerator is not light, probably at least 100jin

0:07:18.418,0:07:19.948
然后把这个楼梯也带上
Also I need to take the ladder with me

0:07:24.336,0:07:25.796
这应该没问题 掉不下来
This should be fine, it won’t fall off

0:07:26.915,0:07:30.848
楼梯 发电机 灯差不多了
Ladder, regenerator and the light, this is probably all

0:07:36.268,0:07:40.263
还有最重要的线都没拿 等一下拿去估计要翻车啊
We almost forgot the most important cables, almost failed to grab everything

0:07:47.430,0:07:49.432
这线我们配的是50米的
The cable is 50 meters long

0:07:53.278,0:07:54.791
还有把这些设备也拿上去
We might as well take all the equipments with us

0:08:12.387,0:08:13.243
差不多了 走嘛
Okay, this should be it, let’s go

0:08:15.131,0:08:16.888
好了 现在我们要回富顺了
Okay now we are heading back to Fushun

0:08:16.888,0:08:20.359
就是回去把这个发电机装上
Going back to put up the regenerator

0:08:20.359,0:08:22.643
然后继续剪我的视频
Then I will continue to edit my videos

0:08:23.960,0:08:28.409
还有就是这段时间在忙新工作室这边的事情
Moreover, lately I have been busying renovating my new studio 

0:08:28.409,0:08:29.703
很少拍做菜的视频
I cannot film many cooking videos

0:08:30.673,0:08:33.637
这里兄弟姐妹们先谅解一下
Sorry about this, hope you guys can understand

0:08:34.117,0:08:36.347
过段时间就可以拍了
I can start filming again later

0:08:37.352,0:08:38.812
应该三五几天吧
Around three to five days

0:08:45.516,0:08:47.902
好了 我们终于把这个弄上来了
Okay now we finally brought this up here

0:08:47.920,0:08:51.556
现在来把它卸下来 把线牵上去就可以了
Now I just need to remove it from the car and connect it with the cable

0:08:59.895,0:09:00.236
好了
Okay

0:09:17.631,0:09:20.131
可以了先将就着用
Okay I will just use the regenerator

0:09:25.612,0:09:27.369
这个终于接上电了
Now we finally have power

0:09:28.584,0:09:30.359
这个发电机功率应该不够
This regenerator probably is not powerful enough

0:09:30.385,0:09:33.995
可能我们拖空调拖不起 只能拖几台电脑
It is not powerful enough to run the AC, it can only support a few computers

0:09:35.228,0:09:36.014
不过也够了
But this is enough

0:09:37.693,0:09:38.497
来电没
Do you have power?

0:09:39.939,0:09:40.647
来了电没
Do you have power?

0:09:43.978,0:09:45.840
来了的 那样子可以了嘎
Okay, it looks like this works well

0:09:54.764,0:09:57.736
好 可以了电脑开了可以剪视频了
Okay, the computer is on, I can edit video now

0:09:58.287,0:09:59.948
好了 本期视频到这里 拜拜
Okay, this is the end of the video, bye
