### ISSUE TITLE
[华农兄弟] 蜂蜜 - https://youtu.be/yHyjJ4NweM4

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1220]
https://youtu.be/yHyjJ4NweM4
<p>&#35270;&#39057;&#21457;&#24067;&#20110; June 28, 2020 at 11:22PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/yHyjJ4NweM4

#华农兄弟：听说兄弟在割蜂蜜，去帮一下忙，顺便搞点来尝一下
#Huanong Brothers: Somebody told me that my buddy is havesting honey. Let's help him, and also get some to have a try.

0:00:00.000,0:00:03.780
# 大家好  今天聽說兄弟在割蜂蜜哦  過來看一下(註︰他又是經常把「蜂蜜」和「蜜蜂」說錯，會配合一下)
Hi everyone! Somebody told me that my buddy's gonna harvest the honey today. So I come and have a look.

0:00:04.240,0:00:05.200
# 帶個安全帽
Let me put on a safety hat.

0:00:06.800,0:00:07.620
# 怕萬一
Just in case

0:00:08.620,0:00:10.000
# 蟄到臉就不好看了
It would be too embarrassing if my face got stung.

0:00:13.460,0:00:15.120
# 手臂又裸露著
And my arms are naked.

0:00:16.500,0:00:20.540
# 你看  這個是  剛開箱的哦  那麼多
Look! This is, this box is newly opened. There's so much.

0:00:21.640,0:00:22.460
# 要慢一點
You gotta do it slowly.

0:00:24.100,0:00:27.240
# 別把蜂蜜惹急了  惹急了它就蟄人了
Don't provoke the honey, the honey bees. They sting if they are provoked.

0:00:38.760,0:00:39.400
# 嗯
Um!

0:00:41.140,0:00:42.020
# 好甜啊
It's so sweet!

0:00:44.980,0:00:46.180
# 哎呀  謝謝  謝謝
Aya! Thanks, thanks!

0:01:00.480,0:01:02.200
# 哇  這一塊多哦  這個
Wa! This board is filled with honey, this one.

0:01:04.420,0:01:06.820
# 這個  要哪個  你要不要自己提
This one.
Which one? You wanna hold it yourself?

0:01:07.840,0:01:09.940
# 這個才多  我要提這個  這個多的
This is the heavy one. I wanna hold this one, the one with more honey.

0:01:12.240,0:01:14.620
# 好重啊  這個  最少幾斤  你看
It's so heavy! This is, at least a couple of kilograms. Look!

0:01:16.700,0:01:17.360
# 看到沒有
See?

0:01:18.160,0:01:19.520
# 出去出去  哎  走啦
Get out, get out! Ay! It's out.

0:01:19.700,0:01:22.260
# 你看  這就是我們本地的土蜂蜜
Look! This is the local honey here at our place.

0:01:22.940,0:01:24.300
# 這個時候是百花蜜哦
At this time of the year, it is multiflora honey.

0:01:24.800,0:01:26.840
# 就是很多種花混合在一起
That means it combines many different types of flowers.

0:01:27.080,0:01:28.980
# 你看這裡  全是糖
Look! Here, it's all honey.

0:01:33.260,0:01:34.320
# 爽啊  看看
Cool! Have a look!

0:01:35.420,0:01:36.480
# 看上去都想吃
It looks so attractive.

0:01:37.300,0:01:38.360
# 我搞一塊來吃一下
Let me take a piece and have a try.

0:01:40.120,0:01:42.440
# 你看這個  都漏啊  漏啦
Have a look here! It's drip, dripping.

0:01:43.660,0:01:44.160
# 哎呀
Aya!

0:01:48.520,0:01:50.020
# 全是糖  這些地方
It's all honey, this area.

0:01:51.460,0:01:54.140
# 你看最近天氣好  它這蜂蜜產量很高哦
Look! The weather is nice recently. So the yield of the honey here is really high.

0:01:55.840,0:01:57.160
# 真想一口咬下去
I really wanna simply bite it.

0:02:00.680,0:02:01.460
# 這樣又不好
But it's not nice.

0:02:02.580,0:02:03.520
# 太粗魯啦  這樣
It's, too rude.

0:02:06.880,0:02:09.000
# 你看這邊  全是蜂蜜  看到沒有
Have a look at this side. It's all honey. See?

0:02:09.880,0:02:10.560
# 這邊也是
And this side too.

0:02:11.540,0:02:13.840
# 封了蓋的全是滿的蜜哦  封蓋了
Under the seal it's full of honey, under the seal.

0:02:14.820,0:02:17.000
# 他家的蜂蜜怎麼  那麼勤勞
Why are his honey bees, so, so diligent?

0:02:17.820,0:02:19.360
# 我們家有 有一箱蜂蜜
We also have a box of honey at home.

0:02:20.540,0:02:22.400
# 一 一滴蜜我都沒吃到
But I've never had any honey from them, not, not even a drip.

0:02:23.220,0:02:23.800
# 太懶了
They're too lazy.

0:02:25.200,0:02:25.980
# 把它甩出來
Let's spin it out.

0:02:26.740,0:02:28.200
# 甩到那個瓶子裡面裝著
Spin it out into the bucket there.

0:02:30.960,0:02:35.060
# 他把這個蓋子  蓋子要割掉  蜜才能甩得出來
The seal, he's now cutting off the seal, so that the honey can be spun out.

0:02:35.700,0:02:38.580
# 要不然甩不出來  你看  全是蜜
Otherwise, you can't spin it out. Look! It's all honey.

0:02:54.720,0:02:56.180
# 還沒甩掉  還有好多
Not yet. There's still a lot.

0:02:58.820,0:03:00.620
# 甩乾淨一點  那個蜜夠吃
Spin more thoroughly, so that we can have enough honey,

0:03:02.240,0:03:03.420
# 蜜蜂才勤快
the bees will be more diligent.

0:03:09.980,0:03:12.800
# 這一餅才重啊 哇  最少七八斤
This is the heavy board. Wa! It's at least three or four kilograms.

0:03:14.080,0:03:14.660
# 喂呦
Wayo!

0:03:17.220,0:03:19.560
# 你看  它這  這邊也很多哦  你看這裡
Look! Here it, there's also a lot on this side. Have a look here!

0:03:22.380,0:03:23.340
# 好重啊
It's so heavy.

0:03:24.040,0:03:24.940
# 拎都拎不起來
I can only barely hold it.

0:03:26.300,0:03:29.800
# 你看這種  這種蜜蜂是我們本地的小蜜蜂來的
Look! These are, these bees are our local bees here.

0:03:31.700,0:03:33.480
# 好多糖啊  太勤快啦
A lot of honey! They're just too diligent.

0:03:34.560,0:03:37.200
# 給他先  哎呦  那麼重  這個
I give it back to him first. Ayo! It's so heavy, this one.

0:03:38.920,0:03:41.360
# 他這樣一甩都甩到幾斤出來
A couple of kilograms can be spun out without too much work.

0:03:41.660,0:03:42.820
# 哇  你看  過濾一下
Wa! Look! Let's filter it.

0:03:43.980,0:03:45.480
# 過濾一下比較乾淨
It becomes cleaner after filtering.

0:03:59.320,0:04:01.340
# 你看這一桶  一百多斤哦  這個
Have a look at the bucket here. It's more than fifty kilograms, this one.

0:04:02.660,0:04:04.040
# 很快的  兩下就滿啦
It doesn't take long. It gets filled up very quickly.

0:04:06.840,0:04:07.660
# 那麼多蜂蜜
So much honey

0:04:08.520,0:04:11.140
# 你看這個  還有好多蜜的  這個可以吃的哦  這個
Have a look here. There's still a lot of honey. This is also edible, you know.

0:04:13.340,0:04:14.340
# 這種  這種
This one, like this one

0:04:15.420,0:04:17.000
# 你看這個  還有那麼多蜜  這個
Have a look at this one. There's still so much honey, this one.

0:04:29.940,0:04:34.220
# 這種蜂巢  可以  可以用來嚼一下  好香啊
This kind of bee combs, can be, can be chewed. It smells so good.

0:04:35.280,0:04:35.780
# 你看
Look!

0:04:37.680,0:04:38.180
# 嗯
Um!

0:04:40.800,0:04:41.440
# 太浪費啦
What a waste!

0:04:42.360,0:04:43.340
# 老是往地下掉
It's always dripping onto the ground.

0:04:48.940,0:04:50.060
# 這就是蜂巢蜜
This is called honeycomb.

0:04:50.740,0:04:51.940
# 其實蜂巢也可以吃的
Bee combs are also edible, in fact.

0:04:59.820,0:05:00.600
# 嗯~
Um~

0:05:04.020,0:05:04.700
# 這好多
Here's a lot!

0:05:08.200,0:05:10.080
# 你看  這裡還有好多啊
Look! Here are still a lot!

0:05:10.720,0:05:11.920
# 幾十箱  上百箱
Tens, or up to a hundred boxes

0:05:16.560,0:05:17.840
# 兄弟家的小別墅
This is my buddy's tiny villa.

0:05:19.420,0:05:20.620
# 還有一條狗在這裡
Here's also a dog.

0:05:29.160,0:05:31.060
# 你看  兄弟的大狗
Look! My buddy's big dog.

0:05:31.700,0:05:32.340
# 好猛啊
He's ferocious.

0:05:58.480,0:05:59.800
# 上上上去
Go, go, get him!

0:06:01.200,0:06:02.040
# 幹他幹他幹他
Attack, attack, attack!

0:06:10.960,0:06:15.560
# 那鏈子  鏈子一脫的話  麻  麻煩了  它那鏈子一脫
The chain, if the chain breaks, game, game over, if the chain breaks.

0:06:17.480,0:06:18.120
# 不聽話
Not listening.

0:06:19.380,0:06:20.000
# 它不聽話
He's not listening.

0:06:22.560,0:06:24.560
# 上面還有好多啊  一直上去都有的
Here's still a lot up there, all the way up there.

0:06:27.840,0:06:28.880
# 全是野蜂蜜哦
All is wild honey.

0:06:34.720,0:06:37.460
# 你看這些小蜜蜂   好勤勞哦
Have a look at these little bees. They're so diligent,

0:06:38.820,0:06:40.420
# 飛來飛去 飛來飛去的
flying here and there, here and there.

0:06:41.200,0:06:43.760
# 回來的時候都有花粉在腳上
There's pollen on their feet when they come back,

0:06:44.000,0:06:47.840
# 沾著  等下它拿回去就是要釀蜜
sticking there. The bees are gonna make the honey when they're back.

0:06:48.620,0:06:50.760
# 你看  腳上都有花粉的
Look! There's pollen on their feet.

0:06:51.600,0:06:53.960
# 有幾個蜜蜂虎視眈眈的看著我
Some bees are staring at me with greed.

0:06:55.140,0:06:57.940
# 喜歡看著我  等下我去吃你的蜜
They like staring at me. Your honey will be mine very soon.

0:07:00.280,0:07:02.520
# 你滿  滿箱的哦  一整箱都是
This is full, this box is full, full of honey.

0:07:03.400,0:07:05.400
# 你看  腳上都有 花粉
Look! There's pollen, on their feet.

0:07:07.000,0:07:08.600
# 飛進飛出 飛進飛出
In and out and in and out

0:07:09.720,0:07:11.740
# 一個禮拜左右就把糖搞滿啦
The whole box will be filled with honey in around a week.

0:07:15.720,0:07:19.380
# 哇  全部是滿的  怪不得它們不出去
Wa! It's all full. No wonder they're not going out.

0:07:19.860,0:07:23.520
# 你看  原來是  都夠吃啦  它們就不出去
Look! It's because, they have enough food. So they're not going out.

0:07:29.720,0:07:31.420
# 哇  全部滿蜜的
Wa! It's full of honey!

0:07:32.080,0:07:32.700
# 看到嗎
See?

0:07:32.700,0:07:33.700
# 滿糖的
It's complete filled with honey!

0:07:40.020,0:07:40.860
# 哇
Wa!

0:07:41.300,0:07:41.880
# 怎麼樣
How's it?

0:07:41.880,0:07:42.940
# 漏啦漏啦
It's dripping, it's dripping!

0:08:06.800,0:08:08.660
# 現在越來越多蜂蜜了哇
It's getting more and more honey bees.

0:08:09.740,0:08:11.740
# 你看  全部都圍著我了  走了
Look! They're all flying around me. Let's go.
