### ISSUE TITLE
[雪鱼] 西北羊肠面 - https://youtu.be/VGgbfhyCiQs

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#1226]
**视频链接**：<https://youtu.be/VGgbfhyCiQs>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
<大西北早餐真硬核，2米面条抓进碗，加羊肠卖11元！人多炉灶都坐满>

简介
<探寻世界美味，从南吃到北，从白吃到黑，我是雪鱼。
从这期开始，雪鱼将开始新的旅程，探索中国大西北的美食风味。首站来到青海省西宁市，这是一个高原城市，昼夜温差大，整座城市沿着河流分布，两面环山，风景如画。早上起来，我就直奔一家西宁当地很有名气的早餐店，专门来吃羊肠抓面！顾名思义，就是羊肠加面。一碗素面是5元，加羊肠辣子卖到11元，3个阿姨在透明半开放的厨房里忙碌。这个面条的一大特点是特别长，需要用手抓到碗里，一根面最长可以达到2米，甚至3米，加上羊肠的面，需要在滚烫的热水里冒几下直到烫熟，最后加辣椒、醋等调味品，看上去非常诱人。老顾客除了要一碗羊肠抓面，还会点一碗牛头肉，牛头肉筋道有味，配合蒜泥辣椒的香气，更让人爱不释手。在西宁的早上吃这样一碗羊肠面，真是热量非常高，管饱暖和舒服！>

字幕
<1
00:00:01,680 --> 00:00:02,400
很多人来西宁

2
00:00:02,400 --> 00:00:04,440
是为了打卡绝美的风景

3
00:00:04,440 --> 00:00:05,920
而雪鱼这次来西宁

4
00:00:05,920 --> 00:00:10,280
不仅仅是来看风景 还有品尝大西北的美食

5
00:00:14,800 --> 00:00:17,720
从西安飞到西宁 一下飞机 我就觉得特别冷

6
00:00:17,720 --> 00:00:22,040
我发现我的手表上 出现了从来没有的数字显示

7
00:00:22,040 --> 00:00:26,320
我现在在海拔2千多米的高原上

8
00:00:29,360 --> 00:00:32,920
司机师傅告诉我们 在青海旅游就要注意两点

9
00:00:32,920 --> 00:00:34,180
一个是防晒

10
00:00:34,200 --> 00:00:36,720
因为这边的紫外线特别强烈

11
00:00:36,720 --> 00:00:39,640
第二个呢 一定要做好防雨的准备

12
00:00:39,640 --> 00:00:41,960
有的时候 之前可能是晴空万里

13
00:00:41,960 --> 00:00:44,480
但是雨呢 就是说下就下

14
00:00:48,200 --> 00:00:52,440
接下来雪鱼要去吃的是羊肠面 在当地是比较常见的

15
00:00:52,440 --> 00:00:54,760
名字听起来可能不太精致

16
00:00:54,760 --> 00:00:58,920
但是能够称得起当地特色的美食 味道应该不会很差

17
00:00:58,920 --> 00:01:03,080
坐出租走吧

18
00:01:10,120 --> 00:01:12,120
就是这家的羊肠面

19
00:01:31,220 --> 00:01:32,040
你要啥样的

20
00:01:32,780 --> 00:01:34,780
一份羊肠面 再加一份牛头肉

21
00:01:36,960 --> 00:01:38,960
把牛头肉放在另一个碗里

22
00:01:41,080 --> 00:01:43,080
看到周围一直注视的目光

23
00:01:44,000 --> 00:01:47,900
我意识到我可能答非所问

24
00:01:47,940 --> 00:01:49,940
通过不断的比划和重复 我想要的是

25
00:01:50,560 --> 00:01:52,560
一碗羊肠面和一份牛头肉

26
00:01:58,800 --> 00:02:00,800
这种摊在桌子上的

27
00:02:00,840 --> 00:02:02,840
要不断用手抓 不断散落的

28
00:02:02,840 --> 00:02:04,380
金黄色的细面条

29
00:02:04,840 --> 00:02:06,840
是用鸡蛋 面粉和食用碱做成的

30
00:02:07,180 --> 00:02:09,680
把它煮到七八分熟后 捞出来过凉水

31
00:02:10,120 --> 00:02:12,520
处理好的面条 就会放在店里最显眼的位置

32
00:02:13,400 --> 00:02:16,140
客人点完面 就把面放在沸汤里过几遍

33
00:02:16,140 --> 00:02:18,140
大约几秒就可以出锅

34
00:02:18,680 --> 00:02:20,000
如果面上码了肉

35
00:02:20,280 --> 00:02:22,280
肉呢 也会随面一起进入漏勺

36
00:02:22,280 --> 00:02:26,020
经历几次漏勺开花 最后一同进入碗中

37
00:02:48,860 --> 00:02:53,260
现在是调上醋 蒜 辣子 我们就可以端走了

38
00:03:13,680 --> 00:03:15,680
今天吃的就是羊肠面

39
00:03:16,080 --> 00:03:19,280
除了面以外，我们还要了一份牛头肉 共消费22元

40
00:03:19,800 --> 00:03:22,160
这碗是免费自己盛的汤

41
00:03:35,920 --> 00:03:38,500
羊肠面 看字面意思就是羊肠加面

42
00:03:39,360 --> 00:03:44,080
面是提前用个鸡蛋 面粉 食用碱一起和出来的

43
00:03:44,680 --> 00:03:47,380
你看 这边的抓面 一根都有1米长

44
00:03:47,420 --> 00:03:49,420
最长的能够达到3米

45
00:03:49,700 --> 00:03:51,700
每抓一次面都是在做力气活啊

46
00:03:54,560 --> 00:03:56,560
这么一挑面条 冒着热气

47
00:03:56,800 --> 00:03:58,800
我们尝一尝吧

48
00:04:01,560 --> 00:04:03,820
这个面条很像武汉的热干面

49
00:04:04,100 --> 00:04:07,060
是干拌的 看起来又很筋道

50
00:04:20,360 --> 00:04:24,500
面条里加了辣子是很香的

51
00:04:26,940 --> 00:04:28,280
没有一点的汤汁

52
00:04:29,140 --> 00:04:31,140
面条之间主要靠表面的油来分离开

53
00:04:34,280 --> 00:04:36,280
来尝尝今天的主角 羊肠

54
00:04:38,800 --> 00:04:43,220
羊肠不是空心的 分肉肠和面肠的

55
00:04:43,220 --> 00:04:45,020
像这种颜色比较深的

56
00:04:45,300 --> 00:04:48,500
里面就是用羊的内脏加调料做出来的

57
00:04:49,220 --> 00:04:51,520
而这个颜色比较浅的

58
00:04:52,740 --> 00:04:55,300
就是用豆面糊加调料煮出来的

59
00:04:57,320 --> 00:05:00,280
吃面肠就像吃山药一样，面面的口感

60
00:05:01,980 --> 00:05:04,740
外面的肠衣是脆的 里面是绵的

61
00:05:06,940 --> 00:05:09,020
面肠的味道会比较淡一些

62
00:05:10,140 --> 00:05:13,580
肉肠的味道就是胡椒粉的辛辣味道比较重

63
00:05:16,040 --> 00:05:19,960
一碗面里的羊肠不多

64
00:05:20,580 --> 00:05:23,680
已经被我默默地吃掉四五个了

65
00:05:28,420 --> 00:05:32,000
肉肠挂辣子 吃起来更香 更辣

66
00:05:39,420 --> 00:05:41,420
会吃肠子的人 都知道

67
00:05:42,220 --> 00:05:44,740
像羊肠这种东西 就是把内壁洗干净

68
00:05:45,240 --> 00:05:48,080
但是一定不要刮这个肠壁油

69
00:05:48,720 --> 00:05:51,400
因为有肠壁油 羊肠吃起来才会更香

70
00:05:51,760 --> 00:05:54,080
总的来说 清洗羊肠 就是要洗的干净

71
00:05:54,200 --> 00:05:56,200
但是不能洗的太过于干净

72
00:05:56,320 --> 00:05:58,320
这样的分寸要拿捏好

73
00:06:09,360 --> 00:06:12,940
很多人听到羊肠面这个名字 听起来是很重口的

74
00:06:12,940 --> 00:06:14,900
所以说内心会比较排斥

75
00:06:14,900 --> 00:06:16,840
但是试一试你会发现

76
00:06:17,260 --> 00:06:19,900
它并没有想象的那么黑暗难吃

77
00:06:20,540 --> 00:06:23,160
辣子 肉香 面香啊 让你越吃越想吃

78
00:06:32,660 --> 00:06:35,480
这是个炉子 是用来加热酸汤的

79
00:06:35,940 --> 00:06:38,400
但它不仅仅是一个炉子 还是一个桌子

80
00:06:38,760 --> 00:06:43,980
很多人就是围着炉子一边吃面一边喝汤

81
00:06:50,500 --> 00:06:53,940
我们的西宁美食之旅从这期就要开始啦

>
```

**Comment by Kevinzheng5** [comment]
认领

**Comment by Kevinzheng5** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
<大西北早餐真硬核，2米面条抓进碗，加羊肠卖11元！人多炉灶都坐满>
Breakfast in Northwestern China-Lamb Sausage Noodles

简介
<探寻世界美味，从南吃到北，从白吃到黑，我是雪鱼。
从这期开始，雪鱼将开始新的旅程，探索中国大西北的美食风味。首站来到青海省西宁市，这是一个高原城市，昼夜温差大，整座城市沿着河流分布，两面环山，风景如画。早上起来，我就直奔一家西宁当地很有名气的早餐店，专门来吃羊肠抓面！顾名思义，就是羊肠加面。一碗素面是5元，加羊肠辣子卖到11元，3个阿姨在透明半开放的厨房里忙碌。这个面条的一大特点是特别长，需要用手抓到碗里，一根面最长可以达到2米，甚至3米，加上羊肠的面，需要在滚烫的热水里冒几下直到烫熟，最后加辣椒、醋等调味品，看上去非常诱人。老顾客除了要一碗羊肠抓面，还会点一碗牛头肉，牛头肉筋道有味，配合蒜泥辣椒的香气，更让人爱不释手。在西宁的早上吃这样一碗羊肠面，真是热量非常高，管饱暖和舒服！>
Explore delicious foods, from south to north during days and nights. I’m Xueyu
From this episode, Xueyu will start a new journey to explore local specials in Northwestern China. The first stop is Xining, the capitol of Qinghai province. It’s a city on the plateau with a huge temperature difference between the days and nights. The city sits on a river with mountains surrounding. What a view! This morning, I went directly to a famous breakfast place for its lamb sausage noodles. As the name implies, it’s noodle with lamb sausages. Noodles alone is 5 yuan. Noodles along with lamb sausages and chili oil is 11 yuan. There are 3 aunties in a clear, semi-open kitchen. The noodles are really long and they need to be grabbed by hands into the bowl. A noodle can be as long as 2 meters or even 3. The noodles with lamb sausages need to be blanched in the boiling water. Then dress them with vinegar and chili oil, making it seem so good. The frequent customers often order a bowl of beef head meat with the noodles. The beef head meet is chewy and rich. The garlic sauce and the chili oil adds another dimension to its aroma. A bowl of lamb sausage noodles in the morning of Xining gives you enough calories for the cold. Make you feel full, warm and comfortable!

字幕
<1
00:00:01,680 --> 00:00:02,400
很多人来西宁
Most people are here in Xining

2
00:00:02,400 --> 00:00:04,440
是为了打卡绝美的风景
For the breath-taking views

3
00:00:04,440 --> 00:00:05,920
而雪鱼这次来西宁
But I’m here this time

4
00:00:05,920 --> 00:00:10,280
不仅仅是来看风景 还有品尝大西北的美食
For not only the views, but also to taste the northwestern cuisines

5
00:00:14,800 --> 00:00:17,720
从西安飞到西宁 一下飞机 我就觉得特别冷
I flew from Xi’an to Xining. And I felt so cold the moment I got off the plane

6
00:00:17,720 --> 00:00:22,040
我发现我的手表上 出现了从来没有的数字显示
There appeared a new feature on my watch

7
00:00:22,040 --> 00:00:26,320
我现在在海拔2千多米的高原上
I’m now on an altitude more than 2000 meters

8
00:00:29,360 --> 00:00:32,920
司机师傅告诉我们 在青海旅游就要注意两点
The driver told us there are two important things for visiting Qinghai

9
00:00:32,920 --> 00:00:34,180
一个是防晒
One is sun screening

10
00:00:34,200 --> 00:00:36,720
因为这边的紫外线特别强烈
Because the ultraviolet here is extreme

11
00:00:36,720 --> 00:00:39,640
第二个呢 一定要做好防雨的准备
And the other is rainproof

12
00:00:39,640 --> 00:00:41,960
有的时候 之前可能是晴空万里
Sometimes the sky is clear and shiny

13
00:00:41,960 --> 00:00:44,480
但是雨呢 就是说下就下
But the rain could fall any seconds

14
00:00:48,200 --> 00:00:52,440
接下来雪鱼要去吃的是羊肠面 在当地是比较常见的
I’m going to have some lamb sausage noodles today, which is pretty popular here

15
00:00:52,440 --> 00:00:54,760
名字听起来可能不太精致
It’s not an exquisite name

16
00:00:54,760 --> 00:00:58,920
但是能够称得起当地特色的美食 味道应该不会很差
But it should taste well since it’s the local special

17
00:00:58,920 --> 00:01:03,080
坐出租走吧
Let’s get a taxi

18
00:01:10,120 --> 00:01:12,120
就是这家了，羊肠面
Here it is, lamb sausage noodles

19
00:01:31,220 --> 00:01:32,040
你要啥样的
What can I get you?

20
00:01:32,780 --> 00:01:34,780
一份羊肠面 再加一份牛头肉
An order of lamb sausage noodles with an order of beef head meat

21
00:01:36,960 --> 00:01:38,960
把牛头肉放在另一个碗里
The beef head meat in another bowl, please

22
00:01:41,080 --> 00:01:43,080
看到周围一直注视的目光
Everybody was staring at me

23
00:01:44,000 --> 00:01:47,900
我意识到我可能答非所问
I realized I was answering to not what has been asked

24
00:01:47,940 --> 00:01:49,940
通过不断的比划和重复 我想要的是
I had to repeat and show with hands to let them understand what I wanted

25
00:01:50,560 --> 00:01:52,560
一碗羊肠面和一份牛头肉
An order of lamb sausage noodles with an order of beef head meat

26
00:01:58,800 --> 00:02:00,800
这种摊在桌子上的
These noodles on the table

27
00:02:00,840 --> 00:02:02,840
要不断用手抓 不断散落的
Need constantly grabbing and scattering

28
00:02:02,840 --> 00:02:04,380
金黄色的细面条
They are golden yellow thin noodles

29
00:02:04,840 --> 00:02:06,840
是用鸡蛋 面粉和食用碱做成的
Made of eggs, flour and baking soda

30
00:02:07,180 --> 00:02:09,680
把它煮到七八分熟后 捞出来过凉水
Boil them to medium well and cool them in water

31
00:02:10,120 --> 00:02:12,520
处理好的面条 就会放在店里最显眼的位置
The noodles are then put in the most obvious place once ready

32
00:02:13,400 --> 00:02:16,140
客人点完面 就把面放在沸汤里过几遍
When ordered, the noodles will be blanched a few times in the boiling soup

33
00:02:16,140 --> 00:02:18,140
大约几秒就可以出锅
It will take just a few seconds

34
00:02:18,680 --> 00:02:20,000
如果面上码了肉
If you order noodles with meat

35
00:02:20,280 --> 00:02:22,280
肉呢 也会随面一起进入漏勺
The meat will be in the slotted spoon with the noodles

36
00:02:22,280 --> 00:02:26,020
经历几次漏勺开花 最后一同进入碗中
Blanching a few times and together in the bowl 

37
00:02:48,860 --> 00:02:53,260
现在是调上醋 蒜 辣子 我们就可以端走了
Now they are putting some vinegar, garlic sauce and chili oil in there and it will be ready

38
00:03:13,680 --> 00:03:15,680
今天吃的就是羊肠面
Today we have the lamb sausage noodles

39
00:03:16,080 --> 00:03:19,280
除了面以外，我们还要了一份牛头肉 共消费22元
Besides the noodles, we ordered some beef head meat too. It cost 22 yuan in total

40
00:03:19,800 --> 00:03:22,160
这碗是免费自己盛的汤
This is the free soup

41
00:03:35,920 --> 00:03:38,500
羊肠面 看字面意思就是羊肠加面
Lamb sausage noodles. As the name implies, it’s noodle with lamb sausages

42
00:03:39,360 --> 00:03:44,080
面是提前用个鸡蛋 面粉 食用碱一起和出来的
The dough was made of eggs, flour and baking soda

43
00:03:44,680 --> 00:03:47,380
你看 这边的抓面 一根都有1米长
The noodles here are at least one meter long

44
00:03:47,420 --> 00:03:49,420
最长的能够达到3米
The longest can be 3 meters

45
00:03:49,700 --> 00:03:51,700
每抓一次面都是在做力气活啊
It’s like working out every time they grab them

46
00:03:54,560 --> 00:03:56,560
这么一挑面条 冒着热气
The steam comes out when we pick up the noodles

47
00:03:56,800 --> 00:03:58,800
我们尝一尝吧
Let’s give it a try

48
00:04:01,560 --> 00:04:03,820
这个面条很像武汉的热干面
The noodles are pretty similar to the Wuhan’s hot dry noodles

49
00:04:04,100 --> 00:04:07,060
是干拌的 看起来又很筋道
The noodles seem al dente and the dressing is dry

50
00:04:20,360 --> 00:04:24,500
面条里加了辣子是很香的
The chili oil in the noodles smells so good

51
00:04:26,940 --> 00:04:28,280
没有一点的汤汁
No soup in there at all

52
00:04:29,140 --> 00:04:31,140
面条之间主要靠表面的油来分离开
The noodles are separated by the oil on the surface

53
00:04:34,280 --> 00:04:36,280
来尝尝今天的主角 羊肠
Let’s try today’s special, the lamb sausages

54
00:04:38,800 --> 00:04:43,220
羊肠不是空心的 分肉肠和面肠的
The lamb sausages have meat sausages and dough sausages

55
00:04:43,220 --> 00:04:45,020
像这种颜色比较深的
These sausages are darker in color

56
00:04:45,300 --> 00:04:48,500
里面就是用羊的内脏加调料做出来的
The ingredients are the lamb guts with seasoning

57
00:04:49,220 --> 00:04:51,520
而这个颜色比较浅的
These sausages are lighter in color

58
00:04:52,740 --> 00:04:55,300
就是用豆面糊加调料煮出来的
It’s made of bean flour and seasonings

59
00:04:57,320 --> 00:05:00,280
吃面肠就像吃山药一样，面面的口感
The dough sausages have a starchy taste like Chinese yam

60
00:05:01,980 --> 00:05:04,740
外面的肠衣是脆的 里面是绵的
The outside is crunchy and the inside is delicate

61
00:05:06,940 --> 00:05:09,020
面肠的味道会比较淡一些
The dough sausages taste lighter

62
00:05:10,140 --> 00:05:13,580
肉肠的味道就是胡椒粉的辛辣味道比较重
The meat sausages have a strong taste of pepper

63
00:05:16,040 --> 00:05:19,960
一碗面里的羊肠不多
There’s not many lamb sausages in one order of noodles

64
00:05:20,580 --> 00:05:23,680
已经被我默默地吃掉四五个了
And I’ve already had four or five of them

65
00:05:28,420 --> 00:05:32,000
肉肠挂辣子 吃起来更香 更辣
The sausages with the chili oil taste more spicy and delicious

66
00:05:39,420 --> 00:05:41,420
会吃肠子的人 都知道
Everybody having sausages knows it

67
00:05:42,220 --> 00:05:44,740
像羊肠这种东西 就是把内壁洗干净
To make lamb sausages, first we need to clean the interior

68
00:05:45,240 --> 00:05:48,080
但是一定不要刮这个肠壁油
But leave the intestine fat on there

69
00:05:48,720 --> 00:05:51,400
因为有肠壁油 羊肠吃起来才会更香
It’s the fat that contains the aroma of sausages

70
00:05:51,760 --> 00:05:54,080
总的来说 清洗羊肠 就是要洗的干净
In general, we need to make the intestines clean

71
00:05:54,200 --> 00:05:56,200
但是不能洗的太过于干净
But not too clean

72
00:05:56,320 --> 00:05:58,320
这样的分寸要拿捏好
Need to be careful with that

73
00:06:09,360 --> 00:06:12,940
很多人听到羊肠面这个名字 听起来是很重口的
The name lamb sausage noodles sounds pretty heavy-taste

74
00:06:12,940 --> 00:06:14,900
所以说内心会比较排斥
Some people may be resistant to only the name

75
00:06:14,900 --> 00:06:16,840
但是试一试你会发现
But after trying you’ll find out

76
00:06:17,260 --> 00:06:19,900
它并没有想象的那么黑暗难吃
It’s not too heavy or nasty as you may have imagined

77
00:06:20,540 --> 00:06:23,160
辣子 肉香 面香啊 让你越吃越想吃
You can never have enough of the aroma of chili oil, meat and the noodles

78
00:06:32,660 --> 00:06:35,480
这是个炉子 是用来加热酸汤的
This is a stove to heat up the soup

79
00:06:35,940 --> 00:06:38,400
但它不仅仅是一个炉子 还是一个桌子
It’s also a table

80
00:06:38,760 --> 00:06:43,980
很多人就是围着炉子一边吃面一边喝汤
Many people sit around this stove to have noodles and soup

81
00:06:50,500 --> 00:06:53,940
我们的西宁美食之旅从这期就要开始啦
Our food tasting journey of Xining starts from this episode
