### ISSUE TITLE
【美食作家王刚】后厨的深度清洁 - https://youtu.be/ggnKS91ExwA

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1229]
**视频链接**：https://youtu.be/ggnKS91ExwA

视频时长5:04，预计发布时间为北京时间7月3日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨房深度清洁，厨师长亲自翻新二手厨具，后厨是如何做例行清洁的？用了什么去油污的特殊材料？

简介
大家好，本期视频来给新工作室做一番深度清洁，并且也给大家介绍一下在专业后厨一般是如何做例行清洁的。后厨的卫生至关重要，不仅是对消费者负责，也是对工作环境的负责，所以卫生也是一个厨师长必须要了解并且负责的板块。一般情况下是每个工作日结束后都需要做一次清洁，主要使用无公害的洗洁精将灶台台面，打荷台，水池，地面等区域进行刷洗。然后一周进行一次深度清洁，利用烧碱（氢氧化钠 NaOH）水溶液的碱性和腐蚀性来去除顽固的油渍和污渍，重点清洁位置包括排油烟系统，排水系统，灶台缝隙等特别容易藏污纳垢的地方，这样就能最大程度上保持后厨的卫生。不过在这里提醒大家烧碱是有毒的，所以除非是做好保护和可以确保清洁之后可以完全将烧碱溶液冲洗干净之后再来使用，后厨都有非常专业的排水系统，所以深度清洁过后只要用大量活水冲洗就可以保证没有烧碱残留。

字幕
0:00:00.531,0:00:02.023
哈喽大家好 我是王刚

0:00:02.100,0:00:07.786
我们这里东西已经摆好了 像这些盆盆罐罐也买到了

0:00:08.074,0:00:11.988
反正不知道为什么看到不锈钢的心情就无比的舒畅

0:00:12.937,0:00:17.708
比如说像这后面 这一截全是不锈钢的 而且都是新的

0:00:18.151,0:00:19.479
但是有一个灶是旧的

0:00:19.760,0:00:22.065
这个灶的话因为放的时间比较长

0:00:22.480,0:00:23.787
又有比较多的锈

0:00:23.815,0:00:28.594
然后我今天买了这个 买了一点烧碱

0:00:28.706,0:00:30.554
烧碱来把它洗一下

0:00:30.604,0:00:32.845
还有这个工作台也是旧的 上面还有一些锈

0:00:33.288,0:00:34.862
也给它除一下锈 搞搞卫生

0:00:35.410,0:00:38.783
然后搞好卫生了之后就开始买餐具啊

0:00:38.790,0:00:41.433
买那些东西就可以开火了

0:00:42.761,0:00:45.916
现在我去找了一副眼镜 这个墨镜跟别人借的

0:00:46.233,0:00:48.861
就是等一下烧烧碱的时候戴一下

0:00:49.121,0:00:50.681
然后再戴一副这个胶手套

0:00:51.299,0:00:56.436
我们不建议在家庭里面烧这个烧碱来洗东西

0:00:56.436,0:00:57.392
这个特别危险

0:00:57.694,0:00:59.845
非专业人士切勿模仿

0:01:01.278,0:01:02.199
先把墨镜带上

0:01:14.483,0:01:17.926
我以前烧碱都弄到过眼睛一次 差点瞎了

0:01:19.493,0:01:21.503
因为那个时候太小 不懂事

0:01:31.377,0:01:32.852
好了 我们这个水已经烧开了

0:01:33.091,0:01:34.391
现在放烧碱进去

0:01:35.684,0:01:37.680
放烧碱的时候一定要慢慢 慢慢的放

0:01:37.772,0:01:39.254
一次性放多了它水会满出来

0:01:40.744,0:01:46.678
所以干这个活不建议普通人在家里面做 特别危险

0:01:54.138,0:01:55.909
这个烧碱一下子放进去就化了

0:01:58.594,0:02:00.561
现在已经变成了超强碱水

0:02:01.468,0:02:03.506
给它一点一点的淋在这个上面

0:02:04.391,0:02:05.621
一次不要淋太多

0:02:08.783,0:02:13.569
这个不能接触皮肤 接触皮肤会腐蚀皮肤而且会特别痒

0:02:13.956,0:02:15.980
如果弄破了的话皮肤会烂

0:02:16.907,0:02:18.453
所以一定要小心泼这个

0:02:22.332,0:02:25.192
大家可以看一下这个锈 一下子就掉完了

0:02:26.914,0:02:27.898
除锈特别好

0:02:29.191,0:02:34.188
这个只适合我们厨房里面这样子做 不适合家庭的

0:02:34.848,0:02:36.471
家庭操作起来特别危险

0:02:37.715,0:02:38.755
也不建议这样子去干

0:02:41.081,0:02:42.972
而且这个除油特别厉害

0:02:45.129,0:02:47.547
除锈除油都可以

0:02:50.421,0:02:56.015
也有的人专门做这个的 他是用那个高温手枪给它冲

0:02:57.111,0:02:58.383
里面就是烧碱

0:03:00.702,0:03:02.438
这个千万不要触碰到皮肤

0:03:15.987,0:03:21.412
好啦 我们把这一锅水端到那边去洗那个锅 这一锅碱水

0:03:25.691,0:03:26.732
在下面不好洗

0:03:26.858,0:03:27.926
我站上去吧

0:03:46.373,0:03:49.915
好啦 现在我们冲水啦

0:03:51.060,0:03:53.689
这个油渍呀是很容易去掉的你看

0:03:54.630,0:03:56.008
这冲一下特别干净

0:03:56.479,0:03:58.074
冲一下这个上面

0:04:03.246,0:04:05.537
好了 我们今天就简简单单弄一下

0:04:06.415,0:04:11.566
一般我们在厨房里面是每天都要用洗洁精这样子搞一下卫生

0:04:11.566,0:04:14.722
然后一个星期要用烧碱来烧

0:04:14.722,0:04:19.803
然后这个不锈钢上面全部都要用烧碱来给它去一下油渍

0:04:21.939,0:04:25.087
我们这个如果说长时间不弄的话

0:04:25.396,0:04:27.722
一旦这个油多了就很难洗

0:04:28.039,0:04:30.091
如果我们一个星期做一次大扫除的话

0:04:30.850,0:04:33.309
基本上就不会有什么油 特别干净

0:04:33.731,0:04:37.561
就想说工作的时候特别的心情比较舒畅一点

0:04:38.432,0:04:41.869
如果摸到哪儿都是油哪儿都粘手的话可能就很不爽

0:04:42.375,0:04:44.152
好了 本期视频就到这里了 拜拜

0:04:46.057,0:04:49.781
然后每天搞一点 再搞几次就可以了


```

**Comment by Zui409** [comment]
认领

**Comment by Zui409** [comment]
#标题（翻译主要意思即可，不要超过 100 个字符）
#厨房深度清洁，厨师长亲自翻新二手厨具，后厨是如何做例行清洁的？用了什么去油污的特殊材料？
Kitchen deep cleaning! How to refurbish kitchen equipment and remove cooking grease?


#简介
#大家好，本期视频来给新工作室做一番深度清洁，并且也给大家介绍一下在专业后厨一般是如何做例行清洁的。后厨的卫生至关重要，不仅是对消费者负责，也是对工作环境的负责，所以卫生也是一个厨师长必须要了解并且负责的板块。一般情况下是每个工作日结束后都需要做一次清洁，主要使用无公害的洗洁精将灶台台面，打荷台，水池，地面等区域进行刷洗。然后一周进行一次深度清洁，利用烧碱（氢氧化钠 NaOH）水溶液的碱性和腐蚀性来去除顽固的油渍和污渍，重点清洁位置包括排油烟系统，排水系统，灶台缝隙等特别容易藏污纳垢的地方，这样就能最大程度上保持后厨的卫生。不过在这里提醒大家烧碱是有毒的，所以除非是做好保护和可以确保清洁之后可以完全将烧碱溶液冲洗干净之后再来使用，后厨都有非常专业的排水系统，所以深度清洁过后只要用大量活水冲洗就可以保证没有烧碱残留。
Hello everyone, in today’s episode I will show you guys how we usually do routine cleaning in a professional kitchen. Hygiene in the kitchen is vital, not only for the customers but also for our working environment. So hygiene is also an aspect that a head chef must know and be responsible for. Usually, cleaning is required at the end of each working day. We normally use harmless detergent to clean the wok ranges, prep tables, sinks, and the floor. Deep cleaning of the kitchen is carried out once a week. We use caustic soda (sodium hydroxide, NaOH) solution to remove stubborn grease and stains. The key cleaning locations include the fume extraction system, the drainage system, the stove areas, and other areas that are particularly susceptible to trapping grease and stains. This will keep the kitchen as sanitary as possible. But here I have to remind you that caustic soda is TOXIC. Make sure you are well protected and can ensure that caustic soda can be completely rinsed off before you use it. Our kitchen has a professional drainage system, so we can ensure that there is no caustic soda residue as long as we use a lot of live water to rinse.

#字幕
0:00:00.531,0:00:02.023
#哈喽大家好 我是王刚
Hi everyone, I am Wang Gang

0:00:02.100,0:00:07.786
#我们这里东西已经摆好了 像这些盆盆罐罐也买到了
Look we’ve got all utensils and cookware ready here 

0:00:08.074,0:00:11.988
#反正不知道为什么看到不锈钢的心情就无比的舒畅
Anyway, I don’t know why I feel so good when I see stainless steel

0:00:12.937,0:00:17.708
#比如说像这后面 这一截全是不锈钢的 而且都是新的
Like those things behind me, they are all made of stainless steel and are all brand new

0:00:18.151,0:00:19.479
#但是有一个灶是旧的
But one of the stoves is old

0:00:19.760,0:00:22.065
#这个灶的话因为放的时间比较长
That stove has been idle for a long time

0:00:22.480,0:00:23.787
#又有比较多的锈
and is covered in rust

0:00:23.815,0:00:28.594
#然后我今天买了这个 买了一点烧碱
So today I bought some caustic soda

0:00:28.706,0:00:30.554
#烧碱来把它洗一下
to remove the rust from it

0:00:30.604,0:00:32.845
#还有这个工作台也是旧的 上面还有一些锈
This old workbench also has rust on it

0:00:33.288,0:00:34.862
#也给它除一下锈 搞搞卫生
Let’s get it cleaned 

0:00:35.410,0:00:38.783
#然后搞好卫生了之后就开始买餐具啊
When I’m done with the cleaning, I’ll go shopping for more utensils and tableware

0:00:38.790,0:00:41.433
#买那些东西就可以开火了
Then I can start cooking in here once I get everything I need. 

0:00:42.761,0:00:45.916
#现在我去找了一副眼镜 这个墨镜跟别人借的
I borrowed a pair of sunglasses from someone

0:00:46.233,0:00:48.861
#就是等一下烧烧碱的时候戴一下
to wear when we prepare the caustic soda 

0:00:49.121,0:00:50.681
#然后再戴一副这个胶手套
Also I need to wear a pair of rubber gloves for protection

0:00:51.299,0:00:56.436
#我们不建议在家庭里面烧这个烧碱来洗东西
We don’t recommend using caustic soda at home for kitchen cleaning  

0:00:56.436,0:00:57.392
#这个特别危险
This is really DANGEROUS

0:00:57.694,0:00:59.845
#非专业人士切勿模仿
For non-professionals please do not imitate 

0:01:01.278,0:01:02.199
#先把墨镜带上
Let’s put on the sunglasses first

0:01:14.483,0:01:17.926
#我以前烧碱都弄到过眼睛一次 差点瞎了
I’ve got caustic soda in my eye once before and I almost went blind

0:01:19.493,0:01:21.503
#因为那个时候太小 不懂事
because I was too young too naive 

0:01:31.377,0:01:32.852
#好了 我们这个水已经烧开了
Okay, the water is boiling now

0:01:33.091,0:01:34.391
#现在放烧碱进去
Now put the caustic soda in

0:01:35.684,0:01:37.680
#放烧碱的时候一定要慢慢 慢慢的放
Make sure you add it slowly and gently

0:01:37.772,0:01:39.254
#一次性放多了它水会满出来
If you add too much of it at once, the water will spill

0:01:40.744,0:01:46.678
#所以干这个活不建议普通人在家里面做 特别危险
That’s why we don’t recommend people to do this kind of work at home. It’s very DANGEROUS.

0:01:54.138,0:01:55.909
#这个烧碱一下子放进去就化了
The caustic soda melts immediately

0:01:58.594,0:02:00.561
#现在已经变成了超强碱水
It’s now a super-alkaline solution 

0:02:01.468,0:02:03.506
#给它一点一点的淋在这个上面
Pour it on the top little by little

0:02:04.391,0:02:05.621
#一次不要淋太多
Not too much at a time 

0:02:08.783,0:02:13.569
#这个不能接触皮肤 接触皮肤会腐蚀皮肤而且会特别痒
It can erode your skin and make you feel itchy so you should avoid contacting it with skin 

0:02:13.956,0:02:15.980
#如果弄破了的话皮肤会烂 
It may also rot your skin

0:02:16.907,0:02:18.453
#所以一定要小心泼这个
So please be careful when you pour it.

0:02:22.332,0:02:25.192
#大家可以看一下这个锈 一下子就掉完了
As you can see, the rust can be easily scrapped off. 

0:02:26.914,0:02:27.898
#除锈特别好
It does an excellent job on removing rust

0:02:29.191,0:02:34.188
#这个只适合我们厨房里面这样子做 不适合家庭的
But this method is only suitable for our kitchen, not for household use

0:02:34.848,0:02:36.471
#家庭操作起来特别危险
It’s extremely DANGEROUS to operate at home

0:02:37.715,0:02:38.755
#也不建议这样子去干
I wouldn’t recommend you do this

0:02:41.081,0:02:42.972
#而且这个除油特别厉害
This is also an excellent grease remover 

0:02:45.129,0:02:47.547
#除锈除油都可以
It works well on removing both rust and grease

0:02:50.421,0:02:56.015
#也有的人专门做这个的 他是用那个高温手枪给它冲
Professional kitchen cleaning normally uses a high-pressure washer 

0:02:57.111,0:02:58.383
#里面就是烧碱
with caustic soda solution  

0:03:00.702,0:03:02.438
#这个千万不要触碰到皮肤
Don’t let it touch your skin

0:03:15.987,0:03:21.412
#好啦 我们把这一锅水端到那边去洗那个锅 这一锅碱水
Okay, let’s bring this pot of alkaline solution over there to clean that wok range

0:03:25.691,0:03:26.732
#在下面不好洗
It’s not easy to clean here

0:03:26.858,0:03:27.926
#我站上去吧
I’ll stand up there

0:03:46.373,0:03:49.915
#好啦 现在我们冲水啦
All right, let’s flush it with water 

0:03:51.060,0:03:53.689
#这个油渍呀是很容易去掉的你看
Look how easy removing this grease is!

0:03:54.630,0:03:56.008
#这冲一下特别干净
It becomes very clean after a quick rinse

0:03:56.479,0:03:58.074
#冲一下这个上面
Let’s rinse the top part a bit

0:04:03.246,0:04:05.537
#好了 我们今天就简简单单弄一下
Okay, let’s make this simple today

0:04:06.415,0:04:11.566
#一般我们在厨房里面是每天都要用洗洁精这样子搞一下卫生
Usually we use detergent to clean the kitchen everyday 

0:04:11.566,0:04:14.722
#然后一个星期要用烧碱来烧
We also use caustic soda every week 
 
0:04:14.722,0:04:19.803
#然后这个不锈钢上面全部都要用烧碱来给它去一下油渍
to remove the grease on the stainless steel

0:04:21.939,0:04:25.087
#我们这个如果说长时间不弄的话
If we get lazy for a long time,

0:04:25.396,0:04:27.722
#一旦这个油多了就很难洗
the grease will accumulate and become hard to wash

0:04:28.039,0:04:30.091
#如果我们一个星期做一次大扫除的话
If we do deep cleaning every week,

0:04:30.850,0:04:33.309
#基本上就不会有什么油 特别干净
we can keep our kitchen clean and tidy 

0:04:33.731,0:04:37.561
#就想说工作的时候特别的心情比较舒畅一点
And it makes me feel much better when I’m cooking

0:04:38.432,0:04:41.869
#如果摸到哪儿都是油哪儿都粘手的话可能就很不爽
I hate the feeling of grease being everywhere and sticking to my hands 

0:04:42.375,0:04:44.152
#好了 本期视频就到这里了 拜拜
Okay, that’s it for today’s episode. Bye!

0:04:46.057,0:04:49.781
#然后每天搞一点 再搞几次就可以了
We’ll continue tidying for a few more days and then the place should be ready
