### ISSUE TITLE
[老饭骨] 老醋花生 - https://youtu.be/d_FmTf3cv-k

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1234]
**视频链接**：https://youtu.be/d_FmTf3cv-k

发布日期：北京时间7月3日晚上10点。时长06:12。

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【國宴大師•老醋花生】喝酒聊天必備涼菜，香脆又開胃，秘制老醋汁配方公開，別小看小菜兒！|老飯骨

简介
小友們好，今天我們的涼菜專家大師姐要教大家一道夏日聊天喝酒、居家生活必備的小菜兒——老醋花生。這老醋汁可不簡單，是大師姐從業這麼多年來的一個心得體會，用到了三種不同的醋！那麼究竟是哪三種呢，小友們帶着疑問仔細看看視頻吧！

字幕
1
00:00:00,000 --> 00:00:02,480
三种不同的醋  口感是不一样的

2
00:00:02,480 --> 00:00:04,400
味道出来了

3
00:00:04,600 --> 00:00:08,720
这个老醋汁是我干了这么多年凉菜

4
00:00:08,720 --> 00:00:10,960
自己的一个心得体会

5
00:00:10,960 --> 00:00:13,160
 

6
00:00:13,160 --> 00:00:14,720
我这胃已经炸开了

7
00:00:14,880 --> 00:00:18,120
喝酒的小菜儿 老醋花生

8
00:00:18,120 --> 00:00:21,480
今天要用的花生是这种小粒的花生

9
00:00:21,480 --> 00:00:22,960
第一步得把这花生

10
00:00:22,960 --> 00:00:24,560
咱们得先轻轻洗一下

11
00:00:24,560 --> 00:00:26,520
为了让它下油锅以后

12
00:00:26,520 --> 00:00:29,520
不至于那么快就变颜色

13
00:00:29,520 --> 00:00:32,880
炸花生的时候最好用花生油

14
00:00:32,880 --> 00:00:35,920
我师父都给我倒好了 花生油香啊

15
00:00:35,920 --> 00:00:41,720
凉锅凉油凉花生下锅

16
00:00:41,720 --> 00:00:46,000
怎么炸到合适呢 咱们在里边扔瓣儿蒜

17
00:00:46,000 --> 00:00:49,920
什么时候这个蒜表面金黄了熟透了

18
00:00:49,920 --> 00:00:52,880
这个花生也就基本上差不多了

19
00:00:52,880 --> 00:00:55,840
小火 在这给我们网友提示一下

20
00:00:55,840 --> 00:00:58,840
你看这花生下去以后它是冒大泡的

21
00:00:58,840 --> 00:01:01,200
等我们越炸的时候

22
00:01:01,200 --> 00:01:03,200
这油越来越变成小泡

23
00:01:03,200 --> 00:01:05,800
就说明这个水分少了

24
00:01:05,800 --> 00:01:07,280
这个不是时间的事

25
00:01:07,280 --> 00:01:11,360
是要把水分要炸干 这声音有点脆了啊

26
00:01:11,360 --> 00:01:13,200
您看这个蒜已经金黄了

27
00:01:13,200 --> 00:01:15,400
我觉得应该可以捞了

28
00:01:16,400 --> 00:01:19,200
然后咱们这盘子上放张吸油纸

29
00:01:19,200 --> 00:01:21,560
把这油吸一下

30
00:01:21,560 --> 00:01:25,560
咱们把它摊在盘子里边 吸油 晾凉

31
00:01:25,560 --> 00:01:29,000
然后这儿还有一个小关键点

32
00:01:29,000 --> 00:01:31,240
咱们滴两滴白酒

33
00:01:31,240 --> 00:01:34,440
可以保持这花生米酥脆

34
00:01:34,440 --> 00:01:38,640
咱们把花生拌匀 一定晾凉吹干

35
00:01:40,080 --> 00:01:42,800
下一步咱们兑一个老醋汁

36
00:01:42,800 --> 00:01:46,920
这个老醋汁是我干了这么多年凉菜

37
00:01:46,920 --> 00:01:49,440
自己的一个心得体会

38
00:01:49,440 --> 00:01:50,880
这一共用了三种醋

39
00:01:50,880 --> 00:01:54,520
陈醋 香醋 还有清香米醋

40
00:01:54,520 --> 00:01:57,760
咱们先在这里边放 糖

41
00:01:57,760 --> 00:02:04,560
这糖要多少 糖有一百克

42
00:02:04,560 --> 00:02:10,280
咱们再来点盐 咱们适量

43
00:02:10,280 --> 00:02:16,080
这陈醋可以二百克

44
00:02:16,080 --> 00:02:18,120
我在这儿就不倒那么多了

45
00:02:18,120 --> 00:02:22,240
咱们香醋 就是镇江香醋

46
00:02:22,240 --> 00:02:25,320
刚才咱们（陈醋）倒了有一百克

47
00:02:25,320 --> 00:02:29,680
咱们这香醋有六十克就可以了

48
00:02:29,680 --> 00:02:34,080
这清香米醋有二十克 酸味稳定

49
00:02:34,080 --> 00:02:36,640
三种不同的醋口感是不一样的

50
00:02:36,640 --> 00:02:37,720
酸度也不一样

51
00:02:37,720 --> 00:02:41,200
然后咱们再滴一点香油

52
00:02:41,200 --> 00:02:43,720
这醋汁基本就调好了

53
00:02:43,720 --> 00:02:46,000
大爷 葱头 尖椒

54
00:02:46,000 --> 00:02:47,920
花生也差不多了

55
00:02:47,920 --> 00:02:50,000

56
00:02:50,000 --> 00:02:53,800
酥脆 这火候拿捏的准确

57
00:02:53,800 --> 00:02:55,920
行了别老掂了再掂都得给掂碎了

58
00:02:55,920 --> 00:02:56,760
要听这声音啊

59
00:02:56,760 --> 00:02:59,920
来咱们把这汁浇到里边 拌一下

60
00:02:59,920 --> 00:03:01,440
齐了

61
00:03:01,440 --> 00:03:04,160
你看看这味道出来了

62
00:03:06,640 --> 00:03:09,040
好 照相

63
00:03:09,040 --> 00:03:12,120
带汁儿的有味儿的 小菜大智慧

64
00:03:12,120 --> 00:03:14,240
别小看小菜

65
00:03:14,240 --> 00:03:16,520

66
00:03:16,520 --> 00:03:18,920
脆吗 那当然脆了

67
00:03:18,920 --> 00:03:21,840
现在我这胃已经炸开了

68
00:03:21,840 --> 00:03:24,080
小菜 也要做的专业

69
00:03:24,080 --> 00:03:25,920
三种醋的这种调和

70
00:03:25,920 --> 00:03:28,200
到嘴里这种清脆

71
00:03:28,200 --> 00:03:29,960
这个真好

72
00:03:29,960 --> 00:00:02,000

73
00:03:37,280 --> 00:03:38,760
这网友子淞问

74
00:03:38,760 --> 00:03:40,080
做宫保鸡丁的时候

75
00:03:40,080 --> 00:03:42,360
滑油和不滑油有什么区别

76
00:03:42,360 --> 00:03:43,720
然后还有有人做的时候

77
00:03:43,720 --> 00:03:44,560
加辣椒面

78
00:03:44,560 --> 00:03:46,720
有的时候在最后加辣椒油

79
00:03:46,720 --> 00:03:48,520
这个味道上又有什么区别

80
00:03:48,520 --> 00:03:49,160
滑油

81
00:03:49,160 --> 00:03:50,240
与不滑油

82
00:03:50,240 --> 00:03:52,280
两种烹调方法

83
00:03:52,280 --> 00:03:52,960
过去呢

84
00:03:52,960 --> 00:03:54,840
就是讲究卧油煸炒

85
00:03:54,840 --> 00:03:56,840
但是这个煸炒加辣椒面

86
00:03:56,840 --> 00:03:58,520
它炒出的东西更香

87
00:03:58,520 --> 00:04:01,800
但是如果说要滑油的话

88
00:04:01,800 --> 00:04:03,960
可能要出菜形式

89
00:04:03,960 --> 00:04:05,560
要比他要整齐

90
00:04:05,560 --> 00:04:06,360
是吧

91
00:04:06,360 --> 00:04:09,760
而且油滑的要比那个煸炒要有把握

92
00:04:09,760 --> 00:04:10,440
还要嫩

93
00:04:10,440 --> 00:04:13,240
加辣椒面是过去这些老的 大的饭店

94
00:04:13,240 --> 00:04:15,160
当时北京饭店和前门饭店

95
00:04:15,160 --> 00:04:16,320
是最火的

96
00:04:16,320 --> 00:04:17,800
因为那是十大饭店

97
00:04:17,800 --> 00:04:18,840
十大饭店是吧

98
00:04:18,840 --> 00:04:21,280
而且那些那些老师傅

99
00:04:21,280 --> 00:04:21,880
都是

100
00:04:21,880 --> 00:04:23,720
国家给调过来

101
00:04:23,720 --> 00:04:24,760
原籍四川的

102
00:04:24,760 --> 00:04:26,360
他们也是继承了老一辈的

103
00:04:26,360 --> 00:04:27,880
这种传统技法

104
00:04:27,880 --> 00:04:29,520
煸完了之后

105
00:04:29,520 --> 00:04:30,520
加上辣椒面

106
00:04:30,520 --> 00:04:31,640
加辣椒面

107
00:04:31,640 --> 00:04:35,160
它有一种辣椒的那种清香味

108
00:04:35,160 --> 00:04:37,800
和鸡丁揉在一块

109
00:04:37,800 --> 00:04:39,960
那种香气更浓一些

110
00:04:39,960 --> 00:04:41,480
但是它不好在哪呢

111
00:04:43,400 --> 00:04:44,640
这煸辣椒面

112
00:04:44,640 --> 00:04:47,000
和卧油煸炒

113
00:04:47,000 --> 00:04:49,400
这需要你有一定的功夫了

114
00:04:49,400 --> 00:04:50,840
如果说

115
00:04:50,840 --> 00:04:51,800
您的功夫差点

116
00:04:51,800 --> 00:04:52,920
可能是辣椒面

117
00:04:52,920 --> 00:04:54,560
可能就煸糊了

118
00:04:54,560 --> 00:04:55,880
或者鸡丁的出来

119
00:04:55,880 --> 00:04:57,080
掌握不好的油温的

120
00:04:57,080 --> 00:04:58,640
他就不嫩了

121
00:04:58,640 --> 00:05:00,240
这需要有一定的难度

122
00:05:00,240 --> 00:05:02,240
但是滑炒相对来讲就难度

123
00:05:02,240 --> 00:05:04,920
稍微低一点是吧

124
00:05:04,920 --> 00:05:07,160
最后放辣椒油的话

125
00:05:07,160 --> 00:05:09,560
辣椒油是现代的产物

126
00:05:09,560 --> 00:05:10,280
不是过去的

127
00:05:10,280 --> 00:05:12,840
它以胡辣 小荔枝为口的

128
00:05:12,840 --> 00:05:14,960
这种口味是吧

129
00:05:14,960 --> 00:05:18,320
然后改成现在有点大甜酸了

130
00:05:18,320 --> 00:05:19,360
大甜酸之后

131
00:05:19,360 --> 00:05:20,240
他就炼红油

132
00:05:20,240 --> 00:05:22,000
炼红油第一省事

133
00:05:22,000 --> 00:05:23,080
第二个颜色漂亮

134
00:05:23,080 --> 00:05:26,720
是现代版的这种产物

135
00:05:26,720 --> 00:05:28,800
吃起来的味道还是有些

136
00:05:28,800 --> 00:05:29,840
有些区别

137
00:05:31,240 --> 00:05:32,840
要辣干辣的那种

138
00:05:35,280 --> 00:05:37,560
他们在制作红油的时候

139
00:05:37,560 --> 00:05:39,960
也加了一些特殊的香料

140
00:05:40,680 --> 00:05:41,880
追求的是颜色

141
00:05:44,920 --> 00:05:45,440
这就是不一样

142
00:05:45,440 --> 00:05:47,840
两位拥有60多万赞的人就是不一样

143
00:05:47,840 --> 00:05:49,080
这气色

144
00:05:53,480 --> 00:05:55,200
别唱了大爷

145
00:05:55,200 --> 00:05:56,000
开始

146
00:05:56,000 --> 00:05:56,680
对不起啊

147
00:05:56,680 --> 00:05:57,280
等一下

148
00:05:58,080 --> 00:05:59,520
我录上了吗

149
00:05:59,520 --> 00:06:00,480
您自己都不在线上

150
00:06:02,160 --> 00:06:03,280
线下的你

151
00:06:03,280 --> 00:06:03,520

**Comment by immoonancient** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【國宴大師•老醋花生】喝酒聊天必備涼菜，香脆又開胃，秘制老醋汁配方公開，別小看小菜兒！|老飯骨
State Banquet Master Chefs - Peanuts in Aged Vinegar, a Must-Have Appetizing Drunk Food!

简介

小友們好，今天我們的涼菜專家大師姐要教大家一道夏日聊天喝酒、居家生活必備的小菜兒——老醋花生。這老醋汁可不簡單，是大師姐從業這麼多年來的一個心得體會，用到了三種不同的醋！那麼究竟是哪三種呢，小友們帶着疑問仔細看看視頻吧！

Hello friends, today our cold dish specialist Da Shi Jie is gonna show you "Lao Cu Hua Sheng" ("Peanuts in Aged Vinegar"), a tiny dish that you must have when chatting and drinking in summers. The vinegar sauce is nowhere simple, but instead, it's the essense of the many years Da Shi Jie spent in making cold dishes. Three different kinds of vinegars are used! If you want to know which three types exactly, check it out in the video!

字幕
1
00:00:00,000 --> 00:00:02,480
三种不同的醋  口感是不一样的
Three different kinds of vinegar. They taste differently

2
00:00:02,480 --> 00:00:04,400
味道出来了
The scent has come out

3
00:00:04,600 --> 00:00:08,720
这个老醋汁是我干了这么多年凉菜
This vinegar sauce is from my years of experience of making cold dishes

4
00:00:08,720 --> 00:00:10,960
自己的一个心得体会
My own experience and understanding

5
00:00:10,960 --> 00:00:13,160
 

6
00:00:13,160 --> 00:00:14,720
我这胃已经炸开了
It's exploding in my stomach

7
00:00:14,880 --> 00:00:18,120
喝酒的小菜儿 老醋花生
A drunk food, "Lao Cu Hua Sheng" ("peanuts in aged vinegar")

8
00:00:18,120 --> 00:00:21,480
今天要用的花生是这种小粒的花生
注：不太确定“小粒花生”这样译对不对，请检查
Today we're gonna use peanuts of small granules

9
00:00:21,480 --> 00:00:22,960
第一步得把这花生
First of all

10
00:00:22,960 --> 00:00:24,560
咱们得先轻轻洗一下
We need to rinse the peanuts for a bit

11
00:00:24,560 --> 00:00:26,520
为了让它下油锅以后
So that when deep frying

12
00:00:26,520 --> 00:00:29,520
不至于那么快就变颜色
Their color doesn't change so quickly

13
00:00:29,520 --> 00:00:32,880
炸花生的时候最好用花生油
It's best to fry peanuts in peanut oil

14
00:00:32,880 --> 00:00:35,920
我师父都给我倒好了 花生油香啊
- My master has poured it out already
- Peanut oil smells great

15
00:00:35,920 --> 00:00:41,720
凉锅凉油凉花生下锅
Cold peanuts into cold wok and cold oil

16
00:00:41,720 --> 00:00:46,000
怎么炸到合适呢 咱们在里边扔瓣儿蒜
How do we know when they are fried well? We put a clove of garlic

17
00:00:46,000 --> 00:00:49,920
什么时候这个蒜表面金黄了熟透了
When the garlic has turned golden brown and fully cooked

18
00:00:49,920 --> 00:00:52,880
这个花生也就基本上差不多了
The peanuts should also be good enough

19
00:00:52,880 --> 00:00:55,840
小火 在这给我们网友提示一下
- Low heat
- Here's a tip for our friends

20
00:00:55,840 --> 00:00:58,840
你看这花生下去以后它是冒大泡的
As you see, when we put the peanuts in, the bubbles are large

21
00:00:58,840 --> 00:01:01,200
等我们越炸的时候
As we fry longer and longer

22
00:01:01,200 --> 00:01:03,200
这油越来越变成小泡
The bubbles become smallers

23
00:01:03,200 --> 00:01:05,800
就说明这个水分少了
It means there's less water left

24
00:01:05,800 --> 00:01:07,280
这个不是时间的事
This is not about the time

25
00:01:07,280 --> 00:01:11,360
是要把水分要炸干 这声音有点脆了啊
- It's about getting rid of the water completely
- It sounds a bit crunchy already

26
00:01:11,360 --> 00:01:13,200
您看这个蒜已经金黄了
As you see, the garlic has turned golden brown

27
00:01:13,200 --> 00:01:15,400
我觉得应该可以捞了
I think we can take them out

28
00:01:16,400 --> 00:01:19,200
然后咱们这盘子上放张吸油纸
Then we put a piece of oil-aborbing paper on this tray

29
00:01:19,200 --> 00:01:21,560
把这油吸一下
To aborb some oil

30
00:01:21,560 --> 00:01:25,560
咱们把它摊在盘子里边 吸油 晾凉
Let them rest in the tray, oil absorbed and cooled

31
00:01:25,560 --> 00:01:29,000
然后这儿还有一个小关键点
And then we have a key step

32
00:01:29,000 --> 00:01:31,240
咱们滴两滴白酒
We spray a few drops of baijiu liquor

33
00:01:31,240 --> 00:01:34,440
可以保持这花生米酥脆
It helps keeping the peanuts crunchy

34
00:01:34,440 --> 00:01:38,640
咱们把花生拌匀 一定晾凉吹干
Let's mix the peanuts well. Must be cooled and fan-dried

35
00:01:40,080 --> 00:01:42,800
下一步咱们兑一个老醋汁
Next, we prepare a "aged vinegar sauce"

36
00:01:42,800 --> 00:01:46,920
这个老醋汁是我干了这么多年凉菜
This vinegar sauce is from my years of experience of making cold dishes

37
00:01:46,920 --> 00:01:49,440
自己的一个心得体会
My own experience and understanding

38
00:01:49,440 --> 00:01:50,880
这一共用了三种醋
We have three kinds of vinegar here

39
00:01:50,880 --> 00:01:54,520
陈醋 香醋 还有清香米醋
"Chencu" aged vinegar, "Xiangcu" vinegar, and rice vinegar

40
00:01:54,520 --> 00:01:57,760
咱们先在这里边放 糖
First put in some sugar

41
00:01:57,760 --> 00:02:04,560
这糖要多少 糖有一百克
- How much sugar?
- 100g of sugar

42
00:02:04,560 --> 00:02:10,280
咱们再来点盐 咱们适量
Then we add some salt to taste

43
00:02:10,280 --> 00:02:16,080
这陈醋可以二百克
We can put up to 200g of "Chencu" vinegar

44
00:02:16,080 --> 00:02:18,120
我在这儿就不倒那么多了
This time we don't need that much 

45
00:02:18,120 --> 00:02:22,240
咱们香醋 就是镇江香醋
"Xiangcu" vinegar. That's Zhenjiang vinegar

46
00:02:22,240 --> 00:02:25,320
刚才咱们（陈醋）倒了有一百克
We just added about 100g of "Chencu" vinegar

47
00:02:25,320 --> 00:02:29,680
咱们这香醋有六十克就可以了
For "Xiangcu" vinegar, 60g are enough

48
00:02:29,680 --> 00:02:34,080
这清香米醋有二十克 酸味稳定
20g of rice vinegar, with a stable acidity

49
00:02:34,080 --> 00:02:36,640
三种不同的醋口感是不一样的
Three different kinds of vinegar. They taste differently

50
00:02:36,640 --> 00:02:37,720
酸度也不一样
Their acidities are different, too

51
00:02:37,720 --> 00:02:41,200
然后咱们再滴一点香油
Then add a few drops of sesame oil

52
00:02:41,200 --> 00:02:43,720
这醋汁基本就调好了
Now the vinegar sauce should be done

53
00:02:43,720 --> 00:02:46,000
大爷 葱头 尖椒
- Da Ye!
- Shallots, and chili peppers

54
00:02:46,000 --> 00:02:47,920
花生也差不多了
The peanuts should also be good now

55
00:02:47,920 --> 00:02:50,000

56
00:02:50,000 --> 00:02:53,800
酥脆 这火候拿捏的准确
Crunchy! Cooked to the right degree accurately!

57
00:02:53,800 --> 00:02:55,920
行了别老掂了再掂都得给掂碎了
Alright, you can stop tossing. You'll break them if you keep tossing

58
00:02:55,920 --> 00:02:56,760
要听这声音啊
We need to hear the sound

59
00:02:56,760 --> 00:02:59,920
来咱们把这汁浇到里边 拌一下
Now let's pour the sauce in, and mix it

60
00:02:59,920 --> 00:03:01,440
齐了
Finished

61
00:03:01,440 --> 00:03:04,160
你看看这味道出来了
The scent has come out

62
00:03:06,640 --> 00:03:09,040
好 照相
Good, take a picture

63
00:03:09,040 --> 00:03:12,120
带汁儿的有味儿的 小菜大智慧
The sauce and the flavor. Wisdom hidden in a tiny dish

64
00:03:12,120 --> 00:03:14,240
别小看小菜
Don't look down upon tiny dishes

65
00:03:14,240 --> 00:03:16,520

66
00:03:16,520 --> 00:03:18,920
脆吗 那当然脆了
- Is it crunchy?
- Crunchy, of course

67
00:03:18,920 --> 00:03:21,840
现在我这胃已经炸开了
It's exploding in my stomach

68
00:03:21,840 --> 00:03:24,080
小菜 也要做的专业
Even a tiny dish should still be done in the professional way

69
00:03:24,080 --> 00:03:25,920
三种醋的这种调和
The mixing of the three vinegars

70
00:03:25,920 --> 00:03:28,200
到嘴里这种清脆
The crunchiness in the mouth

71
00:03:28,200 --> 00:03:29,960
这个真好
This is so good

72
00:03:29,960 --> 00:00:02,000

73
00:03:37,280 --> 00:03:38,760
这网友子淞问
Our audience Zisong asks

74
00:03:38,760 --> 00:03:40,080
做宫保鸡丁的时候
When making Kung Pao Chicken

75
00:03:40,080 --> 00:03:42,360
滑油和不滑油有什么区别
What's the difference between "Hua You" and not "Hua You"?
("Hua You": Parcook the ingredient by slightly frying in oil)

76
00:03:42,360 --> 00:03:44,560
然后还有有人做的时候
And some people add chili powder

78
00:03:44,560 --> 00:03:46,720
有的时候在最后加辣椒油
While some others add chili oil when finishing

79
00:03:46,720 --> 00:03:48,520
这个味道上又有什么区别
What are the different flavors?

80
00:03:48,520 --> 00:03:49,160
滑油
Hua You

81
00:03:49,160 --> 00:03:50,240
与不滑油
Or not Hua You

82
00:03:50,240 --> 00:03:52,280
两种烹调方法
Two different methods

83
00:03:52,280 --> 00:03:52,960
过去呢
In the past

84
00:03:52,960 --> 00:03:54,840
就是讲究卧油煸炒
We want dry stir frying in the "Wo You" style
("Wo You": All cooking done continuously without parcooking)

85
00:03:54,840 --> 00:03:56,840
但是这个煸炒加辣椒面
However, if you add chili powder when dry stir frying

86
00:03:56,840 --> 00:03:58,520
它炒出的东西更香
The food is more fragrant

87
00:03:58,520 --> 00:04:01,800
但是如果说要滑油的话
If you Hua You instead

88
00:04:01,800 --> 00:04:03,960
可能要出菜形式
The presence of the dish is probably

89
00:04:03,960 --> 00:04:05,560
要比他要整齐
Neater than the other method

90
00:04:05,560 --> 00:04:06,360
是吧
Yeah

91
00:04:06,360 --> 00:04:09,760
而且油滑的要比那个煸炒要有把握
And Hua You is easier to master than dry stir frying

92
00:04:09,760 --> 00:04:10,440
还要嫩
It's also more tender

93
00:04:10,440 --> 00:04:13,240
加辣椒面是过去这些老的 大的饭店
Adding chili powder is what the old, big restaurants do in the past

94
00:04:13,240 --> 00:04:15,160
当时北京饭店和前门饭店
Like Beijing Hotel and Qianmen Hotel

95
00:04:15,160 --> 00:04:16,320
是最火的
The most popular ones at that time

96
00:04:16,320 --> 00:04:17,800
因为那是十大饭店
Because they are among the top ten restaurants

97
00:04:17,800 --> 00:04:18,840
十大饭店是吧
Top ten restaurants, are they?

98
00:04:18,840 --> 00:04:21,280
而且那些那些老师傅
And all those experienced chefs

99
00:04:21,280 --> 00:04:21,880
都是
They were like

100
00:04:21,880 --> 00:04:23,720
国家给调过来
The government assigned them there

101
00:04:23,720 --> 00:04:24,760
原籍四川的
They are originally from Sichuan

102
00:04:24,760 --> 00:04:26,360
他们也是继承了老一辈的
They also inherited the traditional techniques

103
00:04:26,360 --> 00:04:27,880
这种传统技法
from the past generation

104
00:04:27,880 --> 00:04:29,520
煸完了之后
After dry stir frying

105
00:04:29,520 --> 00:04:30,520
加上辣椒面
Add chili powder

106
00:04:30,520 --> 00:04:31,640
加辣椒面
Add chili powder

107
00:04:31,640 --> 00:04:35,160
它有一种辣椒的那种清香味
It has the refreshing fragrance of chili peppers

108
00:04:35,160 --> 00:04:37,800
和鸡丁揉在一块
Together with chicken dice

109
00:04:37,800 --> 00:04:39,960
那种香气更浓一些
The fragrance is even stronger

110
00:04:39,960 --> 00:04:41,480
但是它不好在哪呢
However, what's the down side?

111
00:04:43,400 --> 00:04:44,640
这煸辣椒面
To dry fry chili powder

112
00:04:44,640 --> 00:04:47,000
和卧油煸炒
and to dry stir fry in the Wo You style

113
00:04:47,000 --> 00:04:49,400
这需要你有一定的功夫了
You have to be skillful enough

114
00:04:49,400 --> 00:04:50,840
如果说
In case

115
00:04:50,840 --> 00:04:51,800
您的功夫差点
You are not that skillful

116
00:04:51,800 --> 00:04:54,560
可能是辣椒面 可能就煸糊了
You'll probably burn the chili powder

118
00:04:54,560 --> 00:04:55,880
或者鸡丁的出来
Or when cooking the chicken dice

119
00:04:55,880 --> 00:04:57,080
掌握不好的油温的
If you use the wrong oil temperature

120
00:04:57,080 --> 00:04:58,640
他就不嫩了
It's not tender any more

121
00:04:58,640 --> 00:05:00,240
这需要有一定的难度
This is somewhat difficult

122
00:05:00,240 --> 00:05:02,240
但是滑炒相对来讲就难度
Comparatively, the difficulty of Hua You

123
00:05:02,240 --> 00:05:04,920
稍微低一点是吧
It's a bit lower

124
00:05:04,920 --> 00:05:07,160
最后放辣椒油的话
How about finishing with chili oil?

125
00:05:07,160 --> 00:05:09,560
辣椒油是现代的产物
Chili oil is a modern product

126
00:05:09,560 --> 00:05:10,280
不是过去的
Not a traditional one

127
00:05:10,280 --> 00:05:12,840
它以胡辣 小荔枝为口的
注：这里说的应该是宫保鸡丁口味改良史。考虑到这部分是严肃的知识讲解，就帮他们注明了
The traditional flavors (of Kung Pao Chicken) was mostly "Hu La" and "Xiao Li Zhi"

128
00:05:12,840 --> 00:05:14,960
这种口味是吧
Those flavors, right?

129
00:05:14,960 --> 00:05:18,320
然后改成现在有点大甜酸了
And now it has become kind of a strong sweet and sour flavor

130
00:05:18,320 --> 00:05:19,360
大甜酸之后
After becoming sweet and sour

131
00:05:19,360 --> 00:05:20,240
他就炼红油
They use chili oil

132
00:05:20,240 --> 00:05:22,000
炼红油第一省事
First of all, chili oil is convenient

133
00:05:22,000 --> 00:05:23,080
第二个颜色漂亮
Second, the color looks pretty

134
00:05:23,080 --> 00:05:26,720
是现代版的这种产物
That's a modern product

135
00:05:26,720 --> 00:05:29,840
吃起来的味道还是有些 有些区别
When you eat it, the taste is still a bit different

137
00:05:31,240 --> 00:05:32,840
要辣干辣的那种
（不会译...）
Different in their types of spiciness

138
00:05:35,280 --> 00:05:37,560
他们在制作红油的时候
And when they make chili oil

139
00:05:37,560 --> 00:05:39,960
也加了一些特殊的香料
They also add some special spices

140
00:05:40,680 --> 00:05:41,880
追求的是颜色
Their goal is the color

141
00:05:44,920 --> 00:05:45,440
这就是不一样
That's so different

142
00:05:45,440 --> 00:05:47,840
两位拥有60多万赞的人就是不一样
With over 600k likes, you two look so different

143
00:05:47,840 --> 00:05:49,080
这气色
Looking great!

144
00:05:53,480 --> 00:05:55,200
别唱了大爷
Stop singing, Da Ye

145
00:05:55,200 --> 00:05:56,000
开始
Start

146
00:05:56,000 --> 00:05:56,680
对不起啊
Sorry

147
00:05:56,680 --> 00:05:57,280
等一下
Wait a minute

148
00:05:58,080 --> 00:05:59,520
我录上了吗
Am I recording

149
00:05:59,520 --> 00:06:00,480
您自己都不在线上
You are not even online yourself

150
00:06:02,160 --> 00:06:03,280
线下的你
You are offline

151
00:06:03,280 --> 00:06:03,520
