### ISSUE TITLE
[华农兄弟] 抓鱼 - https://youtu.be/FB90ODffiBs

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1241]
https://youtu.be/FB90ODffiBs
<p>&#35270;&#39057;&#21457;&#24067;&#20110; July 3, 2020 at 11:50AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/FB90ODffiBs

#华农兄弟：白天太热了，晚上出来活动一下，抓点鱼
Huanong Brothers: It's too not in the day. We come out to stroll around at night, and catch some fish.

0:00:06.900,0:00:08.560
#  大家好  現在白天太熱啦
Hi everyone. It's too hot in the day recently.

0:00:08.720,0:00:09.940
# 所以晚上出來活動
So we're coming out at night.

0:00:10.800,0:00:14.160
# 來夾點魚  看下有沒有黃鱔啊  看下有沒有蛇頭魚
We're gonna catch some fish. Let's see if there are any eels, see if there are any snakehead fish.

0:00:14.160,0:00:17.000
# 我家附近的魚全部都夾完啦  小魚都看不到
I've caught all the fish around my place. I can't even see any small fish there.

0:00:17.360,0:00:19.100
# 看下攝影小哥家附近有沒有
Let's see if there are any around Mr. Cameraman's home.

0:00:19.800,0:00:20.840
# 這裡有條小溝哦
Here's a small pit.

0:00:21.800,0:00:22.440
# 應該有魚
There should be fish.

0:00:25.180,0:00:27.060
# 哇  這裡有小魚呦
Wa! Here are some small fish.

0:00:27.820,0:00:29.940
# 那麼小的  放過它吧
 Leave them alone. They're so small.

0:00:31.460,0:00:32.880
# 我等它長大了我再來
I'll come again when they grow up.

0:00:33.700,0:00:36.060
# 這條水泥溝的話應該沒有多少大魚
I don't think there are a lot of fish in this pit.

0:00:36.860,0:00:37.880
# 我去下面看一下
Let me go down there and have a look.

0:00:39.300,0:00:41.060
# 你看 那裡好多小蝌蚪
Look! There are a lot of tadpoles.

0:00:42.380,0:00:43.840
# 剛出生沒多久的
They just came out from the eggs not long ago.

0:00:44.740,0:00:45.640
# 你看  這裡有一個
Look! Here's a...

0:00:47.400,0:00:50.220
# 你看  這種青蛙  好瘦啊它
Look! This kind of frog...It's so skinny.

0:00:50.960,0:00:52.240
# 肯定找不到東西吃
It must have difficulties in finding food.

0:00:53.100,0:00:56.140
# 它這種青蛙是  吃那個  小蟲子的哦
This kind of frogs, they feed on, on little bugs, you know.

0:00:56.480,0:00:58.820
# 這個是莊稼的守護
They are the frogs that corps, corps

0:00:59.160,0:01:01.040
# 守護莊稼的那個青蛙
that guard the crops.

0:01:01.460,0:01:02.780
# 不能 不能把它抓啦
No one, no one should catch them.

0:01:03.800,0:01:04.860
# 我把它放生
I'm gonna release it.

0:01:05.460,0:01:06.060
# 跑
Run!

0:01:07.960,0:01:09.540
# 兄弟家的梨樹 梨古
This is my buddy's pear tree, pear.

0:01:10.400,0:01:11.520
# 現在越來越大了哦
Now it's getting larger and larger.

0:01:12.740,0:01:14.540
# 就看到一個 白天還看見很多
I see just one. I can see a lot in the day.

0:01:14.940,0:01:16.260
# 這大晚上的看不到
But I can't see any at night.

0:01:16.940,0:01:18.020
# 應該都躲起來啊
They must be hiding away.

0:01:19.400,0:01:20.800
# 等熟了時候再來
I'll come again when they're ripe.

0:01:21.700,0:01:23.320
# 你看  這是螢火蟲哦
Look! This is a firefly.

0:01:23.860,0:01:25.440
# 它屁股後面都是發亮的
It glows at the back of the butt.

0:01:27.140,0:01:28.540
# 你信你把燈關掉看一下
Switch off the light and you'll see, if you don't trust me.

0:01:30.820,0:01:31.380
# 是不是
Am I right?

0:01:32.060,0:01:33.000
# 一亮一亮的
Twinkle twinkle

0:01:34.300,0:01:36.380
# 喂 開始飛啦 它馬上想飛走啦
Hey, it starts flying. It wants to fly away now.

0:01:37.800,0:01:39.740
# 愛護蟲子  人人有責哦
Protecting bugs is the responsibility of everyone.

0:01:40.560,0:01:42.420
# 飛吧  不知道飛哪裡去啦
Fly! Who knows where it is now.

0:01:43.160,0:01:44.140
# 找都找不到啦
I can't find it anymore.

0:01:45.220,0:01:46.000
# 你自由啦
You're free now.

0:01:47.220,0:01:48.280
# 幸好是碰到我
You should feel blessed that it's me.

0:01:50.600,0:01:53.200
# 你看這個  我還以為是個雞蛋呢
Have a look at this one. I thought that it were an egg.

0:01:53.680,0:01:54.800
# 原來是個毒蘑菇
But it's a poisonous mushroom.

0:01:56.960,0:01:58.060
# 像一條蛇一樣的
It's like a snake.

0:02:09.480,0:02:12.040
# 這樣的招澤地很多黃鱔跟泥鰍的哦
There are always a lot of eels and loaches in this kind of ponds.

0:02:18.820,0:02:20.260
# 有點嚇人啊這裡
It's a bit scary here.

0:02:28.720,0:02:32.180
# 你看  這裡有一條  小泥 小黃鱔
Look! Here's a small loa.. a small eel.

0:02:35.400,0:02:36.240
# 差點跑啦
It's almost gone.

0:02:38.700,0:02:39.720
# 這裡還有沒有
Any more here?

0:02:41.260,0:02:43.040
# 要很小心  走這樣的路
Special cares need to be taken, while walking on this kind of surface.

0:02:47.300,0:02:48.460
# 你看  這裡還有一條
Look! Here's another one.

0:02:49.420,0:02:50.060
# 這裡有一條
Here's one.

0:02:50.800,0:02:51.500
# 那麼大的
It's so big.

0:02:53.700,0:02:54.740
# 幸好我帶了桶
Fortunately, I have a bucket with me.

0:03:02.940,0:03:03.820
# 這裡有一條
Here's one.

0:03:04.060,0:03:05.480
# 跑啦  這泥鰍
It runs away, this loach.

0:03:08.660,0:03:09.300
# 跑啦
Run away...

0:03:18.400,0:03:19.300
# 這裡沒有了
No more here

0:03:20.880,0:03:23.120
# 溝裡面  去溝裡面看下有沒有
Into the pit, let's go into the pit and see if there are any.

0:03:25.340,0:03:26.600
# 這有個蛇頭魚呦
Here's a snakehead fish.

0:03:37.020,0:03:38.020
# 誒呦 抓到啦
Eyo! I got it!

0:03:39.020,0:03:40.200
# 看見沒有  你看
See? Look!

0:03:40.860,0:03:42.080
# 一條那麼小的蛇頭魚
It's a tiny snakehead fish.

0:03:42.840,0:03:43.960
# 被我逮到啦
And I've caught it.

0:03:45.560,0:03:46.640
# 想跑
You wanna run away?

0:03:48.020,0:03:49.040
# 你看這個魚
Have a look at this fish!

0:03:51.400,0:03:52.300
# 那麼兇
It's so fierce.

0:04:05.540,0:04:07.020
# 哇  你看  這裡有條蛇頭魚
Wa! Look! Here's a snakehead fish.

0:04:09.400,0:04:10.780
# 看見沒有  我看到它尾巴
See? I can see its tail,

0:04:11.280,0:04:12.180
# 也看到它頭
and also its head.

0:04:15.880,0:04:16.460
# 哪裡去了
Where is it now?

0:04:25.800,0:04:26.580
# 在草裡面
It's in the grass.

0:04:28.220,0:04:30.160
# 誒   沒撈到  撈到泥巴
Eh? I couldn't catch it? It's only mud here.

0:04:39.920,0:04:40.780
# 不在了
It's not here.

0:04:42.560,0:04:44.160
# 剛剛還看到它在這裡的
I just saw it here a couple of seconds ago.

0:04:49.860,0:04:53.240
# 誒呦  那麼難搞  這蛇頭魚就是這樣
Eyo! It's so hard. Well, this is snakehead fish.

0:04:54.460,0:04:55.620
# 一鑽到泥上去就
Once they squeeze into the mud,

0:04:57.100,0:04:58.200
# 怎麼找都找不到啦
you can never find it.

0:04:58.240,0:05:01.380
# 你看  這裡有一條  看到沒有  剛好動了一下
Look! Here's one. See? It just shook a little bit.

0:05:01.780,0:05:03.120
# 把水都搞渾濁啦
The water is so muddy now.

0:05:07.640,0:05:09.020
# 你看  這有一條蛇頭魚
Look! Here's a snakehead fish.

0:05:15.980,0:05:17.020
# 啊  它鑽泥
Ah! It squeezes into the mud.

0:05:17.700,0:05:20.120
# 鑽泥也跑不掉  你看抓到啦
Squeeze into the mud or not, it's not gonna run away. Look! I got it now.

0:05:28.460,0:05:31.560
# 你看  這裡有條小的蛇頭魚  看到沒有  太小啦
Look! Here's a small snakehead fish. See? It's too small.

0:05:34.460,0:05:36.180
# 抓到啦  那麼小
Got it! It's so small.

0:05:37.180,0:05:38.280
# 那麼小也不放過
But size doesn't matter.

0:05:40.840,0:05:42.540
# 你看  這條泥鰍
Look! This loach...

0:05:44.880,0:05:46.020
# 看能不能夾住它
Let's see if I can catch it.

0:05:50.860,0:05:51.460
# 別跑
Freeze!

0:06:01.220,0:06:01.820
# 跑啦
Run away...

0:06:11.040,0:06:13.780
# 嘿  想跑  這樣都被我抓住
Hey! Wanna run away? I can still catch you.

0:06:16.160,0:06:18.280
# 你看 抓了一晚上就抓了那麼一點點
Look! We've spent the whole night, only to have just a tiny little bit here.

0:06:19.280,0:06:20.520
# 蛇頭魚跟黃鱔
Snakehead fish, and eels

0:06:21.180,0:06:22.340
# 泥鰍就搞了幾條
and some loaches

0:06:23.380,0:06:24.560
# 現在都快十二點啦
It's almost midnight now.

0:06:24.940,0:06:26.060
# 就抓了那麼一點點  (註︰沒有原字幕)
And we have just a tiny little bit here.

0:06:26.660,0:06:30.760
# 要準備回去啦  不回去的話  要駡人啦
We gotta get ready to go home. Somebody's gonna get mad otherwise.
