### ISSUE TITLE
【美食作家王刚】摘葡萄 - https://youtu.be/XJB4CkHWGFs

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1243]
**视频链接**：https://youtu.be/XJB4CkHWGFs

视频时长5:30，预计发布时间为北京时间7月6日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
在工作室正式开工前再休息半天，和家人一起摘葡萄，没想到居然有这么多品种，奇怪的知识又增加了

简介
大家好，趁着新工作室还没开工，带着家人来偷个闲，逛一逛摘一些刚刚成熟的葡萄，果真还是新鲜刚摘下来的最好吃！工作室已经进入收尾工作，马上就可以开工，新的拍摄设备也在调试测试中，到时候就会忙起来了，硬核教学很快就会回归！

字幕
0:00:00.000,0:00:00.640
哎哟

0:00:01.720,0:00:03.360
你这么大了还要坐这个车啊

0:00:06.012,0:00:07.098
哈喽 大家好

0:00:07.466,0:00:11.020
今天带着女儿 儿子老婆来摘下葡萄

0:00:11.260,0:00:12.782
现在反正也七月份了吧

0:00:12.782,0:00:14.820
这个葡萄熟了的季节

0:00:15.300,0:00:16.596
来摘点巨峰

0:00:16.596,0:00:18.740
因为我平时也很喜欢吃巨峰葡萄

0:00:20.796,0:00:21.350
走了

0:00:25.634,0:00:26.500
这个啥子品种安

0:00:26.700,0:00:29.820
这个是我们的醉金香它的口感哈

0:00:29.820,0:00:30.780
啥子味道的哦

0:00:30.970,0:00:32.500
它是那种

0:00:34.222,0:00:37.620
纯甜而且有一种有一股很好的香味

0:00:37.660,0:00:39.153
可不可以摘一个来试一下

0:00:39.153,0:00:41.341
可以  你摘一个来尝

0:00:46.700,0:00:47.546
这个没有籽

0:00:49.367,0:00:50.731
你看他看到你吃

0:00:51.647,0:00:55.410
这个葡萄好涩口 好酸啊 里面是甜的

0:00:57.481,0:01:00.020
这个皮跟李子一样 跟李子有点（像）

0:01:00.260,0:01:01.292
要不要吃一个沺沺

0:01:01.292,0:01:02.100
有点涩口

0:01:02.488,0:01:05.455
但是里面这个我觉得好像比巨峰还要更甜一点

0:01:07.346,0:01:08.830
皮不吃皮不吃

0:01:09.218,0:01:09.736
酸不酸

0:01:10.204,0:01:11.229
酸的

0:01:11.816,0:01:12.354
不酸啊

0:01:13.840,0:01:14.910
这个葡萄比较好

0:01:15.320,0:01:16.690
它已经熟透了

0:01:17.460,0:01:19.470
像你们种那个都是专家喽嘎

0:01:19.680,0:01:23.394
这个我们还是已经十哒十年了

0:01:25.475,0:01:26.600
像这一串就是熟透了样

0:01:26.600,0:01:27.575
哦 对对对

0:01:27.824,0:01:32.040
像这一串它已经熟透了 你看它它全部是一种金黄色的哈

0:01:32.360,0:01:33.305
给人的感觉

0:01:33.364,0:01:35.470
你先品尝一个嘛

0:01:35.470,0:01:35.910
来

0:01:36.317,0:01:36.601
好

0:01:38.855,0:01:40.009
这个口味就很好

0:01:40.248,0:01:40.706
嗯

0:01:41.413,0:01:43.982
这个皮子不怎么涩口

0:01:43.982,0:01:45.340
但是这个

0:01:46.988,0:01:48.510
这个有点不一样是啥子安

0:01:48.640,0:01:50.721
它不像巨峰一挤那个肉就出来了

0:01:50.721,0:01:51.299
哎 对

0:01:51.428,0:01:53.071
这个只有连这皮子一哈吃

0:01:53.071,0:01:56.480
哎 对这个 就是这样的 它的这个品种不一样

0:01:56.480,0:01:58.080
因为很多品种不一样

0:01:58.840,0:02:00.800
好 差不多了 我们去摘点巨峰嘛

0:02:00.800,0:02:01.880
哎 要得 去摘点巨峰嘛

0:02:01.880,0:02:02.448
巨峰

0:02:02.448,0:02:03.040
那边的是不哦

0:02:03.040,0:02:04.167
我们这边的品种很多

0:02:04.295,0:02:05.080
嗯 走嘛

0:02:05.860,0:02:07.387
抓一下下没事

0:02:07.420,0:02:08.707
等下他要吃手

0:02:17.392,0:02:19.040
这个嘛 这个是沉香

0:02:19.040,0:02:20.072
它都是一种果香味

0:02:20.720,0:02:23.520
它的甜度啊

0:02:23.640,0:02:28.190
是已经达到20%以上了 给人的感觉很舒服

0:02:28.340,0:02:29.298
那这个就是沉香

0:02:29.442,0:02:30.420
哎 这都是沉香

0:02:31.743,0:02:32.629
有股花香味

0:02:32.746,0:02:33.883
哦 对

0:02:34.412,0:02:36.557
哪个最适合做葡萄酒

0:02:36.707,0:02:39.242
做葡萄酒来说 这个夏黑哈做葡萄酒

0:02:39.242,0:02:42.520
跟我们的这个光辉 跟我们的早巨峰

0:02:43.057,0:02:46.360
还有我们的这个早霞玫瑰的这三个品种

0:02:46.560,0:02:47.955
混合做的葡萄酒哈

0:02:48.200,0:02:49.760
那个喝起来真的是舒服

0:02:49.760,0:02:50.945
好多品种到底一哈有

0:02:51.188,0:02:54.080
总共这个院子里的品种哈是

0:02:54.360,0:02:56.480
20余种20多种哦

0:02:56.480,0:02:57.320
这样啊

0:02:57.555,0:02:58.490
不知道是什么

0:02:59.722,0:03:00.588
好 你推吧

0:03:01.150,0:03:02.074
慢点推啊

0:03:02.394,0:03:04.082
你别推到沟里去了

0:03:10.533,0:03:12.935
因为它颗粒啊稍微的偏小一点点的

0:03:12.935,0:03:14.271
但是它口感非常好

0:03:14.590,0:03:20.898
而且它的品质 你看我们的肉质 是非常非常的细嫩的

0:03:21.360,0:03:22.640
而且很细嫩

0:03:22.960,0:03:24.830
给人的感觉吃起很舒服

0:03:26.417,0:03:27.862
我还是觉得这个更好吃

0:03:29.000,0:03:30.370
其它的我

0:03:30.840,0:03:32.541
让我选的话我还是吃这个

0:03:35.413,0:03:37.820
就那种黢黑的就是熟了嘎

0:03:37.860,0:03:39.900
因为我们呢 就是自然红的

0:03:39.940,0:03:42.460
自然熟的 全部都自然熟

0:03:42.570,0:03:43.010
你看

0:03:43.100,0:03:44.670
虽然说有一点点红啊

0:03:44.897,0:03:46.740
而且那是已经熟透了

0:03:46.740,0:03:48.576
这个是不是摘回去了要放一段时间哦

0:03:48.576,0:03:52.383
不不不  你放哈冰箱更好吃一下

0:03:52.383,0:03:53.100
冻一哈更好吃哦

0:03:53.100,0:03:55.716
你看这串葡萄已经成熟了的

0:03:55.867,0:03:56.780
而且这个

0:03:56.900,0:03:58.051
看这个一串有好重哦

0:03:58.395,0:04:00.781
这个一串是一斤 一斤多一点点的

0:04:01.080,0:04:03.520
所以说我们的巨峰跟市面上的巨峰不一样

0:04:03.520,0:04:04.680
这怕没得一斤的哦

0:04:04.680,0:04:06.467
这个看起来很舒服的

0:04:06.686,0:04:06.988
嗯

0:04:07.520,0:04:08.534
好差不多了

0:04:08.979,0:04:12.121
我那一篮都有5斤了害怕都有 够了

0:04:13.780,0:04:14.940
这个蜂蜜味的

0:04:14.940,0:04:17.380
而且它是一个蜂蜜味带纯甜

0:04:17.580,0:04:19.311
而且给人的感觉是很舒服的

0:04:19.860,0:04:21.772
来 宝贝尝一下蜂蜜味的

0:04:21.873,0:04:22.545
是什么味道

0:04:22.545,0:04:22.847
过来

0:04:23.376,0:04:24.124
好不好吃

0:04:26.489,0:04:27.772
看下你有没有蜂蜜

0:04:29.106,0:04:31.762
就是我觉得不是不甜

0:04:31.773,0:04:35.818
它是一个蜂蜜的味道一下子就把这个葡萄的味道给抢了

0:04:36.503,0:04:38.184
蜂蜜的味道抢了葡萄的味道我觉得

0:04:40.407,0:04:42.454
今天摘了四五斤葡萄这个

0:04:42.894,0:04:44.474
葡萄甜还是挺甜的

0:04:45.359,0:04:46.640
但是这个棚里面热呀

0:04:46.640,0:04:47.325
真的是热

0:04:47.600,0:04:49.834
我女儿热的她都不想走路要爸爸抱

0:04:50.760,0:04:51.200
你也热

0:04:51.200,0:04:51.894
我们赶紧出去

0:04:51.894,0:04:52.390
儿子也热

0:04:53.740,0:04:54.796
真的很热

0:04:57.225,0:04:58.339
哦 想睡觉了 是不是

0:04:59.264,0:05:02.111
然后我们这个家庭出来嘛

0:05:02.807,0:05:04.869
反正就摘摘水果啊什么还是挺好的

0:05:06.958,0:05:09.140
虽然说这个棚里面的老板都说了

0:05:09.140,0:05:13.030
棚里面的这个价格要比外面摊上面的价格要略贵一些

0:05:13.780,0:05:15.780
这个应该也能理解

0:05:15.780,0:05:17.281
因为边摘的时候都在吃

0:05:18.952,0:05:20.500
所以贵那么一点是正常的

0:05:21.398,0:05:23.281
好啦  本期视频到这里啦 拜拜

0:05:23.560,0:05:24.913
有空的时候带家人出来

0:05:25.700,0:05:27.608
好好放松放松


```

**Comment by Kevinzheng5** [comment]
认领

**Comment by Kevinzheng5** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
在工作室正式开工前再休息半天，和家人一起摘葡萄，没想到居然有这么多品种，奇怪的知识又增加了
Took a half day off before the studio launching day. Grape picking with my family. Didn’t know we have so many species of grapes.

简介
大家好，趁着新工作室还没开工，带着家人来偷个闲，逛一逛摘一些刚刚成熟的葡萄，果真还是新鲜刚摘下来的最好吃！工作室已经进入收尾工作，马上就可以开工，新的拍摄设备也在调试测试中，到时候就会忙起来了，硬核教学很快就会回归！
Hey guys, since the new studio hasn’t launched yet, I took some leisure time with my family. We had a field trip and picked some grapes that were just ripe. The ripe on trees fruits are indeed the best. The new studio is already in the finishing-up phase and it should be ready immediately. The new photographing equipment are being tested too. I’ll soon be back busy and the hardcore cooking videos will be back soon!

字幕
0:00:00.000,0:00:00.640
Come on
哎哟

0:00:01.720,0:00:03.360
你这么大了还要坐这个车啊
Still want to ride the stroller when you are this big?

0:00:06.012,0:00:07.098
哈喽 大家好
Hey guys

0:00:07.466,0:00:11.020
今天带着女儿 儿子老婆来摘下葡萄
Today I took my family here to pick some grapes

0:00:11.260,0:00:12.782
现在反正也七月份了吧
It’s already July

0:00:12.782,0:00:14.820
这个葡萄熟了的季节
The grapes are ready in this season

0:00:15.300,0:00:16.596
来摘点巨峰
Let’s pick some Jufeng (A specie of grapes)
 
0:00:16.596,0:00:18.740
因为我平时也很喜欢吃巨峰葡萄
Because I like really like that specie

0:00:20.796,0:00:21.350
走了
Let’s go

0:00:25.634,0:00:26.500
这个啥子品种安
What’s this specie?

0:00:26.700,0:00:29.820
这个是我们的醉金香它的口感哈
It’s called Zuijinxiang. It has a good texture

0:00:29.820,0:00:30.780
啥子味道的哦
How does it taste like?

0:00:30.970,0:00:32.500
它是那种
It is

0:00:34.222,0:00:37.620
纯甜而且有一种有一股很好的香味
Pure sweet with a delicious aroma

0:00:37.660,0:00:39.153
可不可以摘一个来试一下
Can I pick one to try?

0:00:39.153,0:00:41.341
可以  你摘一个来尝
Sure, go for it

0:00:46.700,0:00:47.546
这个没有籽
This is seedless

0:00:49.367,0:00:50.731
你看他看到你吃
The baby is seeing you eating!

0:00:51.647,0:00:55.410
这个葡萄好涩口 好酸啊 里面是甜的
Gosh it’s actually pucker and sour. Only the core is sweet 

0:00:57.481,0:01:00.020
这个皮跟李子一样 跟李子有点（像）
Its skin is like plums’

0:01:00.260,0:01:01.292
要不要吃一个沺沺
Tiantian, you want one?

0:01:01.292,0:01:02.100
有点涩口
It’s a bit astringent

0:01:02.488,0:01:05.455
但是里面这个我觉得好像比巨峰还要更甜一点
But the inside is even sweeter than Jufeng

0:01:07.346,0:01:08.830
皮不吃皮不吃
Don’t eat the skin

0:01:09.218,0:01:09.736
酸不酸
Is it sour?

0:01:10.204,0:01:11.229
酸的
Guess it is

0:01:11.816,0:01:12.354
不酸啊
It’s not that sour

0:01:13.840,0:01:14.910
这个葡萄比较好
This bunch is good	

0:01:15.320,0:01:16.690
它已经熟透了
Ripe on the tree

0:01:17.460,0:01:19.470
像你们种那个都是专家喽嘎
You guys are the experts on planting these

0:01:19.680,0:01:23.394
这个我们还是已经十哒十年了
Yeah we have been farming these for 10 years

0:01:25.475,0:01:26.600
像这一串就是熟透了样
It’s ripe when it’s like this bunch, right?

0:01:26.600,0:01:27.575
哦 对对对
Exactly

0:01:27.824,0:01:32.040
像这一串它已经熟透了 你看它它全部是一种金黄色的哈
This bunch is thoroughly ripe. Look at the golden color

0:01:32.360,0:01:33.305
给人的感觉
It feels like…

0:01:33.364,0:01:35.470
你先品尝一个嘛
Have a try first

0:01:35.470,0:01:35.910
来
Here you go	

0:01:36.317,0:01:36.601
好
Aright

0:01:38.855,0:01:40.009
这个口味就很好
It should taste really well

0:01:40.248,0:01:40.706
嗯
Yes

0:01:41.413,0:01:43.982
这个皮子不怎么涩口
The skin is not that astringent

0:01:43.982,0:01:45.340
但是这个
But

0:01:46.988,0:01:48.510
这个有点不一样是啥子安
It has one deficit

0:01:48.640,0:01:50.721
它不像巨峰一挤那个肉就出来了
The fruit doesn’t pop out like Jufeng

0:01:50.721,0:01:51.299
哎 对
Yeah right

0:01:51.428,0:01:53.071
这个只有连这皮子一哈吃
You have to eat it with the skin

0:01:53.071,0:01:56.480
哎 对这个 就是这样的 它的这个品种不一样
Yeah it’s like that. It’s different species

0:01:56.480,0:01:58.080
因为很多品种不一样
It’s because of the species

0:01:58.840,0:02:00.800
好 差不多了 我们去摘点巨峰嘛
Alright. Let ‘s go for some Jufeng

0:02:00.800,0:02:01.880
哎 要得 去摘点巨峰嘛
Alright. Let’s go to Jufeng

0:02:01.880,0:02:02.448
巨峰
Jufeng

0:02:02.448,0:02:03.040
那边的是不哦
Are they on that side?

0:02:03.040,0:02:04.167
我们这边的品种很多
We have a lot of species here

0:02:04.295,0:02:05.080
嗯 走嘛
Alright, let’s go

0:02:05.860,0:02:07.387
抓一下下没事
It’s okay for him to touch it

0:02:07.420,0:02:08.707
等下他要吃手
He’ll put his fingers in his mouth later

0:02:17.392,0:02:19.040
这个嘛 这个是沉香
These down here are called Chenxiang

0:02:19.040,0:02:20.072
它都是一种果香味
It tastes really fruity

0:02:20.720,0:02:23.520
它的甜度啊
Its sugar percentage

0:02:23.640,0:02:28.190
是已经达到20%以上了 给人的感觉很舒服
Is above 20 percent. Really comforting taste

0:02:28.340,0:02:29.298
那这个就是沉香
That’s Chenxiang

0:02:29.442,0:02:30.420
哎 这都是沉香
Yeha, all these

0:02:31.743,0:02:32.629
有股花香味
It’s got a flagrance of flowers

0:02:32.746,0:02:33.883
哦 对
Yeah right

0:02:34.412,0:02:36.557
哪个最适合做葡萄酒
Which specie is the best for wine making?

0:02:36.707,0:02:39.242
做葡萄酒来说 这个夏黑哈做葡萄酒
The Xiaheiha is the best to make wine

0:02:39.242,0:02:42.520
跟我们的这个光辉 跟我们的早巨峰
Mix it with Guanghui, early Jufeng

0:02:43.057,0:02:46.360
还有我们的这个早霞玫瑰的这三个品种
And also the early Xiameigui

0:02:46.560,0:02:47.955
混合做的葡萄酒哈
The wine made of the mixture of those

0:02:48.200,0:02:49.760
那个喝起来真的是舒服
tastes really well

0:02:49.760,0:02:50.945
好多品种到底一哈有
How many species are there in total?

0:02:51.188,0:02:54.080
总共这个院子里的品种哈是
In total, this farm has about

0:02:54.360,0:02:56.480
20余种20多种哦
More than 20 species

0:02:56.480,0:02:57.320
这样啊
Got it

0:02:57.555,0:02:58.490
不知道是什么
I don’t know what that is

0:02:59.722,0:03:00.588
好 你推吧
Alright, you push

0:03:01.150,0:03:02.074
慢点推啊
Take it slow

0:03:02.394,0:03:04.082
你别推到沟里去了
Don’t push it into the ditch

0:03:10.533,0:03:12.935
因为它颗粒啊稍微的偏小一点点的
This one has smaller fruits

0:03:12.935,0:03:14.271
但是它口感非常好
But it tastes extra well

0:03:14.590,0:03:20.898
而且它的品质 你看我们的肉质 是非常非常的细嫩的
The texture of it is really smooth

0:03:21.360,0:03:22.640
而且很细嫩
Really smooth

0:03:22.960,0:03:24.830
给人的感觉吃起很舒服
Tastes really comforting

0:03:26.417,0:03:27.862
我还是觉得这个更好吃
This one is my personal favorite

0:03:29.000,0:03:30.370
其它的我
All the others…

0:03:30.840,0:03:32.541
让我选的话我还是吃这个
I’ll go for this if I have a choice

0:03:35.413,0:03:37.820
就那种黢黑的就是熟了嘎
The really black ones are ripe, right?

0:03:37.860,0:03:39.900
因为我们呢 就是自然红的
Yeah we let them ripe on the tree

0:03:39.940,0:03:42.460
自然熟的 全部都自然熟
All of them

0:03:42.570,0:03:43.010
你看
See

0:03:43.100,0:03:44.670
虽然说有一点点红啊
Even though this one is still a little bit red

0:03:44.897,0:03:46.740
而且那是已经熟透了
It’s already totally ripe

0:03:46.740,0:03:48.576
这个是不是摘回去了要放一段时间哦
Do we need to let them rest for some time when we get home?

0:03:48.576,0:03:52.383
不不不  你放哈冰箱更好吃一下
No. But they are better after you put them in fridge

0:03:52.383,0:03:53.100
冻一哈更好吃哦
Cool them down and they taste better

0:03:53.100,0:03:55.716
你看这串葡萄已经成熟了的
See, this bunch is ripe

0:03:55.867,0:03:56.780
而且这个
And

0:03:56.900,0:03:58.051
看这个一串有好重哦
This bunch is heavy

0:03:58.395,0:04:00.781
这个一串是一斤 一斤多一点点的
About 1 jin (500 gram), or a little bit above 

0:04:01.080,0:04:03.520
所以说我们的巨峰跟市面上的巨峰不一样
Our Jufeng is different than the ones on the market

0:04:03.520,0:04:04.680
这怕没得一斤的哦
It’s not 1 jin I guess

0:04:04.680,0:04:06.467
这个看起来很舒服的
It looks comfortable

0:04:06.686,0:04:06.988
嗯
Yeah

0:04:07.520,0:04:08.534
好差不多了
OK I think these should be enough

0:04:08.979,0:04:12.121
我那一篮都有5斤了害怕都有 够了
Only the ones in my basket are more than 5 jins. Enough

0:04:13.780,0:04:14.940
这个蜂蜜味的
This one tastes like honey

0:04:14.940,0:04:17.380
而且它是一个蜂蜜味带纯甜
It’s pure sweet plus honey

0:04:17.580,0:04:19.311
而且给人的感觉是很舒服的
Gives you a comfortable feeling

0:04:19.860,0:04:21.772
来 宝贝尝一下蜂蜜味的
Come on baby, taste the honey flavor ones

0:04:21.873,0:04:22.545
是什么味道
See how it tastes like

0:04:22.545,0:04:22.847
过来
Come here

0:04:23.376,0:04:24.124
好不好吃
See whether it’s good

0:04:26.489,0:04:27.772
看下你有没有蜂蜜
See whether you can have some honey

0:04:29.106,0:04:31.762
就是我觉得不是不甜
I think it’s sweet

0:04:31.773,0:04:35.818
它是一个蜂蜜的味道一下子就把这个葡萄的味道给抢了
But the honey flavor really takes the grape flavor away

0:04:36.503,0:04:38.184
蜂蜜的味道抢了葡萄的味道我觉得
It takes the place of the grape flavor

0:04:40.407,0:04:42.454
今天摘了四五斤葡萄这个
Today we picked about 4-5 jins of grapes

0:04:42.894,0:04:44.474
葡萄甜还是挺甜的
The grapes are sweet 

0:04:45.359,0:04:46.640
但是这个棚里面热呀
But it’s really hot in here

0:04:46.640,0:04:47.325
真的是热
It’s steaming

0:04:47.600,0:04:49.834
我女儿热的她都不想走路要爸爸抱
My daughter quitted walking because of the heat and she wants to me to carry her

0:04:50.760,0:04:51.200
你也热
Haha you feel hot too

0:04:51.200,0:04:51.894
我们赶紧出去
Let’s get out of here

0:04:51.894,0:04:52.390
儿子也热
My son feels hot too

0:04:53.740,0:04:54.796
真的很热
Gosh it’s burning

0:04:57.225,0:04:58.339
哦 想睡觉了 是不是
Oh maybe you want to have a nap

0:04:59.264,0:05:02.111
然后我们这个家庭出来嘛
Today I took my whole family

0:05:02.807,0:05:04.869
反正就摘摘水果啊什么还是挺好的
It feels great to pick the fruits and all

0:05:06.958,0:05:09.140
虽然说这个棚里面的老板都说了
Although the owner said that

0:05:09.140,0:05:13.030
棚里面的这个价格要比外面摊上面的价格要略贵一些
The grapes we pick have a higher price than the outside markets

0:05:13.780,0:05:15.780
这个应该也能理解
It’s understandable

0:05:15.780,0:05:17.281
因为边摘的时候都在吃
Because we tasted when we were picking

0:05:18.952,0:05:20.500
所以贵那么一点是正常的
It’s okay to be a little bit more expensive

0:05:21.398,0:05:23.281
好啦  本期视频到这里啦 拜拜
Alright, that’s it for this episode

0:05:23.560,0:05:24.913
有空的时候带家人出来
Take your family out when you got some time

0:05:25.700,0:05:27.608
好好放松放松
Live a little
