### ISSUE TITLE
[雪鱼] 手抓羊肉 -https://youtu.be/Jgbz672ijyw

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#1247]
**视频链接**：https://youtu.be/Jgbz672ijyw

# 请翻译以下全部内容

```

字幕
1
00:00:01,460 --> 00:00:02,260
青海·西宁

2
00:00:02,500 --> 00:00:04,500
西宁市 是青藏高原的东方门户

3
00:00:04,800 --> 00:00:06,800
独特的气候条件 和 地理条件

4
00:00:06,800 --> 00:00:09,600
使得这边形成了丰富的饮食文化

5
00:00:09,600 --> 00:00:11,360
在众多的美食当中

6
00:00:11,360 --> 00:00:14,520
羊肉应该是出镜率最高的美食了

7
00:00:14,520 --> 00:00:18,360
今天呢在西宁 我们找一个羊肉的特色吃法

8
00:00:18,360 --> 00:00:20,240
手抓羊肉

9
00:00:23,600 --> 00:00:26,560
就是这里了

10
00:00:31,960 --> 00:00:36,800
一个个师傅都是抱着一怀的羊肉走进后厨

11
00:00:41,200 --> 00:00:43,040
从路过的场面能够看出

12
00:00:43,040 --> 00:00:47,120
他们好像抱的都是肋排 羊排 还有羊腿

13
00:00:47,120 --> 00:00:48,840
这样的肉多一些

14
00:00:48,840 --> 00:00:52,480
不知道自己说的对不对呢 待会去验证一下

15
00:00:58,480 --> 00:01:00,960
哇

16
00:01:01,640 --> 00:01:04,640
又来了一个

17
00:01:10,840 --> 00:01:13,920
咱们原来看剁肉的 都是在案板上

18
00:01:13,920 --> 00:01:16,680
我刚才发现他们这边剁肉 有点不同

19
00:01:16,680 --> 00:01:19,440
他们的案板好像特别高

20
00:01:42,120 --> 00:01:44,480
看来刚才的羊肉还只是冰山一角

21
00:01:44,480 --> 00:01:47,200
我不断地录 他们这边羊肉不断地放

22
00:01:47,200 --> 00:01:51,120
现在羊肉堆的 就像一座大山

23
00:02:11,480 --> 00:02:12,520
虽然说 这边是一个饭店

24
00:02:12,520 --> 00:02:15,640
但是我觉得它更像是一个手抓羊肉的加工厂

25
00:02:15,640 --> 00:02:18,640
这边的羊肉剁完就会在另一边清洗

26
00:02:18,640 --> 00:02:20,480
清洗之后 （羊肉）要炸 要焖

27
00:02:20,480 --> 00:02:23,640
整个的制作过程可能需要十多个人来参与

28
00:02:23,640 --> 00:02:26,800
两个多小时才能够忙完 特别忙碌

29
00:02:40,240 --> 00:02:42,920
因为肉太多 而且锅很大

30
00:02:42,920 --> 00:02:45,000
所以说 在放羊肉的时候

31
00:02:45,000 --> 00:02:46,880
需要在下面放上一层料包

32
00:02:46,880 --> 00:02:51,840
上面再放一层料包 这样羊肉才能够更加入味

33
00:03:58,960 --> 00:04:01,240
现在羊肉呢 是正在炖着

34
00:04:01,240 --> 00:04:03,200
厨师们正在吃饭

35
00:04:03,200 --> 00:04:05,920
我发现他们吃的东西 我是没见过的

36
00:04:05,920 --> 00:04:09,000
你好 我问一下 这个叫什么

37
00:04:09,000 --> 00:04:12,720
这个叫焜锅馍馍

38
00:04:12,720 --> 00:04:15,840
原来它就是焜锅馍馍

39
00:04:17,560 --> 00:04:20,800
啊 它还有一个名字

40
00:04:20,800 --> 00:04:22,660
青海面包

41
00:04:22,960 --> 00:04:26,840
它是甜的吗 还是说 只是面粉的味道

42
00:04:28,400 --> 00:04:32,280
很自然的 没有添加的

43
00:04:32,400 --> 00:04:34,560
像在我们那儿 馍馍都是蒸出来的

44
00:04:34,560 --> 00:04:37,800
我发现这个馍馍是烤出来的

45
00:04:41,760 --> 00:04:45,120
逮住老板 问几个问题

46
00:04:45,120 --> 00:04:50,200
我想问一下 我看羊肉不是全羊

47
00:04:51,880 --> 00:04:53,720
是羊的前身

48
00:04:53,720 --> 00:04:56,400
就是后腿部分不要的

49
00:04:56,400 --> 00:04:59,480
后腿部分 一般要的比较少一些

50
00:04:59,480 --> 00:05:02,000
要后腿主要是为了炒菜用

51
00:05:02,000 --> 00:05:05,440
做黄焖手抓羊肉 主要用的是羊的前身

52
00:05:05,440 --> 00:05:07,000
羊的前身 就是

53
00:05:07,000 --> 00:05:11,840
羊脖子 羊腱子那些 羊排 软肋这些都要的

54
00:05:11,840 --> 00:05:13,840
羊一般是多大的羊

55
00:05:13,840 --> 00:05:17,760
这个羊就是六七个月 半岁吧 半岁多

56
00:05:17,760 --> 00:05:18,880
也就这么个样子

57
00:05:18,880 --> 00:05:19,840
得多重

58
00:05:19,840 --> 00:05:25,760
我们家一般是自己亲自去选 在羊肉铺

59
00:05:25,760 --> 00:05:28,360
大小在30斤左右

60
00:05:28,360 --> 00:05:33,120
这样就是一锅能煮出来

61
00:05:33,120 --> 00:05:36,720
要是大小有差异的话 一锅煮出来

62
00:05:36,720 --> 00:05:40,040
硬的硬 糯的糯 就是不太合适

63
00:05:40,040 --> 00:05:42,800
这样煮出来的话 肥而不腻

64
00:05:42,800 --> 00:05:45,600
出锅后会香嫩一些

65
00:05:45,600 --> 00:05:49,720
这里的羊肉真的是特别多 剁好的羊肉都有30多盆

66
00:05:49,720 --> 00:05:52,440
一天能够做多少斤的羊肉

67
00:05:52,440 --> 00:05:57,440
大概就是三百多斤吧 四百斤左右

68
00:06:07,900 --> 00:06:13,160
看到捞羊肉的场景 只能用壮观来形容了

69
00:06:54,300 --> 00:06:56,300
来吧 吃羊肉吧

70
00:07:48,180 --> 00:07:51,500
哇 好香啊

71
00:07:52,340 --> 00:07:54,340
这就是我们点的手抓羊肉

72
00:08:03,960 --> 00:08:06,040
这个要蘸着辣酱吃是吧

73
00:08:06,040 --> 00:08:07,000
嗯对

74
00:08:11,860 --> 00:08:14,380
现在手抓羊肉的料已经齐全了

75
00:08:14,800 --> 00:08:17,760
一份这个是带点辣椒油的

76
00:08:17,920 --> 00:08:20,500
油碟吧 然后这个就是椒盐

77
00:08:21,360 --> 00:08:24,140
刚才 我弱智地问了一句 这个怎么吃

78
00:08:24,560 --> 00:08:27,680
她说 撒上去吃也行 然后蘸着吃也行

79
00:08:28,060 --> 00:08:30,520
羊肉 一定要手抓着吃

80
00:08:31,920 --> 00:08:33,920
这样吃 才有特色

81
00:08:36,260 --> 00:08:38,640
你看 咱们在新疆吃手抓饭

82
00:08:39,280 --> 00:08:42,580
虽然叫手抓饭 但是可以用勺 筷子来吃

83
00:08:42,780 --> 00:08:44,780
今天这份手抓羊肉

84
00:08:46,240 --> 00:08:48,240
是真的要用手抓着吃

85
00:08:50,460 --> 00:08:51,100
吃这个

86
00:08:52,220 --> 00:08:53,100
就趁热吃

87
00:08:54,140 --> 00:08:56,140
先吃原味的

88
00:08:57,280 --> 00:08:59,280
它这个肉 炖的特别烂

89
00:08:59,980 --> 00:09:01,980
吃起来毫不费力

90
00:09:02,200 --> 00:09:04,200
可以蘸辣酱吃 也可以蘸干碟吃

91
00:09:17,860 --> 00:09:19,860
辣酱）它也不是很辣

92
00:09:19,860 --> 00:09:21,560
这个是我们自己配制的蒜酱

93
00:09:22,240 --> 00:09:24,240
蒜和辣子的调料

94
00:09:28,740 --> 00:09:32,160
刚才是蘸的油碟 它是里面有油 有蒜汁的

95
00:09:33,280 --> 00:09:35,280
咱们现在蘸下干的

96
00:09:40,580 --> 00:09:42,580
它就是另外一种风味

97
00:09:43,200 --> 00:09:45,360
就是没有油 没有蒜汁的味道

98
00:09:45,460 --> 00:09:47,320
反而有点烧烤的意思

99
00:09:48,280 --> 00:09:52,580
在西宁这边吃羊肉 可能就不能那么约束

100
00:09:52,580 --> 00:09:54,500
需要粗犷一点

101
00:09:55,580 --> 00:09:58,880
中午伴随我的除了羊肉 还有想了很久的酸奶

102
00:09:59,380 --> 00:10:01,660
上面有很黄的一层 但不是奶皮

103
00:10:01,660 --> 00:10:06,320
老板说是加了当地的食用油 这样颜色会更好看一些

104
00:10:06,320 --> 00:10:10,460
还有就是麦仁粥 小小的一碗 里面却有丰富的材料

105
00:10:11,720 --> 00:10:14,740
它里面真的能看到小麦 黄豆

106
00:10:14,740 --> 00:10:16,740
还冒着热气呢

107
00:10:23,800 --> 00:10:26,680
这里面是加了胡椒粉吗

108
00:10:26,800 --> 00:10:27,400
对

109
00:10:29,260 --> 00:10:32,120
还有肉

110
00:10:32,180 --> 00:10:34,180
是加了一些牛肉

111
00:10:37,880 --> 00:10:40,400
最后 我还得提一下我眼前的这盘土豆

112
00:10:41,420 --> 00:10:44,820
外面脆 里面是有点绵 有点软


```

**Comment by Kevinzheng5** [comment]
认领

**Comment by Kevinzheng5** [comment]
字幕
1
00:00:01,460 --> 00:00:02,260
青海·西宁
Xining, Qinghai province

2
00:00:02,500 --> 00:00:04,500
西宁市 是青藏高原的东方门户
Xining city is the eastern gate of the Qinghai-Tibet plateau

3
00:00:04,800 --> 00:00:06,800
独特的气候条件 和 地理条件
Its unique climate and geographical conditions

4
00:00:06,800 --> 00:00:09,600
使得这边形成了丰富的饮食文化
Formed the rich food culture here

5
00:00:09,600 --> 00:00:11,360
在众多的美食当中
Among all the great food around

6
00:00:11,360 --> 00:00:14,520
羊肉应该是出镜率最高的美食了
Lamb appears the most

7
00:00:14,520 --> 00:00:18,360
今天呢在西宁 我们找一个羊肉的特色吃法
Today in Xining, we’re going to try a special style of lamb

8
00:00:18,360 --> 00:00:20,240
手抓羊肉
Boiled lamb

9
00:00:23,600 --> 00:00:26,560
就是这里了
Right here

10
00:00:31,960 --> 00:00:36,800
一个个师傅都是抱着一怀的羊肉走进后厨
All the cooks are having lamb full in their arms when they walk in the kitchen 

11
00:00:41,200 --> 00:00:43,040
从路过的场面能够看出
We can see from here

12
00:00:43,040 --> 00:00:47,120
他们好像抱的都是肋排 羊排 还有羊腿
They are holding lamb ribs and legs

13
00:00:47,120 --> 00:00:48,840
这样的肉多一些
Mostly ribs and legs

14
00:00:48,840 --> 00:00:52,480
不知道自己说的对不对呢 待会去验证一下
I don’t know if I’m right. Let’s find out later

15
00:00:58,480 --> 00:01:00,960
哇
Whoa

16
00:01:01,640 --> 00:01:04,640
又来了一个
Another bunch

17
00:01:10,840 --> 00:01:13,920
咱们原来看剁肉的 都是在案板上
Usually we cut meat on a chopping board

18
00:01:13,920 --> 00:01:16,680
我刚才发现他们这边剁肉 有点不同
I just found out their way of chopping is a bit different

19
00:01:16,680 --> 00:01:19,440
他们的案板好像特别高
They have an extra high chopping board

20
00:01:42,120 --> 00:01:44,480
看来刚才的羊肉还只是冰山一角
All the lamb we saw are just the tip of the iceberg

21
00:01:44,480 --> 00:01:47,200
我不断地录 他们这边羊肉不断地放
They kept laying down lamb as I was shooting

22
00:01:47,200 --> 00:01:51,120
现在羊肉堆的 就像一座大山
All the lamb here looks like a mountain now

23
00:02:11,480 --> 00:02:12,520
虽然说 这边是一个饭店
It is a restaurant

24
00:02:12,520 --> 00:02:15,640
但是我觉得它更像是一个手抓羊肉的加工厂
But I think it’s more like a boiled lamb factory

25
00:02:15,640 --> 00:02:18,640
这边的羊肉剁完就会在另一边清洗
First they chop the lamb and wash it on the other side

26
00:02:18,640 --> 00:02:20,480
清洗之后 （羊肉）要炸 要焖
Then they fry and boil the lamb

27
00:02:20,480 --> 00:02:23,640
整个的制作过程可能需要十多个人来参与
The whole process needs more than a dozen people

28
00:02:23,640 --> 00:02:26,800
两个多小时才能够忙完 特别忙碌
It takes more than two hours and everybody is so busy

29
00:02:40,240 --> 00:02:42,920
因为肉太多 而且锅很大
The amount of lamb is huge and they have a tremendous pot

30
00:02:42,920 --> 00:02:45,000
所以说 在放羊肉的时候
So, when they put the lamb in the pot

31
00:02:45,000 --> 00:02:46,880
需要在下面放上一层料包
They need to put a layer of seasoning bags at the bottom

32
00:02:46,880 --> 00:02:51,840
上面再放一层料包 这样羊肉才能够更加入味
And another layer of seasoning bags on the top so that the flavor can penetrate

33
00:03:58,960 --> 00:04:01,240
现在羊肉呢 是正在炖着
Now the lamb is being boiled

34
00:04:01,240 --> 00:04:03,200
厨师们正在吃饭
The cooks are having their meals

35
00:04:03,200 --> 00:04:05,920
我发现他们吃的东西 我是没见过的
I found out that they are eating something I’ve never seen

36
00:04:05,920 --> 00:04:09,000
你好 我问一下 这个叫什么
Hi excuse me, what’s this?	

37
00:04:09,000 --> 00:04:12,720
这个叫焜锅馍馍
It’s the stew pot bun

38
00:04:12,720 --> 00:04:15,840
原来它就是焜锅馍馍
Oh this is the stew pot bun

39
00:04:17,560 --> 00:04:20,800
啊 它还有一个名字
Yeah, and it has another name

40
00:04:20,800 --> 00:04:22,660
青海面包
Qinghai bread

41
00:04:22,960 --> 00:04:26,840
它是甜的吗 还是说 只是面粉的味道
Is it sweat? Or is it just the taste of flour?

42
00:04:28,400 --> 00:04:32,280
很自然的 没有添加的
It’s very natural and we don’t add anything to it

43
00:04:32,400 --> 00:04:34,560
像在我们那儿 馍馍都是蒸出来的
In our place the buns are steamed

44
00:04:34,560 --> 00:04:37,800
我发现这个馍馍是烤出来的
This bun was baked

45
00:04:41,760 --> 00:04:45,120
逮住老板 问几个问题
We got the owner to ask a few questions

46
00:04:45,120 --> 00:04:50,200
我想问一下 我看羊肉不是全羊
I want to ask whether the lamb is whole lamb

47
00:04:51,880 --> 00:04:53,720
是羊的前身
It’s the fore half of the sheep

48
00:04:53,720 --> 00:04:56,400
就是后腿部分不要的
We don’t have the hind legs

49
00:04:56,400 --> 00:04:59,480
后腿部分 一般要的比较少一些
The hind legs don’t get ordered that much

50
00:04:59,480 --> 00:05:02,000
要后腿主要是为了炒菜用
They are mainly for stir frying dishes

51
00:05:02,000 --> 00:05:05,440
做黄焖手抓羊肉 主要用的是羊的前身
We mainly use the fore half for boiled lamb or stewed lamb

52
00:05:05,440 --> 00:05:07,000
羊的前身 就是
The fore half are basically

53
00:05:07,000 --> 00:05:11,840
羊脖子 羊腱子那些 羊排 软肋这些都要的
The neck, fore shank, ribs and loin. All of them

54
00:05:11,840 --> 00:05:13,840
羊一般是多大的羊
How old are the sheep usually?

55
00:05:13,840 --> 00:05:17,760
这个羊就是六七个月 半岁吧 半岁多
They are about 6-7 months. A little over half-year old

56
00:05:17,760 --> 00:05:18,880
也就这么个样子
That’s about it

57
00:05:18,880 --> 00:05:19,840
得多重
How much do they usually weigh?

58
00:05:19,840 --> 00:05:25,760
我们家一般是自己亲自去选 在羊肉铺
We usually go to the butcher’s ourselves

59
00:05:25,760 --> 00:05:28,360
大小在30斤左右
The sheep is about 30 jins (500 grams)

60
00:05:28,360 --> 00:05:33,120
这样就是一锅能煮出来
So the lamb in the whole pot can be evenly cooked

61
00:05:33,120 --> 00:05:36,720
要是大小有差异的话 一锅煮出来
If the size of sheep differ too much and we cook them in one pot

62
00:05:36,720 --> 00:05:40,040
硬的硬 糯的糯 就是不太合适
The texture will differ from tough and soft. That won’t be appropriate

63
00:05:40,040 --> 00:05:42,800
这样煮出来的话 肥而不腻
The half-year old sheep after cooking is rich but not greasy

64
00:05:42,800 --> 00:05:45,600
出锅后会香嫩一些
After boiling, it will have an aroma and juicy texture

65
00:05:45,600 --> 00:05:49,720
这里的羊肉真的是特别多 剁好的羊肉都有30多盆
It has the world’s lamb here. Only the cut lamb are more than 30 pots

66
00:05:49,720 --> 00:05:52,440
一天能够做多少斤的羊肉
How many lamb can we make here today?

67
00:05:52,440 --> 00:05:57,440
大概就是三百多斤吧 四百斤左右
About more than 300 jins (500 grams). About 400 jins (500 grams)

68
00:06:07,900 --> 00:06:13,160
看到捞羊肉的场景 只能用壮观来形容了
It’s such a view to watch them get the lamb out of the pot

69
00:06:54,300 --> 00:06:56,300
来吧 吃羊肉吧
Alright, let’s try some lamb

70
00:07:48,180 --> 00:07:51,500
哇 好香啊
Whoa! It smells so good

71
00:07:52,340 --> 00:07:54,340
这就是我们点的手抓羊肉
This is the boiled lamb we ordered

72
00:08:03,960 --> 00:08:06,040
这个要蘸着辣酱吃是吧
Does it go with the hot sauce?

73
00:08:06,040 --> 00:08:07,000
嗯对
Yeah right

74
00:08:11,860 --> 00:08:14,380
现在手抓羊肉的料已经齐全了
Now we have all the dipping for the lamb

75
00:08:14,800 --> 00:08:17,760
一份这个是带点辣椒油的
This one has some chili oil

76
00:08:17,920 --> 00:08:20,500
油碟吧 然后这个就是椒盐
The oil dipping. And this is the spiced salt

77
00:08:21,360 --> 00:08:24,140
刚才 我弱智地问了一句 这个怎么吃
I just asked a stupid question on how to have these

78
00:08:24,560 --> 00:08:27,680
她说 撒上去吃也行 然后蘸着吃也行
She told me to either put them on or dip

79
00:08:28,060 --> 00:08:30,520
羊肉 一定要手抓着吃
It’s important that we use our hands to eat the lamb

80
00:08:31,920 --> 00:08:33,920
这样吃 才有特色
That’s the style

81
00:08:36,260 --> 00:08:38,640
你看 咱们在新疆吃手抓饭
Remember we had pilaf in Xijiang?

82
00:08:39,280 --> 00:08:42,580
虽然叫手抓饭 但是可以用勺 筷子来吃
Even though it’s called hand grabbing rice, we usually have it with a spoon or chopsticks

83
00:08:42,780 --> 00:08:44,780
今天这份手抓羊肉
Today we are having the boiled lamb, which is called hand grabbing lamb

84
00:08:46,240 --> 00:08:48,240
是真的要用手抓着吃
We are actually gonna grab them with our hands

85
00:08:50,460 --> 00:08:51,100
吃这个
To have it

86
00:08:52,220 --> 00:08:53,100
就趁热吃
Let’s try when it’s still hot

87
00:08:54,140 --> 00:08:56,140
先吃原味的
Let’s try the original taste first

88
00:08:57,280 --> 00:08:59,280
它这个肉 炖的特别烂
The texture is really soft after boiled

89
00:08:59,980 --> 00:09:01,980
吃起来毫不费力
Doesn’t need any effort for you to eat them

90
00:09:02,200 --> 00:09:04,200
可以蘸辣酱吃 也可以蘸干碟吃
You can also have it with the hot sauce or the spiced salt

91
00:09:17,860 --> 00:09:19,860
辣酱）它也不是很辣
The hot sauce is not that spicy

92
00:09:19,860 --> 00:09:21,560
这个是我们自己配制的蒜酱
It’s the homemade garlic sauce

93
00:09:22,240 --> 00:09:24,240
蒜和辣子的调料
Garlic and chili sauce

94
00:09:28,740 --> 00:09:32,160
刚才是蘸的油碟 它是里面有油 有蒜汁的
We just tried the chili oil. It has chili oil and garlic sauce

95
00:09:33,280 --> 00:09:35,280
咱们现在蘸下干的
Now let’s try the spiced salt

96
00:09:40,580 --> 00:09:42,580
它就是另外一种风味
It’s a different flavor

97
00:09:43,200 --> 00:09:45,360
就是没有油 没有蒜汁的味道
It doesn’t have the oil or the garlic flavor

98
00:09:45,460 --> 00:09:47,320
反而有点烧烤的意思
It’s more like barbecue

99
00:09:48,280 --> 00:09:52,580
在西宁这边吃羊肉 可能就不能那么约束
When you have lamb in Xining, don’t restrict yourself

100
00:09:52,580 --> 00:09:54,500
需要粗犷一点
You can be more rugged

101
00:09:55,580 --> 00:09:58,880
中午伴随我的除了羊肉 还有想了很久的酸奶
Besides the lamb, my lunch also has the yogurt which I’ve looked forward for a long time

102
00:09:59,380 --> 00:10:01,660
上面有很黄的一层 但不是奶皮
It has a yellow layer but it’s not the milk skin

103
00:10:01,660 --> 00:10:06,320
老板说是加了当地的食用油 这样颜色会更好看一些
The owner told me they added some local vegetable oil so it has a better color

104
00:10:06,320 --> 00:10:10,460
还有就是麦仁粥 小小的一碗 里面却有丰富的材料
Also there’s the wheat congee. It has a lot of ingredients in a small bowl

105
00:10:11,720 --> 00:10:14,740
它里面真的能看到小麦 黄豆
We can see the wheat and beans here

106
00:10:14,740 --> 00:10:16,740
还冒着热气呢
It’s still steaming

107
00:10:23,800 --> 00:10:26,680
这里面是加了胡椒粉吗
Is it pepper in there?

108
00:10:26,800 --> 00:10:27,400
对
Yeah

109
00:10:29,260 --> 00:10:32,120
还有肉
And also meat

110
00:10:32,180 --> 00:10:34,180
是加了一些牛肉
Some beef

111
00:10:37,880 --> 00:10:40,400
最后 我还得提一下我眼前的这盘土豆
Last, I need to mention the plate of potatoes here

112
00:10:41,420 --> 00:10:44,820
外面脆 里面是有点绵 有点软
Crunchy outside and smooth inside
