### ISSUE TITLE
[老饭骨] 米汤浸时蔬 - https://youtu.be/XN1DGUjeRVc

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1249]
**视频链接**：https://youtu.be/XN1DGUjeRVc

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•米汤浸时蔬】不加一滴油的蔬菜新吃法！清爽细腻、健康低脂，家家都能做！ |老饭骨

简介
小友们好，老饭骨又给大家上菜咯！
这次带给大家的米汤浸时蔬，没有添加一滴油，非常的健康低脂，口感清爽细腻，而且这道菜做法非常简单，新手也能学会！
这道菜的爆点在哪里呢？大家听听大爷这回答，可太皮了！小友们看出来了吗？欢迎在评论区留言！
片尾大爷还讲了自己的一个愿望，原来大爷做厨师之前还想从事这个行业？到底是什么呢，小友们快去视频里找答案吧！

字幕
1
00:00:00,040 --> 00:00:01,560
爆点在哪儿呢 健康

2
00:00:01,560 --> 00:00:03,000
越滚越白 越黏了

3
00:00:03,000 --> 00:00:04,920
操作当中的最爆点在哪儿 简单

4
00:00:04,920 --> 00:00:07,520
过去就在这勺子上就弄上了

5
00:00:07,520 --> 00:00:08,760

6
00:00:08,760 --> 00:00:10,720
您能气死我

7
00:00:10,720 --> 00:00:12,040
您说啊

8
00:00:12,040 --> 00:00:13,000
家家都能做

9
00:00:13,000 --> 00:00:14,640
米汤浸时蔬

10
00:00:14,640 --> 00:00:18,080
 

11
00:00:18,080 --> 00:00:19,520
这是卫青萝卜

12
00:00:19,520 --> 00:00:22,960
先把这个萝卜给它刮下皮

13
00:00:22,960 --> 00:00:24,760
青萝卜白萝卜都行是吧

14
00:00:24,760 --> 00:00:29,240
咱们用青萝卜是为了颜色好看一点

15
00:00:29,240 --> 00:00:33,280
食材都比较普通  家家都有

16
00:00:33,280 --> 00:00:35,400
辛苦您帮我坐点水 好

17
00:00:35,400 --> 00:00:39,560
切成萝卜丝

18
00:00:39,560 --> 00:00:41,440
咱们这萝卜丝切好了

19
00:00:41,440 --> 00:00:44,640
然后咱们水里边下几个花椒粒

20
00:00:44,640 --> 00:00:48,680
作用是去掉萝卜的臭萝卜味儿

21
00:00:48,680 --> 00:00:51,600
够了吧 够了 再多了有味儿了

22
00:00:51,600 --> 00:00:54,880
这行了关火 你看这米油 没问题了

23
00:00:54,880 --> 00:00:55,920
粥底的一个做法

24
00:00:55,920 --> 00:00:58,760
广东菜就用米汤浸时蔬

25
00:00:58,760 --> 00:01:01,280
浸好多菜 都是用这种方法做的

26
00:01:01,280 --> 00:01:02,440
后来给演绎过来了

27
00:01:02,440 --> 00:01:06,120
水开了 咱把萝卜丝下锅焯一下

28
00:01:06,120 --> 00:01:07,920
去掉萝卜的臭气味

29
00:01:07,920 --> 00:01:10,200
放点盐 增加点底味

30
00:01:10,200 --> 00:01:12,400
可以把花椒撇出来了

31
00:01:12,400 --> 00:01:15,920
比如说老年人可以把萝卜炖的烂糊点

32
00:01:15,920 --> 00:01:17,840
这样入口即化

33
00:01:17,840 --> 00:01:20,160
再有还可以配点金针菇啊

34
00:01:20,160 --> 00:01:22,640
这种丝状的蘑菇

35
00:01:22,640 --> 00:01:27,920
虾丸鱼片这都行 因为萝卜吃腥

36
00:01:27,920 --> 00:01:29,920
大爷 虾最好用什么虾好吃啊

37
00:01:29,920 --> 00:01:33,000
生敲 生敲虾片

38
00:01:33,000 --> 00:01:34,960
吃着滑爽再搁这粥里边

39
00:01:34,960 --> 00:01:38,480
虾球 虾片 鱼丸 这都行

40
00:01:38,480 --> 00:01:40,520
你闻闻大爷这气味

41
00:01:40,520 --> 00:01:44,400
清香青脆 颜色好看

42
00:01:44,400 --> 00:01:46,640
咱们把这水倒了

43
00:01:46,640 --> 00:01:50,200
把米油过滤出来

44
00:01:50,200 --> 00:01:53,920
咱把火点上 它得调味儿

45
00:01:53,920 --> 00:01:56,360
瑶柱 瑶柱水 做好的（提前泡）

46
00:01:56,360 --> 00:01:58,760
倒在米油里边

47
00:01:58,760 --> 00:02:01,560
你看这个米汤很匀称 比勾芡还勾的好

48
00:02:01,560 --> 00:02:07,280
瑶柱这香味马上就出来了 鲜味出来了

49
00:02:07,680 --> 00:02:08,880
马上调味

50
00:02:08,880 --> 00:02:11,240
盐 少搁点盐

51
00:02:11,240 --> 00:02:13,240
然后（白）胡椒粉

52
00:02:13,240 --> 00:02:14,880
（白）胡椒粉提鲜

53
00:02:15,840 --> 00:02:17,120

54
00:02:17,120 --> 00:02:22,880
然后点一点糖代替味精 有一点就行 提鲜

55
00:02:22,880 --> 00:02:25,600
越滚越白 越黏了 收汁

56
00:02:25,600 --> 00:02:27,760
这个孕妇确实吃这不错

57
00:02:27,760 --> 00:02:29,760
好 咱们把火关了

58
00:02:29,760 --> 00:02:33,600

59
00:02:33,600 --> 00:02:36,680
过去就在这勺子上就弄上了

60
00:02:36,680 --> 00:02:40,000
好了师父 够了 家常方法

61
00:02:40,000 --> 00:02:42,560
咱们来点干贝 揉碎

62
00:02:42,560 --> 00:02:47,560
咱们撒在上边 星星点点

63
00:02:47,560 --> 00:02:49,240
好了 别太多了

64
00:02:49,240 --> 00:02:51,800
来大爷 您先尝尝

65
00:02:51,800 --> 00:02:53,880

66
00:02:53,880 --> 00:02:56,400
听这声音还是不错

67
00:02:56,400 --> 00:02:57,600
清爽   细腻

68
00:02:57,600 --> 00:03:00,040
为什么细腻 这米汤你看 不澥

69
00:03:00,040 --> 00:03:04,680

70
00:03:04,680 --> 00:03:05,600
真好喝

71
00:03:05,600 --> 00:03:06,960
爆点在哪儿呢 健康

72
00:03:06,960 --> 00:03:09,560
最爆点 操作当中的最爆点

73
00:03:09,560 --> 00:03:10,600
简单

74
00:03:10,600 --> 00:03:12,120

75
00:03:12,120 --> 00:03:13,880
您能气死我

76
00:03:13,880 --> 00:03:15,400
您说

77
00:03:15,400 --> 00:03:17,040
这个点在哪呢

78
00:03:17,040 --> 00:03:19,200
大爷 你看她那花椒加的特别巧

79
00:03:19,200 --> 00:03:21,440
你看一点花椒味儿吃不出来

80
00:03:21,440 --> 00:03:23,200
而且把萝卜这味给带走了

81
00:03:23,200 --> 00:03:26,400
这就是亮点 亮点在这儿

82
00:03:26,400 --> 00:00:02,000

83
00:03:33,320 --> 00:03:35,680
其实呢原来也有自己的一个愿望

84
00:03:35,680 --> 00:03:38,600
我想呢 这辈子干点什么呢

85
00:03:38,600 --> 00:03:40,080
第一

86
00:03:40,080 --> 00:03:41,160
没想干厨师啊

87
00:03:41,160 --> 00:03:43,320
想当个裁缝

88
00:03:43,320 --> 00:03:45,960
因为我觉得裁缝是个手艺人

89
00:03:45,960 --> 00:03:47,120
一把剪子

90
00:03:47,120 --> 00:03:50,680
不同的布料能裁出各种的

91
00:03:50,680 --> 00:03:52,240
千变万化的服装

92
00:03:52,240 --> 00:03:55,200
因为我小时候也爱穿新衣服

93
00:03:55,200 --> 00:03:57,240
所以就想当个裁缝

94
00:03:57,240 --> 00:03:58,680
这个愿望没实现

95
00:03:58,680 --> 00:04:01,320
第二个愿望想当一个

96
00:04:01,320 --> 00:04:02,400
那叫文秘

97
00:04:02,400 --> 00:04:03,280
现在叫秘书

98
00:04:03,280 --> 00:04:07,000
我就想呢写个报告啊 写个什么东西

99
00:04:07,000 --> 00:04:08,160
那阵也没有电脑

100
00:04:08,160 --> 00:04:10,240
全是那种铅印的打印机

101
00:04:10,240 --> 00:04:11,520
凿那个铅字的

102
00:04:11,520 --> 00:04:13,680
刷那油墨的

103
00:04:13,680 --> 00:04:15,520
我说我要把字练好了

104
00:04:15,520 --> 00:04:17,000
我给领导写篇文章

105
00:04:17,000 --> 00:04:19,200
写个总结 写个报告

106
00:04:19,200 --> 00:04:22,240
所以那阵我从上中学的时候

107
00:04:22,240 --> 00:04:24,000
我抄过王杰日记

108
00:04:24,000 --> 00:04:25,440
欧阳海日记

109
00:04:25,440 --> 00:04:26,720
焦裕禄日记

110
00:04:26,720 --> 00:04:28,040
你看我的作业

111
00:04:28,040 --> 00:04:30,000
就上中学的数学作业

112
00:04:30,000 --> 00:04:32,520
我从来不用铅笔

113
00:04:32,520 --> 00:04:34,400
我的作业全部都是钢笔

114
00:04:34,400 --> 00:04:40,680
而且写语文我这个作业本上没有一个是改过的

115
00:04:40,680 --> 00:04:42,440
只要我写错了一个字

116
00:04:42,440 --> 00:04:43,560
这张纸就撕了

117
00:04:43,560 --> 00:04:45,760
最挠头的时候

118
00:04:45,760 --> 00:04:48,560
最后一行写错了两个字

119
00:04:48,560 --> 00:04:50,160
但是我不涂不改

120
00:04:50,160 --> 00:04:52,280
撕 重新写

121
00:04:52,280 --> 00:04:54,600
希望我们的网友呢

122
00:04:54,600 --> 00:04:56,760
需要哪方面的知识

123
00:04:56,760 --> 00:04:58,240
都提示给我

124
00:04:58,240 --> 00:05:00,720
我通过老饭骨的叨叨叨

125
00:05:00,720 --> 00:05:03,040
来了解大家的需求

126
00:05:03,040 --> 00:05:06,000
尽量满足大家的愿望

127
00:05:06,000 --> 00:05:08,720
分享这方面的知识

128
00:05:08,720 --> 00:05:10,920
我们一定跟您好好学

129
00:05:10,920 --> 00:05:13,640
今天咱们就聊到这

130
00:05:13,640 --> 00:05:15,080
谢谢小语

131
00:05:15,080 --> 00:00:01,560
```

**Comment by GUThe** [comment]
Check

**Comment by GUThe** [comment]
https://youtu.be/XN1DGUjeRVc

【国宴大师•米汤浸时蔬】不加一滴油的蔬菜新吃法！清爽细腻、健康低脂，家家都能做！ |老饭骨
State Banquet Master Chefs-(check the video), Try this  

简介
小友们好，老饭骨又给大家上菜咯！
这次带给大家的米汤浸时蔬，没有添加一滴油，非常的健康低脂，口感清爽细腻，而且这道菜做法非常简单，新手也能学会！
这道菜的爆点在哪里呢？大家听听大爷这回答，可太皮了！小友们看出来了吗？欢迎在评论区留言！
片尾大爷还讲了自己的一个愿望，原来大爷做厨师之前还想从事这个行业？到底是什么呢，小友们快去视频里找答案吧！

Hello Friends, Lao Fangu’s presenting you a new dish!
Today’s recipe is “Rice Soup & Veggie Stew”, an refreshing, oil-free dish with smooth texture. The recipe is also quite simple, and easy-to-follow for new cookers!
What is the best part of this dish? Let’s listen to the lectures from Da Ye. Can anyone tell what does Da Ye mean? Share your opinion in the comment section down below!
At the end of the video Da Ye gives some interesting sidelights on his past dream occupations, let’s find out together.

字幕
1
00:00:00,040 --> 00:00:01,560
爆点在哪儿呢 健康
What makes this dish extraordinary? —Wholesomeness.

2
00:00:01,560 --> 00:00:03,000
越滚越白 越黏了
It’s boiled white and dense.

3
00:00:03,000 --> 00:00:04,920
操作当中的最爆点在哪儿 简单
What is the best part while cooking this dish?—Simpleness.

4
00:00:04,920 --> 00:00:07,520
过去就在这勺子上就弄上了
注释：存疑
Traditionally you can even operate with an spoon.


5
00:00:07,520 --> 00:00:08,760

6
00:00:08,760 --> 00:00:10,720
您能气死我
You piss me off Sir.

7
00:00:10,720 --> 00:00:12,040
您说啊
What say you, Sir.

8
00:00:12,040 --> 00:00:13,000
家家都能做
Everyone can cook it at home.

9
00:00:13,000 --> 00:00:14,640
米汤浸时蔬
Rice Soup & Veggie Stew 

10
00:00:14,640 --> 00:00:18,080
 

11
00:00:18,080 --> 00:00:19,520
这是卫青萝卜
This is Weiqin Radish.

12
00:00:19,520 --> 00:00:22,960
先把这个萝卜给它刮下皮
First peel the skin.

13
00:00:22,960 --> 00:00:24,760
青萝卜白萝卜都行是吧
Green radish and white radish both work?

14
00:00:24,760 --> 00:00:29,240
咱们用青萝卜是为了颜色好看一点
We use green ones only for atheistic purpose.

15
00:00:29,240 --> 00:00:33,280
食材都比较普通  家家都有
These are common ingredients.

16
00:00:33,280 --> 00:00:35,400
辛苦您帮我坐点水 好
Would you boil some water for me? Good.

17
00:00:35,400 --> 00:00:39,560
切成萝卜丝
Julienne the radish.

18
00:00:39,560 --> 00:00:41,440
咱们这萝卜丝切好了
Our radish silvers are ready.

19
00:00:41,440 --> 00:00:44,640
然后咱们水里边下几个花椒粒
Drop a couple of SiChuan Peppercorns.

20
00:00:44,640 --> 00:00:48,680
作用是去掉萝卜的臭萝卜味儿
This step should eliminate the “Radish Odor”.

21
00:00:48,680 --> 00:00:51,600
够了吧 够了 再多了有味儿了
Good? Good, we don’t want the pungent taste.

22
00:00:51,600 --> 00:00:54,880
这行了关火 你看这米油 没问题了
Alright turn off the heat. It’s all set, the rice oil oozes out.

23
00:00:54,880 --> 00:00:55,920
粥底的一个做法
Here’s one of the method to prepare the congee base.

24
00:00:55,920 --> 00:00:58,760
广东菜就用米汤浸时蔬
Guangdong Dish boils veggies in rice soup.

25
00:00:58,760 --> 00:01:01,280
浸好多菜 都是用这种方法做的
(Rice soup) is good company for many veggies, all using the same method.

26
00:01:01,280 --> 00:01:02,440
后来给演绎过来了
Then we have this kind of dish as successor. 


27
00:01:02,440 --> 00:01:06,120
水开了 咱把萝卜丝下锅焯一下
The water ‘s boiling, blanch the radish silvers.

28
00:01:06,120 --> 00:01:07,920
去掉萝卜的臭气味
Get rid of the radish odor.

29
00:01:07,920 --> 00:01:10,200
放点盐 增加点底味
Add a grin of salt to enhance the flavor.

30
00:01:10,200 --> 00:01:12,400
可以把花椒撇出来了
Fish out the peppercorns. 

31
00:01:12,400 --> 00:01:15,920
比如说老年人可以把萝卜炖的烂糊点
You can cook the radish to well done for your elders to enjoy. 

32
00:01:15,920 --> 00:01:17,840
这样入口即化
This way it melts into your mouth.

33
00:01:17,840 --> 00:01:20,160
再有还可以配点金针菇啊
And you can also get some needle mushroom.

34
00:01:20,160 --> 00:01:22,640
这种丝状的蘑菇
This kind of mushrooms.

35
00:01:22,640 --> 00:01:27,920
虾丸鱼片这都行 因为萝卜吃腥
注释：check afterwards
Shrimp balls, fillet are all good choices. Radish can balance their fishy odor. 

36
00:01:27,920 --> 00:01:29,920
大爷 虾最好用什么虾好吃啊
Da Ye, what kind of shrimp tastes the best?

37
00:01:29,920 --> 00:01:33,000
生敲 生敲虾片
Shredded prawn slices.


38
00:01:33,000 --> 00:01:34,960
吃着滑爽再搁这粥里边
The smooth texture of prawn makes it a good addition for congee.

39
00:01:34,960 --> 00:01:38,480
虾球 虾片 鱼丸 这都行
Shrimp balls, shredded prawn, fish balls, all good.


40
00:01:38,480 --> 00:01:40,520
你闻闻大爷这气味
Da Ye, smell it.


41
00:01:40,520 --> 00:01:44,400
清香青脆 颜色好看
It’s faintly fragrant and crispy, the color also looks nice. 


42
00:01:44,400 --> 00:01:46,640
咱们把这水倒了
Let’s pour out the water.

43
00:01:46,640 --> 00:01:50,200
把米油过滤出来
Filter out the rice oil.

44
00:01:50,200 --> 00:01:53,920
咱把火点上 它得调味儿
Turn on the heat, we need to season it.

45
00:01:53,920 --> 00:01:56,360
瑶柱 瑶柱水 做好的（提前泡）
Dried scallops and scallops water. We soaked the scallops in advance.

46
00:01:56,360 --> 00:01:58,760
倒在米油里边
Pour it into the rice oil.

47
00:01:58,760 --> 00:02:01,560
你看这个米汤很匀称 比勾芡还勾的好
You can tell that the texture of the rice soup is perfectly uniform, better than adding slurry.

48
00:02:01,560 --> 00:02:07,280
瑶柱这香味马上就出来了 鲜味出来了
Scallops’ savory aroma comes out immediately.

49
00:02:07,680 --> 00:02:08,880
马上调味
Season it right now.

50
00:02:08,880 --> 00:02:11,240
盐 少搁点盐
Salt, add a little bit of salt.

51
00:02:11,240 --> 00:02:13,240
然后（白）胡椒粉
After that, add white pepper.

52
00:02:13,240 --> 00:02:14,880
（白）胡椒粉提鲜
White pepper can boost the umami flavor.

53
00:02:15,840 --> 00:02:17,120

54
00:02:17,120 --> 00:02:22,880
然后点一点糖代替味精 有一点就行 提鲜
Add a touch of sugar instead of SMG, just a bit, for the umami flavor.

55
00:02:22,880 --> 00:02:25,600
越滚越白 越黏了 收汁
The soup is boiled white and dense, reduce the liquid.

56
00:02:25,600 --> 00:02:27,760
这个孕妇确实吃这不错
This dish is pretty good for pregnant women.

57
00:02:27,760 --> 00:02:29,760
好 咱们把火关了
Alright, let’s turn off the heat.

58
00:02:29,760 --> 00:02:33,600

59
00:02:33,600 --> 00:02:36,680
过去就在这勺子上就弄上了
In the past we do this step with a spoon 

60
00:02:36,680 --> 00:02:40,000
好了师父 够了 家常方法
Alright Master, we have sufficient techniques for home cooking already~

61
00:02:40,000 --> 00:02:42,560
咱们来点干贝 揉碎
Crush some dried scallops.

62
00:02:42,560 --> 00:02:47,560
咱们撒在上边 星星点点
We sprinkle the crush on it.

63
00:02:47,560 --> 00:02:49,240
好了 别太多了
Enough, don’t add too much

64
00:02:49,240 --> 00:02:51,800
来大爷 您先尝尝
Da Ye, try it first.

65
00:02:51,800 --> 00:02:53,880

66
00:02:53,880 --> 00:02:56,400
听这声音还是不错
According to the sound made—it’s not bad.

67
00:02:56,400 --> 00:02:57,600
清爽   细腻
Refreshing, smooth and delicate.

68
00:02:57,600 --> 00:03:00,040
为什么细腻 这米汤你看 不澥
Why smooth? Look at the soup, it’s not watery.

69
00:03:00,040 --> 00:03:04,680

70
00:03:04,680 --> 00:03:05,600
真好喝
Taste great!

71
00:03:05,600 --> 00:03:06,960
爆点在哪儿呢 健康
What makes this dish extraordinary? —Wholesomeness.

72
00:03:06,960 --> 00:03:09,560
最爆点 操作当中的最爆点
What is the best part while cooking this dish?.

73
00:03:09,560 --> 00:03:10,600
简单
—Simpleness

74
00:03:10,600 --> 00:03:12,120

75
00:03:12,120 --> 00:03:13,880
您能气死我
You pissed me off, Sir!

76
00:03:13,880 --> 00:03:15,400
您说
What say you, Sir?

77
00:03:15,400 --> 00:03:17,040
这个点在哪呢
What is important?

78
00:03:17,040 --> 00:03:19,200
大爷 你看她那花椒加的特别巧
Da Ye, she added peppercorns with very intricate techniques.

79
00:03:19,200 --> 00:03:21,440
你看一点花椒味儿吃不出来
There are barely any peppercorns’ pungency at all.

80
00:03:21,440 --> 00:03:23,200
而且把萝卜这味给带走了
It balances the radish taste as well.

81
00:03:23,200 --> 00:03:26,400
这就是亮点 亮点在这儿
This is the key, it’s right here.

82
00:03:26,400 --> 00:00:02,000

83
00:03:33,320 --> 00:03:35,680
其实呢原来也有自己的一个愿望
Actually, I used to have a dream.

84
00:03:35,680 --> 00:03:38,600
我想呢 这辈子干点什么呢
I thought to myself, what did I want to do with my life.

85
00:03:38,600 --> 00:03:40,080
第一
At the first place...

86
00:03:40,080 --> 00:03:41,160
没想干厨师啊
I did not desire to be a chef.

87
00:03:41,160 --> 00:03:43,320
想当个裁缝
I wanted to be a tailor.

88
00:03:43,320 --> 00:03:45,960
因为我觉得裁缝是个手艺人
Because I thought a tailor would be a handicraftsman.

89
00:03:45,960 --> 00:03:47,120
一把剪子
A scissor.

90
00:03:47,120 --> 00:03:50,680
不同的布料能裁出各种的
And varying clothing are made...

91
00:03:50,680 --> 00:03:52,240
千变万化的服装
...from different materials.

92
00:03:52,240 --> 00:03:55,200
因为我小时候也爱穿新衣服
I loved new clothes when I was a kid.

93
00:03:55,200 --> 00:03:57,240
所以就想当个裁缝
That also made me want to be a tailor.

94
00:03:57,240 --> 00:03:58,680
这个愿望没实现
This dream never comes true.

95
00:03:58,680 --> 00:04:01,320
第二个愿望想当一个
My second dream drove me to be a...

96
00:04:01,320 --> 00:04:02,400
那叫文秘
...As it was called, a secretarial clerk.

97
00:04:02,400 --> 00:04:03,280
现在叫秘书
Now we just call it Secretary.

98
00:04:03,280 --> 00:04:07,000
我就想呢写个报告啊 写个什么东西
All I wanted was to write a report or something.

99
00:04:07,000 --> 00:04:08,160
那阵也没有电脑
Back then there was no computer.

100
00:04:08,160 --> 00:04:10,240
全是那种铅印的打印机
Those letterpress typewriters occupied the entire market.

101
00:04:10,240 --> 00:04:11,520
凿那个铅字的
Carving the lead characters...

102
00:04:11,520 --> 00:04:13,680
刷那油墨的
Or brushing ink onto the printer.

103
00:04:13,680 --> 00:04:15,520
我说我要把字练好了
I told myself I was gonna try hard on practicing calligraphy. (The art of writing beautiful Chinese Characters)

104
00:04:15,520 --> 00:04:17,000
我给领导写篇文章
Then I might write an article for the leadership.

105
00:04:17,000 --> 00:04:19,200
写个总结 写个报告
Or I could write a summary, a report.

106
00:04:19,200 --> 00:04:22,240
所以那阵我从上中学的时候
Hence since I was in middle school.

107
00:04:22,240 --> 00:04:24,000
我抄过王杰日记
I tried to transcribe the Diary of Wang Jie,

108
00:04:24,000 --> 00:04:25,440
欧阳海日记
The Diary of Ou Yang Hai,

109
00:04:25,440 --> 00:04:26,720
焦裕禄日记
The Diary of Jiao Yu Lu.

110
00:04:26,720 --> 00:04:28,040
你看我的作业
Take a look at my homework,

111
00:04:28,040 --> 00:04:30,000
就上中学的数学作业
Middle school math homework to be specific.

112
00:04:30,000 --> 00:04:32,520
我从来不用铅笔
I never use pencils.

113
00:04:32,520 --> 00:04:34,400
我的作业全部都是钢笔
My homework’s were all written with pens. 

114
00:04:34,400 --> 00:04:40,680
而且写语文我这个作业本上没有一个是改过的
And while writing my Chinese homework I never did change a single character on my notebook.

115
00:04:40,680 --> 00:04:42,440
只要我写错了一个字
As soon as I miswrote one character,

116
00:04:42,440 --> 00:04:43,560
这张纸就撕了
I tore the sheet of paper.

117
00:04:43,560 --> 00:04:45,760
最挠头的时候
At the most head-scratching moment,

118
00:04:45,760 --> 00:04:48,560
最后一行写错了两个字
I miswrote two characters in the last row.

119
00:04:48,560 --> 00:04:50,160
但是我不涂不改
But I did not obliterate on the spots.

120
00:04:50,160 --> 00:04:52,280
撕 重新写
Tore it! Wrote it all over again.

121
00:04:52,280 --> 00:04:54,600
希望我们的网友呢
I hope our dear viewers.

122
00:04:54,600 --> 00:04:56,760
需要哪方面的知识
Don’t hesitate to leave a massage, 

123
00:04:56,760 --> 00:04:58,240
都提示给我
If you need any information from us.

124
00:04:58,240 --> 00:05:00,720
我通过老饭骨的叨叨叨
I hope to understand what our viewers want... 

125
00:05:00,720 --> 00:05:03,040
来了解大家的需求
...by keeping nagging at you on Lao Fangu.

126
00:05:03,040 --> 00:05:06,000
尽量满足大家的愿望
We will be trying our best to meet your expectations,

127
00:05:06,000 --> 00:05:08,720
分享这方面的知识
To share knowledge of such. 

128
00:05:08,720 --> 00:05:10,920
我们一定跟您好好学
We will definitely learn from you!

129
00:05:10,920 --> 00:05:13,640
今天咱们就聊到这
Let’s call it a day.

130
00:05:13,640 --> 00:05:15,080
谢谢小语
Thank you! Xiao Yu.

131
00:05:15,080 --> 00:00:01,560
