### ISSUE TITLE
[华农兄弟] 摘西瓜 - https://youtu.be/c1IaAhC7fYw

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1250]
https://youtu.be/c1IaAhC7fYw
<p>&#35270;&#39057;&#21457;&#24067;&#20110; July 7, 2020 at 12:03PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/c1IaAhC7fYw

#华农兄弟：兄弟很久没联系我们，估计是西瓜熟了，带2个小箩筐去摘
#Huanong Brothers: My buddy has not contacted me for a long time. I think it's because his watermelons are ripe. I go with two small baskets.

0:00:00.000,0:00:02.260
# 大家好 兄弟很久都沒有跟我聊過天啦
Hi everyone! My buddy hasn't talked with me for a long time.

0:00:02.640,0:00:05.140
# 估計我猜他家的那個西瓜肯定熟啦
I think, I bet his watermelons must be ripe now.

0:00:06.400,0:00:07.560
# 帶了兩個籮筐
So I come with two baskets,

0:00:08.280,0:00:10.720
# 去他家的那個瓜地裡面挑
to go to his farm and take some,

0:00:11.720,0:00:12.940
# 挑點西瓜回來
take some watermelons back home.

0:00:18.060,0:00:19.100
# 刀又沒帶
My knife is not here.

0:00:20.060,0:00:21.500
# 誒  剛好這裡有把刀
Eh? It just so happens that here's a knife.

0:00:23.060,0:00:24.260
# 這把刀  可以
This knife, is good enough.

0:00:24.580,0:00:25.740
# 帶一個杆子過來
And I have a pole with me.

0:00:28.800,0:00:29.400
# 帶上
Take the,

0:00:29.700,0:00:31.000
# 刀去備用一下
the knife with me, just in case

0:00:37.140,0:00:39.640
# 剛好把這個小  小女兒抬過去
Nice! It can also carry this little, little girl.

0:00:40.420,0:00:42.340
# 抬過去吃  吃飽再回來啊
Let me take her there, and come, come back when she has eaten enough.

0:00:44.000,0:00:45.760
# 哇  還有一個瀑布  漂不漂亮
Wa! Here's a waterfall too. Is it pretty?

0:00:46.860,0:00:47.880
# 瀑布靚不靚
Is the waterfall beautiful?

0:00:53.480,0:00:54.980
# 你看  兄弟家的香瓜
Look! My buddy's oriental melons,

0:00:55.440,0:00:56.520
# 壞了都不叫我們
he didn't call me and simply let them go rotten.

0:00:57.200,0:00:58.520
# 有幾個都壞掉啦
A couple of them are already rotten.

0:01:00.860,0:01:01.600
# 這有一個
Here's still one.

0:01:02.480,0:01:03.920
# 誒呀  這個也壞啦  這個
Eya! This is also rotten, this one,

0:01:04.880,0:01:05.920
# 那麼大都壞啦
though it's so large.

0:01:09.380,0:01:10.360
# 這也壞掉啦
This is also rotten.

0:01:10.800,0:01:12.040
# 你看  這裡一個
Look! Here's one.

0:01:12.840,0:01:14.000
# 它好像還不是很熟
But it doesn't seem completely ripe.

0:01:29.760,0:01:31.880
# 你看 這個  這有點裂開啦
Look! This one, this one is a bit cracked open.

0:01:37.840,0:01:39.200
# 嗯 剛剛好
Um! Perfect!

0:01:41.420,0:01:42.180
# 嗯 可以喲
Um! Not bad

0:01:43.980,0:01:45.020
# 這有點壞啦
It's a bit rotten.

0:01:46.480,0:01:47.300
# 我們就不要
We're not taking it.

0:01:49.040,0:01:50.140
# 我們吃那好的
Let's eat only the good part.

0:02:04.960,0:02:08.060
# 我們這種香瓜是有那個機肥種出來的哦
Our oriental melons here are grown with organic fertiliser, you know.

0:02:08.920,0:02:10.620
# 就是種下去不怎麼管
It means, they don't need much care.

0:02:11.740,0:02:12.780
# 它就長到那麼靚的
They can always grow well and are always so beautiful,

0:02:12.960,0:02:13.800
# 而且很膽
and are really crunchy too.

0:02:17.820,0:02:18.920
# 去摘點西瓜啦
Let's pick some watermelons.

0:02:20.460,0:02:21.080
# 放在這裡
I leave them here,

0:02:22.580,0:02:23.440
# 放這旁邊
put them aside.

0:02:26.300,0:02:26.800
# 給你吃
It's for you.

0:02:26.800,0:02:27.300
# 你看
Look!

0:02:27.960,0:02:28.620
# 西瓜
Watermelons

0:02:29.980,0:02:30.820
# 那麼小
They're so small.

0:02:31.600,0:02:32.760
# 我以為很大呢
I thought they were big.

0:02:37.660,0:02:38.440
# 刀都不用啦
I don't even need the knife.

0:02:40.740,0:02:41.980
# 你看  這種西瓜
Look! This kind of watermelons,

0:02:42.400,0:02:44.200
# 這種西瓜就已經熟透了的
a watermelon like this one means it is completely ripe.

0:02:45.860,0:02:49.020
# 啊  這個西瓜那麼小  我以為很大呢
Oh! This watermelon is so small. I though it were big.

0:02:49.760,0:02:50.740
# 跟我的頭一樣大
It's about the size my of head.

0:02:56.840,0:02:59.220
# 你看  這個也摘的  這個
Look! This can also be picked, this one.

0:03:01.480,0:03:03.920
# 哎呀  這種小西瓜  剛剛好
Aya! This kind of small watermelons, is a perfect,

0:03:04.320,0:03:05.440
# 一個人吃一個
single person portion.

0:03:09.160,0:03:10.000
# 這個也行
This one is also good.

0:03:12.760,0:03:14.560
# 你看  這種西瓜  哎呀
Look! This kind of watermelons... aya!

0:03:15.400,0:03:16.080
# 七八斤
three to four kilograms

0:03:17.000,0:03:18.180
# 剛好夠我一個人吃
It's just enough for me alone.

0:03:29.480,0:03:30.240
# 這個大
This one is huge.

0:03:33.900,0:03:35.240
# 哎喲 這一個大的
Ayo! This one is big!

0:03:36.320,0:03:36.960
# 大不大
Is it big?

0:03:37.380,0:03:38.160
# 你抱不動
You can't hold it.

0:03:38.960,0:03:40.640
# 你又跑到這裡來  割腳腳的
Why are you coming here? It cuts your cute little feet.

0:03:41.640,0:03:42.220
# 快點
C'mon!

0:03:51.220,0:03:52.480
# 很靚的  這兩個小的
These two small ones are, really beautiful!

0:03:58.540,0:04:00.580
# 媽媽我肚痛
Mama! My tummy hurts!

0:04:01.820,0:04:03.140
# 你看  這兩個大的
Look! These two are big.

0:04:05.860,0:04:06.380
# 這個
This is,

0:04:07.540,0:04:08.340
# 大西瓜
a giant watermelon.

0:04:17.880,0:04:19.660
# 不信  挑不起來
I can take it. Nothing is possible.

0:04:32.040,0:04:33.020
# 可以  可以  可以
Yea, yea, yea!

0:04:33.320,0:04:34.020
# 剛剛好
It's just right!

0:04:38.840,0:04:40.680
# 你看  兄弟家還有這個眉豆哦  (註︰他現在說眉豆，之後說扁豆，我都不知是甚麼豆，總之豆算了)
Look! My buddy has this kind of beans as well.

0:04:41.020,0:04:42.120
# 這個眉豆很好吃的
These beans are really tasty.

0:04:42.720,0:04:43.440
# 扁眉豆
The flat beans

0:04:44.240,0:04:45.380
# 不是吧  就一個
You kidding? Just one?

0:04:45.980,0:04:48.020
# 這一個  這沒用的  這個
This one, this is useless, this one.

0:04:48.180,0:04:48.720
# 壞的
It's rotten.

0:04:49.260,0:04:50.580
# 哎呀 這裡還有兩個
Aya! Here are two more.

0:04:51.860,0:04:53.700
# 你看  這個眉豆
Look! These beans...

0:04:56.960,0:04:58.440
# 誒  這裡還有一個
Eh? Here's one more.

0:04:58.900,0:05:00.240
# 就一餐啊  剛剛好
It's a perfect portion, for one meal,

0:05:01.480,0:05:02.520
# 剛好煮一餐
one single meal.

0:05:07.180,0:05:07.880
# 哎喲
Ayo!

0:05:08.920,0:05:09.860
# 剛好夠一餐
It's one meal portion,

0:05:10.500,0:05:11.660
# 一個小家庭
No too much, not too little

0:05:12.800,0:05:13.900
# 剛好夠吃
for a small family

0:05:14.880,0:05:15.620
# 還有沒有
Any more?

0:05:17.560,0:05:18.860
# 這天氣太熱啦
It's too hot now.

0:05:19.180,0:05:20.140
# 汗都出來啦
I'm even sweating.

0:05:24.160,0:05:25.220
# 你看  這個扁豆
Look! These beans...

0:05:26.040,0:05:27.740
# 剛好去買點  買點豬肉
We can just buy some, buy some pork.

0:05:29.280,0:05:31.060
# 豬肉炒一下這篇豆很好吃的哦
It's really tasty when these beans are fried with pork.

0:05:31.560,0:05:32.800
# 等一下  我要帶回去
I'll bring them back in a while.

0:05:34.580,0:05:36.220
# 你看  這還有兩個絲瓜哦
Look! Here are two sponge gourds too.

0:05:37.320,0:05:38.260
# 刀都沒帶
But my knife is not with me.

0:05:39.840,0:05:40.560
# 把它擰斷
I just twist them off.

0:05:49.320,0:05:50.280
# 這裡有一個
Here's one.

0:05:53.200,0:05:54.660
# 這種絲瓜很靚的
These sponge gourds are really beautiful.

0:05:55.940,0:05:58.180
# 打湯很好  很好吃的哦  這裡有一個
You know, making a soup with them is really tasty. Here's one.

0:06:02.120,0:06:02.820
# 靚吧
Beautiful, isn't it?

0:06:04.880,0:06:06.240
# 你看  摘了那麼一點點
Look! I've picked just a tiny little bit here.

0:06:11.180,0:06:12.820
# 兄弟  這個玉米是不是你家的
Hey man! Are these corns yours?

0:06:13.500,0:06:14.000
# 是啊
Yup!

0:06:15.020,0:06:15.920
# 熟了哦
They're ripe now.

0:06:16.380,0:06:17.120
# 沒熟
No, they aren't!

0:06:17.220,0:06:19.180
# 熟啦  你看  那個鬚都老啦
Yes, they are! Look! The silk is already getting old!

0:06:20.800,0:06:21.760
# 沒熟都沒熟
Well, let it be no then.

0:06:22.300,0:06:23.160
# 看一下還有沒有其它的
Let me see if there is anything else.

0:06:23.160,0:06:24.820
# 沒有熟啊  下次來
They're not ripe. Come again next time.

0:06:25.360,0:06:26.540
# 辣椒  辣椒
Chilli, chilli

0:06:26.960,0:06:30.100
# 等下次熟的時候我再  我再叫你過來摘
I'll call you, call you to come again when they're ripe.

0:06:30.540,0:06:31.920
# 你看  那些瓜子那些
Look! The gourds, there,

0:06:32.360,0:06:33.960
# 那麼多瓜子都老啦
there are so many of them and they're already old.

0:06:35.360,0:06:37.800
# 這生薑  生薑很靚的哦 這生薑  你看
The ginger, ginger is really beautiful. The ginger, look!

0:06:39.020,0:06:41.120
# 還沒長大  可以挖  可以挖啦  差不多  (註︰原字幕沒有寫下「還沒長大」，但一拼翻譯會較有趣)
They haven't grown up yet.
We can dig them up, dig them up. They're ready now.

0:06:41.120,0:06:42.000
# 還沒長大  這個
They have not yet grown up, the ginger.

0:06:42.040,0:06:42.540
# 沒長大
Not yet?

0:06:42.580,0:06:43.220
# 沒大 沒大
No, no, no

0:06:43.840,0:06:44.360
# 下次來
Next time

0:06:44.920,0:06:47.880
# 是呀  摘那麼(大)[SIC]多你也  你也拿不到是不是
Exactly! Don't take too much. You can't carry that much, right?

0:06:48.460,0:06:49.160
# 拿得到
Yes, I can!

0:06:49.240,0:06:52.280
# 拿不到  走走走走回去啦  大陽那麼大
No, you can't! Go, go go! Let's go back! The sun is so strong now.

0:06:52.800,0:06:53.700
# 你看  這青瓜
Look! The cucumber...

0:06:54.120,0:06:54.900
# 太浪費啦
What a waste!

0:06:59.780,0:07:01.140
# 這種青的很好吃的哦
These green ones are really tasty, you know.

0:07:10.880,0:07:13.500
# 額  這蕉還沒開花就長得那麼茂盛
Eh! The banana, they're already growing so well, though there are still no flowers.

0:07:16.480,0:07:18.180
# 劉楚萱走啦  不要啦
Liu Chuxuan, let's go! We're not taking it.

0:07:18.940,0:07:19.760
# 你要是不是
You want it, don't you?

0:07:23.700,0:07:24.580
# 可以  給你
Alright. Take it!

0:07:26.200,0:07:26.820
# 媽媽
Mama!

0:07:26.960,0:07:28.260
# 今天晚上煮給你吃啊
I'll cook it for your dinner tonight, alright?

0:07:29.360,0:07:30.200
# 要不要吃
You want it?

0:07:30.240,0:07:30.740
# 要
Yes

0:07:31.480,0:07:32.140
# 要吃
You want.

0:07:33.500,0:07:35.520
# 哇 你看  摘了那麼多
Wa! Look! I've picked so many!

0:07:51.600,0:07:53.080
# 兄弟家的苦瓜在這裡哦
My buddy's bitter gourds are here.

0:07:53.840,0:07:54.660
# 下去看一下
Let me go down and have a look.

0:07:55.960,0:07:56.600
# 看有沒有
I'm gonna see if there are any,

0:08:01.580,0:08:03.240
# 哎呀  好多哇
Aya! A lot!

0:08:03.300,0:08:04.540
# 啊  在這乘一下涼
Ah! Let me take a shelter and cool down here.

0:08:05.100,0:08:05.720
# 好累啦
I'm exhausted.

0:08:05.760,0:08:07.940
# 爸爸  這裡有一個
Daddy! Here's one!

0:08:08.100,0:08:09.380
# 嗯  這個不要去動
Um! Make sure that you're not touching it.

0:08:11.340,0:08:13.040
# 這裡好多  好多苦瓜
Here are a lot, a lot of bitter gourds.

0:08:14.120,0:08:15.360
# 順便摘一點回去
Why don't we pick some back home?

0:08:22.500,0:08:23.600
# 苦瓜你也要哇
You want a bitter gourd too?

0:08:24.000,0:08:24.580
# 拿著
Hold it.

0:08:25.740,0:08:26.380
# 放在這裡
Put it here.

0:08:27.180,0:08:28.080
# 在這等一下我啊
Wait for me here.

0:08:30.860,0:08:31.640
# 這裡一個
Here's one.

0:08:32.180,0:08:33.100
# 你看  這樣的苦瓜
Look! This kind of bitter gourds,

0:08:33.460,0:08:35.600
# 我們本地的小苦瓜  很好吃的
are the local little bitter gourds here. They're really tasty.

0:08:37.040,0:08:38.120
# 香味十足
A rich scent of bitter gourd

0:08:40.760,0:08:42.300
# 這個也很靚的 這個
This one is also beautiful, this one.

0:08:42.660,0:08:44.700
# 今天晚上就可以釀苦瓜啦
Then tonight, we can have stuffed better gourd,

0:08:45.100,0:08:46.700
# 還有苦瓜炒肉
and also bitter gourd fried with pork,

0:08:47.140,0:08:48.500
# 還有紅燒苦瓜
and also stewed bitter gourd.

0:08:49.240,0:08:51.580
# 兄弟家吃不完  那麼多他哪裡吃的完
My buddy can't finish them. How can he finish them? There are so many.

0:08:51.820,0:08:52.740
# 我幫他吃一點
I'm here to help him.

0:08:53.060,0:08:54.080
# 別浪費啦
Don't waste the food.

0:09:08.940,0:09:09.720
# 哎喲
Ayo!

0:09:10.880,0:09:13.020
# 它這個棍子  放這裡踢腳
The rod is here, it's here to set me up.

0:09:18.240,0:09:19.300
# 把這個大的給你
This big one is for you.

0:09:20.240,0:09:21.160
# 這裡有一個是不是
Here's one, right?

0:09:24.200,0:09:25.580
# 那裡也有一個
There's another one!

0:09:25.620,0:09:28.180
# 夠啦  夠啦  夠啦  可以啦  別那麼貪心
Enough, enough, enough. It's alright now! Don't be so greedy!

0:09:28.760,0:09:29.960
# 那麼小就那麼貪心
You're still a baby and you're already so greedy.

0:09:30.520,0:09:31.620
# 拿都你都拿不到啦
You can't even take anymore!

0:09:32.380,0:09:33.960
# 走啦  我們回家家  走走
Let's go! Home sweet home! Let's go!

0:09:34.800,0:09:35.300
# 夠啦  
It's enough.

0:09:36.400,0:09:37.020
# 不要那麼多
We don't need too many.

0:09:42.980,0:09:44.380
# 放到冰箱裡面凍一下
Let's chill it in the fridge.

0:09:45.040,0:09:46.040
# 吃一個再說
Let's share one first.

0:09:46.720,0:09:48.700
# 用這個水流沖一下  這個西瓜
I'm gonna rinse the watermelon, with the running water.

0:09:49.060,0:09:49.920
# 更快冷
It will cool down much faster.

0:09:50.800,0:09:54.880
# 這個  曬  曬燙了的西瓜吃會拉肚  會拉肚子的哦
This, a watermelon heated under the sun, is gonna give you a bad, stom..., a bad stomach.

0:10:04.440,0:10:05.520
# 刀都磿好啦
The knife is already sharpened.

0:10:05.860,0:10:07.640
# 就等著這個西瓜  冷了就吃
Let wait until the watermelon, cools down.

0:10:09.900,0:10:12.500
# 這個水龍頭  那麼慢它的速度
The tap is, why is it so slow?

0:10:13.240,0:10:15.260
# 流的  流水的速度太慢啦
The water, the water flows too slowly.

0:10:18.320,0:10:19.400
# 泡了一個小時
An hour has passed.

0:10:20.240,0:10:20.820
# 熟啦
It's ripe.

0:10:23.100,0:10:23.720
# 把這個
Let me...

0:10:26.100,0:10:27.160
# 哎呀 好紅
Aya! It's so red!

0:10:27.520,0:10:28.380
# 差點跑啦
It almost runs away.

0:10:29.180,0:10:31.140
# 哇  手  你手拿開
Wa! Hand! Get your hand off!

0:10:32.560,0:10:33.740
# 等一下  等一下
A moment, a moment!

0:10:34.060,0:10:34.820
# 等下啊
A moment, okay?

0:10:35.280,0:10:35.900
# 等下
A moment

0:10:38.820,0:10:39.780
# 我切一塊給你吃啊
I give you a piece, alright?

0:10:40.920,0:10:42.300
# 快點  你先去吃
C'mon! Take it first!

0:10:42.640,0:10:43.760
# 坐那旁邊吃啊
Sit over there and finish it, okay?

0:10:44.020,0:10:44.820
# 吃完來啊
Finish it, alright?

0:10:47.520,0:10:48.960
# 哇 這西瓜好紅啊
Wa! This watermelon is so red!

0:10:49.180,0:10:50.340
# 而且還有沙的哦
And it's grainy too.

0:10:53.420,0:10:56.460
# 兄弟肯定用有機肥種出來的  絕對好吃
My buddy must have grown it with organic fertiliser. It's absolutely tasty.

0:10:56.880,0:10:58.580
# 先嘗一下  看好不好吃
Let me have a try first, and see if it's tasty.

0:11:01.240,0:11:01.940
# 嗯
Um!

0:11:02.920,0:11:03.540
# 可以喲
Not bad!

0:11:07.040,0:11:07.800
# 不要來
Stand clear!

0:11:17.460,0:11:18.580
# 太甜啦  這個  (註︰這裡用"too"好像怎麼搞都是負面意思，改一下用字較好)
It's really really sweet, this,

0:11:19.100,0:11:19.760
# 這西瓜
this watermelon.

0:11:23.420,0:11:24.700
# 這瓜瓜太甜啦  是不是
The melon is really sweetie sweetie, isn't it?

0:11:26.540,0:11:28.420
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.

0:11:30.120,0:11:30.880
# 吃相不好
My eating manner is bad.

0:11:31.180,0:11:31.900
# 吃相不好
My manner is bad.

0:11:32.320,0:11:33.200
# 不要把啦
Don't film me.
