### ISSUE TITLE
【美食作家王刚】解释后厨教学停更 - https://youtu.be/FmnoakOKwqk

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1251]
**视频链接**：https://youtu.be/FmnoakOKwqk

视频时长3:31，预计发布时间为北京时间7月9日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
这段时间做菜视频停更说明，并没有偷懒，为更优质的内容和画面做准备！

简介
大家好，新工作室正式投入使用！下期视频开始正式更新硬核后厨教学内容，这段时间花了太多精力在工作室的翻新；设备的更新和调试；还有后期方面，导致了视频断更，请大家谅解。不过我觉得还是值得的，永远在学习中，让自己的内容在各方面进步，为了给大家呈现出更加优质的内容而努力！

字幕
0:00:00.460,0:00:01.340
哈喽 大家好

0:00:01.340,0:00:02.300
我是王刚

0:00:02.300,0:00:06.300
最近停更了（做菜视频）差不多有10天半个月了吧

0:00:06.300,0:00:08.100
这些时间粉丝也在问我

0:00:08.100,0:00:09.580
这段时间到底在干什么

0:00:09.580,0:00:12.322
其实我想跟大家说我一刻也没有闲着

0:00:12.580,0:00:16.009
然后这边的话是我们的厨房

0:00:16.009,0:00:18.300
现在已经全部ok了

0:00:18.710,0:00:22.150
 这里其实已经拍了一期视频了

0:00:22.150,0:00:24.430
这是电影机的三脚架

0:00:24.430,0:00:26.550
这个箱子是专门装电影机的

0:00:26.590,0:00:27.806
那个是装微单的

0:00:28.070,0:00:30.070
这里有一些三脚架一些灯

0:00:30.290,0:00:32.209
还有一些厨具已经全部到了

0:00:32.209,0:00:33.890
然后昨天拍了一期

0:00:33.890,0:00:35.410
现在在做后期

0:00:35.410,0:00:37.764
其实这个后期流程比较复杂

0:00:38.010,0:00:39.170
是非常麻烦的

0:00:39.450,0:00:41.800
大家过来这边看一下

0:00:42.370,0:00:46.650
我这边总共有三台这个炒菜的灶

0:00:46.980,0:00:48.180
就是炒菜的灶

0:00:48.180,0:00:49.460
大家会问我这个

0:00:50.168,0:00:51.887
其实用这么多灶来干什么

0:00:52.310,0:00:54.770
就是为了以后这里成熟了之后

0:00:55.070,0:00:57.990
可以到时候接待粉丝什么的过来吃大餐

0:00:58.030,0:00:59.030
是没有问题的

0:00:59.030,0:01:01.190
其实我拍视频只要一台就够了

0:01:01.230,0:01:02.430
为什么买这么多

0:01:02.470,0:01:05.630
就是想着吧 想法总是美好的

0:01:05.850,0:01:06.510
是吧

0:01:06.900,0:01:08.300
多招几个徒弟啊

0:01:08.300,0:01:09.420
有用的徒弟

0:01:09.420,0:01:11.081
男徒弟过来学厨艺

0:01:11.340,0:01:12.620
学好了之后

0:01:12.860,0:01:14.520
接待一下粉丝也挺好玩的

0:01:14.700,0:01:16.740
这个是补光灯

0:01:17.280,0:01:18.740
然后我这边

0:01:18.920,0:01:20.250
是切菜的地方

0:01:21.130,0:01:23.270
像这个砧板也换了一个

0:01:23.450,0:01:24.800
因为原先的砧板

0:01:25.050,0:01:27.170
特别容易发霉

0:01:27.250,0:01:29.890
现在是用的这种更硬一点的

0:01:29.890,0:01:31.250
更耐用一点

0:01:31.290,0:01:32.970
然后这边是两个补光灯

0:01:33.010,0:01:35.890
其实为什么换这么大的工作室的原因就是

0:01:35.890,0:01:38.570
原先的工作室这一面是靠墙的

0:01:38.570,0:01:39.975
我想做一些补光

0:01:40.290,0:01:43.750
想换一些长焦镜头是根本就没有位置

0:01:44.050,0:01:45.010
所以

0:01:47.340,0:01:50.060
这边然后是两个冰箱

0:01:50.060,0:01:51.540
现在只开了一个

0:01:51.830,0:01:54.190
放的食材什么的都比较少

0:01:54.640,0:01:56.600
现在只是说开了运行一下

0:01:56.860,0:01:58.580
然后下面放了一些菜

0:01:58.760,0:02:03.335
这些菜目前就是我跟摄影师

0:02:04.320,0:02:06.939
上午过来拍 拍到中午之后 我们就自己炒了

0:02:07.310,0:02:08.550
炒点菜在这里吃了

0:02:08.550,0:02:10.550
然后吃完饭下午又接着干

0:02:10.590,0:02:12.750
然后这一台的话暂时还没有用

0:02:13.000,0:02:14.480
这些也是全新的

0:02:14.480,0:02:16.652
然后这边还有一个六眼灶

0:02:17.140,0:02:19.060
就跟我那边差不多吧

0:02:19.060,0:02:22.860
六眼灶买来就是拍一些比较

0:02:23.080,0:02:26.499
更加家常的做一些煲仔呀煲汤之类的就在这边做

0:02:27.650,0:02:29.690
 现在整体做了一天

0:02:29.690,0:02:32.050
昨天拍了一期感觉这个

0:02:32.450,0:02:35.027
这边特别湿啊特别回潮

0:02:35.174,0:02:36.490
蚊子特别多

0:02:36.725,0:02:38.145
其他都还好

0:02:38.330,0:02:40.050
然后这里空间也够高

0:02:40.050,0:02:40.770
然后

0:02:41.020,0:02:42.520
布局也比较好

0:02:42.834,0:02:46.240
就感觉做起来更加得心应手吧

0:02:46.438,0:02:48.200
嗯 昨天拍了第一期

0:02:48.400,0:02:49.957
虽然说拍得很辛苦

0:02:50.400,0:02:54.244
扛着个电影机还有那三角架加起来肯定有30多斤

0:02:54.360,0:02:55.357
扛着跑来跑去的

0:02:55.357,0:02:56.432
然后这些灯啊

0:02:56.432,0:02:58.560
第一天拍遇到了不少麻烦

0:02:58.780,0:03:00.420
不过这些都是小问题

0:03:00.420,0:03:02.300
特别容易就克服了

0:03:02.520,0:03:03.730
小小的问题

0:03:03.910,0:03:04.840
难不倒我们

0:03:05.340,0:03:06.870
然后这边

0:03:07.360,0:03:08.200
明天吧

0:03:08.200,0:03:10.960
明天我们的视频做菜的视频就会更新

0:03:11.180,0:03:12.960
但是第一期我们没有做菜

0:03:13.140,0:03:15.100
第一期用冰糖

0:03:15.100,0:03:16.420
用糖拍了一期

0:03:16.579,0:03:18.940
你们可以先猜一下我们拍的是什么

0:03:19.260,0:03:20.220
呃 好了

0:03:20.260,0:03:21.420
本期视频就到这里

0:03:21.420,0:03:27.464
以后的话会在这里产出更多质量更高的内容

0:03:27.900,0:03:29.395
就到这里 拜拜


```

**Comment by siyusun6918** [comment]
认领

**Comment by siyusun6918** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
这段时间做菜视频停更说明，并没有偷懒，为更优质的内容和画面做准备！
Explaining why I paused uploading cooking tutorials for the preparation of better content and imagine! 

简介
大家好，新工作室正式投入使用！下期视频开始正式更新硬核后厨教学内容，这段时间花了太多精力在工作室的翻新；设备的更新和调试；还有后期方面，导致了视频断更，请大家谅解。不过我觉得还是值得的，永远在学习中，让自己的内容在各方面进步，为了给大家呈现出更加优质的内容而努力！
Hello! The new studio has launched. From the next video, kitchen tutorials will be resumed. I have spent many efforts in the renovation of the studio and equipment, and post-production, which results in the pause of uploading. Please forgive us. But I think it’s worth it. Keep learning and getting better, and making great efforts for better content.   

字幕
0:00:00.460,0:00:01.340
哈喽 大家好
Hello

0:00:01.340,0:00:02.300
我是王刚
I am Chef Wang

0:00:02.300,0:00:06.300
最近停更了（做菜视频）差不多有10天半个月了吧
I haven’t uploaded cooking videos for about half a month. 

0:00:06.300,0:00:08.100
这些时间粉丝也在问我
Fans also have been asking me 

0:00:08.100,0:00:09.580
这段时间到底在干什么
What was I doing during this time

0:00:09.580,0:00:12.322
其实我想跟大家说我一刻也没有闲着
I what to tell you all that I was busy working

0:00:12.580,0:00:16.009
然后这边的话是我们的厨房
This is our kitchen 

0:00:16.009,0:00:18.300
现在已经全部ok了
It’s all ready and ok now

0:00:18.710,0:00:22.150
 这里其实已经拍了一期视频了
We have already shot a video here

0:00:22.150,0:00:24.430
这是电影机的三脚架
This is the tripod for the movie camera

0:00:24.430,0:00:26.550
这个箱子是专门装电影机的
This box is for the movie camera

0:00:26.590,0:00:27.806
那个是装微单的
That one is for the digital camera

0:00:28.070,0:00:30.070
这里有一些三脚架一些灯
Here are some tripods and lights

0:00:30.290,0:00:32.209
还有一些厨具已经全部到了
And some of the cooking equipment has arrived 

0:00:32.209,0:00:33.890
然后昨天拍了一期
And we shot one video yesterday

0:00:33.890,0:00:35.410
现在在做后期
We are doing post-production now

0:00:35.410,0:00:37.764
其实这个后期流程比较复杂
The process of post-production is actually complex

0:00:38.010,0:00:39.170
是非常麻烦的
It’s really a big deal

0:00:39.450,0:00:41.800
大家过来这边看一下
Let’s take a cook here

0:00:42.370,0:00:46.650
我这边总共有三台这个炒菜的灶
I have three cooking stations

0:00:46.980,0:00:48.180
就是炒菜的灶
Cooking stations with stoves

0:00:48.180,0:00:49.460
大家会问我这个
People ask me

0:00:50.168,0:00:51.887
其实用这么多灶来干什么
Why so many stations

0:00:52.310,0:00:54.770
就是为了以后这里成熟了之后
When the business is mature here

0:00:55.070,0:00:57.990
可以到时候接待粉丝什么的过来吃大餐
We can host fans for a big meal here

0:00:58.030,0:00:59.030
是没有问题的
There’s no problem 

0:00:59.030,0:01:01.190
其实我拍视频只要一台就够了
Actually I only need one stove for making videos

0:01:01.230,0:01:02.430
为什么买这么多
Then why I bought so many

0:01:02.470,0:01:05.630
就是想着吧 想法总是美好的
I was thinking, Intentions are always great

0:01:05.850,0:01:06.510
是吧
Isn’t it

0:01:06.900,0:01:08.300
多招几个徒弟啊
Recruit a few more apprentices 

0:01:08.300,0:01:09.420
有用的徒弟
Usefel appretices

0:01:09.420,0:01:11.081
男徒弟过来学厨艺
Male apprentices come to learn how to cook

0:01:11.340,0:01:12.620
学好了之后
After they learned

0:01:12.860,0:01:14.520
接待一下粉丝也挺好玩的
It’s fun to host fans

0:01:14.700,0:01:16.740
这个是补光灯
This is the fill-light

0:01:17.280,0:01:18.740
然后我这边
And here is 

0:01:18.920,0:01:20.250
是切菜的地方
A placing for cutting ingredients 

0:01:21.130,0:01:23.270
像这个砧板也换了一个
We changed to a new cutting board

0:01:23.450,0:01:24.800
因为原先的砧板
Because the old cutting board

0:01:25.050,0:01:27.170
特别容易发霉
is really easy to go moldy

0:01:27.250,0:01:29.890
现在是用的这种更硬一点的
Now we are using the harder one

0:01:29.890,0:01:31.250
更耐用一点
It can last longer

0:01:31.290,0:01:32.970
然后这边是两个补光灯
There are two fill-lights

0:01:33.010,0:01:35.890
其实为什么换这么大的工作室的原因就是
The reason why I changed into this big studio is that

0:01:35.890,0:01:38.570
原先的工作室这一面是靠墙的
In the old studio, this side was leaning the wall

0:01:38.570,0:01:39.975
我想做一些补光
I want to fill some lights

0:01:40.290,0:01:43.750
想换一些长焦镜头是根本就没有位置
There is no room for long lens

0:01:44.050,0:01:45.010
所以
So

0:01:47.340,0:01:50.060
这边然后是两个冰箱
Here are two friges

0:01:50.060,0:01:51.540
现在只开了一个
Only one is operating 

0:01:51.830,0:01:54.190
放的食材什么的都比较少
We put a few ingredients in here

0:01:54.640,0:01:56.600
现在只是说开了运行一下
It’s operating for testing

0:01:56.860,0:01:58.580
然后下面放了一些菜
And down here are some dishes

0:01:58.760,0:02:03.335
这些菜目前就是我跟摄影师
These dishes are for the photographer and me

0:02:04.320,0:02:06.939
上午过来拍 拍到中午之后 我们就自己炒了
We came here and filmed before noon.  

0:02:07.310,0:02:08.550
炒点菜在这里吃了
Then we cooked some dishes here for lunch

0:02:08.550,0:02:10.550
然后吃完饭下午又接着干
Then we continue working after lunch

0:02:10.590,0:02:12.750
然后这一台的话暂时还没有用
This one hasn’t been put into use yet

0:02:13.000,0:02:14.480
这些也是全新的
All those are brand new

0:02:14.480,0:02:16.652
然后这边还有一个六眼灶
And here is a cooking station with six stoves

0:02:17.140,0:02:19.060
就跟我那边差不多吧
It’s similar to the one I used before

0:02:19.060,0:02:22.860
六眼灶买来就是拍一些比较
This six stoves station is for some dishes

0:02:23.080,0:02:26.499
更加家常的做一些煲仔呀煲汤之类的就在这边做
Some homestyle dishes like clay pot dishes (Baozai) and soups will be cooked here

0:02:27.650,0:02:29.690
 现在整体做了一天
Now everything has been put into operation for a day

0:02:29.690,0:02:32.050
昨天拍了一期感觉这个
We shot a video yesterday

0:02:32.450,0:02:35.027
这边特别湿啊特别回潮
I feel that it’s really wet and moist around here

0:02:35.174,0:02:36.490
蚊子特别多
A lot of mosquitoes

0:02:36.725,0:02:38.145
其他都还好
Everything else has been fine

0:02:38.330,0:02:40.050
然后这里空间也够高
And the space is tall enough

0:02:40.050,0:02:40.770
然后
And

0:02:41.020,0:02:42.520
布局也比较好
Space is well distributed

0:02:42.834,0:02:46.240
就感觉做起来更加得心应手吧
I feel working with greater facility 

0:02:46.438,0:02:48.200
嗯 昨天拍了第一期
En, we shot the first video yesterday

0:02:48.400,0:02:49.957
虽然说拍得很辛苦
Although the shotting wasn’t easy

0:02:50.400,0:02:54.244
扛着个电影机还有那三角架加起来肯定有30多斤
Carrying the cinema camera and that tripod, they must add up to 30 jin (15kg)

0:02:54.360,0:02:55.357
扛着跑来跑去的
Running around with that

0:02:55.357,0:02:56.432
然后这些灯啊
And all these lights

0:02:56.432,0:02:58.560
第一天拍遇到了不少麻烦
It wasn’t easy on the first day of shotting

0:02:58.780,0:03:00.420
不过这些都是小问题
But these are all small problems

0:03:00.420,0:03:02.300
特别容易就克服了
Super easy to overcome 

0:03:02.520,0:03:03.730
小小的问题
Small problems

0:03:03.910,0:03:04.840
难不倒我们
Won’t beat us

0:03:05.340,0:03:06.870
然后这边
And here

0:03:07.360,0:03:08.200
明天吧
Tomorrow

0:03:08.200,0:03:10.960
明天我们的视频做菜的视频就会更新
Our cooking tutorial videos will be uploaded tomorrow

0:03:11.180,0:03:12.960
但是第一期我们没有做菜
But we didn’t cook dishes for the first video

0:03:13.140,0:03:15.100
第一期用冰糖
We used white ice sugar

0:03:15.100,0:03:16.420
用糖拍了一期
for that video

0:03:16.579,0:03:18.940
你们可以先猜一下我们拍的是什么
You can guess first what did we shot 

0:03:19.260,0:03:20.220
呃 好了
En, Ok

0:03:20.260,0:03:21.420
本期视频就到这里
It’s all for this video

0:03:21.420,0:03:27.464
以后的话会在这里产出更多质量更高的内容
We will continue to produce more content with higher quality here

0:03:27.900,0:03:29.395
就到这里 拜拜
It’s all, Bye.
