### ISSUE TITLE
[老饭骨]三瓜炖排骨 - https://youtu.be/v3nZmhE-zbQ

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1255]
**视频链接** https://youtu.be/v3nZmhE-zbQ

发布日期北京时间7月8日晚上10点

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【國宴大師•三瓜燉排骨】究竟哪三瓜？湯鮮味清、肉香骨爛，一招教你變廢為寶，這三瓜絕了！|老飯骨

简介
小友們好，今天咱二伯要給大傢伙兒露一手了！三瓜燉排骨，究竟是哪三種瓜，小友們猜得到嗎？這樣燉出來的排骨肉爛、湯鮮，配上三瓜的清香，絕了！
ps.本期節目最後放出精彩幕後花絮，絕對不容錯過哦！

字幕
1
00:00:00,000 --> 00:00:01,520
别人不用了的西瓜皮

2
00:00:01,520 --> 00:00:03,200
然后冬瓜 凉瓜

3
00:00:03,200 --> 00:00:04,760
跟肉一搭 绝搭

4
00:00:04,760 --> 00:00:08,440

5
00:00:08,440 --> 00:00:10,480
大爷您看排骨 

6
00:00:10,480 --> 00:00:14,400
这么点儿啊 够了大爷 不够吃

7
00:00:14,400 --> 00:00:20,000
别人不用的西瓜皮 冬瓜 凉瓜三瓜

8
00:00:20,000 --> 00:00:22,760
这里还一块鸡呢 我借点鲜味

9
00:00:22,760 --> 00:00:23,520
还有一块鸡腿

10
00:00:23,520 --> 00:00:25,680
还有两个白蔻 借点味

11
00:00:25,680 --> 00:00:28,200

12
00:00:28,800 --> 00:00:30,400
两截葱 姜

13
00:00:30,400 --> 00:00:33,040
我今天是看着二伯做饭最猛的一次

14
00:00:33,040 --> 00:00:35,160
乐什么 你别乐啊

15
00:00:35,160 --> 00:00:36,560
我夸你两句你就乐啊

16
00:00:36,560 --> 00:00:38,760
然后再搁两块橘子皮

17
00:00:38,760 --> 00:00:42,600
你看粤菜 你看人家煲冬瓜汤

18
00:00:42,600 --> 00:00:45,280
咱们北方家庭里边都去皮

19
00:00:45,280 --> 00:00:47,600
到粤菜连瓤儿都不去

20
00:00:47,600 --> 00:00:49,280
然后还带着冬瓜皮

21
00:00:49,280 --> 00:00:51,200
这瓤咱都留着煲水用

22
00:00:51,200 --> 00:00:53,280

23
00:00:53,280 --> 00:00:57,200
这凉瓜是两头发圆

24
00:00:57,200 --> 00:01:02,240
这苦瓜北方都是两头尖 长度也不算很长

25
00:01:02,240 --> 00:01:05,160
北方苦瓜比较苦 味儿重

26
00:01:05,160 --> 00:01:06,760
小魏 再搁点黄酒

27
00:01:06,760 --> 00:01:08,680

28
00:01:08,680 --> 00:01:09,360
去腥

29
00:01:09,360 --> 00:01:12,680
拿勺打打沫子

30
00:01:12,680 --> 00:01:15,240
排骨也好了

31
00:01:15,240 --> 00:01:17,680
把这水给它倒了

32
00:01:17,680 --> 00:01:18,640
搁点水

33
00:01:18,640 --> 00:01:20,680
大爷为什么要让它洗干净了

34
00:01:20,680 --> 00:01:22,880
这意思说这汤不能浑浊

35
00:01:22,880 --> 00:01:25,520
好 干净了

36
00:01:25,520 --> 00:01:27,440
咱就搁这里头

37
00:01:27,440 --> 00:01:31,680
少搁点姜 陈皮来一点 葱 

38
00:01:35,680 --> 00:01:40,280
放胡椒粉 盐后搁 

39
00:01:40,280 --> 00:01:42,280
少搁少搁 一会辣了 辣不了

40
00:01:42,280 --> 00:01:44,160
黄酒

41
00:01:46,720 --> 00:01:49,360
这瓤不用扔 把这水煲一下

42
00:01:49,360 --> 00:01:51,280
这就是喝汤 煲十分钟

43
00:01:51,280 --> 00:01:55,040
水开了师父 上高压锅

44
00:01:55,040 --> 00:01:55,640

45
00:02:00,560 --> 00:02:02,720
地道啊 关火

46
00:02:02,720 --> 00:02:04,960
来 二十分钟

47
00:02:04,960 --> 00:02:07,040

48
00:02:07,040 --> 00:02:10,120
下一步怎么着 调一个吃排骨的汁

49
00:02:10,120 --> 00:02:12,440
香葱 香菜 小米辣

50
00:02:12,440 --> 00:02:14,280
水开了师父 我给倒进去了

51
00:02:14,280 --> 00:02:20,640
去一下瓜的苦味 三瓜下锅焯一下

52
00:02:20,640 --> 00:02:23,840
切点小葱和香菜 咱们调一个汁

53
00:02:27,960 --> 00:02:29,320
焯完了迅速过凉

54
00:02:29,600 --> 00:02:29,720

55
00:02:30,560 --> 00:02:32,040
大爷您闻这清香味

56
00:02:32,040 --> 00:02:34,600
各种瓜的味混合在一起

57
00:02:34,600 --> 00:02:37,560
三瓜为一体 变废为宝了

58
00:02:38,840 --> 00:02:39,840
弄点豉油 

59
00:02:39,840 --> 00:02:42,520
倒点葱油 这葱油非常香 

60
00:02:42,520 --> 00:02:43,920
我就省的煸葱了

61
00:02:43,920 --> 00:02:45,600

62
00:02:45,600 --> 00:02:46,960
太香了

63
00:02:46,960 --> 00:02:50,040
这（蒸鱼豉油）往里一倒一呲就行了

64
00:02:53,760 --> 00:02:57,080
咱就等着排骨出锅了 豉油汁

65
00:02:57,080 --> 00:03:00,120
时间到了  手闪开师父

66
00:03:00,120 --> 00:03:03,320
大爷您看 清清凉凉的

67
00:03:03,320 --> 00:03:07,280
先把这排骨捞出来  正好

68
00:03:07,280 --> 00:03:09,880
高压锅出来的汤是清的

69
00:03:09,880 --> 00:03:13,520
因为它不是使劲咕嘟 没有大火翻腾

70
00:03:13,520 --> 00:03:15,000
大爷咱把这加进去 三瓜搁上

71
00:03:15,000 --> 00:03:16,600

72
00:03:16,600 --> 00:03:17,920
调个味 盐

73
00:03:17,920 --> 00:03:18,760

74
00:03:19,640 --> 00:03:22,120
压上 再压五分钟

75
00:03:22,120 --> 00:03:22,840

76
00:03:22,840 --> 00:03:24,920
出锅了 您这三瓜

77
00:03:25,960 --> 00:03:28,320
大爷给出盘呢

78
00:03:28,320 --> 00:03:29,480
加汤

79
00:03:31,120 --> 00:03:32,720
来俩枸杞 好了

80
00:03:32,720 --> 00:03:34,720
大爷 您先蘸这吃大爷

81
00:03:34,720 --> 00:03:36,480

82
00:03:36,480 --> 00:03:37,080
大爷怎么样

83
00:03:37,560 --> 00:03:38,640

84
00:03:38,640 --> 00:03:40,040
鲜

85
00:03:40,040 --> 00:03:42,440
蘸汁和不蘸汁截然不同

86
00:03:42,440 --> 00:03:44,800

87
00:03:44,800 --> 00:03:47,720
这排骨一点腥味都没有 肉香骨烂

88
00:03:47,720 --> 00:03:50,640
西瓜皮 说实话这西瓜 

89
00:03:50,640 --> 00:03:53,160
二伯应该去皮

90
00:03:53,160 --> 00:03:53,200

91
00:03:53,200 --> 00:03:55,280
瓜皮要厚点大爷说了

92
00:03:55,280 --> 00:03:56,840
这可以把皮削下去

93
00:03:56,840 --> 00:03:59,440
因为今天这西瓜太薄了

94
00:03:59,440 --> 00:04:01,560
最后一个您再喝碗汤

96
00:04:14,560 --> 00:04:15,360
好了 继续啊

97
00:04:16,600 --> 00:04:19,120
大家都在吃面

98
00:04:19,120 --> 00:04:19,720
刚做好的面

99
00:04:19,720 --> 00:04:20,600
你知道这什么面么

100
00:04:21,560 --> 00:04:22,240
你说说

101
00:04:23,440 --> 00:04:24,600
你照照表

102
00:04:24,600 --> 00:04:25,520
十一点二十了

103
00:04:25,520 --> 00:04:26,920
还在工作

104
00:04:26,920 --> 00:04:27,960
夜间十一点二十了

105
00:04:28,560 --> 00:04:30,000
再照照外边的黑天

106
00:04:30,320 --> 00:04:32,520
窗外十一点的天空

107
00:04:33,880 --> 00:04:35,440
为什么您不吃面吃西瓜

108
00:04:36,400 --> 00:04:38,280
我这老做做的我这嘴都木了

109
00:04:38,960 --> 00:04:40,080
做一天面了

110
00:04:52,440 --> 00:04:54,440
大爷 您别在吃了

111
00:04:54,440 --> 00:04:55,880
越吃越胖 那肚子

112
00:04:57,920 --> 00:04:59,440
一会不还有那秘制鸡么

113
00:04:59,440 --> 00:05:01,360
秘制鸡最后真吃不动了

114
00:05:02,480 --> 00:05:04,120
但总要尝一口

115
00:05:05,520 --> 00:05:07,080
那秘制鸡还没蒸呢吧

116
00:05:08,680 --> 00:05:09,720
这十二点了

117
00:05:10,760 --> 00:05:12,360
让老四真说对了

118
00:05:13,080 --> 00:05:13,800

**Comment by Koi111** [comment]
认领

**Comment by Koi111** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【國宴大師•三瓜燉排骨】究竟哪三瓜？湯鮮味清、肉香骨爛，一招教你變廢為寶，這三瓜絕了！|老飯骨
State Banquet Master Chefs’Stewed Pork Ribs with 3 Melons, savory soup with tender meat 

简介
小友們好，今天咱二伯要給大傢伙兒露一手了！
Hey friends! It’s Er Bai’s time to teach us today.
三瓜燉排骨，究竟是哪三種瓜，小友們猜得到嗎？
Stewed pork ribs with 3 melons, can you guys guess which 3 of the melons are?
這樣燉出來的排骨肉爛、湯鮮，配上三瓜的清香，絕了！
Using this way to stew pork ribs creates tender meat and clear soup with umami flavour, complement with the light fragrance of the melons, awesome! 
ps.本期節目最後放出精彩幕後花絮，絕對不容錯過哦！
Ps, There are some interesting behind the scenes at the end of this video, don’t miss it!

字幕
1
00:00:00,000 --> 00:00:01,520
别人不用了的西瓜皮
Watermelon rinds that are often left out

2
00:00:01,520 --> 00:00:03,200
然后冬瓜 凉瓜
and then winter melon, bitter melon

3
00:00:03,200 --> 00:00:04,760
跟肉一搭 绝搭
complementing the meat. Perfect!

4
00:00:04,760 --> 00:00:08,440

5
00:00:08,440 --> 00:00:10,480
大爷您看排骨 
Da Ye, please look at these pork ribs

6
00:00:10,480 --> 00:00:14,400
这么点儿啊 够了大爷 不够吃
Only this tiny bit? It’s enough Da Ye. Not enough

7
00:00:14,400 --> 00:00:20,000
别人不用的西瓜皮 冬瓜 凉瓜三瓜
Watermelon rinds that are not commonly used, winter melon and bitter melon, 3 kinds of melons

8
00:00:20,000 --> 00:00:22,760
这里还一块鸡呢 我借点鲜味
Here’s a piece of chicken meat too, I need it’s umami flavour

9
00:00:22,760 --> 00:00:23,520
还有一块鸡腿
And a piece of drumstick

10
00:00:23,520 --> 00:00:25,680
还有两个白蔻 借点味
Two more white cardamoms, produce more aroma

11
00:00:25,680 --> 00:00:28,200

12
00:00:28,800 --> 00:00:30,400
两截葱 姜
Two pieces of spring onion and ginger

13
00:00:30,400 --> 00:00:33,040
我今天是看着二伯做饭最猛的一次
I can see that Er Bai is putting a lot of effort today

14
00:00:33,040 --> 00:00:35,160
乐什么 你别乐啊
Why are you smiling, don’t be so happy

15
00:00:35,160 --> 00:00:36,560
我夸你两句你就乐啊
You are this happy even I just complimented you with a few sentences

16
00:00:36,560 --> 00:00:38,760
然后再搁两块橘子皮
Add two pieces of mandarin peel

17
00:00:38,760 --> 00:00:42,600
你看粤菜 你看人家煲冬瓜汤
In Cantonese cuisine, for winter melon soup,

18
00:00:42,600 --> 00:00:45,280
咱们北方家庭里边都去皮
Us as northern China families would remove its rinds

19
00:00:45,280 --> 00:00:47,600
到粤菜连瓤儿都不去
They would not even remove the flesh and the seeds

20
00:00:47,600 --> 00:00:49,280
然后还带着冬瓜皮
And they left the rinds on it too

21
00:00:49,280 --> 00:00:51,200
这瓤咱都留着煲水用
Well we keep the flesh to use during boiling the water

22
00:00:51,200 --> 00:00:53,280

23
00:00:53,280 --> 00:00:57,200
这凉瓜是两头发圆
This bitter melon has rounded ends

24
00:00:57,200 --> 00:01:02,240
这苦瓜北方都是两头尖 长度也不算很长
Bitter melons in Northern China have more pointy ends, and they’re not really long

25
00:01:02,240 --> 00:01:05,160
北方苦瓜比较苦 味儿重
Bitter melons in Northern China are more bitter with a more intense flavour

26
00:01:05,160 --> 00:01:06,760
小魏 再搁点黄酒
Xiao Wei, please add some Huangjiu rice wine in it

27
00:01:06,760 --> 00:01:08,680

28
00:01:08,680 --> 00:01:09,360
去腥
Remove unpleasant smell
29
00:01:09,360 --> 00:01:12,680
拿勺打打沫子
Remove the scum with a ladle 

30
00:01:12,680 --> 00:01:15,240
排骨也好了
The pork ribs are done

31
00:01:15,240 --> 00:01:17,680
把这水给它倒了
Pour the water away

32
00:01:17,680 --> 00:01:18,640
搁点水
Add some water

33
00:01:18,640 --> 00:01:20,680
大爷为什么要让它洗干净了
Da Ye, why do we have to rinse it?

34
00:01:20,680 --> 00:01:22,880
这意思说这汤不能浑浊
So that the soup is not cloudy

35
00:01:22,880 --> 00:01:25,520
好 干净了
Ok, it's clean now

36
00:01:25,520 --> 00:01:27,440
咱就搁这里头
We'll put it there

37
00:01:27,440 --> 00:01:31,680
少搁点姜 陈皮来一点 葱 
Put a little bit of ginger, some mandarin peel and spring onion

38
00:01:35,680 --> 00:01:40,280
放胡椒粉 盐后搁 
Add grounded white pepper then add the salt

39
00:01:40,280 --> 00:01:42,280
少搁少搁 一会辣了 辣不了
Just put a tiny bit, or else it would be too spicy

40
00:01:42,280 --> 00:01:44,160
黄酒
Huangjiu rice wine

41
00:01:46,720 --> 00:01:49,360
这瓤不用扔 把这水煲一下
Don't throw away the flesh, boil the water together with it

42
00:01:49,360 --> 00:01:51,280
这就是喝汤 煲十分钟
This is the soup we’ll be drinking, cook it for 10 minutes

43
00:01:51,280 --> 00:01:55,040
水开了师父 上高压锅
The water is boiled, master. Pour it into high pressure cooker

44
00:01:55,040 --> 00:01:55,640

45
00:02:00,560 --> 00:02:02,720
地道啊 关火
It's authentic, turn off the flame

46
00:02:02,720 --> 00:02:04,960
来 二十分钟
Here it goes, 20 minutes

47
00:02:04,960 --> 00:02:07,040

48
00:02:07,040 --> 00:02:10,120
下一步怎么着 调一个吃排骨的汁
What's the next step? Make a sauce for the pork ribs

49
00:02:10,120 --> 00:02:12,440
香葱 香菜 小米辣
Scallions, cilantro and "Xiaomila" chili pepper

50
00:02:12,440 --> 00:02:14,280
水开了师父 我给倒进去了
The water is boiled now master, I will add the melons into the wok

去一下瓜的苦味 三瓜下锅焯一下
Remove the bitterness of the melons by blanching them for a while

52
00:02:20,640 --> 00:02:23,840
切点小葱和香菜 咱们调一个汁
Cut some scallions and cilantro to make a sauce

53
00:02:27,960 --> 00:02:29,320
焯完了迅速过凉
Cool them off immediately after blanching them

54
00:02:29,600 --> 00:02:29,720

55
00:02:30,560 --> 00:02:32,040
大爷您闻这清香味
Da Ye, can you smell the fragrance of it

56
00:02:32,040 --> 00:02:34,600
各种瓜的味混合在一起
The fragrance of the melons are well mixed

57
00:02:34,600 --> 00:02:37,560
三瓜为一体 变废为宝了
They complement each other well, turning waste into treasure

58
00:02:38,840 --> 00:02:39,840
弄点豉油 
Let's make some seasoned soy sauce

59
00:02:39,840 --> 00:02:42,520
倒点葱油 这葱油非常香 
Pour some scallion oil, it is very fragrant

60
00:02:42,520 --> 00:02:43,920
我就省的煸葱了
I'll skip the step of frying the scallions

61
00:02:43,920 --> 00:02:45,600

62
00:02:45,600 --> 00:02:46,960
太香了
That's so aromatic

63
00:02:46,960 --> 00:02:50,040
这（蒸鱼豉油）往里一倒一呲就行了
Heat up the seasoned soy sauce for seafood and pour it in, that's it

64
00:02:53,760 --> 00:02:57,080
咱就等着排骨出锅了 豉油汁
We'll just wait for the pork ribs to be cooked

65
00:02:57,080 --> 00:03:00,120
时间到了  手闪开师父
It's time now, please be careful with your hands master

66
00:03:00,120 --> 00:03:03,320
大爷您看 清清凉凉的
Da Ye, please look at this, the soup is very clear

67
00:03:03,320 --> 00:03:07,280
先把这排骨捞出来  正好
Take the pork ribs out first, they have been cooked until just right

68
00:03:07,280 --> 00:03:09,880
高压锅出来的汤是清的
Soups cooked with high pressure cooker is very clear

69
00:03:09,880 --> 00:03:13,520
因为它不是使劲咕嘟 没有大火翻腾
Because of the lower temperature, it doesn’t bubble vigorously

70
00:03:13,520 --> 00:03:15,000
大爷咱把这加进去 三瓜搁上
Let’s add the melons in, three of them

71
00:03:15,000 --> 00:03:16,600

72
00:03:16,600 --> 00:03:17,920
调个味 盐
Season it, salt

73
00:03:17,920 --> 00:03:18,760

74
00:03:19,640 --> 00:03:22,120
压上 再压五分钟
Cook it for more 5 minutes

75
00:03:22,120 --> 00:03:22,840

76
00:03:22,840 --> 00:03:24,920
出锅了 您这三瓜
It can be served now, these melons

77
00:03:25,960 --> 00:03:28,320
大爷给出盘呢
Da Ye is plating the dish

78
00:03:28,320 --> 00:03:29,480
加汤
Add the soup

79
00:03:31,120 --> 00:03:32,720
来俩枸杞 好了
Some goji berries, it's done

80
00:03:32,720 --> 00:03:34,720
大爷 您先蘸这吃大爷
Da Ye, please try it with the dipping sauce first

81
00:03:34,720 --> 00:03:36,480

82
00:03:36,480 --> 00:03:37,080
大爷怎么样
How is it, Da Ye?

83
00:03:37,560 --> 00:03:38,640

84
00:03:38,640 --> 00:03:40,040
鲜
Strong umami flavour

85
00:03:40,040 --> 00:03:42,440
蘸汁和不蘸汁截然不同
It's totally different with or without the dipping sauce

86
00:03:42,440 --> 00:03:44,800

87
00:03:44,800 --> 00:03:47,720
这排骨一点腥味都没有 肉香骨烂
The pork ribs don't have any gamey taste, aromatic meat and soft bone

88
00:03:47,720 --> 00:03:50,640
西瓜皮 说实话这西瓜
To be honest, about the watermelon rinds

89
00:03:50,640 --> 00:03:53,160
二伯应该去皮
Er Bai should’ve remove the outer skin

90
00:03:53,160 --> 00:03:53,200

91
00:03:53,200 --> 00:03:55,280
瓜皮要厚点大爷说了
Da Ye said that if the rinds are thicker,

92
00:03:55,280 --> 00:03:56,840
这可以把皮削下去
We can just peel off the outer skin

93
00:03:56,840 --> 00:03:59,440
因为今天这西瓜太薄了
Because the watermelon rinds are too thin

94
00:03:59,440 --> 00:04:01,560
最后一个您再喝碗汤
Lastly, please drink a bowl of soup

96
00:04:14,560 --> 00:04:15,360
好了 继续啊
Ok, let's continue

97
00:04:16,600 --> 00:04:19,120
大家都在吃面
Everyone is having noodles

98
00:04:19,120 --> 00:04:19,720
刚做好的面
They just made this

99
00:04:19,720 --> 00:04:20,600
你知道这什么面么
Do you know what noodles is this

100
00:04:21,560 --> 00:04:22,240
你说说
Say it out

101
00:04:23,440 --> 00:04:24,600
你照照表
You can film the clock

102
00:04:24,600 --> 00:04:25,520
十一点二十了
It's 11.20 p.m. already

103
00:04:25,520 --> 00:04:26,920
还在工作
Still working

104
00:04:26,920 --> 00:04:27,960
夜间十一点二十了
It's late night

105
00:04:28,560 --> 00:04:30,000
再照照外边的黑天
Film the dark sky outside too

106
00:04:30,320 --> 00:04:32,520
窗外十一点的天空
The sky of 11 o'clock outside the window

107
00:04:33,880 --> 00:04:35,440
为什么您不吃面吃西瓜
Why don't you eat the noodles but the watermelon

108
00:04:36,400 --> 00:04:38,280
我这老做做的我这嘴都木了
I’m always cooking, I don’t have the appetite already

109
00:04:38,960 --> 00:04:40,080
做一天面了
We’ve been making noodles for all day long

110
00:04:52,440 --> 00:04:54,440
大爷 您别在吃了
Da Ye, please don’t eat anymore

111
00:04:54,440 --> 00:04:55,880
越吃越胖 那肚子
Your tummy is getting bigger and bigger

112
00:04:57,920 --> 00:04:59,440
一会不还有那秘制鸡么
We still have the last dish yet to be served

113
00:04:59,440 --> 00:05:01,360
秘制鸡最后真吃不动了
I don’t think I can eat much of that, the special made chicken

114
00:05:02,480 --> 00:05:04,120
但总要尝一口
Nontheless, you still have to try a little bit of it

115
00:05:05,520 --> 00:05:07,080
那秘制鸡还没蒸呢吧
The special made chicken is not done yet

116
00:05:08,680 --> 00:05:09,720
这十二点了
It’s 12 o’clock now

117
00:05:10,760 --> 00:05:12,360
让老四真说对了
Si Di is right
