### ISSUE TITLE
【美食作家王刚】糖的质变- https://youtu.be/dl1S_BeUTEM

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1256]
**视频链接**：https://youtu.be/dl1S_BeUTEM

视频时长5:42，预计发布时间为北京时间7月11日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“糖的质变”，糖色，糖葫芦，挂霜，拔丝，糖衣等专业做法，糖的最全面科普！

简介
硬核后厨正式回归！第一期拍得还不够全面，由于换了新的设备和后期流程，遇到了不少挑战，不过世上无难事，只怕有心人，相信会越来越好的！希望大家喜欢新的后厨和画面，我会继续努力给大家呈现更多优秀的内容💪💪💪这期还尝试了软字幕，如果需要字幕可以使用YouTube的CC功能，不知道这样会不会给大家提供更好的观看体验。

本期内容主题为“糖”，让大家更加了解不同种类的糖和炒糖的整个流程。其实糖色，拔丝，挂霜，糖衣等等这些看似高深的后厨专业术语，在了解其制作过程和原理之后就很简单了，研习此视频包你学会，要是还不会就再多看几遍😃

字幕
0:00:00.320,0:00:01.088
哈喽 大家好我是王刚

0:00:01.088,0:00:02.758
本期视频我跟大家分享

0:00:03.151,0:00:04.804
糖色的过程

0:00:05.440,0:00:08.110
首先我们来了解有色糖和无色糖

0:00:08.580,0:00:09.640
有色糖大概有

0:00:09.742,0:00:10.638
片糖

0:00:10.827,0:00:11.870
红糖

0:00:12.020,0:00:13.130
土冰糖

0:00:13.220,0:00:14.347
无色糖大概有

0:00:14.347,0:00:15.304
白砂糖

0:00:15.470,0:00:16.380
精炼冰糖

0:00:16.945,0:00:19.658
其中冰糖又分精炼冰糖和土冰糖

0:00:20.380,0:00:23.420
精炼冰糖的纯度高更透明且杂质非常少

0:00:23.786,0:00:26.878
因为颜色纯净下锅融化得也更快更好

0:00:27.060,0:00:28.700
所以比较适合炒糖色

0:00:29.140,0:00:32.590
土冰糖偏淡黄色略带蔗糖的原始甜香味

0:00:32.860,0:00:34.500
它的优点是精炼次数少

0:00:34.660,0:00:36.100
营养成分保留得更多

0:00:36.100,0:00:36.860
更全面

0:00:37.326,0:00:39.101
但同时杂质也相对更多

0:00:39.101,0:00:40.540
土冰糖比较适合熬粥

0:00:40.637,0:00:41.446
泡茶

0:00:41.562,0:00:42.397
泡开水

0:00:42.825,0:00:45.442
片糖的优点是方便储存不易回潮

0:00:45.937,0:00:46.940
相对比较硬

0:00:46.940,0:00:49.380
不容易化开适合广式糖水

0:00:49.895,0:00:51.431
红糖的质量比较松软

0:00:51.588,0:00:53.760
也是所有糖类中最容易吸收之一

0:00:54.062,0:00:56.165
其特点是不容易保存容易回潮

0:00:56.756,0:00:59.200
白砂糖炒制的糖色色泽不如冰糖红亮

0:00:59.296,0:01:01.480
最常见的作用就是烹饪时候的调味

0:01:01.760,0:01:03.948
在这里不建议大家用砂糖炒制糖色

0:01:04.160,0:01:05.442
下一步开始制作

0:01:05.840,0:01:08.337
首先我们选择适量的精炼冰糖敲碎备用

0:01:08.610,0:01:11.703
这一步的目的是让冰糖在炒制的时候更快的溶解

0:01:18.763,0:01:20.761
然后加入和冰糖等量的清水

0:01:20.980,0:01:23.980
新手操作建议糖和水的比例增加到1:1.2

0:01:24.320,0:01:25.890
再加入适量的植物油

0:01:25.960,0:01:28.613
加植物油可以提升炒糖色的时候的温度

0:01:28.760,0:01:29.893
下一步开始操作

0:01:30.171,0:01:32.760
首先我们开中小火把调好的糖水下锅

0:01:32.921,0:01:36.232
糖水下锅之后烧开转小火边搅边观察糖的变化

0:01:44.860,0:01:47.530
糖浆充分融化之后会起比较大的气泡

0:01:48.040,0:01:49.950
然后继续熬至水分蒸发

0:01:53.940,0:01:55.642
水分蒸发之后气泡变小

0:01:55.796,0:01:57.450
即可以制作挂霜的菜品

0:02:00.760,0:02:02.988
继续熬制糖浆变成香油色的时候

0:02:03.140,0:02:05.180
也就是糖浆逐渐变成淡黄色之后

0:02:05.180,0:02:07.180
又马上可以进入拔丝菜品的状态

0:02:13.940,0:02:15.330
好 我们继续往下制作

0:02:15.740,0:02:17.670
再接着糖浆的黄色会加深

0:02:17.740,0:02:18.660
这个时候的糖

0:02:18.660,0:02:20.300
非常适合做冰糖葫芦

0:02:20.300,0:02:21.370
冰糖李子等等

0:02:22.320,0:02:23.040
继续开火

0:02:23.080,0:02:25.480
略等十秒钟之后会变成初级枣红色

0:02:25.840,0:02:27.059
如果此时加入开水的话

0:02:27.059,0:02:28.720
就是略带甜味的糖色

0:02:28.880,0:02:30.490
行业之中称为嫩汁

0:02:30.700,0:02:32.530
初级变色之后将锅离火

0:02:32.840,0:02:35.070
利用余温将嫩汁顶呈深枣色

0:02:48.460,0:02:51.230
深枣色之后再加入糖浆自身两倍的开水

0:02:51.620,0:02:53.270
同学们切记不能用冷水

0:02:53.540,0:02:56.070
冷水容易让高温的糖浆炸裂伤人

0:02:56.300,0:02:59.114
也容易让糖色的颜色不融合导致分层

0:02:59.340,0:03:01.830
加入开水之后也要继续熬煮一分钟

0:03:11.665,0:03:13.240
最终的糖色无味

0:03:13.240,0:03:14.160
颜色红亮

0:03:14.480,0:03:16.930
非常适合添加到卤味和红烧当中

0:03:33.960,0:03:37.270
初次制作卤味的时候糖色需要慢慢的添加

0:03:37.620,0:03:39.450
直到颜色适合之后即可

0:03:41.940,0:03:44.490
然后再加入配制好的卤料包和调味料

0:03:52.460,0:03:53.950
用糖色调色的卤水

0:03:54.040,0:03:55.053
需要注意的是

0:03:55.309,0:03:58.880
卤制的成品在出锅之后需要刷上一层油保色

0:03:59.280,0:04:02.207
否则糖色很容易经过时间的氧化变黑

0:04:09.105,0:04:10.577
下面开始技术总结

0:04:10.577,0:04:12.040
糖水过程的质变

0:04:12.500,0:04:14.340
第一水分蒸发之后

0:04:14.380,0:04:15.900
气泡变小是挂霜

0:04:16.165,0:04:19.080
同学们挂霜也就是水分蒸发完的时候关火

0:04:19.440,0:04:21.270
下入原材料翻炒至冷却

0:04:21.480,0:04:22.970
此做法称为挂霜

0:04:23.380,0:04:24.430
同学们切记

0:04:24.500,0:04:26.479
一定要关火炒到糖浆冷却

0:04:26.593,0:04:27.770
凝固硬化

0:04:39.752,0:04:42.083
第二糖浆变黄是拔丝

0:04:42.306,0:04:45.139
拔丝原料下锅之前必须再加入少许的底油

0:04:45.560,0:04:48.089
这一步的目的是让糖丝能够拉得更长

0:04:48.500,0:04:51.198
成菜冷却之后且不容易粘连成一坨

0:05:20.460,0:05:21.230
第三

0:05:21.280,0:05:23.520
糖浆颜色变深之后可以挂糖制作

0:05:23.520,0:05:24.440
琥珀核桃

0:05:24.800,0:05:25.790
冰糖葫芦

0:05:26.040,0:05:27.250
冰糖李子等等

0:05:27.420,0:05:28.407
同学们切记

0:05:28.534,0:05:30.900
糖浆必须有热度才能挂得更薄

0:05:31.320,0:05:33.430
糖浆温度下降的时候则越厚

0:05:34.580,0:05:36.510
糖色的质变技术总结完毕


```

**Comment by immoonancient** [comment]
微信群的 Bowen 请前来认领

**Comment by BOWEN0305772** [comment]
认领

**Comment by BOWEN0305772** [comment]
Chief Wang teaches you: The Qualitative Change of Sugar 
 
Abstract
Chief Wang has returned! The first video was not full-scaled, and due to the replacement of the new facilities, updating the back process, we met few challenges. However, no problems can’t be soved once we tried our best. There is no dounbt that it would be better! Hoping everyone would enjoy the new kitchen, and I would continue to upload more and better videos. I tried soft subtile in this video so that everyone could use the CC that is embeded in the YouTube for their own needs.
 
Sugar would be this video’s topic. I want to introduce to eveyone more about the various kinds of sugar and the overall process of cooking with sugar. In fact, you will find that advanced cooking techbiques, including caramelized sugar, hot candied, guashuang, and sugar coating, are not as hard as they are sounded. By watching this video, I promises that you will learned these advanced techniques. If there are any problems, just watch it agian, the problem will be solved.
 
Subtitles
0:00:00.320,0:00:01.088
哈喽 大家好我是王刚
Hello everone, I am Wang Gang
 
0:00:01.088,0:00:02.758
本期视频我跟大家分享
In this video, I am going to share the process of
 
0:00:03.151,0:00:04.804
糖色的过程
Making caramelized sugar.
 
0:00:05.440,0:00:08.110
首先我们来了解有色糖和无色糖
Firstly, let’s have a look at colored sugars and colourless sugars.
 
0:00:08.580,0:00:09.640
有色糖大概有
Colored sugards include
 
0:00:09.742,0:00:10.638
片糖
Sliced cane sugar
0:00:10.827,0:00:11.870
红糖
Brown sugar
0:00:12.020,0:00:13.130
土冰糖
Matured rock sugar
 
0:00:13.220,0:00:14.347
无色糖大概有
Colourless sugars include
0:00:14.347,0:00:15.304
白砂糖
White granulated sugar
0:00:15.470,0:00:16.380
精炼冰糖
Refined rock sugar
 
0:00:16.945,0:00:19.658
其中冰糖又分精炼冰糖和土冰糖
Refined rock sugar and matured rock sugar are branched of rock sugar.
 
0:00:20.380,0:00:23.420
精炼冰糖的纯度高更透明且杂质非常少
Refined rock sugar has higher purity, it is transparent and has very little impurities.
 
0:00:23.786,0:00:26.878
因为颜色纯净下锅融化得也更快更好
Its purity allows it to melt faster while cooking,
 
0:00:27.060,0:00:28.700
所以比较适合炒糖色
and therefore, it is a good choice for making caramelized sugar.
 
0:00:29.140,0:00:32.590
土冰糖偏淡黄色略带蔗糖的原始甜香味
Matured rock sugar has pale-yellow appearance, it accompanied with the original flavor of cane sugar
 
0:00:32.860,0:00:34.500
它的优点是精炼次数少
With the advantage of less refinement,
 
0:00:34.660,0:00:36.100
营养成分保留得更多
It maintained more nutrients in either amount
 
0:00:36.100,0:00:36.860
更全面
and kinds.
 
0:00:37.326,0:00:39.101
但同时杂质也相对更多
On contrast, it has more impurities.
 
0:00:39.101,0:00:40.540
土冰糖比较适合熬粥
Matured rock sugar is better to be used when preparing congee,
0:00:40.637,0:00:41.446
泡茶
teas,
0:00:41.562,0:00:42.397
泡开水
hot water.
0:00:42.825,0:00:45.442
片糖的优点是方便储存不易回潮
Sliced cane sugar has the convinience in storage and hard to be damped,
0:00:45.937,0:00:46.940
相对比较硬
It is also more solid,
0:00:46.940,0:00:49.380
不容易化开适合广式糖水
hard to melt, so it’s suitable for making Cantonese sugar water
0:00:49.895,0:00:51.431
红糖的质量比较松软
Brown sugar is more soft, and
0:00:51.588,0:00:53.760
也是所有糖类中最容易吸收之一
It is one of the easiest absorbed sugar
0:00:54.062,0:00:56.165
其特点是不容易保存容易回潮
It is not easy to store and easily get damped
0:00:56.756,0:00:59.200
白砂糖炒制的糖色色泽不如冰糖红亮
Caramelized sugar made from white granulated sugar doesn’t looks as red and light as it made from rock sugar
0:00:59.296,0:01:01.480
最常见的作用就是烹饪时候的调味
While cooking, it is most commonly used as seasoning
0:01:01.760,0:01:03.948
在这里不建议大家用砂糖炒制糖色
Therefore, it is not a good idea to make caramelized sugar from granulated sugar
0:01:04.160,0:01:05.442
下一步开始制作
Then, let’s start
0:01:05.840,0:01:08.337
首先我们选择适量的精炼冰糖敲碎备用
We firstly break suitable amount of refined rock sugar for preparation
0:01:08.610,0:01:11.703
这一步的目的是让冰糖在炒制的时候更快的溶解
This aimed to help melting the sugar while cooking
0:01:18.763,0:01:20.761
然后加入和冰糖等量的清水
Then add water with the same amount as sugar
0:01:20.980,0:01:23.980
新手操作建议糖和水的比例增加到1:1.2
If you are new for this, the sugar to water ratio could be 1:1.2
0:01:24.320,0:01:25.890
再加入适量的植物油
Add proper amount of vegetable oil
0:01:25.960,0:01:28.613
加植物油可以提升炒糖色的时候的温度
Vegetavle oil could rise the temperature while stiring the caramelized sugar
0:01:28.760,0:01:29.893
下一步开始操作
Next, we start to cook
0:01:30.171,0:01:32.760
首先我们开中小火把调好的糖水下锅
Firstly, we turn on the cooking bench at medium level, and pour the sugar water into the pot
0:01:32.921,0:01:36.232
糖水下锅之后烧开转小火边搅边观察糖的变化
After boiled, turn the cooking bench to low level and pay attention to the change in sugar
0:01:44.860,0:01:47.530
糖浆充分融化之后会起比较大的气泡
If sugar melt completely, there would be big bubbles
0:01:48.040,0:01:49.950
然后继续熬至水分蒸发
Then continue cooking until water evaporated
0:01:53.940,0:01:55.642
水分蒸发之后气泡变小
The bubble will be smaller after evaporation
0:01:55.796,0:01:57.450
即可以制作挂霜的菜品
Then it could be used for preparing dishes that need guashuang
0:02:00.760,0:02:02.988
继续熬制糖浆变成香油色的时候
If continue cooking until the syrup has a similar color to sesame oil
0:02:03.140,0:02:05.180
也就是糖浆逐渐变成淡黄色之后
in other word, after syrup gradually changed to pale-yellow,
0:02:05.180,0:02:07.180
又马上可以进入拔丝菜品的状态
It could be used for preparing dishes that need hot candied
0:02:13.940,0:02:15.330
好 我们继续往下制作
Ok, let’s continue.
0:02:15.740,0:02:17.670
再接着糖浆的黄色会加深
The color of syrup will be depper
0:02:17.740,0:02:18.660
这个时候的糖
At this time,
0:02:18.660,0:02:20.300
非常适合做冰糖葫芦
It is best to be used to make bingtanghulu,
0:02:20.300,0:02:21.370
冰糖李子等等
Bingtanglizi, and etc.
0:02:22.320,0:02:23.040
继续开火
Let’s keep cooking
0:02:23.080,0:02:25.480
略等十秒钟之后会变成初级枣红色
It would changed to purplish red after about ten seconds
0:02:25.840,0:02:27.059
如果此时加入开水的话
If we add water at this time
0:02:27.059,0:02:28.720
就是略带甜味的糖色
It is the caramelized sugar that is slightly sweet
0:02:28.880,0:02:30.490
行业之中称为嫩汁
We call it nengzhi
0:02:30.700,0:02:32.530
初级变色之后将锅离火
Taking the pot away from the cooking bench after it change color
0:02:32.840,0:02:35.070
利用余温将嫩汁顶呈深枣色
Utilize the tempeture left and waite the top of nengzhi change to deep-purplish red
0:02:48.460,0:02:51.230
深枣色之后再加入糖浆自身两倍的开水
Then add water as twice amont on volumn as syrup
0:02:51.620,0:02:53.270
同学们切记不能用冷水
Please do not use cold water
 
0:02:53.540,0:02:56.070
冷水容易让高温的糖浆炸裂伤人
Since cold water will cause the syrup crack and possibly hurt people
0:02:56.300,0:02:59.114
也容易让糖色的颜色不融合导致分层
It may also cause the distinct color of caramelized sugar, and lead to hierarchical appearance
0:02:59.340,0:03:01.830
加入开水之后也要继续熬煮一分钟
Waiting one more nimute after adding the water
0:03:11.665,0:03:13.240
最终的糖色无味
The final caramelized sugar is tasteless
0:03:13.240,0:03:14.160
颜色红亮
Has bright red color
0:03:14.480,0:03:16.930
非常适合添加到卤味和红烧当中
And very suitable to be added into master stock
0:03:33.960,0:03:37.270
初次制作卤味的时候糖色需要慢慢的添加
While first time making the master stock, caramelized should be gradually added
0:03:37.620,0:03:39.450
直到颜色适合之后即可
Until the color looks fine
0:03:41.940,0:03:44.490
然后再加入配制好的卤料包和调味料
Then, add premade halogen package and seasoning
0:03:52.460,0:03:53.950
用糖色调色的卤水
Using the master stock that was mixed with caramelized sugar
0:03:54.040,0:03:55.053
需要注意的是
Please notice that
0:03:55.309,0:03:58.880
卤制的成品在出锅之后需要刷上一层油保色
The stewed product should be brushed over with oil
0:03:59.280,0:04:02.207
否则糖色很容易经过时间的氧化变黑
Or caramelized sugar will easily get dark since the oxidation
0:04:09.105,0:04:10.577
下面开始技术总结
Followings are technicial summary
0:04:10.577,0:04:12.040
糖水过程的质变
The process of qualitative change of sugar
0:04:12.500,0:04:14.340
第一水分蒸发之后
Firstly, after evaporation
0:04:14.380,0:04:15.900
气泡变小是挂霜
Small bubbles implies guashuang is available
0:04:16.165,0:04:19.080
同学们挂霜也就是水分蒸发完的时候关火
If performing guashuang, turn off the cooking bench after completely evaporation
0:04:19.440,0:04:21.270
下入原材料翻炒至冷却
Add ingredients and keep stiring until cooled
0:04:21.480,0:04:22.970
此做法称为挂霜
Whis is so called guashuang
0:04:23.380,0:04:24.430
同学们切记
Please remember
0:04:24.500,0:04:26.479
一定要关火炒到糖浆冷却
We must turn off the cooking bench and keep stiring until syrup is cooled,
0:04:26.593,0:04:27.770
凝固硬化
solidated
0:04:39.752,0:04:42.083
第二糖浆变黄是拔丝
Secondly, hot candied is prepared when syrup become yellow
0:04:42.306,0:04:45.139
拔丝原料下锅之前必须再加入少许的底油
Add few oil before adding the food ingredients
0:04:45.560,0:04:48.089
这一步的目的是让糖丝能够拉得更长
This aimmed to make sugar filaments as long as possible
0:04:48.500,0:04:51.198
成菜冷却之后且不容易粘连成一坨
and ingradients won’t glue up
0:05:20.460,0:05:21.230
第三
Thirdly,
0:05:21.280,0:05:23.520
糖浆颜色变深之后可以挂糖制作
After the color of syrup become deeper, it could be used to make sugar coating
0:05:23.520,0:05:24.440
琥珀核桃
Amber walnut
0:05:24.800,0:05:25.790
冰糖葫芦
bingtanghulu
0:05:26.040,0:05:27.250
冰糖李子等等
Bingtanglizi and etc.
0:05:27.420,0:05:28.407
同学们切记
Please remember
0:05:28.534,0:05:30.900
糖浆必须有热度才能挂得更薄
Thinner sugar coating can only be obtained by using hot syrup
0:05:31.320,0:05:33.430
糖浆温度下降的时候则越厚
The coating will be whicker if the temperature of syrup drop
0:05:34.580,0:05:36.510
糖色的质变技术总结完毕
This is the end of qualitative change od sugar technicial summary.
