### ISSUE TITLE
[雪鱼] 玫瑰饼 - https://youtu.be/JVrz1ykbSag

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#1257]
**视频链接**：https://youtu.be/JVrz1ykbSag

# 请翻译以下全部内容

```
字幕
1
00:00:01,680 --> 00:00:05,040
它真的是像一个玫瑰花一样的饼

2
00:00:05,040 --> 00:00:08,360
但是它和云南的鲜花饼不同的是

3
00:00:08,360 --> 00:00:11,680
它的块头真的是特别大个

4
00:00:12,080 --> 00:00:18,400
我不敢举太高 我怕一不小心把玫瑰饼全部打翻

5
00:00:18,520 --> 00:00:22,800
玫瑰花瓣一片片，飘落在眼前

6
00:00:24,200 --> 00:00:28,200
青海·西宁

7
00:00:32,120 --> 00:00:34,080
雪鱼现在在青海西宁

8
00:00:34,080 --> 00:00:37,000
待会呢 我们要去吃的是玫瑰花饼

9
00:00:37,000 --> 00:00:40,520
这个玫瑰花饼和云南的玫瑰花饼 可截然不同

10
00:00:40,520 --> 00:00:42,600
待会看一看 庐山真面目

11
00:00:42,600 --> 00:00:46,680
绝对会刷新你对玫瑰花饼的认知

12
00:00:47,280 --> 00:00:49,280
待会我要去的是一个菜市场

13
00:00:49,280 --> 00:00:51,800
里面有一家专门做玫瑰饼的小店

14
00:00:51,800 --> 00:00:54,320
是这种前店后厨的模式

15
00:00:55,720 --> 00:00:58,640
做好的玫瑰饼呢 会拿到前面切完再卖

16
00:00:58,640 --> 00:01:01,640
这么大的一个 切完 也只能切成八份

17
00:01:01,640 --> 00:01:06,440
如果你前面站着八个人 那你一定会等下一个玫瑰饼

18
00:01:16,480 --> 00:01:19,840
55元3角 给55元吧

19
00:01:30,680 --> 00:01:34,280
回去先不要系 晾凉了再系上

20
00:01:40,520 --> 00:01:43,520
它已经碎了

21
00:01:43,520 --> 00:01:45,240
原来是像花一样的美食

22
00:01:45,360 --> 00:01:48,240
现在碎成了三瓣

23
00:01:48,240 --> 00:01:51,120
刚才我已经偷偷吃了一两块

24
00:01:51,320 --> 00:01:53,120
可能就是因为它太容易碎了

25
00:01:53,120 --> 00:01:55,400
所以说 你看 老板都是提前切好

26
00:01:55,400 --> 00:01:58,920
你只能从他切好的块当中去选

27
00:01:58,920 --> 00:02:03,000
不能够再切了 再切就碎成渣了

28
00:02:03,000 --> 00:02:04,720
接下来雪鱼呀给大家看一下

29
00:02:04,720 --> 00:02:08,640
这个玫瑰花饼有多厚

30
00:02:09,640 --> 00:02:12,720
它的横切面还是很好看的

31
00:02:12,720 --> 00:02:14,800
真的是这么厚

32
00:02:14,800 --> 00:02:17,000
有一圈圈的花纹

33
00:02:17,000 --> 00:02:20,880
这个玫瑰饼是把底面放在了上面

34
00:02:20,880 --> 00:02:24,200
其实下面 才是它的上面

35
00:02:24,200 --> 00:02:27,520
我说袋子的下面才是（玫瑰饼）的上面

36
00:02:30,880 --> 00:02:34,480
现在我把玫瑰饼正过来了

37
00:02:35,600 --> 00:02:39,200
玫瑰饼就是 没切的时候

38
00:02:39,200 --> 00:02:43,360
但是切开之后 它的侧面更像一朵花

39
00:02:47,160 --> 00:02:50,680
这样的渣渣都觉得好吃

40
00:02:51,920 --> 00:02:55,440
它的颜色就是 红 黄 黑相间的

41
00:02:55,440 --> 00:02:58,480
外面是硬壳 烤的比较坚硬

42
00:02:58,480 --> 00:03:01,560
但是 它下面的内瓤是一层层的

43
00:03:02,680 --> 00:03:06,240
哎呦 一碰就掉啊 我们就吃它这一块吧

44
00:03:06,240 --> 00:03:07,720
来

45
00:03:08,480 --> 00:03:13,560
玫瑰花瓣一片片 飘落在眼前

46
00:03:20,160 --> 00:03:25,320
它这个玫瑰饼 算不上多甜

47
00:03:25,320 --> 00:03:29,680
（从外面看颜色）颜色和枣糕很像 闻起来的味道也很像

48
00:03:29,680 --> 00:03:34,640
但是吃一口发现 它们的味道真的是截然不同

49
00:03:34,640 --> 00:03:38,000
像枣糕这种就是闻着甜 吃起来更甜

50
00:03:38,000 --> 00:03:38,880
但是这个（不是）

51
00:03:38,880 --> 00:03:42,040
它的甜度只比  就是嚼馒头的时候

52
00:03:42,040 --> 00:03:45,200
那个麦芽糖的甜味稍稍高一点

53
00:03:45,200 --> 00:03:47,440
根本就不算很甜

54
00:03:54,200 --> 00:03:58,880
美食不仅可以吃 还可以用来享受

55
00:03:58,880 --> 00:04:01,840
它好像美食届的七彩丹霞地貌

56
00:04:01,840 --> 00:04:03,440
它的味道很奇特

57
00:04:03,920 --> 00:04:08,080
既有面包的暄软 又像千层饼一样的酥脆

58
00:04:08,320 --> 00:04:12,080
还有就是 像玫瑰饼的甜美

59
00:04:23,760 --> 00:04:26,440
刚才吃的玫瑰饼 吃的晕头转向的

60
00:04:26,440 --> 00:04:29,120
因为它的味道是既甜 又咸

61
00:04:29,120 --> 00:04:32,360
甜是很容易理解的 里面放了玫瑰酱

62
00:04:32,360 --> 00:04:34,200
这个咸 我想了老半天

63
00:04:34,200 --> 00:04:36,680
好像不太明白 它为什么是咸的

64
00:04:36,680 --> 00:04:39,360
接下来雪鱼就是 返回原来的地方

65
00:04:39,360 --> 00:04:40,240
问一问老板

66
00:04:40,240 --> 00:04:42,920
里面还有什么样的材料是我不知道的

67
00:04:47,480 --> 00:04:52,100
就是里面加了胡麻 还有姜黄 还有一种叫什么

68
00:04:52,100 --> 00:04:52,720
红曲

69
00:04:52,800 --> 00:04:57,760
这实际上就是 八月十五我们蒸的月饼变成烤的了

70
00:04:57,760 --> 00:05:01,640
蒸的东西放不住 这个能够放一个礼拜

71
00:05:01,640 --> 00:05:05,520
蒸的东西 两三天边上就干了

72
00:05:09,240 --> 00:05:14,040
它就是 以前我们那用老酵面做的 发面做的

73
00:05:14,040 --> 00:05:17,760
有些原料 是从老家 自产运过来的

74
00:05:17,760 --> 00:05:20,200
全汁原味 就算绿色产品吧

75
00:05:30,000 --> 00:05:32,640
除了了解里面放了什么原料之外

76
00:05:32,640 --> 00:05:35,000
还意识到 自己原来吃了个月饼

77
00:05:35,360 --> 00:05:39,960
好了 接下来雪鱼将要去下一个地方了

78
00:05:45,040 --> 00:05:48,440
关 注
雪 鱼  探 店

```

**Comment by 3yearsyoung** [comment]
1
00:00:01,680 --> 00:00:05,040
它真的是像一个玫瑰花一样的饼
This cake literally looks like a rose

2
00:00:05,040 --> 00:00:08,360
但是它和云南的鲜花饼不同的是
The difference between this rose cake and the flower cake in Yunnan is

3
00:00:08,360 --> 00:00:11,680
它的块头真的是特别大个
That this one is really big

4
00:00:12,080 --> 00:00:18,400
我不敢举太高 我怕一不小心把玫瑰饼全部打翻
I don’t want to hold it too high because I’m afraid to knock over the whole cake

5
00:00:18,520 --> 00:00:22,800
玫瑰花瓣一片片，飘落在眼前
Pieces of rose petals are falling in front of my eyes

6
00:00:24,200 --> 00:00:28,200
青海·西宁
Xining, Qinghai

7
00:00:32,120 --> 00:00:34,080
雪鱼现在在青海西宁
I’m currently in Xining, Qinghai

8
00:00:34,080 --> 00:00:37,000
待会呢 我们要去吃的是玫瑰花饼
We are going to eat the local rose cake in a few minutes

9
00:00:37,000 --> 00:00:40,520
这个玫瑰花饼和云南的玫瑰花饼 可截然不同
The rose cake here and the one in Yunnan are totally different

10
00:00:40,520 --> 00:00:42,600
待会看一看 庐山真面目
We’ll see the real deal in a moment

11
00:00:42,600 --> 00:00:46,680
绝对会刷新你对玫瑰花饼的认知
It will definitely challenge your usual understanding of rose cake

12
00:00:47,280 --> 00:00:49,280
待会我要去的是一个菜市场
Where I’m going is a farmers’ market

13
00:00:49,280 --> 00:00:51,800
里面有一家专门做玫瑰饼的小店
There is a small street food shop specialised in making rose cakes inside

14
00:00:51,800 --> 00:00:54,320
是这种前店后厨的模式
Counter in the front and kitchen in the back

15
00:00:55,720 --> 00:00:58,640
做好的玫瑰饼呢 会拿到前面切完再卖
The rose cake coming out of the oven will be brought to the front and cut into portions before selling to the public

16
00:00:58,640 --> 00:01:01,640
这么大的一个 切完 也只能切成八份
It can only be cut into 8 portions even it’s already this big

17
00:01:01,640 --> 00:01:06,440
如果你前面站着八个人 那你一定会等下一个玫瑰饼
If there are 8 people queueing in the front, you will have to wait for the next cake

18
00:01:16,480 --> 00:01:19,840
55元3角 给55元吧
55 yuan and 30 cents. Take it home for 55

19
00:01:30,680 --> 00:01:34,280
回去先不要系 晾凉了再系上
Don’t tighten the bag immediately after you get home. Wait until it’s cold

20
00:01:40,520 --> 00:01:43,520
它已经碎了
It has already broken

21
00:01:43,520 --> 00:01:45,240
原来是像花一样的美食
The cake used to look like a flower

22
00:01:45,360 --> 00:01:48,240
现在碎成了三瓣
Now it has broken into three chunks

23
00:01:48,240 --> 00:01:51,120
刚才我已经偷偷吃了一两块
I sneaked two pieces just now

24
00:01:51,320 --> 00:01:53,120
可能就是因为它太容易碎了
Probably because it’s too fragile

25
00:01:53,120 --> 00:01:55,400
所以说 你看 老板都是提前切好
The shopkeeper has to cut the cake for you in advance

26
00:01:55,400 --> 00:01:58,920
你只能从他切好的块当中去选
And you can only choose from the cut portions

27
00:01:58,920 --> 00:02:03,000
不能够再切了 再切就碎成渣了
You can’t cut it any further, or it will turn into broken bits

28
00:02:03,000 --> 00:02:04,720
接下来雪鱼呀给大家看一下
Now, let me show you

29
00:02:04,720 --> 00:02:08,640
这个玫瑰花饼有多厚
How thick this rose cake is

30
00:02:09,640 --> 00:02:12,720
它的横切面还是很好看的
The cut side actually looks pretty lovely

31
00:02:12,720 --> 00:02:14,800
真的是这么厚
The cake is REALLY thick

32
00:02:14,800 --> 00:02:17,000
有一圈圈的花纹
There is a pattern of circles here

33
00:02:17,000 --> 00:02:20,880
这个玫瑰饼是把底面放在了上面
The rose cake is upside down here

34
00:02:20,880 --> 00:02:24,200
其实下面 才是它的上面
The top side is actually on the bottom

35
00:02:24,200 --> 00:02:27,520
我说袋子的下面才是（玫瑰饼）的上面
I mean the top side of the rose cake is on the bottom of the bag

36
00:02:30,880 --> 00:02:34,480
现在我把玫瑰饼正过来了
Now I have turned it over

37
00:02:35,600 --> 00:02:39,200
玫瑰饼就是 没切的时候 外形像一朵花
The shape of the whole cake is like a rose before it’s cut

38
00:02:39,200 --> 00:02:43,360
但是切开之后 它的侧面更像一朵花
But once cut, the side of the cake resembles a rose more

39
00:02:47,160 --> 00:02:50,680
这样的渣渣都觉得好吃
Even these broken bits taste great

40
00:02:51,920 --> 00:02:55,440
它的颜色就是 红 黄 黑相间的
The colour is a mix of red, yellow and black

41
00:02:55,440 --> 00:02:58,480
外面是硬壳 烤的比较坚硬
The outer shell is crusty and crunchy

42
00:02:58,480 --> 00:03:01,560
但是 它下面的内瓤是一层层的
But underneath the shell are layers of goodness

43
00:03:02,680 --> 00:03:06,240
哎呦 一碰就掉啊 我们就吃它这一块吧
Wow, it’s so delicate. Let’s just eat it

44
00:03:06,240 --> 00:03:07,720
来
Here we go

45
00:03:08,480 --> 00:03:13,560
玫瑰花瓣一片片 飘落在眼前
Pieces of rose petals are falling in front of my eyes

46
00:03:20,160 --> 00:03:25,320
它这个玫瑰饼 算不上多甜
This rose cake is, to be honest, not too sweet

47
00:03:25,320 --> 00:03:29,680
（从外面看颜色）颜色和枣糕很像 闻起来的味道也很像
The colour (on the outside) is similar to the date cake, so is the smell

48
00:03:29,680 --> 00:03:34,640
但是吃一口发现 它们的味道真的是截然不同
But once you take a bite, they have completely different flavours

49
00:03:34,640 --> 00:03:38,000
像枣糕这种就是闻着甜 吃起来更甜
The date cake smells sweet, and tastes even sweeter

50
00:03:38,000 --> 00:03:38,880
但是这个（不是）
Totally not the case for this rose cake

51
00:03:38,880 --> 00:03:42,040
它的甜度只比  就是嚼馒头的时候
It’s only slightly sweeter than the maltose

52
00:03:42,040 --> 00:03:45,200
那个麦芽糖的甜味稍稍高一点
When you chew mantou (aka Chinese steamed buns)

53
00:03:45,200 --> 00:03:47,440
根本就不算很甜
Not so sweet at all

54
00:03:54,200 --> 00:03:58,880
美食不仅可以吃 还可以用来享受
You can not only eat, but also enjoy this gourmet food

55
00:03:58,880 --> 00:04:01,840
它好像美食届的七彩丹霞地貌
It seems like the landscape of the colourful Danxia

56
00:04:01,840 --> 00:04:03,440
它的味道很奇特
And it has such a unique taste

57
00:04:03,920 --> 00:04:08,080
既有面包的暄软 又像千层饼一样的酥脆
Soft like bread, crunchy like mille-feuille

58
00:04:08,320 --> 00:04:12,080
还有就是 像玫瑰饼的甜美
And sweet as a rose cake

59
00:04:23,760 --> 00:04:26,440
刚才吃的玫瑰饼 吃的晕头转向的
I’m so confused by the rose cake I just ate

60
00:04:26,440 --> 00:04:29,120
因为它的味道是既甜 又咸
Because it tastes both sweet and savoury at the same time

61
00:04:29,120 --> 00:04:32,360
甜是很容易理解的 里面放了玫瑰酱
It’s easy to understand the sweetness as it has rose sauce in it

62
00:04:32,360 --> 00:04:34,200
这个咸 我想了老半天
But I just can’t comprehend, from my perspective

63
00:04:34,200 --> 00:04:36,680
好像不太明白 它为什么是咸的
Why it is also savoury

64
00:04:36,680 --> 00:04:39,360
接下来雪鱼就是 返回原来的地方
So next, I’ll go back to the shop

65
00:04:39,360 --> 00:04:40,240
问一问老板
And ask the shopkeeper

66
00:04:40,240 --> 00:04:42,920
里面还有什么样的材料是我不知道的
If there are any secret ingredients in there that I don’t know

67
00:04:47,480 --> 00:04:52,100
就是里面加了胡麻 还有姜黄 还有一种叫什么
So, there are sesame and turmeric. What’s the other one called?

68
00:04:52,100 --> 00:04:52,720
红曲
Red yeast

69
00:04:52,800 --> 00:04:57,760
这实际上就是 八月十五我们蒸的月饼变成烤的了
In fact, it’s similar to the mooncake. We just bake it instead of steaming it

70
00:04:57,760 --> 00:05:01,640
蒸的东西放不住 这个能够放一个礼拜
Steamed foods don’t last long, but this cake can last a week

71
00:05:01,640 --> 00:05:05,520
蒸的东西 两三天边上就干了
The edge will dry out within 2 to 3 days if you steam it

72
00:05:09,240 --> 00:05:14,040
它就是 以前我们那用老酵面做的 发面做的
The dough is made from the old starter

73
00:05:14,040 --> 00:05:17,760
有些原料 是从老家 自产运过来的
Some ingredients are brought here from our hometown by ourselves

74
00:05:17,760 --> 00:05:20,200
全汁原味 就算绿色产品吧
All natural and organic. We shall count them as green products

75
00:05:30,000 --> 00:05:32,640
除了了解里面放了什么原料之外
Apart from knowing what ingredients have been put inside

76
00:05:32,640 --> 00:05:35,000
还意识到 自己原来吃了个月饼
I also realise that I just ate a mooncake

77
00:05:35,360 --> 00:05:39,960
好了 接下来雪鱼将要去下一个地方了
Alright, I’ll be on my way to the next place

78
00:05:45,040 --> 00:05:48,440
关 注
雪 鱼  探 店
Follow Xueyu - China Food Travel
