### ISSUE TITLE
[华农兄弟] 华农兄弟搞了点田螺砍点野胡椒一起炒味道还可以哟 - https://youtu.be/I4B4sPo9ulw

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1258]
https://youtu.be/I4B4sPo9ulw
<p>&#35270;&#39057;&#21457;&#24067;&#20110; July 9, 2020 at 01:34PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, pleas upload
#https://youtu.be/I4B4sPo9ulw

#华农兄弟：搞了点田螺，砍点野胡椒一起炒，味道还可以哟
#Huanong Brothers: We got some river snails. Let's fry them with wild pepper. It's not bad!

0:00:00.000,0:00:02.520
# 大家好  今天搞了一點田螺回來哦
Hi everyone! I got some river snails back today.

0:00:03.600,0:00:04.940
# 準備炒田螺吃
We're gonna make some fried river snails.

0:00:05.680,0:00:07.260
# 要搞點這個山胡椒  (註︰他這裡說山胡椒，之後說野胡椒，不管了，就當是山上的胡椒算了)
I gotta fetch some wild pepper.

0:00:08.680,0:00:10.560
# 山胡椒搞點下來  你看
Wild pepper., let's fetch some. Look!

0:00:11.060,0:00:12.120
# 上面就好多
There's a lot up there.

0:00:14.360,0:00:15.700
# 把它勾點下來就好啦
I only need to hook some down here.

0:00:20.560,0:00:22.120
# 你看  一下子就搞了那麼多
Look! I can get so much with just a single pull.

0:00:22.960,0:00:24.420
# 吃不完的等下用來曬乾
The rest can be dried if we can't finish them.

0:00:26.640,0:00:28.740
# 下去  炒田螺  (註︰這裡說得太明白感覺極奇怪，所以starts cooking算了)
Let's go, and start cooking.

0:00:34.120,0:00:36.760
# 我們把這個果子摘下來  摘下來然後就
We first pick all the fruits here, pick them all and then we can,

0:00:37.920,0:00:41.120
# 用油炸一下  這個味道就全部出來啦
fry them in the oil. Then the flavour will all come out,

0:00:41.940,0:00:43.080
# 山胡椒的味道
The scent of wild pepper,

0:00:43.420,0:00:44.300
# 很香的哦
is really nice, you know.

0:00:44.920,0:00:45.820
# 小時候我們
When we were small,

0:00:46.340,0:00:50.520
# 摘來賣  現在都沒人要啦  山上到處都是
we used to sell them. But now nobody wants them anymore. They're everywhere on the hills.

0:00:51.320,0:00:53.140
# 以前一毛錢一斤摘來賣
We sold them at 1 jiao (0.1 RMB) per 500 grams in the past.

0:00:53.920,0:00:55.740
# 每天能摘個一塊錢
And we could have up to 1 RMB in a day.

0:00:57.480,0:00:59.320
# 那時候一塊錢可以買很多糖啦
Back in those days, we could buy a lot of candies with 1 RMB.

0:01:06.120,0:01:07.820
# 你看  摘了那麼一點  夠啦
Look! I've picked just a bit here. It's enough.

0:01:08.360,0:01:10.780
# 要洗一下  洗一下晾乾  等一下
We need to wash it, wash it and then dry it, and then,

0:01:11.200,0:01:12.280
# 就直接可以用啦
it can be used right away.

0:01:23.420,0:01:24.980
# 你看  這是攝影小哥的
Look! These are Mr. Cameraman's

0:01:25.900,0:01:27.300
# 私人小物品
private little kits.

0:01:28.440,0:01:29.080
# 在底下
At the bottom

0:01:30.100,0:01:30.780
# 誒呀
Eya!

0:01:31.380,0:01:32.860
# 這個  給這個鉗子給你
This, this pincer is for you.

0:01:32.860,0:01:33.360
# 好
'kay

0:01:34.380,0:01:35.220
# 這個甚麼鬼
What the heck is it?

0:01:39.660,0:01:40.760
# 這個剪毛的
Is it for cutting hair?

0:01:43.200,0:01:44.140
# 這裡還有把
Here's one more.

0:01:44.920,0:01:45.760
# 打開來看
Let me open it and have a look.

0:01:46.740,0:01:47.600
# 這個尖鉗
It's a sharp pincer.

0:01:48.560,0:01:50.040
# 夠了  那麼多個鉗子
Enough. We have so many pincers now.

0:01:50.580,0:01:52.340
# 幾個人一起來剪  剪得快一點  (註︰同樣是說明"cut"的話，感覺很突冗)
Let's do it together with several of us. It takes much less time.

0:01:52.800,0:01:54.160
# 我要這個最猛的
I take this most powerful one.

0:02:02.860,0:02:05.140
# 你看 這個鉗子好剪  哎呀
Look! This pincer is really effective. Aya!

0:02:20.120,0:02:22.020
# 洗一下這個田螺  這個田螺剪好啦
Let's wash the river snails. They've all been processed.

0:02:22.660,0:02:23.540
# 再洗一下
Wash a few more times.

0:02:43.560,0:02:46.060
# 好啦  洗好啦  我們煮一下水喲
Alright! They're clean now. We're gonna boil them in water for a while.

0:02:46.420,0:02:47.660
# 要把水煮一下
They needs to be boiled in water for a while.

0:02:48.840,0:02:51.840
# 裝點水  煮一下這個田螺  然後再來炒
Take some water, and boil the snails for a while. And then we can fry them.

0:02:52.580,0:02:53.760
# 那才沒那麼腥
So that they won't smell so fishy.

0:03:05.140,0:03:05.940
# 水太多了
Too much water

0:03:15.680,0:03:16.960
# 搞點這個香料下去
Put some spice,

0:03:19.380,0:03:20.700
# 把它臭味遮住
to cover up the bad odour.

0:03:22.280,0:03:25.180
# 你看  再煮一下  好像火候還不是很夠
Look! It doesn't seem long enough. Let's boil it for a longer while.

0:03:28.540,0:03:30.380
# 你看  這個煮好了哦
Look! It's alright now.

0:03:30.520,0:03:32.440
# 我去那個  我去洗一下
I'm gonna, I mean, I'm gonna wash it.

0:03:59.080,0:04:01.900
# 這樣搓一下就把這個瞉  你看  就整個掉下來啦
As I'm rubbing it, the shell, look, the whole piece of shell comes off.

0:04:15.720,0:04:17.420
# 先把鍋燒開
Let me heat the wok first,

0:04:18.920,0:04:20.100
# 然後放油
and then put the oil.

0:04:53.740,0:04:54.980
# 生薑去炸一下
Ginger, let me fry it.

0:05:03.440,0:05:04.260
# 再把這個
And then I put the,

0:05:05.220,0:05:05.960
# 野胡椒
wild pepper,

0:05:16.080,0:05:17.220
# 哎喲  好香哦
Ayo! It smells so good!

0:05:21.360,0:05:22.400
# 搞點這個八角
Put some, this is star anise.

0:05:30.820,0:05:32.160
# 好  準備放田螺啦
Alright! Time for the river snails

0:05:56.440,0:05:57.160
# 加點鹽
Put some salt.

0:05:57.780,0:05:58.620
# 鹽都沒放
I didn't even put salt.

0:06:00.240,0:06:01.100
# 放鹹一點
A bit more salt

0:06:10.100,0:06:11.220
# 好香啊
It smells so good!

0:06:12.140,0:06:13.300
# 聞都聞得那個味道
The smell is already confirming the taste.

0:06:19.120,0:06:20.260
# 丟幾個辣椒下去
Let me throw some chilli in.

0:06:21.000,0:06:23.240
# 這裡還有辣椒粉哦  再搞點下去
Here's also some chilli powder. Let me put some as well.

0:06:24.720,0:06:27.260
# 沒事  攝影小哥不喜歡吃田螺
No worries. Mr. Cameraman doesn't like river snails.

0:06:31.080,0:06:32.420
# 誒  多啦
Ey? Too much

0:06:38.820,0:06:39.980
# 這裡還有點乾辣椒
Here's also some dried chilli.

0:06:51.520,0:06:53.020
# 再放點這個醬油
Put some, some soy sauce too.

0:07:02.780,0:07:04.360
# 你看 顏色就出來啦
Look! The colour is coming out now.

0:07:05.740,0:07:07.000
# 色香味俱全
It pleases your eyes, your nose and your tastes bud as well.

0:07:11.160,0:07:13.920
# 先去把一下  看還有甚麼好放的  順便放下去
Let me have a look around, and see if there's anything good, and put them here all along.

0:07:18.860,0:07:20.420
# 你看  剛好還有點黃酒
Look! I just see that we have some huangjiu (yellow rice wine) here as well.

0:07:21.320,0:07:22.500
# 搞點黃酒下去
Let me put some huangjiu.

0:07:32.100,0:07:33.740
# 在廚房找了一個大蒜
And I got a garlic in the kitchen.

0:07:34.600,0:07:36.000
# 大蒜也扔下去算啦
Let me just throw the garlic in.

0:07:39.540,0:07:40.340
# 拍一下就好
Smash it, that's it!

0:07:49.880,0:07:50.880
# 這有幾個大蒜
Here's some garlic.

0:07:58.600,0:07:59.860
# 哎呀  越來越香啦放點水下去
Aya! The scent is getting more and more attractive.

0:08:01.780,0:08:02.920
# 加點水
Put some water.

0:08:04.500,0:08:06.520
# 把它燜 煮熟它
And then stew it, cook it.

0:08:10.100,0:08:10.900
# 放點水
Put some water.

0:08:11.080,0:08:12.180
# 誒  鍋呢
Eh? Where's the pot?

0:08:19.240,0:08:20.920
# 搞了點山泉水來燜
I've fetched some spring water to the stew.

0:08:33.840,0:08:34.900
# 燜個半個小時
Stew it for half and hour,

0:08:35.140,0:08:36.720
# 這田螺就可以吃啦
and then I can start my feast.

0:08:51.580,0:08:52.900
# 應該熟了哦  看一下
I think it's done now. Let me have a look.

0:09:10.700,0:09:11.840
# 看上去就好吃
It looks really tasty.

0:09:17.140,0:09:17.980
# 裝不下啦
The plate is full.

0:09:18.900,0:09:19.540
# 下一盤
Next plate...

0:09:20.580,0:09:21.800
# 看  吃這盤就好啦
Look! This plate is already enough for me.

0:09:21.960,0:09:22.860
# 這盤我的
And this plate is my,

0:09:23.220,0:09:24.100
# 晚上我來吃
one of the dishes of my dinner.

0:09:26.240,0:09:27.980
# 哎呀  到這裡來吸
Aya! Let me enjoy it here.

0:09:37.600,0:09:39.200
# 你看  這個葉子
Look! This leave...

0:09:40.880,0:09:41.520
# 漂亮吧
Pretty, isn't it?

0:09:42.660,0:09:44.020
# 瞬間上檔次
It becomes fine dining instantly.

0:09:52.060,0:09:53.100
# 哎呀  很燙
Aya! Hot!

0:09:59.060,0:09:59.560
# 這個
The,

0:09:59.940,0:10:00.640
# 田螺瞉把
the shells can be used to,

0:10:01.640,0:10:02.140
# 餵魚
feed the fish.

0:10:08.100,0:10:10.680
# 哇  真的很好吃哦  就是有點辣
Wa! It's really tasty. But it's a rather spicy.

0:10:27.580,0:10:29.380
# 一個田螺就那麼一點點肉
The edible part of a river snail is just a tiny little bit here.

0:10:35.220,0:10:35.780
# 好辣
Burning!

0:10:41.100,0:10:42.420
# 真的很辣哦  這個辣椒
It's really spicy, this kind of chilli.

0:10:42.620,0:10:44.740
# 好啦  今天視頻就到這裡啦
Alright! The video ends here.

0:10:45.820,0:10:47.320
# 反正攝影小哥又吃不了
Mr. Cameraman can't stand it anyway.

0:10:47.440,0:10:48.080
# 太辣啦
It's far too spicy.
