### ISSUE TITLE
[华农兄弟] 砍芒草 - https://youtu.be/1V_wXgEq6JY

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1263]
https://youtu.be/1V_wXgEq6JY
<p>&#35270;&#39057;&#21457;&#24067;&#20110; July 11, 2020 at 11:31AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/1V_wXgEq6JY

#华农兄弟：山上长满了芒草，砍点来做扫把，很实用哦
#Huanong Brothers: The silvergrass is everywhere on the hill. We chop some and make a broom. It's really nice.

0:00:00.000,0:00:02.060
# 大家好  家裡的掃把都壞啦
Hi everyone! My broom at home is broken.

0:00:02.640,0:00:05.320
# 我們 割點這個芒花  這就個芒花  (註︰標題說是芒草，而這也應該是芒草，芒花應該是他的叫法而已，沒有很好的翻譯，所以不予以配合)
We're gonna get some this kind of silvergrass, I mean the silvergrass here.

0:00:06.040,0:00:07.860
# 拿來做一個  做幾個掃把來
We'll make a broom, a couple of brooms using it.

0:00:09.000,0:00:12.660
# 這個要帶手套來  不撚割手的  安全第一
I gotta wear the gloves. It cuts otherwise. Safety first.

0:00:13.120,0:00:15.940
# 你看這個  一割就可以把它割下來
Look! It can be cut down simply with a single pull.

0:00:29.600,0:00:32.440
# 農村裡面  就喜歡用這個做掃把
People in the villages loves the brooms made with silvergrass.

0:00:33.280,0:00:34.840
# 老人家  不用錢買啊
I mean the elderlies. It saves money.

0:00:35.680,0:00:37.780
# 要把這個一個個敲 敲  敲完來
These stuffs need to be all shaken, shaken, shaken off one by one.

0:00:38.460,0:00:39.660
# 不敲完的話就
If any of them remain,

0:00:41.060,0:00:42.700
# 就沒用  越掃越多
the broom would be useless. If anything, it would only make more dust.

0:00:43.400,0:00:44.740
# 這樣  要慢慢的
So it is. It takes time,

0:00:45.560,0:00:46.520
# 慢慢的掃
it takes time to clear them all.

0:00:47.980,0:00:52.940
# 這個先會回去曬一下  不曬一下搞不了 老是會斷掉
It needs to be dried under the sun at home first. It doesn't work otherwise. It would break very easily.

0:00:56.840,0:00:58.780
# 隨便收拾一下
I'm just trying to tidy it up,

0:00:59.740,0:01:02.060
# 收拾一下  然後放在家裡面
tidy it up, and then, leave it at home,

0:01:02.740,0:01:06.180
# 曬個兩三天  就可以做這個掃把啦
then dry it under the sun for a couple of days. And then we can use it to make brooms.

0:01:28.520,0:01:30.180
# 這裡差不多可以做一個
Here's almost enough for a broom.

0:01:31.040,0:01:32.040
# 好像還是不夠的
Well, not quite

0:01:33.280,0:01:35.600
# 到時候把它紥起來就這樣  咻咻
That's how it looks when we tie it up! Hiup, hiup~!

0:01:36.240,0:01:37.920
# 但這個要  把這個毛給搞掉
But we need to, we need to get rid of the fur.

0:01:38.780,0:01:39.640
# 這是種子哦
These are the seeds, in fact.

0:01:40.440,0:01:41.200
# 撒在哪裡
Where they drop,

0:01:41.980,0:01:43.960
# 哪裡就  落地生根
where they, get rooted.

0:01:47.080,0:01:49.320
# 還要去割點  不少了  再割點過來
I still need more. It's too little here. Let me cut a bit more.

0:01:51.760,0:01:54.320
# 前面好多  你看  一大片都是
There's a lot in the front. It's everywhere.

0:02:03.360,0:02:06.760
# 小黑 走  帶你去吃香的喝辣的
Let's go Blacky! I have good food and good wine for you.

0:02:12.500,0:02:13.100
# 哦
Oh?

0:02:14.220,0:02:14.840
# 掉啦
It drops.

0:02:26.320,0:02:26.860
# 你看
Look!

0:02:29.540,0:02:30.500
# 好靚哦  這個
It's really beautiful,

0:02:30.920,0:02:31.700
# 看球球的
like a furry ball.

0:02:44.380,0:02:44.960
# 你看
Look!

0:02:45.880,0:02:46.860
# 就拗了這一點點
So I have just a tiny little bit here.

0:02:47.920,0:02:49.440
# 回那個廠裡面去
I'm gonna take it back to, you know, our site.

0:02:49.740,0:02:51.700
# 再搞一點  就可以做一個啦
Let me get a bit more. Then it will be enough to make a broom.

0:02:52.040,0:02:53.520
# 這個只能做半個
It's only enough for half a broom here.

0:02:54.900,0:02:56.300
# 你看  這樣就可以掃地啦
Look! Then we can sweep the floor.

0:02:56.500,0:02:57.740
# 掃的很乾淨的哦
It sweeps very well, you know.

0:02:58.760,0:02:59.340
# 掃狗
Sweep away the dog

0:03:24.960,0:03:26.020
# 它們都胖了
They're getting fat.

0:03:28.100,0:03:29.720
# 哎呀  這鴨子就剛剛好
Aya! This duck is perfect.

0:03:37.760,0:03:39.280
# 你看 這裡就很多
Look! Here's a lot!

0:03:40.600,0:03:41.360
# 從這裡進來
Let's get in from here.

0:03:46.240,0:03:47.700
# 你看  這裡就很方便啦
Look! It's really convenient here.

0:03:50.600,0:03:52.100
# 雖然搞這個有點麻煩
Though the process is quite a trouble,

0:03:52.740,0:03:54.240
# 但是用起來就很方便
the product gives much convenience.

0:03:56.900,0:03:57.740
# 你看  現在
Look! Now,

0:04:00.780,0:04:02.280
# 這都剛好到那個
right now it's the, I mean,

0:04:03.200,0:04:05.740
# 就是 開花的季節  就把它搞掉
like, the blossoming season. And now we cut it off.

0:04:11.920,0:04:13.560
# 你看  這種就是沒開花的
Look! These have no flowers.

0:04:14.140,0:04:15.340
# 沒開花的也行
But it doesn't matter.

0:04:17.620,0:04:19.200
# 這些碎的就把它砍掉
I'm gonna cut off these shattered ones,

0:04:19.760,0:04:21.100
# 沒有長的也把它砍掉
and also those which are not growing.

0:04:21.980,0:04:24.800
# 砍完之後就到時候  明佃它就會長很多出來
After clearing them, later, next year, a lot will be coming out.

0:04:31.640,0:04:35.080
# 你看  這個叫芒  芒花  
Look! This is called silver, silvergrass.

0:04:36.140,0:04:37.020
# 芒草的芒 (註︰這裡就是找一些說了等於沒說的字算了)
Silver, as in silvergrass

0:04:38.300,0:04:39.260
# 小花的花
Grass, as in grassland

0:04:43.700,0:04:45.660
# 不需要那麼長的  砍短一點
It doesn't it to be that long, cut it short.

0:05:04.900,0:05:08.000
# 你看  差不多啦  留點種子給人家
Look! It should be enough now. Gotta leave some here growing.

0:05:09.460,0:05:10.880
# 幾棵  幾棵就夠啦
A couple, a couple of them would be enough.

0:05:12.180,0:05:13.540
# 不要把它全部砍光啦
Don't cut everything.

0:05:14.860,0:05:15.860
# 這些帶回去
Let me take all these back.

0:05:42.180,0:05:45.420
# 你看  這個砍回來啦  我要曬幾天
Look! I've taken them all back and gonna dry them under the sun for a few days.

0:05:46.320,0:05:47.100
# 就這樣曬著
Just leave them here.

0:05:47.600,0:05:49.680
# 過兩天就可以  直接做掃把啦
We can make the brooms using them right away, in a couple of days.

0:05:51.020,0:05:52.700
# 今天吃的那個碗都沒收
The bowl that I used today is still here.

0:05:52.960,0:05:53.980
# 吃午飯吃的
I used it for my lunch.

0:05:56.140,0:05:57.960
# 這個芒杆  曬干了哦
The stems, are all dried now.

0:05:58.400,0:06:01.440
# 你看 這個毛  其實就是它的種子來的
Look! The fur, these are the seeds in fact.

0:06:02.580,0:06:03.420
# 這個種子
The seeds,

0:06:05.320,0:06:05.960
# 要把它
needs to be,

0:06:06.780,0:06:07.880
# 打  打脫掉
all shake, shaken off.

0:06:08.780,0:06:11.860
# 不打脫掉等一下就  越掃越多毛
It simply leaves even more dust if the any of the seeds are left here.

0:06:13.780,0:06:15.420
# 你看 現在沒那麼多毛啦
Look! There's much less fur now.

0:06:25.460,0:06:27.880
# 這個種子  傳播很快的哦
The seeds, they spread really fast, you know.

0:06:29.180,0:06:31.680
# 如果一不小心的話  整個山頭都是這個
The seeds would spread to everywhere in the hill in no time,

0:06:32.560,0:06:35.180
# 芒杆的種子  就時候就全部長出這個
if they're not taken care of. And you will see the silvergrass,

0:06:35.920,0:06:36.600
# 芒杆啦
everywhere.

0:06:42.180,0:06:44.540
# 這個掃把  其實我是不會做的
Frankly speaking, I, I don't really know how to make a broom.

0:06:45.180,0:06:48.000
# 剛好攝影小哥的奶奶來啦  叫她幫忙做一下
Right now Mr. Cameraman's grandma is here. I'll ask her to help us.

0:06:49.680,0:06:52.260
# 我以前我看過  看過別人做過
I've seen, seen people making them in the past.

0:06:53.300,0:06:54.300
# 自己沒做過
But I've never made one myself.

0:06:55.380,0:06:57.380
# 叫攝影小哥的奶奶教我做一下
So I'm gonna let Mr. Cameraman's grandma show me how to make one.

0:07:00.900,0:07:01.400
# 好啦
Alright!

0:07:12.860,0:07:15.460
# 你們在乾甚麼
What are you doing~?

0:07:15.700,0:07:17.720
# 我們在紥掃把
We are making brooms~!

0:07:18.720,0:07:20.160
# 掃把
Broom!

0:07:24.100,0:07:28.620
# 先把這個皮先撕一下  其實這個是  芒杆的葉子
Let me first peel off the skin. It's its leaf, in fact.

0:07:29.400,0:07:33.120
# 先把它撕下來  撕下來之後就慢慢地把它紥
I first tear it off, tear it off and then we can spend the rest of the time tying them up.

0:07:34.480,0:07:36.120
# 要紥成幾個小捆來做
We need to tie them up in small bunches.

0:07:40.300,0:07:42.420
# 我來  幫奶奶打下手
I am here, to be Grandma's assistance.

0:07:44.620,0:07:45.340
# 再來一根
One more

0:07:47.840,0:07:50.260
# 以前在農村裡面這個掃把都不用買
In the past, we didn't need to buy any brooms in the village.

0:07:51.080,0:07:55.000
# 都是自己做  竹葉子都可以做  這個也可以做
Brooms were always made by ourselves. We used bamboo leaves, and silvergrass too.

0:08:30.440,0:08:32.620
# 把這個  摘上來一點
This one, make it here.

0:09:21.420,0:09:23.200
# 嗯  搞好啦  你看
Um! Done! Have a look!

0:09:23.780,0:09:25.300
# 這掃把  很紥實哦
The broom, is really sturdy.

0:09:26.740,0:09:27.860
# 搞的很乾淨
It sweeps very well.

0:09:29.280,0:09:30.220
# 一塵不染
Completely dustless

0:09:30.620,0:09:31.880
# 這裡還有一點點這個
Here's still a little bit of, you know,

0:09:32.340,0:09:33.900
# 毛毛  掉完就好啦
the fur. Just let it drop and it's fine.

0:09:35.020,0:09:38.920
# 你看 掃這個地  是不是一個小螞蟻都掃的乾乾淨淨
Look! Even a tiny ant, can be swept, swept away from the floor, isn't it?

0:09:49.400,0:09:51.740
# 這個掃把  掃的好乾淨的哦這個
This brooms, it really sweeps very well, you know.

0:09:52.040,0:09:53.720
# 比買的掃把掃的還乾淨
It's even better then those bought outside.

0:09:55.080,0:09:57.280
# 好啦 今天的視頻就到這裡啦
Alright! The video ends here.

0:09:58.220,0:09:59.380
# 你看  就做了一個
Look! One is done now.
