### ISSUE TITLE
[华农兄弟] 炸小鱼 - https://youtu.be/Rly3oKNvuZs

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1271]
https://youtu.be/Rly3oKNvuZs
<p>&#35270;&#39057;&#21457;&#24067;&#20110; July 12, 2020 at 11:36AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/Rly3oKNvuZs

#华农兄弟：周末聚餐，炸点小鱼，摘点兄弟家菜，又是开心的一天
#Huanong Brothers: Weekend gathering. Some fried fish, with some veggies from buddy's. Another joyful day.

0:00:00.000,0:00:01.240
# 今天是週末哦
It's weekend today.

0:00:02.120,0:00:03.480
# 去搞了一點小魚
I've fetch some small fish.

0:00:04.540,0:00:06.500
# 剛好加加餐  小孩子都回來啦
So we can have an extra dish. The kids are all back here.

0:00:07.900,0:00:09.640
# 那個放地籠  放地籠
Well, the trap, I've put the trap,

0:00:10.720,0:00:11.860
# 裝了一點魚回來
and have caught some fish.

0:00:16.040,0:00:17.700
# 這是螃蟹  這是石班魚
These are crabs, these are (freshwater) groupers,

0:00:18.540,0:00:19.800
# 這個是pa gong
and these are "pa gong" (untranslatable local carps).

0:00:48.940,0:00:50.320
# 家裡又沒有煤氣啦
We've run out of gas here again.

0:00:50.840,0:00:51.700
# 用這個柴火
I'm gonna use the firewood.

0:00:52.140,0:00:53.340
# 這個柴火不用錢的
The firewood is free of charge.

0:01:05.820,0:01:06.820
# 嗯  著啦
Um! It glows.

0:01:11.560,0:01:13.080
# 誒呀  這麼多水
Aya! It's so wet.

0:01:13.500,0:01:14.760
# 一吹就滅掉啦
The fire can't even stand a single blow of wind.

0:01:16.900,0:01:17.800
# 好 可以啦
Alright! Fine!

0:01:18.040,0:01:18.540
# 夠啦
It's enough.

0:01:35.180,0:01:37.920
# 家裡沒甚麼青菜 我去兄弟家搞點來
I don't have much veggies left here. So I'm gonna get some from my buddy's place.

0:01:39.080,0:01:40.280
# 拿這個筲箕來
I go with this sieve.

0:01:46.100,0:01:47.020
# 好多魚魚
A lot of fishy!

0:01:47.280,0:01:48.000
# 這個魚魚
These fishy

0:01:48.260,0:01:48.880
# 哪裡
Where?

0:01:48.900,0:01:49.400
# 跑啦
They've run away.

0:01:49.840,0:01:50.420
# 好多魚
A lot of fish

0:01:50.660,0:01:51.740
# 小小的 是不是
They're so tiny, aren't they?

0:01:52.140,0:01:53.100
# 哪裡  看到沒有
Where?
See?

0:01:57.100,0:01:59.120
# 是  好多這個魚魚  你不要抓
Yea! Here are a lot of fish. Don't try to catch them!

0:01:59.160,0:02:00.300
# 等掉溝裡面去喲
We might fall into the ditch otherwise.

0:02:01.080,0:02:01.720
# 刘星辰
Liu Xingchen!

0:02:02.300,0:02:02.960
# 不要下去啦
You're not going down!

0:02:03.480,0:02:04.840
# 很髒 有水
It's dirty, and it's wet!

0:02:07.920,0:02:09.440
# 去  到裡面摘菜  走
Let's go! We go inside for the veggies. C'mon!

0:02:10.140,0:02:11.040
# 刘楚萱
Liu Chuxuan!

0:02:12.060,0:02:13.280
# 衣服都被你撐爛啦
You're ruining your T-shirt!

0:02:20.960,0:02:22.320
# 刘星辰你不要下去啦
Liu Xingchen, you're not going down!

0:02:27.760,0:02:29.520
# 你看  兄弟家的老茄子
Look! My buddy's old egg plants,

0:02:29.920,0:02:31.020
# 又大又長
are all big and long.

0:02:31.840,0:02:33.040
# 我把它摘掉一點
Let me help him pick some,

0:02:33.700,0:02:34.840
# 幫它吃掉一點
and help him finish some.

0:02:37.080,0:02:38.400
# 哎呀 小狗你也來啦
Aya! Doggie, you're here too?

0:02:39.100,0:02:41.580
# 3個  夠啦  我看一下有沒有攀蒲
Three. It's enough. Let me see if there are any pumpkins.

0:02:41.760,0:02:43.660
# 搞兩個攀蒲回去  再搞點青椒
I'm gonna get a couple of pumpkins, and also some green peppers.

0:02:44.760,0:02:45.820
# 差不多就這樣啦
And I think that's it.

0:02:47.440,0:02:49.260
# 這裡面 前面好像有苦瓜哦
Here inside. There seems to be some bitter gourds in the front.

0:02:50.820,0:02:51.920
# 我來摘兩個
I'm gonna pick a couple of them.

0:02:53.340,0:02:54.100
# 這個
This one

0:03:02.340,0:03:03.520
# 好  這三個
Alright! These three

0:03:04.460,0:03:05.200
# 好靚哦
Beautiful!

0:03:06.020,0:03:06.780
# 三個
So three

0:03:10.400,0:03:12.640
# 還有其它的  再看一下其它的有沒有
There are something more. Let's see if there's anything else.

0:03:14.820,0:03:16.040
# 哎呀  這裡有一個
Aya! Here's one.

0:03:17.620,0:03:19.160
# 這裡有一個小南瓜
Here's a small pumpkin.

0:03:20.360,0:03:21.880
# 很小的  看到沒有
It's really small, see?

0:03:23.680,0:03:24.420
# 這個南瓜
This pumpkin,

0:03:24.900,0:03:25.680
# 特別小
is exceptionally small.

0:03:26.480,0:03:28.500
# 一個就夠啦  我吃一餐就可以啦
One is enough. It's only for one meal.

0:03:30.000,0:03:32.360
# 搞一點青椒  對面有青椒哦
Let me pick some green peppers. There are green peppers on the other side.

0:03:39.840,0:03:41.140
# 這  這裡還有青椒
Here, here are some green peppers too.

0:03:44.580,0:03:45.760
# 這  這青椒
These, these green peppers,

0:03:46.600,0:03:47.600
# 摘點來配菜
let me pick some as side ingredients.

0:03:57.100,0:03:58.020
# 這裡有一個
Here's one.

0:04:01.000,0:04:01.760
# 就沒啦
Just one?

0:04:02.640,0:04:04.440
# 誒喲  一條狗在這裡
Eyo! A dog is here!

0:04:09.380,0:04:12.320
# 嗯 都爛啦  這個有點  爛啦
Um! It's rotten. This is a bit, rotten.

0:04:12.780,0:04:13.700
# 夠啦  你看
Enough! Look!

0:04:14.520,0:04:15.800
# 都是兄弟家的
These are all from my buddy.

0:04:19.400,0:04:21.040
# 天天都有蔬菜吃  (註︰這個不想直譯，直譯感覺好像只是說一個飲食習慣而已，所以寫得更明白一點)
I'm never short of veggies.

0:04:21.140,0:04:21.940
# 先煎
First let's fry,

0:04:23.180,0:04:24.220
# 先煎點魚
fry some fish.

0:04:25.640,0:04:27.100
# 先把大的先下鍋
I put the big ones into the wok first,

0:04:28.680,0:04:29.820
# 小的慢慢來
followed by the small ones.

0:04:37.280,0:04:38.480
# 這是小的
These are small.

0:04:39.340,0:04:41.000
# 小的等下一鍋就煎啦
I'll fry the small ones in a while.

0:04:51.960,0:04:54.760
# 你看  這個  可以啦
Look! This is, alright now.

0:05:32.220,0:05:33.080
# 這個煙囱
This is a chimney.

0:05:34.820,0:05:35.900
# 太大煙啦
It's too smoky.

0:05:36.680,0:05:37.360
# 來啊
C'mon!

0:05:38.220,0:05:39.540
# 現在煙都沒的出
Now the smoke is not coming out.

0:05:43.100,0:05:46.040
# 你看  搞了這幾個  搞到現在天都黑啦
Look! So I'm done with these dishes. It's already dark now.

0:05:46.940,0:05:47.960
# 好  還有一個
Ya! One more dish

0:05:48.320,0:05:49.060
# (刘星辰，我的瓶子被狗咬壞了怎麼辦) (註︰這個沒有原字幕，但太清楚了，我想一拼翻譯)
(Liu Xingchen! The dog is chewing my bottle. What should I do?)

0:05:49.060,0:05:49.700
# 還有一個
One more
(Liu Xingchen! The dog is chewing my bottle. What should I do?)

0:05:49.700,0:05:51.040
# (刘星辰，我的瓶子被狗咬壞了怎麼辦)
(Liu Xingchen! The dog is chewing my bottle. What should I do?)

0:05:51.040,0:05:52.080
# 被你端走啦
You've taken it away.
(Liu Xingchen! The dog is chewing my bottle. What should I do?)

0:05:52.080,0:05:53.840
# (刘星辰，我的瓶子被狗咬壞了怎麼辦)
(Liu Xingchen! The dog is chewing my bottle. What should I do?)

0:05:55.420,0:05:57.100
# 可以準備吃飯啦
Alright! Let's get ready for dinner.

0:05:59.060,0:06:00.380
# 今天的視頻就到這裡啦
So the video ends here.

0:06:00.620,0:06:01.520
# 開始吃飯啦
We're gonna have our dinner.

0:06:02.740,0:06:04.040
# 開飯啦  開飯啦
Meal time, meal tim!

0:06:12.200,0:06:13.620
# 哦  我要可樂
Oh! I want coke!

0:06:13.660,0:06:14.280
# 你要可樂哇
You want coke, right?

0:06:15.640,0:06:17.300
# 好可以啦  不要喝多啦
Alright, enough! Not too much

0:06:18.560,0:06:19.720
# 不能一起喝的
Don't share!
