### ISSUE TITLE
【美食作家王刚】珊瑚鱼 - https://youtu.be/8GF3Di-WCv0

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1274]
**视频链接**：https://youtu.be/8GF3Di-WCv0

视频时长11:49，预计发布时间为北京时间7月14日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“珊瑚鱼”的终极做法，最完整全面的技术分享，期待同学们做出来！

简介
大家好，硬核厨房第二期来做个拿手菜“珊瑚鱼”，由于其成菜形状酷似珊瑚而得名，做法流程和松鼠鱼有异曲同工之妙，不过对刀工和油的掌控要求更高，所以想做此菜的朋友一定要多多研习此视频。如果哪位朋友在家做出来的话，请在此留言下告诉我，我会亲自点评，非常期待！

字幕
0:00:00.283,0:00:00.811
哈喽 大家好

0:00:00.831,0:00:01.440
我是王刚

0:00:01.440,0:00:03.480
本期视频我给大家分享一道拿手菜

0:00:04.820,0:00:05.990
珊瑚鱼

0:00:06.200,0:00:08.811
首先我们准备一条三斤左右的草鱼

0:00:09.459,0:00:10.760
用刀拍晕鱼头之后

0:00:10.760,0:00:12.160
在颈部切上一刀

0:00:12.340,0:00:15.178
这一步的目的是切断草鱼的神经防止跳动

0:00:15.380,0:00:17.302
然后用小刀将鱼鳞刮干净

0:00:21.451,0:00:23.420
鱼鳞刮干净之后剖开鱼肚

0:00:25.112,0:00:27.895
然后去除各种内脏和鱼鳃清洗干净备用

0:00:34.274,0:00:35.834
下一步开始准备分解

0:00:36.286,0:00:39.122
将鱼从中间片开之后再按照步骤取下鱼肉

0:00:39.637,0:00:42.500
同学们取鱼排的时候必须贴着肉往下滑

0:00:42.580,0:00:44.327
否则鱼肉不规则也无法切成

0:00:44.327,0:00:45.863
长条完整的珊瑚

0:00:46.380,0:00:48.766
由于此菜不需要用到鱼头和鱼骨

0:00:48.885,0:00:51.503
分解下来的鱼骨和鱼头可以安排煮汤

0:01:12.400,0:01:14.127
下一步我们开始切珊瑚

0:01:14.520,0:01:17.040
首先我们斜刀切下第一片鱼肉不用

0:01:17.160,0:01:19.874
然后继续斜刀将鱼片间隔一厘米左右

0:01:20.000,0:01:21.180
切至鱼皮不断

0:01:21.306,0:01:23.700
鱼皮的厚度大约保持在三毫米左右

0:01:23.840,0:01:25.960
同学们切记不能片得低于三毫米

0:01:26.080,0:01:28.759
否则鱼片切丝或者上粉的时候容易抖断

0:01:29.030,0:01:31.160
然后我们看一下切好的成品

0:01:34.400,0:01:35.679
下一步开始切丝

0:01:36.438,0:01:39.020
这一步我们将鱼肉朝上放到菜板上面

0:01:39.775,0:01:43.397
然后一片一片翻过来用刀根部往外推切成细丝

0:01:43.660,0:01:46.100
同学们切记这一步至关重要

0:01:46.100,0:01:48.542
必须是菜刀根部先着地往前滑

0:01:48.641,0:01:50.980
刀角切下的位置必须顶着鱼皮

0:01:51.088,0:01:53.482
这样切出来的珊瑚才够直观好看

0:01:53.728,0:01:56.906
还有一种方法是将鱼肉冰冻之后再用剪刀裁剪

0:01:57.140,0:01:59.500
鱼肉冰冻后再裁剪到出成品

0:01:59.500,0:02:00.900
大约需要四小时

0:02:01.140,0:02:02.780
由于时间比较慢

0:02:02.780,0:02:04.059
所以已经淘汰

0:02:04.245,0:02:05.980
专业厨师按照此法改刀出品

0:02:05.980,0:02:07.980
只需要15分钟即可上菜

0:02:08.120,0:02:09.596
下一步开始初加工

0:02:09.829,0:02:12.473
首先我们将鱼肉放入清水中清洗干净

0:02:12.781,0:02:16.255
这一步可以去除鱼肉之间残存的血水和细小的肉粒

0:02:17.410,0:02:19.480
清洗干净之后将鱼肉捞出

0:02:30.880,0:02:33.410
鱼肉捞出之后准备一张干净的毛巾

0:02:35.540,0:02:37.620
将鱼肉放到毛巾中折叠起来

0:02:37.740,0:02:40.100
轻轻的挤压几下吸干多余的水分

0:02:40.240,0:02:43.357
这一步的目的是方便下一步腌制吸收调料的味道

0:02:43.620,0:02:45.450
下一步我们开始准备腌制

0:02:45.500,0:02:47.470
碗中加入食用盐一小勺

0:02:47.560,0:02:49.555
加入适量的黄酒搅拌均匀备用

0:02:49.800,0:02:52.024
没有黄酒的同学也可以用料酒代替

0:02:55.315,0:02:57.816
然后将吸干水分的鱼肉腌制两分钟

0:02:58.040,0:02:59.760
同学们切记不能加胡椒粉

0:03:00.000,0:03:01.600
否则成菜会有糊辣味

0:03:27.120,0:03:29.680
两分钟之后加入玉米淀粉一大碗拌匀

0:03:30.000,0:03:32.510
玉米淀粉可以控制鱼肉松软的口感

0:03:32.580,0:03:35.510
喜欢外酥内软的同学可以全程加玉米淀粉

0:03:47.602,0:03:50.410
然后加入土豆淀粉一大碗均匀的拍上

0:03:50.554,0:03:53.252
这个过程必须拍到位不能放过每一个细节

0:03:53.660,0:03:56.730
加土豆淀粉可以让鱼肉长时间的保持脆爽

0:03:56.980,0:03:59.710
玉米和土豆淀粉的比例大概为3:7

0:04:10.543,0:04:12.290
下一步开始调碗汁

0:04:12.720,0:04:15.070
碗中加入番茄酱300克

0:04:16.660,0:04:18.153
加入白醋40克

0:04:20.540,0:04:22.310
加入白糖120克

0:04:31.360,0:04:33.690
搅拌的中途再加入少许的食用盐

0:04:37.498,0:04:38.683
下一步开始制作

0:04:39.210,0:04:40.920
首先我们把锅烧热

0:04:40.920,0:04:42.532
锅烧热之后加入宽油（植物混合油）

0:04:42.907,0:04:44.421
 油量大约为五公斤

0:04:52.451,0:04:54.163
然后将油温烧至六成热

0:05:00.778,0:05:03.448
油温六成热之后将鱼肉的淀粉稍微抖一下

0:05:10.410,0:05:12.060
双手拉着两边下锅炸

0:05:17.625,0:05:20.945
略微定型之后再放手将鱼肉下锅中小火炸三分钟

0:05:21.134,0:05:23.153
同学们火候的变化分两个阶段

0:05:23.320,0:05:25.151
下锅前两分钟小火略高（5成油温）

0:05:25.400,0:05:26.814
油温大约150度

0:05:26.939,0:05:30.565
第二阶段在两分钟之后开一次中火将油温提升15度

0:05:46.065,0:05:48.637
三分钟之后将鱼肉捞出

0:05:57.044,0:06:00.069
鱼肉炸好之后捞出将其堆叠摆盘即可

0:06:00.069,0:06:02.202
刚捞出来的鱼肉非常的烫手

0:06:02.438,0:06:04.650
建议不抗烫的同学带防烫手套

0:06:04.650,0:06:06.827
或者待其稍微冷却之后再操作

0:06:15.220,0:06:18.267
宽油倒出之后再加入少许的底油开始烧汁

0:06:20.122,0:06:22.421
然后直接将调好的番茄汁下锅

0:06:35.080,0:06:37.928
中火烧滚之后再加入适量的清水稀释一下

0:06:43.146,0:06:44.764
再次烧开之后将锅离火

0:06:47.132,0:06:49.344
然后少量多次的加入水淀粉拌匀

0:07:05.498,0:07:07.394
淀粉拌匀之后将其烧开

0:07:14.125,0:07:16.488
最后再加入少许的明油分两次加入

0:07:16.888,0:07:18.980
第一次加入的明油将其拌匀

0:07:21.617,0:07:23.144
第二次加的明油不动

0:07:24.152,0:07:27.280
料汁烧好之后直接出锅淋在炸好的鱼上面即可

0:07:27.420,0:07:30.090
最后可以撒上自己喜欢的点缀即可上菜

0:07:39.125,0:07:42.317
一道口感酥脆味道酸甜的珊瑚鱼就制作完成

0:07:54.488,0:07:55.767
下面开始技术总结

0:07:55.972,0:07:57.901
第一工具的选择

0:07:58.060,0:07:59.580
首先我们会用到三把刀

0:07:59.580,0:08:02.576
分别是砍刀 小尖刀和片刀

0:08:02.576,0:08:04.215
第一次使用的是砍刀

0:08:04.215,0:08:06.380
用于拍晕草鱼和开边剁骨

0:08:09.931,0:08:13.340
第二把是小尖刀用于刮鱼鳞和开膛破肚

0:08:20.392,0:08:21.740
第三把是片刀

0:08:21.780,0:08:23.420
此刀刀身宽薄长

0:08:23.460,0:08:25.060
用于片鱼和切丝

0:08:26.720,0:08:27.440
第二

0:08:27.520,0:08:29.134
用砍刀横切整个鱼的时候

0:08:29.134,0:08:31.063
刀锋略朝下贴着鱼肉滑过

0:08:31.354,0:08:33.243
这样可以留下绝大部分的鱼肉

0:08:33.480,0:08:34.760
同时新手操作的时候

0:08:34.760,0:08:36.600
左手可以用毛巾垫着抓鱼

0:08:36.740,0:08:38.816
这样可以防止粘液滑手撞刀

0:08:49.766,0:08:51.340
此段演示错误的操作

0:08:51.460,0:08:52.596
由于刀锋朝下

0:08:52.940,0:08:54.708
且没有贴着鱼的脊骨取肉

0:08:55.020,0:08:58.540
所以取下的鱼肉呈现不规则也不美观

0:09:14.820,0:09:16.873
第三取鱼排的时候同样需要

0:09:16.873,0:09:18.402
贴着排骨往下切

0:09:18.629,0:09:21.460
这样除了美观之外也能提升草鱼的出肉率

0:09:21.775,0:09:25.637
同时酸菜鱼水煮鱼也是以此类方法取肉

0:09:55.120,0:09:58.296
第四片鱼的时候取掉第一片鱼肉不要

0:09:58.296,0:10:01.368
然后以20至25度斜刀切至鱼皮处

0:10:01.602,0:10:04.117
右手拿刀切的时候用力必须均匀

0:10:04.420,0:10:05.980
这样鱼片才能够一致

0:10:06.020,0:10:08.540
同学们切记不能将鱼皮切断

0:10:08.580,0:10:11.151
否则断一刀就能废掉一整个菜

0:10:27.040,0:10:27.800
第五

0:10:28.000,0:10:29.742
我们再来复习切丝的技巧

0:10:30.016,0:10:33.549
切丝的时候尽量把每一片鱼肉实打实的贴在菜板上面

0:10:35.700,0:10:38.060
切完一片再拿另外一片下来切

0:10:38.310,0:10:40.384
偶尔断一两根属于正常现象

0:10:55.800,0:10:56.588
第六

0:10:56.785,0:10:58.760
抖粉之前必须将鱼肉清洗

0:10:58.800,0:11:00.493
且用毛巾将水分粘干

0:11:00.724,0:11:03.360
抖干淀粉的时候必须每一处都很均匀

0:11:03.540,0:11:06.110
鱼肉下锅炸之前不能有湿润的地方

0:11:06.200,0:11:08.070
否则下锅容易粘成一团

0:11:13.823,0:11:16.140
最后在淋汁的时候如果不赶时间的话

0:11:16.140,0:11:19.300
可以用小汤匙少量多次的淋在鱼上面

0:11:24.640,0:11:26.330
珊瑚鱼的技术总结完毕


```

**Comment by Hackerry** [comment]
认领

**Comment by Hackerry** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“珊瑚鱼”的终极做法，最完整全面的技术分享，期待同学们做出来！
Chef Wang teaches you: The ultimate guide for "Coral Fish" with very comprehensive technical tips.

简介
大家好，硬核厨房第二期来做个拿手菜“珊瑚鱼”，由于其成菜形状酷似珊瑚而得名，做法流程和松鼠鱼有异曲同工之妙，不过对刀工和油的掌控要求更高，所以想做此菜的朋友一定要多多研习此视频。如果哪位朋友在家做出来的话，请在此留言下告诉我，我会亲自点评，非常期待！
Hello everyone, in this second episode of "Hardcore Kitchen" I cooked my specialty - "Coral Fish". It gets its name for the coral-like shape. The procedure is very much like cooking "Squirrel Fish", but requires having more stringent knife skills and temperature control. Therefore, friends who want to succeed in making this dish must invest time in reviewing this video and practicing. If anyone make it at home, please tell me in the comment. I'll comment and judge myself. Looking forward to your final results!

字幕
0:00:00.283,0:00:00.811
哈喽 大家好
Hello, everyone.

0:00:00.831,0:00:01.440
我是王刚
I'm Wang Gang

0:00:01.440,0:00:03.480
本期视频我给大家分享一道拿手菜
In this video I want to share with you my specialty -

0:00:04.820,0:00:05.990
珊瑚鱼
"Coral Fish"

0:00:06.200,0:00:08.811
首先我们准备一条三斤左右的草鱼
First we get a ~3 Jin (1.5kg) grass carp

0:00:09.459,0:00:10.760
用刀拍晕鱼头之后
After hitting on its head and putting it into coma,

0:00:10.760,0:00:12.160
在颈部切上一刀
cut into its neck.

0:00:12.340,0:00:15.178
这一步的目的是切断草鱼的神经防止跳动
This step is to cut the nerves so that it doesn't flop

0:00:15.380,0:00:17.302
然后用小刀将鱼鳞刮干净
Then use a utility knife to scale the fish

0:00:21.451,0:00:23.420
鱼鳞刮干净之后剖开鱼肚
Cut open its belly

0:00:25.112,0:00:27.895
然后去除各种内脏和鱼鳃清洗干净备用
Then gut and gill the fish, and clean it up

0:00:34.274,0:00:35.834
下一步开始准备分解
Next we prepare to dissect the fish

0:00:36.286,0:00:39.122
将鱼从中间片开之后再按照步骤取下鱼肉
Slice the meat from the middle following these steps

0:00:39.637,0:00:42.500
同学们取鱼排的时候必须贴着肉往下滑
You must touch the bones and cut downwards

0:00:42.580,0:00:44.327
否则鱼肉不规则也无法切成
Otherwise the final fillet won't be regularly shaped,

0:00:44.327,0:00:45.863
长条完整的珊瑚
and unsuitable for the next step.

0:00:46.380,0:00:48.766
由于此菜不需要用到鱼头和鱼骨
Since we don't need the bones and head,

0:00:48.885,0:00:51.503
分解下来的鱼骨和鱼头可以安排煮汤
they can be used for later making soup.

0:01:12.400,0:01:14.127
下一步我们开始切珊瑚
Next we start cutting out the coral shape

0:01:14.520,0:01:17.040
首先我们斜刀切下第一片鱼肉不用
First we slant-cut the first piece and desert it

0:01:17.160,0:01:19.874
然后继续斜刀将鱼片间隔一厘米左右
Then continue slant-cutting at 1cm spaces,

0:01:20.000,0:01:21.180
切至鱼皮不断
and keep the fish skin intact.

0:01:21.306,0:01:23.700
鱼皮的厚度大约保持在三毫米左右
Fish skin is about 3mm thick

0:01:23.840,0:01:25.960
同学们切记不能片得低于三毫米
So be careful not to cut too much into that 3mm,

0:01:26.080,0:01:28.759
否则鱼片切丝或者上粉的时候容易抖断
or the whole slice can break in later steps.

0:01:29.030,0:01:31.160
然后我们看一下切好的成品
Let's take a look at the final shape

0:01:34.400,0:01:35.679
下一步开始切丝
Next we cut them into strips

0:01:36.438,0:01:39.020
这一步我们将鱼肉朝上放到菜板上面
We want to put the fish vertically on the chopping board in this step

0:01:39.775,0:01:43.397
然后一片一片翻过来用刀根部往外推切成细丝
Then flip each piece over and use the end of the cleaver to cut each piece into strips

0:01:43.660,0:01:46.100
同学们切记这一步至关重要
You must remember this step is crucial

0:01:46.100,0:01:48.542
必须是菜刀根部先着地往前滑
You must make the end of the cleaver touch the board first and then slide forward

0:01:48.641,0:01:50.980
刀角切下的位置必须顶着鱼皮
The rear side of the cleaver must touch the fish skin

0:01:51.088,0:01:53.482
这样切出来的珊瑚才够直观好看
This ensures the final "coral" looks real and appealing

0:01:53.728,0:01:56.906
还有一种方法是将鱼肉冰冻之后再用剪刀裁剪
Another method is to freeze the meat and cut with a pair of scissors

0:01:57.140,0:01:59.500
鱼肉冰冻后再裁剪到出成品
The whole freeze-and-cut process

0:01:59.500,0:02:00.900
大约需要四小时
can take about 4 hours.

0:02:01.140,0:02:02.780
由于时间比较慢
Considering the long hours spent,

0:02:02.780,0:02:04.059
所以已经淘汰
we've abandoned that method.

0:02:04.245,0:02:05.980
专业厨师按照此法改刀出品
Professional chefs now use this type of cutting

0:02:05.980,0:02:07.980
只需要15分钟即可上菜
It reduces the whole cooking and serving process to 15 minutes

0:02:08.120,0:02:09.596
下一步开始初加工
Next we pre-process the fish

0:02:09.829,0:02:12.473
首先我们将鱼肉放入清水中清洗干净
First we clean the meat with fresh water

0:02:12.781,0:02:16.255
这一步可以去除鱼肉之间残存的血水和细小的肉粒
This step is to remove blood in veins and wash away detached meat dices

0:02:17.410,0:02:19.480
清洗干净之后将鱼肉捞出
Then take it out

0:02:30.880,0:02:33.410
鱼肉捞出之后准备一张干净的毛巾
Get a clean towel

0:02:35.540,0:02:37.620
将鱼肉放到毛巾中折叠起来
Then wrap the meat inside

0:02:37.740,0:02:40.100
轻轻的挤压几下吸干多余的水分
and lightly squeeze out the water.

0:02:40.240,0:02:43.357
这一步的目的是方便下一步腌制吸收调料的味道
This step is to make it easy to later absorb the seasoning

0:02:43.620,0:02:45.450
下一步我们开始准备腌制
Next we start marinating

0:02:45.500,0:02:47.470
碗中加入食用盐一小勺
Add one small spoon of salt into a bowl

0:02:47.560,0:02:49.555
加入适量的黄酒搅拌均匀备用
and some huangjiu rice wine, and mix well.

0:02:49.800,0:02:52.024
没有黄酒的同学也可以用料酒代替
You can use Chinese cooking wine if you don't have huangjiu rice wine

0:02:55.315,0:02:57.816
然后将吸干水分的鱼肉腌制两分钟
Then marinate the meat for two minutes

0:02:58.040,0:02:59.760
同学们切记不能加胡椒粉
You must not add black pepper powder

0:03:00.000,0:03:01.600
否则成菜会有糊辣味
Otherwise the final dish will be hot and spicy

0:03:27.120,0:03:29.680
两分钟之后加入玉米淀粉一大碗拌匀
Two minutes later add a large bowl of corn starch and mix well

0:03:30.000,0:03:32.510
玉米淀粉可以控制鱼肉松软的口感
Corn starch can stiffen the soft fish meat

0:03:32.580,0:03:35.510
喜欢外酥内软的同学可以全程加玉米淀粉
If you like the "crispy outside tender inside" style, you can keep using corn starch for later steps

0:03:47.602,0:03:50.410
然后加入土豆淀粉一大碗均匀的拍上
Then add a large bowl of potato starch and cover the fish

0:03:50.554,0:03:53.252
这个过程必须拍到位不能放过每一个细节
You must not miss any corners

0:03:53.660,0:03:56.730
加土豆淀粉可以让鱼肉长时间的保持脆爽
Potato starch can keep the meat crisp and juicy

0:03:56.980,0:03:59.710
玉米和土豆淀粉的比例大概为3:7
The corn starch to potato starch ratio is about 3:7

0:04:10.543,0:04:12.290
下一步开始调碗汁
Next we prepare the sauce

0:04:12.720,0:04:15.070
碗中加入番茄酱300克
Add 300g tomato sauce to a bowl

0:04:16.660,0:04:18.153
加入白醋40克
Add 40g white vinegar

0:04:20.540,0:04:22.310
加入白糖120克
Add 120g white sugar

0:04:31.360,0:04:33.690
搅拌的中途再加入少许的食用盐
Add a little bit of salt while mixing

0:04:37.498,0:04:38.683
下一步开始制作
Next we start cooking

0:04:39.210,0:04:40.920
首先我们把锅烧热
First heat up the wok

0:04:40.920,0:04:42.532
锅烧热之后加入宽油（植物混合油）
Then add Kuan You (literally "broad oil")

0:04:42.907,0:04:44.421
 油量大约为五公斤
About 5kg

0:04:52.451,0:04:54.163
然后将油温烧至六成热
Then wait till oil temperature is about 180°C

0:05:00.778,0:05:03.448
油温六成热之后将鱼肉的淀粉稍微抖一下
When oil temperature is about 180°C, shake off excessive starch on the meat

0:05:10.410,0:05:12.060
双手拉着两边下锅炸
Hold both sides and fry

0:05:17.625,0:05:20.945
略微定型之后再放手将鱼肉下锅中小火炸三分钟
When the fish stiffen, put it in and fry 3 minutes

0:05:21.134,0:05:23.153
同学们火候的变化分两个阶段
There are two temperatures that we need to pay attention to:

0:05:23.320,0:05:25.151
下锅前两分钟小火略高（5成油温）
Two minutes before putting the fish in, we are at low heat.

0:05:25.400,0:05:26.814
油温大约150度
The oil temperature is about 150°C.

0:05:26.939,0:05:30.565
第二阶段在两分钟之后开一次中火将油温提升15度
The second temperature measure is at two minutes later. Now we raise the temperature by 15°C on middle heat.

0:05:46.065,0:05:48.637
三分钟之后将鱼肉捞出
Three minutes later, take out the fish

0:05:57.044,0:06:00.069
鱼肉炸好之后捞出将其堆叠摆盘即可
Arrange in a plate

0:06:00.069,0:06:02.202
刚捞出来的鱼肉非常的烫手
The meat is very hot

0:06:02.438,0:06:04.650
建议不抗烫的同学带防烫手套
You may want to wear some heat-insulating gloves

0:06:04.650,0:06:06.827
或者待其稍微冷却之后再操作
Or wait till it cools

0:06:15.220,0:06:18.267
宽油倒出之后再加入少许的底油开始烧汁
Empty the wok and add some base oil to make the sauce

0:06:20.122,0:06:22.421
然后直接将调好的番茄汁下锅
Then pour straight in the tomato-based sauce just made

0:06:35.080,0:06:37.928
中火烧滚之后再加入适量的清水稀释一下
Use middle heat and dilute it with some water when the sauce comes to a boil

0:06:43.146,0:06:44.764
再次烧开之后将锅离火
When the sauce boils again, remove from heat and

0:06:47.132,0:06:49.344
然后少量多次的加入水淀粉拌匀
add slurry little by little with mixing.

0:07:05.498,0:07:07.394
淀粉拌匀之后将其烧开
Then boil again

0:07:14.125,0:07:16.488
最后再加入少许的明油分两次加入
Finally add some Ming You (literally "oil for a shiny presence") twice

0:07:16.888,0:07:18.980
第一次加入的明油将其拌匀
Mix the first half well with the sauce

0:07:21.617,0:07:23.144
第二次加的明油不动
Leave the second half unstirred

0:07:24.152,0:07:27.280
料汁烧好之后直接出锅淋在炸好的鱼上面即可
Spread the sauce over the fish

0:07:27.420,0:07:30.090
最后可以撒上自己喜欢的点缀即可上菜
Finally add some herbs in complement and serve

0:07:39.125,0:07:42.317
一道口感酥脆味道酸甜的珊瑚鱼就制作完成
A crispy-tasting and sweet & sour "Coral Fish" is finished

0:07:54.488,0:07:55.767
下面开始技术总结
Now for the technical tips:

0:07:55.972,0:07:57.901
第一工具的选择
First, choice of knives

0:07:58.060,0:07:59.580
首先我们会用到三把刀
We need three knives:

0:07:59.580,0:08:02.576
分别是砍刀 小尖刀和片刀
they are cleaver, utility knife and slicing knife.

0:08:02.576,0:08:04.215
第一次使用的是砍刀
We used cleaver, at the start,

0:08:04.215,0:08:06.380
用于拍晕草鱼和开边剁骨
to hit grass carp and cut bones.

0:08:09.931,0:08:13.340
第二把是小尖刀用于刮鱼鳞和开膛破肚
Then we used utility knife to scale and gut the fish

0:08:20.392,0:08:21.740
第三把是片刀
The third knife we used was a slicing knife

0:08:21.780,0:08:23.420
此刀刀身宽薄长
It has long and narrow blade

0:08:23.460,0:08:25.060
用于片鱼和切丝
Suitable for slicing fish and cutting strips

0:08:26.720,0:08:27.440
第二
Second,

0:08:27.520,0:08:29.134
用砍刀横切整个鱼的时候
when separating the meat from the bone,

0:08:29.134,0:08:31.063
刀锋略朝下贴着鱼肉滑过
we need to point the knife blade slightly downward and slide across the bone.

0:08:31.354,0:08:33.243
这样可以留下绝大部分的鱼肉
This is to cleanly separate the meat from the bone

0:08:33.480,0:08:34.760
同时新手操作的时候
It may be easier for novices to

0:08:34.760,0:08:36.600
左手可以用毛巾垫着抓鱼
use a towel when holding the fish.

0:08:36.740,0:08:38.816
这样可以防止粘液滑手撞刀
To prevent slipping and accidentally cutting yourselves

0:08:49.766,0:08:51.340
此段演示错误的操作
This is an incorrect demonstration

0:08:51.460,0:08:52.596
由于刀锋朝下
The blade points downward,

0:08:52.940,0:08:54.708
且没有贴着鱼的脊骨取肉
but it doesn't touch the bone.

0:08:55.020,0:08:58.540
所以取下的鱼肉呈现不规则也不美观
So the final piece is not regular and not appealing

0:09:14.820,0:09:16.873
第三取鱼排的时候同样需要
Third, when making fish fillets out of a whole fish,

0:09:16.873,0:09:18.402
贴着排骨往下切
it's the same technique of pointing downward and cutting along the spine.

0:09:18.629,0:09:21.460
这样除了美观之外也能提升草鱼的出肉率
This makes the fillet looks nice and reduces waste

0:09:21.775,0:09:25.637
同时酸菜鱼水煮鱼也是以此类方法取肉
This technique can also be applied when making "Suan Cai Yu: (literally "Sour Vegetable Fish") and "Shui Zhu Yu" (literally "Water Boiled Fish")

0:09:55.120,0:09:58.296
第四片鱼的时候取掉第一片鱼肉不要
Forth, the first slant-cut piece of meat is deserted

0:09:58.296,0:10:01.368
然后以20至25度斜刀切至鱼皮处
Then slant-cut at an angle of 20 to 25 degrees until touching the skin

0:10:01.602,0:10:04.117
右手拿刀切的时候用力必须均匀
Keep a constant force on your right hand

0:10:04.420,0:10:05.980
这样鱼片才能够一致
so that the pieces are uniform.

0:10:06.020,0:10:08.540
同学们切记不能将鱼皮切断
You must not cut break the skin

0:10:08.580,0:10:11.151
否则断一刀就能废掉一整个菜
One wrong cut and the whole dish is wasted

0:10:27.040,0:10:27.800
第五
Fifth,

0:10:28.000,0:10:29.742
我们再来复习切丝的技巧
let's review some julienning techniques.

0:10:30.016,0:10:33.549
切丝的时候尽量把每一片鱼肉实打实的贴在菜板上面
Make sure each piece is indeed laid attached to the board

0:10:35.700,0:10:38.060
切完一片再拿另外一片下来切
Finish one piece and then continue to flip over the next one

0:10:38.310,0:10:40.384
偶尔断一两根属于正常现象
Breaking one or two strips during this process is normal

0:10:55.800,0:10:56.588
第六
Sixth,

0:10:56.785,0:10:58.760
抖粉之前必须将鱼肉清洗
Wash the meat thoroughly before covering with starch

0:10:58.800,0:11:00.493
且用毛巾将水分粘干
Use a towel to dry completely

0:11:00.724,0:11:03.360
抖干淀粉的时候必须每一处都很均匀
Starch must cover every part of the meat

0:11:03.540,0:11:06.110
鱼肉下锅炸之前不能有湿润的地方
There has to be no wet places

0:11:06.200,0:11:08.070
否则下锅容易粘成一团
Otherwise meat may become attached in a jumble

0:11:13.823,0:11:16.140
最后在淋汁的时候如果不赶时间的话
If there is no time constraints at the final step,

0:11:16.140,0:11:19.300
可以用小汤匙少量多次的淋在鱼上面
you can use a small spoon to fully spread the sauce.

0:11:24.640,0:11:26.330
珊瑚鱼的技术总结完毕
That's all for the technical tips
