### ISSUE TITLE
[雪鱼] 兰州牛肉面 - https://youtu.be/vtJugiIIFzM

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#1275]
**视频链接**：<https://youtu.be/vtJugiIIFzM>

# 请翻译以下全部内容

```

字幕
<1
00:00:01,920 --> 00:00:07,520
甘肃·兰州

2
00:00:28,680 --> 00:00:32,280
雪鱼现在在兰州 来兰州怎么能不吃牛兰州拉面呢

3
00:00:32,280 --> 00:00:34,360
但是 你走在大街小巷上 你会发现

4
00:00:34,360 --> 00:00:36,960
他们的牌子上 没有一家写的是拉面馆

5
00:00:36,960 --> 00:00:39,680
而都是牛肉面

6
00:00:39,680 --> 00:00:42,400
接下来我将去后面的牛肉面馆 看一看

7
00:00:42,400 --> 00:00:45,720
兰州的牛肉面 和我以前吃的有什么不同

8
00:01:06,900 --> 00:01:08,900
牛肉面 8块钱一碗

9
00:01:12,600 --> 00:01:16,240
你好 我要一碗牛肉面

10
00:01:18,160 --> 00:01:19,680
粗细 拌面的时候告诉他

11
00:01:19,680 --> 00:01:22,200
噢 好的 支付成功了

12
00:01:41,120 --> 00:01:44,320
看我后面这一米大锅里 他们炖了好多的牛肉

13
00:01:44,320 --> 00:01:47,720
这个汤就是待会牛肉面的底汤

14
00:01:47,720 --> 00:01:50,920
不过比起牛肉 我相信很多人和我一样

15
00:01:50,920 --> 00:01:54,720
更想知道的是 在兰州 这个面条是怎么做成的

16
00:01:54,720 --> 00:02:00,080
来 跟着我去拿面 这个过程就会看的明明白白

17
00:04:14,040 --> 00:04:18,440
他们这边的牛肉面 讲究是一清 二白 三红 四绿 五黄

18
00:04:18,440 --> 00:04:21,440
一清是指的 它的牛肉汤底很清

19
00:04:21,440 --> 00:04:23,680
二白呢 是萝卜片白

20
00:04:23,680 --> 00:04:25,520
三红就是辣子红

21
00:04:25,520 --> 00:04:28,920
四绿就是 蒜苗韭菜翠绿

22
00:04:28,920 --> 00:04:31,480
五黄是因为面条里面加了蓬灰

23
00:04:31,480 --> 00:04:34,400
所以呢 面条显示出微微的淡黄色

24
00:04:35,440 --> 00:04:38,600
我是没想到8块钱的牛肉面 是这么大的分量

25
00:04:38,600 --> 00:04:41,560
除了拉面之外呢 还要了一份酱牛肉

26
00:04:41,560 --> 00:04:43,760
这盘呢 就是牛腱子肉

27
00:04:43,760 --> 00:04:45,240
此外呢 还加了一个卤蛋

28
00:04:45,240 --> 00:04:48,320
在当地 这个就叫 肉蛋双飞

29
00:04:56,400 --> 00:05:00,800
这样的红油辣子 看起来都是很有食欲的

30
00:05:12,000 --> 00:05:16,000
这个面无敌 吃一口实在是太香了

31
00:05:16,000 --> 00:05:18,960
面条并没有想象当中的 很有嚼头

32
00:05:18,960 --> 00:05:20,760
反而是咬一口 很容易咬断

33
00:05:20,760 --> 00:05:24,640
吃的时候 你会觉得汤头浓郁 辣子香

34
00:05:26,080 --> 00:05:28,800
你看 在这边吃了这么久 我都替你们尝了

35
00:05:28,800 --> 00:05:31,520
这边的辣子 虽然说 看起来 惊心动魄

36
00:05:31,520 --> 00:05:34,960
但是一点都不辣 而是增加了这种香味

37
00:05:51,960 --> 00:05:55,240
不过这半天 我们只看到了面条

38
00:05:55,240 --> 00:05:58,040
牛肉面 不应该有肉吗

39
00:06:00,600 --> 00:06:05,440
找一找 有没有牛受的皮外伤的肉

40
00:06:07,760 --> 00:06:11,760
看来就是一碗8块钱的牛肉面 是没有牛肉的

41
00:06:11,760 --> 00:06:14,320
如果说 想吃牛肉就是得另加

42
00:06:14,320 --> 00:06:19,320
要不呢 就是要酱牛肉 要不呢就是 要牛腱子肉

43
00:06:19,320 --> 00:06:23,400
酱牛肉：80块钱一斤
牛腱子肉：90块钱一斤

44
00:06:23,400 --> 00:06:28,400
吃的时候呢 要一两就可以 一两就是一碟

45
00:06:32,600 --> 00:06:36,000
我现在要把它变成 豪华牛肉面

46
00:06:40,480 --> 00:06:44,120
一般来说 都是实物与图片不符

47
00:06:44,120 --> 00:06:47,760
现在我们来还原图片

48
00:06:49,200 --> 00:06:51,640
还有一个蛋

49
00:06:56,400 --> 00:06:59,760
现在就是肉 蛋 面齐飞

50
00:07:00,440 --> 00:07:02,440
我已经把肉盖住了面

51
00:07:02,440 --> 00:07:05,920
我觉得在座的各位的牛肉面 都没有我的豪华

52
00:07:05,920 --> 00:07:10,160
它是8块钱 9块钱 加上原来的8块钱

53
00:07:10,160 --> 00:07:15,480
再加上一个蛋 一共是27块钱的牛肉面

54
00:07:16,160 --> 00:07:19,600
肉多也不是什么好事 挡住我吃面了

55
00:07:23,040 --> 00:07:25,680
这句话好像是在炫耀

56
00:07:27,400 --> 00:07:30,760
他们这边的面条 粗细是分很多种规格的

57
00:07:30,760 --> 00:07:34,280
你想要哪种粗细 一定要在点面的时候告诉他

58
00:07:34,520 --> 00:07:37,840
像我点面的时候 就是直接问的 要粗的还是要细的

59
00:07:37,840 --> 00:07:40,120
我说要细的 默认就是二细

60
00:07:40,120 --> 00:07:43,400
我后面的 还有的人点了韭叶宽 还有毛细

61
00:07:43,400 --> 00:07:46,920
你想要什么样规格的 师傅都能给你拉出来

62
00:07:57,720 --> 00:07:59,640
你看做拉面的小哥是很精瘦的

63
00:07:59,640 --> 00:08:02,600
我本来以为 他应该是那种大块头

64
00:08:02,600 --> 00:08:06,040
有这种大力气的人才能够拉得动那么长的面

65
00:08:06,040 --> 00:08:09,480
但实际上 做面的是一个比较精瘦的小哥

66
00:08:09,480 --> 00:08:13,960
他一直示意我们 过来拍啊 拍啊 表现欲很强

67
00:08:52,920 --> 00:08:54,760
在兰州有句玩笑话叫

68
00:08:54,760 --> 00:08:56,560
兰州人 一天卖出的牛肉面

69
00:08:56,560 --> 00:08:59,240
能够把地球绕成一个毛线团子

70
00:08:59,240 --> 00:09:02,280
销量如此巨大 本地人的生活离不开它

71
00:09:02,280 --> 00:09:07,640
外地的朋友来到兰州 也一定会尝尝这碗面的味道

72
00:09:24,120 --> 00:09:26,720
吃完牛肉面 到黄河第一桥来看一看

73
00:09:27,000 --> 00:09:29,600
中山桥呢 是黄河上修建最早的铁桥

74
00:09:29,600 --> 00:09:32,200
素有 天下黄河第一桥 的美称

75
00:09:32,240 --> 00:09:35,920
在没有修建它之前 想跨越黄河 是件很困难的事情

76
00:09:35,920 --> 00:09:38,760
修建之后 不仅方便了两岸的经济生活

77
00:09:38,760 --> 00:09:42,160
也加强了兰州和西北地区的交流

78
00:10:02,920 --> 00:10:06,280
关  注
雪 鱼  探 店

>
```

**Comment by Kevinzheng5** [comment]
认领

**Comment by Kevinzheng5** [comment]
字幕
<1
00:00:01,920 --> 00:00:07,520
甘肃·兰州
Lanzhou, Gansu Province

2
00:00:28,680 --> 00:00:32,280
雪鱼现在在兰州 来兰州怎么能不吃牛兰州拉面呢
I’m in Lanzhou now and how can we skip the Lanzhou beef noodles

3
00:00:32,280 --> 00:00:34,360
但是 你走在大街小巷上 你会发现
I found an interesting fact walking on the streets

4
00:00:34,360 --> 00:00:36,960
他们的牌子上 没有一家写的是拉面馆
None of their signs say ramen

5
00:00:36,960 --> 00:00:39,680
而都是牛肉面
They all say beef noodles

6
00:00:39,680 --> 00:00:42,400
接下来我将去后面的牛肉面馆 看一看
Let’s have a look in this beef noodles restaurant behind 

7
00:00:42,400 --> 00:00:45,720
兰州的牛肉面 和我以前吃的有什么不同
What is different in Lanzhou’s beef noodles

8
00:01:06,900 --> 00:01:08,900
牛肉面 8块钱一碗
Beef noodles are 8 yuan per bowl

9
00:01:12,600 --> 00:01:16,240
你好 我要一碗牛肉面
Hi, I’d like a bowl of beef noodles

10
00:01:18,160 --> 00:01:19,680
粗细 拌面的时候告诉他
Teel the staff how wide would you like the noodles

11
00:01:19,680 --> 00:01:22,200
噢 好的 支付成功了
OK paid

12
00:01:41,120 --> 00:01:44,320
看我后面这一米大锅里 他们炖了好多的牛肉
They are stewing so much beef in the meter-round pot behind me

13
00:01:44,320 --> 00:01:47,720
这个汤就是待会牛肉面的底汤
The soup will be the base for the beef noodles

14
00:01:47,720 --> 00:01:50,920
不过比起牛肉 我相信很多人和我一样
But I believe lots of people like myself are more interested in how they make the noodles

15
00:01:50,920 --> 00:01:54,720
更想知道的是 在兰州 这个面条是怎么做成的
Especially how they make them here in Lanzhou

16
00:01:54,720 --> 00:02:00,080
来 跟着我去拿面 这个过程就会看的明明白白
Come with me to get the noodles and let’s see

17
00:04:14,040 --> 00:04:18,440
他们这边的牛肉面 讲究是一清 二白 三红 四绿 五黄
The standard for the beef noodles here are: clear, white, red, green and yellow

18
00:04:18,440 --> 00:04:21,440
一清是指的 它的牛肉汤底很清
First the soup base needs to be clear

19
00:04:21,440 --> 00:04:23,680
二白呢 是萝卜片白
Secondly, the radish slices are white

20
00:04:23,680 --> 00:04:25,520
三红就是辣子红
Thirdly, the chili oil is red

21
00:04:25,520 --> 00:04:28,920
四绿就是 蒜苗韭菜翠绿
Fourthly, the garlic greens and chives are green

22
00:04:28,920 --> 00:04:31,480
五黄是因为面条里面加了蓬灰
Finally, the noodles are yellow because of the baking soda in them

23
00:04:31,480 --> 00:04:34,400
所以呢 面条显示出微微的淡黄色
So that the noodles are a little yellow

24
00:04:35,440 --> 00:04:38,600
我是没想到8块钱的牛肉面 是这么大的分量
I didn’t expect such big portion size for the 8 yuan price

25
00:04:38,600 --> 00:04:41,560
除了拉面之外呢 还要了一份酱牛肉
I also ordered some spiced beef besides the noodles

26
00:04:41,560 --> 00:04:43,760
这盘呢 就是牛腱子肉
This plate is the beef shank meat

27
00:04:43,760 --> 00:04:45,240
此外呢 还加了一个卤蛋
Also a spiced egg

28
00:04:45,240 --> 00:04:48,320
在当地 这个就叫 肉蛋双飞
It’s called the protein bomb here

29
00:04:56,400 --> 00:05:00,800
这样的红油辣子 看起来都是很有食欲的
The chili oil seems so appetizing

30
00:05:12,000 --> 00:05:16,000
这个面无敌 吃一口实在是太香了
The aroma is just amazing

31
00:05:16,000 --> 00:05:18,960
面条并没有想象当中的 很有嚼头
The noodles are not as al dente as I expected 

32
00:05:18,960 --> 00:05:20,760
反而是咬一口 很容易咬断
It’s very easy to bite

33
00:05:20,760 --> 00:05:24,640
吃的时候 你会觉得汤头浓郁 辣子香
The soup is really rich and the chili oil is so savory

34
00:05:26,080 --> 00:05:28,800
你看 在这边吃了这么久 我都替你们尝了
Based on lots of food tasting in this trip

35
00:05:28,800 --> 00:05:31,520
这边的辣子 虽然说 看起来 惊心动魄
The chili oil here seems very spicy

36
00:05:31,520 --> 00:05:34,960
但是一点都不辣 而是增加了这种香味
But it’s not hot at all. It only adds the aroma

37
00:05:51,960 --> 00:05:55,240
不过这半天 我们只看到了面条
We only saw noodles till now

38
00:05:55,240 --> 00:05:58,040
牛肉面 不应该有肉吗
Shouldn’t the beef noodles come with beef?

39
00:06:00,600 --> 00:06:05,440
找一找 有没有牛受的皮外伤的肉
Let’s see whether we can even find some beef grain

40
00:06:07,760 --> 00:06:11,760
看来就是一碗8块钱的牛肉面 是没有牛肉的
It seems that the 8 yuan beef noodles don’t have beef

41
00:06:11,760 --> 00:06:14,320
如果说 想吃牛肉就是得另加
If you want beef with it, you have to order specifically

42
00:06:14,320 --> 00:06:19,320
要不呢 就是要酱牛肉 要不呢就是 要牛腱子肉
Or you can have the spiced beef or shank meat

43
00:06:19,320 --> 00:06:23,400
酱牛肉：80块钱一斤
牛腱子肉：90块钱一斤
The spiced beef and shank meat are 80 and 90 yuan per jin (500 grams), respectively

44
00:06:23,400 --> 00:06:28,400
吃的时候呢 要一两就可以 一两就是一碟
You can order one liang (50 grams) and that’s one small plate

45
00:06:32,600 --> 00:06:36,000
我现在要把它变成 豪华牛肉面
Now let’s turn our noodles into the deluxe version 

46
00:06:40,480 --> 00:06:44,120
一般来说 都是实物与图片不符
Usually the food doesn’t seem the same from the ads

47
00:06:44,120 --> 00:06:47,760
现在我们来还原图片
Now let’s get the ad version

48
00:06:49,200 --> 00:06:51,640
还有一个蛋
One more egg

49
00:06:56,400 --> 00:06:59,760
现在就是肉 蛋 面齐飞
Right now it’s the protein bomb with the carbohydrate bomb

50
00:07:00,440 --> 00:07:02,440
我已经把肉盖住了面
The meat can cover the noodles

51
00:07:02,440 --> 00:07:05,920
我觉得在座的各位的牛肉面 都没有我的豪华
My noodles are the most luxury than everybody else’s here

52
00:07:05,920 --> 00:07:10,160
它是8块钱 9块钱 加上原来的8块钱
It’s 8 plus 9 plus 8 yuan

53
00:07:10,160 --> 00:07:15,480
再加上一个蛋 一共是27块钱的牛肉面
Also with the egg, this bowl of beef noodles is 27 yuan in total

54
00:07:16,160 --> 00:07:19,600
肉多也不是什么好事 挡住我吃面了
The only downside of this much meat is I can’t reach the noodles now

55
00:07:23,040 --> 00:07:25,680
这句话好像是在炫耀
Sounds like bragging though

56
00:07:27,400 --> 00:07:30,760
他们这边的面条 粗细是分很多种规格的
There’s a lot of sizes for noodles here

57
00:07:30,760 --> 00:07:34,280
你想要哪种粗细 一定要在点面的时候告诉他
You need to tell them how wide you like your noodles when you order

58
00:07:34,520 --> 00:07:37,840
像我点面的时候 就是直接问的 要粗的还是要细的
They only asked me wide or fine when I ordered

59
00:07:37,840 --> 00:07:40,120
我说要细的 默认就是二细
I said fine and it went second fine by default

60
00:07:40,120 --> 00:07:43,400
我后面的 还有的人点了韭叶宽 还有毛细
Guys behind me ordered chive wide and hair fine

61
00:07:43,400 --> 00:07:46,920
你想要什么样规格的 师傅都能给你拉出来
The cook can make you any size you want 

62
00:07:57,720 --> 00:07:59,640
你看做拉面的小哥是很精瘦的
The cooks seem pretty lean

63
00:07:59,640 --> 00:08:02,600
我本来以为 他应该是那种大块头
I thought they would be big

64
00:08:02,600 --> 00:08:06,040
有这种大力气的人才能够拉得动那么长的面
So that they have enough strength to pull the big doughs

65
00:08:06,040 --> 00:08:09,480
但实际上 做面的是一个比较精瘦的小哥
But actually he is pretty lean

66
00:08:09,480 --> 00:08:13,960
他一直示意我们 过来拍啊 拍啊 表现欲很强
He was constantly telling us to come around and shoot, pretty outgoing

67
00:08:52,920 --> 00:08:54,760
在兰州有句玩笑话叫
There is a local saying

68
00:08:54,760 --> 00:08:56,560
兰州人 一天卖出的牛肉面
The beef noodles sold in Lanzhou in one day

69
00:08:56,560 --> 00:08:59,240
能够把地球绕成一个毛线团子
Can twine the earth into a woolen ball

70
00:08:59,240 --> 00:09:02,280
销量如此巨大 本地人的生活离不开它
The sales are huge and the locals cannot live without it

71
00:09:02,280 --> 00:09:07,640
外地的朋友来到兰州 也一定会尝尝这碗面的味道
Tourists in Lanzhou also will definitely come and taste

72
00:09:24,120 --> 00:09:26,720
吃完牛肉面 到黄河第一桥来看一看
After the beef noodles, let’s see the first Yellow River bridge

73
00:09:27,000 --> 00:09:29,600
中山桥呢 是黄河上修建最早的铁桥
The Zhongshan bridge is the first bridge built across Yellow River

74
00:09:29,600 --> 00:09:32,200
素有 天下黄河第一桥 的美称
So it’s called the first Yellow River bridge

75
00:09:32,240 --> 00:09:35,920
在没有修建它之前 想跨越黄河 是件很困难的事情
It was very difficult to go across yellow river before building it

76
00:09:35,920 --> 00:09:38,760
修建之后 不仅方便了两岸的经济生活
The building of the bridge not only make the people’s lives more convenient

77
00:09:38,760 --> 00:09:42,160
也加强了兰州和西北地区的交流
It also strengthens the communications between Lanzhou and the Northwestern China

78
00:10:02,920 --> 00:10:06,280
关  注
雪 鱼  探 店
Subscribe please 
>
