### ISSUE TITLE
[华农兄弟] 华农兄弟挖点五指毛桃抓只老母鸡来煲汤又香又好吃 - https://youtu.be/uq-xI3Dqj6U

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1284]
https://youtu.be/uq-xI3Dqj6U
<p>&#35270;&#39057;&#21457;&#24067;&#20110; July 14, 2020 at 01:26PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/uq-xI3Dqj6U

#华农兄弟：挖点五指毛桃，抓只老母鸡来煲汤，又香又好吃
#Huanong Brothers: We dig some hairy figs. Make a soup with a chicken. Good smell, good taste!

0:00:00.000,0:00:02.540
# 大家好  今天去挖點那個五指毛桃來
Hi everyone! Today we're gonna pick some, well, some hairy figs (roots).

0:00:02.540,0:00:03.920
# 用來煲那個  雞湯
to make a, a chicken soup.

0:00:04.540,0:00:06.380
# 就在後山  後山這裡很多的
Right on our hill, on our hill, there are a lot.

0:00:07.540,0:00:08.740
# 拿這個小鋤頭子來
I'm going with this little pickax.

0:00:11.220,0:00:13.100
# 這裡上 危險啊
This way up. It's dangerous.

0:00:24.260,0:00:25.580
# 你看  這條路
Look! This path,

0:00:26.260,0:00:28.180
# 很久都沒來上山砍竹子啦
it has been a long time since my last time here for the bamboos.

0:00:29.320,0:00:31.140
# 這裡現在到處都長滿了野草
Now the weed is growing everywhere.

0:00:40.220,0:00:42.580
# 你看  這個就是五指毛桃啦  (註︰這個「就」字英文似乎沒有很好的翻譯，唯有寫得清楚一點)
Look! This is what we're looking for, hairy fig.

0:00:43.580,0:00:47.420
# 找了那麼遠  至少找了一兩公里才把它找上來
It's such a long way! We've been searching for at least a kilometre or two along the path before reaching it.

0:00:49.280,0:00:49.880
# 砍掉
Chop it down!

0:00:50.640,0:00:51.280
# 這個不要了
We don't need this part.

0:00:52.660,0:00:53.720
# 只要挖這個根
We only need to dig out the root,

0:00:54.580,0:00:55.300
# 就可以啦
and that's it.

0:01:00.000,0:01:00.780
# 你看  這個
Look! Here it is.

0:01:01.300,0:01:02.480
# 要把它的根挖出來
We gotta dig out the root.

0:01:03.460,0:01:04.280
# 這根才是
It's the root,

0:01:05.100,0:01:05.920
# 最主要的
which matters.

0:01:10.520,0:01:12.500
# 這個  太小啦  這個根
This one, is too small, this root.

0:01:21.180,0:01:21.860
# 你看
Look!

0:01:22.320,0:01:23.920
# 那麼小就被我挖回去啦
So I've dug it out though it's so small.

0:01:24.920,0:01:26.120
# 沒辦法  就找到你
I've no choice. You're the only one here.

0:01:27.640,0:01:28.280
# 這兩根
These two...

0:01:29.140,0:01:30.040
# 這裡還有一根
Here's one more.

0:01:30.940,0:01:31.620
# 那麼小
It's so small.

0:01:32.580,0:01:33.400
# 那麼小也是
But size doesn't matter.

0:01:39.680,0:01:41.460
# 你看  這個還是條老根
Look! This is an old root, in fact.

0:01:42.560,0:01:44.800
# 找到條老根  粗粗的
Got an old root, it's rather thick.

0:01:46.100,0:01:46.640
# 看到沒有
See?

0:01:47.660,0:01:48.280
# 這個就是
Here it is.

0:01:49.340,0:01:50.720
# 根拉不起來就不要啦
I leave it alone. I can't pull out the root.

0:01:52.120,0:01:53.340
# 就搞這根就行了
I'll have just this one.

0:01:53.960,0:01:55.620
# 這裡也有一棵哦  這裡
Here's one more, here.

0:02:01.820,0:02:02.500
# 你看
Look!

0:02:03.440,0:02:04.860
# 五指  五指毛桃
Hairy, hairy figs

0:02:08.440,0:02:09.620
# 這個好深啊  這個
It goes very deep, this one.

0:02:15.060,0:02:17.380
# 你看  終於拔起來啦
Look! I've dug it out finally.

0:02:18.280,0:02:18.980
# 它這個
This one...

0:02:19.940,0:02:21.380
# 它上面還有一棵  我看到
There's another one up there. I saw it.

0:02:29.080,0:02:29.700
# 你看
Look!

0:02:30.320,0:02:32.960
# 這是野生的黃花倒水蓮哦
This is wild "huang hua dau shui lian" (a type of herbal leaf).

0:02:34.120,0:02:35.080
# 我們土話叫
In our local dialect here, it's called,

0:02:35.820,0:02:36.460
# 鴨腳木
duck feet wood,

0:02:36.820,0:02:37.420
# 鴨腳
duck feet,

0:02:38.820,0:02:41.180
# 鴨腳樹  叫鴨腳樹還是
duck feet tree. Is it duck feet tree or?

0:02:42.480,0:02:44.920
# 它這個是用來  也  好像也可厶用來那個
This is used for, like, it seems that it can be, you know...

0:02:47.280,0:02:49.380
# 不知道用來幹嘛的  反正  老人家
No ideas what it's for. Anyway, the elderlies,

0:02:49.780,0:02:51.680
# 經常  經常說這個很珍貴
always, always say that it's rare.

0:02:53.540,0:02:55.420
# 先不要破壞它的  生態
Let's not destroy its, ecosystem.

0:02:55.980,0:02:57.080
# 讓它長高高
Instead we let it grow and grow well,

0:02:57.960,0:02:58.820
# 長高一點
and be a tall nice plant.

0:02:59.580,0:03:03.940
# 你看它的  小小黃花  像不像那個小鴨子
Have a look at its little, little yellow flowers? Do they look like the little duckies?

0:03:08.720,0:03:10.020
# 再去下  往下面去
Let's go down, down further,

0:03:10.960,0:03:12.100
# 看下有沒有
and see if there are any more.

0:03:14.040,0:03:15.500
# 這邊 上面都沒有了
Here are, no more up there.

0:03:17.100,0:03:19.400
# 你看  這還有一個  一指毛桃 (註︰這個有點麻煩，五指毛桃的五指是指葉上有五個指狀的葉冠，但這棵的葉只有一個，但這個「指」的概念沒有在英文名字中表達出來)
Look! This leaf has just one, one lobe.

0:03:19.760,0:03:21.680
# 就長了一個指  一個指出來的
It has just one, one lobe.

0:03:22.080,0:03:23.100
# 這個也可以用
This is also fine.

0:03:24.180,0:03:26.460
# 有五指的不夠  用一指的來湊
There are not enough five-lobe ones (the normal ones). This can fill the gap.

0:03:38.980,0:03:40.280
# 啊  這個
Ah! This is,

0:03:40.760,0:03:41.800
# 這一根還
this one is still...

0:03:43.540,0:03:44.900
# 就長了那麼一點
It's just a little bit here.

0:03:49.060,0:03:53.300
# 這一棵  腐爛的木頭  壓在這裡
This one, a rotten wood, is pressing on it.

0:04:01.660,0:04:02.500
# 這一棵
This one...

0:04:08.000,0:04:10.340
# 逃的脫 逃的脫我的掌心
You think you can escape, escape from my hand?

0:04:10.980,0:04:13.600
# 那麼小根  扯  扯起來
It's so small. I pull, pull it out.

0:04:17.700,0:04:20.120
# 差不多啦  看路邊上還有沒有
It's almost there. Let's see if there are any more on the sides of the path.

0:04:20.720,0:04:21.720
# 再挖幾個就夠啦
I just need a few more.

0:04:25.440,0:04:26.820
# 你看  這裡有一棵哦
Look! Here's one!

0:04:44.240,0:04:47.020
# 一定要用力挖  它這根好長啊  它這根
I gotta dig forcefully. Its root goes really deep, its root.

0:04:52.460,0:04:54.020
# 被我扯掉一棵下來
I've pulled off a piece.

0:05:00.400,0:05:01.360
# 你看  挖到啦
Look! Here it is!

0:05:02.860,0:05:03.660
# 就那一點點
It's just a tiny little bit here.

0:05:04.620,0:05:06.800
# 它一棵就一點點的  不是很多
There's never a lot, as each root is just a tiny little bit.

0:05:07.460,0:05:07.960
# 因為
Cuz,

0:05:08.600,0:05:10.580
# 不是種植的  種植的就很大棵
they're not cultivated. The cultivated ones are really big.

0:05:12.480,0:05:14.980
# 你看  差不多可以 煲一隻雞啦
Look! It's should be enough, enough for a chicken.

0:05:18.820,0:05:21.220
# 回去  洗一下 曬乾
Let's take it back, wash it and dry it under the sun.

0:05:22.060,0:05:23.660
# 明天就搞一隻雞來煲一下
I'll get a chicken and make a soup tomorrow.

0:05:33.620,0:05:35.880
# 你看  上次我們種的西瓜
Look! These are the watermelons that we planted last time.

0:05:36.820,0:05:38.440
# 好不容易結了一個起來哦
Finally, ultimately, we have one watermelon now.

0:05:39.180,0:05:41.020
# 你看這個西瓜  都長那麼大啦
Have a look at this watermelon. It's so big now.

0:05:42.980,0:05:45.340
# 下次來 等它熟了之後
I'll come again next time. When it's ripe,

0:05:46.060,0:05:47.300
# 我就把它摘來吃了
I'll pick it and finish it.

0:05:48.240,0:05:49.240
# 誰都不能摘啊
No one is allowed to pick it.

0:05:50.520,0:05:51.860
# 誰摘了我跟誰急
If anyone dares to pick it, I'll squabble with him, without any hesitation.

0:05:53.520,0:05:56.600
# 好不容易長了一個  全部都死完啦  就剩下這一棵樹
This is the last survivor. All others have died and only this one remains,

0:05:56.980,0:05:57.660
# 沒死的
and is still alive.

0:05:59.580,0:06:01.000
# 難得長一個瓜出來
It's an invaluable single watermelon.

0:06:02.160,0:06:03.980
# 每天都用那個有機肥
Everyday, I spray the, the organic fertiliser,

0:06:04.940,0:06:06.440
# 潑到那個  它根部
onto its, its root.

0:06:07.500,0:06:08.760
# 才能長出那麼好的
That's why it's growing so well.

0:06:10.260,0:06:11.900
# 要不然就長不了那麼好的
It wouldn't be growing so well otherwise.

0:06:17.280,0:06:19.320
# 這個就要洗一下  清洗一下
It needs to be washed, and cleansed.

0:06:28.860,0:06:31.980
# 差不多洗乾淨啦  洗乾淨還要曬一下的哦
It's almost done now. When it's cleaned, it needs to be dried under the sun, you know.

0:06:33.660,0:06:34.600
# 曬了才好吃
So it becomes much more tasty.

0:06:35.420,0:06:36.700
# 不曬就不夠香
The aroma is greatly reduced if it's not dried.

0:06:39.680,0:06:40.780
# 拿到這邊曬一下
I'll let it dry under the sun here.

0:06:41.920,0:06:44.460
# 要把這個曬一下  要曬乾來啦
It needs to be dried, dried under the sun first,

0:06:45.120,0:06:46.540
# 把裡面的水分  曬乾
to dry up all the moisture inside.

0:06:47.560,0:06:48.560
# 再用那個
And then we can,

0:06:48.900,0:06:53.340
# 大火去煲它  一煲湯的話  它就把裡面的香味釋放出來啦
cook it on high heat. Then in the soup, the aroma will be unlocked.

0:06:54.820,0:06:59.760
# 所以  如果想直接  直接煲也可以  那肯定沒那麼香的
So, it's alright if you wanna use it right, right away. But then the aroma is certainly affected.

0:07:00.680,0:07:03.300
# 來曬一下  曬乾來  明天去一隻雞來
Let's leave it here, dry it. We're gonna fetch a chicken tomorrow,

0:07:04.000,0:07:04.680
# 燉
and stew it!

0:07:06.700,0:07:09.580
# 你看  這個于指毛桃就已曬乾了哦
Look! The hairy figs (roots) are now dried.

0:07:09.800,0:07:13.140
# 就缺個雞啦  我去村裡面搞一個鴨子來
A chicken is what we need now. Let me go into the village, and get a duck.

0:07:13.500,0:07:14.860
# 哦  不是  搞一隻雞
Ah, no! Get a chicken

0:07:16.400,0:07:18.140
# 先放在這裡  我去搞隻雞來
Leave it here first. I'm gonna get a chicken.

0:07:18.720,0:07:22.800
# 我去上面那個村子  看一下  有沒有雞  搞一隻來
I'm going to the village up there and see, if there are any chicken. I'll get one there.

0:07:36.420,0:07:37.360
# 沒抓到
Missed

0:07:48.740,0:07:49.540
# 搞了一隻
So here's one.

0:07:53.860,0:07:56.840
# 好像這個有蛋的  我換一隻來  不要這個
It seems that it has eggs. I'm not taking it. I'll take another one.

0:08:09.880,0:08:11.180
# 我一下它有沒有蛋
Let me feel if it has any eggs.

0:08:12.820,0:08:14.460
# 這個沒蛋  就這個
No eggs. Then this one

0:08:18.320,0:08:21.560
# 你看  這固公雞  它是以前廠裡面拿上來的哦
Look! This rooster, it was taken here from our site, you know.

0:08:22.020,0:08:24.240
# 要不然都被那個小黑咬 咬死啦
Otherwise Blacky would have bitten, bitten it to death.

0:08:26.880,0:08:28.120
# 活的最久的一隻
This rooster has the longest live.

0:08:37.840,0:08:40.060
# 不叫的  它現在都是
It doesn't yelp. It's now,

0:08:41.780,0:08:45.140
# 一身都是  紅毛  紅光發亮
covered with red feather, shiny red feather.

0:08:47.420,0:08:49.260
# 說明它的日子過得很不錯哦
It's an evidence of its joyful days here.

0:08:50.060,0:08:52.100
# 以前都很瘦的 在都那麼胖
It used to be very skinny, but it's so big now.

0:08:56.020,0:08:56.880
# 不叫了它
It's not yelping now.

0:08:59.460,0:09:00.880
# 你看  那麼肥啦它
Look! It's so big now.

0:09:07.060,0:09:11.820
# 你看  這個魚塘  在有草魚啦  放了  幾十條草魚下去
Look! In this pond, there are grass carps now. We've put dozens of grass carps into the pond.

0:09:14.160,0:09:15.560
# 到時候就可以去撈啦
We can catch them later.

0:09:18.260,0:09:20.460
# 還有其他魚的 還有鯽休放了好多下去
There are also other fish, We've put a lot of "ji yu" (local carps) too.

0:09:21.860,0:09:23.240
# 每天割點草給它吃
We feed them with grass every day.

0:09:25.680,0:09:26.640
# 長得很快的
They grow really fast.

0:09:27.800,0:09:29.000
# 好啦  先回去啦
Alright! Let go back first.

0:09:35.840,0:09:37.720
# 來來來來來  有骨頭吃啦
Come here, come here, come here! I have bones for you.

0:09:40.520,0:09:41.600
# 骨頭你們都不要
Are you sure that you don't want bones?

0:09:50.140,0:09:51.100
# 我燒點開水
Let me boil some water.

0:09:59.480,0:10:03.380
# 你看  這個雞  雪白雪白的
Look! This chicken, is snowy white.

0:10:05.580,0:10:06.380
# 很靚吧
Beautiful, isn't it?

0:10:31.400,0:10:32.280
# 這一個小雞腿
Here's a tiny chicken leg.

0:11:04.800,0:11:05.940
# 打火機都不見啦
The lighter is gone.

0:11:13.320,0:11:14.740
# 很快  很快就著了
It glows, it glows in no time.

0:11:32.040,0:11:35.620
# 我先燒點開水  這開水燒燙來再放雞肉
Let me boil some water first. I'll put the chicken when the water boils.

0:11:40.040,0:11:41.860
# 兄弟  兄弟的打氣筒
My buddy's, my buddy's air pump.

0:11:42.760,0:11:45.240
# 用來這個  吹這個  這麼猛
I blow it, blow it here. It's so strong.

0:11:46.200,0:11:48.200
# 很好用的哦 從這邊吹
It's pretty nice. I blow on this side.

0:11:49.160,0:11:50.820
# 誒呦 反過來吹
Ayo! Wrong side

0:11:52.160,0:11:54.200
# 剛好拿腳趾  腳趾插進去
It just fits, fits my toe here.

0:12:00.440,0:12:02.980
# 火旺啦這樣 你看  那邊  誒呀
The fire is getting strong here, look, on that side. Aya!

0:12:04.540,0:12:06.420
# 沒燒掉  可  可以啦
It's not burnt. Al, alright now!

0:12:07.380,0:12:09.840
# 放點生薑下去  生薑可以這樣
I put some ginger. The ginger can be, like,

0:12:10.340,0:12:12.180
# 兩個生薑這樣一捏就可以
crush the two gingers together. Done!

0:12:13.440,0:12:14.840
# 就碎掉啦  你看
So it's smashed. Look!

0:12:15.920,0:12:16.660
# 這個碎了
It's smashed.

0:12:20.660,0:12:21.440
# 這個捏不碎
I couldn't smash it.

0:12:22.780,0:12:23.700
# 哎 可以啦
Ay! It's alright now!

0:12:26.500,0:12:28.260
# 生薑放下去接下來就是雞肉
When the ginger is there, next, the chicken.

0:12:28.760,0:12:30.040
# 這雞肉也放下去
I put the chicken as well.

0:12:30.440,0:12:31.200
# 水下夠
Not enough water

0:12:37.140,0:12:38.440
# 再加點山泉水
Let me add some spring water.

0:12:42.920,0:12:44.400
# 把這個五指毛桃也放下去
I now put the hairy fig into the wok,

0:12:45.580,0:12:46.640
# 全部一起放下去
put them all into the wok.

0:12:55.700,0:12:58.080
# 就這樣大火燒它 一直燒
So here it is. Keep it cooking, on high heat.

0:13:00.140,0:13:00.940
# 一直燒
Keep it cooking,

0:13:02.400,0:13:03.760
# 燒到它沒火為止
until the fire goes off.

0:13:09.320,0:13:10.500
# 來  慢慢燒
Alright! Leave it cooking,

0:13:12.320,0:13:13.180
# 煮一個小時
for an hour.

0:13:14.360,0:13:16.120
# 就夠啦  它這老母雞來的
And that's it. This is an old hen.

0:13:22.400,0:13:24.140
# 你看  這個知了哦
Look! This is a cicada.

0:13:24.440,0:13:25.960
# 它飛到我身上來的
It lands on me.

0:13:26.840,0:13:28.560
# 都不知道怎麼回事你看
Who knows what happened. Look!

0:13:30.100,0:13:30.780
# 可能想
I think it may want to,

0:13:32.220,0:13:33.620
# 想跟大家見個面
want to say hi to everyone.

0:13:35.120,0:13:38.020
# 它 震動 震動那麼厲害
It's shaking, shaking so forcefully.

0:13:41.240,0:13:41.780
# 還動
It's still moving.

0:13:42.440,0:13:43.040
# 動不了哦
Now it stops.

0:13:46.480,0:13:48.680
# 還小的時候我們經常抓來玩
We always played with these bugs when we were small.

0:13:49.220,0:13:50.900
# 這樣一捏它就會
Here, if you squeeze it, it will...

0:13:52.460,0:13:55.160
# 它是從這個發聲的  它這裡有個聲帶
The sound is coming from here. Here's a vocal cord.

0:13:55.640,0:13:57.500
# 我一捏它帶 誒
If I squeeze its vocal cord...ay!

0:13:59.500,0:14:00.500
# 你看  啞了吧
Look! It's now dumb, isn't it?

0:14:03.780,0:14:04.440
# 就在這裡
It's right here.

0:14:05.320,0:14:07.180
# 它還小的時候是可以吃的  那個知了
It's edible when it was small, the cicada.

0:14:07.540,0:14:08.260
# 特別好吃
It's really tasty.

0:14:08.760,0:14:09.700
# 現在都老了
But it's old now.

0:14:10.460,0:14:11.420
# 我又不吃你
I'm not eating you.

0:14:12.460,0:14:13.320
# 不好吃
You're not tasty.

0:14:13.620,0:14:14.720
# 老了又不能吃了
The old ones are not edible.

0:14:15.900,0:14:16.980
# 現在你自由啦
You're free now.

0:14:17.760,0:14:18.360
# 飛吧
Fly!

0:14:19.780,0:14:20.760
# 不走是不是
You're not leaving, are you?

0:14:21.340,0:14:22.880
# 你看 我跟它有感情了
Look! We have developed boding.

0:14:24.280,0:14:25.040
# 看見沒有
See?

0:14:26.860,0:14:28.740
# 是不是 它知道感恩
Is it, because it is grateful?

0:14:29.060,0:14:30.260
# 是我救了它哦
After all, I've saved its life.

0:14:31.660,0:14:32.920
# 誒呦  跑啦
Eyo? It runs away.

0:14:33.820,0:14:34.780
# 可以  放點鹽
Alright! Put some salt.

0:14:39.200,0:14:39.840
# 好啦
Alright!

0:14:43.540,0:14:44.040
# 你看
Look!

0:14:44.500,0:14:46.160
# 這白色的湯馬上就出來啦
The milky white soup is here immediately.

0:14:48.780,0:14:49.580
# 蓋好來
Cover it up,

0:14:50.260,0:14:50.940
# 繼續煲
and keep it cooking.

0:15:30.880,0:15:31.960
# 來 給你好吃的哦
Hey! I have some good food for you.

0:15:37.360,0:15:39.180
# 它不怎麼吃  吃一點點
It's not really eating. It eats just a tiny little bit.

0:15:43.320,0:15:45.000
# 哇  熟啦熟啦熟啦熟啦
Wa! It's done, it's done, done, done!

0:15:47.680,0:15:48.960
# 冒那麼大的煙
It's so smoky.

0:15:54.780,0:15:55.660
# 嘗一下
Let me have a try.

0:16:16.100,0:16:17.640
# 嗯  好吃
Um! Tasty!

0:16:22.900,0:16:24.820
# 老母雞哦  現在都燉爛啦
It's an old hen. And it's now soft and mushy.

0:16:28.900,0:16:30.760
# 可以可以可以  開鍋啦
Not bad, not bad. Let's get started!

0:16:38.020,0:16:38.520
# 嗯
Um!

0:16:39.160,0:16:39.940
# 拿個碗來
Let me take a bowl.

0:16:41.240,0:16:42.980
# 哇  好久 沒吃過這個雞肉啦
Wa! I haven't had chicken for a long time.

0:16:44.140,0:16:45.380
# 這個是老母雞
This is an old hen.

0:16:46.080,0:16:47.100
# 老母雞燉這個
Old hen boiled with, you know,

0:16:48.380,0:16:49.180
# 五指毛桃
hairy fig.

0:16:53.660,0:16:54.620
# 好香
It smells great.

0:16:59.620,0:17:02.420
# 燉了兩小時  母雞都燉熟啦
We've boiled it for two hours. And the hen is thoroughly cooked now.

0:17:09.180,0:17:11.280
# 好啦  今天的視頻就到這裡吧
Alright! The video ends here.

0:17:12.080,0:17:13.580
# 你看這些小狗  全部都看著我
These doggies, are all looking at me.
