### ISSUE TITLE
[华农兄弟] 胡椒羊 - https://youtu.be/x-67wErV1V4

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1289]
https://youtu.be/x-67wErV1V4
<p>&#35270;&#39057;&#21457;&#24067;&#20110; July 15, 2020 at 11:08PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
這個標題改得過份了....XD

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/x-67wErV1V4

#华农兄弟：跑掉的那只羊抓回来了，砍点野胡椒给它们吃
#Huanong Brothers: The escaped goat is caught. I chop some wild pepper to feed them.

0:00:00.000,0:00:04.000
# 你看這隻羊 早上被我扛回來了  抬回來的
Have a look at this goat. I brought it back this morning, I carried it back.

0:00:04.340,0:00:05.600
# 它不願意回來哦
In fact, it didn't wanna come back.

0:00:06.500,0:00:07.720
# 被我抬回來啦
So I carried it on my shoulder.

0:00:08.620,0:00:09.860
# 它很喜歡吃這個
It likes the,

0:00:10.500,0:00:12.700
# 野胡椒的 野  野胡椒的那葉子哦
the leaves, the leaves of the wild, wild pepper very much.

0:00:13.360,0:00:14.900
# 像草它都不喜歡吃
But it doesn't like the elephant grass that much.

0:00:14.900,0:00:16.000
# 山薑子
Wild ginger

0:00:16.860,0:00:18.620
# 我們這邊叫做山薑子
We call it wild ginger here.

0:00:22.740,0:00:25.500
# 吃那個  這個像草  紅像草它都不喜歡吃
It doesn't, elephant grass, the red elephant grass, it doesn't like it.

0:00:28.120,0:00:29.920
# 可能這個味道比較香
I think it's because it smells better.

0:00:40.840,0:00:43.020
# 我去搞一點  搞點在它窩裡面
Let's fetch some, fetch some into its lair.

0:00:44.620,0:00:45.840
# 搞點在它窩裡面
Let's fetch some into its lair.

0:00:46.680,0:00:48.280
# 讓它今天晚上吃個夠
So that it can have a big feast tonight.

0:00:54.960,0:00:57.140
# 你看  這個西瓜  那麼大啦
Have a look at this watermelon! It's so big now.

0:00:58.800,0:01:01.920
# 放在這裡  長大了再來搞  現在還小
Leave it here. I'll pick it, when it becomes big. Now it's still small.

0:01:11.320,0:01:12.720
# 好多刺啊這裡
It's very spiky here.

0:01:22.420,0:01:25.600
# 你看  這個  山胡椒
Look! This is, wild pepper.

0:01:27.880,0:01:28.800
# 就要這個葉子
We just need the leaves.

0:01:40.120,0:01:41.480
# 這個就夠它吃啦  這個
This is enough for it, here.

0:01:43.020,0:01:44.480
# 我從這裡扔下去就好了
Throw it down from here, that's it.

0:01:49.540,0:01:50.320
# 這個
The branches,

0:01:52.360,0:01:53.600
# 那樹枝不要的
I don't need the branches.

0:01:54.380,0:01:55.920
# 把尾巴砍掉就OK了
Cut off the tail and then it's okay.

0:01:56.340,0:01:57.780
# 它明年還會長葉子的
The leaves will still be growing next year.

0:02:05.940,0:02:07.500
# 我對那個羊多好啊
You see how well I treat the goats?

0:02:10.540,0:02:11.780
# 搞了七八條下去
So I've got seven or eight here.

0:02:12.840,0:02:14.000
# 我也現在也下去了
I'm also heading down as well.

0:02:17.100,0:02:19.480
# 這個陡坡要小心點  鴨都叫了
This steep slope, be a bit more careful. The ducks are yelping.

0:02:20.020,0:02:21.460
# 今天都忘記餵鴨了
I forgot to feed the ducks today.

0:02:23.700,0:02:24.740
# 這裡很陡的哦
It's really steep here.

0:02:36.580,0:02:37.080
# 你看
Look!

0:02:37.680,0:02:38.660
# 砍了那麼一點
So I've chopped a tiny little bit here.

0:02:39.160,0:02:41.040
# 給它們吃  看它們吃不吃的完
I'll feed them and see if they can finish it.

0:02:52.940,0:02:57.440
# 你看  剛拿下來  可能比較陌生  不怎麼喜歡吃
Look! I've just taken it here. I think it's not something quite new to them. So they don't really like it.

0:02:58.580,0:02:59.760
# 好啦 聞到味道啦
Good! They can smell it now.

0:03:07.600,0:03:12.000
# 還有那麼多它們又不想吃  剛才搞了一點它們又馬上在搶
They don't wanna eat when they see so much here. Whey were fighting over it when there was just a little.

0:03:13.520,0:03:14.860
# 它們兩個想打架
They wanted to start a fight.

0:03:18.460,0:03:19.300
# 別打架哦
No fighting here, got it?

0:03:20.980,0:03:22.200
# 打架你們就完了
If you fight, game over.

0:03:40.740,0:03:43.860
# 你看這個羊  它有些沒有角有些有角的
Have a look at the goats. Some have the horns while some don't.

0:03:43.860,0:03:48.440
# 你看這個就是沒角 同樣是母的  竟然它就有角它就沒角  (註︰「竟然」這個概念沒有直接翻譯，唯有把感覺寫出來)
Look! This one has no horns. They're both female, but this one has the horns but this one doesn't, strange.

0:03:50.400,0:03:53.120
# 可能它一個跟老媽姓 一個跟老爸姓
Perhaps one takes the name from its mum, and the other from its dad.
