### ISSUE TITLE
[华农兄弟] 华农兄弟有村民种羊角蜜我们都不知道摘一点来吃 - https://youtu.be/-zUxBhbOC7E

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1301]
https://youtu.be/-zUxBhbOC7E
<p>&#35270;&#39057;&#21457;&#24067;&#20110; July 19, 2020 at 08:17PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/-zUxBhbOC7E

#华农兄弟：有村民种羊角蜜，我们都不知道，摘一点来吃
#Huanong Brothers: Some villagers are growing horn melons. We didn't know that. Let's pick some.

0:00:00.000,0:00:04.120
# 大家好  我們村發現那個  有棧民在種那個羊角蜜喲
Hi everyone! We discoered that the our villagers are, I mean, the villagers are planting the, the horn melons.

0:00:05.940,0:00:08.060
# 我們都不知道  就在那裡
We didn't know that. It's right over there.

0:00:08.560,0:00:09.520
# 帶了一個桶去
I'm going with a bucket.

0:00:11.240,0:00:12.720
# 好多哇  那麼多
A lot, so many!

0:00:14.740,0:00:15.980
# 你看  這個
Look! These are,

0:00:16.440,0:00:17.900
# 它這個沒搭棚的  這個
these are not put up on fence, those here.

0:00:18.960,0:00:21.960
# 在農村  農村人種  種東西就是這樣
In the village, that's how the, the villagers grow our crops.

0:00:22.520,0:00:24.740
# 雖然是好  但是  看相不好 但是
Though it's good, but, I mean it doesn't look good, but,

0:00:25.280,0:00:27.040
# 質量還是很不錯的
but the quality is really not bad.

0:00:28.980,0:00:29.680
# 嗯
Um!

0:00:32.120,0:00:33.260
# 真的很好吃哦
It's really tasty!

0:00:34.660,0:00:35.560
# 削一下這個
Let me peel this one.

0:00:47.560,0:00:50.220
# 這個是有  可以算是有機的
This is org... It can be considered as organic.

0:00:50.840,0:00:52.460
# 都沒打過葯  沒施過肥
No pesticide has even been sprayed, nor fertiliser.

0:00:53.200,0:00:54.360
# 種下去就不管的
After planting, they're left alone.

0:00:54.700,0:00:55.320
# 草又多
So there's a lot of weed,

0:00:56.100,0:00:57.000
# 爛掉的也多
the same with the rotten ones.

0:01:02.920,0:01:03.820
# 這種都掉啦
These ones have fallen down.

0:01:04.200,0:01:05.100
# 來的太遲啦
We're too late.

0:01:07.440,0:01:08.340
# 來  拿著這個
C'mon! Hold this one!

0:01:08.560,0:01:09.160
# 這樣吃
Eat this part.

0:01:11.840,0:01:12.580
# 這搞了一個
She has picked one here.

0:01:13.200,0:01:14.220
# 看一下還有沒有
Let me see if there are any more.

0:01:16.920,0:01:18.120
# 真的好甜啊
It's really sweet!

0:01:26.740,0:01:27.740
# 熟了這個
Alright, this is ripe.

0:01:28.220,0:01:29.840
# 哈哈  他搞了一個西瓜
Haha! He has picked a watermelon.

0:01:34.000,0:01:36.320
# 不要啦  刘星辰  不要啦  不要西瓜
No more! Liu Xingchen! No more! No more watermelons!

0:01:36.760,0:01:37.840
# 摘這個羊角蜜
Pick these porn melons!

0:01:40.820,0:01:42.760
# 你看  這個都是熟的這個
Look! These are all ripe, these melons.

0:01:48.820,0:01:51.380
# 這羊角蜜 這種就很靚的 這種熟啦
The horn melons, these are really beautiful. These are ripe now.

0:01:51.880,0:01:53.580
# 品相不怎麼好的哦  這個
They don't really look good, those here.

0:01:54.120,0:01:56.700
# 但是肯定很好吃的  因為它沒有架起來
But they're certainly very tasty, as they've never been framed up.

0:01:56.700,0:01:58.460
# 本來這個羊角蜜要架起來的
Normally, these melons are framed up,

0:01:58.820,0:01:59.620
# 架起來才好看
so that they look better.

0:02:09.500,0:02:11.580
# 可以  這個也是  你看  那麼大條
Alright! This one too. Look! It's so long and big.

0:02:14.960,0:02:16.220
# 這個壞的  這個
This is rotten, this one.

0:02:24.260,0:02:25.740
# 你看  這有西瓜哦
Look! Here are some watermelons!

0:02:25.760,0:02:26.820
# 這幾個西瓜
This couple of watermelons,

0:02:27.980,0:02:28.760
# 很小
are very small.

0:02:30.420,0:02:31.840
# 現在好多都壞啦
Many are already rotten.

0:02:35.580,0:02:38.760
# 這種應該可以  這都苗都  苗都
I think this is alright. This is, even the seedling, the seedling,

0:02:39.200,0:02:40.160
# 死掉啦
are dead.

0:02:43.540,0:02:44.700
# 這個不知道熟了沒有
Let me check if it is ripe.

0:02:45.760,0:02:47.620
# 這個  我們這邊叫梨瓜
This one, we call it "peer melon" here.

0:02:48.360,0:02:49.480
# 以前還小的時候
In the past, when I was small,

0:02:50.140,0:02:52.740
# 經常去  去摘隔壁家的
I always, always picked them from my neighbour.

0:02:54.140,0:02:54.920
# 現在
And now,

0:02:56.260,0:02:57.360
# 現在還是
now I'm still doing the same thing.

0:02:59.560,0:03:01.820
# 這種香瓜很好吃的  這種香瓜  很脆的
These melons are really tasty, these melons. They're very crunchy.

0:03:06.600,0:03:08.220
# 嗯  有點苦這裡
Um! It's a bit bitter here.

0:03:11.580,0:03:12.600
# 很香的哦  這個
You know, it's smells so good, this one.

0:03:20.100,0:03:22.280
# 怎麼感覺沒有小時候那麼好吃啦
Why doesn't it seem to be as tasty as it was, when I was small?

0:03:26.440,0:03:27.580
# 現在還是燙的
It's still hot.

0:03:28.620,0:03:29.360
# 本來要
Normally, it should be,

0:03:30.180,0:03:31.860
# 進冰箱冷凍一下才好吃
chilled for a while in a fridge. It would then be more tasty.

0:03:33.200,0:03:33.900
# 不管啦
Whatever

0:03:37.500,0:03:39.480
# 好久沒吃過那麼  那麼香的那個
It smells so good. I haven't, haven't eaten such a nice melon for a,

0:03:40.260,0:03:41.300
# 這個  香瓜啦
for a long time.

0:03:41.640,0:03:43.680
# 你看  地上都爛了好多啊
Have a look at the ground! There are a lot of rotten ones.

0:03:53.240,0:03:54.260
# 都沒摘掉
No body picked them.

0:03:58.760,0:04:01.520
# 你看  我們摘點  我們搞點回去
Look! We're gonna pick some, pick some back home.

0:04:02.720,0:04:03.780
# 給家人吃
for our families.

0:04:05.100,0:04:06.460
# 搞一點  搞點
Let me pick a bit, pick some...

0:04:07.060,0:04:08.560
# 嗯  壞掉啦  這個
Um! It's rotten, this one.

0:04:29.340,0:04:30.560
# 就搞了那麼一點點
So we've picked a tiny little bit here.

0:04:31.020,0:04:31.920
# 我們回去啦
Let's go back.

0:04:36.120,0:04:37.360
# 兄弟還送了一點這個
My buddy has also given us a bit of, these are,

0:04:38.400,0:04:40.140
# 油果  跟那個芒杆糍粑
"you guo" (fried rice cake) and these are "manggan qiba" (rice cake wrapped in leaves).

0:04:40.780,0:04:41.540
# 給我們吃
All are for us.

0:04:44.220,0:04:44.920
# 好不好吃  (註︰沒有原字幕)
Is it tasty?

0:04:51.180,0:04:53.040
# 這種做的  他們這裡做的很漂亮啊
This one, the ones that they made here are so pretty.

0:04:53.060,0:04:55.120
# 像我們做的  哎  真的沒法
The ones that we made are, ay, really,

0:04:55.620,0:04:57.840
# 沒法入  沒法入眼
they really hurt, hurt our eyes.

0:05:00.300,0:05:02.560
# 真正做的好看的是這種 這個
This one, this is what it should look like when it's properly made.

0:05:07.560,0:05:09.000
# 雪白雪白的  看到沒有
It's snowy white, see?

0:05:12.240,0:05:14.200
# 非常好吃的  真正好吃的
It tastes very good, really good.

0:05:20.580,0:05:23.640
# 上次我們做的好像  這動的
The ones that we made last time were, like, they could move.

0:05:34.180,0:05:35.940
# 好啦  叫拾一下  準備回去啦
Alright! Let's tidy up, and get ready to go home.

0:05:39.880,0:05:43.000
# 回到半路  看到兄弟家做這個  進來吃兩個
On the way, we see that my buddy is making these things. So I come in and have some.

0:05:43.720,0:05:46.120
# 你看  這個是  小的時候那個  我們這邊叫那個
Look! This is, when we were small... Here we call it,

0:05:46.120,0:05:47.640
# 窩粑qi
"guo ba qi" (rice crêpe)

0:05:50.240,0:05:51.080
# 這個很好吃的
It's really tasty.

0:05:52.480,0:05:53.080
# 吃一點
Let me have a bit.

0:05:55.060,0:05:57.760
# 下去拿到碗來  下面有碗
Go down there and take a bowl! There are bowls!

0:05:57.820,0:05:59.320
# 下面厨櫃裡有
In the cupboard down there!

0:06:01.760,0:06:02.460
# 很好吃哦
It's really tasty!

0:06:06.260,0:06:07.520
# 有點  有點燙
A bit, a bit too hot.

0:06:10.120,0:06:11.020
# 燙得很靚
It's beautiful!

0:06:11.460,0:06:13.700
# 燙的沒那麼好  哈哈哈
Not really, hahaha!

0:06:16.480,0:06:17.320
# 鍋都不粘
It's not sticking onto the pan at all.

0:06:18.440,0:06:19.700
# 倒點香油下去
Put some oil.

0:06:19.740,0:06:20.780
# 先是燒點油
She heats up some oil first.

0:06:23.120,0:06:24.280
# 燒了油再
After heating the oil, then...

0:06:28.800,0:06:30.440
# 這個就是米漿做的
This is made of rice milk,

0:06:30.600,0:06:31.920
# 米漿跟韮菜
rice milk and leek.

0:06:33.120,0:06:33.620
# 米漿
Rice milk

0:06:34.120,0:06:34.780
# 米漿
Rice milk

0:06:35.140,0:06:36.280
# 就是那個推出來的
It's like, ground,

0:06:36.300,0:06:38.360
# 到上面去磨  磨出來的
it's ground, ground up there.

0:06:43.300,0:06:45.180
# 這個是那個推磨  推的
It's ground, using the mill.

0:06:45.420,0:06:46.260
# 就是那個磨石
You mean the stone mill, right?

0:06:46.580,0:06:48.880
# 加了韮菜
Yea, together with some leek.

0:06:53.620,0:06:56.740
# 純天然的哈  沒有其他任何色素的
It's purely natural, without any artificial colouring.

0:06:57.200,0:06:58.360
# 再加上花生油
Together with some peanuts oil

0:07:05.680,0:07:07.440
# 是  我就在全南就做這個
Yea, that's what I'm making in Quannan.

0:07:07.960,0:07:09.060
# 哦  在縣城做這個
Ah! You make these in the county seat.

0:07:09.140,0:07:10.920
# 是  做這個搞外賣
Yea, it's for takeaway.

0:07:11.020,0:07:12.760
# 你看  這還有一個公雞喲
Look! Here's also a roaster.

0:07:13.600,0:07:14.780
# 哎呀  還有鴨子
Aya! And ducks too

0:07:23.180,0:07:24.800
# 你看  這還有綠頭鴨哦
Look! Here are also mallards.

0:07:27.900,0:07:28.600
# 還有那個
And also,

0:07:29.780,0:07:30.780
# 花的那個
those tinted ones.

0:07:32.020,0:07:32.920
# 那邊也還有
Some more over there

0:07:34.500,0:07:36.660
# 兄弟家真富有  啥都有
My buddy is really rich. He has everything.

0:07:39.480,0:07:41.220
# 你看  這了[SIC]還有很多梨[SIC]李樹哦
Look! Here are also many plum trees,

0:07:41.680,0:07:42.480
# 李子樹
plum trees,

0:07:43.640,0:07:46.360
# 那邊還有梨樹  啥都有  他家
There are also pear trees. He really has, everything.

0:07:47.220,0:07:48.660
# 經常來他家做客
Let me come and be his guest more often.

0:07:52.260,0:07:54.940
# 啊  還有楊梅樹  看到沒有  幾棵楊梅樹
Ah! There are also some bayberry trees. See? A couple of bayberry trees.

0:07:57.740,0:07:59.080
# 好啦 回去啦
Alright! Let's go back!

0:07:59.860,0:08:00.940
# 天都快黑啦
It's already getting dark.
