### ISSUE TITLE
[雪鱼] 兰州羊杂 - https://youtu.be/T_r0hrEsXG0

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#1302]
**视频链接**：<https://youtu.be/T_r0hrEsXG0>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
兰州人的夜宵干拌羊杂+牛奶鸡蛋醪糟）

简介
兰州人的清晨属于牛肉面，而夜晚属于中山桥！不过在去中山桥之前，我先去吃了一家当地的特色夜宵凉拌羊杂！下午过去的时候已经开始要排队了，赶紧找一个空桌坐下来。这家的特色是把羊杂凉拌着吃，不同于羊杂汤，干拌的味道要更加猛烈一些，辣椒、蒜泥几乎覆盖了整盘羊杂。对于羊杂里的肉类，可以自由选择搭配，不想吃什么可以不加。老板大叔手法熟练得切着羊杂，切好的羊杂装盘，然后下沸水中烫30几秒，出锅装盘最后再加调味料。吃羊杂不能单吃，配一块大饼，既能中和羊杂的麻辣口感，又能果腹，一盘羊杂一块大饼，岂不美哉！
吃过羊杂后，我又来到了兰州最知名的正宁街夜市，一座城市的活力大抵可以从夜市中看出来。这里挤满了逛街的人，几乎比肩接踵，很多人下班后约三五好友在夜市中随便找一个座位坐下来，吃烧烤、羊杂、羊头肉、喝啤酒等。我要了一杯牛奶鸡蛋醪糟，这个小吃几乎是这条街最热门的了。更多精彩内容欢迎观看视频。

字幕
1
00:00:01,840 --> 00:00:06,280
甘肃·兰州

2
00:00:11,840 --> 00:00:13,840
啊 走过了

3
00:00:15,000 --> 00:00:19,360
现在是晚上6点钟 我们将要去一个羊杂店

4
00:00:19,600 --> 00:00:22,560
在兰州 如果说早上是属于牛的

5
00:00:22,560 --> 00:00:25,120
那么晚上 一定是属于羊的

6
00:00:25,120 --> 00:00:28,280
早上呢 不用多说 就是卖牛肉面的多一些

7
00:00:28,280 --> 00:00:31,440
就像我今天早上刚吃的这一种

8
00:00:31,520 --> 00:00:34,240
随着这个时间逐渐到了中午 到了晚上

9
00:00:34,240 --> 00:00:36,000
卖牛肉的食品逐渐少了

10
00:00:36,000 --> 00:00:41,520
但是卖羊杂 羊蹄 这样的有关羊的食物逐渐多了起来

11
00:00:41,520 --> 00:00:44,480
今天下午呢 我们将前往这个巷子的深处

12
00:00:44,480 --> 00:00:47,440
品尝羊杂 特色的羊杂

13
00:00:48,120 --> 00:00:51,880
现在已经开始排队了 我们也赶快过去吧

14
00:01:03,940 --> 00:01:05,940
用滚烫烫30秒

15
00:01:21,900 --> 00:01:24,400
切好了羊杂以后

16
00:01:25,240 --> 00:01:27,100
先撒椒盐

17
00:01:27,480 --> 00:01:29,360
然后就是蒜泥

18
00:01:31,160 --> 00:01:34,560
爱吃辣子就调一点辣子

19
00:01:39,240 --> 00:01:41,240
这就比较圆满了

20
00:01:41,300 --> 00:01:43,300
这是蒜苗

21
00:01:46,460 --> 00:01:48,460
这是椒盐羊肝

22
00:01:49,080 --> 00:01:51,080
这盘是纯羊头肉

23
00:01:57,120 --> 00:02:00,620
我看又有羊杂汤又有凉拌的？

24
00:02:00,780 --> 00:02:03,640
是 有凉拌羊杂和羊杂汤2种

25
00:02:05,440 --> 00:02:07,440
干拌羊杂味道好一些

26
00:02:10,240 --> 00:02:13,480
我们的特色就是干拌羊杂

27
00:02:13,720 --> 00:02:16,220
是我们兰州本地的特色

28
00:02:19,560 --> 00:02:22,740
干拌的调料比较足一些 味道好

29
00:02:26,120 --> 00:02:27,480
这是羊舌头

30
00:02:27,520 --> 00:02:29,520
哦 还看不出来呢

31
00:02:35,040 --> 00:02:37,040
这个是混着卖的呀

32
00:02:37,700 --> 00:02:39,620
是 都可以 随便

33
00:02:39,720 --> 00:02:42,840
单独点其中一种可以 混合的也可以

34
00:02:44,080 --> 00:02:47,540
那我要一个最普通的 混着的羊杂

35
00:02:47,540 --> 00:02:48,720
再给加一个饼

36
00:03:08,260 --> 00:03:10,780
11号在这

37
00:03:11,260 --> 00:03:15,460
我们要的是35块钱的大份的

38
00:03:15,460 --> 00:03:19,220
配的是一个饼

39
00:03:19,220 --> 00:03:21,780
11号

40
00:03:21,780 --> 00:03:23,660
谢谢

41
00:03:31,220 --> 00:03:35,180
好浓重的蒜汁和醋的味道

42
00:03:35,180 --> 00:03:39,620
放眼望去 就是满眼的蒜汁和辣子

43
00:03:44,220 --> 00:03:46,780
以前吃羊杂 都是喝羊杂汤

44
00:03:46,780 --> 00:03:49,580
他们这边是把羊杂凉拌出来

45
00:03:49,580 --> 00:03:52,500
我本来以为这个羊杂碎是点一盘

46
00:03:52,500 --> 00:03:54,700
然后大家围着一起吃

47
00:03:54,700 --> 00:03:56,900
实际上呢 是一人点一盘

48
00:03:56,900 --> 00:03:59,500
吃的时候呢 还会配一碗羊汤

49
00:04:04,140 --> 00:04:07,020
这个羊杂是怎么做的呢 它是半熟之后

50
00:04:07,020 --> 00:04:10,140
然后就是客人点了之后 再用沸汤过几下

51
00:04:10,140 --> 00:04:14,780
最后就是放上辣子 蒜汁这些 端到我们的面前

52
00:04:21,840 --> 00:04:23,840
是不是感觉配饼刚刚好

53
00:04:23,840 --> 00:04:24,640
嗯

54
00:04:27,660 --> 00:04:29,980
这么配饼吃 刚刚好

55
00:04:40,780 --> 00:04:44,180
这个肝 确实嫩

56
00:04:45,020 --> 00:04:47,460
喝口汤

57
00:04:50,060 --> 00:04:53,060
配这个汤 也很好

58
00:04:54,060 --> 00:04:56,900
在这边吃饭 调料味会重很多

59
00:04:56,900 --> 00:05:01,140
如果说 肉不够 光蘸一蘸这个料 我都能把饼吃完

60
00:05:01,860 --> 00:05:03,580
下午 我只是要了羊杂

61
00:05:03,940 --> 00:05:06,580
其实这边还有一种食物是我没有尝试的

62
00:05:06,580 --> 00:05:07,640
就是羊头

63
00:05:10,340 --> 00:05:13,180
你看 咱们要的羊杂里面是有羊脸肉的

64
00:05:13,180 --> 00:05:16,140
这个羊头除去了羊脸肉之外

65
00:05:16,140 --> 00:05:19,180
剩下的部分 还可以当做一道菜

66
00:05:19,460 --> 00:05:23,080
这就是一套 羊脸和羊干头

67
00:05:24,060 --> 00:05:26,300
干头供不应求

68
00:05:26,300 --> 00:05:28,980
那吃羊头吃什么

69
00:05:28,980 --> 00:05:33,260
吃眼睛 吃上颌

70
00:05:38,820 --> 00:05:43,180
大叔 咱们在这边做多久了

71
00:05:43,180 --> 00:05:53,540
我们原来在市场 的时候我们干了十几年

72
00:05:53,540 --> 00:05:55,900
13年

73
00:05:55,900 --> 00:06:00,660
在这边 我们又干了8年 就这个铺子

74
00:06:00,660 --> 00:06:03,900
刚开始就跟老伴两个人

75
00:06:03,900 --> 00:06:06,980
后来儿子就参加

76
00:06:07,340 --> 00:06:10,940
因为这个工作比较繁琐

77
00:06:11,340 --> 00:06:16,500
也不是一个人 两个人就能干了的事情

78
00:06:16,500 --> 00:06:22,140
现在我们这儿5个人都忙不过来 还得再增加人手

79
00:06:33,860 --> 00:06:36,580
吃完了羊杂 我又来到了正宁路小吃街

80
00:06:36,580 --> 00:06:40,020
这边有一种甜品叫做 牛奶鸡蛋醪糟

81
00:06:40,020 --> 00:06:41,780
我想来试一下

82
00:06:47,460 --> 00:06:51,100
走了这么久 我倒是发现了很多家卖牛奶鸡蛋醪糟的

83
00:06:51,100 --> 00:06:53,100
有个有意思的现象就是

84
00:06:53,100 --> 00:06:58,120
凡是卖牛奶鸡蛋醪糟的 都是一个姓马的白胡子老爷爷

85
00:06:58,300 --> 00:07:01,460
除了位置不同 我感觉不到有什么样的区别

86
00:07:03,900 --> 00:07:08,260
最后呢 我找了一家看起来还不错的牛奶鸡蛋醪糟来排队

87
00:07:09,800 --> 00:07:11,800
加醪糟 牛奶 白糖

88
00:08:08,880 --> 00:08:10,880
10元一杯

89
00:08:15,320 --> 00:08:17,040
我们是排了一圈

90
00:08:17,220 --> 00:08:21,860
我后面的小哥说 排队就像贪吃蛇一样

91
00:08:22,820 --> 00:08:26,940
它这个是稀的 不是稠的 上面就是漂着蛋花

92
00:08:27,180 --> 00:08:32,820
还有呢 就是放了花生 葡萄干 黑白芝麻

93
00:08:38,740 --> 00:08:43,260
味道很像这个 叫什么 叫什么来

94
00:08:43,600 --> 00:08:47,560
它的味道很像核桃露的味道

95
00:08:49,460 --> 00:08:55,380
闻着米酒的味道还是很冲的 喝起来完全感知不到

96
00:08:55,600 --> 00:08:56,960
可能每一杯的味道都不太一样

97
00:08:57,100 --> 00:09:00,940
因为我在那个地方观察它的牛奶 米酒的比例

98
00:09:01,120 --> 00:09:04,120
我感觉有的时候 好像勺数是不一样的

99
00:09:04,160 --> 00:09:05,800
有的时候就是米酒多放点

100
00:09:06,020 --> 00:09:08,860
有的时候就是牛奶多放点

101
00:09:10,460 --> 00:09:14,500
我以为鸡蛋和成了蛋花 放在里面 应该是均匀的状态

102
00:09:14,780 --> 00:09:17,400
没想到 它和热的米酒牛奶放在一起

103
00:09:17,840 --> 00:09:21,920
还是成了大的蛋花


```

**Comment by shuaisoserious** [comment]
认领

**Comment by WuStevenShengyang** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
兰州人的夜宵干拌羊杂+牛奶鸡蛋醪糟）
Lanzhou Supper: Lamb Haslet Salad and Laozao with milk and egg.

简介
兰州人的清晨属于牛肉面，而夜晚属于中山桥！不过在去中山桥之前，我先去吃了一家当地的特色夜宵凉拌羊杂！下午过去的时候已经开始要排队了，赶紧找一个空桌坐下来。这家的特色是把羊杂凉拌着吃，不同于羊杂汤，干拌的味道要更加猛烈一些，辣椒、蒜泥几乎覆盖了整盘羊杂。对于羊杂里的肉类，可以自由选择搭配，不想吃什么可以不加。老板大叔手法熟练得切着羊杂，切好的羊杂装盘，然后下沸水中烫30几秒，出锅装盘最后再加调味料。吃羊杂不能单吃，配一块大饼，既能中和羊杂的麻辣口感，又能果腹，一盘羊杂一块大饼，岂不美哉！
Lanzhou's morning belongs to beef noodle soup, but the night belongs to Zhongshan Bridge. We went to a local lamb haslet salad restaurant. People already lined up in the afternoon. We were able to find an empty table. Unlike the haslet soup, haslet salad is the special here. It is more flavorful. Chili and garlic covered almost the entire plate. After chopping the lamb haslet, he cooked it in boiling water for around 30 seconds. After that, he added seasonings. You need to eat haslet with a pastry. It not only will help you eat the spicy haslet, but also fill your stomach. What a dish!
吃过羊杂后，我又来到了兰州最知名的正宁街夜市，一座城市的活力大抵可以从夜市中看出来。这里挤满了逛街的人，几乎比肩接踵，很多人下班后约三五好友在夜市中随便找一个座位坐下来，吃烧烤、羊杂、羊头肉、喝啤酒等。我要了一杯牛奶鸡蛋醪糟，这个小吃几乎是这条街最热门的了。更多精彩内容欢迎观看视频。
After having the lamb haslet salad, we came to the well-known night market at Lanzhou: Zhengning Street. We could tell the energy of a city from its night market. There were full of people and they were having barbecue, lamb haslet, lamb head, and beer. I ordered a Laozao with Milk and Egg, which is one of the most popular disserts in this night market. More in this video! 

字幕
1
00:00:01,840 --> 00:00:06,280
甘肃·兰州
Lanzhou, Gansu.

2
00:00:11,840 --> 00:00:13,840
啊 走过了
Oh, I missed it.

3
00:00:15,000 --> 00:00:19,360
现在是晚上6点钟 我们将要去一个羊杂店
It is 6 P.M., and we are heading to a lamb haslet restaurant.

4
00:00:19,600 --> 00:00:22,560
在兰州 如果说早上是属于牛的
In Lanzhou, if the morning belongs to the beef,

5
00:00:22,560 --> 00:00:25,120
那么晚上 一定是属于羊的
then the night definetely belongs to the lamb.

6
00:00:25,120 --> 00:00:28,280
早上呢 不用多说 就是卖牛肉面的多一些
In the morning, basically, there are lots of places selling beef noodle soup.

7
00:00:28,280 --> 00:00:31,440
就像我今天早上刚吃的这一种
Like the one I just had this morning.

8
00:00:31,520 --> 00:00:34,240
随着这个时间逐渐到了中午 到了晚上
When it gets to the afternoon and evening, 

9
00:00:34,240 --> 00:00:36,000
卖牛肉的食品逐渐少了
there won't be that much beef products anymore.

10
00:00:36,000 --> 00:00:41,520
但是卖羊杂 羊蹄 这样的有关羊的食物逐渐多了起来
However, by the time you will see more lamb products such as lamb haslet and lamb's foot. 

11
00:00:41,520 --> 00:00:44,480
今天下午呢 我们将前往这个巷子的深处
This evening, we are heading into this alley.

12
00:00:44,480 --> 00:00:47,440
品尝羊杂 特色的羊杂
To try some lamb haslet.

13
00:00:48,120 --> 00:00:51,880
现在已经开始排队了 我们也赶快过去吧
They have already lined up over there, let's go.

14
00:01:03,940 --> 00:01:05,940
用滚烫烫30秒
We will cook this in boiling soup for about 30 seconds.

15
00:01:21,900 --> 00:01:24,400
切好了羊杂以后
After we chopped up the lamb haslet,

16
00:01:25,240 --> 00:01:27,100
先撒椒盐
we will add some salt and pepper,

17
00:01:27,480 --> 00:01:29,360
然后就是蒜泥
and minced garlic.

18
00:01:31,160 --> 00:01:34,560
爱吃辣子就调一点辣子
If you want it to be spicy you can add some red chili oil.

19
00:01:39,240 --> 00:01:41,240
这就比较圆满了
This is a good dish.

20
00:01:41,300 --> 00:01:43,300
这是蒜苗
Sprinkle some garlic sprouts on top.

21
00:01:46,460 --> 00:01:48,460
这是椒盐羊肝
This is salt & pepper lamb haslet.

22
00:01:49,080 --> 00:01:51,080
这盘是纯羊头肉
This right here, is lamb head meat.

23
00:01:57,120 --> 00:02:00,620
我看又有羊杂汤又有凉拌的？
I saw that you can have either lamb haslet soup or salad?

24
00:02:00,780 --> 00:02:03,640
是 有凉拌羊杂和羊杂汤2种
Yes, we have two different kinds.

25
00:02:05,440 --> 00:02:07,440
干拌羊杂味道好一些
But haslet salad tastes better,

26
00:02:10,240 --> 00:02:13,480
我们的特色就是干拌羊杂
which is our special.

27
00:02:13,720 --> 00:02:16,220
是我们兰州本地的特色
Our local special.

28
00:02:19,560 --> 00:02:22,740
干拌的调料比较足一些 味道好
The salad seasoning makes it more flavorful.

29
00:02:26,120 --> 00:02:27,480
这是羊舌头
This is lamb's tougue.

30
00:02:27,520 --> 00:02:29,520
哦 还看不出来呢
Oh, I didn't even recognize.

31
00:02:35,040 --> 00:02:37,040
这个是混着卖的呀
Do you sell a mixture of lamb haslet?

32
00:02:37,700 --> 00:02:39,620
是 都可以 随便
Yes.

33
00:02:39,720 --> 00:02:42,840
单独点其中一种可以 混合的也可以
You can order a specific type of haslet, or a mixture of all haslet.

34
00:02:44,080 --> 00:02:47,540
那我要一个最普通的 混着的羊杂
Then I will have a mixed lamb haslet,

35
00:02:47,540 --> 00:02:48,720
再给加一个饼
with a pastry as well.

36
00:03:08,260 --> 00:03:10,780
11号在这
No.11 is right here.

37
00:03:11,260 --> 00:03:15,460
我们要的是35块钱的大份的
We bought the large size, which is 35 RMB.

38
00:03:15,460 --> 00:03:19,220
配的是一个饼
I also ordered a pastry.

39
00:03:19,220 --> 00:03:21,780
11号
No.11.

40
00:03:21,780 --> 00:03:23,660
谢谢
Thank you.

41
00:03:31,220 --> 00:03:35,180
好浓重的蒜汁和醋的味道
The scent of garlic and vinegar is quite strong.

42
00:03:35,180 --> 00:03:39,620
放眼望去 就是满眼的蒜汁和辣子
If you look at this dish, it's just full of garlic and chili.

43
00:03:44,220 --> 00:03:46,780
以前吃羊杂 都是喝羊杂汤
We used to only eat lamb haslet soup in the past.

44
00:03:46,780 --> 00:03:49,580
他们这边是把羊杂凉拌出来
But here they took out the haslet and turned it into a salad. 

45
00:03:49,580 --> 00:03:52,500
我本来以为这个羊杂碎是点一盘
At first, I thought this haslet comes in a very large plate.

46
00:03:52,500 --> 00:03:54,700
然后大家围着一起吃
And we will eat together from one plate.

47
00:03:54,700 --> 00:03:56,900
实际上呢 是一人点一盘
However, every person has his own plate of lamb haslet,

48
00:03:56,900 --> 00:03:59,500
吃的时候呢 还会配一碗羊汤
accompanied with a bowl of lamb broth.

49
00:04:04,140 --> 00:04:07,020
这个羊杂是怎么做的呢 它是半熟之后
How do they make lamb haslet? It was typically half-cooked at first.

50
00:04:07,020 --> 00:04:10,140
然后就是客人点了之后 再用沸汤过几下
After we ordered, they cooked it again in the boiling soup.

51
00:04:10,140 --> 00:04:14,780
最后就是放上辣子 蒜汁这些 端到我们的面前
After adding garlic and chili oil, the dish is ready to be served.

52
00:04:21,840 --> 00:04:23,840
是不是感觉配饼刚刚好

53
00:04:23,840 --> 00:04:24,640
嗯
Yea.

54
00:04:27,660 --> 00:04:29,980
这么配饼吃 刚刚好
It's delicious with the pastry.

55
00:04:40,780 --> 00:04:44,180
这个肝 确实嫩
This lamb liver is so tender.

56
00:04:45,020 --> 00:04:47,460
喝口汤
With some broth.

57
00:04:50,060 --> 00:04:53,060
配这个汤 也很好
This combination is also awesome.

58
00:04:54,060 --> 00:04:56,900
在这边吃饭 调料味会重很多
Dishes here typically has lots of seasoning.

59
00:04:56,900 --> 00:05:01,140
如果说 肉不够 光蘸一蘸这个料 我都能把饼吃完
If there wasn't that much meet, I can eat the whole pastry with only the seasoning in the plate.

60
00:05:01,860 --> 00:05:03,580
下午 我只是要了羊杂
I only had lamb haslet in the afternoon.

61
00:05:03,940 --> 00:05:06,580
其实这边还有一种食物是我没有尝试的
However, there is another type of food that I have yet to try.

62
00:05:06,580 --> 00:05:07,640
就是羊头
The lamb head.

63
00:05:10,340 --> 00:05:13,180
你看 咱们要的羊杂里面是有羊脸肉的
Our lamb haslet has meat from lamb's face.

64
00:05:13,180 --> 00:05:16,140
这个羊头除去了羊脸肉之外
However, after removing the meat from the face,

65
00:05:16,140 --> 00:05:19,180
剩下的部分 还可以当做一道菜
they can use the rest of the lamb head to make a separate dish.

66
00:05:19,460 --> 00:05:23,080
这就是一套 羊脸和羊干头
This a whole set of lamb face and head.

67
00:05:24,060 --> 00:05:26,300
干头供不应求
So many people want to order the lamb head.

68
00:05:26,300 --> 00:05:28,980
那吃羊头吃什么
What can you eat from the lamb head?

69
00:05:28,980 --> 00:05:33,260
吃眼睛 吃上颌
Eyes, upper jaw, etc.

70
00:05:38,820 --> 00:05:43,180
大叔 咱们在这边做多久了
Sir, how long have your restaurant been here.

71
00:05:43,180 --> 00:05:53,540
我们原来在市场 的时候我们干了十几年
We used to be in the market for over a decade.

72
00:05:53,540 --> 00:05:55,900
13年
13 years.

73
00:05:55,900 --> 00:06:00,660
在这边 我们又干了8年 就这个铺子
And we have been in this place for 8 years.

74
00:06:00,660 --> 00:06:03,900
刚开始就跟老伴两个人
After first, it was only me and my wife.

75
00:06:03,900 --> 00:06:06,980
后来儿子就参加
Then, my son joined.

76
00:06:07,340 --> 00:06:10,940
因为这个工作比较繁琐
Because this job is quite tedious.

77
00:06:11,340 --> 00:06:16,500
也不是一个人 两个人就能干了的事情
It is not something that can be easily done with one or two persons.

78
00:06:16,500 --> 00:06:22,140
现在我们这儿5个人都忙不过来 还得再增加人手
Now, even with five persons, we still need more employees.

79
00:06:33,860 --> 00:06:36,580
吃完了羊杂 我又来到了正宁路小吃街
After having the lamb haslet, we are now at Zhengning Road's Snack Street.

80
00:06:36,580 --> 00:06:40,020
这边有一种甜品叫做 牛奶鸡蛋醪糟
There is a type of dessert called: Laozao with milk and egg (Laozao: rice wine distillerse grains).

81
00:06:40,020 --> 00:06:41,780
我想来试一下
I want to try it.

82
00:06:47,460 --> 00:06:51,100
走了这么久 我倒是发现了很多家卖牛奶鸡蛋醪糟的
I think there are quite a lot of shops that make this dessert.

83
00:06:51,100 --> 00:06:53,100
有个有意思的现象就是
What's interesting is that,

84
00:06:53,100 --> 00:06:58,120
凡是卖牛奶鸡蛋醪糟的 都是一个姓马的白胡子老爷爷
every shop that makes this dissert has a grandpa whose lastname is Ma.

85
00:06:58,300 --> 00:07:01,460
除了位置不同 我感觉不到有什么样的区别
Other than location, I don't really feel any difference between those shops.

86
00:07:03,900 --> 00:07:08,260
最后呢 我找了一家看起来还不错的牛奶鸡蛋醪糟来排队
Eventually, I lined up at a store that looks quite decent.

87
00:07:09,800 --> 00:07:11,800
加醪糟 牛奶 白糖
Laozao, milk, and sugar.

88
00:08:08,880 --> 00:08:10,880
10元一杯
10 RMB per cup.

89
00:08:15,320 --> 00:08:17,040
我们是排了一圈
Our line looks like a circle.

90
00:08:17,220 --> 00:08:21,860
我后面的小哥说 排队就像贪吃蛇一样
The person behind be said, the line is like a snake.

91
00:08:22,820 --> 00:08:26,940
它这个是稀的 不是稠的 上面就是漂着蛋花
It is actually quite watery, not thick at all. There are some egg flowers on top.

92
00:08:27,180 --> 00:08:32,820
还有呢 就是放了花生 葡萄干 黑白芝麻
There are also peanuts, raisins, and sesame seeds on top.

93
00:08:38,740 --> 00:08:43,260
味道很像这个 叫什么 叫什么来
It smells like, like,

94
00:08:43,600 --> 00:08:47,560
它的味道很像核桃露的味道
walnut milk.

95
00:08:49,460 --> 00:08:55,380
闻着米酒的味道还是很冲的 喝起来完全感知不到
The rice wine flavor doesn't taste as strong as it smells.

96
00:08:55,600 --> 00:08:56,960
可能每一杯的味道都不太一样
Probably because every cup tastes a little differently.

97
00:08:57,100 --> 00:09:00,940
因为我在那个地方观察它的牛奶 米酒的比例
I have noticed that, the ratio of milk and rice wine

98
00:09:01,120 --> 00:09:04,120
我感觉有的时候 好像勺数是不一样的
is different sometimes.

99
00:09:04,160 --> 00:09:05,800
有的时候就是米酒多放点
Sometimes they put more rice wine,

100
00:09:06,020 --> 00:09:08,860
有的时候就是牛奶多放点
sometimes more milk.

101
00:09:10,460 --> 00:09:14,500
我以为鸡蛋和成了蛋花 放在里面 应该是均匀的状态
I thought the egg flowers should be mixed evenly within this dissert.

102
00:09:14,780 --> 00:09:17,400
没想到 它和热的米酒牛奶放在一起
It surprised me that, mixing with hot rice wine and milk,

103
00:09:17,840 --> 00:09:21,920
还是成了大的蛋花
the egg turned into even larger egg flowers.
