### ISSUE TITLE
【美食作家王刚】红烧肉的酒店做法 - https://youtu.be/9PgsGxThueI

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1303]
**视频链接**：https://youtu.be/9PgsGxThueI

视频时长9:25，预计发布时间为北京时间7月22日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：方正软糯“红烧肉”的酒店做法，行业秘密全盘脱出，让你在家也能做出惊艳的感觉！

简介
大家好，今天做一道“红烧肉”，这是我第三次分享红烧肉的做法，之前都为家常菜版本，对菜品的外形没有过分的要求。但有不少朋友问怎么才能做出酒店版本的红烧肉，那种很方正但又特别软糯的，今天就来和大家破解其中的秘密！技术总结从之前的文字分享改变成了动态分享，希望大家喜欢！

本期菜品【红烧肉】
【主料】
五花肉（1大块）
【配料】
红酒（适量）
大葱（4根）
生姜（2小块）
植物油（适量）
姜葱油（少许）
冰糖（1小块）
糖色（10克）
桂皮（2小块）
西兰花（适量）
【调味料】
食用盐（适量）

字幕
0:00:00.468,0:00:01.678
哈喽大家好我是王刚

0:00:01.678,0:00:03.790
本期视频我跟大家分享一道拿手菜

0:00:04.259,0:00:06.130
电饭锅红烧肉

0:00:06.541,0:00:09.869
首先我们准备新鲜且富有弹性的五花肉一大块

0:00:10.340,0:00:13.190
不喜欢五花肉的同学也可以选择二刀肉

0:00:14.857,0:00:17.289
然后在托盘中加入适量的清水

0:00:22.108,0:00:23.670
下一步开始烧皮

0:00:25.623,0:00:28.169
首先用喷枪把猪皮烧至焦黑色

0:00:28.580,0:00:30.214
第一遍是去除猪毛

0:00:37.257,0:00:39.062
第二遍是烧至皮黄

0:00:45.527,0:00:47.195
第三遍才是烧至焦黑

0:00:47.608,0:00:50.700
托盘中加水的目的是防止托盘受热变形

0:00:51.633,0:00:53.672
烧至焦黑之后用钢丝球或者菜刀

0:00:53.672,0:00:55.656
将烧焦的部分刮洗干净

0:01:07.956,0:01:09.812
刮洗干净之后开始分肉

0:01:10.000,0:01:12.080
首先带乳头的部分容易分层

0:01:12.080,0:01:13.400
但瘦肉比较多

0:01:23.031,0:01:24.940
最后的部分肥肉比较厚重

0:01:25.220,0:01:28.109
而中间部分则不肥不瘦比较紧实

0:01:28.792,0:01:31.460
然后我们取中间部分下一步开始煮肉

0:01:31.736,0:01:34.458
将五花肉放入电饭锅中加入适量的清水

0:01:41.660,0:01:43.335
加入适量的红酒

0:01:49.669,0:01:51.950
准备大葱两根切成小段加入

0:01:55.174,0:01:57.749
准备生姜一小块切成姜片备用

0:02:00.565,0:02:02.920
然后接上电源将五花肉煮至断生

0:02:03.197,0:02:06.120
此过程根据不同的电饭锅煮制的时间也不同

0:02:13.673,0:02:16.681
大约20分钟之后用筷子能插透即可捞出

0:02:26.520,0:02:29.210
猪肉捞出之后均匀的撒上适量的食用盐

0:02:31.233,0:02:32.948
下一步开始准备炸皮

0:02:33.820,0:02:35.652
首先我们把锅烧热

0:02:35.837,0:02:38.318
锅烧热之后加入一勺植物油烧热

0:02:41.061,0:02:44.708
油温烧至六成热之后将猪皮朝下炸至金黄色

0:02:45.020,0:02:48.060
这一步的目的是保证红烧肉软而皮不烂

0:03:09.276,0:03:12.254
炸至金黄色之后捞出皮朝下放入托盘中

0:03:13.921,0:03:16.242
然后准备一个小托盘压在上面

0:03:17.215,0:03:19.670
也可以用重物或者胶带缠紧

0:03:34.527,0:03:37.086
猪肉压紧之后放入冰箱冰冻一个小时

0:03:37.300,0:03:40.716
这一步的目的是防止猪肉下锅热胀冷缩导致变形

0:03:40.980,0:03:44.190
冰冻一个小时之后将肉取出切成小方块备用

0:03:53.935,0:03:55.304
理论上切得越大

0:03:55.520,0:03:56.560
则烧得越久

0:03:56.912,0:03:59.220
相反切得越小块时间则越短

0:04:09.820,0:04:12.252
然后将切好的猪肉放入锅中

0:04:14.293,0:04:16.278
准备生姜一小块拍散备用

0:04:17.174,0:04:19.228
准备大葱两根切成小段备用

0:04:20.551,0:04:22.012
锅中加入适量的清水

0:04:22.384,0:04:24.465
水的量需要参考电饭锅的火力

0:04:24.465,0:04:26.620
以及水分蒸发的时间等等

0:04:31.740,0:04:33.630
锅中加入少许的姜葱油

0:04:33.680,0:04:35.970
没有姜葱油的同学也可以不加

0:04:36.460,0:04:38.038
加入冰糖一小块

0:04:38.860,0:04:40.278
加入红酒60克

0:04:40.278,0:04:43.517
没有红酒的同学也可以用黄酒或者料酒代替

0:04:44.220,0:04:45.588
加入糖色10克

0:04:54.062,0:04:55.658
最后加入桂皮两小块

0:04:56.680,0:04:59.118
然后盖上盖子煮120分钟

0:05:03.357,0:05:06.106
烧至60分钟的时候捡去姜葱香料不要

0:05:15.691,0:05:17.803
然后加入适量的食用盐调咸味

0:05:17.960,0:05:20.220
调好味之后继续烧剩余的时间

0:05:24.420,0:05:27.570
中途需要定时揭开锅盖查看水量是否烧干

0:05:33.660,0:05:37.453
烧够两个小时之后水分略干且汤汁浓稠即可出锅

0:05:37.580,0:05:39.020
同学们汤汁是否浓稠

0:05:39.020,0:05:40.500
除了肉胶的作用之外

0:05:40.500,0:05:42.460
冰糖也起到了很大的作用

0:05:52.515,0:05:54.448
然后准备烧热的小石锅一个

0:05:54.448,0:05:56.440
加入焯好水的西兰花垫底

0:05:56.560,0:05:59.958
同学们选用烧热的石锅可以增加成菜的保温时间

0:06:00.240,0:06:02.750
没有石锅的同学也可以选用砂锅

0:06:03.129,0:06:05.434
蔬菜垫底之后依次加入红烧肉

0:06:11.950,0:06:14.193
最后淋上剩余的汤汁即可上菜

0:06:18.000,0:06:21.222
一道肥而不腻的电饭锅红烧肉就制作完成

0:06:23.786,0:06:25.360
下面开始技术总结

0:06:25.800,0:06:28.160
第一五花肉部位的选择

0:06:28.200,0:06:30.480
五花肉边上带乳头的部位比较瘦

0:06:30.560,0:06:33.449
但肉比较松容易脱层影响美观

0:06:39.680,0:06:42.040
同样最后的位置肉最Q弹

0:06:42.080,0:06:44.320
但肥肉最多很容易腻口

0:06:49.560,0:06:51.400
中间的五花肉肥瘦参半

0:06:51.440,0:06:52.360
且不脱层

0:06:52.680,0:06:54.480
所以比较适合红烧肉的原料是

0:06:54.480,0:06:56.080
不肥不瘦的中间部位

0:07:05.020,0:07:05.860
第二

0:07:05.900,0:07:07.460
电饭锅火力虽然小

0:07:07.500,0:07:09.048
但是很容易将猪肉烧透

0:07:09.048,0:07:11.908
口感上来说比高压锅出品更加弹牙

0:07:12.056,0:07:14.100
家庭长时间炖肉容易被遗忘

0:07:14.140,0:07:17.028
而电饭锅也可以自动跳闸也显得更加的安全

0:07:17.180,0:07:17.879
第三

0:07:18.208,0:07:20.640
炸肉之前可以先涂抹一层食用盐

0:07:20.760,0:07:22.880
这样可以防止猪肉油脂爆炸

0:07:22.920,0:07:25.574
即使猪肉很肥下锅也不容易炸锅

0:07:32.787,0:07:34.855
下面进行不抹盐下锅测试

0:07:35.006,0:07:36.646
大家可以很显然的感受到

0:07:36.646,0:07:38.461
猪肉的油脂已经炸裂

0:07:38.645,0:07:40.301
同学们这一步比较危险

0:07:40.557,0:07:41.512
请勿模仿

0:07:41.815,0:07:45.981
肉皮经过油炸之后即使烧很长时间也能够保持原型不烂

0:07:46.141,0:07:46.708
第四

0:07:47.136,0:07:49.581
未加冰冻的肉也可以直接切块烧

0:07:49.581,0:07:53.170
但猪肉会热胀冷缩导致成品膨胀不方正

0:07:53.371,0:07:55.220
解决这个问题最好的方法就是用

0:07:55.220,0:07:57.100
重物平压冰冻一个小时

0:08:08.846,0:08:11.410
这样操作过的红烧肉显得方方正正

0:08:11.460,0:08:12.950
且不影响口感

0:08:13.060,0:08:15.090
以下大家可以看一下对比

0:08:20.475,0:08:21.244
第五

0:08:21.244,0:08:23.931
加红酒烧肉可以分解肥肉中的油脂

0:08:23.931,0:08:26.671
红酒加得越多则越不容易腻

0:08:34.200,0:08:36.960
在最后吃的时候可以配上酸萝卜和红酒

0:08:36.960,0:08:38.357
这样也可以解腻

0:08:38.357,0:08:39.968
红烧肉的技术总结完毕


```

**Comment by immoonancient** [comment]
@iamatrollatrollisme 请前来认领

**Comment by iamatrollatrollisme** [comment]
认领

**Comment by iamatrollatrollisme** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：方正软糯“红烧肉”的酒店做法，行业秘密全盘脱出，让你在家也能做出惊艳的感觉！
Chef Wang teaches you: Authentic restaurant style “red braised pork”, easy replicate at home

简介
大家好，今天做一道“红烧肉”，这是我第三次分享红烧肉的做法，之前都为家常菜版本，对菜品的外形没有过分的要求。但有不少朋友问怎么才能做出酒店版本的红烧肉，那种很方正但又特别软糯的，今天就来和大家破解其中的秘密！技术总结从之前的文字分享改变成了动态分享，希望大家喜欢！
Hello everyone, today I am making “red braised pork”. This is the third time that I am sharing a recipe of red braised pork. I have made home style red braised pork before, I never held high standard on the dish appearance. But many friends are asking how do you make a restaurant version of red braised pork. Today, let’s debunk the secrets of restaurant style red braised pork. Technical summary has changed from text to video, I hope you all like it.

本期菜品【红烧肉】
Today’s dish: Red Braised Pork

【主料】
Ingredients

五花肉（1大块）
Pork Belly (One large piece)

【配料】
Other Ingredients

红酒（适量）
Red Wine (Some)
大葱（4根）
Spring Onions (4 pieces)
生姜（2小块）
Ginger (2 small pieces)
植物油（适量）
Vegetable Oil (Some)
姜葱油（少许）
Ginger Scallion Oil (A little)
冰糖（1小块）
White Rock Sugar (A small piece)
糖色（10克）
Caramelized Sugar (10g)
桂皮（2小块）
Cinnamon (2 small pieces)
西兰花（适量）
Broccoli (Some) 

【调味料】
[Seasoning]

食用盐（适量）
Salt (Some)

字幕
0:00:00.468,0:00:01.678
哈喽大家好我是王刚
Hello everyone, I am Wang Gang

0:00:01.678,0:00:03.790
本期视频我跟大家分享一道拿手菜
In this video, I am sharing with you the dish I am very good at

0:00:04.259,0:00:06.130
电饭锅红烧肉
Rice cooker red braised pork

0:00:06.541,0:00:09.869
首先我们准备新鲜且富有弹性的五花肉一大块
First, we prepare a large piece of fresh and bouncy pork belly

0:00:10.340,0:00:13.190
不喜欢五花肉的同学也可以选择二刀肉
If you don’t like pork belly, you can also choose pork hind leg top cut

0:00:14.857,0:00:17.289
然后在托盘中加入适量的清水
Then we add some water into the tray 

0:00:22.108,0:00:23.670
下一步开始烧皮
Next, we start torching the skin

0:00:25.623,0:00:28.169
首先用喷枪把猪皮烧至焦黑色
We will torch and burn the skin to black color first

0:00:28.580,0:00:30.214
第一遍是去除猪毛
The first time is to remove the hair

0:00:37.257,0:00:39.062
第二遍是烧至皮黄
The second time is to torch the skin until it is yellow

0:00:45.527,0:00:47.195
第三遍才是烧至焦黑
The third time is to torch it until it is black

0:00:47.608,0:00:50.700
托盘中加水的目的是防止托盘受热变形
Adding water in the tray is to prevent the tray to deform while being heated

0:00:51.633,0:00:53.672
烧至焦黑之后用钢丝球或者菜刀
After torching it black, we use stainless steel scrubber or knife 

0:00:53.672,0:00:55.656
将烧焦的部分刮洗干净
To remove the burnt part and wash it clean

0:01:07.956,0:01:09.812
刮洗干净之后开始分肉
After cleaning the meat, we can start dividing the meat

0:01:10.000,0:01:12.080
首先带乳头的部分容易分层
First, the part that has nipples is very easy to split between layers

0:01:12.080,0:01:13.400
但瘦肉比较多
But it has a lot of lean meat

0:01:23.031,0:01:24.940
最后的部分肥肉比较厚重
The last part has a lot more fat

0:01:25.220,0:01:28.109
而中间部分则不肥不瘦比较紧实
The middles part is not too lean or too fat, very firm

0:01:28.792,0:01:31.460
然后我们取中间部分下一步开始煮肉
Then we will take the middle part to continue cooking

0:01:31.736,0:01:34.458
将五花肉放入电饭锅中加入适量的清水
Put the pork belly into rick cooker and add some water

0:01:41.660,0:01:43.335
加入适量的红酒
Add some red wine

0:01:49.669,0:01:51.950
准备大葱两根切成小段加入
Prepare a couple spring onions, add them in after cut them into small pieces 

0:01:55.174,0:01:57.749
准备生姜一小块切成姜片备用
Prepare a small piece of ginger and slice them for later use

0:02:00.565,0:02:02.920
然后接上电源将五花肉煮至断生
Then power it up and cook the pork belly

0:02:03.197,0:02:06.120
此过程根据不同的电饭锅煮制的时间也不同
This process could take various length of time depending on which rice cooker you use

0:02:13.673,0:02:16.681
大约20分钟之后用筷子能插透即可捞出
In about 20 mins later, you can take the meat out if chopsticks can penetrate it

0:02:26.520,0:02:29.210
猪肉捞出之后均匀的撒上适量的食用盐
Put some salt on the pork after taking it out

0:02:31.233,0:02:32.948
下一步开始准备炸皮
Next, we start to fry the skin

0:02:33.820,0:02:35.652
首先我们把锅烧热
We heat up the wok first

0:02:35.837,0:02:38.318
锅烧热之后加入一勺植物油烧热
After the wok is heated, we can add a scoop of vegetable oil

0:02:41.061,0:02:44.708
油温烧至六成热之后将猪皮朝下炸至金黄色
When the oil is about 180 Celsius, we can put the pork in skin down until its golden brown 

0:02:45.020,0:02:48.060
这一步的目的是保证红烧肉软而皮不烂
This step is to make sure the red braised pork will be soft, but the skin doesn’t fall apart

0:03:09.276,0:03:12.254
炸至金黄色之后捞出皮朝下放入托盘中
After it is golden brown, put it on the tray skin down

0:03:13.921,0:03:16.242
然后准备一个小托盘压在上面
Then prepare another smaller tray on top of it

0:03:17.215,0:03:19.670
也可以用重物或者胶带缠紧
You can also use heavy object or tape to tighten it

0:03:34.527,0:03:37.086
猪肉压紧之后放入冰箱冰冻一个小时
After pressing the pork firm, you can put it into the freezer for an hour

0:03:37.300,0:03:40.716
这一步的目的是防止猪肉下锅热胀冷缩导致变形
This step is to prevent the pork expand or shrink due to change of the temperature, resulting in deforming of the pork belly 

0:03:40.980,0:03:44.190
冰冻一个小时之后将肉取出切成小方块备用
After freezing for an hour, take the meat out and cut them into small cubes

0:03:53.935,0:03:55.304
理论上切得越大
Theoretically, the bigger you cut them

0:03:55.520,0:03:56.560
则烧得越久
It will take longer to braise

0:03:56.912,0:03:59.220
相反切得越小块时间则越短
On the contrary, the smaller you cut them, the shorter it takes to braise them 

0:04:09.820,0:04:12.252
然后将切好的猪肉放入锅中
Then put the pork cubes you cut into the cooker

0:04:14.293,0:04:16.278
准备生姜一小块拍散备用
Prepare a small ginger and smash it for later use

0:04:17.174,0:04:19.228
准备大葱两根切成小段备用
Prepare a couple spring onions into small piece for later use

0:04:20.551,0:04:22.012
锅中加入适量的清水
Add some water into the cooker

0:04:22.384,0:04:24.465
水的量需要参考电饭锅的火力
The amount of water you need to consider the heat rice cooker can generate

0:04:24.465,0:04:26.620
以及水分蒸发的时间等等
And the time it takes for the water to evaporate

0:04:31.740,0:04:33.630
锅中加入少许的姜葱油
Adding a little ginger scallion oil 

0:04:33.680,0:04:35.970
没有姜葱油的同学也可以不加
If you do not have ginger scallion oil, it’s fine if you don’t add it

0:04:36.460,0:04:38.038
加入冰糖一小块
Add a small piece of white rock sugar

0:04:38.860,0:04:40.278
加入红酒60克
Add 60g of red wine

0:04:40.278,0:04:43.517
没有红酒的同学也可以用黄酒或者料酒代替
If you don’t have red wine, you can also use huangjiu rice wine or Chinese cooking wine

0:04:44.220,0:04:45.588
加入糖色10克
Add 10g of caramelized sugar

0:04:54.062,0:04:55.658
最后加入桂皮两小块
At the end, add a couple pieces of cinnamon

0:04:56.680,0:04:59.118
然后盖上盖子煮120分钟
Then cover it and cook it for 120 minutes

0:05:03.357,0:05:06.106
烧至60分钟的时候捡去姜葱香料不要
After cooking for 60 minutes, remove the ginger, spring onions and other ingredients

0:05:15.691,0:05:17.803
然后加入适量的食用盐调咸味
Then add some salt for saltiness 

0:05:17.960,0:05:20.220
调好味之后继续烧剩余的时间
After adjusting the flavor, I will continue to cook for the rest of the 120 minutes

0:05:24.420,0:05:27.570
中途需要定时揭开锅盖查看水量是否烧干
While cooking, we need to open the cooker and check if majority of the water are evaporated every now and then

0:05:33.660,0:05:37.453
烧够两个小时之后水分略干且汤汁浓稠即可出锅
After 2 hours, when the water is mostly evaporated and the sauce is very thick, we can take the meat out

0:05:37.580,0:05:39.020
同学们汤汁是否浓稠
Everyone you know, whether or not the sauce is thick

0:05:39.020,0:05:40.500
除了肉胶的作用之外
Not only because of the effect of the collagen in the meat

0:05:40.500,0:05:42.460
冰糖也起到了很大的作用
But also because of the white rock sugar

0:05:52.515,0:05:54.448
然后准备烧热的小石锅一个
Then prepare a small hot stone pot

0:05:54.448,0:05:56.440
加入焯好水的西兰花垫底
Add some blanched broccoli in the bottom

0:05:56.560,0:05:59.958
同学们选用烧热的石锅可以增加成菜的保温时间
Everyone, the reason I choose a hot stone pot is because it can keep the dish warm for a while

0:06:00.240,0:06:02.750
没有石锅的同学也可以选用砂锅
If you do not have a stone pot you can also use a clay pot

0:06:03.129,0:06:05.434
蔬菜垫底之后依次加入红烧肉
After putting the vegetables on the bottom, then you can add the red braised pork on top of them

0:06:11.950,0:06:14.193
最后淋上剩余的汤汁即可上菜
At the end, pour the sauce over the dish then we present it

0:06:18.000,0:06:21.222
一道肥而不腻的电饭锅红烧肉就制作完成
A fat but not greasy rice cooker red braised pork is finished

0:06:23.786,0:06:25.360
下面开始技术总结
Now here are the technical summary

0:06:25.800,0:06:28.160
第一五花肉部位的选择
First is how we choose the pork belly cut

0:06:28.200,0:06:30.480
五花肉边上带乳头的部位比较瘦
The side of the pork belly with nipples is leaner

0:06:30.560,0:06:33.449
但肉比较松容易脱层影响美观
But the meat is loose and easy to split between layers

0:06:39.680,0:06:42.040
同样最后的位置肉最Q弹
And the back part of the pork belly is very tender

0:06:42.080,0:06:44.320
但肥肉最多很容易腻口
But it has the fattest meat so it got greasy very fast

0:06:49.560,0:06:51.400
中间的五花肉肥瘦参半
The middle part of pork belly is balanced with fat and lean meat

0:06:51.440,0:06:52.360
且不脱层
And it is not that easy to split between layers

0:06:52.680,0:06:54.480
所以比较适合红烧肉的原料是
So, the cut that fit red braised pork is

0:06:54.480,0:06:56.080
不肥不瘦的中间部位
The middle part that is well balance with far and lean meat

0:07:05.020,0:07:05.860
第二
Secondly

0:07:05.900,0:07:07.460
电饭锅火力虽然小
Although rice cooker can not generate a lot of heat

0:07:07.500,0:07:09.048
但是很容易将猪肉烧透
But it is easy to fully cook the pork

0:07:09.048,0:07:11.908
口感上来说比高压锅出品更加弹牙
And the texture is better than the ones cooked by high pressure cooker

0:07:12.056,0:07:14.100
家庭长时间炖肉容易被遗忘
Cooking it for a long time at home, it’s easy to forget the meat is still cooking

0:07:14.140,0:07:17.028
而电饭锅也可以自动跳闸也显得更加的安全
And the rice cooker can automatically stop cooking so it is safer this way

0:07:17.180,0:07:17.879
第三
Third

0:07:18.208,0:07:20.640
炸肉之前可以先涂抹一层食用盐
Before frying the meat, we can rub some salt on the surface

0:07:20.760,0:07:22.880
这样可以防止猪肉油脂爆炸
This way we can prevent the oil to splash while frying

0:07:22.920,0:07:25.574
即使猪肉很肥下锅也不容易炸锅
Even when the meat is very fatty, it is not easy to splash while frying

0:07:32.787,0:07:34.855
下面进行不抹盐下锅测试
Now let’s make an experiment without rubbing the salt on it

0:07:35.006,0:07:36.646
大家可以很显然的感受到
We can obviously feel that

0:07:36.646,0:07:38.461
猪肉的油脂已经炸裂
The oil in the pork is already burst

0:07:38.645,0:07:40.301
同学们这一步比较危险
This step is very dangerous

0:07:40.557,0:07:41.512
请勿模仿
Please don’t do this at home

0:07:41.815,0:07:45.981
肉皮经过油炸之后即使烧很长时间也能够保持原型不烂
After frying the skin, even if we braise the pork for a long time, the cube will stay in shape

0:07:46.141,0:07:46.708
第四
Fourth

0:07:47.136,0:07:49.581
未加冰冻的肉也可以直接切块烧
You can also braise the unfrozen meat

0:07:49.581,0:07:53.170
但猪肉会热胀冷缩导致成品膨胀不方正
But the pork will deform due the change of the temperature

0:07:53.371,0:07:55.220
解决这个问题最好的方法就是用
The best solution for this problem is 

0:07:55.220,0:07:57.100
重物平压冰冻一个小时
To use heavy object to hold it down in the freezer for an hour

0:08:08.846,0:08:11.410
这样操作过的红烧肉显得方方正正
After this, the red braised pork will stay in shape as a neat cube

0:08:11.460,0:08:12.950
且不影响口感
It won’t affect the texture 

0:08:13.060,0:08:15.090
以下大家可以看一下对比
Here is the comparison for you

0:08:20.475,0:08:21.244
第五
Fifth

0:08:21.244,0:08:23.931
加红酒烧肉可以分解肥肉中的油脂
Adding alcohol here is to wash down the grease

0:08:23.931,0:08:26.671
红酒加得越多则越不容易腻
The more wine you add, the less greasy the pork will taste like

0:08:34.200,0:08:36.960
在最后吃的时候可以配上酸萝卜和红酒
At then end when you eat it, you can eat it with pickled radish and red wine

0:08:36.960,0:08:38.357
这样也可以解腻
This is good for washing down the grease too

0:08:38.357,0:08:39.968
红烧肉的技术总结完毕
This is the end of technical summary in red braised pork
