### ISSUE TITLE
[老饭骨] 葱烧海参 - https://youtu.be/Ope_ow82QKU

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1307]
**视频链接**：https://youtu.be/Ope_ow82QKU

发布日期：北京时间7月22日晚上10点，时长8分49秒。（后面问题解答的字幕有问题所以没能有时间轴版本的）

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【國宴大師•蔥燒海參】家庭版做法媲美大飯店品質，軟糯香滑，頂級大廚教你做不吊湯也夠味兒的蔥燒海參！| 料酒、花雕、黃酒的區別|老飯骨

简介
小友們好，今天二伯要給大傢伙兒露一手嘍！著名的魯菜——蔥燒海參的家庭版做法奉上，不像酒店裡那麼複雜，但做出來的味道絕對媲美大飯店，讓你在家也能吃到高品質的美味！蔥香味濃、海參口感軟糯、入味，絕對是必學的一道經典大菜！
本期片尾還有大爺、二伯為大家講解料酒、花雕酒和黃酒的區別，之前有許多小友們提問，千萬不要錯過了哦！

字幕
1
00:00:00,000 --> 00:00:01,400
大爷过去烧海参

2
00:00:01,400 --> 00:00:04,280
得做什么你知道吗 熬点好汤

3
00:00:04,280 --> 00:00:05,280
今儿不要汤

4
00:00:05,280 --> 00:00:07,120
所以说就能烧出这个味道来

5
00:00:07,120 --> 00:00:08,240
到时候您看一看

6
00:00:08,240 --> 00:00:11,040
关键是我这做法太简单了

7
00:00:11,040 --> 00:00:12,320

8
00:00:12,320 --> 00:00:14,880
拍拍 充分的出味

9
00:00:14,880 --> 00:00:20,200
大姜 葱叶子 咱就把海参焯一焯

10
00:00:20,200 --> 00:00:23,200
温水下锅 给大家教一个家庭版的

11
00:00:23,200 --> 00:00:26,520
酒店还得拿好汤煨 有的还得鲍汁煨

12
00:00:26,520 --> 00:00:27,880
那就废了人劲了

13
00:00:27,880 --> 00:00:31,440
料酒（黄酒）去去海参的腥味

14
00:00:31,440 --> 00:00:33,280
家庭版的烧海参

15
00:00:33,280 --> 00:00:36,320
这时候咱们就切葱 把它切成细条

16
00:00:36,320 --> 00:00:37,760
更好的释放味道

17
00:00:37,760 --> 00:00:40,760
师父这些葱丝咱们是炸葱油是吧

18
00:00:40,760 --> 00:00:45,880
海参行了 主要是软硬程度 冲水

19
00:00:46,080 --> 00:00:48,920
花生油 咱们多来点

20
00:00:48,920 --> 00:00:52,040
葱烧海参香不香 主要是看这锅油

21
00:00:52,040 --> 00:00:54,480
料也得足 大葱（和香葱）葱丝

22
00:00:54,480 --> 00:00:57,760
温油下锅让它耗着这味儿就行了

23
00:00:57,760 --> 00:01:00,800
小火慢熬别着急

24
00:01:00,800 --> 00:01:02,040
这是基础做法

25
00:01:02,040 --> 00:01:04,360
你愿意加点其他的也可以

26
00:01:04,360 --> 00:01:07,000
但是我这种方法比较简单

27
00:01:07,000 --> 00:01:09,880
反过来它的味道还非常浓

28
00:01:09,880 --> 00:01:11,720
师父这个分两次下

29
00:01:11,720 --> 00:01:13,200
是先把葱白熬一下

30
00:01:13,200 --> 00:01:15,200
最后下的小香葱叶

31
00:01:15,200 --> 00:01:17,440
网友朋友们一定要注意火不能大

32
00:01:17,440 --> 00:01:20,840
一定要把葱的味完全的给它熬出来

33
00:01:20,840 --> 00:01:22,240
香味出来了

34
00:01:22,240 --> 00:01:25,000
两种葱香味更浓

35
00:01:25,000 --> 00:01:28,200
这就差不多了大爷 赶紧捞

36
00:01:28,200 --> 00:01:30,280

37
00:01:30,280 --> 00:01:31,600
网友朋友们一定要注意

38
00:01:31,600 --> 00:01:34,040
这个葱绝对要炸金黄色 不能糊了

39
00:01:35,800 --> 00:01:37,520
师父这锅水是做什么使的

40
00:01:37,520 --> 00:01:39,640
在家庭里边不可能烧一盘海参

41
00:01:39,640 --> 00:01:43,160
再买一只老母鸡吊汤去 那怎么办

42
00:01:43,160 --> 00:01:48,080
就得用这种家常版的这种方式

43
00:01:48,080 --> 00:01:51,000
用这水把葱泡上

44
00:01:52,000 --> 00:01:54,240
或者有条件还可以煮一煮

45
00:01:54,240 --> 00:01:56,360
搁点酒啊 酱油啊

46
00:01:56,360 --> 00:01:59,480
煮完了以后调好一个烧海参的汁

47
00:01:59,480 --> 00:02:02,320
这个效果出来以后香味就十足了

48
00:02:03,200 --> 00:02:05,800
然后第二步我再坐点水

49
00:02:05,800 --> 00:02:08,960
葱切条 这是烧海参的里边的葱条

50
00:02:08,960 --> 00:02:12,680
水开了大爷 我们调调味道

51
00:02:12,680 --> 00:02:17,320
酱油

52
00:02:17,320 --> 00:02:19,800
（白）胡椒粉

53
00:02:19,800 --> 00:02:23,520
补充点糖  料酒

54
00:02:23,520 --> 00:02:26,240
可多可少 这东西根据情况

55
00:02:26,240 --> 00:02:30,760
这样你看我们把海参就下去

56
00:02:30,760 --> 00:02:33,400
下海参 擦边下

57
00:02:33,400 --> 00:02:36,040
你看我师父这手法 擦边下

58
00:02:36,040 --> 00:02:38,160
然后你看这水还有点浅

59
00:02:38,160 --> 00:02:43,920
我们再加点老抽 这就行了

60
00:02:43,920 --> 00:02:47,360
我再补点盐 我们现在煮它一会儿

61
00:02:47,360 --> 00:02:48,400
这海参你看见没有

62
00:02:48,400 --> 00:02:51,840
这就是我第一次焯 第二次煨

63
00:02:51,840 --> 00:02:56,240
这要是在咱们酒店里边 用点毛汤

64
00:02:56,240 --> 00:02:57,640
因为咱们在家里边没有

65
00:02:57,640 --> 00:03:01,760
就得靠调味品

66
00:03:01,760 --> 00:03:04,600
增加它的香味 去掉它的腥味

67
00:03:04,600 --> 00:03:08,120
要巧妙的灵活的去做

68
00:03:08,120 --> 00:03:10,400
你看见没有 来点葱油

69
00:03:10,400 --> 00:03:13,160
你看一加油它就容易化

70
00:03:13,160 --> 00:03:15,360
但是我怕它化了我后加油

71
00:03:15,360 --> 00:03:19,360
海参最怕的就是加油加的太早

72
00:03:19,360 --> 00:03:21,240
为什么咱们酒店里边

73
00:03:21,240 --> 00:03:23,840
煨海参的时候用毛汤

74
00:03:23,840 --> 00:03:25,840
毛汤里边没有油

75
00:03:25,840 --> 00:03:29,200
你要用那好汤 油大

76
00:03:29,200 --> 00:03:30,680
一会海参 好家伙

77
00:03:30,680 --> 00:03:32,880
本来一盘海参 剩半盘了

78
00:03:32,880 --> 00:03:34,560
这海参行了 我捞出来

79
00:03:35,840 --> 00:03:36,760
泡着

80
00:03:36,760 --> 00:03:41,080
把泡葱的汤给它提出来

81
00:03:41,080 --> 00:03:44,320
就这里边的香气 必须让它顶出来

82
00:03:44,320 --> 00:03:46,600
这叫物理压榨

83
00:03:46,600 --> 00:03:48,440
这就行了 搁这里

84
00:03:48,440 --> 00:03:52,760
这时候我们用煸的好的葱油

85
00:03:52,760 --> 00:03:56,600
把葱条下锅 葱条先下去

86
00:03:56,600 --> 00:04:02,240
还是小火 慢慢的煸 煸成金黄色

87
00:04:02,240 --> 00:04:05,160
这样它的香气全出来了

88
00:04:05,160 --> 00:04:09,080
好了好了 料酒 多烹点没事儿

89
00:04:09,080 --> 00:04:16,640
酱油 顺着锅边儿一煸 

90
00:04:16,640 --> 00:04:20,800
烹起来 香气出来了

91
00:04:20,800 --> 00:04:25,160
再来点好汤 你看这个

92
00:04:25,160 --> 00:04:29,720
物理压榨法 记住这个词语网友朋友们

93
00:04:29,720 --> 00:04:33,760
海参下锅 调点味

94
00:04:33,760 --> 00:04:35,800
加点糖  不要多

95
00:04:35,800 --> 00:04:40,800
小点火 （白）胡椒

96
00:04:40,800 --> 00:04:44,920
用小火煨着 煨着入味

97
00:04:44,920 --> 00:04:47,320
旁边我给我师父打个下手

98
00:04:47,320 --> 00:04:50,720
弄个小菜心 搁点葱油搁点盐

99
00:04:50,720 --> 00:04:53,280
勾芡了啊 海参好了

100
00:04:53,280 --> 00:04:56,440
勾芡 

101
00:04:56,440 --> 00:05:00,480
得开大火了

102
00:05:05,040 --> 00:05:06,680
再来点芡

103
00:05:08,400 --> 00:05:12,840
这勾芡最好是两次到三次

104
00:05:12,840 --> 00:05:16,560
不要一次性勾成  边收汁边勾芡

105
00:05:16,560 --> 00:05:19,480
来点油吧 慢慢来

106
00:05:19,480 --> 00:05:24,080
过去讲究 点点儿葱油

107
00:05:25,800 --> 00:05:32,080
过去讲究淋三次油 亮啊

108
00:05:34,440 --> 00:05:37,080
别着急 慢慢的 这时候就慢慢的烧

109
00:05:37,080 --> 00:05:40,240
海参的窍门在这儿呢 好了好了

110
00:05:40,240 --> 00:05:43,320
几勺油加的漂亮 最后越裹越亮

111
00:05:43,320 --> 00:05:48,200
汁芡融合一体 油也融合一体 装盘

112
00:05:48,200 --> 00:05:54,080
葱汁完全的包裹着海参 葱香味浓

113
00:05:54,080 --> 00:05:58,120
汁儿颜色红亮 非常非常地道

114
00:05:58,120 --> 00:05:59,360

115
00:06:02,680 --> 00:06:06,480
怎么样 我这儿都闻着这个味了 真香

116
00:06:06,480 --> 00:06:09,480
糯香 葱香 酒香

117
00:06:09,480 --> 00:06:10,760

118
00:06:11,760 --> 00:06:17,560
软糯 滑 而且入味 关键是入味 真棒

119
00:06:17,560 --> 00:06:18,920
一点腥味都没有

120
00:06:18,920 --> 00:06:19,720
顺便说一下

121
00:06:19,720 --> 00:06:24,480
二伯为什么是三遍勾芡三遍淋油

122
00:06:24,480 --> 00:06:27,200
你看我们有很多人在做菜

123
00:06:27,200 --> 00:06:29,440
为什么得动脑子 要精巧

124
00:06:29,440 --> 00:06:31,600
通过勾芡收汁

125
00:06:31,600 --> 00:06:36,360
使汁芡把原材料包裹的融为一体

126
00:06:36,360 --> 00:06:38,520
现你看现在你看这盘汁

127
00:06:38,520 --> 00:06:39,560

128
00:06:39,560 --> 00:06:40,720
不见油

129
00:06:40,720 --> 00:06:43,800
但是海参又挺亮

130
00:06:43,800 --> 00:06:47,040
这就是做菜的诀窍

131
00:06:47,040 --> 00:00:02,000

**Comment by Koi111** [comment]
认领

**Comment by Koi111** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【國宴大師•蔥燒海參】家庭版做法媲美大飯店品質，軟糯香滑，頂級大廚教你做不吊湯也夠味兒的蔥燒海參！| 料酒、花雕、黃酒的區別|老飯骨
State Banquet Master Chefs -Sea Cucumbers with Spring Onions. Differences between Chinese cooking wine
简介
小友們好，今天二伯要給大傢伙兒露一手嘍！
Hey friends! Today Er Bai will teach us something.
著名的魯菜——蔥燒海參的家庭版做法奉上，不像酒店裡那麼複雜，但做出來的味道絕對媲美大飯店，讓你在家也能吃到高品質的美味！
Homemade version of a famous dish in Shandong cuisine, Sea Cucumbers with Spring Onions. The cooking steps are not that complicated as in big restaurants, but the flavour can definitely compete with the dishes in big restaurants. You can have wonderful delicacies at home too!
蔥香味濃、海參口感軟糯、入味，絕對是必學的一道經典大菜！
With the strong fragrance of spring onions and the tender sea cucumbers, this is an authentic dish that you have to try and learn!
本期片尾還有大爺、二伯為大家講解料酒、花雕酒和黃酒的區別，之前有許多小友們提問，千萬不要錯過了哦！
At the end of this video, Da Ye and Er Bai are going to talk about the differences between Chinese cooking wine, Huadiao rice wine and huangjiu rice wine because lots of friends asked about this, so stay tuned.

字幕
1
00:00:00,000 --> 00:00:01,400
大爷过去烧海参
Da Ye, when we cook sea cucumbers in the past,

2
00:00:01,400 --> 00:00:04,280
得做什么你知道吗 熬点好汤
Do you know what do we have to do? Make some great broth.

3
00:00:04,280 --> 00:00:05,280
今儿不要汤
We don’t need excellent broth today

4
00:00:05,280 --> 00:00:07,120
所以说就能烧出这个味道来
But I can still make an excellent sea cucumbers dish

5
00:00:07,120 --> 00:00:08,240
到时候您看一看
So please look as I cook this

6
00:00:08,240 --> 00:00:11,040
关键是我这做法太简单了
The key is that the steps are really simple

7
00:00:11,040 --> 00:00:12,320

8
00:00:12,320 --> 00:00:14,880
拍拍 充分的出味
Crush it, so that we can release the flavours better

9
00:00:14,880 --> 00:00:20,200
大姜 葱叶子 咱就把海参焯一焯
Ginger, leafy parts in spring onions, let’s parboil the sea cucumbers

10
00:00:20,200 --> 00:00:23,200
温水下锅 给大家教一个家庭版的
-Add the sea cucumbers when the water is warm -Teach you guys a homemade version

11
00:00:23,200 --> 00:00:26,520
酒店还得拿好汤煨 有的还得鲍汁煨
In some big restaurants, they would cook it with high-quality broth or abalone broth

12
00:00:26,520 --> 00:00:27,880
那就废了人劲了
That’s too energy-consuming

13
00:00:27,880 --> 00:00:31,440
料酒（黄酒）去去海参的腥味
Add some huangjiu rice wine to remove the gamey taste

14
00:00:31,440 --> 00:00:33,280
家庭版的烧海参
Homemade version of brewed sea cucumbers

15
00:00:33,280 --> 00:00:36,320
这时候咱们就切葱 把它切成细条
Now let’s cut the spring onions into long strips

16
00:00:36,320 --> 00:00:37,760
更好的释放味道
to release the flavour better

17
00:00:37,760 --> 00:00:40,760
师父这些葱丝咱们是炸葱油是吧
Master, these spring onions are used to make scallion oil right?

18
00:00:40,760 --> 00:00:45,880
海参行了 主要是软硬程度 冲水
The sea cucumbers are done, we just have to pay attention to their tenderness. Rinse it

19
00:00:46,080 --> 00:00:48,920
花生油 咱们多来点
Peanut oil, put more of it

20
00:00:48,920 --> 00:00:52,040
葱烧海参香不香 主要是看这锅油
The fragrance of this dish mainly depends on this oil

21
00:00:52,040 --> 00:00:54,480
料也得足 大葱（和香葱）葱丝
There should be sufficient ingredients, including spring onions and scallions

22
00:00:54,480 --> 00:00:57,760
温油下锅让它耗着这味儿就行了
Add them in when the oil is still warm so that they have enough time to release all of their flavour

23
00:00:57,760 --> 00:01:00,800
小火慢熬别着急
Fry them with low heat, don’t be so eager

24
00:01:00,800 --> 00:01:02,040
这是基础做法
This is a basic method

25
00:01:02,040 --> 00:01:04,360
你愿意加点其他的也可以
You can add other ingredients if you want

26
00:01:04,360 --> 00:01:07,000
但是我这种方法比较简单
But this is a simple way

27
00:01:07,000 --> 00:01:09,880
反过来它的味道还非常浓
Conversely, the flavour is very rich and intense

28
00:01:09,880 --> 00:01:11,720
师父这个分两次下
Master’s method can be divided into 2 parts

29
00:01:11,720 --> 00:01:13,200
是先把葱白熬一下
Fry the white parts of the spring onions first,

30
00:01:13,200 --> 00:01:15,200
最后下的小香葱叶
Then the leafy parts and scallions

31
00:01:15,200 --> 00:01:17,440
网友朋友们一定要注意火不能大
Remember to not fry this under high heat, my friends

32
00:01:17,440 --> 00:01:20,840
一定要把葱的味完全的给它熬出来
We must let the spring onions to release their flavour completely

33
00:01:20,840 --> 00:01:22,240
香味出来了
The fragrance is released now

34
00:01:22,240 --> 00:01:25,000
两种葱香味更浓
It is richer with two kinds of fragrance from different onions

35
00:01:25,000 --> 00:01:28,200
这就差不多了大爷 赶紧捞
It’s almost done now Da Ye, please strain it immediately

36
00:01:28,200 --> 00:01:30,280

37
00:01:30,280 --> 00:01:31,600
网友朋友们一定要注意
Friends, please pay attention to this,

38
00:01:31,600 --> 00:01:34,040
这个葱绝对要炸金黄色 不能糊了
The spring onions and scallions have to be in golden colour, don’t burn them

39
00:01:35,800 --> 00:01:37,520
师父这锅水是做什么使的
Master, why do we have this water over here

40
00:01:37,520 --> 00:01:39,640
在家庭里边不可能烧一盘海参
When we cook sea cucumbers at home, it’s impossible that 

41
00:01:39,640 --> 00:01:43,160
再买一只老母鸡吊汤去 那怎么办
we purposely buy an old hen just to cook a pot of broth. So what can we do?

42
00:01:43,160 --> 00:01:48,080
就得用这种家常版的这种方式
We have to use ways that are more suitable for home-cooking

43
00:01:48,080 --> 00:01:51,000
用这水把葱泡上
Soak the spring onions and scallion with the water

44
00:01:52,000 --> 00:01:54,240
或者有条件还可以煮一煮
You can cook it for a while too

45
00:01:54,240 --> 00:01:56,360
搁点酒啊 酱油啊
Add some wine and light soy sauce

46
00:01:56,360 --> 00:01:59,480
煮完了以后调好一个烧海参的汁
Make a sauce for the sea cucumbers once you finished cooking the onion water

47
00:01:59,480 --> 00:02:02,320
这个效果出来以后香味就十足了
The aroma would be wonderful if you follow this step

48
00:02:03,200 --> 00:02:05,800
然后第二步我再坐点水
For the next step is to add some water again

49
00:02:05,800 --> 00:02:08,960
葱切条 这是烧海参的里边的葱条
Cut the spring onions into strips, these are the ones for the dish

50
00:02:08,960 --> 00:02:12,680
水开了大爷 我们调调味道
The water is boiled now, let’s season it

51
00:02:12,680 --> 00:02:17,320
酱油
Light soy sauce

52
00:02:17,320 --> 00:02:19,800
（白）胡椒粉
Grounded white pepper

53
00:02:19,800 --> 00:02:23,520
补充点糖  料酒
Add some sugar and Chinese cooking wine

54
00:02:23,520 --> 00:02:26,240
可多可少 这东西根据情况
The amount is adjustable, it depends on the situation

55
00:02:26,240 --> 00:02:30,760
这样你看我们把海参就下去
Look, now we add the sea cucumbers

56
00:02:30,760 --> 00:02:33,400
下海参 擦边下
We have to add them from the side of the wok

57
00:02:33,400 --> 00:02:36,040
你看我师父这手法 擦边下
Look at my master’s technique, add them from the side

58
00:02:36,040 --> 00:02:38,160
然后你看这水还有点浅
The colour of the broth is not dark enough

59
00:02:38,160 --> 00:02:43,920
我们再加点老抽 这就行了
Add some dark soy sauce and it’s ok now

60
00:02:43,920 --> 00:02:47,360
我再补点盐 我们现在煮它一会儿
Add some salt and cook it for a while

61
00:02:47,360 --> 00:02:48,400
这海参你看见没有
Look at the sea cucumbers

62
00:02:48,400 --> 00:02:51,840
这就是我第一次焯 第二次煨
Parboil it first, then cook it later

63
00:02:51,840 --> 00:02:56,240
这要是在咱们酒店里边 用点毛汤
If we are cooking this dish in a big restaurant, we would be using meat broth

64
00:02:56,240 --> 00:02:57,640
因为咱们在家里边没有
But we don’t have that in our house

65
00:02:57,640 --> 00:03:01,760
就得靠调味品
So we have to rely on seasonings

66
00:03:01,760 --> 00:03:04,600
增加它的香味 去掉它的腥味
to increase the aroma and remove the gamey taste

67
00:03:04,600 --> 00:03:08,120
要巧妙的灵活的去做
We have to cook with flexible steps and smart ways

68
00:03:08,120 --> 00:03:10,400
你看见没有 来点葱油
Can you see that? Add some scallion oil

69
00:03:10,400 --> 00:03:13,160
你看一加油它就容易化
The sea cucumbers would be more tender when you add oil

70
00:03:13,160 --> 00:03:15,360
但是我怕它化了我后加油
I’m afraid that it would be too soft, so I add the oil later on

71
00:03:15,360 --> 00:03:19,360
海参最怕的就是加油加的太早
We must avoid adding oil too early when we are cooking sea cucumbers

72
00:03:19,360 --> 00:03:21,240
为什么咱们酒店里边
When we are cooking in restaurants,

73
00:03:21,240 --> 00:03:23,840
煨海参的时候用毛汤
Why do we use meat stock?

74
00:03:23,840 --> 00:03:25,840
毛汤里边没有油
That’s because there isn’t much oil in meat broth

75
00:03:25,840 --> 00:03:29,200
你要用那好汤 油大
If you use some rich broth, it would be too oily

76
00:03:29,200 --> 00:03:30,680
一会海参 好家伙
and the sea cucumbers,

77
00:03:30,680 --> 00:03:32,880
本来一盘海参 剩半盘了
The size of the sea cucumbers would be reduced by half

78
00:03:32,880 --> 00:03:34,560
这海参行了 我捞出来
The sea cucumbers are done now, let’s set them aside

79
00:03:35,840 --> 00:03:36,760
泡着
Immerse them for a while

80
00:03:36,760 --> 00:03:41,080
把泡葱的汤给它提出来
Strain the broth with the spring onions in it

81
00:03:41,080 --> 00:03:44,320
就这里边的香气 必须让它顶出来
We have to push them so that the flavour can be released fully

82
00:03:44,320 --> 00:03:46,600
这叫物理压榨
This is how we obtain the flavour physically

83
00:03:46,600 --> 00:03:48,440
这就行了 搁这里
It’s done, just put it aside

84
00:03:48,440 --> 00:03:52,760
这时候我们用煸的好的葱油
Now let’s use the scallion oil we just made

85
00:03:52,760 --> 00:03:56,600
把葱条下锅 葱条先下去
Add the spring onion strips first

86
00:03:56,600 --> 00:04:02,240
还是小火 慢慢的煸 煸成金黄色
Using small heat and fry the spring onion slowly

87
00:04:02,240 --> 00:04:05,160
这样它的香气全出来了
The aroma can be released fully

88
00:04:05,160 --> 00:04:09,080
好了好了 料酒 多烹点没事儿
Okay, add some more Chinese cooking wine please

89
00:04:09,080 --> 00:04:16,640
酱油 顺着锅边儿一煸 
Add the soy sauce around the sides of the wok

90
00:04:16,640 --> 00:04:20,800
烹起来 香气出来了
Heat it first to bring out the aroma

91
00:04:20,800 --> 00:04:25,160
再来点好汤 你看这个
Add some broth, look at this

92
00:04:25,160 --> 00:04:29,720
物理压榨法 记住这个词语网友朋友们
Obtaining flavour physically, remember this please my friends

93
00:04:29,720 --> 00:04:33,760
海参下锅 调点味
Add the sea cucumbers and season them

94
00:04:33,760 --> 00:04:35,800
加点糖  不要多
Some sugar, not too much

95
00:04:35,800 --> 00:04:40,800
小点火 （白）胡椒
Lower the heat, white pepper

96
00:04:40,800 --> 00:04:44,920
用小火煨着 煨着入味
Cook this with low heat for flavour penetration

97
00:04:44,920 --> 00:04:47,320
旁边我给我师父打个下手
Let me help my master on the side

98
00:04:47,320 --> 00:04:50,720
弄个小菜心 搁点葱油搁点盐
Cook some Choy sum, add some scallion oil and salt

99
00:04:50,720 --> 00:04:53,280
勾芡了啊 海参好了
It’s time to add slurry, the sea cucumbers are almost done

100
00:04:53,280 --> 00:04:56,440
勾芡 
Add some slurry

101
00:04:56,440 --> 00:05:00,480
得开大火了
We have to turn up the heat

102
00:05:05,040 --> 00:05:06,680
再来点芡
Some more slurry

103
00:05:08,400 --> 00:05:12,840
这勾芡最好是两次到三次
It’s better to add slurry separately in two to three times

104
00:05:12,840 --> 00:05:16,560
不要一次性勾成  边收汁边勾芡
We should not add the slurry and thicken the sauce only once

105
00:05:16,560 --> 00:05:19,480
来点油吧 慢慢来
Add a little bit of oil, take it slowly

106
00:05:19,480 --> 00:05:24,080
过去讲究 点点儿葱油
Add some scallion oil

107
00:05:25,800 --> 00:05:32,080
过去讲究淋三次油 亮啊
In the past, we have to add oil for 3 times so that the dish is shiny and glossy

108
00:05:34,440 --> 00:05:37,080
别着急 慢慢的 这时候就慢慢的烧
Don’t be impatient, we have to cook this slowly now

109
00:05:37,080 --> 00:05:40,240
海参的窍门在这儿呢 好了好了
That’s the trick for cooking sea cucumbers, it’s done now

110
00:05:40,240 --> 00:05:43,320
几勺油加的漂亮 最后越裹越亮
The scallion oil is added with a perfect amount at a perfect timing, the final dish is glossy

111
00:05:43,320 --> 00:05:48,200
汁芡融合一体 油也融合一体 装盘
The sauce, slurry and oil have combined well together, let’s serve this

112
00:05:48,200 --> 00:05:54,080
葱汁完全的包裹着海参 葱香味浓
The spring onion sauce coats the sea cucumbers perfectly, so aromatic!

113
00:05:54,080 --> 00:05:58,120
汁儿颜色红亮 非常非常地道
The sauce is glossy with hints of reddish, this is very authentic

114
00:05:58,120 --> 00:05:59,360

115
00:06:02,680 --> 00:06:06,480
怎么样 我这儿都闻着这个味了 真香
How is it, I can smell the aroma from here, so fragrant!

116
00:06:06,480 --> 00:06:09,480
糯香 葱香 酒香
The aroma of the sea cucumbers, spring onions and cooking wine

117
00:06:09,480 --> 00:06:10,760

118
00:06:11,760 --> 00:06:17,560
软糯 滑 而且入味 关键是入味 真棒
Tender and soft, flavourful, this is awesome

119
00:06:17,560 --> 00:06:18,920
一点腥味都没有
There isn’t any unpleasant taste from the sea cucumbers

120
00:06:18,920 --> 00:06:19,720
顺便说一下
By the way, let’s talk about 

121
00:06:19,720 --> 00:06:24,480
二伯为什么是三遍勾芡三遍淋油
why Er Bai add the slurry and the scallion oil for three times respectively

122
00:06:24,480 --> 00:06:27,200
你看我们有很多人在做菜
Look, when we are cooking,

123
00:06:27,200 --> 00:06:29,440
为什么得动脑子 要精巧
why do we have to be smart and think?

124
00:06:29,440 --> 00:06:31,600
通过勾芡收汁
By adding slurry and thickening the sauce,

125
00:06:31,600 --> 00:06:36,360
使汁芡把原材料包裹的融为一体
The sauce would coat the ingredients entirely

126
00:06:36,360 --> 00:06:38,520
现你看现在你看这盘汁
Look at the sauce now,

127
00:06:38,520 --> 00:06:39,560

128
00:06:39,560 --> 00:06:40,720
不见油
you can’t see any oil

129
00:06:40,720 --> 00:06:43,800
但是海参又挺亮
but the sea cucumbers are shiny

130
00:06:43,800 --> 00:06:47,040
这就是做菜的诀窍
This is a technique in cooking

131
00:06:47,040 --> 00:00:02,000

0:06:53.620,0:06:54.920
只不过叫法不同
Just that they have different names

0:06:54.920,0:06:56.120
第一个问题，有网友问
For the first question, there are friends asking about

0:06:56.120,0:06:59.180
黄酒，料酒和花雕酒的区别
the differences between Chinese cooking wine, huangjiu and Huadiao rice wine

0:06:59.180,0:07:01.360
黄酒 花雕酒是一类酒
Huangjiu and Huadiao rice wine are the same types of wine

0:07:01.360,0:07:02.420
只不过叫法不同
just that they have different names

0:07:02.420,0:07:05.700
黄酒一般都是产在绍兴
Huangjiu is usually produced in Shaoxing city in Zhejiang province

0:07:05.700,0:07:06.740
过去有什么 GYLS
There was a brand called GLYS in the past

0:07:06.740,0:07:07.880
现在还有一个新的品牌
and there is a new brand now

0:07:07.880,0:07:09.380
我忘了叫什么名了
I can’t remember the name

0:07:09.380,0:07:10.440
有这么两大品牌
There are these two brands that are popular

0:07:10.440,0:07:12.900
过去有加饭陈酿
In the past, we have those with rice added in during the fermentation process,

0:07:13.120,0:07:13.960
大紫檀的
fermenter made out of Burmese rosewood
 
0:07:13.960,0:07:15.320
黑釉面的
and fermenter with black ceramic glaze,

0:07:15.320,0:07:16.960
就是栗色的
which is a bit maroon colour

0:07:17.320,0:07:18.800
这个酒是比较好的
These are higher-quality wine

0:07:18.800,0:07:20.120
还有我们做菜	
And when we cook,

0:07:20.120,0:07:21.900
常用的是大泥坛
we often use the ones in large earthen pots

0:07:21.900,0:07:23.660
那一坛大约20斤
It’s around 20 Jin in a pot (10kg)

0:07:23.660,0:07:24.700
稍微便宜点
It’s slightly cheaper 

0:07:24.700,0:07:26.320
但是那酒非常好
But the wine is really good

0:07:26.320,0:07:28.000
是我们做菜当中
When we cook, 

0:07:28.000,0:07:29.400
不可缺少的黄酒
this is something that we cannot be short of

0:07:30.100,0:07:30.840
说料酒 
About the Chinese cooking wine (Liaojiu),

0:07:30.840,0:07:33.200
全国餐饮发展这么快
The food and beverage services in the whole country develops quickly

0:07:33.240,0:07:36.060
用量也很大
The usage of Chinese cooking wine is really big

0:07:36.060,0:07:37.080
有些调味品公司
Some condiment companies

0:07:37.080,0:07:39.800
就研发了一些叫烹调料酒
developed something called “cooking wine”

0:07:39.800,0:07:41.120
有的厂家是勾兑的
Some factories blend and dilute the wine

0:07:41.120,0:07:43.120
它直接买了一家黄酒
They just bought a type of Huangjiu produced

0:07:43.120,0:07:44.960
然后自己又勾兑了一些酒
and blend it with some other wine

0:07:44.960,0:07:45.760
稀释了
Dilute it

0:07:45.760,0:07:47.900
这酒就不是很好然后
This kind of wine is not really good

0:07:47.900,0:07:50.000
价格也很便宜
And also, the price is quite cheap

0:07:50.000,0:07:51.400
那种黄酒
That kind of huangjiu

0:07:51.460,0:07:53.740
它的酒醇味很重
has an intense alchol smell

0:07:53.840,0:07:55.240
等我们做完菜以后
When we finished cooking, 

0:07:56.160,0:07:59.900
会留下很重的酒醇味
the  dish would left with a strong alcohol smell

0:07:59.900,0:08:01.120
香味差
Upsetting smell

0:08:01.120,0:08:03.120
所以我们不倡导用这类酒
So we don’t really recommend this kind of wine

0:08:03.300,0:08:05.520
所以就选用了花雕酒
That’s why we chose to use Huadiao rice wine

0:08:05.520,0:08:06.160
特别香
It’s really fragrant

0:08:06.620,0:08:10.320
而且那酒香去腥提香
and the fragrance of Huadiao can remove some unpleasant taste

0:08:10.320,0:08:12.880
提鲜特别好的酒
It’s a really good wine for adding umami flavour

0:08:12.880,0:08:14.320
大爷说特别对
Da Ye is right

0:08:14.320,0:08:16.720
我曾经做菜的时候
In the past, when I’m cooking,

0:08:16.720,0:08:18.900
就用普通的料酒去做
I used ordinary Chinese cooking wine

0:08:19.020,0:08:21.040
做完料酒给我的感觉是什么
What’s the impression that the wine has given to me

0:08:21.040,0:08:22.460
还不如不放对
I would rather not put it in

0:08:22.740,0:08:26.600
我跟你说 不但这个菜没起到去腥的作用
Let me tell you, the wine didn’t remove unpleasant smell

0:08:26.600,0:08:28.020
反倒那个酒味
Instead, the alcohol smell

0:08:28.020,0:08:29.820
最后还出不去
can’t be removed

0:08:29.820,0:08:31.200
还闷到这里面
It’s been cooked into the flavour of the dish

0:08:31.360,0:08:32.680
闷到菜里面去了
Mixing with the flavour of the dish

0:08:32.680,0:08:37.260
而且就跟这些肉 什么东西不新鲜捂了似的
It smells like the meat is not fresh

0:08:37.260,0:08:38.700
所以说与其这样
Therefore, instead of having this awful flavour

0:08:38.700,0:08:39.680
还不如不放对
I would rather eliminate it
