### ISSUE TITLE
[老饭骨] 蒜泥拌鸡蛋 - https://youtu.be/J3Hfyjeaxpk

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1312]
**视频链接**：https://youtu.be/J3Hfyjeaxpk

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•蒜泥拌鸡蛋】一学就会的山东家常早点，浓浓蒜香，鸡蛋原来还能这样吃！附各种淀粉的用途（下）|老饭骨

简介
小友们好，又到了周五晚上，大爷二伯今天给大家分享一道山东的家常小菜——蒜泥拌鸡蛋。
这道菜大师姐在山东吃过之后就再也忘不了了，满满蒜香。并且做法简单，几分钟就能做好。
小友们周末要是睡个懒觉，来个蒜泥拌鸡蛋，配上大白馒头和稀饭，这味儿，绝了！
片尾大爷和二伯继续给大家聊聊关于淀粉的那些事儿，如果还有不清楚的地方，小友们记得在评论区告诉大爷和二伯！

字幕
1
00:00:00,000 --> 00:00:01,000

2
00:00:01,000 --> 00:00:02,160
排队站着

3
00:00:02,160 --> 00:00:04,560
鸡蛋 蒜 就这两样 简单吧

4
00:00:04,560 --> 00:00:07,600
热热乎乎的 鸡蛋加馒头

5
00:00:07,600 --> 00:00:08,720
真香

6
00:00:08,720 --> 00:00:10,240
山东的家常菜

7
00:00:10,240 --> 00:00:13,560

8
00:00:13,560 --> 00:00:15,600
咱们把鸡蛋下锅

9
00:00:16,600 --> 00:00:19,640
鸡蛋煮上了 咱把这算蒜捶了

10
00:00:19,640 --> 00:00:22,840
拍一下 这样它不用满处乱跑

11
00:00:22,840 --> 00:00:23,480

12
00:00:23,480 --> 00:00:26,120
咱们如果家里没有蒜臼子

13
00:00:26,120 --> 00:00:28,040
咱们把它搁到打碎机里头

14
00:00:28,040 --> 00:00:29,280
我在家里没有这个

15
00:00:29,280 --> 00:00:31,120
我们就使擀面杖砸

16
00:00:31,120 --> 00:00:32,600
其实这个是最好的

17
00:00:32,600 --> 00:00:34,280
这菜简单啊

18
00:00:34,280 --> 00:00:36,000
小菜当中有智慧

19
00:00:36,000 --> 00:00:39,360
锅开了 来咱们把馒头蒸上

20
00:00:39,360 --> 00:00:42,200
差不多了

21
00:00:42,200 --> 00:00:44,520
搁一碗里头 鸡蛋好了

22
00:00:44,520 --> 00:00:46,680
咱们冲一下凉

23
00:00:46,680 --> 00:00:48,080

24
00:00:48,080 --> 00:00:49,000
排队站着

25
00:00:49,240 --> 00:00:53,600
您看 拿凉水激完皮就好剥

26
00:00:53,600 --> 00:00:56,080
先搁这儿

27
00:00:56,080 --> 00:00:58,520
这个菜咱们鸡蛋不能煮成溏心儿

28
00:00:58,520 --> 00:01:01,040
吃的是沙瓤

29
00:01:01,040 --> 00:01:03,440
蒜臼子小点了 把鸡蛋掰碎

30
00:01:03,440 --> 00:01:05,080

31
00:01:05,080 --> 00:01:08,040
捣一下 先捣蒜后捣蛋

32
00:01:08,040 --> 00:01:10,560
捣成块状 擓出来

33
00:01:10,560 --> 00:01:11,440

34
00:01:11,440 --> 00:01:14,360
其实这捣细了还不好吃 没有口感

35
00:01:14,360 --> 00:01:17,520
来咱们把这个蒜搁在里边

36
00:01:17,520 --> 00:01:18,480
然后咱们

37
00:01:18,480 --> 00:01:20,320

38
00:01:20,320 --> 00:01:21,920
（放入）盐

39
00:01:21,920 --> 00:01:23,640
咱们倒入香油

40
00:01:23,640 --> 00:01:24,920

41
00:01:24,920 --> 00:01:26,200
多搁点

42
00:01:26,200 --> 00:01:29,960
搁上盐搁上香油 这个味儿出来了吧

43
00:01:29,960 --> 00:01:31,120

44
00:01:31,120 --> 00:01:32,520
这小盘漂亮

45
00:01:32,520 --> 00:01:34,840
忙的时候吃干 闲的时候吃稀

46
00:01:34,840 --> 00:01:37,440
不闲不忙 干稀搭配

47
00:01:37,440 --> 00:01:39,320
咱们这馒头也好了

48
00:01:39,320 --> 00:01:42,280
大白馒头

49
00:01:42,280 --> 00:01:44,800
咱们来个小薄荷叶

50
00:01:44,800 --> 00:01:47,000
当个早点不错啊

51
00:01:47,000 --> 00:01:48,440
是啊 省事儿啊

52
00:01:48,440 --> 00:01:50,880
先给我大伯来一个 先给师父

53
00:01:50,880 --> 00:01:52,840
您看这大馒头

54
00:01:52,840 --> 00:01:56,760
咱们这馒头咱别切 切的没有掰的香

55
00:01:56,760 --> 00:01:59,080
来半拉 中间这儿一掰

56
00:01:59,080 --> 00:02:02,680
你看看 先给你师父 先给大爷

57
00:02:02,680 --> 00:02:06,320
热乎乎的鸡蛋加馒头

58
00:02:06,320 --> 00:02:08,160

59
00:02:13,800 --> 00:02:15,680
怎么样 朝辉  真好吃

60
00:02:15,680 --> 00:02:17,840
我第一次吃

61
00:02:17,840 --> 00:02:19,280
特别香

62
00:02:19,280 --> 00:02:23,720
这跟炒鸡蛋完全不是一个味道

63
00:02:23,720 --> 00:02:26,280
蒜的辣味不那么呛不吧 不辣不辣

64
00:02:26,280 --> 00:02:27,960
一点都不辣 二伯

65
00:02:27,960 --> 00:02:31,880
您这好 还没给您照呢您就一大口了

66
00:02:31,880 --> 00:02:32,640

67
00:02:32,640 --> 00:02:36,560
这个菜也是我在山东淄博第一次吃到

68
00:02:36,560 --> 00:02:38,240
后来我就忘不了了

69
00:02:38,240 --> 00:02:39,640
还有一个东西呢

70
00:02:39,640 --> 00:02:42,080
就这一个薄荷叶让你给抄着了

71
00:02:42,080 --> 00:02:42,760

72
00:02:42,760 --> 00:02:43,760
再来一口

73
00:02:43,760 --> 00:02:46,280

74
00:02:46,280 --> 00:02:47,560
正好变了一个味道

75
00:02:47,560 --> 00:02:51,560
这薄荷 和蒜鸡蛋的清香味 马上变味

76
00:02:51,560 --> 00:02:52,720

77
00:02:52,720 --> 00:02:56,040
每次吃师父都有创新

78
00:02:56,040 --> 00:02:57,800
这薄荷真香

79
00:02:57,800 --> 00:02:59,480
您这吃的跟人家都不一样

80
00:02:59,480 --> 00:03:03,720
朝辉 这大礼拜六的 起的晚点儿

81
00:03:03,720 --> 00:03:06,600
捣上两瓣蒜 腾俩馒头 煮俩鸡蛋

82
00:03:06,600 --> 00:03:07,640
再配碗粥

83
00:03:07,640 --> 00:03:08,800

84
00:03:08,800 --> 00:03:09,840
真香

86
00:03:16,000 --> 00:03:18,560
有网友就一直想让大爷二伯

87
00:03:18,560 --> 00:03:20,240
讲讲各种淀粉的用途

88
00:03:20,240 --> 00:03:23,000
再有像我们做松鼠鱼

89
00:03:23,000 --> 00:03:24,200
脆皮鱼

90
00:03:24,200 --> 00:03:27,320
什么焦溜肉片

91
00:03:27,320 --> 00:03:29,080
还有锅包肉

92
00:03:29,080 --> 00:03:29,880
像这类的

93
00:03:29,880 --> 00:03:30,920
如果要用生粉

94
00:03:30,920 --> 00:03:31,840
他炸出来以后

95
00:03:31,840 --> 00:03:33,960
效果还特别好看

96
00:03:33,960 --> 00:03:34,840
但是他一挂汁

97
00:03:34,840 --> 00:03:36,600
麻烦了

98
00:03:36,600 --> 00:03:38,640
吃这有点黏牙

99
00:03:38,640 --> 00:03:39,920
不脆

100
00:03:39,920 --> 00:03:41,360
炸出来很脆

101
00:03:41,360 --> 00:03:42,760
但是他一挂汁

102
00:03:42,760 --> 00:03:43,920
瞬间

103
00:03:43,920 --> 00:03:45,600
他就会回软

104
00:03:45,600 --> 00:03:47,440
吃起来有点黏牙垫牙

105
00:03:47,440 --> 00:03:49,080
但是我们用的白薯粉

106
00:03:49,080 --> 00:03:50,360
土豆粉

107
00:03:50,360 --> 00:03:51,480
还有玉米淀粉

108
00:03:51,480 --> 00:03:53,160
还有绿豆淀粉

109
00:03:53,160 --> 00:03:54,920
他炸完了以后是酥脆的

110
00:03:54,920 --> 00:03:56,000
是吧

111
00:03:56,000 --> 00:03:56,720
所以我们

112
00:03:56,720 --> 00:03:57,880
在用淀粉的时候

113
00:03:57,880 --> 00:03:59,560
一定要掌握好这几个环节

114
00:03:59,560 --> 00:04:01,720
如果掌握不好

115
00:04:01,720 --> 00:04:02,680
炸出来以后

116
00:04:02,680 --> 00:04:04,480
它效果也不会好

117
00:04:05,040 --> 00:04:06,600
二伯有什么补充的吗

118
00:04:06,600 --> 00:04:07,880
大爷

119
00:04:07,880 --> 00:04:11,200
非常详细

120
00:04:11,200 --> 00:04:11,800
全面

121
00:04:11,800 --> 00:04:12,840
非常勤奋

122
00:04:12,840 --> 00:04:13,880
非常详细

123
00:04:13,880 --> 00:04:15,000
这是我上

124
00:04:15,000 --> 00:04:16,760
大学老师专门给讲的

125
00:04:16,760 --> 00:04:18,520
淀粉和淀粉之间的

126
00:04:18,520 --> 00:04:20,320
它的区别

127
00:04:20,320 --> 00:04:21,320
再有一个就是

128
00:04:21,320 --> 00:04:23,360
生粉在勾芡当中

129
00:04:23,360 --> 00:04:24,960
温度不能太高

130
00:04:24,960 --> 00:04:25,880
一般你看

131
00:04:25,880 --> 00:04:27,120
有好多粤菜的师傅

132
00:04:27,120 --> 00:04:28,560
在勾芡的时候

133
00:04:28,560 --> 00:04:30,720
他会把火拉（开） 把锅

134
00:04:30,720 --> 00:04:32,000
离开火

135
00:04:32,000 --> 00:04:35,240
在旁边有一个锅架  在90度

136
00:04:35,240 --> 00:04:36,240
左右的温度上

137
00:04:36,240 --> 00:04:37,160
勾芡

138
00:04:37,160 --> 00:04:38,400
如果用高温的方法

139
00:04:38,400 --> 00:04:39,960
一勾 就是一坨子

140
00:04:39,960 --> 00:04:41,120
大爷说的这个

141
00:04:41,120 --> 00:04:42,400
特别关键

142
00:04:42,400 --> 00:04:44,480
你比如说过去说打蚝油芡

143
00:04:44,480 --> 00:04:45,760
是吧

144
00:04:45,760 --> 00:04:46,640
打蚝油汁

145
00:04:46,640 --> 00:04:48,920
那火似开非开的时候

146
00:04:48,920 --> 00:04:51,560
然后他还不能大火晃荡

147
00:04:51,560 --> 00:04:52,440
是吧

148
00:04:52,440 --> 00:04:54,760
然后最后打完以后

149
00:04:54,760 --> 00:04:56,200
最后它封油的时候

150
00:04:56,200 --> 00:04:57,400
你看封油之后

151
00:04:57,400 --> 00:05:00,600
他用勺底下抹着封油

152
00:05:00,600 --> 00:05:02,960
所以说这就是生粉的作用

153
00:05:02,960 --> 00:05:03,960
是吧

154
00:05:03,960 --> 00:05:04,880
谢谢

155
00:05:04,880 --> 00:01:55,200

157
00:03:09,840 --> 00:00:02,000


```

**Comment by brainshawn** [comment]
认领

**Comment by brainshawn** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•蒜泥拌鸡蛋】一学就会的山东家常早点，浓浓蒜香，鸡蛋原来还能这样吃！附各种淀粉的用途（下）|老饭骨
[State Banquet Master Chef: Boiled eggs with mashed garlic] - Homely breakfast from Shandong, very easy to learn and delicious! Attached starch usage (continued)

简介
小友们好，又到了周五晚上，大爷二伯今天给大家分享一道山东的家常小菜——蒜泥拌鸡蛋。
这道菜大师姐在山东吃过之后就再也忘不了了，满满蒜香。并且做法简单，几分钟就能做好。
小友们周末要是睡个懒觉，来个蒜泥拌鸡蛋，配上大白馒头和稀饭，这味儿，绝了！
片尾大爷和二伯继续给大家聊聊关于淀粉的那些事儿，如果还有不清楚的地方，小友们记得在评论区告诉大爷和二伯！
Hello friends, Friday evening comes again! This time Da Ye and Er Bai will share a homely dish from Shandong --  boiled eggs with mashed garlic. Da Shijie said she would never forget this dish since she tasted it in Shandong -- full of garlic aroma. Cooking this dish only takes several minutes, so it is very easy. It would be perfect, if we eat this dish together with Mantou (aka Chinese steamed buns) and congee, especially on a lazy weekend morning! At the end of this video, Da Ye and Er Bai will continue to talk about the usage of starch, so please feel free to leave your comments if there’s anything unclear to you!



字幕
1
00:00:00,000 --> 00:00:01,000

2
00:00:01,000 --> 00:00:02,160
排队站着
Stand in one line

3
00:00:02,160 --> 00:00:04,560
鸡蛋 蒜 就这两样 简单吧
Egg and garlic, that’s all, so easy

4
00:00:04,560 --> 00:00:07,600
热热乎乎的 鸡蛋加馒头
Warm eggs and Mantou

5
00:00:07,600 --> 00:00:08,720
真香
It smells so good

6
00:00:08,720 --> 00:00:10,240
山东的家常菜
Homely dish from Shandong

7
00:00:10,240 --> 00:00:13,560

8
00:00:13,560 --> 00:00:15,600
咱们把鸡蛋下锅
Put the eggs in the pot

9
00:00:16,600 --> 00:00:19,640
鸡蛋煮上了 咱把这算蒜捶了
During boiling eggs, let’s smash the garlics

10
00:00:19,640 --> 00:00:22,840
拍一下 这样它不用满处乱跑
Slap to make them more stable

11
00:00:22,840 --> 00:00:23,480

12
00:00:23,480 --> 00:00:26,120
咱们如果家里没有蒜臼子
If you don’t have a mortar

13
00:00:26,120 --> 00:00:28,040
咱们把它搁到打碎机里头
We could put the garlic into a blender

14
00:00:28,040 --> 00:00:29,280
我在家里没有这个
If we don’t have a blender either

15
00:00:29,280 --> 00:00:31,120
我们就使擀面杖砸
We could use a rolling pin to punch it

16
00:00:31,120 --> 00:00:32,600
其实这个是最好的
Actually this is the best

17
00:00:32,600 --> 00:00:34,280
这菜简单啊
This dish is very easy to make

18
00:00:34,280 --> 00:00:36,000
小菜当中有智慧
Small dish could also reflect wisdom

19
00:00:36,000 --> 00:00:39,360
锅开了 来咱们把馒头蒸上
The water has been boiled, let’s steam some Mantou

20
00:00:39,360 --> 00:00:42,200
差不多了
Almost done

21
00:00:42,200 --> 00:00:44,520
搁一碗里头 鸡蛋好了
Put them into a bowl; eggs are ready

22
00:00:44,520 --> 00:00:46,680
咱们冲一下凉
Let’s cool eggs down with water

23
00:00:46,680 --> 00:00:48,080

24
00:00:48,080 --> 00:00:49,000
排队站着
Stand in one line

25
00:00:49,240 --> 00:00:53,600
您看 拿凉水激完皮就好剥
Look, it’s easier to peel after cooled down with water

26
00:00:53,600 --> 00:00:56,080
先搁这儿
Put them here first

27
00:00:56,080 --> 00:00:58,520
这个菜咱们鸡蛋不能煮成溏心儿
We shouldn’t use tender eggs in this dish

28
00:00:58,520 --> 00:01:01,040
吃的是沙瓤
We need to make eggs like pulp


29
00:01:01,040 --> 00:01:03,440
蒜臼子小点了 把鸡蛋掰碎
The mortar is a bit small, so we firstly break the eggs off with our hands

30
00:01:03,440 --> 00:01:05,080

31
00:01:05,080 --> 00:01:08,040
捣一下 先捣蒜后捣蛋
Mash garlics then eggs

32
00:01:08,040 --> 00:01:10,560
捣成块状 擓出来
Mash them into small blocks, then take them out

33
00:01:10,560 --> 00:01:11,440

34
00:01:11,440 --> 00:01:14,360
其实这捣细了还不好吃 没有口感
Actually it would be less tasty if we mash too much

35
00:01:14,360 --> 00:01:17,520
来咱们把这个蒜搁在里边
Let’s put the garlics inside

36
00:01:17,520 --> 00:01:18,480
然后咱们
Then we

37
00:01:18,480 --> 00:01:20,320

38
00:01:20,320 --> 00:01:21,920
（放入）盐
(add) some salt

39
00:01:21,920 --> 00:01:23,640
咱们倒入香油
And some sesame oil

40
00:01:23,640 --> 00:01:24,920

41
00:01:24,920 --> 00:01:26,200
多搁点
Add more

42
00:01:26,200 --> 00:01:29,960
搁上盐搁上香油 这个味儿出来了吧
With salt and sesame oil, the taste begins to show up

43
00:01:29,960 --> 00:01:31,120

44
00:01:31,120 --> 00:01:32,520
这小盘漂亮
The small dish is beautiful

45
00:01:32,520 --> 00:01:34,840
忙的时候吃干 闲的时候吃稀
Eat dry food when busy, and wet food when idle

46
00:01:34,840 --> 00:01:37,440
不闲不忙 干稀搭配
If you are both not busy and not idle, you could mix dry and wet food together

47
00:01:37,440 --> 00:01:39,320
咱们这馒头也好了
Mantou is eady

48
00:01:39,320 --> 00:01:42,280
大白馒头
Big white Mantou

49
00:01:42,280 --> 00:01:44,800
咱们来个小薄荷叶
Add some mint leaves

50
00:01:44,800 --> 00:01:47,000
当个早点不错啊
A good breakfast

51
00:01:47,000 --> 00:01:48,440
是啊 省事儿啊
Yes, very easy

52
00:01:48,440 --> 00:01:50,880
先给我大伯来一个 先给师父
Da Bo eat fist, my master

53
00:01:50,880 --> 00:01:52,840
您看这大馒头
Look at the bid white Mantou

54
00:01:52,840 --> 00:01:56,760
咱们这馒头咱别切 切的没有掰的香
Don’t cut the Mantou, it’s more delicious to break off with hands

55
00:01:56,760 --> 00:01:59,080
来半拉 中间这儿一掰
Take half, break off in the middle

56
00:01:59,080 --> 00:02:02,680
你看看 先给你师父 先给大爷
Look, give it to your master first, Da Ye

57
00:02:02,680 --> 00:02:06,320
热乎乎的鸡蛋加馒头
Warm eggs with Mantou

58
00:02:06,320 --> 00:02:08,160

59
00:02:13,800 --> 00:02:15,680
怎么样 朝辉  真好吃
How does it taste? Chaohui, very good

60
00:02:15,680 --> 00:02:17,840
我第一次吃
It’s my first time to eat this

61
00:02:17,840 --> 00:02:19,280
特别香
Very delicious

62
00:02:19,280 --> 00:02:23,720
这跟炒鸡蛋完全不是一个味道
Very different taste from Scrambled eggs

63
00:02:23,720 --> 00:02:26,280
蒜的辣味不那么呛不吧 不辣不辣
Is the garlic too spicy? Not at all

64
00:02:26,280 --> 00:02:27,960
一点都不辣 二伯
Not at all, Er Bai

65
00:02:27,960 --> 00:02:31,880
您这好 还没给您照呢您就一大口了
Look, you eat too fast to take a photo

66
00:02:31,880 --> 00:02:32,640

67
00:02:32,640 --> 00:02:36,560
这个菜也是我在山东淄博第一次吃到

I ate this dish the first time in Zibo Shandong
68
00:02:36,560 --> 00:02:38,240
后来我就忘不了了
And can’t forget it since then

69
00:02:38,240 --> 00:02:39,640
还有一个东西呢
Missed one thing

70
00:02:39,640 --> 00:02:42,080
就这一个薄荷叶让你给抄着了
You took the only mint leaf

71
00:02:42,080 --> 00:02:42,760

72
00:02:42,760 --> 00:02:43,760
再来一口
Eat once more

73
00:02:43,760 --> 00:02:46,280

74
00:02:46,280 --> 00:02:47,560
正好变了一个味道
A new taste

75
00:02:47,560 --> 00:02:51,560
这薄荷 和蒜鸡蛋的清香味 马上变味
The taste was changed immediately, when mixing mint, eggs and garlic together

76
00:02:51,560 --> 00:02:52,720

77
00:02:52,720 --> 00:02:56,040
每次吃师父都有创新
Master can always innovate each time

78
00:02:56,040 --> 00:02:57,800
这薄荷真香
The mint is so delicious

79
00:02:57,800 --> 00:02:59,480
您这吃的跟人家都不一样
You eat very differently from others

80
00:02:59,480 --> 00:03:03,720
朝辉 这大礼拜六的 起的晚点儿
Chaohui, wake up later on Saturday

81
00:03:03,720 --> 00:03:06,600
捣上两瓣蒜 腾俩馒头 煮俩鸡蛋
Mash 2 pieces of garlic, steam 2 pieces of Mantou, and boil 2 eggs

82
00:03:06,600 --> 00:03:07,640
再配碗粥
And a bowl of congee

83
00:03:07,640 --> 00:03:08,800

84
00:03:08,800 --> 00:03:09,840
真香
So perfect

86
00:03:16,000 --> 00:03:18,560
有网友就一直想让大爷二伯
Some friends want Da Ye and Er Bai

87
00:03:18,560 --> 00:03:20,240
讲讲各种淀粉的用途
To talk about the usage of different types of starch

88
00:03:20,240 --> 00:03:23,000
再有像我们做松鼠鱼
For instance, when we cook squirrel fish

89
00:03:23,000 --> 00:03:24,200
脆皮鱼
Crispy Fish

90
00:03:24,200 --> 00:03:27,320
什么焦溜肉片
Jiao Liu Rou Pian

91
00:03:27,320 --> 00:03:29,080
还有锅包肉
Guo Bao Rou

92
00:03:29,080 --> 00:03:29,880
像这类的
And so on

93
00:03:29,880 --> 00:03:30,920
如果要用生粉
If we use starchy flour

94
00:03:30,920 --> 00:03:31,840
他炸出来以后
After fried

95
00:03:31,840 --> 00:03:33,960
效果还特别好看
The dish will have a good look

96
00:03:33,960 --> 00:03:34,840
但是他一挂汁
But after adding sauce

97
00:03:34,840 --> 00:03:36,600
麻烦了
The problem comes up

98
00:03:36,600 --> 00:03:38,640
吃这有点黏牙
The dish will become sticky

99
00:03:38,640 --> 00:03:39,920
不脆
Not crispy anymore

100
00:03:39,920 --> 00:03:41,360
炸出来很脆
Initially crispy after frying

101
00:03:41,360 --> 00:03:42,760
但是他一挂汁
But after adding sauce

102
00:03:42,760 --> 00:03:43,920
瞬间
Immediately

103
00:03:43,920 --> 00:03:45,600
他就会回软
It becomes soft

104
00:03:45,600 --> 00:03:47,440
吃起来有点黏牙垫牙
And even sticks your teeth

105
00:03:47,440 --> 00:03:49,080
但是我们用的白薯粉
But if we use sweet potato starch


106
00:03:49,080 --> 00:03:50,360
土豆粉
Potato starch

107
00:03:50,360 --> 00:03:51,480
还有玉米淀粉
And cornstarch

108
00:03:51,480 --> 00:03:53,160
还有绿豆淀粉
And mung bean starch

109
00:03:53,160 --> 00:03:54,920
他炸完了以后是酥脆的
The food is crispy after being fried

110
00:03:54,920 --> 00:03:56,000
是吧
Yes

111
00:03:56,000 --> 00:03:56,720
所以我们
So when we

112
00:03:56,720 --> 00:03:57,880
在用淀粉的时候
Use starch

113
00:03:57,880 --> 00:03:59,560
一定要掌握好这几个环节
We must pay attention to these steps

114
00:03:59,560 --> 00:04:01,720
如果掌握不好
Otherwise

115
00:04:01,720 --> 00:04:02,680
炸出来以后
After frying

116
00:04:02,680 --> 00:04:04,480
它效果也不会好
The result wouldn’t be good

117
00:04:05,040 --> 00:04:06,600
二伯有什么补充的吗
Er Bai, do you have anything to say

118
00:04:06,600 --> 00:04:07,880
大爷
Da Ye

119
00:04:07,880 --> 00:04:11,200
非常详细
Very detailed

120
00:04:11,200 --> 00:04:11,800
全面
Comprehensive

121
00:04:11,800 --> 00:04:12,840
非常勤奋
Very diligent

122
00:04:12,840 --> 00:04:13,880
非常详细
Very detailed

123
00:04:13,880 --> 00:04:15,000
这是我上
This was 

124
00:04:15,000 --> 00:04:16,760
大学老师专门给讲的
What I learnt when I was in university

125
00:04:16,760 --> 00:04:18,520
淀粉和淀粉之间的
Among different types of starch

126
00:04:18,520 --> 00:04:20,320
它的区别
The difference

127
00:04:20,320 --> 00:04:21,320
再有一个就是
Another one is

128
00:04:21,320 --> 00:04:23,360
生粉在勾芡当中
Starchy flour during adding slurry

129
00:04:23,360 --> 00:04:24,960
温度不能太高
The temperature shouldn’t be very high

130
00:04:24,960 --> 00:04:25,880
一般你看
In most cases

131
00:04:25,880 --> 00:04:27,120
有好多粤菜的师傅
Many chefs of Guangdong cuisine

132
00:04:27,120 --> 00:04:28,560
在勾芡的时候
When adding slurry

133
00:04:28,560 --> 00:04:30,720
他会把火拉（开） 把锅
They will move the wok away

134
00:04:30,720 --> 00:04:32,000
离开火
From the fire

135
00:04:32,000 --> 00:04:35,240
在旁边有一个锅架  在90度
Put it on a rack, use 90 degrees

136
00:04:35,240 --> 00:04:36,240
左右的温度上
Or so temperature

137
00:04:36,240 --> 00:04:37,160
勾芡
Add slurry

138
00:04:37,160 --> 00:04:38,400
如果用高温的方法
If the temperature is too high

139
00:04:38,400 --> 00:04:39,960
一勾 就是一坨子
The starch will form solid

140
00:04:39,960 --> 00:04:41,120
大爷说的这个
What Da Ye said

141
00:04:41,120 --> 00:04:42,400
特别关键
Is very important

142
00:04:42,400 --> 00:04:44,480
你比如说过去说打蚝油芡
For example, long time ago, when mixing starch with oyster sauce

143
00:04:44,480 --> 00:04:45,760
是吧
Yes

144
00:04:45,760 --> 00:04:46,640
打蚝油汁
Mix with oyster sauce

145
00:04:46,640 --> 00:04:48,920
那火似开非开的时候
When the water seems to be boiled but is not boiled yet

146
00:04:48,920 --> 00:04:51,560
然后他还不能大火晃荡
You should keep the temperature not too high

147
00:04:51,560 --> 00:04:52,440
是吧
yes

148
00:04:52,440 --> 00:04:54,760
然后最后打完以后
Finally

149
00:04:54,760 --> 00:04:56,200
最后它封油的时候
In the encapsulation oil step

150
00:04:56,200 --> 00:04:57,400
你看封油之后
Then you will find

151
00:04:57,400 --> 00:05:00,600
他用勺底下抹着封油
They encapsulate oil using the bottom of fry spoon

152
00:05:00,600 --> 00:05:02,960
所以说这就是生粉的作用
So this is the effect of starch flour

153
00:05:02,960 --> 00:05:03,960
是吧
Yes

154
00:05:03,960 --> 00:05:04,880
谢谢
Thanks

155
00:05:04,880 --> 00:01:55,200

157
00:03:09,840 --> 00:00:02,000
