### ISSUE TITLE
[雪鱼] 临洮热凉面 - https://youtu.be/i2KWIWUW2dM

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#1314]
**视频链接**：<https://youtu.be/i2KWIWUW2dM>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
<甘肃临洮热凉面，早上来一碗可加卤肉肥肠，老吃家一坐下就剥蒜，连卤汁都不剩>

简介
<早就听闻临洮热凉面，于是乎我从兰州直奔临洮。这儿的热凉面是被本地人当作早餐食用的，刚出锅的面条烫嘴，阿姨会将其放置在案板上，撒上菜籽油防止粘连，凉透的面条上浇上热卤汁，再根据个人喜好加上肉片、肥肠、鸡蛋等，一盘丰盛的临洮热凉面就做好了！这老吃家早上一来，就先剥蒜，喝一口面汤，吃一口蒜，最后连面带卤汁统统吃干净！>

字幕
<1
00:00:01,880 --> 00:00:04,960
甘肃·临洮

2
00:00:07,160 --> 00:00:11,360
现在雪鱼在临洮 待会呢打算去吃一碗热凉面

3
00:00:11,360 --> 00:00:14,920
当时注意到热凉面的时候 我就有一个疑问

4
00:00:14,920 --> 00:00:18,400
这个面
到底是热的呢还是凉的

5
00:00:18,400 --> 00:00:21,360
查了老半天资料还是觉得一头雾水

6
00:00:21,360 --> 00:00:26,120
索性就直接来临洮看一看 热凉面到底是什么样子

7
00:00:27,160 --> 00:00:37,040
歌曲：小镇故事多  充满喜和乐

8
00:00:42,160 --> 00:00:45,240
进去吃凉面吧

9
00:01:02,600 --> 00:01:06,200
吃热的还是吃凉的（面条）

10
00:01:06,200 --> 00:01:08,040
凉的和热的有什么样的区别

11
00:01:08,040 --> 00:01:09,960
凉的就是拌了一下油

12
00:01:10,120 --> 00:01:12,920
热的就是直接从锅里捞出来的

13
00:01:12,920 --> 00:01:14,320
那我要热的

14
00:01:14,320 --> 00:01:15,200
好的 吃热的

15
00:01:15,200 --> 00:01:16,220
要宽面条还是细面条

16
00:01:16,280 --> 00:01:17,420
要细的

17
00:01:17,420 --> 00:01:18,680
加肉 加肥肠吗

18
00:01:18,880 --> 00:01:20,320
加 都加

19
00:01:20,320 --> 00:01:22,240
好的 都加

20
00:01:22,240 --> 00:01:23,880
辣椒吃吗   可以

21
00:01:24,680 --> 00:01:26,720
对 加个蛋

22
00:01:26,720 --> 00:01:27,960
你坐就行

23
00:01:27,960 --> 00:01:29,200
行 行 好 谢谢

24
00:01:39,280 --> 00:01:40,520
好 谢谢

25
00:01:40,520 --> 00:01:41,400
不客气

26
00:01:41,400 --> 00:01:46,160
到面馆里吃面 落座之后会上一碗面汤

27
00:01:49,400 --> 00:01:54,480
这边一看就是吃面的地方 桌子上摆着蒜

28
00:01:54,480 --> 00:01:57,920
辣子 还有一壶的醋

29
00:02:00,000 --> 00:02:01,960
好大一份

30
00:02:10,680 --> 00:02:15,520
它这个面条是浸在卤子里的 这个卤子会倒两遍

31
00:02:15,520 --> 00:02:17,840
第一遍呢 就是在底下打个底

32
00:02:17,840 --> 00:02:21,960
还要把面条翻一下 让这个面条都有卤子

33
00:02:21,960 --> 00:02:24,520
第二个部分呢 就是再倒一勺卤子

34
00:02:24,520 --> 00:02:28,440
这样好再倒上肉啊 鸡蛋这些

35
00:02:28,440 --> 00:02:34,160
不多说了赶快吃吧 这个面都坨了

36
00:02:36,800 --> 00:02:39,560
我也先拌一拌吧

37
00:02:39,560 --> 00:02:42,320
好香啊

38
00:02:50,920 --> 00:02:55,320
不管面还是肉 都浸满了卤子

39
00:03:03,000 --> 00:03:08,000
今天是又要了肉 又要了蛋 还是肉蛋双飞的这种类型

40
00:03:08,000 --> 00:03:12,440
好喜欢吃辣子下的肉 吃起来香香的

41
00:03:16,920 --> 00:03:20,240
我感觉要的豪华版的 根本就不是来吃面的

42
00:03:20,240 --> 00:03:22,840
好像是来吃肉的

43
00:03:27,520 --> 00:03:30,960
面条就像前几天在兰州吃的牛肉面一样

44
00:03:30,960 --> 00:03:35,720
都是这种比较劲道的口感 而且颜色都是淡黄色

45
00:03:37,120 --> 00:03:40,800
来店里点面 老板的一般问题都是

46
00:03:40,800 --> 00:03:42,660
要热的 还是要凉的

47
00:03:42,660 --> 00:03:44,220
要宽面还是细面

48
00:03:44,560 --> 00:03:46,640
要不要肉 要不要辣子

49
00:03:46,640 --> 00:03:49,400
连环地问 到底吃什么样的面条

50
00:03:49,400 --> 00:03:53,000
像我这份就是细的面条 热的面条

51
00:03:53,000 --> 00:03:56,200
加辣子 加肉 加蛋 全都有了

52
00:03:56,200 --> 00:04:00,720
这边的调料就是少不了醋 辣子 蒜汁

53
00:04:00,720 --> 00:04:03,400
流水的面馆 铁打的调料 都是这三样

54
00:04:03,400 --> 00:04:07,200
最近吃的都是这三样

55
00:04:10,880 --> 00:04:14,360
这碗面最大的特点应该就是这浓郁的卤汁了吧

56
00:04:14,360 --> 00:04:17,480
半流淌的状态 让它能够依附于面条

57
00:04:17,480 --> 00:04:19,880
每吃一口 我都要发出吸溜的声音

58
00:04:19,880 --> 00:04:21,520
吃着吃着就会发现

59
00:04:21,520 --> 00:04:26,120
卤汁包裹下的面条 味道好像更饱满一些

60
00:04:26,200 --> 00:04:29,400
吃完了热凉面呢  我打算去他们的厨房看一看

61
00:04:29,400 --> 00:04:32,920
因为我感觉里面的气氛好像是异常火爆

62
00:04:32,920 --> 00:04:34,560
正好借这个机会看一看

63
00:04:34,560 --> 00:04:36,680
凉面（还有热凉面）是怎么做成的吧

64
00:04:50,800 --> 00:04:54,520
走进厨房 首先能够看到的是他们切肉的场景

65
00:04:54,520 --> 00:04:58,240
在这边倒是没有看到大刀剁肉 这种酣畅淋漓的场面

66
00:04:58,240 --> 00:05:02,960
反而是这种三角小刀片肉的场面倒是别具一格

67
00:05:03,160 --> 00:05:05,000
肉切到什么程度

68
00:05:05,000 --> 00:05:06,680
要切的很薄很薄

69
00:05:07,120 --> 00:05:09,560
这样的厚度就刚刚好

70
00:05:12,800 --> 00:05:16,880
这边放在面里的肉 不仅有肘子肉 还有卤肥肠

71
00:05:16,880 --> 00:05:20,960
在卤肉的旁边 就是一小碟 一小碟的卤肥肠

72
00:05:20,960 --> 00:05:24,480
肉是提前做出来的 切出来会比较干

73
00:05:24,480 --> 00:05:29,520
所以说 切过的肉 还要在后面的大锅里再冒（烫）一下

74
00:05:29,520 --> 00:05:31,840
出锅的时候 还会再放一些老汤

75
00:05:31,840 --> 00:05:35,160
这样会让肉更有味道

76
00:05:39,120 --> 00:05:41,840
再朝前走 就是他们做面的地方了

77
00:05:41,840 --> 00:05:45,080
凉面店里的面条呢 也是像兰州牛肉面一样

78
00:05:45,080 --> 00:05:46,840
需要现场拉出来

79
00:05:46,840 --> 00:05:50,760
根据顾客的需求 有的会要粗一点的 有的会要细一点的

80
00:05:50,760 --> 00:05:52,960
都是根据需求 现做出来的

81
00:05:52,960 --> 00:05:56,120
临洮有句关于做凉面的话就是

82
00:05:56,120 --> 00:06:01,360
这个面需要  三遍水 三遍蓬灰 九九八十一道揉

83
00:06:01,360 --> 00:06:06,600
就是为了让这个面拉起来更有韧性 吃起来是劲道

84
00:06:30,880 --> 00:06:33,440
小哥 你这个面揉的像麻花一样

85
00:06:33,440 --> 00:06:35,920
一定要这么用力地揉吗

86
00:06:35,920 --> 00:06:38,400
对 对

87
00:06:38,400 --> 00:06:42,840
揉得越厉害 它越筋道

88
00:06:42,840 --> 00:06:46,600
这一块面团要揉多久

89
00:06:47,200 --> 00:06:50,240
半个小时吧

90
00:07:11,520 --> 00:07:15,200
小哥 这个过程叫溜条 还是叫溜条
—
、

91
00:07:15,200 --> 00:07:17,120
叫溜条
—

92
00:07:17,120 --> 00:07:20,240
就是把面团揪成一块块的

93
00:07:23,360 --> 00:07:25,560
这一块就是一碗面

94
00:07:25,560 --> 00:07:28,400
一个剂子是一碗面

95
00:07:28,400 --> 00:07:31,240
大小是一样的

96
00:07:31,840 --> 00:07:34,320
后面这个拉面的小哥很有意思

97
00:07:34,320 --> 00:07:39,000
他刚才把面条丢进锅里 然后冲着我说

98
00:07:39,000 --> 00:07:40,600
这个东西很简单

99
00:07:40,600 --> 00:07:43,200
我们过去看看真的是这么简单吗

100
00:08:23,080 --> 00:08:24,760
我动作稍微慢一点 让你看清楚

101
00:08:24,760 --> 00:08:27,780
小哥 你说做拉面简单吗

102
00:08:28,200 --> 00:08:30,560
简单  非常简单

103
00:08:41,760 --> 00:08:47,640
小姐姐 我想问一下 凉面还有热凉面的区别

104
00:08:47,640 --> 00:08:51,400
凉面就是 面从锅里捞出来 再用油拌一下

105
00:08:51,400 --> 00:08:52,840
晾凉了 就是凉面

106
00:08:52,840 --> 00:08:56,800
热面就是面直接从锅里捞出来 直接调上汤汁 就是热的

107
00:08:56,800 --> 00:08:59,040
不用拌凉

108
00:08:59,040 --> 00:09:00,600
就是这样的

109
00:09:00,600 --> 00:09:04,120
我看咱们这边吃面条是分宽的和细的

110
00:09:04,120 --> 00:09:07,120
还有二细 韭叶 三细

111
00:09:07,120 --> 00:09:09,520
那顾客是要细的多一些呢 还是要粗的多一些呢

112
00:09:09,520 --> 00:09:11,440
这个就看个人口味了

113
00:09:11,440 --> 00:09:13,920
有的人喜欢吃宽的 有的人喜欢吃细的

114
00:09:13,920 --> 00:09:16,000
好 谢谢

115
00:09:16,000 --> 00:09:17,480
不用谢

116
00:09:17,480 --> 00:09:18,680
刚才小姐姐说的是

117
00:09:18,680 --> 00:09:22,000
凉面和热凉面在做法和操作上的区别

118
00:09:22,000 --> 00:09:25,200
就是热凉面不经过拌油冷却这个过程

119
00:09:25,200 --> 00:09:27,360
实际上 最先出现的是凉面

120
00:09:27,360 --> 00:09:29,640
那个时候都是挑着担子在外面卖

121
00:09:29,640 --> 00:09:33,040
担子的一边的放的是已经用油拌好的凉面

122
00:09:33,040 --> 00:09:34,720
另一边呢 放的是热汤

123
00:09:34,720 --> 00:09:36,200
后来呢 有了凉面店

124
00:09:36,200 --> 00:09:38,960
有的顾客说可以把面直接放在热卤里

125
00:09:38,960 --> 00:09:41,160
这么吃就是胃舒服些

126
00:09:41,160 --> 00:09:44,160
这个时候 热凉面才开始出现

127
00:09:44,440 --> 00:09:48,280
这么看来 热凉面应该是凉面发展的产物吧

128
00:09:50,280 --> 00:09:51,240
还有一点就是

129
00:09:51,240 --> 00:09:54,480
吃凉面和吃热凉面 和季节有很大的关系

130
00:09:54,480 --> 00:09:59,000
像这种天气 来碗凉面 可能更配一些

131
00:10:03,680 --> 00:10:07,360
奶奶 吃面之前要先剥蒜吗

132
00:10:07,360 --> 00:10:09,360
这个蒜

133
00:10:09,360 --> 00:10:13,400
吃这个蒜配面里面的肉

134
00:10:13,400 --> 00:10:17,840
奶奶 您经常来吃凉面吗

135
00:10:17,840 --> 00:10:19,520
经常吃

136
00:10:19,520 --> 00:10:22,280
他们家的凉面 就是好

137
00:10:22,280 --> 00:10:27,640
凉面是咱们这边特色是吧

138
00:10:27,640 --> 00:10:30,480
临洮的特色面

139
00:10:30,480 --> 00:10:34,160
您点的是热凉面还是凉面呢

140
00:10:34,160 --> 00:10:37,840
凉的 它那个汤不是热的吗

141
00:10:37,840 --> 00:10:39,320
夏天吃这个好

142
00:10:42,720 --> 00:10:45,200
在临洮 满大街的都是凉面店

143
00:10:45,200 --> 00:10:47,600
凉面呢 大家从早上起来就可以吃

144
00:10:47,600 --> 00:10:49,360
一直到下午两点

145
00:10:49,360 --> 00:10:52,760
早上呢 不需要点那么贵的 不需要加那么多的肉

146
00:10:52,760 --> 00:10:55,760
一种肉 或者说加一个蛋 已经足够了

147
00:10:55,760 --> 00:10:59,080
我的这种 我觉得加的 有点过分了

148
00:10:59,080 --> 00:11:00,880
好了 今天的视频就到这

149
00:11:02,240 --> 00:11:04,720
~~拜拜

150
00:11:24,360 --> 00:11:28,560
关  注
雪 鱼 探 店

>
```

**Comment by immoonancient** [comment]
@Chuwanggangsiqiu 请前来认领

**Comment by Chuwanggangsiqiu** [comment]
认领

**Comment by Chuwanggangsiqiu** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
<甘肃临洮热凉面，早上来一碗可加卤肉肥肠，老吃家一坐下就剥蒜，连卤汁都不剩>
<Hot-Cold Noodle in Lintao, Gansu Prov. Have a one with braised meat and pork intestine in the morning, it’s so tasty that you want to finish them all.>
简介
<早就听闻临洮热凉面，于是乎我从兰州直奔临洮。这儿的热凉面是被本地人当作早餐食用的，刚出锅的面条烫嘴，阿姨会将其放置在案板上，撒上菜籽油防止粘连，凉透的面条上浇上热卤汁，再根据个人喜好加上肉片、肥肠、鸡蛋等，一盘丰盛的临洮热凉面就做好了！这老吃家早上一来，就先剥蒜，喝一口面汤，吃一口蒜，最后连面带卤汁统统吃干净！>
<I heard the Lintao’s hot-cold noodle for a long time, so I went there from Lanzhou. The noodle is treated as breakfast in the local, the noodle is extremely hot when it comes out from the boiled pot, so she will put it on a board, mixed with colza oil to prevent the noodles stick to each other, and pour over the noodles with hot braised sauce, come with multiple selections from sliced meat, pork intestine, braised egg, etc. A plate of hearty Lintao’s specialty noodles is well prepared! 
字幕
<1
00:00:01,880 --> 00:00:04,960
甘肃·临洮
Lintao, Gansu
2
00:00:07,160 --> 00:00:11,360
现在雪鱼在临洮 待会呢打算去吃一碗热凉面
Now I’m at Lintao, I will have a bowl of Hot-Cold noodles later.
3
00:00:11,360 --> 00:00:14,920
当时注意到热凉面的时候 我就有一个疑问
I was kind of interested when I noticed the name of the Hot-Cold noodles. 
4
00:00:14,920 --> 00:00:18,400
这个面
到底是热的呢还是凉的
Is the noodle hot or cold?
5
00:00:18,400 --> 00:00:21,360
查了老半天资料还是觉得一头雾水
I did a lot of research on this one, but still got confused.
6
00:00:21,360 --> 00:00:26,120
索性就直接来临洮看一看 热凉面到底是什么样子
Therefore, I thought why not come to this city, and see what is it look like?
7
00:00:27,160 --> 00:00:37,040
歌曲：小镇故事多  充满喜和乐

8
00:00:42,160 --> 00:00:45,240
进去吃凉面吧
Let’s get in!
9
00:01:02,600 --> 00:01:06,200
吃热的还是吃凉的（面条）
Do you want the hot one or the cold one (noodles)? 
10
00:01:06,200 --> 00:01:08,040
凉的和热的有什么样的区别
What’s the difference between the cold one and the hot one?
11
00:01:08,040 --> 00:01:09,960
凉的就是拌了一下油
Cold one is stirred with some oil 
12
00:01:10,120 --> 00:01:12,920
热的就是直接从锅里捞出来的
Hot one is come right out from the pot 
13
00:01:12,920 --> 00:01:14,320
那我要热的
Then I want the hot one 
14
00:01:14,320 --> 00:01:15,200
好的 吃热的
Hot one? Right!
15
00:01:15,200 --> 00:01:16,220
要宽面条还是细面条
With the wide noodle or the thin noodle?
16
00:01:16,280 --> 00:01:17,420
要细的
The thin one
17
00:01:17,420 --> 00:01:18,680
加肉 加肥肠吗
Add meat and pork intestine? 
18
00:01:18,880 --> 00:01:20,320
加 都加
Yeah, add them all.
19
00:01:20,320 --> 00:01:22,240
好的 都加
All of them? Right!
20
00:01:22,240 --> 00:01:23,880
辣椒吃吗   可以
Is it okay with hot chili?  Yeah, It’s fine
21
00:01:24,680 --> 00:01:26,720
对 加个蛋
Yes, add a braised egg
22
00:01:26,720 --> 00:01:27,960
你坐就行
You can have a seat
23
00:01:27,960 --> 00:01:29,200
行 行 好 谢谢
Aright, thanks 
24
00:01:39,280 --> 00:01:40,520
好 谢谢
Thanks 
25
00:01:40,520 --> 00:01:41,400
不客气
You’re welcome
26
00:01:41,400 --> 00:01:46,160
到面馆里吃面 落座之后会上一碗面汤
If you are going to the noodle house, they normally would bring a bowl of noodle soup to your table after you have sat 
27
00:01:49,400 --> 00:01:54,480
这边一看就是吃面的地方 桌子上摆着蒜
You would know this place is for you to having noodles when you have seen the garlic on the table 
28
00:01:54,480 --> 00:01:57,920
辣子 还有一壶的醋
With hot chilies, and some vinegar 
29
00:02:00,000 --> 00:02:01,960
好大一份
It’s huge
30
00:02:10,680 --> 00:02:15,520
它这个面条是浸在卤子里的 这个卤子会倒两遍
This noodle is immersed in the braised sauce, they will pour over twice  
31
00:02:15,520 --> 00:02:17,840
第一遍呢 就是在底下打个底
The first time will put some underneath 
32
00:02:17,840 --> 00:02:21,960
还要把面条翻一下 让这个面条都有卤子
And flip over the noodles to ensure it is fully covered by the sauce 
33
00:02:21,960 --> 00:02:24,520
第二个部分呢 就是再倒一勺卤子
Second part will be pouring over the sauce another time
34
00:02:24,520 --> 00:02:28,440
这样好再倒上肉啊 鸡蛋这些
And then followed by putting some meat and egg on the top
35
00:02:28,440 --> 00:02:34,160
不多说了赶快吃吧 这个面都坨了
I have to start eating as the noodles are going to be soggy 
36
00:02:36,800 --> 00:02:39,560
我也先拌一拌吧
Mix it first 
37
00:02:39,560 --> 00:02:42,320
好香啊
Smells good 
38
00:02:50,920 --> 00:02:55,320
不管面还是肉 都浸满了卤子
Both noodles and meat are fully immersed with the sauce 
39
00:03:03,000 --> 00:03:08,000
今天是又要了肉 又要了蛋 还是肉蛋双飞的这种类型
Ordered meat and egg in this
40
00:03:08,000 --> 00:03:12,440
好喜欢吃辣子下的肉 吃起来香香的
I like to have the meat with some hot chili, so luscious
41
00:03:16,920 --> 00:03:20,240
我感觉要的豪华版的 根本就不是来吃面的
I feel like I’m not came here to having these noodles with this deluxe version
42
00:03:20,240 --> 00:03:22,840
好像是来吃肉的
Seems in order to having these meats instead
43
00:03:27,520 --> 00:03:30,960
面条就像前几天在兰州吃的牛肉面一样
These noodles are just like the beef noodles that I had few days ago in Lanzhou
44
00:03:30,960 --> 00:03:35,720
都是这种比较劲道的口感 而且颜色都是淡黄色
They shared the same chewy texture and both in light-yellow color
45
00:03:37,120 --> 00:03:40,800
来店里点面 老板的一般问题都是
If you come over to the shop, they will always ask you the same questions 
46
00:03:40,800 --> 00:03:42,660
要热的 还是要凉的
You want the hot one or the cold one?
47
00:03:42,660 --> 00:03:44,220
要宽面还是细面
Wide noodles or thin noodles?
48
00:03:44,560 --> 00:03:46,640
要不要肉 要不要辣子
Do you want to add some meat? Are you okay with spicy chili?
49
00:03:46,640 --> 00:03:49,400
连环地问 到底吃什么样的面条
Ask you a serial of questions, what do you want specifically?
50
00:03:49,400 --> 00:03:53,000
像我这份就是细的面条 热的面条
Like the one I ordered here, this is the hot one and with thin noodles
51
00:03:53,000 --> 00:03:56,200
加辣子 加肉 加蛋 全都有了
Add spicy chili, meat, and egg. Added all their selections.
52
00:03:56,200 --> 00:04:00,720
这边的调料就是少不了醋 辣子 蒜汁
And vinegar, spicy chili, garlic juice, are indispensable parts of its flavor
53
00:04:00,720 --> 00:04:03,400
流水的面馆 铁打的调料 都是这三样
Noodle houses are normally come with these flowed processes and fixed sauces
54
00:04:03,400 --> 00:04:07,200
最近吃的都是这三样
I’m having the same flavors lately  
55
00:04:10,880 --> 00:04:14,360
这碗面最大的特点应该就是这浓郁的卤汁了吧
One of the biggest features of this noodle is the bold taste of its sauce
56
00:04:14,360 --> 00:04:17,480
半流淌的状态 让它能够依附于面条
It can attach to the noodles with its semi-liquid state 
57
00:04:17,480 --> 00:04:19,880
每吃一口 我都要发出吸溜的声音
And I’m making the slurping sound for every single bite
58
00:04:19,880 --> 00:04:21,520
吃着吃着就会发现
While in the meantime,
59
00:04:21,520 --> 00:04:26,120
卤汁包裹下的面条 味道好像更饱满一些
You will find out the sauce wrapped noodles will become more flavorful 
60
00:04:26,200 --> 00:04:29,400
吃完了热凉面呢  我打算去他们的厨房看一看
After finished this noodle, I’m going to have a look in their kitchen 
61
00:04:29,400 --> 00:04:32,920
因为我感觉里面的气氛好像是异常火爆
Cause I feel like it’s so hearty in there
62
00:04:32,920 --> 00:04:34,560
正好借这个机会看一看
With this chance, I’m going to checkout
63
00:04:34,560 --> 00:04:36,680
凉面（还有热凉面）是怎么做成的吧
How they make the hot-cold noodles
64
00:04:50,800 --> 00:04:54,520
走进厨房 首先能够看到的是他们切肉的场景
First, you will see they are cutting the meat after you walked into the kitchen
65
00:04:54,520 --> 00:04:58,240
在这边倒是没有看到大刀剁肉 这种酣畅淋漓的场面
You won’t see they are chopping the meat exuberantly with heavy knifes 
66
00:04:58,240 --> 00:05:02,960
反而是这种三角小刀片肉的场面倒是别具一格
Instead, they are using this little triangular blade to slice the meat. 
67
00:05:03,160 --> 00:05:05,000
肉切到什么程度
How thin do you have to cut this meat to?
68
00:05:05,000 --> 00:05:06,680
要切的很薄很薄
Very thin
69
00:05:07,120 --> 00:05:09,560
这样的厚度就刚刚好
Like this one 
70
00:05:12,800 --> 00:05:16,880
这边放在面里的肉 不仅有肘子肉 还有卤肥肠
The meat they are offering are not limited to pork shoulder, but also braised pork intestine
71
00:05:16,880 --> 00:05:20,960
在卤肉的旁边 就是一小碟 一小碟的卤肥肠
Beside the pork shoulder, there have putted pork intestine into each single small plate
72
00:05:20,960 --> 00:05:24,480
肉是提前做出来的 切出来会比较干
Since the meat is cooked already a while ago, and a bit of dry when you cut it
73
00:05:24,480 --> 00:05:29,520
所以说 切过的肉 还要在后面的大锅里再冒（烫）一下
Therefore, the sliced meats are going to quick boil for a moment
74
00:05:29,520 --> 00:05:31,840
出锅的时候 还会再放一些老汤
They will put some broth in it when it come out from the pot
75
00:05:31,840 --> 00:05:35,160
这样会让肉更有味道
Then the meat will become more flavorful 
76
00:05:39,120 --> 00:05:41,840
再朝前走 就是他们做面的地方了
And a few steps further, that’s the place where they produce the noodles  
77
00:05:41,840 --> 00:05:45,080
凉面店里的面条呢 也是像兰州牛肉面一样
The noodles in this shop are pretty like the Lanzhou beef noodles
78
00:05:45,080 --> 00:05:46,840
需要现场拉出来
They need stretch the dough in the same time
79
00:05:46,840 --> 00:05:50,760
根据顾客的需求 有的会要粗一点的 有的会要细一点的
Followed by the customer’s requirements, someone would order the thick one, others may want the thin one
80
00:05:50,760 --> 00:05:52,960
都是根据需求 现做出来的
It’s all made out after their requests
81
00:05:52,960 --> 00:05:56,120
临洮有句关于做凉面的话就是
There is a saying about Lintao’s Hot-Cold noodles 
82
00:05:56,120 --> 00:06:01,360
这个面需要  三遍水 三遍蓬灰 九九八十一道揉
This noodle need go through many processes 
83
00:06:01,360 --> 00:06:06,600
就是为了让这个面拉起来更有韧性 吃起来是劲道
To ensure the noodles will be more chewy 
84
00:06:30,880 --> 00:06:33,440
小哥 你这个面揉的像麻花一样
Hey, your dough is like Mahua when you are kneading 
85
00:06:33,440 --> 00:06:35,920
一定要这么用力地揉吗
Do you have to kneading this hard?
86
00:06:35,920 --> 00:06:38,400
对 对
Yeah
87
00:06:38,400 --> 00:06:42,840
揉得越厉害 它越筋道
The harder you knead the dough, the stronger it will get 
88
00:06:42,840 --> 00:06:46,600
这一块面团要揉多久
How long should you knead this dough for?
89
00:06:47,200 --> 00:06:50,240
半个小时吧
Around half hour
90
00:07:11,520 --> 00:07:15,200
小哥 这个过程叫溜条 还是叫溜条
—
、
Is the word Liu pronounced with first tone or fourth tone?
91
00:07:15,200 --> 00:07:17,120
叫溜条
—
First tone
92
00:07:17,120 --> 00:07:20,240
就是把面团揪成一块块的
Just need to pull this dough into pieces
93
00:07:23,360 --> 00:07:25,560
这一块就是一碗面
One piece per serving
94
00:07:25,560 --> 00:07:28,400
一个剂子是一碗面
One piece is a bowl of noodles
95
00:07:28,400 --> 00:07:31,240
大小是一样的
The size is same
96
00:07:31,840 --> 00:07:34,320
后面这个拉面的小哥很有意思
The guy who are pulling the dough is kind of interesting
97
00:07:34,320 --> 00:07:39,000
他刚才把面条丢进锅里 然后冲着我说
He just throws the noodles into the pot and saying to me 
98
00:07:39,000 --> 00:07:40,600
这个东西很简单
This thing is very easy
99
00:07:40,600 --> 00:07:43,200
我们过去看看真的是这么简单吗
Let’s see how easy that could be 
100
00:08:23,080 --> 00:08:24,760
我动作稍微慢一点 让你看清楚
I will move slowly, and you can have a clear look
101
00:08:24,760 --> 00:08:27,780
小哥 你说做拉面简单吗
You said it’s very easy to make pulled noodles? 
102
00:08:28,200 --> 00:08:30,560
简单  非常简单
It’s very simple
103
00:08:41,760 --> 00:08:47,640
小姐姐 我想问一下 凉面还有热凉面的区别
Hey, Miss. I want asking what’s the difference between cold noodles and hot-cold noodles?
104
00:08:47,640 --> 00:08:51,400
凉面就是 面从锅里捞出来 再用油拌一下
Cold noodles are made directly from the pot and mixed up with some oil 
105
00:08:51,400 --> 00:08:52,840
晾凉了 就是凉面
Wait it’s getting cold, then it will be cold noodles
106
00:08:52,840 --> 00:08:56,800
热面就是面直接从锅里捞出来 直接调上汤汁 就是热的
Hot noodles are the same but pouring over some broth and sauce when it come out from the pot. 
107
00:08:56,800 --> 00:08:59,040
不用拌凉
You don’t need to wait it getting cold and mixing with the oil 
108
00:08:59,040 --> 00:09:00,600
就是这样的
That’s it
109
00:09:00,600 --> 00:09:04,120
我看咱们这边吃面条是分宽的和细的
You can order the noodles in different shape of forms beside wide and thin
110
00:09:04,120 --> 00:09:07,120
还有二细 韭叶 三细
There are Erxi, Jiuye, Sanxi
111
00:09:07,120 --> 00:09:09,520
那顾客是要细的多一些呢 还是要粗的多一些呢
The degree of thinness and thickness will depend on 
112
00:09:09,520 --> 00:09:11,440
这个就看个人口味了
Personal favors 
113
00:09:11,440 --> 00:09:13,920
有的人喜欢吃宽的 有的人喜欢吃细的
Someone may like the wide one, someone like the thin one
114
00:09:13,920 --> 00:09:16,000
好 谢谢
Alright, thinks 
115
00:09:16,000 --> 00:09:17,480
不用谢
You’re welcome
116
00:09:17,480 --> 00:09:18,680
刚才小姐姐说的是
The miss just said 
117
00:09:18,680 --> 00:09:22,000
凉面和热凉面在做法和操作上的区别
The distinctions of method and how to handle between cold noodles and hot-cold noodles
118
00:09:22,000 --> 00:09:25,200
就是热凉面不经过拌油冷却这个过程
It’s hot-cold noodles are not required of having the processes of mixing with the oil and wait it become cold
119
00:09:25,200 --> 00:09:27,360
实际上 最先出现的是凉面
In fact, cold noodles are the original one 
120
00:09:27,360 --> 00:09:29,640
那个时候都是挑着担子在外面卖
People used to sell the cold noodles outside by carrying around them with Danzi 
121
00:09:29,640 --> 00:09:33,040
担子的一边的放的是已经用油拌好的凉面
The one side of Danzi is filled with oil mixed cold noodles 
122
00:09:33,040 --> 00:09:34,720
另一边呢 放的是热汤
And the other side is filled with the hot broth 
123
00:09:34,720 --> 00:09:36,200
后来呢 有了凉面店
And later, there’s cold noodle house 
124
00:09:36,200 --> 00:09:38,960
有的顾客说可以把面直接放在热卤里
And some customers said the noodles can be put into the gravy 
125
00:09:38,960 --> 00:09:41,160
这么吃就是胃舒服些
And the stomach will feel a bit more comfortable  
126
00:09:41,160 --> 00:09:44,160
这个时候 热凉面才开始出现
At that time, Hot-Cold noodles began to appear 
127
00:09:44,440 --> 00:09:48,280
这么看来 热凉面应该是凉面发展的产物吧
Seems the hot-cold noodles should be the product of cold noodles development in this way 
128
00:09:50,280 --> 00:09:51,240
还有一点就是
And there is another point
129
00:09:51,240 --> 00:09:54,480
吃凉面和吃热凉面 和季节有很大的关系
The seasonality is also mostly related of choosing cold noodles and hot-cold noodles 
130
00:09:54,480 --> 00:09:59,000
像这种天气 来碗凉面 可能更配一些
A bowl of cold noodles will be more fitted in these days  
131
00:10:03,680 --> 00:10:07,360
奶奶 吃面之前要先剥蒜吗
Hi Miss, do you have to peel the garlic before you having the noodles?
132
00:10:07,360 --> 00:10:09,360
这个蒜
This garlic 
133
00:10:09,360 --> 00:10:13,400
吃这个蒜配面里面的肉
Eat this garlic with the meat from the noodles
134
00:10:13,400 --> 00:10:17,840
奶奶 您经常来吃凉面吗
Hi Miss, do you come to here all the time?
135
00:10:17,840 --> 00:10:19,520
经常吃
Yeah, very often
136
00:10:19,520 --> 00:10:22,280
他们家的凉面 就是好
Their cold noodles are very good
137
00:10:22,280 --> 00:10:27,640
凉面是咱们这边特色是吧
Cold noodles are the specialty of here?
138
00:10:27,640 --> 00:10:30,480
临洮的特色面
Lintao’s special noodles 
139
00:10:30,480 --> 00:10:34,160
您点的是热凉面还是凉面呢
Did you order the hot-cold noodles or the cold noodles?
140
00:10:34,160 --> 00:10:37,840
凉的 它那个汤不是热的吗
Cold one, but the broth is still hot?
141
00:10:37,840 --> 00:10:39,320
夏天吃这个好
It’s good of having this one in the summer 
142
00:10:42,720 --> 00:10:45,200
在临洮 满大街的都是凉面店
There are full of cold noodle houses in Lintao
143
00:10:45,200 --> 00:10:47,600
凉面呢 大家从早上起来就可以吃
Everyone can have the cold noodles right start from the day 
144
00:10:47,600 --> 00:10:49,360
一直到下午两点
Until two o’clock in the afternoon 
145
00:10:49,360 --> 00:10:52,760
早上呢 不需要点那么贵的 不需要加那么多的肉
In the morning, you don’t have to order this much amount of meat 
146
00:10:52,760 --> 00:10:55,760
一种肉 或者说加一个蛋 已经足够了
One type of meat or a braised egg should be enough 
147
00:10:55,760 --> 00:10:59,080
我的这种 我觉得加的 有点过分了
The one that I had is bit of too much 
148
00:10:59,080 --> 00:11:00,880
好了 今天的视频就到这
Aright, today’s video will be stop right here
149
00:11:02,240 --> 00:11:04,720
~~拜拜
~~Bye
150
00:11:24,360 --> 00:11:28,560
关  注
雪 鱼 探 店
