### ISSUE TITLE
[华农兄弟] 蜜汁鸡 - https://youtu.be/-JDAccwmQuc

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1324]
https://youtu.be/-JDAccwmQuc
<p>&#35270;&#39057;&#21457;&#24067;&#20110; July 28, 2020 at 11:46AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/-JDAccwmQuc

#华农兄弟：搞了点蜜蜂来养，刚好大漠叔来了，做只蜜汁鸡招待一下
#Huanong Brothers: We keep some bees here. Uncle Damo come to visit us. We serve him with a grilled chicken.

0:00:00.000,0:00:03.440
# 大家好  等一下  我就去把那個兄弟家的那個蜂蜜 (註︰他雖然確是說蜂蜜，但這個是他經常說錯的，我想寫清楚一點，下一句的「養」很清楚是蜜蜂，但英文的Keep則不太清楚，會誤以為只是蜂蜜)
Hi everyone! I'm gonna, I'll go and take my, my buddy's, his honey, honey bees.

0:00:03.440,0:00:05.620
# 全部拉到我們這邊場裡面來養
I'll gonna keep them all here at my site.

0:00:06.060,0:00:09.060
# 你看  這裡環境  還有外面好多那個花花草草哦
Look! The environment here, there are also a lot of flowers and whatever plants outside.

0:00:09.480,0:00:10.020
# 都有
There's everything.

0:00:11.380,0:00:12.140
# 蜂蜜到了 (註︰他又双叒叕把「蜂蜜」和「蜜蜂」搞錯了)
The honey is here now.

0:00:12.780,0:00:13.700
# 蜜蜂哦
I mean the honey bees.

0:00:15.760,0:00:17.780
# 有沒有塞住
Are they sealed?

0:00:17.780,0:00:18.660
# 塞住了
Yes, they are.

0:00:29.780,0:00:33.940
# 你看  這個是堵住了的  它出不來  全部蜂蜜在這裡面 (註︰這個蜂蜜其實又是想說蜜蜂，所以用Pluaral)
Look! It's sealed here. They can't come here. All the honey are inside,

0:00:34.600,0:00:35.780
# 出不來  蜜蜂
they can't come out. I mean the honey bees.

0:00:44.300,0:00:46.000
# 放邊上  一路可以放過去
Put them on the side, and all the way up there.

0:00:51.560,0:00:55.420
# 你看  全部都放好啦  這裡一路過  放過來
Look! So they're all here, from there, all the way up, up to here.

0:00:56.120,0:00:58.520
# 十幾箱  明天再來搞  上面的
I now have a dozen of boxes. Let's go on tomorrow, and put them up there.

0:00:59.680,0:01:00.860
# 現在天色有點晚
Now it's a little bit late.

0:01:11.700,0:01:14.140
# 你看  今天又搬了一箱  搬了一些下來
Look! Today I've taken another box, another couple of boxes here,

0:01:14.780,0:01:17.200
# 那裡一車  好多蜂蜜在這裡
in the car there. There are a lot of honey.

0:01:32.080,0:01:35.160
# 你看  把這些蜂箱  放在這附近
Look! I put these beehives, all around here.

0:01:35.640,0:01:38.500
# 把這個蜂箱一打開  蜂蜜就可以出來啦  蜜蜂
Once the beehives are unsealed. The honey can come out, I mean the honey bees,

0:01:38.980,0:01:39.900
# 就可以出來啦
they can come out then.

0:01:50.280,0:01:52.840
# 這些蜂箱就放在這裡  等一下  晚一點
I'll simply leave the beehives here, for a while, till later.

0:01:53.360,0:01:54.660
# 要讓它先適應一下
I gotta let them get used to,

0:01:55.240,0:01:56.800
# 這裡的  環境
the environment, here.

0:01:57.440,0:02:00.740
# 然後再把這個拉開  額  蜜蜂就出來
And then once I pull this thing out, eh, then the honey bees are come out.

0:02:01.060,0:02:02.640
# 然後就會自己采蜜啦
Then they can collect the nectar on their own.

0:02:04.000,0:02:06.320
# 像現在肯定還不敢開  一開的話它全部跑啦
I dare not open them now, no way. They all are gonna run away.

0:02:11.220,0:02:14.140
# 下次我們拉皂就放到裡面去  裡面還可以放
Next time we can take them inside. There are still more rooms inside.

0:02:17.220,0:02:20.040
# 剛好今天大漠過來啦  你看  他在上面
It just so happens that Uncle Daimo came to us today. Look! Here is up there.

0:02:28.800,0:02:30.040
# 我們要包頭哦
We need to push them to a dead end.

0:02:30.340,0:02:30.840
# 嗯
Um

0:02:31.240,0:02:32.120
# 不然抓不到啊
Otherwise you can't catch them.

0:02:40.100,0:02:42.300
# 先找啊  看哪一隻最好吃找出來
Let' see first, see which one is the most tasty.

0:02:44.740,0:02:46.060
# 全部吃的下嗎
Are you sure that you can finish all?

0:02:46.320,0:02:47.500
# 抓到的都賺了
Got it! It's worth more than the cost of my trip here.

0:02:48.840,0:02:49.700
# 賺了賺了
It's worth much more.

0:02:50.180,0:02:53.420
# 夠了夠了  一人一隻夠了  夠了夠了夠了
Enough, enough. We can have one each. Enough, enough, enough.

0:02:54.120,0:02:55.880
# 走走走走走  架火架火
Go, go, go, go, go,! Let's set the fire, set the fire!

0:03:00.580,0:03:01.560
# 這肉可以哦
Their meat is not bad, right?

0:03:01.840,0:03:02.420
# 可以可以
Not bad, not bad.

0:03:02.420,0:03:03.380
# 很香額 可以
It smells good, right?
It's not bad.

0:03:03.720,0:03:04.280
# 很香
It smells so good!

0:03:04.280,0:03:05.580
# 很香哈哈哈哈
Yes, it is. Ha ha ha ha!

0:03:06.020,0:03:07.460
# 我已經聞到香味了
I can already sense the smell now.

0:03:09.820,0:03:12.460
# 你看  這個蜂蜜  取點蜂蜜來刷那個雞
Look! This is honey. We take some honey and brush it onto the chicken.

0:03:12.840,0:03:14.100
# 做秘[SIC]汁烤雞
We're gonna make a honey grill chicken.

0:03:14.700,0:03:16.740
# 我們  搞一小碗就行啦
We're, gonna take just a small bowl of honey.

0:03:16.740,0:03:17.680
# 不用搞太多
We don't need too much.

0:03:29.980,0:03:31.680
# 這才是原裝蜂蜜啊
This is exactly what original honey should be.

0:03:31.980,0:03:33.660
# 這邊的山都是甚麼花
What kind of flowers are there on the hill here?

0:03:34.280,0:03:35.680
# 嗯  都是  野花  百花  百花咯
Um, it's like... 
Wild flowers?

0:03:35.680,0:03:36.780
# (註︰上句太多重疊，所以拆成兩句)
All different kinds of flowers.
It's multifloral.

0:03:36.780,0:03:38.160
# 就百花  這就旦花蜜啊
So it's multifloral. And this is multifloral honey.

0:03:38.160,0:03:38.660
# 對
Yup!

0:03:39.120,0:03:41.460
# 我拿刀來把它切  切成一塊一塊
I'm gonna take a knife. I need to cut it, cut it into pieces.

0:03:42.180,0:03:43.720
# 直接吃  放到碗裡面來吃  嗯
We eat right away, from the bowl.
Um!

0:03:46.440,0:03:48.740
# 你割的時候蜜蜂還跑出來啦
The bees are coming when when you're cutting it.

0:03:52.560,0:03:55.780
# 嗯  我眼鏡去哪啦  哎呀  不管啦
Um? Where are my eye glasses? Aya! Forget it.

0:03:57.260,0:03:59.300
# 哦  好哦  正好  正好拿了這塊來
Oh! Nice! 
Take this piece right, right here.

0:03:59.500,0:04:00.140
# 來  我來
Alright, let me do it.

0:04:01.660,0:04:03.940
# 用小力就可以啦  不用那麼那魯
Be gentle. Don't be too rude.

0:04:05.260,0:04:05.800
# 再來
Go on.

0:04:22.680,0:04:24.680
# 嗯~捧哦
Um! It's nice!

0:04:25.400,0:04:26.360
# 這個很靚
It's really beautiful!

0:04:26.740,0:04:28.680
# 你看  這種蜜是很好的蜜哦這種
Look! This kind of honey is really good honey, you know.

0:04:35.220,0:04:37.040
# 哦  掉了誒  不要浪費了
Oh! It drops! Ey! Don't waste it!

0:04:37.760,0:04:39.640
# 三秒鐘肉就不髒啊
It doesn't get contaminated in less than three seconds. 

0:04:42.040,0:04:43.420
# 嗯  不要浪費  不要浪費
Um! Don't waste it, don't waste it.

0:04:45.960,0:04:47.480
# 它這花粉是茶花
The pollen here is from tea flowers.

0:04:47.820,0:04:48.320
# 嗯
Um

0:04:49.640,0:04:50.740
# 有茶花的味道
There's a scent of tea flowers.

0:04:50.960,0:04:51.460
# 嗯
Um

0:04:51.460,0:04:54.720
# 等下我們用來烤那個  蜜汁 蜜汁烤雞
We're gonna use it and make a, a honey, honey grill chicken.

0:04:54.740,0:04:56.420
# 淡香  有點小淡香
Subtle fragrance. There's a subtle fragrance.

0:04:56.680,0:04:59.680
# 那個蠟  蠟特別濃  我這  這一  這一塊很濃
The beeswax, is exceptionally rich. The piece, this, this piece that I have here, is really rich.

0:04:59.680,0:05:01.860
# 這個你嚼一下這個蠟  越嚼越香
You can chew the beeswax, and then the fragrance would become more significant.

0:05:03.200,0:05:04.040
# 我們拿下去吃
Let's enjoy it down there.

0:05:04.920,0:05:06.680
# 你看  剛好今天人比較多哦
Look! It just so happens that there are quite a lot of people here today.

0:05:06.860,0:05:09.600
# 順便搞了兄弟家兩隻雞  我也湊了一個鴨
So I've taken two chicks from my buddy. I've also contributed a duck.

0:05:11.200,0:05:14.080
# 把它宰好啦   準備把它清理一下
I've already got them ready. I'm gonna wash and clean them.

0:05:15.840,0:05:16.620
# 清理一下
Wash them.

0:05:17.540,0:05:18.680
# 把這雞腌一下
Let me marinate the chicken.

0:05:19.080,0:05:19.720
# 放這裡
Put it here.

0:05:20.780,0:05:21.900
# 搞點鹽
Put some salt.

0:05:22.800,0:05:23.620
# 腌一下
Marinate it.

0:05:24.560,0:05:25.860
# 再搞點醬油
Then put some say sauce.

0:05:29.580,0:05:30.200
# 再加點
And also some,

0:05:31.240,0:05:32.080
# 料酒
cooking wine.

0:05:33.540,0:05:35.040
# 加完之後再加點
After that, let's put some,

0:05:36.380,0:05:37.700
# 加點這個油
put some, some oil.

0:05:40.820,0:05:41.920
# 再搞點生薑
And also some ginger

0:05:44.620,0:05:46.820
# 先把這個邊上割一點花出來
Let me slice it a few times on this side.

0:05:48.200,0:05:49.420
# 更入味 這樣就
It will then be, much more flavourful.

0:05:54.460,0:05:56.540
# 特別是這個  雞胸肉
Especially the, chicken breast,

0:05:58.860,0:06:00.440
# 雞胸肉最厚的
chicken breast is always the thickest.

0:06:09.720,0:06:11.820
# 好啦  再給它莫兩下就好啦
Alright! Rub it a few more times and that's it.

0:06:14.480,0:06:16.080
# 嗯  先腌半個小時先
Um! Marinate it for half an hour first.

0:06:16.240,0:06:17.860
# 把這個雞放下去過一下水
I put the chicken here and blanch it for a while first.

0:06:19.040,0:06:20.700
# 這小雞  小雞仔
It's a chicken, a small chicken.

0:06:21.660,0:06:23.540
# 剛好香菇也放下去一下過水
I'm also putting the shiitake mushrooms and blanch them together.

0:06:23.820,0:06:25.800
# 過了水就直接撈起來  就直接
After blanching, I can take them out, and then,

0:06:26.780,0:06:29.080
# 香菇 嘖  燜小雞
stew the mushrooms, with chicken right away.

0:06:30.940,0:06:32.400
# 好啦  直接把它蓋  蓋起來
Alright! Let me just cover, cover it right away.

0:06:38.960,0:06:43.160
# 這是以前的灶台哦  你看  現在還有用  大水沒把它沖走
This used to be our stove, and it's now still good. The flood didn't wash it away.

0:06:44.000,0:06:44.900
# 我們繼續用
Let's keep on using it.

0:06:55.740,0:06:57.200
# 你看  兩邊有火
Look! Fire on both sides

0:06:59.460,0:07:01.940
# 現在  火還沒升起來哦  搞點這個
Now we're waiting for the fire to glow. Here I have some...

0:07:02.400,0:07:05.120
# 嘗一下我們這邊的土特產  吃一下
This is our local specialty here. Have a try!

0:07:05.620,0:07:06.240
# 燙皮
It's "tang pi" (baked ground rice chips).

0:07:08.960,0:07:10.180
# 這個包裝可以哦
This package is not bad.

0:07:14.420,0:07:15.360
# 這一個特產哦
This is a local specialty, isn't it?

0:07:15.580,0:07:17.720
# 我吃了好多啦  上午我吃了好多啦
I've had a lot. I've already eaten a lot this morning,

0:07:18.760,0:07:20.080
# 我吃的都飽了
so much that I'm already full now.

0:07:20.380,0:07:23.200
# 河邊燒烤哦  別有一番風情
A riverside barbecue. It's really exotic.

0:07:23.200,0:07:26.240
# 但是要注意這種天氣還是比較熱  今天三十來度是吧
But you gotta pay attention to the weather. It's rather hot today. It's thirty some degrees, right?

0:07:26.660,0:07:27.560
# 三十六度  三十六  嗯
Thirty six degree.

0:07:27.560,0:07:28.500
# (上一句分成兩句)
Thirty six.
Um.

0:07:28.500,0:07:30.220
# 所以要多喝水防止中暑
So we need to drink more water to prevent heat stroke.

0:07:30.580,0:07:31.880
# 只在那水裡也可以
Lying in the water also works.

0:07:33.320,0:07:34.180
# 也可以哦
It also works right?

0:07:34.500,0:07:35.220
# 防止中暑
It prevents heat stroke.

0:07:45.940,0:07:48.380
# 你看  把這個雞
Look! I'm gonna tie,

0:07:49.940,0:07:52.000
# 綁起來 綁起來再烤
tie up, tie up the chicken and then grill it.

0:07:54.360,0:07:55.640
# 剛好帶了個鐵絲來
It just so happens that I have a wire with me.

0:07:57.040,0:07:58.040
# 把它腳綁起來
I can tie up its feet.

0:08:04.740,0:08:06.340
# OK  你看  搞定
OK! Look! It's done!

0:08:06.640,0:08:08.700
# 哦  這樣  這樣大家看一下哦
Oh! Then, now, everybody have a look!

0:08:09.100,0:08:12.260
# 他這樣  按照華農兄弟這樣綁那雞就跑不了啦
Tying it up in Huanong's way can prevent the chicken from running away.

0:08:12.560,0:08:14.760
# 這樣你給它跑  它跑不了啦  你看
Then it can no longer run away even if you're not watching it.Look!

0:08:14.760,0:08:18.320
# 像這就是為甚麼要綁腳哦 綁腳的原因就在這裡
That's why he needs to tie up the feet. Here's the reason for tying up the feet.

0:08:19.780,0:08:22.580
# 誒  這樣跑不掉了嘛  跑不了了  跑不了了
Ey! Then it can no longer run away. No way, no way.

0:08:24.720,0:08:28.380
# 等一下這個火  等它滅  等它滅了再說
Let's wait until the fire, until the fire goes off.

0:08:35.860,0:08:37.380
# 哇  差不多可以烤啦
Wa! I think we can start grilling now.

0:08:51.000,0:08:52.120
# 我們刷點油
Let's brush some oil.

0:08:53.280,0:08:54.400
# 不然太乾啦
It would be too dry otherwise.

0:08:56.500,0:08:57.840
# 給它皮膚做下
I'm giving its skin,

0:08:58.660,0:08:59.720
# 做下潤滑
some moisturiser.

0:09:10.860,0:09:14.080
# 哎呀這個  炭都滅掉啦  沒甚麼火
Aya! The charcoals is not longer burning. There's hardly any fire.

0:09:14.300,0:09:16.360
# 回家裡烤算啦 現在太晚啦
Let's just grill it at home. It's too late now.

0:09:16.780,0:09:17.680
# 還沒吃晚飯
I still haven't had my dinner.

0:09:18.020,0:09:21.160
# 還沒吃 午飯  不然我帶回家裡
I still haven't had, my lunch. Well I'm taking it home.

0:09:21.860,0:09:23.700
# 肚子餓的很  還沒烤熟
I'm staving, but it still needs a longer time.

0:09:24.740,0:09:28.060
# 這個兄弟家的炭不行啊  我帶了  我拿著我家的炭來烤
This is my buddy's charcoal. It's no good. I'll take, I'm gonna grill with my own charcoal.

0:09:29.420,0:09:30.600
# 把這個火滅掉
Let's put off the fire here.

0:09:40.660,0:09:42.780
# 你看  這個家裡的燙也煲好啦
Look! The soup at home is also done,

0:09:42.780,0:09:45.660
# 雞  那個鴨也搞好啦  雞燙也煲好啦
chick, and also the duck, and also the chicken soup.

0:09:46.300,0:09:50.300
# 搞兩塊 我先吃啦  我先吃了這些再說
Let me have some. I'm gonna eat first. I eat something here first.

0:09:51.200,0:09:52.600
# 人都餓的乾趴趴啦
I'm starving and am about to pass out.

0:09:54.560,0:09:55.460
# 誒呀  好香
Eya! It smells good!

0:10:00.520,0:10:01.500
# 味道太好吃啦
It tastes simply marvellous!

0:10:05.420,0:10:07.200
# 我們吃完飯接著烤那個雞
We'll have our lunch first and then continue with the chicken.

0:10:08.160,0:10:09.840
# 先把  先把午飯吃了再說
Let's, let's have our lunch first, before everything

0:10:10.300,0:10:13.140
# 你看  午飯都做好啦  我們先吃午飯吧
Look! Our lunch is here. Let's have our lunch!

0:10:14.500,0:10:18.240
# 你看 鴨子  南瓜  青菜  碗豆
Look! Here are duck, pumpkins, veggies, green peas,

0:10:18.820,0:10:19.640
# 蘿蔔
radish,

0:10:20.520,0:10:22.320
# 還有  紫薯豬  (註︰這個發音錯誤不應該直接翻譯，找個近似的找替)
and also, purple yam cock,

0:10:22.320,0:10:23.260
# 紫薯粥
purple yam congee.

0:10:25.840,0:10:26.620
# 開始開始
Let's start, let's start!

0:10:26.620,0:10:27.120
# 開始
Let's start!

0:10:27.480,0:10:29.120
# 吃完飯啦  就想吃西瓜
After lunch, now I want some watermelons.

0:10:29.500,0:10:32.100
# 上次我摘了兄弟家  搞了十幾個西瓜  現在還有
Last time, I've taken, taken dozens of watermelons from my buddy's place. Now I still have some.

0:10:33.020,0:10:34.900
# 今天就沒有啦  吃完這兩個
But no more today. These two are the last ones.

0:10:37.060,0:10:38.700
# 哇 鮮紅色
Wa! It's shinning red.

0:10:39.360,0:10:40.840
# 這樣的西瓜肯定很好吃
This kind of watermelons is certainly tasty.

0:10:41.540,0:10:42.620
# 先端走一半
Take away this half first.

0:10:55.560,0:10:58.060
# 你去那裡搞  搞  搞這些  這些西瓜
Where did you get, get, get these, these watermelons?

0:10:58.940,0:10:59.740
# 後面搞的
I picked them back there.

0:11:01.340,0:11:02.520
# 還是兄弟家的咯
And I bet that there are from your buddy, right?

0:11:04.020,0:11:06.580
# 兄弟家大把  他家吃不完  我幫他吃一下
My buddy has a lot! He can't finish them. So I'm helping him.

0:11:06.800,0:11:08.620
# 嘿嘿嘿 我也在幫他吃
He he he! And I'm also helping him now.

0:11:09.480,0:11:11.080
# 等一下要不要一起去  搞一點
You wanna get some, together with me, in a while?

0:11:11.720,0:11:12.400
# 一會兒嗎
In a while?

0:11:12.920,0:11:15.720
# 誒  我剛剛到村裡面  村民去哪啦  跑完啦
Ey? I was just in the village. Where are the villagers. Did they all run away?

0:11:16.500,0:11:19.380
# 不知道  在田裡面乾活吧  看西瓜熟了
No ideas. I think they're working in the fields. the watermelons are ripe now.

0:11:19.400,0:11:23.120
# 不可能  現在十二點啦  十二點了一個村民沒看到
No, it's impossible. It's now twelve at noon, at noon and not even a single villager came into my eyes.

0:11:24.380,0:11:26.000
# 這個時候西瓜剛好成熟
The watermelons are becoming ripe in this period of time.

0:11:26.200,0:11:26.820
# 哦
Oh!

0:11:27.360,0:11:29.140
# 可能他們幾乎去搞西瓜啦
So I think almost everybody is picking the watermelons.

0:11:29.240,0:11:30.440
# 哦哦哦哦哦
I see, I see, I see, I see, I see.

0:11:30.660,0:11:32.240
# 一會我們去搞一點  再搞一點
Let's pick some, some more in a while.

0:11:32.800,0:11:34.260
# 我今天早  早上打電話給他
I phoned him this morning.

0:11:34.520,0:11:36.260
# 打了一早上他沒接  不知道幹嘛
I've been phoning for the while morning. But he didn't answer. Who knows what he was doing.

0:11:36.740,0:11:37.460
# 我兄弟  哦  沒有接  對啊
My buddy

0:11:37.460,0:11:39.100
# (上一句分兩句)
Oh! He didn't answer.
Exactly

0:11:41.520,0:11:43.960
# 本來我說帶你去搞兄弟家西瓜的
Originally, I wanted to take you to pick some watermelons at my buddy's place.

0:11:43.960,0:11:46.420
# 反正我一路拍過來  我在村裡面一路拍
I was like, filming all along the way. We were filming all along the way in the village.

0:11:46.420,0:11:47.640
# 一個村民都沒有
But we saw not even one villager.

0:11:48.220,0:11:49.080
# 很奇怪
It's weird.

0:11:49.080,0:11:50.080
# 人比較少
Not many people are here.

0:11:50.480,0:11:51.480
# 現在人少是吧
There are not so many people now, right?

0:11:51.720,0:11:52.960
# 對  只有老人跟孩子
Yup! Only the elderlies and the children are here.

0:11:53.580,0:11:55.260
# 哦  老人孩子也沒看到
Oh! But I saw nobody, neither elderlies, nor children.

0:11:55.640,0:11:56.240
# 在家裡
They stay at home.

0:11:56.820,0:11:57.460
# 哦
I see.

0:11:58.540,0:12:01.460
# 今天上午沒把它烤熟  今天下午我們繼續
We were in the halfway this morning. So let's continue now in the afternoon.

0:12:04.040,0:12:05.900
# 今天上午的火候不猛
The fire this morning was not strong enough.

0:12:16.340,0:12:18.300
# 現在是拿了一個凳子給爸爸坐是不是
So you are bringing daddy a stool, aren't you?

0:12:19.100,0:12:20.340
# 謝謝謝謝謝
Thx, thx thx!

0:12:20.620,0:12:23.680
# 去  去那邊坐著玩啊 等下烤好雞就叫你來吃啊
Go! Have a seat over there. I'll call you when the chicken is done.

0:12:24.700,0:12:26.200
# 去  家裡坐好來
Get, get a seat inside.

0:12:37.100,0:12:38.580
# 擦點蜂蜜給它身上
Let me brush some honey onto its body.

0:12:41.040,0:12:42.040
# 精油Spa
Essential oil spa

0:12:42.940,0:12:44.100
# 給它接一下摩
I give it a massage.

0:12:44.100,0:12:45.540
# 額  還要按一下摩啊
Eh! It even needs a massage.

0:12:47.160,0:12:48.160
# (雞)脖子都快斷啦
Its neck is about to break.

0:12:49.300,0:12:50.060
# 小心一點
I gotta be careful.

0:12:52.660,0:12:53.860
# 全身都擦的到
It's brushed all over the body.

0:12:54.920,0:12:56.620
# 油  油光油光啊
It's oily, shinning oily, right?

0:12:56.940,0:12:59.660
# 對呀  蜂蜜撚到它每一寸肌膚
Yup! The honey is brushed onto every inch of its skin.

0:12:59.840,0:13:00.440
# 嗯
Um

0:13:02.860,0:13:04.100
# 腳趾上也抺一點
And also on the toes

0:13:05.000,0:13:08.580
# 搞(好？)  開始  稍微再烤一下就可以了
Alright. Let's start. We just need to slightly grill it for another short while.

0:13:09.280,0:13:10.300
# 我先洗個手再來
I'll come back after washing my hands.

0:13:15.300,0:13:16.340
# 這雞烤好啦
The chicken is done.

0:13:17.300,0:13:18.420
# 來 大漠叔叔
Hey! Uncle Daimo!

0:13:18.640,0:13:20.180
# 來  直接開始吃了哈
Alright! We can start eating right away.

0:13:20.200,0:13:21.300
# 嗯 來來
Um! C'mon, c'mon!

0:13:23.960,0:13:25.000
# 嗯  棒哦
Um! Excellent!

0:13:25.200,0:13:25.980
# 我也要
Me too!

0:13:27.960,0:13:28.500
# 不夠粗魯
You're not rude enough.

0:13:28.500,0:13:29.140
# 有點燙
It's a bit hot.

0:13:30.380,0:13:31.360
# 幫我拿一下
Hold it for me.

0:13:31.680,0:13:32.900
# 你直接放口袋裡面
Why don't you just put it in your pocket right away?

0:13:37.680,0:13:39.040
# 這一塊  這一塊
This piece, this piece...

0:13:39.040,0:13:40.960
# 我想吃這一塊  嗯好  你吃這一塊
I want this piece.
Alright! You take this piece.

0:13:43.560,0:13:44.220
# 怎麼樣
How is it?

0:13:44.940,0:13:45.840
# (拿不到)  (註︰原字幕沒有這句，但刘星辰說得太清楚了，不想去掉)
I can't take it.

0:13:47.620,0:13:49.120
# 哦  很甜
Oh! It's so sweet!

0:13:49.620,0:13:50.620
# 嗯  加點蜂蜜還不錯
Um! The honey really makes a difference.

0:14:02.020,0:14:02.520
# 香不香
Is it good?

0:14:03.280,0:14:04.740
# 哇  我要吃肉
Wa! I want a piece of meat.

0:14:05.020,0:14:05.560
# 不要吃肉
You want meat, right?

0:14:05.560,0:14:06.700
# 嗯  有點燙
Um! It's a bit hot.

0:14:07.740,0:14:08.280
# 還要嗎
You want more?

0:14:08.540,0:14:10.320
# 你還要不要  你要不要皮  這個
You want more? You want a piece of skin? Here.

0:14:10.320,0:14:12.760
# 要要要  我要皮  我不要皮
Yea, yea, yea! I want skin!
No, I don't want!

0:14:14.980,0:14:15.960
# 皮才有味
The skin is the most flavourful.

0:14:21.240,0:14:23.980
# 兩下就被 被小孩搶光啦  我就吃了個雞頭哦
The kids finished, finished the whole chicken in seconds. And I'm now eating the chicken head.

0:14:24.300,0:14:25.300
# 沒有啦
There's no more.

0:14:26.160,0:14:26.700
# 沒啦
Nothing more

0:14:27.600,0:14:28.240
# 要不要雞頭
You want chicken head?

0:14:36.900,0:14:38.100
# 嗯 味道很不錯
Um! It tastes really not bad.

0:14:41.760,0:14:43.600
# 好啦  下次我要烤五個來
Alright! Next time I'm gonna grill five chickens.

0:14:44.060,0:14:45.120
# 它這太少啦  這個
It's far from enough, here.

0:14:45.880,0:14:46.860
# 一下就吃完啦
Everything is gone in a second.

0:14:54.740,0:14:57.280
# 幸好我搶得快  吃了三個
Fortunately, I was fast time. So I had three pieces.

0:15:08.940,0:15:11.280
# 給你的  你最小的 寶貝
It's for you! You're the smallest, baby!

0:15:13.500,0:15:14.500
# 一起玩  一起玩
We play together, play together

0:15:25.420,0:15:28.420
# 它這  這是甚麼 這是  花灑  哈哈哈哈
It's a, what is it? It's a shower. Ha ha ha ha!

0:15:31.120,0:15:34.640
# 看一下這甚麼  這鏡子  哦
See what it is? It's a mirror, oh!

0:15:35.280,0:15:36.020
# 是不是
Isn't it?

0:15:36.260,0:15:37.980
# 這個是她化妝的
She uses it when use puts on the makeup.

0:15:38.000,0:15:39.880
# 是不是真的有用的  哎呀  真的有用
Is it a really mirror? Aya! It's real one.

0:15:41.380,0:15:43.420
# 匆匆忙忙的二天就過去啦
It's the end of a hectic day.

0:15:44.060,0:15:44.820
# 謝謝兄弟 
Thank you man!

0:15:44.820,0:15:46.720
# 帶點我們本地的東西回去
Bring some, bring some of our local products back home.

0:15:47.540,0:15:50.180
# 這一次也有點美中不足
There are still some rooms to perfection.

0:15:50.180,0:15:50.740
# 美中不足 
Some rooms to perfection

0:15:50.740,0:15:52.040
# 就是  還  還有嗎
I mean, are there, are there any more?

0:15:52.460,0:15:54.120
# 再  再給一點  再給一點
Give, give me more, give me more!

0:15:54.120,0:15:56.060
# 其實我還能拿的下  還能拿  能拿
In fact I can still take more.
I can, I surely can.

0:15:56.080,0:15:58.780
# 地址  地址  把地址給我們  我們到時候就寄
Address, address, give us your address and then we can send you.

0:15:59.120,0:16:01.940
# 不 我們現在能拿嗎  能拿就再拿一點吧
No. Can we take now? If yes, I can still take more.

0:16:01.940,0:16:03.820
# 誒誒  能拿  我們能拿
Ey, ey! Yes, we can take more.

0:16:03.820,0:16:05.300
# 額 我們還有後備箱
Eh! We still have a spare suitcase.
