### ISSUE TITLE
[老饭骨] 酸辣瓜条 - https://youtu.be/IljXmwSD2TQ

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1328]
**视频链接**：https://youtu.be/IljXmwSD2TQ

YouTube 视频如果无法访问，请参考抖音视频：
- 酸辣瓜条：https://v.douyin.com/J2Ky5Dh/
- 大爷日常：https://v.douyin.com/J2K64ty/
- 二伯日常：https://v.douyin.com/J2KFLQu/

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•】夏季开胃小凉菜：酸辣瓜条，爽口开胃，脆嫩多汁，调出万能凉拌汁！大爷二伯的日常|老饭骨

简介
小友们好！今儿星期五，大师姐给我们们带来了一道经典的开胃凉菜——酸辣瓜条。
这道精品小凉菜在很多重要宴会上都出现过，大师姐这次做出来的味道和40年前的一样，一点儿都没走味儿！
学会了这个万能凉拌汁，黄瓜皮，黄瓜卷，萝卜皮，油吃黄瓜，珊瑚白菜这些菜都能做！
片尾附上大爷和二伯的生活小花絮，不知道这样的大爷和二伯小友们喜欢吗？

字幕
1
00:00:00,000 --> 00:00:02,440
重要宴会都上过这道菜 很精品

2
00:00:02,440 --> 00:00:04,760
这也是我上学的时候做的一道菜

3
00:00:04,760 --> 00:00:07,320
传统菜 酸辣瓜条

4
00:00:07,320 --> 00:00:08,880
今天主要使用的

5
00:00:08,880 --> 00:00:11,640
黄瓜 葱丝 姜丝 辣椒丝

6
00:00:11,640 --> 00:00:12,800
我提前准备好了

7
00:00:12,800 --> 00:00:15,120
咱们先把黄瓜处理一下

8
00:00:15,120 --> 00:00:16,720
给大家讲一小窍门

9
00:00:16,720 --> 00:00:18,800
把这个头这儿去完以后

10
00:00:18,800 --> 00:00:21,280
咱们手指头这个是变不了的

11
00:00:21,280 --> 00:00:23,720
卡在这儿 一切

12
00:00:23,720 --> 00:00:27,760
这样瓜条到什么时候它都是一边长

13
00:00:27,760 --> 00:00:30,400
合理的一个大约在五公分

14
00:00:30,400 --> 00:00:32,320
黄瓜心咱们给它去掉

15
00:00:32,320 --> 00:00:34,880

16
00:00:34,880 --> 00:00:37,960
为什么呢 因为黄瓜心它容易出汤

17
00:00:37,960 --> 00:00:41,160
切完了要求它都得一边长

18
00:00:41,160 --> 00:00:43,120
出来摆盘比较好看

19
00:00:43,120 --> 00:00:45,600
这个黄瓜条切完了 咱们杀上盐

20
00:00:45,600 --> 00:00:49,360
先出一下水 别怕盐多

21
00:00:49,360 --> 00:00:50,840
稍稍多一点没事

22
00:00:50,840 --> 00:00:54,320
待会咸味一出汤以后就带走了

23
00:00:54,320 --> 00:00:55,840

24
00:00:55,840 --> 00:00:59,960
咱们把黄瓜先搁一边 腌着备用

25
00:00:59,960 --> 00:01:01,400
开始操作了

26
00:01:01,400 --> 00:01:05,600
最主要的就是辣椒丝 葱丝 姜丝

27
00:01:05,600 --> 00:01:06,400
这都是我提前准备好的

28
00:01:06,400 --> 00:01:07,800
这个量还挺大的

29
00:01:07,800 --> 00:01:09,680
这个汁儿咱们可以多炒一点

30
00:01:09,680 --> 00:01:13,880
您分两次或者三次吃都可以

31
00:01:13,880 --> 00:01:16,120
下面咱们调汁 点火

32
00:01:16,120 --> 00:01:21,640
锅烧热了 咱们记住一定是放香油

33
00:01:21,640 --> 00:01:22,800
香油香啊

34
00:01:22,800 --> 00:01:25,760
过去做凉菜炒汁的时候

35
00:01:25,760 --> 00:01:27,240
一般使香油使的比较多

36
00:01:27,240 --> 00:01:29,760
这个菜香油必须得加热

37
00:01:29,760 --> 00:01:32,720
不加热它的香度太大

38
00:01:32,720 --> 00:01:37,160
然后通过加热把一些浓度释放出来

39
00:01:37,160 --> 00:01:39,400
先煸姜 先下姜

40
00:01:39,400 --> 00:01:42,960
姜丝 葱丝

41
00:01:42,960 --> 00:01:45,600
这个菜的关键就是用香油煸

42
00:01:45,600 --> 00:01:49,880
辣椒丝 把它煸出香味来

43
00:01:49,880 --> 00:01:53,720
咱们注意 这个辣椒别给它炒糊了

44
00:01:53,720 --> 00:01:57,360
油温别太高 搁进去以后一下糊了

45
00:01:57,360 --> 00:01:59,560
它影响后边的口感

46
00:01:59,560 --> 00:02:02,200
大爷你看没有香油味都没了

47
00:02:02,200 --> 00:02:04,320
全是辣椒和葱姜丝的味

48
00:02:04,320 --> 00:02:05,520
葱姜丝的香味出来了

49
00:02:05,520 --> 00:02:08,680
咱们下边 米醋

50
00:02:08,680 --> 00:02:13,680
北京的米醋 北京米醋有名

51
00:02:13,680 --> 00:02:15,840
然后咱们光是米醋的味道不够

52
00:02:15,840 --> 00:02:18,440
咱们再加点白醋

53
00:02:18,440 --> 00:02:20,640

54
00:02:20,640 --> 00:02:22,960
加白醋的味道立马就窜出来了

55
00:02:22,960 --> 00:02:25,680
你这糖也不少加啊

56
00:02:25,680 --> 00:02:30,880
有三百克差不多吧

57
00:02:30,880 --> 00:02:32,560
就因为加了糖以后

58
00:02:32,560 --> 00:02:35,480
它这汁粘稠了而且有亮度

59
00:02:35,480 --> 00:02:39,160
咱们这样太浓了这汁 咱再加点水

60
00:02:39,160 --> 00:02:42,400

61
00:02:42,400 --> 00:02:44,720
这能泡好多黄瓜啊

62
00:02:44,720 --> 00:02:47,040
咱们这个汁一次调好了以后

63
00:02:47,040 --> 00:02:50,080
可以放在冰箱里 它也不坏

64
00:02:50,080 --> 00:02:52,760
加点盐

65
00:02:52,760 --> 00:02:54,960
来咱们点一点酱油

66
00:02:54,960 --> 00:02:55,960

67
00:02:58,800 --> 00:03:01,600
实际上这是凉菜一个特殊的味道

68
00:03:01,600 --> 00:03:02,840
一个味儿型

69
00:03:02,840 --> 00:03:06,200
适合自己的才是好的味道

70
00:03:06,200 --> 00:03:09,040
咱们这边差不多了 晾凉

71
00:03:09,040 --> 00:03:11,560

72
00:03:12,280 --> 00:03:14,720
咱们熬汁的时候速度要快

73
00:03:14,720 --> 00:03:17,160
锅一开咱们就得给它盛出来

74
00:03:17,160 --> 00:03:20,160
要不然醋挥发的就跑了

75
00:03:20,160 --> 00:03:22,440
然后再搁冰箱里边腌制（镇凉）

76
00:03:22,440 --> 00:03:24,280
你看现在腌了多长时间了

77
00:03:24,280 --> 00:03:26,200
有个半个小时

78
00:03:26,200 --> 00:03:28,680
刚开始腌的时候是出汤

79
00:03:28,680 --> 00:03:31,080
然后一刻钟时候我尝了是皮的

80
00:03:31,080 --> 00:03:33,520
现在你看时间到了是脆的

81
00:03:33,520 --> 00:03:35,440
您看着里面的水

82
00:03:35,440 --> 00:03:38,160
咱把它给倒出去 篦出去

83
00:03:38,160 --> 00:03:39,840
所以说它必须得腌够了时间

84
00:03:39,840 --> 00:03:41,040
把它澄干净

85
00:03:41,040 --> 00:03:46,040
您看咱们这个汁也凉了 越凉越粘稠

86
00:03:46,040 --> 00:03:48,200
咱们把这个汁倒进去

87
00:03:48,200 --> 00:03:50,360
大爷你这要搁一宿

88
00:03:50,360 --> 00:03:52,280
明天早上再吃才 那爽

89
00:03:52,280 --> 00:03:53,800
咱们把这拌一下

90
00:03:53,800 --> 00:03:55,640
明天早上一吃 脆爽脆爽的

91
00:03:55,640 --> 00:03:59,400
咱们这个再腌俩小时 俩小时以后 好

92
00:03:59,400 --> 00:04:01,640
放冰箱里头镇一下

93
00:04:01,640 --> 00:04:03,720
师伯咱么这个腌好了

94
00:04:05,400 --> 00:04:06,920
您看这个黄瓜条

95
00:04:06,920 --> 00:04:11,960
皮儿朝上 而且瓜条宽窄长短都一样了

96
00:04:11,960 --> 00:04:14,360
这样摆出来就整齐好看

97
00:04:14,360 --> 00:04:16,320
行了差不多了

98
00:04:16,320 --> 00:04:18,640
差不多了 然后咱们把这个料

99
00:04:18,680 --> 00:04:22,400
把料搁在上边 点缀

100
00:04:22,400 --> 00:04:26,440
你看这没有过多的去修饰 简简单单

101
00:04:31,400 --> 00:04:34,240
四十年前的味道 一点都没走味儿

102
00:04:34,240 --> 00:04:36,640
为什么老说这小菜很重要

103
00:04:36,640 --> 00:04:39,800
到一酒店吃饭 进门的菜是什么菜

104
00:04:39,800 --> 00:04:41,800
不是热菜 是凉菜

105
00:04:41,800 --> 00:04:45,240
重要宴会其实都上过这道菜 很精品

106
00:04:45,240 --> 00:04:47,200
这个汁咱们还可以做

107
00:04:47,200 --> 00:04:49,440
黄瓜皮 黄瓜卷 萝卜皮

108
00:04:49,440 --> 00:04:51,440
油吃黄瓜 珊瑚白菜

109
00:04:51,440 --> 00:04:54,280
基本上和这个口味上差不多

110
00:04:54,280 --> 00:00:02,000


```

**Comment by glasscatfish** [comment]
认领

**Comment by glasscatfish** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•】夏季开胃小凉菜：酸辣瓜条，爽口开胃，脆嫩多汁，调出万能凉拌汁！大爷二伯的日常|老饭骨
Spicy and Sour Cucumber with All Purpose Sauce 

简介
小友们好！今儿星期五，大师姐给我们们带来了一道经典的开胃凉菜——酸辣瓜条。
这道精品小凉菜在很多重要宴会上都出现过，大师姐这次做出来的味道和40年前的一样，一点儿都没走味儿！
学会了这个万能凉拌汁，黄瓜皮，黄瓜卷，萝卜皮，油吃黄瓜，珊瑚白菜这些菜都能做！
片尾附上大爷和二伯的生活小花絮，不知道这样的大爷和二伯小友们喜欢吗？
Hellow! It’s Friday, Shijie is going to bring us a classical cold dish -- Spicy and Sour Cucumber
This dish has shown up in multiple banquets. Shijie is going to make it taste like how it was 40 years ago.
Once you learn this sauce, you can use it in different cold dishes!
There will be add-on sidelights of Da Ye and Er Bai at the end, would you like it?

字幕
1
00:00:00,000 --> 00:00:02,440
重要宴会都上过这道菜 很精品
This is a banquet dish, very classical

2
00:00:02,440 --> 00:00:04,760
这也是我上学的时候做的一道菜
It is also a dish I made when I was in school

3
00:00:04,760 --> 00:00:07,320
传统菜 酸辣瓜条
It’s a traditional dish Spicy and Sour Cucumber

4
00:00:07,320 --> 00:00:08,880
今天主要使用的
Today we are using

5
00:00:08,880 --> 00:00:11,640
黄瓜 葱丝 姜丝 辣椒丝
Cucumber, Julienne Spring Onion, Julienne Ginger, Julienne Dried Chilies

6
00:00:11,640 --> 00:00:12,800
我提前准备好了
I’ve prepared them in advance
7
00:00:12,800 --> 00:00:15,120
咱们先把黄瓜处理一下
Let’s first cut the cucumber

8
00:00:15,120 --> 00:00:16,720
给大家讲一小窍门
I’ll share some tricks

9
00:00:16,720 --> 00:00:18,800
把这个头这儿去完以后
Once you cut off the end

10
00:00:18,800 --> 00:00:21,280
咱们手指头这个是变不了的
The length of your finger doesn’t change

11
00:00:21,280 --> 00:00:23,720
卡在这儿 一切
So you could measure the length of cucumber strips with your finger

12
00:00:23,720 --> 00:00:27,760
这样瓜条到什么时候它都是一边长
To keep them the same size 

13
00:00:27,760 --> 00:00:30,400
合理的一个大约在五公分
About 5cm

14
00:00:30,400 --> 00:00:32,320
黄瓜心咱们给它去掉
Let’s remove the seeds

15
00:00:32,320 --> 00:00:34,880

16
00:00:34,880 --> 00:00:37,960
为什么呢 因为黄瓜心它容易出汤
To remove extra moisture

17
00:00:37,960 --> 00:00:41,160
切完了要求它都得一边长
Make sure to keep them the same length

18
00:00:41,160 --> 00:00:43,120
出来摆盘比较好看
So they look pretty 

19
00:00:43,120 --> 00:00:45,600
这个黄瓜条切完了 咱们杀上盐
Once we cut the cucumber, sprinkle some salt on it

20
00:00:45,600 --> 00:00:49,360
先出一下水 别怕盐多
Let the moisture come out. Don’t be afraid there’s too much salt 

21
00:00:49,360 --> 00:00:50,840
稍稍多一点没事
It’s okay to go a little heavy on salt

22
00:00:50,840 --> 00:00:54,320
待会咸味一出汤以后就带走了
It will be removed with the moisture

23
00:00:54,320 --> 00:00:55,840

24
00:00:55,840 --> 00:00:59,960
咱们把黄瓜先搁一边 腌着备用
Let’s put the cucumber aside, let it sit

25
00:00:59,960 --> 00:01:01,400
开始操作了
And start making the sauce

26
00:01:01,400 --> 00:01:05,600
最主要的就是辣椒丝 葱丝 姜丝
Mainly Julienne Chili, Spring Onion and Julienne Ginger

27
00:01:05,600 --> 00:01:06,400
这都是我提前准备好的
I’ve prepared them in advance

28
00:01:06,400 --> 00:01:07,800
这个量还挺大的
This is a big portion

29
00:01:07,800 --> 00:01:09,680
这个汁儿咱们可以多炒一点
You can make it in advance

30
00:01:09,680 --> 00:01:13,880
您分两次或者三次吃都可以
And use it whenever it’s needed

31
00:01:13,880 --> 00:01:16,120
下面咱们调汁 点火
Let’s start! Turn on the stove

32
00:01:16,120 --> 00:01:21,640
锅烧热了 咱们记住一定是放香油
Warm the wok. Make sure to use sesame oil

33
00:01:21,640 --> 00:01:22,800
香油香啊
It’s aromatic

34
00:01:22,800 --> 00:01:25,760
过去做凉菜炒汁的时候
We’ve always used sesame oil

35
00:01:25,760 --> 00:01:27,240
一般使香油使的比较多
When making sauce for cold dished

36
00:01:27,240 --> 00:01:29,760
这个菜香油必须得加热
Sesame oil must be heated for this dish

37
00:01:29,760 --> 00:01:32,720
不加热它的香度太大
Otherwise it will be overly aromatic

38
00:01:32,720 --> 00:01:37,160
然后通过加热把一些浓度释放出来
So by heating it, we let the aroma evaporate for a bit

39
00:01:37,160 --> 00:01:39,400
先煸姜 先下姜
Put the Julienne ginger first

40
00:01:39,400 --> 00:01:42,960
姜丝 葱丝
Julienne ginger and Julienne spring onion

41
00:01:42,960 --> 00:01:45,600
这个菜的关键就是用香油煸
The key for this dish is to fry with sesame oil 

42
00:01:45,600 --> 00:01:49,880
辣椒丝 把它煸出香味来
Add Julienne dried chili and fry until aromatic

43
00:01:49,880 --> 00:01:53,720
咱们注意 这个辣椒别给它炒糊了
Be careful to not burn the chili

44
00:01:53,720 --> 00:01:57,360
油温别太高 搁进去以后一下糊了
Don’t bring the temperature too high, otherwise it will burn

45
00:01:57,360 --> 00:01:59,560
它影响后边的口感
It affects the taste 

46
00:01:59,560 --> 00:02:02,200
大爷你看没有香油味都没了
Da Ye, there’s no overt sesame oil aroma now

47
00:02:02,200 --> 00:02:04,320
全是辣椒和葱姜丝的味
It’s full of the aromas of chili, spring onion and ginger

48
00:02:04,320 --> 00:02:05,520
葱姜丝的香味出来了
The aromas of ginger and spring onion has been released

49
00:02:05,520 --> 00:02:08,680
咱们下边 米醋
Now, add rice vinegar

50
00:02:08,680 --> 00:02:13,680
北京的米醋 北京米醋有名
Beijing rice vinegar, it’s popular

51
00:02:13,680 --> 00:02:15,840
然后咱们光是米醋的味道不够
Just vinegar is not enough

52
00:02:15,840 --> 00:02:18,440
咱们再加点白醋
Let’s also add some white vinegar

53
00:02:18,440 --> 00:02:20,640

54
00:02:20,640 --> 00:02:22,960
加白醋的味道立马就窜出来了
The aroma is out once you add white vinegar

55
00:02:22,960 --> 00:02:25,680
你这糖也不少加啊
That’s quite a lot of sugar too

56
00:02:25,680 --> 00:02:30,880
有三百克差不多吧
About 300g

57
00:02:30,880 --> 00:02:32,560
就因为加了糖以后
Sugar gives 

58
00:02:32,560 --> 00:02:35,480
它这汁粘稠了而且有亮度
Consistency and brightness

59
00:02:35,480 --> 00:02:39,160
咱们这样太浓了这汁 咱再加点水
Now it’s too thick, let’s add some water

60
00:02:39,160 --> 00:02:42,400

61
00:02:42,400 --> 00:02:44,720
这能泡好多黄瓜啊
The sauce can be used for lots of cucumbers

62
00:02:44,720 --> 00:02:47,040
咱们这个汁一次调好了以后
Once the sauce is made 

63
00:02:47,040 --> 00:02:50,080
可以放在冰箱里 它也不坏
It can be kept in the fridge it doesn’t go bad

64
00:02:50,080 --> 00:02:52,760
加点盐
Add some salt

65
00:02:52,760 --> 00:02:54,960
来咱们点一点酱油
And soy sauce

66
00:02:54,960 --> 00:02:55,960

67
00:02:58,800 --> 00:03:01,600
实际上这是凉菜一个特殊的味道
This dish actually has a special taste

68
00:03:01,600 --> 00:03:02,840
一个味儿型
A taste type

69
00:03:02,840 --> 00:03:06,200
适合自己的才是好的味道
Whatever taste you like is the best

70
00:03:06,200 --> 00:03:09,040
咱们这边差不多了 晾凉
It’s dones let’s remove it from the wok and let it cool

71
00:03:09,040 --> 00:03:11,560

72
00:03:12,280 --> 00:03:14,720
咱们熬汁的时候速度要快
We need to move quickly when we make the sauce

73
00:03:14,720 --> 00:03:17,160
锅一开咱们就得给它盛出来
Remove it from the pot as soon as it boils

74
00:03:17,160 --> 00:03:20,160
要不然醋挥发的就跑了
Otherwise, the vinegar will get evaporated

75
00:03:20,160 --> 00:03:22,440
然后再搁冰箱里边腌制（镇凉）
Put the sauce in the fridge

76
00:03:22,440 --> 00:03:24,280
你看现在腌了多长时间了
Check how long it’s been (for the cucumber)

77
00:03:24,280 --> 00:03:26,200
有个半个小时
It’s been half an hour

78
00:03:26,200 --> 00:03:28,680
刚开始腌的时候是出汤
The moisture came out at first

79
00:03:28,680 --> 00:03:31,080
然后一刻钟时候我尝了是皮的
I tasted it at after 15 minutes, it’s soft

80
00:03:31,080 --> 00:03:33,520
现在你看时间到了是脆的
Now it’s crunchy

81
00:03:33,520 --> 00:03:35,440
您看着里面的水
Look at the liquid that came out

82
00:03:35,440 --> 00:03:38,160
咱把它给倒出去 篦出去
Discard it

83
00:03:38,160 --> 00:03:39,840
所以说它必须得腌够了时间
You must give it enough time

84
00:03:39,840 --> 00:03:41,040
把它澄干净
Drain it all out

85
00:03:41,040 --> 00:03:46,040
您看咱们这个汁也凉了 越凉越粘稠
The sauce has cooled down

86
00:03:46,040 --> 00:03:48,200
咱们把这个汁倒进去
Pour the sauce in the cucumber

87
00:03:48,200 --> 00:03:50,360
大爷你这要搁一宿
Da Ye, if you let it marinate overnight

88
00:03:50,360 --> 00:03:52,280
明天早上再吃才 那爽
And eat it tomorrow. It will be tastier.

89
00:03:52,280 --> 00:03:53,800
咱们把这拌一下
Let’s mix it

90
00:03:53,800 --> 00:03:55,640
明天早上一吃 脆爽脆爽的
Eat it tomorrow, it will be tasty and crunchy

91
00:03:55,640 --> 00:03:59,400
咱们这个再腌俩小时 俩小时以后 好
Let’s have it marinate for two more hours. After two hours

92
00:03:59,400 --> 00:04:01,640
放冰箱里头镇一下
Chill it in the fridge

93
00:04:01,640 --> 00:04:03,720
师伯咱么这个腌好了
It’s done Shi Bo

94
00:04:05,400 --> 00:04:06,920
您看这个黄瓜条
Look at the cucumber 

95
00:04:06,920 --> 00:04:11,960
皮儿朝上 而且瓜条宽窄长短都一样了
Face the skin-side up, keep them the same length

96
00:04:11,960 --> 00:04:14,360
这样摆出来就整齐好看
To make it look nicely

97
00:04:14,360 --> 00:04:16,320
行了差不多了
Almost done

98
00:04:16,320 --> 00:04:18,640
差不多了 然后咱们把这个料
Let’s add the condiments on top

99
00:04:18,680 --> 00:04:22,400
把料搁在上边 点缀
For decoration

100
00:04:22,400 --> 00:04:26,440
你看这没有过多的去修饰 简简单单
No extra decorations keep it simple

101
00:04:31,400 --> 00:04:34,240
四十年前的味道 一点都没走味儿
Taste like how it is 40 years ago, nothing has changed

102
00:04:34,240 --> 00:04:36,640
为什么老说这小菜很重要
Why do we always say that starters are important

103
00:04:36,640 --> 00:04:39,800
到一酒店吃饭 进门的菜是什么菜
Because they are the first dished you see

104
00:04:39,800 --> 00:04:41,800
不是热菜 是凉菜
Not mains but appetizers

105
00:04:41,800 --> 00:04:45,240
重要宴会其实都上过这道菜 很精品
This dish has been presented on important banquits, it’s very classical

106
00:04:45,240 --> 00:04:47,200
这个汁咱们还可以做
We can also use the sauce in making

107
00:04:47,200 --> 00:04:49,440
黄瓜皮 黄瓜卷 萝卜皮
Cucumber skin, shaved cucumber, radish skin

108
00:04:49,440 --> 00:04:51,440
油吃黄瓜 珊瑚白菜
Cucumber marinated in oil, Coral Napa Cabbage

109
00:04:51,440 --> 00:04:54,280
基本上和这个口味上差不多
Flavours are all similar

110
00:04:54,280 --> 00:00:02,000

**Comment by glasscatfish** [comment]
0:04:55.140,0:04:59.440
今天让我们来康康宝藏男孩郑秀生的日常
Today, let’s see Treasure Boy Zhe Xiu Sheng’s (Da ye) daily life

0:04:59.800,0:05:01.340
他喜欢唱歌
He likes singing

0:05:01.620,0:05:02.620


0:05:05.020,0:05:06.600


0:05:08.580,0:05:10.740
随时来两首小曲
He sings as he please

0:05:12.080,0:05:13.080


0:05:14.720,0:05:16.220
他用实力卖萌
He acts cute

0:05:16.220,0:05:17.600
  

0:05:17.600,0:05:19.500
实力模仿魏刚强
Imitate Wei Gang Qiang (Er Bai’s apprentice)

0:05:20.640,0:05:21.640
大爷
Da Ye

0:05:22.480,0:05:23.480
走了
Leaving

0:05:24.260,0:05:25.860
他博学多才
He is of great learning and great ability

0:05:25.860,0:05:27.120
你得有一个正能量
You must hold a positive attitude

0:05:27.240,0:05:28.580
要给这些孩子们
Tell theories

0:05:28.600,0:05:30.280
讲出些门门道道来
To the descendant

0:05:30.480,0:05:34.280
家有大厨 就是幸福
Happy life with a chef at home

0:05:34.520,0:05:36.340
这样的大爷你爱了吗 
Do you like Da Ye like this?

0:05:37.600,0:05:41.100
今天我们来盘点一下颜值担当孙立新 
Let’s now talk about handsom Sun Li Xin (Er Bai)

0:05:42.120,0:05:43.540
他沉迷诗歌
He loves poetry

0:05:43.540,0:05:47.060
爹娘深深的系着我的爱恋


0:05:47.720,0:05:50.120
期待着如期般的守望

0:05:50.840,0:05:51.980
他金句频频
He tells verse

0:05:52.540,0:05:54.600
演绎着人间的温暖
Interpreting the warmth of the world

0:05:54.600,0:05:57.560
靠我们厨师去温暖这个世界
Let us, chefs to warm the world

0:05:58.140,0:05:59.220
他多才多艺
He is versatil

0:05:59.520,0:06:01.020
我还学过织毛衣呢
I’ve learned knitting

0:06:01.700,0:06:02.680
你以为呢
What do you think?

0:06:03.000,0:06:05.020
无情铁手剥花生
Peeling peanuts

0:06:06.180,0:06:09.100
最后我们康康别人眼中的他
Finally, let’s see other people’s perspectives of him

0:06:09.920,0:06:12.720
孙老师啊是我们烹饪界的美男子
Sun is the handsome man in culinary industry

0:06:13.000,0:06:15.600
烹饪界的中医大夫
The Chinese doctor in culinary industry

0:06:15.760,0:06:18.680
烹饪界的理论家和哲学家
The theorist and philosopher in culinary industry

0:06:18.680,0:06:20.680
这样的二伯您喜欢吗
Do you like Er Bai like this?

**Comment by glasscatfish** [comment]
看过了 修改没有问题
