### ISSUE TITLE
[雪鱼] 宁夏羊杂 - https://youtu.be/FwsFGrOkBmI

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#1329]
**视频链接**：<https://youtu.be/FwsFGrOkBmI>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
宁夏最特别的羊杂，羊肺里灌面浆，面浆还有讲究，加羊油辣子香得很！

简介
吃遍了各个地方的羊杂后，大家都说宁夏吴忠的羊杂最特色，于是乎今天就来到了这里。一路从甘肃过来的时候，路上的风景也是美妙绝伦，广袤无际的大西北有种神秘的色彩，忽而蓝天白云，忽而乌云骤雨，忽而漫山遍野的西瓜地，忽而一片荒野。经历5个小时的车程到达吴忠，黄河从这里经过，拐了一个大弯，从空中俯瞰，那曲段分外妖娆，奈何无人机飞的太低，没有拍摄到全貌。顺着黄河一路向北，尽是繁茂之景。书里说这儿的滩羊最肥美，这里的人最会吃羊肉，可以从头吃到脚，从里吃到外，连一碗羊杂都特讲究。羊肺要先灌入面浆，这面浆也有讲究，必须洗掉面筋才行，灌了面筋的羊肺叫做面肺，面肺和羊心肝肚头一起烩一锅，加上羊油辣子，一碗20元那叫一个过瘾，最主要的是这儿的羊杂是早餐就吃的，吃一碗羊杂，喝一杯八宝茶，吴忠人的一天就开始了。

字幕
1
00:00:02,000 --> 00:00:04,300
宁夏 吴忠

2
00:00:15,625 --> 00:00:18,275
雪鱼现在在黄河流域的宁夏吴忠

3
00:00:18,575 --> 00:00:20,350
这边的人真的是很会吃羊肉

4
00:00:20,550 --> 00:00:23,075
他们对羊肉的吃法是从头吃到脚

5
00:00:23,150 --> 00:00:24,875
从里吃到外啊

6
00:00:25,300 --> 00:00:27,675
光是羊杂他们就有很多的讲究

7
00:00:27,925 --> 00:00:29,875
走 去看一看

8
00:00:35,175 --> 00:00:37,350
排队也费劲啊

9
00:00:47,925 --> 00:00:50,250
你好 后面的几位

10
00:00:50,375 --> 00:00:51,725
我要一份带走的

11
00:00:51,875 --> 00:00:53,525
好的

12
00:00:53,725 --> 00:00:58,250
怎么说呢 大家会说来这个羊杂店会看到羊杂西施

13
00:00:58,750 --> 00:01:01,700
真的是看了很多的什么什么西施 如油条西施 奶茶西施

14
00:01:01,700 --> 00:01:04,350
这家的西施绝对的名不虚传

15
00:01:05,475 --> 00:01:07,525
啊 我的八宝茶上来了

16
00:01:08,900 --> 00:01:10,375
它是宁夏的特色

17
00:01:10,500 --> 00:01:12,500
几乎每次吃饭都会点的

18
00:01:15,175 --> 00:01:22,775
这里面是茶叶 冰糖 枸杞 沙枣 核桃 还有桂圆 芝麻 玫瑰花

19
00:01:24,975 --> 00:01:26,700
这里面是额外加的白糖吗

20
00:01:26,775 --> 00:01:28,325
是的 白砂糖

21
00:01:30,975 --> 00:01:34,975
相机上的她真的是不上镜 现场看她

22
00:01:34,975 --> 00:01:38,300
我都感觉我看直了眼

23
00:01:38,450 --> 00:01:41,150
美的东西嘛 不管男的女的都喜欢看

24
00:01:44,575 --> 00:01:47,625
喝茶的功夫 羊杂就已经开始制作了

25
00:01:48,225 --> 00:01:50,125
现在这边在清洗羊肺

26
00:01:50,375 --> 00:01:52,150
羊肺原来是血红色

27
00:01:52,350 --> 00:01:55,775
需要用水不断地冲洗 冲到变成白色

28
00:01:55,900 --> 00:01:59,300
现在羊肺就像一个吹了气的鹅一样

29
00:01:59,575 --> 00:02:01,800
变得白白胖胖的

30
00:02:04,350 --> 00:02:06,000
（洗掉面筋的面浆）

31
00:02:07,325 --> 00:02:09,025
（这是面筋）

32
00:02:13,175 --> 00:02:15,650
现在是准备开始灌羊肺

33
00:02:22,475 --> 00:02:25,175
把面浆灌进去 水会渗出来一部分

34
00:02:25,500 --> 00:02:27,975
这个肺啊 已经越来越大了

35
00:02:29,925 --> 00:02:32,525
（蒸熟 放凉）

36
00:02:41,425 --> 00:02:42,525
（羊头肉）

37
00:02:45,750 --> 00:02:46,800
（羊肝）

38
00:02:53,075 --> 00:02:54,725
（羊肚）

39
00:02:57,375 --> 00:02:58,875
（羊心）

40
00:03:04,525 --> 00:03:08,950
切好的羊杂会和盐 辣子等一起放在羊肉汤里烩一下

41
00:03:21,800 --> 00:03:23,500
（蒜末）

42
00:04:04,000 --> 00:04:06,325
哇 谢谢

43
00:04:08,900 --> 00:04:11,850
这个羊杂看起来就是红油辣子很浓郁

44
00:04:12,800 --> 00:04:15,775
不吃它就这么闻着就觉得很香啊

45
00:04:17,600 --> 00:04:19,775
看上去很大的量啊 20元一碗

46
00:04:20,950 --> 00:04:24,575
热气腾腾的一碗 浓郁飘香

47
00:04:24,750 --> 00:04:26,400
这满满的一桌都是我的

48
00:04:26,775 --> 00:04:31,450
分别是羊杂 八宝茶 还有晒的茄干 凉粉

49
00:04:32,550 --> 00:04:34,150
这顿饭很丰盛啊

50
00:04:34,150 --> 00:04:37,527
我们看看这碗羊杂里有什么东西吧

51
00:04:37,600 --> 00:04:40,175
能够明显看到的就是羊肚

52
00:04:40,925 --> 00:04:43,175
这个就是传说中的面肺了吧

53
00:04:43,875 --> 00:04:46,150
除了面肺 羊肚

54
00:04:46,325 --> 00:04:52,650
还有羊头肉 简单来说就说心肝肚肺头

55
00:04:52,800 --> 00:04:55,150
不多说了 赶快来尝一尝吧

56
00:04:55,925 --> 00:05:01,375
这个羊杂浸入到辣子中真是香味扑鼻啊

57
00:05:04,900 --> 00:05:06,600
（羊肝绵密）

58
00:05:08,350 --> 00:05:12,575
这个辣子应该是羊油辣子 吃起来特别的香

59
00:05:13,375 --> 00:05:15,700
该吃一个面肺了

60
00:05:17,025 --> 00:05:22,825
毕竟面肺是吴忠羊杂和其他地方的羊杂之间的一个很重要的区别

61
00:05:28,775 --> 00:05:31,475
这个面肺好神奇的口感啊

62
00:05:33,600 --> 00:05:38,900
有点弹口 又有点像土豆泥这样的棉的口感

63
00:05:41,300 --> 00:05:43,450
吃起来特别爽滑

64
00:05:54,600 --> 00:06:00,050
我觉得吴忠人对羊杂的吃法有点超乎我的想象 

65
00:06:00,150 --> 00:06:05,375
我根本想象不到 他们对羊肺还有自己独特的吃法

66
00:06:05,625 --> 00:06:09,400
就是要把面灌入肺中 和羊杂搭配一起吃

67
00:06:09,900 --> 00:06:13,075
在做面肺前，一定要把面筋去掉 只灌入面浆

68
00:06:13,350 --> 00:06:16,550
如果说有面浆的话 可能会灌不进去 可能会堵塞

69
00:06:16,875 --> 00:06:21,100
这么做出来的面肺真的是口感特别的润滑

70
00:06:24,200 --> 00:06:26,525
这边的羊肉羊杂吃起来一点都不膻

71
00:06:27,250 --> 00:06:32,200
有了这个面肺后 才觉得这碗羊杂是真正完美的

72
00:06:38,500 --> 00:06:40,700
我觉得这碗羊杂就是一碗饭

73
00:06:40,850 --> 00:06:43,025
如果你觉得吃不饱的话

74
00:06:43,075 --> 00:06:47,725
一个是吃这种白饼

75
00:06:47,950 --> 00:06:50,950
另一个就是配这边的饸饹面

76
00:06:51,225 --> 00:06:56,250
两种都能顶饱

77
00:06:57,400 --> 00:07:02,450
吃羊杂的过程中 来一碗八宝茶 解腻又解辣

78
00:08:00,950 --> 00:08:03,650
  告别了小姐姐  我们今天的视频就到这儿

79
00:08:04,050 --> 00:08:06,925
如果说 你觉得我的视频能够给你带来一些欢乐的话

80
00:08:07,125 --> 00:08:09,575
记得关注哦 拜拜


```

**Comment by zliu185** [comment]
认领

**Comment by zliu185** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
宁夏最特别的羊杂，羊肺里灌面浆，面浆还有讲究，加羊油辣子香得很！
The most special Yangzatang(mutton’s pluck soup) in Ningxia, made with specific flour water, so tangy with mutton tallow and chili.


简介
吃遍了各个地方的羊杂后，大家都说宁夏吴忠的羊杂最特色，于是乎今天就来到了这里。一路从甘肃过来的时候，路上的风景也是美妙绝伦，广袤无际的大西北有种神秘的色彩，忽而蓝天白云，忽而乌云骤雨，忽而漫山遍野的西瓜地，忽而一片荒野。经历5个小时的车程到达吴忠，黄河从这里经过，拐了一个大弯，从空中俯瞰，那曲段分外妖娆，奈何无人机飞的太低，没有拍摄到全貌。顺着黄河一路向北，尽是繁茂之景。书里说这儿的滩羊最肥美，这里的人最会吃羊肉，可以从头吃到脚，从里吃到外，连一碗羊杂都特讲究。羊肺要先灌入面浆，这面浆也有讲究，必须洗掉面筋才行，灌了面筋的羊肺叫做面肺，面肺和羊心肝肚头一起烩一锅，加上羊油辣子，一碗20元那叫一个过瘾，最主要的是这儿的羊杂是早餐就吃的，吃一碗羊杂，喝一杯八宝茶，吴忠人的一天就开始了。
After tasting various mutton’s pluck soup over China, people say the most special mutton’s pluck soup is in Wuzhong, Ningxia, that is why we here. Travel from Gansu, the vast expanse of Northwest China has a mysterious style, sometimes blue sky along with white clouds, sometimes rain follows dark cloud, sometimes great watermelon fields showed, sometimes a wilderness. Gansu to Wuzhong took 5 hours of driving, the Yellow River from here through a big bend, from the air, the Yellow River extraordinarily enchanting, the only pity was the drone flew too low to take the full picture of the Yellow River. Follow the Yellow River all the way to the north, all the luxuriant scenery! Some books indicate Wuzhong has the most tender Tan mutton meat, and the people here are the best eaters of lamb, eating it from head to toe, inside and out, even a bowl of mutton’s pluck soup is exquisite. Before steam, starch water will pump into the mutton’s lung. The starch water is made by mixing water and flour then wash out gluten. Steamed mutton lung after pumping starch water called “flour lung”. The mutton’s pluck soup made by stewing the “flour lung”, with mutton’s heart, liver, and tripe, seasoning by mutton tallow and chili. Each mutton’s pluck soup cost 20 yuan (about 3 dollars). The moment of satisfying showed after the first tasting. In Wuzhong, people’s daily start with the mutton’s pluck soup with a cup of Babao Tea (a traditional assorted herbal tea).


字幕
1
00:00:02,000 --> 00:00:04,300
宁夏 吴忠
Ningxia Wuzhong
2
00:00:15,625 --> 00:00:18,275
雪鱼现在在黄河流域的宁夏吴忠
Xueyu currently in Wuzhong, Ningxia, in the Yellow River valley

3
00:00:18,575 --> 00:00:20,350
这边的人真的是很会吃羊肉
The people here are really good at cook mutton

4
00:00:20,550 --> 00:00:23,075
他们对羊肉的吃法是从头吃到脚
They eat lamb from head to toe.


5
00:00:23,150 --> 00:00:24,875
从里吃到外啊
From inside to outside

6
00:00:25,300 --> 00:00:27,675
光是羊杂他们就有很多的讲究
even a bowl of mutton’s pluck soup is exquisite

7
00:00:27,925 --> 00:00:29,875
走 去看一看
Follow me, let’s take a look

8
00:00:35,175 --> 00:00:37,350
排队也费劲啊
The queue is so long

9
00:00:47,925 --> 00:00:50,250
你好 后面的几位
Welcome, next please  

10
00:00:50,375 --> 00:00:51,725
我要一份带走的
I want a takeout

11
00:00:51,875 --> 00:00:53,525
好的
Sure

12
00:00:53,725 --> 00:00:58,250
怎么说呢 大家会说来这个羊杂店会看到羊杂西施
Em, people said we can find “mutton’s pluck beauty” at this restaurant 

13
00:00:58,750 --> 00:01:01,700
真的是看了很多的什么什么西施 如油条西施 奶茶西施
We see many beauties during our journey such as “youtiao (deep-fried dough strips) beauty” or “boba tea beauty”

14
00:01:01,700 --> 00:01:04,350
这家的西施绝对的名不虚传
The “mutton’s pluck beauty” is absolutely worthy of fame

15
00:01:05,475 --> 00:01:07,525
啊 我的八宝茶上来了
Ah, my Babao Tea(traditional assorted herbal tea) is ready
16
00:01:08,900 --> 00:01:10,375
它是宁夏的特色
This is the local special of Ningxia.

17
00:01:10,500 --> 00:01:12,500
几乎每次吃饭都会点的
Its served almost every dinner

18
00:01:15,175 --> 00:01:22,775
这里面是茶叶 冰糖 枸杞 沙枣 核桃 还有桂圆 芝麻 玫瑰花
The Babao tea made with tea leaf, rock sugar, medlar, sand dates, walnuts, and longan, sesame, roses

19
00:01:24,975 --> 00:01:26,700
这里面是额外加的白糖吗
Is mine served with extra sugar?

20
00:01:26,775 --> 00:01:28,325
是的 白砂糖
Yes, we add some granulated sugar.

21
00:01:30,975 --> 00:01:34,975
相机上的她真的是不上镜 现场看她
She is much more pretty than I recorded. When I look at her

22
00:01:34,975 --> 00:01:38,300
我都感觉我看直了眼
I feel like… I can hardly move my eyes.

23
00:01:38,450 --> 00:01:41,150
美的东西嘛 不管男的女的都喜欢看
You know, both male and female love beauty.

24
00:01:44,575 --> 00:01:47,625
喝茶的功夫 羊杂就已经开始制作了
While I’m having my tea, they start making my mutton’s pluck soup.

25
00:01:48,225 --> 00:01:50,125
现在这边在清洗羊肺
Now they are dressing the mutton’s lung.

26
00:01:50,375 --> 00:01:52,150
羊肺原来是血红色
The mutton’s lung is blood-red at the beginning.

27
00:01:52,350 --> 00:01:55,775
需要用水不断地冲洗 冲到变成白色
It needs to be rinsed with water constantly until it turns white.

28
00:01:55,900 --> 00:01:59,300
现在羊肺就像一个吹了气的鹅一样
Now the mutton's lung is like a blown goose.

29
00:01:59,575 --> 00:02:01,800
变得白白胖胖的
Turn into fat in vain.

30
00:02:04,350 --> 00:02:06,000
（洗掉面筋的面浆）
(Starch water without gluten)

31
00:02:07,325 --> 00:02:09,025
（这是面筋）
(This is gluten)

32
00:02:13,175 --> 00:02:15,650
现在是准备开始灌羊肺
Now it's time to pump starch water into mutton's lung.

33
00:02:22,475 --> 00:02:25,175
把面浆灌进去 水会渗出来一部分
Some water will penetrate through the lung when pumping starch water inside.

34
00:02:25,500 --> 00:02:27,975
这个肺啊 已经越来越大了
This lung is getting bigger.

35
00:02:29,925 --> 00:02:32,525
（蒸熟 放凉）
(Steam and let it cool)

36
00:02:41,425 --> 00:02:42,525
（羊头肉）
(Mutton head meat)

37
00:02:45,750 --> 00:02:46,800
（羊肝）
(Mutton liver)

38
00:02:53,075 --> 00:02:54,725
（羊肚）
(Mutton tripe)

39
00:02:57,375 --> 00:02:58,875
（羊心）
(Mutton heart)


40
00:03:04,525 --> 00:03:08,950
切好的羊杂会和盐 辣子等一起放在羊肉汤里烩一下
Chopped pluck will be stewing with salt and chili in the mutton soup.


41
00:03:21,800 --> 00:03:23,500
（蒜末）
(minced garlic)

42
00:04:04,000 --> 00:04:06,325
哇 谢谢
Wow thank you

43
00:04:08,900 --> 00:04:11,850
这个羊杂看起来就是红油辣子很浓郁
The mutton’s pluck soup looks tangy with red chili oil.

44
00:04:12,800 --> 00:04:15,775
不吃它就这么闻着就觉得很香啊
Smells appetizing even before tasting.

45
00:04:17,600 --> 00:04:19,775
看上去很大的量啊 20元一碗
20 yuan for each seems a lot.

46
00:04:20,950 --> 00:04:24,575
热气腾腾的一碗 浓郁飘香
The hot pluck soup steaming fragrance.

47
00:04:24,750 --> 00:04:26,400
这满满的一桌都是我的
It’s all mine.

48
00:04:26,775 --> 00:04:31,450
分别是羊杂 八宝茶 还有晒的茄干 凉粉
Those are the mutton’s pluck soup, the Babao tea, the dehydrated eggplant, and the bean jelly.

49
00:04:32,550 --> 00:04:34,150
这顿饭很丰盛啊
That was a big meal.

50
00:04:34,150 --> 00:04:37,527
我们看看这碗羊杂里有什么东西吧
Let us see what inside this pluck soup.

51
00:04:37,600 --> 00:04:40,175
能够明显看到的就是羊肚
We can obviously find mutton’s tripe.

52
00:04:40,925 --> 00:04:43,175
这个就是传说中的面肺了吧
This is the legendary “flour lung”.

53
00:04:43,875 --> 00:04:46,150
除了面肺 羊肚
Besides flour lung, mutton’s tripe.

54
00:04:46,325 --> 00:04:52,650
还有羊头肉 简单来说就说心肝肚肺头
We also have the muttonhead meat. Simply said, we have mutton’s heart, liver, lung, and tripe.

55
00:04:52,800 --> 00:04:55,150
不多说了 赶快来尝一尝吧
Without further ado, let's have a bite.

56
00:04:55,925 --> 00:05:01,375
这个羊杂浸入到辣子中真是香味扑鼻啊
The mutton’s pluck soaked in chili powder really smells delicious

57
00:05:04,900 --> 00:05:06,600
（羊肝绵密）
Mutton’s liver taste thick.

58
00:05:08,350 --> 00:05:12,575
这个辣子应该是羊油辣子 吃起来特别的香
The red chili oil must make with mutton tallow, delicious 

59
00:05:13,375 --> 00:05:15,700
该吃一个面肺了
Time to eat “flour lung”

60
00:05:17,025 --> 00:05:22,825
毕竟面肺是吴忠羊杂和其他地方的羊杂之间的一个很重要的区别
After all, one of the major differences between Wuzhong’s mutton pluck and others is they use the “flour lung”.


61
00:05:28,775 --> 00:05:31,475
这个面肺好神奇的口感啊
This flour lung has interesting texture!

62
00:05:33,600 --> 00:05:38,900
有点弹口 又有点像土豆泥这样的棉的口感
A bit chewy, but also have a bit soft texture like mush potato.

63
00:05:41,300 --> 00:05:43,450
吃起来特别爽滑
It tastes very smooth

64
00:05:54,600 --> 00:06:00,050
我觉得吴忠人对羊杂的吃法有点超乎我的想象 
I think the way Wuzhong people cook mutton’s pluck is a bit beyond my imagination

65
00:06:00,150 --> 00:06:05,375
我根本想象不到 他们对羊肺还有自己独特的吃法
I can’t imagine they have their unique cook style.

66
00:06:05,625 --> 00:06:09,400
就是要把面灌入肺中 和羊杂搭配一起吃
Which pump starch water into the lung and stew with mutton’s pluck.

67
00:06:09,900 --> 00:06:13,075
在做面肺前，一定要把面筋去掉 只灌入面浆
Before pumping “flour water” into the lung, make sure get rid of the gluten and just put in the starch water

68
00:06:13,350 --> 00:06:16,550
如果说有面浆的话 可能会灌不进去 可能会堵塞
Otherwise, the gluten will block the water into the lung.

69
00:06:16,875 --> 00:06:21,100
这么做出来的面肺真的是口感特别的润滑
The “flour lung” they made have really smooth taste.

70
00:06:24,200 --> 00:06:26,525
这边的羊肉羊杂吃起来一点都不膻
The smell of mutton is completely eliminated from their mutton meat and mutton pluck.

71
00:06:27,250 --> 00:06:32,200
有了这个面肺后 才觉得这碗羊杂是真正完美的
This mutton’s pluck soup is perfect with the “flour lung”.

72
00:06:38,500 --> 00:06:40,700
我觉得这碗羊杂就是一碗饭
I feel like the bowl itself can serve as a staple food.

73
00:06:40,850 --> 00:06:43,025
如果你觉得吃不饱的话
If you still not full fill

74
00:06:43,075 --> 00:06:47,725
一个是吃这种白饼
You can either have this white cookie.

75
00:06:47,950 --> 00:06:50,950
另一个就是配这边的饸饹面
Or have their Hele Noodle.

76
00:06:51,225 --> 00:06:56,250
两种都能顶饱
Both can fill your stomach.

77
00:06:57,400 --> 00:07:02,450
吃羊杂的过程中 来一碗八宝茶 解腻又解辣
Babao tea can fresh your mouth and reduce the heat of the chili.

78
00:08:00,950 --> 00:08:03,650
告别了小姐姐  我们今天的视频就到这儿
Say goodbye to pluck beauty and that's the end of today's video

79
00:08:04,050 --> 00:08:06,925
如果说 你觉得我的视频能够给你带来一些欢乐的话
If you enjoy our video.

80
00:08:07,125 --> 00:08:09,575
记得关注哦 拜拜
Remember to subscribe, thanks for watching.
