### ISSUE TITLE
【美食作家王刚】搬石磨回老家 - https://youtu.be/95qZYw8svkw

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1330]
**视频链接**：https://youtu.be/95qZYw8svkw

视频时长3:28，预计发布时间为北京时间7月31日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
把400多斤的石磨搬回老家，让四伯也吃上考验传统手艺的美食
Chef Wang decided to move the 200kg stone mill back to home, let his family also can enjoy the traditional delicacy

简介
大家好，这几天一直忙着拍一期最全面最硬核的家乡美食“富顺豆花”。花了很多时间和精力，所以更新不勤请大家见谅。视频已经拍好还在后期，效果非常不错所以就决定把石磨搬回老家来给家人做最新鲜的豆花。
Hello everyone, these past few days have been busy making the most comprehensive and hardcore hometown food "Fushun Douhua(Fushun soy curd flower)". I spent a lot of time and energy in it, so the video update not as often as used to be, please forgive me. The video has been shot well and in the post production, the finished result is so good, so I decided to move the stone mill back home to make the freshest soy flowers for my family.

字幕
0:00:00.401,0:00:01.095
哈喽 大家好

0:00:01.320,0:00:03.579
最近我们这个豆花已经拍完了

0:00:03.912,0:00:07.186
这一期是拍的时间最长的 已经拍了个多星期了

0:00:07.186,0:00:09.387
今天我跟我老爸来把这个石磨

0:00:09.387,0:00:12.647
拿到老家去推一点豆花吃一下

0:00:12.647,0:00:16.215
还有我们一个同事过来帮忙抬

0:00:16.215,0:00:18.477
那个石磨比较重 有几百斤

0:00:18.477,0:00:21.369
三四百斤吧 一起抬比较轻松一点

0:00:21.369,0:00:25.804
正好把车开过来一起拉上去 走嘛

0:00:27.637,0:00:30.347
这个起码都有八九十斤的样子

0:00:30.660,0:00:32.430
这个要3个人一起抬

0:00:37.155,0:00:39.571
2个人都抬得起

0:00:43.852,0:00:44.978
小心手

0:00:48.129,0:00:52.497
这个磨盘下面这坨特别重 下面这个估计有300斤

0:00:52.698,0:00:53.729
那个一百斤

0:00:53.930,0:00:55.475
那个也差不多一百斤

0:00:56.058,0:00:59.014
下面这个2个人也抬得动 但是有点费力

0:00:59.373,0:01:00.852
 3个人抬很轻松

0:01:02.709,0:01:03.628
好

0:01:12.295,0:01:13.975
你看嘛 它还要滚

0:01:16.054,0:01:16.669
好

0:01:21.679,0:01:23.449
干这个活没有点蛮力不行

0:01:24.183,0:01:29.441
反正干厨师也要能文能武

0:01:29.441,0:01:30.041
对吧

0:01:30.839,0:01:32.026
这个要不要的

0:01:32.049,0:01:34.401
这个要 这个是垫豆花的

0:01:35.655,0:01:36.662
还差啥子

0:01:36.752,0:01:37.463
帕子

0:01:37.774,0:01:39.966
还有锅 那个纱布

0:01:41.251,0:01:41.747
锅儿安

0:01:44.418,0:01:48.030
你看这个锅这个铁锅啊 特别秀气啊

0:01:48.551,0:01:50.457
如果不放油这样子的话

0:01:51.544,0:01:53.930
两三个小时就会生很多锈

0:01:54.632,0:01:56.094
我现在放了一些油在里面

0:01:56.320,0:01:58.470
放个几年都不会生锈 

0:01:58.470,0:02:02.012
这个就是有保养跟没保养区别就在这里

0:02:02.605,0:02:04.534
一点油其实不值什么钱

0:02:09.436,0:02:12.781
好啦 现在我要开始出发了

0:02:14.078,0:02:15.102
回老家

0:02:21.160,0:02:22.252
放在这上面

0:02:24.675,0:02:25.563
小心手哦

0:02:29.027,0:02:29.565
好

0:02:30.003,0:02:33.208
这边用泡沫垫哈 这个才往那边流得下去

0:02:35.051,0:02:35.781
噶 四伯爷

0:02:35.817,0:02:36.164
对对对

0:02:36.209,0:02:37.047
这边还要矮点

0:02:37.047,0:02:38.787
整点水来试哈就晓得了撒

0:02:39.097,0:02:40.182
不用试得那边都高了

0:02:40.501,0:02:41.385
不得高那边

0:02:45.849,0:02:46.652
这哈往那边放

0:02:47.254,0:02:49.058
 那个碓窝在哪儿买的哦

0:02:49.348,0:02:50.359
是借的啊

0:02:50.469,0:02:50.924
嗯

0:02:53.778,0:02:57.411
这个要一个人搬 这个两个人搬反而不好搬

0:02:59.707,0:03:00.459
放在这上面撒

0:03:00.615,0:03:01.784
这上面的一坨120斤

0:03:02.494,0:03:03.048
称过的啊

0:03:03.444,0:03:03.841
嗯

0:03:04.979,0:03:06.431
要轻放这磨盘

0:03:08.444,0:03:09.958
 我们那个安哪儿

0:03:10.114,0:03:10.699
那不是啊

0:03:10.699,0:03:12.004
放这个要有技巧

0:03:13.225,0:03:15.375
不要在上面磨过去磨过来的 

0:03:15.375,0:03:16.659
磨的话把那个齿齿（磨掉）

0:03:16.983,0:03:18.152
那肯定撒

0:03:18.590,0:03:21.408
好可以了 终于现在放下来了

0:03:21.931,0:03:23.141
好 本期视频就到这里

0:03:23.141,0:03:25.010
下次推豆花吃

0:03:25.720,0:03:26.419
拜拜


0:00:00.401,0:00:01.095
Hello, everybody.

0:00:01.320,0:00:03.579
We've recently finished shooting the Soy Curd Flower video.

0:00:03.912,0:00:07.186
This one's the longest one. We've been shooting for over a week.

0:00:07.186,0:00:09.387
Today, my dad and I are going to move the stone mill to...

0:00:09.387,0:00:12.647
our countryside home, and make some authentic soy curd flower .

0:00:12.647,0:00:16.215
And one of our colleagues came to help carry it.

0:00:16.215,0:00:18.477
That stone mill is so heavy. It weighs several hundred jin.

0:00:18.477,0:00:21.369
Three or four hundred jin (150-200kg). It's easier to move with others.

0:00:21.369,0:00:25.804
bring the car to the door and pull it up. Let's go.

0:00:27.637,0:00:30.347
This one weighs at least 80 to 90 jin.

0:00:30.660,0:00:32.430
It takes three men to carry this.

0:00:37.155,0:00:39.571
Two people can lift it.

0:00:43.852,0:00:44.978
Watch your hands.

0:00:48.129,0:00:52.497
This pile underneath the mill is very heavy, probably weighs about 300 jin.

0:00:52.698,0:00:53.729
That one is about 100 jin.

0:00:53.930,0:00:55.475
That one is also around 100 jin.

0:00:56.058,0:00:59.014
This one can be lifted by two men, but it's a bit hard to move.

0:00:59.373,0:01:00.852
 It's easy for three people to carry.

0:01:02.709,0:01:03.628
good

0:01:12.295,0:01:13.975
See? It will roll.

0:01:16.054,0:01:16.669
good

0:01:21.679,0:01:23.449
You can't do this job without some brute strength.

0:01:24.183,0:01:29.441
In order to be a good cook, you need to be a good fighter anyway.

0:01:29.441,0:01:30.041
right?

0:01:30.839,0:01:32.026
Do we need this one?

0:01:32.049,0:01:34.401
Yes, this one is also for making the soy cured flower.

0:01:35.655,0:01:36.662
What's missing?

0:01:36.752,0:01:37.463
filter mesh

0:01:37.774,0:01:39.966
Oh, the pot, and the filter mesh

0:01:41.251,0:01:41.747
big pot

0:01:44.418,0:01:48.030
Look at this iron wok. It's so beautiful.

0:01:48.551,0:01:50.457
If you don't put oil in it,

0:01:51.544,0:01:53.930
in two or three hours, there'll be a lot of rust.

0:01:54.632,0:01:56.094
I've put some oil in it now.

0:01:56.320,0:01:58.470
It won't rust for years. 

0:01:58.470,0:02:02.012
That's the difference between maintenance and no maintenance.

0:02:02.605,0:02:04.534
A little oil isn't really expensive.

0:02:09.436,0:02:12.781
All right, now I'm off.

0:02:14.078,0:02:15.102
back to our countryside home

0:02:21.160,0:02:22.252
Put it on here.

0:02:24.675,0:02:25.563
Watch your hands.

0:02:29.027,0:02:29.565
good

0:02:30.003,0:02:33.208
Use a foam pad here, the juice flows that way by a slope.

0:02:35.051,0:02:35.781
Right? Uncle Si.

0:02:35.817,0:02:36.164
Yes, yes, yes.

0:02:36.209,0:02:37.047
It need to be shorter here.

0:02:37.047,0:02:38.787
We'll see if we can get some water to test it.

0:02:39.097,0:02:40.182
You don't have to try. It's too high over there.

0:02:40.501,0:02:41.385
I don't think so.

0:02:45.849,0:02:46.652
Put this over here.

0:02:47.254,0:02:49.058
 Where did you get that quern-stone?

0:02:49.348,0:02:50.359
I borrowed it.

0:02:50.469,0:02:50.924
Hmm.

0:02:53.778,0:02:57.411
This one has to be moved by one person, it's harder by two.

0:02:59.707,0:03:00.459
Put it on here.

0:03:00.615,0:03:01.784
This one weighs 120 jin (60kg).

0:03:02.494,0:03:03.048
Weighed?

0:03:03.444,0:03:03.841
Yes

0:03:04.979,0:03:06.431
You have to be gentle with the grindstone.

0:03:08.444,0:03:09.958
 Where should we put it?

0:03:10.114,0:03:10.699
Yes

0:03:10.699,0:03:12.004
It takes skill to place this.

0:03:13.225,0:03:15.375
Don't rub it over the stone. 

0:03:15.375,0:03:16.659
If you rub it, the tooth will grind off.

0:03:16.983,0:03:18.152
That's for sure.

0:03:18.590,0:03:21.408
Okay, that's good. We finally moving them back to our house.

0:03:21.931,0:03:23.141
Okay, that's it for this video.

0:03:23.141,0:03:25.010
Next time we'll use this to make soy beans flower.

0:03:25.720,0:03:26.419
bye-bye


```

**Comment by immoonancient** [comment]
bot, please upload on behalf of the assignee

标题（翻译主要意思即可，不要超过 100 个字符）
把400多斤的石磨搬回老家，让四伯也吃上考验传统手艺的美食
Chef Wang decided to move the 200kg stone mill back to home, let his family also can enjoy the traditional delicacy

简介
大家好，这几天一直忙着拍一期最全面最硬核的家乡美食“富顺豆花”。花了很多时间和精力，所以更新不勤请大家见谅。视频已经拍好还在后期，效果非常不错所以就决定把石磨搬回老家来给家人做最新鲜的豆花。
Hello everyone, these past few days have been busy making the most comprehensive and hardcore hometown food "Fushun Douhua(Fushun soy curd flower)". I spent a lot of time and energy in it, so the video update not as often as used to be, please forgive me. The video has been shot well and in the post production, the finished result is so good, so I decided to move the stone mill back home to make the freshest soy flowers for my family.

字幕

0:00:00.401,0:00:01.095
哈喽 大家好
Hello, everybody.
0:00:01.320,0:00:03.579
最近我们这个豆花已经拍完了
We've recently finished shooting the Soy Curd Flower video.
0:00:03.912,0:00:07.186
这一期是拍的时间最长的 已经拍了个多星期了
This one's the longest one. We've been shooting for over a week.
0:00:07.186,0:00:09.387
今天我跟我老爸来把这个石磨
Today, my dad and I are going to move the stone mill to...
0:00:09.387,0:00:12.647
拿到老家去推一点豆花吃一下
our countryside home, and make some authentic soy curd flower .
0:00:12.647,0:00:16.215
还有我们一个同事过来帮忙抬
And one of our colleagues came to help carry it.
0:00:16.215,0:00:18.477
那个石磨比较重 有几百斤
That stone mill is so heavy. It weighs several hundred jin.
0:00:18.477,0:00:21.369
三四百斤吧 一起抬比较轻松一点
Three or four hundred jin (150-200kg). It's easier to move with others.
0:00:21.369,0:00:25.804
正好把车开过来一起拉上去 走嘛
bring the car to the door and pull it up. Let's go.
0:00:27.637,0:00:30.347
这个起码都有八九十斤的样子
This one weighs at least 80 to 90 jin.
0:00:30.660,0:00:32.430
这个要3个人一起抬
It takes three men to carry this.
0:00:37.155,0:00:39.571
2个人都抬得起
Two people can lift it.
0:00:43.852,0:00:44.978
小心手
Watch your hands.
0:00:48.129,0:00:52.497
这个磨盘下面这坨特别重 下面这个估计有300斤
This pile underneath the mill is very heavy, probably weighs about 300 jin.
0:00:52.698,0:00:53.729
那个一百斤
That one is about 100 jin.
0:00:53.930,0:00:55.475
那个也差不多一百斤
That one is also around 100 jin.
0:00:56.058,0:00:59.014
下面这个2个人也抬得动 但是有点费力
This one can be lifted by two men, but it's a bit hard to move.
0:00:59.373,0:01:00.852
3个人抬很轻松
It's easy for three people to carry.
0:01:02.709,0:01:03.628
好
good
0:01:12.295,0:01:13.975
你看嘛 它还要滚
See? It will roll.
0:01:16.054,0:01:16.669
好
good
0:01:21.679,0:01:23.449
干这个活没有点蛮力不行
You can't do this job without some brute strength.
0:01:24.183,0:01:29.441
反正干厨师也要能文能武
In order to be a good cook, you need to be a good fighter anyway.
0:01:29.441,0:01:30.041
对吧
right?
0:01:30.839,0:01:32.026
这个要不要的
Do we need this one?
0:01:32.049,0:01:34.401
这个要 这个是垫豆花的
Yes, this one is also for making the soy cured flower.
0:01:35.655,0:01:36.662
还差啥子
What's missing?
0:01:36.752,0:01:37.463
帕子
filter mesh
0:01:37.774,0:01:39.966
还有锅 那个纱布
Oh, the pot, and the filter mesh
0:01:41.251,0:01:41.747
锅儿安
big pot
0:01:44.418,0:01:48.030
你看这个锅这个铁锅啊 特别秀气啊
Look at this iron wok. It's so beautiful.
0:01:48.551,0:01:50.457
如果不放油这样子的话
If you don't put oil in it,
0:01:51.544,0:01:53.930
两三个小时就会生很多锈
in two or three hours, there'll be a lot of rust.
0:01:54.632,0:01:56.094
我现在放了一些油在里面
I've put some oil in it now.
0:01:56.320,0:01:58.470
放个几年都不会生锈
It won't rust for years.
0:01:58.470,0:02:02.012
这个就是有保养跟没保养区别就在这里
That's the difference between maintenance and no maintenance.
0:02:02.605,0:02:04.534
一点油其实不值什么钱
A little oil isn't really expensive.
0:02:09.436,0:02:12.781
好啦 现在我要开始出发了
All right, now I'm off.
0:02:14.078,0:02:15.102
回老家
back to our countryside home
0:02:21.160,0:02:22.252
放在这上面
Put it on here.
0:02:24.675,0:02:25.563
小心手哦
Watch your hands.
0:02:29.027,0:02:29.565
好
good
0:02:30.003,0:02:33.208
这边用泡沫垫哈 这个才往那边流得下去
Use a foam pad here, the juice flows that way by a slope.
0:02:35.051,0:02:35.781
噶 四伯爷
Right? Uncle Si.
0:02:35.817,0:02:36.164
对对对
Yes, yes, yes.
0:02:36.209,0:02:37.047
这边还要矮点
It need to be shorter here.
0:02:37.047,0:02:38.787
整点水来试哈就晓得了撒
We'll see if we can get some water to test it.
0:02:39.097,0:02:40.182
不用试得那边都高了
You don't have to try. It's too high over there.
0:02:40.501,0:02:41.385
不得高那边
I don't think so.
0:02:45.849,0:02:46.652
这哈往那边放
Put this over here.
0:02:47.254,0:02:49.058
那个碓窝在哪儿买的哦
Where did you get that quern-stone?
0:02:49.348,0:02:50.359
是借的啊
I borrowed it.
0:02:50.469,0:02:50.924
嗯
Hmm.
0:02:53.778,0:02:57.411
这个要一个人搬 这个两个人搬反而不好搬
This one has to be moved by one person, it's harder by two.
0:02:59.707,0:03:00.459
放在这上面撒
Put it on here.
0:03:00.615,0:03:01.784
这上面的一坨120斤
This one weighs 120 jin (60kg).
0:03:02.494,0:03:03.048
称过的啊
Weighed?
0:03:03.444,0:03:03.841
嗯
Yes
0:03:04.979,0:03:06.431
要轻放这磨盘
You have to be gentle with the grindstone.
0:03:08.444,0:03:09.958
我们那个安哪儿
Where should we put it?
0:03:10.114,0:03:10.699
那不是啊
Yes
0:03:10.699,0:03:12.004
放这个要有技巧
It takes skill to place this.
0:03:13.225,0:03:15.375
不要在上面磨过去磨过来的
Don't rub it over the stone.
0:03:15.375,0:03:16.659
磨的话把那个齿齿（磨掉）
If you rub it, the tooth will grind off.
0:03:16.983,0:03:18.152
那肯定撒
That's for sure.
0:03:18.590,0:03:21.408
好可以了 终于现在放下来了
Okay, that's good. We finally moving them back to our house.
0:03:21.931,0:03:23.141
好 本期视频就到这里
Okay, that's it for this video.
0:03:23.141,0:03:25.010
下次推豆花吃
Next time we'll use this to make soy beans flower.
0:03:25.720,0:03:26.419
拜拜
bye-bye
