### ISSUE TITLE
[手工耿] 卫生间机器人 - https://youtu.be/NyQKvp7UfeM

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1334]
https://youtu.be/NyQKvp7UfeM
<p>&#35270;&#39057;&#21457;&#24067;&#20110; July 31, 2020 at 08:00PM</p>
<p>&#26631;&#39064;<br>
&#29028;&#27683;&#32592;&#25913;&#36896;&#27231;&#22120;&#20154;&#65281;&#36454;&#36842;/&#20786;&#29289;/&#36865;&#32025;/&#25793;&#25265;&#65292;&#34907;&#29983;&#38291;&#26377;&#23427;&#23601;&#22816;&#20102;!&#12304;&#25163;&#24037;&#32831;Handy Geng&#12305;</p>
<p>&#31616;&#20171;<br>
&#24466;&#25163;&#25171;&#36896;&#34907;&#29983;&#38291;&#22810;&#29992;&#27231;&#22120;&#20154;&#65281;&#65281; &#19981;&#20677;&#26377;&#35486;&#38899;&#31995;&#32113;&#65292;&#36996;&#33021;&#20936;&#21270;&#31354;&#27683;&#12289;&#20786;&#29289;&#12289;&#28888;&#20094;&#12289;&#33258;&#21205;&#36865;&#32025;&#12289;&#20805;&#38651;&#12289;&#36454;&#36842;&#12289;&#25793;&#25265;&#65281; &#19978;&#24257;&#25152;&#21644;&#25214;&#27138;&#23376;&#65292;&#20841;&#19981;&#35492;~ &mdash;&mdash; &#21029;&#20154;&#31505;&#25105;&#22826;&#30219;&#30322;&#65292;&#31505;&#23436;&#30219;&#30322;&#31505;&#25105;&#38289;&#12290; &#22823;&#23478;&#22909;&#65292;&#25105;&#26159;&#25163;&#24037;&#32831;&#65292;&#22914;&#26524;&#20320;&#21916;&#27489;&#25105;&#30340;&#35222;&#38971;&#65292;&#27489;&#36814;&#40670;&#25802;&#35330;&#38321;&#12290; #&#25163;&#24037;&#32831; #&#27231;&#22120;&#20154; #UselessEdison #&#32831;&#24101; #ChineseEdison #shougonggeng #handicraft #&#25163;&#24037; #&#30828;&#26680; #&#33258;&#35069;&#27231;&#22120;&#20154; #inventions #&#20013;&#22283;&#30332;&#26126; #&#20013;&#22283;&#24859;&#36842;&#29983; #&#24290;&#26612;&#24859;&#36842;&#29983; #&#25630;&#31505;&#30332;&#26126;</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/113772413d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by max-sun-hongyi** [comment]
标题
煤氣罐改造機器人！蹦迪/儲物/送紙/擁抱，衛生間有它就夠了!【手工耿Handy Geng】
Retrofit Gas Cylinder! Disco/Storage/Paper/Hugs, all you need for a toilet [Handy Geng]


简介
徒手打造衛生間多用機器人！！ 不僅有語音系統，還能凈化空氣、儲物、烘乾、自動送紙、充電、蹦迪、擁抱！ 上廁所和找樂子，兩不誤~ —— 別人笑我太瘋癲，笑完瘋癲笑我閑。 大家好，我是手工耿，如果你喜歡我的視頻，歡迎點擊訂閱。 #手工耿 #機器人 #UselessEdison #耿帥 #ChineseEdison #shougonggeng #handicraft #手工 #硬核 #自製機器人 #inventions #中國發明 #中國愛迪生 #廢柴愛迪生 #搞笑發明

Hand-made multi-functional toilet robot!
Additional to Voice Recognition System, it can also improve air quality, built-in storage, blow drying, auto-paper, battery charger, disco and hugs!
In the toilet and have fun! You can have both!

Hello everyone, I am Handy Geng. Welcome to subscribe to my channel if you like my videos!


0:00:00.820,0:00:03.260
Recently I have made a stand for blowers. 

0:00:03.440,0:00:05.060
 This time, I am going to upgrade it

0:00:05.600,0:00:07.240
 Turn it into a multi-functional robot for toilet.

0:02:28.680,0:02:32.400
 Now let me introduce you with the multi-functional robot I've made

0:02:32.400,0:02:35.720
When you feel the nature's call

0:02:36.180,0:02:37.520
Welcome!

0:02:37.920,0:02:40.740
When you walk out from the toilet 

0:02:42.500,0:02:44.500
Have a good one!

0:02:44.540,0:02:47.495
Very polite, you can tell from his simple words 

0:02:47.500,0:02:51.740
Turns a regular loo into a fancy washroom 

0:02:52.280,0:02:55.040
The air quality in most toilets is not great 

0:02:55.040,0:02:57.960
There is a device to purify the air around it 

0:02:58.440,0:03:00.060
Add essence oil in here

0:03:00.340,0:03:01.840
Here we have a small fan 

0:03:02.080,0:03:03.700
Turn on the switch on its ear

0:03:04.360,0:03:06.900
It speeds up the evaporation of essence oil 

0:03:10.220,0:03:12.860
If we look down, there is a storage compartment unit

0:03:13.440,0:03:16.980
You can store your cleaning products here

0:03:17.480,0:03:20.040
plus a water hose and a basin

0:03:20.440,0:03:22.480
You can wash your hands in here

0:03:23.320,0:03:25.100
or wash your hair 

0:03:25.280,0:03:27.120
When you done washing, check this out

0:03:28.100,0:03:29.980
Close this door

0:03:30.380,0:03:34.300
The blow dryer will automatically move towards you hand  

0:03:34.780,0:03:36.500
and blow dries your hands 

0:03:41.800,0:03:44.080
it even moves back to it's original position once drying is finished

0:03:45.575,0:03:48.345
You can also pick it up to blow dry your hair

0:03:49.645,0:03:50.645
Put it back

0:03:51.635,0:03:53.085
Automatically turns off

0:03:53.440,0:03:56.600
On the other hand, you can find toilet paper

0:03:56.760,0:03:58.680
When we are done 

0:03:59.300,0:04:01.300
Just yell at it

0:04:02.360,0:04:03.120
PAPER COME!

0:04:04.660,0:04:07.220
It will bring toilet paper to you

0:04:08.200,0:04:09.840
All done in a ritualistic manner

0:04:12.005,0:04:13.475
Tear off what you need 

0:04:13.845,0:04:15.695
It revert back to it's original position

0:04:18.415,0:04:21.145
I like to play on my phone in the toilet

0:04:21.145,0:04:22.420
Low battery level worries me

0:04:22.640,0:04:24.960
That's why I've installed a AC socket in here 

0:04:25.320,0:04:27.280
You can charge up your phone when it's running low on juice  

0:04:29.660,0:04:32.780
Previously I have installed a disco lighting system in the toilet   

0:04:32.780,0:04:35.140
But I get a bit bored dancing by myself

0:04:35.140,0:04:37.180
This robot can even dance with you 

0:04:37.180,0:04:43.180
 Let's turn on the switch and see

**Comment by immoonancient** [comment]
bot, please upload on behalf of the assignee

# https://youtu.be/NyQKvp7UfeM

# 标题
# 煤氣罐改造機器人！蹦迪/儲物/送紙/擁抱，衛生間有它就夠了!【手工耿Handy Geng】
# Retrofit Gas Cylinder! Disco/Storage/Paper/Hugs, all you need for a toilet [Handy Geng]

# 简介

# 徒手打造衛生間多用機器人！！ 不僅有語音系統，還能凈化空氣、儲物、烘乾、自動送紙、充電、蹦迪、擁抱！ 上廁所和找樂子，兩不誤~ —— 別人笑我太瘋癲，笑完瘋癲笑我閑。 大家好，我是手工耿，如果你喜歡我的視頻，歡迎點擊訂閱。 #手工耿 #機器人 #UselessEdison #耿帥 #ChineseEdison #shougonggeng #handicraft #手工 #硬核 #自製機器人 #inventions #中國發明 #中國愛迪生 #廢柴愛迪生 #搞笑發明

# Hand-made multi-functional toilet robot!
# Additional to Voice Recognition System, it can also improve air quality, built-in storage, blow drying, auto-paper, battery charger, disco and hugs!
# In the toilet and have fun! You can have both!

# import intro

0:00:00.820,0:00:03.260
前不久我做了一个吹风机支架
Recently I have made a stand for blowers.

0:00:03.440,0:00:05.060
这次我准备升级一下它
This time, I am going to upgrade it

0:00:05.600,0:00:07.240
做一个卫生间的多用机器人
Turn it into a multi-functional robot for toilet.

0:02:28.680,0:02:32.400
给大家介绍一下我做的这个卫生间多功能机器人
Now let me introduce you with the multi-functional robot I've made

0:02:32.400,0:02:35.720
当你去卫生间方便的时候
When you feel the nature's call

0:02:36.180,0:02:37.520
您好 欢迎光临
Welcome!

0:02:37.920,0:02:40.740
当你上完厕所 走的时候
When you walk out from the toilet

0:02:42.500,0:02:44.500
谢谢惠顾 请慢走
Have a good one!

0:02:44.540,0:02:47.495
非常的有礼貌 简简单单一句话
Very polite, you can tell from his simple words

0:02:47.500,0:02:51.740
让一个普普通通的卫生间瞬间升级为星级卫生间
Turns a regular loo into a fancy washroom

0:02:52.280,0:02:55.040
大部分卫生间里面的空气也不是特别好
The air quality in most toilets is not great

0:02:55.040,0:02:57.960
他头部还有一个净化空气的装置
There is a device to purify the air around it

0:02:58.440,0:03:00.060
往里面加上香料啊
Add essence oil in here

0:03:00.340,0:03:01.840
这里还有一个小电扇
Here we have a small fan

0:03:02.080,0:03:03.700
打开耳朵上的开关
Turn on the switch on its ear

0:03:04.360,0:03:06.900
它还可以加速香料的挥发
It speeds up the evaporation of essence oil

0:03:10.220,0:03:12.860
这个空气净化机的下面是一个储物柜
If we look down, there is a storage compartment unit

0:03:13.440,0:03:16.980
打开之后里面可以放一些我们平常的洗漱用品
You can store your cleaning products here

0:03:17.480,0:03:20.040
里面还有一个水龙头和洗手盆
plus a water hose and a basin

0:03:20.440,0:03:22.480
平时我们可以在这里洗手
You can wash your hands in here

0:03:23.320,0:03:25.100
啊 洗头
or wash your hair

0:03:25.280,0:03:27.120
洗完之后请注意
When you done washing, check this out

0:03:28.100,0:03:29.980
关上这个储物柜之后
Close this door

0:03:30.380,0:03:34.300
这个烘干机就会自动地给我们递到手下面
The blow dryer will automatically move towards you hand

0:03:34.780,0:03:36.500
把手烘干
and blow dries your hands

0:03:41.800,0:03:44.080
吹完之后它会自动地复原
it even moves back to it's original position once drying is finished

0:03:45.575,0:03:48.345
拿起之后还可以给你吹下头发之类的
You can also pick it up to blow dry your hair

0:03:49.645,0:03:50.645
放回去
Put it back

0:03:51.635,0:03:53.085
自动关闭
Automatically turns off

0:03:53.440,0:03:56.600
他的另一只手里面还可以放一些卫生纸
On the other hand, you can find toilet paper

0:03:56.760,0:03:58.680
这样我们方便玩擦屁屁的时候
When we are done

0:03:59.300,0:04:01.300
只需要对它大喊一声
Just yell at it

0:04:02.360,0:04:03.120
来纸
PAPER COME!

0:04:04.660,0:04:07.220
卫生纸就会自动地递到你的面前
It will bring toilet paper to you

0:04:08.200,0:04:09.840
非常的有仪式感
All done in a ritualistic manner

0:04:12.005,0:04:13.475
撕完纸之后
Tear off what you need

0:04:13.845,0:04:15.695
它会自动复原
It revert back to it's original position

0:04:18.415,0:04:21.145
上厕所我比较喜欢玩手机
I like to play on my phone in the toilet

0:04:21.145,0:04:22.420
最害怕手机没有电
Low battery level worries me

0:04:22.640,0:04:24.960
所以我在这里安装一个插座
That's why I've installed a AC socket in here

0:04:25.320,0:04:27.280
没电的时候还可以在这里充电
You can charge up your phone when it's running low on juice

0:04:29.660,0:04:32.780
以前我在卫生间里装了一套蹦迪的系统
Previously I have installed a disco lighting system in the toilet

0:04:32.780,0:04:35.140
但是说一个人蹦有点无聊
But I get a bit bored dancing by myself

0:04:35.140,0:04:37.180
这个机器人还可以陪你一起蹦迪
This robot can even dance with you

0:04:37.180,0:04:43.180
现在咱们打开开关试一下
Let's turn on the switch and see
