### ISSUE TITLE
[华农兄弟] 华农兄弟收到一份神秘的快递拆开来尝一下味道还可以哟 - https://youtu.be/TbU48B_6hrc

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1335]
https://youtu.be/TbU48B_6hrc
<p>&#35270;&#39057;&#21457;&#24067;&#20110; August 1, 2020 at 11:32AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/TbU48B_6hrc

#华农兄弟：收到一份神秘的快递，拆开来尝一下，味道还可以哟
#Huanong Brothers: We received a mysterious parcel. Let's open and have a try. It tastes not bad.

0:00:00.000,0:00:02.380
# 大家好  我們收到一個神秘的快遞喲
Hi everyone! We received a mysterious parcel today.

0:00:02.560,0:00:04.460
# 不知道是甚麼  我們拆開來看一下
I wonder what it is. Let's open it and have a look.

0:00:08.120,0:00:09.000
# 哇~
Wa~

0:00:12.800,0:00:14.500
# 單兵制(SIC)熱食品  (註︰包著上寫「自熱」，原字幕幾乎都搞錯了)
Self-heat military food for single use

0:00:15.300,0:00:18.800
# 這是@中國火箭軍  寄給我們的哦
This is from the Liberation Army Rocket Force. They sent it to us.

0:00:19.080,0:00:20.460
# 東風快遞寄過來的
It's sent through Dongfeng Express. (dimunitive name of Dongfeng Missile).

0:00:21.640,0:00:23.220
# 制熱食品應該就是
Self-heat food should be kind of,

0:00:25.380,0:00:27.420
# 應該就是我們人民的軍隊吃的
should be the food used by our people's army.

0:00:30.240,0:00:31.000
# 這個餅乾
The bar...

0:00:33.340,0:00:34.380
# 多維能量餅
Multidimensional energy bar

0:00:35.560,0:00:39.460
# 壓縮餅乾  吃一點點它就能維持  就不會那麼飢餓
Energy bar. A tiny little bit of it can keep... You won't feel that hungry.

0:00:39.460,0:00:40.680
# 只要吃一點點就好啦
A tiny little bit would be enough.

0:00:41.960,0:00:45.140
# 多維能量餅 (葡萄乾)  (註︰非說話)
Multidimensional energy bar
(Dried Grapefruits)

0:00:47.820,0:00:50.780
# 你看  這個就是壓縮餅乾吧
Look! This is the so called energy bar, isn't it?

0:00:52.560,0:00:54.560
# 嘗一下  哇  好香
Let me have a try! Wa! Smells good!

0:00:54.940,0:00:55.920
# 真的好香啊
Really good!

0:00:57.920,0:00:58.880
# 哇  你看
Wa! Look!

0:01:05.320,0:01:06.040
# 葡萄味
Grapefruits flavour

0:01:07.220,0:01:09.640
# 你看  葡萄乾味  這裡面有葡萄乾的
Look! Dried grapefruits flavour. There are dried grapefruits inside.

0:01:10.360,0:01:11.100
# 這個軍糧
This kind of military food,

0:01:11.360,0:01:13.120
# 他上山的時候帶一點  特別好
is exceptionally good when they're going onto the mountains.

0:01:13.180,0:01:14.140
# 是呀  充飢
Indeed. It can satiate the hunger.

0:01:14.740,0:01:18.300
# 呃 吃一點點就能扛的住  扛得住很久
Eh, a tiny little bit of it can allow them to hang in, hang in for a long time.

0:01:18.580,0:01:19.700
# 它能充飢哇
Cuz, it can satiate the hunger.

0:01:23.120,0:01:24.180
# 吃一塊就飽啦
A single piece is enough make you full.

0:01:24.840,0:01:28.940
# 我們的人民解放軍戰士  你看  每次去出差呀 打仗啊
The soldiers of our People's Liberation Amry... Look! Every time when they are out for work, for a war,

0:01:28.940,0:01:31.400
# 或者那個訓練之外就吃這個東西
or, you know, training, or whatever, this is what they eat.

0:01:31.680,0:01:34.120
# 這個容易充飢哇  方便紐帶  (註︰「紐帶」在這視頻出現了很多次，西瓜和B站的人都沒看明白，所以當「携帶」算了)
This can keep them feel full easily. And it's easy to carry.

0:01:38.440,0:01:39.960
# 你看  保家衞國
Look! Protecting our families and our country,

0:01:40.580,0:01:42.620
# 都是他們在做  是啊  吃的都是這種
is what they're doing. Yup! And this is what they're eating.

0:01:42.940,0:01:43.720
# 還有這種
And also this kind of,

0:01:45.400,0:01:46.060
# 這醬料
the sauce...

0:01:46.740,0:01:49.260
# 有一個制熱袋  熱的那個飯就直接這樣吃
There is a self-heat pack. You can heat the rice and then eat it right away.

0:01:50.280,0:01:51.120
# 特別辛苦
Life is really harsh,

0:01:52.020,0:01:52.720
# 在外面
when they're outside.

0:01:53.000,0:01:54.500
# 哇  這個是衣服哦
Wa! This is a T-shirt!

0:01:55.840,0:01:56.600
# 拆開來
Let me open it,

0:01:57.100,0:01:57.880
# 看一下
and have a look.

0:01:59.540,0:02:01.420
# 哇瑟  哇  那麼漂亮
Gosh! Wa! It's pretty!

0:02:04.140,0:02:04.740
# 正義
Justice

0:02:05.200,0:02:06.960
# 天降正義  (註︰這不是說話，但我想解釋一下)
Justice from Heaven

0:02:06.980,0:02:07.580
# 你看 
Look!

0:02:08.020,0:02:08.620
# 正義
Justice

0:02:08.860,0:02:10.920
# 東風快遞 使拿必達
Dongfeng Epress, Mission Complete

0:02:11.220,0:02:12.740
# 你看  我把這衣服穿上
Look! I'm gonna put on this T-shirt!

0:02:15.480,0:02:16.620
# 誒  上面那頭
Eh? The goat up there,

0:02:16.980,0:02:18.200
# 兩頭羊都過來啦
both goats are coming.

0:02:34.580,0:02:35.940
# 你看  帥不帥
Look! Is it cool?

0:02:36.900,0:02:38.740
# 天降正義  (註︰這不是說話，但我想解釋一下)
Justice from Heaven

0:02:39.700,0:02:40.880
# 看下下還有甚麼好東西
Let me see what other good stuff are there.

0:02:42.800,0:02:45.820
# 誒 這個也是衣服  大的  加大
Eh? These are also T-shirts. This is large size, extra large.

0:02:47.500,0:02:48.560
# 哇  還有這個
Wa! Here's also a...

0:02:52.400,0:02:53.780
# 你看  這個桌墊  (東風快遞 使命必達  火箭軍) (註︰這不是說話，但我想解釋一下)
Look! This desk pad is,
(Dongfeng Express, Mission Complete. Rocket Army)

0:02:53.780,0:02:54.380
# (東風快遞 使命必達  火箭軍)
(Dongfeng Express, Mission Complete. Rocket Army)

0:02:54.380,0:02:55.080
# 靚吧
beautiful, isn't it?
(Dongfeng Express, Mission Complete. Rocket Army)

0:02:55.080,0:02:55.940
# (東風快遞 使命必達  火箭軍)
(Dongfeng Express, Mission Complete. Rocket Army)

0:02:56.320,0:02:57.260
# 火箭軍
Rocket Army

0:02:59.400,0:03:01.300
# 東風快遞 使命必達
Dongfeng Express, Mission Complete

0:03:04.440,0:03:07.400
# 這個也可以做  用來做那個  額 鼠標墊的  這個
This can also be, it can be, I mean, eh, a mouse pad, this one.

0:03:07.940,0:03:10.460
# 它這很柔軟的  摸起來很舒服
It's really soft. It feels so comfortable.

0:03:14.300,0:03:15.280
# 好威武哇
So formidable!

0:03:20.640,0:03:22.340
# 我們去加點水來試一下這個
Let me get some water, and try this one.

0:03:30.020,0:03:32.380
# 好久沒下雨啦  差不多兩個月都沒下雨
It has been a long time since the last rain, almost two months.

0:03:32.900,0:03:33.520
# 現在
And now,

0:03:34.020,0:03:35.020
# 好大的雨呀
it's raining heavily.

0:03:38.820,0:03:40.580
# 洗一下這裡的灰塵
It can wash away the dust here.

0:03:47.700,0:03:48.500
# 吃一下這個飯
Let me try this rice.

0:03:49.900,0:03:52.040
# 這個飯輕輕的撕開
The rice, I tear it open here, gently.

0:03:52.800,0:03:54.500
# 你看  這是飯哦  這是
Look! This is rice, this is,

0:03:55.020,0:03:57.100
# 海鮮  咖喱炒飯
fried rice, with seafood, and curry sauce.

0:03:57.800,0:03:59.500
# 這是  兩袋那個
These, two packs are, you know,

0:04:00.900,0:04:02.400
# 發熱 發熱片
heating, heating pads.

0:04:02.840,0:04:03.840
# 這樣把它裹住
We can wrap it up like this.

0:04:04.840,0:04:06.300
# 這樣把它裹住 再放進去
Wrap it up, and then we can put it inside.

0:04:07.040,0:04:10.420
# 然後就可以直接放點水 就可以直接發熱啦
Then it can heat, with some water, it can heat up right away.

0:04:10.920,0:04:13.040
# 這裡還有一個加熱器用水袋
These is a water bag for the heating pad.

0:04:13.780,0:04:16.020
# 裝那麼多水就可以啦  我去裝點那個冷水
I only need to fill the water up here. I'm gonna get some cold water..

0:04:16.800,0:04:17.440
# 你看
Look!

0:04:17.740,0:04:18.840
# 它畫了綫啦
A line is here.

0:04:19.440,0:04:20.520
# 很人性化
It's really user friendly.

0:04:21.180,0:04:22.420
# 把這水倒進去
So I pour the water in.

0:04:27.940,0:04:28.940
# 然後再把它
And then I'm gonna,

0:04:29.460,0:04:30.160
# 蓋起來
cover it up.

0:04:31.580,0:04:33.600
# 要快一點啊  快一點  因為現在開始
I gotta be fast, and faster, cuz it's starting to...

0:04:33.840,0:04:34.960
# 你看  開始發脹啦
Look! It starts blowing up now.

0:04:35.340,0:04:36.300
# 哇
Wa!

0:04:37.200,0:04:38.620
# 快不快  好快呀
Isn't it fast? It's really fast!

0:04:38.960,0:04:40.180
# 這個溫度好燙的喲
The temperature is really high.

0:04:41.120,0:04:42.260
# 都能燙手  這個
It, it burns my hand.

0:04:43.600,0:04:44.600
# 先把它蓋起來
Let me cover it up first.

0:04:46.840,0:04:47.920
# 這樣放著就可以啦
Place it here and that's it.

0:04:48.020,0:04:50.260
# 這個十分鐘以後哇 就可以吃啦
Well, in ten minutes, it will be ready to serve.

0:04:50.580,0:04:52.000
# 還有西紅杮蛋湯哦
Here's also tomato soup with egg.

0:04:52.400,0:04:53.200
# 藍莓乾
Dried blue berries

0:04:54.380,0:04:55.800
# 雞肉香辣醬
Chicken chilli sauce

0:04:57.300,0:05:00.100
# 香辣金針菇 等下飯好啦  我就把這個放上去就好啦
Spicy sauce with enokitake. When the rice it ready, I can simply put it onto the rice.

0:05:00.380,0:05:01.900
# 這個藍莓乾這應該是
I think the dried blue berries should be,

0:05:02.260,0:05:03.040
# 小零食
some kinds of snacks.

0:05:04.240,0:05:04.880
# 這個湯
The soup...

0:05:05.480,0:05:06.140
# 後面來
Later!

0:05:07.760,0:05:09.480
# 在香口香糖 這還有口香糖  (註︰原字幕有錯吧？沒看懂也沒聽懂)
This is chewing gum, there's also chewing gum.

0:05:10.140,0:05:12.300
# 口香糖是在路上吃的
They chew the chewing gum, when they're on the way.

0:05:15.220,0:05:17.560
# 放這靠一下  靠熱一點
Put it here, closer to the heat.

0:05:20.300,0:05:22.820
# 現在好了哦  我把這個飯盒拿出來
It's ready now. I'm gonna take out the rice container.

0:05:26.520,0:05:28.800
# 把這個勺子拿出來
I take out the spoon as well.

0:05:28.960,0:05:31.220
# 把這飯倒出來  很燙的哦  這個
Let me pour out the rice. It's really hot, the rice.

0:05:31.320,0:05:33.280
# 一定要注意  不要燙傷弓手
I need to be very careful. Otherwise it may burn my hands.

0:05:36.500,0:05:38.360
# 一個撕口  就這樣撕開
I can simply tear it open, from here.

0:05:40.540,0:05:43.140
# 這個溫度可以  超過百度哦  這個
This temperature is not bad. It's over a hundred degrees, you know.

0:05:43.760,0:05:44.860
# 超過一百度哦
It's over a hundred degrees.

0:05:45.160,0:05:46.640
# 還有  可以把這個配料
Also, I can pour the side ingredients,

0:05:47.540,0:05:48.340
# 放進去
onto the rice.

0:05:48.420,0:05:49.320
# 金針菇
Enokitake

0:05:50.000,0:05:51.360
# 這辣椒醬哦  這個
And this is, this is chilli sauce.

0:05:52.520,0:05:53.160
# 你看
Look!

0:05:53.760,0:05:55.580
# 這飯就好啦 特別簡單
The rice is now ready. It's really simple.

0:05:58.660,0:05:59.160
# 嗯
Um!

0:06:01.920,0:06:02.860
# 這個飯好吃
It tastes really good!

0:06:05.980,0:06:07.060
# 這還有海鮮哦
There's seafood as well,

0:06:10.980,0:06:11.840
# 還有辣椒醬
and chilli sauce too.

0:06:14.060,0:06:16.000
# 吃了這個飯很容易補充體力喲
This rice can refuel the body very quickly.

0:06:16.000,0:06:17.600
# 而且紐帶起來特別方便
And carrying it is also exceptionally convenient.

0:06:20.820,0:06:21.780
# 熱騰騰的
It's boiling hot.

0:06:22.780,0:06:24.120
# 還燙手  現在
I can still feel it burning, even now.

0:06:26.620,0:06:28.640
# 感謝人民解放軍的辛苦付出
My greatest gratitude to all the hardships and givings of the People's Liberation Army.

0:06:28.640,0:06:31.000
# 守護我們的祖國每一寸土地
It's all because of their protection of every single inch of soil of our Motherland,

0:06:31.380,0:06:33.360
# 才有我們今天的美好生活
that we can enjoy our beautiful and fruitful lives nowadays.

0:06:33.760,0:06:36.760
# 祝我們的國家繁榮昌盛  越來越強大
I wish our Motherland forever prosperity, and endless blossoming.

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/TbU48B_6hrc

#华农兄弟：收到一份神秘的快递，拆开来尝一下，味道还可以哟
#Huanong Brothers: We received a mysterious parcel. Let's open and have a try. It tastes not bad.

0:00:00.000,0:00:02.380
# 大家好  我們收到一個神秘的快遞喲
Hi everyone! We received a mysterious parcel today.

0:00:02.560,0:00:04.460
# 不知道是甚麼  我們拆開來看一下
I wonder what it is. Let's open it and have a look.

0:00:08.120,0:00:09.000
# 哇~
Wa~

0:00:12.800,0:00:14.500
# 單兵制(SIC)熱食品  (註︰包著上寫「自熱」，原字幕幾乎都搞錯了)
Self-heat military food for single use

0:00:15.300,0:00:18.800
# 這是@中國火箭軍  寄給我們的哦
This is from the Liberation Army Rocket Force. They sent it to us.

0:00:19.080,0:00:20.460
# 東風快遞寄過來的
It's sent through Dongfeng Express. (dimunitive name of Dongfeng Missile).

0:00:21.640,0:00:23.220
# 制熱食品應該就是
Self-heat food should be kind of,

0:00:25.380,0:00:27.420
# 應該就是我們人民的軍隊吃的
should be the food used by our people's army.

0:00:30.240,0:00:31.000
# 這個餅乾
The bar...

0:00:33.340,0:00:34.380
# 多維能量餅
Multidimensional energy bar

0:00:35.560,0:00:39.460
# 壓縮餅乾  吃一點點它就能維持  就不會那麼飢餓
Energy bar. A tiny little bit of it can keep... You won't feel that hungry.

0:00:39.460,0:00:40.680
# 只要吃一點點就好啦
A tiny little bit would be enough.

0:00:41.960,0:00:45.140
# 多維能量餅 (葡萄乾)  (註︰非說話)
Multidimensional energy bar
(Dried Grapefruits)

0:00:47.820,0:00:50.780
# 你看  這個就是壓縮餅乾吧
Look! This is the so called energy bar, isn't it?

0:00:52.560,0:00:54.560
# 嘗一下  哇  好香
Let me have a try! Wa! Smells good!

0:00:54.940,0:00:55.920
# 真的好香啊
Really good!

0:00:57.920,0:00:58.880
# 哇  你看
Wa! Look!

0:01:05.320,0:01:06.040
# 葡萄味
Grapefruits flavour

0:01:07.220,0:01:09.640
# 你看  葡萄乾味  這裡面有葡萄乾的
Look! Dried grapefruits flavour. There are dried grapefruits inside.

0:01:10.360,0:01:11.100
# 這個軍糧
This kind of military food,

0:01:11.360,0:01:13.120
# 他上山的時候帶一點  特別好
is exceptionally good when they're going onto the mountains.

0:01:13.180,0:01:14.140
# 是呀  充飢
Indeed. It can satiate the hunger.

0:01:14.740,0:01:18.300
# 呃 吃一點點就能扛的住  扛得住很久
Eh, a tiny little bit of it can allow them to hang in, hang in for a long time.

0:01:18.580,0:01:19.700
# 它能充飢哇
Cuz, it can satiate the hunger.

0:01:23.120,0:01:24.180
# 吃一塊就飽啦
A single piece is enough make you full.

0:01:24.840,0:01:28.940
# 我們的人民解放軍戰士  你看  每次去出差呀 打仗啊
The soldiers of our People's Liberation Amry... Look! Every time when they are out for work, for a war,

0:01:28.940,0:01:31.400
# 或者那個訓練之外就吃這個東西
or, you know, training, or whatever, this is what they eat.

0:01:31.680,0:01:34.120
# 這個容易充飢哇  方便紐帶  (註︰「紐帶」在這視頻出現了很多次，西瓜和B站的人都沒看明白，所以當「携帶」算了)
This can keep them feel full easily. And it's easy to carry.

0:01:38.440,0:01:39.960
# 你看  保家衞國
Look! Protecting our families and our country,

0:01:40.580,0:01:42.620
# 都是他們在做  是啊  吃的都是這種
is what they're doing. Yup! And this is what they're eating.

0:01:42.940,0:01:43.720
# 還有這種
And also this kind of,

0:01:45.400,0:01:46.060
# 這醬料
the sauce...

0:01:46.740,0:01:49.260
# 有一個制熱袋  熱的那個飯就直接這樣吃
There is a self-heat pack. You can heat the rice and then eat it right away.

0:01:50.280,0:01:51.120
# 特別辛苦
Life is really harsh,

0:01:52.020,0:01:52.720
# 在外面
when they're outside.

0:01:53.000,0:01:54.500
# 哇  這個是衣服哦
Wa! This is a T-shirt!

0:01:55.840,0:01:56.600
# 拆開來
Let me open it,

0:01:57.100,0:01:57.880
# 看一下
and have a look.

0:01:59.540,0:02:01.420
# 哇瑟  哇  那麼漂亮
Gosh! Wa! It's pretty!

0:02:04.140,0:02:04.740
# 正義
Justice

0:02:05.200,0:02:06.960
# 天降正義  (註︰這不是說話，但我想解釋一下)
Justice from Heaven

0:02:06.980,0:02:07.580
# 你看 
Look!

0:02:08.020,0:02:08.620
# 正義
Justice

0:02:08.860,0:02:10.920
# 東風快遞 使拿必達
Dongfeng Epress, Mission Complete

0:02:11.220,0:02:12.740
# 你看  我把這衣服穿上
Look! I'm gonna put on this T-shirt!

0:02:15.480,0:02:16.620
# 誒  上面那頭
Eh? The goat up there,

0:02:16.980,0:02:18.200
# 兩頭羊都過來啦
both goats are coming.

0:02:34.580,0:02:35.940
# 你看  帥不帥
Look! Is it cool?

0:02:36.900,0:02:38.740
# 天降正義  (註︰這不是說話，但我想解釋一下)
Justice from Heaven

0:02:39.700,0:02:40.880
# 看下下還有甚麼好東西
Let me see what other good stuff are there.

0:02:42.800,0:02:45.820
# 誒 這個也是衣服  大的  加大
Eh? These are also T-shirts. This is large size, extra large.

0:02:47.500,0:02:48.560
# 哇  還有這個
Wa! Here's also a...

0:02:52.400,0:02:53.780
# 你看  這個桌墊  (東風快遞 使命必達  火箭軍) (註︰這不是說話，但我想解釋一下)
Look! This desk pad is,
(Dongfeng Express, Mission Complete. Rocket Army)

0:02:53.780,0:02:54.380
# (東風快遞 使命必達  火箭軍)
(Dongfeng Express, Mission Complete. Rocket Army)

0:02:54.380,0:02:55.080
# 靚吧
beautiful, isn't it?
(Dongfeng Express, Mission Complete. Rocket Army)

0:02:55.080,0:02:55.940
# (東風快遞 使命必達  火箭軍)
(Dongfeng Express, Mission Complete. Rocket Army)

0:02:56.320,0:02:57.260
# 火箭軍
Rocket Army

0:02:59.400,0:03:01.300
# 東風快遞 使命必達
Dongfeng Express, Mission Complete

0:03:04.440,0:03:07.400
# 這個也可以做  用來做那個  額 鼠標墊的  這個
This can also be, it can be, I mean, eh, a mouse pad, this one.

0:03:07.940,0:03:10.460
# 它這很柔軟的  摸起來很舒服
It's really soft. It feels so comfortable.

0:03:14.300,0:03:15.280
# 好威武哇
So formidable!

0:03:20.640,0:03:22.340
# 我們去加點水來試一下這個
Let me get some water, and try this one.

0:03:30.020,0:03:32.380
# 好久沒下雨啦  差不多兩個月都沒下雨
It has been a long time since the last rain, almost two months.

0:03:32.900,0:03:33.520
# 現在
And now,

0:03:34.020,0:03:35.020
# 好大的雨呀
it's raining heavily.

0:03:38.820,0:03:40.580
# 洗一下這裡的灰塵
It can wash away the dust here.

0:03:47.700,0:03:48.500
# 吃一下這個飯
Let me try this rice.

0:03:49.900,0:03:52.040
# 這個飯輕輕的撕開
The rice, I tear it open here, gently.

0:03:52.800,0:03:54.500
# 你看  這是飯哦  這是
Look! This is rice, this is,

0:03:55.020,0:03:57.100
# 海鮮  咖喱炒飯
fried rice, with seafood, and curry sauce.

0:03:57.800,0:03:59.500
# 這是  兩袋那個
These, two packs are, you know,

0:04:00.900,0:04:02.400
# 發熱 發熱片
heating, heating pads.

0:04:02.840,0:04:03.840
# 這樣把它裹住
We can wrap it up like this.

0:04:04.840,0:04:06.300
# 這樣把它裹住 再放進去
Wrap it up, and then we can put it inside.

0:04:07.040,0:04:10.420
# 然後就可以直接放點水 就可以直接發熱啦
Then it can heat, with some water, it can heat up right away.

0:04:10.920,0:04:13.040
# 這裡還有一個加熱器用水袋
These is a water bag for the heating pad.

0:04:13.780,0:04:16.020
# 裝那麼多水就可以啦  我去裝點那個冷水
I only need to fill the water up here. I'm gonna get some cold water..

0:04:16.800,0:04:17.440
# 你看
Look!

0:04:17.740,0:04:18.840
# 它畫了綫啦
A line is here.

0:04:19.440,0:04:20.520
# 很人性化
It's really user friendly.

0:04:21.180,0:04:22.420
# 把這水倒進去
So I pour the water in.

0:04:27.940,0:04:28.940
# 然後再把它
And then I'm gonna,

0:04:29.460,0:04:30.160
# 蓋起來
cover it up.

0:04:31.580,0:04:33.600
# 要快一點啊  快一點  因為現在開始
I gotta be fast, and faster, cuz it's starting to...

0:04:33.840,0:04:34.960
# 你看  開始發脹啦
Look! It starts blowing up now.

0:04:35.340,0:04:36.300
# 哇
Wa!

0:04:37.200,0:04:38.620
# 快不快  好快呀
Isn't it fast? It's really fast!

0:04:38.960,0:04:40.180
# 這個溫度好燙的喲
The temperature is really high.

0:04:41.120,0:04:42.260
# 都能燙手  這個
It, it burns my hand.

0:04:43.600,0:04:44.600
# 先把它蓋起來
Let me cover it up first.

0:04:46.840,0:04:47.920
# 這樣放著就可以啦
Place it here and that's it.

0:04:48.020,0:04:50.260
# 這個十分鐘以後哇 就可以吃啦
Well, in ten minutes, it will be ready to serve.

0:04:50.580,0:04:52.000
# 還有西紅杮蛋湯哦
Here's also tomato soup with egg.

0:04:52.400,0:04:53.200
# 藍莓乾
Dried blue berries

0:04:54.380,0:04:55.800
# 雞肉香辣醬
Chicken chilli sauce

0:04:57.300,0:05:00.100
# 香辣金針菇 等下飯好啦  我就把這個放上去就好啦
Spicy sauce with enokitake. When the rice it ready, I can simply put it onto the rice.

0:05:00.380,0:05:01.900
# 這個藍莓乾這應該是
I think the dried blue berries should be,

0:05:02.260,0:05:03.040
# 小零食
some kinds of snacks.

0:05:04.240,0:05:04.880
# 這個湯
The soup...

0:05:05.480,0:05:06.140
# 後面來
Later!

0:05:07.760,0:05:09.480
# 在香口香糖 這還有口香糖  (註︰原字幕有錯吧？沒看懂也沒聽懂)
This is chewing gum, there's also chewing gum.

0:05:10.140,0:05:12.300
# 口香糖是在路上吃的
They chew the chewing gum, when they're on the way.

0:05:15.220,0:05:17.560
# 放這靠一下  靠熱一點
Put it here, closer to the heat.

0:05:20.300,0:05:22.820
# 現在好了哦  我把這個飯盒拿出來
It's ready now. I'm gonna take out the rice container.

0:05:26.520,0:05:28.800
# 把這個勺子拿出來
I take out the spoon as well.

0:05:28.960,0:05:31.220
# 把這飯倒出來  很燙的哦  這個
Let me pour out the rice. It's really hot, the rice.

0:05:31.320,0:05:33.280
# 一定要注意  不要燙傷弓手
I need to be very careful. Otherwise it may burn my hands.

0:05:36.500,0:05:38.360
# 一個撕口  就這樣撕開
I can simply tear it open, from here.

0:05:40.540,0:05:43.140
# 這個溫度可以  超過百度哦  這個
This temperature is not bad. It's over a hundred degrees, you know.

0:05:43.760,0:05:44.860
# 超過一百度哦
It's over a hundred degrees.

0:05:45.160,0:05:46.640
# 還有  可以把這個配料
Also, I can pour the side ingredients,

0:05:47.540,0:05:48.340
# 放進去
onto the rice.

0:05:48.420,0:05:49.320
# 金針菇
Enokitake

0:05:50.000,0:05:51.360
# 這辣椒醬哦  這個
And this is, this is chilli sauce.

0:05:52.520,0:05:53.160
# 你看
Look!

0:05:53.760,0:05:55.580
# 這飯就好啦 特別簡單
The rice is now ready. It's really simple.

0:05:58.660,0:05:59.160
# 嗯
Um!

0:06:01.920,0:06:02.860
# 這個飯好吃
It tastes really good!

0:06:05.980,0:06:07.060
# 這還有海鮮哦
There's seafood as well,

0:06:10.980,0:06:11.840
# 還有辣椒醬
and chilli sauce too.

0:06:14.060,0:06:16.000
# 吃了這個飯很容易補充體力喲
This rice can refuel the body very quickly.

0:06:16.000,0:06:17.600
# 而且紐帶起來特別方便
And carrying it is also exceptionally convenient.

0:06:20.820,0:06:21.780
# 熱騰騰的
It's boiling hot.

0:06:22.780,0:06:24.120
# 還燙手  現在
I can still feel it burning, even now.

0:06:26.620,0:06:28.640
# 感謝人民解放軍的辛苦付出
My greatest gratitude to all the hardships and givings of the People's Liberation Army.

0:06:28.640,0:06:31.000
# 守護我們的祖國每一寸土地
It's all because of their protection of every single inch of soil of our Motherland,

0:06:31.380,0:06:33.360
# 才有我們今天的美好生活
that we can enjoy our beautiful and fruitful lives nowadays.

0:06:33.760,0:06:36.760
# 祝我們的國家繁榮昌盛  越來越強大
I wish our Motherland forever prosperity, and endless blossoming.
