### ISSUE TITLE
[华农兄弟] 华农兄弟新场门口出现一窝黄蜂太吓人了把它捅下来吃掉 - https://youtu.be/KYlTuvw1Tcw

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1343]
https://youtu.be/KYlTuvw1Tcw
<p>&#35270;&#39057;&#21457;&#24067;&#20110; August 3, 2020 at 01:08PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/KYlTuvw1Tcw

#华农兄弟：新场门口出现一窝黄蜂，太吓人了，把它捅下来吃掉
#Huanong Brothers: A nest of wasps appears on the door at our new site. Sacry! We poke it down and eat them.

0:00:00.000,0:00:02.720
# 大家好  很久都沒來這個新廠房啦  你看
Hi everyone! I haven't been to this new site for a pretty long time. Look!

0:00:02.980,0:00:03.780
# 現在都
Now,

0:00:04.680,0:00:06.460
# 到處都是那個  雜草從生
the weed is, the weed is growing everything.

0:00:06.980,0:00:09.260
# 而且這門口上有一個那麼大的黃蜂窩
And there's also such a big nest of wasps in front of the door.

0:00:09.960,0:00:12.940
# 今天要進  進裡面  你看這個黃蜂擋住了路
We're gonna get, get inside today. Look! The wasps are blocking our way.

0:00:13.840,0:00:15.020
# 要把它捅下來喲
I gotta poke it down.

0:00:31.280,0:00:33.940
# 你看 那些黃蜂  它們都好激動啊
Have a look at those wasps! They're so excited.

0:00:34.300,0:00:35.480
# 一直都在那盤旋
They keep circling around over there,

0:00:35.880,0:00:36.600
# 看著我
staring at me.

0:00:38.440,0:00:41.000
# 等一下 我來  等下我來接  讓它們  讓他們的
A moment. I'm gonna, I'll tackle them in a while. Let them, let their,

0:00:41.380,0:00:42.640
# 情緒先恢復一下
their emotion cool down a bit first.

0:00:43.280,0:00:45.600
# 你看  到處都是  東飛西飛的
Look! They're everywhere, flying here and there.

0:00:53.540,0:00:55.280
# 好多子啊  到這邊來
There are a lot of larvae and pupae. Let's go to this side.

0:00:56.240,0:00:58.380
# 你看  這裡飛出  飛來一個
Look! A wasp is flying, flying from here.

0:00:59.320,0:01:00.320
# 幸好它沒看到我
Fortunately, it can't see me.

0:01:00.980,0:01:01.860
# 太嚇人啦
It's scary!

0:01:02.860,0:01:04.240
# 突然之間跑過來的哦
It popped up all of a sudden, you know.

0:01:07.980,0:01:11.040
# 不是我  不是我把你的窩捅下來的
It was not me. I didn't poke your nest down.

0:01:12.400,0:01:14.640
# 是那個棍子 別找我哦
It was that rod. So leave me alone!

0:01:19.780,0:01:21.200
# 你看  這些蜂蛹  你看
Look! These are the pupae, look!

0:01:21.680,0:01:22.480
# 都還有好多
There are still a lot.

0:01:23.740,0:01:25.020
# 這可以直接吃的哦
These can be eaten right away, you know.

0:01:26.560,0:01:27.740
# 問你敢不敢吃
The problem is whether you dare or not.

0:01:27.880,0:01:29.480
# 我是還小的時候吃了好多
I did eat a lot when I was small.

0:01:30.100,0:01:30.680
# 就是
It's like,

0:01:31.580,0:01:33.320
# 優質的蛋白質來源
a source of high quality protein.

0:01:35.280,0:01:36.980
# 你看  這個蜂蛹 看  就這種
Look! This is a pupa. It looks like this.

0:01:37.760,0:01:38.500
# 很好吃的
It tastes really good.

0:01:40.500,0:01:41.920
# 不能咬哦 一咬就
Make sure that you don't chew it. If you do,

0:01:42.760,0:01:43.420
# 就那個
it would be, you know...

0:01:45.160,0:01:47.540
# 多吃幾個  可以哦  這個味道
Let me eat a few more. It's really not bad, the taste.

0:01:47.900,0:01:49.660
# 哎  出來  你看  就那麼
Ay! Get out! Look! Here it is.

0:01:49.920,0:01:51.940
# 就這樣的  這個還會動的  看到沒有
Here it is. It's, it's still moving. See?

0:01:52.740,0:01:56.020
# 這個要活吃哦  如果  你把它咬碎了就
It needs to be eaten alive. If you chew it, it would be,

0:01:56.400,0:01:59.140
# 太那個啦  是啊  就這樣直接吞掉就好啦
too, you know.. Yea, just swallow it right away.

0:02:07.420,0:02:08.780
# 不知道你們還小的時候有沒吃過
Have you ever eaten these things when you were small?

0:02:08.780,0:02:10.320
# 我還小吃了好多這樣的
I used to eat a lot when I was small,

0:02:10.880,0:02:11.600
# 黃蜂子
I mean wasps larvae and pupae.

0:02:15.120,0:02:15.820
# 這一個
This one...

0:02:16.640,0:02:19.100
# 這種用油炸一下也可以吃的哦  這個
They can also be fried in oil, these things.

0:02:24.100,0:02:25.060
# 你看  這裡也有
Look! Some more here

0:02:26.080,0:02:27.100
# 來  吃一個
C'mon! Take one!

0:02:27.240,0:02:28.860
# 誒  掉啦
Ey? It dropped.

0:02:29.400,0:02:30.340
# 這樣  等一下不要啦
Well, doesn't matter.

0:02:30.540,0:02:32.300
# 等叫那鴨子過來把它吃掉
I'll let the duck eat it in a while.

0:02:38.400,0:02:39.700
# 嗯  要不要吃一個
Um! You want one?

0:02:40.040,0:02:40.800
# 嘗一個
Try one!

0:02:41.860,0:02:43.240
# 看你口水都流出來啦
I see that you're already drooling.

0:02:46.000,0:02:47.440
# 上次我們吃的是那個
What we ate last time were the,

0:02:48.360,0:02:49.140
# 我們這邊叫
here we call them,

0:02:49.760,0:02:52.820
# 辣椒蜂  就是那個蟄一下那個  手很辣的
"chilli wasps". It's like its sting burns, burns the hand.

0:02:52.860,0:02:55.640
# 這種不一樣  這種是稍微比較大的  這個是真正的
But this one is different. These are larger. They're the authentic,

0:02:55.880,0:02:57.920
# 那個黃蜂來的  這大黃蜂
authentic wasps. These are big wasps.

0:03:02.740,0:03:04.080
# 這還有 幾個
Here are still, a few.

0:03:05.900,0:03:09.260
# 以前  蛋白質來源  以前家裡沒有肉吃
It was, a source or protein. We hardly had any meat at home in the past.

0:03:09.700,0:03:10.880
# 吃點  這個蛋白質
We ate this. Its protein,

0:03:11.500,0:03:12.600
# 它這挺好的
is in fact quite good.

0:03:13.740,0:03:15.680
# 還有幾個給那個小鴨子吃
The last few are left for the duckies.

0:03:17.480,0:03:19.560
# 你看  買了七八十隻鴨子回來
Look! I've bought around eighties ducks back here.

0:03:24.040,0:03:27.540
# 現在這個廠房一直都空著看  現在買了一些鴨子回來
This site has always been idled. So I've bought some ducks.

0:03:27.960,0:03:29.800
# 買了七八十隻鴨子放在這裡
I've bought seventy or eighty ducks and leave them here.

0:03:30.160,0:03:33.860
# 這個  呃  窗戶在外面啊  就是有幾個大魚塘
It's, eh, outside the windows, there's a couple of big ponds.

0:03:34.300,0:03:35.160
# 剛好它們
Right now they're here.

0:03:35.640,0:03:38.460
# 有空閒的時候就可以把它們趕到池塘裡面去
I can drive them to the ponds when I'm free.

0:03:45.600,0:03:46.520
# 看這有好吃的
I have something tasty here.

0:03:47.000,0:03:47.680
# 蟲子哦
Bugs!

0:03:48.380,0:03:50.580
# 蛋白質  營養豐富
Rich in protein, and nutritious

0:03:52.100,0:03:53.260
# 你們可能沒吃過
I bet it's your first time.

0:03:54.280,0:03:56.720
# 你看  嘗到味道啦 它們在搶
Look! Once they've tasted it, they're now fighting over it.

0:03:58.580,0:03:59.720
# 你看  這還有一個
Look! One more is here.

0:04:02.800,0:04:06.100
# 這鴨子還小的時候好可愛的哦  你看  那麼小就游泳
These ducks are really lovely when they're small. Look! Though they're so small, they can swim already.

0:04:06.800,0:04:07.860
# 長大了 就很好吃
And they'll be really tasty when they grow up.

0:04:12.540,0:04:14.200
# 至少養個四五個月
They need to be raised for about four or five months.

0:04:14.900,0:04:19.100
# 養  養不夠四五個月長不大  因為這個可能
Any, anything less than four or five months doesn't work at all. I think it's because,

0:04:19.260,0:04:21.220
# 到後面直接玉米給它吃
they're given corns right away at later stages.

0:04:21.620,0:04:22.860
# 不給飼料給它吃
No fodder is given.

0:04:23.560,0:04:27.300
# 週期長一點  但是  肉質還是可以的
The period becomes longer. But, the texture of the meat is not bad.

0:04:28.180,0:04:30.960
# 這個是土鴨子 長不了多大的  這個
These ducks are native here. They, they don't get really big.

0:04:34.180,0:04:38.320
# 你看  這裡還有一個黑色的鴨子  小黑  小黑鴨
Look! Here's a black duck, a little black, little black ducky.

0:04:38.320,0:04:41.560
# 看到沒有 在那裡  我都沒發現  抓的時候
See? It's over there. I didn't notice it when I was picking them.

0:04:44.720,0:04:47.360
# 讓它們慢慢慢慢的就習慣這裡啦
Little by little, they'll get used to this place.

0:04:47.360,0:04:49.420
# 在這裡放回去  它們自己會回家
Then I can release them. They''ll know their way home.

0:04:50.040,0:04:51.920
# 這裡好多草啊  到處都是
Here's a lot of grass. It's everywhere.

0:05:01.840,0:05:03.540
# 哎呀  這樣都沒抓到你
Aya! How can you escape from me?

0:05:05.660,0:05:08.540
# 你看  這吃的好飽啊  看到沒  這都鼓起來啦
Look! It has eaten a lot! See? It's popping out here.

0:05:10.160,0:05:10.920
# 那麼小
It's so small.

0:05:14.420,0:05:16.640
# 你看  它口水都流出來啦  看到沒有
Look! It's drooling. See?

0:05:17.040,0:05:18.320
# 我也流出來啦
And I'm drooling too.

0:05:18.540,0:05:21.280
# 你還小  好可愛啊  還小的時候
You're still small. It's so lovely, when it's small.

0:05:21.440,0:05:23.400
# 誒喲  既然吐口水給我
Ayo! It spits on me!

0:05:23.560,0:05:24.660
# 那麼壞你
You're so naughty!

0:05:24.820,0:05:25.600
# 放了你
I let you go.

0:05:31.560,0:05:33.940
# 都一群一群的  它不會單獨分開的
They're always in a herd. There's no lone duck.

0:05:38.540,0:05:41.320
# 養大啦  好大啦  是個  整個都是滿的
When they grow up, they'll b really big. Yea, they'll occupy the whole room here.

0:05:41.920,0:05:44.820
# 每天餵一點給它吃就可以啦  不用餵那麼多的
A little bit of food every day is enough, not too much.

0:05:45.080,0:05:46.000
# 它也跑不了
They can't run away anyway.

0:05:46.900,0:05:50.980
# 一下子餵多一點啊  讓它們夠吃一天的量就可以啦
A little bit more at a time, enough for a whole day, is everything needed.

0:05:52.640,0:05:54.120
# 好啦  現在回去啦
Alright! We're going back now.
