### ISSUE TITLE
[老飯骨] 香辣土豆丝 -https://youtu.be/YFE6_MR5VP4

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1352]
**视频链接**：https://youtu.be/YFE6_MR5VP4
抖音参考链接：
香辣土豆丝： https://v.douyin.com/JjvDE2j/
炒糖色： https://v.douyin.com/JjvuyxQ/

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•香辣土豆丝】咸香酥脆，香辣土豆丝也能做出国宴的味道！家常易学，用料超简单！炒糖色|老饭骨

简介
小友们好，老饭骨今天带给大家一道特别简单的家常菜——香辣土豆丝。
大家可别小瞧了这土豆丝，把家常菜做好了，也能上国宴！
这道菜用料非常简单，所有材料家里都能找到，小友们一定要动手试试！
不要忘了来“老饭骨”公众号和Facebook交作业咯！大爷和二伯已经收集了很多大家伙的作品了，感谢小友们对老饭骨的支持，说不定你的作品就出现在下支视频里了！
片尾大爷还给大家带来炒糖色的一些小常识，记得关注哦！

字幕
1
00:00:00,000 --> 00:00:01,880
这家伙 哪个外国总统（来了）

2
00:00:01,880 --> 00:00:05,280
别给上牛扒 来盘土豆丝儿 吃美了

3
00:00:05,280 --> 00:00:06,840
 

4
00:00:06,840 --> 00:00:09,160

5
00:00:09,160 --> 00:00:10,640
土豆丝我提前切出来了

6
00:00:10,640 --> 00:00:12,800
辣椒面待会耗个小红油

7
00:00:12,800 --> 00:00:14,880
两种辣椒面 细辣椒面跟粗辣椒面

8
00:00:14,880 --> 00:00:16,640
芝麻也给炒出来了 熟芝麻

9
00:00:16,640 --> 00:00:18,720
香菜呢 香菜切好了

10
00:00:18,720 --> 00:00:21,160
别使这香菜 别使叶儿

11
00:00:21,160 --> 00:00:23,280
就用点梗才漂亮呢出来

12
00:00:23,280 --> 00:00:25,280
来 咱们先炸点红油

13
00:00:25,280 --> 00:00:28,320
第一步 葱的下脚料 炼点小葱油

14
00:00:30,240 --> 00:00:34,320
往里头稍微加点水 辣椒面加水

15
00:00:34,320 --> 00:00:36,560
它不容易糊 这是个小窍门

16
00:00:36,560 --> 00:00:38,520
咱们炸一个简易版的小红油

17
00:00:38,520 --> 00:00:41,920
拿热油沏上辣椒面

18
00:00:41,920 --> 00:00:46,120

19
00:00:46,120 --> 00:00:49,080
耗上 开始咱们准备炸土豆丝

20
00:00:50,040 --> 00:00:52,680
咱把土豆丝水空出去

21
00:00:52,800 --> 00:00:54,760
八成油温 咱就少下

22
00:00:54,760 --> 00:00:56,640
分两锅到三锅

23
00:00:56,640 --> 00:00:58,800

24
00:00:59,920 --> 00:01:02,640
这个我们要跟网友提示一下

25
00:01:02,640 --> 00:01:05,040
土豆丝要漂漂水

26
00:01:05,040 --> 00:01:07,440
因为里边的含粉量比较高

27
00:01:07,440 --> 00:01:09,960
不漂水的话一会就上色了

28
00:01:09,960 --> 00:01:13,160
刚才我这个冲了有半小时

29
00:01:13,160 --> 00:01:15,640
在家为了省水换水也可以

30
00:01:15,640 --> 00:01:17,920
这个油温就是八成油温

31
00:01:17,920 --> 00:01:19,480
在咱家的灶就是大火

32
00:01:19,480 --> 00:01:21,800
在饭店的时候就是小火 沁炸

33
00:01:21,800 --> 00:01:24,040
炸成金黄色 把水分给它逼出去

34
00:01:24,040 --> 00:01:26,200
您这也差不多了 漂起来

35
00:01:26,200 --> 00:01:28,400
必须垫厨房用纸 吸油

36
00:01:28,400 --> 00:01:30,800
看着油多 其实没那么多油

37
00:01:30,800 --> 00:01:33,280
所以说油温必须得够

38
00:01:33,280 --> 00:01:37,440
土豆丝炸好了啊 金黄色

39
00:01:37,440 --> 00:01:39,760
刚才师父说了 香菜得用梗

40
00:01:39,760 --> 00:01:42,600
香菜梗清爽利落 叶容易塌

41
00:01:42,600 --> 00:01:44,760
会影响菜的美观

42
00:01:44,760 --> 00:01:45,720
寸段

43
00:01:45,720 --> 00:01:48,240

44
00:01:48,240 --> 00:01:48,960
行了

45
00:01:48,960 --> 00:01:50,760

46
00:01:50,760 --> 00:01:54,800
辣椒段 小火慢慢煸一下

47
00:01:54,800 --> 00:01:56,360
这会儿关火了开始

48
00:01:56,360 --> 00:01:57,360
关火一定关火

49
00:01:57,360 --> 00:01:59,400

50
00:01:59,400 --> 00:02:01,920
土豆丝下锅 加味喽

51
00:02:01,920 --> 00:02:04,880
白糖

52
00:02:04,880 --> 00:02:06,760
盐 少了点再来一点

53
00:02:06,760 --> 00:02:08,720

54
00:02:08,720 --> 00:02:11,360
为什么关火 开着火就糊了

55
00:02:11,360 --> 00:02:13,480
这土豆丝本身就是熟的了

56
00:02:13,480 --> 00:02:15,480
白胡椒粉

57
00:02:15,480 --> 00:02:18,000

58
00:02:18,000 --> 00:02:19,920
少搁点香油

59
00:02:19,920 --> 00:02:22,160
香油来点

60
00:02:22,160 --> 00:02:25,520
这时候葱丝该撒上了

61
00:02:26,080 --> 00:02:28,160
红油搁不搁啊 待会搁师父

62
00:02:28,160 --> 00:02:29,640
搁吧现在

63
00:02:29,640 --> 00:02:32,400
红油搁的时候咱得用一下篦子

64
00:02:32,400 --> 00:02:34,720
少撒点红油

65
00:02:34,720 --> 00:02:39,720

66
00:02:39,720 --> 00:02:42,880
香菜 扒拉扒拉就出来了

67
00:02:42,880 --> 00:02:44,720
这时候开一下大火

68
00:02:44,720 --> 00:02:47,160

69
00:02:47,160 --> 00:02:48,440
稍微一颠就行了

70
00:02:48,440 --> 00:02:50,520
香菜的味都出来了

71
00:02:50,520 --> 00:02:53,560
金黄色  这时候该关火了

72
00:02:53,560 --> 00:02:56,240
撒上熟芝麻 刚才我炒的 出锅了

73
00:02:56,240 --> 00:02:58,040

74
00:02:58,040 --> 00:02:59,680
水一定擦出去

75
00:02:59,680 --> 00:03:01,800

76
00:03:03,680 --> 00:03:05,320
听着就酥脆

77
00:03:05,320 --> 00:03:07,720
你看搁点颜色（红油）对了吧

78
00:03:08,120 --> 00:03:09,920
为什么是香辣土豆丝啊

79
00:03:09,920 --> 00:03:12,760
插一筷子它就不爱倒了

80
00:03:12,760 --> 00:03:15,480
就跟盖房子似的 有根龙骨了

81
00:03:16,120 --> 00:03:18,080
这龙骨就是大爷

82
00:03:18,080 --> 00:03:20,440
咱再轻轻的给拿下来

83
00:03:20,440 --> 00:03:22,520
好了 齐活

84
00:03:22,520 --> 00:03:24,000
您老哥俩尝尝

85
00:03:24,000 --> 00:03:27,520

86
00:03:27,520 --> 00:03:28,240
好吃

87
00:03:28,240 --> 00:03:31,800

88
00:03:31,800 --> 00:03:37,960
酥脆 咸香 微辣 葱香 香菜香

89
00:03:37,960 --> 00:03:39,720
芝麻的香 辣椒的香

90
00:03:39,720 --> 00:03:41,680
红油的香 土豆的脆

91
00:03:41,680 --> 00:03:42,840
很普通一个土豆丝

92
00:03:42,840 --> 00:03:45,160
能做的这么精彩 这么有味道

93
00:03:45,160 --> 00:03:46,600
虽然国宴菜是国宴菜

94
00:03:46,600 --> 00:03:48,800
但是我们要把家常菜做好了

95
00:03:48,800 --> 00:03:49,760
也能上国宴

96
00:03:49,760 --> 00:03:50,720

97
00:03:50,720 --> 00:03:52,320
这家伙哪个外国总统（来了）

98
00:03:52,320 --> 00:03:53,560
别给上牛扒

99
00:03:53,560 --> 00:03:55,640
来盘土豆丝 吃美了

100
00:03:55,640 --> 00:03:57,320

101
00:04:00,320 --> 00:04:01,040
这网友问说

102
00:04:01,040 --> 00:04:03,120
能讲讲炒糖色吗

103
00:04:03,120 --> 00:04:04,880
还有拔丝炒糖

104
00:04:04,880 --> 00:04:06,200
老是操作不好

105
00:04:06,200 --> 00:04:07,320
炒糖色的

106
00:04:07,320 --> 00:04:10,200
糖最好用冰糖

107
00:04:10,200 --> 00:04:12,600
它出来以后颜色红亮

108
00:04:12,600 --> 00:04:15,080
说如果没有冰糖怎么办

109
00:04:15,080 --> 00:04:16,520
我们就用棉白糖

110
00:04:16,520 --> 00:04:17,880
或者是砂糖

111
00:04:17,880 --> 00:04:19,680
如果是棉白糖的话

112
00:04:19,680 --> 00:04:22,120
就锅底儿把锅要烧好

113
00:04:22,120 --> 00:04:22,960
溜一溜

114
00:04:22,960 --> 00:04:24,680
放点底油

115
00:04:24,680 --> 00:04:26,080
把绵白糖下锅

116
00:04:26,080 --> 00:04:27,400
因为你的锅是热锅

117
00:04:27,400 --> 00:04:29,080
要凉油

118
00:04:29,080 --> 00:04:31,240
所以刚开始起火的时候

119
00:04:31,240 --> 00:04:33,160
别太大 等糖化了以后

120
00:04:33,160 --> 00:04:35,080
它冒的是大泡

121
00:04:35,080 --> 00:04:36,200
白色的

122
00:04:36,200 --> 00:04:38,160
然后慢慢的经过加温

123
00:04:38,160 --> 00:04:39,600
开始变中火

124
00:04:39,600 --> 00:04:41,520
这糖就开始变色了

125
00:04:41,520 --> 00:04:42,520
有点黄色的了

126
00:04:42,520 --> 00:04:46,640
这个节骨眼是拔丝的火候

127
00:04:46,640 --> 00:04:47,720
继续往下找

128
00:04:47,720 --> 00:04:49,760
炒的跟酱油色似的

129
00:04:49,760 --> 00:04:51,360
有点冒烟了

130
00:04:51,360 --> 00:04:52,240
好

131
00:04:52,240 --> 00:04:54,160
这时候旁边准备一点

132
00:04:54,160 --> 00:04:56,280
温水

133
00:04:56,280 --> 00:04:57,640
一看冒烟了

134
00:04:57,640 --> 00:04:59,280
色也跟酱油色似的

135
00:04:59,280 --> 00:05:00,600
把水迅速的倒进去

136
00:05:00,600 --> 00:05:02,160
这就是糖色

137
00:05:02,160 --> 00:05:03,880
但是糖色这个环节

138
00:05:03,880 --> 00:05:06,240
这糖拿勺搅起来

139
00:05:06,240 --> 00:05:09,200
很快就回落到锅心里面去了

140
00:05:09,200 --> 00:05:10,440
不是那种冒泡的了

141
00:05:10,440 --> 00:05:11,600
就特别稀

142
00:05:11,600 --> 00:05:13,480
而且颜色也很重

143
00:05:13,480 --> 00:05:14,560
而且还冒烟

144
00:05:14,560 --> 00:05:16,560
过了火就有点发苦

145
00:05:16,560 --> 00:05:18,760
先把糖色取出来

146
00:05:18,760 --> 00:05:21,280
然后我们再把肉解（冻）好了

147
00:05:21,280 --> 00:05:23,040
然后再回锅再炒

148
00:05:23,040 --> 00:05:24,800
逐渐的再加强起来

149
00:05:24,800 --> 00:05:27,800
这糖色就炒好了

150
00:05:27,800 --> 00:05:29,440


```

**Comment by brainshawn** [comment]
认领

**Comment by brainshawn** [comment]
[老飯骨] 香辣土豆丝 -https://youtu.be/YFE6_MR5VP4 #1352



标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•香辣土豆丝】咸香酥脆，香辣土豆丝也能做出国宴的味道！家常易学，用料超简单！炒糖色|老饭骨
[State Banquet Master Chef: aromatic and spicy shredded potato] Salty, aromatic and crispy, the taste from the state banquet! Super simple ingredients and easy to learn! (learn making caramelized sugar in the end)

简介
小友们好，老饭骨今天带给大家一道特别简单的家常菜——香辣土豆丝。
大家可别小瞧了这土豆丝，把家常菜做好了，也能上国宴！
这道菜用料非常简单，所有材料家里都能找到，小友们一定要动手试试！
不要忘了来“老饭骨”公众号和Facebook交作业咯！大爷和二伯已经收集了很多大家伙的作品了，感谢小友们对老饭骨的支持，说不定你的作品就出现在下支视频里了！
片尾大爷还给大家带来炒糖色的一些小常识，记得关注哦！
Hello friends, today we introduce a super simple homestyle dish -- aromatic and spicy shredded potatoes.
Don’t look down on shredded potato, because it can also show up in the state banquet if well cooked!
The ingredients are very simple, and can be easily found at home, so we strongly recommend to have a try!
Don’t forget to upload your homework to our WeChat and Facebook accounts! Da Ye and Er Bai have collected lots of homeworks from our friends. Very appreciated to your support -- maybe your homework would show up in our next video!
At the end of this video, Da Ye also introduces the common sense to make caramelized sugar. It's worth your concern!


字幕
1
00:00:00,000 --> 00:00:01,880
这家伙 哪个外国总统（来了）
When a foreign president (comes)

2
00:00:01,880 --> 00:00:05,280
别给上牛扒 来盘土豆丝儿 吃美了
Don’t serve steak, but instead shredded potato; that’s wonderful

5
00:00:09,160 --> 00:00:10,640
土豆丝我提前切出来了
I have shredded potatoes in advance

6
00:00:10,640 --> 00:00:12,800
辣椒面待会耗个小红油
The chili powder will be used to make red chili oil

7
00:00:12,800 --> 00:00:14,880
两种辣椒面 细辣椒面跟粗辣椒面
Two different types of chili powder, fine- and coarse-grained

8
00:00:14,880 --> 00:00:16,640
芝麻也给炒出来了 熟芝麻
The sesame has been cooked

9
00:00:16,640 --> 00:00:18,720
香菜呢 香菜切好了
How about the cilantro? Already cut

10
00:00:18,720 --> 00:00:21,160
别使这香菜 别使叶儿
Don’t use cilantro leaves

11
00:00:21,160 --> 00:00:23,280
就用点梗才漂亮呢出来
The dish is more beautiful if we only use cilantro stems

12
00:00:23,280 --> 00:00:25,280
来 咱们先炸点红油
Okay, let’s cook some read chili oil first

13
00:00:25,280 --> 00:00:28,320
第一步 葱的下脚料 炼点小葱油
Firstly, the unused green onion parts, to make some onion oil

14
00:00:30,240 --> 00:00:34,320
往里头稍微加点水 辣椒面加水
Add a little water into the chili powder

15
00:00:34,320 --> 00:00:36,560
它不容易糊 这是个小窍门
A tip to avoid burnt

16
00:00:36,560 --> 00:00:38,520
咱们炸一个简易版的小红油
Let’s make a simple version of red chili oil

17
00:00:38,520 --> 00:00:41,920
拿热油沏上辣椒面
Pour the hot oil on the chili powder

19
00:00:46,120 --> 00:00:49,080
耗上 开始咱们准备炸土豆丝
Let’s prepare for frying the shredded potatoes

20
00:00:50,040 --> 00:00:52,680
咱把土豆丝水空出去
Let’s pour the water away

21
00:00:52,800 --> 00:00:54,760
八成油温 咱就少下
Eighty percent of the oil temperature, so let’s fry less initially

22
00:00:54,760 --> 00:00:56,640
分两锅到三锅
Fry 2 or 3 times

24
00:00:59,920 --> 00:01:02,640
这个我们要跟网友提示一下
Here I want to hint our friends

25
00:01:02,640 --> 00:01:05,040
土豆丝要漂漂水
The shredded potatoes must have been washed

26
00:01:05,040 --> 00:01:07,440
因为里边的含粉量比较高
Because potatoes have too much starch inside

27
00:01:07,440 --> 00:01:09,960
不漂水的话一会就上色了
The color will be changed very soon if the potatoes have not has been washed

28
00:01:09,960 --> 00:01:13,160
刚才我这个冲了有半小时
I have flushed them with water for about half an hour

29
00:01:13,160 --> 00:01:15,640
在家为了省水换水也可以
When at home,we could also wash them and change water several times to save water 

30
00:01:15,640 --> 00:01:17,920
这个油温就是八成油温
The oil temperature is eighty percent

31
00:01:17,920 --> 00:01:19,480
在咱家的灶就是大火
When cooking at home, we use large heat power 

32
00:01:19,480 --> 00:01:21,800
在饭店的时候就是小火 沁炸
While in restaurant, we use small heat power

33
00:01:21,800 --> 00:01:24,040
炸成金黄色 把水分给它逼出去
Fry to golden color, to get rid of the water

34
00:01:24,040 --> 00:01:26,200
您这也差不多了 漂起来
Looks almost done, take them out

35
00:01:26,200 --> 00:01:28,400
必须垫厨房用纸 吸油
Must use kitchen towel to absorb oil

36
00:01:28,400 --> 00:01:30,800
看着油多 其实没那么多油
The oil looks very much, but actually not

37
00:01:30,800 --> 00:01:33,280
所以说油温必须得够
So the oil temperature must be high enough

38
00:01:33,280 --> 00:01:37,440
土豆丝炸好了啊 金黄色
The frying is done, golden color

39
00:01:37,440 --> 00:01:39,760
刚才师父说了 香菜得用梗
Master just said, we must use cilantro stems instead of leaves

40
00:01:39,760 --> 00:01:42,600
香菜梗清爽利落 叶容易塌
Cilantro stems make the dish look more clean, while leaves is contrary

41
00:01:42,600 --> 00:01:44,760
会影响菜的美观
Will affect the beauty of the dish

42
00:01:44,760 --> 00:01:45,720
寸段
Cut into cun (~3.3 cm)

44
00:01:48,240 --> 00:01:48,960
行了
Okay


46
00:01:50,760 --> 00:01:54,800
辣椒段 小火慢慢煸一下
Chili segments, cook a little with low heat power

47
00:01:54,800 --> 00:01:56,360
这会儿关火了开始
Turn off heating

48
00:01:56,360 --> 00:01:57,360
关火一定关火
Must turn off heating

50
00:01:59,400 --> 00:02:01,920
土豆丝下锅 加味喽
Add the shredded potatoes into the pot, now begin to add seasoning

51
00:02:01,920 --> 00:02:04,880
白糖
Sugar

52
00:02:04,880 --> 00:02:06,760
盐 少了点再来一点
Salt, not enough, add a little more

54
00:02:08,720 --> 00:02:11,360
为什么关火 开着火就糊了
Why turn off heating? Otherwise the shredded potatoes will be burnt

55
00:02:11,360 --> 00:02:13,480
这土豆丝本身就是熟的了
Note that the shredded potatoes have already been cooked

56
00:02:13,480 --> 00:02:15,480
白胡椒粉
White pepper powder

58
00:02:18,000 --> 00:02:19,920
少搁点香油
A little sesame oil

59
00:02:19,920 --> 00:02:22,160
香油来点
A little

60
00:02:22,160 --> 00:02:25,520
这时候葱丝该撒上了
Now add the cut leaves of green onion

61
00:02:26,080 --> 00:02:28,160
红油搁不搁啊 待会搁师父
Whether to add the red chilli oil now? Add it soon, master

62
00:02:28,160 --> 00:02:29,640
搁吧现在
Now add the red chilli oil

63
00:02:29,640 --> 00:02:32,400
红油搁的时候咱得用一下篦子
We need to use a fine-toothed comb

64
00:02:32,400 --> 00:02:34,720
少撒点红油
Don’t add too much red chilli oil

66
00:02:39,720 --> 00:02:42,880
香菜 扒拉扒拉就出来了
Add cilantro, just mix them up to finish the cooking

67
00:02:42,880 --> 00:02:44,720
这时候开一下大火
Now use high heating power

69
00:02:47,160 --> 00:02:48,440
稍微一颠就行了
Just toss the wok several times

70
00:02:48,440 --> 00:02:50,520
香菜的味都出来了
The smell of cilantro is out

71
00:02:50,520 --> 00:02:53,560
金黄色  这时候该关火了
Golden color, now turn off the heating

72
00:02:53,560 --> 00:02:56,240
撒上熟芝麻 刚才我炒的 出锅了
Scatter the sesame I cooked just now, done

74
00:02:58,040 --> 00:02:59,680
水一定擦出去
Must get rid of the water

76
00:03:03,680 --> 00:03:05,320
听着就酥脆
Listen already crispy

77
00:03:05,320 --> 00:03:07,720
你看搁点颜色（红油）对了吧
Look, it makes sense to add some color (red chilli oil)

78
00:03:08,120 --> 00:03:09,920
为什么是香辣土豆丝啊
Why aromatic and spicy shredded potato

79
00:03:09,920 --> 00:03:12,760
插一筷子它就不爱倒了
Look, it won’t collapse if we insert a chopstick

80
00:03:12,760 --> 00:03:15,480
就跟盖房子似的 有根龙骨了
Just like building a house, it has a keel

81
00:03:16,120 --> 00:03:18,080
这龙骨就是大爷
Da Ye is the keel

82
00:03:18,080 --> 00:03:20,440
咱再轻轻的给拿下来
Let’s take the keel away lightly

83
00:03:20,440 --> 00:03:22,520
好了 齐活
Okay, done

84
00:03:22,520 --> 00:03:24,000
您老哥俩尝尝
You two brothers have a taste

86
00:03:27,520 --> 00:03:28,240
好吃
Delicious

88
00:03:31,800 --> 00:03:37,960
酥脆 咸香 微辣 葱香 香菜香
Crispy, a little spicy, mixed aroma of salt, green onion and cilantro

89
00:03:37,960 --> 00:03:39,720
芝麻的香 辣椒的香
And the aroma of sesame and chili

90
00:03:39,720 --> 00:03:41,680
红油的香 土豆的脆
The aroma of red chili oil, the crisp of potatoes

91
00:03:41,680 --> 00:03:42,840
很普通一个土豆丝
An ordinary shredded potato dish

92
00:03:42,840 --> 00:03:45,160
能做的这么精彩 这么有味道
So wonderful and delicious

93
00:03:45,160 --> 00:03:46,600
虽然国宴菜是国宴菜
Even though state banquet dishes are from the state banquet

94
00:03:46,600 --> 00:03:48,800
但是我们要把家常菜做好了
But if we could cook homestyle dishes well

95
00:03:48,800 --> 00:03:49,760
也能上国宴
They can also show up in the state banquet

97
00:03:50,720 --> 00:03:52,320
这家伙哪个外国总统（来了）
So if a foreign president (comes)

98
00:03:52,320 --> 00:03:53,560
别给上牛扒
Don’t server steak

99
00:03:53,560 --> 00:03:55,640
来盘土豆丝 吃美了
But instead shredded potato; that’s wonderful

101
00:04:00,320 --> 00:04:01,040
这网友问说
Some friends ask

102
00:04:01,040 --> 00:04:03,120
能讲讲炒糖色吗
Can you introduce how to make caramelized sugar

103
00:04:03,120 --> 00:04:04,880
还有拔丝炒糖
And crisp frying with syrup

104
00:04:04,880 --> 00:04:06,200
老是操作不好
Always fail

105
00:04:06,200 --> 00:04:07,320
炒糖色的
To make caramelized sugar

106
00:04:07,320 --> 00:04:10,200
糖最好用冰糖
It’s better to use white rock sugar

107
00:04:10,200 --> 00:04:12,600
它出来以后颜色红亮
The final color will be more red and light

108
00:04:12,600 --> 00:04:15,080
说如果没有冰糖怎么办
What if we don’t have white rock sugar

109
00:04:15,080 --> 00:04:16,520
我们就用棉白糖
We could choose cotton sugar

110
00:04:16,520 --> 00:04:17,880
或者是砂糖
Or the granulated sugar

111
00:04:17,880 --> 00:04:19,680
如果是棉白糖的话
If cotton sugar

112
00:04:19,680 --> 00:04:22,120
就锅底儿把锅要烧好
We first need to heat the pot

113
00:04:22,120 --> 00:04:22,960
溜一溜
Make the pot hot enough

114
00:04:22,960 --> 00:04:24,680
放点底油
Then add some base oil

115
00:04:24,680 --> 00:04:26,080
把绵白糖下锅
Add cotton sugar

116
00:04:26,080 --> 00:04:27,400
因为你的锅是热锅
Because your pot is hot

117
00:04:27,400 --> 00:04:29,080
要凉油
You need cold oil

118
00:04:29,080 --> 00:04:31,240
所以刚开始起火的时候
So at the beginning of cooking

119
00:04:31,240 --> 00:04:33,160
别太大 等糖化了以后
Don’t use high heating power; when the sugar becomes melted

120
00:04:33,160 --> 00:04:35,080
它冒的是大泡
It has big bubble initially

121
00:04:35,080 --> 00:04:36,200
白色的
White

122
00:04:36,200 --> 00:04:38,160
然后慢慢的经过加温
After heating slowly

123
00:04:38,160 --> 00:04:39,600
开始变中火
Change to medium heating power

124
00:04:39,600 --> 00:04:41,520
这糖就开始变色了
Then the sugar color begins to change

125
00:04:41,520 --> 00:04:42,520
有点黄色的了
A little yellow

126
00:04:42,520 --> 00:04:46,640
这个节骨眼是拔丝的火候
At this moment it’s the perfect time for crisp frying with syrup

127
00:04:46,640 --> 00:04:47,720
继续往下找
But if you continue heat

128
00:04:47,720 --> 00:04:49,760
炒的跟酱油色似的
The sugar color will become like soy sauce

129
00:04:49,760 --> 00:04:51,360
有点冒烟了
And even begins to smoke

130
00:04:51,360 --> 00:04:52,240
好
Okay

131
00:04:52,240 --> 00:04:54,160
这时候旁边准备一点
Now prepare some

132
00:04:54,160 --> 00:04:56,280
温水
Warm water

133
00:04:56,280 --> 00:04:57,640
一看冒烟了
Once it begins to smoke

134
00:04:57,640 --> 00:04:59,280
色也跟酱油色似的
And the color looks like soy sauce

135
00:04:59,280 --> 00:05:00,600
把水迅速的倒进去
Pour the warm water in immediately

136
00:05:00,600 --> 00:05:02,160
这就是糖色
This is the so-called caramelized sugar

137
00:05:02,160 --> 00:05:03,880
但是糖色这个环节
But during making caramelized sugar

138
00:05:03,880 --> 00:05:06,240
这糖拿勺搅起来
If you try to mix the sugar with a wok spoon

139
00:05:06,240 --> 00:05:09,200
很快就回落到锅心里面去了
You will find the sugar falls back the middle of pot very fast

140
00:05:09,200 --> 00:05:10,440
不是那种冒泡的了
It’s not like bubbling anymore

141
00:05:10,440 --> 00:05:11,600
就特别稀
It is very sparse

142
00:05:11,600 --> 00:05:13,480
而且颜色也很重
And the color is also very deep

143
00:05:13,480 --> 00:05:14,560
而且还冒烟
And it smokes

144
00:05:14,560 --> 00:05:16,560
过了火就有点发苦
It will become bitter if overcooked

145
00:05:16,560 --> 00:05:18,760
先把糖色取出来
We could take the cooked caramelized sugar out first

146
00:05:18,760 --> 00:05:21,280
然后我们再把肉解（冻）好了
And after we thaw the meat

147
00:05:21,280 --> 00:05:23,040
然后再回锅再炒
Then put the caramelized sugar back to cook

148
00:05:23,040 --> 00:05:24,800
逐渐的再加强起来
Enhance gradually

149
00:05:24,800 --> 00:05:27,800
这糖色就炒好了
The caramelized sugar is done
