### ISSUE TITLE
[雪鱼探店] 宁夏羊脖子 - https://youtu.be/_QkEdBPHYUA

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#1358]
**视频链接**：<https://youtu.be/_QkEdBPHYUA>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
宁夏特色美食凉羊脖子，直接清水煮，出锅只撒盐就很好吃

简介
宁夏滩羊味道鲜美，口感不膻不腻，做手抓羊肉只需要清水炖煮，稍微加一些葱姜即可，出锅时候斩大块摆盘，最后撒上椒盐就可以上桌。羊肋排肥瘦相间，肉质软烂，一口下去羊肉味道十足，配合一碟醋蒜汁，味道更美。高级一点的吃货会对羊脖子青睐有加！羊脖子同手抓羊肉一锅炖出来，只不过出锅时间会晚一个小时，出锅后的羊脖子放入冰箱冷藏，冷藏后的羊脖子极易切片，大刀切开，状如雪花，夹起来吃一口，口感细腻入微，入口即化，神仙口感，而此时，几乎不用任何蘸料就觉得美味。

字幕
1 
00:00:06,880 --> 00:00:09,040
哈喽 雪鱼现在在银川

2 
00:00:09,040 --> 00:00:12,400
有句话叫做 吃在吴忠 游在银川

3 
00:00:12,400 --> 00:00:15,040
这次我专门来银川 耍一耍

4 
00:00:15,040 --> 00:00:17,960
在吴忠的时候 我吃了早茶 吃了羊杂

5 
00:00:17,960 --> 00:00:20,400
但是还有一种 手抓 没有尝到

6 
00:00:20,400 --> 00:00:24,080
这次来银川呢 先把没有吃到手抓的遗憾弥补掉吧

7 
00:00:24,080 --> 00:00:27,120
很多吴忠的手抓店 在银川这边也会有的

8 
00:00:27,120 --> 00:00:30,400
前一段时间 我刚在西宁这边吃过手抓羊排

9 
00:00:30,400 --> 00:00:32,240
不过同在西北

10 
00:00:32,240 --> 00:00:37,200
宁夏的手抓和西宁的手抓还是有很大区别的

11 
00:00:52,040 --> 00:00:56,240
这正好是遇上 羊肉刚出锅

12 
00:00:56,240 --> 00:00:57,720
这个锅盖一打开

13 
00:00:57,720 --> 00:01:01,680
羊肉的香味立刻飘过来冲击到脑子里

14 
00:01:06,760 --> 00:01:11,160
大哥 我问一下 这里面主要是羊什么部位的肉

15 
00:01:11,160 --> 00:01:16,480
主要是羊的前排 前羊排

16 
00:01:19,200 --> 00:01:20,800
这一锅大约能有多少斤

17 
00:01:20,800 --> 00:01:23,800
这一锅达到140斤

18 
00:01:37,000 --> 00:01:38,920
炖羊肉的汤里没有什么大料包

19 
00:01:38,920 --> 00:01:41,320
只有简单的葱姜这样的调味品

20 
00:01:41,320 --> 00:01:45,200
这么看着真的是 汤上面只是泛着一层清油

21 
00:01:45,200 --> 00:01:48,680
仔细看看汤 汤还是很白的

22 
00:02:07,520 --> 00:02:09,880
锅里是几乎不加盐的

23 
00:02:09,880 --> 00:02:13,360
炖的时候 羊汤的锅里几乎是不加盐的

24 
00:02:13,640 --> 00:02:16,800
这个锅里除了比较明显能够看到的羊排

25 
00:02:16,800 --> 00:02:19,920
还有一个不能不说

26 
00:02:19,920 --> 00:02:23,680
难以想象吧 它还是一种比较特色的美食

27 
00:02:23,800 --> 00:02:26,800
这一锅 羊脖子也就是四个到五个

28 
00:02:26,800 --> 00:02:31,320
因为吃热制羊脖的很少 吃凉制的比较多

29 
00:02:31,680 --> 00:02:36,480
做羊脖的时间还比较长 它是最后才出锅

30 
00:02:36,480 --> 00:02:40,360
这一个羊脖有三斤半

31 
00:02:40,360 --> 00:02:43,280
煮熟后也要剩余二斤半（缩水）

32 
00:02:44,920 --> 00:02:47,840
师傅 这个羊脖大约需要煮多久

33 
00:02:47,840 --> 00:02:52,200
（开锅后）煮两个半小时

34 
00:02:57,600 --> 00:02:58,720
（切羊脖）体现了刀工

35 
00:02:58,720 --> 00:03:04,120
纯手工剁制的 就为两片羊脖出来 薄如雪花

36 
00:03:04,120 --> 00:03:06,000
薄如雪花 都是手动剁出来的

37 
00:03:06,000 --> 00:03:09,200
有些客人来说 你们这个羊脖是不是拿机子切的

38 
00:03:09,200 --> 00:03:13,200
没有 全是师傅凭手工切出来的

39 
00:03:31,560 --> 00:03:36,800
切好的羊脖 最后才能撒上椒盐 然后才能上桌

40 
00:03:52,640 --> 00:03:59,000
今天呢 点了一盘的凉羊脖 还有一盘的热的羊排

41 
00:03:59,000 --> 00:04:02,240
这两盘肉都是码放好之后端上来的

42 
00:04:02,240 --> 00:04:04,640
随着这两盘肉 一起上来的呢

43 
00:04:04,640 --> 00:04:07,240
还有一小碟的蒜醋汁

44 
00:04:07,240 --> 00:04:12,600
还有一小碟的  吃肉不可缺少的大蒜

45 
00:04:14,720 --> 00:04:20,080
这样好像才是西北吃肉的正确打开方式

46 
00:04:22,520 --> 00:04:26,640
它这个羊肉是原味的 只是在上桌之前先放了一点盐

47 
00:04:26,640 --> 00:04:28,320
咱们呢 就是先尝尝

48 
00:04:28,320 --> 00:04:31,680
什么都不蘸的这种羊肉是什么样的味道

49 
00:04:31,680 --> 00:04:34,880
先来一个羊排吧

50 
00:04:34,880 --> 00:04:38,680
试一试 手抓版

51 
00:04:38,680 --> 00:04:43,040
羊排是直接用手一抽 骨头就能掉下来

52 
00:04:43,040 --> 00:04:46,360
炖的好软烂 看来是不能用手抓着吃了

53 
00:04:46,360 --> 00:04:48,280
用筷子夹着吃

54 
00:04:49,080 --> 00:04:54,240
它这个羊排 就是这种肥瘦相间的 还冒着油

55 
00:05:04,880 --> 00:05:07,600
羊排炖的很软烂

56 
00:05:07,600 --> 00:05:12,440
我刚才就是用嘴唇吸溜进去的

57 
00:05:12,440 --> 00:05:14,960
宁夏人把肥的 叫做壮

58 
00:05:14,960 --> 00:05:18,600
我觉得这一盘 应该是死壮死壮（strong强壮）的吧

59 
00:05:22,520 --> 00:05:24,560
是不是我的嘴上都是油

60 
00:05:24,560 --> 00:05:28,240
你看 羊排都是带点肥油的

61 
00:05:28,240 --> 00:05:32,240
它是热的 这么一吃 羊肉的香味特别足

62 
00:05:33,400 --> 00:05:37,520
不得不说 这边的菜码真的是特别大

63 
00:05:43,440 --> 00:05:45,440
我看资料的时候 有句话是

64 
00:05:45,440 --> 00:05:48,680
初级的吃货是喜欢吃手抓羊排的

65 
00:05:48,680 --> 00:05:53,600
但是稍微高级一点 进阶一点喜欢吃的是凉的羊脖

66 
00:05:53,600 --> 00:05:57,400
凉的羊脖 肥的就会明显少很多

67 
00:05:57,400 --> 00:05:59,200
看起来特别好看

68 
00:05:59,200 --> 00:06:01,880
像雪花一样

69 
00:06:10,280 --> 00:06:12,400
羊脖：好细嫩

70 
00:06:14,160 --> 00:06:16,840
忍不住再吃一口

71 
00:06:16,840 --> 00:06:20,160
它这个是吃不出来什么调料的味道

72 
00:06:20,160 --> 00:06:23,000
只能吃出来是这种稍微的咸味

73 
00:06:23,000 --> 00:06:26,760
还有羊肉的 这种带点肥的这种香味

74 
00:06:33,520 --> 00:06:36,280
掉了 掉了

75 
00:06:47,760 --> 00:06:49,200
蘸了蒜醋汁

76 
00:06:49,200 --> 00:06:54,200
好像把羊脖子上最后一点的油腻都掩盖了

77 
00:07:13,600 --> 00:07:17,520
吃完了手抓 雪鱼即将前往的是镇北堡影视基地

78 
00:07:17,520 --> 00:07:19,680
在这个地方你可以体验一下

79 
00:07:19,680 --> 00:07:23,480
至尊宝和紫霞仙子的爱情故事

80 
00:07:42,360 --> 00:07:46,160
前面还有比武招亲的吗 还是抛绣球的

81 
00:07:46,600 --> 00:07:47,600
小姐

82 
00:07:47,600 --> 00:07:50,920
风流倜傥的

83 
00:07:50,920 --> 00:07:52,280
脚下生风的

84 
00:07:52,280 --> 00:07:54,960
腚大腰圆的

85 
00:07:54,960 --> 00:07:58,400
小姐
自己挑
自己选

86 
00:07:58,400 --> 00:08:01,680
小姐
请抛绣球

87 
00:08:03,520 --> 00:08:05,640
给你吧

88 
00:08:17,600 --> 00:08:21,800
刚才绣球直接到了我这里

89 
00:08:22,960 --> 00:08:27,160
我只是一个过客 没想到得到了一个小姐

90 
00:08:32,480 --> 00:08:36,160
来这里
拍照的经典动作

91 
00:08:53,360 --> 00:08:56,880
     关  注
雪 鱼  探 店


```

**Comment by shuaisoserious** [comment]
认领

**Comment by shuaisoserious** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
宁夏特色美食凉羊脖子，直接清水煮，出锅只撒盐就很好吃

简介
宁夏滩羊味道鲜美，口感不膻不腻，做手抓羊肉只需要清水炖煮，稍微加一些葱姜即可，出锅时候斩大块摆盘，最后撒上椒盐就可以上桌。羊肋排肥瘦相间，肉质软烂，一口下去羊肉味道十足，配合一碟醋蒜汁，味道更美。高级一点的吃货会对羊脖子青睐有加！羊脖子同手抓羊肉一锅炖出来，只不过出锅时间会晚一个小时，出锅后的羊脖子放入冰箱冷藏，冷藏后的羊脖子极易切片，大刀切开，状如雪花，夹起来吃一口，口感细腻入微，入口即化，神仙口感，而此时，几乎不用任何蘸料就觉得美味。

字幕
1 
00:00:06,880 --> 00:00:09,040
哈喽 雪鱼现在在银川
Hello, xueyu is at Yinchuan now
2 
00:00:09,040 --> 00:00:12,400
有句话叫做 吃在吴忠 游在银川
There is a saying that eats in Wuzhong and travel in Yinchuan
3 
00:00:12,400 --> 00:00:15,040
这次我专门来银川 耍一耍
I come to Yinchuan to travel for this time
4 
00:00:15,040 --> 00:00:17,960
在吴忠的时候 我吃了早茶 吃了羊杂
I eat Zaocha and mutton offal in Wuzhong while i was in Wuzhong
5 
00:00:17,960 --> 00:00:20,400
但是还有一种 手抓 没有尝到
But i haven’t tried Shouzhua yet
6 
00:00:20,400 --> 00:00:24,080
这次来银川呢 先把没有吃到手抓的遗憾弥补掉吧
This time I’m here to make up for my regret in Yinchuan
7 
00:00:24,080 --> 00:00:27,120
很多吴忠的手抓店 在银川这边也会有的
A lot shouzhuan restaurant from Wuzhong are open in Yinchuan
8 
00:00:27,120 --> 00:00:30,400
前一段时间 我刚在西宁这边吃过手抓羊排
A few weeks ago I just ate shouzhua lamb chops in Xining
9 
00:00:30,400 --> 00:00:32,240
不过同在西北
although it’s both in Northwest
10 
00:00:32,240 --> 00:00:37,200
宁夏的手抓和西宁的手抓还是有很大区别的
Shouzhua are different in Ningxia and Xining
11 
00:00:52,040 --> 00:00:56,240
这正好是遇上 羊肉刚出锅
Fresh cooked lamb just out of the pot
12 
00:00:56,240 --> 00:00:57,720
这个锅盖一打开
Once the lid open
13 
00:00:57,720 --> 00:01:01,680
羊肉的香味立刻飘过来冲击到脑子里
The fragment smell of lamb crashed my mind
14 
00:01:06,760 --> 00:01:11,160
大哥 我问一下 这里面主要是羊什么部位的肉
Brother, what part of lamb is the meat is?
15 
00:01:11,160 --> 00:01:16,480
主要是羊的前排 前羊排
Lamb front ribs mainly
16 
00:01:19,200 --> 00:01:20,800
这一锅大约能有多少斤
How many jin in a pot?
17 
00:01:20,800 --> 00:01:23,800
这一锅达到140斤
About 140 jin(70kg)
18 
00:01:37,000 --> 00:01:38,920
炖羊肉的汤里没有什么大料包
There is no seasoning package in the lamb soup
19 
00:01:38,920 --> 00:01:41,320
只有简单的葱姜这样的调味品
Just simple seasons like ginger and green onion
20 
00:01:41,320 --> 00:01:45,200
这么看着真的是 汤上面只是泛着一层清油
There is a layer of clear oil on the soup
21 
00:01:45,200 --> 00:01:48,680
仔细看看汤 汤还是很白的
The soup are white when you see it more serious
22 
00:02:07,520 --> 00:02:09,880
锅里是几乎不加盐的
There is no salt in the soup
23 
00:02:09,880 --> 00:02:13,360
炖的时候 羊汤的锅里几乎是不加盐的
They don’t add salt in the pot of soup when they boil the soup
24 
00:02:13,640 --> 00:02:16,800
这个锅里除了比较明显能够看到的羊排
We can see lamb ribs in the pot
25 
00:02:16,800 --> 00:02:19,920
还有一个不能不说
And we have to say
26 
00:02:19,920 --> 00:02:23,680
难以想象吧 它还是一种比较特色的美食
Hard to image, it is a special food
27 
00:02:23,800 --> 00:02:26,800
这一锅 羊脖子也就是四个到五个
There only four to five lamb neck in a pot
28 
00:02:26,800 --> 00:02:31,320
因为吃热制羊脖的很少 吃凉制的比较多
Because people more prefer to eat cold lamb neck
29 
00:02:31,680 --> 00:02:36,480
做羊脖的时间还比较长 它是最后才出锅
It also take very long time to make, lamb neck is the last to take out from the pot
30 
00:02:36,480 --> 00:02:40,360
这一个羊脖有三斤半
The lamb neck is about 3 jin and a half(1.75kg)
31 
00:02:40,360 --> 00:02:43,280
煮熟后也要剩余二斤半（缩水）
It still have 2 jin and a half(1.25kg) after cook(shrink)
32 
00:02:44,920 --> 00:02:47,840
师傅 这个羊脖大约需要煮多久
Master, how long time it take to cook the lamb neck?
33 
00:02:47,840 --> 00:02:52,200
（开锅后）煮两个半小时
About 2 and a half hours(after boiling)
34 
00:02:57,600 --> 00:02:58,720
（切羊脖）体现了刀工
It reflect the skill of cutting when they cut the lamb neck
35 
00:02:58,720 --> 00:03:04,120
纯手工剁制的 就为两片羊脖出来 薄如雪花
Hand chopped just for two slices of lamb neck, as thin as snowflake?
36 
00:03:04,120 --> 00:03:06,000
薄如雪花 都是手动剁出来的
As thin as snowflake, all by hand chopped
37 
00:03:06,000 --> 00:03:09,200
有些客人来说 你们这个羊脖是不是拿机子切的
Some customers will ask about is that chopped by machine
38 
00:03:09,200 --> 00:03:13,200
没有 全是师傅凭手工切出来的
No, all hand chopped by master
39 
00:03:31,560 --> 00:03:36,800
切好的羊脖 最后才能撒上椒盐 然后才能上桌
Chopped lamb neck are ready to serve after sprink salt and pepper on it
40 
00:03:52,640 --> 00:03:59,000
今天呢 点了一盘的凉羊脖 还有一盘的热的羊排
We ordered a cold lamb neck and a hot lamb ribs
41 
00:03:59,000 --> 00:04:02,240
这两盘肉都是码放好之后端上来的
The two plates of meat are ready to serve after tidy up
42 
00:04:02,240 --> 00:04:04,640
随着这两盘肉 一起上来的呢
Garlic and vinegar sauce are serve
43 
00:04:04,640 --> 00:04:07,240
还有一小碟的蒜醋汁
with the two plates of meat
44 
00:04:07,240 --> 00:04:12,600
还有一小碟的  吃肉不可缺少的大蒜
And a small plate of garlic, which are essential to eat with lam
45 
00:04:14,720 --> 00:04:20,080
这样好像才是西北吃肉的正确打开方式
This seems the right way to eat meat in northwest
46 
00:04:22,520 --> 00:04:26,640
它这个羊肉是原味的 只是在上桌之前先放了一点盐
This lamb are original flavor, just add some salt before serve
47 
00:04:26,640 --> 00:04:28,320
咱们呢 就是先尝尝
We just try how
48 
00:04:28,320 --> 00:04:31,680
什么都不蘸的这种羊肉是什么样的味道
The taste of original flavor of lamb without any seasoning
49 
00:04:31,680 --> 00:04:34,880
先来一个羊排吧
We try the lamb ribs first 
50 
00:04:34,880 --> 00:04:38,680
试一试 手抓版
Try shouzhua
51 
00:04:38,680 --> 00:04:43,040
羊排是直接用手一抽 骨头就能掉下来
The bone of lamb ribs are easy to pull out from meat
52 
00:04:43,040 --> 00:04:46,360
炖的好软烂 看来是不能用手抓着吃了
It stewed very long time, looks we don’t need to use our hand 
53 
00:04:46,360 --> 00:04:48,280
用筷子夹着吃
Eat it with our chopsticks
54 
00:04:49,080 --> 00:04:54,240
它这个羊排 就是这种肥瘦相间的 还冒着油
The lamb ribs are with fatty and lean meat, and the oil is coming out
55 
00:05:04,880 --> 00:05:07,600
羊排炖的很软烂
Lamb chops stewed very soft
56 
00:05:07,600 --> 00:05:12,440
我刚才就是用嘴唇吸溜进去的
I sucked it with my lips
57 
00:05:12,440 --> 00:05:14,960
宁夏人把肥的 叫做壮
Ningxia people called “fatty” to strong
58 
00:05:14,960 --> 00:05:18,600
我觉得这一盘 应该是死壮死壮（strong强壮）的吧
I think this plate is very ”strong”
59 
00:05:22,520 --> 00:05:24,560
是不是我的嘴上都是油
Look, is the oil all over my mouth?
60 
00:05:24,560 --> 00:05:28,240
你看 羊排都是带点肥油的
Look, all lamb ribs are with some fatty oil
61 
00:05:28,240 --> 00:05:32,240
它是热的 这么一吃 羊肉的香味特别足
It’s hot, so with very strong flavor and fragment of lamb
62 
00:05:33,400 --> 00:05:37,520
不得不说 这边的菜码真的是特别大
We have to say that they give large amount of meat for every plate
63 
00:05:43,440 --> 00:05:45,440
我看资料的时候 有句话是
There is a saying when I read the information
64 
00:05:45,440 --> 00:05:48,680
初级的吃货是喜欢吃手抓羊排的
Beginner foodies like to eat lamb chops
65 
00:05:48,680 --> 00:05:53,600
但是稍微高级一点 进阶一点喜欢吃的是凉的羊脖
And advanced foodie like to eat cold lamb neck
66 
00:05:53,600 --> 00:05:57,400
凉的羊脖 肥的就会明显少很多
Cold lamb neck with less fatty 
67 
00:05:57,400 --> 00:05:59,200
看起来特别好看
Looks pretty good
68 
00:05:59,200 --> 00:06:01,880
像雪花一样
Like snowflake
69 
00:06:10,280 --> 00:06:12,400
羊脖：好细嫩
Lamb neck are soft and tender
70 
00:06:14,160 --> 00:06:16,840
忍不住再吃一口
Can not stop to eat
71 
00:06:16,840 --> 00:06:20,160
它这个是吃不出来什么调料的味道
I don’t know what seasonings they use  in the lamb neck
72 
00:06:20,160 --> 00:06:23,000
只能吃出来是这种稍微的咸味
Just taste some salty taste
73 
00:06:23,000 --> 00:06:26,760
还有羊肉的 这种带点肥的这种香味
And some fragment of lamb with fatty
74 
00:06:33,520 --> 00:06:36,280
掉了 掉了
dropped
75 
00:06:47,760 --> 00:06:49,200
蘸了蒜醋汁
With garlic and vinegar sauce dipping
76 
00:06:49,200 --> 00:06:54,200
好像把羊脖子上最后一点的油腻都掩盖了
It cover up oily taste of lamb neck
77 
00:07:13,600 --> 00:07:17,520
吃完了手抓 雪鱼即将前往的是镇北堡影视基地
After we finished eat, xueyu gonna go Zhenbeibao Film and Television Base
78 
00:07:17,520 --> 00:07:19,680
在这个地方你可以体验一下
We can experienced 
79 
00:07:19,680 --> 00:07:23,480
至尊宝和紫霞仙子的爱情故事
Love story between zhizunbao and zixiaxianzi
80 
00:07:42,360 --> 00:07:46,160
前面还有比武招亲的吗 还是抛绣球的
Is there any contest in front of martial arts to recruit relatives? Or throwing hydrangea


81 
00:07:46,600 --> 00:07:47,600
小姐
Young lady
82 
00:07:47,600 --> 00:07:50,920
风流倜傥的

83 
00:07:50,920 --> 00:07:52,280
脚下生风的

84 
00:07:52,280 --> 00:07:54,960
腚大腰圆的

85 
00:07:54,960 --> 00:07:58,400
小姐
自己挑
自己选

86 
00:07:58,400 --> 00:08:01,680
小姐
请抛绣球

87 
00:08:03,520 --> 00:08:05,640
给你吧
Give it to you
88 
00:08:17,600 --> 00:08:21,800
刚才绣球直接到了我这里

89 
00:08:22,960 --> 00:08:27,160
我只是一个过客 没想到得到了一个小姐

90 
00:08:32,480 --> 00:08:36,160
来这里
拍照的经典动作

91 
00:08:53,360 --> 00:08:56,880
     关  注
雪 鱼  探 店
