### ISSUE TITLE
【美食作家王刚】帮老师傅卖凉糕 - https://youtu.be/sNNW7Wv6jN4

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1361]
**视频链接**：https://youtu.be/sNNW7Wv6jN4

视频时长7:09，预计发布时间为北京时间8月9日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
富顺传统凉糕手艺即将失传，老师傅退休之际爽快答应收我为徒，再学一门手艺

简介
大家好，今天来做一天的凉糕学徒，先和老师傅去把当天的凉糕卖完，再回来做第二天份的凉糕，并且学一学如何用最传统的方法来制作。相信凉糕是很多四川朋友小时候的记忆，其实我也是，小时候家里没钱，就觉得长大后我也要做凉糕，想吃多少就吃多少，现在学起来也不迟！

字幕
0:00:03.677,0:00:04.300
走嘛

0:00:08.267,0:00:09.604
 凉糕哟

0:00:17.750,0:00:19.012
 凉糕诶

0:00:20.045,0:00:21.276
卖凉糕了

0:00:22.188,0:00:23.252
凉糕

0:00:26.079,0:00:27.629
让它浪起来

0:00:31.702,0:00:35.455
 今天我跟一个老师父出来体验一下

0:00:35.486,0:00:37.553
挑着担子卖凉糕是什么感觉 

0:00:38.449,0:00:39.726
这个你请的啊 

0:00:40.243,0:00:42.127
嗯 我是学徒 

0:00:43.677,0:00:44.346
  当真的啊 

0:00:44.468,0:00:47.978
真的啊 真的 跟师父学哈 

0:00:49.604,0:00:52.127
一个当了几年兵的（回来）看到何师傅卖凉糕 

0:00:52.264,0:00:55.711
追起追起的要（吃） 

0:00:55.790,0:00:56.960
我小时候都追过 

0:00:57.066,0:00:58.523
我没有乱说嘛 

0:00:58.525,0:01:03.358
人家跑到上面拿着多大的碗  噗噗噗地跟都追

0:01:07.386,0:01:10.334
 是 我还多久没吃到他的凉糕了

0:01:10.334,0:01:13.221
 遮都它就是  拉开来一哈遮都就是 

0:01:18.951,0:01:21.823
 凉糕诶 凉糕 

0:01:23.784,0:01:25.288
  凉糕哦 

0:01:25.775,0:01:29.133
卖凉糕哦 凉糕 

0:01:29.939,0:01:30.790
你打嘛 

0:01:30.790,0:01:31.686
看你打得来不  

0:01:33.723,0:01:35.455
这儿给它翻起来

0:01:37.310,0:01:38.161
 3碗啊 

0:01:38.176,0:01:38.753
嗯

0:01:39.696,0:01:40.668
 先给你打了来 

0:01:42.750,0:01:44.285
 凉糕哦 

0:01:53.662,0:01:54.407
 打不打（凉糕）

0:01:54.407,0:01:55.486
 我不晓得他打不打

0:01:55.531,0:01:56.367
 我喊了他的

0:02:00.942,0:02:02.097
 凉糕哦

0:02:06.884,0:02:08.601
来给我打一碗 

0:02:11.945,0:02:12.963
多点嘛少点 

0:02:13.419,0:02:14.741
跟他舀3勺嘛

0:02:22.948,0:02:24.832
 我先休息一下

0:02:24.848,0:02:29.194
 你还没学会 你挑着就很累

0:02:29.194,0:02:29.817
 是 

0:02:30.045,0:02:31.337
凉糕哦 

0:03:00.136,0:03:01.945
 现在我们卖得还剩最后三碗 

0:03:02.416,0:03:05.577
然后这个大姐又要一两碗 

0:03:05.668,0:03:06.443
好多钱一碗 

0:03:06.717,0:03:09.072
没得了只有三碗 你端一碗去嘛 

0:03:09.452,0:03:11.550
我给那个小乖乖买一碗去 

0:03:12.097,0:03:12.826
好多钱一碗嘛 

0:03:12.841,0:03:13.282
2元 

0:03:13.282,0:03:14.164
我这一哈拿钱 

0:03:14.255,0:03:16.003
没想到还不够卖  真的

0:03:16.656,0:03:18.252
再多来几碗都没问题

0:03:19.954,0:03:22.933
 现在我师父卖完了马上回去现拷（做）

0:03:22.993,0:03:25.455
 拷（做）了之后明天又可以接着卖

0:03:25.455,0:03:28.844
因为做出来的不是马上可以吃 要等它冷 

0:03:30.607,0:03:31.458
这哈我整（挑）它得动了 

0:03:36.033,0:03:37.735
这下可以把它整的动了 

0:03:37.993,0:03:40.638
现在轻了好多 少了几十斤

0:03:52.492,0:03:53.480
 要不要烧火安 

0:03:53.480,0:03:54.696
不 要等会 

0:03:58.419,0:04:01.003
这个拷（做）都还要注意到安全

0:04:01.003,0:04:03.145
 一烫到你的话甩不脱 

0:04:03.145,0:04:03.981
好烫啊

0:04:04.042,0:04:06.626
烫来要起泡 

0:04:09.908,0:04:12.386
 你不烧它 它就不得下沉 

0:04:12.492,0:04:13.267
全是白色的（沉淀物）  

0:04:13.328,0:04:15.121
要烧开之后才会有这个噶 

0:04:15.121,0:04:16.960
先看着没有烧的时候好脏哦噶

0:04:17.036,0:04:18.981
 嗯 这下多清亮 

0:04:21.656,0:04:22.735
我先尝一下这个水

0:04:25.197,0:04:26.565
 这哈快当  一会就拷好了 

0:04:28.161,0:04:30.911
嗯 很强的那个皮蛋（碱）的味道

0:04:31.428,0:04:34.483
 那个自贡的还不是啊 专门下来（学）

0:04:34.498,0:04:37.066
 看了之后回去拷 结果又叫他上去教 

0:04:38.966,0:04:41.352
这剩下的就是颗粒  你用手去摸嘛

0:04:42.705,0:04:46.489
 哦 颗粒 这是没有被充分打碎的 

0:04:46.595,0:04:48.541
你没得颗粒就全部都要的 

0:04:48.677,0:04:52.112
我的小孩他看都不得来看一眼 他不学 

0:04:52.629,0:04:54.741
他不喜欢这个手艺噶 

0:04:54.772,0:04:56.215
嗯他不得学 

0:04:56.291,0:04:57.325
这个就不加了嘛

0:04:57.325,0:04:57.872
 要 

0:04:57.948,0:04:59.118
这个还要加进去啊

0:04:59.817,0:05:03.373
 这个看黏稠度 不够就加点来又拷（做）

0:05:03.541,0:05:05.045
 哦 还可以后面慢慢的加 

0:05:09.772,0:05:11.109
你看嘛  他慢慢的加 

0:05:11.686,0:05:12.568
来 我给你拷都 

0:05:16.033,0:05:19.376
我来 搅给你看

0:05:19.893,0:05:22.446
就是下去那哈就要好好得拷 

0:05:22.705,0:05:24.300
要让它浪起来

0:05:28.510,0:05:30.547
 这个咋子晓得它的浓稠度呢

0:05:30.987,0:05:33.373
 这个只有自己掌握老嫩 

0:05:44.437,0:05:46.838
这没满就给它加点

0:05:53.161,0:05:55.273
小心端哦 慢点烫得很哦 

0:05:57.234,0:05:59.650
端一个就可以了 你没端习惯

0:06:13.738,0:06:14.680
锅巴呀

0:06:15.151,0:06:18.419
就像以前做的浑水粑味道

0:06:23.206,0:06:24.832
嗯 很香这个

0:06:25.364,0:06:28.586
就是这个浆浆好吃 你夹一点来试试嘛

0:06:29.924,0:06:31.595
我女儿就喜欢吃这个 

0:06:32.750,0:06:33.966
绵绵的

0:06:33.966,0:06:35.167
有浑水粑的味道

0:06:38.343,0:06:40.045
我们这刚好66碗

0:06:40.243,0:06:42.963
现在煮了一大锅就做了66碗

0:06:43.297,0:06:46.793
大概是四五斤 四斤左右的大米

0:06:47.857,0:06:50.531
现在又学会一样传统手艺了

0:06:50.729,0:06:52.082
过两天拍个视频 

0:06:54.741,0:06:57.112
66碗 刚好66碗 

0:06:57.887,0:06:59.650
64 那儿少2个缺口

0:07:00.455,0:07:02.568
 64碗那就差不多跟以前 

0:07:02.735,0:07:03.784
64碗

0:07:04.696,0:07:06.823
好啦 本期视频就到这里了 拜拜 


```

**Comment by immoonancient** [comment]
@Hackerry 请前来认领

**Comment by Hackerry** [comment]
认领

**Comment by Hackerry** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
富顺传统凉糕手艺即将失传，老师傅退休之际爽快答应收我为徒，再学一门手艺
Traditional Fushun Lianggao craft is dying. Old master agrees to teach me before he retires.

简介
大家好，今天来做一天的凉糕学徒，先和老师傅去把当天的凉糕卖完，再回来做第二天份的凉糕，并且学一学如何用最传统的方法来制作。相信凉糕是很多四川朋友小时候的记忆，其实我也是，小时候家里没钱，就觉得长大后我也要做凉糕，想吃多少就吃多少，现在学起来也不迟！
Hello everyone, I became a student today. I sold Lianggao with my master and learned how to make traditional Lianggao while watching him preparing for tomorrow's sale. I believe many of you from Sichuan have sweet childhood memories that include Lianggao. As a poor kid, I once aspired to make Lianggao when I grow up, so that I don't have to buy it anymore. It's not too late to learn it now!

字幕
0:00:03.677,0:00:04.300
走嘛
Go

0:00:08.267,0:00:09.604
凉糕哟
Lianggao

0:00:17.750,0:00:19.012
凉糕诶
Lianggao

0:00:20.045,0:00:21.276
卖凉糕了
Who wants Lianggao

0:00:22.188,0:00:23.252
凉糕
Lianggao

0:00:26.079,0:00:27.629
让它浪起来
Make it swirl

0:00:31.702,0:00:35.455
今天我跟一个老师父出来体验一下
Today I follow my master and

0:00:35.486,0:00:37.553
挑着担子卖凉糕是什么感觉 
hawk Lianggao in the street.

0:00:38.449,0:00:39.726
这个你请的啊 
He's your employee?

0:00:40.243,0:00:42.127
嗯 我是学徒 
En. I'm an apprentice.

0:00:43.677,0:00:44.346
当真的啊 
You are serious?

0:00:44.468,0:00:47.978
真的啊 真的 跟师父学哈 
Yes. I am. I'm learning from my master.

0:00:49.604,0:00:52.127
一个当了几年兵的（回来）看到何师傅卖凉糕
A serviceman saw Master He selling Lianggao the other day

0:00:52.264,0:00:55.711
追起追起的要（吃） 
He chased him eagerly (for Lianggao)

0:00:55.790,0:00:56.960
我小时候都追过
Sounds like me when I was little

0:00:57.066,0:00:58.523
我没有乱说嘛
See? I didn't brag.

0:00:58.525,0:01:03.358
人家跑到上面拿着多大的碗  噗噗噗地跟都追
He ran a long way to fetch a large bowl and chase him

0:01:07.386,0:01:10.334
是 我还多久没吃到他的凉糕了
It for sure has been a long time since I last bought Lianggao from him

0:01:10.334,0:01:13.221
遮都它就是  拉开来一哈遮都就是
Just cover it. Stretch it and put over the basket.

0:01:18.951,0:01:21.823
凉糕诶 凉糕
Lianggao. Lianggao.

0:01:23.784,0:01:25.288
凉糕哦
Lianggao.

0:01:25.775,0:01:29.133
卖凉糕哦 凉糕
Lianggao for sale. Lianggao.

0:01:29.939,0:01:30.790
你打嘛
Give it a try

0:01:30.790,0:01:31.686
看你打得来不
See whether you can serve it well

0:01:33.723,0:01:35.455
这儿给它翻起来
Scoop from the bottom

0:01:37.310,0:01:38.161
3碗啊 
You want three servings, right?

0:01:38.176,0:01:38.753
嗯
Yes

0:01:39.696,0:01:40.668
先给你打了来
I'll fetch them

0:01:42.750,0:01:44.285
凉糕哦
Lianggao

0:01:53.662,0:01:54.407
打不打（凉糕）
Do you want some (Lianggao)?

0:01:54.407,0:01:55.486
我不晓得他打不打
I'm not sure whether he wants it

0:01:55.531,0:01:56.367
我喊了他的
He didn't answer

0:02:00.942,0:02:02.097
凉糕哦
Lianggao

0:02:06.884,0:02:08.601
来给我打一碗
Here. I want a bowl (of Lianggao).

0:02:11.945,0:02:12.963
多点嘛少点
How much (syrup)?

0:02:13.419,0:02:14.741
跟他舀3勺嘛
3 spoons

0:02:22.948,0:02:24.832
我先休息一下
I need a rest

0:02:24.848,0:02:29.194
你还没学会 你挑着就很累
You are tired because you haven't learned the trick

0:02:29.194,0:02:29.817
是
Indeed

0:02:30.045,0:02:31.337
凉糕哦 
Lianggao

0:03:00.136,0:03:01.945
现在我们卖得还剩最后三碗 
We have 3 bowls of Lianggao left

0:03:02.416,0:03:05.577
然后这个大姐又要一两碗 
And this Aunt wants some

0:03:05.668,0:03:06.443
好多钱一碗 
How much is it?

0:03:06.717,0:03:09.072
没得了只有三碗 你端一碗去嘛 
Only three are left. Come and get one.

0:03:09.452,0:03:11.550
我给那个小乖乖买一碗去 
I will buy one for my little one.

0:03:12.097,0:03:12.826
好多钱一碗嘛
How much?

0:03:12.841,0:03:13.282
2元 
2 Yuan

0:03:13.282,0:03:14.164
我这一哈拿钱 
Let me get some money

0:03:14.255,0:03:16.003
没想到还不够卖  真的
It's too popular and quickly sold

0:03:16.656,0:03:18.252
再多来几碗都没问题
We can definitely sell more

0:03:19.954,0:03:22.933
现在我师父卖完了马上回去现拷（做）
Now my master is going back to make more

0:03:22.993,0:03:25.455
拷（做）了之后明天又可以接着卖
Get ready for tomorrow's sale

0:03:25.455,0:03:28.844
因为做出来的不是马上可以吃 要等它冷
Lianggao needs to be served cold

0:03:30.607,0:03:31.458
这哈我整（挑）它得动了 
Now I'm able to take it

0:03:36.033,0:03:37.735
这下可以把它整的动了
Take it easily

0:03:37.993,0:03:40.638
现在轻了好多 少了几十斤
It is quite lighter now

0:03:52.492,0:03:53.480
要不要烧火安 
Should I light up the fire now?

0:03:53.480,0:03:54.696
不 要等会 
No. Wait a second.

0:03:58.419,0:04:01.003
这个拷（做）都还要注意到安全
Be careful when make this

0:04:01.003,0:04:03.145
一烫到你的话甩不脱 
It's very hot and 

0:04:03.145,0:04:03.981
好烫啊
How hot?

0:04:04.042,0:04:06.626
烫来要起泡
Skin-swelling hot

0:04:09.908,0:04:12.386
你不烧它 它就不得下沉 
Heat will make it precipitate

0:04:12.492,0:04:13.267
全是白色的（沉淀物）
All those white (precipitations)?

0:04:13.328,0:04:15.121
要烧开之后才会有这个噶
It only forms after boiling

0:04:15.121,0:04:16.960
先看着没有烧的时候好脏哦噶
It looks quite muddy before boiling

0:04:17.036,0:04:18.981
嗯 这下多清亮 
En. Now it's clear.

0:04:21.656,0:04:22.735
我先尝一下这个水
Let me have a taste of this solution

0:04:25.197,0:04:26.565
这哈快当  一会就拷好了
The fire is catching up. It won't take too long.

0:04:28.161,0:04:30.911
嗯 很强的那个皮蛋（碱）的味道
En. Very strong century egg (basic) taste.

0:04:31.428,0:04:34.483
那个自贡的还不是啊 专门下来（学）
We had people from Zigong who came all the way just to learn this

0:04:34.498,0:04:37.066
看了之后回去拷 结果又叫他上去教
He had learned well and taught others

0:04:38.966,0:04:41.352
这剩下的就是颗粒  你用手去摸嘛
Those are the particles left. You can feel it.

0:04:42.705,0:04:46.489
哦 颗粒 这是没有被充分打碎的 
Oh. Particles that survive the grinding.

0:04:46.595,0:04:48.541
你没得颗粒就全部都要的
They must be left out

0:04:48.677,0:04:52.112
我的小孩他看都不得来看一眼 他不学
My kid doesn't ever cast a glance at this. He doesn't want to learn.

0:04:52.629,0:04:54.741
他不喜欢这个手艺噶 
He doesn't like this craft

0:04:54.772,0:04:56.215
嗯他不得学 
No. He doesn't.

0:04:56.291,0:04:57.325
这个就不加了嘛
We don't need this?

0:04:57.325,0:04:57.872
要
Yes.

0:04:57.948,0:04:59.118
这个还要加进去啊
Oh, we need this?

0:04:59.817,0:05:03.373
这个看黏稠度 不够就加点来又拷（做）
We can add some depending on the stickiness

0:05:03.541,0:05:05.045
哦 还可以后面慢慢的加 
Oh. So we can add it later.

0:05:09.772,0:05:11.109
你看嘛  他慢慢的加 
See? He is adding little by little.

0:05:11.686,0:05:12.568
来 我给你拷都 
Here. I'll stir.

0:05:16.033,0:05:19.376
我来 搅给你看
Give me that. Let me show you how it's done.

0:05:19.893,0:05:22.446
就是下去那哈就要好好得拷 
Stir well once you added that

0:05:22.705,0:05:24.300
要让它浪起来
Make it swirl

0:05:28.510,0:05:30.547
这个咋子晓得它的浓稠度呢
How to know how thick it is?

0:05:30.987,0:05:33.373
这个只有自己掌握老嫩
Experiences

0:05:44.437,0:05:46.838
这没满就给它加点
Add it to full

0:05:53.161,0:05:55.273
小心端哦 慢点烫得很哦 
Careful. It's very hot.

0:05:57.234,0:05:59.650
端一个就可以了 你没端习惯
Just get that one. You need more practice.

0:06:13.738,0:06:14.680
锅巴呀
Crispy rice!

0:06:15.151,0:06:18.419
就像以前做的浑水粑味道
It tastes like Hun Shui Ba (another rice made food)

0:06:23.206,0:06:24.832
嗯 很香这个
En. Taste good.

0:06:25.364,0:06:28.586
就是这个浆浆好吃 你夹一点来试试嘛
This chunky stuff is good. Try it.

0:06:29.924,0:06:31.595
我女儿就喜欢吃这个 
My daughter likes it

0:06:32.750,0:06:33.966
绵绵的
Very soft

0:06:33.966,0:06:35.167
有浑水粑的味道
Taste like Hun Shui Ba

0:06:38.343,0:06:40.045
我们这刚好66碗
We have 66 bowls here

0:06:40.243,0:06:42.963
现在煮了一大锅就做了66碗
We made 66 bowls from that batch

0:06:43.297,0:06:46.793
大概是四五斤 四斤左右的大米
We used about 4 Jin (2kg) rice

0:06:47.857,0:06:50.531
现在又学会一样传统手艺了
Now I learned a new traditional craft

0:06:50.729,0:06:52.082
过两天拍个视频
I'll make a video about it in a couple of days

0:06:54.741,0:06:57.112
66碗 刚好66碗 
Exactly 66 bowls (6 is a lucky number in China)

0:06:57.887,0:06:59.650
64 那儿少2个缺口
64 actually. There are two missing.

0:07:00.455,0:07:02.568
64碗那就差不多跟以前 
64 is what I expected

0:07:02.735,0:07:03.784
64碗
64 bowls

0:07:04.696,0:07:06.823
好啦 本期视频就到这里了 拜拜
Good. That's all for this episode. Bye bye.
