### ISSUE TITLE
[华农兄弟] 华农兄弟鸭子越养越瘦了抓只来做啤酒鸭不然白养了 - https://youtu.be/5xncVGq4Fio

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1365]
https://youtu.be/5xncVGq4Fio
<p>&#35270;&#39057;&#21457;&#24067;&#20110; August 8, 2020 at 11:45AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/5xncVGq4Fio

#华农兄弟：鸭子越养越瘦了，抓只来做啤酒鸭，不然白养了
#Huanong Brothers: The ducks get skinner every day. We make a beer duck. Otherwise it woudl be a waste.


0:00:00.320,0:00:01.780
# 大家好  今天下雨哦
Hi everyone! It's raining today.

0:00:02.280,0:00:05.920
# 剛好沒甚麼肉吃  上那個上面還有幾隻鴨子
I've just run out of meat. Let's go up, I mean, up there. There are still a couple of ducks.

0:00:06.600,0:00:08.180
# 我現在做一個啤酒鴨來
I'm now gonna make a beer duck.

0:00:11.960,0:00:13.880
# 搞點這像草餵一下那個豬
Let me get some elephant grass here for the pig.

0:00:14.720,0:00:16.480
# 豬絕食了  不吃
The pig is on hunger strike. It doesn't eat.

0:00:21.580,0:00:22.940
# 去餵一下那個小豬
I'm gonna feed that piggy.

0:00:31.880,0:00:33.240
# 把這個象草給它吃
I'll give it the elephant grass.

0:00:33.840,0:00:34.360
# 小豬
Piggy!

0:00:38.520,0:00:39.340
# 看它吃不吃
Let's see if it's eating.

0:00:40.000,0:00:41.180
# 嗯  它會吃哦
Um! It's eating!

0:00:48.340,0:00:49.800
# 好斯文啊這條豬
It has a very good manner, this pig.

0:00:50.760,0:00:51.760
# 不怎麼吃哦
It doesn't eat much.

0:00:53.840,0:00:56.040
# 明天再不吃的話我就磿刀了哦
You'll see me sharpening my knife if you don't start eating something by tomorrow, got it?

0:01:00.900,0:01:03.080
# 吃那麼一點點  就這樣子吃
It eats just a tiny little bit, bit by bit.

0:01:03.900,0:01:07.780
# 你看  它會吃一點 沒事啦  應該是養的活這頭豬
Look! It's eating a little bit. It should be fine. I should be able to make it survive, this pig.

0:01:09.840,0:01:10.760
# 準備抓鴨
Get ready to catch a duck!

0:01:12.220,0:01:13.380
# 鴨跑哪裡去啦
Where are the ducks?

0:01:23.440,0:01:25.160
# 你看  一下就抓住啦
Look! I got it in a single grab.

0:01:26.460,0:01:27.340
# 不反抗的哦
It didn't resist at all.

0:01:58.000,0:01:59.740
# 不用看  下次就輪到你啦
You don't need to watch. It will be your turn next time.

0:02:04.960,0:02:06.140
# 它竟然不怕
Why isn't it scared?

0:02:34.620,0:02:35.600
# 烤鴨
Grilled duck!

0:02:36.420,0:02:37.420
# 嘎嘎
Ga ga!

0:02:39.580,0:02:40.860
# 好啦  這個鴨子
Alright! This duck...

0:02:41.700,0:02:43.560
# 拔不乾淨的  就這樣  有一點點
Here's still some feather. Here, a tiny little bit.

0:02:43.880,0:02:45.500
# 一點毛也可以吃的  這個毛
A little bit of feather is edible, the feather here.

0:02:46.940,0:02:47.780
# 還有一點點毛
There's still a tiny little bit of feather.

0:02:50.040,0:02:52.180
# 這個鴨子砍好啦  就那麼一點點
So I've chopped up the duck. Just a tiny little bit here.

0:02:52.840,0:02:54.920
# 我搞點子薑  來湊一下
I've fetched some young ginger, to make it a dish.

0:02:55.580,0:02:59.260
# 湊下去就多一點  這樣子吃  不然太少啦
Then we can have more to eat. Otherwise, it's too few here.

0:03:00.140,0:03:01.100
# 不夠吃啊
It won't be enough for us.

0:03:02.200,0:03:04.420
# 你看  把這個鴨子炒一下
Look! I'm gonna fry the duck for a while.

0:03:06.380,0:03:07.100
# 搞點油
Put some oil.

0:03:12.220,0:03:14.660
# 因為這個鴨子沒甚麼油  要多放點油
We need a bit more oil, cuz there's hardly any oil in the duck.

0:03:17.500,0:03:19.620
# 把這個生薑先放下去炸一下
I put the ginger into the wok and fry it for a while.

0:03:35.320,0:03:39.080
# 把鴨子  把這個鴨子燜熟  燜熟之後再來  再來煮
I'll stew it, stew the duck, until it's done. And then I'll, I'll cook it for another while.

0:03:41.000,0:03:43.020
# 你看這個鴨子  一點肥肉都沒有
Look! This duck is completely free of fat.

0:03:44.160,0:03:45.660
# 煮這個鴨子比較費油
Cooking this duck needs quite a lot of oil.

0:03:46.580,0:03:48.020
# 所以油要放多一點
So we have to put a bit more oil.

0:03:55.240,0:03:56.140
# 放點鹽
Put some salt.

0:03:59.240,0:04:01.840
# 鹽都不出來 放多一點
The salt doesn't come out. Put more salt.

0:04:11.140,0:04:14.380
# 這個香葉和八角  放下去
Here are bay leaves and star anise. Put them in.

0:04:17.520,0:04:18.860
# 放點這個啤酒
Put some this kind of beer.

0:04:20.160,0:04:21.380
# 這三瓶都放下去
We put all these three cans.

0:04:30.580,0:04:33.140
# 鴨子  啤酒鴨
Duck! Beer duck!

0:04:43.520,0:04:46.020
# 就這樣慢慢燜  小火慢慢燜
We just keep stewing it, on low heat.

0:04:48.240,0:04:49.320
# 把它蓋起來
Cover it up.

0:04:50.320,0:04:51.460
# 誒呦  剛剛好哦
Ayo! It fits perfectly well!

0:05:01.320,0:05:02.780
# 這個啤酒鴨做好啦
So the beer duck is done.

0:05:04.080,0:05:05.100
# 味道杠杠的
C'est délicieux!

0:05:05.500,0:05:06.580
# 鴨個雞腿來吃
Let me have a chicken leg.

0:05:08.860,0:05:09.760
# 這個鴨腿
This duck leg,

0:05:11.100,0:05:12.060
# 好有嚼勁哦
is really chewy.

0:05:12.500,0:05:13.560
# 味道很不錯
It tastes really not bad.

0:05:14.440,0:05:18.560
# 山葯  王剛  要不要一起來  花式啤酒美味挑戰
Yam, Wang Gang! You wanna join? Freestyle Beer Delicacy Challenge.

0:05:22.480,0:05:26.200
# 味道絕對OK  經過我的調養  你們看它的肉質
The taste is absolutely OK, after my special care. Have a look at its texture!

0:05:27.180,0:05:28.300
# 一點肥肉都沒有
It's completely free of fat.

0:05:30.160,0:05:31.480
# 吃一頓  餓三餐
I feed it not every meal, but every four meals.

0:05:32.400,0:05:33.420
# 餵出來的鴨子
Then the ducks are,

0:05:34.960,0:05:35.660
# 就是好
nothing but good.

0:05:38.780,0:05:39.700
# 像這個鴨子  (註︰他應該是說︰「你看這個鴨子」)
Have a look at the duck!

0:05:41.360,0:05:43.460
# 除了瘦肉就是骨頭  還有一層皮
Except lean meat, there's only bone, and skin.

0:05:45.620,0:05:46.120
# 好啦
Alright!

0:05:48.300,0:05:51.500
# 今天的視頻就到這裡啦  我們準備吃晚飯啦
The video ends here. We're getting ready to have our dinner.

0:05:53.600,0:05:54.680
# 給這大肥狗
It's for this big fat dog.

0:05:55.860,0:05:56.860
# 一直都沒吃到
He couldn't get anything.
