### ISSUE TITLE
[华农兄弟] 华农兄弟炸点烫皮边钓鱼边吃钓不到就下去抓 - https://youtu.be/EBX2iWUsLKU

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1369]
https://youtu.be/EBX2iWUsLKU
<p>&#35270;&#39057;&#21457;&#24067;&#20110; August 9, 2020 at 11:37AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/EBX2iWUsLKU

#华农兄弟：炸点烫皮，边钓鱼边吃，钓不到就下去抓
#Huanong Brothers: We make some "tang pi", as fishing snacks. If rod doesn't work, we use net.

0:00:00.000,0:00:02.940
# 大家好  現在我用油煎一下我們這邊的燙皮
Hi everyone! I'm gonna fry some "tang pi" (ground rice chips), a kind of our local snacks.

0:00:03.300,0:00:06.420
# 以前用那個沙子炒也可以炒的 現在用那個油炸一下
We baked them in sand in the past. It also works. But now I'm gonna fry them, using oil.

0:00:06.760,0:00:07.560
# 更香哦
It smells even better.

0:00:09.340,0:00:10.760
# 看一下炸出來是甚麼效果
Let's see how it's gonna look like.

0:00:11.100,0:00:12.020
# 肯定很好吃的
It must be very tasty.

0:00:12.620,0:00:16.340
# 不要放那麼多  一點點來放  要不然搞不贏啦
Don't put too much. Just a tiny little bit at a time. Otherwise you can't make it.

0:00:18.620,0:00:19.400
# 好快呦
It doesn't take long.

0:00:21.580,0:00:23.520
# 這個是很小的時候我們最喜歡吃的
This was our most favourite snacks when we were small.

0:00:26.900,0:00:30.500
# 放在油鍋裡面  一攪拌  全部都起來了
Put it into the oil, stir it, and it's done.

0:00:36.160,0:00:37.020
# 全部倒完啦
All is here now.

0:00:38.200,0:00:39.540
# 哎呀  完啦  太多啦
Aya! My God! Too much!

0:00:56.700,0:00:57.280
# 可以
Not bad!

0:00:58.960,0:01:02.580
# 這個小時候經常在  在家裡放著就月土子餓的時候吃一點
When we were small, we always had, had some of this at home. So we could take some whenever we were hungry.

0:01:03.060,0:01:04.560
# 或者有客人來的時候吃一點
Or we could serve it to our guests.

0:01:05.400,0:01:08.200
# 像這個 每逢過年過節我們都會做一點這個
It's like, we always make some of this whenever there are festivals or celebrations.

0:01:09.500,0:01:11.080
# 我們做的一般就是這種黃色的
The one that me make is usually this kind of yellow one.

0:01:12.280,0:01:13.840
# (這個是  蕉芋口)  (註︰沒有原字幕，但他說得太清楚了)
This is, Indian shots fla...

0:01:14.260,0:01:15.740
# 這個是蕉芋  蕉芋味的
This is Indian shots, Indian shots flavour.

0:01:16.080,0:01:17.000
# 這是韭菜味的
And this is leek flavour.

0:01:22.100,0:01:24.100
# 有點炸糊了  但沒事
It's a bit burnt, but no worries.

0:01:25.860,0:01:26.520
# 嗯~
Um~

0:01:27.720,0:01:31.600
# 可以  我們帶點去那個池塘邊  邊釣魚邊吃
Not bad! We're gonna take some to the pond side. It will be our fishing snacks.

0:01:35.000,0:01:38.360
# 你看  兄弟家池塘就在那裡  那裡好多魚的哦
Look! My buddy's pond is right over there. There are a lot of fish, you know.

0:01:45.420,0:01:49.140
# 你看那個魚  看到沒有  一大堆  全是草魚
Have a look at the fish! See? A big crowd of them. All are grass carps.

0:01:49.740,0:01:50.740
# 我搞根草來釣
Let me fetch a piece of grass as bait.

0:01:51.700,0:01:52.560
# 應該可以釣的到
I think it should work.

0:02:08.780,0:02:11.480
# 搞點這個葉子  這個是紅薯葉哦  這個
Let me take a leaf here. These are sweet potato leaves, this one.

0:02:12.980,0:02:15.100
# 在這摘幾片這個葉子就可以了
A couple of leaves here would be enough.

0:02:17.100,0:02:18.800
# 很喜歡吃的  這個紅薯葉
They like it very much, I mean sweet potato leaves.

0:02:23.780,0:02:24.640
# 你看把這個
Look! I'm putting,

0:02:25.540,0:02:26.080
# 葉子
the leaves,

0:02:27.080,0:02:27.980
# 捆在這裡
here. Tie them here.

0:02:28.820,0:02:30.360
# 勾在這裡就可以釣啦
Hook them here. Then we can start fishing.

0:02:37.140,0:02:40.620
# 可以 那個魚在哪裡  扔到它面前
Alright! Where are the fish? I'm gonna throw it to the front of their eyes.

0:02:47.560,0:02:49.540
# 你看  在那個魚鈎上徘徊
Look! They're wandering around the hook.

0:02:50.520,0:02:52.480
# 走來走去硬是不咬鈎
They're going here and there. But none of them attempt to bite the hook.

0:02:57.160,0:02:58.480
# 很好吃的
It's really tasty!

0:02:59.520,0:03:02.960
# 紅薯葉哦  你們都最喜歡吃的  我都不吃
It's sweet potato leaf, your most favourite food, not mine.

0:03:04.120,0:03:05.520
# 別逼我放水哦
Don't make me drain the pond!

0:03:29.960,0:03:32.320
# 太熱啦  等一下  我倒回去
It's too hot. I'll come back, in a while.

0:03:33.180,0:03:34.020
# 看它會不會咬
Let me see if they're biting the hook.

0:03:37.880,0:03:38.560
# 受不了
I can't stand it.

0:03:41.280,0:03:42.940
# 就在旁邊徘徊它都不吃
They're wandering right around the hook. But they don't attempt to eat the leaf.

0:03:43.580,0:03:48.040
# 是不它害怕  我們找個地方  涼快的地方待著  待一下
Are they scared? We're gonna find a cooler place, and wait, wait for a while.

0:03:49.160,0:03:49.820
# 再過來
I'll be back.

0:03:50.820,0:03:53.140
# 咬都不咬  等了兩個小時了
They didn't bite the hook at all. We've been waiting for two hours.

0:03:54.320,0:03:55.200
# 吃都不吃
They didn't even eat the leaf.

0:03:56.700,0:03:58.360
# 你看  葉子還是新鮮的
Look! The leaf is still as it was.

0:04:02.560,0:04:03.800
# 拿抄網來抄它
Let me catch with a catch net.

0:04:04.880,0:04:06.800
# 這些魚  鈎也不咬
These fish, they're not biting the hook.

0:04:07.520,0:04:08.660
# 水又那麼淺
And the water is so shallow.

0:04:09.260,0:04:10.920
# 下去應該能撈的到
Let me go into the pond. I should be able to catch them.

0:04:16.040,0:04:17.500
# 誒  魚呢
Ey? Where are the fish?

0:04:21.160,0:04:24.280
# 來  好多  你看
This way! A lot! Look!

0:04:31.780,0:04:32.840
# 差點翻車
I almost fell.

0:04:39.820,0:04:42.160
# 哎呀  全部跑啦  一條不剩
Aya! All run away. Even the last one.

0:04:48.580,0:04:49.600
# 踩我一腳
I stepped on something.

0:04:52.280,0:04:53.100
# 難搞啊
It's not that simple.

0:04:54.220,0:04:55.280
# 今天撈不到啦
We can't catch any today.

0:04:58.580,0:05:00.120
# 有沒有送上門來的
Anyone wants to come?

0:05:01.080,0:05:02.240
# 有沒有自願的
Any volunteers?

0:05:16.580,0:05:20.880
# 叫我弟他們過來  拿多幾個這個抄網  一起下來抓
Let me ask our brothers to come here, with some more, this kind of catch nets. We're gonna catch together here.

0:05:21.860,0:05:25.220
# 抓不到  太大的動靜啦  摸的到但是抓不到它
We can't catch any. We moved too much. We could only touch them, but not catch them.

0:05:26.100,0:05:27.380
# 打個電話叫他們過來
Let me give them a ring.

0:05:33.180,0:05:35.360
# 要不要換地方  換地方
Shall we move to another place? Move to another place.

0:05:37.620,0:05:38.960
# 換地方  換地方
Another place, another place.

0:05:43.260,0:05:44.300
# 跑啦  跑啦
It has run away.
Yup!

0:05:45.600,0:05:48.880
# 這邊這裡還有好多  別管那裡 / 別管那裡啦
Here are still a lot! Don't care about that side.
Forget about that side!

0:05:49.240,0:05:50.940
# 中間 中間 / 跑了就跑了
Middle, in the middle!
It has run away, leave if alone.

0:05:51.600,0:05:52.480
# 又跑了一條
We miss another one.

0:05:53.000,0:05:53.540
# 還有
Still more!

0:06:00.000,0:06:02.160
# 跑了  跑了再繼續  還有的
Missed. Missed then go on. There are still more.

0:06:14.520,0:06:18.240
# 看一下啊  就在這裡啦  那邊  看有沒有  這裡
Let's see. It's here. There! Any here?

0:06:20.880,0:06:24.780
# 搞不到  我去搞點那個網  再來試一下看行不行
It didn't work. I'm gonna get that kind of net and try again. Let's see if it works.

0:06:44.160,0:06:46.260
# 就是它跳我們也先不要動
Let's not start moving even if we see it jumping around.

0:06:46.260,0:06:47.100
# 直接抓住它
Instead, we just catch it right away.

0:06:51.540,0:06:53.020
# 直接去壓一來  壓下來
Press it down right away! Press!

0:06:54.640,0:06:55.520
# 別讓它跑
Don't let it run away.

0:07:00.820,0:07:01.520
# 抓住沒有
Did you get it?

0:07:02.080,0:07:04.300
# 沒抓住  抓到我的手了
No!
It's my hand!

0:07:05.620,0:07:06.240
# 繼續
Go on!

0:07:13.260,0:07:16.260
# 誒呦  想跑  抓住它  誒 / 跑啦又
Ayo! You wanna run away? Catch it! Ey!
Missed again.

0:07:17.140,0:07:19.280
# (沒有  你看XXX就壓下去)  (註︰沒有原字幕，但他說得都比較清楚)
No. Just press down whenever you see anything.

0:07:21.600,0:07:24.300
# 還有  還有  不要急 / 就跑了兩條
Still more. 
Still more. Stay calm. 

0:07:24.300,0:07:25.520
# (上一句分兩句)
We've only missed two.

0:07:28.060,0:07:28.840
# 看一下
Let me see.

0:07:34.160,0:07:35.900
# 又空了  沒了沒了
Missed again. No more, no more.

0:07:36.700,0:07:38.620
# 放水吧  抽水機抽水機
Drain the pond! Water pump! Water pump!

0:07:42.820,0:07:44.720
# 搞到一條  夠了
We got one! It's enough.

0:07:49.340,0:07:50.640
# 這條魚就夠大啦
This fish is really big.

0:08:02.560,0:08:03.840
# 放在邊上  別跑了
Put it on the side. Don't let it run away.

0:08:06.220,0:08:10.520
# 好啦  今天的視頻就到這裡啦  回去把它煮了
Alright! The video ends here. I'm gonna take it back home and cook it.
