### ISSUE TITLE
[雪鱼] 秦镇米皮【字幕少】 - https://youtu.be/TgmTdfdT7Kc

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#1372]
**视频链接**：https://youtu.be/TgmTdfdT7Kc

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
西安秦镇米皮

简介
秦镇米皮，一直全国出名，这次雪鱼专程来到陕西西安的秦镇，来看看秦镇的米皮是什么样子。刚到秦镇，满大街都是卖米皮的，最吸引我的是大妈的小吃摊，她切米皮的刀就有1米长，足足30斤，用这样的刀切米皮需要利用惯性把刀提起来，一上一下就把米皮切好了，大妈一天要切几百张，一天就要换一次桌布。这切米皮的手艺吸引人，比这更让人着迷的切好后加红辣椒油凉拌出来的米皮。米皮蘸过红油，一下子就焕发诱人食欲，这一份也只是卖6元。

字幕
1
00:00:02,480 --> 00:00:05,600
现在是在去往秦镇的路上

2
00:00:07,400 --> 00:00:11,480
走在这边 你发现路两边有很多人在招呼你

3
00:00:11,480 --> 00:00:15,320
他们呢 是招呼你进去吃米皮的

4
00:00:21,060 --> 00:00:23,340
这样的场面 原来只在海鲜市场遇到过

5
00:00:24,280 --> 00:00:27,080
没想到米皮也能竞争成这样的程度

6
00:00:28,120 --> 00:00:32,480
到达目的地

7
00:00:39,360 --> 00:00:41,480
满大街都是卖米皮的

8
00:01:11,980 --> 00:01:13,980
阿姨 这个刀重不重啊

9
00:01:13,980 --> 00:01:15,320
13斤

10
00:01:16,580 --> 00:01:17,320
您做米皮多久了啊

11
00:01:17,820 --> 00:01:19,820
俺在这干一辈子了

12
00:01:21,240 --> 00:01:23,840
从十来岁开始一直干到现在

13
00:01:27,960 --> 00:01:30,800
这是真正的做了三代人了

14
00:01:32,020 --> 00:01:34,020
切这个米皮都不用看吗

15
00:01:34,380 --> 00:01:36,380
熟练了 不用看

16
00:01:46,280 --> 00:01:48,280
阿姨 您切到过手吗

17
00:01:49,500 --> 00:01:50,560
还没有

18
00:01:59,880 --> 00:02:01,880
不轻吧 你掂着试试

19
00:02:02,540 --> 00:02:04,540
一般一个女人都拿不起来

20
00:02:15,040 --> 00:02:19,360
这一张米皮是两份 一份是6块钱

21
00:02:19,360 --> 00:02:25,080
阿姨做米皮的年头也很久了 切皮子的速度很快

22
00:02:25,400 --> 00:02:29,560
你看做肉夹馍的 需要不停地在案板上剁肉

23
00:02:29,560 --> 00:02:31,760
所以呢 他们比较费案板

24
00:02:31,760 --> 00:02:36,080
而像阿姨这种切米皮的 因为一天要切几百张皮子

25
00:02:36,080 --> 00:02:39,480
他们呢 需要经常换下面的这块布

26
00:02:45,760 --> 00:02:48,600
切好的米皮 蘸上辣子 加上豆芽

27
00:02:48,600 --> 00:02:51,440
满满的一碗端到跟前

28
00:02:54,520 --> 00:02:58,480
如果觉得这还不够 来瓶冰峰 再加个肉夹馍

29
00:02:58,480 --> 00:03:02,440
体验一下三秦套餐的魅力

30
00:03:19,080 --> 00:03:20,240
上头

31
00:04:03,880 --> 00:04:07,080
关  注
雪 鱼 探 店


```

**Comment by shuaisoserious** [comment]
认领

**Comment by shuaisoserious** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
西安秦镇米皮
Xi’an Qinzhen rice noodle
简介
秦镇米皮，一直全国出名，这次雪鱼专程来到陕西西安的秦镇，来看看秦镇的米皮是什么样子。刚到秦镇，满大街都是卖米皮的，最吸引我的是大妈的小吃摊，她切米皮的刀就有1米长，足足30斤，用这样的刀切米皮需要利用惯性把刀提起来，一上一下就把米皮切好了，大妈一天要切几百张，一天就要换一次桌布。这切米皮的手艺吸引人，比这更让人着迷的切好后加红辣椒油凉拌出来的米皮。米皮蘸过红油，一下子就焕发诱人食欲，这一份也只是卖6元。
Qinzhen rice noodle is famous in China, xueyu comes to Qinzhen in Shanxi, xi’an. To see how rice noodle in Qinzhen looks like, an aunt attracted me because her knife is about a meter long, and weighted 30 jin(15kg), and she chopped hundreds of rice noodle everyday, rice noodle attract me more than that aunt, because rice noodle with red oil dipping are very fragment, and only for 6 yuan each serve.
字幕
1
00:00:02,480 --> 00:00:05,600
现在是在去往秦镇的路上
We are on the way to Qinzhen now
2
00:00:07,400 --> 00:00:11,480
走在这边 你发现路两边有很多人在招呼你
A lot of people at two sides of road say hello to you when you walk on the street
3
00:00:11,480 --> 00:00:15,320
他们呢 是招呼你进去吃米皮的
They call you to eat rice noodle
4
00:00:21,060 --> 00:00:23,340
这样的场面 原来只在海鲜市场遇到过
It only happened in seafood market before
5
00:00:24,280 --> 00:00:27,080
没想到米皮也能竞争成这样的程度
I don’t know rice noodle has competition like this
6
00:00:28,120 --> 00:00:32,480
到达目的地
We arrived
7
00:00:39,360 --> 00:00:41,480
满大街都是卖米皮的
The whole street are selling rice noodle
8
00:01:11,980 --> 00:01:13,980
阿姨 这个刀重不重啊
Aunt, is the knife heavy?
9
00:01:13,980 --> 00:01:15,320
13斤
About 13 jin(6.5 kg)
10
00:01:16,580 --> 00:01:17,320
您做米皮多久了啊
How long have you do the rice noodle business
11
00:01:17,820 --> 00:01:19,820
俺在这干一辈子了
Since i was a kid
12
00:01:21,240 --> 00:01:23,840
从十来岁开始一直干到现在
It start since i was about ten years old
13
00:01:27,960 --> 00:01:30,800
这是真正的做了三代人了
It’s really been 3 generation
14
00:01:32,020 --> 00:01:34,020
切这个米皮都不用看吗
Don’t you even take a look at it when you chop the rice noodle?
15
00:01:34,380 --> 00:01:36,380
熟练了 不用看
No need, i’m very good at it
16
00:01:46,280 --> 00:01:48,280
阿姨 您切到过手吗
Aunt have you even hurt your finger
17
00:01:49,500 --> 00:01:50,560
还没有
Not yet
18
00:01:59,880 --> 00:02:01,880
不轻吧 你掂着试试
It’s pretty heavy right? You can try it
19
00:02:02,540 --> 00:02:04,540
一般一个女人都拿不起来
A women can’t even lift it
20
00:02:15,040 --> 00:02:19,360
这一张米皮是两份 一份是6块钱
One slice rice noodle is two pieces, 6 yuan each pieces
21
00:02:19,360 --> 00:02:25,080
阿姨做米皮的年头也很久了 切皮子的速度很快
Aunt working on rice noodle business for very long time, so she chop the rice noodle pretty fast
22
00:02:25,400 --> 00:02:29,560
你看做肉夹馍的 需要不停地在案板上剁肉
People who work on Rougamo business, they need to chop meat on the chopping board none stopped.
23
00:02:29,560 --> 00:02:31,760
所以呢 他们比较费案板
So they replaced chopping board frequently 
24
00:02:31,760 --> 00:02:36,080
而像阿姨这种切米皮的 因为一天要切几百张皮子
People like aunt who need chopped hundreds of rice noodle every day
25
00:02:36,080 --> 00:02:39,480
他们呢 需要经常换下面的这块布
They need replaced the cloth under the chopping board
26
00:02:45,760 --> 00:02:48,600
切好的米皮 蘸上辣子 加上豆芽
Chopped rice noodle with spicy dipping and sprout on it
27
00:02:48,600 --> 00:02:51,440
满满的一碗端到跟前
Full of a bowl to serve to you
28
00:02:54,520 --> 00:02:58,480
如果觉得这还不够 来瓶冰峰 再加个肉夹馍
If that’s not enough, order a Bingfeng(a soft drink), and a Rougamo
29
00:02:58,480 --> 00:03:02,440
体验一下三秦套餐的魅力
Experience the beauty of three qin combo(rice noodle, bingfeng and Rougamo)
30
00:03:19,080 --> 00:03:20,240
上头
comfortable
31
00:04:03,880 --> 00:04:07,080
关  注
雪 鱼 探 店
