### ISSUE TITLE
[雪鱼] 高原人的早餐牛杂汤 - https://youtu.be/eH8YiSUxzBw

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#1373]
**视频链接**：<https://youtu.be/eH8YiSUxzBw>
# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
高原人的早餐，凌晨4点喝牛杂汤，花30元选5种肉，大饼一泡吃着香

简介
西宁地处青藏高原东部，这儿的温差极大，人们的一天是从一碗牛杂汤开始的。早上4点，天还没有亮，小店的门口就已经有人来等着喝汤了。一上午的时间，几乎都是排队的状态。小店不大，只摆了几张桌子，门口一口大锅，热气腾腾的汤勾人食欲。老板正在剁牛杂，排队的时候就能听见剁肉的声音。一碗牛杂汤的价格从15元到30元不等，附带一个大饼。买一碗牛杂汤坐下，抱着喝汤，那种辛辣的感觉一下就祛除了身体的寒冷，碗里有5种牛杂，个个都炖地软烂，一口汤一口饼，再冷的高原都变得温暖。

字幕
1
00:00:01,560 --> 00:00:01,920
青海·西宁

2
00:00:02,040 --> 00:00:03,240
雪鱼现在还在西宁

3
00:00:03,240 --> 00:00:06,800
今天是起个大早 打算早早地去把早饭吃了

4
00:00:08,480 --> 00:00:12,040
现在是早上起来六点半 温度呢 只有9度

5
00:00:12,040 --> 00:00:15,600
比我前两天来的 都要冷

6
00:00:15,880 --> 00:00:18,640
已经把秋裤套上了

7
00:00:18,640 --> 00:00:22,360
这么清冷的天气 一定要吃点比较硬核的早餐

8
00:00:22,360 --> 00:00:25,760
像我们之前吃的羊肠面 就是比较富有能量

9
00:00:25,760 --> 00:00:29,200
今天呢 再吃个不一样的  就是牛杂汤

10
00:00:29,200 --> 00:00:31,240
这家店很小 还不太好找

11
00:00:31,240 --> 00:00:34,080
别人都叫它是 巷子里的米其林

12
00:00:34,120 --> 00:00:36,120
至于为什么会叫这个名字

13
00:00:36,120 --> 00:00:37,880
我觉得应该是有点贵吧

14
00:00:37,880 --> 00:00:39,640
走 去看看吧

15
00:00:46,080 --> 00:00:49,160
真是太冷了 我的鼻子都冻红了

16
00:00:58,680 --> 00:01:03,040
来的不晚啊 没想到还是有这么多人 比我要早到

17
00:01:16,280 --> 00:01:18,360
多少钱一碗

18
00:01:18,360 --> 00:01:20,220
有30元 20元的 最少是15元一碗的

19
00:01:20,320 --> 00:01:23,840
最少15 给我拿一个30的吧 加一个饼

20
00:01:23,840 --> 00:01:25,200
在这儿吃

21
00:01:25,200 --> 00:01:25,720
对

22
00:01:27,200 --> 00:01:31,600
每碗是配一个饼

23
00:01:35,720 --> 00:01:37,280
过去了

24
00:01:47,120 --> 00:01:49,240
30的是吧

25
00:01:49,240 --> 00:01:51,360
不是的 这是两个小碗的端

26
00:02:02,820 --> 00:02:04,820
这正好来了一锅新汤

27
00:02:36,480 --> 00:02:40,240
大哥 20块钱的和30块钱的有什么区别吗

28
00:02:40,240 --> 00:02:45,520
料是一样的 但是量不一样

29
00:03:18,760 --> 00:03:20,000
这个是我的吗

30
00:03:20,000 --> 00:03:20,920
对 30的

31
00:03:20,920 --> 00:03:22,320
好 谢谢

32
00:03:22,320 --> 00:03:24,280
到这边吧 那边没有位

33
00:03:29,280 --> 00:03:31,680
这是我们刚才排队买的牛杂汤

34
00:03:31,680 --> 00:03:34,600
奢华 顶配版 30块钱

35
00:03:34,600 --> 00:03:36,680
里面的内容 极其丰富

36
00:03:36,680 --> 00:03:42,200
看 像牛肚 牛肉还有切的很大块的牛肠

37
00:03:42,580 --> 00:03:44,580
先尝一口汤吧

38
00:03:45,960 --> 00:03:47,060
哇 被辣到

39
00:03:49,920 --> 00:03:52,080
这种辛辣 不仅是胡椒粉的辛辣

40
00:03:52,080 --> 00:03:54,080
还有大葱的辛辣

41
00:04:12,600 --> 00:04:17,680
说实话 我从来没有喝过一碗汤 是这个味道

42
00:04:19,960 --> 00:04:20,800
有些冲

43
00:04:20,800 --> 00:04:24,000
因为这边的温度 早晚的温度差异很大

44
00:04:24,000 --> 00:04:27,120
喝碗这种辛辣的汤 能够去除寒冷

45
00:04:27,120 --> 00:04:30,080
让你一早上 暖暖的

46
00:04:30,640 --> 00:04:32,640
味道指数：4颗星

47
00:04:36,120 --> 00:04:40,880
这里有一块牛肠

48
00:04:43,200 --> 00:04:46,800
肉其实没有什么特别的味道 就是处理的很干净

49
00:04:46,800 --> 00:04:50,920
这碗牛杂的味道 灵魂 全在汤里

50
00:04:50,920 --> 00:04:52,340
可免费无限加汤

51
00:04:56,800 --> 00:05:00,320
找到一根好肥硕的牛肚

52
00:05:06,000 --> 00:05:12,000
他们这边的牛杂为什么感觉都是那么的肥美又软烂

53
00:05:21,440 --> 00:05:23,800
大哥 这边是早上几点开门

54
00:05:24,840 --> 00:05:28,480
每天早上4点到上午10点半

55
00:05:28,920 --> 00:05:31,640
4点就开门了 这么早

56
00:05:31,640 --> 00:05:36,400
我们过来的时候 已经有等的人了 有的人已经在等着了

57
00:05:36,400 --> 00:05:39,440
像喝完酒的

58
00:05:39,920 --> 00:05:42,880
通宵的也是 他们都过来吃

59
00:05:49,080 --> 00:05:52,720
刚从小店出来 店里只有几张桌子 人挤得满满的

60
00:05:52,720 --> 00:05:54,840
刚才还是好不容易才找的座位

61
00:05:54,840 --> 00:05:57,680
好多人也都是一早 赶来吃这碗牛杂汤

62
00:06:08,160 --> 00:06:09,680
直接就在这儿吃了

63
00:06:09,680 --> 00:06:13,200
我先在这儿泡着 那没地方 里面都坐满了

64
00:06:17,280 --> 00:06:20,680
关 注
雪 鱼  探 店


```

**Comment by BOWEN0305772** [comment]
认领！

**Comment by BOWEN0305772** [comment]
认领

**Comment by BOWEN0305772** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
高原人的早餐，凌晨4点喝牛杂汤，花30元选5种肉，大饼一泡吃着香
Breakfast for Amdo people 4:00 am enjoying Beef offal soup, 30 Chinese Yuan for 5 opinions of offal. Eating the soup with a soak naan, fantastic! 
简介
西宁地处青藏高原东部，这儿的温差极大，人们的一天是从一碗牛杂汤开始的。早上4点，天还没有亮，小店的门口就已经有人来等着喝汤了。一上午的时间，几乎都是排队的状态。小店不大，只摆了几张桌子，门口一口大锅，热气腾腾的汤勾人食欲。老板正在剁牛杂，排队的时候就能听见剁肉的声音。一碗牛杂汤的价格从15元到30元不等，附带一个大饼。买一碗牛杂汤坐下，抱着喝汤，那种辛辣的感觉一下就祛除了身体的寒冷，碗里有5种牛杂，个个都炖地软烂，一口汤一口饼，再冷的高原都变得温暖。
Xining is a city where it is at eastern Qinghai-Tibet Plateau. The difference in temperature between morning and afternoon is great. People start their daily lives from a morning Beef offal soup. At early 4:00 am, before dawn, there are many people waiting for the soup. There is always a long line in front of the soup café during the whole morning. This café is not big. There are several tables and there is a cauldron near the door. The piping hot soup lets people feel starving. The boss of this Breakfast shop is cutting off the beef offal. When waiting in the line, you can hear the cutting voice. One bowl of soup is around 15 Yuan to 30 Yuan, with a naan. Sitting down and having a steaming soup, the taste of peppery gets rid of the chill of body. There are five different types of beef offal in the soup. Every kind of beef offal is boiled very soft. One soup with one bite of naan, the Plateau is going to get warm even it is such freeze before. 
字幕
1
00:00:01,560 --> 00:00:01,920
青海·西宁
Qinghai(Amdo)·Xining
2
00:00:02,040 --> 00:00:03,240
雪鱼现在还在西宁
Xue Yu is still at Xining
3
00:00:03,240 --> 00:00:06,800
今天是起个大早 打算早早地去把早饭吃了
I wake up so early today, now is time to eat breakfast. 
4
00:00:08,480 --> 00:00:12,040
现在是早上起来六点半 温度呢 只有9度
Now is 6:30 am in the morning, the temperature is 9°C. 
5
00:00:12,040 --> 00:00:15,600
比我前两天来的 都要冷
chiller than two days before when I just arrived 
6
00:00:15,880 --> 00:00:18,640
已经把秋裤套上了
Now I am wearing leggings under my pants to stay warm.
7
00:00:18,640 --> 00:00:22,360
这么清冷的天气 一定要吃点比较硬核的早餐
Such freeze morning, I need to find some tough food as my breakfast
8
00:00:22,360 --> 00:00:25,760
像我们之前吃的羊肠面 就是比较富有能量
Such like lamb offal noodle that we ate before, which is full of energy
9
00:00:25,760 --> 00:00:29,200
今天呢 再吃个不一样的  就是牛杂汤
Today we are going to try another different food, which is beef offal soup.
10
00:00:29,200 --> 00:00:31,240
这家店很小 还不太好找
This shop is so small that customers are hardly to find out it easily. 
11
00:00:31,240 --> 00:00:34,080
别人都叫它是 巷子里的米其林
People call it Michelin-starred restaurant in Hutong
12
00:00:34,120 --> 00:00:36,120
至于为什么会叫这个名字
Why do people call it that name?
13
00:00:36,120 --> 00:00:37,880
我觉得应该是有点贵吧
I think it is because the price is not cheap
14
00:00:37,880 --> 00:00:39,640
走 去看看吧
Let’s go
15
00:00:46,080 --> 00:00:49,160
真是太冷了 我的鼻子都冻红了
So cold, my nose is getting red
16
00:00:58,680 --> 00:01:03,040
来的不晚啊 没想到还是有这么多人 比我要早到
I came here not so late, but there are still so many people who came here earlier than me.
17
00:01:16,280 --> 00:01:18,360
多少钱一碗
How much for one bowl of soup?
18
00:01:18,360 --> 00:01:20,220
有30元 20元的 最少是15元一碗的
30 or 20 the cheapest one is 15
19
00:01:20,320 --> 00:01:23,840
最少15 给我拿一个30的吧 加一个饼
Well,15 is the cheapest…I will take 30 with a naan
20
00:01:23,840 --> 00:01:25,200
在这儿吃
Eat in？
21
00:01:25,200 --> 00:01:25,720
对
Yes 
22
00:01:27,200 --> 00:01:31,600
每碗是配一个饼
One soup with one naan
23
00:01:35,720 --> 00:01:37,280
过去了
Coming through
24
00:01:47,120 --> 00:01:49,240
30的是吧
30 Yuan,right?
25
00:01:49,240 --> 00:01:51,360
不是的 这是两个小碗的端
Not that one, that are two small bowls
26
00:02:02,820 --> 00:02:04,820
这正好来了一锅新汤
There is a pot of new soup
27
00:02:36,480 --> 00:02:40,240
大哥 20块钱的和30块钱的有什么区别吗
Bro, what is the difference between 20 soup and 30 soup? 
28
00:02:40,240 --> 00:02:45,520
料是一样的 但是量不一样
The beef is same, but the amount is different. 
29
00:03:18,760 --> 00:03:20,000
这个是我的吗
Is that for me?
30
00:03:20,000 --> 00:03:20,920
对 30的
Yes, 30 soup
31
00:03:20,920 --> 00:03:22,320
好 谢谢
Ok, thanks 
32
00:03:22,320 --> 00:03:24,280
到这边吧 那边没有位
Come here, there are some unoccupied seats. 
33
00:03:29,280 --> 00:03:31,680
这是我们刚才排队买的牛杂汤
This is the beef offal soup that we waited for a long line to buy
34
00:03:31,680 --> 00:03:34,600
奢华 顶配版 30块钱
Luxurious top-of-the-line 30 Yuan
35
00:03:34,600 --> 00:03:36,680
里面的内容 极其丰富
There are so many things in the soup
36
00:03:36,680 --> 00:03:42,200
看 像牛肚 牛肉还有切的很大块的牛肠
Look, ox tripe, beef and large size of ox intestine
37
00:03:42,580 --> 00:03:44,580
先尝一口汤吧
Let’s taste the soup first.
38
00:03:45,960 --> 00:03:47,060
哇 被辣到
Wow, the spicy taste gets me.
39
00:03:49,920 --> 00:03:52,080
这种辛辣 不仅是胡椒粉的辛辣
This kind of peppery is not just because of pepper
40
00:03:52,080 --> 00:03:54,080
还有大葱的辛辣
As well as the pungency of green onion
41
00:04:12,600 --> 00:04:17,680
说实话 我从来没有喝过一碗汤 是这个味道
To be honest, it is first time that I eat a beef soup in this kind of flavor 
42
00:04:19,960 --> 00:04:20,800
有些冲
Sharp taste 
43
00:04:20,800 --> 00:04:24,000
因为这边的温度 早晚的温度差异很大
Because the difference in temperature between morning and afternoon is great.
44
00:04:24,000 --> 00:04:27,120
喝碗这种辛辣的汤 能够去除寒冷
the beef soup with such sharp taste can get rid of chill of body.
45
00:04:27,120 --> 00:04:30,080
让你一早上 暖暖的
Let you be warm for the whole morning. 
46
00:04:30,640 --> 00:04:32,640
味道指数：4颗星
Flavor star: 4
47
00:04:36,120 --> 00:04:40,880
这里有一块牛肠
There is a piece of ox intestine.
48
00:04:43,200 --> 00:04:46,800
肉其实没有什么特别的味道 就是处理的很干净
No other weird smell or strange taste, the ox intestine is clean enough to be eaten.
49
00:04:46,800 --> 00:04:50,920
这碗牛杂的味道 灵魂 全在汤里
The soul of beef offal soup is soup itself. 
50
00:04:50,920 --> 00:04:52,340
可免费无限加汤
You can add extra soup for free
51
00:04:56,800 --> 00:05:00,320
找到一根好肥硕的牛肚
I find a such big ox intestine
52
00:05:06,000 --> 00:05:12,000
他们这边的牛杂为什么感觉都是那么的肥美又软烂
Why is the beef offal in the soup such tender and soft？
53
00:05:21,440 --> 00:05:23,800
大哥 这边是早上几点开门
Hi bro, when is your open time?
54
00:05:24,840 --> 00:05:28,480
每天早上4点到上午10点半
4:00 am to 10:30 am 
55
00:05:28,920 --> 00:05:31,640
4点就开门了 这么早
Open at 4:00 am? So early
56
00:05:31,640 --> 00:05:36,400
我们过来的时候 已经有等的人了 有的人已经在等着了
When we came the shop, there are already many people waiting here
57
00:05:36,400 --> 00:05:39,440
像喝完酒的
Like people who drank last night
58
00:05:39,920 --> 00:05:42,880
通宵的也是 他们都过来吃
Or people who stay up for the whole night. They would enjoy the soup. 
59
00:05:49,080 --> 00:05:52,720
刚从小店出来 店里只有几张桌子 人挤得满满的
We just came out from the café. There are several tables, so crowded
60
00:05:52,720 --> 00:05:54,840
刚才还是好不容易才找的座位
It took me a while to find the place to be seated. 
61
00:05:54,840 --> 00:05:57,680
好多人也都是一早 赶来吃这碗牛杂汤
Many people, they came the shop to eat the soup like me, at the early morning
62
00:06:08,160 --> 00:06:09,680
直接就在这儿吃了
They eat in the shop. 
63
00:06:09,680 --> 00:06:13,200
我先在这儿泡着 那没地方 里面都坐满了
We could stay here first, there is no room, all the seats are occupied. 
64
00:06:17,280 --> 00:06:20,680
关 注
雪 鱼  探 店
Follow my channel XUEYU TANDIAN
