### ISSUE TITLE
【美食作家王刚】给四伯做凉糕 - https://youtu.be/CUHjzdpBmH0

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1382]
**视频链接**：https://youtu.be/CUHjzdpBmH0

视频时长8:19，预计发布时间为北京时间8月14日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
王刚从师父那学来了老式“凉糕”比例，四伯说吃到小时候的味道了，好的凉糕要夹的起来！

简介
由于现在食品工艺的冲击，老式凉糕越来越少，现在大多数贩售的凉糕都是由半成品凉糕粉制作而成。四伯也多年没有吃到传统的风味了，所以既然学会了这门手艺，就来给家人邻里们做来尝尝，来找一找小时候的味道。

字幕
0:00:00.469,0:00:01.273
哈喽大家好

0:00:01.377,0:00:05.281
今天我用这个泡了五斤米

0:00:05.511,0:00:07.360
五斤桂朝米

0:00:07.360,0:00:08.747
然后昨晚上泡的

0:00:08.977,0:00:12.891
今天给我四伯爷做一个小时候的味道 凉糕

0:00:13.131,0:00:14.791
现在这个天气热得不得了

0:00:15.258,0:00:17.004
我四伯爷今天卖了肉回来

0:00:18.486,0:00:20.920
等一下我弄来冻到冰箱里面

0:00:20.920,0:00:21.597
要的啊

0:00:21.840,0:00:23.080
天气太大了

0:00:23.080,0:00:25.000
泡好了就用这个机子来打

0:00:25.344,0:00:26.280
把它打出来

0:00:26.280,0:00:30.040
其实我们用这个打比石磨推要快得多

0:00:30.040,0:00:32.720
因为这个不像豆花儿不像黄豆

0:00:32.720,0:00:35.386
黄豆当然是用那个石磨磨 磨得更好

0:00:35.560,0:00:36.430
因为越细越好

0:00:36.640,0:00:38.340
这个的话是机器更省力

0:00:38.632,0:00:39.050
来嘛

0:00:49.175,0:00:50.215
多了打2次就是

0:00:52.077,0:00:53.002
嗯 可以

0:01:03.058,0:01:04.916
好啦 这个已经磨完了

0:01:05.949,0:01:09.905
要是传统做法的话可能要磨个两个小时吧

0:01:10.167,0:01:11.249
要一两个小时

0:01:11.972,0:01:13.280
这个特别的快

0:01:14.465,0:01:18.110
我们现在把这个给它弄出来

0:01:18.110,0:01:19.572
因为底下有一层

0:01:20.240,0:01:21.569
有一点点粗

0:01:24.363,0:01:26.304
走嘛 我把这个洗哈洗了来

0:01:26.480,0:01:27.379
这哈咋个整

0:01:27.680,0:01:28.800
熬了撒就可以

0:01:28.906,0:01:29.906
机子你弄来洗了

0:01:29.906,0:01:34.058
啊 洗了 洗了之后我煮那个石灰水

0:01:34.620,0:01:36.540
我没干过 我清不到

0:01:36.826,0:01:37.348
不关事

0:01:37.540,0:01:39.724
我吃倒是吃过

0:01:54.530,0:01:56.380
好啦 我们这个水已经烧开了

0:01:56.874,0:01:59.420
石灰水烧开了之后让它再沉淀一下

0:02:00.300,0:02:02.580
沉淀完了之后把这个渣去掉

0:02:02.580,0:02:04.100
去掉了之后再把它烧开

0:02:04.380,0:02:06.897
然后就把这个米浆可以倒进去

0:02:07.672,0:02:08.260
先搅

0:02:08.719,0:02:10.706
搅到它适合的浓稠度了之后

0:02:10.706,0:02:14.184
再把它倒出来然后凉了之后就变成了凉糕

0:02:15.170,0:02:17.786
你看像我们这个上面飘的这个东西啊

0:02:18.287,0:02:20.339
其实它是因为空气

0:02:20.838,0:02:22.579
进去了就发生了一个反应

0:02:22.970,0:02:25.512
现在我们把它煮开了之后就让它沉淀

0:02:26.833,0:02:30.011
等一下面上这里会有一层 把它舀来扔掉

0:02:30.369,0:02:32.974
然后下面的那一层也不要 我们只要中间的水

0:02:33.257,0:02:35.936
待会儿沉淀好了我们再来煮凉糕

0:02:35.936,0:02:37.070
现在开始熬红糖

0:02:38.228,0:02:40.415
然后我们把这个红糖切碎

0:02:41.576,0:02:45.896
红糖的比例就是2斤糖 1斤多一点的水

0:02:46.963,0:02:49.075
如果水放太多了的话就稀一点

0:02:49.075,0:02:51.251
当然不喜欢吃太甜的可以多放水

0:02:56.435,0:03:00.167
好啦 我们把这里切好了就可以熬糖浆了

0:03:25.940,0:03:27.907
慢点的

0:03:28.854,0:03:33.097
慢点慢点 慢点 四伯爷不要慌嘛

0:03:34.342,0:03:37.595
太快了的话一哈就

0:03:40.000,0:03:42.461
这种凉糕硬是拷的 尽是用拷

0:03:44.045,0:03:45.940
还要拷快点诶

0:03:46.421,0:03:50.693
这个还有技术的 拷太快溅起来烫到人不得了

0:03:53.240,0:03:56.237
拷慢了这下面就糟了 粘锅

0:04:00.480,0:04:03.089
好好好 四伯爷先不倒了

0:04:03.620,0:04:05.233
不能倒了

0:04:06.443,0:04:09.259
好啦 我们这个按照比例已经做出来了

0:04:09.476,0:04:11.258
这个还多白

0:04:11.258,0:04:11.937
嗯

0:04:12.320,0:04:14.625
现在我们把它再煮一会儿

0:04:17.937,0:04:19.361
好啦 现在我们已经搞出来

0:04:19.361,0:04:20.489
我们都满头大汗

0:04:20.489,0:04:22.283
因为现在又是三伏天 热得不得了

0:04:23.180,0:04:24.649
一次性做这么多

0:04:24.820,0:04:28.809
等会儿叫乡亲邻里过来一起吃

0:04:30.039,0:04:32.503
你看这个效果非常的棒

0:04:37.348,0:04:40.083
这个木头盒子是跟我师傅借的

0:04:40.797,0:04:41.877
跟他借来用一下

0:04:42.820,0:04:46.252
我小时候就是他们就是用的这个

0:04:46.252,0:04:48.662
把它划成一块一块的挑着来卖

0:04:49.085,0:04:51.036
这一次做的就相当于是小时候的味道了

0:04:54.412,0:04:55.512
这里可能有50斤

0:04:55.766,0:04:56.545
50斤啊

0:04:56.545,0:04:56.949
嗯

0:04:57.070,0:04:58.127
差不多四五十斤

0:04:58.882,0:05:00.882
我们这个凉糕已经做了有

0:05:01.824,0:05:04.127
放了十几个小时了吧

0:05:04.270,0:05:04.639
嗯

0:05:04.639,0:05:05.720
是十多个小时

0:05:05.962,0:05:07.103
是昨天下午做的

0:05:07.103,0:05:09.983
然后今天又放了一会儿

0:05:10.140,0:05:12.543
到现在目前为止有15个小时左右了

0:05:12.999,0:05:14.858
然后我跟我师父借了这个

0:05:15.100,0:05:16.260
直接这样比起来

0:05:16.798,0:05:17.384
直接这样子

0:05:18.375,0:05:19.251
一划一划

0:05:19.909,0:05:21.335
干起撒 划撒

0:05:21.335,0:05:21.980
划来干起 要得

0:05:21.980,0:05:23.693
老子想吃得很了

0:05:25.623,0:05:26.637
开始划了 四伯爷

0:05:27.442,0:05:30.299
抵着这个（竹片）哈 不要挨着那个

0:05:32.497,0:05:32.780
好

0:05:33.361,0:05:35.620
这个还就是要划快一点 划慢了还不得行

0:05:35.620,0:05:36.100
嗯

0:05:36.100,0:05:37.463
划慢了要划烂

0:05:38.218,0:05:39.208
又打湿哈水

0:05:44.506,0:05:45.376
这哈竖着来

0:05:48.088,0:05:48.994
有点大坨了噶

0:05:48.994,0:05:51.344
好啦 现在我们这个已经划出来了

0:05:52.260,0:05:54.900
但是要先淋点水上去才好(分开）

0:05:56.200,0:05:57.209
才好把它弄出来

0:06:01.341,0:06:02.392
可能这一块会烂

0:06:03.316,0:06:04.331
不用（碗）我把它放这里面

0:06:04.620,0:06:05.346
放那里面冷着啊

0:06:05.521,0:06:06.837
放冰水里把它冰着

0:06:14.557,0:06:14.853
看

0:06:15.004,0:06:15.487
哇

0:06:15.687,0:06:16.383
来了火的

0:06:16.800,0:06:17.982
好安逸

0:06:20.030,0:06:21.957
还合适的很安

0:06:24.802,0:06:25.551
它还要跑

0:06:28.000,0:06:29.660
不关事

0:06:34.868,0:06:35.489
伯爷先来嘛

0:06:35.622,0:06:37.124
要的 我先欣赏哈

0:06:37.176,0:06:39.405
你给他数着嘛 看他吃得了几碗

0:06:43.863,0:06:44.799
安逸

0:06:45.926,0:06:48.208
哦哟 好大一碗的哦

0:06:50.227,0:06:52.019
快点哦 我这碗没得了

0:07:01.778,0:07:03.280
沺沺 来吃凉糕了

0:07:05.554,0:07:06.175
沺沺过来

0:07:09.083,0:07:10.089
没有调羹（勺子）

0:07:18.235,0:07:19.627
喊爷爷再吃一碗

0:07:19.765,0:07:21.654
我都吃完了这一碗

0:07:23.320,0:07:27.374
再来一碗 你说爷爷再吃一碗

0:07:33.680,0:07:35.960
这凉糕我伯爷吃了三块

0:07:36.347,0:07:37.546
可能有三斤多

0:07:37.720,0:07:39.080
我伯娘也吃了两碗多了

0:07:39.324,0:07:40.303
我还又在吃

0:07:40.343,0:07:41.088
我这是第二碗

0:07:42.053,0:07:43.432
这都是第四碗上了

0:07:43.735,0:07:45.072
吃是挺好吃的

0:07:45.320,0:07:47.680
就是怎么说呢 做这个有点麻烦

0:07:47.720,0:07:48.760
成本是很低

0:07:49.080,0:07:50.400
时间成本比较高

0:07:51.680,0:07:54.640
又不散 又嫩 又绵扎

0:07:54.660,0:07:55.120
嗯

0:07:55.460,0:07:57.020
夹得起来 看

0:07:57.600,0:07:58.900
夹得起来 又嫩

0:08:00.660,0:08:02.660
吃凉糕就是要这样子 嫩很了的不好吃

0:08:02.660,0:08:04.220
嫩很了要用勺子的不好吃

0:08:04.840,0:08:05.620
就这样夹来吃

0:08:05.620,0:08:06.180
嗯

0:08:06.480,0:08:08.780
好啦 本期视频就到这里 拜拜

0:08:09.720,0:08:10.500
拜拜

0:08:10.500,0:08:11.600
我吃了四大碗

0:08:11.600,0:08:12.400
拜拜

0:08:13.480,0:08:15.280
我吃了三碗了这碗吃了

0:08:15.340,0:08:16.300
吃了四大碗

0:08:17.660,0:08:18.340
真的好吃


```

**Comment by WuStevenShengyang** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
王刚从师父那学来了老式“凉糕”比例，四伯说吃到小时候的味道了，好的凉糕要夹的起来！
Wang Gang learned traditional rice cake recipe from his master. Uncle likes it. Taste like childhood.

简介
由于现在食品工艺的冲击，老式凉糕越来越少，现在大多数贩售的凉糕都是由半成品凉糕粉制作而成。四伯也多年没有吃到传统的风味了，所以既然学会了这门手艺，就来给家人邻里们做来尝尝，来找一找小时候的味道。
Nowadays, there aren't many traditional rice cake anymore since many made from rice cake powder. My uncle hasn't eaten traditional rice cake for years. Because I have learned this recipe, let's make it and bring our the taste of childhood.

字幕
0:00:00.469,0:00:01.273
哈喽大家好
Hello!

0:00:01.377,0:00:05.281
今天我用这个泡了五斤米
Today I have prepared 5 Jin(2.5kg) of rice.

0:00:05.511,0:00:07.360
五斤桂朝米
This is Guichao Rice.

0:00:07.360,0:00:08.747
然后昨晚上泡的
They have been soaked overnight.

0:00:08.977,0:00:12.891
今天给我四伯爷做一个小时候的味道 凉糕
I will make a childhood dish, cold rice cake, for my uncle.

0:00:13.131,0:00:14.791
现在这个天气热得不得了
Today is very hot.

0:00:15.258,0:00:17.004
我四伯爷今天卖了肉回来
My uncle has just came back from the butchery.

0:00:18.486,0:00:20.920
等一下我弄来冻到冰箱里面
We can put some meat into the freezer afterwards.

0:00:20.920,0:00:21.597
要的啊
Sure.

0:00:21.840,0:00:23.080
天气太大了
It is way to hot today.

0:00:23.080,0:00:25.000
泡好了就用这个机子来打
We will actually use this machine to mill the rice.

0:00:25.344,0:00:26.280
把它打出来
Using a machine

0:00:26.280,0:00:30.040
其实我们用这个打比石磨推要快得多
is way faster than using a stone mill.

0:00:30.040,0:00:32.720
因为这个不像豆花儿不像黄豆
Since those are not soy beans

0:00:32.720,0:00:35.386
黄豆当然是用那个石磨磨 磨得更好
that require the use of stone mill

0:00:35.560,0:00:36.430
因为越细越好
to create a better and smoother texture,

0:00:36.640,0:00:38.340
这个的话是机器更省力
using machine on rice is much more efficient.

0:00:38.632,0:00:39.050
来嘛
Let's do it.

0:00:49.175,0:00:50.215
多了打2次就是
We can mill it several times.

0:00:52.077,0:00:53.002
嗯 可以
That looks good.

0:01:03.058,0:01:04.916
好啦 这个已经磨完了
Now we have finished milling the rice.

0:01:05.949,0:01:09.905
要是传统做法的话可能要磨个两个小时吧
It might cost about two hours using a traditional mill.

0:01:10.167,0:01:11.249
要一两个小时
One or two hours.

0:01:11.972,0:01:13.280
这个特别的快
But this is really fast.

0:01:14.465,0:01:18.110
我们现在把这个给它弄出来
Now we will pour those out,

0:01:18.110,0:01:19.572
因为底下有一层
because the bottom layer

0:01:20.240,0:01:21.569
有一点点粗
is a little thicker.

0:01:24.363,0:01:26.304
走嘛 我把这个洗哈洗了来
Let's clean this up.

0:01:26.480,0:01:27.379
这哈咋个整
What do we do with the rice milk?

0:01:27.680,0:01:28.800
熬了撒就可以
You just steam it.

0:01:28.906,0:01:29.906
机子你弄来洗了
Are you going to clean the machine as well?

0:01:29.906,0:01:34.058
啊 洗了 洗了之后我煮那个石灰水
Yes, and I will boil the whitewash afterwards.

0:01:34.620,0:01:36.540
我没干过 我清不到
I have never done this before so I can't help.

0:01:36.826,0:01:37.348
不关事
It is fine.

0:01:37.540,0:01:39.724
我吃倒是吃过
But I have eaten it before.

0:01:54.530,0:01:56.380
好啦 我们这个水已经烧开了
Ok, this water is boiling.

0:01:56.874,0:01:59.420
石灰水烧开了之后让它再沉淀一下
We will let it subside for a while after boiling.

0:02:00.300,0:02:02.580
沉淀完了之后把这个渣去掉
After that, we will clean up the residues.

0:02:02.580,0:02:04.100
去掉了之后再把它烧开
Then boil it again.

0:02:04.380,0:02:06.897
然后就把这个米浆可以倒进去
Now we are ready to pour the rice milk in.

0:02:07.672,0:02:08.260
先搅
Stir.

0:02:08.719,0:02:10.706
搅到它适合的浓稠度了之后
After mixing to the right thickness,

0:02:10.706,0:02:14.184
再把它倒出来然后凉了之后就变成了凉糕
pour the mixture out and it will turn into rice cake.

0:02:15.170,0:02:17.786
你看像我们这个上面飘的这个东西啊
You see those things that are floating around.

0:02:18.287,0:02:20.339
其实它是因为空气
It because of air

0:02:20.838,0:02:22.579
进去了就发生了一个反应
getting in and starting a reaction.

0:02:22.970,0:02:25.512
现在我们把它煮开了之后就让它沉淀
We will let it subside after boiling.

0:02:26.833,0:02:30.011
等一下面上这里会有一层 把它舀来扔掉
Later on, there will be a layer of residues at the surface, which we will get rid of.

0:02:30.369,0:02:32.974
然后下面的那一层也不要 我们只要中间的水
There will be another layer at the bottom which we also don't need. We only need the whitewash in the middle.

0:02:33.257,0:02:35.936
待会儿沉淀好了我们再来煮凉糕
We will wait for a little while before we pour in the rice milk.

0:02:35.936,0:02:37.070
现在开始熬红糖
Now let's prepare the brown sugar.

0:02:38.228,0:02:40.415
然后我们把这个红糖切碎
We need to cut up the brown sugar.

0:02:41.576,0:02:45.896
红糖的比例就是2斤糖 1斤多一点的水
The ratio is: 2 Jin(1kg) of brown sugar with 1 Jin(0.5kg) of water.

0:02:46.963,0:02:49.075
如果水放太多了的话就稀一点
It will be too watery if you add to much water.

0:02:49.075,0:02:51.251
当然不喜欢吃太甜的可以多放水
However, you can certainly add more water if you don't like it to be overly sweet.

0:02:56.435,0:03:00.167
好啦 我们把这里切好了就可以熬糖浆了
Okay, now we are ready to make the syrup.

0:03:25.940,0:03:27.907
慢点的
Slowly.

0:03:28.854,0:03:33.097
慢点慢点 慢点 四伯爷不要慌嘛
Slowly, uncle don't panic.

0:03:34.342,0:03:37.595
太快了的话一哈就
It's bad to go too fast.

0:03:40.000,0:03:42.461
这种凉糕硬是拷的 尽是用拷
This kind of rice cake is made by mixing everything together.

0:03:44.045,0:03:45.940
还要拷快点诶
You need to mix faster.

0:03:46.421,0:03:50.693
这个还有技术的 拷太快溅起来烫到人不得了
This is actually a skill, if you mix it too fast the mixture will spatter out.

0:03:53.240,0:03:56.237
拷慢了这下面就糟了 粘锅
However, if you do it too slowly the mixture will stick to the bottom of the wok.

0:04:00.480,0:04:03.089
好好好 四伯爷先不倒了
Okay, uncle that is enough.

0:04:03.620,0:04:05.233
不能倒了
We can't pour in anymore.

0:04:06.443,0:04:09.259
好啦 我们这个按照比例已经做出来了
Okay, we have followed the right ratio.

0:04:09.476,0:04:11.258
这个还多白
This is pretty white.

0:04:11.258,0:04:11.937
嗯
Yes.

0:04:12.320,0:04:14.625
现在我们把它再煮一会儿
Now let's boil it for a little longer.

0:04:17.937,0:04:19.361
好啦 现在我们已经搞出来
Okay, we are done.

0:04:19.361,0:04:20.489
我们都满头大汗
We are sweating already.

0:04:20.489,0:04:22.283
因为现在又是三伏天 热得不得了
It is really hot recently.

0:04:23.180,0:04:24.649
一次性做这么多
I made so much rice cake at once.

0:04:24.820,0:04:28.809
等会儿叫乡亲邻里过来一起吃
I will let my neighbors to try it.

0:04:30.039,0:04:32.503
你看这个效果非常的棒
You see this looks quite decent.

0:04:37.348,0:04:40.083
这个木头盒子是跟我师傅借的
I borrowed this wooden box from my master.

0:04:40.797,0:04:41.877
跟他借来用一下
Borrowed from him.	

0:04:42.820,0:04:46.252
我小时候就是他们就是用的这个
When I was a kid, they used to carry those boxes with rice cake

0:04:46.252,0:04:48.662
把它划成一块一块的挑着来卖
and slice them into chunks to sell.

0:04:49.085,0:04:51.036
这一次做的就相当于是小时候的味道了
This time I am tasting my childhood.

0:04:54.412,0:04:55.512
这里可能有50斤
There might be 50 Jin(25kg) right here.

0:04:55.766,0:04:56.545
50斤啊
50 Jin(25 kg)?

0:04:56.545,0:04:56.949
嗯
Yes.

0:04:57.070,0:04:58.127
差不多四五十斤
About 40 Jin(20kg) to 50 Jin(25kg).

0:04:58.882,0:05:00.882
我们这个凉糕已经做了有
It's been

0:05:01.824,0:05:04.127
放了十几个小时了吧
more than ten hours.

0:05:04.270,0:05:04.639
嗯
Yea.

0:05:04.639,0:05:05.720
是十多个小时
About ten hours.

0:05:05.962,0:05:07.103
是昨天下午做的
We made this yesterday afternoon.

0:05:07.103,0:05:09.983
然后今天又放了一会儿
Until right now,

0:05:10.140,0:05:12.543
到现在目前为止有15个小时左右了
I guess it has been 15 hours.

0:05:12.999,0:05:14.858
然后我跟我师父借了这个
And I have also borrowed this from my master.

0:05:15.100,0:05:16.260
直接这样比起来
We will line it up like this.

0:05:16.798,0:05:17.384
直接这样子
And just

0:05:18.375,0:05:19.251
一划一划
slice it.

0:05:19.909,0:05:21.335
干起撒 划撒
Let's do it.

0:05:21.335,0:05:21.980
划来干起 要得
Yea!

0:05:21.980,0:05:23.693
老子想吃得很了
I want to try this so bad.

0:05:25.623,0:05:26.637
开始划了 四伯爷
I am starting, uncle.

0:05:27.442,0:05:30.299
抵着这个（竹片）哈 不要挨着那个
I need to line up with this piece of bamboo.

0:05:32.497,0:05:32.780
好
Yes.

0:05:33.361,0:05:35.620
这个还就是要划快一点 划慢了还不得行
I need to slice it quickly.

0:05:35.620,0:05:36.100
嗯
Yes.

0:05:36.100,0:05:37.463
划慢了要划烂
I will ruin the shape if I slice it too slowly.

0:05:38.218,0:05:39.208
又打湿哈水
Dip this in water.

0:05:44.506,0:05:45.376
这哈竖着来
Let's do it this way.

0:05:48.088,0:05:48.994
有点大坨了噶
That looks kind of big.

0:05:48.994,0:05:51.344
好啦 现在我们这个已经划出来了
Now we have slice out the chunks.

0:05:52.260,0:05:54.900
但是要先淋点水上去才好(分开）
But we still need to pour water 

0:05:56.200,0:05:57.209
才好把它弄出来
in order to separate them.

0:06:01.341,0:06:02.392
可能这一块会烂
This one might break.

0:06:03.316,0:06:04.331
不用（碗）我把它放这里面
Let's put this in here.

0:06:04.620,0:06:05.346
放那里面冷着啊
Let it cools down.

0:06:05.521,0:06:06.837
放冰水里把它冰着
Put this in ice water.

0:06:14.557,0:06:14.853
看
Look.

0:06:15.004,0:06:15.487
哇
Wow.

0:06:15.687,0:06:16.383
来了火的
Looks good.

0:06:16.800,0:06:17.982
好安逸
Nice.

0:06:20.030,0:06:21.957
还合适的很安
That looks really nice.

0:06:24.802,0:06:25.551
它还要跑
It kind of wiggles around.

0:06:28.000,0:06:29.660
不关事
No big deal.

0:06:34.868,0:06:35.489
伯爷先来嘛
Uncle, you try it first.

0:06:35.622,0:06:37.124
要的 我先欣赏哈
Sure, let me try it.

0:06:37.176,0:06:39.405
你给他数着嘛 看他吃得了几碗
You need to count and see how many bowls he can eat.

0:06:43.863,0:06:44.799
安逸
So nice.

0:06:45.926,0:06:48.208
哦哟 好大一碗的哦
Wow, this a big bowl.

0:06:50.227,0:06:52.019
快点哦 我这碗没得了
You gotta be fast, I am almost finished.

0:07:01.778,0:07:03.280
沺沺 来吃凉糕了
Tiantian, come to eat rice cake.

0:07:05.554,0:07:06.175
沺沺过来
Come here.

0:07:09.083,0:07:10.089
没有调羹（勺子）
I don't have a spoon though.

0:07:18.235,0:07:19.627
喊爷爷再吃一碗
Call your grandpa to eat another bowl.

0:07:19.765,0:07:21.654
我都吃完了这一碗
I have already finished this one.

0:07:23.320,0:07:27.374
再来一碗 你说爷爷再吃一碗
One more, say this to your grandpa.

0:07:33.680,0:07:35.960
这凉糕我伯爷吃了三块
My uncle has already eaten three chunks of rice cake.

0:07:36.347,0:07:37.546
可能有三斤多
About 1.5kg.

0:07:37.720,0:07:39.080
我伯娘也吃了两碗多了
And my aunt has eaten two chunks.

0:07:39.324,0:07:40.303
我还又在吃
I am still eating as well.

0:07:40.343,0:07:41.088
我这是第二碗
This is my second chunk.

0:07:42.053,0:07:43.432
这都是第四碗上了
It's already my fourth bowl.

0:07:43.735,0:07:45.072
吃是挺好吃的
It's really tasty.

0:07:45.320,0:07:47.680
就是怎么说呢 做这个有点麻烦
But this rice cake is kind of tedious to make.

0:07:47.720,0:07:48.760
成本是很低
It doesn't cost much money,

0:07:49.080,0:07:50.400
时间成本比较高
but a lot of time.

0:07:51.680,0:07:54.640
又不散 又嫩 又绵扎
This is firm, tender, and smooth.

0:07:54.660,0:07:55.120
嗯
Yea.

0:07:55.460,0:07:57.020
夹得起来 看
I can pick it up with my chopsticks, see.

0:07:57.600,0:07:58.900
夹得起来 又嫩
It's really tender.

0:08:00.660,0:08:02.660
吃凉糕就是要这样子 嫩很了的不好吃
This is a good rice cake. Those that are way too tender aren't good.

0:08:02.660,0:08:04.220
嫩很了要用勺子的不好吃
To the point that you need a spoon to eat it.

0:08:04.840,0:08:05.620
就这样夹来吃
It's good to eat it like this with chopsticks.

0:08:05.620,0:08:06.180
嗯
Yes.

0:08:06.480,0:08:08.780
好啦 本期视频就到这里 拜拜
Okay, this is it for this video. See you!

0:08:09.720,0:08:10.500
拜拜
Bye!

0:08:10.500,0:08:11.600
我吃了四大碗
Four bowls.

0:08:11.600,0:08:12.400
拜拜
Bye!

0:08:13.480,0:08:15.280
我吃了三碗了这碗吃了
I have eaten three bowls already.

0:08:15.340,0:08:16.300
吃了四大碗
Four bowls.

0:08:17.660,0:08:18.340
真的好吃
It's so good.
