### ISSUE TITLE
【美食作家王刚】摘菜摘梨 - https://youtu.be/0PdX_lG2sEg

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1385]
**视频链接**：https://youtu.be/0PdX_lG2sEg

视频时长5:52，预计发布时间为北京时间8月15日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
王刚爷爷留下的梨树结下了超大果实，每一口都很甜！

简介
老家的梨树结果子了，之前总是被小鸟蜜蜂叨扰，果子结的不是很好，今年特地保护了起来，结下来的梨饱满多汁。这颗梨树据四伯说是当年我爷爷种下的，到现在少说也有五十多年了，老宅和这梨树已经静静地陪了我们三代人，希望以后还可以更长长久久。

字幕
0:00:02.988,0:00:04.136
搞深点的

0:00:04.938,0:00:05.804
掐深点的啊

0:00:06.824,0:00:07.717
我这边挨着挨着掐的

0:00:08.537,0:00:12.250
今天我们摘一点这个空心菜回去吃

0:00:13.722,0:00:17.129
我四伯爷种这个长得太快了 吃不完

0:00:17.649,0:00:18.779
 搞不赢吃这个

0:00:19.208,0:00:20.546
你哪里搞得赢哦

0:00:20.865,0:00:24.291
还有这些辣椒再不摘的话晒都给它晒烂了

0:00:24.710,0:00:27.881
然后待会再上去摘点梨吃一下

0:00:27.881,0:00:28.938
现在梨也熟了

0:00:29.913,0:00:30.460
多摘点

0:00:32.072,0:00:34.139
煎得到两顿都可以了

0:00:34.806,0:00:36.507
这个菜啊都是自己种的

0:00:37.047,0:00:38.669
要吃的话现摘

0:00:38.877,0:00:40.337
而且就在我们家院子

0:00:40.492,0:00:41.694
随时都可以整来吃

0:00:42.742,0:00:43.116
就是

0:00:45.904,0:00:47.845
根子弄来扔了就是

0:00:48.045,0:00:49.312
可以吃两顿了这个

0:00:49.968,0:00:50.359
好

0:00:51.271,0:00:53.302
还有一些没掐到

0:00:53.394,0:00:55.231
摘点海椒嘛 加点海椒炒起安逸

0:00:55.735,0:00:56.236
要的啊

0:00:56.564,0:00:56.902
嗯

0:00:57.594,0:00:59.170
这个我感觉没得好辣的这个海椒

0:00:59.289,0:01:00.300
这个是二荆条

0:01:00.628,0:01:00.984
啊

0:01:01.904,0:01:04.009
再弄几个朝天椒一起炒

0:01:04.464,0:01:05.148
要的啊

0:01:05.995,0:01:07.088
 这种就辣哦

0:01:07.307,0:01:08.728
啊 混在里面

0:01:09.503,0:01:11.754
我还弄断了一个枝

0:01:14.879,0:01:16.529
还长开花了你看

0:01:16.719,0:01:17.146
嗯嗯

0:01:18.915,0:01:19.480
好

0:01:20.082,0:01:22.268
摘点鱼香嘛 下次可以煮点鱼

0:01:22.391,0:01:23.362
可以安

0:01:23.471,0:01:24.592
这不摘死都死了（过季）

0:01:26.633,0:01:29.075
等我下次去钓点鱼回来烧给你吃

0:01:29.585,0:01:30.241
要的啊

0:01:34.414,0:01:36.172
他们都在打谷子了嘎

0:01:36.656,0:01:39.271
是哦 我们都要迟点 

0:01:39.271,0:01:43.359
人家那些 我今天出去看到那些

0:01:43.936,0:01:46.888
基本上都要打完了

0:01:48.218,0:01:53.028
是 我上去弄点梨子下来吃

0:01:54.022,0:01:55.844
四伯爷帮我扶着楼梯

0:01:58.591,0:02:00.241
拿个篮子上来嘛不是

0:02:00.444,0:02:01.237
 口袋

0:02:01.237,0:02:02.704
要的嘛 拿个口袋上来

0:02:03.873,0:02:05.814
 四伯爷你的背后有个笋子虫 那儿

0:02:06.876,0:02:07.565
哪里哦

0:02:07.840,0:02:09.908
那儿那儿 

0:02:10.139,0:02:10.713
  笋子虫

0:02:12.530,0:02:15.582
这么大的梨 太可惜了

0:02:16.107,0:02:17.301
真的是

0:02:20.815,0:02:21.598
这个也烂了

0:02:22.761,0:02:25.531
 哇 这个巨无霸这个

0:02:26.802,0:02:27.979
这个也有一斤

0:02:28.192,0:02:28.848
这个好

0:02:29.212,0:02:30.880
 先暂时放在一起

0:02:32.085,0:02:32.604
这个呢

0:02:34.068,0:02:35.271
这个也摘了吧

0:02:38.739,0:02:39.778
看这个梨

0:02:41.631,0:02:42.743
哇 这个也挺好

0:02:44.077,0:02:46.413
二娃 你在那儿站起看那边的三个

0:02:46.413,0:02:47.613
那边那三个

0:02:47.613,0:02:49.207
我过去看

0:02:51.547,0:02:52.422
这个都烂了

0:02:52.422,0:02:55.056
那外面的三个干脆一哈摘了

0:02:55.056,0:02:56.649
免得它坏了可惜了

0:02:56.867,0:03:00.177
好我过去看  大丰收了今年

0:03:03.225,0:03:05.011
哇 这个最大

0:03:07.692,0:03:09.235
四伯爷这个起码一斤多

0:03:09.990,0:03:11.333
真的安逸今年子这个

0:03:12.233,0:03:13.098
好大哦那个

0:03:16.737,0:03:18.131
哇塞 这个呢 

0:03:19.388,0:03:20.318
这个也是好的

0:03:28.378,0:03:29.833
 最近这个天确实很热

0:03:29.833,0:03:31.509
摘个梨满头大汗

0:03:32.085,0:03:33.105
现在准备下去了

0:03:34.402,0:03:38.065
今天收获了几十斤梨

0:03:38.350,0:03:39.830
好 现在我要下去了

0:03:41.501,0:03:43.873
四伯爷过来提哈梨子 多得很

0:03:45.709,0:03:46.265
来嘛 四伯爷

0:03:47.877,0:03:48.515
重得很

0:03:49.724,0:03:51.373
几十斤这个

0:03:52.622,0:03:53.879
 丢都丢了好多个

0:03:54.087,0:03:55.435
丢都丢了十几个

0:03:57.683,0:03:59.095
我们家的梨这么大一个

0:04:00.296,0:04:01.936
 害怕往年都没有结到这么大个

0:04:01.936,0:04:04.491
都这么大个

0:04:04.491,0:04:06.538
可能都是被鸟吃了

0:04:06.747,0:04:09.923
被鸟吃了 蜜蜂也要蛰

0:04:10.139,0:04:10.740
蜜蜂要蛰

0:04:10.740,0:04:13.969
蜜蜂爱得很 这些烂的就是蜜蜂干的事

0:04:14.995,0:04:16.477
好梨子它就要吃安

0:04:17.330,0:04:19.681
我们去年的时候正好在修房子

0:04:19.681,0:04:21.594
那个时候梨全部被鸟吃了

0:04:22.187,0:04:24.946
所以今年我们就把它给（裹起来)

0:04:25.282,0:04:27.678
不关事 这个皮子有点厚我就把它削厚点

0:04:29.638,0:04:32.207
我少吃点 我整不动

0:04:33.382,0:04:34.539
我还是少划点

0:04:38.350,0:04:41.349
看嘛 这才是本地梨子的味道

0:04:42.354,0:04:43.047
慢点哈

0:04:47.414,0:04:48.152
好吃嘛

0:04:48.152,0:04:48.671
嗯 

0:04:53.030,0:04:54.096
水分特别足

0:04:54.420,0:04:55.522
这梨子树好多年了

0:04:55.522,0:04:57.800
水分足得很这梨子的

0:04:58.424,0:05:01.242
自带一点点果酸味有一点点酸

0:05:03.410,0:05:04.595
我们这棵树好久了

0:05:04.837,0:05:05.320
几十年了

0:05:05.725,0:05:06.135
好多安

0:05:06.696,0:05:08.391
我记事的时候就有了

0:05:14.041,0:05:15.927
应该这个树有50年左右吧

0:05:16.852,0:05:18.538
然后下面把它保护好一点

0:05:19.107,0:05:21.968
结出更多的梨 到时候跟粉丝分享

0:05:21.968,0:05:24.565
（以前）那会结得才安逸 过路的都要摘

0:05:25.116,0:05:26.546
你问你伯爷嘛

0:05:27.409,0:05:30.107
你伯爷背上是啥子安

0:05:30.107,0:05:30.763
石灰

0:05:33.756,0:05:35.231
摘个梨我全身都湿透了

0:05:35.466,0:05:37.516
好 本期视频就到这里 拜拜

0:05:40.500,0:05:41.512
等会我吃这个

0:05:42.595,0:05:43.570
拿回去撒

0:05:45.653,0:05:46.865
带回去嘛把这些


```

**Comment by immoonancient** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
王刚爷爷留下的梨树结下了超大果实，每一口都很甜！
Pear Tree Planted by Wang Gang's Grandfather is Bearing Super Big Pears. Taste so Sweet!

简介
老家的梨树结果子了，之前总是被小鸟蜜蜂叨扰，果子结的不是很好，
今年特地保护了起来，结下来的梨饱满多汁。
这颗梨树据四伯说是当年我爷爷种下的，到现在少说也有五十多年了，
老宅和这梨树已经静静地陪了我们三代人，希望以后还可以更长长久久。
The pear tree in my hometown is bearing fruits.
Before, they were always eaten by birds and bees, so the yield wasn't great.
This year, we protected them specifically, so the pears are full and juicy.
Uncle said that the pear tree was planted by my grandfather, which was at least 50 years ago.
The old house and the pear tree have accompanied the tree generations of us. I wish they last long.

字幕
0:00:02.988,0:00:04.136
搞深点的
Deeper

0:00:04.938,0:00:05.804
掐深点的啊
Pick deeper?

0:00:06.824,0:00:07.717
我这边挨着挨着掐的
I'm picking one next to another

0:00:08.537,0:00:12.250
今天我们摘一点这个空心菜回去吃
Today, we're picking some water spinach to eat

0:00:13.722,0:00:17.129
我四伯爷种这个长得太快了 吃不完
Uncle planted it. It grows too fast, we can't finish it

0:00:17.649,0:00:18.779
搞不赢吃这个
We can't win against it

0:00:19.208,0:00:20.546
你哪里搞得赢哦
How can you win against it?

0:00:20.865,0:00:24.291
还有这些辣椒再不摘的话晒都给它晒烂了
And these peppers. If we don't pick them now, they'll rot under the sun

0:00:24.710,0:00:27.881
然后待会再上去摘点梨吃一下
Then we'll climb up there and pick some pears to eat

0:00:27.881,0:00:28.938
现在梨也熟了
Now the pears are also ripe

0:00:29.913,0:00:30.460
多摘点
I'll pick more

0:00:32.072,0:00:34.139
煎得到两顿都可以了
It'll be good 

0:00:34.806,0:00:36.507
这个菜啊都是自己种的
We planted these veggies ourselves

0:00:37.047,0:00:38.669
要吃的话现摘
We pick whenever we want

0:00:38.877,0:00:40.337
而且就在我们家院子
And they are just in our yard

0:00:40.492,0:00:41.694
随时都可以整来吃
Pick whenever we want

0:00:42.742,0:00:43.116
就是
Exactly

0:00:45.904,0:00:47.845
根子弄来扔了就是
Just get rid of the roots

0:00:48.045,0:00:49.312
可以吃两顿了这个
This is enough for two meals

0:00:49.968,0:00:50.359
好
Alright

0:00:51.271,0:00:53.302
还有一些没掐到
I haven't picked them all

0:00:53.394,0:00:55.231
摘点海椒嘛 加点海椒炒起安逸
Let's pick some peppers to cook together. It will be nice

0:00:55.735,0:00:56.236
要的啊
Sure

0:00:56.564,0:00:56.902
嗯
Hmm

0:00:57.594,0:00:59.170
这个我感觉没得好辣的这个海椒
I feel like these peppers are not really spicy

0:00:59.289,0:01:00.300
这个是二荆条
These are Erjingtiao

0:01:00.628,0:01:00.984
啊
Ah

0:01:01.904,0:01:04.009
再弄几个朝天椒一起炒
Also some Chaotianjiao to cook together

0:01:04.464,0:01:05.148
要的啊
Sure

0:01:05.995,0:01:07.088
这种就辣哦
These are the spicy ones

0:01:07.307,0:01:08.728
啊 混在里面
Ah, put them together

0:01:09.503,0:01:11.754
我还弄断了一个枝
I broke a branch

0:01:14.879,0:01:16.529
还长开花了你看
It even bloomed. Look

0:01:16.719,0:01:17.146
嗯嗯
Hmm

0:01:18.915,0:01:19.480
好
Alright

0:01:20.082,0:01:22.268
摘点鱼香嘛 下次可以煮点鱼
How about some Yuxiang? We can make a fish stew next time

0:01:22.391,0:01:23.362
可以安
Of course

0:01:23.471,0:01:24.592
这不摘死都死了（过季）
If we don't pick, it's going to die (out of season)

0:01:26.633,0:01:29.075
等我下次去钓点鱼回来烧给你吃
Next time I go fishing, I'll cook it for you

0:01:29.585,0:01:30.241
要的啊
Sure

0:01:34.414,0:01:36.172
他们都在打谷子了嘎
They have been harvesting rice already?

0:01:36.656,0:01:39.271
是哦 我们都要迟点
Yeah. We are a bit late

0:01:39.271,0:01:43.359
人家那些 我今天出去看到那些
The other people-- I mean those I saw today

0:01:43.936,0:01:46.888
基本上都要打完了
They have basically finished harvesting

0:01:48.218,0:01:53.028
是 我上去弄点梨子下来吃
Yeah. I'll climb up and pick some pears

0:01:54.022,0:01:55.844
四伯爷帮我扶着楼梯
Could you hold the ladder for me, uncle?

0:01:58.591,0:02:00.241
拿个篮子上来嘛不是
Do you need a basket?

0:02:00.444,0:02:01.237
口袋
Bag

0:02:01.237,0:02:02.704
要的嘛 拿个口袋上来
Sure. Get a bag!

0:02:03.873,0:02:05.814
四伯爷你的背后有个笋子虫 那儿
Uncle, there's a bamboo weevil behind you. Over there

0:02:06.876,0:02:07.565
哪里哦
Where?

0:02:07.840,0:02:09.908
那儿那儿 
Over there

0:02:10.139,0:02:10.713
笋子虫
Bamboo weaver

0:02:12.530,0:02:15.582
这么大的梨 太可惜了
What a big pear! But it's wasted

0:02:16.107,0:02:17.301
真的是
Geez

0:02:20.815,0:02:21.598
这个也烂了
This is rotten, too

0:02:22.761,0:02:25.531
哇 这个巨无霸这个
Wow, this one is gigantic

0:02:26.802,0:02:27.979
这个也有一斤
This is over 1 jin (500g)

0:02:28.192,0:02:28.848
这个好
A good one

0:02:29.212,0:02:30.880
先暂时放在一起
Put them together for now

0:02:32.085,0:02:32.604
这个呢
How about this?

0:02:34.068,0:02:35.271
这个也摘了吧
I'm also picking it

0:02:38.739,0:02:39.778
看这个梨
Let's check this pear

0:02:41.631,0:02:42.743
哇 这个也挺好
Wow, this is also good

0:02:44.077,0:02:46.413
二娃 你在那儿站起看那边的三个
译者注：这里的“二娃”应该指的是王刚而不是漆二娃。为了避免读者混乱就模糊处理了
Kid, stand up and look over there! There are three

0:02:46.413,0:02:47.613
那边那三个
Three over there

0:02:47.613,0:02:49.207
我过去看
I'll take a look

0:02:51.547,0:02:52.422
这个都烂了
This is already rotten

0:02:52.422,0:02:55.056
那外面的三个干脆一哈摘了
How about picking those three together?

0:02:55.056,0:02:56.649
免得它坏了可惜了
Before they rot and get wasted

0:02:56.867,0:03:00.177
好我过去看  大丰收了今年
OK, I'll go and check! What a harvest this year!

0:03:03.225,0:03:05.011
哇 这个最大
Wow, this is the biggest one

0:03:07.692,0:03:09.235
四伯爷这个起码一斤多
Uncle, this is at least 1 jin, or even more

0:03:09.990,0:03:11.333
真的安逸今年子这个
It's really nice this year

0:03:12.233,0:03:13.098
好大哦那个
That's a very big one

0:03:16.737,0:03:18.131
哇塞 这个呢 
Wow, how about this one?

0:03:19.388,0:03:20.318
这个也是好的
Also a good one

0:03:28.378,0:03:29.833
最近这个天确实很热
It's really hot recently

0:03:29.833,0:03:31.509
摘个梨满头大汗
I just picked some pears, and I'm already soaked in sweat

0:03:32.085,0:03:33.105
现在准备下去了
Now I'm getting down

0:03:34.402,0:03:38.065
今天收获了几十斤梨
Today, we harvested dozens of jin of pears

0:03:38.350,0:03:39.830
好 现在我要下去了
Alright, now I'm getting down

0:03:41.501,0:03:43.873
四伯爷过来提哈梨子 多得很
Uncle, come here and take some pears. There's a lot

0:03:45.709,0:03:46.265
来嘛 四伯爷
Come, uncle

0:03:47.877,0:03:48.515
重得很
It's heavy

0:03:49.724,0:03:51.373
几十斤这个
Dozens of jin

0:03:52.622,0:03:53.879
丢都丢了好多个
You already threw away many pears

0:03:54.087,0:03:55.435
丢都丢了十几个
Threw away a dozen of pears

0:03:57.683,0:03:59.095
我们家的梨这么大一个
Our pears are like this big

0:04:00.296,0:04:01.936
害怕往年都没有结到这么大个
I guess they wern't this large in the past years?

0:04:01.936,0:04:04.491
都这么大个
They've all been this big

0:04:04.491,0:04:06.538
可能都是被鸟吃了
Maybe the birds ate them

0:04:06.747,0:04:09.923
被鸟吃了 蜜蜂也要蛰
Birds ate them. And bees stung them

0:04:10.139,0:04:10.740
蜜蜂要蛰
Even bees?

0:04:10.740,0:04:13.969
蜜蜂爱得很 这些烂的就是蜜蜂干的事
Bees love them! They made those rotten ones 

0:04:14.995,0:04:16.477
好梨子它就要吃安
These are good pears. They also want to eat some

0:04:17.330,0:04:19.681
我们去年的时候正好在修房子
Last year we were building the house

0:04:19.681,0:04:21.594
那个时候梨全部被鸟吃了
The pears were all eaten by the birds

0:04:22.187,0:04:24.946
所以今年我们就把它给（裹起来)
So this year, we've wrapped them up

0:04:25.282,0:04:27.678
不关事 这个皮子有点厚我就把它削厚点
The peel is a bit thick, so I'll cut deeper

0:04:29.638,0:04:32.207
我少吃点 我整不动
I'll just have a little. I can't bite

0:04:33.382,0:04:34.539
我还是少划点
I'll have a

0:04:38.350,0:04:41.349
看嘛 这才是本地梨子的味道
Check it out, this is how local pears taste like

0:04:42.354,0:04:43.047
慢点哈
Enjoy

0:04:47.414,0:04:48.152
好吃嘛
Is it good?

0:04:48.152,0:04:48.671
嗯
Hmm

0:04:53.030,0:04:54.096
水分特别足
This is especially juicy

0:04:54.420,0:04:55.522
这梨子树好多年了
This pear tree is so many years old

0:04:55.522,0:04:57.800
水分足得很这梨子的
This pear is very juicy

0:04:58.424,0:05:01.242
自带一点点果酸味有一点点酸
It has a bit of fruit acidity

0:05:03.410,0:05:04.595
我们这棵树好久了
How old is the tree?

0:05:04.837,0:05:05.320
几十年了
Dozens of years

0:05:05.725,0:05:06.135
好多安
How many?

0:05:06.696,0:05:08.391
我记事的时候就有了
Since I was a kid

0:05:14.041,0:05:15.927
应该这个树有50年左右吧
The tree should be about fifty years old

0:05:16.852,0:05:18.538
然后下面把它保护好一点
译者注：这里中文字幕似乎有误，我听到的是“下一年把它保护好一点”
And we are going to protect it better next year

0:05:19.107,0:05:21.968
结出更多的梨 到时候跟粉丝分享
So that it yields more pears. I'll share with you then

0:05:21.968,0:05:24.565
（以前）那会结得才安逸 过路的都要摘
Before, it was bearing even more. Even passersby could pick some

0:05:25.116,0:05:26.546
你问你伯爷嘛
Your uncle knows it

0:05:27.409,0:05:30.107
你伯爷背上是啥子安
What's on the back of your uncle?

0:05:30.107,0:05:30.763
石灰
Lime

0:05:33.756,0:05:35.231
摘个梨我全身都湿透了
I'm soaked in sweat after picking these pears

0:05:35.466,0:05:37.516
好 本期视频就到这里 拜拜
Alright, that's it for this video. Bye bye!

0:05:40.500,0:05:41.512
等会我吃这个
I'll have this one later

0:05:42.595,0:05:43.570
拿回去撒
Take it home

0:05:45.653,0:05:46.865
带回去嘛把这些
Take them back home
