### ISSUE TITLE
【美食作家王刚】西瓜的几种切法 - https://youtu.be/gMWQXBvrZ8Q

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1388]
**视频链接**：https://youtu.be/gMWQXBvrZ8Q

视频时长1:44，预计发布时间为北京时间8月16日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨房小技巧：西瓜的几种切法，踩住夏天的尾巴吃西瓜

简介
大家好，今天和大家分享几种快速切西瓜的小技巧，大家尽量使用专用的水果菜板来切来避免西瓜串味，如果没有专用菜板也可以用保鲜膜将菜板包住或者在大盘子上操作。这些方法中我最喜欢的是第二种，浪费非常少，并且直接成块倒出即可，西瓜的汁水也较好的保留了下来，为了给大家比较好的展示所以扣在菜板上操作，大家也可以翻过来操作，这样也能有效避免瓜瓤接触菜板。

字幕
0:00:00.161,0:00:01.280
哈喽大家好我是王刚

0:00:01.280,0:00:02.809
本期视频我跟大家分享

0:00:03.150,0:00:05.050
西瓜的多种切法

0:00:05.360,0:00:06.859
首先我们来切第一种

0:00:07.440,0:00:09.880
将西瓜整齐地切成三厘米左右的厚片

0:00:11.659,0:00:13.840
然后用尖刀沿着瓜皮转一圈

0:00:13.840,0:00:15.702
这样可以把瓜肉分离

0:00:18.739,0:00:22.369
最后再根据个人喜好划出方形或者菱形块即可

0:00:29.160,0:00:31.905
第二种是直接切开西瓜分成两边

0:00:33.248,0:00:35.833
翻过来用小刀插进去横着切一半

0:00:39.457,0:00:42.209
再取出尖刀横向隔开几厘米继续切

0:00:46.323,0:00:48.340
然后继续纵向隔开几厘米

0:00:48.340,0:00:49.907
以同样的手法切到底部

0:00:50.173,0:00:52.058
瓜背切好之后翻过来切瓜肉

0:00:52.058,0:00:53.940
同样沿着瓜皮用小刀转圈

0:00:53.940,0:00:56.327
这一步可以让瓜肉脱落瓜皮

0:00:56.700,0:00:58.860
然后再竖着将瓜肉切成小方块

0:00:59.460,0:01:01.703
同学们切记每一刀都需要切到底部

0:01:07.047,0:01:09.500
最后将瓜肉倒出即可食用

0:01:09.975,0:01:12.255
第三种也是将西瓜切成两边

0:01:13.470,0:01:15.874
西瓜扣过来之后直刀切成小方块即可

0:01:17.125,0:01:20.526
此方法比较适合切一些十斤以下的小西瓜

0:01:21.786,0:01:23.786
最后再分享一种粗暴式的切法

0:01:23.786,0:01:25.866
将对半的西瓜倒扣放平

0:01:25.866,0:01:28.540
直接用西瓜刀砍掉周围的西瓜皮

0:01:28.986,0:01:30.306
然后横刀切掉瓜蒂

0:01:30.306,0:01:32.988
切掉瓜蒂之后再横刀将瓜肉切成厚片

0:01:33.500,0:01:35.868
最后横竖刀将瓜肉剁成小方块即可

0:01:36.525,0:01:39.347
此法略显粗暴非专业人士请勿模仿


```

**Comment by maaxnatasha** [comment]
认领

**Comment by immoonancient** [comment]
bot, please upload on behalf of the assignee

标题（翻译主要意思即可，不要超过 100 个字符）
厨房小技巧：西瓜的几种切法，踩住夏天的尾巴吃西瓜
Kitchen tips: different ways to cut watermelons. Eat some watermelons while summer is almost ending.

简介
大家好，今天和大家分享几种快速切西瓜的小技巧，大家尽量使用专用的水果菜板来切来避免西瓜串味，如果没有专用菜板也可以用保鲜膜将菜板包住或者在大盘子上操作。这些方法中我最喜欢的是第二种，浪费非常少，并且直接成块倒出即可，西瓜的汁水也较好的保留了下来，为了给大家比较好的展示所以扣在菜板上操作，大家也可以翻过来操作，这样也能有效避免瓜瓤接触菜板。

Hey friends, today I will share different tips to cut watermelons faster. Preferably use fruit only cutting board in order to avoid the mix of taste. If there’s no fruit only cutting board available, use a plastic wrap on the cutting board or cut it on a large plate. Among the all the tips, my favorite is the second one since there no much waste of the pulp and can directly pour out in shape while saving the watermelon juice. Opposite down cutting on the board is for better demonstration, you can also turn it on the other side to prevent the pulp from contacting the cutting board.

字幕
0:00:00.161,0:00:01.280
哈喽大家好我是王刚
Hey friends, this is Wang Gang

0:00:01.280,0:00:02.809
本期视频我跟大家分享
In this video, I am going to share about

0:00:03.150,0:00:05.050
西瓜的多种切法
Different ways to cut watermelons

0:00:05.360,0:00:06.859
首先我们来切第一种
The first way is to

0:00:07.440,0:00:09.880
将西瓜整齐地切成三厘米左右的厚片
Cut the watermelon into thick slices around 3 centimeters

0:00:11.659,0:00:13.840
然后用尖刀沿着瓜皮转一圈
Then use a sharp knife to follow the watermelon rind

0:00:13.840,0:00:15.702
这样可以把瓜肉分离
It can separate the pulp and the rind

0:00:18.739,0:00:22.369
最后再根据个人喜好划出方形或者菱形块即可
Last, cut into square or rhombus shape as your favor

0:00:29.160,0:00:31.905
第二种是直接切开西瓜分成两边
The second way is to cut the watermelon in half

0:00:33.248,0:00:35.833
翻过来用小刀插进去横着切一半
Turn it over and cut it horizontally by half with a small knife

0:00:39.457,0:00:42.209
再取出尖刀横向隔开几厘米继续切
Take out the knife and leave some spaces in between and continue to cut

0:00:46.323,0:00:48.340
然后继续纵向隔开几厘米
Continue to cut it horizontally

0:00:48.340,0:00:49.907
以同样的手法切到底部
Cut to the bottom using the same method

0:00:50.173,0:00:52.058
瓜背切好之后翻过来切瓜肉
Turn over to cut the pulp after finish cutting the rind

0:00:52.058,0:00:53.940
同样沿着瓜皮用小刀转圈
Follow the pulp with the small knife

0:00:53.940,0:00:56.327
这一步可以让瓜肉脱落瓜皮
This step can separate the pulp from the grind

0:00:56.700,0:00:58.860
然后再竖着将瓜肉切成小方块
Then place the pulp vertically and cut it into small pieces

0:00:59.460,0:01:01.703
同学们切记每一刀都需要切到底部
Guys remember to cut to the bottom every single time

0:01:07.047,0:01:09.500
最后将瓜肉倒出即可食用
Last pour out the pulp to eat

0:01:09.975,0:01:12.255
第三种也是将西瓜切成两边
The third way also need to cut the watermelon in half

0:01:13.470,0:01:15.874
西瓜扣过来之后直刀切成小方块即可
Turn over the watermelon and cut into dices

0:01:17.125,0:01:20.526
此方法比较适合切一些十斤以下的小西瓜
This way of cutting is more suitable for small watermelons under 10jin (5kg)

0:01:21.786,0:01:23.786
最后再分享一种粗暴式的切法
To share a more rough way at last

0:01:23.786,0:01:25.866
将对半的西瓜倒扣放平
Put half of the melon upside down on a flat surface

0:01:25.866,0:01:28.540
直接用西瓜刀砍掉周围的西瓜皮
Directly cut the rind with watermelon knife

0:01:28.986,0:01:30.306
然后横刀切掉瓜蒂
Then cut the top melon rind horizontally

0:01:30.306,0:01:32.988
切掉瓜蒂之后再横刀将瓜肉切成厚片
After the previous step, cut the pulp horizontally in thick layers

0:01:33.500,0:01:35.868
最后横竖刀将瓜肉剁成小方块即可
Finally, cut the pulp vertically

0:01:36.525,0:01:39.347
此法略显粗暴非专业人士请勿模仿
This way is kind of rough, don’t imitate unless professionals
