### ISSUE TITLE
[手工耿] 美人魚浴缸 - https://youtu.be/_GVOsRizyhM

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1389]
https://youtu.be/_GVOsRizyhM
<p>&#35270;&#39057;&#21457;&#24067;&#20110; August 14, 2020 at 08:00PM</p>
<p>&#26631;&#39064;<br>
&#33258;&#35069;&#21490;&#19978;&#26368;&#20840;&#33021;&ldquo;&#32654;&#20154;&#39770;&rdquo;&#28020;&#32568;&#65281;&#27873;&#28577;&amp;&#29138;&#28900;&amp;&#36454;&#36842;&amp;&#22132;&#27849;...&#20320;&#20540;&#24471;&#25793;&#26377;!&#12304;&#25163;&#24037;&#32831;Handy Geng&#12305;</p>
<p>&#31616;&#20171;<br>
Make the most versatile "Mermaid" bathtub container in history! Not only can you soak in the bath, but you can also grill skewers, bouncing, fountains, self-catering... &#33258;&#35069;&#21490;&#19978;&#26368;&#20840;&#33021;&#12300;&#32654;&#20154;&#39770;&#12301;&#28020;&#32568;&#38598;&#35037;&#31665;&#65281; &#19981;&#20677;&#21487;&#20197;&#27873;&#28577;&#65292;&#36996;&#33021;&#28900;&#20018;&#12289;&#36454;&#36842;&#12289;&#22132;&#27849;&#12289;&#33258;&#21161;&#39184;&#39154;...... &#21482;&#26377;&#20320;&#24819;&#19981;&#21040;&#65292;&#27794;&#26377;&#25105;&#20570;&#19981;&#21040;&#12290; &mdash;&mdash; &#21029;&#20154;&#31505;&#25105;&#22826;&#30219;&#30322;&#65292;&#31505;&#23436;&#30219;&#30322;&#31505;&#25105;&#38289;&#12290; &#22823;&#23478;&#22909;&#65292;&#25105;&#26159;&#25163;&#24037;&#32831;&#65292;&#22914;&#26524;&#20320;&#21916;&#27489;&#25105;&#30340;&#35222;&#38971;&#65292;&#27489;&#36814;&#40670;&#25802;&#35330;&#38321;&#12290; #&#25163;&#24037;&#32831; #&#27231;&#22120;&#20154; #&#32654;&#20154;&#39770; #&#29138;&#28900;&#26550;&#24590;&#40636;&#20570; #UselessEdison #&#32831;&#24101; #ChineseEdison #handicraft #&#25163;&#24037; #&#30828;&#26680; #&#33258;&#35069;&#27231;&#22120;&#20154; #&#29138;&#28900;&#26550; #&#20013;&#22283;&#30332;&#26126; #&#24290;&#26612;&#24859;&#36842;&#29983; #&#25630;&#31505;&#30332;&#26126;</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/113772413d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by hengdiliang** [comment]
认领

**Comment by hengdiliang** [comment]
标题
自製史上最全能“美人魚”浴缸！泡澡&燒烤&蹦迪&噴泉...你值得擁有!【手工耿Handy Geng】
The most versatile homemade "mermaid" bathtub in history! Bath & BBQ & Disco & Fountain... You deserve it! (Handicraft Geng aka Useless Edison)

0:00:00.000,0:00:02.000
（美人鱼烧烤浴盆）
(Mermaid barbecue bathtub)

0:00:02.115,0:00:04.815
最近有个小兄弟来找我
A little brother came to me recently

0:00:04.815,0:00:07.545
说是想要出去摆摊创业卖烧烤
He said he wanted to set up a market stall and sell barbecue

0:00:07.545,0:00:09.250
但是现在竞争比较激烈啊
But competitions are intense now

0:00:09.250,0:00:10.675
最近又是三伏天了
And it’s been a hot season recently

0:00:10.675,0:00:12.225
烤串比较怕热
Having barbecue can be very hot

0:00:12.375,0:00:13.225
问我有没有办法解决
So he asked if I had a solution

0:00:13.225,0:00:15.675
啊，想了一段时间之后
After thinking about it for a while

0:00:15.675,0:00:18.625
我决定给他做一个美人鱼烧烤浴盆
I decided to make a mermaid barbecue bathtub for him

0:02:35.000,0:02:41.000
(人鱼烧烤)
Mermaid Barbecue

0:02:42.035,0:02:45.095
给大家介绍一下我的这个美人鱼烧烤浴盆
Let me introduce my mermaid barbecue bathtub

0:02:45.095,0:02:47.225
等我们出去摆摊儿啊
When we go out and set up a stall

0:02:47.225,0:02:50.175
卖烧烤的时候
and sell barbecue

0:02:50.175,0:02:51.805
首先先掀开上面这个盖子
First, take the lid off

0:02:53.225,0:02:57.395
它就会变成一个给我们招揽生意的灯箱
It will become a light box for us to attract business

0:02:57.515,0:02:58.965
这里是开关
Here is the switch

0:02:59.685,0:03:01.105
可能是白天的原因啊
Maybe because it’s in the daytime

0:03:01.106,0:03:02.105
显得不是特别亮
It doesn't seem very bright

0:03:02.105,0:03:04.105
晚上说咱们的拍拍看
Let’s wait until the night to shoot the video

0:03:04.105,0:03:06.935
不仅如此，它还可以啊旋转
Besides, it can rotate

0:03:08.515,0:03:10.395
漂不漂亮
Isn’t it beautiful?

0:03:10.395,0:03:12.285
下面是一个音乐喷泉
Below is a music fountain

0:03:12.395,0:03:13.685
打开开关之后
After the switches are on

0:03:14.085,0:03:15.745
它就会喷出水来
It's going to spray water

0:03:16.355,0:03:18.605
而且如果说有音乐的话
And if there is music

0:03:21.525,0:03:23.525
它还会随着音乐的节拍
It will follow the beat of the music

0:03:24.185,0:03:26.165
上下起伏
Up and down

0:03:26.265,0:03:34.165
[Music]

0:03:34.885,0:03:36.625
啊，这个浴池的两边
On both sides of the bath

0:03:36.825,0:03:38.895
是一个它的烤箱
are the ovens

0:03:39.295,0:03:42.875
打开之后这里可以变成一个小吧台
It can be turned into a small bar when opened

0:03:43.175,0:03:45.675
我们在里面烧烤的时候不会感觉到炎热
We don't feel hot when we barbecue inside

0:03:45.775,0:03:48.875
啊如果说水太凉的话你还会感觉到特别冷
You will even feel very cold if the water is too cold

0:03:48.875,0:03:50.635
但是也不用担心
But no need to worry

0:03:50.735,0:03:54.085
它在下面有一个啊加热系统
It has a heating system below

0:03:54.295,0:03:55.975
只需要打开这里
You only need to open here

0:03:56.515,0:03:58.455
往里面添一些柴火
Add some firewood

0:03:58.455,0:04:00.645
就可以给浴池加热
Then you can heat the bathtub

0:04:07.455,0:04:11.545
现在是已经开了，我们可以到里面烧烤了
Now that the water is boiling, we can go inside to barbecue

0:04:15.315,0:04:17.685
啊，其实里面的水并没有开
Ah, the water is not really boiling

0:04:18.005,0:04:19.735
只不过是为了视觉效果
This is just for the visual effect

0:04:20.045,0:04:23.155
我在这个浴池底下安装几个出气孔
I installed some vent holes under this bathtub

0:04:23.245,0:04:24.155
这里是开关
Here is the switch

0:04:24.545,0:04:27.375
关上之后，它就没有了
The bubbles disappear after you turn it off

0:04:27.375,0:04:28.625
然后再打开
Then turn it on again

0:04:30.565, 0:04:34.045
这个烟是里面有一个雾化器
The smoke is due to a nebulizer inside

0:04:34.475,0:04:36.755
可以制造出烟雾来
which can produce smoke

0:04:36.755,0:04:39.685
让我们有一种仙气飘飘的感觉
and let us feel as in the fairyland

0:04:40.255,0:04:42.265
浴盆尾部的这三个罐子
The three pots at the end of the bathtub

0:04:42.265,0:04:45.435
我们可以卖一些可乐啤酒之类的饮料
We can sell drinks like coke and beer

0:04:48.385,0:04:51.735
里面还有一个美人鱼的套装
There is also a mermaid suit in it

0:04:54.755,0:04:57.205
下面我穿上整体给大家演示一下
Now I'll put it on to show you

0:05:00.075,0:05:02.655
穿上这个美人鱼套装之后啊
After putting on the mermaid suit

0:05:02.655,0:05:06.615
我就会变成一个美人鱼烧烤大师
I will become a mermaid barbecue master

0:05:06.715,0:05:09.535
让我在激烈的竞争者之中脱颖而出
which lets me stand out from the fierce competition

0:05:09.535,0:05:14.375
弄不好半条街的烧烤生意都是我的
Perhaps half of the barbecue business on this street will be mine

0:05:16.655,0:05:19.635
如果能找到一个好看的美人鱼烧烤师啊
If we can find a beautiful mermaid barbecue master

0:05:19.635,0:05:21.165
生意会更好
The business can be better

0:05:21.535,0:05:24.845
像我这样的可能会差一点
Having someone like me, the business may not be as good

0:05:26.135,0:05:28.845
接着奏乐
Continue the music

0:05:42.000,0:05:44.000
感谢收看，欢迎订阅 – 手工耿
Thank you for watching. Welcome to subscribe. – Handicraft Geng
