### ISSUE TITLE
[华农兄弟] 华农兄弟抓点笋虫来烤再捡点田螺来炒很美味哦 - https://youtu.be/szk6rGr6UNY

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1390]
https://youtu.be/szk6rGr6UNY
<p>&#35270;&#39057;&#21457;&#24067;&#20110; August 15, 2020 at 12:14PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/szk6rGr6UNY

#华农兄弟：抓点笋虫来烤，再捡点田螺来炒，很美味哦
#Huanong Brothers: We pick some bamboo shoots weevils, grill them; then pick some river snails, fry them. Tasty!

0:00:00.300,0:00:02.840
# 大家好  我去抓點那個笋蟲
Hi everyone! I'm gonna catch some, some bamboo shoots weevils,

0:00:02.960,0:00:04.600
# 笋蟲來 補充一下蛋白質  (原字幕不見了)
some weevils to replenish me with protein.

0:00:05.100,0:00:06.740
# 最近老是腰酸背痛
The back pain is always attacking me these days.

0:00:08.120,0:00:10.680
# 那邊  笋蟲就喜歡待在那種地方
There. The bamboo shots weevils like staying in those places.

0:00:17.140,0:00:20.880
# 你看  笋蟲就生活在嫩的竹笋上面
Look! The weevils are living on the young bamboo shoots.

0:00:21.540,0:00:23.000
# 它吸竹笋的汁
They suck the juice from the bamboo shoots.

0:00:23.440,0:00:25.480
# 它是壞蛋來的  害蟲來的
They are bad guys, pests!

0:00:29.440,0:00:32.760
# 都沒有  是不是看到我來啦  它們都全跑啦
I can't see any of them. Have they all run away, cuz they saw me coming?

0:00:34.520,0:00:35.480
# 一個都沒有哦
Not even one here

0:00:37.960,0:00:41.140
# 這個笋蟲的種都可能被  去年被我們抓完啦
Perhaps we've already caught the last, the last weevil last year.

0:00:44.940,0:00:46.340
# 這裡深山老林一樣
Here's like a deep, wild and ancient forest.

0:00:47.640,0:00:49.180
# 這 那麼多草
Here's so much weeds.

0:00:51.000,0:00:53.900
# 你看  找了好久  只找了一找了一個
Look! After a long time, we've found, found only one.

0:00:55.280,0:00:55.920
# 抓起來
Let me catch it.

0:00:57.580,0:00:58.960
# 我忘了它好大的力氣
I've forgotten that it grabs very strongly.

0:01:00.620,0:01:02.100
# 看你的力氣大還是我的力氣大
Let's see who's stronger, you or me.

0:01:02.460,0:01:05.600
# 這個是害蟲來的哦  專吃這個竹子的汁啊
This is pest, you know. It eats nothing but the juice from bamboos.

0:01:06.900,0:01:07.680
# 壞的很
They're really bad.

0:01:10.640,0:01:14.000
# 你看  它現在跑不了啦  可以  可以透氣的這裡
Look! Then it can't run away now. The air, the air can pass through here.

0:01:14.860,0:01:17.680
# 再去看一下有沒有  一個不夠吃啊
Let's see if there are any more. One is not enough.

0:01:21.300,0:01:24.340
# 應該  附近應該有的  還有的
There should be, should be some more nearby. There should be more.

0:01:24.340,0:01:27.900
# 不可能有一個的  要有也有一對呀
It can't be just one. Two makes much more sense.

0:01:28.120,0:01:32.900
# 你看  這塊竹笋 就是被那個笋蟲吃的  咬了幾個口
Look! This bamboo shoot, has been eaten by the weevils. There are a few bites.

0:01:34.160,0:01:35.600
# 它們壞的很
They're really bad guys.

0:01:36.780,0:01:41.200
# 就把那個竹子汁都吸乾啦  這棵竹子都可能會死掉
They've sucked all the juice from this bamboo. It might not survive.

0:01:49.020,0:01:50.360
# 你看  又抓到一個
Look! One more here.

0:01:52.200,0:01:54.640
# 還在  可能還  它還在睡覺
It's still, it may be still, still sleeping.

0:01:55.720,0:01:59.300
# 這個蟲子炸了很好吃的  誒耶  哦尿的
This weevil is really tasty when it's fried. Aya, it pisses.

0:02:00.540,0:02:01.260
# 等一下來
A moment

0:02:02.160,0:02:03.140
# 那瓶子裝起來
Put it in the jar.

0:02:04.380,0:02:06.900
# 這個用油炸一下或者烤一下都很好吃的
Fried or grilled, it's really tasty.

0:02:10.680,0:02:11.960
# 你看  就抓了兩個
Look! So you've caught just two.

0:02:12.600,0:02:15.000
# 我看下明天我再去找一下看能不能找的到
l think I'll be coming again tomorrow and see if there are any more.

0:02:15.520,0:02:17.480
# 再搞一點來 太 太少啦
I want a little more. It's too, too few.

0:02:18.140,0:02:18.860
# 不夠吃啊
It's not enough.

0:02:22.020,0:02:23.420
# 好啦  先回去啦
Alright! Let's go back first.

0:02:26.720,0:02:31.500
# 你看  抓了一天  才抓了四個  怎麼吃  太少啦
Look! I spent a whole day only to have caught just four. What should I do? It's too few.

0:02:32.000,0:02:34.680
# 去  檢一點田螺來湊  湊一點田螺才
I'm gonna, pick some river snails to make it a meal. Without some river snails,

0:02:35.300,0:02:36.900
# 才夠  夠吃
it won't be, won't be enough.

0:02:37.620,0:02:38.620
# 就在河邊檢一下
We're heading to the riverside.

0:02:53.360,0:02:53.860
# 過來
Come here!

0:02:54.720,0:02:55.480
# 快點快點
C'mon, c'mon!

0:03:20.860,0:03:22.980
# 剛好來到這裡  搞點這個薄荷回去
It just so happens that I pass by here. Let me get some mint back home.

0:03:23.420,0:03:24.800
# 這薄荷都已經開花啦
The mint has already blossomed.

0:03:25.660,0:03:26.860
# 嗯  好濃的味道
Um! A rich scent of mint

0:03:32.740,0:03:34.020
# 你看  這個是草來的
Look! This is grass.

0:03:38.140,0:03:39.720
# 一聞都聞的出這個味道
I can tell immediately by the smell.

0:03:41.600,0:03:45.160
# 在野外摘東西要摘  摘對來哦  有時會摘錯的
While in the wild, it's important to pick the right things. Sometime we may pick the wrong things,

0:03:46.100,0:03:47.020
# 那就不好啦
and it's too bad.

0:03:50.280,0:03:53.160
# 夠啦夠啦  嗯  這個就是薄荷
Enough, enough. Um. This is mint.

0:04:08.200,0:04:09.720
# 剛好衣服都濕完啦
My clothes are already soaked now.

0:04:10.580,0:04:12.020
# 直接坐在河裡面去
Let us just sit in the river.

0:04:13.280,0:04:14.080
# 啊~
Ah~

0:04:16.500,0:04:17.180
# 舒服啊
Wonderful!

0:04:18.420,0:04:21.520
# 你看  天氣熱  在水裡面走 走水路  很不錯的哦
Look! When it's hot, walking in the water, through a water path, is really not bad, you know.

0:04:22.400,0:04:24.840
# 你看  又不要用力  輕輕的蹬兩下就好啦
Look! I don't need to do anything, except pushing a few times very slightly.

0:04:25.800,0:04:27.320
# 它這水太淺了
The water here is too shallow.

0:04:29.560,0:04:30.680
# 很舒服的哦  這樣
It's so nice, in the water.

0:04:33.780,0:04:36.120
# 它這裡太淺啦  老是刮底盤
It's too shallow here. The bank is always scratching me.

0:04:40.500,0:04:41.940
# 在深一點的地方就可以
I would be better with deeper water.

0:04:43.520,0:04:45.680
# 褲子濕了  衣服也濕了
My pants are soaked, and so is my T-shirt.

0:04:46.500,0:04:49.840
# 你看這頭牛  偷吃我的象草哦
Have a look at these cows. They're stealing my elephant grass.

0:04:50.940,0:04:53.160
# 誰家的  讚到我家這裡來
Whose cows are they? Why do they come to my place?

0:04:57.520,0:04:58.340
# 摸一下
Let me touch you.

0:05:00.260,0:05:04.360
# 你看  這一片象草都是我種的  這些都是今年剛種下的  紅的
Look! The whole area of elephant grass here is mine. I planted them this year, the red ones.

0:05:05.520,0:05:07.320
# 這明年就很多啦  這一片都是
There will be a lot next year, covering the whole area.

0:05:08.520,0:05:13.580
# 下面的那個  白的象草 那一坨象草  你看  多茂盛啊
Those down there, the white elephant grass, that bunch of elephant grass. Look! It's so bushy.

0:05:15.300,0:05:18.000
# 搞兩條牛  搞兩條牛回來食都可以把它養大
I can fetch a couple of cattle, fetch a couple of cattle and raise them here.

0:05:18.000,0:05:19.160
# 那麼多草  夠了
There's so much grass. It must be enough.

0:05:25.920,0:05:28.620
# 這田螺  很靚哦
These river snails, are really beautiful!

0:05:39.580,0:05:41.060
# 等一下就乾淨了
They will be clean in a while.

0:05:44.940,0:05:48.120
# 洗一點這個米水  泡一下這個田螺
I'm gonna get some, some rice water. I'll soak the snails in it.

0:05:49.800,0:05:52.700
# 我們這些  家裡的大米 自己碾出來的
This is our, home grown rice. We milled them ourselves.

0:05:53.860,0:05:56.220
# 都是  這個米水都是乳白色的
It's like, the rice water is always milky white,

0:05:57.500,0:05:58.500
# 像牛奶一樣
just like milk.

0:06:03.100,0:06:06.920
# 你看  開始啦  這個米水它們不適應它就
Look! It starts. They don't like the rice water, so they're,

0:06:06.920,0:06:10.160
# 身上的泥 它就  把它的身子伸出來
the mud on their bodies, they're squeezing out their bodies,

0:06:10.160,0:06:12.320
# 伸出來之後身上的泥就會吐出來哦
and then they'll, spit out the mud on their bodies.

0:06:13.680,0:06:14.400
# 看上這個
Have a look at this one!

0:06:14.800,0:06:17.780
# 這個沒事的  沒毒的  只是它們不適應而已
It's not a problem, not poisonous. It's all because it doesn't like the rice water.

0:06:17.780,0:06:18.520
# 3小時後
Three hours later

0:06:28.820,0:06:30.080
# 你看  這些都是
Look! These are all,

0:06:30.780,0:06:31.800
# 田螺的那個
the cracked shells from the,

0:06:33.760,0:06:34.660
# 田螺瞉
from the river snails,

0:06:35.420,0:06:36.460
# 碎的田螺瞉
the cracked snail shells.

0:06:38.980,0:06:41.040
# 你看  掉了好多泥
Look! They've spitted out a lot of mud.

0:06:41.520,0:06:42.620
# 用那個摟一下
Let me rinse them with the, you know.

0:06:51.600,0:06:54.880
# 你看  現在很乾淨了哦  一點泥味都沒有了
Look! It's very clean now. Not even a bit of the smell of mud remains.

0:06:57.040,0:06:58.000
# 去一下它屁股
Let's get rid of their butts.

0:06:58.460,0:06:59.520
# 把它屁股剪掉
I'm gonna cut away their butts.

0:07:01.040,0:07:01.920
# 這個好剪
This pincer is nice.

0:07:10.640,0:07:12.040
# 搞點這個生薑下去
I put some, some ginger here.

0:07:13.280,0:07:16.480
# 你看 這田螺  溫水煮田螺
Look! The river snails, boil the snails, slowly in warm water.

0:07:30.200,0:07:32.320
# 你看這些田螺  毫無反抗能力
Have a look at the river snails. They simply can't resist at all.

0:07:33.760,0:07:37.080
# 這煮出來的湯都沒甚麼  看上去都沒甚麼泥  泥巴味
There's hardly any, I can't see any mud, any smell of mud in the water.

0:07:42.740,0:07:43.660
# 乾淨啦
It's clean now.

0:07:43.920,0:07:45.060
# 把它撈起來啦
Let me take them out.

0:07:49.920,0:07:51.380
# 去清水洗一下
Wash them with fresh water first.

0:07:52.420,0:07:55.600
# 洗洗  洗洗它的身子
Let me wash, wash their bodies.

0:08:06.460,0:08:09.620
# 把這些料搞香 再把田螺放下去
I fry the side ingredients first, and then put the river snails.

0:08:09.900,0:08:11.000
# 把這田螺放下去啦
Now it's time for the river snails.

0:08:17.340,0:08:18.140
# 放點鹽
Put some salt.

0:08:19.720,0:08:20.780
# 稍微放鹹一點
I want a bit more salt.

0:08:28.860,0:08:30.040
# 加點這個薄荷
Put some, some mint.

0:08:35.260,0:08:37.080
# 加點老抽和生抽哦
I'm putting some dark and light soy sauce.

0:08:38.440,0:08:41.040
# 這是老抽  這是生抽
This is the dark one, and this is the light one.

0:08:44.760,0:08:47.920
# 要放點水  放點水把它煮乾那個水就好啦
I gotta put some water. It will then be done when the water dries out.

0:08:56.040,0:08:57.720
# 等下  直接大火收汁
I'll then, thicken the sauce on high heat.

0:09:01.440,0:09:02.620
# 哇  這田螺好啦
Wa! The river snails are ready now.

0:09:21.980,0:09:24.300
# 你看  經過一下午的努力
Look! With the effort in the whole afternoon,

0:09:25.760,0:09:26.620
# 做了一個菜
a dish is completed.

0:09:27.100,0:09:27.760
# 就這個菜
It's this one.

0:09:28.440,0:09:29.180
# 田螺
River snails

0:09:31.320,0:09:32.640
# 挑個最大的來吃
Let me pick the biggest one.

0:09:33.060,0:09:34.220
# 你看  這個
Look! This one

0:09:44.800,0:09:46.240
# 嗯 可以
Um! Not bad!

0:09:47.460,0:09:48.760
# 好啦  我去看一下那個笋蟲
Alright! Let me take a look at the weevils.

0:09:49.920,0:09:51.820
# 趁現在還有火哦  我把笋蟲烤啦
I'm gonna grill the weevil, before the fire goes off.

0:09:52.800,0:09:55.940
# 起來啦起來啦  準備上刑場啦
Wake up, wake up! Time to go to the fire stake!

0:09:58.760,0:09:59.860
# 把它的腳去掉
I remove its legs,

0:10:00.180,0:10:01.880
# 把它的腳去掉  把頭去掉
remove its legs, and also its head,

0:10:02.860,0:10:03.840
# 就可以吃啦
then the rest is edible.

0:10:05.240,0:10:06.320
# 這頭也要去掉
The head needs to be removed as well.

0:10:15.500,0:10:19.360
# 這翅肪也要去掉  翅肪不好吃的  你看
The wings need to be removed as well. The wings don't taste good. Look!

0:10:21.120,0:10:22.920
# 同樣的來 再來一個
The same steps. Next one.

0:10:23.820,0:10:25.820
# 誰來  就你長的大一點
Who's coming? You're the bigger one.

0:10:27.080,0:10:28.360
# 哎呦 它要咬人一樣
Aya! It wants to bite.

0:10:29.480,0:10:30.420
# 戳的我好痛
It stings me. It hurts.

0:10:31.180,0:10:32.680
# 你看  戳著我的手
Look! It stings my finger.

0:10:33.340,0:10:34.460
# 臨死掙扎
Final struggle

0:10:35.340,0:10:37.380
# 我也知道啊  那誰叫你的
I know. But who asked you to be,

0:10:38.980,0:10:43.080
# 你的營養有那麼好嘞  是不是 它勾著我了 不放
to be so nutritious, right? It hooks on me. It's not going away.

0:10:45.140,0:10:46.000
# 放開我
Off your legs!

0:10:47.060,0:10:47.760
# 放不放
Are you listeing?

0:10:51.940,0:10:52.780
# 你敢飛嗎
Dare you fly away?

0:10:53.820,0:10:54.700
# 它又不敢飛
It dares not.

0:10:56.520,0:10:59.080
# 你看 它死都不放哦  一直抱著我
Look! It's grabbing me with all its might, grabbing my,

0:11:01.000,0:11:02.820
# 把著我的  小手
grabbing my, tiny finger.

0:11:18.780,0:11:21.880
# 你看這個還會動哦  沒事
Look! This one is still moving. No worries.

0:11:26.500,0:11:31.320
# 等下要  先烤一下  撒點鹽撒點油  嘖  就可以吃啦
I'll then, grill it for a while, spray some oil and some salt. Then it will be ready to serve.

0:11:31.940,0:11:33.480
# 你看  這裡還有一點火
Look! Here's still a little bit fire.

0:11:34.260,0:11:36.400
# 這樣就不用  不用生火
Then I don't need to, start another fire.

0:11:37.660,0:11:38.600
# 搞點油
Put some oil.

0:11:41.320,0:11:42.460
# 再撒點鹽
And then some salt.

0:11:43.800,0:11:46.240
# 雨路均沾  一人沾一點
To be fair, everybody has its share of salt.

0:11:50.020,0:11:51.800
# 哇  搞的好香啊
Wa! It smells so good!

0:12:04.960,0:12:07.900
# 好香啊  這味道出來啦
It smells so good! The flavour is coming out.

0:12:09.540,0:12:11.000
# 好多鹽  先洗一下
Too much salt. Let me wash it.

0:12:17.440,0:12:18.860
# 你看  直接烤熟了哦
Look! It's done right away.

0:12:21.020,0:12:21.700
# 夾一下它
Hold it here.

0:12:23.300,0:12:24.180
# 哇  你看肉  (註︰不知道昆蟲用"meat"是否適合，但找不到更好的字了)
Wa! Have a look at the meat.

0:12:28.480,0:12:29.380
# 好香啊
It smells so good!

0:12:30.760,0:12:31.660
# 真的
Really good!

0:12:33.260,0:12:34.260
# 你看  這些渣渣
Look! Here's the residue.

0:12:36.680,0:12:38.120
# 蛋白質豐富  瘦肉
Rich in protein. Lean meat.

0:12:39.660,0:12:41.040
# 嗯  可以
Um! Not bad!

0:12:42.520,0:12:43.860
# 它頭沒有 沒有肉
There's nothing to eat, in the head.

0:12:45.960,0:12:48.460
# 真的  感覺像有點雞肉味一樣
No kidding. It really tastes a bit like chicken.

0:12:51.680,0:12:55.480
# 好香啊 攝影哥  攝影小哥還小的時候經常吃這個
It smells so good. Mr. Camra, Mr. Cameraman used to eat a lot of these when he was small.

0:12:57.340,0:12:58.380
# 口味太重啦
He was simply too exceptional.

0:13:02.280,0:13:03.160
# 這種是害蟲
These are pest.

0:13:05.160,0:13:07.500
# 吃起來 就是好啦
But they're so nice, as food.

0:13:09.700,0:13:12.800
# 你看  這個是肉哦  有點像瘦肉  看到沒有
Look! This is lean meat. It's a bit like lean meat. See?

0:13:14.580,0:13:17.420
# 嗯  味道還可以  來  嘗一個
Um! It tastes not bad. C'mon! Try one!

0:13:17.960,0:13:19.640
# 今天的視頻就到這這裡啦
The video ends here.
