### ISSUE TITLE
【美食作家王刚】麻辣花生 - https://youtu.be/m1eqNAz87E0

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1393]
**视频链接**：https://youtu.be/m1eqNAz87E0

视频时长2:53，预计发布时间为北京时间8月17日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“麻辣花生米”“酒鬼花生”的家常做法，口口香脆，值得一学

简介
大家好，今天给大家介绍一道四川风味小吃“酒鬼麻辣花生”，以其鲜咸麻辣特别下酒为著名，其秘诀就是先煮再炸最后再炒，花生经过三次受热会变得特别香脆，并且不容易回潮。现在很流行的“黄飞红麻辣花生”也是使用类似的制作方法。大家可以一次多做一些，然后装入较为密封的容器中保存即可。

字幕
0:00:00.159,0:00:01.294
哈喽大家好 我是王刚

0:00:01.294,0:00:03.328
本期视频我跟大家分享一道小吃

0:00:05.120,0:00:07.840
首先我们准备花生米500克放入盆中

0:00:07.880,0:00:10.585
加入适量的清水浸泡60分钟备用

0:00:10.760,0:00:13.080
浸泡的目的是为了更好地搓掉花生皮

0:00:13.360,0:00:15.506
喜欢吃皮的同学也可以不用搓

0:00:15.686,0:00:16.720
但是必须浸泡

0:00:18.588,0:00:21.340
然后将去皮的花生米再次淘洗干净备用

0:00:21.427,0:00:24.271
同学们如果是新鲜的花生米也可以直接制作

0:00:24.420,0:00:26.100
下一步开始配制辅料

0:00:26.140,0:00:27.582
碗中加入八角2颗

0:00:27.626,0:00:28.828
加入桂皮2小块

0:00:28.903,0:00:31.423
然后准备适量的子弹头剪成辣椒丝备用

0:00:31.620,0:00:34.112
喜欢吃更辣的同学可以换成小米干辣椒

0:00:35.960,0:00:37.560
再加入适量的青花椒

0:00:37.600,0:00:39.557
不喜欢吃麻的同学也可以不加

0:00:39.680,0:00:42.328
再加入适量的高度白酒浸泡20分钟备用

0:00:42.328,0:00:44.703
白酒浸泡的目的是“榨”出辣味和麻味

0:00:44.920,0:00:47.840
同学们白酒也可以反复使用降低成本

0:00:47.840,0:00:49.080
下一步开始制作

0:00:49.080,0:00:51.240
首先我们在锅中加入适量的清水

0:00:52.140,0:00:54.060
然后加入剥好皮的花生米

0:00:55.396,0:00:58.328
大火烧开之后转小火煮五分钟将其煮熟

0:01:00.436,0:01:02.340
中途可以加入适量的白醋

0:01:03.188,0:01:06.106
加白醋可以让花生米的颜色更白更纯

0:01:06.787,0:01:09.962
5分钟之后捞出放入冰箱中冰冻30分钟冷却

0:01:10.260,0:01:13.103
花生米经过一冷一热之后会变得更脆

0:01:13.832,0:01:16.300
30分钟之后取出花生米开始制作

0:01:16.564,0:01:18.269
首先我们把锅烧热

0:01:18.479,0:01:20.310
锅烧热之后加入小宽油

0:01:23.343,0:01:25.290
然后直接下入冻好的花生米

0:01:26.241,0:01:28.041
开中小火炸制五分钟左右

0:01:28.483,0:01:29.491
将其炸脆

0:01:30.333,0:01:32.171
家庭小灶则需要8分钟左右

0:01:35.455,0:01:37.278
花生米炸脆之后捞出备用

0:01:40.260,0:01:41.555
下一步开始炒制

0:01:42.578,0:01:44.779
锅中加入少许的底油烧至五成热

0:01:45.075,0:01:47.736
然后加入处理好的花椒辣椒小火爆香

0:01:50.525,0:01:54.153
辣椒爆香之后下入炸好的花生米小火翻炒10分钟左右

0:01:55.254,0:01:57.874
同学们花椒辣椒经过浸泡所以不怕炒糊

0:02:01.804,0:02:04.132
中途加入适量的食用盐和白糖调味

0:02:04.132,0:02:06.355
其中盐可以是平时炒菜的三倍

0:02:06.355,0:02:07.443
否则不够咸

0:02:11.121,0:02:14.172
起锅之前再加入少许的高度白酒翻炒一分钟即可

0:02:14.775,0:02:16.460
加白酒的目的是增香

0:02:16.823,0:02:19.191
也可以让花生米长时间保持脆度

0:02:22.150,0:02:25.164
翻炒一分钟之后将花生米倒出放凉即可食用

0:02:28.710,0:02:31.782
一道非常香辣爽脆的下酒花生米就制作完成

0:02:31.880,0:02:33.318
下面开始技术总结

0:02:33.700,0:02:34.260
第一

0:02:34.424,0:02:36.060
花生米最好选择陈花生米

0:02:36.631,0:02:39.025
这样经过浸泡之后很容易将皮搓掉

0:02:39.874,0:02:40.380
第二

0:02:40.500,0:02:43.522
花生米经过一冷一热再油炸可以变得异常酥脆

0:02:44.745,0:02:45.266
第三

0:02:45.409,0:02:48.677
不喜欢麻辣的同学也可以用其他香料代替花椒辣椒

0:02:48.870,0:02:50.647
麻辣花生米的技术总结完毕


```

**Comment by Yibing-Du** [comment]
认领

**Comment by Yibing-Du** [comment]
bot, please upload
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“麻辣花生米”“酒鬼花生”的家常做法，口口香脆，值得一学
Chef Wang teaches you: "Spicy and Numbing Peanuts" and "Peanuts accompanying Chinese wine," super crunchy!

简介
Introduction
大家好，今天给大家介绍一道四川风味小吃“酒鬼麻辣花生”，以其鲜咸麻辣特别下酒为著名，其秘诀就是先煮再炸最后再炒，花生经过三次受热会变得特别香脆，并且不容易回潮。现在很流行的“黄飞红麻辣花生”也是使用类似的制作方法。大家可以一次多做一些，然后装入较为密封的容器中保存即可。
Hello everyone, today I'll introduce a Sichuan-style snack, "Spicy and numbing peanuts for wine enthusiasts," known for a mix of umami, salty, numbing, and spicy flavors, which makes it go along with wine very well. The secret trick is to first boil, then fry, and finally stir-fry. After being heated three times, peanuts become particularly crunchy and tasty, and they won't become rancid very easily. Nowadays the famous snack "Huang Feihong Spicy and Numbing Peanuts" is made similarly. You can make lots of them and store them in a relatively sealed container.

字幕
0:00:00.159,0:00:01.294
哈喽大家好 我是王刚
Hello everyone, this is Wang Gang
0:00:01.294,0:00:03.328
本期视频我跟大家分享一道小吃
In today's video, I'll share the recipe of a snack
0:00:05.120,0:00:07.840
首先我们准备花生米500克放入盆中
First, prepare 500g of peanuts in a pot
0:00:07.880,0:00:10.585
加入适量的清水浸泡60分钟备用
Add some water and soak them for 60 minutes
0:00:10.760,0:00:13.080
浸泡的目的是为了更好地搓掉花生皮
This makes removing the skin easier later
0:00:13.360,0:00:15.506
喜欢吃皮的同学也可以不用搓
You can also leave the skin there if you like
0:00:15.686,0:00:16.720
但是必须浸泡
But soaking in water is a must
0:00:18.588,0:00:21.340
然后将去皮的花生米再次淘洗干净备用
Then rinse the peanuts with their skin removed and set them aside
0:00:21.427,0:00:24.271
同学们如果是新鲜的花生米也可以直接制作
If the peanuts are fresh, you can ignore these previous steps
0:00:24.420,0:00:26.100
下一步开始配制辅料
Next, prepare other ingredients
0:00:26.140,0:00:27.582
碗中加入八角2颗
Add 2 pieces of star anises to the bowl
0:00:27.626,0:00:28.828
加入桂皮2小块
Add 2 small pieces of cinnamon
0:00:28.903,0:00:31.423
然后准备适量的子弹头剪成辣椒丝备用
Then prepare some "Zidantou" chili peppers and cut them into slices
0:00:31.620,0:00:34.112
喜欢吃更辣的同学可以换成小米干辣椒
If you can eat very spicy food, you can use Xiaomi dried chili peppers instead
0:00:35.960,0:00:37.560
再加入适量的青花椒
Then add some green Sichuan peppercorns
0:00:37.600,0:00:39.557
不喜欢吃麻的同学也可以不加
If you don't want the peanuts to be numbing, don't add them
0:00:39.680,0:00:42.328
再加入适量的高度白酒浸泡20分钟备用
Then add some hard liquor baijiu and soak for 20 minutes
0:00:42.328,0:00:44.703
白酒浸泡的目的是“榨”出辣味和麻味
This is to enhance the spicy and numbing flavors
0:00:44.920,0:00:47.840
同学们白酒也可以反复使用降低成本
You can reuse baijiu to lower the cost
0:00:47.840,0:00:49.080
下一步开始制作
Next, start cooking
0:00:49.080,0:00:51.240
首先我们在锅中加入适量的清水
First we add some water to the wok
0:00:52.140,0:00:54.060
然后加入剥好皮的花生米
Then add the pealed peanuts
0:00:55.396,0:00:58.328
大火烧开之后转小火煮五分钟将其煮熟
After it boils, turn to low heat and boil for 5 minutes
0:01:00.436,0:01:02.340
中途可以加入适量的白醋
You can add some rice vinegar midway
0:01:03.188,0:01:06.106
加白醋可以让花生米的颜色更白更纯
Adding rice vinegar can make the peanuts' color purely white
0:01:06.787,0:01:09.962
5分钟之后捞出放入冰箱中冰冻30分钟冷却
After 5 minutes, remove the peanuts from water and put them in the freezer for 30 minutes
0:01:10.260,0:01:13.103
花生米经过一冷一热之后会变得更脆
Peanuts become more crunchy after the quick change of temperature
0:01:13.832,0:01:16.300
30分钟之后取出花生米开始制作
After 30 minutes, take out the peanuts and start cooking
0:01:16.564,0:01:18.269
首先我们把锅烧热
First we heat up the wok
0:01:18.479,0:01:20.310
锅烧热之后加入小宽油
When the wok is heated, add some Kuan You
0:01:23.343,0:01:25.290
然后直接下入冻好的花生米
Then add the frozen peanuts
0:01:26.241,0:01:28.041
开中小火炸制五分钟左右
Use medium-low heat to fry for around 5 minutes
0:01:28.483,0:01:29.491
将其炸脆
Until they become crunchy
0:01:30.333,0:01:32.171
家庭小灶则需要8分钟左右
If you cook at home, it takes around 8 minutes
0:01:35.455,0:01:37.278
花生米炸脆之后捞出备用
Take the peanuts out after they become crunchy
0:01:40.260,0:01:41.555
下一步开始炒制
Then start stir-frying
0:01:42.578,0:01:44.779
锅中加入少许的底油烧至五成热
Add some base oil and heat it to around 150 degrees celsius
0:01:45.075,0:01:47.736
然后加入处理好的花椒辣椒小火爆香
Then add pre-processed peppercorns and chili peppers and bring out the aroma with low heat
0:01:50.525,0:01:54.153
辣椒爆香之后下入炸好的花生米小火翻炒10分钟左右
After you smell the peppers, add the fried peanuts and stir-fry for 10 minutes
0:01:55.254,0:01:57.874
同学们花椒辣椒经过浸泡所以不怕炒糊
Since we've soaked the peppercorns and chili peppers in water, they won't be burnt
0:02:01.804,0:02:04.132
中途加入适量的食用盐和白糖调味
Add some salt and sugar midway
0:02:04.132,0:02:06.355
其中盐可以是平时炒菜的三倍
You can add three times as much salt as you usually do when cooking
0:02:06.355,0:02:07.443
否则不够咸
Or it won't be salty enough
0:02:11.121,0:02:14.172
起锅之前再加入少许的高度白酒翻炒一分钟即可
Before we're done, add a little bit of baijiu and stir-fry for another minute
0:02:14.775,0:02:16.460
加白酒的目的是增香
This is to enhance the flavors
0:02:16.823,0:02:19.191
也可以让花生米长时间保持脆度
and let the peanuts stay crunchy for a long time
0:02:22.150,0:02:25.164
翻炒一分钟之后将花生米倒出放凉即可食用
After one minute, pour our the peanuts and let them cool down before we eat
0:02:28.710,0:02:31.782
一道非常香辣爽脆的下酒花生米就制作完成
A very tasty, spicy, and crunchy peanuts that go well with wine is finished
0:02:31.880,0:02:33.318
下面开始技术总结
Now let's summarize the techniques
0:02:33.700,0:02:34.260
第一
First
0:02:34.424,0:02:36.060
花生米最好选择陈花生米
When choosing peanuts, older ones are better
0:02:36.631,0:02:39.025
这样经过浸泡之后很容易将皮搓掉
Because their skin is easier to remove after soaking
0:02:39.874,0:02:40.380
第二
Secondly
0:02:40.500,0:02:43.522
花生米经过一冷一热再油炸可以变得异常酥脆
Freezing the peanuts and then frying it can make it extra crunchy
0:02:44.745,0:02:45.266
第三
Thirdly
0:02:45.409,0:02:48.677
不喜欢麻辣的同学也可以用其他香料代替花椒辣椒
If you don't like the spicy and numbing flavor, you can replace peppercorns and peppers with other spices
0:02:48.870,0:02:50.647
麻辣花生米的技术总结完毕
Above is all techniques for Spicy and Numbing Peanuts
