### ISSUE TITLE
【美食作家王刚】看望凉糕师父 - https://youtu.be/0oeAW3RtEw0

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1399]
**视频链接**：https://youtu.be/0oeAW3RtEw0

视频时长3:58，预计发布时间为北京时间8月18日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
师父虽卖凉糕挑担子30多年但身板笔直，聊一聊之前的故事和以后的安排

简介
大家好，今天来看望我师父，顺便把之前借来的工具还回来。聊了很多之前的故事和以后的安排，之前当兵的经历改变了他很多，甚至一直影响他至今。由于家人想让他在家享清福，所以以后可能也就不再卖凉糕了，不过也要看街坊邻居是不是还真的想吃传统凉糕，相信一切都会是最好的安排，我也会把这门手艺用另一种形式继续传承，大家可以通过视频来学习，师父本人的意愿是只要想学就不怕漏手艺！传统凉糕的制作：https://www.youtube.com/watch?v=kJGlCChsWz4

字幕
0:00:00.256,0:00:00.913
哈喽 大家好

0:00:01.028,0:00:03.788
上次跟我师父借了这个工具以后

0:00:04.160,0:00:06.251
 我用这个也做了一个凉糕

0:00:06.440,0:00:08.601
也做出了以前小时候的味道

0:00:08.972,0:00:10.780
现在我拿回来还给他

0:00:11.512,0:00:15.687
他今天因为这个天气下雨 所以没有出摊

0:00:15.906,0:00:18.345
所以我今天特意来看一下他

0:00:25.802,0:00:27.870
我给你拿点水果来

0:00:28.917,0:00:32.198
这个我拷了50坨

0:00:32.198,0:00:35.845
一坨平均都有一斤多重 是不是我倒多了哦

0:00:36.633,0:00:38.246
你舀满了

0:00:38.274,0:00:39.321
舀得太满了噶

0:00:40.226,0:00:41.612
米又买了2袋啊

0:00:41.612,0:00:42.998
啊 拷了2盆啊

0:00:42.998,0:00:43.810
  就是那点

0:00:43.810,0:00:44.809
卖2天 卖了就没得了

0:00:45.063,0:00:45.456
哦

0:00:45.664,0:00:47.236
那以后都不卖了啊

0:00:47.236,0:00:49.075
不卖了 这下明年都不卖了

0:00:49.687,0:00:52.075
 今年他要卖我都不要他卖了

0:00:52.462,0:00:56.612
以前我都是立了秋我就不干了

0:00:57.480,0:00:58.763
立了秋我就不干了

0:00:58.763,0:01:00.770
不是  师父你的意思是以后都不干了啊

0:01:00.832,0:01:01.190
 啊

0:01:01.225,0:01:03.028
那不能说得那么绝对

0:01:03.028,0:01:05.329
我不要他卖了 

0:01:06.531,0:01:08.069
他想着想着就要卖

0:01:08.104,0:01:09.780
之前歇了五年没卖  不要他卖了

0:01:10.104,0:01:11.919
街上的人要吃我的凉糕的嘛

0:01:11.919,0:01:14.531
有人问他嘛 他回来又不得了

0:01:14.531,0:01:19.017
街上好多（起码不低于20个）人都说你好多年没干了

0:01:19.017,0:01:21.410
我就好多年没吃凉糕了

0:01:22.323,0:01:25.413
看嘛 我师父说了今年干了以后都不干了

0:01:26.000,0:01:28.670
那不能说得那么绝对

0:01:28.890,0:01:30.809
要求大了就整点

0:01:31.791,0:01:36.027
街坊在呼唤的时候还是要出来摆摊

0:01:36.231,0:01:42.023
搞忘记给你说（糖浆）要拿白纱布来沥过

0:01:42.023,0:01:45.383
2斤糖 才弄得黏稠

0:01:45.838,0:01:46.959
 黏 还是黏

0:01:47.132,0:01:48.771
可以黏不可以清

0:01:48.771,0:01:50.739
 清了你不能改 黏了可以

0:01:50.739,0:01:52.624
 过于黏了也不得行

0:01:52.786,0:01:57.951
以后师父不干了 你的这套工具传给我撒

0:01:58.404,0:01:59.260
要的啊

0:01:59.283,0:02:00.924
我以后把这个担子挑起来

0:02:01.086,0:02:02.820
师父你今年好多岁了

0:02:02.994,0:02:04.473
65啊

0:02:05.930,0:02:07.019
以前你在哪里当兵安

0:02:10.011,0:02:16.080
辽阳待了9个月  在山东又呆了3年多

0:02:16.323,0:02:17.260
呆了3年多啊

0:02:18.219,0:02:21.838
就是我们很多粉丝说你站得很直

0:02:22.046,0:02:25.188
他们都在说你是不是当过兵的 我跟他们说是当过兵的

0:02:27.734,0:02:32.531
你看我的2块军属牌都在上面得

0:02:32.682,0:02:33.467
军属

0:02:34.323,0:02:35.421
那会你好多岁安

0:02:35.895,0:02:36.716
那会20岁

0:02:37.433,0:02:38.404
20岁啊去当兵

0:02:38.404,0:02:40.417
那会调皮

0:02:40.878,0:02:45.650
这个在部队里党和国家教育多好

0:02:45.650,0:02:50.228
很多人安以前可能是有点调皮

0:02:50.485,0:02:54.660
随便哪个 摸都就要跟你干起（打架）

0:02:54.660,0:02:59.294
现在就可以 随便啥子都和和气气的

0:02:59.491,0:03:05.873
给人家犁过田 喂过牛 还卖过肉 做过屠夫

0:03:05.873,0:03:11.993
看来当兵可以让一个人思想变好

0:03:13.352,0:03:15.768
怎么说呢 我这个年纪肯定是去不了

0:03:16.340,0:03:17.689
小时候是挺想去的

0:03:18.404,0:03:19.352
但是很多原因吧

0:03:19.352,0:03:21.423
当兵真的是这样子

0:03:22.011,0:03:23.653
以前还是3年噶

0:03:24.046,0:03:25.317
以前我是4年

0:03:25.317,0:03:27.237
最早是4年啊

0:03:27.237,0:03:28.170
4年义务

0:03:28.404,0:03:29.109
嗯

0:03:29.514,0:03:31.240
要得 师父

0:03:31.240,0:03:32.901
就在这里吃午饭嘛

0:03:32.901,0:03:34.716
我回去还有事

0:03:34.855,0:03:37.317
以后下次再来看你

0:03:37.445,0:03:38.219
好

0:03:38.369,0:03:41.583
如果你确实是不做这个了 

0:03:42.797,0:03:44.994
到时候我来接着干

0:03:45.144,0:03:46.265
啊 要的啊 

0:03:47.791,0:03:48.173
走了 

0:03:48.219,0:03:48.913
好 要的

0:03:50.242,0:03:51.780
好 慢走你

0:03:51.907,0:03:52.300
嗯

0:03:53.075,0:03:54.682
你不送不送 下着雨的

0:03:54.867,0:03:55.410
你慢走


```

**Comment by yurichuanqi** [comment]
认领

**Comment by yurichuanqi** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
师父虽卖凉糕挑担子30多年但身板笔直，聊一聊之前的故事和以后的安排
Talk to the master who has been selling cold cakes for more than 30 years
简介
大家好，今天来看望我师父，顺便把之前借来的工具还回来。聊了很多之前的故事和以后的安排，之前当兵的经历改变了他很多，甚至一直影响他至今。由于家人想让他在家享清福，所以以后可能也就不再卖凉糕了，不过也要看街坊邻居是不是还真的想吃传统凉糕，相信一切都会是最好的安排，我也会把这门手艺用另一种形式继续传承，大家可以通过视频来学习，师父本人的意愿是只要想学就不怕漏手艺！传统凉糕的制作：https://www.youtube.com/watch?v=kJGlCChsWz4
Hello everyone, I came to visit my master today and return the tools I borrowed earlier by the way. I talked about a lot of previous stories and future arrangements. The previous experience of serving as a soldier has changed him a lot, and it has even affected him to this day. Since his family wants him to enjoy the blessing at home, he may no longer sell cold cakes in the future, but it also depends on whether the neighbors in the neighborhood really want to eat traditional cold cakes. I believe everything will be the best arrangement, and I will also Let this craft be passed on in another form. Everyone can learn it through video. Master's personal wish is that as long as you want to learn, you will not be afraid of missing the craft! Making traditional cold cake: https://www.youtube.com/watch?v=kJGlCChsWz4
字幕
0:00:00.256,0:00:00.913
哈喽 大家好
Hello everyone
0:00:01.028,0:00:03.788
上次跟我师父借了这个工具以后
After borrowing this tool from my master last time,
0:00:04.160,0:00:06.251
我用这个也做了一个凉糕
I also made a cold cake with this
0:00:06.440,0:00:08.601
也做出了以前小时候的味道
also made the taste of my childhood
0:00:08.972,0:00:10.780
现在我拿回来还给他
Now I take it back to him
0:00:11.512,0:00:15.687
他今天因为这个天气下雨 所以没有出摊
He didn’t have a stall today because of the rain
0:00:15.906,0:00:18.345
所以我今天特意来看一下他
So I visit to him today specially
0:00:25.802,0:00:27.870
我给你拿点水果来
I'll bring you some fruit
0:00:28.917,0:00:32.198
这个我拷了50坨
I took 50 lumps of this
0:00:32.198,0:00:35.845
一坨平均都有一斤多重 是不是我倒多了哦
A tuft weighs one jin(0.5kg) on average, is it because I have fallen too much
0:00:36.633,0:00:38.246
你舀满了
You scoop full
0:00:38.274,0:00:39.321
舀得太满了噶
The scoop is too full
0:00:40.226,0:00:41.612
米又买了2袋啊
I bought 2 more bags of rice
0:00:41.612,0:00:42.998
啊 拷了2盆啊
Ah, I got 2 pots
0:00:42.998,0:00:43.810
就是那点
That's it
0:00:43.810,0:00:44.809
卖2天 卖了就没得了
Sold for 2 days, it ends when sold out
0:00:45.063,0:00:45.456
哦
Oh
0:00:45.664,0:00:47.236
那以后都不卖了啊
Then you won't sell it anymore
0:00:47.236,0:00:49.075
不卖了 这下明年都不卖了
Don’t sell it anymore, I won’t sell it next year
0:00:49.687,0:00:52.075
今年他要卖我都不要他卖了
I don’t want him to sell it this year
0:00:52.462,0:00:56.612
以前我都是立了秋我就不干了
I used to stop doing it until Autumn beigins
0:00:57.480,0:00:58.763
立了秋我就不干了
I won't do it until Liqiu
0:00:58.763,0:01:00.770
不是  师父你的意思是以后都不干了啊
Master, you mean you don’t do it anymore.
0:01:00.832,0:01:01.190
啊
Ah
0:01:01.225,0:01:03.028
那不能说得那么绝对
That can't be said absolutely
0:01:03.028,0:01:05.329
我不要他卖了 
I don't want him to sell it
0:01:06.531,0:01:08.069
他想着想着就要卖
He thinks about it and sells it
0:01:08.104,0:01:09.780
之前歇了五年没卖  不要他卖了
I haven’t sold it for five years, don’t let him sell it
0:01:10.104,0:01:11.919
街上的人要吃我的凉糕的嘛
The people on the street who want to eat my cold cake?
0:01:11.919,0:01:14.531
有人问他嘛 他回来又不得了
Someone asked him, he was terrible when he came back
0:01:14.531,0:01:19.017
街上好多（起码不低于20个）人都说你好多年没干了
Many people on the street (at least not less than 20) said you haven’t done it for years
0:01:19.017,0:01:21.410
我就好多年没吃凉糕了
I haven't eaten cold cakes for years
0:01:22.323,0:01:25.413
看嘛 我师父说了今年干了以后都不干了
Look, my master said that after doing it this year, I will stop doing it
0:01:26.000,0:01:28.670
那不能说得那么绝对
That can't be said absolutely
0:01:28.890,0:01:30.809
要求大了就整点
It's the whole point
0:01:31.791,0:01:36.027
街坊在呼唤的时候还是要出来摆摊
Neighbors still have to come out to set up stalls when they call
0:01:36.231,0:01:42.023
搞忘记给你说（糖浆）要拿白纱布来沥过
I forgot to tell you (syrup) to drain with white gauze
0:01:42.023,0:01:45.383
2斤糖 才弄得黏稠
2 pounds of sugar makes it sticky
0:01:45.838,0:01:46.959
 黏 还是黏
Sticky and sticky
0:01:47.132,0:01:48.771
可以黏不可以清
Can be sticky but not be clear
0:01:48.771,0:01:50.739
 清了你不能改 黏了可以
You can’t change it if it’s cleared
0:01:50.739,0:01:52.624
 过于黏了也不得行
Too sticky, not good
0:01:52.786,0:01:57.951
以后师父不干了 你的这套工具传给我撒
Master will quit in the future, pass this set of your tools to me
0:01:58.404,0:01:59.260
要的啊
Yes
0:01:59.283,0:02:00.924
我以后把这个担子挑起来
I will pick up this task later
0:02:01.086,0:02:02.820
师父你今年好多岁了
Master, how old are you?
0:02:02.994,0:02:04.473
65啊
65
0:02:05.930,0:02:07.019
以前你在哪里当兵安
Where did you work as a soldier before
0:02:10.011,0:02:16.080
辽阳待了9个月  在山东又呆了3年多
Stayed in Liaoyang for 9 months and stayed in Shandong for more than 3 years
0:02:16.323,0:02:17.260
呆了3年多啊
Stayed  more than 3 years
0:02:18.219,0:02:21.838
就是我们很多粉丝说你站得很直
Many of our fans said you stand straight
0:02:22.046,0:02:25.188
他们都在说你是不是当过兵的 我跟他们说是当过兵的
They are all asking if you were a soldier, I told them that you were a soldier
0:02:27.734,0:02:32.531
你看我的2块军属牌都在上面得
Look at my 2 military family members cards.
0:02:32.682,0:02:33.467
军属
Military family members
0:02:34.323,0:02:35.421
那会你好多岁安
How old were you then?
0:02:35.895,0:02:36.716
那会20岁
20 years old then
0:02:37.433,0:02:38.404
20岁啊去当兵
Served as a soldier at 20
0:02:38.404,0:02:40.417
那会调皮
I was naughty then
0:02:40.878,0:02:45.650
这个在部队里党和国家教育多好
How good is it to receive education from the CPC and the country in the army
0:02:45.650,0:02:50.228
很多人安以前可能是有点调皮
Many people used to be a bit naughty
0:02:50.485,0:02:54.660
随便哪个 摸都就要跟你干起（打架）
Anyone who touches will have to fight with you
0:02:54.660,0:02:59.294
现在就可以 随便啥子都和和气气的
It's okay right now, whatever you want is nice
0:02:59.491,0:03:05.873
给人家犁过田 喂过牛 还卖过肉 做过屠夫
I plowed the fields for others, fed the cows and sold meat, I was a butcher
0:03:05.873,0:03:11.993
看来当兵可以让一个人思想变好
It seems that being a soldier can make a person think better
0:03:13.352,0:03:15.768
怎么说呢 我这个年纪肯定是去不了
How should I put it? I must not be a soldier at my age
0:03:16.340,0:03:17.689
小时候是挺想去的
I wanted to be a soldier when I was young
0:03:18.404,0:03:19.352
但是很多原因吧
But for many reasons
0:03:19.352,0:03:21.423
当兵真的是这样子
It's really like this as a soldier
0:03:22.011,0:03:23.653
以前还是3年噶
It was 3 years before
0:03:24.046,0:03:25.317
以前我是4年
I used to serve for 4 years
0:03:25.317,0:03:27.237
最早是4年啊
4 years at the earliest
0:03:27.237,0:03:28.170
4年义务
4 years conscript
0:03:28.404,0:03:29.109
嗯
Yeah
0:03:29.514,0:03:31.240
要得 师父
Yes, master
0:03:31.240,0:03:32.901
就在这里吃午饭嘛
Right here for lunch
0:03:32.901,0:03:34.716
我回去还有事
I'm still going back
0:03:34.855,0:03:37.317
以后下次再来看你
I'll see you next time
0:03:37.445,0:03:38.219
好
OK
0:03:38.369,0:03:41.583
如果你确实是不做这个了 
If you really don't do this
0:03:42.797,0:03:44.994
到时候我来接着干
I'll continue to work when the time comes
0:03:45.144,0:03:46.265
啊 要的啊 
OK
0:03:47.791,0:03:48.173
走了 
I am leaving
0:03:48.219,0:03:48.913
好 要的
OK
0:03:50.242,0:03:51.780
好 慢走你
OK, go safety
0:03:51.907,0:03:52.300
嗯
Yeah
0:03:53.075,0:03:54.682
你不送不送 下着雨的
You don't have to send me, it's raining
0:03:54.867,0:03:55.410
你慢走
Go safety

**Comment by yurichuanqi** [comment]
thank you

**Comment by immoonancient** [comment]
@yurichuanqi 请问你在我们的微信群里吗？
不在的话建议加一下，方便沟通。请加我微信 immoonancient

**Comment by yurichuanqi** [comment]
我加你微信了，请通过一下
