### ISSUE TITLE
【美食作家王刚】宝塔肉 - https://www.youtube.com/watch?v=Hpy48FLnYWY

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1426]
**视频链接**：<视频链接>

西瓜视频链接：https://www.ixigua.com/6864483743420121612?logTag=USPM86-rVVLmsf4UP7u2b

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
<视频标题（如果标题无需翻译，请删除此节）>

简介
<视频简介（如果简介无需翻译，请删除此节）>

字幕
哈喽大家好我是王刚
本期视频我跟大家分享一道家常菜
宝塔肉
首先我们准备不脱层的五花肉一块
肉的尺寸大概为18厘米的正方形
然后将肉放在漏勺或者铁架子上烧焦备用
没有喷枪的同学也可以在铁锅中烙黑
肉皮烧焦黑之后用清水清洗干净备用
下一步开始准备煮肉的香料
碗中加入八角2颗
加入桂皮2小块
加入几勺红曲米粉
准备大葱1根切成小段备用
准备生姜1小块切成姜片备用
下一步开始煮肉
首先锅中加入大半锅清水
然后将肉和辅料下锅大火烧开
中途加入适量的黄酒去腥
大火烧开后去除浮沫
然后转小火煮15分钟
这一步只需要将五花肉煮至上色即可
15分钟之后捞出在肉皮上抹上适量的盐
这一步的目的是防止猪肉下锅炸的时候爆油
家庭制作可以省略这一步（摸盐，炸肉）
然后将肉下入6成油温的锅中煎炸1分钟左右
这一步的目的是增加猪皮的韧劲不容易蒸烂
将猪肉放入平整的托盘中压上重物
最后放入冰箱中冰冻6小时
同学们只有经过冰冻的肉才能更好的切成薄片
下一步开始准备垫底的原料
准备适量的芽菜清洗十遍备用
多洗几遍可以更好的去除芽菜的咸度和泥沙
清洗干净之后切碎备用
准备大蒜几颗和生姜1小块剁碎备用
碗中加入适量的干辣椒段
不能吃辣的同学也可以不加
再加入适量的花椒
下一步开始调酱
碗中加入适量的柱候酱
加入适量的排骨酱
加入适量的海鲜酱
加入适量的甜面酱
再加入南乳一小块
加入适量的蚝油
最后加入适量的黄酒搅拌均匀备用
然后拿出冻好的猪肉对比磨具切下多余的边角料
同学们切下的边角料可以切成小粒
再和芽菜一起翻炒垫底
下一步开始切肉
将五花肉皮朝自己直刀切至底部不断
然后转角的时候切一个小弧形防止断裂
切的时候必须看着肉皮随时掌握厚薄度
边切边转圈就像削苹果皮的原理一样
同学们切记不能切断否则很费菜
长肉片切好之后再均匀的抹上调好的酱料
涂抹均匀之后再顺着原来的方向将五花肉裹回原形
裹好的形状必须是一开始的正方形
否则裹歪或者形状不对都无法放入磨具中
然后将猪皮朝下整齐的套入模具里面
下一步开始炒“底料”
锅烧热后加入少许的底油
油温5成热之后下入边角料爆香
边角料爆香后下入切好的姜蒜辣椒花椒
料头爆香后加入切好的芽菜粒炒香
调味只需要加入剩余的酱汁
再加入适量的酱油和黄酒即可
翻炒均匀之后再填充到模具里面
同学们填充好之后一定要用筷子稍微挤压
否则肉倒出来的时候会比较“歪”
然后再放入锅中蒸3小时
嫌慢的同学也可以放入高压锅中压25分钟
宝塔肉的特点是蒸得越软越好
时间到了之后取出宝塔肉将多余的汁水倒回锅中
然后再加入适量的清水和淀粉把汤汁收浓
最后淋在肉上面即可
一道非常美味的宝塔肉就制作完成
下面开始技术总结
第一，猪肉切片时肉皮一定要对着自己，否则就像这样切得很厚，当然这是一个错误的示范
第二，家庭制作可以不用抹盐和下油锅炸，蒸的时候也可以用高压锅更节省时间
第三，煮好的猪肉必须用重物压制后冰冻，大家可以看一下未冰冻之后出品的效果，这也是错误的示范
第四，芽菜清洗的时候需要摘除其中的野草或者异物
第五，所有调味酱中都含有咸味，所以在烹饪中需要特别注意咸度
宝塔肉的技术总结完毕
```

**Comment by SilvesterDong** [comment]
Hello, everyone. I'm Wang Gang.
In this video I'm going to share a popular dish with you.
Pagoda Pork Belly
First, let's prepare a piece of firm pork belly
The measurements of the belly are approximately 18 cm square.
Then burn the skin on a leaky spoon or rack
For those of you who don't have a burner, you can burn the skin in a hot wok.
Once the skin is blackened, rinse the meat with water and clean it well.
Next, start preparing the spices for cooking the meat.
Add 2 star anise to the bowl
Add 2 small pieces of cinnamon
Add a few spoonfuls of red yeast rice flour
Prepare 1 large scallion cut into small pieces
Prepare 1 small piece of ginger cut into slices
Next, start cooking the meat.
First add water to the wok until half full
Then bring the meat and ingredients to a boil over high heat.
Add some huangjiu rice wine in the middle of the process to remove the odor.
After boiling over high heat, remove scum.
Then turn down the heat and cook for another 15 minutes.
All you need to do for this step is cook the pork until it's nicely browned.
After 15 minutes, remove the meat and rub a generous amount of salt on the skin.
The purpose of this step is to prevent the oil from exploding when the pork is fried.
You can skip this step if you make it at home (rub salt, and fry meat)
Then fry the meat with 60% oil temperature (180 °C) for about 1 minute.
The purpose of this step is to increase the toughness of the pork skin so that it doesn't rotten easily.
Place the pork on a flat tray and press down on a heavy weight
Finally, place in the freezer for 6 hours.
Only meat that been frozen is better sliced thinly.
The next step is to start preparing the other ingredients.
Prepare some "Ya Cai" Sichuan preserved mustard greens and wash them about ten times.
Washing the "Ya Cai" will better remove the saltiness and sediment from them
After washing, chop it up.
Chop a few garlics and 1 small piece of ginger into fine pieces.
Add the dried chili segments to the bowl
Don't add chilli if you can't eat spicy food.
And add a good amount of Sichuan peppercorns.
Next let's prepare the sauce.
Add some Chu Hou Sauce to the bowl
Add some Spare Rib Sauce
Add some Hoisin Sauce
Add some "Tian Mian Jiang" sweet bean paste
Add a small piece of Red Beancurd
Add some Oyster Sauce
Finally, stir in some of the huangjiu rice wine.
Then take out the frozen pork and cut off any excess trimmings compared to the mold.
Cut the excess trimmings into small pieces
And then stir-fry with the "Ya Cai" Sichuan preserved mustard greens
Next, start cutting the meat.
Cut the skin of the pork belly towards you straight down to the bottom continuously
And then when you reach the corner, cut a small arc to turn to prevent breakage.
You have to keep an eye on the thickness of the skin when you cut it.
Cutting and turning is like peeling an apple.
Remember, don't break or it'll cost you a fortune.
Once the long sliced meat is cut, rub it evenly with the sauce.
And then wrap the pork back into its original shape in the same direction.
The wrapped shape must be a square just like the original shape.
Otherwise, it will not fit into the mold.
Then, place the pork skin side down neatly inside the mold.
The next step is to start frying the "base"
Add a bit bottom oil after the wok is hot.
When the oil temperature is about 50% (150 ℃), add in the excess trimmings.
And then add the chopped ginger, garlic, and chili.
And then add the chopped "Ya Cai" Sichuan preserved mustard greens and stir-fry.
Add the rest of the sauce to adjust the taste.
Add some soy sauce and cooking wine to taste.
Stir-fry evenly and then fill it into the mold.
Must use chopsticks to squeeze the "base" after filling.
Otherwise, the meat will be "crooked" when the dish is ready.
Then steam the whole thing for 3 hours
If you think it's too slow, you can put it into the pressure cooker for 25 minutes.
The characteristic of the Pagoda Pork Belly is that the softer it is steamed, the better.
When the time is up remove the meat and pour the excess juices back into the wok.
Then add some water and starch to thicken the sauce.
Pour the sauce over the meat at the end.
A very tasty Pagoda Pork Belly is ready!
Let's start the technical summary.
First, the skin must be facing you when slicing the pork, otherwise it will cut thickly like this, which is of course a false demonstration
Secondly, if you do it at home, you don't have to deep fry it. You can also steam it in a pressure cooker to save time.
Thirdly, cooked pork must be pressed with a heavy object and then frozen. There is another false demonstration.
Fourth, "Ya Cai" Sichuan preserved mustard greens must be washed and cleaned to remove sediment.
Fifth, all sauces contain saltiness, so you need to pay special attention to the saltiness in cooking.
The technical summary of the Pagoda Pork Belly is complete

**Comment by immoonancient** [comment]
bot, please upload on behalf of the assignee

哈喽大家好我是王刚
Hello, everyone. I'm Wang Gang.

本期视频我跟大家分享一道家常菜
In this video I'm going to share a popular dish with you.

宝塔肉
Pagoda Pork Belly

首先我们准备不脱层的五花肉一块
First, let's prepare a piece of firm pork belly

肉的尺寸大概为18厘米的正方形
The measurements of the belly are approximately 18 cm square.

然后将肉放在漏勺或者铁架子上烧焦备用
Then burn the skin on a leaky spoon or rack

没有喷枪的同学也可以在铁锅中烙黑
For those of you who don't have a burner, you can burn the skin in a hot wok.

肉皮烧焦黑之后用清水清洗干净备用
Once the skin is blackened, rinse the meat with water and clean it well.

下一步开始准备煮肉的香料
Next, start preparing the spices for cooking the meat.

碗中加入八角2颗
Add 2 star anise to the bowl

加入桂皮2小块
Add 2 small pieces of cinnamon

加入几勺红曲米粉
Add a few spoonfuls of red yeast rice flour

准备大葱1根切成小段备用
Prepare 1 large scallion cut into small pieces

准备生姜1小块切成姜片备用
Prepare 1 small piece of ginger cut into slices

下一步开始煮肉
Next, start cooking the meat.

首先锅中加入大半锅清水
First add water to the wok until half full

然后将肉和辅料下锅大火烧开
Then bring the meat and ingredients to a boil over high heat.

中途加入适量的黄酒去腥
Add some huangjiu rice wine in the middle of the process to remove the odor.

大火烧开后去除浮沫
After boiling over high heat, remove scum.

然后转小火煮15分钟
Then turn down the heat and cook for another 15 minutes.

这一步只需要将五花肉煮至上色即可
All you need to do for this step is cook the pork until it's nicely browned.

15分钟之后捞出在肉皮上抹上适量的盐
After 15 minutes, remove the meat and rub a generous amount of salt on the skin.

这一步的目的是防止猪肉下锅炸的时候爆油
The purpose of this step is to prevent the oil from exploding when the pork is fried.

家庭制作可以省略这一步（摸盐，炸肉）
You can skip this step if you make it at home (rub salt, and fry meat)

然后将肉下入6成油温的锅中煎炸1分钟左右
Then fry the meat with 60% oil temperature (180 °C) for about 1 minute.

这一步的目的是增加猪皮的韧劲不容易蒸烂
The purpose of this step is to increase the toughness of the pork skin so that it doesn't rotten easily.

将猪肉放入平整的托盘中压上重物
Place the pork on a flat tray and press down on a heavy weight

最后放入冰箱中冰冻6小时
Finally, place in the freezer for 6 hours.

同学们只有经过冰冻的肉才能更好的切成薄片
Only meat that been frozen is better sliced thinly.

下一步开始准备垫底的原料
The next step is to start preparing the other ingredients.

准备适量的芽菜清洗十遍备用
Prepare some "Ya Cai" Sichuan preserved mustard greens and wash them about ten times.

多洗几遍可以更好的去除芽菜的咸度和泥沙
Washing the "Ya Cai" will better remove the saltiness and sediment from them

清洗干净之后切碎备用
After washing, chop it up.

准备大蒜几颗和生姜1小块剁碎备用
Chop a few garlics and 1 small piece of ginger into fine pieces.

碗中加入适量的干辣椒段
Add the dried chili segments to the bowl

不能吃辣的同学也可以不加
Don't add chilli if you can't eat spicy food.

再加入适量的花椒
And add a good amount of Sichuan peppercorns.

下一步开始调酱
Next let's prepare the sauce.

碗中加入适量的柱候酱
Add some Chu Hou Sauce to the bowl

加入适量的排骨酱
Add some Spare Rib Sauce

加入适量的海鲜酱
Add some Hoisin Sauce

加入适量的甜面酱
Add some "Tian Mian Jiang" sweet bean paste

再加入南乳一小块
Add a small piece of Red Beancurd

加入适量的蚝油
Add some Oyster Sauce

最后加入适量的黄酒搅拌均匀备用
Finally, stir in some of the huangjiu rice wine.

然后拿出冻好的猪肉对比磨具切下多余的边角料
Then take out the frozen pork and cut off any excess trimmings compared to the mold.

同学们切下的边角料可以切成小粒
Cut the excess trimmings into small pieces

再和芽菜一起翻炒垫底
And then stir-fry with the "Ya Cai" Sichuan preserved mustard greens

下一步开始切肉
Next, start cutting the meat.

将五花肉皮朝自己直刀切至底部不断
Cut the skin of the pork belly towards you straight down to the bottom continuously

然后转角的时候切一个小弧形防止断裂
And then when you reach the corner, cut a small arc to turn to prevent breakage.

切的时候必须看着肉皮随时掌握厚薄度
You have to keep an eye on the thickness of the skin when you cut it.

边切边转圈就像削苹果皮的原理一样
Cutting and turning is like peeling an apple.

同学们切记不能切断否则很费菜
Remember, don't break or it'll cost you a fortune.

长肉片切好之后再均匀的抹上调好的酱料
Once the long sliced meat is cut, rub it evenly with the sauce.

涂抹均匀之后再顺着原来的方向将五花肉裹回原形
And then wrap the pork back into its original shape in the same direction.

裹好的形状必须是一开始的正方形
The wrapped shape must be a square just like the original shape.

否则裹歪或者形状不对都无法放入磨具中
Otherwise, it will not fit into the mold.

然后将猪皮朝下整齐的套入模具里面
Then, place the pork skin side down neatly inside the mold.

下一步开始炒“底料”
The next step is to start frying the "base"

锅烧热后加入少许的底油
Add a bit bottom oil after the wok is hot.

油温5成热之后下入边角料爆香
When the oil temperature is about 50% (150 ℃), add in the excess trimmings.

边角料爆香后下入切好的姜蒜辣椒花椒
And then add the chopped ginger, garlic, and chili.

料头爆香后加入切好的芽菜粒炒香
And then add the chopped "Ya Cai" Sichuan preserved mustard greens and stir-fry.

调味只需要加入剩余的酱汁
Add the rest of the sauce to adjust the taste.

再加入适量的酱油和黄酒即可
Add some soy sauce and cooking wine to taste.

翻炒均匀之后再填充到模具里面
Stir-fry evenly and then fill it into the mold.

同学们填充好之后一定要用筷子稍微挤压
Must use chopsticks to squeeze the "base" after filling.

否则肉倒出来的时候会比较“歪”
Otherwise, the meat will be "crooked" when the dish is ready.

然后再放入锅中蒸3小时
Then steam the whole thing for 3 hours

嫌慢的同学也可以放入高压锅中压25分钟
If you think it's too slow, you can put it into the pressure cooker for 25 minutes.

宝塔肉的特点是蒸得越软越好
The characteristic of the Pagoda Pork Belly is that the softer it is steamed, the better.

时间到了之后取出宝塔肉将多余的汁水倒回锅中
When the time is up remove the meat and pour the excess juices back into the wok.

然后再加入适量的清水和淀粉把汤汁收浓
Then add some water and starch to thicken the sauce.

最后淋在肉上面即可
Pour the sauce over the meat at the end.

一道非常美味的宝塔肉就制作完成
A very tasty Pagoda Pork Belly is ready!

下面开始技术总结
Let's start the technical summary.

第一，猪肉切片时肉皮一定要对着自己，否则就像这样切得很厚，当然这是一个错误的示范
First, the skin must be facing you when slicing the pork, otherwise it will cut thickly like this, which is of course a false demonstration

第二，家庭制作可以不用抹盐和下油锅炸，蒸的时候也可以用高压锅更节省时间
Secondly, if you do it at home, you don't have to deep fry it. You can also steam it in a pressure cooker to save time.

第三，煮好的猪肉必须用重物压制后冰冻，大家可以看一下未冰冻之后出品的效果，这也是错误的示范
Thirdly, cooked pork must be pressed with a heavy object and then frozen. There is another false demonstration.

第四，芽菜清洗的时候需要摘除其中的野草或者异物
Fourth, "Ya Cai" Sichuan preserved mustard greens must be washed and cleaned to remove sediment.

第五，所有调味酱中都含有咸味，所以在烹饪中需要特别注意咸度
Fifth, all sauces contain saltiness, so you need to pay special attention to the saltiness in cooking.

宝塔肉的技术总结完毕
The technical summary of the Pagoda Pork Belly is complete

**Comment by immoonancient** [comment]
已发布
