### ISSUE TITLE
【美食作家王刚】 介绍香料 - https://youtu.be/3Mrs5M2Lul8

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1429]
**视频链接**：https://youtu.be/3Mrs5M2Lul8

视频时长4:59，预计发布时间为北京时间8月29日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“香料冷知识”，很多从未见过的香料都在这里了

简介
大家好，今天来给大家介绍一些平常不太常见或者容易搞混的香料，分别从用途和性状来入手给大家讲解。虽说都叫“香料”，但功能却可能非常不一样，其中可以分为“增色”“压腥”“增香”“调味”等等，之后也会给大家分享具体的香料的用法和正宗卤水，敬请期待！

字幕
0:00:00.118,0:00:01.257
哈喽 大家好 我是王刚

0:00:01.370,0:00:02.810
本期视频我跟大家分享

0:00:02.835,0:00:04.775
冷门香料

0:00:07.364,0:00:09.790
第一部分是名字中带“姜”的香料

0:00:09.922,0:00:11.377
大概有沙姜

0:00:12.030,0:00:12.735
良姜

0:00:13.281,0:00:14.090
干姜（脱水姜）

0:00:14.504,0:00:15.179
黄姜

0:00:15.551,0:00:17.970
其中沙姜分干沙姜和鲜沙姜

0:00:17.970,0:00:20.028
良姜主要作用于卤水调配

0:00:20.217,0:00:22.410
干沙姜主要作用于底料炒制

0:00:22.490,0:00:24.455
以及磨成粉制作江湖菜

0:00:24.586,0:00:27.490
自贡菜中又多用于鸡鸭鱼的去腥增香

0:00:27.926,0:00:31.124
干姜其实就是新鲜姜脱水 方便长期储存

0:00:31.470,0:00:32.910
黄姜虽然也带“姜”

0:00:33.190,0:00:35.430
但其实只能用作于菜肴的上色

0:00:35.430,0:00:38.310
其中多用于盐焗鸡或者咖喱酱

0:00:38.566,0:00:40.604
只作用于天然的着色剂

0:00:40.950,0:00:43.550
第二部分是普通家庭比较少见的香料

0:00:43.790,0:00:44.870
大概有檀香

0:00:45.572,0:00:46.393
槟榔片

0:00:46.850,0:00:47.287
辛夷

0:00:47.970,0:00:48.836
五加皮

0:00:49.620,0:00:53.408
檀香在大部分场景中磨碎之后燃烧去除异味

0:00:53.850,0:00:55.825
也能在烹饪中少量的使用

0:00:56.270,0:00:58.763
槟榔片主要用于酱香型调味

0:00:58.910,0:01:00.372
或者酱香卤水调配

0:01:01.159,0:01:02.403
辛夷又名木兰

0:01:02.403,0:01:04.410
在餐饮行业中被称为毛桃

0:01:04.610,0:01:06.711
是因为形状像未长大的毛桃

0:01:06.711,0:01:08.690
大多用于卤水中去腥增香

0:01:09.200,0:01:11.096
五加皮同样是去异增香

0:01:11.229,0:01:12.698
味道闻起来有奶香

0:01:12.880,0:01:14.188
细嚼起来发苦

0:01:14.504,0:01:16.360
卤水中用量以千分比计算

0:01:16.720,0:01:18.805
第三部分分为特殊香味的香料

0:01:18.931,0:01:23.877
大概有香茅草 甘松 灵香草 藿香杆

0:01:23.877,0:01:26.677
其中香茅草的味道和柠檬的味道非常相似

0:01:26.997,0:01:29.111
所以在餐饮行业中被称为柠檬草

0:01:29.378,0:01:32.237
藿香叶在富顺地区多用于豆花蘸水的点缀

0:01:32.637,0:01:35.202
其中藿香摘去叶子之后也将其晒干

0:01:35.202,0:01:36.517
作为增香的香料

0:01:36.926,0:01:38.877
甘松的味道极其特殊和强烈

0:01:38.877,0:01:41.637
在一般人的嗅觉中会认为此香料为足臭

0:01:41.917,0:01:44.663
但在广泛卤水锅中使用之后臭味消失

0:01:45.007,0:01:46.680
反而甘松有压腥的作用

0:01:46.926,0:01:48.967
灵香草也有特殊清淡的香味

0:01:49.160,0:01:51.727
其作用在卤水中是增香防腐护色

0:01:52.087,0:01:53.682
黑白胡椒主要区分为

0:01:54.087,0:01:56.207
白胡椒是完全成熟后的果实

0:01:56.462,0:01:58.407
相反黑胡椒是未成熟的果实

0:01:58.647,0:02:00.960
黑白胡椒为两个不同时段的产物

0:02:01.127,0:02:04.247
黑胡椒比白胡椒更浓香 且辛辣味略低

0:02:04.247,0:02:06.841
由于颜色的限制 所以多用于西餐烹饪

0:02:07.167,0:02:10.047
其中白胡椒主要为去腥增香增辣

0:02:10.257,0:02:11.683
多用于中餐烹饪

0:02:13.229,0:02:15.014
第五是天然上色香料

0:02:15.014,0:02:16.387
大概有红黄之分

0:02:16.525,0:02:19.090
其中有姜黄、红曲米、栀子

0:02:19.457,0:02:20.777
姜黄为纯黄色

0:02:20.937,0:02:23.417
红曲米为纯红色 栀子为橙黄色

0:02:23.785,0:02:25.417
这三种调色剂运用广泛

0:02:25.654,0:02:26.524
比如卤水

0:02:26.967,0:02:27.825
蛋糕

0:02:28.437,0:02:30.229
饮料等食品加工之类

0:02:30.527,0:02:32.407
第六分为最容易混淆的香料

0:02:32.492,0:02:36.314
大概有孜然粒 迷迭香 千里香 小茴香

0:02:36.647,0:02:39.238
其中千里香长得很像缩小版的瓜子

0:02:40.053,0:02:41.971
小茴香像未成熟的稻谷

0:02:42.611,0:02:44.368
孜然则以味道更好的区分

0:02:44.452,0:02:46.104
主要用作于烧烤的撒料

0:02:46.216,0:02:48.662
迷迭香相比其它三样更细更长

0:02:48.877,0:02:50.144
有点类似于茶叶

0:02:50.437,0:02:51.437
因为长相接近

0:02:51.437,0:02:53.757
所以在使用的时候需要区分清楚

0:02:54.037,0:02:55.717
比如作为烧烤的撒料来说

0:02:55.717,0:02:57.780
其它三样均无法代替孜然

0:02:58.127,0:03:00.411
又有几种带壳的香料也很类似

0:03:00.567,0:03:04.500
其中香果、草果、槟榔外形非常相似

0:03:04.621,0:03:07.362
只有将其切开之后才能看到其中的不同

0:03:07.362,0:03:09.447
槟榔切开之后里面是黑色的籽

0:03:09.603,0:03:11.967
香果切开之后是白色饱满的果实

0:03:12.281,0:03:14.621
草果切开之后是较多的小颗粒籽

0:03:14.987,0:03:18.147
第七分为夫妻香料 公丁香和母丁香

0:03:18.347,0:03:19.667
虽然是夫妻香料

0:03:19.849,0:03:21.587
但在外观上却相差甚远

0:03:21.810,0:03:23.431
公丁香是已开的花蕾

0:03:23.567,0:03:25.387
母丁香是花蕾后的果实

0:03:25.534,0:03:27.425
其中广泛应用的是公丁香

0:03:27.867,0:03:29.267
其香味非常的浓烈

0:03:29.414,0:03:30.362
用量极少

0:03:31.002,0:03:32.583
第八为慎重使用的香料

0:03:32.780,0:03:35.327
山楂和当归在烹饪中需要注意用量

0:03:35.675,0:03:37.799
当归在卤水中起到去异增香

0:03:38.160,0:03:40.004
山楂开胃解腻消食

0:03:40.388,0:03:42.584
其中当归有活血化瘀的功效

0:03:42.864,0:03:45.265
所以含有这两样香料加工过的食材

0:03:45.462,0:03:46.344
孕妇慎用

0:03:46.776,0:03:48.904
第九部分是主攻甘甜味的香料

0:03:49.064,0:03:50.624
其中有罗汉果和甘草

0:03:50.957,0:03:53.613
罗汉果在使用过程中水会变成褐色

0:03:53.824,0:03:56.224
所以在卤水中需要考虑到颜色的把控

0:03:56.663,0:03:59.875
罗汉果和甘草在卤水中可以调节苦味和涩味

0:04:00.346,0:04:03.914
在生活中我个人也经常用罗汉果泡开水喝

0:04:06.164,0:04:10.020
第十部分我们来介绍价格差异最大的香料陈皮

0:04:10.648,0:04:12.067
陈皮就像白酒一样

0:04:12.187,0:04:14.127
年份越久 价格越贵

0:04:14.485,0:04:17.083
昂贵的陈皮每斤能达到6位数以上

0:04:17.275,0:04:19.552
一般普通的陈皮10元1斤左右

0:04:19.950,0:04:22.705
最后跟大家分享五香粉和五香卤料

0:04:22.705,0:04:24.600
五香粉其中香料是

0:04:24.600,0:04:30.034
红花椒 丁香 八角 小茴香 桂皮组合而成

0:04:30.294,0:04:33.056
然后再简单的跟大家分享一个五香卤料包

0:04:33.445,0:04:36.942
其中有香叶 甘草 草果 白寇

0:04:36.942,0:04:40.845
甘松 丁香 香果 小茴香 排草

0:04:40.845,0:04:45.005
白芷 荜拨 香砂仁 桂皮 八角

0:04:45.005,0:04:47.100
此配方介于家用和商用之间

0:04:47.100,0:04:49.450
所以五香卤料只是一个名称

0:04:49.450,0:04:51.755
而不是由香料的品种数量来决定

0:04:52.950,0:04:57.800
香料介绍完毕，后续会以香料制作卤水，敬请期待


```

**Comment by ddkite** [comment]
认领

**Comment by ddkite** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“香料冷知识”，很多从未见过的香料都在这里了
Chef Wang teaches you: 10 spice facts you never knew

简介
大家好，今天来给大家介绍一些平常不太常见或者容易搞混的香料，分别从用途和性状来入手给大家讲解。虽说都叫“香料”，但功能却可能非常不一样，其中可以分为“增色”“压腥”“增香”“调味”等等，之后也会给大家分享具体的香料的用法和正宗卤水，敬请期待！
Hello everyone. Today I’m going to introduce you with uncommon and confusing spices, from aspects of their application and features. Functions may vary dramatically among spices which can be divided into categories like coloring, gamey taste inhibition, aroma enhancing, seasoning, and so on. Next, we will continue to share specific application of spices and authentic master stock ingredients.

字幕
0:00:00.118,0:00:01.257
哈喽 大家好 我是王刚
Hello everyone. I’m Wang Gang.

0:00:01.370,0:00:02.810
本期视频我跟大家分享
In this video I’m going to share with you

0:00:02.835,0:00:04.775
冷门香料
uncommon spices

0:00:07.364,0:00:09.790
第一部分是名字中带“姜”的香料
1. spices with “jiang” in their names

0:00:09.922,0:00:11.377
大概有沙姜
which include sand ginger

0:00:12.030,0:00:12.735
良姜
galangal

0:00:13.281,0:00:14.090
干姜（脱水姜）
dried ginger

0:00:14.504,0:00:15.179
黄姜
and turmeric

0:00:15.551,0:00:17.970
其中沙姜分干沙姜和鲜沙姜
Sand ginger is divided into dried and fresh ones.

0:00:17.970,0:00:20.028
良姜主要作用于卤水调配
Galangal is mainly used in master stock.

0:00:20.217,0:00:22.410
干沙姜主要作用于底料炒制
Dried sand ginger is used in hot pot base

0:00:22.490,0:00:24.455
以及磨成粉制作江湖菜
ground for Jianghu dishes

0:00:24.586,0:00:27.490
自贡菜中又多用于鸡鸭鱼的去腥增香
or used in Zigong dishes to remove gamey taste and enhance aroma of chicken, duck, or fish 

0:00:27.926,0:00:31.124
干姜其实就是新鲜姜脱水 方便长期储存
Dried ginger is dehydrated fresh ginger for purpose of long-term storage

0:00:31.470,0:00:32.910
黄姜虽然也带“姜”
Turmeric

0:00:33.190,0:00:35.430
但其实只能用作于菜肴的上色
is only used for adding color

0:00:35.430,0:00:38.310
其中多用于盐焗鸡或者咖喱酱
commonly seen in salt baked chicken and curry paste

0:00:38.566,0:00:40.604
只作用于天然的着色剂
as a natural color additive

0:00:40.950,0:00:43.550
第二部分是普通家庭比较少见的香料
2. spices uncommonly used in normal family

0:00:43.790,0:00:44.870
大概有檀香
which include sandalwood

0:00:45.572,0:00:46.393
槟榔片
betel nut slice

0:00:46.850,0:00:47.287
辛夷
xinyi (flos magnoliae)

0:00:47.970,0:00:48.836
五加皮
and wujiapi

0:00:49.620,0:00:53.408
檀香在大部分场景中磨碎之后燃烧去除异味
Sandalwood is usually ground and burnt to eliminate unpleasant smell

0:00:53.850,0:00:55.825
也能在烹饪中少量的使用
and can also be used in cooking sometimes

0:00:56.270,0:00:58.763
槟榔片主要用于酱香型调味
Betel nut slice is mainly used in sauce fragrant seasoning 

0:00:58.910,0:01:00.372
或者酱香卤水调配
or making master stock
0:01:01.159,0:01:02.403
辛夷又名木兰
Xinyi is also called mulan

0:01:02.403,0:01:04.410
在餐饮行业中被称为毛桃
or maotao in catering industry

0:01:04.610,0:01:06.711
是因为形状像未长大的毛桃
because of its green wild peach - like shape

0:01:06.711,0:01:08.690
大多用于卤水中去腥增香
It is commonly used to remove gamey taste and enhance aroma in master stock.

0:01:09.200,0:01:11.096
五加皮同样是去异增香
Wujiapi is used to remove unpleasant smell and enhance aroma.

0:01:11.229,0:01:12.698
味道闻起来有奶香
It has a milk scent

0:01:12.880,0:01:14.188
细嚼起来发苦
and a bitter taste chewing carefully

0:01:14.504,0:01:16.360
卤水中用量以千分比计算
It is calculated at so much per mill in master stock

0:01:16.720,0:01:18.805
第三部分分为特殊香味的香料
3. spices with special aroma

0:01:18.931,0:01:23.877
大概有香茅草 甘松 灵香草 藿香杆
which include lemongrass, gan song, ling xiang cao, and huo xiang stalk

0:01:23.877,0:01:26.677
其中香茅草的味道和柠檬的味道非常相似
Lemongrass has a lemon flavor

0:01:26.997,0:01:29.111
所以在餐饮行业中被称为柠檬草
so is called “lemon” grass

0:01:29.378,0:01:32.237
藿香叶在富顺地区多用于豆花蘸水的点缀
Huo xiang leaves are commonly used as an ornament in douhua (tofu pudding) dipping sauce 

0:01:32.637,0:01:35.202
其中藿香摘去叶子之后也将其晒干
The stalk can be sun-dried

0:01:35.202,0:01:36.517
作为增香的香料
and used as a spice to enhance aroma

0:01:36.926,0:01:38.877
甘松的味道极其特殊和强烈
The scent of gan song is distinctive and strong

0:01:38.877,0:01:41.637
在一般人的嗅觉中会认为此香料为足臭
It smells like smelly feet to most people

0:01:41.917,0:01:44.663
但在广泛卤水锅中使用之后臭味消失
However, when it is used in common master stock, the smelly odor will disappear

0:01:45.007,0:01:46.680
反而甘松有压腥的作用
and it can inhibit gamey taste

0:01:46.926,0:01:48.967
灵香草也有特殊清淡的香味
Ling xiang cao has a special light aroma

0:01:49.160,0:01:51.727
其作用在卤水中是增香防腐护色
functioning in master stock to enhance aroma, fix color and preserve

0:01:52.087,0:01:53.682
黑白胡椒主要区分为
The difference between black pepper and white pepper is that
0:01:54.087,0:01:56.207
白胡椒是完全成熟后的果实
white pepper is the ripe fruit

0:01:56.462,0:01:58.407
相反黑胡椒是未成熟的果实
while black pepper is the green fruit

0:01:58.647,0:02:00.960
黑白胡椒为两个不同时段的产物
They are the same fruit in different stages

0:02:01.127,0:02:04.247
黑胡椒比白胡椒更浓香 且辛辣味略低
Black pepper tastes stronger and less spicy than white pepper

0:02:04.247,0:02:06.841
由于颜色的限制 所以多用于西餐烹饪
and is mainly used in western dishes

0:02:07.167,0:02:10.047
其中白胡椒主要为去腥增香增辣
White pepper is used to remove gamey taste, enhance aroma and add spicy

0:02:10.257,0:02:11.683
多用于中餐烹饪
and is mainly used in Chinese dishes

0:02:13.229,0:02:15.014
第五是天然上色香料
5. natural coloring spices

0:02:15.014,0:02:16.387
大概有红黄之分
which can introduce red or yellow color

0:02:16.525,0:02:19.090
其中有姜黄、红曲米、栀子
Under this category there are turmeric, red yeast rice, and gardenia

0:02:19.457,0:02:20.777
姜黄为纯黄色
Turmeric adds yellow color

0:02:20.937,0:02:23.417
红曲米为纯红色 栀子为橙黄色
red yeast rice red, and gardenia orange

0:02:23.785,0:02:25.417
这三种调色剂运用广泛
These color additives are widely used in food production

0:02:25.654,0:02:26.524
比如卤水
For example, in master storage

0:02:26.967,0:02:27.825
蛋糕
cakes
0:02:28.437,0:02:30.229
饮料等食品加工之类
drinks and so on

0:02:30.527,0:02:32.407
第六分为最容易混淆的香料
6. confusing spices

0:02:32.492,0:02:36.314
大概有孜然粒 迷迭香 千里香 小茴香
I.e. cumin seed, rosemary, orange jasmine, and fennel seed

0:02:36.647,0:02:39.238
其中千里香长得很像缩小版的瓜子
Orange jasmine looks like miniature sunflower seeds

0:02:40.053,0:02:41.971
小茴香像未成熟的稻谷
Fennel seed looks like unripe paddy rice

0:02:42.611,0:02:44.368
孜然则以味道更好的区分
Cumin seed stands out by its flavor

0:02:44.452,0:02:46.104
主要用作于烧烤的撒料
and is mainly used in BBQ sprinkle seasoning

0:02:46.216,0:02:48.662
迷迭香相比其它三样更细更长
Rosemary is thinner and longer than others

0:02:48.877,0:02:50.144
有点类似于茶叶
looks like tea leaves

0:02:50.437,0:02:51.437
因为长相接近
Because of their similarity 

0:02:51.437,0:02:53.757
所以在使用的时候需要区分清楚
these spices need to be clearly distinguished when cooking

0:02:54.037,0:02:55.717
比如作为烧烤的撒料来说
For example, in BBQ sprinkle seasoning

0:02:55.717,0:02:57.780
其它三样均无法代替孜然
none of the others can be a substitute for cumin seeds

0:02:58.127,0:03:00.411
又有几种带壳的香料也很类似
There are some shelled spices look similar as well

0:03:00.567,0:03:04.500
其中香果、草果、槟榔外形非常相似
Xiang guo (Ligusticum chuanxiong Hort fruit), tsao-ko and betel nut look very much alike
0:03:04.621,0:03:07.362
只有将其切开之后才能看到其中的不同
and can only be distinguished when cut open

0:03:07.362,0:03:09.447
槟榔切开之后里面是黑色的籽
Betel nut has a black core inside

0:03:09.603,0:03:11.967
香果切开之后是白色饱满的果实
xiang guo has a white plump seed

0:03:12.281,0:03:14.621
草果切开之后是较多的小颗粒籽
And tsao-ko has many small seeds when cut open

0:03:14.987,0:03:18.147
第七分为夫妻香料 公丁香和母丁香
7. Couple spices - male clove and female clove

0:03:18.347,0:03:19.667
虽然是夫妻香料
Though are called couple spices

0:03:19.849,0:03:21.587
但在外观上却相差甚远
they differ in looks

0:03:21.810,0:03:23.431
公丁香是已开的花蕾
Male clove is known as clove bud

0:03:23.567,0:03:25.387
母丁香是花蕾后的果实
while female clove refers to clove fruit

0:03:25.534,0:03:27.425
其中广泛应用的是公丁香
Male clove is most widely used

0:03:27.867,0:03:29.267
其香味非常的浓烈
Because of its strong flavor

0:03:29.414,0:03:30.362
用量极少
only a small amount is needed each time

0:03:31.002,0:03:32.583
第八为慎重使用的香料
8. Spices require use with cautious 

0:03:32.780,0:03:35.327
山楂和当归在烹饪中需要注意用量
The amount of hawthorn and dong quai (Chinese Angelica) used in cooking requires attention

0:03:35.675,0:03:37.799
当归在卤水中起到去异增香
Dong quai is used in master stock to remove unpleasant smell and enhance aroma

0:03:38.160,0:03:40.004
山楂开胃解腻消食
Hawthorn can stimulate appetite, refresh palate and promote digestion

0:03:40.388,0:03:42.584
其中当归有活血化瘀的功效
Dong quai can improve blood circulation and transform stasis

0:03:42.864,0:03:45.265
所以含有这两样香料加工过的食材
so pregnant women should be careful

0:03:45.462,0:03:46.344
孕妇慎用
with food containing these two spices

0:03:46.776,0:03:48.904
第九部分是主攻甘甜味的香料
9. Spices that add sweetness

0:03:49.064,0:03:50.624
其中有罗汉果和甘草
include luo han guo (monk fruit) and licorice

0:03:50.957,0:03:53.613
罗汉果在使用过程中水会变成褐色
Luo han guo will turn water into brown color

0:03:53.824,0:03:56.224
所以在卤水中需要考虑到颜色的把控
thus, when luo han guo presents, the color of master stock needs to be considered 

0:03:56.663,0:03:59.875
罗汉果和甘草在卤水中可以调节苦味和涩味
Luo han guo and licorice can neutralize bitter and astringent tastes in master stock

0:04:00.346,0:04:03.914
在生活中我个人也经常用罗汉果泡开水喝
I often make a luo han guo tea by steeping luo han guo in hot water

0:04:06.164,0:04:10.020
第十部分我们来介绍价格差异最大的香料陈皮
10. Largest price difference in spice - dried mandarin peel

0:04:10.648,0:04:12.067
陈皮就像白酒一样
Dried mandarin peel is like baijiu

0:04:12.187,0:04:14.127
年份越久 价格越贵
the price of which increases with age

0:04:14.485,0:04:17.083
昂贵的陈皮每斤能达到6位数以上
The price of dried mandarin peel can be more than one million yuan per jin (0.5kg)

0:04:17.275,0:04:19.552
一般普通的陈皮10元1斤左右
while normal price is about 10 yuan per jin (0.5kg)

0:04:19.950,0:04:22.705
最后跟大家分享五香粉和五香卤料
Lastly, I’m going to share with you Chinese five spice and five spice marinade ingredients

0:04:22.705,0:04:24.600
五香粉其中香料是
Ingredients in Chinese five spice are

0:04:24.600,0:04:30.034
红花椒 丁香 八角 小茴香 桂皮组合而成
red Sichuan peppercorn, clove, star anise, fennel seed, and cinnamon

0:04:30.294,0:04:33.056
然后再简单的跟大家分享一个五香卤料包
Then the recipe of five spice marinade ingredients includes

0:04:33.445,0:04:36.942
其中有香叶 甘草 草果 白寇
bay leaf, licorice, tsao-ko, white cardamom,

0:04:36.942,0:04:40.845
甘松 丁香 香果 小茴香 排草
gan song, clove, xiang guo, fennel seed, xiang pai cao, 

0:04:40.845,0:04:45.005
白芷 荜拨 香砂仁 桂皮 八角
baizhi, long pepper, Cardamom Seed, cinnamon, and star anise

0:04:45.005,0:04:47.100
此配方介于家用和商用之间
This recipe is for either domestic or commercial use

0:04:47.100,0:04:49.450
所以五香卤料只是一个名称
Chinese five spice is a name

0:04:49.450,0:04:51.755
而不是由香料的品种数量来决定
rather than naming the number of spices.

0:04:52.950,0:04:57.800
香料介绍完毕，后续会以香料制作卤水，敬请期待
That is all for spice introduction. Applying spices in master stock is coming soon.
