### ISSUE TITLE
[华农兄弟] 华农兄弟秋季蜂蜜大丰收搞点来烤鸽子油光发亮很美味哦 - https://youtu.be/n58TZep7v7g

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1444]
https://youtu.be/n58TZep7v7g
<p>&#35270;&#39057;&#21457;&#24067;&#20110; September 3, 2020 at 01:10PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
0:00:00.000,0:00:03.340
# 大家好  你看這蜂蜜  全部都有好多糖了哦
Hi everyone! Have a look at the honey. They're all very full now.

0:00:03.780,0:00:05.340
# 叫兄弟過來  幫忙搞一下
I've asked my buddy to come, and help me deal with it.

0:00:06.440,0:00:10.580
# 你看  就這個  全部都站在外面問口啦  不出去採蜜啦
Look! Right this one. They're all standing in front of the door and are not going out for nectar.

0:00:10.920,0:00:11.940
# 里面肯定滿了
It must be full inside.

0:00:13.300,0:00:14.700
# 因為我們這邊好多野花
Cuz there are a lot of wild flowers here around our site.

0:00:15.680,0:00:18.960
# 這秋天  秋天的蜜哦  就叫秋蜜
It's autumn, it's honey in autumn. So it's called autumn honey.

0:00:20.380,0:00:22.520
# 你看  這個是蜂王  看到沒有這個
Look! This is the bee queen. See? It's this one.

0:00:22.900,0:00:23.820
# 這就是蜂王
This is the bee queen.

0:00:25.720,0:00:27.040
# 就這個  就這個蜂王
This one, this is the bee queen.

0:00:27.220,0:00:29.320
# 別挖走了 哈哈哈
Don't scoop it away. Hahaha~

0:00:30.740,0:00:33.940
# 你看這裡  好多那個蜜蜂崽哦  你看  全部都是
Have have look here. Here are a lot of, of baby bees. Look! They're all here.

0:00:34.860,0:00:37.060
# 一卷一卷的  這裡也是哦  (註︰怎樣「一卷一卷」)
They're curling up. Here as well

0:00:37.840,0:00:40.040
# 它有封蓋  等下封了蓋之後它就
They're sealing it off. After it's sealed, it's gonna,

0:00:40.560,0:00:42.540
# 慢慢地就會把那個蜜蜂會長出來
it's gonna slowly, it's gonna grow into a bee.

0:00:43.860,0:00:45.440
# 你看  現在我都不怕蜜蜂啦
Look! Now I am no longer scared of bees.

0:00:46.700,0:00:47.940
# 好漂亮哦這個  你看
It's really pretty. Look!

0:00:48.980,0:00:52.060
# 這個蜜蜂很漂亮的哦這個  我們家裡的土蜂蜜來的  (註︰他又把蜜蜂說成蜂蜜了)
These bees are really pretty, you know. They're our local honey bees here,

0:00:52.420,0:00:55.060
# 不是那種國外的那種大蜂
instead of that kind of big bees from other countries.

0:00:56.240,0:00:58.200
# 好多糖哦  你看這是  是不是
A lot of honey. Have a look here. Right?

0:00:59.600,0:01:01.040
# 搞一點吃一下看下怎麼樣
Let me have some and see how it is.

0:01:02.920,0:01:03.920
# 哎呀  你看
Aya! Look!

0:01:06.660,0:01:07.620
# 好甜啊
It's so sweet!

0:01:11.460,0:01:13.240
# 今天準備搖點糖出來哦
We're gonna spin out some honey today.

0:01:20.560,0:01:24.240
# 好快啊這個  甚麼蜜都可以甩的乾
It's really fast. It can spin out every single drop of honey.

0:01:24.620,0:01:27.240
# 叫兄弟過來  過來幫我的忙
I ask my buddy to come, to come and help me out.

0:01:27.820,0:01:29.280
# 這個太危險了
It's far too dangerous.

0:01:31.160,0:01:33.940
# 不是專業的人不要去搞哦  要不然搞了會
Make sure that you never attempt to do it unless you're a professional. Otherwise,

0:01:34.380,0:01:36.360
# 就把他蟄的鼻青臉腫的
the whole face would get stung and swell like a balloon.

0:01:37.560,0:01:39.320
# 現在今年好多糖啊
Now there's a lot of honey this year.

0:01:41.300,0:01:43.100
# 哎呀  那麼危險
Eya! It's so dangerous!

0:01:57.120,0:01:58.680
# 你看好多糖啊  你看
Look! Here's a lot of honey. Look!

0:02:02.560,0:02:03.500
# 這個糖啊
It's honey.

0:02:04.500,0:02:07.980
# 我們這裡好多  好多這些  秋天是好多那個野花
There are a lot of, a lot of this kind of, a lot of wild flowers here at our place in autumn.

0:02:10.080,0:02:13.260
# 你看  糖就好多  這邊也是  好多哦
Look! Here's plenty of honey. This side too. A lot!

0:02:16.840,0:02:17.720
# 搞一塊來
Let me take a piece.

0:02:18.840,0:02:19.680
# 哎呀
Aya!

0:02:22.720,0:02:24.240
# 吃  我吃幾塊來
Let, let me have a few pieces.

0:02:25.980,0:02:28.140
# 好啦  直接把它甩  甩出來就好啦
Look! Spin it out, spin it out right away and that's it.

0:02:29.140,0:02:31.180
# 甩之前要把這個蓋子  把它
Before spinning, the seal needs to be, it needs to be,

0:02:31.840,0:02:32.460
# 割開
cut open.

0:02:33.220,0:02:34.080
# 就樣就很多
Then there would be a lot.

0:02:52.520,0:02:54.680
# 哇 受不了啦  你看割一塊吃
Wa! I can't resist anymore. I need to cut a piece for myself.

0:03:01.560,0:03:04.300
# 歪呦  好啦  拿出來啦
Wayo! Alright! It's out!

0:03:04.960,0:03:07.860
# 這個拿去甩  其它的拿去甩  這個就是我來吃
This will be put into the spinner. The rest will be put into the spinner. But this is mine.

0:03:08.960,0:03:10.160
# 你看  這個
Look! This,

0:03:11.320,0:03:12.080
# 這個蜂蜜
this honey...

0:03:14.400,0:03:15.200
# 嗯~
Um~

0:03:16.980,0:03:18.100
# 好香啊
It smells so good!

0:03:18.900,0:03:20.080
# 可能現在秋天啦
Perhaps cuz it's autumn now,

0:03:20.760,0:03:23.280
# 這個蜂蜜  比那個春蜜更好吃哦
and the honey, tastes even better than spring honey.

0:03:25.120,0:03:26.260
# 而且產量很高
And the yield is also very high.

0:03:29.740,0:03:31.300
# 整個蜂巢直接咬
Chew the beehive directly.

0:03:33.980,0:03:34.720
# 嗯~
Um~

0:03:36.540,0:03:37.300
# 好甜
So sweet!

0:03:40.260,0:03:42.260
# 你看  這個糖  好多啊
Look! There's, a lot of honey!

0:03:42.960,0:03:43.580
# 看見沒有
See?

0:03:45.200,0:03:47.840
# 這邊就是那個  蜜蜂崽哦  小崽
One this side are the, the baby bees, the babies.

0:03:48.140,0:03:51.980
# 這個我們不要去傷害它  我們只要把那個蜜取掉就好啦
We're not doing harm on them. The honey is all we want. Take the honey, that's it.

0:03:53.340,0:03:56.000
# 你看 這邊也是  全是 一片一片的
Look! This side too. All here. They're in clusters.

0:03:56.460,0:03:59.040
# 這一邊的就是小蜜蜂  小蜜蜂崽來的
Those on this side are the little bees, the baby bees.

0:03:59.380,0:04:03.180
# 所以要  我們不要把它甩出來  就不會破壞到那個小蜂蜜
So we have to, we're not spinning them out. They we won't hurt the little honey bees.

0:04:07.440,0:04:08.300
# 好香
Nice!

0:04:10.220,0:04:11.340
# 好多花粉在這裡
Here's a lot of pollen.

0:04:12.640,0:04:15.700
# 要把這個口要割掉  割掉之後才可以甩哦
This opening needs to be unsealed. We need to unseal it before spinning.

0:04:15.920,0:04:17.600
# 要不然蓋子封著甩不出來
We can't get anything when it's covered by the seal.

0:04:19.200,0:04:22.740
# 我這有兩  兩餅割開的  直接可以甩掉
These two, two boards here are already unsealed and can be spun right away.

0:04:27.680,0:04:29.080
# 誒呦  好快呀
Eyo! It's so fast!

0:04:30.660,0:04:33.200
# 甩的差不多了  要換個  換個面
After spinning for a while, it needs to be, needs to be flipped.

0:04:37.620,0:04:39.860
# 就那面已經甩完啦  就甩這面
I've already done with that side. So this side now.

0:04:41.340,0:04:41.980
# 誒呦
Eyo!

0:04:44.000,0:04:44.860
# 還想跑
You wanna run away?

0:04:51.020,0:04:51.840
# 就沒有啦
That's all?

0:04:52.540,0:04:55.420
# 我以為很多嘞 原來就甩了那麼一丟丟
I thought that it would be a lot. But there's only a tiny little bit.

0:04:57.280,0:04:59.480
# 好輕啊  一甩完就沒啦
It's so light now. After spinning, no more honey.

0:05:03.780,0:05:04.740
# 這蜜蜂
This bee,

0:05:06.180,0:05:07.160
# 想蟄我是不是
does it want to sting me?

0:05:09.380,0:05:10.720
# 來呀  讓你蟄  你蟄
C'mon! I let you sting. Sting me!

0:05:13.660,0:05:14.380
# 別當真啊
Don't take it seriously.

0:05:15.600,0:05:16.440
# 把它倒出來
Let me pour it out.

0:05:27.600,0:05:29.760
# 這裡有三四斤啊  這裡
It's almost, two kilograms here.

0:05:32.380,0:05:36.700
# 這個就是蜂蜜  你看  就  就那兩三餅  就搖到那麼多出來
This is honey. Look! Such much honey can be spun out from just, just a couple of boards.

0:05:39.040,0:05:41.640
# 早上 早上用來裹饅頭  買點饅頭
In the morning, eat it with mantou in the morning. Buy some mantou,

0:05:42.040,0:05:44.140
# 放點蜂蜜  就這樣吃
put some honey, and eat right away.

0:05:44.360,0:05:46.820
# 這個是沒有過濾哦  這樣看上去就是
This has not been filtered. So it looks a bit...

0:05:47.220,0:05:49.980
# 蜂蠟跟那個蜂蜜混在一起  不好看
The beeswax and the honey are mixed together. It doesn't look good.

0:05:54.200,0:05:56.260
# 嗯  好香啊
Um! It smells really nice!

0:05:59.060,0:06:01.060
# 嗯 好香啊
Um! It smells really nice!

0:06:01.520,0:06:03.280
# 明天我拿個東西來烤一下
I'm gonna get something to grill tomorrow.

0:06:03.720,0:06:04.720
# 刷點蜂蜜
Brush some honey.

0:06:08.220,0:06:09.900
# 好啦  我把這個端下下面去
Alright! Let me take it down there,

0:06:12.160,0:06:13.040
# 等著先
and keep it there.

0:06:14.340,0:06:15.220
# 這裡還有好多
Here's still a lot.

0:06:16.200,0:06:17.380
# 來  叫兄弟來甩
Yup! I'll ask my buddy to spin out the honey.

0:06:17.980,0:06:19.180
# 我準備去烤東西啦
And I need to prepare for the barbecue.

0:06:25.480,0:06:27.160
# 你看  搞了幾隻鴿子回來哦
Look! I got a couple of pigeons back.

0:06:27.700,0:06:28.920
# 我們去烤乳鴿
Let's have grilled baby pigeons.

0:06:34.460,0:06:35.940
# 這鴿子你看  漂亮吧
Have a look at this pigeon. It's pretty, isn't it?

0:06:37.280,0:06:39.380
# 可以喲  哎呀  那麼多肉
Not bad! Aya! It's so meaty.

0:06:43.020,0:06:43.580
# 哎呀
Aya!

0:06:44.520,0:06:45.600
# 屎都嚇出來了
I scared the poo out of it.

0:06:46.440,0:06:47.000
# 拿刀來
Let me get my knife.

0:07:00.920,0:07:04.580
# 你看  這三隻乳鴿殺好啦  有一個是黑色的
Look! These three baby pigeons are now cleaned and ready. One of them is black.

0:07:05.980,0:07:08.180
# 可能就是這樣子的  皮膚比較黑
Perhaps it's just because it has a darker skin.

0:07:08.700,0:07:12.380
# 這兩個就比較白  我把內臟取一下 然後就把它架著
These two have whiter skins. I'm gonna remove the guts and then put them onto the frames,

0:07:12.960,0:07:14.160
# 把它插上來
pierce them through,

0:07:15.400,0:07:16.480
# 就直接烤啦
and then grill them right away.

0:07:26.640,0:07:27.440
# 放點鹽
Put some salt.

0:07:31.380,0:07:32.200
# 放點油
Put some oil.

0:07:36.060,0:07:37.500
# 再削點生薑下去
And then cut some ginger,

0:07:40.640,0:07:41.820
# 生薑去腥
to get rid of the bloody smell.

0:07:43.140,0:07:44.020
# 加點醬油
Put some soy sauce.

0:07:46.180,0:07:47.040
# 加點料酒
Put some cooking wine.

0:07:53.040,0:07:54.200
# 給它搓搓背
Give it a back massage.

0:07:55.380,0:07:56.160
# 按按腳
and a leg massage.

0:07:59.040,0:08:04.660
# 要用力點搓我  這樣味道才能  才能融入它的身體
I need to press it stronger, so that the flavour can be, can be fully integrated with its body.

0:08:06.900,0:08:09.440
# 好啦  腌製半個小時
Alright! Marinate it for half an hour.

0:08:21.360,0:08:23.300
# 你看  我找了幾根棍子過來哦
Look! I've found a couple of rods.

0:08:25.160,0:08:27.200
# 要用棍子給它  綁它一下
I gotta tie them up, with the rods.

0:08:28.260,0:08:29.060
# 這樣它就
Then they'll,

0:08:30.580,0:08:32.340
# 聽話一點  不會亂跑
they'll behave a bit better, instead of running around.

0:08:36.120,0:08:37.440
# 你看  已經綁好啦
Look! They're tied up now.

0:08:39.320,0:08:41.180
# 現在它們就聽話啦
They're gonna well behave now.

0:08:42.280,0:08:45.760
# 現在就會去烤  三個一起烤  哎呀  美味
I'm gonna grill them, all three together. Aya! Tasty!

0:08:54.440,0:08:57.540
# 我到對面那裡去  靠著河邊來
I go to the opposite over there, by the riverside.

0:08:58.380,0:09:00.540
# 到處都長了好多草  看見沒有
The weeds are growing everywhere. See?

0:10:42.260,0:10:43.300
# 先這樣烤一下
Grill it for a while here.

0:10:45.020,0:10:47.300
# 不然等下不知道烤不烤的熟 它炭太少
Otherwise, I wonder if we can ever make it done. We have too little charcoal.

0:11:19.340,0:11:20.460
# 搞點醬料
Get some sauce.

0:11:22.920,0:11:23.980
# 從頭刷到尾
Brush from head to tail.

0:11:25.660,0:11:26.820
# 它頭上也刷
And on the head too.

0:11:29.280,0:11:32.380
# 頭上翅肪上到處  好  轉一圈
One the head, one the wings. Everywhere. Alright! Turn it over.

0:11:34.760,0:11:39.380
# 來  給它洗洗澡  這個醬料很香哦  它很喜歡
Yup! Let me give it a bath. This sauce smells really good.  It likes the sauce very much.

0:11:43.120,0:11:46.540
# 你看這個  去非洲旅行一樣 曬的那麼黑
Look! This one seems to be back from the trip to Africa. It's so darkly tanned.

0:11:47.940,0:11:49.120
# 生出來就是這樣子
It's its inborn colour.

0:11:51.920,0:11:55.340
# 剛把它  把它毛褪掉的話一看到這個黑就這個
Once I, once I finished defeathering it, I already saw that it is so black.

0:11:56.180,0:12:00.140
# 所以不是我們搞(烤)的  本來就是那麼黑
So it's not because of us. It's not burnt. It has always been black.

0:13:33.280,0:13:36.760
# 哎呀  這裡有個小龍蝦哦   那麼大的小龍蝦
Aya! Here's a crayfish. It's such a big crayfish.

0:13:41.000,0:13:44.460
# 哇你看  這裡有隻那麼大的小龍蝦
Wa! Look! Here's such a big crayfish.

0:13:44.860,0:13:47.100
# 來  給它烤烤火  它可能冷了
C'mon! We've set a fire for it. Perhaps it feels very cold now.

0:13:53.760,0:13:56.800
# 要划一下  不划一下烤下熟
I need to slice it. Otherwise it would take forever.

0:14:14.980,0:14:16.160
# 嗯 差不多熟了
Um! It's almost done now.

0:14:26.860,0:14:28.040
# 搞點調料
Put some seasoning.

0:14:56.400,0:14:59.820
# 這昨天割出來的蜂蜜哦  很新鮮的哦
This is the honey harvested yesterday. It's really fresh, you know.

0:15:00.140,0:15:01.300
# 開始刷蜂蜜啦
Let's put on the honey.

0:15:02.560,0:15:04.140
# 現在蜂蜜多的很
Honey is now plentiful.

0:15:04.880,0:15:05.980
# 但是不能浪費哦
But wasting is never an option.

0:15:07.220,0:15:07.940
# 下面
Underneath,

0:15:09.820,0:15:10.800
# 下面接著
catch it underneath.

0:15:20.740,0:15:21.380
# 哇
Wa!

0:15:26.140,0:15:27.820
# 全身都裹著蜂蜜
The whole body is coated with honey.

0:15:28.320,0:15:29.620
# 這樣  這樣才好吃
That, that makes it a delicacy.

0:15:30.220,0:15:31.660
# 從頭上淋一兩下
Pour some above its head.

0:15:32.780,0:15:34.400
# 翅肪上也淋一下
And also on the wings

0:15:36.380,0:15:38.220
# 烤個兩分鐘就可以直接吃哦
Two more minutes. And then we can start eating right away.

0:15:41.080,0:15:42.540
# 好啦 準備開吃開吃
Alright! Ready, ready!

0:15:43.360,0:15:43.960
# 放這裡來
Put it here.

0:15:47.620,0:15:48.960
# 放在這裡就行啦
Just put it here. It's fine.

0:15:50.140,0:15:51.820
# 嘗一下 嘗一下味道怎麼樣
Let me have a try, have a try and see how it tastes.

0:15:52.260,0:15:53.080
# 我吃一個啊
I'll have one.

0:15:57.400,0:15:58.560
# 好香啊 吃這一個
It smells good! I'll have this one.

0:16:03.200,0:16:03.980
# 嗯~
Um~

0:16:06.100,0:16:07.060
# 好香啊
It smells really nice!

0:16:10.220,0:16:11.940
# 真的好好吃啊  不騙你們的
It tastes really good! No kidding!

0:16:16.180,0:16:17.880
# 你看  漂亮吧
Look! Isn't it pretty?

0:16:26.400,0:16:27.600
# 烤的酥酥的
It's crispy.

0:16:32.260,0:16:33.160
# 太好吃了
It's really fantastic!

0:16:36.180,0:16:40.340
# 來  哈吧  小哈吧 哈吧狗
Hey! Pug, puggy, pug!

0:16:53.300,0:16:54.440
# 來  吃骨頭
C'mon! The bone is yours.

0:16:56.840,0:16:58.600
# 這個烤鴿子好吃  這個烤鴿子
The grilled pigeon tastes really good, this grilled pigeon.

0:16:59.000,0:17:01.000
# 好久都沒吃過這麼好吃的東西了  (註︰好像很難照意思去完全翻譯而又不顯得突兀)
I've been longing for this kind of wonderful delicacy for a long time.

0:17:07.140,0:17:08.100
# 嗯 大胖狗
Um! Big Chubby!

0:17:09.300,0:17:10.400
# 嘿  別掉了哦
Hey! Don't drop it!

0:17:11.680,0:17:12.860
# 不能浪費食物
Never waste food!

0:17:15.480,0:17:17.420
# (娃哈哈) 我要搞個頭給它吃 (註︰字幕沒有寫，那黑白狗叫娃哈哈)
Wahaha, let me give him the head.

0:17:21.580,0:17:23.840
# 頭哦 包含好多營養的哦  (註︰其實我聽到︰「娃哈哈   好多營養的哦」)
It's head. It's very nutritious.

0:17:25.240,0:17:26.000
# 它搶不到
He lost to Big Cubby!

0:17:29.080,0:17:31.880
# 你看  這個鴿子加了蜂蜜  好好吃啊
Look! This pigehon, with honey, tastes really good.

0:17:32.780,0:17:33.600
# 甜甜的
It's kind of sweet.

0:17:35.340,0:17:37.420
# 蜜汁乳鴿哦  這樣搞
Honey grilled pigeon, so it's called.

0:17:39.520,0:17:41.560
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.

0:17:45.160,0:17:45.820
# 吃多兩口
I have a few more bites.

0:17:56.780,0:17:58.300
# 把那個火滅一下  回去啦
Let's put off the fire, and go back now.
