### ISSUE TITLE
[雪鱼] 济南牛肉烧饼 - https://youtu.be/QNw5lUeqFuc

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#1459]
**视频链接**：https://youtu.be/QNw5lUeqFuc

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
济南特色牛肉烧饼！热牛肉软烂，烧饼烫手，8元一个塞满肉能吃撑！

简介
“您还记得大明湖畔的夏雨荷吗”，是的，雪鱼又到了山东济南，来到济南最绕不开的美食就是牛肉烧饼！这烧饼就像西安的肉夹馍一样普遍！刚出炉的饼中间切开，把剁好的肉塞进去，满满的很厚实，拿在手里沉甸甸的感觉！一个单纯的烧饼是1.5元，夹上牛肉就是8元一个，牛肉是咸香味道，炖地软烂入味；烧饼都是从旁边炉子里直接拿出来的，很烫手，这热牛肉和热烧饼搭配一起，别提有多美啦。在济南，牛肉烧饼一般是作为早餐食用，一个就能吃饱，现在很多店铺也会营业到下午，一天都可以吃到。吃完牛肉烧饼，一定要来市区的大明湖散散步，呼吸一下新鲜空气～

字幕
1
00:00:01,840 --> 00:00:07,920
山东·济南

2
00:00:15,600 --> 00:00:17,040
我又在济南了

3
00:00:17,040 --> 00:00:20,400
这次来济南呢 是为了把自己的颌垫去掉

4
00:00:20,400 --> 00:00:23,080
颌垫去掉之后 当然要吃点好的了

5
00:00:23,080 --> 00:00:25,640
昨天我有个朋友发了很多的美食图片

6
00:00:25,640 --> 00:00:29,280
里面最吸引我的 最让我觉得馋的不是肉

7
00:00:29,280 --> 00:00:31,280
而是烧饼

8
00:00:31,280 --> 00:00:34,800
想想自己也是很长时间没有吃到烧饼火烧这些东西了

9
00:00:34,800 --> 00:00:36,480
今天中午去买点

10
00:00:36,480 --> 00:00:40,280
如果觉得好吃 就再给她捎一点回去

11
00:00:48,400 --> 00:00:50,400
店的门口已经坐了几桌来吃饭的人了

12
00:00:51,080 --> 00:00:53,400
进去看看吧

13
00:00:54,640 --> 00:00:58,700
（菜单）

14
00:01:17,160 --> 00:01:21,360
看我后面 这边来买牛肉烧饼的人好多

15
00:01:23,240 --> 00:01:27,440
关键是 现在还不到十一点 人就这么多了

16
00:01:27,520 --> 00:01:29,480
在哪儿交钱

17
00:01:29,480 --> 00:01:32,540
我要一个烧饼夹牛肉 和一碗牛肉汤

18
00:01:32,800 --> 00:01:34,080
在这儿吃？ 对

19
00:01:34,080 --> 00:01:37,720
18块钱

20
00:01:38,960 --> 00:01:42,840
这个牛肉 闻着就是挺香的

21
00:01:44,860 --> 00:01:46,860
（阿姨说一天得卖3锅牛肉）

22
00:01:54,540 --> 00:01:56,540
（阿姨说闻着就特别香）

23
00:02:16,740 --> 00:02:17,940
谢谢

24
00:02:19,700 --> 00:02:21,700
这是小碗的牛肉汤（10元）

25
00:02:22,220 --> 00:02:24,220
这个碗都是这么大的！

26
00:02:27,280 --> 00:02:29,280
牛肉烧饼也来了（8元）

27
00:02:38,760 --> 00:02:40,760
看这个头不小吧

28
00:02:41,440 --> 00:02:45,080
这一面全是芝麻 量多让人感动

29
00:02:45,080 --> 00:02:46,980
它肯定是怕我觉得它不够香

30
00:02:49,000 --> 00:02:52,740
我们打开烧饼 看一看里面的牛肉

31
00:02:52,740 --> 00:02:53,920
哇

32
00:02:55,620 --> 00:02:57,620
这个牛肉切的特别细

33
00:02:57,620 --> 00:02:59,460
我感觉是瘦肉多 肥肉少

34
00:02:59,460 --> 00:03:01,140
几乎看不到肥肉

35
00:03:04,620 --> 00:03:05,340
来一口吧

36
00:03:09,560 --> 00:03:10,420
好香阿

37
00:03:11,980 --> 00:03:16,620
这个烧饼是咸香味的 芝麻的味道特浓郁

38
00:03:18,940 --> 00:03:20,940
我用手撕一下它的外壳

39
00:03:21,780 --> 00:03:24,740
看看刚烤的烧饼是多么的酥脆

40
00:03:25,200 --> 00:03:27,200
芝麻都掉了好多

41
00:03:29,820 --> 00:03:31,820
里面是分层的

42
00:03:41,580 --> 00:03:47,460
因为加了足够的芝麻所以即使没有肉也很香

43
00:03:55,240 --> 00:04:00,920
透过窗户也能看到 它这个牛肉原来是放在汤里的

44
00:04:00,920 --> 00:04:03,440
现要呢 就是现捞出来 现剁出来

45
00:04:03,440 --> 00:04:05,960
就是切成这种小细末

46
00:04:06,800 --> 00:04:09,320
夹在里面

47
00:04:13,480 --> 00:04:17,280
肉多到就是感觉无从下口

48
00:04:18,200 --> 00:04:21,080
我看很多人都是直接来买牛肉

49
00:04:21,080 --> 00:04:23,000
有的人也是直接来买烧饼

50
00:04:23,000 --> 00:04:27,160
烧饼呢 一个人都能买四五个（这种都是带走的）

51
00:04:27,160 --> 00:04:29,600
这都是比较正常的

52
00:04:37,160 --> 00:04:41,280
它这个牛肉汤就会比较清淡

53
00:04:42,680 --> 00:04:47,600
这家小店离市区很远 但是很多人都是专门开车过来吃

54
00:04:47,600 --> 00:04:52,240
这边的火烧还有牛肉 主要就是价格比较合适

55
00:04:52,240 --> 00:04:56,600
一个呢 就是让你吃得饱饱的 味道也还不错

56
00:04:57,000 --> 00:05:01,960
在这边吃着饭 还能听到他们时不时传来的爽朗的笑声

57
00:05:01,960 --> 00:05:06,040
来 我们看一下火烧和牛肉 制作的场景

58
00:05:49,480 --> 00:05:57,000
大哥 
我看你这边找的大部分都是娘子军

59
00:05:58,000 --> 00:06:01,280
一进来一看
全是女的

60
00:06:05,960 --> 00:06:09,520
阿姨 这边早上起来是几点开门

61
00:06:09,520 --> 00:06:12,600
早上起来6点 6点开门

62
00:06:12,600 --> 00:06:16,400
您刚才说 一早上的顾客怎么了

63
00:06:16,400 --> 00:06:19,800
人不断 都是来吃火烧的

64
00:06:27,680 --> 00:06:30,760
大姨 这个还得称一下吗

65
00:06:30,760 --> 00:06:33,080
每一个大约是多重

66
00:06:33,080 --> 00:06:37,200
一两六 不超过一两六

67
00:06:49,640 --> 00:06:52,200
哦 是蘸了水

68
00:06:53,240 --> 00:06:57,760
蘸了水 才能把芝麻粘住

69
00:07:01,960 --> 00:07:06,920
现在已经开始上人了 看我后面 这边有

70
00:07:06,920 --> 00:07:07,680
1 2 3 4 5 6 7

71
00:07:07,680 --> 00:07:10,000
有七个人在忙碌

72
00:07:10,000 --> 00:07:14,240
就先不打扰他们了 我去买点火烧带走

73
00:07:28,160 --> 00:07:31,360
这是我买的火烧

74
00:07:31,680 --> 00:07:34,680
待会回去分一下

75
00:07:34,860 --> 00:07:37,380
她现在应该是上班的时候

76
00:07:37,380 --> 00:07:38,880
还没有理我 回复我消息

77
00:07:56,880 --> 00:08:00,960
关  注
雪 鱼  探 店


```

**Comment by shuaisoserious** [comment]
认领

**Comment by shuaisoserious** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
济南特色牛肉烧饼！热牛肉软烂，烧饼烫手，8元一个塞满肉能吃撑！
Beef Shaobing in Jinan
简介
“您还记得大明湖畔的夏雨荷吗”，是的，雪鱼又到了山东济南，来到济南最绕不开的美食就是牛肉烧饼！这烧饼就像西安的肉夹馍一样普遍！刚出炉的饼中间切开，把剁好的肉塞进去，满满的很厚实，拿在手里沉甸甸的感觉！一个单纯的烧饼是1.5元，夹上牛肉就是8元一个，牛肉是咸香味道，炖地软烂入味；烧饼都是从旁边炉子里直接拿出来的，很烫手，这热牛肉和热烧饼搭配一起，别提有多美啦。在济南，牛肉烧饼一般是作为早餐食用，一个就能吃饱，现在很多店铺也会营业到下午，一天都可以吃到。吃完牛肉烧饼，一定要来市区的大明湖散散步，呼吸一下新鲜空气～

字幕
1
00:00:01,840 --> 00:00:07,920
山东·济南
Jinan, Shandong
2
00:00:15,600 --> 00:00:17,040
我又在济南了
I’m in Jinan again
3
00:00:17,040 --> 00:00:20,400
这次来济南呢 是为了把自己的颌垫去掉
Because I’m here for take off my occlusal guards
4
00:00:20,400 --> 00:00:23,080
颌垫去掉之后 当然要吃点好的了
Of course I’m going to eat delicious food after take it off
5
00:00:23,080 --> 00:00:25,640
昨天我有个朋友发了很多的美食图片
My friend post a lot of delicious food picture yesterday 
6
00:00:25,640 --> 00:00:29,280
里面最吸引我的 最让我觉得馋的不是肉
Which attracts me the most is not meat
7
00:00:29,280 --> 00:00:31,280
而是烧饼
But Shaobing 
8
00:00:31,280 --> 00:00:34,800
想想自己也是很长时间没有吃到烧饼火烧这些东西了
consider of myself that i haven’t eat Shaobing or Huoshao for a very long time
9
00:00:34,800 --> 00:00:36,480
今天中午去买点
We will going to eat some this afternoon
10
00:00:36,480 --> 00:00:40,280
如果觉得好吃 就再给她捎一点回去
I will take some for her if it is delicious
11
00:00:48,400 --> 00:00:50,400
店的门口已经坐了几桌来吃饭的人了
There are a few tables of people sitting at the front door of restaurant already
12
00:00:51,080 --> 00:00:53,400
进去看看吧
Let’s take a look inside
13
00:00:54,640 --> 00:00:58,700
（菜单）
The menu
14
00:01:17,160 --> 00:01:21,360
看我后面 这边来买牛肉烧饼的人好多
Look behind me, there are a lot of people who come here to buy beef Shaobing
15
00:01:23,240 --> 00:01:27,440
关键是 现在还不到十一点 人就这么多了
The point is there are so many people are here already before 11 am
16
00:01:27,520 --> 00:01:29,480
在哪儿交钱
Where to pay?
17
00:01:29,480 --> 00:01:32,540
我要一个烧饼夹牛肉 和一碗牛肉汤
I want a beef Shaobing and a beef soup
18
00:01:32,800 --> 00:01:34,080
在这儿吃？ 对
Diner in? yeah
19
00:01:34,080 --> 00:01:37,720
18块钱
18 yuan
20
00:01:38,960 --> 00:01:42,840
这个牛肉 闻着就是挺香的
Beef smells very fragment
21
00:01:44,860 --> 00:01:46,860
（阿姨说一天得卖3锅牛肉）
(Auntie said they sell 3 pots of beef every day)
22
00:01:54,540 --> 00:01:56,540
（阿姨说闻着就特别香）
(Auntie said it smells very fragment)
23
00:02:16,740 --> 00:02:17,940
谢谢
Thank you
24
00:02:19,700 --> 00:02:21,700
这是小碗的牛肉汤（10元）
This is small beef soup(10 yuan)
25
00:02:22,220 --> 00:02:24,220
这个碗都是这么大的！
Look how large the bowl is
26
00:02:27,280 --> 00:02:29,280
牛肉烧饼也来了（8元）
Our beef shaobing 
27
00:02:38,760 --> 00:02:40,760
看这个头不小吧

28
00:02:41,440 --> 00:02:45,080
这一面全是芝麻 量多让人感动

29
00:02:45,080 --> 00:02:46,980
它肯定是怕我觉得它不够香

30
00:02:49,000 --> 00:02:52,740
我们打开烧饼 看一看里面的牛肉
Let’s open the Shaobing, and take a look at the beef inside
31
00:02:52,740 --> 00:02:53,920
哇
wow
32
00:02:55,620 --> 00:02:57,620
这个牛肉切的特别细
This beef slicing very thin
33
00:02:57,620 --> 00:02:59,460
我感觉是瘦肉多 肥肉少
I feel there is more lean beef but less fatty beef
34
00:02:59,460 --> 00:03:01,140
几乎看不到肥肉
Nearly no fatty
35
00:03:04,620 --> 00:03:05,340
来一口吧
Have a bite
36
00:03:09,560 --> 00:03:10,420
好香阿
So fragment
37
00:03:11,980 --> 00:03:16,620
这个烧饼是咸香味的 芝麻的味道特浓郁
The Shaobing are salty and fragment, and the sesame seeds are very fragment
38
00:03:18,940 --> 00:03:20,940
我用手撕一下它的外壳
I tear it’s shell up with my hands
39
00:03:21,780 --> 00:03:24,740
看看刚烤的烧饼是多么的酥脆
Look how crispy the Fresh baked Shaobing is
40
00:03:25,200 --> 00:03:27,200
芝麻都掉了好多
Many sesames are dropped
41
00:03:29,820 --> 00:03:31,820
里面是分层的
It’s layered inside
42
00:03:41,580 --> 00:03:47,460
因为加了足够的芝麻所以即使没有肉也很香
Because enough sesame is added, it tastes delicious even without meat
43
00:03:55,240 --> 00:04:00,920
透过窗户也能看到 它这个牛肉原来是放在汤里的
You can see it through the window. The beef was put in the soup
44
00:04:00,920 --> 00:04:03,440
现要呢 就是现捞出来 现剁出来
It will be chopped right after the order
45
00:04:03,440 --> 00:04:05,960
就是切成这种小细末
Just chopped into these small pieces
46
00:04:06,800 --> 00:04:09,320
夹在里面
Fold in Shaobing
47
00:04:13,480 --> 00:04:17,280
肉多到就是感觉无从下口
There is so much meat that I don’t know where to start
48
00:04:18,200 --> 00:04:21,080
我看很多人都是直接来买牛肉
I see many people come directly to buy beef
49
00:04:21,080 --> 00:04:23,000
有的人也是直接来买烧饼
Or Shaobing
50
00:04:23,000 --> 00:04:27,160
烧饼呢 一个人都能买四五个（这种都是带走的）
People can buy four or five usually(all these are taken out)
51
00:04:27,160 --> 00:04:29,600
这都是比较正常的
Which is regularly 
52
00:04:37,160 --> 00:04:41,280
它这个牛肉汤就会比较清淡
Its beef soup is light seasoning 
53
00:04:42,680 --> 00:04:47,600
这家小店离市区很远 但是很多人都是专门开车过来吃
This small restaurant is very far away from the city but many people drive here to eat
54
00:04:47,600 --> 00:04:52,240
这边的火烧还有牛肉 主要就是价格比较合适
Shaobing and beef are cost-effective
55
00:04:52,240 --> 00:04:56,600
一个呢 就是让你吃得饱饱的 味道也还不错
And it is enough to get you stuffed and with good taste
56
00:04:57,000 --> 00:05:01,960
在这边吃着饭 还能听到他们时不时传来的爽朗的笑声
you also can hear their laughter While eating here 
57
00:05:01,960 --> 00:05:06,040
来 我们看一下火烧和牛肉 制作的场景
Let’s check out how they make shaobing and beef
58
00:05:49,480 --> 00:05:57,000
大哥 
我看你这边找的大部分都是娘子军
Big brother, I noticed that all of your worker are female
59
00:05:58,000 --> 00:06:01,280
一进来一看
全是女的
I get inside and take a look, all female
60
00:06:05,960 --> 00:06:09,520
阿姨 这边早上起来是几点开门
Auntie, What time does it open in the morning?
61
00:06:09,520 --> 00:06:12,600
早上起来6点 6点开门
6 am in the morning
62
00:06:12,600 --> 00:06:16,400
您刚才说 一早上的顾客怎么了
What you just said about customers in the morning?
63
00:06:16,400 --> 00:06:19,800
人不断 都是来吃火烧的
They all come for Shaobing
64
00:06:27,680 --> 00:06:30,760
大姨 这个还得称一下吗
Auntie, do you have to weigh this?
65
00:06:30,760 --> 00:06:33,080
每一个大约是多重
What’s the weight of each one?
66
00:06:33,080 --> 00:06:37,200
一两六 不超过一两六
1.6 liang, no more than 1.6 liang(around 80 grams)
67
00:06:49,640 --> 00:06:52,200
哦 是蘸了水
Oh, with dipping of water
68
00:06:53,240 --> 00:06:57,760
蘸了水 才能把芝麻粘住
Dip in water to stick the sesame seeds
69
00:07:01,960 --> 00:07:06,920
现在已经开始上人了 看我后面 这边有
Customers are coming
70
00:07:06,920 --> 00:07:07,680
1 2 3 4 5 6 7
One two three four five six seven
71
00:07:07,680 --> 00:07:10,000
有七个人在忙碌
Seven people are busy to making food
72
00:07:10,000 --> 00:07:14,240
就先不打扰他们了 我去买点火烧带走
I won’t bother them for now,i go and take out some Shaobing
73
00:07:28,160 --> 00:07:31,360
这是我买的火烧
This is the Shaobing that i bought
74
00:07:31,680 --> 00:07:34,680
待会回去分一下
I'll go back and give it out later
75
00:07:34,860 --> 00:07:37,380
她现在应该是上班的时候
She should be at work right now
76
00:07:37,380 --> 00:07:38,880
还没有理我 回复我消息
Still not reply my message yet
77
00:07:56,880 --> 00:08:00,960
关  注
雪 鱼  探 店
Subscribe 
Xue yu

**Comment by shuaisoserious** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
济南特色牛肉烧饼！热牛肉软烂，烧饼烫手，8元一个塞满肉能吃撑！
Beef Shaobing in Jinan, hot and soft beef with hot Shaobing, get stuffed with 8 yuan Shaobing with full of beef inside
简介
“您还记得大明湖畔的夏雨荷吗”，是的，雪鱼又到了山东济南，来到济南最绕不开的美食就是牛肉烧饼！这烧饼就像西安的肉夹馍一样普遍！刚出炉的饼中间切开，把剁好的肉塞进去，满满的很厚实，拿在手里沉甸甸的感觉！一个单纯的烧饼是1.5元，夹上牛肉就是8元一个，牛肉是咸香味道，炖地软烂入味；烧饼都是从旁边炉子里直接拿出来的，很烫手，这热牛肉和热烧饼搭配一起，别提有多美啦。在济南，牛肉烧饼一般是作为早餐食用，一个就能吃饱，现在很多店铺也会营业到下午，一天都可以吃到。吃完牛肉烧饼，一定要来市区的大明湖散散步，呼吸一下新鲜空气～
"Do you remember Yuhe Xia in the Daming Lake?" Yes, Xueyu has arrived in Jinan, Shandong. The most delicious food in Jinan is beef Shaobing! This Shaobing is as common as Xi'an's Rou Jia Mo! Cut the fresh baked Shaobing in the middle and stuff the chopped meat in. It is full and thick, and it feels very heavy in your hand! A simple Shaobing is 1.5 yuan, and beef is 8 yuan a piece. The beef is salty and fragrant, and the stew is soft and delicious. The Shaobing is taken directly from the stove and is very hot. This hot beef is paired with hot Shaobing together, didn't mention how beautiful it is. In Jinan, beef Shaobing is generally eaten for breakfast, and one can be full. After eating beef Shaobing, be sure to take a walk in Daming Lake, in the city and breathe in the fresh air~
字幕
1
00:00:01,840 --> 00:00:07,920
山东·济南
Jinan, Shandong
2
00:00:15,600 --> 00:00:17,040
我又在济南了
I’m in Jinan again
3
00:00:17,040 --> 00:00:20,400
这次来济南呢 是为了把自己的颌垫去掉
Because I’m here for take off my occlusal guards
4
00:00:20,400 --> 00:00:23,080
颌垫去掉之后 当然要吃点好的了
Of course I’m going to eat delicious food after take it off
5
00:00:23,080 --> 00:00:25,640
昨天我有个朋友发了很多的美食图片
My friend post a lot of delicious food picture yesterday 
6
00:00:25,640 --> 00:00:29,280
里面最吸引我的 最让我觉得馋的不是肉
Which attracts me the most is not meat
7
00:00:29,280 --> 00:00:31,280
而是烧饼
But Shaobing 
8
00:00:31,280 --> 00:00:34,800
想想自己也是很长时间没有吃到烧饼火烧这些东西了
consider of myself that i haven’t eat Shaobing or Huoshao for a very long time
9
00:00:34,800 --> 00:00:36,480
今天中午去买点
We will going to eat some this afternoon
10
00:00:36,480 --> 00:00:40,280
如果觉得好吃 就再给她捎一点回去
I will take some for her if it is delicious
11
00:00:48,400 --> 00:00:50,400
店的门口已经坐了几桌来吃饭的人了
There are a few tables of people sitting at the front door of restaurant already
12
00:00:51,080 --> 00:00:53,400
进去看看吧
Let’s take a look inside
13
00:00:54,640 --> 00:00:58,700
（菜单）
The menu
14
00:01:17,160 --> 00:01:21,360
看我后面 这边来买牛肉烧饼的人好多
Look behind me, there are a lot of people who come here to buy beef Shaobing
15
00:01:23,240 --> 00:01:27,440
关键是 现在还不到十一点 人就这么多了
The point is there are so many people are here already before 11 am
16
00:01:27,520 --> 00:01:29,480
在哪儿交钱
Where to pay?
17
00:01:29,480 --> 00:01:32,540
我要一个烧饼夹牛肉 和一碗牛肉汤
I want a beef Shaobing and a beef soup
18
00:01:32,800 --> 00:01:34,080
在这儿吃？ 对
Diner in? yeah
19
00:01:34,080 --> 00:01:37,720
18块钱
18 yuan
20
00:01:38,960 --> 00:01:42,840
这个牛肉 闻着就是挺香的
Beef smells very fragment
21
00:01:44,860 --> 00:01:46,860
（阿姨说一天得卖3锅牛肉）
(Auntie said they sell 3 pots of beef every day)
22
00:01:54,540 --> 00:01:56,540
（阿姨说闻着就特别香）
(Auntie said it smells very fragment)
23
00:02:16,740 --> 00:02:17,940
谢谢
Thank you
24
00:02:19,700 --> 00:02:21,700
这是小碗的牛肉汤（10元）
This is small beef soup(10 yuan)
25
00:02:22,220 --> 00:02:24,220
这个碗都是这么大的！
Look how large the bowl is
26
00:02:27,280 --> 00:02:29,280
牛肉烧饼也来了（8元）
Our beef shaobing 
27
00:02:38,760 --> 00:02:40,760
看这个头不小吧

28
00:02:41,440 --> 00:02:45,080
这一面全是芝麻 量多让人感动

29
00:02:45,080 --> 00:02:46,980
它肯定是怕我觉得它不够香

30
00:02:49,000 --> 00:02:52,740
我们打开烧饼 看一看里面的牛肉
Let’s open the Shaobing, and take a look at the beef inside
31
00:02:52,740 --> 00:02:53,920
哇
wow
32
00:02:55,620 --> 00:02:57,620
这个牛肉切的特别细
This beef slicing very thin
33
00:02:57,620 --> 00:02:59,460
我感觉是瘦肉多 肥肉少
I feel there is more lean beef but less fatty beef
34
00:02:59,460 --> 00:03:01,140
几乎看不到肥肉
Nearly no fatty
35
00:03:04,620 --> 00:03:05,340
来一口吧
Have a bite
36
00:03:09,560 --> 00:03:10,420
好香阿
So fragment
37
00:03:11,980 --> 00:03:16,620
这个烧饼是咸香味的 芝麻的味道特浓郁
The Shaobing are salty and fragment, and the sesame seeds are very fragment
38
00:03:18,940 --> 00:03:20,940
我用手撕一下它的外壳
I tear it’s shell up with my hands
39
00:03:21,780 --> 00:03:24,740
看看刚烤的烧饼是多么的酥脆
Look how crispy the Fresh baked Shaobing is
40
00:03:25,200 --> 00:03:27,200
芝麻都掉了好多
Many sesames are dropped
41
00:03:29,820 --> 00:03:31,820
里面是分层的
It’s layered inside
42
00:03:41,580 --> 00:03:47,460
因为加了足够的芝麻所以即使没有肉也很香
Because enough sesame is added, it tastes delicious even without meat
43
00:03:55,240 --> 00:04:00,920
透过窗户也能看到 它这个牛肉原来是放在汤里的
You can see it through the window. The beef was put in the soup
44
00:04:00,920 --> 00:04:03,440
现要呢 就是现捞出来 现剁出来
It will be chopped right after the order
45
00:04:03,440 --> 00:04:05,960
就是切成这种小细末
Just chopped into these small pieces
46
00:04:06,800 --> 00:04:09,320
夹在里面
Fold in Shaobing
47
00:04:13,480 --> 00:04:17,280
肉多到就是感觉无从下口
There is so much meat that I don’t know where to start
48
00:04:18,200 --> 00:04:21,080
我看很多人都是直接来买牛肉
I see many people come directly to buy beef
49
00:04:21,080 --> 00:04:23,000
有的人也是直接来买烧饼
Or Shaobing
50
00:04:23,000 --> 00:04:27,160
烧饼呢 一个人都能买四五个（这种都是带走的）
People can buy four or five usually(all these are taken out)
51
00:04:27,160 --> 00:04:29,600
这都是比较正常的
Which is regularly 
52
00:04:37,160 --> 00:04:41,280
它这个牛肉汤就会比较清淡
Its beef soup is light seasoning 
53
00:04:42,680 --> 00:04:47,600
这家小店离市区很远 但是很多人都是专门开车过来吃
This small restaurant is very far away from the city but many people drive here to eat
54
00:04:47,600 --> 00:04:52,240
这边的火烧还有牛肉 主要就是价格比较合适
Shaobing and beef are cost-effective
55
00:04:52,240 --> 00:04:56,600
一个呢 就是让你吃得饱饱的 味道也还不错
And it is enough to get you stuffed and with good taste
56
00:04:57,000 --> 00:05:01,960
在这边吃着饭 还能听到他们时不时传来的爽朗的笑声
you also can hear their laughter While eating here 
57
00:05:01,960 --> 00:05:06,040
来 我们看一下火烧和牛肉 制作的场景
Let’s check out how they make shaobing and beef
58
00:05:49,480 --> 00:05:57,000
大哥 
我看你这边找的大部分都是娘子军
Big brother, I noticed that all of your worker are female
59
00:05:58,000 --> 00:06:01,280
一进来一看
全是女的
I get inside and take a look, all female
60
00:06:05,960 --> 00:06:09,520
阿姨 这边早上起来是几点开门
Auntie, What time does it open in the morning?
61
00:06:09,520 --> 00:06:12,600
早上起来6点 6点开门
6 am in the morning
62
00:06:12,600 --> 00:06:16,400
您刚才说 一早上的顾客怎么了
What you just said about customers in the morning?
63
00:06:16,400 --> 00:06:19,800
人不断 都是来吃火烧的
They all come for Shaobing
64
00:06:27,680 --> 00:06:30,760
大姨 这个还得称一下吗
Auntie, do you have to weigh this?
65
00:06:30,760 --> 00:06:33,080
每一个大约是多重
What’s the weight of each one?
66
00:06:33,080 --> 00:06:37,200
一两六 不超过一两六
1.6 liang, no more than 1.6 liang(around 80 grams)
67
00:06:49,640 --> 00:06:52,200
哦 是蘸了水
Oh, with dipping of water
68
00:06:53,240 --> 00:06:57,760
蘸了水 才能把芝麻粘住
Dip in water to stick the sesame seeds
69
00:07:01,960 --> 00:07:06,920
现在已经开始上人了 看我后面 这边有
Customers are coming
70
00:07:06,920 --> 00:07:07,680
1 2 3 4 5 6 7
One two three four five six seven
71
00:07:07,680 --> 00:07:10,000
有七个人在忙碌
Seven people are busy to making food
72
00:07:10,000 --> 00:07:14,240
就先不打扰他们了 我去买点火烧带走
I won’t bother them for now,i go and take out some Shaobing
73
00:07:28,160 --> 00:07:31,360
这是我买的火烧
This is the Shaobing that i bought
74
00:07:31,680 --> 00:07:34,680
待会回去分一下
I'll go back and give it out later
75
00:07:34,860 --> 00:07:37,380
她现在应该是上班的时候
She should be at work right now
76
00:07:37,380 --> 00:07:38,880
还没有理我 回复我消息
Still not reply my message yet
77
00:07:56,880 --> 00:08:00,960
关  注
雪 鱼  探 店
Subscribe 
Xue yu
