### ISSUE TITLE
【美食作家王刚】珊瑚鱼的小细节 - https://youtu.be/PnCvJHhGc7s

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1461]
**视频链接**：https://youtu.be/PnCvJHhGc7s

视频时长4:55，预计发布时间为北京时间9月9日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
美食作家王刚教徒弟的日常记录之：做珊瑚鱼需要注意哪些小细节

简介
珊瑚鱼视频发布之后也陆续看到不少朋友尝试，不过多少还是有很多问题。这期视频手把手再教徒弟一遍，也再次给大家展示一些小细节，希望对以后尝试的朋友有帮助。

字幕
0:00:00.000,0:00:05.280
这道菜自从我们更了教学之后很多人都去做

0:00:05.440,0:00:06.877
但是我看了一下

0:00:07.256,0:00:09.640
目前为止没有哪个说做得很好

0:00:10.023,0:00:12.990
都是做得要么就是珊瑚短了

0:00:12.990,0:00:14.150
要么就是歪了

0:00:14.371,0:00:16.240
如果说要把这个珊瑚切条

0:00:16.411,0:00:18.630
这上面这片必定要把它切长

0:00:18.800,0:00:19.920
切这么长就够了

0:00:20.205,0:00:23.038
所以在这个地方下刀是比较适合的

0:00:25.328,0:00:27.525
而且这个不能切太薄知道吧

0:00:27.525,0:00:28.853
鱼片切薄了

0:00:29.090,0:00:32.440
你等一下你腌味上粉的时候

0:00:32.440,0:00:33.476
一下就断了

0:00:34.160,0:00:35.460
好 继续

0:00:39.224,0:00:40.264
看 出来了

0:00:40.553,0:00:43.100
我们可以边看这个

0:00:43.361,0:00:45.678
然后拿起来看一下行了 赶紧停下来

0:00:45.678,0:00:47.278
不要再切了再切就断了

0:00:47.484,0:00:50.798
其实做菜一定要对自己有信心

0:00:54.530,0:00:55.511
从第一片开始

0:00:59.624,0:01:01.586
如果你们第一次切的话

0:01:02.693,0:01:08.569
这个鱼片下来放在冰箱平放

0:01:08.569,0:01:12.171
下面应该是平放 放冰箱冻40分钟

0:01:12.171,0:01:14.133
成不成功就看这个鱼片

0:01:15.636,0:01:18.392
这个鱼啊我们切出来之后一定要去洗一下

0:01:18.622,0:01:20.448
因为这个鱼是新鲜的鱼

0:01:20.680,0:01:25.000
它肯定是会有一些血沫啊

0:01:26.133,0:01:27.962
轻轻挤一下 轻轻捏一下 

0:01:28.356,0:01:30.434
用力一捏这个鱼就废了

0:01:34.533,0:01:36.879
有一点就行 它主要起到一个效果就行了

0:01:39.165,0:01:41.119
淀粉一定要慢慢的加

0:01:41.706,0:01:43.110
不要一下子倒进去

0:01:43.608,0:01:45.513
因为淀粉加到它够了就行了

0:01:45.947,0:01:46.465
知道吧

0:01:46.623,0:01:47.546
加多了没用

0:01:47.668,0:01:49.270
你加多的话全都是浪费

0:01:51.849,0:01:53.172
我们加的时候啊

0:01:53.307,0:01:55.338
一定要注意这种地方

0:01:55.650,0:01:57.849
这种地方如果没有抹到位的话

0:01:58.130,0:02:01.307
那么它炸的时候首先这里会发干

0:02:01.950,0:02:04.307
然后就是会偏 知道吧

0:02:04.870,0:02:07.508
（酱汁）酸甜我们先放这个

0:02:10.352,0:02:11.390
4勺白醋

0:02:12.053,0:02:14.868
番茄酱是甜的 它是甜重于酸

0:02:15.090,0:02:18.078
所以我们白糖一定要适量一点

0:02:18.557,0:02:19.816
两勺半就够了

0:02:20.323,0:02:21.747
然后要放一点点盐

0:02:22.132,0:02:25.620
盐放进去是为了中和酸甜味

0:02:25.870,0:02:28.870
把这两个酸跟甜就

0:02:29.050,0:02:31.256
（不加盐）让人一吃不是酸就是甜

0:02:31.599,0:02:34.020
这个加上去的话它是把它们两个

0:02:34.256,0:02:35.279
融合在一起

0:02:35.279,0:02:36.844
把它们两个往中间靠一点

0:02:37.184,0:02:40.226
好 搅好了就开始操作了

0:02:40.226,0:02:42.946
你们在旁边看 我在那里做

0:03:12.056,0:03:13.798
 然后我们出了菜之后

0:03:14.299,0:03:16.480
先不要太着急上菜

0:03:16.480,0:03:17.200
为什么呢

0:03:17.353,0:03:22.240
因为这个鱼炸硬了之后摆起来不是那么好看

0:03:22.240,0:03:26.240
我们在淋汁30秒钟之后还有一次机会

0:03:26.974,0:03:29.524
还有一次机会把它摆起来

0:03:29.552,0:03:30.393
看一下啊

0:03:31.344,0:03:33.839
刚刚不够立的 现在我们把它立起来摆

0:03:34.760,0:03:37.078
因为它有这个汁水支撑住了 

0:03:37.243,0:03:38.404
它就可以立得起来

0:03:38.746,0:03:43.349
这个时候我们把这个造型摆起来 再上菜的话你可以看

0:03:43.818,0:03:48.835
我随便掐一根 这个我随便掐一根然后蘸点汁

0:03:52.212,0:03:53.742
看到没有 一样是脆的

0:03:54.817,0:03:55.575
听到响吗

0:03:55.575,0:03:56.154
嗯

0:03:58.070,0:04:00.207
来 试一下吧 直接用手就行

0:04:00.440,0:04:01.861
不用那么讲究

0:04:02.360,0:04:05.141
吃下这个味道和这个脆度

0:04:09.511,0:04:12.350
这个汁一淋上去 它虽然说挂在表面

0:04:12.701,0:04:14.487
但是它浸不进去

0:04:14.701,0:04:18.901
浸不进去的话它中间仍然是脆的 知道吧

0:04:20.868,0:04:21.695
嗯 好吃

0:04:22.205,0:04:22.963
试一下

0:04:23.198,0:04:24.179
我觉得好好吃啊

0:04:24.179,0:04:26.901
油的话 我们后面放的那个油

0:04:26.901,0:04:29.101
边上肯定是要有一层油

0:04:29.141,0:04:30.581
但这边肯定是多了

0:04:30.581,0:04:34.679
看这边 比这边再多一点点就可以了

0:04:34.901,0:04:36.685
油也不能太多 知道吧

0:04:36.968,0:04:39.807
好了 剩下的这两条鱼交作业

0:04:39.807,0:04:40.413
这一条

0:04:41.833,0:04:42.922
给其它同事吃

0:04:44.190,0:04:45.936
好 下课


```

**Comment by AudreyTao-star** [comment]
认领

**Comment by AudreyTao-star** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
美食作家王刚教徒弟的日常记录之：做珊瑚鱼需要注意哪些小细节
Wang Gang’s Daily Record Making Detail of Coral-Fish
简介
珊瑚鱼视频发布之后也陆续看到不少朋友尝试，不过多少还是有很多问题。这期视频手把手再教徒弟一遍，也再次给大家展示一些小细节，希望对以后尝试的朋友有帮助。
There are many problem that some people are tried to make the dish, after coral-fish of video , so Wang Gang show you it cooked detail again. Wish can help everyone.
字幕
0:00:00.000,0:00:05.280
这道菜自从我们更了教学之后很多人都去做
My students cooked coral-fish,
0:00:05.440,0:00:06.877
但是我看了一下
I check on it ,
0:00:07.256,0:00:09.640
目前为止没有哪个说做得很好
There is no one who cooked well so far.
0:00:10.023,0:00:12.990
都是做得要么就是珊瑚短了
Either coral-fish was made too short,
0:00:12.990,0:00:14.150
要么就是歪了
Or skew.
0:00:14.371,0:00:16.240
如果说要把这个珊瑚切条
If we slice it into,
0:00:16.411,0:00:18.630
这上面这片必定要把它切长
The piece will be cut long slices into.
0:00:18.800,0:00:19.920
切这么长就够了
look! the length is enough.
0:00:20.205,0:00:23.038
所以在这个地方下刀是比较适合的
so, It’s good that coral-fish is sliced in there here and 
0:00:25.328,0:00:27.525
而且这个不能切太薄知道吧
don’t cut it into too thin in slant-cut!
0:00:27.525,0:00:28.853
鱼片切薄了
If we slice too thin fillet,
0:00:29.090,0:00:32.440
你等一下你腌味上粉的时候
it will crack right off.
0:00:32.440,0:00:33.476
一下就断了
when you marinate and add starch for it, you will know.
0:00:34.160,0:00:35.460
好 继续
ok,go on .
0:00:39.224,0:00:40.264
看 出来了
look!
0:00:40.553,0:00:43.100
我们可以边看这个
were should have checked it on , when we are making it, 0:00:43.361,0:00:45.678
然后拿起来看一下行了 赶紧停下来 
then, we should stop in a proper range.
0:00:45.678,0:00:47.278
不要再切了再切就断了
Don’t cut it into deep part fracturing.
0:00:47.484,0:00:50.798
其实做菜一定要对自己有信心
actually, cooking dishes must be confident for oneself.
0:00:54.530,0:00:55.511
从第一片开始
Supposing you firstly cut it into slices, 
0:00:59.624,0:01:01.586
如果你们第一次切的话
starting from slice,
0:01:02.693,0:01:08.569
这个鱼片下来放在冰箱平放
The fillets can be put refrigerator flatwise
0:01:08.569,0:01:12.171
下面应该是平放 放冰箱冻40分钟
to freeze for 40 minutes.
0:01:12.171,0:01:14.133
成不成功就看这个鱼片
It’s key that the dish whether is success or not.
0:01:15.636,0:01:18.392
这个鱼啊我们切出来之后一定要去洗一下
fillets cut must be washed as 
0:01:18.622,0:01:20.448
因为这个鱼是新鲜的鱼
it’s fresh and
0:01:20.680,0:01:25.000
它肯定是会有一些血沫啊
has some scum.
0:01:26.133,0:01:27.962
轻轻挤一下 轻轻捏一下 
Squeezing gently.
0:01:28.356,0:01:30.434
用力一捏这个鱼就废了
don’t squeeze violently.
0:01:34.533,0:01:36.879
有一点就行 它主要起到一个效果就行了
just to put a little bit, it’s ok.
0:01:39.165,0:01:41.119
淀粉一定要慢慢的加
we don’t need to put starch into very fast . 
0:01:41.706,0:01:43.110
不要一下子倒进去
please,slowly,as fillet just need for fitting slurry.
0:01:43.608,0:01:45.513
因为淀粉加到它够了就行了

0:01:45.947,0:01:46.465
知道吧
you know?
0:01:46.623,0:01:47.546
加多了没用
it’s useless that you add so much
0:01:47.668,0:01:49.270
你加多的话全都是浪费
yes, that’s wasteful.
0:01:51.849,0:01:53.172
我们加的时候啊
Be careful the way that 
0:01:53.307,0:01:55.338
一定要注意这种地方
is used.
0:01:55.650,0:01:57.849
这种地方如果没有抹到位的话
providing that it hasn’t spread evenly,
0:01:58.130,0:02:01.307
那么它炸的时候首先这里会发干
firstly , it will dry out when we have fried deep and flat, and

0:02:01.950,0:02:04.307
然后就是会偏 知道吧
flat, do you know?
0:02:04.870,0:02:07.508
（酱汁）酸甜我们先放这个
We should firstly sauces that are sour and sweet.
0:02:10.352,0:02:11.390
4勺白醋
Add four teaspoons of white vinegar.
0:02:12.053,0:02:14.868
番茄酱是甜的 它是甜重于酸
the catchup is sweet more than sour.
0:02:15.090,0:02:18.078
所以我们白糖一定要适量一点
so when add white sugars that two and a half spoon is enough,      0:02:18.557,0:02:19.816
两勺半就够了
be careful, fit.
0:02:20.323,0:02:21.747
然后要放一点点盐
put bit salt into
0:02:22.132,0:02:25.620
盐放进去是为了中和酸甜味
to neutralize sweet and sour taste.
0:02:25.870,0:02:28.870
把这两个酸跟甜就
Both that are distinguished very easy by people
0:02:29.050,0:02:31.256
（不加盐）让人一吃不是酸就是甜
are  whether sweet or sour. 
0:02:31.599,0:02:34.020
这个加上去的话它是把它们两个
But we add some salt in coral-fish....
0:02:34.256,0:02:35.279
融合在一起
help it mix together.
0:02:35.279,0:02:36.844
把它们两个往中间靠一点
yes, neutralize sweet and sour taste.
0:02:37.184,0:02:40.226
好 搅好了就开始操作了
ok, we can start cooking, string over.
0:02:40.226,0:02:42.946
你们在旁边看 我在那里做
I’m to do here, you learning in side.
0:03:12.056,0:03:13.798
 然后我们出了菜之后
After three dish is cooked ,we don’t worry to serve dish.
0:03:14.299,0:03:16.480
先不要太着急上菜
0:03:16.480,0:03:17.200
为什么呢
what’s reason?
0:03:17.353,0:03:22.240
因为这个鱼炸硬了之后摆起来不是那么好看
Because surface of fillets fried stiff looks like not very well.
0:03:22.240,0:03:26.240
我们在淋汁30秒钟之后还有一次机会
But we that still have chance tide the shape of dish up
0:03:26.974,0:03:29.524
还有一次机会把它摆起来
cover sauces after 39 second.
0:03:29.552,0:03:30.393
看一下啊
Look! 
0:03:31.344,0:03:33.839
刚刚不够立的 现在我们把它立起来摆
fillets just haven’t rose deficiency, now , we are making it stand
0:03:34.760,0:03:37.078
因为它有这个汁水支撑住了 
now that it is hold up by using sauces.
0:03:37.243,0:03:38.404
它就可以立得起来
So that fillets can be stood.
0:03:38.746,0:03:43.349
这个时候我们把这个造型摆起来 再上菜的话你可以看
You can see that they are rose.
0:03:43.818,0:03:48.835
我随便掐一根 这个我随便掐一根然后蘸点汁
I nips off a strip of coral-fish at random, pouring sauces.
0:03:52.212,0:03:53.742
看到没有 一样是脆的
do you hear? It’s Crip.
0:03:54.817,0:03:55.575
听到响吗
hear it?
0:03:55.575,0:03:56.154
嗯
Uh-huh
0:03:58.070,0:04:00.207
来 试一下吧 直接用手就行
come! Try to it by your hands directly.
0:04:00.440,0:04:01.861
不用那么讲究
Don’t care yourself fastidiously.
0:04:02.360,0:04:05.141
吃下这个味道和这个脆度
the sauce that is poured on fillets 
0:04:09.511,0:04:12.350
这个汁一淋上去 它虽然说挂在表面
hasn’t dip into coral-fish,
0:04:12.701,0:04:14.487
但是它浸不进去
but on the surface.
0:04:14.701,0:04:18.901
浸不进去的话它中间仍然是脆的 知道吧
So , it is still crisp , do you know now?
0:04:20.868,0:04:21.695
嗯 好吃
Uh-huh, delicious.
0:04:22.205,0:04:22.963
试一下
Try to it again!
0:04:23.198,0:04:24.179
我觉得好好吃啊
I feel so good.
0:04:24.179,0:04:26.901
油的话 我们后面放的那个油
next time, we can add other oil.
0:04:26.901,0:04:29.101
边上肯定是要有一层油
there must be some oil in side,
0:04:29.141,0:04:30.581
但这边肯定是多了
but it is more oil .
0:04:30.581,0:04:34.679
看这边 比这边再多一点点就可以了
Look!e should add a little bit more oil on the other side.
0:04:34.901,0:04:36.685
油也不能太多 知道吧
we can’t put into cooking oil so much , do you know?
0:04:36.968,0:04:39.807
好了 剩下的这两条鱼交作业
Ok, the rest of two grass carps is homework.
0:04:39.807,0:04:40.413
这一条
which one
0:04:41.833,0:04:42.922
给其它同事吃
gives other colleagues.
0:04:44.190,0:04:45.936
好 下课
Ok, dismiss!
