### ISSUE TITLE
[华农兄弟] 华农兄弟放几个地笼装点螃蟹来吃顺便摘点板栗 - https://youtu.be/gVUnRKdAbdg

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1464]
https://youtu.be/gVUnRKdAbdg
<p>&#35270;&#39057;&#21457;&#24067;&#20110; September 8, 2020 at 11:31AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/gVUnRKdAbdg

#华农兄弟：放几个地笼，装点螃蟹来吃，顺便摘点板栗
#Huanong Brothers: Put some traps to catch some crabs. Then pick some chestnuts on the way.

0:00:00.260,0:00:02.360
# 去河裡面搞點螃蟹來吃哦
We're going to the riverside and catch some crabs.

0:00:03.360,0:00:05.140
# 你看這個是找兄弟借的
Look! These traps are borrowed from my,

0:00:06.140,0:00:07.280
# 找兄弟借的籠子
from my buddy.

0:00:09.500,0:00:12.160
# 把這個餌料放到放個地籠裡面去
Put the bait into the traps.

0:00:27.800,0:00:31.000
# 把這個籠子丟到河邊去 就有螃蟹會進來了
Drop the traps at the riverside and the crabs will be coming in.

0:00:54.140,0:00:55.680
# 好多魚呀這邊
A lot of fish here!

0:00:57.500,0:00:59.540
# 我要抓螃蟹 不要魚
But I want crabs, not fish.

0:00:59.900,0:01:00.940
# 把這個扔到這裡去
Let me drop this one here.

0:01:02.020,0:01:03.500
# 很多螃蟹的哦這裡
Here are a lot of crabs, you know.

0:01:04.520,0:01:07.380
# 一到  一到晚上很好螃蟹都出來活動
Once, once it gets dark, a lot of crabs will be coming out.

0:01:20.960,0:01:22.100
# 這裡可以放一個
One can be placed here.

0:01:23.060,0:01:23.580
# 哎呀
Aya!

0:01:28.200,0:01:29.800
# 
Look! Another one can be placed here, here.

0:01:34.460,0:01:35.680
# 你看 這裡可以放一個哦  這裡
Hang it onto the tree.

0:01:37.320,0:01:38.240
# 掛在這樹上
Then it won’t be blown away.

0:01:46.320,0:01:48.860
# 風就吹不走
Wa! Look! A crab is getting in very soon.

0:01:50.100,0:01:51.940
# 哇  你看有一個螃蟹  馬就就進去了
See? It’s coming here in a moment.

0:01:53.000,0:01:54.060
# 看到沒有  等下它就過來了
Here are a lot of small fish.

0:01:55.280,0:01:59.940
# 好多小魚啊這裡
Look! The crab, it’s searching around the trap. It doesn’t know where the entrance is.

0:02:01.460,0:02:05.360
# 你看  那個螃蟹  它在翻那個籠子   它不知道從哪裡進
It’s over there. How can you get the food otherwise? Eh? It’s going there now.

0:02:06.760,0:02:10.200
# 在那邊啊  不然怎麼吃的到哦  誒它馬上過去啦
Let’s see if it can reach that side. Aya! This crab is so clever.

0:02:10.940,0:02:11.900
# 看它能不能游過去 誒呀  好聰明吲這個螃蟹
It will get in right away.

0:02:15.380,0:02:18.160
# 馬上就進去啦
Almost there! Eh? It’s going back here.

0:02:19.100,0:02:19.960
# 再往前一點  誒  又倒回來啦
Stupid crab!

0:02:21.280,0:02:23.480
# 那麼笨
The function is right in the front. Go a bit further to the front!

0:02:26.480,0:02:29.380
# 前面就是路口啦  再往前走一點啊
It’s just crawling around, but never gets in.

0:02:30.940,0:02:33.080
# 它愣是不進  還老是爬來爬去
Go that side. A tiny little bit more, just a tiny little bit more!

0:02:36.020,0:02:37.040
# 過去  再爬過一點點  再一點點
Go a bit further!

0:02:38.240,0:02:38.980
# 再過來一點
It’s not going.

0:02:43.460,0:02:44.340
# 不過去
Place one here.

0:02:44.980,0:02:46.120
# 這裡放一個
Here must be something.

0:02:48.720,0:02:50.120
# 這裡肯定有東西
It’s really dangerous here.
DO NOT IMITATE

0:02:50.120,0:02:51.560
# 請勿模仿  (註︰警告字句)
DO NOT IMITATE

0:02:59.320,0:03:00.440
# 這裡好危險哦
Drop one here.

0:03:03.300,0:03:04.960
# 這個放在這裡
I’ll drop another one up there.

0:03:35.920,0:03:36.860
# 上面再放一個
This one can be dropped here.

0:03:39.980,0:03:42.840
# 這個就放在這裡
All traps have now been placed. We’ll come to get them back tomorrow.

0:03:43.220,0:03:45.040
# 現在放好啦  明天過來收
Let’s see if there are any good snacks up there,

0:03:45.740,0:03:47.020
# 我去看一下上面有沒有好吃的
something like wild fruits.

0:03:47.680,0:03:49.720
# 野果啊之類的
It's really a scenic spot here.

0:04:03.280,0:04:05.780
# 這裡的風景很漂亮的哦
Look! It’s like beans. Who knows what it is.

0:04:06.180,0:04:07.520
# 你看  扁豆一樣的  不知道甚麼
I don’t think it’s edible.

0:04:08.820,0:04:09.960
# 應該是不能吃的哦
It has beans, you know.

0:04:14.000,0:04:15.140
# 有豆子的哦
There are beans inside.

0:04:16.180,0:04:17.520
# 裡面有豆子
But I have no ideas what plant it is.

0:04:43.780,0:04:45.360
# 我也不知道甚麼植物
Look! It’s really a scenic place, isn’t it?

0:04:46.200,0:04:49.400
# 你看  這裡的環境很漂亮吧
All are, this is, this is, the headwater of our village, this one.

0:04:49.580,0:04:50.600
# 全是 就是  就是  我們家鄉的水源哦  這個
This is the headwater.

0:04:56.520,0:04:57.860
# 這就是水源地
Look! These two,

0:04:58.300,0:05:00.200
# 你看  這兩個
tiny plums. They're so small.

0:05:01.080,0:05:02.400
# 小布丁  那麼小的
Are there any larger ones?

0:05:03.300,0:05:06.320
# 沒有大一點的
It’s now on my wish list. I’ll come and pick them right away next time.

0:05:07.280,0:05:09.320
# 先看好來  不次直接來摘
That’s so called “no frills”.

0:05:14.900,0:05:18.020
# 大家常說的直奔主題
Look! This tree is really big. It’s at least a hundred years old.

0:05:19.640,0:05:21.860
# 你看  這棵樹好大哦  最少有上百年的歷史哦
There are a couple of tree hollows. In the hollows, there must be,

0:05:22.400,0:05:24.940
# 還有幾個樹洞 榼洞裡面肯定有
either, either birds, or snakes.

0:05:34.320,0:05:35.920
# 要不是  要不就是鳥  要不就是蛇
Well, the path is blocked

0:05:49.280,0:05:51.140
# 好  路都被擋了
Look! This is shameplant.

0:05:51.720,0:05:53.680
# 你看  這個是含羞草哦
Look! It will shrink immediately if I blow to it.

0:05:56.220,0:05:58.140
# 沒反應  這個草肯定不要臉
No response. This plant must be shameless.

0:05:59.740,0:06:02.740
# 還含羞草  肯定是冒牌貨
How can it call itself shameplant? It’s counterfeit.

0:06:17.860,0:06:20.760
# 你看  這個  野果那些都還沒熟哦
Look! The, the wild fruits are not yet ripe.

0:06:20.760,0:06:22.540
# 我摘點這個蕉芋花來吸一下
Let me pick some Indian shots and suck them.

0:06:25.400,0:06:26.640
# 要秋天才熟
They won’t be ripe until autumn.

0:06:27.100,0:06:29.000
# 感覺那野果長的好慢啊
It seems that the wild fruits take such a long time to become ripe.

0:06:39.800,0:06:42.200
# 好  回家啦  回家啦  明天再來看
Alright! Let’s go, let’s go! Let’s come again tomorrow.

0:06:45.120,0:06:46.380
# 剛好路過攝影小哥家哦
It just so happens that we pass by Mr. Cameraman’s home.

0:06:46.380,0:06:48.040
# 你看  他家的板栗說他說不要啦
Look! These are his chestnuts but he says that he doesn’t want them anymore.

0:06:48.760,0:06:50.120
# 聽到這句話我就想笑
Hearing this makes my smile.

0:06:50.120,0:06:52.780
# 要砍掉的哦  過  過幾天就要砍掉啦
It needs to be cut away, you know. It, it will be cut away in a few days.

0:06:53.400,0:06:55.420
# 我把那板栗先把它弄下來再說
But before anything, let me get the chestnuts first.

0:07:07.720,0:07:09.420
# 一起上  哈哈  一起上
Let’s climb together. Haha! Climb together!

0:07:09.480,0:07:10.620
# 一起上也可以呀
Why not? Let's climb together.

0:07:11.800,0:07:13.240
# 來 哪[SIC]鋸子給我
C’mon! Give me the saw.

0:07:13.940,0:07:15.000
# 嗯  我拿給你
Um! Here you are.

0:07:19.020,0:07:22.960
# 請物模仿  (註︰警告字句)
DO NOT IMITATE

0:08:26.500,0:08:28.440
# 哎喲  有幾個
Ayo! Here are some!

0:08:29.200,0:08:30.260
# 你看  這多吧
Look! A lot, right?

0:08:33.580,0:08:34.720
# 這還有一個大的
Here’s also a big one.

0:08:40.680,0:08:42.360
# 怎麼這麼脆的這種樹
Why is this tree so brittle,

0:08:42.640,0:08:43.780
# 就這麼脆弱
so fragile?

0:08:55.660,0:08:56.880
# 等下  等下  我出來先
A moment, a moment. Let me get out first.

0:09:05.000,0:09:05.620
# 注意腳
Watch your legs!

0:09:15.260,0:09:16.440
# 拉著樹枝就可以啦
Just pull the branches.

0:09:17.080,0:09:19.620
# 你看  這個4胞胎喲
Look! These are quadruplets.

0:09:26.800,0:09:28.360
# 把板栗搞下來就行啦
We only need to take the chestnuts,

0:09:29.020,0:09:30.080
# 樹枝就不要啦
not the branches.

0:09:34.320,0:09:35.480
# 這個夠大吧
This is really big, isn’t it?

0:09:36.120,0:09:37.300
# 這板栗都是
These chestnuts are all,

0:09:38.760,0:09:40.260
# 很漂亮的哦  這種板栗
all very pretty, you know, these chestnuts.

0:10:06.280,0:10:08.420
# 你看  這一這一袋
Look! This, this bag,

0:10:08.820,0:10:10.460
# 跟這裡應該有五六十斤
together these, should be almost thirty kilograms.

0:10:10.960,0:10:11.920
# 帶瞉的哦
The shells are still there, you know.

0:10:13.640,0:10:16.220
# 回去挖一下應該挖得到  五六斤那個
After cracking them at home, we should be able to have about three kilograms of,

0:10:16.920,0:10:18.320
# 那個  那個板栗出來
I mean, I mean, chestnuts.

0:10:19.400,0:10:21.640
# 沒有啦  樹上還有好多啊
That’s all. There are still a lot on the tree.

0:10:22.020,0:10:23.820
# 留到下次來搞  不要一下子摘完啦
Leave them for next time. We’re not taking everything at a time.

0:10:24.400,0:10:25.340
# 細水長流
It’s called delayed gratification.

0:10:27.940,0:10:28.960
# 好啦  回去啦
Alright! Let’s go back!

0:10:43.980,0:10:46.660
# 今天晚上有得挖啦  挖一晚上
That’s our task this evening. It’s gonna take the whole evening.

0:10:47.560,0:10:49.160
# 有些板栗都烏啦
Some chestnuts have already turned dark.

0:10:49.520,0:10:50.920
# 有些就是還是白的
And some are still white.

0:10:53.860,0:10:55.280
# 你看  這種就很嫩的
Look! This is a very young one.

0:10:55.700,0:10:56.780
# 這很(好)吃的這個
It tastes really good.

0:10:57.520,0:11:00.360
# 那種 直接可以當那個水果 水果來吃
It’s like, it can be eaten right away as fruit.

0:11:00.700,0:11:02.440
# 黑了的就要用那個
The dark ones need to be,

0:11:02.980,0:11:06.380
# 蒸一下  蒸熟了  蒸熟了才可以吃  才好吃
to be steamed. They taste much better after being, being steamed.

0:11:07.120,0:11:08.780
# 那個烏的也可以吃  就是
The dark ones are still edible. They’re just,

0:11:10.040,0:11:12.260
# 就是太硬啦  不好吃  硬邦邦
just too hard, as hard as rock, don’t taste good.

0:11:19.940,0:11:20.640
# 好吃
Tasty!

0:11:50.580,0:11:52.080
# 有好多都是
Many people, like,

0:11:53.140,0:11:55.100
# 乾了再檢 就不用挖
they pick after the chestnuts are dried. Then there’s no need to crack them.

0:11:56.160,0:11:57.100
# 沒那麼好吃
But the taste is not comparable.

0:11:58.240,0:11:59.480
# 這個板栗太難挖啦
Cracking these chestnuts is really exhausting

0:12:00.440,0:12:02.300
# 讓它曬一下  讓它自然爆開
We leave them dry under the sun. They’re gonna crack open,

0:12:03.840,0:12:04.840
# 自然爆開來
by themselves, naturally.

0:12:06.040,0:12:08.260
# 你看  這兩個板栗好肥呀  看到沒
Look! These two chestnuts are really fat. See?

0:12:08.900,0:12:10.280
# 圓嘟嘟的看到沒有
They’re round and chubby. See?

0:12:13.380,0:12:14.600
# 這些都嫩的哦
These are really young,

0:12:17.700,0:12:18.500
# 很漂亮的哦
and pretty, you know.

0:12:19.460,0:12:21.020
# 再吃一個  這嫩的好好吃啊
Let me have one more. The young ones are really tasty.

0:12:22.520,0:12:25.540
# 而且它裡面的那個肉  也很甜
And the pulp inside, is also very sweet.

0:12:26.640,0:12:29.500
# 看到沒有  這個  表面這層保護膜
See? This one, the skin on the surface,

0:12:32.800,0:12:34.380
# 隨便一撕就撕得開來
can be very easily peeled off.

0:12:35.980,0:12:38.100
# 還很嫩  如果老了就不好吃啦
It’s still very young.  It doesn’t taste good after getting old.

0:12:39.360,0:12:40.260
# 你看  這個
Look! This one

0:12:41.600,0:12:42.240
# 嗯
Um!

0:12:43.220,0:12:43.980
# 好香
It smells so good!

0:12:46.080,0:12:47.160
# 感覺不好剥
Cracking these chestnuts doesn’t seem easy.

0:12:48.080,0:12:49.360
# 剥那麼久才剥那麼一點
We’ve only done with such a little bit after such a long time.

0:12:49.400,0:12:50.420
# 第二天
The next day

0:12:50.420,0:12:52.200
# 你看  在這裡喲
Look! It’s here.

0:12:52.700,0:12:55.720
# 剛好今天來收  收一下這個地籠
We’re coming today, to get, get back the traps.

0:12:56.760,0:12:57.920
# 我們就邊叫hang
We say “hang” the traps in our dialect here.

0:12:58.320,0:12:59.880
# 意思就是收地籠
It means getting back the traps.

0:13:04.240,0:13:05.980
# 你看  肯定有螃蟹的
Look! There must be some crabs.

0:13:10.060,0:13:11.040
# 專抓螃蟹
They’re specially designed for crabs.

0:13:17.340,0:13:20.120
# 看一下有兩個  我看到有兩個
It seems to be two. I see two crabs.

0:13:25.660,0:13:26.680
# 哦  3個哦
Oh! Three, actually!

0:13:26.680,0:13:28.600
# 你看 一個大的  兩個那麼小的
Look! One is big, and two are so small.

0:13:30.300,0:13:31.520
# 哦  把它倒出來
Oh. I pour them out.

0:13:38.940,0:13:40.200
# 看  這裡還有一個哦
Look! Here’s another one.

0:13:45.240,0:13:46.200
# 這個有沒有
Are there any crabs?

0:13:48.220,0:13:49.100
# 也有幾個
Yea, some.

0:13:49.880,0:13:51.220
# 又一個小螃蟹
One more little crab

0:13:51.740,0:13:52.300
# 兩個
Two more

0:13:52.960,0:13:54.520
# 3個  但是有一個大的哦
Three! But one is big.

0:13:56.360,0:13:57.940
# 有4個哦 這個
Oh, four crabs here

0:13:58.820,0:13:59.900
# 看了  看了一眼
I peeped, peeped into it.

0:14:03.260,0:14:04.660
# 你看  這裡有4個
Look! Here are four crabs.

0:14:09.800,0:14:11.860
# 你看  兩個籠子就搞了那麼多
Look! We have so many crabs in just two traps.

0:14:12.640,0:14:13.800
# 你看一下其它的
Let me have a look at the rest.

0:14:15.520,0:14:16.840
# 現在已經7個啦
We have seven crabs now.

0:14:17.080,0:14:19.440
# 看一下前面  前面還有幾個看一下有沒少
Let’s have a look in the front. There are still some traps. Let’s see how many crabs there are.

0:14:20.480,0:14:20.980
# 你看
Look!

0:14:21.840,0:14:22.680
# 7個
Seven crabs.

0:14:27.640,0:14:28.960
# 看一下這個籠子有沒有
Let me see if there’s anything in this trap.

0:14:35.420,0:14:36.800
# 也有哦  也有螃蟹
Yea, there are crabs.

0:14:39.500,0:14:40.520
# 把它解開來
Let me untie it.

0:14:42.880,0:14:43.980
# 差點跑啦
It almost ran away.

0:14:48.100,0:14:49.180
# 看一下前面有沒有
Let me see if there are any more in the front.

0:15:00.340,0:15:01.280
# 就一個
Just one

0:15:02.880,0:15:04.780
# 這麼大的籠子就裝了一個
It's such a big trap but there's only one crab.

0:15:08.980,0:15:10.260
# 還一個那麼小的
And it's a tiny crab.

0:15:15.480,0:15:17.540
# 先把籠子放在這裡先 等下倒回來拿
I leave the trap here first. I’ll come back for it later.

0:15:21.400,0:15:22.300
# 我去那邊了
I’m going to that side.

0:15:22.920,0:15:24.100
# 那裡還有一個籠子
There’s one more trap.

0:15:25.940,0:15:27.000
# 這裡有點危險
It’s a bit dangerous here.

0:15:34.320,0:15:35.580
# 這個看一下有沒有啊
Let me see if there are any crabs.

0:15:41.160,0:15:42.960
# 不是吧  空軍
Are you kidding me? It’s empty!

0:15:44.920,0:15:45.920
# 一個都沒看到
I can’t see anything,

0:15:51.280,0:15:52.300
# 一個都沒有
Not even a single crab.

0:15:53.420,0:15:55.680
# 今天的收獲也不錯哇  有十多個
It’s a rather fruitful day today. We have a dozen of crabs.

0:15:56.820,0:15:57.380
# 回去
Let’s go back, and then,

0:15:59.020,0:15:59.700
# 用那個
fry,

0:16:00.720,0:16:02.340
# 油炸了  把它炸啦
fry them in oil.

0:16:03.920,0:16:05.980
# 金黃金黃色的  炸到來吃
Fry them. They’ll turn golden brown.

0:16:06.720,0:16:08.500
# 剛好今天菜又不用買了
So that means we don’t need to buy food today.

0:16:15.580,0:16:18.400
# 你看  螃蟹兄弟  今天就把你當菜吃啦
Look! Hey crabs, my buddies, you’ll be my dish today.

0:16:18.980,0:16:20.280
# 沒辦法  豬肉貴呀
I have no choice. Pork is expensive these days.

0:16:24.500,0:16:26.880
# 你看  今天中午就吃這個哦 就是開水
Look! This is our lunch today. This is boiling water.

0:16:27.240,0:16:29.940
# 要燙一下  表面的寄生蟲才會燙掉的
We gotta blanch them, to get rid of the parasites on the surface.

0:16:32.380,0:16:33.360
# 這個沒辦法
That’s the only way.

0:16:33.740,0:16:35.100
# 一下就變紅啦
They turn red immediately.

0:16:41.340,0:16:43.280
# 這樣燙一下它表面的那些
After being blanched, the tiny,

0:16:43.960,0:16:46.240
# 那些小小的那些寄生蟲就全部燙死掉
tiny parasites on the surface would all be killed.

0:16:46.340,0:16:48.440
# 這個生殖器官要拔掉  不要
The reproductive organ needs to be removed. We don’t want it.

0:16:51.880,0:16:52.380
# 這個
Nor,

0:16:53.400,0:16:54.360
# 蓋子也不要
nor the shells,

0:16:56.720,0:16:57.700
# 這個鰓也不要
nor the gill.

0:16:58.580,0:16:59.660
# 好 就這樣就可以啦
Alright! It's fine now.

0:17:04.140,0:17:06.140
# 這個是母的  這個是公的 你看
This is female, and this is male. Look!

0:17:06.660,0:17:09.120
# 你看  這個母的就這樣子的  公的就這樣子的
Look! This is how female looks like, and this is how male looks likes.

0:17:10.840,0:17:11.340
# 啊
Ah!

0:17:12.560,0:17:13.420
# 搞那麼緊
Why is it so tight?

0:17:16.700,0:17:18.700
# 不一樣的  一看就看很出來
They are very different. You can tell immediately.

0:17:26.400,0:17:28.480
# 洗乾淨來 處理好了就那麼一點
After cleaning, just a little bit remains.

0:17:29.020,0:17:29.780
# 那麼一點點
Just a tiny little bit.

0:17:33.520,0:17:35.820
# 螃蟹的肉太少啦  多加點生薑
The crabs don’t give much to eat. Let’s put more ginger,

0:17:36.260,0:17:37.400
# 看上去就多一點
so that it looks more plentiful.

0:17:38.700,0:17:39.320
# 加點鹽
Put some salt.

0:17:40.940,0:17:42.580
# 夠啦  加點醬油
Enough. Put some soy sauce.

0:17:45.220,0:17:45.960
# 加點料酒
Put some cooking wine

0:17:56.640,0:17:58.940
# 腌個十分鐘左右就下油鍋啦
Marinate it for ten minutes then we can put them into the wok.

0:18:01.480,0:18:02.160
# 加點油
Put some oil.

0:18:10.300,0:18:11.500
# 穿到衣服來
Let me put on my jacket.

0:18:51.960,0:18:53.120
# 蟹黃都出來啦
The guts are bursting out.

0:19:01.100,0:19:02.540
# 看 可以啦  熟啦
Look! Alright! It’s done now.

0:19:04.480,0:19:05.480
# 把它撈起來
Let me take them out.

0:19:12.640,0:19:13.480
# 大大小小
Big and small,

0:19:14.420,0:19:15.260
# 全部都是
all went,

0:19:16.100,0:19:16.980
# 一起下油鍋
into the same wok together.

0:19:20.660,0:19:21.940
# 就搞了那麼一點點
And became just a tiny little bit here.

0:19:22.220,0:19:23.880
# 也好  也是一道菜
Anyway. It’s still a dish.

0:19:24.980,0:19:26.540
# 嗯  有沒有孜然粉
Um? Any cummin powder?

0:19:27.320,0:19:29.140
# 咩  來  有吃的哦
Meh~~ C’mon! I have food here!

0:19:30.080,0:19:30.680
# 要不要
You want some?

0:19:32.540,0:19:33.800
# 羊的肚子好大啦
The goats have very big bellies now.

0:19:34.380,0:19:36.900
# 你看  上一分鐘它還在夾我哦
Look! They were still pinching me a minute ago.

0:19:37.920,0:19:39.380
# 下一分鐘就變成啦
A minute later, they became,

0:19:40.720,0:19:41.620
# 這個樣子
as you can see now,

0:19:42.900,0:19:45.040
# 變成了我的食物
became my food.

0:19:54.380,0:19:55.800
# 嗯  很不錯
Um! It’s really not bad.

0:19:56.380,0:19:57.260
# 好香啊
It smells so good!

0:20:01.220,0:20:03.640
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.
