### ISSUE TITLE
[华农兄弟] 灵芝炖鸡 - https://youtu.be/qdJvzzK34iQ

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1472]
https://youtu.be/qdJvzzK34iQ
<p>&#35270;&#39057;&#21457;&#24067;&#20110; September 10, 2020 at 12:04PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/qdJvzzK34iQ

#华农兄弟：去后山摘个灵芝，再帮忙打一下稻谷，回来炖鸡
#Huanong Brothers:We pick a lingzhi from our backhill, then we help dehusking the rice, and make a chicken soup back home.

0:00:00.000,0:00:02.900
# 這個廠門口  前兩年我們摘過那個靈芝哦
We picked some, some lingzhi at the entrance of the site, a couple of years ago.

0:00:02.900,0:00:04.480
# 野生的靈芝  就在上面一點點
Those were wild lingzhi, just a tiny little bit up there.

0:00:04.860,0:00:06.020
# 看下還有沒有現在
Let’s see if there are any now.

0:00:06.300,0:00:08.240
# 今人應該有 幾個的話可能有的
There should be some this year, perhaps just a few,

0:00:08.860,0:00:10.000
# 多可能沒有
but not more.

0:00:11.600,0:00:13.820
# 全是  全是草
All, all are weeds.

0:00:22.220,0:00:23.780
# 你看  這有一個
Look! Here’s one,

0:00:24.640,0:00:25.720
# 一個那麼小的
such a small one.

0:00:27.040,0:00:28.620
# 而且它只長了一個出來
And it’s the only one.

0:00:31.880,0:00:33.420
# 誒呀  好新鮮的哦這個
Eya! This one is really fresh, you know.

0:00:36.620,0:00:39.300
# 拿回去燉雞  絕對好吃
Let’s take it back and stew with a chicken. Absolutely tasty.

0:00:41.500,0:00:44.080
# 去年長了兩三個  今年就長了一個出來
There were a couple of them last year. This year, only one.

0:00:49.960,0:00:52.080
# 好啦  帶回去  搞隻雞來燉
Alright. Let’s take it back, fetch a chicken, and then stew it.

0:00:52.760,0:00:53.660
# 去看一下
Let’s take a look.

0:00:54.220,0:00:57.260
# 天氣還早 我去看一下我家的稻子熟了沒有
It’s still early. Let’s take a look at our paddy field and see if the rice is ripe.

0:00:57.780,0:00:58.960
# 我幫忙割稻子啦
I’m gonna help them harvest.

0:00:59.340,0:01:01.060
# 現在正在農忙的季節哦
It’s now the farmers’ peak season.

0:01:01.940,0:01:02.820
# 不可以偷懶
There’s no reason for slacking off.

0:01:12.900,0:01:14.600
# 你看  她們已經割的差不多啦
Look! They’re almost done with the harvest.

0:01:30.480,0:01:33.660
# 你看  今年的粮食  大豐收我  看到沒有
Look! The corps this year is Bumper Yield. See?

0:01:35.380,0:01:36.660
# 一串都那麼多
There’s so much on just one plant.

0:01:37.860,0:01:39.300
# 一顆種能種出
Almost twenty grains,

0:01:40.340,0:01:42.000
# 十幾二十顆這樣的來
can be grown from one single seed.

0:01:43.460,0:01:44.560
# 產量高了哦
The yield is really high.

0:02:37.560,0:02:39.380
# 今天去兄弟家拎了一隻雞回來
I’ve taken a chicken from my buddy.

0:02:40.280,0:02:41.880
# 不然太浪費這個靈芝了
Otherwise, this lingzhi would become a big waste.

0:02:42.580,0:02:45.060
# 這個靈芝很難找的  好不容易才找到
Lingzhi is really rare. We’ve spent so much effort getting one.

0:02:45.840,0:02:49.700
# 要把內臟清理一下  然後再來直接煲
I need to remove the guts, and then I can cook it right away.

0:03:18.720,0:03:19.400
# 哇
Wa!

0:03:22.920,0:03:24.200
# 這個雞燙  你看
This chicken soup… Look!

0:03:27.400,0:03:28.400
# 靈芝哦
It’s lingzhi, not other mushrooms!

0:03:29.100,0:03:32.780
# 靈芝蒸出來的雞湯  鮮濃鮮濃的
Soup with lingzhi! Savory and rich!

0:03:38.560,0:03:39.320
# 先嘗一下
Let me have a try,

0:03:40.660,0:03:41.760
# 味道怎麼樣
and see how it tastes.

0:03:50.900,0:03:51.880
# 好燙啊這個
It’s so hot.

0:04:00.800,0:04:01.960
# 還缺了一點鹽
I want a bit more salt.

0:04:10.100,0:04:11.100
# 嗯   可以啦
Um! It’s alright now.

0:04:13.580,0:04:16.200
# 可以吃了  先等一下  好燙啊
We can start now! Not now, it’s very hot.

0:04:20.100,0:04:22.080
# 這個靈芝  煲完燙之後就
The lingzhi, after making the soup,

0:04:23.160,0:04:24.240
# 沒有  沒甚麼用了
it has, it has already served its purpose.

0:04:24.520,0:04:26.180
# 沒甚麼  多大的價值了
It’s no longer, really that worthy now.

0:04:32.060,0:04:33.540
# 這個雞腿才是重點
The focus now is this chicken leg.

0:04:43.600,0:04:46.140
# 等一下來 等下給個骨頭給你吃
A moment. I’ll leave the bone for you.

0:04:49.500,0:04:52.660
# 你看  一叫它們  所有的狗都出來啦
Look! Once I call them, all dogs are coming out.

0:04:59.740,0:05:02.640
# 你看  這老母狗   口水都流出來啦
Look! This great mom, is already drooling.

0:05:11.060,0:05:14.760
# 你看  這就是以前的胖熊 小胖熊  現在都變樣啦
Look! He is Chubby, Chubby Bear back in those days. He looks completely different now.

0:05:19.040,0:05:21.700
# 好啦  今天的視頻就到這裡啦
Alright. The video ends here.

0:05:22.640,0:05:24.300
# 準備炒點青菜來吃飯
I gotta cook some veggies for our meal.
