### ISSUE TITLE
[华农兄弟] 华农兄弟好久没看过竹鼠棚了带大家看一下再喂一下香猪 - https://youtu.be/OT4tKVE0uSs

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1487]
https://youtu.be/OT4tKVE0uSs
<p>&#35270;&#39057;&#21457;&#24067;&#20110; September 16, 2020 at 11:52AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/OT4tKVE0uSs

#华农兄弟：好久没看过竹鼠棚了，带大家看一下，再喂一下香猪
#Huanong Brothers: We haven't see the bamboo rats sheds for a long time. Let's show you. Then we feed the pig.

0:00:00.000,0:00:03.100
# 大家好  好久都沒進過那竹鼠棚裡面去啦
Hi everyone! It has been a long time since my last time going into the bamboo rats shed.

0:00:03.320,0:00:06.840
# 帶大家進去看一下那裡沒有 沒竹鼠了哦
Let me take you there and have a look. There are no, no more bamboo rats now.

0:00:10.980,0:00:13.300
# 小狗  小羊
Doggy! Hey goat!

0:00:26.840,0:00:28.480
# 你看  全是亂糟糟的
Look! It’s a big piece of mess.

0:00:29.340,0:00:33.360
# 你看  這個池子還是很漂亮的哦  剛做沒多久的
Look! These cells are still very pretty, you know. They’re newly built.

0:00:35.200,0:00:37.440
# 放一個公仔圶這裡  看下怎麼樣
Let me put a stuffed toy here, and see how it looks.

0:00:45.160,0:00:46.040
# 像不像真的
Does it look like a real one?

0:00:50.880,0:00:53.820
# 這個可以放在這裡  誒  這裡要掃一下
I can put this one here. Eh? Here needs to be cleaned.

0:01:02.300,0:01:05.920
# 你看  以前每天都掃  現在 不用掃啦
Look! I used to clean them every day. But now, no need.

0:01:06.420,0:01:07.920
# 你看  習不習慣
Look! Do you like this place?

0:01:09.860,0:01:12.020
# 你看  這樣放下去很可愛哦
Look! It’s so cute inside the cell,

0:01:13.800,0:01:14.840
# 就是不會動的
except that it doesn’t move.

0:01:16.860,0:01:20.200
# 你看 摸起來很舒服吧  這個毛
Look! The fur feels really good, the fur.

0:01:21.900,0:01:24.780
# 看搞的跟真的一樣 有點硬邦邦的
It really looks like the real fur. It’s a bit stiff.

0:01:33.540,0:01:36.100
# 你看  它牙齒都白了  肯定上火了
Look! Its teeth are all white. It must have eaten too much junk food.

0:01:36.940,0:01:38.220
# 給它  給一些
Let me give it, give it some,

0:01:38.900,0:01:41.120
# 給一些那個下火的東西給它吃就好啦  (註︰已經不是真竹鼠，不太講究，容易明白就算了)
some it some more healthy food. It will soon be fine.

0:01:42.840,0:01:43.800
# 尾巴那麼短
Its tail is so short.

0:01:44.700,0:01:45.320
# 打架了
It must have had a fight.

0:01:47.600,0:01:49.080
# 這爪子  它的爪子
This claws, its claws,

0:01:49.920,0:01:52.400
# 好鋒利啊它的爪子  看上去就很鋒利
Its claws are really sharp. They look very sharp.

0:01:55.260,0:01:57.120
# 搞不痛的  絨毛做的
It doesn’t hurt. Cuz they’re made of flannel.

0:01:57.920,0:01:59.600
# 要是真的我就不敢給它這樣抓
If wouldn’t dare to let it scratch me if it’s real.

0:02:02.000,0:02:03.100
# 好像啊哦
It really looks like a real one.

0:02:05.720,0:02:06.480
# 捏兩下
Let me squeeze it.

0:02:12.520,0:02:14.160
# 這個不怕它咬啦這個
There’s no risk of being bitten, with this bamboo rat.

0:02:20.120,0:02:22.000
# 鬍子怎麼沒有啦 鬍子
Why aren’t there any whiskers? Where are the whisker?

0:02:23.020,0:02:25.940
# 鬍子容易抓了 容易抓  抓人的臉
The whisker may scratch, they always scratch, scratch our faces.

0:02:28.180,0:02:29.540
# 鬍子都被我拔掉啦
So I pulled out all whiskers.

0:02:32.900,0:02:33.820
# 你看公仔
Have a look at this toy.

0:02:35.180,0:02:35.860
# 放在這裡
I put it here,

0:02:38.200,0:02:38.900
# 放成一排
in a line.

0:02:43.860,0:02:45.300
# 站穩來哦 別掉不去了
Stand still. Don’t fall.

0:02:50.240,0:02:51.100
# 多可愛
So cute!

0:02:55.860,0:02:56.480
# 排隊
Line up!

0:02:58.720,0:03:00.080
# 一二三四五六七八九十
One two three four five six seven eight nine ten

0:03:02.180,0:03:03.420
# 這樣就漂亮啦這樣
Now it’s really pretty, pretty.

0:03:09.020,0:03:10.640
# 要竹鼠有那麼聽話就好了
Why aren’t the real bamboo rats as nice as they are?

0:03:20.480,0:03:21.780
# 你看  把它收回了
Look! I’m gonna get them back.

0:03:22.860,0:03:25.480
# 這個池子  明天就準備把它全部拆掉啦
These cells, I'll start pulling them down tomorrow.

0:03:27.120,0:03:28.960
# 不用啦  也用不上啦
I don’t need them anymore, not now, nor in the future.

0:03:32.480,0:03:34.200
# 來  裝到袋子這邊來
C’mon! Put them into the bag.

0:03:46.000,0:03:48.200
# 你看  這個池子很好拆的哦
Look! Pulling down the cells doesn’t take too much effort.

0:03:48.580,0:03:49.880
# 這個剛做沒兩年
They’re newly built, less than two years ago.

0:03:53.980,0:03:56.620
# 可能還可以有 其它的利用
Perhaps they can still be used, somewhere else.

0:03:57.260,0:03:59.880
# 或者把這個把它  看下有沒有需要的
I could perhaps take them, take it and see if anyone wants them.

0:04:00.380,0:04:02.480
# 需要的就買[SIC]給它算啦
I can sell them these boards.

0:04:04.240,0:04:06.040
# 這些瓷磚也是要錢來買的
Afterall, I did pay for these boards.

0:04:09.420,0:04:10.860
# 明天就把它全部拆掉
I’ll pull them all down tomorrow.

0:04:11.400,0:04:13.420
# 不要啦  把這裡清理一下
Let them go. Then I’ll clean this place,

0:04:14.440,0:04:15.700
# 養點其它東西
and keep some other livestock.

0:04:22.240,0:04:24.800
# 拆的時候很容易拆的哦  一拆就倒啦
Pulling down is easy. A single pull is everything needed.

0:04:25.560,0:04:28.400
# 做的時  做的話這裡最少要做兩個月
But building them, building them needs at least two months.

0:04:28.780,0:04:31.500
# 如果一個人的話可能要兩三個月才能做的完
It may take up to three months if they’re built alone.

0:04:32.280,0:04:35.180
# 要慢慢粘  要要黏  還要固定
You need to glue them, stick them, and place them well, step my step.

0:04:35.940,0:04:37.440
# 一個人拆太累了
Doing it alone is too exhausting.

0:04:38.640,0:04:41.440
# 叫兄弟  明天叫兄弟這來一起拆
I’ll ask my buddy, ask my buddy to come tomorrow and do it together with me.

0:04:42.620,0:04:46.560
# 看一下那個小豬  昨天都沒餵  今天
Let me have a look at the piggy. I didn’t feed it yesterday. So today,

0:04:47.200,0:04:49.840
# 它應該餓著了  去搞點那個玉米來給它吃
it must be staving now. I’m gonna get some corns for it.

0:04:50.560,0:04:51.700
# 先來餵一下它
Let me feed it first.

0:04:58.340,0:05:01.640
# 拿了玉米上來  這個小豬最喜歡吃的這個玉米
So I have the corns with me now. It's the piggy's most favourite food.

0:05:03.160,0:05:05.440
# 它一天就吃那麼一丟丟就夠啦  不要吃那麼多
Just a tiny little bit here is enough for a day. Don’t let it eat too much.

0:05:05.940,0:05:07.300
# 吃多了它容易胖
Eating too much may lead to obesity.

0:05:11.840,0:05:14.220
# 來 妹妹過來呀  餵小豬咯
C’mon! Come here my girl. We’re gonna feed the piggy.

0:05:15.020,0:05:15.720
# 你怕不怕
Are you scared?

0:05:16.720,0:05:17.720
# 你怕不怕小豬
Are you scared of piggy?

0:05:19.300,0:05:20.340
# 還有鴨鴨哦
There’s also ducky,

0:05:21.960,0:05:23.220
# 還有鵝鵝哦
and goose.

0:05:27.840,0:05:28.540
# 走邊上
Walk on the side.

0:05:32.020,0:05:32.920
# 拿給它們吃
Give it to them.

0:05:38.600,0:05:40.980
# 你看這小豬太壞啦  它趕那個鴨子
Look! This piggy is really mean. It’s chasing away the duck.

0:05:47.820,0:05:49.240
# 是不小豬佩琪這條
Is this one Peppa Pig?

0:05:50.500,0:05:51.020
# 是不是
Is it?

0:05:51.740,0:05:53.000
# 小豬佩琪是不是這一隻
Is Peppa Pig in front of us?

0:06:02.560,0:06:04.800
# 你敢不敢去騎豬豬  敢不敢
Do you dare to ride on the piggy? Do you?

0:06:06.180,0:06:06.900
# 敢不敢
Do you dare?

0:06:07.740,0:06:09.120
# 嘿嘿  丟掉啦
Hehe. It dropped.

0:06:09.540,0:06:10.480
# 快把它撿回來
Let me pick it up.

0:06:26.800,0:06:29.360
# 好像又胖了 大了好多 現在
It seems that it has put on weight again. It’s so much bigger now.

0:06:38.220,0:06:39.860
# 摸一下它  看它還有沒有反應
Let me touch it and see if what happens.

0:06:43.080,0:06:44.000
# 過來
Come here!

0:06:47.280,0:06:49.740
# 那麼兇幹嘛  這裡又沒人搶你的
How come are you so fierce? The corns are yours and only yours.

0:06:51.780,0:06:52.500
# 暈了
It’s falling down.

0:06:59.680,0:07:03.900
# 它要吃  如果沒東西吃的話它就躺下啦
It wants to eat. It may lie down if it’s not eating.

0:07:05.740,0:07:08.940
# 我怎麼一模它腳都站不穩了  呵呵呵
Why is my touch making it shaky? Ho ho ho!

0:07:15.340,0:07:16.840
# 嘿耶  不讓我碰
Heya! It refuses my touch.

0:07:18.540,0:07:21.260
# 你看  這個鴨子好肥啦  都下蛋啦
Look! This duck is very fat now. It lays eggs now.

0:07:21.880,0:07:25.140
# 鵝也是  下的蛋都被這條豬偷吃了
The goose too. But their eggs are all stolen by this pig.

0:07:28.020,0:07:33.000
# 你看  這些攀蒲 種的那麼茂盛  都是前面那條豬種的哦
Look! These pumpkins, they’re growing so well. These are all planted by the pigs that used to live here, you know.

0:07:33.640,0:07:35.120
# 有一句話怎麼說來的
How does the saying go?

0:07:36.820,0:07:40.960
# 前豬種  種瓜  後豬爽歪歪
Pumpkins, and, and veggies, pigs plant for their heirs.

0:07:43.460,0:07:45.500
# 很爽口的哦  這個攀蒲
The pumpkins, are really crunchy.

0:07:47.080,0:07:53.020
# 現在豬跟羊  跟鵝  跟鴨  都相處在一起了
The pig is now getting along with the goat, the goose and the duck.

0:07:54.240,0:07:57.820
# 而且很和諧的哦  不打架  不吵也不鬧
And they get along well, you know. No fights, no arguments, no quarrels.

0:08:00.420,0:08:02.960
# 誰干打架 誰敢吵  一鍋端了你
Anyone who dares to make a scene here, I’ll put you into the pot.

0:08:06.560,0:08:07.520
# 咩~
Meh~

0:08:08.840,0:08:09.500
# 咩~
Meh~

0:08:19.660,0:08:20.440
# 咩~
Meh~

0:08:21.720,0:08:22.600
# 咩~
Meh~

0:08:26.160,0:08:27.720
# 肚子好大啦這隻羊
This goat now has a very big belly.

0:08:45.460,0:08:48.960
# 你看  它這個豬的豬身好長啊看著
Look! This pig, its body is really long. See?

0:08:49.620,0:08:52.060
# 原 原來是圓的  現在是加長啦
It used, used to be round. But now it’s much longer.

0:08:52.560,0:08:53.440
# 說明又胖了
That means it’s fatter.

0:08:54.160,0:08:55.240
# 又長大了一點
It has grown up a bit again.

0:08:56.860,0:08:59.220
# 到過年的時候這應長到一百多斤
It would be well over fifty kilograms by the Chinese New Year.

0:09:00.440,0:09:01.980
# 剛好 對半劈開
Cut it into half. Perfect!

0:09:02.440,0:09:04.500
# 我和攝影小 我和攝影小哥一人一半
I and Mr. Camer, I and Mr. Cameraman each takes half.

0:09:06.560,0:09:07.900
# 從中間一破
Split it into two parts from the middle.

0:09:08.920,0:09:10.880
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.

0:09:11.440,0:09:12.860
# 我要回家煮飯啦
I need to go home and cook for my dinner.
