### ISSUE TITLE
[华农兄弟] 华农兄弟买了一把小电锯帮摄影小哥摘板栗也就搞了一小车 - https://youtu.be/_DQ50lE_X84

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1496]
https://youtu.be/_DQ50lE_X84
<p>&#35270;&#39057;&#21457;&#24067;&#20110; September 19, 2020 at 11:40AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/_DQ50lE_X84

#华农兄弟：买了一把小电锯，帮摄影小哥摘板栗，也就搞了一小车
#Huanong Brothers: Bought a chain saw. Help Mr. Cameraman pick chestnuts. Fill up a small van.

0:00:00.000,0:00:04.020
# 你看  買了一個這個鋸子  去攝影小哥家砍樹
Look! I’ve bought this chain saw, to chop the tree at Mr. Cameraman’s place.

0:00:04.200,0:00:07.240
# 他家的板栗樹要砍掉哦  他家要做房子
His chestnuts tree needs to be chopped, cuz he wants to build a house.

0:00:08.020,0:00:11.300
# 所以趁機會把板栗  全部摘下來
So I have the chance. I'm gonna pick all the chestnuts there.

0:00:11.740,0:00:13.340
# 試一下啊  買了一個這個
Let me try. I’ve just bought it.

0:00:24.620,0:00:27.060
# 要穿這個安全褲才行的哦  要不然
We gotta put on this harness. Otherwise,

0:00:27.620,0:00:29.800
# 很危險的 要上那麼高的樹
it's too dangerous. We need to climb such a tall tree.

0:00:30.940,0:00:34.140
# 這個尺寸要調到自己合適  合適為準
The size needs to be adjusted to fit, fit myself.

0:00:36.920,0:00:38.860
# 剛搞這個就是不知道安不安全呢
I’ve just put this on but have no ideas if it's really save.

0:00:39.440,0:00:41.720
# 我去樹上掛一下我  看一下行不行
Let me hang myself onto the tree and see if it works.

0:00:48.100,0:00:49.780
# 我先試一下安不安全這個
Let me try if this is really safe, this harness.

0:01:05.040,0:01:06.720
# 可以啦  這樣挺安全的這樣
Alright. It’s rather safe this way.

0:01:07.740,0:01:09.220
# 這吊兩條豬都沒問題
It can easily stand the weight of two pigs.

0:01:12.900,0:01:13.560
# 可以哦
Not bad!

0:01:17.340,0:01:18.600
# 你看  我都可以掛在這裡
Look! I can hang myself onto the tree.

0:01:22.120,0:01:24.020
# 準備上樹啦  把這個
Let’s get ready. This one,

0:01:25.000,0:01:25.600
# 勾起來
hook it here.

0:03:01.060,0:03:05.700
# 這裡 這裡肯定撿的到  兩三百斤肯定撿的到的
Here, here, we can pick, I’m sure that we can pick up to at least a hundred and fifty kilograms.

0:03:07.060,0:03:08.700
# 好大顆  好大粒啊
It’s so big, really big!

0:03:10.880,0:03:13.600
# 你看 這樣就  很漂亮的哦  這種板栗
Look! This one is, really pretty, you know, this kind of chestnuts.

0:03:14.180,0:03:15.460
# 又大又圓
Big and round.

0:03:17.280,0:03:19.360
# 先把它撿回去  慢慢處理
Let me pick them all back first, and deal with them afterwards.

0:03:46.900,0:03:48.140
# 兩牛皮袋都滿啦
Two bags are completely filled.

0:03:48.900,0:03:50.320
# 先拱到那個麵包車上
Let’s lift it to our van first.

0:04:08.480,0:04:09.580
# 就搞了那麼一點點
So we have just a tiny little bit here.

0:04:11.620,0:04:13.500
# 好像六麻袋還是七麻袋
There seems to be six or seven bags.

0:04:14.820,0:04:15.420
# 回去啦
Let’s go back.

0:04:16.220,0:04:18.540
# 周個豬肚來 板栗煲豬肚
Let me fetch a pork bag, and stew it with the chestnuts.

0:04:20.160,0:04:21.640
# 第二天
The next day

0:04:25.600,0:04:29.420
# 都是瞉裡面看不出來的  一掰出來就是好的  (註︰我聽到他是說「是老的」)
We can’t see the chestnuts inside the shell. But once the shell is cracked, you'll see that it's old.

0:04:35.740,0:04:36.720
# 不是很老的板栗
These chestnuts are not really old.

0:04:36.720,0:04:39.800
# 是的  不是很老  但是也可以吃的哦  你看
Yup. Not very good. But they’re still edible, look!

0:04:40.640,0:04:41.200
# 那麼大
It’s so big.

0:04:41.200,0:04:42.800
# 先把這板栗剝一下
Let’s peel the chestnuts first.

0:04:44.540,0:04:45.860
# 先要一個個把它剝好
I gotta peel them one by one.

0:04:46.580,0:04:48.020
# 這個壞的  壞的就不要
This one is rotten. Pass.

0:04:48.560,0:04:49.480
# 要慢慢剝
It might take some time.

0:04:50.080,0:04:51.040
# 先吃一個先
Let me eat one first.

0:04:52.620,0:04:55.760
# 剛好今天人多啊   搞了3隻雞  在[SIC]搞了一點板栗
It just so happens that there are many people here today. I have fetched three chickens, and also some chestnuts,

0:04:56.100,0:04:56.860
# 加一個豬肚
together with a pork bag,

0:04:57.380,0:04:58.020
# 一鍋燉啦
then stew them all in the same pot.

0:05:01.240,0:05:03.520
# 這個雞在兄弟家
This chicken had been kept

0:05:05.820,0:05:06.340
# 養啦
at my,

0:05:07.180,0:05:08.980
# 養了差不多半年這個土雞
at my buddy’s place for more than half a year, this free range chicken.

0:05:13.300,0:05:14.300
# 沒甚麼肥肉的哦
There’s hardly any fat, you know.

0:05:16.000,0:05:16.740
# 這個雞腿
This chicken leg,

0:05:17.700,0:05:18.760
# 這個雞腿留著
leave this chicken leg in one piece.

0:05:30.140,0:05:33.660
# 好的食材不需要調料的哦 放點生薑就好啦
Good ingredients never need seasoning. A little bit of ginger is everything needed.

0:05:36.740,0:05:39.080
# 放到前面去  直接下鍋
Let me put it over there, and then into the pot right away.

0:05:39.080,0:05:40.340
# 把這個雞都放下去了
So I’m gonna put the chicken in.

0:05:42.700,0:05:43.540
# 哎呀  一大鍋
Aya! A big pot!

0:05:43.680,0:05:45.680
# 然後再把這個豬肚放下去  (註︰原字幕缺失了)
Then I put this pork bag in as well.

0:05:48.960,0:05:49.880
# 就直接在這樣
Then leave everything here right away.

0:05:51.000,0:05:53.440
# 然後直接蓋起來  大火燒
And then cover it up right away, and cook it on high heat.

0:05:54.040,0:05:55.260
# 燒一個小時就可以啦
Cook it for an hour. That’s it.

0:05:55.980,0:05:57.080
# 再搞一點板栗
Let me get some chestnuts as well.

0:06:01.440,0:06:02.640
# 這個板栗剝好了哦
These chestnuts have been peeled now.

0:06:03.840,0:06:04.780
# 等下我把它倒下去
I’ll put them into the pot in a while.

0:06:05.420,0:06:07.840
# 差點忘記啦  這個才是主食來的
I’ve almost forgotten. The protagonist is here,

0:06:07.920,0:06:08.780
# 這是板栗啊
the chestnuts.

0:06:13.120,0:06:13.900
# 加點鹽
Put some salt.

0:06:34.120,0:06:35.580
# 嗯  真的很好吃
Umhm! It’s really tasty.

0:06:35.740,0:06:36.540
# 不騙你們的
No kidding.

0:06:38.220,0:06:38.920
# 這個湯
The soup,

0:06:39.360,0:06:40.880
# 簡直是精華所在
is really where the essence is.

0:06:45.680,0:06:46.780
# 搞一個雞腿吃一下
Let me have a chicken leg.

0:06:50.220,0:06:51.120
# 這個雞腿
This chicken leg…

0:06:52.100,0:06:54.120
# 看到沒有  大長腿
See? It’s a big, long leg.

0:06:55.260,0:06:57.080
# 長而不油膩
Long, but not oily.

0:07:00.740,0:07:01.380
# 很好吃
It’s so tasty.

0:07:03.700,0:07:04.780
# 準備吃飯啦
It’s time for lunch now.

0:07:05.300,0:07:07.240
# 他們都餓的受不了啦
They’re nearly staving to death.

0:07:07.460,0:07:08.460
# 現在都快2點了
It will be two very soon.

0:07:09.920,0:07:11.380
# 那個煲一下湯煲的有點久
Making this soup took a bit longer than expected.

0:07:14.860,0:07:16.660
# 所以 好東西都是
So, good food always,

0:07:17.100,0:07:19.020
# 慢慢  慢慢燉出來的
takes, takes much more time.

0:07:21.560,0:07:23.400
# 嗯  好啦  準備吃飯啦
Um! Alright! Let’s have our lunch.

0:07:26.360,0:07:27.080
# 開吃開吃
Let’s start, let’s start!

0:07:27.560,0:07:28.880
# 吃飯咯  吃飯咯
Meal time, meal time!
