### ISSUE TITLE
[华农兄弟] 华农兄弟摄影小哥老家盖房子去帮一下忙顺便搞点禾笋来吃 - https://youtu.be/m18XbjAclw4

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1502]
https://youtu.be/m18XbjAclw4
<p>&#35270;&#39057;&#21457;&#24067;&#20110; September 20, 2020 at 12:07PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/m18XbjAclw4

#华农兄弟：摄影小哥老家盖房子，去帮一下忙，顺便搞点禾笋来吃
#Huanong Brothers: Mr. Camerman is building a house at home. I go and give him a help, and get some wild rice as well.

0:00:00.000,0:00:04.480
# 大家好  今天攝影小哥家的房子哦  做子個樓頂啊
Hi everyone! Today, Mr. Cameraman’s house, they’re making the, the rooftop,

0:00:04.480,0:00:06.160
# 不是樓頂  這是第一屋的頂
no, not the rooftop, but the roof of the first floor.

0:00:08.140,0:00:09.300
# 我們過來幫一下忙
We’re coming to give a hand.

0:00:09.980,0:00:11.000
# 好多人都上去啦
Many people are already up there.

0:00:11.580,0:00:12.800
# 我也過來幫一下忙
And I’m going as well.

0:00:13.620,0:00:16.000
# 這個是主樑哦  要把這個
This is the main pillar. It needs to be,

0:00:16.980,0:00:19.560
# 這個  水泥要把它灌進去
the, the cement needs to be poured inside.

0:00:19.920,0:00:20.760
# 不灌進去
Otherwise,

0:00:24.020,0:00:25.380
# 不灌進去沒用的
it's useless otherwise.

0:01:37.340,0:01:40.160
# 現在快搞完啦  還有一個小時左右就可以搞得完啦
It’s almost finished now. It will be finished in about an hour.

0:01:40.380,0:01:42.440
# 我去搞點Wo笋來煮飯 (註︰這應該是茭白，萵笋應該是方言叫法，為免混亂，以茭白翻譯，下面有一堆用顯微鏡才看到的附註，不譯了)
Let me get some wild rice for our meal,
(Wild rice: Zizania latifolia, also know as  Manchurian wild rice)

0:01:42.700,0:01:43.340
# 煮晚飯
for our dinner.

0:01:44.000,0:01:44.900
# 在前面那一點
It’s over there a bit in the front.

0:01:46.260,0:01:47.660
# 馬上就天黑啦  你看
It’s getting dark now. Look!

0:01:48.020,0:01:50.660
# 我去搞點那個WO笋  就在那邊
Let me get some wild rice. It’s right over there.

0:01:56.460,0:01:58.180
# 你看  這個就是WO笋哦
Look! This is wild rice.

0:01:59.780,0:02:01.900
# 誒  被兄弟拔啦
Eh? It was picked by my buddy.

0:02:15.080,0:02:16.140
# 有肉的  這個
It is edible, this one.

0:02:18.560,0:02:21.320
# 你看  這個是有肉的看見沒有  好嫩的哦  這個
Look! It has an edible part. See? This one is really young and tender, you know.

0:02:22.900,0:02:24.680
# 直接就可以吃啊  可以當水果吃
It can be eaten right away, as fruits.

0:02:25.800,0:02:27.260
# 有點甘甜甘甜的味道
It tastes a bit savoury and sweet.

0:02:29.100,0:02:31.520
# 你看  剛長出來很嫩的
Look! It has just grown out from the soil. It’s still very young.

0:02:34.620,0:02:35.160
# 嗯
Um!

0:02:36.140,0:02:36.720
# 可以
Not bad!

0:02:48.680,0:02:49.940
# 你看  就這一點點
Look! It’s just a tiny little bit here.

0:02:53.040,0:02:54.740
# 夠嫩吧  這樣才好吃
It’s young, isn’t it? That’s why it is tasty.

0:02:56.520,0:02:57.680
# 就那一點點夠啦
Just a tiny little bit here is enough.

0:03:13.920,0:03:15.840
# 就這一點點  肚子大的  這個
Just a tiny little bit here, with a big belly, this one.

0:03:17.140,0:03:18.840
# 嗯  我們就要這一點點
Um! We only take this tiny little bit here.

0:03:19.320,0:03:21.400
# 看起來不要看它的肚子稍微小一點
Although its belly looks a little bit small,

0:03:21.800,0:03:23.220
# 這個全是肉哇  看到沒有
everything here can be eaten, see?

0:03:24.360,0:03:25.540
# 這就是肉  看到沒有
This part can be eaten, see?

0:03:27.560,0:03:28.600
# 啊 這個肉
Ah! It’s really nice.

0:03:29.620,0:03:31.000
# 金[SIC]瑩剔透的肉
Crystal clear

0:03:31.920,0:03:33.000
# 乳白色的肉
And milky white

0:03:34.600,0:03:35.540
# 很嫩的
It’s really young and tender.

0:03:37.200,0:03:39.420
# 啊  這個就是標準身材  剛剛好
Oh! This is the standard build. Everything is perfect.

0:03:44.100,0:03:45.000
# 你看  可以吧  (註︰我聽到他說︰「可以了」
Look! It’s alright now.

0:03:48.520,0:03:49.620
# 嗯 可以
Um! It’s not bad.

0:03:55.660,0:03:56.400
# 這裡比較多
There are quite a lot here.

0:04:29.280,0:04:31.200
# 沒多少  就那麼一丟丟
Not too much. Just a tiny little bit here.

0:04:40.820,0:04:43.920
# 這個都不是很大  可能  不是很熟
And they’re not really that big. Perhaps, they’re not completely ripe.

0:04:44.920,0:04:46.560
# 但是太熟了又會老掉
But they would be too old if they’re completely ripe.

0:04:48.180,0:04:49.620
# 所以我也很糾結
So I’m always struggling.

0:04:50.860,0:04:52.460
# 你看  就搞了那麼一點點
Look! So we’ve taken just a tiny little bit here.

0:04:53.200,0:04:55.020
# 它現在不是很  很老哦
Now they’re not really, really old.

0:04:55.820,0:04:56.400
# 下次來
Next time.

0:04:57.160,0:04:58.900
# 讓它們也長肥一點  我再來
I’ll come again, after they have grown fatter.

0:04:59.660,0:05:00.640
# 現在不是很胖
They’re not really that fat now.
