### ISSUE TITLE
[华农兄弟] 华农兄弟捡点南酸枣做酸枣糕过程繁琐复杂但味道很不错 - https://youtu.be/M-cIqDw53Bk

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1520]
https://youtu.be/M-cIqDw53Bk
<p>&#35270;&#39057;&#21457;&#24067;&#20110; September 27, 2020 at 06:03PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/M-cIqDw53Bk

#华农兄弟：捡点南酸枣做酸枣糕，过程繁琐复杂，但味道很不错
#Huanong Brothers: Make some hog plum rolls. Though the process is complicated, it tastes really good.

0:00:00.000,0:00:02.620
# 大家好 現在的酸棗(南酸棗)都熟了哦
Hi everyone! The hog plums are ripe now.

0:00:03.060,0:00:06.740
# 我去山上撿點酸棗  但是這個刀有點鈍啦  要磿利一點
Let me go to the hill and pick some hog plums. But this knife is a bit blunt. I gotta sharpen it.

0:00:07.560,0:00:10.880
# 因為現在酸棗剛成熟  山上那個草
Cuz now the plums are just ripe. And the weeds on the hill,

0:00:11.220,0:00:14.800
# 都已經太長啦  所以我要拿這個刀把它劈掉
are already too long. So I’m cutting them off with this knife.

0:00:15.000,0:00:16.460
# 不劈掉的話會割腳的哦
Otherwise they may cut my legs.

0:00:16.980,0:00:20.400
# 你看  長褲又沒得穿  穿了條短褲
Look! I don’t even have trousers. I’m just wearing pants.

0:00:21.880,0:00:26.380
# 好啦  不用磿啦  這個刀已經很利了  本來就很利的
Alright! I think it enough. It is already very sharp. It’s always very sharp.

0:00:27.380,0:00:30.300
# 你看  路過兄弟家的板栗樹哦  這個
Look! We pass by my buddy’s chestnut tree. Here.

0:00:30.300,0:00:34.480
# 很多的  他家的板栗又大  又大個  又多籽
Here are a lot. His chestnuts are big and, big and, there are plenty of nuts.

0:00:35.560,0:00:37.000
# 我去看一下有沒有先
Let me go and see if there are any.

0:00:38.040,0:00:39.540
# 檢兩個來吃一下也好
I would be nice if I could pick a couple of them.

0:00:42.840,0:00:46.600
# 你看  這裡就有一個哦  那麼大的 又大又黃
Look! Right here is one. It’s so big, big and brown,

0:00:47.340,0:00:48.300
# 又大又紅的
I mean big and red.

0:00:56.220,0:00:58.220
# 才檢了一個  太少啦
I've picked just one. It’s too few.

0:00:58.220,0:01:02.120
# 你看  樹上還有好多爆的哦 都裂開啦  它就是不掉下來
Look! Many in the tree have already cracked, cracked open. But they’re not falling dowm.

0:01:02.840,0:01:03.900
# 太氣人啦
It’s too bad.

0:01:09.000,0:01:10.120
# 哎 掉啦
Ay! It drops.

0:01:13.220,0:01:15.180
# 終於到了這個 lian ma gai (南酸棗)的樹下
Finally, we’re under the hog plum tree.

0:01:15.180,0:01:16.360
# 你看  這個lian ma gai (南酸棗)
Have a look at these hog plums.

0:01:16.360,0:01:18.580
# 一樹都是青的  還沒掉下來哦
The green ones are all over the tree, and they’re not falling down.

0:01:22.380,0:01:23.920
# 它從這掉了一點點下來
Some of them have fallen down here along the slope.

0:01:24.800,0:01:27.000
# 熟了它就會掉下來  不熟的它不掉的
They fall when they’re ripe. The green ones never fall.

0:01:27.760,0:01:29.380
# 哎呀  這兩個
Aya! These two…

0:01:30.900,0:01:32.500
# 這個  壞啦  這個
This one, is rotten, this one.

0:01:35.340,0:01:39.160
# 這裡多哦  這裡  剛好掉在這裡  這坑上
Here are a lot! Here, they landed right here, right on this pit.

0:01:40.080,0:01:41.860
# 你看這個是  爛的  不要
Look! This is, rotten. Pass.

0:01:42.520,0:01:43.840
# 我們要檢要檢好的
We pick only the good ones.

0:01:51.260,0:01:54.980
# 你看這個  酸棗就這樣子的  它裡面的肉
Have a look at this one. This is how a hog plum looks like, how the pulp inside looks like.

0:01:57.940,0:02:01.220
# 嗯~吃酸棗的時候第一口是甜的
Um~ The first bite of hog plum is always sweet.

0:02:01.680,0:02:03.540
# 慢慢的就越來越酸 越來越酸
But the sweetness is gradually overtaken by the sourness.

0:02:06.640,0:02:10.820
# 好像裡面的汁是甜的  但是果肉就是慢慢的越來越酸啦
It seems that the juice is sweet. But the sourness from the pulp gradually comes in.

0:02:12.000,0:02:14.180
# 檢了半個小時就搞了那麼一點點
So I’ve picked just a tiny little bit here in half an hour.

0:02:15.940,0:02:19.620
# 等一下  我去兄弟家  他家樹底下應該多一點
Later, let me go to my buddy’s place. There should be more under his tree.

0:02:19.980,0:02:23.540
# 我要檢一點回來  我們這  這是我家的樹哦
Let me pick some from his place. Mine here... This is my tree, you know.

0:02:24.360,0:02:27.620
# 不掉的  全在樹上你看到沒有  好多都是青的
They don’t fall. They're all stilll in the tree, most are still green.

0:02:27.620,0:02:31.200
# 它們沒掉下來  兄弟家的掉下來  去撿兄弟家的
They don’t fall. My buddy’s plums do fall. Let me pick his plums.

0:02:32.840,0:02:35.860
# 好啦  回去準備一下  做酸棗糕
Alright! Let's go back, and get ready, to make some hog plum rolls.

0:02:39.660,0:02:40.740
# 第二天
The second day

0:02:41.040,0:02:42.380
# 這個酸棗撿回來啦
So we’ve taken the hog plums back.

0:02:42.800,0:02:44.520
# 要用開水煮一下
They need to be blanched in water first.

0:02:44.520,0:02:46.780
# 煮一下就可以把那個皮直接剝掉就可以啦
After blanching them, they can be, can be peeled right away.

0:02:50.200,0:02:52.140
# 滿滿的一鍋
One whole, full pot

0:02:59.040,0:03:01.480
# 你看  開始慢慢開裂啦
Look! They’re cracking open now, slowly.

0:03:12.720,0:03:13.980
# 這個要煮熟啦
It’s done now.

0:03:20.520,0:03:22.500
# 像這個要用那個水沖一下啊
It’s like, they need to be rinsed for a while.

0:03:32.400,0:03:36.180
# 好啦 洗乾淨啦 要把它全部捏碎來
Alright! It’s clean now. I need to smash them all.

0:03:44.780,0:03:47.960
# 你看  這個酸棗就這橏把它捏出來的哦  這個
Look! The hog plums need to be squeezed out, you know. Squeeze like this.

0:03:48.580,0:03:49.740
# 一擠就擠出來啦
A single squeeze is enough.

0:03:50.440,0:03:53.420
# 你看  快裝不下啦
Look! It can’t take anymore.

0:03:54.320,0:03:56.460
# 但是也快沒啦  就那麼一丟丟啦
But we are done anyway. Just a tiny little bit remains.

0:03:56.460,0:03:59.860
# 這個要攪拌一下  把那個籽要把它去掉
It needs to be stirred, so as to remove the seeds.

0:04:00.800,0:04:03.160
# 這個酸棗把它做了自己吃的哦
The hog plums rolls are for yourselves only.

0:04:03.940,0:04:07.120
# 就沒那麼講究  本來買了那個一次性手套的
So we can take it easy. In fact I’ve already order the disposable gloves.

0:04:09.680,0:04:12.240
# 資還沒到  但是我急著想吃
The delivery has not yet arrived. But I’m craving for the rolls.

0:04:14.080,0:04:15.000
# 就先做了
So I’m making it now.

0:04:33.400,0:04:35.600
# 你看  越搓它越漂亮
Look! Punching it makes it look prettier.

0:04:37.080,0:04:38.300
# 啊  看這個
Ah! Have a look at this one.

0:04:41.300,0:04:42.440
# 還要繼續搓
I still need to keep punching it.

0:04:44.320,0:04:45.720
# 這是純手工的哦
It’s hundred percentage handmade, you know,

0:04:46.800,0:04:48.040
# 沒有任何添加
without any additives.

0:04:55.820,0:04:58.080
# 你看  這個就有點像豬油一樣
Look! It now looks a little bit like lard.

0:04:59.340,0:05:02.760
# 這全是果肉哦  就把果肉把取出來了
This is all pulp. The pulp is now extracted.

0:05:03.800,0:05:06.040
# 然後我給你放南瓜  下給它拌一下
Then I’ll put some pumpkins, and mix with it.

0:05:06.560,0:05:07.620
# 因為這個太少啦
Cuz it’s too little here.

0:05:08.180,0:05:08.940
# 不夠吃的
It’s not enough.

0:05:10.320,0:05:13.680
# 就這樣一點樹枝樹葉沒事的  樹枝樹葉也可以吃
Here are some branches and leaves. No worries. They cause no harms.

0:05:15.480,0:05:18.260
# 那個酸棗太少啦  我摘個攀蒲來湊一下
There are too few hog plums. I’m gonna pick a pumpkin to make up the portion.

0:05:18.520,0:05:20.400
# 湊一下就多  肉多一點嘛
So that we have more, something more to eat.

0:05:21.120,0:05:22.200
# 不然不夠吃啊
It’s not enough otherwise.

0:05:23.960,0:05:25.040
# 剛好一個攀蒲
A pumpkin is right here.

0:05:26.540,0:05:27.660
# 哎呀  這把刀
Aya! This knife.

0:05:29.020,0:05:31.360
# 你看  剛剛好啊  這個小攀蒲
Look! It’s perfect, this little pumpkin.

0:05:32.000,0:05:33.860
# 全部削進去一蒸它就可以啦
Cut the whole thing into pieces, steam it, and it’s done.

0:05:45.980,0:05:47.420
# 這是老攀蒲哦
This is an old pumpkin.

0:05:48.380,0:05:50.260
# 雖然個子小  但是它很老
Though it’s small, it’s very old.

0:06:14.660,0:06:17.320
# 要把它劈開哦  把裡面的籽去掉
I gotta cut it open, and take away all the seeds inside.

0:06:20.880,0:06:22.700
# 你看 裡面的籽要把它拿掉
Look! The seeds inside need to be taken away.

0:06:23.620,0:06:25.220
# 不拿掉的話就會有籽
There would be seeds otherwise.

0:06:27.600,0:06:28.800
# 切小片一點
Let me cut it into smaller pieces.

0:06:34.660,0:06:37.180
# 好啦  等下我就洗乾淨
Alright! I’ll wash it in a while,

0:06:37.180,0:06:40.260
# 就用那個  鍋蒸一下  把它蒸熟了之後
and then you know, steam it in the cooker. After steaming it,

0:06:40.800,0:06:42.680
# 就跟那個酸棗榚的那個
I’ll mix it with the, you know,

0:06:43.620,0:06:44.400
# (就跟那個 酸棗糕的) [SIC] 那個囊
the dough, of the hog plum rolls.

0:06:45.200,0:06:47.160
# 一起攪拌一下
Mix them all together.

0:06:51.380,0:06:54.240
# 好啦  放鍋里面蒸
Alright! Steam it in the cooker.

0:06:54.480,0:06:56.020
# 把這個攀蒲
The pumpkin,

0:06:57.280,0:06:58.400
# 像這樣放就可以了
simply put it here.

0:07:00.100,0:07:01.220
# 把它蒸熟來
Steam it until it becomes soft.

0:07:04.540,0:07:06.540
# 好  還有一點  給你來煮一下
Alright! Here’s still a bit. Cook it as well.

0:07:08.080,0:07:09.320
# 哇  熟啦熟啦
Wa! It’s done it’s done!

0:07:16.120,0:07:19.780
# 來  把這個攀蒲搞下去 直接這樣放下去
C’mon! Let me put in the pumpkin. Just put it in right away.

0:07:20.860,0:07:24.680
# 全部都已經爛啦  已經煮爛啦
It’s already smashed. It has already been softened.

0:07:29.040,0:07:31.640
# 加點糖  來  全部一拱  拱下來
Put some sugar. C’mon! Pour it in, everything.

0:07:32.680,0:07:35.080
# 搞多點糖  甜一點更好
We need a bit more sugar, the sweeter the better.

0:07:40.520,0:07:44.000
# 你看  加點葡萄糖  這是攝影小哥兒子吃的葡萄糖
Look! Put some glucose powder. This is taken from Mr. Cameraman’s son.

0:07:44.340,0:07:44.960
# 多搞點  
Put more.

0:07:45.660,0:07:47.000
# 到時候我填一點給他
I’ll refill it for him.

0:07:49.080,0:07:50.300
# 好啦好啦  可以
Alright, alright. Okay!

0:07:56.800,0:07:57.840
# 這樣可以了
It's alright now.

0:08:00.680,0:08:01.320
# 夠靚
Beautiful, isn’t it?

0:08:02.900,0:08:04.580
# 還是  繼續攪拌
Then, keep on stirring.

0:08:06.320,0:08:07.740
# 你看  先吃一點
Look! Let me try a bit first.

0:08:10.220,0:08:12.140
# 嗯  可以哦
Um! Not bad.

0:08:13.320,0:08:15.640
# 酸酸甜甜的  曬乾了更好吃
Sweet and sour. It would taste even better when it’s dried.

0:08:18.460,0:08:22.980
# 可以  哇  直的可以哦  很不錯
Not bad! Wa! It’s really nice. Really not bad.

0:08:23.460,0:08:24.120
# 那種
It’s like,

0:08:26.280,0:08:28.480
# 又有酸味又有甜味又有南瓜味
sweetness and sourness, combined with the taste of pumpkins,

0:08:29.640,0:08:31.440
# 還有那個lian ma gai (南酸棗)的味道
and also the, the taste of hog plums.

0:08:35.100,0:08:37.480
# 好啦 準備烤它
Alright! Let’s bake it.

0:08:37.740,0:08:39.100
# 這種天氣  本來要曬的
This weather… It should be dried under the sun, in fact.

0:08:40.020,0:08:42.200
# 沒辦法曬  只能烤了
But it’s now impossible. We can only bake it.

0:08:52.420,0:08:55.740
# 哇  這樣差不多可以啦  讓它慢慢這樣子烤
Alright! It’s almost done. Bake it here, slowly.

0:09:17.420,0:09:19.460
# 你看  現在越來越漂亮啦
Look! It's becoming prettier every second.

0:09:22.660,0:09:23.420
# 黃黃的
Golden brown

0:09:24.520,0:09:25.780
# 上面都已經乾啦
The surface is already dried.

0:09:27.560,0:09:28.680
# 還要再烤一下
But it still needs to be baked for a while.

0:09:36.020,0:09:37.860
# 你看  可以吃了哦
Look! It’s alright now.

0:09:39.480,0:09:43.520
# 嗯~太好吃啦  因為還沒乾 再烤一下才行
Um~ Delicious! It still needs to be baked, cuz it’s still not completely dried.

0:09:44.020,0:09:45.040
# 因為天色已晚
I mean, cuz it’s late now.

0:09:46.540,0:09:47.900
# 酸棗糕就這樣做的
That’s how hog plum rolls are made.

0:09:49.300,0:09:52.580
# 要吃把它切成一條一條  要烤很久的
It needs to be cut into stripes before they can be eaten. It needs to be baked for a very long time.

0:09:53.320,0:09:54.420
# 第三次
The third day

0:09:54.420,0:09:58.220
# 昨天沒烤乾  今天烤了一天才把它烤乾
We couldn't completely dry it yesterday. We've been baking it for a whole day today before it becomes dry.

0:09:58.220,0:09:59.280
# 我要把它切到來
So I’m now cutting it up.

0:10:04.000,0:10:06.600
# 切這個的時候要放點那個葡萄糖粉
I need some, some glucose powder when I’m cutting it.

0:10:09.680,0:10:11.500
# 把它抺一下 這樣就不會粘
Spray it here. So that the dough won’t stick.

0:10:16.700,0:10:18.820
# 你看  首先切一小塊
Look! I cut a small piece first.

0:10:19.960,0:10:22.380
# 這樣  再把它們抺上葡萄糖
And then, spray some glucose powder on it.

0:10:23.140,0:10:25.240
# 抺上葡萄糖其實就是沒那麼粘啦
In fact that’s to prevent it from being too sticky.

0:10:26.280,0:10:28.240
# 你看  現在就好多啦  這樣
Look! It’s so much better now.

0:10:34.800,0:10:36.480
# 再搞一點葡萄糖
Put some more glucose powder.

0:10:38.200,0:10:41.940
# 這樣  撈一下  撈一下  就這是一條一條啦
Then, stir them, stir them and now they they’re stripes.

0:10:45.840,0:10:49.580
# 你看  這就是酸棗糕  切的時候還沒  還不是很乾
Look! These are hog plum rolls. It was not, not really that dry when I was cutting it.

0:10:50.480,0:10:52.060
# 要再烤乾一些  你看
It should have been baked a bit longer, look!

0:10:53.800,0:10:55.760
# 嗯~可以哦
Um! Not bad.

0:10:56.540,0:10:59.180
# 真的  很不錯
Seriously, really nice.

0:11:02.820,0:11:04.800
# 這就是 酸棗糕
This is called, hog plum roll.

0:11:05.280,0:11:08.280
# 你看  這個一條一條的可以把它裝到罐子裡面去
Look! These stripes can be put into a jar.

0:11:08.280,0:11:10.520
# 到時候想吃的時候就拿幾個來吃
We can just take some whenever we want them.

0:11:12.020,0:11:14.480
# 到時候有粉絲來了就可以給他(她)們吃
Or we can serve our fans when they visit us.

0:11:14.940,0:11:16.220
# 很好吃的這個
It’s really tasty, you know.

0:11:17.820,0:11:19.400
# 如果烤乾一點的話就很好
It would be even better if they’re baked longer.

0:11:20.480,0:11:24.600
# 那個 就會火  火燒啦  本來用太陽曬最好的
I mean, it would be burnt however. The best is drying under the sun, in fact.

0:11:32.640,0:11:36.180
# 你看  很溧亮了吧  有點像了哦
Look! It’s pretty, isn’t it? It looks the authentic ones.

0:11:36.840,0:11:39.440
# 放在這裡吃就可以啦  幾天就把它吃完啦
Just leave it here, it’s fine. They will be gone in a few days.

0:11:42.120,0:11:44.940
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.

0:11:47.080,0:11:49.100
# 這罐小罐的就送給攝影小哥吃
This small jar is for Mr. Cameraman.
