### ISSUE TITLE
[雪鱼] 江苏阳春面 - https://youtu.be/UQmmM0n5wQk

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#1521]
**视频链接**：https://youtu.be/UQmmM0n5wQk

# 请翻译以下全部内容

```


字幕
1
00:00:01,920 --> 00:00:06,040
江苏·高邮

2
00:00:15,560 --> 00:00:19,040
雪鱼现在在扬州高邮 今天的天气真的是特别好

3
00:00:19,040 --> 00:00:24,360
待会呢 我要去吃一碗这边比较特色的早餐 阳春面

4
00:00:24,360 --> 00:00:27,000
阳春面可不是说是高邮独有的

5
00:00:27,000 --> 00:00:29,880
像扬州 上海 也是比较常见的

6
00:00:29,880 --> 00:00:32,120
那高邮的阳春面做的这么出名

7
00:00:32,120 --> 00:00:35,280
在做法和味道上 肯定会有自己独特的地方

8
00:00:35,280 --> 00:00:37,080
走 去尝尝吧

9
00:00:46,920 --> 00:00:52,000
看这个搪瓷碗 这家老店的感觉就出来了

10
00:00:52,600 --> 00:00:54,840
面馆里有个特别的现象就是

11
00:00:54,840 --> 00:00:59,440
要把摞在一起的搪瓷碗 一个个地散落在锅里

12
00:00:59,640 --> 00:01:03,760
这边有两口锅 这口大锅里 每次能放十多个碗

13
00:01:03,760 --> 00:01:06,360
碗漂浮在上面 就像小船一样

14
00:01:06,360 --> 00:01:11,280
然后就在这种飘零的状态下 里面会放上各种的佐料

15
00:01:15,320 --> 00:01:17,960
阿姨 这个碗为什么要漂在上面

16
00:01:17,960 --> 00:01:20,600
它这个

17
00:01:20,840 --> 00:01:22,520
我讲话你懂吗

18
00:01:22,520 --> 00:01:24,240
听得懂 听得懂

19
00:01:24,240 --> 00:01:27,160
因为澄一下子 它的味道就是不同

20
00:01:27,160 --> 00:01:31,160
它澄一下的话 味道是浓的

21
00:01:31,160 --> 00:01:35,160
不澄的话 像这一个

22
00:01:40,040 --> 00:01:44,760
给你看一下 这个是没有澄的

23
00:01:45,600 --> 00:01:50,320
这一个蘸料跟这个蘸料比一下子

24
00:01:51,080 --> 00:01:54,800
哦 蘸料就融合了

25
00:01:54,800 --> 00:01:57,440
对 它的味道也不同

26
00:01:59,720 --> 00:02:04,320
这里面调料放的有猪油 酱油 这个是虾籽吗

27
00:02:04,320 --> 00:02:08,560
是的 虾籽

28
00:02:08,560 --> 00:02:10,080
就这几种简单的

29
00:02:15,400 --> 00:02:16,400
6种佐料

30
00:02:18,240 --> 00:02:23,680
猪油 酱油 虾籽

31
00:02:23,680 --> 00:02:27,200
味精 胡椒 香葱

32
00:02:28,680 --> 00:02:33,160
阿姨就是很热情 你不和她说话 她也会想办法和你聊天的

33
00:02:34,080 --> 00:02:36,360
到现在 聊了老半天都没有吃饭呢

34
00:02:36,360 --> 00:02:39,080
我就点一个大家最常点的阳春面

35
00:02:39,080 --> 00:02:43,000
然后再加一个1块5的水煮蛋

36
00:02:45,840 --> 00:02:47,920
这边的座位真的是很紧张

37
00:02:47,920 --> 00:02:51,640
等了好久才找的这么一个座位坐下

38
00:02:52,800 --> 00:02:56,560
对比我以前吃的阳春面 都是把面条浸在汤里

39
00:02:56,560 --> 00:02:59,000
它这碗 底料只是浅浅的一层

40
00:02:59,000 --> 00:03:01,440
它的汤很少  胡椒味特浓郁

41
00:03:02,840 --> 00:03:04,960
就像干拌面一样

42
00:03:13,000 --> 00:03:18,880
它这个面条是又细 又顺滑 还有很大的韧劲

43
00:03:19,680 --> 00:03:21,680
味道是全在汤里的

44
00:03:21,680 --> 00:03:26,680
这个虾籽酱油就是提供这种又香 又鲜的味道

45
00:03:33,680 --> 00:03:37,920
你看 早晨来吃饭 一般会点阳春面的人比较多

46
00:03:37,920 --> 00:03:42,840
逐渐到了中午 到了晚上呢 来点小馄饨的人就更多了

47
00:03:42,840 --> 00:03:46,320
这个小馄饨 是受过汪曾祺老先生赞许的

48
00:03:46,840 --> 00:03:49,280
说它家的红汤馄饨 皮薄馅多

49
00:03:49,280 --> 00:03:52,960
猪肉馅中夹有少量的竹笋 蘑菇 菌类

50
00:03:52,960 --> 00:03:55,720
吃完还会让人满口余香

51
00:04:03,560 --> 00:04:08,320
阿姨 您的馄饨已经被写进文章里了 知道吧

52
00:04:11,120 --> 00:04:13,600
很出名了

53
00:04:26,120 --> 00:04:27,920
这个店开了很多年了吧

54
00:04:27,920 --> 00:04:31,320
二十年了

55
00:04:31,320 --> 00:04:35,040
哦 三十年了

56
00:04:40,760 --> 00:04:43,960
我今年六十五了

57
00:05:00,640 --> 00:05:05,160
背景音乐：
Visionaries - 浮世绘歌舞升平
三澤康広 - つんつんけんけん
Deep East Music - Made This To Lift You
Fresh_Fallen_Snow11

58
00:05:05,160 --> 00:05:08,200
关 注
雪 鱼  探 店


```

**Comment by shuaisoserious** [comment]
认领

**Comment by shuaisoserious** [comment]
字幕
1
00:00:01,920 --> 00:00:06,040
江苏·高邮
Gaoyou, Jiangsu
2
00:00:15,560 --> 00:00:19,040
雪鱼现在在扬州高邮 今天的天气真的是特别好
Xueyu is now in Gaoyou, Yangzhou. Today’s weather is really good.
3
00:00:19,040 --> 00:00:24,360
待会呢 我要去吃一碗这边比较特色的早餐 阳春面
I will have a bowl of special breakfast called Yangchun noodles later
4
00:00:24,360 --> 00:00:27,000
阳春面可不是说是高邮独有的
Yangchun noodles are not unique in Gaoyou
5
00:00:27,000 --> 00:00:29,880
像扬州 上海 也是比较常见的
Which are pretty common in Yangzhou, Shanghai too
6
00:00:29,880 --> 00:00:32,120
那高邮的阳春面做的这么出名
Gaoyou’s Yangchun noodles are so famous 
7
00:00:32,120 --> 00:00:35,280
在做法和味道上 肯定会有自己独特的地方
So it definitely have it’s own unique way in terms of cook and taste
8
00:00:35,280 --> 00:00:37,080
走 去尝尝吧
Let’s check it out
9
00:00:46,920 --> 00:00:52,000
看这个搪瓷碗 这家老店的感觉就出来了
Look at this enamel bowl, it make me feel like a old restaurant
10
00:00:52,600 --> 00:00:54,840
面馆里有个特别的现象就是
A special phenomenon in the noodle restaurant is 
11
00:00:54,840 --> 00:00:59,440
要把摞在一起的搪瓷碗 一个个地散落在锅里
The stacked enamel bowls are scattered one by one in the pot
12
00:00:59,640 --> 00:01:03,760
这边有两口锅 这口大锅里 每次能放十多个碗
There is two pots here and there are more than ten bowls in each pot 
13
00:01:03,760 --> 00:01:06,360
碗漂浮在上面 就像小船一样
The bowl floats on the pot like a boat
14
00:01:06,360 --> 00:01:11,280
然后就在这种飘零的状态下 里面会放上各种的佐料
There will be various condiments while it in this floating state
15
00:01:15,320 --> 00:01:17,960
阿姨 这个碗为什么要漂在上面
Auntie, why does this bowl float on it?
16
00:01:17,960 --> 00:01:20,600
它这个
It is
17
00:01:20,840 --> 00:01:22,520
我讲话你懂吗
Can you understand me?
18
00:01:22,520 --> 00:01:24,240
听得懂 听得懂
Yeah, yeah
19
00:01:24,240 --> 00:01:27,160
因为澄一下子 它的味道就是不同
Because it tastes different 
20
00:01:27,160 --> 00:01:31,160
它澄一下的话 味道是浓的
It taste stronger after 
21
00:01:31,160 --> 00:01:35,160
不澄的话 像这一个
If you don’t, it will be like this
22
00:01:40,040 --> 00:01:44,760
给你看一下 这个是没有澄的
I will show you, this is before
23
00:01:45,600 --> 00:01:50,320
这一个蘸料跟这个蘸料比一下子
Compare the two
24
00:01:51,080 --> 00:01:54,800
哦 蘸料就融合了
Oh, condiments are mixed
25
00:01:54,800 --> 00:01:57,440
对 它的味道也不同
Yeah, it also taste different
26
00:01:59,720 --> 00:02:04,320
这里面调料放的有猪油 酱油 这个是虾籽吗
There are lard and soy sauce in the seasoning. Is this shrimp roe?
27
00:02:04,320 --> 00:02:08,560
是的 虾籽
yeah
28
00:02:08,560 --> 00:02:10,080
就这几种简单的
Just these
29
00:02:15,400 --> 00:02:16,400
6种佐料
Six condiments
30
00:02:18,240 --> 00:02:23,680
猪油 酱油 虾籽
Lard, soy sauce, shrimp roe
31
00:02:23,680 --> 00:02:27,200
味精 胡椒 香葱
MSG, Pepper, green onion
32
00:02:28,680 --> 00:02:33,160
阿姨就是很热情 你不和她说话 她也会想办法和你聊天的
Auntie is very enthusiastic. If you don’t talk to her, she will find a way to talk to you.
33
00:02:34,080 --> 00:02:36,360
到现在 聊了老半天都没有吃饭呢
We are talking for very long time until now and I haven’t eaten yet
34
00:02:36,360 --> 00:02:39,080
我就点一个大家最常点的阳春面
I will order the Yang Chun noodles that everyone orders most often
35
00:02:39,080 --> 00:02:43,000
然后再加一个1块5的水煮蛋
Then add 1.5 yuan boiled egg
36
00:02:45,840 --> 00:02:47,920
这边的座位真的是很紧张
It’s hard to find a seat 
37
00:02:47,920 --> 00:02:51,640
等了好久才找的这么一个座位坐下
We just sit after that long time waiting
38
00:02:52,800 --> 00:02:56,560
对比我以前吃的阳春面 都是把面条浸在汤里
Compared to the Yangchun noodles I had before, they all dip the noodles in the soup
39
00:02:56,560 --> 00:02:59,000
它这碗 底料只是浅浅的一层
There’s just a very thin layer of mixed condiments at the bottom of this bowl
40
00:02:59,000 --> 00:03:01,440
它的汤很少  胡椒味特浓郁
Just a little of soup with a strong flavor of pepper
41
00:03:02,840 --> 00:03:04,960
就像干拌面一样
Like dry mixed noodles
42
00:03:13,000 --> 00:03:18,880
它这个面条是又细 又顺滑 还有很大的韧劲
Its noodles are thin, smoothy and have very tender
43
00:03:19,680 --> 00:03:21,680
味道是全在汤里的
The taste is all in the soup
44
00:03:21,680 --> 00:03:26,680
这个虾籽酱油就是提供这种又香 又鲜的味道
This shrimp roe soy sauce provides fragrant and fresh taste
45
00:03:33,680 --> 00:03:37,920
你看 早晨来吃饭 一般会点阳春面的人比较多
You see, there are more people ordering Yangchun noodles in the morning as their breakfast
46
00:03:37,920 --> 00:03:42,840
逐渐到了中午 到了晚上呢 来点小馄饨的人就更多了
Gradually it’s noon, and more people come to order small wontons at the night
47
00:03:42,840 --> 00:03:46,320
这个小馄饨 是受过汪曾祺老先生赞许的
This small wonton was praised by Mr. Wang Zengqi
48
00:03:46,840 --> 00:03:49,280
说它家的红汤馄饨 皮薄馅多
He said its red soup wonton has a thin skin and a lot of stuffing inside
49
00:03:49,280 --> 00:03:52,960
猪肉馅中夹有少量的竹笋 蘑菇 菌类
There are a small amount of bamboo shoots, mushrooms and fungi in the pork filling
50
00:03:52,960 --> 00:03:55,720
吃完还会让人满口余香
After eating, it will leave full of fragrance in your mouth
51
00:04:03,560 --> 00:04:08,320
阿姨 您的馄饨已经被写进文章里了 知道吧
Auntie, your wonton has been written in the article, right?
52
00:04:11,120 --> 00:04:13,600
很出名了
Pretty famous
53
00:04:26,120 --> 00:04:27,920
这个店开了很多年了吧
This restaurant has been open for many years, right
54
00:04:27,920 --> 00:04:31,320
二十年了
About 20 years
55
00:04:31,320 --> 00:04:35,040
哦 三十年了
Oh 30 years
56
00:04:40,760 --> 00:04:43,960
我今年六十五了
I am sixty-five this years old
57
00:05:00,640 --> 00:05:05,160
背景音乐：
Visionaries - 浮世绘歌舞升平
三澤康広 - つんつんけんけん
Deep East Music - Made This To Lift You
Fresh_Fallen_Snow11

58
00:05:05,160 --> 00:05:08,200
关 注
雪 鱼  探 店
