### ISSUE TITLE
[华农兄弟] 华农兄弟去兄弟家抓羊发现他还养了很多牛路上还长了很奇形怪状的野果 - https://youtu.be/yMIWaDHkEH4

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1541]
https://youtu.be/yMIWaDHkEH4
<p>&#35270;&#39057;&#21457;&#24067;&#20110; October 4, 2020 at 11:30AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/yMIWaDHkEH4

#Huanong Brothers: Catch a goat from buddy. He has a lot of cattle. Many funny wild fruits too!
#Huanong Brothers: We catch a goat from our buddy. He has a lot of cattle as well. We also see a lot of funny wild fruits on the way.

0:00:00.291,0:00:01.675
# 你看 兄弟家的牛
Look! My buddy’s cattle.

0:00:02.170,0:00:04.204
# 那麼多  要發財啦
So many! It’s a great fortune!

0:00:05.844,0:00:06.663
# 過去看一下
Let’s go and have a look.

0:00:17.038,0:00:19.243
# 哇  好多小牛哇  好小的
Wa! A lot of calves, really small ones

0:00:26.796,0:00:28.094
# 這條肚子那麼大
Why does this one have such a big belly?

0:00:30.249,0:00:32.198
# 你看  這小牛很聽話的哦
Look! This calf is really nice, you know.

0:00:32.799,0:00:34.046
# 來 摸一下
C’mon! Let me touch you!

0:00:35.745,0:00:36.427
# 它不肯
It doesn’t want it.

0:00:36.899,0:00:37.838
# 不肯讓我摸
It doesn’t want my touch.

0:00:38.121,0:00:39.727
# 那麼 牛頭哦  那條
That one, the Alpha, that one.

0:00:40.250,0:00:43.020
# 那條是  看到沒有 就那條  那條就是公牛
That one is… See? The one right over there, that one is a bull,

0:00:43.672,0:00:44.577
# 最大的一條
the biggest one.

0:00:45.637,0:00:46.627
# 全部都是它老婆
These are all its wives.

0:00:48.485,0:00:50.194
# 這小的  好可愛這小的哦
This small one, this small one is really cute, you know.

0:00:51.283,0:00:54.275
# 兄弟又在下面那一點  不然抱一條就可以走啦
My buddy is down there. Otherwise, I can simply take one and run away.

0:00:55.958,0:00:58.112
# 好小啊  應該一百斤都不到
It’s so small. I think it’s not even fifty kilograms.

0:00:59.072,0:01:01.791
# 那條  那條牛在那裡抓癢癢
That one, that one is scratching its itchy skin.

0:01:01.791,0:01:03.603
# 誒  一說它它就不抓啦
Ey? It stops once I mention it.

0:01:04.274,0:01:04.974
# 一起抓
C'mon! Scratch together!

0:01:20.073,0:01:21.491
# 這條怎麼那麼像我的呢
Why does this one look like me so much?

0:01:24.935,0:01:28.458
# 你看  這條  這條就是公牛來的  最大條
Look! This one, this one is a bull. It’s the biggest.

0:01:29.120,0:01:31.308
# 哇  這肯定最少能賣一萬多塊錢
Wa! I am sure that it is worth at least ten thousand RMB.

0:01:33.202,0:01:34.210
# 一身都是肉
It’s so meaty.

0:01:34.817,0:01:38.391
# 那脖子上這一坨  全是瘦肉來的  這一坨  供起來的
That part on the neck, is all lean meat. That part, the wedging part

0:01:41.255,0:01:41.920
# 過來
Come here!

0:01:43.698,0:01:44.894
# 這條小牛還在吃奶
The calf is still having milk.

0:01:46.202,0:01:47.004
# 好不好吃
Does it taste good?

0:01:49.859,0:01:50.359
# 過來
Come here!

0:01:54.402,0:01:55.102
# 給你吃
It’s for you.

0:01:55.895,0:01:56.440
# 要不要
You want it?

0:01:58.915,0:01:59.666
# 它不要
No, it doesn’t.

0:02:00.696,0:02:02.747
# 它們都吃飽啦  吃的肚子好大
They’ve all eaten a lot. Their bellies are all that big now.

0:02:03.474,0:02:05.115
# 等下我去抓隻羊回來
Let me catch a goat in a while.

0:02:06.294,0:02:08.842
# 這個牛就  摸都摸不到  抓不到的
The cattle, well, I can’t even touch them, let alone catching them.

0:02:09.442,0:02:10.586
# 去抓兄弟家的羊
Let me catch my buddy’s goat.

0:02:12.868,0:02:14.149
# 你看  今年的野果
Look! The wild fruits this year,

0:02:14.643,0:02:15.411
# 好多哦
are plentiful!

0:02:15.636,0:02:16.866
# 這個是野杮子
These are wild persimmons.

0:02:17.313,0:02:19.399
# 這產量太高啦  可能長得比較瘦
The yield is too high. So they might be a bit skinny,

0:02:20.077,0:02:21.239
# 像個橄欖果一樣
just like olives.

0:02:21.617,0:02:23.634
# 營養  供給不足
They don’t have, enough nutrition.

0:02:24.715,0:02:27.142
# 兩邊都有哇  這兩棵樹雙胞胎
They’re growing on both sides. These two trees are twin.

0:02:28.555,0:02:30.658
# 這都壞了一些  一些都壞掉啦
Some are rotten, some are rotten here.

0:02:31.019,0:02:31.582
# 黑啦
They’re black.

0:02:36.594,0:02:37.567
# 你看  這個
Look! This is,

0:02:38.497,0:02:39.470
# 這個是那個
this is, well...

0:02:40.045,0:02:40.676
# 叫甚麼
How is it called?

0:02:41.505,0:02:44.224
# 就是牛哇  羊很喜歡吃葉子的這個
It’s like, the cattle, the goats like its leaves a lot.

0:02:44.382,0:02:45.749
# 豬仔也特別喜歡吃它的葉子
The piggies also like its leaves.

0:02:46.308,0:02:47.452
# 但我就不知道它叫甚麼
But I have no ideas how it is called.

0:02:47.521,0:02:48.255
# 嗯 長的
Um. It’s sort of like,

0:02:48.605,0:02:50.622
# 像一條毛毛蟲一樣  那麼大條
just like a caterpillar. So big

0:02:52.716,0:02:56.016
# 太大啦  羊吃不到  吃得到的話葉子全部都被它們吃光啦
It’s too big. The goats can’t eat it. Otherwise, all leaves would have been eaten.

0:02:56.846,0:02:58.589
# 這個不知道是花 還是果
Well, I don’t know whether they’re flowers, or fruits.

0:02:59.683,0:03:01.666
# 這個小辣條  小辣條一樣
It’s like “latiao” (lit: spicy stripes, local snacks), just like “latiao”.

0:03:06.918,0:03:10.047
# 這個我們這邊叫香藤子  它的藤子是香的
Look! It is called “xiang tengzi” (lit: fragrant branches, valeria) here. Its branches have a fragrant scent.

0:03:10.250,0:03:11.343
# 它叫香藤子
So it’s called “xiang tengzi”.

0:03:11.721,0:03:13.858
# 你看  這種都可以吃啦  這種
Look! These are edible, these fruits.

0:03:14.129,0:03:16.266
# 是啊  只是不是很熟而已
Yup! They’re just not really that ripe.

0:03:16.478,0:03:18.632
# 但是不影響它的口感
But the texture is not affected.

0:03:19.700,0:03:21.341
# 你看  這個果肉  你看
Look! The pulp… Look!

0:03:22.102,0:03:24.068
# 哦  全部都熟啦
Oh! They're all ripe.

0:03:25.375,0:03:26.468
# 先下手為強
The first-mover gains the advantage.

0:03:27.160,0:03:28.887
# 等下兄弟過來啦  全部把它摘光
My buddy's gonna pick everything when he comes in a while.

0:03:32.265,0:03:35.206
# 嗯  紅的  看到沒有  這種
Um! It’s red. See? This one

0:03:36.097,0:03:37.070
# 很好吃的哦
It’s really tasty, you know.

0:03:40.677,0:03:42.780
# 今年夠多  今年一樹都是
There are a lot this year. They’re all over the tree.

0:03:49.319,0:03:51.918
# 這籽不能吃的這籽  要把它吐出來喲
The seeds are not edible. You gotta spit them out.

0:03:53.210,0:03:54.354
# 現在還不是很熟
They are not really that ripe at this moment.

0:03:55.346,0:03:57.654
# 再過一個禮拜左右就過來  就可以摘啦
Come again in a week. We can pick by then.

0:03:58.996,0:04:00.876
# 一個禮拜就整個都是紅的啦
They'll become all red in a week.

0:04:02.314,0:04:03.989
# 我現在摘的時候都挑一點這個
Now I pick only those, I mean,

0:04:04.376,0:04:06.102
# 紅的就摘  不紅的我都不摘
only the red ones, but not the green ones.

0:04:13.103,0:04:13.785
# 搞幾個
Let me pick some.

0:04:14.584,0:04:15.831
# 搞幾個回去就好啦
Just a few back home would be enough.

0:04:16.219,0:04:17.398
# 這還不是很熟
They are still not that ripe.

0:04:18.671,0:04:21.236
# 把那個紅一點的把它摘掉就好啦
I just pick those which are red,

0:04:22.138,0:04:25.028
# 不怎麼紅的就放在這裡  讓它更紅更好吃
and leave the greener ones here. Let them become tastier when they become red.

0:04:51.201,0:04:53.526
# 不了雨  現在車都上不來啦
It has rained. The car can’t go up here.

0:04:53.596,0:04:56.263
# 這有黃泥在這裡  不然一下子就可以上的去啦
Here’s mud on the path. Otherwise the car can go all the way up.

0:04:56.343,0:04:58.446
# 上次我們都是一路直上
That’s what we did last time.

0:05:00.671,0:05:01.600
# 我們走路進去啦
We gottta walk.

0:05:02.195,0:05:04.144
# 上面一個很紅的那個香藤子哦
There’s a very red “xiang tengzi” up there.

0:05:11.343,0:05:12.676
# 直接把這個竹子砍掉
I need to chop down this bamboo right away,

0:05:12.879,0:05:15.273
# 才能  拿得到  要不拿不到的
so that, I can take it. Otherwise I can’t take it.

0:05:16.801,0:05:18.613
# 這根竹子   它本來就死的
This bamboo, it’s already dead actually.

0:05:19.070,0:05:20.591
# 我把它砍下來而已
I just chop it down.

0:05:26.799,0:05:28.046
# 我把這個藤子要砍掉
These branches need to be chopped away as well.

0:05:28.696,0:05:30.000
# 不砍掉的話它下不來
Otherwise they’re not coming down.

0:05:30.410,0:05:32.730
# 砍掉之後 它明年長得更茂盛的哦  這個
They’re gonna grow even better next year, after chopping it away, you know.

0:05:42.857,0:05:43.420
# 是不是
Am I right?

0:05:44.300,0:05:46.865
# 明年長得  明年這裡可以長出新枝出來
Next week, new branches are gonna grow here next year.

0:05:47.279,0:05:48.000
# 更好看
It will look even better.

0:05:48.563,0:05:50.597
# 你看  哎呀  這棵
Look! Aya. This one

0:05:51.325,0:05:52.333
# 漂亮吧  這棵
It’s pretty, isn’t it? This one

0:05:56.110,0:05:57.000
# 看一下熟了沒有
Let me see if it is ripe.

0:05:59.318,0:05:59.915
# 嗯
Um!

0:06:02.656,0:06:03.544
# 沒熟  這個
It's not yet ripe, this one.

0:06:04.464,0:06:05.232
# 再嘗一個
Let me try another one.

0:06:11.693,0:06:12.581
# 不是很熟
It’s not really that ripe.

0:06:18.240,0:06:19.641
# 它慢慢 慢慢就熟啦
It’s getting ripe, slowly, and gradually.

0:06:23.638,0:06:24.355
# 下雨天
Cuz it rains,

0:06:26.552,0:06:27.799
# 味道沖淡啦
so the flavour is washed away.

0:06:29.368,0:06:31.402
# 這個 很甜的
It should be, really sweet.

0:06:36.155,0:06:37.847
# 還有一個  剩下的給你啦
Here’s still a little bit. The rest is yours.

0:06:48.961,0:06:50.773
# 你看  這裡有一顆
Look! Here's a…

0:06:51.282,0:06:52.735
# 我們這邊叫蓮麻拐
It’s called “lian ma gai” (hog plum) here.

0:06:53.208,0:06:55.140
# 又大又黃哦  又個蓮麻拐
It’s big and brown, this “lian ma gai”.

0:06:55.536,0:06:57.331
# 因為它生在深山裡面
Cuz it’s growing deep in the mountain.

0:06:58.211,0:07:01.854
# 所以它  沒人  很少人  很少進  很少人進來這裡
So it’s, nobody, few people, seldom, people seldom come it.

0:07:03.711,0:07:04.547
# 嗯
Um~

0:07:06.351,0:07:07.102
# 好香啊
It smells so good.

0:07:07.361,0:07:08.813
# 你看 現在都下雨啦
Look! It’s raining now.

0:07:09.000,0:07:11.566
# 我去他那個 羊棚裡面躲一下雨
Let’s go to his, well, his goat shed and take a shelter here.

0:07:12.488,0:07:14.146
# 要不然就被濕身的
Otherwise, we’ll all get soaked.

0:07:19.958,0:07:21.410
# 這兄弟做的路哦
This path was built by my buddy.

0:07:23.725,0:07:24.835
# 那麼多草
So many weeds.

0:07:44.801,0:07:47.212
# 現在只能蹲在這裡啦  這裡才能躲雨
Now I can only stay here. It’s the only shelter.

0:07:47.522,0:07:48.769
# 等雨停了 我再回去
When the rain stops, we'll go back,

0:07:49.399,0:07:50.492
# 順便牽一條羊
taking a goat with us.

0:07:51.442,0:07:52.689
# 鏈條我都帶好啦
I’m even coming with a chain.

0:07:52.942,0:07:53.642
# 放在這裡
Let me put it here,

0:07:54.395,0:07:55.591
# 這刀也放在這裡
and the knife as well.

0:07:57.281,0:07:59.931
# 你看  下好大雨哦  回不去啦
Look! The rain is so heavy. We can’t get back now.

0:08:00.512,0:08:02.529
# 我要等雨停哦 雨停啦
We gotta wait until the rain stops. We can’t go back,

0:08:03.189,0:08:04.179
# 才能回得去
before the rain stops.

0:08:08.072,0:08:09.251
# 這百香果都還沒熟
These passion fruits are all not yet ripe.

0:08:10.299,0:08:11.273
# 都是青的
They’re all still green.

0:08:12.203,0:08:13.159
# 下吧  下吧
C’mon! Keep raining!

0:08:13.512,0:08:14.776
# 下多大我都不要緊
I don’t care at all.

0:08:15.213,0:08:17.812
# 上面有羊 下面有雞  這還有百香果
There are goats up there, chickens down there, and also passion fruits here.

0:08:19.457,0:08:20.653
# 這裡還有大米喲
Here’s rice as well!

0:08:22.198,0:08:23.360
# 大米放在這裡
The rice is here.

0:08:24.850,0:08:27.261
# 不走啦  今天晚上 要再下大一點
We not leaving, not leaving tonight, if it rain gets worse.

0:08:29.214,0:08:31.094
# 柴火又有 全是現成的
Here’s also firewood. Everything is ready here,

0:08:32.283,0:08:33.530
# 而且有新鮮的
and everything is fresh.

0:08:36.104,0:08:39.439
# 你看  那個羊  肚子餓啦  兄弟都不來放
Look! That goat, is starving now. My buddy is not taking them out.

0:08:39.634,0:08:42.507
# 現在都不午兩三點鐘啦  它還不來放
It’s almost three in the afternoon now, but he’s still not taking them out.

0:08:43.274,0:08:45.206
# 餓的它都把頭伸出來
It’s so hungry that it’s peeping out.

0:08:54.169,0:08:56.922
# 你看  今天增加了好多小羊啊
Look! Here are a lot of kids this year.

0:08:56.923,0:08:58.153
# 看到沒  小羔羊
See? The small kids.

0:08:59.437,0:09:00.667
# 搞一條漂亮一點的
Let me get a prettier one,

0:09:01.142,0:09:01.790
# 回去
and take it back home.

0:09:03.631,0:09:04.313
# 聽說
I’ve heard that,

0:09:04.824,0:09:06.122
# 看好多都被閹掉啦
many have already been neutered.

0:09:15.309,0:09:16.145
# 過來  過來  過來
Come here, come here, come here!

0:09:17.555,0:09:18.055
# 過來
Come here!

0:09:18.573,0:09:19.073
# 過來
Come here!

0:09:38.401,0:09:39.135
# 就這隻 
Alright! This one!

0:09:40.004,0:09:41.491
# 你看  這個毛好靚啊
Look! Its coat is really beautiful!

0:09:42.109,0:09:42.997
# 發亮的毛
Shiny coat

0:09:43.081,0:09:44.037
# 去我家啦
Go home with me.

0:09:44.341,0:09:45.212
# 給你發老婆
I’ll give you wives.

0:09:45.828,0:09:46.528
# 兩個哦
Not one but two!

0:10:15.201,0:10:16.671
# 叫他們兩個枱回去
I ask these two guys to carry it back.

0:10:19.314,0:10:20.219
# 刀放著
Put the knife here.

0:10:23.430,0:10:24.000
# 刀
Knife?

0:10:24.000,0:10:24.509
# 是
Yup

0:10:24.646,0:10:25.190
# 不用放
No need

0:11:15.962,0:11:16.918
# 放下來 放下來
Put it down, put it down

0:11:17.100,0:11:17.680
# 放下來是吧
Put it down?

0:11:17.680,0:11:18.180
# 嗯
Um

0:11:19.757,0:11:20.679
# 喂 狗
Hey! Dog!

0:11:26.563,0:11:27.126
# 狗
Dog!

0:11:28.553,0:11:29.903
# 這怎麼有一個耳朵
Why is here an ear?

0:11:30.533,0:11:31.387
# 小耳朵
A tiny ear

0:11:34.455,0:11:36.780
# 咩  去  找你姐姐去
Meh~ Go! Meet your big sisters.

0:11:37.548,0:11:38.048
# 走
Go!

0:11:39.381,0:11:40.543
# 走  走
Go! Go!

0:11:40.851,0:11:41.927
# 上面很好玩的
It’s a lot of fun up there.

0:11:42.160,0:11:43.339
# 你有伴在那裡
You'll have your companions there!

0:11:51.411,0:11:52.641
# 誒  快點
Ey! Hurry up!

0:11:52.932,0:11:53.751
# 不認識嗎
Don’t you know them?

0:11:58.921,0:11:59.706
# 咩
Meh~

0:12:01.232,0:12:01.811
# 咩
Meh~

0:12:06.081,0:12:08.013
# 把它放啦  跑它們在一起就好啦
I'm gonna release it. Let them mingle together. It will be fine.

0:12:09.631,0:12:10.947
# 嘿  不聽話是不是
Heh! Naughty, aren’t you?

0:12:13.344,0:12:14.642
# 我是把它(你)放啦
I’m just trying to release you!

0:12:22.359,0:12:23.178
# 好 可以
Good! Alright!

0:12:24.301,0:12:25.531
# 快 跟它們在一起
C’mon! Go and join them!

0:12:27.359,0:12:28.230
# 兩個人打它
They both beat it!

0:12:35.325,0:12:35.888
# 狗
Dog!

0:12:37.981,0:12:39.930
# 它現在就熟悉啦  跟這兩條羊
It’s starting to know them, these two goats.

0:12:40.914,0:12:43.770
# 兩個你的姐姐哦  這個  跟它們在一起啊
They’re your big sisters. Come and stay with them, alright?

0:12:47.695,0:12:48.343
# 它在幹嘛
What is it doing?

0:12:53.035,0:12:54.145
# 你看  它們三個人
Look! All three of them.

0:12:54.726,0:12:55.734
# 全在一起玩啦
are together now.

0:12:56.401,0:12:58.213
# 不用管的  它們慢慢會回來的
Leave them alone. They’ll be coming back in a while.

0:13:04.320,0:13:07.676
# 我們商量了一下 把那隻羊給它取一個名字
We’ve agreed, to give that goat a name.

0:13:08.087,0:13:10.036
# 它的名字就叫作羊肉包
His name is, Lamb Bun.

0:13:11.881,0:13:12.940
# 它在上面  跑啦
He has run away, up there now.

0:13:15.361,0:13:17.173
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.

0:13:17.683,0:13:19.136
# 我拿點東西來餵一下它
Let me get something to feed him.

**Comment by vincenthychow** [comment]
已發佈
