### ISSUE TITLE
[雪鱼] 扬州早茶 - https://youtu.be/q3jGtmjZph4

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#1543]
**视频链接**：https://youtu.be/q3jGtmjZph4

# 请翻译以下全部内容

```

字幕
1
00:00:02,004 --> 00:00:04,004
早茶   江苏 扬州 

2
00:00:05,600 --> 00:00:09,520
在扬州 有句话叫做“”

3
00:00:09,520 --> 00:00:13,120
这个皮包水 就是指的它的早茶

4
00:00:13,120 --> 00:00:14,400
雪鱼现在在扬州

5
00:00:14,400 --> 00:00:17,920
怎么能错过扬州这种特色的饮食文化呢

6
00:00:17,920 --> 00:00:19,480
走 跟着我去看看吧

7
00:00:29,879 --> 00:00:31,879
朝哪里走呢？ 

8
00:00:43,080 --> 00:00:45,720
到哪里点餐呢    到27号桌点餐

9
00:00:56,360 --> 00:00:59,720
上一桌的顾客刚离开
桌布还没来得及铺好

10
00:00:59,720 --> 00:01:03,080
上一桌的顾客刚离开
桌布还没来得及铺好

11
00:01:06,360 --> 00:01:07,640
现在是来的比较早吗

12
00:01:07,640 --> 00:01:10,440
很多的老人家都是围坐着一个大桌

13
00:01:10,440 --> 00:01:13,000
大家热热闹闹地在这边喝早茶

14
00:01:13,000 --> 00:01:16,960
他们点了好多糕点 光小蒸笼都有那么高

15
00:01:16,960 --> 00:01:20,080
我觉得 他们光吃糕点就能吃到中午

16
00:01:20,080 --> 00:01:23,920
因为我是第一次过来 来的时候给了一个小牌子

17
00:01:23,920 --> 00:01:27,080
就是这个小牌子 它上面有二维码

18
00:01:27,080 --> 00:01:30,800
早上应该按小牌子上的二维码点餐

19
00:01:30,800 --> 00:01:34,440
但是我扫了它桌子上的二维码

20
00:01:34,440 --> 00:01:37,720
然后被告知桌子上的二维码是中餐 晚餐用的

21
00:01:37,720 --> 00:01:39,880
早上扫它是不下单的

22
00:01:39,880 --> 00:01:43,120
现在的情况就是我们点了老半天的菜 不上菜

23
00:01:43,120 --> 00:01:44,960
我们要再重新下单

24
00:01:44,960 --> 00:01:49,240
而和我们同时来的另一桌  他们已经吃上了

25
00:01:49,240 --> 00:01:51,640
我们点餐的过程很艰难

26
00:01:51,640 --> 00:01:54,320
现在呢 点了有蒸饺

27
00:01:54,320 --> 00:01:59,280
蟹黄汤包 他们这边的蟹黄汤包是很出名的 带汤的

28
00:01:59,280 --> 00:02:02,960
还有呢 就是松籽烧麦 三丁包 千层油糕

29
00:02:02,960 --> 00:02:06,880
听说 它这个千层油糕有64层 看一看

30
00:02:06,880 --> 00:02:10,320
还有这边比较出名的烫干丝

31
00:02:10,320 --> 00:02:12,400
最后呢 还要了一壶的绿茶

32
00:02:12,400 --> 00:02:14,480
好了 下单了

33
00:02:14,480 --> 00:02:16,880
现在是89块钱

34
00:02:18,320 --> 00:02:20,280
OK了

35
00:02:46,040 --> 00:02:49,720
这个就是扬州早茶当中最特色的 烫干丝

36
00:02:49,720 --> 00:02:52,280
我点的这个是小份的 12块钱

37
00:02:52,280 --> 00:02:56,040
看着就是酱油的颜色 闻着还有香油的味道

38
00:02:56,040 --> 00:02:58,960
看着浓油赤酱的样子 会觉得它很咸

39
00:02:58,960 --> 00:03:02,760
尝一尝是不是和自己想的（味道）是一样的

40
00:03:13,840 --> 00:03:16,160
一点都不会觉得咸

41
00:03:16,160 --> 00:03:19,360
但是香油的味道确实是很重的

42
00:03:19,360 --> 00:03:22,520
烫干丝啊烫干丝 就是用白豆腐干

43
00:03:22,520 --> 00:03:25,680
切成丝 然后在沸水当中烫完

44
00:03:25,680 --> 00:03:28,840
再加上虾米 酱油等来调味

45
00:03:35,120 --> 00:03:38,400
干丝吃起来是既细又柔软

46
00:03:43,520 --> 00:03:45,680
蟹黄汤包

47
00:03:49,640 --> 00:03:53,440
哦 给了一个吸管

48
00:03:54,000 --> 00:03:56,840
用筷子一敲 就觉得它肯定是个水货（肚里有汤）

49
00:03:56,840 --> 00:04:00,080
里面的汤 很多啊

50
00:04:00,080 --> 00:04:01,674
用筷子一敲

51
00:04:01,674 --> 00:04:05,558
啊 汤出来了

52
00:04:06,360 --> 00:04:10,520
我不是故意的 我只是想敲一敲它

53
00:04:10,520 --> 00:04:13,240
正常应该是用吸管 戳个洞

54
00:04:13,240 --> 00:04:14,880
然后吸着汤汁来吃的

55
00:04:14,880 --> 00:04:18,000
但是 我刚才用筷子 我只是想动一动它 然后

56
00:04:18,000 --> 00:04:20,080
它的汤汁就全出来了

57
00:04:20,080 --> 00:04:22,400
现在 我就是被迫要先吃它了

58
00:04:25,040 --> 00:04:29,520
哎呀 这么吃着 感觉幸福感就降低了很多

59
00:04:34,320 --> 00:04:39,600
我把吸管插到了汤包的面皮上了 根本就吸不上来

60
00:04:39,880 --> 00:04:40,880
这是翻车事件

61
00:04:40,880 --> 00:04:46,480
它这个就是鸡汤和蟹黄 融合在一起的感觉

62
00:04:46,480 --> 00:04:47,672
吃起来有点腥味

63
00:04:48,120 --> 00:04:50,680
我本来为它准备了很多的台词

64
00:04:50,680 --> 00:04:53,160
和它搭配着要演很多的戏

65
00:04:53,160 --> 00:04:56,600
现在呢 它只能被迫离场了

66
00:05:15,680 --> 00:05:19,080
这一拿上来就是能够闻到很重的面香

67
00:05:19,080 --> 00:05:22,760
这一笼呢 就是两个千层油糕

68
00:05:22,760 --> 00:05:25,240
蒸饺 一个单独的豆沙包

69
00:05:25,920 --> 00:05:28,960
我还有一笼 这一笼一共有两种

70
00:05:28,960 --> 00:05:31,200
一个是松子烧麦

71
00:05:31,200 --> 00:05:33,640
能够看到里面（冒出头）的糯米

72
00:05:33,640 --> 00:05:35,640
这个呢 就是三丁包

73
00:05:35,640 --> 00:05:38,080
这次我是点了三丁包 没有点五丁

74
00:05:38,080 --> 00:05:43,440
五丁呢 就是在三丁包的基础上会增加虾丁还有参丁

75
00:05:44,520 --> 00:05:48,120
能够看到里面 鸡肉丁 笋丁还有猪肉丁

76
00:05:48,120 --> 00:05:52,840
它的外皮特别暄软 里面的肉汤 已经浸入到面皮当中了

77
00:05:52,840 --> 00:05:56,200
吃起来就是咸当中还有一些甜味

78
00:05:56,200 --> 00:05:58,800
还有笋丁脆脆的口感

79
00:06:11,720 --> 00:06:17,600
它这个就是 每层之间 会有这个糖油层

80
00:06:17,600 --> 00:06:21,800
上面加了一些青红丝 这么点缀着就是更加好看一些

81
00:06:26,120 --> 00:06:28,600
糖的味道还是很突出的

82
00:06:28,600 --> 00:06:32,600
它的甜 没有让你觉得很油腻

83
00:06:32,600 --> 00:06:36,680
吃起来也是这种很松软 很暄软的口感

84
00:06:41,240 --> 00:06:44,200
本来一口是放不下的

85
00:06:44,200 --> 00:06:47,160
但是 里面有很多的空隙

86
00:06:47,160 --> 00:06:50,120
一口就可以吃掉很大一块的千层油糕

87
00:07:04,760 --> 00:07:08,600
你看 我今天点的蟹黄汤包 还有三丁包是有点油的

88
00:07:08,600 --> 00:07:11,720
而像千层油糕 是有点甜的

89
00:07:11,720 --> 00:07:14,160
但不管是油腻 还是甜腻

90
00:07:14,160 --> 00:07:17,080
都可以喝杯茶解腻

91
00:07:18,560 --> 00:07:23,440
还有 我今天来吃早茶的地方 是很金碧辉煌的

92
00:07:23,440 --> 00:07:26,400
这一层 有几十张桌子

93
00:07:26,400 --> 00:07:28,280
来的时候 都坐得满满的

94
00:07:28,280 --> 00:07:32,120
不过 如果我们的座位被安排到窗边会更好

95
00:07:32,120 --> 00:07:34,360
它那边的窗户都是落地的

96
00:07:34,360 --> 00:07:36,480
可以看到外面的景色

97
00:07:36,480 --> 00:07:39,320
这种的感觉 才是最好的吧

98
00:07:42,640 --> 00:07:46,240
来到扬州的早茶店 我才知道 原来茶叶是可以自带的

99
00:07:46,240 --> 00:07:49,640
很多人呢 就是拿着自己的小水杯 里面放着茶叶

100
00:07:49,640 --> 00:07:51,240
用这边的开水

101
00:07:51,240 --> 00:07:53,560
再点个小点心就可以了

102
00:07:53,600 --> 00:07:55,600
下次 我也要试一试

103
00:08:01,520 --> 00:08:05,600
在扬州 走着走着就能发现 一汪清水 还有一个小亭子

104
00:08:05,600 --> 00:08:10,600
清水里面有花草 就会显得周围的环境格外雅致

105
00:08:20,680 --> 00:08:23,680
      关  注
雪 鱼  探 店


```

**Comment by little-helping-hand** [comment]
认领

**Comment by little-helping-hand** [comment]
早茶是Dim sum, 不是morning tea。

**Comment by immoonancient** [comment]
> 早茶是Dim sum, 不是morning tea。

频道方提供了视频标题简介的翻译，如果有误的话，这种情况下建议把他们提供的翻译修改一遍，一并在这里提交了

**Comment by little-helping-hand** [comment]
字幕
1
00:00:02,004 --> 00:00:04,004
早茶   江苏 扬州 

Dim sum, Yangzhou, Jiangsu.

2
00:00:05,600 --> 00:00:09,520
在扬州 有句话叫做“”

In Yangzhou, there is a saying ‘ 

3
00:00:09,520 --> 00:00:13,120
这个皮包水 就是指的它的早茶

This ‘Pi Bao Shui’ (consommé wrapped in pastry) means Dim sum.

4
00:00:13,120 --> 00:00:14,400
雪鱼现在在扬州

Xue Yu is in Yangzhou.

5
00:00:14,400 --> 00:00:17,920
怎么能错过扬州这种特色的饮食文化呢

How can I miss this unique YangZhou food tasting opportunity?

6
00:00:17,920 --> 00:00:19,480
走 跟着我去看看吧

Let’s go and take a look.

7
00:00:29,879 --> 00:00:31,879
朝哪里走呢？ 

Where is the entrance?

8
00:00:43,080 --> 00:00:45,720
到哪里点餐呢    到27号桌点餐
Where could I place the order? Table number 27 please.

9
00:00:56,360 --> 00:00:59,720
上一桌的顾客刚离开

Previous diners just left. 

10
00:00:59,720 --> 00:01:03,080
桌布还没来得及铺好

The table is not ready yet.

11
00:01:06,360 --> 00:01:07,640
现在是来的比较早吗

Is it still early (for dim sum)?

12
00:01:07,640 --> 00:01:10,440
很多的老人家都是围坐着一个大桌

Many old folks sit around a big table.

13
00:01:10,440 --> 00:01:13,000
大家热热闹闹地在这边喝早茶

They are enjoying dim sum here.

14
00:01:13,000 --> 00:01:16,960
他们点了好多糕点 光小蒸笼都有那么高

They’ve ordered many dim sums. Look at the height of those bamboo steamers.

15
00:01:16,960 --> 00:01:20,080
我觉得 他们光吃糕点就能吃到中午

I guess they don’t need anything else until lunch time.

16
00:01:20,080 --> 00:01:23,920
因为我是第一次过来 来的时候给了一个小牌子

Since my first time here, I was given a card.

17
00:01:23,920 --> 00:01:27,080
就是这个小牌子 它上面有二维码

This one, with a QR code.

18
00:01:27,080 --> 00:01:30,800
早上应该按小牌子上的二维码点餐

I should have placed the order with this QR code in the morning.

19
00:01:30,800 --> 00:01:34,440
但是我扫了它桌子上的二维码

But I scanned the QR code on the table instead.

20
00:01:34,440 --> 00:01:37,720
然后被告知桌子上的二维码是中餐 晚餐用的

Then I was told that the QR code on the table is for lunch and dinner only.

21
00:01:37,720 --> 00:01:39,880
早上扫它是不下单的

You cannot use it for breakfast.

22
00:01:39,880 --> 00:01:43,120
现在的情况就是我们点了老半天的菜 不上菜

Now, it’s like nothing have shown up despite we placed an order ages ago.

23
00:01:43,120 --> 00:01:44,960
我们要再重新下单

We need to place an order again.

24
00:01:44,960 --> 00:01:49,240
而和我们同时来的另一桌  他们已经吃上了

Another table got their meal already despite we all arrived at the same time.

25
00:01:49,240 --> 00:01:51,640
我们点餐的过程很艰难

Order processing is very slow.

26
00:01:51,640 --> 00:01:54,320
现在呢 点了有蒸饺

Now. Here are steamed dumplings.

27
00:01:54,320 --> 00:01:59,280
蟹黄汤包 他们这边的蟹黄汤包是很出名的 带汤的

Crab meat consommé in a bun. This place is renowned for this dish. It comes in consommé.

28
00:01:59,280 --> 00:02:02,960
还有呢 就是松籽烧麦 三丁包 千层油糕

And, Siu Mai with pine nuts, steamed buns with three fillings, steamed layer cake.

29
00:02:02,960 --> 00:02:06,880
听说 它这个千层油糕有64层 看一看

I heard there are 64 layers in steamed layer cake. Take a look.

30
00:02:06,880 --> 00:02:10,320
还有这边比较出名的烫干丝

And a well-known dish, dried bean curd threads in consommé.

31
00:02:10,320 --> 00:02:12,400
最后呢 还要了一壶的绿茶

Finally, a pot of green tea!

32
00:02:12,400 --> 00:02:14,480
好了 下单了

Well, order is placed.

33
00:02:14,480 --> 00:02:16,880
现在是89块钱

It’s RMB89.

34
00:02:18,320 --> 00:02:20,280
OK了

35
00:02:46,040 --> 00:02:49,720
这个就是扬州早茶当中最特色的 烫干丝

This is the most unique dish in Yangzhou’s dim sums, dried bean curd threads in consommé.

36
00:02:49,720 --> 00:02:52,280
我点的这个是小份的 12块钱

I ordered a small portion, RMB12.

37
00:02:52,280 --> 00:02:56,040
看着就是酱油的颜色 闻着还有香油的味道

The colour looks like soy sauce. It also smells sesame oil. 

38
00:02:56,040 --> 00:02:58,960
看着浓油赤酱的样子 会觉得它很咸

By the look of it, it may be quite salty.

39
00:02:58,960 --> 00:03:02,760
尝一尝是不是和自己想的（味道）是一样的

See what it tastes like…

40
00:03:13,840 --> 00:03:16,160
一点都不会觉得咸

It’s not salty at all!

41
00:03:16,160 --> 00:03:19,360
但是香油的味道确实是很重的

But there is a strong hint of sesame oil.

42
00:03:19,360 --> 00:03:22,520
烫干丝啊烫干丝 就是用白豆腐干

Dried bean curd threads in consommé. It threads white 

43
00:03:22,520 --> 00:03:25,680
切成丝 然后在沸水当中烫完

dry bean curd, then blanch them in boiling water. 

44
00:03:25,680 --> 00:03:28,840
再加上虾米 酱油等来调味

Season with dried shrimps, soy sauce and other ingredients.

45
00:03:35,120 --> 00:03:38,400
干丝吃起来是既细又柔软

Texture is so fine and soft.

46
00:03:43,520 --> 00:03:45,680
蟹黄汤包

Crab meat consommé in a bun.

47
00:03:49,640 --> 00:03:53,440
哦 给了一个吸管

A straw.

48
00:03:54,000 --> 00:03:56,840
用筷子一敲 就觉得它肯定是个水货（肚里有汤）

Tap it with a chopstick. There must be consommé inside.

49
00:03:56,840 --> 00:04:00,080
里面的汤 很多啊

So much!

50
00:04:00,080 --> 00:04:01,674
用筷子一敲

Tap, tap.

51
00:04:01,674 --> 00:04:05,558
啊 汤出来了

Oops, it leaked.

52
00:04:06,360 --> 00:04:10,520
我不是故意的 我只是想敲一敲它

I didn’t do it on purpose. I just want to tap it.

53
00:04:10,520 --> 00:04:13,240
正常应该是用吸管 戳个洞

Usually you use straw to poke a hole,

54
00:04:13,240 --> 00:04:14,880
然后吸着汤汁来吃的

then suck the consommé out.

55
00:04:14,880 --> 00:04:18,000
但是 我刚才用筷子 我只是想动一动它 然后

But I only touched it with chopsticks, and

56
00:04:18,000 --> 00:04:20,080
它的汤汁就全出来了

the consommé all come out.

57
00:04:20,080 --> 00:04:22,400
现在 我就是被迫要先吃它了

Now, I have to eat it first.

58
00:04:25,040 --> 00:04:29,520
哎呀 这么吃着 感觉幸福感就降低了很多

Hmmm, this way has much less fun of enjoyment.

59
00:04:34,320 --> 00:04:39,600
我把吸管插到了汤包的面皮上了 根本就吸不上来

My straw sticks inside the pastry. I cannot suck it up!

60
00:04:39,880 --> 00:04:40,880
这是翻车事件

This is a disaster!

61
00:04:40,880 --> 00:04:46,480
它这个就是鸡汤和蟹黄 融合在一起的感觉

It feels like the combination of chicken stock and crab meat.

62
00:04:46,480 --> 00:04:47,672
吃起来有点腥味

It tastes a bit of fishy.

63
00:04:48,120 --> 00:04:50,680
我本来为它准备了很多的台词

Originally, I had a lot to say.

64
00:04:50,680 --> 00:04:53,160
和它搭配着要演很多的戏

And expect a lot of fun with it.

65
00:04:53,160 --> 00:04:56,600
现在呢 它只能被迫离场了

Now, it is done and dusted.

66
00:05:15,680 --> 00:05:19,080
这一拿上来就是能够闻到很重的面香

The fragrance of steamed flour is so strong.

67
00:05:19,080 --> 00:05:22,760
这一笼呢 就是两个千层油糕

There are two steamed layer cakes in the steamer.

68
00:05:22,760 --> 00:05:25,240
蒸饺 一个单独的豆沙包

Steamed dumplings. An individual red bean paste bun.

69
00:05:25,920 --> 00:05:28,960
我还有一笼 这一笼一共有两种

Here is another one. There are two varieties.

70
00:05:28,960 --> 00:05:31,200
一个是松子烧麦

One is Siu Mai with pine nuts.

71
00:05:31,200 --> 00:05:33,640
能够看到里面（冒出头）的糯米

You can see the gluten rice coming out on the top.

72
00:05:33,640 --> 00:05:35,640
这个呢 就是三丁包

This one is buns with three fillings.

73
00:05:35,640 --> 00:05:38,080
这次我是点了三丁包 没有点五丁

I ordered three fillings instead of five this time.

74
00:05:38,080 --> 00:05:43,440
五丁呢 就是在三丁包的基础上会增加虾丁还有参丁

Five fillings will have additional diced shrimps and sea cucumber.

75
00:05:44,520 --> 00:05:48,120
能够看到里面 鸡肉丁 笋丁还有猪肉丁

You can see there are diced chicken, bamboo shoots and pork inside.

76
00:05:48,120 --> 00:05:52,840
它的外皮特别暄软 里面的肉汤 已经浸入到面皮当中了

The bun is extremely soft. The pastry is soaked with juice.

77
00:05:52,840 --> 00:05:56,200
吃起来就是咸当中还有一些甜味

There is a hint of sweetness in this savoury dish.

78
00:05:56,200 --> 00:05:58,800
还有笋丁脆脆的口感

And the taste of crunchiness from bamboo shoots.

79
00:06:11,720 --> 00:06:17,600
它这个就是 每层之间 会有这个糖油层

There is a coating of sugar and oil mixture between each layer.

80
00:06:17,600 --> 00:06:21,800
上面加了一些青红丝 这么点缀着就是更加好看一些

It is topped with some finely sliced green and red peppers. The dressing makes it more attractive.

81
00:06:26,120 --> 00:06:28,600
糖的味道还是很突出的

Sugar taste is particularly strong.

82
00:06:28,600 --> 00:06:32,600
它的甜 没有让你觉得很油腻

It is sweet, but not sickening.

83
00:06:32,600 --> 00:06:36,680
吃起来也是这种很松软 很暄软的口感

The feeling is soft and moist.

84
00:06:41,240 --> 00:06:44,200
本来一口是放不下的

It looks too big for a mouthful.

85
00:06:44,200 --> 00:06:47,160
但是 里面有很多的空隙

But it is very light.

86
00:06:47,160 --> 00:06:50,120
一口就可以吃掉很大一块的千层油糕

You can bite a big chunk off.

87
00:07:04,760 --> 00:07:08,600
你看 我今天点的蟹黄汤包 还有三丁包是有点油的

The crab meat consommé bun and buns with three fillings are savoury.

88
00:07:08,600 --> 00:07:11,720
而像千层油糕 是有点甜的

Whereas layered cake is sweet.

89
00:07:11,720 --> 00:07:14,160
但不管是油腻 还是甜腻

Whether it is savoury or sweet,

90
00:07:14,160 --> 00:07:17,080
都可以喝杯茶解腻

can all be washed done with a cup of cha!

91
00:07:18,560 --> 00:07:23,440
还有 我今天来吃早茶的地方 是很金碧辉煌的

Anyway, I came to a resplendent and magnificent place for dim sum today.

92
00:07:23,440 --> 00:07:26,400
这一层 有几十张桌子

There are dozens of tables on this floor.

93
00:07:26,400 --> 00:07:28,280
来的时候 都坐得满满的

It was full when I came.

94
00:07:28,280 --> 00:07:32,120
不过 如果我们的座位被安排到窗边会更好

It would be nice if we could sit next to the windows.

95
00:07:32,120 --> 00:07:34,360
它那边的窗户都是落地的

They are all French windows.

96
00:07:34,360 --> 00:07:36,480
可以看到外面的景色

You can view outside.

97
00:07:36,480 --> 00:07:39,320
这种的感觉 才是最好的吧

The dining experience would be brilliant!

98
00:07:42,640 --> 00:07:46,240
来到扬州的早茶店 我才知道 原来茶叶是可以自带的

After dim sum, I just realised that I could bring my own tea leaves here.

99
00:07:46,240 --> 00:07:49,640
很多人呢 就是拿着自己的小水杯 里面放着茶叶

Many diners carry their own little cups with tea leaves inside.

100
00:07:49,640 --> 00:07:51,240
用这边的开水

The restaurant provides boiling water.
101
00:07:51,240 --> 00:07:53,560
再点个小点心就可以了

All they need is a few dim sums.

102
00:07:53,600 --> 00:07:55,600
下次 我也要试一试

I want to try it next time as well.

103
00:08:01,520 --> 00:08:05,600
在扬州 走着走着就能发现 一汪清水 还有一个小亭子

In Yangzhou, you can frequently find a small pond and a small pavilion during your walk about.

104
00:08:05,600 --> 00:08:10,600
清水里面有花草 就会显得周围的环境格外雅致

The flowers and plants in the pond give the surrounding a more elegant feel.

105
00:08:20,680 --> 00:08:23,680
      关  注
雪 鱼  探 店

Be sure to follow China Food Travel

**Comment by little-helping-hand** [comment]
Dear editor, 

**I trust you will find the following introduction is an improvement on original version which filled with inaccurate wordings that against the spirit of translation in English. I believe my version represents a better understanding in the eyes of English speaking viewers. Thank you.**

Locals in Yangzhou recommended dim sum as my breakfast. At 7 o’clock in the morning, I arrived at this restaurant. It is a magnificent building with elegant fixture and fittings. It is already packed with people come for dim sum, and nearly all the tables are full. A waiter greeted me with a warm welcome and found me a table. The table is spotless clean. With more than 100 choices of dim sum, I finally can have anything I want here. 

I ordered a crab meat consommé in steamed bun, a steamed bun with three fillings, siu mai with pine nuts, thousand layered cake, dried bean curd threads in consommé and a pot of tea. It only costed me RMB89! There were many old folks having dim sum as their breakfast here. I felt that I shared the same relaxing mentality of Yangzhou people after having my breakfast.
