### ISSUE TITLE
[老饭骨]煎烹鸡肉串 - https://youtu.be/K95brJD1fns

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1548]
**视频链接**：https://youtu.be/K95brJD1fns

如果 YouTube 链接无法访问，请参考抖音链接： https://v.douyin.com/JyYaXUV/

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【國宴大師•煎烹鸡肉串】家常版鸡肉串，外焦里嫩、简单健康，有平底锅就能做！|老飯骨

简介
大家好，老饭骨为大家上菜咯！今天带来一道家常版煎烹鸡肉串。
除了做鸡肉串，小友们还可以用这个方法做羊肉串、牛肉串、大虾串，一通百通！
这样做出来的鸡肉串，外面焦香，鸡肉细嫩；这道菜做法也非常简单，家里有平底锅就能做！这道菜的亮点在辣酱油的香气一直拖着整个菜肴，味道浓郁！
小友们快试试看，在家也能快乐地撸串！

字幕
1
00:00:00,000 --> 00:00:02,960
烹 这汁里边是没有芡的

2
00:00:03,080 --> 00:00:04,440
煎烹鸡肉串

3
00:00:04,560 --> 00:00:08,600

4
00:00:08,600 --> 00:00:09,920
你看这有一签子

5
00:00:09,920 --> 00:00:12,360
这签子有将近五十年了 

6
00:00:12,360 --> 00:00:13,560
这是个老物件

7
00:00:13,560 --> 00:00:16,440
鸡腿肉 先搁点淀粉上浆了

8
00:00:16,440 --> 00:00:18,600
你怎么先搁淀粉啊

9
00:00:18,600 --> 00:00:19,840
都是一样的

10
00:00:19,840 --> 00:00:22,040
鸡蛋

11
00:00:22,040 --> 00:00:27,720
搁点酱油 冰糖老抽 盐 胡椒粉 黄酒

12
00:00:27,720 --> 00:00:29,600
这料就放完了 接着放香油

13
00:00:29,600 --> 00:00:33,880
这料都给它上齐了 已经上劲了

14
00:00:33,880 --> 00:00:37,080
香油 放香油吧 让我给说着了吧

15
00:00:37,080 --> 00:00:40,200
二伯说得非常准

16
00:00:40,200 --> 00:00:43,120
你看这个鸡丁都是现成的

17
00:00:43,120 --> 00:00:44,280
我们给它串好了

18
00:00:44,280 --> 00:00:46,280
不串直接煎也行

19
00:00:46,280 --> 00:00:49,320
到时候咱们把葱姜蒜搁到小料里

20
00:00:49,320 --> 00:00:52,320
煎呢 你要把葱姜蒜搁这里头

21
00:00:52,320 --> 00:00:54,080
一会一煎全是黑渣子

22
00:00:54,080 --> 00:00:57,200
这是真正传统菜 四五十年了

23
00:00:57,200 --> 00:00:58,520
这是个老菜

24
00:00:58,520 --> 00:01:03,720
煎烹牛肉串 煎烹鸡肉串 煎烹羊肉串

25
00:01:03,720 --> 00:01:06,400
什么都能煎 还能煎烹虾

26
00:01:06,400 --> 00:01:10,680
煎烹有各种煎烹的方法

27
00:01:10,680 --> 00:01:13,920
一种像辣酱油的 还有茄汁的

28
00:01:13,920 --> 00:01:16,920
还有一种柠檬汁的

29
00:01:16,920 --> 00:01:19,360
还有糖醋汁的

30
00:01:19,360 --> 00:01:22,200
各种的口味都有所不同

31
00:01:22,200 --> 00:01:25,840

32
00:01:25,840 --> 00:01:28,040
现在味道是丰富多彩

33
00:01:28,040 --> 00:01:30,520
煎烹就是锅里边的油要少

34
00:01:30,520 --> 00:01:36,000
把东西煎到外焦里嫩 然后再烹

35
00:01:36,000 --> 00:01:39,680
但是它没有完全熟 没有完全入味

36
00:01:39,680 --> 00:01:42,320
我们要靠外来的一些调味

37
00:01:42,320 --> 00:01:43,600
给它做一个补充

38
00:01:43,600 --> 00:01:44,920
所以叫煎烹

39
00:01:44,920 --> 00:01:46,560
你看过去有煎烹鱼片

40
00:01:46,560 --> 00:01:49,560
煎烹鸡球 虾球

41
00:01:49,560 --> 00:01:52,200
关键是它的调味汁和原料不同

42
00:01:52,200 --> 00:01:55,160
有的是酸辣的 有时候是咸鲜的

43
00:01:55,160 --> 00:01:57,960
有的是糖醋的

44
00:01:57,960 --> 00:02:01,160
好了 真快 先烧锅

45
00:02:01,160 --> 00:02:05,920
在烧锅的同时 咱把这汁调好 番茄酱

46
00:02:05,920 --> 00:02:08,000
这个辣酱油是上海梅林的

47
00:02:08,000 --> 00:02:11,160
这个是最古老的一种调味汁

48
00:02:11,160 --> 00:02:13,520
咸鲜 微辣

49
00:02:13,600 --> 00:02:15,800
另外它有里边有一个特殊的香味

50
00:02:15,800 --> 00:02:18,000

51
00:02:18,000 --> 00:02:22,160
黄酒 冰糖老抽

52
00:02:22,160 --> 00:02:23,320
搁点糖

53
00:02:23,320 --> 00:02:27,240
再来点胡椒粉

54
00:02:27,240 --> 00:02:30,880
你看这个过程特别简单

55
00:02:30,880 --> 00:02:33,000
好了

56
00:02:33,000 --> 00:02:35,560
煎烹啊 朝辉看啊

57
00:02:35,560 --> 00:02:38,080
一个一个往里搁

58
00:02:38,080 --> 00:02:41,760
别摞着 摞着煎不了了

59
00:02:41,760 --> 00:02:42,120

60
00:02:42,120 --> 00:02:45,200
一煎熟了 好看吧

61
00:02:45,200 --> 00:02:48,680
煎出来的菜是干香 焦香

62
00:02:48,680 --> 00:02:52,000
这就好了 还没完全熟

63
00:02:52,000 --> 00:02:53,840

64
00:02:53,840 --> 00:02:56,040
往这一放 这菜好看吧

65
00:02:56,040 --> 00:02:58,400
还没烹汁呢 一烹汁更好看

66
00:02:58,400 --> 00:03:00,600
来点底油 小料

67
00:03:00,600 --> 00:03:03,920
汁儿一烹这菜就齐活

68
00:03:03,920 --> 00:03:06,840

69
00:03:06,840 --> 00:03:08,640
烹 不勾芡

70
00:03:08,640 --> 00:03:13,080
烹 这汁里边是没有芡的

71
00:03:13,080 --> 00:03:15,600
辣酱油的香味出来了

72
00:03:15,600 --> 00:03:19,000
香气灼人 火力稍微欠点儿

73
00:03:19,000 --> 00:03:21,360

74
00:03:21,360 --> 00:03:23,600
大爷翻的这两下

75
00:03:23,600 --> 00:03:24,800

76
00:03:25,440 --> 00:03:27,520
好啦 铲子

77
00:03:27,760 --> 00:03:28,640

78
00:03:28,640 --> 00:03:31,720
这都不用搁装饰 就这样挺好看的

79
00:03:31,720 --> 00:03:33,000
大爷把过去的老菜

80
00:03:33,000 --> 00:03:34,680
一个一个都展示出来了

81
00:03:34,680 --> 00:03:36,880
让你流口水

82
00:03:36,880 --> 00:03:38,240
因为它是有油

83
00:03:38,240 --> 00:03:40,120
我们拿锡纸给它包一下把儿

84
00:03:40,120 --> 00:03:42,920
二伯 您来

85
00:03:42,920 --> 00:03:45,080
这上宴会的时候一人两串

86
00:03:45,080 --> 00:03:46,880
真嫩

87
00:03:46,880 --> 00:03:49,000
做工简单 但是还讲究

88
00:03:49,000 --> 00:03:50,680
味道复合味浓

89
00:03:50,680 --> 00:03:54,720
辣酱油那种香气 拖着整个的菜肴

90
00:03:54,720 --> 00:03:56,760
看着就想吃

91
00:03:56,760 --> 00:04:00,160
吃了一串还不够 又来一串

92
00:04:00,160 --> 00:04:01,640
吃一串想两串

93
00:04:02,200 --> 00:04:04,160
不过这签子好啊

94
00:04:04,160 --> 00:04:05,920
您能不能送我一套 一定
```

**Comment by little-helping-hand** [comment]
认领

**Comment by little-helping-hand** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）【國宴大師•煎烹鸡肉串】家常版鸡肉串，外焦里嫩、简单健康，有平底锅就能做！\|老飯骨 [State Banquet Master Chef] Home cooked pan-fried chicken skewers  简介大家好，老饭骨为大家上菜咯！今天带来一道家常版煎烹鸡肉串。除了做鸡肉串，小友们还可以用这个方法做羊肉串、牛肉串、大虾串，一通百通！这样做出来的鸡肉串，外面焦香，鸡肉细嫩；这道菜做法也非常简单，家里有平底锅就能做！这道菜的亮点在辣酱油的香气一直拖着整个菜肴，味道浓郁！小友们快试试看，在家也能快乐地撸串！ Hello. Today, we will show you how to do pan fried chicken skewers at home. You can also substitute chicken with lamb, beef, shrimp, and hundreds more.  Pan-fried chicken skewers have a charred and crispy exterior with a moist centre. This simple dish only requires a frying pan! Give it a go and happy ‘Lu Chuan’(Chinese kebab) time! 字幕100:00:00,000 --> 00:00:02,960烹 这汁里边是没有芡的 Pan frying. There is no starch in the sauce. 200:00:03,080 --> 00:00:04,440煎烹鸡肉串 Pan fried chicken skewers. 300:00:04,560 --> 00:00:08,600 400:00:08,600 --> 00:00:09,920你看这有一签子 Take a look at this skewer. 500:00:09,920 --> 00:00:12,360这签子有将近五十年了 You must had those skewers for nearly 50 years. 600:00:12,360 --> 00:00:13,560这是个老物件 These are vintage skewers. 700:00:13,560 --> 00:00:16,440鸡腿肉 先搁点淀粉上浆了 Deboned leg of chicken. Mix with some starch first. 800:00:16,440 --> 00:00:18,600你怎么先搁淀粉啊 Why do you mix them with starch first? 900:00:18,600 --> 00:00:19,840都是一样的 Same thing. 1000:00:19,840 --> 00:00:22,040鸡蛋 Eggs. 1100:00:22,040 --> 00:00:27,720搁点酱油 冰糖老抽 盐 胡椒粉 黄酒 Some soy sauce, caramelised dark soy sauce, salt, ground pepper and rice wine. 1200:00:27,720 --> 00:00:29,600这料就放完了 接着放香油 That is all the seasoning. Next, pour some sesame oil in. 1300:00:29,600 --> 00:00:33,880这料都给它上齐了 已经上劲了 Mix them well. 1400:00:33,880 --> 00:00:37,080香油 放香油吧 让我给说着了吧 I knew you would use sesame oil. 1500:00:37,080 --> 00:00:40,200二伯说得非常准 Er Bai guessed it right. 1600:00:40,200 --> 00:00:43,120你看这个鸡丁都是现成的 Already prepared chicken. 1700:00:43,120 --> 00:00:44,280我们给它串好了 Put the chicken on the skewers. 1800:00:44,280 --> 00:00:46,280不串直接煎也行 It is also alright to fry the chicken without skewers. 1900:00:46,280 --> 00:00:49,320到时候咱们把葱姜蒜搁到小料里 Let us put chopped spring onion, ginger, and garlic with other ingredients.   2000:00:49,320 --> 00:00:52,320煎呢 你要把葱姜蒜搁这里头 You need to put spring onion, ginger, and garlic in here when frying. 2100:00:52,320 --> 00:00:54,080一会一煎全是黑渣子 They will be charred and turn into black bits. 2200:00:54,080 --> 00:00:57,200这是真正传统菜 四五十年了 This is a real traditional dish, which has a long history of 40 or 50 years. 2300:00:57,200 --> 00:00:58,520这是个老菜 Classic dish indeed. 2400:00:58,520 --> 00:01:03,720煎烹牛肉串 煎烹鸡肉串 煎烹羊肉串 Pan fried beef skewers, chicken skewers, lamb skewers. 2500:01:03,720 --> 00:01:06,400什么都能煎 还能煎烹虾 Everything can be pan fried, also shrimps. 2600:01:06,400 --> 00:01:10,680煎烹有各种煎烹的方法 All sorts of ideas for pan-frying. 2700:01:10,680 --> 00:01:13,920一种像辣酱油的 还有茄汁的 One uses Worcestershire sauce, or tomato juice, 2800:01:13,920 --> 00:01:16,920还有一种柠檬汁的 or lemon juice, 2900:01:16,920 --> 00:01:19,360还有糖醋汁的 or sweet and sour sauce. 3000:01:19,360 --> 00:01:22,200各种的口味都有所不同 They all have their own unique flavour. 3100:01:22,200 --> 00:01:25,840 3200:01:25,840 --> 00:01:28,040现在味道是丰富多彩 Nowadays, the taste has become richer and more flavourful. 3300:01:28,040 --> 00:01:30,520煎烹就是锅里边的油要少 Pan frying requires little oil. 3400:01:30,520 --> 00:01:36,000把东西煎到外焦里嫩 然后再烹 Searing and browning outside first. Then frying. 3500:01:36,000 --> 00:01:39,680但是它没有完全熟 没有完全入味 But they are not cooked through yet. The flavour is not fully infused. 3600:01:39,680 --> 00:01:42,320我们要靠外来的一些调味 The flavour is improved by adding additional seasonings. 3700:01:42,320 --> 00:01:43,600给它做一个补充 Enhancing the flavour of the dish. 3800:01:43,600 --> 00:01:44,920所以叫煎烹 So, it is called pan-frying. 3900:01:44,920 --> 00:01:46,560你看过去有煎烹鱼片 In the past, there were pan fried fish slices, 4000:01:46,560 --> 00:01:49,560煎烹鸡球 虾球 pan fried chicken balls, shrimp balls. 4100:01:49,560 --> 00:01:52,200关键是它的调味汁和原料不同 The differences are the marinate and raw ingredients. 4200:01:52,200 --> 00:01:55,160有的是酸辣的 有时候是咸鲜的 Sometimes it is hot and sour, other times savoury. 4300:01:55,160 --> 00:01:57,960有的是糖醋的 Sometimes it is sweet and sour. 4400:01:57,960 --> 00:02:01,160好了 真快 先烧锅 It is done. So quick. Heat up the wok first. 4500:02:01,160 --> 00:02:05,920在烧锅的同时 咱把这汁调好 番茄酱 At the meantime, mix the sauce well. Tomato puree. 4600:02:05,920 --> 00:02:08,000这个辣酱油是上海梅林的 This is Mei Lin spicy soy sauce (Worcestershire sauce) from Shanghai. 4700:02:08,000 --> 00:02:11,160这个是最古老的一种调味汁 It is one of the most classic marinate sauces. 4800:02:11,160 --> 00:02:13,520咸鲜 微辣 Savouriness, slight spicy,  4900:02:13,600 --> 00:02:15,800另外它有里边有一个特殊的香味 And it has a particular aroma.  5000:02:15,800 --> 00:02:18,000 5100:02:18,000 --> 00:02:22,160黄酒 冰糖老抽 Rice wine, caramelised dark soy sauce. 5200:02:22,160 --> 00:02:23,320搁点糖 Add bit of sugar. 5300:02:23,320 --> 00:02:27,240再来点胡椒粉 And pinch of ground pepper. 5400:02:27,240 --> 00:02:30,880你看这个过程特别简单 The process looks extremely easy. 5500:02:30,880 --> 00:02:33,000好了 Done. 5600:02:33,000 --> 00:02:35,560煎烹啊 朝辉看啊 Chao Hui, look. Pan frying. 5700:02:35,560 --> 00:02:38,080一个一个往里搁 One by one, place them in the pan. 5800:02:38,080 --> 00:02:41,760别摞着 摞着煎不了了 Do not stack them up, or the meat will not be brown. 5900:02:41,760 --> 00:02:42,120 6000:02:42,120 --> 00:02:45,200一煎熟了 好看吧 First round is done. Looking good? 6100:02:45,200 --> 00:02:48,680煎出来的菜是干香 焦香 Seared chicken has a smoked and charred aroma.  6200:02:48,680 --> 00:02:52,000这就好了 还没完全熟 Is it done? Not fully cooked yet. 6300:02:52,000 --> 00:02:53,840 6400:02:53,840 --> 00:02:56,040往这一放 这菜好看吧 Plate them. Doesn’t it look delicious? 6500:02:56,040 --> 00:02:58,400还没烹汁呢 一烹汁更好看 Still need to cook the sauce. It will look more delicious with sauce. 6600:02:58,400 --> 00:03:00,600来点底油 小料 Drizzle of oil. Put remaining ingredients in. 6700:03:00,600 --> 00:03:03,920汁儿一烹这菜就齐活 The dish will be done once we mix in the sauce. 6800:03:03,920 --> 00:03:06,840 6900:03:06,840 --> 00:03:08,640烹 不勾芡 Let it fry. Do not add starch. 7000:03:08,640 --> 00:03:13,080烹 这汁里边是没有芡的 Let it cook. There is no starch in the sauce. 7100:03:13,080 --> 00:03:15,600辣酱油的香味出来了 The fragrance of Worcestershire sauce comes out now. 7200:03:15,600 --> 00:03:19,000香气灼人 火力稍微欠点儿 Scorching aroma! Shame the stove is not powerful enough. 7300:03:19,000 --> 00:03:21,360 7400:03:21,360 --> 00:03:23,600大爷翻的这两下 Da Ye, flip them over. 7500:03:23,600 --> 00:03:24,800 7600:03:25,440 --> 00:03:27,520好啦 铲子 It is done.  7700:03:27,760 --> 00:03:28,640 7800:03:28,640 --> 00:03:31,720这都不用搁装饰 就这样挺好看的 No need to dress up the plate. It looks delicious as it is. 7900:03:31,720 --> 00:03:33,000大爷把过去的老菜 Da Ye likes to showcase those classic dishes  8000:03:33,000 --> 00:03:34,680一个一个都展示出来了 one at a time. 8100:03:34,680 --> 00:03:36,880让你流口水 Make a mouth-watering dish for you. 8200:03:36,880 --> 00:03:38,240因为它是有油 Because it (the skewer) is greasy. 8300:03:38,240 --> 00:03:40,120我们拿锡纸给它包一下把儿 Let us wrap it with some tin foil. 8400:03:40,120 --> 00:03:42,920二伯 您来 After you, Er Bai. 8500:03:42,920 --> 00:03:45,080这上宴会的时候一人两串 Two skewers per person was served in the banquet.  8600:03:45,080 --> 00:03:46,880真嫩 So tender! 8700:03:46,880 --> 00:03:49,000做工简单 但是还讲究 It is easy to make, but still need to pay attention to detail. 8800:03:49,000 --> 00:03:50,680味道复合味浓 Rich infused aromas. 8900:03:50,680 --> 00:03:54,720辣酱油那种香气 拖着整个的菜肴 The whole dish is elevated by the aroma of Worcestershire sauce.  9000:03:54,720 --> 00:03:56,760看着就想吃 Just looking at it makes you want to take a bite. 9100:03:56,760 --> 00:04:00,160吃了一串还不够 又来一串 One skewer after another. 9200:04:00,160 --> 00:04:01,640吃一串想两串 Eating one skewer while thinking about the other two on the plate. 9300:04:02,200 --> 00:04:04,160不过这签子好啊 Well, these skewers are nice. 9400:04:04,160 --> 00:04:05,920您能不能送我一套 一定 Could you give me a set? Definitely.
--

**Comment by little-helping-hand** [comment]
标题（翻译主要意思即可，不要超过 100 个字符

[國宴大師•煎烹鸡肉串】家常版鸡肉串，外焦里嫩、简单健康，有平底锅就能做！\|老飯骨 
[State Banquet Master Chef] Home cooked pan-fried chicken skewers

  简介

大家好，老饭骨为大家上菜咯！今天带来一道家常版煎烹鸡肉串。除了做鸡肉串，小友们还可以用这个方法做羊肉串、牛肉串、大虾串，一通百通！这样做出来的鸡肉串，外面焦香，鸡肉细嫩；这道菜做法也非常简单，家里有平底锅就能做！这道菜的亮点在辣酱油的香气一直拖着整个菜肴，味道浓郁！小友们快试试看，在家也能快乐地撸串！
Hello. Today, we will show you how to do pan fried chicken skewers at home. You can also substitute chicken with lamb, beef, shrimp, and hundreds more.  Pan-fried chicken skewers have a charred and crispy exterior with a moist centre. This simple dish only requires a frying pan! Give it a go and happy ‘Lu Chuan’(Chinese kebab) time! 

字幕100:00:00,000 --> 00:00:02,960
烹 这汁里边是没有芡的 
Pan frying. There is no starch in the sauce. 

200:00:03,080 --> 00:00:04,440
煎烹鸡肉串 
Pan fried chicken skewers. 

300:00:04,560 --> 00:00:08,600 

400:00:08,600 --> 00:00:09,920
你看这有一签子 
Take a look at this skewer. 

500:00:09,920 --> 00:00:12,360
这签子有将近五十年了 
You must had those skewers for nearly 50 years. 

600:00:12,360 --> 00:00:13,560
这是个老物件 
These are vintage skewers. 

700:00:13,560 --> 00:00:16,440
鸡腿肉 先搁点淀粉上浆了 
Deboned leg of chicken. Mix with some starch first. 

800:00:16,440 --> 00:00:18,600
你怎么先搁淀粉啊 
Why do you mix them with starch first? 

900:00:18,600 --> 00:00:19,840
都是一样的 
Same thing. 

1000:00:19,840 --> 00:00:22,040
鸡蛋 
Eggs. 

1100:00:22,040 --> 00:00:27,720
搁点酱油 冰糖老抽 盐 胡椒粉 黄酒 
Some soy sauce, caramelised dark soy sauce, salt, ground pepper and rice wine. 

1200:00:27,720 --> 00:00:29,600
这料就放完了 接着放香油 
That is all the seasoning. Next, pour some sesame oil in. 

1300:00:29,600 --> 00:00:33,880
这料都给它上齐了 已经上劲了 
Mix them well. 

1400:00:33,880 --> 00:00:37,080
香油 放香油吧 让我给说着了吧 
I knew you would use sesame oil. 

1500:00:37,080 --> 00:00:40,200
二伯说得非常准 
Er Bai guessed it right. 

1600:00:40,200 --> 00:00:43,120
你看这个鸡丁都是现成的 
Already prepared chicken. 

1700:00:43,120 --> 00:00:44,280
我们给它串好了 
Put the chicken on the skewers. 

1800:00:44,280 --> 00:00:46,280
不串直接煎也行 
It is also alright to fry the chicken without skewers. 

1900:00:46,280 --> 00:00:49,320
到时候咱们把葱姜蒜搁到小料里 
Let us put chopped spring onion, ginger, and garlic with other ingredients.   

2000:00:49,320 --> 00:00:52,320
煎呢 你要把葱姜蒜搁这里头 
You need to put spring onion, ginger, and garlic in here when frying. 

2100:00:52,320 --> 00:00:54,080
一会一煎全是黑渣子 
They will be charred and turn into black bits. 

2200:00:54,080 --> 00:00:57,200
这是真正传统菜 四五十年了 
This is a real traditional dish, which has a long history of 40 or 50 years. 

2300:00:57,200 --> 00:00:58,520
这是个老菜 
Classic dish indeed. 

2400:00:58,520 --> 00:01:03,720
煎烹牛肉串 煎烹鸡肉串 煎烹羊肉串 
Pan fried beef skewers, chicken skewers, lamb skewers. 

2500:01:03,720 --> 00:01:06,400
什么都能煎 还能煎烹虾 
Everything can be pan fried, also shrimps. 

2600:01:06,400 --> 00:01:10,680
煎烹有各种煎烹的方法 
All sorts of ideas for pan-frying. 

2700:01:10,680 --> 00:01:13,920
一种像辣酱油的 还有茄汁的 
One uses Worcestershire sauce, or tomato juice, 2

800:01:13,920 --> 00:01:16,920
还有一种柠檬汁的 
or lemon juice, 

2900:01:16,920 --> 00:01:19,360
还有糖醋汁的 
or sweet and sour sauce. 

3000:01:19,360 --> 00:01:22,200
各种的口味都有所不同 
They all have their own unique flavour. 

3100:01:22,200 --> 00:01:25,840 

3200:01:25,840 --> 00:01:28,040
现在味道是丰富多彩 
Nowadays, the taste has become richer and more flavourful. 

3300:01:28,040 --> 00:01:30,520
煎烹就是锅里边的油要少 
Pan frying requires little oil. 

3400:01:30,520 --> 00:01:36,000
把东西煎到外焦里嫩 然后再烹 
Sear and brown outside first. Then fry. 

3500:01:36,000 --> 00:01:39,680
但是它没有完全熟 没有完全入味 
But they are not cooked through yet. The flavour is not fully infused. 

3600:01:39,680 --> 00:01:42,320
我们要靠外来的一些调味 
The flavour is improved by adding additional seasonings. 

3700:01:42,320 --> 00:01:43,600
给它做一个补充 
Enhancing the flavour of the dish. 

3800:01:43,600 --> 00:01:44,920
所以叫煎烹 
So, it is called pan-frying. 

3900:01:44,920 --> 00:01:46,560
你看过去有煎烹鱼片 
In the past, there were pan fried fish slices, 

4000:01:46,560 --> 00:01:49,560
煎烹鸡球 虾球 
pan fried chicken balls, shrimp balls. 

4100:01:49,560 --> 00:01:52,200
关键是它的调味汁和原料不同 
The differences are the marinate and raw ingredients. 

4200:01:52,200 --> 00:01:55,160
有的是酸辣的 有时候是咸鲜的
Sometimes it is hot and sour, other times savoury. 

4300:01:55,160 --> 00:01:57,960
有的是糖醋的 
Sometimes it is sweet and sour. 

4400:01:57,960 --> 00:02:01,160
好了 真快 先烧锅 
It is done. So quick. Heat up the wok first. 

4500:02:01,160 --> 00:02:05,920
在烧锅的同时 咱把这汁调好 番茄酱 
At the meantime, mix the sauce well. Tomato puree. 

4600:02:05,920 --> 00:02:08,000
这个辣酱油是上海梅林的
This is Mei Lin spicy soy sauce (Worcestershire sauce) from Shanghai. 

4700:02:08,000 --> 00:02:11,160
这个是最古老的一种调味汁 
It is one of the most classic marinate sauces. 

4800:02:11,160 --> 00:02:13,520
咸鲜 微辣 
Savouriness, slight spicy,  

4900:02:13,600 --> 00:02:15,800
另外它有里边有一个特殊的香味 
And it has a particular aroma.  

5000:02:15,800 --> 00:02:18,000 

5100:02:18,000 --> 00:02:22,160
黄酒 冰糖老抽 
Rice wine, caramelised dark soy sauce. 

5200:02:22,160 --> 00:02:23,320
搁点糖 
Add bit of sugar. 

5300:02:23,320 --> 00:02:27,240
再来点胡椒粉 
And pinch of ground pepper. 

5400:02:27,240 --> 00:02:30,880
你看这个过程特别简单 
The process looks extremely easy. 

5500:02:30,880 --> 00:02:33,000
好了 
Done. 

5600:02:33,000 --> 00:02:35,560
煎烹啊 朝辉看啊 
Chao Hui, look. Pan frying. 

5700:02:35,560 --> 00:02:38,080
一个一个往里搁 
One by one, place them in the pan. 

5800:02:38,080 --> 00:02:41,760
别摞着 摞着煎不了了 
Do not stack them up, or the meat will not be brown. 

5900:02:41,760 --> 00:02:42,120 

6000:02:42,120 --> 00:02:45,200
一煎熟了 好看吧 
First round is done. Looking good? 

6100:02:45,200 --> 00:02:48,680
煎出来的菜是干香 焦香 
Seared chicken has a smoked and charred aroma. 

6200:02:48,680 --> 00:02:52,000
这就好了 还没完全熟
Is it done? Not fully cooked yet. 

6300:02:52,000 --> 00:02:53,840 

6400:02:53,840 --> 00:02:56,040
往这一放 这菜好看吧 
Plate them. Doesn’t it look delicious? 

6500:02:56,040 --> 00:02:58,400
还没烹汁呢 一烹汁更好看 
Still need to cook the sauce. It will look more delicious with sauce. 

6600:02:58,400 --> 00:03:00,600
来点底油 小料 
Drizzle of oil. Put remaining ingredients in. 

6700:03:00,600 --> 00:03:03,920
汁儿一烹这菜就齐活 
The dish will be done once we mix in the sauce. 

6800:03:03,920 --> 00:03:06,840 

6900:03:06,840 --> 00:03:08,640
烹 不勾芡 
Let it fry. Do not add starch. 

7000:03:08,640 --> 00:03:13,080
烹 这汁里边是没有芡的 
Let it cook. There is no starch in the sauce. 

7100:03:13,080 --> 00:03:15,600
辣酱油的香味出来了 
The fragrance of Worcestershire sauce comes out now. 

7200:03:15,600 --> 00:03:19,000
香气灼人 火力稍微欠点儿 
Scorching aroma! Shame the stove is not powerful enough. 

7300:03:19,000 --> 00:03:21,360 

7400:03:21,360 --> 00:03:23,600
大爷翻的这两下 
Da Ye, flip them over. 

7500:03:23,600 --> 00:03:24,800 

7600:03:25,440 --> 00:03:27,520
好啦 铲子 
It is done.  

7700:03:27,760 --> 00:03:28,640 

7800:03:28,640 --> 00:03:31,720
这都不用搁装饰 就这样挺好看的 
No need to dress up the plate. It looks delicious as it is. 

7900:03:31,720 --> 00:03:33,000
大爷把过去的老菜 
Da Ye likes to showcase those classic dishes  

8000:03:33,000 --> 00:03:34,680
一个一个都展示出来了 
one at a time. 

8100:03:34,680 --> 00:03:36,880
让你流口水 
Make a mouth-watering dish for you. 

8200:03:36,880 --> 00:03:38,240
因为它是有油 
Because it (the skewer) is greasy. 

8300:03:38,240 --> 00:03:40,120
我们拿锡纸给它包一下把儿
Let us wrap it with some tin foil. 

8400:03:40,120 --> 00:03:42,920
二伯 您来 
After you, Er Bai. 

8500:03:42,920 --> 00:03:45,080
这上宴会的时候一人两串 
Two skewers per person was served in the banquet.  

8600:03:45,080 --> 00:03:46,880
真嫩 
So tender! 

8700:03:46,880 --> 00:03:49,000
做工简单 但是还讲究 
It is easy to make, but still requires an attention to detail. 

8800:03:49,000 --> 00:03:50,680
味道复合味浓 
Rich infused aromas. 

8900:03:50,680 --> 00:03:54,720
辣酱油那种香气 拖着整个的菜肴 
The whole dish is elevated by the aroma of Worcestershire sauce.  

9000:03:54,720 --> 00:03:56,760
看着就想吃 
Just looking at it makes you want to take a bite. 

9100:03:56,760 --> 00:04:00,160
吃了一串还不够 又来一串 
One skewer after another. 

9200:04:00,160 --> 00:04:01,640
吃一串想两串 
Eating one skewer while thinking about the other two on the plate. 

9300:04:02,200 --> 00:04:04,160
不过这签子好啊 
Well, these skewers are nice. 

9400:04:04,160 --> 00:04:05,920
您能不能送我一套 一定 
Could you give me a set? Definitely.

--
