### ISSUE TITLE
[华农兄弟] 华农兄弟上山一趟发现不少野果有些已经十几年没吃过了 - https://youtu.be/pN74mYpEseA

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1553]
https://youtu.be/pN74mYpEseA
<p>&#35270;&#39057;&#21457;&#24067;&#20110; October 10, 2020 at 12:00AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/pN74mYpEseA

#华农兄弟：上山一趟，发现不少野果，有些已经十几年没吃过了

#Huanong Brothers: A trip to the hill. Lot of wild fruits. Haven't seen some for dozen of years.

#Huanong Brothers: We take a trip to the hill and see a lot of wild fruits. Some have already been out of our sight for more than a decade.


0:00:07.040,0:00:10.597
# 大家好  剛才看到兄弟  匆匆忙忙的跑進山上去啦
Hi everyone! I just saw my buddy, rushing to the hill.

0:00:10.597,0:00:12.444
# 我以為他摘果呢 嚇我一大跳
I thought that he was gonna pick the fruits. It scared me.

0:00:12.444,0:00:14.481
# 搞得我開車直接衝進來啦
So I also rushed here right away, driving my car.

0:00:14.481,0:00:16.100
# 我看一下啊我那個果還在不在
Let me see whether my, my fruits are still there.

0:00:16.788,0:00:17.498
# 就在前面
They’re right in the front.

0:00:19.904,0:00:20.905
# 還好  還在
Still there, fortunately

0:00:21.485,0:00:23.049
# 那麼多  還沒熟
There are so many, but are still green.

0:00:24.001,0:00:25.716
# 概[SIC]不到 概不到他不摘
No wonder he didn’t pick them.

0:00:26.264,0:00:27.372
# 不知道他進山幹嘛
So why was he going into the hill?

0:00:27.975,0:00:30.449
# 我去看一下前面  前面還有那個鐵老虎哦
Let’s have a look in the front. There are also "iron tigers" (big kadsura fruits) in the front,

0:00:30.732,0:00:33.586
# 還有酒飯團  還有  那麼甚麼
and "jiu fantuan" (kadsura fruits) too. And also, well, you know,

0:00:34.553,0:00:37.379
# 額 酸棗 都還很多  我去摘一點來
eh, hog plums, at a lot more. Let me go and pick some.

0:00:37.690,0:00:38.590
# 帶了一個小籃子
I go with a small basket.

0:00:56.481,0:00:58.785
# 今天沒下雨  你看  一下就上來啦
There’s no rain today. Look! I can go up right away.

0:00:59.374,0:01:00.957
# 小意思上這樣的坡
This slope is a piece of cake.

0:01:01.072,0:01:02.123
# 這個車很猛的
This car is not to be sniffed at.

0:01:11.122,0:01:12.686
# 你看  這裡好多拿藤果啊
Look! Here are a lot of wild chocolate vine fruits.

0:01:13.484,0:01:14.441
# 好多哇
Really a lot!

0:01:15.149,0:01:15.992
# 一樹都是
All over the tree

0:01:16.808,0:01:17.594
# 哎呀
Aya!

0:01:18.580,0:01:20.239
# 哎呀  這裡勾住啦
Aya! I am hooked here.

0:01:20.481,0:01:22.424
# 你看  那麼多拿藤果
Look! So many chocolate vine fruits

0:01:22.944,0:01:24.337
# 一樹都是  這裡有幾個
All over the three. Some here,

0:01:24.337,0:01:26.356
# 那裡有  那裡有  那裡也有
some there, and there, and there as well

0:01:27.106,0:01:28.233
# 好多哇  今年
Really a lot, this year

0:01:28.961,0:01:30.980
# 我去前面看一下  前面有沒有香藤子
Let me go in the front, and see if there are any “xiang tengzi” (valarien) in the front.

0:01:31.524,0:01:33.714
# 去年我都摘了幾個香藤子  今年應該有
I picked some valariens last year. This year should be no exception.

0:01:41.444,0:01:42.704
# 你看  這個茶花
Look! These are tea flowers.

0:01:43.543,0:01:46.966
# 這個不知道哪裡種的  這裡怎麼有一棵這樣的茶花
I have no ideas who planted it. Why is such a tea flower tree here?

0:01:47.359,0:01:50.421
# 這個時候 這個季節都是  那個茶果子都快熟啦
At this moment, in this season, the tea fruits are already becoming ripe.

0:01:50.518,0:01:51.683
# 他現在才剛開花 
But this is still blossoming,

0:01:52.045,0:01:53.172
# 而且還開了那麼多花
and blossoming so gorgeously,

0:01:54.221,0:01:55.424
# 開的花枝招展
with so many flowers.

0:01:57.001,0:01:57.502
# 誒
Ey?

0:01:57.845,0:01:59.466
# 哎呀  好像那邊有野豬哦
Aiya! There seems to be some wild boars.

0:02:00.001,0:02:00.616
# 看一下
Let me take a look.

0:02:01.325,0:02:03.629
# 誒  我以為是甚麼呢  原來是
Ey! I was wondering what they are. But it turns out to be,

0:02:04.102,0:02:05.742
# 那個  小山羊
you know, little goats.

0:02:07.343,0:02:08.793
# 沒有要的就是野山羊
They belong to no one. So they’re wild goats.

0:02:09.798,0:02:11.912
# 放在那 放在荒效野外
They are left, left in the wild.

0:02:20.387,0:02:20.907
# hello
Hello!

0:02:23.811,0:02:25.451
# 下午好  哎呀
Good afternoon! Aya!

0:02:26.321,0:02:26.917
# 那麼多
There are so many!

0:02:27.361,0:02:28.128
# 咩
Meh~

0:02:29.179,0:02:30.686
# 咩  你看  那頭領頭羊
Meh~ Look! That one is the Alpha,

0:02:31.712,0:02:33.465
# 好黑的  肚子白的那個
the very black one, with a white belly.

0:02:33.659,0:02:35.715
# 應該有一百斤  那麼大
It should be at least fifty kilograms. It’s so big.

0:02:37.003,0:02:38.016
# 全身肌肉
It’s covered with muscles.

0:02:39.273,0:02:40.059
# 肯定好吃
So it must be very tasty,

0:02:43.012,0:02:44.500
# 咩  全跑啦
Meh! They all ran away.

0:02:48.676,0:02:49.651
# 好多小山羊
A lot of small goats.

0:02:53.601,0:02:54.823
# 你看 這野果
Look! These wild fruits…

0:02:55.337,0:02:56.123
# 好多吧
There are a lot, right?

0:02:56.902,0:03:00.230
# 剛我這一眼看上去都七八個哦1 2 3 4 5 6 7 8 9 
My first sight can already see seven or eight, 1 2 3 4 5 6 7 8 9.

0:03:02.006,0:03:03.816
# 還沒熟  熟的時候再來
But they’re not yet ripe. Let me come again when they’re ripe.

0:03:04.573,0:03:05.340
# 先做好標記來
I put a mark here first.

0:03:13.109,0:03:15.242
# 記得從這裡插一個這個東西就知道
I just need to remember that this thing is stuck here.

0:03:18.787,0:03:20.597
# 一個樹枝就知道這裡
A branch is enough to remind myself.

0:03:22.933,0:03:25.313
# 這次把標記做好啦 直奔主題
When the mark is properly done this time. Next time, right to the main theme!

0:03:27.001,0:03:28.754
# 看一下前面還有些甚麼東西
Let me see what else in the front.

0:03:32.832,0:03:35.079
# 你看  這個  我們這邊叫
Look! This is, here it is called,

0:03:35.715,0:03:36.539
# 火柴品
match heads.

0:03:38.001,0:03:39.697
# 就是火柴火柴頭一樣的
Well, they just look like matches, match heads.

0:03:40.439,0:03:41.794
# 火柴頭就是這樣子的
This is how match heads look like.

0:03:43.274,0:03:45.634
# 很靚吧  這個可以吃的  這個  不過特別酸
Beautiful, aren’t they? These are also edible, these fruits. But, they’re exceptionally sour.

0:03:49.257,0:03:50.441
# 嗯  怎麼那麼好吃
Um? Why does it taste so good?

0:03:54.306,0:03:54.883
# 嗯
Um!

0:03:55.552,0:03:56.167
# 好酸
It’s really sour.

0:03:56.852,0:03:57.865
# 啊  你看
Ah! Look!

0:03:58.643,0:03:59.296
# 靚吧
Beautiful, aren’t they?

0:04:02.319,0:04:04.205
# 如果打  打了霜之後更靚
They would be even more beautiful after, after being frosted.

0:04:04.498,0:04:08.490
# 通紅的 而且有點甜甜的  酸酸甜甜的  特別好吃
It would be completely red, with a bit sweet, sweet and sour, exceptionally tasty.

0:04:08.800,0:04:09.813
# 現在還不是很熟
They’re still not really that ripe now.

0:04:11.268,0:04:12.794
# 掛在樹上給鳥吃
I hang it onto the tree for the birds.

0:04:15.120,0:04:17.329
# 到時候鳥就過來吃掉啦  不會浪費
The birds can eat it when they come in a while. Then it would not be wasted.

0:04:17.690,0:04:19.405
# 不能浪費資源
We shouldn’t waste any resources on our planet.

0:04:27.247,0:04:29.114
# 你看  這裡有  酒飯團
Look! Here are “jiu fantuan” (lit: wined rice ball, small kadsura fruits).

0:04:29.468,0:04:30.766
# 那麼小的酒飯團
The “jiu fantuan” are so small.

0:04:31.362,0:04:32.186
# 還沒熟
But they’re not yet ripe.

0:04:32.681,0:04:33.638
# 熟了在[SIC]說
Let’s wait until they’re ripe.

0:04:38.241,0:04:38.818
# 你看
Look!

0:04:39.518,0:04:41.897
# 這太壞啦  被松鼠咬下來啦
It’s too bad. It was bitten off by squirrels.

0:04:42.760,0:04:44.893
# 這個都還沒熟就被它咬下來啦
It’s still green but they bit it off.

0:04:47.277,0:04:47.835
# 哎喲
Aya!

0:04:48.739,0:04:49.715
# 裡面有肉哦  (註︰原字幕缺失了，但太清楚，不想跳過)
Here’s pulp inside.

0:04:55.255,0:04:56.022
# 太浪費啦
What a waste!

0:04:57.121,0:04:58.134
# 這麼壞
They’re so bad!

0:05:02.401,0:05:05.141
# 你看  這個我們這裡叫狐狸桃
Look! These are called “fox fruits” (wild kiwifruits) here.

0:05:06.093,0:05:07.714
# 還沒熟  要冬天才熟
But they’re not yet ripe, not until winter.

0:05:08.614,0:05:09.457
# 好多哇
Really a lot!

0:05:11.338,0:05:12.181
# 很好吃的哦
They’re really tasty, you know.

0:05:12.892,0:05:15.366
# 拿到一捏一吸就進去啦
Take it, squeeze it, suck it, and it’s in your mouth.

0:05:15.585,0:05:16.409
# 皮就一丟
Then throw away the peel.

0:05:18.547,0:05:19.238
# 現在沒熟
But they're not yet ripe.

0:05:21.921,0:05:24.000
# 你看  一隻老鷹在天空中盤旋
Look! An eagle is circling around in the sky.

0:05:24.695,0:05:25.860
# 你是不是想捉我啊
Are you coming to catch me?

0:05:26.591,0:05:27.301
# 來呀
C’mon! Go head!

0:05:29.284,0:05:32.176
# 把我勾上 勾上天空上去也好啊
Hook me, hook me into the sky. It would be really nice!

0:05:36.641,0:05:39.438
# 你看  這裡一塊  很紅的哦  香藤子
Look! The whole area here, is really red, the “xiang tengzi”

0:05:42.881,0:05:43.477
# 你看
Look!

0:05:44.181,0:05:45.156
# 夠紅吧  這個
They’re really red, right?

0:05:45.708,0:05:47.385
# 這個味道很好吃的哦  這種味道
The taste is really good, you know. This taste is,

0:05:48.158,0:05:48.944
# 就是那種
is just like,

0:05:49.325,0:05:51.000
# 有點辣辣的  辣嘴巴  這個
it's a bit spicy, it burns the mouth, sort of.

0:05:54.934,0:05:55.606
# 很甜
It’s really sweet.

0:05:56.205,0:05:59.286
# 它有點辣辣的  甜中帶辣  辣中帶甜
A bit spicy, sweety spicy, spicy sweet,

0:06:00.096,0:06:01.660
# 還有一種果香味
with a fruity scent.

0:06:02.678,0:06:03.862
# 啊  全部把它摘下來
Ah! Let me pick them all.

0:06:04.042,0:06:04.960
# 那還有幾個
There are still a few.

0:06:14.879,0:06:15.722
# 那麼小
They’re so small.

0:06:24.521,0:06:25.155
# 這個靚
 This is beautiful!

0:06:37.133,0:06:38.526
# 哎喲  差點掉啦
Aya! It almost dropped onto the ground.

0:06:41.202,0:06:42.140
# 好靚吧
Beautiful, aren’t they?

0:06:42.552,0:06:44.761
# 你看  這個就熟透了的香藤子
Look! These are completely ripe “xiang tengzi”.

0:06:44.925,0:06:47.980
# 剛才  剛才那個  在路邊上的沒熟的
The, the one, the ones on the road were not yet ripe.

0:06:49.149,0:06:51.377
# 熟透了就這種產色 血紅色
This is the colour when they're completely ripe, bloody red.

0:06:52.673,0:06:53.743
# 看一下前面還有沒有
Let’s see if there are any more in the front.

0:06:56.641,0:06:57.749
# 你看  這樹上
Look! In this tree,

0:06:58.262,0:07:00.000
# 有五六串哦  這樹太高啦
there are five or six strings of them. But this tree is too tall,

0:07:00.770,0:07:03.168
# 只能把樹砍掉才可以摘
we can only chop down the tree if we want to pick them.

0:07:04.021,0:07:04.541
# 這樣
But it’s,

0:07:05.113,0:07:06.885
# 這樣不好  不能亂砍樹
it’s no good. Trees need to be protected.

0:07:09.921,0:07:10.764
# 哇  你看
Wa! Look!

0:07:11.224,0:07:13.167
# 這有兩個哦  那麼大的
Here are two. They’re so big!

0:07:13.952,0:07:15.000
# 它現在沒熟哦
But they’re not yet ripe.

0:07:17.711,0:07:19.275
# 你看  這兩個鐵老虎
Look! These two iron tigers (big kadsura fruits),

0:07:19.658,0:07:20.633
# 那麼大了哦
they’re so big now.

0:07:21.115,0:07:21.882
# 比我拳頭還大
even bigger than my fist,

0:07:22.169,0:07:22.936
# 跟碗一樣
just like a bowl.

0:07:23.237,0:07:25.142
# 現在還沒熟哦  熟了之後我再來
But they’re not yet ripe. When they’re ripe, I’ll come again,

0:07:25.928,0:07:26.790
# 再來摘
come and pick them.

0:07:27.182,0:07:27.797
# 來早了
I come too early.

0:07:28.634,0:07:30.539
# 來遲了又怕被人家 吃
But if we come late, it might have already been, eaten,

0:07:30.881,0:07:31.381
# 摘掉
picked, by other people.

0:07:32.120,0:07:34.044
# 在樹頂上的還有兩個好大的
There are also two very big ones at the top of the tree.

0:07:42.881,0:07:44.179
# 你看  這裡的拿藤果
Look! The chocolate vine fruits here,

0:07:44.541,0:07:45.498
# 那麼大條的
are so big and long.

0:07:46.254,0:07:48.121
# 苗又少  肉又多
There are not many leaves. But the pulp is rich.

0:07:48.502,0:07:49.686
# 個  個頭又大
And the size, the size is really big.

0:07:50.832,0:07:51.940
# 說明這裡的肥料好
It means that here is will fertilised.

0:07:52.871,0:07:54.000
# 兄弟在這裡放牛
My buddy pastures his cattle here.

0:07:54.368,0:07:55.647
# 天天拉牛屎在這裡
And the cattle poop here every day.

0:07:57.001,0:07:57.844
# 怪不很它那麼大
No wonder they’re so big.

0:07:58.241,0:07:59.520
# 你看  又好多金櫻子啊
Look! Here are also a lot of rose fruits.

0:08:01.274,0:08:02.003
# 好多刺的
They're very spiky.

0:08:02.563,0:08:04.203
# 它這個也可以用來泡酒的哦
These can also be used to make infused liquour, you know.

0:08:04.577,0:08:05.401
# 也可以把那個
They can also be, you know,

0:08:06.134,0:08:08.182
# 直接吃也可以  但是要把裡面的籽挖掉
be eaten right away. But the seeds inside need to be removed.

0:08:08.344,0:08:09.452
# 還有外面的刺也把它
And the spikes on the surface also need to be,

0:08:09.977,0:08:10.516
# 搓掉
rubbed off.

0:08:11.416,0:08:12.297
# 直接吃就好
Then they can be eaten right away.

0:08:13.492,0:08:14.505
# 好多啊  今年
There are a lot, this year.

0:08:14.911,0:08:16.588
# 今年好像甚麼野果都很多
It seems that all wild fruits are plentiful this year.

0:08:17.086,0:08:18.270
# 你看  這個茶果哦
Look! This is a tea fruit.

0:08:18.521,0:08:20.275
# 這就是我剛剛說的那個茶樹果
This is the fruit of the tea tree that I just mentioned before.

0:08:21.241,0:08:23.507
# 這個苞啊  裡面都是籽來的
This pocket, there are only seeds inside.

0:08:26.366,0:08:27.759
# 這個可以用來榨油的哦
Oil can be extracted from it, you know.

0:08:31.041,0:08:32.908
# 這裡也可以榨個幾滴油出來喲
A few drops of oil can be extracted here.

0:08:34.418,0:08:37.158
# 你看  這裡還有杮子哦  這個杮子快黃啦
Look! Here are also persimmons. These persimmons will soon be turning yellow.

0:08:41.248,0:08:41.882
# 你看
Look!

0:08:42.320,0:08:43.713
# 這裡一個那麼大串的
Look! Here’s such a huge string of “xiang tengzi”.

0:08:45.201,0:08:47.922
# 好久都沒有  沒有爬過  竹竿啦
I haven’t climbed, haven't climbed a, a bamboo for a long time.

0:08:48.480,0:08:51.258
# 我上試一下能不能  還能不能爬的上去
Let me try if I still can, if I still can climb onto it.

0:09:06.929,0:09:07.753
# 這個可以
It’s not bad.

0:09:24.193,0:09:24.941
# 半斤
A quarter kilogram

0:09:26.260,0:09:27.786
# 這樣的是熟透了這個
This one is completely ripe, this one.

0:09:29.709,0:09:30.400
# 嘗一下
Let me have a try.

0:09:31.860,0:09:32.911
# 這種才好吃哦
This would taste the best.

0:09:35.767,0:09:36.401
# 嗯
Um!

0:09:37.235,0:09:38.192
# 就是不一樣
The difference is significant.

0:09:38.401,0:09:39.623
# 你看  這兩個最大的
Look! These two are the biggest ones.

0:09:48.511,0:09:49.221
# 太好吃啦
It’s simply delicious!

0:09:51.302,0:09:52.334
# 帶回給小孩子吃
Let’s take them back for our children.

0:09:53.259,0:09:54.823
# 他們見都沒見過這個果
They haven’t even seen this kind of fruits before.

0:09:57.705,0:09:58.205
# 還有
There’s,

0:09:58.844,0:09:59.668
# 那還有一棵
there’s another tree.

0:10:04.810,0:10:05.842
# 很累的哦
It’s really tiring, you know.

0:10:07.361,0:10:09.000
# 哎呀  就摘了快一籃子啦
Aya! This basket is nearly full.

0:10:09.581,0:10:10.822
# 我看一下前面還有沒有
Let me see if there are any more in the front.

0:10:12.202,0:10:13.234
# 好久沒上山啦
I haven’t been to the hill for a very long time.

0:10:13.762,0:10:14.775
# 現在我都胖啦
I’m becoming chubby now.

0:10:15.894,0:10:16.794
# 兩腿發軟
And my legs are trembling.

0:10:17.441,0:10:18.095
# 你看
Look!

0:10:18.497,0:10:20.383
# 這樹上還有那個山茘枝哦
There are even wild lychee in this tree.

0:10:20.383,0:10:21.523
# 我都還沒發現
I didn’t see them.

0:10:22.613,0:10:27.000
# 我都  我差不多20年  20年都沒吃過這個  這個東西啦
I haven’t, haven’t eaten these, these things for almost twenty years, twenty years.

0:10:27.724,0:10:28.699
# 好少啦
They’re really rare.

0:10:29.841,0:10:31.063
# 竟然被我碰上啦
But fate brings them to me today.

0:10:32.001,0:10:33.565
# 我上去搖一下看搖不搖得不來
Let me go up and shake it. See if I can shake them off.

0:11:23.403,0:11:25.213
# 哎呀紅的都被掉下去啦
Aya! The red ones are all shaken off.

0:11:26.818,0:11:28.135
# 剩下不紅的就放在這裡
Those which are still here are not red.

0:11:36.001,0:11:36.559
# 你看
Look!

0:11:37.035,0:11:38.029
# 就摘了那麼一點
So I’ve just picked a tiny little bit here.

0:11:41.547,0:11:43.471
# 嘗一下  看一下怎麼樣  味道
Let me try, and see how, how it tastes.

0:11:45.129,0:11:45.972
# 一捏一下
Squeeze it.

0:11:48.686,0:11:49.263
# 好甜
Really sweet

0:11:49.440,0:11:50.599
# 有點像茘枝味一樣
It tastes a bit like lychee.

0:12:02.768,0:12:04.939
# 別浪  不要浪費啦  差點掉啦
Don’t, don’t waste it! It almost dropped.

0:12:09.001,0:12:10.071
# 好  回去啦  回去啦
Alright! Let’s go back, let’s go back.

0:12:15.681,0:12:17.890
# 你看  檢了那麼一點點
Look! We’ve picked just a tiny little bit here.

0:12:18.726,0:12:19.436
# 回去啦
Let’s go back.

0:12:20.727,0:12:22.632
# 看一下前面還有沒有甚它的
Let me see if there's anything else in the front.

0:12:23.041,0:12:23.922
# 你看  這個樹
Have a look at this tree.

0:12:24.398,0:12:25.696
# 又大又紅的哦
They’re all big and red, you know.

0:12:28.012,0:12:29.234
# 叫兄弟上去搖一下
I ask my buddy to go up and shake it.

0:12:31.515,0:12:34.558
# 先把那帽子跟衣服拿過來 褲子也可以
Give me your hat and your shirt first, or your trousers, if you prefer.

0:12:39.741,0:12:40.716
# 把衣服也拿過來
Give me your shirt as well.

0:12:41.684,0:12:42.184
# 好
Alight!

0:12:42.927,0:12:43.656
# 開始了啊
Let’s start.

0:12:44.115,0:12:45.944
# 等一下  等一下  攤好來
Wait, wait! Let me spread it here first.

0:12:46.199,0:12:47.573
# 可以  開始搖
Alright! Start shaking!

0:12:51.913,0:12:53.154
# (一個都沒有)
Not even one!

0:12:57.191,0:12:59.115
# 你看  這個   超級大的
Look! This is, super huge.

0:12:59.572,0:13:00.946
# 還有這個  小的
And this one, a small one.

0:13:01.393,0:13:03.000
# 這個帽子就接了兩個
So two are caught with this hat.

0:13:06.234,0:13:07.437
# 先吃個小的來
Let me have the small one first.

0:13:10.482,0:13:11.306
# 嗯 嗯
Um, um!

0:13:12.204,0:13:13.104
# 特別香
It smells exceptionally good.

0:13:14.900,0:13:17.204
# 果肉黃的  這個留給攝影小哥吃
The pulp is brown. I leave this one for Mr. Cameraman.

0:13:17.589,0:13:18.622
# 他帽子接的
It’s caught with his hat, after all.

0:13:22.561,0:13:23.062
# 你看
Look!

0:13:23.386,0:13:25.139
# 這裡這個皮是這樣子的哦
That’s how their peels look like, you know.

0:13:26.640,0:13:29.380
# 它這個表皮上像那個  獼猴桃一樣的
The peel looks like the, I mean, just like kiwifruits.

0:13:30.524,0:13:32.258
# 但不  不影響它的口感
But it, it tastes as good.

0:13:32.849,0:13:33.862
# 你看 好多啊
Look! Here are a lot!

0:13:34.724,0:13:36.212
# 那邊  那樹上還好多
There, a lot more on that tree.

0:13:37.159,0:13:39.000
# 下次把那夾子帶過來就可以啦
I shall come again with that pincer next time.

0:13:39.269,0:13:40.207
# 好夾  這樣
It would then be much easier.

0:13:41.217,0:13:44.336
# 樹枝太小  上次  我記得我去年就在這裡上面
The branches are too small. Last time, I remember filling up half,

0:13:45.398,0:13:47.113
# 搞了  搞了半蛇皮袋
half a bag up there last year.

0:13:47.474,0:13:48.336
# 半牛皮袋
Half a bag

0:13:52.161,0:13:53.857
# 哇  你看  這一樹都是哦
Wa! Look! They’re all over the tree.

0:13:54.141,0:13:54.965
# 好多哇
A lot!

0:13:55.590,0:13:56.907
# 應該可以把籃子裝滿啦
I think I can fill up this basket now.

0:14:01.766,0:14:02.817
# 天都快黑啦
It will be dark very soon.

0:14:03.807,0:14:04.669
# 黑了我也要
I don’t care. I am going up and pick them,

0:14:05.811,0:14:06.654
# 我也上去摘
dark or not.

0:14:09.269,0:14:10.586
# 這個爽吧  這個
This is really cool, this one!

0:14:11.672,0:14:12.363
# 嘗一下
Let me try.

0:14:18.001,0:14:19.261
# 這裡還有這麼多小果子
Here are still so many tiny fruits.

0:14:19.358,0:14:19.858
# 是啊
Indeed!

0:14:24.961,0:14:26.164
# 一個小籃子都裝滿啦
This small basket is already full.

0:14:27.152,0:14:28.697
# 你看  這裡還有那麼多這個
Look! Here are so many, this is,

0:14:29.198,0:14:29.870
# 這個叫甚麼
how is it called?

0:14:30.001,0:14:31.925
# 我們這邊叫做紅扣子
Here they're called red buttons.

0:14:33.940,0:14:35.105
# 這個可以吃的哦  這個
It’s edible, you know.

0:14:37.756,0:14:38.371
# 你看
Look!

0:14:39.913,0:14:40.888
# 酸酸甜甜的
It’s sweet and sour,

0:14:48.219,0:14:49.062
# 像葡萄一樣
just like grapes.

0:14:49.447,0:14:51.219
# 不信你嘗一下  你要吃一下
Don’t you think so? You can have a try. You gotta have a try.

0:14:56.137,0:14:57.454
# 這樣一串一串
They’re in strings.

0:15:09.121,0:15:10.571
# 天色晚啦  我要回去啦
It’s getting dark now and I gotta go back.

0:15:10.846,0:15:12.998
# 一籃子  裝都裝不下啦
A whole basket. It can't take any more.

0:15:14.173,0:15:15.000
# 回去 回去
Let’s go, let’s go.

0:15:15.726,0:15:17.593
# 等下天黑啦  就出不來山啦
We would get stuck in the hill if it gets dark.

0:15:18.001,0:15:19.185
# 是甚麼東西  這個
What is it? This one

0:15:24.001,0:15:25.014
# 這個像腎一樣的
It looks like a kidney.

0:15:25.772,0:15:28.113
# (我們這邊叫XXXXXX)
Here it’s called, it's called ????? (untranslatable and untransliterable).

0:15:29.601,0:15:32.398
# 聽說這個玩了 會爛手的
People say that, it burns our hands.

0:15:34.081,0:15:34.753
# 但是看上去
But it looks…

0:15:36.229,0:15:36.960
# 好香啊
It smells so good.

0:15:37.479,0:15:40.883
# 我幫我剝啊  裡面的籽不能吃的  這個是辣的啊
Let me peel it. The seed inside is not to be eaten, alright? It’s spicy, you know.

0:15:44.253,0:15:45.000
# 好不好吃
Does it taste good?

0:15:45.557,0:15:46.343
# 籽不要啊
Don’t swallow the seed!

0:15:46.720,0:15:48.132
# 吃不了就哇出來啊
Spit it out if you can’t take it.

0:15:51.463,0:15:53.084
# 全部吐掉啦
She spits everything out.

0:15:53.385,0:15:54.095
# 好不好吃
Does it taste good?

0:15:55.668,0:15:57.000
# 是有一點辣辣的  是不是
It’s a bit spicy, isn’t it?

0:15:57.001,0:15:57.692
# 那你吃葡萄
Then have some grapes,

0:15:58.547,0:15:59.219
# 小葡萄
tiny grapes!

0:15:59.524,0:16:00.462
# 皮不能吃的哈
Don’t eat the peel, alright?

0:16:08.232,0:16:12.167
# 好啦  今天的視頻就到這裡啦  你看  你看他
Alright! The video ends here. Look! Have a look at him!

0:16:13.561,0:16:15.448
# (啊 一個像葡萄一樣的)
Ah! It looks just like a tiny grape.

0:16:15.699,0:16:16.493
# (全吃完啦)
They've already finished everything.
