### ISSUE TITLE
【美食作家王刚】玉米嫩兔 - https://youtu.be/rkgbNqDwH24

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1554]
**视频链接**：https://youtu.be/rkgbNqDwH24

视频时长4:23，预计发布为北京时间10月11日晚，辛苦！时间轴出了些问题，就直接校稿即可，上传时由运营解决时间轴问题。
这是刚哥最新的视频私享链接，由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“玉米嫩兔”的家常做法，清甜型川菜，口感嫩滑

简介
大家好，今天给大家介绍一道清甜型川菜“玉米嫩兔”，其口感嫩滑口味清淡，别有一番风味。其实大家对川菜一直的印象都偏麻辣重口，其实不然，川菜讲究百菜百味，单单一个麻辣都分非常多种味型。以后我还会分享更多更丰富的菜品，来带大家了解更多！

字幕
哈喽大家好我是王刚
本期视频我和大家分享一道家常菜
玉米嫩兔
首先我们准备现宰杀的肉兔半只
砍下前后腿之后再依次的将肋骨，腿骨，脊椎骨取下
去骨的目的是方便老人和小孩食用
当然嫌麻烦的同学也可以忽略
然后直接将兔肉先切成小条再切成小颗粒
同学们切记兔肉的胸部部分韧劲比较强
所以在切的时候必须将菜刀磨锋利
兔丁切好之后下一步开始初加工
盆中加入少许的小苏打（1克）
然后加入适量的冷水抓洗1分钟
这一步的目的是去除血水和增加兔丁的嫩度
抓洗干净之后捞出挤干水分备用
下一步开始准备腌制
盆中加入少许的食用盐（约0.5克）
加入适量的黄酒搅拌至上劲
中途加入适量的红薯淀粉搅打
没有红薯粉淀粉的同学可以用土豆或者玉米淀粉代替
淀粉拌匀之后再加入少许的蛋清增加嫩滑度
最后加入适量的植物油拌匀即可
下一步开始准备辅料
准备嫩玉米2根均匀的取下玉米粒备用
采用新鲜的玉米粒香味和口感最佳
没有的同学也可以用玉米罐头代替
准备青红椒各半个去籽之后切成小颗粒备用
同学们最好选择略带甜味的辣椒
这样成菜的口味更加温和清甜
再准备红萝卜1小块切成小粒备用
红萝卜可以增加菜品的颜色和口感
最后准备少许的生姜和小葱白切成小粒即可
下一步开始调料汁
碗中加入少许食用盐（约1克）
加入适量的胡椒粉（约0.5克）
加入适量的清水
再加入1小勺土豆淀粉搅拌均匀
最后再加入少许香油即可
下一步开始制作
首先我们在锅中加入适量的清水和食用盐
大火烧开之后加入切好的玉米等辅料焯水（青红椒，红萝卜）
中途加入适量的植物油保色
焯水至断生之后倒出控水备用
锅烧热之后加入适量的底油滑锅
然后将热油倒出之后重新加入底油
然后将腌制好的兔肉下锅滑散
同学们兔肉下锅不可以马上搅动
必须煎几秒钟后再翻动
否则容易脱桨或者粘锅
兔肉滑散（断生）之后加入姜葱爆香
姜葱爆香之后加入辅料爆炒几下
辅料爆香之后加入调好的料汁（注：即味汁，芡汁，碗汁）
然后翻炒几下收汁亮芡后即可出锅装盘
此菜为清甜清淡为主
不适合重油重辣
兔肉最好去骨再烹饪
这样更适合老人孩子
下面开始成品展示
下面开始技术总结：
第一，玉米以新鲜嫩玉米为佳，配上青红椒胡萝卜丰富颜色观感
第二，兔肉看似很嫩实际筋膜较多，烹饪前最好用小苏打或者食用碱破坏肌纤维，使其充分吸收水分变嫩
第三，兔肉成熟后会变大所以应尽量切得小颗且均匀
第四，原料下锅前段大火翻炒，后半段需改为重小火收汁亮芡成菜更美观
玉米嫩兔的技术总结完毕
```

**Comment by SilvesterDong** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“玉米嫩兔”的家常做法，清甜型川菜，口感嫩滑
Chef Wang teaches you: "Stir-fried tender rabbit with corn", a sweet fresh Sichuan dish with tender texture.

简介
大家好，今天给大家介绍一道清甜型川菜“玉米嫩兔”，其口感嫩滑口味清淡，别有一番风味。其实大家对川菜一直的印象都偏麻辣重口，其实不然，川菜讲究百菜百味，单单一个麻辣都分非常多种味型。以后我还会分享更多更丰富的菜品，来带大家了解更多！
Hello, today I would like to introduce to you a sweet fresh Sichuan cuisine "Stir-fried tender rabbit with corn", the taste is tender and fresh. In fact, people's impression of Sichuan cuisine is that it is spicy and heavy, but this is actually not the case, Sichuan cuisine emphasizes a hundred dishes with a hundred different flavors. In the future I will share more to let you guys to know more!

字幕
哈喽大家好我是王刚	
Hello, everyone. I'm Wang Gang.	
本期视频我和大家分享一道家常菜	
In this video I'm sharing a homestyle dish with you.	
玉米嫩兔	
Stir-fried tender rabbit with corn	
首先我们准备现宰杀的肉兔半只	
First, let's prepare half of a freshly slaughtered rabbit.	
砍下前后腿之后再依次的将肋骨，腿骨，脊椎骨取下	
Cut off the front and back legs and then remove the ribs, leg bones, and the spine.	
去骨的目的是方便老人和小孩食用	
The purpose of deboning is to make it easier for the elderly and children to eat.	
当然嫌麻烦的同学也可以忽略	
Of course, if you don't mind, you can ignore it.	
然后直接将兔肉先切成小条再切成小颗粒	
Then cut the rabbit into small strips before cutting it into small pieces.	
同学们切记兔肉的胸部部分韧劲比较强	
Remember, the breast part of the rabbit is tougher.	
所以在切的时候必须将菜刀磨锋利	
That's why you have to sharpen your knife before you cut it.	
兔丁切好之后下一步开始初加工	
Once the rabbit pieces are cut, the next step is to start preparing before marinate.	
盆中加入少许的小苏打（1克）	
Add a dash of baking soda (1 gram) to the pot	
然后加入适量的冷水抓洗1分钟	
Then add some cold water and scrub for 1 minute.	
这一步的目的是去除血水和增加兔丁的嫩度	
The purpose of this step is to remove blood and increase the tenderness of the rabbit.	
抓洗干净之后捞出挤干水分备用	
Rinse and dry out the water.	
下一步开始准备腌制	
Next, start marinating.	
盆中加入少许的食用盐（约0.5克）	
Add a dash of table salt to the pot (about 0.5 grams)	
加入适量的黄酒搅拌至上劲	
Add some huangjiu rice wine and stir until thickened.	
中途加入适量的红薯淀粉搅打	
Stir in some sweet potato starch halfway through.	
没有红薯粉淀粉的同学可以用土豆或者玉米淀粉代替	
If you don't have sweet potato starch, you can also use potato or corn starch instead.	
淀粉拌匀之后再加入少许的蛋清增加嫩滑度	
Add a bit egg white after mixing with starch to increase tenderness.	
最后加入适量的植物油拌匀即可	
Finally, add some vegetable oil and mix well.	
下一步开始准备辅料	
Start preparing other ingredients next.	
准备嫩玉米2根均匀的取下玉米粒备用	
Prepare 2 tender corns and remove the corn kernels.	
采用新鲜的玉米粒香味和口感最佳	
Use fresh tender corns for best flavor and texture.	
没有的同学也可以用玉米罐头代替	
For those of you who don't have it, you can use canned corn kernels instead.	
准备青红椒各半个去籽之后切成小颗粒备用	
Prepare half of each green and red pepper, remove the seeds and cut into small pieces.	
同学们最好选择略带甜味的辣椒	
It's better to choose the mildly sweet peppers.	
这样成菜的口味更加温和清甜	
This gives the dish a milder, sweeter taste.	
再准备红萝卜1小块切成小粒备用	
And prepare 1 small carrot, cut into small pieces.	
红萝卜可以增加菜品的颜色和口感	
Carrots can add color and texture to this dish	
最后准备少许的生姜和小葱白切成小粒即可	
Finally, prepare a small piece of ginger and scallion chopped into small pieces.	
下一步开始调料汁	
Start mixing the sauce next.	
碗中加入少许食用盐（约1克）	
Add a pinch of table salt to the bowl (about 1 gram)	
加入适量的胡椒粉（约0.5克）	
Add a bit white pepper powder (about 0.5 grams)	
加入适量的清水	
Add some water	
再加入1小勺土豆淀粉搅拌均匀	
Add 1 spoon of potato starch and mix well	
最后再加入少许香油即可	
Add a little more sesame oil at the end	
下一步开始制作	
Start cooking next.	
首先我们在锅中加入适量的清水和食用盐	
First let's add some water and salt to the wok.	
大火烧开之后加入切好的玉米等辅料焯水（青红椒，红萝卜）	
Add the corn kernels and other accessories to blanch on high heat (green and red peppers, carrots)	
中途加入适量的植物油保色	
Add some vegetable oil to preserve the color halfway through.	
焯水至断生之后倒出控水备用	
Blanch the vegetables until they are half cooked, then pour them out.	
锅烧热之后加入适量的底油滑锅	
And then heat the wok, and add some oil to grease the wok.	
然后将热油倒出之后重新加入底油	
Then pour out the hot oil and add some base oil again.	
然后将腌制好的兔肉下锅滑散	
Then slide the marinated rabbit into the wok.	
同学们兔肉下锅不可以马上搅动	
Attention, don't stir the rabbit right away after it's in the wok.	
必须煎几秒钟后再翻动	
Must fry for a few seconds before stirring.	
否则容易脱浆或者粘锅	
Otherwise, it's easy to de-starch or stick to the wok.	
兔肉滑散（断生）之后加入姜葱爆香	
After the rabbit meat is half cooked, add the ginger and scallion and bring out the aroma.	
姜葱爆香之后加入辅料爆炒几下	
After the aroma is out, add in the vegetables and stir-fry a few times.	
辅料爆香之后加入调好的料汁（注：即味汁，芡汁，碗汁）	
After the ingredients are bursting with aroma, add the seasoning sauce.	
然后翻炒几下收汁亮芡后即可出锅装盘	
Then stir-fry for a few times to thicken the sauce and then ready to serve.	
此菜为清甜清淡为主	
This dish is sweet and light in nature.	
不适合重油重辣	
Not suitable for heavy oils and spices.	
兔肉最好去骨再烹饪	
The rabbit is best cooked boneless.	
这样更适合老人孩子	
It's better for elderly people and children.	
下面开始成品展示	
Let's have a look at the finished dish.	
下面开始技术总结：	
There is the technical summary.	
第一，玉米以新鲜嫩玉米为佳，配上青红椒胡萝卜丰富颜色观感	
First, fresh tender corn is best, green and red peppers and carrots will enrich color.	
第二，兔肉看似很嫩实际筋膜较多，烹饪前最好用小苏打或者食用碱破坏肌纤维，使其充分吸收水分变嫩	
Second, rabbit meat seems to be very tender, but in reality it has a lot of tendons. Before cooking, it is best to use baking soda to tenderise the muscle fibers so that they can fully absorb the moisture and become tender.	
第三，兔肉成熟后会变大所以应尽量切得小颗且均匀	
Third, the rabbit meat will become bigger when it is cooked, so it should be cut as small and evenly as possible.	
第四，原料下锅前段大火翻炒，后半段需改为重小火收汁亮芡成菜更美观	
Fourth, the rabbit frying process need to be on high heat, after add the vegetables, need to use medium low heat to thicken the sauce and brighten dish in order to make it more beautiful.	
玉米嫩兔的技术总结完毕	
Technology summary of Stir-fried tender rabbit with corn is complete.

**Comment by immoonancient** [comment]
bot, please upload on behalf of the assignee

标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“玉米嫩兔”的家常做法，清甜型川菜，口感嫩滑
Chef Wang teaches you: "Stir-fried tender rabbit with corn", a sweet fresh Sichuan dish with tender texture.

简介
大家好，今天给大家介绍一道清甜型川菜“玉米嫩兔”，其口感嫩滑口味清淡，别有一番风味。其实大家对川菜一直的印象都偏麻辣重口，其实不然，川菜讲究百菜百味，单单一个麻辣都分非常多种味型。以后我还会分享更多更丰富的菜品，来带大家了解更多！
Hello, today I would like to introduce to you a sweet fresh Sichuan cuisine "Stir-fried tender rabbit with corn", the taste is tender and fresh. In fact, people's impression of Sichuan cuisine is that it is spicy and heavy, but this is actually not the case, Sichuan cuisine emphasizes a hundred dishes with a hundred different flavors. In the future I will share more to let you guys to know more!

字幕

哈喽大家好我是王刚
Hello, everyone. I'm Wang Gang.

本期视频我和大家分享一道家常菜
In this video I'm sharing a homestyle dish with you.

玉米嫩兔
Stir-fried tender rabbit with corn

首先我们准备现宰杀的肉兔半只
First, let's prepare half of a freshly slaughtered rabbit.

砍下前后腿之后再依次的将肋骨，腿骨，脊椎骨取下
Cut off the front and back legs and then remove the ribs, leg bones, and the spine.

去骨的目的是方便老人和小孩食用
The purpose of deboning is to make it easier for the elderly and children to eat.

当然嫌麻烦的同学也可以忽略
Of course, if you don't mind, you can ignore it.

然后直接将兔肉先切成小条再切成小颗粒
Then cut the rabbit into small strips before cutting it into small pieces.

同学们切记兔肉的胸部部分韧劲比较强
Remember, the breast part of the rabbit is tougher.

所以在切的时候必须将菜刀磨锋利
That's why you have to sharpen your knife before you cut it.

兔丁切好之后下一步开始初加工
Once the rabbit pieces are cut, the next step is to start preparing before marinate.

盆中加入少许的小苏打（1克）
Add a dash of baking soda (1 gram) to the pot

然后加入适量的冷水抓洗1分钟
Then add some cold water and scrub for 1 minute.

这一步的目的是去除血水和增加兔丁的嫩度
The purpose of this step is to remove blood and increase the tenderness of the rabbit.

抓洗干净之后捞出挤干水分备用
Rinse and dry out the water.

下一步开始准备腌制
Next, start marinating.

盆中加入少许的食用盐（约0.5克）
Add a dash of table salt to the pot (about 0.5 grams)

加入适量的黄酒搅拌至上劲
Add some huangjiu rice wine and stir until thickened.

中途加入适量的红薯淀粉搅打
Stir in some sweet potato starch halfway through.

没有红薯粉淀粉的同学可以用土豆或者玉米淀粉代替
If you don't have sweet potato starch, you can also use potato or corn starch instead.

淀粉拌匀之后再加入少许的蛋清增加嫩滑度
Add a bit egg white after mixing with starch to increase tenderness.

最后加入适量的植物油拌匀即可
Finally, add some vegetable oil and mix well.

下一步开始准备辅料
Start preparing other ingredients next.

准备嫩玉米2根均匀的取下玉米粒备用
Prepare 2 tender corns and remove the corn kernels.

采用新鲜的玉米粒香味和口感最佳
Use fresh tender corns for best flavor and texture.

没有的同学也可以用玉米罐头代替
For those of you who don't have it, you can use canned corn kernels instead.

准备青红椒各半个去籽之后切成小颗粒备用
Prepare half of each green and red pepper, remove the seeds and cut into small pieces.

同学们最好选择略带甜味的辣椒
It's better to choose the mildly sweet peppers.

这样成菜的口味更加温和清甜
This gives the dish a milder, sweeter taste.

再准备红萝卜1小块切成小粒备用
And prepare 1 small carrot, cut into small pieces.

红萝卜可以增加菜品的颜色和口感
Carrots can add color and texture to this dish

最后准备少许的生姜和小葱白切成小粒即可
Finally, prepare a small piece of ginger and scallion chopped into small pieces.

下一步开始调料汁
Start mixing the sauce next.

碗中加入少许食用盐（约1克）
Add a pinch of table salt to the bowl (about 1 gram)

加入适量的胡椒粉（约0.5克）
Add a bit white pepper powder (about 0.5 grams)

加入适量的清水
Add some water

再加入1小勺土豆淀粉搅拌均匀
Add 1 spoon of potato starch and mix well

最后再加入少许香油即可
Add a little more sesame oil at the end

下一步开始制作
Start cooking next.

首先我们在锅中加入适量的清水和食用盐
First let's add some water and salt to the wok.

大火烧开之后加入切好的玉米等辅料焯水（青红椒，红萝卜）
Add the corn kernels and other accessories to blanch on high heat (green and red peppers, carrots)

中途加入适量的植物油保色
Add some vegetable oil to preserve the color halfway through.

焯水至断生之后倒出控水备用
Blanch the vegetables until they are half cooked, then pour them out.

锅烧热之后加入适量的底油滑锅
And then heat the wok, and add some oil to grease the wok.

然后将热油倒出之后重新加入底油
Then pour out the hot oil and add some base oil again.

然后将腌制好的兔肉下锅滑散
Then slide the marinated rabbit into the wok.

同学们兔肉下锅不可以马上搅动
Attention, don't stir the rabbit right away after it's in the wok.

必须煎几秒钟后再翻动
Must fry for a few seconds before stirring.

否则容易脱浆或者粘锅
Otherwise, it's easy to de-starch or stick to the wok.

兔肉滑散（断生）之后加入姜葱爆香
After the rabbit meat is half cooked, add the ginger and scallion and bring out the aroma.

姜葱爆香之后加入辅料爆炒几下
After the aroma is out, add in the vegetables and stir-fry a few times.

辅料爆香之后加入调好的料汁（注：即味汁，芡汁，碗汁）
After the ingredients are bursting with aroma, add the seasoning sauce.

然后翻炒几下收汁亮芡后即可出锅装盘
Then stir-fry for a few times to thicken the sauce and then ready to serve.

此菜为清甜清淡为主
This dish is sweet and light in nature.

不适合重油重辣
Not suitable for heavy oils and spices.

兔肉最好去骨再烹饪
The rabbit is best cooked boneless.

这样更适合老人孩子
It's better for elderly people and children.

下面开始成品展示
Let's have a look at the finished dish.

下面开始技术总结：
There is the technical summary.

第一，玉米以新鲜嫩玉米为佳，配上青红椒胡萝卜丰富颜色观感
First, fresh tender corn is best, green and red peppers and carrots will enrich color.

第二，兔肉看似很嫩实际筋膜较多，烹饪前最好用小苏打或者食用碱破坏肌纤维，使其充分吸收水分变嫩
Second, rabbit meat seems to be very tender, but in reality it has a lot of tendons. Before cooking, it is best to use baking soda to tenderise the muscle fibers so that they can fully absorb the moisture and become tender.

第三，兔肉成熟后会变大所以应尽量切得小颗且均匀
Third, the rabbit meat will become bigger when it is cooked, so it should be cut as small and evenly as possible.

第四，原料下锅前段大火翻炒，后半段需改为重小火收汁亮芡成菜更美观
Fourth, the rabbit frying process need to be on high heat, after add the vegetables, need to use medium low heat to thicken the sauce and brighten dish in order to make it more beautiful.

玉米嫩兔的技术总结完毕
Technology summary of Stir-fried tender rabbit with corn is complete.
