### ISSUE TITLE
[华农兄弟] 华农兄弟从早忙到晚给猪煮了一大锅好吃的顺便打了几只地雷蜂 - https://youtu.be/X73HA3NZq5o

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1564]
https://youtu.be/X73HA3NZq5o
<p>&#35270;&#39057;&#21457;&#24067;&#20110; October 14, 2020 at 11:30AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/X73HA3NZq5o

#华农兄弟：从早忙到晚，给猪煮了一大锅好吃的，顺便打了几只地雷蜂
#Huanong Brothers: Busy day! We cook a pot of good food for the pigs and also slap down some wasps.
#Huanong Brothers: A busy day from daylight to dark. We cook a big pot of good food for the pigs. We also slap down a couple of landmine wasps.

0:00:00.000,0:00:03.492
# 大家好  今天天氣比較好哦   剛好把刀磿一下
Hi everyone! The weather today is rather good. Just now I’m sharpening this knife.

0:00:03.492,0:00:06.851
# 你看這個刀都已經生鏽了 我去上山砍點柴
Look! This knife is already rusted. I’m going onto the hill and chop some firewood.

0:00:07.387,0:00:10.038
# 砍點柴用來  用來煮一下那個豬食
I’m gonna pick some firewood, and cook some, some pigwash.

0:00:10.461,0:00:12.978
# 這幾天的豬都餓的不行啦
The pigs are starving to death these days.

0:00:14.606,0:00:18.252
# 砍點柴回來煮熟  把那個豬食煮熟  煮熟來再給它吃
I’l gonna chop some firewood and then cook it, I mean, cook the pigwash. Then I can feed them.

0:00:27.131,0:00:29.609
# 好啦  這個磿利啦
Alright! It’s sharp enough now.

0:00:30.922,0:00:31.506
# 去山上
Onto the hill!

0:00:32.068,0:00:33.150
# 山上砍點下來
Onto the hill and chop some back here.

0:00:44.106,0:00:45.551
# 搞個樹枝給它吃
Let me get them some branches.

0:00:54.442,0:00:56.136
# 這羊很喜歡吃這個樹葉的哦
The goats really like these leaves, you know.

0:01:19.901,0:01:23.393
# 你看  這羊肉包  天天跟豬混在一起哦
Look! This Lamb Bun, he’s mingling with the pigs every day.

0:01:24.558,0:01:27.304
# 不來的  它不跟  那大羊一起去玩
He’s not coming. He doesn’t, doesn’t play with the big goats.

0:01:34.859,0:01:37.739
# 你看這兩隻稍微大了一點  它們去洗澡了哦
Look! These two have grown up a bit. They have taken a bath.

0:01:38.422,0:01:39.484
# 天氣太熱了
It’s too hot now.

0:01:53.088,0:01:54.189
# 這裡有條捷徑哦
Here’s a shortcut.

0:01:54.910,0:01:58.728
# 每天山羊都從這裡  從這裡飛檐走壁
The goats go up along this path every day, flying through the cliffs and slopes.

0:01:59.848,0:02:00.891
# 其實我也可以
In fact, I can do the same as well.

0:02:07.563,0:02:09.506
# 你看  好久都沒來這裡砍竹子啦
Look! I haven’t been chopping bamboos here for a long time.

0:02:10.268,0:02:11.254
# 路都看不到啦
I can hardly see the path now.

0:02:13.150,0:02:15.896
# 清一下  清一下這個路
Let me clear, clear the path.

0:02:29.308,0:02:31.557
# 這些都可以用來當柴火啦
These can all be used as firewood.

0:02:44.414,0:02:46.931
# 把這個擺整齊  整整齊齊
They need to be put tidily, neatly and tidily.

0:02:50.427,0:02:53.345
# 這樣梱起來  這樣就紥實了這樣
Tie them up. So they’re firmly tied now.

0:02:58.119,0:03:03.000
# 要 綁著它要綁兩頭哦  如果綁一頭的話  很容易散掉啦
I gotta, I gotta tie on both ends. It might easily get loosened if it’s only tied on one end.

0:03:03.561,0:03:07.666
# 你看  這裡有一個杉樹哦  這杉樹已經死了
Look! Here’s a ceder. But this ceder is already dead.

0:03:08.555,0:03:09.617
# 所以把它砍下來
So I’ve chopped it down.

0:03:11.810,0:03:15.590
# 本來這個杉樹能值幾塊錢的  死了就不值錢了
In fact, this ceder should be worth a few bucks. But now it’s dead. It isn'tt worth anything.

0:03:19.380,0:03:21.418
# 這個杉樹表面很多刺的哦
The surface of this ceder is very spiky, you know.

0:03:22.120,0:03:23.469
# 但是經過我這樣
But after my, you know,

0:03:24.607,0:03:26.416
# 幫它條一下  修的
my polishing. It’s now,

0:03:27.158,0:03:28.431
# 光滑光滑的
shiny and smooth.

0:03:31.257,0:03:34.520
# 把這個要削尖一點哦 不削灰一點插不進去的
It needs to be sharpened a bit. Otherwise I can't pierce it in.

0:03:35.534,0:03:37.821
# 要削的  鋒利無比
It needs to be, as sharp as knife.

0:03:38.612,0:03:40.727
# 把這  插進去
Then, I can pierce it in.

0:03:42.488,0:03:43.971
# 你看  就這樣直接抬回去啦
Look! Then I can carry it back right away.

0:04:19.179,0:04:22.844
# 你看  這個黃蜂 差點就把那個蜜蜂蟄走啦
Look! This wasp, my bee was almost taken away by this wasp.

0:04:23.891,0:04:28.589
# 我就拍扁了它  你看  屁股一截都被我  攔腰折斷
So I smashed it. Look! I smashed a part of its butt, from its waist.

0:04:28.934,0:04:30.322
# 這個可以用來泡酒的哦
This can be used to make infused liquor. you know.

0:04:30.820,0:04:33.643
# 泡的酒適合我們這樣的三十歲以上的人吃
The infused liquor is really nice for those in their thirties, like us.

0:04:36.001,0:04:36.719
# 很補的
It’s really good for health.

0:04:39.463,0:04:43.510
# 你看  又打了一個  這個就是它的鍋就掛樹上的  這種蜂
Look! Here’s another one. This one have the hives hanging on the tree, this kind of wasps.

0:04:44.285,0:04:46.304
# 剛才我打的那個就是地  地下的
The previous one lived on the ground, underground.

0:04:47.217,0:04:48.203
# 它住地下
They live underground.

0:04:50.604,0:04:52.776
# 很危險的呦  這蟄要打針的哦
They’re really dangerous, you know. Antivenom is needed if you got stung.

0:04:54.537,0:04:55.752
# 好像又打了一個
It seems that I’ve killed another one.

0:04:57.784,0:04:58.942
# 兩個  這裡兩個
These two, these two here

0:04:59.905,0:05:02.058
# 你看  這些馬蜂太壞啦
Look! These wasps are really bad guys.

0:05:02.334,0:05:04.831
# 天天捉那個蜜子的哦  一下來就蟄
They catch the, the honey bees, you know. They catch every time they come down.

0:05:05.023,0:05:06.602
# 咬一個蜂  咬一個那個
Once they bite the bee, bite the, I mean,

0:05:06.909,0:05:09.789
# 那個小蜜蜂  它就把它就  就飛跑啦
the little bees, they, they fly away immediately.

0:05:10.625,0:05:12.434
# 它以吃蜜蜂為主
They mainly feed on bees.

0:05:13.345,0:05:15.517
# 太壞了這些蜂  來一個我殺一個
These wasps are simply too bad. No wasp can leave here alive.

0:05:15.846,0:05:20.391
# 這三個是那個  住地下的  地雷蜂  我們這邊叫地雷蜂
These three are, you know, living underground. Landmine wasps. Here we call them landmine wasps.

0:05:20.391,0:05:24.132
# 這個就是住樹上的 我們叫小馬蜂  這個沒那麼大
These are living on the tree. We call them little wasps. These are not that big.

0:05:24.841,0:05:27.205
# 它們都以吃這個  吃肉為主的這種
They mainly feed on, you know, mainly feed on meat, these wasps.

0:05:28.349,0:05:30.674
# 你看這個蜜蜂  就是被這個大黃蜂
Look! The bee, was caught by the,

0:05:30.674,0:05:32.559
# 吊著  吊起來被我拍下來的
caught by the wasp. I slapped it down.

0:05:33.498,0:05:34.580
# 被它蟄了一下
It was stung.

0:05:36.111,0:05:38.494
# 就被這個大黃蜂蟄一下  這個蜂蜜就
Just a single sting by this wasp, and this bee is,

0:05:39.251,0:05:40.122
# 一命鳴呼啦
is already dying.

0:05:40.989,0:05:42.951
# 大個七八倍哦  這個
It’s seven or eight times larger, the wasp.

0:05:44.817,0:05:46.109
# 你看  太壞拉它們
Look! They’re simply too bad.

0:05:46.798,0:05:48.115
# 都是還活的
They’re still alive.

0:05:48.941,0:05:53.161
# 還沒完全死亡  但是它的針已經沒啦  被我削掉啦
They’re not completely dead. But the sting is no longer there. I’ve chopped it away.

0:05:53.848,0:05:57.226
# 這樣才安全一點  要不然蟄下真的要打針的  這個
It’s much safer. Otherwise, antivenom is a must if anyone gets stung, really.

0:05:58.068,0:06:00.317
# 不打針的話這全身都會痛
Othwerise, the pain may spread throughout the body.

0:06:01.178,0:06:04.154
# 來一個我就殺一個  來一百個我就殺一百個
No wasp can leavehere alive, be it one wasp for a hundred wasps.

0:06:04.403,0:06:06.556
# 來一窩  把你的窩都掏掉
If I see a hive, I’m gonna raid the hive.

0:06:07.847,0:06:08.622
# 拿來泡酒
Then take everything to make infused liquor.

0:06:11.417,0:06:15.981
# 這些就不要啦  下次  下次巿空我去把它的窩挖回來
But not this time. Next time, next time when I have more time, I’m gonna raid their hive and take it back.

0:06:17.340,0:06:23.377
# 那麼大  真的  人都被它蟄死 這種  這種馬蜂
It’s so big, really. It kills, if something is stung by this, this kind of wasps.

0:06:32.018,0:06:34.056
# 你看  它屁股裡面全是空的哦
Look! Its butt is all empty inside, you know,

0:06:34.420,0:06:38.027
# 就一根腸子在那裡  甚麼都沒有那根腸子應該是
except a single gut inside. Nothing else. I think they gut should be,

0:06:38.676,0:06:40.580
# 輸  輸毒液的
trans, transfusing the venom.

0:06:42.295,0:06:43.434
# 針都被我拍下來啦
I’ve already slapped off the sting.

0:06:46.189,0:06:48.648
# 叫你不老實  吃了我多少小蜜蜂
It’s all because you’re bad. How many bees have you eaten from my place?

0:06:54.206,0:06:56.110
# 你看  這個是毒針哦  那麼長
Look! This is the venomous sting. It’s so long.

0:06:56.790,0:06:59.441
# 插入人體的話  有致拿的風險哦
There's a lethal risk if it's pierced into human body.

0:07:02.295,0:07:03.434
# 這個針很鋒利的  你看
This sting is really sharp. Look!

0:07:04.372,0:07:05.741
# 戳進去都沒反應去
The leaf is not moving at all.

0:07:10.508,0:07:11.743
# 隨便一戳就進去啦
It goes inside immediately, without much effort.

0:07:13.312,0:07:14.068
# 太壞人啦
It’s too scary.

0:07:14.867,0:07:16.542
# 皮膚的話一戳就進去了
It happens to skin as well. It goes inside immediately.

0:07:19.069,0:07:20.648
# 像這種杆都可以戳的進
It can pierce this kind of stem as well.

0:07:21.001,0:07:22.312
# 你看戳這個杆
Have a look at this stem.

0:07:24.666,0:07:26.666
# 好殘忍啊  你看  戳進去了
So cruel! Look! It’s inside now.

0:07:27.700,0:07:29.490
# 插在這裡  誒呀  太危險了
It’s pierced into the stem. Eya! Too dangerous.

0:07:29.892,0:07:31.930
# 我還是 放在火堆裡燒掉它去算啦
I’d better, burn everything in a fire.

0:07:33.538,0:07:34.696
# 戳到人就不好啦
It would be too bad if somebody got stung.

0:07:42.416,0:07:46.004
# 你看 剛好攝影小哥家的那個紅薯  它的葉子好多的哦
Look! I just so happens that we pass by Mr. Cameraman’s sweet potatoes. There are a lot of leaves, you know.

0:07:47.349,0:07:48.431
# 搞點給豬吃
Let me fetch some for the pig.

0:07:50.207,0:07:51.556
# 你看 他家的紅薯
Look! These are his sweet potatoes.

0:07:52.469,0:07:53.665
# 土都被撐開啦
The soil is already cracked open.

0:07:55.211,0:07:56.101
# 絕對好吃
It’s absolutely tasty.

0:07:58.226,0:07:59.212
# 連鍋端起
I’m gonna dig out everything.

0:08:00.327,0:08:03.475
# 你看  直接這個  直接可以用來餵豬的
Look! This can, this can be used to feed the pigs right away.

0:08:04.304,0:08:06.247
# 這個要把它搞的整整齊齊
I gotta place them neatly and tidily.

0:08:07.466,0:08:08.605
# 搞整齊來一點
Let me tidy them up.

0:08:14.331,0:08:16.714
# 這樣的土質種出來的紅薯才好吃
This is exactly the soil for growing tasty sweet potatoes.

0:08:18.422,0:08:19.599
# 這個就靚了哦
This is really beautiful.

0:08:22.738,0:08:26.498
# 你看  就搞了點紅薯  這個紅  紅薯藤也帶回去
Look! So we have a little bit sweet potatoes here. I’m gonna take these sweet pota, sweet potato leaves back as well.

0:08:33.724,0:08:35.035
# 你看  好薯葉也搞回來了
Look! The sweet potatoes leaves are taken back now.

0:08:35.911,0:08:39.480
# 我要把它全部切  打碎  打碎之後再用那個鍋來煮
I’m gonna cut, smash, smash them all. And then cook everything in that pot.

0:08:40.082,0:08:41.795
# 煮完之後就可以給豬吃啦
Then I can give it to the pigs.

0:08:49.743,0:08:51.475
# 你看  這個柴很瘦的哦
Look! This piece of wood is very dry and thin, you know.

0:08:51.977,0:08:54.781
# 引火很好的  以前我們家裡都用這個來引火
It glows very well. We used it to set a fire at home in the past.

0:08:56.790,0:08:57.891
# 一燒就冒煙
The smoke comes immediately.

0:09:31.853,0:09:32.353
# 你看
Look!

0:09:33.743,0:09:34.595
# 就那麼一點點
Just a tiny little bit here.

0:09:35.456,0:09:36.000
# 夠了
It’s enough.

0:09:37.459,0:09:38.426
# 你看  搞點米
Look! Put some rice.

0:09:39.496,0:09:42.000
# 加點這個  把這個葉子  把它全部搞下去
Put some, well, these leaves, put them all inside.

0:09:48.103,0:09:49.089
# 放點鹽
Put some salt.

0:09:51.348,0:09:52.506
# 這個鹽是
The salt is,

0:09:53.253,0:09:54.488
# 用來促進消化
is to enhance digestion,

0:09:55.298,0:09:56.762
# 捉進它的新陳代謝
enhance their metabolism.

0:10:03.001,0:10:03.910
# 嗯 可以
Um! Alright!

0:10:10.120,0:10:12.426
# 好啦  先慢慢燜一下
Good! Stew it for a while first.

0:10:14.138,0:10:17.918
# 蓋一下  湊個數就好了  又不是我吃
Cover it up. Quantity rather than quality. It’s not for me anyway.

0:10:24.815,0:10:28.078
# 這個就讓它慢慢煮哦  要煮半個小時左右才可以的哦
Just leave it here. It may need some time. It needs to be cooked for around half an hour, you know.

0:10:28.676,0:10:30.121
# 我洗兩個番薯吃一下
Let me wash a couple of sweet potatoes for myself first,

0:10:31.242,0:10:32.457
# 就剛挖回來的番薯
the freshly dug sweet potatoes.

0:10:34.314,0:10:35.357
# 你看  紅的
Look! It's red.

0:10:39.678,0:10:41.295
# 這個紅薯很好吃的哦  這個紅薯
These sweet potatoes are really tasty, these sweet potatoes.

0:10:41.718,0:10:43.335
# 沒有施肥料  甚麼都沒施
They’ve never been fertilised, nor taken care off.

0:10:43.923,0:10:45.713
# 就讓它自然生長  長出來的
They were simply left to grow, grow naturally.

0:10:47.707,0:10:48.750
# 賣相不好看
They don’t look really good.

0:10:50.905,0:10:51.987
# 但吃就好吃
But they taste really good.

0:10:53.867,0:10:58.393
# 我吐在這裡等下羊會下來吃掉的  那羊  甚麼都吃
I spit it here, and the goats will eat it in a while. The goats, eat everything.

0:11:08.485,0:11:10.102
# 你看  小時候我們就是這樣
Look! That’s what we did when we were small.

0:11:10.856,0:11:13.334
# 煮一大鍋  比這個鍋大十幾倍哦
We cooked with a huge pot, a dozen times larger than this one.

0:11:14.115,0:11:17.072
# 然後那個豬就吃一個  一個星期啦
And then it was enough for the pigs for a, for a whole week.

0:11:17.072,0:11:20.040
# 一個星期都不用去那個  不用去砍竹子
And we didn't need to, I mean, chop the bamboos for the whole week.

0:11:22.621,0:11:27.000
# 還沒煮爛  要等一下再爛  爛了之後才可以哦
It’s still not yet mushy. It needs a bit more time. It needs to be mushy first.

0:11:27.438,0:11:29.088
# 這個香番薯葉很貴的哦
These sweet potato leaves are really expensive, you know.

0:11:30.316,0:11:32.794
# 城市裡面都賣幾塊錢一斤
In the city, half a kilogram of them already costs a few RMB.

0:11:33.256,0:11:35.428
# 我們家裡只能餵 用來餵豬
But in the village, they’re nothing but pigwash.

0:11:35.791,0:11:38.155
# 好多  一田都是  現在都沒人要
There are a lot, all over the field. But now, nobody wants them.

0:11:38.678,0:11:41.673
# 他們砍了直接放到旁邊讓它 腐蝕掉
After chopping off the leaves, they simply throw them onto the roadside right away, and let the leaves decay.

0:11:42.543,0:11:43.376
# 再煮一下
Cook it for a bit longer.

0:11:45.001,0:11:45.719
# 不夠爛
It’s still not mushy enough.

0:12:01.816,0:12:06.361
# 你看 這個是  這是我家裡的那個米糖哦
Look! This is, this is our own rice bran.

0:12:09.102,0:12:12.594
# 在家裡面  我都是自  自己碾米吃
Here in the village, I always mill, mill my own rice.

0:12:13.211,0:12:16.436
# 碾的特別香  就  就剩下的這個米糠
It smells exceptionally good! Now only, only the rice bran is left.

0:12:17.339,0:12:18.077
# 放點下去給它
Put some into the pigwash.

0:12:27.365,0:12:28.447
# 拗一下就可以了
Stir it and it’s done.

0:12:31.726,0:12:33.000
# 現在就很香啦
Now it smells really good.

0:12:34.523,0:12:36.427
# 以前的豬食就是這樣子的
That’s how we made pigwash in the past.

0:12:38.714,0:12:41.919
# 把它抬下去  放到水裡面泡一下  太燙啦這樣
Let’s carry it there and soak it into the water. It’s too hot now.

0:12:42.373,0:12:44.717
# 等下不知道等到明天都可能餵不了
Otherwise, I don’t even know if I can feed them tomorrow.

0:12:48.889,0:12:49.875
# 讓它降下溫
Let it cool down.

0:12:51.955,0:12:53.458
# 哇 好香啊
Wa! It smells so good!

0:12:54.779,0:12:56.014
# 好香  要不要來一點
Really good! Do you want some?

0:12:56.848,0:12:58.484
# 很好吃的  不騙你的
It tastes really good! I’m not kidding.

0:12:59.245,0:13:03.120
# 很香的哦  這個哦  就是很乾淨的  就是薯藤葉加米糠
It smells so good! You know, this is really clean and pure, only sweet potato leaves and rice bran, nothing else.

0:13:03.718,0:13:05.393
# 煮出來的  就煮成這樣子
And that’s, that’s how the product looks like.

0:13:08.160,0:13:09.643
# 等冷了之後再來餵
I’ll feed it to the pig once it cools down.

0:13:10.530,0:13:12.549
# 現在還好燙啊  冒煙
It’s still very hot. The steam is still coming out.

0:13:13.518,0:13:15.786
# 哎呦  還那麼燙
Aya! It’s still so hot.

0:13:17.129,0:13:20.507
# 等下 等下再來餵  那豬都睡覺了
Later, I’ll feed them later. The pigs are all sleeping now.

0:13:21.999,0:13:25.453
# 這個洗車的是攝影小哥買回來的  也可以當槍使
Mr. Cameraman bought it for washing the cars. But it can also be used as a gun.

0:13:26.332,0:13:29.748
# 瞄準 射擊  很準的哦
Aim! Shoot! It aims really well, you know.

0:13:30.001,0:13:31.197
# 你看  這裡有個柚子皮
Look! Here’s a pomelo peel.

0:13:58.700,0:14:00.336
# 那個豬食太難冷啦
The pigwash takes too much time to cool down.

0:14:00.723,0:14:03.718
# 把它沖一下  把它用這個匴子來裝  晾的更快一點
Let me rinse it, put the pigwash into this basin. It cools a bit faster.

0:14:04.216,0:14:06.809
# 不然等下天黑了豬都沒有晚餐吃
Otherwise the pigs couldn’t have their dinner even when it gets dark.

0:14:26.693,0:14:27.947
# 把它倒到這裡來
Let me pour everything here.

0:14:32.334,0:14:35.099
# 拿點來餵魚也可以的  這魚也喜歡吃的
It can also be used to feed the fish. The fish like it very much too.

0:14:37.390,0:14:39.390
# 這裡面養了好多魚的這裡
Here are a lot of fish, here.

0:14:40.815,0:14:42.834
# 原來是少有一百多條
There should be at least a hundred originally.

0:14:43.322,0:14:46.298
# 草魚  全是小的 很小的草魚
Grass carps, all are small, really small grass carps.,

0:14:46.778,0:14:48.185
# 就手指那麼大的草魚
grass carps which are as big as a finger.

0:14:53.058,0:14:56.665
# 海浪就是這樣形成的  你看 波濤洶湧
That’s how waves are formed. Look! Roaring waves.

0:14:59.903,0:15:02.439
# 快點冷啊  我豬都等下及啦
Hurry up! My pigs are losing their patience.

0:15:05.921,0:15:09.413
# 不面的魚  感覺像地震了一樣
The fish underneath, might be experiencing an earthquake.

0:15:13.139,0:15:14.680
# 哎呀  靯都濕掉啦
Aya! My shoes get wet.

0:15:23.189,0:15:25.572
# 來給它們吃啦  那麼多
Alright! Let’s feed them. Here’s so much.

0:15:29.829,0:15:31.217
# 來啊  吃大餐啦
C’mon! Time for a big feast!

0:15:47.094,0:15:49.725
# 羊也吃  羊也吃
The goats are eating too. 
Yea, the goats are eating too.

0:16:04.947,0:16:07.291
# 分開一點  這樣它們不會搶
Let me split it up, so that they won’t fight for it.

0:16:10.308,0:16:14.623
# 這裡有  這裡有哈  快吃
Here, some more here. C'mon!

0:16:20.918,0:16:22.038
# 老是打架
They’re always fighting.

0:16:24.189,0:16:26.093
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.

0:16:26.618,0:16:29.517
# 我們也要吃飯啦  看它們吃的那麼香
We’re gonna have dinner too, seeing them eating so merrily.

0:16:33.993,0:16:35.094
# 這隻小公豬
This little boar…
