### ISSUE TITLE
[华农兄弟] 华农兄弟一年又过去了再来摘点老王家的柿子顺便摘点老刘家的黄豆 - https://youtu.be/bcm0O8qB2zs

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1568]
https://youtu.be/bcm0O8qB2zs
<p>&#35270;&#39057;&#21457;&#24067;&#20110; October 16, 2020 at 11:30AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/bcm0O8qB2zs

#华农兄弟：一年又过去了，再来摘点老王家的柿子，顺便摘点老刘家的黄豆

#Huanong Brothers: A year has passed. Pick some persimmons from Wang's, and some beans from Liu's.
#Huanong Brothers: A year has passed. We pick some persimmons from Wang's, and some beans from Liu's, again.

0:00:00.000,0:00:04.004
# 去年老王家的杮子哦 今年又長了  一樹都是
Remember Wang’s persimmon trees last year? They’re growing well again this year. The persimmons are all over the trees.

0:00:05.065,0:00:08.124
# 我用那望遠看了一下  好多啊
There are a lot. I just saw them with a telescope.

0:00:09.141,0:00:10.452
# 上次在這裡摔了一跤
Last time I fell here.

0:00:11.223,0:00:12.457
# 這次不能摔跤了
No more this time.

0:00:14.249,0:00:16.760
# 啊這裡 有水 麻煩了
Ah! Here, here’s water. That’s not good.

0:00:17.503,0:00:18.571
# 幸好我有刀
I have a knife with me, fortunately.

0:00:19.653,0:00:23.095
# 逢山開路  遇水架橋  哪有上不去的
Though the mountains are high and the oceans are wide, I can always create my path.

0:00:23.543,0:00:25.032
# 哎呀  甘蔗哦
Aya! Sugarcanes!

0:00:25.541,0:00:26.724
# 你看  他種的這個
Look! He planted them,

0:00:27.488,0:00:28.543
# 他種的這個甘蔗
he planted these sugarcanes.

0:00:29.741,0:00:31.792
# 這種甘蔗很好吃的哦  但是在太嫩了
This kind of sugarcane is really tasty. But they’re too young now.

0:00:31.792,0:00:33.269
# 它沒有  它  不能吃那麼快
They don’t, they, not so soon,

0:00:33.831,0:00:35.512
# 到要天的時候就有的吃啦
not until winter, before they can be eaten.

0:00:35.918,0:00:38.505
# 你看  這兩根是我的  這一根是他的
Look! These two are mine, and this one is his.

0:00:40.187,0:00:41.294
# 挨在一起種的
We planted them side by side.

0:00:45.451,0:00:46.481
# 路都沒有啦
I can’t even see the path.

0:00:52.348,0:00:53.633
# 這路也太難走啦
Walking on this path is really hard.

0:01:06.950,0:01:08.171
# 上去看一下有沒有
I'm gonna go up there and see if there are any.

0:01:08.871,0:01:10.488
# 你看這樹  還是那麼大
Have a look at this tree. It’s still that big.

0:01:11.100,0:01:12.092
# 不好上哦
Not and easy climb

0:01:18.190,0:01:19.641
# 啊  終於看到幾個了
Ah! Finally, I can see some of them now.

0:01:22.748,0:01:23.740
# 這個快黃啦
They'll be ripe very soon.

0:01:30.540,0:01:31.327
# 黃的哦
This one is ripe.

0:01:32.375,0:01:35.294
# 這兩個杮子  這個可以吃的哦這個  這個直接可以咬的
These two persimmons… This can be eaten now, this one. I can bite it right away.

0:01:41.291,0:01:43.482
# 啊~好澀啊
Ah~ It’s so acerbic!

0:01:44.531,0:01:45.120
# 哎呀
Aya!

0:01:47.628,0:01:49.985
# 本來這個不是脆杮子嗎  怎麼那麼澀
Isn't it a crunchy persimmon! Where comes the acerbic taste?

0:01:51.582,0:01:52.561
# 啊  受不了啦
Ah! I can’t stand it!

0:01:54.380,0:01:57.000
# 把它摘  把它全部摘回去吧  摘回去
Let me pick, pick them all back home, pick them back home.

0:01:58.295,0:02:00.078
# 那個甚麼 ou一下就可以啦
How do you say it? Ripen it, ripen it for a while. Then it will be fine.

0:02:00.948,0:02:01.786
# 它自己會熟的
They will become ripe by themselves.

0:02:07.899,0:02:10.269
# 應該這個皮澀  它裡面肉應該不澀
I think the acerbic taste comes from the peel, not from the pulp inside.

0:02:17.126,0:02:18.743
# 嗯  好像是誒
Um! Seems to be

0:02:21.616,0:02:22.748
# 這脆杮子
This crunchy persimmon…

0:02:25.178,0:02:25.863
# 怪不得
No wonder

0:02:28.110,0:02:29.114
# 皮不點澀
The peel is a bit acerbic.

0:02:33.331,0:02:34.335
# 你看 很脆吧
Look! It’s really crunchy, isn’t it?

0:02:39.214,0:02:40.652
# 我全部把它摘回去ou一下
Let me pick them all and ripen them at home.

0:02:41.180,0:02:41.865
# ou一下更好吃
They would taste much better.

0:02:44.307,0:02:45.796
# 我全部集中起來  摘到來
I’m gonna put them all together, pick them all,

0:02:46.545,0:02:48.175
# 放家裡  放幾天那就可以吃啦
leave them at home, store them for a few days and we can start eating.

0:02:52.960,0:02:53.747
# 就一個
Just one.

0:02:57.212,0:02:58.408
# 這裡好幾個大的
Here are a couple of big ones.

0:03:12.961,0:03:16.212
# 你看這種脆杮子 手摔就爆掉的哦  這個
Look! This kind of crunchy persimmons, simply crush when they drop, this one.

0:03:17.069,0:03:19.401
# 家  在家裡幾天就可以吃啦  很好吃的
At home, store them at home for a few days. Then they can be eaten. It’s really tasty.

0:03:23.335,0:03:24.761
# 哇  搞得蠻多的
Wa! We have quite a lot here.

0:03:25.462,0:03:26.096
# 可以啦
It’s alright now.

0:03:27.179,0:03:29.907
# 把它的樹  樹上的都  幾乎全部摘完啦
We’ve almost taken, taken everything, everything in the tree.

0:03:30.807,0:03:31.709
# 反正老王不要了
No worries. Wang doesn’t want them anymore.

0:03:35.866,0:03:36.743
# 夠吃啦
It’s enough now.

0:03:37.510,0:03:38.502
# 把它帶回去
Let me take them back.

0:03:39.184,0:03:41.478
# 袋子也沒一個  完啦
Gosh! I don’t even have a bag.

0:03:43.866,0:03:47.257
# 這個  這個杮子  好多杮子就直接這樣背回去算啦
These, these persimmons, many of them can simply be carried on the back right away.

0:03:49.025,0:03:51.663
# 回去等一下  把這個是杮子汁搞到這衣服下
Well, um… what if the juice stains on the T-shirt?

0:03:52.066,0:03:52.981
# 怕老婆罵
I risk being scolded by my wife.

0:03:53.700,0:03:54.564
# 所以挑一下
So I gotta choose,

0:03:55.018,0:03:56.150
# 把好的背回去
and take only the good ones.

0:03:57.001,0:03:58.695
# 壞的 叫攝影小哥拿
The rotten ones, I’ll ask Mr. Cameraman to take them.

0:04:02.190,0:04:04.598
# 你看 好多的  好多都是好的
Look! Many, many of them are good.

0:04:13.302,0:04:17.600
# 你看  這樣可以吧  這等一下攝影小哥會撿
Look! It should be fine, right? Mr. Cameraman will pick the rest in a while.

0:04:22.027,0:04:22.865
# 我先走啦
I’m leaving first.

0:04:27.711,0:04:30.349
# 路過老刻家的那個黃豆  他家的黃豆都熟啦
We pass by Liu’s, Liu’s beans. His beans are already ripe.

0:04:30.819,0:04:33.470
# 我再不吃掉的話等下就被那個老鼠吃掉
They would be eaten by the rats if I don’t eat them now.

0:04:35.806,0:04:38.636
# 為了不讓老鼠吃掉  我來幫他消滅
In order to safe them from the rats, I shall help him take care of them.

0:04:39.937,0:04:41.133
# 你看  草都不割
Look! He just lets the weeds grow.

0:04:44.461,0:04:45.989
# 可以哦  這些黃豆
It’s not bad, these beans.

0:04:47.146,0:04:48.572
# 都是很漂亮的哦
All are very pretty, you know.

0:04:53.717,0:04:56.636
# 要把這個葉子要摘掉  不摘掉這葉子就不好看
These leaves need to be picked away. Otherwise it doesn’t look good.

0:04:57.903,0:05:00.490
# 看到沒有  這就是粒粒飽滿
See? Every bean is round and fat.

0:05:01.216,0:05:01.927
# 又多
And there are a lot.

0:05:02.429,0:05:05.271
# 等拿回去煮一下  特別好吃的這個  放點鹽
Let me take them back and cook them. It’s exceptionally tasty, with some salt.

0:05:05.793,0:05:06.963
# 放點鹽煮一下
Cook them with some salt.

0:05:07.960,0:05:09.437
# 味道杠杠滴  你看
Delizioso! Look!

0:05:09.887,0:05:11.351
# 就這一串一串的往下煮
I just put them into the pot in bunches.

0:05:12.265,0:05:14.150
# 再多搞點  太少了
Let me take more. Too few here.

0:05:14.775,0:05:16.405
# 哎呀  割這個最好割了
Aya! Cutting this is always a pleasure.

0:05:16.569,0:05:17.637
# 一刀一個
Down the knife, off the beans

0:05:18.899,0:05:20.006
# 不用留情
No mercy

0:05:23.943,0:05:25.164
# 一刀就把它割下來
No extra effort needed.

0:05:33.064,0:05:34.132
# 好  夠啦
Alright! Enough!

0:05:36.187,0:05:37.498
# 把這葉子摘下來
Let me pick away the leaves.

0:05:46.564,0:05:47.683
# 你看  把這個黃豆
Look! The beans,

0:05:48.710,0:05:51.335
# 這樣 直直把它擺好一點
here, I leave them straight and tidy.

0:05:53.290,0:05:54.320
# 煮的才香
So that it smells good.

0:05:54.983,0:05:57.366
# 也沒多少啊這裡  我以為很多嘞
There aren’t really too many. I thought there were are lot.

0:05:58.425,0:06:00.093
# 一搞  搞出來就那麼一點點
But it, but it turns out to be just a tiny little bit.

0:06:01.779,0:06:02.771
# 這樣就可以啦
So everything is alright now.

0:06:03.702,0:06:04.655
# 加點鹽
Put some salt

0:06:06.066,0:06:07.989
# 這個鹽要稍微加多一點  沒事
No worries. It really needs slightly more salt.

0:06:09.695,0:06:13.074
# 好啦  就這樣 蓋上鍋蓋 直接煮就可以啦
Alright! That's it! Cover the lid, and I can start cooking right away.

0:06:23.132,0:06:25.464
# 好啦 半個小時  夠啦
Alright! Half an hour. It would be enough.

0:06:25.809,0:06:26.647
# 應該差不多啦
It should be done now.

0:06:27.417,0:06:30.208
# 哎呀  嗯  好香
Aya! Um! It smells so good!

0:06:31.421,0:06:32.796
# 搞一串吃一下
Let me take a bunch and have a try.

0:06:37.629,0:06:39.782
# 你看這個  這個豆子
Have a look at these, these beans.

0:06:40.743,0:06:42.051
# 嗯  很香
Um! It smells really good.

0:06:44.614,0:06:45.823
# 你看  就這樣的豆子
Look! These are the beans.

0:06:50.871,0:06:51.684
# 太好吃啦
Simply delicious

0:06:51.966,0:06:53.826
# 吃的時候要從頭到尾
It should always be eaten down from the top,

0:06:54.150,0:06:55.461
# 或者從尾吃到頭
or up from the bottom.

0:06:56.046,0:06:58.620
# 這樣就不會錯過每一個  每一粒豆子了
Then no one, no beans would be left out.

0:06:59.328,0:07:00.652
# 要是你亂吃的話到時候
But if you just follow an arbitrary order,

0:07:01.146,0:07:02.393
# 吃到哪裡你都不知道
you never know which one you have eaten.

0:07:02.870,0:07:03.734
# 誒  掉了一個
Ey? I dropped one.

0:07:05.575,0:07:07.128
# 你看  這樣
Look! I’m showing you.

0:07:08.020,0:07:09.305
# 一截一截吃過去
Eat from here, part by part.

0:07:19.066,0:07:21.334
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.

0:07:22.008,0:07:22.910
# 我要煮飯啦
I gotta cook now.

0:07:23.214,0:07:24.000
# 天氣那麼晚
It’s so late now.

0:07:24.708,0:07:26.261
# 早點吃飽  早點睡覺
Early meal means early sleep.
