### ISSUE TITLE
[华农兄弟] 华农兄弟很多粉丝问送终鸡去哪里了带大家看一下它 - https://youtu.be/DdY45J_1kGA

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1572]
https://youtu.be/DdY45J_1kGA
<p>&#35270;&#39057;&#21457;&#24067;&#20110; October 17, 2020 at 11:30AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/DdY45J_1kGA

#华农兄弟：很多粉丝问“送终鸡”去哪里了？带大家看一下它
#Huanong Brothers: Many fans ask us where the "Rooster the Final Respect" is. Let's see it today.

0:00:00.000,0:00:03.192
# 大家好 好多粉絲問我們那個送終雞去哪裡啦
Hi everyone! Many fans asked us where the “Rooster the Final Respect” has gone.
(Note: Rooster the Final Respect, translit: "song zhong ji" is a pun, homonym to Song Joong-ki in Mandarin)

0:00:03.192,0:00:05.192
# 其實在我家哦  我藏在我家啦
It’s at home with me, in fact. I hide it at home.
(Note: Rooster the Final Respect, translit: "song zhong ji" is a pun, homonym to Song Joong-ki in Mandarin)

0:00:05.624,0:00:08.674
# 要不然那  被那個狗啊  它老是  那個狗老是喜歡追它
Otherwise, the, it’s always, the dogs, the dogs always like chasing after it.

0:00:09.070,0:00:11.277
# 如果我們不在的話那個狗就把它吃了
It would just be eaten by the dogs if we're not there.

0:00:11.277,0:00:12.877
# 所以我把它藏在這裡面
That’s why I hide it here inside.

0:00:39.201,0:00:42.515
# 你看  被我抓啦  這個  就這個公雞
Look! It’s in my hands now. This one, it’s this rooster.

0:00:43.220,0:00:45.148
# 現在都好大啦  好老啊
It’s very big, very old now.

0:00:50.379,0:00:50.965
# 不叫了
It’s not yelping.

0:00:56.506,0:01:01.948
# 叫啊  叫啊  以前就咕咕咕的叫  現在不叫啦  哎呦
C’mon! Yelp! It used to yelp like “gu gu gu”. But it doesn’t yelp now. Ayo!

0:01:02.587,0:01:03.752
# 抓都不住你了
I can’t even hold you.

0:01:04.704,0:01:05.504
# 你看這它個
Have a look at its,

0:01:07.188,0:01:09.223
# (這個  這個叫甚麼)
this one. How is it called?

0:01:09.341,0:01:10.356
# (這個叫??)
It’s called wattle.

0:01:18.101,0:01:19.430
# 不動聲色  你看
It’s a statue. Look!

0:01:20.001,0:01:22.437
# 它的嘴巴這裡  很利的哦 看到沒有  啄一下
Its beak is here. It’s really sharp! See? If you got pecked,

0:01:22.708,0:01:23.980
# 肉都會啄掉一塊
a whole piece of flesh might got pecked off.

0:01:25.504,0:01:27.040
# 現在它活的好滋潤啦
It’s now having a well fulfilled life.

0:01:28.609,0:01:31.909
# 它天天跟  跟一群母雞混在一起
Every day, it mingles with a whole herd of hens.

0:01:32.669,0:01:34.191
# 滿臉紅光
It’s face is bright and red.

0:01:37.548,0:01:40.633
# 現在差不多有五六斤吧  這個小
I think it’s around three kilograms now. It’s so small.

0:01:41.067,0:01:44.259
# 這公雞長到十斤都可以長  你看它指甲  看到沒有
This kind of roosters can grow up to five kilograms. Have a look at its nails, see?

0:01:44.710,0:01:46.146
# 它這個指甲好長啦
Its nails are really long.

0:01:46.826,0:01:48.697
# 它這個老公雞就這樣子的
This is rather typical for old roosters like this one.

0:01:49.749,0:01:50.821
# 快兩年啦
It’s almost two years old now.

0:01:52.426,0:01:56.190
# 你看 那個就是閹雞來的  那個就被閹了
Look! That one is a capon. It has been neutered.

0:01:58.001,0:01:59.401
# 好  把你放走啦
Alright! I let you go.

0:02:01.057,0:02:02.957
# 咕咕咕咕咕  打架  來
Gu gu gu gu gu! C’mon! Fight!

0:02:08.550,0:02:09.429
# 它們不打
They don’t fight.

0:02:15.965,0:02:18.265
# 這個閹過的哦  閹過的漂亮點 看到沒有
This one is a capon, you know. Capons look prettier, see?

0:02:19.665,0:02:20.701
# 油光發亮的
It’s so shiny.

**Comment by vincenthychow** [comment]
已發佈
