### ISSUE TITLE
[华农兄弟] 华农兄弟吃饱喝足上山捞鱼顺便给猪起了个好听的名字 - https://youtu.be/y1UXHgRDarY

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1577]
https://youtu.be/y1UXHgRDarY
<p>&#35270;&#39057;&#21457;&#24067;&#20110; October 18, 2020 at 11:30AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/y1UXHgRDarY

#华农兄弟：吃饱喝足，上山捞鱼，顺便给猪起了个好听的名字
#Huanong Brothers: After a big feast, we catch some fish, and also give the pigs good names.
#Huanong Brothers: After a big feast, we go onto the hill and catch some fish. Also, we give the pigs good names.

0:00:00.000,0:00:02.357
# 剛剛看到這裡有一條好大的蜈蚣啊
I just saw an enormous centipedes here.

0:00:04.982,0:00:06.310
# 哇 看到啦  在這裡
Wa! I see it now. It’s here.

0:00:09.374,0:00:13.021
# 夠大條吧你看  這個蜈蚣很危險的哦  這個
It’s huge isn’t it? This centipedes is really dangerous, you know.

0:00:13.863,0:00:15.163
# 咬一下人很痛的
It hurts like hell if you got bitten.

0:00:16.368,0:00:19.850
# 剛好這裡還有 一口酒  倒下去
It just so happens that here are, some last few drops of wine. Let me pour it inside.

0:00:22.701,0:00:24.111
# 蓋子  要先那個蓋子來
The cover, I need the cover first.

0:00:28.858,0:00:30.117
# 啊  快點  喝點酒
Ah! C’mon! Drink some wine!

0:00:31.308,0:00:33.390
# 這個酒很好喝的  蓋起來
This wine tastes really good. Cover it up!

0:00:34.965,0:00:35.593
# 它一下子
Instantly,

0:00:37.374,0:00:38.880
# 沉在酒色當中
it has lost itself in debauchery.

0:00:42.417,0:00:43.498
# 給它喝點這個酒
Let it drink some of this wine.

0:00:44.538,0:00:46.373
# 這個酒可以泡著用來做那個的
It can be infused in it and make the, you know...

0:00:47.180,0:00:48.315
# 它很喜歡這裡哦
It likes this place so much.

0:00:50.302,0:00:52.769
# 泡個半個月  它就  那個味道就出來啦
Leave it here for a fortnight. Then it, the flavour will be coming out.

0:00:55.172,0:00:56.404
# 好不好玩  這裡
Is it fun here?

0:00:58.418,0:01:00.720
# 把它放在家裡  我要乾活啦
Let me leave it here. I gotta start working.

0:01:06.485,0:01:08.622
# 幹活之前要補充點能量
Before I start working, I need to refuel myself.

0:01:12.001,0:01:13.946
# 吃點這個  然後再來上山
Let me have some, this one. And then I’ll go onto the hill.

0:01:15.950,0:01:16.962
# 嗯 好香
Um! It smells so good!

0:01:17.659,0:01:18.159
# 燙皮
“Tang pi” (local snacks)

0:01:20.169,0:01:21.181
# 小狗  你們要不要
Puppies! You want some?

0:01:23.387,0:01:24.632
# 搞一點點給它
Let me give it a bit.

0:01:27.293,0:01:28.922
# 誒  會吃哦
Eh? He’s eating.

0:01:30.388,0:01:31.112
# 你要嗎
You want it?

0:01:32.906,0:01:35.153
# 要你就說啊  你又不說  我怎麼知道你要
Tell me if you want! How can I know that you want it if you don’t tell me?

0:01:41.580,0:01:42.276
# 好不好吃
Does it taste good?

0:01:43.146,0:01:43.966
# 好吃就要說啊
You gotta tell me if it tastes good.

0:01:48.259,0:01:51.165
# 你看  上癮啦  這個  這個很香的呦
Look! He can no longer resist. It, it smells really good, you know.

0:01:55.347,0:01:57.800
# 我去把上面那個魚塘把它放啦
I’m gonna go up there, and drain the ponds.

0:01:58.629,0:02:00.341
# 那個魚塘我放了好多魚下去的哦
I’ve put a lot of fish into the ponds, you know.

0:02:01.433,0:02:03.392
# 都快養了一年啦  應該也大啦
They have been there for almost a year. They should have grown up now.

0:02:04.468,0:02:06.386
# 全是蛇頭魚  跟那個鯰魚
All are snakehead fish, and also the, the catfish.

0:02:07.947,0:02:11.443
# 你看  那個羊肉包在那裡哦  偷窺我們
Look! The Lamb Bun is over there, peeping us.

0:02:14.023,0:02:14.637
# 小羊
Goaty!

0:02:15.773,0:02:16.305
# 小羊
Goaty!

0:02:17.743,0:02:18.988
# 我去抓魚你去不去
I’m gonna catch some fish. You wanna join?

0:02:22.861,0:02:24.175
# 哦  它們在這睡覺
Oh! They’re having a nap here.

0:02:25.146,0:02:26.638
# 你看  那兩條豬在這裡哦
Look! Those two pigs are here.

0:02:28.543,0:02:30.000
# 跟著那大豬在睡大覺
They’re having a big sound sleep with the big pig.

0:02:31.391,0:02:34.310
# 你們就好咯  天天不愁吃不愁穿的
I envy you so much. You never need to worry about your meals and your clothes.

0:02:34.788,0:02:35.896
# 還要我餵你
You just ask me to feed you.

0:02:37.869,0:02:39.677
# 我們不幹活就飯飯吃啦
We simply wouldn't have our share of meal if we don’t work.

0:02:41.301,0:02:43.383
# 你看  把這個草都快讓它們鋤完了
Look! They’ve almost cleared all the weeds here.

0:02:44.025,0:02:46.944
# 到時候我們直接種點象草  很靚的哦
I'll then plant some elephant grass here right away. It would be really beautiful, you know.

0:02:51.786,0:02:52.935
# 不聽話啦  現在
It’s so naughty now.

0:02:54.469,0:02:57.087
# 一 一來它就跑  以前它都很聽話的
It, it runs away once I get close. It used to be a very good piggy.

0:02:57.317,0:02:58.302
# 現在都不聽話了
But it’s so naughty now.

0:03:00.178,0:03:02.892
# 你看那小豬  它又去那裡  泡澡啦
Have a look at that piggy. It’s over there, taking a bath again.

0:03:04.426,0:03:07.963
# 生活過很好滋潤啊  我們又給它取了個名字
What a wonderful life! We’ve also given it a name.

0:03:08.605,0:03:10.262
# 把它叫作那個  紅燒肉
It’s called, well, Stewed Pork.

0:03:11.247,0:03:14.084
# 那小豬  黑豬  那個黑豬叫紅燒肉
The piggy, black pig, that black pig is called Stewed Pork.

0:03:14.630,0:03:16.657
# 下次我一叫紅燒肉它就馬上過來啦
It would come immediately whenever I call “Stewed Pork” next time.

0:03:17.287,0:03:21.085
# 我要餵的時候  餵的時候那個要  先喊一下它的名字
When I feed it, when I feed it, I gotta, you know, first call its name.

0:03:21.329,0:03:24.317
# 餵多幾次它自然  我一來一叫它  它就馬上過來啦
Feed it a few more times, then, whenever I come, I call it, it would come immediately.

0:03:26.736,0:03:27.474
# 紅燒肉
Stewed Pork!

0:03:28.555,0:03:30.157
# 紅燒肉 過來
Stewed Pork! Come here!

0:03:31.458,0:03:34.007
# 沒反應  還不知道 剛起的名字
No response. It still doesn’t know. It’s a new name.

0:03:34.704,0:03:35.702
# 慢慢的就習慣啦
It will get used to it.

0:03:37.140,0:03:39.922
# 這兩個白的也給它們起了名字
We have also given names to these two white ones.

0:03:40.303,0:03:41.932
# 叫  叫豬大腸
They, they’re called Chitterlings.

0:03:42.684,0:03:46.043
# 一個豬大腸A 一個豬  豬大腸B
One is Chitterlings A. The other is Chit, Chitterlings B.

0:03:47.096,0:03:48.629
# 反正兩個嘛  兩兄弟
Afterall, they’re, well, brothers.

0:03:49.299,0:03:51.381
# 不要哦  應該是兩夫妻
Ah no! They should be a couple.

0:03:52.627,0:03:54.311
# 一個A 一個B好區分
One is A, one is B. Then there’s a difference.

0:03:55.996,0:03:58.147
# 我去上山上那裡抓點魚
I’m going onto the hill and catch some fish.

0:03:58.542,0:04:01.461
# 這裡我去年放的魚  今年不知道有沒有
These are the fish that I put last year. But I’m not sure if they’re still here this hear.

0:04:01.884,0:04:03.637
# 前兩天我看到有魚在那裡的
I came here a couple of days ago and saw that the fish were still there.

0:04:04.128,0:04:05.730
# 在那動  不知道多大的魚
They were moving. But I don’t know how big that are.

0:04:09.828,0:04:11.677
# 哇  全部長草啦  這裡
Wa! Here, the weeds are growing everywhere.

0:04:13.087,0:04:14.277
# 全部都是草
The weeds are everywhere.

0:04:20.659,0:04:23.359
# 你看  這裡還有個雞窩哦  被我清的差不多啦
Look! Here’s a roost. I’ve almost cleaned up this place.

0:04:23.781,0:04:26.865
# 到時候再蓋個棚子  我買隻雞放在這裡面
I just need to build a shed here later. Then I can buy a chicken here,

0:04:28.564,0:04:30.523
# 讓它自由生長
and let it grow freely.

0:04:34.147,0:04:36.078
# 你看  剛才我看到那魚在動哦
Look! It just saw that fish moving.

0:04:36.816,0:04:37.691
# 不知道甚麼魚
But who knows what kind of fish it is.

0:04:39.108,0:04:41.629
# 把這個掀開一下  然後再直接把水舀乾
Let me take this one away, and then scoop up all the water right away.

0:04:42.165,0:04:44.261
# 放在這個溝  從這排出去  那個水
I pour it into the pit here, and let it flow away this way. I mean the water.

0:04:47.228,0:04:48.322
# 把這個放出去
Let me put it aside.

0:04:58.426,0:04:59.150
# 靠在這裡
Lean it here.

0:05:02.509,0:05:03.576
# 把這個水搞乾
I’m gonna drain all the water here.

0:05:06.326,0:05:07.338
# 肯定有大魚  這裡
Here, must be big fish.

0:05:09.001,0:05:10.397
# 剛剛看到它動了一下
I just saw it move a bit.

0:05:17.733,0:05:19.047
# 兩下就沒水啦
I can drain it in a second.

0:05:33.001,0:05:35.097
# 這個不知道會不會有魚  放在這裡
I’m not sure if here are any fish. Place it here.

0:05:37.303,0:05:38.164
# 我把它
I wanna,

0:05:39.382,0:05:41.094
# 套一下  不然那魚都跑掉了
trap them. Otherwise the fish might run away.

0:05:41.722,0:05:43.173
# 這個兩下就搞乾啦
It would be drained in a second.

0:05:58.616,0:06:00.204
# 哇 這個怎麼那麼深
Wa! Why is this one so deep?

0:06:04.554,0:06:06.000
# 這邊這個  這邊這個
The one here, the one here,

0:06:07.484,0:06:08.921
# 這邊這個快乾啦  真的
the one here will soon be drained. Really

0:06:09.536,0:06:10.411
# 誒  這邊這個
Eh? The one here,

0:06:11.383,0:06:11.942
# 那麼淺啊
why is it so shallow?

0:06:12.666,0:06:15.723
# 三個井都是連通的 我撈一下看撈不撈到魚先啊
These three wells are connecting each other. Let me see if I can catch any fish.

0:06:30.886,0:06:32.474
# 這個有大魚這裡
Here’s a big fish, here!

0:06:34.128,0:06:35.634
# 失算了  那麼深
I didn’t expect it. It’s so deep.

0:06:36.619,0:06:37.892
# 明天我帶抽水機過來
I’ll come again tomorrow with my water pump.

0:06:38.863,0:06:39.971
# 一下就把它抽乾
It would be drained in a second.

0:06:41.203,0:06:41.927
# 那麼深
It’s so deep.

0:06:42.610,0:06:45.241
# 而且全都是那個樹枝擋著了這裡
What’s even worse is that the branches are all blocking here.

0:06:46.226,0:06:47.114
# 現在也到底了
I can reach the bottom now.

0:06:52.030,0:06:53.865
# 誒  魚嘞
Eh? Where are the fish?

0:06:58.712,0:07:01.700
# 活要見人  死要見屍啊
C’mon! Fish! Dead or alive!

0:07:02.218,0:07:03.820
# 這裡差不多從這裡那麼深
It’s almost that deep here.

0:07:19.784,0:07:20.316
# 誒呦
Eyo!

0:07:21.177,0:07:21.750
# 有一條
Here’s a fish.

0:07:24.642,0:07:25.709
# 抓到一條那個鯰魚
I've caught a catfish.

0:07:29.293,0:07:31.554
# 抓到一條 還有的
So one. There should be more.

0:07:32.004,0:07:33.483
# 我記得放了兩條下去
I remember putting two there.

0:07:39.432,0:07:40.019
# 沒啦
No more.

0:07:40.523,0:07:41.562
# 就好像就一條
It seems to be just one.

0:07:42.101,0:07:43.264
# 放了兩條下去
But I’ve put two.

0:07:44.304,0:07:45.426
# 就剩這一條了
Now only one remains.

0:07:47.754,0:07:48.903
# 可能被它吃掉了
Perhaps it was eaten by the other one.

0:07:55.894,0:07:56.796
# 你看 蛇頭魚
Look! Snakehead fish

0:07:57.150,0:07:58.587
# 有啦 又撈一條蛇頭魚
Yea! One more, a snakehead fish

0:07:58.587,0:08:00.313
# 你看  這裡  撈到一條蛇頭魚
Look! Here, I’ve caught a snakehead fish.

0:08:02.732,0:08:03.607
# 放到桶裡面去
Put it into the bucket.

0:08:06.664,0:08:09.282
# 搞了兩條  這兩條就夠大啦
So we’ve caught two fish. These two fish are really big, aren’t they?

0:08:10.459,0:08:12.816
# 明天要把水抽  抽乾  看下有沒有
I’m gonna drain, drain the ponds tomorrow, and see if there are any more fish.

0:08:13.389,0:08:16.157
# 肯定有的  我放了那麼多條下去  就只剩下兩條啦
Certainly there are more. I’ve put so many fish there but now only two remain.
