### ISSUE TITLE
[老饭骨] 脆皮炸生蚝 -  https://youtu.be/oKqSZtRm0NM

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1589]
**视频链接**：
https://youtu.be/oKqSZtRm0NM
<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•脆皮炸生蚝】脆皮糊黄金量化比例，酥脆可口，传承十几年的老手艺，绝对错不了！ |老饭骨

简介
小友们好，今天小魏师傅带给大家一道脆皮炸生蚝！
这个脆皮糊的做法传承了十多年，量化比例过后小友们按照这个方法做，一定不会错！
这次咱们用的是生蚝做示范，小友们可以试试更多的食材，也非常不错！
这个配方小友们记下来，可以一直传承下去，用这个比例做出来的炸物，嘎嘣脆！
字幕
1
00:00:00,000 --> 00:00:02,520
今天咱主要是讲脆皮糊

2
00:00:02,520 --> 00:00:05,440
你听 多脆啊

3
00:00:05,440 --> 00:00:07,600
你按照比例做 就出不了大篓子

4
00:00:07,600 --> 00:00:11,880

5
00:00:11,880 --> 00:00:14,040
我这个都给它做标准做量化了

6
00:00:14,040 --> 00:00:15,480
低筋面粉250克

7
00:00:15,480 --> 00:00:16,760
泡打粉15克

8
00:00:16,760 --> 00:00:18,040
油50克

9
00:00:18,040 --> 00:00:20,360
水是380克 温水

10
00:00:20,360 --> 00:00:23,080
主要还是教大家怎么调脆皮糊

11
00:00:23,080 --> 00:00:25,360
生蚝搁葱姜搁黄酒稍微腌上

12
00:00:25,360 --> 00:00:27,720
它本身就有点咸鲜味

13
00:00:27,720 --> 00:00:29,440
这就不用加盐了

14
00:00:29,440 --> 00:00:32,240
来点香油去腥

15
00:00:32,240 --> 00:00:34,800
胡椒粉撒点 给它腌上

16
00:00:35,560 --> 00:00:35,760

17
00:00:35,760 --> 00:00:36,560
够肥实

18
00:00:36,560 --> 00:00:38,520
咱把脆皮糊给它和了

19
00:00:38,520 --> 00:00:40,960
和脆皮糊的时候先搁泡打粉 15克

20
00:00:40,960 --> 00:00:43,440
温水 发酵比较快

21
00:00:43,440 --> 00:00:47,240
用筷子把泡打粉给它和开了

22
00:00:47,240 --> 00:00:49,600

23
00:00:50,080 --> 00:00:52,160
加上面粉

24
00:00:52,160 --> 00:00:54,400
加水

25
00:00:54,400 --> 00:00:58,080
我给你热上油 谢谢师父

26
00:00:58,080 --> 00:00:59,960
这是急脆浆的一种

27
00:00:59,960 --> 00:01:03,720
传统的老脆浆就是 酵母点点儿碱

28
00:01:03,720 --> 00:01:05,280
油 50克

29
00:01:05,280 --> 00:01:07,960
半斤面粉 15克泡打粉

30
00:01:07,960 --> 00:01:10,920
50克油 380克的（温）水

31
00:01:10,920 --> 00:01:12,880
这都量化了 标准化了

32
00:01:12,880 --> 00:01:15,680
为了增加它的香味儿 香菜末儿

33
00:01:15,680 --> 00:01:17,920
这就是跟传统的不一样了

34
00:01:17,920 --> 00:01:20,080
稍微加点盐

35
00:01:20,080 --> 00:01:21,720
这个糊要给它发酵一下

36
00:01:21,720 --> 00:01:24,280
发酵个五六分钟十来分钟

37
00:01:24,280 --> 00:01:26,160
这效果就会好

38
00:01:26,160 --> 00:01:29,120
这个糊和好了 一定要标准

39
00:01:29,120 --> 00:01:32,120
你按照比例做 就出不了大娄子

40
00:01:32,120 --> 00:01:33,640
少搁点黄酒

41
00:01:33,640 --> 00:01:36,560
水开了 把生蚝焯一下水

42
00:01:36,560 --> 00:01:38,560
稍微一焯水就关火

43
00:01:38,560 --> 00:01:41,360
这生蚝把水给它吸进去

44
00:01:41,360 --> 00:01:45,480
就是原材料的水分要吸干 不管炸什么

45
00:01:46,520 --> 00:01:48,680
脆浆也饧的差不多了有五分钟了

46
00:01:48,680 --> 00:01:51,160
饧完了以后这脆浆就别再搅了

47
00:01:51,160 --> 00:01:53,200
因为一搅又上劲了

48
00:01:53,200 --> 00:01:55,360
这会咱沾点淀粉

49
00:01:55,360 --> 00:01:57,800
锁住它的水分 不容易脱糊

50
00:01:57,800 --> 00:01:59,880
专业叫不容易脱裤子

51
00:01:59,880 --> 00:02:02,400
跟炸鲜奶是一样的

52
00:02:02,400 --> 00:02:05,200
五成油温 油温不能太高了

53
00:02:05,200 --> 00:02:09,280
定一下型就行 待会还得复炸

54
00:02:09,680 --> 00:02:11,600
倍儿漂亮 金黄色

55
00:02:13,000 --> 00:02:17,000
这时候脆皮糊就稍微加点水

56
00:02:17,000 --> 00:02:18,880
稀释点 薄薄的一层糊

57
00:02:18,880 --> 00:02:21,720
要不然太厚了不好看了

58
00:02:21,720 --> 00:02:24,880
紫苏叶必须得炸 炸完了之后垫底

59
00:02:24,880 --> 00:02:24,920

60
00:02:26,000 --> 00:02:28,080
一定要定一下型再翻

61
00:02:28,080 --> 00:02:30,960

62
00:02:31,960 --> 00:02:33,040
倍儿脆

63
00:02:33,040 --> 00:02:34,040
牡蛎回一下锅

64
00:02:34,040 --> 00:02:36,240
油温最少是八成热

65
00:02:36,240 --> 00:02:40,440
叫它把水分给它吐出去

66
00:02:40,440 --> 00:02:44,000
迅速的捞出来 出锅喽

67
00:02:44,000 --> 00:02:46,520
里头油全打出去了 嘎嘣脆

68
00:02:46,520 --> 00:02:47,800

69
00:02:47,800 --> 00:02:50,440
你听这声音 咔吧咔吧的 齐活

70
00:02:50,440 --> 00:02:52,320
师父您看 您听

71
00:02:52,320 --> 00:02:53,800

72
00:02:53,800 --> 00:02:55,480
多脆啊

73
00:02:55,480 --> 00:02:57,120

74
00:02:57,120 --> 00:02:59,840
听声音 嘎嘣脆

75
00:02:59,840 --> 00:03:03,120
下手 大爷 您先尝

76
00:03:03,120 --> 00:03:06,600

77
00:03:06,600 --> 00:03:08,520
瞧这酥脆的声音

78
00:03:08,520 --> 00:03:10,200
这糊调的好

79
00:03:10,200 --> 00:03:12,600
这是师父十多年前教的我

80
00:03:12,600 --> 00:03:15,320
真好吃 这应该说是

81
00:03:15,320 --> 00:03:20,640
糊好 原材料好 手艺好 传承好

82
00:03:20,640 --> 00:03:22,840
师父是什么 是味精

83
00:03:22,840 --> 00:03:26,400
因为过去有些原材料不是那么很好

84
00:03:26,400 --> 00:03:27,840
也不是很新鲜

85
00:03:27,840 --> 00:03:30,360
师父您尝尝这个菜行不行

86
00:03:30,360 --> 00:03:32,400
一尝不够鲜

87
00:03:32,400 --> 00:03:35,840
师父到味精罐儿里头捏点味精

88
00:03:35,840 --> 00:03:38,520
往这菜里边一扔 行了

89
00:03:38,520 --> 00:03:41,080
所以师父是什么 师父是味精

90
00:03:41,080 --> 00:03:45,240
这个例子可能有点不太恰当

91
00:03:45,240 --> 00:03:47,880
但是有一样 师父就是调味

92
00:03:47,880 --> 00:03:49,720
像你师父说的

93
00:03:49,720 --> 00:03:54,560
调味 调情 调水 调心

94
00:03:54,560 --> 00:03:55,880
这很重要

95
00:03:55,880 --> 00:03:57,560
所以今天刚强做这个

96
00:03:57,560 --> 00:04:02,360
非常地道的脆皮炸生蚝

97
00:04:03,480 --> 00:04:05,800
我再来一个啊 再来一个



```

**Comment by Yilyn** [comment]
认领

**Comment by Yilyn** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•脆皮炸生蚝】脆皮糊黄金量化比例，酥脆可口，传承十几年的老手艺，绝对错不了！ |老饭骨

【State Banquet Master Chef•Crispy Fried Oysters】A golden-ratio batter recipe with a long history that ensures the oysters super crispy and savory

简介
小友们好，今天小魏师傅带给大家一道脆皮炸生蚝！
这个脆皮糊的做法传承了十多年，量化比例过后小友们按照这个方法做，一定不会错！
这次咱们用的是生蚝做示范，小友们可以试试更多的食材，也非常不错！
这个配方小友们记下来，可以一直传承下去，用这个比例做出来的炸物，嘎嘣脆！

Hi everyone, today Chef Wei brings us a crispy fried oyster!

The batter recipe has been passed down for more than ten years. The quantified formula will make sure a great final product even for novices.  

This time we are using fresh oysters as a demonstration but you can actually try a variety of different ingredients, which is also great!

Once you guys remember the recipe, you can apply it to other ingredients to create a crispy texture for any fried foods. 




字幕
1
00:00:00,000 --> 00:00:02,520
今天咱主要是讲脆皮糊
Today let’s talk about the batter

2
00:00:02,520 --> 00:00:05,440
你听 多脆啊
Listen, it’s so crispy

3
00:00:05,440 --> 00:00:07,600
你按照比例做 就出不了大篓子
As long as you follow the formula, you can never make it wrong 

4
00:00:07,600 --> 00:00:11,880

5
00:00:11,880 --> 00:00:14,040
我这个都给它做标准做量化了
I’ve already quantified the batter formula 

6
00:00:14,040 --> 00:00:15,480
低筋面粉250克
Low-gluten flour for 250g 

7
00:00:15,480 --> 00:00:16,760
泡打粉15克
Baking powder for 15g

8
00:00:16,760 --> 00:00:18,040
油50克
Oil for 50g

9
00:00:18,040 --> 00:00:20,360
水是380克 温水
Warm water for 380g

10
00:00:20,360 --> 00:00:23,080
主要还是教大家怎么调脆皮糊
Those are the ingredients of the batter 

11
00:00:23,080 --> 00:00:25,360
生蚝搁葱姜搁黄酒稍微腌上
Marinate the oysters with scallion, ginger and huangjiu rice wine

12
00:00:25,360 --> 00:00:27,720
它本身就有点咸鲜味
We don’t need to salt the oysters

13
00:00:27,720 --> 00:00:29,440
这就不用加盐了
Because it comes with a salty taste 

14
00:00:29,440 --> 00:00:32,240
来点香油去腥
Then let’s add some sesame oil to get rid of the gamey flavor 

15
00:00:32,240 --> 00:00:34,800
胡椒粉撒点 给它腌上
A little pepper powder 

16
00:00:35,560 --> 00:00:35,760

17
00:00:35,760 --> 00:00:36,560
够肥实
That’s thick enough

18
00:00:36,560 --> 00:00:38,520
咱把脆皮糊给它和了
Let’s mix the batter nice and well 

19
00:00:38,520 --> 00:00:40,960
和脆皮糊的时候先搁泡打粉 15克
Also, add 15g baking powder before mixing

20
00:00:40,960 --> 00:00:43,440
温水 发酵比较快
Use warm water for the batter to ferment quicker

21
00:00:43,440 --> 00:00:47,240
用筷子把泡打粉给它和开了
Use chopsticks to mix the baking powder as well

22
00:00:47,240 --> 00:00:49,600

23
00:00:50,080 --> 00:00:52,160
加上面粉
Then add flour

24
00:00:52,160 --> 00:00:54,400
加水
And water

25
00:00:54,400 --> 00:00:58,080
我给你热上油 谢谢师父
I’ll prepare some hot oil for you. Thanks, master. 

26
00:00:58,080 --> 00:00:59,960
这是急脆浆的一种
This is actually one of the quick crispy batters.  

27
00:00:59,960 --> 00:01:03,720
传统的老脆浆就是 酵母点点儿碱
The more traditional batter has yeast and soda

28
00:01:03,720 --> 00:01:05,280
油 50克
Let’s do a quick recap. 50g oil

29
00:01:05,280 --> 00:01:07,960
半斤面粉 15克泡打粉
250g flour and 15g backing powder

30
00:01:07,960 --> 00:01:10,920
50克油 380克的（温）水
50g oil and 380g warm water

31
00:01:10,920 --> 00:01:12,880
这都量化了 标准化了
Those are all quantified ingredients 

32
00:01:12,880 --> 00:01:15,680
为了增加它的香味儿 香菜末儿
Let’s add some chopped cilantro for an extra flavoring 

33
00:01:15,680 --> 00:01:17,920
这就是跟传统的不一样了
That’s something different from traditional ways

34
00:01:17,920 --> 00:01:20,080
稍微加点盐
A little salt

35
00:01:20,080 --> 00:01:21,720
这个糊要给它发酵一下
The batter needs to ferment for a while

36
00:01:21,720 --> 00:01:24,280
发酵个五六分钟十来分钟
Like 5-10 mins 

37
00:01:24,280 --> 00:01:26,160
这效果就会好
The fermentation will make it more crispy 

38
00:01:26,160 --> 00:01:29,120
这个糊和好了 一定要标准
Finally, we got the batter 

39
00:01:29,120 --> 00:01:32,120
你按照比例做 就出不了大娄子
As long as you follow the formula there’s no way to make it wrong 

40
00:01:32,120 --> 00:01:33,640
少搁点黄酒
Add a little bit huangjiu rice wine 

41
00:01:33,640 --> 00:01:36,560
水开了 把生蚝焯一下水
The water boiled. Let’s parboil those oysters

42
00:01:36,560 --> 00:01:38,560
稍微一焯水就关火
Just parboiling oysters a little bit 

43
00:01:38,560 --> 00:01:41,360
这生蚝把水给它吸进去
Make sure the oysters don’t soak up too much water

44
00:01:41,360 --> 00:01:45,480
就是原材料的水分要吸干 不管炸什么
Make sure we dry the water of any ingredients before frying in the oil

45
00:01:46,520 --> 00:01:48,680
脆浆也饧的差不多了有五分钟了
The batter has rested for about 5 mins 

46
00:01:48,680 --> 00:01:51,160
饧完了以后这脆浆就别再搅了
There’s no need to stir the mixture again

47
00:01:51,160 --> 00:01:53,200
因为一搅又上劲了
The stirring will add more gluten then create a tough texture 

48
00:01:53,200 --> 00:01:55,360
这会咱沾点淀粉
First, put oysters in the starch 

49
00:01:55,360 --> 00:01:57,800
锁住它的水分 不容易脱糊
To lock the water and get it coated tightly  

50
00:01:57,800 --> 00:01:59,880
专业叫不容易脱裤子
This is very important

51
00:01:59,880 --> 00:02:02,400
跟炸鲜奶是一样的
The same as fried milk 

52
00:02:02,400 --> 00:02:05,200
五成油温 油温不能太高了
The oil temperature should be around 150 celsius. Don’t set it too high

53
00:02:05,200 --> 00:02:09,280
定一下型就行 待会还得复炸
We need to settle the coat then re-fry it later 

54
00:02:09,680 --> 00:02:11,600
倍儿漂亮 金黄色
You see the beatiful golden color?

55
00:02:13,000 --> 00:02:17,000
这时候脆皮糊就稍微加点水
Now we need to add some water into the batter

56
00:02:17,000 --> 00:02:18,880
稀释点 薄薄的一层糊
To thin is slighly

57
00:02:18,880 --> 00:02:21,720
要不然太厚了不好看了
Or else the coat will be too thick and heavy 

58
00:02:21,720 --> 00:02:24,880
紫苏叶必须得炸 炸完了之后垫底
Perilla leaves also need to be fried then put on the bottom of the plate 

59
00:02:24,880 --> 00:02:24,920

60
00:02:26,000 --> 00:02:28,080
一定要定一下型再翻
Make sure the upside coat is settled then flip over for the other side  

61
00:02:28,080 --> 00:02:30,960

62
00:02:31,960 --> 00:02:33,040
倍儿脆
So crispy

63
00:02:33,040 --> 00:02:34,040
牡蛎回一下锅
Let re-fty the oysters one more time in a high temperature

64
00:02:34,040 --> 00:02:36,240
油温最少是八成热
The oil temperature should be at least 250 celsius now

65
00:02:36,240 --> 00:02:40,440
叫它把水分给它吐出去
To drain the water thoroughly 

66
00:02:40,440 --> 00:02:44,000
迅速的捞出来 出锅喽
Get them out of the oil quickly 

67
00:02:44,000 --> 00:02:46,520
里头油全打出去了 嘎嘣脆
Now they should be all nicely fried and super crispy 

68
00:02:46,520 --> 00:02:47,800

69
00:02:47,800 --> 00:02:50,440
你听这声音 咔吧咔吧的 齐活
You can tell the crispiness from the chewing sound 

70
00:02:50,440 --> 00:02:52,320
师父您看 您听
Master, did you see this? 

71
00:02:52,320 --> 00:02:53,800

72
00:02:53,800 --> 00:02:55,480
多脆啊
Wow that’s so crispy 

73
00:02:55,480 --> 00:02:57,120

74
00:02:57,120 --> 00:02:59,840
听声音 嘎嘣脆
Listen to the crsipy sound


75
00:02:59,840 --> 00:03:03,120
下手 大爷 您先尝
Da Ye, have a try! 

76
00:03:03,120 --> 00:03:06,600

77
00:03:06,600 --> 00:03:08,520
瞧这酥脆的声音
Such a pleasant sound 

78
00:03:08,520 --> 00:03:10,200
这糊调的好
The batter is mixed really well 

79
00:03:10,200 --> 00:03:12,600
这是师父十多年前教的我
This is what you taught me ten years before 

80
00:03:12,600 --> 00:03:15,320
真好吃 这应该说是
Yummy! This is the paradigm of 

81
00:03:15,320 --> 00:03:20,640
糊好 原材料好 手艺好 传承好
Great ingredients, excellent cooking skills and continuous heritage. 

82
00:03:20,640 --> 00:03:22,840
师父是什么 是味精
Masters is sort of like a seasoning 

83
00:03:22,840 --> 00:03:26,400
因为过去有些原材料不是那么很好
Students are like a variety of ingredients with different qualities 

84
00:03:26,400 --> 00:03:27,840
也不是很新鲜
They might not be all in the best place at the start  

85
00:03:27,840 --> 00:03:30,360
师父您尝尝这个菜行不行
When the Master’s teaching students, they can tell the room for improvement and lead students to the right path. 

86
00:03:30,360 --> 00:03:32,400
一尝不够鲜
It’s similar to how a seasoning will make a dish better even when ingredients are not the best. 

87
00:03:32,400 --> 00:03:35,840
师父到味精罐儿里头捏点味精
A Master can enlighten students on what went wrong and how to fix them 

88
00:03:35,840 --> 00:03:38,520
往这菜里边一扔 行了
Then students can be another Master in the future 

89
00:03:38,520 --> 00:03:41,080
所以师父是什么 师父是味精
Master is like a seasoning 

90
00:03:41,080 --> 00:03:45,240
这个例子可能有点不太恰当
This metaphor could be a little bit fuzzy but you know what I mean 

91
00:03:45,240 --> 00:03:47,880
但是有一样 师父就是调味
Seasoning That helps to balance everything when it comes to cooking

92
00:03:47,880 --> 00:03:49,720
像你师父说的
That’s what your Master said

93
00:03:49,720 --> 00:03:54,560
调味 调情 调水 调心
To keep all the cooking ingredients in a delicate balance 

94
00:03:54,560 --> 00:03:55,880
这很重要
That’s very important 

95
00:03:55,880 --> 00:03:57,560
所以今天刚强做这个
That’s why Chef Wei did this today 

96
00:03:57,560 --> 00:04:02,360
非常地道的脆皮炸生蚝
Very authentic crispty fried oysters

97
00:04:03,480 --> 00:04:05,800
我再来一个啊 再来一个
I’ll just take one more!

**Comment by Yilyn** [comment]
# 标题 （精简标题）
# 【国宴大师•脆皮炸生蚝】脆皮糊黄金量化比例，酥脆可口，传承十几年的老手艺，绝对错不了！ |老饭骨
# 【State Banquet Master Chef•Crispy Fried Oysters】A great old batter recipe for crispy and savory oysters 
# |--------------------------- title should not be longer than this line ----------------------------|
