### ISSUE TITLE
[华农兄弟] 华农兄弟兄弟看我们抓鱼辛苦特意送来几只牛蛙烤起来很香哦 - https://youtu.be/RQozgkY6WlU

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1597]
https://youtu.be/RQozgkY6WlU
<p>&#35270;&#39057;&#21457;&#24067;&#20110; October 24, 2020 at 11:30AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/RQozgkY6WlU

#华农兄弟：兄弟看我们抓鱼辛苦，特意送来几只牛蛙，烤起来很香哦
#Huanong Brothers: Our buddies gave us a couple of bullfrogs for our effort in catching fish. Nice!
#Huanong Brothers: Seeing that we had a hard time catching fish, our buddies gave us a couple of bullfrogs. We grill them. It smells so good!

0:00:00.000,0:00:01.332
# 你看  紅燒肉它們
Look! Red Braised Pork and its friends,

0:00:02.021,0:00:03.418
# 大腸 豬大腸
Chit, the Chitterlings,

0:00:03.928,0:00:05.602
# 在這拱這個樹枝哦
they're snouting these branches,

0:00:05.805,0:00:06.632
# 拱那個地
snouting the ground.

0:00:07.252,0:00:09.822
# 幫我翻地  到時候我就把象草種一排過去
They’re helping me turn the soil. I can then plant a whole row of elephant grass here later.

0:00:10.350,0:00:11.058
# 剛剛好
Perfect!

0:00:11.710,0:00:13.840
# 上次那個抽水機壞啦 就是因為這個壞啦
Last time the water pump was not working. It’s because this one was broken.

0:00:14.742,0:00:16.872
# 你看 現在我們把它買了一個新的回來
Look! We’ve now bought a new one back.

0:00:17.342,0:00:18.902
# 這個肯定可以抽得上來啦
With this one, we can surely drain the ponds.

0:00:19.828,0:00:22.464
# 那裡有魚  還沒  還不知道有多少啦
There are...Well, I have no ideas how many fish there are.

0:00:23.063,0:00:23.857
# 去搞一下
Let’s take care of it.

0:00:25.304,0:00:25.837
# 小羊
Goaty!

0:00:26.763,0:00:27.443
# 羊肉包
Lamb Bun!

0:00:28.825,0:00:29.407
# 羊肉包
Lamb Bun!

0:00:31.467,0:00:32.598
# 叫你  你就拉尿
Hey! I'm calling you. You just piss.

0:00:34.735,0:00:36.947
# 那個紅燒肉  我一過來它就過來啦
That is Red Braised Pork. It comes to me immediately upon my call.

0:00:37.856,0:00:38.406
# 紅燒肉
Red Braised Pork!

0:00:39.886,0:00:40.664
# 紅燒肉
Red Braised Pork!

0:00:42.001,0:00:42.648
# 它還
It can’t,

0:00:43.737,0:00:44.841
# 它還沒反應過來
it can’t respond immediately.

0:00:44.841,0:00:46.238
# 哇瑟  你又胖啦
Gosh! You're getting fat again!

0:00:47.082,0:00:48.398
# 是啊  適合做紅燒
Yea, right! Excellent for red braised pork.

0:00:53.146,0:00:54.136
# 你要進來嗎
You wanna get in?

0:00:54.459,0:00:55.628
# 你看 豬大腸
Look! Chitterlings,

0:00:57.140,0:00:58.782
# 這個A  這個B
this is A, and this is B.

0:00:58.941,0:01:00.762
# 這個公的是A  母的是B
This male is A, and the female is B.

0:01:09.048,0:01:10.461
# 走啦  幹活啦
Let’s go! I gotta start working now.

0:01:13.360,0:01:15.588
# 你看  上次我們的抽水機還放在這裡
Look! The water pump last time is still here.

0:01:16.628,0:01:18.563
# 把這個裝上  直接打火
Let me put this on, and start the engine right away.

0:01:19.098,0:01:20.544
# 這是山泉水來的哦
This is spring water, you know.

0:01:20.704,0:01:22.199
# 山泉水滲到這裡面來的
The spring water seeps into the ponds.

0:01:50.480,0:01:52.724
# 你看  這一條蛇頭魚哦  看到沒有
Look! Here’s a snakehead fish. See?

0:01:54.139,0:01:55.080
# 看到你啦
I can see you already.

0:01:59.226,0:01:59.808
# 抓到啦
Got it!

0:02:03.279,0:02:03.878
# 你看
Look!

0:02:04.961,0:02:08.444
# 一條 一條鯰魚  看到沒有  它躲在這裡
A, a catfish. See? It’s hiding here.

0:02:13.590,0:02:14.368
# 用力
Keep going!

0:02:18.148,0:02:18.812
# 它縮回去啦
It hides back.

0:02:29.687,0:02:31.329
# 這裡還沒有抽乾哦
Here is still not yet completely drained.

0:02:31.762,0:02:32.524
# 還有的哦
There’s still water.

0:02:44.746,0:02:45.426
# 抽不到哦
No more?

0:02:45.427,0:02:47.785
# 抽不到啦  我把這個拉起來
No more. Then I pull it out.

0:02:51.966,0:02:52.939
# 終於沒有
Finally, it’s finished.

0:02:53.882,0:02:55.507
# 白來  看這裡有沒有大貨
Wastes my time. Let me see if there are any big things.

0:02:56.116,0:02:57.000
# 這麼深
It’s so deep.

0:03:05.684,0:03:06.315
# 全是樹葉
Only leaves

0:03:11.443,0:03:13.019
# 你看  全部把它抽乾啦
Look! They’re all completely drained now.

0:03:13.652,0:03:15.424
# 就搞了3條  2條鯰魚
Just three fish, two catfish and,

0:03:15.910,0:03:17.780
# 2魚蛇頭魚喲  好像  是不是
two snakehead fish, it seems. Am I right?

0:03:18.343,0:03:19.219
# 4條 好像
Four fish, it seems

0:03:22.247,0:03:23.139
# 哦  這有3條
Oh! Here are three.

0:03:23.494,0:03:24.272
# 2條蛇頭魚
Two snakehead fish,

0:03:24.693,0:03:25.487
# 一條鯰魚
and a catfish.

0:03:25.973,0:03:27.940
# 上次搞了一條鯰魚  一條蛇頭魚
Last time we caught a catfish and a snakehead fish.

0:03:28.703,0:03:29.302
# 6條
So six fish

0:03:30.162,0:03:31.494
# 這樣算下去虧本啊
I think it can be considered a loss.

0:03:32.306,0:03:33.247
# 我放了那麼多魚
I have put so many fish here.

0:03:34.368,0:03:35.162
# 都不見啦
But they’re all gone.

0:03:38.565,0:03:39.913
# 好啦  不管它啦
Alright! Forget it.

0:03:40.578,0:03:42.203
# 回家啦  清洗一下
Let’s go back, and wash everything.

0:03:42.379,0:03:43.646
# 再也不放魚到這裡啦
Never will I put any fish here anymore.

0:03:45.549,0:03:47.810
# 我拿這個行啦  我拿這個刀
I only need to take this one. I’ll take this knife as well.

0:04:08.545,0:04:10.007
# 你看  這兩條蛇頭魚
Look! These two snakehead fish

0:04:10.900,0:04:11.564
# 看到沒有
See?

0:04:12.490,0:04:13.447
# 還有一條鯰魚
Here’s also a catfish.

0:04:14.822,0:04:15.861
# 這魚很好吃的哦
This fish is really tasty.

0:04:16.004,0:04:17.157
# 誒  它們是不是
Ey? Were they,

0:04:17.626,0:04:19.496
# 那天被我攪拌了一下
stirred by me last time.?

0:04:20.259,0:04:21.689
# 身上都受了一點小傷
They all have some small wounds on their bodies.

0:04:22.623,0:04:23.352
# 別出來
Don’t try to run away.

0:04:26.657,0:04:28.299
# 先放在這裡養著先
Let me keep them here first.

0:04:29.599,0:04:32.560
# 前兩天兄弟說  我們沒抓到魚
A couple of days ago, my buddy said that I couldn’t catch any fish.

0:04:33.698,0:04:35.144
# 他怎麼知道我們沒抓到魚  你看
How did he know that I couldn’t catch any fish? Look!

0:04:35.222,0:04:36.065
# 特意  他提了
Because of that, he brought me,

0:04:36.551,0:04:39.301
# 提了兩  兩個  這個牛蛙過來
brought me two, two, well, bullfrogs here.

0:04:40.699,0:04:42.243
# 5個哦  不是2個
Oh, five, not two.

0:04:42.386,0:04:43.441
# 拿2隻來烤一下
Let’s grill two of them.

0:04:44.350,0:04:46.562
# 最近很少吃肉  吃點這個牛蛙
We seldom have meat recently. So let’s have some bullfrogs.

0:04:47.015,0:04:48.787
# 你看  這個好肥呀
Look! This one is really fat.

0:04:49.110,0:04:50.605
# 肚子都好白  鼓鼓的
Its belly is so white, and so round.

0:04:52.182,0:04:53.367
# 現在把它處理一下
Let me take care of them first.

0:04:54.309,0:04:56.113
# 這牛蛙要把它  把它摔死哦
To kill the bullfrogs, I need to strike them hard.

0:05:15.592,0:05:17.022
# 你看  搞點這個生薑
Look! Put some, some ginger here.

0:05:19.202,0:05:19.752
# 搞點
Put some,

0:05:20.261,0:05:22.408
# 生薑給你們去去你們的腥味
some ginger to get rid of your bloody smell.

0:05:22.983,0:05:24.625
# 再搞點全南大曲
And then put some “Quannan Taqu (local rice wine)

0:05:27.098,0:05:27.941
# 全南大曲
“Qunnan Taqu”

0:05:29.502,0:05:30.899
# 哎 給你們喝點酒
Ay! I give your some rice wine.

0:05:31.711,0:05:32.798
# 味道杠杠的
Magnifico!

0:05:35.305,0:05:36.132
# 再加點鹽
Then put some salt.

0:05:39.722,0:05:41.445
# 再加點醬油
And also some soy sauce

0:05:49.478,0:05:50.451
# 再抽點油
Then some oil

0:05:51.084,0:05:52.334
# 油要搞多一點
I need a bit more oil.

0:05:53.114,0:05:54.234
# 你看  好啦
Look! It’s alright now.

0:05:55.453,0:05:56.443
# 攪拌一下
Mix them well

0:05:57.799,0:06:00.369
# 你看  剛剛給它喝點酒  馬上就醉啦
Look! I’ve just given them some rice wine, and they’re drunk immediately.

0:06:03.021,0:06:04.728
# 把這個牛蛙  拿上來
So I put these bullfrogs, onto this net.

0:06:06.468,0:06:07.865
# 來  上烤架啦
C’mon! Onto the stove now!

0:06:14.485,0:06:16.664
# 這個  烤這個牛蛙沒那麼快的哦
Well, grilling these bullfrogs needs a bit more time.

0:06:18.001,0:06:19.349
# 我去看一上兄弟家的兔子
Let me have a look at the rabbits at my buddy’s place.

0:06:19.509,0:06:20.596
# 他家兔子養了好多
He has a lot of rabbits.

0:06:25.694,0:06:27.368
# 你看  這就是兔子廠啦
Look! This is his rabbit site.

0:06:31.453,0:06:32.622
# 你看  這個兔子
Look! These rabbits,

0:06:33.140,0:06:34.244
# 好漂亮哦
are so pretty.

0:06:35.479,0:06:35.979
# 你看
Look!

0:06:36.547,0:06:38.140
# 一個都差不多有5斤哦
It’s almost two and a half kilograms each.

0:06:39.896,0:06:40.560
# 太大啦
Too big

0:06:41.567,0:06:43.355
# 可以吃啦  這個兔子那麼大
These rabbits are so big. They can be eaten now.

0:06:44.161,0:06:46.422
# 這種  這種灰色的漂亮  這種灰色的
This, this kind of grey ones are really pretty, these grey ones.

0:06:52.495,0:06:55.033
# 公兔子哦  好大啊  它腳趾
This is a male rabit. It’s so big, its toes.

0:06:56.773,0:06:58.480
# 差不多于六斤啊  這個兔子
It’s almost three kilograms, this rabbit.

0:06:59.291,0:07:00.150
# 把它抱回去
Let me put it back.

0:07:01.027,0:07:02.685
# 哎喲  你太胖啦
Aya! You’re just too fat.

0:07:07.830,0:07:10.449
# 你看  這個  哇  這個好大個
Look! This is.. Wa! This is huge!

0:07:10.561,0:07:12.170
# 灰色的 嘿 過來  過來 過來
The grey one, hey! C’mere, c’mere, c’mere!

0:07:14.206,0:07:15.929
# 啊  過來  不怕
Ah! C’mere! Fear not!

0:07:16.989,0:07:17.898
# 看一下你胖不胖
Let me see if you’re fat.

0:07:18.859,0:07:20.207
# 好胖啊  這個
It’s so fat, this one.

0:07:23.186,0:07:24.436
# 一身都是肉哦
It’s covered with meat.

0:07:24.662,0:07:26.206
# 軟綿綿的  好多肉哇
It’s soft like cotton, so meaty.

0:07:28.924,0:07:29.441
# 嘿
Hey!

0:07:30.381,0:07:31.289
# 這麼大的腳板
What a big foot!

0:07:31.433,0:07:32.602
# 公的  這個
It’s male, this one.

0:07:34.228,0:07:35.218
# 黑  放回去
Hey! Let me put it back

0:07:48.244,0:07:51.499
# 你看  雪白雪白的這個毛哦  眼睛都是紅的
Look! Its coat is snowy white, and the eyes are red.

0:07:52.669,0:07:53.642
# 最少七八斤
It’s at least three or even four kilograms.

0:07:54.959,0:07:55.867
# 肉兔子
They’re raised for their meat.

0:07:59.628,0:08:02.264
# 去不去我家  很近的走路都可以過去
You wanna go home with me? It’s nearby. You can simply walk there.

0:08:04.900,0:08:05.515
# 它不肯
It doesn’t want.

0:08:10.773,0:08:12.000
# 等他養肥一點我在[SIC]來
Let me come again when they get fatter.

0:08:12.379,0:08:13.923
# 現在全是母兔子  他說
Now they’re all female, he said.

0:08:14.229,0:08:15.642
# 他說現在要繁殖的時候
He said that it’s now the breeding time.

0:08:15.770,0:08:18.617
# 不能吃 是啊  等他有商品兔的時候我就再過來
So they can’t be eaten now. Yup. I’ll wait and come again when they’re for sale.

0:08:18.865,0:08:21.843
# 很近的 就相差不到50米
It’s nearby, not even fifty metres away.

0:08:27.982,0:08:30.178
# 搞點這個醬料給它身上
Put some, some sauce here onto their bodies.

0:08:30.533,0:08:32.370
# 看上去烤得有點乾啦
Cuz they look a little bit dry.

0:08:34.241,0:08:35.426
# 嗯  好啦
Um! Alright!

0:08:46.904,0:08:48.252
# 這個爐子太大啦
This stove is too big.

0:08:49.129,0:08:49.711
# 不好烤
It’s hard to grill well.

0:08:49.936,0:08:51.594
# 我怕那個烤得不是很熟
I don't wanna have it only partially cooked at the end.

0:08:52.536,0:08:53.868
# 換一個小爐子來
Let’s change to a smaller stove.

0:09:04.769,0:09:05.400
# 換來
Let’s move,

0:09:05.853,0:09:07.038
# 換了一個地方烤
move to another place.

0:09:07.296,0:09:09.394
# 那個地方太  太高啦
The one there is too, too high.

0:09:11.841,0:09:13.385
# 刷點這個醬料
Let me brush some sauce here,

0:09:14.816,0:09:15.822
# 讓它的味道
so that its taste would change,

0:09:16.683,0:09:17.526
# 更美好
from good to wonderful.

0:09:33.479,0:09:34.518
# 跑出一隻來
One has escaped.

0:09:48.358,0:09:49.869
# 啊  現在可以
Ah! It’s alright now.

0:09:50.045,0:09:52.452
# 烤得差不多咯  可以吃咯  看到沒有
I think it’s done now. We can start. See?

0:09:53.805,0:09:54.746
# 很靚的哦
It's beautiful, you know.

0:09:55.883,0:09:56.742
# 大長腿
Big long legs

0:09:59.771,0:10:01.005
# 好啦  好啦  開吃
Alright, alright! Let’s start.

0:10:03.202,0:10:04.306
# 給它們鬆綁
Let me untie them.

0:10:05.623,0:10:07.004
# 用架子壓著它們
I pressed them here.

0:10:09.070,0:10:11.086
# 我是為了防止它們逃跑
Cuz I wanted to prevent them from escaping.

0:10:11.686,0:10:13.002
# 所以就壓著它們
So I pressed them here.

0:10:20.922,0:10:21.765
# 開蓋啦
Let me open it!

0:10:22.039,0:10:23.909
# 哎呀  哎呀  別啦著這個
Aya, aya! Don’t hold onto it!

0:10:26.703,0:10:28.035
# 手都斷啦  哦
The arm is broken, oh.

0:10:29.547,0:10:30.749
# 嗯  好好吃啊
Um! It tastes really good!

0:10:32.538,0:10:34.571
# 它們的樣子好 很漂亮吧
They look so, really pretty, aren’t they?

0:10:35.856,0:10:37.009
# 哎  沒辦法
Ay! Anyway!

0:10:38.391,0:10:39.690
# 先把它手拿上來
Let me take off its arm first.

0:10:41.756,0:10:42.323
# 嗯
Um!

0:10:42.751,0:10:43.724
# 好好吃哦
It's really tasty!

0:10:45.155,0:10:46.275
# 搞它大長腿來
Let me take its big long leg.

0:10:47.841,0:10:48.341
# 你看
Look!

0:10:49.284,0:10:50.029
# 大腿啊
It’s a leg!

0:10:51.001,0:10:51.567
# 嗯
Um!

0:10:53.020,0:10:53.684
# 好吃
Good!

0:10:58.146,0:10:59.396
# 如果再烤乾一點
It would taste even better,

0:11:00.127,0:11:01.524
# 那味道更好
if there’s a bit less moisture.

0:11:10.379,0:11:11.515
# 嗯  它們腳趾
Um! Their toes

0:11:21.181,0:11:22.790
# 你看  搞一個大腿來吃一下
Look! Take a leg and have a try!

0:11:26.445,0:11:27.000
# 等一下
Wait!

0:11:28.393,0:11:29.480
# 讓你先舔一下
You can lick it first.

0:11:29.738,0:11:31.917
# 舔一下就可以啦  那個腳趾  好好吃的
Just lick it! The toes, are really tasty!

0:11:33.321,0:11:33.985
# 大腿
The leg!

0:11:42.672,0:11:44.314
# 嗯 好香
Um! It smells really good!

0:11:44.918,0:11:45.631
# 小狗
Doggy!

0:11:46.850,0:11:48.166
# 你可真有福氣呀
You’re really privileged, you know.

0:11:49.776,0:11:50.326
# 這裡
Here!

0:11:54.559,0:11:55.304
# 好不好吃
Does it taste good!

0:11:57.000,0:11:57.778
# 要聽話啊
Be a good boy, got it?

0:11:58.802,0:12:00.900
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.

0:12:02.086,0:12:03.239
# 我要回家做飯啦
I gotta go home and cook now.

0:12:03.747,0:12:04.590
# 不做飯的話
Otherwise,

0:12:05.263,0:12:06.302
# 晚上沒飯吃哦
I would have nothing for dinner tonight.
