### ISSUE TITLE
[华农兄弟] 华农兄弟苦等一个多月拿藤果终于熟了边摘边吃 - https://youtu.be/iHOlnJb-ALc

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1607]
https://youtu.be/iHOlnJb-ALc
<p>&#35270;&#39057;&#21457;&#24067;&#20110; October 29, 2020 at 11:30AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/iHOlnJb-ALc 

#华农兄弟：苦等一个多月，拿藤果终于熟了，边摘边吃
#Huanong Brothers: After the month long wait, the wild fruits are finally ripe. Time to pick and eat.
#Huanong Brothers: After the month long wait, the chocolate vine fruits are finally ripe. We have a feast while picking them.

0:00:00.001,0:00:02.930
# 大家好 今天天氣比較好一點哦
Hi everyone! The weather today is a bit better.
A month ago

0:00:03.337,0:00:07.485
# 來這大山里面看一下有沒  有沒這個好吃的  在這裡面
We’re coming into this mountain and see if there, there are any good snacks, any good snacks here.

0:00:08.075,0:00:09.389
# 以前這裡很多好吃的哦
There used to be a lot in the past.

0:00:09.652,0:00:10.723
# 不知道熟了沒有
But I'm not sure if they’re ripe now.

0:00:12.143,0:00:13.214
# 應該快熟啦
I think they’ll be ripe very soon.

0:00:13.910,0:00:16.032
# 沒熟也可以來這裡看一下
We can just take a look here even if they’re not.

0:00:19.745,0:00:20.770
# 這個夠大吧
This is really big, isn’t it?

0:00:21.946,0:00:24.000
# 下還很多的哦  這裡也有
Down there are a lot more, and here as well.

0:00:24.701,0:00:25.802
# 這裡有小的
Here’s a small one.

0:00:26.186,0:00:29.298
# 再去那邊  那邊有三四個好大的
Let’s go to that side as well. There are three or four really big ones.

0:00:29.617,0:00:30.218
# 看到沒有
See?

0:00:31.300,0:00:33.117
# 等它熟的時候我就過來摘
I’ll come again and pick them when they’re ripe.

0:00:33.212,0:00:35.882
# 你看  這個  這個是獼猴桃哦
Look! This is, this is kiwifruit.

0:00:36.419,0:00:38.328
# 我們這野生的猴桃是這樣子的
That’s how our wild kiwifruits here look like.

0:00:38.499,0:00:40.712
# 那麼多毛  哦  全身都長了看
It’s so furry. Oh! It’s covered with fur.

0:00:43.671,0:00:45.137
# 這個  還沒 不是很熟
It’s, it’s not, it’s not really that ripe.

0:00:45.690,0:00:46.776
# 你看  好多毛的
Look! It’s so furry.

0:00:48.150,0:00:49.952
# 哇  你看 全是毛
Wa! Look! It’s covered with fur!

0:00:51.098,0:00:52.473
# 這個還不能吃那麼快
This one can't be eaten yet. Not so soon.

0:00:54.701,0:00:58.057
# 要秋天的時候  要到冬天的時候才可以吃的  這種
Not until autumn, until winter, can they be eaten, these kind of kiwifruits.

0:00:58.776,0:01:00.517
# 我們這邊叫大彌猴桃
Here we call them big kiwifruits.

0:01:00.901,0:01:03.967
# 長大了就可以長那麼大的哦  這麼大 你看  這麼大
The fully grown ones can be that big, you know. That big, look? That big

0:01:04.458,0:01:05.833
# 這個還小  不能吃
This is still small. It can’t be eaten.

0:01:06.294,0:01:07.639
# 這個留給那個鳥吃
I’ll leave it for the birds.

0:01:08.206,0:01:09.292
# 鳥也吃了好多
The birds have also eaten a lot.

0:01:09.798,0:01:11.402
# 本來好多的  現在都掉啦
There should be a lot. But many have dropped.

0:01:12.487,0:01:13.360
# 上面還有幾個
Up there are a few more,.

0:01:14.064,0:01:15.333
# 都還不是很熟
But they’re not really that ripe.

0:01:18.063,0:01:19.179
# 看一下那邊有沒有
Let me see if there are any on that side.

0:01:20.371,0:01:21.975
# 你看  這裡有一個小海灘
Look! This is a small beach.

0:01:22.618,0:01:24.938
# 全是上面的沙子沖下來的哦
The sand is all washed from the upstream.

0:01:26.145,0:01:27.505
# 這沙子很好的
The sand here is really nice.

0:01:28.331,0:01:29.935
# 可以用來做房子的  這沙子
It can be used to build houses, the sand here.

0:01:30.334,0:01:32.288
# 沒甚麼雜質  全是小沙子
There are hardly any impurities, only fine sand.

0:01:38.867,0:01:39.664
# 這裡都是
Here as well

0:01:40.352,0:01:42.596
# 鑽都鑽不進來的  哇  這個
I can’t even squeeze in. Wa! This is…

0:01:43.780,0:01:44.564
# 好多哇
Really a lot!

0:01:45.189,0:01:46.077
# 一樹都是
They’re all over the tree!

0:01:46.427,0:01:47.589
# 這個掉下來啦
This one has dropped.

0:01:49.268,0:01:51.076
# 你看  這有6個 
Look! Here are six.

0:01:51.226,0:01:53.119
# 好瘦哦  今年的拿藤果
They’re so skinny, the chocolate vine fruits this year,

0:01:53.119,0:01:56.825
# 今年的這個拿藤果  因為今年產量特高
the, the chocolate vine fruits this year. It’s because the yield is exceptionally high.

0:02:00.001,0:02:01.529
# 你看  這有竹節果哦
Look! Here are also wild mangosteens.

0:02:02.910,0:02:04.560
# 這個  肯定很酸的
This one, must be very sour.

0:02:05.370,0:02:06.000
# 哎呀
Aya!

0:02:07.419,0:02:08.505
# 你看  它冒汁
Look! The juice is bursting out.

0:02:10.801,0:02:11.844
# 這還沒熟
It’s not yet ripe.

0:02:12.332,0:02:13.463
# 捏都捏不動
I can’t even split it open.

0:02:16.453,0:02:17.661
# 算啦  給那個
Forget it. Let me leave it to the…

0:02:18.081,0:02:18.999
# 一樹都是
They’re all over the tree.

0:02:19.505,0:02:22.495
# 到時候  冬天的時候  我們就可以再過來這裡摘
Later, in winter, we can come again and pick them.

0:02:23.230,0:02:24.179
# 帶一個牛皮袋
Let's come with a bag.

0:02:25.264,0:02:26.914
# 這一棵要摘一牛皮袋
This tree can fill up a bag,

0:02:27.953,0:02:29.938
# 滿滿的 一樹都是
completely. The fruits are all over the tree.

0:02:30.162,0:02:32.634
# 你看  這裡又大又圓哦
Look! These are big and round.

0:02:33.277,0:02:35.353
# 這邊的 向陽光的地方稍微大一點
On this side, those facing the sunshine are a bit larger.

0:02:36.362,0:02:37.174
# 很多的
A lot!

0:02:37.441,0:02:38.938
# 旁邊還有一棵楊梅樹哦
Here’s also a bayberry tree next to it.

0:02:39.170,0:02:41.338
# 你看  吃了楊梅吃竹節果
Look! We can have wild mangosteens after having bayberries.

0:02:41.920,0:02:44.042
# 還可以喲  吃了竹節果又吃楊梅
Not bad! And come back to bayberries afterwards.

0:02:45.492,0:02:47.203
# 我們山上很多這樣的野果樹 (248)
There are a lot of these kinds of wild fruits on our hills.

0:02:47.572,0:02:50.379
# 野果還沒熟哇  我們路過兄弟家的玉米地
The wild fruits are not yet ripe. We pass by our buddy’s corn field.

0:02:50.742,0:02:52.894
# 他的玉米他不要的  他掰過一遍的
He has already harvested. The corns here are leftover.

0:02:53.309,0:02:55.020
# 剩下的都是營食不良的
Only the undernourished ones remain.

0:02:55.541,0:02:56.505
# 搞一點回去吃
Let me pick some back home.

0:02:58.123,0:02:59.590
# 那麼小的 概不得他不要
It’s so small. No wonder he doesn’t want them.

0:03:00.934,0:03:02.812
# 因為裡面的籽沒有多少  看到沒有
There’re not too many corns inside. See?

0:03:03.257,0:03:06.202
# 它的籽就只有一半的  還有一半都沒有的
These are only half-filled, or not even half-filled.

0:03:06.433,0:03:07.869
# 賣的話可能就不好賣
They can hardly be sold.

0:03:08.467,0:03:11.290
# 但它吃的是  吃的話就不影響口感哦
But when it comes to the taste, there’s no difference.

0:03:12.260,0:03:13.378
# 我搞一點回去吃
Let me pick some back home.

0:03:14.111,0:03:15.395
# 就搞了那麼幾個
So I’ve just picked a few here.

0:03:15.535,0:03:18.815
# 好多都沒肉的  一半肉都沒有的  概不得他不要
There’s hardly anything to eat. Most are not even half-filled. No wonder he doesn’t want them.

0:03:19.290,0:03:19.797
# 好啦  
Alright!

0:03:20.044,0:03:21.145
# 回去煮玉米吃
Let’s go back and cook the corns.

0:03:24.001,0:03:26.930
# 一個月後
A month later

0:03:49.216,0:03:52.176
# 你看  這裡有個好黃的  又大又黃
Look! Here's a completely ripe one. It’s big and yellow.

0:03:53.444,0:03:54.000
# 看見沒有
See?

0:03:58.364,0:04:01.583
# 啊  看見沒有  好靚哦這個  還有
Ah! See? This one is really beautiful. There are more.

0:04:02.119,0:04:03.342
# 看到這裡上面  還有
I see some up there. There are more.

0:04:06.682,0:04:09.200
# 這個  有點黃的  要把它摘掉
This one, it's getting ripe. I need to pick it now.

0:04:09.601,0:04:11.494
# 你看這樹上好多黃哦 
Look! Here are a lot of ripe ones in the tree.

0:04:26.819,0:04:30.099
# 你看  就摘了那麼一點點  打開來給大家看一下
Look! So we’ve picked just a tiny little bit. Let me open it and show you.

0:04:30.757,0:04:31.752
# 撒地上來
Just spill them onto the ground.

0:04:37.990,0:04:39.183
# 這兩個又大又黃的
These two are big and golden yellow.

0:04:54.384,0:04:55.150
# 我這個好吃
This one is really tasty.

0:04:56.315,0:04:58.483
# 這個味道很好的哦  很甜的
The taste is really good! It’s so sweet.

0:04:59.202,0:05:03.076
# 是那種又香又甜  又好吃的味道
It’s sort of, a combination of fragrance, sweetness, and good taste.

0:05:06.424,0:05:09.110
# 就像是 就是甜  好甜
It’s like, well, sweet, really sweet.

0:05:25.909,0:05:27.589
# 哎呀  吃不動
Aya! I can’t eat anymore.

0:05:27.989,0:05:29.669
# 多吃一點  這個爛掉啦
Let's eat more. This one is rotten.

0:05:31.546,0:05:34.810
# 你看這個  好香啊
Have a look at this one. It smells really good!

0:05:35.591,0:05:38.505
# 吃飽啦 撐不下去啦  等一下來
I’m really full. I can’t eat anymore now. Later.

0:05:39.773,0:05:41.209
# 到裡面  再慢慢吃
Put it here inside. I’ll eat it later.

0:05:42.416,0:05:43.715
# 你看這個小沙灘
Look! This small beach,

0:05:47.190,0:05:48.245
# 好多沙子啊這裡
here's a lot of sand.

0:05:48.961,0:05:52.195
# 你看這兩個  它在勾引我嗎
Have a look at these two. Are they flirting to me?

0:05:55.071,0:05:57.817
# 怎麼可以那黃  雙胞胎
How can they be so golden yellow! They’re twins.

0:05:58.418,0:06:00.723
# 看到沒有  靚吧
See? Beautiful, aren't they?

0:06:02.539,0:06:04.265
# 剝開  一人一個
Split them. Let’s have one each.

0:06:08.649,0:06:09.324
# 啊~
Ah~

0:06:19.228,0:06:22.371
# 嗯~好吃  不知道前面有沒有啦
Um~ Tasty! Let’s see if there are any more in the front.

0:06:23.775,0:06:26.171
# 你看這個  好大啊這個
Have a look at this one. This is really big!

0:06:27.980,0:06:30.391
# 掛住啦  不肯過來
It gets stuck. It doesn’t wanna come.

0:06:33.091,0:06:35.914
# 過來  過來
Come here! Come here!

0:06:36.801,0:06:37.301
# 你看
Look!

0:06:38.576,0:06:39.373
# 這個
This one,

0:06:40.290,0:06:40.995
# 這個
this one,

0:06:41.696,0:06:42.538
# 肯定很好吃
must be very tasty.

0:06:44.659,0:06:45.425
# 那麼大
It’s so big.

0:06:46.365,0:06:47.926
# 放在這裡  我看下裡面有沒有
Leave it here. Let me see if there any down there.

0:06:57.142,0:06:58.106
# 你看  這裡有
Look! Some more here

0:06:59.907,0:07:00.643
# 誒呦
Eyo!

0:07:02.383,0:07:04.124
# 兩個都被鳥吃啦  還有一個
These two were eaten by the birds. Only one left

0:07:05.910,0:07:08.382
# 你看這個鳥  我跟它有感情的哦
Look! The birds, we have really good relationship, you know.

0:07:08.386,0:07:10.919
# 我不吃這兩個  還有一個就給我吃
I’m not eating these two. And one is left for me.

0:07:11.776,0:07:12.451
# 這還有一個
Here’s one more.

0:07:23.430,0:07:24.181
# 你看是不是
Look! Am I right?

0:07:24.870,0:07:26.413
# 我留給它吃  它留給我吃
I leave them fruits, and they leave me fruits as well.

0:07:27.787,0:07:29.010
# 這兩個也是爛的
These two are also rotten.

0:07:29.897,0:07:30.831
# 你看這個就好的
Look! This one is nice.

0:07:45.616,0:07:48.000
# 這有一個  有點爛啦
Here’s one. It’s a bit rotten.

0:07:52.287,0:07:55.460
# 哇  又大又黃的哦
Ah! It’s big and ripe, you know.

0:08:05.671,0:08:06.666
# 太好吃啦
Simply delicious!

0:08:07.339,0:08:10.497
# 這裡差不多一百多斤  哎呀 應該沒有一百斤
Here is more than fifty kilograms. Aya! No, I think not yet fifty.

0:08:10.790,0:08:13.186
# 可能差不多  接近  一牛皮袋
But it should be close, almost. You know, a whole bag.

0:08:16.308,0:08:18.658
# 是呀  還蠻多的  哎呀
Yea! We’ve quite a lot here. Aya!

0:08:18.662,0:08:19.870
# 我要把這個搞完啦
Don’t break this thing.

0:08:20.608,0:08:21.392
# 搬回去
Let’s take it back.

0:08:40.796,0:08:44.807
# 剛好搞野果  路過兄弟家的那個果園 一大片都是哦
We’ve just finished picking the wild fruits and now we pass by our buddy’s orchard. It’s the whole area here.

0:08:45.176,0:08:49.613
# 這裡最少能產個  七八  七八十萬斤吧
Here can yield at least, three, four, three or four hundred thousand kilograms, right?

0:08:50.367,0:08:53.296
# 應該有那麼多  你看  那邊那邊那邊  裡面還有哦
Yea! I think so. Look! There, there, there and more inside.

0:08:53.604,0:08:54.659
# 這邊快黃啦
Those on this side are becoming ripe very soon.

0:08:55.653,0:08:57.166
# 這邊是向陽的地方
They’re facing the sunshine on this side.

0:09:00.063,0:09:02.611
# 這裡  這裡再過十天應該就可以摘啦
I think these, these can be picked in ten days.

0:09:04.481,0:09:08.949
# 你看這裡  全是標準果哦  不大又不小 剛剛好
Look! The oranges here are all in standard size. Not too big, not too small. Just right

0:09:09.470,0:09:10.861
# 這種果其實洗都不用洗的哦
In fact these oranges don’t need to be washed at all, you know.

0:09:10.864,0:09:14.189
# 摘下來就直接裝箱  這樣它就更新鮮
They can be boxed right away from the tree. This can retain the freshness.

0:09:14.650,0:09:16.650
# 你看  這個果很漂亮吧這個
Look! This orange is really pretty, isn’t it?

0:09:17.183,0:09:18.711
# 不大不小  剛剛好哦  這種
The size is just right, perfect, this one.

0:09:19.659,0:09:20.379
# 還沒熟
But it’s not yet ripe.

0:09:20.696,0:09:23.336
# 不是  現在已經可以  可以吃了  但是有點
No! In fact, it can already be, can be eaten now. But it may be a bit,

0:09:23.336,0:09:25.519
# 可能還有點酸  酸酸甜甜的
it may be a bit sour, sweet and sour.

0:09:25.979,0:09:29.411
# 等到它全部  整個  象這種顏色的時候
We gotta wait, until all, the whole orange, is in this colour.

0:09:30.176,0:09:33.227
# 那就是黃了  熟透了 那個才是真正的臍橙
Then it is ripe, completely ripe. And it will be an authentic navel orange.

0:09:33.535,0:09:35.535
# 剛剛來到兄弟家  他說他不在呦
We’ve just arrived at our buddy’s place. But it said that he’s not here.

0:09:35.886,0:09:36.926
# 關也關著的
The gates are also closed.

0:09:37.448,0:09:39.677
# 你看  他的臍橙  那麼多臍橙他也不看一下
Look! His navel oranges. He has so many oranges but he’s not watching them.

0:09:40.045,0:09:41.024
# 就不怕我摘
Doesn’t he know that I may be picking them?

0:09:41.712,0:09:42.417
# 真是的
Unbelievable!

0:09:43.136,0:09:43.978
# 那麼多
There are so many!

0:09:45.170,0:09:46.850
# 順便叫他送一點給我吃
Why don’t we ask him to give us some?

0:09:50.918,0:09:52.827
# 乾趴趴的  搞了一天
I’m fatigue. A whole day, non-stop!

0:09:53.881,0:09:55.089
# 吃的又太飽了
And I’ve also eaten too much.

0:09:55.823,0:09:56.711
# 把它倒出來
Let me pour them out.

0:10:06.936,0:10:08.525
# 哎呀  全部爆掉啦
Aya! All are cracked,

0:10:09.442,0:10:12.000
# 爛掉的爛掉  爆掉的爆掉  你看這個
either rotten, or cracked. Have a look at this one!

0:10:12.405,0:10:14.329
# 這種就好吃噠  這種
This one is really tasty, this kind.

0:10:15.185,0:10:17.002
# 我都至少吃了二三十個啦
I’ve eaten at least twenty or thirty already.

0:10:22.208,0:10:23.309
# 也給點兄弟
Let me leave some for my buddy.

0:10:23.617,0:10:26.866
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.

0:10:28.656,0:10:32.225
# 等下兄弟會過來  自己拿  叫他帶個鴨子殺一下
My buddy will be coming in a while. He’ll take the fruits himself. Let me ask him to bring a duck here for us.

0:10:32.899,0:10:33.680
# 搞的那麼累
It's really tiring.

**Comment by vincenthychow** [comment]
已發佈
