### ISSUE TITLE
[老饭骨] 金刚火方 - https://youtu.be/uFizmfmLkaw

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1612]
**视频链接**：https://youtu.be/uFizmfmLkaw

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【國宴大師•金剛火方】汁明芡亮！你以為這是一塊東坡肉嗎？國宴大師帶大家解鎖吃不胖的“肉”！吊湯和煲湯的區別|老飯骨
简介
大家好，今天二伯为大家带来一道吃不胖的“肉”——金刚火方！
大家知道这是什么做的呢？是不是很像之前做过的大肉方？
忘记了的小友可以去复习一下！大肉方链接：https://youtu.be/XIFhuncNUQk
本期食材主要有：冬瓜、猴头菇、酥肉、鸡蛋、香菇、菜心、盐、食用油、胡椒粉、淀粉、老抽、葱姜、八角、料酒、酱油、糖、耗油
想知道这些食材怎样才能做出这样一道健康美味的“肉”菜吗？快点击视频，片尾还有大爷二伯的答疑时间！

字幕
1
00:00:00,000 --> 00:00:03,470
一般人不知道 以为就是一块东坡肉

2
00:00:03,470 --> 00:00:05,672
但是没想到 一下嘴

3
00:00:07,807 --> 00:00:09,776
 用最便宜的食材

4
00:00:09,776 --> 00:00:11,011
做出你吃不起的样子

5
00:00:13,346 --> 00:00:15,015
原料是冬瓜

6
00:00:15,015 --> 00:00:17,817
猴头菇 素肉 鸡蛋

7
00:00:17,817 --> 00:00:20,854
这是猴头菇 魏刚强提前给切好了的

8
00:00:20,854 --> 00:00:23,289
这全是素的啊师父 没肉啊

9
00:00:23,289 --> 00:00:25,191
您看见没有 这冬瓜

10
00:00:25,191 --> 00:00:28,395
切成一方块 然后两边一片这儿一片

11
00:00:28,395 --> 00:00:31,664
然后你看 打这么一个方块就出来了

12
00:00:31,664 --> 00:00:32,799
其实很简单

13
00:00:32,799 --> 00:00:37,437
一刀唰一剔 一刀一剔

14
00:00:37,437 --> 00:00:40,807
这叫什么菜名 金刚火方

15
00:00:40,807 --> 00:00:44,210
这是功德林的代表名菜

16
00:00:44,210 --> 00:00:45,779
这个您看

17
00:00:45,779 --> 00:00:49,149
这猴头菇先拿水加点味煮它一下

18
00:00:49,149 --> 00:00:52,052
猴头菇必须得出水 鲜的也得出水

19
00:00:52,052 --> 00:00:54,054
出水以后去去它那个味道

20
00:00:54,054 --> 00:00:56,256
小魏你看 为什么要剁啊你知道么

21
00:00:56,256 --> 00:00:59,259
剁完之后它就有黏性了 否则它散

22
00:00:59,259 --> 00:01:01,694
这就行了

23
00:01:04,664 --> 00:01:07,300
这个素肉是什么成分呢

24
00:01:07,300 --> 00:01:09,335
大豆做的蛋白

25
00:01:09,335 --> 00:01:12,272
这个东西多点少点都没关系

26
00:01:12,272 --> 00:01:13,540
这馅儿准备好了 调味了

27
00:01:18,411 --> 00:01:22,248
这个一个蛋黄 其实有半个蛋黄就足够

28
00:01:22,248 --> 00:01:24,584
这是俗家的素席

29
00:01:24,584 --> 00:01:27,554
加点盐 放放放

30
00:01:28,621 --> 00:01:30,190
胡椒粉

31
00:01:31,291 --> 00:01:31,891
行了

32
00:01:31,891 --> 00:01:33,927
来点粉子

33
00:01:33,927 --> 00:01:36,863
摔拌
뉎㽒൑

34
00:01:36,863 --> 00:01:38,498
原料拍粉

35
00:01:38,498 --> 00:01:40,934
干粉子 为了叫它抓住

36
00:01:40,934 --> 00:01:43,736
粉子它能拿劲儿啊 能粘
荎൛

37
00:01:43,736 --> 00:01:48,675
你看 这基本粉子就铺匀了

38
00:01:48,675 --> 00:01:49,375
瓤馅了得

39
00:01:49,375 --> 00:01:52,278
把馅儿抹在冬瓜上

40
00:01:52,278 --> 00:01:54,981
这槽好粘东西啊 要不然粘不上

41
00:01:54,981 --> 00:01:58,651
它有附着力 它能黏合
上能抓住劲儿

42
00:01:58,651 --> 00:02:00,954
这点馅儿正合适

43
00:02:00,954 --> 00:02:03,857
怎么这么会弄啊 没毛病师父

44
00:02:03,857 --> 00:02:06,359
抹蛋清 光滑

45
00:02:06,359 --> 00:02:09,028
封住它的平面

46
00:02:09,028 --> 00:02:11,264
来点老抽吧小魏 来啦

47
00:02:11,264 --> 00:02:13,700
像五花三层的样

48
00:02:13,700 --> 00:02:16,336
你看 层出来了

49
00:02:16,336 --> 00:02:17,704
大爷 你看 

50
00:02:19,772 --> 00:02:23,276
抹上点老抽

51
00:02:23,276 --> 00:02:25,678
这有点像我们的扣肉一样

52
00:02:25,678 --> 00:02:28,548
抹点老抽下锅炸的时候
上色

53
00:02:28,548 --> 00:02:33,386
来 师父 笊篱

54
00:02:33,386 --> 00:02:35,688
差不多了 六到七成油温

55
00:02:37,757 --> 00:02:42,128
 
先不能攉拢啊 定型
上色

56
00:02:42,128 --> 00:02:44,898
漂亮啊 五花肉出来了

57
00:02:46,065 --> 00:02:47,100
没问题

58
00:02:50,503 --> 00:02:51,571
肉方出来了

59
00:02:51,571 --> 00:02:54,707
这还是 不错的啊 妥妥的

60
00:02:54,707 --> 00:02:55,508
炒汁儿了开始

61
00:02:57,110 --> 00:03:01,414
来点油 葱姜大料 料酒

62
00:03:01,414 --> 00:03:04,017
香菇水

63
00:03:04,017 --> 00:03:06,052
 
71
00:03:06,920 --> 00:03:09,520
酱油

64
00:03:09,489 --> 00:03:11,591
再加点水啊 大爷

65
00:03:11,591 --> 00:03:15,028
胡椒粉 很简单

66
00:03:15,028 --> 00:03:19,532
稍微点点儿糖 来点蚝油 香菇

67
00:03:19,532 --> 00:03:24,837
好 把这葱姜香味熬出来

68
00:03:24,837 --> 00:03:25,939
大爷您看

69
00:03:27,473 --> 00:03:29,809
 
79
00:03:29,840 --> 00:03:33,680
葱姜香菇熬的水 还有大料

70
00:03:33,646 --> 00:03:35,949
熬好了以后我们就灌到

71
00:03:35,949 --> 00:03:39,786
炸好的冬瓜方
⁎
Վ쭟롙඄

72
00:03:39,786 --> 00:03:42,222
半个小时就差不多了

73
00:03:42,222 --> 00:03:44,357
盖盖儿 水够足么 够足

74
00:03:44,357 --> 00:03:45,458
下一步我们配点油菜吧

75
00:03:45,458 --> 00:03:47,894
削好了以后 胡萝卜头儿您看

76
00:03:47,894 --> 00:03:52,398
插进去就行了 这叫鹦鹉菜心

77
00:03:52,398 --> 00:03:54,634
水边加点盐 加点糖

78
00:03:54,634 --> 00:03:56,236
提鲜 还有去涩的作用

79
00:03:56,236 --> 00:04:00,473
我们再滴一点明油 翠绿光亮

80
00:04:00,473 --> 00:04:02,208
稍微一烫

81
00:04:02,208 --> 00:04:07,914
 
92
00:04:07,920 --> 00:04:08,760
好了

82
00:04:08,748 --> 00:04:10,617
关火

83
00:04:10,617 --> 00:04:12,585
小魏这重要任务交给你了 半个小时

84
00:04:12,585 --> 00:04:13,653
师父我给你出盘

85
00:04:15,021 --> 00:04:16,556
出锅喽

86
00:04:16,556 --> 00:04:19,459
可以了啊 把这葱姜拣出去

87
00:04:19,459 --> 00:04:23,596
取其精华 去其糟粕 本味

88
00:04:23,596 --> 00:04:26,199
（原汤倒进锅里）

89
00:04:26,199 --> 00:04:27,834
别着急慢慢的来

90
00:04:27,834 --> 00:04:31,170
你看 走起

91
00:04:31,170 --> 00:04:34,107
你行啊你

92
00:04:34,107 --> 00:04:34,674
 
104
00:04:37,240 --> 00:04:38,480
出水见芙蓉

93
00:04:38,478 --> 00:04:40,813
像个五花肉

94
00:04:40,813 --> 00:04:42,148
 
107
00:04:42,160 --> 00:04:44,720
跟五花肉一样 行了

95
00:04:44,717 --> 00:04:47,754
让它似开非开 然后勾芡

96
00:04:47,754 --> 00:04:49,956
再淋点颜色 老抽

97
00:04:49,956 --> 00:04:52,992
蒸的原汤 勾点芡

98
00:04:52,992 --> 00:04:55,461
小火 勾芡要用小火

99
00:04:55,461 --> 00:04:58,931
为什么用小火啊 出来芡亮

100
00:04:58,931 --> 00:05:03,703
 
114
00:05:03,720 --> 00:05:05,840
这回行了 好

101
00:05:05,838 --> 00:05:06,839
 
116
00:05:06,840 --> 00:05:07,720
淋点油

102
00:05:07,707 --> 00:05:07,740
 
118
00:05:07,760 --> 00:05:13,960
明油 这是粤菜的打蚝油芡的手法

103
00:05:13,946 --> 00:05:17,250
 
120
00:05:17,280 --> 00:05:18,680
油在
扎ʗ䁯൷

104
00:05:18,651 --> 00:05:24,290
 
122
00:05:24,320 --> 00:05:26,880
这四周这汁儿划圆了它

105
00:05:26,859 --> 00:05:29,028
小魏把菜心拿来

106
00:05:29,028 --> 00:05:31,197
九个 一边三棵

107
00:05:31,197 --> 00:05:34,934
摆一圈就行了 齐活

108
00:05:34,934 --> 00:05:38,905
金刚火方 漂亮

109
00:05:38,905 --> 00:05:40,940
这菜我看了N多遍了

110
00:05:40,940 --> 00:05:42,275
但是我一次都没吃过

111
00:05:42,275 --> 00:05:45,111
 
130
00:05:45,120 --> 00:05:47,920
大爷 您老先尝 谢谢

112
00:05:47,914 --> 00:05:50,650
 
132
00:05:50,680 --> 00:05:53,280
好吃 猛一眼看

113
00:05:53,252 --> 00:05:58,157
就跟
ⅎ豫⽎婏읐蒏❶륙襥₀

114
00:05:58,157 --> 00:05:58,191
 
135
00:05:59,840 --> 00:06:02,080
这冬瓜 看似好像硬点

115
00:06:02,061 --> 00:06:03,496
但是它不能软了

116
00:06:03,496 --> 00:06:08,234
再软肉馅和冬瓜就分离了

117
00:06:08,234 --> 00:06:09,702
它必须得拿住它

118
00:06:09,702 --> 00:06:11,871
甜咸适中 汁儿红芡儿亮

119
00:06:11,871 --> 00:06:14,807
五花三层 你吃的是肥的

120
00:06:16,476 --> 00:06:18,578
确实地道啊

121
00:06:18,578 --> 00:06:21,781
一个普通的不起眼的食材

122
00:06:21,781 --> 00:06:24,217
做出了一道大菜

123
00:06:24,717 --> 00:06:26,853
谢谢二伯 谢谢师父

124
00:06:26,853 --> 00:06:28,388


125
00:06:39,932 --> 00:06:41,968
煲汤是把原材料搁在里边

126
00:06:42,001 --> 00:06:43,069
慢慢的煲

127
00:06:43,269 --> 00:06:44,303
一次性成熟

128
00:06:44,303 --> 00:06:45,171
吊汤就不一样

129
00:06:45,171 --> 00:06:46,172
比如说我们吊清汤

130
00:06:46,172 --> 00:06:46,806
吊完之后

131
00:06:46,839 --> 00:06:47,807
再进行清

132
00:06:47,807 --> 00:06:48,408
时间不一样

133
00:06:48,441 --> 00:06:50,276
吊汤是做菜用的

134
00:06:50,276 --> 00:06:51,911
煲汤是直接喝的

135
00:06:55,047 --> 00:06:57,049
开水白菜从吊汤开始

136
00:06:57,049 --> 00:06:58,384
吊完汤以后呢

137
00:06:58,518 --> 00:07:00,386
提出来以后要把油撇干净

138
00:07:00,386 --> 00:07:03,156
用鸡臊子把汤给搞清

139
00:07:03,156 --> 00:07:05,825
白菜再用开水烫熟

140
00:07:06,225 --> 00:07:08,828
捋齐 灌上清汤上锅一蒸

141
00:07:08,861 --> 00:07:09,729
就好了

142
00:07:12,865 --> 00:07:14,901
吊汤来讲呢又分为有白臊

143
00:07:14,901 --> 00:07:16,035
有红臊

144
00:07:16,068 --> 00:07:18,104
白臊是鸡胸肉来调

145
00:07:18,104 --> 00:07:21,874
红臊有的汤是清真用的

146
00:07:22,041 --> 00:07:24,944
茶色 再用白臊再臊一遍

147
00:07:24,944 --> 00:07:27,780
这样这汤又香又鲜

148
00:07:27,780 --> 00:07:28,948
那双吊汤呢

149
00:07:28,948 --> 00:07:30,650
牛肉臊一遍鸡肉臊一遍

150
00:07:35,087 --> 00:07:36,823
我们在撇沫子的时候

151
00:07:37,123 --> 00:07:39,025
就感觉上撇干净了

152
00:07:39,425 --> 00:07:41,160
但我们再用点凉水

153
00:07:41,160 --> 00:07:42,728
再把它炸一下

154
00:07:42,929 --> 00:07:43,963
它一开锅以后

155
00:07:44,030 --> 00:07:45,431
还会产生一些浮沫

156
00:07:45,798 --> 00:07:47,400
再把沫子一清

157
00:07:47,400 --> 00:07:49,168
这汤显得更加清

158
00:07:52,672 --> 00:07:55,341
它是分阶段的去进行腌制的

159
00:07:55,441 --> 00:07:56,909
比如说我们明天用

160
00:07:56,909 --> 00:07:58,044
我们今天晚上加工出来

161
00:07:58,044 --> 00:07:59,645
搁冰箱第二天再用

162
00:07:59,645 --> 00:08:00,680
这效果更好

```

**Comment by lulufun** [comment]
认领

**Comment by lulufun** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【國宴大師•金剛火方】汁明芡亮！你以為這是一塊東坡肉嗎？國宴大師帶大家解鎖吃不胖的“肉”！吊湯和煲湯的區別|老飯骨
简介
大家好，今天二伯为大家带来一道吃不胖的“肉”——金刚火方！
大家知道这是什么做的呢？是不是很像之前做过的大肉方？
忘记了的小友可以去复习一下！大肉方链接：https://youtu.be/XIFhuncNUQk
本期食材主要有：冬瓜、猴头菇、酥肉、鸡蛋、香菇、菜心、盐、食用油、胡椒粉、淀粉、老抽、葱姜、八角、料酒、酱油、糖、耗油
想知道这些食材怎样才能做出这样一道健康美味的“肉”菜吗？快点击视频，片尾还有大爷二伯的答疑时间！

State Banquet Master Chef - King Kong “Meat Cube”. Do you think this is a piece of meat? 
Introduction
Hello everyone, today Er Bai brings you a "meat" that will not make you fat-King Kong “Meat Cube”!
Do you know what this is made of? Is it very similar to the big pork cube we have made before?
Those who have forgotten can go and review it! Link for Braised Pork Cube: https://youtu.be/XIFhuncNUQk
The main ingredients in this video are: winter melon, hericium edodes, crispy “pork”, eggs, shiitake mushrooms, bok choy, salt, oil, pepper, starch, soy sauce, green onion, ginger, star anise, cooking wine, soy sauce, sugar, oyster sauce
Want to know how these ingredients can make such a healthy and delicious "meat" dish? Hurry up and click on the video, and there is Q&A at the end of the film!

# import intro


字幕
1
00:00:00,000 --> 00:00:03,470
一般人不知道 以为就是一块东坡肉
Most people don’t know, they think it’s a piece of Dongpo Pork

2
00:00:03,470 --> 00:00:05,672
但是没想到 一下嘴	
But didn't expect, when you put it in your mouth

3
00:00:07,807 --> 00:00:09,776
 用最便宜的食材
Use the cheapest ingredients

4
00:00:09,776 --> 00:00:11,011
做出你吃不起的样子
Make something look like you can't afford it

5
00:00:13,346 --> 00:00:15,015
原料是冬瓜
The ingredient is winter melon

6
00:00:15,015 --> 00:00:17,817
猴头菇 素肉 鸡蛋
Hericium edodes, vegetarian meat, and eggs

7
00:00:17,817 --> 00:00:20,854
这是猴头菇 魏刚强提前给切好了的
This is hericium edodes. Wei Gangqiang cut it in advance

8
00:00:20,854 --> 00:00:23,289
这全是素的啊师父 没肉啊
This is all vegetable, Master, no meat

9
00:00:23,289 --> 00:00:25,191
您看见没有 这冬瓜
Did you see this winter melon

10
00:00:25,191 --> 00:00:28,395
切成一方块 然后两边一片这儿一片
Cut into a square and then one on both sides, one here

11
00:00:28,395 --> 00:00:31,664
然后你看 打这么一个方块就出来了
Then you see, you can make it to a square shape

12
00:00:31,664 --> 00:00:32,799
其实很简单
it's actually really easy

13
00:00:32,799 --> 00:00:37,437
一刀唰一剔 一刀一剔
One cut and one tick

14
00:00:37,437 --> 00:00:40,807
这叫什么菜名 金刚火方
What is the name of this dish? King Kong “Meat Cube”

15
00:00:40,807 --> 00:00:44,210
这是功德林的代表名菜
This is the representative dish of Gong De Lin

16
00:00:44,210 --> 00:00:45,779
这个您看
Look at this

17
00:00:45,779 --> 00:00:49,149
这猴头菇先拿水加点味煮它一下
This Hericium edodes is cooked with some water

18
00:00:49,149 --> 00:00:52,052
猴头菇必须得出水 鲜的也得出水
This Hericium edodes need to be cooked, even for fresh ones

19
00:00:52,052 --> 00:00:54,054
出水以后去去它那个味道
After boiling, it can get rid of its (earthy) taste

20
00:00:54,054 --> 00:00:56,256
小魏你看 为什么要剁啊你知道么
Look, Xiaowei, why chop? Do you know?

21
00:00:56,256 --> 00:00:59,259
剁完之后它就有黏性了 否则它散
It will become sticky after chopping, otherwise it is loose

22
00:00:59,259 --> 00:01:01,694
这就行了
That's it

23
00:01:04,664 --> 00:01:07,300
这个素肉是什么成分呢		
What is the ingredient of this vegetarian meat?

24
00:01:07,300 --> 00:01:09,335
大豆做的蛋白
Soy protein

25
00:01:09,335 --> 00:01:12,272
这个东西多点少点都没关系
It doesn't matter to use this stuff a bit more or less

26
00:01:12,272 --> 00:01:13,540
这馅儿准备好了 调味了
The stuffing is ready and seasoned

27
00:01:18,411 --> 00:01:22,248
这个一个蛋黄 其实有半个蛋黄就足够
This one egg yolk, actually half is enough

28
00:01:22,248 --> 00:01:24,584
这是俗家的素席
This is a Buddhist banquet

29
00:01:24,584 --> 00:01:27,554
加点盐 放放放
Add some salt

30
00:01:28,621 --> 00:01:30,190
胡椒粉
pepper

31
00:01:31,291 --> 00:01:31,891
行了
Enough

32
00:01:31,891 --> 00:01:33,927
来点粉子
Some starch

33
00:01:33,927 --> 00:01:36,863
摔拌
Beat and mix

34
00:01:36,863 --> 00:01:38,498
原料拍粉
Put some starch on the ingredient

35
00:01:38,498 --> 00:01:40,934
干粉子 为了叫它抓住		
Dry starch, in order to make it easy to grab (other ingredients)

36
00:01:40,934 --> 00:01:43,736
粉子它能拿劲儿啊 能粘
Starch can grab (other ingredients) and be sticky

37
00:01:43,736 --> 00:01:48,675
你看 这基本粉子就铺匀了
You see, the starch is evenly spread

38
00:01:48,675 --> 00:01:49,375
瓤馅了得
Stuffing now

39
00:01:49,375 --> 00:01:52,278
把馅儿抹在冬瓜上
Put the stuffing on the winter melon

40
00:01:52,278 --> 00:01:54,981
这槽好粘东西啊 要不然粘不上
This slot make it easy to stick stuffing, otherwise it won’t stick

41
00:01:54,981 --> 00:01:58,651
它有附着力 它能黏合
上能抓住劲儿
It has adhesion, it can stick, can grab 

42
00:01:58,651 --> 00:02:00,954
这点馅儿正合适
This stuffing is right

43
00:02:00,954 --> 00:02:03,857
怎么这么会弄啊 没毛病师父
Why do you really good at this? No problem, Master

44
00:02:03,857 --> 00:02:06,359
抹蛋清 光滑
Spread the egg whites, smooth

45
00:02:06,359 --> 00:02:09,028
封住它的平面
Seal its surface

46
00:02:09,028 --> 00:02:11,264
来点老抽吧小魏 来啦
Some soy sauce, Xiao Wei, here

47
00:02:11,264 --> 00:02:13,700
像五花三层的样
Like pork belly, with three layers

48
00:02:13,700 --> 00:02:16,336
你看 层出来了
You see, the layers come out

49
00:02:16,336 --> 00:02:17,704
大爷 你看 
Da Ye, look

50
00:02:19,772 --> 00:02:23,276
抹上点老抽
Spread some dark soy sauce

51
00:02:23,276 --> 00:02:25,678
这有点像我们的扣肉一样
This is a bit like our meat

52
00:02:25,678 --> 00:02:28,548
抹点老抽下锅炸的时候
上色
Spread some dark soy sauce for coloring when frying

53
00:02:28,548 --> 00:02:33,386
来 师父 笊篱
Come, master, sieve

54
00:02:33,386 --> 00:02:35,688
差不多了 六到七成油温
It's almost 60 to 70% oil temperature (180 – 210 C)

55
00:02:37,757 --> 00:02:42,128
先不能攉拢啊 定型
上色
Shouldn’t move it around first, fix the shape and coloring

56
00:02:42,128 --> 00:02:44,898
漂亮啊 五花肉出来了
It’s pretty. Pork belly is here.

57
00:02:46,065 --> 00:02:47,100
没问题
No problem

58
00:02:50,503 --> 00:02:51,571
肉方出来了
You can see the “meat cube” now

59
00:02:51,571 --> 00:02:54,707
这还是 不错的啊 妥妥的
This is still good.

60
00:02:54,707 --> 00:02:55,508
炒汁儿了开始
Frying sauce

61
00:02:57,110 --> 00:03:01,414
来点油 葱姜大料 料酒
Some oil, green onion and ginger, cooking wine

62
00:03:01,414 --> 00:03:04,017
香菇水
Soaked mushroom water

63
00:03:04,017 --> 00:03:06,052
 
71
00:03:06,920 --> 00:03:09,520
酱油
Soy sauce


64
00:03:09,489 --> 00:03:11,591
再加点水啊 大爷
Add some water, Da Ye.

65
00:03:11,591 --> 00:03:15,028
胡椒粉 很简单
Pepper powder, very simple


66
00:03:15,028 --> 00:03:19,532
稍微点点儿糖 来点蚝油 香菇
A little sugar, some oyster sauce, shiitake mushrooms

67
00:03:19,532 --> 00:03:24,837
好 把这葱姜香味熬出来
OK, boil out the green onion and ginger fragrance

68
00:03:24,837 --> 00:03:25,939
大爷您看
Da Ye, see

69
00:03:27,473 --> 00:03:29,809
 
79
00:03:29,840 --> 00:03:33,680
葱姜香菇熬的水 还有大料
The water boiled with green onion, ginger, mushrooms and star anise

70
00:03:33,646 --> 00:03:35,949
熬好了以后我们就灌到
After it's cooked, we will pour it on

71
00:03:35,949 --> 00:03:39,786
炸好的冬瓜方
Fried winter melon cube

72
00:03:39,786 --> 00:03:42,222
半个小时就差不多了
It's almost half an hour

73
00:03:42,222 --> 00:03:44,357
盖盖儿 水够足么 够足
Cover it. Is the water enough? Enough

74
00:03:44,357 --> 00:03:45,458
下一步我们配点油菜吧
Let's prepare some bok choy next

75
00:03:45,458 --> 00:03:47,894
削好了以后 胡萝卜头儿您看
After cutting it, look at the carrot head

76
00:03:47,894 --> 00:03:52,398
插进去就行了 这叫鹦鹉菜心
Just plug it in. This is called Parrot Bok Choy

77
00:03:52,398 --> 00:03:54,634
水边加点盐 加点糖
Add some salt to the water and some sugar

78
00:03:54,634 --> 00:03:56,236
提鲜 还有去涩的作用
Improve taste and remove astringency

79
00:03:56,236 --> 00:04:00,473
我们再滴一点明油 翠绿光亮
Let's add a little bit of oil, to make it bright green

80
00:04:00,473 --> 00:04:02,208
稍微一烫
Slightly parboil

81
00:04:02,208 --> 00:04:07,914
 
92
00:04:07,920 --> 00:04:08,760
好了
Good

82
00:04:08,748 --> 00:04:10,617
关火
Turn off heat

83
00:04:10,617 --> 00:04:12,585
小魏这重要任务交给你了 半个小时
Xiao Wei, this important task is on your shoulder.For half an hour

84
00:04:12,585 --> 00:04:13,653
师父我给你出盘
Master, I will help you take it out

85
00:04:15,021 --> 00:04:16,556
出锅喽
Out of the pot

86
00:04:16,556 --> 00:04:19,459
可以了啊 把这葱姜拣出去
Okay, pick out the green onion and ginger

87
00:04:19,459 --> 00:04:23,596
取其精华 去其糟粕 本味
Take the essence and remove the dross

88
00:04:23,596 --> 00:04:26,199
（原汤倒进锅里）
(Pour the original soup into the pot)

89
00:04:26,199 --> 00:04:27,834
别着急慢慢的来
Don't worry and do it slowly

90
00:04:27,834 --> 00:04:31,170
你看 走起
See, there we go

91
00:04:31,170 --> 00:04:34,107
你行啊你
Not bad!

92
00:04:34,107 --> 00:04:34,674
 
104
00:04:37,240 --> 00:04:38,480
出水见芙蓉
See Lotus in the Water

93
00:04:38,478 --> 00:04:40,813
像个五花肉
Like a pork belly

94
00:04:40,813 --> 00:04:42,148
 
107
00:04:42,160 --> 00:04:44,720
跟五花肉一样 行了
Same as pork belly. Good

95
00:04:44,717 --> 00:04:47,754
让它似开非开 然后勾芡
Make it looks open but not fully open, and then make slurry

96
00:04:47,754 --> 00:04:49,956
再淋点颜色 老抽
More color, soy sauce

97
00:04:49,956 --> 00:04:52,992
蒸的原汤 勾点芡
Original soup from steaming, make the slurry

98
00:04:52,992 --> 00:04:55,461
小火 勾芡要用小火
Low heat, use low heat to make the slurry

99
00:04:55,461 --> 00:04:58,931
为什么用小火啊 出来芡亮
Why use a low heat? The slurry will be shinny

100
00:04:58,931 --> 00:05:03,703
 
114
00:05:03,720 --> 00:05:05,840
这回行了 好
Now looks good. Good

101
00:05:05,838 --> 00:05:06,839
 
116
00:05:06,840 --> 00:05:07,720
淋点油
Some oil

102
00:05:07,707 --> 00:05:07,740
 
118
00:05:07,760 --> 00:05:13,960
明油 这是粤菜的打蚝油芡的手法
Oil, this is the way to make oyster sauce slurry in Cantonese cuisine

103
00:05:13,946 --> 00:05:17,250
 
120
00:05:17,280 --> 00:05:18,680
油在
Oil in

104
00:05:18,651 --> 00:05:24,290
 
122
00:05:24,320 --> 00:05:26,880
这四周这汁儿划圆了它
Around the cube, make it round

105
00:05:26,859 --> 00:05:29,028
小魏把菜心拿来
Xiao Wei brought the bok choy

106
00:05:29,028 --> 00:05:31,197
九个 一边三棵
Nine, three on each side

107
00:05:31,197 --> 00:05:34,934
摆一圈就行了 齐活
Just arrange them in a circle, done.

108
00:05:34,934 --> 00:05:38,905
金刚火方 漂亮
King Kong “Meat Cube”. Beautiful

109
00:05:38,905 --> 00:05:40,940
这菜我看了N多遍了
I have watched this dish N times

110
00:05:40,940 --> 00:05:42,275
但是我一次都没吃过
But I haven't eaten it once

111
00:05:42,275 --> 00:05:45,111
 
130
00:05:45,120 --> 00:05:47,920
大爷 您老先尝 谢谢
Da Ye, you try it first. thank you

112
00:05:47,914 --> 00:05:50,650
 
132
00:05:50,680 --> 00:05:53,280
好吃 猛一眼看
Delicious, take a quick look

113
00:05:53,252 --> 00:05:58,157
就跟
like

114
00:05:58,157 --> 00:05:58,191
 
135
00:05:59,840 --> 00:06:02,080
这冬瓜 看似好像硬点
This winter melon seems a bit too hard

115
00:06:02,061 --> 00:06:03,496
但是它不能软了
But it can't be more soft

116
00:06:03,496 --> 00:06:08,234
再软肉馅和冬瓜就分离了
If so, the “meat” and winter melon are separated

117
00:06:08,234 --> 00:06:09,702
它必须得拿住它
It has to grab it

118
00:06:09,702 --> 00:06:11,871
甜咸适中 汁儿红芡儿亮
Moderately sweet and salty, bright red slurry

119
00:06:11,871 --> 00:06:14,807
五花三层 你吃的是肥的
“Pork belly”, what you eat is “fat”

120
00:06:16,476 --> 00:06:18,578
确实地道啊
Really authentic

121
00:06:18,578 --> 00:06:21,781
一个普通的不起眼的食材
An ordinary ingredient

122
00:06:21,781 --> 00:06:24,217
做出了一道大菜
Made a big dish

123
00:06:24,717 --> 00:06:26,853
谢谢二伯 谢谢师父
Thank you Er Bai, thank you master

124
00:06:26,853 --> 00:06:28,388


125
00:06:39,932 --> 00:06:41,968
煲汤是把原材料搁在里边
Soup is to put the raw materials inside

126
00:06:42,001 --> 00:06:43,069
慢慢的煲
Slowly cook

127
00:06:43,269 --> 00:06:44,303
一次性成熟
One-time mature

128
00:06:44,303 --> 00:06:45,171
吊汤就不一样
Broth is different

129
00:06:45,171 --> 00:06:46,172
比如说我们吊清汤
For example, we make clear broth

130
00:06:46,172 --> 00:06:46,806
吊完之后
After the broth is made 

131
00:06:46,839 --> 00:06:47,807
再进行清
You then make it clear

132
00:06:47,807 --> 00:06:48,408
时间不一样
Time is different

133
00:06:48,441 --> 00:06:50,276
吊汤是做菜用的
Broth is for cooking

134
00:06:50,276 --> 00:06:51,911
煲汤是直接喝的
Soup is for eating directly

135
00:06:55,047 --> 00:06:57,049
开水白菜从吊汤开始
Boiling cabbage starts from making broth

136
00:06:57,049 --> 00:06:58,384
吊完汤以后呢
After the broth is made

137
00:06:58,518 --> 00:07:00,386
提出来以后要把油撇干净
Skim off the oil after you bring it up

138
00:07:00,386 --> 00:07:03,156
用鸡臊子把汤给搞清
Use chicken broth to make it clear

139
00:07:03,156 --> 00:07:05,825
白菜再用开水烫熟
Boil the cabbage in boiling water

140
00:07:06,225 --> 00:07:08,828
捋齐 灌上清汤上锅一蒸
Make it tidy, pour the clear broth and steam it

141
00:07:08,861 --> 00:07:09,729
就好了
It’s done

142
00:07:12,865 --> 00:07:14,901
吊汤来讲呢又分为有白臊
In terms of broth, it is divided into white minced meat

143
00:07:14,901 --> 00:07:16,035
有红臊
And Red minced meat

144
00:07:16,068 --> 00:07:18,104
白臊是鸡胸肉来调
White minced meat is made from chicken breast

145
00:07:18,104 --> 00:07:21,874
红臊有的汤是清真用的
Red minced meat is for halal dishes

146
00:07:22,041 --> 00:07:24,944
茶色 再用白臊再臊一遍
Tea color, use white minced meat to clear it one more time

147
00:07:24,944 --> 00:07:27,780
这样这汤又香又鲜
So this soup is fragrant and fresh

148
00:07:27,780 --> 00:07:28,948
那双吊汤呢
What about the double broth

149
00:07:28,948 --> 00:07:30,650
牛肉臊一遍鸡肉臊一遍
Use minced beef and minced chicken to clear

150
00:07:35,087 --> 00:07:36,823
我们在撇沫子的时候
When we were skimming the scum

151
00:07:37,123 --> 00:07:39,025
就感觉上撇干净了
It feels clean

152
00:07:39,425 --> 00:07:41,160
但我们再用点凉水
But if we use some cold water

153
00:07:41,160 --> 00:07:42,728
再把它炸一下
“Smash” it (make it cool down)

154
00:07:42,929 --> 00:07:43,963
它一开锅以后
Once it's boiling again

155
00:07:44,030 --> 00:07:45,431
还会产生一些浮沫
It will also produce some scum

156
00:07:45,798 --> 00:07:47,400
再把沫子一清
Then you skim off the scum

157
00:07:47,400 --> 00:07:49,168
这汤显得更加清
This soup looks clearer

158
00:07:52,672 --> 00:07:55,341
它是分阶段的去进行腌制的
It needs to marinade in stages

159
00:07:55,441 --> 00:07:56,909
比如说我们明天用
For example, we use it tomorrow

160
00:07:56,909 --> 00:07:58,044
我们今天晚上加工出来
We make it tonight

161
00:07:58,044 --> 00:07:59,645
搁冰箱第二天再用
Put in the refrigerator and use in the next day

162
00:07:59,645 --> 00:08:00,680
这效果更好
This works better
