### ISSUE TITLE
[老饭骨] 黄金炒饭 - https://youtu.be/RT9tmSnpziI

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1617]
**视频链接**：https://youtu.be/RT9tmSnpziI

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•黄金炒饭】松软弹香又油润，粒粒分明不粘锅！这样的黄金炒饭不来一碗吗？ |老饭骨

简介
小友们好，今天给大家带来一碗家常的黄金炒饭！
听着这个名字是不是就很诱人呢？每一粒米都吸收了蛋黄，颗颗分明、松软弹香又油润！
这次的讲解细节很到位，小友们可要仔细看视频，这道黄金炒饭做法也很简单，新手也能做！
不知道吃什么的时候就来一碗，小饭骨们，开饭咯！

字幕
1
00:00:00,000 --> 00:00:01,880
黄金炒饭

2
00:00:01,880 --> 00:00:06,080
每一粒米饭 都粘满了蛋黄

3
00:00:06,080 --> 00:00:07,920
所以它成为黄金炒饭

4
00:00:07,920 --> 00:00:11,800

5
00:00:11,800 --> 00:00:14,560
头天的剩米饭 一般炒饭都是剩米饭

6
00:00:14,560 --> 00:00:16,960
润润锅 家里边有不粘锅的

7
00:00:16,960 --> 00:00:18,680
咱就不用聊了 怎么都不粘

8
00:00:18,680 --> 00:00:22,120
怎么润呢 我的工作经验告诉我

9
00:00:22,120 --> 00:00:24,160
一定要把油加进去

10
00:00:24,160 --> 00:00:26,440
然后慢慢的让它加热

11
00:00:26,440 --> 00:00:29,880
怎么也得到六成以上 关火多焖一会儿

12
00:00:29,880 --> 00:00:33,040
这样它的油会渗进去一些

13
00:00:33,040 --> 00:00:36,160
在热的时候表面它就不粘了

14
00:00:36,160 --> 00:00:38,160
热的时候它是往上顶气

15
00:00:38,160 --> 00:00:42,640
准备点什么料呢 我看准备了蛋黄了

16
00:00:42,640 --> 00:00:45,920
炒米饭黄金色是由蛋黄来完成的

17
00:00:45,920 --> 00:00:47,720
那么米饭来讲

18
00:00:47,720 --> 00:00:50,840
新米饭和隔夜饭

19
00:00:50,840 --> 00:00:52,640
都没有什么太大的问题

20
00:00:52,640 --> 00:00:56,200
那么主要是米饭焖完之后

21
00:00:56,200 --> 00:00:59,160
表面它不能开花

22
00:00:59,160 --> 00:01:02,080
开花炒完之后 表面它就

23
00:01:02,080 --> 00:01:04,360
达不到那种光洁度了 就很散

24
00:01:04,360 --> 00:01:06,320
再有一定要检查

25
00:01:06,320 --> 00:01:08,240
米好坏的程度是哪里

26
00:01:08,240 --> 00:01:09,880
蒸熟之后淀粉它会糊化

27
00:01:09,880 --> 00:01:11,080
糊化之后是晶莹剔透的

28
00:01:11,080 --> 00:01:12,640
这应该是新米

29
00:01:12,640 --> 00:01:15,840
如果蒸熟之后又散花 还不剔透

30
00:01:15,840 --> 00:01:18,240
那证明是陈米 炒饭就不好炒了

31
00:01:18,240 --> 00:01:20,640
所以一炒它就会碎掉

32
00:01:20,640 --> 00:01:22,840
它难以呈现是粒粒分明

33
00:01:24,640 --> 00:01:25,720
锅润的差不多了

34
00:01:25,720 --> 00:01:28,920
先别着急 关小火 等着它没关系

35
00:01:28,920 --> 00:01:31,200
时间越长 它润的越透彻

36
00:01:31,200 --> 00:01:34,080
它就更不容易粘锅

37
00:01:34,080 --> 00:01:37,600
咱们这些米饭需要放三个蛋黄

38
00:01:38,880 --> 00:01:40,040
你看到没有

39
00:01:40,040 --> 00:01:44,280
今天隋师傅先把鸡蛋拌到米饭里边

40
00:01:44,280 --> 00:01:45,920
金黄金黄的

41
00:01:45,920 --> 00:01:48,800
米饭如果在冰箱里拿出来比较凉

42
00:01:48,800 --> 00:01:50,680
凉了之后下锅

43
00:01:50,680 --> 00:01:52,200
需要很长时间才会热

44
00:01:52,200 --> 00:01:53,920
我们就不如放在微波炉里边

45
00:01:53,920 --> 00:01:55,400
（提前）给它简单加热一下

46
00:01:55,400 --> 00:01:57,600
加热到二十来度三十来度不冰手

47
00:01:57,600 --> 00:01:59,440
而且它容易散

48
00:01:59,440 --> 00:02:01,720
为什么隔夜饭有的时候好炒

49
00:02:01,720 --> 00:02:04,640
它其实就是不容易粘锅 它容易散开

50
00:02:04,640 --> 00:02:07,200
再有 特别凉的米饭放到锅里边

51
00:02:07,200 --> 00:02:08,680
它特别容易扒锅

52
00:02:08,680 --> 00:02:11,040
温度的反差 温度反差太大了

53
00:02:11,040 --> 00:02:12,880
拌匀了就行了

54
00:02:12,880 --> 00:02:16,120
咱们这个锅润透了

55
00:02:16,120 --> 00:02:19,280

56
00:02:19,280 --> 00:02:22,160
开火 炒米饭的锅一定要干净

57
00:02:22,160 --> 00:02:25,120
看它有没有黑渣子 很干净

58
00:02:25,120 --> 00:02:26,480
这就证明炒饭没问题

59
00:02:26,480 --> 00:02:29,480
它不会影响咱们出菜的整体的颜色

60
00:02:29,480 --> 00:02:33,240
放点葱油 增加炒饭的香气

61
00:02:33,240 --> 00:02:35,560
葱 要想让它炸出香味

62
00:02:35,560 --> 00:02:36,600
就得变成金黄色

63
00:02:36,600 --> 00:02:38,360
金黄色容易出黑渣

64
00:02:38,360 --> 00:02:41,840
所以咱们就食其味不见其物

65
00:02:41,840 --> 00:02:43,560
温油 三成热

66
00:02:43,560 --> 00:02:45,760
下锅之后 不着急扒拉它

67
00:02:45,760 --> 00:02:48,920
慢慢的 下面凝固了 再扒拉一下

68
00:02:48,920 --> 00:02:51,280
完了再凝固上面的

69
00:02:51,280 --> 00:02:54,040
您快速炒 有可能这个蛋就脱掉了

70
00:02:54,040 --> 00:02:57,400
就小火不着急 慢慢让它成熟着

71
00:02:57,400 --> 00:03:00,360
米饭粒越整越晶莹剔透

72
00:03:00,360 --> 00:03:02,760
这黄颜色越好看

73
00:03:02,760 --> 00:03:05,600
然后旁边锅热了 咱们炒蛋白

74
00:03:05,600 --> 00:03:08,360
一是不浪费 二是增加一个颜色

75
00:03:08,360 --> 00:03:10,160
不着急 凝固就行

76
00:03:10,160 --> 00:03:14,960
然后加点盐调味

77
00:03:14,960 --> 00:03:17,640
鸡蛋当中含有谷氨酸钠

78
00:03:17,640 --> 00:03:19,480
所以就不用再加味精了

79
00:03:19,480 --> 00:03:22,160
然后把配料加进去

80
00:03:22,160 --> 00:03:24,640
蛋白差不多了

81
00:03:24,640 --> 00:03:27,760
你看这颜色 中火

82
00:03:27,760 --> 00:03:31,960
黄白分明 加上胡萝卜青豆 颜色美观

83
00:03:31,960 --> 00:03:33,560

84
00:03:38,800 --> 00:03:41,520
黄金炒饭 出锅啦

85
00:03:41,520 --> 00:03:45,320

86
00:03:45,320 --> 00:03:49,240
好香 真香 太香了

87
00:03:49,240 --> 00:03:52,160
你看着啊 每粒米饭

88
00:03:52,160 --> 00:03:54,720
咱把蛋白往边上扒拉扒拉

89
00:03:54,720 --> 00:03:58,000
都粘满了蛋黄

90
00:03:58,000 --> 00:04:00,080
所以它成为一个黄金炒饭

91
00:04:00,080 --> 00:04:03,840
颗粒饱满 比原来米饭粒显着大了吧

92
00:04:03,840 --> 00:04:07,160
而且松软 弹香 特别润

93
00:04:07,160 --> 00:04:10,760
所以米饭作为一个厨师的基本功来讲

94
00:04:10,760 --> 00:04:12,480
它是挺考验人的

95
00:04:12,480 --> 00:04:14,520
看似一盘炒饭

96
00:04:14,520 --> 00:04:18,800
但是它体现出一个厨师的烹饪技巧

97
00:04:18,800 --> 00:04:22,440
和他的基本功的呈现

98
00:04:22,440 --> 00:04:23,720
看起来简单

99
00:04:23,720 --> 00:04:26,600
实际上炒饭 作为一个厨师

100
00:04:26,600 --> 00:04:28,040
在行业当中这块

101
00:04:28,040 --> 00:04:30,120
是一个最难的一件事

102
00:04:30,120 --> 00:04:32,800
你看在香港搞大赛

103
00:04:32,800 --> 00:04:35,880
人家也不炒什么烧海参弄鲍鱼

104
00:04:35,880 --> 00:04:37,680
炒饭 炒牛河

105
00:04:37,680 --> 00:04:39,520
大爷这个饭我最有记忆

106
00:04:39,520 --> 00:04:41,760
您最有发言权 我还真有发言权

107
00:04:41,760 --> 00:04:45,200
我看到这个饭 就想起一件事来

108
00:04:45,200 --> 00:04:48,160
原来我记得在天伦王朝炒这饭的时候

109
00:04:48,160 --> 00:04:51,720
香港人把那火弄好了 把饭搁这

110
00:04:51,720 --> 00:04:53,520
然后直接到我这炒

111
00:04:53,520 --> 00:04:54,880
炒出就有啰嗦

112
00:04:54,880 --> 00:04:57,320
然后我记得香港大厨 我是副的

113
00:04:57,320 --> 00:04:58,920
他把那饭给我拽回来了

114
00:04:58,920 --> 00:05:02,960
带点啰嗦 这不行 给我拽回来了

115
00:05:02,960 --> 00:05:04,800
从那之后我长记性了

116
00:05:04,800 --> 00:05:06,480
记着一辈子这事儿

117
00:05:06,480 --> 00:05:08,840
香港人他不告诉你 特别难炒

118
00:05:08,840 --> 00:05:11,320
但是我们今天诠释的都非常清楚

119
00:05:11,320 --> 00:05:13,640
你照这方法一掌握就会了
```

**Comment by maaxnatasha** [comment]
认领

**Comment by maaxnatasha** [comment]
【国宴大师•黄金炒饭】松软弹香又油润，粒粒分明不粘锅！这样的黄金炒饭不来一碗吗？ |老饭骨

简介
小友们好，今天给大家带来一碗家常的黄金炒饭！
听着这个名字是不是就很诱人呢？每一粒米都吸收了蛋黄，颗颗分明、松软弹香又油润！
这次的讲解细节很到位，小友们可要仔细看视频，这道黄金炒饭做法也很简单，新手也能做！
不知道吃什么的时候就来一碗，小饭骨们，开饭咯！
Hello friends, today we will introduce “golden fried rice”! Isn't it tempting to hear that name? Every grain of rice has absorbed egg yolks, a clear, soft marble fragrance and oily! This time the details of the explanation is in place, make sure to watch the video carefully. This golden fried rice is also very simple, beginner can do it as well! It’s a good choice when you don’t know what to eat. Let’s eat!


字幕
1
00:00:00,000 --> 00:00:01,880
黄金炒饭
Golden fired rice 

2
00:00:01,880 --> 00:00:06,080
每一粒米饭 都粘满了蛋黄
Every grain of rice is covered with egg yolks


3
00:00:06,080 --> 00:00:07,920
所以它成为黄金炒饭
So we called it “Golden fried rice”

4
00:00:07,920 --> 00:00:11,800

5
00:00:11,800 --> 00:00:14,560
头天的剩米饭 一般炒饭都是剩米饭
We often used leftover rice

6
00:00:14,560 --> 00:00:16,960
润润锅 家里边有不粘锅的
Add some oil to prevent stick pans

7
00:00:16,960 --> 00:00:18,680
咱就不用聊了 怎么都不粘
Use non-stick fry pan for the best


8
00:00:18,680 --> 00:00:22,120
怎么润呢 我的工作经验告诉我
From my work experiences 

9
00:00:22,120 --> 00:00:24,160
一定要把油加进去
Add some oil first

10
00:00:24,160 --> 00:00:26,440
然后慢慢的让它加热
Then heat it up slowly

11
00:00:26,440 --> 00:00:29,880
怎么也得到六成以上 关火多焖一会儿
heat it for at least 60 percent 

12
00:00:29,880 --> 00:00:33,040
这样它的油会渗进去一些
In order to let oil seeps in 


13
00:00:33,040 --> 00:00:36,160
在热的时候表面它就不粘了
When the pan is hot, it will not stick 

14
00:00:36,160 --> 00:00:38,160
热的时候它是往上顶气
Steam will rise while the pan is hot

15
00:00:38,160 --> 00:00:42,640
准备点什么料呢 我看准备了蛋黄了
What did you prepare for ingredients? I have prepared egg yolks.

16
00:00:42,640 --> 00:00:45,920
炒米饭黄金色是由蛋黄来完成的
Fired rice’s golden comes from the egg yolks

17
00:00:45,920 --> 00:00:47,720
那么米饭来讲
For rice

18
00:00:47,720 --> 00:00:50,840
新米饭和隔夜饭
Freshly cooked rice or leftover rice

19
00:00:50,840 --> 00:00:52,640
都没有什么太大的问题
Are both okay 

20
00:00:52,640 --> 00:00:56,200
那么主要是米饭焖完之后
After the rice is finished 

21
00:00:56,200 --> 00:00:59,160
表面它不能开花
Make sure it doesn’t break down 

22
00:00:59,160 --> 00:01:02,080
开花炒完之后 表面它就
If it’s broken

23
00:01:02,080 --> 00:01:04,360
达不到那种光洁度了 就很散
It will not be smooth as a whole grain of rice


24
00:01:04,360 --> 00:01:06,320
再有一定要检查
Next double check 

25
00:01:06,320 --> 00:01:08,240
米好坏的程度是哪里
The extend of the rice’s quality 


26
00:01:08,240 --> 00:01:09,880
蒸熟之后淀粉它会糊化 
When steamed, the starch will paste 


27
00:01:09,880 --> 00:01:11,080
糊化之后是晶莹剔透的
If afterwards the paste is crystal clear 


28
00:01:11,080 --> 00:01:12,640
这应该是新米
That will be fresh rice

29
00:01:12,640 --> 00:01:15,840
如果蒸熟之后又散花 还不剔透
If it’s not paste and clear

30
00:01:15,840 --> 00:01:18,240
那证明是陈米 炒饭就不好炒了
That will be old rice, will be harder to cook 


31
00:01:18,240 --> 00:01:20,640
所以一炒它就会碎掉
Old rice tends to break down when you fry it


32
00:01:20,640 --> 00:01:22,840
它难以呈现是粒粒分明
So it’s hard to be grain-clear 




33
00:01:24,640 --> 00:01:25,720
锅润的差不多了
The pan is moist enough to prevent sticking pan 

34
00:01:25,720 --> 00:01:28,920
先别着急 关小火 等着它没关系
Don’t worry, turn to low heat and wait

35
00:01:28,920 --> 00:01:31,200
时间越长 它润的越透彻
Pan will be moister due to longer period


36
00:01:31,200 --> 00:01:34,080
它就更不容易粘锅
It will more likely to prevent stick-pan

37
00:01:34,080 --> 00:01:37,600
咱们这些米饭需要放三个蛋黄
We need three egg yolks for these amount of rice

38
00:01:38,880 --> 00:01:40,040
你看到没有
You see

39
00:01:40,040 --> 00:01:44,280
今天隋师傅先把鸡蛋拌到米饭里边
Mr. Sui mix the yolks with the rice first

40
00:01:44,280 --> 00:01:45,920
金黄金黄的
Golden

41
00:01:45,920 --> 00:01:48,800
米饭如果在冰箱里拿出来比较凉
If the rice is still cool after taking out from the fridge 

42
00:01:48,800 --> 00:01:50,680
凉了之后下锅
Fry it when it’s cool 

43
00:01:50,680 --> 00:01:52,200
需要很长时间才会热
Will take a long time to heat up

44
00:01:52,200 --> 00:01:53,920
我们就不如放在微波炉里边
we might as well put it in the microwave

45
00:01:53,920 --> 00:01:55,400
（提前）给它简单加热一下
Heat it up beforehand

46
00:01:55,400 --> 00:01:57,600
加热到二十来度三十来度不冰手
Around 20 to 20 degrees Celsius 

47
00:01:57,600 --> 00:01:59,440
而且它容易散
Cool rice tends to break down 

48
00:01:59,440 --> 00:02:01,720
为什么隔夜饭有的时候好炒
Why we prefer to use leftover rice

49
00:02:01,720 --> 00:02:04,640
它其实就是不容易粘锅 它容易散开
because it will not stick to the pan

50
00:02:04,640 --> 00:02:07,200
再有 特别凉的米饭放到锅里边
Moreover, cool rice 

51
00:02:07,200 --> 00:02:08,680
它特别容易扒锅
Are likely to stick to the pan

52
00:02:08,680 --> 00:02:11,040
温度的反差 温度反差太大了
Due to the extreme difference in temperature 

53
00:02:11,040 --> 00:02:12,880
拌匀了就行了
Mix it thoroughly 

54
00:02:12,880 --> 00:02:16,120
咱们这个锅润透了
The pan is moist enough 

55
00:02:16,120 --> 00:02:19,280

56
00:02:19,280 --> 00:02:22,160
开火 炒米饭的锅一定要干净
Turn on fire and make sure the pan is clean 

57
00:02:22,160 --> 00:02:25,120
看它有没有黑渣子 很干净
Look, it’s not black, means it’s clean

58
00:02:25,120 --> 00:02:26,480
这就证明炒饭没问题
So it’s good for frying

59
00:02:26,480 --> 00:02:29,480
它不会影响咱们出菜的整体的颜色
Since it will not contaminate the rice

60
00:02:29,480 --> 00:02:33,240
放点葱油 增加炒饭的香气
Add some onion oil to add some aroma

61
00:02:33,240 --> 00:02:35,560
葱 要想让它炸出香味
To fry the onion for aroma

62
00:02:35,560 --> 00:02:36,600
就得变成金黄色
It should turn gold

63
00:02:36,600 --> 00:02:38,360
金黄色容易出黑渣
But it will be blackish when it’s gold

64
00:02:38,360 --> 00:02:41,840
所以咱们就食其味不见其物
So we just eat it instead of seeing it

65
00:02:41,840 --> 00:02:43,560
温油 三成热
Heat the oil around 30 percent 

66
00:02:43,560 --> 00:02:45,760
下锅之后 不着急扒拉它
Don’t fry it immediately 

67
00:02:45,760 --> 00:02:48,920
慢慢的 下面凝固了 再扒拉一下
Fry it when it’s solidified underneath

68
00:02:48,920 --> 00:02:51,280
完了再凝固上面的
Then fry it to make the rice above to solidified 

69
00:02:51,280 --> 00:02:54,040
您快速炒 有可能这个蛋就脱掉了
It you fry it too quickly, the egg will separate from the rice

70
00:02:54,040 --> 00:02:57,400
就小火不着急 慢慢让它成熟着
So just take your time and stay in low heat 

71
00:02:57,400 --> 00:03:00,360
米饭粒越整越晶莹剔透
The longer it takes the clearer the rice

72
00:03:00,360 --> 00:03:02,760
这黄颜色越好看
And the goldish the color

73
00:03:02,760 --> 00:03:05,600
然后旁边锅热了 咱们炒蛋白
Another pan has heated up, let’s fry the egg whites

74
00:03:05,600 --> 00:03:08,360
一是不浪费 二是增加一个颜色
Because we don’t want to waste and it will add some color to the fry rice

75
00:03:08,360 --> 00:03:10,160
不着急 凝固就行
Don’t worry, wait until it’s one piece

76
00:03:10,160 --> 00:03:14,960
然后加点盐调味
And season it with salt

77
00:03:14,960 --> 00:03:17,640
鸡蛋当中含有谷氨酸钠
Eggs contain sodium glutamate


78
00:03:17,640 --> 00:03:19,480
所以就不用再加味精了
So there’s no need to add MSG

79
00:03:19,480 --> 00:03:22,160
然后把配料加进去
Then add other ingredients

80
00:03:22,160 --> 00:03:24,640
蛋白差不多了
Egg whites are almost done

81
00:03:24,640 --> 00:03:27,760
你看这颜色 中火
Look at that color, medium heat

82
00:03:27,760 --> 00:03:31,960
黄白分明 加上胡萝卜青豆 颜色美观
Golden and white, along with the carrots and peas 

83
00:03:31,960 --> 00:03:33,560

84
00:03:38,800 --> 00:03:41,520
黄金炒饭 出锅啦
Finished! Golden fried rice

85
00:03:41,520 --> 00:03:45,320

86
00:03:45,320 --> 00:03:49,240
好香 真香 太香了
Aromatic 

87
00:03:49,240 --> 00:03:52,160
你看着啊 每粒米饭
Look, every piece of ice

88
00:03:52,160 --> 00:03:54,720
咱把蛋白往边上扒拉扒拉
Put the egg whites on top 

89
00:03:54,720 --> 00:03:58,000
都粘满了蛋黄 
Are stick with egg yolks

90
00:03:58,000 --> 00:04:00,080
所以它成为一个黄金炒饭
So it is called “Gold fried rice”

91
00:04:00,080 --> 00:04:03,840
颗粒饱满 比原来米饭粒显着大了吧
Every grain of rice is big and full

92
00:04:03,840 --> 00:04:07,160
而且松软 弹香 特别润
And its fluffy, aromatic and bouncy 

93
00:04:07,160 --> 00:04:10,760
所以米饭作为一个厨师的基本功来讲
As a fundamental  skill for chef, 

94
00:04:10,760 --> 00:04:12,480
它是挺考验人的
Rice I changeling 

95
00:04:12,480 --> 00:04:14,520
看似一盘炒饭
Fired rice seems to be easy 

96
00:04:14,520 --> 00:04:18,800
但是它体现出一个厨师的烹饪技巧
But it represents a chef’s cooking skills

97
00:04:18,800 --> 00:04:22,440
和他的基本功的呈现
And it’s fundamental works

98
00:04:22,440 --> 00:04:23,720
看起来简单
Seems easy

99
00:04:23,720 --> 00:04:26,600
实际上炒饭 作为一个厨师
Actually fired rice,

100
00:04:26,600 --> 00:04:28,040
在行业当中这块
in the industry 

101
00:04:28,040 --> 00:04:30,120
是一个最难的一件事
Is the hardest thing to cook

102
00:04:30,120 --> 00:04:32,800
你看在香港搞大赛
You see, the cooking competition in Hong Kong

103
00:04:32,800 --> 00:04:35,880
人家也不炒什么烧海参弄鲍鱼
They don’t choose to fry  sea cumbers and sea cedans

104
00:04:35,880 --> 00:04:37,680
炒饭 炒牛河
They compete in fried rice and fried NiuHe noodles

105
00:04:37,680 --> 00:04:39,520
大爷这个饭我最有记忆
I remembered Da Ye’s fried rice

106
00:04:39,520 --> 00:04:41,760
您最有发言权 我还真有发言权
I am qualified to talk here 

107
00:04:41,760 --> 00:04:45,200
我看到这个饭 就想起一件事来
Seeing this rice, I recall one event

108
00:04:45,200 --> 00:04:48,160
原来我记得在天伦王朝炒这饭的时候
When I am in Tian Lun Wang Chao frying rice

109
00:04:48,160 --> 00:04:51,720
香港人把那火弄好了 把饭搁这
Hong Kong chef set the fire and put the rice here

110
00:04:51,720 --> 00:04:53,520
然后直接到我这炒
When it’s my turn to cook 

111
00:04:53,520 --> 00:04:54,880
炒出就有啰嗦
The rice doesn’t seem to be clear

112
00:04:54,880 --> 00:04:57,320
然后我记得香港大厨 我是副的
I am the sous chef, then I remembered the chef in Hong Kong

113
00:04:57,320 --> 00:04:58,920
他把那饭给我拽回来了
Take away my fired rice

114
00:04:58,920 --> 00:05:02,960
带点啰嗦 这不行 给我拽回来了
Says it’s not clear enough 


115
00:05:02,960 --> 00:05:04,800
从那之后我长记性了
Afterwards pay attention to it

116
00:05:04,800 --> 00:05:06,480
记着一辈子这事儿
Remember this for my whole life

117
00:05:06,480 --> 00:05:08,840
香港人他不告诉你 特别难炒
Hong Kong chef didn’t tell me my mistake, and it’s hard to figure out

118
00:05:08,840 --> 00:05:11,320
但是我们今天诠释的都非常清楚
But today we introduce all the steps very clearly

119
00:05:11,320 --> 00:05:13,640
你照这方法一掌握就会了
You can get it easily when you cook along
