### ISSUE TITLE
[华农兄弟] 华农兄弟看一下兄弟收藏的陨石顺便尝一个他种得脐橙 - https://youtu.be/LOjrRUavPrQ

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1620]
https://youtu.be/LOjrRUavPrQ
<p>&#35270;&#39057;&#21457;&#24067;&#20110; November 4, 2020 at 11:30AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/LOjrRUavPrQ
#华农兄弟：看一下兄弟收藏的陨石，顺便尝一个他种得脐橙
#Huanong Brothers: We have a look at our buddy's meteorites. And also try his navel oranges.

0:00:00.000,0:00:04.157
# 大家好  聽說兄弟十幾年前就檢了好多那個隕石哦
Hi everyone! I heard that my buddy has started collecting the, the meteorites a dozen of years ago.

0:00:04.398,0:00:06.542
# 我們去看一下  這是他家的果園
Let’s take a look! This is his orchard.

0:00:07.226,0:00:08.962
# 一片一片的 都是
The whole area. They're all,

0:00:09.820,0:00:11.604
# 現在都黃啦 等下來
they’re now becoming ripe. Later!

0:00:12.103,0:00:13.372
# 不急  不急  不急
No hurry, no hurry, no hurry

0:00:15.380,0:00:17.033
# 這個就是鐵隕石呀
These are all iron meteorites.

0:00:17.287,0:00:18.000
# 鐵隕石
Iron meteorites

0:00:18.000,0:00:18.500
# 嗯
Yup

0:00:19.264,0:00:20.174
# 好重啊  這個
It’s really heavy, this one.

0:00:20.174,0:00:21.934
# 是  跟石頭一樣沒區別
Yea. It’s essentially the same as rock.

0:00:22.001,0:00:22.959
# 每個都好重
Each one is really heavy.

0:00:22.959,0:00:23.459
# 是啊 
Yup!

0:00:23.459,0:00:24.225
# 在哪裡撿的
Where did you pick them?

0:00:24.369,0:00:25.612
# 在貴州那邊啊
Somewhere in Guizhou

0:00:25.801,0:00:26.301
# 貴州
Guizhou

0:00:26.490,0:00:26.990
# 是啊
Yup

0:00:28.197,0:00:29.802
# 我們這邊好像很少哦
They seem to be rather rare here.

0:00:29.802,0:00:30.676
# 沒有  沒有
No. no.

0:00:30.676,0:00:31.176
# 沒有
No

0:00:31.227,0:00:32.604
# 嗯  根本上就沒有
Um. Not at all.

0:00:32.946,0:00:34.814
# 這個不是甚麼地方都有的
It’s not something that you can find everywhere.

0:00:35.229,0:00:36.450
# 看就石頭一樣
They look like rocks.

0:00:36.732,0:00:37.232
# 是
Yup

0:00:37.233,0:00:38.646
# 真正是是鐵
But they’re actually iron.

0:00:38.881,0:00:41.684
# 你看  這裡  跟鐵一樣的哦 生鐵一樣
Look! Here! It looks like iron, you know, like pig iron.

0:00:43.741,0:00:45.406
# 這邊  你看  被敲了一下
Here. Look! It has been knocked.

0:00:45.628,0:00:47.161
# 敲了一下有反光
It’s shiny after being knocked.

0:00:51.337,0:00:55.386
# 它這給那個風吹雨打呀  它不會跟那個鐵一樣
It was exposed to the nature. You know, so it doesn’t look like iron.

0:00:55.386,0:00:56.991
# 它就那個光面很好
It’s like, the surface is really shiny.

0:00:57.489,0:01:00.244
# 它會曝光  曝的很滑很光滑
It shines. It shines, it means it’s smooth. Really shiny.

0:01:00.466,0:01:03.185
# 你現在我放在家裡有七八年啦
It has been with me for seven or eight years now.

0:01:03.503,0:01:06.473
# 是不是(所以?)這個光面沒有 沒有沒釉面就不見啦
So it’s not shining. I mean, the shiny surface is not here any more.

0:01:06.804,0:01:11.524
# 它又  又該風吹兩打  就跟那個鐵你給風吹雨打它就會瘦(?)的
And ah… it’s exposed to the nature. If it's iron, if it’s exposed to the nature, it would be roosted.

0:01:11.677,0:01:12.383
# 它會生鏽
It would be rusted.

0:01:12.462,0:01:13.923
# 嗯  它這個就不會的
Um! But not this one.

0:01:13.923,0:01:14.423
# 這個不會
Not this one.

0:01:14.423,0:01:17.223
# 嗯  越曬越那個光面越好的這個
Um! The more it’s exposed to sunshine, the shinier it is.

0:01:17.535,0:01:18.265
# 越曬越亮
Sunshine makes it shinier.

0:01:18.404,0:01:19.589
# 是啊 越曬越亮
Exactly, sunshine makes it shinier.

0:01:21.465,0:01:23.477
# 從天上掉下來  那麼大塊
It dropped from the sky. So big.

0:01:26.335,0:01:27.053
# 很少見
It’s really rare.

0:01:27.527,0:01:28.928
# 我們這邊幾乎都看不到
We hardly see any these things here.

0:01:29.941,0:01:31.546
# 沒有 根本上沒有
No. Not at all.

0:01:31.624,0:01:32.306
# 根本上沒有
Not at all

0:01:32.457,0:01:32.957
# 是啊
Nope

0:01:35.357,0:01:35.926
# 很漂亮
It’s really pretty.

0:01:35.926,0:01:39.340
# 本身我就收藏  我自己收藏很多石頭
In fact I collect, I collect a lot of these kind of rocks myself.

0:01:39.654,0:01:40.636
# 你  你收藏啊
You, you mean you collect them?

0:01:40.636,0:01:41.136
# 是啊
Yup

0:01:41.191,0:01:42.484
# 這幾個都是寶貝喲
These are your treasures.

0:01:42.539,0:01:45.413
# 嗯  是啊  家裡收藏的都是的  那玉石啊
Um! Yea! And so are my collections at home. The jades, for example

0:01:45.857,0:01:46.563
# 還有那個
And also the, you know

0:01:46.822,0:01:50.535
# 雞血玉呀  都很多  家裡都收藏的很多
the red jadeite, a lot! I have a lot of collections at home.

0:01:51.140,0:01:52.158
# 收藏愛好者
You’re a collector.

0:01:52.740,0:01:54.393
# 你就自己在上這樣檢啊
So you just pick them my yourselves?

0:01:54.394,0:01:54.894
# 嗯
Um!

0:01:56.389,0:01:56.963
# 多不多
You have a lot?

0:01:57.222,0:01:59.941
# 沒有  多的話就不值錢啦
No! They wouldn’t be worth anything if there are a lot.

0:02:02.347,0:02:03.496
# 這個不是那
It’s not like…

0:02:04.150,0:02:06.473
# 可遇不可求這個東西
You can’t find it. Fate brings it to you.

0:02:06.588,0:02:07.522
# 這個是
It’s ah…

0:02:07.828,0:02:09.828
# 這個是可遇不可求的事情
You can’t find it. Fate brings it to you.

0:02:09.829,0:02:10.760
# 是啊   嗯
Yea!
Um!

0:02:11.896,0:02:13.944
# 這個是  鐵  鐵隕石
It’s, it’s iron, iron meteorite.

0:02:14.402,0:02:16.630
# 它也好重  是啊  我們看不出來
It’s really heavy. Yea. We can’t say anything about it.

0:02:17.228,0:02:18.485
# 要專家才看得出來
Only an expert can.

0:02:24.685,0:02:26.685
# 快點把它收好來  這個是寶貝來的
Alright! Keep them well. These are your treasures.

0:02:27.773,0:02:29.174
# 來看一下你家的臍橙
Let’s have a look at your navel oranges.

0:02:29.503,0:02:30.003
# 好
Alright!

0:02:30.379,0:02:32.000
# 哇  好多哇  現在
Wa! There are a lot now.

0:02:32.098,0:02:34.613
# 是  今年臍橙大豐收啦
Yea! This year is a Bumper Yield.

0:02:34.704,0:02:35.446
# 大豐收
Bumper Yield

0:02:35.537,0:02:36.087
# 嗯   是啊  (時間太短，放在一起)
Um!
Yea!

0:02:50.742,0:02:52.922
# 你看  這個果  搞一個來吃一下
Look! This orange… Let’s have one.

0:02:56.267,0:02:58.063
# 你看  這個果  不洗都那麼乾淨
Look! This orange, is so clean. We don’t even need to wash it.

0:02:58.478,0:02:59.603
# 很漂亮的這個果
It's really pretty, this orange.

0:02:59.946,0:03:02.413
# 像這有一點點這個小疤  這個很正常
It’s like a small scar here. It’s very normal.

0:03:09.921,0:03:11.394
# 你看  這個皮好薄哇
Look! The peel is really thin.

0:03:13.935,0:03:15.372
# 很好吃的  這種臍橙
It’s really tasty, this kind of navel oranges.

0:03:15.373,0:03:16.403
# 現在剛剛熟
They’re now newly ripe.

0:03:17.416,0:03:21.237
# 應該還有帶點酸酸的  再過半個月的話就不酸啦
So it should be still a little bit sour. The sourness will all be gone in a fortnight.

0:03:21.304,0:03:21.902
# 很甜啦
They will then be really sweet.

0:03:24.001,0:03:24.587
# 嗯
Um!

0:03:25.732,0:03:26.702
# 現在都熟透啦
They’re completely ripe now.

0:03:27.871,0:03:28.541
# 很甜哦
It’s so sweet.

0:03:29.051,0:03:30.991
# 因為我摘的這個  比較黃
It’s because I’ve picked a more ripe one.

0:03:39.724,0:03:40.406
# 大浪費啦
What a waste!

0:03:50.870,0:03:52.487
# 這個樹  多的6年啦
This tree, is six years old now.

0:03:52.488,0:03:53.422
# 嗯 6年啦
Um! Six years.

0:03:53.536,0:03:54.506
# 掛100多斤果
It has more than fifty kilograms of oranges.

0:03:55.100,0:03:56.561
# 可以呀  幾百塊錢哦
Not bad. It means several hundred bucks.

0:03:58.611,0:04:00.240
# 全都是標準果  今年
All are up to standard, this year.

0:04:00.618,0:04:02.318
# 幾乎  幾乎都沒有次果
There are hardly, hardly any substandard ones.

0:04:02.318,0:04:03.455
# 是啊   全是標準果
Yup!
All are up to standard.

0:04:03.456,0:04:04.629
# 全部是標準果
All are up to standard.

0:04:05.460,0:04:08.000
# 你看  這一大片都是兄弟家的臍橙
Look! The whole area is my buddy’s navel oranges.

0:04:08.330,0:04:09.827
# 應該都有幾萬棵
There should be tens of thousands of trees.

0:04:10.577,0:04:13.655
# 大部份樹上都有好多的哦  都長了上百斤
And there are a lot of oranges on most of the trees, more than fifty kilograms.

0:04:14.597,0:04:16.465
# 這是我們村的產業
These are the product of our village.

0:04:21.528,0:04:24.247
# 這邊的稍微青有點 沒有陽光照射
The ones on this side are a bit green, cuz the sunlight can't reach them.

0:04:25.452,0:04:27.799
# 它照射的量不是很足  所以青一點
They don’t have enough sunlight. So they’re a bit green.

0:04:28.001,0:04:29.462
# 外面那裡好黃啊
The ones outside are golden yellow now.

0:04:30.001,0:04:34.852
# 哇  你看這裡  陽光照射比較足的地方就在這裡  都黃了
Wa! Look! It’s where the sunshine can reach. They’re golden yellow now.

0:04:36.387,0:04:39.729
# 你看  這裡都可以摘啦  直接可以摘  這麼黃啦  看見沒有
Look! They can be picked now, picked right away. They’re golden yellow now, see?

0:04:41.139,0:04:43.139
# 因為這裡有一點點青  有一點點青
Cuz, it’s a tiny little bit green here, a tiny little bit green.

0:04:43.140,0:04:44.637
# 這個  其實沒事的這個
It’s ah..In fact it doesn’t matter.

0:04:45.207,0:04:46.979
# 摘果的話必須要那個哦
If you wanna pick them, you need to, you know….

0:04:47.597,0:04:51.490
# 十一月十號才可以開摘  因為我們這邊
You need to wait until November tenth. Cuz here we…

0:04:51.782,0:04:54.788
# 等於說 保  額  為保護那個農戶的利益嘛
It’s like, pro, well, we need to protect the welfare of the farmers.

0:04:54.788,0:04:58.573
# 就是統一一天開園  十一月十一月十號
So we all start picking on the same day. November, November tenth.

0:04:58.892,0:05:01.479
# 才可以摘  其它時候都不能摘
Not before, not other time.

0:05:01.480,0:05:03.145
# 因為如果摘的話  像那個
Cuz if you pick, like…

0:05:03.146,0:05:06.081
# 如果這青的摘下來的話就說口感沒有那麼好的
If you pick the green ones, I mean, it won’t taste as good.

0:05:06.579,0:05:09.597
# 其實要讓它在樹上黃了  那個口感是最好的
In fact they taste the best if they’re left to become ripe on the trees.

0:05:10.131,0:05:13.413
# 這樣能保住  保護這個  贛南臍橙的口感
Then the quality of the Southern Jiangxi Navel Oranges can be pro... can be safeguarded.

0:05:14.594,0:05:18.271
# 不然 如果現在摘的話  大家的摘的話  那價格就會亂掉
Otherwise, if somebody starts picking now, if everybody starts picking now, the price might fluctuate a lot.

0:05:19.611,0:05:22.797
# 你看這個臍橙  長了個肚臍眼出來
Have a look at this navel orange! Here’s a belly button.

0:05:24.332,0:05:25.230
# 很漂亮哦
It’s so pretty.

0:05:38.640,0:05:41.455
# 你看這些果  好大啊
Have a lot at these oranges. They're so big.

0:05:43.090,0:05:46.432
# 夠大吧這個  你看它肚臍眼  所以它叫臍橙
It’s big isn’t it? Have a look at its belly button. They’s why it’s called navel orange.

0:05:47.158,0:05:51.075
# 臍橙  就是那個肚臍眼的臍  臍橙
Navel orange. Navel means belly button. So navel orange.

0:05:52.001,0:05:54.241
# 今年好多臍橙啊  都是豐收的
There are a lot of navel oranges this year. It’s a year of Bumper Yield.

0:05:55.038,0:06:01.243
# 但受疫情影響  到現在  好多  好多果園都還沒訂出去
But because of the pandemic, now, many, many orchards have hardly received any orders.

0:06:02.561,0:06:05.244
# 價格可能也會降  降  降低一點
The price may also drop, drop, drop a bit.

0:06:06.746,0:06:09.225
# 但是不影響  不影響它的銷量哦
But the sale is not, is not affected.

0:06:10.417,0:06:13.819
# 我們贛南這邊  稀土額  那個土地的微量元素啊
Here in Southern Jiangxi, the rare-earth, the minerals in the soil,

0:06:13.820,0:06:17.354
# 就是稀土含量比較高 所以種出的臍橙特別好吃
I mean it’s rich in rare-earth. That’s why the navel oranges here are exceptionally tasty.

0:06:17.927,0:06:21.125
# 所以  贛南  贛南的臍橙都是出了名的這個
So, navel oranges from Southern Jiangxi, Southern Jiangxi is really famous for,

0:06:22.468,0:06:26.708
# 好吃  那叫 叫  叫甚麼 叫微量元素嘛
being tasty. It's called, called, how is it called? It's called minerals, right?

0:06:26.709,0:06:28.493
# 就是含稀土比較高
Anyway, I mean the content of rare-earth is rather high.

0:06:29.459,0:06:33.029
# 全世界的稀土含量 占比最高的地方
It’s the highest in the world and most of the rare-earth is here.

0:06:33.030,0:06:34.383
# 就在我們贛南這一帶
It’s here, in Southern Jiangxi.

**Comment by vincenthychow** [comment]
已發佈
