### ISSUE TITLE
[老饭骨] 花生奶酪 - https://youtu.be/gX5KsCIcloc

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1631]
**视频链接**：https://youtu.be/gX5KsCIcloc

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•花生奶酪】香甜细腻，绵密醇厚，冬季暖胃热饮花生奶酪，做法也太简单了！|老饭骨

简介
小友们好，看到小友们留言说想学习一些简单的菜品做法，大爷就给大家带来一道传统国宴小甜品——花生奶酪！
这个小甜品原料和做法都很简单，只用了去皮花生米、奶、冰糖、水淀粉，按照我们的方法来，一碗香甜细腻、绵密醇厚、奶香浓郁的暖胃热饮花生奶酪几个步骤就能完成！
天气越来越冷，小友们注意保暖的同时，想看哪些养身暖胃的菜品也欢迎在评论区给我们留言！

字幕
1
00:00:00,000 --> 00:00:01,400
天气开始凉了

2
00:00:01,400 --> 00:00:03,240
咱们得弄一冬天喝的

3
00:00:03,240 --> 00:00:04,840
叫花生奶酪

4
00:00:04,840 --> 00:00:08,640
今天就是一盘花生米 还有两袋奶

5
00:00:08,640 --> 00:00:10,400
先把这花生米给它炸一下

6
00:00:10,400 --> 00:00:12,640
花生米去皮有一个小窍门

7
00:00:12,640 --> 00:00:14,080
开水烫两遍

8
00:00:14,080 --> 00:00:15,880
泡的时间不要太长

9
00:00:15,880 --> 00:00:17,720
泡得了赶快捻 特别好捻

10
00:00:17,720 --> 00:00:18,520
一泡长了

11
00:00:18,520 --> 00:00:20,960
花生米一涨再捻就不好捻了

12
00:00:20,960 --> 00:00:23,440
凉油下锅慢慢浸炸

13
00:00:23,440 --> 00:00:26,920
花米不炸它不香 必须要炸一下

14
00:00:26,920 --> 00:00:29,160
在家里边不愿吃炸的也没问题

15
00:00:29,160 --> 00:00:30,000
也可以烤一烤

16
00:00:30,000 --> 00:00:32,440
冒泡了你看啊 关小火

17
00:00:32,440 --> 00:00:34,920
开始大火因为油是凉的

18
00:00:34,920 --> 00:00:37,120
等冒泡了以后火要小一点

19
00:00:37,120 --> 00:00:38,560
攉拢的时候听听声音

20
00:00:38,560 --> 00:00:40,960
你看这声音有点发闷

21
00:00:40,960 --> 00:00:43,440
现在表面这些泡

22
00:00:43,440 --> 00:00:46,200
就是花生米当中的水分

23
00:00:46,200 --> 00:00:47,120
平时炸花生米

24
00:00:47,120 --> 00:00:49,520
最不好炸的是带皮的花生米

25
00:00:49,520 --> 00:00:52,040
你看不见颜色

26
00:00:52,040 --> 00:00:52,920
还有就是

27
00:00:52,920 --> 00:00:54,280
泡的时间稍微长一点的花生米

28
00:00:54,280 --> 00:00:57,080
在炸的时候很容易扒锅

29
00:00:57,080 --> 00:00:58,080
如果泡时间长了

30
00:00:58,080 --> 00:01:00,960
我们可以放这儿先晾一晾

31
00:01:00,960 --> 00:01:03,360
或者入烤箱弄八十度

32
00:01:03,360 --> 00:01:04,720
烤它三分钟两分钟

33
00:01:04,720 --> 00:01:06,560
脱出去水分再开始炸

34
00:01:06,560 --> 00:01:07,480
炸出来以后

35
00:01:07,480 --> 00:01:11,160
花生米的表面它不起泡 特别的酥脆

36
00:01:11,160 --> 00:01:15,920
听声啊 看这泡也少了

37
00:01:15,920 --> 00:01:20,320

38
00:01:20,320 --> 00:01:21,320
温水洗

39
00:01:21,320 --> 00:01:23,440
表面漂起了油花 给它洗掉了

40
00:01:23,440 --> 00:01:25,880

41
00:01:25,880 --> 00:01:27,320
开始粉碎

42
00:01:27,320 --> 00:01:30,120
来点纯净水

43
00:01:30,120 --> 00:01:30,920
一按

44
00:01:36,120 --> 00:01:37,680
这个渣子再搁点奶

45
00:01:37,680 --> 00:01:39,440
熬成粗渣子有口感的

46
00:01:39,440 --> 00:01:41,840
喝的时候有点像咱们那个棒子面粥

47
00:01:42,560 --> 00:01:43,960
好了 开火

48
00:01:45,360 --> 00:01:50,320
二伯 你看这浆都挂勺 很稠

49
00:01:50,320 --> 00:01:52,960
两盒奶

50
00:01:52,960 --> 00:01:55,120
冰糖大爷咱搁进去了

51
00:01:55,120 --> 00:01:57,280
搁点冰糖或者是砂糖

52
00:01:57,280 --> 00:01:59,160
稠 叫酪

53
00:01:59,160 --> 00:02:02,200
稀的像这样的 就像茶

54
00:02:02,200 --> 00:02:04,520
酪就要挂点杯子 稍微稠一点

55
00:02:04,520 --> 00:02:06,800
就是米汤芡

56
00:02:06,800 --> 00:02:09,840
早年我们国宴当中

57
00:02:09,840 --> 00:02:14,920
有很多根据宴会（人数）的多与少

58
00:02:14,920 --> 00:02:18,000
什么杏仁茶 花生奶酪

59
00:02:18,000 --> 00:02:19,040
这是多的

60
00:02:19,040 --> 00:02:22,360
小宴会上我们就拔丝苹果了 八宝饭

61
00:02:22,360 --> 00:02:24,920
像这种几百人上千人的宴会

62
00:02:24,920 --> 00:02:26,520
就得给这个了

63
00:02:26,520 --> 00:02:28,080
花生奶酪杏仁茶

64
00:02:28,080 --> 00:02:30,080
小型宴会还有什么

65
00:02:30,080 --> 00:02:32,600
像夏天的杏仁豆腐

66
00:02:32,600 --> 00:02:34,440
淀粉拢点芡

67
00:02:34,440 --> 00:02:40,320

68
00:02:40,320 --> 00:02:42,560
基本上米汤芡

69
00:02:42,560 --> 00:02:46,400
因为这叫酪 这酪好喝啊

70
00:02:46,400 --> 00:02:47,320
可以加点东西

71
00:02:47,320 --> 00:02:51,520
加点西米 西米酪 西米花生酪

72
00:02:51,520 --> 00:02:55,040
还可以搁点椰米 搁水果也行

73
00:02:55,040 --> 00:02:56,400
这就好啦

74
00:02:58,240 --> 00:03:00,600
咱们把这浮沫篦出去

75
00:03:00,600 --> 00:03:05,440
有这浮沫它不好看 也不好吃

76
00:03:06,160 --> 00:03:08,360
八成满就行了

77
00:03:08,360 --> 00:03:10,160

78
00:03:10,160 --> 00:03:11,840
现在已经好了 非常香

79
00:03:11,840 --> 00:03:15,640
花生奶酪 二伯尝尝呗

80
00:03:17,160 --> 00:03:20,080
都有奶皮子

81
00:03:20,080 --> 00:03:21,000
你说这营养价值

82
00:03:21,000 --> 00:03:23,400
和蛋白质 丰富不丰富

83
00:03:23,400 --> 00:03:26,400

84
00:03:26,400 --> 00:03:27,920
先让二伯那酝着

85
00:03:27,920 --> 00:03:29,360
来 隋坡尝尝

86
00:03:29,360 --> 00:03:32,720
二伯那体会呢 正在砸么滋味呢

87
00:03:32,720 --> 00:03:35,320
师父炸这花生火候特别合适

88
00:03:35,320 --> 00:03:38,000
出香味了 它没有糊味 很香

89
00:03:38,000 --> 00:03:40,600
还有奶香味跟花生的香味

90
00:03:40,600 --> 00:03:44,160
融合到一起入口以后 还有挂口的感觉

91
00:03:44,160 --> 00:03:46,640
香甜 口感特别好 细腻

92
00:03:46,640 --> 00:03:47,800
最关键是什么

93
00:03:47,800 --> 00:03:50,360
冬天养生的非常好的一种甜品

94
00:03:50,360 --> 00:03:51,520
对于我来说

95
00:03:51,520 --> 00:03:54,800
它不单单的是一碗酪的问题

96
00:03:54,800 --> 00:03:59,280
大爷今天给我呈现的是满满的回忆

97
00:03:59,280 --> 00:04:01,840
我参加工作二十几岁的时候

98
00:04:01,840 --> 00:04:04,040
我们曾经做这个酪

99
00:04:04,040 --> 00:04:05,400
今天大爷再现

100
00:04:05,400 --> 00:04:06,840
不但是传承

101
00:04:06,840 --> 00:04:09,400
而且是我们对生活的一种回忆

102
00:04:09,400 --> 00:04:12,160
和我们对后人传承的一种态度

103
00:04:12,160 --> 00:04:14,400
这就是大爷的精神所在

104
00:04:14,960 --> 00:04:15,920
谢谢二伯
```

**Comment by Losskywalker** [comment]
认领

**Comment by Losskywalker** [comment]
bot, please upload
----------------------------------
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•花生奶酪】香甜细腻，绵密醇厚，冬季暖胃热饮花生奶酪，做法也太简单了！|老饭骨
Title: [State Banquet Master Chef] Peanut milk pudding: fragrant, sweet, thick, and smooth. Perfect warm dessert for the cold winter that is so simple to make. |LaoFanGu|

简介
小友们好，看到小友们留言说想学习一些简单的菜品做法，大爷就给大家带来一道传统国宴小甜品——花生奶酪！
这个小甜品原料和做法都很简单，只用了去皮花生米、奶、冰糖、水淀粉，按照我们的方法来，一碗香甜细腻、绵密醇厚、奶香浓郁的暖胃热饮花生奶酪几个步骤就能完成！
天气越来越冷，小友们注意保暖的同时，想看哪些养身暖胃的菜品也欢迎在评论区给我们留言！
Introduction
Dear fans. We have seen your comments that you want to learn some simple dishes. Today, Da Ye will teach you how to make a traditional dessert dish good enough even for the State Banquet. The Peanut milk pudding.
Its simple ingredients only include peanut, milk, crystal sugar and starch. Follow our instructions to make this delicious, sweet , smooth and milky warm dessert in just a few steps.
Winter is coming, everyone please stay warm and let us know about what else do you want to learn in the comments section.

字幕
1
00:00:00,000 --> 00:00:01,400
天气开始凉了
It’s getting cold these days

2
00:00:01,400 --> 00:00:03,240
咱们得弄一冬天喝的
Let’s make something perfect for the winter season

3
00:00:03,240 --> 00:00:04,840
叫花生奶酪
It’s called Peanut Milk Pudding

4
00:00:04,840 --> 00:00:08,640
今天就是一盘花生米 还有两袋奶
We only need some peanuts, two bags of milk

5
00:00:08,640 --> 00:00:10,400
先把这花生米给它炸一下
First let’s fry the peanuts

6
00:00:10,400 --> 00:00:12,640
花生米去皮有一个小窍门
There is a little tip in removing the skin

7
00:00:12,640 --> 00:00:14,080
开水烫两遍
Soak it twice in hot water

8
00:00:14,080 --> 00:00:15,880
泡的时间不要太长
Not for too long

9
00:00:15,880 --> 00:00:17,720
泡得了赶快捻 特别好捻
Quickly soak them in hot water and then clean them immediate

10
00:00:17,720 --> 00:00:18,520
一泡长了
If you soak them for two long

11
00:00:18,520 --> 00:00:20,960
花生米一涨再捻就不好捻了
The peanut will absorb too much water and expand, making it too difficult

12
00:00:20,960 --> 00:00:23,440
凉油下锅慢慢浸炸
Peanuts in, while the oil is still cold

13
00:00:23,440 --> 00:00:26,920
花米不炸它不香 必须要炸一下
You must fry the peanuts to get the maximum aroma

14
00:00:26,920 --> 00:00:29,160
在家里边不愿吃炸的也没问题
If you are cooking a home and you want to avoid frying

15
00:00:29,160 --> 00:00:30,000
也可以烤一烤
You can also roast it

16
00:00:30,000 --> 00:00:32,440
冒泡了你看啊 关小火
See the little bubbles? Now let’s lower the heat

17
00:00:32,440 --> 00:00:34,920
开始大火因为油是凉的
We start with high heat to warm up the oil quickly

18
00:00:34,920 --> 00:00:37,120
等冒泡了以后火要小一点
Once the bubbles come out, we need to lower the heat

19
00:00:37,120 --> 00:00:38,560
攉拢的时候听听声音
Listen while you stir it

20
00:00:38,560 --> 00:00:40,960
你看这声音有点发闷
It sounds a bit muffled

21
00:00:40,960 --> 00:00:43,440
现在表面这些泡
These bubbles that are coming out

22
00:00:43,440 --> 00:00:46,200
就是花生米当中的水分
They are moisture in the peanuts

23
00:00:46,200 --> 00:00:47,120
平时炸花生米
When you fry peanuts

24
00:00:47,120 --> 00:00:49,520
最不好炸的是带皮的花生米
It’s more difficult when the skins are still intact

25
00:00:49,520 --> 00:00:52,040
你看不见颜色
Because you cannot see the color change

26
00:00:52,040 --> 00:00:52,920
还有就是
Also

27
00:00:52,920 --> 00:00:54,280
泡的时间稍微长一点的花生米
Those that have been soaked for too long

28
00:00:54,280 --> 00:00:57,080
在炸的时候很容易扒锅
They will stick to the pan 

29
00:00:57,080 --> 00:00:58,080
如果泡时间长了
If you soak them for too long

30
00:00:58,080 --> 00:01:00,960
我们可以放这儿先晾一晾
You can first leave them drying for a while 

31
00:01:00,960 --> 00:01:03,360
或者入烤箱弄八十度
Ow roast them in a 80 degree oven

32
00:01:03,360 --> 00:01:04,720
烤它三分钟两分钟
For about 2-3 minutes

33
00:01:04,720 --> 00:01:06,560
脱出去水分再开始炸
Remove the moisture and then start frying

34
00:01:06,560 --> 00:01:07,480
炸出来以后
When done properly

35
00:01:07,480 --> 00:01:11,160
花生米的表面它不起泡 特别的酥脆
The surface of the peanuts are still smooth, and they are extremely crisyp

36
00:01:11,160 --> 00:01:15,920
听声啊 看这泡也少了
Listen to that, there are less bubbles now

37
00:01:15,920 --> 00:01:20,320

38
00:01:20,320 --> 00:01:21,320
温水洗
Wash them with warm water

39
00:01:21,320 --> 00:01:23,440
表面漂起了油花 给它洗掉了
To get rid of the excess oil

40
00:01:23,440 --> 00:01:25,880

41
00:01:25,880 --> 00:01:27,320
开始粉碎
Now we can grind them 

42
00:01:27,320 --> 00:01:30,120
来点纯净水
Some clean water

43
00:01:30,120 --> 00:01:30,920
一按
Here we go

44
00:01:36,120 --> 00:01:37,680
这个渣子再搁点奶
We can pour some milk to these residues 

45
00:01:37,680 --> 00:01:39,440
熬成粗渣子有口感的
And cook them into a little bit of a rough texture

46
00:01:39,440 --> 00:01:41,840
喝的时候有点像咱们那个棒子面粥
A bit like the corn flake porridge

47
00:01:42,560 --> 00:01:43,960
好了 开火
OK bring the heat on

48
00:01:45,360 --> 00:01:50,320
二伯 你看这浆都挂勺 很稠	
Look how thick this is, Er Bai, it’s sticking to the spoon

49
00:01:50,320 --> 00:01:52,960
两盒奶
Two  bottles of milk

50
00:01:52,960 --> 00:01:55,120
冰糖大爷咱搁进去了
Let me put the crystal sugar in 

51
00:01:55,120 --> 00:01:57,280
搁点冰糖或者是砂糖
Both crystal sugar or powdered sugar are fine

52
00:01:57,280 --> 00:01:59,160
稠 叫酪
This dish is supposed to be thick

53
00:01:59,160 --> 00:02:02,200
稀的像这样的 就像茶
Otherwise it’s more like tea, not pudding

54
00:02:02,200 --> 00:02:04,520
酪就要挂点杯子 稍微稠一点
It has to be a bit sticky, a bit thick

55
00:02:04,520 --> 00:02:06,800
就是米汤芡
Like a thick porridge

56
00:02:06,800 --> 00:02:09,840
早年我们国宴当中
Back in the days when we were preparing the State Banquet

57
00:02:09,840 --> 00:02:14,920
有很多根据宴会（人数）的多与少
Depending on the number of participants

58
00:02:14,920 --> 00:02:18,000
什么杏仁茶 花生奶酪
We would make Almond tea, or this milk pudding

59
00:02:18,000 --> 00:02:19,040
这是多的
For a large group

60
00:02:19,040 --> 00:02:22,360
小宴会上我们就拔丝苹果了 八宝饭
For a small group we would make toffee apple, or Ba Bao Rice

61
00:02:22,360 --> 00:02:24,920
像这种几百人上千人的宴会
For large groups with hundreds of people

62
00:02:24,920 --> 00:02:26,520
就得给这个了
We need this

63
00:02:26,520 --> 00:02:28,080
花生奶酪杏仁茶
Thinks like this or the apricot kernel tea

64
00:02:28,080 --> 00:02:30,080
小型宴会还有什么
For a small banquet

65
00:02:30,080 --> 00:02:32,600
像夏天的杏仁豆腐
We also make apricot kernel jelly for the summer

66
00:02:32,600 --> 00:02:34,440
淀粉拢点芡
We need some slurry in there

67
00:02:34,440 --> 00:02:40,320

68
00:02:40,320 --> 00:02:42,560
基本上米汤芡
A thin slurry

69
00:02:42,560 --> 00:02:46,400
因为这叫酪 这酪好喝啊
This is called “LAO” 

70
00:02:46,400 --> 00:02:47,320
可以加点东西
You can add some other ingredients in here

71
00:02:47,320 --> 00:02:51,520
加点西米 西米酪 西米花生酪
Like sago

72
00:02:51,520 --> 00:02:55,040
还可以搁点椰米 搁水果也行
Or coconut, or fruits

73
00:02:55,040 --> 00:02:56,400
这就好啦
That’s done

74
00:02:58,240 --> 00:03:00,600
咱们把这浮沫篦出去
Let’s use the sieve to make it clean

75
00:03:00,600 --> 00:03:05,440
有这浮沫它不好看 也不好吃
It will look better, and taste better

76
00:03:06,160 --> 00:03:08,360
八成满就行了
Fill it up to 80%

77
00:03:08,360 --> 00:03:10,160

78
00:03:10,160 --> 00:03:11,840
现在已经好了 非常香
Smells so good

79
00:03:11,840 --> 00:03:15,640
花生奶酪 二伯尝尝呗
Here we have it! Peanut Milk Pudding. Have a taste Er Bai!

80
00:03:17,160 --> 00:03:20,080
都有奶皮子
The milk forms a skin on the surface

81
00:03:20,080 --> 00:03:21,000
你说这营养价值
Must be very nutritious 

82
00:03:21,000 --> 00:03:23,400
和蛋白质 丰富不丰富
Rich in protein

83
00:03:23,400 --> 00:03:26,400

84
00:03:26,400 --> 00:03:27,920
先让二伯那酝着
Er Bai will have a taste

85
00:03:27,920 --> 00:03:29,360
来 隋坡尝尝
Here, Sui Po, have a taste too.

86
00:03:29,360 --> 00:03:32,720
二伯那体会呢 正在砸么滋味呢
Er Bai is enjoying it 

87
00:03:32,720 --> 00:03:35,320
师父炸这花生火候特别合适
This peanut is fried to perfection

88
00:03:35,320 --> 00:03:38,000
出香味了 它没有糊味 很香
Aromatic, but not burnt

89
00:03:38,000 --> 00:03:40,600
还有奶香味跟花生的香味
Combined with the flavor of the milk

90
00:03:40,600 --> 00:03:44,160
融合到一起入口以后 还有挂口的感觉
All combined together in your mouth, and it is slightly sticky

91
00:03:44,160 --> 00:03:46,640
香甜 口感特别好 细腻
Sweet, smooth

92
00:03:46,640 --> 00:03:47,800
最关键是什么
More importantly 

93
00:03:47,800 --> 00:03:50,360
冬天养生的非常好的一种甜品
This is perfect for the winter season

94
00:03:50,360 --> 00:03:51,520
对于我来说
For me

95
00:03:51,520 --> 00:03:54,800
它不单单的是一碗酪的问题
This is more than a bowl of pudding

96
00:03:54,800 --> 00:03:59,280
大爷今天给我呈现的是满满的回忆
This is full of memories

97
00:03:59,280 --> 00:04:01,840
我参加工作二十几岁的时候	
When I started working at around 20 years old

98
00:04:01,840 --> 00:04:04,040
我们曾经做这个酪
We used to make this together

99
00:04:04,040 --> 00:04:05,400
今天大爷再现
Seeing this again 

100
00:04:05,400 --> 00:04:06,840
不但是传承
It’s not only about sharing and learning

101
00:04:06,840 --> 00:04:09,400
而且是我们对生活的一种回忆
But also brings back good memories

102
00:04:09,400 --> 00:04:12,160
和我们对后人传承的一种态度
And our respect to the older generation

103
00:04:12,160 --> 00:04:14,400
这就是大爷的精神所在
That’s the spirit of Da Ye

104
00:04:14,960 --> 00:04:15,920
谢谢二伯
Thank you Er Bai
