### ISSUE TITLE
[老饭骨] 玉簪鸡翼球 - https://youtu.be/38YCGhR42BU

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1633]
**视频链接**：https://youtu.be/38YCGhR42BU

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•玉簪鸡翼球】香、辣、嫩、酥，糊辣味十足！国宴大师教你改良粤菜，解锁鸡翼新吃法！ |老饭骨

简介
小友们大家好，今天大爷给大家带来一道小炒菜品——玉簪鸡翼球！
玉簪鸡翼球的造型很别致，鸡翼中插入青椒和胡萝卜，一红一绿，活像一根玉簪子！
这道菜原本是粤菜的一道老菜，大爷在味型上进行了改良，做成了宫保味儿，香辣酥麻、更加突出鸡翼的肉质细嫩。炒的时候满屋子的人都得在打喷嚏，不然炒得不合格！ 😁
大家还记得老饭骨做过哪些鸡肉的菜品呢？评论区一起回忆一下，还想解锁更多鸡肉的做法，记得要关注老饭骨频道哦！

字幕
1
00:00:00,000 --> 00:00:02,520
炒出来这菜您不打嚏喷我就失败了

2
00:00:02,520 --> 00:00:04,560

3
00:00:04,560 --> 00:00:07,240
烹醋 老的宫保鸡丁的味道

4
00:00:07,240 --> 00:00:10,640
这是粤菜的一道老菜 味型改了

5
00:00:10,640 --> 00:00:12,320

6
00:00:12,320 --> 00:00:15,240

7
00:00:15,240 --> 00:00:19,160
鸡翅 这个不能扔啊 做个辣子鸡

8
00:00:19,160 --> 00:00:20,400

9
00:00:20,400 --> 00:00:23,960
一拍 这两根骨头全断了

10
00:00:23,960 --> 00:00:29,160
看着啊 一压 一个一个的来

11
00:00:29,160 --> 00:00:33,560

12
00:00:33,560 --> 00:00:36,080
先把这留着 然后再去那块

13
00:00:36,080 --> 00:00:37,480
能拿住它

14
00:00:37,480 --> 00:00:39,720
大爷 那个真别糟蹋

15
00:00:39,720 --> 00:00:43,120
绝对糟蹋不了 那个单做出一菜来

16
00:00:43,120 --> 00:00:46,320
做一蒸的吧  蒸的好 豆豉蒸

17
00:00:46,320 --> 00:00:49,280
这徒弟脑瓜灵啊 师父一直在念叨呢

18
00:00:49,280 --> 00:00:50,800
隋坡不来我恨死他了

19
00:00:50,800 --> 00:00:52,160
为什么老不来啊

20
00:00:52,160 --> 00:00:57,320
花为媒 似的 你怎么还不来呀

21
00:00:57,320 --> 00:00:59,240
全算上刚十五分钟

22
00:00:59,240 --> 00:01:01,480
这就完事了 正合适

23
00:01:01,480 --> 00:01:05,480
青椒 长短要比刚才剔出去的骨头

24
00:01:05,480 --> 00:01:10,480
要稍微长一点 来个鸡蛋

25
00:01:10,480 --> 00:01:13,040
你这一招一式还挺利落

26
00:01:13,040 --> 00:01:15,120
照这样你能干到九十岁都没问题

27
00:01:15,120 --> 00:01:17,800
九十岁之前不会歇厨了

28
00:01:17,800 --> 00:01:20,400
二伯 咱俩得永远在一起

29
00:01:20,400 --> 00:01:21,280
实在干不了了

30
00:01:21,280 --> 00:01:22,960
您剥葱剥蒜也得在这儿干

31
00:01:22,960 --> 00:01:24,120

32
00:01:24,120 --> 00:01:27,320
上浆特别快 鸡蛋

33
00:01:27,320 --> 00:01:29,080
因为咱们炒的是红汁菜

34
00:01:29,080 --> 00:01:30,320
就用全鸡蛋

35
00:01:30,320 --> 00:01:31,880
必须要用蛋黄 因为它香

36
00:01:31,880 --> 00:01:34,520
淀粉 大约十五克

37
00:01:34,520 --> 00:01:37,480
盐 三克 特别快啊

38
00:01:37,480 --> 00:01:42,760
鸡蛋蛋清 先把糊和好 攉拢匀了

39
00:01:42,760 --> 00:01:44,200
再给我来一点淀粉

40
00:01:44,200 --> 00:01:46,200
半勺 好好

41
00:01:46,200 --> 00:01:48,600
这些淀粉用不完

42
00:01:48,600 --> 00:01:51,200
一会咱们再这点淀粉干别的用

43
00:01:51,200 --> 00:01:54,040
好 拿走 十秒钟就完事了

44
00:01:54,040 --> 00:01:58,400
这盐搁好了 鸡蛋淀粉 叫搅拌上劲

45
00:01:59,360 --> 00:02:01,840
OK了 有劲了

46
00:02:01,840 --> 00:02:05,040
二伯回手给来点油

47
00:02:06,960 --> 00:02:09,320
封油 好嘞

48
00:02:09,320 --> 00:02:11,240

49
00:02:11,240 --> 00:02:14,040
看着啊 现在开始串

50
00:02:14,040 --> 00:02:15,920
为什么叫玉簪鸡翼球

51
00:02:15,920 --> 00:02:18,480
就跟簪子似的 你看见没有

52
00:02:18,480 --> 00:02:19,720
为什么要用这两个颜色

53
00:02:19,720 --> 00:02:21,960
一红一绿 它漂亮

54
00:02:21,960 --> 00:02:25,880
像不像簪子 再拿牙签咱串它一下

55
00:02:25,880 --> 00:02:28,400
它掉不了 巧就巧在这儿了

56
00:02:28,400 --> 00:02:30,720
一成熟鸡肉就收缩了

57
00:02:30,720 --> 00:02:32,400
这个可以炒

58
00:02:32,400 --> 00:02:36,000
如果我们串点萝卜或者藕条

59
00:02:36,000 --> 00:02:39,280
可以给它出下水 就变成白的了

60
00:02:39,280 --> 00:02:41,160
白汁的可以清炖

61
00:02:41,160 --> 00:02:45,480
国宴过去讲 吃完冷菜上两个小炒

62
00:02:45,480 --> 00:02:47,720
这两个小炒是什么菜呢

63
00:02:47,720 --> 00:02:49,920
是要喝酒的菜

64
00:02:49,920 --> 00:02:53,200
上完小炒以后才上大菜

65
00:02:53,200 --> 00:02:54,800
过去的菜单就这么安排的

66
00:02:54,800 --> 00:02:56,200
比如说上完七个冷菜

67
00:02:56,200 --> 00:02:57,680
跟着上俩小炒

68
00:02:57,680 --> 00:03:00,680
什么干煸牛肉丝 什么炒银芽

69
00:03:00,680 --> 00:03:02,240
那会儿过瘾啊大爷

70
00:03:02,240 --> 00:03:03,080
隋坡看见没有

71
00:03:03,080 --> 00:03:06,520
切东西做东西做事儿要稳妥

72
00:03:06,520 --> 00:03:10,080
稳妥在哪呢 有数

73
00:03:10,080 --> 00:03:11,680
干活要有数

74
00:03:11,680 --> 00:03:15,640
看着啊 就剩了两根 这就不算剩

75
00:03:15,640 --> 00:03:19,760
好 洗手 心里有谱 有谱

76
00:03:19,760 --> 00:03:21,400

77
00:03:21,400 --> 00:03:24,640
这下该下一小节目了啊

78
00:03:24,640 --> 00:03:27,040
咱们兑个碗汁

79
00:03:27,040 --> 00:03:30,040
酱油 米醋

80
00:03:30,040 --> 00:03:32,200
米醋一会还得烹点

81
00:03:32,200 --> 00:03:36,880
黄酒 盐 糖

82
00:03:36,880 --> 00:03:38,480
我这个叫碗汁不叫碗芡

83
00:03:38,480 --> 00:03:39,920
因为这里面没有淀粉

84
00:03:39,920 --> 00:03:41,800
要有淀粉叫碗芡

85
00:03:41,800 --> 00:03:44,240
葱姜蒜小料 这就算齐活了

86
00:03:44,240 --> 00:03:46,280

87
00:03:46,280 --> 00:03:48,080
辣椒 还得洗一洗

88
00:03:48,080 --> 00:03:49,560
把辣椒籽要洗出去

89
00:03:49,560 --> 00:03:52,480
锅烧好了 二伯给倒点油

90
00:03:53,960 --> 00:03:56,480
看啊 这花生米炸好了

91
00:03:56,480 --> 00:03:58,960
给它搞成花生碎

92
00:03:58,960 --> 00:04:01,520
花生碎也好了 油温也高了

93
00:04:01,520 --> 00:04:04,880
现在已经五成热了

94
00:04:04,880 --> 00:04:06,720

95
00:04:06,720 --> 00:04:07,920
下锅

96
00:04:07,920 --> 00:04:12,880

97
00:04:12,880 --> 00:04:16,880
不要乱动它 为什么不让动啊

98
00:04:16,880 --> 00:04:18,920
一定要给鸡肉在油中

99
00:04:18,920 --> 00:04:22,200
表面淀粉糊化成熟的一个时间

100
00:04:22,200 --> 00:04:24,160
否则会粘的满锅都是

101
00:04:24,160 --> 00:04:27,080
这多漂亮 一个都没掉

102
00:04:27,080 --> 00:04:29,800
出锅 收缩就可以倒进去了

103
00:04:29,800 --> 00:04:33,120
花椒 这花椒有的师傅炒

104
00:04:33,120 --> 00:04:36,320
就搁在里边了 但吃起来很不舒服

105
00:04:36,320 --> 00:04:38,200
还要把它捞干净

106
00:04:38,200 --> 00:04:39,880

107
00:04:39,880 --> 00:04:42,640
你看我们这时候油温就很热

108
00:04:42,640 --> 00:04:45,360
我为什么把辣椒给洗一下

109
00:04:45,360 --> 00:04:47,040
这样的也会降低油温

110
00:04:47,040 --> 00:04:49,400

111
00:04:50,440 --> 00:04:52,080
它不会马上糊

112
00:04:52,080 --> 00:04:54,400
到现在都没糊

113
00:04:54,400 --> 00:04:57,480
要不是拿水洗了 一下就糊了 完了

114
00:04:57,480 --> 00:04:58,840

115
00:04:58,840 --> 00:05:00,120
葱姜

116
00:05:00,120 --> 00:05:02,760
糊辣味型的小料标配是葱姜蒜

117
00:05:02,760 --> 00:05:05,080
对 小料的料头要狠

118
00:05:06,080 --> 00:05:08,960
二伯 倒进来

119
00:05:08,960 --> 00:05:11,680
这个时候我们要搁点辣椒面

120
00:05:11,680 --> 00:05:13,680
辣椒面下去以后炒香

121
00:05:13,680 --> 00:05:15,480
碗汁儿

122
00:05:15,480 --> 00:05:17,880

123
00:05:17,880 --> 00:05:19,880
颜色很漂亮

124
00:05:19,880 --> 00:05:21,680
因为这个汁要是炒鸡丁

125
00:05:21,680 --> 00:05:23,440
这汁儿就多了 有一半就够了

126
00:05:23,440 --> 00:05:27,000
勾芡  因为这个鸡球比较大

127
00:05:27,000 --> 00:05:28,920
所以这个汁儿稍微大一点

128
00:05:28,920 --> 00:05:30,840

129
00:05:30,840 --> 00:05:31,640
好了

130
00:05:31,640 --> 00:05:34,320
烹醋 提香

131
00:05:34,320 --> 00:05:37,160

132
00:05:37,160 --> 00:05:38,120
花生碎

133
00:05:38,120 --> 00:05:41,480

134
00:05:41,480 --> 00:05:44,520
您得打嚏喷或者打一咳嗽

135
00:05:44,520 --> 00:05:48,920

136
00:05:51,080 --> 00:05:53,560
炒出来这菜您不打嚏喷我就失败了

137
00:05:55,880 --> 00:05:57,920
你好长时间没来了

138
00:05:57,920 --> 00:05:58,960

139
00:06:00,920 --> 00:06:01,840
谢谢师叔

140
00:06:02,000 --> 00:06:04,520
照大爷 好吃啊这个

141
00:06:04,520 --> 00:06:08,480
糊辣味十足 超级嫩

142
00:06:08,480 --> 00:06:12,360
特别嫩 太香了

143
00:06:12,360 --> 00:06:13,720
改良之后有老的味道

144
00:06:13,720 --> 00:06:16,160
吃出老的宫保鸡丁的味道的时候

145
00:06:16,160 --> 00:06:18,440
还有蔬菜那种清香味

146
00:06:18,440 --> 00:06:20,520
花生米粘在上面

147
00:06:20,520 --> 00:06:21,920
那种花生米的酥香味

148
00:06:21,920 --> 00:06:24,640
这个菜巧妙的融为一体

149
00:06:24,640 --> 00:06:28,280
人说做中国菜境界什么 就是融合

150
00:06:28,280 --> 00:06:29,160
它把各种味道

151
00:06:29,160 --> 00:06:31,600
融合到一个最高的境界

152
00:06:31,600 --> 00:06:33,880
点个赞 谢谢二伯

153
00:06:33,880 --> 00:06:44,760

154
00:06:44,760 --> 00:06:45,920
给我们哥俩来一个

155
00:06:45,920 --> 00:06:50,440

156
00:06:50,440 --> 00:06:53,440
不过来就失去照相机会了
```

**Comment by Yingzhang1122** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•玉簪鸡翼球】香、辣、嫩、酥，糊辣味十足！国宴大师教你改良粤菜，解锁鸡翼新吃法！ |老饭骨
State Banquet Master Chef: Yu Zan Ji Yi Qiu (Jade hairpin chicken wing)

简介
小友们大家好，今天大爷给大家带来一道小炒菜品——玉簪鸡翼球！
玉簪鸡翼球的造型很别致，鸡翼中插入青椒和胡萝卜，一红一绿，活像一根玉簪子！
这道菜原本是粤菜的一道老菜，大爷在味型上进行了改良，做成了宫保味儿，香辣酥麻、更加突出鸡翼的肉质细嫩。炒的时候满屋子的人都得在打喷嚏，不然炒得不合格！ 😁
大家还记得老饭骨做过哪些鸡肉的菜品呢？评论区一起回忆一下，还想解锁更多鸡肉的做法，记得要关注老饭骨频道哦！
Hello friends! Today Da Ye will show you a stir-fried dish: Yu Zan Ji Yi Qiu (Jade hairpin chicken wing)!
The shape of the chicken wing is very special. With green chili and carrot inserted into the chicken wing section, it looks just like a jade hairpin!
It was originally a traditional Cantonese dish. Da Ye has modified the flavor of this dish - he cooks it in the 'Kung Pao' flavor: aromatic, spicy, crispy, numbing, with the extra presentation of the tenderness of the chicken wing. Everyone was sneezing during cooking; otherwise this dish would be a failure!
Do you remember other ways of cooking chicken from our channel? Recall them in the comments, and please subscribe if you want to unlock more chicken recipes!

字幕
1
00:00:00,000 --> 00:00:02,520
#炒出来这菜您不打嚏喷我就失败了
It would be a failure if you don't sneeze when I am cooking

2
00:00:02,520 --> 00:00:04,560

3
00:00:04,560 --> 00:00:07,240
#烹醋 老的宫保鸡丁的味道
Add vinegar. The old flavor of Kung Pao Chicken

4
00:00:07,240 --> 00:00:10,640
#这是粤菜的一道老菜 味型改了
This is a traditional Cantonese dish. I adjusted its flavor

5
00:00:10,640 --> 00:00:12,320

6
00:00:12,320 --> 00:00:15,240

7
00:00:15,240 --> 00:00:19,160
#鸡翅 这个不能扔啊 做个辣子鸡
-Chicken wing. -Don't throw this away, we can still cook 'La Zi Ji' (spicy chicken) out of it!

8
00:00:19,160 --> 00:00:20,400

9
00:00:20,400 --> 00:00:23,960
#一拍 这两根骨头全断了
Knock it. Both bones will break

10
00:00:23,960 --> 00:00:29,160
#看着啊 一压 一个一个的来
Watch this. Press it, one by one

11
00:00:29,160 --> 00:00:33,560

12
00:00:33,560 --> 00:00:36,080
#先把这留着 然后再去那块
Keep this part first. Then remove it

13
00:00:36,080 --> 00:00:37,480
#能拿住它
(In this way) you can hold the chicken wing

14
00:00:37,480 --> 00:00:39,720
#大爷 那个真别糟蹋
Da Ye, don't waste that

15
00:00:39,720 --> 00:00:43,120
#绝对糟蹋不了 那个单做出一菜来
I won't of course! We can make a dish out of it

16
00:00:43,120 --> 00:00:46,320
#做一蒸的吧  蒸的好 豆豉蒸
What about steaming it? Good idea, steam it with "Douchi" fermented soybeans

17
00:00:46,320 --> 00:00:49,280
#这徒弟脑瓜灵啊 师父一直在念叨呢
What a brilliant disciple! Your master has always been talking about you

18
00:00:49,280 --> 00:00:50,800
#隋坡不来我恨死他了
like 'Sui Po doesn't come. I don't like him!' #这里认真的翻译吗哈哈哈

19
00:00:50,800 --> 00:00:52,160
#为什么老不来啊
'Why is he always absent?'

20
00:00:52,160 --> 00:00:57,320
#花为媒 似的 你怎么还不来呀
Like in the opera Hua Wei Mei, 'why~aren't~you~here~yet~'

21
00:00:57,320 --> 00:00:59,240
#全算上刚十五分钟
It's just 15 minutes since we started

22
00:00:59,240 --> 00:01:01,480
#这就完事了 正合适
And it's done! Perfect time

23
00:01:01,480 --> 00:01:05,480
#青椒 长短要比刚才剔出去的骨头
Green chili. The piece should be slightly longer

24
00:01:05,480 --> 00:01:10,480
#要稍微长一点 来个鸡蛋
than the bone that we just removed. Give me an egg

25
00:01:10,480 --> 00:01:13,040
#你这一招一式还挺利落
That's a nice move

26
00:01:13,040 --> 00:01:15,120
#照这样你能干到九十岁都没问题
You can do this all the way to your 90s

27
00:01:15,120 --> 00:01:17,800
#九十岁之前不会歇厨了
You won't retire from the kitchen before your 90s

28
00:01:17,800 --> 00:01:20,400
#二伯 咱俩得永远在一起
Er Bai, we need to stick together forever

29
00:01:20,400 --> 00:01:21,280
#实在干不了了
If you are too old to cook

30
00:01:21,280 --> 00:01:22,960
#您剥葱剥蒜也得在这儿干
You still have to stay here, even you can only peel the green onions and garlics

31
00:01:22,960 --> 00:01:24,120

32
00:01:24,120 --> 00:01:27,320
#上浆特别快 鸡蛋
Battering is very simple. Egg

33
00:01:27,320 --> 00:01:29,080
#因为咱们炒的是红汁菜
Since we are cooking a 'red sauce' dish

34
00:01:29,080 --> 00:01:30,320
#就用全鸡蛋
We can use whole eggs

35
00:01:30,320 --> 00:01:31,880
#必须要用蛋黄 因为它香
You must keep the yolk because it enhances the aroma

36
00:01:31,880 --> 00:01:34,520
#淀粉 大约十五克
Starch. About 15 grams

37
00:01:34,520 --> 00:01:37,480
#盐 三克 特别快啊
Salt. 3 grams. Very fast

38
00:01:37,480 --> 00:01:42,760
#鸡蛋蛋清 先把糊和好 攉拢匀了
Firstly, mix the batter uniformly

39
00:01:42,760 --> 00:01:44,200
#再给我来一点淀粉
Some more starch, please

40
00:01:44,200 --> 00:01:46,200
#半勺 好好
Half a spoon. That's enough!

41
00:01:46,200 --> 00:01:48,600
#这些淀粉用不完
We are not using it all

42
00:01:48,600 --> 00:01:51,200
#一会咱们再这点淀粉干别的用
Let's keep these for later use

43
00:01:51,200 --> 00:01:54,040
#好 拿走 十秒钟就完事了
Ok. Please take it away. It'll be done in 10 seconds

44
00:01:54,040 --> 00:01:58,400
#这盐搁好了 鸡蛋淀粉 叫搅拌上劲
We have added the salt already. Now mix the chicken with the egg-starch batter until you feel the resistance

45
00:01:59,360 --> 00:02:01,840
#OK了 有劲了
That's OK. Now it feels resistant

46
00:02:01,840 --> 00:02:05,040
#二伯回手给来点油
Er Bai, please add some oil

47
00:02:06,960 --> 00:02:09,320
#封油 好嘞
Seal with oil. Done!

48
00:02:09,320 --> 00:02:11,240

49
00:02:11,240 --> 00:02:14,040
#看着啊 现在开始串
Look. Now we start to insert the vegetables

50
00:02:14,040 --> 00:02:15,920
#为什么叫玉簪鸡翼球
Why is it called 'Jade hairpin chicken wing'?

51
00:02:15,920 --> 00:02:18,480
#就跟簪子似的 你看见没有
It looks just like a hairpin. See that?

52
00:02:18,480 --> 00:02:19,720
#为什么要用这两个颜色
Why are we using these two colors,

53
00:02:19,720 --> 00:02:21,960
#一红一绿 它漂亮
red and green? Because it looks beautiful

54
00:02:21,960 --> 00:02:25,880
#像不像簪子 再拿牙签咱串它一下
Looks like a hairpin, doesn't it? You can further stablize it with a toothpick 

55
00:02:25,880 --> 00:02:28,400
#它掉不了 巧就巧在这儿了
It won't fall apart. That's the tricky point

56
00:02:28,400 --> 00:02:30,720
#一成熟鸡肉就收缩了
The chicken shrinks once cooked

57
00:02:30,720 --> 00:02:32,400
#这个可以炒
You can stir-fry the chicken wing here

58
00:02:32,400 --> 00:02:36,000
#如果我们串点萝卜或者藕条
If you use raddish and lotus instead

59
00:02:36,000 --> 00:02:39,280
#可以给它出下水 就变成白的了
You can blanch it. The chicken wing will look white

60
00:02:39,280 --> 00:02:41,160
#白汁的可以清炖
You can make a soup in that case

61
00:02:41,160 --> 00:02:45,480
#国宴过去讲 吃完冷菜上两个小炒
In previous state banquets, two stir-fried dishes were served after the cold starters

62
00:02:45,480 --> 00:02:47,720
#这两个小炒是什么菜呢
What are the stir-fried dishes for?

63
00:02:47,720 --> 00:02:49,920
#是要喝酒的菜
They allow guests to have a drink

64
00:02:49,920 --> 00:02:53,200
#上完小炒以后才上大菜
The main course was served after the stir-fried dishes

65
00:02:53,200 --> 00:02:54,800
#过去的菜单就这么安排的
That's how we arranged the menu

66
00:02:54,800 --> 00:02:56,200
#比如说上完七个冷菜
For example, after seven cold dishes

67
00:02:56,200 --> 00:02:57,680
#跟着上俩小炒
Two stir-fried dishes were served

68
00:02:57,680 --> 00:03:00,680
#什么干煸牛肉丝 什么炒银芽
Like dry-fried shredded beef, or stir-fried bean sprouts

69
00:03:00,680 --> 00:03:02,240
#那会儿过瘾啊大爷
That was the good old times, Da Ye

70
00:03:02,240 --> 00:03:03,080
#隋坡看见没有
See that, Sui Po?

71
00:03:03,080 --> 00:03:06,520
#切东西做东西做事儿要稳妥
You need to be careful whenever you cut things or cook dishes

72
00:03:06,520 --> 00:03:10,080
#稳妥在哪呢 有数
More specifially, you have everything clear in your mind

73
00:03:10,080 --> 00:03:11,680
#干活要有数
Keep everything organized in your mind

74
00:03:11,680 --> 00:03:15,640
#看着啊 就剩了两根 这就不算剩
See that? Just two left. That's nothing

75
00:03:15,640 --> 00:03:19,760
#好 洗手 心里有谱 有谱
Okay, let me wash my hand. -Keep a clear mind!

76
00:03:19,760 --> 00:03:21,400

77
00:03:21,400 --> 00:03:24,640
#这下该下一小节目了啊
Now we proceed to our next show

78
00:03:24,640 --> 00:03:27,040
#咱们兑个碗汁
Let's make a bowl of sauce

79
00:03:27,040 --> 00:03:30,040
#酱油 米醋
Soybean sauce, rice vinegar

80
00:03:30,040 --> 00:03:32,200
#米醋一会还得烹点
We need to add some rice vinegar later

81
00:03:32,200 --> 00:03:36,880
#黄酒 盐 糖
Huangjiu rice wine, salt, and sugar

82
00:03:36,880 --> 00:03:38,480
#我这个叫碗汁不叫碗芡
This is 'bowl sauce', rather than 'bowl slurry sauce'

83
00:03:38,480 --> 00:03:39,920
#因为这里面没有淀粉
Because there's no starch here

84
00:03:39,920 --> 00:03:41,800
#要有淀粉叫碗芡
If there is, it's called 'bowl slurry sauce'

85
00:03:41,800 --> 00:03:44,240
#葱姜蒜小料 这就算齐活了
Minced green onion, ginger, and garlic. That's all we need

86
00:03:44,240 --> 00:03:46,280

87
00:03:46,280 --> 00:03:48,080
#辣椒 还得洗一洗
We need to wash the chili

88
00:03:48,080 --> 00:03:49,560
#把辣椒籽要洗出去
and remove the seeds

89
00:03:49,560 --> 00:03:52,480
#锅烧好了 二伯给倒点油
The wok is heated. Er Bai, please add some oil

90
00:03:53,960 --> 00:03:56,480
#看啊 这花生米炸好了
See? The peanuts are fried

91
00:03:56,480 --> 00:03:58,960
#给它搞成花生碎
Now we crush them into pieces

92
00:03:58,960 --> 00:04:01,520
#花生碎也好了 油温也高了
Peanuts taken care of. The oil temperature is right

93
00:04:01,520 --> 00:04:04,880
#现在已经五成热了
Now it's about 150 degrees celsius

94
00:04:04,880 --> 00:04:06,720

95
00:04:06,720 --> 00:04:07,920
#下锅
Into the wok

96
00:04:07,920 --> 00:04:12,880

97
00:04:12,880 --> 00:04:16,880
#不要乱动它 为什么不让动啊
Don't disturb it too much. Why?

98
00:04:16,880 --> 00:04:18,920
#一定要给鸡肉在油中
That's because you need some time for the starch on the surface of the chicken

99
00:04:18,920 --> 00:04:22,200
#表面淀粉糊化成熟的一个时间
to be solidified

100
00:04:22,200 --> 00:04:24,160
#否则会粘的满锅都是
Otherwise it would be stuck everywhere in the wok

101
00:04:24,160 --> 00:04:27,080
#这多漂亮 一个都没掉
Look how beautiful this is. None of them fell apart

102
00:04:27,080 --> 00:04:29,800
#出锅 收缩就可以倒进去了
Out of the wok as soon as the chicken shrinks

103
00:04:29,800 --> 00:04:33,120
#花椒 这花椒有的师傅炒
Sichuan peppercorns. Some chefs tend to keep them in the dish

104
00:04:33,120 --> 00:04:36,320
#就搁在里边了 但吃起来很不舒服
But in that case, you may have some trouble eating the dish

105
00:04:36,320 --> 00:04:38,200
#还要把它捞干净
So we should remove the peppercorns now

106
00:04:38,200 --> 00:04:39,880

107
00:04:39,880 --> 00:04:42,640
#你看我们这时候油温就很热
See? Now the oil temperature is very high

108
00:04:42,640 --> 00:04:45,360
#我为什么把辣椒给洗一下
That's why I washed the chili

109
00:04:45,360 --> 00:04:47,040
#这样的也会降低油温
This will help lowering the oil temperature as well

110
00:04:47,040 --> 00:04:49,400

111
00:04:50,440 --> 00:04:52,080
#它不会马上糊
The chili does not get burnt soon

112
00:04:52,080 --> 00:04:54,400
#到现在都没糊
Not burnt yet

113
00:04:54,400 --> 00:04:57,480
#要不是拿水洗了 一下就糊了 完了
If the chili was not washed, it will be burnt immediately. That'll spoil the dish

114
00:04:57,480 --> 00:04:58,840

115
00:04:58,840 --> 00:05:00,120
#葱姜
Green onion, ginger

116
00:05:00,120 --> 00:05:02,760
#糊辣味型的小料标配是葱姜蒜
The standard ingredients for this 'Hu La' (Slightly-burnt spicy) flavor are green onion, ginger, and garlic

117
00:05:02,760 --> 00:05:05,080
#对 小料的料头要狠
Yes. Add plenty of those

118
00:05:06,080 --> 00:05:08,960
#二伯 倒进来
Er Bai, put in the chicken in please

119
00:05:08,960 --> 00:05:11,680
#这个时候我们要搁点辣椒面
Now we add some chili pepper powder

120
00:05:11,680 --> 00:05:13,680
#辣椒面下去以后炒香
After adding the chili pepper powder, stir-fry until aromatic

121
00:05:13,680 --> 00:05:15,480
#碗汁儿
Add the bowl-sauce now

122
00:05:15,480 --> 00:05:17,880

123
00:05:17,880 --> 00:05:19,880
#颜色很漂亮
Nice color

124
00:05:19,880 --> 00:05:21,680
#因为这个汁要是炒鸡丁
The sauce would be too much if we are cooking diced chicken

125
00:05:21,680 --> 00:05:23,440
#这汁儿就多了 有一半就够了
Half of this would be enough

126
00:05:23,440 --> 00:05:27,000
#勾芡  因为这个鸡球比较大
Add slurry. Since the chicken wing is relatively large

127
00:05:27,000 --> 00:05:28,920
#所以这个汁儿稍微大一点
So we have relatively more sauce here

128
00:05:28,920 --> 00:05:30,840

129
00:05:30,840 --> 00:05:31,640
#好了
Okay

130
00:05:31,640 --> 00:05:34,320
#烹醋 提香
Add vinegar to enhance the aroma

131
00:05:34,320 --> 00:05:37,160

132
00:05:37,160 --> 00:05:38,120
#花生碎
Crushed peanuts

133
00:05:38,120 --> 00:05:41,480

134
00:05:41,480 --> 00:05:44,520
#您得打嚏喷或者打一咳嗽
You must be sneezing or coughing

135
00:05:44,520 --> 00:05:48,920

136
00:05:51,080 --> 00:05:53,560
#炒出来这菜您不打嚏喷我就失败了
Otherwise this dish would be a failure

137
00:05:55,880 --> 00:05:57,920
#你好长时间没来了
You haven't come for a long time

138
00:05:57,920 --> 00:05:58,960

139
00:06:00,920 --> 00:06:01,840
#谢谢师叔
Thank you, Er Bai!

140
00:06:02,000 --> 00:06:04,520
#照大爷 好吃啊这个
Look at Da Ye. This tastes great!

141
00:06:04,520 --> 00:06:08,480
#糊辣味十足 超级嫩
Full of 'Hu La' flavor. Super tender

142
00:06:08,480 --> 00:06:12,360
#特别嫩 太香了
Extremely tender. Smells awesome

143
00:06:12,360 --> 00:06:13,720
#改良之后有老的味道
You can taste the old flavors from this modified version

144
00:06:13,720 --> 00:06:16,160
#吃出老的宫保鸡丁的味道的时候
Apart from the old 'Kung Pao' flavor

145
00:06:16,160 --> 00:06:18,440
#还有蔬菜那种清香味
You can also taste the frangance of vegetables

146
00:06:18,440 --> 00:06:20,520
#花生米粘在上面
With crushed peanuts on the surface

147
00:06:20,520 --> 00:06:21,920
#那种花生米的酥香味
You can also enjoy the crispy and aroma of peanuts

148
00:06:21,920 --> 00:06:24,640
#这个菜巧妙的融为一体
This dish fuses all the flavors perfectly

149
00:06:24,640 --> 00:06:28,280
#人说做中国菜境界什么 就是融合
What is the highest level of Chinese cooking? Fusing.

150
00:06:28,280 --> 00:06:29,160
#它把各种味道
This dish fuses all flavors

151
00:06:29,160 --> 00:06:31,600
#融合到一个最高的境界
to an unprecedented extent

152
00:06:31,600 --> 00:06:33,880
#点个赞 谢谢二伯
Thumbs up! Thanks, Er Bai!

153
00:06:33,880 --> 00:06:44,760

154
00:06:44,760 --> 00:06:45,920
#给我们哥俩来一个
Let's take a photo for us brothers

155
00:06:45,920 --> 00:06:50,440

156
00:06:50,440 --> 00:06:53,440
#不过来就失去照相机会了
You will lose the opportunity for the photo if you don't come here
