### ISSUE TITLE
[老饭骨] 羊肉饺子 - https://youtu.be/dugcZPi6VGE

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1637]
**视频链接**：https://youtu.be/dugcZPi6VGE

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•羊肉饺子】鲜嫩多汁的羊肉饺子！国宴大师的调馅儿手法，一点没膻味！ |老饭骨

简介
小友们好，看到留言有小友想学羊肉饺子，但是在调味上把握不好，做出来的饺子不够鲜美。
这次大爷上场，带给大家他的调味儿法，做出来的羊肉饺子鲜嫩多汁，还一点儿膻味都没有，也不会影响羊肉本来的鲜香。
看完视频记得留言告诉老饭骨，开锅煮馅儿、闭锅煮皮的还有如何让饺子不粘的秘诀大家学会了吗？

字幕
1
00:00:00,000 --> 00:00:01,760
饺子大家谁都会包

2
00:00:01,760 --> 00:00:03,680
关键是调这馅儿

3
00:00:03,680 --> 00:00:06,120
上次做了一个三鲜馅饺子

4
00:00:06,120 --> 00:00:08,440
很多网友又提出来了

5
00:00:08,440 --> 00:00:10,080
能不能做个羊肉馅的

6
00:00:10,080 --> 00:00:13,640
饺子出锅啦 这大饺子

7
00:00:13,640 --> 00:00:14,800

8
00:00:14,800 --> 00:00:16,800

9
00:00:16,800 --> 00:00:19,320
这是一斤面 大约半斤水

10
00:00:19,320 --> 00:00:22,560
这个面 有的面吃水有的面不吃水

11
00:00:22,560 --> 00:00:27,320
说半斤水 但是最后还得灵活掌握

12
00:00:27,320 --> 00:00:28,960
今天咱用的是中筋粉

13
00:00:28,960 --> 00:00:34,240
防止饺子这面不得劲儿 搁点盐

14
00:00:34,240 --> 00:00:37,400
盐可以增加面粉的筋度

15
00:00:37,400 --> 00:00:39,280
所以说为什么你不给他拿高筋

16
00:00:39,280 --> 00:00:41,480
他就拿盐代替一下

17
00:00:41,480 --> 00:00:43,480
这和面要想让它均匀

18
00:00:43,480 --> 00:00:45,880
先把这面打成啰嗦

19
00:00:45,880 --> 00:00:51,480
您看您真是 一出手就知道是老手

20
00:00:51,480 --> 00:00:56,240
打成啰嗦我们逐渐的加点水

21
00:00:56,240 --> 00:00:58,560
您打大疙瘩汤也好吃

22
00:00:58,560 --> 00:01:00,960
啰嗦就变大了

23
00:01:00,960 --> 00:01:03,520
这时候我们可以往一块揣一揣

24
00:01:03,520 --> 00:01:07,280
还是那句话 三光

25
00:01:07,280 --> 00:01:12,320
看看 半斤水 半斤水没了 正好

26
00:01:12,320 --> 00:01:14,560
然后再揉揉

27
00:01:14,560 --> 00:01:16,680
原来饭店有时候包饺子

28
00:01:16,680 --> 00:01:18,720
咱们到那也得学去

29
00:01:18,720 --> 00:01:19,840
你看这个面

30
00:01:19,840 --> 00:01:23,320
我们为了让它光 还要蘸点水

31
00:01:23,320 --> 00:01:30,560
做面食就得勤揉 把面揉润了

32
00:01:30,560 --> 00:01:34,040
行 找一个布一盖 找块小布

33
00:01:34,040 --> 00:01:38,120
得是湿的 饧着 给我

34
00:01:38,120 --> 00:01:41,200

35
00:01:41,200 --> 00:01:47,440
洗洗手 现在第二步该是打馅

36
00:01:47,440 --> 00:01:49,720
全齐了我给你介绍介绍啊

37
00:01:49,720 --> 00:01:52,480
你看葱姜量都挺大

38
00:01:52,480 --> 00:01:55,760
白菜 是隋坡一刀一刀切的 没剁

39
00:01:55,760 --> 00:01:58,440
咱这要说明一下 白菜尽量别剁

40
00:01:58,440 --> 00:02:00,040
您看多整齐

41
00:02:00,040 --> 00:02:02,560
花椒水 热水泡的花椒水

42
00:02:02,560 --> 00:02:06,040
羊肉我们今天是事先给剁好了

43
00:02:06,040 --> 00:02:09,920
这是羊的后腿

44
00:02:09,920 --> 00:02:11,720
打这羊肉馅

45
00:02:11,720 --> 00:02:14,400
我们第一个要放花椒水

46
00:02:14,400 --> 00:02:16,560
羊肉是吃花椒的

47
00:02:16,560 --> 00:02:19,840
最好的配伍就是花椒 去膻

48
00:02:19,840 --> 00:02:22,560
下盐

49
00:02:22,560 --> 00:02:25,280

50
00:02:25,280 --> 00:02:26,680
酱油

51
00:02:26,680 --> 00:02:28,440
来点老抽 看看颜色

52
00:02:28,440 --> 00:02:31,120
白胡椒粉 两克够了

53
00:02:31,120 --> 00:02:33,000
这个我们开始用手打馅

54
00:02:33,000 --> 00:02:35,720
手打馅打的匀 打的实在

55
00:02:35,720 --> 00:02:37,160
朝一个方向打

56
00:02:37,160 --> 00:02:39,800
跟大爷似的 实实在在的

57
00:02:39,800 --> 00:02:45,040
得摔上劲儿 就跟你摔丸子似的

58
00:02:46,040 --> 00:02:48,680
为什么我不习惯用筷子搅

59
00:02:48,680 --> 00:02:51,640
有时候打的不匀 没劲儿

60
00:02:51,640 --> 00:02:53,960
在吃饺子里边 一般我们不加料酒

61
00:02:53,960 --> 00:02:57,440
因为它煮的 那酒味出不出去

62
00:02:57,440 --> 00:02:58,200
所以不加

63
00:02:58,200 --> 00:02:59,760

64
00:02:59,760 --> 00:03:01,000
又加点老抽

65
00:03:01,000 --> 00:03:03,240
大爷的饺子最关键是什么

66
00:03:03,240 --> 00:03:04,760
您看都能看明白了

67
00:03:04,760 --> 00:03:10,440
调色 调味 调鲜 去膻

68
00:03:10,440 --> 00:03:13,800
按道理如果说 羊肉大葱馅的

69
00:03:13,800 --> 00:03:17,160
这个肉馅就有点硬

70
00:03:17,160 --> 00:03:18,720
我们就得加点花椒水

71
00:03:18,720 --> 00:03:20,480
打上劲以后再加

72
00:03:20,480 --> 00:03:24,000
白菜馅我们就不加了

73
00:03:24,000 --> 00:03:27,320
白菜也不用杀水 正合适

74
00:03:27,320 --> 00:03:33,760
大葱 姜 姜不要太多

75
00:03:33,760 --> 00:03:37,040
你看一抓 正合适

76
00:03:37,040 --> 00:03:39,160
有时候看这盐看哪儿呢

77
00:03:39,160 --> 00:03:40,720
你看这白菜下去

78
00:03:40,720 --> 00:03:42,720
待会它就塌下去了

79
00:03:42,720 --> 00:03:45,360
说明这个盐就到位了

80
00:03:45,360 --> 00:03:48,640
如果说半天这白菜还没下去

81
00:03:48,640 --> 00:03:51,920
说明这咸味不够 这咸味差多了

82
00:03:51,920 --> 00:03:58,000
看着啊 拿手一抓

83
00:03:58,000 --> 00:04:00,760
这用羊肉做白菜馅儿的还真不多

84
00:04:00,760 --> 00:04:03,040
大葱的多 但是搁点白菜

85
00:04:03,040 --> 00:04:05,360
它煮出来以后白菜特别容易烂

86
00:04:05,360 --> 00:04:06,640
我得先闻闻这味

87
00:04:06,640 --> 00:04:08,000
还没搁香油呢

88
00:04:09,200 --> 00:04:11,360
等会儿搁上香油就香了

89
00:04:11,360 --> 00:04:14,640
香油

90
00:04:14,640 --> 00:04:16,880
这就是炸的料油

91
00:04:16,880 --> 00:04:20,680
葱姜 适当再加点小茴香大料就行了

92
00:04:20,680 --> 00:04:23,240
肉馅儿特别肥就不用加油了

93
00:04:23,240 --> 00:04:26,120
少加 香油肯定是要加的

94
00:04:26,120 --> 00:04:28,320
油加完这馅儿特别润

95
00:04:28,320 --> 00:04:30,120
现在基本都是油打馅 好了

96
00:04:30,120 --> 00:04:33,840
二伯 面饧好了 看着啊

97
00:04:33,840 --> 00:04:36,520
这回光滑了 开始包

98
00:04:36,520 --> 00:04:39,200
看这羊肉馅还挺新鲜

99
00:04:39,200 --> 00:04:44,360
这羊肉不错 不错吧 新鲜啊

100
00:04:44,360 --> 00:04:46,920
煮饺子有一小窍门 搁点盐

101
00:04:46,920 --> 00:04:49,960
这干嘛使呢 防止饺子出锅它粘

102
00:04:49,960 --> 00:04:53,760
防止它互相粘连 这就不粘了

103
00:04:53,760 --> 00:04:57,200
煮饺子得隆重 瞧着啊

104
00:04:57,200 --> 00:05:02,680
隋坡知道 因为所以 它不粘了

105
00:05:02,680 --> 00:05:05,640
往里面一推 理论家

106
00:05:06,480 --> 00:05:08,680
咱这锅大点多煮点

107
00:05:08,680 --> 00:05:11,000
到时候粘成一锅了 不会的

108
00:05:11,000 --> 00:05:13,240
粘成一锅那就是片儿汤汆丸子

109
00:05:13,240 --> 00:05:14,960
煮饺子我们是这样

110
00:05:14,960 --> 00:05:19,680
顺着锅边 把这水给轰起来

111
00:05:19,680 --> 00:05:21,840

112
00:05:21,840 --> 00:05:22,960
旋转

113
00:05:22,960 --> 00:05:26,440

114
00:05:26,440 --> 00:05:29,960
开锅是煮馅 闭锅煮皮儿 为什么

115
00:05:29,960 --> 00:05:33,360
因为饺子在水里漂着 漂着的时候

116
00:05:33,360 --> 00:05:36,360
它有上半拉皮是在水外边

117
00:05:36,360 --> 00:05:37,800
所以要盖上盖儿

118
00:05:37,800 --> 00:05:40,200
等皮儿就要快熟了

119
00:05:40,200 --> 00:05:43,000
我们开始煮馅了 就得开着锅

120
00:05:43,000 --> 00:05:45,600
如果再捂 就容易把饺子煮烂了

121
00:05:45,600 --> 00:05:48,200
皮儿就糟了

122
00:05:48,200 --> 00:05:51,080
锅开了

123
00:05:51,080 --> 00:05:54,240
你看锅开大了 加点水

124
00:05:54,240 --> 00:05:56,920
一是给它降降温

125
00:05:56,920 --> 00:06:00,280
二呢补充一点水分

126
00:06:00,280 --> 00:06:01,840
待会我们煮第二波

127
00:06:01,840 --> 00:06:05,080
这水不会乱 不会黏糊

128
00:06:05,080 --> 00:06:08,160
蒜泥 搁点醋 米醋

129
00:06:08,160 --> 00:06:10,920
在北京吃饺子一定要是吃米醋的

130
00:06:12,480 --> 00:06:16,840
少来点香油 香油多了它就不香

131
00:06:16,840 --> 00:06:18,520
这饺子煮到什么程度了你看

132
00:06:18,520 --> 00:06:22,520
全鼓起来 鼓的跟小泡儿似的

133
00:06:22,520 --> 00:06:25,240
起鼓不说了 还透亮呢

134
00:06:25,240 --> 00:06:27,760
摸摸 一按熟了

135
00:06:27,760 --> 00:06:31,760
这个馅儿硬了 硬了就熟了

136
00:06:31,760 --> 00:06:33,920
好 捞了

137
00:06:33,920 --> 00:06:35,520
来 照相

138
00:06:35,520 --> 00:06:38,120
这大饺子 饺子出锅啦

139
00:06:39,360 --> 00:06:39,920

140
00:06:39,920 --> 00:06:42,000
肉馅你看都成团了

141
00:06:42,000 --> 00:06:43,800
有汤吗 有汤你看

142
00:06:43,800 --> 00:06:46,480
最关键是什么

143
00:06:46,480 --> 00:06:49,840
肉非常鲜美 调味调的准确 还不柴

144
00:06:49,840 --> 00:06:51,560

145
00:06:51,560 --> 00:06:52,720
这中筋面粉

146
00:06:52,720 --> 00:06:55,920
师父放那一勺盐 起了作用了

147
00:06:55,920 --> 00:06:58,960
要不然要裂  劲儿不够

148
00:06:58,960 --> 00:07:01,080
它筋道了 韧性特别好

149
00:07:01,080 --> 00:07:03,800
二伯看见没有 这饺子不粘

150
00:07:03,800 --> 00:07:07,160
你看要不然他不加点盐就全粘上了

151
00:07:07,160 --> 00:07:11,360
而且调味的这些香料

152
00:07:11,360 --> 00:07:14,920
比如说花椒水 还有葱姜

153
00:07:14,920 --> 00:07:18,760
它没有把羊肉独有的香味去掉

154
00:07:18,760 --> 00:07:21,360
还保留了 特别好

155
00:07:21,360 --> 00:07:22,320
有汁 很香

156
00:07:22,320 --> 00:07:24,640
馅儿挺嫩吧 嫩

157
00:07:24,640 --> 00:07:26,600
还有您打那勺香料油

158
00:07:26,600 --> 00:07:28,320
最后那勺恰到好处

159
00:07:28,320 --> 00:07:30,280
要没这点油 这馅可能就有点干

160
00:07:30,280 --> 00:07:32,120
好 谢谢二伯 谢谢隋坡

161
00:07:32,120 --> 00:07:34,240
多吃点啊
```

**Comment by siyusun6918** [comment]
认领

**Comment by siyusun6918** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•羊肉饺子】鲜嫩多汁的羊肉饺子！国宴大师的调馅儿手法，一点没膻味！ |老饭骨
【State Banquet Masterchef - Lamb Dumpling】Juicy and Tender Lamb Lumpling, Methods of seasoning the stuffing from a state banquet Masterchef, no gamey taste at all!


简介
小友们好，看到留言有小友想学羊肉饺子，但是在调味上把握不好，做出来的饺子不够鲜美。
这次大爷上场，带给大家他的调味儿法，做出来的羊肉饺子鲜嫩多汁，还一点儿膻味都没有，也不会影响羊肉本来的鲜香。
看完视频记得留言告诉老饭骨，开锅煮馅儿、闭锅煮皮的还有如何让饺子不粘的秘诀大家学会了吗？

Hello friends! We saw in the comments that some of you want to learn how to make lamb dumplings but not sure about seasoning, the dumplings weren’t tasty enough. This time, Da Ye is here with his method of seasoning. The lamb dumplings made with his method are juicy and tender, and have no gamey taste at all, and won’t affect the original taste of the lamb. 
Please comment below and tell us whether you have learned the tips which are cooking the stuffing with open-lid and cooking the dough wrap with close-lid, besides how to prevent dumplings from sticking together. 





字幕
1
00:00:00,000 --> 00:00:01,760
饺子大家谁都会包
Everyone knows how to wrap the dumplings

2
00:00:01,760 --> 00:00:03,680
关键是调这馅儿
Yet not all know how to season the stuffing

3
00:00:03,680 --> 00:00:06,120
上次做了一个三鲜馅饺子
We made Sanxian dumplings last time

4
00:00:06,120 --> 00:00:08,440
很多网友又提出来了
A lot of you requested a video

5
00:00:08,440 --> 00:00:10,080
能不能做个羊肉馅的
for making dumplings with lamb

6
00:00:10,080 --> 00:00:13,640
饺子出锅啦 这大饺子 
The dumplings are fresh out of the pot, looks delicious

7
00:00:13,640 --> 00:00:14,800

8
00:00:14,800 --> 00:00:16,800

9
00:00:16,800 --> 00:00:19,320
这是一斤面 大约半斤水
This is one jin flour (0.5KG), About half jin water (0.25KG)

10
00:00:19,320 --> 00:00:22,560
这个面 有的面吃水有的面不吃水
Some flour absorbs more water than others

11
00:00:22,560 --> 00:00:27,320
说半斤水 但是最后还得灵活掌握
Even we said half jin water (0.25KG), we still need to be flexible about it

12
00:00:27,320 --> 00:00:28,960
今天咱用的是中筋粉
We are using all-purpose flour today
13
00:00:28,960 --> 00:00:34,240
防止饺子这面不得劲儿 搁点盐
Put in some salt in case the dough isn’t al dente enough

14
00:00:34,240 --> 00:00:37,400
盐可以增加面粉的筋度
Salt can help to build the gluten of the flour
15
00:00:37,400 --> 00:00:39,280
所以说为什么你不给他拿高筋
So why didn’t you give him the bread flour

16
00:00:39,280 --> 00:00:41,480
他就拿盐代替一下
He uses salt as an alternative

17
00:00:41,480 --> 00:00:43,480
这和面要想让它均匀
If you want to get an even dough

18
00:00:43,480 --> 00:00:45,880
先把这面打成啰嗦
Knead the flour into strips first

19
00:00:45,880 --> 00:00:51,480
您看您真是 一出手就知道是老手
Look at you, such a real professional 

20
00:00:51,480 --> 00:00:56,240
打成啰嗦我们逐渐的加点水
After we knead it into strips, gradually add some water

21
00:00:56,240 --> 00:00:58,560
您打大疙瘩汤也好吃
The dough drop soup you made was really delicious

22
00:00:58,560 --> 00:01:00,960
啰嗦就变大了
The strip is getting bigger 

23
00:01:00,960 --> 00:01:03,520
这时候我们可以往一块揣一揣
Then we can knead them together 

24
00:01:03,520 --> 00:01:07,280
还是那句话 三光
Again, “san guang” (bowl is clean, hands are clean, the dough is neat)

25
00:01:07,280 --> 00:01:12,320
看看 半斤水 半斤水没了 正好
Look at it, half jin water (0.25KG), just the right amount

26
00:01:12,320 --> 00:01:14,560
然后再揉揉
Then we keep kneading 

27
00:01:14,560 --> 00:01:16,680
原来饭店有时候包饺子
In the past, restaurants sometimes made dumplings 

28
00:01:16,680 --> 00:01:18,720
咱们到那也得学去
We would go there and learn it

29
00:01:18,720 --> 00:01:19,840
你看这个面
Check out this dough

30
00:01:19,840 --> 00:01:23,320
我们为了让它光 还要蘸点水
To make it neat, we need to add a little more water

31
00:01:23,320 --> 00:01:30,560
做面食就得勤揉 把面揉润了
When we make food with flour, we need to knead it a lot to make it moist

32
00:01:30,560 --> 00:01:34,040
行 找一个布一盖 找块小布
Done. Let’s find a cloth to cover it

33
00:01:34,040 --> 00:01:38,120
得是湿的 饧着 给我
The cloth has to be wet. Let’s rest the dough. Give it to me. 

34
00:01:38,120 --> 00:01:41,200

35
00:01:41,200 --> 00:01:47,440
洗洗手 现在第二步该是打馅
Wash my hands. Now the next step is to make the stuffing 

36
00:01:47,440 --> 00:01:49,720
全齐了我给你介绍介绍啊
It’s all here, let me introduce the ingredients 

37
00:01:49,720 --> 00:01:52,480
你看葱姜量都挺大
Lots of scallions and ginger

38
00:01:52,480 --> 00:01:55,760
白菜 是隋坡一刀一刀切的 没剁
Napa cabbage (only the leaves). Sui Po cut it, didn’t chop it. 

39
00:01:55,760 --> 00:01:58,440
咱这要说明一下 白菜尽量别剁
We want to be clear, try not to chop the Napa cabbage 

40
00:01:58,440 --> 00:02:00,040
您看多整齐
How even it is!

41
00:02:00,040 --> 00:02:02,560
花椒水 热水泡的花椒水
Sichuan pepper steeped water. Steeped with hot water
42
00:02:02,560 --> 00:02:06,040
羊肉我们今天是事先给剁好了
We chopped the lamb ahead today

43
00:02:06,040 --> 00:02:09,920
这是羊的后腿
This is the lamb hind leg

44
00:02:09,920 --> 00:02:11,720
打这羊肉馅
Time to make the lamb stuffing

45
00:02:11,720 --> 00:02:14,400
我们第一个要放花椒水
First, we put in the Sichuan pepper steeped water

46
00:02:14,400 --> 00:02:16,560
羊肉是吃花椒的
lamb need to pair up with the Sichuan pepper 

47
00:02:16,560 --> 00:02:19,840
最好的配伍就是花椒 去膻
It is the best combination to get rid of the gamey smell

48
00:02:19,840 --> 00:02:22,560
下盐
Add salt

49
00:02:22,560 --> 00:02:25,280

50
00:02:25,280 --> 00:02:26,680
酱油
Soy sauce

51
00:02:26,680 --> 00:02:28,440
来点老抽 看看颜色
Some dark soy sauce to give it some color

52
00:02:28,440 --> 00:02:31,120
白胡椒粉 两克够了
White pepper powder, 2g is enough

53
00:02:31,120 --> 00:02:33,000
这个我们开始用手打馅
We use our hands to beat the stuffing 

54
00:02:33,000 --> 00:02:35,720
手打馅打的匀 打的实在
The stuffing is more even and solid using the hand

55
00:02:35,720 --> 00:02:37,160
朝一个方向打
Mix it with one direction

56
00:02:37,160 --> 00:02:39,800
跟大爷似的 实实在在的
Just like Da Ye, solid

57
00:02:39,800 --> 00:02:45,040
得摔上劲儿 就跟你摔丸子似的
You need to throw it to get the texture like you throw the meatballs

58
00:02:46,040 --> 00:02:48,680
为什么我不习惯用筷子搅
Why I can’t get used to mixing the stuffing with chopsticks

59
00:02:48,680 --> 00:02:51,640
有时候打的不匀 没劲儿
Sometimes it wasn’t mixed evenly and tender

60
00:02:51,640 --> 00:02:53,960
在吃饺子里边 一般我们不加料酒
When we made the dumpling stuffing, we don’t normally use cooking wine

61
00:02:53,960 --> 00:02:57,440
因为它煮的 那酒味出不出去
Because when it boils, the alcohol wouldn’t volatilize 

62
00:02:57,440 --> 00:02:58,200
所以不加
So we don’t add cooking wine

63
00:02:58,200 --> 00:02:59,760

64
00:02:59,760 --> 00:03:01,000
又加点老抽
Add more dark soy sauce

65
00:03:01,000 --> 00:03:03,240
大爷的饺子最关键是什么
The key points of Da Ye’s dumpling 

66
00:03:03,240 --> 00:03:04,760
您看都能看明白了
You can see them clearly

67
00:03:04,760 --> 00:03:10,440
调色 调味 调鲜 去膻
Coloring, Seasoning, Getting rid of the gamey taste

68
00:03:10,440 --> 00:03:13,800
按道理如果说 羊肉大葱馅的
Normally, if we make the stuffing with lamb and leek

69
00:03:13,800 --> 00:03:17,160
这个肉馅就有点硬
This texture would be too hard

70
00:03:17,160 --> 00:03:18,720
我们就得加点花椒水
We need to add more Sichuan pepper steeped water

71
00:03:18,720 --> 00:03:20,480
打上劲以后再加
Add the water after it has beaten enough
72
00:03:20,480 --> 00:03:24,000
白菜馅我们就不加了
We won’t add more water to this stuffing with Napa cabbage

73
00:03:24,000 --> 00:03:27,320
白菜也不用杀水 正合适
We don’t need to extract water from the Napa cabbage as well

74
00:03:27,320 --> 00:03:33,760
大葱 姜 姜不要太多
Leek, not too much ginger

75
00:03:33,760 --> 00:03:37,040
你看一抓 正合适
Grab it, the texture is just right

76
00:03:37,040 --> 00:03:39,160
有时候看这盐看哪儿呢
Sometimes when we want to know if we need more salt

77
00:03:39,160 --> 00:03:40,720
你看这白菜下去
You can see the cabbage is shrinking

78
00:03:40,720 --> 00:03:42,720
待会它就塌下去了
It will sink later

79
00:03:42,720 --> 00:03:45,360
说明这个盐就到位了
Which means we have enough salt

80
00:03:45,360 --> 00:03:48,640
如果说半天这白菜还没下去
If the cabbage isn’t shrinking after a while

81
00:03:48,640 --> 00:03:51,920
说明这咸味不够 这咸味差多了
Means it’s way not salty enough. 

82
00:03:51,920 --> 00:03:58,000
看着啊 拿手一抓
Look, I’m grabbing it with hands 
83
00:03:58,000 --> 00:04:00,760
这用羊肉做白菜馅儿的还真不多
It’s not common to use napa cabbage in lamb stuffing

84
00:04:00,760 --> 00:04:03,040
大葱的多 但是搁点白菜
Mostly pairs up with leek, but add some napa cabbage

85
00:04:03,040 --> 00:04:05,360
它煮出来以后白菜特别容易烂
After it boiled, the napa cabbage is really easy to become mushy

86
00:04:05,360 --> 00:04:06,640
我得先闻闻这味
I’m going to smell it

87
00:04:06,640 --> 00:04:08,000
还没搁香油呢
We haven’t added the sesame oil 

88
00:04:09,200 --> 00:04:11,360
等会儿搁上香油就香了
It’s going to smell really good after adding the sesame oil

89
00:04:11,360 --> 00:04:14,640
香油
Sesame oil

90
00:04:14,640 --> 00:04:16,880
这就是炸的料油
This is Liao You (the oil fried with many ingredients)

91
00:04:16,880 --> 00:04:20,680
葱姜 适当再加点小茴香大料就行了
Scallions, ginger, and some fennel and star anise 


92
00:04:20,680 --> 00:04:23,240
肉馅儿特别肥就不用加油了
If the stuffing is very fat, there is no need for extra oil

93
00:04:23,240 --> 00:04:26,120
少加 香油肯定是要加的
Don't add too much. Sesame oil is a must

94
00:04:26,120 --> 00:04:28,320
油加完这馅儿特别润
The stuffing is moist after adding the oil

95
00:04:28,320 --> 00:04:30,120
现在基本都是油打馅 好了
Now we all use oil in the stuffing. Done

96
00:04:30,120 --> 00:04:33,840
二伯 面饧好了 看着啊
Er Bai, the dough is rested. Watch closely.

97
00:04:33,840 --> 00:04:36,520
这回光滑了 开始包
It’s smooth now. Time to make the dumplings

98
00:04:36,520 --> 00:04:39,200
看这羊肉馅还挺新鲜
The lamb stuffing is pretty fresh

99
00:04:39,200 --> 00:04:44,360
这羊肉不错 不错吧 新鲜啊
This lamb is good. Right? It’s fresh. 

100
00:04:44,360 --> 00:04:46,920
煮饺子有一小窍门 搁点盐
Here is a tip for boiling the dumplings. Add some salt

101
00:04:46,920 --> 00:04:49,960
这干嘛使呢 防止饺子出锅它粘
Why is that? In case the dumplings stick together out of the pot

102
00:04:49,960 --> 00:04:53,760
防止它互相粘连 这就不粘了 
In case they stick together. Now they won’t. 

103
00:04:53,760 --> 00:04:57,200
煮饺子得隆重 瞧着啊
Boiling dumplings need to be ceremonious. Look at it. 

104
00:04:57,200 --> 00:05:02,680
隋坡知道 因为所以 它不粘了
Sui Po knows. Because of the salt, they won’t stick.

105
00:05:02,680 --> 00:05:05,640
往里面一推 理论家
Give them a little push. Theorists. 

106
00:05:06,480 --> 00:05:08,680
咱这锅大点多煮点
We can boil more with such a big pot

107
00:05:08,680 --> 00:05:11,000
到时候粘成一锅了 不会的
What if they stick together. No, they won’t. 

108
00:05:11,000 --> 00:05:13,240
粘成一锅那就是片儿汤汆丸子 
If they do, then it’s sliced dough soup with boiled meatballs.

109
00:05:13,240 --> 00:05:14,960
煮饺子我们是这样
Here’s what we do when we boil the dumplings

110
00:05:14,960 --> 00:05:19,680
顺着锅边 把这水给轰起来
Spin the water alongside the pot

111
00:05:19,680 --> 00:05:21,840

112
00:05:21,840 --> 00:05:22,960
旋转
Spin

113
00:05:22,960 --> 00:05:26,440

114
00:05:26,440 --> 00:05:29,960
开锅是煮馅 闭锅煮皮儿 为什么
Open-lid is to cook the stuffing, close-lid is to cook the dough wrap. Why

115
00:05:29,960 --> 00:05:33,360
因为饺子在水里漂着 漂着的时候
Because when the dumplings flow in the water

116
00:05:33,360 --> 00:05:36,360
它有上半拉皮是在水外边
Half of the wrap is flowing on the water

117
00:05:36,360 --> 00:05:37,800
所以要盖上盖儿
So we need to close the lid

118
00:05:37,800 --> 00:05:40,200
等皮儿就要快熟了
When the wrap is almost cooked

119
00:05:40,200 --> 00:05:43,000
我们开始煮馅了 就得开着锅
We start to cook the stuffing with open-lid

120
00:05:43,000 --> 00:05:45,600
如果再捂 就容易把饺子煮烂了
If we keep the lid close, the dumplings would break apart

121
00:05:45,600 --> 00:05:48,200
皮儿就糟了
The wrap would be terrible

122
00:05:48,200 --> 00:05:51,080
锅开了
The water is boiling

123
00:05:51,080 --> 00:05:54,240
你看锅开大了 加点水
When you see the water boils, add some water

124
00:05:54,240 --> 00:05:56,920
一是给它降降温
Firstly, it will cool done the temperature 

125
00:05:56,920 --> 00:06:00,280
二呢补充一点水分
Secondly, it will add more water  

126
00:06:00,280 --> 00:06:01,840
待会我们煮第二波
When we boil the second batch later

127
00:06:01,840 --> 00:06:05,080
这水不会乱 不会黏糊
The water will not be messy and sticky

128
00:06:05,080 --> 00:06:08,160
蒜泥 搁点醋 米醋
Minced garlic, add some vinegar, rice vinegar 

129
00:06:08,160 --> 00:06:10,920
在北京吃饺子一定要是吃米醋的
You have to dip rice vinegar when you eat dumplings in Beijing

130
00:06:12,480 --> 00:06:16,840
少来点香油 香油多了它就不香
Add little sesame oil. Too much sesame oil will make it less tasty

131
00:06:16,840 --> 00:06:18,520
这饺子煮到什么程度了你看
Let’s find out how’s the dumplings now
132
00:06:18,520 --> 00:06:22,520
全鼓起来 鼓的跟小泡儿似的
All puff up, like small bubbles

133
00:06:22,520 --> 00:06:25,240
起鼓不说了 还透亮呢
Not only puffs up but also lucency

134
00:06:25,240 --> 00:06:27,760
摸摸 一按熟了
Give it a touch, it’s cooked

135
00:06:27,760 --> 00:06:31,760
这个馅儿硬了 硬了就熟了
The stuffing is hard. Once it’s hardened, it’s cooked

136
00:06:31,760 --> 00:06:33,920
好 捞了
Ok, scoop them out

137
00:06:33,920 --> 00:06:35,520
来 照相
Time for photoes

138
00:06:35,520 --> 00:06:38,120
这大饺子 饺子出锅啦
The dumplings are fresh out of the pot, looks delicious


139
00:06:39,360 --> 00:06:39,920

140
00:06:39,920 --> 00:06:42,000
肉馅你看都成团了
The suffering is shaped like a ball

141
00:06:42,000 --> 00:06:43,800
有汤吗 有汤你看
Is there juice inside? Yes, look. 

142
00:06:43,800 --> 00:06:46,480
最关键是什么
What’s the most important is 

143
00:06:46,480 --> 00:06:49,840
肉非常鲜美 调味调的准确 还不柴
The meat is really tasty, the seasoning is perfect, and it’s not dry at all
144
00:06:49,840 --> 00:06:51,560

145
00:06:51,560 --> 00:06:52,720
这中筋面粉
The all purpose flour

146
00:06:52,720 --> 00:06:55,920
师父放那一勺盐 起了作用了
The salt that the master added is working

147
00:06:55,920 --> 00:06:58,960
要不然要裂  劲儿不够
Otherwise, the dough would break apart, the gluten would not be enough

148
00:06:58,960 --> 00:07:01,080
它筋道了 韧性特别好
Once the gluten has developed, the strength becomes better

149
00:07:01,080 --> 00:07:03,800
二伯看见没有 这饺子不粘
Er Bai look at it, the dumplings didn’t stick 

150
00:07:03,800 --> 00:07:07,160
你看要不然他不加点盐就全粘上了
They would be stick together without that salt

151
00:07:07,160 --> 00:07:11,360
而且调味的这些香料
Add the ingredients for the seasoning

152
00:07:11,360 --> 00:07:14,920
比如说花椒水 还有葱姜
Such as Sichuan pepper steeped water, and scallions and ginger

153
00:07:14,920 --> 00:07:18,760
它没有把羊肉独有的香味去掉
They didn’t get remove the unique taste of the lamb

154
00:07:18,760 --> 00:07:21,360
还保留了 特别好
It was well kept, really nice

155
00:07:21,360 --> 00:07:22,320
有汁 很香
Juciy, tasty 

156
00:07:22,320 --> 00:07:24,640
馅儿挺嫩吧 嫩
Isn’t the stuffing tender? Tender. 

157
00:07:24,640 --> 00:07:26,600
还有您打那勺香料油
And the spoon of sesame oil you added to the stuffing

158
00:07:26,600 --> 00:07:28,320
最后那勺恰到好处
That was perfect

159
00:07:28,320 --> 00:07:30,280
要没这点油 这馅可能就有点干
Without that oil, the stuffing would be a little too dry

160
00:07:30,280 --> 00:07:32,120
好 谢谢二伯 谢谢隋坡
Ok. Thank you, Er Bai. Thank you, Sui Po.

161
00:07:32,120 --> 00:07:34,240
多吃点啊
Bon appetit!
