### ISSUE TITLE
[老饭骨] 冰糖葫芦 - https://youtu.be/EPgZcyqO_mI

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1652]
**视频链接**：https://youtu.be/EPgZcyqO_mI

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•冰糖葫芦】酸酸甜甜特开胃，童年回忆冰糖葫芦，三个步骤薄脆不粘牙！ |老饭骨

简介
小友们好，周一了老饭骨给大家带来一道所有人的童年回忆——冰糖葫芦！
冰糖葫芦酸酸甜甜，老少皆宜，还具有开胃、养颜、增智、消除疲劳、清热等大家可能都想不到的作用。
冰糖葫芦的做法其实也很简单，跟着小魏师傅掌握三个关键步骤，糖衣就能做得薄脆不粘牙，咬起来嘎嘣脆。
做这道小吃，大爷和二伯都还有点伤感了，想起他们小时候吃串糖葫芦就快过年了，这一晃就几十年过去了。
小友们还有什么想吃的童年回忆中的小吃吗？评论区告诉我们，老饭骨给大家做！

字幕
1
00:00:00,000 --> 00:00:00,640
往这一摆

2
00:00:00,640 --> 00:00:02,520
跟那个小算盘似的

3
00:00:02,520 --> 00:00:03,720
挂糖了

4
00:00:03,720 --> 00:00:05,440
薄薄的一层

5
00:00:05,440 --> 00:00:07,000
糖是嘎嘣脆

6
00:00:07,000 --> 00:00:08,400
冰糖葫芦

7
00:00:08,400 --> 00:00:11,360
这个是网友盼了已久已久了

8
00:00:13,080 --> 00:00:14,800
这是刚才洗了一遍水

9
00:00:14,800 --> 00:00:17,240
咱们现在处理一下 加点盐

10
00:00:17,240 --> 00:00:19,000
把这脏东西都处理掉

11
00:00:19,000 --> 00:00:20,520
再加上底口有点盐度

12
00:00:20,520 --> 00:00:22,560
这样它不腻口了

13
00:00:22,560 --> 00:00:24,040
要想甜 加点盐

14
00:00:24,040 --> 00:00:25,680

15
00:00:25,680 --> 00:00:27,360
控下水

16
00:00:27,360 --> 00:00:30,040
糖葫芦也是庙会上的

17
00:00:30,040 --> 00:00:32,280
不可缺少的一个美食

18
00:00:32,280 --> 00:00:34,880
这糖葫芦 又简单又不简单

19
00:00:34,880 --> 00:00:36,640
其实关键是炒糖

20
00:00:36,640 --> 00:00:39,760
炒过了呢就苦了

21
00:00:39,760 --> 00:00:42,160
炒的不够呢 粘牙

22
00:00:42,160 --> 00:00:43,800
你把这难度说的这么大

23
00:00:43,800 --> 00:00:46,960
就说明自己的技术高超啊这意思

24
00:00:46,960 --> 00:00:48,880
在师父跟大爷面前

25
00:00:48,880 --> 00:00:50,040
还是心里

26
00:00:50,040 --> 00:00:50,880
还是有点那什么

27
00:00:50,880 --> 00:00:53,320
不是 师父还是厉害

28
00:00:53,320 --> 00:00:57,200
下次让二伯做一个 那叫翻砂的

29
00:00:57,200 --> 00:01:00,360
那个是我强项

30
00:01:00,360 --> 00:01:05,480
过去我老做翻砂芋头 老粤菜

31
00:01:05,480 --> 00:01:07,440
炒出来特别好吃 是吧

32
00:01:07,440 --> 00:01:08,840
下次您来一个吧

33
00:01:08,840 --> 00:01:10,120
糖葫芦串好了

34
00:01:10,120 --> 00:01:11,880
往这一摆跟那小算盘似的

35
00:01:11,880 --> 00:01:13,200
开始熬糖

36
00:01:13,200 --> 00:01:14,880

37
00:01:14,880 --> 00:01:19,000
260克水

38
00:01:19,000 --> 00:01:23,440
300克白砂糖

39
00:01:23,440 --> 00:01:26,040
水炒 纯水炒

40
00:01:26,040 --> 00:01:27,600
这刚开始大火

41
00:01:27,600 --> 00:01:30,280
待会快好的时候开始就小火了

42
00:01:30,280 --> 00:01:32,520
抹点油这上头

43
00:01:32,520 --> 00:01:35,640
待会不容易粘上 不容易粘

44
00:01:35,640 --> 00:01:37,920
这时候咱们稍微加一点点盐

45
00:01:37,920 --> 00:01:39,440
吃到嘴里它不腻

46
00:01:39,440 --> 00:01:41,680
这个原来小的时候来这么一串

47
00:01:41,680 --> 00:01:45,880
算是好生活了 是吧大爷

48
00:01:47,400 --> 00:01:49,240
很奢侈了

49
00:01:49,240 --> 00:01:52,640
小时候小孩没那么多零食

50
00:01:52,640 --> 00:01:55,320
炒这糖色待会儿会有三个步骤

51
00:01:55,320 --> 00:01:59,000
第一个步骤 就是冒白泡

52
00:01:59,000 --> 00:02:02,360
你看这会儿的糖 这个泡是白的

53
00:02:02,360 --> 00:02:04,560
再炒一会 晾凉了以后

54
00:02:04,560 --> 00:02:06,400
就可以做成翻砂了

55
00:02:06,400 --> 00:02:09,400
炒糖色不能着急

56
00:02:09,400 --> 00:02:11,800
还是大火 慢慢炒

57
00:02:11,800 --> 00:02:14,680
这会有点上色了

58
00:02:14,680 --> 00:02:16,960
大爷现在就可以翻砂了

59
00:02:16,960 --> 00:02:19,120
这时候就得转小火了

60
00:02:19,120 --> 00:02:20,200
第二个步骤

61
00:02:20,200 --> 00:02:21,600
这糖深黄色的时候

62
00:02:21,600 --> 00:02:24,000
再炒一会就可以拔丝了

63
00:02:24,000 --> 00:02:26,400
拔丝就蘸糖葫芦没问题了

64
00:02:26,400 --> 00:02:29,480
然后这稠度一下来 稀释了

65
00:02:29,480 --> 00:02:33,200
花泡一下去就能拔丝了

66
00:02:33,200 --> 00:02:34,520
把火关了啊

67
00:02:34,520 --> 00:02:36,280
离火 离下来

68
00:02:36,280 --> 00:02:38,080
这时候你看 这糖色

69
00:02:38,080 --> 00:02:39,680
这时候拔丝好 金黄色

70
00:02:39,680 --> 00:02:41,760
稀了你看见没有 这就行了

71
00:02:41,760 --> 00:02:44,440
这时候可以挂了啊 挂糖了

72
00:02:44,440 --> 00:02:46,120
薄薄的一层

73
00:02:46,120 --> 00:02:50,400

74
00:02:50,400 --> 00:02:51,480
速度要快

75
00:02:51,480 --> 00:02:52,800

76
00:02:53,240 --> 00:02:54,920
好 齐活

77
00:02:54,920 --> 00:02:56,280
冰糖葫芦

78
00:02:56,280 --> 00:02:57,960
剩下这糖 我加点水

79
00:02:57,960 --> 00:02:59,760
这会儿就糖色了

80
00:03:00,840 --> 00:03:02,440
炖个肉啊 炖个排骨

81
00:03:02,440 --> 00:03:05,160
一举两得了啊 好嘞

82
00:03:05,160 --> 00:03:06,680
师父尝尝

83
00:03:06,680 --> 00:03:09,320

84
00:03:09,320 --> 00:03:10,040
听声音

85
00:03:10,040 --> 00:03:12,560

86
00:03:12,560 --> 00:03:14,480
嘎嘣脆

87
00:03:14,480 --> 00:03:18,680
慢点 别把核当冰糖咬了

88
00:03:18,680 --> 00:03:19,760
大爷咱们小时候

89
00:03:19,760 --> 00:03:22,800
要吃这么一串糖葫芦过年了

90
00:03:22,800 --> 00:03:25,600
一想40多年过去了大爷

91
00:03:25,600 --> 00:03:28,640
多少看见糖葫芦有点伤悲

92
00:03:28,640 --> 00:03:30,320
我有30年

93
00:03:30,320 --> 00:03:32,800
没吃过糖葫芦了

94
00:03:32,800 --> 00:03:34,120
真像二伯说的

95
00:03:34,120 --> 00:03:38,040
我们想起了儿时的记忆

96
00:03:38,040 --> 00:03:39,680
鼓励的话 二伯也说了 我也说了

97
00:03:41,240 --> 00:03:43,960
再说一个不足的地儿

98
00:03:43,960 --> 00:03:45,720
我见人家蘸糖葫芦

99
00:03:45,720 --> 00:03:48,240
其实蘸我们这大理石板上

100
00:03:48,240 --> 00:03:51,000
一定要有一个什么厚一点的石头板

101
00:03:51,000 --> 00:03:53,720
外边晾一下 给它冻一下

102
00:03:53,720 --> 00:03:55,080
或者让它镇凉一点

103
00:03:55,080 --> 00:03:58,080
你这个糖往上一浇 唰一流

104
00:03:58,080 --> 00:04:01,600
正好冰花出来 更精彩

105
00:04:01,600 --> 00:04:04,040
然后还有一点不足大爷

106
00:04:04,040 --> 00:04:06,080
说说说 抢答了

107
00:04:06,080 --> 00:04:07,440
我跟你说做这个

108
00:04:07,440 --> 00:04:09,120
核必须得去

109
00:04:09,120 --> 00:04:11,160
要不然你让我们吐核多难受啊

110
00:04:11,160 --> 00:04:12,520
这必须得改

111
00:04:12,520 --> 00:04:14,680
好 感谢师父 感谢大爷 好
```

**Comment by hansdaman** [comment]
认领

**Comment by hansdaman** [comment]
【国宴大师•冰糖葫芦】酸酸甜甜特开胃，童年回忆冰糖葫芦，三个步骤薄脆不粘牙！ |老饭骨

简介
小友们好，周一了老饭骨给大家带来一道所有人的童年回忆——冰糖葫芦！
冰糖葫芦酸酸甜甜，老少皆宜，还具有开胃、养颜、增智、消除疲劳、清热等大家可能都想不到的作用。
冰糖葫芦的做法其实也很简单，跟着小魏师傅掌握三个关键步骤，糖衣就能做得薄脆不粘牙，咬起来嘎嘣脆。
做这道小吃，大爷和二伯都还有点伤感了，想起他们小时候吃串糖葫芦就快过年了，这一晃就几十年过去了。
小友们还有什么想吃的童年回忆中的小吃吗？评论区告诉我们，老饭骨给大家做！

字幕
1
00:00:00,000 --> 00:00:00,640
往这一摆
Place them like this
2
00:00:00,640 --> 00:00:02,520
跟那个小算盘似的
and it looks just like an abacus
3
00:00:02,520 --> 00:00:03,720
挂糖了
Pour the sugar over
4
00:00:03,720 --> 00:00:05,440
薄薄的一层
to create a thin layer
5
00:00:05,440 --> 00:00:07,000
糖是嘎嘣脆
and that crackling crispy sound
6
00:00:07,000 --> 00:00:08,400
冰糖葫芦
Candied hawthorn
7
00:00:08,400 --> 00:00:11,360
这个是网友盼了已久已久了
Our viewers have been waiting a long, long time for this one
8
00:00:13,080 --> 00:00:14,800
这是刚才洗了一遍水
We’ve just washed it with water
9
00:00:14,800 --> 00:00:17,240
咱们现在处理一下 加点盐
Now we will start to prepare it. First we add salt
10
00:00:17,240 --> 00:00:19,000
把这脏东西都处理掉
This cleans away any remaining dirt
11
00:00:19,000 --> 00:00:20,520
再加上底口有点盐度
and adds a bit of saltiness
12
00:00:20,520 --> 00:00:22,560
这样它不腻口了
so it’s not too sweet
13
00:00:22,560 --> 00:00:24,040
要想甜 加点盐
If you want it sweet, you’ve got to add salt
14
00:00:24,040 --> 00:00:25,680

15
00:00:25,680 --> 00:00:27,360
控下水
Drain the water
16
00:00:27,360 --> 00:00:30,040
糖葫芦也是庙会上的
Candied hawthorn is something
17
00:00:30,040 --> 00:00:32,280
不可缺少的一个美食
no temple fair can be without
18
00:00:32,280 --> 00:00:34,880
这糖葫芦 又简单又不简单
It’s so simple yet so hard to get right
19
00:00:34,880 --> 00:00:36,640
其实关键是炒糖
The key to it is in cooking the caramel
20
00:00:36,640 --> 00:00:39,760
炒过了呢就苦了
Overcook it and it turns bitter
21
00:00:39,760 --> 00:00:42,160
炒的不够呢 粘牙
Undercook it and it sticks to the teeth
22
00:00:42,160 --> 00:00:43,800
你把这难度说的这么大
You make a big deal of how difficult this is
23
00:00:43,800 --> 00:00:46,960
就说明自己的技术高超啊这意思
Are you trying to demonstrate how skilful you are?
24
00:00:46,960 --> 00:00:48,880
在师父跟大爷面前
Next to Master and Da Ye…
25
00:00:48,880 --> 00:00:50,040
还是心里
I still feel a little
26
00:00:50,040 --> 00:00:50,880
还是有点那什么
You know…
27
00:00:50,880 --> 00:00:53,320
不是 师父还是厉害
Master is still the best
28
00:00:53,320 --> 00:00:57,200
下次让二伯做一个 那叫翻砂的
Next time we should get Er Bai to do that sugar coated dish
29
00:00:57,200 --> 00:01:00,360
那个是我强项
That one’s my specialty
30
00:01:00,360 --> 00:01:05,480
过去我老做翻砂芋头 老粤菜
In the past, I would always be making sugar coated taro  -  an old Cantonese dish
31
00:01:05,480 --> 00:01:07,440
炒出来特别好吃 是吧
I can make that one real good  -  oh really?
32
00:01:07,440 --> 00:01:08,840
下次您来一个吧
We’ll get you to do it next time then
33
00:01:08,840 --> 00:01:10,120
糖葫芦串好了
The skewers are all ready to go now
34
00:01:10,120 --> 00:01:11,880
往这一摆跟那小算盘似的
Place them like this and it looks just like an abacus
35
00:01:11,880 --> 00:01:13,200
开始熬糖
Now we can start cooking the sugar
36
00:01:13,200 --> 00:01:14,880

37
00:01:14,880 --> 00:01:19,000
260克水
260g of water
38
00:01:19,000 --> 00:01:23,440
300克白砂糖
300g of white sugar
39
00:01:23,440 --> 00:01:26,040
水炒 纯水炒
We will be using water to cook the sugar, water and nothing else
40
00:01:26,040 --> 00:01:27,600
这刚开始大火
It’s just been put on high heat
41
00:01:27,600 --> 00:01:30,280
待会快好的时候开始就小火了
We let it heat up first and turn it back down to low when it’s almost ready 
42
00:01:30,280 --> 00:01:32,520
抹点油这上头
Rub some oil here
43
00:01:32,520 --> 00:01:35,640
待会不容易粘上 不容易粘
to prevent the sugar from sticking later on
44
00:01:35,640 --> 00:01:37,920
这时候咱们稍微加一点点盐
Now add a small pinch of salt
45
00:01:37,920 --> 00:01:39,440
吃到嘴里它不腻
so it’s not overly sweet
46
00:01:39,440 --> 00:01:41,680
这个原来小的时候来这么一串
Back when we were kids, you would count yourself lucky
47
00:01:41,680 --> 00:01:45,880
算是好生活了 是吧大爷
just to eat even one of these  -  isn’t that right, Da Ye?
48
00:01:47,400 --> 00:01:49,240
很奢侈了
Luxurious is what it’d be 
49
00:01:49,240 --> 00:01:52,640
小时候小孩没那么多零食
Back in our days, kids didn’t have that many snacks
50
00:01:52,640 --> 00:01:55,320
炒这糖色待会儿会有三个步骤
When caramelising the sugar, there are three main steps
51
00:01:55,320 --> 00:01:59,000
第一个步骤 就是冒白泡
The first step is let the bubbles form
52
00:01:59,000 --> 00:02:02,360
你看这会儿的糖 这个泡是白的
Look at how the sugar is here, the bubbles are white
53
00:02:02,360 --> 00:02:04,560
再炒一会 晾凉了以后
If you keep cooking, after it has cooled and dried
54
00:02:04,560 --> 00:02:06,400
就可以做成翻砂了
you can use it as a sugar coating
55
00:02:06,400 --> 00:02:09,400
炒糖色不能着急
When caramelising sugar it’s important not to rush, you’ve got to be patient with it
56
00:02:09,400 --> 00:02:11,800
还是大火 慢慢炒
It’s still on high heat  -  let it continue to caramelise slowly
57
00:02:11,800 --> 00:02:14,680
这会有点上色了
You can see it’s starting to get a bit of colour
58
00:02:14,680 --> 00:02:16,960
大爷现在就可以翻砂了
Da Ye could use this as sugar coating when it’s at this stage
59
00:02:16,960 --> 00:02:19,120
这时候就得转小火了
We turn the heat down to low
60
00:02:19,120 --> 00:02:20,200
第二个步骤
The second step
61
00:02:20,200 --> 00:02:21,600
这糖深黄色的时候
When the caramel has taken on a dark yellow colour
62
00:02:21,600 --> 00:02:24,000
再炒一会就可以拔丝了
keep cooking a bit longer and it will be ready for use as a sugar glaze
63
00:02:24,000 --> 00:02:26,400
拔丝就蘸糖葫芦没问题了
This glaze will have no problem sticking to the hawthorn
64
00:02:26,400 --> 00:02:29,480
然后这稠度一下来 稀释了
When it has reached this consistency, the water starts to take on the sugar
65
00:02:29,480 --> 00:02:33,200
花泡一下去就能拔丝了
Keep stirring for a while longer and it’ll be ready for use
66
00:02:33,200 --> 00:02:34,520
把火关了啊
Turn the heat off
67
00:02:34,520 --> 00:02:36,280
离火 离下来
and take it off the hob
68
00:02:36,280 --> 00:02:38,080
这时候你看 这糖色
Have a look at this colour
69
00:02:38,080 --> 00:02:39,680
这时候拔丝好 金黄色
You know it’s ready when you see this golden hue
70
00:02:39,680 --> 00:02:41,760
稀了你看见没有 这就行了
See how clear it is now
71
00:02:41,760 --> 00:02:44,440
这时候可以挂了啊 挂糖了
We can now start glazing
72
00:02:44,440 --> 00:02:46,120
薄薄的一层
a thin layer like this
73
00:02:46,120 --> 00:02:50,400

74
00:02:50,400 --> 00:02:51,480
速度要快
You’ve got to move quick for this step
75
00:02:51,480 --> 00:02:52,800

76
00:02:53,240 --> 00:02:54,920
好 齐活
Alright! It’s all ready
77
00:02:54,920 --> 00:02:56,280
冰糖葫芦
Candied hawthorn
78
00:02:56,280 --> 00:02:57,960
剩下这糖 我加点水
With the leftover glaze, we add some water
79
00:02:57,960 --> 00:02:59,760
这会儿就糖色了
and we’re left with some caramelised sugar
80
00:03:00,840 --> 00:03:02,440
炖个肉啊 炖个排骨
This is good to braise meat with like spare ribs
81
00:03:02,440 --> 00:03:05,160
一举两得了啊 好嘞
Two birds with one stone
82
00:03:05,160 --> 00:03:06,680
师父尝尝
Master, have a taste
83
00:03:06,680 --> 00:03:09,320

84
00:03:09,320 --> 00:03:10,040
听声音
Listen to that sound
85
00:03:10,040 --> 00:03:12,560

86
00:03:12,560 --> 00:03:14,480
嘎嘣脆
It has that crackling crispy sound
87
00:03:14,480 --> 00:03:18,680
慢点 别把核当冰糖咬了
Slow down there, you’re going to end up chewing on the core
88
00:03:18,680 --> 00:03:19,760
大爷咱们小时候
When we were young
89
00:03:19,760 --> 00:03:22,800
要吃这么一串糖葫芦过年了
If you wanted to eat this, we’d have to wait for Chinese New Year
90
00:03:22,800 --> 00:03:25,600
一想40多年过去了大爷
Thinking about it now, it must be around 40 years now right Da Ye?
91
00:03:25,600 --> 00:03:28,640
多少看见糖葫芦有点伤悲
How many of these have I seen since then? Makes me a bit sad
92
00:03:28,640 --> 00:03:30,320
我有30年
Its been 30 years for me
93
00:03:30,320 --> 00:03:32,800
没吃过糖葫芦了
since I last ate this
94
00:03:32,800 --> 00:03:34,120
真像二伯说的
It’s just like Er Bai says
95
00:03:34,120 --> 00:03:38,040
我们想起了儿时的记忆
When we think back to our childhood
96
00:03:38,040 --> 00:03:39,680
鼓励的话 二伯也说了 我也说了
Alright, Er Bai and I have both said words of encouragement
97
00:03:41,240 --> 00:03:43,960
再说一个不足的地儿
Now lets talk about ways we could improve this
98
00:03:43,960 --> 00:03:45,720
我见人家蘸糖葫芦
I saw someone making this once
99
00:03:45,720 --> 00:03:48,240
其实蘸我们这大理石板上
but they were using a marble board
100
00:03:48,240 --> 00:03:51,000
一定要有一个什么厚一点的石头板
It’s best to use a thicker stone board
101
00:03:51,000 --> 00:03:53,720
外边晾一下 给它冻一下
then if you dry the surface and freeze it
102
00:03:53,720 --> 00:03:55,080
或者让它镇凉一点
or press something cold against it
103
00:03:55,080 --> 00:03:58,080
你这个糖往上一浇 唰一流
When the glaze falls off it
104
00:03:58,080 --> 00:04:01,600
正好冰花出来 更精彩
it freezes and creates beautiful ice crystals
105
00:04:01,600 --> 00:04:04,040
然后还有一点不足大爷
and there’s still one last thing, Da Ye
106
00:04:04,040 --> 00:04:06,080
说说说 抢答了
Go on， over to you
107
00:04:06,080 --> 00:04:07,440
我跟你说做这个
When you making this dish
108
00:04:07,440 --> 00:04:09,120
核必须得去
it’s best to remove the core
109
00:04:09,120 --> 00:04:11,160
要不然你让我们吐核多难受啊
otherwise people have to keep spitting it out, not the best eating experience, you know?
110
00:04:11,160 --> 00:04:12,520
这必须得改
You’re not wrong, it’s much better to do it that way
111
00:04:12,520 --> 00:04:14,680
好 感谢师父 感谢大爷 好
Alright, thank you Master. Thank you Da Ye
