### ISSUE TITLE
[老饭骨] 菜团子 - https://youtu.be/xXVPqDovdcc

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1654]
**视频链接**：https://youtu.be/xXVPqDovdcc

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•菜团子】家常菜团子做法，薄皮大馅软糯咸香，个个都圆润润！ |老饭骨

简介
小友们好，大爷今天为大家带来一个家常美味——菜团子。
这道菜是大妈点名要吃的，大爷之前做的也会经常遇到开裂等问题，经过不断摸索，终于找到了一个新的手法，做出来的菜团子薄皮大馅、软糯咸香，各个都圆润润金灿灿！
快点击视频，看看大爷的独家秘方！小友们还有什么想学的家常菜，快在评论区里面告诉我们！

字幕
1
00:00:00,000 --> 00:00:03,240
你看 圆圆乎乎了吧

2
00:00:03,240 --> 00:00:06,360
大团子 还真光溜啊

3
00:00:06,360 --> 00:00:09,480
就用这种办法 保证薄皮儿大馅儿

4
00:00:09,480 --> 00:00:12,720
有很多网友说这菜团子怎么包

5
00:00:12,720 --> 00:00:15,080
我创造了一个新的手法

6
00:00:15,080 --> 00:00:17,200
其实我也包不是特别专业

7
00:00:17,200 --> 00:00:18,840
我们家是这样

8
00:00:18,840 --> 00:00:20,720
这个棒子面要烫棒子面

9
00:00:20,720 --> 00:00:24,120
烫一半留一半

10
00:00:24,120 --> 00:00:26,000
大爷一瞧很专业啊

11
00:00:26,000 --> 00:00:27,800
你看 二伯也懂

12
00:00:27,800 --> 00:00:29,600
烫一半

13
00:00:29,600 --> 00:00:32,760
今天这棒子面就比较细

14
00:00:32,760 --> 00:00:35,280
还筋道

15
00:00:35,280 --> 00:00:37,160
好了 这就可以了

16
00:00:37,160 --> 00:00:39,720
但是我们还要搁一些凉水

17
00:00:39,720 --> 00:00:41,960
把它和匀了 和滋润了

18
00:00:41,960 --> 00:00:45,280
热水烫起到了决定性作用 黏糊了

19
00:00:45,280 --> 00:00:46,840
以前特别逗

20
00:00:46,840 --> 00:00:49,560
十几岁我就会包这个菜团子

21
00:00:49,560 --> 00:00:53,480
07年 大妈特别想吃个菜团子

22
00:00:53,480 --> 00:00:55,600
完了以后我说没问题

23
00:00:55,600 --> 00:00:58,720
我给你包个菜团子保证是薄皮大馅

24
00:00:58,720 --> 00:01:00,080
想吃我说包一个吧

25
00:01:00,080 --> 00:01:02,080
是棒子面的问题

26
00:01:02,080 --> 00:01:04,240
是我的手艺问题

27
00:01:04,240 --> 00:01:06,320
一包一裂口 一包一裂口

28
00:01:06,320 --> 00:01:07,720
然后我就拿面补

29
00:01:07,720 --> 00:01:10,640
越补这面 这团子越大

30
00:01:10,640 --> 00:01:12,440
咬了一口没咬着馅

31
00:01:12,440 --> 00:01:15,440
我们家老伴说了 瞧你这吹

32
00:01:15,440 --> 00:01:17,920
隋坡再给我来点水 好嘞

33
00:01:17,920 --> 00:01:19,840
但是我还是不死心

34
00:01:19,840 --> 00:01:22,080
过几天我说我再给你包一回

35
00:01:22,080 --> 00:01:23,440
这回保证薄皮大馅

36
00:01:23,440 --> 00:01:25,480
我创造了一个新的手法

37
00:01:25,480 --> 00:01:27,040
是哪儿启发了我呢

38
00:01:27,040 --> 00:01:28,640
一会我给大家展示一下

39
00:01:29,360 --> 00:01:32,680
这个面好了 然后让它饧一饧

40
00:01:32,680 --> 00:01:35,080
下一步咱弄馅

41
00:01:35,080 --> 00:01:37,360
你看 这个红皮萝卜

42
00:01:37,360 --> 00:01:38,920
我们常说的叫卞萝卜

43
00:01:38,920 --> 00:01:40,200
这是个大圆的

44
00:01:40,200 --> 00:01:42,920
这儿就用这个萝卜来擦的丝

45
00:01:42,920 --> 00:01:45,480
这胡萝卜也是擦

46
00:01:45,480 --> 00:01:47,800
这个是略焯 不要焯太大发了

47
00:01:47,800 --> 00:01:48,840
略焯

48
00:01:48,840 --> 00:01:50,120
好了

49
00:01:50,120 --> 00:01:51,600
冲凉

50
00:01:51,600 --> 00:01:57,400
你看胡萝卜白萝卜出完水了 冲凉了

51
00:01:57,400 --> 00:01:58,960
给它挤挤水

52
00:02:00,560 --> 00:02:00,960

53
00:02:01,960 --> 00:02:03,760
木耳

54
00:02:03,760 --> 00:02:05,240
这个蛋皮丝可以

55
00:02:05,240 --> 00:02:08,720
也可以炒点碎碎的鸡蛋

56
00:02:08,720 --> 00:02:10,800

57
00:02:10,800 --> 00:02:12,560
二伯 来

58
00:02:12,560 --> 00:02:15,480
把萝卜丝揽两刀

59
00:02:15,480 --> 00:02:16,120

60
00:02:16,520 --> 00:02:20,440
看着啊 粉丝准备好了 油也热了

61
00:02:20,440 --> 00:02:21,120

62
00:02:21,120 --> 00:02:23,840
看见了吧 特别简单

63
00:02:23,840 --> 00:02:26,920
这就好了 再来

64
00:02:29,560 --> 00:02:31,040
就搁这儿就行

65
00:02:31,040 --> 00:02:33,400
一会儿给它斩一斩

66
00:02:33,400 --> 00:02:35,320
或者让它晾一晾拿手一揉

67
00:02:36,400 --> 00:02:38,360
炸完以后它就已经熟了

68
00:02:38,360 --> 00:02:40,400
还香呢炸完了

69
00:02:40,400 --> 00:02:42,600
你看拿刀轻轻一斩

70
00:02:42,600 --> 00:02:46,960
在素馅里边 这粉丝是必须要给的

71
00:02:46,960 --> 00:02:50,640
为什么呢 有的素菜它会出水

72
00:02:50,640 --> 00:02:53,920
出水怎么办 搁点粉丝

73
00:02:53,920 --> 00:02:56,200
另外它还产生了香气

74
00:02:56,200 --> 00:02:58,720
好了 现在要调味了

75
00:02:58,720 --> 00:03:00,560
素馅调味的不加酱油

76
00:03:00,560 --> 00:03:04,680
先把盐加上 这盐要不能少

77
00:03:04,680 --> 00:03:06,080
因为团子（有面）

78
00:03:06,080 --> 00:03:09,240
一勺不够 两勺 两勺半盐

79
00:03:09,240 --> 00:03:13,000
盐搁完了 白胡椒

80
00:03:13,000 --> 00:03:13,760

81
00:03:13,760 --> 00:03:15,240
香油

82
00:03:16,320 --> 00:03:18,480
馅儿一好 咱就开始了

83
00:03:18,480 --> 00:03:20,840
来 二伯给倒上 倒点味精

84
00:03:22,480 --> 00:03:25,760
手拌馅是最快的 而且还拌的匀

85
00:03:25,760 --> 00:03:27,400
来点葱姜

86
00:03:27,400 --> 00:03:31,560
还得来点油吗 来油啊

87
00:03:31,560 --> 00:03:32,760
还得炼点儿油呢

88
00:03:32,760 --> 00:03:35,560
搁点葱尾巴 香葱

89
00:03:35,560 --> 00:03:37,240
香菜 搁个大料

90
00:03:37,240 --> 00:03:39,720

91
00:03:39,720 --> 00:03:43,360
还很香这个油 很香 再搁点料油

92
00:03:43,360 --> 00:03:46,080
我还得讲刚才的故事 接着讲

93
00:03:46,080 --> 00:03:48,360
我就奇怪了

94
00:03:48,360 --> 00:03:50,240
我说我现在厨艺有点下降了

95
00:03:50,240 --> 00:03:53,640
后来我想了个诀窍 什么诀窍呢

96
00:03:53,640 --> 00:03:56,240
有一次 正好什么启发了我呢

97
00:03:56,240 --> 00:03:58,040
包一个一斤半的狮子头

98
00:03:58,040 --> 00:04:01,840
里边还要上馅儿 谁也包不上去

99
00:04:01,840 --> 00:04:03,920
我忽然间就启发了

100
00:04:03,920 --> 00:04:07,040
找一个保鲜膜找一大碗

101
00:04:07,040 --> 00:04:10,680
把肉馅打好了以后铺在保鲜膜上

102
00:04:10,680 --> 00:04:13,160
给它抹圆乎了抹均匀了

103
00:04:13,160 --> 00:04:16,000
然后把炒好的素馅装进去

104
00:04:16,000 --> 00:04:18,040
这是一斤（肉）馅儿啊

105
00:04:18,040 --> 00:04:19,640
然后再称了半斤馅儿

106
00:04:19,640 --> 00:04:22,800
再把底儿一封 拿保鲜膜一兜

107
00:04:22,800 --> 00:04:24,960
二伯 这么大一狮子头

108
00:04:24,960 --> 00:04:28,320
包的好好的光溜溜的

109
00:04:28,320 --> 00:04:29,160
我就想起这个来了

110
00:04:29,160 --> 00:04:30,320
今天呢

111
00:04:30,320 --> 00:04:33,120
我这个方法给大家重现一下

112
00:04:33,120 --> 00:04:35,880
你看找一个合适的碗

113
00:04:35,880 --> 00:04:38,600
把这面搁里头

114
00:04:38,600 --> 00:04:44,040
首先要把碗底儿的皮给它抹的均匀

115
00:04:45,640 --> 00:04:48,000
你看看 都已经成一碗状了

116
00:04:48,000 --> 00:04:50,480
这时候我们往里边盛馅儿

117
00:04:50,480 --> 00:04:54,440
这个菜团子的馅儿得足实

118
00:04:54,440 --> 00:04:58,000
你看啊 装好了吧

119
00:04:58,000 --> 00:05:02,280
一起一提了 出来了

120
00:05:02,280 --> 00:05:07,240
首先我相信我底下这个皮儿是薄的

121
00:05:07,240 --> 00:05:09,880
然后我们一点一点的

122
00:05:09,880 --> 00:05:12,240
拢的时候手里沾点水

123
00:05:12,240 --> 00:05:15,560
要不它粘的哪儿都是 馅儿都跑了

124
00:05:15,560 --> 00:05:17,520
一边拢着一边蹲

125
00:05:18,600 --> 00:05:22,440
越蹲越收口

126
00:05:22,440 --> 00:05:25,280
那天我看什么大饼 肉饼

127
00:05:25,280 --> 00:05:29,080
那疙瘩面不很多 那块肉可不少

128
00:05:29,080 --> 00:05:31,600
三团两团

129
00:05:31,600 --> 00:05:34,080
把这一大块肉给团进去了

130
00:05:34,080 --> 00:05:36,640
二伯看见了吧 你看你看

131
00:05:36,640 --> 00:05:38,360
这口越来越小

132
00:05:39,680 --> 00:05:43,320
这得有耐心 大爷的耐心够大的

133
00:05:43,320 --> 00:05:44,960
一点一点

134
00:05:44,960 --> 00:05:45,280

135
00:05:45,280 --> 00:05:49,200
你看也不漏

136
00:05:50,600 --> 00:05:51,960
圆圆乎乎的吧

137
00:05:51,960 --> 00:05:55,440
上锅了 一开锅十五分钟

138
00:05:55,440 --> 00:05:57,760
得嘞 我看时间 您歇会

139
00:05:57,760 --> 00:06:00,200
二伯 蒸了十五分钟

140
00:06:00,200 --> 00:06:01,640
闷了有一分多钟

141
00:06:01,640 --> 00:06:03,920
薄皮大馅 走着

142
00:06:03,920 --> 00:06:07,520
还真光溜 不错

143
00:06:07,520 --> 00:06:10,360
晾晾晾晾 下不了手

144
00:06:10,360 --> 00:06:14,960
好啦 大团子

145
00:06:14,960 --> 00:06:19,760
黄澄澄金灿灿的大团子

146
00:06:19,760 --> 00:06:20,840
二伯先吃

147
00:06:20,840 --> 00:06:23,560

148
00:06:23,560 --> 00:06:26,160
这面嚼起来还有点糯

149
00:06:26,160 --> 00:06:28,520
关键什么

150
00:06:28,520 --> 00:06:31,000
这馅儿的咸淡味拿捏的特别好

151
00:06:31,000 --> 00:06:35,360
比馒头进去还舒服

152
00:06:35,360 --> 00:06:37,840
谢谢二伯

153
00:06:37,840 --> 00:06:42,720
隋坡呢 我吃俩了都 饿了你是

154
00:06:42,720 --> 00:06:44,680
难以形容的好吃

155
00:06:44,680 --> 00:06:46,120
特别是二伯炸的料油搁里边

156
00:06:46,120 --> 00:06:49,120
特别的香 油润润的

157
00:06:49,120 --> 00:06:51,160
料油的香味特别足

158
00:06:51,160 --> 00:06:53,280
一般咱们会噎嗓子

159
00:06:53,280 --> 00:06:56,400
但是他这个出溜就下去了

160
00:06:56,400 --> 00:06:59,240
非常舒服 很滑

161
00:06:59,240 --> 00:07:03,000
为你点赞 谢谢二伯 谢谢隋坡

162
00:07:03,000 --> 00:07:04,640
对不住了 中午我有饭了
```

**Comment by Yingzhang1122** [comment]
#标题（翻译主要意思即可，不要超过 100 个字符）
#【国宴大师•菜团子】家常菜团子做法，薄皮大馅软糯咸香，个个都圆润润！ |老饭骨
State Banquet Master Chef: Steamed Vegetable Buns

#简介
#小友们好，大爷今天为大家带来一个家常美味——菜团子。
#这道菜是大妈点名要吃的，大爷之前做的也会经常遇到开裂等问题，经过不断摸索，终于找到了一个新的手法，做出来的菜团子薄皮大馅、软糯咸香，各个都圆润润金灿灿！
#快点击视频，看看大爷的独家秘方！小友们还有什么想学的家常菜，快在评论区里面告诉我们！
Hello friends! Da Ye brings a home-made dish today: steamed vegetable buns.
This dish was ordered by Da Ma. Da Ye encountered some problems, such as cracking, when he cooked this dish before. However, he invented a new technique after exploration and made perfect golden yellow steamed buns, which are full of stuffing, soft, and delicious.
Watch the video now to learn Da Ye's unique trick! Please also tell us what home-made dishes you want to learn - just comment!

#字幕
1
00:00:00,000 --> 00:00:03,240
#你看 圆圆乎乎了吧
See? They are spherical now

2
00:00:03,240 --> 00:00:06,360
#大团子 还真光溜啊
Big steamed buns. Really smooth surface

3
00:00:06,360 --> 00:00:09,480
#就用这种办法 保证薄皮儿大馅儿
In this way, you will definitely make buns with thin skin and full stuffing

4
00:00:09,480 --> 00:00:12,720
#有很多网友说这菜团子怎么包
Some friends asked me how to make steamed vegetable buns

5
00:00:12,720 --> 00:00:15,080
#我创造了一个新的手法
I invented a new technique

6
00:00:15,080 --> 00:00:17,200
#其实我也包不是特别专业
Actually I am not very professional in making buns

7
00:00:17,200 --> 00:00:18,840
#我们家是这样
In my home, it was like this

8
00:00:18,840 --> 00:00:20,720
#这个棒子面要烫棒子面
The cornmeal... You need to add boiling water

9
00:00:20,720 --> 00:00:24,120
#烫一半留一半
Mix half of the cornmeal with boiling water and keep the other half

10
00:00:24,120 --> 00:00:26,000
#大爷一瞧很专业啊
That looks professional, Da Ye

11
00:00:26,000 --> 00:00:27,800
#你看 二伯也懂
Er Bai knows this as well

12
00:00:27,800 --> 00:00:29,600
#烫一半
Mix half of the cornmeal with boiling water

13
00:00:29,600 --> 00:00:32,760
#今天这棒子面就比较细
The cornmeal here is very fine

14
00:00:32,760 --> 00:00:35,280
#还筋道
and somewhat tough

15
00:00:35,280 --> 00:00:37,160
#好了 这就可以了
Ok. That's done

16
00:00:37,160 --> 00:00:39,720
#但是我们还要搁一些凉水
But we still need to add some cold water

17
00:00:39,720 --> 00:00:41,960
#把它和匀了 和滋润了
To mix it up until it looks shiny

18
00:00:41,960 --> 00:00:45,280
#热水烫起到了决定性作用 黏糊了
Boiling water is the key. It's sticky now

19
00:00:45,280 --> 00:00:46,840
#以前特别逗
This is a funny story

20
00:00:46,840 --> 00:00:49,560
#十几岁我就会包这个菜团子
I could make this when I was a teenager

21
00:00:49,560 --> 00:00:53,480
#07年 大妈特别想吃个菜团子
In 2007, Da Ma really wanted to have this dish

22
00:00:53,480 --> 00:00:55,600
#完了以后我说没问题
I was like, no problem!

23
00:00:55,600 --> 00:00:58,720
#我给你包个菜团子保证是薄皮大馅
Let me make it for you. I am sure it must be full of stuffing with thin skin

24
00:00:58,720 --> 00:01:00,080
#想吃我说包一个吧
Then I made some (steamed vegetable buns)

25
00:01:00,080 --> 00:01:02,080
#是棒子面的问题
I didn't know if the problem was with the cornmeal

26
00:01:02,080 --> 00:01:04,240
#是我的手艺问题
or my cooking ability

27
00:01:04,240 --> 00:01:06,320
#一包一裂口 一包一裂口
There were crackings on each of them!

28
00:01:06,320 --> 00:01:07,720
#然后我就拿面补
Then I filled the crackings with wheat flour

29
00:01:07,720 --> 00:01:10,640
#越补这面 这团子越大
But the steamed buns were getting bigger and bigger

30
00:01:10,640 --> 00:01:12,440
#咬了一口没咬着馅
You could not even touch the stuffing on your first bite 

31
00:01:12,440 --> 00:01:15,440
#我们家老伴说了 瞧你这吹
My wife was like, 'You must be bluffing!'

32
00:01:15,440 --> 00:01:17,920
#隋坡再给我来点水 好嘞
Sui Po, get me some more water. Ok!

33
00:01:17,920 --> 00:01:19,840
#但是我还是不死心
But I didn't give up

34
00:01:19,840 --> 00:01:22,080
#过几天我说我再给你包一回
Several days later, I told her that I would make the buns again

35
00:01:22,080 --> 00:01:23,440
#这回保证薄皮大馅
I promised that they would be full of stuffing with thin skin

36
00:01:23,440 --> 00:01:25,480
#我创造了一个新的手法
I invented a new technique

37
00:01:25,480 --> 00:01:27,040
#是哪儿启发了我呢
What inspired me?

38
00:01:27,040 --> 00:01:28,640
#一会我给大家展示一下
I will show you later

39
00:01:29,360 --> 00:01:32,680
#这个面好了 然后让它饧一饧
The cornmeal is ready. Leave it to rest

40
00:01:32,680 --> 00:01:35,080
#下一步咱弄馅
Let's prepare the stuffing next

41
00:01:35,080 --> 00:01:37,360
#你看 这个红皮萝卜
Look. The red-skin radish here

42
00:01:37,360 --> 00:01:38,920
#我们常说的叫卞萝卜
We also refer to it as 'Bian' radish

43
00:01:38,920 --> 00:01:40,200
#这是个大圆的
This is a round one

44
00:01:40,200 --> 00:01:42,920
#这儿就用这个萝卜来擦的丝
These shreds are from the radish

45
00:01:42,920 --> 00:01:45,480
#这胡萝卜也是擦
Use the kitchen shredder to shred the carrot as well

46
00:01:45,480 --> 00:01:47,800
#这个是略焯 不要焯太大发了
Blanch it shortly. Do not blanch for too long

47
00:01:47,800 --> 00:01:48,840
#略焯
Just a little while

48
00:01:48,840 --> 00:01:50,120
#好了
Done

49
00:01:50,120 --> 00:01:51,600
#冲凉
Rinse with cold water

50
00:01:51,600 --> 00:01:57,400
#你看胡萝卜白萝卜出完水了 冲凉了
After rinsing the shredded radish with water

51
00:01:57,400 --> 00:01:58,960
#给它挤挤水
Squeeze the water out

52
00:02:00,560 --> 00:02:00,960

53
00:02:01,960 --> 00:02:03,760
#木耳
Black wood ear

54
00:02:03,760 --> 00:02:05,240
#这个蛋皮丝可以
Shredded fried egg

55
00:02:05,240 --> 00:02:08,720
#也可以炒点碎碎的鸡蛋
You can replace it with eggs that are fried into tiny bits

56
00:02:08,720 --> 00:02:10,800

57
00:02:10,800 --> 00:02:12,560
#二伯 来
Er bai, come on

58
00:02:12,560 --> 00:02:15,480
#把萝卜丝揽两刀
Simply chop the shredded radish

59
00:02:15,480 --> 00:02:16,120

60
00:02:16,520 --> 00:02:20,440
#看着啊 粉丝准备好了 油也热了
Look. The vermicelli is ready. The oil is also hot

61
00:02:20,440 --> 00:02:21,120

62
00:02:21,120 --> 00:02:23,840
#看见了吧 特别简单
See that? Very simple

63
00:02:23,840 --> 00:02:26,920
#这就好了 再来
This is done. Again

64
00:02:29,560 --> 00:02:31,040
#就搁这儿就行
Place it here

65
00:02:31,040 --> 00:02:33,400
#一会儿给它斩一斩
Let' s cut it later

66
00:02:33,400 --> 00:02:35,320
#或者让它晾一晾拿手一揉
Or cool it down and crush with your hand

67
00:02:36,400 --> 00:02:38,360
#炸完以后它就已经熟了
It's already cooked after frying

68
00:02:38,360 --> 00:02:40,400
#还香呢炸完了
It also smells better

69
00:02:40,400 --> 00:02:42,600
#你看拿刀轻轻一斩
Look. Simply chop it with the knife

70
00:02:42,600 --> 00:02:46,960
#在素馅里边 这粉丝是必须要给的
In vegetable stuffing, you must have vermicelli

71
00:02:46,960 --> 00:02:50,640
#为什么呢 有的素菜它会出水
Why? Some vegetables may be juicy and will give out moisture

72
00:02:50,640 --> 00:02:53,920
#出水怎么办 搁点粉丝
How to deal with that? Add some vermicelli

73
00:02:53,920 --> 00:02:56,200
#另外它还产生了香气
Also the vermicelli enhances the aroma

74
00:02:56,200 --> 00:02:58,720
#好了 现在要调味了
Good. Now let's season it

75
00:02:58,720 --> 00:03:00,560
#素馅调味的不加酱油
Soy sauce does not go well with vegetable stuffing

76
00:03:00,560 --> 00:03:04,680
#先把盐加上 这盐要不能少
Add salt first. Not too little

77
00:03:04,680 --> 00:03:06,080
#因为团子（有面）
Since the buns (are made of cornmeal and are bland)

78
00:03:06,080 --> 00:03:09,240
#一勺不够 两勺 两勺半盐
One teaspoon is not enough. Two, two and a half teaspoons of salt

79
00:03:09,240 --> 00:03:13,000
#盐搁完了 白胡椒
After the salt, white pepper powder

80
00:03:13,000 --> 00:03:13,760

81
00:03:13,760 --> 00:03:15,240
#香油
Sesame oil

82
00:03:16,320 --> 00:03:18,480
#馅儿一好 咱就开始了
Let's start when the stuffing is ready

83
00:03:18,480 --> 00:03:20,840
#来 二伯给倒上 倒点味精
Come on, Er Bai. Add some MSG

84
00:03:22,480 --> 00:03:25,760
#手拌馅是最快的 而且还拌的匀
It's the fastest to mix the stuffing with your hands. Also it's gonna be more uniform

85
00:03:25,760 --> 00:03:27,400
#来点葱姜
Some ginger and green onion

86
00:03:27,400 --> 00:03:31,560
#还得来点油吗 来油啊
Some more oil? Yes please

87
00:03:31,560 --> 00:03:32,760
#还得炼点儿油呢
Let's prepare some oil as well

88
00:03:32,760 --> 00:03:35,560
#搁点葱尾巴 香葱
Some green onion leaves. Scallion

89
00:03:35,560 --> 00:03:37,240
#香菜 搁个大料
Coriander. A star anise

90
00:03:37,240 --> 00:03:39,720

91
00:03:39,720 --> 00:03:43,360
#还很香这个油 很香 再搁点料油
The oil is very aromatic. Some more oil please

92
00:03:43,360 --> 00:03:46,080
#我还得讲刚才的故事 接着讲
Let me continue to tell my previous story

93
00:03:46,080 --> 00:03:48,360
#我就奇怪了
I was wondering

94
00:03:48,360 --> 00:03:50,240
#我说我现在厨艺有点下降了
I was like, 'Is my cooking ability dropping now?'

95
00:03:50,240 --> 00:03:53,640
#后来我想了个诀窍 什么诀窍呢
Later on I invented a trick. What was it?

96
00:03:53,640 --> 00:03:56,240
#有一次 正好什么启发了我呢
There was one time... when I was inspired

97
00:03:56,240 --> 00:03:58,040
#包一个一斤半的狮子头
Making a 750-g Shi Zi Tou (Literally lion head, braised pork ball in brown sauce)

98
00:03:58,040 --> 00:04:01,840
#里边还要上馅儿 谁也包不上去
We needed to put stuffing inside as well. No one could do it

99
00:04:01,840 --> 00:04:03,920
#我忽然间就启发了
It suddenly came to my mind that

100
00:04:03,920 --> 00:04:07,040
#找一个保鲜膜找一大碗
I found a piece of plastic wrap and a big bowl

101
00:04:07,040 --> 00:04:10,680
#把肉馅打好了以后铺在保鲜膜上
Placed the minced meat on the plastic wrap

102
00:04:10,680 --> 00:04:13,160
#给它抹圆乎了抹均匀了
Spreaded it evenly

103
00:04:13,160 --> 00:04:16,000
#然后把炒好的素馅装进去
Then placed cooked vegetable stuffing inside

104
00:04:16,000 --> 00:04:18,040
#这是一斤（肉）馅儿啊
That was 500 grams of minced meat

105
00:04:18,040 --> 00:04:19,640
#然后再称了半斤馅儿
Then I got 250 more grams of minced meat

106
00:04:19,640 --> 00:04:22,800
#再把底儿一封 拿保鲜膜一兜
to seal the bottom. Then I wrapped up the plastic wrap

107
00:04:22,800 --> 00:04:24,960
#二伯 这么大一狮子头
Er Bai, the lion head was like this big

108
00:04:24,960 --> 00:04:28,320
#包的好好的光溜溜的
It was perfect and smooth

109
00:04:28,320 --> 00:04:29,160
#我就想起这个来了
This inspired me

110
00:04:29,160 --> 00:04:30,320
#今天呢
Today

111
00:04:30,320 --> 00:04:33,120
#我这个方法给大家重现一下
I will show you this technique

112
00:04:33,120 --> 00:04:35,880
#你看找一个合适的碗
Look. Find a right bowl

113
00:04:35,880 --> 00:04:38,600
#把这面搁里头
Put the cornmeal inside

114
00:04:38,600 --> 00:04:44,040
#首先要把碗底儿的皮给它抹的均匀
Make sure the skin underneath is even in thickness

115
00:04:45,640 --> 00:04:48,000
#你看看 都已经成一碗状了
Look. It already looks like a bowl

116
00:04:48,000 --> 00:04:50,480
#这时候我们往里边盛馅儿
Let's add stuffing now

117
00:04:50,480 --> 00:04:54,440
#这个菜团子的馅儿得足实
You need enough stuffing for the steamed bun

118
00:04:54,440 --> 00:04:58,000
#你看啊 装好了吧
See that? The bun is filled with stuffing

119
00:04:58,000 --> 00:05:02,280
#一起一提了 出来了
Lift it up. Out of the bowl

120
00:05:02,280 --> 00:05:07,240
#首先我相信我底下这个皮儿是薄的
Firstly, I am sure that the skin at the bottom is thin

121
00:05:07,240 --> 00:05:09,880
#然后我们一点一点的
Then let's seal it, little-by-little

122
00:05:09,880 --> 00:05:12,240
#拢的时候手里沾点水
Apply some water in your hand

123
00:05:12,240 --> 00:05:15,560
#要不它粘的哪儿都是 馅儿都跑了
Otherwise it's gonna stick to everywhere. The stuffing will be gone

124
00:05:15,560 --> 00:05:17,520
#一边拢着一边蹲
Close it slowly while 'sitting' it to the bottom

125
00:05:18,600 --> 00:05:22,440
#越蹲越收口
The opening will be closed as you 'sit' it

126
00:05:22,440 --> 00:05:25,280
#那天我看什么大饼 肉饼
I was watching (others making) meat pies the other day

127
00:05:25,280 --> 00:05:29,080
#那疙瘩面不很多 那块肉可不少
I noticed that the dough was small, but there was a lot of meat

128
00:05:29,080 --> 00:05:31,600
#三团两团
But somehow, as he 'sat' the meat stuffing into the dough

129
00:05:31,600 --> 00:05:34,080
#把这一大块肉给团进去了
The whole pile of meat stuffing was closed in the skin

130
00:05:34,080 --> 00:05:36,640
#二伯看见了吧 你看你看
Er Bai, see that?

131
00:05:36,640 --> 00:05:38,360
#这口越来越小
The opening is getting smaller and smaller

132
00:05:39,680 --> 00:05:43,320
#这得有耐心 大爷的耐心够大的
You need to be patient. Da Ye has great patience

133
00:05:43,320 --> 00:05:44,960
#一点一点
Little by little

134
00:05:44,960 --> 00:05:45,280

135
00:05:45,280 --> 00:05:49,200
#你看也不漏
Look, no cracking

136
00:05:50,600 --> 00:05:51,960
#圆圆乎乎的吧
They are spherical now

137
00:05:51,960 --> 00:05:55,440
#上锅了 一开锅十五分钟
Into the pot. 15 minutes after boiling

138
00:05:55,440 --> 00:05:57,760
#得嘞 我看时间 您歇会
Okay. I'll keep an eye on the time and you can have a rest

139
00:05:57,760 --> 00:06:00,200
#二伯 蒸了十五分钟
Er Bai. Steamed for 15 minutes,

140
00:06:00,200 --> 00:06:01,640
#闷了有一分多钟
rest with the lid closed for about 1-2 minutes

141
00:06:01,640 --> 00:06:03,920
#薄皮大馅 走着
Full stuffing, thin skin. Let's go!

142
00:06:03,920 --> 00:06:07,520
#还真光溜 不错
So smooth. Looks good

143
00:06:07,520 --> 00:06:10,360
#晾晾晾晾 下不了手
Cool it for a while. Can't touch it now

144
00:06:10,360 --> 00:06:14,960
#好啦 大团子
Done. Big steamed buns!

145
00:06:14,960 --> 00:06:19,760
#黄澄澄金灿灿的大团子
Golden yellow buns!

146
00:06:19,760 --> 00:06:20,840
#二伯先吃
Er Bai, take a bite first.

147
00:06:20,840 --> 00:06:23,560

148
00:06:23,560 --> 00:06:26,160
#这面嚼起来还有点糯
The cornmeal is somewhat soft

149
00:06:26,160 --> 00:06:28,520
#关键什么
The key is

150
00:06:28,520 --> 00:06:31,000
#这馅儿的咸淡味拿捏的特别好
The savory taste is perfect

151
00:06:31,000 --> 00:06:35,360
#比馒头进去还舒服
Feels even better than steamed bread

152
00:06:35,360 --> 00:06:37,840
#谢谢二伯
Thank you, Er Bai

153
00:06:37,840 --> 00:06:42,720
#隋坡呢 我吃俩了都 饿了你是
-Sui Po, what about you? -I have had two already. - You must be hungry

154
00:06:42,720 --> 00:06:44,680
#难以形容的好吃
Unbelievably delicious

155
00:06:44,680 --> 00:06:46,120
#特别是二伯炸的料油搁里边
Especially, with Er Bai's aromatic oil

156
00:06:46,120 --> 00:06:49,120
#特别的香 油润润的
The steamed buns are so aromatic and smooth

157
00:06:49,120 --> 00:06:51,160
#料油的香味特别足
The aroma of the oil is so strong

158
00:06:51,160 --> 00:06:53,280
#一般咱们会噎嗓子
You might choke up on normal steamed buns

159
00:06:53,280 --> 00:06:56,400
#但是他这个出溜就下去了
But this one simply goes down your gullet

160
00:06:56,400 --> 00:06:59,240
#非常舒服 很滑
Very comfortable. So smooth

161
00:06:59,240 --> 00:07:03,000
#为你点赞 谢谢二伯 谢谢隋坡
Thumb up for you! Thanks, Er Bai! Thanks, Sui Po!

162
00:07:03,000 --> 00:07:04,640
#对不住了 中午我有饭了
Sorry about that. Got food for my lunch #这里意思是要打包带走？
