### ISSUE TITLE
[老饭骨] 干烧冬笋- https://youtu.be/DIG4fs7J818

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1656]
**视频链接**：https://youtu.be/DIG4fs7J818

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•干烧冬笋】爽脆咸香，冬季必吃的应季菜！传统手法细节满满！ |老饭骨

简介
小友们好，今天带给大家一道冬季必吃的应季菜——干烧冬笋。
冬笋其实不太入味，配上炸过的雪菜叶，非常酥香脆嫩。
这道菜非常家常，做法也不难，但是细节还是很多的，大爷之前分享过的“劈柴块”刀功，大家还有印象吗？
还有什么冬季的时令菜大家想吃的？留言给老饭骨，大爷二伯教你们做！

字幕
1
00:00:00,000 --> 00:00:02,800
北方人吃笋吃的少

2
00:00:02,800 --> 00:00:05,120
有很多人也不知道怎么做

3
00:00:05,680 --> 00:00:07,840
咱们要做一个干烧冬笋

4
00:00:10,160 --> 00:00:12,080
你看雪里蕻的叶

5
00:00:12,120 --> 00:00:14,680
经过这一炸你看 酥脆

6
00:00:14,760 --> 00:00:16,920
这个是应季的

7
00:00:16,920 --> 00:00:19,120
先剌一刀给剌一刀剥皮

8
00:00:19,120 --> 00:00:21,120
外皮很老

9
00:00:21,160 --> 00:00:22,880
但是越剥里边就越嫩了

10
00:00:23,080 --> 00:00:25,000
这个皮有几个说法

11
00:00:25,000 --> 00:00:26,200
这边的皮

12
00:00:26,240 --> 00:00:27,520
就像这一块的皮

13
00:00:27,600 --> 00:00:28,640
这可以做菜的

14
00:00:29,080 --> 00:00:30,040
这个皮 

15
00:00:30,040 --> 00:00:31,560
这叫笋衣

16
00:00:32,280 --> 00:00:33,760
你像比如我们做的酸辣汤

17
00:00:34,080 --> 00:00:35,920
搁点豆腐片

18
00:00:36,000 --> 00:00:37,560
笋衣片

19
00:00:37,560 --> 00:00:39,800
这个特别嫩 好东西

20
00:00:39,800 --> 00:00:40,880
可以直接吃吗

21
00:00:40,880 --> 00:00:43,080
不能直接吃 一会还得处理一下

22
00:00:43,080 --> 00:00:46,480
我们把这笋给它修成这种窝头状

23
00:00:46,520 --> 00:00:48,120
外边刮得光溜的

24
00:00:49,520 --> 00:00:50,600
我们给它煮上

25
00:00:51,120 --> 00:00:52,960
凉水热水都行

26
00:00:53,000 --> 00:00:54,520
煮15分钟

27
00:00:54,640 --> 00:00:56,440
这边煮着咱们切点小料

28
00:00:57,600 --> 00:00:58,520
雪菜

29
00:00:58,520 --> 00:01:00,520
把这雪菜叶展开

30
00:01:00,640 --> 00:01:03,360
一炸垫底下碧绿碧绿的倍漂亮

31
00:01:03,560 --> 00:01:05,640
老师傅老手法

32
00:01:06,400 --> 00:01:08,760
这梗别太多 太多它咸

33
00:01:08,760 --> 00:01:10,560
这雪菜用的时候呢

34
00:01:10,760 --> 00:01:12,520
要洗洗它 泡泡它

35
00:01:12,640 --> 00:01:14,040
切成小丁状

36
00:01:15,400 --> 00:01:17,200
别死乞白赖挤

37
00:01:17,200 --> 00:01:19,440
要吃雪菜的脆嫩

38
00:01:19,440 --> 00:01:21,200
要把这水都给挤干了

39
00:01:21,240 --> 00:01:22,680
它就不脆了

40
00:01:23,320 --> 00:01:25,160
咱们这边煮着

41
00:01:25,920 --> 00:01:28,480
这边可以炸雪菜了

42
00:01:28,680 --> 00:01:30,640
油温四成热

43
00:01:30,800 --> 00:01:32,360
你看啊

44
00:01:33,400 --> 00:01:36,280
立马就伸展开了

45
00:01:36,480 --> 00:01:40,520
炸的是雪菜叶 碧绿碧绿的

46
00:01:40,800 --> 00:01:43,160
好看吧 行

47
00:01:43,440 --> 00:01:46,520
好了大爷 行了

48
00:01:46,520 --> 00:01:48,800
先关火 这边晾着

49
00:01:48,960 --> 00:01:51,040
晾完了它才酥脆

50
00:01:51,600 --> 00:01:52,760
冬笋好了

51
00:01:52,800 --> 00:01:54,360
因为你没煮的时候

52
00:01:54,360 --> 00:01:56,560
一切它就容易炸了

53
00:01:56,560 --> 00:01:58,040
就不容易出刀口

54
00:01:58,040 --> 00:01:59,760
现在煮完了以后你看

55
00:02:00,080 --> 00:02:01,920
一看就透了

56
00:02:01,920 --> 00:02:04,680
在大爷学堂里面有个刀工叫劈柴块

57
00:02:04,680 --> 00:02:06,120
什么叫劈柴块

58
00:02:06,120 --> 00:02:07,560
看着啊 不是切了

59
00:02:07,560 --> 00:02:10,440
要把它这个丝纹路给拍松

60
00:02:10,720 --> 00:02:12,520
现在已经松了你看

61
00:02:12,840 --> 00:02:14,120
隋坡你看着啊

62
00:02:14,120 --> 00:02:15,240
剌开一口

63
00:02:15,240 --> 00:02:16,720
劈柴

64
00:02:16,880 --> 00:02:18,800
到这就不能切了

65
00:02:19,280 --> 00:02:20,480
撕

66
00:02:22,000 --> 00:02:23,320
拢住了

67
00:02:23,640 --> 00:02:25,160
干烧冬笋有好多

68
00:02:25,160 --> 00:02:27,120
有好多社会餐饮也在做

69
00:02:27,480 --> 00:02:28,840
但是刀工处理上

70
00:02:28,840 --> 00:02:30,720
他的方法就错了

71
00:02:30,720 --> 00:02:32,400
这叫劈柴块

72
00:02:33,240 --> 00:02:35,280
这样做的最大好处 便于入味

73
00:02:35,320 --> 00:02:36,880
还有什么便于烹调

74
00:02:36,880 --> 00:02:38,280
二伯点火

75
00:02:40,360 --> 00:02:42,000
二伯 你看都齐了

76
00:02:42,000 --> 00:02:43,800
整齐了 刀工一致

77
00:02:43,800 --> 00:02:45,840
少搁一点盐入点味

78
00:02:45,840 --> 00:02:46,600
掸点淀粉

79
00:02:46,600 --> 00:02:49,520
搁这个淀粉以后炸出来有点虎皮色

80
00:02:49,520 --> 00:02:51,600
这个感觉比较突出

81
00:02:52,920 --> 00:02:55,120
这油啊 六成热了

82
00:02:59,240 --> 00:03:02,800
就上点颜色 外焦 脆嫩

83
00:03:03,040 --> 00:03:04,000
这炸着

84
00:03:04,000 --> 00:03:05,600
咱把这盘也给它装好

85
00:03:06,240 --> 00:03:08,200
这菜出来漂亮

86
00:03:08,440 --> 00:03:10,280
过去装饰都是自然的

87
00:03:10,280 --> 00:03:12,720
而且还可食的

88
00:03:15,440 --> 00:03:16,720
底油

89
00:03:16,720 --> 00:03:18,160
小料 葱 姜 蒜

90
00:03:18,160 --> 00:03:20,040
雪菜的梗

91
00:03:21,280 --> 00:03:22,800
再来点水

92
00:03:22,960 --> 00:03:24,160
酱油

93
00:03:25,560 --> 00:03:26,960
黄酒

94
00:03:30,040 --> 00:03:31,240
老抽

95
00:03:33,800 --> 00:03:34,880
白糖

96
00:03:36,920 --> 00:03:38,160
胡椒

97
00:03:43,760 --> 00:03:44,840
贼烫贼烫的

98
00:03:45,080 --> 00:03:47,200
下锅以后再煨一煨

99
00:03:47,200 --> 00:03:50,040
搁点水 因为火旺

100
00:03:55,600 --> 00:03:56,560
来点香油

101
00:03:56,560 --> 00:03:58,240
这就行啦

102
00:03:58,240 --> 00:04:00,360
来点明油

103
00:04:00,960 --> 00:04:03,080
好菜 一锅好菜

104
00:04:07,480 --> 00:04:09,440
干烧 没有汁儿

105
00:04:09,520 --> 00:04:11,160
今天我觉得咱耍开了

106
00:04:11,520 --> 00:04:12,840
颠起锅来了

107
00:04:16,840 --> 00:04:19,360
尝尝

108
00:04:25,200 --> 00:04:27,600
太脆了 脆吧 太脆了

109
00:04:27,840 --> 00:04:28,800
再来一根

110
00:04:28,920 --> 00:04:31,440
我给你带点雪里红梗

111
00:04:31,560 --> 00:04:32,960
再来一块

112
00:04:37,760 --> 00:04:39,320
隋坡也看半天了

113
00:04:39,760 --> 00:04:41,400
隋坡 来

114
00:04:44,760 --> 00:04:46,640
这个笋味很香很脆

115
00:04:47,120 --> 00:04:48,760
再奖励一个

116
00:04:50,360 --> 00:04:51,640
雪里蕻

117
00:04:52,480 --> 00:04:53,720
搁里边还有一个点缀的作用

118
00:04:53,720 --> 00:04:54,560
绿绿的

119
00:04:54,560 --> 00:04:55,920
入口呢还是脆的

120
00:04:56,560 --> 00:04:58,080
曾经师父跟我说过一个

121
00:04:58,080 --> 00:04:59,920
叫逢烧必炸

122
00:04:59,920 --> 00:05:02,920
然后表面还掸了这些淀粉

123
00:05:02,920 --> 00:05:04,520
它遇热糊化之后

124
00:05:04,520 --> 00:05:06,200
师父把这个汁儿往里一放

125
00:05:06,200 --> 00:05:08,200
刚刚好表面的淀粉

126
00:05:08,200 --> 00:05:10,160
把汁吸完了 好看漂亮

127
00:05:10,160 --> 00:05:11,480
口感特别的清脆

128
00:05:11,600 --> 00:05:13,440
你看这雪里蕻这叶啊

129
00:05:13,440 --> 00:05:16,000
经过这一炸 你看 酥脆

130
00:05:16,360 --> 00:05:18,640
因为冬笋它不易入味

131
00:05:18,640 --> 00:05:20,200
搭着冬笋加上这个

132
00:05:20,200 --> 00:05:22,560
吃起来有一种酥香

133
00:05:22,760 --> 00:05:24,160
脆嫩的感觉

134
00:05:24,680 --> 00:05:26,360
得掺着吃

135
00:05:26,360 --> 00:05:29,840
这也是一种点缀的方法

136
00:05:30,040 --> 00:05:31,280
叫可食

137
00:05:31,520 --> 00:05:33,480
你看见没有 没有一点糊弄的

138
00:05:33,760 --> 00:05:35,720
你看包括刀工的处理

139
00:05:35,720 --> 00:05:38,240
味道 形状 色彩

140
00:05:38,360 --> 00:05:39,680
其实是还原

141
00:05:39,680 --> 00:05:42,120
原汁原味的过去40多年前的

142
00:05:42,120 --> 00:05:43,920
这种菜品

143
00:05:44,000 --> 00:05:45,560
40年如一日

144
00:05:45,560 --> 00:05:46,680
兢兢业业

145
00:05:46,680 --> 00:05:48,840
为烹调事业做贡献

146
00:05:49,520 --> 00:05:50,280
高

147
00:05:50,280 --> 00:05:51,320
谢谢二伯

```

**Comment by Yingzhang1122** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
#【国宴大师•干烧冬笋】爽脆咸香，冬季必吃的应季菜！传统手法细节满满！ |老饭骨
State Banquet Master Chef: Dry-braised winter bamboo shoots

简介
#小友们好，今天带给大家一道冬季必吃的应季菜——干烧冬笋。
#冬笋其实不太入味，配上炸过的雪菜叶，非常酥香脆嫩。
#这道菜非常家常，做法也不难，但是细节还是很多的，大爷之前分享过的“劈柴块”刀功，大家还有印象吗？
#还有什么冬季的时令菜大家想吃的？留言给老饭骨，大爷二伯教你们做！
Hello friends! Today we are presenting a seasonal dish for winter - dry-braised winter bamboo shoots. In fact, it's hard for the bamboo shoots to absorb all the flavors. However, this dish is very crispy and delicious when served with fried potherb mustard leaves. You can cook easily it at home, but there are still plenty of details to pay attention to. Do you still remember the 'chop-wood' cutting skill taught by Da Ye? By the way, is there any other winter dishes that you want to learn? Please comment and Da Ye and Er Bai will show you how to cook!

字幕
1
00:00:00,000 --> 00:00:02,800
#北方人吃笋吃的少
People in the north rarely eat bamboo shoots

2
00:00:02,800 --> 00:00:05,120
#有很多人也不知道怎么做
A lot of people do not know how to cook either

3
00:00:05,680 --> 00:00:07,840
#咱们要做一个干烧冬笋
We are going to cook 'dry-braised winter bamboo shoots'

4
00:00:10,160 --> 00:00:12,080
#你看雪里蕻的叶
Look. The leaves of pickled potherb mustard

5
00:00:12,120 --> 00:00:14,680
#经过这一炸你看 酥脆
So crispy after frying

6
00:00:14,760 --> 00:00:16,920
#这个是应季的
This is seasonal food

7
00:00:16,920 --> 00:00:19,120
#先剌一刀给剌一刀剥皮
Cut it first to remove the skin

8
00:00:19,120 --> 00:00:21,120
#外皮很老
The outer skin is very hard and chewy

9
00:00:21,160 --> 00:00:22,880
#但是越剥里边就越嫩了
But it becomes tender inside as you peel it

10
00:00:23,080 --> 00:00:25,000
#这个皮有几个说法
There are some issues about the skin

11
00:00:25,000 --> 00:00:26,200
#这边的皮
The skin in this part

12
00:00:26,240 --> 00:00:27,520
#就像这一块的皮
For example, here

13
00:00:27,600 --> 00:00:28,640
#这可以做菜的
You can use it in some dishes

14
00:00:29,080 --> 00:00:30,040
#这个皮 
The skin here

15
00:00:30,040 --> 00:00:31,560
#这叫笋衣
is named 'bamboo shoot clothes'

16
00:00:32,280 --> 00:00:33,760
#你像比如我们做的酸辣汤
For example, in sour-spicy soup

17
00:00:34,080 --> 00:00:35,920
#搁点豆腐片
You may add some sliced tofu

18
00:00:36,000 --> 00:00:37,560
#笋衣片
and 'bamboo shoot clothes'

19
00:00:37,560 --> 00:00:39,800
#这个特别嫩 好东西
This is very tender. Good stuff

20
00:00:39,800 --> 00:00:40,880
#可以直接吃吗
Can we eat it raw?

21
00:00:40,880 --> 00:00:43,080
#不能直接吃 一会还得处理一下
Nope, we need to process it later

22
00:00:43,080 --> 00:00:46,480
#我们把这笋给它修成这种窝头状
Cut the bamboo shoot into the shape of 'wo tou' (steamed corn bread)

23
00:00:46,520 --> 00:00:48,120
#外边刮得光溜的
Shave the outside until smooth

24
00:00:49,520 --> 00:00:50,600
#我们给它煮上
Let's boil it

25
00:00:51,120 --> 00:00:52,960
#凉水热水都行
Either cold or hot water

26
00:00:53,000 --> 00:00:54,520
#煮15分钟
Boil it for 15 minutes

27
00:00:54,640 --> 00:00:56,440
#这边煮着咱们切点小料
Let's cut some ingredients while boiling the bamboo shoot

28
00:00:57,600 --> 00:00:58,520
#雪菜
(Pickled) Potherb mustard

29
00:00:58,520 --> 00:01:00,520
#把这雪菜叶展开
Spread the leaf

30
00:01:00,640 --> 00:01:03,360
#一炸垫底下碧绿碧绿的倍漂亮
Fry it and put under the dish. It's beautifully green

31
00:01:03,560 --> 00:01:05,640
#老师傅老手法
Old chef, old cooking style

32
00:01:06,400 --> 00:01:08,760
#这梗别太多 太多它咸
Don't add too much stem, otherwise it's gonna be too salty

33
00:01:08,760 --> 00:01:10,560
#这雪菜用的时候呢
Before adding into the dish

34
00:01:10,760 --> 00:01:12,520
#要洗洗它 泡泡它
You need to wash it and soak it

35
00:01:12,640 --> 00:01:14,040
#切成小丁状
Cut into small dices

36
00:01:15,400 --> 00:01:17,200
#别死乞白赖挤
But don't squeeze it too much

37
00:01:17,200 --> 00:01:19,440
#要吃雪菜的脆嫩
you want it to be crunchy and tender

38
00:01:19,440 --> 00:01:21,200
#要把这水都给挤干了
If you squeeze out all the water

39
00:01:21,240 --> 00:01:22,680
#它就不脆了
It's not crunchy any more

40
00:01:23,320 --> 00:01:25,160
#咱们这边煮着
While boiling

41
00:01:25,920 --> 00:01:28,480
#这边可以炸雪菜了
We can start frying the pickled potherb mustard

42
00:01:28,680 --> 00:01:30,640
#油温四成热
Oil temperature is 120 degrees Celsius

43
00:01:30,800 --> 00:01:32,360
#你看啊
Look

44
00:01:33,400 --> 00:01:36,280
#立马就伸展开了
The leaves spread immediately

45
00:01:36,480 --> 00:01:40,520
#炸的是雪菜叶 碧绿碧绿的
The fried leaves are beautifully green

46
00:01:40,800 --> 00:01:43,160
#好看吧 行
Looks nice? Yeah

47
00:01:43,440 --> 00:01:46,520
#好了大爷 行了
That's done, Da Ye. Okay

48
00:01:46,520 --> 00:01:48,800
#先关火 这边晾着
Turn off the fire. Cool it a bit

49
00:01:48,960 --> 00:01:51,040
#晾完了它才酥脆
The leaves will be crispy after cooling down

50
00:01:51,600 --> 00:01:52,760
#冬笋好了
Bamboo shoot is done

51
00:01:52,800 --> 00:01:54,360
#因为你没煮的时候
If you do not boil it (before cutting)

52
00:01:54,360 --> 00:01:56,560
#一切它就容易炸了
The shoot is going to crack once you cut it

53
00:01:56,560 --> 00:01:58,040
#就不容易出刀口
In that case, it's not beautiful

54
00:01:58,040 --> 00:01:59,760
#现在煮完了以后你看
Now, after boiling

55
00:02:00,080 --> 00:02:01,920
#一看就透了
You can easily cut through it

56
00:02:01,920 --> 00:02:04,680
#在大爷学堂里面有个刀工叫劈柴块
There is a special cutting skill, 'chop-wood' cut

57
00:02:04,680 --> 00:02:06,120
#什么叫劈柴块
What is a 'chop-wood' cut?

58
00:02:06,120 --> 00:02:07,560
#看着啊 不是切了
Look. This is not all about cutting

59
00:02:07,560 --> 00:02:10,440
#要把它这个丝纹路给拍松
You need to crack it through the fibers

60
00:02:10,720 --> 00:02:12,520
#现在已经松了你看
Now there's a crack

61
00:02:12,840 --> 00:02:14,120
#隋坡你看着啊
Look, Sui Po

62
00:02:14,120 --> 00:02:15,240
#剌开一口
Cut it from here

63
00:02:15,240 --> 00:02:16,720
#劈柴
'chop-wood'

64
00:02:16,880 --> 00:02:18,800
#到这就不能切了
Don't cut deeper when it reaches here

65
00:02:19,280 --> 00:02:20,480
#撕
Tear it apart

66
00:02:22,000 --> 00:02:23,320
#拢住了
Hold it tight

67
00:02:23,640 --> 00:02:25,160
#干烧冬笋有好多
There are a lot of restaurants

68
00:02:25,160 --> 00:02:27,120
#有好多社会餐饮也在做
that offer this dish

69
00:02:27,480 --> 00:02:28,840
#但是刀工处理上
But they always make mistakes

70
00:02:28,840 --> 00:02:30,720
#他的方法就错了
in terms of cutting the bamboo shoot

71
00:02:30,720 --> 00:02:32,400
#这叫劈柴块
This is the 'chop-wood' cut

72
00:02:33,240 --> 00:02:35,280
#这样做的最大好处 便于入味
The biggest advantage is for better flavor penetration

73
00:02:35,320 --> 00:02:36,880
#还有什么便于烹调
What else? For easy cooking

74
00:02:36,880 --> 00:02:38,280
#二伯点火
Er Bai, turn on the fire, please

75
00:02:40,360 --> 00:02:42,000
#二伯 你看都齐了
Er Bai, we have everything here

76
00:02:42,000 --> 00:02:43,800
#整齐了 刀工一致
Everything's ready. Uniformly cut

77
00:02:43,800 --> 00:02:45,840
#少搁一点盐入点味
Add some salt for the base flavor

78
00:02:45,840 --> 00:02:46,600
#掸点淀粉
Add some starch

79
00:02:46,600 --> 00:02:49,520
#搁这个淀粉以后炸出来有点虎皮色
In this way, the bamboo shoot becomes caramel brown after fried 

80
00:02:49,520 --> 00:02:51,600
#这个感觉比较突出
That's gonna be great

81
00:02:52,920 --> 00:02:55,120
#这油啊 六成热了
The oil temperature is about 180 degrees Celsius

82
00:02:59,240 --> 00:03:02,800
#就上点颜色 外焦 脆嫩
Fry it for the color. Also it's gonna be crispy outside, while crunchy and tender inside

83
00:03:03,040 --> 00:03:04,000
#这炸着
While frying

84
00:03:04,000 --> 00:03:05,600
#咱把这盘也给它装好
Prepare the plate

85
00:03:06,240 --> 00:03:08,200
#这菜出来漂亮
The dish is gonna be beautiful

86
00:03:08,440 --> 00:03:10,280
#过去装饰都是自然的
In the past, we used natural materials for decoration

87
00:03:10,280 --> 00:03:12,720
#而且还可食的
The decorations were usually edible as well

88
00:03:15,440 --> 00:03:16,720
#底油
base oil

89
00:03:16,720 --> 00:03:18,160
#小料 葱 姜 蒜
Ingredients. Green onion, ginger, garlic

90
00:03:18,160 --> 00:03:20,040
#雪菜的梗
Stem of pickled potherb mustard

91
00:03:21,280 --> 00:03:22,800
#再来点水
Some water

92
00:03:22,960 --> 00:03:24,160
#酱油
Soysauce

93
00:03:25,560 --> 00:03:26,960
#黄酒
'Huangjiu' rice wine

94
00:03:30,040 --> 00:03:31,240
#老抽
dark soy sauce

95
00:03:33,800 --> 00:03:34,880
#白糖
Sugar

96
00:03:36,920 --> 00:03:38,160
#胡椒
Pepper

97
00:03:43,760 --> 00:03:44,840
#贼烫贼烫的
This is very hot

98
00:03:45,080 --> 00:03:47,200
#下锅以后再煨一煨
Braise it for some time after adding it into the wok

99
00:03:47,200 --> 00:03:50,040
#搁点水 因为火旺
Add some water. The heat is very powerful now

100
00:03:55,600 --> 00:03:56,560
#来点香油
Some sesame oil

101
00:03:56,560 --> 00:03:58,240
#这就行啦
That's it

102
00:03:58,240 --> 00:04:00,360
#来点明油
Some oil at last

103
00:04:00,960 --> 00:04:03,080
#好菜 一锅好菜
Nice dish. That's a nice one

104
00:04:07,480 --> 00:04:09,440
#干烧 没有汁儿
Dry-braise. No extra sauce

105
00:04:09,520 --> 00:04:11,160
#今天我觉得咱耍开了
Today we are playing it wild

106
00:04:11,520 --> 00:04:12,840
#颠起锅来了
I can toss the wok

107
00:04:16,840 --> 00:04:19,360
#尝尝
Taste it

108
00:04:25,200 --> 00:04:27,600
#太脆了 脆吧 太脆了
Too crunchy. Right? Incredibly crunchy

109
00:04:27,840 --> 00:04:28,800
#再来一根
One more

110
00:04:28,920 --> 00:04:31,440
#我给你带点雪里红梗
with some potherb mustard stem this time

111
00:04:31,560 --> 00:04:32,960
#再来一块
One more

112
00:04:37,760 --> 00:04:39,320
#隋坡也看半天了
Sui Po has been looking at it for a long time

113
00:04:39,760 --> 00:04:41,400
#隋坡 来
Sui Po, come on

114
00:04:44,760 --> 00:04:46,640
#这个笋味很香很脆
The bamboo shoot is very delicious and crunchy

115
00:04:47,120 --> 00:04:48,760
#再奖励一个
One more for you

116
00:04:50,360 --> 00:04:51,640
#雪里蕻
The pickled potherb mustard...

117
00:04:52,480 --> 00:04:53,720
#搁里边还有一个点缀的作用
is a perfect decoration for this dish

118
00:04:53,720 --> 00:04:54,560
#绿绿的
Green

119
00:04:54,560 --> 00:04:55,920
#入口呢还是脆的
and crunchy

120
00:04:56,560 --> 00:04:58,080
#曾经师父跟我说过一个
Previously my master told me

121
00:04:58,080 --> 00:04:59,920
#叫逢烧必炸
Braised food must be fried in advance

122
00:04:59,920 --> 00:05:02,920
#然后表面还掸了这些淀粉
Also, the starch on the surface

123
00:05:02,920 --> 00:05:04,520
#它遇热糊化之后
When the starch gelatinizes after heating

124
00:05:04,520 --> 00:05:06,200
#师父把这个汁儿往里一放
Master poured in the sauce

125
00:05:06,200 --> 00:05:08,200
#刚刚好表面的淀粉
The starch on the surface will

126
00:05:08,200 --> 00:05:10,160
#把汁吸完了 好看漂亮
absorb all the sauce. Looks beautiful

127
00:05:10,160 --> 00:05:11,480
#口感特别的清脆
The texture is extremely crunchy

128
00:05:11,600 --> 00:05:13,440
#你看这雪里蕻这叶啊
The potherb mustard leaves

129
00:05:13,440 --> 00:05:16,000
#经过这一炸 你看 酥脆
becomes very crispy after frying

130
00:05:16,360 --> 00:05:18,640
#因为冬笋它不易入味
Since it's hard for the bamboo shoot to absorb the flavors

131
00:05:18,640 --> 00:05:20,200
#搭着冬笋加上这个
The bamboo shoots and potherb mustard leaves

132
00:05:20,200 --> 00:05:22,560
#吃起来有一种酥香
match with each other to give a crispy,

133
00:05:22,760 --> 00:05:24,160
#脆嫩的感觉
crunchy and tender feeling

134
00:05:24,680 --> 00:05:26,360
#得掺着吃
You should enjoy them together

135
00:05:26,360 --> 00:05:29,840
#这也是一种点缀的方法
This is also one way of decorating the dish

136
00:05:30,040 --> 00:05:31,280
#叫可食
Edible decorations

137
00:05:31,520 --> 00:05:33,480
#你看见没有 没有一点糊弄的
See? Not careless at all

138
00:05:33,760 --> 00:05:35,720
#你看包括刀工的处理
Including cutting skills,

139
00:05:35,720 --> 00:05:38,240
#味道 形状 色彩
taste, shape, and color

140
00:05:38,360 --> 00:05:39,680
#其实是还原
This is to recover

141
00:05:39,680 --> 00:05:42,120
#原汁原味的过去40多年前的
The original dish 

142
00:05:42,120 --> 00:05:43,920
#这种菜品
from more than 40 years ago

143
00:05:44,000 --> 00:05:45,560
#40年如一日
(Da Ye) has been working for 40 years,

144
00:05:45,560 --> 00:05:46,680
#兢兢业业
but has always been following the same principles

145
00:05:46,680 --> 00:05:48,840
#为烹调事业做贡献
and contributes to the cooking industry

146
00:05:49,520 --> 00:05:50,280
#高
That's marvelous

147
00:05:50,280 --> 00:05:51,320
#谢谢二伯
Thanks, Er Bai
