### ISSUE TITLE
[老饭骨] 群英荟萃 - https://youtu.be/Om5AcAGbYJM

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1660]
**视频链接**：https://youtu.be/Om5AcAGbYJM

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•群英荟萃】鲜香滋补，三种萝卜用最朴素的烹饪手法做出无比鲜美的味道！ |老饭骨

简介
小友们好，今天咱们这个菜名可够别致的，叫——群英荟萃。看这五颜六色的，小友们能猜到主要的食材是什么吗？
没错，就是萝卜！俗话说得好，冬吃萝卜夏吃姜。萝卜营养丰富，含有多种维生素和大量植物蛋白等，经常吃萝卜有利于增强免疫力。
这道群英荟萃，选用了白萝卜、胡萝卜和青萝卜，颜色搭配好看，并且使用了淮阳菜的老菜扣三丝的手法，成菜更加精致。
搭配熬得奶白的鲫鱼汤，一口下去，无比鲜美！小友们家常吃也可以把萝卜丝儿直接煮到鲫鱼汤里，更加方便快捷！

字幕
1
00:00:00,040 --> 00:00:01,320
1 2 走

2
00:00:02,040 --> 00:00:03,720
展现了淮扬菜的老菜叫

3
00:00:03,720 --> 00:00:05,240
扣三丝的手法

4
00:00:05,240 --> 00:00:07,520
结合了一个萝卜丝鲫鱼汤

5
00:00:07,520 --> 00:00:08,280
看着啊 

6
00:00:08,840 --> 00:00:10,000
就要这一瞬间

7
00:00:10,800 --> 00:00:12,080
俩菜组合

8
00:00:12,160 --> 00:00:13,480
群英荟萃

9
00:00:17,760 --> 00:00:19,560
先处理鲫鱼

10
00:00:19,560 --> 00:00:20,920
鳍都要铰掉

11
00:00:20,920 --> 00:00:23,080
它的牙非常非常腥

12
00:00:23,080 --> 00:00:25,440
里边还有好多血水

13
00:00:26,240 --> 00:00:28,160
表皮黏液腥味太重

14
00:00:28,160 --> 00:00:30,440
而且夹杂了很多细菌

15
00:00:30,440 --> 00:00:32,160
所以这我们要用80度左右的水

16
00:00:32,160 --> 00:00:33,120
要烫一下

17
00:00:33,200 --> 00:00:34,840
咱们用刀刮一下

18
00:00:35,640 --> 00:00:36,800
看这水 你要不擖饬

19
00:00:36,800 --> 00:00:38,400
你看看 脏成什么样了

20
00:00:38,400 --> 00:00:40,200
里边那些杂质处理下来

21
00:00:40,200 --> 00:00:41,440
又出了很多

22
00:00:43,280 --> 00:00:44,560
这要溶解到汤里边

23
00:00:44,560 --> 00:00:46,640
跟刷锅水似的

24
00:00:47,560 --> 00:00:48,880
你看这鱼多干净

25
00:00:49,320 --> 00:00:50,560
干干净净

26
00:00:50,600 --> 00:00:52,360
清澈见底

27
00:00:52,520 --> 00:00:54,440
好 下一步

28
00:00:54,520 --> 00:00:55,280
打花刀

29
00:00:55,280 --> 00:00:56,920
这个打花刀也很重要

30
00:00:57,440 --> 00:00:58,760
没事打狠一点

31
00:00:59,360 --> 00:01:01,000
因为咱们只用汤

32
00:01:01,680 --> 00:01:03,040
花刀打完之后

33
00:01:03,040 --> 00:01:04,880
它便于它的一个成熟

34
00:01:05,280 --> 00:01:06,200
好

35
00:01:06,200 --> 00:01:06,960
煎鱼

36
00:01:07,040 --> 00:01:08,280
对 热锅凉油

37
00:01:08,480 --> 00:01:09,920
放点葱油还有色拉油

38
00:01:09,920 --> 00:01:12,400
这就是老方法 二合油

39
00:01:13,000 --> 00:01:14,000
放两片姜

40
00:01:14,000 --> 00:01:16,400
把这姜煸的的有点香味

41
00:01:16,400 --> 00:01:18,240
然后把鱼放进去

42
00:01:25,960 --> 00:01:27,160
大火煎

43
00:01:27,920 --> 00:01:28,840
先不着急动

44
00:01:29,200 --> 00:01:32,440
这个鱼只有把它肉煎熟了之后

45
00:01:32,440 --> 00:01:34,480
那么再加入热水

46
00:01:34,480 --> 00:01:36,680
汤才能浓白

47
00:01:36,800 --> 00:01:38,760
鱼皮经过热处理之后

48
00:01:38,760 --> 00:01:40,440
刮掉表面黏膜

49
00:01:40,840 --> 00:01:43,480
这个皮就很少了 几乎没有了

50
00:01:43,480 --> 00:01:46,520
所以在煎的时候就很容易会脱落

51
00:01:46,960 --> 00:01:48,960
好 呲水

52
00:01:49,600 --> 00:01:50,920
就要这一瞬间

53
00:01:53,400 --> 00:01:54,440
搁点黄酒

54
00:01:54,440 --> 00:01:56,200
料酒去腥

55
00:01:56,200 --> 00:01:57,600
还得打打沫子

56
00:02:00,040 --> 00:02:02,840
滚白了 滚白了为止 一刻钟

57
00:02:02,960 --> 00:02:04,880
这个鱼汤我们煮着

58
00:02:05,160 --> 00:02:07,920
这个萝卜丝咱们用三种颜色

59
00:02:07,920 --> 00:02:08,960
一个是白萝卜

60
00:02:08,960 --> 00:02:10,200
胡萝卜 还有青萝卜

61
00:02:10,200 --> 00:02:12,000
萝卜开会真来了啊

62
00:02:12,360 --> 00:02:13,320
先切片

63
00:02:13,960 --> 00:02:14,760
这切完之后呢

64
00:02:14,760 --> 00:02:16,240
一会咱们要先焯水

65
00:02:16,240 --> 00:02:17,880
因为如果我们要码盘

66
00:02:17,880 --> 00:02:19,320
先切完丝儿再焯水

67
00:02:19,320 --> 00:02:20,560
那就不好码了

68
00:02:21,000 --> 00:02:22,960
咱们这水里边要放点盐

69
00:02:23,680 --> 00:02:25,440
冷水热水都问题不是很大

70
00:02:25,480 --> 00:02:27,480
但是一定要让它迅速的开锅

71
00:02:27,480 --> 00:02:28,240
时间长了

72
00:02:28,240 --> 00:02:30,000
把那萝卜就煮烂掉了

73
00:02:30,000 --> 00:02:31,360
然后也是不能盖盖

74
00:02:32,560 --> 00:02:35,040
行了 萝卜一开汤儿

75
00:02:36,600 --> 00:02:39,600
汤现在已经开始变白

76
00:02:40,000 --> 00:02:41,040
还没达到要求

77
00:02:41,360 --> 00:02:42,520
里边儿腥味儿比较大

78
00:02:42,520 --> 00:02:43,880
咱们搁两片儿 葱姜

79
00:02:45,240 --> 00:02:45,960
继续

80
00:02:46,160 --> 00:02:47,360
你看这汤倍儿白

81
00:02:48,040 --> 00:02:48,960
切丝儿

82
00:02:55,600 --> 00:02:57,000
您要觉得切丝难呢

83
00:02:57,040 --> 00:02:58,680
你拿擦丝器擦

84
00:02:59,560 --> 00:03:00,960
这鱼汤啊 看看啊

85
00:03:00,960 --> 00:03:01,960
鱼汤到一定程度

86
00:03:01,960 --> 00:03:03,760
就把这个肉给它杵烂

87
00:03:03,760 --> 00:03:05,880
我们只要汤不要肉

88
00:03:06,200 --> 00:03:07,320
该装碗了

89
00:03:07,360 --> 00:03:09,280
下边垫一层保鲜膜

90
00:03:09,280 --> 00:03:11,280
蒸完之后遇热它好脱

91
00:03:11,400 --> 00:03:13,000
这个地方直接摆到

92
00:03:13,000 --> 00:03:16,200
碗中心这个部位 不能过中心

93
00:03:16,960 --> 00:03:19,320
剩下呢 咱们这个萝卜丝

94
00:03:19,400 --> 00:03:20,880
全部都放到碗底

95
00:03:20,880 --> 00:03:24,240
成型的时候更容易托着

96
00:03:24,640 --> 00:03:26,200
不搁这个这中间一个大坑

97
00:03:26,640 --> 00:03:28,440
为了更加美观

98
00:03:28,440 --> 00:03:30,600
把这个边要铰一下

99
00:03:31,320 --> 00:03:32,240
扣出来以后

100
00:03:32,280 --> 00:03:33,560
边上一圈是圆的

101
00:03:33,960 --> 00:03:35,960
修边 铰刘海

102
00:03:36,720 --> 00:03:37,440
找一干净盘

103
00:03:37,440 --> 00:03:38,640
把这点肉捞出来

104
00:03:39,800 --> 00:03:40,680
在家里边

105
00:03:40,680 --> 00:03:42,160
您要觉得很麻烦的话

106
00:03:42,160 --> 00:03:43,240
您就切点五彩丝儿

107
00:03:43,240 --> 00:03:44,400
做个鲫鱼汤往里一放

108
00:03:44,400 --> 00:03:46,040
你要想变个展示的方法

109
00:03:46,040 --> 00:03:47,560
您就按照我这个操作一下

110
00:03:47,920 --> 00:03:49,520
来 过滤一下

111
00:03:53,760 --> 00:03:55,680
我们把这个鱼汤得调一下味

112
00:03:55,680 --> 00:03:57,240
然后倒在萝卜丝里

113
00:03:57,240 --> 00:03:59,000
然后上锅得蒸一下

114
00:03:59,160 --> 00:04:01,560
你看这汤 特别的白

115
00:04:01,560 --> 00:04:02,400
奶白奶白的

116
00:04:02,640 --> 00:04:03,440
搁点盐

117
00:04:03,680 --> 00:04:05,000
这口味得重一点

118
00:04:05,840 --> 00:04:07,320
胡椒

119
00:04:10,160 --> 00:04:11,760
灌上鱼汤

120
00:04:12,880 --> 00:04:14,280
咱们上锅蒸

121
00:04:14,360 --> 00:04:17,000
上气之后咱们蒸上10分钟

122
00:04:17,000 --> 00:04:18,120
10分钟足够了

123
00:04:18,120 --> 00:04:20,560
因为这萝卜焯过水了

124
00:04:21,840 --> 00:04:22,680
时间到了

125
00:04:22,680 --> 00:04:24,640
好出锅

126
00:04:25,640 --> 00:04:27,520
关火 关火别烫着了

127
00:04:27,960 --> 00:04:28,960
别烫着

128
00:04:29,880 --> 00:04:31,440
把这个汤篦一下

129
00:04:31,520 --> 00:04:33,160
它里边有萝卜那个

130
00:04:33,440 --> 00:04:35,120
多余的臭气

131
00:04:35,280 --> 00:04:36,640
这汤就不要了

132
00:04:38,160 --> 00:04:39,120
翻

133
00:04:39,160 --> 00:04:40,440
1 2 走

134
00:04:41,680 --> 00:04:43,680
没事没事 掀你的

135
00:04:43,680 --> 00:04:44,440
没问题

136
00:04:44,440 --> 00:04:46,160
防止它把这个丝儿冲乱

137
00:04:46,200 --> 00:04:47,680
上面要搁一个罩

138
00:04:54,360 --> 00:04:56,280
蛋皮丝增加颜色

139
00:04:56,280 --> 00:04:59,920
把中间刀口盖上

140
00:05:00,760 --> 00:05:01,680
咱们还有枸杞

141
00:05:01,680 --> 00:05:03,160
这叫封底

142
00:05:05,160 --> 00:05:06,480
群英荟萃

143
00:05:06,920 --> 00:05:08,040
一口鲜

144
00:05:11,800 --> 00:05:14,040
这个菜还真不一样

145
00:05:19,880 --> 00:05:22,080
我建议多熬点汤

146
00:05:22,080 --> 00:05:23,520
然后随一大碗汤走

147
00:05:23,520 --> 00:05:26,120
一人来一小碗一盛就完美了

148
00:05:26,520 --> 00:05:29,240
这是我跟大爷的一点建议

149
00:05:29,240 --> 00:05:30,520
谢谢二伯

150
00:05:30,520 --> 00:05:31,720
谢谢师父

151
00:05:32,480 --> 00:05:34,560
端出去吧 展示一下

152
00:05:34,560 --> 00:05:36,000
品尝一下

```

**Comment by Yingzhang1122** [comment]
#标题（翻译主要意思即可，不要超过 100 个字符）
#【国宴大师•群英荟萃】鲜香滋补，三种萝卜用最朴素的烹饪手法做出无比鲜美的味道！ |老饭骨
State Banquet Master Chef: Qun Ying Hui Cui (Gathering of heroes)

#简介
#小友们好，今天咱们这个菜名可够别致的，叫——群英荟萃。看这五颜六色的，小友们能猜到主要的食材是什么吗？
#没错，就是萝卜！俗话说得好，冬吃萝卜夏吃姜。萝卜营养丰富，含有多种维生素和大量植物蛋白等，经常吃萝卜有利于增强免疫力。
#这道群英荟萃，选用了白萝卜、胡萝卜和青萝卜，颜色搭配好看，并且使用了淮阳菜的老菜扣三丝的手法，成菜更加精致。
#搭配熬得奶白的鲫鱼汤，一口下去，无比鲜美！小友们家常吃也可以把萝卜丝儿直接煮到鲫鱼汤里，更加方便快捷！
Hello friends! Today we are having a dish with a very special name: Qun Ying Hui Cui (Gathering of heroes). Looking at this colorful dish, can you figure out what the ingredients are?
Yes, radish! As a saying goes, radish is for winter and ginger is for summer. Radish is very nutrient, containing various vitamins and rich plant proteins. Eating radish regularly is good for your immune system.
For this dish, we use white radish, carrots, and green radish. Apart from its beautiful color, this dish is cooked in a delicate fashion - same as a traditional Huaiyang dish, Kou San Si.
This dish is incomparably delicious with the milky-white carp soup. When cooking at home, you may also boil the shredded radish in the carp soup, making it simple and fast!

字幕
1
00:00:00,040 --> 00:00:01,320
#1 2 走
One, two, go!

2
00:00:02,040 --> 00:00:03,720
#展现了淮扬菜的老菜叫
This dish presents the cooking technique of a traditional Huaiyang dish

3
00:00:03,720 --> 00:00:05,240
#扣三丝的手法.0
which is named 'Kou San Si'

4
00:00:05,240 --> 00:00:07,520
#结合了一个萝卜丝鲫鱼汤
While the other part of this dish is from 'Carp soup with shredded radish'

5
00:00:07,520 --> 00:00:08,280
#看着啊 
Look

6
00:00:08,840 --> 00:00:10,000
#就要这一瞬间
That's the key moment

7
00:00:10,800 --> 00:00:12,080
#俩菜组合
The combination of two dishes

8
00:00:12,160 --> 00:00:13,480
#群英荟萃
Gathering of heroes

9
00:00:17,760 --> 00:00:19,560
#先处理鲫鱼
Let's process the carp first

10
00:00:19,560 --> 00:00:20,920
#鳍都要铰掉
Scissor the fins

11
00:00:20,920 --> 00:00:23,080
#它的牙非常非常腥
The teeth are extremely fishy

12
00:00:23,080 --> 00:00:25,440
#里边还有好多血水
There's much blood in it too

13
00:00:26,240 --> 00:00:28,160
#表皮黏液腥味太重
The skin mucus also smells very fishy

14
00:00:28,160 --> 00:00:30,440
#而且夹杂了很多细菌
and has a lot of bacteria

15
00:00:30,440 --> 00:00:32,160
#所以这我们要用80度左右的水
So we need to use hot water at about 80 degrees Celsius

16
00:00:32,160 --> 00:00:33,120
#要烫一下
to 'wash' it #感觉soak和blanch都不太好

17
00:00:33,200 --> 00:00:34,840
#咱们用刀刮一下
Let's scratch it with a knife

18
00:00:35,640 --> 00:00:36,800
#看这水 你要不擖饬
Look at the water. If you don't wash it

19
00:00:36,800 --> 00:00:38,400
#你看看 脏成什么样了
Look how dirty it is

20
00:00:38,400 --> 00:00:40,200
#里边那些杂质处理下来
The impurities are removed

21
00:00:40,200 --> 00:00:41,440
#又出了很多
There's a lot (of dirty stuff)

22
00:00:43,280 --> 00:00:44,560
#这要溶解到汤里边
If these impurities dissolve in the soup

23
00:00:44,560 --> 00:00:46,640
#跟刷锅水似的
The soup will be like dishwater

24
00:00:47,560 --> 00:00:48,880
#你看这鱼多干净
Look how clean the fish are

25
00:00:49,320 --> 00:00:50,560
#干干净净
So clean

26
00:00:50,600 --> 00:00:52,360
#清澈见底
So clear that you can see the bottom of the bowl

27
00:00:52,520 --> 00:00:54,440
#好 下一步
Ok. Next

28
00:00:54,520 --> 00:00:55,280
#打花刀
Cut the fish

29
00:00:55,280 --> 00:00:56,920
#这个打花刀也很重要
Scoring is also important

30
00:00:57,440 --> 00:00:58,760
#没事打狠一点
It's ok. Score deeper

31
00:00:59,360 --> 00:01:01,000
#因为咱们只用汤
Because we just need the soup

32
00:01:01,680 --> 00:01:03,040
#花刀打完之后
After scoring

33
00:01:03,040 --> 00:01:04,880
#它便于它的一个成熟
The fish will be cooked much faster

34
00:01:05,280 --> 00:01:06,200
#好
Okay

35
00:01:06,200 --> 00:01:06,960
#煎鱼
Fry the fish

36
00:01:07,040 --> 00:01:08,280
#对 热锅凉油
Yes. Hot wok, cold oil

37
00:01:08,480 --> 00:01:09,920
#放点葱油还有色拉油
Add some green onion oil and salad oil

38
00:01:09,920 --> 00:01:12,400
#这就是老方法 二合油
That's a traditional technique. Mixed oil

39
00:01:13,000 --> 00:01:14,000
#放两片姜
Two slices of ginger

40
00:01:14,000 --> 00:01:16,400
#把这姜煸的的有点香味
Fry the ginger until aromatic

41
00:01:16,400 --> 00:01:18,240
#然后把鱼放进去
Then put the fish in

42
00:01:25,960 --> 00:01:27,160
#大火煎
Fry it with high heat

43
00:01:27,920 --> 00:01:28,840
#先不着急动
Don't touch it for now

44
00:01:29,200 --> 00:01:32,440
#这个鱼只有把它肉煎熟了之后
The fish... only after the fish is completely cooked

45
00:01:32,440 --> 00:01:34,480
#那么再加入热水
can you add hot water

46
00:01:34,480 --> 00:01:36,680
#汤才能浓白
The soup will be thick and milky white in this way

47
00:01:36,800 --> 00:01:38,760
#鱼皮经过热处理之后
The fish skin... after washed with hot water

48
00:01:38,760 --> 00:01:40,440
#刮掉表面黏膜
and removing the mucus

49
00:01:40,840 --> 00:01:43,480
#这个皮就很少了 几乎没有了
The skin is almost gone

50
00:01:43,480 --> 00:01:46,520
#所以在煎的时候就很容易会脱落
Hence the fish falls apart easily when frying

51
00:01:46,960 --> 00:01:48,960
#好 呲水
Okay. Add hot water

52
00:01:49,600 --> 00:01:50,920
#就要这一瞬间
That's the key moment

53
00:01:53,400 --> 00:01:54,440
#搁点黄酒
Add some Huangjiu rice wine

54
00:01:54,440 --> 00:01:56,200
#料酒去腥
Wine removes the fishy odor

55
00:01:56,200 --> 00:01:57,600
#还得打打沫子
Remove the scum as well

56
00:02:00,040 --> 00:02:02,840
#滚白了 滚白了为止 一刻钟
Boil until the soup turns white. 15 minutes

57
00:02:02,960 --> 00:02:04,880
#这个鱼汤我们煮着
While boiling the fish soup

58
00:02:05,160 --> 00:02:07,920
#这个萝卜丝咱们用三种颜色
Let's prepare three types of shredded radish

59
00:02:07,920 --> 00:02:08,960
#一个是白萝卜
White radish

60
00:02:08,960 --> 00:02:10,200
#胡萝卜 还有青萝卜
Carrot, and green radish #严格来说白萝卜和青萝卜是十字花科的；胡萝卜是伞形科的，不是真萝卜...所以这里要解释一下嘛？

61
00:02:10,200 --> 00:02:12,000
#萝卜开会真来了啊
That's radishes having a meeting

62
00:02:12,360 --> 00:02:13,320
#先切片
Slice first

63
00:02:13,960 --> 00:02:14,760
#这切完之后呢
After slicing

64
00:02:14,760 --> 00:02:16,240
#一会咱们要先焯水
We need to blanch them first

65
00:02:16,240 --> 00:02:17,880
#因为如果我们要码盘
Since we want to present the dish in a beautiful way

66
00:02:17,880 --> 00:02:19,320
#先切完丝儿再焯水
If we blanch after shredding

67
00:02:19,320 --> 00:02:20,560
#那就不好码了
Presenting the dish will be very difficult

68
00:02:21,000 --> 00:02:22,960
#咱们这水里边要放点盐
Add some salt into the water

69
00:02:23,680 --> 00:02:25,440
#冷水热水都问题不是很大
It doesn't matter if you use cold or hot water

70
00:02:25,480 --> 00:02:27,480
#但是一定要让它迅速的开锅
But you should make sure it boils quickly

71
00:02:27,480 --> 00:02:28,240
#时间长了
If it boils slowly

72
00:02:28,240 --> 00:02:30,000
#把那萝卜就煮烂掉了
The radishes will be too soft

73
00:02:30,000 --> 00:02:31,360
#然后也是不能盖盖
Also, don't close the lid

74
00:02:32,560 --> 00:02:35,040
#行了 萝卜一开汤儿
Done. As soon as it boils

75
00:02:36,600 --> 00:02:39,600
#汤现在已经开始变白
The fish soup is turning white

76
00:02:40,000 --> 00:02:41,040
#还没达到要求
But not white enough yet

77
00:02:41,360 --> 00:02:42,520
#里边儿腥味儿比较大
It still smells fishy

78
00:02:42,520 --> 00:02:43,880
#咱们搁两片儿 葱姜
Let's add some green onion and ginger

79
00:02:45,240 --> 00:02:45,960
#继续
Go on

80
00:02:46,160 --> 00:02:47,360
#你看这汤倍儿白
Look. The soup is so white

81
00:02:48,040 --> 00:02:48,960
#切丝儿
Shred the radish

82
00:02:55,600 --> 00:02:57,000
#您要觉得切丝难呢
If you feel it's hard to shred the radish with a knife

83
00:02:57,040 --> 00:02:58,680
#你拿擦丝器擦
You can use a kitchen shredder

84
00:02:59,560 --> 00:03:00,960
#这鱼汤啊 看看啊
The fish soup. Look

85
00:03:00,960 --> 00:03:01,960
#鱼汤到一定程度
At some point

86
00:03:01,960 --> 00:03:03,760
#就把这个肉给它杵烂
You can mash the fish

87
00:03:03,760 --> 00:03:05,880
#我们只要汤不要肉
We just need the soup. Not the meat

88
00:03:06,200 --> 00:03:07,320
#该装碗了
Time to put in the bowl

89
00:03:07,360 --> 00:03:09,280
#下边垫一层保鲜膜
Apply a piece of plastic wrap underneath

90
00:03:09,280 --> 00:03:11,280
#蒸完之后遇热它好脱
(The dish) will fall out easily from the bowl after steaming

91
00:03:11,400 --> 00:03:13,000
#这个地方直接摆到
Place the shredded radish

92
00:03:13,000 --> 00:03:16,200
#碗中心这个部位 不能过中心
to the center of the bowl. Do not go over the center

93
00:03:16,960 --> 00:03:19,320
#剩下呢 咱们这个萝卜丝
The remaining radish...

94
00:03:19,400 --> 00:03:20,880
#全部都放到碗底
Put them all at the bottom

95
00:03:20,880 --> 00:03:24,240
#成型的时候更容易托着
They will hold the dish together

96
00:03:24,640 --> 00:03:26,200
#不搁这个这中间一个大坑
Otherwise there'll be a big pit

97
00:03:26,640 --> 00:03:28,440
#为了更加美观
To make it more beautiful

98
00:03:28,440 --> 00:03:30,600
#把这个边要铰一下
Trim the surroundings

99
00:03:31,320 --> 00:03:32,240
#扣出来以后
such that when you turn over the bowl

100
00:03:32,280 --> 00:03:33,560
#边上一圈是圆的
The surrounding can form a circle

101
00:03:33,960 --> 00:03:35,960
#修边 铰刘海
Trim the surroundings. Just like cutting the bangs

102
00:03:36,720 --> 00:03:37,440
#找一干净盘
Get a clean plate

103
00:03:37,440 --> 00:03:38,640
#把这点肉捞出来
Take out the meat

104
00:03:39,800 --> 00:03:40,680
#在家里边
When cooking at home

105
00:03:40,680 --> 00:03:42,160
#您要觉得很麻烦的话
If you think this is too complicated

106
00:03:42,160 --> 00:03:43,240
#您就切点五彩丝儿
Just prepare some shredded radish #这里应该是指萝卜丝？

107
00:03:43,240 --> 00:03:44,400
#做个鲫鱼汤往里一放
Make a carp soup and simply put it in

108
00:03:44,400 --> 00:03:46,040
#你要想变个展示的方法
If you want to change the way of presenting

109
00:03:46,040 --> 00:03:47,560
#您就按照我这个操作一下
You can follow my protocol

110
00:03:47,920 --> 00:03:49,520
#来 过滤一下
Let's filter it

111
00:03:53,760 --> 00:03:55,680
#我们把这个鱼汤得调一下味
We need to season the soup

112
00:03:55,680 --> 00:03:57,240
#然后倒在萝卜丝里
Then pour it into the shredded radish

113
00:03:57,240 --> 00:03:59,000
#然后上锅得蒸一下
Then steam the dish

114
00:03:59,160 --> 00:04:01,560
#你看这汤 特别的白
Look at the soup

115
00:04:01,560 --> 00:04:02,400
#奶白奶白的
Milky white

116
00:04:02,640 --> 00:04:03,440
#搁点盐
Add some salt

117
00:04:03,680 --> 00:04:05,000
#这口味得重一点
Make it a bit strong

118
00:04:05,840 --> 00:04:07,320
#胡椒
Pepper

119
00:04:10,160 --> 00:04:11,760
#灌上鱼汤
Add some fish soup

120
00:04:12,880 --> 00:04:14,280
#咱们上锅蒸
Let's steam the dish

121
00:04:14,360 --> 00:04:17,000
#上气之后咱们蒸上10分钟
Steam for 10 minutes after boiling

122
00:04:17,000 --> 00:04:18,120
#10分钟足够了
10 minutes is enough

123
00:04:18,120 --> 00:04:20,560
#因为这萝卜焯过水了
Since we have already blanched the radish

124
00:04:21,840 --> 00:04:22,680
#时间到了
Time's up!

125
00:04:22,680 --> 00:04:24,640
#好出锅
Okay. Take it out of the pot

126
00:04:25,640 --> 00:04:27,520
#关火 关火别烫着了
Turn of the heat. Don't burn yourself

127
00:04:27,960 --> 00:04:28,960
#别烫着
Careful. Don't burn yourself

128
00:04:29,880 --> 00:04:31,440
#把这个汤篦一下
Remove the soup

129
00:04:31,520 --> 00:04:33,160
#它里边有萝卜那个
The soup is contaminated

130
00:04:33,440 --> 00:04:35,120
#多余的臭气
with the odor of the radish

131
00:04:35,280 --> 00:04:36,640
#这汤就不要了
Discard the soup

132
00:04:38,160 --> 00:04:39,120
#翻
Flip it

133
00:04:39,160 --> 00:04:40,440
#1 2 走
One, two, go!

134
00:04:41,680 --> 00:04:43,680
#没事没事 掀你的
It's okay. Go ahead

135
00:04:43,680 --> 00:04:44,440
#没问题
That's perfect

136
00:04:44,440 --> 00:04:46,160
#防止它把这个丝儿冲乱
To prevent (the soup) from disturbing the shredded radish

137
00:04:46,200 --> 00:04:47,680
#上面要搁一个罩
We need to 'shield' it

138
00:04:54,360 --> 00:04:56,280
#蛋皮丝增加颜色
Enrich the color with shredded fried egg

139
00:04:56,280 --> 00:04:59,920
#把中间刀口盖上
Cover the junction in the middle

140
00:05:00,760 --> 00:05:01,680
#咱们还有枸杞
Add some wolfberries too

141
00:05:01,680 --> 00:05:03,160
#这叫封底
That's 'sealing the bottom'

142
00:05:05,160 --> 00:05:06,480
#群英荟萃
Gathering of heroes

143
00:05:06,920 --> 00:05:08,040
#一口鲜
A bite of umami taste

144
00:05:11,800 --> 00:05:14,040
#这个菜还真不一样
This is a unique dish

145
00:05:19,880 --> 00:05:22,080
#我建议多熬点汤
I suggest you to make more soup

146
00:05:22,080 --> 00:05:23,520
#然后随一大碗汤走
And serve the dish with a large bowl of soup

147
00:05:23,520 --> 00:05:26,120
#一人来一小碗一盛就完美了
So that (in a banquet) everyone can have a small bowl of soup.

148
00:05:26,520 --> 00:05:29,240
#这是我跟大爷的一点建议
That's a piece of advice from Da Ye and me

149
00:05:29,240 --> 00:05:30,520
#谢谢二伯
Thank you, Er Bai

150
00:05:30,520 --> 00:05:31,720
#谢谢师父
Thanks, master!

151
00:05:32,480 --> 00:05:34,560
#端出去吧 展示一下
Take it out and show it to everyone

152
00:05:34,560 --> 00:05:36,000
#品尝一下
Let them taste it
