### ISSUE TITLE
[老饭骨] 桃仁酥鸭方 -https://youtu.be/GJH4nGlZcnI

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1662]
**视频链接**：https://youtu.be/GJH4nGlZcnI

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•桃仁酥鸭方】香酥入味、满满鸭肉香！国宴大师的绝招—桃仁酥鸭方!|老饭骨

简介
小友们好，今天大爷给大家带来一道传统老菜——桃仁酥鸭方！
本期视频大爷将会展示完整地处理鸭子的做法，经过香料腌制过的鸭肉，鲜嫩入味。
再加上用虾滑和肥膘肉做的瓤，搭配上桃仁，一口下去，没有失去鸭子的本味，反而更突出主味，满口挂香！

字幕
1
00:00:00,000 --> 00:00:02,560
桃仁排队了啊 一道大菜

2
00:00:02,560 --> 00:00:05,080

3
00:00:07,120 --> 00:00:10,080
鸭子的肛门处（清理干净）

4
00:00:10,080 --> 00:00:12,440
这边呢 鸭骚

5
00:00:12,440 --> 00:00:14,960
可骚了这个 可有味了

6
00:00:14,960 --> 00:00:17,080
我看有舌头没有 没有

7
00:00:17,080 --> 00:00:18,320
这很关键啊

8
00:00:18,320 --> 00:00:20,440
大爷能给您舌头么

9
00:00:20,440 --> 00:00:21,440
那舌头贵着呢

10
00:00:21,440 --> 00:00:23,200
那舌头早卖钱去了

11
00:00:23,200 --> 00:00:25,680
这里有根管 食管

12
00:00:25,680 --> 00:00:27,680
得把管给抽出来

13
00:00:27,680 --> 00:00:29,720
看啊 关键这点的啊

14
00:00:29,720 --> 00:00:32,080
挤出来可都是脏东西

15
00:00:32,080 --> 00:00:35,400
这鸭子里边大脏鼻涕

16
00:00:35,400 --> 00:00:37,760
把这鸭子好好的洗一洗

17
00:00:37,760 --> 00:00:40,000
你看这水 倍儿脏

18
00:00:40,000 --> 00:00:42,080

19
00:00:42,080 --> 00:00:45,840
这鸭子在做之前首先得腌

20
00:00:45,840 --> 00:00:48,240
用盐要搓洗

21
00:00:48,240 --> 00:00:52,000
腿 肚皮里边

22
00:00:52,000 --> 00:00:56,240
拿手（抹匀）让它便于入味

23
00:00:56,240 --> 00:00:59,120
第二步搁香料

24
00:00:59,120 --> 00:01:04,600
大料 花椒 小茴香（桂皮）

25
00:01:04,600 --> 00:01:09,000
料酒 姜葱来点

26
00:01:09,000 --> 00:01:11,880
腌的时候我们腌两个小时

27
00:01:11,880 --> 00:01:14,440
因为鸭子大 得入味

28
00:01:14,440 --> 00:01:16,640
我们时不时就要给它翻一翻

29
00:01:16,640 --> 00:01:19,160
今天咱采取煮的办法

30
00:01:19,160 --> 00:01:21,640
因为咱家没有那么大的蒸锅

31
00:01:21,640 --> 00:01:23,000
这个先腌一会儿

32
00:01:23,000 --> 00:01:26,080
待会儿咱们给它煮上

33
00:01:26,080 --> 00:01:28,160
借这个机会咱们备点料

34
00:01:28,160 --> 00:01:32,640
炒点花椒 晾一晾

35
00:01:32,640 --> 00:01:34,800
这个桃仁我们要在处理的时候

36
00:01:34,800 --> 00:01:36,800
要拿水泡 开水泡

37
00:01:36,800 --> 00:01:39,080
拿牙签把皮给扒下去

38
00:01:39,080 --> 00:01:40,920
要不然它就涩苦

39
00:01:40,920 --> 00:01:42,680
这油温别太大

40
00:01:42,680 --> 00:01:45,680
这一定要用老桃仁 老桃仁香

41
00:01:46,560 --> 00:01:48,960
差不多了 尽快的离开油

42
00:01:48,960 --> 00:01:50,320
为什么要早炸啊

43
00:01:50,320 --> 00:01:52,920
早炸得让它晾凉了 它脆

44
00:01:52,920 --> 00:01:54,600
好了 鸭子够时间了

45
00:01:54,600 --> 00:01:58,320
这个水里边有葱姜 黄酒 盐

46
00:01:58,320 --> 00:02:00,280
盖盖儿

47
00:02:02,000 --> 00:02:03,480
三十五分钟

48
00:02:03,480 --> 00:02:05,760
大爷今儿这个菜都费劲的菜

49
00:02:05,760 --> 00:02:07,360
擀面杖来了

50
00:02:07,360 --> 00:02:10,440
你看这花椒 现在非常酥是吧

51
00:02:10,440 --> 00:02:14,160
在过去 因为在酒店上班

52
00:02:14,160 --> 00:02:16,240
这鸭子不能带骨头

53
00:02:16,240 --> 00:02:19,080
那就好好把这鸭子去骨

54
00:02:19,080 --> 00:02:21,120
去骨这肉少了

55
00:02:21,120 --> 00:02:23,080
肉少了拿虾找补

56
00:02:23,080 --> 00:02:24,640
弄点馅给它一瓤

57
00:02:24,640 --> 00:02:25,720
吃起来又方便

58
00:02:25,720 --> 00:02:28,200
最好吃的还就是虾

59
00:02:28,200 --> 00:02:31,240
你看这个是小窍门啊

60
00:02:31,240 --> 00:02:33,680
找葱芯 为什么啊

61
00:02:33,680 --> 00:02:36,600
你看这葱芯肉厚水分足

62
00:02:36,600 --> 00:02:37,520
这是我师父

63
00:02:37,520 --> 00:02:40,240
教给我这么一个小绝招

64
00:02:40,240 --> 00:02:42,240
李党为什么说你来着了呢

65
00:02:42,880 --> 00:02:45,960
把花椒面和葱混到一起

66
00:02:45,960 --> 00:02:48,880
加上盐 葱椒盐

67
00:02:48,880 --> 00:02:50,160
你看二伯

68
00:02:50,160 --> 00:02:52,400
二伯一看就有丰富的经验

69
00:02:52,400 --> 00:02:54,360
二伯您回答非常正确啊

70
00:02:54,360 --> 00:02:56,880
得到你表扬真不容易

71
00:02:56,880 --> 00:02:58,440
我从来不表扬人

72
00:02:58,440 --> 00:03:01,160
您一下就说对了

73
00:03:01,160 --> 00:03:03,400
你要让李党说李党都说不出来

74
00:03:03,400 --> 00:03:04,800
说不出来 真说不出来

75
00:03:04,800 --> 00:03:07,280
这就是比椒盐好吃啊 香啊

76
00:03:07,280 --> 00:03:08,560
特别香这个

77
00:03:08,560 --> 00:03:09,680
这解决什么问题呢

78
00:03:09,680 --> 00:03:11,920
比如香酥鸡 香酥鸭

79
00:03:11,920 --> 00:03:14,960
有时候这底味 味道不足

80
00:03:14,960 --> 00:03:17,240
原料底下给抹点葱椒盐

81
00:03:17,240 --> 00:03:20,000
这就是师父的绝招在这

82
00:03:20,000 --> 00:03:21,000
而且刚才一剁

83
00:03:21,000 --> 00:03:23,720
花椒的香味跟葱的鲜味

84
00:03:23,720 --> 00:03:25,720
马上就产生出来了

85
00:03:25,880 --> 00:03:28,600
而且那鸭子出来味道就不一样了

86
00:03:28,600 --> 00:03:30,040
你看这刚才准备的

87
00:03:30,040 --> 00:03:31,720
肥膘肉切碎

88
00:03:31,720 --> 00:03:34,280
虾馅 一斤虾肉要搁

89
00:03:34,280 --> 00:03:36,440
二两五左右的肥膘肉

90
00:03:36,440 --> 00:03:39,840
葱姜 搁点酒 这叫什么

91
00:03:39,840 --> 00:03:40,920
葱姜酒水

92
00:03:40,920 --> 00:03:42,840
倒这虾胶里头

93
00:03:42,840 --> 00:03:44,440
淀粉 盐

94
00:03:44,440 --> 00:03:46,280
白胡椒粉 去腥的啊

95
00:03:46,280 --> 00:03:49,400
蛋清也别太多 一半就够了

96
00:03:49,400 --> 00:03:52,280
料都放齐了 抓匀搅拌上劲

97
00:03:52,280 --> 00:03:55,640
这虾胶打的还真是腻乎啊

98
00:03:55,640 --> 00:03:58,080
好 有劲儿了

99
00:03:58,080 --> 00:03:59,640
咱就等鸭子了啊 好嘞

100
00:03:59,640 --> 00:04:00,960
走

101
00:04:02,400 --> 00:04:03,960
咱们这鸭子晾凉了

102
00:04:03,960 --> 00:04:07,400
晾凉了咱们给它把骨头拆了

103
00:04:07,400 --> 00:04:11,960

104
00:04:11,960 --> 00:04:14,160
拆骨的时候脯朝下

105
00:04:14,160 --> 00:04:15,720
拆出来是整个的

106
00:04:15,720 --> 00:04:22,160

107
00:04:22,160 --> 00:04:26,280
我们这拆骨要拆净它

108
00:04:26,280 --> 00:04:26,480

109
00:04:26,480 --> 00:04:29,800
好了 行

110
00:04:29,800 --> 00:04:34,280
撒点淀粉就行 粘上它

111
00:04:34,280 --> 00:04:36,920
它一炸能托一下 

112
00:04:37,920 --> 00:04:39,160
因为这刚做的鸭子

113
00:04:39,160 --> 00:04:41,600
一会炸的时候表面好酥脆

114
00:04:41,600 --> 00:04:43,640
倒油 烧上了啊

115
00:04:43,640 --> 00:04:46,640
葱椒盐 铺上了

116
00:04:46,640 --> 00:04:48,560
铺上了要拍淀粉

117
00:04:49,800 --> 00:04:51,080
这鸭子是新煮的

118
00:04:51,080 --> 00:04:53,120
淀粉要稍微多一点

119
00:04:53,120 --> 00:04:56,040
连拍带弹 定型了啊

120
00:04:56,040 --> 00:05:00,200
这样炸出来它不掉它不散了

121
00:05:00,200 --> 00:05:02,800
这会咱们就开始往上抹馅了

122
00:05:02,800 --> 00:05:04,000

123
00:05:04,000 --> 00:05:05,160
我们厨师啊

124
00:05:05,160 --> 00:05:07,640
不单单是会做菜

125
00:05:07,640 --> 00:05:09,840
还要会瓦匠

126
00:05:09,840 --> 00:05:11,680

127
00:05:11,680 --> 00:05:16,840
要会抹 抹平

128
00:05:16,840 --> 00:05:20,080
薄厚要均匀 好了

129
00:05:20,080 --> 00:05:21,880
还一个关键点

130
00:05:21,880 --> 00:05:23,800

131
00:05:23,800 --> 00:05:28,880
让它彻底馅和鸭肉融为一体

132
00:05:28,880 --> 00:05:30,800
师父这叫什么

133
00:05:30,800 --> 00:05:34,760
这叫瓤 瓤馅儿么

134
00:05:34,760 --> 00:05:37,520
轻轻的排一下 然后再给抹平了

135
00:05:37,520 --> 00:05:39,680
这就是师父的绝招啊

136
00:05:39,680 --> 00:05:41,720
这就是烹饪中的技巧

137
00:05:43,360 --> 00:05:46,240
桃仁 这样你粘完之后

138
00:05:46,240 --> 00:05:50,360
打死它都不会脱了

139
00:05:50,360 --> 00:05:52,720
桃仁排队了啊

140
00:05:52,720 --> 00:05:55,040

141
00:05:55,040 --> 00:05:57,960
一推齐活 一道大菜

142
00:05:57,960 --> 00:06:04,880
往那一出溜 油温六成热

143
00:06:04,880 --> 00:06:07,480
这油温也不能太高 也不能太凉

144
00:06:08,560 --> 00:06:11,720
定型的时候就得高点 先定

145
00:06:11,720 --> 00:06:14,480

146
00:06:14,480 --> 00:06:17,120
融为一个整体了吧

147
00:06:17,800 --> 00:06:20,120
鼓起来了 鼓起就熟了

148
00:06:20,120 --> 00:06:23,760

149
00:06:31,760 --> 00:06:35,960
桃仁酥鸭方 好了

150
00:06:35,960 --> 00:06:37,760
李党给你尝一个 来

151
00:06:37,760 --> 00:06:41,160
张嘴 谢谢二伯

152
00:06:41,160 --> 00:06:43,600

153
00:06:43,600 --> 00:06:46,280
桃仁这个香 满嘴挂香

154
00:06:46,280 --> 00:06:48,120
虾胶这种鲜

155
00:06:48,120 --> 00:06:48,800
鸭子这种特殊的

156
00:06:48,800 --> 00:06:50,400
拿香料腌的这种香味

157
00:06:50,400 --> 00:06:51,520
它没有失本味

158
00:06:51,520 --> 00:06:52,800
但是所有的东西

159
00:06:52,800 --> 00:06:54,520
都是为了突出主味

160
00:06:54,520 --> 00:06:56,040
这个鸭子的香气

161
00:06:56,040 --> 00:06:57,120
大爷我跟您说句话

162
00:06:57,120 --> 00:06:57,920
从始到终

163
00:06:57,920 --> 00:07:00,680
我并没有吃出这葱椒盐的味来

164
00:07:00,680 --> 00:07:02,680
它完全是鸭子的香气

165
00:07:02,680 --> 00:07:05,200
就是他做这东西恰到好处

166
00:07:05,200 --> 00:07:06,720
要没有葱 坏了

167
00:07:08,160 --> 00:07:09,000
要没有葱

168
00:07:09,000 --> 00:07:11,840
它整个的都是花椒味了

169
00:07:11,840 --> 00:07:13,840
所以说呢师父 谢谢您

170
00:07:13,840 --> 00:07:15,000
谢谢师父

171
00:07:15,000 --> 00:07:16,160
今天让我学到了

172
00:07:16,160 --> 00:07:17,200
真正的

173
00:07:17,200 --> 00:07:19,200
而且真正马上快失传的（技法）

174
00:07:19,200 --> 00:07:20,680
我师父今年都65了

175
00:07:20,680 --> 00:07:22,840
很多这样的一个菜品

176
00:07:22,840 --> 00:07:24,440
让我非常激动

177
00:07:24,440 --> 00:07:25,440

178
00:07:25,440 --> 00:07:26,880
感激师父

179
00:07:26,880 --> 00:07:29,640
感谢你拜了这么一个好的师父

180
00:07:29,640 --> 00:07:31,120
给师父深深鞠一躬

181
00:07:31,120 --> 00:07:32,480
谢谢师父

182
00:07:33,360 --> 00:07:34,160
谢谢二伯
```

**Comment by Yingzhang1122** [comment]
#标题（翻译主要意思即可，不要超过 100 个字符）
#【国宴大师•桃仁酥鸭方】香酥入味、满满鸭肉香！国宴大师的绝招—桃仁酥鸭方!|老饭骨
State Banquet Master Chef: Crispy walnut kernel duck cubes

#简介
#小友们好，今天大爷给大家带来一道传统老菜——桃仁酥鸭方！
#本期视频大爷将会展示完整地处理鸭子的做法，经过香料腌制过的鸭肉，鲜嫩入味。
#再加上用虾滑和肥膘肉做的瓤，搭配上桃仁，一口下去，没有失去鸭子的本味，反而更突出主味，满口挂香！
Hello friends! Today Da Ye brings a traditional dish: crispy walnut kernel duck cubes!
In this video, Da Ye will show a complete protocol of processing a duck. The duck will be tender and delicious after marination with spices.
The duck will then be stuffed with mashed shrimp, pork fat, and decorated with walnut kernels. However, these ingredients will not steal the show - in contrast, they dramatically enhance the aroma of duck!

字幕
1
00:00:00,000 --> 00:00:02,560
#桃仁排队了啊 一道大菜
That's walnut kernels lining up! A 'big' dish

2
00:00:02,560 --> 00:00:05,080

3
00:00:07,120 --> 00:00:10,080
#鸭子的肛门处（清理干净）
Clean up the anal area of the duck

4
00:00:10,080 --> 00:00:12,440
#这边呢 鸭骚
Here, (remove) the preen gland #这里我怀疑鸭骚指的是尾脂腺https://en.wikipedia.org/wiki/Uropygial_gland

5
00:00:12,440 --> 00:00:14,960
#可骚了这个 可有味了
This smells really bad. It will produce a terrible flavor

6
00:00:14,960 --> 00:00:17,080
#我看有舌头没有 没有
Let me check if the tongue is still there

7
00:00:17,080 --> 00:00:18,320
#这很关键啊
This is really important

8
00:00:18,320 --> 00:00:20,440
#大爷能给您舌头么
Da Ye, it's not possible that they keep the tongue

9
00:00:20,440 --> 00:00:21,440
#那舌头贵着呢
Tongues are expensive

10
00:00:21,440 --> 00:00:23,200
#那舌头早卖钱去了
They must have sold it

11
00:00:23,200 --> 00:00:25,680
#这里有根管 食管
Here's a tube. The gullet

12
00:00:25,680 --> 00:00:27,680
#得把管给抽出来
We need to pull it out

13
00:00:27,680 --> 00:00:29,720
#看啊 关键这点的啊
Look. This is important

14
00:00:29,720 --> 00:00:32,080
#挤出来可都是脏东西
I am squeezing out the dirty stuff

15
00:00:32,080 --> 00:00:35,400
#这鸭子里边大脏鼻涕
The dirty snot in the duck

16
00:00:35,400 --> 00:00:37,760
#把这鸭子好好的洗一洗
Wash the duck thoroughly

17
00:00:37,760 --> 00:00:40,000
#你看这水 倍儿脏
Look. The water is pretty dirty

18
00:00:40,000 --> 00:00:42,080

19
00:00:42,080 --> 00:00:45,840
#这鸭子在做之前首先得腌
Before cooking, we need to marinate the duck

20
00:00:45,840 --> 00:00:48,240
#用盐要搓洗
Rub it with salt

21
00:00:48,240 --> 00:00:52,000
#腿 肚皮里边
Legs. Inside the belly #还是abdominal cavity？

22
00:00:52,000 --> 00:00:56,240
#拿手（抹匀）让它便于入味
Spread the salt with your hands to let flavor penetrate

23
00:00:56,240 --> 00:00:59,120
#第二步搁香料
Second, add the spices

24
00:00:59,120 --> 00:01:04,600
#大料 花椒 小茴香（桂皮）
Star anise, Sichuan peppercorns, fennel seed (and cinnamon)

25
00:01:04,600 --> 00:01:09,000
#料酒 姜葱来点
Chinese cooking wine, and some ginger and green onion

26
00:01:09,000 --> 00:01:11,880
#腌的时候我们腌两个小时
Marinate the duck for 2 hours

27
00:01:11,880 --> 00:01:14,440
#因为鸭子大 得入味
Because this is a big duck. We need to wait for the flavor penetration

28
00:01:14,440 --> 00:01:16,640
#我们时不时就要给它翻一翻
Flip the duck from time to time

29
00:01:16,640 --> 00:01:19,160
#今天咱采取煮的办法
Today we will boil the duck

30
00:01:19,160 --> 00:01:21,640
#因为咱家没有那么大的蒸锅
Because we don't have a steaming pot that's big enough

31
00:01:21,640 --> 00:01:23,000
#这个先腌一会儿
Let's marinate it for now

32
00:01:23,000 --> 00:01:26,080
#待会儿咱们给它煮上
We'll boil it later

33
00:01:26,080 --> 00:01:28,160
#借这个机会咱们备点料
At this time, prepare some other ingredients

34
00:01:28,160 --> 00:01:32,640
#炒点花椒 晾一晾
Stir-fry some Sichuan peppercorns, then cool them

35
00:01:32,640 --> 00:01:34,800
#这个桃仁我们要在处理的时候
The walnut kernels... when processing it

36
00:01:34,800 --> 00:01:36,800
#要拿水泡 开水泡
You need to soak it with boiling water

37
00:01:36,800 --> 00:01:39,080
#拿牙签把皮给扒下去
Then remove the skin with a toothpick

38
00:01:39,080 --> 00:01:40,920
#要不然它就涩苦
Otherwise it's gonna taste bitter

39
00:01:40,920 --> 00:01:42,680
#这油温别太大
Don't use very high oil temperature

40
00:01:42,680 --> 00:01:45,680
#这一定要用老桃仁 老桃仁香
You must use ripe walnut kernels. They're more aromatic

41
00:01:46,560 --> 00:01:48,960
#差不多了 尽快的离开油
That's almost done. Pick it out from the oil asap

42
00:01:48,960 --> 00:01:50,320
#为什么要早炸啊
Why frying it prior to cooking the duck?

43
00:01:50,320 --> 00:01:52,920
#早炸得让它晾凉了 它脆
We need to cool it down such that it becomes crispy

44
00:01:52,920 --> 00:01:54,600
#好了 鸭子够时间了
Okay. The duck is done

45
00:01:54,600 --> 00:01:58,320
#这个水里边有葱姜 黄酒 盐
There're ginger, green onion, Huangjiu cooking wine, and salt

46
00:01:58,320 --> 00:02:00,280
#盖盖儿
Close the lid

47
00:02:02,000 --> 00:02:03,480
#三十五分钟
35 minutes

48
00:02:03,480 --> 00:02:05,760
#大爷今儿这个菜都费劲的菜
Da Ye is preparing some really complicated dishes today

49
00:02:05,760 --> 00:02:07,360
#擀面杖来了
Here's the rolling pin

50
00:02:07,360 --> 00:02:10,440
#你看这花椒 现在非常酥是吧
Look at the Sichuan peppercorns. Very crispy now, right?

51
00:02:10,440 --> 00:02:14,160
#在过去 因为在酒店上班
In the past, I was working in restaurants

52
00:02:14,160 --> 00:02:16,240
#这鸭子不能带骨头
The duck must be served without bones

53
00:02:16,240 --> 00:02:19,080
#那就好好把这鸭子去骨
So I needed to debone the duck carefully

54
00:02:19,080 --> 00:02:21,120
#去骨这肉少了
However, that'll remove some meat as well

55
00:02:21,120 --> 00:02:23,080
#肉少了拿虾找补
So we compensate with shrimp

56
00:02:23,080 --> 00:02:24,640
#弄点馅给它一瓤
Prepare some mashed shrimp as the stuffing

57
00:02:24,640 --> 00:02:25,720
#吃起来又方便
That's also convenient for eating

58
00:02:25,720 --> 00:02:28,200
#最好吃的还就是虾
Shrimp is the most delicious food

59
00:02:28,200 --> 00:02:31,240
#你看这个是小窍门啊
This is a trick

60
00:02:31,240 --> 00:02:33,680
#找葱芯 为什么啊
Use the core of the green onion

61
00:02:33,680 --> 00:02:36,600
#你看这葱芯肉厚水分足
The green onion core is thick and full of moisture

62
00:02:36,600 --> 00:02:37,520
#这是我师父
This is a small trick

63
00:02:37,520 --> 00:02:40,240
#教给我这么一个小绝招
taught by my master

64
00:02:40,240 --> 00:02:42,240
#李党为什么说你来着了呢
Li Dang, your trip here is worth it

65
00:02:42,880 --> 00:02:45,960
#把花椒面和葱混到一起
Mix the Sichuan peppercorn powder with the minced green onion

66
00:02:45,960 --> 00:02:48,880
#加上盐 葱椒盐
Then add some salt. That's onion-pepper-salt

67
00:02:48,880 --> 00:02:50,160
#你看二伯
Hey, Er Bai

68
00:02:50,160 --> 00:02:52,400
#二伯一看就有丰富的经验
Er Bai is very experienced

69
00:02:52,400 --> 00:02:54,360
#二伯您回答非常正确啊
Er Bai is absolutely right

70
00:02:54,360 --> 00:02:56,880
#得到你表扬真不容易
It's difficult to be praised by you

71
00:02:56,880 --> 00:02:58,440
#我从来不表扬人
I hardly ever praise people

72
00:02:58,440 --> 00:03:01,160
#您一下就说对了
but you got it right immediately

73
00:03:01,160 --> 00:03:03,400
#你要让李党说李党都说不出来
Li Dang cannot answer this question

74
00:03:03,400 --> 00:03:04,800
#说不出来 真说不出来
No, I cannot... Seriously

75
00:03:04,800 --> 00:03:07,280
#这就是比椒盐好吃啊 香啊
This is definitely better than pepper-salt. It's more aromatic

76
00:03:07,280 --> 00:03:08,560
#特别香这个
Extremely aromatic

77
00:03:08,560 --> 00:03:09,680
#这解决什么问题呢
How does it work?

78
00:03:09,680 --> 00:03:11,920
#比如香酥鸡 香酥鸭
Say, when cooking fried crispy chicken or duck

79
00:03:11,920 --> 00:03:14,960
#有时候这底味 味道不足
The base flavor is not strong enough sometimes

80
00:03:14,960 --> 00:03:17,240
#原料底下给抹点葱椒盐
In this case, spread some onion-pepper-salt underneath the meat

81
00:03:17,240 --> 00:03:20,000
#这就是师父的绝招在这
That's a great trick from your master

82
00:03:20,000 --> 00:03:21,000
#而且刚才一剁
Also, as we just chopped it

83
00:03:21,000 --> 00:03:23,720
#花椒的香味跟葱的鲜味
The aromas of peppercorns and green onion...

84
00:03:23,720 --> 00:03:25,720
#马上就产生出来了
are activated immediately

85
00:03:25,880 --> 00:03:28,600
#而且那鸭子出来味道就不一样了
The duck will also taste differently after cooking

86
00:03:28,600 --> 00:03:30,040
#你看这刚才准备的
Look. This is what we just prepared

87
00:03:30,040 --> 00:03:31,720
#肥膘肉切碎
Minced pork fat

88
00:03:31,720 --> 00:03:34,280
#虾馅 一斤虾肉要搁
Mashed shrimp stuffing. In 500 grams of shrimp,

89
00:03:34,280 --> 00:03:36,440
#二两五左右的肥膘肉
We add about 125 g of pork fat

90
00:03:36,440 --> 00:03:39,840
#葱姜 搁点酒 这叫什么
Green onion, ginger, and some cooking wine. What's this?

91
00:03:39,840 --> 00:03:40,920
#葱姜酒水
Onion-ginger-wine

92
00:03:40,920 --> 00:03:42,840
#倒这虾胶里头
Pour it into the shrimp stuffing

93
00:03:42,840 --> 00:03:44,440
#淀粉 盐
Starch and salt

94
00:03:44,440 --> 00:03:46,280
#白胡椒粉 去腥的啊
White pepper powder. This removes the fishy odor

95
00:03:46,280 --> 00:03:49,400
#蛋清也别太多 一半就够了
Don't add too much egg white. Just a half would be enough

96
00:03:49,400 --> 00:03:52,280
#料都放齐了 抓匀搅拌上劲
That's all the ingredients. Mix until it becomes sticky

97
00:03:52,280 --> 00:03:55,640
#这虾胶打的还真是腻乎啊
The shrimp stuffing is indeed very sticky

98
00:03:55,640 --> 00:03:58,080
#好 有劲儿了
Okay. Now it's sticky enough

99
00:03:58,080 --> 00:03:59,640
#咱就等鸭子了啊 好嘞
Let's wait for the duck to be done

100
00:03:59,640 --> 00:04:00,960
#走
Pick it out

101
00:04:02,400 --> 00:04:03,960
#咱们这鸭子晾凉了
After cooling the duck

102
00:04:03,960 --> 00:04:07,400
#晾凉了咱们给它把骨头拆了
Let's remove the bones

103
00:04:07,400 --> 00:04:11,960

104
00:04:11,960 --> 00:04:14,160
#拆骨的时候脯朝下
When deboning, the duck breast should be put towards the chopping board

105
00:04:14,160 --> 00:04:15,720
#拆出来是整个的
In that case, you'll have a complete duck at last

106
00:04:15,720 --> 00:04:22,160

107
00:04:22,160 --> 00:04:26,280
#我们这拆骨要拆净它
We need to remove the bones completely

108
00:04:26,280 --> 00:04:26,480

109
00:04:26,480 --> 00:04:29,800
#好了 行
Ok. It's done

110
00:04:29,800 --> 00:04:34,280
#撒点淀粉就行 粘上它
Sprinkle some starch. Let it stick to the duck

111
00:04:34,280 --> 00:04:36,920
#它一炸能托一下 
When frying, it's gonna hold the duck together#我也不是很明白这里是啥意思...

112
00:04:37,920 --> 00:04:39,160
#因为这刚做的鸭子
The duck is freshly made

113
00:04:39,160 --> 00:04:41,600
#一会炸的时候表面好酥脆
Hence the surface is gonna be crispy after frying

114
00:04:41,600 --> 00:04:43,640
#倒油 烧上了啊
Add some oil. Heating now

115
00:04:43,640 --> 00:04:46,640
#葱椒盐 铺上了
Onion-pepper-salt. Spread on the duck

116
00:04:46,640 --> 00:04:48,560
#铺上了要拍淀粉
After that, pat some starch on the duck

117
00:04:49,800 --> 00:04:51,080
#这鸭子是新煮的
The duck is just boiled

118
00:04:51,080 --> 00:04:53,120
#淀粉要稍微多一点
Hence we need to use more starch

119
00:04:53,120 --> 00:04:56,040
#连拍带弹 定型了啊
Pat it to fix the shape

120
00:04:56,040 --> 00:05:00,200
#这样炸出来它不掉它不散了
Then it's not gonna fall apart when frying

121
00:05:00,200 --> 00:05:02,800
#这会咱们就开始往上抹馅了
Let's apply the stuffing now

122
00:05:02,800 --> 00:05:04,000

123
00:05:04,000 --> 00:05:05,160
#我们厨师啊
As a chef

124
00:05:05,160 --> 00:05:07,640
#不单单是会做菜
Cooking is not our only profession

125
00:05:07,640 --> 00:05:09,840
#还要会瓦匠
We need to be bricklayers sometimes

126
00:05:09,840 --> 00:05:11,680

127
00:05:11,680 --> 00:05:16,840
#要会抹 抹平
You should be able to spread it evenly

128
00:05:16,840 --> 00:05:20,080
#薄厚要均匀 好了
The thickness should be even. That's done

129
00:05:20,080 --> 00:05:21,880
#还一个关键点
One more important trick

130
00:05:21,880 --> 00:05:23,800

131
00:05:23,800 --> 00:05:28,880
#让它彻底馅和鸭肉融为一体
is to fuse the stuffing with the duck completely

132
00:05:28,880 --> 00:05:30,800
#师父这叫什么
What's this trick, master?

133
00:05:30,800 --> 00:05:34,760
#这叫瓤 瓤馅儿么
This is called 'rang'. 'Rang' the stuffing

134
00:05:34,760 --> 00:05:37,520
#轻轻的排一下 然后再给抹平了
Cut it gently. Then flatten the surface again

135
00:05:37,520 --> 00:05:39,680
#这就是师父的绝招啊
That's a secret trick from your master

136
00:05:39,680 --> 00:05:41,720
#这就是烹饪中的技巧
A trick in cooking

137
00:05:43,360 --> 00:05:46,240
#桃仁 这样你粘完之后
The walnut kernel. In this way,

138
00:05:46,240 --> 00:05:50,360
#打死它都不会脱了
The stuffing will never fall from the duck

139
00:05:50,360 --> 00:05:52,720
#桃仁排队了啊
That's walnut kernels lining up

140
00:05:52,720 --> 00:05:55,040

141
00:05:55,040 --> 00:05:57,960
#一推齐活 一道大菜
Press it, done! A 'big' dish

142
00:05:57,960 --> 00:06:04,880
#往那一出溜 油温六成热
Slide it into the wok. The oil temperature is 180 degrees Celsius

143
00:06:04,880 --> 00:06:07,480
#这油温也不能太高 也不能太凉
It shouldn't be too high, nor too low

144
00:06:08,560 --> 00:06:11,720
#定型的时候就得高点 先定
When fixing the shape, you need to use a higher oil temperature

145
00:06:11,720 --> 00:06:14,480

146
00:06:14,480 --> 00:06:17,120
#融为一个整体了吧
That's fusing together

147
00:06:17,800 --> 00:06:20,120
#鼓起来了 鼓起就熟了
It's swelling up. That's done

148
00:06:20,120 --> 00:06:23,760

149
00:06:31,760 --> 00:06:35,960
#桃仁酥鸭方 好了
Crispy walnut kernel duck cubes. Done!

150
00:06:35,960 --> 00:06:37,760
#李党给你尝一个 来
Li Dang, taste it. Come on

151
00:06:37,760 --> 00:06:41,160
#张嘴 谢谢二伯
Open your mouth. Thank you, Er Bai

152
00:06:41,160 --> 00:06:43,600

153
00:06:43,600 --> 00:06:46,280
#桃仁这个香 满嘴挂香
The aroma of walnut kernel stays in the whole mouth

154
00:06:46,280 --> 00:06:48,120
#虾胶这种鲜
The umami taste of the shrimp stuffing

155
00:06:48,120 --> 00:06:48,800
#鸭子这种特殊的
Also the special taste of duck

156
00:06:48,800 --> 00:06:50,400
#拿香料腌的这种香味
The aroma from different spices

157
00:06:50,400 --> 00:06:51,520
#它没有失本味
The original flavor of duck is not gone

158
00:06:51,520 --> 00:06:52,800
#但是所有的东西
All these ingredients...

159
00:06:52,800 --> 00:06:54,520
#都是为了突出主味
serve to emphasize the main flavor

160
00:06:54,520 --> 00:06:56,040
#这个鸭子的香气
The aroma of the duck

161
00:06:56,040 --> 00:06:57,120
#大爷我跟您说句话
Da Ye, let me tell you

162
00:06:57,120 --> 00:06:57,920
#从始到终
From the beginning to the end

163
00:06:57,920 --> 00:07:00,680
#我并没有吃出这葱椒盐的味来
I did not taste the onion-pepper-salt at all

164
00:07:00,680 --> 00:07:02,680
#它完全是鸭子的香气
It's completely the aroma of duck

165
00:07:02,680 --> 00:07:05,200
#就是他做这东西恰到好处
This is perfect cooking

166
00:07:05,200 --> 00:07:06,720
#要没有葱 坏了
If there's no green onion, it's gonna be terrible

167
00:07:08,160 --> 00:07:09,000
#要没有葱
Without the green onion

168
00:07:09,000 --> 00:07:11,840
#它整个的都是花椒味了
It's completely the flavor of peppercorns

169
00:07:11,840 --> 00:07:13,840
#所以说呢师父 谢谢您
So thank you, master

170
00:07:13,840 --> 00:07:15,000
#谢谢师父
Thanks, master

171
00:07:15,000 --> 00:07:16,160
#今天让我学到了
Today I have learnt

172
00:07:16,160 --> 00:07:17,200
#真正的
The real

173
00:07:17,200 --> 00:07:19,200
#而且真正马上快失传的（技法）
cooking technique that's gonna be lost

174
00:07:19,200 --> 00:07:20,680
#我师父今年都65了
My master is 65 years old now

175
00:07:20,680 --> 00:07:22,840
#很多这样的一个菜品
...and many dishes like this

176
00:07:22,840 --> 00:07:24,440
#让我非常激动
I am so excited

177
00:07:24,440 --> 00:07:25,440

178
00:07:25,440 --> 00:07:26,880
#感激师父
I appreciate it a lot for my master

179
00:07:26,880 --> 00:07:29,640
#感谢你拜了这么一个好的师父
You should thank your master a lot, who is so nice and knowledgeable

180
00:07:29,640 --> 00:07:31,120
#给师父深深鞠一躬
Bow to your master

181
00:07:31,120 --> 00:07:32,480
#谢谢师父
Thank you, master!

182
00:07:33,360 --> 00:07:34,160
#谢谢二伯
Thanks, Er Bai
