### ISSUE TITLE
[老饭骨] 黄焖羊肉 - https://youtu.be/ckJ6u-mFW8Q

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1663]
**视频链接**：https://youtu.be/ckJ6u-mFW8Q

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•黄焖羊肉】冬至必吃黄焖羊肉，筋道咸香，河南特色八大碗，忒棒了！ |老饭骨

简介
小友们好，今天是冬至，冬至是养生的大好时机，咱就得来一道羊肉！
有冬至吃水饺习惯的小友也可以复习一下之前做的鲜嫩多汁的【羊肉水饺】https://youtu.be/dugcZPi6VGE
俗话说“气始于冬至”，小友们一定要注意保暖，多吃有营养的食物，今天带来的这道黄焖羊肉是河南特色八大碗之一，羊肉先炸后蒸。炸羊肉的糊不是软炸糊也不是脆皮糊，炸完之后的这糊酥脆，一蒸就软和了，筋道咸香！
豫中平原这块儿，做菜都离不开十三香，加了十三香能够更加突出羊肉的鲜香，又不失其本味，忒棒！

字幕
1
00:00:00,000 --> 00:00:01,800
河南黄焖羊肉

2
00:00:01,800 --> 00:00:04,320
俺过年时候经常吃的一道菜

3
00:00:04,320 --> 00:00:05,440
香啊

4
00:00:05,440 --> 00:00:07,960

5
00:00:07,960 --> 00:00:11,280
今天我带过来的是羊腿肉 前腿

6
00:00:11,280 --> 00:00:12,720
这样的油给它剔掉

7
00:00:12,720 --> 00:00:14,560

8
00:00:14,560 --> 00:00:16,320
给它切成小的滚刀块

9
00:00:16,320 --> 00:00:18,480
有时候切太大了它不好蒸

10
00:00:18,480 --> 00:00:20,600
蒸时间比较长

11
00:00:20,600 --> 00:00:23,680
过春节啊 结婚宴啊 大席桌

12
00:00:23,680 --> 00:00:25,440
这个菜是离不开的

13
00:00:25,440 --> 00:00:26,920
好 腌制一下

14
00:00:26,920 --> 00:00:28,800
干辣椒 两截儿

15
00:00:28,800 --> 00:00:30,120
微微的辣味

16
00:00:30,120 --> 00:00:31,560
花椒 七八个

17
00:00:31,560 --> 00:00:33,160
羊肉还是喜欢花椒的

18
00:00:33,160 --> 00:00:35,120
放个大料 姜片 两个马蹄葱

19
00:00:35,120 --> 00:00:37,480
倒一点点黄酒

20
00:00:37,480 --> 00:00:39,280
盐 这个里边别太咸了

21
00:00:39,280 --> 00:00:41,720
因为汤里面还带一点点味道

22
00:00:41,720 --> 00:00:43,560
老家的一个感觉

23
00:00:43,560 --> 00:00:45,040
就是一定要放一点点十三香

24
00:00:45,040 --> 00:00:47,840
我们豫中平原这一块

25
00:00:47,840 --> 00:00:49,160
基本上吃什么都有

26
00:00:49,160 --> 00:00:51,480
五香粉 十三香离不开

27
00:00:51,480 --> 00:00:54,160
白糖来一点点 就是提鲜的

28
00:00:54,160 --> 00:00:55,920
入一下味 腌一会

29
00:00:55,920 --> 00:00:56,760
咱们这时候打个糊

30
00:00:56,760 --> 00:00:58,720

31
00:00:58,720 --> 00:01:00,520
蒸酥肉

32
00:01:00,520 --> 00:01:02,200
这道菜实惠啊

33
00:01:02,200 --> 00:01:04,080
打这糊呢 不需要脆皮糊

34
00:01:04,080 --> 00:01:05,800
也不需要软炸糊

35
00:01:05,800 --> 00:01:07,920
也不能太酥了 因为它是蒸么

36
00:01:07,920 --> 00:01:10,320
只是放一点面粉

37
00:01:10,320 --> 00:01:11,920
这个面粉跟淀粉的比例

38
00:01:11,920 --> 00:01:13,040
就是二比一

39
00:01:13,040 --> 00:01:17,680
面粉一定是二 淀粉是一

40
00:01:17,680 --> 00:01:21,200
搁一鸡蛋这糊一蒸就软和了

41
00:01:21,200 --> 00:01:23,080
加一点点水

42
00:01:23,080 --> 00:01:25,880
打这个糊的时候不能太稠了

43
00:01:25,880 --> 00:01:29,240
你看它稍微一拉能拉出线来

44
00:01:29,240 --> 00:01:30,760
拉出一条线

45
00:01:30,760 --> 00:01:33,320
这时候羊肉也正好行了

46
00:01:33,320 --> 00:01:35,400
咱们把这糊给倒在羊肉里面

47
00:01:35,400 --> 00:01:37,360
正合适

48
00:01:37,360 --> 00:01:39,000
又不过分的稠 也不稀

49
00:01:39,000 --> 00:01:41,240
充分的抓在上面了

50
00:01:41,240 --> 00:01:42,680
这时候咱们油也烧好了

51
00:01:42,680 --> 00:01:44,440
油温在四成到五成热就行

52
00:01:44,440 --> 00:01:48,000
这就合适 这还到不了五成呢

53
00:01:48,000 --> 00:01:49,400

54
00:01:49,400 --> 00:01:50,960
还有一个给咱网友说一声

55
00:01:50,960 --> 00:01:52,160
炸东西的时候

56
00:01:52,160 --> 00:01:53,800
一定要离油近一点

57
00:01:53,800 --> 00:01:57,560
越近它越不崩 挨着油下

58
00:01:58,520 --> 00:02:01,000
他越害怕越烫手

59
00:02:01,000 --> 00:02:01,040

60
00:02:01,040 --> 00:02:02,480
你看刚才在腌制的

61
00:02:02,480 --> 00:02:05,000
葱跟姜直接就炸里边

62
00:02:05,000 --> 00:02:07,800
它一炸稍微的一起就行了

63
00:02:07,800 --> 00:02:09,920
一定要给它稍微炸干一点点

64
00:02:09,920 --> 00:02:12,400
等一下咱们蒸的时候它会吸

65
00:02:12,400 --> 00:02:14,200
完全吸收原汤

66
00:02:14,200 --> 00:02:16,680
然后蒸出来更加酥烂

67
00:02:16,680 --> 00:02:20,400
咱们这就是一次炸成 一次炸好

68
00:02:20,400 --> 00:02:22,920
然后这时候咱们看这个糊

69
00:02:22,920 --> 00:02:24,800
完全给它炸的就是

70
00:02:24,800 --> 00:02:26,320
一听哗啦哗啦响

71
00:02:26,320 --> 00:02:30,640
而且咱们这个肉基本上也炸熟了

72
00:02:30,640 --> 00:02:33,040
这时候咱们就可以关火

73
00:02:33,040 --> 00:02:35,000
好 下一步调汤

74
00:02:35,000 --> 00:02:36,320

75
00:02:36,320 --> 00:02:38,200
放点底油

76
00:02:38,200 --> 00:02:40,200
一点点花椒粒

77
00:02:40,200 --> 00:02:41,280
葱姜

78
00:02:41,280 --> 00:02:44,120
然后放一点点酱油

79
00:02:44,120 --> 00:02:47,480
加点水

80
00:02:47,480 --> 00:02:49,880
这个颜色你看 说红不红

81
00:02:49,880 --> 00:02:51,960
而且也不能太红 也不能太黑了

82
00:02:51,960 --> 00:02:53,160
有时候煮个羊肉

83
00:02:53,160 --> 00:02:57,440
煮个汤 加里面味道更好

84
00:02:57,440 --> 00:02:59,160
这时候咱们稍微调一下

85
00:02:59,160 --> 00:03:00,520
因为刚才已经加盐了

86
00:03:00,520 --> 00:03:02,360
我们这时候也放一点点盐

87
00:03:02,360 --> 00:03:04,080
放一点点十三香

88
00:03:04,080 --> 00:03:06,000
来一点点白胡椒粉

89
00:03:06,000 --> 00:03:08,480
白胡椒粉

90
00:03:08,480 --> 00:03:10,480
好了 其实特别简单

91
00:03:10,480 --> 00:03:13,400
这时候咱们把这个汤灌上

92
00:03:13,400 --> 00:03:15,560

93
00:03:15,560 --> 00:03:17,760
这时候咱们放个大料

94
00:03:17,760 --> 00:03:19,320
放点葱放点姜

95
00:03:19,320 --> 00:03:22,480
上笼屉 蒸一个小时

96
00:03:22,480 --> 00:03:23,960
来碗蒸羊肉

97
00:03:23,960 --> 00:03:25,320
一个小时到了

98
00:03:25,320 --> 00:03:27,520
拿筷子把这料头拣出来

99
00:03:27,520 --> 00:03:30,640
大料 河南八大碗之一

100
00:03:30,640 --> 00:03:31,720
在我们家里边

101
00:03:31,720 --> 00:03:32,800
你也可以倒出来

102
00:03:32,800 --> 00:03:34,160
也可以不倒出来

103
00:03:34,160 --> 00:03:36,160
也可以在碗里边

104
00:03:38,440 --> 00:03:39,760
香油就是一点点

105
00:03:39,760 --> 00:03:42,800
河南黄焖羊肉 忒好咧

106
00:03:42,800 --> 00:03:47,040

107
00:03:47,040 --> 00:03:47,840
怎么样啊

108
00:03:47,840 --> 00:03:50,040

109
00:03:50,040 --> 00:03:51,320
香啊

110
00:03:51,320 --> 00:03:53,840

111
00:03:53,840 --> 00:03:55,960
还是有点意思

112
00:03:55,960 --> 00:03:58,840
里边很筋道 还有嚼头

113
00:03:58,840 --> 00:04:01,240
李党出锅点了几滴香油

114
00:04:01,240 --> 00:04:02,960
这个太妙了

115
00:04:02,960 --> 00:04:04,840
这一下这味儿 就激发出来了

116
00:04:04,840 --> 00:04:08,200
用酥肉这种方式做羊肉

117
00:04:08,360 --> 00:04:10,440
咱们在北京地区还不常见

118
00:04:10,440 --> 00:04:13,160
出来效果也非常好吃

119
00:04:13,160 --> 00:04:15,360

120
00:04:15,360 --> 00:04:17,200
高手在民间

121
00:04:18,960 --> 00:04:21,480
二伯这一句话就总结性发言
```

**Comment by Yingzhang1122** [comment]
#标题（翻译主要意思即可，不要超过 100 个字符）
#【国宴大师•黄焖羊肉】冬至必吃黄焖羊肉，筋道咸香，河南特色八大碗，忒棒了！ |老饭骨
State Banquet Master Chef: Huang Men Yang Rou (Braised fried lamb)

#简介
#小友们好，今天是冬至，冬至是养生的大好时机，咱就得来一道羊肉！
#有冬至吃水饺习惯的小友也可以复习一下之前做的鲜嫩多汁的【羊肉水饺】https://youtu.be/dugcZPi6VGE
#俗话说“气始于冬至”，小友们一定要注意保暖，多吃有营养的食物，今天带来的这道黄焖羊肉是河南特色八大碗之一，羊肉先炸后蒸。炸羊肉的糊不是软炸糊也不是脆皮糊，炸完之后的这糊酥脆，一蒸就软和了，筋道咸香！
#豫中平原这块儿，做菜都离不开十三香，加了十三香能够更加突出羊肉的鲜香，又不失其本味，忒棒！
Hello friends! Today is winter solstice, a great chance to keep healthy - what's better than a lamb dish?
For friends who enjoy dumplings on winter solstice day please also review our previous video: Lamb dumplings https://youtu.be/dugcZPi6VGE
As a saying goes, 'Qi' (a concept for human energy in traditional Chinese medicine) starts from winter solstice. Hence, please keep yourself warm and eat more healthy food at this time. The dish in this video is one of the 'Eight Special Bowls' in Henan province, in which the lamb was first fried and steamed. The batter that we use here is neither soft-fry batter, nor crispy-fry batter. The batter we use today becomes crispy after frying, but turns soft and chewy after steaming.
In the middle Henan plains, the '13 spices' appear in every dish. Specifically, the lamb in this dish tastes extra delicious with the '13 spices' without losing its original flavor. 

字幕
1
00:00:00,000 --> 00:00:01,800
#河南黄焖羊肉
Henan Huang Men Yang Rou (Braised fried lamb)

2
00:00:01,800 --> 00:00:04,320
#俺过年时候经常吃的一道菜
A dish that I usually have during Chinese New Year

3
00:00:04,320 --> 00:00:05,440
#香啊
Tastes so good

4
00:00:05,440 --> 00:00:07,960

5
00:00:07,960 --> 00:00:11,280
#今天我带过来的是羊腿肉 前腿
The meat that I brought here is the front leg of a lamb

6
00:00:11,280 --> 00:00:12,720
#这样的油给它剔掉
Remove the fat like this

7
00:00:12,720 --> 00:00:14,560

8
00:00:14,560 --> 00:00:16,320
#给它切成小的滚刀块
Cut into small dices

9
00:00:16,320 --> 00:00:18,480
#有时候切太大了它不好蒸
It's hard to steam if cut too large

10
00:00:18,480 --> 00:00:20,600
#蒸时间比较长
The steaming will take a while

11
00:00:20,600 --> 00:00:23,680
#过春节啊 结婚宴啊 大席桌
During spring festival, or on weddings and large banquets

12
00:00:23,680 --> 00:00:25,440
#这个菜是离不开的
You will always see this dish

13
00:00:25,440 --> 00:00:26,920
#好 腌制一下
Ok. Marinate it for a while

14
00:00:26,920 --> 00:00:28,800
#干辣椒 两截儿
Dried chili. Two sections

15
00:00:28,800 --> 00:00:30,120
#微微的辣味
Slight spicy

16
00:00:30,120 --> 00:00:31,560
#花椒 七八个
Sichuan peppercorns. 7 or 8

17
00:00:31,560 --> 00:00:33,160
#羊肉还是喜欢花椒的
Lamb matches well with Sichuan peppercorns

18
00:00:33,160 --> 00:00:35,120
#放个大料 姜片 两个马蹄葱
Add some star anise, ginger slices, and two pieces of green onion

19
00:00:35,120 --> 00:00:37,480
#倒一点点黄酒
Just a little bit huangjiu rice wine

20
00:00:37,480 --> 00:00:39,280
#盐 这个里边别太咸了
Salt. Don't make it too salty

21
00:00:39,280 --> 00:00:41,720
#因为汤里面还带一点点味道
because the soup would be a bit salty as well

22
00:00:41,720 --> 00:00:43,560
#老家的一个感觉
A tradition in my hometown

23
00:00:43,560 --> 00:00:45,040
#就是一定要放一点点十三香
is to add some 'thirteen-spices'

24
00:00:45,040 --> 00:00:47,840
#我们豫中平原这一块
In the middle Henan plains

25
00:00:47,840 --> 00:00:49,160
#基本上吃什么都有
You may see all types of food

26
00:00:49,160 --> 00:00:51,480
#五香粉 十三香离不开
but all of them come with five-spices or thirteen-spices

27
00:00:51,480 --> 00:00:54,160
#白糖来一点点 就是提鲜的
A bit of sugar to elevate the umami taste

28
00:00:54,160 --> 00:00:55,920
#入一下味 腌一会
Let the flavor penetrate. Marinate it for a while

29
00:00:55,920 --> 00:00:56,760
#咱们这时候打个糊
Let's make a batter now

30
00:00:56,760 --> 00:00:58,720

31
00:00:58,720 --> 00:01:00,520
#蒸酥肉
Steamed deep-fried meat

32
00:01:00,520 --> 00:01:02,200
#这道菜实惠啊
That's a fulfilling dish

33
00:01:02,200 --> 00:01:04,080
#打这糊呢 不需要脆皮糊
This batter is not a crispy batter

34
00:01:04,080 --> 00:01:05,800
#也不需要软炸糊
not a soft-fry batter either

35
00:01:05,800 --> 00:01:07,920
#也不能太酥了 因为它是蒸么
You shouldn't make it too crispy. We need to steam it after all

36
00:01:07,920 --> 00:01:10,320
#只是放一点面粉
Just some flour

37
00:01:10,320 --> 00:01:11,920
#这个面粉跟淀粉的比例
The ratio between flour and starch

38
00:01:11,920 --> 00:01:13,040
#就是二比一
is 2:1

39
00:01:13,040 --> 00:01:17,680
#面粉一定是二 淀粉是一
Two portions of flour, one portion of starch

40
00:01:17,680 --> 00:01:21,200
#搁一鸡蛋这糊一蒸就软和了
Add an egg and the batter will be soft after steaming

41
00:01:21,200 --> 00:01:23,080
#加一点点水
A little water

42
00:01:23,080 --> 00:01:25,880
#打这个糊的时候不能太稠了
The batter shouldn't be too heavy

43
00:01:25,880 --> 00:01:29,240
#你看它稍微一拉能拉出线来
See? Lift it and it'll give a stream

44
00:01:29,240 --> 00:01:30,760
#拉出一条线
A stream

45
00:01:30,760 --> 00:01:33,320
#这时候羊肉也正好行了
Now the lamb is ready

46
00:01:33,320 --> 00:01:35,400
#咱们把这糊给倒在羊肉里面
Let's pour the batter into the lamb

47
00:01:35,400 --> 00:01:37,360
#正合适
Right amount

48
00:01:37,360 --> 00:01:39,000
#又不过分的稠 也不稀
Not too heavy, but not light

49
00:01:39,000 --> 00:01:41,240
#充分的抓在上面了
The batter perfectly wraps the lamb

50
00:01:41,240 --> 00:01:42,680
#这时候咱们油也烧好了
Now the oil temperature is high enough

51
00:01:42,680 --> 00:01:44,440
#油温在四成到五成热就行
The temperature should be between 120 and 150 degrees celsius

52
00:01:44,440 --> 00:01:48,000
#这就合适 这还到不了五成呢
That's right. Not 150 degrees yet

53
00:01:48,000 --> 00:01:49,400

54
00:01:49,400 --> 00:01:50,960
#还有一个给咱网友说一声
One more thing to be careful about

55
00:01:50,960 --> 00:01:52,160
#炸东西的时候
When frying stuff

56
00:01:52,160 --> 00:01:53,800
#一定要离油近一点
Make sure you put it close enough to the oil surface

57
00:01:53,800 --> 00:01:57,560
#越近它越不崩 挨着油下
The closer it is, the less oil will be splashed

58
00:01:58,520 --> 00:02:01,000
#他越害怕越烫手
You'll definitely burn yourself if you are afraid

59
00:02:01,000 --> 00:02:01,040

60
00:02:01,040 --> 00:02:02,480
#你看刚才在腌制的
Look. The ginger and green onion that we use for marinating

61
00:02:02,480 --> 00:02:05,000
#葱跟姜直接就炸里边
will also be put into the oil

62
00:02:05,000 --> 00:02:07,800
#它一炸稍微的一起就行了
As soon as the batter slightly swells up, it's done

63
00:02:07,800 --> 00:02:09,920
#一定要给它稍微炸干一点点
Make sure you fry it until it's dry

64
00:02:09,920 --> 00:02:12,400
#等一下咱们蒸的时候它会吸
The meat will absorb the...

65
00:02:12,400 --> 00:02:14,200
#完全吸收原汤
original broth when steaming

66
00:02:14,200 --> 00:02:16,680
#然后蒸出来更加酥烂
And it'll be more soft after steaming

67
00:02:16,680 --> 00:02:20,400
#咱们这就是一次炸成 一次炸好
We just need to fry it once

68
00:02:20,400 --> 00:02:22,920
#然后这时候咱们看这个糊
And the batter...

69
00:02:22,920 --> 00:02:24,800
#完全给它炸的就是
As you can hear

70
00:02:24,800 --> 00:02:26,320
#一听哗啦哗啦响
the noise from colliding batter

71
00:02:26,320 --> 00:02:30,640
#而且咱们这个肉基本上也炸熟了
Also the meat is almost cooked now

72
00:02:30,640 --> 00:02:33,040
#这时候咱们就可以关火
Let's turn off the heat now

73
00:02:33,040 --> 00:02:35,000
#好 下一步调汤
Ok. Let's make a sauce

74
00:02:35,000 --> 00:02:36,320

75
00:02:36,320 --> 00:02:38,200
#放点底油
Some base oil

76
00:02:38,200 --> 00:02:40,200
#一点点花椒粒
Some Sichuan peppercorns

77
00:02:40,200 --> 00:02:41,280
#葱姜
Green onion and ginger

78
00:02:41,280 --> 00:02:44,120
#然后放一点点酱油
Some soysauce

79
00:02:44,120 --> 00:02:47,480
#加点水
Some water

80
00:02:47,480 --> 00:02:49,880
#这个颜色你看 说红不红
The color is a bit red

81
00:02:49,880 --> 00:02:51,960
#而且也不能太红 也不能太黑了
It shouldn't be too red, nor too dark

82
00:02:51,960 --> 00:02:53,160
#有时候煮个羊肉
If you want to make a lamb soup

83
00:02:53,160 --> 00:02:57,440
#煮个汤 加里面味道更好
You can also add this sauce to the soup

84
00:02:57,440 --> 00:02:59,160
#这时候咱们稍微调一下
Let's season it

85
00:02:59,160 --> 00:03:00,520
#因为刚才已经加盐了
We just added some salt

86
00:03:00,520 --> 00:03:02,360
#我们这时候也放一点点盐
So we add a bit more salt here

87
00:03:02,360 --> 00:03:04,080
#放一点点十三香
and a bit 'thirteen-spices'

88
00:03:04,080 --> 00:03:06,000
#来一点点白胡椒粉
Some white pepper powder

89
00:03:06,000 --> 00:03:08,480
#白胡椒粉
white pepper powder

90
00:03:08,480 --> 00:03:10,480
#好了 其实特别简单
Done. This is actually a very simple dish

91
00:03:10,480 --> 00:03:13,400
#这时候咱们把这个汤灌上
Pour the sauce into the meat

92
00:03:13,400 --> 00:03:15,560

93
00:03:15,560 --> 00:03:17,760
#这时候咱们放个大料
Add a star anise

94
00:03:17,760 --> 00:03:19,320
#放点葱放点姜
Some ginger and green onion

95
00:03:19,320 --> 00:03:22,480
#上笼屉 蒸一个小时
Put into the steam pot and steam for one hour

96
00:03:22,480 --> 00:03:23,960
#来碗蒸羊肉
Let's have steamed lamb

97
00:03:23,960 --> 00:03:25,320
#一个小时到了
That's one hour

98
00:03:25,320 --> 00:03:27,520
#拿筷子把这料头拣出来
Pick out the ingredients with chopsticks

99
00:03:27,520 --> 00:03:30,640
#大料 河南八大碗之一
-Star anise. - One of the 'Eight Special Bowls' in Henan

100
00:03:30,640 --> 00:03:31,720
#在我们家里边
In my home

101
00:03:31,720 --> 00:03:32,800
#你也可以倒出来
You can pour the lamb into a larger plate

102
00:03:32,800 --> 00:03:34,160
#也可以不倒出来
Or not

103
00:03:34,160 --> 00:03:36,160
#也可以在碗里边
Just keep it in the bowl

104
00:03:38,440 --> 00:03:39,760
#香油就是一点点
A little bit seasame oil

105
00:03:39,760 --> 00:03:42,800
#河南黄焖羊肉 忒好咧
Henan Huang Men Yang Rou (Braised fried lamb). Fantastic

106
00:03:42,800 --> 00:03:47,040

107
00:03:47,040 --> 00:03:47,840
#怎么样啊
How is it?

108
00:03:47,840 --> 00:03:50,040

109
00:03:50,040 --> 00:03:51,320
#香啊
Tastes so good

110
00:03:51,320 --> 00:03:53,840

111
00:03:53,840 --> 00:03:55,960
#还是有点意思
That's interesting

112
00:03:55,960 --> 00:03:58,840
#里边很筋道 还有嚼头
It's chewy inside

113
00:03:58,840 --> 00:04:01,240
#李党出锅点了几滴香油
Li Dang added a few drops of seasame oil before serving

114
00:04:01,240 --> 00:04:02,960
#这个太妙了
This is a great trick

115
00:04:02,960 --> 00:04:04,840
#这一下这味儿 就激发出来了
The flavor is activated immediately

116
00:04:04,840 --> 00:04:08,200
#用酥肉这种方式做羊肉
Cooking lamb by deep-frying

117
00:04:08,360 --> 00:04:10,440
#咱们在北京地区还不常见
Is a pretty rare method in Beijing

118
00:04:10,440 --> 00:04:13,160
#出来效果也非常好吃
It is very delicious indeed

119
00:04:13,160 --> 00:04:15,360

120
00:04:15,360 --> 00:04:17,200
#高手在民间
Masters always hide in the public

121
00:04:18,960 --> 00:04:21,480
#二伯这一句话就总结性发言
That's a great summary, Er Bai
