### ISSUE TITLE
[老饭骨] 番茄牛肉 - https://youtu.be/G4CBtbGBy8Q

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1677]
**视频链接**：https://youtu.be/G4CBtbGBy8Q

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•番茄牛肉】鲜美浓郁!搭配牛油果的番茄牛肉你一定没吃过!|老饭骨

简介
大家好，今天由二伯带给大家一道鲜美浓郁的番茄牛肉！
这道菜可和我们平时吃过的西红柿炖牛腩可不一样。首先牛腩一定要用冷水去焯，撇出浮沫，并且要反复砸水，这样牛腩才能处理干净，炖牛腩的原汤才会干净！
番茄、西芹和洋葱用黄油炒过之后，加入牛肉汤煮一会儿，还要用粉碎机打碎，食材更加细腻，这样我们做出来的汤才会更加浓郁。
最后加入牛油果，搭配牛油果的牛肉会有一种特殊的香气，吃一口欲罢不能！
小友们快去试试看，这道家常番茄牛肉，真的不一般！

字幕
1
00:00:00,040 --> 00:00:02,360
二伯的番茄牛肉来了

2
00:00:05,320 --> 00:00:07,360
第一步 焯牛肉 牛腩更好

3
00:00:07,360 --> 00:00:08,800
凉水下锅

4
00:00:09,480 --> 00:00:11,760
千万别用热水去焯

5
00:00:11,760 --> 00:00:14,080
搁两根葱稍微去去腥味

6
00:00:14,640 --> 00:00:15,920
姜可以多搁点

7
00:00:16,720 --> 00:00:18,440
老饭骨的黄酒我们来一点

8
00:00:20,800 --> 00:00:22,560
这个沫子要及时撇出 

9
00:00:22,560 --> 00:00:23,800
你要不把它撇出来

10
00:00:23,800 --> 00:00:25,320
它一会滚到肉上去了

11
00:00:25,320 --> 00:00:27,080
以前大爷在清汤的时候

12
00:00:27,080 --> 00:00:28,320
为什么要砸一下

13
00:00:28,320 --> 00:00:29,480
因为外边一紧了以后

14
00:00:29,480 --> 00:00:31,320
这沫子还没出来 锁死了

15
00:00:31,320 --> 00:00:33,680
这砸一下它又张开了

16
00:00:33,680 --> 00:00:34,920
是吧 你看大爷又砸一回

17
00:00:34,920 --> 00:00:36,480
它又出来了 反复的砸

18
00:00:36,480 --> 00:00:37,680
我们这时候可以下个大料

19
00:00:37,680 --> 00:00:38,800
把这肉煮一会

20
00:00:38,800 --> 00:00:39,960
一个两个都没关系

21
00:00:39,960 --> 00:00:41,640
就是说肉多两个也没问题

22
00:00:42,080 --> 00:00:44,000
你看你闻到料香味了吧

23
00:00:44,000 --> 00:00:45,840
这时候大料就扔出去

24
00:00:45,840 --> 00:00:47,880
就不能要了 再要这味就进去了

25
00:00:48,760 --> 00:00:50,160
你看汤清

26
00:00:52,480 --> 00:00:53,760
这样我们就捞出来

27
00:00:54,080 --> 00:00:55,520
料就不要了 搁一边去

28
00:00:56,040 --> 00:00:57,080
这就行了

29
00:00:57,080 --> 00:00:59,120
咱是不是该压了师父 该压

30
00:01:00,400 --> 00:01:02,000
跟着我们就下一些料

31
00:01:02,000 --> 00:01:03,920
一根芹菜 芹菜段

32
00:01:03,920 --> 00:01:05,320
然后洋葱

33
00:01:05,520 --> 00:01:07,120
胡萝卜再来一根

34
00:01:07,720 --> 00:01:08,840
两片香叶

35
00:01:09,440 --> 00:01:11,280
来一个丁香 一到两个

36
00:01:11,280 --> 00:01:12,960
搁个辣椒

37
00:01:12,960 --> 00:01:14,960
别多了 多了就味太重了

38
00:01:16,160 --> 00:01:18,400
压多久呢 压40分钟

39
00:01:21,520 --> 00:01:24,280
好了 40分钟到了

40
00:01:24,280 --> 00:01:26,120
大爷您看看这个 清澈见底

41
00:01:27,560 --> 00:01:29,360
这个时候我再把肉捞出来

42
00:01:30,000 --> 00:01:32,520
肉已经好了 现在开始调味了

43
00:01:34,680 --> 00:01:38,040
黄油啊大爷 黄油增加香气

44
00:01:38,720 --> 00:01:40,240
我先煸葱头

45
00:01:41,480 --> 00:01:44,000
然后这个芹菜一块煸

46
00:01:45,600 --> 00:01:47,360
葱头跟牛肉是绝搭

47
00:01:47,360 --> 00:01:49,760
再加上黄油 西芹

48
00:01:49,760 --> 00:01:50,920
这是我们根据

49
00:01:50,920 --> 00:01:53,200
从西餐改良过来的东西

50
00:01:54,120 --> 00:01:56,640
我们来一片香叶 有一片就够了

51
00:01:57,800 --> 00:01:59,360
现在我们可以

52
00:01:59,360 --> 00:02:01,520
加上番茄酱

53
00:02:01,960 --> 00:02:05,080
番茄酱呢 起增色

54
00:02:05,680 --> 00:02:08,240
番茄沙司 来一点

55
00:02:08,360 --> 00:02:10,240
番茄沙司 起增味

56
00:02:10,480 --> 00:02:12,960
西红柿 搁里边

57
00:02:14,560 --> 00:02:17,840
鲜的番茄是增鲜 你看红亮

58
00:02:18,200 --> 00:02:19,640
下一步我们就可以加上汤了

59
00:02:19,640 --> 00:02:22,720
加上炖制牛肉的原汤 原汤原味

60
00:02:27,600 --> 00:02:29,000
把这捞出来

61
00:02:29,000 --> 00:02:31,280
用粉碎机把它打碎

62
00:02:34,640 --> 00:02:37,720
牛肉汤都搁里边 都搁进去了啊

63
00:02:38,520 --> 00:02:40,640
大爷我把肉下里边了

64
00:02:41,120 --> 00:02:42,600
肉入味

65
00:02:43,720 --> 00:02:45,440
打好的搁进去 很细腻啊

66
00:02:45,440 --> 00:02:47,520
把味道充分（融）进去了

67
00:02:48,120 --> 00:02:51,560
加点老抽因为这颜色它发粉

68
00:02:51,560 --> 00:02:53,480
加点盐

69
00:02:53,680 --> 00:02:55,120
再来点糖

70
00:02:55,120 --> 00:02:56,600
来一点水淀粉

71
00:02:56,600 --> 00:02:57,800
勾点芡

72
00:02:58,680 --> 00:03:03,600
牛油果配这个就是特殊的香气味道

73
00:03:03,600 --> 00:03:06,080
二伯 的番茄牛肉来了

74
00:03:08,360 --> 00:03:10,560
颜色红亮

75
00:03:10,720 --> 00:03:12,480
再加点牛油果 大爷

76
00:03:14,760 --> 00:03:16,320
味道十分鲜美

77
00:03:17,160 --> 00:03:18,800
方法独特

78
00:03:19,080 --> 00:03:20,440
整个要从头到尾要搁着大料

79
00:03:20,440 --> 00:03:21,360
就有大料味了

80
00:03:21,360 --> 00:03:23,680
但是我煮了一会儿我拿掉了

81
00:03:23,680 --> 00:03:25,600
你看见没大料这味 一点没有

82
00:03:25,640 --> 00:03:27,680
这是技巧 香味

83
00:03:27,760 --> 00:03:29,360
还有一个技巧在哪

84
00:03:29,360 --> 00:03:31,120
就是大爷这五砸水

85
00:03:31,120 --> 00:03:32,800
大爷可能砸了五回

86
00:03:33,000 --> 00:03:34,880
他这砸一回 我撇一回沫子

87
00:03:34,880 --> 00:03:36,640
他这砸一回 我撇一回沫子

88
00:03:36,640 --> 00:03:38,240
他通过砸的方法

89
00:03:38,600 --> 00:03:40,640
实际上就把一次次的沫子

90
00:03:40,640 --> 00:03:41,960
就彻底弄透了

91
00:03:42,000 --> 00:03:43,560
你看这汤 清澈到底

92
00:03:43,760 --> 00:03:45,040
这还倍儿鲜
```

**Comment by Yingzhang1122** [comment]
#标题（翻译主要意思即可，不要超过 100 个字符）
#【国宴大师•番茄牛肉】鲜美浓郁!搭配牛油果的番茄牛肉你一定没吃过!|老饭骨
State Banquet Master Chef : Beef and Tomato


#简介
#大家好，今天由二伯带给大家一道鲜美浓郁的番茄牛肉！
#这道菜可和我们平时吃过的西红柿炖牛腩可不一样。首先牛腩一定要用冷水去焯，撇出浮沫，并且要反复砸水，这样牛腩才能处理干净，炖牛腩的原汤才会干净！
#番茄、西芹和洋葱用黄油炒过之后，加入牛肉汤煮一会儿，还要用粉碎机打碎，食材更加细腻，这样我们做出来的汤才会更加浓郁。
#最后加入牛油果，搭配牛油果的牛肉会有一种特殊的香气，吃一口欲罢不能！
#小友们快去试试看，这道家常番茄牛肉，真的不一般！
Hello friends! Er Bai brings an amazingly delicious dish - Beef and Tomato!
This dish is different from the tomato beef brisket stew that we usually have. Firstly, the beef brisket must be blanched with cold water with the scum removed immediately. Cold water should be added into the pot repeatedly to clean up the beef as well as the broth.
The tomato, celery, and onion should be stir-fried with butter, boiled with the original beef broth, and crushed with a blender. In this way, the soup will be creamy, thick, and rich.
Finally, the avacado will give a special aroma in combination with beef, which makes you never drop your chopsticks!
Please try to cook this dish by yourselves - this home-made beef and tomato is incredible!

#字幕
1
00:00:00,040 --> 00:00:02,360
#二伯的番茄牛肉来了
Here it comes - Er Bai's Beef and Tomato!

2
00:00:05,320 --> 00:00:07,360
#第一步 焯牛肉 牛腩更好
First, blanch the beef. Beef brisket is better

3
00:00:07,360 --> 00:00:08,800
#凉水下锅
Blanch with cold water

4
00:00:09,480 --> 00:00:11,760
#千万别用热水去焯
Never use hot water

5
00:00:11,760 --> 00:00:14,080
#搁两根葱稍微去去腥味
Add some green onion to remove the odor

6
00:00:14,640 --> 00:00:15,920
#姜可以多搁点
You may add more ginger

7
00:00:16,720 --> 00:00:18,440
#老饭骨的黄酒我们来一点
Add some Lao Fan Gu's Huangjiu rice wine

8
00:00:20,800 --> 00:00:22,560
#这个沫子要及时撇出 
Remove the scum immediately

9
00:00:22,560 --> 00:00:23,800
#你要不把它撇出来
If you don't remove it now

10
00:00:23,800 --> 00:00:25,320
#它一会滚到肉上去了
It's gonna stick to the meat later

11
00:00:25,320 --> 00:00:27,080
#以前大爷在清汤的时候
Previously when Da Ye was 'cleaning' the broth

12
00:00:27,080 --> 00:00:28,320
#为什么要砸一下
Why did he 'za' (add cold water into) the broth?

13
00:00:28,320 --> 00:00:29,480
#因为外边一紧了以后
Since if the outer surface of the meat shrinks

14
00:00:29,480 --> 00:00:31,320
#这沫子还没出来 锁死了
The scum will stay inside. Locked in the meat

15
00:00:31,320 --> 00:00:33,680
#这砸一下它又张开了
By adding cold water, (the surface) opens again

16
00:00:33,680 --> 00:00:34,920
#是吧 你看大爷又砸一回
Right? Look, Da Ye is adding water again

17
00:00:34,920 --> 00:00:36,480
#它又出来了 反复的砸
More scum is coming out. Add cold water repeatedly

18
00:00:36,480 --> 00:00:37,680
#我们这时候可以下个大料
We can add a star anise now

19
00:00:37,680 --> 00:00:38,800
#把这肉煮一会
Boil it with the meat for a while

20
00:00:38,800 --> 00:00:39,960
#一个两个都没关系
One or two, both ok

21
00:00:39,960 --> 00:00:41,640
#就是说肉多两个也没问题
You may add two (star anise) if you have more meat

22
00:00:42,080 --> 00:00:44,000
#你看你闻到料香味了吧
You can smell the aroma now, right?

23
00:00:44,000 --> 00:00:45,840
#这时候大料就扔出去
Now, pick out the star anise

24
00:00:45,840 --> 00:00:47,880
#就不能要了 再要这味就进去了
We don't need it anymore. Otherwise the flavor gets in

25
00:00:48,760 --> 00:00:50,160
#你看汤清
Look. The broth is clear

26
00:00:52,480 --> 00:00:53,760
#这样我们就捞出来
Pick it out now

27
00:00:54,080 --> 00:00:55,520
#料就不要了 搁一边去
Don't need the star anise now. Put it aside

28
00:00:56,040 --> 00:00:57,080
#这就行了
Done

29
00:00:57,080 --> 00:00:59,120
#咱是不是该压了师父 该压
-Should we use the pressure cooker now, master? -Yes

30
00:01:00,400 --> 00:01:02,000
#跟着我们就下一些料
Then, add some ingredients

31
00:01:02,000 --> 00:01:03,920
#一根芹菜 芹菜段
A celery. Cut into sections

32
00:01:03,920 --> 00:01:05,320
#然后洋葱
Then onion

33
00:01:05,520 --> 00:01:07,120
#胡萝卜再来一根
One carrot

34
00:01:07,720 --> 00:01:08,840
#两片香叶
Two bay leaves

35
00:01:09,440 --> 00:01:11,280
#来一个丁香 一到两个
One clove. One or two

36
00:01:11,280 --> 00:01:12,960
#搁个辣椒
One chili pepper

37
00:01:12,960 --> 00:01:14,960
#别多了 多了就味太重了
Don't add two much. Otherwise it's too strong

38
00:01:16,160 --> 00:01:18,400
#压多久呢 压40分钟
How long? Pressure-cook for 40 minutes. 

39
00:01:21,520 --> 00:01:24,280
#好了 40分钟到了
Okay. It's been 40 minutes now

40
00:01:24,280 --> 00:01:26,120
#大爷您看看这个 清澈见底
Look at this, Da Ye. Clear as you can see the bottom

41
00:01:27,560 --> 00:01:29,360
#这个时候我再把肉捞出来
Now pick out the meat

42
00:01:30,000 --> 00:01:32,520
#肉已经好了 现在开始调味了
Meat is done. Now start seasoning

43
00:01:34,680 --> 00:01:38,040
#黄油啊大爷 黄油增加香气
Butter, Da Ye. Butter enhances the aroma

44
00:01:38,720 --> 00:01:40,240
#我先煸葱头
Stir-fry the onion first

45
00:01:41,480 --> 00:01:44,000
#然后这个芹菜一块煸
Then stir-fry with the celery

46
00:01:45,600 --> 00:01:47,360
#葱头跟牛肉是绝搭
Onion matches perfectly with beef 

47
00:01:47,360 --> 00:01:49,760
#再加上黄油 西芹
Plus butter and celery

48
00:01:49,760 --> 00:01:50,920
#这是我们根据
This is what we ...

49
00:01:50,920 --> 00:01:53,200
#从西餐改良过来的东西
adopted from western food

50
00:01:54,120 --> 00:01:56,640
#我们来一片香叶 有一片就够了
One bay leaf. One is enough

51
00:01:57,800 --> 00:01:59,360
#现在我们可以
Now we can 

52
00:01:59,360 --> 00:02:01,520
#加上番茄酱
Add some tomato paste

53
00:02:01,960 --> 00:02:05,080
#番茄酱呢 起增色
Tomato paste improves the color

54
00:02:05,680 --> 00:02:08,240
#番茄沙司 来一点
Ketchup. Add some

55
00:02:08,360 --> 00:02:10,240
#番茄沙司 起增味
Ketchup enhances the flavor

56
00:02:10,480 --> 00:02:12,960
#西红柿 搁里边
Tomato. Put into the wok

57
00:02:14,560 --> 00:02:17,840
#鲜的番茄是增鲜 你看红亮
Fresh tomato enhances the umami flavor. Look, red and shiny

58
00:02:18,200 --> 00:02:19,640
#下一步我们就可以加上汤了
Next, add the broth

59
00:02:19,640 --> 00:02:22,720
#加上炖制牛肉的原汤 原汤原味
Add some broth from cooking the beef. Original broth, original taste

60
00:02:27,600 --> 00:02:29,000
#把这捞出来
Take this out

61
00:02:29,000 --> 00:02:31,280
#用粉碎机把它打碎
Crush it with a blender

62
00:02:34,640 --> 00:02:37,720
#牛肉汤都搁里边 都搁进去了啊
Pour the broth into the wok. All of it

63
00:02:38,520 --> 00:02:40,640
#大爷我把肉下里边了
Da Ye, I am adding the meat into the wok

64
00:02:41,120 --> 00:02:42,600
#肉入味
The flavor penetrates well into the meat

65
00:02:43,720 --> 00:02:45,440
#打好的搁进去 很细腻啊
Blended vegetables. Very creamy

66
00:02:45,440 --> 00:02:47,520
#把味道充分（融）进去了
The flavor fuses into the dish perfectly

67
00:02:48,120 --> 00:02:51,560
#加点老抽因为这颜色它发粉
Add some dark soy sauce because it looks pink now

68
00:02:51,560 --> 00:02:53,480
#加点盐
Add some salt

69
00:02:53,680 --> 00:02:55,120
#再来点糖
Then some sugar

70
00:02:55,120 --> 00:02:56,600
#来一点水淀粉
Add some slurry

71
00:02:56,600 --> 00:02:57,800
#勾点芡
Thicken the soup

72
00:02:58,680 --> 00:03:03,600
#牛油果配这个就是特殊的香气味道
The avacado produces a special aroma in this dish

73
00:03:03,600 --> 00:03:06,080
#二伯 的番茄牛肉来了
Here it comes - Er Bai's Beef and Tomato!

74
00:03:08,360 --> 00:03:10,560
#颜色红亮
The color is red and bright

75
00:03:10,720 --> 00:03:12,480
#再加点牛油果 大爷
Add some avacado, Da Ye

76
00:03:14,760 --> 00:03:16,320
#味道十分鲜美
The flavor is awesome

77
00:03:17,160 --> 00:03:18,800
#方法独特
The method is unique

78
00:03:19,080 --> 00:03:20,440
#整个要从头到尾要搁着大料
If we keep the star anise from the beginning to the end

79
00:03:20,440 --> 00:03:21,360
#就有大料味了
Its flavor remains in the dish

80
00:03:21,360 --> 00:03:23,680
#但是我煮了一会儿我拿掉了
But I took it out after boiling for a while

81
00:03:23,680 --> 00:03:25,600
#你看见没大料这味 一点没有
You cannot taste it at all

82
00:03:25,640 --> 00:03:27,680
#这是技巧 香味
This is a trick on the aroma

83
00:03:27,760 --> 00:03:29,360
#还有一个技巧在哪
Where's the other trick?

84
00:03:29,360 --> 00:03:31,120
#就是大爷这五砸水
Da Ye added cold water for five times

85
00:03:31,120 --> 00:03:32,800
#大爷可能砸了五回
He might have done it for five times

86
00:03:33,000 --> 00:03:34,880
#他这砸一回 我撇一回沫子
Once he adds cold water, I remove the scum

87
00:03:34,880 --> 00:03:36,640
#他这砸一回 我撇一回沫子
Once he adds cold water, I remove the scum

88
00:03:36,640 --> 00:03:38,240
#他通过砸的方法
By adding cold water repeatedly

89
00:03:38,600 --> 00:03:40,640
#实际上就把一次次的沫子
In fact, the scum

90
00:03:40,640 --> 00:03:41,960
#就彻底弄透了
is removed completely

91
00:03:42,000 --> 00:03:43,560
#你看这汤 清澈到底
Look, the soup is clear as you can see the bottom

92
00:03:43,760 --> 00:03:45,040
#这还倍儿鲜
It's very delicious as well
