### ISSUE TITLE
【美食作家王刚】干锅鸭掌 - https://youtu.be/Eq1LPxKn0wI

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#382]
【美食作家王刚】干锅鸭掌 - https://youtu.be/Eq1LPxKn0wI
视频时长 5:17，预计发布时间为北京时间11月14日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

首先我们冰冻鸭掌几个
将鸭掌的指甲减掉之后备用
其实鸭掌和鸡脚一样很难买到新鲜的
所以建议大家到正规食材购买冻货
下一步开始准备辅料
准备土豆和莲藕各半个去皮之后切成小条备用
同学们可以适量的切粗一些这样下锅不容易碎
准备芹菜几根切成小段备用
芹菜最好不要叶子这样更加清爽
准备大红椒1个切成小片备用
加红椒的目的是配颜色
准备洋葱半个切成丝放入干锅垫底
洋葱切好之后最好抓散这样能均匀受热
下一步开始准备料头
准备适量的生姜和大蒜切成小粒备用
其中大蒜和生姜的比例为4：1
准备麻辣火锅底料40克切散备用
最后再准备适量的干辣椒和青花椒备用
下一步开始制作
首先我们在锅中加入适量的清水
然后将准备好的鸭掌下锅焯水
中途加入适量的啤酒
然后大火烧开
大火烧开之后撇去浮沫
再转小火煮20分钟
这一步的目的是将鸭掌煮制熟透
牙口不好的同学可以煮30分钟以上
20分钟之后将鸭掌倒出控水备用
下一步开始处理辅料
然后我们把锅烧热加入“小宽油”
油温5成热之后加入准备好的土豆和莲藕
同学们注意入料下锅之后必须转小火炸至熟透
辅料熟透之后倒出备用
再少许的底油烧热
油温4成热之后将所有料头下锅
料头下锅之后转小火爆香
中途再加入火锅底料炒香炒化
底料炒化之后将鸭掌下锅翻炒均匀
然后开始调味
加入生抽酱油6克从锅边淋入
加入少许老抽调底色
翻炒均匀之后再加入剩下的啤酒小火烧10分钟
10分钟之后开始调味
锅中就让鸡精1勺
加入少许食用盐调底味
加入少许白糖中和辣味
翻炒几下之后加入红椒片炒至断生
中途加入芹菜和小葱段
再加入炸好的土豆和莲藕条
最后再加入1勺孜然粉和适量的明油翻炒均匀即可出锅装盘
一道非常美味的干锅鸭脚就制作完成
下面开始技术总结
第一，鸭脚最好提前煮软，也可以用高压锅压制8分钟
第二，配菜不受限制可以随意搭配
第三，没有底料的同学可以用豆瓣酱代替
第四，此菜需要控制盐的量防止过咸
干锅鸭掌的技术总结完毕

**Comment by heyitstracccy** [comment]
干锅鸭掌🦆

**Comment by heyitstracccy** [comment]
bot, please upload

0:00:00.040,0:00:01.540
# 哈喽大家好我是王刚
Hi everyone, this is Wang Gang

0:00:01.620,0:00:03.020
# 本期视频我给大家分享一道家常菜
In this video, I'm gonna share you with a homely dish

0:00:03.480,0:00:04.920
# 干锅鸭掌
"Dry pot duck feet"

0:00:05.220,0:00:07.040
# 首先我们解冻冰冻鸭掌几个
First, let's unfreeze some duck feet

0:00:07.280,0:00:09.360
# 将鸭掌的指甲减掉之后备用
Trim the toes and set aside

0:00:09.700,0:00:12.460
# 其实鸭掌和鸡脚一样很难买到新鲜的
It's hard to get the fresh ones

0:00:12.860,0:00:15.260
# 所以建议大家到正规食材购买冻货
I recommend to buy them in big supermarkets

0:00:15.480,0:00:17.420
# 下一步开始准备辅料
Next, we prepare the supplementary ingredients

0:00:17.700,0:00:20.520
# 准备土豆和莲藕各半个去皮之后切成小条备用
Get one potato and half lotus root, remove the skin and cut them into strips

0:00:21.180,0:00:24.040
# 同学们可以适量的切粗一些这样下锅不容易碎
Cut them into thick strips in case broken while cooking

0:00:36.660,0:00:38.520
# 准备芹菜几根切成小段备用
Prepare some celery, cut them into small sections 

0:00:38.680,0:00:40.800
# 芹菜最好不要叶子这样更加清爽
It's better to remove the leaves so that taste more refreshing

0:00:43.660,0:00:45.020
# 准备大红椒1个切成小片备用
Prepare a big red pepper, cut into pieces and set aside 

0:00:45.100,0:00:47.240
# 加红椒的目的是配颜色
It's to add more color

0:00:50.240,0:00:55.340
# 准备洋葱半个切成丝放入干锅垫底
Prepare half onion and cut into thin slices, put them on the bottom of the pot for the base

0:00:59.540,0:01:03.000
# 洋葱切好之后最好抓散这样能均匀受热
Spread the onion so that they can be heated evenly

0:01:03.400,0:01:04.740
# 下一步开始准备料头
Next, we prepare the "liaotou"

0:01:05.120,0:01:07.700
# 准备适量的生姜和大蒜切成小粒备用
Dice some ginger and garlic into small pieces

0:01:07.880,0:01:10.060
# 其中大蒜和生姜的比例为4：1
The proportion of garlic and ginger should be 4:1

0:01:24.000,0:01:26.060
# 准备麻辣火锅底料40克切散备用
Chop 40g hotpot base into smaller pieces

0:01:28.980,0:01:31.900
# 最后再准备适量的干辣椒和青花椒备用
Last we prepare a suitable amount of dried chilies and Sichuan peppercorns

0:01:32.700,0:01:34.380
# 下一步开始制作
Let's start cooking

0:01:34.680,0:01:36.320
# 首先我们在锅中加入适量的清水
First, we add some water into the wok

0:01:37.760,0:01:40.000
# 然后将准备好的鸭掌下锅焯水
Add the duck feet 

0:01:42.320,0:01:43.500
# 中途加入适量的啤酒
Add some beer

0:01:47.855,0:01:49.525
# 然后大火烧开
Bring to a boil on high heat

0:01:52.740,0:01:54.480
# 大火烧开之后撇去浮沫
Remove the floating foam when it comes to a boil

0:01:57.020,0:01:59.060
# 再转小火煮20分钟
Boil for 20 minutes with low heat

0:01:59.320,0:02:01.000
# 这一步的目的是将鸭掌煮制熟透
This is to let them fully cooked

0:02:01.260,0:02:03.000
# 牙口不好的同学可以煮30分钟以上
It's better to boil more than 30 minutes if you like a soft palate

0:02:03.120,0:02:05.860
# 20分钟之后将鸭掌倒出控水备用
Remove the duck feet and set aside to drain dry

0:02:06.400,0:02:07.680
# 下一步开始处理辅料
Next, we cook the supplementary ingredients

0:02:07.860,0:02:16.600
# 然后我们把锅烧热加入“小宽油”
First, we heat the wok and add "xiaokuanyou" (many oil)

0:02:23.100,0:02:25.780
# 油温5成热之后加入准备好的土豆和莲藕
Add prepared potato and lotus root strips when the oil reaches 150℃

0:02:26.660,0:02:29.360
# 同学们注意入料下锅之后必须转小火炸至熟透
Fry them with low heat until fully cooked

0:02:33.215,0:02:35.015
# 辅料熟透之后倒出备用
When they are ready, drain and set aside

0:02:38.660,0:02:40.700
# 再少许的底油烧热
Add some base oil and heat up

0:02:44.600,0:02:47.200
# 油温4成热之后将所有料头下锅
Add all "liaotou" ingredients into the wok when the oil reaches 120℃

0:02:52.385,0:02:54.595
# 料头下锅之后转小火爆香
Turn to low heat, fry them until fragrant

0:03:00.875,0:03:03.125
# 中途再加入火锅底料炒香炒化
Add the hotpot base

0:03:12.155,0:03:14.615
# 底料炒化之后将鸭掌下锅翻炒均匀
Add the duck feet into the wok after the hotpot base is fully incorporated, stir-fry evenly

0:03:21.005,0:03:22.485
# 然后开始调味
Then we start seasoning

0:03:23.020,0:03:25.240
# 加入生抽酱油6克从锅边淋入
Add 6g soy sauce around the sides of the wok

0:03:25.940,0:03:27.920
# 加入少许老抽调底色
Add a little bit dark soy sauce to add color

0:03:30.865,0:03:33.955
# 翻炒均匀之后再加入剩下的啤酒小火烧10分钟
Stir-fry a little bit then add the rest of the beer, cook 10 minutes with low heat

0:03:50.415,0:03:52.545
# 10分钟之后开始调味
Season again after 10 minutes

0:03:53.185,0:03:54.745
# 锅中就让鸡精1勺
Add one teaspoon of chicken essence

0:03:55.480,0:03:57.400
# 加入少许食用盐调底味
Add a little bit salt to add base taste

0:03:57.700,0:03:59.520
# 加入少许白糖中和辣味
Add a little bit of sugar to reduce the spicy taste

0:04:06.345,0:04:08.925
# 翻炒几下之后加入红椒片炒至断生
Stir-fry several times, then add the red pepper

0:04:14.955,0:04:17.105
# 中途加入芹菜和小葱段
Add the celery and green onion

0:04:23.445,0:04:25.615
# 再加入炸好的土豆和莲藕条
Add the fried potato and lotus root

0:04:27.500,0:04:40.440
# 最后再加入1勺孜然粉和适量的明油翻炒均匀即可出锅装盘
Finally, add one teaspoon of cumin powder and a little scallion oil, stir-fry to mix thoroughly, and it's ready to serve

0:04:48.860,0:04:51.240
# 一道非常美味的干锅鸭脚就制作完成
A very tasty dish of "Dry pot duck feet" is completed 

0:04:54.660,0:04:56.180
# 下面开始技术总结
Technical summary:

0:04:56.520,0:05:00.120
# 第一，鸭脚最好提前煮软，也可以用高压锅压制8分钟
Tip1: Duck feet shall be cooked soft in advance, you can use presser cooker to cook 8 minutes

0:05:00.520,0:05:02.760
# 第二，配菜不受限制可以随意搭配
Tip2: Choose whatever vegetable you like  

0:05:02.960,0:05:05.940
# 第三，没有底料的同学可以用豆瓣酱代替
Tip3: Use soy sauce instead if you don't have hotpot base

0:05:06.100,0:05:09.400
# 第四，此菜需要控制盐的量防止过咸
Tip4: Don' add too much salt in case it's too salty

0:05:09.540,0:05:11.240
# 干锅鸭掌的技术总结完毕
That's it for today's technical summary

0:05:11.540,0:05:15.455
Subscribe to my channel, where there's always a dish for you~
