### ISSUE TITLE
【美食作家王刚】酸辣大白菜 - https://youtu.be/RY-KAQQB4ik

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#408]
【美食作家王刚】酸辣大白菜 - https://youtu.be/RY-KAQQB4ik
视频时长 2:35，预计发布时间为北京时间11月23日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.140,0:00:01.360
哈喽大家好，我是王刚

0:00:01.360,0:00:03.080
本期视频我给大家分享一道

0:00:03.080,0:00:04.940
家常版本的酸辣大白菜

0:00:05.140,0:00:07.140
首先我们准备大白菜1颗

0:00:07.380,0:00:09.380
将叶子取下之后对半切开

0:00:09.380,0:00:10.980
然后斜刀切成片备用

0:00:11.140,0:00:13.140
同学们切记不可用铁刀切白菜

0:00:13.140,0:00:14.520
否则会有铁锈味

0:00:14.640,0:00:16.640
也可以用手将其撕成小片

0:00:30.640,0:00:32.640
下一步开始准备辅料

0:00:32.800,0:00:35.500
准备大蒜几颗拍散之后剁成蒜末备用

0:00:41.220,0:00:43.260
准备干辣椒几颗剪成小节备用

0:00:43.480,0:00:45.480
干辣椒的辣度各有不同

0:00:45.800,0:00:48.000
可以根据个人口味和地方选择

0:00:50.220,0:00:52.220
最后准备青红椒各半个切成片备用

0:00:52.220,0:00:53.860
加青红椒的目的是配色

0:00:57.700,0:00:59.700
下一步开始调烹汁

0:00:59.740,0:01:01.740
碗中加入食用盐1勺

0:01:01.740,0:01:03.340
加入生抽酱油3克

0:01:04.740,0:01:05.960
加入香醋3克

0:01:07.800,0:01:09.800
最后加入适量的水淀粉拌匀备用

0:01:12.400,0:01:13.740
下一步开始制作

0:01:14.120,0:01:15.800
首先我们把锅烧热

0:01:15.800,0:01:17.720
锅烧热之后加入适量的底油

0:01:18.060,0:01:20.060
油的量可以适量的多一点

0:01:20.280,0:01:23.600
油温6成热之后加入准备好的蒜末和干辣椒爆香

0:01:28.060,0:01:30.640
料头爆香之后加入切好的辣椒片和白菜

0:01:34.620,0:01:37.420
然后转中大火爆炒40秒炒至断生

0:01:37.620,0:01:40.980
同学们切记在保证白菜不糊的情况下尽量开大火

0:01:41.100,0:01:43.400
否则小火慢炒白菜会容易出水

0:01:43.500,0:01:46.020
大火爆炒40秒之后加入调好的料汁

0:01:50.260,0:01:51.740
然后将其翻炒均匀

0:01:54.240,0:01:57.520
最后在起锅之前加入适量的明油即可出锅装盘

0:02:05.520,0:02:08.340
一道口味酸辣爽口的大白菜就制作完成

0:02:11.240,0:02:12.560
下面开始技术总结

0:02:12.660,0:02:16.600
第一，爆炒白菜不能停火慢慢调味，必须实现兑料汁

0:02:16.860,0:02:21.660
第二，炒白菜必须大火爆炒，可以多加油防止炒糊

0:02:21.820,0:02:27.080
第三，此菜必须最后放盐或者烹料汁，提前调味会导致白菜出水不香

0:02:27.280,0:02:29.520
酸辣大白菜的技术总结完毕

**Comment by Toniayoung** [comment]
这个翻译好了，请问如何上传？

**Comment by Toniayoung** [comment]
bot, please upload Hello everyone this is Wang Gang
In today’s video I will share with you
how to make home styled sweet and sour cabbage
First, let’s prepare a cabbage
cut it in half after pealing the leaves off
Then slant-cut into pieces 
Be sure not to use an iron knife
otherwise the cabbage might have a rusty taste
you could also use your hand to rip it into pieces
Next step is to prepare the side ingredients
crush a few cloves of garlic and chop them up
cut a few dried chilli peppers into pieces
There are different levels of spiciness of dried peppers
you can make your own choice base on your preference
Finally, prepare half of green and red peppers each and cut into pieces
The peppers make a good colour scheme for the dish
The next step is to make the sauce
add a spoonful of salt into a bowl
add 3g of soy sauce
and 3g vinegar 
lastly add some water mixed with starch
Now, let’s start cooking
first, we heat up the pan
add some oil once the pan is heated
we could add a bit more oil than usual
Once the oil reaches 180 degrees, quick-fry the garlic and dried chilli peppers in
then put in the red and green peppers and the cabbage
Make sure to set on high heat 
otherwise the cabbage might become soggy
Stir fry on high heat for 40 seconds then add the sauce
stir fry and mix them well
lastly add some oil and quick-fry for a few seconds, the dish is ready to serve
a tasty dish of sweet and sour cabbage is now finished
Here is a summary for the tips
first, you cannot add seasoning during the cooking process, making the sauce beforehand is necessary.
second, high heat is needed for stir-frying cabbage, you can add some more oil to prevent overcooking the cabbage.
Third, the sauce must be added towards the end. The cabbage will become soggy and less tasty if you add the sauce early
That’s all for the tips.

**Comment by Toniayoung** [comment]
bot, please upload 0:00:00.140,0:00:01.360
哈喽大家好，我是王刚
Hello everyone this is Wang Gang
0:00:01.360,0:00:03.080
本期视频我给大家分享一道
In today’s video I will share with you
0:00:03.080,0:00:04.940
家常版本的酸辣大白菜
how to make home styled sweet and sour Chinese cabbage
0:00:05.140,0:00:07.140
首先我们准备大白菜1颗
First, let’s prepare a Chinese cabbage
0:00:07.380,0:00:09.380
将叶子取下之后对半切开
cut it in half after pealing the leaves off
0:00:09.380,0:00:10.980
然后斜刀切成片备用
Then slant-cut into pieces
0:00:11.140,0:00:13.140
同学们切记不可用铁刀切白菜
Be sure not to use an iron knife
0:00:13.140,0:00:14.520
否则会有铁锈味
otherwise the cabbage might have a rusty taste
0:00:14.640,0:00:16.640
也可以用手将其撕成小片
you could also use your hand to rip it into pieces
0:00:30.640,0:00:32.640
下一步开始准备辅料
Next step is to prepare the side ingredients
0:00:32.800,0:00:35.500
准备大蒜几颗拍散之后剁成蒜末备用
crush a few cloves of garlic and chop them up
0:00:41.220,0:00:43.260
准备干辣椒几颗剪成小节备用
cut a few dried chilli peppers into pieces
0:00:43.480,0:00:45.480
干辣椒的辣度各有不同
There are different levels of spiciness of dried peppers
0:00:45.800,0:00:48.000
可以根据个人口味和地方选择
you can make your own choice base on your preference
0:00:50.220,0:00:52.220
最后准备青红椒各半个切成片备用
Finally, prepare half of green and red peppers each and cut into pieces
0:00:52.220,0:00:53.860
加青红椒的目的是配色
The peppers make a good colour scheme for the dish
0:00:57.700,0:00:59.700
下一步开始调烹汁
The next step is to make the sauce
0:00:59.740,0:01:01.740
碗中加入食用盐1勺
add a spoonful of salt into a bowl
0:01:01.740,0:01:03.340
加入生抽酱油3克
add 3g of soy sauce
0:01:04.740,0:01:05.960
加入香醋3克
and 3g vinegar 
0:01:07.800,0:01:09.800
最后加入适量的水淀粉拌匀备用
lastly add some water mixed with starch
0:01:12.400,0:01:13.740
下一步开始制作
Now, let’s start cooking
0:01:14.120,0:01:15.800
首先我们把锅烧热
first, we heat up the pan
0:01:15.800,0:01:17.720
锅烧热之后加入适量的底油
add some oil once the pan is heated
0:01:18.060,0:01:20.060
油的量可以适量的多一点
we could add a bit more oil than usual
0:01:20.280,0:01:23.600
油温6成热之后加入准备好的蒜末和干辣椒爆香
Once the oil reaches 180 degrees, quick-fry the garlic and dried chilli peppers in
0:01:28.060,0:01:30.640
料头爆香之后加入切好的辣椒片和白菜
then put in the red and green peppers and the cabbage
0:01:34.620,0:01:37.420
然后转中大火爆炒40秒炒至断生
stir fry for 40 seconds on medium-high heat 
0:01:37.620,0:01:40.980
同学们切记在保证白菜不糊的情况下尽量开大火
Make sure to set on high heat 
0:01:41.100,0:01:43.400
否则小火慢炒白菜会容易出水
otherwise the cabbage might become soggy
0:01:43.500,0:01:46.020
大火爆炒40秒之后加入调好的料汁
Stir fry on high heat for 40 seconds then add the sauce
0:01:50.260,0:01:51.740
然后将其翻炒均匀
stir fry and mix them well
0:01:54.240,0:01:57.520
最后在起锅之前加入适量的明油即可出锅装盘
lastly add some oil and quick-fry for a few seconds, the dish is ready to serve
0:02:05.520,0:02:08.340
一道口味酸辣爽口的大白菜就制作完成
a tasty dish of sweet and sour cabbage is now finished
0:02:11.240,0:02:12.560
下面开始技术总结
Here is a summary for the tips
0:02:12.660,0:02:16.600
第一，爆炒白菜不能停火慢慢调味，必须实现兑料汁
first, you cannot add seasoning during the cooking process, making the sauce beforehand is necessary.
0:02:16.860,0:02:21.660
第二，炒白菜必须大火爆炒，可以多加油防止炒糊
second, high heat is needed for stir-frying cabbage, you can add some more oil to prevent overcooking the cabbage.
0:02:21.820,0:02:27.080
第三，此菜必须最后放盐或者烹料汁，提前调味会导致白菜出水不香
Third, the sauce must be added towards the end. The cabbage will become soggy and less tasty if you add the sauce early
0:02:27.280,0:02:29.520
酸辣大白菜的技术总结完毕
That’s all for the tips.
