### ISSUE TITLE
【美食作家王刚】腊鲤鱼 - https://youtu.be/ZpCGMkp3Cjs

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#475]
【美食作家王刚】腊鲤鱼 - https://youtu.be/ZpCGMkp3Cjs
视频时长 6:58，预计发布时间为北京时间12月14日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.080,0:00:01.080
哈喽大家好

0:00:02.200,0:00:05.220
我四伯跟漆二娃再我舅公那边

0:00:05.720,0:00:09.320
我们一起弄了一大盆鱼过来做腊鱼

0:00:09.660,0:00:11.260
就是因为猪肉涨价

0:00:11.760,0:00:14.320
猪肉涨价吃不起 我们弄点腊鱼来吃

0:00:14.960,0:00:16.960
猪肉涨价就吃腊鱼

0:00:17.340,0:00:26.840
现在板鸭竹鼠鸡这些就要便宜点撒

0:00:26.840,0:00:28.840
比猪肉便宜得哪里去了

0:00:28.840,0:00:31.500
我们平时不做这些因为今年猪肉涨价嘛

0:00:31.500,0:00:32.080
是吧

0:00:32.080,0:00:32.580
嗯

0:00:32.580,0:00:34.160
鸡鸭鱼都来一点

0:00:34.340,0:00:35.680
来嘛 我们开始杀鱼嘛

0:00:35.680,0:00:36.600
要得 好

0:00:39.840,0:00:40.880
好生点哈

0:00:58.840,0:01:01.440
来漆二娃 我去炒盐巴去了

0:01:05.880,0:01:07.660
现在差不多了火升起来了

0:01:09.480,0:01:13.020
这里20条鱼大概40斤

0:01:13.340,0:01:16.320
40斤的话我用个6-7斤盐吧

0:01:17.880,0:01:21.840
因为这个鱼做咸一点吧才不会变味

0:01:23.780,0:01:27.580
其实这个跟那个腊鸭腊竹鼠差不多的

0:01:28.460,0:01:30.080
就是放盐进去炒

0:01:30.320,0:01:32.140
炒完了之后放香料

0:01:32.740,0:01:33.600
炒香

0:01:33.600,0:01:36.480
最后涂抹在鱼上面

0:01:37.640,0:01:41.640
腌制过4-6天再拿出来给它挂起来

0:01:42.180,0:01:47.660
喜欢烟熏的可以放点柏树丫熏一下

0:02:02.560,0:02:04.180
四伯爷帮我烧哈火嘛

0:02:04.180,0:02:05.200
好嘛

0:02:05.200,0:02:06.580
这个要搞咸一点哦

0:02:06.600,0:02:08.380
嗯 把它整咸点

0:02:08.380,0:02:10.260
不整咸点（放不久）

0:02:11.160,0:02:13.120
3包6斤盐

0:02:22.820,0:02:24.020
抓一把这个花椒

0:02:24.920,0:02:25.860
整麻点哦

0:02:26.380,0:02:27.000
可以

0:02:27.180,0:02:28.720
再放点干辣椒

0:02:29.320,0:02:30.400
放点八角

0:02:31.920,0:02:33.840
还有那个沙姜

0:02:48.460,0:02:50.320
这个香料一下去（锅）就闻到香了噶

0:03:02.280,0:03:04.200
哎呀 四伯爷来拨哈嘛

0:03:04.200,0:03:05.360
我拨不来

0:03:06.340,0:03:07.220
拨不转噶

0:03:07.220,0:03:09.940
我只有慢慢给你翻一下

0:03:34.540,0:03:36.160
再翻几下

0:03:37.940,0:03:39.940
好这个已经差不多了

0:03:40.420,0:03:42.100
我拿过去等他凉

0:03:42.100,0:03:43.660
凉了之后腌鱼

0:03:45.380,0:03:46.340
四伯爷

0:03:47.220,0:03:48.980
盐巴冷得差不多了我倒进去了哦

0:03:48.980,0:03:50.980
要的呀 要的呀 一哈到进去吗

0:03:51.140,0:03:52.080
哈嘛

0:03:52.300,0:03:53.960
哈看咸不咸哦

0:03:57.800,0:03:59.800
不咸40斤鱼

0:04:00.140,0:04:01.100
你翻哈多

0:04:02.440,0:04:05.520
一个一个的翻 不要急慢慢来

0:04:07.320,0:04:08.360
不要慌

0:04:13.880,0:04:14.580
烫不烫

0:04:14.580,0:04:15.140
不烫

0:04:15.140,0:04:16.040
这哈子不烫了

0:04:16.240,0:04:18.320
诶 不要乱来撒

0:04:18.320,0:04:19.780
好 好不乱来

0:04:20.580,0:04:24.880
还是要看到舒服那样子撒

0:04:25.860,0:04:27.520
好 哪个敢在你面前乱来哦

0:04:27.520,0:04:28.340
开玩笑

0:04:29.560,0:04:30.360
是不是

0:04:30.360,0:04:31.280
是啊

0:04:32.240,0:04:34.240
哎呀 多吃点鱼今年子哈

0:04:34.240,0:04:34.960
好

0:04:35.700,0:04:37.460
少吃肉多吃鱼

0:04:37.760,0:04:40.000
是啊肉好贵嘛

0:04:40.320,0:04:42.720
我们这里这个鲤鱼来8块钱1斤

0:04:42.860,0:04:44.480
8块钱1斤

0:04:44.580,0:04:45.600
猪肉好多呀

0:04:45.820,0:04:49.620
猪肉20斤1斤又回升转来了又是26-27块钱1斤了

0:04:49.940,0:04:52.980
可能到过年又是30-32块钱1斤的肉

0:04:53.660,0:04:54.420
对呀

0:04:55.520,0:04:57.380
1斤肉我们可以吃3斤鱼了

0:04:57.380,0:04:59.300
现在目前这个状况

0:05:01.440,0:05:02.600
好 要得咯

0:05:03.000,0:05:03.860
慢点哈

0:05:04.440,0:05:05.740
要注意哈形象

0:05:07.860,0:05:10.720
这排好看着该安逸嘛

0:05:12.200,0:05:13.280
小心烫哦

0:05:18.140,0:05:18.840
好

0:05:27.440,0:05:29.980
现在我们把它抹均匀了放几天

0:05:30.680,0:05:35.020
放3天吧3天之后再把它穿起来

0:05:35.420,0:05:37.660
给它做个十字架这边架好

0:05:37.660,0:05:42.360
然后再用那个绳子绑起来捆在那个地方

0:05:44.440,0:05:46.440
凉得哪里啊 到时候再熏一下不

0:05:46.620,0:05:50.380
熏就挂在上次哪里熏

0:05:50.920,0:05:54.340
再把它熏一下熏出香味放到过年吃

0:05:54.680,0:05:58.620
要放在楼上下面耗子凶得很耗子跟猫

0:05:59.300,0:06:05.400
哎呀 你看我整的些鸭子拿给那些猫耗子整（咬）了好多哦

0:06:05.400,0:06:07.180
腿腿都那给它咬去了

0:06:07.760,0:06:09.500
我都没享受它还先享受

0:06:10.020,0:06:10.780
它还先吃

0:06:10.780,0:06:11.520
是啊

0:06:12.100,0:06:14.340
但是这个整得这么咸它下得了嘴噶

0:06:14.340,0:06:17.220
嗨呀 它下得到嘴哦

0:06:19.140,0:06:23.920
你看嘛这样跟放盘子一样盘起盘起的多受看多美观撒

0:06:24.960,0:06:30.560
乱七八糟的放起形象都没得

0:06:30.560,0:06:31.840
形象不佳

0:06:33.760,0:06:35.400
看一下我们的杰作

0:06:35.400,0:06:37.640
该好看撒跟美女一样

0:06:38.780,0:06:40.500
你看可以吧

0:06:40.980,0:06:42.300
可以咯可以咯

0:06:42.480,0:06:43.780
要得 走嘛我们抬回去

0:06:43.780,0:06:44.460
好 拜拜

0:06:45.340,0:06:47.980
还没有说拜拜你都晓得要拜拜咯

0:06:47.980,0:06:49.420
那不是咋子安

0:06:51.060,0:06:52.020
来嘛 四伯爷抬哈

0:06:54.480,0:06:55.480
好 拜拜

0:06:55.480,0:06:56.640
拜拜

**Comment by 3yearsyoung** [comment]
I'll take it

**Comment by 3yearsyoung** [comment]
[cured carp.docx](https://github.com/immoonancient/YTSubtitles/files/3962872/cured.carp.docx)

**Comment by 3yearsyoung** [comment]
腊鲤鱼
Cured Carp

如果想支持我或想看更多多幕后周边和我的生活私照的朋友们可以考虑加入”宽油帮“油管会员，点击订阅按钮旁的加入按钮会弹出详情，会员福利如下：
If you’d like to support me or crave for more backstage features and my personal photos, consider joining my YouTube membership “Kuan You Bang”. Just click on the “Join” button next to “Subscribe” and follow the prompts on the pop-up window. Members’ benefits are as follows:
1. 拥有“宽油帮”成长徽章
1. Obtain “Kuan You Bang” badge which can level up over time
2. “宽油”社区动态，独家生活私照和生活分享
2. “Kuan You” Community feed, my exclusive personal photos and life story sharing
3. 拥有更多留言被回复的机会
3. Having more chances of getting your comments replied
名词解释：
Terminologies
宽油：大量的油，很多的油
Kuanyou: A large amount of oil
滑锅：冷油下锅，滑过锅底，使锅的温度迅速提高，并产生油膜，防止粘锅
Huaguo: Pour cold oil into the wok which can significantly increase the wok temperature and produce the oil isolation to prevent food from sticking to the wok
明油：成菜之后淋入一点点葱油，来提高菜品的色泽与明亮度，葱油制作链接https://www.youtube.com/watch?v=K1iUm...
Mingyou: Drizzle with a touch of spring onion infused oil when the dish is done, to brighten up the dish. To know how to make the spring onion infused oil, please click the link below
https://www.youtube.com/watch?v=K1iUm
刀口辣椒：干辣椒干花椒炒香炒脆后，手工切碎即为刀口辣椒，香辣麻三位一体，辣度温和，制作链接 https://www.youtube.com/watch?v=USoC8...
Daokoulajiao: Sauté the dried chilies and Sichuan peppercorns until fragrant and crispy, then crush them by hand. Daokoulajiao is the holy trinity and it’s mild in spiciness. Click on the link below to see how it is made
https://www.youtube.com/watch?v=USoC8
我是王刚，一个草根厨师长，从15岁做学徒到30岁开始在网上教大家做菜，我感恩每一段经历，感恩这个时代，也真心希望通过我的视频可以帮到大家，让大家走进厨房，爱上厨房。我会坚持做菜，坚持教大家做菜。也希望大家来订阅我的YouTube官方频道，欢迎大家点赞、分享和评论。在西瓜视频，头条和微博上也有我相同名字的账户“美食作家王刚”，微信公众号为“厨王刚丝球”，谢谢大家支持！
I’m Wang Gang, a working class chef. I started my career as an apprentice since 15 and began to teach others how to cook at the age of 30. I feel so grateful for every single experience as well as this golden age. I genuinely hope by watching my videos, it can motivate you to walking into the kitchen and fall in love with the kitchen. I will keep cooking and keep teaching you guys how to cook. In the meantime, please subscribe my YouTube channel, and feel free to thumb up, share and leave comments. Alternatively, you may also find my channels on Xi Gua Video, Tou Tiao and Weibo with the identical name. My WeChat channel is called “Chu Wang Gang Si Qiu”, and I appreciate all your support!

0:00:00.080,0:00:01.080
哈喽大家好
Hello everyone
0:00:02.200,0:00:05.220
我四伯跟漆二娃再我舅公那边
My uncle and Qi Erwa were at my granduncle’s place
0:00:05.720,0:00:09.320
我们一起弄了一大盆鱼过来做腊鱼
And we fetched a big tub of carp together to make some cured fish
0:00:09.660,0:00:11.260
就是因为猪肉涨价
This is due to the price hike of pork
0:00:11.760,0:00:14.320
猪肉涨价吃不起 我们弄点腊鱼来吃
Pork is now too expensive to eat, so we will make some cured fish to feed ourselves
0:00:14.960,0:00:16.960
猪肉涨价就吃腊鱼
Time to eat cured fish when the price of pork is increasing
0:00:17.340,0:00:26.840
现在板鸭竹鼠鸡这些就要便宜点撒
Currently, ducks, bamboo rats and chicken are indeed somewhat cheaper
0:00:26.840,0:00:28.840
比猪肉便宜得哪里去了
Way cheaper than pork
0:00:28.840,0:00:31.500
我们平时不做这些因为今年猪肉涨价嘛
We don’t usually make this dish but this year, we have no choice because of the price hikes of pork
0:00:31.500,0:00:32.080
是吧
Is that correct?
0:00:32.080,0:00:32.580
嗯
Yes
0:00:32.580,0:00:34.160
鸡鸭鱼都来一点
Chicken, ducks and fish, we can have a bit of all of them
0:00:34.340,0:00:35.680
来嘛 我们开始杀鱼嘛
Come on, let’s prepare the fish
0:00:35.680,0:00:36.600
要得 好
No problems
0:00:39.840,0:00:40.880
好生点哈
Be careful
0:00:58.840,0:01:01.440
来漆二娃 我去炒盐巴去了
Come here and do this Qi Erwa. I’m going to sauté the salt
0:01:05.880,0:01:07.660
现在差不多了火升起来了
Now the temperature is coming up
0:01:09.480,0:01:13.020
这里20条鱼大概40斤
Here we have 20 carp weighing about 20kg
0:01:13.340,0:01:16.320
40斤的话我用个6-7斤盐吧
Let’s put in 3-3.5kg of the salt
0:01:17.880,0:01:21.840
因为这个鱼做咸一点吧才不会变味
This dish must be made a little bit saltier to avoid being spoilt
0:01:23.780,0:01:27.580
其实这个跟那个腊鸭腊竹鼠差不多的
It’s actually similar to cured ducks and bamboo rats
0:01:28.460,0:01:30.080
就是放盐进去炒
Just pour in the salt and sauté
0:01:30.320,0:01:32.140
炒完了之后放香料
Add in some spices when it’s done
0:01:32.740,0:01:33.600
炒香
Bring up the aroma
0:01:33.600,0:01:36.480
最后涂抹在鱼上面
And lastly massage the mixture onto the fish
0:01:37.640,0:01:41.640
腌制过4-6天再拿出来给它挂起来
Hang them out after curing them for 4-6 days
0:01:42.180,0:01:47.660
喜欢烟熏的可以放点柏树丫熏一下
If you like the smoky flavour, you can always get some cypress branches and smoke the fish
0:02:02.560,0:02:04.180
四伯爷帮我烧哈火嘛
Would you mind helping me with the fire uncle?
0:02:04.180,0:02:05.200
好嘛
Sure
0:02:05.200,0:02:06.580
这个要搞咸一点哦
This has to be salty
0:02:06.600,0:02:08.380
嗯 把它整咸点
Of course, I’ll make it so
0:02:08.380,0:02:10.260
不整咸点（放不久）
If not salty enough, it won’t last long until it goes bad
0:02:11.160,0:02:13.120
3包6斤盐
3 packs totalling 3kg of salt
0:02:22.820,0:02:24.020
抓一把这个花椒
A handful of Sichuan peppercorns
0:02:24.920,0:02:25.860
整麻点哦
Make it a bit numb?
0:02:26.380,0:02:27.000
可以
Why not
0:02:27.180,0:02:28.720
再放点干辣椒
Some dried chillies
0:02:29.320,0:02:30.400
放点八角
Star anises
0:02:31.920,0:02:33.840
还有那个沙姜
And some galangals
0:02:48.460,0:02:50.320
这个香料一下去（锅）就闻到香了噶
You can instantly smell the aroma as soon as the spices go inside
0:03:02.280,0:03:04.200
哎呀 四伯爷来拨哈嘛
Do you want to try to flip the wok uncle?
0:03:04.200,0:03:05.360
我拨不来
No thanks. I can’t do it
0:03:06.340,0:03:07.220
拨不转噶
Hard to flip it around?
0:03:07.220,0:03:09.940
我只有慢慢给你翻一下
I can only stir it slowly for you like this
0:03:34.540,0:03:36.160
再翻几下
A few more times
0:03:37.940,0:03:39.940
好这个已经差不多了
Alright, this is almost done
0:03:40.420,0:03:42.100
我拿过去等他凉
I’ll take it over there for it to cool down
0:03:42.100,0:03:43.660
凉了之后腌鱼
Then cure the fish afterwards
0:03:45.380,0:03:46.340
四伯爷
Uncle
0:03:47.220,0:03:48.980
盐巴冷得差不多了我倒进去了哦
The salt is cool enough. I’m going to pour the salt in
0:03:48.980,0:03:50.980
要的呀 要的呀 一哈到进去吗
Yeah let’s go. All at once?
0:03:51.140,0:03:52.080
哈嘛
Yep
0:03:52.300,0:03:53.960
哈看咸不咸哦
Will it be too salty?
0:03:57.800,0:03:59.800
不咸40斤鱼
It won’t be. There are 20kg of fish in there
0:04:00.140,0:04:01.100
你翻哈多
Would you flip the fish?
0:04:02.440,0:04:05.520
一个一个的翻 不要急慢慢来
One by one, no rush here. Do it slowly
0:04:07.320,0:04:08.360
不要慌
Don’t panic
0:04:13.880,0:04:14.580
烫不烫
Is to too hot?
0:04:14.580,0:04:15.140
不烫
Not at all
0:04:15.140,0:04:16.040
这哈子不烫了
It’s not hot now
0:04:16.240,0:04:18.320
诶 不要乱来撒
Hey, don’t mess it around
0:04:18.320,0:04:19.780
好 好不乱来
OK, I won’t make it messy
0:04:20.580,0:04:24.880
还是要看到舒服那样子撒
It needs to look comforting
0:04:25.860,0:04:27.520
好 哪个敢在你面前乱来哦
All good. Who dares to mess things around in front of you?
0:04:27.520,0:04:28.340
开玩笑
It must be kidding
0:04:29.560,0:04:30.360
是不是
Is that right?
0:04:30.360,0:04:31.280
是啊
Yeah
0:04:32.240,0:04:34.240
哎呀 多吃点鱼今年子哈
Wow, we are eating more fish this year
0:04:34.240,0:04:34.960
好
Definitely
0:04:35.700,0:04:37.460
少吃肉多吃鱼
More fish but less meat
0:04:37.760,0:04:40.000
是啊肉好贵嘛
Yes, as the meat is so expensive
0:04:40.320,0:04:42.720
我们这里这个鲤鱼来8块钱1斤
The carp are sold at only 8 Yuan per 500g
0:04:42.860,0:04:44.480
8块钱1斤
8 Yuan per 500g
0:04:44.580,0:04:45.600
猪肉好多呀
Pork is so expensive in the meantime
0:04:45.820,0:04:49.620
猪肉20斤1斤又回升转来了又是26-27块钱1斤了
It was 20 Yuan per 500g but now it goes back to 26-27 Yuan per 500g
0:04:49.940,0:04:52.980
可能到过年又是30-32块钱1斤的肉
The price could increase to 30-32 Yuan per 500g approaching the Lunar New Year
0:04:53.660,0:04:54.420
对呀
Indeed
0:04:55.520,0:04:57.380
1斤肉我们可以吃3斤鱼了
We can eat 1.5 kg of fish for the price of 500g of meat
0:04:57.380,0:04:59.300
现在目前这个状况
Given the current circumstances
0:05:01.440,0:05:02.600
好 要得咯
Excellent. It looks good
0:05:03.000,0:05:03.860
慢点哈
Take it slowly
0:05:04.440,0:05:05.740
要注意哈形象
Pay attention to plating
0:05:07.860,0:05:10.720
这排好看着该安逸嘛
The whole lot looks much better when arranged neatly
0:05:12.200,0:05:13.280
小心烫哦
Watch out for the heat
0:05:18.140,0:05:18.840
好
Nice
0:05:27.440,0:05:29.980
现在我们把它抹均匀了放几天
Now we have rubbed the fish evenly and they need to be cured for a few days
0:05:30.680,0:05:35.020
放3天吧3天之后再把它穿起来
Maybe just 3 days. We will hang them after 3 days
0:05:35.420,0:05:37.660
给它做个十字架这边架好
Make a cross here for those fish
0:05:37.660,0:05:42.360
然后再用那个绳子绑起来捆在那个地方
And then tie them up with some strings over there
0:05:44.440,0:05:46.440
凉得哪里啊 到时候再熏一下不
Where should I hang them? Are we going to smoke them as well?
0:05:46.620,0:05:50.380
熏就挂在上次哪里熏
Just smoke them there where we did it last time
0:05:50.920,0:05:54.340
再把它熏一下熏出香味放到过年吃
Smoke them until fragrant and save them for the Lunar New Year
0:05:54.680,0:05:58.620
要放在楼上下面耗子凶得很耗子跟猫
They must be hung upstairs. The rats and cats downstairs are so destructive
0:05:59.300,0:06:05.400
哎呀 你看我整的些鸭子拿给那些猫耗子整（咬）了好多哦
Sigh. You know last time I did this, some of my ducks were bitten by those cats and rats
0:06:05.400,0:06:07.180
腿腿都那给它咬去了
Legs were all bitten off
0:06:07.760,0:06:09.500
我都没享受它还先享受
They enjoyed the ducks even before I did 
0:06:10.020,0:06:10.780
它还先吃
They ate first
0:06:10.780,0:06:11.520
是啊
Yep
0:06:12.100,0:06:14.340
但是这个整得这么咸它下得了嘴噶
But this time, the fish are probably too salty for them to eat
0:06:14.340,0:06:17.220
嗨呀 它下得到嘴哦
No way, they can always eat
0:06:19.140,0:06:23.920
你看嘛这样跟放盘子一样盘起盘起的多受看多美观撒
Look, by plating them like this, the fish look like layered plates. How beautiful they are
0:06:24.960,0:06:30.560
乱七八糟的放起形象都没得
It wouldn’t be as good if you had messed the plating
0:06:30.560,0:06:31.840
形象不佳
Bad plating
0:06:33.760,0:06:35.400
看一下我们的杰作
Behold our masterpiece
0:06:35.400,0:06:37.640
该好看撒跟美女一样
It should look as good as beautiful girls
0:06:38.780,0:06:40.500
你看可以吧
Are you happy with it?
0:06:40.980,0:06:42.300
可以咯可以咯
Yes, it’s very good
0:06:42.480,0:06:43.780
要得 走嘛我们抬回去
Great. Let’s carry them back
0:06:43.780,0:06:44.460
好 拜拜
OK, bye bye
0:06:45.340,0:06:47.980
还没有说拜拜你都晓得要拜拜咯
We are not saying goodbye yet and you knew we were finishing?
0:06:47.980,0:06:49.420
那不是咋子安
Or what
0:06:51.060,0:06:52.020
来嘛 四伯爷抬哈
Come on uncle, give me a hand
0:06:54.480,0:06:55.480
好 拜拜
Cool, bye bye
0:06:55.480,0:06:56.640
拜拜
Bye bye

**Comment by 3yearsyoung** [comment]
完全不知道怎么弄。。。

**Comment by 3yearsyoung** [comment]
[cured carp.docx](https://github.com/immoonancient/YTSubtitles/files/3962884/cured.carp.docx)

**Comment by immoonancient** [comment]
@3yearsyoung 你回复 "bot, please upload" 后面加上稿子内容就可以了

像这样https://github.com/immoonancient/YTSubtitles/issues/409#issuecomment-556097944

**Comment by immoonancient** [comment]
bot, please upload

0:00:00.080,0:00:01.080
哈喽大家好
Hello everyone
0:00:02.200,0:00:05.220
我四伯跟漆二娃再我舅公那边
My uncle and Qi Erwa were at my granduncle’s place
0:00:05.720,0:00:09.320
我们一起弄了一大盆鱼过来做腊鱼
And we fetched a big tub of carp together to make some cured fish
0:00:09.660,0:00:11.260
就是因为猪肉涨价
This is due to the price hike of pork
0:00:11.760,0:00:14.320
猪肉涨价吃不起 我们弄点腊鱼来吃
Pork is now too expensive to eat, so we will make some cured fish to feed ourselves
0:00:14.960,0:00:16.960
猪肉涨价就吃腊鱼
Time to eat cured fish when the price of pork is increasing
0:00:17.340,0:00:26.840
现在板鸭竹鼠鸡这些就要便宜点撒
Currently, ducks, bamboo rats and chicken are indeed somewhat cheaper
0:00:26.840,0:00:28.840
比猪肉便宜得哪里去了
Way cheaper than pork
0:00:28.840,0:00:31.500
我们平时不做这些因为今年猪肉涨价嘛
We don’t usually make this dish but this year, we have no choice because of the price hikes of pork
0:00:31.500,0:00:32.080
是吧
Is that correct?
0:00:32.080,0:00:32.580
嗯
Yes
0:00:32.580,0:00:34.160
鸡鸭鱼都来一点
Chicken, ducks and fish, we can have a bit of all of them
0:00:34.340,0:00:35.680
来嘛 我们开始杀鱼嘛
Come on, let’s prepare the fish
0:00:35.680,0:00:36.600
要得 好
No problems
0:00:39.840,0:00:40.880
好生点哈
Be careful
0:00:58.840,0:01:01.440
来漆二娃 我去炒盐巴去了
Come here and do this Qi Erwa. I’m going to sauté the salt
0:01:05.880,0:01:07.660
现在差不多了火升起来了
Now the temperature is coming up
0:01:09.480,0:01:13.020
这里20条鱼大概40斤
Here we have 20 carp weighing about 20kg
0:01:13.340,0:01:16.320
40斤的话我用个6-7斤盐吧
Let’s put in 3-3.5kg of the salt
0:01:17.880,0:01:21.840
因为这个鱼做咸一点吧才不会变味
This dish must be made a little bit saltier to avoid being spoilt
0:01:23.780,0:01:27.580
其实这个跟那个腊鸭腊竹鼠差不多的
It’s actually similar to cured ducks and bamboo rats
0:01:28.460,0:01:30.080
就是放盐进去炒
Just pour in the salt and sauté
0:01:30.320,0:01:32.140
炒完了之后放香料
Add in some spices when it’s done
0:01:32.740,0:01:33.600
炒香
Bring up the aroma
0:01:33.600,0:01:36.480
最后涂抹在鱼上面
And lastly massage the mixture onto the fish
0:01:37.640,0:01:41.640
腌制过4-6天再拿出来给它挂起来
Hang them out after curing them for 4-6 days
0:01:42.180,0:01:47.660
喜欢烟熏的可以放点柏树丫熏一下
If you like the smoky flavour, you can always get some cypress branches and smoke the fish
0:02:02.560,0:02:04.180
四伯爷帮我烧哈火嘛
Would you mind helping me with the fire uncle?
0:02:04.180,0:02:05.200
好嘛
Sure
0:02:05.200,0:02:06.580
这个要搞咸一点哦
This has to be salty
0:02:06.600,0:02:08.380
嗯 把它整咸点
Of course, I’ll make it so
0:02:08.380,0:02:10.260
不整咸点（放不久）
If not salty enough, it won’t last long until it goes bad
0:02:11.160,0:02:13.120
3包6斤盐
3 packs totalling 3kg of salt
0:02:22.820,0:02:24.020
抓一把这个花椒
A handful of Sichuan peppercorns
0:02:24.920,0:02:25.860
整麻点哦
Make it a bit numb?
0:02:26.380,0:02:27.000
可以
Why not
0:02:27.180,0:02:28.720
再放点干辣椒
Some dried chillies
0:02:29.320,0:02:30.400
放点八角
Star anises
0:02:31.920,0:02:33.840
还有那个沙姜
And some galangals
0:02:48.460,0:02:50.320
这个香料一下去（锅）就闻到香了噶
You can instantly smell the aroma as soon as the spices go inside
0:03:02.280,0:03:04.200
哎呀 四伯爷来拨哈嘛
Do you want to try to flip the wok uncle?
0:03:04.200,0:03:05.360
我拨不来
No thanks. I can’t do it
0:03:06.340,0:03:07.220
拨不转噶
Hard to flip it around?
0:03:07.220,0:03:09.940
我只有慢慢给你翻一下
I can only stir it slowly for you like this
0:03:34.540,0:03:36.160
再翻几下
A few more times
0:03:37.940,0:03:39.940
好这个已经差不多了
Alright, this is almost done
0:03:40.420,0:03:42.100
我拿过去等他凉
I’ll take it over there for it to cool down
0:03:42.100,0:03:43.660
凉了之后腌鱼
Then cure the fish afterwards
0:03:45.380,0:03:46.340
四伯爷
Uncle
0:03:47.220,0:03:48.980
盐巴冷得差不多了我倒进去了哦
The salt is cool enough. I’m going to pour the salt in
0:03:48.980,0:03:50.980
要的呀 要的呀 一哈到进去吗
Yeah let’s go. All at once?
0:03:51.140,0:03:52.080
哈嘛
Yep
0:03:52.300,0:03:53.960
哈看咸不咸哦
Will it be too salty?
0:03:57.800,0:03:59.800
不咸40斤鱼
It won’t be. There are 20kg of fish in there
0:04:00.140,0:04:01.100
你翻哈多
Would you flip the fish?
0:04:02.440,0:04:05.520
一个一个的翻 不要急慢慢来
One by one, no rush here. Do it slowly
0:04:07.320,0:04:08.360
不要慌
Don’t panic
0:04:13.880,0:04:14.580
烫不烫
Is to too hot?
0:04:14.580,0:04:15.140
不烫
Not at all
0:04:15.140,0:04:16.040
这哈子不烫了
It’s not hot now
0:04:16.240,0:04:18.320
诶 不要乱来撒
Hey, don’t mess it around
0:04:18.320,0:04:19.780
好 好不乱来
OK, I won’t make it messy
0:04:20.580,0:04:24.880
还是要看到舒服那样子撒
It needs to look comforting
0:04:25.860,0:04:27.520
好 哪个敢在你面前乱来哦
All good. Who dares to mess things around in front of you?
0:04:27.520,0:04:28.340
开玩笑
It must be kidding
0:04:29.560,0:04:30.360
是不是
Is that right?
0:04:30.360,0:04:31.280
是啊
Yeah
0:04:32.240,0:04:34.240
哎呀 多吃点鱼今年子哈
Wow, we are eating more fish this year
0:04:34.240,0:04:34.960
好
Definitely
0:04:35.700,0:04:37.460
少吃肉多吃鱼
More fish but less meat
0:04:37.760,0:04:40.000
是啊肉好贵嘛
Yes, as the meat is so expensive
0:04:40.320,0:04:42.720
我们这里这个鲤鱼来8块钱1斤
The carp are sold at only 8 Yuan per 500g
0:04:42.860,0:04:44.480
8块钱1斤
8 Yuan per 500g
0:04:44.580,0:04:45.600
猪肉好多呀
Pork is so expensive in the meantime
0:04:45.820,0:04:49.620
猪肉20斤1斤又回升转来了又是26-27块钱1斤了
It was 20 Yuan per 500g but now it goes back to 26-27 Yuan per 500g
0:04:49.940,0:04:52.980
可能到过年又是30-32块钱1斤的肉
The price could increase to 30-32 Yuan per 500g approaching the Lunar New Year
0:04:53.660,0:04:54.420
对呀
Indeed
0:04:55.520,0:04:57.380
1斤肉我们可以吃3斤鱼了
We can eat 1.5 kg of fish for the price of 500g of meat
0:04:57.380,0:04:59.300
现在目前这个状况
Given the current circumstances
0:05:01.440,0:05:02.600
好 要得咯
Excellent. It looks good
0:05:03.000,0:05:03.860
慢点哈
Take it slowly
0:05:04.440,0:05:05.740
要注意哈形象
Pay attention to plating
0:05:07.860,0:05:10.720
这排好看着该安逸嘛
The whole lot looks much better when arranged neatly
0:05:12.200,0:05:13.280
小心烫哦
Watch out for the heat
0:05:18.140,0:05:18.840
好
Nice
0:05:27.440,0:05:29.980
现在我们把它抹均匀了放几天
Now we have rubbed the fish evenly and they need to be cured for a few days
0:05:30.680,0:05:35.020
放3天吧3天之后再把它穿起来
Maybe just 3 days. We will hang them after 3 days
0:05:35.420,0:05:37.660
给它做个十字架这边架好
Make a cross here for those fish
0:05:37.660,0:05:42.360
然后再用那个绳子绑起来捆在那个地方
And then tie them up with some strings over there
0:05:44.440,0:05:46.440
凉得哪里啊 到时候再熏一下不
Where should I hang them? Are we going to smoke them as well?
0:05:46.620,0:05:50.380
熏就挂在上次哪里熏
Just smoke them there where we did it last time
0:05:50.920,0:05:54.340
再把它熏一下熏出香味放到过年吃
Smoke them until fragrant and save them for the Lunar New Year
0:05:54.680,0:05:58.620
要放在楼上下面耗子凶得很耗子跟猫
They must be hung upstairs. The rats and cats downstairs are so destructive
0:05:59.300,0:06:05.400
哎呀 你看我整的些鸭子拿给那些猫耗子整（咬）了好多哦
Sigh. You know last time I did this, some of my ducks were bitten by those cats and rats
0:06:05.400,0:06:07.180
腿腿都那给它咬去了
Legs were all bitten off
0:06:07.760,0:06:09.500
我都没享受它还先享受
They enjoyed the ducks even before I did
0:06:10.020,0:06:10.780
它还先吃
They ate first
0:06:10.780,0:06:11.520
是啊
Yep
0:06:12.100,0:06:14.340
但是这个整得这么咸它下得了嘴噶
But this time, the fish are probably too salty for them to eat
0:06:14.340,0:06:17.220
嗨呀 它下得到嘴哦
No way, they can always eat
0:06:19.140,0:06:23.920
你看嘛这样跟放盘子一样盘起盘起的多受看多美观撒
Look, by plating them like this, the fish look like layered plates. How beautiful they are
0:06:24.960,0:06:30.560
乱七八糟的放起形象都没得
It wouldn’t be as good if you had messed the plating
0:06:30.560,0:06:31.840
形象不佳
Bad plating
0:06:33.760,0:06:35.400
看一下我们的杰作
Behold our masterpiece
0:06:35.400,0:06:37.640
该好看撒跟美女一样
It should look as good as beautiful girls
0:06:38.780,0:06:40.500
你看可以吧
Are you happy with it?
0:06:40.980,0:06:42.300
可以咯可以咯
Yes, it’s very good
0:06:42.480,0:06:43.780
要得 走嘛我们抬回去
Great. Let’s carry them back
0:06:43.780,0:06:44.460
好 拜拜
OK, bye bye
0:06:45.340,0:06:47.980
还没有说拜拜你都晓得要拜拜咯
We are not saying goodbye yet and you knew we were finishing?
0:06:47.980,0:06:49.420
那不是咋子安
Or what
0:06:51.060,0:06:52.020
来嘛 四伯爷抬哈
Come on uncle, give me a hand
0:06:54.480,0:06:55.480
好 拜拜
Cool, bye bye
0:06:55.480,0:06:56.640
拜拜
Bye bye
