### ISSUE TITLE
【美食作家王刚】大蒜烧肚条 - https://youtu.be/i1VU70Zrzko

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#501]
【美食作家王刚】大蒜烧肚条 - https://youtu.be/i1VU70Zrzko
视频时长 6:09，预计发布时间为北京时间12月20日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.300,0:00:01.460
哈喽大家好 我是王刚

0:00:01.480,0:00:03.640
本期视频我和大家分享一道家常菜

0:00:03.880,0:00:05.200
大蒜烧肚条

0:00:05.640,0:00:07.740
首先我们准备新鲜的猪肚一个（约750克）

0:00:07.740,0:00:10.600
市场上售卖的猪肚一般都是被摊主翻过来的

0:00:10.720,0:00:14.500
这样看起来更有卖相，同样肥肠也是如此

0:00:14.800,0:00:16.080
下一步开始处理

0:00:16.080,0:00:17.760
首先我们用剪刀将猪肚剪开

0:00:17.980,0:00:20.080
这样更方便内外清洗和处理

0:00:23.380,0:00:26.200
猪肚剪开之后再去除猪肚里面多余的油脂

0:00:26.340,0:00:29.700
这层油脂跟肥肠的不同它有一定的腥味

0:00:29.920,0:00:31.860
去除得约干净越好

0:00:32.020,0:00:34.420
手撕不动的同学也可以用剪刀剪掉

0:00:40.020,0:00:42.200
肥油去除之后加入热水挼（搓）洗几遍

0:00:42.300,0:00:44.740
这一步的目的是去除猪肚表层的胃液

0:00:44.940,0:00:47.180
同学们注意这一步必须用热水挼 （抓）

0:00:47.360,0:00:49.360
否则剩余的肥油容易腻手

0:00:49.500,0:00:52.140
同时对胃酸过敏的同学可以戴手套操作

0:00:52.340,0:00:53.940
以免对手造成腐蚀

0:00:54.060,0:00:55.440
下一步开始深度清理

0:01:01.480,0:01:04.160
首先在盆中加入一把食用盐挼（抓）洗3分钟

0:01:04.160,0:01:06.160
这一步是对猪肚的初步处理

0:01:12.720,0:01:14.980
3分钟之后加入滚水清洗干净

0:01:24.460,0:01:27.040
清洗干净之后再次加入一大把食用盐

0:01:29.240,0:01:31.580
加入适量的高度白酒用力抓5分钟

0:01:31.780,0:01:33.640
这一步的目的是去除腥臭味

0:01:43.320,0:01:45.520
中途再加入一小把干淀粉挼

0:01:45.660,0:01:48.000
加干淀粉的目的是带走抓出来的黏液

0:01:48.180,0:01:51.260
温馨提示：同学们切记此过程比较棘手和辣手

0:01:51.500,0:01:55.200
对胃酸过敏的同学和手上有伤口的同学请谨慎操作

0:01:55.200,0:01:57.700
5分钟之后加入滚水清洗干净备用

0:02:05.620,0:02:07.700
下一步开始准备煮猪肚是辅料

0:02:07.920,0:02:09.980
准备生姜1小块切成姜片备用

0:02:13.580,0:02:15.240
准备大葱1根切成片备用

0:02:19.540,0:02:21.360
碗中加入适量 的高度白酒

0:02:21.360,0:02:22.760
下一步开始煮猪肚

0:02:23.180,0:02:25.360
首先我们在锅中加入大半锅清水

0:02:26.680,0:02:29.480
然后将处理好的猪肚冷水下锅开大火煮开

0:02:36.400,0:02:38.400
大火烧开之后再撇去浮末

0:02:41.660,0:02:43.760
将猪肚焯水定型之后捞出

0:02:48.540,0:02:50.800
然后将剩余的水倒入高压锅中备用

0:02:51.000,0:02:53.560
没有高压锅的同学可以直接煮40分钟

0:02:53.580,0:02:54.920
下一步开始压猪肚

0:02:55.020,0:02:57.040
将捞出的猪肚对半切开

0:03:00.060,0:03:02.460
然后将肚头上面的白色物质刮干净

0:03:02.460,0:03:04.780
这个部位非常腥臭必须去除干净

0:03:05.500,0:03:08.320
处理干净之后放入高压锅里面上汽之后压8分钟

0:03:08.420,0:03:11.880
同学们压制8分钟这个时长可以让猪肚口感爽脆不嫩不老

0:03:12.300,0:03:15.000
喜欢有嚼劲的同学可以减少压制时间

0:03:15.200,0:03:18.260
8分钟之后捞出趁热改刀切成小条备用

0:03:27.960,0:03:29.460
下一步开始准备辅料

0:03:30.340,0:03:31.660
准备莴笋半条

0:03:31.660,0:03:34.660
从中间切开之后再切成跟猪肚大小的条备用

0:03:40.100,0:03:42.100
准备大蒜50克切成小粒备用

0:03:42.240,0:03:45.480
同学们大蒜主要是增香所用可以适当的多加一些

0:03:46.360,0:03:48.420
准备生姜1小块切成姜粒备用

0:03:52.080,0:03:54.080
准备大葱1根切成小粒备用

0:03:59.820,0:04:02.320
最后准备大红椒半个切成小条备用

0:04:04.620,0:04:06.040
下一步开始制作

0:04:09.600,0:04:11.180
首次我们把锅烧热

0:04:11.360,0:04:13.420
锅烧热之后加入适量的油滑锅

0:04:16.380,0:04:19.000
然后将热油倒出加入少许的底油

0:04:24.820,0:04:27.300
油温6成热之后加入切好的料头爆香（大蒜，生姜，葱粒）

0:04:32.820,0:04:36.440
料头爆香之后加入切好的肚条转中火爆炒1分钟

0:04:46.200,0:04:49.040
爆炒1分钟之后加入1碗煮猪肚的原汤

0:04:53.880,0:04:55.620
然后转中小火烧3分钟

0:04:57.500,0:05:00.280
3分钟之后加入切好的笋条和大红椒

0:05:09.240,0:05:10.420
下一步开始调味

0:05:11.120,0:05:12.760
锅中加入食用盐1勺（约2克）

0:05:13.540,0:05:15.060
加入少许白糖提鲜

0:05:15.700,0:05:16.940
加入少许胡椒粉

0:05:19.300,0:05:21.560
调好味之后将辅料烧至断生即可

0:05:23.520,0:05:26.440
辅料断生之后再加入适量的水淀粉把汤汁勾浓

0:05:32.580,0:05:35.480
最后加入适量的明油翻炒均匀即可出锅装盘

0:05:45.700,0:05:48.840
一道非常美味营养的大蒜烧肚条就制作完成

0:05:51.120,0:05:52.640
下面开始技术总结

0:05:52.680,0:05:58.300
第一，猪肚必须加盐，白酒，淀粉抓洗，对酒精过敏的同学可以用白醋代替

0:05:58.340,0:06:03.060
第二，猪肚用高压锅更加节省时间，也可以直接煮40分钟

0:06:03.060,0:06:06.720
第三，此菜咸鲜微辣特别适合老人孩子食用

0:06:06.720,0:06:08.680
大蒜烧肚条的技术总结完毕

**Comment by riana33** [comment]
认领

**Comment by riana33** [comment]
bot, please upload
0:00:00.300,0:00:01.460
# 哈喽大家好 我是王刚
Hello everyone, this is Wang Gang

0:00:01.480,0:00:03.640
# 本期视频我和大家分享一道家常菜
In this video I'll share with you...

0:00:03.880,0:00:05.200
# 大蒜烧肚条
Garlic and pork tripe strips stir-fried

0:00:05.640,0:00:07.740
# 首先我们准备新鲜的猪肚一个（约750克）
First of all, prepare a fresh tripe (about 750g)

0:00:07.740,0:00:10.600
# 市场上售卖的猪肚一般都是被摊主翻过来的
Pork tripe bought from the market is often turned inside out

0:00:10.720,0:00:14.500
# 这样看起来更有卖相，同样肥肠也是如此
It presents better that way, the same for pork intestine

0:00:14.800,0:00:16.080
# 下一步开始处理
Next step, process the tripe

0:00:16.080,0:00:17.760
# 首先我们用剪刀将猪肚剪开
First, cut the tripe open with scissors

0:00:17.980,0:00:20.080
# 这样更方便内外清洗和处理
This makes it easier to clean both the interior and exterior of the tripe

0:00:23.380,0:00:26.200
# 猪肚剪开之后再去除猪肚里面多余的油脂
Remove the excessive fat content inside the tripe

0:00:26.340,0:00:29.700
# 这层油脂跟肥肠的不同它有一定的腥味
Different from port intestine, this layer of fat has a smelly odor

0:00:29.920,0:00:31.860
# 去除得约干净越好
So try your best eliminating it

0:00:32.020,0:00:34.420
# 手撕不动的同学也可以用剪刀剪掉
If you cannot tear it off, try scissors

0:00:40.020,0:00:42.200
# 肥油去除之后加入热水挼（搓）洗几遍
When done, rub the tripe thoroughly with hot water

0:00:42.300,0:00:44.740
# 这一步的目的是去除猪肚表层的胃液
Rubbing would wash off any unwanted gastric juice on the surface of the tribe

0:00:44.940,0:00:47.180
# 同学们注意这一步必须用热水挼 （抓）
Make sure that you rub with hot water...

0:00:47.360,0:00:49.360
# 否则剩余的肥油容易腻手
Or the fat residual might stick to your hand

0:00:49.500,0:00:52.140
# 同时对胃酸过敏的同学可以戴手套操作
People allergic to gastric acid may use gloves

0:00:52.340,0:00:53.940
# 以免对手造成腐蚀
It also protects your hands from the acid

0:00:54.060,0:00:55.440
# 下一步开始深度清理
Next, deep cleaning to the tripe

0:01:01.480,0:01:04.160
#首先在盆中加入一把食用盐挼（抓）洗3分钟
Add a grain of salt, then rub it for 3 minutes

0:01:04.160,0:01:06.160
# 这一步是对猪肚的初步处理
This gives the tripe a primary processing

0:01:12.720,0:01:14.980
# 3分钟之后加入滚水清洗干净
After 3 minutes, pour in boiling water to rinse it off

0:01:24.460,0:01:27.040
# 清洗干净之后再次加入一大把食用盐
Add a generous handful of salt after draining the water

0:01:29.240,0:01:31.580
# 加入适量的高度白酒用力抓5分钟
Add some strong liquor to rub the tripe hard for another 5 minutes

0:01:31.780,0:01:33.640
# 这一步的目的是去除腥臭味
This should eliminate all the odor

0:01:43.320,0:01:45.520
# 中途再加入一小把干淀粉挼
Add a grain of starch and continue rubbing the tripe

0:01:45.660,0:01:48.000
# 加干淀粉的目的是带走抓出来的黏液
Starch helps to remove the slime as an unwanted product from the preparation process

0:01:48.180,0:01:51.260
# 温馨提示：同学们切记此过程比较棘手和辣手
Note that this step can burn your hands...

0:01:51.500,0:01:55.200
# 对胃酸过敏的同学和手上有伤口的同学请谨慎操作
Again, if you are allergic to gastric acid or wounded, practice this step with care and caution  

0:01:55.200,0:01:57.700
# 5分钟之后加入滚水清洗干净备用
After 5 minutes, add boiling water to clean the tripe and set it aside

0:02:05.620,0:02:07.700
# 下一步开始准备煮猪肚是辅料
Next step, prepare the aromatics for boiling the tripe

0:02:07.920,0:02:09.980
# 准备生姜1小块切成姜片备用
Slice up a small chunk of ginger

0:02:13.580,0:02:15.240
# 准备大葱1根切成片备用
Also slice some scallions, set aside

0:02:19.540,0:02:21.360
# 碗中加入适量 的高度白酒
Add some strong baijiu liquor into the bowl

0:02:21.360,0:02:22.760
# 下一步开始煮猪肚
Add some strong baijiu liquor into the bowl

0:02:23.180,0:02:25.360
# 首先我们在锅中加入大半锅清水
Add a lot of water into the wok

0:02:26.680,0:02:29.480
# 然后将处理好的猪肚冷水下锅开大火煮开
Add the tripe into the cold water directly, and then boil over high heat

0:02:36.400,0:02:38.400
# 大火烧开之后再撇去浮末
Skim off the scums after it boils

0:02:41.660,0:02:43.760
# 将猪肚焯水定型之后捞出
Take the tripe out

0:02:48.540,0:02:50.800
#然后将剩余的水倒入高压锅中备用
Transfer the boiled water to the pressure cooker

0:02:51.000,0:02:53.560
#没有高压锅的同学可以直接煮40分钟
If you do not have a pressure cooker, boil the tripe for 40 minutes in a regular pot

0:02:53.580,0:02:54.920
#下一步开始压猪肚
Next step: pressure cooking the tripe

0:02:55.020,0:02:57.040
# 将捞出的猪肚对半切开
Cut the tripe in half

0:03:00.060,0:03:02.460
# 然后将肚头上面的白色物质刮干净
Scrape off the white substances on the "head" of the tripe

0:03:02.460,0:03:04.780
# 这个部位非常腥臭必须去除干净
It is crucial to clean this place thoroughly to avoid bringing odor into the dish

0:03:05.500,0:03:08.320
# 处理干净之后放入高压锅里面上汽之后压8分钟
When done, put the tripe back to the pressure cooker to cook for another 8 minutes

0:03:08.420,0:03:11.880
# 同学们压制8分钟这个时长可以让猪肚口感爽脆不嫩不老
Remember that it takes 8 minutes to achieve the ideal crunchy texture for our dish that is neither too tender nor too chewy

0:03:12.300,0:03:15.000
喜欢有嚼劲的同学可以减少压制时间
If you prefer the tripe to be chewy, reduce the cooking time to your preference

0:03:15.200,0:03:18.260
# 8分钟之后捞出趁热改刀切成小条备用
After 8 minutes, take the tripe out

0:03:27.960,0:03:29.460
# 下一步开始准备辅料
Next, prepare the minor ingredients

0:03:30.340,0:03:31.660
# 准备莴笋半条
cut half of stem lettuce 

0:03:31.660,0:03:34.660
# 从中间切开之后再切成跟猪肚大小的条备用
in the middle then chop it into slices 

0:03:40.100,0:03:42.100
# 准备大蒜50克切成小粒备用
Dice 50 gram garlic for later use 

0:03:42.240,0:03:45.480
# 同学们大蒜主要是增香所用可以适当的多加一些
because the garlic is for adding flavor, you could add a little bit more 

0:03:46.360,0:03:48.420
# 准备生姜1小块切成姜粒备用
Dice a chunk of ginger for later use

0:03:52.080,0:03:54.080
# 准备大葱1根切成小粒备用
Dice a spring onion for later use 

0:03:59.820,0:04:02.320
# 最后准备大红椒半个切成小条备用
cut half of red pepper into small strips for later use
0:04:04.620,0:04:06.040
# 下一步开始制作
Now Let’s start cooking 

0:04:09.600,0:04:11.180
# 首次我们把锅烧热
Frist, heat up the wok

0:04:11.360,0:04:13.420
# 锅烧热之后加入适量的油滑锅
after heating the wok, add some oil to grease the wok

0:04:16.380,0:04:19.000
# 然后将热油倒出加入少许的底油
Pour out the hot oil then add some base oil

0:04:24.820,0:04:27.300
# 油温6成热之后加入切好的料头爆香（大蒜，生姜，葱粒）
after 60% of heating oil, adding the chopped garlic, ginger and spring onion let the aroma release.

0:04:32.820,0:04:36.440
# 料头爆香之后加入切好的肚条转中火爆炒1分钟
then add the prepared pork tripe strips in, turn on the medium heat stir-fry for 1 minute

0:04:46.200,0:04:49.040
# 爆炒1分钟之后加入1碗煮猪肚的原汤
then add a bowl of pork tripe stock 

0:04:53.880,0:04:55.620
# 然后转中小火烧3分钟
then turn it into middle low heat cook for 3 minutes 

0:04:57.500,0:05:00.280
# 3分钟之后加入切好的笋条和大红椒
after that, add the stem lettuce and the red pepper

0:05:09.240,0:05:10.420
# 下一步开始调味
Next step is seasoning 

0:05:11.120,0:05:12.760
# 锅中加入食用盐1勺（约2克）
add one teaspoon salt (about 2 grams)

0:05:13.540,0:05:15.060
# 加入少许白糖提鲜
add some sugar for umani taste 

0:05:15.700,0:05:16.940
# 加入少许胡椒粉
add some white pepper powder

0:05:19.300,0:05:21.560
# 调好味之后将辅料烧至断生即可
after seasoning, stir fry the minor ingredients until them are just cooked 

0:05:23.520,0:05:26.440
# 辅料断生之后再加入适量的水淀粉把汤汁勾浓
then add some wet starch for making the soup rich and thick 

0:05:32.580,0:05:35.480
# 最后加入适量的明油翻炒均匀即可出锅装盘
0:05:45.700,0:05:48.840
# 一道非常美味营养的大蒜烧肚条就制作完成
That is how to cook a delicious and nutritious dish- garlic and tripe strips stir-fry.

0:05:51.120,0:05:52.640
# 下面开始技术总结
Here are some key points for cooking

0:05:52.680,0:05:58.300
# 第一，猪肚必须加盐，白酒，淀粉抓洗，对酒精过敏的同学可以用白醋代替
1.	Must add slat, Baijiu and starch to clean the stomach, if you’re allergic to alcohol, replace Baijiu with rice vinegar.

0:05:58.340,0:06:03.060
# 第二，猪肚用高压锅更加节省时间，也可以直接煮40分钟
2.	It is more time-saving for using pressure cooker to stew the pork tripe, if you don't use pressure cooker, you could just boil pork tripe in regular pot for 40 minutes.

0:06:03.060,0:06:06.720
# 第三，此菜咸鲜微辣特别适合老人孩子食用
3.	This dish is not too spicy and has salty-umami style flavor, so it is suitable for elderly and children.

0:06:06.720,0:06:08.680
大蒜烧肚条的技术总结完毕
