### ISSUE TITLE
【美食作家王刚】山药家挖山药吃柴火鸡 - https://youtu.be/_HeUgy3Kbug

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#516]
【美食作家王刚】山药家挖山药吃柴火鸡 - https://youtu.be/_HeUgy3Kbug
视频时长 12:29，预计发布时间为北京时间12月26日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.220,0:00:01.460
哈喽大家好

0:00:01.460,0:00:04.040
今天我来山里面找我一个兄弟

0:00:04.120,0:00:05.440
大家可以猜到他是谁吗

0:00:06.100,0:00:08.820
我平时都以为我是非常抗冻的

0:00:08.820,0:00:11.560
但是到了这里还是要穿很多衣服加个围巾

0:00:11.560,0:00:12.960
这里非常的冷

0:00:12.960,0:00:16.580
大家可以先猜一下现在这个地方在哪里

0:00:26.720,0:00:30.520
经过一个多小时我们都上来现在找到我兄弟了

0:00:30.780,0:00:32.000
我兄弟山药

0:00:32.060,0:00:32.800
哈喽

0:00:32.940,0:00:34.400
哈喽 大家好我是山药

0:00:34.400,0:00:35.860
大家看一下这个

0:00:36.520,0:00:37.640
吐气

0:00:37.640,0:00:39.260
你别真感冒了

0:00:39.300,0:00:40.300
不会

0:00:40.600,0:00:42.240
给你送点见面礼

0:00:42.240,0:00:43.060
谢谢

0:00:43.060,0:00:43.800
这个是

0:00:43.800,0:00:45.120
带毛猕猴桃

0:00:45.120,0:00:46.220
猕猴桃

0:00:46.240,0:00:50.940
就是上次华农兄弟他们来弄这个

0:00:51.120,0:00:52.900
没被他们赶尽杀绝

0:00:52.900,0:00:54.240
就是蹬树子那个是不哦

0:00:54.240,0:00:55.140
还有吗

0:00:55.340,0:00:56.700
上面现在没有了

0:00:56.700,0:00:57.600
只有这么多了

0:00:57.600,0:00:59.320
要不然你削来试一下

0:01:02.060,0:01:03.940
可以味道真的很巴适

0:01:03.940,0:01:06.120
走刚哥 今天带你去挖山药

0:01:07.100,0:01:08.260
野山药是不哦

0:01:08.745,0:01:09.840
半野

0:01:09.840,0:01:11.400
半野半家

0:01:11.400,0:01:17.240
半野半家是我一个伯伯它弄了一点种子栽到那里的

0:01:23.680,0:01:24.440
伯伯

0:01:25.260,0:01:27.360
我把你那个山药给你处理了哦

0:01:27.360,0:01:28.400
处理了

0:01:28.840,0:01:30.040
我给你找锄头啊

0:01:30.040,0:01:31.700
嗯 要得

0:01:32.200,0:01:34.700
这个磨盘直接转推豆花

0:01:34.820,0:01:38.420
看到没有我们四川人家就是专业的做这个

0:01:38.640,0:01:40.720
这个磨盘起码有1米宽

0:01:40.720,0:01:41.920
直径有1米

0:01:42.500,0:01:43.500
就是这窝

0:01:43.840,0:01:47.420
我要把架架弄开

0:01:49.900,0:01:51.760
那这样就直接把藤割了吗

0:01:51.760,0:01:56.920
不割不割先不慌我先把架子收拾了

0:02:00.720,0:02:02.260
慢点那里绞起了

0:02:06.695,0:02:10.145
挖山药要从颠颠开始慢慢刨

0:02:18.655,0:02:20.215
对它温柔一点

0:02:22.065,0:02:25.005
你不要太粗暴了 太粗暴了容易弄断

0:02:28.220,0:02:32.340
这个山药跟那个莲藕一样难挖

0:02:37.320,0:02:41.620
我感觉掏这个山药比掏黄金还要难

0:02:48.900,0:02:51.340
哦哟 终于成功了

0:02:51.920,0:02:53.180
这是山药吗

0:02:53.180,0:02:54.420
这就是山药

0:02:54.420,0:02:55.720
怎么那么丑

0:02:58.940,0:03:00.480
好 成功了可以了可以了

0:03:00.480,0:03:01.240
好小哦

0:03:01.360,0:03:03.420
可以了 今天我们就挖到这条山药

0:03:03.640,0:03:06.000
可以了大功告成

0:03:06.560,0:03:09.060
我们挖这个山药就跟人参一样

0:03:09.960,0:03:11.740
我感觉比淘黄金还难

0:03:12.720,0:03:14.860
它长在那个石头缝里面很难搞

0:03:20.260,0:03:22.420
姜还是老的辣

0:03:32.660,0:03:34.140
还有这种操作

0:03:35.960,0:03:37.280
你看这个山药蛋

0:03:39.220,0:03:42.320
看起来像鹌鹑蛋一样

0:03:44.200,0:03:47.180
这个皮稍微掐开一点就看到里面的果实了

0:03:47.415,0:03:49.905
这个埋在土里面它也可以生长

0:04:03.095,0:04:05.755
我们挖了半天你看挖了这么深

0:04:06.615,0:04:09.675
不是不好挖是它下面这个石头挡住了

0:04:10.600,0:04:13.340
有块这么大的石头

0:04:15.060,0:04:18.900
所以今天这个挖山药就以失败告终

0:04:18.900,0:04:21.360
但也不是失败挖了好几条这个

0:04:21.360,0:04:25.480
我们挖了有4根 挖了4根山药

0:04:25.480,0:04:30.660
这个应该我跟刚哥先回家熬个鸡汤

0:04:30.860,0:04:31.940
好啦走吧

0:04:32.480,0:04:34.220
要把它埋起嘛不哦

0:04:34.920,0:04:36.040
把它填回去吗

0:04:36.040,0:04:37.380
那个锄头把它填了

0:04:43.360,0:04:44.700
好差不多

0:04:45.365,0:04:47.435
走 回家熬山药汤

0:04:47.905,0:04:51.015
我兄弟山药带我去挖山药结果没挖成

0:04:51.020,0:04:53.965
就挖了几节这么长的断山药

0:04:53.965,0:04:57.800
然后他杀了它们家一只大公鸡

0:04:57.800,0:04:58.960
6斤多

0:04:59.220,0:05:00.940
它请我吃柴火鸡

0:05:00.960,0:05:03.460
等一下他来操作我来炒

0:05:07.540,0:05:08.860
看一下水开了没有

0:05:12.340,0:05:13.520
还差一点点

0:05:13.655,0:05:16.665
发了一些笋干跟那个木耳

0:05:17.485,0:05:18.485
再发一会儿

0:05:19.820,0:05:21.520
来我给你按到给你按到腿

0:05:25.940,0:05:28.080
这个油先放里面

0:05:31.920,0:05:34.180
宰大点嘛 整旺实点

0:05:36.400,0:05:38.980
我去把菜洗了你先砍着

0:05:38.980,0:05:39.480
要得

0:05:46.540,0:05:47.860
好啦 砍好啦

0:05:49.540,0:05:51.240
一筲箕满满的

0:06:03.140,0:06:04.780
把这个辣椒一哈切了嘛

0:06:04.780,0:06:05.720
一哈

0:06:06.140,0:06:07.100
干辣椒都嘛

0:06:07.100,0:06:08.620
这个辣椒不辣

0:06:10.120,0:06:11.100
没有小米辣辣

0:06:14.000,0:06:16.140
子弹头（辣椒）就是颜色好看点

0:06:17.445,0:06:18.445
我放油了哦

0:06:23.945,0:06:26.275
你这个油也准备得太好了吧刚好够

0:06:27.785,0:06:29.985
刚好这都是跟二牛借的

0:06:34.480,0:06:37.180
油差不多了我来先下点辣椒

0:06:37.300,0:06:38.420
辣椒一起放了哦

0:06:39.200,0:06:40.100
着得住不

0:06:40.100,0:06:41.100
着得住

0:06:58.120,0:07:00.180
我们干辣椒就是爆到这个程度

0:07:03.480,0:07:04.980
干辣椒爆成褐色

0:07:05.540,0:07:07.200
这样又香又没有糊味

0:07:08.100,0:07:10.160
我随时都爆成黑色

0:07:10.180,0:07:12.520
干辣椒爆成这个颜色是香的

0:07:17.540,0:07:19.780
把它水炸干是不哦

0:07:23.300,0:07:25.040
你坐着炒吧

0:07:26.060,0:07:27.880
我这是第一次炒菜是坐着炒

0:07:34.000,0:07:35.240
先把香料放下去

0:07:44.080,0:07:47.400
感觉鸡的颜色有点巴适哦

0:07:48.800,0:07:50.420
金黄金黄的

0:07:52.080,0:07:54.360
现在这个水份已经爆得有点干了

0:07:54.380,0:07:57.180
你看剩下的都是刚才放的油

0:07:57.580,0:08:00.540
那个油把那个干辣椒香味炝出来了

0:08:00.540,0:08:03.120
然后鸡皮里面的油也爆出来了

0:08:07.380,0:08:08.740
这个鸡肉是很香的

0:08:11.220,0:08:12.280
先下调料

0:08:13.000,0:08:14.240
先下这个辅料

0:08:15.080,0:08:17.900
下（锅）咯 一哈下了哦

0:08:19.080,0:08:21.240
没得事 我们都是重口味的

0:08:21.940,0:08:25.340
哎呀 这一股风吹得好巴适

0:08:26.020,0:08:30.400
我也感到有点点的巴适 鸡皮疙瘩都起来了吹了来

0:08:38.440,0:08:40.220
好 放豆瓣酱

0:08:41.980,0:08:42.680
够了不

0:08:42.680,0:08:43.920
你整得刚刚好埃

0:08:55.000,0:08:56.520
整点老抽

0:09:02.460,0:09:03.780
再加一瓶啤酒

0:09:08.240,0:09:10.340
好香哦 酒香味都闻得到

0:09:13.100,0:09:14.780
啤酒不够水来凑

0:09:22.340,0:09:24.240
好 没过鸡块

0:09:28.020,0:09:28.680
笋子

0:09:29.500,0:09:31.700
这个笋子要烧很久 所以先放

0:09:31.940,0:09:32.840
木耳不放啊

0:09:32.840,0:09:35.480
等它开了再放魔芋跟土豆

0:09:36.040,0:09:38.060
现在放下去要掉（淀）粉

0:09:38.300,0:09:39.120
嘿嘿

0:09:39.120,0:09:40.120
掉粉

0:09:42.880,0:09:45.120
把这一筲箕一哈放下去哦

0:09:48.000,0:09:51.040
没找到干豇豆有点干豇豆就巴适了

0:09:51.580,0:09:52.580
上锅盖

0:09:54.640,0:09:55.720
往前面一点

0:09:56.500,0:09:57.580
感觉要遭烧到了

0:09:58.240,0:10:02.700
这个鸡肉太多了 所以找了超大的锅盖来盖

0:10:07.360,0:10:08.480
哇塞

0:10:09.240,0:10:10.520
这一锅

0:10:17.960,0:10:18.960
土豆耙了

0:10:20.040,0:10:20.940
可以吃了

0:10:20.940,0:10:21.960
海椒放下去

0:10:22.940,0:10:24.580
那火就不退了等下还要（加热）

0:10:24.860,0:10:26.180
要得 边煮边吃

0:10:26.180,0:10:27.580
翻两哈就可以了

0:10:28.140,0:10:29.440
我来拿筷子 开整

0:10:31.540,0:10:32.760
那是不是（屁股）翘翘哦

0:10:34.000,0:10:34.800
不是得不是得

0:10:34.800,0:10:35.540
你看

0:10:35.560,0:10:38.140
不是得 这是瘦肉 瘦的

0:10:38.620,0:10:40.280
嗯 巴适

0:10:40.880,0:10:41.380
香

0:10:41.920,0:10:42.900
鸡肉好吃

0:10:43.580,0:10:45.100
喂了差不多一年多噶

0:10:45.200,0:10:45.900
嗯

0:10:53.480,0:10:58.360
这个魔芋确实是很有弹性

0:10:59.760,0:11:05.060
真的你买的这个魔芋是我吃过目前为止口感最好的魔芋

0:11:05.060,0:11:06.300
真的啊 嗯

0:11:09.060,0:11:10.220
我很喜欢吃这个

0:11:10.840,0:11:11.620
吃这个啊

0:11:11.620,0:11:12.380
鸡冠子

0:11:14.840,0:11:16.340
这个是最好吃的我觉得

0:11:16.520,0:11:20.440
整只鸡上面就是它的鸡冠还有鸡翅

0:11:20.440,0:11:22.440
鸡腿都没有这两个东西好吃

0:11:26.765,0:11:28.715
这个专门有人专门卖这个冠子的噶

0:11:29.275,0:11:30.275
没得吧

0:11:31.140,0:11:35.220
我看是上个月在哪里吃九大碗的时候

0:11:35.760,0:11:40.820
我看到人家专门就是弄那个泡鸡脚样的泡鸡冠

0:11:40.820,0:11:42.620
那冰冻的 不好吃

0:11:42.620,0:11:43.480
不好吃哦

0:11:45.060,0:11:46.800
还是要吃这种原生态的

0:11:50.560,0:11:53.180
谢谢我们山药哥的热情款待

0:11:53.260,0:11:56.080
一只鸡喂了一年多不容易

0:11:56.080,0:11:57.500
一下子就给宰了 嘿嘿

0:11:58.000,0:12:00.040
没得事刚哥你来了下个月我们

0:12:00.620,0:12:02.080
下个月又要宰一只

0:12:02.080,0:12:03.780
下个月再宰一只 还有鸽子

0:12:03.780,0:12:07.460
到时候我们又到后面来整个啥子柴火鸽

0:12:07.800,0:12:08.800
柴火鸽啊 嗯

0:12:10.400,0:12:12.580
因为我们这个都是在四川很近

0:12:12.925,0:12:14.765
所以串门特别方便

0:12:15.780,0:12:17.760
等我们这边下雪了又过来

0:12:17.760,0:12:18.260
好

0:12:18.260,0:12:19.840
这山上雪景特别爽

0:12:19.900,0:12:21.800
本期视频就到这里 拜拜啦

0:12:21.800,0:12:23.640
下次带你们来看雪景

0:12:23.860,0:12:25.200
拜拜

**Comment by Losskywalker** [comment]
认领

**Comment by Losskywalker** [comment]
bot, please upload

【美食作家王刚】山药家挖山药吃柴火鸡 - https://youtu.be/_HeUgy3Kbug
Title: Farmhouse chicken with freshly harvested yam. Feat. Mr. Yam

视频时长 12:29，预计发布时间为北京时间12月26日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！
0:00:00.220,0:00:01.460
哈喽大家好
Hi everyone
0:00:01.460,0:00:04.040
今天我来山里面找我一个兄弟
I’m here today to visit my friend in the mountains
0:00:04.120,0:00:05.440
大家可以猜到他是谁吗
Can you figure out who that is?
0:00:06.100,0:00:08.820
我平时都以为我是非常抗冻的
I thought I was quite tolerant against cold weather
0:00:08.820,0:00:11.560
但是到了这里还是要穿很多衣服加个围巾
But it’s so cold here that I had to wear a lot with a scarf. 
0:00:11.560,0:00:12.960
这里非常的冷
It’s really cold here.
0:00:12.960,0:00:16.580
大家可以先猜一下现在这个地方在哪里
Maybe you can first guess where I am
0:00:26.720,0:00:30.520
经过一个多小时我们都上来现在找到我兄弟了
Finally, I’m here with my friend after one hour of travelling.
0:00:30.780,0:00:32.000
我兄弟山药
Mr. Yam!
0:00:32.060,0:00:32.800
哈喽
Hi everyone
0:00:32.940,0:00:34.400
哈喽 大家好我是山药
Hi I’m Mr. Yam
0:00:34.400,0:00:35.860
大家看一下这个
Check this out
0:00:36.520,0:00:37.640
吐气
I can see my breath
0:00:37.640,0:00:39.260
你别真感冒了
Did you really catch a cold?
0:00:39.300,0:00:40.300
不会
No I’m ok
0:00:40.600,0:00:42.240
给你送点见面礼
I’ve brought you something
0:00:42.240,0:00:43.060
谢谢
Thanks!
0:00:43.060,0:00:43.800
这个是
What’s that?
0:00:43.800,0:00:45.120
带毛猕猴桃
“Hairy” Kiwi fruits
0:00:45.120,0:00:46.220
猕猴桃
Kiwi fruits
0:00:46.240,0:00:50.940
就是上次华农兄弟他们来弄这个
The same ones that Huanong brothers collected last time. 
0:00:51.120,0:00:52.900
没被他们赶尽杀绝
There are still some survivors.
0:00:52.900,0:00:54.240
就是蹬树子那个是不哦
Ah right when they were kicking the trees
0:00:54.240,0:00:55.140
还有吗
Any more?
0:00:55.340,0:00:56.700
上面现在没有了
Not on the trees
0:00:56.700,0:00:57.600
只有这么多了
That’s all I have
0:00:57.600,0:00:59.320
要不然你削来试一下
Wanna try? 
0:01:02.060,0:01:03.940
可以味道真的很巴适
It’s really nice.
0:01:03.940,0:01:06.120
走刚哥 今天带你去挖山药
Let’s go, I will show you how to harvest yam.
0:01:07.100,0:01:08.260
野山药是不哦
Are they wild yam?
0:01:08.745,0:01:09.840
半野
Kind of.
0:01:09.840,0:01:11.400
半野半家
Half wild.
0:01:11.400,0:01:17.240
半野半家是我一个伯伯它弄了一点种子栽到那里的
It’s not completely wild because it was planted by my uncle
0:01:23.680,0:01:24.440
伯伯
Uncle!
0:01:25.260,0:01:27.360
我把你那个山药给你处理了哦
We are going to get the yam
0:01:27.360,0:01:28.400
处理了
Sure
0:01:28.840,0:01:30.040
我给你找锄头啊
I’ll get you a hoe
0:01:30.040,0:01:31.700
嗯 要得
Yes please.
0:01:32.200,0:01:34.700
这个磨盘直接转推豆花
This mill is used to grind soybeans to make tofu.
0:01:34.820,0:01:38.420
看到没有我们四川人家就是专业的做这个
See? We take this very seriously here at home in Sicuan.
0:01:38.640,0:01:40.720
这个磨盘起码有1米宽
This is like 1 meter wide
0:01:40.720,0:01:41.920
直径有1米
1 meter for diameter
0:01:42.500,0:01:43.500
就是这窝
Here we are.
0:01:43.840,0:01:47.420
我要把架架弄开
I’ll remove the racks.
0:01:49.900,0:01:51.760
那这样就直接把藤割了吗
Should I cut of the bine?
0:01:51.760,0:01:56.920
不割不割先不慌我先把架子收拾了
No not yet, let me first handle the racks.
0:02:00.720,0:02:02.260
慢点那里绞起了
Careful, it’s twisted there.
0:02:06.695,0:02:10.145
挖山药要从颠颠开始慢慢刨
We need to start digging slowly form the side
0:02:18.655,0:02:20.215
对它温柔一点
Take it gently
0:02:22.065,0:02:25.005
你不要太粗暴了 太粗暴了容易弄断
Don’t force it, otherwise it might break.
0:02:28.220,0:02:32.340
这个山药跟那个莲藕一样难挖
Digging yam is as difficult as digging lotus roots
0:02:37.320,0:02:41.620
我感觉掏这个山药比掏黄金还要难
I think it’s as difficult as digging gold.
0:02:48.900,0:02:51.340
哦哟 终于成功了
Yes! Finally
0:02:51.920,0:02:53.180
这是山药吗
This is yam?
0:02:53.180,0:02:54.420
这就是山药
Yes indeed
0:02:54.420,0:02:55.720
怎么那么丑
That’s ugly.
0:02:58.940,0:03:00.480
好 成功了可以了可以了
Great we did it
0:03:00.480,0:03:01.240
好小哦
That’s so small though.
0:03:01.360,0:03:03.420
可以了 今天我们就挖到这条山药
OK so that’s all we got today
0:03:03.640,0:03:06.000
可以了大功告成
Mission accomplished.
0:03:06.560,0:03:09.060
我们挖这个山药就跟人参一样
It’s like digging Ginseng
0:03:09.960,0:03:11.740
我感觉比淘黄金还难
I feel more like digging gold
0:03:12.720,0:03:14.860
它长在那个石头缝里面很难搞
It’s growing between the rocks. Very tricky.
0:03:20.260,0:03:22.420
姜还是老的辣
It really takes experiences.
0:03:32.660,0:03:34.140
还有这种操作
I didn’t know you can do that.
0:03:35.960,0:03:37.280
你看这个山药蛋
Look at it
0:03:39.220,0:03:42.320
看起来像鹌鹑蛋一样
It’s like the quail egg
0:03:44.200,0:03:47.180
这个皮稍微掐开一点就看到里面的果实了
Just peel it off a bit and you can see the flesh inside
0:03:47.415,0:03:49.905
这个埋在土里面它也可以生长
It will grow if you burry it in soil too.
0:04:03.095,0:04:05.755
我们挖了半天你看挖了这么深
We spent quite some time to dig this deep.
0:04:06.615,0:04:09.675
不是不好挖是它下面这个石头挡住了
It’s because there is a big rock blocking us.
0:04:10.600,0:04:13.340
有块这么大的石头
A roc that THIS big.
0:04:15.060,0:04:18.900
所以今天这个挖山药就以失败告终
So this one is a failed mission.
0:04:18.900,0:04:21.360
但也不是失败挖了好几条这个
Not completely though, we’ve got these
0:04:21.360,0:04:25.480
我们挖了有4根 挖了4根山药
We’ve got 4 pieces.
0:04:25.480,0:04:30.660
这个应该我跟刚哥先回家熬个鸡汤
We should go home and cook some chicken soup.
0:04:30.860,0:04:31.940
好啦走吧
Alright let’s go
0:04:32.480,0:04:34.220
要把它埋起嘛不哦
Do we need to put it back?
0:04:34.920,0:04:36.040
把它填回去吗
The soil?
0:04:36.040,0:04:37.380
那个锄头把它填了
Sure we can use the hoe for that
0:04:43.360,0:04:44.700
好差不多
OK that’s fine
0:04:45.365,0:04:47.435
走 回家熬山药汤
Let’s go and make some yam soup
0:04:47.905,0:04:51.015
我兄弟山药带我去挖山药结果没挖成
So, Mr. Yam did not find too much yam today
0:04:51.020,0:04:53.965
就挖了几节这么长的断山药
Only a few broken pieces like these
0:04:53.965,0:04:57.800
然后他杀了它们家一只大公鸡
And he killed a rooster today for me
0:04:57.800,0:04:58.960
6斤多
Over 3 kg
0:04:59.220,0:05:00.940
它请我吃柴火鸡
We will prepare a farmhouse chicken
0:05:00.960,0:05:03.460
等一下他来操作我来炒
So, he will prepare, and I will cook
0:05:07.540,0:05:08.860
看一下水开了没有
Is the water boiling already?
0:05:12.340,0:05:13.520
还差一点点
Almost
0:05:13.655,0:05:16.665
发了一些笋干跟那个木耳
I have soaked some dried bamboo shoot and mushroom
0:05:17.485,0:05:18.485
再发一会儿
It’ll still take a while
0:05:19.820,0:05:21.520
来我给你按到给你按到腿
I’ll hold the legs for you
0:05:25.940,0:05:28.080
这个油先放里面
Let’s put the fat aside for now
0:05:31.920,0:05:34.180
宰大点嘛 整旺实点
Just make the pieces larger (不太确定旺实是啥意思)
0:05:36.400,0:05:38.980
我去把菜洗了你先砍着
You do the chopping, I’ll wash the vegetables
0:05:38.980,0:05:39.480
要得
Sure
0:05:46.540,0:05:47.860
好啦 砍好啦
OK it’s done
0:05:49.540,0:05:51.240
一筲箕满满的
A whole lot of meat
0:06:03.140,0:06:04.780
把这个辣椒一哈切了嘛
Let use all of the chili peppers
0:06:04.780,0:06:05.720
一哈
All?
0:06:06.140,0:06:07.100
干辣椒都嘛
They are dried ones
0:06:07.100,0:06:08.620
这个辣椒不辣
They are not that spicy
0:06:10.120,0:06:11.100
没有小米辣辣
Not as spicy as the little ones
0:06:14.000,0:06:16.140
子弹头（辣椒）就是颜色好看点
This one has a better color
0:06:17.445,0:06:18.445
我放油了哦
Let me pour the oil in
0:06:23.945,0:06:26.275
你这个油也准备得太好了吧刚好够
Perfect, you’ve prepared exactly the amount I need
0:06:27.785,0:06:29.985
刚好这都是跟二牛借的
I borrowed it from Erniu
0:06:34.480,0:06:37.180
油差不多了我来先下点辣椒
OK the oil is hot enough, let’s put the chili peppers in
0:06:37.300,0:06:38.420
辣椒一起放了哦
All together at once
0:06:39.200,0:06:40.100
着得住不
Can you handle it?
0:06:40.100,0:06:41.100
着得住
Of course
0:06:58.120,0:07:00.180
我们干辣椒就是爆到这个程度
We need to fry it until it’s like this
0:07:03.480,0:07:04.980
干辣椒爆成褐色
Perfectly brown
0:07:05.540,0:07:07.200
这样又香又没有糊味
It’s fragrant but not smoky
0:07:08.100,0:07:10.160
我随时都爆成黑色
I always overcook it, then it turns black
0:07:10.180,0:07:12.520
干辣椒爆成这个颜色是香的
It smells the best when fried until this color
0:07:17.540,0:07:19.780
把它水炸干是不哦
So we just need to get rid of the excess moisture?
0:07:23.300,0:07:25.040
你坐着炒吧
You can sit and fry
0:07:26.060,0:07:27.880
我这是第一次炒菜是坐着炒
I’ve never sit while cooking
0:07:34.000,0:07:35.240
先把香料放下去
In goes the species
0:07:44.080,0:07:47.400
感觉鸡的颜色有点巴适哦
The color of the chicken is amazing
0:07:48.800,0:07:50.420
金黄金黄的
Beautifully golden
0:07:52.080,0:07:54.360
现在这个水份已经爆得有点干了
OK the moisture is none
0:07:54.380,0:07:57.180
你看剩下的都是刚才放的油
It’s only oil that’s left
0:07:57.580,0:08:00.540
那个油把那个干辣椒香味炝出来了
The oil helps bring out the fragrance of the dried chili peppers.
0:08:00.540,0:08:03.120
然后鸡皮里面的油也爆出来了
Also, the fat in the skin has been rendered
0:08:07.380,0:08:08.740
这个鸡肉是很香的
It smells amazing already.
0:08:11.220,0:08:12.280
先下调料
The rest of ingredients (刚哥说下调料，但是应该说的是辅料吧)
0:08:13.000,0:08:14.240
先下这个辅料
These go in first
0:08:15.080,0:08:17.900
下（锅）咯 一哈下了哦
All together?
0:08:19.080,0:08:21.240
没得事 我们都是重口味的
Sure, we can handle the spices.
0:08:21.940,0:08:25.340
哎呀 这一股风吹得好巴适
Wow, “cool wind in my hair”, feels good.
0:08:26.020,0:08:30.400
我也感到有点点的巴适 鸡皮疙瘩都起来了吹了来
Me too, got a little bit goose bump.
0:08:38.440,0:08:40.220
好 放豆瓣酱
Now let’s put the Doubanjiang (chili bean paste) in
0:08:41.980,0:08:42.680
够了不
Enough?
0:08:42.680,0:08:43.920
你整得刚刚好埃
Perfect!
0:08:55.000,0:08:56.520
整点老抽
Now the dark soy sauce
0:09:02.460,0:09:03.780
再加一瓶啤酒
A bottle of beer
0:09:08.240,0:09:10.340
好香哦 酒香味都闻得到
Wow the beer aroma is everwhere!
0:09:13.100,0:09:14.780
啤酒不够水来凑
Use water if you don’t have enough beer
0:09:22.340,0:09:24.240
好 没过鸡块
Good, just over the chicken
0:09:28.020,0:09:28.680
笋子
Bamboo shoot
0:09:29.500,0:09:31.700
这个笋子要烧很久 所以先放
It needs to be cooked for a while, so we put it in first
0:09:31.940,0:09:32.840
木耳不放啊
Mushroom?
0:09:32.840,0:09:35.480
等它开了再放魔芋跟土豆
Not yet, we will put the konjac and potato in after it boils 
0:09:36.040,0:09:38.060
现在放下去要掉（淀）粉
If we put them now, we will lose the starch
0:09:38.300,0:09:39.120
嘿嘿
Haha
0:09:39.120,0:09:40.120
掉粉
Starch, and followers too.
0:09:42.880,0:09:45.120
把这一筲箕一哈放下去哦
Everything goes at once
0:09:48.000,0:09:51.040
没找到干豇豆有点干豇豆就巴适了
I couldn’t find dried cowpea, otherwise it would be great.
0:09:51.580,0:09:52.580
上锅盖
Lid on
0:09:54.640,0:09:55.720
往前面一点
Move it away
0:09:56.500,0:09:57.580
感觉要遭烧到了
It almost get burnt
0:09:58.240,0:10:02.700
这个鸡肉太多了 所以找了超大的锅盖来盖
We need this massive lid to cover the chicken.
0:10:07.360,0:10:08.480
哇塞
WOW
0:10:09.240,0:10:10.520
这一锅
Look at that
0:10:17.960,0:10:18.960
土豆耙了
Potato is cooked to soft
0:10:20.040,0:10:20.940
可以吃了
It’s ready.
0:10:20.940,0:10:21.960
海椒放下去
Now the green chili peppers.
0:10:22.940,0:10:24.580
那火就不退了等下还要（加热）
Let’s keep the fire on. We need it (to heat up) later anyway.
0:10:24.860,0:10:26.180
要得 边煮边吃
OK, we eat while cooking.
0:10:26.180,0:10:27.580
翻两哈就可以了
Give it a stir and it’s good to go.
0:10:28.140,0:10:29.440
我来拿筷子 开整
I’ll get the chopsticks. Let’s dig in.
0:10:31.540,0:10:32.760
那是不是（屁股）翘翘哦
Is that the tail?
0:10:34.000,0:10:34.800
不是得不是得
Nah not really
0:10:34.800,0:10:35.540
你看
Look
0:10:35.560,0:10:38.140
不是得 这是瘦肉 瘦的
It’s not, it’s lean meat here.
0:10:38.620,0:10:40.280
嗯 巴适
Emmm, nice
0:10:40.880,0:10:41.380
香
Smells amazing
0:10:41.920,0:10:42.900
鸡肉好吃
The meat is great.
0:10:43.580,0:10:45.100
喂了差不多一年多噶
We raised it for almost a whole year
0:10:45.200,0:10:45.900
嗯
OK
0:10:53.480,0:10:58.360
这个魔芋确实是很有弹性
The konjac is spongy
0:10:59.760,0:11:05.060
真的你买的这个魔芋是我吃过目前为止口感最好的魔芋
Actually this is the best konjac I’ve ever tasted.
0:11:05.060,0:11:06.300
真的啊 嗯
Really? (yes)
0:11:09.060,0:11:10.220
我很喜欢吃这个
I like this a lot
0:11:10.840,0:11:11.620
吃这个啊
This?
0:11:11.620,0:11:12.380
鸡冠子
The comb.
0:11:14.840,0:11:16.340
这个是最好吃的我觉得
This is the best part of the chicken
0:11:16.520,0:11:20.440
整只鸡上面就是它的鸡冠还有鸡翅
The comb, and the wings.
0:11:20.440,0:11:22.440
鸡腿都没有这两个东西好吃
Much better than the legs.
0:11:26.765,0:11:28.715
这个专门有人专门卖这个冠子的噶
Is there anyone selling the comb?
0:11:29.275,0:11:30.275
没得吧
I don’t think so.
0:11:31.140,0:11:35.220
我看是上个月在哪里吃九大碗的时候
I remember having a village dinner last month
0:11:35.760,0:11:40.820
我看到人家专门就是弄那个泡鸡脚样的泡鸡冠
They had a dish of this in pickles.
0:11:40.820,0:11:42.620
那冰冻的 不好吃
But that’s frozen, it was not that good.
0:11:42.620,0:11:43.480
不好吃哦
That’s not good.
0:11:45.060,0:11:46.800
还是要吃这种原生态的
The fresh ones are much better.
0:11:50.560,0:11:53.180
谢谢我们山药哥的热情款待
Let’s thank Mr. Yam for inviting us here.
0:11:53.260,0:11:56.080
一只鸡喂了一年多不容易
This chicken has been kept for a year.
0:11:56.080,0:11:57.500
一下子就给宰了 嘿嘿
And he specially killed it for us.
0:11:58.000,0:12:00.040
没得事刚哥你来了下个月我们
No worries, if you come next month
0:12:00.620,0:12:02.080
下个月又要宰一只
I will get another for you
0:12:02.080,0:12:03.780
下个月再宰一只 还有鸽子
And another one. We also have pigeons.
0:12:03.780,0:12:07.460
到时候我们又到后面来整个啥子柴火鸽
Then we can cook a farmhouse pigeon
0:12:07.800,0:12:08.800
柴火鸽啊 嗯
Farmhouse pigeon? (Yes)
0:12:10.400,0:12:12.580
因为我们这个都是在四川很近
We are both in Sichuan, we are very close-by.
0:12:12.925,0:12:14.765
所以串门特别方便
Quite easy to visit each other.
0:12:15.780,0:12:17.760
等我们这边下雪了又过来
Come again when it snows.
0:12:17.760,0:12:18.260
好
Sure
0:12:18.260,0:12:19.840
这山上雪景特别爽
The view here after snow is stunning.
0:12:19.900,0:12:21.800
本期视频就到这里 拜拜啦
OK this is it for today’s video, bye-bye
0:12:21.800,0:12:23.640
下次带你们来看雪景
Let’s come again for the snow
0:12:23.860,0:12:25.200
拜拜
Bye bye!
