### ISSUE TITLE
【美食作家王刚】蒸腊鱼 - https://youtu.be/nBxYMduBO4A

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#534]
【美食作家王刚】蒸腊鱼 - https://youtu.be/nBxYMduBO4A
视频时长 7:56，预计发布时间为北京时间1月2日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.360,0:00:01.060
嗨喽大家好

0:00:01.060,0:00:03.120
上次我们不是做了腊鱼吗

0:00:03.120,0:00:07.220
这个腊鱼后面抹了一些辣椒还有花椒

0:00:07.220,0:00:08.740
因为四川都要吃辣嘛

0:00:08.745,0:00:11.035
现在准备拿一条弄来吃一下

0:00:11.040,0:00:12.680
看一下味道怎么样

0:00:12.680,0:00:16.280
冬天了是吃香腊 这个腊味的时候了

0:00:16.280,0:00:17.520
噶 四伯爷

0:00:17.980,0:00:18.900
嗯 是按

0:00:18.980,0:00:20.720
吃来试哈看嘛 看安不安逸嘛

0:00:20.720,0:00:21.620
煮一条就是哈

0:00:21.640,0:00:23.720
啊整一条嘛 少整点来试一哈看

0:00:23.720,0:00:24.240
要得

0:00:24.960,0:00:27.520
这个鱼弄开 把这个割开

0:00:27.760,0:00:29.780
先把它放到锅里面煮一下

0:00:29.920,0:00:31.760
但是我现在先配一下料

0:00:32.060,0:00:33.100
这个先放这边哈

0:00:35.560,0:00:37.020
这个料非常简单

0:00:37.020,0:00:38.960
就是姜跟蒜

0:00:39.280,0:00:41.440
你不拿花（椒） 不用花椒吗

0:00:41.440,0:00:42.140
昂

0:00:42.140,0:00:43.300
不拿花椒吗

0:00:43.300,0:00:43.880
要

0:00:44.400,0:00:45.220
对咯

0:00:49.460,0:00:51.520
这个姜蒜稍微多一点

0:00:52.480,0:00:54.340
一起剁碎了就行了

0:00:56.720,0:00:59.860
这个做法是贵州 就是我老婆她们那边

0:00:59.860,0:01:01.160
少数民族的一种做法

0:01:02.700,0:01:05.480
他们喜欢这样子做的话是因为这个姜蒜

0:01:05.480,0:01:07.795
下锅爆香了之后加那个干辣椒

0:01:07.800,0:01:09.480
然后再跟那个鱼一起炒

0:01:09.480,0:01:10.980
炒香了再用来蒸

0:01:11.040,0:01:13.500
把这个姜蒜的香味蒸到鱼里面去

0:01:14.700,0:01:15.620
好了

0:01:16.480,0:01:18.260
所以一般会多一些

0:01:18.260,0:01:19.540
少数民族的做法

0:01:21.800,0:01:23.660
然后再切点这个干辣椒

0:01:27.940,0:01:29.440
干辣椒切开就行了

0:01:30.620,0:01:33.860
其实干辣椒用刀切比用剪刀更快

0:01:37.700,0:01:42.640
我还准备了一些这个辣椒面跟花椒粉

0:01:44.620,0:01:46.160
今天的猪肉好不好卖哦四伯爷

0:01:46.160,0:01:47.260
今天没卖

0:01:47.460,0:01:48.520
今天休息啊

0:01:48.720,0:01:49.680
休息

0:01:50.600,0:01:52.100
我以为你今天赶场去了

0:01:52.100,0:01:55.860
每天赶三道场太累了 休息一天

0:01:55.860,0:01:57.340
干两天休息一天

0:01:58.800,0:02:00.820
这个火现在起来了我要加点水

0:02:00.820,0:02:02.960
把这个鱼放下去先煮个十分钟

0:02:02.960,0:02:06.740
把它的一些盐味啊咸味啊还有一些辣味啊

0:02:06.740,0:02:09.600
还有一些不好的味道先除一下味

0:02:14.800,0:02:16.580
你这个瓜瓢都用了很多年了噶

0:02:17.560,0:02:19.500
田上下户你想哈看

0:02:20.080,0:02:22.500
煮腊肉一般我们冷水下锅更好一些

0:02:23.260,0:02:25.180
冷水下锅更容易煮透 是噶

0:02:26.360,0:02:31.580
因为我们农村这个腊鱼腊肉咸味都会稍微重一些

0:02:31.600,0:02:33.860
所以就先放水里面煮一次

0:02:35.480,0:02:37.780
煮完了之后再用这个姜蒜辣椒

0:02:37.820,0:02:41.760
还有这个花椒面一起再重新调味

0:02:41.760,0:02:43.520
再放点白糖综合一下

0:02:43.520,0:02:45.460
最后再放到锅里面蒸

0:02:45.760,0:02:48.360
四伯爷 你说你小时候非凡

0:02:49.340,0:02:50.360
有好凡呢

0:02:50.360,0:02:51.860
哎呀 啥样都干过

0:02:51.960,0:02:52.620
啥样都干过

0:02:52.620,0:02:54.140
哦 啥样都干过

0:02:54.140,0:02:54.680
比如呢

0:02:54.680,0:02:55.740
烧锅锅酒儿（过家家）啊

0:02:55.740,0:02:57.220
得屠场头割肉啊

0:02:57.460,0:02:59.480
人家的边口（猪肉）搭得那板板高头及

0:02:59.480,0:03:01.560
一爪就把人家的腰子给人家逮（拿）了

0:03:01.560,0:03:02.960
逮起出去烧锅锅酒儿

0:03:04.280,0:03:06.675
伯娘那哈说你留长头发多帅的噶

0:03:06.675,0:03:07.680
嗯 是啊

0:03:07.680,0:03:11.120
那哈照身份证的时候拿钢夹（发夹）锁起来照

0:03:11.700,0:03:12.600
照那个时候

0:03:12.700,0:03:14.300
你是咋子追的四伯娘

0:03:15.580,0:03:17.180
哎呀 那个时候

0:03:17.200,0:03:21.860
我们认到就是那哈儿最初那个田土下放的时候

0:03:21.860,0:03:24.560
买起电影机子看电影

0:03:24.560,0:03:26.000
就看那个天仙配

0:03:26.000,0:03:26.500
啊

0:03:26.580,0:03:29.120
就看了连续我就看了七场

0:03:29.600,0:03:31.720
好 那哈子才想耍朋友了

0:03:32.560,0:03:34.380
否则还没得那个感觉得

0:03:34.660,0:03:37.180
诶 那个天仙配看了来启发了我

0:03:38.640,0:03:40.420
不是的话 我都还是光棍

0:03:40.740,0:03:43.660
司令还是个 光棍司令是个

0:03:47.100,0:03:48.640
这个鱼快要熟了

0:03:48.640,0:03:50.020
辣椒面都浮起来了

0:03:50.600,0:03:55.820
其实这个辣椒面它腌鱼的话就不是说用来一直让它在肉里面

0:03:55.820,0:03:57.440
这个就是取它的味道

0:04:00.520,0:04:04.500
好了 四伯爷先不忙放柴了

0:04:04.800,0:04:05.840
这个鱼要得了

0:04:07.080,0:04:08.260
我拿起去砍

0:04:13.100,0:04:14.780
哇 这个鱼还不是特别干

0:04:15.020,0:04:17.720
要是再干一点的话肯定会更香一些

0:04:18.795,0:04:20.055
我拿起去砍去了

0:04:20.425,0:04:22.340
要得 这哈子就不烧（火）咯

0:04:22.340,0:04:23.380
暂时不烧

0:04:24.060,0:04:27.820
这条鱼还没 还没到时间所以有一点嫩

0:04:29.560,0:04:32.120
不管它 先砍来尝一下味道

0:04:50.640,0:04:51.160
好

0:04:51.160,0:04:52.420
现在放一点点油

0:04:54.000,0:04:55.840
这个可以稍微多那么一点点

0:04:57.660,0:05:01.920
其实做鱼的话还是要这个菜油更香哈

0:05:01.920,0:05:07.080
吃鱼不是菜油不好吃 有些拿那个植物油来煎起就不安逸

0:05:08.920,0:05:12.520
好了 这个油已经在冒大烟了

0:05:12.520,0:05:14.080
说明这个菜籽油已经熟了

0:05:14.800,0:05:15.980
现在放点花椒

0:05:17.020,0:05:19.120
再放这个干辣椒爆一下

0:05:20.480,0:05:21.760
再放这个姜蒜粒

0:05:25.240,0:05:26.520
（火）小滴点儿的 四伯爷

0:05:27.180,0:05:29.660
才两三根柴呢 两根都不够

0:05:32.000,0:05:34.980
炒到这个姜蒜粒香了之后再放这个辣椒面

0:05:35.300,0:05:38.000
辣椒面是出颜色的 也是出香味的

0:05:39.220,0:05:40.740
可以稍微多一点

0:05:40.740,0:05:42.240
少整点 多很了辣得很哦

0:05:42.240,0:05:45.040
不关事 这个是蒸的

0:05:45.040,0:05:46.740
这个蒸的都辣

0:05:47.500,0:05:48.500
好嘛

0:05:50.020,0:05:51.560
稍微小滴点儿的 四伯爷 火

0:05:51.820,0:05:53.400
然后放这个鱼下去炒

0:05:56.820,0:05:58.600
因为这个鱼可能有一点嫩

0:05:59.880,0:06:01.660
所以翻动的时候轻一点

0:06:02.980,0:06:05.000
我们这个调味只放白糖

0:06:05.780,0:06:08.620
因为这个是腊鱼 放白糖可以压住它的咸味

0:06:09.200,0:06:10.560
再放一点花椒面

0:06:13.440,0:06:15.160
花椒面可以稍微多一些

0:06:15.980,0:06:18.120
等它炒匀了就可以起锅了

0:06:22.360,0:06:24.620
好 炒匀了就起锅

0:06:25.300,0:06:26.600
直接就放到这个碗里面

0:06:34.560,0:06:37.440
这个鱼非常的香 又香又入味

0:06:44.460,0:06:46.640
现在我们把这个盖上蒸一会儿

0:06:46.980,0:06:50.960
让它那个菜油充分的把这个香味蒸到鱼里面

0:06:51.460,0:06:52.580
大概十分钟

0:06:52.920,0:06:55.140
最后出来的时候就撒上葱花就可以了

0:06:57.920,0:07:00.300
现在已经蒸了十多分钟了 差不多了

0:07:00.740,0:07:01.740
我看哈看

0:07:03.300,0:07:04.000
哦哟

0:07:04.000,0:07:05.380
还多香 蒸起

0:07:06.680,0:07:07.720
颜色还多安逸噶

0:07:07.720,0:07:08.880
我尝哈味道怎么样

0:07:11.580,0:07:12.660
先整来告（试）哈看

0:07:16.660,0:07:18.200
嗯 这个味道已经融合了

0:07:18.200,0:07:20.480
融合了这个调料的味道

0:07:20.480,0:07:21.800
差不多了 我端咯

0:07:21.800,0:07:23.260
烫哦 慢点儿哦

0:07:23.260,0:07:24.000
不关事

0:07:25.580,0:07:26.720
诶呀 四伯爷 火就不烧了

0:07:26.720,0:07:27.420
要得

0:07:28.560,0:07:29.700
撒点葱花就可以了

0:07:31.000,0:07:31.960
四伯爷尝哈不

0:07:31.960,0:07:32.760
可以啊

0:07:33.860,0:07:35.080
辣呼辣呼的

0:07:35.660,0:07:36.860
嗯 安逸

0:07:38.220,0:07:39.160
很要入味噶

0:07:39.160,0:07:40.120
很有好入味 还多

0:07:40.340,0:07:43.080
没有放盐巴 就是我觉得咸了一点点

0:07:43.080,0:07:47.640
不关事嘛 咸点不管下烧酒下饭也好都可以撒

0:07:47.640,0:07:48.500
嗯 要得

0:07:48.545,0:07:49.560
可以可以可以

0:07:49.560,0:07:51.605
好 把火熄了嘛

0:07:51.605,0:07:53.020
老子要二回多整点

0:07:54.360,0:07:55.260
嗯 我在那方（饭厅）等你哦

0:07:55.260,0:07:56.080
好嘛好

**Comment by immoonancient** [comment]
我来堵抢眼了...

**Comment by immoonancient** [comment]
bot, please upload

0:00:00.360,0:00:01.060
嗨喽大家好
Hello everyone

0:00:01.060,0:00:03.120
上次我们不是做了腊鱼吗
Last time we made some cured fish

0:00:03.120,0:00:07.220
这个腊鱼后面抹了一些辣椒还有花椒
There are some chili and Sichuan peppercorns on it

0:00:07.220,0:00:08.740
因为四川都要吃辣嘛
You know, everyone eats chilis in Sichuan

0:00:08.745,0:00:11.035
现在准备拿一条弄来吃一下
Now we are going to have one of the fish

0:00:11.040,0:00:12.680
看一下味道怎么样
See how it tastes

0:00:12.680,0:00:16.280
冬天了是吃香腊 这个腊味的时候了
It’s winter now. It’s the season for enjoying cured food

0:00:16.280,0:00:17.520
噶 四伯爷
Right, uncle?

0:00:17.980,0:00:18.900
嗯 是按
Hmm, yeah

0:00:18.980,0:00:20.720
吃来试哈看嘛 看安不安逸嘛
Let’s have a try, see if it’s nice

0:00:20.720,0:00:21.620
煮一条就是哈
Cook one of them?


0:00:21.640,0:00:23.720
啊整一条嘛 少整点来试一哈看
Ah, just one. Not too much, just have a try

0:00:23.720,0:00:24.240
要得
Sure

0:00:24.960,0:00:27.520
这个鱼弄开 把这个割开
Open the fish, and cut this

0:00:27.760,0:00:29.780
先把它放到锅里面煮一下
Need to boil it first

0:00:29.920,0:00:31.760
但是我现在先配一下料
But I got to prepare the other stuff

0:00:32.060,0:00:33.100
这个先放这边哈
Leave it here first

0:00:35.560,0:00:37.020
这个料非常简单
It’s very simple

0:00:37.020,0:00:38.960
就是姜跟蒜
Only ginger and garlic

0:00:39.280,0:00:41.440
你不拿花（椒） 不用花椒吗
You don’t take pep… No Sichuan peppercorns?

0:00:41.440,0:00:42.140
昂
Huh?

0:00:42.140,0:00:43.300
不拿花椒吗
You don’t need Sichuan peppercorns?

0:00:43.300,0:00:43.880
要
I do

0:00:44.400,0:00:45.220
对咯
That’s right

0:00:49.460,0:00:51.520
这个姜蒜稍微多一点
Need a bit more ginger and garlic

0:00:52.480,0:00:54.340
一起剁碎了就行了
Just mince everything together

0:00:56.720,0:00:59.860
这个做法是贵州 就是我老婆她们那边
This is a Guizhou recipe. It’s from my wife’s hometown

0:00:59.860,0:01:01.160
少数民族的一种做法
From the ethnic minorities there

0:01:02.700,0:01:05.480
他们喜欢这样子做的话是因为这个姜蒜
They prefer this recipe, as they

0:01:05.480,0:01:07.795
下锅爆香了之后加那个干辣椒
fry the ginger and garlic to fragrant, and then add dried chili

0:01:07.800,0:01:09.480
然后再跟那个鱼一起炒
and stir fry with the fish

0:01:09.480,0:01:10.980
炒香了再用来蒸
and finally steam it

0:01:11.040,0:01:13.500
把这个姜蒜的香味蒸到鱼里面去
so that the flavor of garlic and ginger is steamed into the fish

0:01:14.700,0:01:15.620
好了
Alright

0:01:16.480,0:01:18.260
所以一般会多一些
So we need more of these

0:01:18.260,0:01:19.540
少数民族的做法
This is an ethnic recipe

0:01:21.800,0:01:23.660
然后再切点这个干辣椒
Then we chop some dried chili

0:01:27.940,0:01:29.440
干辣椒切开就行了
Just chop it like this

0:01:30.620,0:01:33.860
其实干辣椒用刀切比用剪刀更快
In fact, chopping is more efficient than cutting with scissors

0:01:37.700,0:01:42.640
我还准备了一些这个辣椒面跟花椒粉
I also prepared some chili powder and Sichuan pepper powder

0:01:44.620,0:01:46.160
今天的猪肉好不好卖哦四伯爷
How’s your pork business today, uncle?

0:01:46.160,0:01:47.260
今天没卖
No business today

0:01:47.460,0:01:48.520
今天休息啊
Closed today?

0:01:48.720,0:01:49.680
休息
Closed

0:01:50.600,0:01:52.100
我以为你今天赶场去了
I thought you went to the market

0:01:52.100,0:01:55.860
每天赶三道场太累了 休息一天
It’s too tiring to work in three markets everyday. I’m a rest

0:01:55.860,0:01:57.340
干两天休息一天
Work for two days, then rest for one day

0:01:58.800,0:02:00.820
这个火现在起来了我要加点水
Now the fire is on, I’ll add some water

0:02:00.820,0:02:02.960
把这个鱼放下去先煮个十分钟
Put the fish in and boil for 10 minutes

0:02:02.960,0:02:06.740
把它的一些盐味啊咸味啊还有一些辣味啊
To get rid of the saltiness, spiciness

0:02:06.740,0:02:09.600
还有一些不好的味道先除一下味
and some other unpleasant tastes. To reduce them

0:02:14.800,0:02:16.580
你这个瓜瓢都用了很多年了噶
You’ve been using this scoop for quite many years?

0:02:17.560,0:02:19.500
田土下户你想哈看
Since the 1980s. Think about it! # 家庭联产承包责任制什么的太难解释了，算了吧...

0:02:20.080,0:02:22.500
煮腊肉一般我们冷水下锅更好一些
To boil cured meat, it’s better to start boiling in cold water

0:02:23.260,0:02:25.180
冷水下锅更容易煮透 是噶
That makes it easier to cook through

0:02:26.360,0:02:31.580
因为我们农村这个腊鱼腊肉咸味都会稍微重一些
Our countryside homemade cured fish and pork are typically very salty

0:02:31.600,0:02:33.860
所以就先放水里面煮一次
so we boil it in water first

0:02:35.480,0:02:37.780
煮完了之后再用这个姜蒜辣椒
After boiling, we season it again with

0:02:37.820,0:02:41.760
还有这个花椒面一起再重新调味
ginger, garlic, chili and Sichuan pepper powder

0:02:41.760,0:02:43.520
再放点白糖中和一下
And neutralize it with some sugar

0:02:43.520,0:02:45.460
最后再放到锅里面蒸
And finally steam it

0:02:45.760,0:02:48.360
四伯爷 你说你小时候非凡
Uncle, you said you were “extraordinary” when you were young

0:02:49.340,0:02:50.360
有好凡呢
How extraordinary was it?

0:02:50.360,0:02:51.860
哎呀 啥样都干过
Eiya, I’ve done all kinds of things

0:02:51.960,0:02:52.620
啥样都干过
You’ve done all kinds of things?

0:02:52.620,0:02:54.140
哦 啥样都干过
Yeah, everything

0:02:54.140,0:02:54.680
比如呢
For example?

0:02:54.680,0:02:55.740
烧锅锅酒儿（过家家）啊
Playing grown up

0:02:55.740,0:02:57.220
得屠场头割肉啊
Taking meat from the slaughterhouse

0:02:57.460,0:02:59.480
人家的边口（猪肉）搭得那板板高头及
They left those “biankou” (pork) on some tall platforms

0:02:59.480,0:03:01.560
一爪就把人家的腰子给人家逮（拿）了
I reached out and grabbed the kidney

0:03:01.560,0:03:02.960
逮起出去烧锅锅酒儿
Grabbed it to play grown up

0:03:04.280,0:03:06.675
伯娘那哈说你留长头发多帅的噶
Aunt said you had long hair before, which was cool then?

0:03:06.675,0:03:07.680
嗯 是啊
Hmm, yeah

0:03:07.680,0:03:11.120
那哈照身份证的时候拿钢夹（发夹）锁起来照
At that time, when taking my ID photo, I got to use a hair clip

0:03:11.700,0:03:12.600
照那个时候
when taking the photo

0:03:12.700,0:03:14.300
你是咋子追的四伯娘
How did you marry aunt?

0:03:15.580,0:03:17.180
哎呀 那个时候
Eiya… At that time

0:03:17.200,0:03:21.860
我们认到就是那哈儿最初那个田土下放的时候
We met each other in 1980s, when we got the fields

0:03:21.860,0:03:24.560
买起电影机子看电影
We bought a movie machine to watch movies

0:03:24.560,0:03:26.000
就看那个天仙配
We watched Tian Xian Pei (aka Fairy Couple)

0:03:26.000,0:03:26.500
啊
Ah

0:03:26.580,0:03:29.120
就看了连续我就看了七场
I watched it for 7 times in a row

0:03:29.600,0:03:31.720
好 那哈子才想耍朋友了
Then I realized I needed a girlfriend

0:03:32.560,0:03:34.380
否则还没得那个感觉得
Otherwise, I had so such idea in my mind

0:03:34.660,0:03:37.180
诶 那个天仙配看了来启发了我
Eh, so apparently the movie inspired me

0:03:38.640,0:03:40.420
不是的话 我都还是光棍
Otherwise, I’m still single

0:03:40.740,0:03:43.660
司令还是个 光棍司令是个
Lonely single man # 这个实在没法翻译...

0:03:47.100,0:03:48.640
这个鱼快要熟了
The fish is almost cooked

0:03:48.640,0:03:50.020
辣椒面都浮起来了
The chili powder is already floating

0:03:50.600,0:03:55.820
其实这个辣椒面它腌鱼的话就不是说用来一直让它在肉里面
Actually, when curing fish with chili powder, you don’t need it to stay in the fish

0:03:55.820,0:03:57.440
这个就是取它的味道
You just need the flavor

0:04:00.520,0:04:04.500
好了 四伯爷先不忙放柴了
Alright, uncle, no more firewoods for now

0:04:04.800,0:04:05.840
这个鱼要得了
The fish is done

0:04:07.080,0:04:08.260
我拿起去砍
I’ll chop it

0:04:13.100,0:04:14.780
哇 这个鱼还不是特别干
Wow, the fish isn’t very dry yet

0:04:15.020,0:04:17.720
要是再干一点的话肯定会更香一些
It should be more flavorful if it has become drier

0:04:18.795,0:04:20.055
我拿起去砍去了
I’ll take it to chop

0:04:20.425,0:04:22.340
要得 这哈子就不烧（火）咯
OK. You don’t need the fire now?

0:04:22.340,0:04:23.380
暂时不烧
Not for now

0:04:24.060,0:04:27.820
这条鱼还没 还没到时间所以有一点嫩
This fish hasn’t been preserved for long enough, so it’s still a bit soft

0:04:29.560,0:04:32.120
不管它 先砍来尝一下味道
Never mind. Chop it and have a try

0:04:50.640,0:04:51.160
好
Alright

0:04:51.160,0:04:52.420
现在放一点点油
Add a little bit oil

0:04:54.000,0:04:55.840
这个可以稍微多那么一点点
Can be a little bit more

0:04:57.660,0:05:01.920
其实做鱼的话还是要这个菜油更香哈
For fish, it’s rapeseed oil that gives the best flavor?

0:05:01.920,0:05:07.080
吃鱼不是菜油不好吃 有些拿那个植物油来煎起就不安逸
Must use rapeseed oil for fish. Those vegetable oil 

0:05:08.920,0:05:12.520
好了 这个油已经在冒大烟了
Alright, the oil is smoking a lot

0:05:12.520,0:05:14.080
说明这个菜籽油已经熟了
which means the rapeseed oil is already cooked

0:05:14.800,0:05:15.980
现在放点花椒
Now add in some Sichuan peppercorns

0:05:17.020,0:05:19.120
再放这个干辣椒爆一下
And add in some dried chili and fry

0:05:20.480,0:05:21.760
再放这个姜蒜粒
And diced ginger garlic

0:05:25.240,0:05:26.520
（火）小滴点儿的 四伯爷
Lower fire, uncle

0:05:27.180,0:05:29.660
才两三根柴呢 两根都不够
There are just two fire logs. Not even two

0:05:32.000,0:05:34.980
炒到这个姜蒜粒香了之后再放这个辣椒面
When the diced ginger and garlic turns fragrant, add in the chili powder

0:05:35.300,0:05:38.000
辣椒面是出颜色的 也是出香味的
Chili powder gives both the color and the flavor

0:05:39.220,0:05:40.740
可以稍微多一点
We can use some more

0:05:40.740,0:05:42.240
少整点 多很了辣得很哦
Enough, it will be too spicy

0:05:42.240,0:05:45.040
不关事 这个是蒸的
Doesn’t matter. This is steamed

0:05:45.040,0:05:46.740
这个蒸的都辣
Steamed is also spicy

0:05:47.500,0:05:48.500
好嘛
OK

0:05:50.020,0:05:51.560
稍微小滴点儿的 四伯爷 火
A bit lower, uncle. The fire

0:05:51.820,0:05:53.400
然后放这个鱼下去炒
Then add in the fish and stir fry

0:05:56.820,0:05:58.600
因为这个鱼可能有一点嫩
As the fish is still kind of soft

0:05:59.880,0:06:01.660
所以翻动的时候轻一点
the operation should be gentle

0:06:02.980,0:06:05.000
我们这个调味只放白糖
We only use white sugar fo seasoning

0:06:05.780,0:06:08.620
因为这个是腊鱼 放白糖可以压住它的咸味
White sugar neutralizes the saltiness in the cured fish

0:06:09.200,0:06:10.560
再放一点花椒面
Also a little Sichuan pepper powder

0:06:13.440,0:06:15.160
花椒面可以稍微多一些
Can be a little more

0:06:15.980,0:06:18.120
等它炒匀了就可以起锅了
Toss it evenly, and then we can plate it

0:06:22.360,0:06:24.620
好 炒匀了就起锅
Alright, it’s even. Let’s plate it

0:06:25.300,0:06:26.600
直接就放到这个碗里面
Just put it into this bowl

0:06:34.560,0:06:37.440
这个鱼非常的香 又香又入味
The fish is so fragrant. Fragrant and flavorful

0:06:44.460,0:06:46.640
现在我们把这个盖上蒸一会儿
Now let’s cover it and steam it for a while

0:06:46.980,0:06:50.960
让它那个菜油充分的把这个香味蒸到鱼里面
So that the rapeseed oil carries all the flavors into the fish

0:06:51.460,0:06:52.580
大概十分钟
About 10 minutes

0:06:52.920,0:06:55.140
最后出来的时候就撒上葱花就可以了
And finally top it with some chopped green onion before serving

0:06:57.920,0:07:00.300
现在已经蒸了十多分钟了 差不多了
Ten minutes now. Should be there

0:07:00.740,0:07:01.740
我看哈看
Let me check

0:07:03.300,0:07:04.000
哦哟
Oh

0:07:04.000,0:07:05.380
还多香 蒸起
It smells so good after steaming

0:07:06.680,0:07:07.720
颜色还多安逸噶
The color looks nice, huh?

0:07:07.720,0:07:08.880
我尝哈味道怎么样
Let me check how it tastes

0:07:11.580,0:07:12.660
先整来告（试）哈看
Let me check

0:07:16.660,0:07:18.200
嗯 这个味道已经融合了
Hmm, the flavors have already fused

0:07:18.200,0:07:20.480
融合了这个调料的味道
Have already fused the flavors of the seasonings

0:07:20.480,0:07:21.800
差不多了 我端咯
Should be good now. I’ll take it out

0:07:21.800,0:07:23.260
烫哦 慢点儿哦
It’s hot. Be careful!

0:07:23.260,0:07:24.000
不关事
I’m fine

0:07:25.580,0:07:26.720
诶呀 四伯爷 火就不烧了
Eiya, uncle, we can put out the fire

0:07:26.720,0:07:27.420
要得
Sure

0:07:28.560,0:07:29.700
撒点葱花就可以了
Sprinkle some chopped green onion, then it’s good to go

0:07:31.000,0:07:31.960
四伯爷尝哈不
Have a try, uncle?

0:07:31.960,0:07:32.760
可以啊
Yeah

0:07:33.860,0:07:35.080
辣呼辣呼的
Kind of spicy, huh?

0:07:35.660,0:07:36.860
嗯 安逸
Hmm, nice

0:07:38.220,0:07:39.160
很要入味噶
Very flavorful, isn’t it?

0:07:39.160,0:07:40.120
很有好入味 还多
Very flavorful, and...

0:07:40.340,0:07:43.080
没有放盐巴 就是我觉得咸了一点点
I didn’t add salt. I felt like it’s a bit too salty

0:07:43.080,0:07:47.640
不关事嘛 咸点不管下烧酒下饭也好都可以撒
I don’t mind. It’s still good with shaojiu (liquor) or rice

0:07:47.640,0:07:48.500
嗯 要得
Hmm, OK

0:07:48.545,0:07:49.560
可以可以可以
Good, good, good

0:07:49.560,0:07:51.605
好 把火熄了嘛
Alright, let’s put out the fire

0:07:51.605,0:07:53.020
老子要二回多整点
Next time Imma make more of dis

0:07:54.360,0:07:55.260
嗯 我在那方（饭厅）等你哦
Yeah. Join us in the dining room

0:07:55.260,0:07:56.080
好嘛好
OK, yeah

**Comment by immoonancient** [comment]
修正版已上传，等发布

**Comment by immoonancient** [comment]
已发布
