### ISSUE TITLE
【美食作家王刚】6种饺子馅 - https://youtu.be/hkgou-S6aZk

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#547]
【美食作家王刚】6种饺子馅 - https://youtu.be/hkgou-S6aZk
视频时长 11:40，预计发布时间为北京时间1月6日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.225,0:00:01.225
哈喽大家好

0:00:01.240,0:00:04.840
最近很多粉丝在问过年做点什么菜

0:00:04.840,0:00:08.320
我觉得过年其实有很多菜可以做

0:00:08.320,0:00:12.860
但是这些菜（我觉得）都没有饺子更合适嘎

0:00:12.860,0:00:13.660
嗯

0:00:13.660,0:00:18.440
今天所以我跟我伯爷一起来做几种这个饺子馅

0:00:18.440,0:00:22.180
我准备了一些牛肉、虾、（猪）肉、还有鸡蛋

0:00:22.180,0:00:24.640
还有一些其他的辅料

0:00:25.500,0:00:27.060
我先准备好这些东西

0:00:29.740,0:00:31.540
来嘛 四伯爷 帮着剥这个虾

0:00:31.540,0:00:32.860
这个咋个整嘛

0:00:32.880,0:00:35.280
把虾子的肉剥出来

0:00:36.560,0:00:37.560
这样子剥一哈

0:00:42.560,0:00:43.700
剥的来不

0:00:45.420,0:00:47.780
这有啥子剥不来安 逮都脑壳跟它一扯

0:00:49.320,0:00:50.480
是不是

0:00:52.100,0:00:54.880
不是的 这个要一哈要剥下来

0:00:54.885,0:00:56.560
一哈剥下来

0:00:56.560,0:00:57.840
对 把肉一哈剥下来 不是扯脑壳

0:00:59.280,0:01:01.580
这个虾如果你们不好剥的话

0:01:02.160,0:01:03.520
就拿去冰箱冻一下

0:01:03.520,0:01:04.820
把它冻硬了就很好剥

0:01:05.460,0:01:06.580
这是一个小技巧

0:01:07.760,0:01:12.180
哎呀 随便啥子东西还是要熟能生巧 要多干

0:01:12.820,0:01:13.680
确实是

0:01:13.700,0:01:16.020
实践出真经

0:01:17.020,0:01:18.020
好不好剥嘛

0:01:19.160,0:01:20.460
就是没得好好剥的

0:01:22.440,0:01:23.820
我剥都没剥过

0:02:31.240,0:02:32.720
先把它切成片片儿

0:02:32.780,0:02:36.140
然后把它切成颗颗儿

0:02:37.680,0:02:40.340
切成丝 横竖跟它切

0:02:40.740,0:02:41.400
是安

0:02:42.140,0:02:43.240
更快都嘛

0:02:45.760,0:02:47.580
四伯还是懂得起哦

0:02:51.645,0:02:52.675
横着切一下

0:02:53.660,0:02:56.540
切了再宰一下

0:02:58.280,0:03:01.320
其实这个饺子馅不需要剁得太细的嘎

0:03:02.540,0:03:04.620
太细了反而吃起没得口感的

0:04:26.220,0:04:28.480
好了 现在我们这些料已经准备好了

0:04:28.480,0:04:29.520
不过这个料太多了

0:04:29.520,0:04:30.740
就一样一样的来

0:04:31.220,0:04:34.480
第一个饺馅儿就是三鲜馅儿

0:04:34.800,0:04:35.540
三鲜的哈 四伯爷

0:04:35.540,0:04:36.380
三鲜的啊

0:04:36.380,0:04:36.940
嗯

0:04:37.860,0:04:39.000
三鲜的话

0:04:39.000,0:04:42.700
我们先调的就是这个虾

0:04:42.700,0:04:46.660
鲜虾 虾仁 把它剥了壳之后剁碎的

0:04:46.660,0:04:47.500
先放一点

0:04:48.120,0:04:50.080
然后我切了一些香菇

0:04:50.900,0:04:53.100
这也是带鲜味的 给它一起放进去

0:04:53.840,0:04:55.180
香菇可以多一点

0:04:59.120,0:05:02.020
然后又加点木耳 这个木耳是水（泡）发的

0:05:02.020,0:05:03.820
然后给它剁碎了 新鲜的也可以

0:05:06.480,0:05:08.920
再加一点这个葱 这个小葱

0:05:12.320,0:05:15.220
调味的话都是一样的 就是放点盐

0:05:18.240,0:05:19.560
然后再放点胡椒粉

0:05:25.860,0:05:27.580
再放点这个生抽酱油

0:05:29.460,0:05:31.140
酱油可以稍微少一些

0:05:33.080,0:05:34.240
然后就给它抓匀

0:05:38.220,0:05:39.900
这个虾仁嘛 是新鲜的

0:05:40.180,0:05:43.100
加点盐进去给它这样子顺着一个方向搅（搅）

0:05:43.100,0:05:45.620
它会上劲 有粘性了就可以了

0:05:46.080,0:05:47.480
这个饺子就成了

0:05:48.360,0:05:49.420
饺子馅就成了

0:05:49.420,0:05:50.600
好 这是第一种

0:05:50.960,0:05:56.160
如果大家喜欢的话还可以加一点这个胡萝卜进去配一下颜色

0:05:57.000,0:05:59.300
加胡萝卜的话小孩子就比较喜欢吃

0:05:59.300,0:06:00.460
它是脆脆的

0:06:01.720,0:06:03.360
好第一个（饺子馅）就成了

0:06:03.780,0:06:05.240
三鲜就成了

0:06:06.420,0:06:09.660
第二种我们用这个牛肉 做牛肉馅的

0:06:10.040,0:06:12.360
这个是剁好的那个牛里脊肉

0:06:12.720,0:06:14.980
牛肉馅的饺子放芹菜更好吃

0:06:16.100,0:06:18.260
抓一点芹菜进去 这个牛肉有点多

0:06:20.080,0:06:23.400
这个比例的话根据大家自己的喜好来

0:06:23.940,0:06:25.900
这个的话是我们本地的韭黄

0:06:26.100,0:06:28.180
加点韭黄进去 增香

0:06:30.300,0:06:33.380
然后加点这个马蹄（荸荠）

0:06:34.035,0:06:35.320
我们这喊啥子安这个

0:06:35.320,0:06:38.000
我们这里喊的是“茨瓜儿”

0:06:38.560,0:06:41.180
这个是削了皮被我剁碎的

0:06:42.520,0:06:45.220
然后加点这个干香菇

0:06:45.720,0:06:48.260
这个是干香菇 加进去增香的

0:06:50.020,0:06:53.740
这个馅儿叫做香菇牛肉馅

0:06:53.940,0:06:55.480
调味还是放盐

0:06:56.280,0:06:58.200
这个盐可以稍微重一点点

0:07:00.680,0:07:04.040
然后根据口味调一下 加点酱油

0:07:07.120,0:07:11.180
因为这个牛肉是里脊 是瘦的

0:07:11.420,0:07:13.100
所以要加点香油

0:07:13.720,0:07:14.880
滋润一下

0:07:18.900,0:07:20.720
再加一点胡椒粉

0:07:22.380,0:07:23.920
好了 抓匀

0:07:23.920,0:07:26.880
就像刚才那个鲜虾（馅）是一样的

0:07:27.700,0:07:30.340
好了 这个抓匀就可以了

0:07:31.215,0:07:34.125
下一个是鸡蛋韭菜 （馅）

0:07:34.460,0:07:35.940
韭菜鸡蛋馅儿

0:07:35.940,0:07:38.020
这个鸡蛋我放了6个 煎得

0:07:38.020,0:07:41.460
煎了之后把它弄碎 韭菜就放一半就行了

0:07:41.560,0:07:44.020
因为韭菜放多了加了盐它会出水

0:07:45.080,0:07:47.800
这个的话就只要韭菜跟鸡蛋就OK

0:07:48.960,0:07:51.920
同样的是调味 加一点点盐

0:07:53.880,0:07:56.400
这个的话因为煎鸡蛋的时候有放油

0:07:56.400,0:07:59.800
现在只放盐就行了 不用放其他的调料

0:08:01.720,0:08:05.380
同样的然后给它拌匀就可以用来包饺子

0:08:05.960,0:08:07.920
这样子拌匀就算一个馅儿

0:08:08.080,0:08:09.580
现在我们来调第四种

0:08:09.700,0:08:11.380
就是大白菜猪肉馅

0:08:11.380,0:08:13.480
这个大白菜我们要把它处理一下

0:08:13.940,0:08:15.120
加一勺盐进去

0:08:16.580,0:08:19.640
让它提前脱一下水给它抓一下

0:08:19.680,0:08:22.360
因为大家都知道大白菜水分比较多

0:08:22.820,0:08:26.680
如果是说不脱水的话包出来很多水就不好吃了

0:08:27.380,0:08:28.980
四伯爷 你喜欢吃哪种馅儿安

0:08:29.260,0:08:32.760
吃哪种馅 我看你整的个个馅我都喜欢吃

0:08:32.960,0:08:33.600
是不哦

0:08:33.600,0:08:34.180
是啊

0:08:34.980,0:08:37.580
你不喜欢吃啥子味道的馅嘛 你说

0:08:39.020,0:08:42.900
那种甜的我就没得好喜欢吃的

0:08:43.200,0:08:45.840
好了 现在这个白菜我随便抓两下

0:08:45.840,0:08:47.660
这个水都已经出来了

0:08:52.960,0:08:54.140
先让它脱一下水

0:08:54.140,0:08:58.240
免得带到肉里面去 水分它会溢出来

0:09:09.500,0:09:11.020
然后加点肉进去

0:09:11.020,0:09:14.400
肉的话根据你们自身家庭情况来放

0:09:16.460,0:09:18.660
然后还是要调一点酱油

0:09:18.660,0:09:20.740
白菜其实是已经有盐的了

0:09:21.300,0:09:23.060
调了酱油以后再打一个 （鸡蛋）

0:09:23.380,0:09:24.900
这点肉打不了一个（鸡蛋）

0:09:25.320,0:09:27.640
打半个鸡蛋就可以了

0:09:27.980,0:09:31.500
给它做的嫩一些 蛋清就行

0:09:31.860,0:09:33.580
同样的再加一点胡椒粉 然后给它拌匀

0:09:36.480,0:09:37.760
然后给它拌匀

0:09:40.680,0:09:42.740
好 现在我们来第五种

0:09:43.120,0:09:45.740
第五种的话就是香菇加肉

0:09:45.740,0:09:49.820
这个是干香菇 泡发好的干香菇 加进去

0:09:49.820,0:09:53.860
然后这个是新鲜的香菇 相互配合

0:09:55.160,0:09:57.140
然后加点这个肉 肥肉

0:09:57.520,0:09:59.060
也不是肥肉 就是五花肉

0:10:00.180,0:10:01.420
加一点进去

0:10:03.560,0:10:06.320
然后这个的话可以配一些胡萝卜配颜色

0:10:06.320,0:10:09.000
这个小孩子特别喜欢

0:10:09.420,0:10:11.040
再加一点这个马蹄

0:10:11.400,0:10:14.460
马蹄吃起来口感脆脆的 很不错

0:10:14.460,0:10:17.820
同样也是这些调料 盐

0:10:20.200,0:10:21.900
加点盐 加点酱油

0:10:23.400,0:10:24.860
再加点胡椒粉

0:10:25.940,0:10:29.860
这个因为它是自带肥油了 所以就不用再加油了

0:10:30.080,0:10:31.920
好了 现在还有最后一种

0:10:31.920,0:10:33.560
最后一种就随意一点

0:10:34.080,0:10:36.680
加点这个肉 把剩下的肉全部放进去

0:10:36.960,0:10:40.720
然后这个 我们本地的韭黄放一些

0:10:41.260,0:10:42.740
再放一些韭菜

0:10:43.620,0:10:45.060
韭菜放进去香啊

0:10:45.380,0:10:46.380
多放点

0:10:47.020,0:10:50.820
这个小葱 给它放一半的小葱

0:10:51.520,0:10:54.340
然后这个马蹄再放一些进去

0:10:55.320,0:10:56.840
再放几颗胡萝卜

0:10:58.720,0:11:00.100
然后再调一下味

0:11:01.500,0:11:02.460
盐

0:11:05.160,0:11:06.300
酱油

0:11:10.640,0:11:11.540
胡椒粉

0:11:15.040,0:11:16.720
好 给它抓匀就行了

0:11:18.660,0:11:20.720
这个可以根据你们个人口味来

0:11:20.720,0:11:22.880
有的他也加味精 鸡精

0:11:22.880,0:11:24.780
但是我觉得没有这个必要

0:11:25.065,0:11:26.220
自己家里面吃的话

0:11:26.220,0:11:29.080
行了 你看 香得很

0:11:29.560,0:11:30.560
你闻哈看嘛

0:11:31.460,0:11:32.640
是不是  嗯

0:11:32.960,0:11:35.940
好了 现在我们这6个馅都已经和完了

0:11:35.940,0:11:37.340
就是把它已经拌好了

**Comment by riana33** [comment]
认领

**Comment by riana33** [comment]
bot, please upload
0:00:00.225,0:00:01.225
# 哈喽大家好
Hello everyone, this is Wang Gang
0:00:01.240,0:00:04.840
#最近很多粉丝在问过年做点什么菜
Recently, a lot of you guys are asking 
0:00:04.840,0:00:08.320
# 我觉得过年其实有很多菜可以做
I believe there are many options
0:00:08.320,0:00:12.860
# 但是这些菜（我觉得）都没有饺子更合适嘎
But all these dishes ( I personally think )
0:00:12.860,0:00:13.660
# 嗯
Um
0:00:13.660,0:00:18.440
# 今天所以我跟我伯爷一起来做几种这个饺子馅
So today I will make several types of stuffing with my uncle
0:00:18.440,0:00:22.180
# 我准备了一些牛肉、虾、（猪）肉、还有鸡蛋
I prepared some beef, shrimp, pork and eggs 
0:00:22.180,0:00:24.640
# 还有一些其他的辅料
and some minor ingredients
0:00:25.500,0:00:27.060
# 我先准备好这些东西
Let me prepare these stuffs first
0:00:29.740,0:00:31.540
# 来嘛 四伯爷 帮着剥这个虾
Come on, Uncle help me peel the shrimp
0:00:31.540,0:00:32.860
# 这个咋个整嘛
How to do it?
0:00:32.880,0:00:35.280
# 把虾子的肉剥出来
Taking the meat part of shrimp
0:00:36.560,0:00:37.560
# 这样子剥一哈  
Like this
0:00:42.560,0:00:43.700
# 剥的来不
Are you ok with it?
0:00:45.420,0:00:47.780
# 这有啥子剥不来安 逮都脑壳跟它一扯
It is nothing hard. Catch the head and drag it
0:00:49.320,0:00:50.480
# 是不是
Am I right?
0:00:52.100,0:00:54.880
# 不是的 这个要一哈要剥下来
No, you need to peel both of them together
0:00:54.885,0:00:56.560
# 一哈剥下来 
Altogether?
0:00:56.560,0:00:57.840
#对 把肉一哈剥下来 不是扯脑壳
Yes, come with the shrimp body part, not the head 
0:00:59.280,0:01:01.580
# 这个虾如果你们不好剥的话
If you guys have problem with peeling shrimp 
0:01:02.160,0:01:03.520
# 就拿去冰箱冻一下
You could put them in refrigerator for freezing 
0:01:03.520,0:01:04.820
# 把它冻硬了就很好剥
When they are frozen, it becomes easy to clean them
0:01:05.460,0:01:06.580
# 这是一个小技巧
Here is a tip
0:01:07.760,0:01:12.180
# 哎呀 随便啥子东西还是要熟能生巧 要多干
Aiya, no matter what XXX, you need to practice more 
0:01:12.820,0:01:13.680
# 确实是
That’s true
0:01:13.700,0:01:16.020
# 实践出真经
Truth comes from practice
0:01:17.020,0:01:18.020
# 好不好剥嘛
Is it easy to peel the shrimp?
0:01:19.160,0:01:20.460
# 就是没得好好剥的
Nope 
0:01:22.440,0:01:23.820
# 我剥都没剥过
I’ve never tried it
0:02:31.240,0:02:32.720
# 先把它切成片片儿
First, slice it into pieces 
0:02:32.780,0:02:36.140
# 然后把它切成颗颗儿
And then cut them into little cubes 
0:02:37.680,0:02:40.340
# 切成丝 横竖跟它切
cut into shreds 
0:02:40.740,0:02:41.400
# 是安
Yeah
0:02:42.140,0:02:43.240
# 更快都嘛
It’s faster
0:02:45.760,0:02:47.580
# 四伯还是懂得起哦
Oh, uncle, you know a lot 
0:02:51.645,0:02:52.675
# 横着切一下
 First cut it in the horizontal direction
0:02:53.660,0:02:56.540
# 切了再宰一下
then gathering all of them
0:02:58.280,0:03:01.320
# 其实这个饺子馅不需要剁得太细的嘎
actually you don't need to mince the dumpling stuffing too small
0:03:02.540,0:03:04.620
# 太细了反而吃起没得口感的
Otherwise, when you taste it, it will lose a part of texture 
0:04:26.220,0:04:28.480
# 好了 现在我们这些料已经准备好了
OK now we are finish preparing of these ingredients 
0:04:28.480,0:04:29.520
# 不过这个料太多了
But the mount of total ingredients is huge 
0:04:29.520,0:04:30.740
# 就一样一样的来  
Just do it one by one
0:04:31.220,0:04:34.480
# 第一个饺馅儿就是三鲜馅儿
First one is Sanxian stuffing 
0:04:34.800,0:04:35.540
# 三鲜的哈 四伯爷
0:04:35.540,0:04:36.380
# 三鲜的啊
Oh~ Sanxian 
0:04:36.380,0:04:36.940
# 嗯
Yes
0:04:37.860,0:04:39.000
# 三鲜的话
For Sanxian flavor 
0:04:39.000,0:04:42.700
# 我们先调的就是这个虾
What we make first is the shrimp
0:04:42.700,0:04:46.660
# 鲜虾 虾仁 把它剥了壳之后剁碎的
Fresh shrimps after cleaning, cut them into small cubes
0:04:46.660,0:04:47.500
# 先放一点
Add a little bit 
0:04:48.120,0:04:50.080
# 然后我切了一些香菇
The cut some mushrooms 
0:04:50.900,0:04:53.100
# 这也是带鲜味的 给它一起放进去
They have umami taste, let’s put them together 
0:04:53.840,0:04:55.180
# 香菇可以多一点
We could add a bit more mushroom 
0:04:59.120,0:05:02.020
# 然后又加点木耳 这个木耳是水（泡）发的
Then add some wood-ear mushroom, it is dried, you need to put them in water first 
0:05:02.020,0:05:03.820
# 然后给它剁碎了 新鲜的也可以
And cut them into small pieces, you could also choose to use fresh wood-ear mushroom
0:05:06.480,0:05:08.920
# 再加一点这个葱 这个小葱
And add some spring onion 
0:05:12.320,0:05:15.220
# 调味的话都是一样的 就是放点盐
For seasoning, it’s salt 
0:05:18.240,0:05:19.560
# 然后再放点胡椒粉
and some pepper powder 
0:05:25.860,0:05:27.580
# 再放点这个生抽酱油
and some soy sauce (Shengchou)
0:05:29.460,0:05:31.140
# 酱油可以稍微少一些
Not too much soy sauce
0:05:33.080,0:05:34.240
# 然后就给它抓匀
and mix all of them 
0:05:38.220,0:05:39.900
# 这个虾仁嘛 是新鲜的
The shrimp is fresh 
0:05:40.180,0:05:43.100
# 加点盐进去给它这样子顺着一个方向搅（搅）
add some salt in it and mix it from same direction like a circle 
0:05:43.100,0:05:45.620
# 它会上劲 有粘性了就可以了
and it will become sticky
0:05:46.080,0:05:47.480
# 这个饺子就成了
The dumplings are made  
0:05:48.360,0:05:49.420
# 饺子馅就成了
The dumpling stuffing has been prepared 
0:05:49.420,0:05:50.600
# 好 这是第一种
This is the first type
0:05:50.960,0:05:56.160
# 如果大家喜欢的话还可以加一点这个胡萝卜进去配一下颜色
You guys could also add some carrots to make it more colorful, it’s up to you
0:05:57.000,0:05:59.300
# 加胡萝卜的话小孩子就比较喜欢吃
Children tend to like the dumpling with carrots in it
0:05:59.300,0:06:00.460
# 它是脆脆的
It is crunchy
0:06:01.720,0:06:03.360
# 好第一个（饺子馅）就成了
Well, the first dumpling is out here
0:06:03.780,0:06:05.240
# 三鲜就成了
Sanxian stuffing has already been prepared now 
0:06:06.420,0:06:09.660
# 第二种我们用这个牛肉 做牛肉馅的
Next we’ll make beef stuffing 
0:06:10.040,0:06:12.360
# 这个是剁好的那个牛里脊肉
It is minced beef tenderloin
0:06:12.720,0:06:14.980
# 牛肉馅的饺子放芹菜更好吃
beef with leaf celery is more delicious 
0:06:16.100,0:06:18.260
# 抓一点芹菜进去 这个牛肉有点多
get some leaf celery in it, the minced beef is a bit too much
0:06:20.080,0:06:23.400
# 这个比例的话根据大家自己的喜好来
the portion is up to you guys personal preference
0:06:23.940,0:06:25.900
# 这个的话是我们本地的韭黄
This is our local hotbed chives 
0:06:26.100,0:06:28.180
# 加点韭黄进去 增香
Add some hotbed chives, add more flavor 
0:06:30.300,0:06:33.380
# 然后加点这个马蹄（荸荠）
then add some water chestnut
0:06:34.035,0:06:35.320
# 我们这喊啥子安这个
What we call it here?
0:06:35.320,0:06:38.000
# 我们这里喊的是“茨瓜儿”
We call it Qianguaer in local dialect
0:06:38.560,0:06:41.180
# 这个是削了皮被我剁碎的
it has been peeled and chopped by me 
0:06:42.520,0:06:45.220
# 然后加点这个干香菇
Add some dry mushroom
0:06:45.720,0:06:48.260
# 这个是干香菇 加进去增香的
the dry mushroom is for adding aroma 
0:06:50.020,0:06:53.740
# 这个馅儿叫做香菇牛肉馅
This filling is called “mushroom beef stuffing”
0:06:53.940,0:06:55.480
# 调味还是放盐
Salt for seasoning as well
0:06:56.280,0:06:58.200
# 这个盐可以稍微重一点点
it could be a bit more of salt here
0:07:00.680,0:07:04.040
# 然后根据口味调一下 加点酱油
Then based on your own flavor, add some soy sauce 
0:07:07.120,0:07:11.180
# 因为这个牛肉是里脊 是瘦的
Because it is beef tenderloin, it is lean meet 
0:07:11.420,0:07:13.100
# 所以要加点香油
we need to add some sesame oil
0:07:13.720,0:07:14.880
# 滋润一下
for moisturizing 
0:07:18.900,0:07:20.720
# 再加一点胡椒粉
And add some pepper powder 
0:07:22.380,0:07:23.920
# 好了 抓匀
Okay, mix it 
0:07:23.920,0:07:26.880
# 就像刚才那个鲜虾（馅）是一样的
Just like how we mix shrimp stuffing previously 
0:07:27.700,0:07:30.340
# 好了 这个抓匀就可以了
Cool, now that is enough
0:07:31.215,0:07:34.125
# 下一个是鸡蛋韭菜 （馅）
Next one is egg with Chinese chive filling 
0:07:34.460,0:07:35.940
# 韭菜鸡蛋馅儿
egg with Chinese chive filling 
0:07:35.940,0:07:38.020
# 这个鸡蛋我放了6个 煎得
I fried six eggs 
0:07:38.020,0:07:41.460
# 煎了之后把它弄碎 韭菜就放一半就行了
After it’s cooked, mix it with half of Chinese chive
0:07:41.560,0:07:44.020
# 因为韭菜放多了加了盐它会出水
Because too many Chinese chives with salt will produce extra water
0:07:45.080,0:07:47.800
# 这个的话就只要韭菜跟鸡蛋就OK
For this stuffing only Chinese chives and eggs are enough
0:07:48.960,0:07:51.920
# 同样的是调味 加一点点盐
As for seasoning, a little bit salt 
0:07:53.880,0:07:56.400
# 这个的话因为煎鸡蛋的时候有放油
For this stuffing, because we have already fried it with oil 
0:07:56.400,0:07:59.800
# 现在只放盐就行了 不用放其他的调料
now we only need to add salt without any other seasoning 
0:08:01.720,0:08:05.380
# 同样的然后给它拌匀就可以用来包饺子
mix it finely, then we could use it for make dumplings 
0:08:05.960,0:08:07.920
# 这样子拌匀就算一个馅儿
After we mix it, we are finished one more dumpling stuffing making 
0:08:08.080,0:08:09.580
# 现在我们来调第四种
Now it is the fourth dumpling stuffing making 
0:08:09.700,0:08:11.380
# 就是大白菜猪肉馅
It is ”napa cabbage with pork “ filing 
0:08:11.380,0:08:13.480
# 这个大白菜我们要把它处理一下
We need to procees the napa cabbage first 
0:08:13.940,0:08:15.120
# 加一勺盐进去
Add one spoon of salt 
0:08:16.580,0:08:19.640
# 让它提前脱一下水给它抓一下
To dehydrate the napa cabbage, and squeeze the water out  
0:08:19.680,0:08:22.360
# 因为大家都知道大白菜水分比较多
As we all know, napa cabbage contains high portion of water 
0:08:22.820,0:08:26.680
# 如果是说不脱水的话包出来很多水就不好吃了
If we skip this step, the the dumpling skin will be soggy and untasted
0:08:27.380,0:08:28.980
# 四伯爷 你喜欢吃哪种馅儿安
Uncle, which dumpling stuffing do you like?
0:08:29.260,0:08:32.760
# 吃哪种馅 我看你整的个个馅我都喜欢吃
Which one? I like every flavor as far as it is made by you
0:08:32.960,0:08:33.600
# 是不哦
Is it?
0:08:33.600,0:08:34.180
# 是啊
Yes, it is 
0:08:34.980,0:08:37.580
# 你不喜欢吃啥子味道的馅嘛 你说
Tell me what flavor you don't like
0:08:39.020,0:08:42.900
# 那种甜的我就没得好喜欢吃的
I don't like eat sweet flavor dumplings that much
0:08:43.200,0:08:45.840
# 好了 现在这个白菜我随便抓两下
Ok, now I’ll squeeze the cabbage for a bit
0:08:45.840,0:08:47.660
# 这个水都已经出来了
The water has come out
0:08:52.960,0:08:54.140
# 先让它脱一下水
Let it be dehydrated for a while 
0:08:54.140,0:08:58.240
# 免得带到肉里面去 水分它会溢出来
in case the extra water comes into the meat
0:09:09.500,0:09:11.020
# 然后加点肉进去
and add some meat
0:09:11.020,0:09:14.400
# 肉的话根据你们自身家庭情况来放
you can control the quantity based on your own condition 
0:09:16.460,0:09:18.660
# 然后还是要调一点酱油
and some soy sauce
0:09:18.660,0:09:20.740
# 白菜其实是已经有盐的了
Napa cabbage is salted now
0:09:21.300,0:09:23.060
# 调了酱油以后再打一个 （鸡蛋）
after seasoning with soy sauce, crack an egg
0:09:23.380,0:09:24.900
# 这点肉打不了一个（鸡蛋）
the meat is not that much for using one egg
0:09:25.320,0:09:27.640
# 打半个鸡蛋就可以了
use half of egg
0:09:27.980,0:09:31.500
# 给它做的嫩一些 蛋清就行
to make it more tender, only add egg white 
0:09:31.860,0:09:33.580
# 同样的再加一点胡椒粉 然后给它拌匀
Same, add some pepper powder, mix it 
0:09:36.480,0:09:37.760
# 然后给它拌匀
Then mix it up finely 
0:09:40.680,0:09:42.740
# 好 现在我们来第五种
Now here is the fifth flavor of dumpling filling 
0:09:43.120,0:09:45.740
# 第五种的话就是香菇加肉
The fifth is “mushroom with pork”
0:09:45.740,0:09:49.820
# 这个是干香菇 泡发好的干香菇 加进去
0:09:49.820,0:09:53.860
# 然后这个是新鲜的香菇 相互配合
0:09:55.160,0:09:57.140
# 然后加点这个肉 肥肉
0:09:57.520,0:09:59.060
# 也不是肥肉 就是五花肉
It is nor pork fat, it’s pork belly 
0:10:00.180,0:10:01.420
# 加一点进去
Add some 
0:10:03.560,0:10:06.320
# 然后这个的话可以配一些胡萝卜配颜色
we could mix some carrots in it as well 
0:10:06.320,0:10:09.000
# 这个小孩子特别喜欢
Children like it very much
0:10:09.420,0:10:11.040
# 再加一点这个马蹄
Add more water chestnut dumplings 
0:10:11.400,0:10:14.460
# 马蹄吃起来口感脆脆的 很不错
Water chestnut texture is crunchy, very good
0:10:14.460,0:10:17.820
# 同样也是这些调料 盐

0:10:20.200,0:10:21.900
# 加点盐 加点酱油
Add some salt, add some soy sauce 
0:10:23.400,0:10:24.860
# 再加点胡椒粉
add some pepper powder 
0:10:25.940,0:10:29.860
# 这个因为它是自带肥油了 所以就不用再加油了
This one comes with pork fat, we don't need to add more oil 
0:10:30.080,0:10:31.920
# 好了 现在还有最后一种
Now we have the last one of dumpling stuffing 
0:10:31.920,0:10:33.560
# 最后一种就随意一点
The last flavor of filling could be more casual 
0:10:34.080,0:10:36.680
# 加点这个肉 把剩下的肉全部放进去
add some meat, put all the rest of meat in it 
0:10:36.960,0:10:40.720
# 然后这个 我们本地的韭黄放一些
We also put some local hotbed chives 
0:10:41.260,0:10:42.740
# 再放一些韭菜
Add more Chinese chives 
0:10:43.620,0:10:45.060
# 韭菜放进去香啊
Chinese chives are so fragrant 
0:10:45.380,0:10:46.380
# 多放点
Add bit more 
0:10:47.020,0:10:50.820
# 这个小葱 给它放一半的小葱
Put half of these spring onions 
0:10:51.520,0:10:54.340
# 然后这个马蹄再放一些进去
then add some water chestnuts
0:10:55.320,0:10:56.840
# 再放几颗胡萝卜
put some carrots 
0:10:58.720,0:11:00.100
# 然后再调一下味
seasoning 
0:11:01.500,0:11:02.460
# 盐
Salt
0:11:05.160,0:11:06.300
# 酱油
Soy sauce  
0:11:10.640,0:11:11.540
# 胡椒粉
Pepper powder
0:11:15.040,0:11:16.720
# 好 给它抓匀就行了
OK, just mix it finely 
0:11:18.660,0:11:20.720
# 这个可以根据你们个人口味来
it all depends on your personal preference 
0:11:20.720,0:11:22.880
# 有的他也加味精 鸡精
You could add MSG or chicken powder
0:11:22.880,0:11:24.780
# 但是我觉得没有这个必要
but I don't think that's necessary 
0:11:25.065,0:11:26.220
# 自己家里面吃的话
for homemade food
0:11:26.220,0:11:29.080
# 行了 你看 香得很
that's enough, See, it’s so aromatic 
0:11:29.560,0:11:30.560
# 你闻哈看嘛
Have a smell 
0:11:31.460,0:11:32.640
# 是不是 嗯
Does it smell good, Um
0:11:32.960,0:11:35.940
# 好了 现在我们这6个馅都已经和完了
Alright, now we have finished all these 6 different dumpling stuffing 
0:11:35.940,0:11:37.340
# 就是把它已经拌好了
They are all finely mixed
