### ISSUE TITLE
【美食作家王刚】年菜炸酥肉（排骨）- https://youtu.be/hzW13k526Us

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#554]
【美食作家王刚】年菜炸酥肉（排骨）- https://youtu.be/hzW13k526Us
视频时长 5:23，预计发布时间为北京时间1月7日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.380,0:00:02.480
首先我们来介绍原材料

0:00:02.480,0:00:04.380
第一种是最常见的五花肉

0:00:07.840,0:00:10.620
第二种是二刀肉俗称猪臀肉

0:00:10.620,0:00:13.660
它的特点是肥瘦分明嫩而不柴

0:00:13.660,0:00:16.440
跟五花肉对比二刀肉更胜一筹

0:00:16.920,0:00:18.560
第三种是猪大排

0:00:18.560,0:00:21.440
所谓大排就是整边排骨最中间的几根

0:00:21.440,0:00:24.100
用排骨制作的酥肉比二刀肉更香

0:00:24.100,0:00:25.800
但在性价比略低于二刀肉

0:00:25.800,0:00:26.880
下一步开始制作

0:00:26.880,0:00:30.140
首先我们在盆中加入适量的热水将排骨清洗干净

0:00:30.160,0:00:32.200
摊主为了猪肉有更好的卖相

0:00:32.200,0:00:35.075
一般从屠宰场到菜市场都不会进行清洗

0:00:35.075,0:00:37.780
在此建议大家买回的排骨先洗后剁

0:00:37.780,0:00:39.460
这样才更加的干净卫生

0:00:39.800,0:00:42.640
排骨清洗干净之后捞出改刀剁成小块备用

0:00:56.840,0:00:59.220
排骨剁好之后再次加入温水

0:01:01.720,0:01:03.960
加入一把干淀粉抓洗2分钟

0:01:03.960,0:01:06.400
这一步的目的是去除骨头中的淤血

0:01:06.400,0:01:08.860
有淤血的排骨炸好之后会发黑

0:01:08.880,0:01:10.880
所以建议大家按照此法操作

0:01:10.880,0:01:14.040
将排骨处理好之后捞出挤干水份下一步开始腌制

0:01:17.245,0:01:19.320
盆中加入一小块拍散的生姜

0:01:19.320,0:01:20.645
加入几根小葱

0:01:25.355,0:01:27.360
加入适量的食用盐调底味

0:01:27.360,0:01:28.600
加入少许胡椒粉

0:01:28.600,0:01:30.520
加入适量的料酒抓匀

0:01:37.180,0:01:40.000
加入少许花椒面之后腌制10分钟备用

0:01:40.000,0:01:42.320
不喜欢麻味的同学可以不加

0:01:43.800,0:01:45.360
下一步开始调糊

0:01:45.360,0:01:47.100
盆中加入适量的红薯淀粉（约400克）

0:01:48.500,0:01:49.920
加入面粉50克

0:01:52.000,0:01:54.020
加入适量的清水将其调散

0:02:05.900,0:02:08.620
调散之后准备鸡蛋4个打入盆中拌匀

0:02:20.920,0:02:24.320
鸡蛋拌匀之后再次加入适量的面粉拌匀防止过稀

0:02:28.160,0:02:31.660
调至面糊拉丝之后加入植物油40克搅拌均匀

0:02:31.915,0:02:35.195
加油的目的是让酥肉更加发泡不粘连

0:02:44.395,0:02:47.075
最后加入排骨裹上糊即可

0:02:49.535,0:02:51.020
下一步开始制作

0:02:51.020,0:02:52.565
首先我们把锅烧热

0:02:52.565,0:02:54.340
锅烧热之后加入宽油

0:02:54.340,0:02:56.820
炸酥肉的情况下油越多越好

0:02:56.820,0:02:58.920
这样才能保证均匀受热

0:03:06.360,0:03:09.560
油温6成热之后将上好糊的排骨依次下入锅中

0:03:27.820,0:03:29.960
然后转中火将排骨炸至熟透

0:03:39.000,0:03:41.420
中途需要将锅边的细渣捞出不用

0:03:56.160,0:03:58.220
排骨炸至熟透之后捞出

0:04:05.280,0:04:07.580
然后用细漏将残渣去除

0:04:07.580,0:04:10.000
这一步的目的是保证宽油没有糊味

0:04:20.900,0:04:24.220
然后待油温升起之后将排骨下锅复炸1分钟

0:04:37.660,0:04:40.300
将排骨炸至金黄酥脆之后即可捞出

0:04:53.780,0:04:56.280
一道农村宴席酥排骨就制作完成

0:04:59.000,0:05:00.640
下面开始技术总结

0:05:00.640,0:05:06.060
第一，原材料可选择五花肉，二刀肉，猪排骨，其中排骨最香

0:05:06.120,0:05:10.920
第二，挂糊最好用红薯淀粉和面粉搭配，这样味道更香脆

0:05:10.920,0:05:16.040
第三，酥排骨可撒上椒盐粉或者直接食用，又或者可以蒸煮

0:05:16.080,0:05:20.300
第四，炸排骨的宽油必须去除残留的细渣否则油会串味

0:05:20.300,0:05:22.200
酥排骨的技术总结完毕

**Comment by immoonancient** [comment]
这个我自己顶上吧...

**Comment by immoonancient** [comment]
bot, please upload

0:00:00.380,0:00:02.480
首先我们来介绍原材料
First, let's introduce the ingredients

0:00:02.480,0:00:04.380
第一种是最常见的五花肉
The first type is regular pork belly

0:00:07.840,0:00:10.620
第二种是二刀肉俗称猪臀肉
The second type is "Er Dao Rou" ("second cut pork"), aka pork ham

0:00:10.620,0:00:13.660
它的特点是肥瘦分明嫩而不柴
The fat and lean parts interleave each other, making it tender but not dry

0:00:13.660,0:00:16.440
跟五花肉对比二刀肉更胜一筹
Compared to pork belly, "Er Dao Rou" is a better choice

0:00:16.920,0:00:18.560
第三种是猪大排
The third type is "Da Pai" pork ribs

0:00:18.560,0:00:21.440
所谓大排就是整边排骨最中间的几根
which are the middle bones of the rib cage

0:00:21.440,0:00:24.100
用排骨制作的酥肉比二刀肉更香
Deep fried pork ribs are even more flavorful than "Er Dao Rou"

0:00:24.100,0:00:25.800
但在性价比略低于二刀肉
However, they are less cost efficient

0:00:25.800,0:00:26.880
下一步开始制作
Next, let's start processing

0:00:26.880,0:00:30.140
首先我们在盆中加入适量的热水将排骨清洗干净
First, clean up the ribs in warm water

0:00:30.160,0:00:32.200
摊主为了猪肉有更好的卖相
Most pork sellers do not clean up pork in advance

0:00:32.200,0:00:35.075
一般从屠宰场到菜市场都不会进行清洗
so that the pork has a better presence after slaughtering

0:00:35.075,0:00:37.780
在此建议大家买回的排骨先洗后剁
Therefore, it's recommended to clean up the pork ribs before chopping

0:00:37.780,0:00:39.460
这样才更加的干净卫生
which is a more hygienic practice

0:00:39.800,0:00:42.640
排骨清洗干净之后捞出改刀剁成小块备用
After cleaning, chop the ribs into small pieces

0:00:56.840,0:00:59.220
排骨剁好之后再次加入温水
Then add in some warm water again

0:01:01.720,0:01:03.960
加入一把干淀粉抓洗2分钟
Add some starch and wash it for 2 minutes

0:01:03.960,0:01:06.400
这一步的目的是去除骨头中的淤血
This is for removing the remaining blood from the ribs

0:01:06.400,0:01:08.860
有淤血的排骨炸好之后会发黑
Otherwise, the ribs may appear dark after deep frying

0:01:08.880,0:01:10.880
所以建议大家按照此法操作
So we recommend this method

0:01:10.880,0:01:14.040
将排骨处理好之后捞出挤干水份下一步开始腌制
After that, take out the rib and squeeze out the water
Next, marination

0:01:17.245,0:01:19.320
盆中加入一小块拍散的生姜
Add a piece of crushed ginger

0:01:19.320,0:01:20.645
加入几根小葱
Add some green onions

0:01:25.355,0:01:27.360
加入适量的食用盐调底味
Add some salt as the base seasoning

0:01:27.360,0:01:28.600
加入少许胡椒粉
Add some pepper powder

0:01:28.600,0:01:30.520
加入适量的料酒抓匀
Add some Chinese cooking wine, and mix it well

0:01:37.180,0:01:40.000
加入少许花椒面之后腌制10分钟备用
Add some Sichuan pepper powder, and then marinate for 10 minutes

0:01:40.000,0:01:42.320
不喜欢麻味的同学可以不加
You may skip it if you don't prefer the numbing flavor

0:01:43.800,0:01:45.360
下一步开始调糊
Next, make the frying batter

0:01:45.360,0:01:47.100
盆中加入适量的红薯淀粉（约400克）
Add a moderate amount of sweet potato starch (~400g)

0:01:48.500,0:01:49.920
加入面粉50克
Add 50g of flour

0:01:52.000,0:01:54.020
加入适量的清水将其调散
Add a moderate amount of water to mix it well

0:02:05.900,0:02:08.620
调散之后准备鸡蛋4个打入盆中拌匀
Then add in 4 eggs and mix it well

0:02:20.920,0:02:24.320
鸡蛋拌匀之后再次加入适量的面粉拌匀防止过稀
Then mix in some flour again to avoid it being too watery

0:02:28.160,0:02:31.660
调至面糊拉丝之后加入植物油40克搅拌均匀
When soft peaks can be formed, mix in 40g of vegetable oil

0:02:31.915,0:02:35.195
加油的目的是让酥肉更加发泡不粘连
This makes the deep fried ribs more puffy, and also avoids sticking

0:02:44.395,0:02:47.075
最后加入排骨裹上糊即可
Finally, coat the ribs with the batter

0:02:49.535,0:02:51.020
下一步开始制作
Next, cooking

0:02:51.020,0:02:52.565
首先我们把锅烧热
First, heat up the wok

0:02:52.565,0:02:54.340
锅烧热之后加入宽油
After that, add in "Kuan You" ("broad oil")

0:02:54.340,0:02:56.820
炸酥肉的情况下油越多越好
For deep fried pork, we should use as much frying oil as possible

0:02:56.820,0:02:58.920
这样才能保证均匀受热
to ensure that the pork is heated evenly

0:03:06.360,0:03:09.560
油温6成热之后将上好糊的排骨依次下入锅中
After reaching ~180°C oil temperature, add in the pork ribs successively

0:03:27.820,0:03:29.960
然后转中火将排骨炸至熟透
Turn to medium fire to thoroughly cook to ribs

0:03:39.000,0:03:41.420
中途需要将锅边的细渣捞出不用
Make sure to remove the floating scums during the process

0:03:56.160,0:03:58.220
排骨炸至熟透之后捞出
Take out the ribs after thoroughly cooked

0:04:05.280,0:04:07.580
然后用细漏将残渣去除
After that, remove all the residues with a fine strainer

0:04:07.580,0:04:10.000
这一步的目的是保证宽油没有糊味
so that there is no burned taste in the "Kuan You"

0:04:20.900,0:04:24.220
然后待油温升起之后将排骨下锅复炸1分钟
Reheat the oil, and then re-fry the ribs for one minute

0:04:37.660,0:04:40.300
将排骨炸至金黄酥脆之后即可捞出
Take them out after they have turned golden yellow and crispy

0:04:53.780,0:04:56.280
一道农村宴席酥排骨就制作完成
A countryside banquet dish "Su Paigu" (deep fried pork ribs) is now complete!

0:04:59.000,0:05:00.640
下面开始技术总结
Next, technical summary

0:05:00.640,0:05:06.060
第一，原材料可选择五花肉，二刀肉，猪排骨，其中排骨最香
1. We can use pork belly, "Er Dao Rou" pork ham or pork ribs for this dish. Ribs are the best

0:05:06.120,0:05:10.920
第二，挂糊最好用红薯淀粉和面粉搭配，这样味道更香脆
2. It is recommended to use sweet potato starch and four in combination to make the frying batter, so that it's more flavorful and crispy

0:05:10.920,0:05:16.040
第三，酥排骨可撒上椒盐粉或者直接食用，又或者可以蒸煮
3. The deep fried ribs can be consumed either directly with salt and pepper powder, or after steaming or stewing

0:05:16.080,0:05:20.300
第四，炸排骨的宽油必须去除残留的细渣否则油会串味
4. Before frying the ribs, make sure to remove all residues from the frying oil. Otherwise there might be other unpleasant tastes

0:05:20.300,0:05:22.200
酥排骨的技术总结完毕
That's all for the technical summary
