### ISSUE TITLE
【美食作家王刚】年菜红烧鲤鱼 - https://youtu.be/cHXO5befcUI

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#555]
【美食作家王刚】年菜红烧鲤鱼 - https://youtu.be/cHXO5befcUI
视频时长 4:39，预计发布时间为北京时间1月8日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.000,0:00:01.980
首先我们准备鲤鱼1条（约900克）

0:00:01.980,0:00:05.120
将鱼敲晕之后去除鱼鳞和内脏清洗干净备用

0:00:05.120,0:00:08.160
同学们处理鱼的时候最好能将里面的牙齿去除

0:00:08.160,0:00:09.960
这样能减少腥味

0:00:19.860,0:00:21.540
下一步开始改刀

0:00:21.540,0:00:23.780
首先在鱼身斜刀切三刀

0:00:23.780,0:00:25.640
然后反过来对切三刀

0:00:27.260,0:00:29.080
然后再反过来对切三刀

0:00:29.080,0:00:31.100
同学们切记不能把鱼边切开

0:00:31.100,0:00:33.460
否则在煎的时候鱼身容易烂

0:00:34.460,0:00:36.440
下一步开始准备辅料

0:00:36.440,0:00:38.600
准备五花肉一小块切成小粒备用

0:00:38.660,0:00:41.020
加五花肉的目的是增加成菜的香味

0:00:41.020,0:00:42.860
也可以直接用猪肉代替

0:00:45.720,0:00:47.760
准备香菇3个切成小粒备用

0:00:47.760,0:00:50.240
香菇可以代替味精提升鱼的鲜味

0:00:56.180,0:00:58.540
准备生姜1小块切成姜粒备用

0:01:00.660,0:01:03.580
准备大蒜几颗切成小粒备用

0:01:05.275,0:01:07.835
最后准备几根小葱白切成小粒备用

0:01:08.440,0:01:09.920
下一步开始制作

0:01:10.140,0:01:11.740
首先我们把锅烧热

0:01:11.740,0:01:14.320
锅烧热之后加入适量的底油烧至5成热

0:01:17.100,0:01:18.840
油热之后加入食用盐1勺（约2克）

0:01:24.240,0:01:26.620
然后将鲤鱼下锅开中小火煎5分钟

0:01:26.620,0:01:29.340
这一步的目的是将鲤鱼两面煎香煎黄

0:01:33.260,0:01:35.660
然后中途将其翻面过来继续煎香

0:01:35.660,0:01:38.120
同学们加盐在油中煎鱼可以防止粘锅

0:01:42.360,0:01:44.380
5分钟之后将鲤鱼倒出备用

0:01:46.780,0:01:49.340
锅中再次加入少许底油烧热

0:01:50.700,0:01:53.800
油热之后加入切好的五花肉爆香爆出猪油

0:02:03.540,0:02:06.220
猪肉爆香之后加入切好的姜蒜粒爆香

0:02:06.220,0:02:08.860
同学们猪肉粒必须炒至金黄出油才算香

0:02:19.480,0:02:22.040
姜蒜粒炒香之后加入切好的香菇和葱粒

0:02:33.100,0:02:34.980
翻炒均匀之后开始调汁

0:02:35.440,0:02:36.980
锅中加入蚝油10克

0:02:38.520,0:02:40.720
加入生抽酱油6克从锅边淋入

0:02:45.600,0:02:47.140
然后加入啤酒1瓶（500毫升）

0:02:54.260,0:02:56.540
大火烧开之后加入食用盐1勺（约1.5克）

0:02:58.680,0:03:00.220
加入胡椒粉少许

0:03:01.080,0:03:02.960
加入少许的白糖提鲜

0:03:03.640,0:03:04.860
加入半勺五香粉

0:03:06.880,0:03:08.620
加入糖色4克调色

0:03:08.660,0:03:10.900
没有糖色的同学可以用老抽代替

0:03:12.560,0:03:14.500
然后将鲤鱼下锅烧6分钟

0:03:18.080,0:03:21.040
中途只需要把汤汁淋在鱼身即可

0:03:21.040,0:03:22.220
无需翻动鲤鱼

0:03:26.180,0:03:28.180
6分钟之后将鲤鱼捞出摆盘

0:03:43.300,0:03:45.160
然后将剩余的汤汁烧开

0:03:48.360,0:03:51.220
汤汁烧开之后加入适量的水淀粉收汁

0:03:56.840,0:03:59.960
最后再加入少许明油拌匀淋在鱼身即可

0:04:14.260,0:04:17.480
一道非常美味的年菜红烧鲤鱼就制作完成

0:04:18.660,0:04:19.920
下面开始技术总结

0:04:19.920,0:04:24.100
第一，此法适用于大部分鱼类，最好是刺越少越好

0:04:24.100,0:04:28.140
第二，此法烹饪的口味较为清淡适合老人孩子食用

0:04:28.140,0:04:31.400
第三，喜欢重口味的同学请看下期川菜版本

0:04:31.400,0:04:33.080
红烧鲤鱼的技术总结完毕（不辣版本 ）

**Comment by 3yearsyoung** [comment]
bot, please upload, 
年菜红烧鲤鱼
Lunar New Year’s Dish: Braised Carp

如果想支持我或想看更多多幕后周边和我的生活私照的朋友们可以考虑加入”宽油帮“油管会员，点击订阅按钮旁的加入按钮会弹出详情，会员福利如下：
If you’d like to support me or crave for more backstage features and my personal photos, consider joining my YouTube membership “Kuan You Bang”. Just click on the “Join” button next to “Subscribe” and follow the prompts on the pop-up window. Members’ benefits are as follows: 
1. 拥有“宽油帮”成长徽章
Obtain “Kuan You Bang” badge which can level up over time
2. “宽油”社区动态，独家生活私照和生活分享
“Kuan You” Community feed, my exclusive personal photos and life story sharing
3. 拥有更多留言被回复的机会
Having more chances of getting your comments replied
名词解释：
Terminologies:
宽油：大量的油，很多的油
Kuanyou: A large amount of oil
滑锅：冷油下锅，滑过锅底，使锅的温度迅速提高，并产生油膜，防止粘锅
Huaguo: Pour cold oil into the wok which can significantly increase the wok temperature and produce the oil isolation to prevent food from sticking to the wok
明油：成菜之后淋入一点点葱油，来提高菜品的色泽与明亮度，葱油制作链接
Mingyou: Drizzle with a touch of spring onion infused oil when the dish is done to brighten up the dish. To know how to make the spring onion infused oil, please click the link below:
https://www.youtube.com/watch?v=K1iUmWhezjA
刀口辣椒：干辣椒干花椒炒香炒脆后，手工切碎即为刀口辣椒，香辣麻三位一体，辣度温和，制作链接 
Daokoulajiao: Sauté the dried chilies and Sichuan peppercorns until fragrant and crispy, then crush them by knife. Daokoulajiao is the holy trinity of fragrance, spiciness and numbness, and it’s mild in spiciness. Click on the link below to see how it is made:
https://www.youtube.com/watch?v=USoC8AqirVA

我是王刚，一个草根厨师长，从15岁做学徒到30岁开始在网上教大家做菜，我感恩每一段经历，感恩这个时代，也真心希望通过我的视频可以帮到大家，让大家走进厨房，爱上厨房。我会坚持做菜，坚持教大家做菜。也希望大家来订阅我的YouTube官方频道，欢迎大家点赞、分享和评论。在西瓜视频，头条和微博上也有我相同名字的账户“美食作家王刚”，微信公众号为“厨王刚丝球”，谢谢大家支持！
I’m Wang Gang, a working-class chef. I started my career as an apprentice since 15 and began to teach others how to cook at the age of 30. I feel so grateful for every single experience as well as this golden age. I genuinely hope by watching my videos, you can be motivated to walk into the kitchen and fall in love with the kitchen. I will keep cooking and keep teaching you guys how to cook. In the meantime, please subscribe my YouTube channel, and feel free to thumb up, share and leave comments. Alternatively, you may also find my channels on Xi Gua Video, Tou Tiao and Weibo with the identical name. My WeChat channel is called “Chu Wang Gang Si Qiu”, and I appreciate all your support!

0:00:00.000,0:00:01.980
首先我们准备鲤鱼1条（约900克）
Firstly, let’s prepare the carp (about 900g)

0:00:01.980,0:00:05.120
将鱼敲晕之后去除鱼鳞和内脏清洗干净备用
Stun the fish, and remove its scales and guts, then rinse it for later use

0:00:05.120,0:00:08.160
同学们处理鱼的时候最好能将里面的牙齿去除
It’s better to remove its teeth inside as well when preparing

0:00:08.160,0:00:09.960
这样能减少腥味
Which can reduce the fishy smell

0:00:19.860,0:00:21.540
下一步开始改刀
Next, score the fish

0:00:21.540,0:00:23.780
首先在鱼身斜刀切三刀
Make three slant cuts on one side of the carp

0:00:23.780,0:00:25.640
然后反过来对切三刀
Turn it around, and make three more cuts

0:00:27.260,0:00:29.080
然后再反过来对切三刀
Then flip over the fish and repeat the process

0:00:29.080,0:00:31.100
同学们切记不能把鱼边切开
Remember not to cut the edge of the fish

0:00:31.100,0:00:33.460
否则在煎的时候鱼身容易烂
Otherwise the carp could easily break down when we pan fry it later

0:00:34.460,0:00:36.440
下一步开始准备辅料
Next, let’s prepare the other ingredients

0:00:36.440,0:00:38.600
准备五花肉一小块切成小粒备用
Get a small piece of pork belly and dice it into small cubes

0:00:38.660,0:00:41.020
加五花肉的目的是增加成菜的香味
The purpose of adding pork belly is to lift the fragrance of the dish

0:00:41.020,0:00:42.860
也可以直接用猪肉代替
You can also just use some lard instead

0:00:45.720,0:00:47.760
准备香菇3个切成小粒备用
Dice three shiitake mushrooms

0:00:47.760,0:00:50.240
香菇可以代替味精提升鱼的鲜味
They can replace MSG to increase the umami taste of the fish

0:00:56.180,0:00:58.540
准备生姜1小块切成姜粒备用
Then dice a small piece of ginger

0:01:00.660,0:01:03.580
准备大蒜几颗切成小粒备用
A few cloves of garlic

0:01:05.275,0:01:07.835
最后准备几根小葱白切成小粒备用
And lastly some white parts of scallions

0:01:08.440,0:01:09.920
下一步开始制作
Now, let’s cook

0:01:10.140,0:01:11.740
首先我们把锅烧热
Firstly, heat up the wok

0:01:11.740,0:01:14.320
锅烧热之后加入适量的底油烧至5成热
Once the wok is hot, add in some base oil and heat it up to 50% hot (150 degrees centigrade)

0:01:17.100,0:01:18.840
油热之后加入食用盐1勺（约2克）
Add one teaspoon of salt (2g) into the hot oil

0:01:24.240,0:01:26.620
然后将鲤鱼下锅开中小火煎5分钟
Then put it the carp and pan fry it for 5 minutes with medium-low heat

0:01:26.620,0:01:29.340
这一步的目的是将鲤鱼两面煎香煎黄
This allows both sides of the fish to be golden and fragrant

0:01:33.260,0:01:35.660
然后中途将其翻面过来继续煎香
Halfway through, flip the carp over, and continue frying

0:01:35.660,0:01:38.120
同学们加盐在油中煎鱼可以防止粘锅
The salt added into the oil can prevent the fish from sticking to the wok

0:01:42.360,0:01:44.380
5分钟之后将鲤鱼倒出备用
After 5 minutes, remove the carp from the wok and leave it to rest

0:01:46.780,0:01:49.340
锅中再次加入少许底油烧热
Next, add in small amount of base oil and heat it up again

0:01:50.700,0:01:53.800
油热之后加入切好的五花肉爆香爆出猪油
Then fry the diced pork belly, and bring out the aroma and fat

0:02:03.540,0:02:06.220
猪肉爆香之后加入切好的姜蒜粒爆香
After that, add in the diced ginger and garlic and stir fry until aromatic

0:02:06.220,0:02:08.860
同学们猪肉粒必须炒至金黄出油才算香
The pork belly cubes must be fried until golden and its fat released

0:02:19.480,0:02:22.040
姜蒜粒炒香之后加入切好的香菇和葱粒
Once ginger and garlic are fragrant, add in the diced shiitake mushrooms and scallions 

0:02:33.100,0:02:34.980
翻炒均匀之后开始调汁
Stir fry them evenly, and then season the sauce

0:02:35.440,0:02:36.980
锅中加入蚝油10克
Add in 10g of oyster sauce

0:02:38.520,0:02:40.720
加入生抽酱油6克从锅边淋入
Drizzle in 6g of light soy sauce from the edge of the wok

0:02:45.600,0:02:47.140
然后加入啤酒1瓶（500毫升）
Then pour in a bottle of beer (500ml)

0:02:54.260,0:02:56.540
大火烧开之后加入食用盐1勺（约1.5克）
After the sauce is boiled with high heat, add in a teaspoon of salt (1.5g)

0:02:58.680,0:03:00.220
加入胡椒粉少许
A small amount of ground pepper

0:03:01.080,0:03:02.960
加入少许的白糖提鲜
Some sugar to lift the umami

0:03:03.640,0:03:04.860
加入半勺五香粉
Half a teaspoon of five spices

0:03:06.880,0:03:08.620
加入糖色4克调色
And 4g of caramel

0:03:08.660,0:03:10.900
没有糖色的同学可以用老抽代替
Alternatively, you can use dark soy sauce if you don’t have caramel

0:03:12.560,0:03:14.500
然后将鲤鱼下锅烧6分钟
Next, add back the carp to braise for 6 minutes

0:03:18.080,0:03:21.040
中途只需要把汤汁淋在鱼身即可
Baste the fish with the sauce while braising

0:03:21.040,0:03:22.220
无需翻动鲤鱼
You don’t need to flip it over

0:03:26.180,0:03:28.180
6分钟之后将鲤鱼捞出摆盘
After 6 minutes, take the carp out of the wok for plating

0:03:43.300,0:03:45.160
然后将剩余的汤汁烧开
Then, boil the remaining sauce

0:03:48.360,0:03:51.220
汤汁烧开之后加入适量的水淀粉收汁
Once boiled, add in some water starch and reduce the sauce down

0:03:56.840,0:03:59.960
最后再加入少许明油拌匀淋在鱼身即可
Lastly, stir in a small amount of Mingyou and pour the sauce over the fish

0:04:14.260,0:04:17.480
一道非常美味的年菜红烧鲤鱼就制作完成
A delicious braised carp suitable for the Lunar New Year is now served

0:04:18.660,0:04:19.920
下面开始技术总结
Let’s move on to the technical review:

0:04:19.920,0:04:24.100
第一，此法适用于大部分鱼类，最好是刺越少越好
Firstly, most types of fish can be used for this dish, but you’d better choose those with fewer fishbones

0:04:24.100,0:04:28.140
第二，此法烹饪的口味较为清淡适合老人孩子食用
Secondly, this dish is rather mild and good for elder people and young kids

0:04:28.140,0:04:31.400
第三，喜欢重口味的同学请看下期川菜版本
Thirdly, if you like heavier taste, please watch my next video where I will be making a Sichuan version of it

0:04:31.400,0:04:33.080
红烧鲤鱼的技术总结完毕（不辣版本 ）
That’s all for the technical review of the braised carp (non-spicy version)

**Comment by immoonancient** [comment]
已发布
