### ISSUE TITLE
【美食作家王刚】鱼丸火锅 - https://youtu.be/T6_qExnAPKA

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#583]
【美食作家王刚】鱼丸火锅 - https://youtu.be/T6_qExnAPKA
视频时长 10:16，预计发布时间为北京时间1月17日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.656,0:00:01.357
哈喽大家好

0:00:01.466,0:00:03.525
最近天气冷了 也快过年了

0:00:03.686,0:00:06.694
所以今天准备跟大家分享做一个鱼丸火锅

0:00:07.034,0:00:09.968
鱼丸火锅的话 除了喝汤之外还可以烫菜

0:00:10.277,0:00:12.054
这条鱼来的也很不容易

0:00:12.938,0:00:13.770
是漆二娃弄的是不哦 

0:00:13.886,0:00:16.820
是漆二娃弄的 她去罩还摔了一跟头

0:00:17.184,0:00:17.972
滚得田头去了是不哦

0:00:17.977,0:00:18.915
滚得田头去了

0:00:18.997,0:00:21.266
爬起来冷的她打腮壳儿（打抖抖）

0:00:22.487,0:00:24.145
这条鱼来的非常不容易

0:00:24.446,0:00:25.576
好 现在开始弄

0:00:31.161,0:00:32.182
这条鱼还多大哦

0:00:32.209,0:00:36.482
这条是田头的鱼 田头的鱼要好干（吃）点哦 野生鱼哦

0:00:36.692,0:00:37.977
可能有四斤多噶

0:00:38.168,0:00:38.878
嗯

0:00:44.710,0:00:46.851
先我们把这个肉给它剔下来

0:00:56.692,0:00:59.507
这种尾巴一起给它砍下来

0:01:04.136,0:01:07.507
这里就相当于猪的肋排

0:01:09.634,0:01:12.454
慢慢一刀一刀的往底下割

0:01:12.819,0:01:15.882
割得差不多了之后 这里就立着给它割 

0:01:18.681,0:01:19.087
是不是

0:01:19.208,0:01:19.675
嗯

0:01:23.387,0:01:23.732
好 

0:01:24.401,0:01:26.348
  从中间斜刀切下去

0:01:26.977,0:01:32.332
不要切断 这边就慢慢的来

0:01:37.931,0:01:41.541
左右移 左右移一下子就去下来了

0:01:41.642,0:01:46.186
然后再把表面这个红的肉去一点

0:01:47.302,0:01:52.373
红色这个肉去下来做成鱼丸更白 颜色更好看

0:01:53.265,0:01:55.152
然后也减少一些腥味

0:02:03.306,0:02:06.937
好了 现在我们这个鱼红色的（肉）已经去掉了一部分

0:02:07.829,0:02:10.993
然后就开始处理 把它切成小块

0:02:13.732,0:02:16.551
切成小块加水洗 多洗几次

0:02:17.363,0:02:21.176
好 现在加点水把这个鱼片多洗几次

0:02:24.421,0:02:28.032
这个鱼要洗干净 你看 这一洗水都浑了

0:02:28.235,0:02:29.533
就是这个（鱼）的血

0:02:30.791,0:02:32.515
把它的血水洗干净

0:02:32.576,0:02:33.853
放到这个里面再洗一次

0:02:36.815,0:02:39.148
好 洗好了下一步就开始腌制了

0:02:43.569,0:02:47.221
准备一块姜 再准备一些葱

0:02:47.748,0:02:49.695
这个姜的话先提前切一下

0:02:53.529,0:02:54.908
四伯爷你晓得这个是啥子不

0:02:55.659,0:02:57.119
搅拌机 搅鱼的

0:02:57.410,0:02:59.290
嗯 你咋子浪聪明安

0:03:00.121,0:03:03.833
看这个形式都像那个工具

0:03:03.995,0:03:06.470
我们用这个葱 再少一点 不用那么多

0:03:07.342,0:03:10.851
这个葱挽一下捏成一团

0:03:10.993,0:03:14.624
把这个放进去 姜葱一起放进去

0:03:14.908,0:03:16.389
然后再加点水

0:03:17.180,0:03:19.168
加大概2、3两水

0:03:19.574,0:03:21.237
盖起来把这个打成姜葱汁

0:03:28.498,0:03:29.330
这个很快当

0:03:29.776,0:03:31.906
然后用这个姜葱汁来腌这个鱼

0:03:33.813,0:03:36.511
全部倒进去都可以 多就多一点吧

0:03:39.634,0:03:43.620
其实很多人它做这个鱼丸做出来腥味重啊

0:03:45.415,0:03:46.673
这一步特别重要 

0:03:47.870,0:03:48.803
这一步很重要

0:03:49.066,0:03:52.961
让它泡十分钟 姜葱进香味然后又去腥味

0:03:56.511,0:03:58.458
好了 我们这个腌了十多分钟了

0:03:58.478,0:04:01.947
现在把这个鱼给它捡出来稍微洗一下

0:04:02.880,0:04:03.711
把它洗一下

0:04:05.253,0:04:07.971
 就像这样就可以了 把它丢进去

0:04:08.762,0:04:13.136
如果对这个颜色品质要求高的 可以多清洗几次

0:04:13.569,0:04:15.699
把这个绿色的东西全部洗干净

0:04:16.713,0:04:20.020
好 我们现在加点冰水 这个水一定要够冰

0:04:20.486,0:04:28.133
就是防止它高速转动得时候 温度过高破坏鱼的弹性

0:04:50.223,0:04:51.217
好 可以了

0:04:52.210,0:04:54.056
我们这个现在效率很高

0:04:54.056,0:04:57.099
用这个东西的话比你用刀剁快

0:04:57.505,0:05:00.243
用这个最多就搅个两三分钟

0:05:00.304,0:05:04.178
用刀要剁四十分钟 特别的浪费时间

0:05:04.320,0:05:05.618
所以我选择用这个

0:05:05.740,0:05:07.383
诶呀 搅得好融

0:05:08.154,0:05:09.472
我们直接加这个蛋清

0:05:11.480,0:05:12.352
直接加蛋清

0:05:13.853,0:05:15.984
 蛋清的话就根据自己家的条件来

0:05:16.085,0:05:19.675
加一个也行 加三四个也行 我今天准备加四个

0:05:20.121,0:05:24.158
这个蛋黄先放这边 蛋黄等会儿还可以拿来炒个菜噶

0:05:30.243,0:05:33.285
好 现在先把它和转（匀）

0:05:35.841,0:05:38.722
今天我准备做一个弹牙弹的厉害一点的

0:05:38.782,0:05:40.811
所以水加得比较少

0:05:44.827,0:05:46.348
先加个3、4克盐

0:05:48.336,0:05:51.582
盐少量多次加 不要一次加够了

0:05:52.981,0:05:54.482
像这样搅十分钟

0:05:58.985,0:05:59.736
可以了

0:06:01.480,0:06:02.900
刚刚滴下来的这个不算

0:06:03.285,0:06:05.659
看嘛 这个能够坚持到十秒钟 可以了

0:06:08.316,0:06:10.223
定住了 看都没 

0:06:11.156,0:06:15.334
像这样就行了 在手上面十秒钟不掉就行了

0:06:16.206,0:06:19.127
现在开始挤丸子了

0:06:19.553,0:06:23.083
我们这个丸子成功与否 就看它看下水能不能飘起来

0:06:24.016,0:06:27.363
还要准备油 润一下勺子 不至于粘得太厉害

0:06:27.829,0:06:29.168
好 准备挤丸子

0:06:30.608,0:06:33.427
挤小一点 因为待会儿丸子它还会发胀

0:06:33.590,0:06:35.010
诶 它咋子不沉安

0:06:35.131,0:06:35.943
飘起了撒

0:06:36.693,0:06:40.101
就说明空气就打进去了撒

0:06:40.385,0:06:41.054
就要得了噶

0:06:41.156,0:06:42.008
对 就要得了

0:06:42.981,0:06:44.726
好 挤第三个

0:06:46.678,0:06:48.600
嘿嘿 狗东西还奇怪

0:06:50.060,0:06:50.770
第四个

0:06:51.987,0:06:53.995
手都要拷（搅拌）偻（酸）我给你说

0:06:53.995,0:06:56.105
你没拷过的人拷的话

0:06:58.884,0:07:00.933
这是哪个的发明安

0:07:01.480,0:07:03.711
属于我们中国人的发明撒

0:07:05.050,0:07:07.383
你要晓得我们饮食的几千年的文化了

0:07:08.072,0:07:10.405
没得点功夫咋可能安

0:07:10.953,0:07:12.981
好 现在开始准备制作了

0:07:13.914,0:07:15.780
把这个锅烧热了先加点油

0:07:15.902,0:07:17.849
这回不用你的宽油了四伯爷

0:07:18.438,0:07:21.642
哎呀 随便用啥子油都要得

0:07:22.657,0:07:23.346
少放点

0:07:23.590,0:07:25.780
还分你的我的 你都是我的安

0:07:27.342,0:07:28.214
是 嘿嘿

0:07:37.180,0:07:41.500
我们先把这个油烧热了之后放点盐在锅底里面

0:07:41.987,0:07:47.789
待会儿煎鱼骨头的时候才不至于说太腥或者是说煎得太烂

0:07:51.845,0:07:54.482
好 这个油烧热了 鱼放下去煎

0:07:56.754,0:07:58.752
煎鱼头的时候加点这个姜 

0:08:01.602,0:08:03.975
那个葱待会儿我们煮的时候再放

0:08:06.024,0:08:07.809
好 慢慢的给它煎

0:08:08.539,0:08:12.312
好 这个我们煎下面一层就可以了 把它煎香煎黄

0:08:12.352,0:08:13.488
加点这个开水来煮

0:08:14.401,0:08:16.997
四伯爷这个火要烧大点哦

0:08:17.261,0:08:19.594
好好好 加大火力

0:08:20.567,0:08:23.285
好 现在就等着这个鱼汤熬出来

0:08:25.374,0:08:28.510
现在这个水开了 但是要把浮沫打（去）一下

0:08:30.202,0:08:32.636
打完浮沫加点葱下去一起煮

0:08:36.571,0:08:39.687
好了 我们这个汤都熬白了 现在把这个葱拿出来

0:08:40.202,0:08:42.314
拿出来了之后就准备下鱼丸了

0:08:42.406,0:08:43.914
下鱼丸之前先调味

0:08:44.259,0:08:47.355
要不然等一下再放盐下去搅一下就会把鱼丸搅烂了

0:08:48.122,0:08:49.274
放点盐调底味

0:08:50.375,0:08:52.103
四伯爷你端着我来漏（捞）

0:08:54.914,0:08:56.774
火的话就可以烧小点的

0:08:57.423,0:08:59.948
轻轻地漏起来 再轻轻地放下去

0:09:02.184,0:09:04.846
吃好多煮好多 边吃边煮

0:09:06.348,0:09:07.457
好 这个差不多了

0:09:07.508,0:09:09.573
我先盛点出来给我伯爷尝一下

0:09:09.829,0:09:11.297
鱼丸下锅煮了十分钟左右

0:09:11.638,0:09:12.866
因为这次的比较小

0:09:13.583,0:09:16.399
所以的话时间就比较快一点

0:09:17.337,0:09:18.600
熟肯定是熟了

0:09:20.989,0:09:22.013
熟了的 完全熟了的

0:09:22.030,0:09:25.900
这是你精心制作的东西

0:09:28.924,0:09:31.480
嗯 安逸

0:09:31.552,0:09:34.044
适合老人吃噶 适合牙口不好的

0:09:34.112,0:09:38.054
好干（吃） 跟豆腐脑一样 一抿就烂了

0:09:38.157,0:09:38.498
是不哦

0:09:38.600,0:09:38.959
是啊

0:09:39.198,0:09:40.204
我再拿个碗装点

0:09:40.972,0:09:42.457
伯娘过来吃

0:09:44.590,0:09:45.375
很耙噶

0:09:46.041,0:09:47.064
好嫩气哦

0:09:47.747,0:09:49.385
嗯 跟豆腐一样

0:09:49.624,0:09:49.965
是安

0:09:53.532,0:09:56.390
这个特别适合牙口不好的 还有小孩子

0:09:56.416,0:09:59.232
因为它这个鱼刺已经打得非常碎了

0:10:00.204,0:10:01.450
看嘛 好安逸嘛

0:10:01.570,0:10:02.713
伯娘可以多吃一点

0:10:04.146,0:10:10.238
啥子都没加 就只加了盐巴加了姜葱加了点蛋清

0:10:10.648,0:10:12.730
好 本期视频就到这里了 拜拜

0:10:13.447,0:10:14.402
你慢慢吃

**Comment by riana33** [comment]
认领

**Comment by riana33** [comment]
bot, please upload
0:00:00.656,0:00:01.357
# 哈喽大家好
Hello everyone
0:00:01.466,0:00:03.525
# 最近天气冷了 也快过年了
Recently, the weather is getting cold, and it’s close to lunar new year
0:00:03.686,0:00:06.694
# 所以今天准备跟大家分享做一个鱼丸火锅
so today I’ll share you guys a dish -- fish ball hotpot 
0:00:07.034,0:00:09.968
# 鱼丸火锅的话 除了喝汤之外还可以烫菜
you could not only drink the soup of fish ball hotpot but boil some veggies in it as well
0:00:10.277,0:00:12.054
# 这条鱼来的也很不容易
it’s not easy to get this fish 
0:00:12.938,0:00:13.770
# 是漆二娃弄的是不哦
Did Qierwa catch it?
0:00:13.886,0:00:16.820
# 是漆二娃弄的 她去罩还摔了一跟头
Yes, she did it, and she actually had a fall when she was catching fish 
0:00:17.184,0:00:17.972
# 滚得田头去了是不哦
and fall into the field?
0:00:17.977,0:00:18.915
# 滚得田头去了
Yes 
0:00:18.997,0:00:21.266
# 爬起来冷的她打腮壳儿（打抖抖）
She was shaking when she got out of the field
0:00:22.487,0:00:24.145
# 这条鱼来的非常不容易
This fish is so hard to get 
0:00:24.446,0:00:25.576
# 好 现在开始弄
Now, we can start
0:00:31.161,0:00:32.182
# 这条鱼还多大哦
This fish is huge
0:00:32.209,0:00:36.482
# 这条是田头的鱼 田头的鱼要好干（吃）点哦 野生鱼哦
Because it’s caught in field, it’s much tastier, wild fish
0:00:36.692,0:00:37.977
# 可能有四斤多噶
More than 2 kilogram 
0:00:38.168,0:00:38.878
# 嗯
Yep
0:00:44.710,0:00:46.851
# 先我们把这个肉给它剔下来
First, we fillet the meat 
0:00:56.692,0:00:59.507
# 这种尾巴一起给它砍下来
cut the tail together 
0:01:04.136,0:01:07.507
# 这里就相当于猪的肋排
This part is equal to the rib of pork 
0:01:09.634,0:01:12.454
# 慢慢一刀一刀的往底下割
And slowly cut it 
0:01:12.819,0:01:15.882
# 割得差不多了之后 这里就立着给它割
after that, standing it and cut 
0:01:18.681,0:01:19.087
# 是不是
Is it right?
0:01:19.208,0:01:19.675
# 嗯
Yes
0:01:23.387,0:01:23.732
# 好
Okay 
0:01:24.401,0:01:26.348
# 从中间斜刀切下去
Cut it with slant angle 
0:01:26.977,0:01:32.332
# 不要切断 这边就慢慢的来
but don’t cut off totally, and take it slowly 
0:01:37.931,0:01:41.541
# 左右移 左右移一下子就去下来了
and move the knife left and right, the fillet has been easily taken off
0:01:41.642,0:01:46.186
# 然后再把表面这个红的肉去一点
then cut some “red” meat off 
0:01:47.302,0:01:52.373
# 红色这个肉去下来做成鱼丸更白 颜色更好看
because after that,fish balls made by white meat will have a beautiful colour
0:01:53.265,0:01:55.152
# 然后也减少一些腥味
it also helps to cut down some fishy smell
0:02:03.306,0:02:06.937
# 好了 现在我们这个鱼红色的（肉）已经去掉了一部分
Alright, now we have already cut the red meat off
0:02:07.829,0:02:10.993
# 然后就开始处理 把它切成小块
then start to process fillets, cut it into small pieces 
0:02:13.732,0:02:16.551
# 切成小块加水洗 多洗几次
add some water to clean them, multiple times 
0:02:17.363,0:02:21.176
# 好 现在加点水把这个鱼片多洗几次
okay, now we’re cleaning them several times 
0:02:24.421,0:02:28.032
# 这个鱼要洗干净 你看 这一洗水都浑了
you have to clean them well, look, the water becomes turbic 
0:02:28.235,0:02:29.533
# 就是这个（鱼）的血
that’s its blood 
0:02:30.791,0:02:32.515
# 把它的血水洗干净
clean its blood finely
0:02:32.576,0:02:33.853
# 放到这个里面再洗一次
and wash it again 
0:02:36.815,0:02:39.148
# 好 洗好了下一步就开始腌制了
After washing it, we start to marinate it
0:02:43.569,0:02:47.221
# 准备一块姜 再准备一些葱
prepare a chunk of ginger some green onion 
0:02:47.748,0:02:49.695
# 这个姜的话先提前切一下
we need to cut the ginger first
0:02:53.529,0:02:54.908
# 四伯爷你晓得这个是啥子不
Uncle, do you know what it is?
0:02:55.659,0:02:57.119
# 搅拌机 搅鱼的
Mixer for mixing fishes 
0:02:57.410,0:02:59.290
# 嗯 你咋子浪聪明安
Hey, how could you be so smart?
0:03:00.121,0:03:03.833
# 看这个形式都像那个工具
It just looks like that 
0:03:03.995,0:03:06.470
# 我们用这个葱 再少一点 不用那么多
We don't need that much green onion, just a bit 
0:03:07.342,0:03:10.851
# 这个葱挽一下捏成一团
and tie it as a knot 
0:03:10.993,0:03:14.624
# 把这个放进去 姜葱一起放进去
put ginger and green onion in it 
0:03:14.908,0:03:16.389
# 然后再加点水
add some water 
0:03:17.180,0:03:19.168
# 加大概2、3两水
around 200-300 gram
0:03:19.574,0:03:21.237
# 盖起来把这个打成姜葱汁
cover it and blend them into mix sauce 
0:03:28.498,0:03:29.330
# 这个很快当
It is so fast 
0:03:29.776,0:03:31.906
# 然后用这个姜葱汁来腌这个鱼
and marinate fish meat with the sauce 
0:03:33.813,0:03:36.511
# 全部倒进去都可以 多就多一点吧
We could use all of them, it’s okay to use a bit more sauce 
0:03:39.634,0:03:43.620
# 其实很多人它做这个鱼丸做出来腥味重啊
Many people say fish balls have strong fishy taste
0:03:45.415,0:03:46.673
# 这一步特别重要
This is step is so important 
0:03:47.870,0:03:48.803
# 这一步很重要
it is the key
0:03:49.066,0:03:52.961
# 让它泡十分钟 姜葱进香味然后又去腥味
Set for 10 minutes to make sure the ginger and green onion flavor could wipe the fishy taste 
0:03:56.511,0:03:58.458
# 好了 我们这个腌了十多分钟了
Okay, it’s more than 10 minutes now
0:03:58.478,0:04:01.947
# 现在把这个鱼给它捡出来稍微洗一下
now we could pick it up and wash
0:04:02.880,0:04:03.711
# 把它洗一下
wash it 
0:04:05.253,0:04:07.971
# 就像这样就可以了 把它丢进去
Just like that and throw it 
0:04:08.762,0:04:13.136
# 如果对这个颜色品质要求高的 可以多清洗几次
If you have high preference of the colour, you could wash it more times 
0:04:13.569,0:04:15.699
# 把这个绿色的东西全部洗干净
Cleaning the green stuff 
0:04:16.713,0:04:20.020
# 好 我们现在加点冰水 这个水一定要够冰
now we add some cold water the water has too be cold enough
0:04:20.486,0:04:28.133
# 就是防止它高速转动得时候 温度过高破坏鱼的弹性
to pretend high temperature destroying the resilience of fish meat when doing high-speed mixing 
0:04:50.223,0:04:51.217
好 可以了
It’s done
0:04:52.210,0:04:54.056
# 我们这个现在效率很高
We have high efficiency now
0:04:54.056,0:04:57.099
# 用这个东西的话比你用刀剁快
using this machine is faster than using knife  
0:04:57.505,0:05:00.243
# 用这个最多就搅个两三分钟
it only takes 2-3 minutes 
0:05:00.304,0:05:04.178
# 用刀要剁四十分钟 特别的浪费时间
for knife, it takes 40 minutes, it’s too time wasting 
0:05:04.320,0:05:05.618
# 所以我选择用这个
so I choose to use mixer 
0:05:05.740,0:05:07.383
# 诶呀 搅得好融
Wow, it is so smooth
0:05:08.154,0:05:09.472
# 我们直接加这个蛋清
Now we add some egg white 
0:05:11.480,0:05:12.352
# 直接加蛋清
Add it directly 
0:05:13.853,0:05:15.984
# 蛋清的话就根据自己家的条件来
it depends on your own option for how many eggs white
0:05:16.085,0:05:19.675
# 加一个也行 加三四个也行 我今天准备加四个
it could be one or three and four, I’m gonna add four eggs white today
0:05:20.121,0:05:24.158
# 这个蛋黄先放这边 蛋黄等会儿还可以拿来炒个菜噶
Set the egg yolk aside, we could cook them for another dish 
0:05:30.243,0:05:33.285
# 好 现在先把它和转（匀）
okay, we finely mix them first
0:05:35.841,0:05:38.722
# 今天我准备做一个弹牙弹的厉害一点的
I’m gonna prepare some more elastic fish balls 
0:05:38.782,0:05:40.811
# 所以水加得比较少
so add less water 
0:05:44.827,0:05:46.348
# 先加个3、4克盐
add 3-4grams salt
0:05:48.336,0:05:51.582
# 盐少量多次加 不要一次加够了
add multiple times with less quantity, don't add them all in one time 
0:05:52.981,0:05:54.482
# 像这样搅十分钟
and mix it like this for 1o minutes 
0:05:58.985,0:05:59.736
# 可以了
Finished !
0:06:01.480,0:06:02.900
# 刚刚滴下来的这个不算
That one drop didn't count 
0:06:03.285,0:06:05.659
# 看嘛 这个能够坚持到十秒钟 可以了
Look! This could hold for 10 seconds that’s enough  
0:06:08.316,0:06:10.223
# 定住了 看都没
You see it? it sticks on top
0:06:11.156,0:06:15.334
# 像这样就行了 在手上面十秒钟不掉就行了
like this, stick on hands for 10 second is enough 
0:06:16.206,0:06:19.127
# 现在开始挤丸子了
Now starting to squeeze balls 
0:06:19.553,0:06:23.083
# 我们这个丸子成功与否 就看它看下水能不能飘起来
If the balls could float on water, we make fish balls successfully, otherwise it’s failed 
0:06:24.016,0:06:27.363
# 还要准备油 润一下勺子 不至于粘得太厉害
we also need to moisturize the spoon with oil to avoid fish balls stick on the spoon 
0:06:27.829,0:06:29.168
# 好 准备挤丸子
ready for squeezing now 
0:06:30.608,0:06:33.427
# 挤小一点 因为待会儿丸子它还会发胀
don’s squeeze too big balls, because they will become bigger later 
0:06:33.590,0:06:35.010
# 诶 它咋子不沉安
umm? Why it didn't sink
0:06:35.131,0:06:35.943
# 飘起了撒
It’s floating 
0:06:36.693,0:06:40.101
# 就说明空气就打进去了撒
which means the air has been added in the meat while mixing it 
0:06:40.385,0:06:41.054
# 就要得了噶
and that’s it? 
0:06:41.156,0:06:42.008
# 对 就要得了
Yes, that’s it 
0:06:42.981,0:06:44.726
# 好 挤第三个
Cool, the third one 
0:06:46.678,0:06:48.600
# 嘿嘿 狗东西还奇怪
hehe, it’s kinda strange 
0:06:50.060,0:06:50.770
# 第四个
The fourth
0:06:51.987,0:06:53.995
# 手都要拷（搅拌）偻（酸）我给你说
My hands are so tired 
0:06:53.995,0:06:56.105
# 你没拷过的人拷的话
If you have never mixed it before 
0:06:58.884,0:07:00.933
# 这是哪个的发明安
Who invented this method?
0:07:01.480,0:07:03.711
# 属于我们中国人的发明撒
It’s our Chinese invention 
0:07:05.050,0:07:07.383
# 你要晓得我们饮食的几千年的文化了
you know, we have several thousands years of food culture 
0:07:08.072,0:07:10.405
# 没得点功夫咋可能安
How could we don’t have some Kongfu (mixing skill)
0:07:10.953,0:07:12.981
# 好 现在开始准备制作了
now we are ready to cook
0:07:13.914,0:07:15.780
# 把这个锅烧热了先加点油
heat up the wok and add some oil 
0:07:15.902,0:07:17.849
# 这回不用你的宽油了四伯爷
we don't use your Kuanyou(literally "broad oil") this time, uncle 
0:07:18.438,0:07:21.642
# 哎呀 随便用啥子油都要得
you could use any kind of oil 
0:07:22.657,0:07:23.346
# 少放点
don't put too much 
0:07:23.590,0:07:25.780
# 还分你的我的 你都是我的安
There is no ‘yours’ or ‘mine’, yourself is also mine 
0:07:27.342,0:07:28.214
# 是 嘿嘿
Yep, hehe
0:07:37.180,0:07:41.500
# 我们先把这个油烧热了之后放点盐在锅底里面
Now we heat the oil and add some salt in the wok
0:07:41.987,0:07:47.789
# 待会儿煎鱼骨头的时候才不至于说太腥或者是说煎得太烂
to avoid fishy taste or broken shape when we are frying fishbone 
0:07:51.845,0:07:54.482
# 好 这个油烧热了 鱼放下去煎
now oil is heated, adding fish 
0:07:56.754,0:07:58.752
# 煎鱼头的时候加点这个姜
add some ginger when frying the fish head 
0:08:01.602,0:08:03.975
# 那个葱待会儿我们煮的时候再放
put green onions when boiling fish 
0:08:06.024,0:08:07.809
# 好 慢慢的给它煎
fry it slowly 
0:08:08.539,0:08:12.312
# 好 这个我们煎下面一层就可以了 把它煎香煎黄
we only need to fry one side of the fish till it becomes golden and having aroma 
0:08:12.352,0:08:13.488
# 加点这个开水来煮
add some hot water to boil it 
0:08:14.401,0:08:16.997
# 四伯爷这个火要烧大点哦
Uncle, add some fire 
0:08:17.261,0:08:19.594
# 好好好 加大火力
Cool, cool add more fire 
0:08:20.567,0:08:23.285
# 好 现在就等着这个鱼汤熬出来
Now we’re waiting the fish soup 
0:08:25.374,0:08:28.510
# 现在这个水开了 但是要把浮沫打（去）一下
now it starts boiling, we need to get the scum out of water 
0:08:30.202,0:08:32.636
# 打完浮沫加点葱下去一起煮
and add some green onions to boil 
0:08:36.571,0:08:39.687
# 好了 我们这个汤都熬白了 现在把这个葱拿出来
when the soup turns into white colour, pick up green onions 
0:08:40.202,0:08:42.314
# 拿出来了之后就准备下鱼丸了
and it’s ready to put fish balls 
0:08:42.406,0:08:43.914
# 下鱼丸之前先调味
before that, seasoning first 
0:08:44.259,0:08:47.355
# 要不然等一下再放盐下去搅一下就会把鱼丸搅烂了
otherwise mixing salt in soup will break fish balls shape 
0:08:48.122,0:08:49.274
# 放点盐调底味
add some salt 
0:08:50.375,0:08:52.103
# 四伯爷你端着我来漏（捞）
Uncle, you hold it, I’m scooping up the fish balls 
0:08:54.914,0:08:56.774
# 火的话就可以烧小点的
turn down the fire 
0:08:57.423,0:08:59.948
# 轻轻地漏起来 再轻轻地放下去
scoop them up evenly and put in again
0:09:02.184,0:09:04.846
# 吃好多煮好多 边吃边煮
Boil as many as you eat, boiling while eating 
0:09:06.348,0:09:07.457
# 好 这个差不多了
Right, it’s done here
0:09:07.508,0:09:09.573
# 我先盛点出来给我伯爷尝一下
Let me spoon up some fish balls to give my uncle for a taste
0:09:09.829,0:09:11.297
# 鱼丸下锅煮了十分钟左右
it takes around 10 minutes to boil the fish balls 
0:09:11.638,0:09:12.866
# 因为这次的比较小
because the fish balls are not too big this time 
0:09:13.583,0:09:16.399
# 所以的话时间就比较快一点
it’s faster to cook them than normal 
0:09:17.337,0:09:18.600
# 熟肯定是熟了
it’s definitely cooked 
0:09:20.989,0:09:22.013
# 熟了的 完全熟了的
Yes, not row at all, completely cooked 
0:09:22.030,0:09:25.900
# 这是你精心制作的东西
This is your we
0:09:28.924,0:09:31.480
# 嗯 安逸
Amazing!
0:09:31.552,0:09:34.044
# 适合老人吃噶 适合牙口不好的
It is easy to chew, very suitable for elderly and someone who has bad teeth
0:09:34.112,0:09:38.054
# 好干（吃） 跟豆腐脑一样 一抿就烂了
It is so delicious, just like tofu brain, melting in your mouth
0:09:38.157,0:09:38.498
# 是不哦
Is it?
0:09:38.600,0:09:38.959
# 是啊
Yes 
0:09:39.198,0:09:40.204
# 我再拿个碗装点
Let me have an another bowl of fish balls 
0:09:40.972,0:09:42.457
# 伯娘过来吃
Auntie, come here to eat fish balls 
0:09:44.590,0:09:45.375
# 很耙噶
So tender 
0:09:46.041,0:09:47.064
# 好嫩气哦
It’s so tender 
0:09:47.747,0:09:49.385
# 嗯 跟豆腐一样
Umm like tofu
0:09:49.624,0:09:49.965
# 是安
Yep
0:09:53.532,0:09:56.390
# 这个特别适合牙口不好的 还有小孩子
it’s very suitable for those people who have bad teeth and children as well 
0:09:56.416,0:09:59.232
# 因为它这个鱼刺已经打得非常碎了
Because the fish bones has been smashed 
0:10:00.204,0:10:01.450
# 看嘛 好安逸嘛
Look! It’s so tasty and beautiful 
0:10:01.570,0:10:02.713
# 伯娘可以多吃一点
Aunt, eat more 
0:10:04.146,0:10:10.238
# 啥子都没加 就只加了盐巴加了姜葱加了点蛋清
It didn’t have any extra adding, only salt ginger green onion and some egg white 
0:10:10.648,0:10:12.730
# 好 本期视频就到这里了 拜拜
Here is today’s video Byebye 
0:10:13.447,0:10:14.402
# 你慢慢吃
Enjoy your meal

**Comment by immoonancient** [comment]
校对版字幕已发布
