### ISSUE TITLE
[华农兄弟] 华农兄弟看下小黑生的小肥狗再去看下另一只母猪生的小猪崽 - https://youtu.be/A3JUJ6-0dKc

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#585]
https://youtu.be/A3JUJ6-0dKc
<p>&#35270;&#39057;&#21457;&#24067;&#20110; January 14, 2020 at 08:10PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/A3JUJ6-0dKc

#华农兄弟：看下小黑生的小肥狗，再去看下另一只母猪生的小猪崽
#Huanong Brothers: Let's take a look at Blacky's chubby puppies, and also the piglets from another sow.

0:00:00.000,0:00:03.180
# 前幾天小黑生啦  它生了三個  很胖的哦
Blacky has given birth a few days ago, She gave birth to three babies. All are very fat.

0:00:03.540,0:00:05.100
# 就在上面  看一下
They are just upstairs. Let me show you.

0:00:09.020,0:00:11.540
# 你看小黑  這三個那麼大個
Look, Blacky! These three are so big.

0:00:13.340,0:00:14.680
# 這  胖的
He's, so fat,

0:00:15.280,0:00:15.800
# 胖的
so fat,

0:00:16.480,0:00:17.260
# 胖的圓的
so fat that he's even round.

0:00:18.420,0:00:19.480
# 看一下你小孩
Let me have a look at your kids!

0:00:20.160,0:00:20.740
# 親一下
Kiss him.

0:00:22.220,0:00:23.100
# 好胖啊它
He's so fat!

0:00:24.520,0:00:25.840
# 這個  這也是
This one, it's also...

0:00:26.580,0:00:27.280
# 看一下
Let me see.

0:00:28.000,0:00:28.920
# 這個是  母的
She's, a girl.

0:00:29.600,0:00:31.600
# 現在也胖的不行啦  那麼胖
She's ridiculously fat now, so fat.

0:00:32.660,0:00:35.320
# 看這個  誒喲  那麼小  你想咬我啊
Have a look at this one. Eyo! You're still that small and you wanna bite me?

0:00:36.280,0:00:38.000
# 這個也是那麼大 (註︰原字幕應該錯了，他是說「這個也是母的」) 一公二母
This is also a girl. One boy, two girls.

0:00:39.640,0:00:41.060
# 啊  看這個
Ah! Have a look at this one!

0:00:41.260,0:00:43.480
# 這個  這個  全是黑的哦
This is, this is, all black. You see?

0:00:44.500,0:00:46.720
# 跟小黑  跟小黑應該有點像
He should look a bit, a bit like Blacky.

0:00:48.820,0:00:51.240
# 好胖啊  眼腈都睜開了
He's so fat. His eyes have already opened.

0:00:56.320,0:00:57.820
# 超標啦  身材
You're overweight, you know.

0:00:58.960,0:01:01.760
# 油光滑亮的  你看  肥的好好啊
His coat is smooth and shiny. Look! He's chubby and healthy.

0:01:05.620,0:01:06.720
# 牙都還沒長出來
His teeth have still not yet come out.

0:01:11.640,0:01:13.840
# 小黑 借我用  借我拍一下啊
Blacky, lend me your boy! I wanna film him for a while.

0:01:14.660,0:01:15.440
# 不能這樣子
Come one, that's not nice.

0:01:19.700,0:01:20.200
# 你看
Look!

0:01:21.000,0:01:22.640
# 這是小黑最大的崽
This is Blacky's biggest kid.

0:01:25.200,0:01:26.120
# 好大啊
So big!

0:01:27.080,0:01:27.960
# 圓的
He's just round!

0:01:35.640,0:01:37.880
# 是不是還沒長出來  好大
Are they still not coming out? They're still so small.

0:01:46.280,0:01:49.700
# 別叫了  等下小黑要過來  一叫小黑就過來啦
Don't yelp. Otherwise Blacky is coming. Blacky just comes whenever they yelp.

0:01:51.740,0:01:54.200
# 你看它的毛色好亮(註︰我覺得他是說「好靚」)  發亮
Look! His coat is really beautiful. It's shiny.

0:02:04.100,0:02:06.080
# 把它放回去  那小黑一直在看著我
Put it back. Blacky has never put her eyes away from me.

0:02:06.620,0:02:09.040
# 一直在看著我  生怕我把它抱走
She's always look at me, thinking that I might take her boy away.

0:02:09.380,0:02:10.880
# 不會的  放心啦
No worries. I won't.

0:02:11.760,0:02:12.920
# 你看  這個比較小
Look! This is a bit smaller.

0:02:16.580,0:02:18.820
# 別叫  別叫  一叫你媽媽又來啦
Don't yelp! Don't yelp! Or your mom comes again.

0:02:19.880,0:02:21.080
# 叫的好凶啊
She's yelping so fiercely.

0:02:23.060,0:02:26.080
# 把你放下去  別叫了啊  別叫了啊  把你放下去
I put you down. Don't yelp, don't yelp. I put you down.

0:02:27.240,0:02:28.000
# 看下這個
Have a look at this one.

0:02:29.160,0:02:29.760
# 你別叫
Stop yelping!

0:02:32.020,0:02:34.460
# 看看你爪子都胖的成這樣子了  看到沒有
Look! Even your paws are that fat. You see?

0:02:35.560,0:02:36.360
# 好胖啊  (註︰原子幕沒有)
So fat.

0:02:38.720,0:02:39.660
# 這個聽話一點
This one behaves a bit better.

0:02:47.240,0:02:48.060
# 牙都還沒有
She still has no teeth.

0:02:51.120,0:02:53.200
# 就像小黑  那麼喜歡叫
They like yelping that much, just like Blacky.

0:02:59.500,0:03:01.700
# 不要叫  別叫啦
C'mon! Don't yelp. Don't yelp, alright?

0:03:05.600,0:03:08.300
# 另外一條母豬  昨晚也生了哦  我去看一下
Another sow has also given birth yesterday night. Let me take a look.

0:03:10.940,0:03:12.360
# 抱在一起  互相取暖
Cling together, to stay warm!

0:03:18.300,0:03:20.200
# 你看  小豬在裡面  我帶了鞭子
Look! The piglets are inside. I take a stick with me.

0:03:20.800,0:03:22.160
# 怕那公豬來敢擊我
The boar might attack me.

0:03:22.800,0:03:24.100
# 門又被我們堵住啦
We've blocked the door again.

0:03:25.040,0:03:26.580
# 我直接窗戶上爬進去
I climb inside right from the window.

0:03:29.360,0:03:30.920
# 那母豬生的那個崽  (註︰這個母豬是最初的母豬，他沒有說清楚，我也不解釋了)
These are the piglets from the sow.

0:03:31.600,0:03:33.640
# 現在就那麼大啦  一大堆大那裡
They're already that big now. A whole bunch of them is over there.

0:03:34.180,0:03:35.600
# 抱著它媽媽在睡覺
They're sleeping, leaning on their mom.

0:03:35.840,0:03:38.120
# 那個狗你看  躲在豬後面
The puppy, look! It's hiding behind the pigs.

0:03:38.120,0:03:40.200
# 我還以為是  小豬崽嘞
I just thought that, it were a piglet.

0:03:40.960,0:03:45.140
# 它在偷豬奶喝  它媽媽肯定也發現它了  全都是黑黑的
It's stealing the pig milk. The mom must have spotted it. It's black all over the body.

0:03:47.360,0:03:48.160
# 沒去管
But it doesn't care.

0:03:48.260,0:03:50.080
# 天天跟那個豬待在一起
That puppy is always with the pigs.

0:03:51.640,0:03:55.440
# 那豬長了二三十斤了  你還長個幾斤在那裡  嘿嘿
The pigs will soon weigh more than ten kilograms. But you're still a few kilograms, hehe.

0:03:55.820,0:03:56.820
# 那狗不會大的
That puppy won't grow too much.

0:03:59.640,0:04:02.600
# 它們重  重叠在一起  很暖的哦  這樣子
They're stack, stacking up. It makes them feel very warm.

0:04:04.960,0:04:05.460
# Hello
Hello!

0:04:06.320,0:04:10.320
# 你看這個小狗  這個小狗偷豬奶喝啦  最喜歡吃噠
Look at this puppy! It's stealing the milk. It's the biggest eater.

0:04:12.300,0:04:15.840
# 不用跑  我又不管你  來  隨便喝  隨便喝 喝  吃吃吃
You don't need to run away. I didn't say anything. C'mon. Feel free to take the milk. Suck it, suck it!

0:04:18.320,0:04:19.500
# 我一去它就怕我
It's scared of me whenever I get close,

0:04:19.820,0:04:21.060
# 我手上拿了鞭子
as I have a stick in my hand.

0:04:21.560,0:04:22.960
# 我是怕那個公豬拱我
It's because the boar might attack me.

0:04:23.120,0:04:24.000
# 才帶了鞭子
That's why I take a stick.

0:04:26.500,0:04:28.160
# 我看一下小豬  小豬在這裡哦
Let me take a look at the piglets. The piglets are here.

0:04:31.440,0:04:33.200
# 你看  這個小豬崽
Look! The piglets,

0:04:34.160,0:04:35.320
# 跟它媽媽在一起
are with their mom.

0:04:36.240,0:04:39.680
# 哇  我又不摸  我只是看一下而已  我又不摸你小崽
Wa! I won't touch them. I just wanna take a look. I'm not touching your babies.

0:04:40.200,0:04:41.200
# 那麼兇幹嘛
Why are you that fierce?

0:04:42.500,0:04:45.680
# 看你兇不兇  (註︰我聽到「像不像」) 那麼  耳朵都豎起來啦
Look how fierce you are. You're so, you ears are even pointing up.

0:04:49.260,0:04:51.820
# 它們碰著它媽媽  肯定身上很暖
They're leaning on their mom. It's body must be very warm.

0:04:52.320,0:04:56.260
# 它們就  挨在一起  我特意給它做了一個棚子  雨棚
They're then, clinging together. I've made a shelter, a rain shelter, just for them.

0:04:56.380,0:04:57.280
# 現在有點下雨啦
There's a bit rain now.

0:04:58.700,0:05:00.780
# 這裡有個那麼好的地方你們不鑽進去
Here's such a good place but you're not staying inside.

0:05:00.780,0:05:02.240
# 就硬要鑽到這裡來
You just wanna stay here.

0:05:05.500,0:05:07.220
# 因為昨天晚上太急啦
It was all of a sudden yesterday night.

0:05:07.220,0:05:09.780
# 我就搞了點塑料袋  就放在這裡  給它做窩
So I simply took some plastic bags here, for it to make a lair.

0:05:10.840,0:05:14.000
# 就是我們裝  裝過來米糖的這個塑料袋啊  全部給它啦
These are the plastic bags that we've used for storing, storing the rice bran. They're all here now.

0:05:18.680,0:05:20.420
# 幹嘛  還是餵奶呦
What are you doing? You still need to feed the babies, you know?

0:05:21.060,0:05:23.360
# 你我又餵奶  等下不要我鞭我
You're not feeding. Don't make me flog you!

0:05:27.580,0:05:29.180
# 好小哦  生了八隻
Really small. Eight piglets.

0:05:31.840,0:05:34.480
# 很警愓我們哦  我怕我把它小孩子抱走
It's on high alert, thinking that we might take the babies away.

0:05:36.400,0:05:39.200
# 沒事的  我又不抱  我只看看
No worries. I'm not taking them away. I just wanna take a look.

0:05:40.880,0:05:42.640
# 哎呦  哎呦  哎呦  哎呦
Ayo, ayo, ayo, ayo!

0:05:43.420,0:05:44.900
# 你擠著你的小豬啦
You're pressing on your piglets!

0:05:48.600,0:05:51.840
# 唉  不要看啦  不要看啦  越看它越發飆
Ay! Don't watch it, don't watch it. It's getting more and more angry.

0:05:53.360,0:05:54.640
# 你看那公豬又來啦
Look! The boar is coming again.

0:05:55.560,0:05:56.820
# 好怕啊  它
It's so scared.

0:05:59.280,0:06:00.920
# 我又沒對它們做甚麼
I haven't done anything bad to them.

0:06:03.020,0:06:03.520
# 聽話
Behave!

0:06:03.860,0:06:04.720
# 不聽話就鞭你
I'll flog you if you don't.

0:06:07.840,0:06:08.920
# 你看  老實啦
Look! Much better now.

0:06:10.260,0:06:11.980
# 一說它它就退回去啦
It steps back once I talk about it.

0:06:14.840,0:06:18.240
# 你看這條公豬  天氣有點冷啦  它(身體)收回去了
Look at this boar! It's a bit cold now. So it shrinks.

0:06:18.800,0:06:19.720
# 收得有點短
It's a bit short now.

0:06:20.980,0:06:22.800
# 等一下  它天氣熱的時候  它又可以
Later, when it's hotter, it can again,

0:06:23.240,0:06:23.880
# 長一點
become a bit longer.

0:06:32.520,0:06:33.540
# 我又不打你
I won't beat you.

0:06:36.220,0:06:38.240
# 哇  這  小豬崽
Wa! The, piglets,

0:06:40.660,0:06:41.580
# 都好胖啦
are all very fat.

**Comment by vincenthychow** [comment]
已發佈
