### ISSUE TITLE
[华农兄弟] 华农兄弟快过年了给村里的老人做个美味的竹鼠年夜饭 - https://youtu.be/HeebXOzbSsc

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#589]
https://youtu.be/HeebXOzbSsc
<p>&#35270;&#39057;&#21457;&#24067;&#20110; January 17, 2020 at 09:08AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
0:00:00.000,0:00:02.460
# 今年準備做一個竹鼠年夜飯
This year, we're gonna make a bamboo rats New Year Eve dinner,

0:00:02.740,0:00:04.960
# 給村裡的老人吃  孝敬一下老人
for the elderly in our village, to show them our respect.

0:00:05.400,0:00:08.820
# 你看  你看這個竹鼠  不胖也不瘦
Look! Have a look at this bamboo rat. It's neither too fat nor too skinny.

0:00:09.120,0:00:10.980
# 你看 身材剛剛好哦 嘖
Look! It's perfect, isn't it?

0:00:11.460,0:00:13.580
# 這個用來做紅燒  很好吃的哦
Let's braise it. It must be very tasty.

0:00:19.660,0:00:21.180
# 這個竹鼠太瘦啦
This bamboo rat is far too skinny,

0:00:22.240,0:00:23.300
# 又兇又瘦
fierce and skinny.

0:00:24.100,0:00:25.720
# 這個用來  做白切竹鼠
This bamboo rat, can be steamed.

0:00:26.080,0:00:27.640
# 特別好  你看  它那打架了
It would be really nice. Look! It had a fight.

0:00:27.880,0:00:29.040
# 旁邊還有一點小傷
Here's still a small wound.

0:00:29.580,0:00:30.080
# 沒事
Never mind.

0:00:33.820,0:00:34.860
# 你看  這個竹鼠
Look! This bamboo rat,

0:00:36.840,0:00:38.600
# 它這個竹鼠好胖啊  這個竹鼠
it's really fat, this bamboo rat.

0:00:39.880,0:00:42.740
# 用來  用來烤  特別合適
Let's, let's roast it. It would be perfect.

0:00:44.500,0:00:45.700
# 好  放回去
Alright! Put it back.

0:00:48.460,0:00:49.060
# 進去
Into the cage!

0:00:53.300,0:00:54.280
# 你看這個竹鼠
Have a look at this bamboo rat!

0:00:56.240,0:00:57.400
# 這個也不是很胖哦
This one is not really that fat.

0:00:58.260,0:01:01.160
# 這樣的竹鼠用來做那個  炒  炒  炒那個竹笋啊
This kind of bamboo rats can be, you know, fried, fried, fried with the bamboo shoots.

0:01:01.560,0:01:02.740
# 這個特別好吃的哦
It would taste really nice.

0:01:03.520,0:01:04.240
# 它的肉質
It's texture,

0:01:04.600,0:01:05.220
# 特別好
is exceptional.

0:01:10.700,0:01:11.480
# 不肯進
It's not getting in.

0:01:13.480,0:01:14.700
# 這個好兇啊  這個
This one is really fierce, you know.

0:01:15.380,0:01:16.880
# 每次給它發老婆它都不要
It rejects every single wife assigned to it.

0:01:18.520,0:01:19.220
# 把你烤啦
I'll have you roasted.

0:01:29.020,0:01:30.840
# 現在五個啦  再抓一個
I have five now. Let me catch one more.

0:01:31.560,0:01:32.560
# 再抓一個長得
Let me catch a,

0:01:34.600,0:01:36.420
# 又大又肥的  這個是
big and fat one. This one,

0:01:36.960,0:01:38.140
# 這個  這個  你看  這個
this one, this one. Look! This one,

0:01:38.460,0:01:39.780
# 這個四斤多  這個
this one weighs more than two kilograms.

0:01:40.380,0:01:42.420
# 現在都長不大了  一直都是這樣子
It's not growing anymore. It has been in this size for a while already.

0:01:46.080,0:01:47.540
# 天天吃  吃的很多哦它
It eats, it eats a lot every day.

0:01:49.140,0:01:49.700
# 把它
Let me,

0:01:50.600,0:01:51.240
# 把他用來
let me make a,

0:01:52.080,0:01:53.120
# 用來燉湯
make a soup with it.

0:01:56.540,0:01:57.680
# 這個很靚哦  這個
This one is really beautiful.

0:01:58.680,0:02:00.400
# 一點肥肉都沒有  全是瘦肉
It has only lean meat, not even a bit of fat.

0:02:01.620,0:02:02.180
# 就你啦
You're chosen.

0:02:08.100,0:02:09.040
# 塞都塞不進去
I can't even squeeze it in.

0:02:09.440,0:02:11.140
# 太 太大個了
It's, it's simply too big.

0:02:13.760,0:02:14.460
# 剛剛好
Just right.

0:02:16.640,0:02:18.160
# 我們把它帶下去處理一下
Let's take them down there for further processing.

0:02:40.940,0:02:43.120
# 你看  這個竹鼠  你看  殺好啦
Look! The bamboo rats, look, are ready now.

0:02:43.740,0:02:44.640
# 全都是這樣子的
They all look the same.

0:02:48.160,0:02:49.240
# 這  這裡還有兩個
Here, here are two more,

0:02:50.100,0:02:50.840
# 這裡還有兩個
two more here.

0:02:52.160,0:02:53.480
# 這個用來做  白切(註︰他最後是蒸的)
This one is to be, steamed.

0:02:54.180,0:02:55.360
# 改刀都改好啦
And this one is to be roasted.

0:02:56.580,0:02:57.080
# 先把這個  這個肉
Look!

0:02:57.380,0:02:58.300
# 改刀都改好啦
It has already been sliced.

0:03:02.860,0:03:04.700
# 先把這個  這個肉
First, the, the meat,

0:03:05.440,0:03:06.540
# 搞點這個肉出來
let me cut off some meat here.

0:03:07.920,0:03:09.060
# 這個是竹鼠肉哦
This is bamboo rat meat.

0:03:11.320,0:03:12.580
# 我把它  切碎一點
Let me, mince it.

0:03:14.580,0:03:16.420
# 老  老人家  牙齒不太好
The elderly doesn't have very good teeth.

0:03:23.300,0:03:25.080
# 生薑  生薑跟這個
Ginger, ginger together with,

0:03:25.800,0:03:26.360
# 肉沫
minced meat,

0:03:28.180,0:03:28.920
# 放在一起
are put together.

0:03:36.060,0:03:37.300
# 感覺肉太少啦
The meat doesn't seem quite enough.

0:03:37.840,0:03:38.800
# 再割點下來
Let me get more.

0:03:39.700,0:03:41.320
# 這個肉就在那個大腿上取
The meat is just taken from the thigh.

0:03:42.940,0:03:45.420
# 你看  這個  還有塊瘦肉
Look! Here, is still a piece of lean meat.

0:03:49.460,0:03:51.280
# 這全是瘦肉  你看  這塊也可以
There's only lean meat. Look! This piece is also good.

0:03:53.760,0:03:54.840
# 你看  這瘦肉
Look! This is lean meat.

0:03:55.660,0:03:56.580
# 小狗  走開
Puppy! Go 'way!

0:04:03.820,0:04:05.500
# 這個  這個肉差不多好啦
The, the meat should be quite alright now.

0:04:10.220,0:04:11.160
# 這是肉沫
This is minced meat.

0:04:13.060,0:04:15.140
# 放高一點  等下被小狗吃掉啦
Put it higher. Otherwise it would be eaten by the doggies.

0:04:17.800,0:04:19.240
# 這個竹鼠先把它砍碎
Let me first chop this bamboo rat into pieces,

0:04:20.140,0:04:21.580
# 全部把它砍成一塊一塊的
chop it all into pieces.

0:04:28.820,0:04:29.760
# 砍碎一點
I cut it into smaller pieces,

0:04:30.960,0:04:31.920
# 比較好夾一點
so that it's easier to take with chopsticks.

0:04:33.560,0:04:34.720
# 砍碎了就放在這裡
I'll put the pieces here.

0:04:41.720,0:04:45.700
# 我先弄一下那個烤竹鼠 要腌一下  提前  提前  腌一下才行
Let me first prepare the roast bamboo rat. It needs to be marinate, mar, marinated beforehand.

0:04:46.440,0:04:47.440
# 把它放到這裡先
Let me put it here first.

0:04:56.900,0:04:58.300
# 這個用來烤的  這個
This is to be roasted, this one.

0:05:00.120,0:05:02.140
# 這個是用來白切的  白切的
And this is to be steamed, steamed,

0:05:05.860,0:05:07.760
# 白切的就這樣  這樣蒸就可以啦
steamed. Well. it can be steamed right away.

0:05:13.500,0:05:14.860
# 就直  直接這樣蒸
Just put, put it here and steam right away.

0:05:15.560,0:05:16.720
# 把它蒸出來就行啦
It will be done after steaming for a while.

0:05:20.140,0:05:21.160
# 把它劈一下
Let me cut it open.

0:05:28.700,0:05:31.380
# 你看  這個就直接這樣蒸  蒸出來
Look! Now it can be steamed, steamed right away.

0:05:32.080,0:05:33.060
# 這個小竹鼠
It's a small bamboo rat.

0:05:33.820,0:05:35.480
# 蒸的話它會收回去的哦
It will shrink after steaming.

0:05:38.700,0:05:39.280
# 這個
The,

0:05:40.180,0:05:41.040
# 這個烤的要
the one to be roasted,

0:05:41.260,0:05:42.360
# 烤的就要  在這裡
to be roasted, should be put here,

0:05:42.960,0:05:43.540
# 腌一下
and marinated for a while.

0:05:44.520,0:05:45.060
# 我拿那個
Let me,

0:05:45.640,0:05:46.540
# 到這旁邊來
put it aside.

0:05:47.540,0:05:48.420
# 加點這個生薑
Put some ginger.

0:05:49.360,0:05:50.300
# 加點這個醬油
Put some soy sauce,

0:05:51.400,0:05:52.360
# 醬油搞多一油
a bit more soy sauce.

0:05:53.360,0:05:54.800
# 再加點這個  料酒
And also some, this is, cooking wine.

0:05:58.960,0:06:00.060
# 哎呦  不出來
Ayo! It's not coming out.

0:06:04.260,0:06:05.120
# 再加點油
Then put some oil.

0:06:10.920,0:06:11.700
# 再加點鹽
And also some salt.

0:06:16.320,0:06:16.940
# 拌一下
Mix it well,

0:06:18.600,0:06:20.020
# 讓它提前入味
so that it becomes more flavourful.

0:06:24.280,0:06:26.840
# 好啦  再 腌半個小時
Alright! Then, marinate it for half an hour.

0:06:27.280,0:06:28.440
# 我們就可以直接烤啦
And we can roast it right away.

0:06:33.840,0:06:34.820
# 你看  加點水
Look! With some water,

0:06:35.360,0:06:36.960
# 烤的竹鼠就不會  沒那麼乾
the roast bamboo rat won't, won't be that dry.

0:06:38.020,0:06:38.920
# 這個蓋  蓋上
The lid, cover it.

0:06:43.680,0:06:44.660
# 把它勾起來
Put the hook here.

0:06:49.060,0:06:50.940
# 嗯  可以  把它掛起來
Um! Alright! It can be hung in the oven.

0:06:57.440,0:06:57.940
# 你看
Look!

0:06:58.300,0:06:58.940
# 這個勾住啦
So it's hung here.

0:06:59.240,0:06:59.820
# 就這樣
Then it can be,

0:07:00.280,0:07:00.780
# 直接烤
roasted right away.

0:07:04.040,0:07:04.760
# 把這個
Let me,

0:07:05.760,0:07:06.320
# 柴火
set a fire here,

0:07:07.440,0:07:08.440
# 放在這裡燒一下
with the firewood.

0:07:25.940,0:07:28.260
# 你看這個竹鼠  放點薑在它背上
Look at this bamboo rat! I've put some ginger on its back.

0:07:31.120,0:07:32.000
# 直接蒸了
Steam it right away.

0:07:35.740,0:07:37.760
# 再放點柴  直接大火燒就行
Put some more firewood. Just high heat would suffice.

0:07:38.580,0:07:39.900
# 加點這個蕉芋粉
Put some Indian shots powder.

0:07:40.760,0:07:42.900
# 我先攪拌一下  這個是竹鼠肉
Let me mix it well first. This is bamboo rat meat,

0:07:43.860,0:07:44.620
# 跟葱子
and spring onions.

0:07:47.520,0:07:48.820
# 現在我開始釀豆腐
Now I start stuffing it into the tofu.

0:07:52.620,0:07:53.880
# 釀豆腐這裡有一個
To stuff it in, here's a...

0:07:56.620,0:07:59.260
# 要把它挖出來一點  要不然塞不進去
I need to make a hole here. Otherwise nothing can be stuffed in.

0:07:59.660,0:08:00.600
# 要塞多一點
I wanna put more.

0:08:04.280,0:08:06.540
# 塞滿一點  這個肉好好吃的哦
Yup! Put more. The meat paste is really tasty.

0:08:10.320,0:08:11.840
# 啊  你看  釀好一個啦
Ah! Look! One is done.

0:08:16.760,0:08:17.800
# 你看  又釀好一個
Look! Another is done.

0:08:18.440,0:08:20.400
# 要這樣放才放得下 不然放一下
I think I need to put it this way. Otherwise the plate is not large enough.

0:08:25.700,0:08:27.120
# 這個釀豆腐已經做好啦
The stuffed tofu is ready now.

0:08:28.420,0:08:30.840
# 我們剩下的這個料子啊  我們做肉圓
Let's, let's make meat balls using the remaining ingredients.

0:08:31.280,0:08:33.100
# 你看  做好一個啦
Look! One is done.

0:08:37.920,0:08:38.600
# 兩個
Two

0:08:43.100,0:08:43.860
# 三個
Three

0:08:45.400,0:08:46.500
# 做的有點醜
They look a bit awful.

0:08:46.760,0:08:47.380
# 沒辦法
Anyway...

0:08:47.820,0:08:50.840
# 這個肉圓做好啦  這個釀豆腐也釀好啦
The meat balls are ready. The stuffed tofu are also ready.

0:08:51.120,0:08:53.800
# 這個豆腐我們用來nai一下  就是紅
The tofu can be "nai". That means, bray,

0:08:53.800,0:08:55.720
# 就是紅  就是意思就是紅燒一下
that means bray, I mean, that means braise it.

0:08:56.040,0:08:57.040
# 這個就蒸出來
And this is to be steamed.

0:09:02.760,0:09:04.360
# 你看  這個竹鼠  蒸好啦
Look! The steam bamboo rat, is done now.

0:09:05.760,0:09:06.960
# 一捏就爛掉的這個
It's really soft and delicate, the, 

0:09:07.420,0:09:08.040
# 這皮
the skin.

0:09:08.540,0:09:09.480
# 把它拿到裡面去
Let me put it inside.

0:09:10.980,0:09:14.220
# 我現在  蒸這個  肉圓  這個鼠做的肉圓啊
I now, steam the, meat balls. These are the meat balls made from bamboo rat meat.

0:09:15.520,0:09:16.180
# 燒火
Fire

0:09:22.100,0:09:24.520
# 先把這個  油  倒下去
Let me put the, oil first.

0:09:35.060,0:09:37.900
# 這是雞蛋哦  粘一下  這樣
This is egg. Dip it in, and then...

0:09:51.220,0:09:52.480
# 把這竹笋拿來炒一下
Let me fry the bamboo shoots.

0:10:02.620,0:10:04.200
# 我給那個叔叔阿姨端過去
Let me take it to the uncles and aunties.

0:10:09.000,0:10:11.520
# 這是我們廠裡面最  最胖的竹鼠
This is the fattest, fattest bamboo rat at my site.

0:10:11.900,0:10:13.260
# 把它做成了烤竹鼠
I make a roast bamboo rat with it.

0:10:13.780,0:10:15.120
# 叫做"鼠來寶"
It's called "Fortune Comes with Rat".

0:10:16.540,0:10:18.380
# 你看  可以嘗一下  大家可以嘗一下
Look! Have a try! Feel free to have a try!

0:10:20.920,0:10:23.380
# 哎呀  靚哦  哈哈哈哈
Aya! It's beautiful! Ha ha ha ha!

0:10:26.720,0:10:27.280
# 嘗一下
Have a try!

0:10:40.400,0:10:41.420
# 好香哦
It smells so good!

0:10:42.760,0:10:44.900
# 很香的哦  這個哦  烤起來很香
It smells really good. It's, it's really nice when it's roasted.

0:10:45.460,0:10:47.420
# 今天我把它切碎了  切碎了就好吃一點
I have chopped it into small pieces today. You can enjoy it better in small pieces.

0:10:48.160,0:10:50.080
# 太大塊了就不好搞了
It's hard to deal with when it's too big.

0:10:53.440,0:10:55.140
# 竹鼠肉  竹鼠肉
Bamboo rat meat, bamboo rat meat.

0:10:55.140,0:10:55.920
# 是不是竹鼠啊  (註︰我好像聽到「係唔係土輪呀」)
Is it bamboo rat?

0:10:55.920,0:10:56.800
# 是竹鼠肉  這個
Yes, bamboo rat meat. It is.

0:10:59.160,0:11:01.200
# 竹鼠  普通話叫竹鼠
"Zhu shu". It's called "zhu shu" in mandarin.

0:11:06.600,0:11:08.180
# 這個叫"竹林一鍋端"
This is called "Bamboo Forest in a Pot".

0:11:08.580,0:11:10.000
# 竹笋炒竹鼠
Bamboo rat fried with bamboo shoots

0:11:10.420,0:11:11.840
# 你看  很漂亮哦
Look! It's so pretty.

0:11:12.960,0:11:15.080
# 還炒  炒竹笋誒
It's fried, fried bamboo shoots.

0:11:15.080,0:11:16.680
# 誒呀  看著就好吃哦
Eya! It looks really delicious.

0:11:17.580,0:11:21.400
# 吃吃吃 竹鼠炒竹笋  特  肯定很好吃的
C'mon! Get some! Bamboo rat fried with bamboo shoots. It must be very tasty.

0:11:25.740,0:11:26.480
# 好香好香
Wonderful! Wonderful!

0:11:28.660,0:11:31.400
# 笋子啊  笋子啊  好吃哦  好香哦
Bamboo shoot, bamboo shoots It's really tasty, really nice!

0:11:42.200,0:11:43.820
# 這個是"心有所鼠"
This is "Rat in Your Heart".

0:11:44.420,0:11:45.680
# 竹鼠肉釀豆腐
Stuffed tofu with bamboo rat meat

0:11:46.260,0:11:48.680
# 很好吃的哦  這是我們這邊的特色菜
It's really tasty. This is a specialty at our place.

0:11:49.520,0:11:52.220
# 把 把竹鼠肉釀在豆腐的心裡面
The, the bamboo rat meat is stuffed into the tofu.

0:11:52.600,0:11:53.720
# 來  很好吃的
C'mon! It tastes really good.

0:11:54.220,0:11:54.800
# 嘗一下
Have a try!

0:11:56.660,0:11:57.240
# 好
Good!

0:11:59.860,0:12:01.260
# 這個是
This is...

0:12:01.260,0:12:03.180
# 豆腐  豆腐  這個豆腐
Tofu, tofu, this is tofu.

0:12:03.620,0:12:04.900
# 老人家多吃點這個
Elderly may have a bit more of it.

0:12:04.900,0:12:06.400
# 還有特色這個菜哦
This dish is quite special.

0:12:06.400,0:12:06.900
# 比較嫩
It's rather tender.

0:12:12.380,0:12:13.720
# 豆腐都可以吃的動的
Chewing tofu shouldn't be a great problem.

0:12:21.100,0:12:23.680
# 這個  竹鼠肉圓  鼠年團圓
This is, bamboo rat meat balls. "Reunion in the Year of Rat".

0:12:24.460,0:12:26.020
# 可以嘗一下這個  竹鼠肉做的
Feel free to have a try. It's made from bamboo rat meat.

0:12:31.360,0:12:32.480
# 嘗一下  嘗一下
Have a try! Have a try!

0:12:32.760,0:12:33.660
# 哎呀  好硬哦
Aya! It's hard!

0:12:37.800,0:12:38.480
# 可能冷了
It might have cooled down.

0:12:43.780,0:12:44.580
# 好香好香
It's really really good!

0:12:44.580,0:12:46.020
# 吃  可以嘗一點
Yup!
You can have a try!

0:12:57.720,0:13:00.320
# 這個  白切鼠條  這是白切竹鼠
This is, steamed bamboo rat strips. This is steamed.

0:13:02.300,0:13:03.140
# 要蘸醬吃
It's eaten with the sauce.

0:13:03.140,0:13:04.480
# 哇  這個是白切的是吧
Wa! You mean it is steamed?

0:13:05.960,0:13:06.580
# 太好啦
Bravo!

0:13:07.760,0:13:09.860
# 這個要蘸醬  這個要蘸醬  醬料
It's to be eaten with the sauce, with the sauce. 
The sauce.

0:13:11.680,0:13:15.480
# 太好啦  這個  這個  白切的  白的  竹鼠  (註︰我想他不是真的想說白色的竹鼠吧)
It's simply marvelous! It's, it's steamed, plain bamboo rat.

0:13:17.040,0:13:18.140
# 來  嘗一下
C'mon! Have a try!

0:13:25.320,0:13:26.940
# 嗯  可以
Um! Not bad!

0:13:32.920,0:13:34.500
# 這個是竹鼠火鍋哦
This is bamboo rat hot pot.

0:13:34.780,0:13:36.180
# 就用竹鼠湯的湯底
The soup base is bamboo rat soup.

0:13:36.740,0:13:38.160
# 所以叫"湯姆和杰瑞"
So it's called "Tom and Jerry" (Note: "Soup" in Chinese sounds like "Tom".)

0:13:38.740,0:13:41.480
# 很好喝的  老人家多喝點這個湯  對身體很好
It's really tasty. Elderly may have more. It's good for the body.

0:13:41.640,0:13:43.320
# 很補的  多吃點
Have more! It's good for the health.

0:13:44.680,0:13:46.820
# 對對對對  可以  可以嘗一下
Yea yea yea yea. You can, you can have a try.

0:13:56.060,0:13:57.640
# 不要肉  不要肉  不要肉
No meat. No meat. No meat.

0:13:57.640,0:13:58.140
# 舀一下湯
Have some soup.

0:13:58.140,0:13:59.480
# 嗯  舀湯  舀湯
Um! Soup, soup.

0:14:03.780,0:14:06.540
# 誒  老人家喝了再活九十五歳 啊
Eh! After having this soup, elderly can live another ninety five years, you know.

0:14:14.320,0:14:16.300
# 你看  這個"鼠香門弟"  這個
Look! This is "Family of Scholar Rats". This is,

0:14:16.580,0:14:17.640
# 竹鼠肉煲黃豆
bamboo rat and soy bean stew.

0:14:19.140,0:14:20.080
# 這個  很好吃的哦
This is, really tasty.

0:14:20.560,0:14:21.360
# 大家可以吃一下
Feel free to take some!

0:14:22.620,0:14:24.700
# 嗯 這個是湯  這竹鼠湯  對
Um! This is soup, bamboo rat soup, yep!

0:14:26.260,0:14:29.340
# 這個竹鼠稍微胖一點的  我把它做成了紅燒竹鼠
This bamboo rat is a bit fat. So I make a braised bamboo rat with it.

0:14:31.100,0:14:31.800
# 很靚啊
It's beautiful!

0:14:33.180,0:14:35.760
# 大家先吃  先吃一點  吃一點  都餓啦
You can eat first. Eat some, c'mon. You're hungry now.

0:14:36.660,0:14:40.900
# 今年是鼠年啊  祝大家鼠年健康  萬事如意
This year will be the year of Rat. I wish you good health in the year of Rat, and every prayer answered.

0:14:46.620,0:14:48.160
# 誒 謝謝  謝謝  謝謝  謝謝
Eh? Thank you! Thank you, thanks!

0:15:09.220,0:15:12.260
# 很多年輕人覺得給老人一些錢就是最好的
Many young people think that giving money to the elderly is the best way to show our care.

0:15:12.260,0:15:15.200
# 其實不是哦  老人們 他{她}們需要陪伴
But in fact it's not true. The elderly needs companionship.

0:15:15.820,0:15:18.660
# 給他們做一頓飯  給他們買一買新衣服那些
Cooking them a meal, or like, buying new clothes with them,

0:15:19.060,0:15:21.800
# 還有 回家  陪他們過個年
also, going back home, spending the new year with them,

0:15:22.180,0:15:25.700
# 這個是  其實  老人家是  最需要這  最需要的
this is, in fact, what the elderly needs, needs the most.

0:15:26.560,0:15:29.040
# 好啦  今天的視頻到這裡啦  快過年啦
Alright! The video ends here. The Chinese New Year is around the corner,

0:15:29.320,0:15:31.980
# 大家都回去陪陪自己的家人吧
let's go back home and spend time with our family.

**Comment by vincenthychow** [comment]
已發佈
