### ISSUE TITLE
【美食作家王刚】坝坝宴 - https://youtu.be/3V9fkm4wZN0

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#611]
【美食作家王刚】坝坝宴 - https://youtu.be/3V9fkm4wZN0
视频时长 3:19，预计发布时间为北京时间1月26日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.425,0:00:01.119
哈喽大家好

0:00:01.410,0:00:04.277
我们这个地方过年的这个气氛还是不错的

0:00:05.039,0:00:08.040
有很多粉丝想看一下我们这个农村坝坝宴是什么样子的

0:00:08.040,0:00:10.167
今天我就带大家去看一下

0:00:10.615,0:00:16.438
让在城里的一些没见过的朋友来了解一下我们乡村文化

0:00:21.746,0:00:23.426
这个是我们炸好的鱼

0:00:23.762,0:00:25.957
这一边是青菜（花菜）焯好水的

0:00:26.091,0:00:28.891
这个的话是泥鳅烧的耙泥鳅

0:00:29.048,0:00:33.213
然后这个是现搭的一个炉灶

0:00:33.437,0:00:39.328
你看下面全是用砖搭起来的围起来的中间烧的是炭火

0:00:39.798,0:00:50.011
里面蒸的是扣肉还有粑粑肉还有一些蒸菜有排骨酥肉这些

0:00:50.257,0:00:53.102
我们这个位置是专门摆放凉菜的地方

0:00:53.303,0:00:58.833
这些虾呀凉菜呀还有一些甜品呀就是饭前甜品全部摆在这个地方

0:01:05.307,0:01:09.518
这个是我们邻居家的妈妈满80岁过寿宴

0:01:09.944,0:01:12.430
所以我们这里摆了坝坝宴

0:01:12.922,0:01:17.834
你看人山人海的这上面有7-8桌

0:01:18.253,0:01:19.686
摆了7-8桌这上面

0:01:20.179,0:01:22.844
下面我们家的坝子里面摆了10多桌

0:01:23.001,0:01:25.487
过年了大家都回来聚在一起

0:01:26.472,0:01:29.921
这个气氛非常的融洽

0:01:30.459,0:01:32.967
也只有过年的时候才能有这种机会

0:01:33.594,0:01:35.453
我觉得也特别不容易

**Comment by vincenthychow** [comment]
bot, please upload
0:00:00.425,0:00:01.119
哈喽大家好
Hi everyone!

0:00:01.410,0:00:04.277
我们这个地方过年的这个气氛还是不错的
The atmosphere of the Chinese New Year here at our place is really not bad.

0:00:05.039,0:00:08.040
有很多粉丝想看一下我们这个农村坝坝宴是什么样子的
Many fans want to see how the "Ba Ba Banquet" looks like in our village.

0:00:08.040,0:00:10.167
今天我就带大家去看一下
Let me show you today,

0:00:10.615,0:00:16.438
让在城里的一些没见过的朋友来了解一下我们乡村文化
and let those in the cities know more about our rural culture.

0:00:21.746,0:00:23.426
这个是我们炸好的鱼
These are the deep fried fish.

0:00:23.762,0:00:25.957
这一边是青菜（花菜）焯好水的
And the vegetables here have already been boiled.

0:00:26.091,0:00:28.891
这个的话是泥鳅烧的耙泥鳅
And what you see here is "ba niqiu" (Note: Niqiu = loach)

0:00:29.048,0:00:33.213
然后这个是现搭的一个炉灶
And then here is a temporary stove.

0:00:33.437,0:00:39.328
你看下面全是用砖搭起来的围起来的中间烧的是炭火
Have a look at the brick-built base surrounding the fire in the middle.

0:00:39.798,0:00:50.011
里面蒸的是扣肉还有粑粑肉还有一些蒸菜有排骨酥肉这些
Inside the stove are steamed pok belly, ribs and some other stuffs.

0:00:50.257,0:00:53.102
我们这个位置是专门摆放凉菜的地方
This place is reserved for cold dishes (appetizer).

0:00:53.303,0:00:58.833
这些虾呀凉菜呀还有一些甜品呀就是饭前甜品全部摆在这个地方 (註︰留意這裡的甜品不能用Dessert，因為Dessert其實是指最後一道菜)
The shrimps, cold dishes and the sweet dishes, I mean the sweet dishes served before the meal, are all placed here.

0:01:05.307,0:01:09.518
这个是我们邻居家的妈妈满80岁过寿宴
This is the 80th birthday banquet of our neighbour's mother.

0:01:09.944,0:01:12.430
所以我们这里摆了坝坝宴
That's why we have a "Ba Ba Banquet" here.

0:01:12.922,0:01:17.834
你看人山人海的这上面有7-8桌
Look! There are so many people. There are around 7-8 tables here.

0:01:18.253,0:01:19.686
摆了7-8桌这上面
7-8 tables here.

0:01:20.179,0:01:22.844
下面我们家的坝子里面摆了10多桌  (註︰不知甚麼壩)
There are another dozen of tables down there on our dam.

0:01:23.001,0:01:25.487
过年了大家都回来聚在一起
It will soon be the Chinese New Year so everybody is back.

0:01:26.472,0:01:29.921
这个气氛非常的融洽
It's full of harmony.

0:01:30.459,0:01:32.967
也只有过年的时候才能有这种机会
It's not quite possible if it's not the Chinese New Year.

0:01:33.594,0:01:35.453
我觉得也特别不容易
This is really a precious moment.
