### ISSUE TITLE
[华农兄弟] 华农兄弟看一下兄弟家的甘蔗顺便砍点来尝下再去砍一把香蕉 - https://youtu.be/C7x5-4poiyQ

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#616]
https://youtu.be/C7x5-4poiyQ
<p>&#35270;&#39057;&#21457;&#24067;&#20110; January 27, 2020 at 01:40PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/C7x5-4poiyQ

#华农兄弟：看一下兄弟家的甘蔗，顺便砍点来尝下，再去砍一把香蕉
#Huanong Brothers: We take a look at our buddy's sugar canes, get some and have a try. And then we get a bunch of bananas.

0:00:00.180,0:00:02.460
# 大家好  今天天氣好冷哦
Hi everyone! It's freezing today.

0:00:02.500,0:00:04.720
# 我去看一下兄弟家的甘蔗有沒有砍完
I'm gonna have a look at my buddy's sugar canes and if there are still any.

0:00:04.960,0:00:07.620
# 上次看到他開了幾輪拖頭(車)在那裡哦
Last time I saw him having several trucks over there.

0:00:08.820,0:00:10.380
# 不知道有沒有沒砍掉的
I wonder if there are still any.

0:00:12.400,0:00:13.300
# 鴨子
Duckies!

0:00:14.360,0:00:15.440
# 小鴨子
Little duckies!

0:00:28.120,0:00:31.420
# 你看兄弟家的大棚  裡面還有好多哦
Look! These are my buddy's sheds. There are still a lot inside.

0:00:31.520,0:00:33.020
# 這邊就已經砍完啦
Those on this side have already been chopped.

0:00:49.220,0:00:53.300
# 你看   那麼多甘蔗都不砍  放在這裡好多哇
Look! Here are so many sugar canes. My buddy didn't chop them.

0:00:53.900,0:00:55.740
# 我找一根  找一根最小的來
Let me get a, get a smallest one,

0:00:56.480,0:00:57.120
# 嘗一下
and have a try.

0:01:11.380,0:01:11.940
# 這根
This one!

0:01:12.980,0:01:14.660
# 這根長得不好看
This one doesn't look good.

0:01:15.500,0:01:16.120
# 最小
It's the smallest.

0:01:17.140,0:01:18.400
# 剛好帶了一把刀過來
It just so happens that I have a knife with me,

0:01:18.800,0:01:19.740
# 我家的菜刀
my kitchen knife.

0:01:31.860,0:01:32.740
# 哎呀
Aya!

0:01:32.980,0:01:35.620
# 這甘蔗就好吃啦  這種甘蔗
This sugar cane is really tasty, you know.

0:01:36.780,0:01:38.520
# 味道肯定很好
A good taste is ensured.

0:01:42.080,0:01:44.600
# 哎呀 好重  這根甘蔗差不多10斤哦
Aya! So heavy! This sugar cane is almost five kilograms.

0:01:45.140,0:01:46.000
# 那麼重
It's so heavy!

0:01:51.420,0:01:52.260
# 這甘蔗
This sugar cane...

0:01:53.540,0:01:55.160
# 嘗一下  看味道怎麼樣
Let me have a try, and see how it tastes.

0:01:55.620,0:01:58.400
# 你看  這個結頭那麼多  肯定不靚哦
Look! There are so many buds. It can't grow beautifully.

0:01:59.380,0:02:02.340
# 幫兄弟 幫兄弟吃掉  這結得太多啦
Let me get rid of it, get rid of it for my buddy. There are too many buds.

0:02:08.240,0:02:09.120
# 你看  削好啦
Look! It's alright now.

0:02:14.360,0:02:15.260
# 嗯  可以
Um! Not bad!

0:02:16.580,0:02:17.520
# 這個味道可以
It's a good taste.

0:02:21.300,0:02:22.320
# 不過有點硬
But it's a bit hard.

0:02:24.720,0:02:25.900
# 我帶回家裡去吃
I bring it back home.

0:02:45.680,0:02:47.280
# 來都來啦 搞一根
I'm already here. How can I just take one?

0:02:48.340,0:02:50.780
# 搞兩根來 好事要成雙
Let me get two. Good things should come in pairs.

0:02:52.100,0:02:53.180
# 你看  這根比較小
Look! This one is rather small.

0:02:53.940,0:02:54.820
# 這根砍啦
I'll take it.

0:02:57.840,0:02:58.580
# 拿著
Hold it!

0:03:00.660,0:03:02.240
# 要不要吃  可以吃一點
Do you want it? You can have some.

0:03:44.540,0:03:46.400
# 好啦  好啦  不要啦  我都背不起啦
Alright, alright! Enough! It's already too heavy for me.

0:03:58.040,0:03:59.000
# 現在我們回去啦
We're heading back now.

0:04:26.980,0:04:28.060
# 刀又沒帶
I left my knife at home.

0:04:45.420,0:04:46.140
# 這香蕉
The bananas,

0:04:47.180,0:04:47.900
# 很靚的哦
are really beautiful!

0:04:48.580,0:04:49.720
# 可以不是很大
Though they're not that big.

0:04:50.840,0:04:51.740
# 把它砍回去
Let me take it back home.

0:04:54.780,0:04:56.500
# 你看  這個香蕉樹都死掉啦
Look! This banana tree is already dead.

0:04:57.180,0:05:00.020
# 我把這個香蕉帶回家裡去
I'm gonna take the bananas home.

0:05:01.180,0:05:02.020
# 太小啦
They're too small.

0:05:02.660,0:05:04.340
# 反正都死啦  我拿那個
It's dead anyway. Let me,

0:05:04.920,0:05:06.220
# 用鋤頭把它搞一來
take it down with a hoe.

0:05:09.980,0:05:11.860
# 這個鋤頭把它鏟下來
I'll chop it down with this hoe.

0:05:34.420,0:05:35.760
# 這個搞不開
I can't break it here.

0:05:36.000,0:05:36.940
# 我回去拿刀
Let me fetch a knife.

0:05:37.880,0:05:39.200
# 回去拿一把刀過來
Let me fetch a knife first.

0:05:40.460,0:05:41.720
# 搞這樣了  搞不下
It's impossible otherwise.

0:05:42.120,0:05:45.440
# 帶了一把刀過來  沒找到小刀  就找到這把  (註︰這把也不大，我想他的「小刀」是指水果刀之類的吧)
So I'm back with a knife. I can't find a paring knife, only this one.

0:05:46.760,0:05:47.440
# 這個刀
This knife,

0:05:48.240,0:05:49.540
# 就把你卸(註︰應該是「切」)下來
is enough to cut you off.

0:05:51.900,0:05:52.680
# 很鋒利呀
It's really sharp!

0:05:53.400,0:05:54.280
# 哎呦
Ayo!

0:05:55.520,0:05:56.940
# 香蕉都被切走一半
Half of the banana is cut away.

0:06:00.340,0:06:02.920
# 我把它抬回家  放在那裡  看會不會熟
I'll bring it back home, put it there and see if it will ripen.

**Comment by vincenthychow** [comment]
已發佈
