### ISSUE TITLE
[老饭骨] 丰收棒子鱼 - https://www.youtube.com/watch?v=PeIY_FTyhIA

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#620]
https://www.youtube.com/watch?v=PeIY_FTyhIA

视频发布于 2020 年 1 月 27 日，时长 10:09

**Comment by Losskywalker** [comment]
bot, please upload

【老飯骨家宴•豐收棒子魚】形如玉米，外焦裏嫩的“榴蓮芒果魚”，廚王爭霸拿獎菜揭秘！|老飯骨 
Titie:[Family dinner of Lao Fan Gu-Corn Fish] A fish dish with Durian and Mango but looks like corn. Crispy outside and tender inside. The secret behind a prize-winning dish! |Lao Fan GU

0:00:00.000,0:00:03.740
Corn fish
(aka. Gold & Jade)

0:00:04.295,0:00:06.295
Happy new year!

0:00:06.295,0:00:09.000
That's the traditional gesture for the new year

0:00:09.000,0:00:09.925
(Gang, what are you cooking today?)

0:00:10.000,0:00:12.840
I'm cooking the corn fish today

0:00:12.980,0:00:13.900
aka. Gold & Jade

0:00:14.400,0:00:15.520
What a nice name

0:00:15.520,0:00:16.580
Your master is right next to you

0:00:16.980,0:00:18.120
Everything's under control. 

0:00:18.460,0:00:19.460
Alright

0:00:19.840,0:00:20.840
What kind of fish is it?

0:00:21.040,0:00:22.040
Cao Yu(Grass carp)

0:00:22.300,0:00:25.260
Known as Cao Yu in Northern China
Wan Yu in the South.

0:00:25.840,0:00:27.080
It's all up to your knife skills today.

0:00:27.400,0:00:29.040
Look at all him. 

0:00:29.260,0:00:31.540
How professional!

0:00:31.840,0:00:33.260
Look, all the bones are removed.

0:00:33.380,0:00:34.280
Time to shape it with my knife.

0:00:34.640,0:00:38.160
Huan, we are putting your knife skills to a test today

0:00:38.620,0:00:39.620
Slice it vertically

0:00:40.040,0:00:43.140
It has to resemble the shape of a corn seed

0:00:43.840,0:00:44.940
Don't cut through

0:00:45.440,0:00:46.860
You should not slice through the skin.

0:00:47.440,0:00:48.500
Oil in to the wok.

0:00:48.940,0:00:51.180
I used to cook this dish when I was in a competition.

0:00:51.300,0:00:52.700
Did you win though?

0:00:53.440,0:00:55.080
I did, I did!

0:00:56.620,0:00:57.980
The hidden history!

0:00:58.520,0:00:59.800
You didn't win because your master was not there helping you.

0:01:00.100,0:01:01.920
That's so true!

0:01:02.140,0:01:06.120
He actually participated in the competition several times.

0:01:06.740,0:01:08.440
And he won!

0:01:08.440,0:01:10.380
Later, you know, he went abroad to compete

0:01:10.520,0:01:12.840
So many master chefs from 5-star hotels did't make it in the competition.

0:01:12.920,0:01:14.640
He was the only one to end up with a draw.

0:01:14.640,0:01:16.640
Why is that?

0:01:17.280,0:01:20.140
He changed his strategy to cooking western dishes. Just like other chefs.

0:01:20.520,0:01:22.660
It was too difficult to judge. So it was a draw.

0:01:22.860,0:01:24.240
50-50

0:01:24.240,0:01:26.040
So, did you realize?

0:01:26.260,0:01:28.560
It's the year of the rat this year

0:01:28.560,0:01:30.260
Rats are smart
(Just like Er Bai)

0:01:30.340,0:01:33.040
He was smart to change his strategy.

0:01:33.040,0:01:35.420
You have to slice it evenly.

0:01:36.260,0:01:39.300
Not only the thickness has to be even

0:01:39.300,0:01:42.260
What' important is that the skin has to stay intact.

0:01:43.200,0:01:45.980
Slice as close as touching the skin.

0:01:46.120,0:01:49.195
Without breaking the skin. That's the point.

0:01:50.240,0:01:52.580
Why do you only cut it vertically?

0:01:52.640,0:01:55.980
Firstly to make it look like corn seeds.

0:01:56.180,0:01:58.840
Secondly, it was easier.

0:01:59.580,0:02:00.900
What's the most important?

0:02:01.560,0:02:02.840
The most important is...

0:02:03.420,0:02:04.360
(No pressure)

0:02:04.360,0:02:06.040
Do you know what's most important?

0:02:06.040,0:02:07.820
We have a different style than Da Ye.

0:02:07.820,0:02:09.960
Da Ye does it at an angle

0:02:10.340,0:02:11.680
We slice it vertically.

0:02:11.685,0:02:14.095
If he goes vertical, then we will take an angle.

0:02:14.645,0:02:16.465
You have to be different from Da Ye

0:02:16.855,0:02:19.665
Don't listen to Da Ye

0:02:19.665,0:02:23.320
We have to be smart in the year of Rat.

0:02:27.020,0:02:28.860
Both of you are smart!

0:02:29.120,0:02:31.000
(He's not your real master)

0:02:32.300,0:02:34.800
then he is better than my real master.

0:02:35.340,0:02:37.520
You see, he tricked you again.

0:02:37.660,0:02:39.160
 You became my student after with an officially ceremony.

0:02:39.160,0:02:40.080
How come that I'm not your real master?

0:02:40.440,0:02:43.040
He tricked you again.

0:02:43.960,0:02:45.700
I wasn't smart enough for that.

0:02:45.700,0:02:46.640
Yet I am your real Da Ye (Grandmaster)

0:02:48.840,0:02:50.280
The grandmaster is always the grandmaster

0:02:52.555,0:02:55.465
There comes the corn shape

0:02:55.465,0:02:57.260
A big one and a small one

0:02:57.560,0:02:59.320
Here we go

0:02:59.320,0:03:01.640
Fish for fortune! 

0:03:01.640,0:03:03.500
Gold and Jade everywhere!

0:03:03.640,0:03:04.720
The corn fish!

0:03:04.720,0:03:05.880
First, marination .

0:03:06.140,0:03:08.500
Rice wine, and salt

0:03:10.220,0:03:11.220
A bit of pepper

0:03:12.840,0:03:14.040
Not to much

0:03:14.120,0:03:17.560
Our own rice wine. （just a little bit, you don't want the color in it）

0:03:17.700,0:03:19.260
Smells good!

0:03:19.260,0:03:20.760
(Too much?) It's OK.

0:03:20.760,0:03:22.060
It's not too much

0:03:22.060,0:03:24.740
This is a traditional dish

0:03:24.960,0:03:26.280
Passed down for generations.

0:03:26.600,0:03:28.400
But between us three generations

0:03:28.740,0:03:30.800
There's a special meaning in the traditional dish.

0:03:30.920,0:03:35.980
Skill wise, it is an old dish. But there is something new

0:03:36.320,0:03:37.875
New in what?

0:03:37.875,0:03:40.485
Check the sauce out

0:03:40.485,0:03:42.675
There's Durian and Mango in it

0:03:43.440,0:03:45.800
Now that's special

0:03:45.800,0:03:49.520
It's a new flavor for this dish in Beijing.

0:03:49.520,0:03:52.780
So it is "Durian-Mango fish".

0:03:52.780,0:03:53.760
That's a bad name!

0:03:54.360,0:03:55.680
Think of a better name.

0:03:55.820,0:03:58.700
Durian-Mango-Corn fish.

0:03:58.900,0:04:02.560
it's almost a tongue twister!

0:04:03.240,0:04:04.240
That's high heat

0:04:05.000,0:04:07.400
That's ready

0:04:07.820,0:04:09.340
That's how you coat it with starch

0:04:09.340,0:04:11.400
What's that technique?

0:04:11.940,0:04:19.240
The idea is to first marinate  it before coating it with starch.

0:04:19.740,0:04:21.140
Dry it, then coat it.

0:04:21.500,0:04:27.395
We didn't dry it, we coat it directly with starch

0:04:27.400,0:04:28.420
Straight out of marination.

0:04:29.100,0:04:32.240
It's a special technique called "Jiao Liu"

0:04:32.420,0:04:35.780
But "Jiao Liu" needs a wet batter

0:04:35.780,0:04:37.720
Here we go.

0:04:39.120,0:04:40.120


0:04:40.840,0:04:44.320
Oil temperature at around 200~240°C

0:04:44.580,0:04:47.480
Something like 180~240°C

0:04:47.520,0:04:49.440
That's like an old corn!

0:04:52.560,0:04:54.380
It fits perfectly in the Chinese new year

0:04:54.545,0:04:56.985
It has a golden color.

0:04:56.985,0:04:59.715
The corn represents a good harvest.

0:04:59.715,0:05:02.155
It has a sweet-sour flavor. Crispy on the outside but tender inside.

0:05:02.745,0:05:06.035
With Mango and Durian.

0:05:06.355,0:05:09.385
It used to be named "Grape fish"

0:05:09.985,0:05:13.085
Be extra careful if you cook it at home.

0:05:13.085,0:05:16.420
It needs to be deep-fried. 

0:05:19.460,0:05:21.060
It's almost like frying dough by Da Ye

0:05:22.335,0:05:23.545
I like the deep-fried dough made by Da Ye

0:05:27.745,0:05:29.895
Seasoning is the key!

0:05:30.400,0:05:32.440
Seasoning is the key!

0:05:35.820,0:05:38.740
What's this step? Making the sauce?

0:05:38.860,0:05:40.700
Let's prepare the sauce

0:05:40.700,0:05:42.940
Some water

0:05:43.900,0:05:46.940
Plain water in, to make the sauce.

0:05:47.540,0:05:49.860
So first we will make a sweet base? Right!

0:05:49.940,0:05:51.460
You need salt to bring out the sweetness

0:05:52.960,0:05:54.800
I learnt it from my master

0:05:54.800,0:05:56.100
OK that's enough salt.

0:05:57.680,0:06:00.540
Do you need starch? Yes!

0:06:00.540,0:06:04.880
OK now the sauce. The Lemon-Durian-Mango sauce is in.

0:06:05.100,0:06:05.600


0:06:06.600,0:06:08.580
You need to prepare this beforehand.

0:06:09.880,0:06:13.320
OK now we add starch.

0:06:13.700,0:06:14.540
What starch are you using? Corn or potato starch.

0:06:14.680,0:06:16.680
Everyone, remember to use corn or potato starch

0:06:17.560,0:06:19.460
Starch in

0:06:19.865,0:06:20.865
Turn off the heat

0:06:21.640,0:06:22.140


0:06:24.280,0:06:25.380
There are bubbles.

0:06:26.920,0:06:28.640
Family dinner of Lao Fan Gu.

0:06:29.000,0:06:35.340
See? The sieve gets rid of the lumps and  makes the sauce really fine.  

0:06:36.740,0:06:38.840
A little bit of oil.

0:06:39.780,0:06:41.620
The oil is cold

0:06:42.740,0:06:43.740


0:06:44.800,0:06:47.800
The fish please! Here it is!

0:06:48.140,0:06:50.580
The sauce is very bright!

0:06:51.640,0:06:53.955
I learnt from the best!

0:06:53.960,0:06:57.460
Good guidance indeed, lovely sauce!

0:06:57.500,0:07:00.505
Who came up with the whole "guidance" thing?

0:07:00.505,0:07:03.360
That's a long story.

0:07:03.365,0:07:05.965
Lovely golden color.

0:07:05.965,0:07:08.685
Pour evenly

0:07:08.685,0:07:10.820
The fruit sauce has a lovely yellow color

0:07:11.040,0:07:13.760
Beautiful! Looks great through the lenses.

0:07:13.800,0:07:14.920
The guidance of Da Ye really helps!

0:07:15.320,0:07:19.400
Golden brown color, crispy on the outside and tender on the inside.

0:07:19.460,0:07:22.060
Sweet and sour flavor. Applause!

0:07:22.860,0:07:26.100
With the guidance of Da Ye, we finished in 30 mins.

0:07:26.280,0:07:28.120
Mission accomplished!

0:07:28.360,0:07:30.940
There's the ear of the corn

0:07:30.945,0:07:32.055
The final touch.

0:07:32.740,0:07:35.400
It's actually just cole.

0:07:35.740,0:07:38.220
Cole can help clean up your mouth after tasting the sweet and sour sauce.

0:07:38.220,0:07:39.400
Thanks master.

0:07:39.720,0:07:41.445
Thanks Xiao Liang

0:07:41.940,0:07:43.860
Thanks, everyone!

0:07:43.960,0:07:47.300
So here it is, the corn fish, aka, Gold and Jade.

0:07:47.305,0:07:50.505
The corn is a god wish for harvest during the Chinese new year.

0:07:50.505,0:07:54.720
Sweet and sour flavor, wishes for a lot of fortune and wealth.

0:07:54.720,0:07:56.880
Golden color, sweet and sour.

0:07:56.900,0:07:59.380
Sweet and beautiful.

0:07:59.380,0:08:02.120
With added fragrance from Durian and Mango

0:08:02.120,0:08:04.020
A traditional dish with innovation.

0:08:04.200,0:08:07.300
Special thanks to my master, and everyone.

0:08:07.700,0:08:09.860
Thank you !

0:08:10.160,0:08:11.260
Let's dig in!

0:08:12.660,0:08:14.540
Let's go!

0:08:15.660,0:08:17.300
Let's try the "seeds" first.

0:08:17.680,0:08:19.000
It smells really good.

0:08:19.680,0:08:22.920
Sour enough? Yes it's sour enough.

0:08:23.080,0:08:25.360
You have to comment on this nice dish.

0:08:25.540,0:08:30.920
So, the dish is called Gold and Jade, it wishes for a beautiful future of our country.

0:08:31.720,0:08:33.740
The prosper of our nation

0:08:33.740,0:08:35.660
The harmony of the families.

0:08:35.840,0:08:37.700
The wealth of our people

0:08:37.920,0:08:39.920
It has all flavors in our lives: sour, sweet, bitter, spicy, salty.

0:08:40.060,0:08:42.080
The five flavors of life.

0:08:42.080,0:08:43.620
What a speech!

0:08:43.780,0:08:45.060
Shall we drink something?

0:08:45.060,0:08:46.700
There's our liquor.

0:08:46.840,0:08:50.100
Good liquor to match the good dish.

0:08:51.580,0:08:53.500
Some more

0:08:54.020,0:08:56.180
OK let's toast together.

0:08:56.840,0:08:57.840


0:08:59.160,0:09:02.560
Let's toast with the whole family.

0:09:02.560,0:09:03.140


0:09:03.240,0:09:04.220


0:09:04.220,0:09:04.760


0:09:05.160,0:09:08.940
Best wishes of the new year to our followers

0:09:09.240,0:09:12.275
what should you eat for the new year?

0:09:12.275,0:09:13.275
The "corn"

0:09:13.285,0:09:16.545
Gold and Jade!

0:09:16.595,0:09:19.775
To health!

0:09:19.775,0:09:22.995
Good job everyone.

0:09:25.980,0:09:29.260
Happy new year to the masters.

0:09:30.700,0:09:33.700
Happy new year

0:09:39.340,0:09:40.060
I am Da Ye

0:09:40.240,0:09:40.840
I am Er Bai

0:09:41.100,0:09:41.700
I am San Shu

0:09:41.940,0:09:44.540
We are Lao Fan Gu

0:09:44.540,0:09:47.835
Please subscribe to our YouTube Channel

0:09:47.835,0:09:50.215
We are here to teach you how to cook.

0:09:50.215,0:09:53.225
And to share with you some little tips. Hope you like them.

0:09:53.225,0:09:56.300
We that hope everyone around the world likes our videos.

0:09:56.940,0:09:59.640
Subscribe to our channel, and click the reminder bell.

0:09:59.640,0:10:02.000
Here, we wish everyone

0:10:02.700,0:10:04.700
A lot of happiness and fortune in the coming new year!

**Comment by shuaisoserious** [comment]
丰收棒子鱼
金玉满堂
过年了过年了
兄弟们过年好
你看这老礼 
过年了
刚子
今天做什么菜啊
今天咱做一个丰收棒子鱼
也叫金玉满堂
这名起的好啊
师父在旁边呢
有谱了
好
这是什么鱼
草鱼
北方叫草鱼
南方叫皖鱼
欢子看你刀工了啊
看看我们的师弟啊
这也太专业了
看啊
鱼刺都剔完了
该改刀了啊
欢子今天你的刀功
可就要考验你了
直来直下
因为要体现出它的玉米粒来
形状
不能断啊
把皮刺破了就麻烦了
烧油
前两年我参加厨王争霸时候做过这道菜
也没有拿到奖吧
拿奖了 拿了啊
揭底了
没拿奖师傅肯定没在
你看我净说实话了
这小魏参加厨王争霸打了几次擂
而且还全部都赢了
后来你知道吗
就上国外去打擂了
所有的五星级酒店的大厨全输了
就小魏一人打平了
这小魏为什么打平了呀
小魏临时变阵
我做西餐了 跟你们一样
这老外没法评了
得的分都一样
打一个平手
所以说你看到没有啊
今年这不是鼠年嘛
鼠年就贼啊
风格有点像二伯
贼啊
临时变了
刀功得粗细一致啊
你不能说光粗细一致
关键是什么呀
他不能把这皮给剌断了是不是
得深到什么时候啊
贴到皮
但皮还不能剌
就达到目的了 是不是
小魏为什么选择 全是直刀法啊
直刀第一个
它出来就跟玉米的形状是一样的
第二这操作比较便捷
最关键是什么呀
最关键是
你得说对了
最关键的最关键是什么 你知道吗
跟大爷不是一门派
大爷是唰唰唰 坡着
咱就得玩直的
他玩直的咱就得玩斜的
所以说千万别跟他一样A股
小魏啊 你千万别上你大爷的当
今年是鼠年了啊
用的全是计谋啊你知道吗
大爷和我师父都是大智慧
你的师父不是你的亲师父
胜似我的亲师父
你又上了他的道了吧
你是磕头的徒弟
怎么不是亲师父呢
你就上了他的道了
还是师父转得快
我是你的亲大爷啊
你大爷还是你大爷
老玉米出来了啊
出来了啊
一个大玉米一个小玉米
这就起来了啊
年年有余
金玉满堂
丰收棒子鱼
先腌味
料酒
对 盐
胡椒粉来点
千万得少
老饭骨的黄酒来一点
太多了上色
香香的 香香的
多了 不多不多
棒子鱼是个老菜
是个传承的菜
但是你看我们祖孙三代
带有传承的意义 为什么啊
你看这个菜啊 手法上是个老菜
但是又是个新菜
新菜新在哪儿呢
你看到没有 这是打好的汁
里面有榴莲有芒果
所以说这个汁非常好
这个就是一个新的口味出现了
在北京诞生了
什么鱼 榴芒鱼
不能叫榴芒鱼
小魏给起一个名字
榴莲芒果棒棒鱼
榴莲芒果棒棒鱼
这有点绕嘴了
这火真旺啊
小魏 这就行
你看这淀粉挂得多好
这个挂淀粉叫什么手法
这个是先上浆等于先给它入味
入完味以后给它拍淀粉
这叫拍淀粉
脱浆 拍粉
咱这个没有脱浆
这没有脱浆 直接就拍粉了
腌好之后就直接拍粉了 
这没脱浆
这属于焦溜做鱼的方法
焦溜还得挂糊呢 还得挂湿糊
下锅了
咱油温得七成
六七成就行
这个老玉米棒子
正好这也是咱们春节了
做这一个菜
颜色金黄
老玉米又代表着丰收 五谷丰登
糖醋口 外焦里嫩
又加入了芒果和榴莲
原名叫葡萄鱼 葡萄鱼
关键在家里炸 要注意安全
这很重要
油量比较大
跟大爷炸的油条一样
我就吃大爷油条
调味是关键啊
调味是关键啊
这一步是什么啊
师兄 该做汁了
我们先把汁浇上
先加点水
加水后 给它打这个玉米汁
这是先熬糖汁吧
要想甜 必加盐
我师父教我定味的
行了 盐够了
有淀粉吗 有淀粉
加汁吧 挂糖汁
柠檬榴莲芒果汁
挂好了
柠檬榴莲芒果汁
这个是提勾兑对好的
好 打芡
用的什么淀粉 生粉
这个里面用生粉啊 网友们
生粉 生粉
把火关了
冒泡了
老饭骨的家宴
这样它就更细了 看到没有全是淀粉
这样你能让它更加细
来点明油
油凉
鱼盘 鱼盘来了
这汁亮堂啊
这师爷和师父指挥的吗
师爷指挥的好 这汁够亮啊
这谁码的坑 啊 这坑下的多大啊
这坑埋的够大的啊
色泽金黄啊
把它浇均匀了
榴芒汁真黄啊
好 漂亮啊 这镜头感漂亮
你师爷一指导就是不一样啊
色泽金黄 外焦里嫩
色泽金黄 外焦里嫩
糖醋口 鼓掌
在师爷的指导下用了30分钟 好
完成了任务 这还有个玉米穗
点睛之笔
大家看看啊 这就是一个油菜
吃完糖醋口了 来一个小油菜清清口
感谢师父
感谢小亮
感谢诸位师兄弟
这个丰收棒子鱼
也叫金玉满堂
在春节的时候啊
玉米也代表着五谷丰登 糖醋口
年年有余的寓意也有了
色彩金黄 口味糖醋
甜甜美美
增加了榴莲和芒果汁的香气
这菜有创新 有传承
感谢我师父 感谢我们大家
感谢大家
开吃
抄家伙
先尝尝玉米粒
香不香 真香
酸不酸 真酸
这么好的菜 您得说说
金玉满堂 象征着我们国家的兴旺
民族的振兴 家族的和谐
人民的富裕 甜甜美美
有酸甜苦辣咸
人生五味
光说好了
那喝点什么
酒 这摆着酒呢
喝不喝啊 喝
好酒配好菜 倒上
再来点
来来来 我们一起来
全家福啊 我们一起来
我们的粉丝在春节来临之际
做什么菜 吃什么菜
吃棒子 吃老玉米
金玉满堂 健康啊
健康啊
粗纤维啊
家人们都辛苦了
给师父和二伯拜个年
过年了
我是大爷
我是二伯
我是三叔
我们是老饭骨
欢迎大家订阅
我们老饭骨youtube频道
我们老饭骨组合
就是教大家做菜
传授一些精kan的小厨艺
希望大家喜欢
希望全球的美食爱好者喜欢我们
订阅我们的频道
点亮我们的小铃铛
同时在这里我们祝全球的华人
万事如意 恭喜发财

**Comment by immoonancient** [comment]
已发布
