### ISSUE TITLE
[美食作家王刚] 苦瓜煎蛋饼 - https://youtu.be/UjFxgYCLUlQ

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#65]
https://youtu.be/UjFxgYCLUlQ

1.5M 点击热门老视频，考虑补字幕

老同学不用太着急接，让新同学更容易参与

**Comment by heyitstracccy** [comment]
苦瓜煎蛋饼🍳

**Comment by heyitstracccy** [comment]
bot, please upload

![image](https://user-images.githubusercontent.com/57466592/68518952-584e6180-025c-11ea-80c5-6e003893fa11.png)

**Comment by heyitstracccy** [comment]
bot, please upload

0:00:00.520,0:00:01.820
#哈喽大家好我是王刚
hi everyone, this is Wang Gang

0:00:02.020,0:00:04.300
#本期视频我跟大家分享一道家常菜
in this video I'm gonna share with you a homely dish

0:00:04.420,0:00:05.340
#苦瓜煎蛋饼
bitter gourd fried eggs pancake

0:00:05.740,0:00:07.040
#首先我们准备苦瓜一条
first, let's prepare a bitter gourd

0:00:07.520,0:00:09.560
#用清水把苦瓜清洗干净备用
clean it with clear water

0:00:11.600,0:00:13.740
#然后将苦瓜的两头切掉
then remove the stem of bitter gourd on both sides

0:00:15.300,0:00:17.140
#从中间下刀切成两边
cut in the middle and split it in two

0:00:17.660,0:00:19.780
#然后用平刀把苦瓜籽切掉
cut off the bitter seeds in "Ping Dao" (flat cut) technique

0:00:20.060,0:00:23.120
#不会平刀切的朋友也可以用勺子刮干净
you can also use a spoon to shave the seeds off

0:00:24.800,0:00:28.140
#然后再把苦瓜切成2毫米左右的薄片备用
then cut the bitter gourd into 2 cm thin slices

0:00:28.660,0:00:30.460
#苦瓜切得越薄口感就越好
the thinner you cut the slices, the better it tastes

0:00:30.620,0:00:32.940
#这样煎出来的蛋才不会发苦
in this way, the pancake won't be bitter

0:00:33.360,0:00:35.200
#下一步我们开始处理苦瓜
next, let's fight with the bitter gourd

0:00:35.580,0:00:37.580
#首先我们在锅中加入适量的清水
put some water into the wok first

0:00:39.140,0:00:40.740
#开大火把锅里面的水烧开
boil the water with strong fire

0:00:41.580,0:00:43.460
#水烧开之后加入食用盐2克
add 2g salt once the water is boiling

0:00:45.800,0:00:47.500
#加入少许的白糖
add a little sugar 

0:00:49.520,0:00:51.200
#再加入适量的食用油
and the appropriate amount of cooking oil

0:00:52.500,0:00:55.160
#然后把切好的苦瓜下锅焯水30秒
then blanch the bitter gourd slices for 30 seconds

0:00:55.520,0:00:57.500
#焯水的目的是减少苦瓜的苦涩味
the purpose of blanching is to reduce the bitter taste

0:00:58.040,0:01:00.360
#加盐的目的是防止维生素流失
the purpose of adding salt is to prevent vitamin loss

0:01:00.580,0:01:03.340
#30秒之后将焯好水的苦瓜倒出
after 30 seconds of blanching, pour the bitter gourd slices out 

0:01:03.900,0:01:06.080
#再用凉水冲洗之后沥干水分备用
wash them with cold water, then drain the water

0:01:06.420,0:01:09.460
#这一步的目的是把苦瓜的温度降下来防止苦瓜发黄
this is to cool the bitter gourd down and prevent them from turning yellow

0:01:09.820,0:01:11.500
#下一步我们开始处理鸡蛋
next, we prepare the eggs

0:01:11.660,0:01:14.360
#首先我们在碗中打入3个鸡蛋
first, we crack 3 eggs into the bowl

0:01:17.400,0:01:18.740
#加入适量的食用盐
add some salt

0:01:19.760,0:01:21.040
#加入少许的胡椒粉
add a little pepper

0:01:21.440,0:01:24.900
#然后用筷子把鸡蛋朝一个方向搅拌1分钟
stir the eggs with chopsticks in one direction for 1 minute

0:01:25.380,0:01:27.120
#搅拌的时候不能停
don't stop while stirring the eggs

0:01:27.280,0:01:30.380
#这一步的目的是通过快速搅拌把空气搅进蛋液里面
this is to let the air fully mixed with the eggs through fast-stirring

0:01:30.660,0:01:34.260
#只有经过这样搅拌的蛋液才能煎出色泽金黄的蛋饼
stirring like this can make sure the golden color of the pancake

0:01:35.940,0:01:40.320
#蛋液搅拌均匀后再将焯好水的苦瓜倒入蛋液中轻轻的搅拌均匀备用
mix the eggs with the bitter gourd together, and stir slightly to make sure they are fully mixed

0:01:41.980,0:01:44.480
#下一步我来跟大家分享如何煎鸡蛋饼不粘锅
next, I will show you how to avoid sticking while frying the egg

0:01:45.140,0:01:47.100
#首先我们把锅烧热至冒烟为止
heat up the wok until it smokes

0:01:47.860,0:01:49.340
#然后在锅中加入少许的油
add some oil into the wok

0:01:49.900,0:01:52.380
#把锅中的油烧热之后再加入适量的清水
add some water once the oil is heated up

0:01:56.820,0:01:59.780
#用清水把锅清洗干净之后再用此法重复一次
clean the wok with clear water, and repeat this technique one more time

0:02:00.380,0:02:02.940
#这一步骤在行业中被称为“养锅”
this technique is called "yangguo" (season the wok)

0:02:03.580,0:02:07.620
#家庭炒锅经过这样的处理之后可以杜绝99%的粘锅
the family wok has a 99% chance of not sticking after this treatment

0:02:09.180,0:02:12.240
#在第三次把锅烧热之后加入适量的油滑锅
after heating the wok for the third time, add some oil to grease the wok 

0:02:15.760,0:02:18.340
#锅滑好之后将热油倒出再加入少许的底油
after that, pour out the hot oil and add some base oil

0:02:21.820,0:02:24.280
#然后将调好的蛋液缓缓下锅
pour slowly the prepared eggs mixture into the wok

0:02:32.360,0:02:34.160
#把中间堆积的蛋液往边上摊
push the egg liquid in the middle to the side

0:02:40.320,0:02:43.780
#蛋液摊好后开微小火煎3分钟至金黄色为止
fry it with soft fire for 3 minutes until the color turns golden

0:02:44.420,0:02:46.420
#煎制的过程中需要随时摇动蛋饼
you need to shake the egg pancake all the time while frying

0:02:46.720,0:02:49.660
#这样做的目的是让蛋饼均匀受热防止煎糊
this is to let the egg pancake be heated evenly, to avoid overcooking

0:02:50.580,0:02:53.600
#微小火煎3分钟之后把蛋饼翻面过来再煎2分钟
after 3-minute fry with soft fire, flip it to the other side and fry for 2 minutes

0:02:55.840,0:02:58.080
#继续煎2分钟之后即可出锅装盘
continue frying for 2 minutes and it's ready to serve

0:03:05.180,0:03:08.000
#一道非常美味的苦瓜煎蛋就制作完成
a very delicious dish of bitter gourd fried eggs pancake is done!

0:03:10.020,0:03:12.075
#下面开始煎蛋饼的技术总结
here are some tips for you guys:

0:03:12.700,0:03:16.580
#第一，苦瓜需要切薄一些这样吃起来才不会有太重的苦味
tip1: the bitter gourd slices need to be thinly cut so that to avoid a too bitter taste

0:03:17.120,0:03:20.600
#第二，煎蛋饼全程都必须小火否则容易煎糊
tip2: use soft fire during the whole frying process or it will be overcooked

0:03:20.980,0:03:25.360
#家庭煎蛋饼之前必须“养锅”这样才能减少粘锅的几率
tip3: "yangguo" (season the wok) at first, this will reduce the chance of sticking

0:03:26.120,0:03:27.600
#煎蛋饼的技术总结完毕
tips end

0:03:28.220,0:03:32.300
#关注头条号美食作家，这里总有一款属于你
subscribe to my channel, where there is always a dish for you~

**Comment by immoonancient** [comment]
已发布
