### ISSUE TITLE
【雪鱼】烧鹅-https://www.youtube.com/watch?v=OYzTZp-CNcA

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#654]
https://www.youtube.com/watch?v=OYzTZp-CNcA

**标题：**开车100里到郊区吃烧鹅，明火烤制256元一只，油光绽放，顾客坐满2层楼
**简介**：在广东中山吃烧鹅，这家的烧鹅在珠三角地区都很知名，烧鹅的炉子都是公开透明的，很多顾客来了就要拍照，都快要成了风景线。一只鹅一只炉子，炉子底下烧着柴火，上面的烧鹅一直在转圈圈，转足一个小时就烤好了。烧鹅看起来油光锃亮，师傅快刀斩肉，128元半只，直接上桌开吃，我能吃2碗饭。注意这家店人气火爆，虽然位置远，但是每天中午的顾客都要坐满2层楼哦。
**字幕：**
1
00:00:01,680 --> 00:00:06,720
广东·中山
1月份拍摄

2
00:00:12,320 --> 00:00:15,320
今天我们还是到一个庄园来吃饭

3
00:00:15,320 --> 00:00:18,160
在这个地方 我们就能听到鹅的叫声

4
00:00:18,160 --> 00:00:21,320
我们今天要去吃的是 果木烤鹅

5
00:00:26,600 --> 00:00:29,520
刚才叔叔告诉我们 要朝这边走

6
00:00:29,520 --> 00:00:33,280
接下来我们要去找吃饭的地方

7
00:00:43,480 --> 00:00:46,280
一进来就看到了好多鱼

8
00:00:46,280 --> 00:00:48,640
不过都是观赏性的鱼

9
00:00:49,240 --> 00:00:52,000
这是专门买的鱼吧

10
00:01:20,160 --> 00:01:23,000
这一个农家庄园 真的是什么都有

11
00:01:23,000 --> 00:01:25,920
这边呢 就是做烧鹅的

12
00:01:25,920 --> 00:01:30,080
看我前面就是在做腐竹 还有做煎堆的

13
00:01:30,080 --> 00:01:34,080
各种各样的菜品都能在这里找得到

14
00:01:34,080 --> 00:01:36,560
这个农家园光厨房就有四五个

15
00:01:36,560 --> 00:01:39,840
炒菜 做烧鹅 做糕点

16
00:01:39,840 --> 00:01:44,160
每个师傅好像都有自己的任务在这个地方忙

17
00:02:13,640 --> 00:02:15,400
我后面就是几十个金钟罩

18
00:02:15,400 --> 00:02:16,600
里面就是

19
00:02:16,600 --> 00:02:19,520
每一个炉子里面都有一只鹅

20
00:02:19,520 --> 00:02:22,440
它们金黄诱人 还流着肥油

21
00:02:22,440 --> 00:02:24,120
一只平平无奇的鹅

22
00:02:24,120 --> 00:02:26,080
想要变得如此光鲜亮丽

23
00:02:26,080 --> 00:02:28,520
还得经历一些的磨难

24
00:02:29,120 --> 00:02:31,720
洗净的鹅要吹气 滚水 烫皮

25
00:02:31,720 --> 00:02:35,520
然后 才能够把腌料 塞进肚子里

26
00:02:35,520 --> 00:02:38,920
这个时候的鹅 从外面看 除了变得气鼓鼓的

27
00:02:38,920 --> 00:02:40,560
好像没有什么样的变化

28
00:02:40,560 --> 00:02:44,600
但是腌料的味道 正在向全身蔓延

29
00:02:45,160 --> 00:02:48,160
这个鹅得先在后面进行风干处理

30
00:02:48,160 --> 00:02:50,840
然后才能够上烤炉

31
00:02:50,840 --> 00:02:53,520
它要在里面 转呀 转呀 转呀

32
00:02:53,520 --> 00:02:57,440
转足一个小时 才能够下来

33
00:02:57,440 --> 00:02:58,800
在偌大的庄园里

34
00:02:58,800 --> 00:03:02,440
一只只烤鹅转圈圈的场景成为了全场的焦点

35
00:03:02,440 --> 00:03:04,840
虽然说 我们只能看到它的下半身

36
00:03:10,360 --> 00:03:12,480
经过长时间的文火烤制

37
00:03:12,480 --> 00:03:14,840
鹅外皮的颜色会逐渐加深

38
00:03:14,840 --> 00:03:18,280
果木香和肉香 也变得更加浓郁

39
00:03:46,800 --> 00:03:50,880
烤鹅做好了 师傅要把它片成这种片状

40
00:03:50,880 --> 00:03:52,120
片完之后呢

41
00:03:52,120 --> 00:03:54,560
还要在上面浇一勺的汤汁

42
00:03:54,560 --> 00:03:57,360
这样才能感觉到更加诱人

43
00:03:57,800 --> 00:03:59,720
玻璃是隔音的吧 什么也听不到

44
00:03:59,720 --> 00:04:01,640
只能看着眼馋

45
00:04:45,600 --> 00:04:49,680
一楼都坐满了 我们现在要上二楼了

46
00:04:56,320 --> 00:05:00,880
没想到来庄园吃饭 还要喝茶

47
00:05:00,880 --> 00:05:03,560
我们就是要了一个很普通的茶

48
00:05:03,560 --> 00:05:05,200
然后现在就是点单

49
00:05:05,200 --> 00:05:06,680
它这边是扫码点单

50
00:05:06,680 --> 00:05:08,400
咱们看一看有什么好吃的

51
00:05:10,160 --> 00:05:10,920
不看不知道

52
00:05:10,920 --> 00:05:12,680
真的是什么都有

53
00:05:12,680 --> 00:05:15,080
咱们这次来的
目的是
吃烧鹅

54
00:05:15,080 --> 00:05:17,080
所以一定点
烧鹅

55
00:05:17,080 --> 00:05:19,040
其它的
便点点吧

56
00:05:19,040 --> 00:05:21,240
看烧鹅就挺大的了

57
00:05:21,280 --> 00:05:23,600
好小的蜡烛

58
00:05:25,480 --> 00:05:28,280
给了一个加热的蜡烛

59
00:05:30,160 --> 00:05:31,680
挺好的

60
00:05:32,800 --> 00:05:35,440
这个放烤鹅的盘子

61
00:05:35,440 --> 00:05:37,920
长度呢 差不多会有我的

62
00:05:37,920 --> 00:05:40,720
四扎吧 用我的手来比划的话

63
00:05:40,720 --> 00:05:42,880
差不多是四扎的长度

64
00:05:43,600 --> 00:05:47,120
这只是半只 就是这么长

65
00:05:47,120 --> 00:05:50,000
烧鹅的外皮 油亮油亮的 仔细看

66
00:05:50,000 --> 00:05:53,440
肉和皮之间还有一层很薄的脂肪层

67
00:05:55,960 --> 00:05:57,880
一只鹅被端上餐桌之前

68
00:05:57,880 --> 00:06:01,600
要经过吹气 风干 刷皮水 烤制等过程

69
00:06:01,640 --> 00:06:03,400
表皮没有那么多的水分

70
00:06:03,400 --> 00:06:06,160
烤完之后吃起来 会有微弱的脆的口感

71
00:06:06,160 --> 00:06:07,680
而包裹在里面的鹅肉

72
00:06:07,680 --> 00:06:11,080
吃起来鲜嫩 而且多汁

73
00:06:15,440 --> 00:06:18,320
每一块的鹅肉 其实都是很肥腻的

74
00:06:18,320 --> 00:06:21,760
这个时候呢 你可以来点酸甜口的酱料

75
00:06:21,760 --> 00:06:23,840
也可以来点咸口的酱料

76
00:06:23,840 --> 00:06:25,760
但是不管是哪种口味的

77
00:06:25,760 --> 00:06:28,840
对于它来说 都是解腻的

78
00:06:32,880 --> 00:06:34,560
不管菜品再丰富

79
00:06:34,560 --> 00:06:37,400
最后都得归结于一碗白米饭

80
00:06:37,400 --> 00:06:40,840
这样才能够感觉吃得饱

81
00:06:46,960 --> 00:06:49,960
这个鹅实在是太大了 半只都没有吃了

82
00:06:49,960 --> 00:06:53,480
我们要把大块的鹅腿带走了

83
00:07:30,600 --> 00:07:33,120
走出来都差点没有找到路

84
00:07:33,120 --> 00:07:35,240
这个地方太大了

85
00:07:57,760 --> 00:08:00,560
关 注
雪 鱼 探 店

**Comment by greentea007** [comment]
认领

**Comment by greentea007** [comment]
bot, please upload
![image](https://user-images.githubusercontent.com/60958433/74319818-8d69d300-4dba-11ea-879e-3cf391b0d596.png)

**Comment by greentea007** [comment]
bot, please upload
**标题：**开车100里到郊区吃烧鹅，明火烤制256元一只，油光绽放，顾客坐满2层楼
简介：在广东中山吃烧鹅，这家的烧鹅在珠三角地区都很知名，烧鹅的炉子都是公开透明的，很多顾客来了就要拍照，都快要成了风景线。一只鹅一只炉子，炉子底下烧着柴火，上面的烧鹅一直在转圈圈，转足一个小时就烤好了。烧鹅看起来油光锃亮，师傅快刀斩肉，128元半只，直接上桌开吃，我能吃2碗饭。注意这家店人气火爆，虽然位置远，但是每天中午的顾客都要坐满2层楼哦。
字幕：
1 Zhongshan, Guangdong. Videotaped in January. 
00:00:01,680 --> 00:00:06,720
广东·中山
1月份拍摄
2 Today, we’re going to a manor for dinner.
00:00:12,320 --> 00:00:15,320
今天我们还是到一个庄园来吃饭
3 At the place where we are standing, we can hear those geese are honking.
00:00:15,320 --> 00:00:18,160
在这个地方 我们就能听到鹅的叫声
4 We’re having roast goose today.
00:00:18,160 --> 00:00:21,320
我们今天要去吃的是 果木烤鹅
5 That guy told us to head over there.
00:00:26,600 --> 00:00:29,520
刚才叔叔告诉我们 要朝这边走
6 Now, let’s get into the restaurant. 
00:00:29,520 --> 00:00:33,280
接下来我们要去找吃饭的地方
7 So many fishes in the pond.
00:00:43,480 --> 00:00:46,280
一进来就看到了好多鱼
8 But, they’re all decorative fishes.
00:00:46,280 --> 00:00:48,640
不过都是观赏性的鱼
9 are they bought just for decoration?
00:00:49,240 --> 00:00:52,000
这是专门买的鱼吧
10 This countryside manor has everything
00:01:20,160 --> 00:01:23,000
这一个农家庄园 真的是什么都有
11 Over there, is for the geese to get roasted.
00:01:23,000 --> 00:01:25,920
这边呢 就是做烧鹅的
12 Right here, they are making Tofu skin and Sesame balls.
00:01:25,920 --> 00:01:30,080
看我前面就是在做腐竹 还有做煎堆的
13 They have a large variety of food here.
00:01:30,080 --> 00:01:34,080
各种各样的菜品都能在这里找得到
14 This countryside manor has 4 or 5 kitchens 
00:01:34,080 --> 00:01:36,560
这个农家园光厨房就有四五个
15 stir fry dish, roast goose, and pastry.
00:01:36,560 --> 00:01:39,840
炒菜 做烧鹅 做糕点
16 every chef is working on their own station.
00:01:39,840 --> 00:01:44,160
每个师傅好像都有自己的任务在这个地方忙
17 The thing right behind me is a few dozens of tiny ovens.
00:02:13,640 --> 00:02:15,400
我后面就是几十个金钟罩
18 Right there.
00:02:15,400 --> 00:02:16,600
里面就是
19 Every each of that ovens contains a goose.
00:02:16,600 --> 00:02:19,520
每一个炉子里面都有一只鹅
20 those golden-brown geese are dripping goose fat.
00:02:19,520 --> 00:02:22,440
它们金黄诱人 还流着肥油
21If an ordinary goose
00:02:22,440 --> 00:02:24,120
一只平平无奇的鹅
22 wants to because shinny in appearance
00:02:24,120 --> 00:02:26,080
想要变得如此光鲜亮丽
23 It needs to go through a lot more than that.
00:02:26,080 --> 00:02:28,520
还得经历一些的磨难
24 A cleaned goose has to be inflated, boiled, and blanched with cooking oil.
00:02:29,120 --> 00:02:31,720
洗净的鹅要吹气 滚水 烫皮
25 and then, they stuff the goose with marinates. 
00:02:31,720 --> 00:02:35,520
然后 才能够把腌料 塞进肚子里
26 At this moment, the goose is no different expect it has been inflated.
00:02:35,520 --> 00:02:38,920
这个时候的鹅 从外面看 除了变得气鼓鼓的
27 it looks like nothing has changed.
00:02:38,920 --> 00:02:40,560
好像没有什么样的变化
28 But the aroma of the marinates are spreading all over the meat.
00:02:40,560 --> 00:02:44,600
但是腌料的味道 正在向全身蔓延
29 It needs to be dried,
00:02:45,160 --> 00:02:48,160
这个鹅得先在后面进行风干处理
30 before it goes into the oven.
00:02:48,160 --> 00:02:50,840
然后才能够上烤炉
31 that goose is going to spin in that oven
00:02:50,840 --> 00:02:53,520
它要在里面 转呀 转呀 转呀
32 for a good hour.
00:02:53,520 --> 00:02:57,440
转足一个小时 才能够下来
33 In this massive manor,
00:02:57,440 --> 00:02:58,800
在偌大的庄园里
34 spinning geese are catching all the spotlights.
00:02:58,800 --> 00:03:02,440
一只只烤鹅转圈圈的场景成为了全场的焦点
35 Although, we can only see the bottom part of the geese.
00:03:02,440 --> 00:03:04,840
虽然说 我们只能看到它的下半身
36 After an hour of roasting on low heat,
00:03:10,360 --> 00:03:12,480
经过长时间的文火烤制
37 The skin color of those geese is darkening.
00:03:12,480 --> 00:03:14,840
鹅外皮的颜色会逐渐加深
38 Also, the aroma of meat and fruit wood are thickening.
00:03:14,840 --> 00:03:18,280
果木香和肉香 也变得更加浓郁
39 When geese are ready, chefs will slice the meat into this shape.
00:03:46,800 --> 00:03:50,880
烤鹅做好了 师傅要把它片成这种片状
40 after slicing,
00:03:50,880 --> 00:03:52,120
片完之后呢
41They will pour a spoon of goose stock.
00:03:52,120 --> 00:03:54,560
还要在上面浇一勺的汤汁
42 It just made the goose so much tempting.
00:03:54,560 --> 00:03:57,360
这样才能感觉到更加诱人
43 this glass is soundproofed right? I can’t hear anything. 
00:03:57,800 --> 00:03:59,720
玻璃是隔音的吧 什么也听不到
44 but I can see that goose inside.
00:03:59,720 --> 00:04:01,640
只能看着眼馋
45 the ground level is packed, lets head to the second floor.
00:04:45,600 --> 00:04:49,680
一楼都坐满了 我们现在要上二楼了
46 I wasn’t expecting tea here.
00:04:56,320 --> 00:05:00,880
没想到来庄园吃饭 还要喝茶
47 I ordered some regular tea.
00:05:00,880 --> 00:05:03,560
我们就是要了一个很普通的茶
48 Let’s order some food.
00:05:03,560 --> 00:05:05,200
然后现在就是点单
49 They provide a QR code for food ordering.
00:05:05,200 --> 00:05:06,680
它这边是扫码点单
50 Let’s see what they got.
00:05:06,680 --> 00:05:08,400
咱们看一看有什么好吃的
51 I didn’t know they
00:05:10,160 --> 00:05:10,920
不看不知道
52 got everything.
00:05:10,920 --> 00:05:12,680
真的是什么都有
53 The goal of this trip is to try their roast goose.
00:05:12,680 --> 00:05:15,080
咱们这次来的
目的是
吃烧鹅
54 So, I have to order that roast goose.
00:05:15,080 --> 00:05:17,080
所以一定点
烧鹅
55 I’m getting some side dishes as well.
00:05:17,080 --> 00:05:19,040
其它的
便点点吧
56 the goose itself looks pretty big.
00:05:19,040 --> 00:05:21,240
看烧鹅就挺大的了
57 What a tiny candle.
00:05:21,280 --> 00:05:23,600
好小的蜡烛
58 they gave us candles to keep the dish warm.
00:05:25,480 --> 00:05:28,280
给了一个加热的蜡烛
59 not bad.
00:05:30,160 --> 00:05:31,680
挺好的
60 The length of the plate for this goose
00:05:32,800 --> 00:05:35,440
这个放烤鹅的盘子
61 is almost
00:05:35,440 --> 00:05:37,920
长度呢 差不多会有我的
62 60 centimeters.
00:05:37,920 --> 00:05:40,720
四扎吧 用我的手来比划的话
63 I’m using my hand to measure it
00:05:40,720 --> 00:05:42,880
差不多是四扎的长度
64 This is a half of the goose.
00:05:43,600 --> 00:05:47,120
这只是半只 就是这么长
65 the skin of is shining, if I look closely,
00:05:47,120 --> 00:05:50,000
烧鹅的外皮 油亮油亮的 仔细看
66 there is a very thin layer of fat between the mean and the skin.
00:05:50,000 --> 00:05:53,440
肉和皮之间还有一层很薄的脂肪层
67 Before a goose got served for eating,
00:05:55,960 --> 00:05:57,880
一只鹅被端上餐桌之前
68 It has to be inflated, dried, roasted.
00:05:57,880 --> 00:06:01,600
要经过吹气 风干 刷皮水 烤制等过程
69 Without the moisture in the skin,
00:06:01,640 --> 00:06:03,400
表皮没有那么多的水分
70 it just tastes much crispier and crunchier.
00:06:03,400 --> 00:06:06,160
烤完之后吃起来 会有微弱的脆的口感
71 and the meat inside
00:06:06,160 --> 00:06:07,680
而包裹在里面的鹅肉
72 will taste juicier and more tender
00:06:07,680 --> 00:06:11,080
吃起来鲜嫩 而且多汁
73 Actually, every bite is quite fatty.
00:06:15,440 --> 00:06:18,320
每一块的鹅肉 其实都是很肥腻的
74 So, you need some sweet and sour dipping sauce.
00:06:18,320 --> 00:06:21,760
这个时候呢 你可以来点酸甜口的酱料
75 or some savory sauce.
00:06:21,760 --> 00:06:23,840
也可以来点咸口的酱料
76 but no matter which kind of sauce you chose.
00:06:23,840 --> 00:06:25,760
但是不管是哪种口味的
77 you can get rid of some of the greasy taste.
00:06:25,760 --> 00:06:28,840
对于它来说 都是解腻的
78 No matter how rich and various the food is,
00:06:32,880 --> 00:06:34,560
不管菜品再丰富
79 You need a bowl of rice to finish the meal
00:06:34,560 --> 00:06:37,400
最后都得归结于一碗白米饭
80 Therefore, you can get fulled
00:06:37,400 --> 00:06:40,840
这样才能够感觉吃得饱
81 This goose is way to big, I couldn’t even finish a half of it
00:06:46,960 --> 00:06:49,960
这个鹅实在是太大了 半只都没有吃了
82 We’re taking the goose drumstick home.
00:06:49,960 --> 00:06:53,480
我们要把大块的鹅腿带走了
83 I almost lost track of direction on the way out.
00:07:30,600 --> 00:07:33,120
走出来都差点没有找到路
84 This place is massive.
00:07:33,120 --> 00:07:35,240
这个地方太大了
85 Please subscribe to my channel! Xue Yu
00:07:57,760 --> 00:08:00,560
关 注
雪 鱼 探 店

**Comment by greentea007** [comment]
bot, please upload**标题：**开车100里到郊区吃烧鹅，明火烤制256元一只，油光绽放，顾客坐满2层楼
I drove 50km all the way to the countryside just for the roast goose, 256rmb each with crispy oil dripping skin, 2 levels were packed with customers. 
简介：在广东中山吃烧鹅，这家的烧鹅在珠三角地区都很知名，烧鹅的炉子都是公开透明的，很多顾客来了就要拍照，都快要成了风景线。一只鹅一只炉子，炉子底下烧着柴火，上面的烧鹅一直在转圈圈，转足一个小时就烤好了。烧鹅看起来油光锃亮，师傅快刀斩肉，128元半只，直接上桌开吃，我能吃2碗饭。注意这家店人气火爆，虽然位置远，但是每天中午的顾客都要坐满2层楼哦。
I’m having roast goose in Zhongshan, Guangdong. This roast goose restaurant is extremely famous in the pearl river area. You can see those ovens inside. Many customers are here for a photo. Each tiny oven contains a goose with fruitwood burning underneath. It. The geese will be roasted for a good hour and the chef will slice it into small pieces. 128 for a half of it, you can eat it right away. Be aware, although the location of that Restaurant is far away from the city, it usually packed with customers during the lunchtime
字幕：
1
00:00:01,680 --> 00:00:06,720
广东·中山
1月份拍摄
Zhongshan, Guangdong. Videotaped in January.
2
00:00:12,320 --> 00:00:15,320
今天我们还是到一个庄园来吃饭
Today, we’re going to a manor for dinner.
3
00:00:15,320 --> 00:00:18,160
在这个地方 我们就能听到鹅的叫声
At the place where we are standing, we can hear those geese are honking.
4
00:00:18,160 --> 00:00:21,320
我们今天要去吃的是 果木烤鹅
We’re having roast goose today.
5
00:00:26,600 --> 00:00:29,520
刚才叔叔告诉我们 要朝这边走
That guy told us to head over there.
6
00:00:29,520 --> 00:00:33,280
接下来我们要去找吃饭的地方
Now, let’s get into the restaurant. 

7
00:00:43,480 --> 00:00:46,280
一进来就看到了好多鱼
So many fishes in the pond.
8
00:00:46,280 --> 00:00:48,640
不过都是观赏性的鱼
But, they’re all decorative fishes.
9
00:00:49,240 --> 00:00:52,000
这是专门买的鱼吧
are they bought just for decoration?
10
00:01:20,160 --> 00:01:23,000
这一个农家庄园 真的是什么都有
This countryside manor has everything
11
00:01:23,000 --> 00:01:25,920
这边呢 就是做烧鹅的
Over there, is for the geese to get roasted.
12
00:01:25,920 --> 00:01:30,080
看我前面就是在做腐竹 还有做煎堆的
Right here, they are making Tofu skin and Sesame balls.
13
00:01:30,080 --> 00:01:34,080
各种各样的菜品都能在这里找得到
They have a large variety of food here.
14
00:01:34,080 --> 00:01:36,560
这个农家园光厨房就有四五个
This countryside manor has 4 or 5 kitchens 
15
00:01:36,560 --> 00:01:39,840
炒菜 做烧鹅 做糕点
stir fry dish, roast goose, and pastry.
16
00:01:39,840 --> 00:01:44,160
每个师傅好像都有自己的任务在这个地方忙
every chef is working on their own station.
17
00:02:13,640 --> 00:02:15,400
我后面就是几十个金钟罩
The thing right behind me is a few dozens of tiny ovens.
18
00:02:15,400 --> 00:02:16,600
里面就是
Right there.
19
00:02:16,600 --> 00:02:19,520
每一个炉子里面都有一只鹅
Every each of that ovens contains a goose.
20
00:02:19,520 --> 00:02:22,440
它们金黄诱人 还流着肥油
those golden-brown geese are dripping goose fat.
21
00:02:22,440 --> 00:02:24,120
一只平平无奇的鹅
If an ordinary goose
22
00:02:24,120 --> 00:02:26,080
想要变得如此光鲜亮丽
wants to because shiny in appearance
23
00:02:26,080 --> 00:02:28,520
还得经历一些的磨难
It needs to go through a lot more than that.
24
00:02:29,120 --> 00:02:31,720
洗净的鹅要吹气 滚水 烫皮
A cleaned goose has to be inflated, boiled and blanched with cooking oil.
25
00:02:31,720 --> 00:02:35,520
然后 才能够把腌料 塞进肚子里
and then, they stuff the goose with marinates.
26
00:02:35,520 --> 00:02:38,920
这个时候的鹅 从外面看 除了变得气鼓鼓的
At this moment, the goose is no different except it has been inflated.
27
00:02:38,920 --> 00:02:40,560
好像没有什么样的变化
it looks like nothing has changed.
28
00:02:40,560 --> 00:02:44,600
但是腌料的味道 正在向全身蔓延
But the aroma of the marinates are spreading all over the meat.
29
00:02:45,160 --> 00:02:48,160
这个鹅得先在后面进行风干处理
It needs to be dried,
30
00:02:48,160 --> 00:02:50,840
然后才能够上烤炉
before it goes into the oven.
31
00:02:50,840 --> 00:02:53,520
它要在里面 转呀 转呀 转呀
that goose is going to spin in that oven
32
00:02:53,520 --> 00:02:57,440
转足一个小时 才能够下来
or a good hour.
33
00:02:57,440 --> 00:02:58,800
在偌大的庄园里
In this massive manor,
34
00:02:58,800 --> 00:03:02,440
一只只烤鹅转圈圈的场景成为了全场的焦点
spinning geese are catching all the spotlights.
35
00:03:02,440 --> 00:03:04,840
虽然说 我们只能看到它的下半身
Although, we can only see the bottom part of the geese.
36
00:03:10,360 --> 00:03:12,480
经过长时间的文火烤制
After an hour of roasting on low heat,
37
00:03:12,480 --> 00:03:14,840
鹅外皮的颜色会逐渐加深
he skin color of those geese are darkening.
38
00:03:14,840 --> 00:03:18,280
果木香和肉香 也变得更加浓郁
Also, the aroma of meat and fruitwood is thickening.
39
00:03:46,800 --> 00:03:50,880
烤鹅做好了 师傅要把它片成这种片状
When geese are ready, chefs will slice the meat into this shape.
40
00:03:50,880 --> 00:03:52,120
片完之后呢
after slicing,
41
00:03:52,120 --> 00:03:54,560
还要在上面浇一勺的汤汁
They will pour a spoon of goose stock.
42
00:03:54,560 --> 00:03:57,360
这样才能感觉到更加诱人
It just made the goose so much more tempting.
43
00:03:57,800 --> 00:03:59,720
玻璃是隔音的吧 什么也听不到
this glass is soundproofed, right? I can’t hear anything.
44
00:03:59,720 --> 00:04:01,640
只能看着眼馋
but I can see that goose inside.
45
00:04:45,600 --> 00:04:49,680
一楼都坐满了 我们现在要上二楼了
the ground level is packed, lets head to the second floor.
46
00:04:56,320 --> 00:05:00,880
没想到来庄园吃饭 还要喝茶
I wasn’t expecting tea here.
47
00:05:00,880 --> 00:05:03,560
我们就是要了一个很普通的茶
I ordered some regular tea.
48
00:05:03,560 --> 00:05:05,200
然后现在就是点单
Let’s order some food.
49
00:05:05,200 --> 00:05:06,680
它这边是扫码点单
They provide a QR code for food ordering.
50
00:05:06,680 --> 00:05:08,400
咱们看一看有什么好吃的
Let’s see what they got.
51
00:05:10,160 --> 00:05:10,920
不看不知道
I didn’t know they
52
00:05:10,920 --> 00:05:12,680
真的是什么都有
got everything.
53
00:05:12,680 --> 00:05:15,080
咱们这次来的
目的是
吃烧鹅
The goal of this trip is to try their roast goose.

54
00:05:15,080 --> 00:05:17,080
所以一定点
烧鹅
So, I have to order that roast goose.
55
00:05:17,080 --> 00:05:19,040
其它的
便点点吧
I’m getting some side dishes as well.
56
00:05:19,040 --> 00:05:21,240
看烧鹅就挺大的了
the goose itself looks pretty big.
57
00:05:21,280 --> 00:05:23,600
好小的蜡烛
What a tiny candle.
58
00:05:25,480 --> 00:05:28,280
给了一个加热的蜡烛
they gave us candles to keep the dish warm.
59
00:05:30,160 --> 00:05:31,680
挺好的
not bad.
60
00:05:32,800 --> 00:05:35,440
这个放烤鹅的盘子
The length of the plate for this goose
61
00:05:35,440 --> 00:05:37,920
长度呢 差不多会有我的
is almost
62
00:05:37,920 --> 00:05:40,720
四扎吧 用我的手来比划的话
60 centimeters.
63
00:05:40,720 --> 00:05:42,880
差不多是四扎的长度
I’m using my hand to measure it
64
00:05:43,600 --> 00:05:47,120
这只是半只 就是这么长
This is only a half of the goose.

65
00:05:47,120 --> 00:05:50,000
烧鹅的外皮 油亮油亮的 仔细看
he skin of is shining, if I look closely,
66
00:05:50,000 --> 00:05:53,440
肉和皮之间还有一层很薄的脂肪层
there is a very thin layer of fat between the mean and the skin.
67
00:05:55,960 --> 00:05:57,880
一只鹅被端上餐桌之前
Before a goose got served for eating,
68
00:05:57,880 --> 00:06:01,600
要经过吹气 风干 刷皮水 烤制等过程
it has to be inflated, dried, roasted.
69
00:06:01,640 --> 00:06:03,400
表皮没有那么多的水分
Without the moisture in the skin,
70
00:06:03,400 --> 00:06:06,160
烤完之后吃起来 会有微弱的脆的口感
it just tastes much crisper and crunchier.
71
00:06:06,160 --> 00:06:07,680
而包裹在里面的鹅肉
and the meat inside
72
00:06:07,680 --> 00:06:11,080
吃起来鲜嫩 而且多汁
will taste juicier and more tender
73
00:06:15,440 --> 00:06:18,320
每一块的鹅肉 其实都是很肥腻的
Actually, every bite is quite fatty.
74
00:06:18,320 --> 00:06:21,760
这个时候呢 你可以来点酸甜口的酱料
So, you need some sweet and sour dipping sauce.
75
00:06:21,760 --> 00:06:23,840
也可以来点咸口的酱料
or some savory sauce.
76
00:06:23,840 --> 00:06:25,760
但是不管是哪种口味的
but no matter which kind of sauce you chose.
77
00:06:25,760 --> 00:06:28,840
对于它来说 都是解腻的
you can get rid of some of the greasy taste.
78
00:06:32,880 --> 00:06:34,560
不管菜品再丰富
No matter how rich and various the food is,
79
00:06:34,560 --> 00:06:37,400
最后都得归结于一碗白米饭
You need a bowl of rice to finish the meal
80
00:06:37,400 --> 00:06:40,840
这样才能够感觉吃得饱
Therefore, you can get full
81
00:06:46,960 --> 00:06:49,960
这个鹅实在是太大了 半只都没有吃了
This goose is way too big, I couldn’t even finish half of it
82
00:06:49,960 --> 00:06:53,480
我们要把大块的鹅腿带走了
We’re taking the goose drumstick home.
83
00:07:30,600 --> 00:07:33,120
走出来都差点没有找到路
I almost lost track of direction on the way out.
84
00:07:33,120 --> 00:07:35,240
这个地方太大了
This place is massive.
85
00:07:57,760 --> 00:08:00,560
关 注
雪 鱼 探 店
Please subscribe to my channel! Xue Yu

**Comment by immoonancient** [comment]
已发布
