### ISSUE TITLE
【美食作家王刚】回兜山看望四伯 - https://youtu.be/j5Aii36bknY

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#661]
【美食作家王刚】回兜山看望四伯 - https://youtu.be/j5Aii36bknY
视频时长 6:06，预计发布时间为北京时间2月15日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.825,0:00:02.775
哈喽大家好我是王刚

0:00:03.400,0:00:07.850
在这个城里面已经有十多二十天没有回（老）家了

0:00:07.850,0:00:10.150
今天回去看一下我四伯

0:00:10.525,0:00:15.154
这段时间我四伯也没有去赶场卖肉

0:00:20.200,0:00:23.950
十多二十天没开车现在都有点生疏了

0:00:26.950,0:00:28.650
特别是戴上这个口罩

0:00:28.650,0:00:30.275
我感觉我有点缺氧

0:00:31.575,0:00:35.025
现在也不知道我四伯那里有没有设卡（点）

0:00:36.275,0:00:38.050
还不知道进不进得去

0:00:39.100,0:00:40.950
不过应该没问题吧

0:00:40.950,0:00:44.800
因为是我老家我回自己祖屋应该没问题

0:00:44.800,0:00:46.225
进应该是进得去

0:00:52.850,0:00:55.325
现在我们乡下还是没有什么车

0:00:55.325,0:00:59.950
平时的话像现在应该在堵车

0:00:59.950,0:01:02.875
然后排队通过

0:01:04.400,0:01:07.650
好了我们现在已经到了乡村小道了

0:01:07.650,0:01:10.450
现在这个菜籽都开花了

0:01:10.450,0:01:11.300
好漂亮啊

0:01:14.350,0:01:17.350
哦在前面这个卡点设在前面

0:01:20.670,0:01:21.825
也拉了横幅

0:01:22.470,0:01:25.875
我估计车的话要停在外面进不去了

0:01:32.775,0:01:34.100
现在下去问一下

0:01:37.350,0:01:39.600
师傅我想把车停里面

0:01:39.600,0:01:40.100
安

0:01:40.100,0:01:41.350
我想把车停里面

0:01:41.350,0:01:42.150
你到哪里去嘛

0:01:42.150,0:01:43.423
我就是张家湾的

0:01:43.423,0:01:45.300
你是张家湾的？对

0:01:46.525,0:01:58.075
努力沟通中

0:02:03.700,0:02:05.200
我伯爷都出来接我来了

0:02:07.125,0:02:09.000
外来人员不得进入

0:02:12.375,0:02:15.075
四伯爷给你拿了点水果下来

0:02:15.475,0:02:17.625
你拿起来我还不是干了

0:02:18.550,0:02:21.125
拿瓶酒给你喝你得屋头无聊

0:02:21.125,0:02:22.450
我还敢喝酒

0:02:23.000,0:02:24.575
要得嘛我慢慢晕（喝）嘛

0:02:24.575,0:02:28.225
我给你找了个口罩只有一个你拿到将就用

0:02:28.225,0:02:29.425
屋头有 还有几个

0:02:29.425,0:02:30.950
要的戴到拿都给你拿起来了

0:02:30.950,0:02:32.150
我都还有四五个

0:02:32.150,0:02:32.950
戴都嘛四伯爷

0:02:32.950,0:02:33.600
要得呀

0:02:35.301,0:02:36.625
我来戴

0:02:36.900,0:02:39.875
我学会（戴口罩）了这个东西你提到嘛

0:02:40.842,0:02:42.762
过年到现在还没来的（看你）呀 没有

0:02:43.825,0:02:45.750
今年还没（回来过）

0:02:46.150,0:02:49.075
走下巴那里两根一起

0:02:50.289,0:02:52.081
我就是一哈就搞定

0:02:52.081,0:02:53.425
上面套下去也可以

0:02:54.125,0:02:55.925
走这后面套进去

0:02:56.200,0:02:57.750
我是这样戴的你看嘛

0:03:00.900,0:03:02.180
这个往下面

0:03:02.180,0:03:05.000
这个放下面 一个挂耳朵上

0:03:05.000,0:03:05.700
哦对

0:03:05.800,0:03:07.413
我还是学会了的

0:03:07.413,0:03:09.175
鼻子还露在外面得不得行

0:03:09.175,0:03:10.925
这个拉起来就是了

0:03:11.075,0:03:13.575
拉起来给它按一下就贴紧了

0:03:13.575,0:03:15.125
往里面按一下

0:03:15.125,0:03:19.125
就是撒 就来了火了是不是嘛

0:03:19.150,0:03:21.500
四伯爷那这个东西拿给你我就先走了

0:03:21.675,0:03:24.650
那你等到我回去给你挖几颗菜出来嘛

0:03:25.575,0:03:27.600
也可以现在青菜也不好买

0:03:27.775,0:03:29.275
你的口罩戴归一（好）点

0:03:30.000,0:03:31.825
这个稍微往下面按一下

0:03:33.975,0:03:35.550
那我在这里等你嘛

0:03:35.550,0:03:37.300
要的我去给你挖过来

0:03:37.300,0:03:38.725
好

0:03:40.075,0:03:42.150
现在这个卡点卡在这里

0:03:42.150,0:03:46.550
我们最好不去串门

0:03:46.550,0:03:50.200
在卡点外面等我四伯回去给我弄点青菜

0:03:52.000,0:03:53.300
扯好多哦四伯爷

0:03:54.104,0:03:55.650
这不见得很多

0:03:56.200,0:03:58.000
这还不见得很多 掉了

0:03:58.750,0:04:00.225
这么多芹菜

0:04:01.225,0:04:02.575
放车里面

0:04:03.775,0:04:05.300
吃完了过后又来（挖菜）

0:04:05.300,0:04:05.975
好

0:04:13.900,0:04:16.125
四伯爷这个时候猪肉好多钱一斤

0:04:16.725,0:04:18.350
35（元一斤）

0:04:18.350,0:04:21.275
乡头35城里38、40

0:04:21.425,0:04:23.425
成都卖45

0:04:23.650,0:04:25.650
是不是有史以来最高的一次

0:04:25.650,0:04:28.875
历史以来活上一百岁的人没吃过这么贵的猪肉

0:04:29.600,0:04:32.100
要得四伯爷我就拿起走了

0:04:32.100,0:04:32.825
要得

0:04:38.000,0:04:40.325
好了现在准备回家了

0:04:41.750,0:04:43.650
四伯在这里送我

0:04:43.650,0:04:44.625
开车慢点哈

0:04:44.625,0:04:45.525
走了四伯爷

0:04:45.525,0:04:46.500
好拜拜

0:04:46.500,0:04:47.514
嗯拜拜

0:04:48.075,0:04:49.750
过几天再下来

0:04:50.200,0:04:51.734
再下来弄青菜

0:04:53.025,0:04:55.150
回到兜山（老家）被卡点卡住

0:04:56.800,0:04:59.300
因为刚刚领导也说了

0:04:59.500,0:05:01.250
这个疫情的严重性

0:05:01.650,0:05:05.000
现在不能够走家串户也不能走亲戚

0:05:06.346,0:05:10.925
回家的话要想拿点东西让亲人拿到卡点来

0:05:11.378,0:05:12.450
不过这样也好

0:05:13.325,0:05:15.900
为了防止这个疫情扩散嘛

0:05:16.667,0:05:20.050
我自己回自己的老家居然被拦下来了

0:05:20.225,0:05:22.450
我刚开始以为可以进去的

0:05:23.475,0:05:25.250
就是要通行证嘛（我没有）

0:05:26.487,0:05:30.475
回趟老家没回到自己家里面去

0:05:30.775,0:05:33.875
等这个疫情好一些有好转了

0:05:33.875,0:05:34.905
就是彻底断根（结束）之后

0:05:34.905,0:05:37.975
我们再进行一些

0:05:37.975,0:05:41.225
走亲戚呀走访啊不是走访

0:05:41.225,0:05:41.825
就是

0:05:42.675,0:05:44.875
客串 串门

0:05:46.975,0:05:49.273
久了没出门话都说不清楚了

0:05:52.575,0:05:54.600
好了本期视频就到这里了

0:05:55.375,0:05:59.750
我们农村也还是（管控）这么严格

0:06:00.475,0:06:01.725
挺好的

**Comment by Jasminelv** [comment]
认领

**Comment by Jasminelv** [comment]
【美食作家王刚】回兜山看望四伯 - https://youtu.be/j5Aii36bknY
视频时长 6:06，预计发布时间为北京时间2月15日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.825,0:00:02.775
哈喽，大家好我是王刚
Hello everyone, I am Wang Gang.

0:00:03.400,0:00:07.850
在这个城里面，已经有十多二十天没有回（老）家了
I've been staying in the city for around 10-20 days without going to my family house of my home village.

0:00:07.850,0:00:10.150
今天回去看一下我四伯
Today I will go back and visit my Uncle.

0:00:10.525,0:00:15.154
这段时间，我四伯也没有去赶场卖肉
During these days, my uncle hasn't been the market to sell pork either.

0:00:20.200,0:00:23.950
十多二十天没开车，现在都有点生疏了
10-20 days of not driving, I am feeling a little bit rusty.

0:00:26.950,0:00:28.650
特别是戴上这个口罩
Especially when I am wearing this face mask..

0:00:28.650,0:00:30.275
我感觉我有点缺氧
I am feeling somewhat suffocating. 

0:00:31.575,0:00:35.025
现在也不知道我四伯那里有没有设卡（点）
Right now I don't even know if there is a check point established at my Uncle's (village).

0:00:36.275,0:00:38.050
还不知道进不进得去
Still not sure if I could go in or not.

0:00:39.100,0:00:40.950
不过应该没问题吧
...but at the same time, there shouldn't be a problem (I hope)...

0:00:40.950,0:00:44.800
因为是我老家我回自己祖屋应该没问题
Because that is my hometown, if I go back to my family house, shouldn't be a problem.

0:00:44.800,0:00:46.225
进应该是进得去
I should be allowed entry (of the village).

0:00:52.850,0:00:55.325
现在我们乡下还是没有什么车
Now in the country, there are still few cars on the road.

0:00:55.325,0:00:59.950
平时的话，像现在，应该在堵车
Usually, there is a traffic jam during this time of day.

0:00:59.950,0:01:02.875
然后排队通过
Cars go through here slowly bumper to bumper.

0:01:04.400,0:01:07.650
好了，我们现在已经到了乡村小道了
OK, now we are on the country road.

0:01:07.650,0:01:10.450
现在这个菜籽都开花了
Now the rapeseed flowers are blooming.

0:01:10.450,0:01:11.300
好漂亮啊
It is so pretty!

0:01:14.350,0:01:17.350
哦，在前面这个卡点设在前面
OK，there is a check point ahead.

0:01:20.670,0:01:21.825
也拉了横幅
There is also a banner....

0:01:22.470,0:01:25.875
我估计车的话，要停在外面进不去了
I suppose I have to park the car outside of the check point.

0:01:32.775,0:01:34.100
现在下去问一下
Let me ask them.

0:01:37.350,0:01:39.600
师傅我想把车停里面
Sir, I want to park my car inside.

0:01:39.600,0:01:40.100
咹？
What (are you talking about)?

0:01:40.100,0:01:41.350
我想把车停里面
I want to park my car inside.

0:01:41.350,0:01:42.150
你到哪里去嘛
Where are you heading to?

0:01:42.150,0:01:43.423
我就是张家湾的
I am a native of ZhangJiaWan (village name).

0:01:43.423,0:01:45.300
你是张家湾的？对
Are you a native of ZhangJiaWan?  (Sure.)

0:01:46.525,0:01:58.075
努力沟通中
(much communication going on)

0:02:03.700,0:02:05.200
我伯爷都出来接我来了
Even my uncle came to the check point to meet up with me.

0:02:07.125,0:02:09.000
外来人员不得进入
No outsiders are permitted of entry.

0:02:12.375,0:02:15.075
四伯爷，（我）给你拿了点水果下来
Uncle, I bring some fruit for you.

0:02:15.475,0:02:17.625
你拿起来，我还不是（喝）干了
You bring me some hard drinking alcohol? You know I would just finish it.

0:02:18.550,0:02:21.125
拿瓶酒给你喝，你呆屋头无聊
The drinks are for your long isolation days at home, I know you must be bored.

0:02:21.125,0:02:22.450
我还敢喝酒
I really shouldn't be drinking.

0:02:23.000,0:02:24.575
要得嘛，我慢慢晕（喝）嘛
Well, that's ok, I guess I could drink it slowly....

0:02:24.575,0:02:28.225
我给你找了个口罩，只有一个，你拿倒，将就用
I brought you a face mask, just one, you can use it for now.

0:02:28.225,0:02:29.425
屋头有， 还有几个
I have a few at home.

0:02:29.425,0:02:30.950
要的，戴倒，拿都给你拿起来了
OK, wear it now, I have brought it all the way here.

0:02:30.950,0:02:32.150
我都还有四五个
I have 4 or 5 myself.

0:02:32.150,0:02:32.950
戴倒嘛，四伯爷
Wear it now, Uncle.

0:02:32.950,0:02:33.600
要得呀
Fine.

0:02:35.301,0:02:36.625
我来戴
Let me put it on it for you.

0:02:36.900,0:02:39.875
我学会（戴口罩）了。这个东西你提到嘛
I have learnt how to put a mask on, just help me carrying these bags for now.

0:02:40.842,0:02:42.762
过年到现在还没来的（看你）呀? 没有.
Has ... visited you yet since the Chinese New Year?     Not yet.

0:02:43.825,0:02:45.750
今年还没（回来过）
... hasn't been back this year.

0:02:46.150,0:02:49.075
走下巴那里两根一起
Get into it from the chin, then lift the 2 strings.

0:02:50.289,0:02:52.081
我就是一哈就搞定
I can get it done in no time.

0:02:52.081,0:02:53.425
上面套下去也可以
It can also be worn from downside.

0:02:54.125,0:02:55.925
走这后面套进去
Get into it from the back.

0:02:56.200,0:02:57.750
我是这样戴的你看嘛
You see, this is how I wear it.

0:03:00.900,0:03:02.180
这个往下面
This string should be placed on the lower side.

0:03:02.180,0:03:05.000
这个放下面 一个挂耳朵上
This should be placed on the bottom, the other one hangs on the ear.

0:03:05.000,0:03:05.700
哦对
Yes, that is right.

0:03:05.800,0:03:07.413
我还是学会了的
I had learnt it.

0:03:07.413,0:03:09.175
鼻子还露在外面的，不得行
You nose should not be left outside of the mask.

0:03:09.175,0:03:10.925
这个拉起来就是了
It's fine, just pull it up.

0:03:11.075,0:03:13.575
拉起来给它按一下就贴紧了
Pull it up a little then press it down firmly here, it will snug to the face nicely.

0:03:13.575,0:03:15.125
往里面按一下
Press down a little like this.

0:03:15.125,0:03:19.125
就是撒， 就来了，合（适）了，是不是嘛？
That is right!  It fits perfectly, isn't it?

0:03:19.150,0:03:21.500
四伯爷，那这个东西拿给你（了），我就先走了
Uncle, since you've received my gifts, I'll head back to the city now.

0:03:21.675,0:03:24.650
那你等到，我回去给你挖几颗菜出来嘛
Wait for me here, I'll go get some veggies for you.

0:03:25.575,0:03:27.600
也可以，现在青菜也不好买
That is nice.  Veggies are short of supply these days in the city.

0:03:27.775,0:03:29.275
你的口罩戴归一（好）点
Wear your mask better,

0:03:30.000,0:03:31.825
这个稍微往下面按一下
press it down with some pressure here.

0:03:33.975,0:03:35.550
那我在这里等你嘛
I will be waiting for you here.

0:03:35.550,0:03:37.300
要的我去给你挖过来
Ok, I will go dig some veggies for you.

0:03:37.300,0:03:38.725
好
Great.

0:03:40.075,0:03:42.150
现在这个卡点卡在这里
I am now getting stopped here at the village's check point.

0:03:42.150,0:03:46.550
我们最好不去串门
It is better that we don't visit other people.

0:03:46.550,0:03:50.200
在卡点外面等我四伯回去给我弄点青菜
I'm waiting outside of the check point, waiting for my uncle to get some green veggies for me from his home garden.

0:03:52.000,0:03:53.300
扯好多哦四伯爷
That is a lot of (veggies), Uncle.

0:03:54.104,0:03:55.650
这不见得很多
Not much at all.

0:03:56.200,0:03:58.000
这还不见得很多 掉了
It is so much, some are falling off my hands.

0:03:58.750,0:04:00.225
这么多芹菜
So much (Chinese) celery.

0:04:01.225,0:04:02.575
放车里面
Put them in your car.

0:04:03.775,0:04:05.300
吃完了过后又来（挖菜）
When it is finished, come back and get s'more.

0:04:05.300,0:04:05.975
好
OK.

0:04:13.900,0:04:16.125
四伯爷这个时候猪肉好多钱一斤
Uncle, what is the market price for pork these days?

0:04:16.725,0:04:18.350
35（元一斤）
35 (Chinese RMB/500grams, about 1.1lbs)

0:04:18.350,0:04:21.275
乡头35城里38、40
In the town, 35.  In the city, 38 or 40.

0:04:21.425,0:04:23.425
成都卖45
The price in Chengdu (provincial capital city) is 45.

0:04:23.650,0:04:25.650
是不是有史以来最高的一次
Is it  the most historically high?

0:04:25.650,0:04:28.875
历史以来活上一百岁的人没吃过这么贵的猪肉
Even people who are more than 100 yrs old says the pork price has never been this high.

0:04:29.600,0:04:32.100
要得四伯爷我就拿起走了
Uncle, I will thank for your veggies and go home now.

0:04:32.100,0:04:32.825
要得
That is fine.

0:04:38.000,0:04:40.325
好了现在准备回家了
OK, now I am getting ready to head back home.

0:04:41.750,0:04:43.650
四伯在这里送我 
My uncle is seeing me off here at the check point.

0:04:43.650,0:04:44.625
开车慢点哈
Drive slowly okay?

0:04:44.625,0:04:45.525
走了四伯爷
I am leaving now, Uncle.

0:04:45.525,0:04:46.500
好拜拜
OK, bye bye.

0:04:46.500,0:04:47.514
嗯拜拜
Alright, bye bye.

0:04:48.075,0:04:49.750
过几天再下来
I will be coming this way in a few days

0:04:50.200,0:04:51.734
再下来弄青菜
to get some more vegetables. 

0:04:53.025,0:04:55.150
回到兜山（老家）被卡点卡住
I was stopped (visiting uncle) at the village check point.

0:04:56.800,0:04:59.300
因为像刚刚领导也说了
Because like just now the village chief has emphasized

0:04:59.500,0:05:01.250
这个疫情的严重性
this recent pandemic is seriously bad,

0:05:01.650,0:05:05.000
现在不能够走家串户也不能走亲戚
for now, we can not visit our neighborhood or relatives.

0:05:06.346,0:05:10.925
回家的话要想拿点东西让亲人拿到卡点来
If someone wants to get something from their family house, just ask a family member brings it to the village check point.

0:05:11.378,0:05:12.450
不过这样也好
but this practice is ok as well.

0:05:13.325,0:05:15.900
为了防止这个疫情扩散嘛
in order to prevent the virus spread out.

0:05:16.667,0:05:20.050
我自己回自己的老家居然被拦下来了
I still can't believe I was stopped while visiting my own family house.

0:05:20.225,0:05:22.450
我刚开始以为可以进去的
I thought I could get in.

0:05:23.475,0:05:25.250
就是要通行证嘛（我没有）
They require a pass (which I don't have).

0:05:26.487,0:05:30.475
回趟老家没回到自己家里面去
Went back hometown but didn't get to visit my family's house...

0:05:30.775,0:05:33.875
等这个疫情好一些有好转了
As soon as the epidemic gets somewhat better, 

0:05:33.875,0:05:34.905
就是彻底断根（结束）之后
I mean, when it is completely gone.

0:05:34.905,0:05:37.975
我们再进行一些
Then we can do something like

0:05:37.975,0:05:41.225
走亲戚呀走访啊不是走访
visiting relatives...interview...uh, not interview

0:05:41.225,0:05:41.825
就是
I meant

0:05:42.675,0:05:44.875
客串 串门
visiting others

0:05:46.975,0:05:49.273
久了没出门话都说不清楚了
I haven't left my house for so long, I can't talk clearly now.

0:05:52.575,0:05:54.600
好了本期视频就到这里了
OK, that is all for this episode.

0:05:55.375,0:05:59.750
我们农村也还是（管控）这么严格
Even in the country the management is very strict, 

0:06:00.475,0:06:01.725
挺好的
that is really nice.

**Comment by Jasminelv** [comment]
bot, please upload.
【美食作家王刚】回兜山看望四伯 - https://youtu.be/j5Aii36bknY
视频时长 6:06，预计发布时间为北京时间2月15日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.825,0:00:02.775
哈喽，大家好我是王刚
Hello everyone, I am Wang Gang.

0:00:03.400,0:00:07.850
在这个城里面，已经有十多二十天没有回（老）家了
I've been staying in the city for around 10-20 days without going to my family house of my home village.

0:00:07.850,0:00:10.150
今天回去看一下我四伯
Today I will go back and visit my Uncle.

0:00:10.525,0:00:15.154
这段时间，我四伯也没有去赶场卖肉
During these days, my uncle hasn't been the market to sell pork either.

0:00:20.200,0:00:23.950
十多二十天没开车，现在都有点生疏了
10-20 days of not driving, I am feeling a little bit rusty.

0:00:26.950,0:00:28.650
特别是戴上这个口罩
Especially when I am wearing this face mask..

0:00:28.650,0:00:30.275
我感觉我有点缺氧
I am feeling somewhat suffocating. 

0:00:31.575,0:00:35.025
现在也不知道我四伯那里有没有设卡（点）
Right now I don't even know if there is a check point established at my Uncle's (village).

0:00:36.275,0:00:38.050
还不知道进不进得去
Still not sure if I could go in or not.

0:00:39.100,0:00:40.950
不过应该没问题吧
...but at the same time, there shouldn't be a problem (I hope)...

0:00:40.950,0:00:44.800
因为是我老家我回自己祖屋应该没问题
Because that is my hometown, if I go back to my family house, shouldn't be a problem.

0:00:44.800,0:00:46.225
进应该是进得去
I should be allowed entry (of the village).

0:00:52.850,0:00:55.325
现在我们乡下还是没有什么车
Now in the country, there are still few cars on the road.

0:00:55.325,0:00:59.950
平时的话，像现在，应该在堵车
Usually, there is a traffic jam during this time of day.

0:00:59.950,0:01:02.875
然后排队通过
Cars go through here slowly bumper to bumper.

0:01:04.400,0:01:07.650
好了，我们现在已经到了乡村小道了
OK, now we are on the country road.

0:01:07.650,0:01:10.450
现在这个菜籽都开花了
Now the rapeseed flowers are blooming.

0:01:10.450,0:01:11.300
好漂亮啊
It is so pretty!

0:01:14.350,0:01:17.350
哦，在前面这个卡点设在前面
OK，there is a check point ahead.

0:01:20.670,0:01:21.825
也拉了横幅
There is also a banner....

0:01:22.470,0:01:25.875
我估计车的话，要停在外面进不去了
I suppose I have to park the car outside of the check point.

0:01:32.775,0:01:34.100
现在下去问一下
Let me ask them.

0:01:37.350,0:01:39.600
师傅我想把车停里面
Sir, I want to park my car inside.

0:01:39.600,0:01:40.100
咹？
What (are you talking about)?

0:01:40.100,0:01:41.350
我想把车停里面
I want to park my car inside.

0:01:41.350,0:01:42.150
你到哪里去嘛
Where are you heading to?

0:01:42.150,0:01:43.423
我就是张家湾的
I am a native of ZhangJiaWan (village name).

0:01:43.423,0:01:45.300
你是张家湾的？对
Are you a native of ZhangJiaWan?  (Sure.)

0:01:46.525,0:01:58.075
努力沟通中
(much communication going on)

0:02:03.700,0:02:05.200
我伯爷都出来接我来了
Even my uncle came to the check point to meet up with me.

0:02:07.125,0:02:09.000
外来人员不得进入
No outsiders are permitted of entry.

0:02:12.375,0:02:15.075
四伯爷，（我）给你拿了点水果下来
Uncle, I bring some fruit for you.

0:02:15.475,0:02:17.625
你拿起来，我还不是（喝）干了
You bring me some hard drinking alcohol? You know I would just finish it.

0:02:18.550,0:02:21.125
拿瓶酒给你喝，你呆屋头无聊
The drinks are for your long isolation days at home, I know you must be bored.

0:02:21.125,0:02:22.450
我还敢喝酒
I really shouldn't be drinking.

0:02:23.000,0:02:24.575
要得嘛，我慢慢晕（喝）嘛
Well, that's ok, I guess I could drink it slowly....

0:02:24.575,0:02:28.225
我给你找了个口罩，只有一个，你拿倒，将就用
I brought you a face mask, just one, you can use it for now.

0:02:28.225,0:02:29.425
屋头有， 还有几个
I have a few at home.

0:02:29.425,0:02:30.950
要的，戴倒，拿都给你拿起来了
OK, wear it now, I have brought it all the way here.

0:02:30.950,0:02:32.150
我都还有四五个
I have 4 or 5 myself.

0:02:32.150,0:02:32.950
戴倒嘛，四伯爷
Wear it now, Uncle.

0:02:32.950,0:02:33.600
要得呀
Fine.

0:02:35.301,0:02:36.625
我来戴
Let me put it on it for you.

0:02:36.900,0:02:39.875
我学会（戴口罩）了。这个东西你提到嘛
I have learnt how to put a mask on, just help me carrying these bags for now.

0:02:40.842,0:02:42.762
过年到现在还没来的（看你）呀? 没有.
Has ... visited you yet since the Chinese New Year?     Not yet.

0:02:43.825,0:02:45.750
今年还没（回来过）
... hasn't been back this year.

0:02:46.150,0:02:49.075
走下巴那里两根一起
Get into it from the chin, then lift the 2 strings.

0:02:50.289,0:02:52.081
我就是一哈就搞定
I can get it done in no time.

0:02:52.081,0:02:53.425
上面套下去也可以
It can also be worn from downside.

0:02:54.125,0:02:55.925
走这后面套进去
Get into it from the back.

0:02:56.200,0:02:57.750
我是这样戴的你看嘛
You see, this is how I wear it.

0:03:00.900,0:03:02.180
这个往下面
This string should be placed on the lower side.

0:03:02.180,0:03:05.000
这个放下面 一个挂耳朵上
This should be placed on the bottom, the other one hangs on the ear.

0:03:05.000,0:03:05.700
哦对
Yes, that is right.

0:03:05.800,0:03:07.413
我还是学会了的
I had learnt it.

0:03:07.413,0:03:09.175
鼻子还露在外面的，不得行
You nose should not be left outside of the mask.

0:03:09.175,0:03:10.925
这个拉起来就是了
It's fine, just pull it up.

0:03:11.075,0:03:13.575
拉起来给它按一下就贴紧了
Pull it up a little then press it down firmly here, it will snug to the face nicely.

0:03:13.575,0:03:15.125
往里面按一下
Press down a little like this.

0:03:15.125,0:03:19.125
就是撒， 就来了，合（适）了，是不是嘛？
That is right!  It fits perfectly, isn't it?

0:03:19.150,0:03:21.500
四伯爷，那这个东西拿给你（了），我就先走了
Uncle, since you've received my gifts, I'll head back to the city now.

0:03:21.675,0:03:24.650
那你等到，我回去给你挖几颗菜出来嘛
Wait for me here, I'll go get some veggies for you.

0:03:25.575,0:03:27.600
也可以，现在青菜也不好买
That is nice.  Veggies are short of supply these days in the city.

0:03:27.775,0:03:29.275
你的口罩戴归一（好）点
Wear your mask better,

0:03:30.000,0:03:31.825
这个稍微往下面按一下
press it down with some pressure here.

0:03:33.975,0:03:35.550
那我在这里等你嘛
I will be waiting for you here.

0:03:35.550,0:03:37.300
要的我去给你挖过来
Ok, I will go dig some veggies for you.

0:03:37.300,0:03:38.725
好
Great.

0:03:40.075,0:03:42.150
现在这个卡点卡在这里
I am now getting stopped here at the village's check point.

0:03:42.150,0:03:46.550
我们最好不去串门
It is better that we don't visit other people.

0:03:46.550,0:03:50.200
在卡点外面等我四伯回去给我弄点青菜
I'm waiting outside of the check point, waiting for my uncle to get some green veggies for me from his home garden.

0:03:52.000,0:03:53.300
扯好多哦四伯爷
That is a lot of (veggies), Uncle.

0:03:54.104,0:03:55.650
这不见得很多
Not much at all.

0:03:56.200,0:03:58.000
这还不见得很多 掉了
It is so much, some are falling off my hands.

0:03:58.750,0:04:00.225
这么多芹菜
So much (Chinese) celery.

0:04:01.225,0:04:02.575
放车里面
Put them in your car.

0:04:03.775,0:04:05.300
吃完了过后又来（挖菜）
When it is finished, come back and get s'more.

0:04:05.300,0:04:05.975
好
OK.

0:04:13.900,0:04:16.125
四伯爷这个时候猪肉好多钱一斤
Uncle, what is the market price for pork these days?

0:04:16.725,0:04:18.350
35（元一斤）
35 (Chinese RMB/500grams, about 1.1lbs)

0:04:18.350,0:04:21.275
乡头35城里38、40
In the town, 35.  In the city, 38 or 40.

0:04:21.425,0:04:23.425
成都卖45
The price in Chengdu (provincial capital city) is 45.

0:04:23.650,0:04:25.650
是不是有史以来最高的一次
Is it  the most historically high?

0:04:25.650,0:04:28.875
历史以来活上一百岁的人没吃过这么贵的猪肉
Even people who are more than 100 yrs old says the pork price has never been this high.

0:04:29.600,0:04:32.100
要得四伯爷我就拿起走了
Uncle, I will thank for your veggies and go home now.

0:04:32.100,0:04:32.825
要得
That is fine.

0:04:38.000,0:04:40.325
好了现在准备回家了
OK, now I am getting ready to head back home.

0:04:41.750,0:04:43.650
四伯在这里送我 
My uncle is seeing me off here at the check point.

0:04:43.650,0:04:44.625
开车慢点哈
Drive slowly okay?

0:04:44.625,0:04:45.525
走了四伯爷
I am leaving now, Uncle.

0:04:45.525,0:04:46.500
好拜拜
OK, bye bye.

0:04:46.500,0:04:47.514
嗯拜拜
Alright, bye bye.

0:04:48.075,0:04:49.750
过几天再下来
I will be coming this way in a few days

0:04:50.200,0:04:51.734
再下来弄青菜
to get some more vegetables. 

0:04:53.025,0:04:55.150
回到兜山（老家）被卡点卡住
I was stopped (visiting uncle) at the village check point.

0:04:56.800,0:04:59.300
因为像刚刚领导也说了
Because like just now the village chief has emphasized

0:04:59.500,0:05:01.250
这个疫情的严重性
this recent pandemic is seriously bad,

0:05:01.650,0:05:05.000
现在不能够走家串户也不能走亲戚
for now, we can not visit our neighborhood or relatives.

0:05:06.346,0:05:10.925
回家的话要想拿点东西让亲人拿到卡点来
If someone wants to get something from their family house, just ask a family member brings it to the village check point.

0:05:11.378,0:05:12.450
不过这样也好
but this practice is ok as well.

0:05:13.325,0:05:15.900
为了防止这个疫情扩散嘛
in order to prevent the virus spread out.

0:05:16.667,0:05:20.050
我自己回自己的老家居然被拦下来了
I still can't believe I was stopped while visiting my own family house.

0:05:20.225,0:05:22.450
我刚开始以为可以进去的
I thought I could get in.

0:05:23.475,0:05:25.250
就是要通行证嘛（我没有）
They require a pass (which I don't have).

0:05:26.487,0:05:30.475
回趟老家没回到自己家里面去
Went back hometown but didn't get to visit my family's house...

0:05:30.775,0:05:33.875
等这个疫情好一些有好转了
As soon as the epidemic gets somewhat better, 

0:05:33.875,0:05:34.905
就是彻底断根（结束）之后
I mean, when it is completely gone.

0:05:34.905,0:05:37.975
我们再进行一些
Then we can do something like

0:05:37.975,0:05:41.225
走亲戚呀走访啊不是走访
visiting relatives...interview...uh, not interview

0:05:41.225,0:05:41.825
就是
I meant

0:05:42.675,0:05:44.875
客串 串门
visiting others

0:05:46.975,0:05:49.273
久了没出门话都说不清楚了
I haven't left my house for so long, I can't talk clearly now.

0:05:52.575,0:05:54.600
好了本期视频就到这里了
OK, that is all for this episode.

0:05:55.375,0:05:59.750
我们农村也还是（管控）这么严格
Even in the country the management is very strict, 

0:06:00.475,0:06:01.725
挺好的
that is really nice.

**Comment by immoonancient** [comment]
已发布
