### ISSUE TITLE
【美食作家王刚】炸鲜奶 - https://youtu.be/MJuNod7VaSQ

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#672]
【美食作家王刚】炸鲜奶 - https://youtu.be/MJuNod7VaSQ
视频时长 4:09，预计发布时间为北京时间2月18日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.400,0:00:01.680
大家好 我是王刚

0:00:01.680,0:00:03.500
本期视频我给大家分享一道甜品

0:00:03.820,0:00:04.820
炸鲜奶

0:00:05.380,0:00:08.650
首先我们准备纯牛奶250克倒入碗中

0:00:08.650,0:00:11.475
不喜欢纯牛奶的同学可以用酸奶代替

0:00:14.775,0:00:17.850
然后加入玉米淀粉30克搅拌均匀备用

0:00:24.850,0:00:26.750
中途加入白糖30克

0:00:26.775,0:00:29.075
不喜欢甜味的同学可以不加

0:00:34.775,0:00:37.335
准备模具一个均匀地刷上食用油备用

0:00:37.335,0:00:39.575
刷油的目的是防止牛奶粘连

0:00:42.725,0:00:44.400
下一步开始准备煮奶

0:00:44.425,0:00:46.350
首先我们把锅洗干净

0:00:46.350,0:00:48.350
锅中最好不要有残留的油

0:00:50.475,0:00:52.750
牛奶下锅之后先开中火烧开

0:00:52.750,0:00:55.750
然后转小火边煮边搅拌以防止糊锅

0:00:55.750,0:00:58.800
煮的过程中必须随时观察牛奶稠度的变化

0:01:05.125,0:01:08.125
一旦牛奶变成粘稠性质之后即可关火出锅

0:01:09.375,0:01:11.950
然后将牛奶糊倒入刷满油的模具中

0:01:11.950,0:01:14.325
同学们也可以用比较浅的盘子

0:01:23.500,0:01:25.925
然后将其放入冰箱中冷藏一个小时

0:01:27.675,0:01:30.325
冷藏1小时之后将凝固的牛奶（糊）取出

0:01:30.350,0:01:32.375
然后切成大小均匀的条

0:01:48.850,0:01:51.950
切好之后放入碗中下一步开始准备挂糊

0:01:51.950,0:01:54.225
准备适量的面包糠倒入碗中（约50克）

0:01:54.225,0:01:57.175
然后将切好的奶糊均匀的粘上一层面包糠

0:01:57.175,0:01:59.275
粘好面包糠之后取出备用

0:02:14.700,0:02:17.425
准备鸡蛋2个打入碗中搅拌均匀备用

0:02:27.375,0:02:29.725
鸡蛋打散之后加入奶糊滚一遍

0:02:29.725,0:02:31.600
然后再粘上一层面包糠

0:02:31.600,0:02:34.250
这样的目的是将奶糊充分的粘上辅料

0:02:46.225,0:02:48.975
均匀的裹好原材料之后下一步开始制作

0:02:49.400,0:02:51.050
首先我们把锅烧热

0:02:51.050,0:02:53.075
锅烧热之后加入小宽油

0:03:01.350,0:03:04.075
油温5成热之后将奶糊依次下入锅中

0:03:13.250,0:03:15.325
然后转中小火炸1分钟

0:03:15.325,0:03:18.275
这一步的目的是将奶糊炸至表面金黄酥脆

0:03:18.275,0:03:21.125
同学们切记不能开大火否则容易炸糊

0:03:25.025,0:03:27.475
炸至1分钟之后即可出锅装盘

0:03:38.980,0:03:41.660
一道外酥里嫩的炸鲜奶就制作完成

0:03:49.380,0:03:51.380
下面开始技术总结

0:03:51.500,0:03:54.880
第一，牛奶可以根据自己的喜好选择不同的口味

0:03:54.880,0:03:58.980
第二，煮牛奶的时候必须小火慢煮，这样才能够均匀的受热

0:03:59.200,0:04:06.780
第三，奶糊下锅之前油温不能过高或者过低，最好将其保持在5成热，否则容易炸糊或者不够酥脆

0:04:06.780,0:04:08.660
炸鲜奶的技术总结完毕

**Comment by greentea007** [comment]
认领

**Comment by greentea007** [comment]
bot, please upload
【美食作家王刚】炸鲜奶 - https://youtu.be/MJuNod7VaSQ
视频时长 4:09，预计发布时间为北京时间2月18日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！
0:00:00.400,0:00:01.680
大家好 我是王刚
Hello, everyone, I’m Wang Gang
0:00:01.680,0:00:03.500
本期视频我给大家分享一道甜品
For this episode, I’m sharing a recipe for dessert with you.
0:00:03.820,0:00:04.820
炸鲜奶
Deep-fried milk
0:00:05.380,0:00:08.650
首先我们准备纯牛奶250克倒入碗中
Firstly, we need to pour 250 grams of milk into the bowl.
0:00:08.650,0:00:11.475
不喜欢纯牛奶的同学可以用酸奶代替
You can use yogurt instead of milk if you prefer.
0:00:14.775,0:00:17.850
然后加入玉米淀粉30克搅拌均匀备用
Secondly, add 30 grams of corn starch and fully whisk it up with milk.
0:00:24.850,0:00:26.750
中途加入白糖30克
Add 30 grams of sugar during the mixing.
0:00:26.775,0:00:29.075
不喜欢甜味的同学可以不加
You don’t have to add sugar if you prefer a lighter taste.
0:00:34.775,0:00:37.335
准备模具一个均匀地刷上食用油备用
Oil spray the cake mold.
0:00:37.335,0:00:39.575
刷油的目的是防止牛奶粘连
The propose of it is to prevent the milk from sticking on it
0:00:42.725,0:00:44.400
下一步开始准备煮奶
Next, we need to prepare to boil the milk.
0:00:44.425,0:00:46.350
首先我们把锅洗干净
Get a clean wok
0:00:46.350,0:00:48.350
锅中最好不要有残留的油
With no grease left on it.
0:00:50.475,0:00:52.750
牛奶下锅之后先开中火烧开
Pour our milk into the wok and heat it up after.
0:00:52.750,0:00:55.750
然后转小火边煮边搅拌以防止糊锅
Stir it while simmering on low heat.
0:00:55.750,0:00:58.800
煮的过程中必须随时观察牛奶稠度的变化
Always observe changes in milk consistency while simmering it.
0:01:05.125,0:01:08.125
一旦牛奶变成粘稠性质之后即可关火出锅
Once the milk became gooey, we can turn the heat off.
0:01:09.375,0:01:11.950
然后将牛奶糊倒入刷满油的模具中
Pour the milk into the oil sprayed mold.
0:01:11.950,0:01:14.325
同学们也可以用比较浅的盘子
or a shallow pan.
0:01:23.500,0:01:25.925
然后将其放入冰箱中冷藏一个小时
Put it in the refrigerator for an hour.
0:01:27.675,0:01:30.325
冷藏1小时之后将凝固的牛奶（糊）取出
Pull out the frozen milk after an hour in the refrigerator.
0:01:30.350,0:01:32.375
然后切成大小均匀的条
Slice it into strips.
0:01:48.850,0:01:51.950
切好之后放入碗中下一步开始准备挂糊
Next, prepare for the battering
0:01:51.950,0:01:54.225
准备适量的面包糠倒入碗中（约50克）
Get 50 grams of breadcrumbs
0:01:54.225,0:01:57.175
然后将切好的奶糊均匀的粘上一层面包糠
Dip the milk strips into the breadcrumbs
0:01:57.175,0:01:59.275
粘好面包糠之后取出备用
until well combined.

0:02:14.700,0:02:17.425
准备鸡蛋2个打入碗中搅拌均匀备用
Whisk 2 eggs in a bowl.
0:02:27.375,0:02:29.725
鸡蛋打散之后加入奶糊滚一遍
Dip the milk strips into the egg mixture.
0:02:29.725,0:02:31.600
然后再粘上一层面包糠
dip the milk into the breadcrumbs for the second time.
0:02:31.600,0:02:34.250
这样的目的是将奶糊充分的粘上辅料
The propose of it is making sure the milk strips are fully coated with breadcrumbs.
0:02:46.225,0:02:48.975
均匀的裹好原材料之后下一步开始制作
Now, we can move to the next phase.
0:02:49.400,0:02:51.050
首先我们把锅烧热
Heat up the wok
0:02:51.050,0:02:53.075
锅烧热之后加入小宽油
Pour Kuan You (literally “broad oil”) into the wok
0:03:01.350,0:03:04.075
油温5成热之后将奶糊依次下入锅中
Heat up the oil to 150°C and deep-fry the milk strips
0:03:13.250,0:03:15.325
然后转中小火炸1分钟
Turn the heat to medium-low for 1 minute.
0:03:15.325,0:03:18.275
这一步的目的是将奶糊炸至表面金黄酥脆
Until it is crunchy and golden-brown  
0:03:18.275,0:03:21.125
同学们切记不能开大火否则容易炸糊
Please remember to keep the heat low to prevent burning.
0:03:25.025,0:03:27.475
炸至1分钟之后即可出锅装盘
It will be ready after 1 minute of deep-frying 
0:03:38.980,0:03:41.660
一道外酥里嫩的炸鲜奶就制作完成
We’ve completed preparing a dish with crunchy paste and milky stuff, deep-fried milk. 
0:03:49.380,0:03:51.380
下面开始技术总结
Now, Let’s summarize the key techniques
0:03:51.500,0:03:54.880
第一，牛奶可以根据自己的喜好选择不同的口味
Firstly, you can choose all kinds of flavors of milk according to your preference.
0:03:54.880,0:03:58.980
第二，煮牛奶的时候必须小火慢煮，这样才能够均匀的受热
Secondly, When simmering the milk, you must simmer it on low heat so that you can heat the milk evenly.
0:03:59.200,0:04:06.780
第三，奶糊下锅之前油温不能过高或者过低，最好将其保持在5成热，否则容易炸糊或者不够酥脆
You must keep the oil at 150°C to making sure the milk strips are crunchy as we expect.
0:04:06.780,0:04:08.660
炸鲜奶的技术总结完毕
Above are all techniques for deep-fried milk.

**Comment by immoonancient** [comment]
已发布
