### ISSUE TITLE
【美食作家王刚】折耳根的介绍 - https://youtu.be/PsKNAxACtg8

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#679]
【美食作家王刚】折耳根的介绍 - https://youtu.be/PsKNAxACtg8
视频时长 1:16，预计发布时间为北京时间2月21日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.475,0:00:02.100
嗨喽大家好 我是王刚

0:00:02.100,0:00:05.700
最近收到有私信的粉丝在问这个折耳根怎么吃

0:00:05.700,0:00:08.350
今天我跟大家分享一下这个折耳根的吃法

0:00:08.350,0:00:10.800
这个是折耳根的根

0:00:10.800,0:00:12.575
它这个根上面有很多须

0:00:12.575,0:00:14.450
这个须已经被我们去掉了

0:00:14.450,0:00:17.450
然后这个根的话可以用来炒

0:00:17.450,0:00:21.500
然后也可以凉拌 还可以用来炖汤炖猪肺

0:00:21.500,0:00:24.300
我们这个凉茶里面就有这个成分

0:00:24.300,0:00:27.525
这个是润肺的这个折耳根

0:00:27.525,0:00:29.725
可以用来炖鸡炖猪肺

0:00:30.050,0:00:32.025
然后还有这个叶子

0:00:32.425,0:00:35.250
这个叶子的话在我们四川就比较多

0:00:35.250,0:00:39.250
因为我们随时在那个田埂上面都可以找得到这种折耳根

0:00:39.250,0:00:43.825
如果是说运输到外面的话可能你们只能够吃到这个根

0:00:43.825,0:00:46.400
就没有叶子 或者是叶子比较少

0:00:46.425,0:00:49.867
我们四川这个叶子喜欢用那个辣椒油

0:00:49.867,0:00:54.525
用来把它辣椒蒜辣椒油一起拌 拌来吃

0:00:54.525,0:00:59.650
然后这个根的话我们本地有很多餐饮（店）他会用这个根切碎

0:00:59.650,0:01:01.650
切碎来做烤鱼

0:01:01.650,0:01:03.275
味道也非常的突出

0:01:03.275,0:01:07.050
然后有的人吃不惯这个菜

0:01:07.050,0:01:09.400
它就跟香菜一样因为吃起来是臭的

0:01:09.400,0:01:11.800
如果你吃得惯的话这个就是香的

0:01:11.800,0:01:14.200
好啦本期视频就跟你们分享到这里

0:01:14.200,0:01:15.150
拜拜

**Comment by WuStevenShengyang** [comment]
我來吧

**Comment by immoonancient** [comment]
> 我來吧

微信群里有一位之前认领了，先等等吧

**Comment by iamatrollatrollisme** [comment]
回复这里

**Comment by iamatrollatrollisme** [comment]
bot, please upload
0:00:00.475,0:00:02.100
嗨喽大家好 我是王刚
Hello everyone, I am Wang Gang.
0:00:02.100,0:00:05.700
最近收到有私信的粉丝在问这个折耳根怎么吃
Recently I have received private message from fans about how to cook fish mint
0:00:05.700,0:00:08.350
今天我跟大家分享一下这个折耳根的吃法
Today I am going to share the way to handle fish mint
0:00:08.350,0:00:10.800
这个是折耳根的根
This is the root of fish mint
0:00:10.800,0:00:12.575
它这个根上面有很多须
There are many deep roots on the tap root
0:00:12.575,0:00:14.450
这个须已经被我们去掉了
We have taken off the deep root
0:00:14.450,0:00:17.450
然后这个根的话可以用来炒
We can stir fry the tap root
0:00:17.450,0:00:21.500
然后也可以凉拌 还可以用来炖汤炖猪肺
As well as making into cold dish(salad) or make soup with pig lung
0:00:21.500,0:00:24.300
我们这个凉茶里面就有这个成分
Sometimes we make herbal tea with fish mint
0:00:24.300,0:00:27.525
这个是润肺的这个折耳根
Fish mint helps with clearing our lungs
0:00:27.525,0:00:29.725
可以用来炖鸡炖猪肺
We can stew fish mint with chicken or pig lung
0:00:30.050,0:00:32.025
然后还有这个叶子
The leaf of fish mint
0:00:32.425,0:00:35.250
这个叶子的话在我们四川就比较多
The leaf of fish mint is quite common in Sichuan
0:00:35.250,0:00:39.250
因为我们随时在那个田埂上面都可以找得到这种折耳根
We can pretty much find fish mint on farmland any time
0:00:39.250,0:00:43.825
如果是说运输到外面的话可能你们只能够吃到这个根
Outside of Sichuan, you might only be able to find the root of fish mint
0:00:43.825,0:00:46.400
就没有叶子 或者是叶子比较少
There isn’t any leaf or very few leaves
0:00:46.425,0:00:49.867
我们四川这个叶子喜欢用那个辣椒油
In Sichuan we like to use mix the fish mint with chili oil
0:00:49.867,0:00:54.525
用来把它辣椒蒜辣椒油一起拌 拌来吃 
Eat them together as spicy fish mint salad
0:00:54.525,0:00:59.650
然后这个根的话我们本地有很多餐饮（店）他会用这个根切碎
We have many local restaurants will chop the fish mint
0:00:59.650,0:01:01.650
切碎来做烤鱼
Mix the chopped fish mint with fish to make grilled fish
0:01:01.650,0:01:03.275
味道也非常的突出
The taste stands out very much
0:01:03.275,0:01:07.050
然后有的人吃不惯这个菜
Some people are not used to the taste
0:01:07.050,0:01:09.400
它就跟香菜一样因为吃起来是臭的
Because it has unique unpleasant taste for some people, like cilantro
0:01:09.400,0:01:11.800
如果你吃得惯的话这个就是香的
If you are used to the unique taste, you will love it
0:01:11.800,0:01:14.200
好啦本期视频就跟你们分享到这里
Okay, this is what I’d like to share with you today
0:01:14.200,0:01:15.150
拜拜
Bye bye

**Comment by immoonancient** [comment]
已发布
