### ISSUE TITLE
[华农兄弟] 华农兄弟小黑的崽越来越胖了看起来很肥抓来玩一下 - https://youtu.be/D3zp36n12IM

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#694]
https://youtu.be/D3zp36n12IM
<p>&#35270;&#39057;&#21457;&#24067;&#20110; February 19, 2020 at 08:45PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/D3zp36n12IM

#华农兄弟：小黑的崽越来越胖了，看起来很肥，抓来玩一下
#Huanong Brothers: Blacky's child is getting bigger and bigger. It looks really fat. Let's catch it and have some fun.

0:00:00.500,0:00:01.660
# 這個小黑的崽
This is Blacky's child.

0:00:02.080,0:00:03.080
# 那麼胖的哦
He's so fat now.

0:00:04.020,0:00:04.620
# 小黑
Blacky!

0:00:09.020,0:00:10.300
# 一身肥膘
He's covered with fat.

0:00:12.320,0:00:14.040
# 不知道為甚麼它吃的[SIC]那麼胖
I have no ideas why he is that fat.

0:00:14.040,0:00:15.080
# 別的都沒那麼大
The others are not that big.

0:00:15.420,0:00:17.260
# 就它的那 就它這隻那麼大
But he is, this is exceptionally big.

0:00:18.860,0:00:20.120
# 它太能吃啦  可能
He is a big eater, perhaps.

0:00:20.700,0:00:21.520
# 吃太多啦
He eats too much.

0:00:21.800,0:00:23.580
# 你看一下你  長了多少個月
Look at yourself! How old are you?

0:00:23.900,0:00:25.680
# 長了半年啦  沒人家大
You're already half an year old now, but still not as big as him.

0:00:26.260,0:00:29.000
# 人家才一個多月  就長成這樣子啦
He's just a month old, and is already that big now.

0:00:30.040,0:00:30.600
# 哦
Oh!

0:00:31.920,0:00:32.420
# 小黑
Blacky!

0:00:34.100,0:00:35.000
# 你看  它的爪子
Look! His paws are,

0:00:35.160,0:00:36.580
# 好大啊  它的爪子
so big, his paws.

0:00:38.260,0:00:39.600
# 比別人胖了一半
He's one half of the others.

0:00:40.160,0:00:41.480
# 它這個毛豎起來的
His fur is standing.

0:00:41.600,0:00:42.720
# 其實沒那麼胖的
In fact he's not really that fat.

0:00:43.620,0:00:44.840
# 看上去就那麼胖
But he looks really fat.

0:00:45.600,0:00:46.480
# 它也不叫了哦
He's not yelping anymore.

0:00:46.600,0:00:48.140
# 以前它  我一摸它  它就
He used to start screaming immediately whenever,

0:00:49.100,0:00:50.760
# 開始叫起來  現在它都不叫啦
whenever I touched him. But now he's not screaming anymore.

0:00:51.600,0:00:52.520
# 跟我熟悉啦
He knows me well now.

0:00:53.880,0:00:54.580
# 哦  小狗
Oh! Puppy!

0:00:57.460,0:00:58.760
# 你看它  眼睛
Look at him, his eyes are

0:01:00.540,0:01:01.680
# 默默無聞的
speechless.

0:01:02.920,0:01:03.420
# 是啊
Indeed.

0:01:03.740,0:01:05.260
# 隨便你把它怎麼樣都行
You can simply do whatever you like on him.

0:01:05.560,0:01:07.520
# 它 反正它就是   不反抗  (註︰把這兩句合一較易處理)
He's, he's not fighting back anyway.

0:01:13.900,0:01:14.980
# 吃的好多哇
He eats so much.

0:01:17.480,0:01:19.060
# 撓它痒痒它也沒反應
He has no response even if I tickle him.

0:01:19.180,0:01:20.080
# 要聽話哦
Be a good boy! Got it?

0:01:20.720,0:01:21.800
# 不聽話我就把你
Otherwise I'll,

0:01:22.400,0:01:23.140
# 拿來送人
give you to other people,

0:01:23.400,0:01:24.320
# 送給兄弟
to my buddy.

0:01:26.380,0:01:27.020
# 不知不道
Got it?

0:01:27.740,0:01:29.820
# 等天晴啦  我把它洗一下澡 (註︰他的洗澡應該只是拋到河裡洗兩下)
I'll bathe you when it's sunny.

0:01:33.220,0:01:34.260
# 看著我幹嘛
Why are you looking at me?

0:01:34.640,0:01:36.160
# 給你洗一個澡  看你一身
I said I'll bathe you. You see you're,

0:01:36.860,0:01:37.820
# 一身都好髒
you're covered with dirt.

0:01:38.020,0:01:39.620
# 從出生到現在都沒有洗過澡
You've never taken a bath since you were born.

0:01:41.780,0:01:42.740
# 它一直看著我
He keeps staring at me.

0:01:43.680,0:01:44.680
# 怎麼  不認識我一樣
It's like, as if he doesn't know me.

0:01:45.380,0:01:46.260
# 天天餵你
I feed you everyday.

0:01:46.440,0:01:47.400
# 你怎麼不認識我
You should know me well.

0:01:49.180,0:01:51.620
# 呵呵  腳翹起來  不敢動
Hm hm, he stretches his legs straight, and dares not move.

0:01:52.280,0:01:53.380
# 你是不是不敢動嗎
Don't you dare to move?

0:01:56.000,0:01:56.620
# 小黑
Blacky,

0:01:56.680,0:01:57.580
# 這是你的崽
this is your boy.

0:01:57.800,0:01:59.220
# 就是你把它餵的那麼胖的
Because of you, he's so fat now.

**Comment by immoonancient** [comment]
PR 已 merge，不知为何显示错误

**Comment by vincenthychow** [comment]
已發佈
