### ISSUE TITLE
[华农兄弟] 摘艾草做米果 - https://youtu.be/mgV9i9mQKVU

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#698]
https://youtu.be/mgV9i9mQKVU
<p>&#35270;&#39057;&#21457;&#24067;&#20110; February 21, 2020 at 11:32AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/mgV9i9mQKVU

#华农兄弟：春天了，摘点艾草来做米果，圆圆的很好吃哦
#Huanong Brothers: It's spring. We pick some mugwort to make some rice cames. They're round and tasty!


0:00:03.900,0:00:07.180
# 大家好  今天我摘點這個艾草來做這個艾油果  (註︰他說的應該是客家話)
Hi everyone! Today I'm gonna pick some mugwort to make some mugwort rice cake.

0:00:07.640,0:00:08.640
# 現在春天啦
It's now spring,

0:00:09.060,0:00:10.500
# 這個艾草都長起來啦
and the mugwort has just started growing.

0:00:11.080,0:00:12.500
# 剛剛露出尖來
You can only see the tips.

0:00:13.280,0:00:15.720
# 我就把它摘回去  這樣才夠嫩
I pick them now, to ensure the freshness.

0:00:17.460,0:00:20.700
# 如果夏天的話  這個艾草老啦  就不好吃啦
The mugwort will become too old in summer and it won't taste good.

0:00:21.060,0:00:22.760
# 這個很嫩的哦  剛剛
It is really young. It has just,

0:00:23.300,0:00:24.440
# 剛剛長出來的
it has just started growing.

0:00:26.080,0:00:27.540
# 我們把嫩的摘掉就好啦
We pick only the young ones.

0:00:28.480,0:00:30.160
# 我們把它摘掉又長出來的
Once we pick it, it grows again.

0:00:30.840,0:00:32.080
# 它自己會長出來
It grows all by itself.

0:00:32.860,0:00:33.600
# 你看 這裡
Look! Here,

0:00:34.080,0:00:35.060
# 這裡好多哇
here's a lot!

0:00:44.300,0:00:46.160
# 這個  摘的時候
I mean, when you're picking,

0:00:46.440,0:00:48.400
# 一定要看清楚  別摘錯啦
you need to be very careful. Don't pick the wrong one.

0:00:49.500,0:00:50.140
# 有一種
There's one,

0:00:50.800,0:00:52.840
# 有一種草跟這個很像的哦
there's one which looks very similar to it.

0:00:54.440,0:00:56.560
# 別摘錯了就吃了就拉肚子就完啦 (註︰這句文法有點錯亂)
Pick the wrong one, eat it, then get a bad tummy and good luck

0:00:58.720,0:01:00.060
# 好香啊  這個艾草
The mugwort smells really good!

0:01:01.020,0:01:01.760
# 好有味道
It's so aromatic.

0:01:03.180,0:01:04.120
# 比較新鮮
It's quite fresh.

0:01:05.460,0:01:06.800
# 好多  好多都還沒長起來
Many, many have not yet grown.

0:01:06.920,0:01:08.180
# 這一片就長起來啦
But those here have already grown up.

0:01:09.120,0:01:11.240
# 可能這一片的陽光比較充足
Perhaps the sunshine here is better.

0:01:19.120,0:01:21.340
# 這可以  也可以直接炒來吃的  這個
It can be, it can be fried and eaten right away, I mean,

0:01:21.720,0:01:22.220
# 艾草
the mugwort.

0:01:25.400,0:01:26.280
# 你看  夠啦
Look! It's enough.

0:01:26.520,0:01:27.360
# 不要摘那麼多
Don't pick too much.

0:01:28.220,0:01:30.240
# 留  留一點給老人家摘一下
I shall leave, leave some for the elderly.

0:01:30.580,0:01:32.200
# 不要全部摘光啦  就不好啦
Don't pick them all. It's not nice.

0:01:34.660,0:01:36.140
# 哇  很香啊
Wa! It smells so good!

0:01:37.080,0:01:39.420
# 很濃的那個  那個  這個艾草味
It has a rich, rich, I mean, scent of mugwort.

0:01:45.840,0:01:46.820
# 那螞蟻
An ant!

0:01:47.700,0:01:48.700
# 咬我一口
It bit me!

0:01:51.720,0:01:52.660
# 好 回去啦
Alright! Let's go back!

0:02:01.140,0:02:17.720
# (註︰不知在說甚麼，但也說明一下為何沒有翻譯吧)
Conversations in Hakka dialect

0:02:21.260,0:02:23.740
# 這個 把這個撞qi的這個  洗一下
Let me wash the, the, here of the "zhong qi" (grinding pole).

0:02:25.000,0:02:26.940
# 我也不知道叫甚麼  管它
I have no ideas how it's called. Who cares.

0:02:30.780,0:02:31.720
# 把這個艾草
Now I wash the mugwort,

0:02:32.000,0:02:33.100
# 洗乾淨
wash it thoroughly.

0:02:38.880,0:02:40.380
# 這個艾草把它放下去
Now I put the mugwort onto the mortar,

0:02:41.360,0:02:42.420
# 直接搗爛就行啦
smash it, and done.

0:02:54.100,0:02:55.320
# 摘這個有點累的哦
This job is a bit tiring, you know.

0:02:56.140,0:02:57.820
# 這個手臂 手臂很酸
I can feel the sore, the sore on my arm.

0:03:00.800,0:03:02.840
# 有這個東西就很快就把它搗爛啦
It doesn't take too much time, with this stuff.

0:03:03.480,0:03:05.720
# 要我 我把它打成稀巴爛的那一種
I, ah, I need to smash it to some kind of a paste,

0:03:06.720,0:03:07.960
# 把它打成黏黏的
the sticky one.

0:03:08.800,0:03:09.460
# 就可以啦
That would be good.

0:03:11.240,0:03:13.040
# 然後我們直接放那個麵粉下去
Then we can put in the flour right away.

0:03:13.100,0:03:14.220
# 不是  糯米粉
I mean, sweet rice flour.

0:03:15.160,0:03:15.980
# 摘那糯米粉
Yea, sweet rice flour.

0:03:29.220,0:03:29.740
# 好啦
Alright!

0:03:30.600,0:03:32.100
# 已經把它接的
It has already been ground,

0:03:32.340,0:03:33.140
# 稀巴爛啦
into a paste.

0:03:36.600,0:03:37.940
# 我把這個撈起來
Let me put it here.

0:03:47.680,0:03:49.420
# 把它帶回去  這個是兄弟家的
I'll bring it back. It's my buddy's.

0:03:49.760,0:03:50.860
# 等一上來洗一下
I'll have it washed first.

0:03:51.720,0:03:52.880
# 我先要加點鹽
I put some salt first.

0:03:56.720,0:03:57.820
# 你的手不要搞
Watch your hands! Don't touch!

0:03:59.480,0:04:00.300
# 應該夠啦
It should be enough.

0:04:00.560,0:04:02.000
# 加點這個  不夠
Put some more, you know. It's not enough.

0:04:02.480,0:04:03.400
# 太稀啦
It's too soft.

0:04:06.900,0:04:08.080
# 粉放多啦
And now it's too much.

0:04:09.440,0:04:11.160
# 我只要這邊的  那邊的不要
Okay, I take only the flour on this side, not that side.

0:04:13.660,0:04:15.940
# 你看  這個就很靚  這個
Look! So it's now really beautiful, isn't it?

0:04:16.860,0:04:18.500
# 很濕潤  剛剛好
The moisture is good, perfect!

0:04:18.600,0:04:19.720
# 我們做成丸子
We'll make it into balls.

0:04:20.080,0:04:22.980
# 以前是燒餅一樣的  現在做成小丸子
We used to make it into discs. But this time we make balls.

0:04:25.720,0:04:27.360
# 這樣  像個鳥蛋一樣
That's it! Just like a bird egg.

0:04:35.140,0:04:37.000
# 你看  我把它做成小丸子
Look! I make it into balls.

0:04:40.280,0:04:41.300
# 一個一個
One by one

0:04:42.820,0:04:45.560
# 不要讓他們挨在一起  挨在一起它們就粘在一起啦
Put them separately. Otherwise they would stick together.

0:04:55.620,0:04:56.940
# 你看  這個圓的
Look! These are round.

0:04:57.500,0:04:58.120
# 做了一盤子
So here's a whole plate of them.

0:04:58.720,0:05:01.640
# 先  先煎著它來  然後我們再做這個  (註︰我不區分他的煎炒炸了，反正都要倒到一堆油裡去)
I'll fry, fry them first. Then I'll come to the rest.

0:05:01.900,0:05:04.620
# 這個鍋已經燒熱了 我加點油下去
The, the wok is already heated. So I'll now put the oil.

0:05:10.740,0:05:11.500
# 加多一點
I need more.

0:05:15.800,0:05:16.700
# 好  可以啦
Good! It's alright now.

0:05:25.700,0:05:26.820
# 把這也放下去
Put them into the wok too.

0:05:28.940,0:05:29.480
# 誒
Ay!?

0:05:29.780,0:05:30.600
# 可以喲
It's not bad.

0:05:32.140,0:05:33.180
# 已經夠燙啦
It's already hot enough.

0:05:33.440,0:05:34.320
# 這個很快的哦
It won't take long.

0:05:35.860,0:05:38.040
# 像公雞下蛋一樣  一個一個往下
Drop them down one by one, like a cock laying eggs.

0:05:38.540,0:05:39.420
# 往下掉
Throw it in.

0:06:03.660,0:06:04.180
# 哎喲
Ayo!

0:06:04.340,0:06:05.360
# 會爆炸的
It bursts.

0:06:19.700,0:06:21.820
# 你看  它裡面都熟了的  哦
Look! It's also well cooked inside.

0:06:23.580,0:06:24.840
# 你看  小黑都跑回來啦
Look! Blacky has also come back.

0:06:25.780,0:06:27.140
# 來喲  給點給你吃
C'mon! I give you some.

0:06:28.700,0:06:29.480
# 不要吐掉哦
Don't spit it out!

0:06:30.440,0:06:31.160
# 吃掉哦
Swallow it!

0:06:32.780,0:06:33.600
# 直的吃
She did it.

0:06:35.740,0:06:36.560
# 雙胞胎
Twins

0:06:45.120,0:06:45.700
# 好啦
Alright!

0:06:46.060,0:06:47.420
# 今天的視頻就到這裡啦
The video ends here.

0:06:49.120,0:06:51.120
# 留  留給他們  吃一下
I'll leave, leave some for them.

0:06:52.300,0:06:53.620
# 不能一個人全吃啦
I shouldn't finish it alone.

**Comment by vincenthychow** [comment]
已發佈
