### ISSUE TITLE
[华农兄弟] 华农兄弟帮老妈犁一下田再去小河里面划一下水 - https://youtu.be/flR4s6OoUjk

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#706]
https://youtu.be/flR4s6OoUjk
<p>&#35270;&#39057;&#21457;&#24067;&#20110; February 22, 2020 at 05:32PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/flR4s6OoUjk

#华农兄弟：帮老妈犁一下田，再去小河里面划一下水
#Huanong Brothers: I help my mom plough the field and then we have some fun in the river.

0:00:00.000,0:00:01.660
# 大家好  今天天氣比較好
Hi everyone! The weather today is quite good.

0:00:01.660,0:00:03.540
# 我幫我老媽犁一下那個田
I'm gonna help my mom plough the field.

0:00:03.960,0:00:06.260
# 因為那個犁那個田  那工作量有點大
Cuz, you know, ploughing the field is rather physically demanding.

0:00:06.320,0:00:08.940
# 它老是要抖  抖的全身都不舒服的
It shakes and shakes and shakes. It makes you feel really awful.

0:00:09.220,0:00:10.740
# 所以幫她搞一下
That's why I'm helping her,

0:00:10.940,0:00:11.900
# 她就沒那麼累
to share her burden.

0:00:11.900,0:00:13.760
# 用來種一些蔬菜之類的 (註︰這句很奇怪，應該是突然轉換話題)
It's for plant, planting the veggies or whatever.

0:00:14.000,0:00:14.920
# 在這上面一點
It's just a bit up there.

0:00:22.080,0:00:23.520
# 我先把那個火打著
I start the engine first.

0:01:10.900,0:01:12.680
# 搞這個腰有一點累的哦
This work is rather tiring for the lower back.

0:01:12.760,0:01:16.700
# 這個腰啊  很累的  它要這樣  這樣駝背  駝著
I mean the lower back, is really tired. You need to bend, bend you back, like this.

0:01:17.080,0:01:18.280
# 所以這個腰很累
So the lower back is really tired.

0:01:18.780,0:01:19.960
# 我去拿一個
I'm gonna fetch a,

0:01:20.220,0:01:22.400
# 拿一個那個床單  到河邊水  (註︰那不是床單好吧....)
fetch a, well, a sleeping mat, to the riverside.

0:01:23.040,0:01:24.320
# 河邊去游一下游
to the riverside and have a swim.

0:01:25.160,0:01:28.180
# 不是游泳  坐一下那個  那個水船
No, not swim. I mean, have a ride one a, you know, a boat,

0:01:28.700,0:01:29.880
# 那河裡面
on the river.

0:01:30.400,0:01:31.620
# 哇  太累啦
Wa! I'm exhausted.

0:01:34.460,0:01:37.920
# 把這個  這個床單丟到河裡面去
Let me throw the, throw the sleeping mat onto the river first.

0:01:38.180,0:01:40.240
# 等一下  我就直接跳到上面去就行弓
Then I can, simply hop onto it right away.

0:01:40.540,0:01:41.540
# 哎喲
Ayo!

0:01:41.840,0:01:42.840
# 那麼深的
It's so deep!

0:01:48.060,0:01:49.060
# 踩了一個坑
I stepped into the pit.

0:02:03.660,0:02:05.060
# 差一點就摔下去啦
I almost fell.

0:02:07.900,0:02:08.720
# 可以喲
It's not bad!

0:02:10.420,0:02:11.080
# 不要棍  (唔愛掍)
I don't need the pole!

0:02:19.040,0:02:19.720
# 可以喲
It's not bad!

0:02:19.860,0:02:21.180
# 就這樣漂著  讓它漂
So it's drifting. Just let it drift.

0:02:21.460,0:02:23.540
# 漂到哪裡算哪裡  反正下面過不行
It doesn't matter where it drifts to. The downstream is blocked anyway.

0:02:43.280,0:02:44.320
# 怕不怕
Are you scared?

0:03:05.100,0:03:06.520
# 氣死我啦  (註︰以往這句我會譯"Damn it"，但這次出自刘星辰....)
You guys are too bad!

0:03:09.120,0:03:10.580
# 扔石頭去
I'll throw them a rock!

0:03:11.700,0:03:12.640
# 不要扔 刘星辰
Don't throw! Liu Xinchen!

0:03:12.760,0:03:13.380
# 不要扔
Don't throw!

0:03:18.400,0:03:20.120
# (刘星辰，聽話一點哦)
Liu Xinchen, be a good boy!

0:03:20.720,0:03:23.280
# (睡覺呀，你怕不怕？)
Have a nap. Are you scared?

0:03:25.300,0:03:26.180
# 刘星辰
Liu Xinchen!

0:03:30.640,0:03:32.160
# (不可以  上來玩  上來玩
No! Come up here, up here!

0:03:33.460,0:03:36.180
# 怕不怕  去  把你抱上去  快點
Are you scared? C'mon! I'll take you back. C'mon!

0:03:37.020,0:03:38.520
# (過來  刘星辰)
Come here! Liu Xinchen!

0:03:39.680,0:03:42.140
# (刘星辰過來 快點)    (註︰這以下很多對話都沒有字幕，我把聽得懂的都做一點，讓不懂中文的觀眾可以更投入)
Liu Xinchen! Come here! Hurry up!

0:03:43.920,0:03:47.180
# (等一下來  等一下來  XX就會給你們啊)
A moment, a moment! I'll be your turn.

0:03:53.140,0:03:54.160
# (啊 我來)
Let me take her!

0:03:56.840,0:03:57.860
# (上來啊 妹妹)
Come here, girl!

0:03:58.760,0:03:59.500
# (上來啊)
Come here!

0:04:00.620,0:04:01.680
# (她不抓)
She's not holding.

0:04:04.440,0:04:05.900
# (不要去啊)
Stay here!

0:04:38.340,0:04:39.860
# (走啦 刘星辰)
We're leaving, Liu Xinchen!

0:04:58.865,0:04:59.865
# (你爸爸也起來啦)
You dad is also coming.

0:05:04.320,0:05:07.160
# (等一下  把你爸爸帶上來了哈)
Stay here! I'll take your dad up, alright?

0:05:35.640,0:05:39.540
# 在農村  在家裡 經常陪一下小孩很開心的
It's really happy to be with the children more often when we're at home, in the village.

0:05:40.080,0:05:41.440
# 哦  開不開心
Oh! Are you happy?

0:05:42.260,0:05:43.140
# 開不開心
Are you?

0:05:43.600,0:05:44.280
# 她要上來
She wants to get down.

0:05:45.460,0:05:47.540
# 多開心 跑啦
She's so happy, that she runs away.

0:05:48.580,0:05:49.360
# 我要帶小孩
I go to look after her.

0:05:51.320,0:05:52.180
# 怕摔跤
Watch out! Don't fall!

0:06:09.040,0:06:10.000
# 握握手
Shake hand with me.

0:06:10.400,0:06:11.880
# 它不會  不肯
It can't, or it doesn't want to.

0:06:12.280,0:06:14.300
# 它跟公雞在一起  公雞啄它
It's with the cock. Hey cock! Peck it!

0:06:15.120,0:06:16.140
# 不聽話
Naughty!

0:06:28.280,0:06:29.220
# 它不理我
It ignores me.

0:06:32.380,0:06:33.460
# 送一朵花給你
We give you a flower.

0:06:34.900,0:06:36.240
# 一丟  送給它
Throw, throw it the flower.

0:06:36.680,0:06:37.600
# 問它要不要
Ask if it wants the flower.

0:06:38.220,0:06:39.660
# 跟它說  問它要不要
Say it! Ask if it wants.

0:06:42.000,0:06:43.680
# 這個  這個是公貓來的
This, this cat is male.

0:06:43.900,0:06:45.140
# 肯定不要花啦
Certainly it doesn't want a flower.

0:06:45.760,0:06:46.860
# 看到花都跑
It runs away from flowers.

0:06:47.360,0:06:48.040
# 小貓
Kitty!

0:06:50.540,0:06:51.280
# 把它撿回來
Let me pick it up.

0:06:54.920,0:06:57.420
# 啊  我把這個花花扎到你頭髮上  好不好
Ah! Let me put this flower onto your hair, shall I?

0:07:00.660,0:07:02.560
# 扎到一個新花
You have a new flower.

0:07:03.640,0:07:05.820
# 不要動  不要動  不要動  別動
Don't move, don't move, don't move, don't move

0:07:06.860,0:07:09.040
# 好啦  你看一下  靚不靚
Alright! Have a look. Is it beautiful?

0:07:09.160,0:07:10.620
# 很靚哦  是不是
It's so beautiful, isn't it?

0:07:11.680,0:07:13.920
# 別坐下去   好髒  站起來
Don't sit here. It's so dirty. Stand up!

0:07:14.220,0:07:14.740
# 走啦
Let's go!

0:07:16.200,0:07:18.500
# 貓貓不要  它不要
Kitty doesn't want it, it doesn't.

0:07:18.800,0:07:20.620
# 扎到你頭髮上啦  很靚了啊
It's now on your hair. It so beautiful, isn't it?

0:07:28.260,0:07:29.280
# 要不要肉哦
Do you want some meat?

0:07:29.880,0:07:30.720
# 要不要雞腿
Or a chicken leg?

0:07:32.640,0:07:33.460
# 它不要
It doesn't.

0:07:35.740,0:07:37.520
# 一群鴨子  就剩下這兩個啦
Only these two ducks remain from a whole herd of them.

0:07:38.720,0:07:39.900
# 全部被吃光啦
All have been eaten.

0:07:42.200,0:07:43.960
# 啊~啊~啊~啊  下個蛋出來
Ah~ah~ah~ah! Lay an egg!

**Comment by vincenthychow** [comment]
已發佈
