### ISSUE TITLE
【美食作家王刚】鱼腥草猪肺汤 - https://youtu.be/NYs4Fk59QFw

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#707]
【美食作家王刚】鱼腥草猪肺汤 - https://youtu.be/NYs4Fk59QFw
视频时长 6:20，预计发布时间为北京时间2月24日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.400,0:00:01.560
哈喽大家好 我是王刚

0:00:01.560,0:00:03.020
本期视频我给大家分享

0:00:03.240,0:00:04.860
鱼腥草猪肺汤

0:00:05.480,0:00:07.900
首先我们准备新鲜的猪肺1副

0:00:08.575,0:00:11.175
然后用水管对着气管灌入清水

0:00:13.600,0:00:16.550
灌满清水之后用牙签将其戳出小洞

0:00:17.775,0:00:20.225
这一步的目的是循环猪肺中的脏水

0:00:21.575,0:00:24.550
灌水满之后再倒出反复灌洗十遍以上

0:00:24.800,0:00:27.400
中途可以挤压猪肺让其快速循环

0:00:27.400,0:00:29.775
直到清洗为粉红色或者白肺为止

0:00:30.875,0:00:32.475
下一步开始初加工

0:00:33.450,0:00:36.200
首先将猪肺气管上依附的淋巴取下

0:00:36.750,0:00:39.525
淋巴不适合食用所以必须去除干净

0:00:52.500,0:00:54.600
下一步开始准备辅料

0:00:54.850,0:00:57.225
准备生姜2块拍散之后备用

0:00:59.500,0:01:01.525
准备小葱几根挽成结备用

0:01:03.400,0:01:04.725
下一步开始焯水

0:01:05.275,0:01:07.500
首先在锅中加入大半锅清水

0:01:12.725,0:01:14.675
然后加入准备好的姜葱

0:01:16.300,0:01:18.475
将猪肺冷水下锅焯水10分钟

0:01:18.475,0:01:20.875
这一步的目的是将猪肺定型

0:01:34.750,0:01:36.325
中途加入适量的白酒（约15克）

0:01:39.375,0:01:41.375
大火烧开之后再撇去浮沫

0:01:48.000,0:01:50.250
10分钟之后将猪肺捞出

0:01:59.750,0:02:01.825
然后将猪肺改刀切成小块

0:02:01.825,0:02:04.600
这一步的目的是让猪肺能够充分焯水

0:02:19.250,0:02:21.675
将猪肺切好之后准备再次焯水

0:02:22.075,0:02:24.107
然后锅中加入适量的清水

0:02:24.550,0:02:27.125
将切好的猪肺下锅焯水10分钟

0:02:37.300,0:02:39.850
中途继续加入适量的白酒去腥

0:02:50.700,0:02:52.300
10分钟之后捞出

0:03:06.150,0:03:08.575
捞出之后放入清水中清洗2遍

0:03:08.575,0:03:11.450
这一步的目的是去除猪肺中间的脏东西

0:03:37.650,0:03:39.775
然后将猪肺切成小片备用

0:03:55.025,0:03:57.400
切成小片之后加入食用盐1小把

0:03:58.475,0:03:59.900
加入少许白醋

0:03:59.900,0:04:01.825
然后抓洗5分钟备用

0:04:01.825,0:04:03.825
这一步的目的是去除异味

0:04:07.900,0:04:10.550
5分钟之后加入清水投洗干净即可

0:04:29.050,0:04:30.800
下一步开始准备辅料

0:04:31.250,0:04:33.525
准备生姜1小块拍散之后备用

0:04:34.925,0:04:36.775
准备折耳根200克备用

0:04:37.100,0:04:38.450
下一步开始制作

0:04:38.900,0:04:41.175
首先我们在锅中加入适量的清水

0:04:42.575,0:04:44.500
再加入处理好的猪肺下锅

0:04:54.150,0:04:56.050
中途加入几根小葱

0:04:59.200,0:05:01.275
大火烧开之后撇去浮沫

0:05:05.225,0:05:07.975
大火烧开之后转中小火煮90分钟

0:05:07.975,0:05:10.175
这一步的目的是把汤熬至浓白

0:05:10.850,0:05:14.025
煮至40分钟的时候捞出小葱再加入折耳根

0:05:24.525,0:05:26.450
90分钟之后开始调味

0:05:26.750,0:05:28.625
锅中加入适量的食用盐（约8克）

0:05:29.750,0:05:31.300
加入1勺胡椒粉

0:05:34.525,0:05:36.500
调好味之后即可出锅

0:05:48.120,0:05:51.000
一道营养丰富的猪肺汤就制作完成

0:05:58.560,0:06:19.180
下面开始技术总结
第一，必须选择有检疫证明宰杀的生猪肺，如有黑斑或
大面积淤血的猪肺需谨慎
第二，猪肺必须反复灌水清洗，洗至粉色或者白色最佳
第三，折耳根猪肺汤具有一定预防呼吸道疾病的功效，同学们可以
踊跃尝试
折耳根猪肺汤的技术总结完毕

**Comment by archerdominique** [comment]
bot, please upload
0:00:00.400,0:00:01.560
哈喽大家好 我是王刚
Hi guys! This is Wang Gang

0:00:01.560,0:00:03.020
本期视频我给大家分享
In today's video I'm gonna share with you

0:00:03.240,0:00:04.860
鱼腥草猪肺汤
Pig lung soup cooked with fish mint

0:00:05.480,0:00:07.900
首先我们准备新鲜的猪肺1副
First we have a pair of fresh pig lung

0:00:08.575,0:00:11.175
然后用水管对着气管灌入清水
And then pump in water through the trachea

0:00:13.600,0:00:16.550
灌满清水之后用牙签将其戳出小洞
When the lung is filled with water, use a toothpick to stab over the surface

0:00:17.775,0:00:20.225
这一步的目的是循环猪肺中的脏水
The purpose of this step is to discharge the dirty water from the lung

0:00:21.575,0:00:24.550
灌水满之后再倒出反复灌洗十遍以上
Pour out the water after the lung is full, and repeat this step over ten times

0:00:24.800,0:00:27.400
中途可以挤压猪肺让其快速循环
during which you can press the lung to speed up the water circulation

0:00:27.400,0:00:29.775
直到清洗为粉红色或者白肺为止
Until the lung appears pink or white

0:00:30.875,0:00:32.475
下一步开始初加工
Next, let's start the initial procedure

0:00:33.450,0:00:36.200
首先将猪肺气管上依附的淋巴取下
First, remove the lymph stick to the trachea

0:00:36.750,0:00:39.525
淋巴不适合食用所以必须去除干净
The lymph is not edible. It must be completely removed

0:00:52.500,0:00:54.600
下一步开始准备辅料
Next, let's get the minor ingredients ready

0:00:54.850,0:00:57.225
准备生姜2块拍散之后备用
Crush two lumps of ginger

0:00:59.500,0:01:01.525
准备小葱几根挽成结备
Tie up a few scallion for later use

0:01:03.400,0:01:04.725
下一步开始焯水
The next step is to parboil the lung

0:01:05.275,0:01:07.500
首先在锅中加入大半锅清水
Pour in more than half wok of water

0:01:12.725,0:01:14.675
然后加入准备好的姜葱
Drop in the ginger and scallion

0:01:16.300,0:01:18.475
将猪肺冷水下锅焯水10分钟
Put in the pig lung when the water is still cool, and parboil it for 10 minutes

0:01:18.475,0:01:20.875
这一步的目的是将猪肺定型
This is to fix the shape of the lung

0:01:34.750,0:01:36.325
中途加入适量的白酒（约15克）
Add some Bai Jiu (lit. Clear Chinese cooking wine)

0:01:39.375,0:01:41.375
大火烧开之后再撇去浮沫
Boil the water in high heat and then remove the scum

0:01:48.000,0:01:50.250
10分钟之后将猪肺捞出
After 10 minutes, take out the pig lung

0:01:59.750,0:02:01.825
然后将猪肺改刀切成小块
Cut the lung into small pieces

0:02:01.825,0:02:04.600
这一步的目的是让猪肺能够充分焯水
So that the lung can be parboiled thoroughly

0:02:19.250,0:02:21.675
将猪肺切好之后准备再次焯水
Prepare to parboil for the second time

0:02:22.075,0:02:24.107
然后锅中加入适量的清水
Pour in appropriate amount of water

0:02:24.550,0:02:27.125
将切好的猪肺下锅焯水10分钟
Parboil the lung pieces for another 10 minutes

0:02:37.300,0:02:39.850
中途继续加入适量的白酒去腥
Again, add some Bai Jiu to taste, in order to purge the smell

0:02:50.700,0:02:52.300
10分钟之后捞出
Take out the lung pieces after 10 minutes

0:03:06.150,0:03:08.575
捞出之后放入清水中清洗2遍
Wash them twice in clear water

0:03:08.575,0:03:11.450
这一步的目的是去除猪肺中间的脏东西
To remove the dirt within the lung

0:03:37.650,0:03:39.775
然后将猪肺切成小片备用
Furtherly cut the lung into small slices

0:03:55.025,0:03:57.400
切成小片之后加入食用盐1小把
After that, add a handful of salt

0:03:58.475,0:03:59.900
加入少许白醋
A little vinegar

0:03:59.900,0:04:01.825
然后抓洗5分钟备用
Grip and wash for 5 minutes

0:04:01.825,0:04:03.825
这一步的目的是去除异味
In order to remove the unpleasant smell and taste

0:04:07.900,0:04:10.550
5分钟之后加入清水投洗干净即可
After 5 minutes, rinse the lung slices in clear water

0:04:29.050,0:04:30.800
下一步开始准备辅料
Next, prepare the side ingredients

0:04:31.250,0:04:33.525
准备生姜1小块拍散之后备用
Crush a small lump of ginger

0:04:34.925,0:04:36.775
准备折耳根200克备用
200g of fish mint for later use

0:04:37.100,0:04:38.450
下一步开始制作
Now let's start cooking

0:04:38.900,0:04:41.175
首先我们在锅中加入适量的清水
First, pour in appropriate amount of water

0:04:42.575,0:04:44.500
再加入处理好的猪肺下锅
Drop in the lung slices

0:04:54.150,0:04:56.050
中途加入几根小葱
During cooking, put in some scallions

0:04:59.200,0:05:01.275
大火烧开之后撇去浮沫
Boil in high heat and remove the scum

0:05:05.225,0:05:07.975
大火烧开之后转中小火煮90分钟
After boiling, turn down the fire and cook for 90 minutes in medium or low heat

0:05:07.975,0:05:10.175
这一步的目的是把汤熬至浓白
So that the soup could take on a white colour

0:05:10.850,0:05:14.025
煮至40分钟的时候捞出小葱再加入折耳根
After about 40 minutes, take out the scallions and put in the fish mint

0:05:24.525,0:05:26.450
90分钟之后开始调味
When the time reaches 90 minutes, start seasoning

0:05:26.750,0:05:28.625
锅中加入适量的食用盐（约8克）
Some salt to taste (about 8g)

0:05:29.750,0:05:31.300
加入1勺胡椒粉
A spoonful of pepper powder

0:05:34.525,0:05:36.500
调好味之后即可出锅
It is ready to serve after seasoning

0:05:48.120,0:05:51.000
一道营养丰富的猪肺汤就制作完成
Now this nutritious pig lung soup is finished

0:05:58.560,0:06:19.180
下面开始技术总结
第一，必须选择有检疫证明宰杀的生猪肺，如有黑斑或
大面积淤血的猪肺需谨慎
第二，猪肺必须反复灌水清洗，洗至粉色或者白色最佳
第三，折耳根猪肺汤具有一定预防呼吸道疾病的功效，同学们可以
踊跃尝试
折耳根猪肺汤的技术总结完毕
Here are some tips:
Tip 1: The pig lung should have the quarantine certificate. Lungs with black spots or lots of extravasated blood should be treated cautiously
Tip 2: The pig lung needs to be wash repeatedly until the colour turns pink or white
Tip 3: The pig lung soup with fish mint has some effect of preventing respiratory diseases. You might wanna have a try!
That's all for the tips

**Comment by immoonancient** [comment]
已发布
