### ISSUE TITLE
[华农兄弟] 挖甘蔗 - https://youtu.be/Iesb1LgvLTY

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#712]
https://youtu.be/Iesb1LgvLTY
<p>&#35270;&#39057;&#21457;&#24067;&#20110; February 23, 2020 at 12:49PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/Iesb1LgvLTY

#华农兄弟：上次种了几根甘蔗，挖起来看一下有没有发芽
#Huanong Brothers: We planted some sugar canes last time. Let's dig them up and see if there are any sprouts.

0:00:00.000,0:00:02.780
# 大家好  前幾天我在這裡種甘蔗哦
Hi everyone. We've planted some sugar canes here a couple of days ago.

0:00:02.780,0:00:03.820
# 看一下有沒有發芽
Let's see if they have started sprouting.

0:00:04.820,0:00:06.160
# 上次因為種的比較急  (註︰以我所知這裡的急不是急著種完，而是事件沒太多準備)
We didn't film it last time,

0:00:06.460,0:00:07.380
# 沒拍視頻
as we didn't have the time.

0:00:07.920,0:00:10.160
# 這次我特地過來  把它挖起來看一下
That's why I'm coming again, to dig it up and have a look.

0:00:11.300,0:00:12.700
# 不知道會不會發芽
Let's see if there are any sprouts.

0:00:17.440,0:00:18.020
# 這個
This one...

0:00:19.080,0:00:19.840
# 出來啦
It's coming out.

0:00:23.800,0:00:24.340
# 你看
Look!

0:00:24.640,0:00:26.380
# 快發芽啦  看見沒有  這些都是
It'll be sprouting soon. See? There are all,

0:00:26.900,0:00:28.960
# 青的  它這個長  長那個莖的
all green. The, the stems will be coming up here.

0:00:29.680,0:00:31.180
# 這裡可以就看得出來
I can tell by simply looking at it.

0:00:34.120,0:00:34.880
# 你看 這邊
Look! This side,

0:00:35.660,0:00:36.880
# 這邊  這個看一下
this side. Let me have a look.

0:00:38.220,0:00:40.520
# 你看  這裡  這裡有青色的哦  看到沒有
Look! Here, here is a green spot. See?

0:00:40.840,0:00:42.300
# 這就準備發芽啦
That means it's ready to sprout.

0:00:42.740,0:00:43.620
# 你看 這個芽
Look! The sprout,

0:00:43.920,0:00:45.240
# 都露出了一點點哦
a bit of it is already coming out.

0:00:46.200,0:00:47.280
# 把它包回去
I'll wrap it up again.

0:00:48.540,0:00:50.180
# 把它種下去又把它挖起來
I shouldn't dig it up right after planting it.

0:00:51.020,0:00:52.520
# 哎呀 不好意思啊
Aya! My apologies.

0:00:54.640,0:00:56.380
# 這個芽  這個芽馬上出來啦
This sprout, this sprout will be coming out very soon.

0:00:56.920,0:00:57.580
# 一點點
A tiny little bit

0:01:02.140,0:01:02.960
# 啊  這裡
Ah! Here

0:01:03.580,0:01:04.680
# 這個芽那麼大啦
This sprout is already that big.

0:01:04.760,0:01:05.940
# 馬上就會長出來啦
It will be coming out very soon.

0:01:06.100,0:01:07.700
# 種下去才五六天左右
They were planted just five or six days ago.

0:01:08.460,0:01:09.380
# 也不是很久
It's not a long time.

0:01:09.380,0:01:10.380
# 把它埋回去
Let me put it back.

0:01:19.420,0:01:22.000
# 到時候 明年的春天就有甘蔗吃啦
Then, we can have sugar canes in the spring next year.

0:01:22.620,0:01:24.060
# 就不用去拿兄弟家的啦
We don't need to take from our buddy any more.

0:01:24.680,0:01:26.100
# 上次拿兄弟家的
Last time, when I took my buddy's sugar canes,

0:01:27.200,0:01:28.640
# 說好了是拿一根一根
I promised to take one, just one.

0:01:29.540,0:01:31.140
# 我拿了十幾二十根回來
But I came back with a dozen.

0:01:32.240,0:01:33.720
# 今年他甘蔗都每[SIC]種
He didn't plant any sugar canes this year.

0:01:34.580,0:01:36.280
# 田都荒在那裡  他不種啦
The field is just over there, abandoned.

0:01:36.380,0:01:37.060
# 不知道幹嘛
Who knows what happened to him.

0:01:37.920,0:01:39.580
# 看他甘蔗賣得也挺好的啊
The sales of his sugar canes are rather good, in fact.

0:01:41.440,0:01:44.340
# 好啦  反正這應該也長得出二三十棵
Anyway, here I think I'll have a dozen or two,

0:01:44.480,0:01:45.200
# 甘蔗出來
of sugar canes.

0:01:45.860,0:01:46.860
# 夠我吃的啦
It's well enough for me.

0:01:47.780,0:01:50.060
# 這裡  這裡搞一個  一整條都有
Here, I put one here. And it grows all along this row.

0:01:50.220,0:01:51.140
# 那邊還有一行
And there's one more row.

0:01:51.620,0:01:52.120
# 都是  
The same.

0:01:52.900,0:01:53.400
# 你看
Look!

0:01:53.740,0:01:54.740
# 我們種的大蒜
This is our garlic.

0:01:55.300,0:01:57.560
# 你看  我在這土里面還種了大蒜哦
Look! I've also planted some garlic here.

0:01:58.560,0:01:59.300
# 你看  這個大蒜
Look at this garlic.

0:01:59.860,0:02:00.620
# 很靚的吧
It's beautiful, isn't it?

0:02:01.260,0:02:04.900
# 前  前五六天  跟甘蔗一起種下去的  你看
I planted them with the sugar canes five, five or six days ago.

0:02:05.100,0:02:05.860
# 現在那麼多啦
There are so many now.

0:02:07.200,0:02:09.620
# 這個大蒜很快的  它長了那麼高 我就把它拔啦
The garlic grows very fast. I'll pick them up when they're about that tall.

0:02:10.080,0:02:11.080
# 把它拿去賣呀
Then we can sell them.

0:02:12.380,0:02:13.940
# 你看  這一片  那邊還有
Look! The whole area here, and there too.

0:02:14.540,0:02:15.860
# 這一片都是我家的
This whole area here is my,

0:02:15.920,0:02:16.460
# 那個
I mean,

0:02:16.900,0:02:17.440
# 菜園
veggie garden.

0:02:18.160,0:02:19.240
# 那邊有青菜呀
There are some veggies,

0:02:19.680,0:02:20.380
# 蘿蔔呀
radish.

0:02:20.560,0:02:22.340
# 這邊我全部用來種了這個大蒜
But I reserve here for the garlic.

0:02:22.660,0:02:25.620
# 你看  這個蒜苗幾乎都是百分之一百成活的哦
The survival rate of the sprouts here is almost always a hundred percent.

0:02:26.300,0:02:26.800
# 沒有
There are no,

0:02:27.440,0:02:29.380
# 沒有 沒有假的  全是真的  (註︰怎麼假的大蒜，想說甚麼？)
no, no fake ones. All are real and genuine.

0:02:30.380,0:02:31.340
# 長得好快呀
They grow really fast.

0:02:32.200,0:02:32.720
# 你看
Look!

0:02:34.880,0:02:37.460
# 這個草木灰  我把草木灰放下去肥下它們
This is wood ash. I put some wood ash here as fertilizer.

0:02:37.840,0:02:38.760
# 它們長得好快
And they grow really fast.

0:02:38.920,0:02:39.440
# 你看
Look!

0:02:40.940,0:02:41.980
# 烏黑發亮哦
It's shining black.

0:02:44.420,0:02:47.240
# 再過一個月的話  應該就可以拔蒜苗賣
I think they can be picked for sale after a month.

0:02:48.620,0:02:49.820
# 來這菜園里面
We're now in the veggie garden.

0:02:50.100,0:02:52.020
# 搞點這個  這個菜花呀
Let me pick some, some veggies,

0:02:52.600,0:02:54.200
# 菜花給攝影小哥帶回去
veggies for Mr. Cameraman.

0:02:55.640,0:02:57.540
# 這個是  綠色無公害的哦
These are, organic vegetables,

0:02:59.120,0:03:01.100
# 沒有施  沒有施過化肥的
without, without any chemical fertilizers.

0:03:20.700,0:03:22.040
# 它這菜就很[好]種的
Growing these vegetables doesn't need too much effort.

0:03:22.520,0:03:23.700
# 種下去就不用管
Plant it, leave it growing, that's it.

0:03:24.740,0:03:25.340
# 每天  每天都有很拗
Then we can,

0:03:26.040,0:03:27.540
# 每天  每天都有得拗
come here, come here and pick some everyday.

0:03:28.400,0:03:29.460
# 我都拗了好多啦
I've already picked a lot.

0:03:29.960,0:03:32.740
# 很多鄰居都  他們沒種菜的都到我這邊來拗
Many neighbours also come here and pick some if they don't grow any veggies at home.

0:03:33.560,0:03:34.540
# 我叫他隨便拗
I ask them to take whatever they like.

0:03:35.580,0:03:36.640
# 不用給我客氣
It's my pleasure.

0:03:49.800,0:03:50.400
# 夠啦
It's enough.

0:03:50.880,0:03:52.340
# 這裡夠吃一兩餐啦
It's enough for a meal or two.

0:03:54.480,0:03:56.080
# 到時候吃完 吃完再拔
We can pick again, when it's finished.

0:03:56.160,0:03:56.660
# 再進來
We can come again,

0:03:57.180,0:03:58.000
# 再進來拗
and pick more.

0:03:59.800,0:04:01.740
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.

0:04:02.620,0:04:03.720
# 我要回家煮飯啦
I need to go back home and cook.

**Comment by vincenthychow** [comment]
已發佈
