### ISSUE TITLE
[华农兄弟] 华农兄弟看一下兄弟家的牛再看一下他家的鱼塘和香菇 - https://youtu.be/qMWpPtGZDSI

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#715]
https://youtu.be/qMWpPtGZDSI
<p>&#35270;&#39057;&#21457;&#24067;&#20110; February 23, 2020 at 09:46PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/qMWpPtGZDSI

#华农兄弟：看一下兄弟家的牛，再看一下他家的鱼塘和香菇
#Huanong Brothers: Let's take a look at my buddy's cattle, his fish and his shiitake mushrooms.

0:00:00.000,0:00:02.680
# 大家好  今天找兄弟搞一條牛來
Hi everyone! Today I come to my buddy to get a cow.

0:00:02.680,0:00:03.920
# 你看  這麼多都是他的
Look! All these belong to him.

0:00:04.280,0:00:05.960
# 我去看一下哪條  漂亮一點
I'm gonna see which one, is more pretty.

0:00:06.760,0:00:07.780
# 把它牽回去
I'll take it back.

0:00:09.500,0:00:10.320
# 先來看一下
I take a look first.

0:00:12.360,0:00:12.860
# 你看
Look!

0:00:13.680,0:00:15.080
# 上次我賣了一條牛給他
I sold him a cow last time.

0:00:16.560,0:00:17.540
# 是哪條啦
Which one is it?

0:00:18.760,0:00:19.780
# 有點黃的
It's a bit brown.

0:00:21.280,0:00:22.060
# 忘記啦
I can't remember.

0:00:25.680,0:00:26.840
# 有點像那一條
It seems to be that one.

0:00:27.000,0:00:28.420
# 不像啊  我的很漂亮的
No, it isn't. Mine is very pretty.

0:00:28.960,0:00:30.300
# 現在都好像長大啦
I think it has already grown up,

0:00:31.000,0:00:31.720
# 不一樣啦
and looks very different now.

0:00:34.040,0:00:35.520
# 你看  這一條小牛黑黑的
Look! This calf is rather black.

0:00:35.980,0:00:36.920
# 很漂亮的哦
It's so pretty.

0:00:37.660,0:00:38.400
# 太小啦
It's too small.

0:00:49.800,0:00:51.540
# 怎麼全是公牛  你看
Why are they all male? Look!

0:00:51.720,0:00:53.720
# 一條公牛 兩條三條四條
One male, two, three, four

0:00:54.720,0:00:56.200
# 全部小牛都是公的
All calves are male.

0:00:57.420,0:00:58.500
# 沒有一條母的哦
There's not even one female.

0:00:59.260,0:00:59.980
# 這麼奇怪
Strange!

0:01:02.140,0:01:03.260
# 全是小公牛
All calves are male.

0:01:05.820,0:01:06.460
# 後面還有
There are more behind us.

0:01:06.740,0:01:07.560
# 後面還有牛哦
There are some more cows behind us.

0:01:08.160,0:01:09.020
# 沒有來哦
They didn't come here.

0:01:16.700,0:01:17.220
# 你看
Look!

0:01:17.520,0:01:18.420
# 這些都是
These are all,

0:01:18.580,0:01:19.960
# 大一點的都是母牛
the larger ones are all female.

0:01:20.600,0:01:21.660
# 小的全是公牛
And the small ones are all male.

0:01:24.040,0:01:25.300
# 這些公牛都很靚
These bulls are really beautiful.

0:01:35.460,0:01:37.500
# 現在還小  兄弟肯定不肯
They are still small. My buddy won't agree,

0:01:37.800,0:01:39.780
# 不肯給我的  他要長大一點才給我
won't agree to give me one, not until they become a bit larger.

0:01:41.020,0:01:41.940
# 到時候看一看
I'll see by that time.

0:01:50.400,0:01:52.940
# 你看  我們本地小黃牛  就是這樣子的
Look! These are exactly our local cattle here.

0:01:53.800,0:01:55.080
# 全是吃青草的
They feed only on grass,

0:01:56.620,0:01:57.280
# 不肥
and won't get fat.

0:01:59.060,0:02:00.320
# 全是瘦肉來的
They have only lean meat.

0:02:04.280,0:02:05.680
# 我去兄弟家喝一下茶
I'll have a cup of tea at my buddy's place,

0:02:06.560,0:02:08.020
# 順便吃個晚飯再回去
and also a dinner before getting back home.

0:02:09.240,0:02:11.380
# 大家好  今天看一下兄弟家的這個魚塘
Hi everyone! Today we'll take a look at my buddy's fish pond.

0:02:11.800,0:02:13.840
# 看下有沒有魚  我順便搞一條來吃
Let's see if there are any fish. I can also take one as well.

0:02:14.920,0:02:16.700
# 哇  現在看得到哦  好多魚
Wa! I can see the fish now, a lot of them!

0:02:32.860,0:02:34.680
# 沒跟兄弟打招呼  兄弟都不在
I didn't call my buddy before coming, and he's not around right now.

0:02:35.300,0:02:36.860
# 想抓條魚吃都抓不到
I wanted to catch a fish, but now I can't.

0:02:36.880,0:02:38.020
# 看一下還有甚麼東西
Let's see if there are any other things.

0:02:40.740,0:02:42.160
# 你看  這個兄弟家的香菇
Look! These are my buddy's shiitake mushrooms.

0:02:43.920,0:02:45.780
# 每 我們這邊每家每戶都種啦
Each, every family here grows,

0:02:46.000,0:02:47.260
# 種了一點這樣的香菇啊
grows a bit this kind of mushrooms.

0:02:48.240,0:02:50.720
# 但是一年的產量  也不是很搞
But the annual yield, is not really that high.

0:02:51.280,0:02:52.120
# 一家
A family,

0:02:52.640,0:02:53.240
# 一家能
a family can,

0:02:53.680,0:02:55.420
# 摘個五六十斤  乾的香菇
can have around 30 kilograms of dried mushrooms.

0:02:55.500,0:02:56.180
# 我就沒有
But I have none.

0:02:57.240,0:02:58.780
# 所以我們經常去找他們收
That's why we always buy from them.

0:03:01.680,0:03:02.960
# 這些被他們摘掉啦
These have all been picked.

0:03:03.360,0:03:04.860
# 被兄弟摘掉啦  好多哇
My buddy picked them all. A lot!

0:03:06.220,0:03:07.540
# 一棵樹都長那麼多
So many can grow from one single tree.

0:03:11.880,0:03:12.820
# 你看  這個香菇
Have a look at this mushroom.

0:03:13.380,0:03:15.880
# 它曬了 曬了一下 你看  就裂開啦
It has been under the sun, under the sun for a while. Look! It's cracked.

0:03:16.380,0:03:17.700
# 就個就變成了花菇
And now it has become a "hua  gu" (shiitake mushroom with pattern).

0:03:21.780,0:03:23.700
# 你看  有裂紋的就叫花菇
Look! The cracked ones are called "hua gu",

0:03:23.860,0:03:25.180
# 沒裂紋的就叫香菇
while the others are called "xiang gu" (shiitake mushroom with aroma).

0:03:30.900,0:03:32.760
# 兄弟不在哦  不好意思摘
I don't feel good to pick them now as my buddy is not around.

0:03:33.260,0:03:36.060
# 因為他 我拍摘了他那個  那個  那個小狗哇
Cuz he ah...if I pick them, I'm afraid his, I mean, you know, his doggy,

0:03:36.240,0:03:37.060
# 不放過我
won't let me go.

0:03:37.940,0:03:38.900
# 還是算了吧
Well, forget it!

0:03:40.120,0:03:41.600
# 今天的視頻就到這裡啦
The video ends here.

0:03:41.700,0:03:42.280
# 回去啦
Let's go back.

**Comment by vincenthychow** [comment]
已發佈
