### ISSUE TITLE
【国宴大师•老北京炸酱面】 https://www.youtube.com/watch?v=tb0h3GJ4ciY&t

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#720]
https://www.youtube.com/watch?v=tb0h3GJ4ciY

标题：
【国宴大师•老北京炸酱面】老北京小碗儿干炸，吃得出的颗颗分明的肉粒，就是这个味儿，真爽！|老饭骨
简介：
小友们好，今天三叔带给大家一道老北京炸酱面！
真正的炸酱面还是在北京，其实并没有标准，但每家都好吃，今天呢，就是三叔平时做的方法，希望大家能够喜欢。
今天的做炸酱面的小诀窍以字幕的形式被嵌入视频中喽，
爱吃炸酱面的朋友们仔细学习哦！
字幕：
1
00:00:00,000 --> 00:00:02,240
真正炸酱面还是在北京

2
00:00:02,240 --> 00:00:03,400
它没有标准

3
00:00:03,400 --> 00:00:04,720
是所有人都会做

4
00:00:04,720 --> 00:00:06,440
就每个家每个家庭

5
00:00:06,440 --> 00:00:08,560
都做的手法不一样

6
00:00:08,560 --> 00:00:11,360
但是你去谁家吃都好吃

7
00:00:11,360 --> 00:00:14,560
这是什么  摄像机

8
00:00:14,560 --> 00:00:16,400
这就是炸酱面的码

9
00:00:16,400 --> 00:00:18,640
八个码什么码都可以

10
00:00:18,640 --> 00:00:19,960
不是这白菜太脆了

11
00:00:19,960 --> 00:00:21,680
跟咱们北京的白菜不太一样

12
00:00:21,680 --> 00:00:22,960
它的水比较大

13
00:00:22,960 --> 00:00:24,720
北京黄酱多香啊

14
00:00:24,720 --> 00:00:27,600
澥成这样你看

15
00:00:27,600 --> 00:00:30,920
跟我围裙一样也是这样戴的

16
00:00:32,120 --> 00:00:35,440
老北京的炸酱面油要大

17
00:00:36,480 --> 00:00:38,880
愿意吃块儿大的

18
00:00:38,880 --> 00:00:39,800

19
00:00:42,360 --> 00:00:44,800
八角就是大料

20
00:00:44,800 --> 00:00:47,120
你得把那油脱脂脱出来

21
00:00:47,120 --> 00:00:49,680
把那肉稍微要有焦感

22
00:00:49,680 --> 00:00:52,000
它才会有焦香味  对

23
00:00:52,000 --> 00:00:53,160
到这份上就可以了

24
00:00:54,360 --> 00:00:56,400
下酱不能全下去

25
00:00:56,400 --> 00:00:59,600
一边炒一边下

26
00:00:59,600 --> 00:01:00,960
就都能把酱炸透了

27
00:01:00,960 --> 00:01:04,040
你如果一倒进去就咕嘟了

28
00:01:04,040 --> 00:01:05,840

29
00:01:05,840 --> 00:01:08,720
做饭手法很重要  程序

30
00:01:08,720 --> 00:01:10,480
很多人为什么味道会差一点

31
00:01:10,480 --> 00:01:13,920
程序弄错  香味提不出来

32
00:01:13,920 --> 00:01:15,920
分三次下

33
00:01:15,920 --> 00:01:19,120
最后剩一点  这个就不能加凉水

34
00:01:19,120 --> 00:01:20,640
因为它会降温

35
00:01:21,600 --> 00:01:24,600
在这个过程中就可以提一点糖

36
00:01:24,600 --> 00:01:25,680
充当味精用

37
00:01:25,680 --> 00:01:27,080
而且糖有个好处

38
00:01:27,080 --> 00:01:29,280
可以让色泽更漂亮

39
00:01:29,280 --> 00:01:32,960
就说做什么东西一定要见着物

40
00:01:32,960 --> 00:01:34,520
就见着它的主材

41
00:01:34,520 --> 00:01:38,040
一搁肉沫就不好吃了这东西很怪

42
00:01:39,480 --> 00:01:41,320
色香味俱全

43
00:01:41,320 --> 00:01:44,000

44
00:01:44,000 --> 00:01:45,040
炸酱不要着急

45
00:01:45,040 --> 00:01:46,960
它是一态度问题

46
00:01:46,960 --> 00:01:48,600
你态度好炸出酱就好

47
00:01:48,600 --> 00:01:50,720
你要态度不好着急

48
00:01:50,720 --> 00:01:53,520
肉也腥酱也不熟

49
00:01:53,520 --> 00:01:55,840
前期炒的时候你记住一定用这火

50
00:01:55,840 --> 00:01:58,480

51
00:01:58,480 --> 00:02:02,160
慢慢澥慢慢收

52
00:02:02,160 --> 00:02:03,600
把肉的油憋出来出来

53
00:02:03,600 --> 00:02:05,760
然后逼进酱里

54
00:02:05,760 --> 00:02:07,520

55
00:02:11,080 --> 00:02:13,440
到这时候可以了关小火

56
00:02:13,440 --> 00:02:17,120
慢慢慢慢的㸆

57
00:02:17,120 --> 00:02:19,640

58
00:02:19,640 --> 00:02:22,520
这才叫老北京的小碗干炸 知道吧

59
00:02:22,520 --> 00:02:23,880
这酱全裹在肉上

60
00:02:25,440 --> 00:02:27,240
这肉块也比我们家大

61
00:02:27,240 --> 00:02:29,200
对你们家不舍得

62
00:02:29,200 --> 00:02:32,040
你爸说了过日子讲究一点

63
00:02:32,040 --> 00:02:34,880
大块吃着多过瘾

64
00:02:34,880 --> 00:02:39,360
你看老北京有时候搁点香油

65
00:02:39,360 --> 00:02:41,600
一定要有油植物油

66
00:02:41,600 --> 00:02:43,800
我们过去老北京有句话叫什么

67
00:02:43,800 --> 00:02:45,440
想长寿吃肥肉

68
00:02:45,440 --> 00:02:48,880
不是肥肉不好  一定要吃肥肉

69
00:02:50,680 --> 00:02:52,720
出锅了  好香哦

70
00:02:52,720 --> 00:02:55,160
一定是肉是肉(油是油)酱是酱

71
00:02:55,160 --> 00:02:58,720
酱一定裹在肉上  酱得裹肉上

72
00:02:58,720 --> 00:03:00,440
油要凸显出来

73
00:03:00,440 --> 00:03:03,800
不要说酱粘粘乎乎一堆

74
00:03:03,800 --> 00:03:05,560
这就是小碗干炸

75
00:03:05,560 --> 00:03:09,840
刚才我们讲的这面开锅点三次水

76
00:03:09,840 --> 00:03:12,680
台湾这个面还真好

77
00:03:12,680 --> 00:03:15,160
你看又白又筋道

78
00:03:15,160 --> 00:03:17,760
咱们吃面的时候先这样

79
00:03:17,760 --> 00:03:21,080

80
00:03:21,080 --> 00:03:23,880
它给一勺还要擓一勺油 润它

81
00:03:23,880 --> 00:03:25,240
黄瓜丝

82
00:03:26,120 --> 00:03:28,280
芹菜末

83
00:03:29,040 --> 00:03:30,840
豆角白菜

84
00:03:30,840 --> 00:03:33,400
这个码比面多

85
00:03:34,480 --> 00:03:36,600
吃的就是码和酱

86
00:03:36,600 --> 00:03:41,680
萝卜丝  咱北京是心儿里美

87
00:03:41,680 --> 00:03:42,400

88
00:03:42,400 --> 00:03:45,000
这个您就自己拌  拌透了

89
00:03:45,000 --> 00:03:46,880

90
00:03:46,880 --> 00:03:48,160
不要怕油

91
00:03:48,160 --> 00:03:51,320
咱讲的是什么  猪油是这样

92
00:03:51,320 --> 00:03:53,840
我父亲活了八十七八

93
00:03:53,840 --> 00:03:57,520
他说了想长寿吃肥肉

94
00:03:57,520 --> 00:04:00,520
然后但是必须要跟上茶

95
00:04:00,520 --> 00:04:03,040
吃肥肉没事茶跟上

96
00:04:05,480 --> 00:04:08,280
这个大蒜真棒来一口

97
00:04:08,280 --> 00:04:10,360
一口面一口大蒜

98
00:04:10,360 --> 00:04:12,040
对味的

99
00:04:12,040 --> 00:04:14,720
这个面条的酱炸到什么叫最好

100
00:04:14,720 --> 00:04:18,280
拌完以后这面条是枣红色

101
00:04:18,280 --> 00:04:21,280
酱红色特别感觉有食欲的

102
00:04:21,280 --> 00:04:23,280

103
00:04:23,280 --> 00:04:25,360
给个表示怎么样

104
00:04:25,360 --> 00:04:28,000
武大师亲手做的

105
00:04:28,000 --> 00:04:29,960
比我的亲家做得还好

106
00:04:29,960 --> 00:04:30,560

107
00:04:32,200 --> 00:04:34,520
行了充电去吧

**Comment by 3yearsyoung** [comment]
bot, please upload
【国宴大师•老北京炸酱面】老北京小碗儿干炸，吃得出的颗颗分明的肉粒，就是这个味儿，真爽！|老饭骨
「The State Banquet Chef's Pork Noodles with Soybean Paste」 Deep-fried sauce in small bowls - Old Beijing Style. Mouthful of individual pork pieces - that’s what I’m talking about! Mind-blowing!

小友们好，今天三叔带给大家一道老北京炸酱面！
Hello everyone! Today, Uncle #3 will present an authentic Old Beijing Pork Noodles with Soybean Paste!

真正的炸酱面还是在北京，其实并没有标准，但每家都好吃，今天呢，就是三叔平时做的方法，希望大家能够喜欢。
The real pork noodles are only available in Beijing. There is no standard, but every Beijinger can make it right. Today Uncle #3 will bring his version which he makes every time, and we hope you like it.
今天的做炸酱面的小诀窍以字幕的形式被嵌入视频中喽，爱吃炸酱面的朋友们仔细学习哦！
Tips and tricks of making the noodles have been embedded in captions. Watch and learn carefully if you love to eat pork noodles!
大家好，我们是老饭骨！三个能吃、会做、擅长侃大山的北京大爷。
Hello, everyone, we are LaoFanGu, three old men from Beijing that can eat, cook and chill.
我们的菜好看好吃又硬核，过去我们都是做国宴打美食外交的，如今退休在家和老朋友一起想把我们年轻时研究操练的菜品分享给大家，让大家在家里学着做真正儿的大菜，尝尝国宴菜品和中外领导人吃过的美食。
Our dishes look good and taste even better. All three of us used to work for Chinese National Banquet catered to government guests. Now we are all retired, and we want to share the dishes we developed when we were young to all of you, so everyone can try at home what country leaders are served when they visit China.
我们分别是大爷郑秀生 国宴大师北京饭店行政总厨，亲自主理建国五十周年，开国第一宴工作；
Grandpa #1 (Xiusheng Zheng): Executive Chef for Beijing Hotel, hosted China's 50th Anniversary Banquet.
二伯孙立新；多次担任多位国家领导人宴请中外贵宾的菜单主设计者，
Uncle #2 (Lixin Sun): Designed menus for Chinese National Banquet for foreign leaders when they visit China multiple times.
三叔武剑利，国际高级烹饪技师，中华金厨，是著名的“熏肉之乡”柴沟铺的第三代传人，研发了“武式熏酱”大招。
Uncle #3 (Jianli Wu): Internationally renowned ‘Golden Chef of China’. 3rd Generation successor of Chaigoupu smoked meat. Developed 'Wu type smoked sauce'.
三位老饭骨（吃货）合体教你做地道美味的家常菜，最正宗的北方菜，还有几乎失传的老菜，家传秘方通通倾囊相授！
All three of us (foodies) will bring together to teach you the most delicious everyday plates, most authentic Northern China Cuisine, most forgotten dishes from old generations and most secret recipes from our own families!
我们会每周一三五更新视频，教你做菜，和你唠嗑，与你分享家的味道。
We will upload new videos every Monday, Wednesday and Friday, bringing new dishes, chilling out, and sharing the taste of family with you.
喜欢我们的朋友欢迎评论，点赞和订阅，打开小铃铛不会错过我们的最新动态哦！
You are welcome to comment, like and subscribe to our channel. Turn on the notification to receive the latest news of the channel!
点击下面的链接可以直接订阅哦！
Click the link below to subsribe:
https://bit.ly/30QmA1X

*Facebook*
https://www.facebook.com/laofangu/

1
00:00:00,000 --> 00:00:02,240
真正炸酱面还是在北京
The real pork noodles with soybean paste are only available in Beijing

2
00:00:02,240 --> 00:00:03,400
它没有标准
There is no standard

3
00:00:03,400 --> 00:00:04,720
是所有人都会做
Every Beijinger can make it

4
00:00:04,720 --> 00:00:06,440
就每个家每个家庭
Every family

5
00:00:06,440 --> 00:00:08,560
都做的手法不一样
They all have their own versions

6
00:00:08,560 --> 00:00:11,360
但是你去谁家吃都好吃
But every single of them is tasty

7
00:00:11,360 --> 00:00:14,560
这是什么 摄像机
What’s this? It’s a camera

8
00:00:14,560 --> 00:00:16,400
这就是炸酱面的码
These are the toppings for the noodles

9
00:00:16,400 --> 00:00:18,640
八个码什么码都可以
Eight kinds of toppings or whatever you like

10
00:00:18,640 --> 00:00:19,960
不是这白菜太脆了
These Chinese cabbages are so crunchy

11
00:00:19,960 --> 00:00:21,680
跟咱们北京的白菜不太一样
They are different from what we have in Beijing

12
00:00:21,680 --> 00:00:22,960
它的水比较大
They are quite watery

13
00:00:22,960 --> 00:00:24,720
北京黄酱多香啊
This soybean paste is so aromatic

14
00:00:24,720 --> 00:00:27,600
澥成这样你看
Dilute with water until it looks like this

15
00:00:27,600 --> 00:00:30,920
跟我围裙一样也是这样戴的
I wear my apron this way as well

16
00:00:32,120 --> 00:00:35,440
老北京的炸酱面油要大
You need a large amount of oil

17
00:00:36,480 --> 00:00:38,880
愿意吃块儿大的
Everyone loves big pieces

18
00:00:38,880 --> 00:00:39,800

19
00:00:42,360 --> 00:00:44,800
八角就是大料
Star anise is an essential ingredient

20
00:00:44,800 --> 00:00:47,120
你得把那油脱脂脱出来
You must render the fat out

21
00:00:47,120 --> 00:00:49,680
把那肉稍微要有焦感
Pork pieces should be slightly brown and crispy

22
00:00:49,680 --> 00:00:52,000
它才会有焦香味 对
So they can develop that fragrance from caramelisation

23
00:00:52,000 --> 00:00:53,160
到这份上就可以了
It’s right on spot now

24
00:00:54,360 --> 00:00:56,400
下酱不能全下去
You can’t pour all paste in at once

25
00:00:56,400 --> 00:00:59,600
一边炒一边下
You must add it in batches

26
00:00:59,600 --> 00:01:00,960
就都能把酱炸透了
So it can be thoroughly fried

27
00:01:00,960 --> 00:01:04,040
你如果一倒进去就咕嘟了
If you pour all of the paste into the pan, it will become boiled

28
00:01:04,040 --> 00:01:05,840

29
00:01:05,840 --> 00:01:08,720
做饭手法很重要 程序
The steps in cooking are important (or procedures)

30
00:01:08,720 --> 00:01:10,480
很多人为什么味道会差一点
A lot of dishes are not as tasty

31
00:01:10,480 --> 00:01:13,920
程序弄错 香味提不出来
Because they messed up the procedures, so the fragrance was not lifted

32
00:01:13,920 --> 00:01:15,920
分三次下
Add it in three batches

33
00:01:15,920 --> 00:01:19,120
最后剩一点 这个就不能加凉水
For the last bit, you can’t mix it with cold water

34
00:01:19,120 --> 00:01:20,640
因为它会降温
Because it will cause the temperature to drop

35
00:01:21,600 --> 00:01:24,600
在这个过程中就可以提一点糖
Add in a little bit of sugar in the meantime

36
00:01:24,600 --> 00:01:25,680
充当味精用
It acts like MSG

37
00:01:25,680 --> 00:01:27,080
而且糖有个好处
Also, sugar has an extra benefit

38
00:01:27,080 --> 00:01:29,280
可以让色泽更漂亮
That it can make the final dish brighter and more colourful

39
00:01:29,280 --> 00:01:32,960
就说做什么东西一定要见着物
I always say that you must see the ingredients whenever you cook

40
00:01:32,960 --> 00:01:34,520
就见着它的主材
You must see the main ingredients of a dish

41
00:01:34,520 --> 00:01:38,040
一搁肉沫就不好吃了这东西很怪
It would be tasteless and weird if you put pork mince in this dish

42
00:01:39,480 --> 00:01:41,320
色香味俱全
Now it’s colourful, fragrant and tasty

43
00:01:41,320 --> 00:01:44,000

44
00:01:44,000 --> 00:01:45,040
炸酱不要着急
You must be patient when you fry the sauce

45
00:01:45,040 --> 00:01:46,960
它是一态度问题
It’s attitude

46
00:01:46,960 --> 00:01:48,600
你态度好炸出酱就好
If you are patient, the sauce will be perfect in return

47
00:01:48,600 --> 00:01:50,720
你要态度不好着急
On the contrary, if you have a bad temper

48
00:01:50,720 --> 00:01:53,520
肉也腥酱也不熟
The meat will be smelly, and the sauce will not be properly cooked

49
00:01:53,520 --> 00:01:55,840
前期炒的时候你记住一定用这火
Remember to use such heat when you first fry them

50
00:01:55,840 --> 00:01:58,480

51
00:01:58,480 --> 00:02:02,160
慢慢澥慢慢收
Slowly dilute the sauce and then slowly thicken it

52
00:02:02,160 --> 00:02:03,600
把肉的油憋出来出来
Render the fat out of the meat

53
00:02:03,600 --> 00:02:05,760
然后逼进酱里
And then push it back to the sauce

54
00:02:05,760 --> 00:02:07,520

55
00:02:11,080 --> 00:02:13,440
到这时候可以了关小火
Now turn down to low heat

56
00:02:13,440 --> 00:02:17,120
慢慢慢慢的㸆
Braise the sauce really slowly

57
00:02:17,120 --> 00:02:19,640

58
00:02:19,640 --> 00:02:22,520
这才叫老北京的小碗干炸 知道吧
This is what I call ‘deep fried sauce in small bowls’, you know

59
00:02:22,520 --> 00:02:23,880
这酱全裹在肉上
All meat pieces are covered with the sauce

60
00:02:25,440 --> 00:02:27,240
这肉块也比我们家大
These meat pieces are bigger than what we usually use

61
00:02:27,240 --> 00:02:29,200
对你们家不舍得
Yes, because your family are not willing to spend too much on those things

62
00:02:29,200 --> 00:02:32,040
你爸说了过日子讲究一点
Your father always says that you need to be particular about the spending

63
00:02:32,040 --> 00:02:34,880
大块吃着多过瘾
It feels so satisfied to eat these big pieces

64
00:02:34,880 --> 00:02:39,360
你看老北京有时候搁点香油
Old Beijingers will sometimes add in some sesame oil here

65
00:02:39,360 --> 00:02:41,600
一定要有油植物油
There must be oil, vegetable oil

66
00:02:41,600 --> 00:02:43,800
我们过去老北京有句话叫什么
We Beijingers had a saying called

67
00:02:43,800 --> 00:02:45,440
想长寿吃肥肉
Eat fats if you want to live longer

68
00:02:45,440 --> 00:02:48,880
不是肥肉不好 一定要吃肥肉
Fatty meats are not evil, and you must eat them

69
00:02:50,680 --> 00:02:52,720
出锅了 好香哦
Take them out of the pan. They smell so good

70
00:02:52,720 --> 00:02:55,160
一定是肉是肉(油是油)酱是酱
Meat, oil and paste must be separate like this

71
00:02:55,160 --> 00:02:58,720
酱一定裹在肉上 酱得裹肉上
The meat pieces must be covered with the sauce

72
00:02:58,720 --> 00:03:00,440
油要凸显出来
Oil needs to stand out

73
00:03:00,440 --> 00:03:03,800
不要说酱粘粘乎乎一堆
Don’t make it mixed up altogether

74
00:03:03,800 --> 00:03:05,560
这就是小碗干炸
This is the authentic ‘deep fried sauce in small bowls’

75
00:03:05,560 --> 00:03:09,840
刚才我们讲的这面开锅点三次水
Dip the noodles in boiling water three times like we just said

76
00:03:09,840 --> 00:03:12,680
台湾这个面还真好
These Taiwanese noodles are so good

77
00:03:12,680 --> 00:03:15,160
你看又白又筋道
Brilliantly white and chewy

78
00:03:15,160 --> 00:03:17,760
咱们吃面的时候先这样
We shall eat the noodles like this

79
00:03:17,760 --> 00:03:21,080

80
00:03:21,080 --> 00:03:23,880
它给一勺还要擓一勺油 润它
One spoonful of the sauce with an extra spoon of oil to moisturise the noodles

81
00:03:23,880 --> 00:03:25,240
黄瓜丝
Cucumber juliennes

82
00:03:26,120 --> 00:03:28,280
芹菜末
Celery cubes

83
00:03:29,040 --> 00:03:30,840
豆角白菜
Cowpeas and Chinese cabbage

84
00:03:30,840 --> 00:03:33,400
这个码比面多
There should be more toppings than the actual noodles

85
00:03:34,480 --> 00:03:36,600
吃的就是码和酱
Toppings and sauce are the centrepiece of this dish

86
00:03:36,600 --> 00:03:41,680
萝卜丝 咱北京是心儿里美
Radish juliennes. We Beijingers use this sweet pink-fleshed radish

87
00:03:41,680 --> 00:03:42,400

88
00:03:42,400 --> 00:03:45,000
这个您就自己拌 拌透了
You may mix up everything by yourself. Mix them evenly

89
00:03:45,000 --> 00:03:46,880

90
00:03:46,880 --> 00:03:48,160
不要怕油
Don’t be afraid of the oil

91
00:03:48,160 --> 00:03:51,320
咱讲的是什么 猪油是这样
We have a saying for the pork fat

92
00:03:51,320 --> 00:03:53,840
我父亲活了八十七八
My father lived to his late eighties

93
00:03:53,840 --> 00:03:57,520
他说了想长寿吃肥肉
He said if you wanted to live longer, you must eat fatty meats

94
00:03:57,520 --> 00:04:00,520
然后但是必须要跟上茶
And then drink some tea

95
00:04:00,520 --> 00:04:03,040
吃肥肉没事茶跟上
It’s absolutely fine to eat fatty meats as long as you also drink tea

96
00:04:05,480 --> 00:04:08,280
这个大蒜真棒来一口
These garlics are fantastic

97
00:04:08,280 --> 00:04:10,360
一口面一口大蒜
One mouthful of noodles and one bite of garlics

98
00:04:10,360 --> 00:04:12,040
对味的
They match so well

99
00:04:12,040 --> 00:04:14,720
这个面条的酱炸到什么叫最好
The best sauce for the noodles is that

100
00:04:14,720 --> 00:04:18,280
拌完以后这面条是枣红色
The noodles will become jujube red after mixing up

101
00:04:18,280 --> 00:04:21,280
酱红色特别感觉有食欲的
Such red colour lifts the appetite so much

102
00:04:21,280 --> 00:04:23,280

103
00:04:23,280 --> 00:04:25,360
给个表示怎么样
What do you think of the dish?

104
00:04:25,360 --> 00:04:28,000
武大师亲手做的
Hand made by Shifu Wu

105
00:04:28,000 --> 00:04:29,960
比我的亲家做得还好
It tastes even better than my parents-in-law’s version

106
00:04:29,960 --> 00:04:30,560

107
00:04:32,200 --> 00:04:34,520
行了充电去吧
Alright guys, give it a go

**Comment by immoonancient** [comment]
已发布
