### ISSUE TITLE
[华农兄弟] 野池塘枇杷苗 - https://youtu.be/ZJjZ-UIp8fE

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#724]
https://youtu.be/ZJjZ-UIp8fE
<p>&#35270;&#39057;&#21457;&#24067;&#20110; February 26, 2020 at 11:33AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/ZJjZ-UIp8fE

#华农兄弟：看一下兄弟家的野池塘还有没有鱼，再拔点枇杷苗来种
#Huanong Brothers: Let's take a if there are still any fishh in my buddy's wild pond. And then we pick some loquat seedlings.

0:00:00.000,0:00:00.680
# 大家好
Hi everyone!

0:00:01.020,0:00:02.200
# 今天天氣比較好哦
The weather today is quite good.

0:00:02.280,0:00:04.560
# 我來看一下兄弟家的  那麼野池塘啊
I'm coming to take a look at my buddy's, I mean his wild pond.

0:00:05.100,0:00:06.240
# 好久都沒來過啦
It has been a long time since my last visit.

0:00:06.600,0:00:07.380
# 有點想念
I miss it.

0:00:09.140,0:00:10.280
# 可以  可以過去
It's alright. I can walk from here.

0:00:10.960,0:00:11.840
# 好多水哇
There's so much water.

0:00:14.700,0:00:15.580
# 水都這麼滿
It almost overflows.

0:00:17.560,0:00:18.340
# 肯定有魚
There must be fish.

0:00:19.640,0:00:20.200
# 你看這裡
Have a look at here!

0:00:20.660,0:00:21.660
# 好多蝌蚪哇
There are so many tadpoles.

0:00:22.060,0:00:23.280
# 在游來游去
They're swimming around.

0:00:27.260,0:00:27.940
# 也有小魚
There are also small fish.

0:00:28.920,0:00:29.820
# 大魚沒看到
But I can't see any big fish.

0:00:37.940,0:00:39.620
# 你看  這水好多啦  現在
Look! Now there's so much water.

0:00:40.880,0:00:42.340
# 放水都不好放  太多水了啦
There's so much water that draining out the water may not be a good idea.

0:00:43.060,0:00:44.560
# 下次我用  魚釣來勾
Next time I'll come with a hook, to catch the fish.

0:00:45.820,0:00:48.100
# 勾不到的時候就  沒辦法了就放水
Draining out the water is the last resort, when the hook doesn't work.

0:00:48.920,0:00:50.080
# 用抽水機來抽
I can use my water pump.

0:00:51.920,0:00:53.020
# 我剛才看到好多
I've just seen a lot,

0:00:53.600,0:00:54.220
# 好多魚
a lot of fish.

0:00:57.500,0:00:58.360
# 看到我都跑
But they ran way when they saw me.

0:01:02.620,0:01:03.220
# 小的
This one is small.

0:01:07.340,0:01:08.480
# 沒有紅鯉魚
I can't see any red carps.

0:01:08.680,0:01:09.600
# 沒紅鯉魚
There are no red carps.

0:01:17.900,0:01:19.520
# 你看這個有一棵批把樹哦
Look! Here's a loquat tree.

0:01:20.580,0:01:21.480
# 我把它拔出來
Let me pull it out.

0:01:22.700,0:01:24.100
# 這里面是兄弟家的菜園
Inside the fence is my buddy's veggie garden.

0:01:24.480,0:01:26.260
# 這個兄弟  兄弟種的
This tree was planted, planted by my buddy.

0:01:26.900,0:01:29.060
# 它的脖子往外歪  歪出來啦
Its neck is bending out, out of the fence.

0:01:29.860,0:01:30.620
# 我把它拔掉
Let me pull it out.

0:01:38.480,0:01:39.500
# 拔到那個
I pull it out and then,

0:01:40.140,0:01:41.680
# 拔到我們下面那邊去種
and then plant it at our site.

0:01:42.480,0:01:43.800
# 還有  這邊還有
There are some more, some more over there.

0:01:43.980,0:01:45.200
# 你看  這裡也有一棵
Look! Here's another one.

0:01:48.580,0:01:50.540
# 種就種多一點  看下還有沒有
It's better to plant more. Let's see if there are any more.

0:01:51.880,0:01:53.920
# 你看  這棵批把樹是野生的哦
Look! This is a wild loquat tree.

0:01:53.980,0:01:55.260
# 它就這樣長在河邊
It's simply growing on the riverside.

0:01:55.700,0:01:56.800
# 還有的時候就一直
When I was a kid, it was like...

0:01:57.740,0:01:58.720
# 現在那麼大啦
But it's that big now.

0:01:59.360,0:02:01.180
# 我記得我還小的時候就那麼大一點
I remember that it was just around that big when I was a kid.

0:02:01.720,0:02:04.120
# 經常爬上去 現在那麼大啦  這棵樹
I used to climb this tree pretty often. It's so big now.

0:02:05.240,0:02:06.160
# 看一下還有沒有
Let me see if there are any more.

0:02:06.200,0:02:07.020
# 誒  這里有
Eh? Here's one!

0:02:09.920,0:02:10.780
# 這是它的秧
This is its seedling.

0:02:14.660,0:02:15.720
# 這裡也有一棵
Here's one more.

0:02:20.060,0:02:21.040
# 這裡也有一棵
And here's one more.

0:02:25.040,0:02:26.040
# 這裡也有一棵
And here's one more.

0:02:29.500,0:02:31.880
# 可以  你看  這有六七棵這個 批把曲
Alright! Look! Here are half a dozen of, you know, loquat seedlings.

0:02:32.620,0:02:33.800
# 我們拿到下面去種
Let's plant them down there.

0:02:36.500,0:02:38.280
# 兄弟家問口又找到兩棵
I see two more in front of my buddy's door.

0:02:39.820,0:02:40.680
# 他家的比較
His seedling are,

0:02:41.160,0:02:42.220
# 比較大一點
are a bit larger.

0:02:43.760,0:02:44.500
# 這裡有一棵
Here's one.

0:02:47.320,0:02:48.840
# 你看  這個很大  好靚
Look! This one is really big, and beautiful!

0:02:54.900,0:02:56.100
# 你看  拔了一棵大的
Look! I've picked a big one!

0:02:56.300,0:02:57.400
# 大的種到這裡來
I plant the big one here.

0:03:13.420,0:03:14.800
# 這樣種下去就可以啦
I only need to leave it here.

0:03:16.240,0:03:17.380
# 馬上就要下雨啦
It will be raining very soon.

0:03:17.780,0:03:18.580
# 水都不用澆
So I don't even need to water it.

0:03:19.220,0:03:19.840
# 等下
It'll,

0:03:20.040,0:03:21.360
# 快下點雨就可以啦
it'll be fine as long as there's rain.

0:03:22.980,0:03:23.840
# 種了棵
So I'm done with one.

0:03:25.020,0:03:26.620
# 還有幾棵 我到那邊去種
There is still a couple more. Let me plant them over there.

0:03:32.820,0:03:34.000
# 這個就種到這裡啦
I'll plant this one here.

0:03:39.760,0:03:41.060
# 好  這裡種了一棵
Alright! One is planted here!

0:03:41.240,0:03:42.600
# 現在全部種好啦
All have been planted now.

0:03:43.200,0:03:45.480
# 到時候  到時候我們就有批把吃啦
We'll, we'll have loquats later.

0:03:46.460,0:03:47.800
# 今天的視頻到這裡啦
The video ends here.

**Comment by vincenthychow** [comment]
已發佈
