### ISSUE TITLE
【美食作家王刚】懒人烧豆腐 - https://youtu.be/fzHXf8XRQxI

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#729]
【美食作家王刚】懒人烧豆腐 - https://youtu.be/fzHXf8XRQxI
视频时长 3:30，预计发布时间为北京时间2月29日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.500,0:00:01.820
哈喽大家好 我是王刚

0:00:01.820,0:00:03.780
本期视频我跟大家分享一道家常菜

0:00:04.280,0:00:05.340
懒人烧豆腐

0:00:05.760,0:00:07.880
首先我们准备老豆腐2大块（约500克）

0:00:07.947,0:00:09.771
将老豆腐切成厚片备用（约0.8厘米）

0:00:17.752,0:00:19.478
下一步开始准备辅料

0:00:19.674,0:00:21.498
准备小米辣几个切碎备用

0:00:23.876,0:00:26.710
准备二荆条2个从中间片开之后切碎备用

0:00:32.052,0:00:34.462
准备大蒜2颗拍散之后剁碎备用

0:00:35.570,0:00:37.687
准备韭菜几根切成小段备用

0:00:37.719,0:00:40.325
喜欢吃肉的同学可以加一些五花肉

0:00:41.009,0:00:42.671
下一步开始准备料汁

0:00:42.833,0:00:44.657
碗中加入食用盐半勺（约1克）

0:00:44.860,0:00:46.431
加入少许白糖

0:00:46.612,0:00:48.078
加入生抽酱油6克

0:00:50.618,0:00:51.824
加入蚝油3克

0:00:54.625,0:00:56.254
加入清水150克

0:00:58.925,0:01:01.628
最后加入1大勺土豆淀粉搅拌均匀备用

0:01:03.452,0:01:04.885
下一步开始制作

0:01:05.179,0:01:06.644
首先我们把锅烧热

0:01:06.840,0:01:09.348
锅烧热之后加入适量的植物油滑锅

0:01:11.433,0:01:14.560
滑好锅之后将热油倒出之后再加入少许的底油

0:01:17.850,0:01:19.869
在锅中撒入少许的食用盐

0:01:24.258,0:01:26.742
然后将切好的老豆腐依次下入锅中

0:01:26.807,0:01:28.990
同学们加盐煎豆腐可以防止粘锅

0:01:29.022,0:01:30.618
同时还能够去除豆腥味

0:01:40.651,0:01:43.550
豆腐下锅之后再加入适量的油从锅边淋入

0:01:47.361,0:01:49.315
然后转中小火煎6分钟

0:01:49.851,0:01:52.685
煎的过程中必须随时摇动豆腐防止煎糊

0:01:55.254,0:01:57.013
中途再翻过来煎另一面

0:02:17.436,0:02:20.986
将豆腐煎至金黄色之后加入切好的辣椒和蒜末炒香

0:02:25.338,0:02:27.619
中途可以适当的加一些油来润锅

0:02:34.131,0:02:37.030
辣椒煎香之后将调好的料汁搅拌均匀下锅

0:02:51.610,0:02:54.444
汤汁稍浓之后加入切好的韭菜段烧至断生

0:03:01.631,0:03:04.204
韭菜烧至断生之后即可出锅装盘

0:03:09.173,0:03:12.096
一道非常简单美味的烧豆腐就制作完成

0:03:14.080,0:03:29.500
下面开始技术总结
第一，选择老豆腐煎出来比嫩豆腐更香且不容易碎
第二，煎豆腐的锅中不能有水否则容易粘锅煎碎
第三，此菜为懒人菜系全过程豆腐只需要翻一次即可
懒人烧豆腐的技术总结完毕

**Comment by lhy8458d** [comment]
已认领

**Comment by lhy8458d** [comment]
认领

**Comment by lhy8458d** [comment]
bot, please upload.
0:00:00.500,0:00:01.820
哈喽大家好 我是王刚
Hello, everyone. I am Wang Gang
0:00:01.820,0:00:03.780
本期视频我跟大家分享一道家常菜
In this video I m going to share an ordinary home cook meal with you. 
0:00:04.280,0:00:05.340
懒人烧豆腐
Lazy man’s Tofu. 
0:00:05.760,0:00:07.880
首先我们准备老豆腐2大块（约500克）
Firstly, we prepare 2 pieces of hard bean tofu. (around 500 g)  
0:00:07.947,0:00:09.771
将老豆腐切成厚片备用（约0.8厘米）
cut the tofu into thick slices. (0.8 cm width) 
0:00:17.752,0:00:19.478
下一步开始准备辅料
Next, prepare the intergradient. 
0:00:19.674,0:00:21.498
准备小米辣几个切碎备用
Prepare "Xiaomila" chili pepper, mince. 
0:00:23.876,0:00:26.710
准备二荆条2个从中间片开之后切碎备用
Prepare 2 piece of "Erjingtiao" chili pepper. Cut from the middle and then mince. 
0:00:32.052,0:00:34.462
准备大蒜2颗拍散之后剁碎备用
Prepare 2 piece of garlic. Crush them and then mince. 
0:00:35.570,0:00:37.687
准备韭菜几根切成小段备用
Prepare a few Chinese chives. Cut into small pieces. 
0:00:37.719,0:00:40.325
喜欢吃肉的同学可以加一些五花肉
For those meat lover, you can put in some pork belly. 
0:00:41.009,0:00:42.671
下一步开始准备料汁
Next, prepare the sauce. 
0:00:42.833,0:00:44.657
碗中加入食用盐半勺（约1克）
Put half teaspoon of salt into the bowl. (around 1 g) 
0:00:44.860,0:00:46.431
加入少许白糖
Add a little bit of sugar. 
0:00:46.612,0:00:48.078
加入生抽酱油6克
Add 6 g of soy sauce. 

0:00:50.618,0:00:51.824
加入蚝油3克
Add 3 g of oyster sauce. 
0:00:54.625,0:00:56.254
加入清水150克
Add 150 g of fresh water. 
0:00:58.925,0:01:01.628
最后加入1大勺土豆淀粉搅拌均匀备用
At last, add one cooking spoon of potato starch. Stirring until they evenly mixed.  
0:01:03.452,0:01:04.885
下一步开始制作
Next, we start to cook. 
0:01:05.179,0:01:06.644
首先我们把锅烧热
Firstly, let’s heat up the wok. 
0:01:06.840,0:01:09.348
锅烧热之后加入适量的植物油
Until the wok is heated, put in some vegetable oil to grease the wok. 
0:01:11.433,0:01:14.560
滑好锅之后将热油倒出之后再加入少许的底油
After that, get rid of the greasing oil. Then put in some base oil. 
0:01:17.850,0:01:19.869
在锅中撒入少许的食用盐
Add a little bit of salt. 
0:01:24.258,0:01:26.742
然后将切好的老豆腐依次下入锅中
Then we put in our sliced tofu into the wok by order. 
0:01:26.807,0:01:28.990
同学们加盐煎豆腐可以防止粘锅
Fellows, adding some salt can prevent tofu from sticking onto the wok during pan-frying. 
0:01:29.022,0:01:30.618
同时还能够去除豆腥味
And meantime, unwanted smell of tofu can be removed. 
0:01:40.651,0:01:43.550
豆腐下锅之后再加入适量的油从锅边淋入
After putting tofu into the wok, adding some more oil from the edges of the wok. 
0:01:47.361,0:01:49.315
然后转中小火煎6分钟
Turn down the heat to medium-low. Then fry for 6 mins. 
0:01:49.851,0:01:52.685
煎的过程中必须随时摇动豆腐防止煎糊
During pan-frying, keep moving tofu pieces in wok to prevent it getting burnt. 
0:01:55.254,0:01:57.013
中途再翻过来煎另一面
In the middle of fry, turn the tofu around and fry another side.  
0:02:17.436,0:02:20.986
将豆腐煎至金黄色之后加入切好的辣椒和蒜末炒香
After the tofu turns into golden yellow, then we put peppers and garlic into the wok. 
0:02:25.338,0:02:27.619
中途可以适当的加一些油来润锅
During cooking, you can put in some extra oil to keep the wok moist. 
0:02:34.131,0:02:37.030
辣椒煎香之后将调好的料汁搅拌均匀下锅
After the taste of the peppers coming out, we can put our prepared sauce evenly into the wok. 
0:02:51.610,0:02:54.444
汤汁稍浓之后加入切好的韭菜段烧至断生
After thickening the sauce, put in Chinese chives and soften them. 
0:03:01.631,0:03:04.204
韭菜烧至断生之后即可出锅装盘
After Chinese chive getting soft, we can finish the dish and place the plate. 
0:03:09.173,0:03:12.096
一道非常简单美味的烧豆腐就制作完成
And now a simple-cooked delicious tofu is finished. 
0:03:14.080,0:03:29.500
下面开始技术总结
第一，选择老豆腐煎出来比嫩豆腐更香且不容易碎
第二，煎豆腐的锅中不能有水否则容易粘锅煎碎
第三，此菜为懒人菜系全过程豆腐只需要翻一次即可
懒人烧豆腐的技术总结完毕

Now we summarize the key points.

Firstly, we use hard bean tofu instead of tender bean tofu. It tastes better and it’s easier to keep the shape. 

Secondly, make sure there is no water in wok during frying. Otherwise the tofu would stick onto the wok and easily broke. 

Thirdly, this dish is designed for lazy people. You only need to turn the tofu once during the whole cooking process. 

Those are the all for this Lazy man’s tofu.

**Comment by immoonancient** [comment]
已发布
