### ISSUE TITLE
[华农兄弟] 地笼收鱼 - https://youtu.be/z5mlJIFOgO4

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#731]
https://youtu.be/z5mlJIFOgO4
<p>&#35270;&#39057;&#21457;&#24067;&#20110; February 28, 2020 at 11:31AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/z5mlJIFOgO4

#华农兄弟：扔了4个地笼到水潭里，第二天高兴的带个桶去收鱼
#Huanong Brothers: We threw four traps into the pond. The next time, we go back to the pond happily with a bucket, to get the fish.

0:00:00.140,0:00:00.840
# 大家好
Hi everyone!

0:00:01.140,0:00:02.300
# 我帶了點這個地籠
I'm taking some, you see, some traps,

0:00:02.380,0:00:03.880
# 去抓點那個魚來養  (註︰他現在說是養，後來說是用油炸)
to catch some, you know, some fish back home,

0:00:04.040,0:00:05.100
# 在河裡面抓
from the river,

0:00:06.220,0:00:06.760
# 在下面
down there.

0:00:12.040,0:00:15.460
# 你看  這個好靚啊  肯定很多魚
Look! It's so beautiful! There must be a lot of fish.

0:00:32.520,0:00:34.120
# 這個是新網來的哦
This is a new trap, you know.

0:00:34.840,0:00:35.940
# 還是去年買的
But it was bought last year.

0:00:36.540,0:00:37.240
# 沒有繩子啦
There's no string.

0:00:37.900,0:00:39.020
# 我去找一(個)[SIC]根繩子來
Let me fetch a piece of string.

0:01:19.720,0:01:21.160
# 好啦  放好一個啦
Alright! I'm done with this one.

0:01:21.640,0:01:23.220
# 還有幾個放到下面去
There's a couple more. I'm gonna put them down there.

0:01:57.400,0:01:59.580
# 還有兩副網  放到一下面去
There are two more. Let me put them down there.

0:02:25.580,0:02:26.980
# 現在已經搞好了哦
So now we're done.

0:02:27.560,0:02:29.940
# 放下地籠啦  明天我們再過來收
All the traps have been placed. We'll come again tomorrow to get them back.

0:02:31.900,0:02:32.980
# 第二天
The next day

0:02:33.320,0:02:34.740
# 昨天晚上我做夢
I made a dream yesterday night.

0:02:34.740,0:02:37.680
# 看到那個一地龍都是那個草魚呀  鯉魚呀  鯽魚呀  (註︰這裡有作太多翻譯了，總之一大堆魚吧)
In the dream, I saw the traps were filled with, you know, carps, grass carps, and many others.

0:02:37.760,0:02:38.720
# 好多  好多魚
A lot and a lot of fish!

0:02:38.820,0:02:39.800
# 還有石斑魚
And cichlids too!

0:02:40.120,0:02:42.860
# 我帶一個那麼大的桶去裝  把它裝滿帶回家
I'm going with such a huge bucket and come back with the bucket filled with fish.

0:03:20.420,0:03:23.020
# 我們到河邊啦  就好那邊  去看一下
We're now at the riverside. It's right over there. Let's take a look.

0:03:23.620,0:03:24.680
# 肯定有魚
There must be fish.

0:04:02.540,0:04:03.540
# 就一條泥鰍
Just a pond loach

0:04:05.560,0:04:06.460
# 就一條泥鰍
Just a pond loach

0:04:22.540,0:04:23.700
# 哎呀 好重啊
Aya! It's so heavy!

0:04:33.180,0:04:34.260
# 難道又沒有
Nothing again?

0:04:40.840,0:04:42.000
# 兩個小蝦米
Two tiny little shrimps

0:04:43.640,0:04:45.020
# 你看  這個小蝦米
Look! The tiny little shrimps,

0:04:45.160,0:04:46.020
# 很小哦
are really small.

0:04:47.540,0:04:49.500
# 先放在這裡  看一下其它的
I put it here first, and have a look at the other traps.

0:05:14.700,0:05:15.600
# 全是泥巴
Nothing but mud

0:05:30.580,0:05:31.660
# 一條都沒有
There's not even one fish.

0:05:42.980,0:05:44.400
# 你看就摘了那麼一點  (註︰我覺得他應該是說「抓」，不要「摘」)
Look! We have just a tiny little bit here.

0:05:47.040,0:05:48.200
# 昨天沒有放餌料
I didn't put any bait yesterday.

0:05:48.380,0:05:51.180
# 肯定沒餌料(的原因) 不然怎麼會那麼一點點吧
Yea, no bait! Otherwise I wouldn't have just a tiny little bit here.

0:05:55.700,0:05:56.660
# 全是小魚
All are small fish.

0:05:58.200,0:05:59.940
# 你看  這條拿沙狗子
Look! This is a goby.

0:06:02.000,0:06:04.160
# 這條是花鯽魚  長不大的 就那麼大一點
This is a "hua ji yu". It's always that small. It won't get any bigger.

0:06:04.260,0:06:05.400
# 這是石斑魚
This is a cichlid.

0:06:05.520,0:06:06.360
# 這是泥鰍
And this is a pond loach,

0:06:06.400,0:06:06.980
# 蝦米
small shrimps.

0:06:07.900,0:06:08.940
# 還不夠一餐
That's not even enough for a meal.

0:06:09.440,0:06:11.860
# 如果多一點的話  可以拿回去油炸一下  很好吃的哦
I could have them fried if there are more. I would be really tasty!

0:06:12.020,0:06:12.960
# 現在太少啦
But now it's too few.

0:06:13.420,0:06:14.400
# 把它放掉
Let me just release them.

0:06:17.500,0:06:18.460
# 回歸自然
Back to the nature

0:06:19.220,0:06:20.540
# 下次不要進網了啊
Don't come into the trap next time, got it?

0:06:20.640,0:06:21.180
# 那麼小
You guys are so small.

0:06:33.100,0:06:37.840
# 下次我放點餌料進去  要抓大魚  這個小魚抓得沒意思  太小啦
I'll put some bait next time. I want big fish. The small fish are far too small. It's not fun at all.

0:06:38.480,0:06:39.720
# 下次我搞點餌料來
I'll come with some bait next time.

0:06:39.900,0:06:41.900
# 我又沒放餌料抓了那麼小
Without the bait, there are only small fish.

0:06:43.460,0:06:44.600
# 把你們放走吧
Let me release you guys.

0:06:45.540,0:06:47.780
# 放點哦 不然 你們自由了
Hurry up! Otherwise.... You're free now.

0:06:49.400,0:06:51.860
# 加油  加油  誰跑得快一點
Keep going, keep going! Let's see who is the fastest.

0:06:52.340,0:06:53.440
# 逆水而上
They're swimming against the current.

0:06:55.140,0:06:56.460
# 好多都逆水而上啦
Many are already swimming against the current.

0:06:57.460,0:06:59.320
# 誰不上的  我拿回去
Those who are not swimming, are to go back home with me,

0:06:59.960,0:07:02.180
# 我拿回去用油炸一下
back home with me, and to be fried in oil.

0:07:04.020,0:07:05.960
# 全部都往上爬
They're all swimming upwards.

0:07:08.080,0:07:10.560
# 快點跑哦  不跑就沒機會啦
C'mon! Hurry up! This is your last chance!

0:07:15.280,0:07:17.980
# 全跑啦  就剩下一條泥鰍
All have run away, except this pond loach.

0:07:18.140,0:07:20.200
# 泥鰍你怎麼那麼笨  走哇
Why are you do stupid, pond loach? Just go!

0:07:22.360,0:07:25.500
# 等一下今天晚上就把你那個煮啦哦  跑啦
Otherwise I'll have you cooked tonight. Alright it has left.

0:07:26.780,0:07:29.260
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.

0:07:30.200,0:07:31.000
# 回去啦
Let's go back.

0:07:32.240,0:07:34.460
# 抓了那麼小的魚  沒意思
The fish are so small. It's not fun at all.

0:07:37.000,0:07:38.660
# 桶又帶一個那麼大的來
I came with such a large bucket.

0:07:39.420,0:07:40.640
# 就沒裝到
But it's still empty.

**Comment by vincenthychow** [comment]
已發佈

**Comment by immoonancient** [comment]
尝试给 bot 加个新功能，做个测试

**Comment by immoonancient** [comment]
测试通过，sorry for the noise...

**Comment by immoonancient** [comment]
sorry, 再测一轮...

**Comment by immoonancient** [comment]
这次真的是最后一轮测试...
