### ISSUE TITLE
【美食作家王刚】安装工程灶 - https://youtu.be/LljkO7EXgRY

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#735]
【美食作家王刚】安装工程灶 - https://youtu.be/LljkO7EXgRY
视频时长 5:42，预计发布时间为北京时间3月2日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.358,0:00:01.587
嗨喽大家好我是王刚

0:00:02.133,0:00:03.720
之前 也不是之前

0:00:03.720,0:00:06.348
反正一两年来总有粉丝要问

0:00:06.655,0:00:09.982
我们这个专业设备买来适不适合家里面用

0:00:10.273,0:00:12.525
今天我就买一套来告诉大家

0:00:13.310,0:00:14.266
不适合家里用

0:00:14.692,0:00:18.020
然后跟大家介绍一下这个工程款的炉灶

0:00:19.061,0:00:21.523
师傅 我们这个灶还是你来介绍吧

0:00:21.552,0:00:23.737
你要专业一点

0:00:24.180,0:00:26.348
这个灶属于是油气两用

0:00:26.382,0:00:28.651
它其实还可以三用 它液化气也能用

0:00:28.651,0:00:29.313
嗯 对

0:00:29.368,0:00:32.098
然后这里这个是天然气的开关

0:00:32.286,0:00:34.078
这个是烧油的那个开关

0:00:34.078,0:00:35.733
油开关嘛反正

0:00:35.784,0:00:37.781
然后下面这个是风机的开关

0:00:37.815,0:00:40.648
它这个灶的风机功率特别大

0:00:40.904,0:00:43.447
所以它这个只要一台风机就够了

0:00:45.290,0:00:49.078
然后像这个高端的好一点的那个灶都配了这种

0:00:49.180,0:00:53.122
就是那边有一个水可以直接洗灶台的这种

0:00:53.395,0:00:54.266
方便一点

0:00:55.051,0:00:56.467
OK 我来补充一下

0:00:56.621,0:00:59.744
我们这一款的话是工程灶 超大型的

0:00:59.897,0:01:03.225
长2米 宽是116厘米

0:01:03.481,0:01:04.351
是116吧

0:01:04.351,0:01:04.965
对对对

0:01:05.034,0:01:06.040
116厘米 

0:01:06.416,0:01:09.590
然后我们这个宽度的话是非常宽

0:01:09.607,0:01:11.689
然后高的话大概是80（厘米）的样子

0:01:12.389,0:01:14.095
79-80（厘米）

0:01:14.624,0:01:16.945
我们这个灶是酒店里面的专业款

0:01:17.542,0:01:21.450
然后很多粉丝他说看我们在厨房里面炒菜

0:01:21.467,0:01:25.029
他觉得这一款如果在自己家里面买一套的话就非常好

0:01:25.051,0:01:26.006
其实我想告诉你

0:01:26.194,0:01:30.563
你们家里面的厨房拿都拿不进去 首先第一点

0:01:31.006,0:01:32.116
宽都这么宽

0:01:32.354,0:01:33.293
然后是什么呢

0:01:33.327,0:01:36.382
我们这个灶是费了很大力气

0:01:36.433,0:01:37.866
六七个人抬下来

0:01:38.225,0:01:39.505
这个灶有八百斤没有

0:01:40.204,0:01:40.750
差不多

0:01:40.870,0:01:41.860
差不多八百斤

0:01:41.996,0:01:43.750
以前的灶它还更加重

0:01:43.754,0:01:46.382
因为它里面是弄的水泥是吧

0:01:46.399,0:01:46.825
对对对

0:01:46.945,0:01:49.078
现在它不是水泥 现在要减轻一点

0:01:49.641,0:01:55.972
然后这一套设备除了酒店里面用的话没有其他什么地方用

0:01:56.023,0:01:58.566
其他地方用的话就是用再小一点的

0:01:58.737,0:02:00.290
小的尺寸是多少

0:02:00.631,0:02:04.215
小的是有1米55乘以80（厘米）的

0:02:04.726,0:02:06.604
还有那个1米75乘80

0:02:07.969,0:02:08.976
哦 宽是80

0:02:09.044,0:02:09.829
对对对

0:02:10.580,0:02:12.252
高度都是差不多一样高的

0:02:12.303,0:02:13.890
所有厨房的东西都差不多高

0:02:14.044,0:02:17.013
比方说包括操作台那些东西都是一样高 都是80

0:02:17.252,0:02:20.836
所以说家里面用这个不是买一个灶就可以了

0:02:21.313,0:02:23.788
还要有上面的抽风机

0:02:24.812,0:02:26.518
要不然这个油烟非常的大

0:02:27.269,0:02:28.583
然后还有一个原因是什么呢

0:02:28.754,0:02:31.177
它下面有一个鼓风机

0:02:31.979,0:02:37.030
这个鼓风机550瓦 非常的吵

0:02:37.798,0:02:40.068
因为农村的柴火都比较小

0:02:40.682,0:02:44.129
炒菜达不到我想要的那种效果

0:02:45.614,0:02:48.805
用惯了这个灶 用柴火灶有点不习惯

0:02:49.436,0:02:52.167
所以现在买一套来练一下手

0:02:54.436,0:02:55.529
好 师傅你继续吧

0:02:56.194,0:02:59.539
弄好了我好来试一下

0:03:14.726,0:03:19.180
好了 我们这个灶已经电接好了 气也接好了

0:03:19.300,0:03:20.631
现在就先试一下 

0:03:21.194,0:03:23.737
火能不能吹起来

0:03:31.962,0:03:32.866
电帮我开一下

0:04:04.568,0:04:06.679
好 可以 差不多

0:04:07.332,0:04:09.596
再试下另外一个

0:04:45.182,0:04:47.523
没有问题 没有什么大问题

0:04:48.483,0:04:50.249
现在就差水了是吧

0:04:50.902,0:04:52.667
现在水接上就可以了

0:04:53.704,0:04:55.623
好了 这个放一点水进去

0:04:55.738,0:04:57.619
因为我们这个干烧的话

0:04:57.696,0:05:00.767
这个气从这里出去 热量从这里出去

0:05:00.959,0:05:02.418
所以这个里面要放点水

0:05:11.170,0:05:12.821
这边把水给它放上的话

0:05:13.781,0:05:16.161
它使用的寿命就会更加的长

0:05:16.276,0:05:21.689
所以我们在视频里面会看到它这个水管会一直水流个不停

0:05:21.804,0:05:24.760
就是为了降温度 降温用的

0:05:26.564,0:05:29.712
如果不给它降温的话 这里温度会非常高

0:05:29.788,0:05:32.744
这些地方 还有这里都会烧坏

0:05:34.472,0:05:36.314
好了 本期视频就到这里了

0:05:36.429,0:05:40.115
待会儿把这个撕掉 这个灶就非常的漂亮了

**Comment by Jasminelv** [comment]
认领。

**Comment by Jasminelv** [comment]
认领

**Comment by Jasminelv** [comment]
【美食作家王刚】安装工程灶 - https://youtu.be/LljkO7EXgRY   视频时长   5:42，预计发布时间为北京时间3月2日晚   这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面   文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！   0:00:00.358,0:00:01.587   嗨喽大家好我是王刚   Hello everyone, I am Wang Gang.   0:00:02.133,0:00:03.720   之前 也不是之前   In the past days…maybe earlier,   0:00:03.720,0:00:06.348   反正一两年来总有粉丝要问   Anyway, every once in a while some fans will ask me,   0:00:06.655,0:00:09.982   我们这个专业设备买来适不适合家里面用   Should they buy and install our professional cooking   system for their home use.   0:00:10.273,0:00:12.525   今天我就买一套来告诉大家   Today I will demonstrate    0:00:13.310,0:00:14.266   不适合家里用   How it doesn’t work for home cooking.   0:00:14.692,0:00:18.020   然后跟大家介绍一下这个工程款的炉灶   I will also introduce to you the professional cooking   stove.   0:00:19.061,0:00:21.523   师傅 我们这个灶还是你来介绍吧   Sir, please do the introduction and presentation,   0:00:21.552,0:00:23.737   你要专业一点   You are the professional.   0:00:24.180,0:00:26.348   这个灶属于是油气两用   This stove works both for oil and gas.   0:00:26.382,0:00:28.651   它其实还可以三用 它液化气也能用   Actually it works with propane, too.   0:00:28.651,0:00:29.313   嗯 对   Yes, that’s right.   0:00:29.368,0:00:32.098   然后这里这个是天然气的开关   Now, here it is the switch for natural gas.   0:00:32.286,0:00:34.078   这个是烧油的那个开关   And this is the switch for oil.   0:00:34.078,0:00:35.733   油开关嘛反正   OK the oil switch.   0:00:35.784,0:00:37.781   然后下面这个是风机的开关   Underneath here it is the switch for the fan.   0:00:37.815,0:00:40.648   它这个灶的风机功率特别大   This stove fan power is higher than most of the others.   0:00:40.904,0:00:43.447   所以它这个只要一台风机就够了   Therefore it only needs one fan.   0:00:45.290,0:00:49.078   然后像这个高端的好一点的那个灶都配了这种   And higher end stoves like this all have the advanced   0:00:49.180,0:00:53.122   就是那边有一个水可以直接洗灶台的这种   Running water system to conveniently clean the cooking   area   0:00:53.395,0:00:54.266   方便一点   Make things easier    0:00:55.051,0:00:56.467   OK 我来补充一下   OK, let me add some more details about this   0:00:56.621,0:00:59.744   我们这一款的话是工程灶 超大型的   What we have here is an oversized engineering level stove   0:00:59.897,0:01:03.225   长2米 宽是116厘米   It is 2 meters long, 116 centimeters wide   0:01:03.481,0:01:04.351   是116吧   Is is 116 centimeters?   0:01:04.351,0:01:04.965   对对对   Yes, that is correct.   0:01:05.034,0:01:06.040   116厘米   116 centimeters.   0:01:06.416,0:01:09.590   然后我们这个宽度的话是非常宽   And the width is extra wide too.   0:01:09.607,0:01:11.689   然后高的话大概是80（厘米）的样子   The height is about 80 centimeters.   0:01:12.389,0:01:14.095   79-80（厘米）   79-80 centimeters.   0:01:14.624,0:01:16.945   我们这个灶是酒店里面的专业款   This stove is the professional style for restaurants.   0:01:17.542,0:01:21.450   然后很多粉丝他说看我们在厨房里面炒菜   Many fans said they really love the way we cook in the   kitchen   0:01:21.467,0:01:25.029   他觉得这一款如果在自己家里面买一套的话就非常好   And they wanted the same cooking system installed in their   own homes for the best cooking results.   0:01:25.051,0:01:26.006   其实我想告诉你   But I would really want to tell you,    0:01:26.194,0:01:30.563   你们家里面的厨房拿都拿不进去 首先第一点   It would not fit for a home kitchen.  First of all,    0:01:31.006,0:01:32.116   宽都这么宽   It is very wide.   0:01:32.354,0:01:33.293   然后是什么呢   Second…   0:01:33.327,0:01:36.382   我们这个灶是费了很大力气   We made an ultimate effort   0:01:36.433,0:01:37.866   六七个人抬下来   With 6-7 people carried it together,    0:01:38.225,0:01:39.505   这个灶有八百斤没有   Does this stove weight around 400 KG (880 lbs)?   0:01:40.204,0:01:40.750   差不多   Very close estimate.   0:01:40.870,0:01:41.860   差不多八百斤   Around 400 KG.   0:01:41.996,0:01:43.750   以前的灶它还更加重   The former one was even heavier.   0:01:43.754,0:01:46.382   因为它里面是弄的水泥是吧   Is it because it was built with cement inside?   0:01:46.399,0:01:46.825   对对对   Yes, that is right.   0:01:46.945,0:01:49.078   现在它不是水泥 现在要减轻一点   This one has no cement, therefore it weighs less.   0:01:49.641,0:01:55.972   然后这一套设备除了酒店里面用的话没有其他什么地方用   Would any other facilities use this kind of equipment   beside restaurants?   0:01:56.023,0:01:58.566   其他地方用的话就是用再小一点的   Other facilities would use smaller versions.   0:01:58.737,0:02:00.290   小的尺寸是多少   What are the measurements for the smaller versions?   0:02:00.631,0:02:04.215   小的是有1米55乘以80（厘米）的   Some are like 1.55 meters by 80 centimeters.   0:02:04.726,0:02:06.604   还有那个1米75乘80   Also there is 1.75 meters by 80 centimeters.   0:02:07.969,0:02:08.976   哦 宽是80   OK, so the width would be 80 meters.   0:02:09.044,0:02:09.829   对对对   That is right.   0:02:10.580,0:02:12.252   高度都是差不多一样高的   The height is always almost the same.   0:02:12.303,0:02:13.890   所有厨房的东西都差不多高   All the kitchen stuff are almost the same height.   0:02:14.044,0:02:17.013   比方说包括操作台那些东西都是一样高 都是80   For instance things including countertops are always 80 centimeters   high.   0:02:17.252,0:02:20.836   所以说家里面用这个不是买一个灶就可以了   So when use at home, buying a stove is only a start.   0:02:21.313,0:02:23.788   还要有上面的抽风机   Also you will need a kitchen fan.   0:02:24.812,0:02:26.518   要不然这个油烟非常的大   Otherwise the cooking smoke will be overwhelming.   0:02:27.269,0:02:28.583   然后还有一个原因是什么呢   And another reason that makes it impractical is   0:02:28.754,0:02:31.177   它下面有一个鼓风机   There should be a blower under there.   0:02:31.979,0:02:37.030   这个鼓风机550瓦 非常的吵   This blower’s power is 550 Walt, very noisy   0:02:37.798,0:02:40.068   因为农村的柴火都比较小   In the countryside, we use chop wood, it is not powerful enough   for me   0:02:40.682,0:02:44.129   炒菜达不到我想要的那种效果   I can not get the result I want with chop wood stove.   0:02:45.614,0:02:48.805   用惯了这个灶 用柴火灶有点不习惯   I am now used to this stove, and a stranger of the chop   wood stove.   0:02:49.436,0:02:52.167   所以现在买一套来练一下手   So I want to purchase this for the purpose of practice.   0:02:54.436,0:02:55.529   好 师傅你继续吧   OK sir, you may continue.   0:02:56.194,0:02:59.539   弄好了我好来试一下   I will try it when you finish with it.   0:03:14.726,0:03:19.180   好了 我们这个灶已经电接好了 气也接好了   OK, now the electric part of the stove is all finished, as   well as the gas connection.   0:03:19.300,0:03:20.631   现在就先试一下   Let’s try it.   0:03:21.194,0:03:23.737   火能不能吹起来   To see if the flame can be blown to a good level.   0:03:31.962,0:03:32.866   电帮我开一下   Please help me to turn the power on.   0:04:04.568,0:04:06.679   好 可以 差不多   OK, not bad, it achieves my expectation.   0:04:07.332,0:04:09.596   再试下另外一个   Let’s try the other stove top.   0:04:45.182,0:04:47.523   没有问题 没有什么大问题   No problem, no big issue.   0:04:48.483,0:04:50.249   现在就差水了是吧   Now we will need the connection of the water, right?   0:04:50.902,0:04:52.667   现在水接上就可以了   Just add the water, it should work fine.   0:04:53.704,0:04:55.623   好了 这个放一点水进去   OK, let’s pour some water in.   0:04:55.738,0:04:57.619   因为我们这个干烧的话   If we heated it dry,   0:04:57.696,0:05:00.767   这个气从这里出去 热量从这里出去   Air will go out here as well as the heat.   0:05:00.959,0:05:02.418   所以这个里面要放点水   So we will need some water in here.   0:05:11.170,0:05:12.821   这边把水给它放上的话   When we have some water here   0:05:13.781,0:05:16.161   它使用的寿命就会更加的长   The service life will be longer.   0:05:16.276,0:05:21.689   所以我们在视频里面会看到它这个水管会一直水流个不停   So in our videos you have seen this water hose always has water   running    0:05:21.804,0:05:24.760   就是为了降温度 降温用的   It is for cooling down   0:05:26.564,0:05:29.712   如果不给它降温的话 这里温度会非常高   If not cooling things down, the temperature will be too   high   0:05:29.788,0:05:32.744   这些地方 还有这里都会烧坏   Here and here….these places will be burnt out.   0:05:34.472,0:05:36.314   好了 本期视频就到这里了   OK, that is all for today’s video.   0:05:36.429,0:05:40.115   待会儿把这个撕掉 这个灶就非常的漂亮了   I will tear this off in a second, then the stove will look   even nicer!
--

**Comment by Jasminelv** [comment]
【美食作家王刚】安装工程灶 - https://youtu.be/LljkO7EXgRY
视频时长 5:42，预计发布时间为北京时间3月2日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！
0:00:00.358,0:00:01.587
嗨喽大家好我是王刚
Hello everyone, I am Wang Gang.
0:00:02.133,0:00:03.720
之前 也不是之前
In the past days…maybe earlier,
0:00:03.720,0:00:06.348
反正一两年来总有粉丝要问
Anyway, every once in a while some fans will ask me,
0:00:06.655,0:00:09.982
我们这个专业设备买来适不适合家里面用
Should they buy and install our professional cooking system for their home use.
0:00:10.273,0:00:12.525
今天我就买一套来告诉大家
Today I will demonstrate 
0:00:13.310,0:00:14.266
不适合家里用
How it doesn’t work for home cooking.
0:00:14.692,0:00:18.020
然后跟大家介绍一下这个工程款的炉灶
I will also introduce to you the professional cooking stove.
0:00:19.061,0:00:21.523
师傅 我们这个灶还是你来介绍吧
Sir, please do the introduction and presentation,
0:00:21.552,0:00:23.737
你要专业一点
You are the professional.
0:00:24.180,0:00:26.348
这个灶属于是油气两用
This stove works both for oil and gas.
0:00:26.382,0:00:28.651
它其实还可以三用 它液化气也能用
Actually it works with propane, too.
0:00:28.651,0:00:29.313
嗯 对
Yes, that’s right.
0:00:29.368,0:00:32.098
然后这里这个是天然气的开关
Now, here it is the switch for natural gas.
0:00:32.286,0:00:34.078
这个是烧油的那个开关
And this is the switch for oil.
0:00:34.078,0:00:35.733
油开关嘛反正
OK the oil switch.
0:00:35.784,0:00:37.781
然后下面这个是风机的开关
Underneath here it is the switch for the fan.
0:00:37.815,0:00:40.648
它这个灶的风机功率特别大
This stove fan power is higher than most of the others.
0:00:40.904,0:00:43.447
所以它这个只要一台风机就够了
Therefore it only needs one fan.
0:00:45.290,0:00:49.078
然后像这个高端的好一点的那个灶都配了这种
And higher end stoves like this all have the advanced
0:00:49.180,0:00:53.122
就是那边有一个水可以直接洗灶台的这种
Running water system to conveniently clean the cooking area
0:00:53.395,0:00:54.266
方便一点
Make things easier 
0:00:55.051,0:00:56.467
OK 我来补充一下
OK, let me add some more details about this
0:00:56.621,0:00:59.744
我们这一款的话是工程灶 超大型的
What we have here is an oversized engineering level stove
0:00:59.897,0:01:03.225
长2米 宽是116厘米
It is 2 meters long, 116 centimeters wide
0:01:03.481,0:01:04.351
是116吧
Is is 116 centimeters?
0:01:04.351,0:01:04.965
对对对
Yes, that is correct.
0:01:05.034,0:01:06.040
116厘米
116 centimeters.
0:01:06.416,0:01:09.590
然后我们这个宽度的话是非常宽
And the width is extra wide too.
0:01:09.607,0:01:11.689
然后高的话大概是80（厘米）的样子
The height is about 80 centimeters.
0:01:12.389,0:01:14.095
79-80（厘米）
79-80 centimeters.
0:01:14.624,0:01:16.945
我们这个灶是酒店里面的专业款
This stove is the professional style for restaurants.
0:01:17.542,0:01:21.450
然后很多粉丝他说看我们在厨房里面炒菜
Many fans said they really love the way we cook in the kitchen
0:01:21.467,0:01:25.029
他觉得这一款如果在自己家里面买一套的话就非常好
And they wanted the same cooking system installed in their own homes for the best cooking results.
0:01:25.051,0:01:26.006
其实我想告诉你
But I would really want to tell you, 
0:01:26.194,0:01:30.563
你们家里面的厨房拿都拿不进去 首先第一点
It would not fit for a home kitchen.  First of all, 
0:01:31.006,0:01:32.116
宽都这么宽
It is very wide.
0:01:32.354,0:01:33.293
然后是什么呢
Second…
0:01:33.327,0:01:36.382
我们这个灶是费了很大力气
We made an ultimate effort
0:01:36.433,0:01:37.866
六七个人抬下来
With 6-7 people carried it together, 
0:01:38.225,0:01:39.505
这个灶有八百斤没有
Does this stove weight around 400 KG (880 lbs)?
0:01:40.204,0:01:40.750
差不多
Very close estimate.
0:01:40.870,0:01:41.860
差不多八百斤
Around 400 KG.
0:01:41.996,0:01:43.750
以前的灶它还更加重
The former one was even heavier.
0:01:43.754,0:01:46.382
因为它里面是弄的水泥是吧
Is it because it was built with cement inside?
0:01:46.399,0:01:46.825
对对对
Yes, that is right.
0:01:46.945,0:01:49.078
现在它不是水泥 现在要减轻一点
This one has no cement, therefore it weighs less.
0:01:49.641,0:01:55.972
然后这一套设备除了酒店里面用的话没有其他什么地方用
Would any other facilities use this kind of equipment beside restaurants?
0:01:56.023,0:01:58.566
其他地方用的话就是用再小一点的
Other facilities would use smaller versions.
0:01:58.737,0:02:00.290
小的尺寸是多少
What are the measurements for the smaller versions?
0:02:00.631,0:02:04.215
小的是有1米55乘以80（厘米）的
Some are like 1.55 meters by 80 centimeters.
0:02:04.726,0:02:06.604
还有那个1米75乘80
Also there is 1.75 meters by 80 centimeters.
0:02:07.969,0:02:08.976
哦 宽是80
OK, so the width would be 80 meters.
0:02:09.044,0:02:09.829
对对对
That is right.
0:02:10.580,0:02:12.252
高度都是差不多一样高的
The height is always almost the same.
0:02:12.303,0:02:13.890
所有厨房的东西都差不多高
All the kitchen stuff are almost the same height.
0:02:14.044,0:02:17.013
比方说包括操作台那些东西都是一样高 都是80
For instance things including countertops are always 80 centimeters high.
0:02:17.252,0:02:20.836
所以说家里面用这个不是买一个灶就可以了
So when use at home, buying a stove is only a start.
0:02:21.313,0:02:23.788
还要有上面的抽风机
Also you will need a kitchen fan.
0:02:24.812,0:02:26.518
要不然这个油烟非常的大
Otherwise the cooking smoke will be overwhelming.
0:02:27.269,0:02:28.583
然后还有一个原因是什么呢
And another reason that makes it impractical is
0:02:28.754,0:02:31.177
它下面有一个鼓风机
There should be a blower under there.
0:02:31.979,0:02:37.030
这个鼓风机550瓦 非常的吵
This blower’s power is 550 Walt, very noisy
0:02:37.798,0:02:40.068
因为农村的柴火都比较小
In the countryside, we use chop wood, it is not powerful enough for me
0:02:40.682,0:02:44.129
炒菜达不到我想要的那种效果
I can not get the result I want with chop wood stove.
0:02:45.614,0:02:48.805
用惯了这个灶 用柴火灶有点不习惯
I am now used to this stove, and a stranger of the chop wood stove.
0:02:49.436,0:02:52.167
所以现在买一套来练一下手
So I want to purchase this for the purpose of practice.
0:02:54.436,0:02:55.529
好 师傅你继续吧
OK sir, you may continue.
0:02:56.194,0:02:59.539
弄好了我好来试一下
I will try it when you finish with it.
0:03:14.726,0:03:19.180
好了 我们这个灶已经电接好了 气也接好了
OK, now the electric part of the stove is all finished, as well as the gas connection.
0:03:19.300,0:03:20.631
现在就先试一下
Let’s try it.
0:03:21.194,0:03:23.737
火能不能吹起来
To see if the flame can be blown to a good level.
0:03:31.962,0:03:32.866
电帮我开一下
Please help me to turn the power on.
0:04:04.568,0:04:06.679
好 可以 差不多
OK, not bad, it achieves my expectation.
0:04:07.332,0:04:09.596
再试下另外一个
Let’s try the other stove top.
0:04:45.182,0:04:47.523
没有问题 没有什么大问题
No problem, no big issue.
0:04:48.483,0:04:50.249
现在就差水了是吧
Now we will need the connection of the water, right?
0:04:50.902,0:04:52.667
现在水接上就可以了
Just add the water, it should work fine.
0:04:53.704,0:04:55.623
好了 这个放一点水进去
OK, let’s pour some water in.
0:04:55.738,0:04:57.619
因为我们这个干烧的话
If we heated it dry,
0:04:57.696,0:05:00.767
这个气从这里出去 热量从这里出去
Air will go out here as well as the heat.
0:05:00.959,0:05:02.418
所以这个里面要放点水
So we will need some water in here.
0:05:11.170,0:05:12.821
这边把水给它放上的话
When we have some water here
0:05:13.781,0:05:16.161
它使用的寿命就会更加的长
The service life will be longer.
0:05:16.276,0:05:21.689
所以我们在视频里面会看到它这个水管会一直水流个不停
So in our videos you have seen this water hose always has water running 
0:05:21.804,0:05:24.760
就是为了降温度 降温用的
It is for cooling down
0:05:26.564,0:05:29.712
如果不给它降温的话 这里温度会非常高
If not cooling things down, the temperature will be too high
0:05:29.788,0:05:32.744
这些地方 还有这里都会烧坏
Here and here….these places will be burnt out.
0:05:34.472,0:05:36.314
好了 本期视频就到这里了
OK, that is all for today’s video.
0:05:36.429,0:05:40.115
待会儿把这个撕掉 这个灶就非常的漂亮了
I will tear this off in a second, then the stove will look even nicer!
