### ISSUE TITLE
[华农兄弟] 砍兄弟家的棕花 - https://youtu.be/M6RvHhO6lhk

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#740]
https://youtu.be/M6RvHhO6lhk
<p>&#35270;&#39057;&#21457;&#24067;&#20110; March 2, 2020 at 11:34AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/M6RvHhO6lhk

#华农兄弟：捡个石头，把刀磨利，砍点兄弟家的棕花来吃
#Huanong Brothers: We pick a rock, sharpen our knife and chop some palm flowers from our buddy for our lunch.

0:00:00.000,0:00:02.180
# 大家好 家裡的菜刀都有點鈍啦
Hi everyone! My kitchen knife at home is a bit blunt,

0:00:02.180,0:00:03.220
# 沒有那個磿刀石
but I don't have a sharpening stone.

0:00:03.480,0:00:05.140
# 我到那個河邊  檢一個磿刀石
We're gonna pick one from the, you know, the riverside.

0:00:09.320,0:00:10.340
# 嗯  這個針草(註︰這個「針草」不像是網上找到的「鬼針草」，隨便取個名字算了)
Um! This is "needle grass".

0:00:12.500,0:00:13.000
# 哎呀
Aya!

0:00:14.120,0:00:14.660
# 哎呀
Aya!

0:00:16.520,0:00:17.660
# 好深啊  這個
It's so deep here.

0:00:34.140,0:00:35.240
# 像這個就可以呀
A stone like this one is good enough.

0:00:35.260,0:00:37.000
# 不過太小啦  我們要找一個大的
But it's too small. We're gonna find a big one.

0:00:37.340,0:00:37.880
# 你看
Look!

0:00:38.600,0:00:40.260
# 一磿就可以把那個粉磨出來  (註︰這裡應該說是磿刀時把鋼粉磿出來)
Then, the steel dust can be ground out,

0:00:41.040,0:00:42.020
# 哇  是不是
Wa! Right?

0:00:42.500,0:00:43.620
# 那刀磿得很利的
The knife can be made really sharp.

0:00:45.320,0:00:46.300
# 要找個大的
I gotta find a big one.

0:00:49.200,0:00:50.160
# 難找哦
That's not easy, though.

0:00:55.860,0:00:57.040
# 好多魚呀
There are a lot of small fish.

0:00:57.060,0:00:58.220
# 都在撞到我腳上來啦
They're all bumping onto my feet.

0:01:04.640,0:01:05.700
# 也有大魚喲
I can see some big fish too.

0:01:21.760,0:01:22.440
# 有個
Here's one!

0:01:24.380,0:01:24.880
# 你看
Look!

0:01:25.160,0:01:25.920
# 這檢了一個
So I've picked one.

0:01:27.000,0:01:28.140
# 呃  這個有用的
Eh! This one is good.

0:01:31.920,0:01:33.420
# 拿回家哦  拿回家去
Let's bring it back, bring it back home.

0:01:33.980,0:01:35.440
# 把我那張菜刀磿利一點
I gotta sharpen my kitchen knife.

0:01:36.700,0:01:37.480
# 看一下還有沒有
Let's see if I can find another one.

0:01:38.140,0:01:39.640
# 好成事雙  多檢一個
Good things should come in pair. So one more.

0:01:49.900,0:01:51.180
# 沒啦  就一個
This is the only one. No more.

0:01:51.700,0:01:52.320
# 一個也好
One is already good enough.

0:01:53.120,0:01:54.340
# 回家  吃午飯
Let's go back home, for lunch,

0:01:54.880,0:01:55.660
# 磿一個那個刀  (註︰不知為何，這樣譯法好像更順耳，但文法卻不對)
and sharpen the knife.

0:02:31.840,0:02:33.400
# 你看 這鐵屑都磿出來啦
Look! This steel dust is already coming out.

0:02:40.080,0:02:41.060
# 好啦  磿好啦
Alright! Done!

0:02:42.100,0:02:43.940
# 隨便削就削掉啦  好利呀
It can simply be peeled. The knife is so sharp now.

0:02:50.600,0:02:53.420
# 我去 菜園裡面看一下  有甚麼好切的
Let me, have a look at the veggie garden and see if there's anything good.

0:02:53.500,0:02:54.200
# 切一點回來
I'll come back with some.

0:02:57.960,0:02:58.700
# 鴨子
Duckies!

0:03:04.520,0:03:05.260
# 小雞
Chickens!

0:03:10.800,0:03:12.380
# 你看  這兄弟家的菜園哦
Look! This is my buddy's veggie garden.

0:03:14.080,0:03:15.040
# 蘿蔔也老啦
The radish is already getting old,

0:03:15.740,0:03:16.600
# 青菜也老啦
and the veggies too.

0:03:18.100,0:03:18.820
# 啥都沒有
Nothing good.

0:03:18.960,0:03:19.540
# 哎喲
Ayo!

0:03:19.740,0:03:20.580
# 兄弟家的雞
My buddy's chickens.

0:03:21.340,0:03:22.100
# 跑那麼快
They're running so fast.

0:03:23.500,0:03:25.920
# 你看  這個  這個  這個可以吃的  這個
Look! This, this, this can be dished up. I mean this,

0:03:27.160,0:03:28.140
# 這個棕樹
this palm,

0:03:28.680,0:03:29.440
# 棕樹花
palm flowers.

0:03:30.420,0:03:30.960
# 哎呀
Aya!

0:03:32.640,0:03:33.260
# 怎麼回事
What happens?

0:03:33.760,0:03:34.840
# 那麼多雞跑出來
So many chickens are running out!

0:03:35.680,0:03:36.960
# 我把這個棕樹把它搞下來
I'm gonna get the palm flowers, get them down.

0:03:37.040,0:03:38.980
# 這個炒  炒肉很好吃的哦  這個
It tastes really good when it's fried, fried with meat.

0:03:43.280,0:03:44.140
# 拿梯子來
I need a ladder.

0:03:47.060,0:03:48.960
# 你看  這個兄弟家的梯子
Look! This is my buddy's ladder.

0:03:49.480,0:03:50.380
# 借用一下啊
Let's borrow it.

0:03:54.420,0:03:56.240
# 你看  這兄弟家的雞窩哦
Look! This is my buddy's chicken coop.

0:03:56.400,0:03:57.380
# 他都不養雞
But he doesn't have any chickens.

0:03:57.680,0:03:59.840
# 下次我買兩隻雞來  放在這裡
I'll buy two chickens next time, and bring them here.

0:04:03.560,0:04:04.760
# 嗯   這樣就可以啦
Um! It's alright now.

0:04:12.700,0:04:13.200
# 嘿
Hey!

0:04:13.680,0:04:14.320
# 下來
Get down!

0:04:20.680,0:04:21.740
# 剛剛好  這個
Perfect! And this one.

0:04:22.340,0:04:23.800
# 這個也可以砍掉它
This one can be chopped off too.

0:04:25.340,0:04:27.000
# 你看 這個很漂亮的哦
Look! It's so beautiful, isn't it?

0:04:27.960,0:04:28.480
# 這個
It's like...

0:04:29.240,0:04:31.740
# 你看  也很  很嫩  這個開了的很嫩
Look! It's re, really young, it's really young inside.

0:04:39.760,0:04:40.260
# 你看
Look!

0:04:41.620,0:04:44.340
# 這個就 還沒有怎麼開  比較嫩一點  這個
And this is, it has not really blossomed, and it's rather young.

0:04:44.460,0:04:47.400
# 這個就穩微老一點  它的很多的開花啦
This one is a bit old. There are already many flowers.

0:04:48.080,0:04:48.820
# 這個就沒有
But not this one.

0:04:50.080,0:04:50.600
# 你看
Look!

0:04:52.000,0:04:52.500
# 你看
Look!

0:04:52.780,0:04:55.520
# 那個粉  粉艷色  那個顏色那麼鮮艷
That's pink, shocking pink. The colour is so bright.

0:04:56.280,0:04:57.580
# 這個桃花很漂亮的哦
This peach flowers are really pretty.

0:04:58.420,0:04:59.220
# 我去看一下
Let me take a look.

0:04:59.820,0:05:01.320
# 你都沒見過這種桃花
I've never seen this kind of peach flowers before.

0:05:03.760,0:05:05.840
# 你看  這個是我前年放的香菇哦
Look! These are the shiitake mushrooms that I put two years ago.

0:05:06.300,0:05:08.480
# 現在有一點點  木頭都腐蝕掉啦
There's a tiny little bit of mushrooms. The wood is already rotten.

0:05:09.260,0:05:11.840
# 等下晚上我  過來把它摘啦  現在沒帶袋子
I'll come and pick them tonight. I don't have a bag with me now.

0:05:12.600,0:05:13.260
# 等一下來
I'll come again.

0:05:18.040,0:05:19.500
# 桃花朵朵開
Peach flowers are everywhere.

0:05:20.340,0:05:21.360
# 你看 這個桃花
Have a look at the peach flowers.

0:05:21.680,0:05:23.220
# 這裡長了兩棵桃花
Here are two peach flowers.

0:05:24.220,0:05:26.080
# 很漂亮的哦  這種桃花
The flowers are really pretty!

0:05:28.160,0:05:28.960
# 我記住它啦
I'll bear this in my mind.

0:05:28.960,0:05:30.840
# 下次我有桃子的時候  就直接來摘
Where there are peaches, I'll coming and pick them right away.

0:05:31.580,0:05:34.380
# 這個  不知道是不是誰家的  應該是野生的
This is, I wonder if if belongs to anyone. I think it's wild.

0:05:37.640,0:05:39.060
# 那個顏色那麼鮮艷
The colour is really bright.

0:05:39.180,0:05:41.100
# 普通的桃花好像沒那麼鮮艷  哦
It seems to be so much brighter than ordinary peach flowers, am I right?

0:05:41.320,0:05:42.380
# 桃子應該很好吃
The peaches must be very tasty.

0:05:42.660,0:05:43.960
# 這個  這種桃子
The, I mean this kind of peaches.

0:05:44.820,0:05:46.040
# 花都開得那麼漂亮
It has really pretty flowers.

0:05:46.300,0:05:47.600
# 桃子也應該也很靚
And so it must have really beautiful peaches.

0:05:48.060,0:05:48.860
# 肯定很好吃
Certainly, the taste must be wonderful too.

0:05:50.820,0:05:52.800
# 我還小的時候  我爺爺跟我說
When I was still a kid, my grandpa told me,

0:05:52.840,0:05:53.920
# 站在桃花樹上
that standing on a peach tree,

0:05:54.600,0:05:55.580
# 在桃花樹下
I mean under a peach tree,

0:05:55.860,0:05:56.900
# 搖一下這個桃花
then shake off the peach flowers,

0:05:57.240,0:05:58.360
# 拿去桃花運的哦
brings you "peach luck" (brings you a new lover).

0:06:00.380,0:06:01.380
# 哎喲  忘記啦
Ayo! I've forgotten,

0:06:01.480,0:06:02.900
# 我都是有婦之夫啦
that I'm already somebody's husband.

0:06:04.840,0:06:05.480
# 不好意思
I'm sorry,

0:06:05.580,0:06:06.400
# 把你搖啦
for having shaken you.

0:06:16.980,0:06:18.220
# 這樣 把這個切碎
So, I cut it into pieces.

0:06:24.580,0:06:25.960
# 像個魚蛋一樣  這個  (註︰他應該是指魚的卵)
It looks like fish eggs, isn't it?

0:06:30.120,0:06:31.340
# 先把這個過一下水
I'll boil it in water first,

0:06:31.360,0:06:33.200
# 用開水煮一下  然後再來炒
boil it in hot water first, and the fry it.

0:06:37.660,0:06:39.340
# 把這個水燒燙  把這個倒下去
I'll pour it into the water when the water starts boiling.

0:06:39.900,0:06:40.640
# 過一下水
then boil it for a while.

0:06:41.200,0:06:43.680
# 就等於說把它的那個澀味呀  把它去掉
It's like, to remove the astringent taste in the flowers.

0:06:44.520,0:06:45.380
# 有點澀澀的  (註︰不想太重覆"Astringent"這個字)
It might taste a bit funny otherwise.

0:06:52.440,0:06:53.340
# 火力不夠猛
The fire isn't strong enough.

0:06:54.800,0:06:55.640
# 稍等一下
A moment

0:06:56.500,0:06:58.440
# 這個水燙啦  把這個放下去
The water is boiling now. Let me put it in,

0:07:01.220,0:07:01.880
# 煮一下
and boil it for a while.

0:07:05.920,0:07:06.520
# 哇
Wa!

0:07:07.260,0:07:08.080
# 好香啊
It smells so good!

0:07:10.540,0:07:11.500
# 那種香味
The fragrance...

0:07:13.240,0:07:14.840
# 把這個  撈起來
Let me, scoop it out.

0:07:24.060,0:07:24.860
# 把這個洗一下
I wash it first.

0:07:42.500,0:07:43.420
# 多搞點油
Put some more oil.

0:07:59.600,0:08:00.880
# 把這豬肉放下去
I now put the pork into the wok.

0:08:15.020,0:08:15.780
# 再把這個
And then,

0:08:18.280,0:08:19.780
# 再把這個順便放下去
and then the flowers too.

0:08:25.960,0:08:26.960
# 啊  放點鹽
Ah! Put some salt,

0:08:29.040,0:08:29.720
# 多放點
more salt,

0:08:30.160,0:08:31.360
# 放香一點(註︰?????這是甚麼意思)
so that it smells better.

0:08:46.360,0:08:47.060
# 摘點水
Get some water.

0:08:52.820,0:08:53.560
# 加點水
Put some water.

0:09:01.900,0:09:03.260
# 搞幾個泡椒下去
Why don't we put some pickled peppers?

0:09:42.520,0:09:43.540
# 加點這個醬油
Put some soy sauce.

0:09:56.860,0:09:57.420
# 啊  好啦
Ah! Alright!

0:09:58.620,0:09:59.280
# 關火
Off the fire.

0:10:06.240,0:10:07.160
# 看下  這個
Have a look at this one.

0:10:07.460,0:10:08.520
# 可以喲  看上去
It's looks not bad.

0:10:12.680,0:10:13.240
# 嗯
Um!

0:10:13.520,0:10:14.020
# 可以
Not bad!

0:10:14.940,0:10:15.780
# 很不錯哦
It's really quite good.

0:10:17.700,0:10:18.380
# 有點那種
It has a sort of like,

0:10:19.480,0:10:20.420
# 那種澀澀的
like an astringent

0:10:21.840,0:10:22.660
# 澀澀的感覺
astringent taste,

0:10:24.100,0:10:24.620
# 還有
and a,

0:10:26.380,0:10:27.460
# 里面有蛋香味
a scent of eggs,

0:10:27.680,0:10:28.560
# 雞蛋的蛋
I mean chicken eggs.

0:10:33.540,0:10:34.300
# 很好吃
It's really tasty.

0:10:36.380,0:10:37.180
# 這個太老啦
It's too old.

0:10:37.400,0:10:37.900
# 如果
If,

0:10:38.240,0:10:38.840
# 再過
after,

0:10:40.180,0:10:41.420
# 提前  提前半個月
if we came two weeks, two weeks earlier

0:10:41.500,0:10:43.400
# 我把來摘來吃  就比較嫩一點
it would be younger and much more tender.

0:10:46.240,0:10:46.920
# 不過還不老
But it's still not really old.

0:10:47.420,0:10:48.520
# 還沒完全開花
It has not yet completely blossomed.

0:10:54.860,0:10:55.360
# 嗯
Um!

0:10:59.700,0:11:01.780
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.
