### ISSUE TITLE
【老饭骨】虾爆鳝 https://www.youtube.com/watch?v=Dal0VbnlPDM

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#743]
标题：【国宴大师•虾爆鳝】高营养低脂特色杭帮小糖醋口，鲜美又酸甜，增强免疫力就吃它，吃了还想吃！|老饭骨
简介：
小友们好，是不是很久没见我们哥仨一起给大家做菜啦，有没有想我们？
今天给大家带来一道特色杭帮菜：虾仁爆鳝片！这道菜以小糖醋口儿为特点，同时虾仁和鳝片的搭配增加了菜品的营养价值：
虾仁和鳝鱼脂肪含量低，且鳝鱼含有较为丰富的蛋白质、卵磷脂，维生素，以及的特种物质“鳝鱼素”，可提高免疫力，是一道补脑健体的菜。
三叔代大家问了个好几个问题：“为什么鳝鱼都不去血，带血吃呢？为什么存放鳝鱼不能用呢？为什么要先滑虾仁后放鳝鱼呢？“ 
嘿，咱大爷还说了，现在炒虾仁儿他都不过油，用水汆呢！这是为什么呀？
小友们要不也试一试？说不定效果也还不错？咱大爷的回答都在视频里呢！不要错过啊！
其实咱用心做菜，菜品的色、形、味都有讲究，有的小友之前问道：为什么老饭骨做菜程序总是那么复杂呢？
其实并不是，我们只是把我们过去多年的做菜经验通过视频传递给大家，虽然是家常菜，但每一道菜品我们都用心对待，将最美的呈现给大家。希望大家能从中学到一些小诀窍，提升下厨的幸福感。当然，一通百通也是我们一直呼吁的，大家不要忘记了哦！
字幕：
1
00:00:00,000 --> 00:00:02,480
烹汁

2
00:00:02,480 --> 00:00:04,360
汁红亮芡

3
00:00:04,840 --> 00:00:06,800
虾仁爆鳝片

4
00:00:06,800 --> 00:00:08,480
虾爆鳝

5
00:00:08,480 --> 00:00:10,880
刚才大爷讲了说

6
00:00:10,880 --> 00:00:13,480
这个菜淮扬菜也有 对老菜

7
00:00:13,480 --> 00:00:15,360
这个是杭帮菜

8
00:00:15,360 --> 00:00:17,560
杭州菜实际上也是

9
00:00:17,560 --> 00:00:19,400
过去淮扬菜的一列

10
00:00:19,400 --> 00:00:22,560
归属于淮扬菜“管辖”

11
00:00:22,560 --> 00:00:25,040
因为有大爷做淮扬菜

12
00:00:25,040 --> 00:00:26,320
我就让大爷看看

13
00:00:26,320 --> 00:00:29,040
三弟这个菜行不行 很行

14
00:00:29,040 --> 00:00:32,520
是炒是爆 爆

15
00:00:32,520 --> 00:00:35,040
咱们先调汁 一定要调汁

16
00:00:35,040 --> 00:00:39,800
一勺两勺 糖 放糖 两勺半

17
00:00:39,800 --> 00:00:43,200
小糖醋口 不是大糖醋口

18
00:00:43,200 --> 00:00:44,800
香醋 镇江香醋

19
00:00:44,800 --> 00:00:48,200
这颜色深没问题 颜色重

20
00:00:48,200 --> 00:00:53,800
搁点盐 盐是本 盐还不少呢

21
00:00:53,800 --> 00:00:54,640
（白）胡椒粉要大

22
00:00:54,640 --> 00:00:57,200
炒鳝鱼胡椒粉要大 必须得大

23
00:00:57,200 --> 00:00:59,280
大也不能说太大

24
00:00:59,280 --> 00:01:02,360
来点老抽 调调色

25
00:01:02,360 --> 00:01:04,680
颜色就起来了

26
00:01:04,680 --> 00:01:07,600
酱油

27
00:01:07,600 --> 00:01:08,160

28
00:01:08,160 --> 00:01:10,600
香油要不要 必须要

29
00:01:10,600 --> 00:01:12,640
这手还直哆嗦

30
00:01:12,640 --> 00:01:16,240
紧张了吧 这眼睛还看不见

31
00:01:16,240 --> 00:01:17,320
盖不上盖儿了还

32
00:01:17,320 --> 00:01:19,920
酒 酒最后 黄酒

33
00:01:23,440 --> 00:01:25,800
倒没了 该买了啊

34
00:01:25,800 --> 00:01:30,440
咱们是这样 来点水来点汤

35
00:01:30,440 --> 00:01:32,360
这粉子（淀粉）这是技巧

36
00:01:32,360 --> 00:01:36,240
少搁点粉子靠火收

37
00:01:36,240 --> 00:01:38,240
粉子大了赶紧出 对

38
00:01:39,280 --> 00:01:40,840
你说对了

39
00:01:42,080 --> 00:01:46,280
小汁儿兑好 这颜色是不浅点儿啊

40
00:01:46,280 --> 00:01:48,160
我认为稍微浅点

41
00:01:48,160 --> 00:01:50,280
再搁点老抽吧

42
00:01:50,280 --> 00:01:52,160
这回行了

43
00:01:54,040 --> 00:01:55,680
浆这个吧 很简单

44
00:01:55,680 --> 00:01:57,200
还是酒先

45
00:01:57,200 --> 00:02:01,520

46
00:02:01,520 --> 00:02:05,680
多了 葫芦 口小肚子大

47
00:02:05,680 --> 00:02:07,600
还得拿双筷子

48
00:02:07,600 --> 00:02:09,320
说一声我给你拿

49
00:02:09,320 --> 00:02:10,440
别介您闪着腰怎么办

50
00:02:10,440 --> 00:02:12,680
三叔你家这个（酒）没了

51
00:02:13,200 --> 00:02:15,720
三叔 我给你放油怎么样

52
00:02:16,840 --> 00:02:18,160
您先把火灭了吧

53
00:02:18,160 --> 00:02:21,160

54
00:02:21,160 --> 00:02:22,880
盐 底口

55
00:02:24,120 --> 00:02:26,960
您说现在为什么虾仁进不去水

56
00:02:26,960 --> 00:02:29,600
它本身就含水量就大 真大

57
00:02:29,600 --> 00:02:33,160
你看 越打越出

58
00:02:33,160 --> 00:02:35,080
没事就拿纸蘸一下

59
00:02:35,960 --> 00:02:40,400
蘸干水分 加粉子

60
00:02:40,400 --> 00:02:42,920
可以 加粉子

61
00:02:42,920 --> 00:02:44,880

62
00:02:44,880 --> 00:02:46,840
按正常的搁点蛋清咱不搁了

63
00:02:46,840 --> 00:02:50,720
搁不了 再搁就澥了

64
00:02:51,400 --> 00:02:56,720
咱们把鳝鱼加上盐 就是淀粉啊

65
00:02:56,720 --> 00:02:58,280
这鳝鱼都切好了

66
00:02:58,280 --> 00:03:00,560
切好了 趁您没在

67
00:03:00,560 --> 00:03:03,080
你知道他买回来就是斜刀片

68
00:03:03,080 --> 00:03:05,160
买的就是去骨的人都给切好了的

69
00:03:05,160 --> 00:03:07,000
现在超市真方便

70
00:03:07,000 --> 00:03:09,800
二伯你愿意干活 你搅匀了

71
00:03:09,800 --> 00:03:11,400
我先把这个料头切了

72
00:03:11,400 --> 00:03:14,520
咱这个是红椒青椒 就是配头

73
00:03:16,560 --> 00:03:18,320
大爷为什么鳝鱼都不去血

74
00:03:18,320 --> 00:03:19,560
都带着血吃

75
00:03:19,560 --> 00:03:22,120
鳝鱼的血是有营养的

76
00:03:22,120 --> 00:03:26,280
当然为什么要求我们在做鳝鱼的时候

77
00:03:26,280 --> 00:03:29,720
S鳝鱼不能用 存放的鳝鱼不能用

78
00:03:29,720 --> 00:03:31,360
血变质了

79
00:03:31,360 --> 00:03:35,240
头天的血是鲜红的 第二天血是黑色的

80
00:03:35,240 --> 00:03:37,280
所以那（第二天的）血就得把它洗了

81
00:03:37,280 --> 00:03:39,440
鳝鱼这血只要一变色

82
00:03:39,440 --> 00:03:43,440
它的鲜味就没了 而且还腥了

83
00:03:43,440 --> 00:03:44,880
而且也没有营养了

84
00:03:44,880 --> 00:03:47,040
因为它变质太快

85
00:03:47,040 --> 00:03:48,720
所以我们鳝鱼一定是

86
00:03:48,720 --> 00:03:51,160
当天买 当天吃 当天用

87
00:03:51,160 --> 00:03:55,560
S甲鱼 S鳝鱼 S螃蟹都不能吃

88
00:03:55,560 --> 00:03:58,000
咱们先把虾仁滑出来大爷

89
00:03:58,000 --> 00:04:01,400
为什么先滑虾仁

90
00:04:01,400 --> 00:04:05,200
虾仁干净 给染了 这个有序

91
00:04:05,200 --> 00:04:07,520

92
00:04:07,520 --> 00:04:10,640
火大一点 就这么大

93
00:04:10,640 --> 00:04:11,800
油温还是差点

94
00:04:11,800 --> 00:04:13,320
虾仁水分太大 太大了

95
00:04:13,320 --> 00:04:15,160
还不敢动 你想想

96
00:04:15,160 --> 00:04:16,720

97
00:04:16,720 --> 00:04:19,080
咱们这青红椒在油锅里一放

98
00:04:19,080 --> 00:04:21,000
这一着热就熟了

99
00:04:21,000 --> 00:04:22,160
你知道我现在炒虾仁

100
00:04:22,160 --> 00:04:23,040
在家里怎么炒么

101
00:04:23,040 --> 00:04:25,640
我都不过油了 直接用水滑

102
00:04:25,640 --> 00:04:26,680
大家感觉这虾仁

103
00:04:26,680 --> 00:04:29,680
吃起来这虾仁特别的脆

104
00:04:29,680 --> 00:04:31,880
实际上虾仁没那么脆

105
00:04:31,880 --> 00:04:33,320
含水量比较高

106
00:04:33,320 --> 00:04:37,000
上浆起来效果不会太好

107
00:04:37,000 --> 00:04:39,640
所以我就直接拿水就直接汆了

108
00:04:39,640 --> 00:04:41,800
效果还不错

109
00:04:41,800 --> 00:04:45,360
但是老觉得跟油滑的

110
00:04:45,360 --> 00:04:46,880
还是相对有点区别

111
00:04:46,880 --> 00:04:48,400
还是有点区别 差一点

112
00:04:48,400 --> 00:04:50,320
油滑的香

113
00:04:50,320 --> 00:04:52,080
好了这油温可以慢慢去炸

114
00:04:52,080 --> 00:04:56,600
这油温多少 五成了

115
00:04:56,600 --> 00:04:58,000

116
00:04:58,000 --> 00:05:00,040
这鳝鱼切的条啊 他切的大长条

117
00:05:00,040 --> 00:05:02,600
他那外边（买）进来的 他就没动

118
00:05:02,600 --> 00:05:07,360
我怕大爷还得（收拾）少下少下

119
00:05:07,360 --> 00:05:11,400
网友直接就买去了 还省事儿呢

120
00:05:11,400 --> 00:05:14,840
就炸这种颜色 因为它有血

121
00:05:14,840 --> 00:05:16,760
三叔是太聪明了

122
00:05:16,760 --> 00:05:18,240
还复油（炸）么 不用复油

123
00:05:18,240 --> 00:05:20,800
鳝鱼嫩 你一炸就小了

124
00:05:20,800 --> 00:05:23,280
把它的肉炸硬了 一次成活

125
00:05:23,280 --> 00:05:25,240
这鳝鱼不少

126
00:05:25,240 --> 00:05:27,640
现在已经就等于是出锅了这菜

127
00:05:27,640 --> 00:05:29,640

128
00:05:29,640 --> 00:05:31,240
留一点底油

129
00:05:31,240 --> 00:05:34,960
你看看亮子 把它倒回来了

130
00:05:34,960 --> 00:05:36,760
一烹汁 齐活

131
00:05:36,760 --> 00:05:38,760
瞧这碗儿好使

132
00:05:38,760 --> 00:05:41,760
开火 看见没有 烹汁儿

133
00:05:41,760 --> 00:05:42,960

134
00:05:46,480 --> 00:05:48,840
明汁亮芡 把盘拿过来

135
00:05:48,840 --> 00:05:51,200
这盘儿小点儿 小点儿就是它了

136
00:05:52,120 --> 00:05:53,600
给点明油

137
00:05:53,600 --> 00:05:57,560

138
00:05:57,560 --> 00:05:59,200
汁红亮芡

139
00:05:59,200 --> 00:06:01,800

140
00:06:01,800 --> 00:06:06,120
星星点点 好漂亮

141
00:06:06,120 --> 00:06:08,400
真蹿啊 漂亮漂亮

142
00:06:09,560 --> 00:06:12,440
大爷这是最后的一道 最经典的

143
00:06:12,440 --> 00:06:14,440
这是我最关键的一点

144
00:06:14,440 --> 00:06:17,200
（白）胡椒粉 最后撒胡椒粉

145
00:06:17,200 --> 00:06:20,280
炒的里边还有 里外两次

146
00:06:20,280 --> 00:06:22,520
所以胡椒粉用的量非常大

147
00:06:22,520 --> 00:06:25,240
大爷你自己尝吧 来了

148
00:06:25,240 --> 00:06:26,120
我就不

149
00:06:26,120 --> 00:06:27,480

150
00:06:27,600 --> 00:06:28,760
快接着亮子

151
00:06:29,800 --> 00:06:31,680
你看像不像红烧海参那样子

152
00:06:31,680 --> 00:06:32,560
香

153
00:06:32,560 --> 00:06:34,720
怎么样这菜做的 确实够意思吧

154
00:06:34,720 --> 00:06:37,360

155
00:06:37,360 --> 00:06:38,200
三叔聪明

156
00:06:38,960 --> 00:06:43,200
过去鳝鱼它是上浆滑油

157
00:06:43,200 --> 00:06:45,600
他改成了一个炸的方法

158
00:06:46,560 --> 00:06:49,160
炸的方法呢鳝鱼更加滑嫩

159
00:06:49,160 --> 00:06:52,440
而且它就特别丰满

160
00:06:52,440 --> 00:06:53,880
有一个保护层

161
00:06:53,880 --> 00:06:55,320
就跟穿着衣服似的

162
00:06:55,320 --> 00:07:00,520
另外挂汁着味 覆味覆的好

163
00:07:00,520 --> 00:07:03,800
再加上他拿汁拿芡拿的挺准

164
00:07:03,800 --> 00:07:06,680
所以你看特别亮

165
00:07:06,680 --> 00:07:10,560
出锅的时候再点点香油 更显着亮

166
00:07:10,560 --> 00:07:14,400
胡椒粉再多点 更好吃

167
00:07:14,400 --> 00:07:15,160

168
00:07:15,160 --> 00:07:20,600
所以按照中国的英语的话说

169
00:07:20,600 --> 00:07:22,440
非常好

170
00:07:22,440 --> 00:07:23,520
再来一块

171
00:07:23,520 --> 00:07:26,160

172
00:07:26,160 --> 00:07:26,200

173
00:07:26,200 --> 00:07:28,160
谢谢小亮默默的付出

174
00:07:28,160 --> 00:07:30,200
谢谢三叔辛苦了

175
00:07:30,200 --> 00:07:32,560
谢谢大爷精彩的点评

176
00:07:32,560 --> 00:07:33,320
然后呢

177
00:07:33,320 --> 00:07:35,680

178
00:07:35,680 --> 00:07:39,320
大爷 三叔 小亮子

179
00:07:39,320 --> 00:07:41,040
对不起了我先拿走了

180
00:07:41,040 --> 00:07:41,960

“我是大爷” 00:07:52,19

**Comment by Bella-812** [comment]
认领

**Comment by immoonancient** [comment]
bot, please upload on behalf of the assignee
 
1
00:00:00,000 --> 00:00:02,480
烹汁
Cooking the sauce 
2
00:00:02,480 --> 00:00:04,360
汁红亮芡
Shiny and brownish
3
00:00:04,840 --> 00:00:06,800
虾仁爆鳝片
The Asian swamp eel flakes fried with prawns 
 
4
00:00:06,800 --> 00:00:08,480
虾爆鳝
The Asian swamp eel flakes fried with prawns
5
00:00:08,480 --> 00:00:10,880
刚才大爷讲了说
Grandpa was just saying 
6
00:00:10,880 --> 00:00:13,480
这个菜淮扬菜也有 对老菜
‘This dish belongs to Huaiyang Cuisine as well’. ‘Yes, really traditional.’
7
00:00:13,480 --> 00:00:15,360
这个是杭帮菜
This is originally belonging to Hangzhou Cuisine.  
8
00:00:15,360 --> 00:00:17,560
杭州菜实际上也是
Well ‘Hangzhou Cuisine’ was actually
9
00:00:17,560 --> 00:00:19,400
过去淮扬菜的一列
Part of ‘Huaiyang cuisine’.
10
00:00:19,400 --> 00:00:22,560
归属于淮扬菜“管辖”
One type of ‘Huaiyang Cuisine’. 
11
00:00:22,560 --> 00:00:25,040
因为有大爷做淮扬菜
Since Grandpa is the master of ‘Huaiyang cuisine’ 
12
00:00:25,040 --> 00:00:26,320
我就让大爷看看
I’ll show what I can do 
13
00:00:26,320 --> 00:00:29,040
三弟这个菜行不行 很行
To prove myself. ‘Very well’. 
14
00:00:29,040 --> 00:00:32,520
是炒是爆 爆
‘fried or deep fried?’ ‘Deep fried.’
15
00:00:32,520 --> 00:00:35,040
咱们先调汁 一定要调汁
First we have to make the sauce. It is necessary. 
16
00:00:35,040 --> 00:00:39,800
一勺两勺 糖 放糖 两勺半
One or two spoons of sugar, about two and half.  
17
00:00:39,800 --> 00:00:43,200
小糖醋口 不是大糖醋口
‘You going to make it taste sour and sweet?’ ‘Definitely’
18
00:00:43,200 --> 00:00:44,800
香醋 镇江香醋
Zhenjiang Vinegar. 
19
00:00:44,800 --> 00:00:48,200
这颜色深没问题 颜色重
It’s OK if the color looks a bit dark. It should be dark. 
20
00:00:48,200 --> 00:00:53,800
搁点盐 盐是本 盐还不少呢
‘Add some salt. The salt is the based flavor.’ ‘Quite a lot.’
21
00:00:53,800 --> 00:00:54,640
（白）胡椒粉要大
‘Also needs a lot of white pepper’ 
22
00:00:54,640 --> 00:00:57,200
炒鳝鱼胡椒粉要大 必须得大
‘You need to make the flavor of pepper quite heavy if you are cooking this dish.’ ‘It has to be.’
 
23
00:00:57,200 --> 00:00:59,280
大也不能说太大
‘But not too heavy.’
24
00:00:59,280 --> 00:01:02,360
来点老抽 调调色
‘Dark soy sauce helps to tone the color’. 
25
00:01:02,360 --> 00:01:04,680
颜色就起来了
Now the color looks good.
26
00:01:04,680 --> 00:01:07,600
酱油
Light Soy sauce.
27
00:01:07,600 --> 00:01:08,160
28
00:01:08,160 --> 00:01:10,600
香油要不要 必须要
‘Do we need sesame oil’ ‘Absolutely.’
29
00:01:10,600 --> 00:01:12,640
这手还直哆嗦
why your hands are shaking
30
00:01:12,640 --> 00:01:16,240
紧张了吧 这眼睛还看不见
‘I’m too nervous. My eyes can barely see.’ 
31
00:01:16,240 --> 00:01:17,320
盖不上盖儿了还
Can’t even close this thing.
32
00:01:17,320 --> 00:01:19,920
酒 酒最后 黄酒
‘At the end, rice wine.’
33
00:01:23,440 --> 00:01:25,800
倒没了 该买了啊
‘No left. Should buy some more’ 
34
00:01:25,800 --> 00:01:30,440
咱们是这样 来点水来点汤
‘All right then, add some water’ 
35
00:01:30,440 --> 00:01:32,360
这粉子（淀粉）这是技巧
‘Now this is an important thing’
36
00:01:32,360 --> 00:01:36,240
少搁点粉子靠火收
‘Don’t put too much starch in it.’ 
37
00:01:36,240 --> 00:01:38,240
粉子大了赶紧出 对
‘let the sauce reduced by the natural heat.’
38
00:01:39,280 --> 00:01:40,840
你说对了
‘you are right’ 
39
00:01:42,080 --> 00:01:46,280
小汁儿兑好 这颜色是不浅点儿啊
‘Is this color too light’ 
40
00:01:46,280 --> 00:01:48,160
我认为稍微浅点
‘I think so.’
41
00:01:48,160 --> 00:01:50,280
再搁点老抽吧
‘let’s put some more dark soy sauce.’ 
42
00:01:50,280 --> 00:01:52,160
这回行了
‘Now it’s good.’
43
00:01:54,040 --> 00:01:55,680
浆这个吧 很简单
‘Let’s marinate the prawns’
44
00:01:55,680 --> 00:01:57,200
还是酒先
‘still you need the wine first’
45
00:01:57,200 --> 00:02:01,520
46
00:02:01,520 --> 00:02:05,680
多了 葫芦 口小肚子大
A little bit too much. The bottle has large body. 
47
00:02:05,680 --> 00:02:07,600
还得拿双筷子
And the chopsticks. 
48
00:02:07,600 --> 00:02:09,320
说一声我给你拿
Just tell me to get them for you
49
00:02:09,320 --> 00:02:10,440
别介您闪着腰怎么办
Don’t bother, I’m worried about your back.
50
00:02:10,440 --> 00:02:12,680
三叔你家这个（酒）没了
Brother third, you are running off the wine.
51
00:02:13,200 --> 00:02:15,720
三叔 我给你放油怎么样
Shall I pour the oil for you?
 
52
00:02:16,840 --> 00:02:18,160
您先把火灭了吧
Just turn off the fire first. 
 
53
00:02:18,160 --> 00:02:21,160
54
00:02:21,160 --> 00:02:22,880
盐 底口
Salt, the based flavor.
55
00:02:24,120 --> 00:02:26,960
您说现在为什么虾仁进不去水
Why the prawns today cannot absorb the water
56
00:02:26,960 --> 00:02:29,600
它本身就含水量就大 真大
It contains lots of water though. 
57
00:02:29,600 --> 00:02:33,160
你看 越打越出
Exactly. You stir heavier, the water comes out more
58
00:02:33,160 --> 00:02:35,080
没事就拿纸蘸一下
Take piece of tissue to wipe it.
59
00:02:35,960 --> 00:02:40,400
蘸干水分 加粉子
Dry the water, add the starch. 
60
00:02:40,400 --> 00:02:42,920
可以 加粉子
Yeah, continue to add the starch. 
61
00:02:42,920 --> 00:02:44,880
62
00:02:44,880 --> 00:02:46,840
按正常的搁点蛋清咱不搁了
Normally we should add some egg white as well, but we won’t do it today.
63
00:02:46,840 --> 00:02:50,720
搁不了 再搁就澥了
Right, otherwise the prawns will not be chewy. 
64
00:02:51,400 --> 00:02:56,720
咱们把鳝鱼加上盐 就是淀粉啊
Let’s put some starch in the swamp eel. 
65
00:02:56,720 --> 00:02:58,280
这鳝鱼都切好了
Wow, the eel has already been sliced.
66
00:02:58,280 --> 00:03:00,560
切好了 趁您没在
Yeah, it been done while you were not here. 
67
00:03:00,560 --> 00:03:03,080
你知道他买回来就是斜刀片
He bought it as slant-cut. 
68
00:03:03,080 --> 00:03:05,160
买的就是去骨的人都给切好了的
It is boneless when you buy it. 
69
00:03:05,160 --> 00:03:07,000
现在超市真方便
The market now is super convenience. 
70
00:03:07,000 --> 00:03:09,800
二伯你愿意干活 你搅匀了
Would you like to stir it for me please?
 
71
00:03:09,800 --> 00:03:11,400
我先把这个料头切了
I’ll cut these first.
72
00:03:11,400 --> 00:03:14,520
咱这个是红椒青椒 就是配头
These are red pepper and green pepper, as the sides. 
73
00:03:16,560 --> 00:03:18,320
大爷为什么鳝鱼都不去血
Why you don’t rinse the blood from the swamp eel? 
74
00:03:18,320 --> 00:03:19,560
都带着血吃
Cooked with the blood.
75
00:03:19,560 --> 00:03:22,120
鳝鱼的血是有营养的
The blood of the fish is full of the nutrients. 
76
00:03:22,120 --> 00:03:26,280
当然为什么要求我们在做鳝鱼的时候
However you definitely cannot use 
77
00:03:26,280 --> 00:03:29,720
S鳝鱼不能用 存放的鳝鱼不能用
The dead eel and those have been stored for long time. 
78
00:03:29,720 --> 00:03:31,360
血变质了
The blood has deteriorated. 
79
00:03:31,360 --> 00:03:35,240
头天的血是鲜红的 第二天血是黑色的
First day you see the red blood, then it turns into black on the next day. 
80
00:03:35,240 --> 00:03:37,280
所以那（第二天的）血就得把它洗了
That’s why you need to clean the blood (if its from the second day)
81
00:03:37,280 --> 00:03:39,440
鳝鱼这血只要一变色
As long as the blood’s color changed
82
00:03:39,440 --> 00:03:43,440
它的鲜味就没了 而且还腥了
It will lose its’ umami taste and taste badly.
 
83
00:03:43,440 --> 00:03:44,880
而且也没有营养了
By the way there won’t be any nutrition contained neither.
84
00:03:44,880 --> 00:03:47,040
因为它变质太快
Because the Asian swamp eel is too easy to get deteriorated.
85
00:03:47,040 --> 00:03:48,720
所以我们鳝鱼一定是
Therefore we need to make sure that the eel fish 
86
00:03:48,720 --> 00:03:51,160
当天买 当天吃 当天用
Is bought by today, used and ate by today. 
87
00:03:51,160 --> 00:03:55,560
S甲鱼 S鳝鱼 S螃蟹都不能吃
Such as dead soft- shelled turtles, dead swamp eel, dead crabs are all not able to cooked. 
88
00:03:55,560 --> 00:03:58,000
咱们先把虾仁滑出来大爷
Okay let’s put the prawns first
89
00:03:58,000 --> 00:04:01,400
为什么先滑虾仁
Why we put the prawns first?
90
00:04:01,400 --> 00:04:05,200
虾仁干净 给染了 这个有序
Otherwise the color will be mixed.
91
00:04:05,200 --> 00:04:07,520
92
00:04:07,520 --> 00:04:10,640
火大一点 就这么大
Turn the heat higher
93
00:04:10,640 --> 00:04:11,800
油温还是差点
The temperature of the oil still needs some time
94
00:04:11,800 --> 00:04:13,320
虾仁水分太大 太大了
The prawn contained so much water.
95
00:04:13,320 --> 00:04:15,160
还不敢动 你想想
Don’t move yet. 
96
00:04:15,160 --> 00:04:16,720
97
00:04:16,720 --> 00:04:19,080
咱们这青红椒在油锅里一放
Then the peppers.
98
00:04:19,080 --> 00:04:21,000
这一着热就熟了
They get cooked immediately. 
99
00:04:21,000 --> 00:04:22,160
你知道我现在炒虾仁
You know what I do with the prawns 
100
00:04:22,160 --> 00:04:23,040
在家里怎么炒么
At home?
101
00:04:23,040 --> 00:04:25,640
我都不过油了 直接用水滑
I don’t even use the oil, I only use water.
102
00:04:25,640 --> 00:04:26,680
大家感觉这虾仁
People might feel that the prawns are really crispy 
103
00:04:26,680 --> 00:04:29,680
吃起来这虾仁特别的脆
When you bite it.
104
00:04:29,680 --> 00:04:31,880
实际上虾仁没那么脆
Actually it’s not like that. 
105
00:04:31,880 --> 00:04:33,320
含水量比较高
They are full of water
106
00:04:33,320 --> 00:04:37,000
上浆起来效果不会太好
So, the prawns are not easy to thicken the sauce. 
107
00:04:37,000 --> 00:04:39,640
所以我就直接拿水就直接汆了
That’s why I only use the water to boil them.
108
00:04:39,640 --> 00:04:41,800
效果还不错
It works though. 
109
00:04:41,800 --> 00:04:45,360
但是老觉得跟油滑的
But still a bit different from the oil way 
110
00:04:45,360 --> 00:04:46,880
还是相对有点区别
111
00:04:46,880 --> 00:04:48,400
还是有点区别 差一点
Still a bit difference
112
00:04:48,400 --> 00:04:50,320
油滑的香
The oil provides aroma.
113
00:04:50,320 --> 00:04:52,080
好了这油温可以慢慢去炸
Right now the temperature is enough for the deep fried.
114
00:04:52,080 --> 00:04:56,600
这油温多少 五成了
What’s the temperature now? About half boiled. 
115
00:04:56,600 --> 00:04:58,000
116
00:04:58,000 --> 00:05:00,040
这鳝鱼切的条啊 他切的大长条
The eel sliced into slices, they make the slices really big.
117
00:05:00,040 --> 00:05:02,600
他那外边（买）进来的 他就没动
He bought directly from the market
118
00:05:02,600 --> 00:05:07,360
我怕大爷还得（收拾）少下少下
Saving Grandpa’s time 
119
00:05:07,360 --> 00:05:11,400
网友直接就买去了 还省事儿呢
Yeah people now usually do the same way.
120
00:05:11,400 --> 00:05:14,840
就炸这种颜色 因为它有血
This how the color looks like, because it has blood in it.
121
00:05:14,840 --> 00:05:16,760
三叔是太聪明了
Brother third is really smart
122
00:05:16,760 --> 00:05:18,240
还复油（炸）么 不用复油
Do you need to put them back to the oil? No needs.
123
00:05:18,240 --> 00:05:20,800
鳝鱼嫩 你一炸就小了
The fish cannot be overcooked, it will turn smaller.
 
124
00:05:20,800 --> 00:05:23,280
把它的肉炸硬了 一次成活
Deep fried the fish only once.
 
125
00:05:23,280 --> 00:05:25,240
这鳝鱼不少
There is quite a lot 
126
00:05:25,240 --> 00:05:27,640
现在已经就等于是出锅了这菜
Now the dish is already finished
127
00:05:27,640 --> 00:05:29,640
128
00:05:29,640 --> 00:05:31,240
留一点底油
Left some oil 
129
00:05:31,240 --> 00:05:34,960
你看看亮子 把它倒回来了
Look, now we put it back
130
00:05:34,960 --> 00:05:36,760
一烹汁 齐活
Finished with the sauce
131
00:05:36,760 --> 00:05:38,760
瞧这碗儿好使
check this bowl
132
00:05:38,760 --> 00:05:41,760
开火 看见没有 烹汁儿
Turn the heat on, making the sauce now 
133
00:05:41,760 --> 00:05:42,960
134
00:05:46,480 --> 00:05:48,840
明汁亮芡 把盘拿过来
The sauce is so shiny and brownish, pass me the plate please
135
00:05:48,840 --> 00:05:51,200
这盘儿小点儿 小点儿就是它了
‘Is this plate too small’  ‘No problem’ 
136
00:05:52,120 --> 00:05:53,600
给点明油
And some oil
137
00:05:53,600 --> 00:05:57,560
138
00:05:57,560 --> 00:05:59,200
汁红亮芡
Check this color
139
00:05:59,200 --> 00:06:01,800
140
00:06:01,800 --> 00:06:06,120
星星点点 好漂亮
How beautiful 
141
00:06:06,120 --> 00:06:08,400
真蹿啊 漂亮漂亮
The dish is 
142
00:06:09,560 --> 00:06:12,440
大爷这是最后的一道 最经典的
And now the very last step
143
00:06:12,440 --> 00:06:14,440
这是我最关键的一点
The most important thing is 
144
00:06:14,440 --> 00:06:17,200
（白）胡椒粉 最后撒胡椒粉
White pepper. Drop the white pepper
145
00:06:17,200 --> 00:06:20,280
炒的里边还有 里外两次
Remember to put the pepper twice 
146
00:06:20,280 --> 00:06:22,520
所以胡椒粉用的量非常大
The pepper would been used a lot 
147
00:06:22,520 --> 00:06:25,240
大爷你自己尝吧 来了
Grandpa come to taste it. Coming
148
00:06:25,240 --> 00:06:26,120
我就不
149
00:06:26,120 --> 00:06:27,480
150
00:06:27,600 --> 00:06:28,760
快接着亮子
Come on, liangzi
151
00:06:29,800 --> 00:06:31,680
你看像不像红烧海参那样子
You see isn’t this look like the braised sea cucumber
152
00:06:31,680 --> 00:06:32,560
香
Smells so good
 
153
00:06:32,560 --> 00:06:34,720
怎么样这菜做的 确实够意思吧
How’s my dish? Good ?
154
00:06:34,720 --> 00:06:37,360
155
00:06:37,360 --> 00:06:38,200
三叔聪明
Brother third is really smart indeed.
156
00:06:38,960 --> 00:06:43,200
过去鳝鱼它是上浆滑油
In the past days we used the fried way.
157
00:06:43,200 --> 00:06:45,600
他改成了一个炸的方法
But he changed it to the deep-fried way.
158
00:06:46,560 --> 00:06:49,160
炸的方法呢鳝鱼更加滑嫩
This method makes the swamp eel taste more smoothly
159
00:06:49,160 --> 00:06:52,440
而且它就特别丰满
And chewy as well
 
160
00:06:52,440 --> 00:06:53,880
有一个保护层
It therefore has a protected layer. 
161
00:06:53,880 --> 00:06:55,320
就跟穿着衣服似的
Just like with ‘clothes’
162
00:06:55,320 --> 00:07:00,520
另外挂汁着味 覆味覆的好
Plus the sauce taste so yummy
163
00:07:00,520 --> 00:07:03,800
再加上他拿汁拿芡拿的挺准
He controlled the fire to make the starch thicken perfectly. 
164
00:07:03,800 --> 00:07:06,680
所以你看特别亮
That’s why the color so bright
165
00:07:06,680 --> 00:07:10,560
出锅的时候再点点香油 更显着亮
It’ll looks brighter if you add some sesame oil when you take it to the table
166
00:07:10,560 --> 00:07:14,400
胡椒粉再多点 更好吃
And more pepper
167
00:07:14,400 --> 00:07:15,160
168
00:07:15,160 --> 00:07:20,600
所以按照中国的英语的话说
So in the Chinese way to speak English
169
00:07:20,600 --> 00:07:22,440
非常好
Very good
170
00:07:22,440 --> 00:07:23,520
再来一块
One more please
171
00:07:23,520 --> 00:07:26,160
172
00:07:26,160 --> 00:07:26,200
173
00:07:26,200 --> 00:07:28,160
谢谢小亮默默的付出
Thanks for Liang’s helping
174
00:07:28,160 --> 00:07:30,200
谢谢三叔辛苦了
Thank you Brother third.
175
00:07:30,200 --> 00:07:32,560
谢谢大爷精彩的点评
Thanks for Grandpa’s comments. 
176
00:07:32,560 --> 00:07:33,320
然后呢
And what else?
177
00:07:33,320 --> 00:07:35,680
178
00:07:35,680 --> 00:07:39,320
大爷 三叔 小亮子
Grandpa, Brother Third, Liangzi
179
00:07:39,320 --> 00:07:41,040
对不起了我先拿走了
Sorry I’ll just take them all 
180
00:07:41,040 --> 00:07:41,960
“我是大爷” 00:07:52,19
I’m the grandpa
