### ISSUE TITLE
[老饭骨] 开水白菜 - https://www.youtube.com/watch?v=Pn0PyUe5tx8

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#745]
老饭骨频道最热门视频，考虑补档

标题
```
【国宴大师•开水白菜】顶级川菜，国宴一绝，形如开水，回味无穷的清口菜，特级厨师教你家庭版做法！|老饭骨
```

描述
```
小友们好，今天分享一道中华名菜 -- 开水白菜，
它曾是宫廷御膳，又被川菜大师罗国荣发扬光大，让各国领导人赞不绝口。
这道菜看似简单，实则工序极为讲究。
似开水的高汤为这道菜的点睛之笔，
咱大爷今天毫无保留地分享了制汤的步骤和小秘诀，
虽然是家庭版，但绝不含糊，望各位小友喜欢！
```

字幕
频道官方表示原始字幕文件已丢失，需要我们自己手打中文字幕+时间轴

**Comment by immoonancient** [comment]
@shuaisoserious 过来抄中文

**Comment by lhrotk** [comment]
认领

**Comment by lhrotk** [comment]
0:00:00.040,0:00:02.810
The next program is Steamed Chinese Cabbage in Supreme Soup (aka 'boiled chinese cabbage ')

0:00:02.820,0:00:03.670
For the first part of making boiled chinese cabbage

0:00:03.680,0:00:04.940
You need to hang soup

0:00:04.950,0:00:07.650
It's soup again

0:00:07.760,0:00:10.740
Take away this chicken claw first in the process of making soup

0:00:10.750,0:00:11.940
we won't use it

0:00:11.940,0:00:13.180
chicken butt neither

0:00:13.190,0:00:14.760
I've cut off the chicken head，it has odor

0:00:14.770,0:00:16.720
Because we are using smaller pots at home

0:00:16.730,0:00:18.200
let's cut it into pieces

0:00:18.400,0:00:19.820
Repeat this time

0:00:19.830,0:00:22.050
Hanging soup is prepared for dishes

0:00:22.210,0:00:23.790
Stewed soup is for drinking

0:00:23.800,0:00:26.470
Bring out chicken breast

0:00:26.480,0:00:28.070
We'll make clear soup later

0:00:28.080,0:00:29.570
So we need this chicken breast

0:00:31.190,0:00:33.500
It's easy to chop a chicken

0:00:33.900,0:00:36.220
Put the chicken wings into the pot

0:00:36.230,0:00:39.330
Take the chicken breast and cut it

0:00:39.520,0:00:40.240
into chunks.

0:00:40.600,0:00:43.350
smaller chunks are easier to cook

0:00:43.360,0:00:45.290
and will save time of making soup

0:00:45.300,0:00:48.770
The old boys are so cool

0:00:50.080,0:00:50.860
Very good

0:00:50.860,0:00:51.630
Very good

0:00:51.630,0:00:53.840
Pay attention, we need to discard this part

0:00:53.860,0:00:56.420
We call it tip in chicken

0:00:56.430,0:00:57.770
since it is smelly

0:00:57.780,0:00:58.670
and is unhealthy

0:00:58.680,0:00:59.360
Yes

0:00:59.370,0:01:00.540
Ignition

0:01:00.540,0:01:02.740
Cold water in pot as we start

0:01:02.740,0:01:05.520
The reason of putting chicken in soup is for freshness

0:01:05.520,0:01:07.100
The reason of using elbows or some lean meat

0:01:07.160,0:01:08.540
is to make it smells good .

0:01:09.720,0:01:12.260
Bones is good for making soup

0:01:12.600,0:01:13.690
It contains calcium

0:01:13.700,0:01:16.180
And it also makes the soup fragrant

0:01:16.660,0:01:19.000
Take advandage of the smell of bone

0:01:19.010,0:01:21.850
The smell of meat and bones and the flavor of chicken

0:01:21.860,0:01:22.400
Is it right? my brother

0:01:22.940,0:01:27.980
Since we are making a clear soup later

0:01:27.990,0:01:29.090
Smash the chicken breast to make 'saozi'

0:01:29.450,0:01:30.020
Processing cabbage is simple

0:01:30.030,0:01:32.340
But making soup is so complicated

0:01:32.350,0:01:35.530
Boiled cabbage is a famous dish in Sichuan

0:01:36.180,0:01:37.720
The chef who invented this dish

0:01:38.290,0:01:40.650
is Luo Guorong from Beijing Hotel

0:01:41.040,0:01:42.070
Sichuan cuisine master

0:01:42.690,0:01:45.130
That day, the guest wanted to eat chinese cabbage

0:01:45.140,0:01:46.470
want less oil

0:01:46.740,0:01:47.690
but remains delicious

0:01:48.240,0:01:49.650
When they served this boiled cabbage

0:01:49.660,0:01:51.170
The guest thought it was really cabbage in boiling water

0:01:51.180,0:01:54.090
But was shocked when he taste it

0:01:54.850,0:01:55.600
True fragrance

0:01:56.000,0:01:57.290
Looks like boiling water

0:01:57.290,0:01:58.850
Cabbage is super soft

0:01:58.860,0:02:02.760
So it became a famous Sichuan dish

0:02:02.770,0:02:04.900
Minced Chicken ('saozi') is done

0:02:04.950,0:02:06.210
How we are going to use this

0:02:06.220,0:02:09.190
We use it to clean the meat soup

0:02:09.200,0:02:10.460
Don't need to be too fine-grained

0:02:10.470,0:02:11.790
Let it be connected

0:02:11.800,0:02:13.670
When clean up the soup later

0:02:13.740,0:02:16.340
It will absort all residue in the soup

0:02:16.350,0:02:19.970
Now we put two pieces of ginger

0:02:20.030,0:02:21.250
Two more slices of green onion later

0:02:21.420,0:02:22.040
That's all.

0:02:22.490,0:02:23.150
Do you see

0:02:23.160,0:02:24.410
That is why start boiling with cold water

0:02:24.420,0:02:27.380
This slowly extract the dirt from the inside

0:02:27.390,0:02:27.770
now the foam comes out

0:02:27.780,0:02:29.490
let's clean it

0:02:31.360,0:02:32.950
all should be skimmed.

0:02:37.800,0:02:39.720
Look at the foam

0:02:39.720,0:02:41.840
Sometimes it's hard to skim

0:02:42.180,0:02:43.180
just add some cold water

0:02:43.660,0:02:44.600
To 'smash' it.

0:02:44.960,0:02:46.630
'Smash'

0:02:46.640,0:02:47.240
You see

0:02:47.500,0:02:50.910
The foam sink after I smash it

0:02:51.660,0:02:52.130
And then continue skim the foam

0:02:53.490,0:02:56.330
The foam is released more fully

0:02:56.330,0:02:59.330
'Smashing' is for skimming

0:03:00.140,0:03:02.950
I've been on so many TV shows

0:03:02.960,0:03:04.930
I've seen countless TV shows, too

0:03:05.500,0:03:08.400
None of them are as hardcore as this

0:03:08.510,0:03:10.440
Chef Zheng is selfless and patient

0:03:10.440,0:03:13.530
Teach clearing soup twice today

0:03:14.030,0:03:17.330
Let's move the soup to another pot

0:03:18.820,0:03:20.080
We will insist on

0:03:20.090,0:03:21.480
What I said last time

0:03:21.490,0:03:24.140
use high pressure to reduce purine in soup

0:03:24.150,0:03:25.460
retrieve the meat from the soup

0:03:25.530,0:03:26.460
Put it here

0:03:30.890,0:03:32.100
The bone needs more time

0:03:32.200,0:03:33.150
My pot is a little bit small

0:03:33.150,0:03:34.910
Need to boil each side

0:03:35.210,0:03:37.120
Home edition also need carefulness

0:03:37.130,0:03:40.390
The process is the same as that in hotel

0:03:40.510,0:03:41.350
Sometimes it is necessary

0:03:41.360,0:03:42.550
to wash it

0:03:42.560,0:03:43.530
Er Bai please clean off the foam

0:03:44.640,0:03:45.860
now it is very clean

0:03:47.870,0:03:51.590
The water of the pork is clean

0:03:52.240,0:03:54.820
Put the original soup in this pot

0:03:54.830,0:03:55.080
You see

0:03:56.190,0:03:56.740
Help me handle the pot

0:03:56.750,0:03:58.090
Add more water

0:03:58.100,0:03:59.350
to cover the meat

0:03:59.360,0:04:02.380
How long does the pressure cooker takes

0:04:02.890,0:04:05.200
Need four hours for ordinary pot

0:04:05.200,0:04:07.440
Using pressure cooker takes basically 25 minutes to half an hour

0:04:07.450,0:04:07.960
Is that so?

0:04:07.970,0:04:10.140
It takes more than an hour including deflating

0:04:10.760,0:04:12.640
See the soup, now is thoroughly clean

0:04:13.190,0:04:16.440
Now we're going to cook with high pressure

0:04:16.670,0:04:19.290
This foam is very clean

0:04:19.290,0:04:21.070
Very good.

0:04:21.070,0:04:24.320
put it back to the container

0:04:24.330,0:04:24.720
good

0:04:25.300,0:04:25.900
Stew soup mode

0:04:26.440,0:04:28.770
25Minutes to go

0:04:28.770,0:04:33.810
'boiled cabbage' (in Sichuan accent)

0:04:35.490,0:04:38.680
We should use seasoned chinese cabbage

0:04:40.030,0:04:42.750
Best chinese cabbage is produced in Taian, Shandong

0:04:42.760,0:04:45.080
Taian has three beauties

0:04:45.090,0:04:46.320
Chinese cabbage

0:04:46.330,0:04:47.080
Tofu and spring water

0:04:47.250,0:04:49.810
That cabbage is called Huang Ya Bai

0:04:50.010,0:04:50.870
or Huang Ya Cai

0:04:50.880,0:04:53.460
It tastes amazing

0:04:53.460,0:04:57.180
This dish will be more beautiful with Huang Ya Bai

0:04:57.460,0:04:58.250
Golden yellow

0:04:58.260,0:04:58.850
Golden yellow

0:04:59.330,0:05:01.080
But we use baby cabbage today

0:05:01.090,0:05:03.630
Baby cabbage need more blanching

0:05:04.270,0:05:06.650
to remove the bitter taste of it

0:05:06.660,0:05:08.210
Do you need some salt

0:05:08.220,0:05:08.790
No

0:05:09.170,0:05:10.150
While it is boiling here

0:05:10.160,0:05:11.140
Let's check the chicken soup

0:05:11.150,0:05:13.000
Hanging soup with pressure cooker

0:05:13.010,0:05:14.380
Come on

0:05:15.430,0:05:15.930
Yes

0:05:15.930,0:05:17.870
Pot filled with clear soup

0:05:17.870,0:05:19.980
Listen the sound of cabbage in boiling water

0:05:19.990,0:05:21.620
I like this atmosphere

0:05:21.620,0:05:24.290
Listen to this

0:05:25.750,0:05:28.390
Gudong gudu gudu gudu gudu

0:05:28.390,0:05:29.910
Know the cabbage is ready

0:05:29.910,0:05:31.730
Then we need to wash it by cool water

0:05:32.390,0:05:33.060
Listen

0:05:33.070,0:05:37.780
Why cabbage cooked by some people is smelly

0:05:37.790,0:05:38.170
They didn't wash it

0:05:38.180,0:05:38.680
No shower.

0:05:39.430,0:05:39.660
Yes

0:05:39.670,0:05:42.290
We need to get rid of this smell

0:05:42.300,0:05:44.230
Go taste it when he is absent

0:05:44.810,0:05:45.670
Is it still bitter

0:05:45.680,0:05:48.340
or has astringency

0:05:48.350,0:05:50.040
All are gone

0:05:50.050,0:05:51.440
It is just alright

0:05:52.660,0:05:54.800
And then we split it after cooling down

0:05:54.870,0:05:56.600
to four strips

0:05:57.100,0:05:58.500
Man I just want to tell you the flavour

0:05:58.600,0:06:00.170
is very perfect

0:06:00.180,0:06:02.060
It doesn contain strange tastes any more

0:06:02.880,0:06:07.090
Let the inner part of cabbage face upward

0:06:07.100,0:06:09.080
Trim it up

0:06:09.090,0:06:09.860
Let't go

0:06:09.870,0:06:11.090
Look how tidy this dish is

0:06:11.090,0:06:12.610
Skim the oil.

0:06:15.320,0:06:18.820
This soup must be boiled when you skim the oil

0:06:19.130,0:06:21.700
The oil is floating

0:06:21.710,0:06:24.250
Sometimes you have to push it to the side

0:06:24.680,0:06:26.190
Clean up the oil

0:06:27.720,0:06:30.100
Well that is carefulness from old chef

0:06:31.040,0:06:31.970
Very crafted work

0:06:32.710,0:06:34.280
My soup smells so good

0:06:34.290,0:06:34.570
Yes

0:06:36.710,0:06:38.280
At th end,  we want less oil and more soup

0:06:38.380,0:06:39.370
Don't waste the soup

0:06:39.590,0:06:40.500
Let me taste it

0:06:40.730,0:06:41.800
good

0:06:42.440,0:06:45.290
Blow the oil out

0:06:45.300,0:06:46.670
Well, there is no oil in this soup

0:06:46.680,0:06:50.230
Use some water to resolve minced chicken meat

0:06:50.230,0:06:51.540
Use some water

0:06:51.540,0:06:55.280
Put some Huadiao Wine in it

0:06:56.300,0:06:57.440
We can't make it without Huadiao Wine

0:06:57.860,0:06:59.880
Huadiao wine is really useful

0:07:00.400,0:07:02.040
Huadiao comes

0:07:02.050,0:07:03.030
good

0:07:03.040,0:07:06.860
Stir the minced chicken

0:07:07.230,0:07:09.220
Put it into the boiling soup

0:07:10.090,0:07:11.320
Set the heat high

0:07:14.790,0:07:17.180
Stir in one direction

0:07:17.190,0:07:19.740
It will boil soon.

0:07:20.700,0:07:21.840
Steamer ready

0:07:21.850,0:07:24.570
Because we are going to steam the cabbage soup

0:07:24.580,0:07:25.290
This is called 'Sao'

0:07:25.410,0:07:26.280
Which makes the soup even more clear

0:07:26.290,0:07:27.340
There are to way to 'Sao', one is white Sao

0:07:27.680,0:07:29.660
So called Bai Sao is to use chicken breast

0:07:29.670,0:07:30.760
Another kind is called red Sao

0:07:30.770,0:07:34.250
using beef fillet

0:07:34.260,0:07:37.440
Color of our soup seems to be a little bit deep

0:07:37.450,0:07:41.420
There is another way used by the noble in the past

0:07:41.430,0:07:43.310
Use both beef and chicken

0:07:43.320,0:07:45.410
You see, boiling brings oil to the surface

0:07:46.010,0:07:49.060
Now the foam comes out again

0:07:49.070,0:07:54.620
Some other phenomenon occurs when we hanging soup

0:07:54.630,0:07:56.520
Some of them have a lot of meat skin and chicken claws in them

0:07:56.530,0:08:02.050
The problem is these things contains too much collagen

0:08:02.060,0:08:04.300
So putting this things

0:08:04.310,0:08:05.370
makes the soup turbid

0:08:06.100,0:08:07.220
You see the water is boiling

0:08:07.230,0:08:08.670
The foam is all floating

0:08:11.010,0:08:12.480
Clean all these foam

0:08:12.490,0:08:14.420
You're almost done with the soup now

0:08:15.480,0:08:19.660
And then in order to make the soup even more perfect

0:08:19.670,0:08:21.300
'Smash' it fot the second time

0:08:21.620,0:08:23.960
Well

0:08:24.160,0:08:27.210
Set in on high heat and stir

0:08:27.930,0:08:29.250
Utilizing the mincered chicken breast

0:08:29.260,0:08:32.530
do agitation rotation and contraction

0:08:32.990,0:08:38.400
It basically absorbs all the impurities in the soup

0:08:44.090,0:08:45.860
The soup is clear

0:08:45.870,0:08:47.400
Clean the foam

0:08:47.400,0:08:51.010
For our last video

0:08:51.780,0:08:53.870
audience raised some questions

0:08:53.880,0:08:55.590
What means 'smashing'?

0:08:55.600,0:08:58.080
Let me show you today

0:08:58.090,0:08:58.540
good

0:08:58.550,0:08:59.310
Get some cold water

0:08:59.320,0:09:02.600
The soup has few foam on its surface

0:09:02.610,0:09:04.600
Maybe there are still some foam inside, so 'smash' it

0:09:04.610,0:09:05.350
Do you see

0:09:05.670,0:09:08.270
'smash' using cold water

0:09:08.280,0:09:08.890
The set the fire high.

0:09:08.900,0:09:10.580
See

0:09:10.590,0:09:10.780
Yes

0:09:10.790,0:09:13.090
It is crystal clear now

0:09:13.100,0:09:13.950
We can even see bottom of the pot

0:09:13.960,0:09:15.930
And the chicken breast sinks

0:09:16.340,0:09:17.090
You see

0:09:17.630,0:09:19.290
It's going down slowly

0:09:19.630,0:09:21.160
There will be some foam taken out by the mincered chicken later

0:09:21.950,0:09:22.260
Smash

0:09:22.270,0:09:26.180
It's just to bring out all the foam, even in the mincered chicken

0:09:26.190,0:09:27.620
Come on, come on

0:09:38.660,0:09:40.910
You see, it is clearer

0:09:43.560,0:09:43.810
Okay

0:09:43.820,0:09:46.760
Turn off the fire.

0:09:46.770,0:09:47.440
Turn off the fire

0:09:47.450,0:09:49.720
Turn off the fire and filter now

0:09:51.180,0:09:54.270
we'd better hanging or stewing for half an hour

0:09:55.850,0:09:56.880
Next time we talk about stewing

0:09:56.890,0:09:59.200
When we done stewing, everything sink to the bottom

0:09:59.210,0:10:03.270
In addition, the flavor of mincered chicken can be triggered by hanging

0:10:04.520,0:10:06.640
You see, the flavour of chicken comes out

0:10:06.650,0:10:07.170
Yes

0:10:07.350,0:10:09.570
Look at the soup. The chicken is smashed down

0:10:09.900,0:10:11.860
The color is yellow

0:10:11.860,0:10:14.860
Pay attention to mincered chickenwhen filtering

0:10:14.870,0:10:16.010
There are dregs in it

0:10:16.020,0:10:17.420
Do not stir.

0:10:17.430,0:10:20.780
Finally, we'd better use double layer Doubao cloth

0:10:20.930,0:10:23.070
Double layer Doubao cloth

0:10:23.310,0:10:26.860
After that, use paper to dip oil

0:10:26.870,0:10:28.690
In the past, this is the most fastidious detail in banquet

0:10:28.690,0:10:30.140
The soup is ready

0:10:30.150,0:10:31.260
Now it's time to season

0:10:31.270,0:10:32.060
Salt.

0:10:32.470,0:10:33.850
White pepper powder

0:10:34.160,0:10:37.930
Because this soup is made of baby cabbage

0:10:38.180,0:10:39.890
it might be a little bitter

0:10:39.900,0:10:41.010
When we season soup

0:10:41.020,0:10:43.730
Put a little sugar

0:10:44.780,0:10:45.140
good

0:10:45.150,0:10:46.290
Now we are done

0:10:46.300,0:10:48.580
This time pour it on the cabbage

0:10:56.540,0:10:58.720
When should we stop steaming?

0:10:58.730,0:11:02.550
When the cabbage floats

0:11:02.610,0:11:05.830
When it floats

0:11:06.140,0:11:10.320
Boiled Chinese Cabbage in Soup!

0:11:10.330,0:11:12.060
I made some innovation

0:11:12.120,0:11:13.480
I put some medlar

0:11:15.290,0:11:15.680
Uh huh.

0:11:16.210,0:11:16.790
Pretty good

0:11:16.800,0:11:18.680
This is really boiled cabbage

0:11:27.600,0:11:28.180
I am Da Ye.

0:11:28.190,0:11:28.810
I am Er Bai.

0:11:28.820,0:11:29.650
I am San Shu.

0:11:30.110,0:11:32.240
We are Lao Fan Gu

0:11:32.250,0:11:34.320
Welcome to subscribe to our Lao Fan Gu YouTube channel

0:11:35.510,0:11:38.400
We are here to teach you how to cook

0:11:38.480,0:11:40.550
and share with you some little tips

0:11:40.560,0:11:41.530
I hope you like it

0:11:41.540,0:11:44.510
I hope food lovers all over the world like us

0:11:44.940,0:11:46.390
Subscribe our channel

0:11:46.400,0:11:47.490
Click the notification bell

0:11:47.500,0:11:48.910
At the same time here

0:11:48.920,0:11:51.340
We wish you all the best

0:11:51.350,0:11:53.230
May you have a lot of happiness and fortune

0:11:53.240,0:11:55.900
Thank you

**Comment by shuaisoserious** [comment]
下一个节目
开水白菜
开水白菜的第一个环节呢
还得先吊汤
又吊上汤了 又吊上了
先把这个鸡爪子
一般在我们熬汤当中
不用
鸡屁股也不用
鸡头我已经砍掉了
鸡头腥
因为咱们在家里做
锅小一点
咱们给它改成块
这次再重复一下
吊汤是为菜而吊汤
煲汤是为喝而煲汤
把这鸡胸肉给提出来
提出来
一会咱们要做清汤的
得用这鸡胸肉
左撕右dun（手字旁屯）啊
这个剔个鸡很简单
把这个鸡翅膀就扔到锅里头
把这个鸡胸肉拿下来
这样呢就给它改改块
块改小一点便于烹调
一会熬汤也快
这老哥俩
帅呆了酷毙了
这点儿得注意
这鸡的我们管它叫尖端
一个是有味
一个是不健康
点火啦， 凉水下锅
鸡在汤里起的作用是鲜
搁点肘子或者瘦肉
它是提香
这个骨头熬汤非常好
它里面含钙
而且它熬出这汤香
用骨头的这种香味
肉骨的这种香味
再加上鸡的鲜味
这鸡胸肉为了一会还要清汤么
砸一个鸡燥子
白菜简单
但是这个汤可要了命了
开水白菜是四川的一个
很有名的菜
发明这个菜的师傅
是北京饭店的
叫罗国荣
川菜大师
但是那天客人还想吃白菜
还要油要少
味儿还要好吃
这开水白菜一端上来
这客人以为真是开水
但是客人这一吃
可不一样了
真香
形如开水
白菜软烂
这成四川名菜了
这个鸡蓉砸好了
这有什么用处啊
一会清汤啊
鸡蓉不用砸特别细
不用砸太细
让它那筋能连着
待会儿下锅清这汤的时候
它会把汤里面所有的杂质都吸上去
顺手搁两片姜
待会再搁两片葱
就齐啦
你看见没有
它为什么凉水下
它慢慢的把这个脏东西
从里到外给拱出来
出沫子了啊
沫子一定要干净
要撇净了
等会这个有点耍不开了
看着啊沫子起来了
当有时候不好打的时候
下点凉水
要砸一下
砸一下以后呢
这沫子就沉下来点儿来了
再逮一逮沫子
沫子释放的更加充分
砸这沫子是为了撇东西
我参加过这么多电视节目
我也看过无数次电视节目
没有一个是真正的
像这么着
你看郑老师今天无私的
两次了
两次教清汤
咱们把出好水的肉
搁另外一个锅里头
我们还要坚持
我上次说的这个道理
还要高压
减少汤的嘌呤
把它弄干净以后
搁到这里头
骨头再出出水
这锅有点小
分两次
家庭版也很重要啊
跟酒店的整个过程都是一样的
有时候有必要呢
我们还要给它洗一洗
二伯给打打沫子
非常干净
这个猪肉的飞水就干净了
原汤 给放在这锅里
帮我扶一下锅
再加点水啊
给它压上
不拿高压锅压得多长时间
要照着四小时
拿高压锅压着
二十五分钟半小时就行
让放气儿
一个多小时就够了
这汤你看见没有？
彻底干净了
这时候我们把它高压上
你看这沫子特别干净
看好了啊
我们把这个放到锅里头
煲汤 二十五分钟
就开始啦
用四川话说嘞就叫开水白菜
我们做呢应该是找应季的
应季的白菜
应该是最好的白菜是产在哪儿呢？
产在山东泰安
泰安有三美啊
白菜 豆腐 水
它那个白菜叫黄芽白
叫黄芽菜
那菜绝了吃完了
那菜要做出来以后更漂亮
金黄金黄的
但是我们今天用的是娃娃菜
娃娃菜在烫的时候多烫一会儿
去掉娃娃菜本身的涩苦味
不用搁点盐么
不用
这边煮着菜
咱们取鸡汤
高压锅吊汤 来着
一锅清汤
二伯你看这白菜煮的
咕嘟咕嘟的声音
多有气氛
看看啊 大家听听这声儿
咕嘟咕嘟咕嘟咕嘟
好啦 白菜已经好了
关火
好了以后我们去给它冲凉
大家看看啊
好多人为什么白菜
捂的臭白菜味啊， 它不鲜阿
它不冲凉啊有时候
对
要把这白菜的味彻底冲干净
趁他不在赶紧尝尝
苦不苦啊
涩也没了吧
这一冲啊还真没了
而且吧正合适
凉了我们把它劈开
一劈四瓣
我给你说这味道啊
一点都没有邪味了
把这个心儿口朝上
把它修整整齐
走
看看啊看看白菜多整齐
看看撇油呢啊
撇油的时候这汤一定要开
这油在上头飘着
有时候一推还往边儿上走
把油要拾（手四个又）干净
好 还是老师傅心细啊
做活儿讲究
你闻着这汤很香
到最后油少汤多
别浪费这汤
来我吹一下
把油吹出去
好了这汤已经没有油了
这是鸡蓉
鸡蓉用点水把它分解开
这里边搁点花雕酒
没花雕酒还真不行
花雕
还不少搁呢
这鸡蓉把它抓碎
这汤已经开了
倒进去
这时候开大火
搅动
一个方向
马上就开
蒸锅准备好
因为这白菜要去蒸
这个汤给它扫清了 这叫扫汤
一种是白臊
所谓白臊就是用鸡胸肉
还有一种是红臊
比如说用瘦牛肉啊， 瘦里脊啊
它这汤出来以后颜色比较稍微重一点
还有一个呢
宫廷里面叫双吊汤
又使牛肉又使鸡肉
你看见没有
它这一开把那油都带出来了
对
你看现在这浮沫已经出来了
有时候我们在熬汤当中
也会出现其他一些现象
有点里面搁了好多肉皮凤爪
关键他搁这些东西
它那胶原蛋白太厚
太重了
他搁了这些比较浑浊的东西
它容易浑汤
你看这水开了
这沫子全都浮起来了
把这沫子打干净
现在这汤基本就清了
为了使这汤更加完美
二次砸
大火呼一下
顺时针搅动
通过鸡蓉下去这种
搅动 旋转 收缩
它把汤里面的一些杂质
基本上都给收起来了
大家看啊这汤已经清了
这沫子打干净
有点网友在上次节目当中
提了一些疑问
什么叫砸呀
今天我给大家演示一下啊
接点凉水
这汤现在可能觉得沫子少了吧
可能还有沫子
再砸它一遍 看见没有
再砸
凉水一砸 大火一开
现在已经清澈无比了
已经见底儿了把
而且这东西往下沉了应该
你看 慢慢慢慢就下去了
对你看 一会还有沫子
砸呢就是要把它
这鸡蓉里面也有沫子
彻底砸出来
你看啊 这汤更清
看着啊 关火
关火了大爷关火了
过萝
看这汤
最好燉它半小时
上次咱们讲燉
燉完了这个料就沉底了
另外这鸡蓉的香味
也能给它吊出来
你看这鸡蓉已经吊出味了
你看这汤颜色
你看砸下去了吧
颜色也很黄
过滤的时候注意点鸡蓉
鸡蓉也有渣子 我们别搅动
最好用双层豆包布
双层豆包布 给它过一下
豆包布过完了
还得用纸去粘粘油去
过去做宴会最讲究的在这儿呢
汤 齐了
现在开始调味
搁盐
白胡椒粉
因为这个汤用的是娃娃菜
它可能会有点涩苦味
我们在调汤的时候
稍微点点糖
点点糖
好 这味就有啦
这可以把它灌在这里
漂亮
开水白菜蒸到什么时候为好呢
白菜浮起
即好
这就是窍门 飘起来
开水白菜
这白菜
我也创点新
中间撒了点枸杞
不错 真是开水大白菜
