### ISSUE TITLE
【美食作家王刚】介绍工程灶和其他厨房用具价格 - https://youtu.be/MeaLR9gvhHY

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#747]
【美食作家王刚】介绍工程灶和其他厨房用具价格 - https://youtu.be/MeaLR9gvhHY
视频时长 7:49，预计发布时间为北京时间3月5日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.650,0:00:02.225
哈喽大家好 我是王刚

0:00:02.700,0:00:04.250
有很多粉丝跟我留言

0:00:04.325,0:00:05.825
然后问了一些问题

0:00:06.125,0:00:08.590
今天拍这个视频跟大家解释一下

0:00:08.590,0:00:11.500
这一套炉具相关的一些东西

0:00:11.700,0:00:13.850
第一个粉丝问这个设备买下来多少钱

0:00:14.825,0:00:18.450
关于这个的话我后面来跟大家算一个总账多少钱

0:00:18.900,0:00:20.275
然后第二个是说 

0:00:21.000,0:00:22.550
让我报个价让他死心

0:00:23.025,0:00:25.050
等一下也放到后面来聊

0:00:25.350,0:00:29.475
还有一个粉丝就是说这个无论是酒店专用还是怎么样

0:00:29.550,0:00:33.450
他个人认为还是电磁炉实用成本低

0:00:33.725,0:00:36.775
这个确实是电磁炉比较实用体积又小

0:00:36.925,0:00:37.925
拿着就走

0:00:38.100,0:00:44.100
但是说仅限于是家庭使用或者是单身人士使用

0:00:44.200,0:00:45.350
是吧 随拿随走

0:00:45.500,0:00:47.375
如果说让我们专业人士来做的话

0:00:47.500,0:00:50.950
我至今从来没有用电磁炉炒过菜

0:00:51.350,0:00:55.775
电磁炉在我们(后厨)迫不得已的话我只用它来煮一些汤

0:00:55.800,0:00:57.250
或者是炖一些菜

0:00:57.575,0:00:58.925
从来不会用它做炒菜

0:00:59.150,0:01:00.500
因为你一炒的话

0:01:00.650,0:01:02.200
刚开始锅热的时候还行

0:01:02.675,0:01:06.650
菜一下去一会儿这个东西就是叫做煮菜不叫做炒菜

0:01:07.200,0:01:08.825
好啦现在我来介绍一下这边

0:01:09.600,0:01:13.825
这个报价就是粉丝最关心的一个问题留言最多的一个问题

0:01:14.050,0:01:16.000
也好让你们死一下心

0:01:16.200,0:01:17.742
这一个你们看得到的这个

0:01:17.950,0:01:19.850
不锈钢的叫做打荷台

0:01:20.125,0:01:22.000
这个打荷台有贵有便宜

0:01:22.025,0:01:27.550
它贵与便宜区别在于皮有厚有薄

0:01:27.825,0:01:30.990
最薄的是0.4毫米

0:01:31.375,0:01:32.825
然后有0.6毫米

0:01:33.000,0:01:34.275
有1.0毫米

0:01:35.600,0:01:39.075
一般来说0.4毫米的话就300多块钱一张

0:01:39.139,0:01:43.837
这个它宽度是80（厘米）长是1.8（米）高度也是80（厘米）

0:01:44.325,0:01:47.725
然后它这个便宜的话用手可以按进去

0:01:48.050,0:01:50.000
可以这样用力按就是一个窝

0:01:50.050,0:01:51.725
所以这个质量就非常差

0:01:51.950,0:01:54.975
然后我买得这款是0.6毫米的

0:01:55.275,0:01:56.625
这个中间加了木板

0:01:56.800,0:01:59.675
然后普通家庭用的话还是非常不错

0:01:59.700,0:02:01.150
如果是我们专业厨房的话

0:02:01.275,0:02:03.150
最好用1.0（毫米）以上的

0:02:03.450,0:02:05.050
因为1.0以上的我们

0:02:05.475,0:02:10.625
剁菜的时候一刀剁下去或者是说用力捶一下一点不会变形

0:02:10.675,0:02:12.600
质量非常的好 但是它非常贵

0:02:13.250,0:02:14.975
0.6（毫米）的是900多

0:02:15.325,0:02:19.250
然后1.0以上的还要分中间有没有这个隔层

0:02:19.400,0:02:20.150
有没有拉门

0:02:20.550,0:02:26.175
就是最便宜的没有拉门两层的是1600块钱左右

0:02:26.400,0:02:30.075
如果有拉门有隔层的最少2000块钱以上

0:02:30.450,0:02:33.975
我们厨房里面就拿一个灶来说

0:02:34.050,0:02:35.075
最少配两张

0:02:35.900,0:02:40.375
所以这里的话两张我们就按照最贵的来算3000多

0:02:40.800,0:02:42.275
3800块钱

0:02:42.925,0:02:47.025
然后我买这两个的话花了1960块钱

0:02:47.775,0:02:49.350
两张花了1960块钱

0:02:49.600,0:02:54.225
然后第二件东西的话就是这个菜板砧板这一块

0:02:54.475,0:02:57.225
这个砧板的话你看有这么厚

0:02:57.800,0:02:58.850
10-20公分厚

0:02:59.275,0:03:01.100
这块的话就不贵

0:03:01.300,0:03:03.175
但是非常的笨重

0:03:03.425,0:03:04.925
有50-60斤

0:03:05.300,0:03:08.725
然后120块钱左右吧

0:03:09.075,0:03:10.125
这个东西是不贵

0:03:10.250,0:03:13.750
应该说整个厨房当中是比较便宜的一个东西

0:03:14.000,0:03:15.150
然后就是菜刀

0:03:15.425,0:03:17.975
菜刀就不用说了家庭用的话就随便

0:03:18.250,0:03:20.450
有的粉丝说5块钱也可以买一把

0:03:20.800,0:03:23.925
但是我们这个如果要用得好一点

0:03:24.025,0:03:26.700
质量OK的话最少100块钱以上

0:03:27.325,0:03:29.750
然后品牌的话就自己去选

0:03:30.325,0:03:34.025
现在我来说一下这个最主要的东西就是这个炉灶

0:03:34.250,0:03:36.375
这个炉灶的话我是按照顶配来买的

0:03:36.825,0:03:39.925
它的价格是3800块钱左右

0:03:40.225,0:03:43.225
如果你想配置更高一点

0:03:43.325,0:03:44.325
加两个鼓风机

0:03:44.625,0:03:45.250
要加钱

0:03:45.775,0:03:48.325
大概要加1000块钱

0:03:48.450,0:03:51.500
然后就是4800左右 再配上一个运费

0:03:51.550,0:03:54.550
因为经销商它不会给你包邮的

0:03:54.650,0:03:56.750
因为他给你拉过来什么的都是要钱

0:03:57.025,0:03:58.625
加运费这一坨 

0:03:58.925,0:04:02.075
我是成都买的 到我们这个地方

0:04:02.525,0:04:04.200
花了800多块钱的运费

0:04:04.200,0:04:06.675
不是说你这些买回来就可以用

0:04:06.750,0:04:10.275
第一你如果是接煤气的话你要买煤气罐 对吧

0:04:11.125,0:04:13.800
如果你是用天然气的话你要开户

0:04:14.050,0:04:15.875
开户的话这个多少钱我就不知道了

0:04:15.900,0:04:17.800
然后就是可以烧环保油

0:04:18.350,0:04:21.550
这三种无非就是怎么样转换呢

0:04:21.600,0:04:28.400
把炉心根据你用什么燃料然后就换什么炉心 很简单比较便宜

0:04:28.500,0:04:30.675
这是第一个气就是燃料这一块

0:04:31.100,0:04:32.250
第二的话就是电

0:04:32.925,0:04:34.400
你知道这个有鼓风机对吧

0:04:34.475,0:04:36.550
这个要拉线来接上这个鼓风机

0:04:36.600,0:04:37.525
它还要耗电

0:04:37.850,0:04:39.550
有了电和气还不行

0:04:39.650,0:04:40.750
还要接上水

0:04:41.175,0:04:43.375
因为这个炉的话温度比较高

0:04:43.625,0:04:45.400
你如果不放水这里两下就烧坏了

0:04:45.450,0:04:46.100
要接上水

0:04:47.150,0:04:48.700
还有一个最重要的一个点

0:04:48.825,0:04:49.500
油烟机

0:04:50.025,0:04:51.750
如果你的楼房特别高

0:04:51.925,0:04:54.775
你要从一楼装一个排烟道装到楼顶

0:04:55.000,0:04:58.000
那这个（费用）可多可少

0:04:58.400,0:05:02.550
我做过的餐厅最贵的装一根油烟管道花了10万

0:05:02.675,0:05:04.489
如果你是在自己家里面

0:05:04.800,0:05:06.665
就是农村的家你不能在城市里面

0:05:06.675,0:05:09.100
城市里面你很难弄进去

0:05:09.350,0:05:10.600
然后也会非常吵

0:05:11.200,0:05:14.350
在自己家里面的话这一套下来

0:05:14.675,0:05:18.425
全部置办下来到你能够炒菜

0:05:19.150,0:05:22.575
我估计的话预算 大概预算是1万块钱

0:05:22.950,0:05:24.600
然后我建不建议你们这么做呢

0:05:24.725,0:05:26.275
其实不建议你们这么做

0:05:26.450,0:05:28.450
第一是价钱让你们死心

0:05:28.600,0:05:31.525
第二是这个操作也是让你们死心

0:05:31.900,0:05:33.075
然后最后一点呢

0:05:33.325,0:05:35.150
你这些东西买回来了之后

0:05:35.350,0:05:37.500
你不会用也是很麻烦的你看

0:05:37.675,0:05:42.200
随便一个你炒菜必须用这个锅 家用的锅放不进去

0:05:42.275,0:05:43.100
因为这个特别大

0:05:43.250,0:05:46.225
放进去了之后你不可能用锅铲这样子炒

0:05:46.400,0:05:49.900
而你要配上这一套技术对吧

0:05:50.425,0:05:54.825
你不可能买了这一套东西然后花个10年8年去学烹饪什么的

0:05:54.925,0:05:55.975
这个也不大现实

0:05:56.625,0:06:03.625
所以我们大家对于说买这套炉具来自己家用的话就看一下就好啦

0:06:04.350,0:06:06.287
如果你们实在是想

0:06:06.750,0:06:08.950
还想买的话我就建议你们

0:06:09.250,0:06:10.600
其实不用买双灶

0:06:10.700,0:06:13.675
有单灶的 单灶就便宜很多

0:06:14.100,0:06:15.250
第一呢它运费便宜

0:06:15.300,0:06:16.925
第二呢它是买得也便宜

0:06:17.250,0:06:19.225
单灶的话1000多块钱

0:06:19.550,0:06:20.700
它也带鼓风机

0:06:21.125,0:06:24.250
然后的话它面积就比这个小很多很多

0:06:24.375,0:06:25.600
就更方便于操作

0:06:26.075,0:06:28.229
我们买得这一套是中配

0:06:28.650,0:06:32.900
如果你想买简约一点的可以买一个小的

0:06:33.100,0:06:35.928
先尝试一下能不能驾驭得了这个

0:06:36.250,0:06:40.450
如果能驾驭得了我们以后再慢慢扩也可以

0:06:40.825,0:06:43.000
就是说烹饪作为一个爱好

0:06:43.650,0:06:47.650
我们这一套全部按照最顶格来配的话

0:06:48.000,0:06:50.950
不考虑油烟机大概2万块钱左右

0:06:51.325,0:06:53.075
就相当于翻了一番价格

0:06:53.450,0:06:55.450
如果按照最简约的来配的话

0:06:55.600,0:06:57.000
打荷台300多

0:06:57.225,0:07:03.250
然后这个炉灶带鼓风机的单个炉灶1000多

0:07:03.950,0:07:05.375
加上菜板什么的

0:07:05.650,0:07:07.275
所有加起来2000块钱以内

0:07:07.650,0:07:08.550
都是OK的

0:07:08.975,0:07:10.525
然后也有粉丝再问

0:07:10.550,0:07:12.700
他说你买这一套来干什么呢

0:07:12.875,0:07:14.525
其实我买这一套炉具来

0:07:14.650,0:07:16.736
第一是跟大家分享它的作用

0:07:17.025,0:07:21.900
可能大家没看过真正后厨的这个是怎么样子操作

0:07:22.300,0:07:25.750
然后呢也是从第一步炒菜跟大家分享

0:07:25.850,0:07:29.450
从翻锅开始到后面的我会的

0:07:29.750,0:07:30.625
跟你们分享

0:07:31.050,0:07:33.575
这就是我买这一套厨具的初衷

0:07:34.000,0:07:35.900
好啦本期视频就到这里结束

0:07:36.100,0:07:37.675
喜欢我的可以关注一下我

0:07:37.725,0:07:41.600
后面慢慢来 我们来日方长慢慢得学

0:07:41.800,0:07:44.000
我也在不断的学习

0:07:44.325,0:07:46.000
跟大家分享更多的东西

0:07:46.200,0:07:47.325
好啦 就到这里

0:07:47.475,0:07:47.975
拜拜

**Comment by Yingzhang1122** [comment]
#https://youtu.be/MeaLR9gvhHY

0:00:00.650,0:00:02.225
哈喽大家好 我是王刚
Hi everyone, I'm Wang Gang

0:00:02.700,0:00:04.250
有很多粉丝跟我留言
Many fans have left their comments

0:00:04.325,0:00:05.825
然后问了一些问题
and asked some questions

0:00:06.125,0:00:08.590
今天拍这个视频跟大家解释一下
Today I'm shooting this video to explain to you guys

0:00:08.590,0:00:11.500
这一套炉具相关的一些东西
something about this cooking stove

0:00:11.700,0:00:13.850
第一个粉丝问这个设备买下来多少钱
One fan asked me how much does this whole set of cooking system take?

0:00:14.825,0:00:18.450
关于这个的话我后面来跟大家算一个总账多少钱
I'll calculate how much it costs in total later in this video

0:00:18.900,0:00:20.275
然后第二个是说
Another fan said that

0:00:21.000,0:00:22.550
让我报个价让他死心
he wanted me to tell the price just to let him give up

0:00:23.025,0:00:25.050
等一下也放到后面来聊
I'll talk about this later

0:00:25.350,0:00:29.475
还有一个粉丝就是说这个无论是酒店专用还是怎么样
Another fan said that, no matter in the restaurant or at home

0:00:29.550,0:00:33.450
他个人认为还是电磁炉实用成本低
He thinks induction cooker is cheaper and more practical

0:00:33.725,0:00:36.775
这个确实是电磁炉比较实用体积又小
Indeed, induction cooker is easy to use and small

0:00:36.925,0:00:37.925
拿着就走
You can even bring it with you

0:00:38.100,0:00:44.100
但是说仅限于是家庭使用或者是单身人士使用
But it's limited to family use, or those who live alone

0:00:44.200,0:00:45.350
是吧 随拿随走
Right? It's quite portable

0:00:45.500,0:00:47.375
如果说让我们专业人士来做的话
However, in the case of professional use

0:00:47.500,0:00:50.950
我至今从来没有用电磁炉炒过菜
I've never cooked any dish with induction cooker

0:00:51.350,0:00:55.775
电磁炉在我们(后厨)迫不得已的话我只用它来煮一些汤
In restaurant kitchens, we only use induction cookers to make soup if there is no other choice

0:00:55.800,0:00:57.250
或者是炖一些菜
Or stew some food

0:00:57.575,0:00:58.925
从来不会用它做炒菜
But we never use induction cookers to make stir-fry dishes

0:00:59.150,0:01:00.500
因为你一炒的话
Because if you stir-fry food with it

0:01:00.650,0:01:02.200
刚开始锅热的时候还行
It's OK in the beginning when the wok is still hot

0:01:02.675,0:01:06.650
菜一下去一会儿这个东西就是叫做煮菜不叫做炒菜
However when you put more food into the wok, it turns into "boiling" instead of "stir-frying"

0:01:07.200,0:01:08.825
好啦现在我来介绍一下这边
Alright. Let me introduce this now

0:01:09.600,0:01:13.825
这个报价就是粉丝最关心的一个问题留言最多的一个问题
Most fans are really concerned about the price. That's the most frequently asked question too.

0:01:14.050,0:01:16.000
也好让你们死一下心
Let me tell you so that you can give up

0:01:16.200,0:01:17.742
这一个你们看得到的这个
This one, as you can see

0:01:17.950,0:01:19.850
不锈钢的叫做打荷台
This table made of stainless steel is called "Da He Tai" (Spreader table)

0:01:20.125,0:01:22.000
这个打荷台有贵有便宜
Well, its price can vary

0:01:22.025,0:01:27.550
它贵与便宜区别在于皮有厚有薄
depending on how thick the steel "skin" is #请检查这里，我在这里用了skin表示外皮，但是后面用了sheet，算是铁皮的通用说法，不知道这样是否合适

0:01:27.825,0:01:30.990
最薄的是0.4毫米
The thinnest sheet can be 0.4 mm

0:01:31.375,0:01:32.825
然后有0.6毫米
While some are 0.6 mm

0:01:33.000,0:01:34.275
有1.0毫米
and 1.0 mm

0:01:35.600,0:01:39.075
一般来说0.4毫米的话就300多块钱一张
Generally a "Da He Tai" with 0.4 mm thick sheet is about 300 yuan

0:01:39.139,0:01:43.837
这个它宽度是80（厘米）长是1.8（米）高度也是80（厘米）
The dimensions of this table are 80 cm in width and height, while 1.8 m in length

0:01:44.325,0:01:47.725
然后它这个便宜的话用手可以按进去
For the cheapest ones, if you press it with your hand

0:01:48.050,0:01:50.000
可以这样用力按就是一个窝
there'll be a pit

0:01:50.050,0:01:51.725
所以这个质量就非常差
In that case, the quality is really bad

0:01:51.950,0:01:54.975
然后我买得这款是0.6毫米的
This one that I bought is with 0.6 mm-thick sheet

0:01:55.275,0:01:56.625
这个中间加了木板
With a wooden board sandwiched in the middle

0:01:56.800,0:01:59.675
然后普通家庭用的话还是非常不错
It's pretty ideal for family use

0:01:59.700,0:02:01.150
如果是我们专业厨房的话
But in a professional kitchen

0:02:01.275,0:02:03.150
最好用1.0（毫米）以上的
It's better to use the table with a skin thicker than 1.0 mm

0:02:03.450,0:02:05.050
因为1.0以上的我们
Because for those tables (with sheets thicker than 1.0 mm)

0:02:05.475,0:02:10.625
剁菜的时候一刀剁下去或者是说用力捶一下一点不会变形
when you chop the food, or hit it hard, the table won't deform

0:02:10.675,0:02:12.600
质量非常的好 但是它非常贵
It's of high quality, but very expensive

0:02:13.250,0:02:14.975
0.6（毫米）的是900多
The table with 0.6 mm-thick skin is more than 900 yuan

0:02:15.325,0:02:19.250
然后1.0以上的还要分中间有没有这个隔层
For those with sheet over 1.0 mm thick, the price also depends on if there are shelving racks

0:02:19.400,0:02:20.150
有没有拉门
and sliding doors

0:02:20.550,0:02:26.175
就是最便宜的没有拉门两层的是1600块钱左右
The cheapest two-layer table without sliding door is about 1,600 yuan

0:02:26.400,0:02:30.075
如果有拉门有隔层的最少2000块钱以上
If it's with sliding doors and shelving racks, it will be at least 2,000 yuan

0:02:30.450,0:02:33.975
我们厨房里面就拿一个灶来说
Typically in a professional kitchen, for each cooking stove

0:02:34.050,0:02:35.075
最少配两张
It should be accompanied with at least two tables

0:02:35.900,0:02:40.375
所以这里的话两张我们就按照最贵的来算3000多
So here we've got two tables, assuming they are the most expensive ones, it would be more than 3,000 yuan

0:02:40.800,0:02:42.275
3800块钱
3,800 yuan

0:02:42.925,0:02:47.025
然后我买这两个的话花了1960块钱
For these two, I spent 1,960 yuan

0:02:47.775,0:02:49.350
两张花了1960块钱
1,960 yuan for these two tables

0:02:49.600,0:02:54.225
然后第二件东西的话就是这个菜板砧板这一块
The second thing is the cutting board

0:02:54.475,0:02:57.225
这个砧板的话你看有这么厚
You see, this cutting board is so thick

0:02:57.800,0:02:58.850
10-20公分厚
about 10-20 cm thick

0:02:59.275,0:03:01.100
这块的话就不贵
This one is not expensive though

0:03:01.300,0:03:03.175
但是非常的笨重
But very bulky and heavy

0:03:03.425,0:03:04.925
有50-60斤
It's about 50-60 Jin (25-30 kg)

0:03:05.300,0:03:08.725
然后120块钱左右吧
And it's about 120 yuan

0:03:09.075,0:03:10.125
这个东西是不贵
Well, it's not expensive indeed 

0:03:10.250,0:03:13.750
应该说整个厨房当中是比较便宜的一个东西
It should be one of the cheapest things in kitchen

0:03:14.000,0:03:15.150
然后就是菜刀
Next, the cleaver #还是kitchen knife?

0:03:15.425,0:03:17.975
菜刀就不用说了家庭用的话就随便
Well, it doesn't matter what kind of cleaver you use in family kitchen

0:03:18.250,0:03:20.450
有的粉丝说5块钱也可以买一把
Some fans say you can buy one for 5 yuan

0:03:20.800,0:03:23.925
但是我们这个如果要用得好一点
However, if you want to use a better one

0:03:24.025,0:03:26.700
质量OK的话最少100块钱以上
You need to spend at least 100 yuan for a high quality cleaver

0:03:27.325,0:03:29.750
然后品牌的话就自己去选
Choose the brand on your own

0:03:30.325,0:03:34.025
现在我来说一下这个最主要的东西就是这个炉灶
Now I'm gonna talk about the most important thing, the cooking stove

0:03:34.250,0:03:36.375
这个炉灶的话我是按照顶配来买的
This stove I bought is with the best configurations

0:03:36.825,0:03:39.925
它的价格是3800块钱左右
It's about 3,800 yuan

0:03:40.225,0:03:43.225
如果你想配置更高一点
If you want even better configurations

0:03:43.325,0:03:44.325
加两个鼓风机
For example, with two blowers

0:03:44.625,0:03:45.250
要加钱
You need to pay extra money

0:03:45.775,0:03:48.325
大概要加1000块钱
That's about 1,000 yuan

0:03:48.450,0:03:51.500
然后就是4800左右 再配上一个运费
So that's about 4,800 yuan in total, excluding the delivery charge

0:03:51.550,0:03:54.550
因为经销商它不会给你包邮的
Since the seller usually doesn't include the delivery charge in the price

0:03:54.650,0:03:56.750
因为他给你拉过来什么的都是要钱
as he must deliver it to you, which costs some money

0:03:57.025,0:03:58.625
加运费这一坨
With the delivery charge included...

0:03:58.925,0:04:02.075
我是成都买的 到我们这个地方
I bought this from Chengdu. To deliver it here,

0:04:02.525,0:04:04.200
花了800多块钱的运费
I spent about 800 yuan just for delivery

0:04:04.200,0:04:06.675
不是说你这些买回来就可以用
In addition, actually you can't use them immediately even if you have all these stuff

0:04:06.750,0:04:10.275
第一你如果是接煤气的话你要买煤气罐 对吧
For example, if you wanna use LPG, you'll also need to buy gas tanks

0:04:11.125,0:04:13.800
如果你是用天然气的话你要开户
Or, if you want to use natural gas, you need to sign a contract with some company

0:04:14.050,0:04:15.875
开户的话这个多少钱我就不知道了
I don't know how much that'll cost

0:04:15.900,0:04:17.800
然后就是可以烧环保油
You can also use eco-friendly oil instead

0:04:18.350,0:04:21.550
这三种无非就是怎么样转换呢
It's not hard to switch between different fuels

0:04:21.600,0:04:28.400
把炉心根据你用什么燃料然后就换什么炉心 很简单比较便宜
You can replace the stove core according to the type of fuel. It's simple and cheap

0:04:28.500,0:04:30.675
这是第一个气就是燃料这一块
This is the first issue. The fuel

0:04:31.100,0:04:32.250
第二的话就是电
Secondly, you need to have electricity supply

0:04:32.925,0:04:34.400
你知道这个有鼓风机对吧
You know, there's a blower

0:04:34.475,0:04:36.550
这个要拉线来接上这个鼓风机
You'll need (to buy) cables for the blower

0:04:36.600,0:04:37.525
它还要耗电
It consumes electricity as well

0:04:37.850,0:04:39.550
有了电和气还不行
Electricity and fuel supply are still not enough though

0:04:39.650,0:04:40.750
还要接上水
Water is also needed

0:04:41.175,0:04:43.375
因为这个炉的话温度比较高
Because the temperature of this stove is relatively high

0:04:43.625,0:04:45.400
你如果不放水这里两下就烧坏了
If there's no water here, it'll be burnt easily

0:04:45.450,0:04:46.100
要接上水
So you need to connect water supply as well

0:04:47.150,0:04:48.700
还有一个最重要的一个点
Moreover, the most important point

0:04:48.825,0:04:49.500
油烟机
The range hood

0:04:50.025,0:04:51.750
如果你的楼房特别高
Suppose your building is very tall

0:04:51.925,0:04:54.775
你要从一楼装一个排烟道装到楼顶
and you'll need an exhaust duct from the first floor to the roof

0:04:55.000,0:04:58.000
那这个（费用）可多可少
The price can be very high #请检查这里，按照前面的说法应该是比较高的

0:04:58.400,0:05:02.550
我做过的餐厅最贵的装一根油烟管道花了10万
In one of the restaurants that I worked in, they spent 100,000 yuan on installing an exhaust duct pipe

0:05:02.675,0:05:04.489
如果你是在自己家里面
If you want to have it in your home

0:05:04.800,0:05:06.665
就是农村的家你不能在城市里面
In the countryside, of course, not in the city

0:05:06.675,0:05:09.100
城市里面你很难弄进去
It's very hard to install this in your home in the city

0:05:09.350,0:05:10.600
然后也会非常吵
It'll also be very noisy

0:05:11.200,0:05:14.350
在自己家里面的话这一套下来
In your home... If you really want to have a whole set of these equipments

0:05:14.675,0:05:18.425
全部置办下来到你能够炒菜
In total, I mean, when you can really start cooking

0:05:19.150,0:05:22.575
我估计的话预算 大概预算是1万块钱
I think the budget will be approximately 10,000 yuan

0:05:22.950,0:05:24.600
然后我建不建议你们这么做呢
And... what do I suggest?

0:05:24.725,0:05:26.275
其实不建议你们这么做
In fact I don't suggest you to do so (have such a set in your home)

0:05:26.450,0:05:28.450
第一是价钱让你们死心
First, the price is high enough to let you give up

0:05:28.600,0:05:31.525
第二是这个操作也是让你们死心
Second, the operations are also very complicated #请检查这里，不太按照原文

0:05:31.900,0:05:33.075
然后最后一点呢
And at last,

0:05:33.325,0:05:35.150
你这些东西买回来了之后
even if you have all these

0:05:35.350,0:05:37.500
你不会用也是很麻烦的你看
It'll be a trouble if you can't use them

0:05:37.675,0:05:42.200
随便一个你炒菜必须用这个锅 家用的锅放不进去
For example, you must use this wok when cooking. The woks for family cooking cannot be used here

0:05:42.275,0:05:43.100
因为这个特别大
Also, since it's really big

0:05:43.250,0:05:46.225
放进去了之后你不可能用锅铲这样子炒
You can't use a spatula and cook as usual

0:05:46.400,0:05:49.900
而你要配上这一套技术对吧
You'll need cooking skills like this

0:05:50.425,0:05:54.825
你不可能买了这一套东西然后花个10年8年去学烹饪什么的
It's not practical that you buy such a set of equipments and spend 10 or 8 years on learning how to cook professionally

0:05:54.925,0:05:55.975
这个也不大现实
It's not realistic

0:05:56.625,0:06:03.625
所以我们大家对于说买这套炉具来自己家用的话就看一下就好啦
So for you guys, it's not recommended that you buy all these for family use

0:06:04.350,0:06:06.287
如果你们实在是想
If you really want to...

0:06:06.750,0:06:08.950
还想买的话我就建议你们
to have these in your home, I would suggest you

0:06:09.250,0:06:10.600
其实不用买双灶
You don't actually need a dual-stove cooker

0:06:10.700,0:06:13.675
有单灶的 单灶就便宜很多
There's single-stove cooker. It's much cheaper

0:06:14.100,0:06:15.250
第一呢它运费便宜
First, the delivery fee is rather low

0:06:15.300,0:06:16.925
第二呢它是买得也便宜
Second, it's cheap as well

0:06:17.250,0:06:19.225
单灶的话1000多块钱
For a single-stove cooker, it's about 1,000 yuan

0:06:19.550,0:06:20.700
它也带鼓风机
It's also with a blower

0:06:21.125,0:06:24.250
然后的话它面积就比这个小很多很多
It occupies much less area than this one

0:06:24.375,0:06:25.600
就更方便于操作
So it's easy to operate

0:06:26.075,0:06:28.229
我们买得这一套是中配
This set here is middle-end

0:06:28.650,0:06:32.900
如果你想买简约一点的可以买一个小的
You can buy a small one instead

0:06:33.100,0:06:35.928
先尝试一下能不能驾驭得了这个
and try if you can handle it

0:06:36.250,0:06:40.450
如果能驾驭得了我们以后再慢慢扩也可以
If you do, you can upgrade it gradually in the future

0:06:40.825,0:06:43.000
就是说烹饪作为一个爱好
I mean, if cooking is your hobby

0:06:43.650,0:06:47.650
我们这一套全部按照最顶格来配的话
For this set here, if all with the best configurations

0:06:48.000,0:06:50.950
不考虑油烟机大概2万块钱左右
In total it'll be about 20,000 yuan, excluding the range hood

0:06:51.325,0:06:53.075
就相当于翻了一番价格
That is, twice the price now

0:06:53.450,0:06:55.450
如果按照最简约的来配的话
If with the simplest configurations

0:06:55.600,0:06:57.000
打荷台300多
300 yuan for the spreading table

0:06:57.225,0:07:03.250
然后这个炉灶带鼓风机的单个炉灶1000多
and about 1,000 yuan for a single-stove cooker with a blower

0:07:03.950,0:07:05.375
加上菜板什么的
as well as the cutting board, etc.

0:07:05.650,0:07:07.275
所有加起来2000块钱以内
All add up below 2,000 yuan

0:07:07.650,0:07:08.550
都是OK的
That's also OK

0:07:08.975,0:07:10.525
然后也有粉丝再问
Some fans also asked

0:07:10.550,0:07:12.700
他说你买这一套来干什么呢
why I bought this set here

0:07:12.875,0:07:14.525
其实我买这一套炉具来
Actually I buy them

0:07:14.650,0:07:16.736
第一是跟大家分享它的作用
because I want to share with you how it works

0:07:17.025,0:07:21.900
可能大家没看过真正后厨的这个是怎么样子操作
Maybe you guys have never seen what it's like in real restaurant kitchens

0:07:22.300,0:07:25.750
然后呢也是从第一步炒菜跟大家分享
Also, I want to share with you from the first step of cooking

0:07:25.850,0:07:29.450
从翻锅开始到后面的我会的
From flipping food in the wok, to whatever I can

0:07:29.750,0:07:30.625
跟你们分享
I'll share with you

0:07:31.050,0:07:33.575
这就是我买这一套厨具的初衷
That's why I bought this set of equipments

0:07:34.000,0:07:35.900
好啦本期视频就到这里结束
Ok that's the end of this video

0:07:36.100,0:07:37.675
喜欢我的可以关注一下我
If you like my videos, please subscribe

0:07:37.725,0:07:41.600
后面慢慢来 我们来日方长慢慢得学
I'll share with you in the future. We still have a lot of time to learn

0:07:41.800,0:07:44.000
我也在不断的学习
I'm also learning continuously

0:07:44.325,0:07:46.000
跟大家分享更多的东西
and I'll share more with you

0:07:46.200,0:07:47.325
好啦 就到这里
Ok. That's the end

0:07:47.475,0:07:47.975
拜拜
Bye-bye!

**Comment by immoonancient** [comment]
发布了再 close 吧

**Comment by Yingzhang1122** [comment]
ok

**Comment by immoonancient** [comment]
另外现在不需要手工 close 了，bot 会 15 分钟检测一次字幕发布状况，发布了就自动 close
