### ISSUE TITLE
[华农兄弟] 大公猪 - https://youtu.be/Jzc-1x9_bd4

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#749]
https://youtu.be/Jzc-1x9_bd4
<p>&#35270;&#39057;&#21457;&#24067;&#20110; March 4, 2020 at 12:04PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by lhrotk** [comment]
认领

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/Jzc-1x9_bd4

#华农兄弟：这头大公猪最近胖了，看它趴在地上无聊，跟它聊一下
#Haunong Brothers: This big boar is getting fat recently. It looks so bored lying on the ground. Let me have a chat with it.

0:00:00.000,0:00:00.620
# 小豬
Piggy!

0:00:01.720,0:00:02.720
# 你在這裡幹嘛
What are you doing here?

0:00:04.540,0:00:05.660
# 在曬太陽嗎
Are you sunbathing?

0:00:06.020,0:00:07.060
# 現在太陽又沒有
But the sun is not shining now.

0:00:10.080,0:00:11.960
# 這條公豬很兇的  這條公豬
This boar is really fierce, this boar.

0:00:13.520,0:00:15.740
# 它還發脾氣  發脾氣竟然還交人哦  (註︰語序關係，把重覆部份換了一下)
It bites, it even bites if it loses temper.

0:00:17.640,0:00:18.180
# 是不是
Don't you?

0:00:19.060,0:00:20.260
# 不可以咬我知不知道
Do should never bite me, got it?

0:00:20.780,0:00:21.800
# 咬了我的話
If you ever dare to bite me,

0:00:23.880,0:00:25.160
# 我就把你給宰啦
I would kill you.

0:00:26.620,0:00:27.820
# 你看  這條公豬
Have a look at this boar!

0:00:28.160,0:00:29.600
# 它的腳趾是白的哦
It has white toes, see?

0:00:30.740,0:00:31.980
# 身上好多泥巴呀
It's covered with mud.

0:00:33.880,0:00:36.360
# 天氣熱得話  它會搞到泥巴上去
It always gets onto the mud when it's hot,

0:00:37.280,0:00:40.240
# 抓癢癢  那蟲子啊  蚊子啊  就咬不進它
to scratch the itch, and to prevent the bites from, you know, the bugs, and the mosquitoes.

0:00:41.020,0:00:42.020
# 皮也很厚
It has really thick skin too.

0:00:42.340,0:00:43.900
# 它現在應該一百多斤
I think it's now around, sixty, seventy,

0:00:43.980,0:00:45.160
# 一百五十斤左右  (註︰不想太麻煩註釋「斤」，把說法改一改較好看)
or seventy five kilograms.

0:00:46.680,0:00:48.980
# 還不夠胖  要把它養到五百斤
It's not fat enough. I wanna make it two hundred and fifty kilograms,

0:00:50.700,0:00:52.180
# 胖成一條豬一樣
so that it becomes as fat as a pig.

0:00:53.600,0:00:54.500
# 本來就是豬
Well, it's already a pig from day one.

0:00:56.060,0:00:57.240
# 胖成一條牛一樣
Then as fat as a cow

0:00:57.980,0:00:59.240
# 你看  它的耳朵
Look! Its ears...

0:01:00.060,0:01:01.600
# 你的耳朵用來做那個
You ears can be made into a, um,

0:01:02.300,0:01:03.860
# 涼拌耳朵很好吃的哦
cold and dressed ears. It would be really tasty.

0:01:05.740,0:01:07.080
# 它的  腿
Its...legs,

0:01:07.940,0:01:10.300
# 後腳  後腳用來做紅燒  (註︰我想他是想說「後腿」，但似乎和粵語一樣，腿腳不分)
the hind legs, the hind legs can be braised.

0:01:11.300,0:01:12.880
# 排骨用來做紅燒排骨
And the ribs, the ribs can be braised,

0:01:13.520,0:01:14.260
# 也可以烤
or grilled.

0:01:15.540,0:01:16.360
# 很好吃的
Tasty!

0:01:17.240,0:01:18.840
# 前腳就用來煲湯
A soup can be made using the forelegs.

0:01:20.200,0:01:20.700
# 那個
And then,

0:01:21.980,0:01:22.860
# 身上的肉哇
the pork on the body,

0:01:23.960,0:01:24.760
# 用來做
can be,

0:01:25.940,0:01:26.960
# 用來做那個
can be, you know,

0:01:28.360,0:01:29.240
# 炒芹菜
can be fried with celery.

0:01:31.120,0:01:32.140
# 特別是它豬肚 (註︰不明白怎麼「特別是」，不理了，直譯算了)
Especially its stomach,

0:01:32.800,0:01:33.700
# 豬肚煲雞
when stewed with chicken,

0:01:34.620,0:01:35.420
# 很補的
it's good for health.

0:01:35.940,0:01:39.080
# 到時候我殺了豬之後哇  我就搞個豬  豬雜湯
I would make a pork, pork offal soup, after slaughtering the pig.

0:01:40.640,0:01:45.100
# 就是  豬肝跟瘦肉跟豬腸混在一起 煮一鍋湯  (註︰語序長短關係，放在一起較好辦)
It's like, making a soup with the liver, lean meat, guts, everything together.

0:01:45.700,0:01:47.860
# 還小的時候每家每戶殺豬的時候哇
When I was a kid, this pork offal soup was always on the table,

0:01:48.160,0:01:49.920
# 都要吃這個豬雜湯
whenever a pig was slaughtered.

0:01:50.640,0:01:51.880
# 全村人一起吃哦
It was shared with everybody in the village.

0:01:52.020,0:01:53.980
# 等於說全村人去幫忙殺一條豬
That means, it took the whole village to slaughter a pig.

0:01:54.160,0:01:56.220
# 然後就是  煮一餐肉
And then we made a feast,

0:01:56.340,0:01:58.760
# 煮一餐那個豬肉宴大家一起吃
made a feast with the pork and enjoyed together.

0:01:59.880,0:02:01.140
# 現在  現在農村
Now, now in the villages,

0:02:01.920,0:02:04.560
# 都幾乎都看不到殺豬哇   都是進屠宰場
slaughtering of pigs is rarely seen. It's done in a slaughterhouse instead.
#https://youtu.be/Jzc-1x9_bd4

#华农兄弟：这头大公猪最近胖了，看它趴在地上无聊，跟它聊一下
#Huanong Brothers: This big boar is getting fat recently. It looks so bored lying on the ground. Let me have a chat with it.

0:02:08.620,0:02:09.920
# 哇  這個蹄子
Wa! The hoof,

0:02:10.680,0:02:11.640
# 這個蹄子用來
the hoof should be,

0:02:12.620,0:02:13.940
# 紅燒一下挺好吃
should be really tasty if it's braised.

0:02:17.900,0:02:18.460
# 干嘛
What happens?

0:02:19.760,0:02:20.340
# 哎呀
Aya!

0:02:21.020,0:02:22.080
# 我又沒說好
I was not talking about you.

0:02:23.200,0:02:24.400
# 生氣了一樣  你看
It looks angry. Look!

0:02:24.860,0:02:25.640
# 生氣了啦
Yea, it's angry,

0:02:25.660,0:02:26.400
# 想跑
and wants to run away.

0:02:27.780,0:02:29.260
# 你看 它的那個 前臂
Look! Its ah, it's forearm, 

0:02:30.020,0:02:30.900
# 好多肉哇
is so meaty!

0:02:31.500,0:02:32.820
# 刮下來全是肉  
It's covered with meat.
