### ISSUE TITLE
【美食作家王刚】苦瓜酿肉 - https://youtu.be/PTqX405aepU

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#752]
https://youtu.be/PTqX405aepU
视频时长 5:54，预计发布时间为北京时间3月7日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

标题
```
【美食作家王刚】厨师长教你：湘菜“苦瓜酿肉”的家常做法，口感和味道很棒，值得一试的好菜！
```

字幕
```
0:00:00.620,0:00:01.920
哈喽大家好 我是王刚

0:00:01.920,0:00:03.820
本期视频我跟大家分享一道家常菜

0:00:04.320,0:00:05.560
苦瓜酿肉

0:00:05.820,0:00:08.240
首先我们准备碧绿色的苦瓜两条

0:00:08.475,0:00:09.700
将苦瓜切头去尾

0:00:09.900,0:00:13.500
因为苦瓜两头比较狭小无法酿肉所以必须去除

0:00:13.625,0:00:16.075
然后将苦瓜切成1厘米左右的节备用

0:00:16.225,0:00:18.650
切好节之后用手将苦瓜中的籽去掉

0:00:18.825,0:00:21.350
苦瓜中白色的瓜瓤部分带有苦涩味

0:00:21.475,0:00:24.675
“怕吃苦”的同学可以用小刀将其全部去除干净

0:00:27.650,0:00:30.100
下一步我们开始准备苦瓜的初步处理

0:00:30.925,0:00:33.125
首先我们在锅中加入适量的清水

0:00:35.700,0:00:37.475
然后加入食用盐1大勺（约3克）

0:00:37.575,0:00:40.425
加盐的目的是防止营养流失

0:00:44.075,0:00:46.775
大火将水烧开之后再加入适量的食用油

0:00:47.600,0:00:50.125
然后将切好的苦瓜下锅焯水1分钟

0:00:50.425,0:00:53.375
加油焯水的目的是保持苦瓜成菜之后的光泽

0:00:53.600,0:00:55.700
还有一点就是防止苦瓜发黄

0:00:56.525,0:00:59.375
1分钟之后将苦瓜捞出放入冷水中浸泡

0:01:08.225,0:01:11.125
待苦瓜凉透之后捞出沥干水份备用

0:01:14.750,0:01:16.275
下一步开始准备猪肉

0:01:16.400,0:01:18.335
准备半肥瘦的五花肉1小块

0:01:18.375,0:01:20.575
去掉猪皮之后先切成片

0:01:24.250,0:01:26.150
然后再剁成肉泥备用

0:01:37.925,0:01:39.275
下一步开始调味

0:01:39.400,0:01:40.875
碗中加入食用盐1勺

0:01:41.475,0:01:42.875
加入少许胡椒粉

0:01:43.350,0:01:44.950
加入生抽酱油3克

0:01:47.200,0:01:48.575
加入少许老抽调底色

0:01:52.800,0:01:54.100
然后将猪肉搅拌均匀

0:01:54.350,0:01:56.000
这一步的目的是上劲

0:02:00.650,0:02:03.200
猪肉上劲之后再加入1个鸡蛋搅拌均匀

0:02:15.600,0:02:18.075
最后再加入少许玉米淀粉拌匀备用

0:02:28.475,0:02:29.600
下一步开始制作

0:02:29.950,0:02:32.200
首先我们在苦瓜圈中抹上干淀粉

0:02:32.275,0:02:34.275
这一步的目的是让肉泥粘的更稳

0:02:44.325,0:02:46.475
然后将调好味的肉泥酿入苦瓜中

0:02:46.575,0:02:48.525
同学们可以尽量的多加一些肉末

0:02:48.775,0:02:50.675
这样能够使苦瓜更加的饱满

0:02:55.900,0:02:58.300
然后在酿好的肉末两边粘上干淀粉备用

0:02:58.500,0:03:01.475
粘干淀粉的目的是防止两面煎的时候粘连

0:03:16.000,0:03:17.750
下一步我们开始调碗汁

0:03:17.950,0:03:19.775
碗中加入生抽酱油5克

0:03:21.375,0:03:22.750
加入蚝油3克

0:03:25.450,0:03:26.675
加入少许白糖

0:03:27.650,0:03:29.000
加入食用盐1勺

0:03:29.775,0:03:31.275
加入清汤40克

0:03:34.350,0:03:36.825
最后加入适量的干淀粉（土豆淀粉）搅拌均匀备用

0:03:39.200,0:03:40.600
下一步开始制作

0:03:40.775,0:03:42.200
首先我们把锅烧热

0:03:42.300,0:03:44.375
锅烧热之后加入适量的油滑锅

0:03:47.500,0:03:49.300
滑好锅之后将热油倒出

0:03:51.050,0:03:52.700
然后加入少许的底油

0:03:53.800,0:03:56.004
油温4成热之后依次下入苦瓜

0:04:11.250,0:04:12.975
然后开小火煎8分钟

0:04:13.075,0:04:15.500
同学们切记必须小火慢慢煎

0:04:15.650,0:04:17.800
不能开大火否则很容易煎糊

0:04:18.000,0:04:19.700
正所谓慢工出细活

0:04:19.775,0:04:21.800
中途用筷子将其翻面煎香

0:04:34.275,0:04:38.100
两面煎香之后转中火然后缓缓加入调好的碗汁

0:04:48.975,0:04:50.800
碗汁下锅之后转中小火

0:04:50.875,0:04:52.850
将汤汁收浓即可出锅装盘

0:05:18.740,0:05:22.220
一道非常美味的“生活菜”苦瓜酿肉就制作完成

0:05:26.540,0:05:49.540
下面开始技术总结
第一：必须选择绿色结实的苦瓜，这样成菜更绿
第二：焯水的时候加油、盐的目的是让苦瓜保持翠绿，同时也能够去除一些苦涩味
第三：煎制的时候必须小火慢慢煎，否则中间不容易熟
第四：最后收汁不能超过3分钟，否则成菜容易发黄
苦瓜酿肉的技术总结完毕
```

**Comment by Yibing-Du** [comment]
bot, please upload
0:00:00.620,0:00:01.920
哈喽大家好 我是王刚
Hello everyone, this is Wang Gang

0:00:01.920,0:00:03.820
本期视频我跟大家分享一道家常菜
In this video, I'll share with you an everyday dish

0:00:04.320,0:00:05.560
苦瓜酿肉
Bitter Gourd Stuffed Meat

0:00:05.820,0:00:08.240
首先我们准备碧绿色的苦瓜两条
First, prepare two green bitter gourds

0:00:08.475,0:00:09.700
将苦瓜切头去尾
Remove the two ends

0:00:09.900,0:00:13.500
因为苦瓜两头比较狭小无法酿肉所以必须去除
Since the ends are too narrow to stuff the meat in, we need to remove them

0:00:13.625,0:00:16.075
然后将苦瓜切成1厘米左右的节备用
Then cut the bitter gourd to chunks that are 1cm thick

0:00:16.225,0:00:18.650
切好节之后用手将苦瓜中的籽去掉
After cutting, remove the seeds by hand

0:00:18.825,0:00:21.350
苦瓜中白色的瓜瓤部分带有苦涩味
The white portion is bitter

0:00:21.475,0:00:24.675
“怕吃苦”的同学可以用小刀将其全部去除干净
If you don't like the bitter tast, use a knife to remove it all

0:00:27.650,0:00:30.100
下一步我们开始准备苦瓜的初步处理
Then we start preprocessing the bitter gourd

0:00:30.925,0:00:33.125
首先我们在锅中加入适量的清水
First add some water to the wok

0:00:35.700,0:00:37.475
然后加入食用盐1大勺（约3克）
Then add a large spoon of salt (around 3g)

0:00:37.575,0:00:40.425
加盐的目的是防止营养流失
Adding salt keeps the nutrition

0:00:44.075,0:00:46.775
大火将水烧开之后再加入适量的食用油
Add some oil after the water boils

0:00:47.600,0:00:50.125
然后将切好的苦瓜下锅焯水1分钟
Then add the cutted bitter gourd and parboil for a minute

0:00:50.425,0:00:53.375
加油焯水的目的是保持苦瓜成菜之后的光泽
Parboiling with oil keeps the glaze of the bitter gourd

0:00:53.600,0:00:55.700
还有一点就是防止苦瓜发黄
And prevents it from turning yellow

0:00:56.525,0:00:59.375
1分钟之后将苦瓜捞出放入冷水中浸泡
After one minute, take the bitter gourd out and place it in cold water

0:01:08.225,0:01:11.125
待苦瓜凉透之后捞出沥干水份备用
When it's completely cooled down, remove the water and set aside

0:01:14.750,0:01:16.275
下一步开始准备猪肉
Next, start preparing the pork

0:01:16.400,0:01:18.335
准备半肥瘦的五花肉1小块
Prepare a small piece of 50% lean 50% fat pork

0:01:18.375,0:01:20.575
去掉猪皮之后先切成片
Remove the skin and slice it

0:01:24.250,0:01:26.150
然后再剁成肉泥备用
Then cut it to grounded meat

0:01:37.925,0:01:39.275
下一步开始调味
Then start marinating the meat

0:01:39.400,0:01:40.875
碗中加入食用盐1勺
Add a spoon of salt to the bowl

0:01:41.475,0:01:42.875
加入少许胡椒粉
Add a little ground pepper

0:01:43.350,0:01:44.950
加入生抽酱油3克
Add 3g of soy sauce

0:01:47.200,0:01:48.575
加入少许老抽调底色
Add some dark soy sauce for the color

0:01:52.800,0:01:54.100
然后将猪肉搅拌均匀
Then mix the meat with the sauces

0:01:54.350,0:01:56.000
这一步的目的是上劲
This allows the meat to come together

0:02:00.650,0:02:03.200
猪肉上劲之后再加入1个鸡蛋搅拌均匀
Then add an egg and mix properly

0:02:15.600,0:02:18.075
最后再加入少许玉米淀粉拌匀备用
Finally add some corn starch to mix and set aside

0:02:28.475,0:02:29.600
下一步开始制作
Then start cooking

0:02:29.950,0:02:32.200
首先我们在苦瓜圈中抹上干淀粉
First, apply some starch to the inner side of the ring-shaped bitter gourds

0:02:32.275,0:02:34.275
这一步的目的是让肉泥粘的更稳
This is to allow the ground meat to stay in the ring

0:02:44.325,0:02:46.475
然后将调好味的肉泥酿入苦瓜中
Then add the marinated meat to the bitter gourds

0:02:46.575,0:02:48.525
同学们可以尽量的多加一些肉末
More meat is better

0:02:48.775,0:02:50.675
这样能够使苦瓜更加的饱满
Because it makes the final product more rich

0:02:55.900,0:02:58.300
然后在酿好的肉末两边粘上干淀粉备用
Then apply starch on the two sides of the meat

0:02:58.500,0:03:01.475
粘干淀粉的目的是防止两面煎的时候粘连
Starch prevents the two sides from sticking together when it's fried

0:03:16.000,0:03:17.750
下一步我们开始调碗汁
Next, we start to prepare the sauce

0:03:17.950,0:03:19.775
碗中加入生抽酱油5克
Add 5g of soy sauce to the bowl

0:03:21.375,0:03:22.750
加入蚝油3克
Add 3g of oyster sauce

0:03:25.450,0:03:26.675
加入少许白糖
Add a little sugar

0:03:27.650,0:03:29.000
加入食用盐1勺
Add a spoon of salt

0:03:29.775,0:03:31.275
加入清汤40克
Add 40g of clear broth

0:03:34.350,0:03:36.825
最后加入适量的干淀粉（土豆淀粉）搅拌均匀备用
Finally add some potato starch and mix it properly

0:03:39.200,0:03:40.600
下一步开始制作
Next, start pan-frying

0:03:40.775,0:03:42.200
首先我们把锅烧热
First we heat up the wok

0:03:42.300,0:03:44.375
锅烧热之后加入适量的油滑锅
When the wok is heated, add some oil to the wok

0:03:47.500,0:03:49.300
滑好锅之后将热油倒出
Then pour the oil out

0:03:51.050,0:03:52.700
然后加入少许的底油
Now add some base oil

0:03:53.800,0:03:56.004
油温4成热之后依次下入苦瓜
When it's 40% heated, add the bitter gourds one by one

0:04:11.250,0:04:12.975
然后开小火煎8分钟
Then turn to low heat for 8 minutes

0:04:13.075,0:04:15.500
同学们切记必须小火慢慢煎
Keep in mind we need low heat

0:04:15.650,0:04:17.800
不能开大火否则很容易煎糊
Because high heat easily burns the bitter gourds

0:04:18.000,0:04:19.700
正所谓慢工出细活
Patience is the best practice

0:04:19.775,0:04:21.800
中途用筷子将其翻面煎香
Midway, flip the bitter gourds to pan-fry the other side

0:04:34.275,0:04:38.100
两面煎香之后转中火然后缓缓加入调好的碗汁
When both sides are ready, turn to mid heat and slowly pour in the prepared sauce

0:04:48.975,0:04:50.800
碗汁下锅之后转中小火
Then turn to mid-low heat

0:04:50.875,0:04:52.850
将汤汁收浓即可出锅装盘
When the sauce becomes condensed, it's ready to be served

0:05:18.740,0:05:22.220
一道非常美味的“生活菜”苦瓜酿肉就制作完成
Now a delicious everyday dish, Bitter Gourd Stuffed Meat, is ready

0:05:26.540,0:05:49.540
下面开始技术总结
第一：必须选择绿色结实的苦瓜，这样成菜更绿
第二：焯水的时候加油、盐的目的是让苦瓜保持翠绿，同时也能够去除一些苦涩味
第三：煎制的时候必须小火慢慢煎，否则中间不容易熟
第四：最后收汁不能超过3分钟，否则成菜容易发黄
苦瓜酿肉的技术总结完毕
Now let's summarize the techniques
Firstly, we need to choose green and riped bitter gourds so that the product looks bright-colored
Secondly, we need to add oil and salt while parboiling to keep the bitter gourds green and remove its bitterness
Thirdly, we need to turn to low heat while pan-frying or the middle part would stay rare
Fourthly, don't boil the sauce for more than 3 minutes, or the bitter gourds would turn yellow
Above are all the techniques
