### ISSUE TITLE
[华农兄弟] 兄弟家的香菇和场地 - https://youtu.be/1ncYUCm-6mg

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#760]
https://youtu.be/1ncYUCm-6mg
<p>&#35270;&#39057;&#21457;&#24067;&#20110; March 7, 2020 at 11:41AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/1ncYUCm-6mg

#华农兄弟：看一下兄弟家的香菇，顺便参观一下他家上千亩的场地
#Huanong Brothers: Let's take a look at my buddy's shiitake mushrooms, and also his tens of hectares of land.

0:00:00.000,0:00:01.860
# 大家好  去看一下兄弟家的香菇
Hi everyone! Let's go and have a look at my buddy's shiitake mushrooms.

0:00:01.980,0:00:02.920
# 就在這下面哦
It's just down there.

0:00:03.200,0:00:04.120
# 現在都下雨啦
It's raining now.

0:00:04.280,0:00:05.340
# 下雨了也要去
But I'm still going. I don't care.

0:00:08.080,0:00:09.600
# 你看  兄弟家的鴨子
Look! My buddy's ducks.

0:00:10.960,0:00:13.180
# 都那麼大啦  那麼肥啦  也不宰  (註︰這個「宰」譯作"kill" 或"slaughter"的話有點怪，所以譯作"eat"算了)
They're so big and fat now. But he still doesn't eat them.

0:00:35.620,0:00:36.520
# 我都不認識
Can't you even recognize me?

0:00:42.440,0:00:43.160
# 不准叫
No barking!

0:00:51.820,0:00:52.320
# 你看
Look!

0:00:52.840,0:00:54.120
# 這個是花豬哦  (註︰這是這種豬的特式，我想寫清楚點)
The pigs are black-and-white.

0:00:55.200,0:00:55.860
# 巴拿馬  (註︰救命，他不是第一次口誤了，這種豬叫「巴馬香豬」，但他總說錯成「巴拿香豬」、「巴拿馬豬」之類)
Panama (speech error of "bama pigs")

0:00:56.960,0:00:58.280
# 嗯 還有幾條黑豬
Um! There are several black pigs too.

0:01:10.200,0:01:12.920
# 兄弟這裡  上千畝的那個平地喲  (註︰不再太多註譯了，用簡單的方法另大家明白很大就算了，而且其實亦沒錯)
My buddy has tens of hectares of land here.

0:01:13.240,0:01:14.260
# 這裡一挖就挖開啦  (註︰「挖」是指挖山)
He opened up the land himself.

0:01:14.260,0:01:16.540
# 你看 這裡種的臍橙也有  鴨子也有
Look! Here are navel oranges, and also ducks.

0:01:16.900,0:01:18.860
# 這個廠也有  下面還有養豬的(註︰「廠」是經常出現的字，找不到一個很好的翻譯，就是大本營之類的建築物)
Here's a building, and a pigsty down there.

0:01:19.340,0:01:20.720
# 上面還有  還有廠房
And also up there. There are also some buildings.

0:01:20.920,0:01:22.840
# 放東西的  還有住人的就在上面
They are for storage. The living quarters are also up there.

0:01:23.320,0:01:24.600
# 我們去看一下   在上面
Let's take a look, up there.

0:01:29.700,0:01:31.000
# 坐下去  快點  坐下去
Sit down! C'mon, sit down!

0:01:31.340,0:01:32.700
# 誒  坐下去
Eh? Sit down!

0:01:33.060,0:01:34.160
# 這麼聽話的這條狗
What a good dog!

0:01:34.700,0:01:35.900
# 好聽話的這條狗
It's such a good dog.

0:01:36.700,0:01:37.340
# 小狗
Doggy!

0:01:39.380,0:01:41.080
# 對啊  坐下去  不要動哦
Yea, right! Sit down, and don't move!

0:01:45.180,0:01:46.900
# 走  走  跟我來
Go, go! Follow me!

0:01:47.080,0:01:49.380
# 你看  兄弟家種了  種了很多這個臍橙哦  (註︰加一個"tree"，令下句翻譯更自然)
Look! My buddy has planted, planted a lot of, you know, navel orange trees.

0:01:49.920,0:01:53.000
# 差不多種了四五千棵啊  這個臍橙  到處都是
He has planted thousands of them, I mean the navel orange trees. They're everywhere,

0:01:53.240,0:01:54.240
# 那上面還有一大片
and also a whole lot of land up there.

0:01:54.240,0:01:55.480
# 等一下我們到上面去看一下
We're gonna go up there and have a look in a while.

0:01:56.100,0:01:57.360
# 這邊  這邊也開花啦
These, these have already blossomed.

0:01:57.680,0:01:58.560
# 應該可以摘啦  (註︰他應該是想說「應該快有臍橙結果可以摘」，不然摘橙樹的花幹啥， 但我不幫他解譯了....)
I think they can be picked.

0:01:58.660,0:02:00.360
# 兩年多啦  應該可以
It's like, more than two years already. I think we can,

0:02:00.860,0:02:02.680
# 留幾個來  留幾個來吃
reserve a couple, reserve a couple for ourselves.

0:02:05.140,0:02:06.100
# 這棵也開花啦
This tree has also blossomed.

0:02:09.220,0:02:11.100
# 你看  那一大片都是臍橙樹
Look! All those are navel orange trees over there.

0:02:11.820,0:02:13.440
# 兄弟家有豬  豬在這裡
And my buddy's pigs, the pigs are there.

0:02:13.640,0:02:15.980
# 那邊  那  那  那裡是可以住人哦
Tha... that, that, that building can be used for accommodation.

0:02:17.520,0:02:18.700
# 這裡以前都是山
Here used to be hills and only hills.

0:02:18.720,0:02:21.080
# 都被兄弟把它挖  挖出來啦
But my buddy opened, opened it up.

0:02:21.540,0:02:22.860
# 我去看一下兄弟家的香菇
Let me take a look at my buddy's shiitake mushrooms.

0:02:23.000,0:02:24.740
# 那裡有一點點香菇  我們去看一下
There's a tiny little bit mushrooms. Let's take a look.

0:02:27.980,0:02:29.380
# 我們看上面有沒有
Let's see if there's any,

0:02:29.720,0:02:30.700
# 好東西吃
good food up there.

0:02:43.320,0:02:44.700
# 兄弟還有後花園哦
My buddy has a backyard too.

0:02:45.240,0:02:46.920
# (兄)[SIC]種了好多菜  好多花
He has planted a lot of veggies, and a lot flowers here.

0:02:47.460,0:02:48.500
# 這是油菜花
This is rapeseed,

0:02:49.340,0:02:49.940
# 包菜
and cabbages.

0:03:01.300,0:03:02.360
# 這裡面好多哇
There are a lot inside.

0:03:02.780,0:03:04.860
# 他這個到處都是香菇 他放的
The mushrooms are everywhere here. He has put them everywhere.

0:03:04.900,0:03:07.100
# 上  上面還有很多  等下我帶大家去看一下
There, there are a lot more up there. I'll show you in a while.

0:03:07.760,0:03:09.080
# 進裡面去看下
Let's take a look inside,

0:03:09.480,0:03:09.980
# 現在
now.

0:03:12.300,0:03:12.960
# 哇
Wa!

0:03:13.960,0:03:15.100
# 很漂亮哦 這些香菇
These mushrooms are really pretty.

0:03:15.140,0:03:17.740
# 這些都是超大啦  超標啦 他都不摘
These are too big. They're already oversize. But he didn't pick them.

0:03:18.380,0:03:19.060
# 太懶啦
He's far too lazy.

0:03:19.980,0:03:20.700
# 那邊還有
And there too

0:03:21.600,0:03:22.540
# 到處都是
Everywhere

0:03:26.980,0:03:27.840
# 到處都是
Everywhere

0:03:29.300,0:03:31.100
# 這裡也是  你看  這裡
Here too. Look! Here.

0:03:33.940,0:03:34.860
# 這上面還有哦
And also up there

0:03:49.320,0:03:51.240
# 你看  這個很漂亮的哦  這個香菇
Look! It's really pretty, this mushroom.

0:03:52.060,0:03:53.080
# 都摘了好多啦
He has already picked a lot.

0:03:53.300,0:03:55.220
# 前兩天他還摘了千多斤 這個
He picked hundreds of kilograms here, a couple of days ago.

0:03:58.340,0:04:00.700
# 現在等一下  這場雨下完之後哇
And now, another hundreds of kilograms might be coming out,

0:04:00.740,0:04:02.380
# 又可能又有一千多斤出來
in a while, after the rain.

0:04:02.640,0:04:03.520
# 很快的這個
It grows really fast.

0:04:03.700,0:04:04.600
# 一下雨就很多
There are always a lot whenever is rains.

0:04:04.820,0:04:08.260
# 要是乾  樹 很乾燥的天氣反而沒有(註︰那個「樹」應該是「燥」的誤讀而已)
There's hardly any if it's jai...I mean, if it's dry.

0:04:08.680,0:04:10.700
# 它就要潮濕的天氣  它就長很多出來
It grows a lot when the humidity is high.

0:04:12.460,0:04:14.900
# 這邊只是一點點  上面還有好多哇
Here's only a tiny little bit. There are much more up there.

0:04:18.260,0:04:19.440
# 你看 到處都是
Look! The mushrooms are everywhere.

0:04:19.980,0:04:21.000
# 摘他都不想摘
He is already tired to picking them.

0:04:21.280,0:04:22.380
# 摘的他手都乾
It hurts his hands.

0:04:24.440,0:04:25.840
# 叫我來幫你摘呀
Why didn't you ask for my help?

0:04:28.840,0:04:30.300
# 再去另外一個地方看一下
Let's have a look at another place.

0:04:30.580,0:04:31.560
# 就從這裡上去
Let's go up this way.

0:04:32.080,0:04:33.420
# 上面還有好多香菇哦
There are also a lot of mushrooms.

0:04:39.020,0:04:39.900
# 這公雞
Roosters

0:05:04.320,0:05:05.760
# 你看  這裡好多哇
Look! Here are a lot!

0:05:10.140,0:05:11.080
# 這有這個樹欄
Here's a wooden handrail. 

0:05:12.300,0:05:13.400
# 可以喲搞得
Well, it's not bad!

0:05:15.640,0:05:17.580
# 兄弟全部把它摘啦  就還有一點點
My buddy has picked all, except a tiny little bit.

0:05:17.640,0:05:19.000
# 你看 我都只看到幾個
Look! I can see only a few here.

0:05:19.820,0:05:20.880
# 都被他們在摘完啦
They've already picked everything.

0:05:21.660,0:05:23.100
# 看一下上面  上面還有哦
Let's take a look up there. There are still more.

0:05:26.300,0:05:28.300
# 這些 你看  這個  做了一個樹欄
This is, look! This is, a wooden handrail.

0:05:28.480,0:05:29.460
# 這滑滑的  這裡
It's a bit slippery here.

0:05:34.380,0:05:35.840
# 你看  這還有一個山塘
Look! Here's a wild pond too.

0:05:36.620,0:05:37.740
# 裡面好多魚的哦
There are a lot of fish, you know.

0:05:39.840,0:05:41.540
# 你看  這裡還有一大片果園
Look! There's also a huge orchard,

0:05:41.840,0:05:43.060
# 往裡面進去都是
from here all the way inside.

0:05:43.820,0:05:45.100
# 天晴的時候我們再來
Let's come again on a sunny day,

0:05:45.580,0:05:46.440
# 摘點香菇
and pick some mushrooms.

0:05:48.720,0:05:50.320
# 這個地方實在太大啦
This place is simply enormous.

0:05:50.500,0:05:53.080
# 最少  真的上千畝哇  到處都是
It's at least, really, tens of hectares, the whole area.

0:05:53.460,0:05:55.040
# 反正我  下面我還沒走哦
I ah, I haven't been down there,

0:05:55.240,0:05:57.620
# 這上面我還沒走  我只是在中間這一段
and neither up there. We've always been here in the middle.

0:05:58.300,0:06:00.700
# 啊  現在兩腿發軟啦  我要回去啦
Ah! Now my legs are fatigue. I need to go back.

0:06:01.160,0:06:02.940
# 不然晚上都  腳都會發抖的
Otherwise, my legs would be trembling tonight.

0:06:04.660,0:06:06.660
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.
