### ISSUE TITLE
【美食作家王刚】椒盐虾 - https://youtu.be/bl5E6lx8HRY

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#773]
【美食作家王刚】厨师长教你：“椒盐虾”的粤式做法，口感酥脆，就是这个味道！内附“椒盐”做法 - https://youtu.be/bl5E6lx8HRY
视频时长 5:05，预计发布时间为北京时间3月12日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.100,0:00:02.125
首先我们准备鲜虾500克

0:00:02.300,0:00:05.200
同学们最好选择鲜活的虾勿用死虾

0:00:05.350,0:00:06.875
下一步开始准备辅料

0:00:06.900,0:00:10.050
准备生姜和大蒜各20克切成片之后剁碎备用

0:00:10.050,0:00:11.893
同学们切记姜蒜不能用刀拍

0:00:12.325,0:00:13.765
否则很容易出水

0:00:15.100,0:00:17.975
准备大红椒和青椒各小半个切成小粒备用

0:00:18.175,0:00:20.737
加青红椒的目的是给菜品配红绿色

0:00:20.925,0:00:23.700
然后将切好的青红椒粒和姜蒜放在一起

0:00:30.400,0:00:32.825
准备洋葱1小片切成小颗粒备用

0:00:32.875,0:00:35.275
加洋葱粒的目的是增加葱香味

0:00:37.625,0:00:39.625
最后准备几根小葱头切碎备用

0:00:41.125,0:00:42.625
下一步开始制作椒盐

0:00:42.825,0:00:44.525
碗中加入适量的食用盐（约80克）

0:00:46.575,0:00:47.825
加入八角1颗

0:00:47.975,0:00:50.225
同学们必须将中间的八角籽去除

0:00:50.450,0:00:52.600
这样可以防止椒盐产生苦涩味

0:00:55.775,0:00:57.625
碗中加入适量的干辣椒（约10克）

0:00:58.075,0:00:59.575
加入适量的青花椒（约3克）

0:01:00.575,0:01:01.975
加入适量的白胡椒（约5克）

0:01:02.100,0:01:03.450
下一步开始炒椒盐

0:01:03.875,0:01:05.275
首先我们把锅烧热

0:01:05.425,0:01:07.975
锅烧热之后将配好比例的盐下锅

0:01:09.200,0:01:11.125
然后转中小火翻炒10分钟

0:01:11.375,0:01:13.600
这一步的目的是将盐和香料炒香

0:01:14.475,0:01:16.002
10分钟之后将其取出

0:01:18.850,0:01:20.650
然后放入石臼中捣碎备用

0:01:20.850,0:01:23.275
同学们在捣碎的过程中必须戴好口罩

0:01:23.475,0:01:25.250
否则眼泪和鼻涕不断

0:01:28.550,0:01:30.900
中途再加入适量的味精拌匀即可

0:01:31.050,0:01:33.100
不喜欢味精的同学可以不加

0:01:38.125,0:01:40.251
椒盐倒出之后下一步开始制作

0:01:41.725,0:01:44.850
首先我们在锅中加入适量的清水开大火烧开

0:01:51.525,0:01:54.225
大火烧开之后将鲜虾下锅焯水断生

0:01:56.025,0:01:58.275
中途加入适量的料酒去除腥味

0:02:04.675,0:02:07.150
等待虾背弯曲之后即可倒出备用

0:02:09.175,0:02:11.000
然后我们再次把锅烧热

0:02:11.050,0:02:13.300
锅烧热之后举盆之力加入宽油

0:02:19.625,0:02:21.975
然后大火将油温烧至6成热

0:02:26.300,0:02:28.875
中途抓1大把土豆淀粉将虾拌匀

0:02:29.000,0:02:31.625
加淀粉裹虾的目的是让其外酥里嫩

0:02:34.900,0:02:38.950
油温6成热之后将裹好淀粉的虾依次下入锅中炸至定型

0:02:50.700,0:02:52.650
鲜虾定型之后捞出备用

0:02:58.750,0:03:00.875
然后用细漏将残渣打捞干净

0:03:01.000,0:03:04.950
这一步的目的是防止残渣炸糊导致宽油提前报废

0:03:06.625,0:03:08.975
然后转大火将油温升至7成热

0:03:13.025,0:03:15.975
油温7成热之后将鲜虾下锅复炸30秒钟

0:03:23.550,0:03:25.425
复炸30秒之后捞出备用

0:03:32.425,0:03:35.050
将残渣清理干净之后再把宽油倒出

0:03:43.600,0:03:46.700
然后将切好的辅料全部下锅开中火爆香（姜蒜，辣椒，葱粒）

0:03:55.725,0:03:58.025
料头爆香之后加入炸好的鲜虾

0:03:59.850,0:04:01.600
鲜虾下锅之后开始调味

0:04:01.950,0:04:03.575
锅中加入适量的椒盐粉（约4.5克）

0:04:14.250,0:04:16.900
然后转小火翻炒几下即可出锅装盘

0:04:27.920,0:04:30.500
一道外酥里嫩的椒盐虾就制作完成

0:04:37.620,0:05:00.440
下面开始技术总结
第一，鲜虾可以不用开背
第二，捣碎椒盐的时候必须戴口罩
第三，嫌麻烦的同学可以直接在超市购买成品椒盐
第四，自制椒盐比商品椒盐更有味道且更香
第五，不喜欢椒盐中的味精可以不加
第六，加淀粉炸虾的目的是防止成菜回软
椒盐虾的技术总结完毕

**Comment by Yibing-Du** [comment]
认领

**Comment by Yibing-Du** [comment]
Bot, please upload
0:00:00.100,0:00:02.125
首先我们准备鲜虾500克
First, prepare 500g of shrimps

0:00:02.300,0:00:05.200
同学们最好选择鲜活的虾勿用死虾
We should use fresh shrimps instead of dead ones

0:00:05.350,0:00:06.875
下一步开始准备辅料
Next, start preparing the minor ingredients

0:00:06.900,0:00:10.050
准备生姜和大蒜各20克切成片之后剁碎备用
Prepare ginger and garlic, 20g each, slice them and mince them

0:00:10.050,0:00:11.893
同学们切记姜蒜不能用刀拍
Remember not to crack them with knives

0:00:12.325,0:00:13.765
否则很容易出水
Or else the juice comes out

0:00:15.100,0:00:17.975
准备大红椒和青椒各小半个切成小粒备用
Perpare halves of red and green bell peppers and dice them

0:00:18.175,0:00:20.737
加青红椒的目的是给菜品配红绿色
Adding bell peppers would add red and green colors to the dish

0:00:20.925,0:00:23.700
然后将切好的青红椒粒和姜蒜放在一起
Then put the prepared bell peppers, ginger, and garlic together

0:00:30.400,0:00:32.825
准备洋葱1小片切成小颗粒备用
Prepare a small piece of onion and dice it

0:00:32.875,0:00:35.275
加洋葱粒的目的是增加葱香味
This adds the onion flavor to the dish

0:00:37.625,0:00:39.625
最后准备几根小葱头切碎备用
Then mince a few scallions and set them aside

0:00:41.125,0:00:42.625
下一步开始制作椒盐
Next prepare the salt and pepper mixture

0:00:42.825,0:00:44.525
碗中加入适量的食用盐（约80克）
Add some salt to the bowl (around 80g)

0:00:46.575,0:00:47.825
加入八角1颗
Add one star anise

0:00:47.975,0:00:50.225
同学们必须将中间的八角籽去除
We need to remove the seeds

0:00:50.450,0:00:52.600
这样可以防止椒盐产生苦涩味
So that the salt and pepper mixture wouldn't be bitter

0:00:55.775,0:00:57.625
碗中加入适量的干辣椒（约10克）
Add some dried chili pepper to the bowl (around 10g)

0:00:58.075,0:00:59.575
加入适量的青花椒（约3克）
Add some Sichuan green peppercorn (around 3g)

0:01:00.575,0:01:01.975
加入适量的白胡椒（约5克）
Add some white pepper (around 5g)

0:01:02.100,0:01:03.450
下一步开始炒椒盐
Next, stir-fry the salt and pepper mixture

0:01:03.875,0:01:05.275
首先我们把锅烧热
First, we heat up the wok

0:01:05.425,0:01:07.975
锅烧热之后将配好比例的盐下锅
When the wok is heated, put in the salt mixture

0:01:09.200,0:01:11.125
然后转中小火翻炒10分钟
Then turn to medium-low heat and stir-fry for 10 minutes

0:01:11.375,0:01:13.600
这一步的目的是将盐和香料炒香
This is to bring out the fragrant smell of salt and spices

0:01:14.475,0:01:16.002
10分钟之后将其取出
Take it out after 10 minutes

0:01:18.850,0:01:20.650
然后放入石臼中捣碎备用
And then ground it in quern-stones

0:01:20.850,0:01:23.275
同学们在捣碎的过程中必须戴好口罩
Make sure to wear a mask when you do it

0:01:23.475,0:01:25.250
否则眼泪和鼻涕不断
Or you will tear up and develop a running nose

0:01:28.550,0:01:30.900
中途再加入适量的味精拌匀即可
Add some chicken essence midway

0:01:31.050,0:01:33.100
不喜欢味精的同学可以不加
If you don't like it, don't add it

0:01:38.125,0:01:40.251
椒盐倒出之后下一步开始制作
Pour the mixture out for the next step

0:01:41.725,0:01:44.850
首先我们在锅中加入适量的清水开大火烧开
First we add some water to the wok and boil it with high heat

0:01:51.525,0:01:54.225
大火烧开之后将鲜虾下锅焯水断生
When the water boils, parboil the shrimps

0:01:56.025,0:01:58.275
中途加入适量的料酒去除腥味
Add some cooking wine midway to remove the fishy taste

0:02:04.675,0:02:07.150
等待虾背弯曲之后即可倒出备用
When the shrimps bend, they're ready to be taken out

0:02:09.175,0:02:11.000
然后我们再次把锅烧热
Then we heat the wok up again

0:02:11.050,0:02:13.300
锅烧热之后举盆之力加入宽油
When it's heated, add Kuang You

0:02:19.625,0:02:21.975
然后大火将油温烧至6成热
Then heat the oil up to 60% with high heat

0:02:26.300,0:02:28.875
中途抓1大把土豆淀粉将虾拌匀
Add a handful of potato starch to mix with the shrimp

0:02:29.000,0:02:31.625
加淀粉裹虾的目的是让其外酥里嫩
Adding starch to shrimps makes them crispy on the outside and tender on the inside

0:02:34.900,0:02:38.950
油温6成热之后将裹好淀粉的虾依次下入锅中炸至定型
When the oil is 60% heated, add the shrimps one by one to the wok and fry them

0:02:50.700,0:02:52.650
鲜虾定型之后捞出备用
After deep frying, take the shrimps out

0:02:58.750,0:03:00.875
然后用细漏将残渣打捞干净
And use a strainer to remove the remainders from the wok

0:03:01.000,0:03:04.950
这一步的目的是防止残渣炸糊导致宽油提前报废
This is to prevent the remainders from being over-fried and shortening the lifespan of Kuan You

0:03:06.625,0:03:08.975
然后转大火将油温升至7成热
Then turn to high heat till the oil is 70% heated

0:03:13.025,0:03:15.975
油温7成热之后将鲜虾下锅复炸30秒钟
After the oil is 70% heated, deep-fry the shrimps again for 30s

0:03:23.550,0:03:25.425
复炸30秒之后捞出备用
After frying for 30s, take them out

0:03:32.425,0:03:35.050
将残渣清理干净之后再把宽油倒出
Remove the remainders once again and pour the Kuan You out

0:03:43.600,0:03:46.700
然后将切好的辅料全部下锅开中火爆香（姜蒜，辣椒，葱粒）
Then add all precut ingredients to stir-fry in the wok with medium heat (ginger, garlic, chili pepper, and scallions)

0:03:55.725,0:03:58.025
料头爆香之后加入炸好的鲜虾
When they're ready, add the fried shrimps

0:03:59.850,0:04:01.600
鲜虾下锅之后开始调味
After adding the shrimps into the wok, start seasoning

0:04:01.950,0:04:03.575
锅中加入适量的椒盐粉（约4.5克）
Add some salt pepper mixture (around 4.5g)

0:04:14.250,0:04:16.900
然后转小火翻炒几下即可出锅装盘
Then turn to low heat and stir fry for a bit before it's ready to be served

0:04:27.920,0:04:30.500
一道外酥里嫩的椒盐虾就制作完成
We've finished making the salt-pepper shrimps that is crispy on the outside and tender on the inside

0:04:37.620,0:05:00.440
下面开始技术总结
第一，鲜虾可以不用开背
第二，捣碎椒盐的时候必须戴口罩
第三，嫌麻烦的同学可以直接在超市购买成品椒盐
第四，自制椒盐比商品椒盐更有味道且更香
第五，不喜欢椒盐中的味精可以不加
第六，加淀粉炸虾的目的是防止成菜回软
椒盐虾的技术总结完毕
Now we summarize the techniques
First, we don't need to cut fresh shrimps open on the back
Secondly, wear masks when you ground the salt-pepper mixture
Thirdly, if it's too much, you can buy salt-pepper mixture from the supermarket
Fourthly, homemade salt-pepper mixture tastes better
Fifthly, if you don't like chicken essence, don't add it
Sixthly, adding starch to the shrimps prevent them from becoming sloppy when being served
Above is all the techniques for the salt-pepper shrimps
