### ISSUE TITLE
【美食作家王刚】芋儿烧鸡 - https://youtu.be/XrPk__AeWrU

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#777]
https://youtu.be/XrPk__AeWrU
视频时长 5:04，预计发布时间为北京时间3月15日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

标题
```
【美食作家王刚】厨师长教你：“芋儿烧鸡”“土豆烧鸡”的家常做法，芋头和土豆超级好吃，一锅够全家人吃！
```

字幕
```
0:00:00.050,0:00:02.250
今天我们把这个公鸡把它剁了

0:00:02.250,0:00:03.940
是个我们这里的土鸡

0:00:04.175,0:00:05.391
我们先把它剁一下

0:00:06.775,0:00:09.350
剁鸡也是从中间开始剁

0:00:11.550,0:00:13.600
一般烧的鸡我们就剁大块一点

0:00:15.075,0:00:19.750
大家可以看一下这两个是鸡的腰子 据说是大补

0:00:20.488,0:00:22.863
然后就不用改刀 改了刀它就烂了

0:00:22.863,0:00:24.413
就直接放在里面一起烧

0:00:24.413,0:00:26.513
这个是它的消化的东西

0:00:26.688,0:00:30.513
切这个鸡胗的时候不要切这边 这边是筋

0:00:30.588,0:00:34.113
你必须切这一面它才会散花 才会这样子散开

0:00:34.238,0:00:35.513
切这一面是不会散开的

0:00:35.663,0:00:37.713
而且切这一面非常的丑

0:00:38.538,0:00:41.988
然后我们一刀一刀地切下去 不要切断

0:00:42.638,0:00:45.263
刚好切到那一面白色的位置

0:00:45.663,0:00:47.588
看到没中间是白色的东西

0:00:48.313,0:00:52.338
然后再横过来再切 切进去

0:00:54.313,0:00:58.638
待会儿它熟了过后这个就收缩起来像一朵花一样

0:01:00.163,0:01:03.438
这个鸡胗这样子切出来口感非常的好

0:01:04.813,0:01:06.113
四伯爷 你看

0:01:06.238,0:01:07.488
跟汤圆儿一样噶

0:01:07.538,0:01:10.438
人家不晓得的以为这个是鸡蛋 以为这个是土鸡蛋

0:01:10.988,0:01:12.613
看到没 还有这个白的

0:01:12.863,0:01:16.038
大家看得到吗 这个小土豆

0:01:16.613,0:01:19.113
然后这个是芋头 小芋头

0:01:19.513,0:01:21.388
待会儿烧公鸡就用这个来烧

0:01:21.638,0:01:26.038
这个大蒜就对半切 切了煮一下方便你们等会儿拈来吃

0:01:26.388,0:01:28.088
这蒜整耙了好干（吃）

0:01:36.738,0:01:44.763
这个吃辣点跟中辣两个 吃特辣就要冬天越辣越安逸

0:01:45.313,0:01:48.163
这个时候安 吃中辣是最合适的

0:01:48.713,0:01:50.038
四伯爷还会吃安

0:01:50.213,0:01:51.463
要根据天气

0:01:52.788,0:01:53.963
我说你还多会吃安

0:01:54.063,0:01:56.263
嗨 这些东西都想不到啊

0:02:00.688,0:02:03.013
诶 好久你又做泡海椒安

0:02:03.588,0:02:05.220
要下半年去了都嘛

0:02:05.238,0:02:07.913
下半年去了噶 下半年我们一起做嘛

0:03:40.149,0:03:43.156
撒点香菜就可以吃了

0:03:44.951,0:03:47.665
这个土豆你看 筷子都夹得耙

0:03:48.166,0:03:50.963
你想嘛 是你师父亲自做得咋不好吃嘛

0:03:51.089,0:03:52.759
看 我们这个土豆（好软）

0:03:53.469,0:03:55.682
等我学会了我做给你吃四伯爷

0:03:55.682,0:03:58.187
好嘛好嘛 你把技术学都来做给我吃嘛

0:03:59.690,0:04:01.360
你跟你师父两个比哈嘛

0:04:01.861,0:04:04.659
我才不跟他比呢 我不敢

0:04:04.700,0:04:05.702
不敢哇

0:04:06.287,0:04:07.456
我不配

0:04:08.166,0:04:09.586
你学会了还是可以

0:04:11.047,0:04:15.932
下次你整点土豆烧点排骨跟我吃嘛

0:04:16.183,0:04:16.809
要得啊

0:04:16.934,0:04:20.567
那个东西烧起还不是好吃啊 安逸得很

0:04:20.817,0:04:25.535
弄个子四伯爷 二回你出排骨我出土豆 嘿嘿

0:04:25.619,0:04:29.419
要的啊 我们两爷子我吃点亏不关事的

0:04:30.588,0:04:32.341
我们吃排骨不吃亏

0:04:32.717,0:04:34.304
我出嘴巴就要得了哈四伯爷

0:04:34.429,0:04:35.139
好

0:04:37.059,0:04:38.771
土鸡是不一样

0:04:40.024,0:04:44.951
三黄鸡 二代鸡都没得这个土鸡好吃

0:04:45.744,0:04:47.581
嗯 这个芋头比土豆好吃

0:04:47.748,0:04:49.753
真的啊 我没尝
```

**Comment by immoonancient** [comment]
@iamatrollatrollisme 请前来认领谢谢

**Comment by iamatrollatrollisme** [comment]
我来了

（这算认领了吗）

**Comment by iamatrollatrollisme** [comment]
认领

**Comment by immoonancient** [comment]
bot 出 bug 了...?

**Comment by iamatrollatrollisme** [comment]
呵呵，我看不懂。。

**Comment by immoonancient** [comment]
@iamatrollatrollisme 已经认领成功了，按照上面提示的步骤继续做就可以了

bot 出了点 bug 我待会修了 😂

**Comment by iamatrollatrollisme** [comment]
0:00:00.050,0:00:02.250
今天我们把这个公鸡把它剁了
Today we are going to chop this rooster

0:00:02.250,0:00:03.940
是个我们这里的土鸡
This is our own free range chicken

0:00:04.175,0:00:05.391
我们先把它剁一下
Let’s chop a big cut

0:00:06.775,0:00:09.350
剁鸡也是从中间开始剁
Chop the chicken into pieces from the middle

0:00:11.550,0:00:13.600
一般烧的鸡我们就剁大块一点
Since we are going to braise the chicken we can chop them into bigger pieces

0:00:15.075,0:00:19.750
大家可以看一下这两个是鸡的腰子 据说是大补
Let’s take a look, this is the chicken’s kidneys, I heard they are very nutritious

0:00:20.488,0:00:22.863
然后就不用改刀 改了刀它就烂了
And then no need to cut it, otherwise it will dissolve in the stew

0:00:22.863,0:00:24.413
就直接放在里面一起烧
Just dump them into the stew

0:00:24.413,0:00:26.513
这个是它的消化的东西
This is what the chicken digested

0:00:26.688,0:00:30.513
切这个鸡胗的时候不要切这边 这边是筋
Don’t cut this side of the chicken gizzard while slicing it, this side is the tendon

0:00:30.588,0:00:34.113
你必须切这一面它才会散花 才会这样子散开
You need to slice this side, so it will shrink and spread out like this 

0:00:34.238,0:00:35.513
切这一面是不会散开的
Slicing from this side will not spread out

0:00:35.663,0:00:37.713
而且切这一面非常的丑
And it will look very ugly if slicing from this side

0:00:38.538,0:00:41.988
然后我们一刀一刀地切下去 不要切断
Now we are slicing it slowly, don’t cut through

0:00:42.638,0:00:45.263
刚好切到那一面白色的位置
Stop slicing when you reach the white part

0:00:45.663,0:00:47.588
看到没中间是白色的东西
You see this white strip in the middle

0:00:48.313,0:00:52.338
然后再横过来再切 切进去
Then turn it and slice again

0:00:54.313,0:00:58.638
待会儿它熟了过后这个就收缩起来像一朵花一样
Once it’s cooked it will shrink and spread out like flower blossom

0:01:00.163,0:01:03.438
这个鸡胗这样子切出来口感非常的好
Cut the gizzard this way the texture will be satisfying

0:01:04.813,0:01:06.113
四伯爷 你看
Uncle Four, check it out

0:01:06.238,0:01:07.488
跟汤圆儿一样噶
They look like Tangyuan

0:01:07.538,0:01:10.438
人家不晓得的以为这个是鸡蛋 以为这个是土鸡蛋
People who don’t know might think these are eggs, they might think these are our farm eggs

0:01:10.988,0:01:12.613
看到没 还有这个白的
You see this one, it’s white

0:01:12.863,0:01:16.038
大家看得到吗 这个小土豆
Let’s see, this is mini potato

0:01:16.613,0:01:19.113
然后这个是芋头 小芋头
And this one is taro, mini taro

0:01:19.513,0:01:21.388
待会儿烧公鸡就用这个来烧
We will braise the rooster with these

0:01:21.638,0:01:26.038
这个大蒜就对半切 切了煮一下方便你们等会儿拈来吃
We are cutting the garlic in half, easier to grab to eat later

0:01:26.388,0:01:28.088
这蒜整耙了好干（吃）
You gotta cook the garlic soft for it to taste good

0:01:36.738,0:01:44.763
这个吃辣点跟中辣两个 吃特辣就要冬天越辣越安逸
We normally eat two type of spicy, medium hot and extra spicy, it's better to eat extra spicy in winter, the spicier dishes are in winter, the more comfortable we are

0:01:45.313,0:01:48.163
这个时候安 吃中辣是最合适的
This time of the year, medium hot is the best

0:01:48.713,0:01:50.038
四伯爷还会吃安
Uncle Four you know your food

0:01:50.213,0:01:51.463
要根据天气
Gotta eat according to the weather

0:01:52.788,0:01:53.963
我说你还多会吃安
That’s why I said you know your food

0:01:54.063,0:01:56.263
嗨 这些东西都想不到啊
Oh well there are many things you can’t even think of

0:02:00.688,0:02:03.013
诶 好久你又做泡海椒安
Oh when are you making pickled chili pepper

0:02:03.588,0:02:05.220
要下半年去了都嘛
Later half of the year

0:02:05.238,0:02:07.913
下半年去了噶 下半年我们一起做嘛
Okay, later, later we can make it together

0:03:40.149,0:03:43.156
撒点香菜就可以吃了
Garnish with some cilantro we can eat it now

0:03:44.951,0:03:47.665
这个土豆你看 筷子都夹得耙
Check out this potatoes, it’s soft that I can cut it in half with my chopsticks

0:03:48.166,0:03:50.963
你想嘛 是你师父亲自做得咋不好吃嘛
Think about it, your teacher made this himself, how can it be bad

0:03:51.089,0:03:52.759
看 我们这个土豆（好软）
See, this potato is so soft

0:03:53.469,0:03:55.682
等我学会了我做给你吃四伯爷
When I learn how to cook this I will make it for you Uncle Four

0:03:55.682,0:03:58.187
好嘛好嘛 你把技术学都来做给我吃嘛
Okay fine, learn the skill and cook for me

0:03:59.690,0:04:01.360
你跟你师父两个比哈嘛
And compete with your teacher

0:04:01.861,0:04:04.659
我才不跟他比呢 我不敢
I am not going to compete with him, I don’t think I can

0:04:04.700,0:04:05.702
不敢哇
I am too scared to

0:04:06.287,0:04:07.456
我不配
I do not deserve to

0:04:08.166,0:04:09.586
你学会了还是可以
If you learn how to cook you can

0:04:11.047,0:04:15.932
下次你整点土豆烧点排骨跟我吃嘛
Next time can you braise some potatoes with ribs for me

0:04:16.183,0:04:16.809
要得啊
Sure

0:04:16.934,0:04:20.567
那个东西烧起还不是好吃啊 安逸得很
Braising those together is very tasty, feel good about it

0:04:20.817,0:04:25.535
弄个子四伯爷 二回你出排骨我出土豆 嘿嘿
Next time Uncle Four, you provide ribs I will provide potatoes, how about that

0:04:25.619,0:04:29.419
要的啊 我们两爷子我吃点亏不关事的
Sure, it doesn’t matter if we rip each other off a little

0:04:30.588,0:04:32.341
我们吃排骨不吃亏
We are getting ripped off If we are getting ribs to eat

0:04:32.717,0:04:34.304
我出嘴巴就要得了哈四伯爷
I am just gonna provide my mouth

0:04:34.429,0:04:35.139
好
Sure

0:04:37.059,0:04:38.771
土鸡是不一样
Free range chicken is really different

0:04:40.024,0:04:44.951
三黄鸡 二代鸡都没得这个土鸡好吃
Yeah, neither yellow chicken nor hybrid chicken(farm/industrial) is as good as this free range chicken

0:04:45.744,0:04:47.581
嗯 这个芋头比土豆好吃
This taro is tastier than the potatoes

0:04:47.748,0:04:49.753
真的啊 我没尝
Oh really, I haven’t tried yet

**Comment by iamatrollatrollisme** [comment]
【美食作家王刚】厨师长教你：“芋儿烧鸡”“土豆烧鸡”的家常做法，芋头和土豆超级好吃，一锅够全家人吃！
【Food Artist Wanggang】Chef teach you: Making “Braise chicken with taro/potato” at home, very delicious and one-pot dish for entire family


0:00:00.050,0:00:02.250
今天我们把这个公鸡把它剁了
Today we are going to chop this rooster

0:00:02.250,0:00:03.940
是个我们这里的土鸡
This is our own free range chicken

0:00:04.175,0:00:05.391
我们先把它剁一下
Let’s chop a big cut

0:00:06.775,0:00:09.350
剁鸡也是从中间开始剁
Chop the chicken into pieces from the middle

0:00:11.550,0:00:13.600
一般烧的鸡我们就剁大块一点
Since we are going to braise the chicken we can chop them into bigger pieces

0:00:15.075,0:00:19.750
大家可以看一下这两个是鸡的腰子 据说是大补
Let’s take a look, this is the chicken’s kidneys, I heard they are very nutritious

0:00:20.488,0:00:22.863
然后就不用改刀 改了刀它就烂了
And then no need to cut it, otherwise it will dissolve in the stew

0:00:22.863,0:00:24.413
就直接放在里面一起烧
Just dump them into the stew

0:00:24.413,0:00:26.513
这个是它的消化的东西
This is what the chicken digested

0:00:26.688,0:00:30.513
切这个鸡胗的时候不要切这边 这边是筋
Don’t cut this side of the chicken gizzard while slicing it, this side is the tendon

0:00:30.588,0:00:34.113
你必须切这一面它才会散花 才会这样子散开
You need to slice this side, so it will shrink and spread out like this 

0:00:34.238,0:00:35.513
切这一面是不会散开的
Slicing from this side will not spread out

0:00:35.663,0:00:37.713
而且切这一面非常的丑
And it will look very ugly if slicing from this side

0:00:38.538,0:00:41.988
然后我们一刀一刀地切下去 不要切断
Now we are slicing it slowly, don’t cut through

0:00:42.638,0:00:45.263
刚好切到那一面白色的位置
Stop slicing when you reach the white part

0:00:45.663,0:00:47.588
看到没中间是白色的东西
You see this white strip in the middle

0:00:48.313,0:00:52.338
然后再横过来再切 切进去
Then turn it and slice again

0:00:54.313,0:00:58.638
待会儿它熟了过后这个就收缩起来像一朵花一样
Once it’s cooked it will shrink and spread out like flower blossom

0:01:00.163,0:01:03.438
这个鸡胗这样子切出来口感非常的好
Cut the gizzard this way the texture will be satisfying

0:01:04.813,0:01:06.113
四伯爷 你看
Uncle Four, check it out

0:01:06.238,0:01:07.488
跟汤圆儿一样噶
They look like Tangyuan

0:01:07.538,0:01:10.438
人家不晓得的以为这个是鸡蛋 以为这个是土鸡蛋
People who don’t know might think these are eggs, they might think these are our farm eggs

0:01:10.988,0:01:12.613
看到没 还有这个白的
You see this one, it’s white

0:01:12.863,0:01:16.038
大家看得到吗 这个小土豆
Let’s see, this is mini potato

0:01:16.613,0:01:19.113
然后这个是芋头 小芋头
And this one is taro, mini taro

0:01:19.513,0:01:21.388
待会儿烧公鸡就用这个来烧
We will braise the rooster with these

0:01:21.638,0:01:26.038
这个大蒜就对半切 切了煮一下方便你们等会儿拈来吃
We are cutting the garlic in half, easier to grab to eat later

0:01:26.388,0:01:28.088
这蒜整耙了好干（吃）
You gotta cook the garlic soft for it to taste good

0:01:36.738,0:01:44.763
这个吃辣点跟中辣两个 吃特辣就要冬天越辣越安逸
We normally eat two type of spicy, medium hot and extra spicy, it's better to eat extra spicy in winter, the spicier dishes are in winter, the more comfortable we are

0:01:45.313,0:01:48.163
这个时候安 吃中辣是最合适的
This time of the year, medium hot is the best

0:01:48.713,0:01:50.038
四伯爷还会吃安
Uncle Four you know your food

0:01:50.213,0:01:51.463
要根据天气
Gotta eat according to the weather

0:01:52.788,0:01:53.963
我说你还多会吃安
That’s why I said you know your food

0:01:54.063,0:01:56.263
嗨 这些东西都想不到啊
Oh well there are many things you can’t even think of

0:02:00.688,0:02:03.013
诶 好久你又做泡海椒安
Oh when are you making pickled chili pepper

0:02:03.588,0:02:05.220
要下半年去了都嘛
Later half of the year

0:02:05.238,0:02:07.913
下半年去了噶 下半年我们一起做嘛
Okay, later, later we can make it together

0:03:40.149,0:03:43.156
撒点香菜就可以吃了
Garnish with some cilantro we can eat it now

0:03:44.951,0:03:47.665
这个土豆你看 筷子都夹得耙
Check out this potatoes, it’s soft that I can cut it in half with my chopsticks

0:03:48.166,0:03:50.963
你想嘛 是你师父亲自做得咋不好吃嘛
Think about it, your teacher made this himself, how can it be bad

0:03:51.089,0:03:52.759
看 我们这个土豆（好软）
See, this potato is so soft

0:03:53.469,0:03:55.682
等我学会了我做给你吃四伯爷
When I learn how to cook this I will make it for you Uncle Four

0:03:55.682,0:03:58.187
好嘛好嘛 你把技术学都来做给我吃嘛
Okay fine, learn the skill and cook for me

0:03:59.690,0:04:01.360
你跟你师父两个比哈嘛
And compete with your teacher

0:04:01.861,0:04:04.659
我才不跟他比呢 我不敢
I am not going to compete with him, I don’t think I can

0:04:04.700,0:04:05.702
不敢哇
I am too scared to

0:04:06.287,0:04:07.456
我不配
I do not deserve to

0:04:08.166,0:04:09.586
你学会了还是可以
If you learn how to cook you can

0:04:11.047,0:04:15.932
下次你整点土豆烧点排骨跟我吃嘛
Next time can you braise some potatoes with ribs for me

0:04:16.183,0:04:16.809
要得啊
Sure

0:04:16.934,0:04:20.567
那个东西烧起还不是好吃啊 安逸得很
Braising those together is very tasty, feel good about it

0:04:20.817,0:04:25.535
弄个子四伯爷 二回你出排骨我出土豆 嘿嘿
Next time Uncle Four, you provide ribs I will provide potatoes, how about that

0:04:25.619,0:04:29.419
要的啊 我们两爷子我吃点亏不关事的
Sure, it doesn’t matter if we rip each other off a little

0:04:30.588,0:04:32.341
我们吃排骨不吃亏
We are getting ripped off If we are getting ribs to eat

0:04:32.717,0:04:34.304
我出嘴巴就要得了哈四伯爷
I am just gonna provide my mouth

0:04:34.429,0:04:35.139
好
Sure

0:04:37.059,0:04:38.771
土鸡是不一样
Free range chicken is really different

0:04:40.024,0:04:44.951
三黄鸡 二代鸡都没得这个土鸡好吃
Yeah, neither yellow chicken nor hybrid chicken(farm/industrial) is as good as this free range chicken

0:04:45.744,0:04:47.581
嗯 这个芋头比土豆好吃
This taro is tastier than the potatoes

0:04:47.748,0:04:49.753
真的啊 我没尝
Oh really, I haven’t tried yet
