### ISSUE TITLE
[华农兄弟] 烤鱼 - https://youtu.be/31ksAw6OuSE

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#780]
https://youtu.be/31ksAw6OuSE
<p>&#35270;&#39057;&#21457;&#24067;&#20110; March 11, 2020 at 11:40AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/31ksAw6OuSE

#华农兄弟：兄弟看我们半天没钓到，特意送来一鱼，烤起很香哦
#Huanong Brothers: Our buddy gives us a fish, as he sees us getting home empty-handed after spending a whole day fishing. We grill the fish and it smells really good!

0:00:00.140,0:00:02.100
# 大家好  很久都沒吃過肉啦
Hi everyone! We haven't had any meat for a long time.

0:00:02.520,0:00:04.780
# 拿個魚竿來  釣點魚回去烤
So I come with a fishing pole, to catch some fish and grill them.

0:00:05.320,0:00:06.500
# 不知道能不能釣得到  (註︰這裡如果用"I don't know if..."或"I wonder.."感覺會帶點否定，和他原意不太配合)
Let's see if we can catch any

0:00:08.320,0:00:10.100
# 魚都可以看的到  好多哇
I can see the fish already. There are a lot!

0:00:11.880,0:00:12.880
# 哎喲
Ayo!

0:00:15.980,0:00:17.020
# 都不咬鈎的
They don't bite the hook at all.

0:00:17.680,0:00:19.220
# 釣那麼久都還不咬鈎
I've been here for such a long time but no fish have ever bitten the hook.

0:00:21.720,0:00:23.740
# 你看  那麼菜葉子就是給個魚吃的
Look! Those veggie leaves are food for the fish.

0:00:25.000,0:00:26.220
# 下面還有鴨子哦
There are ducks down there too.

0:00:26.920,0:00:30.240
# 用魚鈎來鈎鴨子應該很好釣  一下子就可以釣得到
I think catching the ducks with the hook wouldn't take too much effort. A single pull is all what's needed.

0:00:44.480,0:00:46.380
# 可能姿勢不對哦
Is it because of my posture?

0:00:46.600,0:00:47.500
# 釣不到的
I can't catch any.

0:00:48.220,0:00:48.720
# 唉
Ey?

0:00:51.820,0:00:52.320
# 哦
Oh?

0:00:56.100,0:00:58.440
# 這個角落沒有魚的  我去那邊
There aren't any fish at this corner. I'm going to that,

0:00:58.780,0:00:59.820
# 那邊釣  (註︰「釣」字不譯了，譯了反而更怪，但上句刪去"side"字以保留不完整的感覺)
that side.

0:01:30.980,0:01:33.460
# 一條魚都沒釣到  魚鈎都不咬的
Not even a single fish. They didn't bite the hook at all.

0:01:33.620,0:01:35.860
# 下次我叫兄弟搞一隻鴨子來吃
Next time I'll ask my buddy to get me a duck.

0:01:36.120,0:01:37.320
# 下面那個鴨子
I mean the ducks down there.

0:01:37.540,0:01:38.160
# 幾天後
A few days later

0:01:38.260,0:01:39.720
# 上次我去兄弟釣魚  
Last time we went fishing at my buddy's place.

0:01:39.860,0:01:40.840
# 一條都沒有釣到
But we couldn't catch any.

0:01:41.140,0:01:42.260
# 今天他送了一條給我
Today, he gave me a fish.

0:01:43.620,0:01:44.820
# 應該有2斤多
It should be at least a kilogram.

0:01:45.280,0:01:47.460
# 我們去把它給  給處理一下
Let's have it, have it processed,

0:01:48.540,0:01:49.260
# 去河邊
at the riverside.

0:02:18.360,0:02:19.700
# 割點花出來哦
Let slice it a few times.

0:02:27.000,0:02:28.580
# 這把刀不是很利
This knife is not really that sharp.

0:02:29.660,0:02:32.160
# 拿的家里的水果刀  菜刀又不見了
This is my cutting knife. The kitchen knife is again nowhere to be found.

0:02:40.920,0:02:42.000
# 這邊也是
This side too.

0:02:58.260,0:02:59.000
# 好啦
Alright!

0:03:01.560,0:03:02.740
# 等一下我們就放點
Then we'll marinate it,

0:03:04.840,0:03:07.280
# 放點鹽跟生薑那些  先腌一下
marinate it first with some salt, and ginger and whatever.

0:03:07.320,0:03:08.640
# 等一下用鍚紙裏起來
Then, wrap it up with aluminium foil,

0:03:09.120,0:03:09.980
# 烤一下
and grill it.

0:03:14.240,0:03:14.860
# 可以
Okay!

0:03:15.800,0:03:17.440
# 這袋子  把它裝起 (註︰我聽到他是說「把它裝"肥"去」)
The bag, put it in the bag.

0:03:29.240,0:03:30.280
# 我先回去啦
Let me go back first.

0:03:38.800,0:03:39.840
# 先把這個鍚紙
Let's get the foil, 

0:03:41.140,0:03:42.520
# 把這個釣紙搞起來  (註︰「搞起來」是甚麼意思？)
get the foil ready first.

0:03:46.180,0:03:48.120
# 把這個魚放到這裡
And then put the fish here.

0:03:58.800,0:04:01.060
# 放點鹽  放到傷口上
Put some salt, and rub it into the wound.

0:04:13.220,0:04:13.980
# 可以啦
Should be alright now

0:04:16.680,0:04:17.920
# 這個是醬油  (註︰其實這應該不是醬油，即不是用大豆釀制的，這應該是用小麥釀制的鮮露，但我不管他了，他怎說我怎譯)
This is soy sauce.

0:04:35.460,0:04:37.500
# 再加點這個  這個是油哦
And also some, well, this is oil,

0:04:38.060,0:04:39.220
# 是植物油
veggie oil.

0:04:43.900,0:04:45.200
# 夠啦  不要那麼多
Enough. We don't need that much.

0:04:51.920,0:04:52.980
# 這是葱
This is spring onion.

0:04:54.380,0:04:55.280
# 搞點葱
Put some spring onion.

0:04:56.360,0:04:57.580
# 塞它肚子上去
Stuff it into the belly.

0:05:08.940,0:05:10.260
# 咬點這個葱
Have a bite of the spring onion.

0:05:10.700,0:05:11.700
# 咬點這個葱
Having a bite of the spring onion,

0:05:12.800,0:05:14.620
# 煮起來的時候就沒那麼痛苦啦
can reduce the pain when it's being cooked.

0:05:21.420,0:05:22.720
# 搞點生薑
Put some ginger.

0:05:41.920,0:05:43.180
# 輕輕的塞到它嘴里
I stuff it into the mouth gently.

0:05:44.880,0:05:46.640
# 吃了生薑沒那麼腥
It wouldn't smell that fishy after eating the ginger.

0:05:48.720,0:05:49.760
# 這樣就很靚啦
And now it's really beautiful.

0:05:51.140,0:05:52.420
# 唉  剛好這裡還有一個笋
Eh? I just see a bamboo shoot here.

0:05:52.500,0:05:53.680
# 把這個笋也放下去
Why don't we put it in as well?

0:05:55.040,0:05:56.220
# 處理下這個笋
Let me tackle it first.

0:05:56.820,0:05:58.580
# 這個笋太嫩啦
This bamboo shoot is simply too tender.

0:06:07.680,0:06:08.860
# 就那麼一點點
Just a tiny little bit remains.

0:06:14.940,0:06:15.860
# 把這個也削下去
I'll slice it,

0:06:16.920,0:06:17.720
# 一起煮掉
and cook it together with the fish.

0:06:19.480,0:06:20.960
# 你看 把這些笋
Look! The bamboo shoot,

0:06:21.920,0:06:23.240
# 削成薄薄的片
I cut it into thin slices.

0:06:24.660,0:06:26.000
# 增加它的香味
This can enhance the aroma.

0:06:28.080,0:06:30.620
# 把這些配料  要全部塞到肚子上去
The side ingredients, are all to be stuffed into the belly.

0:06:31.140,0:06:34.200
# 不然一烤  這個全部都會燒焦的
Otherwise it would all be burnt, once they're grilled.

0:06:42.080,0:06:43.240
# 它(吃)得很飽啦
It has eaten a lot.

0:06:44.080,0:06:45.280
# 把它裏起來
Let me, wrap it up.

0:06:50.820,0:06:52.680
# 哎喲  肚子夠大哦
Ayo! The belly becomes that big,

0:06:53.280,0:06:54.560
# 吃了那麼多東西
after eating so many things.

0:06:56.920,0:06:58.160
# 還是一條魚
It's still a fish.

0:06:58.620,0:06:59.720
# 還是一條魚樣
It still looks like a fish.

0:07:05.280,0:07:06.580
# 這是尾巴這裡
This is its tail here.

0:07:07.340,0:07:08.660
# 尾巴這裡要多裏一點
The tail here needs to be wrapped a few more times.

0:07:11.460,0:07:12.080
# 啊
Ah!

0:07:15.040,0:07:16.200
# 等一下我們就直接
Then we can grill it,

0:07:16.820,0:07:17.720
# 上烤架 
on the stand,

0:07:17.940,0:07:18.620
# 燒它
right away.

0:07:21.680,0:07:22.800
# 這尾巴歪了一點
The tails is a bit twisted.

0:07:23.020,0:07:24.040
# 把它擺正一點
Let me fix it.

0:07:25.360,0:07:25.900
# 可以
Okay!

0:07:27.100,0:07:28.660
# 我去把那個炭生起來
I'm gonna light up the charcoal.

0:07:29.420,0:07:31.240
# 可以喲  炭烤活魚
Nice! Charcoal grilled fish

0:07:46.460,0:07:48.380
# 把這個架子放上去  把魚
Put the net on top, and the fish...

0:07:48.700,0:07:50.320
# 唉  怎麼不夠長啊
Eh? Why isn't it long enough?

0:07:52.820,0:07:54.080
# 尾巴彎一下
Let me bend its tail.

0:07:56.680,0:07:57.640
# 這樣烤
Then grill it,

0:07:58.000,0:07:59.100
# 這樣現烤著  (註︰下明白想說甚麼)
grill it now.

0:08:05.920,0:08:08.680
# 你看這個  這個火生很好旺哦'
Look! The, the fire is really strong, isn't it?

0:08:10.600,0:08:12.620
# 聽那  嗶哩啪啦 嗶哩啪啦
Listen! It's like, bila bila.

0:08:15.400,0:08:17.120
# 嗯  有點味道出來啦
Um! I can already smell something.

0:08:31.420,0:08:32.780
# 你看  這冒煙  (註︰這兩句的原字幕時間出錯)
Look! The steam is coming out.

0:08:33.420,0:08:34.540
# 馬上就快好啦
It will be ready very soon.

0:08:36.040,0:08:37.340
# 再烤幾個分鐘
Just a few more minutes.

0:08:37.540,0:08:39.520
# 就直接拿下去吃啦
Then we can bring it down, and enjoy it right away.

0:08:43.160,0:08:45.160
# 唉  唉  這個不燙  你看
Ay! Ay! It's not hot. Look!

0:08:47.080,0:08:49.620
# 好香呀 應該熟啦  下去
It smells really nice! It should be alright now. Let's go downstairs,

0:08:49.640,0:08:51.040
# 下去把它刨開來
and open it.

0:08:53.780,0:08:55.200
# 應該這樣搓爛
I think I should break it here,

0:08:55.400,0:08:57.120
# 把它掰開就可以啦
and then peel it open, and that's it.

0:08:58.200,0:08:59.680
# 哎呀  全熟啦
Aya! It's alright now.

0:09:01.440,0:09:02.060
# 哎呀
Aya!

0:09:03.740,0:09:04.420
# 哎呀
Aya!

0:09:06.240,0:09:07.820
# 這肉看上去就好吃
The meat looks very tasty.

0:09:13.180,0:09:14.760
# 哇  一整條魚
Wa! The whole fish...

0:09:15.480,0:09:17.280
# 你看  整條魚還是原樣的
Look! The whole fish is till in its shape.

0:09:18.140,0:09:20.320
# 我來吃一下你的肉  看一下好不好吃
Let me taste your meat, and see if it tastes good.

0:09:22.280,0:09:22.960
# 嗯
Um!

0:09:23.500,0:09:24.300
# 可以喲
Not bad!

0:09:25.960,0:09:26.600
# 好燙
Very hot!

0:09:31.200,0:09:32.300
# 你看這個肚子
Have a look at the belly!

0:09:33.040,0:09:33.840
# 哎呀
Aya!

0:09:35.780,0:09:36.740
# 這個魚泡
This is the swim bladder,

0:09:37.760,0:09:39.260
# 就是魚泡哦
swim bladder, you know.

0:09:44.260,0:09:45.200
# 好燙
Very hot!

0:09:50.920,0:09:52.060
# 這個魚好吃
This fish is really tasty.

0:09:52.760,0:09:53.760
# 哇  這竹笋
Wa! The bamboo shoot...

0:09:55.260,0:09:55.900
# 可以
Not bad!

0:09:56.320,0:09:57.500
# 味道很不錯  這個竹笋
It tastes not bad, the bamboo shoot.

0:10:07.320,0:10:11.080
# 沒有辣椒粉  有辣椒粉  加點辣椒粉  味道很不錯的
I don't have any chilli powder. It would taste really nice with some chilli powder.

0:10:22.200,0:10:24.640
# 這個等一下留著晚上  晚飯來吃
I'll leave it for the dinner, for the dinner tonight.

0:10:26.600,0:10:27.940
# 不然晚上都沒菜吃
We'll have nothing for dinner otherwise.

0:10:44.500,0:10:47.740
# 晚上吃米糠拌飯就行啦  這個魚不好吃的
No worries. You'll have rice and bran tonight. The fish doesn't taste good at all.

0:10:47.980,0:10:48.700
# 知不知道
Got it?

0:10:49.100,0:10:50.740
# 快點 散啦  散啦  散啦  (註︰原字幕少了一次「散啦」)
C'mon! Dismiss, dismiss, dismiss, dismiss!

0:10:50.820,0:10:51.800
# 沒甚麼好吃的
It doesn't taste good at all.
