### ISSUE TITLE
[雪鱼] 澳门早餐广东早茶 - https://youtu.be/uU4m2gvXihU

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#792]
视频链接：https://youtu.be/uU4m2gvXihU
视频时长：10min
发布日期：2020年3月13日
求翻译以下全部内容

---

字幕
```
1
00:00:01,625 --> 00:00:02,275
澳门

2
00:00:09,975 --> 00:00:12,550
来澳门 我们还没有尝试这边的早饭

3
00:00:12,850 --> 00:00:15,475
今天早上呢 咱们将要前往前面的巷子

4
00:00:15,650 --> 00:00:17,175
喝一碗粥

5
00:00:17,475 --> 00:00:19,425
这家粥店别看地方不大

6
00:00:19,600 --> 00:00:21,800
只是在一个几米的走廊里

7
00:00:22,050 --> 00:00:24,050
它狭窄到什么程度呢 就是

8
00:00:24,200 --> 00:00:26,800
除了老板之外 只能走一个人

9
00:00:27,075 --> 00:00:29,400
但是 人真的很多

10
00:00:41,575 --> 00:00:42,525
走过了

11
00:00:44,150 --> 00:00:46,275
是这个

12
00:00:47,100 --> 00:00:48,400
如果我刚才没有留意到

13
00:00:48,450 --> 00:00:50,550
今天早上 我可能连饭都吃不着了

14
00:00:51,150 --> 00:00:53,000
别说 如此隐蔽的早餐摊

15
00:00:53,000 --> 00:00:54,475
里面喝粥的人

16
00:00:54,475 --> 00:00:56,500
竟然要比外面马路上的人都要多

17
00:00:56,975 --> 00:01:00,375
门口呢 还堵着一群想要进去的人

18
00:01:05,725 --> 00:01:08,350
这边卖的生滚粥 种类并没有很稀奇

19
00:01:08,700 --> 00:01:12,425
像我们以前经常能够看到的猪杂 鱼片 肉丸

20
00:01:12,425 --> 00:01:13,650
这边都有

21
00:01:17,675 --> 00:01:19,375
想好了自己要点哪种粥

22
00:01:19,625 --> 00:01:20,875
老板会现场给你抓食材

23
00:01:21,075 --> 00:01:23,625
放在锅里 和白粥煮一会儿

24
00:01:24,075 --> 00:01:26,250
几分钟吧 就可以上桌了

25
00:01:46,625 --> 00:01:48,150
但是 做的再快

26
00:01:48,275 --> 00:01:51,400
饭点的时候 也赶不上顾客点的速度

27
00:01:51,900 --> 00:01:54,350
于是 我们决定 打包带走

28
00:01:54,975 --> 00:01:56,425
鱼片粥

29
00:01:56,700 --> 00:01:59,200
25块钱

30
00:02:05,025 --> 00:02:08,325
这个是我们买的25块钱的鱼片粥

31
00:02:08,550 --> 00:02:10,675
加了一个7块钱的油条

32
00:02:10,675 --> 00:02:12,625
因为里面的人实在是太多了

33
00:02:12,625 --> 00:02:13,775
根本没地方坐

34
00:02:13,775 --> 00:02:16,000
所以呢 我们就是打包出来吃

35
00:02:16,975 --> 00:02:18,625
想不到这么狭窄的档口

36
00:02:18,900 --> 00:02:20,100
生意是真好

37
00:02:25,575 --> 00:02:27,650
这个粥看上去就很美味

38
00:02:28,475 --> 00:02:32,300
白白糯糯的米粥 加上诱人的鱼片

39
00:02:32,500 --> 00:02:35,600
中间撒了姜丝还有香葱

40
00:02:35,600 --> 00:02:37,800
我们迫不及待尝一口吧

41
00:02:42,175 --> 00:02:44,000
咸鲜度正好

42
00:02:44,100 --> 00:02:45,450
其中的大米

43
00:02:46,575 --> 00:02:48,775
几乎快融化成水了

44
00:02:49,075 --> 00:02:50,400
舀一勺 流下去

45
00:02:50,650 --> 00:02:53,075
米都是这种粘稠的状态

46
00:02:53,725 --> 00:02:55,925
熬的已经化了

47
00:03:02,250 --> 00:03:05,675
我们是从上面 翻着朝下喝

48
00:03:05,900 --> 00:03:10,550
上面有米油 还有鱼油

49
00:03:10,550 --> 00:03:12,025
吃起来特别香

50
00:03:12,200 --> 00:03:14,800
使劲翻呢 还能看到鱼片 大块的鱼片

51
00:03:14,800 --> 00:03:16,850
从下面 涌上来

52
00:03:26,350 --> 00:03:27,475
一碗热粥下肚

53
00:03:27,475 --> 00:03:30,622
我们又继续穿梭在澳门的大街小巷

54
00:03:39,950 --> 00:03:43,150
随人群买了一杯瓦煲咖啡

55
00:03:44,100 --> 00:03:46,025
我忘了 我要的是烫的

56
00:03:46,925 --> 00:03:49,925
又垂涎别人手上的蛋挞

57
00:03:56,350 --> 00:03:58,975
吃一口就是有鸡蛋香甜的味道

58
00:03:58,975 --> 00:04:02,000
而且还有淡淡的奶油的味道

59
00:04:17,875 --> 00:04:21,725
一个个门面不大的小吃店 总是排起长队

60
00:04:21,725 --> 00:04:23,025
我不禁叹了一声

61
00:04:23,025 --> 00:04:24,825
吃点好吃的 好难

62
00:04:34,300 --> 00:04:35,775
广东·中山

63
00:04:46,275 --> 00:04:47,075
时隔一年

64
00:04:47,125 --> 00:04:49,100
我又出现在了广东的早茶点

65
00:04:49,450 --> 00:04:51,150
这次 咱们吃早茶的地方

66
00:04:51,425 --> 00:04:54,225
就是后面这家看起来很像大排档的店

67
00:04:54,450 --> 00:04:56,450
怎么说呢 从外面看

68
00:04:56,650 --> 00:04:58,025
（店）几乎看不到任何的装修

69
00:04:58,150 --> 00:05:00,225
就是很多人 围坐在一起

70
00:05:00,300 --> 00:05:01,950
喝着茶 吃着点心

71
00:05:02,175 --> 00:05:04,075
外面已经坐了十几桌

72
00:05:04,150 --> 00:05:06,400
我们进去看一看 里面是什么样子吧

73
00:05:07,625 --> 00:05:09,000
这家店 别看门脸不大

74
00:05:09,225 --> 00:05:11,075
走进来就像进入了花果山一样

75
00:05:11,400 --> 00:05:14,217
地方特别大 桌子特别多

76
00:05:14,217 --> 00:05:17,167
而且感觉每一桌 都是在吃酒席一样

77
00:05:22,475 --> 00:05:24,425
我们到里面去看一下

78
00:05:27,275 --> 00:05:30,900
哦 这里面还有

79
00:05:32,900 --> 00:05:35,150
我觉得这边 上百桌是有的

80
00:05:36,000 --> 00:05:37,925
这只是一个吃早茶的地方

81
00:06:01,300 --> 00:06:03,650
拿这个卡 到档口选东西

82
00:06:04,675 --> 00:06:06,475
这个是给我们的牙签

83
00:06:06,700 --> 00:06:08,175
这个（卡）是我们自己拿着的

84
00:06:08,175 --> 00:06:09,950
到那边去点东西

85
00:06:11,950 --> 00:06:14,300
这一屉屉的小点心 别说我们认不全

86
00:06:14,550 --> 00:06:17,700
怕店里的人 也不能完全叫得上它们的名字

87
00:06:23,050 --> 00:06:25,650
大哥 我想问一下 点心大约有多少种

88
00:06:26,650 --> 00:06:29,225
品种有两百多 差不多三百个品种吧

89
00:06:30,375 --> 00:06:33,175
我们到现在已经有18年了

90
00:06:34,750 --> 00:06:35,975
点心的品种是特别多

91
00:06:36,150 --> 00:06:39,500
但是不可能二三个品种呼呼地全摆出来

92
00:06:39,625 --> 00:06:41,375
咱们现在就是看到什么

93
00:06:41,375 --> 00:06:44,050
喜欢吃什么 然后拿什么

94
00:07:10,800 --> 00:07:12,100
我拿个虾饺

95
00:07:13,225 --> 00:07:15,150
对 有牛仔骨吗

96
00:07:15,650 --> 00:07:17,150
拿一笼

97
00:07:18,725 --> 00:07:20,600
给我卡

98
00:07:24,550 --> 00:07:27,000
那边不还有吗 我再到那边去点

99
00:07:27,550 --> 00:07:28,575
谢谢

100
00:07:29,050 --> 00:07:31,525
这还有很多的点心

101
00:07:39,275 --> 00:07:41,200
咱们这次早茶的内容是

102
00:07:41,450 --> 00:07:43,800
牛仔骨 虾饺 皮蛋瘦肉粥

103
00:07:43,925 --> 00:07:45,534
还要了一盘的凉菜

104
00:07:45,534 --> 00:07:46,600
因为我们不太懂茶

105
00:07:46,600 --> 00:07:48,159
就叫阿姨随便上了一壶

106
00:07:48,159 --> 00:07:51,459
我也不知道是什么茶 反正品就是了

107
00:08:06,950 --> 00:08:10,500
你看 这边的点心都是放在小竹笼里的

108
00:08:10,800 --> 00:08:12,675
像虾饺就是四个为一笼

109
00:08:12,875 --> 00:08:14,325
拿一屉就可以了

110
00:08:14,600 --> 00:08:15,975
这个就是牛仔骨

111
00:08:16,300 --> 00:08:18,025
里面还是放了一个小盘子

112
00:08:18,650 --> 00:08:21,525
能够看到牛仔骨是四五块的大骨头

113
00:08:21,725 --> 00:08:23,175
里面还放了一些花生

114
00:08:25,300 --> 00:08:27,500
尝尝这边的虾饺

115
00:08:29,475 --> 00:08:32,025
虾饺 就是看上去外面是透明的

116
00:08:32,350 --> 00:08:33,850
能看到里面的馅儿

117
00:08:34,125 --> 00:08:35,450
鼓鼓囊囊的馅儿

118
00:08:35,825 --> 00:08:38,425
这一个虾饺下去 里面一个大虾仁就出来了

119
00:08:38,425 --> 00:08:41,725
吃这么一口虾仁 还是感觉很幸福的

120
00:08:43,025 --> 00:08:44,550
接下来我要隆重介绍

121
00:08:44,725 --> 00:08:47,075
今天最难看的牛仔骨

122
00:08:47,250 --> 00:08:49,700
但是也是最好吃的牛仔骨

123
00:08:50,300 --> 00:08:52,200
它虽然说 外面黑黢黢的

124
00:08:52,375 --> 00:08:53,925
但它是黑椒味的

125
00:08:54,025 --> 00:08:55,460
吃起来虽然说 有点油

126
00:08:55,460 --> 00:08:56,685
但是味道真的不错

127
00:08:56,950 --> 00:09:00,200
黑椒当中 还带有一点麻和辣的味道

128
00:09:01,300 --> 00:09:04,500
刚吃下去第一口就流口水了

129
00:09:15,900 --> 00:09:18,850
这应该是我喝过料最多的皮蛋瘦肉粥了

130
00:09:19,175 --> 00:09:21,925
碗大 里面的瘦肉多

131
00:09:22,375 --> 00:09:23,399
我不知道

132
00:09:23,399 --> 00:09:25,949
大家最常喝皮蛋瘦肉粥的地方是哪里

133
00:09:26,200 --> 00:09:28,225
我是在某快餐品牌最常喝这个

134
00:09:28,800 --> 00:09:32,000
但是 两者真的差距很大

135
00:09:32,500 --> 00:09:36,025
它这里面是放了皮蛋还有肉

136
00:09:36,150 --> 00:09:38,525
你喝一口 不仅有大米的绵软

137
00:09:38,700 --> 00:09:40,725
还有一口的香甜

138
00:09:42,700 --> 00:09:45,000
我们又闯入了老年人的天地

139
00:09:45,175 --> 00:09:47,175
现在是早茶时间

140
00:09:47,400 --> 00:09:50,550
和很多的爷爷奶奶在这边一起 吃早茶

141
00:10:02,825 --> 00:10:04,450
现在已经吃完点心了

142
00:10:04,525 --> 00:10:06,875
接下来的时光就是 倒杯茶

143
00:10:06,975 --> 00:10:11,600
品味一下接下来美好的时光

144
00:10:22,200 --> 00:10:25,725
同样是老太太 你看人家就在这边喝早茶

145
00:10:26,025 --> 00:10:31,500
我奶奶早上起来就去超市门口抢鸡蛋 哈哈


```

**Comment by archerdominique** [comment]
bot, please up load
1
00:00:01,625 --> 00:00:02,275
澳门
Macau

2
00:00:09,975 --> 00:00:12,550
来澳门 我们还没有尝试这边的早饭
We haven't tried the breakfast of Macau 

3
00:00:12,850 --> 00:00:15,475
今天早上呢 咱们将要前往前面的巷子
So this morning, we are gonna go to the little alley over there

4
00:00:15,650 --> 00:00:17,175
喝一碗粥
to eat a bowl of congee

5
00:00:17,475 --> 00:00:19,425
这家粥店别看地方不大
This congee shop looks small

6
00:00:19,600 --> 00:00:21,800
只是在一个几米的走廊里
Located in a narrow alley of a few metres wide

7
00:00:22,050 --> 00:00:24,050
它狭窄到什么程度呢 就是
How narrow it is? It's like

8
00:00:24,200 --> 00:00:26,800
除了老板之外 只能走一个人
Apart from the chef, it only allows one person to go through

9
00:00:27,075 --> 00:00:29,400
但是 人真的很多
Nevertheless, there are quite a lot people here

10
00:00:41,575 --> 00:00:42,525
走过了
I almost passed by without noticing it

11
00:00:44,150 --> 00:00:46,275
是这个
It's here!

12
00:00:47,100 --> 00:00:48,400
如果我刚才没有留意到
If I didn't see it

13
00:00:48,450 --> 00:00:50,550
今天早上 我可能连饭都吃不着了
I would probably lose my breakfast this morning 

14
00:00:51,150 --> 00:00:53,000
别说 如此隐蔽的早餐摊
Believe it or not, such a hidden breakfast place

15
00:00:53,000 --> 00:00:54,475
里面喝粥的人
The guests in side

16
00:00:54,475 --> 00:00:56,500
竟然要比外面马路上的人都要多
are even more than those on the street

17
00:00:56,975 --> 00:01:00,375
门口呢 还堵着一群想要进去的人
The entrance is jammed with a crowd who want to squeeze in

18
00:01:05,725 --> 00:01:08,350
这边卖的生滚粥 种类并没有很稀奇
The congee sold here is not uncommon

19
00:01:08,700 --> 00:01:12,425
像我们以前经常能够看到的猪杂 鱼片 肉丸
Using those that we can often see - pork offal, fish slices, meatballs

20
00:01:12,425 --> 00:01:13,650
这边都有
They have all here

21
00:01:17,675 --> 00:01:19,375
想好了自己要点哪种粥
When you decide what kind of congee you're gonna have

22
00:01:19,625 --> 00:01:20,875
老板会现场给你抓食材
The chef will grab the ingredients for you

23
00:01:21,075 --> 00:01:23,625
放在锅里 和白粥煮一会儿
Put them in the pot and boil with the rice congee

24
00:01:24,075 --> 00:01:26,250
几分钟吧 就可以上桌了
In about a few minutes, it will be ready to serve

25
00:01:46,625 --> 00:01:48,150
但是 做的再快
Nevertheless, no matter how fast they can cook the congee

26
00:01:48,275 --> 00:01:51,400
饭点的时候 也赶不上顾客点的速度
During the breakfast time, they could not do as fast as customers' ordering

27
00:01:51,900 --> 00:01:54,350
于是 我们决定 打包带走
So we decide to take away

28
00:01:54,975 --> 00:01:56,425
鱼片粥
Fish slice congee

29
00:01:56,700 --> 00:01:59,200
25块钱
25 yuan

30
00:02:05,025 --> 00:02:08,325
这个是我们买的25块钱的鱼片粥
This is what we ordered, 25-yuan fish slice congee

31
00:02:08,550 --> 00:02:10,675
加了一个7块钱的油条
with a 7-yuan You Tiao (deep-fried dough stick)

32
00:02:10,675 --> 00:02:12,625
因为里面的人实在是太多了
Because too many people are in there

33
00:02:12,625 --> 00:02:13,775
根本没地方坐
We have no place to sit

34
00:02:13,775 --> 00:02:16,000
所以呢 我们就是打包出来吃
So we take them outside to eat

35
00:02:16,975 --> 00:02:18,625
想不到这么狭窄的档口
I never knew that so narrow a place

36
00:02:18,900 --> 00:02:20,100
生意是真好
Can have such a reputation

37
00:02:25,575 --> 00:02:27,650
这个粥看上去就很美味
You feel its good taste just by looking at it

38
00:02:28,475 --> 00:02:32,300
白白糯糯的米粥 加上诱人的鱼片
White and tender rice congee with delicious fish slices

39
00:02:32,500 --> 00:02:35,600
中间撒了姜丝还有香葱
seasoned by ginger shreds and scallions

40
00:02:35,600 --> 00:02:37,800
我们迫不及待尝一口吧
I can't wait to have a taste

41
00:02:42,175 --> 00:02:44,000
咸鲜度正好
The salt and umami taste just right

42
00:02:44,100 --> 00:02:45,450
其中的大米
The rice in the congee

43
00:02:46,575 --> 00:02:48,775
几乎快融化成水了
almost melts into the water

44
00:02:49,075 --> 00:02:50,400
舀一勺 流下去
Take a spoonful of congee it flows away

45
00:02:50,650 --> 00:02:53,075
米都是这种粘稠的状态
The rice is all of such sticky and fluid texture

46
00:02:53,725 --> 00:02:55,925
熬的已经化了
It's been cooked to melted

47
00:03:02,250 --> 00:03:05,675
我们是从上面 翻着朝下喝
We start from the surface

48
00:03:05,900 --> 00:03:10,550
上面有米油 还有鱼油
with the fat of rise and fish

49
00:03:10,550 --> 00:03:12,025
吃起来特别香
The aroma is strong

50
00:03:12,200 --> 00:03:14,800
使劲翻呢 还能看到鱼片 大块的鱼片
Dig deep down and turn it up, you can see large slices of fish

51
00:03:14,800 --> 00:03:16,850
从下面 涌上来
emerging from the bottom

52
00:03:26,350 --> 00:03:27,475
一碗热粥下肚
A bowl of warm congee ends up in my stomach

53
00:03:27,475 --> 00:03:30,622
我们又继续穿梭在澳门的大街小巷
We go on shuttling on the streets of Macau

54
00:03:39,950 --> 00:03:43,150
随人群买了一杯瓦煲咖啡
Imitating others, I bought a cup of coffee brewed with clay pot

55
00:03:44,100 --> 00:03:46,025
我忘了 我要的是烫的
I forget it! I've asked for a hot one

56
00:03:46,925 --> 00:03:49,925
又垂涎别人手上的蛋挞
What's more, I drooled over the egg tarts they had

57
00:03:56,350 --> 00:03:58,975
吃一口就是有鸡蛋香甜的味道
Have a bite, and the aromatic and sweet taste of eggs comes out

58
00:03:58,975 --> 00:04:02,000
而且还有淡淡的奶油的味道
Together with a light taste of cream

59
00:04:17,875 --> 00:04:21,725
一个个门面不大的小吃店 总是排起长队
Those snack shops do not have a conspicuous facade, but are always crowded with a long queue

60
00:04:21,725 --> 00:04:23,025
我不禁叹了一声
Can't help to sighhhh

61
00:04:23,025 --> 00:04:24,825
吃点好吃的 好难
It's so hard to taste some good stuff


62
00:04:34,300 --> 00:04:35,775
广东·中山
Zhongshan, Guangdong Province

63
00:04:46,275 --> 00:04:47,075
时隔一年
After a year

64
00:04:47,125 --> 00:04:49,100
我又出现在了广东的早茶点
I come to Guangdong's morning tea restaurant again

65
00:04:49,450 --> 00:04:51,150
这次 咱们吃早茶的地方
This time we are gonna have morning tea

66
00:04:51,425 --> 00:04:54,225
就是后面这家看起来很像大排档的店
at this place behind me - it looks like an open-air food stall

67
00:04:54,450 --> 00:04:56,450
怎么说呢 从外面看
How to describe it? You see from the outside

68
00:04:56,650 --> 00:04:58,025
（店）几乎看不到任何的装修
you barely see any decoration

69
00:04:58,150 --> 00:05:00,225
就是很多人 围坐在一起
Just plenty of people sitting around together

70
00:05:00,300 --> 00:05:01,950
喝着茶 吃着点心
drinking tea and having dim sum

71
00:05:02,175 --> 00:05:04,075
外面已经坐了十几桌
There're over 10 tables of guests out there

72
00:05:04,150 --> 00:05:06,400
我们进去看一看 里面是什么样子吧
Let's come in and see what it's like inside

73
00:05:07,625 --> 00:05:09,000
这家店 别看门脸不大
This restaurant don't have a large facade

74
00:05:09,225 --> 00:05:11,075
走进来就像进入了花果山一样
but when you come in, it's like going into a complete different world

75
00:05:11,400 --> 00:05:14,217
地方特别大 桌子特别多
The place is extremely spacious with lots of tables

76
00:05:14,217 --> 00:05:17,167
而且感觉每一桌 都是在吃酒席一样
and it seems that guests at each table are having an exuberant banquet

77
00:05:22,475 --> 00:05:24,425
我们到里面去看一下
Let's go further inside

78
00:05:27,275 --> 00:05:30,900
哦 这里面还有
Oh, they've got more in here

79
00:05:32,900 --> 00:05:35,150
我觉得这边 上百桌是有的
I think there are over 100 tables

80
00:05:36,000 --> 00:05:37,925
这只是一个吃早茶的地方
This is only a place for morning tea. *WOW!*

81
00:06:01,300 --> 00:06:03,650
拿这个卡 到档口选东西
Take this card with you and pick what you want at the stalls

82
00:06:04,675 --> 00:06:06,475
这个是给我们的牙签
These are the toothpicks we were given

83
00:06:06,700 --> 00:06:08,175
这个（卡）是我们自己拿着的
This (card) we take with ourselves

84
00:06:08,175 --> 00:06:09,950
到那边去点东西
Place our order over there. Let's go!

85
00:06:11,950 --> 00:06:14,300
这一屉屉的小点心 别说我们认不全
These trays of dim sum, we can't tell the name of each

86
00:06:14,550 --> 00:06:17,700
怕店里的人 也不能完全叫得上它们的名字
I'm afarid that neither can the staff know all the names

87
00:06:23,050 --> 00:06:25,650
大哥 我想问一下 点心大约有多少种
Brother, do you know how many kinds of dim sum you have here?

88
00:06:26,650 --> 00:06:29,225
品种有两百多 差不多三百个品种吧
Over 200, I think nearly 300 kinds

89
00:06:30,375 --> 00:06:33,175
我们到现在已经有18年了
This place's been here for 18 years

90
00:06:34,750 --> 00:06:35,975
点心的品种是特别多
They do have lots of different dim sum

91
00:06:36,150 --> 00:06:39,500
但是不可能二三个品种呼呼地全摆出来
But they cannot lay out all

92
00:06:39,625 --> 00:06:41,375
咱们现在就是看到什么
So now we are like, taking from whatever we see

93
00:06:41,375 --> 00:06:44,050
喜欢吃什么 然后拿什么
the dim sum we'd like to eat

94
00:07:10,800 --> 00:07:12,100
我拿个虾饺
I will have some shrimp dumplings

95
00:07:13,225 --> 00:07:15,150
对 有牛仔骨吗
Yeah. Do you have beef on bone? 

96
00:07:15,650 --> 00:07:17,150
拿一笼
I will take a tray of it

97
00:07:18,725 --> 00:07:20,600
给我卡
Hand me the card

98
00:07:24,550 --> 00:07:27,000
那边不还有吗 我再到那边去点
There're more over there, aren't there? I will have more from that side

99
00:07:27,550 --> 00:07:28,575
谢谢
Thanks!

100
00:07:29,050 --> 00:07:31,525
这还有很多的点心
Here are quite a lot dim sum

101
00:07:39,275 --> 00:07:41,200
咱们这次早茶的内容是
So what we've got for today's morning tea are

102
00:07:41,450 --> 00:07:43,800
牛仔骨 虾饺 皮蛋瘦肉粥
Beef on the bone, shrimp dumplings, and pork congee with preserved eggs

103
00:07:43,925 --> 00:07:45,534
还要了一盘的凉菜
We also asked for a cold dish

104
00:07:45,534 --> 00:07:46,600
因为我们不太懂茶
Because we don't really know much about tea

105
00:07:46,600 --> 00:07:48,159
就叫阿姨随便上了一壶
We asked for a random tea from the staff

106
00:07:48,159 --> 00:07:51,459
我也不知道是什么茶 反正品就是了
I don't know what kind of tea it is, but taste it anyway

107
00:08:06,950 --> 00:08:10,500
你看 这边的点心都是放在小竹笼里的
You see, the dim sum here are all served in such little bamboo trays

108
00:08:10,800 --> 00:08:12,675
像虾饺就是四个为一笼
Like the shrimp dumplings, a tray have four in it

109
00:08:12,875 --> 00:08:14,325
拿一屉就可以了
It's just fine to take one tray

110
00:08:14,600 --> 00:08:15,975
这个就是牛仔骨
This is the beef on the bone

111
00:08:16,300 --> 00:08:18,025
里面还是放了一个小盘子
There's still a small plate in the tray

112
00:08:18,650 --> 00:08:21,525
能够看到牛仔骨是四五块的大骨头
As you can see, there are four to five large bones

113
00:08:21,725 --> 00:08:23,175
里面还放了一些花生
With a little peanut

114
00:08:25,300 --> 00:08:27,500
尝尝这边的虾饺
Let me have taste of the shrimp dumplings here

115
00:08:29,475 --> 00:08:32,025
虾饺 就是看上去外面是透明的
The shrimp dumplings, they look transparent from the outside

116
00:08:32,350 --> 00:08:33,850
能看到里面的馅儿
You can see the filling

117
00:08:34,125 --> 00:08:35,450
鼓鼓囊囊的馅儿
Very abundant fillings

118
00:08:35,825 --> 00:08:38,425
这一个虾饺下去 里面一个大虾仁就出来了（第一句有点模糊，我根据场景意译了一下）
Tear down the wrapper and a large shrimp slips out

119
00:08:38,425 --> 00:08:41,725
吃这么一口虾仁 还是感觉很幸福的
It's indeed a bliss to have a bite of this shrimp

120
00:08:43,025 --> 00:08:44,550
接下来我要隆重介绍
Now I'm gonna introduce 

121
00:08:44,725 --> 00:08:47,075
今天最难看的牛仔骨
Today's most bad-looking beef on the bone

122
00:08:47,250 --> 00:08:49,700
但是也是最好吃的牛仔骨
The most delicious though

123
00:08:50,300 --> 00:08:52,200
它虽然说 外面黑黢黢的
Although it looks pitch black

124
00:08:52,375 --> 00:08:53,925
但它是黑椒味的
But it has the black pepper flavour

125
00:08:54,025 --> 00:08:55,460
吃起来虽然说 有点油
It taste a little greasy

126
00:08:55,460 --> 00:08:56,685
但是味道真的不错
But it's indeed very delicious

127
00:08:56,950 --> 00:09:00,200
黑椒当中 还带有一点麻和辣的味道
The black pepper sauce has some spicy and numb taste

128
00:09:01,300 --> 00:09:04,500
刚吃下去第一口就流口水了
My mouth is watering from the first bite

129
00:09:15,900 --> 00:09:18,850
这应该是我喝过料最多的皮蛋瘦肉粥了
This should be the the most ample pork and preserved eggs congee I've ever had

130
00:09:19,175 --> 00:09:21,925
碗大 里面的瘦肉多
A large bowl, and there're lots of lean pork in it

131
00:09:22,375 --> 00:09:23,399
我不知道
I don't know

132
00:09:23,399 --> 00:09:25,949
大家最常喝皮蛋瘦肉粥的地方是哪里
where you guys often have pork and preserved eggs congee

133
00:09:26,200 --> 00:09:28,225
我是在某快餐品牌最常喝这个
I often have it at KFC

134
00:09:28,800 --> 00:09:32,000
但是 两者真的差距很大
But there's a sharp contrast between them 

135
00:09:32,500 --> 00:09:36,025
它这里面是放了皮蛋还有肉
It has preserved eggs and pork

136
00:09:36,150 --> 00:09:38,525
你喝一口 不仅有大米的绵软
Have a taste, you not only get the tender texture of rice

137
00:09:38,700 --> 00:09:40,725
还有一口的香甜
and the mouthful of aroma

138
00:09:42,700 --> 00:09:45,000
我们又闯入了老年人的天地
We break into the world of the elder again

139
00:09:45,175 --> 00:09:47,175
现在是早茶时间
Now is the time for morning tea

140
00:09:47,400 --> 00:09:50,550
和很多的爷爷奶奶在这边一起 吃早茶
Having morning tea here together with lots of grandpas and grandmas 

141
00:10:02,825 --> 00:10:04,450
现在已经吃完点心了
Now we've finished our dim sum

142
00:10:04,525 --> 00:10:06,875
接下来的时光就是 倒杯茶
Next we'll spend the time on having a cup of tea

143
00:10:06,975 --> 00:10:11,600
品味一下接下来美好的时光
And have a taste of this pleasant moment

144
00:10:22,200 --> 00:10:25,725
同样是老太太 你看人家就在这边喝早茶
These grandmas here are having morning tea

145
00:10:26,025 --> 00:10:31,500
我奶奶早上起来就去超市门口抢鸡蛋 哈哈
But my grandma would go to store and grab some eggs in the morning, haha
