### ISSUE TITLE
【美食作家王刚】介绍鲜八角 - https://youtu.be/whoE8pjUgII

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#795]
**视频链接**：https://youtu.be/whoE8pjUgII

视频时长 2:31，预计发布时间为北京时间3月18日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

**请翻译以下全部内容**

---

标题（翻译主要意思即可，不要超过 100 个字符）
```
厨师长分享：“新鲜八角”的原始样子，四伯连说太神奇了，大家来看看见没见过！
```

简介
```
同学们好，托朋友弄了些新鲜八角来，想说可能很多朋友没有见过八角新鲜的样子，那就正好拍一期视频来和大家分享一下。刚摘下来的八角很丰满水分很多，并且籽也没有漏在外面，需要晾晒至干燥就可以用来做菜。听朋友说新鲜晾晒出来的八角味道会更加甘香，很期待晾好！
```

字幕
```
0:00:00.400,0:00:01.175
嗨喽大家好

0:00:01.575,0:00:03.925
今天我托我朋友弄了一些东西过来

0:00:04.400,0:00:05.475
四伯爷你晓得这是啥子不

0:00:05.750,0:00:06.425
不晓得

0:00:07.325,0:00:09.300
这是叶子 

0:00:11.425,0:00:13.600
你看嘛 新鲜的

0:00:15.150,0:00:18.875
就跟它那个大树上的拐爪儿（拐枣）差不多

0:00:23.450,0:00:24.525
这个是八角 

0:00:24.817,0:00:26.289
你们有没有见过新鲜的八角

0:00:27.953,0:00:30.925
看到没 这个八角弄来晒一下

0:00:31.225,0:00:34.075
要晒好几天 把它晒干

0:00:35.175,0:00:39.625
2 4 6 8 嘿 八角还真是八个尖尖

0:00:39.625,0:00:42.075
只有8个 如果多几个出来的话那种就不是得

0:00:42.075,0:00:43.425
那种有毒

0:00:48.350,0:00:50.000
这个有米米（籽）没得安

0:00:50.275,0:00:50.650
有

0:00:51.100,0:00:53.950
对了 它咋个种不起安

0:00:54.850,0:00:56.950
这边不好种 这个都烂了

0:00:57.264,0:00:58.300
啥子不好种哦

0:00:58.350,0:01:03.100
前晚上我看那个新闻 人家种那个羊肚（菌）

0:01:04.450,0:01:06.475
咋啦 用了好多钱哦

0:01:07.725,0:01:09.500
始终人家最后还是干成功了的

0:01:09.575,0:01:10.725
你闻哈看 四伯爷 

0:01:12.600,0:01:13.675
你这样掐了来闻

0:01:13.775,0:01:15.715
就这样闻都闻得到 很香

0:01:15.750,0:01:16.454
掐一哈你再闻

0:01:20.525,0:01:21.375
是不是很香

0:01:21.450,0:01:22.200
嗯 很有好香

0:01:22.350,0:01:24.425
这个时候丢一颗（锅里）的话味道不晓得好大

0:01:25.175,0:01:28.200
因为以前我也没有见过这个新鲜的是什么样子

0:01:28.225,0:01:30.325
所以我托我朋友寄点过来 

0:01:30.875,0:01:32.150
也跟大家分享一下这个

0:01:32.225,0:01:34.075
我第一次看到八角像这个样子

0:01:34.600,0:01:35.075
是不哦

0:01:35.325,0:01:35.700
是啊

0:01:36.075,0:01:37.125
长见识了噶

0:01:37.600,0:01:38.875
这个呢就是叶子

0:01:39.550,0:01:43.125
我朋友说这个产量最高的是在广西

0:01:43.225,0:01:44.425
广西专门种这个的

0:01:44.800,0:01:47.975
这个弄来晒 晒一个星期左右

0:01:48.075,0:01:50.200
35几天一个星期 晒干了来就可以用了

0:01:51.425,0:01:53.525
晒干了就放的久

0:01:54.850,0:01:57.350
你数哈看嘛 随便拿一个来数哈

0:01:57.475,0:01:59.175
都是8个角角

0:02:00.375,0:02:03.050
是 那这个就拿给你了 你晒一下晒了你用

0:02:04.775,0:02:07.875
因为有粉丝在问 老是问这个新鲜八角长什么样子

0:02:08.475,0:02:10.975
今天给大家分享一下 就是长这个样子

0:02:11.275,0:02:12.950
绿色的 比较饱满

0:02:12.975,0:02:16.650
你们买的干的那种 它是缩起来的

0:02:16.700,0:02:18.200
就是这个已经被晒干了

0:02:18.300,0:02:19.350
缩起来一片一片的

0:02:19.525,0:02:21.165
一片一片的中间带了一个籽

0:02:21.575,0:02:24.050
如果你们做菜的话最好就把那个籽去掉

0:02:28.000,0:02:30.025
好了本期视频就到这里了拜拜


```

**Comment by siyusun6918** [comment]
认领

**Comment by siyusun6918** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“新鲜八角”的原始样子，四伯连说太神奇了，大家来看看见没见过！
Chef’s Share: Fresh Star Anise, Come Take A Look!
简介
同学们好，托朋友弄了些新鲜八角来，想说可能很多朋友没有见过八角新鲜的样子，那就正好拍一期视频来和大家分享一下。刚摘下来的八角很丰满水分很多，并且籽也没有漏在外面，需要晾晒至干燥就可以用来做菜。听朋友说新鲜晾晒出来的八角味道会更加甘香，很期待晾好！
Hello, I got some fresh star anise from a friend. I think a lot of friends probably never saw fresh star anise. This is a good time to shoot a video to share with you all. Freshly picked star anise is plump and juicy, and seeds are not exposed. They can be used in cooking after air-dried. My friend said fresh air-dried star anise has a better and sweeter flavor, so I’m really looking forward to it. 
字幕
0:00:00.400,0:00:01.175
嗨喽大家好
Hello,

0:00:01.575,0:00:03.925
今天我托我朋友弄了一些东西过来
Today, I asked my friends to send me something
0:00:04.400,0:00:05.475
四伯爷你晓得这是啥子不
Uncle, do you know what this is?

0:00:05.750,0:00:06.425
不晓得
I don’t know

0:00:07.325,0:00:09.300
这是叶子 
These are leaves

0:00:11.425,0:00:13.600
你看嘛 新鲜的
Look, so fresh

0:00:15.150,0:00:18.875
就跟它那个大树上的拐爪儿（拐枣）差不多
It looks like Turn Jujube from the tree

0:00:23.450,0:00:24.525
这个是八角 
This is star anise

0:00:24.817,0:00:26.289
你们有没有见过新鲜的八角
Have you seen fresh star anise before?

0:00:27.953,0:00:30.925
看到没 这个八角弄来晒一下
See, you air-dry this star anise 

0:00:31.225,0:00:34.075
要晒好几天 把它晒干
For days, until it dries 

0:00:35.175,0:00:39.625
2 4 6 8 嘿 八角还真是八个尖尖
Two, Four, Six, Eight. Star anise really has eight tips 

0:00:39.625,0:00:42.075
只有8个 如果多几个出来的话那种就不是得
Only eight. If there is more, then it’s not star anise

0:00:42.075,0:00:43.425
那种有毒
It’s poisonous  

0:00:48.350,0:00:50.000
这个有米米（籽）没得安
Does it have seeds?

0:00:50.275,0:00:50.650
有
Yes, it has

0:00:51.100,0:00:53.950
对了 它咋个种不起安
Oh, can the star anise be planted?

0:00:54.850,0:00:56.950
这边不好种 这个都烂了
It’s hard to plant it here. This one is rotten. 

0:00:57.264,0:00:58.300
啥子不好种哦
How come?

0:00:58.350,0:01:03.100
前晚上我看那个新闻 人家种那个羊肚（菌）
I saw the news the other night. They planted the fungi culture

0:01:04.450,0:01:06.475
咋啦 用了好多钱哦
Spend a lot of money

0:01:07.725,0:01:09.500
始终人家最后还是干成功了的
They succeeded eventually

0:01:09.575,0:01:10.725
你闻哈看 四伯爷 
Smell it, uncle

0:01:12.600,0:01:13.675
你这样掐了来闻
You break like this and smell it

0:01:13.775,0:01:15.715
就这样闻都闻得到 很香
I can smell like this, smells nice

0:01:15.750,0:01:16.454
掐一哈你再闻
Try to break it first and smell it

0:01:20.525,0:01:21.375
是不是很香
Doesn’t it smell nice?

0:01:21.450,0:01:22.200
嗯 很有好香
Eh, it smells nice

0:01:22.350,0:01:24.425
这个时候丢一颗（锅里）的话味道不晓得好大
If we throw one in the wok now, it’s going to smell great

0:01:25.175,0:01:28.200
因为以前我也没有见过这个新鲜的是什么样子
Because I have never seen star anise when it’s fresh

0:01:28.225,0:01:30.325
所以我托我朋友寄点过来 
So I asked my friend to send some to me

0:01:30.875,0:01:32.150
也跟大家分享一下这个
And share with you all

0:01:32.225,0:01:34.075
我第一次看到八角像这个样子
It’s my first time seeing star anise like this

0:01:34.600,0:01:35.075
是不哦
Isn’t it so?

0:01:35.325,0:01:35.700
是啊
Yeah

0:01:36.075,0:01:37.125
长见识了噶
Learned new knowledge

0:01:37.600,0:01:38.875
这个呢就是叶子
This is the leaves

0:01:39.550,0:01:43.125
我朋友说这个产量最高的是在广西
My friend said Guangxi has the highest production of star anise

0:01:43.225,0:01:44.425
广西专门种这个的
Guangxi is specialized to grow star anise

0:01:44.800,0:01:47.975
这个弄来晒 晒一个星期左右
Air-dry it for about a week

0:01:48.075,0:01:50.200
35几天一个星期 晒干了来就可以用了
Three, five, a week. You can use it when it’s dried.

0:01:51.425,0:01:53.525
晒干了就放的久
The drier it is, the longer it can be stored

0:01:54.850,0:01:57.350
你数哈看嘛 随便拿一个来数哈
You count it, pick one

0:01:57.475,0:01:59.175
都是8个角角
All have eight tips

0:02:00.375,0:02:03.050
是 那这个就拿给你了 你晒一下晒了你用
Then this is yours. You use it after air-dried

0:02:04.775,0:02:07.875
因为有粉丝在问 老是问这个新鲜八角长什么样子
Because some fans ask, what does fresh star anise look like

0:02:08.475,0:02:10.975
今天给大家分享一下 就是长这个样子
I’m sharing with you today, it looks like this 

0:02:11.275,0:02:12.950
绿色的 比较饱满
Green, plump

0:02:12.975,0:02:16.650
你们买的干的那种 它是缩起来的
The dry one you bought, it’s shrunken

0:02:16.700,0:02:18.200
就是这个已经被晒干了
After it’s air-dried 

0:02:18.300,0:02:19.350
缩起来一片一片的
Shrunk into slides

0:02:19.525,0:02:21.165
一片一片的中间带了一个籽
Slides with seed in between

0:02:21.575,0:02:24.050
如果你们做菜的话最好就把那个籽去掉
When you are cooking, it’s better to remove the seed 

0:02:28.000,0:02:30.025
好了本期视频就到这里了拜拜
Alright, that’s it for today, bye-bye
