### ISSUE TITLE
【美食作家王刚】乡下小龙虾 - https://youtu.be/qsBy0Iy2hAw

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#798]
**视频链接**：https://youtu.be/qsBy0Iy2hAw

视频时长 5:37，预计发布时间为北京时间3月19日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

**请翻译以下全部内容**

---

标题（翻译主要意思即可，不要超过 100 个字符）
```
厨师长乡下分享烧：“10斤小龙虾”，小宽油过虾，只加啤酒不放水，味道一流
```

简介
```
大家好，天气转暖也快到了吃小龙虾的季节，现在还不是最肥美的时间，但由于嘴馋还是买来10斤犒劳下家人。可能是由于刷10斤小龙虾实在是有些吃力，切青瓜的时候居然翻车，刀碰到了手，其实回想多年以前刚学厨的时候为了赶上大师傅的速度经常会碰到手，伤疤是厨师必须要经历的。大家如果在烹饪的过程中碰到手一定要及时处理，不仅仅是为了自己负责也是为了食客负责，当然还是希望大家可以永远都可以安安全全的。最后如果大家想看小龙虾具体的处理和烹饪教学可以看我之前的视频，链接在此：麻辣小龙虾 https://www.youtube.com/watch?v=DGmPpeDbjBg 十三香小龙虾 https://www.youtube.com/watch?v=JRawQBCkQ34&t=67s
```

字幕
```
0:00:00.640,0:00:03.200
我们这个小龙虾现在已经刷了很多次了（很多只了）

0:00:03.880,0:00:05.480
这个水特别的黑

0:00:07.300,0:00:11.825
所以我之前拍的那个“麻辣小龙虾”刷6遍一点都不夸张

0:00:11.875,0:00:15.350
今天我们准备了这个小龙虾 你看10斤

0:00:15.775,0:00:17.900
10斤现在已经洗了第一遍

0:00:17.925,0:00:21.175
大家看一下这个水 黑成什么样子

0:00:22.250,0:00:24.475
这新买的刷子都变黑了

0:00:28.850,0:00:30.450
我们切青瓜这样子切

0:00:31.400,0:00:32.800
竖下来切一条

0:00:34.600,0:00:39.500
每一边切三条 这样子走下来

0:00:42.050,0:00:43.550
然后就切成条了

0:00:50.850,0:00:51.750
大蒜放多一点

0:00:51.900,0:00:56.875
这个的话整个的也可以 切下来也行

0:01:08.600,0:01:11.775
刚才拿这个黄瓜的时候不小心刮到一下手

0:01:11.875,0:01:13.425
这里破了点皮

0:01:13.625,0:01:17.750
切这个小米辣 所以我要把这个弄上

0:01:17.825,0:01:20.700
因为刚哥的手也是有感觉的好不好

0:01:21.175,0:01:22.400
之前说抓辣椒没感觉

0:01:22.500,0:01:27.475
这个伤口抓辣椒感觉不是一般的好

0:01:38.075,0:01:40.525
今天呢我们准备了一些魔芋

0:01:40.925,0:01:43.425
魔芋在我们四川啊 人人都爱吃

0:01:43.575,0:01:44.825
只不过我四伯爷不爱吃

0:01:44.875,0:01:47.600
待会儿他可能不会吃这个魔芋

0:03:53.825,0:03:56.750
漆二娃 你来吃撒

0:03:56.850,0:03:59.100
先你都在说你口水都流出来了安

0:04:06.675,0:04:10.800
漆二娃吃这个龙虾我要拜你为师哦

0:04:11.150,0:04:12.625
嗯 对

0:04:12.725,0:04:14.525
你吃龙虾还是老师噶

0:04:18.675,0:04:22.175
我们这个小龙虾之前很多粉丝说做这个太麻烦了

0:04:22.175,0:04:23.375
黄瓜可以吃都嘛

0:04:23.500,0:04:24.075
可以

0:04:24.425,0:04:29.725
然后我现在把这些料全部搞在一个小包装里面

0:04:29.825,0:04:33.550
你们拿回去直接煮就可以了

0:04:43.775,0:04:47.150
我还是学到了 吃这个东西

0:04:47.325,0:04:48.575
下次不用你说了

0:04:51.100,0:04:52.100
把它掰开

0:04:52.200,0:04:54.450
我晓得啊 这里我倒吃得来了

0:05:03.475,0:05:05.425
没得什么弄得

0:05:05.500,0:05:06.950
你看她好厉害哦

0:05:09.025,0:05:10.050
多啃就是了

0:05:12.375,0:05:14.500
你是老师吃龙虾的老师

0:05:16.400,0:05:20.050
你一个人吃5斤这里10斤一个人要吃好多哦

0:05:21.425,0:05:23.375
好啦下次再给你们分享做法

0:05:23.475,0:05:25.250
这个又没什么吃方得了

0:05:26.075,0:05:28.625
今天是切这个黄瓜翻车了

0:05:29.275,0:05:30.050
切到一下手

0:05:30.875,0:05:32.838
然后所以今天有很多东西没拍到

0:05:32.900,0:05:35.125
下一次给你们拍一个更加仔细的


```

**Comment by Losskywalker** [comment]
认领

**Comment by Losskywalker** [comment]
bot, please upload
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长乡下分享烧：“10斤小龙虾”，小宽油过虾，只加啤酒不放水，味道一流

Chef Wang teaches you how to cook 5kg village-style crayfish with beer.
简介
大家好，天气转暖也快到了吃小龙虾的季节，现在还不是最肥美的时间，但由于嘴馋还是买来10斤犒劳下家人。可能是由于刷10斤小龙虾实在是有些吃力，切青瓜的时候居然翻车，刀碰到了手，其实回想多年以前刚学厨的时候为了赶上大师傅的速度经常会碰到手，伤疤是厨师必须要经历的。大家如果在烹饪的过程中碰到手一定要及时处理，不仅仅是为了自己负责也是为了食客负责，当然还是希望大家可以永远都可以安安全全的。最后如果大家想看小龙虾具体的处理和烹饪教学可以看我之前的视频，链接在此：麻辣小龙虾 https://www.youtube.com/watch?v=DGmPpeDbjBg 十三香小龙虾 https://www.youtube.com/watch?v=JRawQBCkQ34&t=67s

Hi everyone. It’s getting warm these days and it’s almost the crayfish season. Although it’s not the perfect time yet and the crayfish is still growing, we could not resist and got 5 kg of crayfish for my family. I spent so much energy on cleaning these crayfish that I even lost control of my knife and sliced myself. Well, that reminds me of my time as a student, when I often had to try very hard to catch up with my master. Naturally, these injuries are part of my learning experience to become a real chef. Having said that, it is very important that you take immediate care of the wound during cooking, which is important for yourself and your guests. Being careful and safe during cooking is always a priority. Lastly, if you want to learn more about detailed preparation and cooking tutorials, please check out my previous videos Sichuan spicy crayfish: https://www.youtube.com/watch?v=DGmPpeDbjBg Crayfish with Chinese 13-species mix https://www.youtube.com/watch?v=JRawQBCkQ34&t=67s



字幕
0:00:00.640,0:00:03.200
#我们这个小龙虾现在已经刷了很多次了（很多只了）
We have been cleaning these crayfish for several times

0:00:03.880,0:00:05.480
#这个水特别的黑
The water here are turning black

0:00:07.300,0:00:11.825
#所以我之前拍的那个“麻辣小龙虾”刷6遍一点都不夸张
See? When I said that I had to clean 6 times in my previous video, I was not joking.

0:00:11.875,0:00:15.350
#今天我们准备了这个小龙虾 你看10斤
Today, we have 5 kg of crayfish

0:00:15.775,0:00:17.900
#10斤现在已经洗了第一遍
This is after the first round of cleaning

0:00:17.925,0:00:21.175
#大家看一下这个水 黑成什么样子
Look at the color, how dark it is

0:00:22.250,0:00:24.475
#这新买的刷子都变黑了
Even the brand new brush is turning black.

0:00:28.850,0:00:30.450
#我们切青瓜这样子切
Here’s how I chop the cucumber

0:00:31.400,0:00:32.800
#竖下来切一条
First slice it in half

0:00:34.600,0:00:39.500
#每一边切三条 这样子走下来
And then slice each half into three strips.

0:00:42.050,0:00:43.550
#然后就切成条了
Then we chop them into pieces

0:00:50.850,0:00:51.750
#大蒜放多一点
Be generous with the garlic

0:00:51.900,0:00:56.875
#这个的话整个的也可以 切下来也行
You can either use them like this, or chop them into small pieces 

0:01:08.600,0:01:11.775
#刚才拿这个黄瓜的时候不小心刮到一下手
I accidentally cut myself when I was preparing the cucumbers

0:01:11.875,0:01:13.425
#这里破了点皮
A small cut here

0:01:13.625,0:01:17.750
#切这个小米辣 所以我要把这个弄上
I had to cover it with Band-Aid because I am now chopping the chili peppers  

0:01:17.825,0:01:20.700
#因为刚哥的手也是有感觉的好不好
Because, hey, I do have feelings on my fingers.

0:01:21.175,0:01:22.400
#之前说抓辣椒没感觉
Some fans were joking that I don’t feel the chilis at all on my figners

0:01:22.500,0:01:27.475
#这个伤口抓辣椒感觉不是一般的好
Well, it feels very “nice” on the wounds like this

0:01:38.075,0:01:40.525
#今天呢我们准备了一些魔芋
We also have some Konjac here

0:01:40.925,0:01:43.425
#魔芋在我们四川啊 人人都爱吃
Everyone loves Konjac in Sichuan

0:01:43.575,0:01:44.825
#只不过我四伯爷不爱吃
Except my uncle

0:01:44.875,0:01:47.600
#待会儿他可能不会吃这个魔芋
So he will probably skip this later

0:03:53.825,0:03:56.750
#漆二娃 你来吃撒
Have a taste Qi Erwa

0:03:56.850,0:03:59.100
#先你都在说你口水都流出来了安
You were saying that you were already drooling

0:04:06.675,0:04:10.800
#漆二娃吃这个龙虾我要拜你为师哦
Qi Erwa you are the real master of Eating a crayfish

0:04:11.150,0:04:12.625
#嗯 对
Of course

0:04:12.725,0:04:14.525
#你吃龙虾还是老师噶
You have to teach us

0:04:18.675,0:04:22.175
#我们这个小龙虾之前很多粉丝说做这个太麻烦了
Some followers were saying that it was quite complicated to cook crayfish

0:04:22.175,0:04:23.375
#黄瓜可以吃都嘛
(Can I also eat the cucumber?)

0:04:23.500,0:04:24.075
#可以
Sure

0:04:24.425,0:04:29.725
#然后我现在把这些料全部搞在一个小包装里面
Now I have prepared all the ingredients in one package

0:04:29.825,0:04:33.550
#你们拿回去直接煮就可以了
So you can just cook them directly at home

0:04:43.775,0:04:47.150
#我还是学到了 吃这个东西
I have learnt how to eat it properly

0:04:47.325,0:04:48.575
#下次不用你说了
I don’t need your guidance next time.

0:04:51.100,0:04:52.100
#把它掰开
Just break it up like this

0:04:52.200,0:04:54.450
#我晓得啊 这里我倒吃得来了
I know, I know already.

0:05:03.475,0:05:05.425
#没得什么弄得
There’s not too much to eat though.

0:05:05.500,0:05:06.950
#你看她好厉害哦
Look at her, she’s good!

0:05:09.025,0:05:10.050
#多啃就是了
Practice makes perfect!

0:05:12.375,0:05:14.500
#你是老师吃龙虾的老师
You are the master in eating crayfish

0:05:16.400,0:05:20.050
#你一个人吃5斤这里10斤一个人要吃好多哦
You can finish like 2.5 kg already by yourself (we only have 5 kg here)

0:05:21.425,0:05:23.375
#好啦下次再给你们分享做法
Alright I will share more cooking details next time.

0:05:23.475,0:05:25.250
#这个又没什么吃方得了
This one is so small.

0:05:26.075,0:05:28.625
#今天是切这个黄瓜翻车了
I screwed up a little bit while cutting the cucumbers

0:05:29.275,0:05:30.050
#切到一下手
I cut my finger a little bit.

0:05:30.875,0:05:32.838
#然后所以今天有很多东西没拍到
So we didn’t film enough details today.

0:05:32.900,0:05:35.125
#下一次给你们拍一个更加仔细的
I will come back with more details next time.
