### ISSUE TITLE
【美食作家王刚】 葱的几种切法 - https://youtu.be/J2FH8pj_jSw

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#799]
**视频链接**：https://youtu.be/J2FH8pj_jSw

视频时长 3:37，预计发布时间为北京时间3月20日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

**请翻译以下全部内容**

---

标题（翻译主要意思即可，不要超过 100 个字符）
```
厨师长教你：“葱的几种切法”与应用，和切“蒸鱼辅料”的刀法，收藏！
```

简介
```
同学们好，今天和大家分享“葱的几种切法”，葱作为常用的辅料配料在非常多的菜品中都会出现，其中比较常见的表现形式为葱粒，葱片，葱花，葱丝等等，在不同的菜品种有最适合的葱的切法，最后又给大家分享了一下如何准备和切蒸鱼的辅料，希望可以对大家有帮助。如果大家还有什么想学的小技巧，欢迎大家留言告诉我！
```

字幕
```
0:00:00.220,0:00:01.440
哈喽大家好 我是王刚

0:00:01.440,0:00:02.900
本期视频我和大家分享

0:00:03.220,0:00:04.420
葱的几种切法

0:00:04.840,0:00:08.400
在实际烹饪中大葱的绿色部分很少用上

0:00:08.400,0:00:10.425
所以我们直接将其切掉

0:00:12.075,0:00:14.075
首先我们展示第一种切法

0:00:14.075,0:00:16.800
将大葱直接切成1厘米左右的小颗粒

0:00:16.800,0:00:19.450
这种颗粒状的形态适合做爆炒类的料头

0:00:19.450,0:00:21.575
或者用作宫保鸡丁的辅料

0:00:21.575,0:00:23.325
下面我们来看成品展示

0:00:25.850,0:00:27.750
然后我们开始展示第二种切法

0:00:27.750,0:00:29.225
此法更加的简单

0:00:29.225,0:00:30.925
直接将大葱斜刀切成片

0:00:30.925,0:00:33.425
此切法的角度和厚度必须掌握一致

0:00:33.425,0:00:35.000
否则会很不均匀

0:00:35.025,0:00:38.650
此切法的大葱适用于葱爆羊肉或者葱爆类的做法

0:00:38.650,0:00:40.275
然后我们来看第三种切法

0:00:40.275,0:00:42.650
首先将大葱从中间切开一边

0:00:42.650,0:00:45.225
同学们要注意不能把大葱对半切开

0:00:45.225,0:00:47.050
而只是切一边即可

0:00:47.050,0:00:50.350
然后将大葱（翻）面朝下倾斜直刀切成细丝即可

0:00:50.350,0:00:52.525
这样的切法比较适合大众类的菜

0:00:52.525,0:00:54.475
或者用于京酱肉丝的垫底

0:00:54.475,0:00:57.625
同样是切丝我们再来看第四种切法

0:00:57.800,0:00:59.850
首先我们将大葱切成长段

0:00:59.850,0:01:02.350
同学们这一步直接决定葱丝的长度

0:01:02.350,0:01:03.900
然后再切开一边

0:01:03.900,0:01:05.925
我们首先来展示错误的方法

0:01:05.925,0:01:07.850
切开一边之后直接切丝

0:01:09.675,0:01:12.775
在不去除内芯的情况下切出来的丝比较粗狂

0:01:15.975,0:01:18.450
下面我们再来尝试去掉中间的内芯

0:01:20.750,0:01:23.800
去掉内芯之后重叠在一起顺着切成细丝

0:01:24.000,0:01:26.625
这样切出来的大葱丝更加的规则细小

0:01:41.275,0:01:43.575
它比较适用于炝锅或者蒸鱼

0:01:43.575,0:01:45.525
说到蒸鱼所用的所有辅料

0:01:45.525,0:01:47.000
请大家继续往下看

0:01:47.000,0:01:49.650
我们再准备小葱1小把切掉葱头

0:01:52.200,0:01:54.050
然后将小葱卷2圈

0:01:56.300,0:01:59.250
卷起来之后用手按住直刀切成细丝

0:02:08.750,0:02:10.350
切好之后放入碗中

0:02:12.525,0:02:14.000
准备大红椒1个

0:02:14.000,0:02:16.200
对半切开之后再去除辣椒籽

0:02:25.950,0:02:28.025
然后去除辣椒中多余的“肉”

0:02:28.025,0:02:30.175
这一步的目的是让辣椒变得更薄

0:02:30.175,0:02:32.650
这样才能切出更加细的辣椒丝

0:02:59.300,0:03:01.156
然后我们再准备生姜1小块

0:03:01.156,0:03:04.484
首先用垫刀切出薄片然后切成细丝即可

0:03:04.484,0:03:07.600
鱼蒸好之后再将其撒在上面泼油即可

0:03:28.075,0:03:29.900
好了我的分享到此结束

0:03:29.900,0:03:31.900
如果你们还有感兴趣的小技巧

0:03:31.900,0:03:33.525
可以在评论区留言


```

**Comment by Jasminelv** [comment]
认领

**Comment by Jasminelv** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“葱的几种切法”与应用，和切“蒸鱼辅料”的刀法，收藏！
简介
同学们好，今天和大家分享“葱的几种切法”，葱作为常用的辅料配料在非常多的菜品中都会出现，其中比较常见的表现形式为葱粒，葱片，葱花，葱丝等等，在不同的菜品种有最适合的葱的切法，最后又给大家分享了一下如何准备和切蒸鱼的辅料，希望可以对大家有帮助。如果大家还有什么想学的小技巧，欢迎大家留言告诉我！
Hello everyone， today I’d like to share with you a few different ways to cut scallion.  As a commonly used seasoning, scallion is used in many dishes.  We can cut scallions into different sizes and shapes, in order to pair with different dishes.  At the end of this video, I will also share with you how to prepare seasonings for steaming fish.  Hope this helps, if you want to learn anything, please let me know.

字幕
0:00:00.220,0:00:01.440
哈喽大家好 我是王刚
Hello everyone, I am Wang Gang.

0:00:01.440,0:00:02.900
本期视频我和大家分享
Today I’d like to share

0:00:03.220,0:00:04.420
葱的几种切法
Different ways to cut scallions.

0:00:04.840,0:00:08.400
在实际烹饪中大葱的绿色部分很少用上
In restaurant cooking, the green part of scallions is rarely used.

0:00:08.400,0:00:10.425
所以我们直接将其切掉
So we just cut and discard it.

0:00:12.075,0:00:14.075
首先我们展示第一种切法
The first method is

0:00:14.075,0:00:16.800
将大葱直接切成1厘米左右的小颗粒
To cut the scallion into small dices around 1 centimeter long （about 1/3 inch）

0:00:16.800,0:00:19.450
这种颗粒状的形态适合做爆炒类的料头
This shape and size is good for stir frying

0:00:19.450,0:00:21.575
或者用作宫保鸡丁的辅料
Or used in Kung Pao Chicken

0:00:21.575,0:00:23.325
下面我们来看成品展示
Now let’s see what it is like when I’ve done cutting it.

0:00:25.850,0:00:27.750
然后我们开始展示第二种切法
The second method of cutting scallion

0:00:27.750,0:00:29.225
此法更加的简单
Is even simpler

0:00:29.225,0:00:30.925
直接将大葱斜刀切成片
Just to cut the scallions with an angle

0:00:30.925,0:00:33.425
此切法的角度和厚度必须掌握一致
The key is to cut in the same angle and thickness

0:00:33.425,0:00:35.000
否则会很不均匀
To keep it evenly cut

0:00:35.025,0:00:38.650
此切法的大葱适用于葱爆羊肉或者葱爆类的做法
This cut of scallion is best for stir frying lamb

0:00:38.650,0:00:40.275
然后我们来看第三种切法
Here is the third method.

0:00:40.275,0:00:42.650
首先将大葱从中间切开一边
First, cut to the center of the scallion

0:00:42.650,0:00:45.225
同学们要注意不能把大葱对半切开
Yet not to cut it through

0:00:45.225,0:00:47.050
而只是切一边即可
Just cut it deep enough to the center


0:00:47.050,0:00:50.350
然后将大葱（翻）面朝下倾斜直刀切成细丝即可
Then open the scallion, turn it upside down, then thin slice it with angle.

0:00:50.350,0:00:52.525
这样的切法比较适合大众类的菜
This kind of slice is for most dishes.

0:00:52.525,0:00:54.475
或者用于京酱肉丝的垫底
Or use it as bottom part of a plate of Beijing Bean Paste Pork.

0:00:54.475,0:00:57.625
同样是切丝我们再来看第四种切法
Next we are going to learn the fourth way.

0:00:57.800,0:00:59.850
首先我们将大葱切成长段
First let’s cut the scallions into longer sections

0:00:59.850,0:01:02.350
同学们这一步直接决定葱丝的长度
The length is as shown.

0:01:02.350,0:01:03.900
然后再切开一边
Cut into the center of the scallions

0:01:03.900,0:01:05.925
我们首先来展示错误的方法
Now I will first show you the next step in the wrong way.

0:01:05.925,0:01:07.850
切开一边之后直接切丝
That after cutting into the center, I’ll keep thin slicing the whole thing.

0:01:09.675,0:01:12.775
在不去除内芯的情况下切出来的丝比较粗狂
It will end up not looking pretty.

0:01:15.975,0:01:18.450
下面我们再来尝试去掉中间的内芯
The right way is to remove the center of the scallions first.

0:01:20.750,0:01:23.800
去掉内芯之后重叠在一起顺着切成细丝
Then stack the outer part and cut, the slicing will be nice and easy.

0:01:24.000,0:01:26.625
这样切出来的大葱丝更加的规则细小
You’ll end up getting thin and even scallion threads.

0:01:41.275,0:01:43.575
它比较适用于炝锅或者蒸鱼
This kind of scallion is best for steaming fish, or first step of stir frying. （炝锅有统一说法没）

0:01:43.575,0:01:45.525
说到蒸鱼所用的所有辅料
To talk about steaming a fish

0:01:45.525,0:01:47.000
请大家继续往下看
We will be introducing how to prepare its seasonings 

0:01:47.000,0:01:49.650
我们再准备小葱1小把切掉葱头
Get a bundle of spring onion, remove its white part

0:01:52.200,0:01:54.050
然后将小葱卷2圈
Roll the green part twice.

0:01:56.300,0:01:59.250
卷起来之后用手按住直刀切成细丝
Press the roll down firmly, then cut it thinly with no angle 

0:02:08.750,0:02:10.350
切好之后放入碗中
Put it into a bowl 

0:02:12.525,0:02:14.000
准备大红椒1个
 Get one big red pepper

0:02:14.000,0:02:16.200
对半切开之后再去除辣椒籽
Cut in half and remove all the seeds.

0:02:25.950,0:02:28.025
然后去除辣椒中多余的“肉”
Removing the extra “meat”

0:02:28.025,0:02:30.175
这一步的目的是让辣椒变得更薄
In order to make the pepper slice even thinner

0:02:30.175,0:02:32.650
这样才能切出更加细的辣椒丝
we then can cut it into fine threads.  

0:02:59.300,0:03:01.156
然后我们再准备生姜1小块
Get a small nugget of ginger

0:03:01.156,0:03:04.484
首先用垫刀切出薄片然后切成细丝即可
Thin slice it then cut it into very fine threads

0:03:04.484,0:03:07.600
鱼蒸好之后再将其撒在上面泼油即可
After the fish is steamed, put it on the top, then pour heated oil on it.

0:03:28.075,0:03:29.900
好了我的分享到此结束
That’s all for today.

0:03:29.900,0:03:31.900
如果你们还有感兴趣的小技巧
If you guys want to know other techniques 

0:03:31.900,0:03:33.525
可以在评论区留言
Let me know in the comment area.
