### ISSUE TITLE
[华农兄弟] 看野果挖竹笋 - https://youtu.be/qfjU4ENHdys

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#802]
https://youtu.be/qfjU4ENHdys
<p>&#35270;&#39057;&#21457;&#24067;&#20110; March 16, 2020 at 11:36AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
0:00:00.260,0:00:02.180
# 大家好  今天終於出太陽啦
Hi everyone! Finally, the sun shines today.

0:00:02.540,0:00:04.160
# 我上山上看一有沒有那個野果
We're going onto the hill and see if there are any wild fruits.

0:00:04.480,0:00:05.860
# 看下它們的產量高不高
Let's see if the yield is high or not.

0:00:06.700,0:00:07.280
# 在這上面
It's up there.

0:00:08.060,0:00:09.720
# 今年應該很高的產量哦
The yield this year should be rather high, you know,

0:00:10.280,0:00:12.120
# 因為它開花的時候沒怎麼下雨
cuz it barely rained when the flowers blossomed.

0:00:18.280,0:00:20.100
# 你看  這個是吊deng po哦
Look! This is "diao deng po" (note: local wild fruits).

0:00:20.620,0:00:22.000
# 今年的產日量特別高
The yield this year is exceptionally high.

0:00:22.760,0:00:23.720
# 一樹都是哦
They're all over the tree.

0:00:24.180,0:00:25.980
# 隨便找了棵樹都是那麼多的哦
And it's the same in any other trees.

0:00:26.920,0:00:29.640
# 所以 到了那個夏天的時候就有的吃啦
So, we're gonna have feast when, you know, when summer comes.

0:00:30.160,0:00:32.140
# 這些都是小小的  幾百個哦
These are all very small. I see hundreds of them,

0:00:32.700,0:00:33.940
# 一顆[SIC]樹上有幾百個
hundreds of them in just one tree.

0:00:34.860,0:00:36.900
# 現在還沒熟  到時候來摘
They're still green now. We're come again later.

0:00:41.460,0:00:42.380
# 這個就是
This is called,

0:00:42.480,0:00:44.680
# 我們這邊的方言叫re 萢子
it's called "re po le" in our dialect here.

0:00:45.600,0:00:47.760
# 它  這個應該也叫野草莓一樣的
It's, kind of, sort of like wild berries.

0:00:48.260,0:00:51.420
# 很好吃的哦  長  到熟了之後那麼大  紅的
It tastes really good. When they grow, I mean,  become ripe, they'll become that big and turn red.

0:00:51.920,0:00:54.480
# 到時候就用那個  針草串起來一串一串的
Then we can make strings of them, using the needle grass.

0:00:55.960,0:00:57.280
# 特別好吃 特別甜
It's really tasty, really sweet.

0:00:57.780,0:01:00.200
# 今年也好多啊  到處都是  這個
There are also a lot this year. They're everywhere, see?

0:01:00.980,0:01:03.960
# 你看  現在都是青的  到熟了之後就紅的
Look! They're now green, and will turn red when they become ripe.

0:01:04.780,0:01:05.860
# 你看  這些
Look! These are,

0:01:06.520,0:01:07.600
# 像個小光頭一樣
just like a little skin head.

0:01:08.440,0:01:08.980
# 好多
A lot!

0:01:14.240,0:01:15.100
# 這個荷蘭豆
These are snow peas.

0:01:15.540,0:01:16.640
# 這個花好靚的哦
The flowers are really beautiful,

0:01:17.100,0:01:18.120
# 像個小蝴蝶一樣
like a small butterfly.

0:01:20.860,0:01:22.700
# 這是隔壁老奶奶種的  你看
They belong to our neighbouring old lady.

0:01:23.320,0:01:25.120
# 八十多歲了  還種了那麼靚的菜
She's already in her eighties. But her veggies are still that beautiful.

0:01:26.100,0:01:27.360
# 這個不  就不能去摘了
We're not, we shouldn't pick them.

0:01:27.900,0:01:28.940
# 摘了就不厚道了
It would be too mean otherwise.

0:01:35.740,0:01:39.580
# 你看 今年長了好多枇杷果啊  一樹都是哦上面
Look! There are a lot loquats this year. They're all over the tree up there,

0:01:40.900,0:01:41.520
# 一大片
everywhere.

0:01:42.480,0:01:44.180
# 你看  這裡好多梨花啊
Look! Here are a lot of pear flowers.

0:01:45.020,0:01:46.040
# 這是梨樹來的
This is a pear tree.

0:01:47.120,0:01:50.360
# 到時候又有梨吃了 這個兄弟家的  這個梨樹
We'll then have pears later. It belongs to my buddy, this pear tree.

0:01:51.040,0:01:52.420
# 還有  棕花
Here are also, palm flowers.

0:01:57.620,0:01:59.120
# 這樹上還有饅頭哦
There are also figs in this tree.

0:02:00.220,0:02:01.700
# 這個  饅頭  饅頭果
These are, figs, figs fruits.

0:02:02.460,0:02:03.500
# 做那個涼粉
They can be used to make jelly.

0:02:06.000,0:02:07.580
# 這是梨花哦  這個
These are pear flowers you know.

0:02:11.200,0:02:13.140
# 全是梨花  今年的梨
All are pear flowers, the pear this year.

0:02:14.420,0:02:14.920
# 哇
Wa!

0:02:16.240,0:02:17.420
# 兄弟家的老母雞
My buddy's old hens

0:02:18.080,0:02:18.900
# 我去看一下
Let me take a look,

0:02:19.580,0:02:20.800
# 看一下有沒有雞蛋檢
and see if there are any eggs for me.

0:02:30.280,0:02:33.700
# 你看這個雞  個個都四五斤的哦  這種雞
Look at these hens! Each weighs at least two kilograms, these hens.

0:02:34.320,0:02:35.960
# 很好吃的  又肥
They taste really good, and they're fat.

0:02:37.960,0:02:39.080
# 走了  回家啦
Alright! Let's go back home.

0:02:39.760,0:02:40.900
# 有甚麼好看的
What's so interesting there?

0:02:41.500,0:02:44.540
# 剛好路過兄弟家的大棚哦  看一上他種甚麼菜
We just pass by my buddy's big shed. Let's see what veggies he has.

0:02:45.460,0:02:47.280
# 誒  又是茄子
Eh! Eggplants again.

0:02:47.920,0:02:49.960
# 兄弟咋麼那麼喜吃茄子嘞
What makes him like eggplants that much.

0:02:50.020,0:02:51.220
# 一百多個大棚哦
There are more than a hundred big sheds,

0:02:51.440,0:02:51.940
# 這裡
right here.

0:02:52.360,0:02:53.240
# 全是種的這個
But there's nothing but,

0:02:53.740,0:02:54.940
# 黃瓜跟這個茄子
cucumbers and, you know, eggplants.

0:02:56.560,0:02:59.380
# 這兄弟也不種點西瓜也可以呀  香瓜也好啊
Why doesn't this guy grow some melons, or watermelons, or whatever?

0:02:59.440,0:03:00.720
# 種點水果吃  好多啊
I mean, some fruits. It would certainly be really nice.

0:03:01.380,0:03:02.240
# 種這茄子
Eggplants, 

0:03:02.900,0:03:03.820
# 只能當菜吃
they're just nothing more than veggies.

0:03:06.120,0:03:07.560
# 唉 怎麼那麼多茄子
Ay! Why the hell are there some many eggplants?

0:03:11.020,0:03:12.140
# 這個樹很好爬的哦
I think I can climb this tree very easily.

0:03:12.400,0:03:13.440
# 一跳就跳上去了
A single hop is all that's needed.

0:03:16.400,0:03:17.680
# 一跳就跳上去
A single hop is all that's needed.

0:03:19.940,0:03:20.720
# 這個梅子
This is a plum.

0:03:21.320,0:03:23.400
# 這在都好大了哦  差不多就可以摘啦
It's now very big and can be picked very soon.

0:03:24.560,0:03:25.920
# 到時候我們摘點來泡酒
We'll then pick some and infuse them into liquor.

0:03:33.760,0:03:34.780
# 哇  這個大
Wa! This one is big!

0:03:35.440,0:03:36.420
# 這個好大啊
This one is really big.

0:03:39.700,0:03:40.800
# 還沒熟  不摘掉
It's still green. I leave it here.

0:03:41.520,0:03:42.540
# 你看  這些
Look! These are,

0:03:44.520,0:03:45.380
# 都很大啦
already very big now.

0:03:45.960,0:03:47.300
# 差不多可以吃了
I can eat them very soon.

0:03:49.380,0:03:50.080
# 摘一個下來
Let me pick one.

0:03:50.800,0:03:51.380
# 你看
Look!

0:03:52.040,0:03:52.760
# 小小的
A tiny one

0:03:53.300,0:03:54.440
# 這就是這個青梅
This is exactly a green plum.

0:03:56.160,0:03:56.880
# 很靚的哦這個
It's really beautiful.

0:03:58.540,0:03:59.500
# 這個還不能吃
It's still not to be eaten.

0:04:01.960,0:04:02.660
# 嗯  這
Um! It's...

0:04:05.680,0:04:06.420
# 好苦
bitter!

0:04:06.720,0:04:07.320
# 不太熟
It's not ripe.

0:04:12.260,0:04:13.320
# 但這個梅子味
But it's really rich,

0:04:13.840,0:04:14.720
# 很十足哦
in the flavour of plum.

0:04:17.480,0:04:19.360
# 啊~受不了
Ah~ I can't stand it!

0:04:21.240,0:04:21.880
# 你看這個
Look at this one!

0:04:22.140,0:04:23.340
# 這個楊梅也開花了哦
The plum flowers have also blossomed.

0:04:24.440,0:04:24.940
# 好多啊
A lot!

0:04:25.780,0:04:26.580
# 開了小花
Small flowers

0:04:36.240,0:04:37.980
# 你看  這笋子都長出來啦
Look! The bamboo shoot is already coming out.

0:04:39.060,0:04:40.060
# 好多  這裡有一個
A lot! Here's one.

0:04:40.420,0:04:42.040
# 那裡有一個  還不大的
There's another one. That one is not that big.

0:04:45.380,0:04:46.420
# 你看  這裡有一個
Look! Here's one.

0:04:47.080,0:04:48.540
# 土都裂開啦  還有
The soil has already cracked open. One more,

0:04:48.940,0:04:49.520
# 這裡有一個
one more here.

0:04:52.940,0:04:54.540
# 好多啊  這笋子
They're everywhere, the shoots.

0:05:05.260,0:05:07.640
# 你看這個李子樹  有很多小李子哦
Have a loot at his prune tree. There are a lot of small prunes!

0:05:08.960,0:05:10.040
# 你看 很小的
Look! They're really small.

0:05:10.600,0:05:12.880
# 你看  這個  很小的這個李子
Look! Here, the prunes are really small.

0:05:13.920,0:05:15.160
# 好多  一樹都是
A lot! All over the tree.

0:05:18.340,0:05:20.740
# 這個也是那個野生的哦 沒人要的
These are also, you know, wild, and don't belong to anyone.

0:05:20.980,0:05:22.320
# 就長在那個河邊上
They're just growing on the riverside.

0:05:23.440,0:05:24.880
# 到時候我們想摘的時候就來摘
We can come and pick some later whenever we want.

0:05:26.260,0:05:27.400
# 別人不會說我的
Nobody's gonna say anything.

0:05:35.300,0:05:37.300
# 轉了一圈  甚麼都沒找到
Now we're back, without finding anything. 

0:05:37.340,0:05:39.080
# 我上山上挖個竹笋來烤
Let me go onto the hill, dig a bamboo shoot, and grill it.

0:05:40.120,0:05:42.040
# 山上竹笋已經冒出頭來了哦
The heads of the bamboo shoots there are already coming out.

0:05:42.880,0:05:43.720
# 一鋤頭就沒了
Put down the hoe, gone!

0:05:49.300,0:05:49.800
# (沒有原字幕)
Puppies!

0:05:51.060,0:05:51.560
# (沒有原字幕)
Puppies!

0:06:21.560,0:06:22.500
# 你看  這裡有一個
Look! Here's one.

0:06:23.920,0:06:24.560
# 還太了啦
It's still too small.

0:06:25.500,0:06:26.420
# 去搞個大點啦
I'm gonna get a bigger one.

0:06:31.160,0:06:31.900
# 這裡有一個大的
Here's a big one!

0:06:34.480,0:06:35.080
# 你看  這個
Look! This is,

0:06:35.800,0:06:36.640
# 這個夠大的  這個
this is big enough, yea.

0:06:37.520,0:06:39.160
# 你看  啊  這個  那麼大的
Look! Ah! This one, is so big!

0:06:41.540,0:06:42.860
# 這個是春笋啊
This is a spring shoot, you know.

0:06:43.840,0:06:45.400
# 它長大就是一棵竹子
I would become a bamboo if it grows up.

0:06:48.920,0:06:50.640
# 不能挖那麼多  挖一個就夠了
I can't get too many. Just one is enough.

0:06:56.560,0:06:57.600
# 你看  這個
Have a look at it!

0:06:58.360,0:06:59.300
# 我拿回去
I'm gonna take it back,

0:06:59.900,0:07:00.680
# 拿去去烤
take it back and grill it.

0:07:02.920,0:07:03.420
# 夠了
Enough

0:07:03.660,0:07:04.360
# 一個就夠了
One is already enough.

0:07:04.480,0:07:05.100
# 那麼大
It's that big.

0:07:31.360,0:07:32.560
# 高壓水槍一樣的
It's just like a high-pressure water gun.

0:07:41.220,0:07:43.320
# 一層一層的把它剝掉
I'm peeling it off layer by layer.

0:07:46.900,0:07:47.520
# 這是
These are,

0:07:48.680,0:07:49.920
# 剛長出來的莖
the stems that have just come out.

0:07:51.780,0:07:52.380
# 你看
Look!

0:07:53.820,0:07:55.040
# 很靚哦  這個
It's really beautiful!

0:07:59.900,0:08:00.940
# 這樣繼續剝
Keep peeling

0:08:03.200,0:08:05.480
# 肉好少的哦這個  肉就一點點
There's not so much to eat, just a tiny little bit.

0:08:27.920,0:08:29.000
# 就那麼一點點
Just a tiny little bit.

0:08:29.760,0:08:30.880
# 等下你少吃一點
So you're going to have less.

0:08:37.060,0:08:38.560
# 就這一點  哈哈
Just a bit here, ha ha!

0:08:51.340,0:08:51.840
# 把這個
I'm gonna...

0:08:52.420,0:08:53.380
# 你看  這個竹笋
Look! This bamboo shoot.

0:09:02.700,0:09:05.560
# 很靚哦  這個  等下就這樣  就這樣去烤
It's so beautiful! This, this can be, can be then grilled right away.

0:09:07.080,0:09:08.820
# 要不然把它對半先破開先
Or, shall I first, cut it into halves first?

0:09:10.680,0:09:11.600
# 你看  這聲音
Look! The sound!

0:09:13.200,0:09:13.700
# 好
Good!

0:09:33.900,0:09:35.040
# 哎呀 好香啊
Aya! It smells really nice!

0:10:32.000,0:10:36.200
# 把竹笋  把這個竹笋  把這個竹笋裏起來
Let me wrap, wrap the, wrap the bamboo shoot,

0:10:36.720,0:10:38.440
# 放到那個  火堆里面去
put it, into the fire,

0:10:38.720,0:10:39.300
# (沒有原字幕，我聽到好像是「煨」，都想把它譯了)
and grill it.

0:10:45.160,0:10:46.380
# 先把它烤  烤熟
Grill, grill it first.

0:10:46.820,0:10:48.620
# 烤熟之後我們再加上那個
They we can put some, you know,

0:10:49.600,0:10:50.520
# 加上孜然
put some cummin powder,

0:10:51.320,0:10:52.260
# 加上醬油
put some soy sauce.

0:10:53.880,0:10:54.700
# 就可以吃二
And then it can served.

0:10:58.680,0:11:01.200
# 你看  就這樣 把它奶到那  火堆里面去
Look! Then, I can simply, throw it, into the fire.

0:11:01.220,0:11:02.480
# 放在這裡燒就可以了
Leave it here, grill it, that's it.

0:11:04.420,0:11:06.540
# 燒個二十多分鐘就夠了
Leaving it here for a good twenty minutes would be enough.

0:11:09.040,0:11:09.880
# 這熟了哦
It's alright now.

0:11:14.160,0:11:15.140
# 好香啊
It smells so good!

0:11:15.900,0:11:17.300
# 加點醬油就可以吃的  這個
With some soy sauce, it can be eaten right away.

0:11:18.320,0:11:19.120
# 這個太燙啦
It's too hot.

0:11:22.200,0:11:24.440
# 要等一下  放在這裡等一下再
Leave it here, leave it here for a while, and then,

0:11:24.960,0:11:26.440
# 等它熟了之後我再那個
When it's done, we'll, you know,

0:11:27.260,0:11:28.120
# 再去吃
we'll eat it.

0:11:30.560,0:11:31.400
# 火太燙啦
The fire is too hot.

0:11:47.740,0:11:49.380
# 變成竹笋乾了這個
It has become dried bamboo shoot.

0:11:52.320,0:11:53.220
# 火燒啦
It's burnt.

0:11:53.640,0:11:55.200
# 叫我弟看火看火
I asked my younger brother to watch the fire.

0:11:55.860,0:11:57.740
# 看著叫他看著別燒掉啦
Let it, I asked him not to let it burnt.

0:11:58.300,0:11:59.200
# 就燒掉了
And now it's burnt.

0:12:00.820,0:12:01.400
# 靠下住啊
What an unreliable guy!

0:12:01.860,0:12:02.540
# 不能吃了
No, it's not edible.

0:12:03.520,0:12:05.140
# 打開來看一下這個能不能吃
Let me open it and see if it's edible.

0:12:12.980,0:12:13.840
# 好香啊
It smells so good!

0:12:16.280,0:12:17.100
# 真的很香
Really good!

0:12:22.900,0:12:23.400
# 嗯
Um!

0:12:24.100,0:12:25.020
# 還有竹子的甜味
There's still the sweetness of bamboo.

0:12:29.660,0:12:31.180
# 嗯  還可以哦
Um! It's not too bad!

0:12:32.440,0:12:35.420
# 還有竹子的那個清香味  在這裡面  竹笋的清香味
There's still the scent of bamboo, inside, the scent of bamboo shoot.
#https://youtu.be/qfjU4ENHdys

#华农兄弟：提前踩点，看下村里野果结果情况，再挖1个竹笋来烤
#Huanong Brothers: We go site visit and see how the wild fruits in our village are growing. Then we dig a bamboo shoot and grill it.

0:12:36.200,0:12:36.960
# 還可以吃
It's still edible.

0:12:39.340,0:12:39.840
# 嗯
Um!

0:12:42.260,0:12:43.700
# 可以哦  很香
Not bad! It smells really good!

0:12:44.540,0:12:45.040
# 很脆
And it's crunchy.

0:12:50.180,0:12:51.060
# 你們想不想吃
Do you guys want some?

0:12:52.420,0:12:54.220
# 這是素來的  你們不吃的
It's veggie. You don't like it.

0:12:54.920,0:12:55.420
# 你們吃肉
You guys eat only meat.

0:13:03.840,0:13:05.240
# 給你們吃了  不要啦
It's yours now. I don't want it anymore.

0:13:23.580,0:13:25.300
# 你看  這個皮都可以撕的下來
Look! It can be peeled.

0:13:31.040,0:13:33.220
# 好啦  給你們吃啦  不好吃
Alright! It's yours now! It's tastes so bad.

0:13:33.700,0:13:34.740
# 快  快點吃掉啊
Come, c'mon! Finish it!

0:13:35.020,0:13:37.280
# 今晚給你們  這就是你們的晚餐  吃掉
Tonight you'll have...It's your dinner. Finish it!
