### ISSUE TITLE
[老饭骨] 汆水蛋 - https://www.youtube.com/watch?v=eZqg2C8wsoI&t=25s

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#807]
**视频链接**：https://www.youtube.com/watch?v=eZqg2C8wsoI&t=25s

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

**请翻译以下全部内容**

---

标题（翻译主要意思即可，不要超过 100 个字符）
```
【国宴大师•汆水蛋】有实力火遍全国的汆水蛋，极嫩极鲜、低脂健康，二伯家传秘方大揭秘！ |老饭骨
```

简介
```
小友们好，今天带来二伯家传的奶奶汆水蛋。
这道菜是由二伯的奶奶传承的，看似平凡但不简单，若忽视一些细节则整个味道都不对。
这道菜食材简单，只用了韭菜、鸡蛋、酱油、味精和香油。但手法稍微讲究一点，得把鸡蛋燉熟，小友们可要看仔细了！
关于这汆水蛋的秘诀，二伯可是犹豫了半天要不要公布，小友们快来视频里找答案吧！

```

字幕
```
1
00:00:00,120 --> 00:00:01,800
我跟你说这个菜 我告诉你

2
00:00:01,800 --> 00:00:04,920
都能火遍整个中国 太健康了

3
00:00:04,920 --> 00:00:09,520
下一个节目 汆水蛋

4
00:00:09,520 --> 00:00:11,920
据说这水蛋是奶奶传承的

5
00:00:11,920 --> 00:00:13,960
对我奶奶传承给我

6
00:00:13,960 --> 00:00:16,240
我再教给我徒弟

7
00:00:16,240 --> 00:00:18,800
徒弟的味道做的还真不对

8
00:00:18,800 --> 00:00:19,400
就简单东西

9
00:00:19,400 --> 00:00:21,080
后来我告诉他细节在哪

10
00:00:21,080 --> 00:00:23,400
你看见没有大爷 火咱先点上

11
00:00:23,400 --> 00:00:25,640
把韭菜切的跟馅儿似的

12
00:00:25,640 --> 00:00:27,360
就是切馅儿一样

13
00:00:27,360 --> 00:00:29,360
你看 在家里这道菜

14
00:00:29,360 --> 00:00:31,880
既好吃又营养 还谁都能做

15
00:00:31,880 --> 00:00:35,400
但是就有一个窍门

16
00:00:35,400 --> 00:00:37,440
一会儿我在制作当中

17
00:00:37,440 --> 00:00:39,040
我给你们讲了

18
00:00:39,040 --> 00:00:42,280
要不讲永远也不知道

19
00:00:42,280 --> 00:00:43,160
还真不好吃

20
00:00:43,160 --> 00:00:47,200
半斤韭菜 六个鸡蛋

21
00:00:47,200 --> 00:00:48,440
其实现在鸡蛋没有

22
00:00:48,440 --> 00:00:50,560
过去奶奶那时候做的好吃

23
00:00:50,560 --> 00:00:52,280
没有那鸡蛋好

24
00:00:52,280 --> 00:00:54,520
水量一定要充足

25
00:00:54,520 --> 00:00:56,040
为什么说健康

26
00:00:56,040 --> 00:00:58,200
你看不加淀粉 就是韭菜鸡蛋

27
00:00:58,200 --> 00:00:59,720
不加淀粉不加盐

28
00:00:59,720 --> 00:01:03,080

29
00:01:03,080 --> 00:01:06,840
你看这就行了 直接下锅

30
00:01:06,840 --> 00:01:10,800
这个火要大了 你看可以小一点

31
00:01:13,480 --> 00:01:17,960
微微的小一点 别太小了 

32
00:01:18,640 --> 00:01:22,000
燉熟 这就叫燉

33
00:01:25,600 --> 00:01:26,880
燉熟

34
00:01:26,880 --> 00:01:30,360
这也是一种很奇妙的技巧

35
00:01:30,360 --> 00:01:33,600
慢推慢燉

36
00:01:33,600 --> 00:01:34,640
你看说这菜简单

37
00:01:34,640 --> 00:01:39,560
但是它确实需要一定的技法

38
00:01:39,560 --> 00:01:40,920

39
00:01:40,920 --> 00:01:43,400
你看二位大师帮着我忙活这点事

40
00:01:43,400 --> 00:01:45,280
我主要是掌握一个火力

41
00:01:45,280 --> 00:01:46,920
这菜简单吗 它不简单

42
00:01:48,160 --> 00:01:49,280
往往有些菜

43
00:01:49,280 --> 00:01:52,160
越简单的方法是越不简单

44
00:01:52,160 --> 00:01:56,280
平凡当中没有平凡 对不平凡

45
00:01:56,280 --> 00:01:58,080
简单当中又不简单

46
00:01:58,080 --> 00:02:05,440

47
00:02:05,440 --> 00:02:07,440
你看 还是不行

48
00:02:09,280 --> 00:02:11,120
开锅了你看

49
00:02:11,120 --> 00:02:12,360

50
00:02:12,360 --> 00:02:14,000
是开锅 是不开锅呢

51
00:02:14,000 --> 00:02:15,160
得开一点

52
00:02:15,160 --> 00:02:16,480
但是也别完全开大了

53
00:02:16,480 --> 00:02:22,080
把鸡蛋得给它煮熟了

54
00:02:22,080 --> 00:02:23,400

55
00:02:23,400 --> 00:02:26,600
水汆

56
00:02:26,600 --> 00:02:27,880
似开非开

57
00:02:27,880 --> 00:02:36,400

58
00:02:36,400 --> 00:02:40,160
大家已经是静下来了

59
00:02:40,160 --> 00:02:42,480
这是沁熟的

60
00:02:42,480 --> 00:02:43,440

61
00:02:44,560 --> 00:02:47,080
有点像鸡豆花啊 对啊

62
00:02:47,080 --> 00:02:48,640
这马上该熟了

63
00:02:48,640 --> 00:02:52,280

64
00:02:53,840 --> 00:02:56,920
这沫子可以要可以不要

65
00:02:56,920 --> 00:02:58,480
基本就快熟了

66
00:02:58,480 --> 00:03:00,200

67
00:03:02,440 --> 00:03:04,920
马上该熟了

68
00:03:05,400 --> 00:03:09,200
鲜嫩 这韭菜本身也提鲜

69
00:03:09,200 --> 00:03:10,720
关火了

70
00:03:10,720 --> 00:03:11,920

71
00:03:11,920 --> 00:03:13,520
你看这水太多了

72
00:03:13,520 --> 00:03:17,280

73
00:03:19,520 --> 00:03:20,840
豆花似的

74
00:03:20,840 --> 00:03:22,680
关键的来了

75
00:03:22,680 --> 00:03:25,440

76
00:03:25,440 --> 00:03:28,920
酱油 您觉得咸味够不够

77
00:03:28,920 --> 00:03:31,480
什么酱油都行 够了

78
00:03:31,480 --> 00:03:34,360
这咸味够不够 够了

79
00:03:34,360 --> 00:03:36,640

80
00:03:38,040 --> 00:03:39,240
你看这个温度多少度啊

81
00:03:39,240 --> 00:03:41,600
到不了八十度吧 到不了

82
00:03:41,600 --> 00:03:43,480
就是说这种情况下

83
00:03:43,480 --> 00:03:45,120
为什么是健康菜

84
00:03:45,120 --> 00:03:46,480
这味精一点毒素没有

85
00:03:46,480 --> 00:03:48,480
就把这点味精就加进去就行了

86
00:03:48,480 --> 00:03:50,560

87
00:03:50,560 --> 00:03:51,640
香油

88
00:03:51,640 --> 00:03:53,720
这个菜我是今天头一次

89
00:03:53,720 --> 00:03:55,080
亲自在现场看见的

90
00:03:55,080 --> 00:03:57,160
过去是在电视上孙大师做过

91
00:03:57,160 --> 00:03:59,160
做过之后再也没做过

92
00:03:59,160 --> 00:04:01,520
你再不做也失传了

93
00:04:01,520 --> 00:04:03,640
这个菜极嫩

94
00:04:03,640 --> 00:04:04,920
大哥你看这就完了

95
00:04:04,920 --> 00:04:06,560
您看 一会您尝尝

96
00:04:06,560 --> 00:04:08,640
我跟你说这个菜

97
00:04:08,640 --> 00:04:10,280
我告诉你都能火遍整个中国

98
00:04:10,280 --> 00:04:11,560
太健康了

99
00:04:11,560 --> 00:04:14,080
大爷迫切的吃上了

100
00:04:14,080 --> 00:04:15,840
急的吃上了

101
00:04:15,840 --> 00:04:16,200

102
00:04:16,200 --> 00:04:19,640
嫩 真鲜

103
00:04:19,640 --> 00:04:23,800
千万别加酱油了 正好 够咸

104
00:04:23,800 --> 00:04:25,360
最关键的东西你知道在哪儿么

105
00:04:25,360 --> 00:04:27,760
我是说还是不说跟网友们

106
00:04:27,760 --> 00:04:29,240
那肯定得说

107
00:04:29,240 --> 00:04:30,320
您发现没有 这韭菜都是脆的

108
00:04:30,320 --> 00:04:31,920
我跟你说 我说是不说

109
00:04:31,920 --> 00:04:33,080
必须说

110
00:04:33,080 --> 00:04:35,200
要说了就没有秘密了谁都能做

111
00:04:35,200 --> 00:04:36,560
要什么秘密

112
00:04:36,560 --> 00:04:39,600
现在你孙大师胸怀这么大

113
00:04:39,600 --> 00:04:41,520
孙大师你就叫网友们学会了

114
00:04:41,520 --> 00:04:43,760
人也知道你奶奶啊

115
00:04:43,760 --> 00:04:46,880
其实我一揭秘您就知道了

116
00:04:46,880 --> 00:04:47,720

117
00:04:47,720 --> 00:04:49,440
我关火调味

118
00:04:49,440 --> 00:04:51,520
如果说你要开着火 有一点火调味

119
00:04:51,520 --> 00:04:54,480
这菜马上这味道就变了

120
00:04:54,480 --> 00:04:59,160
它必须香油 味精 酱油不能着热

“我是大爷”00:05:02,
```

**Comment by Summer0208** [comment]
认领

**Comment by Summer0208** [comment]
1
00:00:00,120 --> 00:00:01,800
我跟你说这个菜 我告诉你
You know what,
2
00:00:01,800 --> 00:00:04,920
都能火遍整个中国 太健康了
it’s going to be popular all over China by it’s healthiness. 
3
00:00:04,920 --> 00:00:09,520
下一个节目 汆水蛋
up coming show: Cuan Shui dan(boiled egg with Chinese chives). 
4
00:00:09,520 --> 00:00:11,920
据说这水蛋是奶奶传承的
I heard that this dish is heritaged from your grandma? 
5
00:00:11,920 --> 00:00:13,960
对我奶奶传承给我
Yeah, My grandma past it to me. 
6
00:00:13,960 --> 00:00:16,240
我再教给我徒弟
And I taught it to my disciples. 
7
00:00:16,240 --> 00:00:18,800
徒弟的味道做的还真不对
However, my disciples couldn’t get the flavor right.  
8
00:00:18,800 --> 00:00:19,400
就简单东西
for such a simple recipe,
9
00:00:19,400 --> 00:00:21,080
后来我告诉他细节在哪
until I told him where the tricky part is. 
10
00:00:21,080 --> 00:00:23,400
你看见没有大爷 火咱先点上
Look,Da Ye. Frist we turn on the stove. 
11
00:00:23,400 --> 00:00:25,640
把韭菜切的跟馅儿似的
Chop the chives like making stuffing. 
12
00:00:25,640 --> 00:00:27,360
就是切馅儿一样
it’s just like how you make stuffing. 
13
00:00:27,360 --> 00:00:29,360
你看 在家里这道菜
Look, cooking this dish back at home,
14
00:00:29,360 --> 00:00:31,880
既好吃又营养 还谁都能做
it's both delicious and healthy.; and everyone can make it. 
15
00:00:31,880 --> 00:00:35,400
但是就有一个窍门
but there’s just one trick. 
16
00:00:35,400 --> 00:00:37,440
一会儿我在制作当中
I will talk about it later during the process. 
17
00:00:37,440 --> 00:00:39,040
我给你们讲了
You know what, 
18
00:00:39,040 --> 00:00:42,280
要不讲永远也不知道
If I don’t point it out, people will never know. 
19
00:00:42,280 --> 00:00:43,160
还真不好吃
and it won’t taste good. 
20
00:00:43,160 --> 00:00:47,200
半斤韭菜 六个鸡蛋
250 grams of chives with six eggs. 
21
00:00:47,200 --> 00:00:48,440
其实现在鸡蛋没有
the egg nowadays does not 
22
00:00:48,440 --> 00:00:50,560
过去奶奶那时候做的好吃
taest as good as eggs from grandma’s age.  
23
00:00:50,560 --> 00:00:52,280
没有那鸡蛋好
not tasty as their eggs. 
24
00:00:52,280 --> 00:00:54,520
水量一定要充足
water has to be sufficient
25
00:00:54,520 --> 00:00:56,040
为什么说健康
Why do I say it’s healthy, 
26
00:00:56,040 --> 00:00:58,200
你看不加淀粉 就是韭菜鸡蛋
you see I don’ t put starch,just chives and eggs. 
27
00:00:58,200 --> 00:00:59,720
不加淀粉不加盐
No starch, no salt. 
28
00:00:59,720 --> 00:01:03,080

29
00:01:03,080 --> 00:01:06,840
你看这就行了 直接下锅
Look, that’s it. Directly into the pot.  
30
00:01:06,840 --> 00:01:10,800
这个火要大了 你看可以小一点
if there’s too much heat, you can turn it down a bit
31
00:01:13,480 --> 00:01:17,960
微微的小一点 别太小了 
just turn down a little bit, not too much. 
32
00:01:18,640 --> 00:01:22,000
燉熟 这就叫燉
simmer it done. This is called simmer. 
33
00:01:25,600 --> 00:01:26,880
燉熟
simmer it done. 
34
00:01:26,880 --> 00:01:30,360
这也是一种很奇妙的技巧
this is also an interesting technique. 
35
00:01:30,360 --> 00:01:33,600
慢推慢燉
slowly push, slowly simmer. 
36
00:01:33,600 --> 00:01:34,640
你看说这菜简单
The dish looks easy, 
37
00:01:34,640 --> 00:01:39,560
但是它确实需要一定的技法
but needs quite a bit of technique
38
00:01:39,560 --> 00:01:40,920

39
00:01:40,920 --> 00:01:43,400
你看二位大师帮着我忙活这点事
You two masters are helping me for this simple task. 
40
00:01:43,400 --> 00:01:45,280
我主要是掌握一个火力
I’m just controling the heat. 
41
00:01:45,280 --> 00:01:46,920
这菜简单吗 它不简单
Is the dish easy? No it’s not. 
42
00:01:48,160 --> 00:01:49,280
往往有些菜
There is always dishes
43
00:01:49,280 --> 00:01:52,160
越简单的方法是越不简单
looks simple but acctully not. 
44
00:01:52,160 --> 00:01:56,280
平凡当中没有平凡 对不平凡
what's common is not common
45
00:01:56,280 --> 00:01:58,080
简单当中又不简单
it’s simple but not easy. 

46
00:01:58,080 --> 00:02:05,440

47
00:02:05,440 --> 00:02:07,440
你看 还是不行
still not yet. 
48
00:02:09,280 --> 00:02:11,120
开锅了你看
see, it’s boiling now
49
00:02:11,120 --> 00:02:12,360

50
00:02:12,360 --> 00:02:14,000
是开锅 是不开锅呢
You want it boil or not?
51
00:02:14,000 --> 00:02:15,160
得开一点
just boil a little bit. 
52
00:02:15,160 --> 00:02:16,480
但是也别完全开大了
but not over boiled. 
53
00:02:16,480 --> 00:02:22,080
把鸡蛋得给它煮熟了
just get the egg cooked. 
54
00:02:22,080 --> 00:02:23,400

55
00:02:23,400 --> 00:02:26,600
水汆
boiling a little bit. 
56
00:02:26,600 --> 00:02:27,880
似开非开
semes boil but not fully boil. 
57
00:02:27,880 --> 00:02:36,400

58
00:02:36,400 --> 00:02:40,160
大家已经是静下来了
it’s getting quiet. 
59
00:02:40,160 --> 00:02:42,480
这是沁熟的
this is cooked through soaking
60
00:02:42,480 --> 00:02:43,440

61
00:02:44,560 --> 00:02:47,080
有点像鸡豆花啊 对啊
like how we cook Ji Dou Hua. Right?
62
00:02:47,080 --> 00:02:48,640
这马上该熟了
almost cooked now. 
63
00:02:48,640 --> 00:02:52,280

64
00:02:53,840 --> 00:02:56,920
这沫子可以要可以不要
it’s opptional to leave the foam here or not. 
65
00:02:56,920 --> 00:02:58,480
基本就快熟了
it’s basically done. 
66
00:02:58,480 --> 00:03:00,200

67
00:03:02,440 --> 00:03:04,920
马上该熟了
it should be cooked. 
68
00:03:05,400 --> 00:03:09,200
鲜嫩 这韭菜本身也提鲜
tender and flavorful, and the chives also make it flavorful. 
69
00:03:09,200 --> 00:03:10,720
关火了
turning off the stove
70
00:03:10,720 --> 00:03:11,920

71
00:03:11,920 --> 00:03:13,520
你看这水太多了
You see, it’s too much of water. 
72
00:03:13,520 --> 00:03:17,280

73
00:03:19,520 --> 00:03:20,840
豆花似的
just like dou hua. 
74
00:03:20,840 --> 00:03:22,680
关键的来了
now here is the point. 
75
00:03:22,680 --> 00:03:25,440

76
00:03:25,440 --> 00:03:28,920
酱油 您觉得咸味够不够
soy sauce, do you think it’s salty enough? 
77
00:03:28,920 --> 00:03:31,480
什么酱油都行 够了
any kind of soy sauce. that’s enough. 
78
00:03:31,480 --> 00:03:34,360
这咸味够不够 够了
it it enough salt? that’s enough. 
79
00:03:34,360 --> 00:03:36,640

80
00:03:38,040 --> 00:03:39,240
你看这个温度多少度啊
What do you think is the temperature? 
81
00:03:39,240 --> 00:03:41,600
到不了八十度吧 到不了
less than 80C? probeblly not there. 
82
00:03:41,600 --> 00:03:43,480
就是说这种情况下
in this case, 
83
00:03:43,480 --> 00:03:45,120
为什么是健康菜
why is it a healthy dish? 
84
00:03:45,120 --> 00:03:46,480
这味精一点毒素没有
MSG does not have negative effects. 
85
00:03:46,480 --> 00:03:48,480
就把这点味精就加进去就行了
just put this bit of MSG in it. 
86
00:03:48,480 --> 00:03:50,560

87
00:03:50,560 --> 00:03:51,640
香油
sesame oil
88
00:03:51,640 --> 00:03:53,720
这个菜我是今天头一次
it’s my first time see the process
89
00:03:53,720 --> 00:03:55,080
亲自在现场看见的
live in person.  
90
00:03:55,080 --> 00:03:57,160
过去是在电视上孙大师做过
I used to see Master Sun making it on TV. 
91
00:03:57,160 --> 00:03:59,160
做过之后再也没做过
afterwards,it’s never been cooked again. 
92
00:03:59,160 --> 00:04:01,520
你再不做也失传了
the process is lost if you don't make it. 
93
00:04:01,520 --> 00:04:03,640
这个菜极嫩
this dish is extremely tender.
94
00:04:03,640 --> 00:04:04,920
大哥你看这就完了
it’s done by now. 
95
00:04:04,920 --> 00:04:06,560
您看 一会您尝尝
look, try it later. 
96
00:04:06,560 --> 00:04:08,640
我跟你说这个菜
You know what about this dish, 
97
00:04:08,640 --> 00:04:10,280
我告诉你都能火遍整个中国
I tell you it’s going to be popular all over China. 
98
00:04:10,280 --> 00:04:11,560
太健康了
It’s too healthy. 
99
00:04:11,560 --> 00:04:14,080
大爷迫切的吃上了
Da Ye can't wait to try it. 
100
00:04:14,080 --> 00:04:15,840
急的吃上了
He can’t wait 
101
00:04:15,840 --> 00:04:16,200

102
00:04:16,200 --> 00:04:19,640
嫩 真鲜
it’s tender, and so flavourful. 
103
00:04:19,640 --> 00:04:23,800
千万别加酱油了 正好 够咸
No more soy sauce, it’s good, salty enough.  
104
00:04:23,800 --> 00:04:25,360
最关键的东西你知道在哪儿么
you know what’s the tricky part is? 
105
00:04:25,360 --> 00:04:27,760
我是说还是不说跟网友们
Should I tell all our audiance? 
106
00:04:27,760 --> 00:04:29,240
那肯定得说
You have to say it. 
107
00:04:29,240 --> 00:04:30,320
您发现没有 这韭菜都是脆的
You see, the chive is crispy. 
108
00:04:30,320 --> 00:04:31,920
我跟你说 我说是不说
Should I keep it a secret? 
109
00:04:31,920 --> 00:04:33,080
必须说
You must say. 
110
00:04:33,080 --> 00:04:35,200
要说了就没有秘密了谁都能做
If I give it out, everyone is able to make it. 
111
00:04:35,200 --> 00:04:36,560
要什么秘密
no more mystery
112
00:04:36,560 --> 00:04:39,600
现在你孙大师胸怀这么大
Master Sun you are broadminded,
113
00:04:39,600 --> 00:04:41,520
孙大师你就叫网友们学会了
just let our audiance learn. 
114
00:04:41,520 --> 00:04:43,760
人也知道你奶奶啊
so that we also know your grandma’s recipy
115
00:04:43,760 --> 00:04:46,880
其实我一揭秘您就知道了
it’s quite obvious 
116
00:04:46,880 --> 00:04:47,720

117
00:04:47,720 --> 00:04:49,440
我关火调味
I turned off the stove to season it. 
118
00:04:49,440 --> 00:04:51,520
如果说你要开着火 有一点火调味
If you season it with the stove on, 
119
00:04:51,520 --> 00:04:54,480
这菜马上这味道就变了
the flavor would change immediately. 
120
00:04:54,480 --> 00:04:59,160
它必须香油 味精 酱油不能着热
sesame oil, MSG, soy sauce are sensitive to heat
“我是大爷”00:05:02,

**Comment by Summer0208** [comment]
【国宴大师•汆水蛋】有实力火遍全国的汆水蛋，极嫩极鲜、低脂健康，二伯家传秘方大揭秘！ |老饭骨
【State Banquet Master Chef】eggs that have the strength to be famous all over the country, extremely tender, fresh, low-fat, and healthy. | Lao Fan Gu 

小友们好，今天带来二伯家传的奶奶汆水蛋。
这道菜是由二伯的奶奶传承的，看似平凡但不简单，若忽视一些细节则整个味道都不对。
这道菜食材简单，只用了韭菜、鸡蛋、酱油、味精和香油。但手法稍微讲究一点，得把鸡蛋燉熟，小友们可要看仔细了！
关于这汆水蛋的秘诀，二伯可是犹豫了半天要不要公布，小友们快来视频里找答案吧！
Hello friends, today Er Bai brings us traditional Cuan Shui Dan from his grandama. 
This recipe is a heritage of Er Bai’s grandma. It looks simple but not easy. One tiny step missing then the whole flavor will be wrong. The ingredients are simple, using only Chinese Chives, eggs, soy sauce, MSG and sesame oil. However, the technique is tricky that the eggs are simmered, watch out for that, friends. 
About the secret recipe, Er Bai hesitated for a long time to announce it, come find the answer in the video, friends!

1
00:00:00,120 --> 00:00:01,800
我跟你说这个菜 我告诉你
You know what,
2
00:00:01,800 --> 00:00:04,920
都能火遍整个中国 太健康了
it’s going to be popular all over China by it’s healthiness. 
3
00:00:04,920 --> 00:00:09,520
下一个节目 汆水蛋
up coming show: Cuan Shui dan(boiled egg with Chinese chives). 
4
00:00:09,520 --> 00:00:11,920
据说这水蛋是奶奶传承的
I heard that this dish is heritaged from your grandma? 
5
00:00:11,920 --> 00:00:13,960
对我奶奶传承给我
Yeah, My grandma past it to me. 
6
00:00:13,960 --> 00:00:16,240
我再教给我徒弟
And I taught it to my disciples. 
7
00:00:16,240 --> 00:00:18,800
徒弟的味道做的还真不对
However, my disciples couldn’t get the flavor right.  
8
00:00:18,800 --> 00:00:19,400
就简单东西
for such a simple recipe,
9
00:00:19,400 --> 00:00:21,080
后来我告诉他细节在哪
until I told him where the tricky part is. 
10
00:00:21,080 --> 00:00:23,400
你看见没有大爷 火咱先点上
Look,Da Ye. Frist we turn on the stove. 
11
00:00:23,400 --> 00:00:25,640
把韭菜切的跟馅儿似的
Chop the chives like making stuffing. 
12
00:00:25,640 --> 00:00:27,360
就是切馅儿一样
it’s just like how you make stuffing. 
13
00:00:27,360 --> 00:00:29,360
你看 在家里这道菜
Look, cooking this dish back at home,
14
00:00:29,360 --> 00:00:31,880
既好吃又营养 还谁都能做
it's both delicious and healthy.; and everyone can make it. 
15
00:00:31,880 --> 00:00:35,400
但是就有一个窍门
but there’s just one trick. 
16
00:00:35,400 --> 00:00:37,440
一会儿我在制作当中
I will talk about it later during the process. 
17
00:00:37,440 --> 00:00:39,040
我给你们讲了
You know what, 
18
00:00:39,040 --> 00:00:42,280
要不讲永远也不知道
If I don’t point it out, people will never know. 
19
00:00:42,280 --> 00:00:43,160
还真不好吃
and it won’t taste good. 
20
00:00:43,160 --> 00:00:47,200
半斤韭菜 六个鸡蛋
250 grams of chives with six eggs. 
21
00:00:47,200 --> 00:00:48,440
其实现在鸡蛋没有
the egg nowadays does not 
22
00:00:48,440 --> 00:00:50,560
过去奶奶那时候做的好吃
taest as good as eggs from grandma’s age.  
23
00:00:50,560 --> 00:00:52,280
没有那鸡蛋好
not tasty as their eggs. 
24
00:00:52,280 --> 00:00:54,520
水量一定要充足
water has to be sufficient
25
00:00:54,520 --> 00:00:56,040
为什么说健康
Why do I say it’s healthy, 
26
00:00:56,040 --> 00:00:58,200
你看不加淀粉 就是韭菜鸡蛋
you see I don’ t put starch,just chives and eggs. 
27
00:00:58,200 --> 00:00:59,720
不加淀粉不加盐
No starch, no salt. 
28
00:00:59,720 --> 00:01:03,080

29
00:01:03,080 --> 00:01:06,840
你看这就行了 直接下锅
Look, that’s it. Directly into the pot.  
30
00:01:06,840 --> 00:01:10,800
这个火要大了 你看可以小一点
if there’s too much heat, you can turn it down a bit
31
00:01:13,480 --> 00:01:17,960
微微的小一点 别太小了 
just turn down a little bit, not too much. 
32
00:01:18,640 --> 00:01:22,000
燉熟 这就叫燉
simmer it done. This is called simmer. 
33
00:01:25,600 --> 00:01:26,880
燉熟
simmer it done. 
34
00:01:26,880 --> 00:01:30,360
这也是一种很奇妙的技巧
this is also an interesting technique. 
35
00:01:30,360 --> 00:01:33,600
慢推慢燉
slowly push, slowly simmer. 
36
00:01:33,600 --> 00:01:34,640
你看说这菜简单
The dish looks easy, 
37
00:01:34,640 --> 00:01:39,560
但是它确实需要一定的技法
but needs quite a bit of technique
38
00:01:39,560 --> 00:01:40,920

39
00:01:40,920 --> 00:01:43,400
你看二位大师帮着我忙活这点事
You two masters are helping me for this simple task. 
40
00:01:43,400 --> 00:01:45,280
我主要是掌握一个火力
I’m just controling the heat. 
41
00:01:45,280 --> 00:01:46,920
这菜简单吗 它不简单
Is the dish easy? No it’s not. 
42
00:01:48,160 --> 00:01:49,280
往往有些菜
There is always dishes
43
00:01:49,280 --> 00:01:52,160
越简单的方法是越不简单
looks simple but acctully not. 
44
00:01:52,160 --> 00:01:56,280
平凡当中没有平凡 对不平凡
what's common is not common
45
00:01:56,280 --> 00:01:58,080
简单当中又不简单
it’s simple but not easy. 

46
00:01:58,080 --> 00:02:05,440

47
00:02:05,440 --> 00:02:07,440
你看 还是不行
still not yet. 
48
00:02:09,280 --> 00:02:11,120
开锅了你看
see, it’s boiling now
49
00:02:11,120 --> 00:02:12,360

50
00:02:12,360 --> 00:02:14,000
是开锅 是不开锅呢
You want it boil or not?
51
00:02:14,000 --> 00:02:15,160
得开一点
just boil a little bit. 
52
00:02:15,160 --> 00:02:16,480
但是也别完全开大了
but not over boiled. 
53
00:02:16,480 --> 00:02:22,080
把鸡蛋得给它煮熟了
just get the egg cooked. 
54
00:02:22,080 --> 00:02:23,400

55
00:02:23,400 --> 00:02:26,600
水汆
boiling a little bit. 
56
00:02:26,600 --> 00:02:27,880
似开非开
semes boil but not fully boil. 
57
00:02:27,880 --> 00:02:36,400

58
00:02:36,400 --> 00:02:40,160
大家已经是静下来了
it’s getting quiet. 
59
00:02:40,160 --> 00:02:42,480
这是沁熟的
this is cooked through soaking
60
00:02:42,480 --> 00:02:43,440

61
00:02:44,560 --> 00:02:47,080
有点像鸡豆花啊 对啊
like how we cook Ji Dou Hua. Right?
62
00:02:47,080 --> 00:02:48,640
这马上该熟了
almost cooked now. 
63
00:02:48,640 --> 00:02:52,280

64
00:02:53,840 --> 00:02:56,920
这沫子可以要可以不要
it’s opptional to leave the foam here or not. 
65
00:02:56,920 --> 00:02:58,480
基本就快熟了
it’s basically done. 
66
00:02:58,480 --> 00:03:00,200

67
00:03:02,440 --> 00:03:04,920
马上该熟了
it should be cooked. 
68
00:03:05,400 --> 00:03:09,200
鲜嫩 这韭菜本身也提鲜
tender and flavorful, and the chives also make it flavorful. 
69
00:03:09,200 --> 00:03:10,720
关火了
turning off the stove
70
00:03:10,720 --> 00:03:11,920

71
00:03:11,920 --> 00:03:13,520
你看这水太多了
You see, it’s too much of water. 
72
00:03:13,520 --> 00:03:17,280

73
00:03:19,520 --> 00:03:20,840
豆花似的
just like dou hua. 
74
00:03:20,840 --> 00:03:22,680
关键的来了
now here is the point. 
75
00:03:22,680 --> 00:03:25,440

76
00:03:25,440 --> 00:03:28,920
酱油 您觉得咸味够不够
soy sauce, do you think it’s salty enough? 
77
00:03:28,920 --> 00:03:31,480
什么酱油都行 够了
any kind of soy sauce. that’s enough. 
78
00:03:31,480 --> 00:03:34,360
这咸味够不够 够了
it it enough salt? that’s enough. 
79
00:03:34,360 --> 00:03:36,640

80
00:03:38,040 --> 00:03:39,240
你看这个温度多少度啊
What do you think is the temperature? 
81
00:03:39,240 --> 00:03:41,600
到不了八十度吧 到不了
less than 80C? probeblly not there. 
82
00:03:41,600 --> 00:03:43,480
就是说这种情况下
in this case, 
83
00:03:43,480 --> 00:03:45,120
为什么是健康菜
why is it a healthy dish? 
84
00:03:45,120 --> 00:03:46,480
这味精一点毒素没有
MSG does not have negative effects. 
85
00:03:46,480 --> 00:03:48,480
就把这点味精就加进去就行了
just put this bit of MSG in it. 
86
00:03:48,480 --> 00:03:50,560

87
00:03:50,560 --> 00:03:51,640
香油
sesame oil
88
00:03:51,640 --> 00:03:53,720
这个菜我是今天头一次
it’s my first time see the process
89
00:03:53,720 --> 00:03:55,080
亲自在现场看见的
live in person.  
90
00:03:55,080 --> 00:03:57,160
过去是在电视上孙大师做过
I used to see Master Sun making it on TV. 
91
00:03:57,160 --> 00:03:59,160
做过之后再也没做过
afterwards,it’s never been cooked again. 
92
00:03:59,160 --> 00:04:01,520
你再不做也失传了
the process is lost if you don't make it. 
93
00:04:01,520 --> 00:04:03,640
这个菜极嫩
this dish is extremely tender.
94
00:04:03,640 --> 00:04:04,920
大哥你看这就完了
it’s done by now. 
95
00:04:04,920 --> 00:04:06,560
您看 一会您尝尝
look, try it later. 
96
00:04:06,560 --> 00:04:08,640
我跟你说这个菜
You know what about this dish, 
97
00:04:08,640 --> 00:04:10,280
我告诉你都能火遍整个中国
I tell you it’s going to be popular all over China. 
98
00:04:10,280 --> 00:04:11,560
太健康了
It’s too healthy. 
99
00:04:11,560 --> 00:04:14,080
大爷迫切的吃上了
Da Ye can't wait to try it. 
100
00:04:14,080 --> 00:04:15,840
急的吃上了
He can’t wait 
101
00:04:15,840 --> 00:04:16,200

102
00:04:16,200 --> 00:04:19,640
嫩 真鲜
it’s tender, and so flavourful. 
103
00:04:19,640 --> 00:04:23,800
千万别加酱油了 正好 够咸
No more soy sauce, it’s good, salty enough.  
104
00:04:23,800 --> 00:04:25,360
最关键的东西你知道在哪儿么
you know what’s the tricky part is? 
105
00:04:25,360 --> 00:04:27,760
我是说还是不说跟网友们
Should I tell all our audiance? 
106
00:04:27,760 --> 00:04:29,240
那肯定得说
You have to say it. 
107
00:04:29,240 --> 00:04:30,320
您发现没有 这韭菜都是脆的
You see, the chive is crispy. 
108
00:04:30,320 --> 00:04:31,920
我跟你说 我说是不说
Should I keep it a secret? 
109
00:04:31,920 --> 00:04:33,080
必须说
You must say. 
110
00:04:33,080 --> 00:04:35,200
要说了就没有秘密了谁都能做
If I give it out, everyone is able to make it. 
111
00:04:35,200 --> 00:04:36,560
要什么秘密
no more mystery
112
00:04:36,560 --> 00:04:39,600
现在你孙大师胸怀这么大
Master Sun you are broadminded,
113
00:04:39,600 --> 00:04:41,520
孙大师你就叫网友们学会了
just let our audiance learn. 
114
00:04:41,520 --> 00:04:43,760
人也知道你奶奶啊
so that we also know your grandma’s recipy
115
00:04:43,760 --> 00:04:46,880
其实我一揭秘您就知道了
it’s quite obvious 
116
00:04:46,880 --> 00:04:47,720

117
00:04:47,720 --> 00:04:49,440
我关火调味
I turned off the stove to season it. 
118
00:04:49,440 --> 00:04:51,520
如果说你要开着火 有一点火调味
If you season it with the stove on, 
119
00:04:51,520 --> 00:04:54,480
这菜马上这味道就变了
the flavor would change immediately. 
120
00:04:54,480 --> 00:04:59,160
它必须香油 味精 酱油不能着热
sesame oil, MSG, soy sauce are sensitive to heat
“我是大爷”00:05:02,
I am Da Ye.
