### ISSUE TITLE
[雪鱼] 照烧鸡腿饭 - https://youtu.be/brvl0tDcmU8

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#810]
**视频链接**：https://youtu.be/brvl0tDcmU8

视频时长：5min 发布日期：2020年3月18日

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【雪鱼vlog】不出门在家做照烧鸡腿饭，3个大鸡腿配一碗饭，花10元吃得比外卖好

简介
雪鱼不探店的日常：近期不出门，在家自己学着做美味小吃。
特别想吃肉了，现学了一个照烧鸡腿饭，
到超市采购食材，看看风景，回家用1个小时做出来，
颜色诱人，汤汁亮丽，米饭饱满，肉质水嫩，吃起来很完美。
配料：鸡腿，盐，胡椒，食用油，蜂蜜，生抽，老抽，姜丝，葱花
做法如视频，快快行动起来吧，给特别的日子增添一些幸福感。

字幕
1
00:00:17,080 --> 00:00:18,560
好久没有下来吃饭了

2
00:00:18,560 --> 00:00:21,160
今天发现 下面的两家小吃店

3
00:00:21,160 --> 00:00:23,280
都贴上了出租的标志

4
00:00:29,640 --> 00:00:32,800
现在很多的店都已经正常营业了

5
00:00:32,800 --> 00:00:34,640
不过要求就是 进入时

6
00:00:34,640 --> 00:00:38,200
必须要戴口罩 必须要检查测体温

7
00:00:47,480 --> 00:00:49,360
我要下车买东西了

8
00:00:49,360 --> 00:00:52,120
大家乖乖地在这儿等着我

9
00:01:19,040 --> 00:01:20,640
嗨  我回来了

10
00:01:20,640 --> 00:01:22,920
这次买了鸡腿 买了西兰花

11
00:01:22,920 --> 00:01:24,320
还买了一些水果

12
00:01:24,320 --> 00:01:27,160
现在准备回家了

13
00:01:27,400 --> 00:01:30,920
这个时间点 是我要饿的时候了

14
00:01:46,040 --> 00:01:49,000
蒸米饭

15
00:02:03,880 --> 00:02:07,000
鸡腿剔骨

16
00:02:08,720 --> 00:02:11,800
我有一双神奇的剪刀手

17
00:02:16,120 --> 00:02:18,400
我妈说 上次我炸的麻花不好看

18
00:02:18,400 --> 00:02:23,880
这次我一定要把鸡腿饭做的好看一点

19
00:02:24,440 --> 00:02:27,160
不蒸馒头 争口气

20
00:02:30,720 --> 00:02:33,400
做照烧鸡腿饭 方子我都是现找的

21
00:02:33,400 --> 00:02:34,880
好在材料都有

22
00:02:37,800 --> 00:02:40,120
现在我们就是把这些腌料放进碗里

23
00:02:40,120 --> 00:02:44,080
料酒
姜片
黑胡椒
食用油
盐

24
00:02:49,640 --> 00:02:52,520
好浓重的料酒的味道

25
00:02:53,440 --> 00:02:56,320
好了 腌着吧

26
00:03:14,520 --> 00:03:17,800
现在的目标就是把鸡皮煎出油来

27
00:03:28,360 --> 00:03:31,280
本鱼还是第一次做 看样子 还是很成功的

28
00:03:52,040 --> 00:03:54,040
压实 压实 压实

29
00:03:55,400 --> 00:03:57,920
满满的米饭

30
00:03:57,920 --> 00:04:02,680
压实的米饭 才是我对你的爱

31
00:04:03,440 --> 00:04:04,360
好了

32
00:04:23,560 --> 00:04:25,440
历经一个多小时 我们总算

33
00:04:25,440 --> 00:04:28,000
把照烧鸡腿饭做完了

34
00:04:28,000 --> 00:04:29,120
还是很不错的吧

35
00:04:29,120 --> 00:04:30,960
看这浓郁的汤汁

36
00:04:30,960 --> 00:04:33,280
真的恨不得马上吃掉它

37
00:04:36,400 --> 00:04:38,960
这个鸡腿被我煎的金黄金黄的

38
00:04:38,960 --> 00:04:42,000
而且鸡皮已经煎的有点焦脆了

39
00:04:44,160 --> 00:04:46,360
就是微微的酱油的咸味

40
00:04:46,360 --> 00:04:48,040
带蜂蜜的甜味

41
00:04:52,360 --> 00:04:53,600
鸡腿比较好咬

42
00:04:53,600 --> 00:04:55,240
像我这种牙齿不好的

43
00:04:55,240 --> 00:04:57,480
不 我是颌关节不太好

44
00:04:57,480 --> 00:05:00,320
吃这个鸡腿完全没有任何的压力

45
00:05:04,200 --> 00:05:08,440
汤汁流到米饭上

46
00:05:08,440 --> 00:05:09,860
无敌好吃

47
00:05:10,040 --> 00:05:14,280
光这个酱汁 就能够吃完3碗饭

48
00:05:16,560 --> 00:05:20,600
为什么我一个北方人 对米饭情有独钟呢

49
00:05:20,600 --> 00:05:23,440
做照烧鸡腿饭 简单易学

50
00:05:23,440 --> 00:05:24,080
而且

51
00:05:24,080 --> 00:05:26,600
吃完 就刷一个碗

52
00:05:37,320 --> 00:05:38,680
好久没有出去了

53
00:05:38,680 --> 00:05:41,280
最近在家都捂白了好多
```

**Comment by iamatrollatrollisme** [comment]
认领

**Comment by iamatrollatrollisme** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【雪鱼vlog】不出门在家做照烧鸡腿饭，3个大鸡腿配一碗饭，花10元吃得比外卖好
【xueyu vlog】Homemade teriyaki chicken with rice, $1.41 better than takeout

简介
雪鱼不探店的日常：近期不出门，在家自己学着做美味小吃。
特别想吃肉了，现学了一个照烧鸡腿饭，
到超市采购食材，看看风景，回家用1个小时做出来，
颜色诱人，汤汁亮丽，米饭饱满，肉质水嫩，吃起来很完美。
配料：鸡腿，盐，胡椒，食用油，蜂蜜，生抽，老抽，姜丝，葱花
做法如视频，快快行动起来吧，给特别的日子增添一些幸福感。

What do I do when I am not visiting places: Recently I am not going out anymore, so I am making some delicious food at home. Really craving for some meat so I learned how to make teriyaki chicken on Rice. Including the time spent on purchasing ingredient from supermarket, check out the view on the way, get home and finish cooking, it took me an hour. Beautiful color, bright sauce, fluffy rice, juicy chicken, taste perfect.

Ingredients: Chicken Drumstick, salt, pepper, cooking oil, honey, soy sauce, dark soy sauce, slice ginger, diced green onion

Steps see the video, hurry up and make the delicious dish. Comfort food to comfort the special life. 

字幕
1
00:00:17,080 --> 00:00:18,560
好久没有下来吃饭了
It’s been a while since last time I ate out. 

2
00:00:18,560 --> 00:00:21,160
今天发现 下面的两家小吃店
Today I found out the 2 restaurants

3
00:00:21,160 --> 00:00:23,280
都贴上了出租的标志
Are both renting out

4
00:00:29,640 --> 00:00:32,800
现在很多的店都已经正常营业了
Now lots of stores are operating like normal

5
00:00:32,800 --> 00:00:34,640
不过要求就是 进入时
But the requirement is while entering

6
00:00:34,640 --> 00:00:38,200
必须要戴口罩 必须要检查测体温
You must wear mask and get body temperature measured

7
00:00:47,480 --> 00:00:49,360
我要下车买东西了
I’m going to buy some groceries

8
00:00:49,360 --> 00:00:52,120
大家乖乖地在这儿等着我
Please wait here

9
00:01:19,040 --> 00:01:20,640
嗨  我回来了
Hi I’m back

10
00:01:20,640 --> 00:01:22,920
这次买了鸡腿 买了西兰花
This time I bought chicken drumsticks, some broccoli

11
00:01:22,920 --> 00:01:24,320
还买了一些水果
I also bought some fruit

12
00:01:24,320 --> 00:01:27,160
现在准备回家了
Now I am ready to go home

13
00:01:27,400 --> 00:01:30,920
这个时间点 是我要饿的时候了
This time, is the time for me to get hungry

14
00:01:46,040 --> 00:01:49,000
蒸米饭
Steam some white rice

15
00:02:03,880 --> 00:02:07,000
鸡腿剔骨
Debone the chicken drum sticks

16
00:02:08,720 --> 00:02:11,800
我有一双神奇的剪刀手
I’ve got magical scissor hands 

17
00:02:16,120 --> 00:02:18,400
我妈说 上次我炸的麻花不好看
My mom said last time my Chinese fried donuts were ugly

18
00:02:18,400 --> 00:02:23,880
这次我一定要把鸡腿饭做的好看一点
This time I am going to make the chicken rick pretty 

19
00:02:24,440 --> 00:02:27,160
不蒸馒头 争口气
Redemption time

20
00:02:30,720 --> 00:02:33,400
做照烧鸡腿饭 方子我都是现找的
Making teriyaki chicken rice, I just learned the recipe

21
00:02:33,400 --> 00:02:34,880
好在材料都有
Good thing I have most of the ingredients

22
00:02:37,800 --> 00:02:40,120
现在我们就是把这些腌料放进碗里
Now are putting the marinating ingredient into the bowl

23
00:02:40,120 --> 00:02:44,080
料酒   Chinese cooking wine
姜片   sliced ginger
黑胡椒 black pepper
食用油 cooking oil
盐 salt

24
00:02:49,640 --> 00:02:52,520
好浓重的料酒的味道
Very heavy smell of the cooking wine

25
00:02:53,440 --> 00:02:56,320
好了 腌着吧
Okay, let it marinate

26
00:03:14,520 --> 00:03:17,800
现在的目标就是把鸡皮煎出油来
Now the goal the to crisp the skin, get the fat out

27
00:03:28,360 --> 00:03:31,280
本鱼还是第一次做 看样子 还是很成功的
It is my fist time making it, look like a successful case

28
00:03:52,040 --> 00:03:54,040
压实 压实 压实
Press firm, firm, extra firm

29
00:03:55,400 --> 00:03:57,920
满满的米饭
Bowl full of rice

30
00:03:57,920 --> 00:04:02,680
压实的米饭 才是我对你的爱
Firmly pressed bowl full of rice, is my love to you

31
00:04:03,440 --> 00:04:04,360
好了 
Okay

32
00:04:23,560 --> 00:04:25,440
历经一个多小时 我们总算
After a bit over an hour, we finally

33
00:04:25,440 --> 00:04:28,000
把照烧鸡腿饭做完了
Finish the teriyaki chicken rich

34
00:04:28,000 --> 00:04:29,120
还是很不错的吧
It looks not bad

35
00:04:29,120 --> 00:04:30,960
看这浓郁的汤汁
Look at this thick sauce

36
00:04:30,960 --> 00:04:33,280
真的恨不得马上吃掉它
I really want to gorge it

37
00:04:36,400 --> 00:04:38,960
这个鸡腿被我煎的金黄金黄的
The chicken leg is fried to perfectly browned

38
00:04:38,960 --> 00:04:42,000
而且鸡皮已经煎的有点焦脆了
And the skin is a bit crispy

39
00:04:44,160 --> 00:04:46,360
就是微微的酱油的咸味
Just a little bit salty from the soy sauce

40
00:04:46,360 --> 00:04:48,040
带蜂蜜的甜味
With some sweetness from the honey

41
00:04:52,360 --> 00:04:53,600
鸡腿比较好咬
Very tender chicken, easy to bite into

42
00:04:53,600 --> 00:04:55,240
像我这种牙齿不好的
Like me who have weak teeth

43
00:04:55,240 --> 00:04:57,480
不 我是颌关节不太好
No, I mean weak jaw joint 

44
00:04:57,480 --> 00:05:00,320
吃这个鸡腿完全没有任何的压力
No pressure in eating the chicken leg

45
00:05:04,200 --> 00:05:08,440
汤汁流到米饭上
The sauce got on rice

46
00:05:08,440 --> 00:05:09,860
无敌好吃
Taste extremely good

47
00:05:10,040 --> 00:05:14,280
光这个酱汁 就能够吃完3碗饭
Just the sauce, can get me finish 3 bowls of rice

48
00:05:16,560 --> 00:05:20,600
为什么我一个北方人 对米饭情有独钟呢
Why do I love rice so much as a northern Chinese resident

49
00:05:20,600 --> 00:05:23,440
做照烧鸡腿饭 简单易学
The teriyaki chicken rice, easy to make

50
00:05:23,440 --> 00:05:24,080
而且
And

51
00:05:24,080 --> 00:05:26,600
吃完 就刷一个碗
You only wash one dish

52
00:05:37,320 --> 00:05:38,680
好久没有出去了
Have not gone out for a while

53
00:05:38,680 --> 00:05:41,280
最近在家都捂白了好多
My skin got a lot lighter
