### ISSUE TITLE
【美食作家王刚】玉米烙 - https://youtu.be/wV4L5mdOM7I

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#811]
**视频链接**：https://youtu.be/wV4L5mdOM7I

视频时长 5:35，预计发布时间为北京时间3月22日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“玉米烙”的家常做法，比蜂窝玉米更适合牙口不好的老人吃，四伯很喜欢！

简介
朋友们好，今天和大家分享一道“玉米烙”，
相信常关注我的朋友知道我之前做过一次“蜂窝玉米”，
和这次的玉米烙比较相似。
但蜂窝玉米整体为酥脆香酥的，小孩子特别喜欢吃，
但对于像四伯这样牙口不好的老人不太友好，所以这次改做成“玉米烙”。
这样做出来的玉米外酥里嫩，外面有一层薄薄的酥壳，
但里面非常软非常嫩，四伯很喜欢！

字幕
0:00:00.225,0:00:01.150
哈喽  大家好

0:00:01.150,0:00:04.100
今天我用这个玉米和大家分享一个玉米烙

0:00:04.100,0:00:07.800
就只要玉米鸡蛋和（土豆）淀粉

0:00:08.225,0:00:10.400
就可以做一个大大的饼

0:00:10.400,0:00:11.775
又脆又好吃

0:00:11.800,0:00:13.575
我们这次用的是鲜玉米

0:00:15.000,0:00:16.625
这个（玉米）浆浆都冒出来了

0:00:17.500,0:00:19.150
这玉米我们就直接把它切下来

0:00:20.275,0:00:21.800
如果你们没有鲜玉米

0:00:21.825,0:00:24.375
可以买（玉米）罐头

0:00:25.075,0:00:26.175
四伯爷  吃过玉米罐头吗

0:00:26.525,0:00:27.200
没有

0:00:28.750,0:00:29.750
然后这个玉米棒子

0:00:29.850,0:00:32.200
我们很多人切了之后就把它丢了

0:00:32.500,0:00:34.225
其实这个切了之后

0:00:34.275,0:00:39.175
放点排骨 放点马蹄之类的煲汤特别好喝

0:00:39.875,0:00:42.175
然后打一个鸡蛋

0:00:42.425,0:00:45.450
鸡蛋大家记住 只要蛋黄不要蛋清

0:00:45.600,0:00:47.800
蛋清放下去了之后会脱粉

0:00:49.125,0:00:51.375
然后把蛋黄滤出来

0:00:56.400,0:00:58.525
蛋黄放下去把它拌匀

0:01:00.175,0:01:02.725
这个蛋清等会我们用来做蛋花汤

0:01:02.950,0:01:03.875
可以安

0:01:05.275,0:01:07.500
 然后我们这个你看黄黄的是吧 

0:01:07.525,0:01:08.650
蛋黄加进去后 

0:01:09.275,0:01:10.125
 颜色也很好看

0:01:11.075,0:01:11.975
金黄金黄的安逸

0:01:12.450,0:01:14.175
 然后我们再加一点吉士粉

0:01:14.250,0:01:17.554
吉士粉它也可以说是一种香精嘛 

0:01:18.475,0:01:19.600
 不喜欢的话可以不加

0:01:19.725,0:01:21.425
你看 现在它粘粘的

0:01:21.950,0:01:22.350
对吧

0:01:22.475,0:01:23.125
肯定撒

0:01:23.335,0:01:25.027
吉士粉放了之后

0:01:25.027,0:01:25.913
再抓一把淀粉

0:01:26.260,0:01:27.019
先抓一小把

0:01:28.205,0:01:29.138
然后给它拌匀

0:01:30.909,0:01:32.774
因为这个蛋黄它自带粘性

0:01:33.786,0:01:34.956
我们裹上去之后

0:01:35.541,0:01:36.980
然后再加一点点（淀粉）

0:01:40.047,0:01:41.770
就是让它颗粒分明

0:01:42.513,0:01:42.861
可以了

0:01:43.541,0:01:43.826
可以了

0:01:44.094,0:01:44.584
现在我去炸

0:01:45.549,0:01:46.387
马上就可以炸好

0:01:46.450,0:01:47.415
炸好之后多大一个饼饼儿

0:01:49.090,0:01:49.739
香  是不

0:01:50.893,0:01:52.758
那里面有一点点香精

0:01:52.758,0:01:53.881
但是是食用香精

0:01:54.513,0:01:54.972
可以吃的

0:01:57.675,0:01:59.272
用它烙饼肯定很安逸

0:01:59.762,0:02:00.616
烙饼肯定好吃

0:03:05.723,0:03:06.940
火是不是小了点

0:03:12.237,0:03:13.280
来火了撒

0:03:19.988,0:03:20.922
放点白糖

0:03:21.249,0:03:22.561
放点白糖好干（吃）点

0:03:22.909,0:03:24.221
你吃得没得好甜的哦

0:03:24.221,0:03:24.897
少放一点

0:03:25.075,0:03:25.660
要得要得

0:03:25.660,0:03:26.877
我晓得你吃得厚

0:03:28.458,0:03:29.675
厚点吃着扎实点

0:03:30.260,0:03:31.383
吃得厚 吃得老

0:03:32.363,0:03:33.043
吃得老

0:03:33.976,0:03:35.003
钓鱼才说吃得老都嘛

0:03:35.162,0:03:36.569
随便啥子都要吃老点的

0:03:37.075,0:03:38.450
做生意都要吃得老点的

0:03:38.608,0:03:39.841
不吃老点要吃亏

0:03:40.395,0:03:41.565
 我们两爷子就拿手嘛

0:03:42.197,0:03:43.114
要得

0:03:44.632,0:03:45.169
自己弄哦

0:03:48.474,0:03:49.233
这个很脆

0:03:49.802,0:03:50.861
蘸点白糖

0:03:54.782,0:03:55.351
安逸

0:03:56.189,0:03:57.928
很脆 大家可以在家里面试一下

0:03:58.245,0:03:59.035
又香又甜

0:03:59.620,0:04:02.181
在饭店里面的话  还要再做薄一点

0:04:02.909,0:04:05.059
还要炸得更硬一些

0:04:05.106,0:04:06.766
然后切成三角形

0:04:06.988,0:04:09.913
最后撒上白糖  撒上西红柿颗粒

0:04:13.707,0:04:14.355
我叫伯娘来吃

0:04:16.964,0:04:17.438
伯娘

0:04:20.363,0:04:21.675
这个好吃

0:04:27.051,0:04:28.284
伯娘过来吃东西

0:04:37.675,0:04:39.541
你不快点我吃完了哦

0:04:42.498,0:04:43.383
你再不来

0:04:44.031,0:04:44.911
等会我们俩都吃完了

0:04:49.754,0:04:50.909
我们直接用手掰的

0:04:51.446,0:04:52.047
用手掰的呀

0:04:53.834,0:04:54.134
试一下

0:04:54.371,0:04:55.557
放的白糖是不哦

0:04:56.173,0:04:56.869
放的粉子（土豆淀粉）

0:04:57.501,0:05:00.347
先炸  然后再撒的白糖

0:05:03.367,0:05:04.110
真的好吃

0:05:06.387,0:05:08.664
你看这一截全部都是我掰来吃了的

0:05:08.727,0:05:09.217
你呀

0:05:09.217,0:05:10.163
你好厉害哦

0:05:16.195,0:05:16.835
好吃

0:05:17.201,0:05:18.229
大口吃哦

0:05:18.719,0:05:19.494
大口大口的

0:05:19.943,0:05:20.948
你咬得动啊

0:05:22.166,0:05:22.640
咬得动

0:05:22.687,0:05:23.430
好厉害哦

0:05:23.826,0:05:25.375
这个是外酥里嫩

0:05:26.845,0:05:27.272
好吃

0:05:31.241,0:05:32.585
你们先吃  我收拾一下


```

**Comment by WuStevenShengyang** [comment]
# https://youtu.be/wV4L5mdOM7I

标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“玉米烙”的家常做法，比蜂窝玉米更适合牙口不好的老人吃，四伯很喜欢！
Corn Pancake, more tender than honeycomb corn. Uncle likes it!

简介
朋友们好，今天和大家分享一道“玉米烙”，
Hey friends! Today, I will share with you: corn pancake.
相信常关注我的朋友知道我之前做过一次“蜂窝玉米”,
If you have been watching my channel, I have made a video on honeycomb corn previously.
和这次的玉米烙比较相似。
This dish is similar to that.
但蜂窝玉米整体为酥脆香酥的，小孩子特别喜欢吃，
But honeycomb corn is more crispy and kids like it especially.
但对于像四伯这样牙口不好的老人不太友好，所以这次改做成“玉米烙”。
However, as for my uncle, who have weaker teech, honeycomb isn't too good for him. So I decide to make corn pancake this time.
这样做出来的玉米外酥里嫩，外面有一层薄薄的酥壳，
Dish dish is crispy outside and tender inside.
但里面非常软非常嫩，四伯很喜欢！
And my uncle likes it a lot.

字幕
0:00:00.225,0:00:01.150
哈喽  大家好
Hello, everyone!

0:00:01.150,0:00:04.100
今天我用这个玉米和大家分享一个玉米烙
Today I will use corn to make corn pancake. 

0:00:04.100,0:00:07.800
就只要玉米鸡蛋和（土豆）淀粉
The only ingredients we will be using are corn, eggs, and potato starch.

0:00:08.225,0:00:10.400
就可以做一个大大的饼
And we will be able to make a large pancake.

0:00:10.400,0:00:11.775
又脆又好吃
It is crispy and delicious.

0:00:11.800,0:00:13.575
我们这次用的是鲜玉米
We will use fresh corns.

0:00:15.000,0:00:16.625
这个（玉米）浆浆都冒出来了
The corn juice is effusing.

0:00:17.500,0:00:19.150
这玉米我们就直接把它切下来
We need to cut the corn off the cob.

0:00:20.275,0:00:21.800
如果你们没有鲜玉米
However, if you don't have fresh corn,

0:00:21.825,0:00:24.375
可以买（玉米）罐头
you can use canned corn instead.

0:00:25.075,0:00:26.175
四伯爷  吃过玉米罐头吗
Uncle, have you ever tried canned corn?

0:00:26.525,0:00:27.200
没有
No.

0:00:28.750,0:00:29.750
然后这个玉米棒子
As for the cobs,

0:00:29.850,0:00:32.200
我们很多人切了之后就把它丢了
many people will throw them away into the trash.

0:00:32.500,0:00:34.225
其实这个切了之后
However, we can chop them into chunks,

0:00:34.275,0:00:39.175
放点排骨 放点马蹄之类的煲汤特别好喝
add some pork ribs, and water-chestnuts to make a delicious bowl of soup.

0:00:39.875,0:00:42.175
然后打一个鸡蛋
Next, we need to crack an egg.

0:00:42.425,0:00:45.450
鸡蛋大家记住 只要蛋黄不要蛋清
However, we will only use the yolk.

0:00:45.600,0:00:47.800
蛋清放下去了之后会脱粉
The potato starch will fall off if we add in the egg white.

0:00:49.125,0:00:51.375
然后把蛋黄滤出来
We need to take out the yolk only.

0:00:56.400,0:00:58.525
蛋黄放下去把它拌匀
After adding the yolk, we need to mix it with the corn.

0:01:00.175,0:01:02.725
这个蛋清等会我们用来做蛋花汤
Later on, we can make egg flower soup with the egg white.

0:01:02.950,0:01:03.875
可以安
Sure.

0:01:05.275,0:01:07.500
然后我们这个你看黄黄的是吧 
See, it's pretty yellow.

0:01:07.525,0:01:08.650
蛋黄加进去后 
After adding the yolk,

0:01:09.275,0:01:10.125
颜色也很好看
the color looks nice.

0:01:11.075,0:01:11.975
金黄金黄的安逸
Nice, its golden.

0:01:12.450,0:01:14.175
然后我们再加一点吉士粉
Then, we will add some custard power.

0:01:14.250,0:01:17.554
吉士粉它也可以说是一种香精嘛 
Custard power is actually a type of food essence.

0:01:18.475,0:01:19.600
不喜欢的话可以不加
You can ignore this step if you don't like it.

0:01:19.725,0:01:21.425
你看 现在它粘粘的
See, it is sticky now.

0:01:21.950,0:01:22.350
对吧
Yea.

0:01:22.475,0:01:23.125
肯定撒
Sure.

0:01:23.335,0:01:25.027
吉士粉放了之后
After mixing the custard power,

0:01:25.027,0:01:25.913
再抓一把淀粉
we will add some potato starch.

0:01:26.260,0:01:27.019
先抓一小把
We will start with a small amount of starch.

0:01:28.205,0:01:29.138
然后给它拌匀
And mix it well.

0:01:30.909,0:01:32.774
因为这个蛋黄它自带粘性
Because the yolk itself is sticky

0:01:33.786,0:01:34.956
我们裹上去之后
after we coat the corn with starch, 

0:01:35.541,0:01:36.980
然后再加一点点（淀粉）
we will add some starch again.

0:01:40.047,0:01:41.770
就是让它颗粒分明
To make it clear.

0:01:42.513,0:01:42.861
可以了
Done.

0:01:43.541,0:01:43.826
可以了
Done.

0:01:44.094,0:01:44.584
现在我去炸
Now let's deep fry it.

0:01:45.549,0:01:46.387
马上就可以炸好
This will be quick.

0:01:46.450,0:01:47.415
炸好之后多大一个饼饼儿
Afterwards we will have a big corn pancake.

0:01:49.090,0:01:49.739
香  是不
Smells pretty good, right?

0:01:50.893,0:01:52.758
那里面有一点点香精
There is a little bit MSG in it.

0:01:52.758,0:01:53.881
但是是食用香精
But because it is MSG,

0:01:54.513,0:01:54.972
可以吃的
it is safe to eat.

0:01:57.675,0:01:59.272
用它烙饼肯定很安逸
I bet the pancake will be good.

0:01:59.762,0:02:00.616
烙饼肯定好吃
Definetly.

0:03:05.723,0:03:06.940
火是不是小了点
Isn't the heat too low?

0:03:12.237,0:03:13.280
来火了撒
Now it's coming up.

0:03:19.988,0:03:20.922
放点白糖
We can add some sugar on it.

0:03:21.249,0:03:22.561
放点白糖好干（吃）点
To make it tastes better.

0:03:22.909,0:03:24.221
你吃得没得好甜的哦
Have you tried it yet? It's so sweet.

0:03:24.221,0:03:24.897
少放一点
Then we need to add a little less sugar.

0:03:25.075,0:03:25.660
要得要得
Sure.

0:03:25.660,0:03:26.877
我晓得你吃得厚
I know you like more flavor.

0:03:28.458,0:03:29.675
厚点吃着扎实点
More flavor is more stable.

0:03:30.260,0:03:31.383
吃得厚 吃得老
Stable, and tough.

0:03:32.363,0:03:33.043
吃得老
Tough.

0:03:33.976,0:03:35.003
钓鱼才说吃得老都嘛
Aren't you only suppose to say this when you go fishing?

0:03:35.162,0:03:36.569
随便啥子都要吃老点的
No, 

0:03:37.075,0:03:38.450
做生意都要吃得老点的
you also need to be tough as a businessman.

0:03:38.608,0:03:39.841
不吃老点要吃亏
Otherwise you will lose money.

0:03:40.395,0:03:41.565
我们两爷子就拿手嘛
Can we just use our hands?

0:03:42.197,0:03:43.114
要得
Sure.

0:03:44.632,0:03:45.169
自己弄哦
Help yourself, uncle.

0:03:48.474,0:03:49.233
这个很脆
It's crunchy.

0:03:49.802,0:03:50.861
蘸点白糖
I will dip it into the sugar.

0:03:54.782,0:03:55.351
安逸
Nice.

0:03:56.189,0:03:57.928
很脆 大家可以在家里面试一下
It's crunchy, you should try this at home.

0:03:58.245,0:03:59.035
又香又甜
Sweet and delicious.

0:03:59.620,0:04:02.181
在饭店里面的话  还要再做薄一点
The pancake will be thiner if you were to eat this in a restaurant.

0:04:02.909,0:04:05.059
还要炸得更硬一些
Add they will deep fry it even more.

0:04:05.106,0:04:06.766
然后切成三角形
And then cut it into triangles.

0:04:06.988,0:04:09.913
最后撒上白糖  撒上西红柿颗粒
Finally, sprinkle with sugar and tomato chunks.

0:04:13.707,0:04:14.355
我叫伯娘来吃
I will go get aunty to try this.

0:04:16.964,0:04:17.438
伯娘
Aunty!

0:04:20.363,0:04:21.675
这个好吃
This is good.

0:04:27.051,0:04:28.284
伯娘过来吃东西
Aunty, come and try this.

0:04:37.675,0:04:39.541
你不快点我吃完了哦
Or I will eat it all,

0:04:42.498,0:04:43.383
你再不来
if you don't come.

0:04:44.031,0:04:44.911
等会我们俩都吃完了
We would eat this all if you come too late.

0:04:49.754,0:04:50.909
我们直接用手掰的
We will use our hands.

0:04:51.446,0:04:52.047
用手掰的呀
Ok, I will use my hand as well.

0:04:53.834,0:04:54.134
试一下
Let me try it.

0:04:54.371,0:04:55.557
放的白糖是不哦
Did you put sugar in it.

0:04:56.173,0:04:56.869
放的粉子（土豆淀粉）
It's potato starch, actually.

0:04:57.501,0:05:00.347
先炸  然后再撒的白糖
We deep fried it, then sprinkled some sugar.

0:05:03.367,0:05:04.110
真的好吃
It's really delicious.

0:05:06.387,0:05:08.664
你看这一截全部都是我掰来吃了的
See, I just ate all those.

0:05:08.727,0:05:09.217
你呀
You,

0:05:09.217,0:05:10.163
你好厉害哦
you are so good...hahaha.

0:05:16.195,0:05:16.835
好吃
So good.

0:05:17.201,0:05:18.229
大口吃哦
Take a big bite.

0:05:18.719,0:05:19.494
大口大口的
Big bite.

0:05:19.943,0:05:20.948
你咬得动啊
Isn't this too tough for you to eat?

0:05:22.166,0:05:22.640
咬得动
I think he has no problem eating it.

0:05:22.687,0:05:23.430
好厉害哦
So good.

0:05:23.826,0:05:25.375
这个是外酥里嫩
It's crunchy outside and tender inside.

0:05:26.845,0:05:27.272
好吃
Delicious

0:05:31.241,0:05:32.585
你们先吃  我收拾一下
You guys eat, I will clean those up.
