### ISSUE TITLE
【美食作家王刚】 工程款冰箱 - https://youtu.be/pbK7lbp19RY

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#814]
**视频链接**：https://youtu.be/pbK7lbp19RY

视频时长 5:04，预计发布时间为北京时间3月23日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长又一硬核开箱：“酒店大冰箱”和家用冰箱的区别，看看大家是不是也想要一个？

简介
朋友们好，为了配合猛火灶，打算逐步完善我的乡下厨房，这次购入了后厨的另一个大件“大冰箱”，让我带你们看看和家用的有什么区别。好处很明显，那就是性价比，价格很低的同时可以得到非常大的储存空间，非常适合需要大量储存空间的朋友。但缺点也很明显，因为保温性能和温控性能不如家用冰箱，所以更加耗电，并且压缩机的噪音也相对较大。最后就是要看大家的需求了，如果家人很多，想经常储存大量的食材，并且空间够用的话，这种款式的冰箱还是值得推荐的！

字幕
0:00:01.350,0:00:03.150
嗨喽大家好 我是王刚

0:00:03.500,0:00:06.575
前段时间我们买了一套工程款的那个炉灶回来

0:00:07.000,0:00:10.025
今天我又买了一个工程款的冰箱

0:00:10.025,0:00:12.450
这个冰箱四五百斤 宽也很宽

0:00:12.450,0:00:14.275
跟我们屋头的不一样

0:00:14.275,0:00:16.675
肯定不一样哦 你那个好大哦

0:00:16.675,0:00:21.209
然后这个好像能耗也比你那个高

0:00:21.209,0:00:24.275
肯定撒 你冻的东西都比较多按

0:00:24.275,0:00:26.175
肯定那耗电量肯定大撒

0:00:26.175,0:00:28.800
好 现在我们去看一下 去开箱

0:00:29.100,0:00:29.800
走嘛

0:00:30.025,0:00:32.275
这钉子些取不取哦

0:00:32.275,0:00:36.975
钉子不取都要得 后头要留一部分留个那种（缝缝）出来

0:00:37.775,0:00:38.775
留个缝缝

0:00:38.775,0:00:40.400
对 要留个缝缝

0:00:40.825,0:00:43.000
不是它那个散不到热

0:00:43.400,0:00:44.550
来嘛 （移）哈嘛四伯爷

0:00:44.550,0:00:46.250
这个门朝这方移

0:00:46.650,0:00:48.676
都还好这个有轮子 不是的话（不好移）

0:00:48.676,0:00:49.750
你朝门口扯撒

0:00:52.250,0:00:54.325
这个没得轮子的话才懒得搞

0:00:54.325,0:00:55.850
没得轮子害怕你够得干安

0:00:55.850,0:00:58.700
等一哈等一哈 把那个胶纸取了多

0:00:59.050,0:01:00.350
我拿菜刀来割

0:01:02.775,0:01:04.650
这根绳子要整了来

0:01:11.900,0:01:13.300
这个拿得下来不

0:01:13.300,0:01:14.675
拿得下来这个

0:01:15.675,0:01:16.975
先把这个取了

0:01:19.300,0:01:20.775
卡起了 没得那么高的

0:01:21.425,0:01:23.175
四伯爷 你更拿不到

0:01:23.175,0:01:24.100
有啥子拿不到哦

0:01:26.025,0:01:29.150
这儿还有点卡起得

0:01:36.025,0:01:36.950
可以咯

0:01:36.950,0:01:37.575
这上面呢

0:01:37.575,0:01:38.575
泡沫拿了就可以了

0:01:39.125,0:01:41.275
不要慌四伯爷 我把这儿割了多

0:01:46.425,0:01:48.675
这里都有点压烂了

0:01:50.450,0:01:54.350
这个是我们运输过程当中挤压到了

0:01:54.350,0:01:56.783
这一点点没事 不影响使用

0:01:56.783,0:01:58.525
在路高头压到的啊

0:01:59.575,0:02:02.175
哦哟 这里也遭压了   

0:02:08.200,0:02:12.750
这个不关事 皮子上面有点压到不影响使用

0:02:12.750,0:02:15.350
主要是看它压缩机啊那个

0:02:15.350,0:02:16.875
这不美观的嘛

0:02:17.350,0:02:19.300
哎呀 这个东西实用就OK了

0:02:19.300,0:02:23.500
你买的时候咋不跟他交涉呢 你包送包给我上下（货）

0:02:23.825,0:02:27.025
你整坏了这些我要我都不要 你拿去换过

0:02:27.275,0:02:29.075
哎呀 将心比心

0:02:29.075,0:02:31.950
我们看一下这个空间

0:02:32.300,0:02:36.200
这个的话唯一不好的是什么呢 它有声音

0:02:36.200,0:02:40.150
这个压制机它有时候制冷的时候咕咕咕的响

0:02:40.600,0:02:43.200
有一点点声响 就比家用的要响一点

0:02:43.200,0:02:44.350
估计有两米左右（高）

0:02:44.500,0:02:46.650
然后宽的话很宽 

0:02:48.125,0:02:49.350
耗电量的话也高

0:02:49.350,0:02:51.550
这个最好呢一个好处是什么呢

0:02:51.550,0:02:52.400
就是空间大

0:02:53.200,0:02:54.375
可以放很多东西

0:02:54.375,0:02:57.400
上面是保鲜 下面是急冻

0:03:02.550,0:03:04.600
冻两三个（头）猪儿都冻得到

0:03:04.600,0:03:06.625
两三个猪儿 可以哦

0:03:07.725,0:03:10.100
这个冰柜很舒服 就是用起来很舒服

0:03:10.100,0:03:12.125
如果你们家人口比较多的话

0:03:12.125,0:03:16.775
像我们家一家十多口人就适合用这种冰箱

0:03:16.775,0:03:20.525
如果你们家三四个人五六个人的话就特别不适合

0:03:20.525,0:03:24.325
这个的话就只适合怎么说呢酒店里面用

0:03:25.075,0:03:28.150
还有我们这个冰箱不管是这种还是家里面用的

0:03:28.150,0:03:31.650
拿回来都要放一段时间 放两三个小时再插电

0:03:31.775,0:03:34.775
然后这个冰箱它的价格是2400块钱

0:03:34.775,0:03:40.400
就价格来说的话比我们家用的便宜了不是一点点

0:03:40.575,0:03:42.825
家用的那个冰箱有几万的都有

0:03:42.825,0:03:44.525
我见过最贵的几万

0:03:44.525,0:03:46.250
但是这个的话是非常实用的

0:03:46.250,0:03:51.300
它除了能耗就是电量 耗电量高一点点之外

0:03:51.300,0:03:55.775
大坨一点之外没有其他什么缺点

0:03:56.350,0:04:00.625
还有我们这个冰箱靠墙放的话后面要有一点距离

0:04:00.625,0:04:03.375
不能够让它贴紧了 贴紧了没办法散热

0:04:03.850,0:04:05.525
朝里面移一点点

0:04:07.300,0:04:08.800
好 要得了要得了

0:04:10.150,0:04:13.975
这个滚滚（轮子）你要固定一哈 拿个啥子东西来塞到

0:04:14.900,0:04:16.350
嗯塞哈 稍微塞哈就是

0:04:16.350,0:04:19.275
不是它要到处跑 稍微哪样点

0:04:20.925,0:04:24.213
四伯爷你看嘛 这个冰箱就可以这样子关门

0:04:24.213,0:04:25.800
你的就 你不敢这样子关

0:04:26.525,0:04:27.650
看到没

0:04:30.250,0:04:33.150
小心点 当真是新的是不哦

0:04:33.150,0:04:38.925
不是 它就是那个个性晓得不嘛

0:04:38.925,0:04:42.600
个性 金子做的都遭不住这样子整

0:04:42.625,0:04:45.625
金子做的就发（财）了

0:04:45.625,0:04:47.200
那不是咋子安

0:04:47.200,0:04:49.157
好了 本期就给你们介绍到这里了

0:04:49.157,0:04:51.300
随便啥子东西都要保护得好才得行

0:04:51.300,0:04:53.675
保护得不好几家伙就整烂了

0:04:53.675,0:04:54.200
是

0:04:54.200,0:04:56.150
整烂了还是你的劳动成果去买

0:04:56.850,0:04:58.500
是 是这样子

0:04:59.425,0:05:01.175
好了 本期视频到这里

0:05:01.175,0:05:01.950
拜拜


```

**Comment by max-sun-hongyi** [comment]
厨师长又一硬核开箱：“酒店大冰箱”和家用冰箱的区别，看看大家是不是也想要一个？

Head chef unboxes "Industrial refrigerator" and home refrigerator. Do you want one too?

简介
朋友们好，为了配合猛火灶，打算逐步完善我的乡下厨房，这次购入了后厨的另一个大件“大冰箱”，让我带你们看看和家用的有什么区别。好处很明显，那就是性价比，价格很低的同时可以得到非常大的储存空间，非常适合需要大量储存空间的朋友。但缺点也很明显，因为保温性能和温控性能不如家用冰箱，所以更加耗电，并且压缩机的噪音也相对较大。最后就是要看大家的需求了，如果家人很多，想经常储存大量的食材，并且空间够用的话，这种款式的冰箱还是值得推荐的！

Hello everyone, to facilitate with the powerful burner stove, I plan to gradually improve my country side kitchen. This time I bought a big refrigerator, let me show you the difference between it and a normal home refrigerator. It has apparent pros that is it's cost-performance ratio, you can get a large storage space with a low price which is very suitable for friends need a large storage need. But it has obvious cons as well, because it has inferior insulation and temperature control performance, it consumes more electricity and produces a louder noise from the compressor. Lastly its all up to each and every one's need, if you have a large family and have many ingredients to store, this type of refrigerator is a good choice.

字幕
0:00:01.350,0:00:03.150
嗨喽大家好 我是王刚

Hello everyone this is Wang Gang

0:00:03.500,0:00:06.575
前段时间我们买了一套工程款的那个炉灶回来

Not too long ago we bought a industrial gas stove

0:00:07.000,0:00:10.025
今天我又买了一个工程款的冰箱

And today I bough a industrial refrigerator 

0:00:10.025,0:00:12.450
这个冰箱四五百斤 宽也很宽

It weights 400-500 jin (200-250kg) and pretty wide

0:00:12.450,0:00:14.275
跟我们屋头的不一样

Not quite the same as the one we had at home 

0:00:14.275,0:00:16.675
肯定不一样哦 你那个好大哦

Surely it's not the same, the other one is not the same size

0:00:16.675,0:00:21.209
然后这个好像能耗也比你那个高

And this one uses more electricity than the other one

0:00:21.209,0:00:24.275
肯定撒 你冻的东西都比较多按

For sure, this one have more storage capacity

0:00:24.275,0:00:26.175
肯定那耗电量肯定大撒

It surely consumes more electricity 

0:00:26.175,0:00:28.800
好 现在我们去看一下 去开箱

Alright let's go take a look and unbox it

0:00:29.100,0:00:29.800
走嘛

It's go

0:00:30.025,0:00:32.275
这钉子些取不取哦

Do we need to remove these nails?

0:00:32.275,0:00:36.975
钉子不取都要得 后头要留一部分留个那种（缝缝）出来

It doesn't matter, we need to leave a gap on the back

0:00:37.775,0:00:38.775
留个缝缝

Leave a gap

0:00:38.775,0:00:40.400
对 要留个缝缝

Yep leave a gap

0:00:40.825,0:00:43.000
不是它那个散不到热

Otherwise the heat can't get out

0:00:43.400,0:00:44.550
来嘛 （移）哈嘛四伯爷

Come let's move this Siboye

0:00:44.550,0:00:46.250
这个门朝这方移

Move it towards the door

0:00:46.650,0:00:48.676
都还好这个有轮子 不是的话（不好移）

Good that it's on wheels otherwise (are difficult to move)

0:00:48.676,0:00:49.750
你朝门口扯撒

Pull it towards the door

0:00:52.250,0:00:54.325
这个没得轮子的话才懒得搞

It will be very difficult to move without these wheels

0:00:54.325,0:00:55.850
没得轮子害怕你够得干安

I doubt you can even move it without those wheels

0:00:55.850,0:00:58.700
等一哈等一哈 把那个胶纸取了多

What a minute, lets remove these wraps 

0:00:59.050,0:01:00.350
我拿菜刀来割

I'll go get a knife 

0:01:02.775,0:01:04.650
这根绳子要整了来

Cut this rope 

0:01:11.900,0:01:13.300
这个拿得下来不

Can you take this off

0:01:13.300,0:01:14.675
拿得下来这个

We need to take this off

0:01:15.675,0:01:16.975
先把这个取了

First we take this off

0:01:19.300,0:01:20.775
卡起了 没得那么高的

It got stuck, I'm not tall enough

0:01:21.425,0:01:23.175
四伯爷 你更拿不到

Siboye you can't reach it 

0:01:23.175,0:01:24.100
有啥子拿不到哦

What are you talking about?

0:01:26.025,0:01:29.150
这儿还有点卡起得

This bit got stuck 

0:01:36.025,0:01:36.950
可以咯

Alrighty 

0:01:36.950,0:01:37.575
这上面呢

What about up there

0:01:37.575,0:01:38.575
泡沫拿了就可以了

Take off those foam then that's it 

0:01:39.125,0:01:41.275
不要慌四伯爷 我把这儿割了多

Hang on Siboye, let me cut this part first

0:01:46.425,0:01:48.675
这里都有点压烂了

This part is dented

0:01:50.450,0:01:54.350
这个是我们运输过程当中挤压到了

That happened during the transportation process

0:01:54.350,0:01:56.783
这一点点没事 不影响使用

It doesn't matter, won't affect the usage

0:01:56.783,0:01:58.525
在路高头压到的啊

It got dented on the way?

0:01:59.575,0:02:02.175
哦哟 这里也遭压了   

Crap this part is also dented

0:02:08.200,0:02:12.750
这个不关事 皮子上面有点压到不影响使用

It not a big deal, just on the shell won't affect the performance

0:02:12.750,0:02:15.350
主要是看它压缩机啊那个

As long as the compressor is working fine

0:02:15.350,0:02:16.875
这不美观的嘛

It doesn't look good 

0:02:17.350,0:02:19.300
哎呀 这个东西实用就OK了

Well this thing is more about its functionality 

0:02:19.300,0:02:23.500
你买的时候咋不跟他交涉呢 你包送包给我上下（货）

Why you didn't negotiate (with the seller) when you bought is, they take care of the shipment and courier process 

0:02:23.825,0:02:27.025
你整坏了这些我要我都不要 你拿去换过

If you damaged it, I won't sign off and get me a new one

0:02:27.275,0:02:29.075
哎呀 将心比心

Well if you put yourself in their shoes

0:02:29.075,0:02:31.950
我们看一下这个空间

Let's look at the space 

0:02:32.300,0:02:36.200
这个的话唯一不好的是什么呢 它有声音

The only down side is it is loud

0:02:36.200,0:02:40.150
这个压制机它有时候制冷的时候咕咕咕的响

Sometimes the compressor makes loud noise 

0:02:40.600,0:02:43.200
有一点点声响 就比家用的要响一点

 Just a little more louder than a domestic one  

0:02:43.200,0:02:44.350
估计有两米左右（高）

Roughly 2 meters in height

0:02:44.500,0:02:46.650
然后宽的话很宽 

And it is pretty wide

0:02:48.125,0:02:49.350
耗电量的话也高

Electricity consumption is quite high

0:02:49.350,0:02:51.550
这个最好呢一个好处是什么呢

What's good about it is 

0:02:51.550,0:02:52.400
就是空间大

It is spacious 

0:02:53.200,0:02:54.375
可以放很多东西

It can accommodate lots of stuff

0:02:54.375,0:02:57.400
上面是保鲜 下面是急冻

Refrigerate on the top and freeze at the bottom

0:03:02.550,0:03:04.600
冻两三个（头）猪儿都冻得到

You can even put 2-3 pigs in there	

0:03:04.600,0:03:06.625
两三个猪儿 可以哦

2-3 piglets, sure thing

0:03:07.725,0:03:10.100
这个冰柜很舒服 就是用起来很舒服

This refrigerator is handy to use

0:03:10.100,0:03:12.125
如果你们家人口比较多的话

If you have a big family

0:03:12.125,0:03:16.775
像我们家一家十多口人就适合用这种冰箱

Like us we have more than 10 people in our family 

0:03:16.775,0:03:20.525
如果你们家三四个人五六个人的话就特别不适合

But if your family only has 3-6 people this wouldn't be your best option

0:03:20.525,0:03:24.325
这个的话就只适合怎么说呢酒店里面用

This is suitable for hotels

0:03:25.075,0:03:28.150
还有我们这个冰箱不管是这种还是家里面用的

And another thing is these refrigerators both domestic and industrial 

0:03:28.150,0:03:31.650
拿回来都要放一段时间 放两三个小时再插电

You need to let it sit for 2-3 hours before plug it in 

0:03:31.775,0:03:34.775
然后这个冰箱它的价格是2400块钱

And this one cost about 2400 yuan

0:03:34.775,0:03:40.400
就价格来说的话比我们家用的便宜了不是一点点

Price wise it is a lot cheaper than domestic ones

0:03:40.575,0:03:42.825
家用的那个冰箱有几万的都有

Domestic refrigerators can cost up to tens of thousands 

0:03:42.825,0:03:44.525
我见过最贵的几万

The most expensive one I've seen can cost tens of thousands 

0:03:44.525,0:03:46.250
但是这个的话是非常实用的

But this is very practical 

0:03:46.250,0:03:51.300
它除了能耗就是电量 耗电量高一点点之外

This only down side is it cost a little more on electricity 

0:03:51.300,0:03:55.775
大坨一点之外没有其他什么缺点

And it's a little bulky, other than those it's great 

0:03:56.350,0:04:00.625
还有我们这个冰箱靠墙放的话后面要有一点距离

Also we need to leave a small gap between the wall

0:04:00.625,0:04:03.375
不能够让它贴紧了 贴紧了没办法散热

If it sits too close to the wall, heat can not dissipate away

0:04:03.850,0:04:05.525
朝里面移一点点

Move it in a little bit 

0:04:07.300,0:04:08.800
好 要得了要得了

Alrighty, that will do

0:04:10.150,0:04:13.975
这个滚滚（轮子）你要固定一哈 拿个啥子东西来塞到

You need to find something to block the wheels

0:04:14.900,0:04:16.350
嗯塞哈 稍微塞哈就是

Yeah I will find something 

0:04:16.350,0:04:19.275
不是它要到处跑 稍微哪样点

Otherwise it will roll all around the place

0:04:20.925,0:04:24.213
四伯爷你看嘛 这个冰箱就可以这样子关门

Look Siboye, you can close the fridge like this

0:04:24.213,0:04:25.800
你的就 你不敢这样子关

You can't to this to yours 

0:04:26.525,0:04:27.650
看到没

Look

0:04:30.250,0:04:33.150
小心点 当真是新的是不哦

Careful, are you sure this is brand new?

0:04:33.150,0:04:38.925
不是 它就是那个个性晓得不嘛

Nah this is how it works

0:04:38.925,0:04:42.600
个性 金子做的都遭不住这样子整

It won't last long even if it's made from gold 

0:04:42.625,0:04:45.625
金子做的就发（财）了

If it were made from gold I'll be so rich

0:04:45.625,0:04:47.200
那不是咋子安

Surely you will 

0:04:47.200,0:04:49.157
好了 本期就给你们介绍到这里了

Alright this is the end of this video

0:04:49.157,0:04:51.300
随便啥子东西都要保护得好才得行

You need to cherish everything 

0:04:51.300,0:04:53.675
保护得不好几家伙就整烂了

Otherwise you will break it not for long 

0:04:53.675,0:04:54.200
是

Yes sir!

0:04:54.200,0:04:56.150
整烂了还是你的劳动成果去买

And then you will have to use your own work to pay for a new one

0:04:56.850,0:04:58.500
是 是这样子

Yes you are right 

0:04:59.425,0:05:01.175
好了 本期视频到这里

Alright that's it 

0:05:01.175,0:05:01.950
拜拜

Bye-bye

**Comment by immoonancient** [comment]
bot, please upload on behalf of the assignee

厨师长又一硬核开箱：“酒店大冰箱”和家用冰箱的区别，看看大家是不是也想要一个？
Head chef unboxes "Industrial refrigerator" and home refrigerator. Do you want one too?

简介
朋友们好，为了配合猛火灶，打算逐步完善我的乡下厨房，
这次购入了后厨的另一个大件“大冰箱”，让我带你们看看和家用的有什么区别。
好处很明显，那就是性价比，价格很低的同时可以得到非常大的储存空间，
非常适合需要大量储存空间的朋友。
但缺点也很明显，因为保温性能和温控性能不如家用冰箱，
所以更加耗电，并且压缩机的噪音也相对较大。
最后就是要看大家的需求了，如果家人很多，想经常储存大量的食材，
并且空间够用的话，这种款式的冰箱还是值得推荐的！
Hello everyone, to facilitate with the powerful burner stove, I plan to gradually improve my country side kitchen.
This time I bought a big refrigerator, let me show you the difference between it and a normal home refrigerator.
It has apparent pros that is it's cost-performance ratio, you can get a large storage space with a low price
which is very suitable for friends need a large storage need.
But it has obvious cons as well, because it has inferior insulation and temperature control performance,
it consumes more electricity and produces a louder noise from the compressor.
Lastly its all up to each and every one's need, if you have a large family and have many ingredients to store,
this type of refrigerator is a good choice.

字幕
0:00:01.350,0:00:03.150
嗨喽大家好 我是王刚
Hello everyone this is Wang Gang
0:00:03.500,0:00:06.575
前段时间我们买了一套工程款的那个炉灶回来
Not too long ago we bought a industrial gas stove
0:00:07.000,0:00:10.025
今天我又买了一个工程款的冰箱
And today I bough a industrial refrigerator
0:00:10.025,0:00:12.450
这个冰箱四五百斤 宽也很宽
It weights 400-500 jin (200-250kg) and pretty wide
0:00:12.450,0:00:14.275
跟我们屋头的不一样
Not quite the same as the one we had at home
0:00:14.275,0:00:16.675
肯定不一样哦 你那个好大哦
Surely it's not the same, the other one is not the same size
0:00:16.675,0:00:21.209
然后这个好像能耗也比你那个高
And this one uses more electricity than the other one
0:00:21.209,0:00:24.275
肯定撒 你冻的东西都比较多按
For sure, this one have more storage capacity
0:00:24.275,0:00:26.175
肯定那耗电量肯定大撒
It surely consumes more electricity
0:00:26.175,0:00:28.800
好 现在我们去看一下 去开箱
Alright let's go take a look and unbox it
0:00:29.100,0:00:29.800
走嘛
It's go
0:00:30.025,0:00:32.275
这钉子些取不取哦
Do we need to remove these nails?
0:00:32.275,0:00:36.975
钉子不取都要得 后头要留一部分留个那种（缝缝）出来
It doesn't matter, we need to leave a gap on the back
0:00:37.775,0:00:38.775
留个缝缝
Leave a gap
0:00:38.775,0:00:40.400
对 要留个缝缝
Yep leave a gap
0:00:40.825,0:00:43.000
不是它那个散不到热
Otherwise the heat can't get out
0:00:43.400,0:00:44.550
来嘛 （移）哈嘛四伯爷
Come let's move this Siboye
0:00:44.550,0:00:46.250
这个门朝这方移
Move it towards the door
0:00:46.650,0:00:48.676
都还好这个有轮子 不是的话（不好移）
Good that it's on wheels otherwise (are difficult to move)
0:00:48.676,0:00:49.750
你朝门口扯撒
Pull it towards the door
0:00:52.250,0:00:54.325
这个没得轮子的话才懒得搞
It will be very difficult to move without these wheels
0:00:54.325,0:00:55.850
没得轮子害怕你够得干安
I doubt you can even move it without those wheels
0:00:55.850,0:00:58.700
等一哈等一哈 把那个胶纸取了多
What a minute, lets remove these wraps
0:00:59.050,0:01:00.350
我拿菜刀来割
I'll go get a knife
0:01:02.775,0:01:04.650
这根绳子要整了来
Cut this rope
0:01:11.900,0:01:13.300
这个拿得下来不
Can you take this off
0:01:13.300,0:01:14.675
拿得下来这个
We need to take this off
0:01:15.675,0:01:16.975
先把这个取了
First we take this off
0:01:19.300,0:01:20.775
卡起了 没得那么高的
It got stuck, I'm not tall enough
0:01:21.425,0:01:23.175
四伯爷 你更拿不到
Siboye you can't reach it
0:01:23.175,0:01:24.100
有啥子拿不到哦
What are you talking about?
0:01:26.025,0:01:29.150
这儿还有点卡起得
This bit got stuck
0:01:36.025,0:01:36.950
可以咯
Alrighty
0:01:36.950,0:01:37.575
这上面呢
What about up there
0:01:37.575,0:01:38.575
泡沫拿了就可以了
Take off those foam then that's it
0:01:39.125,0:01:41.275
不要慌四伯爷 我把这儿割了多
Hang on Siboye, let me cut this part first
0:01:46.425,0:01:48.675
这里都有点压烂了
This part is dented
0:01:50.450,0:01:54.350
这个是我们运输过程当中挤压到了
That happened during the transportation process
0:01:54.350,0:01:56.783
这一点点没事 不影响使用
It doesn't matter, won't affect the usage
0:01:56.783,0:01:58.525
在路高头压到的啊
It got dented on the way?
0:01:59.575,0:02:02.175
哦哟 这里也遭压了
Crap this part is also dented
0:02:08.200,0:02:12.750
这个不关事 皮子上面有点压到不影响使用
It not a big deal, just on the shell won't affect the performance
0:02:12.750,0:02:15.350
主要是看它压缩机啊那个
As long as the compressor is working fine
0:02:15.350,0:02:16.875
这不美观的嘛
It doesn't look good
0:02:17.350,0:02:19.300
哎呀 这个东西实用就OK了
Well this thing is more about its functionality
0:02:19.300,0:02:23.500
你买的时候咋不跟他交涉呢 你包送包给我上下（货）
Why you didn't negotiate (with the seller) when you bought is, they take care of the shipment and courier process
0:02:23.825,0:02:27.025
你整坏了这些我要我都不要 你拿去换过
If you damaged it, I won't sign off and get me a new one
0:02:27.275,0:02:29.075
哎呀 将心比心
Well if you put yourself in their shoes
0:02:29.075,0:02:31.950
我们看一下这个空间
Let's look at the space
0:02:32.300,0:02:36.200
这个的话唯一不好的是什么呢 它有声音
The only down side is it is loud
0:02:36.200,0:02:40.150
这个压制机它有时候制冷的时候咕咕咕的响
Sometimes the compressor makes loud noise
0:02:40.600,0:02:43.200
有一点点声响 就比家用的要响一点
Just a little more louder than a domestic one
0:02:43.200,0:02:44.350
估计有两米左右（高）
Roughly 2 meters in height
0:02:44.500,0:02:46.650
然后宽的话很宽
And it is pretty wide
0:02:48.125,0:02:49.350
耗电量的话也高
Electricity consumption is quite high
0:02:49.350,0:02:51.550
这个最好呢一个好处是什么呢
What's good about it is
0:02:51.550,0:02:52.400
就是空间大
It is spacious
0:02:53.200,0:02:54.375
可以放很多东西
It can accommodate lots of stuff
0:02:54.375,0:02:57.400
上面是保鲜 下面是急冻
Refrigerate on the top and freeze at the bottom
0:03:02.550,0:03:04.600
冻两三个（头）猪儿都冻得到
You can even put 2-3 pigs in there
0:03:04.600,0:03:06.625
两三个猪儿 可以哦
2-3 piglets, sure thing
0:03:07.725,0:03:10.100
这个冰柜很舒服 就是用起来很舒服
This refrigerator is handy to use
0:03:10.100,0:03:12.125
如果你们家人口比较多的话
If you have a big family
0:03:12.125,0:03:16.775
像我们家一家十多口人就适合用这种冰箱
Like us we have more than 10 people in our family
0:03:16.775,0:03:20.525
如果你们家三四个人五六个人的话就特别不适合
But if your family only has 3-6 people this wouldn't be your best option
0:03:20.525,0:03:24.325
这个的话就只适合怎么说呢酒店里面用
This is suitable for hotels
0:03:25.075,0:03:28.150
还有我们这个冰箱不管是这种还是家里面用的
And another thing is these refrigerators both domestic and industrial
0:03:28.150,0:03:31.650
拿回来都要放一段时间 放两三个小时再插电
You need to let it sit for 2-3 hours before plug it in
0:03:31.775,0:03:34.775
然后这个冰箱它的价格是2400块钱
And this one cost about 2400 yuan
0:03:34.775,0:03:40.400
就价格来说的话比我们家用的便宜了不是一点点
Price wise it is a lot cheaper than domestic ones
0:03:40.575,0:03:42.825
家用的那个冰箱有几万的都有
Domestic refrigerators can cost up to tens of thousands
0:03:42.825,0:03:44.525
我见过最贵的几万
The most expensive one I've seen can cost tens of thousands
0:03:44.525,0:03:46.250
但是这个的话是非常实用的
But this is very practical
0:03:46.250,0:03:51.300
它除了能耗就是电量 耗电量高一点点之外
This only down side is it cost a little more on electricity
0:03:51.300,0:03:55.775
大坨一点之外没有其他什么缺点
And it's a little bulky, other than those it's great
0:03:56.350,0:04:00.625
还有我们这个冰箱靠墙放的话后面要有一点距离
Also we need to leave a small gap between the wall
0:04:00.625,0:04:03.375
不能够让它贴紧了 贴紧了没办法散热
If it sits too close to the wall, heat can not dissipate away
0:04:03.850,0:04:05.525
朝里面移一点点
Move it in a little bit
0:04:07.300,0:04:08.800
好 要得了要得了
Alrighty, that will do
0:04:10.150,0:04:13.975
这个滚滚（轮子）你要固定一哈 拿个啥子东西来塞到
You need to find something to block the wheels
0:04:14.900,0:04:16.350
嗯塞哈 稍微塞哈就是
Yeah I will find something
0:04:16.350,0:04:19.275
不是它要到处跑 稍微哪样点
Otherwise it will roll all around the place
0:04:20.925,0:04:24.213
四伯爷你看嘛 这个冰箱就可以这样子关门
Look Siboye, you can close the fridge like this
0:04:24.213,0:04:25.800
你的就 你不敢这样子关
You can't to this to yours
0:04:26.525,0:04:27.650
看到没
Look
0:04:30.250,0:04:33.150
小心点 当真是新的是不哦
Careful, are you sure this is brand new?
0:04:33.150,0:04:38.925
不是 它就是那个个性晓得不嘛
Nah this is how it works
0:04:38.925,0:04:42.600
个性 金子做的都遭不住这样子整
It won't last long even if it's made from gold
0:04:42.625,0:04:45.625
金子做的就发（财）了
If it were made from gold I'll be so rich
0:04:45.625,0:04:47.200
那不是咋子安
Surely you will
0:04:47.200,0:04:49.157
好了 本期就给你们介绍到这里了
Alright this is the end of this video
0:04:49.157,0:04:51.300
随便啥子东西都要保护得好才得行
You need to cherish everything
0:04:51.300,0:04:53.675
保护得不好几家伙就整烂了
Otherwise you will break it not for long
0:04:53.675,0:04:54.200
是
Yes sir!
0:04:54.200,0:04:56.150
整烂了还是你的劳动成果去买
And then you will have to use your own work to pay for a new one
0:04:56.850,0:04:58.500
是 是这样子
Yes you are right
0:04:59.425,0:05:01.175
好了 本期视频到这里
Alright that's it
0:05:01.175,0:05:01.950
拜拜
Bye-bye
