### ISSUE TITLE
【美食作家王刚】小炒猪肝 - https://youtu.be/ns2ki06u8XU

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#815]
**视频链接**：https://youtu.be/ns2ki06u8XU

视频时长 3:15，预计发布时间为北京时间3月24日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“小炒猪肝”的家常做法，一锅成菜味道干香，很简单学起来

简介
同学们好，今天和大家分享一道经典家常菜“小炒猪肝”，此菜讲究一锅成菜，干香十足，所以不需要打汁勾芡等，猪肝也不需要特殊处理，只需按照此法腌制即可。这样做出来的猪肝保留了特有的香味，特别下饭，并且做法简单，喜欢的朋友们一定不要错过！

本期菜品:【小炒猪肝】
【主料】
猪肝（350克）
【辅料】
大蒜（几颗）
生姜（约15克）
小米辣（30克）
大红椒（1个）
蒜苗（3根）
植物油（适量）
【调味料】
食用盐（小半勺）
胡椒粉（适量）
老抽(适量)
白糖（少许）
蚝油（5克）
生抽酱油（2克）


字幕
0:00:00.560,0:00:01.800
哈喽大家好 我是王刚

0:00:01.800,0:00:03.680
本期视频我给大家分享一道家常菜

0:00:04.160,0:00:05.080
小炒猪肝

0:00:05.420,0:00:08.120
首先我们准备新鲜的猪肝350克

0:00:08.678,0:00:10.559
加入清水清洗干净之后备用

0:00:11.036,0:00:13.980
此做法属于干香类菜需要提前清洗干净

0:00:16.851,0:00:19.661
清洗干净之后将猪肝切成3毫米左右的厚片

0:00:19.967,0:00:23.729
同学们可以适当的切厚一些这样更方便新手操作

0:00:29.215,0:00:31.304
猪肝切好之后下一步开始腌制

0:00:31.732,0:00:33.406
碗中加入食用盐小半勺（约0.5克）

0:00:33.797,0:00:35.189
加入胡椒粉0.5克

0:00:35.800,0:00:37.279
加入老抽3克调底色

0:00:39.600,0:00:41.298
调好味之后抓拌均匀备用

0:00:46.527,0:00:48.665
最后加入少许的食用油搅拌均匀

0:00:48.983,0:00:51.365
这一步的目的是防止猪肝下锅黏成一团

0:00:52.966,0:00:54.298
下一步开始准备辅料

0:00:54.811,0:00:56.692
准备大蒜几颗切成小粒备用（约30克）

0:00:59.747,0:01:01.530
准备生姜1小块切成小粒备用（约15克）

0:01:09.814,0:01:11.475
准备小米辣30克切碎备用

0:01:11.781,0:01:13.418
不能吃辣的同学可以不加

0:01:14.053,0:01:15.959
准备大红椒1个切成小颗粒备用

0:01:21.164,0:01:23.522
准备蒜苗3根轻轻拍散之后切碎备用

0:01:28.116,0:01:29.191
下一步开始制作

0:01:29.667,0:01:30.938
首先我们把锅烧热

0:01:31.231,0:01:33.064
锅烧热之后加入适量的油滑锅

0:01:36.411,0:01:38.000
滑好锅之后将热油倒出

0:01:40.382,0:01:41.604
然后加入适量的冷油

0:01:44.292,0:01:46.540
再将腌制好的猪肝下锅滑10秒钟

0:01:46.906,0:01:48.959
这一步的目的是将猪肝炒至定型（此时约5成熟）

0:01:55.238,0:01:58.146
然后将切好的姜蒜粒和辣椒粒下锅翻炒30秒

0:01:58.439,0:02:00.186
这一步的目的是将料头炒香

0:02:00.797,0:02:02.948
同学们家庭小灶则需要2分钟左右

0:02:04.169,0:02:06.051
翻炒30秒钟之后开始调味

0:02:07.383,0:02:09.007
锅中加入胡椒粉0.5克

0:02:09.643,0:02:11.011
加入少许白糖提鲜

0:02:11.866,0:02:12.819
加入蚝油5克

0:02:15.446,0:02:16.595
加入生抽酱油2克

0:02:18.696,0:02:20.553
最后加入老抽2克翻炒几下

0:02:25.025,0:02:27.102
翻炒均匀之后再加入切好的蒜苗粒

0:02:29.899,0:02:32.245
开中小火翻炒至断生即可出锅装盘

0:02:40.200,0:02:42.400
一道干香下饭的小炒猪肝就制作完成

0:02:48.020,0:03:08.740
下面开始技术总结
第一，切猪肝之前必须清洗干净，切好之后不用冲洗，
这样才能爆出猪肝原香味（建议此做法切好之后不清洗）
第二，腌制猪肝的时候不必加入淀粉，只需要盐胡椒粉老抽即可
第三，此版本为家常做法，湖南地区可以加入适量的豆豉增加地方风味
小炒猪肝的技术总结完毕


```

**Comment by immoonancient** [comment]
@greentea007 请前来认领

**Comment by greentea007** [comment]
认领

**Comment by immoonancient** [comment]
@greentea007 表示时间安排不了

**Comment by Jasminelv** [comment]
认领

**Comment by Jasminelv** [comment]
厨师长教你：“小炒猪肝”的家常做法，一锅成菜味道干香，很简单学起来

简介
同学们好，今天和大家分享一道经典家常菜“小炒猪肝”，此菜讲究一锅成菜，干香十足，所以不需要打汁勾芡等，猪肝也不需要特殊处理，只需按照此法腌制即可。这样做出来的猪肝保留了特有的香味，特别下饭，并且做法简单，喜欢的朋友们一定不要错过！
Hello everyone, today I am sharing a classic home dish “stir fried pork liver”. This dish is pretty simple and straight forward, with great aroma.  It doesn’t need complicated preparation or finishing, therefore it keeps the original and unique flavor of pork liver, very appetizing! 

本期菜品:【小炒猪肝】
Name of dish: stir fried pork liver
【主料】
Main ingredient 
猪肝（350克）
Pork liver 350 grams (0.8 lbs)
【辅料】
Seasonings:
大蒜（几颗）
Garlic: a few cloves
生姜（约15克）
Ginger: about 15 grams 
小米辣（30克）
Spicy red chili: 30 grams
大红椒（1个）
Red bell pepper: 1 
蒜苗（3根）
Garlic sprouts: 3 counts
植物油（适量）
Vegetable oil: your preference
【调味料】
Spices:
食用盐（小半勺）
Salt: a teaspoon
胡椒粉（适量）
White pepper powder: to your taste
老抽(适量)
Dark soy sauce: to your taste
白糖（少许）
Sugar: a pinch
蚝油（5克）
Oyster sauce: 5 grams
生抽酱油（2克）
Light soy sauce: 2 grams


字幕
0:00:00.560,0:00:01.800
哈喽大家好 我是王刚
Hello everyone, I am Wang Gang.

0:00:01.800,0:00:03.680
本期视频我给大家分享一道家常菜
Today I will share a home dish with you.

0:00:04.160,0:00:05.080
小炒猪肝
Stir fried pork liver.

0:00:05.420,0:00:08.120
首先我们准备新鲜的猪肝350克
First, let’s get 350 grams of fresh pork liver.

0:00:08.678,0:00:10.559
加入清水清洗干净之后备用
Clean it well with water.

0:00:11.036,0:00:13.980
此做法属于干香类菜需要提前清洗干净
No more cleaning is further needed.

0:00:16.851,0:00:19.661
清洗干净之后将猪肝切成3毫米左右的厚片
Cut it into 3mm slices.

0:00:19.967,0:00:23.729
同学们可以适当的切厚一些这样更方便新手操作
If you are a newbie you can slice it even thicker.

0:00:29.215,0:00:31.304
猪肝切好之后下一步开始腌制
Then we marinate it.

0:00:31.732,0:00:33.406
碗中加入食用盐小半勺（约0.5克）
0.5 gram of salt

0:00:33.797,0:00:35.189
加入胡椒粉0.5克
0.5 gram of white pepper

0:00:35.800,0:00:37.279
加入老抽3克调底色
3 grams of dark soy sauce for the color

0:00:39.600,0:00:41.298
调好味之后抓拌均匀备用
Hand mix the ingredients nice and well

0:00:46.527,0:00:48.665
最后加入少许的食用油搅拌均匀
Add some vegetable oil and stir it well 


0:00:48.983,0:00:51.365
这一步的目的是防止猪肝下锅黏成一团
This is to prevent the pork liver from sticking together in the wok

0:00:52.966,0:00:54.298
下一步开始准备辅料
Next we prepare the seasonings.

0:00:54.811,0:00:56.692
准备大蒜几颗切成小粒备用（约30克）
Cut the garlic cloves into smaller pieces (around 30 grams)

0:00:59.747,0:01:01.530
准备生姜1小块切成小粒备用（约15克）
Cut ginger into small pieces too (around 15 grams)

0:01:09.814,0:01:11.475
准备小米辣30克切碎备用
Cut red hot chili pepper finely (about 30 grams)

0:01:11.781,0:01:13.418
不能吃辣的同学可以不加
If you don’t like spicy food, you can skip this.

0:01:14.053,0:01:15.959
准备大红椒1个切成小颗粒备用
Cut the red bell pepper into small pieces.

0:01:21.164,0:01:23.522
准备蒜苗3根轻轻拍散之后切碎备用
Lose the garlic sprouts with the back of the knife, then cut into pieces.

0:01:28.116,0:01:29.191
下一步开始制作
We are now ready to cook.

0:01:29.667,0:01:30.938
首先我们把锅烧热
First let’s heat the wok.

0:01:31.231,0:01:33.064
锅烧热之后加入适量的油滑锅
Then we add some oil to coat the wok.

0:01:36.411,0:01:38.000
滑好锅之后将热油倒出
When the wok is well coated with oil, pour out the heated oil.

0:01:40.382,0:01:41.604
然后加入适量的冷油
Then add some cold oil.

0:01:44.292,0:01:46.540
再将腌制好的猪肝下锅滑10秒钟
Slide the pork liver in and cook it for 10 seconds

0:01:46.906,0:01:48.959
这一步的目的是将猪肝炒至定型（此时约5成熟）
The purpose of this step is to half cook it and firm it a little.

0:01:55.238,0:01:58.146
然后将切好的姜蒜粒和辣椒粒下锅翻炒30秒
Then add the ginger, garlic, and hot chili pepper, stir fry for 30 seconds

0:01:58.439,0:02:00.186
这一步的目的是将料头炒香
Until you smell the aroma.

0:02:00.797,0:02:02.948
同学们家庭小灶则需要2分钟左右
When you cook at home, it might take up to 2 minutes.

0:02:04.169,0:02:06.051
翻炒30秒钟之后开始调味
After 30 seconds you’ll start to add spices to it.

0:02:07.383,0:02:09.007
锅中加入胡椒粉0.5克
Add white pepper powder 0.5 gram

0:02:09.643,0:02:11.011
加入少许白糖提鲜
Then a pinch of sugar

0:02:11.866,0:02:12.819
加入蚝油5克
5 grams of oyster sauce

0:02:15.446,0:02:16.595
加入生抽酱油2克
2 grams of light soy sauce

0:02:18.696,0:02:20.553
最后加入老抽2克翻炒几下
Lastly, 2 grams of dark soy sauce

0:02:25.025,0:02:27.102
翻炒均匀之后再加入切好的蒜苗粒
Stir fry well, then add garlic sprout pieces

0:02:29.899,0:02:32.245
开中小火翻炒至断生即可出锅装盘
With mid-low heat, when the garlic sprout is half cooked, we can serve it.

0:02:40.200,0:02:42.400
一道干香下饭的小炒猪肝就制作完成
Here we have the appetizing aromatic stir fry pork liver.

0:02:48.020,0:03:08.740
下面开始技术总结
Next is our cooking tips:
第一，	切猪肝之前必须清洗干净，切好之后不用冲洗，
First, rinse and clean the pork liver well before cutting it. No more washing or rinsing is further needed, in order to have the best flavor.
这样才能爆出猪肝原香味（建议此做法切好之后不清洗）
第二，	腌制猪肝的时候不必加入淀粉，只需要盐胡椒粉老抽即可
Second, no need for any corn starch.  Only need salt, white pepper powder, and dark soy sauce.
第三，	此版本为家常做法，湖南地区可以加入适量的豆豉增加地方风味
Third, you can add fermented soybean if you prefer HuNan cuisine. 
小炒猪肝的技术总结完毕
That concludes the tips for Stir-Fried Pork Liver.
