### ISSUE TITLE
[老饭骨] 乾隆白菜 - https://www.youtube.com/watch?v=CvU8cmkxOUA

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#819]
**视频链接**：https://www.youtube.com/watch?v=CvU8cmkxOUA

# 请翻译以下全部内容

**标题（翻译主要意思即可，不要超过 100 个字符）**
【国宴大师•乾隆白菜】最正宗的乾隆白菜在此，酸甜爽口，咸香浓郁，厨房小白的第一道拿手菜就是它

**简介**
小友们好，二伯今天要教给大家伙儿一道简单但又经典的拌菜，乾隆白菜。
视频里二伯提到的单位，是便宜坊集团。
成立于明·永乐年。乾隆白菜是便宜坊集团旗下，都一处首创的招牌菜。
乾隆帝曾给都一处亲自赐匾题词。
所以说，今天大家要学到的可是乾隆白菜最正宗的做法了。
这道拌菜所用的材料以及做法都很简单，十分适合厨房新手。
但其味道又不简单，糖醋的酸甜爽口，再配上麻酱的咸香，多重口味刺激你的味蕾。
怎么样？以后可别小瞧这普通的白菜了，它可是能做出许多美味可口的佳肴呢！

**字幕**
本期是早前制作视频，原始字幕文件已丢失
请使用 [YouTube 原生工具](https://www.youtube.com/timedtext_editor?action_mde_edit_form=1&v=CvU8cmkxOUA&lang=en&tab=captions)制作带时间轴的字幕

**Comment by archerdominique** [comment]
bot, please upload
0:00:00.000,0:00:02.200
你在这倒腾什么呢 白菜啊
- What are you making here? - Napa cabbage

0:00:02.200,0:00:05.060
白菜是什么菜 乾隆白菜
- Napa cabbage made in what way? - Qian Long Napa Cabbage (Qian Long: one of the emperors of the Qing Dynasty)

0:00:05.060,0:00:07.740
其实我给更正名儿叫乾隆拌菜
Actually I would change its name to Qian Long Cabbage Salad

0:00:07.740,0:00:10.920
然后你看 芝麻酱
Then you see, (put in) the seasame paste

0:00:10.920,0:00:15.300
你看啊 糖 糖还不少呢
And sugar, more than just a little

0:00:17.020,0:00:19.160
不够甜呢就得搁点盐
If it is not sweet enough, add in some salt

0:00:19.160,0:00:22.060
这菜就是我们公司发明的
This dish is invented by our company

0:00:24.140,0:00:25.760
这搁点儿香油
A little bit seasame oil

0:00:26.960,0:00:30.860
原来他们好多人使米醋 这米醋就不对
I've seen quite a few people using rice vinegar, which is not right

0:00:30.860,0:00:33.980
其实最好是镇江香醋
It's better to use Zhenjiang vinegar

0:00:33.980,0:00:36.880
这醋都差点儿意思
This one is a bit not as good

0:00:37.780,0:00:41.880
到底是以甜酸为主还是以咸鲜为主
Does it gonna feature the sweet-n-sour taste or the umami?

0:00:41.880,0:00:43.640
甜酸咸都有
It has them all

0:00:44.700,0:00:48.320
还是糖醋为主 糖醋稍微大一点
It's mostly sweet-n-sour. The taste of sugar and vinegar would be a little more prominent

0:00:48.320,0:00:49.420
爽口
Tasty and refreshing

0:00:50.800,0:00:52.680
老抽 旁边儿
Dark soy sauce, from the sides

0:00:52.680,0:00:56.200
你看醋都没上上色 原来为什么拌的颜色不对啊
You see, it has not get the right colour from the vinegar

0:00:57.720,0:00:59.560
颜色浅 颜色不够
The colour is too mild

0:01:00.860,0:01:02.775
这色你看还浅
Still mild

0:01:03.260,0:01:06.140
镇江香醋这颜色一下就提起来了
If you use Zhenjiang vinegar the colour would come out immediately

0:01:08.080,0:01:12.020
矿泉水啊
Water

0:01:17.425,0:01:20.785
这就好了点儿 颜色上来了
Now it's better. The colour is emerging

0:01:20.785,0:01:24.320
还缺一样东西 蜂蜜
We need one more thing - honey

0:01:26.420,0:01:31.180
甜酸咸 酱香就是麻酱的香气都能吃出来
Sweet, sour, salty, you can even taste the aroma of seasame paste

0:01:31.180,0:01:33.120
它也是一个复合味
So it has a combo of flavour

0:01:33.120,0:01:35.860
但您搁蜂蜜我觉得特别巧妙
I think, it is very ingenious of you to add the honey

0:01:35.880,0:01:37.300
搁这里边
Put in here

0:01:39.060,0:01:40.860
搅拌均匀
Stir and mix thoroughly

0:01:41.800,0:01:45.940
我这个不好拌啊 还是放个大家伙里头吧
This one is not handy for mixing. I'd better find a larger container

0:01:45.940,0:01:48.100
拿那菜擦擦那盆儿
Pick a leaf to wipe the basin

0:01:49.200,0:01:50.520
老大就是老大啊
I see why you are the first of us

0:01:50.520,0:01:53.700
不是 因为这汁儿特别好吃
Nah, because this sauce is extremely delicious

0:01:53.700,0:01:56.220
这一擦 好家伙
Wiping it, gracious me!

0:01:56.680,0:02:01.140
菜也拌匀了 汁也都擦到菜上了
The veggies are mixed thoroughly with the sauce, and the sauce is sticked to the leaves

0:02:01.140,0:02:03.740
你看外面那麻酱 那没法吃
You know, the seasame paste they use out there, it is even not edible

0:02:03.740,0:02:07.140
要味没味 要颜色没颜色
Ain't got no taste or colour

0:02:07.140,0:02:08.880
白菜有什么要求么
Is there any requirement for the cabbage? 

0:02:08.880,0:02:11.220
您看见没有 全是黄心儿的
Don't you see, the colour is all yellow

0:02:11.220,0:02:14.080
好白菜 这东西绝对不能糊弄
This is cabbage of quality. You must not muddle with it. 

0:02:14.560,0:02:18.100
这是白菜心儿 叶儿占的比例还比较多
This is the heart of the cabbage. It has a considerable proportion of leaves

0:02:18.100,0:02:21.440
对 基本上使叶儿是最好的
Yep. Basically it's best to use the leaves

0:02:21.440,0:02:22.900
来点芝麻啊咱们
Let's get some seasame

0:02:22.905,0:02:26.205
撒里边就行
Just drop in

0:02:27.965,0:02:30.665
我觉得啊 这白菜要是搁点黑芝麻更好看
I think, the cabbage would look better with black seasame

0:02:32.420,0:02:34.380
对啊 那当然是了
Yeah, of course

0:02:34.380,0:02:38.040
黑芝麻的颜色出来以后这效果好
The colour of black seasame would add to the effects

0:02:38.040,0:02:39.680
你看 这叫乾隆白菜
You see, this is what we call Qian Long Napa Cabbage

0:02:39.680,0:02:42.880
这颜色 颜色漂亮 特润
The colour, the colour is so pretty, and looks extremely smooth

0:02:42.920,0:02:46.480
而且每个叶儿上都均匀的裹上了麻酱
Each leave is evenly wrapped with the seasame paste

0:02:46.480,0:02:50.160
现在（外边的）乾隆白菜都不对 没错
- Now people out there are not making the right Qian Long Napa Cabbage. - Exactly

0:02:50.280,0:02:53.220
您还甭说别的 咱看看这个怎么样
No more words, let's see how is this dish

0:02:53.220,0:02:57.960
看您心情吧 我 看您心情 （哎哟哟哟）心情好
- As you please. - Ohh I AM very pleased (这句的意思实在有点捉摸不透)

0:02:57.960,0:02:59.960
您看看这个 这拌完这盆儿
Have a look on this basin after the mixing work

0:02:59.960,0:03:01.520
盆儿干净 不是干净
- It's clear. - Not about being clear or not

0:03:01.525,0:03:04.415
你看这盆儿 它的酱全挂在这儿
You see, it's all covered with the remnant paste

0:03:04.420,0:03:07.360
它不是说像那澥得全是水
It's not watery at all, without any superfluous water

0:03:07.360,0:03:08.980
你说这样它能拌不上么
So the source can definitely stick to the cabbage

0:03:08.980,0:03:10.700
再点点儿芝麻
A little more seasame

0:03:13.200,0:03:18.020
星星点点 芝麻酥香 白菜脆嫩
Specks of aromatic seasame with crispy and tender cabbage

0:03:18.020,0:03:21.380
麻酱润香润香的
The seasame paste is smooth and flavourful

0:03:33.580
我是大爷
