### ISSUE TITLE
[华农兄弟] 铁皮石斛炖大公鸡 - https://youtu.be/3o_GqxEfFBM

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#820]
https://youtu.be/3o_GqxEfFBM
<p>&#35270;&#39057;&#21457;&#24067;&#20110; March 20, 2020 at 11:49AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
0:00:00.000,0:00:03.900
# 大家好  今天去看一下兄弟跟攝影小哥一起種的那個
Hi everyone! Today we're gonna take a look at the, the shi hu planted by Mr. Cameraman,

0:00:04.120,0:00:04.980
# 鐵皮石斛啊
and our buddy.

0:00:05.280,0:00:06.320
# 看一下還在不在
Let's see if they're still there.

0:00:06.780,0:00:09.020
# 前幾年前種的哦  就在那前面
They were planted a couple of years go. There, right in front of us.

0:00:09.900,0:00:11.420
# 哇  這路都那麼靚啦
Wa! Why is this path so beautiful now?

0:00:15.780,0:00:17.780
# 你看  這大片都是哦
Look! It's the whole area here.

0:00:18.080,0:00:21.160
# 棚子都爛啦  沒有管  裡面都是好多草啦
The sheds have already run-down. No one takes care of them anymore and they're now full of weed.

0:00:22.300,0:00:24.600
# 當初他們投了  好像應該有幾十萬吧
At that time, they have invested something like hundreds of thousands RMB.

0:00:26.180,0:00:27.160
# 就成這樣子啦
And that's how it looks now.

0:00:28.800,0:00:29.580
# 太浪費啦
What a waste!

0:00:31.700,0:00:33.720
# 到時候我看一下我家裡有沒有地方
Let me see if I can spare some spaces at my place.

0:00:34.320,0:00:36.600
# 在我家田里面搞幾個棚子起來
Then I can build a couple of sheds on my field.

0:00:37.300,0:00:39.580
# 把它們全部撿回去  反正他們不要啦
I'll take them all back home. They've given them up anyway.

0:00:39.640,0:00:40.640
# 我來撿回去
Let me take them back.

0:00:42.440,0:00:43.660
# 萬一漲價了呢
Who knows? The price may go up.

0:00:46.560,0:00:48.280
# 就在這裡面  我進去看一下
It's right inside. Let me get in and have a look.

0:00:49.560,0:00:51.920
# 哇  全是雜草叢生
Wa! There's nothing but weed!

0:00:52.440,0:00:55.780
# 這個就是鐵皮石斛哦  現在們他沒有管理好
These are the shi hu. But now, they're not taking care of them anymore.

0:00:56.420,0:00:57.260
# 他們太忙了
They might be too busy.

0:00:57.820,0:00:58.960
# 所以就搞成這
So it's now,

0:00:59.260,0:01:00.940
# 造成這樣子  葉子都不見啦
it's now a big piece of mass. I can't even see any leaves.

0:01:01.180,0:01:02.420
# 這個原本要分支的
In fact these need to be branched.

0:01:02.540,0:01:03.740
# 他們就分都沒分  就這樣
But they didn't do anything at all.

0:01:03.900,0:01:05.580
# 也沒有人管  雜草叢生
Nobody takes care of it. There's nothing but weed.

0:01:07.580,0:01:10.420
# 看一下  嘖嘖  那麼漂亮的東西都被他們
Look! My god! It's so pretty but they've,

0:01:11.120,0:01:12.660
# 被他們  這樣糟糟蹋了
they've simply ruined it.

0:01:14.080,0:01:15.700
# 你看  這個都是可以吃的這個
Look! This is edible, you know.

0:01:15.860,0:01:16.760
# 就直接可以咬
You can chew it right away.

0:01:16.960,0:01:18.260
# 我來這樣  就這樣吃都可以吃
I can, like, eat it right here.

0:01:24.900,0:01:26.240
# 就是老  有點老
It's old, a bit old.

0:01:27.020,0:01:27.580
# 不嫩
Not tender at all.

0:01:31.000,0:01:32.400
# 這個是很漂亮的哦  這種
This is really, you know.

0:01:32.660,0:01:33.620
# 葉子都沒有啦
All leaves are gone.

0:01:34.820,0:01:35.880
# 我拿點回去煲湯
Let me take some to make a stew.

0:01:38.060,0:01:40.720
# 來都來了  哪有空手回去的道理
I'm already here. Getting back empty-handed is never an option.

0:01:43.660,0:01:44.220
# 這個
I think,

0:01:44.680,0:01:46.840
# 應該太遠啦  在這裡不好管理
it's way too far. Managing this place takes too much effort.

0:01:47.740,0:01:48.360
# 下次
Let me.

0:01:48.920,0:01:50.520
# 下次我在家也搞個這個棚
Let me also make such a shed at home.

0:01:51.620,0:01:53.760
# 搞這個棚  在這裡拔點苗回去
Make a shed, then I can bring some seedlings from here,

0:01:54.740,0:01:55.960
# 拔點苗回去種
bring some seedlings back from here.

0:01:57.580,0:01:58.220
# 反正
Well,

0:01:59.540,0:02:01.120
# 反正他們也不怎麼管
they've almost abandoned this place.

0:02:05.740,0:02:08.780
# 這種很值錢的哦  以前很值錢的   現在我就不知道
The price is really good. At least it used to be good. But I have no ideas now.

0:02:09.340,0:02:10.920
# 我記得前幾年的時候都
A couple of years go, it was like,

0:02:11.780,0:02:13.280
# 幾百快錢一斤啊  這個
hundreds to a thousand RMB a kilogram.

0:02:15.000,0:02:16.500
# 光這樣的  就這樣纖條
You see, they're just like a bunch of fibre.

0:02:16.800,0:02:18.200
# 就這樣  都幾百塊錢一斤
Nothing special. But it costs hundreds of RMB one kilogram.

0:02:18.940,0:02:19.780
# 你說值不值錢
Isn't it a good price?

0:02:20.400,0:02:21.360
# 比竹鼠還值錢
It costs even more than bamboo rats.

0:02:24.700,0:02:27.220
# 現在可能價格  價格下跌了一點
Now the price, the price might have come down a bit.

0:02:27.860,0:02:28.640
# 他們就不管啦
That's why they stopped growing it.

0:02:29.980,0:02:31.420
# 這樣怎麼行呢  是吧
How can it be? Isn't it?

0:02:31.860,0:02:33.680
# 我在家我也想搞個大棚來
I'm thinking of making a big shed at home.

0:02:34.820,0:02:35.660
# 把它拉回去
Let me take it back.

0:02:36.820,0:02:38.800
# 拉點回去  拉點回去種
Let me take some, take some and plant at home.

0:02:39.620,0:02:41.940
# 苗的話就在這裡拔  拔一點回去
The seedlings can be picked here. Let me pick some back home.

0:02:45.700,0:02:46.700
# 說不定萬一
Who knows? Just in case,

0:02:47.340,0:02:48.340
# 行情好了吶
if the sales are good,

0:02:49.440,0:02:50.580
# 那我不是賺大啦
then doesn't it mean that I can make a good fortune?

0:02:53.620,0:02:54.320
# 你看這種
Look! This is,

0:02:55.780,0:02:57.080
# 這種很靚的  這種
this is really beautiful, isn't it?

0:03:00.380,0:03:01.180
# 拿點回去
Let me pick some,

0:03:02.460,0:03:05.240
# 燉老母雞  剛好我家有個老母雞
to stew with an old hen. It just so happens that I have one at home.

0:03:06.760,0:03:08.320
# 這個葉子都自然掉啦
The leaves are coming off by themselves.

0:03:11.760,0:03:13.480
# 回家  回家拿去曬乾來
Take it back, take it back and dry it under the sun.

0:03:14.360,0:03:16.180
# 或者不用曬也行就直接扔下去
Or I don't even need to dry it. I can simply throw it into the pot,

0:03:17.040,0:03:17.720
# 燉雞湯
and stew with a hen,

0:03:18.500,0:03:19.340
# 或者燉排骨
or ribs.

0:03:20.640,0:03:21.700
# 這個很補的哦這個
It's really good for health you know.

0:03:26.280,0:03:28.040
# 這個 紅杏出牆  (註︰哇~!怎麼譯好呀)
This one, is looking for some affairs out here.

0:03:28.540,0:03:30.700
# 出到牆外面去我都把你抓回來
You're testing the limit but I'll get you back.

0:03:36.800,0:03:38.520
# 這個也可以做成盆景的哦
This one can also be used to make a bonsai,

0:03:38.800,0:03:39.560
# 這個很漂亮的
and is really beautiful.

0:03:40.000,0:03:41.060
# 不過現在沒種它
But I don't have any now.

0:03:41.720,0:03:44.200
# 我拔一棵  我拔一 幾棵 回去
Let me pick one, let me pick one, or some back home,

0:03:44.840,0:03:47.320
# 種  種成一個盆景  把它種  種好看一點
and make, make a bonsai, so that it looks better.

0:03:47.640,0:03:48.380
# 很漂亮的
It would be pretty.

0:03:48.780,0:03:51.880
# 種的不想種的時候就把它捏的來  像這樣子  捏的來
When I don't want it anymore, I can pick it out, like what I'm doing now, pick it out,

0:03:52.360,0:03:53.520
# 燉雞湯 嘖
and stew with chicken, wow!

0:03:53.880,0:03:54.800
# 一舉兩得
It's all up to me.

0:03:56.240,0:03:58.660
# 在家租一個這樣的棚子來種  把它全部 (註︰應該不是「租」，而做「造」)
I can make a similar shed at home, and then,

0:03:59.120,0:04:00.960
# 全部把它搬回去  它們不要啦
and then I can pick them all back. They don't want them anymore.

0:04:07.200,0:04:08.840
# 剛好帶了一個竹筒子過來
It just so happens that I have a bamboo bucket with me.

0:04:09.740,0:04:11.340
# 這個竹筒可以裝這個的哦
I can put the, you know, into the bucket.

0:04:13.080,0:04:14.320
# 你看  把這個塞滿
Look! Let me stuff it full.

0:04:14.900,0:04:16.600
# 種這個一定要用這個樹瞉
This kind of tree bark is a must if you wanna grow these things.

0:04:17.640,0:04:19.100
# 不然的話就不好種
It's not really possible otherwise.

0:04:20.720,0:04:21.480
# 不要那麼多
I don't need that much.

0:04:23.080,0:04:25.420
# 可以 誒詏  有刺啊
Alright! Yeeyo! Spikes!

0:04:26.560,0:04:27.640
# 你看  這裡有一棵
Look! Here's one!

0:04:40.240,0:04:41.400
# 這個樹瞉
The tree bark,

0:04:41.800,0:04:43.280
# 放多點這個樹瞉過去
let me stuff a bit more tree bark.

0:04:50.240,0:04:51.520
# 靚吧  你看
Isn't it beautiful? Look!

0:04:53.100,0:04:56.140
# 我把這個老的要把它捏掉  捏掉之後留下這個小的
I'm gonna pick away, the old ones need to be picked away, leaving only the small ones.

0:04:56.680,0:04:58.560
# 長出來就得漂亮 這個
Then it would be really pretty when it starts growing.

0:04:59.440,0:05:01.000
# 然後掛在這個
Then I can hang it on the,

0:05:01.680,0:05:03.120
# 柱  柱子上  你看
on the pill, pillar. Look!

0:05:03.340,0:05:06.020
# 這個還會開花的哦 這個花  它會不垂
There will even be flowers. The flowers will be, sagging,

0:05:06.400,0:05:08.100
# 它花會慢慢地下垂  垂下來
The flowers will be sagging, sagging down slowly.

0:05:08.940,0:05:11.060
# 垂那麼高  那麼長  嘖  這個
It will be that high, I mean that long, really.

0:05:13.020,0:05:13.520
# 好靚
Beautiful!

0:05:14.960,0:05:17.020
# 帶不盆回去  我帶盆回去
Let me take it back, take it back home,

0:05:17.480,0:05:18.640
# 放到自家陽台上
and place it onto my balcony.

0:05:19.820,0:05:20.780
# 等下種的它這
When it grows,

0:05:21.220,0:05:23.660
# 這個老的話就可以捏來  煲雞湯
The older parts can be picked, to stew with chickens,

0:05:25.400,0:05:26.780
# 煲  煲骨頭湯
or, or with bones.

0:05:28.540,0:05:29.560
# 好啦  回去啦
Alright! Let's go back.

0:05:32.900,0:05:33.760
# (第二天)
The next day

0:05:33.780,0:05:35.900
# 聽說兄弟養了一個很大的公雞哦
I've heard that my buddy has a really large rooster.

0:05:36.120,0:05:37.040
# 你看  那不是啊
Look! Isn't it that one?

0:05:37.460,0:05:38.000
# 就那個
Yeah, that one.

0:05:38.980,0:05:41.840
# 你看  它的那個雞冠都好紅啊  又大
Look! It has a really red, and big cockscomb.

0:05:43.940,0:05:44.440
# 你看
Look!

0:05:45.040,0:05:45.820
# 那個花的
That one is speckled.

0:05:46.880,0:05:48.240
# 它這公雞不會叫我哦
This rooster doesn't yelp at all.

0:05:49.040,0:05:50.360
# 我都沒聽它叫過
I've never heard it yelp.

0:06:03.820,0:06:04.620
# 理都不理我
No response.

0:06:05.500,0:06:06.840
# 肯定不會叫的  這公雞
I don't think it can help, this rooster.

0:06:08.960,0:06:10.740
# 不會叫的公雞就不是好公雞
A rooster is not a good rooster unless it yelps.

0:06:21.880,0:06:22.440
# 來
C'mon!

0:06:23.000,0:06:23.880
# 兄弟送了一個
My buddy just gave me a,

0:06:24.500,0:06:25.500
# 大公雞給我
a giant rooster.

0:06:28.900,0:06:30.920
# 有點毛  他沒幫我搞乾淨
There's still some hair. He didn't clean it well enough.

0:06:33.460,0:06:34.800
# 我把這個大腿缷下來
Let me chop off its leg.

0:06:35.500,0:06:37.060
# 不然它要翹起來這個腿
It would be kicking the lid otherwise.

0:06:39.100,0:06:41.740
# 就這樣  案板都不見啦  誒
I just do it here. The cutting board is gone again, ay!

0:06:42.520,0:06:43.140
# 這樣搞
Too bad.

0:06:44.260,0:06:46.660
# 前兩  前兩天用的那個案板就不見啦
I've, I've used it a couple of days ago. But now it's gone.

0:06:52.160,0:06:54.860
# 你看  裝點水  就直接這樣燜  (註︰他的煲呀，燉呀，炆呀，我不管了，反正他都是亂說的)
Look! I put some water, and then I can put it on the heat right away.

0:06:56.260,0:06:57.520
# 放到這個鍋子上來
Let me put it onto the stand.

0:07:02.880,0:07:04.340
# 把它們剁成三塊
I've cut them into three pieces.

0:07:05.080,0:07:05.780
# 把它放在這裡
Let me put it here.

0:07:06.020,0:07:07.500
# 誒  剛剛好  可以蓋得住
Eh? Perfect! It's just right!

0:07:07.980,0:07:09.080
# 我先把火升起來
Let me set the fire first.

0:07:28.340,0:07:29.100
# 誒呦喂
Yeyowei!

0:07:32.540,0:07:33.040
# 可以
Alright!

0:07:38.860,0:07:40.220
# 塞一點東西進去
Let me stuff something inside.

0:07:40.920,0:07:41.480
# 要不然
Otherwise,

0:07:42.100,0:07:43.020
# 不然火燒不著
otherwise it won't burn.

0:07:46.100,0:07:47.040
# 煙燻雞
Smoked chicken

0:07:52.320,0:07:53.420
# 你看這個(鐵皮)石斛  (註︰我不理會鐵皮了)
Have a look at the shi hu!

0:07:54.640,0:07:56.080
# 上次去兄弟家摘的
These were picked from my buddy's place.

0:07:56.860,0:07:58.280
# 洗一下  把它放下去
Let me wash it, and then put it in.

0:08:13.120,0:08:16.200
# 我把這個生薑跟那個(鐵皮)石斛放下去
I'll put in the ginger, together with the shi hu,

0:08:16.460,0:08:17.240
# 再加點鹽
and also some salt.

0:08:23.200,0:08:24.900
# 誒呀  香哦
Yeya! It smells great!

0:08:25.180,0:08:27.140
# 把這個(鐵皮)石斛放在這旁邊
I put the shi hu on the two side,

0:08:28.760,0:08:29.660
# 放在中間
and in the middle.

0:08:34.340,0:08:35.200
# 再把這個生薑
And then the ginger...

0:08:37.040,0:08:38.700
# 先中間 後兩邊
Middle first, followed by two sides

0:08:44.720,0:08:46.340
# 這個鹽要先放下去哦
The salt needs to be put first.

0:08:46.920,0:08:49.920
# 因為比較大一塊  大塊的那個  雞肉
Cuz the pieces are big, big pieces of, you know, chicken,

0:08:50.160,0:08:52.740
# 所以先放鹽它就  有助於
putting the salt first can enhance,

0:08:53.600,0:08:54.700
# 全身吸收
thorough absorption.

0:09:01.140,0:09:01.640
# 好啦
Alright!

0:09:02.620,0:09:03.420
# 再加點下去
Why not more?

0:09:04.680,0:09:05.180
# 夠啦
Enough

0:09:09.040,0:09:10.060
# 再加它蓋起來
Then cover it up.

0:09:21.320,0:09:22.080
# 看一下
Have a look

0:09:22.960,0:09:23.700
# 哇
Wa!

0:09:25.180,0:09:26.160
# 好香啊
It smells so good!

0:09:27.340,0:09:30.160
# 加點水  這水都快沒啦  要麼再煮一鍋水下去
More water, it's drying out. Shall I boil one more pot of water?

0:09:37.500,0:09:38.240
# 加點水
Refill some water.

0:09:47.360,0:09:49.680
# 看來它要找貪吃古玩去啦 (註︰「貪吃古」是苏洋對跃金的稱呼)
I think she's going to have some fun with Greedy Eater.

0:09:54.780,0:09:57.080
# 誒呀 來  這只棕色的小狗
Yeya! C'mon! This is a brown puppy.

0:09:57.640,0:09:58.920
# 它現在好瘦啊
She's now so skinny.

0:10:01.100,0:10:02.160
# 這母狗辛苦啦
This mother must have had a hard time.

0:10:03.200,0:10:04.180
# 你去旁邊玩吧
Go and enjoy yourself over there.

0:10:04.880,0:10:06.280
# 誒呀  好多狗啊
Yeeya! A lot of dogs

0:10:07.120,0:10:09.660
# 誒呀  這隻狗你還是這麼胖
Yeeya! This dog, you're still that chubby!

0:10:10.300,0:10:13.900
# 誒呀  這小  這小狗是蠻聽話的  別走
Yeeya! This pup, this puppy is rather nice. Don't run away!

0:10:14.980,0:10:17.380
# 這麼聽話的小狗  不要走  來
What a good puppy! Stay here! C'mon!

0:10:17.540,0:10:18.720
# 我幫你鬆鬆毛
Let me give you a massage.

0:10:28.880,0:10:29.820
# 你看現在熟了
Look! It's done now!

0:10:31.620,0:10:32.940
# 喂呀  這個雞腿
Weiya! This chicken leg...

0:10:33.580,0:10:34.760
# 看下  這個大一點
Let me see. This one is larger.

0:10:35.320,0:10:36.020
# 我吃這個
I'll take this one.

0:10:40.100,0:10:42.220
# 那麼大 太燙啦
It's giant! Too hot

0:10:46.860,0:10:47.840
# 哇  可以呦
Wa! It's not bad.

0:10:48.180,0:10:48.940
# 這個味道
I mean the taste.

0:10:53.820,0:10:55.620
# 嘿  走開  等下再吃
Hey! Go 'way! It's not yet your turn.

0:10:56.960,0:10:57.480
# 走燙
Really hot!

0:11:08.360,0:11:09.880
# 很有嚼勁  剛剛好
It's rather chewy. Perfect!

0:11:10.160,0:11:10.780
# 又不爛
And it's not too soft.

0:11:15.720,0:11:16.580
# 就是大了一點
It's just a little bit too big.

0:11:24.560,0:11:26.460
# 哇  很香啊  這個
Wa! It smells really good!

0:11:27.500,0:11:28.280
# 還有這個
And also this part,

0:11:30.140,0:11:30.920
# 也有點味道
It's quite flavourful too.

0:11:32.700,0:11:36.620
# 就額  這個  鉄皮石斛  也有一點這個味道
And eh, you know, the shi hu, is also quite flavourful.

0:11:37.980,0:11:41.660
# 就是鐵皮石斛的味道跟雞肉的味道  融洽在一起 (註︰想保留一個這個「融洽」的誤用)
It's like, the flavour of shi hu is harmonized with that of the chicken.

0:11:57.520,0:11:59.020
# 這個是大公雞來的哦
It's a giant rooster, you know.

0:12:00.440,0:12:01.880
# 這個皮心較有嚼勁的
So its skin is rather chewy.

0:12:02.740,0:12:03.800
# 不會像母雞一樣
It's very different from a hen's skin,

0:12:04.660,0:12:06.180
# 一燉就爛掉啦  這個不會
which gets too soft as soon as it's heated. But a rooster's don't.

0:12:09.260,0:12:10.480
# 它肉還較糯一點
Its meat is a bit mushy.

0:12:13.340,0:12:15.100
# 應該養了一年多的公雞  這個
I think this rooster is at least an year old.

0:12:17.900,0:12:19.280
# 嗯 這肉還蠻好吃的哦
Um! The meat is rather tasty.

0:12:24.840,0:12:25.800
# 這肉比較結實哦
The texture is rather firm, isn't it?

0:12:28.660,0:12:30.100
# 那麼大的腿
What an enormous leg!

0:12:37.720,0:12:38.540
# 要不要啊
Do you want some?
#https://youtu.be/3o_GqxEfFBM

#华农兄弟：看一下摄影小哥种的铁皮石斛，顺便摘点来炖大公鸡
#Huanong Borhters: We take a look at Mr Camerman's shu hu. I pick some and stew with a giant rooster.

0:12:42.200,0:12:45.800
# 你看後面那條胖狗  口水都流出來了
Have a look at the big fat dog behind you. He's already drooling.

0:12:48.320,0:12:50.200
# 就條這  口水都流出來弓
I mean this one. He's drooling.

0:12:51.940,0:12:53.020
# 口水都流出來了
Yea, he's drooling.

0:13:10.160,0:13:10.960
# 等一下來啊
It'll be your turn very soon.

0:13:11.480,0:13:12.440
# 讓我吃先
But let me finish first.

0:13:18.560,0:13:19.620
# 這個(鐵皮)石斛
This shi hu,

0:13:20.780,0:13:21.580
# 這(鐵皮)石斛
this shi hu,

0:13:22.120,0:13:22.860
# 也可以吃的
is also edible.

0:13:26.740,0:13:27.980
# 嗯  好香
Um! It smells really good!

0:13:31.000,0:13:33.360
# 不過有點老  有點  糯糯的
But it's a bit old, a bit, mushy.

0:13:38.720,0:13:41.380
# 好啦  今天的視頻到這裡啦
Alright! The video ends here.

0:13:42.700,0:13:43.680
# 我吃肉啦
It's my meal time now.
