### ISSUE TITLE
[华农兄弟] 抓狗子送大姑 - https://youtu.be/u_R5mllcDSE

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#823]
https://youtu.be/u_R5mllcDSE
<p>&#35270;&#39057;&#21457;&#24067;&#20110; March 21, 2020 at 11:55AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/u_R5mllcDSE

#华农兄弟：下雨天，狗子全围在门口，抓2只送给大姑家养
#Huanong Brothers: It's raining. The dogs are all gathering in front of my door. I catch two for my aunt,

0:00:00.000,0:00:02.660
# 你看 下雨  全部都圍在這裡
Look! It's raining and they're all gathering here.

0:00:05.000,0:00:05.760
# 笑一下
Show me your smile!

0:00:06.480,0:00:09.160
# 那狗會笑的  它不笑了現在  快點笑一下
That dog smiles a lot, but he's not smiling now. C'mon! Show me your smile!

0:00:09.720,0:00:11.120
# 笑一下我給塊肉給你吃
Show me your smile and you can get a piece of meat from me.

0:00:15.800,0:00:17.920
# 你看  它看著我吃辣條哦
Look! She's watching me eating latiao (lit: spicy strip, a kind of snack)

0:00:18.280,0:00:19.100
# 要不要辣條
Do you want latiao?

0:00:20.500,0:00:21.340
# 很辣的哦
It's really spicy, you know.

0:00:22.260,0:00:23.100
# 你不吃的
You won't like it.

0:00:24.760,0:00:25.880
# 你快要嗎  小狗
And you want it too? Puppy

0:00:26.740,0:00:29.420
# 現在下雨啊  那狗都是  在這邊上  (註︰這個「邊」不知怎釋，就是們前的一級而已)
It's raining now. The dogs are, all here on this step.

0:00:29.920,0:00:31.000
# 一地都是狗
Dogs are everywhere.

0:00:32.860,0:00:35.340
# 現在小狗都送的差不多啦  還有七八條
Now I've given out almost all puppies, except seven or eight of them.

0:00:36.180,0:00:37.920
# 等下我又送兩條給我的那個
Later today I'll give another two to my, you know,

0:00:38.800,0:00:39.820
# 給我親戚
to my relatives.

0:00:41.600,0:00:43.520
# 放在它家養  把它養大
They'll keep the puppies, and raise them up.

0:00:46.680,0:00:48.600
# 送一條公的跟一條母的給他們
I'm gonna give them a boy and a girl.

0:00:50.740,0:00:51.580
# 太多啦
Here are too many dogs.

0:00:52.100,0:00:52.640
# 小黑
Blacky!

0:00:53.540,0:00:54.400
# 哪個是小黑
Which one is Blacky?

0:00:55.320,0:00:56.380
# 小黑肯定跟到我
Blacky must have gone to my,

0:00:56.820,0:00:57.600
# 我老家去啦
to my home.

0:00:58.320,0:00:59.120
# 我老家有點
At my home, there's some,

0:00:59.760,0:01:00.620
# 有點那個剩飯
some sort of leftover.

0:01:01.200,0:01:02.640
# 它跑去  跑回去吃啦
So she's, she's having a feast there.

0:01:05.540,0:01:06.080
# 嗯
Um!

0:01:07.060,0:01:08.940
# 嗯 昨天跑回來那狗嘞
Um? Where's the dogs that came back yesterday?

0:01:10.320,0:01:12.720
# 昨天流浪了一個禮拜的那狗不知道跑哪裡去了  (註︰這句他說得有點亂)
The dog had been straying for a week. He came back yesterday. But he's gone again.

0:01:14.220,0:01:16.740
# 一個禮拜都不見它  今天居然回來啦  (註︰那究竟是昨天還是今天回來的....)
He has disappeared for one whole week. But he's back today.

0:01:19.320,0:01:21.040
# 現在 餓的它皮包骨一樣
Now, he was starving and he's now like a skeleton.

0:01:21.800,0:01:22.960
# 誒  走到哪裡去啦
Eh? Where is he now?

0:01:26.300,0:01:27.160
# 小黑過來  (註︰這其實不是小黑)
Come here, Little Black!

0:01:30.200,0:01:31.000
# 你看就這個
Look! It's this one.

0:01:32.060,0:01:34.700
# 這狗  你看  瘦的都不成樣子了
This dog, look! He's now ridiculously skinny.

0:01:36.280,0:01:37.680
# 離家出走了一個禮拜
He has run away for a week.

0:01:39.020,0:01:39.900
# 現在才回來
And now he's back, after one whole week.

0:01:40.300,0:01:41.320
# 看都變色了
His coat has already discoloured.

0:01:42.100,0:01:43.400
# 你看  是不是  (註︰是不是甚麼呢....)
Look! Am I right?

0:01:43.640,0:01:45.060
# 這隻跟了我 一直跟著我的
This one has been with me... It's always with me.

0:01:45.760,0:01:47.220
# 這個就不聽話  跑到外面去
This one is naughty. He ran outside,

0:01:47.660,0:01:48.580
# 跟豬跑了
with the pigs,

0:01:49.400,0:01:51.480
# 跟那大公豬  上山上去玩
with the big boar. They had fun on the hill.

0:01:52.600,0:01:55.160
# 你看  現在都回來了發抖  再不回來的話可能就
Look! He's now back and is trembling. If he stays any longer outside,

0:01:55.580,0:01:56.080
# 會
then,

0:01:57.160,0:01:58.560
# 永遠永遠都回不來了
he might never, never be able to come back.

0:02:00.280,0:02:01.640
# 剛剛吃飽  你看
He has just had a big meal. Look!

0:02:02.480,0:02:03.720
# 肚子都吃那麼大了
His stomach is getting that big now!

0:02:05.660,0:02:08.180
# 你敢不敢跑啦  你跟著豬跑  是不是
Dare you run away again? You ran out with the pigs, didn't you?

0:02:08.560,0:02:09.820
# 在家都不好好待著
You didn't stay at home like a good boy.

0:02:09.960,0:02:10.760
# 還跟它走
But you ran away with the boar.

0:02:10.980,0:02:11.480
# 你看
Look!

0:02:12.000,0:02:13.740
# 餓的不現在剩下皮包骨啦
You were starving and you're now not so much different from a skeleton.

0:02:14.920,0:02:15.760
# 現在腳都發抖
Now his legs are trembling.

0:02:17.120,0:02:18.540
# 沒事的  過兩天就好了
No worries. He'll fine in a couple of days.

0:02:20.100,0:02:22.280
# 那公豬也不知道跑哪裡去了  公豬
The boar has run away to somewhere only god knows, the boar.

0:02:24.600,0:02:25.920
# 這裡還受傷了  這裡
Here's even a wound, here.

0:02:26.400,0:02:28.140
# 我今天給它摘了  摘了點葯水
I've put on some, some medication on him today.

0:02:28.240,0:02:29.800
# 給了點碘伏給它擦了下  (註︰是他自己說拿給狗的，我照譯而已)
I gave him some povidone-iodine.

0:02:31.240,0:02:32.140
# 很快就會好了
He'll get well very soon.

0:02:32.960,0:02:35.060
# 這就是你看  這個跟  跟著我的狗
And this is, look! This is the, the dog which  has always been with me.

0:02:36.640,0:02:37.340
# 是不是
Am I right?

0:02:38.240,0:02:40.640
# 雖然  雖 雖然伙食不是很好
Although, al, although you don't have any excess here,

0:02:41.700,0:02:44.060
# 但是溫飽還是沒問題的  哦
but you never starve, right?

0:02:49.860,0:02:50.840
# 現在好肥了
You're already very fat.

0:02:51.940,0:02:53.480
# 不能吃 少吃一點  知不知道
You can't eat, eat less! Got it?

0:02:54.020,0:02:55.240
# 太肥了不好看的
You're not cute anymore if you get too fat.

0:03:02.040,0:03:03.480
# 好好摸  它這個狗頭
It feels really great, touching his dog head.

0:03:07.640,0:03:11.460
# 現在的牙齒都長得好利啦  就它最兇  專門欺負小狗
Now his teeth are really sharp. He's the most fierce and always bullies other puppies.

0:03:12.980,0:03:13.880
# 是不是
Am I right?

0:03:16.040,0:03:17.140
# 最兇的就是你
You're the most fierce.

0:03:19.200,0:03:20.800
# 笑  笑
Smile! Smile!

0:03:26.060,0:03:27.080
# 它不笑
He doesn't smile.

0:03:28.680,0:03:29.820
# 笑不出來是不是
You just can't smile, right?

0:03:31.480,0:03:32.580
# 要不要骨頭吃
Do you want some bones?

0:03:33.560,0:03:35.920
# 昨天  昨天我搞了一大盆骨頭給它們吃
Yesterday, yesterday I gave them a huge plate of bones.

0:03:36.480,0:03:37.140
# 一口氣
Immediately,

0:03:37.860,0:03:39.300
# 一分鐘都不用  全部吃完啦
in less than a minute, all were gone.

0:03:42.160,0:03:43.700
# 這個毛  太多啦
His fur, he has too much.

0:03:44.360,0:03:45.700
# 一身的毛都崩起來
His fur is curling up all over the body.

0:03:47.180,0:03:50.060
# 幹嘛  上次我都  打過你  你都不聽話
What do you want? Last time I, I beat you, cuz you were naughty.

0:03:50.260,0:03:52.100
# 去咬人家的雞  是不是
You bit other people's chickens, didn't you?

0:03:52.600,0:03:54.740
# 你去咬人家被我打了一次  現在又那麼
You bit others and I beat you. And now you're so,

0:03:55.380,0:03:55.980
# 還那麼
you're still so,

0:03:56.680,0:03:58.280
# 還那麼喜歡跟我黏在一起
you still enjoy that much getting attached to me.

0:03:59.300,0:04:00.660
# 不聽話就要打  知不知道
You deserved it cuz you were naughty. Got it?

0:04:04.260,0:04:05.240
# 你看  它現在
Look! Now she,

0:04:05.560,0:04:06.200
# 乖的很
she's such a good girl.

0:04:06.860,0:04:08.480
# 可能害怕我 我鞭它
Perhaps she's scared, that I might flog her.

0:04:09.280,0:04:10.820
# 所以它一直  一直在
So she's now trying, trying to,

0:04:13.240,0:04:14.280
# 靠近我  是不是
get close to me, am I right?

0:04:15.520,0:04:17.280
# 是不是  肯定  它肯定想靠近我
Right? Surely, surely she wants to get close to me,

0:04:18.040,0:04:19.460
# 跟我  和好
and reconcile with me.

0:04:20.920,0:04:22.200
# 這樣才是  好狗
That's exactly how a, good dog, should be.

0:04:24.500,0:04:26.540
# 對主人那麼忠誠  是不是
You're so loyal to your master, aren't you?

0:04:26.880,0:04:28.240
# 不要去咬人家的雞  知不知道
You shouldn't bite their chickens. Got it?

0:04:28.320,0:04:30.140
# 咬人家的雞的話  人家會罵的
You would be scolded if you do.

0:04:31.140,0:04:32.960
# 人家養雞也不容易呀
Not to say that raising the chickens is never an easy task.

0:04:34.660,0:04:35.940
# 誒  是不是你
Eh? Is that you?

0:04:36.500,0:04:37.600
# 你也跟著去了  是不是
You followed her, didn't you?

0:04:38.720,0:04:40.380
# 這個  這個腳都是白的
Her, her feet are white.

0:04:41.120,0:04:42.400
# 這裡也是白的 嘿嘿
She's also white here, hehe!

0:04:46.900,0:04:48.500
# 它們很喜歡我這樣拎著它
They like it so much when I'm holding them here.

0:04:54.000,0:04:56.260
# 還有一條  這個  小花狗
One more, this is, tinted puppy.

0:04:57.520,0:05:00.860
# 小花狗你給我過來  小花狗  就你不聽話  你看
Tinted, you come here, you tinted puppy. You're always the naughty one. Look!

0:05:01.420,0:05:02.300
# 就它不老實
He's never a good boy.

0:05:02.680,0:05:04.920
# 我不把它它就en~en~的叫
Whenever I hold him, he always yelps like "en~en~".

0:05:06.860,0:05:07.360
# 是不是
Am I right?

0:05:07.920,0:05:09.280
# 看它肚子  看到沒有  小肚子
Have a look at his tummy. See? Little tummy.

0:05:09.960,0:05:11.260
# 小肚腩  吃飽啦
Little belly. He's eaten a lot.

0:05:14.600,0:05:16.620
# 你看一下送哪 哪兩條給
Let me see which one, which two should I give,

0:05:17.020,0:05:18.020
# 給我家那個 
to my, you know,

0:05:18.720,0:05:19.680
#  我家姑姑
my aunt.

0:05:21.380,0:05:22.560
# 隨便挑兩條就好啦
Whichever two. It doesn't matter.

0:05:22.640,0:05:24.160
# 反正這條不送給別人
And this one is never on the list. I'm not giving him to anyone.

0:05:24.880,0:05:25.900
# 這條我就把你養大
This one, I'll bring you up.

0:05:25.940,0:05:26.460
# 誒呀
Eya!

0:05:27.520,0:05:28.020
# 你看
Look!

0:05:28.520,0:05:29.020
# 哦
Oh!

0:05:29.520,0:05:31.080
# 看  看能不能頂得住我
See, see if you can stand my weight.

0:05:31.640,0:05:32.720
# 我才九十斤
I'm only forty-five kilograms.

0:05:33.020,0:05:34.160
# 哼哼  騙它的
Hm hm, I'm just kidding.

0:05:35.120,0:05:35.780
# 誒
Ey!

0:05:36.960,0:05:40.220
# 不行  大瘦小了  我又不敢用力坐
No no. She's too weak and skinny. I dare not give her my full weight.

0:05:43.420,0:05:44.620
# 你怎麼那麼可愛
How can you be that cute?

0:05:45.100,0:05:46.840
# 我就不送你了啊 嘖
So I'm not giving you to anyone, okay?

0:05:47.140,0:05:49.280
# 送其它那幾條  隨便找兩條去
I'll choose from the others. Any two would be fine.

0:05:50.800,0:05:51.780
# 送兩條給他們
I'll give them two.

0:05:52.400,0:05:53.440
# 現在壓力大呀
Life is not easy these days.

0:05:53.600,0:05:56.000
# 養不起它們啦  要慢慢地把它送掉一些
I can't afford keeping them all. I need to give out some of them.

0:05:56.860,0:05:57.600
# 剩下的
And the rest,

0:05:58.380,0:05:59.120
# 剩下的就
the rest will be,

0:05:59.280,0:06:00.400
# 大狗就留下來吧
the big dogs will be staying here.

0:06:00.700,0:06:02.180
# 小狗 幾乎要把它送走
But puppies, almost all will be given out.

0:06:03.840,0:06:05.240
# 不然養不起呀  太多啦
Otherwise I can't afford. Here are too many dogs.

0:06:13.580,0:06:16.480
# 就是這一條  一條生了那麼多
It used to be just one dog. All other dogs came from her.

0:06:17.420,0:06:17.960
# 就它
Here she is.

0:06:19.260,0:06:19.780
# 你看
Look!

0:06:21.200,0:06:22.060
# 做奶奶咯
You're now a grandma.

0:06:27.880,0:06:30.260
# 好啦好啦好啦好啦  你們到外面玩啊
Alright, alright, alright, alright! Enjoy your time outside, okay?

0:06:30.260,0:06:31.540
# 這裡面不適合你們
You won't feel great here inside.

0:06:40.140,0:06:42.020
# 現在狗崽越來越少啦
Now, we have less and less puppies here.

0:06:43.220,0:06:44.700
# 我一條條把它送出去
I'm giving them out, one after the other.

0:06:45.540,0:06:46.220
# 不要那麼多
I don't need so many.

0:06:51.740,0:06:53.180
# 抓  抓都抓不住
I, I couldn't even touch it.

0:06:53.880,0:06:54.580
# 快點過來
Come here!

0:06:59.100,0:07:00.520
# (狗狗狗狗狗狗狗狗)  (註︰沒有原字幕)
Puppies, puppies, puppies!

0:07:00.820,0:07:01.320
# (狗)
Puppies!

0:07:02.660,0:07:03.200
# (狗)
Puppies!

0:07:08.980,0:07:10.160
# 想抓一條都抓不到了
I can't catch even one.

0:07:11.280,0:07:12.260
# 全部不願意去
They're not willing to leave.

0:07:12.700,0:07:13.600
# 這裡那麼好哇
Here is such a good place, isn't it?

0:07:14.760,0:07:16.680
# 沒辦法啊  養不起你們啦
I have no choice. I can't afford keeping you all.

0:07:17.880,0:07:19.340
# (狗狗狗狗狗狗狗狗)
Puppies, puppies, puppies

0:07:21.120,0:07:21.620
# (狗)
Puppies!

0:07:22.680,0:07:23.340
# (狗)
Puppies!

0:07:24.440,0:07:25.320
# 我偷襲它 
Let me attack from the back.

0:07:34.560,0:07:35.700
# 它咬人的
He bites!

0:07:36.380,0:07:37.280
# 那麼小就咬人
You're still a kid, but you bite!

0:07:37.860,0:07:39.400
# 這怎麼行  這麼兇
How can it be? You're so fierce.

0:07:43.140,0:07:44.500
# 嗯  這個個乖啦  (註︰這小狗是公的，但後面知道他一直以為這是母的，所以用"She")
Um! This is a very good girl.

0:07:45.380,0:07:46.940
# 走  帶你去玩
Let's go, and have some fun!

0:07:47.880,0:07:48.440
# 去不去
Are you going?

0:07:57.780,0:07:58.380
# 你看這個
Look! She's,

0:07:59.060,0:07:59.800
# 那麼大啦
already that big now.

0:08:00.880,0:08:01.780
# 把這個蓋起來
Let me cover it up.

0:08:02.240,0:08:03.420
# 蓋下它就跑不出來
Cover it up and then she can't run away.

0:08:03.840,0:08:04.500
# 還要抓一條
I need to catch one more.

0:08:04.800,0:08:05.300
# (狗)
Puppy!

0:08:19.660,0:08:20.460
# 都不肯
They don't want it!

0:08:21.580,0:08:23.300
# 這裡有一條  這  有一條黑的
Here's one. Here's, a black one.

0:08:25.800,0:08:26.900
# (狗狗)
Puppies, puppies!

0:08:27.820,0:08:28.460
# (狗)
Puppies!

0:08:40.460,0:08:40.960
# (狗)
Puppies!

0:08:43.780,0:08:45.000
# 那麼不聽話
So naughty!

0:10:12.560,0:10:13.320
# 上來了
He gets up!

0:11:03.700,0:11:05.820
# 你看  就抓了這兩條
Look! So I've caught these two.

0:11:06.500,0:11:07.260
# 抓這兩條
So I'll give these two,

0:11:08.240,0:11:09.280
# 送給我大姑家
to my aunt.

0:11:10.160,0:11:11.440
# 現在我們把它送上去
We're gonna send them there now.

0:11:12.200,0:11:13.440
# 現在都有十來斤啦
I think they're nearly ten kilograms now.

0:11:14.860,0:11:15.880
# 快養不起它們啦
They'll soon eat up all my money.

0:11:16.860,0:11:17.440
# 送掉
So, given them out!

0:11:17.680,0:11:18.360
# 一條條的送
One after the other!

0:11:21.220,0:11:21.980
# 不知道怎麼弄
But how can I make it?

0:11:23.000,0:11:23.820
# 有沒有蓋子
Is there a cover?

0:11:26.820,0:11:28.020
# 可以  反過來
Alright! Turn it over!

0:11:40.840,0:11:41.980
# 好兇呀  它們
They're so fierce!

0:11:42.840,0:11:44.260
# 把它  放進來
Put them, inside.

0:11:45.200,0:11:47.020
# 可以  這樣  這樣抬著
Alright! Then, then I can take it.

0:11:58.140,0:11:59.220
# 狗崽子 哈哈
Puppies, haha 

0:11:59.260,0:11:59.900
# 拿過去
Put them there

0:12:07.640,0:12:08.780
# 呃  出來
Eh! Come out!

0:12:09.220,0:12:10.560
# 這是你們的新家啦
This is your new home.

0:12:14.560,0:12:15.560
# 這條  這條很靚哦
This one, this one is beautiful, isn't it?

0:12:15.560,0:12:16.060
# 嗯
Yup!

0:12:18.840,0:12:19.580
# 吃了很飽啦
He's eaten a lot

0:12:19.740,0:12:20.660
# 兩條都是公狗嗎
Are they both boys?

0:12:21.100,0:12:21.780
# 不是吧
No, it shouldn't be.

0:12:21.780,0:12:22.280
# 看一下來
Let me check.

0:12:22.720,0:12:23.500
# 母狗吧  這條  
This is should be a girl, this one.

0:12:29.400,0:12:30.200
# 母狗還是公狗
Is it a girl or a boy?

0:12:31.780,0:12:33.040
# 跑雞窩裡面去了
She's getting into the roost.

0:12:35.900,0:12:36.740
# 母狗還是公狗
A girl or a boy?

0:12:48.580,0:12:51.600
# 你看  它們就住在這裡  這裡比那裡好多啦
Look! So they are staying here now. Here is much better than there.

0:12:52.700,0:12:53.640
# 乾淨多了
It's so much cleaner.

0:13:01.800,0:13:03.760
# 一下就很適應了這裡的環境
They've already get used to this place.

0:13:04.280,0:13:05.960
# 你看  不哭也不鬧
Not crying, nor yelping.

0:13:07.640,0:13:08.280
# 在這裡
They're looking for food,

0:13:09.320,0:13:10.220
# 找東西吃
here and there.

0:13:13.740,0:13:15.560
# 這要過段時間  不敢放哦
I dare not take them out. Perhaps later.

0:13:15.920,0:13:17.280
# 不能放  過兩天就可以啦
No, you shouldn't now. But it'll be fine in a couple of days.

0:13:18.720,0:13:20.520
# 你看  它在找東西吃了
Look! He's looking for food.

0:13:21.740,0:13:23.260
# 這個就是你他的新家啦
From now on, this is your new home.

0:13:25.340,0:13:27.300
# 嘖  你看  一看就是大戶人家
Look! I can tell immediately that this is a wealthy family.

0:13:29.180,0:13:30.300
# 牆都貼瓷板啦
They even have porcelain tiles on the wall.

0:13:40.320,0:13:41.400
# 一點都不陌生哦
It doesn't seem to be a new place to him at all.

0:13:44.880,0:13:46.360
# 好啦  我們準備回去啦
Alright! We're getting ready to go back.

0:13:47.880,0:13:49.100
# 下次我們再來看它們
We'll come again to see them next time.
