### ISSUE TITLE
[雪鱼] 姜母鸭早餐面 - https://www.youtube.com/watch?v=zJTV0viW5Ik&t=

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#826]
**视频链接**：https://www.youtube.com/watch?v=zJTV0viW5Ik&t=

视频时长：10‘50“ 发布日期：2020年3月21日

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厦门最好的姜母鸭+漳州奢华早餐面条，18盆卤味任选

简介
本期视频继续分享福建美食。在厦门同安隐藏着一家23年的盐鸭店，据说是厦门公认第一的盐鸭，来到这里正是上午，老板的伙计们正在将鸭子下入砂锅中，锅底是姜片，上部分是整只鸭子；一排排的砂锅很是壮观，足足摆了2间屋子，还有一间屋用来将鸭肉剪成大块，3间屋子都没有座位，一只姜母鸭66元，所有来的客人都必须打包带走吃！即使这样生意依然火爆！++第二家店是漳州的特色早餐卤面，18盆卤味摆一桌任选，猪皮、豆腐、猪脚、肉、卤蛋等等，早上吃这么一大碗，不长胖都没有道理！

字幕
1
00:00:01,650 --> 00:00:02,500
福建·厦门

2
00:00:05,841 --> 00:00:07,616
一炉炉的都是 鸭子

3
00:00:21,425 --> 00:00:22,925
盖上盖子   

4
00:00:27,975 --> 00:00:28,800
姜母鸭

5
00:00:30,700 --> 00:00:32,725
站在这个你都能闻到

6
00:00:32,800 --> 00:00:34,700
鸭油和姜片的这种混合香味

7
00:00:34,950 --> 00:00:37,000
感觉在这儿都要流口水了

8
00:00:38,250 --> 00:00:40,975
雪鱼今天来到的是一家做姜母鸭的熟食店

9
00:00:41,450 --> 00:00:44,500
来的正巧 他们正忙着炖鸭子

10
00:00:45,375 --> 00:00:48,475
走在附近 光这肉香 都能把我吸引过来

11
00:01:11,900 --> 00:01:14,000
这边是两间屋子

12
00:01:14,150 --> 00:01:16,150
都是用来做鸭子的

13
00:01:17,150 --> 00:01:19,100
好多

14
00:01:19,875 --> 00:01:21,700
别人卖鸭子都是一只只地卖

15
00:01:21,925 --> 00:01:24,450
在这里是一排排地卖 一轮轮地卖

16
00:01:24,950 --> 00:01:26,300
要是赶上逢年过节

17
00:01:26,500 --> 00:01:29,875
人不休息 炉子也甭想休息

18
00:01:29,875 --> 00:01:32,250
刚才小哥说 这边最忙的时候

19
00:01:32,250 --> 00:01:33,929
一天能够做七八百只鸭子

20
00:01:34,225 --> 00:01:36,900
我说是从早上 一直做到下午吗

21
00:01:37,025 --> 00:01:40,425
他说 通宵

22
00:01:40,425 --> 00:01:41,875
仔细看 你会发现

23
00:01:41,875 --> 00:01:43,852
做姜母鸭（盐鸭）的装置是特别的

24
00:01:44,100 --> 00:01:47,075
下面是炉火 中间有一层隔热的（盐）

25
00:01:47,075 --> 00:01:48,450
上面才是砂锅

26
00:01:50,000 --> 00:01:51,225
鸭子放进砂锅之前

27
00:01:51,300 --> 00:01:53,000
都是要进行提前腌制的

28
00:01:53,200 --> 00:01:56,650
然后才是一整只鸭子和姜母放在砂锅里

29
00:01:57,000 --> 00:02:00,125
盖上盖子 足足要炖一个多小时

30
00:02:59,150 --> 00:03:01,050
你好 帮我拿半只吧

31
00:03:01,325 --> 00:03:02,075
好

32
00:03:38,825 --> 00:03:43,350
透过袋子 你能隐隐约约看到鸭油和鸭汤

33
00:03:43,475 --> 00:03:48,175
这个时候 有碗米饭真的会很香

34
00:03:59,175 --> 00:04:02,925
看我的白米饭 配鸭肉来吃

35
00:04:03,700 --> 00:04:05,300
鸭子炖的时间很长了

36
00:04:05,400 --> 00:04:07,950
压在下面的姜片都被炖没型了

37
00:04:09,050 --> 00:04:10,500
肉呢 特别软烂

38
00:04:10,700 --> 00:04:13,700
鸭肉很容易从骨头上撕扯下来

39
00:04:18,225 --> 00:04:20,625
它这个鸭子吃起来 干香干香的

40
00:04:21,875 --> 00:04:24,125
吃的时候呢 米饭上还会粘些鸭油

41
00:04:24,425 --> 00:04:28,200
啊 真的是下饭神器

42
00:04:40,600 --> 00:04:41,900
福建·漳州

43
00:04:44,400 --> 00:04:46,175
咱们这是出来吃早餐

44
00:04:46,175 --> 00:04:47,425
但是在我的对面 我发现

45
00:04:47,425 --> 00:04:49,525
他们的夜场都没有散

46
00:05:06,825 --> 00:05:08,800
走了10多分钟 总算来到了卤面店

47
00:05:09,100 --> 00:05:10,798
我们现在要进去

48
00:05:10,798 --> 00:05:12,998
点一碗热气腾腾的面来吃

49
00:05:15,975 --> 00:05:17,200
知道为什么来这么早吗

50
00:05:17,325 --> 00:05:20,375
因为来得早 料多丰富

51
00:05:21,025 --> 00:05:23,375
想吃什么点什么

52
00:05:32,600 --> 00:05:34,275
在这儿吃吗

53
00:05:36,650 --> 00:05:37,975
豆芽 香菜要不要

54
00:05:39,225 --> 00:05:41,575
我这边刚说完 阿姨就揪了一把碱面

55
00:05:41,825 --> 00:05:43,700
放在开水当中 捞一下过水

56
00:05:45,175 --> 00:05:48,500
短短几秒钟 面条脱胎换骨

57
00:05:49,775 --> 00:05:50,825
做好的面

58
00:05:50,825 --> 00:05:53,525
浇上猪骨熬出来的浓郁的卤汁来调味

59
00:05:54,125 --> 00:05:56,475
再按自己的心意 选一些配菜

60
00:05:56,800 --> 00:06:00,050
真的会让这碗面 香上加香

61
00:06:00,525 --> 00:06:03,375
咔嚓 咔嚓

62
00:06:03,450 --> 00:06:05,525
咔嚓 咔嚓   

63
00:06:37,125 --> 00:06:39,650
卤煮  剪肉时候也是这样咔嚓咔嚓

64
00:06:43,500 --> 00:06:45,300
没有食物 刀也不停

65
00:07:29,575 --> 00:07:31,875
雪鱼的口味 让人捉摸不透

66
00:07:40,200 --> 00:07:42,025
它的面条也是这种碱水面

67
00:07:42,200 --> 00:07:43,975
就是很容易咬断

68
00:07:44,700 --> 00:07:48,275
吃面条的时候 还会顺带吃卤子

69
00:07:50,025 --> 00:07:51,550
它这个是

70
00:07:51,650 --> 00:07:52,475
咸的

71
00:07:53,775 --> 00:07:55,525
我们加了鱼丸 猪皮 豆腐

72
00:07:55,825 --> 00:07:58,475
这个是我专门要的鱼丸

73
00:08:01,300 --> 00:08:03,675
很喜欢吃鱼丸这种香中带甜的味道

74
00:08:04,675 --> 00:08:06,400
加了豆腐呢 主要是因为

75
00:08:06,400 --> 00:08:07,725
豆腐能吸收汤汁

76
00:08:07,825 --> 00:08:10,250
这样会让豆腐更饱满一些

77
00:08:11,450 --> 00:08:12,350
这一大早

78
00:08:12,425 --> 00:08:14,325
咱们这碗面加的料还是很丰富的

79
00:08:14,475 --> 00:08:17,025
但是和桌子上摆的料比起来

80
00:08:17,100 --> 00:08:19,075
可能只是它的几分之一了

81
00:08:19,375 --> 00:08:20,900
像大肠 炸肉这些

82
00:08:20,950 --> 00:08:22,600
也都是大家比较喜欢吃的

83
00:08:25,050 --> 00:08:27,025
我要猪皮最重要的一个原因就是

84
00:08:27,125 --> 00:08:29,850
它刚拿出来 看着让人很有食欲

85
00:08:40,075 --> 00:08:42,525
想一想刚才这碗面端上来的时候

86
00:08:42,550 --> 00:08:44,250
汤汁还是很浓郁的

87
00:08:44,400 --> 00:08:45,650
现在有点稀了

88
00:08:46,025 --> 00:08:47,225
但是依然挡不住

89
00:08:47,350 --> 00:08:49,850
它的这种海鲜的鲜甜的味道

90
00:08:59,550 --> 00:09:02,075
现在满屋子都是吸溜面条的声音

91
00:09:02,300 --> 00:09:03,825
但这个声音再大

92
00:09:03,825 --> 00:09:05,825
也抵不过旁边的阿姨拿剪刀

93
00:09:05,950 --> 00:09:09,650
咔嚓咔嚓咔嚓 剪这些材料的声音

94
00:09:09,650 --> 00:09:12,575
真是神奇的剪刀手

95
00:09:35,225 --> 00:09:37,775
你看早上来吃饭 大家都比较赶时间

96
00:09:37,775 --> 00:09:40,325
早一点的话 可能没有那么多人

97
00:09:40,400 --> 00:09:44,075
但是晚几分钟 人都会挤在早餐店的门口

98
00:09:45,250 --> 00:09:48,250
现在呢 上学的和上班的人渐渐多了

99
00:09:48,450 --> 00:09:51,025
早餐店也变得更加忙碌了

100
00:10:05,950 --> 00:10:07,525
伴着咔嚓咔嚓的声音

101
00:10:07,575 --> 00:10:09,475
我们也结束了今天的视频

102
00:10:10,075 --> 00:10:12,300
( ^_^ )/~~拜拜

103
00:10:15,975 --> 00:10:17,975
大早上起来就吃了20多块钱的饭

104
00:10:19,300 --> 00:10:21,250
是不是有点太奢侈了

105
00:10:23,100 --> 00:10:25,375
感觉中午也得少吃点吧 要不

106
00:10:25,600 --> 00:10:27,550
按这个速度长下去

107
00:10:27,875 --> 00:10:30,175
也重不少呢


```

**Comment by siyusun6918** [comment]
认领

**Comment by siyusun6918** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厦门最好的姜母鸭+漳州奢华早餐面条，18盆卤味任选
The best JiangMuYa (Ginger Duck Stew) in Xiamen and luxurious Zhangzhou breakfast noodles with eighteen pot-stewed dishes 

简介
本期视频继续分享福建美食。在厦门同安隐藏着一家23年的盐鸭店，据说是厦门公认第一的盐鸭，来到这里正是上午，老板的伙计们正在将鸭子下入砂锅中，锅底是姜片，上部分是整只鸭子；一排排的砂锅很是壮观，足足摆了2间屋子，还有一间屋用来将鸭肉剪成大块，3间屋子都没有座位，一只姜母鸭66元，所有来的客人都必须打包带走吃！即使这样生意依然火爆！++第二家店是漳州的特色早餐卤面，18盆卤味摆一桌任选，猪皮、豆腐、猪脚、肉、卤蛋等等，早上吃这么一大碗，不长胖都没有道理！

Continuing sharing Fujian cuisine. There’s a salt duck restaurant with 23 years of history hidden in Tongan, Xiamen. It is said that they have the best salt duck in the whole Xiamen area. I arrived at brunch hours, just as the cooks dumping the ducks into the casserole. The bottom of the casseroles was filled with sliced gingers and the upper part of the casserole contained whole ducks. The lined casseroles filled two rooms. There’s another room used to dismembering the cooked ducks into pieces. No seats can be found in any of the three rooms. The ginger duck stew was sold at 66 yuan per portion and the guests can only order carry-outs. But still, the restaurant is always filled with customers waiting for a bite of the duck. 
The second restaurant serves special breakfast heavy-grave noodles with eighteen kinds of pot-stewed sides to add as you like --- pig skins, tofu, pig feet, meat, eggs, etc. With a big bowl of noodles every morning, there’s no chance to not get fat.

字幕
1
00:00:01,650 --> 00:00:02,500
福建·厦门
Fujian, Xiamen

2
00:00:05,841 --> 00:00:07,616
一炉炉的都是 鸭子
Look at the casseroles! These are all ducks. 

3
00:00:21,425 --> 00:00:22,925
盖上盖子  
Close the lids

4
00:00:27,975 --> 00:00:28,800
姜母鸭
Jiangmu Ya (Ginger Duck Stew)

5
00:00:30,700 --> 00:00:32,725
站在这个你都能闻到
You can even smell it over here

6
00:00:32,800 --> 00:00:34,700
鸭油和姜片的这种混合香味
The mixed aroma of duck oil and sliced ginger

7
00:00:34,950 --> 00:00:37,000
感觉在这儿都要流口水了
I feel that I’m gonna drool myself here

8
00:00:38,250 --> 00:00:40,975
雪鱼今天来到的是一家做姜母鸭的熟食店
Today I’m in a deli that mainly serves Jiangmu duck.

9
00:00:41,450 --> 00:00:44,500
来的正巧 他们正忙着炖鸭子
Just in time, they’re busy making duck stews.

10
00:00:45,375 --> 00:00:48,475
走在附近 光这肉香 都能把我吸引过来
Even just walking by, I can be drawn here by the smell of the meat.

11
00:01:11,900 --> 00:01:14,000
这边是两间屋子
The two rooms here

12
00:01:14,150 --> 00:01:16,150
都是用来做鸭子的
are all used to make duck stews

13
00:01:17,150 --> 00:01:19,100
好多
There are so many of them!

14
00:01:19,875 --> 00:01:21,700
别人卖鸭子都是一只只地卖
Others sell duck one at a time

15
00:01:21,925 --> 00:01:24,450
在这里是一排排地卖 一轮轮地卖
They sell ducks by rounds here

16
00:01:24,950 --> 00:01:26,300
要是赶上逢年过节
If it’s the holidays

17
00:01:26,500 --> 00:01:29,875
人不休息 炉子也甭想休息
cooks can’t rest, so as the casseroles

18
00:01:29,875 --> 00:01:32,250
刚才小哥说 这边最忙的时候
The cook just told me, the busiest time here

19
00:01:32,250 --> 00:01:33,929
一天能够做七八百只鸭子
they cooked seven or eight hundred ducks in a day

20
00:01:34,225 --> 00:01:36,900
我说是从早上 一直做到下午吗
I asked him did they cooked a whole day from morning to afternoon

21
00:01:37,025 --> 00:01:40,425
他说 通宵
He said they continued cooking overnight

22
00:01:40,425 --> 00:01:41,875
仔细看 你会发现
If you look closely you’ll find that

23
00:01:41,875 --> 00:01:43,852
做姜母鸭（盐鸭）的装置是特别的
The equipment used to cook the Jiangmu Ya(Ginger duck stew) or salt duck is special

24
00:01:44,100 --> 00:01:47,075
下面是炉火 中间有一层隔热的（盐）
There’s a layer of salt used to prevent direct contact with fire in between of the fire 

25
00:01:47,075 --> 00:01:48,450
上面才是砂锅
and the casseroles

26
00:01:50,000 --> 00:01:51,225
鸭子放进砂锅之前
Before putting into the casseroles

27
00:01:51,300 --> 00:01:53,000
都是要进行提前腌制的
the ducks have to be marinated

28
00:01:53,200 --> 00:01:56,650
然后才是一整只鸭子和姜母放在砂锅里
then they were put into the casseroles with the gingers

29
00:01:57,000 --> 00:02:00,125
盖上盖子 足足要炖一个多小时
They are going to be stewed for an hour with the lid closed.

30
00:02:59,150 --> 00:03:01,050
你好 帮我拿半只吧
Hi! Can I have half of the duck?

31
00:03:01,325 --> 00:03:02,075
好
Sure.

32
00:03:38,825 --> 00:03:43,350
透过袋子 你能隐隐约约看到鸭油和鸭汤
You can vaguely see the duck oil and soup through the plastic bag

33
00:03:43,475 --> 00:03:48,175
这个时候 有碗米饭真的会很香
It will be very nice to have a bowl of rice with it

34
00:03:59,175 --> 00:04:02,925
看我的白米饭 配鸭肉来吃
Look at my white rice. I’m going to eat it with the duck

35
00:04:03,700 --> 00:04:05,300
鸭子炖的时间很长了
The duck has been stewed for a very long time

36
00:04:05,400 --> 00:04:07,950
压在下面的姜片都被炖没型了
The ginger slices underneath have stewed a part 

37
00:04:09,050 --> 00:04:10,500
肉呢 特别软烂
Meat is really soft 

38
00:04:10,700 --> 00:04:13,700
鸭肉很容易从骨头上撕扯下来
It’s really easy to sperate duck meat from the bones

39
00:04:18,225 --> 00:04:20,625
它这个鸭子吃起来 干香干香的
This duck is cooked thoroughly with the oils out on the surface, and tastes very nice! 

40
00:04:21,875 --> 00:04:24,125
吃的时候呢 米饭上还会粘些鸭油
The rice has duck oil on it when you eat it

41
00:04:24,425 --> 00:04:28,200
啊 真的是下饭神器
OMG, it’s so good when eating with rice.

42
00:04:40,600 --> 00:04:41,900
福建·漳州
Zhangzhou, Fujian,

43
00:04:44,400 --> 00:04:46,175
咱们这是出来吃早餐
We are here to eat breakfast

44
00:04:46,175 --> 00:04:47,425
但是在我的对面 我发现
But I found out that across the street

45
00:04:47,425 --> 00:04:49,525
他们的夜场都没有散
They are still continuing their nightlife.

46
00:05:06,825 --> 00:05:08,800
走了10多分钟 总算来到了卤面店
Over 10 minutes walking, We’ve finally arrived at the heavy-gravy noodle restaurant 

47
00:05:09,100 --> 00:05:10,798
我们现在要进去
We are going in now

48
00:05:10,798 --> 00:05:12,998
点一碗热气腾腾的面来吃
to order a bowl of hot noodle 

49
00:05:15,975 --> 00:05:17,200
知道为什么来这么早吗
Do you know why we are here so early?

50
00:05:17,325 --> 00:05:20,375
因为来得早 料多丰富
Because if you come early, there will be more choices of sides

51
00:05:21,025 --> 00:05:23,375
想吃什么点什么
You can order whatever you want 

52
00:05:32,600 --> 00:05:34,275
在这儿吃吗
For here?

53
00:05:36,650 --> 00:05:37,975
豆芽 香菜要不要
Do you want bean sprouts and cilantro 

54
00:05:39,225 --> 00:05:41,575
我这边刚说完 阿姨就揪了一把碱面
She grabs a handful of base noodle just as I’m finishing the sentence

55
00:05:41,825 --> 00:05:43,700
放在开水当中 捞一下过水
Blanch in boiling water 

56
00:05:45,175 --> 00:05:48,500
短短几秒钟 面条脱胎换骨
Just for a few seconds, the noodles are transformed 

57
00:05:49,775 --> 00:05:50,825
做好的面
Cooked noodles

58
00:05:50,825 --> 00:05:53,525
浇上猪骨熬出来的浓郁的卤汁来调味
Pour the heavy-gravy which was decocted from pork bones

59
00:05:54,125 --> 00:05:56,475
再按自己的心意 选一些配菜
Then choose the sides as you want 

60
00:05:56,800 --> 00:06:00,050
真的会让这碗面 香上加香
It will really improve the flavor of the noodles

61
00:06:00,525 --> 00:06:03,375
咔嚓 咔嚓
(scissors chopping)

62
00:06:03,450 --> 00:06:05,525
咔嚓 咔嚓   
(still chopping)

63
00:06:37,125 --> 00:06:39,650
卤煮  剪肉时候也是这样咔嚓咔嚓
Pot-stewed meat are also chopped like this 

64
00:06:43,500 --> 00:06:45,300
没有食物 刀也不停
The chopping never stops 

65
00:07:29,575 --> 00:07:31,875
雪鱼的口味 让人捉摸不透
My taste is a mystery 

66
00:07:40,200 --> 00:07:42,025
它的面条也是这种碱水面
This noodle is also base noodle


67
00:07:42,200 --> 00:07:43,975
就是很容易咬断
It’s very easy to bite apart

68
00:07:44,700 --> 00:07:48,275
吃面条的时候 还会顺带吃卤子
I’m also eating the sides while eating the noodles

69
00:07:50,025 --> 00:07:51,550
它这个是
How does it taste like?

70
00:07:51,650 --> 00:07:52,475
咸的
salty

71
00:07:53,775 --> 00:07:55,525
我们加了鱼丸 猪皮 豆腐
We added fish ball, pigskin, and tofu
72
00:07:55,825 --> 00:07:58,475
这个是我专门要的鱼丸
This fishball is special order by me

73
00:08:01,300 --> 00:08:03,675
很喜欢吃鱼丸这种香中带甜的味道
I like the salty taste with sweetness

74
00:08:04,675 --> 00:08:06,400
加了豆腐呢 主要是因为
I added tofu mainly because

75
00:08:06,400 --> 00:08:07,725
豆腐能吸收汤汁
Tofu can absorb the soup

76
00:08:07,825 --> 00:08:10,250
这样会让豆腐更饱满一些
This will make the tofu more supple

77
00:08:11,450 --> 00:08:12,350
这一大早
In the early

78
00:08:12,425 --> 00:08:14,325
咱们这碗面加的料还是很丰富的
We added too many sides in the noodle

79
00:08:14,475 --> 00:08:17,025
但是和桌子上摆的料比起来
But comparing with the sides on the table

80
00:08:17,100 --> 00:08:19,075
可能只是它的几分之一了
it’s only a portion of them

81
00:08:19,375 --> 00:08:20,900
像大肠 炸肉这些
Like pig intestine and fired meat

82
00:08:20,950 --> 00:08:22,600
也都是大家比较喜欢吃的
they’re faviortes for everyone

83
00:08:25,050 --> 00:08:27,025
我要猪皮最重要的一个原因就是
The most important reason that I choose pigskin is that

84
00:08:27,125 --> 00:08:29,850
它刚拿出来 看着让人很有食欲
It’s freshly cooked, looks very attractive 

85
00:08:40,075 --> 00:08:42,525
想一想刚才这碗面端上来的时候
Think back to the noodles when it’s just served

86
00:08:42,550 --> 00:08:44,250
汤汁还是很浓郁的
The soup was very heavy

87
00:08:44,400 --> 00:08:45,650
现在有点稀了
Now it’s a little bit thinner

88
00:08:46,025 --> 00:08:47,225
但是依然挡不住
but still

89
00:08:47,350 --> 00:08:49,850
它的这种海鲜的鲜甜的味道
The umami and sweetness of the seafood are still here

90
00:08:59,550 --> 00:09:02,075
现在满屋子都是吸溜面条的声音
Now the whole room is filled with the sounds of people eating the noodles

91
00:09:02,300 --> 00:09:03,825
但这个声音再大
But no matter how big the sounds are

92
00:09:03,825 --> 00:09:05,825
也抵不过旁边的阿姨拿剪刀
they are never gonna cover the chopping sounds of the scissors

93
00:09:05,950 --> 00:09:09,650
咔嚓咔嚓咔嚓 剪这些材料的声音
the chopping of the sides

94
00:09:09,650 --> 00:09:12,575
真是神奇的剪刀手
Her movements of the scissors are amazing

95
00:09:35,225 --> 00:09:37,775
你看早上来吃饭 大家都比较赶时间
When eating in the morning, everyone is kind of short on time

96
00:09:37,775 --> 00:09:40,325
早一点的话 可能没有那么多人
If we come earlier, there won’t be this many people

97
00:09:40,400 --> 00:09:44,075
但是晚几分钟 人都会挤在早餐店的门口
But just a few minutes late, everyone will be crowded at the entrance of the restaurant

98
00:09:45,250 --> 00:09:48,250
现在呢 上学的和上班的人渐渐多了
Now, more and more students and people who are heading to work are here

99
00:09:48,450 --> 00:09:51,025
早餐店也变得更加忙碌了
the restraunt is getting busier

100
00:10:05,950 --> 00:10:07,525
伴着咔嚓咔嚓的声音
with the chopping sound

101
00:10:07,575 --> 00:10:09,475
我们也结束了今天的视频
We are putting this video to an end

102
00:10:10,075 --> 00:10:12,300
( ^_^ )/~~拜拜
bye bye

103
00:10:15,975 --> 00:10:17,975
大早上起来就吃了20多块钱的饭
Spent 20 yuan for breakfast in the early morning

104
00:10:19,300 --> 00:10:21,250
是不是有点太奢侈了
Is it too luxrious?

105
00:10:23,100 --> 00:10:25,375
感觉中午也得少吃点吧 要不
Maybe eat less for lunch, or else

106
00:10:25,600 --> 00:10:27,550
按这个速度长下去
growing in this speed

107
00:10:27,875 --> 00:10:30,175
也重不少呢
I’m gonna put up with too much weight
