### ISSUE TITLE
【美食作家王刚】小锅翻锅 - https://youtu.be/MJEn4mmZEDQ

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#839]
**视频链接**：https://youtu.be/MJEn4mmZEDQ

视频时长 3:13，预计发布时间为北京时间3月26日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！
# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：如何练习“小锅翻炒”，简单实用，和大锅异曲同工

简介
同学们好，由于大锅和猛火灶的确不是普通家庭的配置，所以今天和大家分享一下“小锅翻锅”，希望能帮到想在家练习翻锅的朋友。首先，小锅就不需要抓锅布了，直接握牢锅柄即可。然后，不能像大锅一样有支撑点，所以需要把锅抬高。最后，就是翻锅的过程，总结如下：
1. 保持锅的手握一端微微高于另一端，将锅匀速往正前方推。
2. 在适当位置迅速将锅的另一端抬起猛地拉回，菜品因为惯性被抛起然后落回锅中。
3. 在上面1的过程中，可以用炒勺推动菜品以增加菜品前推的速度，使翻勺更加彻底。
其中的动作要领其实是和大锅一样的，异曲同工，但由于缺少支撑点，所以能翻的重量非常有限，所以千万不要逞强，一点点练习才是最正确的方式。并且大家一定要坚持需要翻的菜才翻，不要为了翻而翻，或者为了耍帅翻锅。希望大家喜欢本期内容！

字幕
0:00:00.225,0:00:01.925
哈喽大家好我是王刚

0:00:02.181,0:00:06.071
前几期视频呢我用这个锅跟大家分享了怎么样去翻锅

0:00:06.086,0:00:12.221
当然有的粉丝说要想学一下家庭里面的小锅 用这个翻

0:00:12.537,0:00:17.944
然后今天我们再复习一遍这个家庭小灶的锅跟这个大锅

0:00:18.086,0:00:21.802
我们加两斤盐下去翻 翻给大家看一下

0:00:22.023,0:00:26.403
好了 我们现在先复习一下上次说的锅拉到三分之一

0:00:26.687,0:00:29.581
然后下去 然后拉 下去

0:00:29.581,0:00:33.992
第二步是下去的时候就往上面翻

0:00:34.260,0:00:37.438
然后现在我们来讲用勺子来推这个东西

0:00:37.802,0:00:39.889
现在我们加入盐

0:00:40.300,0:00:43.003
这里是2斤多3斤的盐 倒下去

0:00:45.249,0:00:49.865
然后我们就像之前的教学这样子试一下翻

0:00:50.071,0:00:52.758
翻得时候用勺子顶 把它顶出去

0:00:52.948,0:00:54.624
回来的时候再带一下

0:00:59.494,0:01:01.754
并不是所有的菜都适合这样子翻

0:01:02.055,0:01:05.185
适合这样子猛翻的只有蛋炒饭 只有炒饭类的

0:01:05.201,0:01:08.201
比如一些鱼的话就并不适合这样子翻

0:01:13.422,0:01:16.252
好 这个是我们的大锅翻法

0:01:17.407,0:01:19.920
现在我们来试一下小锅

0:01:20.758,0:01:22.276
（盐）放到这个小锅里面

0:01:23.256,0:01:25.452
 翻得时候锅一定要是这样子抬起来

0:01:25.470,0:01:29.612
因为家庭小灶的话 下面你这样子肯定是不行的

0:01:30.434,0:01:32.015
然后我们注意它的高度

0:01:32.189,0:01:35.114
我们平常家里面 上面就是抽油烟机 

0:01:35.272,0:01:37.312
你拉得太高的话 这个会撞在上面 

0:01:37.549,0:01:40.316
然后我们现在拿矮一点 这样子翻

0:01:43.351,0:01:46.572
并不是我们所有的菜都需要这样子去翻

0:01:46.592,0:01:50.086
我们只坚持一个原则 需要翻得时候我们才翻

0:01:50.086,0:01:52.874
不需要翻得时候我们坚决不要去翻 

0:01:52.874,0:01:54.608
用勺子这样子铲也可以

0:01:55.083,0:01:56.948
我们这样子翻得时候一定要注意

0:01:57.470,0:01:59.984
注意这个火不能开得太大

0:02:00.110,0:02:05.264
这样一翻的话如果有水分的话锅里面会着火

0:02:05.581,0:02:06.861
会发生一些危险

0:02:09.833,0:02:13.185
这个是我们家庭的翻法

0:02:13.249,0:02:16.996
然后我不建议你们手腕没有力的 拿这个翻

0:02:18.197,0:02:23.098
因为你如果没有练习过直接这样子翻得话很可能菜就翻出去了

0:02:23.399,0:02:27.478
大家可以买一包盐在家里面 尝试性的这样子翻一下

0:02:30.450,0:02:32.347
好了 刚才我们看了这一些（操作）

0:02:32.569,0:02:33.818
现在我翻给你们看一下 

0:02:33.834,0:02:37.375
然后我直接用这个锅代替我们专业灶来翻

0:02:37.565,0:02:38.924
待会再这样子翻

0:02:45.549,0:02:48.822
这是我们在专业厨房里面是这种翻法

0:02:49.169,0:02:51.889
然后下一个我们直接拿起来翻

0:02:54.577,0:02:57.328
你们在家里面的时候可以不用放这么多盐

0:02:57.881,0:02:59.509
就放个1斤就够了

0:02:59.905,0:03:04.537
盐炒完了练习完了之后再放起来下一次可以炒菜用

0:03:07.146,0:03:08.758
好了 本期视频就到这里


```

**Comment by Hackerry** [comment]
认领

**Comment by Hackerry** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：如何练习“小锅翻炒”，简单实用，和大锅异曲同工
Chef Wang shares with you: How to practice flipping food in a small wok, easy and practical.

简介
同学们好，由于大锅和猛火灶的确不是普通家庭的配置，所以今天和大家分享一下“小锅翻锅”，希望能帮到想在家练习翻锅的朋友。首先，小锅就不需要抓锅布了，直接握牢锅柄即可。然后，不能像大锅一样有支撑点，所以需要把锅抬高。最后，就是翻锅的过程，总结如下：
1. 保持锅的手握一端微微高于另一端，将锅匀速往正前方推。
2. 在适当位置迅速将锅的另一端抬起猛地拉回，菜品因为惯性被抛起然后落回锅中。
3. 在上面1的过程中，可以用炒勺推动菜品以增加菜品前推的速度，使翻勺更加彻底。
其中的动作要领其实是和大锅一样的，异曲同工，但由于缺少支撑点，所以能翻的重量非常有限，所以千万不要逞强，一点点练习才是最正确的方式。并且大家一定要坚持需要翻的菜才翻，不要为了翻而翻，或者为了耍帅翻锅。希望大家喜欢本期内容！
Hi guys, today I want to share with you some techniques for flipping food in a small wok. Since most families don't have big wok and burner stoves, I hope those techniques can be helpful for friends who want to practice flipping food at home. First, we don't need a wok towel for this. Just firmly grab the handle. Second, we can't use support as when handling big wok. So we need to keep the wok above the stove. Finally, a summary of the process:
1. Keep the grabbing hand slightly higher than the other side of the wok. Move forward with constant speed.
2. Quickly and forcefully flip the wok, and draw it back at a certain position. Food should be propelled up due to having inertia and then fall back into the wok.
3. We can use spoon to push food forward faster when doing step 1. This helps with flipping.
These steps are very similar to that of using a big wok. However, we can only flip so much without a supporting point. So don't overstrain yourself. Pace yourself and practice little by little. More importantly, do the flipping for dishes that requires doing so. Don't flip for the look of it, but rather the need of it.

字幕
0:00:00.225,0:00:01.925
哈喽大家好我是王刚
Hello everyone, I'm Wang Gang.

0:00:02.181,0:00:06.071
前几期视频呢我用这个锅跟大家分享了怎么样去翻锅
In previous episodes I shared how to flip food with this wok.

0:00:06.086,0:00:12.221
当然有的粉丝说要想学一下家庭里面的小锅 用这个翻
Some fans said they want to learn how to flip food in small woks used in family settings. Use this wok.

0:00:12.537,0:00:17.944
然后今天我们再复习一遍这个家庭小灶的锅跟这个大锅
So today I want to review (introduce) how to flip food for both the big wok and the small one.

0:00:18.086,0:00:21.802
我们加两斤盐下去翻 翻给大家看一下
We'll add 2 Jin (1kg) salt (into the wok). I'll showcase how to flip it.

0:00:22.023,0:00:26.403
好了 我们现在先复习一下上次说的锅拉到三分之一
OK. Let's review what we talked about on pulling the wok up to one third position.

0:00:26.687,0:00:29.581
然后下去 然后拉 下去
Then put it down. Pull up. And down.

0:00:29.581,0:00:33.992
第二步是下去的时候就往上面翻
Next step is to flip when putting the wok down.

0:00:34.260,0:00:37.438
然后现在我们来讲用勺子来推这个东西
Now let's talk about how to use this spoon to push food.

0:00:37.802,0:00:39.889
现在我们加入盐
Now let's add in salt.

0:00:40.300,0:00:43.003
这里是2斤多3斤的盐 倒下去
Here we have more than 2 Jin (1kg), about 3 Jin (1.5kg) salt. Add it in.

0:00:45.249,0:00:49.865
然后我们就像之前的教学这样子试一下翻
Let's try flipping like this as shown in the previous tutorial.

0:00:50.071,0:00:52.758
翻得时候用勺子顶 把它顶出去
Use the spoon to push it forward when flipping.

0:00:52.948,0:00:54.624
回来的时候再带一下
Tip inward when it (food) comes back.

0:00:59.494,0:01:01.754
并不是所有的菜都适合这样子翻
Not all dishes need to be flipped like this.

0:01:02.055,0:01:05.185
适合这样子猛翻的只有蛋炒饭 只有炒饭类的
Only cooking egg fried rice needs this fast flipping. Only fried rice.

0:01:05.201,0:01:08.201
比如一些鱼的话就并不适合这样子翻
It's not suitable for cooking dishes like fish.

0:01:13.422,0:01:16.252
好 这个是我们的大锅翻法
Good. This is how we flip in big wok.

0:01:17.407,0:01:19.920
现在我们来试一下小锅
Now let's try with a small wok.

0:01:20.758,0:01:22.276
（盐）放到这个小锅里面
Put (salt) in this small wok.

0:01:23.256,0:01:25.452
翻得时候锅一定要是这样子抬起来
Take the wok above the stove like this when flipping.

0:01:25.470,0:01:29.612
因为家庭小灶的话 下面你这样子肯定是不行的
Because family stoves are different (smaller). It's impossible to do like this.

0:01:30.434,0:01:32.015
然后我们注意它的高度
Then heed the height.

0:01:32.189,0:01:35.114
我们平常家里面 上面就是抽油烟机 
Usually we have a range hood right above the stove.

0:01:35.272,0:01:37.312
你拉得太高的话 这个会撞在上面 
If you flip too high, the wok will hit the range hood.

0:01:37.549,0:01:40.316
然后我们现在拿矮一点 这样子翻
So we now put it lower a little bit, like this.

0:01:43.351,0:01:46.572
并不是我们所有的菜都需要这样子去翻
Not all dishes needs flipping like this.

0:01:46.592,0:01:50.086
我们只坚持一个原则 需要翻得时候我们才翻
We stick to a single principle: flip only when we need it.

0:01:50.086,0:01:52.874
不需要翻得时候我们坚决不要去翻 
Never flip unless we need it.

0:01:52.874,0:01:54.608
用勺子这样子铲也可以
It's possible to just scoop like this.

0:01:55.083,0:01:56.948
我们这样子翻得时候一定要注意
We need to be careful when flipping.

0:01:57.470,0:01:59.984
注意这个火不能开得太大
Be careful not to leave the fire too strong.

0:02:00.110,0:02:05.264
这样一翻的话如果有水分的话锅里面会着火
Otherwise wok may catch fire if there is water steam present.

0:02:05.581,0:02:06.861
会发生一些危险
It can be dangerous.

0:02:09.833,0:02:13.185
这个是我们家庭的翻法
This is how we do "home-version" flipping.

0:02:13.249,0:02:16.996
然后我不建议你们手腕没有力的 拿这个翻
I don't recommend those who don't have strong arms to flip like this.

0:02:18.197,0:02:23.098
因为你如果没有练习过直接这样子翻得话很可能菜就翻出去了
Because it's highly likely food get flipped out if you haven't practiced much.

0:02:23.399,0:02:27.478
大家可以买一包盐在家里面 尝试性的这样子翻一下
You can buy a bag of salt and try flipping like this.

0:02:30.450,0:02:32.347
好了 刚才我们看了这一些（操作）
Good. We have seen those (techniques).

0:02:32.569,0:02:33.818
现在我翻给你们看一下 
Now let me show you how it's done.

0:02:33.834,0:02:37.375
然后我直接用这个锅代替我们专业灶来翻
I'll directly use this instead of the professional wok to showcase.

0:02:37.565,0:02:38.924
待会再这样子翻
Later I'll flip like this.

0:02:45.549,0:02:48.822
这是我们在专业厨房里面是这种翻法
This is how we flip in a professional kitchen.

0:02:49.169,0:02:51.889
然后下一个我们直接拿起来翻
Next I'll just take it up and flip.

0:02:54.577,0:02:57.328
你们在家里面的时候可以不用放这么多盐
You can use less salt at home.

0:02:57.881,0:02:59.509
就放个1斤就够了
1 Jin (0.5kg) is enough.

0:02:59.905,0:03:04.537
盐炒完了练习完了之后再放起来下一次可以炒菜用
After practicing with this salt, it can be stored and used for cooking next time.

0:03:07.146,0:03:08.758
好了 本期视频就到这里
Alright, that's all for this episode.
