### ISSUE TITLE
[华农兄弟] 华农兄弟帮摄影小哥奶奶种点蔬菜果树小孩们也跟着一起去 - https://youtu.be/Ml8FECXswu8

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#843]
https://youtu.be/Ml8FECXswu8
<p>&#35270;&#39057;&#21457;&#24067;&#20110; March 24, 2020 at 01:32PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/Ml8FECXswu8

#华农兄弟：帮摄影小哥奶奶种点蔬菜果树，小孩们也跟着一起去
#Huanong Brothers: We help Mr. Cameraman's grandma plant some veggies and fruit trees. The kids are also coming with us.

0:00:00.000,0:00:02.540
# 大家好  今年種點這個果樹啊  在那個山上  到時候
Hi everyone! We're planting some fruit trees this year, on the hill. Then later,

0:00:03.120,0:00:06.060
# 在那個山上  到時候我們就有果子吃啦
on the hill, later, we'll have a lot of fruits.

0:00:06.100,0:00:08.020
# 順便把子孩也帶上  是吧
We're going with the kids, see?

0:00:08.580,0:00:10.280
# 下著雨  他們都要來
It's raining now, but they're still coming with us.

0:00:11.140,0:00:11.780
# 就在前面
It's right in front of us.

0:00:12.360,0:00:13.040
# 我們走過去
Let's go over there.

0:00:13.500,0:00:16.020
# 我天不怕我還地不怕
Nothing can scare me, neither thunderstorm nor earthquake!

0:00:40.300,0:00:41.480
# 看一下你頭髮
Look at your hair!

0:00:43.480,0:00:46.460
# 要不要  要不要  你們要不要吃的
You want some? You want some? Do you guys want some snacks?

0:00:47.660,0:00:49.640
# 那種很上火的這種  要不要
It's the one which is really "sheng huo" (lit: accumulate internal heat). You want some?

0:00:51.980,0:00:52.580
# 一人一個
One each.

0:00:53.880,0:00:54.660
# 我要吃
I want some,

0:00:55.540,0:00:56.740
# 沙琪瑪
some sachima!

0:00:57.100,0:00:58.520
# 沙琪瑪沒拿的哦
But I didn't bring any sachima.

0:01:00.620,0:01:01.580
# 這種這個是不是
So that's what we're gonna plant, isn't it?

0:01:01.920,0:01:02.720
# 這個甚麼
What is it in fact?

0:01:03.980,0:01:04.620
# 西紅杮
Tomatoes

0:01:08.100,0:01:09.040
# 爸爸
Daddy!

0:01:09.660,0:01:11.080
# 我要沙琪瑪
I want sachima!

0:01:12.080,0:01:14.500
# 這是攝影小哥奶奶哦  快九十歲啦
This is Mr. Cameraman's grandma. She'll be ninety soon.

0:01:15.340,0:01:19.320
# 這是她買的  這個西紅杮苗  跟那個 攀蒲苗
She bought us these seedlings. There are tomato seedlings, and you know, pumpkin seedlings.

0:01:19.720,0:01:21.140
# 她買了點回來  種一下
She's bought some seedlings and we plant them today.

0:01:21.700,0:01:24.800
# 老人家就喜歡看到自己種的  種的東西
Elderly enjoys seeing their own, their own plants grow.

0:01:28.320,0:01:30.760
# 一個  一個穴位就放兩棵  (註︰穴位.....)
I'll put two, two seedlings in each hole.

0:01:32.540,0:01:34.620
# 你看  一個穴位就放兩個
Look! Two seedlings in one hole

0:01:35.000,0:01:37.520
# 它這個西紅杮容易長  這個
The tomato doesn't need to much care, I mean,

0:01:39.360,0:01:40.740
# 隨便搞點泥就可以了
some soil is all it needs.

0:01:46.040,0:01:46.820
# 這多種點
Let me plant more here.

0:01:53.460,0:01:57.440
# 這棵剩下一棵  單啦  這一棵  沒辦法
Only one remains. It's single, a single one, anyway.

0:01:58.340,0:01:59.340
# 不夠配對
I don't have one more to match with it.

0:02:01.000,0:02:04.360
# 現在下雨啦  躲一下雨  在那房子裡面躲下雨
It's raining now. Let's take a shelter. Let's take a shelter inside that house.

0:02:12.780,0:02:16.760
# 你看  這個是攀蒲  現在不下雨啦  趁早把它種下去
Look! These are pumpkins. The rain has stopped. Let's get them planted as soon as possible.

0:02:17.900,0:02:19.020
# 這裡就可以種
We can just plant them here.

0:02:24.720,0:02:25.700
# 這樣就種好啦
So now it's done.

0:02:27.120,0:02:30.000
# 先把土鋤好  然後就種下去
I dig a hole first, and then put in the seedlings.

0:02:31.760,0:02:35.280
# 要兩棵一起好  比較有伴  長勢也長得比較好
I need to put them in pairs. So that they have a buddy and can grow better.

0:02:41.240,0:02:42.180
# 可以  就這樣
Alright! That's it!

0:02:43.080,0:02:43.680
# 還有一棵
Here's one more.

0:03:05.920,0:03:07.120
# 這樣就種好一棵
So then one is planted.

0:03:07.880,0:03:09.460
# 就買了幾棵  一要那麼多
We've bought only a few cuz we don't need too many.

0:03:09.660,0:03:11.900
# 去年種的  種太多啦  吃都吃不完
We planted too, we planted too many last year. We just couldn't finish them.

0:03:13.000,0:03:14.140
# 全部用來餵小豬了
And all were taken to the piglets.

0:03:15.300,0:03:17.460
# 今年就種了六棵  六棵就足夠了
We've just planted six this year. Six would be enough.

0:03:18.440,0:03:19.940
# 把那果樹也種一下
Let's plant the fruit trees as well.

0:03:20.900,0:03:21.980
# 果樹到那邊去種
We plant the fruit trees over there.

0:03:23.220,0:03:24.020
# 要挖個坑
I need to dig a hole first.

0:03:25.600,0:03:27.640
# 這個太大啦  妹妹你拿不拿起起
It's too big baby. Are you sure that you can take it?

0:03:28.640,0:03:30.720
# 拿要不就  讓我來拿吧
Let, why not, let me take it if she can't?

0:03:31.180,0:03:32.880
# 好這個給  給妹妹
Alright! This is for, for baby.

0:03:34.640,0:03:35.320
# 來  胡韋汝
C'mon! Hu Weiru

0:03:35.880,0:03:37.000
# 把這個樹苗放在這裡
Put the seedling here.

0:03:37.120,0:03:37.980
# 種  種樹啦
Let's, let's plant the tree.

0:03:41.180,0:03:41.840
# 最後一個啦
It's the last one.

0:03:43.280,0:03:44.500
# 你也要來是不是  好
You wanna try too, don't you? Alright!

0:03:45.080,0:03:45.880
# 重新挖一個
I'll dig another hole.

0:03:45.940,0:03:47.200
# 我要那個
I want that one!

0:03:48.260,0:03:50.540
# 可以可以  我要這個玩沙沙
Alright, alright!
I want that one to play with the sand (soil)!

0:03:50.540,0:03:51.640
# 好  等下一起玩
Sure! We'll play together in a second!

0:03:52.880,0:03:53.880
# 別搞到手了啊
Don't hurt your hands!

0:03:56.380,0:03:58.360
# 快點  這裡還有一棵  你要就來
C'mon! Here's one more! Come here if you wanna try!

0:03:58.380,0:04:00.000
# 快點  快點去  妹妹去
C'mon! Let's go! Let's go baby!

0:04:03.260,0:04:07.240
# 嗯  就這樣踩下去啊   你們兩個  把這個土  踩結實一點啊
Um! Just step on it! You two! Step on the soil to make it firm!

0:04:07.580,0:04:10.020
# 妹妹也去  結實一點啊  去
Baby too! Make it firm, alright? Let's go!

0:04:10.460,0:04:11.400
# 別踩死啦
Don't step on the seedling!

0:04:15.960,0:04:17.020
# 這裡  這裡兩棵的
Here, here are two.

0:04:18.060,0:04:18.760
# 拔一棵來
I'll take one.

0:04:19.460,0:04:20.600
# 你不要揮這個鋤頭
Stop swinging the hoe!

0:04:23.840,0:04:24.780
# 這個桃樹哦
This is a peach tree.

0:04:29.400,0:04:31.880
# 來把這個踩結 踩結實了啊
Come and step on it. Make, make it firm.

0:04:32.420,0:04:33.800
# 妹妹  你也去踩一下
Baby, would you step on it too?

0:04:34.200,0:04:34.700
# 踩
Step

0:04:35.360,0:04:35.860
# 好
Alright!

0:04:36.260,0:04:37.040
# 快點  踩
C'mon! Step on it!

0:04:37.580,0:04:38.080
# 這裡
Here!

0:04:57.140,0:04:58.560
# 你看  這棵是楊梅樹哦
Look! This is a berry tree.

0:04:59.560,0:05:01.420
# 到時候種下去的話就有楊梅吃啦
Then, when we plant it, then we can have berries later.

0:05:06.720,0:05:10.900
# 爸爸  我要跟  我也要跟他們一起玩沙子
Daddy! I wanna, I also wanna play with the sand (soil) together with them.

0:05:11.880,0:05:13.360
# 這個楊梅樹很漂亮的哦
This berry tree is really pretty!

0:05:14.260,0:05:15.360
# 這個要慢慢種
I need to do it slowly.

0:05:30.140,0:05:31.700
# 這個草先遮一下先
Let me first cover it with the grass first,

0:05:33.520,0:05:34.520
# 再加點泥土
and then put some soil.

0:05:49.000,0:05:49.500
# 可以啦
Alright!

0:05:50.380,0:05:51.080
# 這個楊梅樹
It's a berry tree.

0:05:56.300,0:05:56.920
# 好啦
Alright!

0:05:58.280,0:06:00.560
# 今天的視頻就到這裡啦  要回去啦
The video ends here. We need to go back now.

0:06:01.040,0:06:02.260
# 好像又要下雨啦
It will rain again very soon.

0:06:03.060,0:06:05.200
# 再不回去等下全部都淋都落場雞
We'll all get soaked if we stay any longer here.

0:06:05.440,0:06:06.680
# 啊  好  先回去啦
Ah! Good! Let's go back first.

0:06:07.540,0:06:08.040
# 走啦
Let's go!

0:06:14.640,0:06:16.060
# 快點  把那個衣服拿上來 (註︰不明白)
C'mon, hurry up! Take the clothes!

0:06:16.160,0:06:17.000
# 拿起來啦
Hold it!

0:06:19.640,0:06:22.800
# 有只黑狗  黑狗  黑狗在這裡
Isn't here a black dogs?
Black dog? Black dog is here.

0:06:25.260,0:06:26.700
# 不要去砸它  劉星辰
Don't throw onto the dog, Liu Xingchen!

0:06:28.780,0:06:30.140
# 等下它要咬你了
He's coming to bite you!

0:06:35.480,0:06:37.520
# 這裡有 這裡有更靚的  這裡
Here! Here's one even more beautiful! Here!

0:06:39.100,0:06:41.480
# 你看  這裡  這裡可以用來種菜的哦
Look! Here, we can plant some veggies here, you know.

0:06:41.860,0:06:43.420
# 攝影小哥奶奶很喜歡種菜
Mr. Cameraman's grandma enjoy planting veggies a lot.

0:06:43.620,0:06:44.660
# 到時候我們把它圍起來
We can fence it off later.

0:06:45.340,0:06:46.640
# 小狗就踩不到那個菜了
Then the doggies can't step on the veggies.

0:06:47.160,0:06:48.240
# 我也想要種點青菜
I wanna plant some veggies too.

0:06:58.640,0:06:59.540
# 好不好吃
Does it taste good?

0:07:12.040,0:07:13.000
# 跑到那裡去啦
Where's the dog now?

0:07:14.840,0:07:16.600
# 我要把它跑下來
I'm gonna take it back here!
