### ISSUE TITLE
【美食作家王刚】剁椒鱼头 - https://youtu.be/IEaBzJqWh0U

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#847]
**视频链接**：https://youtu.be/IEaBzJqWh0U

视频时长 6:23，预计发布时间为北京时间3月31日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：经典湘菜“剁椒鱼头”的家常做法，四伯说名不虚传，赞不绝口

简介
大家好，今天给四伯做一道经典湘菜“剁椒鱼头”，此菜将鱼头的鲜味和剁椒的辣融为一体，蒸制的方法将鱼头的鲜香尽量保留在肉中，剁椒的鲜辣又恰到好处的渗入鱼头之中。湖南传统名菜果然名不虚传，四伯吃后都赞不绝口，大家有机会也可以在家尝试。

字幕
0:00:00.000,0:00:02.679
今天咱们做一个剁椒蒸鱼

0:00:02.679,0:00:03.481
蒸鱼头

0:00:03.788,0:00:05.938
这个是花鲢

0:00:06.774,0:00:07.935
这个有好重四伯爷你看

0:00:08.225,0:00:08.959
四五斤吧

0:00:09.129,0:00:10.836
对 四斤半左右

0:00:10.972,0:00:11.843
先把它敲一下

0:00:18.310,0:00:20.477
咱们这个剁椒蒸鱼头

0:00:20.477,0:00:21.706
大家不会改刀的

0:00:21.706,0:00:23.310
现在可以看一下斜着改

0:00:23.805,0:00:26.348
这样子斜着改它鱼头翻过来了之后呢

0:00:26.552,0:00:28.105
它这个头就圆圆的

0:00:28.139,0:00:28.583
这样子

0:00:28.822,0:00:30.631
然后咱们在市场上面买的鱼头

0:00:30.887,0:00:33.242
商贩也会这样子他斜的很厉害

0:00:33.259,0:00:34.607
可能这样子斜对半

0:00:34.948,0:00:36.535
因为鱼头偏贵一些

0:00:36.757,0:00:38.515
鱼尾的话就卖得便宜些

0:00:39.385,0:00:41.245
我们就斜着把鱼肚都留在上面

0:00:42.184,0:00:43.037
伯爷喜欢吃

0:00:43.225,0:00:44.163
然后再翻过来

0:00:45.511,0:00:46.143
这样子

0:00:48.225,0:00:49.402
但是大家一定要小心

0:00:49.402,0:00:50.563
不能直接把它剁开

0:00:50.563,0:00:53.907
剁开了它的内脏的话就出来了

0:00:53.959,0:00:54.897
就不好看

0:00:55.409,0:00:56.228
到这个位置

0:00:56.416,0:00:57.764
这个位置的话给它剁下去

0:00:58.020,0:01:00.034
它的脊椎就到这个位置

0:01:01.092,0:01:02.832
很多同学在问这个鱼头怎么破

0:01:02.832,0:01:03.924
破哪一边

0:01:04.232,0:01:06.075
有人会说选择破肚子这边

0:01:06.262,0:01:07.866
其实破肚子非常难看

0:01:08.071,0:01:09.948
我们必须从这边破下去

0:01:10.426,0:01:12.116
这边破开了非常好看

0:01:13.020,0:01:14.215
慢慢的这样子走过去

0:01:14.658,0:01:16.006
如果你是买的话

0:01:16.006,0:01:17.252
尽量让摊主给你处理好

0:01:19.846,0:01:21.484
好 这样子扳开

0:01:22.269,0:01:25.546
扳开了之后我们再来去它的内脏

0:01:27.662,0:01:30.870
这是它的鱼胆 鱼肝 鱼肠之类的

0:01:31.160,0:01:31.808
不要

0:01:32.354,0:01:34.641
像上次杀那个鲤鱼一样

0:01:37.167,0:01:38.976
好 我们鱼头就改好了

0:01:39.061,0:01:40.268
现在去清洗一下

0:01:40.960,0:01:42.463
现在我们这个鱼清洗干净了

0:01:42.463,0:01:44.112
但是还有一个地方没有去除

0:01:44.196,0:01:45.114
它的这个牙齿

0:01:45.135,0:01:45.908
在这个位置

0:01:46.983,0:01:48.935
大头鱼的都在这个位置

0:01:51.784,0:01:53.058
这个鱼头改一下刀

0:01:53.747,0:01:55.615
就是说在上面随便的剁一下

0:01:57.004,0:01:59.269
剁一下就让它这个味道更容易进去

0:02:00.083,0:02:01.795
下面我们来随便腌制一下

0:02:01.952,0:02:02.818
简单的腌制

0:02:03.517,0:02:04.603
撒一点点这个盐

0:02:05.480,0:02:06.586
不用太多一点点就行

0:02:06.586,0:02:07.901
因为剁椒也是咸的

0:02:09.175,0:02:10.929
好 腌制了给它放在一边

0:02:11.555,0:02:13.204
好 现在来处理这个剁椒

0:02:14.582,0:02:16.753
这个就是湖南本地的一个剁椒

0:02:17.599,0:02:18.935
其实价格很便宜不贵

0:02:21.649,0:02:22.818
大家可以看下这个剁椒

0:02:22.818,0:02:24.582
它原来的水是非常咸的

0:02:24.582,0:02:26.534
而且有一股发酵的味道

0:02:26.534,0:02:27.901
现在我们要把它清洗一下

0:02:28.789,0:02:29.707
把它清洗过呀

0:02:29.979,0:02:31.732
要洗过 不是那个味道有点怪

0:02:31.952,0:02:34.123
这个我们洗个一两次就可以了

0:02:35.208,0:02:36.868
如果这个剁椒里面水太多啊

0:02:36.993,0:02:39.478
它这个蒸出来就是有一股水的味道

0:02:40.177,0:02:41.012
香味就出不来

0:02:42.912,0:02:45.260
好 然后我们这个剁椒里面配一点蒜

0:02:46.085,0:02:48.486
就是给它剁碎了放进去

0:02:50.177,0:02:51.628
切一点这个姜片

0:02:53.215,0:02:54.008
垫在鱼下面

0:02:54.081,0:02:56.732
它蒸的时候自己可以去除一些腥味

0:02:57.014,0:02:58.935
这个葱就把它挽起来就可以了

0:03:00.052,0:03:01.847
现在我们要准备开始做了

0:03:02.411,0:03:05.939
就把这个姜片垫在下面

0:03:07.172,0:03:08.780
然后再放上这个葱

0:03:09.624,0:03:12.974
最后我们来把这个鱼头放到这个上面

0:03:14.039,0:03:14.519
这样子的话

0:03:14.519,0:03:16.461
它那个就有利于它的水呀

0:03:17.045,0:03:18.893
蒸汽水啊  它的血水啊

0:03:18.893,0:03:19.937
流到盘子底下

0:03:20.187,0:03:21.899
待会我们是吧

0:03:21.899,0:03:23.674
蒸的时候就可以把那个水去一去

0:03:24.718,0:03:27.954
好 我去烧火准备蒸起了

0:03:28.215,0:03:28.611
要得

0:03:34.989,0:03:36.388
锅头是菜籽油呀

0:03:36.450,0:03:37.964
菜籽油 你打的那个都嘛

0:03:39.697,0:03:40.949
这个要下去炒哈

0:03:43.444,0:03:44.738
炒了之后就更香这个

0:03:44.739,0:03:45.809
那肯定了

0:03:47.807,0:03:49.478
油多点好吃点

0:03:49.478,0:03:51.524
鱼肯定要油多点才好吃

0:03:51.524,0:03:52.849
整得干巴巴的就不安逸了

0:03:54.968,0:03:56.388
盐巴 一滴滴的就够了

0:03:57.056,0:03:58.027
放点鸡精

0:03:58.580,0:03:59.561
放点这个白糖

0:04:00.281,0:04:01.534
少放一滴滴的蚝油

0:04:05.018,0:04:06.426
稍微炒一哈就可以放在这个上来了

0:04:28.525,0:04:31.650
好 十分钟

0:04:53.850,0:04:55.225
先撒一半的葱花

0:04:56.025,0:04:58.026
过一下油之后再撒剩下的一半

0:05:04.757,0:05:07.231
葱葱撒起  稀稀疏疏的看到还舒服

0:05:07.231,0:05:07.835
在给它撒一点

0:05:08.424,0:05:09.676
好 可以吃了

0:05:11.281,0:05:11.870
试一哈

0:05:12.091,0:05:13.033
管他对不对哦

0:05:13.033,0:05:14.874
先整来试哈

0:05:14.874,0:05:15.846
你先尝一下够不够盐味

0:05:15.891,0:05:18.085
不够盐味我们再淋一点酱油上去

0:05:18.380,0:05:19.955
酱油最后淋上去才好吃

0:05:20.427,0:05:21.855
伯爷 吃鱼头要吃前面

0:05:22.209,0:05:24.388
我先把这个吃了 尝一下味道

0:05:24.388,0:05:24.565
先从这个鱼嘴这里吃起走

0:05:24.565,0:05:25.655
先从这个鱼嘴这里吃起走

0:05:26.759,0:05:27.540
这个才是最滑的

0:05:27.540,0:05:28.394
来 伯娘

0:05:29.086,0:05:30.191
好好好 没得事的

0:05:31.325,0:05:31.826
安逸

0:05:32.150,0:05:32.916
够不够味道

0:05:32.989,0:05:33.475
够味道

0:05:34.005,0:05:34.609
够了 是不是

0:05:34.609,0:05:34.963
 嗯

0:05:35.463,0:05:36.303
嗯 够了

0:05:37.319,0:05:39.749
因为我们这个剁椒可能偏咸一点点

0:05:41.060,0:05:43.564
如果说洗完之后不够味的话

0:05:43.843,0:05:46.126
最后我们再淋一点这个酱油就可以了

0:05:49.160,0:05:49.911
真的安逸

0:05:51.207,0:05:51.958
它和豆花一样

0:05:52.562,0:05:53.976
就是油要多点稍微

0:05:54.683,0:05:55.081
嗯

0:05:57.083,0:05:59.219
如果油少了蒸出来就是干巴巴的这个肉

0:06:00.677,0:06:02.724
本来整鱼就要鱼（的）油多

0:06:02.724,0:06:03.843
嗯 是

0:06:06.789,0:06:07.982
 我伯爷都说很好吃

0:06:08.026,0:06:08.821
嗯 很好吃

0:06:08.939,0:06:10.382
大家可以在家里试一下

0:06:10.957,0:06:14.271
我伯爷说了评价这个湘菜当中的剁椒鱼头

0:06:14.344,0:06:15.301
名不虚传

0:06:15.434,0:06:15.773
嗯 安逸

0:06:16.995,0:06:17.437
好吃

0:06:17.835,0:06:18.600
赞不绝口

0:06:19.116,0:06:20.486
好了 本期视频就到这里


```

**Comment by Jasminelv** [comment]
认领

**Comment by Jasminelv** [comment]
题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：经典湘菜“剁椒鱼头”的家常做法，四伯说名不虚传，赞不绝口
Chef shares a signature dish from Hunan Cuisine: fermented chopped red pepper steam fish head.
Uncle praises highly of this dish!

简介
大家好，今天给四伯做一道经典湘菜“剁椒鱼头”，此菜将鱼头的鲜味和剁椒的辣融为一体，蒸制的方法将鱼头的鲜香尽量保留在肉中，剁椒的鲜辣又恰到好处的渗入鱼头之中。湖南传统名菜果然名不虚传，四伯吃后都赞不绝口，大家有机会也可以在家尝试。
Hello everyone, today I am making a classic Hunan dish for Uncle.  This dish is a perfect combination of the freshness of fish head and spicy from the fermented chopped red pepper.  Steaming is a way to seal the fresh flavor of the fish head, and let the pepper flavor penetrate into the fish.  Hunan cuisine is well-known and for the right reason, Uncle totally enjoyed the dish.  You can try it at home too. 

字幕
0:00:00.000,0:00:02.679
今天咱们做一个剁椒蒸鱼
Today we are making a steamed fish with fermented chopped red pepper.

0:00:02.679,0:00:03.481
蒸鱼头
I meant to say fish head.

0:00:03.788,0:00:05.938
这个是花鲢
This is a calyx.

0:00:06.774,0:00:07.935
这个有好重四伯爷你看
Uncle, guess how much does the fish weigh?

0:00:08.225,0:00:08.959
四五斤吧
2-2.5 kg.

0:00:09.129,0:00:10.836
对 四斤半左右
Correct, around 2.25 kg.

0:00:10.972,0:00:11.843
先把它敲一下
Stun the fish on the head.

0:00:18.310,0:00:20.477
咱们这个剁椒蒸鱼头
To steam a fish head,

0:00:20.477,0:00:21.706
大家不会改刀的
If you don’t know how to cut the meat

0:00:21.706,0:00:23.310
现在可以看一下斜着改
You can try to cut it this way with angle

0:00:23.805,0:00:26.348
这样子斜着改它鱼头翻过来了之后呢
Then when you flip the fish over

0:00:26.552,0:00:28.105
它这个头就圆圆的
The head will be round

0:00:28.139,0:00:28.583
这样子
Like this

0:00:28.822,0:00:30.631
然后咱们在市场上面买的鱼头
The fish head we can buy from the market

0:00:30.887,0:00:33.242
商贩也会这样子他斜的很厉害
The fish sellers usually will cut with a big angle

0:00:33.259,0:00:34.607
可能这样子斜对半
Like 45 degrees

0:00:34.948,0:00:36.535
因为鱼头偏贵一些
Because fish head is usually the more pricy part, 

0:00:36.757,0:00:38.515
鱼尾的话就卖得便宜些
Fishtail is cheaper.

0:00:39.385,0:00:41.245
我们就斜着把鱼肚都留在上面
I cut it this way to keep all the fish belly

0:00:42.184,0:00:43.037
伯爷喜欢吃
Uncle loves this part

0:00:43.225,0:00:44.163
然后再翻过来
Now I flip it over

0:00:45.511,0:00:46.143
这样子
Like this.

0:00:48.225,0:00:49.402
但是大家一定要小心
Please note that

0:00:49.402,0:00:50.563
不能直接把它剁开
You don’t want to just simply cut it open

0:00:50.563,0:00:53.907
剁开了它的内脏的话就出来了
That will have all the organs running out

0:00:53.959,0:00:54.897
就不好看
It won’t look nice.

0:00:55.409,0:00:56.228
到这个位置
From here

0:00:56.416,0:00:57.764
这个位置的话给它剁下去
Chop down from here

0:00:58.020,0:01:00.034
它的脊椎就到这个位置
Where the spine is.

0:01:01.092,0:01:02.832
很多同学在问这个鱼头怎么破
Many asked me, how to cut the fish head into half

0:01:02.832,0:01:03.924
破哪一边
Which side to cut from

0:01:04.232,0:01:06.075
有人会说选择破肚子这边
Some say to cut from the bottom side

0:01:06.262,0:01:07.866
其实破肚子非常难看
It actually would look really ugly

0:01:08.071,0:01:09.948
我们必须从这边破下去
We’d better cut from this way

0:01:10.426,0:01:12.116
这边破开了非常好看
It will look great.

0:01:13.020,0:01:14.215
慢慢的这样子走过去
Cut it slowly and carefully.

0:01:14.658,0:01:16.006
如果你是买的话
If you just buy the fish head

0:01:16.006,0:01:17.252
尽量让摊主给你处理好
Have the seller to cut and clean it for you

0:01:19.846,0:01:21.484
好 这样子扳开
OK, now we open it like this

0:01:22.269,0:01:25.546
扳开了之后我们再来去它的内脏
Then we get rid of its organs

0:01:27.662,0:01:30.870
这是它的鱼胆 鱼肝 鱼肠之类的
Like the gallbladder, liver, and intestines, etc

0:01:31.160,0:01:31.808
不要
Discard them.

0:01:32.354,0:01:34.641
像上次杀那个鲤鱼一样
Just like what we did last time with the carp

0:01:37.167,0:01:38.976
好 我们鱼头就改好了
Now the fish head is ready

0:01:39.061,0:01:40.268
现在去清洗一下
We will rinse it 

0:01:40.960,0:01:42.463
现在我们这个鱼清洗干净了
Now it is rinsed clean

0:01:42.463,0:01:44.112
但是还有一个地方没有去除
But I noticed one more thing to remove

0:01:44.196,0:01:45.114
它的这个牙齿
Its teeth

0:01:45.135,0:01:45.908
在这个位置
It’s located here.

0:01:46.983,0:01:48.935
大头鱼的都在这个位置
Teeth of bighead fishes are all here

0:01:51.784,0:01:53.058
这个鱼头改一下刀
Now we give the fish head some cuts

0:01:53.747,0:01:55.615
就是说在上面随便的剁一下
Just a few random slices is fine

0:01:57.004,0:01:59.269
剁一下就让它这个味道更容易进去
The seasonings will soak in better

0:02:00.083,0:02:01.795
下面我们来随便腌制一下
Now let’s do a simple marinade 

0:02:01.952,0:02:02.818
简单的腌制
Very simple


0:02:03.517,0:02:04.603
撒一点点这个盐
A little bit salt

0:02:05.480,0:02:06.586
不用太多一点点就行
Just a little bit

0:02:06.586,0:02:07.901
因为剁椒也是咸的
Because the fermented red pepper is very salty

0:02:09.175,0:02:10.929
好 腌制了给它放在一边
Now let’s set it aside.

0:02:11.555,0:02:13.204
好 现在来处理这个剁椒
We are going to process the pepper.

0:02:14.582,0:02:16.753
这个就是湖南本地的一个剁椒
It is a brand from Hunan.

0:02:17.599,0:02:18.935
其实价格很便宜不贵
Price is very reasonable.

0:02:21.649,0:02:22.818
大家可以看下这个剁椒
Let’s take a look at it

0:02:22.818,0:02:24.582
它原来的水是非常咸的
The brine water is very salty

0:02:24.582,0:02:26.534
而且有一股发酵的味道
With a fermented smell.

0:02:26.534,0:02:27.901
现在我们要把它清洗一下
So we need to rinse it

0:02:28.789,0:02:29.707
把它清洗过呀
You rinse the pepper?

0:02:29.979,0:02:31.732
要洗过 不是那个味道有点怪
It is necessary, it smells.

0:02:31.952,0:02:34.123
这个我们洗个一两次就可以了
One or two times rinsing is good enough

0:02:35.208,0:02:36.868
如果这个剁椒里面水太多啊
If the pepper is not drained completely

0:02:36.993,0:02:39.478
它这个蒸出来就是有一股水的味道
It will smell watery later.

0:02:40.177,0:02:41.012
香味就出不来
And the aroma will not come out.

0:02:42.912,0:02:45.260
好 然后我们这个剁椒里面配一点蒜
Now we need to add some garlic to the pepper

0:02:46.085,0:02:48.486
就是给它剁碎了放进去
Some minced garlic

0:02:50.177,0:02:51.628
切一点这个姜片
Then some ginger slices

0:02:53.215,0:02:54.008
垫在鱼下面
Place the slices under the fish.

0:02:54.081,0:02:56.732
它蒸的时候自己可以去除一些腥味
It is to get rid of the fishy smell

0:02:57.014,0:02:58.935
这个葱就把它挽起来就可以了
Tie the green onions into a knot

0:03:00.052,0:03:01.847
现在我们要准备开始做了
Now we are ready to steam it.

0:03:02.411,0:03:05.939
就把这个姜片垫在下面
Put the ginger slices on the bottom

0:03:07.172,0:03:08.780
然后再放上这个葱
Then the green onion

0:03:09.624,0:03:12.974
最后我们来把这个鱼头放到这个上面
Last we put the fish head on it

0:03:14.039,0:03:14.519
这样子的话
thus

0:03:14.519,0:03:16.461
它那个就有利于它的水呀
All the liquid

0:03:17.045,0:03:18.893
蒸汽水啊  它的血水啊
Like the steam and blood..

0:03:18.893,0:03:19.937
流到盘子底下
Will stay at the bottom of the plate

0:03:20.187,0:03:21.899
待会我们是吧
During the steaming

0:03:21.899,0:03:23.674
蒸的时候就可以把那个水去一去
We can pour some liquid out


0:03:24.718,0:03:27.954
好 我去烧火准备蒸起了
Now I am going to start the burner

0:03:28.215,0:03:28.611
要得
Okay

0:03:34.989,0:03:36.388
锅头是菜籽油呀
Is this rapeseed oil?

0:03:36.450,0:03:37.964
菜籽油 你打的那个都嘛
Yes, the oil you made.

0:03:39.697,0:03:40.949
这个要下去炒哈
You need to fry these?

0:03:43.444,0:03:44.738
炒了之后就更香这个
Yes, they are more flavorful once fried.

0:03:44.739,0:03:45.809
那肯定了
Sure it is.

0:03:47.807,0:03:49.478
油多点好吃点
More oil will make it tastier.

0:03:49.478,0:03:51.524
鱼肯定要油多点才好吃
Fish dish needs more cooking oil.

0:03:51.524,0:03:52.849
整得干巴巴的就不安逸了
It doesn’t taste good if it is dry.

0:03:54.968,0:03:56.388
盐巴 一滴滴的就够了
As for salt, a little bit is enough.

0:03:57.056,0:03:58.027
放点鸡精
Some chicken bouillon powder

0:03:58.580,0:03:59.561
放点这个白糖
Some sugar

0:04:00.281,0:04:01.534
少放一滴滴的蚝油
And some oyster sauce 

0:04:05.018,0:04:06.426
稍微炒一哈就可以放在这个上来了
Slightly fry it and then pour on the fish

0:04:28.525,0:04:31.650
好 十分钟
OK, 10 minutes 


0:04:53.850,0:04:55.225
先撒一半的葱花
Sprinkle half of the green onion on it.

0:04:56.025,0:04:58.026
过一下油之后再撒剩下的一半
Pour some oil over the green onions, then sprinkle the rest afterward

0:05:04.757,0:05:07.231
葱葱撒起  稀稀疏疏的看到还舒服
Some green makes it look nice.

0:05:07.231,0:05:07.835
在给它撒一点
Some more.

0:05:08.424,0:05:09.676
好 可以吃了
OK, now it’s ready to serve

0:05:11.281,0:05:11.870
试一哈
Let’s try it

0:05:12.091,0:05:13.033
管他对不对哦
Doesn’t matter if every step is perfectly authentic

0:05:13.033,0:05:14.874
先整来试哈
I will try it 

0:05:14.874,0:05:15.846
你先尝一下够不够盐味
Try if it is salty enough

0:05:15.891,0:05:18.085
不够盐味我们再淋一点酱油上去
If not, we can add some soy sauce.

0:05:18.380,0:05:19.955
酱油最后淋上去才好吃
Soy sauce must be added after cooking.

0:05:20.427,0:05:21.855
伯爷 吃鱼头要吃前面
Uncle, the meat in the front is the best.

0:05:22.209,0:05:24.388
我先把这个吃了 尝一下味道
I am just testing if it’s salty enough.

0:05:24.388,0:05:24.565
先从这个鱼嘴这里吃起走
It’s better to start from the fish lips.

0:05:24.565,0:05:25.655
先从这个鱼嘴这里吃起走
Start eating from the fish lip.

0:05:26.759,0:05:27.540
这个才是最滑的
It tastes smooth and nice.

0:05:27.540,0:05:28.394
来 伯娘
Help yourself, aunti-in-law.

0:05:29.086,0:05:30.191
好好好 没得事的
Ok ok ok, no worries

0:05:31.325,0:05:31.826
安逸
It tastes great.

0:05:32.150,0:05:32.916
够不够味道
Salty enough?

0:05:32.989,0:05:33.475
够味道
Yes

0:05:34.005,0:05:34.609
够了 是不是
Enough flavors?

0:05:34.609,0:05:34.963
 嗯
Yes.

0:05:35.463,0:05:36.303
嗯 够了
Enough indeed.

0:05:37.319,0:05:39.749
因为我们这个剁椒可能偏咸一点点
Fermented pepper usually is on the saltier side.

0:05:41.060,0:05:43.564
如果说洗完之后不够味的话
But after rinsing, it might not be as salty.

0:05:43.843,0:05:46.126
最后我们再淋一点这个酱油就可以了
In that case, we just need to add some soy sauce.

0:05:49.160,0:05:49.911
真的安逸
It tastes really nice!

0:05:51.207,0:05:51.958
它和豆花一样
As tender as tofu pudding.

0:05:52.562,0:05:53.976
就是油要多点稍微
It needs more oil than other dishes.

0:05:54.683,0:05:55.081
嗯
Yes.

0:05:57.083,0:05:59.219
如果油少了蒸出来就是干巴巴的这个肉
If the oil is not enough, the steamed fish will taste dry.

0:06:00.677,0:06:02.724
本来整鱼就要鱼（的）油多
All fish dishes require more oil in general.

0:06:02.724,0:06:03.843
嗯 是
Oh, that’s right.

0:06:06.789,0:06:07.982
 我伯爷都说很好吃
My uncle says it tastes really good

0:06:08.026,0:06:08.821
嗯 很好吃
Yes, very flavorful.

0:06:08.939,0:06:10.382
大家可以在家里试一下
You can try to cook this at home.

0:06:10.957,0:06:14.271
我伯爷说了评价这个湘菜当中的剁椒鱼头
My uncles say the steamed fish head with fermented red pepper

0:06:14.344,0:06:15.301
名不虚传
Is really matching its fame.

0:06:15.434,0:06:15.773
嗯 安逸
Yes, really nice.

0:06:16.995,0:06:17.437
好吃
Tasty!

0:06:17.835,0:06:18.600
赞不绝口
Can’t praise it enough.

0:06:19.116,0:06:20.486
好了 本期视频就到这里
OK, that’s all for today’s video.
