### ISSUE TITLE
【美食作家王刚】爆炒鸭肠 - https://youtu.be/iqGGXq0PFq8

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#848]
**视频链接**：https://youtu.be/iqGGXq0PFq8

视频时长 5:04，预计发布时间为北京时间4月1日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：川味正宗“爆炒鸭肠”，味道香辣爽口，学习起来

简介
同学们好，今天和大家分享一道川味正宗“爆炒鸭肠”，由于鸭肠很细小并且很难处理，所以很久以来除了川渝地区人们特别喜爱其他地区没有特别多使用鸭肠的菜品，但由于近些年川菜的流行，鸭肠也就成为了川渝特色菜的代表之一。经过处理后的鸭肠不但没有异味，还特别爽脆，和香辣味型搭配简直天衣无缝，所以想尝正宗川渝菜的朋友不要错过这么一道香辣爽口的爆炒鸭肠！

本期菜品:【爆炒鸭肠】 
【主料】
鸭肠（1000克）
【辅料】
小苏打（约2克）
干淀粉（约50克）
大蒜（约20克）
红泡椒（20克）
老姜（20克）
小米辣（几个）
二荆条（几个）
仔姜（1小块）
芹菜（几根）
小葱头（几根）
植物油（适量）
明油（少许）
【调味料】
食用盐（适量）
料酒（适量）
胡椒粉（适量）
白糖（少许）
生抽酱油（5克）
陈醋（约1克）
豆瓣酱（4克）
老抽（1克）

字幕
0:00:00.340,0:00:01.420
哈喽大家好 我是王刚

0:00:01.420,0:00:03.620
本期视频我给大家分享一道家常菜

0:00:04.360,0:00:05.680
爆炒鸭肠

0:00:05.780,0:00:08.340
首先我们准备新鲜鸭肠1000克

0:00:08.420,0:00:11.075
然后将鸭肠中的黄油和杂质刮干净备用

0:00:11.512,0:00:14.376
同学们鸭肠的最终出肉率仅仅为百分之三十五

0:00:14.690,0:00:16.289
所以必须将料准备足

0:00:16.593,0:00:19.048
黄油刮干净之后开始下一步开始准备清洗

0:00:19.486,0:00:21.693
首先我们在盆中加入适量的食用盐（约50克）

0:00:24.900,0:00:26.403
加入小苏打1小撮（约2克）

0:00:27.183,0:00:28.430
加入适量的干淀粉（约50克）

0:00:31.389,0:00:32.568
加入适量的料酒

0:00:35.613,0:00:37.954
然后我们用手将鸭肠抓拌5分钟

0:00:38.097,0:00:40.513
这一步的目的是充分去除鸭肠的黏液

0:00:40.789,0:00:43.158
加小苏打的目的是让鸭肠保持脆度

0:00:43.311,0:00:46.194
5分钟之后将鸭肠放入清水中清洗干净备用

0:00:46.451,0:00:49.752
同学们必须多清洗几遍直到水清为止

0:01:01.655,0:01:03.777
清洗干净之后捞出挤干水份备用

0:01:05.904,0:01:08.420
然后将鸭肠每一根拉直摆放整齐

0:01:13.615,0:01:16.765
摆放整齐之后将其切成15厘米左右的小段备用

0:01:17.078,0:01:20.352
鸭肠必须切长一些否则受热收缩之后成菜难看

0:01:28.936,0:01:30.477
下一步开始准备辅料

0:01:30.477,0:01:32.952
准备大蒜几颗拍散之后剁碎备用（约20克）

0:01:40.375,0:01:42.593
准备红泡椒20克切成小粒备用

0:01:47.614,0:01:49.949
准备老姜20克拍散之后剁碎备用

0:01:57.119,0:01:59.556
准备几个小米辣和二荆条切碎备用

0:01:59.556,0:02:01.486
不能吃辣的同学可以不加

0:02:09.577,0:02:11.566
准备仔姜1小块切成丝备用

0:02:17.598,0:02:19.552
准备芹菜几根切成小段备用

0:02:26.411,0:02:28.827
最后准备小葱头几根切成小段备用

0:02:29.023,0:02:30.686
下一步开始提前调味

0:02:30.686,0:02:33.103
首先我们在辅料碗中加入食用盐1克

0:02:33.298,0:02:34.775
加入胡椒粉1小勺（约0.5克）

0:02:35.197,0:02:36.701
加入少许白糖提鲜

0:02:37.018,0:02:38.475
加入生抽酱油5克

0:02:40.395,0:02:41.586
加入少许陈醋（约1克）

0:02:42.269,0:02:43.367
下一步开始制作

0:02:43.746,0:02:46.682
首先我们在锅中加入适量的清水开大火烧开

0:02:47.651,0:02:49.177
中途加入适量的料酒

0:02:53.166,0:02:56.264
大火烧开之后将处理好的鸭肠下锅焯水10秒钟

0:02:56.385,0:02:58.373
这一步的目的是将鸭肠烫卷（约6成熟）

0:03:05.646,0:03:07.071
下一步我们开始制作

0:03:07.414,0:03:08.743
首先我们把锅烧热

0:03:09.208,0:03:11.312
锅烧热之后加入适量的油滑锅

0:03:14.459,0:03:16.274
滑好锅之后将热油倒出

0:03:17.730,0:03:19.140
再加入适量的底油

0:03:21.873,0:03:24.555
油温6成热之后加入姜蒜粒和泡椒爆香

0:03:29.155,0:03:32.084
中途再加入豆瓣酱4克炒香炒出红油

0:03:35.883,0:03:39.182
豆瓣酱炒香之后将焯好水的鸭肠下锅翻炒几下

0:03:49.287,0:03:50.917
翻炒均匀之后开始调味

0:03:51.372,0:03:53.615
锅中加入适量的白糖和胡椒粉调味

0:03:56.332,0:03:58.159
加入料酒5克从锅边淋入

0:03:59.313,0:04:01.070
最后加入老抽1克调底色

0:04:01.583,0:04:03.203
然后开中火翻炒几下

0:04:07.467,0:04:09.768
翻炒均匀之后再加入准备好的辅料（辣椒，仔姜丝，芹菜）.

0:04:17.730,0:04:21.163
开中火翻炒至断生之后再加入适量的水淀粉勾成薄芡

0:04:25.469,0:04:28.241
最后加入少许明油翻炒均匀即可出锅装盘

0:04:35.440,0:04:38.240
一道非常美味的爆炒鸭肠就制作完成

0:04:44.700,0:05:03.880
下面开始技术总结
第一，最好选择新鲜鸭肠，冰冻鸭肠口感略低
第二，鸭肠必须加盐淀粉料酒多抓洗几遍，否则会有腥味
第三，辅料下锅之前先调味可以减少翻炒的时间
第四，最后可以勾薄芡也可以不勾芡
爆炒鸭肠的技术总结完毕


```

**Comment by Jasminelv** [comment]
认领

**Comment by Jasminelv** [comment]
请翻译以下全部内容
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：川味正宗“爆炒鸭肠”，味道香辣爽口，学习起来
Chef Wang teaches you: authentic Sichuan stir fry duck intestine, crispy and spicy!

简介
同学们好，今天和大家分享一道川味正宗“爆炒鸭肠”，由于鸭肠很细小并且很难处理，所以很久以来除了川渝地区人们特别喜爱其他地区没有特别多使用鸭肠的菜品，但由于近些年川菜的流行，鸭肠也就成为了川渝特色菜的代表之一。经过处理后的鸭肠不但没有异味，还特别爽脆，和香辣味型搭配简直天衣无缝，所以想尝正宗川渝菜的朋友不要错过这么一道香辣爽口的爆炒鸭肠！
Hello everyone, today I share with you an authentic Sichuan dish, stir fry duck intestine.  
Duck intestine is rather small and difficult to prepare, therefore, for a long time, besides Sichuan and Chongqing area, people didn’t use duck intestine much in their cooking.  In recent years, Sichuan cuisine becomes more and more popular, and the duck intestine has become a signature dish.  When prepared right, duck intestine is not only smell-less but also crispy and goes well with a spicy flavor.  If you like spicy food, you won’t want to miss it.

本期菜品:【爆炒鸭肠】 
Today’s dish: stir fry duck intestine

【主料】
Main ingredient

鸭肠（1000克）
Duck intestine (1000 grams, about 2.2 lbs)

【辅料】
Supplement ingredients:

小苏打（约2克）
Baking soda (about 2 grams)

干淀粉（约50克）
Starch (about 50 grams)

大蒜（约20克）
Garlic (about 20 grams)

红泡椒（20克）
Red fermented pepper (about 20 grams)

老姜（20克）
Ginger (20 grams)
小米辣（几个）
Xiao Mi La pepper (a few)

二荆条（几个）
Er Jing Tiao pepper (a few)

仔姜（1小块）
Baby ginger (1 nugget)

芹菜（几根）
Chinese celery (a few)

小葱头（几根）
Spring onion (a few)

植物油（适量）
Vegetable oil (to your judgment)

明油（少许）
Cold oil (small amount)

【调味料】
Seasonings
食用盐（适量）
Salt (to your judgment)

料酒（适量）
Cooking wine (to your judgment)

胡椒粉（适量）
White pepper powder (to your judgment)

白糖（少许）
Sugar (little)

生抽酱油（5克）
Light soy sauce (5 grams)

陈醋（约1克）
Dark vinegar (1 gram)

豆瓣酱（4克）
Fermented lava bean paste (4 grams)

老抽（1克）
Dark soy sauce (1 gram)

字幕
0:00:00.340,0:00:01.420
哈喽大家好 我是王刚
Hello everyone, I am Wang Gang.

0:00:01.420,0:00:03.620
本期视频我给大家分享一道家常菜
Today I share a home cooking dish with you.

0:00:04.360,0:00:05.680
爆炒鸭肠
Stir fry duck intestine

0:00:05.780,0:00:08.340
首先我们准备新鲜鸭肠1000克
First, we prepare fresh duck intestine about 1000 grams

0:00:08.420,0:00:11.075
然后将鸭肠中的黄油和杂质刮干净备用
Then we clean the duck fat and impurities

0:00:11.512,0:00:14.376
同学们鸭肠的最终出肉率仅仅为百分之三十五
Because duck intestine will shrink to only 35%

0:00:14.690,0:00:16.289
所以必须将料准备足
So we must prepare an adequate amount.

0:00:16.593,0:00:19.048
黄油刮干净之后开始下一步开始准备清洗
After cleaning the yellow fat, we then prepare to wash it

0:00:19.486,0:00:21.693
首先我们在盆中加入适量的食用盐（约50克）
First, we add some salt (about 50 grams)

0:00:24.900,0:00:26.403
加入小苏打1小撮（约2克）
Add a little bit of baking soda (about 2 grams)

0:00:27.183,0:00:28.430
加入适量的干淀粉（约50克）
Some starch (about 50 grams)

0:00:31.389,0:00:32.568
加入适量的料酒
Then some cooking wine 

0:00:35.613,0:00:37.954
然后我们用手将鸭肠抓拌5分钟
And then we hand mix the combined ingredient

0:00:38.097,0:00:40.513
这一步的目的是充分去除鸭肠的黏液
In order to get rid of the slime that the intestine has

0:00:40.789,0:00:43.158
加小苏打的目的是让鸭肠保持脆度
Baking soda will make the intestine crispy

0:00:43.311,0:00:46.194
5分钟之后将鸭肠放入清水中清洗干净备用
After 5 minutes, rinse the intestine well.

0:00:46.451,0:00:49.752
同学们必须多清洗几遍直到水清为止
We must rinse it a few times until it is clean.

0:01:01.655,0:01:03.777
清洗干净之后捞出挤干水份备用
Then drain it completely

0:01:05.904,0:01:08.420
然后将鸭肠每一根拉直摆放整齐
Carefully arrange every intestine straight and nice

0:01:13.615,0:01:16.765
摆放整齐之后将其切成15厘米左右的小段备用
Then cut them into 15 centimeters (6 inches) sections.

0:01:17.078,0:01:20.352
鸭肠必须切长一些否则受热收缩之后成菜难看
Cooked duck intestine will shrink, so cut into longer sections now

0:01:28.936,0:01:30.477
下一步开始准备辅料
Next, let’s prepare the supplement ingredients.

0:01:30.477,0:01:32.952
准备大蒜几颗拍散之后剁碎备用（约20克）
Crush then mince some garlic (about 20 grams)

0:01:40.375,0:01:42.593
准备红泡椒20克切成小粒备用
Dice fermented red pepper (about 20 grams)

0:01:47.614,0:01:49.949
准备老姜20克拍散之后剁碎备用
Crush and mince some ginger (about 20 grams)

0:01:57.119,0:01:59.556
准备几个小米辣和二荆条切碎备用
Dice a few Xiao Mi La pepper and Er Jing Tiao pepper 

0:01:59.556,0:02:01.486
不能吃辣的同学可以不加
If you don’t eat hot and spicy, you can skip this.

0:02:09.577,0:02:11.566
准备仔姜1小块切成丝备用
Cut a small nugget of baby ginger long and thin strips (julienne)

0:02:17.598,0:02:19.552
准备芹菜几根切成小段备用
Cut a few Chinese celeries into sections.

0:02:26.411,0:02:28.827
最后准备小葱头几根切成小段备用
And last, cut some baby spring onions into small sections.

0:02:29.023,0:02:30.686
下一步开始提前调味
Next, we will season the supplement ingredients before cooking.

0:02:30.686,0:02:33.103
首先我们在辅料碗中加入食用盐1克
First, we add 1 gram of salt into the bowl of supplement ingredients 

0:02:33.298,0:02:34.775
加入胡椒粉1小勺（约0.5克）
1 teaspoon of white pepper powder (about 0.5 gram)

0:02:35.197,0:02:36.701
加入少许白糖提鲜
Add a small amount of sugar

0:02:37.018,0:02:38.475
加入生抽酱油5克
Light soy sauce 5 grams

0:02:40.395,0:02:41.586
加入少许陈醋（约1克）
Dark vinegar 1 gram

0:02:42.269,0:02:43.367
下一步开始制作	
Now we are ready to cook


0:02:43.746,0:02:46.682
首先我们在锅中加入适量的清水开大火烧开
First, we boil some water with high heat

0:02:47.651,0:02:49.177
中途加入适量的料酒
During this time, add some cooking wine

0:02:53.166,0:02:56.264
大火烧开之后将处理好的鸭肠下锅焯水10秒钟
When the water is boiling, add the duck intestine and parboil for 10 seconds

0:02:56.385,0:02:58.373
这一步的目的是将鸭肠烫卷（约6成熟）
This is to cook it up to 60%, and it will curl

0:03:05.646,0:03:07.071
下一步我们开始制作
Then we will do the stir-frying

0:03:07.414,0:03:08.743
首先我们把锅烧热
Heat the wok first

0:03:09.208,0:03:11.312
锅烧热之后加入适量的油滑锅
Then add some oil to coat the wok

0:03:14.459,0:03:16.274
滑好锅之后将热油倒出
After the coating, pour out the heated oil

0:03:17.730,0:03:19.140
再加入适量的底油
Then add some cold oil

0:03:21.873,0:03:24.555
油温6成热之后加入姜蒜粒和泡椒爆香
When the oil is 60% heated, add ginger, garlic, and fermented pepper and fry to get the aroma

0:03:29.155,0:03:32.084
中途再加入豆瓣酱4克炒香炒出红油
Add 4 grams of bean paste and stir fry it till you see the red oil

0:03:35.883,0:03:39.182
豆瓣酱炒香之后将焯好水的鸭肠下锅翻炒几下
When you smell the bean paste aroma, add the duck intestine and stir fry

0:03:49.287,0:03:50.917
翻炒均匀之后开始调味
When the intestine is evenly coated with current ingredients, we’ll start to add spice and seasonings

0:03:51.372,0:03:53.615
锅中加入适量的白糖和胡椒粉调味
Add some sugar and white pepper powder

0:03:56.332,0:03:58.159
加入料酒5克从锅边淋入
Add cooking wine 5 grams from the side of the wok

0:03:59.313,0:04:01.070
最后加入老抽1克调底色
Add dark soy sauce 1 gram to add color

0:04:01.583,0:04:03.203
然后开中火翻炒几下
Turn the burner to mid-heat and stir fry a bit more

0:04:07.467,0:04:09.768
翻炒均匀之后再加入准备好的辅料（辣椒，仔姜丝，芹菜）.
When it is evenly coated, add the supplement ingredients. (pepper, young ginger, Chinese celery)

0:04:17.730,0:04:21.163
开中火翻炒至断生之后再加入适量的水淀粉勾成薄芡
With mid-heat, half cook the supplement ingredients then add a little starch water

0:04:25.469,0:04:28.241
最后加入少许明油翻炒均匀即可出锅装盘
Last, add a little cold oil and fry it evenly, then serve.

0:04:35.440,0:04:38.240
一道非常美味的爆炒鸭肠就制作完成
We now get a very tasty stir fry duck intestine.

0:04:44.700,0:05:03.880
下面开始技术总结
Next, tips for cooking.

第一，	最好选择新鲜鸭肠，冰冻鸭肠口感略低
First, fresh duck intestine is the best.  Frozen ones taste not as crispy.

第二，	鸭肠必须加盐淀粉料酒多抓洗几遍，否则会有腥味
Second, duck intestine must be thoroughly cleaned with salt, starch, and cooking wine, and to hand mix, in order to get rid of the unpleasant smell.

第三，	辅料下锅之前先调味可以减少翻炒的时间
Third, in order to shorten the stir fry time, it is better to season the supplement ingredients first.

第四，	最后可以勾薄芡也可以不勾芡
Fourth, you can skip adding the starch water in the last step if you prefer so.

爆炒鸭肠的技术总结完毕
That completes the tips for stir fry duck intestine.
