### ISSUE TITLE
[老饭骨] 珊瑚白菜 - https://www.youtube.com/watch?v=wnOCSeWBBGo

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#859]
**视频链接**：https://www.youtube.com/watch?v=wnOCSeWBBGo

# 请翻译以下全部内容

标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•珊瑚白菜】素食主义者看过来！集齐甜辣酸爽脆五种口感的珊瑚白菜，不得不学！

简介
小友们好，今天大爷做的这道珊瑚白菜又是一道老菜，咱大爷可真是一个“宝藏男孩”啊。有不少朋友们在评论里留言想看素菜，今儿就来了！
这道菜口感丰富，甜辣酸爽脆，集五种口感于一体。最关键的是做完以后还要放入密封盒冷藏一天，才算齐活！
细心的小友们可能发现了，前两天教大家的乾隆白菜用的是白菜叶儿，今天这道珊瑚白菜用的是帮儿，咱老饭骨真是会过日子的人，一点儿都不糟尽。
顺便给大家整理一下之前教的几种白菜做法，这白菜可真有门道勒！
乾隆白菜：https://www.youtube.com/watch?v=CvU8cmkxOUA
开水白菜：https://www.youtube.com/watch?v=Pn0PyUe5tx8
黄金白菜卷：https://www.youtube.com/watch?v=QHQB-GNjcLA

字幕
本期视频需自行制作时间轴及中文对照稿

**Comment by WuStevenShengyang** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•珊瑚白菜】素食主义者看过来！集齐甜辣酸爽脆五种口感的珊瑚白菜，不得不学！
State Banquet Master Chef: Coral Napa Cabbage. Dear vegetarians: sweet, sour, and spicy Coral Napa Cabbage. You have to try it!

简介
小友们好，今天大爷做的这道珊瑚白菜又是一道老菜，咱大爷可真是一个“宝藏男孩”啊。有不少朋友们在评论里留言想看素菜，今儿就来了！
Hey friends, Da Ye will make us Coral Napa Cabbage today. He is such a treasure boy. Many friends were suggesting us to make vegetable dish, here it comes!
这道菜口感丰富，甜辣酸爽脆，集五种口感于一体。最关键的是做完以后还要放入密封盒冷藏一天，才算齐活！
This dish is really flavorful. It's sweet, sour, and spicy; and the napa cabbage is crunchy. The key is to marinate it overnight!
细心的小友们可能发现了，前两天教大家的乾隆白菜用的是白菜叶儿，今天这道珊瑚白菜用的是帮儿，咱老饭骨真是会过日子的人，一点儿都不糟尽。
If you have been watching our previous videoS, we have taught you how to make Qianlong Napa Cabbage with Napa Cabbage leaves. This Coral Nappa Cabbage will use the stems. We won't wasting any parts of the napa cabbage.
顺便给大家整理一下之前教的几种白菜做法，这白菜可真有门道勒！
Here is a list of all the Napa Cabbage dish:

乾隆白菜：https://www.youtube.com/watch?v=CvU8cmkxOUA
Qianlong Napa Cabbage: https://www.youtube.com/watch?v=CvU8cmkxOUA
开水白菜：https://www.youtube.com/watch?v=Pn0PyUe5tx8
Napa Cabbage in "boiled water": https://www.youtube.com/watch?v=Pn0PyUe5tx8
黄金白菜卷：https://www.youtube.com/watch?v=QHQB-GNjcLA
Golden Napa Cabbage Roll: https://www.youtube.com/watch?v=QHQB-GNjcLA

字幕
本期视频需自行制作时间轴及中文对照稿

0:00:00.000,0:00:02.880
您又做大白菜？我來個珊瑚白菜。
Are you cooking napa cabbage again? I am going to make Coral Napa Cabbage.

0:00:02.880,0:00:05.560
這葉兒讓我使了，白菜幫他不能糟盡啊
I have already used the leaves, but we won't waste the stems either.

0:00:06.700,0:00:08.720
冬天的白菜最好，它脆
Napa cabbage tastes the best in winter. It's crunchy.

0:00:08.780,0:00:11.760
我們呢，把這白菜切成條
We will slice the cabbage into strips first.

0:00:11.760,0:00:14.820
切完了一腌，回家一吃
And we will marinate them.

0:00:16.480,0:00:20.900
這個別給切斷了，我們浮浮的
Don't cut the cabbage all the way through though.

0:00:21.200,0:00:24.420
個到這兒，這麽長，對
See, it's about this long.

0:00:24.560,0:00:28.200
今天這個菜出不了，得燉一天
We won't be able to eat this dish today. It has to be marinated overnight.

0:00:28.200,0:00:30.000
我們擱盆裏邊腌上
We will put the cabbage in the bowl and marinate overnight.

0:00:30.120,0:00:34.620
等明天裝盤的時候，拿筷子挑出來
And tomorrow we can just use chopsticks to take them out.

0:00:34.625,0:00:37.575
咔一到，一刀兩段
By the time we will cut them in half completely.

0:00:37.580,0:00:38.820
這個吃起來就好吃了
And it will taste good.

0:00:39.100,0:00:40.200
這個菜叫一刀兩段
This dish is, therefore, also called: Chop them in half.

0:00:40.840,0:00:44.480
我現在先給他撒點鹽，咱們一層一層撒
We will add some salt first, layer by layer.

0:00:48.820,0:00:51.940
我們現在給它腌上，腌十五分鐘
Now, we need to marinate them for 15 minutes.

0:00:52.120,0:00:54.200
然後現在我先炒一個汁
I will make the sauce at the same time.

0:00:57.480,0:01:00.720
來點兒油
Add some vegetable oil.

0:01:01.260,0:01:03.300
你看看二伯，精誠合作啊
Er Bai is cooperating so well with you!

0:01:04.420,0:01:10.080
還得來，這個油吃白菜，油得大一點
Add more, the napa cabbage will absorb lots of oil

0:01:10.260,0:01:13.140
別等到油太熱了，下鍋
We can put them in now. We don't have to heat up the oil all the way.

0:01:13.720,0:01:17.780
買不着辣椒絲，把乾辣椒泡軟了
If you can't buy chili strips, you can soak the dried chilis in water,

0:01:18.240,0:01:20.400
拿剪子較成絲
and cut them into strips with a scissor when they turn soft.

0:01:23.700,0:01:24.900
喔 酸香酸香
Wow, sour and aromatic.

0:01:25.060,0:01:26.180
你看大爺，很有經驗
Da Ye has lots of cooking experience.

0:01:26.820,0:01:28.620
大爺你看見沒有，辣椒他較
He uses scissor to cut chilis.

0:01:28.900,0:01:30.140
要是切可費了勁了
It would be much harder to use a knife.

0:01:30.680,0:01:32.820
個點葱薑絲
Add some spring onion and ginger strips.

0:01:35.060,0:01:36.180
來點礦泉水
Some spring water.

0:01:36.840,0:01:37.920
忘情水
No love water (same syllable as "spring water").

0:01:38.280,0:01:39.360
加點糖一塊熬
Add some sugar.

0:01:43.360,0:01:45.000
大爺補點 再來點水
Da Ye, we need more water.

0:01:47.020,0:01:48.900
這可不加什麽調料了
We won't add any extra seasoning,

0:01:49.640,0:01:50.380
就是糖
just sugar.

0:01:50.800,0:01:53.940
要想甜，必擱鹽
If you want sweetness, you have to add salt.

0:01:56.900,0:01:58.900
鹽沒少擱啊
That's a lot of salt.

0:01:59.160,0:02:00.420
鹽我擱的少 
Actaully, not a lot,

0:02:00.800,0:02:02.660
因爲我們殺這白菜還有味呢
since we have already put salt into our napa cabbage.

0:02:03.120,0:02:04.120
鹽擱了6克啊
We have just add 6 grams of salt.

0:02:04.760,0:02:05.760
這時候加糖
Now, let's add sugar.

0:02:06.465,0:02:08.115
我們家糖全讓你們倆用光了
You guys have used all of the sugar in my house.

0:02:08.840,0:02:11.280
誰説得你也沒少用啊
Sounds as if you didn't use any of them.

0:02:13.220,0:02:16.720
這熬到什麽程度呢 要冒泡
We have to wait until it starts bubbling,

0:02:16.915,0:02:19.925
要起黏兒 有點起拉黏
and a little sticky.

0:02:19.925,0:02:21.580
然後我們最後在個點白醋
Lastly, we will add some white vinegar.

0:02:24.640,0:02:29.160
這個珊瑚白菜現在基本上上有好多酒店都不買了
Lots of restaurants don't even make Coral Napa Cabbage nowadays.

0:02:31.040,0:02:34.060
過去是咱們那年代賣的 現在這年代不賣了
They made this dish back in our time, but not anymore.

0:02:37.520,0:02:38.020
冒泡了吧
It's bubbling.

0:02:38.520,0:02:42.180
這叫珊瑚白菜
This is Coral Nappa Cabbage.

0:02:42.960,0:02:45.460
好啦 這回差不多了
Okay, we are almost done.

0:02:48.060,0:02:48.740
嘿漂亮啊
So beautiful.

0:02:48.920,0:02:50.580
像不像珊瑚 像
Doesn't it look lie coral? Yes.

0:02:50.880,0:02:53.560
往底下放點涼水 給它鎮上
We will use cold water to cool it.

0:02:54.060,0:02:55.640
三叔家是要啥有啥啊
San Shu has everything in his house.

0:02:56.140,0:03:00.020
它涼了給他個點醋 白醋
We can also drizzle some white vinegar.

0:03:00.415,0:03:03.345
這樣呢它涼的就快了
To make it cool faster.

0:03:06.600,0:03:10.080
待會呢找一塊乾毛巾
Then, we will get a towel.

0:03:10.640,0:03:12.540
攥白菜 對
To grasp the cabbage.

0:03:12.765,0:03:16.075
他還得要求這整齊 別把白菜的形狀給破壞了
But we can't break the shape of the cabbage.

0:03:16.080,0:03:16.820
白菜啊
Napa Cabbage.

0:03:17.100,0:03:18.640
小珊瑚汁多漂亮啊
Coral sauce is just adorable.

0:03:19.400,0:03:20.760
這叫珊瑚白菜
This is what we call Coral Napa Cabbage.

0:03:24.320,0:03:25.580
好 真漂亮
Okay, so beautiful.

0:03:28.220,0:03:30.520
珊瑚白菜 又是一個菜
Coral Napa Cabbage.

import ending.srt 00:03:47,000
