### ISSUE TITLE
【美食作家王刚】嫩炒猪肝 - https://youtu.be/HzqI_t_VLr8

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#862]
**视频链接**：https://youtu.be/HzqI_t_VLr8

视频时长 6:23，预计发布时间为北京时间4月2日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：自贡川味“嫩炒猪肝”的详细做法，口感鲜嫩入味，真的特别嫩！

简介
大家好，看到前段时间给大家分享的“小炒猪肝”下面不少朋友留言喜欢吃嫩一点的猪肝，正好四伯摆摊留了一块新鲜的猪肝，就来给大家分享一下“嫩炒猪肝”。猪肝这种食材无论是嫩炒还是爆炒或者盐焗做卤味都别有一番风味，所以还是要看个人口味，但需要特别注意的是如果想做嫩炒就一定要用最新鲜的猪肝，不可以用隔夜的，并且切好之后需清洗干净以免有异味（而小炒老猪肝切好之后不需要清洗，就吃猪肝的原味）。因为四伯的牙口不太好，所以这道嫩炒特别符合他的口味，大家有机会也可以在家尝试！

字幕
0:00:00.525,0:00:06.200
今天我伯爷摆摊留了一块猪肝 留回来专门炒

0:00:06.325,0:00:07.100
先洗一下

0:00:07.625,0:00:11.375
洗一下一会儿那个纵纵就要散了

0:00:12.200,0:00:14.100
今天我们做一下嫩猪肝

0:00:17.925,0:00:19.800
好 我们来开始切这个猪肝

0:00:20.175,0:00:22.600
我们炒嫩猪肝的话就要切薄一点

0:00:22.900,0:00:24.525
炒老猪肝的话就切厚一点

0:00:24.525,0:00:27.525
因为老猪肝切厚点的话它能够经得起炒

0:00:29.325,0:00:34.625
我们切的这个猪肝大概的话是2毫米 不到2毫米

0:00:35.200,0:00:38.668
我们切这个猪肝切着切着的话给它翻过来

0:00:39.120,0:00:40.364
翻过来切另外一面

0:00:40.364,0:00:43.359
你看嘛 这一面的话肉就暴露出来了就更好切

0:00:43.359,0:00:43.677
是啊

0:00:45.644,0:00:48.442
好 我们这个猪肝切好了放到盆里面洗一下

0:00:48.527,0:00:54.111
炒这个嫩猪肝你必须要切得薄必须要清理一哈清洗干净

0:00:54.379,0:00:54.783
嗯

0:00:55.039,0:00:57.727
这个血水要把它弄来洗干净

0:00:59.987,0:01:03.262
好 我们这个洗一下然后把它抓起来沥干水分

0:01:03.433,0:01:04.251
多洗几遍

0:01:05.937,0:01:07.049
再洗一道

0:01:08.869,0:01:13.390
这哈就是第三遍了 这哈水就不浑了

0:01:18.912,0:01:21.124
好 我们这个猪肝已经洗了四五遍了

0:01:21.356,0:01:23.225
现在把它水挤干

0:01:23.787,0:01:27.648
我们腌制前猪肝的水挤不干的话这个味道进不去

0:01:27.941,0:01:31.850
一下锅了这个味道就跟水一样就流出来了

0:01:32.278,0:01:34.428
如果猪肝里面水分过多 

0:01:35.161,0:01:40.867
在没挤干的情况下你们放那个淀粉啊放蛋清给它码味

0:01:40.928,0:01:42.602
一下锅炒的话会脱浆

0:01:42.907,0:01:46.145
挤干水分这个是我们的一个规矩

0:01:47.525,0:01:54.624
如果我们炒菜不守规矩的话可能这个菜做出来跟你想象中有很大的距离

0:01:54.966,0:01:56.579
现在我们开始腌猪肝

0:01:56.640,0:01:58.521
腌猪肝的话盐少放一点

0:01:58.973,0:02:02.626
因为猪肝有点敏感 盐放多了会有点咸

0:02:03.836,0:02:07.623
我们第一步首先要把盐放下去朝一个方向搅

0:02:08.356,0:02:13.084
只有出了浆的猪肝它才会把其他的东西调料吸在上面

0:02:13.146,0:02:18.094
要不然的话这个猪肝一下锅水分没有打干它容易脱浆

0:02:19.034,0:02:21.527
现在我们这个猪肝已经把水分收进去了

0:02:21.979,0:02:24.752
收进去了之后开始来放一点胡椒粉

0:02:24.923,0:02:25.681
开始放味道了

0:02:27.147,0:02:27.929
放一点胡椒粉

0:02:28.503,0:02:29.627
少放点这个

0:02:29.896,0:02:30.885
好 少放点嘛

0:02:32.400,0:02:33.744
然后放这个老抽

0:02:34.208,0:02:36.652
放一点老抽调这个猪肝的颜色

0:02:39.853,0:02:43.139
猪肝的话可以稍微颜色重一点没关系

0:02:44.801,0:02:46.389
好 咱们这个颜色就出来了

0:02:47.806,0:02:51.594
然后再放点这个蚝油 少放一点因为蚝油带咸味

0:02:52.461,0:02:54.111
主要是增加这个咸鲜味

0:02:56.041,0:02:59.352
好 这个我们搅拌好了之后再加一点淀粉

0:03:00.122,0:03:04.105
稍微可以多那么一点点 放一勺半

0:03:05.546,0:03:12.571
淀粉就是把所有的水料调料把它吸在这个猪肝表面

0:03:14.599,0:03:15.711
好 我们最后一步

0:03:16.017,0:03:20.000
这个油加一点进去 这一步非常的关键

0:03:20.415,0:03:24.483
大家这个猪肝腌好了之后最后加点油给它放一下

0:03:24.801,0:03:27.379
下锅的时候这个猪肝很容易就自动散开

0:03:27.452,0:03:28.759
它不会说就黏成一团

0:03:29.236,0:03:30.885
然后这个也不容易脱浆

0:03:32.461,0:03:33.634
OK 现在我们腌好了

0:03:34.257,0:03:36.212
今天拿这个葱黄来炒 四伯爷

0:03:36.811,0:03:37.642
要得

0:03:37.959,0:03:41.124
我们给它切马耳朵的斜刀

0:03:50.714,0:03:53.671
我们炒猪肝的蒜就随便拍一下就可以 不用剁太碎

0:03:54.502,0:03:55.503
再放点泡椒

0:03:56.322,0:03:59.499
四川人炒猪肝不放泡椒要遭别人说的噶

0:03:59.853,0:04:03.188
嗯 说你海椒都没得压不住腥味不好吃

0:04:07.416,0:04:10.555
好 现在我们再做最后一步

0:04:11.716,0:04:13.732
先给这个辅料调味 

0:04:14.147,0:04:16.933
这个是我们四川的特殊手法 先调味

0:04:17.397,0:04:18.375
我们放点胡椒粉 

0:04:20.085,0:04:23.249
然后再放一点鸡精再放点酱油 

0:04:24.593,0:04:27.721
好 再加点豆瓣酱就可以炒了

0:05:05.644,0:05:06.475
四伯爷尝哈看

0:05:06.475,0:05:07.183
告哈看嘛

0:05:07.660,0:05:08.405
非常嫩

0:05:09.981,0:05:11.398
真的很嫩

0:05:11.398,0:05:13.781
这个吃这个猪肝要有吃法

0:05:14.599,0:05:16.962
咋子说安 要蘸点这个汤汤

0:05:16.962,0:05:19.828
汤汤里头才是油 它才好吃

0:05:21.588,0:05:25.839
这个猪肝下锅到起锅十五秒钟都不到

0:05:26.463,0:05:27.086
很嫩很嫩

0:05:27.770,0:05:30.653
咱们炒这个猪肝的时候油尽量可以稍微多一点点

0:05:31.423,0:05:34.257
因为要把这个锅里面的整体温度提升起来

0:05:34.709,0:05:39.022
这个猪肝下去了之后炒几下 然后这个辅料下去翻几下就可以出来

0:05:41.234,0:05:44.948
特别的嫩 很适合像我四伯这种

0:05:45.094,0:05:48.246
我们这种牙口不好的吃起都吃得动

0:05:50.030,0:05:51.056
很有好嫩 安逸

0:05:56.420,0:06:00.696
而且大家可以看一下你把猪肝的水分挤干了之后再腌

0:06:01.075,0:06:02.761
下锅炒它是不会脱浆的

0:06:03.262,0:06:08.295
这就没有黏黏糊糊的 有些炒的猪肝糊起糊起的跟啥子样

0:06:08.307,0:06:09.468
跟烙的锅巴样

0:06:10.702,0:06:12.474
这样子多舒服样 多清亮样

0:06:14.001,0:06:15.296
好了 本期视频就到这里

0:06:16.261,0:06:16.591
拜拜


```

**Comment by Nina-nana** [comment]
认领

**Comment by Nina-nana** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：自贡川味“嫩炒猪肝”的详细做法，口感鲜嫩入味，真的特别嫩！
Sichuan-Zigong Style “Nen Chao Zhu Gan(tender stir-fry pork liver)”

简介
大家好，看到前段时间给大家分享的“小炒猪肝”下面不少朋友留言喜欢吃嫩一点的猪肝，正好四伯摆摊留了一块新鲜的猪肝，就来给大家分享一下“嫩炒猪肝”。猪肝这种食材无论是嫩炒还是爆炒或者盐焗做卤味都别有一番风味，所以还是要看个人口味，但需要特别注意的是如果想做嫩炒就一定要用最新鲜的猪肝，不可以用隔夜的，并且切好之后需清洗干净以免有异味（而小炒老猪肝切好之后不需要清洗，就吃猪肝的原味）。因为四伯的牙口不太好，所以这道嫩炒特别符合他的口味，大家有机会也可以在家尝试！
Hello everyone, after seeing the "Tasty Pork Liver" that I shared with yours a few days ago, that video had some comments said like to eat a tender pork liver. It happens that my uncle set up stall and leave piece of pork liver. Let me show you how to cook "Nen Chao Zhu Gan (tender stir-fry pork liver)".
 It is delicious whether make by tender or stir-fried, salted, braised. So it depends on your personal taste, but you need to pay attention to the fresh pork liver, if you want to make by tender stir-fry must be using fresh pork liver, can't use overnight pork liver. After cutting  you need to wash it to avoid odor( and for "tasty pork liver-old pork liver” this dish does not need to be washed after cutting pork liver, Just eat the original taste of pork liver). 
Because my uncle teeth are not very good, So this tender stir-fry is particularly suitable for his taste. 
Everyone has the opportunity to try it at home!

字幕
0:00:00.525,0:00:06.200
今天我伯爷摆摊留了一块猪肝 留回来专门炒
Today, my uncle set up a stall and specially leave a piece of pork liver to take home and stir-fry.

0:00:06.325,0:00:07.100
先洗一下
First, wash it 

0:00:07.625,0:00:11.375
洗一下一会儿那个纵纵就要散了
Wash it for a while, and it structure going to break up.
(Wash it, later structure will be break up.)

0:00:12.200,0:00:14.100
今天我们做一下嫩猪肝
Today, we make Nen Zhu Gan(tender stir-fry pork liver).

0:00:17.925,0:00:19.800
好 我们来开始切这个猪肝
Okay Let us cut this pork liver.

0:00:20.175,0:00:22.600
我们炒嫩猪肝的话就要切薄一点
We make Nen Zhu Gan should cut it thin.


0:00:22.900,0:00:24.525
炒老猪肝的话就切厚一点
Make old pork liver should cut it thick.

0:00:24.525,0:00:27.525
因为老猪肝切厚点的话它能够经得起炒
Because the old pork liver if it's cut thick can frying long time.


0:00:29.325,0:00:34.625
我们切的这个猪肝大概的话是2毫米 不到2毫米
The pork liver we cut it about 2 mm  less than 2 mm.

0:00:35.200,0:00:38.668
我们切这个猪肝切着切着的话给它翻过来
Let ’s cut this pork liver and turn it over.

0:00:39.120,0:00:40.364
翻过来切另外一面
Turn it over and cut the other side

0:00:40.364,0:00:43.359
你看嘛 这一面的话肉就暴露出来了就更好切
You see, at this side the meat will be exposed and cut it more easier.

0:00:43.359,0:00:43.677
是啊
Yes

0:00:45.644,0:00:48.442
好 我们这个猪肝切好了放到盆里面洗一下
Well Our pork liver is cut finished and put in the basin for washing.

0:00:48.527,0:00:54.111
炒这个嫩猪肝你必须要切得薄必须要清理一哈清洗干净
Make Nen Zhu Gan  You have to cut it thin and clean it up.

0:00:54.379,0:00:54.783
嗯
Um

0:00:55.039,0:00:57.727
这个血水要把它弄来洗干净
The pork blood need wash clear.

0:00:59.987,0:01:03.262
好 我们这个洗一下然后把它抓起来沥干水分
OK, let's wash it clear and drain the water


0:01:03.433,0:01:04.251
多洗几遍
Wash a few times

0:01:05.937,0:01:07.049
再洗一道
Wash it again


0:01:08.869,0:01:13.390
这哈就是第三遍了 这哈水就不浑了
This is the third time. The water is not muddy.

0:01:18.912,0:01:21.124
好 我们这个猪肝已经洗了四五遍了
OK, our pork liver has been washed four or five times.

0:01:21.356,0:01:23.225
现在把它水挤干
Now squeeze it and let water out.


0:01:23.787,0:01:27.648
我们腌制前猪肝的水挤不干的话这个味道进不去
Before we marinate, if the water in the liver is not squeezed, this taste will not go in.


0:01:27.941,0:01:31.850
一下锅了这个味道就跟水一样就流出来了
When you put it in the pot, this is tasting just flows out like water

0:01:32.278,0:01:34.428
如果猪肝里面水分过多 
If there is too much water in the liver

0:01:35.161,0:01:40.867
在没挤干的情况下你们放那个淀粉啊放蛋清给它码味
If you haven't squeezed it, you can put starch or egg white to keep it have marinate.

0:01:40.928,0:01:42.602
一下锅炒的话会脱浆
if you stir-fry it, the marinade material will be separate with liver.

0:01:42.907,0:01:46.145
挤干水分这个是我们的一个规矩
Squeezing water is one of our rules

0:01:47.525,0:01:54.624
如果我们炒菜不守规矩的话可能这个菜做出来跟你想象中有很大的距离
If we don’t follow the rules, we may make this dish far away from what your imagination.

0:01:54.966,0:01:56.579
现在我们开始腌猪肝
Now we're going to marinate pork liver

0:01:56.640,0:01:58.521
腌猪肝的话盐少放一点
Put less salt in the pork liver

0:01:58.973,0:02:02.626
因为猪肝有点敏感 盐放多了会有点咸
Because pork liver is a little sensitive. If you put too much salt will be more salty.

0:02:03.836,0:02:07.623
我们第一步首先要把盐放下去朝一个方向搅
Our first step is to put the salt down and stir in one direction.

0:02:08.356,0:02:13.084
只有出了浆的猪肝它才会把其他的东西调料吸在上面
It absorb other dressing on it only when pork liver squeezed until without water.


0:02:13.146,0:02:18.094
要不然的话这个猪肝一下锅水分没有打干它容易脱浆
Otherwise, when the pork liver put in the pot, the marinade material will be easily separate with pork liver.


0:02:19.034,0:02:21.527
现在我们这个猪肝已经把水分收进去了
Now our pork liver has absorbed the water.

0:02:21.979,0:02:24.752
收进去了之后开始来放一点胡椒粉
After the liver has absorbed the water put in some pepper powder.

0:02:24.923,0:02:25.681
开始放味道了
Start to give seasoning.

0:02:27.147,0:02:27.929
放一点胡椒粉
Put some pepper powder.

0:02:28.503,0:02:29.627
少放点这个
Put less of this.

0:02:29.896,0:02:30.885
好 少放点嘛
Ok put little.

0:02:32.400,0:02:33.744
然后放这个老抽
And then put this dark soy sauce.

0:02:34.208,0:02:36.652
放一点老抽调这个猪肝的颜色
Put a little dark soy sauce to adjust the color of this pork liver.


0:02:39.853,0:02:43.139
猪肝的话可以稍微颜色重一点没关系
It doesn't matter if the color of pork liver is a little heavier.

0:02:44.801,0:02:46.389
好 咱们这个颜色就出来了
Ok this color is come out.

0:02:47.806,0:02:51.594
然后再放点这个蚝油 少放一点因为蚝油带咸味
Then put some oyster sauce, put a little because it's salty.

0:02:52.461,0:02:54.111
主要是增加这个咸鲜味
Mainly to increase the savory taste

0:02:56.041,0:02:59.352
好 这个我们搅拌好了之后再加一点淀粉
OK, let's mix this all and then add some starch.

0:03:00.122,0:03:04.105
稍微可以多那么一点点 放一勺半
Can put a little more, one and a half spoons of starch.

0:03:05.546,0:03:12.571
淀粉就是把所有的水料调料把它吸在这个猪肝表面
Starch is to absorb all the water ingredients on the surface of the pork liver.

0:03:14.599,0:03:15.711
好 我们最后一步
OK Last step.

0:03:16.017,0:03:20.000
这个油加一点进去 这一步非常的关键
Add a little oil. This step is very important.

0:03:20.415,0:03:24.483
大家这个猪肝腌好了之后最后加点油给它放一下
After everyone has marinated this pork liver, add some oil at the end.

0:03:24.801,0:03:27.379
下锅的时候这个猪肝很容易就自动散开
This pork liver easily spreads out when put in the pot.

0:03:27.452,0:03:28.759
它不会说就黏成一团
It doesn't stick together

0:03:29.236,0:03:30.885
然后这个也不容易脱浆
Then this is not easy to separate with pork liver.

0:03:32.461,0:03:33.634
OK 现在我们腌好了
OK Now we marinate pork liver is finish.

0:03:34.257,0:03:36.212
今天拿这个葱黄来炒 四伯爷
Today, let's stir fry with onion(greenish yellow). Uncle.


0:03:36.811,0:03:37.642
要得
Yes.

0:03:37.959,0:03:41.124
我们给它切马耳朵的斜刀
Let's slant-cut.


0:03:50.714,0:03:53.671
我们炒猪肝的蒜就随便拍一下就可以 不用剁太碎
We can just pat the garlic of fried pork liver don't need cut garlic into mince.

0:03:54.502,0:03:55.503
再放点泡椒
Put pickled chili.

0:03:56.322,0:03:59.499
四川人炒猪肝不放泡椒要遭别人说的噶
Sichuan people fried pork liver without pickled peppers, other people will be said.

0:03:59.853,0:04:03.188
嗯 说你海椒都没得压不住腥味不好吃
Um, you don't have  pepper. It's not delicious.

0:04:07.416,0:04:10.555
好 现在我们再做最后一步
Ok now we do the last step.

0:04:11.716,0:04:13.732
先给这个辅料调味 
First, season the subsidiary material.

0:04:14.147,0:04:16.933
这个是我们四川的特殊手法 先调味
This is our special method in Sichuan, seasoning first.


0:04:17.397,0:04:18.375
我们放点胡椒粉 
We put some pepper powder.

0:04:20.085,0:04:23.249
然后再放一点鸡精再放点酱油 
And then put little bit chicken bouillon and little soy sauce.

0:04:24.593,0:04:27.721
好 再加点豆瓣酱就可以炒了
Well  add some “doubanjiang” and you can fry it.

0:05:05.644,0:05:06.475
四伯爷尝哈看
Uncle, taste it.

0:05:06.475,0:05:07.183
告哈看嘛
Taste it.

0:05:07.660,0:05:08.405
非常嫩
Very tender.

0:05:09.981,0:05:11.398
真的很嫩
Really tender.

0:05:11.398,0:05:13.781
这个吃这个猪肝要有吃法
There must be have ways to eat this pork liver.

0:05:14.599,0:05:16.962
咋子说安 要蘸点这个汤汤
To dip this soup


0:05:16.962,0:05:19.828
汤汤里头才是油 它才好吃
It's the oil in the soup that makes it delicious

0:05:21.588,0:05:25.839
这个猪肝下锅到起锅十五秒钟都不到
The pork liver was put into the pot until it was out is under 15 seconds.

0:05:26.463,0:05:27.086
很嫩很嫩
Very tender, very tender.


0:05:27.770,0:05:30.653
咱们炒这个猪肝的时候油尽量可以稍微多一点点
Let's fry the pork liver, try to put a little more oil in the pot.

0:05:31.423,0:05:34.257
因为要把这个锅里面的整体温度提升起来
Because we need to raise the overall temperature in this inside of pot.

0:05:34.709,0:05:39.022
这个猪肝下去了之后炒几下 然后这个辅料下去翻几下就可以出来
The pork liver goes down stir-fry it for a few times, and then turn the subsidiary material down stir-fry it for a few times to out of the pot.

0:05:41.234,0:05:44.948
特别的嫩 很适合像我四伯这种
Very tender  Very suitable for my uncle kind of people.

0:05:45.094,0:05:48.246
我们这种牙口不好的吃起都吃得动
People like us who have bad teeth can eat it.

0:05:50.030,0:05:51.056
很有好嫩 安逸
Very tender nice

0:05:56.420,0:06:00.696
而且大家可以看一下你把猪肝的水分挤干了之后再腌
And everyone can see that you squeezed out the water from the pork liver and then marinated it.

0:06:01.075,0:06:02.761
下锅炒它是不会脱浆的
Stir-fry it, the marinade material is not will be separate.

0:06:03.262,0:06:08.295
这就没有黏黏糊糊的 有些炒的猪肝糊起糊起的跟啥子样
It's not sticky. Some fried pork livers are sticky.

0:06:08.307,0:06:09.468
跟烙的锅巴样
It's like a rice crust.

0:06:10.702,0:06:12.474
这样子多舒服样 多清亮样
It looks so comfortable and clear.

0:06:14.001,0:06:15.296
好了 本期视频就到这里
Ok This is it for this episode.

0:06:16.261,0:06:16.591
拜拜
Bye-bye
