### ISSUE TITLE
【美食作家王刚】醋烧鲈鱼 - https://youtu.be/b-eSvtY9KMI

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#863]
**视频链接**：https://youtu.be/b-eSvtY9KMI

视频时长 4:06，预计发布时间为北京时间4月3日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“醋烧鲈鱼”的做法，经典干烧鱼的另一种做法，回味无穷

简介
同学们好，今天和大家分享一道“醋烧鱼”，这道菜是经典川菜“干烧鱼”的一种变种，这道菜讲究用醋的酸味来综合经典的红烧味，来提升整体菜的鲜味，但其味型还保留在酱油红烧味，而非酸味。这样做出的鲈鱼味道特别鲜美，要比经典的干烧拥有更加浓厚的回味，并且醋有一定软化鱼刺的效果，希望大家喜欢本期视频！如果有想学习经典干烧鱼的朋友可以点击链接：https://www.youtube.com/watch?v=kYyFOwitBqo

本期菜品：【醋烧鲈鱼】
【主料】
鲈鱼（约750克）
【辅料】
猪肥油（约35克）
大蒜（25克）
生姜（适量）
八角（1颗）
桂皮（几小块）
香叶（1小片）
小葱头（几根）
干辣椒（适量）
玉米淀粉（适量）
植物油（适量）
水淀粉（少许）
明油（适量）
葱花（适量）
【调味料】
蚝油（5克）
晒醋（10克）
料酒（10克）
生抽酱油（10克）
食用盐（约2克）
白糖（4克）
胡椒粉（约1克）
鸡精（约1.5克）
老抽（3克）

字幕
0:00:00.140,0:00:01.260
哈喽大家好 我是王刚

0:00:01.280,0:00:03.220
本期视频我跟大家分享一道家常菜

0:00:03.740,0:00:04.800
醋烧鲈鱼

0:00:04.880,0:00:06.880
首先我们准备鲈鱼1条（约750克）

0:00:06.925,0:00:08.875
将鱼鳞去除之后破开鱼肚

0:00:12.075,0:00:14.350
去掉内脏和鱼鳃清洗干净备用

0:00:14.450,0:00:17.875
同学们也可以选用鲤鱼草鱼或者鲫鱼

0:00:19.575,0:00:20.800
下一步开始改刀

0:00:20.900,0:00:23.075
首先我们将鲈鱼切上一字花刀

0:00:23.200,0:00:25.425
刀口不能太宽否则容易烧烂

0:00:27.725,0:00:29.450
下一步开始准备辅料

0:00:29.550,0:00:32.250
准备猪肥油1小块切成颗粒备用（约35克）

0:00:36.750,0:00:39.650
准备大蒜和生姜各25克切成小粒备用

0:00:41.650,0:00:43.225
碗中加入八角1颗

0:00:43.500,0:00:44.900
加入桂皮几小块

0:00:45.425,0:00:46.900
加入香叶1小片

0:00:47.000,0:00:49.025
加入小葱头几根切碎备用

0:00:50.175,0:00:52.700
最后加入适量的干辣椒剪成小节备用

0:00:56.025,0:00:57.450
下一步开始制作

0:00:57.650,0:00:59.125
首先我们把锅烧热

0:00:59.150,0:01:00.925
锅烧热之后加入宽油

0:01:03.800,0:01:06.325
然后开大火烧开将油温烧至6成热

0:01:06.475,0:01:09.250
油温6成热之后转小火准备炸鱼

0:01:11.575,0:01:14.500
鱼下锅之前先加入适量的玉米淀粉拍打均匀

0:01:14.625,0:01:17.775
这一步的目的是防止水分流失将鱼炸得太干

0:01:22.150,0:01:24.775
然后捏着鲈鱼尾巴下锅浸炸3分钟

0:01:24.850,0:01:27.925
这一步的目的是将鲈鱼表面炸至金黄酥脆

0:01:31.550,0:01:34.075
中途需要将油均匀地淋在鱼身上面

0:01:41.075,0:01:43.250
3分钟之后将鲈鱼捞出备用

0:01:43.275,0:01:46.475
不喜欢油炸的同学也可以用少量的油直接煎

0:01:51.350,0:01:53.525
热油倒出之后下一步开始烧汁

0:01:53.750,0:01:55.975
将锅烧热之后加入适量的底油

0:01:57.625,0:02:01.225
油温4成热之后加入准备好的所有料头翻炒1分钟

0:02:01.275,0:02:03.925
这一步必须爆出猪油和将料头炒香

0:02:06.500,0:02:08.450
1分钟之后加入蚝油5克

0:02:11.050,0:02:12.525
加入晒醋10克

0:02:13.675,0:02:14.925
加入料酒10克

0:02:15.875,0:02:17.425
加入生抽酱油10克

0:02:21.900,0:02:24.925
翻炒均匀之后加入适量的清水开大火烧开

0:02:30.050,0:02:32.250
大火烧开之后开始调味

0:02:32.525,0:02:34.450
锅中加入适量的食用盐（约2克）

0:02:36.450,0:02:37.900
加入白糖2勺（4克）

0:02:41.650,0:02:43.050
加入胡椒粉1勺（约1克）

0:02:43.725,0:02:45.125
加入鸡精1勺（约1.5克）

0:02:46.500,0:02:48.075
加入老抽3克调色

0:02:50.600,0:02:53.800
最后加入炸好的鲈鱼下锅转小火烧15分钟

0:02:54.525,0:02:58.950
同学们烧鱼可以不用翻动只需要浇上热汤即可

0:03:02.225,0:03:04.900
15分钟之后将鲈鱼捞出摆盘

0:03:13.825,0:03:15.975
然后将汤汁中的料头捞出

0:03:17.975,0:03:19.525
下一步开始勾芡

0:03:19.625,0:03:22.050
锅中加入少许的水淀粉勾成薄芡

0:03:25.625,0:03:27.750
勾好芡之后再加入现剁的姜末

0:03:32.025,0:03:33.575
再加入适量的明油

0:03:35.875,0:03:38.400
最后均匀地淋在鱼身上面即可上菜

0:03:40.720,0:03:43.300
一道非常美味的醋烧鲈鱼就制作完成

0:03:47.860,0:04:05.360
下面开始技术总结
第一，醋和酒精类似，烧得时间越长挥发得越多
第二，加醋烧鱼可以软化鱼刺，此做法更适合烹制刺多的鱼
第三，最后起锅前加入适量的姜末可以增加不一样的鲜味
醋烧鲈鱼的技术总结完毕


```

**Comment by Yibing-Du** [comment]
认领

**Comment by Yibing-Du** [comment]
bot, please upload
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“醋烧鲈鱼”的做法，经典干烧鱼的另一种做法，回味无穷
Chef Wang teaches you: Vinegar braised bass, fish dish with new flavor

简介
Introduction
同学们好，今天和大家分享一道“醋烧鱼”，这道菜是经典川菜“干烧鱼”的一种变种，这道菜讲究用醋的酸味来综合经典的红烧味，来提升整体菜的鲜味，但其味型还保留在酱油红烧味，而非酸味。这样做出的鲈鱼味道特别鲜美，要比经典的干烧拥有更加浓厚的回味，并且醋有一定软化鱼刺的效果，希望大家喜欢本期视频！如果有想学习经典干烧鱼的朋友可以点击链接：https://www.youtube.com/watch?v=kYyFOwitBqo
Hi everyone, today I'll share the recipe of vinegar braised bass, a variant of classic Sichuan dish braised fish. This dish balances the classic stew fish flavor with the flavor of vinegar to enhance the overall umami taste without taking out the flavor of soy sauce. Bass cooked this way tastes fantastic because there's another layer of taste compared to the classic dish and the venigar also soften the fish bones. I hope you like this! To learn classic braised fish, check this out: https://www.youtube.com/watch?v=kYyFOwitBqo

本期菜品：【醋烧鲈鱼】
Today's dish: Vinegar Braised Bass

【主料】
Major ingredients
鲈鱼（约750克）
Bass (around 750g)

【辅料】
猪肥油（约35克）
Pork fat (around 35g)
大蒜（25克）
Garlic (25g)
生姜（适量）
Ginger (some)
八角（1颗）
Star anise (one)
桂皮（几小块）
Cinnamon (a few)
香叶（1小片）
Bay leaf (a small piece)
小葱头（几根）
Scallion (a few)
干辣椒（适量）
Dried chili pepper (some)
玉米淀粉（适量）
Corn starch (some)
植物油（适量）
Vegetable oil (some)
水淀粉（少许）
Water starch (a little)
明油（适量）
Ming You (some)
葱花（适量）
Minced scallion (some)
【调味料】
Sauce
蚝油（5克）
Oyster sauce (5g)
晒醋（10克）
Vinegar (10g)
料酒（10克）
Chinese cooking wine (10g)
生抽酱油（10克）
Light soy sauce (10g)
食用盐（约2克）
Salt (around 2g)
白糖（4克）
Sugar (4g)
胡椒粉（约1克）
Ground pepper (around 1g)
鸡精（约1.5克）
Chicken essence (around 1.5g)
老抽（3克）
Dark soy sauce (3g)

字幕
0:00:00.140,0:00:01.260
哈喽大家好 我是王刚
Hi everyone, I'm Wang Gang

0:00:01.280,0:00:03.220
本期视频我跟大家分享一道家常菜
Today I'll share the recipe of an everyday dish

0:00:03.740,0:00:04.800
醋烧鲈鱼
Vinegar braised bass

0:00:04.880,0:00:06.880
首先我们准备鲈鱼1条（约750克）
First, prepare a bass (around 750g)

0:00:06.925,0:00:08.875
将鱼鳞去除之后破开鱼肚
Remove the fish scale and cut the belly open

0:00:12.075,0:00:14.350
去掉内脏和鱼鳃清洗干净备用
Remove the insides and fish gill and rinse it

0:00:14.450,0:00:17.875
同学们也可以选用鲤鱼草鱼或者鲫鱼
You can also use carp, grass carp, or crucian carp

0:00:19.575,0:00:20.800
下一步开始改刀
Now cut the fish

0:00:20.900,0:00:23.075
首先我们将鲈鱼切上一字花刀
First we cut the fish in this pattern

0:00:23.200,0:00:25.425
刀口不能太宽否则容易烧烂
You need to keep your knife straight down or else the fish will fall apart in the wok

0:00:27.725,0:00:29.450
下一步开始准备辅料
Next start preparing minor ingredients

0:00:29.550,0:00:32.250
准备猪肥油1小块切成颗粒备用（约35克）
Prepare a small piece of pork fat and dice it (around 35g)

0:00:36.750,0:00:39.650
准备大蒜和生姜各25克切成小粒备用
Prepare garlic and ginger (25g each) and dice them

0:00:41.650,0:00:43.225
碗中加入八角1颗
Add a star anise to the bowl

0:00:43.500,0:00:44.900
加入桂皮几小块
Add some cinnamon

0:00:45.425,0:00:46.900
加入香叶1小片
Add a bay leaf

0:00:47.000,0:00:49.025
加入小葱头几根切碎备用
Add a few cutted scallions

0:00:50.175,0:00:52.700
最后加入适量的干辣椒剪成小节备用
Finally add some dried chili pepper cut in pieces

0:00:56.025,0:00:57.450
下一步开始制作
Next start cooking

0:00:57.650,0:00:59.125
首先我们把锅烧热
First we heat up the wok

0:00:59.150,0:01:00.925
锅烧热之后加入宽油
When it's heated, add Kuan You

0:01:03.800,0:01:06.325
然后开大火烧开将油温烧至6成热
Then turn to high heat until the oil boils to 150 degrees

0:01:06.475,0:01:09.250
油温6成热之后转小火准备炸鱼
When the oil is heated, turn to low heat and fry the fish

0:01:11.575,0:01:14.500
鱼下锅之前先加入适量的玉米淀粉拍打均匀
Before putting the fish into the wok, spread corn starch evenly on the surface

0:01:14.625,0:01:17.775
这一步的目的是防止水分流失将鱼炸得太干
This is to make sure the fish doesn't become too dry

0:01:22.150,0:01:24.775
然后捏着鲈鱼尾巴下锅浸炸3分钟
Then hold the tail and fry the fish for 3 minutes

0:01:24.850,0:01:27.925
这一步的目的是将鲈鱼表面炸至金黄酥脆
This is to fry until the surface is golden and crispy

0:01:31.550,0:01:34.075
中途需要将油均匀地淋在鱼身上面
You need to pour the oil on the fish evenly midway

0:01:41.075,0:01:43.250
3分钟之后将鲈鱼捞出备用
Take the fish out after 3 minutes

0:01:43.275,0:01:46.475
不喜欢油炸的同学也可以用少量的油直接煎
If frying isn't your style, you can pan-fry it with much less oil

0:01:51.350,0:01:53.525
热油倒出之后下一步开始烧汁
Pour out the hot oil and start making the sauce

0:01:53.750,0:01:55.975
将锅烧热之后加入适量的底油
Heat up the wok and add some base oil

0:01:57.625,0:02:01.225
油温4成热之后加入准备好的所有料头翻炒1分钟
When the oil reaches 100 degrees, add all minor ingredients and stir-fry for a minute

0:02:01.275,0:02:03.925
这一步必须爆出猪油和将料头炒香
This is to bring out the flavor of the pork fat and minor ingredients 

0:02:06.500,0:02:08.450
1分钟之后加入蚝油5克
After one minute, add 5g of oyster sauce

0:02:11.050,0:02:12.525
加入晒醋10克
Add 10g of vinegar

0:02:13.675,0:02:14.925
加入料酒10克
Add 10g of Chinese cooking wine

0:02:15.875,0:02:17.425
加入生抽酱油10克
Add 10g of light soy sauce

0:02:21.900,0:02:24.925
翻炒均匀之后加入适量的清水开大火烧开
Mix it up, add some water, and turn to high heat until it boils

0:02:30.050,0:02:32.250
大火烧开之后开始调味
After it boils, add more flavor

0:02:32.525,0:02:34.450
锅中加入适量的食用盐（约2克）
Add some salt to the wok (around 2g)

0:02:36.450,0:02:37.900
加入白糖2勺（4克）
Add two teaspoons of sugar (4g)

0:02:41.650,0:02:43.050
加入胡椒粉1勺（约1克）
Add one teaspoon of ground pepper (around 1g)

0:02:43.725,0:02:45.125
加入鸡精1勺（约1.5克）
Add one teaspoon of chicken essence (around 1.5g)

0:02:46.500,0:02:48.075
加入老抽3克调色
Add 3g of dark soy sauce for the color

0:02:50.600,0:02:53.800
最后加入炸好的鲈鱼下锅转小火烧15分钟
Finally add the fried bass to the wok and braise for 15 minutes at low heat

0:02:54.525,0:02:58.950
同学们烧鱼可以不用翻动只需要浇上热汤即可
You don't need to flip it because you can just pour the hot soup on top

0:03:02.225,0:03:04.900
15分钟之后将鲈鱼捞出摆盘
Take the bass out after 15 minutes and decorate the plate

0:03:13.825,0:03:15.975
然后将汤汁中的料头捞出
Then remove minor ingredients from the wok

0:03:17.975,0:03:19.525
下一步开始勾芡
Next start making the sauce

0:03:19.625,0:03:22.050
锅中加入少许的水淀粉勾成薄芡
Add some water starch to the wok

0:03:25.625,0:03:27.750
勾好芡之后再加入现剁的姜末
Then add some minced ginger

0:03:32.025,0:03:33.575
再加入适量的明油
Then add some Ming You

0:03:35.875,0:03:38.400
最后均匀地淋在鱼身上面即可上菜
Finally spread the sauce on the fish and it's ready

0:03:40.720,0:03:43.300
一道非常美味的醋烧鲈鱼就制作完成
We've finished making a delicious vinegar braised bass

0:03:47.860,0:04:05.360
下面开始技术总结
第一，醋和酒精类似，烧得时间越长挥发得越多
第二，加醋烧鱼可以软化鱼刺，此做法更适合烹制刺多的鱼
第三，最后起锅前加入适量的姜末可以增加不一样的鲜味
醋烧鲈鱼的技术总结完毕
Now, let's summarize the techniques
First, vinegar is like alcohol, the longer you heat it the more likely it'll evaporate
Secondly, adding vinegar softens the fish bones, meaning that this is suitable for fish with lots of bones
Thirdly, adding some minced ginger at the last step enhances the umami flavor
These are all the techniques I'd like to share
