### ISSUE TITLE
[雪鱼] 广西柳州螺蛳粉 - https://youtu.be/zoJZ3m-hTrM

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#864]
**视频链接**：https://youtu.be/zoJZ3m-hTrM

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
广西柳州螺蛳粉，一碗7元，酸辣口味忘不了！再加6大盆的猪蹄鸡脚牛肚，一顿夜宵吃美了

简介
我在广西柳州吃过很多螺蛳粉了，但是今天这家店有点不一样，它是从下午开始营业，一直到深夜。小碗的7元，大碗的8元，上面盖一层小葱酸豆角酸笋，最后浇一勺红油，仿佛给这碗螺蛳粉注入了灵魂！由于酸笋是发酵得来，很多人会觉得味道难闻，但是吃起来不错，注意不是酸臭哦，听老板讲酸臭的螺蛳粉不是好的螺蛳粉！除了常规的螺蛳粉，店家还提供一桌的卤味供顾客选择，有牛肚、猪蹄、鸡脚等！足足6大盆！那些卤味浸透汁水，看着非常有食欲！卤味+螺蛳粉，酸辣口味让人流口水！看着就超级好吃！注意⚠️晚来一会就吃不了，因为深夜都在排队！


字幕
1
00:00:01,880 --> 00:00:04,760
广西·柳州

2
00:00:04,760 --> 00:00:07,480
螺蛳粉

3
00:00:08,140 --> 00:00:09,560
开始添肉了

4
00:00:22,520 --> 00:00:27,080
都不要辣

5
00:00:29,040 --> 00:00:31,760
我不要酸笋 有一份不要酸笋

6
00:00:32,240 --> 00:00:34,160
不要辣

7
00:00:37,140 --> 00:00:39,140
一碗中辣 一碗加辣

8
00:00:47,400 --> 00:00:49,720
来这家店比较有意思的一个地方就是

9
00:00:49,720 --> 00:00:51,120
还未靠近这家店

10
00:00:51,120 --> 00:00:53,920
就能够闻到螺蛳粉的味道

11
00:00:53,920 --> 00:00:56,720
就是那种酸酸的味道  是酸笋的味道

12
00:00:56,720 --> 00:00:58,360
这边的螺蛳粉是小碗的7块钱

13
00:00:58,360 --> 00:00:59,720
大碗的8块钱

14
00:00:59,720 --> 00:01:02,840
咱们要的这一盆就是8块钱的大碗的

15
00:01:02,840 --> 00:01:05,400
这家店有个比较特色的地方就是

16
00:01:05,400 --> 00:01:07,120
这边摆了很多的卤味

17
00:01:07,120 --> 00:01:09,560
可以自己加像鸡脚 鸭脚

18
00:01:09,560 --> 00:01:12,240
牛肚 牛肺 还有鸡蛋 豆腐这些

19
00:01:12,240 --> 00:01:14,800
这些东西选完放在一个盆里

20
00:01:14,800 --> 00:01:17,360
然后老板再另算钱

21
00:01:59,600 --> 00:02:01,360
刚才还没有拍食物的时候

22
00:02:01,360 --> 00:02:04,160
我偷偷地尝了一下酸豆角

23
00:02:04,160 --> 00:02:07,040
蘸了这个汤汁 真的是

24
00:02:07,040 --> 00:02:09,920
酸辣的味道特别想让人流口水

25
00:02:27,440 --> 00:02:30,320
我觉得这个螺蛳粉 比起我们以前吃的来说

26
00:02:31,160 --> 00:02:33,280
它的味要更重一些

27
00:02:33,280 --> 00:02:36,720
这个重不仅体现在汤底 比较浓

28
00:02:36,720 --> 00:02:38,240
红油多一些

29
00:02:38,240 --> 00:02:40,040
而且还有一点就是酸度上

30
00:02:40,040 --> 00:02:41,720
也要更酸一些

31
00:02:41,720 --> 00:02:43,800
我已经和老板说 要微辣了

32
00:02:43,800 --> 00:02:46,760
微辣 还是很辣的

33
00:02:49,640 --> 00:02:51,400
你看

34
00:02:51,760 --> 00:02:53,360
这个汤底

35
00:02:53,360 --> 00:02:56,040
红油特别多 而且明显

36
00:02:59,600 --> 00:03:00,920
我发现

37
00:03:00,920 --> 00:03:05,280
他们这边的螺蛳粉 都会加这种脆的花生

38
00:03:05,280 --> 00:03:08,680
花生刚进来的时候 是热的 脆脆的口感

39
00:03:08,680 --> 00:03:12,000
只不过说 现在泡一泡 会软一些

40
00:03:12,880 --> 00:03:16,080
这碗螺蛳粉里 花生 还有酸豆角 酸笋

41
00:03:16,080 --> 00:03:18,160
这些都是可以随便加的

42
00:03:19,880 --> 00:03:23,040
不要忘了 我们还有这么多的卤味

43
00:03:24,240 --> 00:03:28,080
卤味 像猪蹄 鸭脚 鸡脚

44
00:03:28,080 --> 00:03:29,600
包括虎皮鸡蛋

45
00:03:29,600 --> 00:03:32,040
都是先炸再卤 特别入味

46
00:03:32,400 --> 00:03:36,080
浸透汁水的感觉 看起来就有食欲

47
00:03:36,080 --> 00:03:39,320
你看这个皮 上面都是有一些褶皱的

48
00:03:39,320 --> 00:03:41,040
特别吸收汤汁

49
00:03:41,600 --> 00:03:44,640
可能鸡脚看起来会比较明显一些

50
00:03:51,200 --> 00:03:53,000
这个鸡脚又辣又香

51
00:03:53,000 --> 00:03:55,760
真的是放在嘴里 一抿就化

52
00:04:05,040 --> 00:04:08,760
吃完了 我觉得螺蛳粉给我最大的印象在于

53
00:04:08,760 --> 00:04:12,120
量大 实惠 而且这一碗红红绿绿

54
00:04:12,120 --> 00:04:13,640
特别好看

55
00:04:13,880 --> 00:04:16,640
真是瞅一眼 就觉得 哇 好好吃

56
00:05:04,960 --> 00:05:06,920
咱们来的时候还是白天

57
00:05:06,920 --> 00:05:08,880
吃完饭 已经是黑夜了

58
00:05:08,880 --> 00:05:10,560
这个队 还是这么长

59
00:05:10,560 --> 00:05:13,160
要是晚来一会儿 我肯定就吃不上了

60
00:05:22,440 --> 00:05:26,440
关 注
雪 鱼 探 店


```

**Comment by LuoGuiwen** [comment]
认领。

**Comment by LuoGuiwen** [comment]
认领

**Comment by LuoGuiwen** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
广西柳州螺蛳粉，一碗7元，酸辣口味忘不了！再加6大盆的猪蹄鸡脚牛肚，一顿夜宵吃美了

简介
我在广西柳州吃过很多螺蛳粉了，但是今天这家店有点不一样，它是从下午开始营业，一直到深夜。小碗的7元，大碗的8元，上面盖一层小葱酸豆角酸笋，最后浇一勺红油，仿佛给这碗螺蛳粉注入了灵魂！由于酸笋是发酵得来，很多人会觉得味道难闻，但是吃起来不错，注意不是酸臭哦，听老板讲酸臭的螺蛳粉不是好的螺蛳粉！除了常规的螺蛳粉，店家还提供一桌的卤味供顾客选择，有牛肚、猪蹄、鸡脚等！足足6大盆！那些卤味浸透汁水，看着非常有食欲！卤味+螺蛳粉，酸辣口味让人流口水！看着就超级好吃！注意⚠️晚来一会就吃不了，因为深夜都在排队！


字幕
1
00:00:01,880 --> 00:00:04,760
广西·柳州
Liuzhou city, Guangxi province, China

2
00:00:04,760 --> 00:00:07,480
螺蛳粉
river snails rice noodle

3
00:00:08,140 --> 00:00:09,560
开始添肉了
time to fill the pot with meat

4
00:00:22,520 --> 00:00:27,080
都不要辣
no spicy chili please

5
00:00:29,040 --> 00:00:31,760
我不要酸笋 有一份不要酸笋
give me one without sour bamboo shoots please

6
00:00:32,240 --> 00:00:34,160
不要辣
no spicy chili please

7
00:00:37,140 --> 00:00:39,140
一碗中辣 一碗加辣
one medium spicy, and one heavy spicy

8
00:00:47,400 --> 00:00:49,720
来这家店比较有意思的一个地方就是
one interesting point about this street restaurant is that


9
00:00:49,720 --> 00:00:51,120
还未靠近这家店
before you approach to it,

10
00:00:51,120 --> 00:00:53,920
就能够闻到螺蛳粉的味道
you can smell the taste of river snails rice noodle.

11
00:00:53,920 --> 00:00:56,720
就是那种酸酸的味道  是酸笋的味道
it's a sour taste, derived from sour bamboo shoots.

12
00:00:56,720 --> 00:00:58,360
这边的螺蛳粉是小碗的7块钱
a small bowl costs you 7 RMB

13
00:00:58,360 --> 00:00:59,720
大碗的8块钱
while a big bowl costs 8 RMB.

14
00:00:59,720 --> 00:01:02,840
咱们要的这一盆就是8块钱的大碗的
Here I ordered a big bowl that costs me 8 RMB.

15
00:01:02,840 --> 00:01:05,400
这家店有个比较特色的地方就是
one characteristic about this restaurant is that

16
00:01:05,400 --> 00:01:07,120
这边摆了很多的卤味
it provides lots of stewed food.

17
00:01:07,120 --> 00:01:09,560
可以自己加像鸡脚 鸭脚
accompany with your noodles, you can order chicken feet, duck feet,

18
00:01:09,560 --> 00:01:12,240
牛肚 牛肺 还有鸡蛋 豆腐这些
Beef belly, beef lungs, eggs, tofu, etc.

19
00:01:12,240 --> 00:01:14,800
这些东西选完放在一个盆里
You put what you want into a bowl

20
00:01:14,800 --> 00:01:17,360
然后老板再另算钱
then pay money for them

21
00:01:59,600 --> 00:02:01,360
刚才还没有拍食物的时候
Before we film the food

22
00:02:01,360 --> 00:02:04,160
我偷偷地尝了一下酸豆角
I secretly tried the sour beans

23
00:02:04,160 --> 00:02:07,040
蘸了这个汤汁 真的是
Dip in this soup, it's really...

24
00:02:07,040 --> 00:02:09,920
酸辣的味道特别想让人流口水
The sour and spicy taste really makes you drool.


25
00:02:27,440 --> 00:02:30,320
我觉得这个螺蛳粉 比起我们以前吃的来说
I think the river snails rice noodle in the restaurant, compared to my previous experience,

26
00:02:31,160 --> 00:02:33,280
它的味要更重一些
is heavier taste.


27
00:02:33,280 --> 00:02:36,720
这个重不仅体现在汤底 比较浓
Not only the soup is relatively thick and heavy

28
00:02:36,720 --> 00:02:38,240
红油多一些
the chili oil is more,

29
00:02:38,240 --> 00:02:40,040
而且还有一点就是酸度上
but also the sour taste

30
00:02:40,040 --> 00:02:41,720
也要更酸一些
is heavier.

31
00:02:41,720 --> 00:02:43,800
我已经和老板说 要微辣了
I've told the restaurant owner to give me a slightly spicy one

32
00:02:43,800 --> 00:02:46,760
微辣 还是很辣的
The slightly spicy is also relatively spicy

33
00:02:49,640 --> 00:02:51,400
你看
look

34
00:02:51,760 --> 00:02:53,360
这个汤底
in this pot 

35
00:02:53,360 --> 00:02:56,040
红油特别多 而且明显
there is lots of chili oil, it's evident

36
00:02:59,600 --> 00:03:00,920
我发现
I found that

37
00:03:00,920 --> 00:03:05,280
他们这边的螺蛳粉 都会加这种脆的花生
river snails rice noodle here is always accompanied by crispy peanuts.

38
00:03:05,280 --> 00:03:08,680
花生刚进来的时候 是热的 脆脆的口感
When added into the noodle, peanuts are hot and crispy

39
00:03:08,680 --> 00:03:12,000
只不过说 现在泡一泡 会软一些
but after a while in the noodle soup, it gradually turns soft.

40
00:03:12,880 --> 00:03:16,080
这碗螺蛳粉里 花生 还有酸豆角 酸笋
more peanuts, sour beans and sour bamboo shoots

41
00:03:16,080 --> 00:03:18,160
这些都是可以随便加的
are available for free.

42
00:03:19,880 --> 00:03:23,040
不要忘了 我们还有这么多的卤味
Don't forget, we also ordered so much stewed food.

43
00:03:24,240 --> 00:03:28,080
卤味 像猪蹄 鸭脚 鸡脚
Those stewed food, say trotters, duck feet, chicken feet


44
00:03:28,080 --> 00:03:29,600
包括虎皮鸡蛋
and tiger-skin-like eggs,

45
00:03:29,600 --> 00:03:32,040
都是先炸再卤 特别入味
is made by frying then stewing with spices.

46
00:03:32,400 --> 00:03:36,080
浸透汁水的感觉 看起来就有食欲
soaked in the soup, it looks so appetizing.

47
00:03:36,080 --> 00:03:39,320
你看这个皮 上面都是有一些褶皱的
look at the skin, there are some wrinkles on it,

48
00:03:39,320 --> 00:03:41,040
特别吸收汤汁
which helps to absorb the soup.

49
00:03:41,600 --> 00:03:44,640
可能鸡脚看起来会比较明显一些
those wrinkles on chicken foot are more visible.

50
00:03:51,200 --> 00:03:53,000
这个鸡脚又辣又香
The chicken foot tastes spicy as well as fragrant

51
00:03:53,000 --> 00:03:55,760
真的是放在嘴里 一抿就化
put it into your mouth. once sipped, it melts.

52
00:04:05,040 --> 00:04:08,760
吃完了 我觉得螺蛳粉给我最大的印象在于
I finish it. the biggest impression the river snails rice noodle leaves to me is that 

53
00:04:08,760 --> 00:04:12,120
量大 实惠 而且这一碗红红绿绿
it's enough but cheap

54
00:04:12,120 --> 00:04:13,640
特别好看
and it looks so good.

55
00:04:13,880 --> 00:04:16,640
真是瞅一眼 就觉得 哇 好好吃
once you see it, you'll wow and imagine its delicious taste.

56
00:05:04,960 --> 00:05:06,920
咱们来的时候还是白天
it's daytime when we arrived,

57
00:05:06,920 --> 00:05:08,880
吃完饭 已经是黑夜了
now we finish the deal, it's already dark.

58
00:05:08,880 --> 00:05:10,560
这个队 还是这么长
Look at the line, it's still so long.

59
00:05:10,560 --> 00:05:13,160
要是晚来一会儿 我肯定就吃不上了
If I came here a little bit late, I wouldn't be served so quickly.

60
00:05:22,440 --> 00:05:26,440
关 注
雪 鱼 探 店
Please Subscribe our channel Chinese Street Food.

**Comment by LuoGuiwen** [comment]
不好意思，我第一次翻，翻完才看对译表~~。豆角这个词我翻错了，烦请审阅的小伙伴多加注意，蟹蟹。

**Comment by LuoGuiwen** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
广西柳州螺蛳粉，一碗7元，酸辣口味忘不了！再加6大盆的猪蹄鸡脚牛肚，一顿夜宵吃美了
Liuzhou river snails rice noodle, accompanied by trotters, chicken feets and beef belly, is a wonderful midnight snack

简介
我在广西柳州吃过很多螺蛳粉了，但是今天这家店有点不一样，它是从下午开始营业，一直到深夜。小碗的7元，大碗的8元，上面盖一层小葱酸豆角酸笋，最后浇一勺红油，仿佛给这碗螺蛳粉注入了灵魂！由于酸笋是发酵得来，很多人会觉得味道难闻，但是吃起来不错，注意不是酸臭哦，听老板讲酸臭的螺蛳粉不是好的螺蛳粉！除了常规的螺蛳粉，店家还提供一桌的卤味供顾客选择，有牛肚、猪蹄、鸡脚等！足足6大盆！那些卤味浸透汁水，看着非常有食欲！卤味+螺蛳粉，酸辣口味让人流口水！看着就超级好吃！注意⚠️晚来一会就吃不了，因为深夜都在排队！

I've eaten lots of Liuzhou river snails rice noodle in different restaurants, but the restaurant we visit today is kind of special. It opens in the afternoon, and remains operation till midnight. A small bowl costs you 7 RMB, and a big bowl costs you 8 RMB. The noodle is covered with a layer of scallions, sour cowpeas and bamboo shoots. Pouring a spoonful of chili oil in the end infuses the meal with soul! Since the bamboo shoots are fermented, many people find that it smells unpleasant, but tastes good. Note that it is not literally sour smell, the restaurant owner told me that river snails rice noodle with literally sour smell is actually low-quality one. In addition to the river snails rice noodle, this restaurant also provides stewed food for customers to choose and buy, including beef belly, trotters, chicken feet, etc., that fill 6 large pots. Soaked in the spice soup, those stewed food looks so appetizing. Stewed food + river snails rice noodle, their sour and spicy taste makes you drooling. It looks super delicious! Note ⚠️ If you come here late, you won't be served quickly because you're supposed to line up.



字幕
1
00:00:01,880 --> 00:00:04,760
广西·柳州
Liuzhou city, Guangxi province, China

2
00:00:04,760 --> 00:00:07,480
螺蛳粉
river snails rice noodle

3
00:00:08,140 --> 00:00:09,560
开始添肉了
time to fill the pot with meat

4
00:00:22,520 --> 00:00:27,080
都不要辣
no spicy chili please

5
00:00:29,040 --> 00:00:31,760
我不要酸笋 有一份不要酸笋
give me one without sour bamboo shoots please

6
00:00:32,240 --> 00:00:34,160
不要辣
no spicy chili please

7
00:00:37,140 --> 00:00:39,140
一碗中辣 一碗加辣
one medium spicy, and one heavy spicy

8
00:00:47,400 --> 00:00:49,720
来这家店比较有意思的一个地方就是
one interesting point about this street restaurant is that


9
00:00:49,720 --> 00:00:51,120
还未靠近这家店
before you approach to it,

10
00:00:51,120 --> 00:00:53,920
就能够闻到螺蛳粉的味道
you can smell the taste of river snails rice noodle.

11
00:00:53,920 --> 00:00:56,720
就是那种酸酸的味道  是酸笋的味道
it's a sour taste, derived from sour bamboo shoots.

12
00:00:56,720 --> 00:00:58,360
这边的螺蛳粉是小碗的7块钱
a small bowl costs you 7 RMB

13
00:00:58,360 --> 00:00:59,720
大碗的8块钱
while a big bowl costs 8 RMB.

14
00:00:59,720 --> 00:01:02,840
咱们要的这一盆就是8块钱的大碗的
Here I ordered a big bowl that costs me 8 RMB.

15
00:01:02,840 --> 00:01:05,400
这家店有个比较特色的地方就是
one characteristic about this restaurant is that

16
00:01:05,400 --> 00:01:07,120
这边摆了很多的卤味
it provides lots of stewed food.

17
00:01:07,120 --> 00:01:09,560
可以自己加像鸡脚 鸭脚
accompany with your noodles, you can order chicken feet, duck feet,

18
00:01:09,560 --> 00:01:12,240
牛肚 牛肺 还有鸡蛋 豆腐这些
Beef belly, beef lungs, eggs, tofu, etc.

19
00:01:12,240 --> 00:01:14,800
这些东西选完放在一个盆里
You put what you want into a bowl

20
00:01:14,800 --> 00:01:17,360
然后老板再另算钱
then pay money for them

21
00:01:59,600 --> 00:02:01,360
刚才还没有拍食物的时候
Before we film the food

22
00:02:01,360 --> 00:02:04,160
我偷偷地尝了一下酸豆角
I secretly tried the sour cowpeas

23
00:02:04,160 --> 00:02:07,040
蘸了这个汤汁 真的是
Dip in this soup, it's really...

24
00:02:07,040 --> 00:02:09,920
酸辣的味道特别想让人流口水
The sour and spicy taste really makes you drool.


25
00:02:27,440 --> 00:02:30,320
我觉得这个螺蛳粉 比起我们以前吃的来说
I think the river snails rice noodle in the restaurant, compared to my previous experience,

26
00:02:31,160 --> 00:02:33,280
它的味要更重一些
is heavier taste.


27
00:02:33,280 --> 00:02:36,720
这个重不仅体现在汤底 比较浓
Not only the soup is relatively thick and heavy

28
00:02:36,720 --> 00:02:38,240
红油多一些
the chili oil is more,

29
00:02:38,240 --> 00:02:40,040
而且还有一点就是酸度上
but also the sour taste

30
00:02:40,040 --> 00:02:41,720
也要更酸一些
is heavier.

31
00:02:41,720 --> 00:02:43,800
我已经和老板说 要微辣了
I've told the restaurant owner to give me a slightly spicy one

32
00:02:43,800 --> 00:02:46,760
微辣 还是很辣的
The slightly spicy is also relatively spicy

33
00:02:49,640 --> 00:02:51,400
你看
look

34
00:02:51,760 --> 00:02:53,360
这个汤底
in this pot 

35
00:02:53,360 --> 00:02:56,040
红油特别多 而且明显
there is lots of chili oil, it's evident

36
00:02:59,600 --> 00:03:00,920
我发现
I found that

37
00:03:00,920 --> 00:03:05,280
他们这边的螺蛳粉 都会加这种脆的花生
river snails rice noodle here is always accompanied by crispy peanuts.

38
00:03:05,280 --> 00:03:08,680
花生刚进来的时候 是热的 脆脆的口感
When added into the noodle, peanuts are hot and crispy

39
00:03:08,680 --> 00:03:12,000
只不过说 现在泡一泡 会软一些
but after a while in the noodle soup, it gradually turns soft.

40
00:03:12,880 --> 00:03:16,080
这碗螺蛳粉里 花生 还有酸豆角 酸笋
more peanuts, sour cowpeas and sour bamboo shoots

41
00:03:16,080 --> 00:03:18,160
这些都是可以随便加的
are available for free.

42
00:03:19,880 --> 00:03:23,040
不要忘了 我们还有这么多的卤味
Don't forget, we also ordered so much stewed food.

43
00:03:24,240 --> 00:03:28,080
卤味 像猪蹄 鸭脚 鸡脚
Those stewed food, say trotters, duck feet, chicken feet


44
00:03:28,080 --> 00:03:29,600
包括虎皮鸡蛋
and tiger-skin-like eggs,

45
00:03:29,600 --> 00:03:32,040
都是先炸再卤 特别入味
is made by frying then stewing with spices.

46
00:03:32,400 --> 00:03:36,080
浸透汁水的感觉 看起来就有食欲
soaked in the soup, it looks so appetizing.

47
00:03:36,080 --> 00:03:39,320
你看这个皮 上面都是有一些褶皱的
look at the skin, there are some wrinkles on it,

48
00:03:39,320 --> 00:03:41,040
特别吸收汤汁
which helps to absorb the soup.

49
00:03:41,600 --> 00:03:44,640
可能鸡脚看起来会比较明显一些
those wrinkles on chicken foot are more visible.

50
00:03:51,200 --> 00:03:53,000
这个鸡脚又辣又香
The chicken foot tastes spicy as well as fragrant

51
00:03:53,000 --> 00:03:55,760
真的是放在嘴里 一抿就化
put it into your mouth. once sipped, it melts.

52
00:04:05,040 --> 00:04:08,760
吃完了 我觉得螺蛳粉给我最大的印象在于
I finish it. the biggest impression the river snails rice noodle leaves to me is that 

53
00:04:08,760 --> 00:04:12,120
量大 实惠 而且这一碗红红绿绿
it's enough but cheap

54
00:04:12,120 --> 00:04:13,640
特别好看
and it looks so good.

55
00:04:13,880 --> 00:04:16,640
真是瞅一眼 就觉得 哇 好好吃
once you see it, you'll wow and imagine its delicious taste.

56
00:05:04,960 --> 00:05:06,920
咱们来的时候还是白天
it's daytime when we arrived,

57
00:05:06,920 --> 00:05:08,880
吃完饭 已经是黑夜了
now we finish the deal, it's already dark.

58
00:05:08,880 --> 00:05:10,560
这个队 还是这么长
Look at the line, it's still so long.

59
00:05:10,560 --> 00:05:13,160
要是晚来一会儿 我肯定就吃不上了
If I came here a little bit late, I wouldn't be served so quickly.

60
00:05:22,440 --> 00:05:26,440
关 注
雪 鱼 探 店
Please Subscribe our channel Chinese Street Food.
