### ISSUE TITLE
【美食作家王刚】 鱼羊鲜汤 - https://youtu.be/M2Jd-RsSJA0

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#873]
**视频链接**：https://youtu.be/M2Jd-RsSJA0

视频时长 7:46，预计发布时间为北京时间4月4日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“鱼羊汤”“鲜汤”“鱼羊鲜”的简单做法，居然会有天然的鲜味，并且营养丰富

简介
大家好，今天和大家分享一道“鲜汤”，在很多地区也叫“鱼羊鲜”，是由主料羊肉和鲫鱼制作而成的一道汤菜，相传此菜的历史十分悠久，甚至和“鲜”这个字的由来都有渊源，但现在不同地方也流传着不同此菜的做法，今天就和大家分享一道非常简单适合在家操作的一种做法，将鲫鱼煎香放汤之后将羊肉丸下锅汆熟即可，不用加鸡精或味精本身烫头就会十分的鲜美，如果是喜欢喝汤的朋友一定不要错过这么一道好汤，希望大家喜欢！

字幕
0:00:00.000,0:00:00.700
哈喽 大家好

0:00:01.169,0:00:03.403
这块羊肉是我伯爷用（猪）腰子换的

0:00:03.944,0:00:06.039
现在腰子好多钱一斤哦四伯爷

0:00:06.560,0:00:08.063
腰子10块一个

0:00:08.182,0:00:09.020
10块个20

0:00:09.321,0:00:10.478
那就刚好差不多嘎

0:00:10.724,0:00:12.109
差不多 我没吃到亏

0:00:12.109,0:00:13.940
头回我换的甲鱼我吃了亏

0:00:13.940,0:00:16.070
这哈我还是晓得哈数（套路）了

0:00:16.601,0:00:18.724
今天我们用这块羊肉煮一个汤

0:00:19.243,0:00:20.464
煮一个丸子汤

0:00:22.806,0:00:23.936
先我们把它切碎

0:00:23.936,0:00:26.533
切碎了之后剁成肉泥

0:00:27.116,0:00:29.084
我们这个羊肉最好是用里脊

0:00:29.485,0:00:31.763
然后这个后腿 腿子肉的话

0:00:31.763,0:00:33.466
上面有这个筋膜其实也可以

0:00:34.004,0:00:35.316
就是说里脊更好一些

0:00:36.637,0:00:38.405
我们这个切刀就不要拿来剁

0:00:40.336,0:00:41.142
拿这个来剁

0:00:43.586,0:00:45.359
这个菜应该是你第一次吃

0:00:45.359,0:00:46.747
也是第一次看到过

0:00:47.030,0:00:48.626
而且也是第一次听到说过

0:00:49.157,0:00:49.714
你信不信

0:00:49.714,0:00:51.105
这个名字叫啥子名字嘛

0:00:51.789,0:00:52.736
就叫做鲜汤

0:00:55.436,0:00:56.360
这个肉剁好了

0:00:56.360,0:00:59.030
下一步准备腌这个肉

0:01:00.255,0:01:02.691
我们羊肉里面拍一点姜剁碎放进去 

0:01:03.954,0:01:05.075
去一下腥

0:01:06.849,0:01:08.187
然后再放一点葱头

0:01:08.353,0:01:10.736
这个葱现在慢慢的开始老了噶

0:01:11.105,0:01:12.067
嗯 有点老了

0:01:13.887,0:01:15.887
现在我们加点盐进去调这个味道

0:01:16.609,0:01:18.060
 盐可以稍微多那么一点点

0:01:19.406,0:01:20.383
再放点胡椒粉

0:01:23.541,0:01:25.248
然后我们把它搅拌均匀

0:01:25.797,0:01:26.398
打上劲

0:01:26.909,0:01:29.120
我们新鲜的这个羊肉可以不用加料酒

0:01:29.120,0:01:31.541
特别是煮这个汤的时候

0:01:32.948,0:01:34.360
只需要把它打上劲就可以了

0:01:36.662,0:01:38.430
我们这个打上劲了之后

0:01:38.430,0:01:39.736
再这样子摔一下

0:01:42.288,0:01:42.803
摔好了之后

0:01:42.803,0:01:45.850
我们来处理下一样神秘食材

0:01:48.059,0:01:50.489
杀鲫鱼之前我们先准备一些筷子

0:01:50.489,0:01:51.988
我今天准备了五条鲫鱼

0:01:52.328,0:01:53.702
所以就准备了五双筷子

0:01:56.046,0:01:58.286
我们这个鲫鱼先用筷子

0:01:58.286,0:02:01.827
用一双筷子从嘴巴里面插进去

0:02:03.415,0:02:06.612
这样做就是让它安静一点

0:02:06.612,0:02:07.574
就是不能让它动

0:02:08.164,0:02:09.789
老是动的话不好杀这个鱼

0:02:12.611,0:02:13.718
OK 这样子穿好了

0:02:14.462,0:02:15.084
先放在这里

0:02:17.510,0:02:18.229
它还想越狱

0:02:18.835,0:02:19.506
逮到它 四伯爷

0:02:22.449,0:02:23.443
好 我们穿第二条

0:02:27.510,0:02:28.997
我们这个穿好了之后

0:02:28.997,0:02:31.188
可以直接拿着这里来去鳞

0:02:31.455,0:02:32.417
就特别的方便

0:02:34.931,0:02:36.079
这个鱼鳞去掉之后

0:02:36.079,0:02:38.641
直接在这个鱼旁边这样子切一刀

0:02:40.873,0:02:42.619
切一刀就可以把它放到碗里面

0:02:43.217,0:02:44.017
放到这个盆里了

0:02:44.050,0:02:46.111
待会就直接抠内脏就行了

0:02:47.227,0:02:48.625
这个我们这个鱼就杀好了

0:02:48.682,0:02:50.873
就是去了鱼鳃跟内脏

0:02:51.616,0:02:52.934
然后简单的改下刀

0:02:59.773,0:03:03.047
最后我们再切点姜片

0:03:07.340,0:03:09.021
然后再挽一点小葱

0:03:09.393,0:03:10.056
可以了 四伯爷

0:03:11.236,0:03:12.012
就可以搞了啊

0:03:12.320,0:03:12.805
差不多了

0:03:13.936,0:03:15.384
盐巴帮我拿过来一下  四伯爷

0:03:15.723,0:03:17.073
你还多撇脱（简单）哦

0:03:17.073,0:03:17.962
一下都（可以了）

0:03:18.447,0:03:19.369
肯定撇脱噻

0:03:19.612,0:03:20.929
现在我们煮之前

0:03:21.325,0:03:23.484
煮汤之间先烧半盆水

0:03:23.734,0:03:24.527
把水烧开

0:03:25.084,0:03:27.817
咱们煮这个鱼汤一定要开水 要热水

0:03:29.168,0:03:32.194
制作之前我们先准备半盆清水烧开

0:03:33.469,0:03:35.876
同学们切记煮鱼汤必须用开水

0:03:35.876,0:03:38.495
否则鱼汤煮不白反而还有鱼腥味

0:03:38.619,0:03:40.371
水烧开之后倒出备用

0:03:45.469,0:03:48.141
锅烧热之后我们加入一些底油滑锅

0:03:48.637,0:03:51.309
煎鱼不滑锅的话鱼皮容易粘锅

0:03:51.327,0:03:53.646
热油倒出之后再加入些冷油

0:03:55.398,0:03:58.035
油温5成热之后锅中加入一些食用盐

0:03:58.212,0:04:00.707
这样可以在煎制的时候鱼不容易烂

0:04:00.707,0:04:02.796
同时还能去除一定的鱼腥味

0:04:02.814,0:04:05.610
然后我们再把这个鱼一条一条的放入锅中

0:04:05.610,0:04:08.477
  学习美食的时候咱们也要先保护好自己

0:04:10.407,0:04:12.371
鱼下锅之后先不要动锅

0:04:12.371,0:04:14.241
慢慢的煎它10秒钟左右

0:04:14.360,0:04:16.149
这样是为了让鱼皮定型

0:04:16.149,0:04:19.845
10秒钟之后我们再把锅转动起来煎它1分钟

0:04:20.047,0:04:21.540
煎至鱼皮金黄为止

0:04:21.540,0:04:24.099
同学们家庭小灶则需要2分钟左右

0:04:24.360,0:04:27.132
煎1分钟之后我们再顺势翻过来煎另一面

0:04:27.132,0:04:30.521
 同样煎它1分钟之后再加入事先准备好的开水下锅

0:04:33.021,0:04:35.947
   大火烧开之后再加入切好的姜片和小葱

0:04:35.947,0:04:37.819
然后转中小火煮6分钟

0:04:37.997,0:04:41.398
中途咱们也别闲着边煮边去掉浮沫

0:04:46.327,0:04:48.874
6分钟之后鱼汤已经煮成浓白色了

0:04:49.123,0:04:50.414
然后再把锅离火

0:04:50.651,0:04:53.092
将准备好的羊肉挤成丸子下入锅中 

0:04:59.004,0:05:02.286
丸子全部下入锅中之后开始转小火煮3分钟

0:05:02.748,0:05:05.225
同学们切记丸子下锅之后不能开大火煮

0:05:06.683,0:05:08.661
否则丸子特别容易被冲烂

0:05:17.962,0:05:20.390
    起锅之前我们在碗中撒入适量的葱花

0:05:20.758,0:05:22.997
当然了喜欢香菜的同学也可以放

0:05:23.388,0:05:25.450
然后我们把汤里面的小葱捡出来

0:05:25.793,0:05:26.931
下面开始调味

0:05:27.239,0:05:28.886
锅中加入少许的食用盐

0:05:29.052,0:05:31.492
然后再加入少许胡椒粉就可以出锅

0:05:48.193,0:05:49.280
舀点汤来喝看

0:05:49.335,0:05:50.459
我来给你舀 四伯爷

0:05:52.169,0:05:53.125
吃点羊肉丸嘛

0:05:53.543,0:05:54.110
要的呀

0:05:54.714,0:05:56.182
我给你舀一碗

0:05:57.222,0:05:58.560
羊肉来整的呀这是

0:05:58.560,0:05:59.507
嗯 羊肉丸子

0:06:01.198,0:06:01.969
现宰的

0:06:03.111,0:06:04.273
我尝看有盐味没得多

0:06:05.332,0:06:06.521
盐味肯定是有的

0:06:06.521,0:06:07.638
有

0:06:08.973,0:06:10.357
还多鲜这个味道

0:06:10.701,0:06:11.463
肯定了

0:06:12.131,0:06:12.819
好 可以了可以了

0:06:14.129,0:06:14.556
安逸

0:06:16.312,0:06:16.925
好不好吃嘛

0:06:17.835,0:06:19.489
这次的羊肉是换值了的

0:06:22.336,0:06:23.008
好吃

0:06:24.263,0:06:26.000
我们这个汤特别鲜

0:06:26.363,0:06:28.053
特别是羊肉加进去了之后

0:06:28.601,0:06:32.048
其实你也可以理解成为这个鲫鱼汤加羊肉

0:06:32.986,0:06:33.404
是吧

0:06:34.305,0:06:35.401
为什么叫鲜汤呢

0:06:35.401,0:06:38.095
就是因为有鱼有羊

0:06:38.197,0:06:40.260
这样鲜汤拿来下面吃肯定安逸哦

0:06:40.520,0:06:41.254
必须的撒

0:06:45.127,0:06:46.075
它都想吃

0:06:47.022,0:06:49.679
你吃 我都没吃好多点 你吃

0:06:50.552,0:06:53.265
我们的狗在旁边馋得不行了已经

0:06:53.293,0:06:54.184
它想吃

0:06:57.594,0:06:59.294
我给你多舀点这个丸子

0:07:00.919,0:07:01.486
来 伯爷

0:07:02.062,0:07:05.666
这个东西弄来下面可能相当舒服哦吃起

0:07:05.703,0:07:06.669
伯娘 舀哦

0:07:07.050,0:07:07.682
我自己舀

0:07:08.267,0:07:09.187
要得

0:07:09.187,0:07:09.595
你舀来吃嘛

0:07:09.595,0:07:10.692
要得 你自己舀嘛

0:07:11.035,0:07:11.463
安逸

0:07:15.030,0:07:16.972
 好了 大家如果对这个感兴趣的话

0:07:16.972,0:07:18.366
一定在家里面试一下

0:07:18.739,0:07:19.730
如果买不到羊肉的话

0:07:19.730,0:07:22.354
可以买那个猪肉也可以啊

0:07:22.602,0:07:22.851
对不对

0:07:22.851,0:07:23.590
羊肉虽然贵

0:07:23.590,0:07:25.516
但是猪肉也不便宜嘎

0:07:26.351,0:07:28.125
猪肉也没得好相因（便宜）的呀

0:07:28.484,0:07:29.900
不好意思 打扰了

0:07:33.483,0:07:34.753
好了 本期视频就到这里

0:07:35.174,0:07:35.492
拜拜

0:07:38.964,0:07:39.475
再喝一碗


```

**Comment by immoonancient** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“鱼羊汤”“鲜汤”“鱼羊鲜”的简单做法，居然会有天然的鲜味，并且营养丰富
Chef Wang teaches you: "Fish and Lamb Savory Soup", easy, nutritious and naturally savory!

简介
大家好，今天和大家分享一道“鲜汤”，在很多地区也叫“鱼羊鲜”，
Hello everyone, today I'll share the recipe of "The Savory Soup",
aka "Fish and Lamb Savory Soup" in some regions.
是由主料羊肉和鲫鱼制作而成的一道汤菜，
It is a soup made with lamb and "ji yu" carp.
相传此菜的历史十分悠久，甚至和“鲜”这个字的由来都有渊源，
Legend has it that the dish has a very long history,
and is even related to the origin of the Chinese character for "savory",
which is literally composed of the "fish" and "lamb" particles.
但现在不同地方也流传着不同此菜的做法，
Nowadays, there are different recipes of this dish in different regions.
今天就和大家分享一道非常简单适合在家操作的一种做法，
Today, I'll share a very simple and homely recipe:
将鲫鱼煎香放汤之后将羊肉丸下锅汆熟即可，
fry the fish, add water and boil, and then cook the lamb meatballs in it and it's done!
不用加鸡精或味精本身汤头就会十分的鲜美，
There's no need for MSG or chicken bouillon, as the soup itself is already fully savory.
如果是喜欢喝汤的朋友一定不要错过这么一道好汤，希望大家喜欢！
If you like soups, do not miss this one. Hope everyone likes it!

字幕

0:00:00.000,0:00:00.700
哈喽 大家好
Hello everyone

0:00:01.169,0:00:03.403
这块羊肉是我伯爷用（猪）腰子换的
Uncle traded some pork kidneys for the lamb

0:00:03.944,0:00:06.039
现在腰子好多钱一斤哦四伯爷
How much is pork kidney now, uncle?

0:00:06.560,0:00:08.063
腰子10块一个
10 yuan each

0:00:08.182,0:00:09.020
10块个20
10 yuan each. For 20 yuan...

0:00:09.321,0:00:10.478
那就刚好差不多嘎
That's about right

0:00:10.724,0:00:12.109
差不多 我没吃到亏
Right. Not a bad trade for me

0:00:12.109,0:00:13.940
头回我换的甲鱼我吃了亏
Last time for the softshell turtle, that was a bad trade

0:00:13.940,0:00:16.070
这哈我还是晓得哈数（套路）了
Now I know how things work

0:00:16.601,0:00:18.724
今天我们用这块羊肉煮一个汤
Today, we'll make a soup with the mutton

0:00:19.243,0:00:20.464
煮一个丸子汤
Make a meatball soup

0:00:22.806,0:00:23.936
先我们把它切碎
Let's first cut it up

0:00:23.936,0:00:26.533
切碎了之后剁成肉泥
Then we'll mince it

0:00:27.116,0:00:29.084
我们这个羊肉最好是用里脊
It's best to use mutton tenderloin

0:00:29.485,0:00:31.763
然后这个后腿 腿子肉的话
Or the hind leg, the shank...

0:00:31.763,0:00:33.466
上面有这个筋膜其实也可以
There's some silverskin, which is still fine

0:00:34.004,0:00:35.316
就是说里脊更好一些
Anyway, tenderloin is better

0:00:36.637,0:00:38.405
我们这个切刀就不要拿来剁
This knife is a slicer. Let's not chop with it

0:00:40.336,0:00:41.142
拿这个来剁
Let's chop with this one

0:00:43.586,0:00:45.359
这个菜应该是你第一次吃
It should be the first time you have this dish

0:00:45.359,0:00:46.747
也是第一次看到过
And the first you see it

0:00:47.030,0:00:48.626
而且也是第一次听到说过
Even the first time you ever hear about it

0:00:49.157,0:00:49.714
你信不信
Believe it or not

0:00:49.714,0:00:51.105
这个名字叫啥子名字嘛
What's the name of it?

0:00:51.789,0:00:52.736
就叫做鲜汤
It's literally "the savory soup"

0:00:55.436,0:00:56.360
这个肉剁好了
The meat is chopped up

0:00:56.360,0:00:59.030
下一步准备腌这个肉
Next we'll marinate it

0:01:00.255,0:01:02.691
我们羊肉里面拍一点姜剁碎放进去 
Crush and mince some ginger, into the lamb

0:01:03.954,0:01:05.075
去一下腥
To reduce the smell

0:01:06.849,0:01:08.187
然后再放一点葱头
Also add some scallion white

0:01:08.353,0:01:10.736
这个葱现在慢慢的开始老了噶
The scallions are a bit older now?

0:01:11.105,0:01:12.067
嗯 有点老了
Hmm, a bit old already

0:01:13.887,0:01:15.887
现在我们加点盐进去调这个味道
Now let's season it with some salt

0:01:16.609,0:01:18.060
盐可以稍微多那么一点点
We can use a bit more salt

0:01:19.406,0:01:20.383
再放点胡椒粉
Also some white pepper powder

0:01:23.541,0:01:25.248
然后我们把它搅拌均匀
Then we stir to mix it up

0:01:25.797,0:01:26.398
打上劲
Make it sticky

0:01:26.909,0:01:29.120
我们新鲜的这个羊肉可以不用加料酒
We don't need cooking wine for fresh lamb

0:01:29.120,0:01:31.541
特别是煮这个汤的时候
Especially when making a soup

0:01:32.948,0:01:34.360
只需要把它打上劲就可以了
Just need to stir it well, make it sticky

0:01:36.662,0:01:38.430
我们这个打上劲了之后
After stirring it well

0:01:38.430,0:01:39.736
再这样子摔一下
Then smash it like this

0:01:42.288,0:01:42.803
摔好了之后
After smashing

0:01:42.803,0:01:45.850
我们来处理下一样神秘食材
Let's prepare the next secretive ingredient

0:01:48.059,0:01:50.489
杀鲫鱼之前我们先准备一些筷子
Before cleaning the "ji yu" carp, we need some chopsticks

0:01:50.489,0:01:51.988
我今天准备了五条鲫鱼
I got 5 fish for today

0:01:52.328,0:01:53.702
所以就准备了五双筷子
So there're five pairs of chopsticks

0:01:56.046,0:01:58.286
我们这个鲫鱼先用筷子
First stick a chopstick into the fish

0:01:58.286,0:02:01.827
用一双筷子从嘴巴里面插进去
all the way from the mouth

0:02:03.415,0:02:06.612
这样做就是让它安静一点
This makes it calmer

0:02:06.612,0:02:07.574
就是不能让它动
Immobilizes it

0:02:08.164,0:02:09.789
老是动的话不好杀这个鱼
If it moves around, it will be hard to clean

0:02:12.611,0:02:13.718
OK 这样子穿好了
OK, done 

0:02:14.462,0:02:15.084
先放在这里
Put it here

0:02:17.510,0:02:18.229
它还想越狱
It silll wants to break the prison

0:02:18.835,0:02:19.506
逮到它 四伯爷
Catch it, uncle

0:02:22.449,0:02:23.443
好 我们穿第二条
Alright, the next one

0:02:27.510,0:02:28.997
我们这个穿好了之后
After sticking it

0:02:28.997,0:02:31.188
可以直接拿着这里来去鳞
We can just grab it and scale it

0:02:31.455,0:02:32.417
就特别的方便
which is very convenient

0:02:34.931,0:02:36.079
这个鱼鳞去掉之后
After removing the scales

0:02:36.079,0:02:38.641
直接在这个鱼旁边这样子切一刀
Slice at the side of the fish like this

0:02:40.873,0:02:42.619
切一刀就可以把它放到碗里面
Slice it, and then we can put it in the bowl

0:02:43.217,0:02:44.017
放到这个盆里了
Put it in the basin

0:02:44.050,0:02:46.111
待会就直接抠内脏就行了
Later, we can just remove the organs

0:02:47.227,0:02:48.625
这个我们这个鱼就杀好了
Now we're done cleaning the fish

0:02:48.682,0:02:50.873
就是去了鱼鳃跟内脏
We've remove the gills and the organs

0:02:51.616,0:02:52.934
然后简单的改下刀
Then make some slices

0:02:59.773,0:03:03.047
最后我们再切点姜片
Finally, let's cut some ginger slices

0:03:07.340,0:03:09.021
然后再挽一点小葱
And tie some scallions

0:03:09.393,0:03:10.056
可以了 四伯爷
Done, uncle

0:03:11.236,0:03:12.012
就可以搞了啊
So we can get started?

0:03:12.320,0:03:12.805
差不多了
Yeah

0:03:13.936,0:03:15.384
盐巴帮我拿过来一下  四伯爷
Could you take the salt, uncle?

0:03:15.723,0:03:17.073
你还多撇脱（简单）哦
You made is so easy huh?

0:03:17.073,0:03:17.962
一下都（可以了）
You finished so fast

0:03:18.447,0:03:19.369
肯定撇脱噻
Of course easy!

0:03:19.612,0:03:20.929
现在我们煮之前
Before we start cooking

0:03:21.325,0:03:23.484
煮汤之间先烧半盆水
Before making the soup, boil some water first

0:03:23.734,0:03:24.527
把水烧开
Let it boil

0:03:25.084,0:03:27.817
咱们煮这个鱼汤一定要开水 要热水
We must use hot water to make fish soup

0:03:29.168,0:03:32.194
制作之前我们先准备半盆清水烧开
Boil half a basin of water before cooking

0:03:33.469,0:03:35.876
同学们切记煮鱼汤必须用开水
Keep in mind, use hot water to make fish soup

0:03:35.876,0:03:38.495
否则鱼汤煮不白反而还有鱼腥味
Otherwise, the soup won't become milky white, but smelly instead

0:03:38.619,0:03:40.371
水烧开之后倒出备用
After the water boils, set it aside

0:03:45.469,0:03:48.141
锅烧热之后我们加入一些底油滑锅
Heat up the wok, then grease it with some oil

0:03:48.637,0:03:51.309
煎鱼不滑锅的话鱼皮容易粘锅
If you fry fish without greasing, the skin will stick to the wok

0:03:51.327,0:03:53.646
热油倒出之后再加入些冷油
Pour out the hot oil, and add some cold oil

0:03:55.398,0:03:58.035
油温5成热之后锅中加入一些食用盐
When the oil reaches about 150 °C, add in some salt

0:03:58.212,0:04:00.707
这样可以在煎制的时候鱼不容易烂
So that we don't break the fish when frying

0:04:00.707,0:04:02.796
同时还能去除一定的鱼腥味
And it reduces some fishy smell

0:04:02.814,0:04:05.610
然后我们再把这个鱼一条一条的放入锅中
Then, we put the fish into the wok one by one

0:04:05.610,0:04:08.477
学习美食的时候咱们也要先保护好自己
While studying cooking, we also need to protect ourselves well

0:04:10.407,0:04:12.371
鱼下锅之后先不要动锅
After the fish are in, don't move the wok immediately 

0:04:12.371,0:04:14.241
慢慢的煎它10秒钟左右
Let them fry for about 10 seconds

0:04:14.360,0:04:16.149
这样是为了让鱼皮定型
So that we fix the shape of the fish skin

0:04:16.149,0:04:19.845
10秒钟之后我们再把锅转动起来煎它1分钟
After 10 seconds, we swirl the wok and fry for a minute

0:04:20.047,0:04:21.540
煎至鱼皮金黄为止
Fry until the skin turns golden yellow

0:04:21.540,0:04:24.099
同学们家庭小灶则需要2分钟左右
With a homely stove, this takes about 2 minutes

0:04:24.360,0:04:27.132
煎1分钟之后我们再顺势翻过来煎另一面
1 minute later, flip the fish and fry the other side

0:04:27.132,0:04:30.521
同样煎它1分钟之后再加入事先准备好的开水下锅
Similarly, fry for a minute. Then add in the hot water

0:04:33.021,0:04:35.947
大火烧开之后再加入切好的姜片和小葱
Boil it over high heat. Add in ginger slices and scallion

0:04:35.947,0:04:37.819
然后转中小火煮6分钟
Then turn to medium-low heat and cook for 6 minutes

0:04:37.997,0:04:41.398
中途咱们也别闲着边煮边去掉浮沫
Meanwhile, we shouldn't be idle. Skim off the scum while cooking

0:04:46.327,0:04:48.874
6分钟之后鱼汤已经煮成浓白色了
6 minutes later, the fish soup already turns milky white

0:04:49.123,0:04:50.414
然后再把锅离火
Then move the wok away from the flame

0:04:50.651,0:04:53.092
将准备好的羊肉挤成丸子下入锅中
Squeeze the lamb into meatballs, and add into the wok

0:04:59.004,0:05:02.286
丸子全部下入锅中之后开始转小火煮3分钟
After that, simmer for 3 minutes

0:05:02.748,0:05:05.225
同学们切记丸子下锅之后不能开大火煮
Note that do not boil the meatballs with high heat

0:05:06.683,0:05:08.661
否则丸子特别容易被冲烂
Otherwise, the meatballs may easily break down

0:05:17.962,0:05:20.390
起锅之前我们在碗中撒入适量的葱花
Before serving, put some chopped scallion into the bowl 

0:05:20.758,0:05:22.997
当然了喜欢香菜的同学也可以放
Of course, you can use cilantro if you prefer

0:05:23.388,0:05:25.450
然后我们把汤里面的小葱捡出来
Then we pick up the scallion from the soup

0:05:25.793,0:05:26.931
下面开始调味
Next, add seasonings

0:05:27.239,0:05:28.886
锅中加入少许的食用盐
Add a little salt into the wok

0:05:29.052,0:05:31.492
然后再加入少许胡椒粉就可以出锅
And add a little white pepper powder. Then it's ready!

0:05:48.193,0:05:49.280
舀点汤来喝看
Let's have some soup

0:05:49.335,0:05:50.459
我来给你舀 四伯爷
I'll serve you, uncle

0:05:52.169,0:05:53.125
吃点羊肉丸嘛
Have some lamb meatballs

0:05:53.543,0:05:54.110
要的呀
Sure

0:05:54.714,0:05:56.182
我给你舀一碗
I'll serve you

0:05:57.222,0:05:58.560
羊肉来整的呀这是
Is this lamb?

0:05:58.560,0:05:59.507
嗯 羊肉丸子
Yeah, lamb meatballs

0:06:01.198,0:06:01.969
现宰的
Fresh lamb

0:06:03.111,0:06:04.273
我尝看有盐味没得多
Let me see if it's salty enough

0:06:05.332,0:06:06.521
盐味肯定是有的
It must be

0:06:06.521,0:06:07.638
有
Yeah

0:06:08.973,0:06:10.357
还多鲜这个味道
It's also very savory

0:06:10.701,0:06:11.463
肯定了
Of course

0:06:12.131,0:06:12.819
好 可以了可以了
Alright, good

0:06:14.129,0:06:14.556
安逸
Nice

0:06:16.312,0:06:16.925
好不好吃嘛
Is it tasty?

0:06:17.835,0:06:19.489
这次的羊肉是换值了的
This time the lamb was a good trade

0:06:22.336,0:06:23.008
好吃
Tasty!

0:06:24.263,0:06:26.000
我们这个汤特别鲜
We made the soup especially savory

0:06:26.363,0:06:28.053
特别是羊肉加进去了之后
Especially with the lamb in

0:06:28.601,0:06:32.048
其实你也可以理解成为这个鲫鱼汤加羊肉
Actually, you can also understand it as a "ji yu" carp soup with lamb

0:06:32.986,0:06:33.404
是吧
Right?

0:06:34.305,0:06:35.401
为什么叫鲜汤呢
Why do we call it the savory soup?

0:06:35.401,0:06:38.095
就是因为有鱼有羊
Because there are fish and lamb
(The Chinese character for "savory" consists of "fish" and "lamb" particles)

0:06:38.197,0:06:40.260
这样鲜汤拿来下面吃肯定安逸哦
If we make a noodle soup with the savory soup, that'll be nice!

0:06:40.520,0:06:41.254
必须的撒
Definitely

0:06:45.127,0:06:46.075
它都想吃
It also wanna eat

0:06:47.022,0:06:49.679
你吃 我都没吃好多点 你吃
You wanna eat? I haven't enjoyed yet, but you wanna eat?

0:06:50.552,0:06:53.265
我们的狗在旁边馋得不行了已经
Our dog is drooling next to us

0:06:53.293,0:06:54.184
它想吃
It wanna eat

0:06:57.594,0:06:59.294
我给你多舀点这个丸子
Let me serve you some more meatballs

0:07:00.919,0:07:01.486
来 伯爷
Here, uncle

0:07:02.062,0:07:05.666
这个东西弄来下面可能相当舒服哦吃起
If we make some noodles with it, that should be pretty good

0:07:05.703,0:07:06.669
伯娘 舀哦
Here, aunt

0:07:07.050,0:07:07.682
我自己舀
I can help myself

0:07:08.267,0:07:09.187
要得
Sure

0:07:09.187,0:07:09.595
你舀来吃嘛
Help yourself

0:07:09.595,0:07:10.692
要得 你自己舀嘛
Sure, help yourself

0:07:11.035,0:07:11.463
安逸
Nice

0:07:15.030,0:07:16.972
好了 大家如果对这个感兴趣的话
Alright. If you are interested

0:07:16.972,0:07:18.366
一定在家里面试一下
Please try it at home

0:07:18.739,0:07:19.730
如果买不到羊肉的话
If you can't get lamb

0:07:19.730,0:07:22.354
可以买那个猪肉也可以啊
You can also use pork instead

0:07:22.602,0:07:22.851
对不对
Right?

0:07:22.851,0:07:23.590
羊肉虽然贵
Although lamb is expensive...

0:07:23.590,0:07:25.516
但是猪肉也不便宜嘎
Pork isn't cheap, either

0:07:26.351,0:07:28.125
猪肉也没得好相因（便宜）的呀
Pork isn't quite cheap, right?

0:07:28.484,0:07:29.900
不好意思 打扰了
Sorry, my mistake

0:07:33.483,0:07:34.753
好了 本期视频就到这里
Alright, that's all for this episode

0:07:35.174,0:07:35.492
拜拜
Bye bye!

0:07:38.964,0:07:39.475
再喝一碗
One more bowl
