### ISSUE TITLE
[华农兄弟] 华农兄弟小竹林长满了笋掰点回去烤又香又辣很好吃哦 - https://youtu.be/F55nkfTTWWg

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#878]
https://youtu.be/F55nkfTTWWg
<p>&#35270;&#39057;&#21457;&#24067;&#20110; April 3, 2020 at 08:01PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload 
#https://youtu.be/F55nkfTTWWg

#华农兄弟：小竹林长满了笋，掰点回去烤，又香又辣，很好吃哦
#Huanong Brothers: The bamboo shoots are all over the bamboo forest. We pick some home and grill them with chilli sauce. Tasty!

0:00:00.000,0:00:02.480
# 大家好  今天去拔點那個竹笋
Hi everyone. Today we're gonna pick some, you know, some bamboo shoots.

0:00:02.480,0:00:03.540
# 你看  這個竹笋
Look! The bamboo shoots

0:00:03.820,0:00:05.920
# 像這 這邊竹林里面好多的哦  這個
There are a lot in the, like, the bamboo forest over there.

0:00:06.500,0:00:08.360
# 但是都不知道有沒有
But I don't know if there are still any.

0:00:08.660,0:00:09.420
# 沒去看
I didn't check.

0:00:14.020,0:00:15.880
# 你看  這好密啊  這個竹子
Look! It's really dense, the bamboo.

0:00:16.180,0:00:17.620
# 竹子都長到田裡面來啦
The bamboos are already growing onto the farm.

0:00:18.720,0:00:20.880
# 要拔掉一些  不要  不要那麼多
I need to clear some of them. I, I don't need so many.

0:00:22.420,0:00:23.900
# 這個  搞個嫩的來
Well, let me get the younger ones.

0:00:24.640,0:00:25.300
# 老的就
And the old ones,

0:00:25.640,0:00:26.680
# 老的就不要啦
I don't want the old ones,

0:00:28.440,0:00:30.040
# 小的也不要  挑大的
nor the small ones. I want the big ones.

0:00:34.880,0:00:35.520
# 你看
Look!

0:00:35.800,0:00:36.560
# 這個
It's ah...

0:00:49.760,0:00:50.940
# 這個就嫩一點  這個
This one is younger, this one.

0:00:51.840,0:00:53.300
# 這都是長高啦
It's already rather tall now.

0:00:53.840,0:00:55.560
# 這個也可以吃的  這個  你看
This one is also edible. This one, look!

0:00:58.540,0:01:00.380
# 一搞就碎掉啦  可以的
You can crush it by hands. It's edible.

0:01:02.220,0:01:02.980
# 還不老的
And it's not old.

0:01:10.280,0:01:11.060
# 好多哇
A lot!

0:01:15.500,0:01:16.520
# 這裡好多  這裡
Here are a lot, here.

0:01:21.980,0:01:23.540
# 這個小的也不放過
I'm not not forgoing any, not even the small ones.

0:01:30.360,0:01:31.500
# 好多哇  這個
Really a lot!

0:01:32.400,0:01:33.520
# 都沒人吃
Nobody wants them.

0:01:34.500,0:01:35.700
# 不是沒人吃
Ah no! I mean,

0:01:37.540,0:01:38.960
# 長太多啦  吃不完
there are just too many. It's impossible to finish them.

0:01:47.140,0:01:48.920
# 你看  這個  好肥
Look! This is, so fat!

0:01:49.360,0:01:49.940
# 哎呀
Aya!

0:01:51.080,0:01:52.040
# 剝開來看一下
Let me peel it and have a look inside.

0:01:56.260,0:01:57.100
# 這個肉  (註︰這個「肉」字沒有很好的翻譯，所以改一下用字，表達到讚嘆就行了)
Marvelous!

0:01:57.660,0:01:58.520
# 看上去都
It looks really,

0:01:59.060,0:02:00.620
# 看上去 好吃
it looks really, tasty.

0:02:08.100,0:02:09.380
# 哦  就這一點點
Oh! So just a tiny little bit.

0:02:09.840,0:02:11.260
# 吃的話就吃這麼一點點
the edible part is just a tiny little bit here.

0:02:12.980,0:02:14.060
# 哎呀  這裡一個
Aya! Here's one.

0:02:20.320,0:02:22.780
# 你看  這個  這個超大吧  這個不要啦
Look! This is, this is oversized, isn't it? I don't want it.

0:02:24.880,0:02:25.600
# 這邊
And here,

0:02:25.800,0:02:26.500
# 好多
a lot!

0:02:28.620,0:02:29.960
# 超大的就不要
I don't want the oversized ones.

0:02:34.320,0:02:35.740
# 這個要拔掉一些
Some of these shoots need to be cleared.

0:02:36.340,0:02:37.420
# 如果不拔掉的話
The bamboo would be too dense,

0:02:37.980,0:02:39.180
# 這竹子太密啦
if we don't clear some of the shoots.

0:02:39.580,0:02:40.460
# 它會死掉的
They can't survive.

0:02:40.540,0:02:41.960
# 這竹子都會死的
What's more, the bamboo would die,

0:02:42.920,0:02:43.960
# 和竹笋
together with the shoots.

0:02:48.480,0:02:49.700
# 你看  有3個
Look! Here are three.

0:02:58.440,0:02:59.360
# 這兩個
And these two...

0:03:01.720,0:03:02.860
# 越講越多啊
There are more to come.

0:03:05.140,0:03:06.080
# 好多哇
A lot!

0:03:31.540,0:03:33.720
# 你看  搞了幾分鐘就搞了桶啦
Look! I now have a whole bucket in just a couple of minutes.

0:03:34.660,0:03:35.840
# 這個  這個笋
This, this shoot,

0:03:36.520,0:03:38.440
# 還沒老  你看  一折就斷掉
is still young. Look! It can be broken easily.

0:03:38.580,0:03:39.940
# 說明還很嫩的
It means that it's still very young.

0:03:40.740,0:03:41.880
# 好啦  不要啦
Alright! It's enough.

0:03:43.740,0:03:45.260
# 那麼多 都吃不完
So many here. I don't think I can finish them.

0:03:45.940,0:03:48.140
# 回去送點給  送點給老人家吃
I'll give some, give some to the elderly.

0:03:53.640,0:03:55.680
# 這個是前兩天掰得這個竹笋
These are the bamboo shoots that we picked a couple of days ago.

0:03:59.580,0:04:00.320
# 我們用來
We're gonna,

0:04:00.820,0:04:01.480
# 烤一下
grill them.

0:04:03.200,0:04:04.060
# 搞嫩的來
Let me pick the younger ones.

0:04:10.400,0:04:11.440
# 搞個3條
I'll pick three.

0:04:14.740,0:04:15.680
# 3條就行啦
Three would be enough for us.

0:04:16.920,0:04:18.140
# 先過一下水
It needs to be boiled in the water first.

0:04:19.140,0:04:20.540
# 這個笋沒有過水的哦
The bamboo shoots would taste a bit astringent, 

0:04:20.540,0:04:21.560
# 不過水的話就
a bit astringent,

0:04:22.180,0:04:23.240
# 會有點澀澀的
if they're not boiled in the water first.

0:04:41.060,0:04:41.940
# 搞3條
Let's have three.

0:04:43.340,0:04:44.440
# 這一下水 這個
Boil them in the water, well.

0:04:49.220,0:04:50.200
# 蓋著它就好
Cover it, and wait.

0:04:58.860,0:05:00.520
# 那只狗  下雨啦
The dog... It's raining now.

0:05:00.940,0:05:02.280
# 給它披了一個雨衣
So I've given her a raincoat.

0:05:02.780,0:05:04.240
# 這樣就不會淋  淋濕
Then she won't, she won't get wet,

0:05:04.340,0:05:05.300
# 淋濕身上
all over the body.

0:05:08.760,0:05:11.240
# 呵  這  這個胖了好多哇  現在
Ho! The, the dog is getting much fatter now.

0:05:15.960,0:05:16.460
# 走
Let's go!

0:05:16.740,0:05:17.240
# 走
Let's go!

0:05:23.620,0:05:25.480
# 哇 熟啦 熟啦 熟啦 熟啦
Wa! Alright, alright, alright, alright!

0:05:26.200,0:05:28.060
# 這個笋  拿過來就行啦
So I'll put the bamboo shoots here.

0:05:34.080,0:05:36.200
# 可以 我把它用鍚紙把它裹起來
Alright! I'm gonna, wrap it, wrap it up with foil.

0:05:52.380,0:05:53.980
# 把它壓扁就後把它
I press it first, and then,

0:05:55.080,0:05:55.760
# 就這樣
I mean,

0:05:56.840,0:05:58.020
# 把它分成幾份
tear it into pieces.

0:06:01.780,0:06:02.820
# 可以 可以
Alright! Alright!

0:06:04.000,0:06:05.780
# 我拿鍚紙來  把它裹起來
I'll fetch the foil, and wrap them up.

0:06:12.040,0:06:12.920
# 把這個鍚紙
The foil,

0:06:13.340,0:06:14.700
# 竹笋  這樣子
and the bamboo shoots. Put them here.

0:06:15.640,0:06:17.060
# 放著  然後再來
Place them well, and then,

0:06:18.080,0:06:20.300
# 烤一烤  烤一下  肯定很好吃
grill them, grill them. It must be very tasty.

0:06:23.980,0:06:25.120
# 搞點辣椒醬去
Let me put some chilli sauce.

0:06:29.100,0:06:29.880
# 哎喲
Ayo!

0:06:30.120,0:06:30.740
# 這樣就
That's it!

0:06:31.460,0:06:32.660
# 看上去就有食欲
It looks really appetizing!

0:06:33.760,0:06:35.000
# 就是不知道辣不辣
But I wonder if it's spicy enough.

0:06:41.120,0:06:42.140
# 搞點辣椒油  (註︰其實這只是辣椒醬肉的汁，但不知怎麼譯)
Put some capsicol.

0:07:10.740,0:07:11.780
# 好啦  就這樣烤
Alright! We can grill it now.

0:07:13.020,0:07:14.300
# 烤出來肯定很好吃
It must be really tasty.

0:07:20.940,0:07:21.980
# 這樣可以啦
So everything is ready now.

0:07:31.500,0:07:32.320
# 這樣搖一下它
Let me roll it here.

0:07:32.460,0:07:32.960
# 那個
So that,

0:07:33.220,0:07:34.980
# 辣椒 辣椒就比較均勻
the chilli, the chilli can be more evenly spread.

0:07:35.160,0:07:36.840
# 辣醬啊  就比較均勻
I mean the chilli sauce, can be more evenly spread.

0:07:37.440,0:07:38.200
# 搓兩下
So rub it,

0:07:38.740,0:07:39.680
# 給它按按摩
and give it a massage.

0:07:46.080,0:07:48.320
# 這個烤個十來二十分鐘就夠啦
Grill it for ten to twenty minutes, and it's done.

0:07:50.120,0:07:52.080
# 嗯  放在這裡  不用管啦
Um! Put it here. Leave it alone.

0:07:58.180,0:08:00.100
# 你看 這個該烤熟啦
Look! It should be alright now.

0:08:01.600,0:08:02.440
# 很香哦
It smells so good!

0:08:02.800,0:08:03.800
# 我拿到裡面去吃
I'll enjoy it inside.

0:08:11.080,0:08:12.460
# 聞起來就好有味道啊
The aroma is rather significant.

0:08:12.780,0:08:13.620
# 好香啊
It smells really good!

0:08:24.500,0:08:25.120
# 看上去
It looks...

0:08:26.880,0:08:27.860
# 好香哦
It smells great!

0:08:30.160,0:08:31.160
# 搞快來吃一下
Let me get a piece.

0:08:35.120,0:08:36.340
# 好燙  好燙 好燙
Hot, hot hot!

0:08:50.860,0:08:52.060
# 嗯  可以
Um! Not bad!

0:08:54.220,0:08:55.200
# 很好吃哦
It's really tasty!

0:09:01.720,0:09:03.120
# 這個  這個竹笋
The, the bamboo shoots,

0:09:03.800,0:09:05.060
# 它這樣做是很好吃的
are really tasty when they're grilled.

0:09:06.100,0:09:06.740
# 就是
A bit,

0:09:07.140,0:09:07.980
# 少了一點那個
a bit more oil,

0:09:08.460,0:09:09.560
# 應該是少了一點油
a bit more oil would make it perfect.

0:09:11.460,0:09:12.080
# 很嫩
It's really young.

0:09:14.940,0:09:15.940
# 口咬就斷
So crunchy

0:09:23.680,0:09:24.380
# 有點辣
It's a bit spicy.

0:09:25.200,0:09:27.320
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.

0:09:32.240,0:09:32.780
# 再吃一個
I'll have one more.

0:09:38.600,0:09:39.360
# 搞點辣椒來
Let me fetch some chilli.

**Comment by vincenthychow** [comment]
已發佈
