### ISSUE TITLE
【美食作家王刚】双色豆腐 - https://youtu.be/MVujhtg3fY8

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#879]
**视频链接**：https://youtu.be/MVujhtg3fY8

视频时长 3:49，预计发布时间为北京时间4月6日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“双色家常豆腐”的做法，豆腐软嫩，猪血弹牙（不辣）

简介
同学好，今天和大家分享一道家常菜“双色豆腐”，分别选用老豆腐和猪血为主料，有很多地区因为猪血的性状所以也称其为血豆腐，这就契合了这道“双色豆腐”的菜名了。这道菜的做法步骤和经典川菜麻婆豆腐相似，都是将豆腐焯水之后加入用肉末炒香的汤汁中炖煮，最后用将汤汁调成厚芡包裹在豆腐表面，不过味型差别很大，但依然好吃，尤其是两种豆腐的口感差别很大可以给出不一样的感觉。

本期菜品：【双色豆腐】
【主料】
老豆腐（约400克）
猪血；血豆腐（几块）
鲜牛肉（100克）
【辅料】
西红柿（1个）
大蒜（几颗）
小葱头（几根）
植物油（适量）
水淀粉（适量）
明油（少许）
【调味料】
食用盐（适量）
白糖（少许）
胡椒粉（约1克）
蚝油（10克）

字幕
0:00:00.160,0:00:01.260
哈喽大家好 我是王刚

0:00:01.260,0:00:03.320
本期视频我给大家分享一道家常菜

0:00:03.700,0:00:04.580
双色豆腐

0:00:05.180,0:00:07.080
首先我们准备老豆腐1大块（约400克）

0:00:07.293,0:00:10.922
从中间切开之后重新叠在一起切成小正方形备用

0:00:27.087,0:00:30.213
准备猪血几块以同样的方法切成小正方形备用

0:00:36.379,0:00:39.347
准备鲜牛肉100克切成小条之后剁碎备用

0:00:44.952,0:00:46.756
下一步开始准备辅料

0:00:46.756,0:00:48.829
准备西红柿1个从中间切开

0:00:48.829,0:00:50.556
然后再切成小粒备用

0:01:04.990,0:01:07.754
准备大蒜几颗拍散之后剁碎备用

0:01:13.151,0:01:15.047
准备小葱头几根切碎备用

0:01:15.787,0:01:16.588
下一步开始制作

0:01:17.037,0:01:18.893
首先我们在锅中加入适量的清水

0:01:19.681,0:01:20.778
加入食用盐2勺

0:01:25.584,0:01:28.557
然后加入切好的猪血和豆腐下锅焯水1分钟

0:01:35.863,0:01:37.981
水开之后（锅）离火将豆腐浸泡1分钟

0:01:38.529,0:01:40.746
这一步的目的是让豆腐和猪血更嫩

0:01:44.816,0:01:46.275
1分钟之后倒出控水备用

0:01:46.692,0:01:48.261
下一步开始准备炒辅料

0:01:48.678,0:01:49.939
首先我们把锅烧热

0:01:50.411,0:01:52.413
锅烧热之后加入适量的油滑锅

0:01:54.657,0:01:56.401
滑好锅之后将热油倒出

0:01:57.092,0:01:58.584
热油倒出之后加入适量的底油

0:02:01.130,0:02:04.377
油温5成热之后将剁好的牛肉末下锅炒香爆干水份

0:02:11.914,0:02:14.668
牛肉爆香之后加入切好的蒜末和西红柿

0:02:17.827,0:02:20.120
然后转中小火将西红柿翻炒1分钟

0:02:20.559,0:02:22.654
这一步的目的是去除西红柿的酸味

0:02:23.763,0:02:25.781
西红柿炒香之后加入适量的清水

0:02:29.138,0:02:30.356
下一步开始调味

0:02:31.640,0:02:33.077
锅中加入食用盐1勺（约3克）

0:02:34.086,0:02:35.425
加入少许的白糖

0:02:36.489,0:02:37.641
加入胡椒粉1克

0:02:38.639,0:02:39.846
加入蚝油10克

0:02:42.896,0:02:45.211
然后将焯好水的豆腐下锅烧3分钟

0:02:52.649,0:02:55.370
烧至2分钟的时候加入适量的水淀粉勾成薄芡

0:03:01.524,0:03:04.410
然后烧至3分钟的时候再加入少许的水淀粉勾芡

0:03:04.673,0:03:08.019
间隔勾芡2次可以防止成菜之后豆腐的水份溢出

0:03:10.444,0:03:13.252
勾好芡之后再加入少许的明油即可出锅装盘

0:03:23.560,0:03:26.320
一道非常简单美味的双色豆腐就制作完成

0:03:31.740,0:03:48.440
下面开始技术总结
第一，此菜可以加牛肉末或者猪肉末制作
第二，西红柿必须多翻炒几下去酸，否则成菜之后会有一股异常的酸味
第三，此菜不可添加鸡精味精，可以适当的多加一些蚝油调鲜味
双色豆腐的技术总结完毕


```

**Comment by siyusun6918** [comment]
认领

**Comment by siyusun6918** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“双色家常豆腐”的做法，豆腐软嫩，猪血弹牙（不辣）
Chef Wang teaches you how to make “Two-color Tofu” (not spicy) with tofu and pork blood.

简介
同学好，今天和大家分享一道家常菜“双色豆腐”，分别选用老豆腐和猪血为主料，有很多地区因为猪血的性状所以也称其为血豆腐，这就契合了这道“双色豆腐”的菜名了。这道菜的做法步骤和经典川菜麻婆豆腐相似，都是将豆腐焯水之后加入用肉末炒香的汤汁中炖煮，最后用将汤汁调成厚芡包裹在豆腐表面，不过味型差别很大，但依然好吃，尤其是两种豆腐的口感差别很大可以给出不一样的感觉。
Hello, today I’m going to share with you this family-style dish “Two-color Tofu”, which uses firm tofu and pork blood as mean ingredients. Due to the characteristics of pork blood, in some places, it’s also called blood tofu. That’s why this dish is called “two-color tofu”. The way to cook this dish is similar to the classic Sichuan cuisine “Mapo Tofu”. They both blanch the tofu first, then stew it in ground meat soup. After that, thicken the gravy to cover the surface of tofu. But the favor and look between those two dishes are different. “Two-color Tofu” is delicious, especially the different textures between two kinds of tofu that will bring you a unique experience. 

本期菜品：【双色豆腐】
【主料】
老豆腐（约400克）
猪血；血豆腐（几块）
鲜牛肉（100克）
【辅料】
西红柿（1个）
大蒜（几颗）
小葱头（几根）
植物油（适量）
水淀粉（适量）
明油（少许）
【调味料】
食用盐（适量）
白糖（少许）
胡椒粉（约1克）
蚝油（10克）
【Two-color Tofu】
【Main ingredient】
Firm Tofu (about 400 gram)
Pork Blood; Blood Tofu (a few pieces)
Fresh Beef (100 gram)
【Other ingredient】
Tomato (one)
Garlic (a few cloves)
Scallions(a few)
Vegetable Oil 
Slurry 
Ming You (literally "oil for a shiny presence")
【Seasoning】
Salt
White Sugar
White Pepper Powder (about 1 gram)
Oyster Sause (about 10 gram)

字幕
0:00:00.160,0:00:01.260
哈喽大家好 我是王刚
Hello everyone, I am Chef Wang

0:00:01.260,0:00:03.320
本期视频我给大家分享一道家常菜
Today I’m going to share with you a family-style dish 

0:00:03.700,0:00:04.580
双色豆腐
Two-color Tofu

0:00:05.180,0:00:07.080
首先我们准备老豆腐1大块（约400克）
First, we prepare a piece of firm tofu (about 400 gram)

0:00:07.293,0:00:10.922
从中间切开之后重新叠在一起切成小正方形备用
Cut it half, pile together then cut it into cubes 

0:00:27.087,0:00:30.213
准备猪血几块以同样的方法切成小正方形备用
Prepare a few pieces of pork blood and cut into cubes the same way

0:00:36.379,0:00:39.347
准备鲜牛肉100克切成小条之后剁碎备用
Prepare 100 gram of fresh beef, cut into strips then chop them 

0:00:44.952,0:00:46.756
下一步开始准备辅料
Next step, prepare the side ingredients 

0:00:46.756,0:00:48.829
准备西红柿1个从中间切开
Prepare a tomato, cut it in half 

0:00:48.829,0:00:50.556
然后再切成小粒备用
Then dice it 

0:01:04.990,0:01:07.754
准备大蒜几颗拍散之后剁碎备用
Crush a few cloves of garlic, then chop them

0:01:13.151,0:01:15.047
准备小葱头几根切碎备用
Cut up some scallions 

0:01:15.787,0:01:16.588
下一步开始制作
Next step, we start to cook 

0:01:17.037,0:01:18.893
首先我们在锅中加入适量的清水
First, we add enough water to the wok 

0:01:19.681,0:01:20.778
加入食用盐2勺
Add two spoon of salt 

0:01:25.584,0:01:28.557
然后加入切好的猪血和豆腐下锅焯水1分钟
Then blench the pork blood and tofu for 1 minute 

0:01:35.863,0:01:37.981
水开之后（锅）离火将豆腐浸泡1分钟
When the water boils, remove the wok from the flame,  soak the tofu for another 1 minute 

0:01:38.529,0:01:40.746
这一步的目的是让豆腐和猪血更嫩
The purpose is to make tofu and pork blood more tender 

0:01:44.816,0:01:46.275
1分钟之后倒出控水备用
After a minute, take them out and drain out the water 

0:01:46.692,0:01:48.261
下一步开始准备炒辅料
Next, we start to prepare the side ingredients 

0:01:48.678,0:01:49.939
首先我们把锅烧热
First, we heat up the wok 

0:01:50.411,0:01:52.413
锅烧热之后加入适量的油滑锅
After wok is heated, add some oil to rinse the wok 

0:01:54.657,0:01:56.401
滑好锅之后将热油倒出
pull out the hot oil after rinsing the wok 

0:01:57.092,0:01:58.584
热油倒出之后加入适量的底油
Pull out the hot oil, then add some base oil 

0:02:01.130,0:02:04.377
油温5成热之后将剁好的牛肉末下锅炒香爆干水份
When the oil is half heated up, put ground beef into the wok, cook it until it sweats out 

0:02:11.914,0:02:14.668
牛肉爆香之后加入切好的蒜末和西红柿
After the beef smells down, add chopped garlic and tomato

0:02:17.827,0:02:20.120
然后转中小火将西红柿翻炒1分钟
Turn to mid-low heat and cook the tomato for a minute 

0:02:20.559,0:02:22.654
这一步的目的是去除西红柿的酸味
The purpose is to get rid of the sourness from the tomato 

0:02:23.763,0:02:25.781
西红柿炒香之后加入适量的清水
After the tomato is cooked, add some water 

0:02:29.138,0:02:30.356
下一步开始调味
Next step is to season

0:02:31.640,0:02:33.077
锅中加入食用盐1勺（约3克）
Add a spoon of salt (about 3 gram) into the wok

0:02:34.086,0:02:35.425
加入少许的白糖
Add some white sugar 

0:02:36.489,0:02:37.641
加入胡椒粉1克
Add 1 gram of white pepper powder 

0:02:38.639,0:02:39.846
加入蚝油10克
Add 10 gram of oyster sauce 

0:02:42.896,0:02:45.211
然后将焯好水的豆腐下锅烧3分钟
Then put the blenched tofu into the wok and cook for 3 minutes 

0:02:52.649,0:02:55.370
烧至2分钟的时候加入适量的水淀粉勾成薄芡
After two minutes, add some slurry to thicken a little 

0:03:01.524,0:03:04.410
然后烧至3分钟的时候再加入少许的水淀粉勾芡
After the third minute, add some more slurry to thicken into gravy 

0:03:04.673,0:03:08.019
间隔勾芡2次可以防止成菜之后豆腐的水份溢出
Double thickening can prevent the water from the tofu spill all over after the dish is done 

0:03:10.444,0:03:13.252
勾好芡之后再加入少许的明油即可出锅装盘
After thickening, add some Ming You (oil for a shiny presence), then decorate the dish 

0:03:23.560,0:03:26.320
一道非常简单美味的双色豆腐就制作完成
A simple yet delicious “Two-color Tofu” is done 

0:03:31.740,0:03:48.440
下面开始技术总结
第一，此菜可以加牛肉末或者猪肉末制作
第二，西红柿必须多翻炒几下去酸，否则成菜之后会有一股异常的酸味
第三，此菜不可添加鸡精味精，可以适当的多加一些蚝油调鲜味
双色豆腐的技术总结完毕
Conclusion
First, this dish can be cooked with either ground beef or ground pork
Second, the tomato has to be cooked longer to get rid of the sourness, or the dish will be weirdly sour 
Thirdly, this dish should not add chicken bouillon, you can add more oyster sauce to increase the umami favor 
That’s all for the conclusion of “Two-color Tofu”
