### ISSUE TITLE
【美食作家王刚】炸鸡翅 - https://youtu.be/LW41chCdtBs

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#880]
**视频链接**：https://youtu.be/LW41chCdtBs

视频时长 6:13，预计发布时间为北京时间4月7日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“炸鸡翅”的简单快捷做法，外壳酥脆，肉汁丰富，四伯评价很高！

简介
四伯四伯娘没怎么出过老家，真的没吃过肯德基麦当劳，
但总觉得有机会可以让老人们了解一下现在年轻人吃的东西，
看看年轻人都拿什么来配啤酒😂
其实效果还不错，四伯给的评价还是很高的，
果真食物是不分国界的，好吃就是好吃！
当然这炸鸡翅的做法肯定不是为了复制肯德基或者麦当劳，
只是给大家分享一个简单快捷的做法，
毕竟这道菜好不好吃在于火候，做到外壳酥脆，
肉不柴并且脱骨，就一定会好吃，
希望大家喜欢，有机会也可以在家尝试。

字幕
0:00:00.425,0:00:01.175
哈喽大家好

0:00:01.750,0:00:03.825
我买了12个这个鸡翅

0:00:03.925,0:00:06.725
买回来做炸鸡翅给我伯爷吃

0:00:06.850,0:00:13.700
因为他这个年龄也不会去肯德基麦当劳去买这种炸鸡翅来吃

0:00:13.875,0:00:15.275
好 我先把它腌一下

0:00:16.725,0:00:19.025
腌的话这个切一下就可以了

0:00:20.775,0:00:22.575
你看我们自己买的好大个哦

0:00:25.075,0:00:28.425
然后再切点这个姜 切到这个里面腌一下

0:00:30.250,0:00:31.600
放点葱在这个里头

0:00:31.800,0:00:34.015
这个可以自己喂的土鸡来搞

0:00:34.025,0:00:35.550
搞起害怕更安逸哦

0:00:36.700,0:00:39.075
一个鸡只长一对这个（鸡翅）

0:00:39.175,0:00:42.425
你要吃一顿的话你要喂好多（鸡）哦

0:00:42.700,0:00:44.025
我们先给它放点料酒

0:00:44.050,0:00:45.775
一个鸡两个腿腿儿撒

0:00:47.550,0:00:48.825
翅膀不是腿腿儿

0:00:49.075,0:00:50.300
两个翅膀嘛

0:00:50.556,0:00:51.550
再放点蚝油

0:00:54.025,0:00:57.575
我们再加一勺盐 可以略微咸那么一点点

0:00:59.050,0:00:59.802
给它抓匀

0:01:02.625,0:01:05.325
然后我们调这个糊用的鸡蛋哦四伯爷

0:01:05.525,0:01:06.700
要得 

0:01:06.750,0:01:07.750
打2个鸡蛋

0:01:08.125,0:01:09.400
用鸡蛋还不好啊

0:01:10.625,0:01:12.950
抓一把面粉 大概半斤

0:01:13.150,0:01:16.525
然后我们再放一点牛奶 这样炸出来更香

0:01:17.375,0:01:19.275
然后把它搅拌均匀

0:01:23.050,0:01:24.075
嗯 可以了

0:01:24.325,0:01:26.475
盛起来它能够成1条线下去就可以了

0:01:26.600,0:01:28.700
然后我们再准备一点面包糠

0:01:29.050,0:01:30.275
这个就是面包糠

0:01:30.275,0:01:32.900
面包糠这个跟我们的米糠不一样

0:01:33.075,0:01:34.550
你不要以为这个是米糠

0:01:37.075,0:01:39.625
好 然后拿这个鸡翅出来

0:01:39.775,0:01:43.375
把它的水份稍微地挤那么一下

0:01:43.925,0:01:45.300
然后放到这个里面 

0:01:45.750,0:01:47.500
放到里面让它过（裹）一下

0:01:48.650,0:01:49.950
我们这个水份一定要挤干

0:01:49.950,0:01:53.016
要不然会导致这个糊过稀

0:01:53.350,0:01:56.325
好 现在我们把它抓匀

0:01:56.750,0:01:58.600
让它充分的挂上这个糊

0:01:59.798,0:02:02.239
嘿 看都还多漂亮噶

0:02:04.008,0:02:07.368
然后我们上好糊了之后先暂时不要到（面包糠）里面滚

0:02:07.502,0:02:10.212
我们把油烧好了之后这样子拿起来

0:02:10.414,0:02:12.228
滚一个放一个 滚一个放一个

0:02:12.698,0:02:15.901
因为你现在滚了的话 弄得比较脏

0:02:16.954,0:02:19.216
来嘛 我弄过去开始炸了

0:02:20.358,0:02:21.500
告（试）哈看嘛

0:02:55.700,0:02:59.252
四伯爷你看 这个炸黄了是不是

0:02:59.300,0:03:01.204
先拿（放）下去的就黄了 

0:03:01.245,0:03:03.102
对 先拿下去的就黄了

0:03:03.337,0:03:05.334
把有点黄的先漏起来

0:03:39.623,0:03:41.267
要可以了哦四伯爷

0:03:41.267,0:03:43.009
可以就可以了撒

0:04:00.254,0:04:00.933
可以了

0:04:10.744,0:04:13.936
你掰开嘛 你吃辣椒不哦 弄点海椒（面）来蘸

0:04:13.936,0:04:14.559
不要不要

0:04:17.841,0:04:19.756
嘿 还把它炸脆了安

0:04:21.200,0:04:23.024
好不好吃嘛 掰了来吃撒

0:04:24.437,0:04:26.154
好吃安 好吃啊

0:04:26.428,0:04:27.249
弄点海椒面

0:04:27.568,0:04:28.339
我不要海椒面

0:04:28.343,0:04:29.452
你不蘸啊 蘸哈嘛

0:04:30.744,0:04:32.340
这个它放了盐（腌）的

0:04:34.392,0:04:35.683
蘸不起哦有可能

0:04:40.015,0:04:41.975
嗯好吃 不消蘸的 

0:04:42.021,0:04:42.826
可以蘸哈

0:04:43.085,0:04:43.860
（蘸了）有点辣

0:04:43.966,0:04:44.741
够不够味嘛

0:04:44.878,0:04:45.273
够味

0:04:45.699,0:04:47.188
这中间很嫩

0:04:50.227,0:04:52.249
掰开 掰开了蘸这个海椒

0:04:58.419,0:04:59.422
我还是再吃点

0:04:59.939,0:05:02.644
嗯 这个海椒面蘸起味道又不一样安

0:05:02.689,0:05:05.395
我们这个炸出来的话水份全部被锁在里面了

0:05:05.455,0:05:06.854
里面都是很嫩很嫩的

0:05:18.890,0:05:22.184
我们炸这个的时候一定要开中小火去浸炸

0:05:22.249,0:05:25.790
如果是火太大的话 外面的糊了中间的还没熟

0:05:26.869,0:05:28.632
如果炖来干（吃）嘛还是绵的

0:05:28.647,0:05:30.045
这样炸起还不绵

0:05:31.048,0:05:31.560
是不哦

0:05:31.884,0:05:34.148
是啊 还脱骨还多安逸

0:05:36.048,0:05:37.811
好了本期视频就先到这里

0:05:38.738,0:05:40.881
我们吃（剩）的这个骨头拿给狗儿吃

0:05:41.519,0:05:42.720
看 这个肉好嫩哦

0:05:48.100,0:05:48.981
你都吃了2个了啊

0:05:48.996,0:05:49.224
嗯

0:05:49.285,0:05:50.638
我拿去喂狗

0:05:53.966,0:05:54.513
狗儿喽 

0:05:56.413,0:05:59.696
来 我们吃肉你吃骨头

0:06:00.395,0:06:00.927
尝一下 

0:06:01.823,0:06:03.540
尝一下我们炸这个味道怎么样 

0:06:04.741,0:06:06.033
它还吃起多香噶
```

**Comment by immoonancient** [comment]
@iamatrollatrollisme 请记得前来认领

**Comment by iamatrollatrollisme** [comment]
认领

**Comment by iamatrollatrollisme** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“炸鸡翅”的简单快捷做法，外壳酥脆，肉汁丰富，四伯评价很高！
Executive Chef sharing easy “Fried Chicken wings”, juicy, tender and highly rated

简介
四伯四伯娘没怎么出过老家，真的没吃过肯德基麦当劳，
Uncle Four and his wife never really left hometown, never tasted KFC and McDonald’s

但总觉得有机会可以让老人们了解一下现在年轻人吃的东西，
Always feel like there’s always a chance for elders to taste what younger generations like to eat

看看年轻人都拿什么来配啤酒😂
You see nowadays young people love to eat anything with beer

其实效果还不错，四伯给的评价还是很高的，
It’s actually not bad, uncle four spoke highly of it

果真食物是不分国界的，好吃就是好吃！
Truly there is no border between food, delicious food is simply delicious food!

当然这炸鸡翅的做法肯定不是为了复制肯德基或者麦当劳，
Of course the fried chicken wing recipe is not for replicating KFC or McDonald’s

只是给大家分享一个简单快捷的做法，
I am just sharing a simple and easy way to make fried chicken wing

毕竟这道菜好不好吃在于火候，做到外壳酥脆，
After all whether or not the dish is delicious depending controlling the heat, to achieve crispy on the outside, juiciness on the inside

肉不柴并且脱骨，就一定会好吃，
Tender meat and east to bite off, very tasty

希望大家喜欢，有机会也可以在家尝试。
I hope everyone will like it and try at home


字幕
0:00:00.425,0:00:01.175
哈喽大家好
Hello everyone

0:00:01.750,0:00:03.825
我买了12个这个鸡翅
I bought 12 chicken wings

0:00:03.925,0:00:06.725
买回来做炸鸡翅给我伯爷吃
To make fried chicken wings for my uncle

0:00:06.850,0:00:13.700
因为他这个年龄也不会去肯德基麦当劳去买这种炸鸡翅来吃
Because I think he would not go to KFC or MacDonald’s for this kind of fried chicken wings

0:00:13.875,0:00:15.275
好 我先把它腌一下
Alright, let’s marinate them first

0:00:16.725,0:00:19.025
腌的话这个切一下就可以了
We slice a bit to marinate them better

0:00:20.775,0:00:22.575
你看我们自己买的好大个哦
The chicken wings we picked are quite big

0:00:25.075,0:00:28.425
然后再切点这个姜 切到这个里面腌一下
Then we slice some ginger, add them to marinate the chicken wings too

0:00:30.250,0:00:31.600
放点葱在这个里头
Add some green onions

0:00:31.800,0:00:34.015
这个可以自己喂的土鸡来搞
We can make this dish with our own free range chicken

0:00:34.025,0:00:35.550
搞起害怕更安逸哦
Using that chicken is better

0:00:36.700,0:00:39.075
一个鸡只长一对这个（鸡翅）
One chicken has one pair of wings

0:00:39.175,0:00:42.425
你要吃一顿的话你要喂好多（鸡）哦
Each fried chicken dishes you will need to use a lot of chickens

0:00:42.700,0:00:44.025
我们先给它放点料酒
Let’s add some chinese cooking wine first

0:00:44.050,0:00:45.775
一个鸡两个腿腿儿撒
Each chicken has 2 legs though

0:00:47.550,0:00:48.825
翅膀不是腿腿儿
Wings are not leggs

0:00:49.075,0:00:50.300
两个翅膀嘛
Two wings

0:00:50.556,0:00:51.550
再放点蚝油
Then we add some oyster sauce

0:00:54.025,0:00:57.575
我们再加一勺盐 可以略微咸那么一点点
We can add a teaspoon of salt, it can be a little more salty

0:00:59.050,0:00:59.802
给它抓匀
Mix it well

0:01:02.625,0:01:05.325
然后我们调这个糊用的鸡蛋哦四伯爷
Now we are using eggs to make the batter Uncle Four

0:01:05.525,0:01:06.700
要得 
Okay

0:01:06.750,0:01:07.750
打2个鸡蛋
Add two eggs

0:01:08.125,0:01:09.400
用鸡蛋还不好啊
It is nice to use eggs

0:01:10.625,0:01:12.950
抓一把面粉 大概半斤\
Grab a handful of flour, about 250g

0:01:13.150,0:01:16.525
然后我们再放一点牛奶 这样炸出来更香
Then we add some milk, it will make them smell better

0:01:17.375,0:01:19.275
然后把它搅拌均匀
Mix it very well

0:01:23.050,0:01:24.075
嗯 可以了
Okay finished


0:01:24.325,0:01:26.475
盛起来它能够成1条线下去就可以了
After we scoop the batter, it pours down in a straight line then it is ready

0:01:26.600,0:01:28.700
然后我们再准备一点面包糠
Then we prepare some bread crumbs

0:01:29.050,0:01:30.275
这个就是面包糠
These are the bread crumbs

0:01:30.275,0:01:32.900
面包糠这个跟我们的米糠不一样
Bread crumbs are different from rice crumbs

0:01:33.075,0:01:34.550
你不要以为这个是米糠
Do not assume this is rice crumb

0:01:37.075,0:01:39.625
好 然后拿这个鸡翅出来
Okay then, let’s take out the chicken wings

0:01:39.775,0:01:43.375
把它的水份稍微地挤那么一下
Squeeze the chicken wings a little bit

0:01:43.925,0:01:45.300
然后放到这个里面 
Then put them into the batter

0:01:45.750,0:01:47.500
放到里面让它过（裹）一下
Coat the chicken wing with batter 

0:01:48.650,0:01:49.950
我们这个水份一定要挤干
We must squeeze the water dry

0:01:49.950,0:01:53.016
要不然会导致这个糊过稀
Otherwise the batter will become too thin

0:01:53.350,0:01:56.325
好 现在我们把它抓匀
Okay, now let’s mix them well
0:01:56.750,0:01:58.600
让它充分的挂上这个糊
Let the chicken wings coat with batter completely

0:01:59.798,0:02:02.239
嘿 看都还多漂亮噶
See how beautiful they are

0:02:04.008,0:02:07.368
然后我们上好糊了之后先暂时不要到（面包糠）里面滚
Once they are coated with batter, we do not put them into the bread crumbs yet

0:02:07.502,0:02:10.212
我们把油烧好了之后这样子拿起来
We wait until we heat up the oil

0:02:10.414,0:02:12.228
滚一个放一个 滚一个放一个
We can coat them with bread crumbs one by one

0:02:12.698,0:02:15.901
因为你现在滚了的话 弄得比较脏
If you coat them right now, it gets the station messy

0:02:16.954,0:02:19.216
来嘛 我弄过去开始炸了
Okay, I am going to start frying

0:02:20.358,0:02:21.500
告（试）哈看嘛
Let’s try it

0:02:55.700,0:02:59.252
四伯爷你看 这个炸黄了是不是
Uncle Four you see, now it is fried to golden brown

0:02:59.300,0:03:01.204
先拿（放）下去的就黄了 
Once you put the wings into the wok, they are turning brown

0:03:01.245,0:03:03.102
对 先拿下去的就黄了
First ones that were put into the work have turn golden brown

0:03:03.337,0:03:05.334
把有点黄的先漏起来
We pick up the ones are golden brown

0:03:39.623,0:03:41.267
要可以了哦四伯爷
We are almost finished, Uncle

0:03:41.267,0:03:43.009
可以就可以了撒
Okay

0:04:00.254,0:04:00.933
可以了
It’s done cooking

0:04:10.744,0:04:13.936
你掰开嘛 你吃辣椒不哦 弄点海椒（面）来蘸
You just tear it off, do you eat spicy, you can dip them into spicy pepper flake

0:04:13.936,0:04:14.559
不要不要
No I do not need it

0:04:17.841,0:04:19.756
嘿 还把它炸脆了安
Wow, this is very crunchy

0:04:21.200,0:04:23.024
好不好吃嘛 掰了来吃撒
How does it taste, lets rip the meat off to eat them

0:04:24.437,0:04:26.154
好吃安 好吃啊
It taste pretty good

0:04:26.428,0:04:27.249
弄点海椒面
Let’s use some spicy pepper flake

0:04:27.568,0:04:28.339
我不要海椒面
I don’t want to chilli pepper flake

0:04:28.343,0:04:29.452
你不蘸啊 蘸哈嘛 
You are not using the powder? Try to dip the sauce     

0:04:30.744,0:04:32.340
这个它放了盐（腌）的
He already put salt to marinade

0:04:34.392,0:04:35.683
蘸不起哦有可能
Too salty to dip more sauce?

0:04:40.015,0:04:41.975
嗯好吃 不消蘸的 
It is very tasty, no need to dip in sauce

0:04:42.021,0:04:42.826
可以蘸哈
I can try to dip into the sauce

0:04:43.085,0:04:43.860
（蘸了）有点辣
It is a little spicy

0:04:43.966,0:04:44.741
够不够味嘛
Is it flavorful enough

0:04:44.878,0:04:45.273
够味
Yes it is

0:04:45.699,0:04:47.188
这中间很嫩
It is very tender in the middle

0:04:50.227,0:04:52.249
掰开 掰开了蘸这个海椒
Tear it down to dip the chilli pepper

0:04:58.419,0:04:59.422
我还是再吃点
I can eat a little more

0:04:59.939,0:05:02.644
嗯 这个海椒面蘸起味道又不一样安
Un, dipping with the chilli pepper sauce the chicken wings taste different

0:05:02.689,0:05:05.395
我们这个炸出来的话水份全部被锁在里面了
If we use deep frying method, we are able to lock the juice within

0:05:05.455,0:05:06.854
里面都是很嫩很嫩的
It is very tender inside

0:05:18.890,0:05:22.184
我们炸这个的时候一定要开中小火去浸炸
When we are frying these, we must use medium low heat to fry them

0:05:22.249,0:05:25.790
如果是火太大的话 外面的糊了中间的还没熟
If the heat is too high, we might burn the outside while inside is undercooked

0:05:26.869,0:05:28.632
如果炖来干（吃）嘛还是绵的
If we stew the meat, it will taste soft

0:05:28.647,0:05:30.045
这样炸起还不绵
You fried it this way so the meat is not too soft

0:05:31.048,0:05:31.560
是不哦
Right

0:05:31.884,0:05:34.148
是啊 还脱骨还多安逸
Yeah and it comes off the bone, very good

0:05:36.048,0:05:37.811
好了本期视频就先到这里
Okay these are the content of the video

0:05:38.738,0:05:40.881
我们吃（剩）的这个骨头拿给狗儿吃
Let’s give the leftover bones to the dog

0:05:41.519,0:05:42.720
看 这个肉好嫩哦
See, the meat is very tender

0:05:48.100,0:05:48.981
你都吃了2个了啊
You have eaten 2 already

0:05:48.996,0:05:49.224
嗯
Yeah

0:05:49.285,0:05:50.638
我拿去喂狗
I am going to feed the dog

0:05:53.966,0:05:54.513
狗儿喽 
Hey puppy

0:05:56.413,0:05:59.696
来 我们吃肉你吃骨头
Here, we eat meat you eat bones

0:06:00.395,0:06:00.927
尝一下 
Have a taste

0:06:01.823,0:06:03.540
尝一下我们炸这个味道怎么样 
Give it a try and see how it taste

0:06:04.741,0:06:06.033
它还吃起多香噶
He seems to be enjoying
