### ISSUE TITLE
[老饭骨] 烤鸡翅 - https://www.youtube.com/watch?v=WeZDxAtxixA

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#882]
**视频链接**：https://www.youtube.com/watch?v=WeZDxAtxixA

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•烤鸡翅】金黄酥脆、汁水四溢、最简单的烤鸡翅来啦！独家秘方，一次就能学会！

简介
小友们好！我们YouTube频道有很多在海外的小友，
常常会遇到食材不好买的问题，做不出我们视频里教大家的那个味道。
今天就让老冯来献个宝，传授一下他的独家秘方，
做一道用料非常简单，很容易操作的烤鸡翅！小友们一看就能学会！
鸡翅要想做得好吃，一定要把鸡翅里的血水挤干净，这个小窍门大家一定要记住咯！
这个烤鸡翅可是三叔认证过的好吃，一定要老冯教给各位小友，
小友们学会了记得来评论区告诉我们！

字幕
没有官方字幕，需自行制作时间轴及对照中文
```

**Comment by Koi111** [comment]
认领

**Comment by Koi111** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•烤鸡翅】金黄酥脆、汁水四溢、最简单的烤鸡翅来啦！独家秘方，一次就能学会！
State Banquet Master Chefs’ roasted Chicken Wings; Golden, crispy and juicy, easy to learn!
简介
Introduction
小友们好！我们YouTube频道有很多在海外的小友，常常会遇到食材不好买的问题，做不出我们视频里教大家的那个味道。
Hey friends, a lot of you guys are not able to buy fresh ingredients in other country, therefore there is a difference in the taste.
今天就让老冯来献个宝，传授一下他的独家秘方，
Today Uncle Feng will share his exclusive recipe
做一道用料非常简单，很容易操作的烤鸡翅！小友们一看就能学会！
About roasted chicken wings. An easy task with simple ingredients, you guys can definitely learn this immediately!
鸡翅要想做得好吃，一定要把鸡翅里的血水挤干净，这个小窍门大家一定要记住咯！
The key to delicious chicken wings is to squeeze out the blood inside the meat, remember this tip!
这个烤鸡翅可是三叔认证过的好吃，一定要老冯教给各位小友，
This wonderful dish is approved by San Shu, and he requested Uncle Feng to teach you guys
小友们学会了记得来评论区告诉我们！
If you’ve successfully learnt this dish, remember to tell us in the comments down below!

0:00:00.180,0:00:02.240
#烤鸡翅 皮脆汁又多
Roasted chicken wings, crispy skin and juicy meat

0:00:02.440,0:00:04.220
#这是什么好东西
What delicacy is this?

0:00:04.220,0:00:08.500
#这个您一直跟我说 说咱家鸡翅好吃
Well, you’ve been telling me that our chicken wings are very tasty

0:00:08.500,0:00:11.540
#实际上这个鸡翅很简单的
Actually this is a really simple recipe

0:00:11.540,0:00:13.780
#待会我一教大家就会了
You guys can learn this immediately after I teach you later on

0:00:13.780,0:00:15.780
#一边说一边干活 别白话
Work as you chat along, don’t just waste time talking

0:00:15.820,0:00:19.540
#咱们挑选这种整翅
We have to choose chicken wings like this, a complete one

0:00:19.540,0:00:22.540
#这个要经过泡水 还有出血
We have to soak this in water and remove the excess blood inside the wings

0:00:22.540,0:00:24.440
#就是挤出翅膀上血管里边的血
Which is by squeezing the blood in the blood vessels inside

0:00:24.440,0:00:26.920
#你看我给大家操作一下
Look, I can demonstrate it to you

0:00:26.920,0:00:28.900
#这里边有一根血管
There is a blood vessel inside here

0:00:28.900,0:00:30.920
#捋着这根血管 把这血给它挤出来
Hold it and squeeze out the blood inside

0:00:30.920,0:00:33.220
#看到了么 这个咱们已经挤过一次了
Look, we have already squeezed this once

0:00:33.280,0:00:37.640
#现在清洗得非常干净了 小窍门来了
We cleaned it thoroughly, here comes the little tip!

0:00:37.860,0:00:39.680
#这鸡翅要泡够时间
You must soak the chicken wings for a long time

0:00:39.680,0:00:42.240
#换三次水 两个小时换一次水
Change the water for 3 times and change it every 2 hours

0:00:42.280,0:00:43.800
#夏天是一个小时换一次水
Change it once an hour during summer

0:00:43.800,0:00:46.100
#然后每次水都要把它
Remember to squeeze out the blood

0:00:46.100,0:00:48.800
#血管里的血往给它外撸一撸
when you change the water

0:00:48.800,0:00:50.360
#因为我们这么多年
Because for such many years

0:00:50.360,0:00:54.500
#这个鸡翅是一道非常受欢迎的菜
The chicken wings are very popular

0:00:54.860,0:00:57.600
#三叔跟我说了好几次要让我做这鸡翅
San Shu told me a few times to teach you guys how to make this

0:00:57.600,0:00:58.860
#给我下了命令了
He gave me an order

0:00:58.860,0:01:01.580
#让我必须把这鸡翅教给大家
Therefore I must teach you guys about this recipe

0:01:01.600,0:01:03.400
#好 鸡翅都已经洗的很干净了
Okay, the chicken wings are clean now

0:01:03.400,0:01:06.320
#洗干净之后放在这儿
Put it aside once you are done cleaning them

0:01:06.320,0:01:07.520
#咱们切一点洋葱
Let’s slice some onions

0:01:07.580,0:01:09.760
#我每次切都是让它顶刀切
I slice onions with the flat side down every time

0:01:09.760,0:01:12.920
#因为它这样释放洋葱的味道好
To release the aroma better

0:01:12.920,0:01:15.280
#然后我再教大家调一个料
Next I would like to teach you making a marinade

0:01:15.280,0:01:20.280
#把这孜然炒好 放进去
Toast some cumin seeds and put it into the blender

0:01:20.620,0:01:23.340
#这生孜然搁到锅里边干焙一下
Toast the cumin seeds in a wok or a pan

0:01:23.380,0:01:24.480
#焙出香味来就可以了
until it is aromatic and that’s done

0:01:24.480,0:01:27.240
#然后放一点五香粉 这五香粉的量
Then, some five-spices powder

0:01:27.240,0:01:29.660
#一定不要把孜然的味儿盖住
The five-spices must not overpower the aroma of the cumin

0:01:29.660,0:01:32.860
#黑胡椒也是跟五香粉一样
Same goes with the black pepper

0:01:32.860,0:01:33.680
#好 够了
Okay, that’s enough

0:01:34.000,0:01:41.040
#这儿有白胡椒吧 再搁一点 
You have some white pepper powder right, let’s put some of that

0:01:41.040,0:01:41.740
#好
Yeah

0:01:41.740,0:01:43.540
#接下来呢就是放盐
Then, put some salt

0:01:44.400,0:01:48.260
#五个鸡翅 一勺 两勺
5 chicken wings, let’s put 2 spoons of salt

0:01:48.260,0:01:51.360
#这次我教大家腌的是干腌
This time I am teaching you guys to make a dry rub

0:01:51.440,0:01:53.440
#我店里边用的都是水淹
Normally we use wet rub in my restaurant

0:01:53.500,0:01:57.040
#来吧 齐活儿
Okay done

0:01:57.040,0:01:59.120
#黑胡椒的味道太好了
The fragrant of the black pepper is awesome!

0:01:59.160,0:02:02.720
#这个胡椒打完了以后你闻闻香不香
Can you smell the aroma？

0:02:02.720,0:02:06.120
#真香啊
Nice!

0:02:06.120,0:02:08.960
#给它往里边一撒
Pour it inside together with the onions

0:02:09.020,0:02:13.120
#拌匀 要是干的话可以适当的放点水
Mix well, if you think it’s too dry you can add some water

0:02:13.120,0:02:15.820
#我觉得还是水淹的比较好
I still prefer a wet rub

0:02:15.820,0:02:18.300
#因为水淹的入味比较快
Because the flavour can penetrate more easily

0:02:18.300,0:02:20.880
#咱还是放一点水把
Let’s put some water into the marinade

0:02:20.880,0:02:25.260
#要使劲攥一攥  把洋葱的味道给它攥出来
You have to rub it with strength to release the flavour of the onions

0:02:25.260,0:02:27.200
#给它碰撞出来
Release all the flavours!

0:02:27.320,0:02:29.700
#看看 这样就腌好了
Look, we are done with the marinating

0:02:29.700,0:02:32.360
#假如咱们家里边要是有条件的话呢
If you have other seasoning at your house,

0:02:32.380, 0:02:37.040
#您可以放一点蚝油 
You can out some oyster sauce

0:02:37.100,0:02:41.420
#但是我是不建议放 就是要它的原味
But I don’t recommend it, I prefer the original flavour

0:02:41.540,0:02:45.480
#好 这样给它腌上三个小时
Okay, marinate it for 3 hours

0:02:45.480,0:02:49.560
#烤箱调到二百二十度就可以烤了
Preheat the oven to 220°C


0:02:49.560,0:02:51.380
#就最高火吧
Let’s set it at the highest temperature

0:02:51.380,0:02:53.080
#但是我为了争取时间
To save some time,

0:02:53.080,0:02:57.260
#我把提前腌好的几个咱先烤上
I’ve marinated some chicken wings beforehand and we can roast them now

0:02:57.260,0:03:00.620
#你看这个鸡翅腌完了之后是这样
This is how the wings look like after marinating

0:03:00.620,0:03:02.900
#看出来了吧 光滑 亮
Can you see that? Smooth and glossy

0:03:02.920,0:03:04.960
#这个就是把这个料再腌好之后
To achieve that, rinse the chicken wings

0:03:04.960,0:03:06.300
#给它用水冲一下
after marinating

0:03:06.300,0:03:09.440
#冲一下之后把上边料渣冲下去
Rinse off the marinade

0:03:09.460,0:03:11.300
#现在就开烤了  上烤盘 
Let’s start roasting, take out the tray now

0:03:11.300,0:03:13.700
#烤盘就不用刷油了
We don’t need to grease the tray in advance

0:03:13.700,0:03:16.020
#因为这个鸡翅它本身会出油
Because there are fat in the chicken wings

0:03:16.020,0:03:18.160
#网友们 这鸡翅其实真是简单
Friends, this dish is truly simple

0:03:18.180,0:03:21.980
#这鸡翅吃的是原味的香
We can enjoy the original chicken flavour

0:03:21.980,0:03:24.300
#二百三 咱们烤多长时间啊老冯
230°C, how long should we roast it, Uncle Feng?

0:03:24.300,0:03:28.520
#这个我们在店里一般都是在半个小时
Well, it takes around half an hour in our restaurant

0:03:28.640,0:03:31.300
#咱们这烤箱咱们看吧 观察着来吧
But this is a different oven, let’s observe it and decide later on

0:03:31.300,0:03:33.800
#因为它要求表面要金黄
Because the chicken wings need to develop a golden crust

0:03:33.800,0:03:36.880
#然后皮脆肉嫩 
And the skin has to be crispy with a tender inside

0:03:36.880,0:03:38.140
#咱们就等着了
Just wait

0:03:38.140,0:03:41.300
#鸡翅到点儿啦 闻着味儿怎么样
The time has reached, how does it smell?

0:03:41.300,0:03:45.120
#看看 这是老冯烤鸡翅
Look at this, Feng’s roasted chicken wings

0:03:45.120,0:03:47.620
#三叔给出盘儿了
But San Shu is serving the dish

0:03:47.620,0:03:50.360
#真不错 拿出来味儿就出来了
Such a wonderful dish, you can smell the aroma once it’s been taken out

0:03:50.360,0:03:54.520
#网友们 了不得了啊 香死个人儿了
Friends, this is impressive, so aromatic!

0:03:54.520,0:03:56.360
#漂亮 好	
Great! Okay!

0:03:58.120,0:04:01.420
#嚯 皮酥 你知道还一大最大特点是什么啊
Wow! Such a crispy skin, do you know its best feature?

0:04:01.420,0:04:03.460
#汁水锁得好
The juice is locked inside

0:04:03.460,0:04:06.380
#我刚一咬 你看 看见没有
As soon as I bit into it, can you see that?!

0:04:06.380,0:04:08.560
#汁水锁得好
The chicken wings are extremely juicy

0:04:08.800,0:04:11.780
#够味儿 外焦里嫩 
Rich in flavour, crispy outside and tender inside

0:04:11.940,0:04:16.280
#三叔推荐 再见
Recommended by San Shu. Goodbye!

0:04:16.280,0:04:19.580
#三叔认可了 没毛病了
Approved by San Shu, wonderful!

0:04:33.940,0:04:37.040

# import ending.srt 0:04:33,940 请原样保留此行
