### ISSUE TITLE
[雪鱼] 山东小吃烤牌+烧鸡 - https://youtu.be/dYlWkgn4Wvo

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#885]
**视频链接**：https://youtu.be/dYlWkgn4Wvo

视频时长：10min
发布日期：2020年4月4日
# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
山东小镇名吃，1元的烤牌一天做2000个都不够卖！+46元的烧鸡，用手撕着吃，外皮比肉还香

简介
在山东小镇上吃小吃，30多年的老店生意一直很红火，1块5毛钱一个的烤牌，外皮全是芝麻，吃起来非常酥脆，搭配山东特色羊肉汤，那叫一个过瘾！夫妻两人一天要做2000个，只依靠一个炉子，慢慢做出来，一天就要做12个小时之多！几乎做完一炉卖一炉！除了吃烤牌，还有烧鸡，大大的烧鸡，外皮颜色诱人，大锅先炖，再用老汤调味，同样也是30年的老店，店家做的味道非常好，一只只的烧鸡热气腾腾，勾人食欲，吃烧鸡不能用刀，必须用手撕着吃，鸡皮脆爽，肉虽嫩，不及皮爽！

字幕
1
00:00:02,725 --> 00:00:05,095
我的朝牌（面食）做多少卖多少

2
00:00:07,700 --> 00:00:11,600
早上5点钟起床 到下午6点钟一直在做

3
00:00:11,950 --> 00:00:13,900
超过6点再来买的 也不做了

4
00:00:15,925 --> 00:00:17,925
俺爷爷打朝牌 俺老爹打朝牌

5
00:00:17,925 --> 00:00:20,575
我是第三辈打朝牌 

6
00:00:22,450 --> 00:00:25,458
（顾客）独一份 这刘家朝牌

7
00:00:31,200 --> 00:00:32,850
哈喽 今天天气特别好

8
00:00:32,950 --> 00:00:34,325
雪鱼将要去一个小镇上

9
00:00:34,550 --> 00:00:36,100
吃一个特别有名的朝牌

10
00:00:36,300 --> 00:00:37,600
朝牌1块钱一个

11
00:00:37,700 --> 00:00:39,900
刚出炉的时候 面香特别勾人

12
00:00:40,150 --> 00:00:42,000
我已经好久没有吃了

13
00:00:42,150 --> 00:00:45,250
想想都觉得过瘾 走吧

14
00:00:51,325 --> 00:00:53,975
好像上一炉烤牌刚被卖完

15
00:00:54,700 --> 00:00:56,675
阿姨  还得等多长时间

16
00:00:56,900 --> 00:00:58,850
10分钟

17
00:01:04,050 --> 00:01:05,800
好久没有等刚出炉的朝牌了

18
00:01:05,875 --> 00:01:07,075
这还是开年头一次

19
00:01:08,975 --> 00:01:10,831
之前来的时候还是1块钱一个

20
00:01:11,050 --> 00:01:13,025
这次来发现 （价格）涨了5毛钱

21
00:01:13,325 --> 00:01:15,675
不过1块钱的价格 确实卖了很多年了

22
00:01:15,975 --> 00:01:19,050
看牌子 价格也是刚涨没有多久

23
00:01:22,775 --> 00:01:25,825
已经是30年老店

24
00:01:46,125 --> 00:01:48,325
阿姨擀好朝牌 会在上面刷油

25
00:01:48,475 --> 00:01:49,750
然后撒上芝麻盐

26
00:01:49,900 --> 00:01:52,475
这样吃起来就不会像馒头那样

27
00:01:52,525 --> 00:01:53,975
没有什么样的味道

28
00:02:04,325 --> 00:02:06,100
在阿姨做朝牌的时候 你会发现

29
00:02:06,200 --> 00:02:07,850
芝麻放的特别多

30
00:02:08,125 --> 00:02:10,025
感觉这一整面都是芝麻

31
00:02:10,275 --> 00:02:12,800
你再多放一粒 芝麻都会掉下来

32
00:02:42,475 --> 00:02:46,100
阿姨 这一炉一次能做出来多少个 我想买10个

33
00:02:46,250 --> 00:02:48,075
一炉24个

34
00:02:49,200 --> 00:02:51,150
能放几天

35
00:02:51,400 --> 00:02:53,800
一个星期左右

36
00:02:55,150 --> 00:02:57,725
它越搁越软 面和其它家不同

37
00:02:57,925 --> 00:02:59,325
1.5元一个

38
00:03:03,100 --> 00:03:05,325
敞开袋子的口 

39
00:03:11,075 --> 00:03:14,125
（顾客）我不想要热的

40
00:03:14,125 --> 00:03:19,575
我要带走的 怕热的哈气 就不好了

41
00:03:31,000 --> 00:03:33,150
在马头镇这边 朝牌是非常出名的

42
00:03:33,475 --> 00:03:35,225
它为什么叫朝牌呢

43
00:03:35,375 --> 00:03:37,375
是因为每一个朝牌的样子

44
00:03:37,550 --> 00:03:42,075
很像古代 朝见君王拿的玉牌

45
00:03:42,875 --> 00:03:43,825
像不像

46
00:03:45,425 --> 00:03:46,974
它这个是刚打出来的

47
00:03:46,974 --> 00:03:49,781
上面铺了密密麻麻的白芝麻

48
00:03:50,325 --> 00:03:53,050
看起来就是特别酥脆 特别香

49
00:03:53,725 --> 00:03:56,275
现在我就趁热掰一下朝牌

50
00:03:56,525 --> 00:04:00,725
听到这个声音 你都会觉得它特别美味

51
00:04:00,875 --> 00:04:02,450
看呀

52
00:04:02,975 --> 00:04:04,925
里面是刷了油 加了盐的

53
00:04:05,050 --> 00:04:06,825
所以 即使是这么吃

54
00:04:06,900 --> 00:04:09,475
你也会觉得它很有味道

55
00:04:10,300 --> 00:04:11,675
一口下去

56
00:04:11,700 --> 00:04:14,425
满满的都是芝麻的香味

57
00:04:15,300 --> 00:04:17,100
这一个朝牌分量还是很大的

58
00:04:17,275 --> 00:04:19,350
吃一个就差不多能够饱了

59
00:04:20,025 --> 00:04:21,850
平常呢 可以当主食来吃

60
00:04:21,850 --> 00:04:23,350
你看很多做羊肉汤的地方

61
00:04:23,925 --> 00:04:25,850
（汤）都会配朝牌来吃

62
00:04:26,275 --> 00:04:29,025
它也可以叫烤牌 因为是烤出来的

63
00:04:29,275 --> 00:04:31,450
另一方面呢 如果说平常饿了

64
00:04:31,625 --> 00:04:35,100
用它来当一下点心 也是很不错的

65
00:04:43,900 --> 00:04:46,100
补充一下 在做羊肉汤的地方

66
00:04:46,150 --> 00:04:49,350
配的朝牌 烤牌可不是这个重量的

67
00:04:49,525 --> 00:04:51,900
一般的话 会比较薄一些

68
00:04:54,325 --> 00:04:56,225
如果换成这样大的 普通人的饭量

69
00:04:56,225 --> 00:04:58,125
吃一两个也就饱了

70
00:05:05,000 --> 00:05:07,975
真的没有想到 这么简单的1块钱的小吃

71
00:05:08,050 --> 00:05:10,600
能在这个小镇上红火几十年

72
00:05:12,050 --> 00:05:13,200
我刚买完朝牌 

73
00:05:13,200 --> 00:05:15,450
后面已经有人在等着下一炉了

74
00:05:27,475 --> 00:05:29,375
你知道吗 在我的朋友圈有很多

75
00:05:29,425 --> 00:05:30,825
做熟食的朋友

76
00:05:30,825 --> 00:05:34,100
他们做的肉食 熟食真的会让我垂涎三尺

77
00:05:34,350 --> 00:05:36,375
感觉把我的馋虫都给勾出来了

78
00:05:36,550 --> 00:05:38,150
今天呢 趁着开车出去

79
00:05:38,300 --> 00:05:41,850
我们去买一个当地比较特色的熟食 肉食

80
00:05:41,950 --> 00:05:43,525
就是烧鸡

81
00:05:43,575 --> 00:05:45,450
小的时候 都是逢年过节才能够吃得到

82
00:05:45,600 --> 00:05:47,225
待会就开个远路

83
00:05:47,250 --> 00:05:49,825
去尝一尝小时候的味道

84
00:05:50,550 --> 00:05:53,075
这边正在修路 车也进不来

85
00:05:53,525 --> 00:05:56,150
吃个烧鸡好难啊

86
00:05:57,325 --> 00:05:58,100
快到了

87
00:06:03,950 --> 00:06:06,375
你好 还有烧鸡吗

88
00:06:06,375 --> 00:06:08,703
有 带走吗 对的

89
00:06:09,775 --> 00:06:10,800
要几个

90
00:06:10,800 --> 00:06:11,504
多少钱了

91
00:06:12,250 --> 00:06:12,925
22一斤

92
00:06:13,100 --> 00:06:13,825
要一个就行

93
00:06:13,925 --> 00:06:15,175
要一般大的就行吧

94
00:06:15,325 --> 00:06:15,825
对

95
00:06:16,400 --> 00:06:19,500
因为疫情 烧鸡做的没有以前那么多了

96
00:06:19,550 --> 00:06:21,425
但每天还是能够吃到刚出锅的

97
00:06:22,375 --> 00:06:24,250
烧鸡的做法呢 大体都是

98
00:06:24,250 --> 00:06:26,372
先炖 再上色 最后捞出来浸泡到老汤里  

99
00:06:26,372 --> 00:06:28,520
但是不同的店 用的大料不同

100
00:06:28,520 --> 00:06:30,620
口味上 还是有一些差别的

101
00:06:41,153 --> 00:06:42,396
扣大盖了

102
00:06:44,825 --> 00:06:46,850
盖上盖子 鸡要足足炖半个多小时

103
00:06:47,475 --> 00:06:50,025
才能让肉炖透 料入味

104
00:06:52,675 --> 00:06:55,700
刚捞出来的鸡 颜色只是微微的酱油的颜色

105
00:06:55,950 --> 00:06:57,775
如果说 想要换得真身

106
00:06:58,200 --> 00:07:02,000
还得把锅底烧红 用白糖熏烤上色

107
00:08:40,225 --> 00:08:42,450
看到没 买到了烧鸡

108
00:08:43,025 --> 00:08:45,100
这一只烧鸡是两斤多重

109
00:08:45,375 --> 00:08:47,025
因为它是22块钱一斤

110
00:08:47,075 --> 00:08:49,000
咱们这一只是46块钱的

111
00:08:49,425 --> 00:08:51,975
走吧 回家吃烧鸡了

112
00:08:59,100 --> 00:09:00,450
烧鸡还是热的

113
00:09:00,550 --> 00:09:02,925
隔着袋子 你都能闻到香味

114
00:09:03,525 --> 00:09:05,075
我们要赶快回家

115
00:09:05,075 --> 00:09:06,900
享受这顿美味

116
00:09:12,025 --> 00:09:14,250
撕烧鸡 应该不是什么技术活吧

117
00:09:14,475 --> 00:09:16,275
可大可小

118
00:09:18,850 --> 00:09:22,250
看撕烧鸡的人的心情是怎么样的

119
00:09:26,025 --> 00:09:27,425
大部分的情况下

120
00:09:27,675 --> 00:09:29,975
撕烧鸡的人是有权力

121
00:09:30,175 --> 00:09:31,500
把烧鸡

122
00:09:31,650 --> 00:09:33,725
塞进自己的嘴里的

123
00:09:34,375 --> 00:09:36,125
好香啊

124
00:09:42,175 --> 00:09:44,850
烧鸡的皮特别薄 像褶皱一样

125
00:09:44,850 --> 00:09:48,650
它是相比于鸡肉来说 更咸 更入味的

126
00:09:49,050 --> 00:09:53,700
反观鸡肉呢 就是更白嫩一些

127
00:10:01,925 --> 00:10:05,050
我要继续啃鸡腿了 拜拜


```

**Comment by Hackerry** [comment]
认领

**Comment by Hackerry** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
山东小镇名吃，1元的烤牌一天做2000个都不够卖！+46元的烧鸡，用手撕着吃，外皮比肉还香
Shandong Small Town Gourmet: 1￥ "Kao Pai". Sell more than 2000 a day! And 46￥ braised chicken.

简介
在山东小镇上吃小吃，30多年的老店生意一直很红火，1块5毛钱一个的烤牌，外皮全是芝麻，吃起来非常酥脆，搭配山东特色羊肉汤，那叫一个过瘾！夫妻两人一天要做2000个，只依靠一个炉子，慢慢做出来，一天就要做12个小时之多！几乎做完一炉卖一炉！除了吃烤牌，还有烧鸡，大大的烧鸡，外皮颜色诱人，大锅先炖，再用老汤调味，同样也是30年的老店，店家做的味道非常好，一只只的烧鸡热气腾腾，勾人食欲，吃烧鸡不能用刀，必须用手撕着吃，鸡皮脆爽，肉虽嫩，不及皮爽！
Eat street food at a small town in Shandong. A 30-year-old popular brand selling "Kao Pai", one for 1.5￥. Sesame all around and very crispy. It is especially satisfying when accompanied with Shandong style Lamp Soup! Husband and wife make 2000 a day with one stove. They cook it slowly and spend 12 hours a day in baking. One batch sells immediately after taken out of the stove! Besides "Kao Pai", there is braised chicken. Large chicken with enticing outside. Braised in big wok and seasoned with broth. It's also sold in a 30-year-old restaurant with amazing flavor. Hot chicken with steam attracts customers' taste buds. One must use hand instead of a knife to tear chicken. Skin is crispy and meat is tender, but I like the skin more!

字幕
1
00:00:02,725 --> 00:00:05,095
我的朝牌（面食）做多少卖多少
My "Chao Pai" (dough food) sell as quick as I make them.

2
00:00:07,700 --> 00:00:11,600
早上5点钟起床 到下午6点钟一直在做
I wake up at 5 in the morning and make dough food until 6 pm.

3
00:00:11,950 --> 00:00:13,900
超过6点再来买的 也不做了
The shop is closed after 6.

4
00:00:15,925 --> 00:00:17,925
俺爷爷打朝牌 俺老爹打朝牌
My grand father and my father are both in this business.

5
00:00:17,925 --> 00:00:20,575
我是第三辈打朝牌 
I'm the third generation.

6
00:00:22,450 --> 00:00:25,458
（顾客）独一份 这刘家朝牌
(Customer) This "Liu Jia Chao Pai" is incomparable.

7
00:00:31,200 --> 00:00:32,850
哈喽 今天天气特别好
Hello. It's a nice day today.

8
00:00:32,950 --> 00:00:34,325
雪鱼将要去一个小镇上
Xueyu is going to a small town.

9
00:00:34,550 --> 00:00:36,100
吃一个特别有名的朝牌
To taste a very famous "Chao Pai".

10
00:00:36,300 --> 00:00:37,600
朝牌1块钱一个
One for 1￥.

11
00:00:37,700 --> 00:00:39,900
刚出炉的时候 面香特别勾人
The nice smell of flour when they are taken out of the stove is enticing.

12
00:00:40,150 --> 00:00:42,000
我已经好久没有吃了
I haven't eaten any for a long time.

13
00:00:42,150 --> 00:00:45,250
想想都觉得过瘾 走吧
Just thinking of it makes me satisfied. Let's go.

14
00:00:51,325 --> 00:00:53,975
好像上一炉烤牌刚被卖完
Looks like the last batch was just sold out.

15
00:00:54,700 --> 00:00:56,675
阿姨  还得等多长时间
Auntie, how long do I have to wait?

16
00:00:56,900 --> 00:00:58,850
10分钟
10 minutes.

17
00:01:04,050 --> 00:01:05,800
好久没有等刚出炉的朝牌了
It has been a long time since I last wait for freshly made "Chao Pai".

18
00:01:05,875 --> 00:01:07,075
这还是开年头一次
This is the first time in a new year.

19
00:01:08,975 --> 00:01:10,831
之前来的时候还是1块钱一个
Before it was one for 1￥.

20
00:01:11,050 --> 00:01:13,025
这次来发现 （价格）涨了5毛钱
Now (the price) goes up by 50 cents.

21
00:01:13,325 --> 00:01:15,675
不过1块钱的价格 确实卖了很多年了
But the 1￥ price has been around for quite some years.

22
00:01:15,975 --> 00:01:19,050
看牌子 价格也是刚涨没有多久
The price increase was made not long ago, judging by this new sign.

23
00:01:22,775 --> 00:01:25,825
已经是30年老店
This is a 30-year-old brand.

24
00:01:46,125 --> 00:01:48,325
阿姨擀好朝牌 会在上面刷油
After rolling the dough, auntie will brush some oil on top.

25
00:01:48,475 --> 00:01:49,750
然后撒上芝麻盐
And sprinkle some sesame salt.

26
00:01:49,900 --> 00:01:52,475
这样吃起来就不会像馒头那样
So it doesn't taste, like steam bread,

27
00:01:52,525 --> 00:01:53,975
没有什么样的味道
that bland.

28
00:02:04,325 --> 00:02:06,100
在阿姨做朝牌的时候 你会发现
You can see when making "Chao Pai",

29
00:02:06,200 --> 00:02:07,850
芝麻放的特别多
auntie put a lot of sesame.

30
00:02:08,125 --> 00:02:10,025
感觉这一整面都是芝麻
This side is all sesame.

31
00:02:10,275 --> 00:02:12,800
你再多放一粒 芝麻都会掉下来
Feels like if you put one more it will fall off.

32
00:02:42,475 --> 00:02:46,100
阿姨 这一炉一次能做出来多少个 我想买10个
Auntie, how many in a batch? I want 10.

33
00:02:46,250 --> 00:02:48,075
一炉24个
24 in one stove.

34
00:02:49,200 --> 00:02:51,150
能放几天
How long can I store it?

35
00:02:51,400 --> 00:02:53,800
一个星期左右
About a week.

36
00:02:55,150 --> 00:02:57,725
它越搁越软 面和其它家不同
It turns soft over time. The flour is special.

37
00:02:57,925 --> 00:02:59,325
1.5元一个
one for 1.5￥.

38
00:03:03,100 --> 00:03:05,325
敞开袋子的口 
Leave the plastic bag loose.

39
00:03:11,075 --> 00:03:14,125
（顾客）我不想要热的
(Customer) I don't want hot ones.

40
00:03:14,125 --> 00:03:19,575
我要带走的 怕热的哈气 就不好了
I need to take it away. Hot steam makes it less appealing.

41
00:03:31,000 --> 00:03:33,150
在马头镇这边 朝牌是非常出名的
Here at "Ma Tou Zhen" (literally Horse Head Town), "Chao Pai" is very well-known.

42
00:03:33,475 --> 00:03:35,225
它为什么叫朝牌呢
Why is it called "Chao Pai" (literally "Meeting Board")?

43
00:03:35,375 --> 00:03:37,375
是因为每一个朝牌的样子
Because every one of them,

44
00:03:37,550 --> 00:03:42,075
很像古代 朝见君王拿的玉牌
looks like the jade board a courtier holds when meeting the emperor in ancient China.

45
00:03:42,875 --> 00:03:43,825
像不像
Doesn't it?

46
00:03:45,425 --> 00:03:46,974
它这个是刚打出来的
This is freshly made.

47
00:03:46,974 --> 00:03:49,781
上面铺了密密麻麻的白芝麻
Covered with white sesame.

48
00:03:50,325 --> 00:03:53,050
看起来就是特别酥脆 特别香
It looks crispy and smells good.

49
00:03:53,725 --> 00:03:56,275
现在我就趁热掰一下朝牌
Now I'll split it in half.

50
00:03:56,525 --> 00:04:00,725
听到这个声音 你都会觉得它特别美味
You can imagine how delicious it is by the sound.

51
00:04:00,875 --> 00:04:02,450
看呀
Look.

52
00:04:02,975 --> 00:04:04,925
里面是刷了油 加了盐的
There's oil and salt inside.

53
00:04:05,050 --> 00:04:06,825
所以 即使是这么吃
So even though you are eating it dry,

54
00:04:06,900 --> 00:04:09,475
你也会觉得它很有味道
you will find it flavorful.

55
00:04:10,300 --> 00:04:11,675
一口下去
A mouthful bite,

56
00:04:11,700 --> 00:04:14,425
满满的都是芝麻的香味
brings full of the nice sesame smell.

57
00:04:15,300 --> 00:04:17,100
这一个朝牌分量还是很大的
One "Chao Pai" is quite big.

58
00:04:17,275 --> 00:04:19,350
吃一个就差不多能够饱了
You may feel full after eating one.

59
00:04:20,025 --> 00:04:21,850
平常呢 可以当主食来吃
Usually, it is a staple food.

60
00:04:21,850 --> 00:04:23,350
你看很多做羊肉汤的地方
You can see many Lamp Soup restaurants,

61
00:04:23,925 --> 00:04:25,850
（汤）都会配朝牌来吃
serving "Chao Pai" (with soup).

62
00:04:26,275 --> 00:04:29,025
它也可以叫烤牌 因为是烤出来的
It is also called "Kao Pai" (literally Baked Board), because it's baked dough.

63
00:04:29,275 --> 00:04:31,450
另一方面呢 如果说平常饿了
On the other hand, if you feel hungry,

64
00:04:31,625 --> 00:04:35,100
用它来当一下点心 也是很不错的
it can also be served as a nice pastry.

65
00:04:43,900 --> 00:04:46,100
补充一下 在做羊肉汤的地方
As a side note, at those Lamp Soup places,

66
00:04:46,150 --> 00:04:49,350
配的朝牌 烤牌可不是这个重量的
"Chao Pai" has a different size.

67
00:04:49,525 --> 00:04:51,900
一般的话 会比较薄一些
Normally, it's thinner.

68
00:04:54,325 --> 00:04:56,225
如果换成这样大的 普通人的饭量
If switching to those bigger ones, for a regular person's stomach,

69
00:04:56,225 --> 00:04:58,125
吃一两个也就饱了
one or two is enough.

70
00:05:05,000 --> 00:05:07,975
真的没有想到 这么简单的1块钱的小吃
It's beyond imagination this simple 1￥ pastry

71
00:05:08,050 --> 00:05:10,600
能在这个小镇上红火几十年
at this small town can be so popular for several decades.

72
00:05:12,050 --> 00:05:13,200
我刚买完朝牌 
Right after I bought "Chao Pai",

73
00:05:13,200 --> 00:05:15,450
后面已经有人在等着下一炉了
there were already people waiting for the next batch.

74
00:05:27,475 --> 00:05:29,375
你知道吗 在我的朋友圈有很多
You know, I have many friends who

75
00:05:29,425 --> 00:05:30,825
做熟食的朋友
make hot deli food.

76
00:05:30,825 --> 00:05:34,100
他们做的肉食 熟食真的会让我垂涎三尺
Their cooked meat really makes me hungry.

77
00:05:34,350 --> 00:05:36,375
感觉把我的馋虫都给勾出来了
Enticing all my taste buds.

78
00:05:36,550 --> 00:05:38,150
今天呢 趁着开车出去
Today, since we are driving a car,

79
00:05:38,300 --> 00:05:41,850
我们去买一个当地比较特色的熟食 肉食
we will buy a special local deli food - 

80
00:05:41,950 --> 00:05:43,525
就是烧鸡
braised chicken.

81
00:05:43,575 --> 00:05:45,450
小的时候 都是逢年过节才能够吃得到
When I was little, I can only eat braised chicken during festivals and holidays.

82
00:05:45,600 --> 00:05:47,225
待会就开个远路
Later we will take a detour,

83
00:05:47,250 --> 00:05:49,825
去尝一尝小时候的味道
and taste the flavor of my childhood.

84
00:05:50,550 --> 00:05:53,075
这边正在修路 车也进不来
The road is under construction so we can't drive.

85
00:05:53,525 --> 00:05:56,150
吃个烧鸡好难啊
It's so tiring.

86
00:05:57,325 --> 00:05:58,100
快到了
Almost there.

87
00:06:03,950 --> 00:06:06,375
你好 还有烧鸡吗
Hello, is there any braised chicken?

88
00:06:06,375 --> 00:06:08,703
有 带走吗 对的
Yes. Takeout? Yes.

89
00:06:09,775 --> 00:06:10,800
要几个
How many?

90
00:06:10,800 --> 00:06:11,504
多少钱了
How much is it?

91
00:06:12,250 --> 00:06:12,925
22一斤
22￥ for 1 Jin (500g).

92
00:06:13,100 --> 00:06:13,825
要一个就行
I just want one.

93
00:06:13,925 --> 00:06:15,175
要一般大的就行吧
A normal sized one?

94
00:06:15,325 --> 00:06:15,825
对
Yeah.

95
00:06:16,400 --> 00:06:19,500
因为疫情 烧鸡做的没有以前那么多了
Because of the pandemic, the restaurant has reduced the amount of braised chicken for sale.

96
00:06:19,550 --> 00:06:21,425
但每天还是能够吃到刚出锅的
But each day there are still just-out-of-the-wok braised chicken for customers.

97
00:06:22,375 --> 00:06:24,250
烧鸡的做法呢 大体都是
The recipe is normally,

98
00:06:24,250 --> 00:06:26,372
先炖 再上色 最后捞出来浸泡到老汤里  
first braise, then coloring and finally immersing in broth.

99
00:06:26,372 --> 00:06:28,520
但是不同的店 用的大料不同
However, different restaurants have different seasoning.

100
00:06:28,520 --> 00:06:30,620
口味上 还是有一些差别的
So the falvors are different.

101
00:06:41,153 --> 00:06:42,396
扣大盖了
Put on lid.

102
00:06:44,825 --> 00:06:46,850
盖上盖子 鸡要足足炖半个多小时
After putting on lid, chicken must be braised for over half an hour,

103
00:06:47,475 --> 00:06:50,025
才能让肉炖透 料入味
to soften the meat and let the flavor penetrate the chicken.

104
00:06:52,675 --> 00:06:55,700
刚捞出来的鸡 颜色只是微微的酱油的颜色
Chicken has only faint color from soy sauce when taken out.

105
00:06:55,950 --> 00:06:57,775
如果说 想要换得真身
If, say, we want real authentic braised chicken.

106
00:06:58,200 --> 00:07:02,000
还得把锅底烧红 用白糖熏烤上色
We need to hot the wok and roast the chicken with white sugar.

107
00:08:40,225 --> 00:08:42,450
看到没 买到了烧鸡
Look. I bought braised chicken.

108
00:08:43,025 --> 00:08:45,100
这一只烧鸡是两斤多重
This one weighs more than 2 Jin (1kg).

109
00:08:45,375 --> 00:08:47,025
因为它是22块钱一斤
Since the price is 22￥ for 1 Jin (500g),

110
00:08:47,075 --> 00:08:49,000
咱们这一只是46块钱的
this one worth 46￥.

111
00:08:49,425 --> 00:08:51,975
走吧 回家吃烧鸡了
Let's go home and eat braised chicken.

112
00:08:59,100 --> 00:09:00,450
烧鸡还是热的
The chicken is still hot.

113
00:09:00,550 --> 00:09:02,925
隔着袋子 你都能闻到香味
You can smell the aroma outside the plastic bag.

114
00:09:03,525 --> 00:09:05,075
我们要赶快回家
We need to hurry back home.

115
00:09:05,075 --> 00:09:06,900
享受这顿美味
And enjoy this delicious food.

116
00:09:12,025 --> 00:09:14,250
撕烧鸡 应该不是什么技术活吧
Tearing the chicken is no technical stuff right?

117
00:09:14,475 --> 00:09:16,275
可大可小
No regular sizes.

118
00:09:18,850 --> 00:09:22,250
看撕烧鸡的人的心情是怎么样的
What is it like to look at me tearing this chicken?

119
00:09:26,025 --> 00:09:27,425
大部分的情况下
Under most circumstances,

120
00:09:27,675 --> 00:09:29,975
撕烧鸡的人是有权力
the person who tears the chicken has the right

121
00:09:30,175 --> 00:09:31,500
把烧鸡
to put some

122
00:09:31,650 --> 00:09:33,725
塞进自己的嘴里的
inside her mouth.

123
00:09:34,375 --> 00:09:36,125
好香啊
It smells so good.

124
00:09:42,175 --> 00:09:44,850
烧鸡的皮特别薄 像褶皱一样
The skin is thin as wrinkles.

125
00:09:44,850 --> 00:09:48,650
它是相比于鸡肉来说 更咸 更入味的
It's more salted than the meat and has better flavor.

126
00:09:49,050 --> 00:09:53,700
反观鸡肉呢 就是更白嫩一些
On the other hand, the meat is tenderer and whiter.

127
00:10:01,925 --> 00:10:05,050
我要继续啃鸡腿了 拜拜
I'll keep biting on my chicken legs then. Byebye.
