### ISSUE TITLE
【美食作家王刚】 猪儿粑 - https://youtu.be/Ejd-u85ZMAQ

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#889]
**视频链接**：https://youtu.be/Ejd-u85ZMAQ

视频时长 7:07，预计发布时间为北京时间4月9日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“猪儿粑”“清明粑粑”的家常做法，乡村味道，家人都说很好吃

简介
大家好，和大家分享一道特色美食“猪儿粑”，如果是清明前后加入清明菜的猪儿粑也叫“清明粑粑”，其实做法很简单，并且真的非常香，如果大家找不到清明菜其实直接做成普通的猪儿粑就好，依然可以体验这种西南特色小吃。但需要提醒大家不可以把猪儿粑当饭吃，因为面皮中使用了大量糯米粉，粘性很强，如果一次吃的太多可能会消化不良。（虽说真的很好吃！但是也不能贪食）

字幕
0:00:00.600,0:00:01.400
嗨喽 大家好

0:00:01.425,0:00:03.450
今天我们用这个清明菜

0:00:03.975,0:00:05.875
这个清明菜在我们这里叫燕子花

0:00:06.300,0:00:09.775
我们做一个清明节美食

0:00:11.175,0:00:12.575
这屋头还是有这个菜噶

0:00:12.675,0:00:14.325
有

0:00:14.400,0:00:15.925
反正就是清明的时候吃嘛

0:00:16.725,0:00:20.025
如果你们在农村的话可以弄这个来吃一下

0:00:20.325,0:00:22.650
这个的话还有一些特殊的功效

0:00:22.750,0:00:26.225
它有清热降火 还有润肺的一些功能

0:00:31.650,0:00:32.150
可以了吗

0:00:32.300,0:00:32.725
可以了

0:00:32.975,0:00:33.498
差不多了

0:00:33.498,0:00:34.125
够了吗这点

0:00:35.500,0:00:36.200
够不够哦

0:00:36.575,0:00:37.150
够得到

0:00:37.150,0:00:37.525
差不多了

0:00:37.750,0:00:40.925
害怕整多了到时候是苦的吃起不好吃

0:00:41.250,0:00:41.750
嗯

0:00:42.225,0:00:43.525
要焯过水这个

0:00:44.025,0:00:46.975
必须焯 不焯它就有股酸味

0:01:17.200,0:01:20.225
我们这个清明菜焯完水之后就变得非常绿

0:01:21.575,0:01:23.275
很要绿这个焯了水之后

0:01:23.625,0:01:27.725
然后我们取出一半来把它切碎做那个馅

0:01:33.300,0:01:38.700
我今天准备的馅料有这个香肠

0:01:39.125,0:01:41.425
我们四川的麻辣香肠

0:01:42.575,0:01:44.175
准备一条给它切成颗粒

0:01:45.825,0:01:47.925
如果你们没有香肠的也可以用腊肉

0:01:48.825,0:01:51.725
而且加新鲜肉也是可以的

0:01:51.875,0:01:54.400
只不过用麻辣香肠的话味道会更好一些

0:01:55.500,0:01:58.300
然后我们横过来切成小颗粒

0:02:02.625,0:02:05.000
我们的这个香肠随便剁一下就可以了

0:02:08.200,0:02:11.575
好了 现在剩下的我们用这个石臼把它捣碎

0:02:18.150,0:02:20.975
如果你们家里面有料理机的话可以用料理机来打

0:02:24.250,0:02:25.500
好了 捣烂了

0:02:26.075,0:02:28.550
然后我们捣碎了之后把它舀出来

0:02:29.200,0:02:30.400
现在是这个样子

0:02:32.375,0:02:33.925
现在我们来调这个粉

0:02:34.125,0:02:37.075
然后加点这个粘米粉 

0:02:39.775,0:02:40.675
再加点糯米粉

0:02:42.000,0:02:44.975
粘米粉和糯米粉的比例一比一就可以了

0:02:46.500,0:02:48.175
然后我们再加一点盐

0:02:48.675,0:02:50.725
你一比一没得嫩糍的哦

0:02:51.475,0:02:52.418
嗯 差不多就行了

0:02:52.425,0:02:53.975
糯米粉多加点的

0:02:54.800,0:03:00.725
我们捣好这个清明菜的汁现在我们把它挤进去

0:03:00.750,0:03:02.400
要的就是这个颜色

0:03:05.350,0:03:07.775
好了 加（汁）水挤进去了我们把它拌匀

0:03:11.100,0:03:15.925
我们这个面和好了之后再把这个渣加进去

0:03:16.600,0:03:20.250
把这个原渣加进去给它一起挼

0:03:21.900,0:03:24.775
四伯爷你帮我揉到

0:03:24.775,0:03:26.325
我去把那个腊肉（香肠）弄来炒起

0:03:53.575,0:03:55.600
我先是在手头把它搓圆

0:03:55.700,0:03:56.925
是搓圆了样

0:03:57.575,0:04:00.250
搓圆了你摊在手头

0:04:00.400,0:04:02.000
然后就捏边边

0:04:02.850,0:04:04.632
你要记到捏边边不能捏中间

0:04:04.632,0:04:06.550
中间要稍微厚点的都不关事

0:04:07.225,0:04:08.800
呐 这样子它就圆了

0:04:08.800,0:04:11.700
放在手头 手弄来窝起

0:04:12.225,0:04:14.850
这样子窝起然后舀一勺进去

0:04:16.500,0:04:18.375
这就圆了撒

0:04:18.775,0:04:22.750
然后这里给它稍微捏一哈 跟包包子一样

0:04:22.925,0:04:24.150
捏拢了之后再搓

0:04:26.675,0:04:29.275
这（馅料）没有放点猪油在里头炒啊

0:04:30.100,0:04:33.700
那个香肠里头就有猪油撒

0:04:33.725,0:04:35.475
猪油少了 我的估计

0:04:35.550,0:04:37.975
不少不少 都可以了

0:04:39.700,0:04:44.250
这样子摆起才好蒸嘛 蒸起才像猪儿粑嘛

0:04:46.850,0:04:48.100
不是等哈要塌下来噶

0:04:48.125,0:04:52.750
哦 不是它蒸融了来它要垮下来

0:04:52.750,0:04:55.875
垮下来就成了粑粑 圆啾啾的就不好看

0:04:55.875,0:04:58.125
我是想到包完了再来摆哈

0:04:58.700,0:05:02.057
好了 现在我们弄好了放到（蒸锅）上汽

0:05:02.550,0:05:05.625
上锅蒸 上汽了之后蒸二十分钟左右就可以吃了

0:05:06.025,0:05:07.175
我先拿去蒸起

0:05:15.750,0:05:16.775
好 水已经开了

0:05:30.850,0:05:31.725
把它盖起

0:05:41.225,0:05:42.625
哦哟 

0:05:42.625,0:05:44.175
好大一个个的

0:05:49.375,0:05:51.250
这个吃了来才吃那个大的

0:05:51.275,0:05:52.101
你吃几个哦 吃一个就够了

0:05:52.150,0:05:53.000
我给你拿起来

0:05:53.100,0:05:55.000
这就这样子（夹）撒

0:05:56.000,0:05:57.625
伯娘吃这个 我帮你拿

0:05:59.200,0:06:00.275
好好好 谢谢

0:06:01.525,0:06:02.800
好香啊这个蒸出来

0:06:04.825,0:06:05.700
好不好吃哦晓得

0:06:05.825,0:06:09.525
这个皮子逮到 我把它弄下来

0:06:10.600,0:06:11.295
把它剁下来

0:06:11.325,0:06:12.375
跟它弄的糍粑样

0:06:21.325,0:06:21.800
安逸

0:06:21.900,0:06:22.575
要巴起

0:06:24.750,0:06:26.075
伯娘你笑啥子

0:06:28.550,0:06:29.725
笑啥子哦笑

0:06:32.450,0:06:34.700
你莽起笑 等我个人吃

0:06:35.225,0:06:37.125
真的吗假的哦 各自吃完

0:06:38.400,0:06:45.725
我伯娘笑我伯爷说这个吃了会粘牙齿 其实没什么

0:06:47.600,0:06:48.700
很香真的很香

0:06:48.850,0:06:49.775
是香啊

0:06:50.200,0:06:50.700
安逸

0:06:51.550,0:06:53.925
好吃 很糍的噶

0:06:53.925,0:06:54.800
嗯

0:06:55.225,0:06:59.075
如果不想吃得太黏嘴的话就可以多加一点这个米粉

0:06:59.725,0:07:00.725
少加一点糯米粉

0:07:01.100,0:07:02.525
好 本期视频就到这里

0:07:03.650,0:07:04.975
大家可以尝试做一下


```

**Comment by Kevinzheng5** [comment]
认领

**Comment by immoonancient** [comment]
@Kevinzheng5 谢谢认领！
请问有方便的联系方式吗？比如我们的[微信群](https://github.com/immoonancient/YTSubtitles/blob/master/docs/wechat.md)?

**Comment by Kevinzheng5** [comment]
那个微信群的二维码过期了，麻烦再给发一个？
________________________________

**Comment by immoonancient** [comment]
刚才更新了，麻烦刷新一下

**Comment by Kevinzheng5** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“猪儿粑”“清明粑粑”的家常做法，乡村味道，家人都说很好吃
Chef Wang shares with you: “Pork Rice Cake for Qingming”, home and countryside style, the family loves it!
简介
大家好，和大家分享一道特色美食“猪儿粑”，如果是清明前后加入清明菜的猪儿粑也叫“清明粑粑”，其实做法很简单，并且真的非常香，如果大家找不到清明菜其实直接做成普通的猪儿粑就好，依然可以体验这种西南特色小吃。但需要提醒大家不可以把猪儿粑当饭吃，因为面皮中使用了大量糯米粉，粘性很强，如果一次吃的太多可能会消化不良。（虽说真的很好吃！但是也不能贪食）
Hello Everyone, today I’ll share the recipe of the “Pork Rice Cake”. It is also known as “Qingming Rice Cake” if you add some Qingming herb (Gnaphalium Affine) in it and make it around Qingming festival. The process is pretty straightforward, and the taste is just amazing. If you don’t have the Qingming herb around, you can just skip it and make the regular pork rice cake and still try the southwestern Chinese refreshment. Just don’t have this rice cake for meals since the dough has a lot of sticky rice in it and can cause indigestion.
(Even though it is really good, don’t have too much!)
字幕
0:00:00.600,0:00:01.400
嗨喽 大家好
Hello everyone

0:00:01.425,0:00:03.450
今天我们用这个n清明菜
Today we’ll use this Qingming herb (Gnaphalium Affine)

0:00:03.975,0:00:05.875
这个清明菜在我们这里叫燕子花
which is also called saw-wings flower around our place

0:00:06.300,0:00:09.775
我们做一个清明节美食
to make a traditional refreshment for Qingming festival

0:00:11.175,0:00:12.575
这屋头还是有这个菜噶
We still have this kind of herb around the house?

0:00:12.675,0:00:14.325
有
Sure

0:00:14.400,0:00:15.925
反正就是清明的时候吃嘛
Usually we have this around Qingming festival

0:00:16.725,0:00:20.025
如果你们在农村的话可以弄这个来吃一下
You can get some of this herb to try if you live in the countryside

0:00:20.325,0:00:22.650
这个的话还有一些特殊的功效
The herb also has some pharmacological benefits

0:00:22.750,0:00:26.225
它有清热降火 还有润肺的一些功能
It clears the internal heat and nourishes the lungs

0:00:31.650,0:00:32.150
可以了吗
Enough?	

0:00:32.300,0:00:32.725
可以了
Enough

0:00:32.975,0:00:33.498
差不多了
Seems about right

0:00:33.498,0:00:34.125
够了吗这点
Seems too little to me

0:00:35.500,0:00:36.200
够不够哦
Do we have enough?

0:00:36.575,0:00:37.150
够得到
It’s enough

0:00:37.150,0:00:37.525
差不多了
Seems about right

0:00:37.750,0:00:40.925
害怕整多了到时候是苦的吃起不好吃
If we put too much herb in there, the rice cake is going to taste bitter

0:00:41.250,0:00:41.750
嗯
Alright

0:00:42.225,0:00:43.525
要焯过水这个
We need to blanch the herb first

0:00:44.025,0:00:46.975
必须焯 不焯它就有股酸味
Yeah it’s necessary, otherwise it is too sour

0:01:17.200,0:01:20.225
我们这个清明菜焯完水之后就变得非常绿
The herb becomes very green after blanching

0:01:21.575,0:01:23.275
很要绿这个焯了水之后
It looks so green after blanching

0:01:23.625,0:01:27.725
然后我们取出一半来把它切碎做那个馅
Then we mince half of these for the stuffing

0:01:33.300,0:01:38.700
我今天准备的馅料有这个香肠
I got some sausages for the stuffing ingredient today

0:01:39.125,0:01:41.425
我们四川的麻辣香肠
Our Sichuan style spicy sausage

0:01:42.575,0:01:44.175
准备一条给它切成颗粒
We take one sausage and slice it

0:01:45.825,0:01:47.925
如果你们没有香肠的也可以用腊肉
You can also use the Chinese cured pork if you don’t have the sausage

0:01:48.825,0:01:51.725
而且加新鲜肉也是可以的
Fresh ground pork can also do it

0:01:51.875,0:01:54.400
只不过用麻辣香肠的话味道会更好一些
The sausage tastes a little better though

0:01:55.500,0:01:58.300
然后我们横过来切成小颗粒
Then we dice it to little pieces

0:02:02.625,0:02:05.000
我们的这个香肠随便剁一下就可以了
Then chop the pieces for several times

0:02:08.200,0:02:11.575
好了 现在剩下的我们用这个石臼把它捣碎
Alright, then we mush the sausage in this mortar
0:02:18.150,0:02:20.975
如果你们家里面有料理机的话可以用料理机来打
You can also use the blender if you have one

0:02:24.250,0:02:25.500
好了 捣烂了
Alright it’s done

0:02:26.075,0:02:28.550
然后我们捣碎了之后把它舀出来
Then we scoop them into a bowl

0:02:29.200,0:02:30.400
现在是这个样子
It looks like this now

0:02:32.375,0:02:33.925
现在我们来调这个粉
Now let’s make the pastry dough

0:02:34.125,0:02:37.075
然后加点这个粘米粉 
First add some sticky rice flour

0:02:39.775,0:02:40.675
再加点糯米粉
Then some glutinous rice flour

0:02:42.000,0:02:44.975
粘米粉和糯米粉的比例一比一就可以了
The sticky/glutinous rice flour ratio is 1:1

0:02:46.500,0:02:48.175
然后我们再加一点盐
Then add some salt in there

0:02:48.675,0:02:50.725
你一比一没得嫩糍的哦
Your 1:1 ratio will make it too dry 

0:02:51.475,0:02:52.418
嗯 差不多就行了
Emmm, it should be okay

0:02:52.425,0:02:53.975
糯米粉多加点的
I would add some more glutinous rice flour

0:02:54.800,0:03:00.725
我们捣好这个清明菜的汁现在我们把它挤进去
Now we squeeze the Qingming herb juice in there 

0:03:00.750,0:03:02.400
要的就是这个颜色
This is the color we want

0:03:05.350,0:03:07.775
好了 加（汁）水挤进去了我们把它拌匀
Then we knead it well

0:03:11.100,0:03:15.925
我们这个面和好了之后再把这个渣加进去
After we have the dough, we’ll add the squeezing in there

0:03:16.600,0:03:20.250
把这个原渣加进去给它一起挼
Knead all the squeezing into the dough

0:03:21.900,0:03:24.775
四伯爷你帮我揉到
Uncle, can you help me knead the dough?

0:03:24.775,0:03:26.325
我去把那个腊肉（香肠）弄来炒起
I’ll go stir fry the cured pork (sausage)

0:03:53.575,0:03:55.600
我先是在手头把它搓圆
First we rub it into a ball

0:03:55.700,0:03:56.925
是搓圆了样
Into a ball, done

0:03:57.575,0:04:00.250
搓圆了你摊在手头
Then put the ball in the middle of your hand

0:04:00.400,0:04:02.000
然后就捏边边
Nip the sides

0:04:02.850,0:04:04.632
你要记到捏边边不能捏中间
Be careful to only nip the sides and leave the center alone

0:04:04.632,0:04:06.550
中间要稍微厚点的都不关事
The center of the pastry can stay a little thicker

0:04:07.225,0:04:08.800
呐 这样子它就圆了
Like this round

0:04:08.800,0:04:11.700
放在手头 手弄来窝起
Put the pastry on your fingers and curl your fingers

0:04:12.225,0:04:14.850
这样子窝起然后舀一勺进去
Scoop some stuffing on the center of the pastry

0:04:16.500,0:04:18.375
这就圆了撒
I’ve made my pastry round

0:04:18.775,0:04:22.750
然后这里给它稍微捏一哈 跟包包子一样
Then we nip the edge of the pastry like we are making a dumpling

0:04:22.925,0:04:24.150
捏拢了之后再搓
After the pastry edges meet, we rub it 

0:04:26.675,0:04:29.275
这（馅料）没有放点猪油在里头炒啊
Did you put lard in the stuffing during stir frying?

0:04:30.100,0:04:33.700
那个香肠里头就有猪油撒
We already have lard in the sausage

0:04:33.725,0:04:35.475
猪油少了 我的估计
I think we don’t have enough lard in the stuffing

0:04:35.550,0:04:37.975
不少不少 都可以了
It should be okay

0:04:39.700,0:04:44.250
这样子摆起才好蒸嘛 蒸起才像猪儿粑嘛
Placing them like this is good for the shape during steaming. The pork rice cake should look like this (like a little piggy)

0:04:46.850,0:04:48.100
不是等哈要塌下来噶
Won’t it soften and fall down a bit?

0:04:48.125,0:04:52.750
哦 不是它蒸融了来它要垮下来
Yeah it will fall down a little when it is steamed (if we don’t place them like this)

0:04:52.750,0:04:55.875
垮下来就成了粑粑 圆啾啾的就不好看
If it collapses too much and become flat, it won’t look as nice.

0:04:55.875,0:04:58.125
我是想到包完了再来摆哈
I though we were going to place them after we make all of them

0:04:58.700,0:05:02.057
好了 现在我们弄好了放到（蒸锅）上汽
Alright! Now they are ready for steaming

0:05:02.550,0:05:05.625
上锅蒸 上汽了之后蒸二十分钟左右就可以吃了
Steam them for about 20 minutes and they will be ready

0:05:06.025,0:05:07.175
我先拿去蒸起
I’ll go put them on the steamer now

0:05:15.750,0:05:16.775
好 水已经开了
Alright, the water is already boiling

0:05:30.850,0:05:31.725
把它盖起
Cover it up

0:05:41.225,0:05:42.625
哦哟 
Whoa!

0:05:42.625,0:05:44.175
好大一个个的
They are huge

0:05:49.375,0:05:51.250
这个吃了来才吃那个大的
I’ll have this one first before the biggest one

0:05:51.275,0:05:52.101
你吃几个哦 吃一个就够了
How many are you going to have? I think one should be enough for you

0:05:52.150,0:05:53.000
我给你拿起来
I can get this for you

0:05:53.100,0:05:55.000
这就这样子（夹）撒
I can pick it up myself like this

0:05:56.000,0:05:57.625
伯娘吃这个 我帮你拿
Auntie have one too. Let me get one for you

0:05:59.200,0:06:00.275
好好好 谢谢
Alright, thanks

0:06:01.525,0:06:02.800
好香啊这个蒸出来
After steaming, it smells fantastic

0:06:04.825,0:06:05.700
好不好吃哦晓得
I wonder how it tastes

0:06:05.825,0:06:09.525
这个皮子逮到 我把它弄下来
The leaf is stuck on the cake. Let me peel it off

0:06:10.600,0:06:11.295
把它剁下来
Cut it off

0:06:11.325,0:06:12.375
跟它弄的糍粑样
It is almost like rice pounded paste

0:06:21.325,0:06:21.800
安逸
Nice!

0:06:21.900,0:06:22.575
要巴起
Look at him eating so happily

0:06:24.750,0:06:26.075
伯娘你笑啥子
Auntie, what are you laughing at?

0:06:28.550,0:06:29.725
笑啥子哦笑
Yeah, what are you laughing at?

0:06:32.450,0:06:34.700
你莽起笑 等我个人吃
Go ahead laughing. I’ll enjoy myself.

0:06:35.225,0:06:37.125
真的吗假的哦 各自吃完
Seriously? Have them all like you can

0:06:38.400,0:06:45.725
我伯娘笑我伯爷说这个吃了会粘牙齿 其实没什么
My auntie is mocking at my uncle that the sticky cake will stick on his teeth. It should not be that bad I guess

0:06:47.600,0:06:48.700
很香真的很香
It’s really really good

0:06:48.850,0:06:49.775
是香啊	
Yeah it is

0:06:50.200,0:06:50.700
安逸
Nice!

0:06:51.550,0:06:53.925
好吃 很糍的噶
It is good. It’s very juicy

0:06:53.925,0:06:54.800
嗯
Yeah

0:06:55.225,0:06:59.075
如果不想吃得太黏嘴的话就可以多加一点这个米粉
If you don’t like it to be too sticky, you can add more sticky rice flour

0:06:59.725,0:07:00.725
少加一点糯米粉
And hold the glutinous rice flour a little 

0:07:01.100,0:07:02.525
好 本期视频就到这里
Alright, that’s all for this episode

0:07:03.650,0:07:04.975
大家可以尝试做一下
You guys can try this recipe at home
