### ISSUE TITLE
【美食作家王刚】腌咸鸭蛋 - https://youtu.be/zfcPGG2LZVs

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#890]
**视频链接**：https://youtu.be/zfcPGG2LZVs

视频时长 3:34，预计发布时间为北京时间4月10日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“腌咸鸭蛋”保证流油的方法，简单快捷，蛋黄个个流油

简介
同学们好，今天和大家分享“腌咸鸭蛋”保证流油的方法，这种“干腌”可以确保每一颗咸蛋腌好之后都会有诱人的蛋黄油流出来，配上一碗稀饭简直不能再爽！但是“干腌”也有一些问题，就是会出现蛋白腌的不均匀，经常出现过咸的现象。如果大家对蛋黄油的要求不高，可以使用传统正宗“水腌”的方法，不易出油但香味会更多，大家可以点击链接学习：https://www.youtube.com/watch?v=kzWiPSgEKxQ&t=6s 或者选择介于“干腌”和“水腌”之间的“土法泥腌”，也可以点击链接学习：https://www.youtube.com/watch?v=eB4op6tZHU8

本期菜品：【腌咸蛋】
【主料】
鸭蛋
【辅料】
八角（几颗）
桂皮（适量）
青花椒（适量）
高度白酒（适量）
【调味料】
白醋（300克）
食用盐（1000克）

字幕
0:00:00.175,0:00:01.450
哈喽大家好我是王刚

0:00:01.450,0:00:02.825
本期视频我给大家分享

0:00:03.080,0:00:04.840
如何快速腌咸蛋

0:00:05.044,0:00:07.720
首先我们准备新鲜的鸭蛋29个

0:00:09.344,0:00:11.619
放入盆中之后加入适量的清水

0:00:12.769,0:00:15.094
再加入白醋半瓶浸泡10分钟（约300克）

0:00:17.119,0:00:19.994
10分钟之后将鸭蛋清洗干净之后捞出备用

0:00:20.069,0:00:23.919
加白醋浸泡的目的是方便去除鸭壳表面的鸭屎和杂质

0:00:26.019,0:00:27.769
下一步我们开始准备辅料

0:00:27.919,0:00:30.294
盆中加入八角几颗捏散备用

0:00:34.494,0:00:36.794
加入适量的桂皮捏成小块备用

0:00:40.544,0:00:42.394
再加入适量的青花椒

0:00:43.219,0:00:45.919
然后加入适量的清水将香料清洗干净

0:00:45.994,0:00:48.644
这一步的目的是去除香料表面的灰尘

0:00:49.694,0:00:51.944
清洗干净之后捞出备用

0:00:54.644,0:00:57.469
然后加入适量的高度白酒浸泡30分钟备用

0:00:57.594,0:01:00.169
加白酒浸泡香料的目的是使其出味

0:01:02.994,0:01:06.769
浸泡30分钟之后加入食用盐1000克搅拌均匀备用

0:01:11.169,0:01:13.119
下一步我们开始准备裹鸭蛋

0:01:13.919,0:01:16.069
首先我们准备保鲜膜1大块

0:01:16.719,0:01:18.419
将调好的盐铺上一层

0:01:20.169,0:01:22.269
然后放上清洗干净的鸭蛋

0:01:24.469,0:01:27.094
撒上适量的盐之后再均匀地裹起来即可

0:01:30.719,0:01:34.194
同学们裹得时候最好将两头稍微捏紧防止漏盐

0:01:59.394,0:02:01.444
下面大家再来仔细看一遍

0:02:44.419,0:02:47.844
鸭蛋裹好之后再放入瓦罐坛子中储存30天即可

0:02:48.094,0:02:50.744
同学们切记坛子不可放在暴晒的地方

0:02:50.844,0:02:53.069
必须储存于避免阳光 阴暗的地方

0:02:53.344,0:02:56.294
30天之后将其取出煮熟之后即可食用

0:02:57.300,0:03:00.160
一份简单快捷的咸鸭蛋就制作完成

0:03:12.560,0:03:33.240
下面开始技术总结
第一，同学们最好选择鸭蛋制作，咸蛋中只有鸭蛋最香油最多
第二，如果选择鸡蛋腌制，首先必须缩减时间，理论上鸡蛋只需要24天即可
第三，腌制咸蛋时盐必须给足，因为咸蛋不怕咸就怕盐不够
咸鸭蛋的技术总结完毕


```

**Comment by WuStevenShengyang** [comment]
我來

**Comment by WuStevenShengyang** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“腌咸鸭蛋”保证流油的方法，简单快捷，蛋黄个个流油
Chef Wang teaches you: Cured Duck Eggs. Easy and fast; the eggs are full of oil.
简介
同学们好，今天和大家分享“腌咸鸭蛋”保证流油的方法，这种“干腌”可以确保每一颗咸蛋腌好之后都会有诱人的蛋黄油流出来，配上一碗稀饭简直不能再爽！但是“干腌”也有一些问题，就是会出现蛋白腌的不均匀，经常出现过咸的现象。如果大家对蛋黄油的要求不高，可以使用传统正宗“水腌”的方法，不易出油但香味会更多，大家可以点击链接学习：https://www.youtube.com/watch?v=kzWiPSgEKxQ&t=6s 或者选择介于“干腌”和“水腌”之间的“土法泥腌”，也可以点击链接学习：https://www.youtube.com/watch?v=eB4op6tZHU8
Hey friends, today I will share the recipe of cured duck eggs with you. 
这种“干腌”可以确保每一颗咸蛋腌好之后都会有诱人的蛋黄油流出来，
By curing the eggs, we can ensure that every single egg has delicious oil.
配上一碗稀饭简直不能再爽！
The perfect accompany with a bowl of rice.
但是“干腌”也有一些问题，就是会出现蛋白腌的不均匀，经常出现过咸的现象。
But the problem with curing is that the yolk and the egg white might be unevenly cured, resulting in an overly salted egg.
如果大家对蛋黄油的要求不高，可以使用传统正宗“水腌”的方法，
If you don't require your eggs to have oil, you can just use the traditional method to marinate.
不易出油但香味会更多，
This method will produce less oil but more fragrance.
大家可以点击链接学习：https://www.youtube.com/watch?v=kzWiPSgEKxQ&t=6s 
Links to traditional marinate: https://www.youtube.com/watch?v=kzWiPSgEKxQ&t=6s 
或者选择介于“干腌”和“水腌”之间的“土法泥腌”，也可以点击链接学习：https://www.youtube.com/watch?v=eB4op6tZHU8
Or, you can chose to marinate using dirt: https://www.youtube.com/watch?v=eB4op6tZHU8

本期菜品：【腌咸蛋】
Dish: Cured Duck Eggs
【主料】
Major Ingredient:
鸭蛋
Duck eggs
【辅料】
Other Ingredient:
八角（几颗）
Star anise (several)
桂皮（适量）
Cinnamon (several)
青花椒（适量）
Sichuan green peppercorn (several)
高度白酒（适量）
Baijiu (Chinese Liquor)

【调味料】
Seasoning:
白醋（300克）
White vinegar (300 grams)
食用盐（1000克）
Salt (1000 grams)

字幕
0:00:00.175,0:00:01.450
哈喽大家好我是王刚
Hello, this is Chef Wang Gang.

0:00:01.450,0:00:02.825
本期视频我给大家分享
Today I will share a recipe with you:

0:00:03.080,0:00:04.840
如何快速腌咸蛋
Cured Duck Eggs (Easy Version)

0:00:05.044,0:00:07.720
首先我们准备新鲜的鸭蛋29个
First, we will get 29 fresh duck eggs.

0:00:09.344,0:00:11.619
放入盆中之后加入适量的清水
Add in some water after placing them in a bowl.

0:00:12.769,0:00:15.094
再加入白醋半瓶浸泡10分钟（约300克）
Add half a bottle of white vinegar (about 300 grams) into the water and soak the eggs for 10 minutes.

0:00:17.119,0:00:19.994
10分钟之后将鸭蛋清洗干净之后捞出备用
After 10 minutes, clean up the eggs.

0:00:20.069,0:00:23.919
加白醋浸泡的目的是方便去除鸭壳表面的鸭屎和杂质
Adding white vinegar will remove the faeces and dirt on the eggshells. 

0:00:26.019,0:00:27.769
下一步我们开始准备辅料
Next, let's prepare other ingredients.

0:00:27.919,0:00:30.294
盆中加入八角几颗捏散备用
Add some star anises into the bowl.

0:00:34.494,0:00:36.794
加入适量的桂皮捏成小块备用
Break the cinnamons into small chunks and add them into the bowl.

0:00:40.544,0:00:42.394
再加入适量的青花椒
Then, we add some Sichuan green peppercorn.

0:00:43.219,0:00:45.919
然后加入适量的清水将香料清洗干净
Add in some water to rinse the spices.

0:00:45.994,0:00:48.644
这一步的目的是去除香料表面的灰尘
This step will remove the dirt on the spices.

0:00:49.694,0:00:51.944
清洗干净之后捞出备用
Take out the spices afterwards.

0:00:54.644,0:00:57.469
然后加入适量的高度白酒浸泡30分钟备用
Add some Baijiu (Chinese liquor) and soak the spices for an additional 30 minutes.

0:00:57.594,0:01:00.169
加白酒浸泡香料的目的是使其出味
Soaking the spices with Baijiu will bring out the aroma.

0:01:02.994,0:01:06.769
浸泡30分钟之后加入食用盐1000克搅拌均匀备用
After 30 minutes, add in 100 grams of salt and mix them together.

0:01:11.169,0:01:13.119
下一步我们开始准备裹鸭蛋
The next step is to wrap the eggs.

0:01:13.919,0:01:16.069
首先我们准备保鲜膜1大块
We need a large layer of plastic foil.

0:01:16.719,0:01:18.419
将调好的盐铺上一层
Spread a layer of pre-made salt evenly.

0:01:20.169,0:01:22.269
然后放上清洗干净的鸭蛋
Then, put the eggs on.

0:01:24.469,0:01:27.094
撒上适量的盐之后再均匀地裹起来即可
Spread some additional salt and wrap the foil around.

0:01:30.719,0:01:34.194
同学们裹得时候最好将两头稍微捏紧防止漏盐
We need to twist the sides tighly so that the salt won't come out. 

0:01:59.394,0:02:01.444
下面大家再来仔细看一遍
Let's do this again.

0:02:44.419,0:02:47.844
鸭蛋裹好之后再放入瓦罐坛子中储存30天即可
We will seal the eggs into the jar for 30 days and they will be ready to eat.

0:02:48.094,0:02:50.744
同学们切记坛子不可放在暴晒的地方
We can't put the jar under the sun.

0:02:50.844,0:02:53.069
必须储存于避免阳光 阴暗的地方
It must be stored away from the sun.

0:02:53.344,0:02:56.294
30天之后将其取出煮熟之后即可食用
After 30 days, take out the eggs and boil them before serving.

0:02:57.300,0:03:00.160
一份简单快捷的咸鸭蛋就制作完成
A easy and fast version of cured duck eggs is complete.

0:03:12.560,0:03:33.240
下面开始技术总结
第一，同学们最好选择鸭蛋制作，咸蛋中只有鸭蛋最香油最多
第二，如果选择鸡蛋腌制，首先必须缩减时间，理论上鸡蛋只需要24天即可
第三，腌制咸蛋时盐必须给足，因为咸蛋不怕咸就怕盐不够
咸鸭蛋的技术总结完毕
Now, let's head to the technical summary:
First, it is recommended to use duck eggs, because they have the most oil.
Second, if we use normal eggs instead, we have to reduce the cure time to only 24 days.
Third, we have to use a generous amount of salt for better taste.
That's all for the technical summary.
