### ISSUE TITLE
[老饭骨] 三叔私房茄子 - https://www.youtube.com/watch?v=SVCxFu7ID1g

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#895]
**视频链接**：https://www.youtube.com/watch?v=SVCxFu7ID1g

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•私房茄子】全国独一味儿的私房茄子，集老饭骨三人研究之精华，酒香四溢，绝了！

简介
小友们好，今天这私房茄子可是咱哥仨一起研究出来，
在三叔的基础上，茄子二次加热的时候再铺上醪糟和花雕酒。
做了一点小的变化，全国独一味儿，真香！
除了视频里用到的北京茄子以外，大家还可以因地制宜。
烹饪技巧不变，食材可以变化，正所谓一通百通呐！
小友们可要睁大眼仔细看好这视频了，因为是早期拍摄的视频，
所以镜头有些许晃悠，还请大家多包涵。

# import intro 稿件内请原样保留此行

字幕
需自行制作时间轴及对照中文

# import ending.sbv 0:04:17.600 稿件内请原样保留此行
```

**Comment by CapatainZ** [comment]
认领

**Comment by CapatainZ** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•私房茄子】全国独一味儿的私房茄子，集老饭骨三人研究之精华，酒香四溢，绝了！ 
State Banquet Master Chefs - We made the most unique private eggplant in China.
简介
小友们好，今天这私房茄子可是咱哥仨一起研究出来, 在三叔的基础上，茄子二次加热的时候再铺上醪糟和花雕酒。
做了一点小的变化，全国独一味儿，真香！
除了视频里用到的北京茄子以外，大家还可以因地制宜。
烹饪技巧不变，食材可以变化，正所谓一通百通呐！
小友们可要睁大眼仔细看好这视频了，因为是早期拍摄的视频，
所以镜头有些许晃悠，还请大家多包涵。
Hello friends, this dish was designed by three of us, based on the work of San Shu, we add rice wine and HuaDiao at the process of heating eggplant.
This little change made this dish unique in China.
Besides the Beijing eggplants used in the video, you guys can also choose the ingredients which adapt to your local condition.
The cooking skills are as usual; however, the ingredients are not unchangeable, just like we always said: master the one to master all!
By the way, the video was filmed early and the camera is a little swaying. So we hope you guys watch it more carefully and enjoy it

# import intro 

字幕

0:00:00.000,0:00:01.580
今天咱们做的什么菜你知道吗
Do you know what kind of dishes we cook today?

0:00:01.600,0:00:02.820
就觉得是茄子
I think it is eggplant

0:00:02.840,0:00:04.020
私房茄子
private eggplant

0:00:04.020,0:00:06.220
他既然要传承他肯定要切梳子花刀
Cut it to a comb form is necessary since our seniors told us to do it

0:00:06.220,0:00:07.100
对
Right

0:00:07.100,0:00:09.220
这就是咱北京茄子
That's our Beijing eggplant

0:00:09.220,0:00:10.820
没有籽儿
No seeds inside it 

0:00:10.820,0:00:12.600
这个季节正好是吃茄子的时候
This season happens to be the good time to eat eggplant

0:00:12.600,0:00:13.980
茄子对身体确实好
Eggplant is indeed good for health

0:00:13.980,0:00:15.660
对啊 含铁巨大
Of course, it contains huge iron elements

0:00:15.660,0:00:17.060
你看
Watch it

0:00:19.580,0:00:21.340
这叫什么刀儿
What do you call for this style of cutting

0:00:21.340,0:00:22.460
梳子花刀
comb style

0:00:22.460,0:00:24.380
像梳子吗 拿来我看看
Does it look like a comb? Show me please

0:00:24.380,0:00:25.200
像梳子啊
Sure

0:00:27.420,0:00:28.380
拿一盆
Now, put it to a bowl

0:00:28.380,0:00:30.380
为什么这么切 它容易进味儿
Why we cut it in this way? it will taste much better

0:00:30.380,0:00:33.140
便于烹调 便于入味
Easier to cook and tastier

0:00:33.140,0:00:35.140
北京茄子不削皮
Beijing eggplant does not peel

0:00:35.140,0:00:37.620
削了皮这茄子烧出来没有灵魂
If this eggplant without exocarp without a soul

0:00:37.620,0:00:38.840
对 不好看
Right, not pretty anymore

0:00:38.840,0:00:40.620
烧完了 站不住
It's not solid after cooking it

0:00:40.620,0:00:42.340
跟一滩烂泥似的
Just like a piece of rotten mud

0:00:42.340,0:00:44.820
其实好多营养都在茄子皮上呢
In fact, a lot of nutrition is on its exocarp

0:00:44.820,0:00:48.420
这个不弹粉就生炸
Just fry it, no need to add the starch on it

0:00:48.420,0:00:49.920
然后我们就开始兑汁儿
Then, we start to prepare the sauce

0:00:49.920,0:00:51.420
先搁糖 够啦
add sugar firstly. Enough now

0:00:51.420,0:00:54.300
叫 甜 咸 鲜 香
We call it sweet salty fresh aroma

0:00:54.300,0:00:57.220
够不够 盐
Is this enough? salt

0:00:57.220,0:00:59.340
两勺糖 一勺盐
Two spoons of sugar and a spoon of salt

0:00:59.340,0:01:01.520
（花雕）酒
(Hua Diao)  wine

0:01:01.520,0:01:02.900
你看看这是什么啊
Look what this is

0:01:02.900,0:01:04.860
醪糟
rice wine

0:01:04.860,0:01:06.820
醪糟要三到四勺
We need three or four spoons of rice wine

0:01:06.820,0:01:10.220
让所有茄子全展示出米的感觉
Let all the eggplants show the feeling of rice

0:01:10.220,0:01:14.060
酱油
Soy sauce

0:01:14.060,0:01:14.600
好
OK

0:01:14.600,0:01:15.660
老抽
Dark Soysauce

0:01:15.660,0:01:17.500
香油
Sesame oil

0:01:17.500,0:01:19.500
搁完香油怎么办啊
What's the next step then

0:01:19.500,0:01:20.380
葱 姜 蒜
Onion ginger garlic

0:01:20.380,0:01:21.000
好
OK

0:01:21.000,0:01:23.780
这油现在已经到三成热了 四成了
The oil is medium rare now

0:01:23.780,0:01:24.900
还不下（茄子）啊
Why not pour the eggplant now

0:01:24.900,0:01:27.020
不着急
No need to hurry

0:01:27.020,0:01:28.600
蒜片
Garlic

0:01:28.600,0:01:30.140
烧茄子少不了蒜
Garlic is essential for this dish

0:01:30.140,0:01:30.860
对
Sure

0:01:30.860,0:01:32.980
不要太多 多了之后显得菜乱
No need too much of them, otherwise it will be a little messy

0:01:32.980,0:01:35.420
一般这醪糟啊都是白汁的多
Generally speaking, the rice wine is always full of white juice

0:01:35.420,0:01:36.200
葱花
Onion

0:01:36.200,0:01:38.640
这姜丝切这么溜土豆丝让我切
Let me cut the potato once you finished the ginger

0:01:41.760,0:01:44.240
这肉用腌制一下啊 不用
Should we marinate the meat? No need to do it

0:01:44.240,0:01:46.120
用不用调味啊 不用
add condiment? No

0:01:49.260,0:01:51.260
这颜色就好啦
This color is perfect

0:01:51.260,0:01:52.420
淀粉
Starch

0:01:53.620,0:01:56.480
这三叔这茄子油可没少吃啊
San Shu add a little more oil than most people for this eggplant

0:01:56.480,0:01:58.140
是啊 油太大啦
You are right

0:01:58.140,0:01:59.740
这茄子炸到什么程度呢
How long we need to fry the eggplants?

0:01:59.740,0:02:01.840
金黄色 金黄
Golden color

0:02:01.840,0:02:03.020
然后到这种程度呢
After reaching this level

0:02:03.020,0:02:03.960
还要复炸一下
We need to fry it again

0:02:03.960,0:02:05.720
捞出来 上上油温
Lift it, pour few oil over it

0:02:05.720,0:02:09.420
这茄子吃的才香呢
Only this kind of eggplants will taste delicious

0:02:09.420,0:02:10.620
是香啊 绵
Of course it is

0:02:10.620,0:02:11.700
油可没少加
We also add lots of oil

0:02:11.700,0:02:13.740
你现在看它油大
The oil is plenty now

0:02:13.740,0:02:15.240
待会把油温烧起来
After a period of time

0:02:15.240,0:02:17.340
再一复炸的时候
And fry the eggplants 

0:02:17.340,0:02:19.580
它这油就给逼出来了
The oil will be kicked out from it

0:02:19.580,0:02:22.060
过去老师傅
In the past

0:02:22.060,0:02:25.540
我们这代人传承的老北京烧茄子
The Beijing eggplant in our generation

0:02:25.540,0:02:26.440
咱不能加淀粉
We cannot add starch

0:02:26.440,0:02:28.860
现在为什么加淀粉你知道么
Do you know why we add starch now?

0:02:28.860,0:02:30.860
为了方便卖这茄子
It's for selling the eggplant more easily

0:02:30.860,0:02:32.240
加上淀粉它不爱塌
It will be more solid after add starch

0:02:32.240,0:02:33.140
撑盘儿
The appearance is more beautiful

0:02:33.140,0:02:36.020
咱这个烹制当时就吃
We eat it after we finish the whole process

0:02:36.020,0:02:38.140
为什么说好吃啊 对
Because it is delicious

0:02:38.140,0:02:39.040
复炸一次
Re-fry now

0:02:39.040,0:02:40.820
毛豆
soybean

0:02:40.820,0:02:42.380
搁豌豆行吗 行
How about pea？ Sure

0:02:42.380,0:02:44.220
就是配色
It's just for adding  colors

0:02:44.220,0:02:46.480
中餐我还是那句话
I always say one thing about Chinese food

0:02:46.480,0:02:47.580
没油真不好吃
You have to add enough oil to cook

0:02:47.580,0:02:49.400
提倡的是低油您提倡的是高油
Others are advocating low oil and you are advocating high oil

0:02:49.400,0:02:51.900
对 油要大啊
Definitely

0:02:51.900,0:02:54.220
留点底油
remain a little bit oil in the pot

0:02:54.220,0:02:55.120
牛肉末
beef

0:02:55.120,0:02:57.200
一定要煸透煸干
You have to keep cooking until there is no water inside the beef

0:02:57.200,0:02:59.060
煸香煸干于颗粒状
And make it looks like particles

0:02:59.060,0:03:01.040
大爷 请
Be my guest, Da Ye

0:03:01.040,0:03:04.140
一勺 两勺
One spoon Two spoons

0:03:04.140,0:03:06.220
勾汁 上芡
flip it few time

0:03:08.220,0:03:10.060
快 出锅
Done

0:03:10.060,0:03:12.000
二哥来啦
Er Ge, Here we go

0:03:12.000,0:03:14.820
私房茄子 香气出来了啊
Private eggplant, the aroma is spreading over now

0:03:14.820,0:03:16.380
再二次加热
Reheat it now

0:03:16.380,0:03:17.600
盖盖了你呐
Close the lid 

0:03:17.600,0:03:18.400
好啦
OK

0:03:18.400,0:03:20.200
二伯要出手啦
Er Bai is coming now

0:03:20.200,0:03:21.820
这是老饭骨私房茄子
This is Lao Fan Gu's private eggplant

0:03:21.820,0:03:23.860
在三叔的基础上
Based on the San Shu's work

0:03:23.860,0:03:26.140
我们仨刚才一致研究决定
We have just unanimously decided

0:03:26.140,0:03:27.720
这茄子在中国独一味儿
This eggplant is the most unique one

0:03:27.720,0:03:28.420
你看看（加入醪糟）
Look at it(add rice wine)

0:03:28.420,0:03:29.260
拿筷子扒拉扒拉
Mix it by using the  chopsticks

0:03:29.260,0:03:30.780
这不用 就要这劲
No need to do it 

0:03:30.780,0:03:32.820
看见没有
Just like this

0:03:32.820,0:03:34.200
取香
extract the aroma

0:03:34.200,0:03:36.040
火燎（加入花雕）
add Hua Diao

0:03:36.040,0:03:37.080
看看这香
smells pretty good

0:03:37.080,0:03:39.100
满厨房都是香味啊大爷
it exists in the whole kitchen

0:03:39.100,0:03:41.440
不是香味是酒味 酒香味
It's actually the aroma of wine

0:03:41.440,0:03:43.240
砂锅不能搁到木墩子上
Do not put that pot above the wooden surface

0:03:43.240,0:03:45.240
掀锅
Open the lid

0:03:47.320,0:03:49.740
关键就是这一拌一搅和
The important process is to mix it 

0:03:52.620,0:03:54.180
香么
Smells good?

0:03:54.180,0:03:57.020
香香香
Absolutely

0:03:57.020,0:03:58.360
这茄子绝了
The eggplant is so delicious

0:03:58.360,0:03:59.180
又来一口
One more  time

0:03:59.180,0:04:00.880
烫的直眨眼
Still so hot

0:04:04.180,0:04:06.740
就这种做法适合好多菜
This method is suitable for lots of other food

0:04:06.740,0:04:09.420
比如说丝瓜也可以这么做
Such as loofah

0:04:09.420,0:04:11.420
哎呦  丝瓜才好吃呢
You got it

# import ending.sbv 0:04:17.600
