### ISSUE TITLE
[华农兄弟] 华农兄弟兄弟家的茶叶树又长嫩叶了摘点来做茶叶蛋很香哦 - https://youtu.be/lmPda_2T2rw

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#896]
https://youtu.be/lmPda_2T2rw
<p>&#35270;&#39057;&#21457;&#24067;&#20110; April 7, 2020 at 06:05PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/lmPda_2T2rw

#华农兄弟：兄弟家的茶叶树又长嫩叶了，摘点来做茶叶蛋，很香哦
#Huanong Brothers: The shoots are growing on my buddy's tea tree. We pick some and make some tea eggs. It smells so good!

0:00:00.340,0:00:02.280
# 今天年又來摘一點兄弟家的茶葉啊
We come again to pick my buddy's tea leaves this year.

0:00:02.920,0:00:04.280
# 回去做個茶葉蛋吃
Let's make a tea egg at home.

0:00:05.620,0:00:06.760
# 這茶葉很嫩的
These leaves are really young.

0:00:07.920,0:00:11.040
# 你看這個茶葉 剛剛長出個嫩葉子來哦
Look at the leaves. The young ones have just started growing.

0:00:12.720,0:00:13.640
# 這個很嫩的
These are really young.

0:00:15.020,0:00:15.940
# 只要那個
We just want the,

0:00:16.720,0:00:18.560
# 那個嫩芽  一點點就夠了
the shoots, a little bit of the shoots, not too much.

0:00:22.440,0:00:25.500
# 按  按著摘  不然它老是
I put it, put it under my arm. Otherwise, it's always,

0:00:25.900,0:00:26.780
# 晃來晃去
swinging here and there

0:00:33.920,0:00:36.180
# 這個葉不摘掉也會老掉的
The tea leaves would get old even if they're left here.

0:00:38.820,0:00:39.960
# 老的很快的
They get old really quickly.

0:00:59.740,0:01:03.140
# 你看  這個  每一片葉子下面都長了一個嫩芽
Look! Here! There's a shoot below each leaf.

0:01:05.140,0:01:06.580
# 很嫩的哦  一摘就斷
They are really young. I can pick them out without much effort.

0:01:08.760,0:01:09.560
# 這一個不要
I'm not taking this part.

0:01:10.340,0:01:11.080
# 插回去
Let me put it back

0:01:16.360,0:01:17.820
# 你看  摘了那麼多啦
Look! We have a lot here now!

0:01:19.860,0:01:21.000
# 好香啊  這個
It smells really good!

0:01:21.640,0:01:22.680
# 搓起來更香
It smells even better when it's squeezed.

0:01:27.560,0:01:28.340
# 準備回去
Let's get ready to go back.

0:01:43.680,0:01:44.760
# 你看  這邊好多
Look! Here are a lot!

0:01:48.000,0:01:50.620
# 這個很漂亮的  一茶都是  (註︰怎麼是「一茶都是」？)
It's really pretty! All over the tea...

0:01:52.440,0:01:55.220
# 要把茶葉修一下  就打(?)很多茶葉出來
A lot of leaves are growing out after cutting away some leaves.

0:01:55.820,0:01:57.080
# 這個都沒人修的
But no one do that,

0:01:58.080,0:01:59.360
# 兄弟家又一條
neither my buddy,

0:02:01.740,0:02:03.280
# 每年都是我幫他修
except me. I do it for him every year.

0:02:05.020,0:02:07.000
# 先把這個茶葉  先把它搞
Let's put the tea leaves here first, and then, well,

0:02:08.000,0:02:09.340
# 先把它烘乾來
then let's try them on the heat.

0:02:13.180,0:02:14.320
# 這溫度有點燙
The temperature is rather high.

0:02:15.000,0:02:16.300
# 它溫度又不能太燙
But in fact it can't be too high.

0:02:29.160,0:02:30.240
# 再搓一下
Let' squeeze them.

0:02:31.740,0:02:32.300
# 燙啊
Hot!

0:02:47.620,0:02:49.100
# 這個條要很有耐心的
Doing this job requires a lot of patience.

0:02:49.340,0:02:50.140
# 不然做不到
Patience is essential.

0:02:51.080,0:02:52.180
# 做的很漂亮的
It's really pretty.

0:02:52.920,0:02:53.420
# 我們
I mean,

0:02:53.980,0:02:57.040
# 我們村的老人家做的很靚的  我做的就怎麼好
the elderlies in our village can make really beautiful tea leaves. But I can't make anything appealing.

0:03:13.600,0:03:14.540
# 再搓一下
Squeeze again

0:03:31.460,0:03:32.480
# 一搓就把它
They become a ball,

0:03:33.500,0:03:34.940
# 搓成一團去了
whenever I squeeze them.

0:03:44.320,0:03:45.340
# 你看 差不多好啦
Look! It's almost done.

0:03:45.720,0:03:46.620
# 有點像茶葉啦
They start to look like tea leaves now.

0:03:56.880,0:03:58.980
# 好香啊  這茶葉  真的
It smells so good! The leaves are, really...

0:04:00.220,0:04:01.580
# 這個茶葉搞好啦
So the tea leaves are ready now.

0:04:02.020,0:04:03.020
# 很漂亮的哦
It's so pretty!

0:04:04.580,0:04:06.140
# 你看  綠色的
Look! It's green,

0:04:07.000,0:04:07.920
# 深綠色的
dark green.

0:04:09.220,0:04:10.520
# 我去檢兩個雞蛋回來
Let me pick a couple of eggs.

0:04:12.240,0:04:13.940
# 這個有一個雞窩的哦  有蛋
Here's a chicken roost. Yea, eggs!

0:04:15.940,0:04:16.820
# 哇  這里有
Wa! Eggs!

0:04:19.100,0:04:19.960
# 有五個
Not one but five!

0:04:21.440,0:04:22.640
# 這裡面也有個雞窩的
There's another chicken roost inside.

0:04:24.560,0:04:26.300
# 這裡也有五個雞蛋哦
Here are five eggs too.

0:04:27.640,0:04:29.380
# 剛好煮十個  十個蛋
Ten is a good number, ten eggs.

0:04:35.320,0:04:37.140
# 這個是正宗的土雞蛋哦
These are authentic local eggs.

0:04:38.080,0:04:39.520
# 這是我自家養的雞
They're from my own chickens.

0:04:39.660,0:04:41.700
# 你看  就這個  就它  跟它
Look! It's that one, that one, and that one.

0:04:42.260,0:04:43.360
# 兩個母雞下的
The eggs are from these two hens.

0:04:44.860,0:04:46.240
# 借你的蛋用一下
Lend me your eggs for a while!

0:04:55.720,0:04:56.280
# 哇
Wa!

0:04:56.900,0:04:57.480
# 這個
It ah,

0:04:57.940,0:04:59.540
# 應該  快熟啦
should be, almost done!

0:05:03.920,0:05:04.600
# 要它把
I need to,

0:05:05.640,0:05:07.700
# 要一個個把它敲破才行的這個
I need to crack their shells one by one, you know.

0:05:16.760,0:05:17.680
# 放點鹽下去
Put some salt.

0:05:19.860,0:05:22.020
# 這個鹽要放多一點  因為水比較多
I need a bit more salt as there's too much water.

0:05:24.060,0:05:24.780
# 放點鹽
Put some salt.

0:05:25.340,0:05:26.360
# 放點  醬油
Put some, soy sauce.

0:05:31.320,0:05:32.920
# 再放點這個茶葉
And then some, you know, you tea leaves.

0:05:36.700,0:05:38.140
# 正宗的茶葉蛋
Authentic tea eggs!

0:05:39.360,0:05:40.140
# 是不是這樣做的
Am I doing it right?

0:05:40.380,0:05:40.880
# 我也
It's,

0:05:41.340,0:05:42.020
# 第一次做
my first time.

0:05:43.260,0:05:44.440
# 先把蓋子蓋起來
Let me cover it first.

0:05:46.640,0:05:48.300
# 哇  好香啊
Wa! It smells so good!

0:06:36.060,0:06:37.280
# *華農哥別吃我  (註︰以下有*號的是B站「紅色激情」做的鬼畜，歌詞翻譯要考慮旋律)
Sir Huanong, don't eat me!

0:06:37.520,0:06:38.880
# *給你穿女裝
Girl's costume for you.

0:06:39.100,0:06:40.360
# *華農哥別吃我
Sir Huanong, don't eat me!

0:06:40.580,0:06:41.900
# *給你穿女裝
Girl's costume for you.

0:06:42.140,0:06:43.420
# *白色女裝好漂亮
White girl's costume so pretty.

0:06:43.680,0:06:44.820
# *免死金牌噹噹響
Amnesty medal ding dong ding

0:06:45.120,0:06:46.420
# *真漂亮  真漂亮
So pretty, so pretty

0:06:46.680,0:06:47.680
# *我要穿女裝
I want girl's costume!

0:06:51.080,0:06:52.460
# *華農哥別吃我
Sir Huanong, don't eat me!

0:06:52.680,0:06:53.940
# *我幫你送終
I show condolence

0:06:54.160,0:06:55.400
# *華農哥別吃我
Sir Huanong, don't eat me!

0:06:55.540,0:06:56.760
# *我幫你送終
I show condolence

0:06:57.200,0:06:58.200
# *老子還能活很久
I still have a long long life

0:06:58.380,0:06:59.920
# *今天先給你送終
Let me show condolence first

0:06:59.920,0:07:01.260
# *拔了毛  放點葱
Dehair first, spring onions

0:07:01.480,0:07:02.680
# *文火三分鐘
Low heat three minutes.

0:07:06.060,0:07:07.260
# *華農哥別吃我
Sir Huanong, don't eat me!

0:07:07.660,0:07:08.880
# *我給你下蛋
I lay eggs for you.

0:07:09.080,0:07:10.400
# *華農哥別吃我
Sir Huanong, don't eat me!

0:07:10.560,0:07:11.560
# *我給你下蛋
I'll lay eggs for you.

0:07:12.140,0:07:13.220
# *你家公雞能下蛋?
Can your rooster lay some eggs?

0:07:13.680,0:07:15.040
# *切開肚皮看一看?
Would you open it's belly?

0:07:15.200,0:07:16.220
# *你看看  你看看
Have a look! Have a look!

0:07:16.580,0:07:17.880
# *公雞沒有蛋
Rooster has no eggs!

0:07:21.040,0:07:22.120
# 看一下熟了沒有
Let me see if it's done.

0:07:23.720,0:07:24.980
# 哇  這肯定熟的
Wa! It's done, undoubtedly.

0:07:25.400,0:07:26.700
# 先來  嘗一個
Let me, try one first.

0:07:28.920,0:07:30.060
# 顏色都變了
The colour has already changed.

0:07:30.320,0:07:31.020
# 變色了
It has changed.

0:07:34.000,0:07:35.080
# 看上去都好吃
It looks really tasty.

0:07:35.500,0:07:36.320
# 變紫色了
It has turned purple.

0:07:38.680,0:07:40.520
# 好燙啊  我去泡一下水
It's hot! Let me rinse it.

0:07:58.660,0:08:00.100
# 哇塞  你看
Wa, gosh! Look!

0:08:00.400,0:08:01.180
# 看著就靚
It's so beautiful!

0:08:02.360,0:08:03.180
# 看上去就
It looks really,

0:08:04.200,0:08:05.840
# 好吃  看上去就好吃
tasty. It looks really tasty.

0:08:13.400,0:08:14.000
# 可以呦
It's not bad!

0:08:14.980,0:08:16.280
# 這個是土雞蛋來的
It's our local egg here.

0:08:18.500,0:08:19.540
# 味道完全
It taste completely,

0:08:20.600,0:08:21.180
# 不一樣
different.

0:08:27.860,0:08:28.880
# 你看  這蛋黃
Look! The egg yolk,

0:08:30.400,0:08:31.220
# 很鮮黃
the colour is so bright.

0:08:44.460,0:08:46.820
# 就是這個雞蛋  這個雞蛋小了一點
My only complaint is that the egg, the egg is a bit too small.

0:08:47.900,0:08:48.820
# 不是很大
It's not big.

0:08:51.340,0:08:54.400
# 你看這個茶葉蛋變成這樣顏色 變紫色了
Look! The colour of the tea eggs has changed, changed to purple.

0:08:55.500,0:08:56.240
# 可以吃了
We can enjoy them now.

0:08:56.840,0:08:57.700
# 放在桌子上
Let me put them on the table,

0:08:59.040,0:08:59.980
# 放到里面吃
take them inside.

0:09:05.300,0:09:07.160
# 你看  這個雞蛋有茶葉味了哦
Look! The egg now has the flavour of tea leaves,

0:09:07.460,0:09:08.520
# 淡淡的香味
a subtle fragrance.

0:09:15.480,0:09:15.980
# 嗯
Um!

0:09:16.620,0:09:17.120
# 可以
Not bad!

0:09:17.500,0:09:18.240
# 好吃是吧
Isn't it tasty?

0:09:19.660,0:09:20.540
# 很好吃  真的
It's really tasty, no kidding.

0:09:20.920,0:09:22.080
# 比外面買的還好吃
It tastes even better than those sold in shops.

0:09:25.300,0:09:27.420
# 啊呀  是啊  這蠻好吃的
Aya.
Yea, it's rather tasty.

0:09:29.100,0:09:31.880
# 好啦  今天的視頻到這裡啦
Alright! The video ends here.

0:09:33.980,0:09:35.140
# 我先把它吃完再說
Let me finish it first.

0:09:41.740,0:09:42.980
# 好燙
Very hot!
