### ISSUE TITLE
【美食作家王刚】番茄煎蛋汤 - https://youtu.be/R5pWQPNBWrU

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#898]
**视频链接**：https://youtu.be/R5pWQPNBWrU

视频时长 4:24，预计发布时间为北京时间4月11日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“番茄煎蛋汤”的四川家常做法，汤鲜味美很开胃，加一把面就是“番茄煎蛋面”

简介
大家好，今天和大家分享一道简单美味的四川特色“番茄煎蛋汤”，提前将蛋煎好再加入开水吊汤，煮出来的汤浓白味鲜，个人觉得比番茄蛋花汤要好喝很多，并且真的很简单，只要掌握到小技巧可以轻松做出。如果朋友们没有喝过这样做的番茄蛋汤一定要试一试，保证好喝！最后上了一天班到家很累不想做饭的朋友可以把这道汤煮好后下一把挂面，一道美味的“番茄煎蛋面”就做好了，是不是超级简单，再也没有理由说劝退了，学起来！

字幕
0:00:00.000,0:00:00.647
哈喽 大家好

0:00:00.702,0:00:02.356
今天跟大家分享一个汤

0:00:02.370,0:00:04.038
就是番茄泡蛋汤

0:00:04.162,0:00:06.588
我们这边说的这个泡蛋汤

0:00:06.629,0:00:07.842
其实就是煎蛋汤

0:00:07.980,0:00:10.144
然后番茄蛋汤其实够简单的了

0:00:10.337,0:00:12.405
然后就是分享一些不一样的做法

0:00:13.659,0:00:15.042
我们看这个番茄新不新鲜

0:00:15.042,0:00:16.007
就是看这个位置

0:00:16.386,0:00:18.208
这个（蒂）还是绿色的

0:00:20.856,0:00:22.083
我们切这个番茄的时候

0:00:22.083,0:00:23.955
中间这个（蒂）最好是把它去掉

0:00:24.311,0:00:25.364
先从中间切开

0:00:26.178,0:00:29.097
然后左边一刀 右边一刀

0:00:29.415,0:00:30.323
这样子它就下来了

0:00:31.208,0:00:32.490
我们切这个番茄

0:00:32.947,0:00:34.183
这次我们切厚一点

0:00:34.462,0:00:37.097
切厚一点就是让它中间有足够的汁水

0:00:37.676,0:00:38.852
待会儿煮了之后

0:00:39.153,0:00:40.423
这个汁水就不会流出来

0:00:40.423,0:00:41.493
不会流失

0:00:41.565,0:00:43.337
吃的时候感觉饱满比较多汁

0:00:48.239,0:00:50.356
别看一个简简单单的一个番茄蛋汤

0:00:50.473,0:00:52.457
这中间有很多的小技巧

0:00:53.732,0:00:54.668
然后我们来打鸡蛋

0:00:57.292,0:00:58.874
然后我们这个鸡蛋打的时候

0:00:59.610,0:01:03.225
尽量的把这个鸡蛋给它蛋液挑起来

0:01:03.392,0:01:04.305
让空气进去

0:01:04.612,0:01:06.351
这样子煎出来蛋才够嫩

0:01:08.270,0:01:09.563
把这个蛋液挑起来

0:01:09.830,0:01:12.457
空气进去之后这个蛋液里面会有很多小气泡

0:01:14.009,0:01:15.726
我们一般在酒店里面做的话

0:01:15.774,0:01:18.550
这个蛋液里面要加一点醋 提升它的鲜味

0:01:18.904,0:01:19.755
然后再加一点盐

0:01:21.551,0:01:23.266
好 我们打好了蛋液你看

0:01:23.348,0:01:24.491
非常多的小气泡

0:01:24.818,0:01:27.274
这就说明蛋液打的比较成功

0:01:28.540,0:01:29.942
最后我们切点这个葱花

0:01:33.970,0:01:35.522
好 准备开始整

0:01:43.892,0:01:45.294
 首先我们把锅烧热

0:01:45.410,0:01:47.363
然后加入一大勺植物油滑锅

0:01:47.363,0:01:49.819
同学们煎蛋必须事先烧热油滑锅

0:01:49.989,0:01:51.677
不然煎蛋很容易粘锅

0:01:52.457,0:01:54.462
然后加入蛋液三分之一的油

0:01:54.963,0:01:57.308
油温烧热之后先用炒勺盛出一些

0:01:58.722,0:02:01.915
蛋液下锅之后再把烧热的油重新淋在蛋液上面

0:02:02.019,0:02:04.120
这样可以让蛋液双面受热均匀

0:02:04.680,0:02:06.612
然后转中火把鸡蛋煎香

0:02:06.685,0:02:08.472
中途再翻过来煎另外一面

0:02:10.897,0:02:13.977
鸡蛋煎香之后把切好的西红柿下锅翻炒几下

0:02:18.181,0:02:20.016
然后加入事先准备好的开水

0:02:20.121,0:02:22.659
同学们加开水烧汤更容易把汤烧白

0:02:24.834,0:02:26.976
大火烧开之后转中火烧3分钟

0:02:27.154,0:02:28.892
中途再撇去多余的浮沫

0:02:37.162,0:02:39.587
蛋汤烧白之后再加入适量的盐调味

0:02:42.724,0:02:44.624
最后撒上葱花即可出锅

0:02:50.574,0:02:51.657
来 我给你舀四伯爷

0:02:51.940,0:02:52.489
要的呀

0:02:53.290,0:02:55.020
舀点蛋汤 先喝点汤

0:02:55.505,0:02:56.087
要的

0:02:57.534,0:02:58.876
你吃番茄不

0:02:59.143,0:03:00.153
可以可以

0:03:00.153,0:03:01.631
来2片番茄

0:03:02.082,0:03:03.887
番茄咬得动

0:03:07.413,0:03:08.383
饭前先喝汤

0:03:09.210,0:03:10.849
这个番茄粉嘟嘟的噶

0:03:15.097,0:03:17.263
诶呀 刚烧起来的好烫哦

0:03:17.951,0:03:18.448
慢点嘛

0:03:18.448,0:03:18.516
肯定了四伯爷

0:03:18.516,0:03:19.898
肯定了四伯爷

0:03:20.721,0:03:21.361
你饿了呀

0:03:21.599,0:03:22.830
这个汤肯定有点烫

0:03:23.096,0:03:24.375
我先尝一下什么味道

0:03:25.308,0:03:25.750
好吃

0:03:27.560,0:03:29.078
这个蛋香味特别浓

0:03:29.384,0:03:32.307
我们这个鸡蛋煎的时候不要把它搅碎

0:03:32.561,0:03:34.956
就两边煎到它泡起来了之后

0:03:35.262,0:03:37.368
然后再放番茄下去炒一下再放水

0:03:37.762,0:03:39.370
如果你们家里面火小的话

0:03:39.370,0:03:40.839
可以事先准备好开水

0:03:44.554,0:03:45.917
这个汤很好喝噶

0:03:47.674,0:03:48.549
我们这个的话就是保持

0:03:48.549,0:03:49.335
这个汤很鲜

0:03:49.440,0:03:51.739
 你还没放味精都这么好喝

0:03:52.377,0:03:52.788
嗯

0:03:53.706,0:03:56.057
这个番茄我们就是保持里面的原汁原味

0:03:56.092,0:03:57.596
所以就可以切厚一些

0:03:59.029,0:03:59.484
可以

0:04:00.271,0:04:03.391
如果大家想吃那个番茄蛋花汤的话

0:04:04.318,0:04:05.603
就正好跟这个相反

0:04:06.276,0:04:07.508
切得越薄就越好

0:04:08.024,0:04:09.204
因为更容易熟透

0:04:09.571,0:04:11.118
然后就是用开水冲一下就可以了

0:04:15.629,0:04:16.879
好了 本期视频就到这里

0:04:17.071,0:04:19.886
你们要是对这个感兴趣的话可以尝（试）一下


```

**Comment by Kevinzheng5** [comment]
认领

**Comment by Kevinzheng5** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“番茄煎蛋汤”的四川家常做法，汤鲜味美很开胃，加一把面就是“番茄煎蛋面”
Chef Wang shares with you: Sichuan home style “Tomato and Fried Egg Soup”. Savory and appetizing. Adding noodles makes it “Tomato and Fried Egg Noodles”

简介
大家好，今天和大家分享一道简单美味的四川特色“番茄煎蛋汤”，提前将蛋煎好再加入开水吊汤，煮出来的汤浓白味鲜，个人觉得比番茄蛋花汤要好喝很多，并且真的很简单，只要掌握到小技巧可以轻松做出。如果朋友们没有喝过这样做的番茄蛋汤一定要试一试，保证好喝！最后上了一天班到家很累不想做饭的朋友可以把这道汤煮好后下一把挂面，一道美味的“番茄煎蛋面”就做好了，是不是超级简单，再也没有理由说劝退了，学起来！
Hello everyone, today I’ll share a simple Sichuan style “Tomato and Fried Egg Drop Soup”. We’ll stir fry the eggs first and then add water for the soup. That way the soup becomes thick and white with a savory taste. In my own opinion this soup is much better than the “Tomato and Egg Drop Soup” and it is plain simple. You’ll only need the basic culinary skills for it. If you haven’t had this soup before, you must have a try and it is good guaranteed! The soup fits really nice for a long day after work when you just don’t want to cook. Make the soup and have some noodles with it and you can enjoy the “Tomato and Fried Egg Noodles”. Isn’t that really easy? No more reasons to hesitate, come on! 

字幕
0:00:00.000,0:00:00.647
哈喽 大家好
Hello everyone

0:00:00.702,0:00:02.356
今天跟大家分享一个汤
Today I’ll share a soup with you

0:00:02.370,0:00:04.038
就是番茄泡蛋汤
Which is the “Tomato and Fried Egg Soup”

0:00:04.162,0:00:06.588
我们这边说的这个泡蛋汤
In our accent, it has a different name

0:00:06.629,0:00:07.842
其实就是煎蛋汤
But it’s the same thing

0:00:07.980,0:00:10.144
然后番茄蛋汤其实够简单的了
The regular “Tomato and Egg Drops Soup” is so simple

0:00:10.337,0:00:12.405
然后就是分享一些不一样的做法
So I’ll share a version with a twist to it

0:00:13.659,0:00:15.042
我们看这个番茄新不新鲜
Let’s see how fresh these tomatoes are 
0:00:15.042,0:00:16.007
就是看这个位置
By looking here

0:00:16.386,0:00:18.208
这个（蒂）还是绿色的
The vines are still green

0:00:20.856,0:00:22.083
我们切这个番茄的时候
When we are dicing the tomatoes

0:00:22.083,0:00:23.955
中间这个（蒂）最好是把它去掉
We better cut the vines off

0:00:24.311,0:00:25.364
先从中间切开
First cut it to half

0:00:26.178,0:00:29.097
然后左边一刀 右边一刀
Then slice from the left and right

0:00:29.415,0:00:30.323
这样子它就下来了
It’ll be off like this

0:00:31.208,0:00:32.490
我们切这个番茄
For the tomatoes today

0:00:32.947,0:00:34.183
这次我们切厚一点
Keep the slices a little thicker

0:00:34.462,0:00:37.097
切厚一点就是让它中间有足够的汁水
Thicker slices keep them juicy enough

0:00:37.676,0:00:38.852
待会儿煮了之后
Then during the boiling later

0:00:39.153,0:00:40.423
这个汁水就不会流出来
The juice won’t come out 

0:00:40.423,0:00:41.493
不会流失
It will be contained

0:00:41.565,0:00:43.337
吃的时候感觉饱满比较多汁
Then it will have a juicier taste and more solid texture

0:00:48.239,0:00:50.356
别看一个简简单单的一个番茄蛋汤
Even though it’s only a simple soup

0:00:50.473,0:00:52.457
这中间有很多的小技巧
It still has a lot of culinary tricks

0:00:53.732,0:00:54.668
然后我们来打鸡蛋
Then let’s mix the eggs

0:00:57.292,0:00:58.874
然后我们这个鸡蛋打的时候
When we are mixing the eggs

0:00:59.610,0:01:03.225
尽量的把这个鸡蛋给它蛋液挑起来
Try your best to raise the beat eggs up

0:01:03.392,0:01:04.305
让空气进去
To mix some air inside

0:01:04.612,0:01:06.351
这样子煎出来蛋才够嫩
Then the fried eggs will taste softer

0:01:08.270,0:01:09.563
把这个蛋液挑起来
Raise the beat eggs up like this

0:01:09.830,0:01:12.457
空气进去之后这个蛋液里面会有很多小气泡
When the air is mixed in, there will be many bubbles

0:01:14.009,0:01:15.726
我们一般在酒店里面做的话
The way we make this in restaurants

0:01:15.774,0:01:18.550
这个蛋液里面要加一点醋 提升它的鲜味
We’ll add some vinegar to make it more savory

0:01:18.904,0:01:19.755
然后再加一点盐
Then some salt

0:01:21.551,0:01:23.266
好 我们打好了蛋液你看
Alright, it’s done

0:01:23.348,0:01:24.491
非常多的小气泡
Lots of bubbles inside

0:01:24.818,0:01:27.274
这就说明蛋液打的比较成功
Success

0:01:28.540,0:01:29.942
最后我们切点这个葱花
Finally let’s chop some green onions

0:01:33.970,0:01:35.522
好 准备开始整
Alright, let’s make the soup

0:01:43.892,0:01:45.294
 首先我们把锅烧热
First we heat up the wok

0:01:45.410,0:01:47.363
然后加入一大勺植物油滑锅
Put a large spoon of vegetable oil in

0:01:47.363,0:01:49.819
同学们煎蛋必须事先烧热油滑锅
It’s necessary to heat up the oil and cover the wok with it

0:01:49.989,0:01:51.677
不然煎蛋很容易粘锅
Otherwise the eggs are very easy to stick

0:01:52.457,0:01:54.462
然后加入蛋液三分之一的油
Then add oil about one third the volume of the beat eggs 

0:01:54.963,0:01:57.308
油温烧热之后先用炒勺盛出一些
After the oil is heated, scoop some in the cooking spoon

0:01:58.722,0:02:01.915
蛋液下锅之后再把烧热的油重新淋在蛋液上面
Pour the beat eggs in and then pour the heated oil on the eggs

0:02:02.019,0:02:04.120
这样可以让蛋液双面受热均匀
So that the beat eggs are heated from both sides

0:02:04.680,0:02:06.612
然后转中火把鸡蛋煎香
Turn down the burner to medium

0:02:06.685,0:02:08.472
中途再翻过来煎另外一面
Flip to the other side in the middle

0:02:10.897,0:02:13.977
鸡蛋煎香之后把切好的西红柿下锅翻炒几下
After the eggs’ aroma comes off, pour in the tomatoes. Stir fry them

0:02:18.181,0:02:20.016
然后加入事先准备好的开水
Then pour in some boiling water

0:02:20.121,0:02:22.659
同学们加开水烧汤更容易把汤烧白
The boiling water makes the soup whiter

0:02:24.834,0:02:26.976
大火烧开之后转中火烧3分钟
Bring it to boil and turn the burner down to medium for 3 minutes

0:02:27.154,0:02:28.892
中途再撇去多余的浮沫
Get rid of the froth

0:02:37.162,0:02:39.587
蛋汤烧白之后再加入适量的盐调味
When the soup becomes white, season with salt

0:02:42.724,0:02:44.624
最后撒上葱花即可出锅
Sprinkle the chopped green onions and it’s done

0:02:50.574,0:02:51.657
来 我给你舀四伯爷
Uncle, let me get you some

0:02:51.940,0:02:52.489
要的呀
Alrighty

0:02:53.290,0:02:55.020
舀点蛋汤 先喝点汤
Get some soup first

0:02:55.505,0:02:56.087
要的
Alright

0:02:57.534,0:02:58.876
你吃番茄不
You want tomatoes?

0:02:59.143,0:03:00.153
可以可以
Sure

0:03:00.153,0:03:01.631
来2片番茄
A few slices of tomatoes

0:03:02.082,0:03:03.887
番茄咬得动
The tomatoes are pretty soft

0:03:07.413,0:03:08.383
饭前先喝汤
Have some soup before the meal

0:03:09.210,0:03:10.849
这个番茄粉嘟嘟的噶
The tomatoes look cute

0:03:15.097,0:03:17.263
诶呀 刚烧起来的好烫哦
Hot hot hot

0:03:17.951,0:03:18.448
慢点嘛
Slow down then

0:03:18.448,0:03:18.516
肯定了四伯爷
Of course uncle

0:03:18.516,0:03:19.898
肯定了四伯爷
Of course uncle

0:03:20.721,0:03:21.361
你饿了呀
You hungry, huh?

0:03:21.599,0:03:22.830
这个汤肯定有点烫
The soup must be pretty hot

0:03:23.096,0:03:24.375
我先尝一下什么味道
Let me taste

0:03:25.308,0:03:25.750
好吃
Nice

0:03:27.560,0:03:29.078
这个蛋香味特别浓
The aroma of the eggs is very strong

0:03:29.384,0:03:32.307
我们这个鸡蛋煎的时候不要把它搅碎
Don’t break the eggs during stir frying

0:03:32.561,0:03:34.956
就两边煎到它泡起来了之后
Just wait for both sides to get fluffy

0:03:35.262,0:03:37.368
然后再放番茄下去炒一下再放水
Stir fry with tomatoes and pour water in

0:03:37.762,0:03:39.370
如果你们家里面火小的话
If your burner is weak

0:03:39.370,0:03:40.839
可以事先准备好开水
Remember to boil the water before hand

0:03:44.554,0:03:45.917
这个汤很好喝噶
The soup is nice

0:03:47.674,0:03:48.549
我们这个的话就是保持
We are trying to keep…

0:03:48.549,0:03:49.335
这个汤很鲜
The soup is really savory

0:03:49.440,0:03:51.739
 你还没放味精都这么好喝
It’s so good even without monosodium glutamate

0:03:52.377,0:03:52.788
嗯
Yeah

0:03:53.706,0:03:56.057
这个番茄我们就是保持里面的原汁原味
We are trying to keep the original flavor of the tomatoes

0:03:56.092,0:03:57.596
所以就可以切厚一些
So keep the slices a little thicker

0:03:59.029,0:03:59.484
可以
Nice

0:04:00.271,0:04:03.391
如果大家想吃那个番茄蛋花汤的话
If you want the “Tomato Egg Drop Soup”

0:04:04.318,0:04:05.603
就正好跟这个相反
It will be exactly the opposite

0:04:06.276,0:04:07.508
切得越薄就越好
The thinner tomato slices, the better

0:04:08.024,0:04:09.204
因为更容易熟透
Because that way it’s easier to get cooked

0:04:09.571,0:04:11.118
然后就是用开水冲一下就可以了
Then add some water and bring to boil. It’s simply done

0:04:15.629,0:04:16.879
好了 本期视频就到这里
Alright, that’s it for this episode

0:04:17.071,0:04:19.886
你们要是对这个感兴趣的话可以尝（试）一下
Try on your own if you are interested!
