### ISSUE TITLE
【美食作家王刚】酱泡青椒 - https://youtu.be/VUS-MpDNdWg

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#899]
**视频链接**：https://youtu.be/VUS-MpDNdWg

视频时长 2:58，预计发布时间为北京时间4月12日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：川味开胃小菜“酱泡青椒”的家常做法，口感爽脆鲜辣开胃

简介
同学们好，今天和大家分享一道开胃小菜“酱泡青椒”，这样做出来的青椒口感爽脆并且鲜辣开胃，特别适合过粥下饭，属于经典的四川咸菜类别，并且不需要长时间腌制，基本属于现做现吃。大家也可以根据个人的喜欢来选用不同种类的辣椒青椒，本人最喜欢二荆条，清香味最为浓厚，喜欢吃更辣的朋友也可以加入小米辣。最后需要提醒大家此款酱汁因为有油所以不可以长时间保存或者重复使用多次，放入冰箱冷藏可以保鲜3天左右，期间可以重复使用。

本期菜品：【酱油泡青椒】
【主料】
大青椒（3个）
大红椒（1个）
二荆条（几个）
嫩仔姜（1大块）
大蒜（几颗）
小葱头（几根）
【辅料】
青花椒（适量）
生姜（适量）
八角（1颗）
纯净水（600克）
植物油（适量）
【调味料】
食用盐（约14克）
白糖（约30克）
保宁醋（25克）
生抽酱油（350克）
蚝油（25克）

字幕
0:00:00.320,0:00:01.560
哈喽大家好 我是王刚

0:00:01.560,0:00:03.460
本期视频我给大家分享一道家常菜

0:00:03.680,0:00:05.040
酱油泡青椒

0:00:05.340,0:00:07.580
首先我们准备大青椒3个

0:00:08.268,0:00:10.972
去掉辣椒蒂之后从中间横竖各切1刀

0:00:11.225,0:00:14.308
同学们为保证辣椒的完整性可以不用切断

0:00:14.845,0:00:16.600
准备大红椒1个同样处理

0:00:16.600,0:00:19.525
加大红椒除了增加成菜的甜味还能配色

0:00:19.920,0:00:22.608
最后准备几个二荆条从中间切开备用

0:00:22.719,0:00:24.584
不能吃辣的同学可以不加

0:00:24.964,0:00:27.351
准备嫩仔姜1大块切成姜片备用

0:00:29.486,0:00:31.604
准备大蒜几颗切成蒜片备用

0:00:33.944,0:00:36.837
最后准备几根小葱头拍散之后切成葱段备用

0:00:37.707,0:00:39.051
下一步开始腌制

0:00:39.256,0:00:40.980
盆中加入食用盐1大勺（约4克）

0:00:41.691,0:00:43.383
再加入1小把白糖（约30克）

0:00:44.996,0:00:47.193
然后搅拌均匀腌制2小时备用

0:00:47.304,0:00:50.071
这一步的目的是去除辣椒和辅料的生辣味

0:00:50.150,0:00:51.778
下一步开始准备料汁

0:00:52.015,0:00:53.802
碗中加入适量的青花椒

0:00:54.403,0:00:55.604
加入八角1颗

0:00:56.521,0:00:57.849
再准备一个大盆

0:00:58.086,0:01:00.063
盆中加入保宁醋25克

0:01:00.853,0:01:02.940
加入生抽酱油350克

0:01:04.727,0:01:06.482
加入纯净水600克

0:01:09.960,0:01:12.411
然后加入适量的食用盐搅拌均匀备用（约10克）

0:01:15.794,0:01:17.359
下一步开始熬汁

0:01:17.533,0:01:19.873
首先我们直接将调好的料汁下锅

0:01:21.422,0:01:23.430
然后开大火烧开之后倒出备用

0:01:23.478,0:01:25.470
这一步的目的是初步灭菌

0:01:28.031,0:01:30.909
大火烧开之后锅离火再加入蚝油25克

0:01:32.837,0:01:34.735
同学们蚝油可以不用加热

0:01:35.003,0:01:37.200
这样才能够保留蚝油的原始鲜味

0:01:37.501,0:01:39.588
将蚝油搅拌均匀之后倒出备用

0:01:45.391,0:01:47.225
然后我们再次把锅烧热

0:01:47.604,0:01:49.486
锅烧热之后加入少许的底油

0:01:50.656,0:01:53.217
油温5成热之后将准备好的香料下锅

0:01:54.592,0:01:56.205
然后转慢火炒香即可

0:02:02.656,0:02:05.897
同学们酱油必须冷却之后才能够浸泡青椒

0:02:07.747,0:02:10.814
2个小时之后将腌制好的辣椒攥干水份备用

0:02:13.944,0:02:17.375
然后将冷却的酱油搅拌均匀之后倒入装辣椒的盆中

0:02:20.664,0:02:23.462
最后再浸泡腌制4小时即可食用

0:02:25.422,0:02:28.648
一道非常美味爽口的酱油泡青椒就制作完成

0:02:34.800,0:02:57.080
下面开始技术总结
第一，辣椒的种类可以根据个人口味选择
第二，腌制辣椒可以少加盐多加糖，这样可以中和辣椒的辣味
第三，腌制好的辣椒可以不必清洗直接攥干水份即可
第四，此菜非常适合作为早餐下白粥
第五，剩余的酱油可以反复使用2次左右
酱油泡青椒的技术总结完毕


```

**Comment by Hackerry** [comment]
认领

**Comment by Hackerry** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：川味开胃小菜“酱泡青椒”的家常做法，口感爽脆鲜辣开胃
Chef Wang teaches you: Sichuan-style appetizing cold dish - Sauce pickled green chili peppers.

简介
同学们好，今天和大家分享一道开胃小菜“酱泡青椒”，这样做出来的青椒口感爽脆并且鲜辣开胃，特别适合过粥下饭，属于经典的四川咸菜类别，并且不需要长时间腌制，基本属于现做现吃。大家也可以根据个人的喜欢来选用不同种类的辣椒青椒，本人最喜欢二荆条，清香味最为浓厚，喜欢吃更辣的朋友也可以加入小米辣。最后需要提醒大家此款酱汁因为有油所以不可以长时间保存或者重复使用多次，放入冰箱冷藏可以保鲜3天左右，期间可以重复使用。
Hi friends, today I want to share with you an appetizer, Sauce pickled green chili peppers. The processed peppers are crisp, spicy and very appetizing. Very suitable as a side dish for porridge and rice. It's one of many popular pickled dish in Sichuan and can be readily made before eating. You can also use your favorite type of pepper. I choose my favorite "Erjingtiao" chili pepper because it has the rich smell of freshness. You can add "Xiaomila" chili pepper if you like a more spicy dish. Finally I want to remind you that this sauce is prepared with cooking oil and therefore it can't be stored for very long or reused many times. It is only reusable within about 3 days if stored in the fridge.

本期菜品：【酱油泡青椒】
【主料】
大青椒（3个）
大红椒（1个）
二荆条（几个）
嫩仔姜（1大块）
大蒜（几颗）
小葱头（几根）
【辅料】
青花椒（适量）
生姜（适量）
八角（1颗）
纯净水（600克）
植物油（适量）
【调味料】
食用盐（约14克）
白糖（约30克）
保宁醋（25克）
生抽酱油（350克）
蚝油（25克）
Today's dish: Sauce pickled green chili peppers
Main Ingredients
3 Green chili peppers
1 Red chili pepper
Several "Erjingtiao" chili pepper
1 piece of young ginger
Several cloves of garlic
Several green onion roots

Other Ingredients
Some Sichuan green peppercorn
Some ginger
1 piece of star anise
600g pure water
Some vegetable oil

Seasoning Ingredients
About 14g of salt
About 30g of white sugar
About 25g of "Baoning" vinegar
350g of soy sauce
25g of eel sauce

字幕
0:00:00.320,0:00:01.560
哈喽大家好 我是王刚
Hello everyone, I'm Wang Gang.

0:00:01.560,0:00:03.460
本期视频我给大家分享一道家常菜
In today's video I'll share with you a homemade dish.

0:00:03.680,0:00:05.040
酱油泡青椒
Sauce pickled green chili peppers.

0:00:05.340,0:00:07.580
首先我们准备大青椒3个
First we prepare 3 green chili peppers.

0:00:08.268,0:00:10.972
去掉辣椒蒂之后从中间横竖各切1刀
Remove the stalk and cut twice into the pepper like a cross.

0:00:11.225,0:00:14.308
同学们为保证辣椒的完整性可以不用切断
You can leave the end connected to keep the nice shape of a pepper.

0:00:14.845,0:00:16.600
准备大红椒1个同样处理
Do the same for the one red pepper.

0:00:16.600,0:00:19.525
加大红椒除了增加成菜的甜味还能配色
Adding the red pepper is to bring some sweetness and color to the dish.

0:00:19.920,0:00:22.608
最后准备几个二荆条从中间切开备用
Finally have some "Erjingtiao" chili pepper cut from the middle.

0:00:22.719,0:00:24.584
不能吃辣的同学可以不加
You can skip it if you can't eat spicy food.

0:00:24.964,0:00:27.351
准备嫩仔姜1大块切成姜片备用
Slice a large chunk of young ginger into pieces.

0:00:29.486,0:00:31.604
准备大蒜几颗切成蒜片备用
And cut some cloves of garlic into pieces.

0:00:33.944,0:00:36.837
最后准备几根小葱头拍散之后切成葱段备用
Finally have some green onion root crushed and cut into smaller cylindrical pieces.

0:00:37.707,0:00:39.051
下一步开始腌制
Next to marinate the peppers,

0:00:39.256,0:00:40.980
盆中加入食用盐1大勺（约4克）
add 1 spoonful of salt (about 4g),

0:00:41.691,0:00:43.383
再加入1小把白糖（约30克）
and a small handful of white sugar (about 30g).

0:00:44.996,0:00:47.193
然后搅拌均匀腌制2小时备用
Then mix well and marinate for 2 hours.

0:00:47.304,0:00:50.071
这一步的目的是去除辣椒和辅料的生辣味
This step is to remove the strong spiciness from the peppers and other ingredients.

0:00:50.150,0:00:51.778
下一步开始准备料汁
Next we prepare the sauce.

0:00:52.015,0:00:53.802
碗中加入适量的青花椒
Add some Sichuan green peppercorn to a bowl,

0:00:54.403,0:00:55.604
加入八角1颗
and 1 piece of star anise.

0:00:56.521,0:00:57.849
再准备一个大盆
Then get a large bowl.

0:00:58.086,0:01:00.063
盆中加入保宁醋25克
Add 25g of "Baoning" vinegar in it.

0:01:00.853,0:01:02.940
加入生抽酱油350克
And 350g of soy sauce.

0:01:04.727,0:01:06.482
加入纯净水600克
Pour in 600g of pure water.

0:01:09.960,0:01:12.411
然后加入适量的食用盐搅拌均匀备用（约10克）
Then add some salt (about 10g) and mix well.

0:01:15.794,0:01:17.359
下一步开始熬汁
Next up to simmer the sauce.

0:01:17.533,0:01:19.873
首先我们直接将调好的料汁下锅
First we pour the prepared sauce into the wok.

0:01:21.422,0:01:23.430
然后开大火烧开之后倒出备用
Bring up the high heat and pour out the sauce once it boils.

0:01:23.478,0:01:25.470
这一步的目的是初步灭菌
This step is to pasteurize the sauce.

0:01:28.031,0:01:30.909
大火烧开之后锅离火再加入蚝油25克
When it comes to a boil, remove from heat and add 25g of eel sauce.

0:01:32.837,0:01:34.735
同学们蚝油可以不用加热
We don't need to heat the eel sauce.

0:01:35.003,0:01:37.200
这样才能够保留蚝油的原始鲜味
Because we want to keep the original umami taste in it.

0:01:37.501,0:01:39.588
将蚝油搅拌均匀之后倒出备用
After mixing the eel sauce well, transfer the sauce to a bowl for later use.

0:01:45.391,0:01:47.225
然后我们再次把锅烧热
Now we heat up the wok again.

0:01:47.604,0:01:49.486
锅烧热之后加入少许的底油
Then we add a little bit of base oil.

0:01:50.656,0:01:53.217
油温5成热之后将准备好的香料下锅
Add the spices when the temperature is about 150 °C.

0:01:54.592,0:01:56.205
然后转慢火炒香即可
Then turn to low heat and wait until you smell the aroma.

0:02:02.656,0:02:05.897
同学们酱油必须冷却之后才能够浸泡青椒
We must wait until the sauce is completely cooled down before soaking the peppers.

0:02:07.747,0:02:10.814
2个小时之后将腌制好的辣椒攥干水份备用
Two hours later dry the peppers by gripping on your hand.

0:02:13.944,0:02:17.375
然后将冷却的酱油搅拌均匀之后倒入装辣椒的盆中
Then pour the cooled sauce into the bowl containing peppers.

0:02:20.664,0:02:23.462
最后再浸泡腌制4小时即可食用
Finally pickle for 4 hours and the dish is ready.

0:02:25.422,0:02:28.648
一道非常美味爽口的酱油泡青椒就制作完成
A dish of very delicious and crisp soy sauce pickled green chili peppers is finished.

0:02:34.800,0:02:57.080
下面开始技术总结
第一，辣椒的种类可以根据个人口味选择
第二，腌制辣椒可以少加盐多加糖，这样可以中和辣椒的辣味
第三，腌制好的辣椒可以不必清洗直接攥干水份即可
第四，此菜非常适合作为早餐下白粥
第五，剩余的酱油可以反复使用2次左右
酱油泡青椒的技术总结完毕
Now the technical tips:
First, you can choose peppers according to you favor.
Second, peppers' spicy flavor can be neutralized by adding more sugar and less salt during the marination process.
Third, it's not necessary to wash the peppers after marination. Hand-drying is enough.
Fourth, this appetizer is an ideal side dish for eating rice porridge at breakfast.
Fifth, the remaining soy sauce can be reused about two more times.
That's all for the tips.
