### ISSUE TITLE
[老饭骨] 蒸鸡翅 - https://www.youtube.com/watch?v=sF7-Gj08AB4

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#909]
**视频链接**：https://www.youtube.com/watch?v=sF7-Gj08AB4

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•蒸鸡翅】人人都能学会的豆豉辣味蒸鸡翅，快手下饭菜，简单又好吃

简介
小友们好，前两天教了大家伙儿一个烤鸡翅，今儿咱再来做一个蒸鸡翅。
豆豉的香味配上郫县豆瓣酱的一点点辣味，最重要的是要把鸡翅腌入味，
这样蒸出来的鸡翅真是好吃得根本停不下来！
这蒸鸡翅也是走的家常路线，简单易学又好吃，必须在家自个儿操练起来！
ps: 这期视频也是之前的存货，希望大爷二伯三叔可以再次聚在一起做饭、唠嗑、品尝美食的那天快点到来。

字幕
旧视频没有官方中文字幕，需自制时间轴和对照中文
```

**Comment by Koi111** [comment]
认领

**Comment by Koi111** [comment]
#标题（翻译主要意思即可，不要超过 100 个字符）
#【国宴大师•蒸鸡翅】人人都能学会的豆豉辣味蒸鸡翅，快手下饭菜，简单又好吃
#State Banquet Master Chef•Steamed Chicken Wings, spicy dish with Douchi, easy and yummy

#简介
#小友们好，前两天教了大家伙儿一个烤鸡翅，今儿咱再来做一个蒸鸡翅。
Hey friends, we just taught you a recipe for roasted chicken wings few days ago, today we are making steamed chicken wings. 
#豆豉的香味配上郫县豆瓣酱的一点点辣味，最重要的是要把鸡翅腌入味，
The wonderful aroma of "Douchi" fermented soybeans and the spiciness of Doubanjiang, the most important thing is to marinate the chicken until the flavour penetrates.
#这样蒸出来的鸡翅真是好吃得根本停不下来！
The chicken wings are so good that you cannot stop eating!
#这蒸鸡翅也是走的家常路线，简单易学又好吃，必须在家自个儿操练起来！
This dish is very family-friendly, easy to learn and very tasty, you have to try this at home.
#ps: 这期视频也是之前的存货，希望大爷二伯三叔可以再次聚在一起做饭、唠嗑、品尝美食的那天快点到来。
ps: This episode is also one of our backups, we sincerely hope that Da Ye, Er Bai and San Shu can cook meals, chit-chat and enjoy delicacies together as soon as possible.


0:00:00.140,0:00:02.240
#今天给大家做一个什么呢
What are we making today?

0:00:02.240,0:00:05.220
#做一个豆豉辣味鸡翅
A spicy chicken wings with Douchi

0:00:05.220,0:00:06.380
#辣味鸡翅
Spicy chicken wings

0:00:06.380,0:00:07.400
#蒸的
A steamed dish

0:00:07.400,0:00:09.040
#实际上这鸡翅
Actually cooking chicken wings
 
0:00:09.040,0:00:11.200
#单独用鸡翅来做菜
cooking chicken wings only

0:00:11.200,0:00:13.240
#这个时间不会很长
It won't take too much time

0:00:13.240,0:00:16.280
#因为什么过去我们很少有
Because in the past we don't have much resources

0:00:16.280,0:00:17.480
#专门卖鸡翅的
A place that sells chicken wings only

0:00:17.480,0:00:19.520
#一个鸡就俩鸡翅
There is only one pair of chicken wings froma chicken

0:00:19.520,0:00:22.520
#把这鸡翅剞剞花刀
Make a few cuts on the meat

0:00:22.520,0:00:23.940
#已经改好刀了
I'm done making the cuts

0:00:23.940,0:00:28.460
#我们稍微少搁点盐
We should put just a little bit of salt

0:00:28.520,0:00:31.180
#因为我一会还要拌料
Because I need to mix it with other ingredients too

0:00:31.180,0:00:32.500
#所以这盐不能太多
Hence the salt cannot be too much

0:00:32.680,0:00:35.020
#搁点酒
Put a little bit of cooking wine

0:00:35.360,0:00:36.160
#多搁点
Put a little bit more

0:00:36.160,0:00:37.680
#别太多了 还有呢
Don't put too much of it, we have other seasonings too

0:00:37.800,0:00:38.660
#还有别的菜呢
We still have other ingredients

0:00:38.660,0:00:39.860
#您搁点白酒么
Do you want some baijiu

0:00:39.860,0:00:40.600
#别搁白酒
Don't put Baijiu

0:00:40.600,0:00:43.280
#有的白酒 尤其那曲酒
Some Baijiu liquor, especially Qujiu (a type of Baijiu)

0:00:43.280,0:00:46.340
#搁错了以后它臭
If you put the wrong type, the dish would have an unpleasant smell

0:00:46.340,0:00:47.020
#这二锅头没事
Erguotou is okay

0:00:47.040,0:00:48.800
#二锅头行 清香型的
Erguotou liquor has a delicate fragrance

0:00:48.800,0:00:50.760
#这稍微给它腌一会儿
Marinade the chicken wings for a while

0:00:51.040,0:00:52.700
#腌一会儿 很简单
Just a while, it would be easy

0:00:52.700,0:00:53.660
#搁点葱姜么
Do you want to put some spring onions and ginger into it?

0:00:53.660,0:00:54.560
#葱姜也不要
Nope

0:00:54.580,0:00:56.980
#待会我这炒料里边有葱姜
I will stir-fry some spring onions and ginger later on

0:00:56.980,0:00:59.900
#切点小料
Mince some spring onions,ginger and garlic

0:01:03.420,0:01:04.700
#炒一汁儿
Let's make a sauce 

0:01:04.700,0:01:07.660
#锅里放点油
Put a little bit of oil into the wok

0:01:07.860,0:01:11.340
#先把这个豆豉给炒炒
Stir-fry the Douchi first

0:01:11.680,0:01:13.280
#郫县豆瓣酱
Some Doubanjiang from Pidu District,Chengdu

0:01:13.480,0:01:15.120
#这个不能太辣
The sauce cannot be too spicy

0:01:16.100,0:01:17.640
#弄点牛肉末麻婆豆腐出来了
Add some minced beef and this would be Mapo Tofu

0:01:17.660,0:01:20.060
#小火慢炒烹酱油
Cook the light soy sauce with low heat

0:01:22.280,0:01:23.500
#来点老抽也行
You can add some dark soy sauce too

0:01:23.500,0:01:25.180
#红烧酱油颜色深没问题
With Hong Shao dishes, it's ok to have a darker-coloured sauce

0:01:25.180,0:01:27.460
#你看红烧这颜色就起来了
Look， the colour is showing

0:01:27.680,0:01:29.620
#少来一点点水啊
Put a little bit of water

0:01:29.620,0:01:31.900
#您再来点水淀粉不就行了么
You can add some slurry, isn't it?

0:01:32.160,0:01:33.300
#不要 我就要点水
Nope, I just want some water

0:01:33.300,0:01:35.100
#要点水得熬点味
We need the water to cook and enhance the flavour

0:01:35.100,0:01:36.160
#就不听二伯的
Just don't listen to Er Bai

0:01:37.080,0:01:38.660
#得啦
Done

0:01:39.000,0:01:43.420
#因为有豆瓣酱 它肯定咸
The sauce is kind of salty because of the Doubanjiang

0:01:43.420,0:01:45.800
#咸它有点苦涩味
The saltiness might bring some bitterness

0:01:46.340,0:01:48.580
#搁点糖它就融合了
Put some sugar and it would smooth the bitterness out

0:01:48.940,0:01:50.460
#搁点糖
Add a little bit of sugar

0:01:50.920,0:01:52.380
#这个呢要加点淀粉
We need to add some starch into the wings

0:01:52.640,0:01:54.740
#你看见没有加上淀粉它就滑啦
Look, the chicken wings have became smooth and glossy

0:01:54.940,0:01:56.760
#起嫩 起滑
The meat would be tender 

0:01:57.220,0:01:58.860
#拌点淀粉
Mix some starch into it

0:01:58.940,0:02:02.120
#这就完活啦 看看这劲
Look at this, it's done!

0:02:02.360,0:02:04.360
#你这一蒸就完了
You left the last step only which is to steam it

0:02:05.040,0:02:07.060
#你弄的我们俩的菜都是复杂的
Our dishes are much more complex compared to yours

0:02:07.060,0:02:09.180
#是啊 到你这简单啊
Yeah! Your dish is simpler

0:02:09.400,0:02:11.080
#简单当中不简单啊
There are always some knowledge in simple things

0:02:11.160,0:02:13.200
#这要让网友看着简单
We have to let the audiences to learn some easy dishes

0:02:13.500,0:02:15.900
#老抽
Dark soy sauce

0:02:16.160,0:02:18.160
#您这还得拌点香油呢吧
You have to mix some sesame oil too

0:02:18.600,0:02:19.580
#要的
Yep

0:02:19.660,0:02:21.520
#拿香油封面
Use some sesame oil to seal the flavour

0:02:21.780,0:02:22.880
#再来点
A little bit more

0:02:22.880,0:02:24.340
#别介别介一会油太大了
That's enough, or else it would be too oily

0:02:24.500,0:02:26.040
#腌上十五分钟
Marinate it for 15 minutes

0:02:26.180,0:02:26.680
#锅开啦
The water in the pot is boiling

0:02:26.800,0:02:27.540
#下锅
Put it in

0:02:27.540,0:02:29.660
#一个是豆豉单一的口感
If you have the flavour of Douchi only

0:02:29.680,0:02:31.080
#叫豉香排骨
it can be Douchi pork ribs

0:02:31.080,0:02:32.580
#当我搁点郫县豆瓣酱呢
What if I add some Doubanjiang?

0:02:32.820,0:02:34.280
#豆豉辣排骨
Spicy Douchi pork ribs

0:02:34.360,0:02:36.060
#我们用什么样的辣椒都可以
We can use whatever chillies we want

0:02:36.060,0:02:37.680
#那我要是搁点泡辣椒呢
What if I add some pickled chillies?

0:02:37.680,0:02:39.140
#豆豉泡椒排骨
Douchi and pickled chillies pork ribs

0:02:39.280,0:02:41.740
#关键是把鸡翅腌好了入味
The key is to marinate the chicken wings until the flavour penetrates

0:02:41.740,0:02:44.660
#爱吃烂糊的蒸一小时
If you prefer really tender meat, steam it for an hour

0:02:44.660,0:02:46.620
#因为这鸡翅很快就烂了
Because the chicken wings can get overcooked and mushy easily

0:02:46.620,0:02:48.600
#爱吃硬一点的蒸四十分钟
If you prefer the meaty texture, steam it for 40 minutes

0:02:48.740,0:02:50.340
#就啃着吃
Just bite it and enjoy the meat

0:02:50.340,0:02:51.540
#吃起来就方便
It would be a convenient dish

0:02:51.540,0:02:53.380
#其实家常菜就是下饭菜
Actually home-style dishes are appetizing dishes

0:02:53.380,0:02:54.460
#对就是下饭菜
Yeah, they're appetizing and make you wanna eat some more rice

0:02:54.460,0:02:55.620
#这就是下饭菜啊
This is a dish that goes extremely well with rice

0:02:55.620,0:02:58.860
#吃得香 吃得多 吃的猛
You can eat a lot of it and really enjoy the flavour

0:02:58.860,0:02:59.400
#就是好吃
That's what we called "delicious"

0:02:59.400,0:03:00.840
#吃的舒服
The food comforts you

0:03:00.840,0:03:02.360
#吃的还健康呢
And it is a healthy dish too

0:03:02.360,0:03:03.800
#开锅吧 一小时了
Let's opne the lid, it's been an hour

0:03:03.800,0:03:05.280
#到点啦
It's time

0:03:05.280,0:03:06.540
#你们要不提醒啊
If you guys did not remind me about this,

0:03:06.540,0:03:08.200
#我还真的差点把这茬给忘了
I almost forgotten it

0:03:08.200,0:03:08.820
#看见没有
Can you see that

0:03:08.860,0:03:10.460
#你中间怎么偷偷换了一盘啊
Why did you change another plate in the middle?

0:03:10.460,0:03:13.300
#不是 刚才那个碗小 太多
Nah, the bowl was too small and it's overflowing

0:03:15.320,0:03:19.100
#嘿 王奶奶和玉奶奶就差这点儿 
Hey! The little things make a big difference!

0:03:19.100,0:03:21.040
#对 就差这一点儿
Yeah, the details matter

0:03:22.100,0:03:24.780
#滑 不错
Smooth, not bad

0:03:24.940,0:03:28.660
#三叔你吃一下
Try it, San Shu

0:03:29.580,0:03:31.400
#吃的味道怎么样
How is the taste?

0:03:31.400,0:03:32.860
#太好吃了
It's very yummy!

0:03:32.860,0:03:34.560
#突出了豆豉的香气
You can smell the aroma of the Douchi

0:03:34.560,0:03:37.320
#辣的正合适
and the level spiciness is just perfect

0:03:37.320,0:03:38.560
#这叫什么
What is this called?

0:03:38.560,0:03:41.820
#有辣 不过于辣
There is a hint of spiciness, but it's not overpowering the dish

0:03:42.020,0:03:43.960
#辣而不燥
Spicy but not to over

#0:03:44.180,0:03:45.600
好吃好吃
Awesome flavour

0:03:45.600,0:03:48.800
#一嘬就下来
The meat comes down easily with just a bit

0:03:48.800,0:03:51.960
#很香很香
Very aromatic

0:03:52.200,0:03:53.800
#真的很香
It's truly aromatic

# import ending.srt 00:04:03.660 稿件内请原样保留此行
