### ISSUE TITLE
[华农兄弟] 华农兄弟砍根竹子做个捞网去水塘里捞一下鱼 - https://youtu.be/_gHrpVYbVG0

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#910]
https://youtu.be/_gHrpVYbVG0
<p>&#35270;&#39057;&#21457;&#24067;&#20110; April 11, 2020 at 11:36AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bog, please upload
#https://youtu.be/_gHrpVYbVG0

#华农兄弟：砍根竹子，做个捞网，去水塘里捞一下鱼
#Huanong Brothers: Get a bamboo, make a fishing net, and catch some fish at the pond.

0:00:00.000,0:00:03.020
# 大家好  最近十天半個月都在下雨  (註︰他這奇怪的句子已不是第一次出現)
Hi everyone! It has been raining for half a month in the previous ten days.

0:00:03.840,0:00:05.940
# 天天都在下雨  剛好今天出太陽啊
It rains every day. But just today, it's sunny.

0:00:06.540,0:00:08.700
# 河裡的那個水呀  都已經發水啦
The water in the river is, it's already overflowing.

0:00:08.900,0:00:09.940
# 就等於漲水了哇
I mean, the river filled with water now.

0:00:10.180,0:00:11.280
# 好多魚在雨面
And there are a lot of fish under the water.

0:00:12.300,0:00:13.160
# 我買了一個這個
I've bought this one.

0:00:13.360,0:00:14.040
# 去山上
We go onto the hill,

0:00:14.400,0:00:16.640
# 搞一根竹子  把它做一個撈網出來
to get a bamboo. And then we can make a fishing net.

0:00:17.500,0:00:18.060
# 到時候
Then,

0:00:18.500,0:00:19.800
# 去河邊抓魚
we can go fishing on the riverside.

0:00:21.280,0:00:23.720
# 要上  要上山上砍一根竹子回來
I need to, I need to get a bamboo from the hill.

0:00:33.020,0:00:35.000
# 你看  今年長了好多竹笋啊
Look! There are a lot of bamboo shoots this year.

0:00:35.580,0:00:37.180
# 我把那竹子砍了時候差不多啦  (註︰我中文不好，不明白)
When I was chopping the bamboos, it's like, almost...

0:00:37.180,0:00:38.460
# 現在又長那麼多出來
And now many are coming out again.

0:00:39.480,0:00:41.580
# 呃  到了那個秋天的時候就是一片
Eh, when, you know, the autumn comes, it will be,

0:00:42.060,0:00:42.780
# 又是一片
it will again be,

0:00:43.180,0:00:44.160
# 漂亮的竹林
a pretty bamboo forest.

0:00:53.920,0:00:54.580
# 你看
Look!

0:00:55.500,0:00:56.600
# 這個竹笋大吧
It's a huge bamboo shoot, isn't it?

0:00:56.900,0:00:57.820
# 夠大啊  這個
It's really huge.

0:00:59.700,0:01:02.540
# 那麼大  長大了就是那麼大的竹子
It's so big. It will be as big as this when it grows up into a bamboo.

0:01:02.540,0:01:03.280
# 很快的
It won't take long.

0:01:04.040,0:01:06.440
# 等於說  再過一個月半個月
It's like, after, after a month, or a fortnight,

0:01:06.740,0:01:08.180
# 一  再過半個月左右
a, after around a fortnight,

0:01:08.500,0:01:09.860
# 這又可以長到很高啦
it will already be really tall.

0:01:14.100,0:01:15.640
# 這根竹子太丑啦
This bamboo is too ugly.

0:01:17.200,0:01:18.040
# 長歪啦
It's not really straight.

0:01:38.580,0:01:40.240
# 我回去  回去劈
I'll take it back, and break it there.

0:01:40.760,0:01:42.140
# 這裡沒有硬的東西
I can't find anything hard here.

0:01:42.740,0:01:43.420
# 要那個
I want some kind of,

0:01:43.920,0:01:44.800
# 硬的(是)[SIC]石頭
hard rock,

0:01:46.420,0:01:47.720
# 或者水泥之類
or something like concrete.

0:01:48.440,0:01:49.240
# 就好劈
It would be much easier.

0:02:09.260,0:02:10.900
# 不扎起來它是喜歡動
I need to tie it up here or it's always moving.

0:02:12.900,0:02:14.620
# 你看  這個圈子就出來啦
Look! A ring is formed.

0:02:35.760,0:02:37.120
# 你看  這個撈網做好啦
Look! The fishing net is done.

0:02:37.580,0:02:38.660
# 等明天我拿去
Let me give it a try tomorrow,

0:02:38.980,0:02:39.860
# 河邊試一下
on the riverside.

0:02:40.600,0:02:41.620
# 看一下效果怎麼樣
Let's see if it works well.

0:02:42.780,0:02:43.660
# 應該很不錯
It should be pretty good.

0:02:45.040,0:02:46.780
# 大魚小魚通通不放過
I'm not going to forgo any fish, neither the big ones nor the small ones,

0:02:47.200,0:02:48.640
# 連蝦米都可以撈得起來
not even the smallest shrimps.

0:02:52.800,0:02:54.880
# 昨天做的這個撈網  我來試一下
This is the fishing net that I made yesterday. Let me give it a try,

0:02:55.520,0:02:56.440
# 看撈不撈得到魚
and see if I can catch any fish.

0:03:01.180,0:03:02.300
# 一條都撈不到
Not even one.

0:03:03.380,0:03:05.400
# 哇  一個個  這兩隻
Wa! One by one, these two,

0:03:06.100,0:03:07.320
# 這兩隻鴨子哦
These two are ducks.

0:03:17.440,0:03:18.860
# 跑啦  不知道誰家的
They run away. Whose ducks are they?

0:03:24.660,0:03:26.440
# 撈不到的  鴨子也撈不到
No, I couldn't catch anything, neither ducks,

0:03:26.860,0:03:27.520
# 魚也撈不到
nor fish.

0:03:27.940,0:03:29.340
# 幸好我帶了這個抽水機
Fortunately, my water pump is with me today.

0:03:30.680,0:03:31.340
# 開工開工
Let's start, let's start!

0:03:31.920,0:03:33.100
# 先把這個火打著
Let me start the engine first.

0:04:06.500,0:04:07.860
# 你看  這水都乾啦
Look! The water has been drained.

0:04:08.320,0:04:09.680
# 還有一點點水  放不乾的
There's still a tiny little bit of water. It can't be completely drained.

0:04:10.280,0:04:10.980
# 撈一下
So let me try.

0:04:15.120,0:04:16.100
# 哎喲  這裡有一條
Ayo! Here's one!

0:04:18.060,0:04:18.660
# 不是很大
It's not too big.

0:04:19.420,0:04:19.920
# 哎喲
Ayo!

0:04:20.540,0:04:21.240
# 刺人的
It stings!

0:04:22.640,0:04:23.700
# 這是鯰魚來的
It's a catfish.

0:04:25.760,0:04:26.300
# 你看
Look!

0:04:32.400,0:04:33.220
# 水深啊
It's so deep.

0:04:35.940,0:04:37.260
# 有竹子要不要
Do you want a bamboo?

0:04:39.000,0:04:39.820
# 踩著來
You can step on it.

0:04:40.460,0:04:41.540
# 拿來來
Yea, give me a bamboo.

0:04:46.760,0:04:47.800
# 這樣放嗎
Shall I drop it here?

0:04:47.800,0:04:48.300
# 嗯
Yup!

0:04:57.220,0:04:58.120
# 一條都沒有
Not even one.

0:05:08.840,0:05:10.340
# 那麼多小蝦米
There are so many small shrimps.

0:05:11.660,0:05:12.840
# 你看  這個滲水
Look! The water is seeping in.

0:05:13.240,0:05:14.200
# 抽都抽不乾的
There's no way to drain out all the water.

0:05:15.120,0:05:16.080
# 搞了半天
We've spent half a day draining out the water, look!

0:05:16.480,0:05:17.640
# 沒兩分鐘又滿啦
But now the pond is filled up again in just a couple of minutes.

0:05:18.780,0:05:19.640
# 鯰魚  你看
Catfish, look!

0:05:20.220,0:05:21.420
# 抓了一條鯰魚  你看
I've caught a catfish, look!

0:05:21.960,0:05:22.980
# 它大肚子的
It's pregnant.

0:05:23.420,0:05:24.500
# 把它放回去算啦
Let's just release it.

0:05:25.040,0:05:25.800
# 你自由啦
You're a freedfish now.

0:05:26.560,0:05:27.640
# 碰到我運氣好
Your luck brings you to me.

0:05:28.400,0:05:30.000
# 要不是看到你大肚子的份上
It's solely because of your pregnancy,

0:05:30.640,0:05:31.880
# 我就回去把你給煮啦
that I decide not to have you cooked.

0:05:32.960,0:05:33.740
# 誒  回去
Eh! Go home!

0:05:34.400,0:05:35.160
# 找你老媽
Reunion with you mom!

0:05:38.380,0:05:39.400
# 還有這石斑魚
And this is a freshwater grouper.

0:05:41.800,0:05:43.380
# 王斑魚看著太小啦
But it looks too small.

0:05:43.500,0:05:44.380
# 魚是小魚
Are all small fish.

0:05:45.540,0:05:46.240
# 算啦  算啦
Forget it, forget it.

0:05:46.580,0:05:47.440
# 把它放回去
Let me release them.

0:05:48.340,0:05:49.480
# 你看  這個是 這個是
Look! It's a, it's a...

0:05:50.100,0:05:52.060
# 這不知道甚麼魚  想鯇魚一樣的
No idea. I think it's something like a grass carp.

0:05:53.600,0:05:54.780
# 走吧  還有一條泥鰍
Go! And this is a loach.

0:05:56.100,0:05:57.060
# 泥鰍也放掉它去
Well, release it too.

0:05:58.260,0:06:00.040
# 全部放回去  全部放回去  不要啦
Release them, release them, all of them.

0:06:02.100,0:06:03.420
# 我看到幾條大魚在這裡
I saw a couple of big fish over there.

0:06:03.540,0:06:04.200
# 沒抓到
But I couldn't catch them.

0:06:05.600,0:06:06.940
# 滲水滲得太快啦
The water is seeping in too quickly.

0:06:11.440,0:06:12.540
# 好啦  回去啦
Alright! Let's go back.

0:06:13.300,0:06:13.900
# 不要啦
I give up.

0:06:14.100,0:06:15.020
# 下次我來釣
I'll come again with the fishing rod next time.
