### ISSUE TITLE
【美食作家王刚】烧椒皮蛋 - https://youtu.be/aK3ZTZG4KK0

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#914]
**视频链接**：https://youtu.be/aK3ZTZG4KK0

视频时长 3:43，预计发布时间为北京时间4月15日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：川味凉菜“烧椒皮蛋”的家常做法，香辣回味，流连忘返！

简介
同学们好，今天给大家分享一道川味凉菜“烧椒皮蛋”，顾名思义此菜主要用到的就是皮蛋和烧焦过的辣椒，两种食材经过特制的酱汁完美的融合，不仅突出了皮蛋的香还有着特别香辣的回味，能吃辣的朋友一定要尝试，保证流连忘返！主要特别注意的是皮蛋最好选用四川黄心皮蛋，再有在烧辣椒的时候需注意火候的控制，以免彻底烧焦。

本期菜品：【烧椒皮蛋】
【主料】
黄心皮蛋（几个）
【辅料】
小米辣（几个）
二荆条（几个）
大蒜（几颗）
小葱头（几根）
香辣红油（适量）
【调味料】
食用盐（小半勺）
白糖（小半勺）
香醋（3克）
生抽酱油（10克）
香油（少许）

字幕
0:00:00.000,0:00:01.140
哈喽大家好 我是王刚

0:00:01.140,0:00:03.140
本期视频我给大家分享一道家常菜

0:00:03.540,0:00:04.740
烧椒皮蛋

0:00:04.900,0:00:07.074
首先我们准备几个黄心皮蛋

0:00:07.074,0:00:09.731
敲掉表皮的石灰之后再剥掉蛋壳备用

0:00:13.880,0:00:16.223
同学们皮蛋可以放入清水中剥离

0:00:16.223,0:00:18.042
这样可以防止（将）皮蛋剥烂

0:00:21.144,0:00:23.349
蛋壳剥完之后再清洗干净备用

0:00:27.043,0:00:28.890
然后将皮蛋一切为四

0:00:29.179,0:00:30.774
皮蛋也可以多切几块

0:00:31.098,0:00:32.809
这样摆盘份量显得更多

0:00:37.861,0:00:40.034
皮蛋切好之后下一步准备摆盘

0:00:40.034,0:00:41.539
首先我们准备圆盘1个

0:00:41.539,0:00:44.959
然后将切好的皮蛋蛋黄朝下均匀地摆入盘中

0:00:52.924,0:00:55.283
皮蛋摆好之后下一步开始准备辅料

0:00:55.445,0:00:58.115
准备几个小米辣和二荆条穿入竹签备用

0:00:58.242,0:01:00.208
同学们竹签必须事先泡水

0:01:00.289,0:01:01.988
否则竹签很容易烧断

0:01:12.138,0:01:13.734
下一步开始准备调汁

0:01:13.734,0:01:16.023
准备大蒜几颗拍散之后剁碎备用

0:01:19.780,0:01:21.560
准备几根小葱头切碎备用

0:01:23.144,0:01:24.832
碗中加入食用盐小半勺

0:01:25.398,0:01:27.387
再加入和食用盐等量的白糖

0:01:28.034,0:01:29.329
加入香醋3克

0:01:30.774,0:01:32.219
加入生抽酱油10克

0:01:35.225,0:01:36.682
加入少许的香油

0:01:39.687,0:01:40.959
然后搅拌均匀

0:01:43.699,0:01:45.953
拌匀之后再加入适量的香辣红油

0:01:48.820,0:01:50.462
下一步开始准备烧辣椒

0:01:51.052,0:01:54.011
将穿好的辣椒用明火烧至干香有气泡即可

0:01:54.554,0:01:57.156
（提示：未成年人请在成年人的陪同下制作）

0:02:06.693,0:02:09.052
然后将烧好的辣椒撕成小条备用

0:02:09.398,0:02:11.479
同学们辣椒皮可以不用去除

0:02:11.618,0:02:13.109
这样成菜更具椒香味

0:02:17.526,0:02:19.433
然后将撕好的辣椒放入盘中

0:02:26.219,0:02:28.369
最后淋上调好的料汁即可上菜

0:02:36.520,0:02:39.005
一道非常美味的烧椒皮蛋就制作完成

0:02:46.920,0:03:01.920
下面开始技术总结
第一，最好选择黄心皮蛋制作，黄心皮蛋比黑心皮蛋更香
第二，不能吃辣的同学可以用大青椒代替二荆条
第三，肠胃不好的同学慎吃此菜（生辣型菜谱）
烧椒皮蛋的技术总结完毕


```

**Comment by max-sun-hongyi** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：川味凉菜“烧椒皮蛋”的家常做法，香辣回味，流连忘返！
Head Chef teaches you how to cook: Sichuan cold dish “Grilled chili with thousand-year egg”
简介
同学们好，今天给大家分享一道川味凉菜“烧椒皮蛋”，顾名思义此菜主要用到的就是皮蛋和烧焦过的辣椒，两种食材经过特制的酱汁完美的融合，不仅突出了皮蛋的香还有着特别香辣的回味，能吃辣的朋友一定要尝试，保证流连忘返！主要特别注意的是皮蛋最好选用四川黄心皮蛋，再有在烧辣椒的时候需注意火候的控制，以免彻底烧焦。
Hello everyone today I will show you how to make this Sichuan cold dish:  “Grilled chili with thousand-year egg”. You can tell by the name that this dish uses grilled chili and thousand-year eggs, these two ingredients mixed with special made sauce, not only emphasis the aroma of the thousand-year egg but also has the lingering aroma of grilled chili, this is a must try for spicy food lovers, you won’t regret it! Please note that it is best to use Sichuan yellow heart thousand-year egg, also, remember to control the flame when grilling, don’t over grill the chilies.
本期菜品：【烧椒皮蛋】
【主料】
Main ingredients
黄心皮蛋（几个）
Yellow heart thousand-year eggs (a few)
【辅料】
Other ingredients
小米辣（几个）
Xiaomila chilli (a few)
二荆条（几个）
Erjintiao (a few)
大蒜（几颗）
Garlic (a few)
小葱头（几根）
scallions (a few)
香辣红油（适量）
red chili oil (adjustable) 
【调味料】
Seasonings
食用盐（小半勺）
Salt (half a spoon)
白糖（小半勺）
Sugar (half a spoon)
香醋（3克）
vinegar (3 g)
生抽酱油（10克）
Light soy sauce (10 g)
香油（少许）
Sesame (a small drizzle)

字幕
0:00:00.000,0:00:01.140
哈喽大家好 我是王刚
Hello everyone this is Chef Wang

0:00:01.140,0:00:03.140
本期视频我给大家分享一道家常菜
Today I’m going to share a home dish 

0:00:03.540,0:00:04.740
烧椒皮蛋
“Grilled chili with thousand-year egg”

0:00:04.900,0:00:07.074
首先我们准备几个黄心皮蛋
Firstly, we prepare a few yellow heart thousand-year eggs

0:00:07.074,0:00:09.731
敲掉表皮的石灰之后再剥掉蛋壳备用
Knock off the lime on the surface and peel off the shell, then set aside for later

0:00:13.880,0:00:16.223
同学们皮蛋可以放入清水中剥离
You can submerge it under water to peel off the shell

0:00:16.223,0:00:18.042
这样可以防止（将）皮蛋剥烂
This way it prevents the egg to be broken

0:00:21.144,0:00:23.349
蛋壳剥完之后再清洗干净备用
Wash it thoroughly after peeling off the shell, then set aside for later.

0:00:27.043,0:00:28.890
然后将皮蛋一切为四
Cut the egg into 4 pieces

0:00:29.179,0:00:30.774
皮蛋也可以多切几块
You can cut it into more pieces 

0:00:31.098,0:00:32.809
这样摆盘份量显得更多
This way it looked like you have more on the plate

0:00:37.861,0:00:40.034
皮蛋切好之后下一步准备摆盘
Then we move on to plating 

0:00:40.034,0:00:41.539
首先我们准备圆盘1个
Let’s prepare a round plate 

0:00:41.539,0:00:44.959
然后将切好的皮蛋蛋黄朝下均匀地摆入盘中
Evenly lay down all the wedges of eggs with yolks down on the plate 

0:00:52.924,0:00:55.283
皮蛋摆好之后下一步开始准备辅料
Then we prepare other ingredients

0:00:55.445,0:00:58.115
准备几个小米辣和二荆条穿入竹签备用
Prepare a few Xiaomila and Erjintiao, skew them onto bamboo skewers

0:00:58.242,0:01:00.208
同学们竹签必须事先泡
Remember that the bamboo skewers must be soaked in water before use

0:01:00.289,0:01:01.988
否则竹签很容易烧断
Otherwise it is easily burnt 

0:01:12.138,0:01:13.734
下一步开始准备调汁
Next let’s prepare the seasoning sauce

0:01:13.734,0:01:16.023
准备大蒜几颗拍散之后剁碎备用
Crush a few gloves of garlic then chop them up for later

0:01:19.780,0:01:21.560
准备几根小葱头切碎备用
Chop up some scallions

0:01:23.144,0:01:24.832
碗中加入食用盐小半勺
Add half a spoon of salt into a bowl

0:01:25.398,0:01:27.387
再加入和食用盐等量的白糖
Add the same amount of sugar in the bowl

0:01:28.034,0:01:29.329
加入香醋3克
Add 3 g of vinegar 

0:01:30.774,0:01:32.219
加入生抽酱油10克
Add 10 g of light soy sauce

0:01:35.225,0:01:36.682
加入少许的香油
Add a small drizzle of sesame oil

0:01:39.687,0:01:40.959
然后搅拌均匀
Then mix them up evenly

0:01:43.699,0:01:45.953
拌匀之后再加入适量的香辣红油
After mixing, add some red chili oil

0:01:48.820,0:01:50.462
下一步开始准备烧辣椒
Next we grill the chilies 

0:01:51.052,0:01:54.011
将穿好的辣椒用明火烧至干香有气泡即可
Lightly grill skewed chilies until the skin starts to bubble 

0:01:54.554,0:01:57.156
（提示：未成年人请在成年人的陪同下制作）
(WARNING: Children must be supervised by adults at all times)

0:02:06.693,0:02:09.052
然后将烧好的辣椒撕成小条备用
Then tear grilled chili into small strips for later

0:02:09.398,0:02:11.479
同学们辣椒皮可以不用去除
Chili skin can be left on 

0:02:11.618,0:02:13.109
这样成菜更具椒香味
This way the dish has more chili pungency 

0:02:17.526,0:02:19.433
然后将撕好的辣椒放入盘中
Then place chili strips on the plate

0:02:26.219,0:02:28.369
最后淋上调好的料汁即可上菜
Drizzle on the seasoning sauce to finish it up

0:02:36.520,0:02:39.005
一道非常美味的烧椒皮蛋就制作完成
A delicious dish of grilled chili with thousand-year egg is completed 

0:02:46.920,0:03:01.920
下面开始技术总结
Next the technical summary
第一，最好选择黄心皮蛋制作，黄心皮蛋比黑心皮蛋更香
Firstly, it’s best to use yellow skin thousand-year eggs which taste better than the black skin thousand-year eggs. 

第二，不能吃辣的同学可以用大青椒代替二荆条
Secondly, for those of you who can’t handle spiciness, you can use Daqingjiao instead

第三，肠胃不好的同学慎吃此菜（生辣型菜谱）
Thirdly, be careful eating this if you have a sensitive stomach.

烧椒皮蛋的技术总结完毕
That’s it for the Grilled chili with thousand-year eggs
