### ISSUE TITLE
【美食作家王刚】一串樱桃肉 - https://youtu.be/j4He7VuVyu4

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#916]
**视频链接**：https://youtu.be/j4He7VuVyu4

视频时长 10:05，预计发布时间为北京时间4月16日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：做一串“樱桃红烧肉”，肉红亮软糯，四伯是真心喜欢，吃完樱桃肉再吃点樱桃，安逸！

简介
朋友们好！四伯想吃红烧肉了，特意留了一块肉回来，那必然不能辜负他老人家，赶快做成樱桃肉来！这次的樱桃红烧肉和以往不同，特意做成一串来吃，让成菜更有趣味，大家可以在家尝试，给家人露一手。在调味上大家不必担心过甜，因为炒制完成的糖色的甜度非常低，大家只需要控制调味时候的盐糖量即可，最后成菜咸甜适口，红亮软糯，肥而不腻，吃完肉再来些四川本地樱桃真的安逸！

字幕
0:00:00.421,0:00:01.323
哈喽 大家好

0:00:01.323,0:00:06.981
今天我伯爷赶场卖肉特意留了一小块来做这个樱桃肉

0:00:07.965,0:00:09.431
四伯爷你怎么留这么一点安

0:00:09.739,0:00:12.381
留这点儿的（都不错了）别人已经买了我特意割下来的

0:00:12.381,0:00:18.823
我想到那樱桃出来了拿回来喊二娃整点樱桃肉来吃

0:00:20.154,0:00:21.485
不然一哈都卖了

0:00:21.639,0:00:22.584
是不 是啊

0:00:23.432,0:00:25.014
那我们先把这个肉烧一下

0:00:34.001,0:00:34.754
好好

0:00:35.332,0:00:35.872
可以了

0:00:36.142,0:00:39.112
幸好拿的长的钩子小钩子肯定很烫的

0:00:39.768,0:00:41.080
烫得不得了吧 嗯

0:00:42.082,0:00:44.551
好了 我们这个肉就烧了之后

0:00:45.207,0:00:48.852
拿温水或清水把它泡一下

0:00:48.968,0:00:50.588
泡2分钟这个 非常好洗

0:00:51.282,0:00:52.189
我拿那个碗些来

0:00:52.189,0:00:52.960
轻轻的洗掉了

0:00:52.979,0:00:55.525
现在我们这个猪皮已经把它洗干净了

0:00:55.776,0:00:57.685
这一次我们就做得非常简单

0:00:58.283,0:00:59.151
就直接切

0:01:01.639,0:01:02.950
我们先来切第一刀

0:01:08.100,0:01:11.224
第一刀的话大概切一厘米（宽）左右

0:01:11.571,0:01:12.729
不把这个肉切断

0:01:14.136,0:01:15.101
切到这个位置

0:01:17.608,0:01:19.440
然后再横过来切第二刀

0:01:22.044,0:01:24.243
然后再拉过来切第三刀

0:01:26.441,0:01:27.888
跟着转（转着切）呀

0:01:27.888,0:01:28.968
嗯跟着转

0:01:31.783,0:01:33.134
然后切第四刀

0:01:39.054,0:01:41.002
这样的一块肉就切到这么长

0:01:41.465,0:01:43.182
然后我们在翻过来

0:01:46.962,0:01:50.772
 也是同样的切一厘米左右把皮子留在上面

0:01:51.301,0:01:52.150
让它连着

0:02:01.562,0:02:03.683
等会儿夹（着吃）的时候就戳这个就可以了

0:02:04.937,0:02:06.865
但是前提是要把这个烧耙

0:02:07.695,0:02:09.431
如果烧得不耙那个皮子戳不断

0:02:10.414,0:02:12.324
你切得好长一条哦

0:02:13.037,0:02:13.886
没关系啊

0:02:14.619,0:02:15.679
就是要它长安

0:02:16.567,0:02:18.514
好了 现在我们这个已经改好刀了

0:02:18.939,0:02:20.906
这一串肉就像鞭炮一样

0:02:23.895,0:02:25.053
是不是 四伯爷 嗯

0:02:25.053,0:02:26.846
像不像火炮  是啊

0:02:27.135,0:02:27.772
像噶

0:02:27.772,0:02:29.026
嗯 是啊一模一样

0:02:29.527,0:02:32.092
现在我们这样子切好之后直接下锅

0:02:32.420,0:02:33.767
直接焯下水之后

0:02:33.767,0:02:37.782
直接把它稍微爆一下油然后就放其他东西进去烧

0:02:37.955,0:02:38.842
特别的简单

0:02:41.041,0:02:41.812
放在这里面

0:02:44.223,0:02:45.920
然后准备一点姜片

0:02:50.703,0:02:52.555
再准备一棵大葱

0:02:53.654,0:02:55.062
直接切段就可以

0:02:56.065,0:02:59.363
然后我们这个里面准备了2片香叶

0:02:59.363,0:03:03.201
一些这陈皮还有三颗八角

0:03:03.973,0:03:06.210
然后可以放点山楂呀什么的进去

0:03:06.460,0:03:08.119
就增加这个鲜甜味

0:03:10.433,0:03:11.494
还有冰糖

0:03:11.494,0:03:13.172
搞忘记这个东西了最重要的

0:03:14.484,0:03:15.930
然后我们准备一大块

0:03:16.470,0:03:17.589
把它敲一下

0:03:18.476,0:03:20.273
这样子敲到处洒起

0:03:25.380,0:03:26.981
好了 拍撒之后可以了

0:03:27.367,0:03:28.543
我去拿一个碗来（装）

0:03:29.797,0:03:32.189
首先我们在锅中加入适量的清水

0:03:35.081,0:03:37.377
然后把切好的五花肉下锅焯水

0:03:40.212,0:03:42.198
中途加半勺料酒去腥

0:03:44.590,0:03:46.615
大火烧开之后再撇去浮沫

0:03:48.775,0:03:51.456
焯好水之后到出下一步准备炸五花肉

0:03:54.850,0:03:56.817
锅烧热之后加入一些宽油

0:04:04.513,0:04:07.695
油温烧至5成热再把五花肉下锅炸2分钟

0:04:07.849,0:04:10.588
同学们这样可以去除肥肉中的一些油脂

0:04:16.104,0:04:17.859
略炸之后捞出备用

0:04:25.400,0:04:28.215
热油到出下一步开始准备炒糖色

0:04:30.028,0:04:32.189
首先我们直接加入敲碎的冰糖

0:04:32.189,0:04:34.291
再加入和冰糖1:1的清水

0:04:34.291,0:04:36.123
然后把冰糖熬成糖色

0:04:48.100,0:04:51.282
糖色炒好之后加入适量的开水继续熬2分钟

0:04:51.398,0:04:53.384
同学们可别小看这2分钟

0:04:53.384,0:04:55.679
这样可以让糖色不分层断色

0:05:01.446,0:05:03.587
糖色完全融合之后倒出备用

0:05:03.587,0:05:05.110
下一步开始制作

0:05:06.364,0:05:09.257
首先把配好的姜葱和香料下锅小火炒香

0:05:13.346,0:05:15.834
香料炒香之后加入五花肉翻炒几下

0:05:18.244,0:05:19.556
然后加入适量的清水

0:05:19.865,0:05:22.295
清水的量最好能烧制40分钟以上

0:05:22.295,0:05:23.992
大概需要没过五花肉即可

0:05:25.670,0:05:27.656
加入适量的糖色大火烧开

0:05:47.695,0:05:50.009
大火烧开之后再加入适量的冰糖

0:05:50.106,0:05:51.996
然后转小火烧40分钟

0:05:53.558,0:05:55.467
中途捡去姜葱和辅料（20分钟后）

0:06:04.146,0:06:07.058
捡去辅料之后加入适量的食用盐调咸味

0:06:12.690,0:06:15.216
调好味之后继续小火烧20分钟

0:06:15.429,0:06:18.148
同学们这个时候要密切关注锅中的变化

0:06:18.514,0:06:20.906
因为此时的糖浆非常容易烧糊

0:06:22.892,0:06:25.380
当汁水变得浓稠之后即可出锅摆盘

0:06:38.206,0:06:39.550
可以了 四伯爷

0:06:40.019,0:06:41.524
呵呵 看到是好看

0:06:42.005,0:06:43.259
是不 绯红的

0:06:49.778,0:06:50.395
四伯爷 

0:06:50.395,0:06:50.858
来嘛

0:06:50.858,0:06:51.359
碗

0:06:51.803,0:06:52.941
自己戳来吃哦

0:06:52.941,0:06:53.712
要的呀

0:06:53.712,0:06:54.484
自己戳

0:06:55.409,0:06:57.647
如果你嫌硬的话可以再烧一会儿的

0:06:57.820,0:06:58.958
再拿来烧一会儿

0:07:02.487,0:07:03.703
大家可以看一下这个

0:07:03.703,0:07:04.474
我尝一下

0:07:06.306,0:07:06.923
嗯

0:07:07.618,0:07:09.161
咬得动噻 咬得动咬得动

0:07:11.321,0:07:12.015
安逸

0:07:15.757,0:07:16.354
好干（吃）

0:07:16.354,0:07:17.203
吃 多吃两坨

0:07:19.093,0:07:20.289
看这就没得皮子的

0:07:28.003,0:07:28.659
安逸

0:07:29.296,0:07:31.899
就是说把这个红烧肉切小块一点

0:07:32.671,0:07:34.889
烧起红通通的就跟樱桃一样

0:07:34.889,0:07:36.065
（樱桃肉的名字）主要是这样子喊出来的

0:07:36.952,0:07:39.344
现在还正是吃樱桃的时候

0:07:39.344,0:07:41.118
就是吃这个肉的时候

0:07:41.118,0:07:42.545
是 嗯安逸

0:07:46.846,0:07:48.794
现在就吃这个 等会儿就吃皮子

0:07:51.841,0:07:54.600
嗯好吃 真的好吃

0:07:58.862,0:08:01.542
这样子整起一个人害怕要吃一斤多肉哦

0:08:02.005,0:08:03.047
你有没得浪凶得哦

0:08:03.683,0:08:05.747
试哈看嘛 看我吃得完不嘛

0:08:09.334,0:08:11.147
主要这样子吃的话也不腻

0:08:12.632,0:08:13.384
安逸

0:08:16.933,0:08:20.038
你看嘛 我都吃了好多了这一截都是我夹了的

0:08:20.694,0:08:21.118
嗯

0:08:21.812,0:08:23.336
我把这干的这一截夹来吃

0:08:23.683,0:08:26.673
如果牙口不好的话可以炖的时间稍微长一些

0:08:27.058,0:08:29.546
这样放在嘴里一抿就化了的这种

0:08:29.932,0:08:31.764
我这个只做了40分钟

0:08:31.822,0:08:34.117
如果要软一点就可以做一个小时以上

0:08:35.371,0:08:39.633
一年十二月每个月你整一回给我吃就可以了

0:08:41.832,0:08:43.934
这个经常吃要吃腻

0:08:43.934,0:08:45.882
一个月吃一回不得多噻

0:08:45.882,0:08:47.386
一个月两回都不得腻四伯爷

0:08:47.386,0:08:49.180
吃一回嘛就可以了

0:08:49.296,0:08:51.089
我达到这个愿望就可以了

0:08:51.089,0:08:51.784
要的

0:08:52.285,0:08:54.191
你把肉准备起就是 嘿嘿

0:08:54.191,0:08:57.878
拿肉没得问题我随便削一刀下来就够了

0:08:57.878,0:08:58.669
嗯

0:09:00.829,0:09:03.683
我干到这一行的未必还这个肉还整它不到吗

0:09:03.857,0:09:04.628
这个好吃

0:09:05.361,0:09:08.943
好 我们这个红烧肉吃完了来吃这个

0:09:09.566,0:09:13.558
这个是我们这个本地樱桃

0:09:13.558,0:09:14.947
本地樱桃

0:09:15.622,0:09:16.162
嗯

0:09:18.997,0:09:20.405
这个有点酸

0:09:21.388,0:09:22.661
这个本味都嘛

0:09:22.873,0:09:23.510
嗯

0:09:27.001,0:09:30.086
可以还多安逸这个樱桃跟吃胡豆米一样

0:09:31.629,0:09:35.564
这个就特别适合吃完有一些有一点肥腻的东西

0:09:35.564,0:09:37.743
然后吃这个酸酸的甜甜的

0:09:38.167,0:09:39.074
特别解腻

0:09:41.793,0:09:42.410
安逸

0:09:44.050,0:09:45.940
嗯 真的很酸

0:09:46.538,0:09:47.907
我吃了几个酸得不得了

0:09:48.081,0:09:49.199
我还吃得惯

0:09:53.500,0:09:54.927
两颗两颗的吃


```

**Comment by Kevinzheng5** [comment]
认领

**Comment by Kevinzheng5** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：做一串“樱桃红烧肉”，肉红亮软糯，四伯是真心喜欢，吃完樱桃肉再吃点樱桃，安逸！
Chef Wang shares with you: “Red Braised Pork”. Nice color and texture. Uncle loves it. Have some cherries after, nice!

简介
朋友们好！四伯想吃红烧肉了，特意留了一块肉回来，那必然不能辜负他老人家，赶快做成樱桃肉来！这次的樱桃红烧肉和以往不同，特意做成一串来吃，让成菜更有趣味，大家可以在家尝试，给家人露一手。在调味上大家不必担心过甜，因为炒制完成的糖色的甜度非常低，大家只需要控制调味时候的盐糖量即可，最后成菜咸甜适口，红亮软糯，肥而不腻，吃完肉再来些四川本地樱桃真的安逸！
Hi guys! Uncle want some braised pork so he got a piece of pork back. Surely I can’t let him down, so let’s make some red braised pork! The red braised pork this time is a little different from the previous ones. I made it one string to make the dish more interesting. You can have a try back home for your family. For the seasoning, don’t worry that it’s going to be too sweet since the caramelized sugar is barely sweet. Just be careful when you later season it with salt and sugar. The final dish has a balanced salty and sweet flavor with a bright red color and a soft texture. It’s very juicy but not too greasy. Super nice to have some local Sichuan cherries after the pork, too!


字幕
0:00:00.421,0:00:01.323
哈喽 大家好
Hi everyone

0:00:01.323,0:00:06.981
今天我伯爷赶场卖肉特意留了一小块来做这个樱桃肉
Today my uncle kept a piece of pork from the market for some braised pork

0:00:07.965,0:00:09.431
四伯爷你怎么留这么一点安
Uncle, why did you keep so little?

0:00:09.739,0:00:12.381
留这点儿的（都不错了）别人已经买了我特意割下来的
This piece was even sold and I cut some off

0:00:12.381,0:00:18.823
我想到那樱桃出来了拿回来喊二娃整点樱桃肉来吃
It’s already cherry season and I wanted Erwa here together for some braised pork

0:00:20.154,0:00:21.485
不然一哈都卖了
Otherwise I could sell it altogether

0:00:21.639,0:00:22.584
是不 是啊
Right, right

0:00:23.432,0:00:25.014
那我们先把这个肉烧一下
Then let’s cook some braised pork

0:00:34.001,0:00:34.754
好好
Alright

0:00:35.332,0:00:35.872
可以了
Done

0:00:36.142,0:00:39.112
幸好拿的长的钩子小钩子肯定很烫的
Glad we got the long hook. A shorter hook will burn my hand

0:00:39.768,0:00:41.080
烫得不得了吧 嗯
It’s pretty hot, huh?

0:00:42.082,0:00:44.551
好了 我们这个肉就烧了之后
Alright, after we burn the skin of the pork

0:00:45.207,0:00:48.852
拿温水或清水把它泡一下
Rinse it with some warm water

0:00:48.968,0:00:50.588
泡2分钟这个 非常好洗
Soak it for 2 minutes first. Then the dust will easily come off

0:00:51.282,0:00:52.189
我拿那个碗些来
I’ll bring a bowl for you

0:00:52.189,0:00:52.960
轻轻的洗掉了
It will come off easily

0:00:52.979,0:00:55.525
现在我们这个猪皮已经把它洗干净了
Now we’ve already cleaned the skin of the pork 

0:00:55.776,0:00:57.685
这一次我们就做得非常简单
This time we’ll make it simple

0:00:58.283,0:00:59.151
就直接切
Just slice

0:01:01.639,0:01:02.950
我们先来切第一刀
Slice the first time

0:01:08.100,0:01:11.224
第一刀的话大概切一厘米（宽）左右
Make the slice about one centimeter thick

0:01:11.571,0:01:12.729
不把这个肉切断
Don’t slice through

0:01:14.136,0:01:15.101
切到这个位置
Leave it about here

0:01:17.608,0:01:19.440
然后再横过来切第二刀
Then turn the meat 90 degrees and slice 

0:01:22.044,0:01:24.243
然后再拉过来切第三刀
Then turn again and slice

0:01:26.441,0:01:27.888
跟着转（转着切）呀
Turn and slice?

0:01:27.888,0:01:28.968
嗯跟着转
Yeah turn and slice

0:01:31.783,0:01:33.134
然后切第四刀
Then we slice again

0:01:39.054,0:01:41.002
这样的一块肉就切到这么长
Cut the meat to a strip like this

0:01:41.465,0:01:43.182
然后我们在翻过来
Then we lay it down

0:01:46.962,0:01:50.772
也是同样的切一厘米左右把皮子留在上面
Slice about every centimeter away but leave the skin

0:01:51.301,0:01:52.150
让它连着
To keep the pieces together

0:02:01.562,0:02:03.683
等会儿夹（着吃）的时候就戳这个就可以了
The chopsticks can pick each piece up later

0:02:04.937,0:02:06.865
但是前提是要把这个烧耙
After we make it soft

0:02:07.695,0:02:09.431
如果烧得不耙那个皮子戳不断
It needs to be soft enough for the chopsticks to cut through

0:02:10.414,0:02:12.324
你切得好长一条哦
It’s really long

0:02:13.037,0:02:13.886
没关系啊
It’s okay

0:02:14.619,0:02:15.679
就是要它长安
I wanted it to be long

0:02:16.567,0:02:18.514
好了 现在我们这个已经改好刀了
Alright, now the meat is in proper shape

0:02:18.939,0:02:20.906
这一串肉就像鞭炮一样
It looks like a string of fireworks

0:02:23.895,0:02:25.053
是不是 四伯爷 嗯
Right uncle? Yeah

0:02:25.053,0:02:26.846
像不像火炮  是啊
Like fireworks? Yeah

0:02:27.135,0:02:27.772
像噶
Looks alike?

0:02:27.772,0:02:29.026
嗯 是啊一模一样
Yeah indeed

0:02:29.527,0:02:32.092
现在我们这样子切好之后直接下锅
After slicing, let’s cook it

0:02:32.420,0:02:33.767
直接焯下水之后
Blanch it first

0:02:33.767,0:02:37.782
直接把它稍微爆一下油然后就放其他东西进去烧
Then fry the fat out and braise with spices

0:02:37.955,0:02:38.842
特别的简单
It’s really straight forward

0:02:41.041,0:02:41.812
放在这里面
Put it in here first

0:02:44.223,0:02:45.920
然后准备一点姜片
Slice some ginger

0:02:50.703,0:02:52.555
再准备一棵大葱
Then some spring onions

0:02:53.654,0:02:55.062
直接切段就可以
Cut it to segments

0:02:56.065,0:02:59.363
然后我们这个里面准备了2片香叶
The spices include 2 bay leaves

0:02:59.363,0:03:03.201
一些这陈皮还有三颗八角
Some dried mandarin peel and three whole star anises

0:03:03.973,0:03:06.210
然后可以放点山楂呀什么的进去
You can also put some hawthorn in it

0:03:06.460,0:03:08.119
就增加这个鲜甜味	
To make it sweeter and more savory

0:03:10.433,0:03:11.494
还有冰糖
We also need some white rock sugar

0:03:11.494,0:03:13.172
搞忘记这个东西了最重要的
Almost forgot the most important stuff

0:03:14.484,0:03:15.930
然后我们准备一大块
Get a large piece

0:03:16.470,0:03:17.589
把它敲一下
Smash it

0:03:18.476,0:03:20.273
这样子敲到处洒起
It will go everywhere the way you smash it

0:03:25.380,0:03:26.981
好了 拍撒之后可以了
Alright, smash to pieces

0:03:27.367,0:03:28.543
我去拿一个碗来（装）
Let me get a bowl for it

0:03:29.797,0:03:32.189
首先我们在锅中加入适量的清水
First we add some water in the wok

0:03:35.081,0:03:37.377
然后把切好的五花肉下锅焯水
Then blanch the pork

0:03:40.212,0:03:42.198
中途加半勺料酒去腥
Add some Chinese cooking wine to get rid of the raw smell

0:03:44.590,0:03:46.615
大火烧开之后再撇去浮沫
Bring it to boil and get rid of the scum

0:03:48.775,0:03:51.456
焯好水之后到出下一步准备炸五花肉
After blanching, get the pork off to fry

0:03:54.850,0:03:56.817
锅烧热之后加入一些宽油
Heat up the wok and add Kuan You (literally “broad oil”)

0:04:04.513,0:04:07.695
油温烧至5成热再把五花肉下锅炸2分钟
Heat up the oil to about 150 degrees Celsius and fry the pork for 2 minutes

0:04:07.849,0:04:10.588
同学们这样可以去除肥肉中的一些油脂
Frying this way can get rid of some fat within the pork

0:04:16.104,0:04:17.859
略炸之后捞出备用
Get it off after frying

0:04:25.400,0:04:28.215
热油到出下一步开始准备炒糖色
Oil off the wok. Next step is making the caramelized sugar

0:04:30.028,0:04:32.189
首先我们直接加入敲碎的冰糖
Put the smashed rock sugar in the wok

0:04:32.189,0:04:34.291
再加入和冰糖1:1的清水
Add some water about the same volume of the sugar

0:04:34.291,0:04:36.123
然后把冰糖熬成糖色
Then boil the sugar to caramelize it

0:04:48.100,0:04:51.282
糖色炒好之后加入适量的开水继续熬2分钟
After it’s done, add some boiling water to braise 2 more minutes

0:04:51.398,0:04:53.384
同学们可别小看这2分钟
These 2 minutes are really important

0:04:53.384,0:04:55.679
这样可以让糖色不分层断色
This way the color will be evenly distributed on the pork

0:05:01.446,0:05:03.587
糖色完全融合之后倒出备用
After the caramelized sugar is well mixed, pour it out

0:05:03.587,0:05:05.110
下一步开始制作
Now let’s cook the pork

0:05:06.364,0:05:09.257
首先把配好的姜葱和香料下锅小火炒香
First stir fry the ginger, spring onions and spices at low temperature 

0:05:13.346,0:05:15.834
香料炒香之后加入五花肉翻炒几下
After the smell comes out, put the pork in and stir fry

0:05:18.244,0:05:19.556
然后加入适量的清水
Add some water

0:05:19.865,0:05:22.295
清水的量最好能烧制40分钟以上
Have enough water that can braise for more than 40 minutes

0:05:22.295,0:05:23.992
大概需要没过五花肉即可
About the volume to submerge the pork

0:05:25.670,0:05:27.656
加入适量的糖色大火烧开
Put the caramelized sugar in and bring it to boil

0:05:47.695,0:05:50.009
大火烧开之后再加入适量的冰糖
When it starts to boil, add some sugar

0:05:50.106,0:05:51.996
然后转小火烧40分钟
Then turn the burner down and braise for a total of 40 minutes

0:05:53.558,0:05:55.467
中途捡去姜葱和辅料（20分钟后）
After 20 minutes, pick the ginger, spring onions and other ingredients

0:06:04.146,0:06:07.058
捡去辅料之后加入适量的食用盐调咸味
After picking them out, season with salt

0:06:12.690,0:06:15.216
调好味之后继续小火烧20分钟
Braise for another 20 minutes

0:06:15.429,0:06:18.148
同学们这个时候要密切关注锅中的变化
Be careful what happens in the wok 

0:06:18.514,0:06:20.906
因为此时的糖浆非常容易烧糊
The caramelized sugar gets burnt very easily

0:06:22.892,0:06:25.380
当汁水变得浓稠之后即可出锅摆盘
When the sauce thickens, it’s ready

0:06:38.206,0:06:39.550
可以了 四伯爷
It’s ready, uncle

0:06:40.019,0:06:41.524
呵呵 看到是好看
Ha it looks nice

0:06:42.005,0:06:43.259
是不 绯红的
Right? Look at the scarlet color

0:06:49.778,0:06:50.395
四伯爷 
Uncle

0:06:50.395,0:06:50.858
来嘛
Come on

0:06:50.858,0:06:51.359
碗
Here’s the bowl

0:06:51.803,0:06:52.941
自己戳来吃哦
Help yourself

0:06:52.941,0:06:53.712
要的呀
Alright

0:06:53.712,0:06:54.484
自己戳
Pick a piece yourself

0:06:55.409,0:06:57.647
如果你嫌硬的话可以再烧一会儿的
If the texture is not soft enough, braise longer

0:06:57.820,0:06:58.958
再拿来烧一会儿
Braise for a little longer

0:07:02.487,0:07:03.703
大家可以看一下这个
Have a look, guys

0:07:03.703,0:07:04.474
我尝一下
Let me taste this

0:07:06.306,0:07:06.923
嗯
Nice

0:07:07.618,0:07:09.161
咬得动噻 咬得动咬得动
Soft enough? Yeah the texture is good

0:07:11.321,0:07:12.015
安逸
Nice

0:07:15.757,0:07:16.354
好干（吃）
Delicious

0:07:16.354,0:07:17.203
吃 多吃两坨
Have some more

0:07:19.093,0:07:20.289
看这就没得皮子的
This piece dropped off from the skin

0:07:28.003,0:07:28.659
安逸
Nice

0:07:29.296,0:07:31.899
就是说把这个红烧肉切小块一点
If we slice the pork to smaller pieces

0:07:32.671,0:07:34.889
烧起红通通的就跟樱桃一样
After cooking, the red color makes it look like cherries

0:07:34.889,0:07:36.065
（樱桃肉的名字）主要是这样子喊出来的
That’s the reason it is also called “Cherry Pork”

0:07:36.952,0:07:39.344
现在还正是吃樱桃的时候
It is the cherry season now
0:07:39.344,0:07:41.118
就是吃这个肉的时候
Also the season for this “Red Braised Pork”

0:07:41.118,0:07:42.545
是 嗯安逸
Yeah. So nice!

0:07:46.846,0:07:48.794
现在就吃这个 等会儿就吃皮子
Have the meat first and then we’ll move on to the skin

0:07:51.841,0:07:54.600
嗯好吃 真的好吃
Yeah it’s good. It’s really good

0:07:58.862,0:08:01.542
这样子整起一个人害怕要吃一斤多肉哦
I’m afraid I’ll have more than 500 grams myself

0:08:02.005,0:08:03.047
你有没得浪凶得哦
Seriously?

0:08:03.683,0:08:05.747
试哈看嘛 看我吃得完不嘛
Let me have a try

0:08:09.334,0:08:11.147
主要这样子吃的话也不腻
It’s not too greasy

0:08:12.632,0:08:13.384
安逸
Nice

0:08:16.933,0:08:20.038
你看嘛 我都吃了好多了这一截都是我夹了的
See? I’ve already had a lot. I ate all that was here

0:08:20.694,0:08:21.118
嗯
Yeah	

0:08:21.812,0:08:23.336
我把这干的这一截夹来吃
I’ll have this piece too

0:08:23.683,0:08:26.673
如果牙口不好的话可以炖的时间稍微长一些
You can braise it a little longer if you have bad teeth

0:08:27.058,0:08:29.546
这样放在嘴里一抿就化了的这种
It melts in your month

0:08:29.932,0:08:31.764
我这个只做了40分钟
I only braised it for 40 minutes

0:08:31.822,0:08:34.117
如果要软一点就可以做一个小时以上
You can go for an hour to make it softer

0:08:35.371,0:08:39.633
一年十二月每个月你整一回给我吃就可以了
I want to have it once a month

0:08:41.832,0:08:43.934
这个经常吃要吃腻
You will get tired of it that often

0:08:43.934,0:08:45.882
一个月吃一回不得多噻
Once a month is not too often

0:08:45.882,0:08:47.386
一个月两回都不得腻四伯爷
I think twice a month is even good, uncle

0:08:47.386,0:08:49.180
吃一回嘛就可以了
I’ll be satisfied with once

0:08:49.296,0:08:51.089
我达到这个愿望就可以了
That’s my wish

0:08:51.089,0:08:51.784
要的
Alrighty

0:08:52.285,0:08:54.191
你把肉准备起就是 嘿嘿
You have to provide the pork though lol

0:08:54.191,0:08:57.878
拿肉没得问题我随便削一刀下来就够了
That’s perfectly fine. I’ll just cut a piece from somewhere

0:08:57.878,0:08:58.669
嗯
Right

0:09:00.829,0:09:03.683
我干到这一行的未必还这个肉还整它不到吗
I’m a butcher. I have all the pork in the world

0:09:03.857,0:09:04.628
这个好吃
This is really nice

0:09:05.361,0:09:08.943
好 我们这个红烧肉吃完了来吃这个
Alright, let’s have some of these after the pork

0:09:09.566,0:09:13.558
这个是我们这个本地樱桃
These are the local cherries

0:09:13.558,0:09:14.947
本地樱桃
Local cherries

0:09:15.622,0:09:16.162
嗯
Right

0:09:18.997,0:09:20.405
这个有点酸
It’s a bit sour

0:09:21.388,0:09:22.661
这个本味都嘛
That’s the original flavor though

0:09:22.873,0:09:23.510
嗯
Yeah

0:09:27.001,0:09:30.086
可以还多安逸这个樱桃跟吃胡豆米一样
Nice. These cherries taste like broad beans

0:09:31.629,0:09:35.564
这个就特别适合吃完有一些有一点肥腻的东西
The cherries are great fit for greasy food

0:09:35.564,0:09:37.743
然后吃这个酸酸的甜甜的
Sweet and sour

0:09:38.167,0:09:39.074
特别解腻
Really balances off the grease

0:09:41.793,0:09:42.410
安逸
Nice

0:09:44.050,0:09:45.940
嗯 真的很酸
Man it’s pretty sour

0:09:46.538,0:09:47.907
我吃了几个酸得不得了
I can no longer bear it after a few

0:09:48.081,0:09:49.199
我还吃得惯
I’m good

0:09:53.500,0:09:54.927
两颗两颗的吃
Even two of them every mouthful

**Comment by immoonancient** [comment]
由于有点来不及审稿，先原样上传了吧
等到审完再来修正
