### ISSUE TITLE
【美食作家王刚】搭雨棚给师傅们做午饭 - https://youtu.be/8KpRs6wSesc

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#919]
**视频链接**：https://youtu.be/8KpRs6wSesc

视频时长 5:08，预计发布时间为北京时间4月18日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！
# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
听了大家的意见，搭雨棚！给师傅们做几道菜犒劳一下，以后再也不怕刮风下雨了

简介
大家好，之前不少朋友看到露天厨房就说是不是应该搭个棚子来，的确亲身经历雨淋之后再次意识到棚子的重要性😂所以下定决心请师傅们来搭一个，户外厨房又完整了一步！在我们这边请师傅们来家里干活解决午饭问题是个传统，那理所应当下厨好好给几位做些饭菜，吃饱了饭才好干活嘛！

字幕
0:00:29.558,0:00:30.420
哈喽 大家好

0:00:31.002,0:00:32.688
最近因为我们这里天天下雨

0:00:32.927,0:00:35.627
我在炒菜的时候拍视频拍着拍着就下大了

0:00:35.627,0:00:36.627
非常的不方便

0:00:36.927,0:00:40.252
然后今天难得有比较好的天气

0:00:40.252,0:00:43.577
今天我们准备让师傅帮我们在这里做一个棚

0:00:43.934,0:00:46.709
做一个半透明的一个棚

0:00:46.709,0:00:48.509
既可以遮风又可以挡雨

0:00:48.807,0:00:50.957
而且还比较方便嘛

0:00:51.273,0:00:55.823
然后现在从早上来已经做了差不多半天了

0:00:55.823,0:00:57.014
现在快12点了

0:00:57.014,0:00:58.123
我准备做饭给他们吃

0:02:58.487,0:02:59.037
吃饭

0:03:02.581,0:03:03.366
你（学厨）学了几年安

0:03:04.617,0:03:06.348
学了可能三四年嘛

0:03:07.044,0:03:08.352
我以前还是去学了2年

0:03:09.514,0:03:10.070
是不

0:03:10.472,0:03:13.579
那个时候（距今）差不多有20多年了

0:03:13.719,0:03:14.422
没学会噶

0:03:15.299,0:03:16.640
半路出家

0:03:17.443,0:03:18.334
我还是半路出家

0:03:19.136,0:03:21.262
十多岁去学干到20岁左右就没干了

0:03:23.863,0:03:25.514
其实干厨师这个就是要坚持

0:03:29.769,0:03:30.717
这边有牛肉

0:03:31.274,0:03:32.762
好好好 要的

0:03:53.168,0:03:54.831
四伯爷 以后你的车子都不用打伞得了

0:03:54.831,0:03:56.205
直接退进来就是

0:03:56.205,0:03:59.083
那还用说啊 落偏东雨都没得问题的了

0:03:59.898,0:04:01.272
以后这儿就淋不到雨了

0:04:25.652,0:04:27.380
抬在那儿你们放着就是

0:04:27.888,0:04:29.149
等会我们来抬

0:04:30.333,0:04:32.566
今天我们这个搞了一天

0:04:32.636,0:04:34.736
现在这个棚已经搭好了不锈钢的

0:04:35.010,0:04:37.619
架子是不锈钢的然后上面的话是塑料板

0:04:37.802,0:04:38.931
但是也透一些光

0:04:39.337,0:04:41.442
现在我们以后再也不用怕日晒雨淋了

0:04:42.133,0:04:43.863
上一次我们拍视频的时候

0:04:43.863,0:04:46.664
很尴尬就是边下雨边拍

0:04:46.664,0:04:47.736
以为下得没多大

0:04:47.766,0:04:48.651
后面越来越大

0:04:49.048,0:04:50.237
所以我们下定决心

0:04:50.268,0:04:53.369
让我伯爷请了工人过来把这里重新弄了一下

0:04:53.715,0:04:54.904
你们在看一下成品

0:04:56.256,0:04:58.534
这下就不怕风不怕雨了

0:04:58.626,0:04:59.683
不怕风不怕雨了

0:05:00.069,0:05:01.432
安安全全的噶

0:05:01.798,0:05:02.103
是

0:05:03.750,0:05:04.513
多安逸安

0:05:45.092,0:05:47.169
抬那儿里头放着就是

0:05:47.235,0:05:48.477
扫了来

0:05:49.524,0:05:52.173
好 今天我们这个搞了一天

0:05:52.451,0:05:54.365
现在这个棚已经搭好了不锈钢的

0:05:54.757,0:05:57.292
架子是不锈钢的然后上面的话是塑料板

0:05:57.439,0:05:58.649
但是也透一些光

0:05:58.943,0:06:01.282
现在我们以后再也不用怕日晒雨淋了

0:06:01.724,0:06:03.456
上一次我们拍视频的时候

0:06:03.495,0:06:06.150
很尴尬就是边下雨边拍

0:06:06.207,0:06:07.314
以为下得没多大

0:06:07.385,0:06:08.506
后面越来越大

0:06:08.634,0:06:09.897
所以我们下定决心

0:06:09.940,0:06:13.261
让我伯爷请了工人过来把这里重新弄了一下

0:06:13.261,0:06:14.595
你们再看一下成品

0:06:15.788,0:06:18.172
这下就不怕风不怕雨了

0:06:18.229,0:06:19.705
不怕风不怕雨了

0:06:19.819,0:06:21.040
安安全全的噶

0:06:21.409,0:06:21.806
是

0:06:23.311,0:06:24.191
多安逸安


```

**Comment by kyoiroi880** [comment]
认领

**Comment by kyoiroi880** [comment]
听了大家的意见，搭雨棚！给师傅们做几道菜犒劳一下，以后再也不怕刮风下雨了
After listening to everyone's opinions,we decide to build a canopy under which I will do some dishes for the workers.And we'll never be afraid of wind and rain.
简介
大家好，之前不少朋友看到露天厨房就说是不是应该搭个棚子来，的确亲身经历雨淋之后再次意识到棚子的重要性😂所以下定决心请师傅们来搭一个，户外厨房又完整了一步！在我们这边请师傅们来家里干活解决午饭问题是个传统，那理所应当下厨好好给几位做些饭菜，吃饱了饭才好干活嘛！
Hello everyone,many friends wondered if I should build a canopy or not after seeing the outdoor kitchen before.Indeed,I realized the importance of building a canopy again after my personal experience of the rain drench.So I determined to ask the workers to build one.The outdoor kitchen is so close to complete.It is a tradition that we treat the workers lunch in our country.And it is certain that I should cook some dishes well enough for the workers so that they can work more powerful.
字幕
0:00:29.558,0:00:30.420
哈喽 大家好
Hello everyone!
0:00:31.002,0:00:32.688
最近因为我们这里天天下雨
Because of the successive rain here
0:00:32.927,0:00:35.627
我在炒菜的时候拍视频拍着拍着就下大了
Even the time I was shooting video while cooking the dishes,it rained heavier
0:00:35.627,0:00:36.627
非常的不方便
So inconvenient.
0:00:36.927,0:00:40.252
然后今天难得有比较好的天气
Then it's a rare fine day today
0:00:40.252,0:00:43.577
今天我们准备让师傅帮我们在这里做一个棚
We are going to let the workers build a canopy for us
0:00:43.934,0:00:46.709
做一个半透明的一个棚
A semitransparent canopy 
0:00:46.709,0:00:48.509
既可以遮风又可以挡雨
It can keep out both wind and rain
0:00:48.807,0:00:50.957
而且还比较方便嘛
More convenient as well
0:00:51.273,0:00:55.823
然后现在从早上来已经做了差不多半天了
Then they have been working on it for almost half a day from this morning
0:00:55.823,0:00:57.014
现在快12点了
Now it's almost 12 o'clock
0:00:57.014,0:00:58.123
我准备做饭给他们吃
I'm ready to cook for them
0:02:58.487,0:02:59.037
吃饭
Let's eat now
0:03:02.581,0:03:03.366
你（学厨）学了几年安
How many years have you learnt cooking?
0:03:04.617,0:03:06.348
学了可能三四年嘛
Maybe three or four years 
0:03:07.044,0:03:08.352
我以前还是去学了2年
I also have learnt it for 2 years before 
0:03:09.514,0:03:10.070
是不
Really?
0:03:10.472,0:03:13.579
那个时候（距今）差不多有20多年了
Almost twenty years ago
0:03:13.719,0:03:14.422
没学会噶
Failed to learn?
0:03:15.299,0:03:16.640
半路出家
A halfway decent cooker
0:03:17.443,0:03:18.334
我还是半路出家
I'm still a halfway decent cooker
0:03:19.136,0:03:21.262
十多岁去学干到20岁左右就没干了
I started learning cooking while I was 10 and gave up in my twenties
0:03:23.863,0:03:25.514
其实干厨师这个就是要坚持
In fact,the key to being a cooker lies in perseverance
0:03:29.769,0:03:30.717
这边有牛肉
Here is the beef
0:03:31.274,0:03:32.762
好好好 要的
Good,we need it
0:03:53.168,0:03:54.831
四伯爷 以后你的车子都不用打伞得了
Uncle,you need't open umbrella for your cart any longer
0:03:54.831,0:03:56.205
直接退进来就是
Just push it in 
0:03:56.205,0:03:59.083
那还用说啊 落偏东雨都没得问题的了
Of course,even the eastward rain
0:03:59.898,0:04:01.272
以后这儿就淋不到雨了
Never get wet here
0:04:25.652,0:04:27.380
抬在那儿你们放着就是
Just carry and put it there
0:04:27.888,0:04:29.149
等会我们来抬
We'll carry it later
0:04:30.333,0:04:32.566
今天我们这个搞了一天
We have been doning this for the whole day 
0:04:32.636,0:04:34.736
现在这个棚已经搭好了不锈钢的
Now the canopy has been built with the material of stainless steel
0:04:35.010,0:04:37.619
架子是不锈钢的然后上面的话是塑料板
The shelves are made of stainless steel while the boards  are made of plastic
0:04:37.802,0:04:38.931
但是也透一些光
A little transmittance
0:04:39.337,0:04:41.442
现在我们以后再也不用怕日晒雨淋了
 From now on, we won't be afraid of rain and sun
0:04:42.133,0:04:43.863
上一次我们拍视频的时候
Last time when we were shooting video 
0:04:43.863,0:04:46.664
很尴尬就是边下雨边拍
It was an embarrassing situation that we took video while it rained
0:04:46.664,0:04:47.736
以为下得没多大
We thought it wouldn't get wores 
0:04:47.766,0:04:48.651
后面越来越大
Nevertheless, it rained harder and harder 
0:04:49.048,0:04:50.237
所以我们下定决心
So we made up our minds
0:04:50.268,0:04:53.369
让我伯爷请了工人过来把这里重新弄了一下
Let my uncle pay some workers to renovate it 
0:04:53.715,0:04:54.904
你们在看一下成品
Now have a look at the finished product again
0:04:56.256,0:04:58.534
这下就不怕风不怕雨了
We won't be afraid of wind and rain any more
0:04:58.626,0:04:59.683
Such is the case
0:05:00.069,0:05:01.432
安安全全的噶
Safe and sound
0:05:01.798,0:05:02.103
是
Yeah
0:05:03.750,0:05:04.513
多安逸安
How nice
0:05:45.092,0:05:47.169
抬那儿里头放着就是
Just carry and put it there
0:05:47.235,0:05:48.477
扫了来
I'll come as soon as I finish sweeping the floor
0:05:49.524,0:05:52.173
好 今天我们这个搞了一天
Ok,we have been doning this for the whole day 
0:05:52.451,0:05:54.365
现在这个棚已经搭好了不锈钢的
Now the canopy has been built with the material of stainless steel
0:05:54.757,0:05:57.292
架子是不锈钢的然后上面的话是塑料板
The shelves are made of stainless steel while the boards  are made of plastic
0:05:57.439,0:05:58.649
但是也透一些光
A little transmittance
0:05:58.943,0:06:01.282
现在我们以后再也不用怕日晒雨淋了
 From now on, we won't be afraid of rain and sun
0:06:01.724,0:06:03.456
上一次我们拍视频的时候
Last time when we were shooting video 
0:06:03.495,0:06:06.150
很尴尬就是边下雨边拍
It was an embarrassing situation that we took video while it rained
0:06:06.207,0:06:07.314
以为下得没多大
We thought it wouldn't get wores
0:06:07.385,0:06:08.506
后面越来越大
Nevertheless, it rained harder and harder
0:06:08.634,0:06:09.897
所以我们下定决心
So we made up our mind
0:06:09.940,0:06:13.261
让我伯爷请了工人过来把这里重新弄了一下
Let my uncle pay some workers to renovate it 
0:06:13.261,0:06:14.595
你们再看一下成品
Now have a look at the finished product again
0:06:15.788,0:06:18.172
这下就不怕风不怕雨了
We won't be afraid of wind and rain any more
0:06:18.229,0:06:19.705
不怕风不怕雨了
Such is the case
0:06:19.819,0:06:21.040
安安全全的噶
Safe and sound
0:06:21.409,0:06:21.806
是
Yeah
0:06:23.311,0:06:24.191
多安逸安
How nice
