### ISSUE TITLE
[雪鱼] 山东羊肉汤 - https://youtu.be/iMGPQXSS04Q

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#920]
**视频链接**：https://youtu.be/iMGPQXSS04Q

视频时长10min
发布日期2020年4月15日

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
在山东喝羊肉汤有多豪迈！羊肉切大块，大舀子加汤，花20元吃得痛快

简介
好久没有出来喝汤了，这次来到离家2个小时的山东日照喝羊肉汤！这家店面没有很豪华的装修，
可以说是很破旧，来这家店的顾客主要是奔着味道来的，最低15元一碗肉，加汤免费，
大饼1元管够，咸菜免费自助！如果想多加一点肉，可以要20元，30元，甚至50元一碗的，都可以！
到了中午12点，顾客就像说好了似的一块都来了，排队是常有的事情，大厅里都坐满了人，想要找到一个空座还是不容易的。
一碗羊肉汤里，羊肉很大块，汤汁奶白色，吃一口肉喝一口汤，再就一口饼，真是很惬意的感觉。

字幕
1
00:00:01,920 --> 00:00:06,360
山东·日照

2
00:00:34,360 --> 00:00:37,320
大锅全羊

3
00:00:37,480 --> 00:00:42,240
现在是不到11点 她们都在忙碌着切羊肉

4
00:00:42,240 --> 00:00:45,520
羊肉呢 要把肥的和瘦的分开来

5
00:00:45,520 --> 00:00:47,920
你看 那个肥的都会被她们剔掉

6
00:00:47,920 --> 00:00:51,920
剩的羊肉就是瘦的多 肥的少

7
00:00:51,920 --> 00:00:54,840
看这羊肉切的是不是很带劲

8
00:01:00,520 --> 00:01:04,480
大姐 这边早上几点开门

9
00:01:04,480 --> 00:01:06,880
6点 6点就开始喝羊肉汤了

10
00:01:06,880 --> 00:01:08,880
就喝羊肉汤了

11
00:01:08,880 --> 00:01:13,560
老板3点就开始熬汤

12
00:01:21,280 --> 00:01:24,440
你看 这边的羊肉切的都是很大块的

13
00:01:24,440 --> 00:01:27,600
哇 这个羊骨头直接从肉上掰了下来

14
00:01:54,480 --> 00:01:57,920
这边是一个大棚 可能来的比较早

15
00:01:57,920 --> 00:01:59,640
没有很多人在这边吃

16
00:01:59,640 --> 00:02:02,920
早上来吃的大部分人还是在室内吃的

17
00:02:02,960 --> 00:02:04,520
没想到今天天气这么热

18
00:02:04,520 --> 00:02:07,040
好像只有我穿的比较厚

19
00:02:50,200 --> 00:02:55,080
这个就是吃羊汤配的主食-大饼

20
00:02:59,120 --> 00:03:01,600
这边还有韭菜花和咸菜

21
00:03:01,600 --> 00:03:04,320
都是可以免费加的

22
00:03:04,320 --> 00:03:09,520
我后面就是正在炖的羊 全羊

23
00:03:09,520 --> 00:03:13,480
里面能够明显看到的是羊肉还有羊油

24
00:03:14,840 --> 00:03:18,120
这冒的大泡 看起来就特别香

25
00:03:42,920 --> 00:03:47,320
师傅 他们说羊蝎子11点之前有时候就会被抢光

26
00:03:47,320 --> 00:03:49,120
对

27
00:03:50,760 --> 00:03:52,520
羊蝎子多少钱

28
00:03:52,520 --> 00:03:54,280
3块一个

29
00:03:54,280 --> 00:03:55,800
那确实是很实惠

30
00:03:55,800 --> 00:03:57,320
这个好吃

31
00:03:59,200 --> 00:04:00,480
你吃个吧

32
00:04:00,480 --> 00:04:02,200
现在不吃

33
00:04:02,200 --> 00:04:04,880
还没到饭点

34
00:04:27,760 --> 00:04:31,720
我要一个20的羊汤 再要一个羊骨髓

35
00:04:36,600 --> 00:04:37,400
哦（还没有点饼）

36
00:04:37,400 --> 00:04:40,240
哪有羊骨髓

37
00:04:40,240 --> 00:04:42,520
不是那个 羊蝎子

38
00:04:42,520 --> 00:04:43,480
羊蝎子

39
00:04:43,480 --> 00:04:46,000
付了3块钱 买的是羊蝎子

40
00:04:56,360 --> 00:05:00,040
再加一个大饼 忘了

41
00:05:02,080 --> 00:05:04,000
你要6碗是吧

42
00:05:04,560 --> 00:05:09,500
调料在你后面 是吧 6碗 120元

43
00:05:11,560 --> 00:05:13,040
少一个怎么

44
00:05:13,040 --> 00:05:15,680
二四六 少一碗

45
00:05:15,680 --> 00:05:16,960
不着急

46
00:05:16,960 --> 00:05:18,880
现在开始上人了

47
00:05:18,880 --> 00:05:21,520
还没开始

48
00:05:42,160 --> 00:05:44,360
再给你加两片瘦肉

49
00:05:44,360 --> 00:05:46,000
好 谢谢

50
00:05:46,000 --> 00:05:47,520
多给你点 尝尝

51
00:05:48,000 --> 00:05:49,440
多吃点 你长那么瘦

52
00:05:53,320 --> 00:05:55,720
现在等着加汤了

53
00:05:55,720 --> 00:05:57,280
自己舀吗

54
00:06:12,800 --> 00:06:15,280
好 谢谢

55
00:06:17,400 --> 00:06:20,040
拿着大饼走吧

56
00:06:20,040 --> 00:06:24,760
看我们的羊汤 羊蝎子还有大饼都上桌了

57
00:06:26,360 --> 00:06:27,520
大姐觉得我有点瘦

58
00:06:27,520 --> 00:06:29,960
所以 多给我加了几块瘦肉

59
00:06:29,960 --> 00:06:32,640
还有呢 就是 我要了一块羊蝎子

60
00:06:32,640 --> 00:06:34,560
实际上 还多让了几块

61
00:06:34,560 --> 00:06:37,280
在此非常感谢他们

62
00:06:37,280 --> 00:06:39,680
这边基础的羊汤是15块钱

63
00:06:39,680 --> 00:06:42,960
如果说 想要多吃肉的话 可以自己再加钱

64
00:06:42,960 --> 00:06:45,560
像我呢就是 要了一碗20块钱的

65
00:06:45,560 --> 00:06:46,600
要完肉之后

66
00:06:46,600 --> 00:06:49,080
师傅会先把肉放在漏勺里

67
00:06:49,080 --> 00:06:52,840
然后用滚烫的羊汤来涮几下 冲几下

68
00:06:52,880 --> 00:06:54,880
最后呢 就是再放上羊汤

69
00:06:54,880 --> 00:06:57,280
看样子 真的是觉得特别香

70
00:06:57,280 --> 00:06:59,360
羊汤是没有味道的

71
00:06:59,360 --> 00:07:00,120
也没有膻味

72
00:07:00,120 --> 00:07:03,400
我们需要自己加盐 加胡椒粉

73
00:07:03,640 --> 00:07:06,400
肉就是 瘦的多 肥的少

74
00:07:06,400 --> 00:07:10,080
因为把肥的剔掉了嘛

75
00:07:10,080 --> 00:07:13,560
羊肉切的特别大块

76
00:07:19,280 --> 00:07:20,880
好香啊

77
00:07:20,880 --> 00:07:22,720
吃羊汤 配大饼

78
00:07:22,720 --> 00:07:25,080
一口汤 一口肉加口饼

79
00:07:25,080 --> 00:07:27,440
吃起来特别满足

80
00:07:44,120 --> 00:07:47,160
羊蝎子的肉 一吸溜就掉下来了

81
00:07:50,680 --> 00:07:52,000
五香味很足

82
00:08:06,480 --> 00:08:08,760
大姐 我问几个问题

83
00:08:08,760 --> 00:08:10,640
咱们原来在哪边干的

84
00:08:10,640 --> 00:08:13,400
以前 我以前赶大集卖羊肉汤

85
00:08:13,400 --> 00:08:15,920
就农村那5天一个的大集

86
00:08:15,920 --> 00:08:18,840
对 日照大集上的羊汤是很出名的

87
00:08:20,720 --> 00:08:23,840
顾客喜欢吃 他们说着玩 不是很出名

88
00:08:23,840 --> 00:08:26,320
比咱优秀的有的是

89
00:08:26,320 --> 00:08:30,960
什么时候到这边开的店

90
00:08:30,960 --> 00:08:34,320
三四年了可能是

91
00:08:34,840 --> 00:08:38,000
这边一天最多能卖多少羊

92
00:08:38,000 --> 00:08:40,760
以前一天 以前吧

93
00:08:40,760 --> 00:08:42,600
是能卖四五只 五六只

94
00:08:42,600 --> 00:08:46,720
现在吧 由于这个疫情反正卖的稍微少一点

95
00:08:48,440 --> 00:08:52,080
这个羊肉一定要切成这种大块大片的吗

96
00:08:52,080 --> 00:08:55,440
反正随意切 有时候切片 有时候切块

97
00:08:55,440 --> 00:08:58,800
没有什么很要求的

98
00:09:36,520 --> 00:09:39,560
现在我们在东夷小镇

99
00:10:01,960 --> 00:10:05,320
关 注
雪 鱼 探 店


```

**Comment by immoonancient** [comment]
@shuaisoserious 请前来认领

**Comment by shuaisoserious** [comment]
认领

**Comment by shuaisoserious** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
在山东喝羊肉汤有多豪迈！羊肉切大块，大舀子加汤，花20元吃得痛快
Look how grand it is to drink lamb soup in Shandong! Cut the mutton into large pieces, add the big ladle to the soup, eat it for 20 yuan
简介
好久没有出来喝汤了，这次来到离家2个小时的山东日照喝羊肉汤！这家店面没有很豪华的装修，
可以说是很破旧，来这家店的顾客主要是奔着味道来的，最低15元一碗肉，加汤免费，
大饼1元管够，咸菜免费自助！如果想多加一点肉，可以要20元，30元，甚至50元一碗的，都可以！
到了中午12点，顾客就像说好了似的一块都来了，排队是常有的事情，大厅里都坐满了人，想要找到一个空座还是不容易的。
一碗羊肉汤里，羊肉很大块，汤汁奶白色，吃一口肉喝一口汤，再就一口饼，真是很惬意的感觉。
Its been a long time I haven’t drink lamb soup, now we drink lamb soup in Rizhao, Shandong where drive 2 hours from home. There is no luxurious decoration in this restaurant,
I can say it is very shabby. The customers who come to this restaurant mainly for the taste. The minimum is 15 yuan per bowl of soup and meat, and add soup is free. The flatbread is for 1 yuan, and the pickles are free for self-service! If you want to add a little more lamb meat, you can ask for 20 yuan, 30 yuan, or even 50 yuan per bowl! At noon, customers came together, lining is a common thing, the hall is full of people, and it is not easy to find an empty seat. In a bowl of lamb soup, the lamb meat is very large and the soup is milky white. It is a very comfortable feeling to eat a bite of meat and drink a soup together
字幕
1
00:00:01,920 --> 00:00:06,360
山东·日照
Rizhao. Shandong
2
00:00:34,360 --> 00:00:37,320
大锅全羊
Huge pot of lamb soup
3
00:00:37,480 --> 00:00:42,240
现在是不到11点 她们都在忙碌着切羊肉
It’s less than 11 am now, they are busy to cutting lamb
4
00:00:42,240 --> 00:00:45,520
羊肉呢 要把肥的和瘦的分开来
They are splitting fatty and fatless lamb apart
5
00:00:45,520 --> 00:00:47,920
你看 那个肥的都会被她们剔掉
you see, they take fatty lamb away
6
00:00:47,920 --> 00:00:51,920
剩的羊肉就是瘦的多 肥的少
More fatless and less fatty in rest of lamb
7
00:00:51,920 --> 00:00:54,840
看这羊肉切的是不是很带劲
See how they cut the lamb?
8
00:01:00,520 --> 00:01:04,480
大姐 这边早上几点开门
Anut, what time is it open in the morning?
9
00:01:04,480 --> 00:01:06,880
6点 6点就开始喝羊肉汤了
Around six o’clock
10
00:01:06,880 --> 00:01:08,880
就喝羊肉汤了
    
11
00:01:08,880 --> 00:01:13,560
老板3点就开始熬汤
The restaurant owner start cooking soup at 3 am 
12
00:01:21,280 --> 00:01:24,440
你看 这边的羊肉切的都是很大块的
You see, they cut lamb into large pieces
13
00:01:24,440 --> 00:01:27,600
哇 这个羊骨头直接从肉上掰了下来
Wow, meat is easy to off the bone
14
00:01:54,480 --> 00:01:57,920
这边是一个大棚 可能来的比较早

15
00:01:57,920 --> 00:01:59,640
没有很多人在这边吃

16
00:01:59,640 --> 00:02:02,920
早上来吃的大部分人还是在室内吃的

17
00:02:02,960 --> 00:02:04,520
没想到今天天气这么热

18
00:02:04,520 --> 00:02:07,040
好像只有我穿的比较厚

19
00:02:50,200 --> 00:02:55,080
这个就是吃羊汤配的主食-大饼

20
00:02:59,120 --> 00:03:01,600
这边还有韭菜花和咸菜

21
00:03:01,600 --> 00:03:04,320
都是可以免费加的

22
00:03:04,320 --> 00:03:09,520
我后面就是正在炖的羊 全羊

23
00:03:09,520 --> 00:03:13,480
里面能够明显看到的是羊肉还有羊油

24
00:03:14,840 --> 00:03:18,120
这冒的大泡 看起来就特别香

25
00:03:42,920 --> 00:03:47,320
师傅 他们说羊蝎子11点之前有时候就会被抢光

26
00:03:47,320 --> 00:03:49,120
对

27
00:03:50,760 --> 00:03:52,520
羊蝎子多少钱
How much lamb spine is?
28
00:03:52,520 --> 00:03:54,280
3块一个
3 yuan for each
29
00:03:54,280 --> 00:03:55,800
那确实是很实惠
That’s really good price
30
00:03:55,800 --> 00:03:57,320
这个好吃
This is delicious 
31
00:03:59,200 --> 00:04:00,480
你吃个吧
Do you want one?
32
00:04:00,480 --> 00:04:02,200
现在不吃
Not yet
33
00:04:02,200 --> 00:04:04,880
还没到饭点
It’s not time to eat
34
00:04:27,760 --> 00:04:31,720
我要一个20的羊汤 再要一个羊骨髓
I want a 20 yuan lamb soup and a lamb bone marrow
35
00:04:36,600 --> 00:04:37,400
哦（还没有点饼）
Oh(forget to order a 
36
00:04:37,400 --> 00:04:40,240
哪有羊骨髓
We don’t have lamb bone marrow
37
00:04:40,240 --> 00:04:42,520
不是那个 羊蝎子
Not that one, I mean lamb spine
38
00:04:42,520 --> 00:04:43,480
羊蝎子
Lamb spine
39
00:04:43,480 --> 00:04:46,000
付了3块钱 买的是羊蝎子
Paid 3 yuan for a lamb spine
40
00:04:56,360 --> 00:05:00,040
再加一个大饼 忘了
And a flatbread
41
00:05:02,080 --> 00:05:04,000
你要6碗是吧
You want six bowls of lamb soup right?
42
00:05:04,560 --> 00:05:09,500
调料在你后面 是吧 6碗 120元
Condiments are behind you, 120 yuan for six bowls of lamb soup
43
00:05:11,560 --> 00:05:13,040
少一个怎么
Why there are only 5 bowls of soup
44
00:05:13,040 --> 00:05:15,680
二四六 少一碗
Two,four,six, less one bowl of soup
45
00:05:15,680 --> 00:05:16,960
不着急
Not in rush
46
00:05:16,960 --> 00:05:18,880
现在开始上人了
Now costumers are coming
47
00:05:18,880 --> 00:05:21,520
还没开始
Not yet
48
00:05:42,160 --> 00:05:44,360
再给你加两片瘦肉
I will add two more lean meat for you
49
00:05:44,360 --> 00:05:46,000
好 谢谢
Okay, thank you
50
00:05:46,000 --> 00:05:47,520
多给你点 尝尝
I will give you more meat, try it
51
00:05:48,000 --> 00:05:49,440
多吃点 你长那么瘦
Eat more meat, look how think you are
52
00:05:53,320 --> 00:05:55,720
现在等着加汤了
Now we are waiting for them to add soup
53
00:05:55,720 --> 00:05:57,280
自己舀吗
By your own?
54
00:06:12,800 --> 00:06:15,280
好 谢谢
Okay, thank you 
55
00:06:17,400 --> 00:06:20,040
拿着大饼走吧
Let’s take flatbread and find our seat
56
00:06:20,040 --> 00:06:24,760
看我们的羊汤 羊蝎子还有大饼都上桌了
Look, our lamb soup and lamb spine and flatbread are on table
57
00:06:26,360 --> 00:06:27,520
大姐觉得我有点瘦
Aunt think I’m thin
58
00:06:27,520 --> 00:06:29,960
所以 多给我加了几块瘦肉
So she add more lean meat for me
59
00:06:29,960 --> 00:06:32,640
还有呢 就是 我要了一块羊蝎子
And I order a lamb spine
60
00:06:32,640 --> 00:06:34,560
实际上 还多让了几块
They give me more than what I ordered
61
00:06:34,560 --> 00:06:37,280
在此非常感谢他们
So thanks for them
62
00:06:37,280 --> 00:06:39,680
这边基础的羊汤是15块钱
Basic soup is 15 yuan
63
00:06:39,680 --> 00:06:42,960
如果说 想要多吃肉的话 可以自己再加钱
Pay more money to get more meat
64
00:06:42,960 --> 00:06:45,560
像我呢 就是 要了一碗20块钱的
I order 20 yuan bowl of soup
65
00:06:45,560 --> 00:06:46,600
要完肉之后
After you order meat
66
00:06:46,600 --> 00:06:49,080
师傅会先把肉放在漏勺里
Shifu will put meat in a colander
67
00:06:49,080 --> 00:06:52,840
然后用滚烫的羊汤来涮几下 冲几下
And boiled it with hot lamb soup
68
00:06:52,880 --> 00:06:54,880
最后呢 就是再放上羊汤
Add lamb soup at the end
69
00:06:54,880 --> 00:06:57,280
看样子 真的是觉得特别香
Looks very delicious 
70
00:06:57,280 --> 00:06:59,360
羊汤是没有味道的
Original Lamb soup are insipid taste
71
00:06:59,360 --> 00:07:00,120
也没有膻味
And no tainted taste
72
00:07:00,120 --> 00:07:03,400
我们需要自己加盐 加胡椒粉
We need to add salt and pepper by our own
73
00:07:03,640 --> 00:07:06,400
肉就是 瘦的多 肥的少
There are less fatty and more lean meat
74
00:07:06,400 --> 00:07:10,080
因为把肥的剔掉了嘛
Because they take off fatty
75
00:07:10,080 --> 00:07:13,560
羊肉切的特别大块
They cut lamb meat into big pieces
76
00:07:19,280 --> 00:07:20,880
好香啊
Smells so fragment 
77
00:07:20,880 --> 00:07:22,720
吃羊汤 配大饼
Eat lamb soup with flatbread
78
00:07:22,720 --> 00:07:25,080
一口汤 一口肉加口饼
A bite of soup with a bite of flatbread
79
00:07:25,080 --> 00:07:27,440
吃起来特别满足
Feels good
80
00:07:44,120 --> 00:07:47,160
羊蝎子的肉 一吸溜就掉下来了
Meat of lamb spine is easy to take off the bone
81
00:07:50,680 --> 00:07:52,000
五香味很足
With rich wuxiang(five spiced) flavor
82
00:08:06,480 --> 00:08:08,760
大姐 我问几个问题
Big sis, I want ask you some questions
83
00:08:08,760 --> 00:08:10,640
咱们原来在哪边干的
Where the restaurant open before
84
00:08:10,640 --> 00:08:13,400
以前 我以前赶大集卖羊肉汤
I sale lamb soup at farmer market before
85
00:08:13,400 --> 00:08:15,920
就农村那5天一个的大集
Farmer market which open every five days
86
00:08:15,920 --> 00:08:18,840
对 日照大集上的羊汤是很出名的
Yeah, lamb soup in Rizhao farmer market are famous
87
00:08:20,720 --> 00:08:23,840
顾客喜欢吃 他们说着玩 不是很出名
Our customers like it, they just saying it, not very famous
88
00:08:23,840 --> 00:08:26,320
比咱优秀的有的是
We are not the best
89
00:08:26,320 --> 00:08:30,960
什么时候到这边开的店
When you open the restaurant here?
90
00:08:30,960 --> 00:08:34,320
三四年了可能是
About 3 or 4 years
91
00:08:34,840 --> 00:08:38,000
这边一天最多能卖多少羊
How many lamb are sale every day?
92
00:08:38,000 --> 00:08:40,760
以前一天 以前吧
We used sale 
93
00:08:40,760 --> 00:08:42,600
是能卖四五只 五六只
Four or five, five or six 
94
00:08:42,600 --> 00:08:46,720
现在吧 由于这个疫情反正卖的稍微少一点
But now we sale less due to the epidemic 
95
00:08:48,440 --> 00:08:52,080
这个羊肉一定要切成这种大块大片的吗
Do you have to cut lamb into big pieces or slices?
96
00:08:52,080 --> 00:08:55,440
反正随意切 有时候切片 有时候切块
It depend, we sliced or cut into pieces
97
00:08:55,440 --> 00:08:58,800
没有什么很要求的
Not necessary
98
00:09:36,520 --> 00:09:39,560
现在我们在东夷小镇
Now we are at Dongyi down
99
00:10:01,960 --> 00:10:05,320
关 注
雪 鱼 探 店
