### ISSUE TITLE
[华农兄弟] 华农兄弟摘点梅子来泡酒好多一树都是 - https://youtu.be/0Jpa9dYx1HI

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#921]
https://youtu.be/0Jpa9dYx1HI
<p>&#35270;&#39057;&#21457;&#24067;&#20110; April 16, 2020 at 12:33AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/0Jpa9dYx1HI

#华农兄弟：摘点梅子来泡酒，好多，一树都是
#Huanong Brothers: We pick some plums to make umeshu. A lot! All over the tree!

0:00:00.000,0:00:02.220
# 大家好  今天摘點這個梅子回去
Hi everyone! Today we're gonna pick some plums.

0:00:02.380,0:00:04.600
# 這個梅子還沒熟哦 我們先把它摘下來
The plums are still green. But we're gonna pick them first.

0:00:04.980,0:00:05.520
# 用來
Then we can,

0:00:05.940,0:00:07.300
# 用來那個  用來泡酒
we can, you know, we can make some umeshu (plum liquor).

0:00:07.600,0:00:09.700
# 現在這個梅子好酸  好澀
Now the plums are still very sour, and don't taste good at all.

0:00:10.380,0:00:13.160
# 但是這個用來做那個青梅酒是特別好的
But they are excellent for making umeshu.

0:00:14.800,0:00:16.260
# 聞聞都有它的那個香味
The fragrance is very significant.

0:00:16.520,0:00:17.600
# 它的香味已經出來啦
The fragrance is already there.

0:00:18.400,0:00:20.220
# 你看  這樹上  這樹上就有哦
Look! In this tree, you can see them in this tree.

0:00:20.800,0:00:21.720
# 你看  這裡有一個
Look! Here's one.

0:00:22.760,0:00:24.020
# 誒  是不是
Oy! Isn't it?

0:00:24.020,0:00:27.440
# 我在那裡看到了但是我太矮(摘不到)
I see a lot over there. But I'm too short.
You mean you can't pick?

0:00:27.460,0:00:30.580
# 我把你一扔扔到那裡去  掛到樹上  然後你就可以摘啦
Shall I throw you over there, so that you can pick whatever you want while you're hanging on the tree?

0:00:30.840,0:00:31.340
# 好不好
Shall I?

0:00:32.160,0:00:32.720
# 行不行
Isn't it a good idea?

0:00:33.840,0:00:34.440
# 行不行
Yes or no?

0:00:34.440,0:00:34.940
# 我
I ah...

0:00:35.180,0:00:35.680
# 行
yes...

0:00:36.000,0:00:36.640
# 行是不行
You said yes, didn't you?

0:00:37.100,0:00:39.660
# 好  我要上樹了  摘不到了這裡
Alright! I need to climb onto the  tree. I can't pick any here.

0:00:40.620,0:00:41.720
# 太高啦
It's too high.

0:00:42.340,0:00:42.960
# 這裡可以摘
I can pick some here.

0:00:42.960,0:00:44.140
# 你怎麼上去
How are you going to climb?

0:00:44.620,0:00:46.960
# 這裡可以把它拉下來  我拉下來你來摘好不好
I can pull it down here. I pull it down and then you pick the plums, alright?

0:00:47.100,0:00:47.600
# 嗯
Alright!

0:00:48.060,0:00:49.620
# 看到沒有  摘不摘的[SIC]到
Can you see them? Can you pick them?

0:00:53.120,0:00:54.240
# 這裡都好個
Here are a lot!

0:00:54.240,0:00:55.220
# 我要上去
I need to go up.

0:00:56.180,0:00:57.280
# 快點  你幫我接
C'mon! Take it for me.

0:00:59.680,0:01:02.320
# 你把那個袋口張開來  我來丟  (註︰那是魚網，但他說袋就袋吧)
Keep the bag open. I'm gonna throw it in.

0:01:06.040,0:01:07.020
# 看下還有沒有
Let me see if there are still any.

0:01:07.940,0:01:08.760
# 哪裡還有
Are there still any somewhere?

0:01:17.380,0:01:20.840
# 沒有了  沒有了換另外一棵樹枝  這裡
No more? No more, then let's move to another branch. Here.

0:01:24.720,0:01:25.640
# 走開走開
Go 'way, go 'way.

0:01:26.180,0:01:26.760
# 來
C'mon!

0:01:27.200,0:01:29.040
# 誒呦  長得矮
Ayo! I'm too short.

0:01:29.680,0:01:31.440
# 這些都沒摘到就飛走啦  (註︰沒看懂，唯有照字面譯)
These have already flown away before I can pick them.

0:01:35.800,0:01:36.580
# 還有
More!

0:01:39.340,0:01:40.040
# 誒呦
Ayo!

0:01:40.880,0:01:42.100
# 胡韋汝你敢不敢上樹
Hu Weiru, dare you climb the tree?

0:01:43.160,0:01:43.960
# 我不敢
No, I dare not.

0:01:46.280,0:01:48.320
# 你  你還敢啊
You, you still dare?

0:01:49.120,0:01:50.020
# 我肯定敢
Sure! Why not?

0:01:51.560,0:01:52.640
# 我有甚麼不敢的
Nothing can scare me.

0:01:53.960,0:01:55.360
# 爸爸  你敢不敢上
Daddy, do you dare to climb?

0:01:56.840,0:01:57.540
# 敢啊
Yup!

0:01:59.880,0:02:01.840
# 男生就敢上樹
The boys dare to climb.

0:02:03.540,0:02:07.220
# 我是女生  我 太小了  不會上樹
I'm a girl. I'm...too small. I can't climb.

0:02:09.380,0:02:11.000
# 我好怕我掉下來
I may fall. I'm scared.

0:02:11.580,0:02:14.000
# 你看這裡  好多啊  一樹都是
Look! Here are a lot, all over the tree.

0:02:16.240,0:02:17.760
# 今天我要泡一大缸
I'm gonna make a huge jar,

0:02:18.720,0:02:20.260
# 一  一大缸酒來
a, a huge jar of umeshu today.

0:02:23.040,0:02:26.680
# 剛好  這個帽派上用場啦  我口袋裡面都放滿啦
Good! This hat is finally useful now. My pockets are already full.

0:02:29.200,0:02:30.500
# 你看  這裡  好多
Look! Here are, a lot!

0:02:36.720,0:02:37.820
# 你看  全都是 
Look! All are,

0:02:38.140,0:02:38.900
# 很大的哦
really big, you know.

0:02:39.920,0:02:40.880
# 好靚
Beautiful!

0:02:42.560,0:02:43.680
# 帽子太小
The hat is too small.

0:02:44.440,0:02:45.560
# 帶個大帽子來
You should come with a bigger hat.

0:02:53.940,0:02:55.720
# 你看  現在這帽子都裝滿啦
Look! Now the hat is also full.

0:02:56.160,0:02:57.640
# 你的頭也不長大一點
Why don't you have a larger head?

0:02:58.220,0:02:59.360
# 摘的帽子那麼小
You hat is so tiny.

0:03:00.160,0:03:01.500
# 還有好多哦  你看上面
There are still a lot. Look, up there!

0:03:01.940,0:03:02.760
# 還有好多
There are still a lot.

0:03:03.360,0:03:04.780
# 我把那個拉過來摘
I'm gonna pull it to me.

0:03:07.780,0:03:09.520
# 又要保証自己的安全
But I still need to ensure my own safety.

0:03:11.700,0:03:14.920
# 所以要插在這裡  要不然就會  容易掉下去
So I need to stay between the branches, to prevent myself, from falling.

0:03:15.660,0:03:17.320
# 這樣插就不會掉下去啦
I won't fall when I'm between the branches.

0:03:25.360,0:03:25.940
# 好多  (註︰沒有原字幕)
A lot!

0:03:30.820,0:03:31.960
# 你看這個帽子
Have a look at the hat!

0:03:32.420,0:03:33.300
# 這個帽子都
The hat is already,

0:03:34.180,0:03:35.640
# 滿啦  全滿
already full, completely full.

0:03:37.500,0:03:39.340
# 要怪就怪這個帽子太小
It's too bad that the hat is far too small.

0:03:40.480,0:03:41.480
# 誒呀  又掉了一顆
Eya! I've dropped another one.

0:03:44.840,0:03:45.720
# 這個帽子
The hat...

0:03:47.280,0:03:48.680
# 先下去  先下去
Get down first, get down first.

0:03:49.120,0:03:50.180
# 下去先後我再上來
Get down first and then I'll come back.

0:03:50.720,0:03:51.840
# 我把這個空掉
Let me empty the hat first.

0:03:52.240,0:03:53.440
# 空掉之後我再上來
I'll come back after emptying it.

0:03:58.720,0:04:01.100
# 我們兩個也給我上來
Get down, you two guys!

0:04:01.100,0:04:01.780
# 別倒了哦
Don't drop it!

0:04:03.560,0:04:04.720
# 這樹上還有好多
There are still a lot in the tree.

0:04:05.920,0:04:06.640
# 這個還有
Here

0:04:18.700,0:04:19.560
# 準備下去啦
Let's get ready go get down.

0:04:20.140,0:04:21.040
# 不要搞太多
I don't need too many.

0:04:21.340,0:04:22.220
# 我又不喝酒
I don't drink any alcohol in fact.

0:04:23.840,0:04:25.040
# 我只是拿來送人
I just wanna give them out,

0:04:25.840,0:04:26.920
# 拿來給兄弟喝
to my buddy.

0:04:27.920,0:04:29.100
# 兄弟喝醉了就好
I wanna see him drunk.

0:04:29.880,0:04:30.880
# 好去他家玩
Then I can visit him.

0:04:31.540,0:04:32.780
# 這叫禮尚往來
This is called reciprocity.

0:04:35.680,0:04:36.640
# 兄弟不醉
Without a drunk buddy,

0:04:37.320,0:04:38.260
# 我都沒機會
I have no opportunity.

0:04:42.100,0:04:43.320
# 就摘了那麼一點點
So we have just a tiny little bit here.

0:04:44.460,0:04:45.060
# 不要啦
Enough!

0:04:46.040,0:04:47.440
# 回去 拿來
Let's go back, and make some,

0:04:48.220,0:04:49.140
# 拿來泡點酒
make some umeshu,

0:04:50.220,0:04:51.020
# 給兄弟喝
for my buddy.

0:04:51.600,0:04:54.040
# 我去兄弟家拿點酒來  泡這個梅子酒
Let me get some liquor from my buddy, to make the umeshu.

0:04:56.120,0:04:58.180
# 嗯  可以哦  很不錯
Um! Really not bad. Nice!

0:05:01.400,0:05:02.920
# 好  走啦走啦  回家啦
Alright! Let's go, let's go! Let's go home!

0:05:03.400,0:05:04.220
# 快點  你拿這個
C'mon! You take this.

0:05:04.780,0:05:05.580
# 我拿這個
And I take this.

0:05:07.340,0:05:09.200
# 把這個梅子放到這個瓶子上去
We put the plums into the jars.

0:05:10.240,0:05:10.880
# 放滿就好了
We just need to fill up each jar.

0:05:15.160,0:05:16.940
# 有蒂子的  壞的就不要啊
A stem. The rotten ones need to be thrown away, got it?

0:05:18.040,0:05:19.380
# 就這樣裝  裝這個
Just put them in. Put it here.

0:05:26.020,0:05:27.000
# 別推過來了啊
Don't push it to my side.

0:05:28.120,0:05:29.260
# 夠了  不用裝那麼滿
It's enough. Don't put too many.

0:05:29.920,0:05:31.180
# 我這個還沒裝滿
But this one is not yet full.

0:05:32.740,0:05:33.500
# 裝多一點
Put more then.

0:05:33.560,0:05:35.820
# 等我搞個大瓶子來   全部一起倒掉
Let me put them all into a big jar.

0:05:38.140,0:05:39.720
# 嗯  可以  不要裝那麼滿
Um! Alright! Not too many.

0:05:42.880,0:05:44.840
# 可以啦  你看  這些都是裝的差不多啦
Alright! Look! These are all almost full.

0:05:45.140,0:05:46.220
# 把這酒放下去
So I am pouring the liquor now.

0:05:48.320,0:05:50.000
# 我也想來放酒
I wanna pour the liquor too.

0:05:50.140,0:05:50.800
# 你不要玩
No way.

0:05:51.480,0:05:52.900
# 小孩子不能玩酒的啊
Kids should stay away from liquor, you know.

0:05:57.020,0:05:58.540
# 哇  好靚哦
Wa! Beautiful!

0:05:59.220,0:06:02.240
# 再加冰糖  這個冰糖  加幾顆冰糖下去
And rock sugar. This is rock sugar. Let me put a few pieces of rock sugar,

0:06:02.780,0:06:04.080
# 才不會那個酸
so that it won't be, you know, so sour.

0:06:05.960,0:06:07.320
# 這個聽老人家說的
That's what the elderly told us.

0:06:07.860,0:06:09.440
# 要不先把冰糖放下去
Alternatively, you can put in the rock sugar first.

0:06:09.440,0:06:10.780
# 我也想放冰糖
I wanna help with the rock sugar too.

0:06:10.780,0:06:12.060
# 你  你不能放  
No, no way.

0:06:13.360,0:06:14.320
# 你沒洗手
You haven't washed your hands.

0:06:14.760,0:06:15.780
# 我怕你把瓶子打
It's dangerous. You might drop,

0:06:16.340,0:06:17.040
# 打破啦
drop the jars.

0:06:20.160,0:06:21.940
# 你看  這樣就很靚了哦  這樣
Look! So it's really beautiful now, isn't it?

0:06:22.980,0:06:24.020
# 看上去都靚
It's simply eye catching.

0:06:29.060,0:06:31.120
# 你看  是不是  冰糖加酒
Look! See? Rock sugar with liquor.

0:06:39.780,0:06:40.740
# 誒  沒啦
Eh? No more?

0:06:41.200,0:06:42.120
# 就沒啦
No more?

0:06:43.020,0:06:44.480
# 你等一下  我再拿一瓶來
Wait! I'm gonna fetch one more bottle.

0:06:44.920,0:06:45.700
# 先把它蓋起來
Let me cover it first.

0:06:49.380,0:06:50.240
# 這就樣  你看
That's it! Look!

0:06:51.840,0:06:53.180
# 這個梅子酒就出來啦
So the umeshu is done.

0:06:58.960,0:06:59.520
# 你看
Look!

0:07:02.440,0:07:03.460
# 很漂亮哦
Pretty, isn't it?

0:07:04.440,0:07:06.040
# 看上去想不想吃這個  梅子
Do the plums look tasty? Do you wanna try them?

0:07:06.040,0:07:06.940
# 不想 為甚麼  (註︰想一句時間太短，Youtube字幕不能太短時間，所以兩句併在一起)
No.
Why not?

0:07:07.480,0:07:09.160
# 因為沒吃過
Cuz I've never tried before.

0:07:12.320,0:07:13.240
# 放在這裡先
Put them here first.

0:07:15.460,0:07:16.520
# 再去拿點酒來
I'm gonna get more liquor.

0:07:17.300,0:07:18.420
# 把這個蓋起來
Let me cover them.

0:07:35.980,0:07:37.060
# 看  合好啦
Look!
It's done!

0:07:38.100,0:07:38.920
# 靚哦
Beautiful!

0:07:41.080,0:07:41.940
# 青梅酒
Umeshu

0:07:46.280,0:07:47.920
# 你看  這樣就很漂亮了
Look! So it's really pretty.

0:07:49.260,0:07:50.100
# 這個梅子
The plums,

0:07:51.440,0:07:52.480
# 想都沒想到
could never think of that.

0:07:52.900,0:07:55.220
# 它以為我不  不吃它
They thought that I was not, not gonna eat them.

0:07:56.020,0:07:57.840
# 我拿來泡酒  我是不吃它
But you know what? I don't eat them. But I use them to make umeshu.

0:07:59.760,0:08:01.000
# 過兩天送給兄弟
I'll give it to my buddy in a few days.

0:08:01.620,0:08:02.660
# 你看  這些很靚了哦
Look! They're so beautiful, aren't they?

0:08:09.120,0:08:10.860
# 還聞不到酒味  到時候
I can't smell anything now. Later,

0:08:11.060,0:08:12.320
# 聞得到酒味到時候再來  (註︰我覺得這句是沒完的，再來甚麼，應該是沒有說下去)
later, when I can sense the aroma...

0:08:12.880,0:08:15.000
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.

0:08:16.080,0:08:17.500
# 過兩天給兄弟送過去
I'll take it to my buddy.
