### ISSUE TITLE
【美食作家王刚】懒人排骨 - https://youtu.be/mwaSbGZJtbA

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#924]
**视频链接**：https://youtu.be/mwaSbGZJtbA

视频时长 3:14，预计发布时间为北京时间4月19日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“懒人排骨”的真家常做法，口感很棒味道新颖，超简单的“糖醋排骨”做法

简介
同学们好，今天和大家分享第二道道“懒人”系列菜品“懒人排骨”，此菜一锅成菜，十分简单。但是味道却一点都不简单，和传统糖醋排骨味道接近，酸甜鲜样样不少，需要特别注意的是在收汁的时候一定要控制火候，以免过火变苦。如果大家想学习更加传统的糖醋排骨可以点击下面的链接，糖醋排骨饭店做法：https://www.youtube.com/watch?v=cgSM91WjyuY 糖醋排骨传统做法：https://www.youtube.com/watch?v=xPkN3tugpCQ

本期菜品:【懒人烧排骨】
【主料】
精排骨（500克）
【辅料】
食用面碱（约2克）
柠檬（半个）
生姜（1小块）
小葱（2根）
八角（1颗）
桂皮（1小块）
香叶（半片）
冰糖（约50克）
可乐（1000克）
【调味料】
食用盐（适量）
料酒（适量）
生抽酱油（20克）

字幕
0:00:00.300,0:00:01.460
哈喽大家好 我是王刚

0:00:01.460,0:00:03.520
本期视频我给大家分享一道家常菜

0:00:04.100,0:00:05.580
懒人烧排骨

0:00:06.000,0:00:08.200
首先我们准备精排骨500克

0:00:08.200,0:00:11.300
将排骨横着剁成3大块之后再切成小块备用

0:00:19.450,0:00:21.200
下一步开始处理排骨

0:00:21.425,0:00:23.100
盆中加入食用盐3勺（约6克）

0:00:27.825,0:00:29.500
加入食用面碱1小勺（约2克）

0:00:30.125,0:00:31.300
加入适量的料酒

0:00:33.700,0:00:35.700
然后将排骨抓洗5分钟

0:00:35.700,0:00:37.775
这一步是去除排骨中的血水

0:00:37.775,0:00:40.725
同学们加面碱抓洗可以让排骨变得更嫩

0:00:40.825,0:00:44.050
5分钟之后加入适量的清水将排骨清洗干净

0:00:51.275,0:00:53.875
清洗干净之后再用清水浸泡60分钟

0:00:53.875,0:00:56.100
这一步的目的是去除残留的杂质

0:00:56.100,0:00:58.750
嫌时间长的同学可以直接将排骨焯水

0:00:58.925,0:01:00.675
下一步开始调“懒人汁”

0:01:00.725,0:01:02.800
准备柠檬半个切成薄片备用

0:01:02.800,0:01:05.450
喜欢酸的同学也可以加入整个柠檬

0:01:06.050,0:01:08.300
准备生姜1小块切成姜片备用

0:01:10.250,0:01:12.250
准备小葱2根挽成结备用

0:01:17.425,0:01:18.975
碗中加入八角1颗

0:01:19.475,0:01:20.975
加入桂皮1小块

0:01:21.300,0:01:22.525
加入半块香叶

0:01:23.150,0:01:24.525
加入冰糖1小把（约50克）

0:01:25.275,0:01:26.900
加入生抽酱油20克

0:01:29.525,0:01:31.175
加入可乐1000克

0:01:33.375,0:01:35.025
最后加入食用盐1勺

0:01:35.300,0:01:38.700
可乐加盐除了增加泡沫之外还能刺激懒人的味觉

0:01:38.700,0:01:40.000
下一步开始制作

0:01:40.700,0:01:43.400
锅洗干净之后直接将调好的料汁下锅

0:01:53.075,0:01:55.200
然后加入处理好的排骨下锅

0:01:55.200,0:01:57.350
排骨下锅之后开大火烧开

0:02:06.200,0:02:08.575
大火烧开之后再撇去黑色的浮沫

0:02:08.575,0:02:10.525
然后转小火烧40分钟

0:02:10.525,0:02:13.150
这一步的目的是将排骨烧熟烧至入味

0:02:16.650,0:02:19.850
烧至30分钟的时候捡去姜葱柠檬和所有的辅料

0:02:21.175,0:02:23.075
然后转中火收汁6分钟

0:02:25.300,0:02:27.675
汤汁略干之后再转小火收4分钟

0:02:27.675,0:02:29.800
这一步的目的是把汤汁收浓

0:02:29.800,0:02:32.650
同学们切记最后收汁的时候不能开大火

0:02:32.650,0:02:34.275
否则非常容易烧糊

0:02:34.275,0:02:37.525
最后汤汁和糖浆收浓之后即可出锅摆盘

0:02:45.520,0:02:48.340
一道非常美味的懒人烧排骨就制作完成

0:02:53.380,0:03:13.680
下面开始技术总结
第一，喜欢有嚼劲的同学可以不用加面碱
第二，排骨最好选择中间的精排，这样成菜更香
第三，最后收汁必须小火防止糖浆收浓的时候烧糊
第四，此菜为简单版本的糖醋排骨特别适合家庭小灶操作
懒人烧排骨的技术总结完毕


```

**Comment by archerdominique** [comment]
bot, please upload
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“懒人排骨”的真家常做法，口感很棒味道新颖，超简单的“糖醋排骨”做法
Chef Wang Gang teaches you: the genuine home-made dish "the Lazy One's Braised Pork Ribs", the simple way of cooking sweet and sour pork ribs

简介
同学们好，今天和大家分享第二道道“懒人”系列菜品“懒人排骨”，此菜一锅成菜，十分简单。但是味道却一点都不简单，和传统糖醋排骨味道接近，酸甜鲜样样不少，需要特别注意的是在收汁的时候一定要控制火候，以免过火变苦。如果大家想学习更加传统的糖醋排骨可以点击下面的链接，糖醋排骨饭店做法：https://www.youtube.com/watch?v=cgSM91WjyuY 糖醋排骨传统做法：https://www.youtube.com/watch?v=xPkN3tugpCQ
Hello friends, today I would share with you the second dish of "The Lazy One's" series. This dish is so simple that it cooks all the ingredients together once in the wok, but the taste is not plain at all, not lacking any umami or the sweet and sour taste. What needs to be noticed in particular is that you need to be cautious about the heat when thickening the sauce. The taste would turns bitter if it is overcooked. If you want to know the genuine professional recipe you can watch the video in the link. The restaurant's way:https://www.youtube.com/watch?v=cgSM91WjyuY; the traditional way: https://www.youtube.com/watch?v=xPkN3tugpCQ

本期菜品:【懒人烧排骨】
Today's dish: The Lazy One's Braised Pork Ribs
【主料】
The main ingredients
精排骨（500克）
Lean pork ribs (500g)
【辅料】
The other ingredients
食用面碱（约2克）
Edible soda ash (about 2g)
柠檬（半个）
Lemon (a half)
生姜（1小块）
Ginger (a small lump)
小葱（2根）
Scallion*2
八角（1颗）
Star anise*1
桂皮（1小块）
Cinnamon (a small piece)
香叶（半片）
Bay leaf (half a leaf)
冰糖（约50克）
White rock sugar (about 50g)
可乐（1000克）
Cola (1kg)
【调味料】
(Seasoning ingredients)
食用盐（适量）
Salt to taste
料酒（适量）
Chinese cooking wine to taste
生抽酱油（20克）
Light soy sauce (20g)

字幕
0:00:00.300,0:00:01.460
哈喽大家好 我是王刚
Hi guys this is Wang Gang

0:00:01.460,0:00:03.520
本期视频我给大家分享一道家常菜
In today's video I'm gonna share with you a homely dish

0:00:04.100,0:00:05.580
懒人烧排骨
"The Lazy One's Braised Pork Ribs"

0:00:06.000,0:00:08.200
首先我们准备精排骨500克
First we get 500g of lean pork ribs

0:00:08.200,0:00:11.300
将排骨横着剁成3大块之后再切成小块备用
Chop the ribs into 3 large lumps and cut them into small pieces

0:00:19.450,0:00:21.200
下一步开始处理排骨
Next step is to prepare the ribs

0:00:21.425,0:00:23.100
盆中加入食用盐3勺（约6克）
3 spoons of salt (about 6g)

0:00:27.825,0:00:29.500
加入食用面碱1小勺（约2克）
a spoonful of edible soda ash (about 2g)

0:00:30.125,0:00:31.300
加入适量的料酒
With the appropriate amount of Chinese cooking wine

0:00:33.700,0:00:35.700
然后将排骨抓洗5分钟
Wash and clean the ribs for 5 minutes

0:00:35.700,0:00:37.775
这一步是去除排骨中的血水
This step is to remove the bloody fluid from the ribs

0:00:37.775,0:00:40.725
同学们加面碱抓洗可以让排骨变得更嫩
With the soda ash the ribs are made more tender

0:00:40.825,0:00:44.050
5分钟之后加入适量的清水将排骨清洗干净
After 5 minutes, put in enough water to rinse the ribs

0:00:51.275,0:00:53.875
清洗干净之后再用清水浸泡60分钟
After that, soak them in clear water for 60 minutes

0:00:53.875,0:00:56.100
这一步的目的是去除残留的杂质
The purpose of this step is to clean up the remaining impurities

0:00:56.100,0:00:58.750
嫌时间长的同学可以直接将排骨焯水
If the time is too long for you, you can go straight to parboil them

0:00:58.925,0:01:00.675
下一步开始调“懒人汁”
Next, let's make the "the Lazy One's sauce"

0:01:00.725,0:01:02.800
准备柠檬半个切成薄片备用
Half a lemon cut into thin slices

0:01:02.800,0:01:05.450
喜欢酸的同学也可以加入整个柠檬
If you prefer the sour taste you can use the whole lemon

0:01:06.050,0:01:08.300
准备生姜1小块切成姜片备用
A small lump of ginger cut into slices

0:01:10.250,0:01:12.250
准备小葱2根挽成结备用
Some scallions tied together as a knot

0:01:17.425,0:01:18.975
碗中加入八角1颗
A star anise into the bowl

0:01:19.475,0:01:20.975
加入桂皮1小块
With a small piece of cinnamon

0:01:21.300,0:01:22.525
加入半块香叶
and a half bay leaf

0:01:23.150,0:01:24.525
加入冰糖1小把（约50克）
Add a small handful of white rock sugar (about 50g)

0:01:25.275,0:01:26.900
加入生抽酱油20克
20g of light soy sauce

0:01:29.525,0:01:31.175
加入可乐1000克
1kg of cola

0:01:33.375,0:01:35.025
最后加入食用盐1勺
A spoonful of salt at last

0:01:35.300,0:01:38.700
可乐加盐除了增加泡沫之外还能刺激懒人的味觉
Putting salt to the cola can excite not only the foam but also the Lazy One's sense of taste 

0:01:38.700,0:01:40.000
下一步开始制作
Then let's start cooking

0:01:40.700,0:01:43.400
锅洗干净之后直接将调好的料汁下锅
After cleaning the wok put in the prepared sauce directly

0:01:53.075,0:01:55.200
然后加入处理好的排骨下锅
Drop in the ribs

0:01:55.200,0:01:57.350
排骨下锅之后开大火烧开
And boil the sauce in high heat

0:02:06.200,0:02:08.575
大火烧开之后再撇去黑色的浮沫
When it boils, remove the black scum

0:02:08.575,0:02:10.525
然后转小火烧40分钟
And turn to low heat, braise for 40 minutes

0:02:10.525,0:02:13.150
这一步的目的是将排骨烧熟烧至入味
The purpose is to cook the ribs thoroughly and let the flavour penetrate into the ribs

0:02:16.650,0:02:19.850
烧至30分钟的时候捡去姜葱柠檬和所有的辅料
When the time reaches 30 minutes pick out the ginger, scallions, lemons, and all other ingredients

0:02:21.175,0:02:23.075
然后转中火收汁6分钟
Turn to medium heat and thicken the sauce for 6 minutes

0:02:25.300,0:02:27.675
汤汁略干之后再转小火收4分钟
When the sauce is drying up, turn to low heat and keep it for 4 minutes

0:02:27.675,0:02:29.800
这一步的目的是把汤汁收浓
This is for making the sauce denser

0:02:29.800,0:02:32.650
同学们切记最后收汁的时候不能开大火
Never use a high heat when thickening the sauce

0:02:32.650,0:02:34.275
否则非常容易烧糊
Otherwise it is likely to be overcooked

0:02:34.275,0:02:37.525
最后汤汁和糖浆收浓之后即可出锅摆盘
After the sauce is thickened, you can prepare to serve the dish

0:02:45.520,0:02:48.340
一道非常美味的懒人烧排骨就制作完成
The very delicious braised ribs is finished

0:02:53.380,0:03:13.680
下面开始技术总结
Here are some technical summary
第一，喜欢有嚼劲的同学可以不用加面碱
First, there is no need for soda ash if you prefer the chewy texture
第二，排骨最好选择中间的精排，这样成菜更香
Second, it is better to use the lean ribs in the middle, which adds to the aroma and flavour of the dish
第三，最后收汁必须小火防止糖浆收浓的时候烧糊
Third, you must thicken the sauce in low heat to prevent overcooking
第四，此菜为简单版本的糖醋排骨特别适合家庭小灶操作
Four, this dish is the simplified version of cooking sweet and sour pork ribs, which is very suitable for homely cooking
懒人烧排骨的技术总结完毕
That's all for the technical tips
