### ISSUE TITLE
[老饭骨] 羊蝎子 - https://www.youtube.com/watch?v=1iVyvqEiuKU

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#925]
**视频链接**：https://www.youtube.com/watch?v=1iVyvqEiuKU

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•羊蝎子】史上最强酱汤羊蝎子秘方，保姆级教程，手把手教你做软烂脱骨又不膻的羊蝎子

简介
小友们好，熟悉老饭骨频道的可能都知道，老冯已经是咱们的熟人啦。
他是二伯徒弟，三叔熏酱传承人，同时还开了二十多家烤羊蝎子店。
今天老冯就要教大家如何做家常版的酱汤羊蝎子，可谓是倾囊相授，干货满满。
前两天还有小友在三叔羊棒骨的视频下面留言想看羊蝎子，今儿就来啦。
酱汤的酱都有哪些调料？如何处理羊蝎子的膻味？羊蝎子汤的最后绝招是啥？
小友们带着这些疑问赶紧看看视频吧，绝对看有所获，恨不得立马操练起来！
同时奉上之前烤羊排和羊棒骨视频链接⬇️
【零失败烤箱烤羊排】https://www.youtube.com/watch?v=Q24pqe4X5L4
【熏酱两吃羊棒骨】https://www.youtube.com/watch?v=U1e42yivylo

# import intro 请原样保留此行

字幕（需自制时间轴）
家常版的家常版的家常版的三句啊
酱汤羊蝎子
老冯呢 我给大家介绍一下
全国有了二十多家店的
老冯烤羊蝎子 他就是创始人
又是二伯的徒弟 又是我的传承人

话不多说 赶紧干活
这羊蝎子泡了几个小时
泡了六个小时 跑掉它的血水
咱们凉水下锅么 现在就可以下了
据说啊 在内蒙做羊肉人家不焯水
直接炖撇沫子
我们要是说现宰的羊可以这么做
现在基本上都宰完了进冷库冻了
冻完了之后这肉的颜色
还有腥膻味它会加重 说的有道理
那你这个汆羊蝎子不搁点别的料么
现在不用搁 第一步就是焯水
就是飞水 对
我不知道您注意到没注意到
这个是十二块 十二块羊蝎子是三斤
你看看 他现在拿数字了 搞数字化了
因为咱们家里边做 要是说蒙着投料
没有数字的概念它出来的味道
肯定是 有区别的
我不追求别的 我就追求味道
这也是我们老饭骨的精神
味道为王是不是
现在羊蝎子该逐步的往外出血沫了
还有一股味儿呢
我要如果做羊肉我是肯定搁醋的
我飞水直接就把它拿下去了
您教的这个我已经给它运用上了
现在这步咱们打完这个沫之后
再把您这个醋搁进去
然后它再开了 再挥发一下
要把羊肉的膻味邪味拿的干净一点
得把沫子打一下 打完了
只有大火的时候打沫子才打的干净
这个羊蝎子要是我们在店里边做
它得照着半个小时到四十分钟
连续不断的打沫子
那我现在就给你倒上 您看着搁
我看这么多就够了
你看这浑劲儿看见没有
全给它拿出来了
它还有什么道理再膻呢
一会我会教大家炒一个酱
这个口味不但我能掌握
只要咱们教了这个之后
每个人 你喜欢吃什么口味
最后定味儿的时候 炒酱这一步
您可以按照自己的个人喜好
能做出各式各样的羊蝎子的味道
那就这样就行了啊 现在可以了

用热水冲一下 要洗
咱家里边吃一定要把这个血沫
洗的干干净净的 你看看特别干净
现在北京做羊蝎子的也不少
它是外来货 羊蝎子是从天津传过来的
对从天津 但是从最早也是从内蒙
咱们现在弄好了啊
您看啊 这儿有几款料
有白芷 由良姜 有胡椒的这
就放这三味料就可以了
搁几个干辣椒 捏几个花椒粒 好 够了
一共是五味料 好了这咱就够了
然后加水 咱用矿泉水 可以
咱家里边吃咱要吃的讲究一点么
这水只要能给他没过来就行

羊肉呢我建议还是
按照（高压锅）这个时间三十分钟
因为它是带骨头的东西
因为咱们要让它脱骨
说的太对了 那咱们炒酱
网友们 今天咱们做个羊蝎子啊
咱们老冯是达人啊 跟你老冯一起学
家常版的家常版的家常版的三句啊
酱汤羊蝎子
因为这个油可以量大一点
它待会要涮菜 油大一点不碍事
这个油不要太热下去 让它凉一点
慢煸 煸出葱姜的香气
你说说刚才你放那几味料是起什么作用的
白芷是增香的 良姜是去腥膻味的
这里边最主要的料是胡椒 去腥解腻
这次我放的可不是胡椒粉 是胡椒粒
白胡椒粒
好 这葱见黄了 变成金黄色了
葱姜不炸 酱不够香么
这个酱有一点门道
我倒一半 回头您尝一口
您给品品这酱的味道 有点意思
这个酱这样炒一下就可以了
不要炒的太过 它的香味一出来就可以了
现在这样咱就可以放水了
长白山矿泉水 行了
这个酱汁咱就算熬好了
最后咱们就是一个调味的过程
这个酱是由三款酱组成的
黄豆酱 蚝油 还有一款最关键的柱候酱
但是柱候酱的量要小一些
咱们今天吃的是酱汤的
是以鲜味黄豆酱为主的
有几款香料是为了增加酱香的
八角 小茴香 干姜片 桂皮 丁香
在超市里边都能买的着
这几款是根据咱们自己的口味来调
料也不要太多 打碎了给它放到酱里边
调到一起就行了 最好呢就是
打碎了之后 调到酱里边给它焖两分钟
羊蝎子压熟了 然后再合到那个汤里边
这点儿也差不多了 咱羊肉也该出锅了
嘿 好 咱们起出来
您一块一块给它拣出来就成
一共十二块 别到时候炖完了剩十一块
时间火候掌握的刚刚好
你看 有弹性而且还脱骨
一杵进去了 这就叫正好
放心吧 好太棒了
老饭骨所有的人干活都细
今天咱们把这个原汤加进去
好吧 因为咱们这没有现成的骨汤
再加水这味儿就淡了
我不要上边这层油

（汤面）这就宽了
这回呢咱们调味 先不放盐
您先尝一下味道
因为咱们这个酱它本身就有咸味
相信三叔的力量 一勺半
稍微的给一点颜色（老抽）
因为这个汤色咱们不要它太红
因为这酱的颜色越煮越（深）
现在咱这个羊蝎子小火慢炖二十分钟
然后现在还有一个最关键的一步
您喜欢吃辣么
我要借它那个辣来压羊肉的膻味
这个小米辣不要切粒太大了
它挥发不出来辣味
一定切小薄圈 要精细点
小火慢炖 关小火 现在搁进去了啊
可以 最后的一招我得说说了
您看看这是什么 我看了半天像咖喱
好 放在里边就可以了 这就是对了
今天到您这儿来拍这个视频呢
咱们得拿出点干货来
三叔您看咱们做这个羊蝎子
我可一点没保留啊
按照您的要求 一定要说干货
老饭骨做任何菜
必须以强大的心态 正能量
来这锅台展示他的手艺
我们不许有瑕疵 在这里留一手
网友又不是傻子 我没必要留
四弟曾经说句话 味道就是王道
我们做的就是味道
再说四弟很帅啊
出锅吧 别砍啦 太棒啦
我教大家来检验这羊蝎子合格不合格
无论它怎么呢开锅 它清汤的不会乱
没那么多沫子 上面是油啊
然后它开起来之后你看它汤汁的粘稠度
还有透亮度 你看看
您就是加什么汤 怎么加
它也不会澥 好 灭火
现在这个羊蝎子
假如再搁到汤里边泡半小时 更好吃
```

**Comment by Laofangu** [comment]
家常版的家常版的家常版的三句啊
酱汤羊蝎子
老冯呢  我给大家介绍一下
全国有了二十多家店的
老冯烤羊蝎子  他就是创始人
又是二伯的徒弟  又是我的传承人

话不多说  赶紧干活
这羊蝎子泡了几个小时
泡了六个小时  跑掉它的血水
咱们凉水下锅么  现在就可以下了
据说啊 在内蒙做羊肉人家不焯水
直接炖撇沫子
我们要是说现宰的羊可以这么做
现在基本上都宰完了进冷库冻了
冻完了之后这肉的颜色
还有腥膻味它会加重  说的有道理
那你这个汆羊蝎子不搁点别的料么
现在不用搁  第一步就是焯水
就是飞水  对
我不知道您注意到没注意到
这个是十二块   十二块羊蝎子是三斤
你看看  他现在拿数字了  搞数字化了
因为咱们家里边做  要是说蒙着投料
没有数字的概念它出来的味道
肯定是  有区别的
我不追求别的  我就追求味道
这也是我们老饭骨的精神
味道为王是不是
现在羊蝎子该逐步的往外出血沫了
还有一股味儿呢
我要如果做羊肉我是肯定搁醋的
我飞水直接就把它拿下去了
您教的这个我已经给它运用上了
现在这步咱们打完这个沫之后
再把您这个醋搁进去
然后它再开了  再挥发一下
要把羊肉的膻味邪味拿的干净一点
得把沫子打一下  打完了
只有大火的时候打沫子才打的干净
这个羊蝎子要是我们在店里边做
它得照着半个小时到四十分钟
连续不断的打沫子
那我现在就给你倒上  您看着搁
我看这么多就够了
你看这浑劲儿看见没有
全给它拿出来了  
它还有什么道理再膻呢
一会我会教大家炒一个酱
这个口味不但我能掌握
只要咱们教了这个之后
每个人 你喜欢吃什么口味
最后定味儿的时候  炒酱这一步
您可以按照自己的个人喜好
能做出各式各样的羊蝎子的味道
那就这样就行了啊  现在可以了

用热水冲一下  要洗
咱家里边吃一定要把这个血沫
洗的干干净净的  你看看特别干净
现在北京做羊蝎子的也不少
它是外来货  羊蝎子是从天津传过来的
对从天津  但是从最早也是从内蒙
咱们现在弄好了啊  
您看啊  这儿有几款料
有白芷  由良姜  有胡椒的这
就放这三味料就可以了
搁几个干辣椒  捏几个花椒粒  好  够了
一共是五味料  好了这咱就够了
然后加水  咱用矿泉水  可以
咱家里边吃咱要吃的讲究一点么
这水只要能给他没过来就行

羊肉呢我建议还是
按照（高压锅）这个时间三十分钟
因为它是带骨头的东西
因为咱们要让它脱骨
说的太对了  那咱们炒酱
网友们 今天咱们做个羊蝎子啊
咱们老冯是达人啊  跟你老冯一起学
家常版的家常版的家常版的三句啊
酱汤羊蝎子
因为这个油可以量大一点
它待会要涮菜  油大一点不碍事
这个油不要太热下去  让它凉一点
慢煸 煸出葱姜的香气
你说说刚才你放那几味料是起什么作用的
白芷是增香的  良姜是去腥膻味的
这里边最主要的料是胡椒  去腥解腻
这次我放的可不是胡椒粉  是胡椒粒
白胡椒粒
好  这葱见黄了  变成金黄色了
葱姜不炸  酱不够香么
这个酱有一点门道  
我倒一半   回头您尝一口
您给品品这酱的味道  有点意思
这个酱这样炒一下就可以了
不要炒的太过  它的香味一出来就可以了
现在这样咱就可以放水了
长白山矿泉水  行了
这个酱汁咱就算熬好了
最后咱们就是一个调味的过程
这个酱是由三款酱组成的
黄豆酱  蚝油  还有一款最关键的柱候酱
但是柱候酱的量要小一些
咱们今天吃的是酱汤的 
是以鲜味黄豆酱为主的
有几款香料是为了增加酱香的
八角  小茴香  干姜片  桂皮  丁香
在超市里边都能买的着
这几款是根据咱们自己的口味来调
料也不要太多  打碎了给它放到酱里边
调到一起就行了  最好呢就是
打碎了之后  调到酱里边给它焖两分钟
羊蝎子压熟了  然后再合到那个汤里边
这点儿也差不多了  咱羊肉也该出锅了
嘿  好  咱们起出来
您一块一块给它拣出来就成
一共十二块  别到时候炖完了剩十一块
时间火候掌握的刚刚好
你看  有弹性而且还脱骨
一杵进去了  这就叫正好
放心吧  好太棒了
老饭骨所有的人干活都细
今天咱们把这个原汤加进去
好吧  因为咱们这没有现成的骨汤
再加水这味儿就淡了
我不要上边这层油

（汤面）这就宽了
这回呢咱们调味  先不放盐
您先尝一下味道
因为咱们这个酱它本身就有咸味
相信三叔的力量   一勺半
稍微的给一点颜色（老抽）
因为这个汤色咱们不要它太红
因为这酱的颜色越煮越（深）
现在咱这个羊蝎子小火慢炖二十分钟
然后现在还有一个最关键的一步
您喜欢吃辣么
我要借它那个辣来压羊肉的膻味
这个小米辣不要切粒太大了
它挥发不出来辣味
一定切小薄圈  要精细点
小火慢炖  关小火  现在搁进去了啊
可以  最后的一招我得说说了
您看看这是什么  我看了半天像咖喱
好  放在里边就可以了  这就是对了
今天到您这儿来拍这个视频呢
咱们得拿出点干货来
三叔您看咱们做这个羊蝎子
我可一点没保留啊
按照您的要求  一定要说干货
老饭骨做任何菜  
必须以强大的心态  正能量
来这锅台展示他的手艺
我们不许有瑕疵  在这里留一手
网友又不是傻子  我没必要留
四弟曾经说句话  味道就是王道
我们做的就是味道
再说四弟很帅啊
出锅吧  别砍啦  太棒啦
我教大家来检验这羊蝎子合格不合格
无论它怎么呢开锅  它清汤的不会乱
没那么多沫子  上面是油啊
然后它开起来之后你看它汤汁的粘稠度
还有透亮度  你看看
您就是加什么汤  怎么加  
它也不会澥  好  灭火
现在这个羊蝎子
假如再搁到汤里边泡半小时  更好吃

**Comment by immoonancient** [comment]
bot, please hint

**Comment by WuStevenShengyang** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•羊蝎子】史上最强酱汤羊蝎子秘方，保姆级教程，手把手教你做软烂脱骨又不膻的羊蝎子
State Banquet Master Chef·Lamb Spines: Lamb Spine Hot Pot in Bean Sauce.

简介
小友们好，熟悉老饭骨频道的可能都知道，老冯已经是咱们的熟人啦。
Hey friends, if you have been following our channel, you should be familiar with our friend Feng.
他是二伯徒弟，三叔熏酱传承人，同时还开了二十多家烤羊蝎子店。
He is Er Bo's disciple, and San Shu's successor. He has also opened more than twenty lamb spine restaurant in China.
今天老冯就要教大家如何做家常版的酱汤羊蝎子，可谓是倾囊相授，干货满满。
Feng will teach us how to make Lamb Spine Hot Pot in Bean Sauce at home. This video is full of real and useful skill.
前两天还有小友在三叔羊棒骨的视频下面留言想看羊蝎子，今儿就来啦。
Previouly, people have commented that they want to see how we make lamb spines. Here it comes.
酱汤的酱都有哪些调料？如何处理羊蝎子的膻味？羊蝎子汤的最后绝招是啥？
How to make out sacue? How do we get rid of lamb's taint? What are some secret tips when making the broth?
小友们带着这些疑问赶紧看看视频吧，绝对看有所获，恨不得立马操练起来！
If you have these questions, watch the video and you will love try it yourself.
同时奉上之前烤羊排和羊棒骨视频链接⬇️
Below are the links to the previous lamb chops and lamb bones:
【零失败烤箱烤羊排】https://www.youtube.com/watch?v=Q24pqe4X5L4
Lamb Chops: https://www.youtube.com/watch?v=Q24pqe4X5L4
【熏酱两吃羊棒骨】https://www.youtube.com/watch?v=U1e42yivylo
Lamb bones: https://www.youtube.com/watch?v=U1e42yivylo

字幕
import intro

0:00:00.000,0:00:03.480
家常版的家常版的家常版的三句啊
Homemade, homemade, homemade, I will say it three times in a row.

0:00:03.780,0:00:04.780
酱汤羊蝎子
Lamb Spine Hot Pot in Bean Sauce.

0:00:04.780,0:00:06.340
老冯呢 我给大家介绍一下
Let me introduce to you guys. This is Feng.

0:00:06.660,0:00:07.880
全国有了二十多家店的
Has more than 20 restaurants around China,

0:00:08.080,0:00:10.000
老冯烤羊蝎子 他就是创始人
he is the founder of Feng's Lamb Spine.

0:00:10.280,0:00:12.380
又是二伯的徒弟 又是我的传承人
He is also Er Bai's disciple, and my successor.

0:00:14.725,0:00:17.225
话不多说 赶紧干活
Let's get to work!

0:00:17.225,0:00:18.300
这羊蝎子泡了几个小时
Those lamb spines have been soaked in water for hours.

0:00:18.380,0:00:21.400
泡了六个小时 泡掉它的血水
Six hours, this will remove the blood from the lamb.

0:00:21.400,0:00:23.960
咱们凉水下锅么 现在就可以下了
Do we just put those in while the water is cold? Yes.

0:00:24.100,0:00:27.200
据说啊 在内蒙做羊肉人家不焯水
In Inner Mongolia, people cook lamb without even parboiling.

0:00:27.400,0:00:28.460
直接炖撇沫子
Just simmer it right away and remove the blood foam.

0:00:28.460,0:00:31.280
我们要是说现宰的羊可以这么做
Yes, but this only works for freshly-butchered lamb.

0:00:31.520,0:00:33.980
现在基本上都宰完了进冷库冻了
Most of the lambs nowadays, however, will be refrigerated after butchering.

0:00:34.840,0:00:36.760
冻完了之后这肉的颜色
Doing so will affect the lamb's color,

0:00:36.940,0:00:41.595
还有腥膻味它会加重 说的有道理
and intensify the taints. Yes, you are right.

0:00:41.595,0:00:44.865
那你这个汆羊蝎子不搁点别的料么
Aren't we going to add any spicies?

0:00:44.865,0:00:46.460
现在不用搁 第一步就是焯水
Not yet, we are just parboiling.

0:00:46.620,0:00:47.620
就是飞水 对
Just parboiling? Yes.

0:00:47.920,0:00:49.780
我不知道您注意到没注意到
I don't know if you have noticed,

0:00:50.140,0:00:55.220
这个是十二块 十二块羊蝎子是三斤
There are twelve chunks of spines, which are about 1.5kg.

0:00:55.220,0:00:58.120
你看看 他现在拿数字了 搞数字化了
Yea, they actually use accurate measurements right now.

0:00:58.120,0:01:01.940
因为咱们家里边做 要是说蒙着投料
We won't know how much ingredient to add,

0:01:02.220,0:01:04.180
没有数字的概念它出来的味道
if we don't know exactly how much lamb we are getting.

0:01:04.480,0:01:06.620
肯定是 有区别的
That will make a difference, definitely.

0:01:06.960,0:01:09.400
我不追求别的 我就追求味道
I don't ask for much, but taste.

0:01:09.760,0:01:12.580
这也是我们老饭骨的精神
This is also the spirit of Lao Fan Gu.

0:01:13.000,0:01:14.440
味道为王是不是
Taste is the key.

0:01:14.440,0:01:19.140
现在羊蝎子该逐步的往外出血沫了
Now, the blood foams are coming out of the spines,

0:01:19.140,0:01:20.445
还有一股味儿呢
along with an unpleasant smell.

0:01:20.445,0:01:22.900
我要如果做羊肉我是肯定搁醋的
I will add vinegar for sure，

0:01:23.140,0:01:24.980
我飞水直接就把它拿下去了
when parboiling.

0:01:25.520,0:01:27.980
您教的这个我已经给它运用上了
I have implemented what you have taught me.

0:01:27.980,0:01:31.360
现在这步咱们打完这个沫之后
After we clean up the blood foams,

0:01:31.360,0:01:34.040
再把您这个醋搁进去
we will add some vinegar.

0:01:34.300,0:01:36.660
然后它再开了 再挥发一下
Not it starts to boil, we will let it volatilize further,

0:01:36.660,0:01:41.500
要把羊肉的膻味邪味拿的干净一点
removing the taint even more.

0:01:41.760,0:01:43.420
得把沫子打一下 打完了
We have to clean up the blood foams.

0:01:45.180,0:01:48.540
只有大火的时候打沫子才打的干净
It is best to clean the foams on high heat.

0:01:48.640,0:01:51.060
这个羊蝎子要是我们在店里边做
If I were to cook lamb spines in my restaurant,

0:01:51.240,0:01:53.940
它得照着半个小时到四十分钟
they have to be parboiled for at least 30 to 40 minutes,

0:01:53.940,0:01:55.420
连续不断的打沫子
while cleaning up the foams constantly.

0:01:55.420,0:01:58.100
那我现在就给你倒上 您看着搁
Now I will add vinegar. Sure.

0:01:59.120,0:02:00.200
我看这么多就够了
I think this should be enough.

0:02:00.380,0:02:01.700
你看这浑劲儿看见没有
See? All the foams

0:02:01.960,0:02:03.940
全给它拿出来了
are coming out.

0:02:04.440,0:02:06.600
它还有什么道理再膻呢
There will be no taint at all in our lamb.

0:02:06.860,0:02:08.700
一会我会教大家炒一个酱
Later, I will teach you guys how to make a sauce for this dish.

0:02:09.120,0:02:11.740
这个口味不但我能掌握
Now only I can master the taste,

0:02:12.040,0:02:14.240
只要咱们教了这个之后
if you do what I teach you,

0:02:14.500,0:02:16.255
每个人 你喜欢吃什么口味
no matter what flavor you like,

0:02:16.260,0:02:19.580
最后定味儿的时候 炒酱这一步
you can make any type of sauce

0:02:19.580,0:02:21.940
您可以按照自己的个人喜好
base on your preference.

0:02:22.040,0:02:24.520
能做出各式各样的羊蝎子的味道
And therefore you can make various favors' lamb spines.

0:02:24.520,0:02:27.140
那就这样就行了啊 现在可以了
The lambs should be good now.

0:02:29.000,0:02:31.280
用热水冲一下 要洗
We have to rinse them under hot water.

0:02:31.500,0:02:34.180
咱家里边吃一定要把这个血沫
If we cook lamb spine at home,

0:02:34.640,0:02:38.720
洗的干干净净的 你看看特别干净
we have to clean up the blood foams completely. See they are so clean.

0:02:39.160,0:02:40.440
现在北京做羊蝎子的也不少
There are a lot of restaurants in Beijing that make lamb spines how pot.

0:02:40.445,0:02:43.175
它是外来货 羊蝎子是从天津传过来的
However, this dish came from Tianjin. 

0:02:43.180,0:02:45.640
对从天津 但是从最早也是从内蒙
Yes, but it originates in Inner Mongolia.

0:02:45.820,0:02:46.820
咱们现在弄好了啊
Now we are done with the spines.

0:02:46.820,0:02:49.540
您看啊 这儿有几款料
As you can see, we have some spices here.

0:02:49.540,0:02:52.155
有白芷 有良姜 有胡椒的这
We have angelica roots, galangals, and peppercorns. 

0:02:52.155,0:02:53.845
就放这三味料就可以了
Those three.

0:02:54.480,0:02:59.480
搁几个干辣椒 捏几个花椒粒 好 够了
We can also put in some dried chili pepper, and some Sichuan peppercorns.

0:02:59.620,0:03:02.640
一共是五味料 好了这咱就够了
So we will have a total of five different spices.

0:03:02.940,0:03:05.860
然后加水 咱用矿泉水 可以
And then, add some water. We will use spring water. Sure

0:03:05.940,0:03:08.580
咱家里边吃咱要吃的讲究一点么
We have to be fastidious in our home.

0:03:10.460,0:03:12.700
这水只要能给他没过来就行
The water has to immerse the spices.

0:03:13.980,0:03:16.260
羊肉呢我建议还是
As for the lamb spines,

0:03:16.440,0:03:17.980
按照（高压锅）这个时间三十分钟
we will cook them in a pressure cooker for 30 minutes.

0:03:18.300,0:03:19.920
因为它是带骨头的东西
Since spines have bones,

0:03:20.180,0:03:21.320
因为咱们要让它脱骨
this process will sepearate the meat and the bones.

0:03:23.040,0:03:24.940
说的太对了 那咱们炒酱
Exactly! Now let's make the sauce.

0:03:25.120,0:03:28.140
网友们 今天咱们做个羊蝎子啊
Guys, today we are making lamb spine hot pot.

0:03:28.360,0:03:31.320
咱们老冯是达人啊 跟你老冯一起学
And Feng is such a master at making this dish, you have to learn from him.

0:03:31.540,0:03:34.840
家常版的家常版的家常版的三句啊
Homemade, homemade, homemade, I will say it three times in a row.

0:03:35.240,0:03:37.360
酱汤羊蝎子
Lamb Spine Hot Pot in Bean Sauce.

0:03:37.700,0:03:40.160
因为这个油可以量大一点
We can add a generous amount of oil,

0:03:40.420,0:03:44.420
它待会要涮菜 油大一点不碍事
since we will use it to fry our spices.

0:03:44.880,0:03:47.340
这个油不要太热下去 让它凉一点
We don't have to wait until the oil heats up thoroughly.

0:03:47.600,0:03:50.180
慢煸 煸出葱姜的香气
Just slowly fry them untio aromatic.

0:03:51.260,0:03:53.560
你说说刚才你放那几味料是起什么作用的
Can you tell us the purpose of each spice?

0:03:54.020,0:03:57.640
白芷是增香的 良姜是去腥膻味的
angelica roots creates aroma, galangal removes the taints.

0:03:57.860,0:04:01.120
这里边最主要的料是胡椒 去腥解腻
Peppercorns will cut down the grease of the lamb.

0:04:01.120,0:04:03.840
这次我放的可不是胡椒粉 是胡椒粒
I am using peppercorns instead of powder.

0:04:04.180,0:04:05.260
白胡椒粒
White peppercorns.

0:04:05.760,0:04:07.940
好 这葱见黄了 变成金黄色了
Good, the green onions are turning golden.

0:04:08.460,0:04:11.440
葱姜不炸 酱不够香么
If we don't fry the green onions and ginger, the sauce won't be fragrant enough.

0:04:12.000,0:04:14.140
这个酱有一点门道
This sauce is special.

0:04:14.560,0:04:16.560
我倒一半 回头您尝一口
You should taste it.

0:04:17.380,0:04:22.080
您给品品这酱的味道 有点意思
You try it. Hm, interesting.

0:04:22.340,0:04:23.740
这个酱这样炒一下就可以了
We just fry the sauce like this.

0:04:24.000,0:04:26.960
不要炒的太过 它的香味一出来就可以了
Don't overcook it as long as it turns fragrant.

0:04:27.360,0:04:28.820
现在这样咱就可以放水了
Now, we can add water.

0:04:29.580,0:04:32.500
长白山矿泉水 行了
Paektu Mountain Spring Water. Good.

0:04:32.760,0:04:34.760
这个酱汁咱就算熬好了
And we are done with the sauce.

0:04:35.120,0:04:37.420
最后咱们就是一个调味的过程
Lastly, we will start seasoning.

0:04:37.600,0:04:40.700
这个酱是由三款酱组成的
This sauce is a combination of three other different sauces.

0:04:41.060,0:04:44.640
黄豆酱 蚝油 还有一款最关键的柱候酱
Yellow bean paste, oyster sauce, and Zhuhou sauce.

0:04:45.160,0:04:47.080
但是柱候酱的量要小一些
Remember, we can't add too much Zhuhou sauce.

0:04:47.500,0:04:49.660
咱们今天吃的是酱汤的
Since we are making bean sauce lamb spine,

0:04:50.160,0:04:51.600
是以鲜味黄豆酱为主的
the flavor should be centered around the yellow bean sauce.

0:04:51.760,0:04:54.560
有几款香料是为了增加酱香的
We have some other spices to enhance the fragrance.

0:04:54.560,0:04:57.940
八角 小茴香 干姜片 桂皮 丁香
Star anise, fennel seeds, dried ginger slices, cinnamons, and cloves.

0:04:57.940,0:04:59.240
在超市里边都能买的着
You can find them in a grocery store.

0:04:59.240,0:05:02.060
这几款是根据咱们自己的口味来调
You can adjust the amount of each spice base on your own preference.

0:05:02.120,0:05:04.720
料也不要太多 打碎了给它放到酱里边
However, don't add too much. We will blend them and add into the sauce.

0:05:04.720,0:05:06.620
调到一起就行了 最好呢就是
We better put all of them together.

0:05:06.920,0:05:09.980
打碎了之后 调到酱里边给它焖两分钟
After blending the spices, we will add them in the sauce and simmer for two minutes.

0:05:10.160,0:05:14.420
羊蝎子压熟了 然后再合到那个汤里边
After the spines finish cooking, we will add the sauce into the lamb broth.

0:05:14.700,0:05:17.120
这点儿也差不多了 咱羊肉也该出锅了
The lamb is almost done.

0:05:17.915,0:05:20.555
嘿 好 咱们起出来
Good. Let's take them out.

0:05:20.760,0:05:22.640
您一块一块给它拣出来就成
You can take them out one by one.

0:05:22.640,0:05:25.200
一共十二块 别到时候炖完了剩十一块
There should be 12 pieces total.

0:05:25.520,0:05:27.075
时间火候掌握的刚刚好
Time and heat are just right.

0:05:27.080,0:05:31.300
你看 有弹性而且还脱骨
See, the meat is seperated from the bones.

0:05:31.480,0:05:35.600
一杵进去了 这就叫正好
I can even stick a chopstick in. This is perfection.

0:05:35.600,0:05:38.500
放心吧 好太棒了
It's so good.

0:05:40.460,0:05:42.580
老饭骨所有的人干活都细
Everyone in Lao Fan Gu works with responsibility and carefulness.

0:05:43.860,0:05:47.600
今天咱们把这个原汤加进去
Today, we will add the lamb broth into the sauce,

0:05:47.720,0:05:49.800
好吧 因为咱们这没有现成的骨汤
since we don't have pre-made stock,

0:05:50.120,0:05:51.780
再加水这味儿就淡了
and adding water will dilute the flavor.

0:05:52.140,0:05:53.220
我不要上边这层油
I don't want the oil on the surface.

0:05:59.840,0:06:00.840
（汤面）这就宽了
Now the soup surface is getting broad.

0:06:03.260,0:06:05.885
这回呢咱们调味 先不放盐
As for seasoning, we won't add salt yet.

0:06:05.885,0:06:07.300
您先尝一下味道
You should taste it first.

0:06:07.440,0:06:09.880
因为咱们这个酱它本身就有咸味
Our sauce is salty already.

0:06:13.480,0:06:16.420
相信三叔的力量 一勺半
Trust San Shu, one and a half tablespoon of salt is enough.

0:06:16.420,0:06:17.760
稍微的给一点颜色（老抽）
Add some dark soysauce to give it some color.

0:06:17.980,0:06:21.400
因为这个汤色咱们不要它太红
The broth shouldn't be too dark right now,

0:06:21.400,0:06:23.140
因为这酱的颜色越煮越（深）
because the sauce gets darker the longer we boil it.

0:06:23.140,0:06:27.495
现在咱这个羊蝎子小火慢炖二十分钟
Now we will simmer the spines on low heat for 20 minutes.

0:06:27.500,0:06:30.545
然后现在还有一个最关键的一步
Here comes a key step.

0:06:30.640,0:06:31.860
您喜欢吃辣么
Do you like spicy food?

0:06:32.200,0:06:35.440
我要借它那个辣来压羊肉的膻味
I will use the spiciness to compensate the lamb's taints.

0:06:35.680,0:06:38.440
这个小米辣不要切粒太大了
Remember, don't cut the "Xiaomila" chili pepper too big.

0:06:38.440,0:06:40.040
它挥发不出来辣味
Cutting them too big won't bring out the spiciness.

0:06:40.240,0:06:44.020
一定切小薄圈 要精细点
We have to cut them into small, thing rings.

0:06:44.440,0:06:46.560
小火慢炖 关小火 现在搁进去了啊
Turn off the stove and add in the chili.

0:06:47.180,0:06:50.520
可以 最后的一招我得说说了
Nice. Now comes the final step.

0:06:50.740,0:06:53.040
您看看这是什么 我看了半天像咖喱
Do you know what this is? It looks like curry chunks.

0:06:53.360,0:06:57.420
好 放在里边就可以了 这就是对了
Add the curry chunks in.

0:06:57.420,0:07:00.460
今天到您这儿来拍这个视频呢
Today I am comming here to make this video.

0:07:00.460,0:07:02.165
咱们得拿出点干货来
So I have to teach you some real cooking skills.

0:07:02.165,0:07:04.945
三叔您看咱们做这个羊蝎子
San Shu, as for this dish, I have taught everything I can to the audience,

0:07:04.945,0:07:06.920
我可一点没保留啊
with nothing else left.

0:07:07.080,0:07:09.780
按照您的要求 一定要说干货
As you mentioned, real skill.

0:07:10.240,0:07:12.380
老饭骨做任何菜
Any dish that Lao Fan Gu makes,

0:07:13.060,0:07:16.380
必须以强大的心态 正能量
must come from the chef's positive attitude and energy,

0:07:16.560,0:07:18.880
来这锅台展示他的手艺
to show his skill

0:07:19.080,0:07:22.620
我们不许有瑕疵 在这里留一手
We won't allow any mistakes or reservation.

0:07:23.140,0:07:25.560
网友又不是傻子 我没必要留
Our audience aren't dumb. Yea, and I don't need to reserve anything.

0:07:25.560,0:07:28.260
四弟曾经说句话 味道就是王道
Si Di once said: Taste is the key.

0:07:28.260,0:07:29.660
我们做的就是味道
And we are aiming for better tastes of each dish.

0:07:29.840,0:07:31.500
再说四弟很帅啊
And, by the way, Si Di is quite handsome.

0:07:31.720,0:07:34.740
出锅吧 别砍啦 太棒啦
Well that's enough chatting. Let's take out the spines. Looks amazing.

0:07:34.980,0:07:38.335
我教大家来检验这羊蝎子合格不合格
Let me tell how to examine the spine's quality.

0:07:38.340,0:07:41.820
无论它怎么呢开锅 它清汤的不会乱
The broth should be clear all the time.

0:07:41.820,0:07:44.640
没那么多沫子 上面是油啊
There are grease on the surface, not blood foams.

0:07:44.760,0:07:48.740
然后它开起来之后你看它汤汁的粘稠度
You see the stickness of the broth,

0:07:49.240,0:07:51.680
还有透亮度 你看看
and transparency. See?

0:07:51.680,0:07:53.560
您就是加什么汤 怎么加
You can add as many broth as you prefer,

0:07:53.800,0:07:55.680
它也不会澥 好 灭火
without breaking it down. We can turn off the stove.

0:07:55.860,0:07:57.020
现在这个羊蝎子
Now,

0:07:57.320,0:08:00.760
假如再搁到汤里边泡半小时 更好吃
if we soak the spines in this sauce for an extra 30 minutes, they will taste even better.

# import ending.srt 00:08:10,000
