### ISSUE TITLE
【美食作家王刚】 用料包做麻辣小龙虾 - https://youtu.be/w4yTV9WwPLA

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#926]
**视频链接**：https://youtu.be/w4yTV9WwPLA

视频时长7:51，预计发布时间为北京时间4月20日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：用料包做“麻辣小龙虾”的做法，详解如何去虾线，味道巴适，好吃得停不下来

简介
大家好，之前有朋友买了小龙虾料包但是不太会用，今天就来现场教学一下，并且再详细教一下大家如何给小龙虾去虾线。首先就是准备洗净的小龙虾，然后抓住小龙虾头部，怕被夹的朋友可以带上橡胶手套，然后用另一只手转动龙虾尾中间的部分，最后将虾线抽出即可。最后如果使用料包的话就只用准备好姜葱蒜和喜欢的配料炒制即可，并且此料包还可以用来制作炒田螺，烤鱼，干锅等菜品。

很抱歉海外的朋友暂时可能没有办法买到我的产品，但是也不能阻止吃货的脚步，没有料包的朋友可以看我之前的小龙虾教学，不需要料包也没问题：麻辣小龙虾 https://www.youtube.com/watch?v=DGmPpeDbjBg 十三香小龙虾 https://www.youtube.com/watch?v=JRawQBCkQ34 蒜蓉小龙虾 https://www.youtube.com/watch?v=2EaiAdYI0tY

字幕
0:00:00.225,0:00:01.350
哈喽 大家好

0:00:01.425,0:00:03.350
前段时间我们粉丝买了

0:00:03.575,0:00:06.325
我们自己做的这个小龙虾（调料）回家他不会用

0:00:06.325,0:00:10.950
今天我们就用这个来现场烧一个来试验一下

0:00:11.025,0:00:12.300
这里面有三包

0:00:13.182,0:00:15.182
这个龙虾在那个养殖场买的

0:00:15.325,0:00:16.125
特别干净

0:00:16.850,0:00:18.475
特别干净的一个小龙虾

0:00:18.625,0:00:20.125
然后就用一包来烧

0:00:20.650,0:00:21.950
我把虾线去了都

0:00:23.025,0:00:23.600
看

0:00:23.900,0:00:26.000
这是根啥子嘛

0:00:26.275,0:00:29.013
这根就是它(龙虾）这个肠子

0:00:29.013,0:00:30.725
你看嘛 这

0:00:30.875,0:00:32.625
我来抽哈看抽得来不

0:00:32.900,0:00:34.150
小心它要咬到你哦

0:00:34.225,0:00:35.925
它咬得到我呀

0:00:38.400,0:00:39.975
我都学会了

0:00:40.700,0:00:43.825
今天我们来试验一下3斤龙虾到底有多少个

0:00:43.875,0:00:46.450
等一下我们弄完了就数一下

0:00:46.675,0:00:48.100
两边给它扯住给它拨一下

0:00:48.125,0:00:49.775
扭一下 抓到扭一下

0:00:51.125,0:00:51.950
就把它整出来了

0:00:52.225,0:00:53.400
最后一个

0:00:53.625,0:00:55.050
这个还比较顽固

0:00:55.850,0:00:56.750
最后一个出来了

0:00:56.950,0:00:57.900
我数一哈看有好多个

0:00:57.950,0:00:58.875
我去拿筷子来

0:00:59.100,0:01:00.240
害怕它夹到手

0:01:00.240,0:01:01.525
哪干哦

0:01:02.327,0:01:03.909
夹到它痛得很 四伯爷

0:01:04.764,0:01:07.589
2个3个4个

0:01:08.060,0:01:11.173
17 18 19  20

0:01:11.402,0:01:13.141
52 54  56

0:01:14.293,0:01:14.968
三斤

0:01:15.860,0:01:17.807
一斤20个都没得哦

0:01:18.299,0:01:19.711
我们这个虾算中等吧

0:01:20.056,0:01:23.113
就是三斤的话只有56个

0:01:23.169,0:01:23.668
56个

0:01:23.893,0:01:25.896
56 个也就是说一斤的话

0:01:25.945,0:01:28.411
我们这个虾稍微大点的话连20个都没有

0:01:29.739,0:01:32.056
我们切一点这个姜跟蒜

0:01:33.705,0:01:36.899
随便什么菜 随便你好那种（厉害）的菜

0:01:38.152,0:01:40.135
百分之八十的菜都有这个姜蒜

0:01:40.657,0:01:41.127
是

0:01:41.680,0:01:44.634
这个姜的话 我们就是切大块一点可以

0:01:44.791,0:01:47.025
然后这个蒜的话宰成两三坨

0:01:47.714,0:01:48.768
切小粒就行

0:01:51.597,0:01:53.121
然后再切一点小米辣

0:01:54.208,0:01:56.901
增加一点点鲜辣的味道

0:01:58.663,0:02:00.323
其实也可以加那个二荆条

0:02:00.521,0:02:02.505
如果吃不了太辣的话

0:02:07.526,0:02:10.250
然后配料的话我们就配点魔芋

0:02:14.697,0:02:16.325
魔芋烧在龙虾里面也好吃

0:02:20.866,0:02:22.944
这样子整起好好看哦噶 

0:02:23.695,0:02:24.154
是不

0:02:24.342,0:02:25.709
跟它波浪似的样

0:02:29.780,0:02:32.714
我们这个青瓜加进去要最后加比较脆

0:02:39.238,0:02:40.615
直接切成小条

0:02:42.348,0:02:44.561
是脆的这个放进去

0:02:44.603,0:02:47.807
要慢慢品尝才品尝得出来这个滋味

0:02:52.547,0:02:54.373
最后我们再切点小葱

0:02:54.373,0:02:55.688
小葱切进去

0:02:56.419,0:02:57.974
最后起锅的时候再加

0:02:59.436,0:03:02.317
因为有这个底料非常的方便简单

0:03:04.462,0:03:06.146
加上自己喜欢的辅料

0:03:06.641,0:03:09.324
然后切点大蒜 生姜 辣椒 

0:03:10.085,0:03:11.189
再加一包这个料

0:03:11.560,0:03:12.407
把这个料开一哈都

0:03:15.233,0:03:15.927
全部把它倒出来 

0:03:17.773,0:03:20.551
我们这个料不单单可以烧这个龙虾

0:03:20.561,0:03:21.560
还可以烧干锅

0:03:22.350,0:03:23.958
因为这里面我配了孜然粉

0:03:24.224,0:03:28.563
就是有香辣的那个配方在里面

0:03:30.494,0:03:31.455
好可以了

0:03:33.120,0:03:35.080
你闻哈看有一股干锅的（味道）

0:03:36.194,0:03:38.001
因为放了那个孜然在里头的

0:03:38.049,0:03:39.124
有点干锅的味道

0:03:39.981,0:03:40.713
好 开始炒

0:03:44.776,0:03:46.108
炒起炒起

0:06:15.863,0:06:17.426
来 四伯爷你的筷子

0:06:25.374,0:06:26.710
我吃点黄瓜看

0:06:26.873,0:06:27.557
有味道

0:06:40.303,0:06:43.197
吃是好吃 好多东西我咬不动了

0:06:44.176,0:06:44.906
没得办法得

0:06:46.133,0:06:46.809
吃个小龙虾

0:06:53.590,0:06:54.417
用手撕来吃

0:07:01.116,0:07:03.445
没得好多点黄的了这哈的龙虾

0:07:03.625,0:07:04.479
没得好多肉的

0:07:04.672,0:07:05.306
啊

0:07:08.049,0:07:10.544
我们这个料只放了一包做三斤小龙虾的话

0:07:11.605,0:07:12.653
刚好合适噻

0:07:13.163,0:07:14.500
就是稍微淡一点点

0:07:14.527,0:07:16.163
如果你们要吃重口味的话

0:07:16.347,0:07:17.128
放一包半

0:07:20.207,0:07:22.480
我说的淡是辣味的淡

0:07:23.555,0:07:24.728
诶 这个还可以

0:07:25.131,0:07:25.510
嗯

0:07:29.712,0:07:32.742
一包料烧40个就味道刚刚好

0:07:33.475,0:07:35.968
就是重口味的刚刚好

0:07:38.607,0:07:41.258
好吃 就是没得什么肉现在的龙虾

0:07:47.819,0:07:48.637
 吃起就停不下来


```

**Comment by immoonancient** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：用料包做“麻辣小龙虾”的做法，详解如何去虾线，味道巴适，好吃得停不下来
Chef Wang shares: "Numbing and Spicy Crayfish" with seasoning packs. Unstoppably tasty!

简介
大家好，之前有朋友买了小龙虾料包但是不太会用，
Hello everyone! Some friends bought our crayfish seasoning packs but don't know how to cook with it.
今天就来现场教学一下，并且再详细教一下大家如何给小龙虾去虾线。
Today we'll do a live demonstration, and also show you how to devein a crayfish.
首先就是准备洗净的小龙虾，然后抓住小龙虾头部，
We need to thoroughly clean the crayfish, catch its head,
怕被夹的朋友可以带上橡胶手套，（注：翻译调整了这两句的位置，因为感觉不太好中间插入）
use the other hand to twist the middle part of the tail, and then pull out the vein.
然后用另一只手转动龙虾尾中间的部分，最后将虾线抽出即可。
Wear rubber gloves if you are afraind of being pinched.
最后如果使用料包的话就只用准备好姜葱蒜和喜欢的配料炒制即可，
Lastly, if you are using a seasoning pack, just cook it with ginger, scallion, garlic and your favorite ingredients.
并且此料包还可以用来制作炒田螺，烤鱼，干锅等菜品。
You may also cook river snails, grilled fish, dry pots and etc. with the seasoning pack.

很抱歉海外的朋友暂时可能没有办法买到我的产品，但是也不能阻止吃货的脚步，
Friends overseas probably can't get our products. Sorry about that.
However, nothing can stop a real foodie.
没有料包的朋友可以看我之前的小龙虾教学，不需要料包也没问题：
Please follow my previous crayfish recipes, which do not require a seasoning pack:
麻辣小龙虾 https://www.youtube.com/watch?v=DGmPpeDbjBg
Numbing and Spicy Crayfish: https://www.youtube.com/watch?v=DGmPpeDbjBg
十三香小龙虾 https://www.youtube.com/watch?v=JRawQBCkQ34
Thirteen-Spices Crayfish: https://www.youtube.com/watch?v=JRawQBCkQ34
蒜蓉小龙虾 https://www.youtube.com/watch?v=2EaiAdYI0tY
Crayfish with Minced Garlic: https://www.youtube.com/watch?v=2EaiAdYI0tY

字幕
0:00:00.225,0:00:01.350
哈喽 大家好
Hello everyone

0:00:01.425,0:00:03.350
前段时间我们粉丝买了
Earlier, some fans bought our crayfish seasoning packs

0:00:03.575,0:00:06.325
我们自己做的这个小龙虾（调料）回家他不会用
But they don't know how to use it at home

0:00:06.325,0:00:10.950
今天我们就用这个来现场烧一个来试验一下
Today, we'll cook with it as a live demonstration

0:00:11.025,0:00:12.300
这里面有三包
There are three packs in it

0:00:13.182,0:00:15.182
这个龙虾在那个养殖场买的
We bought the crayfish from a farm

0:00:15.325,0:00:16.125
特别干净
These are really clean

0:00:16.850,0:00:18.475
特别干净的一个小龙虾
Really clean crayfish

0:00:18.625,0:00:20.125
然后就用一包来烧
We'll cook with a pack

0:00:20.650,0:00:21.950
我把虾线去了都
I'm removing the vein

0:00:23.025,0:00:23.600
看
Look

0:00:23.900,0:00:26.000
这是根啥子嘛
What's this?

0:00:26.275,0:00:29.013
这根就是它(龙虾）这个肠子
It's the intestine of the crayfish

0:00:29.013,0:00:30.725
你看嘛 这
Yeah

0:00:30.875,0:00:32.625
我来抽哈看抽得来不
Let me try if I can pull it out

0:00:32.900,0:00:34.150
小心它要咬到你哦
Careful, it bites you

0:00:34.225,0:00:35.925
它咬得到我呀
No way, it can't

0:00:38.400,0:00:39.975
我都学会了
I've learnt it

0:00:40.700,0:00:43.825
今天我们来试验一下3斤龙虾到底有多少个
Today, let's count how many there are in 3 jin of crayfish (1.5kg)

0:00:43.875,0:00:46.450
等一下我们弄完了就数一下
We'll count after we're done

0:00:46.675,0:00:48.100
两边给它扯住给它拨一下
Hold the two ends and pull

0:00:48.125,0:00:49.775
扭一下 抓到扭一下
Twist it lightly

0:00:51.125,0:00:51.950
就把它整出来了
Then it's out

0:00:52.225,0:00:53.400
最后一个
Last one

0:00:53.625,0:00:55.050
这个还比较顽固
which is a stubborn one

0:00:55.850,0:00:56.750
最后一个出来了
Last one done

0:00:56.950,0:00:57.900
我数一哈看有好多个
Let me count how many are there

0:00:57.950,0:00:58.875
我去拿筷子来
I'll get the chopsticks

0:00:59.100,0:01:00.240
害怕它夹到手
Or they pinch my hands

0:01:00.240,0:01:01.525
哪干哦
How could it be?

0:01:02.327,0:01:03.909
夹到它痛得很 四伯爷
It really hurts, uncle

0:01:04.764,0:01:07.589
2个3个4个
2, 3, 4

0:01:08.060,0:01:11.173
17 18 19  20
17, 18, 19, 20

0:01:11.402,0:01:13.141
52 54  56
52, 54, 56

0:01:14.293,0:01:14.968
三斤
3 jin... (1.5kg)

0:01:15.860,0:01:17.807
一斤20个都没得哦
Not even 20 per jin 

0:01:18.299,0:01:19.711
我们这个虾算中等吧
So these crayfish are medium-sized

0:01:20.056,0:01:23.113
就是三斤的话只有56个
Only 56 crayfish for 3 jin

0:01:23.169,0:01:23.668
56个
56

0:01:23.893,0:01:25.896
56 个也就是说一斤的话
56... That means the count per jin is...

0:01:25.945,0:01:28.411
我们这个虾稍微大点的话连20个都没有
Below 20, if the crayfish are not too small

0:01:29.739,0:01:32.056
我们切一点这个姜跟蒜
Let's chop some ginger and garlic

0:01:33.705,0:01:36.899
随便什么菜 随便你好那种（厉害）的菜
Whatever dish, whatever you are good at

0:01:38.152,0:01:40.135
百分之八十的菜都有这个姜蒜
80% of them use ginger and garlic

0:01:40.657,0:01:41.127
是
True

0:01:41.680,0:01:44.634
这个姜的话 我们就是切大块一点可以
We just need to roughly chop the ginger

0:01:44.791,0:01:47.025
然后这个蒜的话宰成两三坨
Chop the garlic into a few pieces

0:01:47.714,0:01:48.768
切小粒就行
Just some small pieces

0:01:51.597,0:01:53.121
然后再切一点小米辣
And dice some "Xiaomila" chili peppers

0:01:54.208,0:01:56.901
增加一点点鲜辣的味道
for the savory and spicy taste

0:01:58.663,0:02:00.323
其实也可以加那个二荆条
Actually, "Erjingtiao" (chili) is also fine

0:02:00.521,0:02:02.505
如果吃不了太辣的话
if you can't handle the spiciness

0:02:07.526,0:02:10.250
然后配料的话我们就配点魔芋
For the sides, we just need some konjac

0:02:14.697,0:02:16.325
魔芋烧在龙虾里面也好吃
Konjac braised with crayfish is delicious

0:02:20.866,0:02:22.944
这样子整起好好看哦噶 
You made it so pretty huh?

0:02:23.695,0:02:24.154
是不
Is it?

0:02:24.342,0:02:25.709
跟它波浪似的样
Looks like waves

0:02:29.780,0:02:32.714
我们这个青瓜加进去要最后加比较脆
The cucumbers should be added last, to keep the crunchiness

0:02:39.238,0:02:40.615
直接切成小条
Cut it into small strips

0:02:42.348,0:02:44.561
是脆的这个放进去
It will be crunchy in the dish

0:02:44.603,0:02:47.807
要慢慢品尝才品尝得出来这个滋味
Gotta taste it slowly to know the flavor

0:02:52.547,0:02:54.373
最后我们再切点小葱
Finally, let's chop some scallions

0:02:54.373,0:02:55.688
小葱切进去
Chop some scallions

0:02:56.419,0:02:57.974
最后起锅的时候再加
And add it at last, before serving

0:02:59.436,0:03:02.317
因为有这个底料非常的方便简单
The seasoning pack makes it very simple and convenient

0:03:04.462,0:03:06.146
加上自己喜欢的辅料
Just add your favorite ingredients

0:03:06.641,0:03:09.324
然后切点大蒜 生姜 辣椒 
Chop some garlic, ginger and chili peppers

0:03:10.085,0:03:11.189
再加一包这个料
And add a pack of the seasoning

0:03:11.560,0:03:12.407
把这个料开一哈都
Need to open the pack

0:03:15.233,0:03:15.927
全部把它倒出来 
Pour everything out

0:03:17.773,0:03:20.551
我们这个料不单单可以烧这个龙虾
The seasoning pack is not only good for crayfish

0:03:20.561,0:03:21.560
还可以烧干锅
but also for dry pots

0:03:22.350,0:03:23.958
因为这里面我配了孜然粉
It's because I added cumin powder in it

0:03:24.224,0:03:28.563
就是有香辣的那个配方在里面
I mean, there's the "Xiangla" spicy mix in it

0:03:30.494,0:03:31.455
好可以了
Alright, good

0:03:33.120,0:03:35.080
你闻哈看有一股干锅的（味道）
It smells like a dry pot, right?

0:03:36.194,0:03:38.001
因为放了那个孜然在里头的
That's because of the cumin

0:03:38.049,0:03:39.124
有点干锅的味道
So it smells like a dry pot

0:03:39.981,0:03:40.713
好 开始炒
Alright, let's start cooking

0:03:44.776,0:03:46.108
炒起炒起
Let's get started

0:06:15.863,0:06:17.426
来 四伯爷你的筷子
Chopsticks for you, uncle

0:06:25.374,0:06:26.710
我吃点黄瓜看
Let me try some cucumber

0:06:26.873,0:06:27.557
有味道
(Properly) flavored

0:06:40.303,0:06:43.197
吃是好吃 好多东西我咬不动了
It's tasty, but there are too many things I can't chew

0:06:44.176,0:06:44.906
没得办法得
No way

0:06:46.133,0:06:46.809
吃个小龙虾
I'll have a crayfish

0:06:53.590,0:06:54.417
用手撕来吃
Tearing it with my hands

0:07:01.116,0:07:03.445
没得好多点黄的了这哈的龙虾
There's not much "yellow stuff" in the crayfish

0:07:03.625,0:07:04.479
没得好多肉的
Not much meat either

0:07:04.672,0:07:05.306
啊
Um

0:07:08.049,0:07:10.544
我们这个料只放了一包做三斤小龙虾的话
We used only one pack of seasoning for 3 jin of crayfish

0:07:11.605,0:07:12.653
刚好合适噻
Just about right?

0:07:13.163,0:07:14.500
就是稍微淡一点点
It's a bit milder though

0:07:14.527,0:07:16.163
如果你们要吃重口味的话
So if you prefer a stronger flavor

0:07:16.347,0:07:17.128
放一包半
Use 1.5 packs

0:07:20.207,0:07:22.480
我说的淡是辣味的淡
By "mild" I mean mild in the spiciness

0:07:23.555,0:07:24.728
诶 这个还可以
Eh, this one is good

0:07:25.131,0:07:25.510
嗯
Um

0:07:29.712,0:07:32.742
一包料烧40个就味道刚刚好
One pack for 40 crayfish should be just about right

0:07:33.475,0:07:35.968
就是重口味的刚刚好
I mean, just about right for a strong flavor

0:07:38.607,0:07:41.258
好吃 就是没得什么肉现在的龙虾
It's tasty! But too little meat in the crayfish

0:07:47.819,0:07:48.637
吃起就停不下来
I just can't stop eating
