### ISSUE TITLE
【美食作家王刚】麻辣羊蝎子 - https://youtu.be/Yif_61VKEYA

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#927]
**视频链接**：https://youtu.be/Yif_61VKEYA

视频时长4:53，预计发布时间为北京时间4月21日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“麻辣羊蝎子”的家常做法，味鲜肉嫩，边炖边吃还能煮火锅！

简介
同学们好，今天和大家分享一道经典好菜“麻辣羊蝎子”，不仅味美，还营养丰富，这样炖出来的羊蝎子肉十分软烂，并且一定不要错过脊椎骨中的骨髓，钙质含量十分丰富，特别适合长身体的孩子们。炖好的羊蝎子可以用明火上桌，一边吃一边炖，羊肉吃的差不多的时候可以下入蔬菜或者其他想涮煮的食材，一道麻辣羊蝎子火锅就成了，大家有机会一定要尝试，非常鲜美！

因为饭店的需求量很大，羊蝎子可能不是特别好购买，所以平常需要和摊主搞好关系，想吃的时候提前和摊主打好招呼，留上一条

本期菜品:【麻辣羊蝎子】
【主料】
羊蝎子（1整条）
【辅料】
生姜（50克）
大葱（50克）
牛油火锅底料（250克）
青花椒（适量）
小茴香（适量）
植物油（适量）
干辣椒（适量）
香菜（适量）
【调味料】
料酒（适量）
高度白酒（适量）
生抽酱油（25克）
食用盐（约5克）
胡椒粉（约1.5克）
白糖（约0.5克）

字幕
0:00:00.500,0:00:01.675
哈喽大家好我是王刚

0:00:01.720,0:00:03.680
本期视频我跟大家分享一道家常菜

0:00:05.280,0:00:06.840
麻辣羊蝎子

0:00:07.000,0:00:09.125
首选我们准备（羊蝎子）1整条

0:00:09.325,0:00:11.500
羊蝎子其实就是羊的脊椎骨

0:00:11.750,0:00:14.625
从羊脖子至羊尾巴都能称之为羊蝎子肉

0:00:14.700,0:00:16.400
下一步我们开始处理食材

0:00:17.000,0:00:20.500
首先我们将羊脊椎骨用砍刀剁成大小均匀的块备用

0:00:20.600,0:00:23.150
由于羊肉受热之后缩水比较严重

0:00:23.200,0:00:25.426
同学们可以适量的剁大块一下

0:00:25.500,0:00:27.950
嫌麻烦的同学也可以交给摊主来处理

0:00:55.353,0:00:57.227
下一步我们开始准备辅料

0:00:58.071,0:01:01.923
准备生姜和大葱各50克改刀切成姜片和葱段备用

0:01:05.828,0:01:09.206
准备麻辣牛油火锅底料250克切碎备用

0:01:17.992,0:01:20.208
准备适量的青花椒放入碗中备用

0:01:20.472,0:01:22.768
再加入和花椒等量的小茴香备用

0:01:23.031,0:01:24.324
下一步开始制作

0:01:24.456,0:01:26.725
首先我们在锅中加入适量的清水

0:01:27.807,0:01:30.155
然后将剁好的羊蝎子冷水下锅焯水

0:01:38.731,0:01:40.894
中途加入适量的料酒去腥

0:01:46.831,0:01:48.942
大火烧开之后再撇去浮沫

0:01:54.483,0:01:57.517
然后将焯好水的羊蝎子捞出控水备用

0:02:02.398,0:02:04.008
下一步开始烧制

0:02:04.140,0:02:05.644
首先我们把锅烧热

0:02:05.802,0:02:07.753
锅烧热之后加入适量的底油（约200克）

0:02:10.340,0:02:13.559
油温5成热之后加入切好的姜葱小火炒香

0:02:21.870,0:02:23.717
中途再加入适量的干辣椒

0:02:23.717,0:02:27.227
同学们切记这一步必须小火把姜葱辣椒炒香

0:02:33.269,0:02:36.277
辣椒变色之后加入准备好的花椒和小茴香

0:02:41.607,0:02:45.089
翻炒几下之后再加入切好的火锅底料下锅炒香炒化

0:02:47.570,0:02:49.997
同学们最好选择牛油比例高的火锅底料

0:02:51.377,0:02:54.411
底料炒香之后再加入处理好的羊蝎子翻炒几下

0:03:00.498,0:03:03.058
中途加入适量的高度白酒翻炒去腥

0:03:03.084,0:03:06.277
白酒挥发的同时也可以增加香味和去腥

0:03:08.256,0:03:10.736
酒精挥发完成之后再加入适量的热水

0:03:10.877,0:03:12.794
热水的量能够没过羊肉即可

0:03:13.058,0:03:15.195
这一步必须一次性将热水放足

0:03:15.432,0:03:18.177
否则中途加水会导致香味变得寡淡

0:03:18.203,0:03:20.155
然后转大火将汤汁烧开

0:03:28.277,0:03:31.496
大火烧开之后再加入生抽酱油25克调鲜味

0:03:36.118,0:03:38.651
酱油下锅之后转小火烧60分钟即可

0:03:38.757,0:03:41.844
同学们羊肉烧制的时间是根据羊的老嫩而定

0:03:41.844,0:03:46.752
可以每过15分钟尝试1次根据个人口感而定时

0:03:46.752,0:03:49.258
羊蝎子烧至60分钟之后开始调味

0:03:50.393,0:03:52.293
锅中加入食用盐2大勺（约5克）

0:03:55.636,0:03:56.963
加入胡椒粉1勺（约1.5克）

0:03:58.282,0:03:59.522
再加入少许白糖（约0.5克）

0:04:00.076,0:04:01.950
调好味之后即可出锅装盘

0:04:16.699,0:04:19.047
最后撒上适量的香菜即可上菜

0:04:19.080,0:04:21.620
一道香辣口味的羊蝎子就制作完成

0:04:27.760,0:04:52.720
下面开始技术总结
第一，除了羊蝎子之外也可以按照此法烹制羊排或者羊蹄
第二，羊蝎子必须冷水下锅焯水否则血沫出不来
第三，香料不需要太多种类，只需要花椒和小茴香即可
第四，热水必须一次性加足，中途不加水
第五，食用盐必须最后起锅才放，这样是为了羊肉更容易炖熟
香辣羊蝎子的技术总结完毕

```

**Comment by Yaohua-Chang** [comment]
认领

**Comment by Yaohua-Chang** [comment]
# https://youtu.be/Yif_61VKEYA

# 标题（翻译主要意思即可，不要超过 100 个字符）
# 厨师长教你：“麻辣羊蝎子”的家常做法，味鲜肉嫩，边炖边吃还能煮火锅！
# Chef Wang teaches you: "Spicy Yangxiezi", home-style dish that tastes delicious.

# 简介
# Introduction
# 同学们好，今天和大家分享一道经典好菜“麻辣羊蝎子”，不仅味美，还营养丰富，这样炖出来的羊蝎子肉十分软烂，并且一定不要错过脊椎骨中的骨髓，钙质含量十分丰富，特别适合长身体的孩子们。炖好的羊蝎子可以用明火上桌，一边吃一边炖，羊肉吃的差不多的时候可以下入蔬菜或者其他想涮煮的食材，一道麻辣羊蝎子火锅就成了，大家有机会一定要尝试，非常鲜美！
# Hi everyone, today I'll share the recipe of Spicy Yangxiezi (aka lamb spine). This dish is delicious and nutritious. The lamb spine stewed in this way is very soft. The bone marrow in the spine is rich in calcium, especially good for kids who need to build body. The stewed lamb spine can be served over fire like hot pot, so you can eat it while it is still stewing. When the lamb is almost ready to eat, add vegetables or other ingredients you want into the hot pot, then the spicy Yangxiezi hotpot is ready to serve. You must try it if you get a chance, it's very delicious!

# 因为饭店的需求量很大，羊蝎子可能不是特别好购买，所以平常需要和摊主搞好关系，想吃的时候提前和摊主打好招呼，留上一条
# Because of the high demand of restaurants, lamb spine may not be very easy to buy, so you need to develop a good relationship with the grocery owner. When you need it, ask the owner to save the one in advance.

# 本期菜品:【麻辣羊蝎子】
# Today's dish: Spicy Yangxiezi

# 【主料】
# Major ingredients
# 羊蝎子（1整条）
# Lamb Spine (a whole piece)

# 【辅料】
# Other ingredients
# 生姜（50克）
# Ginger (50g)
# 大葱（50克）
# Spring onion (50g)
# 牛油火锅底料（250克）
# Beef tallow hot pot seasoning (250g)
# 青花椒（适量）
# Sichuan green peppercorn (a reasonable amount)
# 小茴香（适量）
# Fennel seed (a reasonable amount)
# 植物油（适量）
# Vegetable oil (a reasonable amount)
# 干辣椒（适量）
# Dried chili pepper (a reasonable amount)
# 香菜（适量）
# Cilantro (a reasonable amount)

【调味料】
# Seasoning
料酒（适量）
# Chinese cooking wine (a reasonable amount)
高度白酒（适量）
# High degree baijiu (a reasonable amount)
生抽酱油（25克）
# Light soy sauce (25g)
食用盐（约5克）
# Salt (around 5g)
胡椒粉（约1.5克）
# Ground pepper (around 1.5g)
白糖（约0.5克）
# Sugar (around 0.5g)

字幕
0:00:00.500,0:00:01.675
# 哈喽大家好我是王刚
Hi everyone, I'm Wang Gang

0:00:01.720,0:00:03.680
# 本期视频我跟大家分享一道家常菜
Today I'll share the recipe of a home-style dish

0:00:05.280,0:00:06.840
麻辣羊蝎子
Spicy Yangxiezi (aka lamb spine)

0:00:07.000,0:00:09.125
# 首选我们准备（羊蝎子）1整条
First, prepare a whole piece of Yangxiezi

0:00:09.325,0:00:11.500
# 羊蝎子其实就是羊的脊椎骨
Yangxiezi is actually the spine of a lamb

0:00:11.750,0:00:14.625
# 从羊脖子至羊尾巴都能称之为羊蝎子肉
The meat attached on the spine from the lamb's neck to the tail is called Yangxiezi

0:00:14.700,0:00:16.400
# 下一步我们开始处理食材
Let's start processing the ingredients

0:00:17.000,0:00:20.500
# 首先我们将羊脊椎骨用砍刀剁成大小均匀的块备用
First, we chop the lamb spine into uniform pieces with a machete

0:00:20.600,0:00:23.150
# 由于羊肉受热之后缩水比较严重
Since the lamb shrinks badly after being heated

0:00:23.200,0:00:25.426
# 同学们可以适量的剁大块一下
You can chop it into large chunks

0:00:25.500,0:00:27.950
# 嫌麻烦的同学也可以交给摊主来处理
If you have no patience, you can let the grocery owner handle it

0:00:55.353,0:00:57.227
# 下一步我们开始准备辅料
Next, we start preparing the other ingredients

0:00:58.071,0:01:01.923
# 准备生姜和大葱各50克改刀切成姜片和葱段备用
Cut 50g ginger into slice and cut 50g spring onion into segments

0:01:05.828,0:01:09.206
# 准备麻辣牛油火锅底料250克切碎备用
Cut 250g beef tallow hot pot seasoning into dice

0:01:17.992,0:01:20.208
# 准备适量的青花椒放入碗中备用
Put some Sichuan green peppercorn into a bowl

0:01:20.472,0:01:22.768
# 再加入和花椒等量的小茴香备用
Add the same amount of fennel seed as the peppercorn

0:01:23.031,0:01:24.324
# 下一步开始制作
Next start cooking

0:01:24.456,0:01:26.725
# 首先我们在锅中加入适量的清水
First, we add a reasonable amount of water into the wok

0:01:27.807,0:01:30.155
# 然后将剁好的羊蝎子冷水下锅焯水
Then parboil the chopped Yangxiezi in the cold water

0:01:38.731,0:01:40.894
# 中途加入适量的料酒去腥
Add some Chinese cooking wine halfway to get rid of the lamb odor

0:01:46.831,0:01:48.942
# 大火烧开之后再撇去浮沫
When the water is boiling, remove the froth

0:01:54.483,0:01:57.517
# 然后将焯好水的羊蝎子捞出控水备用
Then take the parboiled Yangxiezi out and drain the water

0:02:02.398,0:02:04.008
# 下一步开始烧制
Next start cooking

0:02:04.140,0:02:05.644
# 首先我们把锅烧热
First, we heat up the wok

0:02:05.802,0:02:07.753
# 锅烧热之后加入适量的底油（约200克）
After it's heated, add a reasonable amount of cold oil (around 200g)

0:02:10.340,0:02:13.559
# 油温5成热之后加入切好的姜葱小火炒香
When the oil reaches 150 °C, add the sliced ginger and green onions and fry them with small fire until the smell comes out 

0:02:21.870,0:02:23.717
# 中途再加入适量的干辣椒
Add some dried chili pepper halfway

0:02:23.717,0:02:27.227
# 同学们切记这一步必须小火把姜葱辣椒炒香
Guys, remember, must use low heat and fry the spices until the smell comes out in this step

0:02:33.269,0:02:36.277
# 辣椒变色之后加入准备好的花椒和小茴香
After the peppers have changed color, add the prepared peppercorns and fennel seed 

0:02:41.607,0:02:45.089
# 翻炒几下之后再加入切好的火锅底料下锅炒香炒化
Stir-fry a few times, then add the diced hot pot seasoning and fry it until it is melted

0:02:47.570,0:02:49.997
# 同学们最好选择牛油比例高的火锅底料
Guys, it's better choosing a hot pot seasoning with a high percentage of beef tallow

0:02:51.377,0:02:54.411
# 底料炒香之后再加入处理好的羊蝎子翻炒几下
After the seasoning smell comes out, add the prepared Yangxiezi and stir-fry a few times

0:03:00.498,0:03:03.058
# 中途加入适量的高度白酒翻炒去腥
Add high degree baijiu to get rid of the lamb odor halfway

0:03:03.084,0:03:06.277
# 白酒挥发的同时也可以增加香味和去腥
It can also add flavor while baijiu is evaporating 

0:03:08.256,0:03:10.736
# 酒精挥发完成之后再加入适量的热水
After the alcohol has evaporated, add a reasonable amount of hot water

0:03:10.877,0:03:12.794
# 热水的量能够没过羊肉即可
The amount of hot water should be enough to cover the lamb

0:03:13.058,0:03:15.195
# 这一步必须一次性将热水放足
You must put the hot water enough at once in this step

0:03:15.432,0:03:18.177
# 否则中途加水会导致香味变得寡淡
Otherwise, adding water in the middle will cause the flavor getting fade

0:03:18.203,0:03:20.155
# 然后转大火将汤汁烧开
Then turn up the heat and boil the soup

0:03:28.277,0:03:31.496
# 大火烧开之后再加入生抽酱油25克调鲜味
After it is boiling, add 25g light soy sauce to season the soup

0:03:36.118,0:03:38.651
# 酱油下锅之后转小火烧60分钟即可
Just put the soy sauce in the wok and turn the heat to low for 60 minutes

0:03:38.757,0:03:41.844
# 同学们羊肉烧制的时间是根据羊的老嫩而定
Guys, the time of stewing depends on how old or tender the lamb is

0:03:41.844,0:03:46.752
# 可以每过15分钟尝试1次根据个人口感而定时
You can try it every 15 minutes and determine the time of stewing according to your taste.

0:03:46.752,0:03:49.258
# 羊蝎子烧至60分钟之后开始调味
After 60-minute stewing, start adding more seasonings

0:03:50.393,0:03:52.293
# 锅中加入食用盐2大勺（约5克）
Add some salt to the wok (around 5g)

0:03:55.636,0:03:56.963
# 加入胡椒粉1勺（约1.5克）
Add one spoonful of ground pepper (around 1.5g)

0:03:58.282,0:03:59.522
# 再加入少许白糖（约0.5克）
Add a little bit of sugar (around 0.5g)

0:04:00.076,0:04:01.950
调好味之后即可出锅装盘
After seasoning, it's ready to take out and pour to a dish

0:04:16.699,0:04:19.047
最后撒上适量的香菜即可上菜
Finally decorate with some cilantro, then the dish is ready to serve.

0:04:19.080,0:04:21.620
一道香辣口味的羊蝎子就制作完成
# A spicy Yangxiezi is finished

0:04:27.760,0:04:52.720
# 下面开始技术总结
# 第一，除了羊蝎子之外也可以按照此法烹制羊排或者羊蹄
# 第二，羊蝎子必须冷水下锅焯水否则血沫出不来
# 第三，香料不需要太多种类，只需要花椒和小茴香即可
# 第四，热水必须一次性加足，中途不加水
# 第五，食用盐必须最后起锅才放，这样是为了羊肉更容易炖熟
# 香辣羊蝎子的技术总结完毕
Now, let's summarize the techniques
First, except for the lamb spine, you can also cook lamb chops or lamb hooves in this way
Second, Yangxiezi must be parboiled in cold water, or the blood froth will not come out
Third, the kinds of spices don't need too many, just peppercorns and fennel seeds are enough
Fourth, enough hot water must be filled at once rather than adding more water in the middle
Fifth, salt must be added at end of the cooking to make the lamb easier to stew well
These are all the techniques about Yangxiezi I'd like to share

**Comment by Yaohua-Chang** [comment]
the lamb odorhttps://youtu.be/Yif_61VKEYA

the lamb odor标题（翻译主要意思即可，不要超过 100 个字符）
the lamb odor厨师长教你：“麻辣羊蝎子”的家常做法，味鲜肉嫩，边炖边吃还能煮火锅！
the lamb odorChef Wang teaches you: "Spicy Yangxiezi", home-style dish that tastes delicious.

the lamb odor简介
the lamb odorIntroduction
the lamb odor同学们好，今天和大家分享一道经典好菜“麻辣羊蝎子”，不仅味美，还营养丰富，这样炖出来的羊蝎子肉十分软烂，并且一定不要错过脊椎骨中的骨髓，钙质含量十分丰富，特别适合长身体的孩子们。炖好的羊蝎子可以用明火上桌，一边吃一边炖，羊肉吃的差不多的时候可以下入蔬菜或者其他想涮煮的食材，一道麻辣羊蝎子火锅就成了，大家有机会一定要尝试，非常鲜美！
the lamb odorHi everyone, today I'll share the recipe of Spicy Yangxiezi (aka lamb spine). This dish is delicious and nutritious. The lamb spine stewed in this way is very soft. The bone marrow in the spine is rich in calcium, especially good for kids who need to build body. The stewed lamb spine can be served over fire like hot pot, so you can eat it while it is still stewing. When the lamb is almost ready to eat, add vegetables or other ingredients you want into the hot pot, then the spicy Yangxiezi hotpot is ready to serve. You must try it if you get a chance, it's very delicious!

the lamb odor因为饭店的需求量很大，羊蝎子可能不是特别好购买，所以平常需要和摊主搞好关系，想吃的时候提前和摊主打好招呼，留上一条
the lamb odorBecause of the high demand of restaurants, lamb spine may not be very easy to buy, so you need to develop a good relationship with the grocery owner. When you need it, ask the owner to save the one in advance.

the lamb odor本期菜品:【麻辣羊蝎子】
the lamb odorToday's dish: Spicy Yangxiezi

the lamb odor【主料】
the lamb odorMajor ingredients
the lamb odor羊蝎子（1整条）
the lamb odorLamb Spine (a whole piece)

the lamb odor【辅料】
the lamb odorOther ingredients
the lamb odor生姜（50克）
the lamb odorGinger (50g)
the lamb odor大葱（50克）
the lamb odorSpring onion (50g)
the lamb odor牛油火锅底料（250克）
the lamb odorBeef tallow hot pot seasoning (250g)
the lamb odor青花椒（适量）
the lamb odorSichuan green peppercorn (a reasonable amount)
the lamb odor小茴香（适量）
the lamb odorFennel seed (a reasonable amount)
the lamb odor植物油（适量）
the lamb odorVegetable oil (a reasonable amount)
the lamb odor干辣椒（适量）
the lamb odorDried chili pepper (a reasonable amount)
the lamb odor香菜（适量）
the lamb odorCilantro (a reasonable amount)

【调味料】
the lamb odorSeasoning
料酒（适量）
the lamb odorChinese cooking wine (a reasonable amount)
高度白酒（适量）
the lamb odorHigh degree baijiu (a reasonable amount)
生抽酱油（25克）
the lamb odorLight soy sauce (25g)
食用盐（约5克）
the lamb odorSalt (around 5g)
胡椒粉（约1.5克）
the lamb odorGround pepper (around 1.5g)
白糖（约0.5克）
the lamb odorSugar (around 0.5g)

字幕
0:00:00.500,0:00:01.675
the lamb odor哈喽大家好我是王刚
Hi everyone, I'm Wang Gang

0:00:01.720,0:00:03.680
the lamb odor本期视频我跟大家分享一道家常菜
Today I'll share the recipe of a home-style dish

0:00:05.280,0:00:06.840
麻辣羊蝎子
Spicy Yangxiezi (aka lamb spine)

0:00:07.000,0:00:09.125
the lamb odor首选我们准备（羊蝎子）1整条
First, prepare a whole piece of Yangxiezi

0:00:09.325,0:00:11.500
the lamb odor羊蝎子其实就是羊的脊椎骨
Yangxiezi is actually the spine of a lamb

0:00:11.750,0:00:14.625
the lamb odor从羊脖子至羊尾巴都能称之为羊蝎子肉
The meat attached on the spine from the lamb's neck to the tail is called Yangxiezi

0:00:14.700,0:00:16.400
the lamb odor下一步我们开始处理食材
Let's start processing the ingredients

0:00:17.000,0:00:20.500
the lamb odor首先我们将羊脊椎骨用砍刀剁成大小均匀的块备用
First, we chop the lamb spine into uniform pieces with a machete

0:00:20.600,0:00:23.150
the lamb odor由于羊肉受热之后缩水比较严重
Since the lamb shrinks badly after being heated

0:00:23.200,0:00:25.426
the lamb odor同学们可以适量的剁大块一下
You can chop it into large chunks

0:00:25.500,0:00:27.950
the lamb odor嫌麻烦的同学也可以交给摊主来处理
If you have no patience, you can let the grocery owner handle it

0:00:55.353,0:00:57.227
the lamb odor下一步我们开始准备辅料
Next, we start preparing the other ingredients

0:00:58.071,0:01:01.923
the lamb odor准备生姜和大葱各50克改刀切成姜片和葱段备用
Cut 50g ginger into slice and cut 50g spring onion into segments

0:01:05.828,0:01:09.206
the lamb odor准备麻辣牛油火锅底料250克切碎备用
Cut 250g beef tallow hot pot seasoning into dice

0:01:17.992,0:01:20.208
the lamb odor准备适量的青花椒放入碗中备用
Put some Sichuan green peppercorn into a bowl

0:01:20.472,0:01:22.768
the lamb odor再加入和花椒等量的小茴香备用
Add the same amount of fennel seed as the peppercorn

0:01:23.031,0:01:24.324
the lamb odor下一步开始制作
Next start cooking

0:01:24.456,0:01:26.725
the lamb odor首先我们在锅中加入适量的清水
First, we add a reasonable amount of water into the wok

0:01:27.807,0:01:30.155
the lamb odor然后将剁好的羊蝎子冷水下锅焯水
Then parboil the chopped Yangxiezi in the cold water

0:01:38.731,0:01:40.894
the lamb odor中途加入适量的料酒去腥
Add some Chinese cooking wine halfway to get rid of the lamb odor

0:01:46.831,0:01:48.942
the lamb odor大火烧开之后再撇去浮沫
When the water is boiling, remove the froth

0:01:54.483,0:01:57.517
the lamb odor然后将焯好水的羊蝎子捞出控水备用
Then take the parboiled Yangxiezi out and drain the water

0:02:02.398,0:02:04.008
the lamb odor下一步开始烧制
Next start cooking

0:02:04.140,0:02:05.644
the lamb odor首先我们把锅烧热
First, we heat up the wok

0:02:05.802,0:02:07.753
the lamb odor锅烧热之后加入适量的底油（约200克）
After it's heated, add a reasonable amount of cold oil (around 200g)

0:02:10.340,0:02:13.559
the lamb odor油温5成热之后加入切好的姜葱小火炒香
When the oil reaches 150 °C, add the sliced ginger and green onions and fry them with small fire until the smell comes out 

0:02:21.870,0:02:23.717
the lamb odor中途再加入适量的干辣椒
Add some dried chili pepper halfway

0:02:23.717,0:02:27.227
the lamb odor同学们切记这一步必须小火把姜葱辣椒炒香
Guys, remember, must use low heat and fry the spices until the smell comes out in this step

0:02:33.269,0:02:36.277
the lamb odor辣椒变色之后加入准备好的花椒和小茴香
After the peppers have changed color, add the prepared peppercorns and fennel seed 

0:02:41.607,0:02:45.089
the lamb odor翻炒几下之后再加入切好的火锅底料下锅炒香炒化
Stir-fry a few times, then add the diced hot pot seasoning and fry it until it is melted

0:02:47.570,0:02:49.997
the lamb odor同学们最好选择牛油比例高的火锅底料
Guys, it's better choosing a hot pot seasoning with a high percentage of beef tallow

0:02:51.377,0:02:54.411
the lamb odor底料炒香之后再加入处理好的羊蝎子翻炒几下
After the seasoning smell comes out, add the prepared Yangxiezi and stir-fry a few times

0:03:00.498,0:03:03.058
the lamb odor中途加入适量的高度白酒翻炒去腥
Add high degree baijiu to get rid of the lamb odor halfway

0:03:03.084,0:03:06.277
the lamb odor白酒挥发的同时也可以增加香味和去腥
It can also add flavor while baijiu is evaporating 

0:03:08.256,0:03:10.736
the lamb odor酒精挥发完成之后再加入适量的热水
After the alcohol has evaporated, add a reasonable amount of hot water

0:03:10.877,0:03:12.794
the lamb odor热水的量能够没过羊肉即可
The amount of hot water should be enough to cover the lamb

0:03:13.058,0:03:15.195
the lamb odor这一步必须一次性将热水放足
You must put the hot water enough at once in this step

0:03:15.432,0:03:18.177
the lamb odor否则中途加水会导致香味变得寡淡
Otherwise, adding water in the middle will cause the flavor getting fade

0:03:18.203,0:03:20.155
the lamb odor然后转大火将汤汁烧开
Then turn up the heat and boil the soup

0:03:28.277,0:03:31.496
the lamb odor大火烧开之后再加入生抽酱油25克调鲜味
After it is boiling, add 25g light soy sauce to season the soup

0:03:36.118,0:03:38.651
the lamb odor酱油下锅之后转小火烧60分钟即可
Just put the soy sauce in the wok and turn the heat to low for 60 minutes

0:03:38.757,0:03:41.844
the lamb odor同学们羊肉烧制的时间是根据羊的老嫩而定
Guys, the time of stewing depends on how old or tender the lamb is

0:03:41.844,0:03:46.752
the lamb odor可以每过15分钟尝试1次根据个人口感而定时
You can try it every 15 minutes and determine the time of stewing according to your taste.

0:03:46.752,0:03:49.258
the lamb odor羊蝎子烧至60分钟之后开始调味
After 60-minute stewing, start adding more seasonings

0:03:50.393,0:03:52.293
the lamb odor锅中加入食用盐2大勺（约5克）
Add some salt to the wok (around 5g)

0:03:55.636,0:03:56.963
the lamb odor加入胡椒粉1勺（约1.5克）
Add one spoonful of ground pepper (around 1.5g)

0:03:58.282,0:03:59.522
the lamb odor再加入少许白糖（约0.5克）
Add a little bit of sugar (around 0.5g)

0:04:00.076,0:04:01.950
调好味之后即可出锅装盘
After seasoning, it's ready to take out and pour to a dish

0:04:16.699,0:04:19.047
最后撒上适量的香菜即可上菜
Finally decorate with some cilantro, then the dish is ready to serve.

0:04:19.080,0:04:21.620
一道香辣口味的羊蝎子就制作完成
the lamb odorA spicy Yangxiezi is finished

0:04:27.760,0:04:52.720
the lamb odor下面开始技术总结
the lamb odor第一，除了羊蝎子之外也可以按照此法烹制羊排或者羊蹄
the lamb odor第二，羊蝎子必须冷水下锅焯水否则血沫出不来
the lamb odor第三，香料不需要太多种类，只需要花椒和小茴香即可
the lamb odor第四，热水必须一次性加足，中途不加水
the lamb odor第五，食用盐必须最后起锅才放，这样是为了羊肉更容易炖熟
the lamb odor香辣羊蝎子的技术总结完毕
Now, let's summarize the techniques
First, except for the lamb spine, you can also cook lamb chops or lamb hooves in this way
Second, Yangxiezi must be parboiled in cold water, or the blood froth will not come out
Third, the kinds of spices don't need too many, just peppercorns and fennel seeds are enough
Fourth, enough hot water must be filled at once rather than adding more water in the middle
Fifth, salt must be added at end of the cooking to make the lamb easier to stew well
These are all the techniques about Yangxiezi I'd like to share
