### ISSUE TITLE
[老饭骨] 清蒸武昌鱼 - https://youtu.be/elLmU66TU-A

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#930]
**视频链接**：https://youtu.be/elLmU66TU-A

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•清蒸武昌鱼】国宴佳肴！二伯传承20多年的古法蒸武昌鱼，极鲜极嫩，倾注了二叔所有心思，为武汉加油！|老饭骨

简介
小友们好，今天带来一道二伯传承了20多年的菜——古法蒸武昌鱼！
这道菜也是一道国宴佳肴，今天就教小友们如何在家制作这道菜！
古法蒸武昌鱼的秘诀在于要放葱油，这样能在蒸的时候锁住水分，让鱼更加鲜嫩喷香！
也希望通过这道菜，能够传递出二伯的满满心意，祝全球的小友们都能元气满满，蒸蒸日上！
同时奉上之前“烫鱼”步骤的【汗蒸鱼】视频链接⬇️
【传统名菜汗蒸鱼Steamed fish】https://youtu.be/M6o5GfjK9CE

字幕
1
00:00:00,000 --> 00:00:02,240
别弄鱼上 让它四周围

2
00:00:02,240 --> 00:00:04,280

3
00:00:04,280 --> 00:00:07,560
古法蒸武昌鱼 武汉好久不见

4
00:00:07,560 --> 00:00:08,880
都什么食材啊

5
00:00:08,880 --> 00:00:12,080
你看看 黄花 木耳 红枣

6
00:00:12,080 --> 00:00:14,000
蒸的时候 必须加点肥膘

7
00:00:14,000 --> 00:00:17,120
我们过去是加网油 现在咱没有了

8
00:00:17,120 --> 00:00:19,360
咱就使点肥肉片将就将就

9
00:00:19,360 --> 00:00:20,600
你先铰着鱼

10
00:00:20,600 --> 00:00:24,680

11
00:00:24,680 --> 00:00:26,920
其实按理说 这还缺一道工序呢

12
00:00:26,920 --> 00:00:28,440
得烫一下

13
00:00:28,440 --> 00:00:31,440
今儿咱就不烫了

14
00:00:31,440 --> 00:00:33,200
修理修理就行了

15
00:00:33,200 --> 00:00:36,800
咱先给它改刀 先把鱼头给它拿掉

16
00:00:36,800 --> 00:00:42,080

17
00:00:42,080 --> 00:00:44,920
今天做的菜是老菜老味道的

18
00:00:44,920 --> 00:00:47,840
古法蒸武昌鱼

19
00:00:47,840 --> 00:00:51,200
但是我们这方法要搁到其他菜系

20
00:00:51,200 --> 00:00:53,080
我们就是新方法

21
00:00:53,080 --> 00:00:57,880
借鉴其他菜系的一个特点是吧

22
00:00:57,880 --> 00:00:59,840

23
00:00:59,840 --> 00:01:01,520
再给它腌一下

24
00:01:01,520 --> 00:01:05,800
盐 胡椒粉 葱姜 料酒

25
00:01:05,800 --> 00:01:09,760

26
00:01:09,760 --> 00:01:10,880
搓匀了

27
00:01:10,880 --> 00:01:11,200

28
00:01:11,200 --> 00:01:12,440
没问题可以了 入了味

29
00:01:12,440 --> 00:01:13,920
把盘儿拿过来

30
00:01:13,920 --> 00:01:15,040
再给它切切

31
00:01:15,040 --> 00:01:18,000
这样的在家合适 便于食用

32
00:01:18,000 --> 00:01:19,760
摆成扇形的 这不就行了么

33
00:01:19,760 --> 00:01:21,120
这不就孔雀开屏了么

34
00:01:21,120 --> 00:01:23,920
肥肉片 搁两片

35
00:01:27,040 --> 00:01:28,920
借点肉片的香味儿

36
00:01:28,920 --> 00:01:30,760
待会葱姜给它挑出来

37
00:01:30,760 --> 00:01:31,440

38
00:01:31,440 --> 00:01:32,960
该调汁儿了吧咱们

39
00:01:32,960 --> 00:01:34,440

40
00:01:34,440 --> 00:01:37,440
黄花 整齐点 够吗师父 够

41
00:01:37,440 --> 00:01:39,200
师弟这都弄好了是吧

42
00:01:39,200 --> 00:01:40,000
里边都什么

43
00:01:40,000 --> 00:01:42,120
枣 木耳 黄花

44
00:01:42,120 --> 00:01:44,600
这个菜营养丰富

45
00:01:44,600 --> 00:01:46,880
而且跟这搭配的也好 荤素搭配

46
00:01:46,880 --> 00:01:47,640
要么说古法呢

47
00:01:47,640 --> 00:01:49,440
然后咱调蚝油呗

48
00:01:49,440 --> 00:01:50,960
蚝油有一勺

49
00:01:50,960 --> 00:01:53,000
再来一勺也行

50
00:01:53,000 --> 00:01:54,160

51
00:01:54,160 --> 00:01:55,720
胡椒粉 别太多了

52
00:01:56,680 --> 00:01:57,720
搁点糖吧师父

53
00:01:57,720 --> 00:02:00,080
糖来一点 来一点点 千万别多

54
00:02:00,080 --> 00:02:01,440
糖提鲜的

55
00:02:01,440 --> 00:02:02,680
来点料酒

56
00:02:02,680 --> 00:02:06,160
来点豉油 多来点没事

57
00:02:06,160 --> 00:02:07,000

58
00:02:07,000 --> 00:02:08,440
粉子抓匀了它

59
00:02:08,440 --> 00:02:09,760
为什么加粉子

60
00:02:09,760 --> 00:02:13,400
加完粉子以后 它那个汁就凝固了

61
00:02:13,400 --> 00:02:14,920
再来点儿粉子

62
00:02:14,920 --> 00:02:18,920

63
00:02:18,920 --> 00:02:21,040
来点葱油一拌 齐了

64
00:02:21,040 --> 00:02:24,440

65
00:02:24,440 --> 00:02:25,320
真漂亮

66
00:02:26,200 --> 00:02:28,520
放在上面让它铺开了 蒸蒸就行了

67
00:02:28,520 --> 00:02:29,160

68
00:02:29,160 --> 00:02:31,520
这时候你看 这葱油

69
00:02:31,520 --> 00:02:32,920
为什么有的蒸完不润呢

70
00:02:32,920 --> 00:02:34,200
一个是亮

71
00:02:34,200 --> 00:02:36,480
第二个搁完这油还锁住水分 增香

72
00:02:36,480 --> 00:02:37,560
它还去腥

73
00:02:37,560 --> 00:02:39,600

74
00:02:39,600 --> 00:02:41,040
准备好了 这就对了

75
00:02:41,480 --> 00:02:43,840
接下来就该蒸了吧

76
00:02:43,840 --> 00:02:46,120

77
00:02:46,120 --> 00:02:47,160
现在闻着就香

78
00:02:47,160 --> 00:02:48,200
那还用说

79
00:02:48,200 --> 00:02:52,240
今天有师父跟梅哥给站脚助威

80
00:02:52,240 --> 00:02:53,680
我心里更有底了

81
00:02:54,200 --> 00:02:57,440
这道菜专门走宴会 接待外宾

82
00:02:57,440 --> 00:02:59,560
古法蒸排骨 古法蒸鸡都行

83
00:02:59,560 --> 00:03:02,280
因为它既保持了食材的新鲜味道

84
00:03:02,280 --> 00:03:04,400
又借助了一些辅料的味道 都好吃

85
00:03:04,400 --> 00:03:05,840
锅开了咱们准备蒸

86
00:03:05,840 --> 00:03:07,040
必须得旺火蒸

87
00:03:07,040 --> 00:03:09,440

88
00:03:09,440 --> 00:03:11,160
上锅喽

89
00:03:11,160 --> 00:03:14,520
蒸完了再浇点油一呲 行了

90
00:03:15,360 --> 00:03:17,480
咱家里的火必须大火

91
00:03:17,480 --> 00:03:19,280
旺火速成十分钟

92
00:03:19,280 --> 00:03:21,680
这边蒸着咱喝点水去 师父喝点水

93
00:03:21,680 --> 00:03:22,880
师父歇会儿

94
00:03:22,880 --> 00:03:25,080
好 时间到

95
00:03:25,080 --> 00:03:29,960

96
00:03:29,960 --> 00:03:31,320
非常漂亮

97
00:03:31,320 --> 00:03:33,240
这怎么看不见啊这个

98
00:03:33,240 --> 00:03:35,880

99
00:03:35,880 --> 00:03:36,800
这就行了

100
00:03:38,200 --> 00:03:41,240
扎一下看熟没熟 熟了

101
00:03:41,240 --> 00:03:43,240
一道美味营养的

102
00:03:43,240 --> 00:03:45,280
古法蒸武昌鱼 出锅了

103
00:03:45,280 --> 00:03:46,760
葱姜挑出去

104
00:03:46,760 --> 00:03:49,280

105
00:03:49,280 --> 00:03:50,440
我来师父

106
00:03:50,440 --> 00:03:54,600

107
00:03:54,600 --> 00:03:57,800
这鱼还真漂亮 加上粉子还贼亮 真香嘿

108
00:03:57,800 --> 00:04:00,200
葱油 这葱油好

109
00:04:00,200 --> 00:04:01,560
把汁给它倒一下

110
00:04:01,560 --> 00:04:03,040
底下那个（汁儿）就不要了

111
00:04:03,280 --> 00:04:05,720
待会呲点油 再淋点鱼汁

112
00:04:05,720 --> 00:04:06,120

113
00:04:06,120 --> 00:04:09,560
没问题 好 漂亮啊

114
00:04:09,560 --> 00:04:11,440
开下火准备呲油

115
00:04:11,440 --> 00:04:13,800
葱姜丝撒上

116
00:04:13,800 --> 00:04:15,040
来点胡椒粉

117
00:04:16,160 --> 00:04:18,680
二合油 香油

118
00:04:18,680 --> 00:04:20,080
倒点香油

119
00:04:20,080 --> 00:04:24,840
葱油加香油 古法武昌鱼

120
00:04:24,840 --> 00:04:26,800
温度得够啊 平地一声雷

121
00:04:26,800 --> 00:04:28,080
照中间呲

122
00:04:28,080 --> 00:04:30,680

123
00:04:30,680 --> 00:04:31,960
再给来点汁（豉油）

124
00:04:31,960 --> 00:04:35,280
顺着边儿上 好喽

125
00:04:35,280 --> 00:04:38,360
再来点 满锅的烟火气

127
00:04:38,360 --> 00:04:42,240
顺着边上 你看这鱼汁的味儿这香

128
00:04:42,240 --> 00:04:46,280
别弄鱼上 让它四周围

129
00:04:46,280 --> 00:04:48,120

130
00:04:48,120 --> 00:04:53,400
这个菜在之前 我跟小魏一块探讨

131
00:04:53,400 --> 00:04:56,920
就说一定要把这菜做成经典

132
00:04:56,920 --> 00:04:59,080
因为武汉YQ马上就结束了

133
00:04:59,080 --> 00:05:03,000
我们要把这份爱献给武汉人民

134
00:05:03,520 --> 00:05:04,600
作为我们厨师

135
00:05:04,600 --> 00:05:07,400
尽我们的所有的这份心思

136
00:05:07,400 --> 00:05:08,800
全倾注到这份菜上了

137
00:05:08,800 --> 00:05:12,400
有木耳 有红枣 有黄花

138
00:05:12,400 --> 00:05:14,320
黄花又叫忘忧草

139
00:05:14,320 --> 00:05:15,920
吃完了以后心情愉悦

140
00:05:15,920 --> 00:05:19,280
我们战胜了YQ

141
00:05:19,280 --> 00:05:22,200
为武汉加油 为中国加油

142
00:05:22,200 --> 00:05:23,480
这话说得太对了

143
00:05:23,480 --> 00:05:25,480
感谢师傅 感谢梅师兄

144
00:05:25,480 --> 00:05:27,720
咱们开始尝尝吧

145
00:05:27,720 --> 00:05:28,680

146
00:05:28,680 --> 00:05:32,280
我在这闻 就这个香味扑鼻

147
00:05:32,280 --> 00:05:34,200

148
00:05:34,200 --> 00:05:36,520
而且一下子想到了二十年前

149
00:05:36,520 --> 00:05:38,760
跟师父在TLWC的时候

150
00:05:38,760 --> 00:05:40,040
出这道菜

151
00:05:40,040 --> 00:05:41,400
那时候我还年轻呢是吧

152
00:05:41,400 --> 00:05:43,240
这一晃六十多了

153
00:05:43,240 --> 00:05:45,200
这个菜我就不用评价

154
00:05:45,200 --> 00:05:47,440
能把二十多年前

155
00:05:47,440 --> 00:05:52,000
我们这份心思能够传承到现在

156
00:05:52,000 --> 00:05:54,240
师父足矣

157
00:05:54,240 --> 00:05:57,480
咱们要做菜就去用心做

158
00:05:57,480 --> 00:06:00,880
搁到今天 今天我可以这么说

159
00:06:00,880 --> 00:06:03,120
这道菜 依然不落后

160
00:06:03,120 --> 00:06:04,880
所以说我希望你用心

161
00:06:04,880 --> 00:06:07,320
把这份情感的东西给传承下去

162
00:06:07,320 --> 00:06:09,120
比什么都重要

163
00:06:09,120 --> 00:06:10,640
咱们一块鱼 再蘸点汁

164
00:06:10,640 --> 00:06:12,280
还得蘸点黄花木耳吃

165
00:06:12,280 --> 00:06:14,200

166
00:06:14,200 --> 00:06:15,080
真好

167
00:06:15,080 --> 00:06:17,600
又鲜 又滑 又有回味

168
00:06:17,600 --> 00:06:19,320
武汉好久不见

169
00:06:19,320 --> 00:06:20,760
中国加油

170
00:06:20,760 --> 00:06:22,200
黄花木耳蒸的比这鱼还好吃

```

**Comment by 3yearsyoung** [comment]
认领

**Comment by 3yearsyoung** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•清蒸武昌鱼】国宴佳肴！二伯传承20多年的古法蒸武昌鱼，极鲜极嫩，倾注了二叔所有心思，为武汉加油！|老饭骨
State Banquet Master Chef - Steamed Wuchang Fish. Made with Er Bai’s love and 20+ years of experience. Incredibly umami and tender. Cheers for Wuhan!

简介
小友们好，今天带来一道二伯传承了20多年的菜——古法蒸武昌鱼！
Hello everyone! Today, Er Bai will bring us a dish he has been cooking for more than 20 years - Old School Steamed Wuchang Fish!
这道菜也是一道国宴佳肴，今天就教小友们如何在家制作这道菜！
It is also one of the State Banquet dishes, and Er Bai will teach us how to make it at home today!
古法蒸武昌鱼的秘诀在于要放葱油，这样能在蒸的时候锁住水分，让鱼更加鲜嫩喷香！
The secret of the Old School Steamed Wuchang Fish is to add spring onion oil when steaming to seal the moisture in the fish, and as a result, the fish will be extra umami, tender and fragrant!
也希望通过这道菜，能够传递出二伯的满满心意，祝全球的小友们都能元气满满，蒸蒸日上！
Er Bai hopes to pass on all his love to Wuhan with this dish, and we wish all fans across the world to stay strong and healthy! Good luck!
同时奉上之前“烫鱼”步骤的【汗蒸鱼】视频链接⬇️
Check out how to blanch the fish for steamed fish dishes via the link below
【传统名菜汗蒸鱼Steamed fish】https://youtu.be/M6o5GfjK9CE

字幕
1
00:00:00,000 --> 00:00:02,240
别弄鱼上 让它四周围
Don’t pour the sauce over the fish, instead, spread it around the fish

2
00:00:02,240 --> 00:00:04,280

3
00:00:04,280 --> 00:00:07,560
古法蒸武昌鱼 武汉好久不见
Old School Steamed Wuchang Fish. Wuhan, long time no see

4
00:00:07,560 --> 00:00:08,880
都什么食材啊
What ingredients do you have here?

5
00:00:08,880 --> 00:00:12,080
你看看 黄花 木耳 红枣
Look, we have daylilies, black fungus, red dates

6
00:00:12,080 --> 00:00:14,000
蒸的时候 必须加点肥膘
And some fatty pork to put on the fish when steaming

7
00:00:14,000 --> 00:00:17,120
我们过去是加网油 现在咱没有了
We used to add caul fat, but now we don’t have that anymore

8
00:00:17,120 --> 00:00:19,360
咱就使点肥肉片将就将就
So we just use the fatty pork as an alternative

9
00:00:19,360 --> 00:00:20,600
你先铰着鱼
Trim the fish first

10
00:00:20,600 --> 00:00:24,680

11
00:00:24,680 --> 00:00:26,920
其实按理说 这还缺一道工序呢
To be honest, there should be another step here

12
00:00:26,920 --> 00:00:28,440
得烫一下
We need to blanch the fish

13
00:00:28,440 --> 00:00:31,440
今儿咱就不烫了
We are not blanching it today

14
00:00:31,440 --> 00:00:33,200
修理修理就行了
We will just trim it

15
00:00:33,200 --> 00:00:36,800
咱先给它改刀 先把鱼头给它拿掉
Let’s score the fish. Firstly, cut off its head

16
00:00:36,800 --> 00:00:42,080

17
00:00:42,080 --> 00:00:44,920
今天做的菜是老菜老味道的
We are presenting the old school flavour in our dish today

18
00:00:44,920 --> 00:00:47,840
古法蒸武昌鱼
Old School Steamed Wuchang Fish

19
00:00:47,840 --> 00:00:51,200
但是我们这方法要搁到其他菜系
But if we put this method in other cuisines

20
00:00:51,200 --> 00:00:53,080
我们就是新方法
It would be regarded creative

21
00:00:53,080 --> 00:00:57,880
借鉴其他菜系的一个特点是吧
That’s a characteristic of getting inspirations from another cuisine

22
00:00:57,880 --> 00:00:59,840

23
00:00:59,840 --> 00:01:01,520
再给它腌一下
Next, marinate the fish

24
00:01:01,520 --> 00:01:05,800
盐 胡椒粉 葱姜 料酒
Salt, pepper, spring onions, ginger, and Chinese cooking wine

25
00:01:05,800 --> 00:01:09,760

26
00:01:09,760 --> 00:01:10,880
搓匀了
Massage the marinade evenly on the fish

27
00:01:10,880 --> 00:01:11,200

28
00:01:11,200 --> 00:01:12,440
没问题可以了 入了味
The fish should have absorbed all the favours by now

29
00:01:12,440 --> 00:01:13,920
把盘儿拿过来
Pass me the plate

30
00:01:13,920 --> 00:01:15,040
再给它切切
Cut the fish into smaller pieces

31
00:01:15,040 --> 00:01:18,000
这样的在家合适 便于食用
It suits home cooking, and the fish will be easier to eat

32
00:01:18,000 --> 00:01:19,760
摆成扇形的 这不就行了么
Present the fish in a fan shape. That’s nice

33
00:01:19,760 --> 00:01:21,120
这不就孔雀开屏了么
It looks like a peacock spreading its tails

34
00:01:21,120 --> 00:01:23,920
肥肉片 搁两片
Put on some fatty pork

35
00:01:27,040 --> 00:01:28,920
借点肉片的香味儿
Which gives the fish some meaty aroma

36
00:01:28,920 --> 00:01:30,760
待会葱姜给它挑出来
Discard the spring onions and ginger later

37
00:01:30,760 --> 00:01:31,440

38
00:01:31,440 --> 00:01:32,960
该调汁儿了吧咱们
We should start preparing the sauce

39
00:01:32,960 --> 00:01:34,440

40
00:01:34,440 --> 00:01:37,440
黄花 整齐点 够吗师父 够
Daylilies. Cut them neatly. Are these enough, Shifu? Yes

41
00:01:37,440 --> 00:01:39,200
师弟这都弄好了是吧
Shidi, these are all done right?

42
00:01:39,200 --> 00:01:40,000
里边都什么
What do we have in there?

43
00:01:40,000 --> 00:01:42,120
枣 木耳 黄花
Red dates, black fungus, and daylilies

44
00:01:42,120 --> 00:01:44,600
这个菜营养丰富
This dish is full of nutrition

45
00:01:44,600 --> 00:01:46,880
而且跟这搭配的也好 荤素搭配
And it’s well-balanced with fish and veggies

46
00:01:46,880 --> 00:01:47,640
要么说古法呢
That’s what we call ‘Old School’

47
00:01:47,640 --> 00:01:49,440
然后咱调蚝油呗
Then, oyster sauce

48
00:01:49,440 --> 00:01:50,960
蚝油有一勺
One tablespoon

49
00:01:50,960 --> 00:01:53,000
再来一勺也行
Maybe another spoonful

50
00:01:53,000 --> 00:01:54,160

51
00:01:54,160 --> 00:01:55,720
胡椒粉 别太多了
Ground pepper. Not too much

52
00:01:56,680 --> 00:01:57,720
搁点糖吧师父
Shall we add some sugar, Shifu?

53
00:01:57,720 --> 00:02:00,080
糖来一点 来一点点 千万别多
Just a little bit. Never put too much sugar

54
00:02:00,080 --> 00:02:01,440
糖提鲜的
Sugar is there to lift the umami

55
00:02:01,440 --> 00:02:02,680
来点料酒
Some Chinese cooking wine

56
00:02:02,680 --> 00:02:06,160
来点豉油 多来点没事
Some soy sauce. Generous amounts of it

57
00:02:06,160 --> 00:02:07,000

58
00:02:07,000 --> 00:02:08,440
粉子抓匀了它
Rub in some corn flour evenly

59
00:02:08,440 --> 00:02:09,760
为什么加粉子
Why corn flour?

60
00:02:09,760 --> 00:02:13,400
加完粉子以后 它那个汁就凝固了
The sauce will become viscous after adding it

61
00:02:13,400 --> 00:02:14,920
再来点儿粉子
A bit more corn flour

62
00:02:14,920 --> 00:02:18,920

63
00:02:18,920 --> 00:02:21,040
来点葱油一拌 齐了
Mix in some spring onion oil. That’s it

64
00:02:21,040 --> 00:02:24,440

65
00:02:24,440 --> 00:02:25,320
真漂亮
How gorgeous!

66
00:02:26,200 --> 00:02:28,520
放在上面让它铺开了 蒸蒸就行了
Spread them on the fish and they will be steamed at the same time

67
00:02:28,520 --> 00:02:29,160

68
00:02:29,160 --> 00:02:31,520
这时候你看 这葱油
Now look, more spring onion oil

69
00:02:31,520 --> 00:02:32,920
为什么有的蒸完不润呢
Why are some fish not moist after steaming?

70
00:02:32,920 --> 00:02:34,200
一个是亮
Firstly, it brightens the dish

71
00:02:34,200 --> 00:02:36,480
第二个搁完这油还锁住水分 增香
Secondly, it seals the moisture in the fish, and increases the aroma

72
00:02:36,480 --> 00:02:37,560
它还去腥
And it also removes the odour

73
00:02:37,560 --> 00:02:39,600

74
00:02:39,600 --> 00:02:41,040
准备好了 这就对了
All prepared. Wonderful

75
00:02:41,480 --> 00:02:43,840
接下来就该蒸了吧
Now it’s time for steaming

76
00:02:43,840 --> 00:02:46,120

77
00:02:46,120 --> 00:02:47,160
现在闻着就香
It already smells so fragrant

78
00:02:47,160 --> 00:02:48,200
那还用说
Of course

79
00:02:48,200 --> 00:02:52,240
今天有师父跟梅哥给站脚助威
I have Shifu and Mei Ge to help and support me today

80
00:02:52,240 --> 00:02:53,680
我心里更有底了
I’m much more confident

81
00:02:54,200 --> 00:02:57,440
这道菜专门走宴会 接待外宾
This dish is exclusively served in State Banquets to welcome foreign guests

82
00:02:57,440 --> 00:02:59,560
古法蒸排骨 古法蒸鸡都行
You can replace the fish with pork ribs or chicken if you want

83
00:02:59,560 --> 00:03:02,280
因为它既保持了食材的新鲜味道
Because it not only keeps the fresh taste of the main ingredient

84
00:03:02,280 --> 00:03:04,400
又借助了一些辅料的味道 都好吃
But also expresses the flavours from the minor ingredients, and they all taste great

85
00:03:04,400 --> 00:03:05,840
锅开了咱们准备蒸
Water is boiling. Let’s steam the fish

86
00:03:05,840 --> 00:03:07,040
必须得旺火蒸
You must use high heat

87
00:03:07,040 --> 00:03:09,440

88
00:03:09,440 --> 00:03:11,160
上锅喽
Into the pot

89
00:03:11,160 --> 00:03:14,520
蒸完了再浇点油一呲 行了
Pour some sizzling oil on the fish after steaming. That sounds amazing

90
00:03:15,360 --> 00:03:17,480
咱家里的火必须大火
We must use high heat when cooking at home

91
00:03:17,480 --> 00:03:19,280
旺火速成十分钟
And it just takes 10 minutes

92
00:03:19,280 --> 00:03:21,680
这边蒸着咱喝点水去 师父喝点水
While it’s steaming, let’s drink some water. Drink some water, Shifu

93
00:03:21,680 --> 00:03:22,880
师父歇会儿
Take some rest, Shifu

94
00:03:22,880 --> 00:03:25,080
好 时间到
Alright, time is up

95
00:03:25,080 --> 00:03:29,960

96
00:03:29,960 --> 00:03:31,320
非常漂亮
Exceptionally beautiful

97
00:03:31,320 --> 00:03:33,240
这怎么看不见啊这个
Why can’t I see it?

98
00:03:33,240 --> 00:03:35,880

99
00:03:35,880 --> 00:03:36,800
这就行了
It should be fine now

100
00:03:38,200 --> 00:03:41,240
扎一下看熟没熟 熟了
Stick the knife into the fish to check if it is cooked. Yes, it’s perfectly done

101
00:03:41,240 --> 00:03:43,240
一道美味营养的
Take the delicious and nutritious

102
00:03:43,240 --> 00:03:45,280
古法蒸武昌鱼 出锅了
Old School Steamed Wuchang Fish out of the pot

103
00:03:45,280 --> 00:03:46,760
葱姜挑出去
Discard the spring onions and ginger

104
00:03:46,760 --> 00:03:49,280

105
00:03:49,280 --> 00:03:50,440
我来师父
Leave it to me, Shifu

106
00:03:50,440 --> 00:03:54,600

107
00:03:54,600 --> 00:03:57,800
这鱼还真漂亮 加上粉子还贼亮 真香嘿
This fish looks so lovely, and so shinny thanks to the corn flour. It’s so fragrant

108
00:03:57,800 --> 00:04:00,200
葱油 这葱油好
The spring onion oil is fantastic

109
00:04:00,200 --> 00:04:01,560
把汁给它倒一下
Discard the juice

110
00:04:01,560 --> 00:04:03,040
底下那个（汁儿）就不要了
We don’t need the juice on the bottom there

111
00:04:03,280 --> 00:04:05,720
待会呲点油 再淋点鱼汁
We will pour some sizzling oil and soy sauce in a minute

112
00:04:05,720 --> 00:04:06,120

113
00:04:06,120 --> 00:04:09,560
没问题 好 漂亮啊
Well done. Good job!

114
00:04:09,560 --> 00:04:11,440
开下火准备呲油
Turn on the heat. Let’s prepare the sizzling oil

115
00:04:11,440 --> 00:04:13,800
葱姜丝撒上
Put some juliennes of spring onions and ginger on the fish

116
00:04:13,800 --> 00:04:15,040
来点胡椒粉
Some ground pepper

117
00:04:16,160 --> 00:04:18,680
二合油 香油
Two types of oil are mixed together. Some sesame oil here

118
00:04:18,680 --> 00:04:20,080
倒点香油
Add in some sesame oil

119
00:04:20,080 --> 00:04:24,840
葱油加香油 古法武昌鱼
Spring onion oil plus sesame oil. Old School Steamed Wuchang Fish

120
00:04:24,840 --> 00:04:26,800
温度得够啊 平地一声雷
The temperature must be high enough, so it sizzles loudly like the thunder

121
00:04:26,800 --> 00:04:28,080
照中间呲
Pour in the centre of the dish

122
00:04:28,080 --> 00:04:30,680

123
00:04:30,680 --> 00:04:31,960
再给来点汁（豉油）
Add in some soy sauce

124
00:04:31,960 --> 00:04:35,280
顺着边儿上 好喽
From the edge of the wok. Nicely done

125
00:04:35,280 --> 00:04:38,360
再来点 满锅的烟火气
A bit more. A wokful of smoky flavour

127
00:04:38,360 --> 00:04:42,240
顺着边上 你看这鱼汁的味儿这香
Pour the sauce around the fish. This soy sauce smells so aromatic

128
00:04:42,240 --> 00:04:46,280
别弄鱼上 让它四周围
Don’t pour the sauce over the fish, instead, spread it around the fish

129
00:04:46,280 --> 00:04:48,120

130
00:04:48,120 --> 00:04:53,400
这个菜在之前 我跟小魏一块探讨
Before cooking this dish, I have been discussing it with Xiao Wei

131
00:04:53,400 --> 00:04:56,920
就说一定要把这菜做成经典
We agree that we must make this dish a classic

132
00:04:56,920 --> 00:04:59,080
因为武汉YQ马上就结束了
As the COVID-19 outbreak is about to end in Wuhan

133
00:04:59,080 --> 00:05:03,000
我们要把这份爱献给武汉人民
We would like to share our love to the people in Wuhan

134
00:05:03,520 --> 00:05:04,600
作为我们厨师
Being chefs like us

135
00:05:04,600 --> 00:05:07,400
尽我们的所有的这份心思
We do our best and put all our care and love

136
00:05:07,400 --> 00:05:08,800
全倾注到这份菜上了
Onto this dish

137
00:05:08,800 --> 00:05:12,400
有木耳 有红枣 有黄花
We have black fungus, red dates, and daylilies

138
00:05:12,400 --> 00:05:14,320
黄花又叫忘忧草
Daylilies are also called ‘Forgetting Sorrow’

139
00:05:14,320 --> 00:05:15,920
吃完了以后心情愉悦
You will become much happier after eating them

140
00:05:15,920 --> 00:05:19,280
我们战胜了YQ
We have defeated COVID-19

141
00:05:19,280 --> 00:05:22,200
为武汉加油 为中国加油
Cheers for Wuhan, and cheers for China

142
00:05:22,200 --> 00:05:23,480
这话说得太对了
You are absolutely right. Well spoken

143
00:05:23,480 --> 00:05:25,480
感谢师傅 感谢梅师兄
Thanks to Shifu and Mei Ge

144
00:05:25,480 --> 00:05:27,720
咱们开始尝尝吧
Let’s eat!

145
00:05:27,720 --> 00:05:28,680

146
00:05:28,680 --> 00:05:32,280
我在这闻 就这个香味扑鼻
I’m smelling the dish, and the fragrance is so mouth-watering

147
00:05:32,280 --> 00:05:34,200

148
00:05:34,200 --> 00:05:36,520
而且一下子想到了二十年前
And it reminds me of the time when I worked with Shifu at TLWC

149
00:05:36,520 --> 00:05:38,760
跟师父在TLWC的时候
20 years ago

150
00:05:38,760 --> 00:05:40,040
出这道菜
And we served this dish

151
00:05:40,040 --> 00:05:41,400
那时候我还年轻呢是吧
I was still young at that time

152
00:05:41,400 --> 00:05:43,240
这一晃六十多了
With a blink of eyes, I’m in my 60s now

153
00:05:43,240 --> 00:05:45,200
这个菜我就不用评价
I don’t need to comment on this dish

154
00:05:45,200 --> 00:05:47,440
能把二十多年前
Being able to pass on our love and thoughts

155
00:05:47,440 --> 00:05:52,000
我们这份心思能够传承到现在
From 20 years ago till now

156
00:05:52,000 --> 00:05:54,240
师父足矣
As your Shifu, I’m so satisfied

157
00:05:54,240 --> 00:05:57,480
咱们要做菜就去用心做
We must cook with our heart

158
00:05:57,480 --> 00:06:00,880
搁到今天 今天我可以这么说
Even today, I can still confidently say

159
00:06:00,880 --> 00:06:03,120
这道菜 依然不落后
That this dish is never out of fashion

160
00:06:03,120 --> 00:06:04,880
所以说我希望你用心
So, I hope you cook with your heart

161
00:06:04,880 --> 00:06:07,320
把这份情感的东西给传承下去
And pass this passion and emotion onto the next generation

162
00:06:07,320 --> 00:06:09,120
比什么都重要
This is more important than anything else

163
00:06:09,120 --> 00:06:10,640
咱们一块鱼 再蘸点汁
Pick up one piece of fish, and dip it in the sauce 

164
00:06:10,640 --> 00:06:12,280
还得蘸点黄花木耳吃
Eat it with some daylilies and black fungus

165
00:06:12,280 --> 00:06:14,200

166
00:06:14,200 --> 00:06:15,080
真好
So yummy

167
00:06:15,080 --> 00:06:17,600
又鲜 又滑 又有回味
It’s umami, moist, and has a brilliant aftertaste

168
00:06:17,600 --> 00:06:19,320
武汉好久不见
Wuhan, long time no see

169
00:06:19,320 --> 00:06:20,760
中国加油
Cheers for China

170
00:06:20,760 --> 00:06:22,200
黄花木耳蒸的比这鱼还好吃
The steamed daylilies and black fungus are even tastier than the fish
