### ISSUE TITLE
【美食作家王刚】川味烧茄子 - https://youtu.be/0seR92vpTMc

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#938]
**视频链接**：https://youtu.be/0seR92vpTMc

视频时长5:39，预计发布时间为北京时间4月22日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“川味烧茄子”的家常做法，口感软嫩，特别适合牙口不好的老人

简介
大家好，今天和大家分享一道经典四川家常味道“烧茄子”，茄子过油之后和炒香的豆瓣酱，蒜末，泡椒一起收汁，最后加入葱花和藿香，一道川味烧茄子就可以出锅了。茄子特别入味并且软嫩，适合牙口不好的老人，并且特别下饭，虽说是道素菜但却和肉一样香！

字幕
0:00:00.219,0:00:03.115
嗨喽大家好 今天跟大家分享一个烧茄子

0:00:03.689,0:00:05.155
我四伯爷牙口不好 

0:00:05.277,0:00:08.857
这个茄子烧软一点特别适合你的胃口噶

0:00:08.882,0:00:09.260
嗯

0:00:13.231,0:00:16.505
我们选这个茄子的时候选这个白色比较多的

0:00:16.603,0:00:18.423
然后选这个颜色浅一点的

0:00:19.059,0:00:22.003
然后你捏一下软的再买

0:00:22.113,0:00:24.178
如果是硬的话就说明中间已经长老了 

0:00:24.251,0:00:25.571
就不要再买了那个是老茄子

0:00:27.941,0:00:30.568
如果我们买菜每个都去跟他捏一哈的话

0:00:30.873,0:00:32.731
那个商贩要起火噶

0:00:33.891,0:00:35.907
看吗又看出来了嘛老嫩

0:00:37.006,0:00:37.299
嗯

0:00:41.258,0:00:44.801
我们烧这个茄子非常简单 （重要配料）只要大蒜

0:00:46.120,0:00:47.672
多吃点蒜有好处噶 四伯爷

0:00:47.831,0:00:48.393
是安

0:00:50.458,0:00:51.105
轻轻地拍哈

0:00:58.106,0:01:01.001
我们的烧茄子这个鱼香烧起是最安逸的

0:01:01.453,0:01:04.007
我们这里这个鱼香其实就是藿香

0:01:05.754,0:01:08.087
再放两颗泡海椒

0:01:09.737,0:01:11.288
这个泡海椒我听到说多辣安

0:01:11.618,0:01:12.339
是辣得很呢

0:01:13.439,0:01:16.386
这个就是我们的鱼香

0:01:17.532,0:01:19.108
闻起来有股特殊的香味

0:01:19.376,0:01:20.427
吃得来的就吃得来

0:01:20.439,0:01:24.312
吃不来的就像不能吃香菜的人吃香菜一样 感觉这个很臭

0:01:24.593,0:01:25.815
其实我们特别喜欢这个

0:01:26.218,0:01:28.173
这个烧鱼特别香特别好吃

0:01:30.445,0:01:33.830
还有我们做豆花（蘸水）这个是少不了的 

0:01:35.088,0:01:38.350
这个给它切一下 当那个葱花起锅的时候用

0:01:43.689,0:01:44.532
然后再切点葱葱

0:01:49.883,0:01:52.987
这个鱼香吗可以说在我们四川没得哪个吃不来的

0:01:53.842,0:01:55.039
还是有少数

0:01:55.100,0:01:56.957
吃不来的就是极少数

0:01:57.923,0:01:59.340
首先我们把锅烧热

0:02:02.044,0:02:03.644
锅烧热之后加入宽油

0:02:09.334,0:02:11.179
然后大火将油温烧至6成热

0:02:16.334,0:02:18.570
油温6成热之后下入切好的茄子

0:02:22.064,0:02:24.740
开中火把茄子炸熟炸至金黄色

0:02:25.149,0:02:26.885
嘿 看到好安逸哦噶

0:02:28.637,0:02:30.299
同学们这里有一个小技巧

0:02:30.458,0:02:34.123
就是炸茄子的时候必须随时搅动让茄子均匀受热

0:02:34.318,0:02:36.689
如果茄子不翻动的话特别容易炸糊

0:02:38.008,0:02:39.975
茄子炸到金黄之后捞出备用

0:02:41.857,0:02:44.544
然后我们把宽油倒出之后下一步开始准备炒制

0:02:47.806,0:02:50.238
在这里应伯爷的要求加入了一些猪油

0:02:53.194,0:02:55.797
油烧热烧化之后加入切好的料头爆香

0:03:00.720,0:03:03.029
料头爆香之后加入适量的豆瓣酱炒香

0:03:14.233,0:03:15.613
然后加入炸好的茄子

0:03:16.127,0:03:17.580
下一步直接开始调味

0:03:18.741,0:03:20.207
锅中加入适量的食用盐

0:03:20.745,0:03:21.356
白糖

0:03:23.054,0:03:23.628
味精

0:03:24.923,0:03:25.693
再放点酱油

0:03:27.929,0:03:29.957
最后加入适量的水淀粉翻炒几下

0:03:33.402,0:03:37.446
芡粉糊化之后加入鱼香叶和小葱翻炒几下即可出锅装盘

0:03:50.028,0:03:51.147
尝哈看茄子 四伯爷

0:03:52.054,0:03:54.038
哎呀不消尝的 这个茄子都好干

0:03:54.079,0:03:54.638
好干噶

0:03:56.470,0:03:56.856
哎呀

0:03:57.184,0:03:57.897
烫哦

0:03:58.341,0:03:59.459
烫得很四伯爷 你小心

0:03:59.479,0:04:00.501
我清得到 

0:04:02.025,0:04:04.860
开玩笑 好多油哦

0:04:10.723,0:04:12.439
嗯 可以

0:04:14.541,0:04:18.881
如果你们家庭小灶做的话可以茄子下锅之前拍一点粉

0:04:18.881,0:04:20.848
这样更容易熟 而且还省油

0:04:24.474,0:04:27.560
又嫩又香 吃起好爽口哦

0:04:29.816,0:04:30.800
还很下饭

0:04:31.822,0:04:32.343
安逸

0:04:40.482,0:04:42.391
特别是这个鱼香才入味

0:04:42.757,0:04:43.259
嗯

0:04:45.053,0:04:46.422
真的好吃这个茄子

0:04:49.411,0:04:49.932
多吃点 

0:04:51.784,0:04:54.059
所以我喊你整这个茄子来干呢

0:04:55.506,0:04:58.487
比你在那个柴火灶里慢慢炒安逸

0:04:58.514,0:04:59.537
那当然咯

0:04:59.787,0:05:00.559
肯定咯

0:05:01.870,0:05:05.805
我们有很多粉丝做这个茄子喜欢把皮扒掉

0:05:06.325,0:05:11.224
其实正是要有这层皮才能够对比出里面的嫩

0:05:11.591,0:05:14.850
我们做这个茄子因为本身是油炸的

0:05:15.255,0:05:17.415
然后第二次炒的时候尽量要少放油

0:05:18.900,0:05:22.372
因为是我伯爷喜欢吃猪油 然后我后面都放了一点点

0:05:23.510,0:05:26.576
好 你们喜欢的话可以试一下

0:05:27.483,0:05:30.433
怕油多的话就放那个淀粉拍一下再炸

0:05:32.999,0:05:35.872
本期视频就到这里 拜拜


```

**Comment by Gavin-Geng** [comment]
认领

**Comment by Gavin-Geng** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“川味烧茄子”的家常做法，口感软嫩，特别适合牙口不好的老人
Chef Wang shares with you:" "Sichuan Eggplant", a homely dish especially suitable for the elderly with chewing problems

简介
大家好，今天和大家分享一道经典四川家常味道“烧茄子”，茄子过油之后和炒香的豆瓣酱，蒜末，泡椒一起收汁，最后加入葱花和藿香，一道川味烧茄子就可以出锅了。茄子特别入味并且软嫩，适合牙口不好的老人，并且特别下饭，虽说是道素菜但却和肉一样香！
Brief introduction
Hello everyone, today I gonna share a classic Sichuan dish with you, "Sichuan Eggplant". After eggplants being fried, sauce with doubanjiang, garlic, and pickled chili, finally add scallion and huoxiang, a Sichuan eggplant can be served. This eggplant with tender taste, which is suitable for the elderly with chewing problems, also goes well with rice.It's a vegetable dish but it tastes as good as meat.

字幕
0:00:00.219,0:00:03.115
嗨喽大家好 今天跟大家分享一个烧茄子
Hello everyone, today I'm gonna share with you a dish "Sichuan Eggplant"

0:00:03.689,0:00:05.155
我四伯爷牙口不好
My uncle's teeth are not good enough to chew things

0:00:05.277,0:00:08.857
这个茄子烧软一点特别适合你的胃口噶
so tender eggplant will really suit your appetite

0:00:08.882,0:00:09.260
嗯
Yes

0:00:13.231,0:00:16.505
我们选这个茄子的时候选这个白色比较多的
When we pick eggplants, choose the ones with more white pulp

0:00:16.603,0:00:18.423
然后选这个颜色浅一点的
and lighter in color

0:00:19.059,0:00:22.003
然后你捏一下软的再买
then pinch them, buy the soft ones

0:00:22.113,0:00:24.178
如果是硬的话就说明中间已经长老了 
If feeling hard inside, it means overgrown

0:00:24.251,0:00:25.571
就不要再买了那个是老茄子
don't buy it, that's a overgrown eggplant

0:00:27.941,0:00:30.568
如果我们买菜每个都去跟他捏一哈的话
If we all give a pinch when go grocery shopping

0:00:30.873,0:00:32.731
那个商贩要起火噶
the vendor would definitely be annoyed 

0:00:33.891,0:00:35.907
看吗又看出来了嘛老嫩
But we can't tell tender or overgrown with our eyes

0:00:37.006,0:00:37.299
嗯
You're right

0:00:41.258,0:00:44.801
我们烧这个茄子非常简单 （重要配料）只要大蒜
We cook this eggplant very simply, only with garlic (the most important ingredient)

0:00:46.120,0:00:47.672
多吃点蒜有好处噶 四伯爷
It's good to eat more garlics, uncle

0:00:47.831,0:00:48.393
是安
Yep

0:00:50.458,0:00:51.105
轻轻地拍哈
Crush lightly

0:00:58.106,0:01:01.001
我们的烧茄子这个鱼香烧起是最安逸的
The best way to cook eggplant is with "Yuxiang leaf"

0:01:01.453,0:01:04.007
我们这里这个鱼香其实就是藿香
Actually, we call "Yuxiang" "ageratum" here

0:01:05.754,0:01:08.087
再放两颗泡海椒
add two more pickled chilies

0:01:09.737,0:01:11.288
这个泡海椒我听到说多辣安
I heard this pickled chili is very hot

0:01:11.618,0:01:12.339
是辣得很呢
Yeah, extremely hot

0:01:13.439,0:01:16.386
这个就是我们的鱼香
That's our "Yuxiang"

0:01:17.532,0:01:19.108
闻起来有股特殊的香味
It smells of a special aroma

0:01:19.376,0:01:20.427
吃得来的就吃得来
people who prefer this taste will always like eating them

0:01:20.439,0:01:24.312
吃不来的就像不能吃香菜的人吃香菜一样 感觉这个很臭
and those who don't, just like people who dislike cilantro, feel very smelly

0:01:24.593,0:01:25.815
其实我们特别喜欢这个
Actually, we especially love it

0:01:26.218,0:01:28.173
这个烧鱼特别香特别好吃
It's very delicious to cook fish with it

0:01:30.445,0:01:33.830
还有我们做豆花（蘸水）这个是少不了的
also, it's an indispensable ingredient when making tofu curd(dips)

0:01:35.088,0:01:38.350
这个给它切一下 当那个葱花起锅的时候用
let me cut and use it when dish up with scallion

0:01:43.689,0:01:44.532
然后再切点葱葱
cut some scallion into pieces

0:01:49.883,0:01:52.987
这个鱼香吗可以说在我们四川没得哪个吃不来的
As for "Yuxiang", it can be said that there's no one in Sichuan can't eat

0:01:53.842,0:01:55.039
还是有少数
still some people can't

0:01:55.100,0:01:56.957
吃不来的就是极少数
but very few

0:01:57.923,0:01:59.340
首先我们把锅烧热
First, heat up the wok

0:02:02.044,0:02:03.644
锅烧热之后加入宽油
Once the wok is hot, add KuanYou (literally "broad oil")

0:02:09.334,0:02:11.179
然后大火将油温烧至6成热
Then heat the oil over a high fire until it reaches 180 °C

0:02:16.334,0:02:18.570
油温6成热之后下入切好的茄子
Add the cut eggplants

0:02:22.064,0:02:24.740
开中火把茄子炸熟炸至金黄色
fry the eggplants over medium heat until get golden brown

0:02:25.149,0:02:26.885
嘿 看到好安逸哦噶
Hey,it looks nice!

0:02:28.637,0:02:30.299
同学们这里有一个小技巧
Here's a tip for you guys

0:02:30.458,0:02:34.123
就是炸茄子的时候必须随时搅动让茄子均匀受热
when frying the eggplant, it must be stirred at any times in order to heat evenly

0:02:34.318,0:02:36.689
如果茄子不翻动的话特别容易炸糊
If we don't turn over, eggplant will be particularly easy to deep-fried coke

0:02:38.008,0:02:39.975
茄子炸到金黄之后捞出备用
After become golden brown, take them out and set aside

0:02:41.857,0:02:44.544
然后我们把宽油倒出之后下一步开始准备炒制
pour out KuanYou and prepare for the next step

0:02:47.806,0:02:50.238
在这里应伯爷的要求加入了一些猪油
At my uncle's request, I add some lard

0:02:53.194,0:02:55.797
油烧热烧化之后加入切好的料头爆香
After the oil is heated and melted, add chopped aromatics until bring out the aroma

0:03:00.720,0:03:03.029
料头爆香之后加入适量的豆瓣酱炒香
Add some doubanjiang (AKA broad bean chili paste)

0:03:14.233,0:03:15.613
然后加入炸好的茄子
add fried eggplants

0:03:16.127,0:03:17.580
下一步直接开始调味
Next step is seasoning

0:03:18.741,0:03:20.207
锅中加入适量的食用盐
Add a reasonable amount of salt

0:03:20.745,0:03:21.356
白糖
sugar

0:03:23.054,0:03:23.628
味精
MSG

0:03:24.923,0:03:25.693
再放点酱油
a little soy sauce

0:03:27.929,0:03:29.957
最后加入适量的水淀粉翻炒几下
finally add some slurry, continue to toss a few times

0:03:33.402,0:03:37.446
芡粉糊化之后加入鱼香叶和小葱翻炒几下即可出锅装盘
Once slurry melted, add Yuxiang leaves and scallions, with tossing a few times, it can be ready to plate

0:03:50.028,0:03:51.147
尝哈看茄子 四伯爷
Uncle, have a taste

0:03:52.054,0:03:54.038
哎呀不消尝的 这个茄子都好干
oh, no need to taste, it's pretty good

0:03:54.079,0:03:54.638
好干噶
Really?

0:03:56.470,0:03:56.856
哎呀
Ah!

0:03:57.184,0:03:57.897
烫哦
It's hot

0:03:58.341,0:03:59.459
烫得很四伯爷 你小心
Be careful not to burn your mouth,uncle

0:03:59.479,0:04:00.501
我清得到
I know

0:04:02.025,0:04:04.860
开玩笑 好多油哦
Kidding me? That's a lot of oil

0:04:10.723,0:04:12.439
嗯 可以
Hmm,good

0:04:14.541,0:04:18.881
如果你们家庭小灶做的话可以茄子下锅之前拍一点粉
If cooking at home, you can sprinkle some flour on the eggplants

0:04:18.881,0:04:20.848
这样更容易熟 而且还省油
that makes it easier to cook and saves oil

0:04:24.474,0:04:27.560
又嫩又香 吃起好爽口哦
It's tender and tasty

0:04:29.816,0:04:30.800
还很下饭
And also goes well with rice

0:04:31.822,0:04:32.343
安逸
Nice

0:04:40.482,0:04:42.391
特别是这个鱼香才入味
Especially this Yuxiang makes the flavor penetration

0:04:42.757,0:04:43.259
嗯
That's it

0:04:45.053,0:04:46.422
真的好吃这个茄子
This eggplant is really delicious

0:04:49.411,0:04:49.932
多吃点
Eat more

0:04:51.784,0:04:54.059
所以我喊你整这个茄子来干呢
That's why I told you to cook eggplants

0:04:55.506,0:04:58.487
比你在那个柴火灶里慢慢炒安逸
It's much better than cooking slowly in a wood stove

0:04:58.514,0:04:59.537
那当然咯
Definitely

0:04:59.787,0:05:00.559
肯定咯
Of course 

0:05:01.870,0:05:05.805
我们有很多粉丝做这个茄子喜欢把皮扒掉
We have a lot of fans who like to peel the eggplant when they cook it

0:05:06.325,0:05:11.224
其实正是要有这层皮才能够对比出里面的嫩
In fact, it is with the skin that we can compare its tender pulp inside

0:05:11.591,0:05:14.850
我们做这个茄子因为本身是油炸的
The eggplant we cooked is fried

0:05:15.255,0:05:17.415
然后第二次炒的时候尽量要少放油
so tried to use less oil when cooking for the second time

0:05:18.900,0:05:22.372
因为是我伯爷喜欢吃猪油 然后我后面都放了一点点
Cuz my uncle like lard, I put a little in it

0:05:23.510,0:05:26.576
好 你们喜欢的话可以试一下
OK, if you like it ,just have a try

0:05:27.483,0:05:30.433
怕油多的话就放那个淀粉拍一下再炸
If afraid of too much oil, sprinkle some flour on the eggplants before frying

0:05:32.999,0:05:35.872
本期视频就到这里 拜拜
So much for this video, bye for now~
