### ISSUE TITLE
[雪鱼] 肉夹馍 - https://youtu.be/VYVr_Inf2Eo

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#944]
**视频链接**：https://youtu.be/VYVr_Inf2Eo

视频时长：6min
发布日期：未发布，将于北京时间4月22日 21：00发布

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
无需翻译

简介
简介无需翻译

字幕
1
00:00:07,450 --> 00:00:08,525
肥瘦（肉）都可以吃吧

2
00:00:08,675 --> 00:00:09,875
嗯 吃

3
00:00:18,000 --> 00:00:21,375
（剁肉声）

4
00:00:44,225 --> 00:00:45,505
起个大早来买肉夹馍

5
00:00:45,505 --> 00:00:47,550
没想到有这么多人 比我还早

6
00:00:47,725 --> 00:00:49,150
这边的肉夹馍卖的比较便宜

7
00:00:49,425 --> 00:00:50,475
上次我买的时候

8
00:00:50,625 --> 00:00:52,100
别人家都是四五块钱一个

9
00:00:52,275 --> 00:00:53,950
他这边时候两块五

10
00:00:54,075 --> 00:00:57,050
不知道这么长时间过去 这边的价格怎么样

11
00:00:57,050 --> 00:00:59,000
咱们去看看吧

12
00:01:13,775 --> 00:01:15,675
顾客排队中

13
00:01:25,250 --> 00:01:27,325
我要3个标准（肥瘦）的肉夹馍

14
00:01:27,675 --> 00:01:28,750
盐味一般

15
00:01:30,075 --> 00:01:31,500
不要辣椒

16
00:01:35,250 --> 00:01:37,250
看这一锅肉 真的是饿了

17
00:01:45,425 --> 00:01:47,925
好香啊 还是熟悉的味道

18
00:01:48,675 --> 00:01:51,225
咱们买了3个脆皮肉夹馍 5元一个

19
00:01:51,400 --> 00:01:52,975
这次呢 我要的是标准（肥瘦）的

20
00:01:53,050 --> 00:01:54,600
有点肥肉带点皮

21
00:01:54,625 --> 00:01:56,750
吃起来口感没有那么干

22
00:01:57,575 --> 00:02:01,826
因为猪肉涨价了嘛 肉夹馍的价格也跟着涨了

23
00:02:01,826 --> 00:02:05,126
不过这边的生意还是很好的

24
00:02:05,126 --> 00:02:07,426
以前吃的肉夹馍 一般都是腊汁肉夹馍

25
00:02:07,850 --> 00:02:10,375
这次咱们买的是潼关肉夹馍

26
00:02:10,750 --> 00:02:13,200
它们最大的区别在于这个饼

27
00:02:14,275 --> 00:02:15,875
我先咽一下口水

28
00:02:16,025 --> 00:02:18,550
烧饼外面是非常酥脆的

29
00:02:18,750 --> 00:02:21,650
呈现这种螺旋花纹的状态

30
00:02:23,325 --> 00:02:27,175
刚出炉的肉夹馍 真是迫不及待地想咬一口

31
00:02:38,200 --> 00:02:41,950
太酥脆了 所以很容易掉渣

32
00:02:42,275 --> 00:02:44,775
饼就像千层饼 油酥饼一样

33
00:02:45,100 --> 00:02:46,625
层呢 就是一层层的

34
00:02:46,875 --> 00:02:51,425
这么一碰 饼皮都会掉下来 特别的酥脆

35
00:02:51,650 --> 00:02:54,925
肉夹馍 一口下去 不仅能够吃到烧饼的酥脆

36
00:02:55,050 --> 00:02:56,575
还有肉的咸香

37
00:02:56,800 --> 00:02:59,425
两种味道在唇齿之间交融 在打架

38
00:02:59,875 --> 00:03:02,450
仿佛都在宣示 我最好吃

39
00:03:02,725 --> 00:03:05,006
以前吃肉夹馍觉得肉很重要

40
00:03:05,075 --> 00:03:07,250
这次发现 饼也很好吃

41
00:03:08,725 --> 00:03:13,350
有的时候 这个饼的酥脆甚至可以掩盖一下肉的油腻

42
00:03:24,775 --> 00:03:27,025
顾客：我看我9点来拿馍

43
00:03:27,500 --> 00:03:30,475
你9点来拿 我给你留着 馍还热乎

44
00:03:33,675 --> 00:03:35,600
你要瘦的还是肥的（肉）

45
00:03:35,725 --> 00:03:38,250
有点肥也行

46
00:03:40,500 --> 00:03:42,975
刷油（为了）分层

47
00:03:58,850 --> 00:04:02,218
小姐姐 我问一下 这一个饼皮大约多重

48
00:04:06,750 --> 00:04:09,775
这是多少 得120g

49
00:04:10,650 --> 00:04:13,575
2两多点

50
00:04:13,750 --> 00:04:16,825
两个人擀饼皮 确实要比煎和烤烧饼更快

51
00:04:17,650 --> 00:04:20,825
所以 饼皮都是整齐地摞放一起

52
00:04:21,425 --> 00:04:25,100
待会阿姨就是一个个把它们放在烤箱里

53
00:04:40,275 --> 00:04:42,250
油酥（油和面混合制成）

54
00:04:59,850 --> 00:05:02,625
烤制（进烤箱）

55
00:05:08,700 --> 00:05:10,900
有那个坏的饼吗

56
00:05:11,475 --> 00:05:14,075
刚才一个大哥来买肉夹馍

57
00:05:14,150 --> 00:05:16,600
但是他不是来买烤好的饼

58
00:05:16,825 --> 00:05:18,925
他是说 这边有没有烤的不好的饼

59
00:05:19,075 --> 00:05:21,800
就是比较便宜地能够买回去

60
00:05:22,175 --> 00:05:24,875
饼都是很好的 但是有时候火候不到位

61
00:05:25,100 --> 00:05:28,000
这样的饼吃起来没有做得好的饼口感那么好

62
00:05:33,100 --> 00:05:35,425
第二盆肉登场

63
00:05:47,100 --> 00:05:48,675
顾客：我要4个加蛋的

64
00:05:48,675 --> 00:05:49,875
吃瘦的还是稍微带点肥的

65
00:05:50,000 --> 00:05:51,000
肥瘦的吧

66
00:05:51,000 --> 00:05:51,850
肥瘦搭配

67
00:06:00,700 --> 00:06:07,000
（剁肉声）


```

**Comment by shuaisoserious** [comment]
我接了

**Comment by shuaisoserious** [comment]
认领

**Comment by shuaisoserious** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
无需翻译

简介
简介无需翻译

字幕
1
00:00:07,450 --> 00:00:08,525
肥瘦（肉）都可以吃吧
Can we eat fatty and fat less pork?
2
00:00:08,675 --> 00:00:09,875
嗯 吃
yes
3
00:00:18,000 --> 00:00:21,375
（剁肉声）
Sound of chopping pork
4
00:00:44,225 --> 00:00:45,505
起个大早来买肉夹馍
We get up very early to buy pork buns
5
00:00:45,505 --> 00:00:47,550
没想到有这么多人 比我还早
I didn’t expect there were so many people are here before me
6
00:00:47,725 --> 00:00:49,150
这边的肉夹馍卖的比较便宜
Their pork buns are cheaper
7
00:00:49,425 --> 00:00:50,475
上次我买的时候
Other restaurant’s is four or five yuan each
8
00:00:50,625 --> 00:00:52,100
别人家都是四五块钱一个
When I bought pork buns for last time
9
00:00:52,275 --> 00:00:53,950
他这边时候两块五
There is two and half yuan each
10
00:00:54,075 --> 00:00:57,050
不知道这么长时间过去 这边的价格怎么样
I don’t know how much it is now after that long time
11
00:00:57,050 --> 00:00:59,000
咱们去看看吧
Lets see
12
00:01:13,775 --> 00:01:15,675
顾客排队中
Customers are in lining
13
00:01:25,250 --> 00:01:27,325
我要3个标准（肥瘦）的肉夹馍
I want to buy 3 regular (both fatty and fatless pork) pork buns
14
00:01:27,675 --> 00:01:28,750
盐味一般
Medium salty
15
00:01:30,075 --> 00:01:31,500
不要辣椒
No spicy pepper
16
00:01:35,250 --> 00:01:37,250
看这一锅肉 真的是饿了
I am starving when I saw meat in the pot
17
00:01:45,425 --> 00:01:47,925
好香啊 还是熟悉的味道
Smells very fragment with familiar flavor 
18
00:01:48,675 --> 00:01:51,225
咱们买了3个脆皮肉夹馍 5元一个
We bought 3 crunchy pork buns, 5 yuan each
19
00:01:51,400 --> 00:01:52,975
这次呢 我要的是标准（肥瘦）的
I ordered regular (both fatty and fatless pork this time
20
00:01:53,050 --> 00:01:54,600
有点肥肉带点皮
A little fatty with pork skin
21
00:01:54,625 --> 00:01:56,750
吃起来口感没有那么干
With less dry texture
22
00:01:57,575 --> 00:02:01,826
因为猪肉涨价了嘛 肉夹馍的价格也跟着涨了
The price of pork buns increased because price of pork increased
23
00:02:01,826 --> 00:02:05,126
不过这边的生意还是很好的
Their business still very good
24
00:02:05,126 --> 00:02:07,426
以前吃的肉夹馍 一般都是腊汁肉夹馍
We used to eat 
25
00:02:07,850 --> 00:02:10,375
这次咱们买的是潼关肉夹馍

26
00:02:10,750 --> 00:02:13,200
它们最大的区别在于这个饼
The biggest differences between them are the bun
27
00:02:14,275 --> 00:02:15,875
我先咽一下口水
Let me swallow my saliva first
28
00:02:16,025 --> 00:02:18,550
烧饼外面是非常酥脆的
Shaobing are very crispy on the outside
29
00:02:18,750 --> 00:02:21,650
呈现这种螺旋花纹的状态
Shows the state of spiral pattern
30
00:02:23,325 --> 00:02:27,175
刚出炉的肉夹馍 真是迫不及待地想咬一口
I can't wait to bite the freshly baked pork buns 
31
00:02:38,200 --> 00:02:41,950
太酥脆了 所以很容易掉渣
Its easy to fall off dross of bun
32
00:02:42,275 --> 00:02:44,775
饼就像千层饼 油酥饼一样
The bun is like thousand layers of buns and shortbread
33
00:02:45,100 --> 00:02:46,625
层呢 就是一层层的
With multiple layers 
34
00:02:46,875 --> 00:02:51,425
这么一碰 饼皮都会掉下来 特别的酥脆
Its very crispy 
35
00:02:51,650 --> 00:02:54,925
肉夹馍 一口下去 不仅能够吃到烧饼的酥脆
U can feel crispy crunch of buns with one bite
36
00:02:55,050 --> 00:02:56,575
还有肉的咸香
And salty fragment of pork
37
00:02:56,800 --> 00:02:59,425
两种味道在唇齿之间交融 在打架
Two flavors are fighting in your lips and teeth 
38
00:02:59,875 --> 00:03:02,450
仿佛都在宣示 我最好吃
As it declare I’m the delicious 
39
00:03:02,725 --> 00:03:05,006
以前吃肉夹馍觉得肉很重要
I used to think pork is very important when I eat pork bun before
40
00:03:05,075 --> 00:03:07,250
这次发现 饼也很好吃
But now I find out the bun is delicious too
41
00:03:08,725 --> 00:03:13,350
有的时候 这个饼的酥脆甚至可以掩盖一下肉的油腻
The crispy of buns even cover up the greasiness of the meat sometimes
42
00:03:24,775 --> 00:03:27,025
顾客：我看我9点来拿馍
Customer: I will take my buns at 9am
43
00:03:27,500 --> 00:03:30,475
你9点来拿 我给你留着 馍还热乎
You can come at 9, and I will keep the buns warm for you
44
00:03:33,675 --> 00:03:35,600
你要瘦的还是肥的（肉）
Do you want fatty or fatless pork?
45
00:03:35,725 --> 00:03:38,250
有点肥也行
It’s okay to have a little fatty
46
00:03:40,500 --> 00:03:42,975
刷油（为了）分层
Brushing oil for layering
47
00:03:58,850 --> 00:04:02,218
小姐姐 我问一下 这一个饼皮大约多重
Sis how heavy for the curst?
48
00:04:06,750 --> 00:04:09,775
这是多少 得120g
About 120 grams
49
00:04:10,650 --> 00:04:13,575
2两多点
emmmmmmmmmmmmm
50
00:04:13,750 --> 00:04:16,825
两个人擀饼皮 确实要比煎和烤烧饼更快
Two people roll out the crust are faster than to fry and bake
51
00:04:17,650 --> 00:04:20,825
所以 饼皮都是整齐地摞放一起
So crusts are stacked neatly
52
00:04:21,425 --> 00:04:25,100
待会阿姨就是一个个把它们放在烤箱里
Aunt will put them into oven one by one later
53
00:04:40,275 --> 00:04:42,250
油酥（油和面混合制成）
“Yousu”(mixed with oil and wheat)
54
00:04:59,850 --> 00:05:02,625
烤制（进烤箱）
Bake(into oven)
55
00:05:08,700 --> 00:05:10,900
有那个坏的饼吗
Do you have bad baked buns
56
00:05:11,475 --> 00:05:14,075
刚才一个大哥来买肉夹馍
A guy come to buy pork buns
57
00:05:14,150 --> 00:05:16,600
但是他不是来买烤好的饼
But he is not coming for well baked buns
58
00:05:16,825 --> 00:05:18,925
他是说 这边有没有烤的不好的饼
He is asking if we have bad baked buns
59
00:05:19,075 --> 00:05:21,800
就是比较便宜地能够买回去
So that he can buy with cheaper price
60
00:05:22,175 --> 00:05:24,875
饼都是很好的 但是有时候火候不到位
Our buns are good, but sometimes not bake well
61
00:05:25,100 --> 00:05:28,000
这样的饼吃起来没有做得好的饼口感那么好
So it taste not as good as well baked buns
62
00:05:33,100 --> 00:05:35,425
第二盆肉登场
Second pot of meat coming
63
00:05:47,100 --> 00:05:48,675
顾客：我要4个加蛋的
I want four pork buns with eggs
64
00:05:48,675 --> 00:05:49,875
吃瘦的还是稍微带点肥的
Fatty or fatless pork?
65
00:05:50,000 --> 00:05:51,000
肥瘦的吧
Both of them
66
00:05:51,000 --> 00:05:51,850
肥瘦搭配
Fatty and fatless
67
00:06:00,700 --> 00:06:07,000
（剁肉声）
Sound of chopping pork
