### ISSUE TITLE
[华农兄弟] 华农兄弟修一下鱼塘顺便看一下山有什么可以吃的 - https://youtu.be/uHqT-YRS_nA

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#946]
https://youtu.be/uHqT-YRS_nA
<p>&#35270;&#39057;&#21457;&#24067;&#20110; April 22, 2020 at 09:56AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/uHqT-YRS_nA

#华农兄弟：修一下鱼塘，顺便看一下山有什么可以吃的
#Huanong Brothers: We go to fix the pond. Then we take a look and see if there are any good snacks on the hill.

0:00:00.000,0:00:04.000
# 大家好  最近老是下雨  這個池塘的水都快溢出來啦
Hi everyone! It's always raining recently. The water in the pond will be overflowing very soon.

0:00:04.640,0:00:07.500
# 我把它  那個修一下  修好一點  別讓魚給跑啦
Let me fix it, get it fixed. I'm not gonna let the fish run away.

0:00:08.760,0:00:10.780
# 在這裡  在這裡好多魚的哦
Here, here are a lot of fish, you know.

0:00:11.580,0:00:12.560
# 不知道有沒有跑掉
Let's see if they've run away.

0:00:16.760,0:00:19.040
# 你看  上次我放的那幾條紅鯉魚
Look! These are the couple of red carps that I put here last time.

0:00:19.500,0:00:20.280
# 還在那裡
They're still there.

0:00:20.980,0:00:21.760
# 兩條
Two are,

0:00:22.000,0:00:22.500
# 黑的
black.

0:00:22.600,0:00:23.380
# 兩條紅的
And two are red.

0:00:23.820,0:00:25.720
# 剛好我看一下蛇頭魚  好大的
I just saw a snakehead fish, a very big one.

0:00:26.420,0:00:27.460
# 跑哪裡去了
Where is it now?

0:00:30.260,0:00:32.760
# 我原以為它們跑了  原來沒跑  你看
I thought they had run away, but they haven't, look!

0:00:33.320,0:00:34.720
# 現在吃的好肥呀  它們
They're really fat now.

0:00:35.580,0:00:37.300
# 這個魚我們從來不用喂的
These fish don't need to be fed at all.

0:00:37.680,0:00:38.400
# 就吃
They only,

0:00:38.860,0:00:40.880
# 吃一些那些草啊  吃一些那些
they only feed on the grass, or, like,

0:00:41.280,0:00:42.660
# 小魚小蝦  就可以了
small fish, small shrimps, that's it.

0:00:44.420,0:00:45.640
# 你看  那幾條鯉魚
Look! The couple of fish over there

0:00:46.660,0:00:48.940
# 應該跑了一些  我放了不止那麼一點點的
I think some have already run away. I've put more than just a tiny little bit here.

0:00:51.060,0:00:52.240
# 我先把這個水堵一下
Let me block the flow of the water first.

0:00:53.600,0:00:55.260
# 把這個水稍微堵高一點  
I'm gonna make a higher block.

0:01:06.300,0:01:07.320
# 我把這個石頭
This rock...

0:01:07.960,0:01:09.020
# 多撈一點起來
I want more rocks.

0:01:54.880,0:01:56.080
# 修一下這個口
Let me block this exit.

0:01:56.740,0:01:57.980
# 魚就跑不出去啦
Then the fish can't run away.

0:02:23.880,0:02:24.600
# 差不多啦
Almost there

0:02:36.900,0:02:37.480
# 你看
Look!

0:02:38.040,0:02:38.940
# 現在就可以啦
It's alright now.

0:02:40.240,0:02:41.320
# 搞的太累了
It's so tiring!

0:02:42.060,0:02:43.900
# 我去山上看一下有沒有那個萢子
Let me go onto the hill and see if there are any, you know,

0:02:44.720,0:02:45.460
# 萢子吃
any berries.

0:02:50.100,0:02:51.060
# 你看這個竹子
Have a look at this bamboo!

0:02:51.680,0:02:52.940
# 一個月長那麼高啦
It has become that tall in just one month.

0:02:54.060,0:02:55.480
# 應該十多米啦
It should be more than 10 metres now.

0:02:56.380,0:02:58.200
# 再過一兩個月的話就長成那個
In one or two months, it will be,

0:02:58.200,0:02:59.500
# 正常的竹子一樣那麼大
as big as the bamboos that we usually see.

0:03:01.560,0:03:03.840
# 好啦  摘點  摘點萢子吃  好口渴
Alright! Let's pick some, pick some berries. I'm really thirsty.

0:03:09.080,0:03:11.720
# 你看  這個就是蛇莓哦
Look! This is called, snake berry.

0:03:12.400,0:03:14.260
# 像草莓一樣的  這個是不能吃的
It looks like a strawberry, but it's not edible.

0:03:15.620,0:03:16.600
# 有毒的哦  這個
It's poisonous, you know.

0:03:27.660,0:03:29.140
# 你看  這裡很多哦
Look! Here are a lot!

0:03:29.860,0:03:30.780
# 但是還沒熟
But they're not yet ripe.

0:03:31.620,0:03:33.500
# 有點酸酸的  等它熟了我再過來
They're a bit sour now. I'll come again when they become ripe.

0:03:35.940,0:03:37.060
# 你看  這裡好多
Look! Here are a lot!

0:03:37.840,0:03:39.580
# 還一是很熟  這裡也有一個
But they're still a bit green. Here's another one.

0:03:41.040,0:03:42.660
# 你看  這樣的都還不是很熟
Look! It's still a bit green,

0:03:44.280,0:03:45.120
# 有點酸
and it's a bit sour.

0:03:46.320,0:03:47.140
# 你看 這樣的
Look! Here they are.

0:03:47.600,0:03:48.560
# 再過幾天就熟了
They will become ripe in a few days.

0:03:54.860,0:03:57.300
# 萢子沒找到哦  看到這裡有點石榴花
I can't find any berries. But I see some pomegranate flowers here.

0:03:57.300,0:03:58.860
# 我搞點石榴花來吃一下  (註︰直譯會變成"get some XXX to eat"，這說法太奇怪，改一下)
These flowers can quench my thirst.

0:03:59.780,0:04:01.340
# 石榴花裡面有很多水份的
These flowers are really juicy.

0:04:02.260,0:04:02.880
# 哇  這
Wa! It's a,

0:04:03.480,0:04:05.320
# 90度的坡  怎麼上
a vertical slope. How can I get onto it?

0:04:19.940,0:04:22.220
# 你看  我就拉了 拉了在這裡吃了
Look! I just pull it, pull it down and have my feast here.

0:04:22.920,0:04:23.820
# 那不然那個
Otherwise, you know,

0:04:26.180,0:04:27.420
# 會把這個樹搞斷的
I would break the branch.

0:04:27.760,0:04:29.000
# 搞斷了明年就沒得吃了
If I broke it, it wouldn't be here anymore next year.

0:04:34.920,0:04:35.660
# 可以哦
It's not bad.

0:04:37.280,0:04:38.060
# 酸酸甜甜
Sweet and sour

0:04:47.500,0:04:49.700
# 吃之前要看一下啊  看有沒有蟲
You need to take a look, and see if there are any bugs, before putting it into your mouth.

0:04:53.320,0:04:55.200
# 哇  口渴的時候也可以解一下渴 這個
Wa! It can really quench thirst, you know.

0:04:57.880,0:04:59.200
# 嗯  這個不好  (註︰沒有原字幕)
Um! This one is no good.

0:04:59.560,0:05:00.820
# 快謝了的就不要了
Don't take it if it's about to wither.

0:05:03.200,0:05:03.840
# 拉下來
Pull it down.

0:05:05.200,0:05:06.920
# 你看這個象草  都長出來啦
Look! The elephant grass is already growing out.

0:05:08.480,0:05:09.340
# 一片綠綠的
It's green everywhere.

0:05:09.800,0:05:10.300
# 很靚哦
So beautiful!

0:05:11.960,0:05:14.700
# 去年 去年霜的死的時候  這杆都打沒啦
When they're killed, killed by the frost last year, nothing was left, not even the stems.

0:05:15.160,0:05:16.060
# 現在又長出來啦
And they're growing out now.

0:05:16.320,0:05:17.580
# 第一年種下去的  你看
It's my first time planting them, look!

0:05:17.740,0:05:18.780
# 一輩子都不用種了
And it's also my last time.

0:05:22.980,0:05:24.180
# 誒呀  好多竹子
Aya! A lot of bamboos

0:05:25.040,0:05:26.700
# 這是兄弟家種的香菇
These are my buddy's shiitake mushrooms.

0:05:28.920,0:05:30.220
# 一個都沒有
Not even one is left.

0:05:30.500,0:05:31.440
# 一個都沒看到
I can't see any, not even one.

0:05:32.940,0:05:34.620
# 太可憐了  一個都沒有
Nothing is left, what a pity!

0:05:35.820,0:05:37.000
# 哎呀  有一個
Aya! Here's one!

0:05:39.380,0:05:40.240
# 沒啦  就一個
Just one, no more.

0:05:42.280,0:05:43.360
# 兄弟在不在
Is my buddy around?

0:05:44.740,0:05:46.440
# 拿回去打湯  就一個
Just one. I'll use it to make soup.

0:05:49.360,0:05:51.940
# 啊  好香啊  你看這香菇  很漂亮吧
Ah! It smells so good. Have a look at this mushroom. It's really pretty, isn't it?

0:05:55.500,0:05:58.280
# 好啦  今天  今天的視頻就到這裡啦 (註︰要對應一下第一次的「今天」發音不準確)
Alright! Tha, the video ends here.

0:05:58.680,0:06:00.580
# 兩手空空  甚麼都沒有
We're leaving, empty-handed, with nothing at all.

0:06:20.340,0:06:21.740
# 你看  這是我家的雞
Look! These are my chickens.

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/uHqT-YRS_nA

#华农兄弟：修一下鱼塘，顺便看一下山有什么可以吃的
#Huanong Brothers: We go to fix the pond. Then we take a look and see if there are any good snacks on the hill.

0:00:00.000,0:00:04.000
# 大家好  最近老是下雨  這個池塘的水都快溢出來啦
Hi everyone! It's always raining recently. The water in the pond will be overflowing very soon.

0:00:04.640,0:00:07.500
# 我把它  那個修一下  修好一點  別讓魚給跑啦
Let me fix it, get it fixed. I'm not gonna let the fish run away.

0:00:08.760,0:00:10.780
# 在這裡  在這裡好多魚的哦
Here, here are a lot of fish, you know.

0:00:11.580,0:00:12.560
# 不知道有沒有跑掉
Let's see if they've run away.

0:00:16.760,0:00:19.040
# 你看  上次我放的那幾條紅鯉魚
Look! These are the couple of red carps that I put here last time.

0:00:19.500,0:00:20.280
# 還在那裡
They're still there.

0:00:20.980,0:00:21.760
# 兩條
Two are,

0:00:22.000,0:00:22.500
# 黑的
black.

0:00:22.600,0:00:23.380
# 兩條紅的
And two are red.

0:00:23.820,0:00:25.720
# 剛好我看一下蛇頭魚  好大的
I just saw a snakehead fish, a very big one.

0:00:26.420,0:00:27.460
# 跑哪裡去了
Where is it now?

0:00:30.260,0:00:32.760
# 我原以為它們跑了  原來沒跑  你看
I thought they had run away, but they haven't, look!

0:00:33.320,0:00:34.720
# 現在吃的好肥呀  它們
They're really fat now.

0:00:35.580,0:00:37.300
# 這個魚我們從來不用喂的
These fish don't need to be fed at all.

0:00:37.680,0:00:38.400
# 就吃
They only,

0:00:38.860,0:00:40.880
# 吃一些那些草啊  吃一些那些
they only feed on the grass, or, like,

0:00:41.280,0:00:42.660
# 小魚小蝦  就可以了
small fish, small shrimps, that's it.

0:00:44.420,0:00:45.640
# 你看  那幾條鯉魚
Look! The couple of fish over there

0:00:46.660,0:00:48.940
# 應該跑了一些  我放了不止那麼一點點的
I think some have already run away. I've put more than just a tiny little bit here.

0:00:51.060,0:00:52.240
# 我先把這個水堵一下
Let me block the flow of the water first.

0:00:53.600,0:00:55.260
# 把這個水稍微堵高一點  
I'm gonna make a higher block.

0:01:06.300,0:01:07.320
# 我把這個石頭
This rock...

0:01:07.960,0:01:09.020
# 多撈一點起來
I want more rocks.

0:01:54.880,0:01:56.080
# 修一下這個口
Let me block this exit.

0:01:56.740,0:01:57.980
# 魚就跑不出去啦
Then the fish can't run away.

0:02:23.880,0:02:24.600
# 差不多啦
Almost there

0:02:36.900,0:02:37.480
# 你看
Look!

0:02:38.040,0:02:38.940
# 現在就可以啦
It's alright now.

0:02:40.240,0:02:41.320
# 搞的太累了
It's so tiring!

0:02:42.060,0:02:43.900
# 我去山上看一下有沒有那個萢子
Let me go onto the hill and see if there are any, you know,

0:02:44.720,0:02:45.460
# 萢子吃
any berries.

0:02:50.100,0:02:51.060
# 你看這個竹子
Have a look at this bamboo!

0:02:51.680,0:02:52.940
# 一個月長那麼高啦
It has become that tall in just one month.

0:02:54.060,0:02:55.480
# 應該十多米啦
It should be more than 10 metres now.

0:02:56.380,0:02:58.200
# 再過一兩個月的話就長成那個
In one or two months, it will be,

0:02:58.200,0:02:59.500
# 正常的竹子一樣那麼大
as big as the bamboos that we usually see.

0:03:01.560,0:03:03.840
# 好啦  摘點  摘點萢子吃  好口渴
Alright! Let's pick some, pick some berries. I'm really thirsty.

0:03:09.080,0:03:11.720
# 你看  這個就是蛇莓哦
Look! This is called, snake berry.

0:03:12.400,0:03:14.260
# 像草莓一樣的  這個是不能吃的
It looks like a strawberry, but it's not edible.

0:03:15.620,0:03:16.600
# 有毒的哦  這個
It's poisonous, you know.

0:03:27.660,0:03:29.140
# 你看  這裡很多哦
Look! Here are a lot!

0:03:29.860,0:03:30.780
# 但是還沒熟
But they're not yet ripe.

0:03:31.620,0:03:33.500
# 有點酸酸的  等它熟了我再過來
They're a bit sour now. I'll come again when they become ripe.

0:03:35.940,0:03:37.060
# 你看  這裡好多
Look! Here are a lot!

0:03:37.840,0:03:39.580
# 還一是很熟  這裡也有一個
But they're still a bit green. Here's another one.

0:03:41.040,0:03:42.660
# 你看  這樣的都還不是很熟
Look! It's still a bit green,

0:03:44.280,0:03:45.120
# 有點酸
and it's a bit sour.

0:03:46.320,0:03:47.140
# 你看 這樣的
Look! Here they are.

0:03:47.600,0:03:48.560
# 再過幾天就熟了
They will become ripe in a few days.

0:03:54.860,0:03:57.300
# 萢子沒找到哦  看到這裡有點石榴花
I can't find any berries. But I see some pomegranate flowers here.

0:03:57.300,0:03:58.860
# 我搞點石榴花來吃一下  (註︰直譯會變成"get some XXX to eat"，這說法太奇怪，改一下)
These flowers can quench my thirst.

0:03:59.780,0:04:01.340
# 石榴花裡面有很多水份的
These flowers are really juicy.

0:04:02.260,0:04:02.880
# 哇  這
Wa! It's a,

0:04:03.480,0:04:05.320
# 90度的坡  怎麼上
a vertical slope. How can I get onto it?

0:04:19.940,0:04:22.220
# 你看  我就拉了 拉了在這裡吃了
Look! I just pull it, pull it down and have my feast here.

0:04:22.920,0:04:23.820
# 那不然那個
Otherwise, you know,

0:04:26.180,0:04:27.420
# 會把這個樹搞斷的
I would break the branch.

0:04:27.760,0:04:29.000
# 搞斷了明年就沒得吃了
If I broke it, it wouldn't be here anymore next year.

0:04:34.920,0:04:35.660
# 可以哦
It's not bad.

0:04:37.280,0:04:38.060
# 酸酸甜甜
Sweet and sour

0:04:47.500,0:04:49.700
# 吃之前要看一下啊  看有沒有蟲
You need to take a look, and see if there are any bugs, before putting it into your mouth.

0:04:53.320,0:04:55.200
# 哇  口渴的時候也可以解一下渴 這個
Wa! It can really quench thirst, you know.

0:04:57.880,0:04:59.200
# 嗯  這個不好  (註︰沒有原字幕)
Um! This one is no good.

0:04:59.560,0:05:00.820
# 快謝了的就不要了
Don't take it if it's about to wither.

0:05:03.200,0:05:03.840
# 拉下來
Pull it down.

0:05:05.200,0:05:06.920
# 你看這個象草  都長出來啦
Look! The elephant grass is already growing out.

0:05:08.480,0:05:09.340
# 一片綠綠的
It's green everywhere.

0:05:09.800,0:05:10.300
# 很靚哦
So beautiful!

0:05:11.960,0:05:14.700
# 去年 去年霜的死的時候  這杆都打沒啦
When they're killed, killed by the frost last year, nothing was left, not even the stems.

0:05:15.160,0:05:16.060
# 現在又長出來啦
And they're growing out now.

0:05:16.320,0:05:17.580
# 第一年種下去的  你看
It's my first time planting them, look!

0:05:17.740,0:05:18.780
# 一輩子都不用種了
And it's also my last time.

0:05:22.980,0:05:24.180
# 誒呀  好多竹子
Aya! A lot of bamboos

0:05:25.040,0:05:26.700
# 這是兄弟家種的香菇
These are my buddy's shiitake mushrooms.

0:05:28.920,0:05:30.220
# 一個都沒有
Not even one is left.

0:05:30.500,0:05:31.440
# 一個都沒看到
I can't see any, not even one.

0:05:32.940,0:05:34.620
# 太可憐了  一個都沒有
Nothing is left, what a pity!

0:05:35.820,0:05:37.000
# 哎呀  有一個
Aya! Here's one!

0:05:39.380,0:05:40.240
# 沒啦  就一個
Just one, no more.

0:05:42.280,0:05:43.360
# 兄弟在不在
Is my buddy around?

0:05:44.740,0:05:46.440
# 拿回去打湯  就一個
Just one. I'll use it to make soup.

0:05:49.360,0:05:51.940
# 啊  好香啊  你看這香菇  很漂亮吧
Ah! It smells so good. Have a look at this mushroom. It's really pretty, isn't it?

0:05:55.500,0:05:58.280
# 好啦  今天  今天的視頻就到這裡啦 (註︰要對應一下第一次的「今天」發音不準確)
Alright! Tha, the video ends here.

0:05:58.680,0:06:00.580
# 兩手空空  甚麼都沒有
We're leaving, empty-handed, with nothing at all.

0:06:20.340,0:06:21.740
# 你看  這是我家的雞
Look! These are my chickens.
