### ISSUE TITLE
[老饭骨] 炸油条 - https://youtu.be/fUZ3AynK0Wg

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#948]
**视频链接**：https://youtu.be/fUZ3AynK0Wg

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•炸油条】家庭版炸油条，蓬松酥脆，奶香味儿十足！健康无矾，超详细配方，一次就能成功！Deep-fried Stick|老饭骨

简介
小友们好，今天老饭骨给大家带来一道我们中国传统面食——炸油条。
炸油条是大家早餐经常吃的，学会炸油条在家里做，没有白矾，会更加健康！
加入牛奶就是奶香味的秘诀！再用茉莉花的水来和面，保留香味儿！
老饭骨们不仅想把手艺教给小友们传承下去，还希望小友们能够学会创新的思路，一通百通，加入自己的想法，把我们中华美食发扬光大！
得嘞，上菜咯，小友们快点击视频学起来吧！

字幕（需自行制作时间轴）
今天咱们玩儿一邪乎的
玩儿面了  不玩儿菜了
做一个家庭版的油条
做上早餐了  做上早餐  正餐也可以吃
这个面大约有一斤重  俩鸡蛋
这是个健康油条
您做什么都是健康的  它里边不搁矾
您真是站着说话不腰疼
现在腿好了是不是啊
腿好了  你看见没有
酵母五克
泡打粉  也五克
小苏打  五克
这小苏打一般就是起外皮酥脆
泡打粉就是起膨胀
酵母是发酵  谁家做油条搁牛奶啊
这成本多高啊
搁牛奶搁水是一样的
奶香味  现在放奶  放多少奶呢
放半盒  一百二十五克
我先给它搅一搅  搅成啰嗦状
是不是还可以搁点奶啊
也可以搁奶也可以搁点水
一百五十毫升三两
和这面就是基本上烙饼面  软和
好啦
搅匀  也就是说水分比较均匀了
我们再开始往一块揉
二伯再给点奶
盐  五克盐
一个盐是起味道
另外一个也起一个拉力（作用）
盐有劲儿  有劲儿油条能拉劲儿
吃起来有弹性
选面基本上选低筋粉
不要用高筋粉
大爷还真行  小活干着小腿儿也没事儿了
网友们咱们祝贺大爷腿好啦
叫他多做菜啊  不能放过他
这时候给它搁点油
你知道还得搁五克黄油
我就不搁  我就这么任性
大爷您千万别上套儿
今天咱们做的就是普通家庭油条
咱先不来这个
这个时候多揣一揣
把它和匀了  和滋润了
你知道我们做拿什么水和么
茉莉花的水和这个面
茉莉花的味儿很浓的
咱们给网友点思路
就是给思路  就是一通百通么
最后再补五克油  他这说的什么意思
老饭骨不但传承  还得引领他们创新
没错
大爷在这儿做一个最基本的东西
然后剩下的就让网友自己延续下来了
今天的面真有劲儿
太有劲儿还不好
但愿成功  一次性成功  没问题
封上油  醒俩小时
嗯  天儿凉
网友们看着啊  大爷这儿出手了
这油条的面已经发好了
看看  行啊
大爷做的是家常版的炸油条
大约三公分  大不大
别着急  不大
用不用给您拿个筷子啊   对是得拿个筷子
这油条大  怎么办啊  改成俩
聪明着呢  真聪明  一捏
这案板太小了
没关系您在家就做五根油条
三米的案板你也不那什么啊
咱们在家就在家么
人家面板上全是油  您就搁面吧
这（案板上）不搁油
为什么咱这油条健康啊  没有那么多油
我不瞒你说这油条
到今天我才炸了第三回
我也是学做  但是我今天呢
要把我学做的体会
跟我们网友一块分享一下
你看我弄这个不像人家特专业的面点师
你这横着看像小船
油条剂儿做好了  我们给它拉一拉
再抻一抻  其实咱们做面点不专业
做面点专业的都是大小统一  长短一致
我这个稍微的差点儿
我这会让给弄得好看点
摆整齐了不就行了
长了切切  这还不好说
大爷很厉害啊  厉害么  厉害
第一个敢伸手  不是专业的敢亮剑
敢跟大家做分享
可以下锅试一个啦  七成
你看  对啊得杵上
怎么样这油条厉害了吧
行不行  太行了
嘿还敢下两根  三根都没事
您下我扒拉
行了  好  这油条真棒
大爷说了自己才做了三回  我不信
这人要聪明干什么都行
我这回更聪明了  直接给它齐剂儿
这叫地道  这叫正规了
终于大爷走上正规的路了
俩一夹  二伯出手了啊  筷子一弄
一扽就行了其实  关东糖似的
好  这就行了
好嘞  灭火
我们都吃这么多了  从炸到现在
我们都没停下嘴
实际上自我评价一下
还有点瑕疵
一个是我抻的手法表面还不太光滑
不太专业  还不太专业
但是我觉得基本上还算可以吧
下次啊  再炸的时候作为课外题
炸的要比这回还要精彩
下次不能炸（油条）了
下次炸油饼了
我是大爷
```

**Comment by siyusun6918** [comment]
认领

**Comment by siyusun6918** [comment]
0:00:00.000,0:00:01.300
今天咱们玩儿一邪乎的
We are going to play with something interesting

0:00:01.360,0:00:03.020
玩儿面了  不玩儿菜了
Play with some dough, not with food 

0:00:03.020,0:00:04.940
做一个家庭版的油条
Make a homemade version of Youtiao (deep-fried dough sticks)

0:00:05.160,0:00:07.300
做上早餐了  做上早餐  正餐也可以吃
It’s breakfast, but also can be eaten as lunch 

0:00:08.180,0:00:10.900
这个面大约有一斤重  俩鸡蛋
This is about one catty of flour, add two eggs

0:00:10.900,0:00:12.440
这是个健康油条
This is a healthy Youtiao 

0:00:13.020,0:00:15.780
您做什么都是健康的  它里边不搁矾
Everything you cook is healthy. This version doesn’t add Alum. 

0:00:15.780,0:00:17.460
您真是站着说话不腰疼
It’s easier to say than done

0:00:17.460,0:00:18.520
现在腿好了是不是啊
Your legs are better now, right?

0:00:18.520,0:00:19.880
腿好了  你看见没有
Much better, you see

0:00:19.880,0:00:21.580
酵母五克
Yeast 5 grams 

0:00:21.740,0:00:23.740
泡打粉  也五克
Baking powder also 5 grams 

0:00:23.740,0:00:25.400
小苏打  五克
Baking soda 5 grams 

0:00:25.880,0:00:28.180
这小苏打一般就是起外皮酥脆
This baking soda is to make the surface more crispy 

0:00:28.180,0:00:29.800
泡打粉就是起膨胀
Baking powder is to puff the dough

0:00:30.260,0:00:32.960
酵母是发酵  谁家做油条搁牛奶啊
Yeast is for fermentation. Who else uses milk to make Youtiao?

0:00:32.960,0:00:34.240
这成本多高啊
The cost is expensive 

0:00:34.240,0:00:36.060
搁牛奶搁水是一样的
Either add milk or water is the same 

0:00:36.640,0:00:39.120
奶香味  现在放奶  放多少奶呢
Milky flavor. Now add the milk. How much?

0:00:39.960,0:00:42.180
放半盒  一百二十五克
Half the box, 125 grams

0:00:43.160,0:00:46.380
我先给它搅一搅  搅成啰嗦状
I’m mixing it first, into small strips 

0:00:46.380,0:00:47.980
是不是还可以搁点奶啊
Can we add some more milk?

0:00:47.980,0:00:49.680
也可以搁奶也可以搁点水
You can add milk or water

0:00:50.100,0:00:52.100
一百五十毫升三两
150 milliliter

0:00:53.380,0:00:57.360
和这面就是基本上烙饼面  软和
This kind of dough is basically the same as Flapjack, it’s soft

0:00:57.360,0:00:57.940
好啦
Done

0:00:58.080,0:01:01.140
搅匀  也就是说水分比较均匀了
Mix well, which means the water content has been evenly distributed 

0:01:01.300,0:01:03.600
我们再开始往一块揉
Then we knead together 

0:01:04.520,0:01:06.520
二伯再给点奶
Er Bai, add some more milk

0:01:06.520,0:01:08.100
盐  五克盐
Salt, 5 grams of salt

0:01:08.100,0:01:09.320
一个盐是起味道
Firstly, salt is to add flavor

0:01:09.320,0:01:10.680
另外一个也起一个拉力（作用）
It also functions as a traction

0:01:11.100,0:01:13.660
盐有劲儿  有劲儿油条能拉劲儿
Salt has stretch, it makes the Youtiao Dough stretchy

0:01:14.480,0:01:17.120
吃起来有弹性
Tastes chewy

0:01:17.640,0:01:19.640
选面基本上选低筋粉
When you choose the flour, go for the low-gluten one

0:01:19.640,0:01:21.340
不要用高筋粉
Don’t use high-gluten flour

0:01:22.840,0:01:25.400
大爷还真行  小活干着小腿儿也没事儿了
Da Ye is really something, doing the work and legs are better 

0:01:25.700,0:01:27.700
网友们咱们祝贺大爷腿好啦
Friends, let’s congrats Da Ye’s legs have recovered  

0:01:27.880,0:01:29.880
叫他多做菜啊  不能放过他
Tell him to cook more, don’t be easy on him 

0:01:30.060,0:01:32.060
这时候给它搁点油
Now it’s time to add some oil

0:01:32.060,0:01:33.820
你知道还得搁五克黄油
You know you need to add 5 grams of butter 

0:01:33.820,0:01:35.740
我就不搁  我就这么任性
I’m not going to, I do what I want 

0:01:35.740,0:01:36.880
大爷您千万别上套儿
Da Ye, don’t fall into the trap

0:01:36.880,0:01:38.760
今天咱们做的就是普通家庭油条
What we are making here is the homemade version of Youtiao 

0:01:38.760,0:01:40.380
咱先不来这个
We don’t make it too complicated 

0:01:40.380,0:01:41.880
这个时候多揣一揣
Knead the dough a few more times 

0:01:42.320,0:01:44.320
把它和匀了  和滋润了
To make the dough even and moist

0:01:45.260,0:01:47.260
你知道我们做拿什么水和么
Do you know what water we used to make the dough?

0:01:47.280,0:01:49.280
茉莉花的水和这个面
We used the water of Jasmine flower to make the dough

0:01:49.280,0:01:50.940
茉莉花的味儿很浓的
Jasmine flower has a strong flavor 

0:01:50.940,0:01:52.120
咱们给网友点思路
We provide ideas for you 

0:01:52.240,0:01:54.240
就是给思路  就是一通百通么
Provide ideas, it’s master the one to master all

0:01:54.560,0:01:56.560
最后再补五克油  他这说的什么意思
Lastly, add another 5 grams of oil. What does he mean by that?

0:01:56.740,0:01:58.740
老饭骨不但传承  还得引领他们创新
What we are doing here is not only to inherit but also to guide you to innovate. 

0:01:58.740,0:01:59.340
没错
Yes

0:01:59.620,0:02:02.020
大爷在这儿做一个最基本的东西
Da Ye only makes something basic here

0:02:02.460,0:02:05.460
然后剩下的就让网友自己延续下来了
Then the rest will be inherited by the audience 

0:02:05.980,0:02:07.980
今天的面真有劲儿
The dough today is stretchy 

0:02:07.980,0:02:10.260
太有劲儿还不好
Too stretchy is not a good thing

0:02:11.380,0:02:13.380
但愿成功  一次性成功  没问题
I hope it works. Success with one try, it will work. 

0:02:14.120,0:02:16.480
封上油  醒俩小时
Cover the dough with oil, let it rest for two hours

0:02:16.640,0:02:18.640
嗯  天儿凉
Eh, the weather is cold 

0:02:19.360,0:02:22.220
网友们看着啊  大爷这儿出手了
Watch closely, Da Ye is going to start 

0:02:22.660,0:02:24.720
这油条的面已经发好了
The dough for Youtiao is terminated well

0:02:24.900,0:02:26.900
看看  行啊
Check it out.  It’s good. 

0:02:27.300,0:02:29.300
大爷做的是家常版的炸油条
Da Ye is making the home-made version of fried Youtiao 

0:02:30.500,0:02:33.300
大约三公分  大不大
About 3 centimeters. Is it too big?

0:02:33.540,0:02:35.540
别着急  不大
Don’t worry, it’s not too big

0:02:35.980,0:02:38.540
用不用给您拿个筷子啊   对是得拿个筷子
Do you need chopsticks? Yes, I need chopsticks. 

0:02:39.320,0:02:42.820
这油条大  怎么办啊  改成俩
This Youtiao is too big. What should we do? Cut it in half.

0:02:43.660,0:02:46.860
聪明着呢  真聪明  一捏
Brilliant. Clever. Pinch the end together

0:02:48.060,0:02:50.060
这案板太小了
This cutting board is too small

0:02:50.640,0:02:52.640
没关系您在家就做五根油条
It’s ok. You only make five Youtiao at home

0:02:53.020,0:02:55.220
三米的案板你也不那什么啊
You don’t need 3 meters of the cutting board

0:02:55.540,0:02:57.800
咱们在家就在家么
We are at home, so use what you have 

0:02:58.720,0:03:01.120
人家面板上全是油  您就搁面吧
Others pull oil on their board, you can use flour 

0:03:01.120,0:03:02.580
这（案板上）不搁油
Don’t put oil on the board 

0:03:03.180,0:03:05.720
为什么咱这油条健康啊  没有那么多油
Why our version of Youtiao is healthier? It contains less oil

0:03:06.300,0:03:08.300
我不瞒你说这油条
As a matter of fact,

0:03:08.640,0:03:10.640
到今天我才炸了第三回
Today is my third time frying the Youtiao 

0:03:11.320,0:03:13.880
我也是学做  但是我今天呢
I learned it. But today, 

0:03:14.340,0:03:16.740
要把我学做的体会
I am sharing my experience of learning

0:03:17.220,0:03:19.520
跟我们网友一块分享一下
with our audience friends 

0:03:19.980,0:03:22.700
你看我弄这个不像人家特专业的面点师
You see, the Youtiao I made is not like what professional pastry chef does

0:03:22.700,0:03:24.880
你这横着看像小船
Yours looks like a boat sideways

0:03:25.580,0:03:27.580
油条剂儿做好了  我们给它拉一拉
Youtiao dough is done. Let’s pull it a little

0:03:27.580,0:03:31.300
再抻一抻  其实咱们做面点不专业
Pull it a little to make it longer. Actually, we are not professional at making pastry 

0:03:31.680,0:03:34.780
做面点专业的都是大小统一  长短一致
The professionals make the dough the same size and same length

0:03:34.980,0:03:36.980
我这个稍微的差点儿
Mine is quite not there 

0:03:37.300,0:03:39.300
我这会让给弄得好看点
I’m going to make them look prettier 

0:03:39.300,0:03:41.000
摆整齐了不就行了
It’s fine as long as you place them well

0:03:41.560,0:03:44.960
长了切切  这还不好说
If it’s too long, just cut it

0:03:45.600,0:03:48.600
大爷很厉害啊  厉害么  厉害
Da Ye is amazing.   Really?   Yes

0:03:49.380,0:03:51.960
第一个敢伸手  不是专业的敢亮剑
To be the first one to try. Not professional, but has the courage to show us 

0:03:52.920,0:03:54.920
敢跟大家做分享
has the courage to share with the audience 

0:03:54.920,0:03:56.940
可以下锅试一个啦  七成
It’s time to try to fry one.  (oil is) About 70% hot

0:03:58.180,0:04:01.120
你看  对啊得杵上
You see.  Yes, you need to stir it a little 

0:04:02.340,0:04:04.340
怎么样这油条厉害了吧
How about this Youtiao, isn’t it great?

0:04:04.600,0:04:06.600
行不行  太行了
Yes, it’s so good. 

0:04:07.660,0:04:10.440
嘿还敢下两根  三根都没事
You dare to fry two at a time!  I can do three at a time. 

0:04:10.600,0:04:12.600
您下我扒拉
You put down the dough, I stir it 

0:04:13.320,0:04:15.660
行了  好  这油条真棒
It’s done. Nice. Youtiao is so good. 

0:04:16.260,0:04:18.260
大爷说了自己才做了三回  我不信
Da Ye said he only did three times, I don’t believe him

0:04:18.440,0:04:20.820
这人要聪明干什么都行
If you are clever, you can do anything well

0:04:21.480,0:04:24.340
我这回更聪明了  直接给它齐剂儿
I’m smarter this time. I’m making the dough into the same length first 

0:04:25.820,0:04:28.660
这叫地道  这叫正规了
This is authentic, this is professional 

0:04:28.980,0:04:31.340
终于大爷走上正规的路了
Finally, Da Ye is one the track of professions

0:04:32.920,0:04:35.580
俩一夹  二伯出手了啊  筷子一弄
Stack together. It’s Er Bai’s turn, use the chopstick to press in the middle 

0:04:36.220,0:04:38.220
一扽就行了其实  关东糖似的
Just pull it a little. It’s like GuanDongTang (a traditional candy from the north)

0:04:38.220,0:04:40.020
好  这就行了
It’s done.

0:04:40.320,0:04:42.320
好嘞  灭火
Ok, turn off the fire

0:04:42.700,0:04:46.200
我们都吃这么多了  从炸到现在
We have eaten a lot. 

0:04:46.440,0:04:48.440
我们都没停下嘴
We haven’t stop eating since started frying 

0:04:48.440,0:04:49.700
实际上自我评价一下
Actually, self-evaluating 

0:04:49.700,0:04:50.960
还有点瑕疵
It’s not perfect 

0:04:51.500,0:04:53.500
一个是我抻的手法表面还不太光滑
One is because the way I pull the dough is not professional, the surface is not smooth 

0:04:53.500,0:04:54.940
不太专业  还不太专业
Not professional yet 

0:04:55.500,0:04:57.500
但是我觉得基本上还算可以吧
But I think it’s basically ok 

0:04:58.420,0:05:00.880
下次啊  再炸的时候作为课外题
Next time, when we are frying Youtiao outside of the camera

0:05:00.940,0:05:02.940
炸的要比这回还要精彩
It will be better than this time 

0:05:02.940,0:05:04.100
下次不能炸（油条）了
We shouldn’t fry Youtiao next time

0:05:04.100,0:05:05.520
下次炸油饼了
We should try to fry Youbin (another type of deep-fried dough)

0:05:13.360,0:05:15.360
我是大爷
I am Da Ye

0:05:15.360,0:05:16.480
我是二伯
I am Er Bai

0:05:16.480,0:05:17.200
我是三叔
I am San Shu

0:05:17.400,0:05:19.400
我们是老饭骨
We are Lao Fan Gu

0:05:19.400,0:05:20.940
欢迎大家订阅
Please subscribe  

0:05:20.940,0:05:22.800
我们老饭骨Youtube频道
to our Youtube Channel

0:05:22.800,0:05:24.180
我们老饭骨组合
We are here 

0:05:24.180,0:05:25.600
就是教大家做菜
to teach you how to cook

0:05:25.700,0:05:27.700
传授一些精湛的小厨艺
And to share with you some cooking tips 

0:05:27.700,0:05:28.960
希望大家喜欢
Hope you like them 

0:05:29.740,0:05:31.740
希望全球的美食爱好者喜欢我们
We hope that food lovers around the world like us 

0:05:31.740,0:05:33.580
订阅我们的频道
Subsribe to our channel 

0:05:33.580,0:05:35.040
点亮我们的小铃铛
Click the notification bell 

0:05:35.600,0:05:37.600
同时在这里我们祝全球的华人
Here, we wish everyone 

0:05:38.280,0:05:40.280
万事如意 恭喜发财
A lot of happiness and fortune in the future
