### ISSUE TITLE
【美食作家王刚】干煸四季豆 - https://youtu.be/NarnE7DQtuc

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#949]
**视频链接**：https://youtu.be/NarnE7DQtuc

视频时长6:16，预计发布时间为北京时间4月25日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“干煸四季豆”的真家常做法，不用宽油也能真香，下饭神器！

简介
朋友们大家好，今天和大家分享下饭神器“干煸四季豆”，这是一道受到很多朋友喜欢的菜，只不过阻止大家在家制作的原因是“宽油”，那我今天就来教教大家不用宽油做出完美的干煸四季豆。其实最正宗的“干煸”是今天教给大家的这种方法，之所以大多数后厨会选择用宽油来炸四季豆是为了更短的出菜时间，如果是炸基本上1分半就可以保证四季豆熟透，但干煸需要6分钟，无形中给后厨增加了很多时间成本。如果大家有兴趣想学宽油版的干煸四季豆可以点击链接：https://www.youtube.com/watch?v=QAmnxADJL54

字幕
0:00:00.279,0:00:01.075
哈喽 大家好

0:00:01.163,0:00:03.460
最近我伯爷说这个灯笼椒

0:00:03.460,0:00:05.979
他以前买的放的时间够长了

0:00:05.994,0:00:07.054
再不吃要坏了

0:00:07.275,0:00:10.044
然后为了想这个灯笼椒怎么吃

0:00:10.294,0:00:12.312
我让我伯爷去买了点四季豆回来

0:00:12.901,0:00:14.933
然后今天正好跟大家分享一下

0:00:15.007,0:00:17.201
我们家庭小灶做干煸四季豆

0:00:17.540,0:00:19.859
不用宽油炸怎么把它做得

0:00:19.926,0:00:21.016
也能做的很好吃吧

0:00:21.914,0:00:23.048
我先把海椒剪了

0:00:23.210,0:00:24.521
放了好久了

0:00:24.771,0:00:26.126
硬是再放（久点）要不得了

0:00:27.893,0:00:29.602
再不吃都发霉了噶

0:00:29.793,0:00:30.309
就是

0:00:30.883,0:00:34.108
我们一般这个灯笼椒很少用来炒菜

0:00:34.948,0:00:37.083
灯笼椒的话它主要是出香味

0:00:37.614,0:00:40.353
它是不辣的也出不了什么颜色

0:00:41.222,0:00:42.488
待会我们再加点这个

0:00:43.181,0:00:46.774
再加一点我们自己这个小米辣

0:00:47.290,0:00:48.085
这个就辣安

0:00:48.954,0:00:50.058
这个出辣味的

0:00:50.324,0:00:52.017
子弹头的话就出颜色

0:00:52.754,0:00:54.639
这个四季豆炒出来香哦

0:00:55.125,0:00:57.702
香   油都没得等哈儿你炒来看香不香嘛

0:00:57.923,0:00:58.836
你又不放油

0:00:59.248,0:01:00.338
你放心四伯爷

0:01:00.368,0:01:01.617
我不是说不放油

0:01:01.617,0:01:02.805
是不拿油来炸

0:01:02.867,0:01:04.641
哦喔 那还差不多

0:01:04.798,0:01:06.669
我剪这个 四伯爷你掐四季豆

0:01:07.097,0:01:08.776
这个咋子嘛 撕过嘎

0:01:08.872,0:01:10.725
把老筋撕了就是

0:01:11.984,0:01:14.746
大四季豆的那个筋就多了

0:01:14.877,0:01:15.375
老噶

0:01:15.769,0:01:16.363
嗯

0:01:20.531,0:01:23.162
还是坏的比较多哦 四伯爷

0:01:23.844,0:01:25.592
坏的就丢了噻 不要噻

0:01:26.155,0:01:27.344
我都剪了好几个坏的了

0:01:27.750,0:01:29.244
再不吃发霉了

0:01:33.617,0:01:35.278
好了 这个干辣椒我剪好了

0:01:35.927,0:01:37.134
我把这个捞一下

0:01:37.134,0:01:38.515
这个（辣椒）籽太多了

0:01:39.270,0:01:41.429
我们把这个籽去掉一些

0:01:42.720,0:01:45.290
这个干煸四季豆的话就用这个五花肉

0:01:46.747,0:01:49.739
给它切成小颗粒切碎

0:01:51.398,0:01:52.989
我们做干煸四季豆

0:01:52.989,0:01:56.179
放肥一点的这个猪肉的话

0:01:56.179,0:02:00.399
它出来的猪油可以把味道吸在这个四季豆上面

0:02:00.399,0:02:02.611
所以就会有味道有盐味

0:02:05.060,0:02:06.521
这样子整起肯定好吃

0:02:06.914,0:02:08.540
把这个肉宰哈宰哈就可以了

0:02:12.477,0:02:13.484
这个肉准备好了 

0:02:13.484,0:02:15.083
再切点姜蒜

0:02:15.303,0:02:17.467
反正在自己家里做的话就随便一点

0:02:17.887,0:02:18.438
噶 四伯爷

0:02:21.580,0:02:22.834
姜还是宰哈

0:02:25.851,0:02:28.870
然后这个再给它配点其它东西

0:02:29.848,0:02:31.157
放点花椒

0:02:31.367,0:02:32.897
哎呀 好多哦放

0:02:33.115,0:02:34.838
这个就是要有麻味才好吃安

0:02:35.714,0:02:37.327
然后再配点这个芽菜

0:02:37.689,0:02:38.654
给它配在一起

0:02:39.346,0:02:41.152
炒出来的话就更有味道

0:02:42.340,0:02:42.822
好

0:02:43.662,0:02:45.206
差不多配齐了就可以炒了四伯爷

0:02:45.516,0:02:46.578
可以嘛 干嘛

0:02:48.419,0:02:51.631
干海椒 肉 芽菜 花椒 姜蒜

0:02:52.294,0:02:52.887
来嘛

0:02:53.127,0:02:53.495
干嘛

0:02:53.838,0:02:54.265
齐了

0:02:55.236,0:02:56.711
首先我们把锅烧热

0:02:57.156,0:02:59.334
锅烧热之后加入适量的油滑锅

0:02:59.454,0:03:01.246
滑好锅之后将热油倒出

0:03:01.789,0:03:03.554
再加入适量的底油烧热

0:03:04.822,0:03:07.049
油温5成热之后撒入适量的食用盐

0:03:07.405,0:03:09.721
这一步的目的是让四季豆进油盐

0:03:09.869,0:03:13.452
然后加入处理好的四季豆转中小火翻炒6分钟

0:03:13.452,0:03:16.623
这一步必须将四季豆炒熟炒至表面焦香

0:03:16.623,0:03:20.151
同学们切记不熟的四季豆容易引发食物中毒

0:03:26.172,0:03:27.654
炒熟之后倒出备用

0:03:31.895,0:03:34.869
然后直接加入剁好的猪肉末炒香爆出猪油

0:03:41.729,0:03:45.079
猪肉爆香之后加入准备好的花椒芽菜姜蒜末爆香

0:03:48.981,0:03:51.078
然后加入剪好的灯笼椒炒香

0:03:57.191,0:03:59.728
灯笼椒炒香之后加入四季豆翻炒几下

0:04:05.627,0:04:07.295
翻炒均匀之后开始调味

0:04:07.594,0:04:09.468
加入适量的食用盐撒入锅中

0:04:09.632,0:04:13.423
同学们炒四季豆可以适当的多加一些盐这样更加地入味

0:04:13.779,0:04:16.852
再撒入一些鸡精 不喜欢的同学可以不放

0:04:17.014,0:04:19.150
最后加入少许陈醋从锅边淋入

0:04:23.270,0:04:25.930
翻炒均匀炒出锅气之后即可出锅装盘

0:04:31.139,0:04:32.690
可以了四伯爷

0:04:33.495,0:04:34.405
尝哈看四伯爷

0:04:36.018,0:04:36.639
尝哈看嘛

0:04:38.744,0:04:42.245
我们这一次用了大量的这个灯笼椒

0:04:43.033,0:04:45.211
灯笼椒的主要作用就是提香

0:04:45.355,0:04:48.525
然后这个四季豆被我在锅里面用油

0:04:48.720,0:04:51.105
先把它爆焦了已经很香了

0:04:51.398,0:04:53.920
然后再爆之前油里面是放了一点盐的

0:04:54.300,0:04:56.450
所以这个四季豆中间都是有味道的

0:04:58.317,0:04:59.305
在家里面做的话

0:04:59.625,0:05:01.854
就放点油先把它炒焦炒熟

0:05:02.156,0:05:03.344
然后再炒其他的佐料

0:05:03.344,0:05:04.227
再一起炒

0:05:04.905,0:05:07.160
不用花太多油去做这个菜

0:05:10.047,0:05:10.598
好吃

0:05:12.559,0:05:13.013
安逸

0:05:15.059,0:05:17.227
但是干辣椒的这个籽啊太多了

0:05:17.902,0:05:19.843
去掉90%的籽

0:05:21.113,0:05:23.222
这个壳给它爆香了

0:05:23.578,0:05:24.487
炒出来很香

0:05:28.637,0:05:32.098
人家都说这个四季豆油盐不进

0:05:32.345,0:05:33.919
这回我就让它进了油盐的噻

0:05:34.778,0:05:36.080
这道四季豆这个做法

0:05:36.080,0:05:38.231
强烈推荐你们去试下

0:05:40.297,0:05:40.603
好了

0:05:40.715,0:05:41.571
本期视频就到这里

0:05:42.935,0:05:44.229
可以这个四季豆炒得

0:05:45.593,0:05:46.143
拜拜

0:05:49.024,0:05:50.405
你尝一下这个肉四伯爷

0:05:50.716,0:05:53.584
这个肉也好吃

0:05:54.876,0:05:56.122
肯定噻

0:05:59.177,0:06:03.219
那下次不要宰这么碎 宰大块点好夹点

0:06:03.713,0:06:05.499
宰碎点出味道安

0:06:06.533,0:06:08.272
夹都夹不起来你宰碎很了 

0:06:21.232,0:06:24.003
这个肉也好吃

0:06:25.550,0:06:26.451
肯定噻

0:06:29.633,0:06:32.141
下次不要宰这么碎 

0:06:32.167,0:06:33.444
宰大块点的好夹

0:06:34.204,0:06:35.817
要宰碎点出味道安

0:06:37.045,0:06:38.575
夹都夹不起来你宰碎很了


```

**Comment by immoonancient** [comment]
@glasscatfish 请前来认领

**Comment by glasscatfish** [comment]
认领

**Comment by glasscatfish** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“干煸四季豆”的真家常做法，不用宽油也能真香，下饭神器！
The Real homely way of “dry-fried French beans”. No need for Kuan You (broad oil)!

简介
朋友们大家好，今天和大家分享下饭神器“干煸四季豆”，这是一道受到很多朋友喜欢的菜，只不过阻止大家在家制作的原因是“宽油”，那我今天就来教教大家不用宽油做出完美的干煸四季豆。其实最正宗的“干煸”是今天教给大家的这种方法，之所以大多数后厨会选择用宽油来炸四季豆是为了更短的出菜时间，如果是炸基本上1分半就可以保证四季豆熟透，但干煸需要6分钟，无形中给后厨增加了很多时间成本。如果大家有兴趣想学宽油版的干煸四季豆可以点击链接：https://www.youtube.com/watch?v=QAmnxADJL54
Hello everyone, today I will share with you a dish that goes very well with rice, “dry-fried French beans”. This is a popular dish many of you like, however, I realized that Kuan You (broad oil) has stopped you from making it. Today, I will teach you a way that doesn’t require Kuan You. this is the real way of making dry-fry dishes is the one I’m showing you today. Chefs choose to make it using Kuan You because it takes less time, deep-frying with Kuan You takes only one minute, while it takes six minutes for the beans to get fully cooked when dry frying, which would cost more time. If you’d like to learn the Kuan You way of making dry-fried French beans, here’s a link: https://www.youtube.com/watch?v=QAmnxADJL54


字幕
0:00:00.279,0:00:01.075
哈喽 大家好
Hello everyone

0:00:01.163,0:00:03.460
最近我伯爷说这个灯笼椒
Recently, uncle said that the dried pimentos 

0:00:03.460,0:00:05.979
他以前买的放的时间够长了
that he bought has been sitting around for long enough.

0:00:05.994,0:00:07.054
再不吃要坏了
It’s going to go bad if we let it sit for longer. 

0:00:07.275,0:00:10.044
然后为了想这个灯笼椒怎么吃
So in order to use these pimentos,

0:00:10.294,0:00:12.312
我让我伯爷去买了点四季豆回来
I asked my uncle to get some French beans. 

0:00:12.901,0:00:14.933
然后今天正好跟大家分享一下
I will share it with you. 

0:00:15.007,0:00:17.201
我们家庭小灶做干煸四季豆
How to make tasty dry-fried french beans at home

0:00:17.540,0:00:19.859
不用宽油炸怎么把它做得
without Kuan You.

0:00:19.926,0:00:21.016
也能做的很好吃吧
（注：因语意通顺的关系，本句与上两句一起翻译）

0:00:21.914,0:00:23.048
我先把海椒剪了
I will first cut the dried chilis 

0:00:23.210,0:00:24.521
放了好久了
It’s been sitting around for a long time.

0:00:24.771,0:00:26.126
硬是再放（久点）要不得了
We’d have to throw it out if it sits for longer.

0:00:27.893,0:00:29.602
再不吃都发霉了噶
It will get molded. 

0:00:29.793,0:00:30.309
就是
Right.

0:00:30.883,0:00:34.108
我们一般这个灯笼椒很少用来炒菜
We rarely use pimentos for stir fry.

0:00:34.948,0:00:37.083
灯笼椒的话它主要是出香味
It is usually used for its aroma. 

0:00:37.614,0:00:40.353
它是不辣的也出不了什么颜色
It’s not spicy and doesn’t add any color to the dish. 

0:00:41.222,0:00:42.488
待会我们再加点这个
We will add some of this later,

0:00:43.181,0:00:46.774
再加一点我们自己这个小米辣
some "Xiaomila" chili pepper.

0:00:47.290,0:00:48.085
这个就辣安
This is spicy,

0:00:48.954,0:00:50.058
这个出辣味的
it gives spiciness.

0:00:50.324,0:00:52.017
子弹头的话就出颜色
"Zidantou" chili pepper, on the other hand, gives color.

0:00:52.754,0:00:54.639
这个四季豆炒出来香哦
This will be aromatic.

0:00:55.125,0:00:57.702
香   油都没得等哈儿你炒来看香不香嘛
Aromatic? You don’t even add oil, let’s see if it will be aromatic.

0:00:57.923,0:00:58.836
你又不放油
You don’t even put oil.

0:00:59.248,0:01:00.338
你放心四伯爷
Relax, uncle.

0:01:00.368,0:01:01.617
我不是说不放油
I’m not saying we are not putting oil at all. 

0:01:01.617,0:01:02.805
是不拿油来炸
We just don’t deep fry. 

0:01:02.867,0:01:04.641
哦喔 那还差不多
Oh, that sounds better. 

0:01:04.798,0:01:06.669
我剪这个 四伯爷你掐四季豆
I will cut this. Could you please break the beans, uncle?

0:01:07.097,0:01:08.776
这个咋子嘛 撕过嘎
How? Do I just tear it?

0:01:08.872,0:01:10.725
把老筋撕了就是
Right, just remove the hard fibers. 

0:01:11.984,0:01:14.746
大四季豆的那个筋就多了
Older french beans are more fibrous. 

0:01:14.877,0:01:15.375
老噶
Old. 

0:01:15.769,0:01:16.363
嗯
Right.

0:01:20.531,0:01:23.162
还是坏的比较多哦 四伯爷
Many of them have gone bad, uncle.

0:01:23.844,0:01:25.592
坏的就丢了噻 不要噻
We should throw them out then, don’t use them.

0:01:26.155,0:01:27.344
我都剪了好几个坏的了
Couple of ones I cut were bad. 

0:01:27.750,0:01:29.244
再不吃发霉了
It will go bad if we still don’t use them.

0:01:33.617,0:01:35.278
好了 这个干辣椒我剪好了
Ok. Now I’ve cut all the chilies. 

0:01:35.927,0:01:37.134
我把这个捞一下
I’m transferring them to another bowel. 

0:01:37.134,0:01:38.515
这个（辣椒）籽太多了
There are too many seeds. 

0:01:39.270,0:01:41.429
我们把这个籽去掉一些
We will remove some seeds. 

0:01:42.720,0:01:45.290
这个干煸四季豆的话就用这个五花肉
Let’s get some pork belly

0:01:46.747,0:01:49.739
给它切成小颗粒切碎
And mince them. 

0:01:51.398,0:01:52.989
我们做干煸四季豆
When we make dry-fried french beans,

0:01:52.989,0:01:56.179
放肥一点的这个猪肉的话
add some pork,

0:01:56.179,0:02:00.399
它出来的猪油可以把味道吸在这个四季豆上面
the beans absorb flavour from rendered fat.

0:02:00.399,0:02:02.611
所以就会有味道有盐味
It would be more flavourful. 

0:02:05.060,0:02:06.521
这样子整起肯定好吃
It’s tastier. 

0:02:06.914,0:02:08.540
把这个肉宰哈宰哈就可以了
Just chopt the pork.

0:02:12.477,0:02:13.484
这个肉准备好了 
Now, the pork is ready. 

0:02:13.484,0:02:15.083
再切点姜蒜
Let’s chop some garlic and ginger as well.

0:02:15.303,0:02:17.467
反正在自己家里做的话就随便一点
We can improvise when cooking at home. 

0:02:17.887,0:02:18.438
噶 四伯爷
Right, uncle?

0:02:21.580,0:02:22.834
姜还是宰哈
We chop the ginger. 


0:02:25.851,0:02:28.870
然后这个再给它配点其它东西
Then we add some other ingredients, 

0:02:29.848,0:02:31.157
放点花椒
some Sichuan peppercorn.

0:02:31.367,0:02:32.897
哎呀 好多哦放
Wow, so much!

0:02:33.115,0:02:34.838
这个就是要有麻味才好吃安
It tastes better when it's numbing. 

0:02:35.714,0:02:37.327
然后再配点这个芽菜
Let’s add some "Ya Cai" (Sichuan preserved mustard greens) too.

0:02:37.689,0:02:38.654
给它配在一起
Put them together. 

0:02:39.346,0:02:41.152
炒出来的话就更有味道
It’s more flavourful. 

0:02:42.340,0:02:42.822
好
Ok. 

0:02:43.662,0:02:45.206
差不多配齐了就可以炒了四伯爷
We’ve done all the prep and are ready to cook, uncle. 

0:02:45.516,0:02:46.578
可以嘛 干嘛
Let’s cook then!

0:02:48.419,0:02:51.631
干海椒 肉 芽菜 花椒 姜蒜
Dried chili pepper, pork, Ya Cai, Sichuan peppercorn, ginger, garlic.  

0:02:52.294,0:02:52.887
来嘛
Let’s go!

0:02:53.127,0:02:53.495
干嘛
Go!

0:02:53.838,0:02:54.265
齐了
Ready!

0:02:55.236,0:02:56.711
首先我们把锅烧热
First, let’s heat the wok.

0:02:57.156,0:02:59.334
锅烧热之后加入适量的油滑锅
Add some oil to grease the wok. 

0:02:59.454,0:03:01.246
滑好锅之后将热油倒出
Pour out the oil after greasing the wok. 

0:03:01.789,0:03:03.554
再加入适量的底油烧热
Then add some base oil.

0:03:04.822,0:03:07.049
油温5成热之后撒入适量的食用盐
When the oil reaches 150°C, add some salt. 

0:03:07.405,0:03:09.721
这一步的目的是让四季豆进油盐
This is to make sure the beans are put in salted oil.

0:03:09.869,0:03:13.452
然后加入处理好的四季豆转中小火翻炒6分钟
Add the beans, turn the heat to medium-low and stir fry for 6 minutes. 

0:03:13.452,0:03:16.623
这一步必须将四季豆炒熟炒至表面焦香
Cook until the beans are lightly brown.

0:03:16.623,0:03:20.151
同学们切记不熟的四季豆容易引发食物中毒
Friends, be sure to keep in mind that uncooked beans are toxic. 

0:03:26.172,0:03:27.654
炒熟之后倒出备用
Remove the beans, set aside. 

0:03:31.895,0:03:34.869
然后直接加入剁好的猪肉末炒香爆出猪油
Add minced pork, render the fat, and release the aroma. 

0:03:41.729,0:03:45.079
猪肉爆香之后加入准备好的花椒芽菜姜蒜末爆香
Then add Sichuan peppercorn, Ya Cai, ginger and garlic, fry until fragrant.

0:03:48.981,0:03:51.078
然后加入剪好的灯笼椒炒香
Add cut pimentos, saute 

0:03:57.191,0:03:59.728
灯笼椒炒香之后加入四季豆翻炒几下
Add beans to combine, 

0:04:05.627,0:04:07.295
翻炒均匀之后开始调味
then start seasoning. 

0:04:07.594,0:04:09.468
加入适量的食用盐撒入锅中
Add some salt.

0:04:09.632,0:04:13.423
同学们炒四季豆可以适当的多加一些盐这样更加地入味
You can put a little more salt than usual to incorporate more flavour. 

0:04:13.779,0:04:16.852
再撒入一些鸡精 不喜欢的同学可以不放
Add chicken bouillon, you can opt it out if you don’t like it. 

0:04:17.014,0:04:19.150
最后加入少许陈醋从锅边淋入
Sprinkle some vinegar along the side of the wok. 

0:04:23.270,0:04:25.930
翻炒均匀炒出锅气之后即可出锅装盘
Mix it until everything is fully combined, remove the beans from the wok and plate.  

0:04:31.139,0:04:32.690
可以了四伯爷
It’s done, uncle.

0:04:33.495,0:04:34.405
尝哈看四伯爷
Please have a taste.

0:04:36.018,0:04:36.639
尝哈看嘛
Try it.

0:04:38.744,0:04:42.245
我们这一次用了大量的这个灯笼椒
We used lots of pimentos this time.

0:04:43.033,0:04:45.211
灯笼椒的主要作用就是提香
The purpose is to make the dish more fragrant.

0:04:45.355,0:04:48.525
然后这个四季豆被我在锅里面用油
And the beans are brown in the wok,

0:04:48.720,0:04:51.105
先把它爆焦了已经很香了
so it’s already very appetizing.

0:04:51.398,0:04:53.920
然后再爆之前油里面是放了一点盐的
Then, because we added some salt in the oil

0:04:54.300,0:04:56.450
所以这个四季豆中间都是有味道的
The saltiness has penetrated the beans.

0:04:58.317,0:04:59.305
在家里面做的话
To cook it at home,

0:04:59.625,0:05:01.854
就放点油先把它炒焦炒熟
put some oil, stir fry it until lightly browned and cooked.

0:05:02.156,0:05:03.344
然后再炒其他的佐料
Add other ingredients, 

0:05:03.344,0:05:04.227
再一起炒
and cook together

0:05:04.905,0:05:07.160
不用花太多油去做这个菜
This dish doesn’t need to much oil

0:05:10.047,0:05:10.598
好吃
Tasty!

0:05:12.559,0:05:13.013
安逸
nice

0:05:15.059,0:05:17.227
但是干辣椒的这个籽啊太多了
But pimento has too many seeds 

0:05:17.902,0:05:19.843
去掉90%的籽
Remove 90% of the seeds

0:05:21.113,0:05:23.222
这个壳给它爆香了
Fry to release the aroma of the pimento itself.

0:05:23.578,0:05:24.487
炒出来很香
It is very fragrant.

0:05:28.637,0:05:32.098
人家都说这个四季豆油盐不进
It is said that it’s hard for french beans to absorb oil and salt.

0:05:32.345,0:05:33.919
这回我就让它进了油盐的噻
This time I made it happen.

0:05:34.778,0:05:36.080
这道四季豆这个做法
I recommend you to try 

0:05:36.080,0:05:38.231
强烈推荐你们去试下
this french bean recipe. (注：此处调换两句话位置更通顺些)

0:05:40.297,0:05:40.603
好了
Ok.

0:05:40.715,0:05:41.571
本期视频就到这里
It’s the end of the video.

0:05:42.935,0:05:44.229
可以这个四季豆炒得
The french beans are really nice.

0:05:45.593,0:05:46.143
拜拜
Bye!

0:05:49.024,0:05:50.405
你尝一下这个肉四伯爷
Try the pork.

0:05:50.716,0:05:53.584
这个肉也好吃
It’s tasty too. 

0:05:54.876,0:05:56.122
肯定噻
Of course!

0:05:59.177,0:06:03.219
那下次不要宰这么碎 宰大块点好夹点
Next time don’t mince it too small, keep it bigger so it’s easier to be picked up.

0:06:03.713,0:06:05.499
宰碎点出味道安
You get more flavour out of it when it’s minced small.

0:06:06.533,0:06:08.272
夹都夹不起来你宰碎很了 
But I couldn’t pick it up, it’s too small. 

0:06:21.232,0:06:24.003
这个肉也好吃
（注：从这句开始和上面重复了，视频中只有一次这段对话）

0:06:25.550,0:06:26.451
肯定噻

0:06:29.633,0:06:32.141
下次不要宰这么碎 

0:06:32.167,0:06:33.444
宰大块点的好夹

0:06:34.204,0:06:35.817
要宰碎点出味道安

0:06:37.045,0:06:38.575
夹都夹不起来你宰碎很了
v标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“干煸四季豆”的真家常做法，不用宽油也能真香，下饭神器！
The Real homely way of “dry-fried French beans”. No need for Kuan You (broad oil)!
