### ISSUE TITLE
【美食作家王刚】红油腰花 - https://youtu.be/ScPoI42mRh4

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#950]
**视频链接**：https://youtu.be/ScPoI42mRh4

视频时长4:28，预计发布时间为北京时间4月26日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：川味正宗“红油腰花”的做法，进阶刀工必学，口感味道一流

简介
同学们好，今天教大家一道“红油腰花”，这道菜重点在于猪腰的处理和切花，处理猪腰的时候需把白色筋膜（腰骚）去除干净，这样才能保证没有腥臊味，然后在切花时使用斜刀可以帮助成菜时“花”更加饱满好看。最后猪腰不能过火烹饪，要严控的时间，保证成品的鲜嫩。如果大家还想学炒腰花的话可以点击链接：https://www.youtube.com/watch?v=xuJJpTHfiu8 但需要注意的是炒腰花的话腰花不能切太长，容易不成型，所以切第二次的时候直刀即可。

本期菜品:【红油腰花】
【主料】
猪腰（几个）   
【辅料】
啤酒（适量）
莴笋（200克）
大蒜（2颗）
小葱头（几根）
香菜根（适量）
土豆淀粉（1小把）
【调味料】
食用盐（适量）
白糖（少许）
陈醋（1克）
生抽酱油（5克）
香辣红油（50克）
料酒（适量）

字幕
0:00:00.220,0:00:01.480
哈喽大家好我是王刚

0:00:01.480,0:00:03.360
本期视频我给大家分享一道家常菜

0:00:03.820,0:00:04.660
红油腰花

0:00:04.840,0:00:07.220
首先我们准备新鲜的猪腰几个

0:00:07.800,0:00:10.325
从中间片开之后平刀去掉腰骚备用

0:00:10.581,0:00:12.625
建议新手同学交给摊主来处理

0:00:12.825,0:00:14.900
否则有可能猪腰会所剩无几

0:00:17.400,0:00:20.300
筋膜去除干净之后下一步开始准备切腰花

0:00:20.650,0:00:23.125
首先我们斜刀切进猪腰的4分之3

0:00:23.250,0:00:26.625
同学们这一步既要切深一些但也不能切断

0:00:32.475,0:00:35.225
然后将猪腰倒过来竖着斜刀切出腰花

0:00:35.350,0:00:37.650
这两步都必须尽量把刀倾斜起来

0:00:37.800,0:00:40.925
角度倾斜得越大切出来的腰花则越长

0:00:56.675,0:00:59.150
然后将切好的猪腰翻面切成小条备用

0:01:04.000,0:01:05.675
下一步开始准备初加工

0:01:06.150,0:01:09.125
碗中加入适量的啤酒将腰花浸泡10分钟备用

0:01:09.225,0:01:11.325
这一步的目的是去除猪腰的骚味

0:01:16.675,0:01:18.075
下一步开始准备辅料

0:01:18.750,0:01:20.750
准备莴笋200克切成细丝备用

0:01:20.900,0:01:23.425
不喜欢莴笋的同学也可以用青瓜丝代替

0:01:23.650,0:01:25.625
还可以用焯熟的绿豆芽代替

0:01:26.625,0:01:30.825
笋丝切好之后加入食用盐1小勺搅拌均匀腌制5分钟备用

0:01:31.000,0:01:33.325
这一步的目的是去除笋丝中的生水

0:01:33.425,0:01:35.775
5分钟之后捞出挤干水分垫底备用

0:01:37.000,0:01:38.525
下一步开始调红油

0:01:41.075,0:01:43.225
准备大蒜2颗拍散之后剁碎备用

0:01:46.925,0:01:49.175
准备小葱头几根拍散之后切碎备用

0:01:53.500,0:01:55.525
最后准备适量的香菜根剁碎备用

0:01:55.700,0:01:58.625
同学们香菜梗必须清洗干净否则会有泥沙

0:01:59.950,0:02:01.850
碗中加入食用盐0.5克

0:02:01.975,0:02:03.125
加入少许白糖

0:02:03.575,0:02:04.750
加入陈醋1克

0:02:05.825,0:02:07.500
加入生抽酱油5克

0:02:08.700,0:02:10.500
最后加入香辣红油50克

0:02:14.075,0:02:16.375
搅拌均匀之后下一步开始处理腰花

0:02:18.450,0:02:21.400
首先我们在锅中加入适量的清水开大火烧开

0:02:23.650,0:02:25.150
中途加入适量的料酒

0:02:32.000,0:02:34.325
然后将腌制好的猪腰倒出沥干啤酒

0:02:38.225,0:02:40.500
用清水清洗干净之后挤干水份

0:02:45.075,0:02:47.725
挤干水份之后加入少许食用盐搅拌均匀（上底味）

0:02:53.450,0:02:55.600
最后再加入1小把土豆淀粉拌匀

0:02:55.975,0:02:58.475
这一步的目的是让腰花保持嫩度和爽脆

0:03:00.450,0:03:02.950
拌匀之后将腰花下入烧开的水中

0:03:05.600,0:03:08.375
然后待水再次开起来10秒钟即可倒出

0:03:08.625,0:03:11.525
同学们切记猪腰不能煮太久否则不嫩

0:03:11.875,0:03:15.375
此刀法切的腰花10秒钟足以煮熟所以不必担心

0:03:30.925,0:03:32.950
沥干水份之后将腰花摆盘

0:03:45.800,0:03:48.100
最后再淋上调好的红油料（汁）即可上菜

0:03:53.580,0:03:56.060
一道非常美味的红油腰花就制作完成

0:04:09.520,0:04:27.640
下面开始技术总结
第一，必须选择微白粉红的猪腰，凡是发黑有淤血的猪腰均为死猪或者病猪
第二，不会切腰花的同学可以直接切成小片
第三，猪腰下锅之前必须加入盐和干淀粉拌匀，这样成菜才足够鲜嫩爽脆
红油腰花 的技术总结完毕

```

**Comment by LuoGuiwen** [comment]
这个我来翻啦

**Comment by LuoGuiwen** [comment]
厨师长教你：川味正宗“红油腰花”的做法，进阶刀工必学，口感味道一流

简介
同学们好，今天教大家一道“红油腰花”，这道菜重点在于猪腰的处理和切花，处理猪腰的时候需把白色筋膜（腰骚）去除干净，这样才能保证没有腥臊味，然后在切花时使用斜刀可以帮助成菜时“花”更加饱满好看。最后猪腰不能过火烹饪，要严控的时间，保证成品的鲜嫩。如果大家还想学炒腰花的话可以点击链接：https://www.youtube.com/watch?v=xuJJpTHfiu8 但需要注意的是炒腰花的话腰花不能切太长，容易不成型，所以切第二次的时候直刀即可。

Hello everyone, today I'm gonna teach you a dish called "red oil kidneys“. The key point is how to clean and cut pig's kidneys. When clean the kidneys, the white fascia (that emits urine smell) should be fully removed, such that there is no urine smell. the kidney should be slant-cut, which makes the prepared product a beautiful flower-like shape. Finally, Pig kidneys can't be over cooked. Cooking time should be precisely controlled to ensure a fresh and tender taste. For more tutorial on how to cook pig kidneys, please click following url,

https://www.youtube.com/watch?v=xuJJpTHfiu8 

It should be noted that when cutting the kidney, each piece can't be too long, otherwise it's hard to turn into a flower-like shape. So the second cut should be done vertically.

本期菜品:【红油腰花】
【主料】
猪腰（几个）   
【辅料】
啤酒（适量）
莴笋（200克）
大蒜（2颗）
小葱头（几根）
香菜根（适量）
土豆淀粉（1小把）
【调味料】
食用盐（适量）
白糖（少许）
陈醋（1克）
生抽酱油（5克）
香辣红油（50克）
料酒（适量）

--Major ingredients--
Pig's kidneys (several)

--Other ingredients--
Beer (appropriate amount)
Lettuce (200g)
Garlic (2 pieces)
Shallots (several)
Coriander root (appropriate amount)
Potato starch (small amount)

--seasoning--
Edible salt (appropriate amount)
White sugar (a little)
Vinegar (1g)
light soy sauce (5g)
Spicy Red Oil (50g)
Chinese cooking wine (appropriate amount)

字幕
0:00:00.220,0:00:01.480
哈喽大家好我是王刚
Hi everyone, This is Chef Wang

0:00:01.480,0:00:03.360
本期视频我给大家分享一道家常菜
In this video I'll share a homely dish with you

0:00:03.820,0:00:04.660
红油腰花
"red oil kidneys“

0:00:04.840,0:00:07.220
首先我们准备新鲜的猪腰几个
First we prepare a few fresh pig's kidneys

0:00:07.800,0:00:10.325
从中间片开之后平刀去掉腰骚备用
cut in the middle, remove all white fascias

0:00:10.581,0:00:12.625
建议新手同学交给摊主来处理
It is recommended that for a novice you better ask the meat seller to do this step for you.

0:00:12.825,0:00:14.900
否则有可能猪腰会所剩无几
Otherwise there may be little kidneys left.

0:00:17.400,0:00:20.300
筋膜去除干净之后下一步开始准备切腰花
After removing all white fascias, next we are going to cut the kidneys into flower-like shape.

0:00:20.650,0:00:23.125
首先我们斜刀切进猪腰的4分之3
We slantly cut into the kidney 3/4.

0:00:23.250,0:00:26.625
同学们这一步既要切深一些但也不能切断
This step must cut deep enough but not cut off.


0:00:32.475,0:00:35.225
然后将猪腰倒过来竖着斜刀切出腰花
Then change a direction slant-cut the kidney into flower-like shape.

0:00:35.350,0:00:37.650
这两步都必须尽量把刀倾斜起来
Both steps must tilt the knife as much as possible

0:00:37.800,0:00:40.925
角度倾斜得越大切出来的腰花则越长
The greater the angle of tilting, the longer the flower-like shape will be.

0:00:56.675,0:00:59.150
然后将切好的猪腰翻面切成小条备用
Then turn the kidney over and cut it into small strips. 


0:01:04.000,0:01:05.675
下一步开始准备初加工
Next step is preliminary processing

0:01:06.150,0:01:09.125
碗中加入适量的啤酒将腰花浸泡10分钟备用
Add moderate amount of beer to the bowl, soak the kidney flowers for 10 minutes.

0:01:09.225,0:01:11.325
这一步的目的是去除猪腰的骚味
The purpose of this step is to remove the smell of kidneys.

0:01:16.675,0:01:18.075
下一步开始准备辅料
Next, prepare assistant ingredients

0:01:18.750,0:01:20.750
准备莴笋200克切成细丝备用
Prepare 200g lettuce and cut into fine shreds

0:01:20.900,0:01:23.425
不喜欢莴笋的同学也可以用青瓜丝代替
Those who do not like lettuce can use cucumber instead,

0:01:23.650,0:01:25.625
还可以用焯熟的绿豆芽代替
and can also use boiled mung-bean sprouts instead.


0:01:26.625,0:01:30.825
笋丝切好之后加入食用盐1小勺搅拌均匀腌制5分钟备用
When lettuce shreds are prepared, add 1 teaspoon of salt, mix them together, marinate for 5 minutes.

0:01:31.000,0:01:33.325
这一步的目的是去除笋丝中的生水
The purpose of this step is to remove water from lettuce.

0:01:33.425,0:01:35.775
5分钟之后捞出挤干水分垫底备用
5 minutes later, squeeze out the water, then put them in the bottom of the bowl

0:01:37.000,0:01:38.525
下一步开始调红油
Next, prepare red oil

0:01:41.075,0:01:43.225
准备大蒜2颗拍散之后剁碎备用
Prepare 2 garlic pieces and crush them up

0:01:46.925,0:01:49.175
准备小葱头几根拍散之后切碎备用
Prepare a few green onions and chop them up

0:01:53.500,0:01:55.525
最后准备适量的香菜根剁碎备用
Finally, prepare an appropriate amount of cilantro roots, chop them up.

0:01:55.700,0:01:58.625
同学们香菜梗必须清洗干净否则会有泥沙
Cilantro roots must be carefully cleaned, otherwise there are remaining fine sands.

0:01:59.950,0:02:01.850
碗中加入食用盐0.5克
Add 0.5g of salt into the bowl

0:02:01.975,0:02:03.125
加入少许白糖
Add a little white sugar

0:02:03.575,0:02:04.750
加入陈醋1克
Add 1g of vinegar

0:02:05.825,0:02:07.500
加入生抽酱油5克
Add 5g of light soy sauce	

0:02:08.700,0:02:10.500
最后加入香辣红油50克
In the end, add 50g of spicy red oil, mix them together

0:02:14.075,0:02:16.375
搅拌均匀之后下一步开始处理腰花
Next deal with the kidneys

0:02:18.450,0:02:21.400
首先我们在锅中加入适量的清水开大火烧开
First, we add the right amount of water into the pot and boil it

0:02:23.650,0:02:25.150
中途加入适量的料酒

Add the right amount of Chinese cooking wine during the heating

0:02:32.000,0:02:34.325
然后将腌制好的猪腰倒出沥干啤酒
Then pour out the marinated kidneys and drain the beer

0:02:38.225,0:02:40.500
用清水清洗干净之后挤干水份
Rinse it with clean water and squeeze water out

0:02:45.075,0:02:47.725
挤干水份之后加入少许食用盐搅拌均匀（上底味）
After squeezing out the water, add a little salt and mix them well (to increase the base taste)

0:02:53.450,0:02:55.600
最后再加入1小把土豆淀粉拌匀
Finally add 1 small handful of potato starch and mix them well

0:02:55.975,0:02:58.475
这一步的目的是让腰花保持嫩度和爽脆
The purpose of this step is to keep the kidneys tender and crisp

0:03:00.450,0:03:02.950
拌匀之后将腰花下入烧开的水中
Then put the kidneys into the boiling water

0:03:05.600,0:03:08.375
然后待水再次开起来10秒钟即可倒出
Wait for the water to boil again, then pour kidneys out in 10 seconds

0:03:08.625,0:03:11.525
同学们切记猪腰不能煮太久否则不嫩
Remember that the kidneys can't be cooked too long or it won't taste tender

0:03:11.875,0:03:15.375
此刀法切的腰花10秒钟足以煮熟所以不必担心
10 seconds is long enough to cook well the kidneys that are cut by this knife skill, so don't worry about it.

0:03:30.925,0:03:32.950
沥干水份之后将腰花摆盘
After draining out the water, place the kidneys on the plate

0:03:45.800,0:03:48.100
最后再淋上调好的红油料（汁）即可上菜
Finally, drizzle the prepared red oil to serve

0:03:53.580,0:03:56.060
一道非常美味的红油腰花就制作完成
A very delicious dish "red oil kidneys" is finished

0:04:09.520,0:04:27.640
下面开始技术总结
第一，必须选择微白粉红的猪腰，凡是发黑有淤血的猪腰均为死猪或者病猪
第二，不会切腰花的同学可以直接切成小片
第三，猪腰下锅之前必须加入盐和干淀粉拌匀，这样成菜才足够鲜嫩爽脆
红油腰花 的技术总结完毕

The technical summary is as below,

First, you must choose the pig's kidneys that are slightly white and pink. 
Any black and bruised kidney is from the dead or sick pig.

Second, those who don't know how to cut kidneys into flower-like shape can directly cut into small pieces.

Third, Before cooking the kidneys, salt and dry starch must be added and mixed well, so that the dish is fresh and crisp.

That's the technical summary of "red oil kidneys".

**Comment by LuoGuiwen** [comment]
卧槽，忘翻标题了。改过

**Comment by LuoGuiwen** [comment]
厨师长教你：川味正宗“红油腰花”的做法，进阶刀工必学，口感味道一流
Chef Wang teaches you: The first-class taste authentic Sichuan "red oil kidneys" recipe, and advanced cutting skills 

简介
同学们好，今天教大家一道“红油腰花”，这道菜重点在于猪腰的处理和切花，处理猪腰的时候需把白色筋膜（腰骚）去除干净，这样才能保证没有腥臊味，然后在切花时使用斜刀可以帮助成菜时“花”更加饱满好看。最后猪腰不能过火烹饪，要严控的时间，保证成品的鲜嫩。如果大家还想学炒腰花的话可以点击链接：https://www.youtube.com/watch?v=xuJJpTHfiu8 但需要注意的是炒腰花的话腰花不能切太长，容易不成型，所以切第二次的时候直刀即可。

Hello everyone, today I'm gonna teach you a dish called "red oil kidneys“. The key point is how to clean and cut pig's kidneys. When clean the kidneys, the white fascia (that emits urine smell) should be fully removed, such that there is no urine smell. the kidney should be slant-cut, which makes the prepared product a beautiful flower-like shape. Finally, Pig kidneys can't be over cooked. Cooking time should be precisely controlled to ensure a fresh and tender taste. For more tutorial on how to cook pig kidneys, please click following url,

https://www.youtube.com/watch?v=xuJJpTHfiu8 

It should be noted that when cutting the kidney, each piece can't be too long, otherwise it's hard to turn into a flower-like shape. So the second cut should be done vertically.

本期菜品:【红油腰花】
【主料】
猪腰（几个）   
【辅料】
啤酒（适量）
莴笋（200克）
大蒜（2颗）
小葱头（几根）
香菜根（适量）
土豆淀粉（1小把）
【调味料】
食用盐（适量）
白糖（少许）
陈醋（1克）
生抽酱油（5克）
香辣红油（50克）
料酒（适量）

--Major ingredients--
Pig's kidneys (several)

--Other ingredients--
Beer (appropriate amount)
Lettuce (200g)
Garlic (2 pieces)
Shallots (several)
Coriander root (appropriate amount)
Potato starch (small amount)

--seasoning--
Edible salt (appropriate amount)
White sugar (a little)
Vinegar (1g)
light soy sauce (5g)
Spicy Red Oil (50g)
Chinese cooking wine (appropriate amount)

字幕
0:00:00.220,0:00:01.480
哈喽大家好我是王刚
Hi everyone, This is Chef Wang

0:00:01.480,0:00:03.360
本期视频我给大家分享一道家常菜
In this video I'll share a homely dish with you

0:00:03.820,0:00:04.660
红油腰花
"red oil kidneys“

0:00:04.840,0:00:07.220
首先我们准备新鲜的猪腰几个
First we prepare a few fresh pig's kidneys

0:00:07.800,0:00:10.325
从中间片开之后平刀去掉腰骚备用
cut in the middle, remove all white fascias

0:00:10.581,0:00:12.625
建议新手同学交给摊主来处理
It is recommended that for a novice you better ask the meat seller to do this step for you.

0:00:12.825,0:00:14.900
否则有可能猪腰会所剩无几
Otherwise there may be little kidneys left.

0:00:17.400,0:00:20.300
筋膜去除干净之后下一步开始准备切腰花
After removing all white fascias, next we are going to cut the kidneys into flower-like shape.

0:00:20.650,0:00:23.125
首先我们斜刀切进猪腰的4分之3
We slantly cut into the kidney 3/4.

0:00:23.250,0:00:26.625
同学们这一步既要切深一些但也不能切断
This step must cut deep enough but not cut off.


0:00:32.475,0:00:35.225
然后将猪腰倒过来竖着斜刀切出腰花
Then change a direction slant-cut the kidney into flower-like shape.

0:00:35.350,0:00:37.650
这两步都必须尽量把刀倾斜起来
Both steps must tilt the knife as much as possible

0:00:37.800,0:00:40.925
角度倾斜得越大切出来的腰花则越长
The greater the angle of tilting, the longer the flower-like shape will be.

0:00:56.675,0:00:59.150
然后将切好的猪腰翻面切成小条备用
Then turn the kidney over and cut it into small strips. 


0:01:04.000,0:01:05.675
下一步开始准备初加工
Next step is preliminary processing

0:01:06.150,0:01:09.125
碗中加入适量的啤酒将腰花浸泡10分钟备用
Add moderate amount of beer to the bowl, soak the kidney flowers for 10 minutes.

0:01:09.225,0:01:11.325
这一步的目的是去除猪腰的骚味
The purpose of this step is to remove the smell of kidneys.

0:01:16.675,0:01:18.075
下一步开始准备辅料
Next, prepare assistant ingredients

0:01:18.750,0:01:20.750
准备莴笋200克切成细丝备用
Prepare 200g lettuce and cut into fine shreds

0:01:20.900,0:01:23.425
不喜欢莴笋的同学也可以用青瓜丝代替
Those who do not like lettuce can use cucumber instead,

0:01:23.650,0:01:25.625
还可以用焯熟的绿豆芽代替
and can also use boiled mung-bean sprouts instead.


0:01:26.625,0:01:30.825
笋丝切好之后加入食用盐1小勺搅拌均匀腌制5分钟备用
When lettuce shreds are prepared, add 1 teaspoon of salt, mix them together, marinate for 5 minutes.

0:01:31.000,0:01:33.325
这一步的目的是去除笋丝中的生水
The purpose of this step is to remove water from lettuce.

0:01:33.425,0:01:35.775
5分钟之后捞出挤干水分垫底备用
5 minutes later, squeeze out the water, then put them in the bottom of the bowl

0:01:37.000,0:01:38.525
下一步开始调红油
Next, prepare red oil

0:01:41.075,0:01:43.225
准备大蒜2颗拍散之后剁碎备用
Prepare 2 garlic pieces and crush them up

0:01:46.925,0:01:49.175
准备小葱头几根拍散之后切碎备用
Prepare a few green onions and chop them up

0:01:53.500,0:01:55.525
最后准备适量的香菜根剁碎备用
Finally, prepare an appropriate amount of cilantro roots, chop them up.

0:01:55.700,0:01:58.625
同学们香菜梗必须清洗干净否则会有泥沙
Cilantro roots must be carefully cleaned, otherwise there are remaining fine sands.

0:01:59.950,0:02:01.850
碗中加入食用盐0.5克
Add 0.5g of salt into the bowl

0:02:01.975,0:02:03.125
加入少许白糖
Add a little white sugar

0:02:03.575,0:02:04.750
加入陈醋1克
Add 1g of vinegar

0:02:05.825,0:02:07.500
加入生抽酱油5克
Add 5g of light soy sauce	

0:02:08.700,0:02:10.500
最后加入香辣红油50克
In the end, add 50g of spicy red oil, mix them together

0:02:14.075,0:02:16.375
搅拌均匀之后下一步开始处理腰花
Next deal with the kidneys

0:02:18.450,0:02:21.400
首先我们在锅中加入适量的清水开大火烧开
First, we add the right amount of water into the pot and boil it

0:02:23.650,0:02:25.150
中途加入适量的料酒

Add the right amount of Chinese cooking wine during the heating

0:02:32.000,0:02:34.325
然后将腌制好的猪腰倒出沥干啤酒
Then pour out the marinated kidneys and drain the beer

0:02:38.225,0:02:40.500
用清水清洗干净之后挤干水份
Rinse it with clean water and squeeze water out

0:02:45.075,0:02:47.725
挤干水份之后加入少许食用盐搅拌均匀（上底味）
After squeezing out the water, add a little salt and mix them well (to increase the base taste)

0:02:53.450,0:02:55.600
最后再加入1小把土豆淀粉拌匀
Finally add 1 small handful of potato starch and mix them well

0:02:55.975,0:02:58.475
这一步的目的是让腰花保持嫩度和爽脆
The purpose of this step is to keep the kidneys tender and crisp

0:03:00.450,0:03:02.950
拌匀之后将腰花下入烧开的水中
Then put the kidneys into the boiling water

0:03:05.600,0:03:08.375
然后待水再次开起来10秒钟即可倒出
Wait for the water to boil again, then pour kidneys out in 10 seconds

0:03:08.625,0:03:11.525
同学们切记猪腰不能煮太久否则不嫩
Remember that the kidneys can't be cooked too long or it won't taste tender

0:03:11.875,0:03:15.375
此刀法切的腰花10秒钟足以煮熟所以不必担心
10 seconds is long enough to cook well the kidneys that are cut by this knife skill, so don't worry about it.

0:03:30.925,0:03:32.950
沥干水份之后将腰花摆盘
After draining out the water, place the kidneys on the plate

0:03:45.800,0:03:48.100
最后再淋上调好的红油料（汁）即可上菜
Finally, drizzle the prepared red oil to serve

0:03:53.580,0:03:56.060
一道非常美味的红油腰花就制作完成
A very delicious dish "red oil kidneys" is finished

0:04:09.520,0:04:27.640
下面开始技术总结
第一，必须选择微白粉红的猪腰，凡是发黑有淤血的猪腰均为死猪或者病猪
第二，不会切腰花的同学可以直接切成小片
第三，猪腰下锅之前必须加入盐和干淀粉拌匀，这样成菜才足够鲜嫩爽脆
红油腰花 的技术总结完毕

The technical summary is as below,

First, you must choose the pig's kidneys that are slightly white and pink. 
Any black and bruised kidney is from the dead or sick pig.

Second, those who don't know how to cut kidneys into flower-like shape can directly cut into small pieces.

Third, Before cooking the kidneys, salt and dry starch must be added and mixed well, so that the dish is fresh and crisp.

That's the technical summary of "red oil kidneys".
