### ISSUE TITLE
[老饭骨] 手抓饭 - https://www.youtube.com/watch?v=ccHSTTEaqoM

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#952]
**视频链接**：https://www.youtube.com/watch?v=ccHSTTEaqoM

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•手抓饭】超热门新疆餐厅大厨教你做地道手抓羊肉饭，大气又正宗，下饭得很喽！

简介
小友们好，还记得教大家做新疆大盘鸡的师傅吗？
邓宏印师傅是北京丽丽古尔新疆餐厅的老板，也是三叔的徒弟。
今天他又来教咱们做新疆正宗的羊肉手抓饭了！
看了这期视频，不用去饭店也能吃到正宗地道的新疆手抓饭了。
所以今儿的视频大家伙可得看仔细喽。
冲洗羊肉的时候为什么要用热水？蒸饭的汤将将漫过米就好？
羊肉为什么不在之前改小块？最后要在饭里要加些什么？
新疆菜的特点就是原始、粗犷，但是它大气、好吃又下饭。
学会了今天这道手抓饭，又可以拿出去炫耀一波了。

# import intro 稿件请原样保留此行

字幕
老视频，原始字幕文件已遗失，需自行制作时间轴及对照中文
```

**Comment by immoonancient** [comment]
@lulufun 请前来认领

**Comment by lulufun** [comment]
认领

**Comment by lulufun** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•手抓饭】超热门新疆餐厅大厨教你做地道手抓羊肉饭，大气又正宗，下饭得很喽！
State Banquet Master Chef – Lamb Pilaf, Learn from the chef of the popular Xinjiang cuisine restaurant, authentic and tasty

简介
小友们好，还记得教大家做新疆大盘鸡的师傅吗？
邓宏印师傅是北京丽丽古尔新疆餐厅的老板，也是三叔的徒弟。
今天他又来教咱们做新疆正宗的羊肉手抓饭了！
看了这期视频，不用去饭店也能吃到正宗地道的新疆手抓饭了。
所以今儿的视频大家伙可得看仔细喽。
冲洗羊肉的时候为什么要用热水？蒸饭的汤将将漫过米就好？
羊肉为什么不在之前改小块？最后要在饭里要加些什么？
新疆菜的特点就是原始、粗犷，但是它大气、好吃又下饭。
学会了今天这道手抓饭，又可以拿出去炫耀一波了。

Introduction
Hello Friends, do you remember the chef who taught us Big Plate Chicken?
Deng Hongyin is the owner of Beijing Lili Gul Xinjiang Restaurant, and he is also the apprentice of San Shu.
Today, he will teach us how to make the authentic Xinjiang Lamb Pilaf!
After watching this video, you don’t need to visit restaurant to get the authentic Xinjiang Lamb Pilaf.
Therefore, you should pay attention while watching.
Why do we need warm water to rinse the lamb? Why do we add the water to just cover the rice?
Why don’t we cut the lamb to smaller pieces before cooking? What are the ingredients we need to add in the end?
Xinjiang cuisine is rustic, but it is tasty.
You can show off to your friends and family after learning this dish. 

# import intro 稿件请原样保留此行

字幕
Subtitle

0:00:00.000,0:00:02.260
您看饭的颜色了吗
Do you see the color of this rice?

0:00:02.260,0:00:05.740
有红的，有黄的，油亮油亮的
It have red and yellow in it. Shiny like oil.

0:00:06.020,0:00:07.880
手抓饭
Pilaf

0:00:09.495,0:00:12.255
做手抓饭一定要用羊后腿
We need to use lamb hind shank.

0:00:12.260,0:00:14.180
作为羊后腿来讲
For the lamb hind shank,

0:00:14.180,0:00:16.860
吃到嘴里头有一种筋道弹性
you can feel the elastic and springy.

0:00:16.860,0:00:20.180
然后会和米饭的这种弹性
The elasticities from the lamb and rice

0:00:20.180,0:00:22.440
能够特别好的混合
mix well together.

0:00:22.440,0:00:24.560
那么我们现在把肉做一个
Now, we will deal with meat

0:00:24.560,0:00:26.080
简单的一个处理
Simplely.

0:00:26.220,0:00:28.680
作为新疆菜来讲是这么一个概念
For the Xinjiang Cuisine, it has a concept.

0:00:28.680,0:00:30.280
新疆菜是比较原始的
It is a bit rustic,

0:00:30.280,0:00:31.660
粗旷而且好吃
Rustic, but tasty.

0:00:31.660,0:00:33.520
然后让人看着特别大气
It will make you feel they are very generous.

0:00:33.520,0:00:35.340
你知道为什么
Do you know the reason?

0:00:35.340,0:00:38.760
我刚从新疆回来没有多久
I just came back from Xinjiang.

0:00:38.920,0:00:41.440
小邓 你这一边说着一边做着
Xiao Deng, you can prepare (the food) while explaining.

0:00:42.100,0:00:43.620
你这块肉不错
The lamb you brought looks great.

0:00:43.620,0:00:46.540
大爷你看小邓有点随三叔是吧
Da Ye, do you think Xiao Deng is similar to San Shu? 

0:00:46.540,0:00:48.980
三叔的徒弟么 有点随三叔
He is the apprentice of San Shu, so it makes sense.

0:00:48.980,0:00:50.820
这处理之后我们开火
After cutting the lamb, let’s turn on the heat.

0:00:50.820,0:00:53.840
然后把肉给它飞下水
Then we parboil the lamb.

0:00:53.840,0:00:56.340
真正在新疆菜原始的做法
Actually, according to the original method,

0:00:56.340,0:00:58.140
这个是不用飞水的
we don’t need to parboil it.

0:00:58.140,0:01:00.820
但是如果说不飞水的话
However, without this step,

0:01:00.820,0:01:04.720
出来以后抓饭颜色会发暗
The color of pilaf will be dark.

0:01:04.780,0:01:07.560
有一些血沫会出来
Some blood will come out.

0:01:07.560,0:01:10.560
影响饭的颜色和质地
It will change the color and texture of the pilaf.

0:01:10.560,0:01:13.080
这是凉水下锅
We use cold water to parboil.

0:01:13.080,0:01:15.360
把它稍微的飞下水
We just need to parboil for a few minutes. 

0:01:15.360,0:01:16.980
这里边有几个原材料
There are some ingredients.

0:01:16.980,0:01:18.620
我给大家简单介绍一下
Let me explain them briefly.

0:01:18.620,0:01:20.860
第一个原材料大家可能都熟悉了
Our friends may familiar with the first ingredient.

0:01:20.860,0:01:23.540
葱头切丝
Let’s julienne the onions.

0:01:23.540,0:01:26.360
那么这葱头在新疆又叫什么
Do you know what they call “onion” in Xinjiang?

0:01:26.360,0:01:28.240
又叫皮牙子
They call it “Pi Ya Zi”.

0:01:28.240,0:01:31.480
这个皮牙子在新疆是唯一的
This “Pi Ya Zi” is the only ingredient in Xinjiang,

0:01:31.480,0:01:36.060
能够解腻去腥的这么一个原材料
Which could be used to balance fat and mask the unpleasant flavor and smell. 

0:01:36.060,0:01:37.440
作为皮牙子来讲
In terms of ‘Pi Ya Zi’,

0:01:37.440,0:01:40.720
白色的皮牙子略甜不辣
The white ones are a little sweet and not too spicy.

0:01:40.720,0:01:44.500
紫色的皮牙子是辣中带甜
The purple ones are spicy with a hint of sweetness.

0:01:44.500,0:01:47.100
紫色的味厚重一点
The flavor of the purple onions is more strong. 

0:01:47.100,0:01:49.700
所以我们采用了两种
Hence, we use two type here. 

0:01:49.700,0:01:51.140
那么除了皮牙子
Besides Pi Ya Zi, 

0:01:51.140,0:01:52.940
还有一个特别重要的原材料
We have another important ingredient. 

0:01:52.940,0:01:55.440
就是胡萝卜和黄萝卜
It is carrot and yellow carrot.

0:01:55.440,0:01:57.320
其实这点我知道
Actually, I know this.

0:01:57.480,0:02:00.480
甭看哪儿的胡萝卜都能吃
Even though you can use carrot from anyway,

0:02:00.480,0:02:03.640
但是新疆的胡萝卜跟哪的都不一样
The carrot from Xinjiang is distinctive from others.

0:02:03.640,0:02:06.360
它好吃 尤其是这黄色的
It is tasty, especially the yellow ones.

0:02:06.360,0:02:09.080
尤其是这黄色的 你尝尝
Especially the yellow one? Try it.

0:02:09.080,0:02:12.575
脆 胡萝卜那味儿足
Crunchy, it has the strong carrot flavor.

0:02:12.580,0:02:16.020
北京这胡萝卜它就叫胡萝卜 它没味道
Beijing’s carrot can be called carrot, but it lacks of the flavor.

0:02:16.020,0:02:18.840
羊肉的品质还是不错的
The quality of this lamb is good.

0:02:18.840,0:02:21.580
一点肥都没有 全是腱子肉
It didn’t have any fat. It is all tendon.

0:02:21.660,0:02:25.360
你大爷是最愿吃的 他不爱吃肥的
Da Ye will like this dish. He doesn’t like fat.

0:02:25.460,0:02:28.120
你看我有一个招你知道吗
I have an idea, do you want to know?

0:02:28.120,0:02:31.220
其实焯的时候按照你师父的加醋
Based on your master’s habit, you can add some vinegar while parboiling the lamb.

0:02:31.220,0:02:32.960
你先加上醋好嘞
You can add some vinegar first. Sure.

0:02:32.960,0:02:34.360
搁点酒可以
We can also add rice wine.

0:02:34.360,0:02:36.560
现在你还可以加一什么你知道么
Do you know what else you could add in here?

0:02:36.560,0:02:38.720
加两粒花椒加个大料
Two Sichuan peppercorn, and one star anise.

0:02:38.720,0:02:40.160
出来那味儿特别香
It will make the lamb smell very good.

0:02:40.160,0:02:42.780
我觉得二伯有点抢生意
I think Er Bai is taking over it now.

0:02:42.780,0:02:46.640
别让你师父知道 背着他师父说
Don’t let your master know. We keep the secret from his master.

0:02:46.740,0:02:49.620
二伯说什么你要分析着听啊
You should analyze Er Bai’s suggestion.

0:02:49.620,0:02:51.220
千万不要掉沟里头
Don’t let him lead you to a wrong direction.

0:02:51.220,0:02:52.800
有时候二伯容易给你刨一坑
Sometimes he may dig a hole for you (It means cause troubles).

0:02:52.800,0:02:54.080
你就按照你的思维
You can just follow your original plan.

0:02:54.080,0:02:55.540
该搁什么不搁什么
Whether we should or shouldn’t put something in.

0:02:55.620,0:02:58.220
没事 哎呦
No problem. Ai You. (expression)

0:02:58.220,0:02:59.620
搁点香菜
Add some cilantro.

0:02:59.620,0:03:02.720
二伯为什么要搁香菜您教我一下
Er bai, could you let me know why we need cilantro here?

0:03:02.720,0:03:06.000
你闻那味儿 不但去腥味还提鲜了
You can smell, it not only mask the unpleasant flavor, but also enhance the pleasant flavor of the lamb.

0:03:06.000,0:03:07.560
煮一会你看看
Let’s wait to see.

0:03:07.560,0:03:09.320
你闻这气味都发生变化了
Did you notice? The smell has changed.

0:03:09.320,0:03:10.760
你比如他们家还有大料
For example, if you has star anise,

0:03:10.760,0:03:13.700
搁一个就行千万别多
You can put one in, don’t put more than one.

0:03:13.820,0:03:15.360
借借味儿可香了
Add some flavor, it will smell good.

0:03:15.360,0:03:18.120
搁几粒花椒别搭理它就行了
Add some Sichuan peppercorn, we just need to leave it there.

0:03:18.120,0:03:19.480
煮它一会儿
Boiling it for a bit.

0:03:19.480,0:03:21.900
煮它是断生还是煮熟了
Should we cooked till medium rare or well done?

0:03:21.900,0:03:23.940
别煮完全熟就行
Don’t need to be fully cooked.

0:03:23.940,0:03:25.520
不煮完全熟
Don’t need to be fully cooked.

0:03:25.520,0:03:28.700
对你炒的时候符合你烹饪的要求
You just cook till it satisfy your standard. 

0:03:28.700,0:03:33.180
再煮一会儿 把它香料的味儿释放出来
We need to boil a bit more, so that the spice can release their flavor. 

0:03:33.180,0:03:37.200
新疆做不是这样做 
In Xinjiang, they didn’t cook in this way.

0:03:37.200,0:03:39.780
你又制造了一个新的配方
You are creating a new recipe.

0:03:39.780,0:03:41.720
好了 关火
OK, turn off the heat.

0:03:42.080,0:03:44.140
你看这香味就出来了
See, it already smells good.

0:03:44.140,0:03:46.540
原汤不要了 不要了 
Don’t we need the original soup? No, we don’t need it.

0:03:46.620,0:03:49.320
好把肉我们冲洗一下
Ok, let’s rinse the lamb.

0:03:49.320,0:03:51.300
这还是热水洗的
The water is warm.

0:03:51.300,0:03:52.200
（用凉水）一下激着了
(If we use cold water) it will make the lamb shrink,

0:03:52.200,0:03:53.560
它那肉容易变老
Which will make it tough.

0:03:53.560,0:03:54.420
你再闻一下这肉
You can smell the meat.

0:03:54.420,0:03:56.540
冲完了什么味都没有
After rinsing it, it doesn’t have any unpleasant smell.

0:03:56.640,0:03:58.960
看这肉 就是原始的肉的香味了
Only left with the good smell of the lamb.

0:03:58.960,0:04:01.940
二伯这么一处理 羊肉变成牛肉了
After Er Bai’s modification, the lamb can mimic beef.

0:04:03.280,0:04:04.860
不带这么刨坑的
Haha, be nice, you dig a hole for me.

0:04:05.160,0:04:07.300
二伯平时爱创新
Er Bai is very creative.

0:04:07.300,0:04:09.320
本来你想的是这样做
You had a plan when you started,

0:04:09.320,0:04:12.060
他会改变你原来的一些方法
He sometimes will change your way to do things.

0:04:12.060,0:04:17.180
虽然他对我进行抗议 但我该夸的还得夸
Even though he disagree with me, he deserve the compliments.

0:04:17.360,0:04:19.500
放点清油
Add some oil.

0:04:19.500,0:04:21.260
我们老饭骨的精神是什么呢
What’s the spirit of Lao Fan Gu?

0:04:21.260,0:04:23.360
创新不忘本 传承还不守旧
Be creative but keep the origin in heart, inherit the culture but not chained by it.

0:04:23.360,0:04:26.120
二伯他有时候看一些方法上吧
Sometimes, when Er Bai is looking at your methodology,

0:04:26.120,0:04:29.880
他略微的给你提个醒
He want to remind you,

0:04:29.880,0:04:31.980
或者说有一个好的建议
Or maybe provide a good suggestion.

0:04:31.980,0:04:36.580
但是我为了尊重你本人的意见
But I want to respect your opinion.

0:04:36.580,0:04:38.580
你就按照原始的做法
You can just follow your own way of cooking.

0:04:38.580,0:04:40.720
在当中会找出一些
You may find something in this process,

0:04:40.720,0:04:43.180
那些方面需要调整的
could be adjusted.

0:04:43.180,0:04:49.100
油炸 要把肉炸一下
Fry. We need to fry the lamb.

0:04:49.100,0:04:54.020
把洋葱到里边一起来进行煸炒
Then we add the onion inside, and stir fry.

0:04:55.200,0:04:58.680
那么炒到了咱们皮牙子变软了
We need to keep frying till the onion is soft,

0:04:58.680,0:05:00.280
然后味道出来了
and you can smell the aroma.

0:05:00.660,0:05:02.560
炒到这个味道变得极佳的时候
The flavor achieve the peak,

0:05:02.720,0:05:03.900
这洋葱好吃
The onion tastes good.

0:05:04.620,0:05:06.080
那我们现在加一点盐
Let’s add some salt.

0:05:06.080,0:05:09.320
小勺 满勺五克
1 tsp, around 5 g.

0:05:09.500,0:05:11.480
 加完盐之后
After the salt, 

0:05:11.480,0:05:13.880
我们开始放胡萝卜和黄萝卜
Let’s add some carrot and yellow carrot.

0:05:13.880,0:05:14.920
炒到什么时候
When do we need to stop frying?

0:05:14.920,0:05:19.300
炒到目前我们胡萝卜和黄萝卜蔫了
Until the carrot are soft.

0:05:19.640,0:05:21.460
炒软了
Fry until the carrot are soft.

0:05:24.580,0:05:30.440
倒水 倒清水 三分之一盆
Add some water, around 1/3 of a big bowl.

0:05:31.180,0:05:33.320
手抓饭么 我们最重要的
Since we are making pilaf, we now need the other important ingredient - 

0:05:33.320,0:05:35.980
另外一个米饭得下锅
Rice. Let’s put rice in the pot.

0:05:36.120,0:05:41.340
这个米就是我们东北的五常大米
The rice is Wu Chang Rice, from Northeastern China.

0:05:41.520,0:05:45.820
大爷说了 这米要淘的清亮才好
Da Ye told us, the rice should be washed until the water is clear.

0:05:45.820,0:05:47.520
做出来米饭才透亮
Then the cooked rice will look transparent and clear. 

0:05:47.520,0:05:50.380
我们做抓饭的时候把这米提前泡一下
We need to soak the rice before we start.

0:05:50.680,0:05:53.660
泡二十五分钟到四十分钟之间
Usually between 25 minutes and 40 minutes.

0:05:53.660,0:05:57.260
那么我们现在把这个倒到电饭锅里
Let’s put the rice in the rice cooker.

0:05:59.340,0:06:03.540
看着真香 这汤要倒进去
It looks great, the soup should also be in now.

0:06:03.540,0:06:06.520
这汤颜色非常好看 黄黄的
The color of this soup is pretty, is golden.

0:06:09.360,0:06:10.660
颜色非常好
The color is good.

0:06:10.740,0:06:15.220
我们放米饭是朝一个方向
When we put the rice in the rice cooker, we should follow one direction. 

0:06:15.220,0:06:17.700
然后把米一个一个放好
Put the rice in place.

0:06:17.780,0:06:21.540
要放匀了是吧 把这个米抹平
So the rice should be even? We should make the rice be flat.

0:06:21.540,0:06:24.100
放进去之后
After we put the rice,

0:06:24.100,0:06:29.460
将汤将将漫过这个 以米为平
Let’s pour the soup, close to the level of the rice.

0:06:29.460,0:06:31.740
稍微略微高一点 略微高一点就行了
The water is just barely higher than rice. Barely higher.

0:06:31.740,0:06:33.460
好嘞 现在盖盖子
Ok, now we close the lid.

0:06:33.580,0:06:34.960
好开始四十分钟
Ok, we then cook for 40 minutes.

0:06:35.120,0:06:39.340
看看啊 这水使得太对了
See, the water is about right.

0:06:39.540,0:06:40.540
走了
It is done.

0:06:42.320,0:06:49.200
看看啊新疆的羊肉手抓饭 漂亮了
See, the Xinjiang Lamb Pilaf. It is pretty.

0:06:49.200,0:06:52.400
咱们的饭还得加点小料
Our rice also need something supplements - 

0:06:52.560,0:06:55.240
葡萄干还有孜然粒
Raisin and cumin.

0:06:55.240,0:06:58.980
然后葡萄干咱们拿水稍微洗一下
Let’s rinse the raisin with water.

0:06:58.980,0:07:00.840
新疆的葡萄干好吃
Xinjiang’s raisin is tasty.

0:07:01.160,0:07:03.820
孜然经过处理了么 焙香了
Did you do anything with cumin? I toasted it lightly.

0:07:03.820,0:07:05.720
然后我们又给它擀到半碎
Then coarse grinder .

0:07:05.720,0:07:07.900
全碎的话会影响口感
If we grinder it too fine, the texture is not ideal. 

0:07:07.900,0:07:10.120
均匀的撒在上面
Evenly sprinkle on the top.

0:07:11.160,0:07:13.700
手抓饭好家伙
Lamb pilaf, very good.

0:07:13.980,0:07:17.760
要把它拌开
Then we need to mix it.

0:07:17.760,0:07:19.800
现在呢我们先干一件事
Now we need to do one thing.

0:07:19.900,0:07:23.900
把我们的刚才肉挑出来之后
For the lamb we picked it out previously, 

0:07:23.900,0:07:26.340
咱们上的时候放在边上
We will put it on the side of the plate when we serve the dish.

0:07:26.520,0:07:28.620
羊肉改改刀么 改改刀
Should we cut the lamb to smaller pieces? Yes, we need to do that.

0:07:28.620,0:07:30.860
这羊肉为什么之前
Why?

0:07:30.860,0:07:32.140
不把它改小一点
Why didn’t we cut it smaller previously?

0:07:32.140,0:07:33.920
咱们这抓饭是需要一个
Because we need to cook the pilaf

0:07:33.920,0:07:36.660
将近四十分钟的一个时间
For more than 40 minutes.

0:07:36.660,0:07:38.280
如果你把块改小了之后
If you cut it to smaller pieces,

0:07:38.280,0:07:41.820
时间长了以后羊肉的太烂了
It will be too soft and may break apart during this long cooking period.

0:07:41.820,0:07:43.200
口感有变化
It changes the texture. 

0:07:43.200,0:07:47.380
听到了吧 为什么羊肉不改小块
See? Why didn’t we cut the lamb to small piece.

0:07:47.440,0:07:52.620
然后现在你看我们把饭拌匀
Now we will mixed the rice and other ingredients.

0:07:52.620,0:07:53.700
我们再加上葡萄干
Put the raisin in.

0:07:53.700,0:07:56.140
新疆人吃饭真是讲究
People in Xinjiang put a lot of thoughts in this dish. 

0:07:56.200,0:07:58.540
您看饭的颜色了吗
Have you seen the color of this rice?

0:07:58.540,0:08:01.820
慢慢的有红的有黄的
Slowly, it has red and yellow color.

0:08:01.820,0:08:05.760
而且饭又经过了肉的汤汁的 
The rice has absorbed the meat juice.

0:08:05.760,0:08:08.340
这种浸泡 油亮油亮的
After soaking in it, the oil makes it looks so shiny.

0:08:08.540,0:08:11.400
盛一份我们的抓饭
Take a portion of the pilaf.

0:08:11.400,0:08:15.200
码一份让网友们看看好
Show our online friends how to plate.

0:08:15.440,0:08:17.940
这盘抓饭放在这儿
Let’ leave the pilaf here,

0:08:17.940,0:08:19.680
然后我们现在再做另外一个处理
And we will do one more thing - 

0:08:19.880,0:08:25.100
羊肉切成大丁好了
Cut the lamb to big chunks.

0:08:25.340,0:08:29.460
尝尝啊给个评价好不好吃
Try it. How is the taste?

0:08:29.460,0:08:31.360
太好吃了是吧
It is super delicious, isn’t it?

0:08:31.420,0:08:35.240
我你得拍我 你不拍我怎么吃
You should focus on me, how could I try without you shooting me?

0:08:35.500,0:08:37.300
你老拍地是吧
You like shooting the floor, aren’t you?

0:08:37.480,0:08:39.540
好吃吧 二伯真好吃
Is it great? Er bai, it is really good.

0:08:39.660,0:08:42.740
羊肉一点膻味都没有
The lamb don’t have the unpleasant smell and flavor.

0:08:42.740,0:08:44.840
而且整个感觉会特别好
It tastes really good as a whole.

0:08:44.840,0:08:48.480
饭的整个口味略带咸甜
The rice is salty and a bit sweet.

0:08:48.480,0:08:50.220
您觉得不够咸的话
If you think it needs more salt,

0:08:50.220,0:08:52.220
也可以再给点盐都行
You could add some (based on your own taste).

# import ending.srt 0:08:56.000稿件内请原样保留此行
