### ISSUE TITLE
[华农兄弟] 华农兄弟参观一下兄弟家的兰花基地各种兰花很漂亮哦 - https://youtu.be/Bg35GtTMdbQ

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#954]
https://youtu.be/Bg35GtTMdbQ
<p>&#35270;&#39057;&#21457;&#24067;&#20110; April 23, 2020 at 11:33AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/Bg35GtTMdbQ

#华农兄弟：参观一下兄弟家的兰花基地，各种兰花，很漂亮哦
#Huanong Brothers: We visit our buddy's orchid site. Here are many different types of orchids. So pretty!

0:00:00.000,0:00:02.900
# 大家好  今天來兄弟家這個蘭花基地看一下
Hi everyone! Today we come to our buddy's orchid cultivation site and have a look.

0:00:03.320,0:00:04.960
# 他家種了好這個蘭花
He has planted a lot of orchids.

0:00:05.340,0:00:06.160
# 那甚麼品種
Whichever species...

0:00:06.520,0:00:08.440
# 你看  都有  七八十種品種哦
Look! He has everything. There are up to eighty species.

0:00:08.980,0:00:09.880
# 進去看一下
Let's take a look inside.

0:00:15.040,0:00:15.900
# 你看  這個
Look! This one,

0:00:16.500,0:00:17.580
# 這個也很漂亮哦
this one is really pretty, isn't it?

0:00:17.720,0:00:18.360
# 它這個
It's like,

0:00:19.440,0:00:21.140
# 就這樣直接種下去就可以啦
it can be planted right away.

0:00:22.080,0:00:23.780
# 它這 這個要到冬天
It's ah, in winter,

0:00:24.420,0:00:26.960
# 冬天  冬天過年時候才會開花
winter, it won't blossom until winter, when the Chinese New Year comes.

0:00:30.560,0:00:32.040
# 好多工人都在這裡面
A lot of workers are over there inside.

0:00:34.180,0:00:34.740
# 上班
They're working.

0:00:37.400,0:00:38.840
# 沒 這個沒甚麼味道  但
No, it doesn't smell anything now. But,

0:00:38.860,0:00:40.400
# 等下它開了花之後就
later, when it blossoms,

0:00:40.780,0:00:41.840
# 那個味道就很濃啦
the fragrance will become really significant.

0:00:42.160,0:00:45.440
# 我聽那個  那個技術員說這個開的花  那個
The, you know, the technician over there told me that the flowers are, like,

0:00:45.940,0:00:46.660
# 很香的哦
the flowers smell really nice.

0:00:49.640,0:00:51.480
# 就跟我們山上的野蘭花差不多
It's almost the same as the wild orchids on our hill.

0:00:51.640,0:00:54.060
# 看上去就是  但是品種下一樣的
They look alike. But they're of different species.

0:00:56.040,0:00:57.380
# 帶動了好多就業
It brings a lot of job opportunities.

0:01:09.740,0:01:11.880
# 小石頭跟那個花去瞉
Small rocks and peanut shell,

0:01:12.640,0:01:13.380
# 拌在一起
mixed together,

0:01:13.900,0:01:14.640
# 就可以種啦
makes perfect soil for the orchids.

0:01:27.120,0:01:28.540
# 你看  這個大片都是
Look! The site covers the whole area here.

0:01:28.980,0:01:30.000
# 一片綠油油的
It's green everywhere.

0:01:40.960,0:01:42.960
# 你看 聽那個技術員說
Look! The technician told me,

0:01:43.680,0:01:44.400
# 他說這個
he told me that,

0:01:45.160,0:01:47.880
# 這個是它爸爸  這個  老一點的就叫它爸爸
This is its daddy. This one, the older one is called the daddy.

0:01:48.860,0:01:50.020
# 不是哦  它爺爺哦
Ah no, it's the grandpa.

0:01:50.100,0:01:51.460
# 搞錯啦  這是它爺爺
I mixed them up. This is the grandpa.

0:01:51.780,0:01:52.540
# 這是它老爸
And this is the daddy.

0:01:53.860,0:01:56.680
# 這種  這種剛長出來的就是它孫子
This one, the one that has just grown out, is the grandson.

0:01:56.920,0:01:58.100
# 剛好就是一定人
So the whole family is here.

0:02:00.400,0:02:01.680
# 剛好住在一個窩里面
They're living under the same roof.

0:02:03.900,0:02:05.760
# 等下開  開蘭花的時候就很香
It will, it will smell really nice later when the orchids blossom.

0:02:05.960,0:02:06.820
# 這個時候還下香
You can't smell anything at this moment.

0:02:12.320,0:02:13.700
# 種植起來好簡單哦
Planting it is a piece of cake.

0:02:13.800,0:02:14.780
# 就用小石頭
Simply take some small rocks,

0:02:15.260,0:02:16.860
# 跟那個頭瞉之類的
together with some bean shells or whatever,

0:02:17.220,0:02:18.260
# 放下去就可以啦
plant it in, that's it.

0:02:20.980,0:02:22.980
# 換個盆 換個竹筒的話也可以喲
Using another pot, I mean a bamboo tube, is also fine.

0:02:23.140,0:02:24.200
# 但竹同太小啦
But a bamboo tube might be too small.

0:02:24.560,0:02:25.780
# 要大竹子才行
You may need a big bamboo.

0:02:28.620,0:02:29.520
# 把它放回去
Let me put it back.

0:02:33.060,0:02:33.660
# 你看
Look!

0:02:34.240,0:02:35.640
# 這個  這個叫墨蘭
This is, this is called "ink orchid".

0:02:38.080,0:02:39.580
# 黑黑的  叫墨蘭
The colour is dark. So it's called "ink orchid".

0:02:42.820,0:02:46.680
# 它的這個  綠色綠到  綠到那種發黑的那種
It's in fact green, dark green, so dark that it's almost, sort of like, black.

0:02:47.960,0:02:48.560
# 很靚
Beautiful

0:02:49.300,0:02:51.040
# 還沒開花  開花了更靚
It has not yet blossomed. It will be even more beautiful when it blossoms.

0:02:52.420,0:02:54.180
# 你看  這個就漂亮啦  你看
Look! It's really pretty, isn't it?

0:02:54.420,0:02:55.460
# 開了一朵花出來
One flower has already blossomed.

0:02:55.680,0:02:57.800
# 它開了好多朵 都被凋謝啦  (註︰被凋謝....)
There should have been a lot of flowers. But most have already withered.

0:02:58.300,0:02:59.120
# 剩下這一朵
Only this one remains.

0:03:01.860,0:03:02.540
# 好靚哦
It's so beautiful!

0:03:03.260,0:03:03.980
# 它這個花
The flower is,

0:03:05.680,0:03:07.480
# 淡淡的  淡淡的紫色
is in light, light violet.

0:03:13.220,0:03:14.420
# 好多株哇  這裡
Here's not one, but many of them.

0:03:14.600,0:03:15.680
# 都是滿盆的
The pot is completely filled.

0:03:16.020,0:03:17.840
# 差不多它們肯定要分  分盆啦
I'm sure that they will need to be sep, separated very soon.

0:03:18.620,0:03:19.700
# 這些太滿啦
There are no more rooms at all.

0:03:21.400,0:03:22.740
# 你看  這也開了一朵花
Look! Here's another flower.

0:03:23.800,0:03:24.900
# 這花很不錯哦
This flower is really not bad.

0:03:34.080,0:03:34.700
# 很靚
Beautiful!

0:03:37.020,0:03:37.900
# 放在這裡先
Put it here first.

0:03:38.080,0:03:39.060
# 看一下其它的
And have a look at the others.

0:03:39.500,0:03:41.220
# 你看  這是自動噴水的哦
Look! An automatic watering system is installed here.

0:03:41.740,0:03:43.100
# 隨便噴一下就濕掉啦
The whole site get drenched in no time.

0:03:43.900,0:03:45.260
# 好均勻啊  噴的
It's really efficient, you know.

0:03:52.620,0:03:54.160
# 噴了5分鐘就足夠了哦
I bet five minutes would be all it needs, right?

0:03:54.920,0:03:56.100
# 一般要噴10分鐘
Normally it takes ten minutes.

0:03:56.120,0:03:56.880
# 要噴10分鐘
Ten minutes, I see.

0:03:56.880,0:03:58.480
# 嗯  噴了就是噴透來
Um! The whole site needs to be thoroughly watered.

0:04:03.880,0:04:05.500
# 你看  給它們洗了一個澡
Look! They've now taken a shower.

0:04:05.880,0:04:06.840
# 變漂亮了哦
And they become so pretty now.

0:04:08.640,0:04:09.520
# 噴了幾分鐘
It has taken a few minutes.

0:04:15.600,0:04:16.480
# 哇  你看 那個
Wa! Look! These are,

0:04:16.960,0:04:17.620
# 雜交
hybrid.

0:04:18.420,0:04:19.980
# 台北小姐
"Ms Taipei"

0:04:23.460,0:04:25.040
# 它還那麼小  還不會開花
They're still that small. They are not going to blossom now.

0:04:25.040,0:04:26.620
# 要長大啦 它就會開花啦
They will blossom once they grow up.

0:04:32.400,0:04:33.640
# 一棵變十棵
One plant will become ten.

0:04:34.900,0:04:35.700
# 可以喲
Not bad!

0:04:35.700,0:04:37.700
# (非對白)
Hybrid Orchid "Ms Taipei"
Cymbidium, Orchidaceae, originated in Taipei, China. Suitable for tropical/subtropical climate. Hybridized in Taiwan.

0:04:37.700,0:04:39.700
# (非對白)
 Flowers are big and plenty, with pink or red strips, subtle fragrance. Stems can reach above 70 cm. Up to a dozen of flowers on each stem.

0:04:39.720,0:04:40.440
# 你看  這個
Look! This one,

0:04:40.980,0:04:42.100
# 這個開花了哦  這個
this one has already blossomed, you know.

0:04:43.080,0:04:46.340
# 它  我聽我兄弟說  他現在把花全部剪掉啦
It's ah, my buddy told me that all flowers are to be cut away at the present moment,

0:04:46.340,0:04:47.180
# 不讓它開花
to make sure that no flowers are here now.

0:04:50.120,0:04:51.960
# 你看  這個  含花待放
Look! This bud, is almost ready to blossom.

0:04:53.420,0:04:54.280
# 現在肯定是
I'm sure that,

0:04:54.720,0:04:56.140
# 躲過來兄弟的剪刀
it has escaped from my buddy's scissors.

0:04:57.000,0:04:58.320
# 不然都會被剪掉的
It would have already been cut away otherwise.

0:04:59.480,0:05:00.680
# 哎呀  好香啊
Aya! It smells so good!

0:05:02.240,0:05:03.320
# 水困的香味一樣
It's like the fragrance of fruits.

0:05:06.100,0:05:07.120
# 這個好漂亮
It's really pretty.

0:05:09.480,0:05:11.280
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.

0:05:12.040,0:05:13.220
# 把這棵帶回去
I'll take this one home.

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/Bg35GtTMdbQ

#华农兄弟：参观一下兄弟家的兰花基地，各种兰花，很漂亮哦
#Huanong Brothers: We visit our buddy's orchid site. Here are many different types of orchids. So pretty!

0:00:00.000,0:00:02.900
# 大家好  今天來兄弟家這個蘭花基地看一下
Hi everyone! Today we come to our buddy's orchid cultivation site and have a look.

0:00:03.320,0:00:04.960
# 他家種了好這個蘭花
He has planted a lot of orchids.

0:00:05.340,0:00:06.160
# 那甚麼品種
Whichever species...

0:00:06.520,0:00:08.440
# 你看  都有  七八十種品種哦
Look! He has everything. There are up to eighty species.

0:00:08.980,0:00:09.880
# 進去看一下
Let's take a look inside.

0:00:15.040,0:00:15.900
# 你看  這個
Look! This one,

0:00:16.500,0:00:17.580
# 這個也很漂亮哦
this one is really pretty, isn't it?

0:00:17.720,0:00:18.360
# 它這個
It's like,

0:00:19.440,0:00:21.140
# 就這樣直接種下去就可以啦
it can be planted right away.

0:00:22.080,0:00:23.780
# 它這 這個要到冬天
It's ah, in winter,

0:00:24.420,0:00:26.960
# 冬天  冬天過年時候才會開花
winter, it won't blossom until winter, when the Chinese New Year comes.

0:00:30.560,0:00:32.040
# 好多工人都在這裡面
A lot of workers are over there inside.

0:00:34.180,0:00:34.740
# 上班
They're working.

0:00:37.400,0:00:38.840
# 沒 這個沒甚麼味道  但
No, it doesn't smell anything now. But,

0:00:38.860,0:00:40.400
# 等下它開了花之後就
later, when it blossoms,

0:00:40.780,0:00:41.840
# 那個味道就很濃啦
the fragrance will become really significant.

0:00:42.160,0:00:45.440
# 我聽那個  那個技術員說這個開的花  那個
The, you know, the technician over there told me that the flowers are, like,

0:00:45.940,0:00:46.660
# 很香的哦
the flowers smell really nice.

0:00:49.640,0:00:51.480
# 就跟我們山上的野蘭花差不多
It's almost the same as the wild orchids on our hill.

0:00:51.640,0:00:54.060
# 看上去就是  但是品種下一樣的
They look alike. But they're of different species.

0:00:56.040,0:00:57.380
# 帶動了好多就業
It brings a lot of job opportunities.

0:01:09.740,0:01:11.880
# 小石頭跟那個花去瞉
Small rocks and peanut shell,

0:01:12.640,0:01:13.380
# 拌在一起
mixed together,

0:01:13.900,0:01:14.640
# 就可以種啦
makes perfect soil for the orchids.

0:01:27.120,0:01:28.540
# 你看  這個大片都是
Look! The site covers the whole area here.

0:01:28.980,0:01:30.000
# 一片綠油油的
It's green everywhere.

0:01:40.960,0:01:42.960
# 你看 聽那個技術員說
Look! The technician told me,

0:01:43.680,0:01:44.400
# 他說這個
he told me that,

0:01:45.160,0:01:47.880
# 這個是它爸爸  這個  老一點的就叫它爸爸
This is its daddy. This one, the older one is called the daddy.

0:01:48.860,0:01:50.020
# 不是哦  它爺爺哦
Ah no, it's the grandpa.

0:01:50.100,0:01:51.460
# 搞錯啦  這是它爺爺
I mixed them up. This is the grandpa.

0:01:51.780,0:01:52.540
# 這是它老爸
And this is the daddy.

0:01:53.860,0:01:56.680
# 這種  這種剛長出來的就是它孫子
This one, the one that has just grown out, is the grandson.

0:01:56.920,0:01:58.100
# 剛好就是一定人
So the whole family is here.

0:02:00.400,0:02:01.680
# 剛好住在一個窩里面
They're living under the same roof.

0:02:03.900,0:02:05.760
# 等下開  開蘭花的時候就很香
It will, it will smell really nice later when the orchids blossom.

0:02:05.960,0:02:06.820
# 這個時候還下香
You can't smell anything at this moment.

0:02:12.320,0:02:13.700
# 種植起來好簡單哦
Planting it is a piece of cake.

0:02:13.800,0:02:14.780
# 就用小石頭
Simply take some small rocks,

0:02:15.260,0:02:16.860
# 跟那個頭瞉之類的
together with some bean shells or whatever,

0:02:17.220,0:02:18.260
# 放下去就可以啦
plant it in, that's it.

0:02:20.980,0:02:22.980
# 換個盆 換個竹筒的話也可以喲
Using another pot, I mean a bamboo tube, is also fine.

0:02:23.140,0:02:24.200
# 但竹同太小啦
But a bamboo tube might be too small.

0:02:24.560,0:02:25.780
# 要大竹子才行
You may need a big bamboo.

0:02:28.620,0:02:29.520
# 把它放回去
Let me put it back.

0:02:33.060,0:02:33.660
# 你看
Look!

0:02:34.240,0:02:35.640
# 這個  這個叫墨蘭
This is, this is called "ink orchid".

0:02:38.080,0:02:39.580
# 黑黑的  叫墨蘭
The colour is dark. So it's called "ink orchid".

0:02:42.820,0:02:46.680
# 它的這個  綠色綠到  綠到那種發黑的那種
It's in fact green, dark green, so dark that it's almost, sort of like, black.

0:02:47.960,0:02:48.560
# 很靚
Beautiful

0:02:49.300,0:02:51.040
# 還沒開花  開花了更靚
It has not yet blossomed. It will be even more beautiful when it blossoms.

0:02:52.420,0:02:54.180
# 你看  這個就漂亮啦  你看
Look! It's really pretty, isn't it?

0:02:54.420,0:02:55.460
# 開了一朵花出來
One flower has already blossomed.

0:02:55.680,0:02:57.800
# 它開了好多朵 都被凋謝啦  (註︰被凋謝....)
There should have been a lot of flowers. But most have already withered.

0:02:58.300,0:02:59.120
# 剩下這一朵
Only this one remains.

0:03:01.860,0:03:02.540
# 好靚哦
It's so beautiful!

0:03:03.260,0:03:03.980
# 它這個花
The flower is,

0:03:05.680,0:03:07.480
# 淡淡的  淡淡的紫色
is in light, light violet.

0:03:13.220,0:03:14.420
# 好多株哇  這裡
Here's not one, but many of them.

0:03:14.600,0:03:15.680
# 都是滿盆的
The pot is completely filled.

0:03:16.020,0:03:17.840
# 差不多它們肯定要分  分盆啦
I'm sure that they will need to be sep, separated very soon.

0:03:18.620,0:03:19.700
# 這些太滿啦
There are no more rooms at all.

0:03:21.400,0:03:22.740
# 你看  這也開了一朵花
Look! Here's another flower.

0:03:23.800,0:03:24.900
# 這花很不錯哦
This flower is really not bad.

0:03:34.080,0:03:34.700
# 很靚
Beautiful!

0:03:37.020,0:03:37.900
# 放在這裡先
Put it here first.

0:03:38.080,0:03:39.060
# 看一下其它的
And have a look at the others.

0:03:39.500,0:03:41.220
# 你看  這是自動噴水的哦
Look! An automatic watering system is installed here.

0:03:41.740,0:03:43.100
# 隨便噴一下就濕掉啦
The whole site get drenched in no time.

0:03:43.900,0:03:45.260
# 好均勻啊  噴的
It's really efficient, you know.

0:03:52.620,0:03:54.160
# 噴了5分鐘就足夠了哦
I bet five minutes would be all it needs, right?

0:03:54.920,0:03:56.100
# 一般要噴10分鐘
Normally it takes ten minutes.

0:03:56.120,0:03:56.880
# 要噴10分鐘
Ten minutes, I see.

0:03:56.880,0:03:58.480
# 嗯  噴了就是噴透來
Um! The whole site needs to be thoroughly watered.

0:04:03.880,0:04:05.500
# 你看  給它們洗了一個澡
Look! They've now taken a shower.

0:04:05.880,0:04:06.840
# 變漂亮了哦
And they become so pretty now.

0:04:08.640,0:04:09.520
# 噴了幾分鐘
It has taken a few minutes.

0:04:15.600,0:04:16.480
# 哇  你看 那個
Wa! Look! These are,

0:04:16.960,0:04:17.620
# 雜交
hybrid.

0:04:18.420,0:04:19.980
# 台北小姐
"Ms Taipei"

0:04:23.460,0:04:25.040
# 它還那麼小  還不會開花
They're still that small. They are not going to blossom now.

0:04:25.040,0:04:26.620
# 要長大啦 它就會開花啦
They will blossom once they grow up.

0:04:32.400,0:04:33.640
# 一棵變十棵
One plant will become ten.

0:04:34.900,0:04:35.700
# 可以喲
Not bad!

0:04:35.700,0:04:37.700
# (非對白)
Hybrid Orchid "Ms Taipei"
Cymbidium, Orchidaceae, originated in Taipei, China. Suitable for tropical/subtropical climate. Hybridized in Taiwan.

0:04:37.700,0:04:39.700
# (非對白)
 Flowers are big and plenty, with pink or red strips, subtle fragrance. Stems can reach above 70 cm. Up to a dozen of flowers on each stem.

0:04:39.720,0:04:40.440
# 你看  這個
Look! This one,

0:04:40.980,0:04:42.100
# 這個開花了哦  這個
this one has already blossomed, you know.

0:04:43.080,0:04:46.340
# 它  我聽我兄弟說  他現在把花全部剪掉啦
It's ah, my buddy told me that all flowers are to be cut away at the present moment,

0:04:46.340,0:04:47.180
# 不讓它開花
to make sure that no flowers are here now.

0:04:50.120,0:04:51.960
# 你看  這個  含花待放
Look! This bud, is almost ready to blossom.

0:04:53.420,0:04:54.280
# 現在肯定是
I'm sure that,

0:04:54.720,0:04:56.140
# 躲過來兄弟的剪刀
it has escaped from my buddy's scissors.

0:04:57.000,0:04:58.320
# 不然都會被剪掉的
It would have already been cut away otherwise.

0:04:59.480,0:05:00.680
# 哎呀  好香啊
Aya! It smells so good!

0:05:02.240,0:05:03.320
# 水困的香味一樣
It's like the fragrance of fruits.

0:05:06.100,0:05:07.120
# 這個好漂亮
It's really pretty.

0:05:09.480,0:05:11.280
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.

0:05:12.040,0:05:13.220
# 把這棵帶回去
I'll take this one home.
