### ISSUE TITLE
[华农兄弟] 蜜汁烤鸡 - https://youtu.be/4stfnmABdas

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#957]
https://youtu.be/4stfnmABdas
<p>&#35270;&#39057;&#21457;&#24067;&#20110; April 24, 2020 at 11:33AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/4stfnmABdas

#华农兄弟：兄弟送了点蜂蜜给我们，抓只鸡来做蜜汁烤鸡
#Huanong Brothers: My buddy has given use some honey. We catch a chicken and make a honey grilled chicken.

0:00:00.340,0:00:02.340
# 大家好  前兩天去了一下兄弟家
Hi everyone! I visited my buddy a couple of days ago.

0:00:02.680,0:00:04.380
# 你看  他家又有一點點蜂蜜了
Look! He has some honey again.

0:00:06.740,0:00:08.600
# 哇  好香啊  他這種蜂蜜
Wa! It smells so good, this kind of honey.

0:00:11.620,0:00:13.560
# 你看  前兩天  前兩天有點冷
Look! A couple of days ago, it was a bit cold a couple of days ago.

0:00:14.000,0:00:15.500
# 現在就結成這樣子了
So the honey has already crystallized.

0:00:15.900,0:00:16.440
# 稠稠的
It's rather thick.

0:00:20.080,0:00:20.580
# 嗯~
Um~

0:00:21.740,0:00:22.600
# 好香啊  這個
It smells really good!

0:00:24.620,0:00:25.120
# 現在都
It has already,

0:00:25.500,0:00:26.700
# 結晶啦  結成這樣子啦
crystallized. You can see the crystals.

0:00:30.720,0:00:31.460
# 可以哦  像是
Not bad. It's like,

0:00:31.840,0:00:32.800
# 像有沙的一樣
like, there's some sand.

0:00:35.280,0:00:37.120
# 現在是  已經是春蜜了  現在
It's now, it's already spring honey now.

0:00:38.420,0:00:40.420
# 不過老是下雨  產量不高
But the yield is not that high, as it's always raining.

0:00:41.220,0:00:41.920
# 只有一點點
There's just a tiny little bit.

0:00:48.840,0:00:49.740
# 去搞一隻雞來烤
Let me get a chicken and grill it.

0:00:50.660,0:00:51.700
# 蜜汁小雞
Honey grilled chicken.

0:00:53.660,0:00:54.440
# 先把它放好
Let me store it well first.

0:01:25.860,0:01:27.720
# 嘿嘿  抓到了
Hehe. I got it!

0:01:30.620,0:01:31.780
# 你看  那麼小的
Look! It's so tiny.

0:01:32.220,0:01:33.560
# 它頭上還有一坨毛的
There's a bunch of hair on it's head.

0:01:35.520,0:01:36.020
# 你看
Look!

0:01:39.420,0:01:40.420
# 到下面去烤
Let me take it down there and grill it.

0:01:43.540,0:01:45.320
# 應該兩斤多到三斤
I think it should be a kilogram to a kilo and a half.

0:01:47.900,0:01:48.920
# 已經把它抓下來了
So I've caught it and taken it here.

0:01:52.040,0:01:54.280
# 給它近  給它的近距離看一下
Let's give you a close, a close up so that you have can a look.

0:01:56.420,0:01:57.720
# 剛才它路得太快了
It was just running too fast.

0:02:01.480,0:02:01.980
# 要不要
You want it?

0:02:03.280,0:02:03.780
# 要不要
Do you?

0:02:05.560,0:02:06.500
# 你看這撮毛
Have a look at the hair here!

0:02:07.060,0:02:07.960
# 立起來的哦
It's standing.

0:02:08.760,0:02:09.680
# 好少呀  這隻
It's a small chicken.

0:02:10.440,0:02:11.160
# 兩斤多
A bit more than a kilogram

0:02:14.720,0:02:15.540
# 你看這個雞
Have a look at the chicken!

0:02:16.240,0:02:18.320
# 你看  頭髮上 它還梳了中分哦
Look! Its's hair is central-parting.

0:02:18.720,0:02:19.600
# 立起來這裡
And it's standing here.

0:02:23.040,0:02:24.080
# 用來烤
Let's grill it.

0:02:25.240,0:02:26.700
# 全身都沒甚麼肥肉的
There's hardly any fat all over the body.

0:02:35.300,0:02:35.940
# 它的爪子
Its foot.

0:02:38.700,0:02:40.260
# 好  我燒點水來
Alright! Let me boil some water.

0:02:46.240,0:02:46.800
# 你看
Look!

0:02:47.280,0:02:48.160
# 把它搞定啦
Everything is ready.

0:02:49.760,0:02:51.400
# 雖然個子小  但是
It's small, but

0:02:51.820,0:02:52.800
# 很多肉哦
it's really meaty.

0:02:53.500,0:02:55.060
# 還出來一個皇冠在這裡
It even has a crown here.

0:02:56.400,0:02:58.100
# 我把它  去一下內臟
Let me, clean up the guts.

0:03:04.680,0:03:06.160
# 把內臟去一下
Let me clean up the guts.

0:03:18.840,0:03:20.260
# 雞屁股  給你吃
The butt is yours.

0:03:32.460,0:03:35.180
# 先把這些  肉  割一下哦
Let me, here, skin, slice it a few times first.

0:03:35.820,0:03:36.900
# 這樣子更入味
Then it will be more flavourful.

0:03:38.460,0:03:39.960
# 誒呀  這把刀  那麼鈍
Eh? This knife is so blunt.

0:03:48.680,0:03:50.060
# 這個雞腿要割一下下  (註︰「一下下」甚麼意思？)
The chicken leg needs to be sliced a few times.

0:03:50.820,0:03:51.900
# 割幾下的話就
With a few slices,

0:03:53.280,0:03:54.140
# 鹽吶
the salt, and ah...

0:04:00.160,0:04:01.820
# 全部都把它弄進裡面去
Everything can get inside.

0:04:12.160,0:04:14.940
# 這個雞放到裡面去 別被那個小狗搞掉啦
Let me put the chicken inside. I'm not gonna let the dogs take it.

0:04:15.640,0:04:16.700
# 你看  加點生薑
Look! Put some ginger.

0:04:17.720,0:04:18.940
# 這鮮 鮮薑
It's fresh, fresh ginger.

0:04:19.720,0:04:21.140
# 能去掉它的那個
It can remove the,

0:04:22.040,0:04:22.940
# 身上的味道
the odour on its body.

0:04:23.860,0:04:24.680
# 就沒那麼腥
So that it won't smell too bloody.

0:04:28.180,0:04:29.060
# 再加點鹽
Then put some salt.

0:04:32.760,0:04:34.380
# 鹽  沒甚麼味道
The salt, doesn't smell anything.

0:04:38.740,0:04:40.020
# 鹽要搞多一點
We need a little bit more salt.

0:04:42.400,0:04:43.920
# 加了鹽 加點這個
With some salt, we can put some, you know,

0:04:44.960,0:04:45.500
# 醬油
some soy sauce.

0:04:47.360,0:04:48.580
# 沒有醬油了呀
No more soy sauce?

0:04:49.760,0:04:50.620
# 剛剛好夠
Just enough.

0:04:52.260,0:04:53.580
# 有點這個  料酒
Put some, well, cooking wine.

0:04:55.720,0:04:56.440
# 加點料酒
Put some cooking wine.

0:04:57.580,0:04:58.720
# 再搞點那個油
Put put some, some oil.

0:04:58.980,0:05:00.840
# 不搞點油的話  等下很那個的
Without some oil, it would be very, you know,

0:05:03.220,0:05:04.520
# 等下就很柴
it would be very dry and hard.

0:05:05.260,0:05:06.100
# 搞點油的話
With some oil,

0:05:08.320,0:05:09.180
# 比較香
it smells better.

0:05:13.780,0:05:15.140
# 這生薑掉出來
The ginger is falling out.

0:05:16.260,0:05:17.200
# 把這個生薑
Let me put the ginger,

0:05:17.900,0:05:19.300
# 都放到它肚子裡面去
all into its belly.

0:05:21.500,0:05:22.220
# 按一下摩
Give it a massage.

0:05:23.740,0:05:25.260
# 腳上也給它按一下摩
The feet need a massage too.

0:05:37.620,0:05:39.340
# 再給它  腌個半個小時
We leave it, and marinate it for half an hour.

0:05:39.880,0:05:40.860
# 等個半個小時
After half an hour,

0:05:41.500,0:05:42.020
# 就上
We can,

0:05:43.020,0:05:43.880
# 就搞一根
I'll get a,

0:05:44.140,0:05:44.980
# 我就搞一根那個
I'll get a, you know,

0:05:46.080,0:05:47.480
# 竹子來  把它穿上
a bamboo stick. And then pierce it,

0:05:47.680,0:05:48.300
# 穿進去
pierce it through the chicken,

0:05:49.180,0:05:50.840
# 好  先讓它待在這裡上
Alright! Let's leave it here first.

0:05:52.100,0:05:53.200
# 待在這裡先啊
Stay here, alright?

0:05:53.920,0:05:54.540
# 別動
Don't move around.

0:05:57.020,0:05:57.740
# 聽話
Be a good chicken.

0:06:00.720,0:06:03.380
# 我去搞根竹子  把那火生起來
Let me fetch a bamboo stick, and set the fire.

0:06:03.700,0:06:07.240
# 然後再把它串起來  就可以直接烤啦
Then we fix it onto the stick and it can be grilled right away.

0:06:46.420,0:06:47.560
# 削一下就可以了
Trim it here, and it's done.

0:06:54.400,0:06:55.180
# 可以
Alright!

0:07:06.380,0:07:08.160
# 走  吃肉啦  走
Go! Let's have some meat! Go!

0:07:21.520,0:07:22.560
# 先把它串起來
Fix it onto the stick first.

0:07:27.220,0:07:29.380
# 這樣的話  順便把這裡也串住
Yea, good. Then I can get here fixed as well.

0:07:33.460,0:07:35.420
# 額  生薑全部掉出來了
Eh? The gingers have all fallen out.

0:07:36.180,0:07:36.780
# 不要了
Never mind

0:07:37.420,0:07:38.980
# 我它們腳來這裡
Put the feet here, and then,

0:07:40.540,0:07:41.220
# 綁起來
tie them up.

0:07:41.420,0:07:41.980
# 你看
Look!

0:07:42.880,0:07:43.620
# 把它綁起來啦
I've tied it up now.

0:07:43.960,0:07:45.120
# 綁的紥紥實實的
And I've tied it tight and firm.

0:07:45.640,0:07:46.440
# 就直接這樣烤
Then it can be grilled right away.

0:07:49.060,0:07:49.980
# 拿上面去
Let me take it up there.

0:07:52.660,0:07:53.360
# 狗  (註︰沒有原字幕)
Doggies!

0:07:54.600,0:07:55.320
# 狗  (註︰沒有原字幕)
Doggies!

0:07:56.320,0:07:57.420
# 有好吃的哦
I have some very good food here!

0:07:58.460,0:07:59.380
# 要不要過來哦
Are you guys coming with me?

0:08:19.020,0:08:20.200
# 這個火升起來了
So the fire has been set.

0:08:20.860,0:08:21.420
# 可以烤了
We can start grilling now.

0:08:22.940,0:08:24.480
# 誒呀  剛剛好哦
Aya! The size is perfect.

0:08:38.860,0:08:40.160
# 好  這樣就可以
Alright! Everything is fine now.

0:09:00.040,0:09:01.980
# 給它起個名字  叫小胖熊
Let me give him a name. He's called Chubby Bear.

0:09:04.000,0:09:04.720
# 跟他那個胖
He's as fat as him.

0:09:10.380,0:09:11.060
# 要不要雞
Do you want some chicken?

0:09:13.700,0:09:14.280
# 不要
No, he doesn't.

0:09:32.540,0:09:33.800
# 搞個水車來
I should get a water wheel,

0:09:34.200,0:09:34.860
# 會動的
which can turn.

0:10:27.380,0:10:29.620
# 用這個葉子  做個刷子出來
Let me pick a leaf and make a brush.

0:10:40.720,0:10:42.860
# 用這個刷子刷點那個
With the brush, I can brush some, you know,

0:10:51.480,0:10:52.240
# 把它拿起來
Hold it high!

0:10:54.740,0:10:56.660
# 刷點這個油  才沒那麼幹
Brush some oil, so that it won't be too dry.

0:10:58.260,0:10:59.720
# 搞點油給它心上
Put some oil onto its heart.

0:11:00.680,0:11:01.800
# 心都看得到
I can see its heart.

0:11:04.620,0:11:05.700
# 這個雞瓜也放點油
I put some oil onto the feet as well.

0:11:46.800,0:11:48.340
# 轉了它才會
I turn and turn and turn, so that it,

0:11:49.340,0:11:49.840
# 才會
so that it,

0:11:50.320,0:11:51.180
# 才會暈了
so that it feels dizzy.

0:12:52.180,0:12:53.360
# 有點燒焦
It's a bit burnt.

0:13:02.860,0:13:04.360
# 狗熊在打架  (註︰沒有原字幕)
Chu, Chubby Bear is having a fight.

0:13:07.860,0:13:09.760
# 你看  現在很香了哦
Look! It smells really good now.

0:13:14.080,0:13:15.560
# 你看  再烤半個小時
Look! After half an hour,

0:13:16.300,0:13:17.460
# 不用烤半個小時
no, not half an hour,

0:13:18.160,0:13:19.380
# 烤多幾分鐘就可以
after a few minutes, I can,

0:13:19.580,0:13:20.760
# 把那個蜂蜜刷上去
I can start putting on the honey.

0:13:22.300,0:13:23.320
# 直接可以開吃啦
Then we can start our feast right away.

0:13:29.540,0:13:30.300
# 好靚
Beautiful!

0:13:31.080,0:13:32.280
# 差不多就要刷蜂蜜啦
It's almost time for the honey.

0:13:39.100,0:13:40.020
# 刷點蜂蜜
Put some honey.

0:13:40.720,0:13:41.660
# 你看這個蜂蜜
Have a look at this honey!

0:13:43.660,0:13:45.280
# 搞一點在它的  身上
I put some onto its, body.

0:13:49.080,0:13:50.080
# 會不會太多啦
Would it be too much?

0:13:51.360,0:13:52.840
# 沒事  甜一點好了
No worries. Let it be sweeter.

0:14:27.020,0:14:27.780
# 哎呀
Wa aya!

0:14:28.560,0:14:29.260
# 好香
It smells so good!

0:14:49.880,0:14:50.700
# 好啦好啦
Alright, alright!

0:14:56.380,0:14:57.380
# 好靚啊  你看
It's really beautiful! Look!

0:14:59.560,0:15:00.200
# 你看
Look!

0:15:02.240,0:15:02.900
# 這個
The,

0:15:03.260,0:15:04.520
# 這個 這個顔色
the, the colour...

0:15:07.360,0:15:09.020
# 好香 我吃一口  吃一口先
It smells great! I have a bite, have a bite first.

0:15:14.140,0:15:15.460
# 嗯~可以哦
Um~Not bad!

0:15:15.940,0:15:16.560
# 很香
It smells so good!

0:15:17.380,0:15:18.420
# 找個地方坐著來吃
Let me take a seat and enjoy it.

0:15:20.440,0:15:22.360
# 好  放在這裡先  先給它鬆綁
Alright. Put it here. Let me untie it first.

0:15:30.340,0:15:31.220
# 鬆綁
Untie it.

0:15:36.720,0:15:37.340
# 這個
The

0:15:37.700,0:15:38.300
# 這個腳
the foot,

0:15:39.960,0:15:40.680
# 燒糊啦
is burnt.

0:15:42.760,0:15:43.260
# 狗  (註︰沒有原字幕)
Doggies!

0:15:45.540,0:15:46.120
# 小狗
Doggies!

0:16:08.200,0:16:09.300
# 來 骨頭
C'mon! Bones!

0:16:09.760,0:16:10.320
# 都給狗
All for the dogs

0:16:16.860,0:16:17.360
# 好啦
Alright!

0:16:17.700,0:16:19.020
# 今天的視頻就到這裡啦
The video ends here.

0:16:22.200,0:16:23.940
# 嗯  很結實的肉
Um! The texture is really firm.
