### ISSUE TITLE
【美食作家王刚】辣子鸡 - https://youtu.be/ZjnOTA65DPo

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#958]
**视频链接**：https://youtu.be/ZjnOTA65DPo

视频时长7:16，预计发布时间为北京时间4月27日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“辣子鸡”的真家常做法，非宽油更家常！

简介
大家好，今天和大家分享一道“辣子鸡”，如果看过我之前辣子鸡教学视频的同学可能知道，鸡块需要下宽油炸熟，这样可以缩短烹饪的时间并且把水分锁在其中，但这样炸出来的鸡也有一定的问题，那就是鸡肉表面比较紧缩比较硬。因为四伯爷的牙口不好，所以今天就用另一种方法来制作，不用宽油，这样在保证鸡肉入味的同时还可以不至于表面太硬。希望大家喜欢本期视频，如果想看辣子鸡后厨专业教学的同学可以点击链接：https://www.youtube.com/watch?v=NqHI1CJU-Rg

字幕
0:00:00.553,0:00:01.223
哈喽大家好

0:00:01.495,0:00:05.438
最近我伯爷家的这只母鸡跟狗打架

0:00:05.975,0:00:07.043
狗把它咬伤了

0:00:07.425,0:00:10.370
今早晨放出来狗跟都它按（追）就把它咬伤了

0:00:10.622,0:00:14.425
咬伤了喂起还不是要瘦 弄来宰来吃了哎呀

0:00:15.828,0:00:18.685
所以说狗跟鸡打架的话 吃亏的是鸡

0:00:19.034,0:00:20.657
我们不可能把狗给宰了

0:00:22.220,0:00:23.056
做啥子 

0:00:23.623,0:00:26.819
还是拿这个嘛 拿这个干海椒弄来炒辣子鸡

0:00:26.908,0:00:27.327
要得啊

0:00:28.143,0:00:29.248
我们把它做成辣子鸡

0:00:31.110,0:00:33.469
我们做辣子鸡的话 这个鸡就稍微砍小一点

0:00:39.621,0:00:41.116
这个是狗咬过的 

0:00:41.214,0:00:42.513
这个脖子

0:00:43.653,0:00:44.529
就拿给它吃 

0:00:45.335,0:00:46.418
狗儿咯 来 

0:00:50.094,0:00:51.582
这鸡要跟它抢啊

0:00:57.252,0:00:58.347
它蹭到吃的就走了

0:01:02.080,0:01:07.346
我们这个辣子鸡要提前放7、8成的盐把它腌一下

0:01:08.013,0:01:09.039
要让它提前入味

0:01:09.238,0:01:14.206
如果我们鸡肉已经炒好了再放盐就没有意义了

0:01:14.325,0:01:15.569
盐是进不去的那个时候

0:01:17.650,0:01:21.153
好了我们这个肉腌好了 给它放十分钟

0:01:21.453,0:01:22.492
现在准备一下配料

0:01:24.068,0:01:27.464
这个配料特别简单 就只要一坨老姜几颗大蒜

0:01:27.880,0:01:30.753
然后再剪一点这个干辣椒 这个灯笼椒

0:01:30.753,0:01:33.549
我们还是用上次的灯笼椒 我伯爷不能吃太辣

0:01:34.587,0:01:39.266
然后这个姜的话切成姜末 还有蒜也切成蒜末

0:01:39.792,0:01:41.656
切小一点更入味

0:01:49.260,0:01:51.105
我们干辣椒用这个剪一碗就行了

0:01:51.777,0:01:55.284
我们那个鸡也差不多一碗 干辣椒也用一碗

0:01:55.638,0:01:58.485
然后在体积上面的话1:1就可以了

0:02:00.134,0:02:01.551
1:1多不多了点哦  

0:02:01.710,0:02:02.138
不多 

0:02:02.944,0:02:05.534
我们在外面（吃）的话辣子鸡是在辣椒里面找鸡（肉）

0:02:06.890,0:02:15.455
外面的话它的辣椒量更多 纯粹就是把干辣椒盖过这个鸡肉

0:02:16.300,0:02:18.475
好 我们这个干辣椒就剪得差不多了 

0:02:19.075,0:02:21.875
满满的一大碗 等一下再筛一下这个籽 

0:02:22.000,0:02:28.175
籽要去掉一些 要不然待会儿吃的话满口都是籽 这样就不好了

0:02:29.375,0:02:33.225
给它稍微漏（筛）几哈 这个米米太多了

0:02:34.150,0:02:36.225
太多了炒出来糊糊呀呀的

0:02:37.100,0:02:39.175
这个籽就不要了 倒了

0:02:40.650,0:02:42.425
这哈子又在上面筛

0:02:43.700,0:02:44.450
看 都还多得很

0:02:44.725,0:02:46.500
但是又不能说一点籽都不要

0:02:46.525,0:02:49.550
没有籽的话又不香了 只是说不能太多

0:02:51.625,0:02:53.175
这样筛两遍就可以了

0:02:54.975,0:02:57.500
好 这个籽也不要了 就行了

0:02:57.700,0:02:59.725
最后我们来加一点花椒

0:03:01.400,0:03:03.900
辣子鸡花椒也是一大灵魂之一

0:03:04.925,0:03:06.984
3、4斤的肉噶 

0:03:07.600,0:03:08.150
抓两把

0:03:09.075,0:03:11.075
好 可以了

0:03:14.900,0:03:18.124
锅中加入适量的菜籽油

0:03:30.400,0:03:32.928
加入准备好的花椒和鸡肉

0:03:47.106,0:03:48.490
四伯爷 这会等它慢慢炒

0:03:48.834,0:03:51.295
这个水没炒干的话这个肉就不香

0:04:01.500,0:04:03.600
锅中加入干辣椒

0:04:06.595,0:04:08.369
把这个干辣椒拿下去跟它一起炒

0:04:11.286,0:04:12.193
四伯爷你来炒哈儿嘛

0:04:13.348,0:04:14.110
试哈嘛 

0:04:15.466,0:04:17.965
我炒都炒不来

0:04:18.439,0:04:20.148
不翻 就这样炒哈就是

0:04:26.196,0:04:27.242
还是你来 

0:04:28.490,0:04:28.806
我不行

0:04:31.119,0:04:32.020
翻不转是不哦 

0:04:39.600,0:04:41.423
锅中加入准备好的姜蒜末

0:04:52.589,0:04:53.799
（味道）辣不辣

0:05:00.571,0:05:02.372
锅中加入切好的火锅底料

0:05:13.358,0:05:14.366
撒点芝麻

0:05:21.216,0:05:22.175
然后关火

0:05:28.221,0:05:31.323
最后加点鸡精

0:05:38.030,0:05:38.300
好

0:05:39.795,0:05:41.430
把它和转（匀）了之后就可以起锅了

0:05:43.567,0:05:44.180
好 出锅

0:05:48.592,0:05:49.112
好大一盆哦

0:05:51.110,0:05:52.094
害怕有几斤哦

0:05:57.584,0:05:58.643
尝哈看 伯爷伯娘

0:05:58.894,0:05:59.981
好 试哈看嘛

0:06:01.272,0:06:03.576
这个肉这样炒起不得老也不得干

0:06:04.802,0:06:07.505
而且它还香也咬得动

0:06:08.434,0:06:08.954
你看这种

0:06:10.041,0:06:12.224
四伯爷这种小的是肉大的是骨头

0:06:13.051,0:06:15.373
你看肉跟骨头都炒脱骨了

0:06:18.179,0:06:18.653
香不香

0:06:19.089,0:06:20.613
香安 是有点好吃这个东西

0:06:21.830,0:06:23.019
下酒哦 安逸噶

0:06:23.232,0:06:24.505
下啤酒安逸安

0:06:26.223,0:06:28.444
今天我们这个辣子鸡没有用宽油来炸

0:06:29.010,0:06:30.915
就是考虑到我伯爷 

0:06:31.202,0:06:35.559
如果宽油炸的话这个鸡肉收缩的比较厉害 就咬不动

0:06:36.943,0:06:43.288
我们这个既香又辣 然后肉又不硬特别入味

0:06:45.991,0:06:46.344
好吃

0:06:47.134,0:06:48.518
好吃 跟茄猫儿（青蛙）肉样

0:06:53.265,0:06:55.699
好了 大家家里有土鸡的可以试一下

0:06:55.847,0:06:57.877
没有土鸡的可以到市场去买 

0:06:59.163,0:06:59.842
买肉鸡

0:07:00.845,0:07:03.251
哎呀 一般好多农村哪个这样整来干哦 

0:07:04.960,0:07:05.657
成本好高哦

0:07:06.493,0:07:06.846
嗯

0:07:10.887,0:07:12.317
好 本期视频就到这里

0:07:13.153,0:07:14.797
我去给你开罐啤酒 四伯爷


```

**Comment by Yingzhang1122** [comment]
# https://youtu.be/ZjnOTA65DPo
#标题（翻译主要意思即可，不要超过 100 个字符）
#厨师长分享：“辣子鸡”的真家常做法，非宽油更家常！
Master chef shares with you: Home-made way of cooking 'La zi ji' (Chicken with chili), no need for 'kuan you'!

简介
大家好，今天和大家分享一道“辣子鸡”，如果看过我之前辣子鸡教学视频的同学可能知道，鸡块需要下宽油炸熟，这样可以缩短烹饪的时间并且把水分锁在其中，但这样炸出来的鸡也有一定的问题，那就是鸡肉表面比较紧缩比较硬。因为四伯爷的牙口不好，所以今天就用另一种方法来制作，不用宽油，这样在保证鸡肉入味的同时还可以不至于表面太硬。希望大家喜欢本期视频，如果想看辣子鸡后厨专业教学的同学可以点击链接：https://www.youtube.com/watch?v=NqHI1CJU-Rg

Hello everyone, today I'm sharing with you how to cook 'La zi ji' (Chicken with chili). If you have watched my previous video about this dish, you should have known that we need to fry the chicken dices in 'kuan you' to shorten the cooking time as well as sealing the moisture inside. However, fried chicken dices are usually dry and relatively hard. Since my uncle suffers from his teeth problems, I'm gonna cook this dish in a new way today, such that the chicken won't be too hard while keeping the flavor penetrated well. Hope you like this video! If you want to watch the professional way of cooking this dish, please click this link: https://www.youtube.com/watch?v=NqHI1CJU-Rg

#字幕
0:00:00.553,0:00:01.223
#哈喽大家好
Hello everyone

0:00:01.495,0:00:05.438
#最近我伯爷家的这只母鸡跟狗打架
Recently my uncle's hen had a fight with his dog

0:00:05.975,0:00:07.043
#狗把它咬伤了
The dog hurt it bad

0:00:07.425,0:00:10.370
#今早晨放出来狗跟都它按（追）就把它咬伤了
This morning the dog chase it and bit it hard

0:00:10.622,0:00:14.425
#咬伤了喂起还不是要瘦 弄来宰来吃了哎呀
Now that it's hurt. Even if I keep feeding it, it'll become thinner. Let's just butcher and eat it. 

0:00:15.828,0:00:18.685
#所以说狗跟鸡打架的话 吃亏的是鸡
So if a dog fights with a chicken, the chicken is always inferior

0:00:19.034,0:00:20.657
#我们不可能把狗给宰了
We can't butcher the dog anyway

0:00:22.220,0:00:23.056
#做啥子
What do we cook?

0:00:23.623,0:00:26.819
#还是拿这个嘛 拿这个干海椒弄来炒辣子鸡
What about this... Cook 'La zi ji' with these dry chili peppers

0:00:26.908,0:00:27.327
#要得啊
OK

0:00:28.143,0:00:29.248
#我们把它做成辣子鸡
Let's cook it into 'La zi ji' (Chicken with chili)

0:00:31.110,0:00:33.469
#我们做辣子鸡的话 这个鸡就稍微砍小一点
Generally in this dish, the chicken should be chopped into small dices

0:00:39.621,0:00:41.116
#这个是狗咬过的 
This was bitten by the dog

0:00:41.214,0:00:42.513
#这个脖子
The neck

0:00:43.653,0:00:44.529
#就拿给它吃 
Let's give it to the dog then

0:00:45.335,0:00:46.418
#狗儿咯 来 
Come on, doggy!

0:00:50.094,0:00:51.582
#这鸡要跟它抢啊
The rooster is competing with it

0:00:57.252,0:00:58.347
#它蹭到吃的就走了
The rooster goes away once it gets some food

0:01:02.080,0:01:07.346
#我们这个辣子鸡要提前放7、8成的盐把它腌一下
In this dish, we need to add 70% to 80% salt in advance to marinate the chicken

0:01:08.013,0:01:09.039
#要让它提前入味
To let the flavor penetrate inside before cooking

0:01:09.238,0:01:14.206
#如果我们鸡肉已经炒好了再放盐就没有意义了
It'll make no sense to add salt after the chicken is fully cooked

0:01:14.325,0:01:15.569
#盐是进不去的那个时候
Salt won't get inside then

0:01:17.650,0:01:21.153
#好了我们这个肉腌好了 给它放十分钟
Ok. The chicken is ready and let's marinate it for 10 minutes

0:01:21.453,0:01:22.492
#现在准备一下配料
Now prepare the side ingredients

0:01:24.068,0:01:27.464
#这个配料特别简单 就只要一坨老姜几颗大蒜
It's very simple. Just a piece of old ginger, some garlic

0:01:27.880,0:01:30.753
#然后再剪一点这个干辣椒 这个灯笼椒
Then scissor some dry chili peppers. The "Denglongjiao" (aka lantern chilis)

0:01:30.753,0:01:33.549
#我们还是用上次的灯笼椒 我伯爷不能吃太辣
We are still using the "Denglongjiao" last time. My uncle can't eat too spicy food

0:01:34.587,0:01:39.266
#然后这个姜的话切成姜末 还有蒜也切成蒜末
Here we mince the ginger and garlic

0:01:39.792,0:01:41.656
#切小一点更入味
Small pieces are better for flavor penetration

0:01:49.260,0:01:51.105
#我们干辣椒用这个剪一碗就行了
One bowl (like this) of dry chili peppers would be enough

0:01:51.777,0:01:55.284
#我们那个鸡也差不多一碗 干辣椒也用一碗
The chicken also fills a bowl. The same amount for chili peppers

0:01:55.638,0:01:58.485
#然后在体积上面的话1:1就可以了
The ratio of chicken to chili is 1:1 in terms of volume

0:02:00.134,0:02:01.551
#1:1多不多了点哦  
Is 1:1 too much?   #这里不确定是谁比谁多...

0:02:01.710,0:02:02.138
#不多 
Nope

0:02:02.944,0:02:05.534
#我们在外面（吃）的话辣子鸡是在辣椒里面找鸡（肉）
When ordering this dish in restaurants, we need to look for chicken in chili pepper

0:02:06.890,0:02:15.455
#外面的话它的辣椒量更多 纯粹就是把干辣椒盖过这个鸡肉
They use much more chili pepper. It's almost like covering the chicken with chili.

0:02:16.300,0:02:18.475
#好 我们这个干辣椒就剪得差不多了 
Ok. That's all for the chili.

0:02:19.075,0:02:21.875
#满满的一大碗 等一下再筛一下这个籽 
A full bowl of chili pepper. I'll need to remove the seeds later

0:02:22.000,0:02:28.175
#籽要去掉一些 要不然待会儿吃的话满口都是籽 这样就不好了
We should remove some seeds. Otherwise, we'll eat too many seeds, which will spoil this dish

0:02:29.375,0:02:33.225
#给它稍微漏（筛）几哈 这个米米太多了
Let's sieve it. There're too many seeds

0:02:34.150,0:02:36.225
#太多了炒出来糊糊呀呀的
The dish will be spoiled with too many seeds  #不是很理解糊糊呀呀是啥哈哈哈

0:02:37.100,0:02:39.175
#这个籽就不要了 倒了
We don't need these seeds. Let's throw them away

0:02:40.650,0:02:42.425
#这哈子又在上面筛
Now sieve the chili peppers up here

0:02:43.700,0:02:44.450
#看 都还多得很
Look. We've still got a lot

0:02:44.725,0:02:46.500
#但是又不能说一点籽都不要
However, we shouldn't throw away all seeds

0:02:46.525,0:02:49.550
#没有籽的话又不香了 只是说不能太多
We'll lose the aroma without seeds. Just not too many

0:02:51.625,0:02:53.175
#这样筛两遍就可以了
Sieve it twice like this

0:02:54.975,0:02:57.500
#好 这个籽也不要了 就行了
Ok. Throw away the seeds here as well and it's done

0:02:57.700,0:02:59.725
#最后我们来加一点花椒
Finally let's add some Sichuan peppercorns

0:03:01.400,0:03:03.900
#辣子鸡花椒也是一大灵魂之一
Sichuan peppercorns are also one of the souls of this dish

0:03:04.925,0:03:06.984
#3、4斤的肉噶 
We have... 3 to 4 Jin  (~1.5 - 2 kg) of chicken, huh?

0:03:07.600,0:03:08.150
#抓两把
Two handfuls of Sichuan peppercorns

0:03:09.075,0:03:11.075
#好 可以了
Ok. That's enough

0:03:14.900,0:03:18.124
#锅中加入适量的菜籽油
Add a moderate amount of rapeseed oil into the wok

0:03:30.400,0:03:32.928
#加入准备好的花椒和鸡肉
Add the Sichuan peppercorns and the chicken

0:03:47.106,0:03:48.490
#四伯爷 这会等它慢慢炒
Uncle, now let's stir-fry it slowly

0:03:48.834,0:03:51.295
#这个水没炒干的话这个肉就不香
If the moisture is not dried out, the meat won't taste good

0:04:01.500,0:04:03.600
#锅中加入干辣椒
Add the dry chili pepper into the wok

0:04:06.595,0:04:08.369
#把这个干辣椒拿下去跟它一起炒
Now we stir-fry the chicken with the chili pepper

0:04:11.286,0:04:12.193
#四伯爷你来炒哈儿嘛
Uncle, would you have a try?

0:04:13.348,0:04:14.110
#试哈嘛 
Just have a try

0:04:15.466,0:04:17.965
#我炒都炒不来
I don't think I can do it

0:04:18.439,0:04:20.148
#不翻 就这样炒哈就是
You don't need to flip the food. Just stir it like this

0:04:26.196,0:04:27.242
#还是你来 
You'll do it better

0:04:28.490,0:04:28.806
#我不行
I can't

0:04:31.119,0:04:32.020
#翻不转是不哦 
Can't flip the food, right?

0:04:39.600,0:04:41.423
#锅中加入准备好的姜蒜末
Add the minced ginger and garlic into the wok

0:04:52.589,0:04:53.799
#（味道）辣不辣
Is it too spicy?

0:05:00.571,0:05:02.372
#锅中加入切好的火锅底料
Add hot pot ingredient (cut into pieces in advance) into the wok

0:05:13.358,0:05:14.366
#撒点芝麻
Sprinkle some sesame

0:05:21.216,0:05:22.175
#然后关火
Turn off the heat

0:05:28.221,0:05:31.323
#最后加点鸡精
Finally, add some chicken bouillon

0:05:38.030,0:05:38.300
#好
Okay

0:05:39.795,0:05:41.430
#把它和转（匀）了之后就可以起锅了
Stir the food uniformly and it's ready to serve!

0:05:43.567,0:05:44.180
#好 出锅
Ok. It's ready!

0:05:48.592,0:05:49.112
#好大一盆哦
That's a large bowl of chicken

0:05:51.110,0:05:52.094
#害怕有几斤哦
Might be several 'Jin' in weight

0:05:57.584,0:05:58.643
#尝哈看 伯爷伯娘
Please take a bite, uncle and aunt

0:05:58.894,0:05:59.981
#好 试哈看嘛
Sure. Let me try it

0:06:01.272,0:06:03.576
#这个肉这样炒起不得老也不得干
The meat is neither too chewy nor too dry

0:06:04.802,0:06:07.505
#而且它还香也咬得动
Tastes good and easy to chew

0:06:08.434,0:06:08.954
#你看这种
Look

0:06:10.041,0:06:12.224
#四伯爷这种小的是肉大的是骨头
Uncle, the small pieces like this are meat. Larger pieces are bones

0:06:13.051,0:06:15.373
#你看肉跟骨头都炒脱骨了
You've seperated the meat from the bones during cooking

0:06:18.179,0:06:18.653
#香不香
Does it taste good?

0:06:19.089,0:06:20.613
#香安 是有点好吃这个东西
Sure. Delicious indeed

0:06:21.830,0:06:23.019
#下酒哦 安逸噶
Best with beer. That'll be nice

0:06:23.232,0:06:24.505
#下啤酒安逸安
Nice with beer

0:06:26.223,0:06:28.444
#今天我们这个辣子鸡没有用宽油来炸
Today we didn't use 'kuan you' to fry the chicken in this dish

0:06:29.010,0:06:30.915
#就是考虑到我伯爷 
Because my uncle...

0:06:31.202,0:06:35.559
#如果宽油炸的话这个鸡肉收缩的比较厉害 就咬不动
If the chicken is fried, the meat will shrink hard. He won't be able to chew it

0:06:36.943,0:06:43.288
#我们这个既香又辣 然后肉又不硬特别入味
In this way, it tastes delicious and spicy. The meat is tender with flavors fully penetrated

0:06:45.991,0:06:46.344
#好吃
Yummy!

0:06:47.134,0:06:48.518
#好吃 跟茄猫儿（青蛙）肉样
Yummy. Tastes like frog

0:06:53.265,0:06:55.699
#好了 大家家里有土鸡的可以试一下
Okay. If you have free-range chicken, just have a try

0:06:55.847,0:06:57.877
#没有土鸡的可以到市场去买 
Otherwise, you can buy it in the markets

0:06:59.163,0:06:59.842
#买肉鸡
Broiler chicken is also fine

0:07:00.845,0:07:03.251
#哎呀 一般好多农村哪个这样整来干哦 
Hmm. Few people in the countryside would do this

0:07:04.960,0:07:05.657
#成本好高哦
It's so expensive

0:07:06.493,0:07:06.846
#嗯
Yep

0:07:10.887,0:07:12.317
#好 本期视频就到这里
Ok. That's the end of this video

0:07:13.153,0:07:14.797
#我去给你开罐啤酒 四伯爷
Let me get you a can of beer, uncle
