### ISSUE TITLE
【美食作家王刚】 介绍后厨工作室 - https://youtu.be/SX9B7i8yG8g

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#966]
**视频链接**：https://youtu.be/SX9B7i8yG8g

视频时长3:13，预计发布时间为北京时间4月29日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
揭秘！给大家介绍我的后厨工作室，来算算一共投了多少钱

简介
大家好，其实自从我拍视频以来一直有不少朋友在问我的拍摄环境是什么样的，这次就来拍个视频来介绍一下。最初拍视频的时候还在做厨师长，每天完成本职工作完再拍视频剪视频都到很晚，后来决定回到老家做一个工作室来全职给大家产出内容，其中也经历了很多迷茫和困苦，但都一点点的走过来了，就像我当初就想把厨艺学好一样，我想把内容做好，让大家想学一道菜就能找到最好最棒的方法！我一直以来很少涉及商业合作，但我觉得在不忘初心的条件下可以适当有些尝试，在这里附上一个邮箱地址 wanggangbusiness@gmail.com 如果有什么合作意向可以发邮件来联系（仅限于商业合作），感谢大家一直以来的支持与喜爱！

字幕
0:00:00.318,0:00:01.722
哈喽大家好 我是王刚

0:00:01.843,0:00:04.081
最近收到后台一些私信

0:00:04.103,0:00:11.870
就是其他作者问我们整个工作室到拍摄要花多少钱

0:00:12.035,0:00:13.428
然后我就算了一笔账

0:00:13.757,0:00:15.359
从我们回来的时候 

0:00:15.611,0:00:21.151
从2017年到现在我们这个房租押金是5千然后房租是1万5一年

0:00:21.426,0:00:24.227
交了4万5千块钱的房租加押金

0:00:24.245,0:00:25.913
反正这一块就5万块钱

0:00:26.549,0:00:32.331
然后就是我回来的时候这个门面它是一个比较长的一个门面

0:00:32.484,0:00:36.752
宽的话是3米5 长的话大概是10米多一点 

0:00:36.895,0:00:38.584
总共是40多个平方

0:00:39.330,0:00:46.275
刚开始我们接手的时候这个门面是毛坯（房） 什么都没有 

0:00:46.396,0:00:49.083
然后我们回来搞了一下装修 

0:00:49.149,0:00:53.274
就吊了顶 做了墙面 然后还有这个地板

0:00:53.614,0:00:56.083
这一块装修大概总共花了2万块钱左右

0:00:56.324,0:00:57.992
大部分的装修做完了之后呢

0:00:58.189,0:01:03.752
就要做排水 排烟道 水电气 这一块也比较贵

0:01:03.894,0:01:08.129
因为我们这个门面它以前是做的库房 没有排水

0:01:08.272,0:01:11.716
我们挖这个排水管从这边一直挖到街上去

0:01:12.002,0:01:14.525
挖得距离有点远 所以有点贵

0:01:14.799,0:01:16.741
总共大概2万块钱左右

0:01:16.884,0:01:23.795
我们这块水电气装修吊顶地板做完了之后开始买设备

0:01:23.938,0:01:29.939
设备的话就包括我后面上面这个烟罩 这个炉具 

0:01:30.060,0:01:34.042
还有一些打荷台之类的东西 还有冰箱 

0:01:34.229,0:01:37.663
还有不锈钢的比如说这种盆盆罐罐的这些东西

0:01:37.926,0:01:39.637
总共花了1万5左右

0:01:40.000,0:01:41.711
其实这一块因为这一块我是专业的嘛

0:01:41.744,0:01:44.574
就是没有买贵 也没有被人家坑 

0:01:44.882,0:01:47.888
有的东西我买的是二手的 所以就便宜很多

0:01:48.118,0:01:50.367
然后剩下的就是一些厨房的工具

0:01:50.455,0:01:55.359
刀具啊 砧板啊 还有一些餐具之类的

0:01:55.633,0:01:57.816
这一块大概花了3、4千

0:01:58.540,0:02:04.421
总的算下来的话 我们不包括拍摄的设备

0:02:04.651,0:02:07.350
到目前为止总共投资了大概10万块钱

0:02:07.635,0:02:13.357
我17年回来的时候就是自己做厨师长攒了一点钱

0:02:13.439,0:02:16.631
然后用我老婆的信用卡刷了几万块钱

0:02:16.631,0:02:22.029
然后借了我亲戚一些钱来做这个工作室

0:02:22.172,0:02:25.222
刚开始的时候别人说我们比较傻

0:02:25.935,0:02:29.270
这个位置又偏 门面的话又不当道

0:02:29.851,0:02:33.274
然后租金也不便宜 1千多块钱一个月

0:02:33.867,0:02:35.501
问我做这个东西来干什么

0:02:35.589,0:02:37.213
开馆子的话位置又差

0:02:37.520,0:02:40.000
投资了这么多钱进去说我比较傻

0:02:40.307,0:02:42.852
然后这几年一步一步走过来 

0:02:43.093,0:02:45.935
我在这个地方拍了几百个视频

0:02:46.154,0:02:49.588
如果你们除了对这个（工作室）感兴趣之外

0:02:49.588,0:02:52.144
你们想看一下我拍摄的设备的话

0:02:52.155,0:02:54.569
下一期我可以给你们做一期视频

0:02:55.063,0:02:56.752
好了 今天的视频就到这里

0:02:57.948,0:03:00.065
总结一下这一块做了几年

0:03:00.219,0:03:02.172
花了十多万 比较值

0:03:03.686,0:03:06.110
就不说其他的 就拍了这么多视频

0:03:06.187,0:03:08.195
跟大家分享了这么多教学做菜

0:03:08.359,0:03:12.923
我觉得值了 这钱花的从心底里面来说很值

0:03:13.296,0:03:15.523
好了本期视频就到这里 拜拜


```

**Comment by Gavin-Geng** [comment]
认领

**Comment by Gavin-Geng** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
揭秘！给大家介绍我的后厨工作室，来算算一共投了多少钱
Demystify!  Introduce my kitchen studio to you, and see how much I've invested in it

简介
大家好，其实自从我拍视频以来一直有不少朋友在问我的拍摄环境是什么样的，这次就来拍个视频来介绍一下。最初拍视频的时候还在做厨师长，每天完成本职工作完再拍视频剪视频都到很晚，后来决定回到老家做一个工作室来全职给大家产出内容，其中也经历了很多迷茫和困苦，但都一点点的走过来了，就像我当初就想把厨艺学好一样，我想把内容做好，让大家想学一道菜就能找到最好最棒的方法！我一直以来很少涉及商业合作，但我觉得在不忘初心的条件下可以适当有些尝试，在这里附上一个邮箱地址 wanggangbusiness@gmail.com 如果有什么合作意向可以发邮件来联系（仅限于商业合作），感谢大家一直以来的支持与喜爱！
Hello everyone, actually since I made the video, many friends have been asking me what the shooting environment is like, so this time I'm going to make a video to introduce it. I was still working as a chef when I first made the video, once finishing my work, I would shoot and edit videos, often staying up late every day. Then I decided to return to my hometown and set up a studio to provide more videos for you guys as a full-time vlogger. During that time, I also experienced a lot of confusion and hardship, but I got through it. I want to make my video better just like I wanted to do well in cooking, and let everyone can find the best way to learn a dish! I have rarely been involved in business cooperation, but I think I can have a try under the condition of not forgetting my original intention. Here is my E-mail address "wanggangbusiness@gmail.com". Should you have any intention of cooperation, please contact me (Commercial cooperation only). Thank you very much for your consistent support and love!

字幕
0:00:00.318,0:00:01.722
哈喽大家好 我是王刚
Hello everyone, I'm Wang Gang

0:00:01.843,0:00:04.081
最近收到后台一些私信
Recently I received some private messages from the backgroud

0:00:04.103,0:00:11.870
就是其他作者问我们整个工作室到拍摄要花多少钱
Other authors asked us how much would it cost from preparing the entire studio to shoot videos

0:00:12.035,0:00:13.428
然后我就算了一笔账
Then, I made a calculation

0:00:13.757,0:00:15.359
从我们回来的时候
Since we got back

0:00:15.611,0:00:21.151
从2017年到现在我们这个房租押金是5千然后房租是1万5一年
from 2017 to now, our rent deposit is 5000 yuan, and the rent is 15,000 yuan per year

0:00:21.426,0:00:24.227
交了4万5千块钱的房租加押金
We paid 45,000 yuan in rent and deposit

0:00:24.245,0:00:25.913
反正这一块就5万块钱
Anyway, all these together cost about 50,000 yuan

0:00:26.549,0:00:32.331
然后就是我回来的时候这个门面它是一个比较长的一个门面
When we came back, it was a long shopfront

0:00:32.484,0:00:36.752
宽的话是3米5 长的话大概是10米多一点
It was 3.5m wide, and about 10 meters long

0:00:36.895,0:00:38.584
总共是40多个平方
totally more than 40 square meters

0:00:39.330,0:00:46.275
刚开始我们接手的时候这个门面是毛坯（房） 什么都没有
When we took over the shopfront, it was a rough room with nothing in it

0:00:46.396,0:00:49.083
然后我们回来搞了一下装修
Then we came back and did some decoration

0:00:49.149,0:00:53.274
就吊了顶 做了墙面 然后还有这个地板
we installed suspended ceiling, decorated walls and laid floor

0:00:53.614,0:00:56.083
这一块装修大概总共花了2万块钱左右
The whole decoration cost about 20,000 yuan in total

0:00:56.324,0:00:57.992
大部分的装修做完了之后呢
After most of the decorating was done

0:00:58.189,0:01:03.752
就要做排水 排烟道 水电气 这一块也比较贵
the following was to do the drainage, exhaust duct, as well as water, electricity and fuel supply. They were also expensive

0:01:03.894,0:01:08.129
因为我们这个门面它以前是做的库房 没有排水
Cuz our shopfront used to be a warehouse, there was no drainage in it

0:01:08.272,0:01:11.716
我们挖这个排水管从这边一直挖到街上去
Our drainpipe was dug from here to the street

0:01:12.002,0:01:14.525
挖得距离有点远 所以有点贵
a little far, so it cost a bit expensive

0:01:14.799,0:01:16.741
总共大概2万块钱左右
In all, we spent about 20,000 yuan

0:01:16.884,0:01:23.795
我们这块水电气装修吊顶地板做完了之后开始买设备
After finished all those mentioned above, we needed to buy equipments

0:01:23.938,0:01:29.939
设备的话就包括我后面上面这个烟罩 这个炉具 
including the top petticoat pipe behind me, the stove

0:01:30.060,0:01:34.042
还有一些打荷台之类的东西 还有冰箱
and some other things like "Da He Tai" (Spreader table), and refrigerator

0:01:34.229,0:01:37.663
还有不锈钢的比如说这种盆盆罐罐的这些东西
also something stainless steel, like these pots and pans

0:01:37.926,0:01:39.637
总共花了1万5左右
All these stuff cost me about 15,000 yuan

0:01:40.000,0:01:41.711
其实这一块因为这一块我是专业的嘛
In fact, I'm a professional in this feild

0:01:41.744,0:01:44.574
就是没有买贵 也没有被人家坑
so I neither spend too much money nor got screwed

0:01:44.882,0:01:47.888
有的东西我买的是二手的 所以就便宜很多
some stuff I bought secondhand, so it was much cheaper

0:01:48.118,0:01:50.367
然后剩下的就是一些厨房的工具
Then, all left are kitchen tools 

0:01:50.455,0:01:55.359
刀具啊 砧板啊 还有一些餐具之类的
like cutting tools, cutting boards and utensils

0:01:55.633,0:01:57.816
这一块大概花了3、4千
These cost about 3000 to 4000 yuan

0:01:58.540,0:02:04.421
总的算下来的话 我们不包括拍摄的设备
All together above, excluding the video equipments

0:02:04.651,0:02:07.350
到目前为止总共投资了大概10万块钱
We've invested about 100,000 yuan so far

0:02:07.635,0:02:13.357
我17年回来的时候就是自己做厨师长攒了一点钱
When I came back in 2017, I had saved some money as being a chef

0:02:13.439,0:02:16.631
然后用我老婆的信用卡刷了几万块钱
Then I swiped ten thousands of yuan on my wife's credit card

0:02:16.631,0:02:22.029
然后借了我亲戚一些钱来做这个工作室
Also borrowed some money from my relatives to make this studio

0:02:22.172,0:02:25.222
刚开始的时候别人说我们比较傻
At first people said we were stupid

0:02:25.935,0:02:29.270
这个位置又偏 门面的话又不当道
The location was out of the way

0:02:29.851,0:02:33.274
然后租金也不便宜 1千多块钱一个月
and the rent was not cheap either, cost more than 1000 yuan a month

0:02:33.867,0:02:35.501
问我做这个东西来干什么
They asked me what I was doing with it

0:02:35.589,0:02:37.213
开馆子的话位置又差
If I opened a restaurant, it would be in a bad location

0:02:37.520,0:02:40.000
投资了这么多钱进去说我比较傻
they said I was silly to invest so much money in it

0:02:40.307,0:02:42.852
然后这几年一步一步走过来
But I went on step by step over the years

0:02:43.093,0:02:45.935
我在这个地方拍了几百个视频
I made hundreds of videos in this place

0:02:46.154,0:02:49.588
如果你们除了对这个（工作室）感兴趣之外
If you're interested in anything besides this (studio)

0:02:49.588,0:02:52.144
你们想看一下我拍摄的设备的话
say you wanna take a look at my video equipments

0:02:52.155,0:02:54.569
下一期我可以给你们做一期视频
I can make it in my next video

0:02:55.063,0:02:56.752
好了 今天的视频就到这里
OK, that's all for today's vedio

0:02:57.948,0:03:00.065
总结一下这一块做了几年
Let's have a summary. I've been engaged in this feild for years

0:03:00.219,0:03:02.172
花了十多万 比较值
and have spent over 100,000 yuan, but it's worth it 

0:03:03.686,0:03:06.110
就不说其他的 就拍了这么多视频
Apart from other things, I've made so many videos

0:03:06.187,0:03:08.195
跟大家分享了这么多教学做菜
shared so many cooking videos

0:03:08.359,0:03:12.923
我觉得值了 这钱花的从心底里面来说很值
I think it's worth it. From the bottom of my heart, that's worth the money

0:03:13.296,0:03:15.523
好了本期视频就到这里 拜拜
All right, that's all for this video. Bye bye
