### ISSUE TITLE
[华农兄弟] 鸡鸭鹅小狗子 - https://youtu.be/7mIilHLwr4I

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#973]
https://youtu.be/7mIilHLwr4I
<p>&#35270;&#39057;&#21457;&#24067;&#20110; April 28, 2020 at 12:25PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/7mIilHLwr4I

#华农兄弟：刚买了一群鸡鸭鹅回来，兄弟又送来一群小狗子
#Huanong Brothers: We have just bought a whold herd of chickens, ducks and geese. But our buddy gives us a bunch of puppies again.

0:00:00.140,0:00:01.620
# 今天買了一些那些
Today I've bought some kind of,

0:00:01.980,0:00:03.980
# 雞  鴨  鵝
chickens, ducks, geese,

0:00:04.120,0:00:04.780
# 公雞
and roosters,

0:00:05.320,0:00:05.880
# 都有
everything.

0:00:06.260,0:00:07.760
# 買點回來這裡放養一下
I took them all back and let them run around here.

0:00:07.800,0:00:09.480
# 這  草好多啦  這裡
Here, here's a lot of grass.

0:00:10.000,0:00:10.960
# 把它們放出來
I let them come out first.

0:00:11.460,0:00:13.420
# 先放這個  這個我也不知道是甚麼
This bag first. I don't even know what they are?

0:00:13.940,0:00:14.800
# 看一下才知道
I need to take a look.

0:00:15.880,0:00:16.900
# 哎呀  這是鵝
Aya! These are geese!

0:00:17.740,0:00:18.960
# 鵝用來看家
I'll keep them as watchgeese.

0:00:19.480,0:00:20.480
# 你看  這兩個鵝
Look! These two geese

0:00:21.280,0:00:22.060
# 哎呀
Aya!

0:00:22.340,0:00:22.960
# 夠大吧
Really big, aren't they?

0:00:25.500,0:00:26.620
# 一下來就拉屎
It poops once it comes out.

0:00:32.100,0:00:32.980
# 好大
Really big!

0:00:35.520,0:00:36.420
# 鴨子
Ducks

0:00:46.740,0:00:47.240
# 這個
These are,

0:00:47.480,0:00:48.540
# 這個也是鴨子哦
these are also ducks.

0:00:49.400,0:00:50.600
# 那麼多隻
So many ducks

0:01:03.820,0:01:05.580
# 這兩個  這兩個也是鵝
These two, these two are geese too.

0:01:12.380,0:01:13.460
# 我要是買小的
If I bought the small ones,

0:01:13.740,0:01:15.460
# 小的長  長大太難啦
the small ones, the small ones would grow too slowly.

0:01:15.660,0:01:17.300
# 還不如直接買大的
So why not simply buy the big ones?

0:01:17.740,0:01:19.600
# 想吃的時候就直接進來拎
Whenever I want something to eat, I can simply come in and take one right away.

0:01:30.080,0:01:31.200
# 這4隻鴨子
These are four ducks.

0:01:32.560,0:01:33.520
# 一共多少隻
How many are there in total?

0:01:35.020,0:01:35.960
# 一共10隻
Ten ducks in total

0:01:40.080,0:01:40.900
# 這小雞
These are chickens.

0:01:42.060,0:01:43.120
# 這雞太小
The chickens are too small.

0:01:44.360,0:01:45.560
# 現在不能吃
I don't think I can eat them now.

0:01:58.780,0:02:00.120
# 這樣的小雞
They are far too tiny!

0:02:00.780,0:02:02.800
# 知道就不買  知道就不買這個
I wouldn't, I wouldn't have bought them had I known it in advance.

0:02:03.080,0:02:03.640
# 太小啦
Too small!

0:02:07.260,0:02:08.060
# 買大的
I should buy the big ones.

0:02:19.900,0:02:21.320
# 你看  這個  笨啊
Look! They are, stupid!

0:02:22.700,0:02:23.660
# 好笨這雞
Stupid chickens!

0:02:28.980,0:02:29.940
# 特意買了一個
Specially for the chickens, I've prepared a,

0:02:31.300,0:02:31.900
# 公的
rooster.

0:02:34.180,0:02:35.360
# 嗯  這個公雞
Um! This is a rooster.

0:02:36.780,0:02:37.540
# 這公雞
This rooster,

0:02:38.560,0:02:40.080
# 夠大的哦  三四斤哦
is big enough. It's almost two kilograms, you know.

0:02:40.500,0:02:41.180
# 會不會飛
Can it fly?

0:02:42.560,0:02:43.420
# 會飛喲
Yea, it can.

0:02:45.760,0:02:46.900
# 啊  這小雞
Ah! These small chickens,

0:02:48.140,0:02:49.020
# 小雞崽
baby chickens

0:03:15.980,0:03:17.160
# 你看  它這個小雞
Look! These small chickens,

0:03:19.820,0:03:20.540
# 那麼小
they're so small.

0:03:21.220,0:03:23.180
# 開始它慢慢開始找  找東西吃啦
They start, they're starting to look, look for food.

0:03:28.720,0:03:29.540
# 看一下那個鵝
Let's have a look at the geese.

0:03:29.960,0:03:31.260
# 那個鵝很靚哦
The geese are really beautiful.

0:03:45.380,0:03:46.380
# 好吵啊  它們
They're so noisy!

0:03:48.600,0:03:50.680
# 應該會下蛋哦  這個  那麼大的
I think they lay egg, don't they? They're already that big now.

0:04:01.780,0:04:03.420
# 不好抓 怕我
I can't catch them. They're scared of me.

0:04:24.000,0:04:24.960
# 來都不來一下
They don't even come to me.

0:04:25.120,0:04:27.080
# 沒餵它們  今天不能餵哦
Cuz I haven't fed them. But I'm not supposed to feed them today.

0:04:27.100,0:04:28.360
# 要明天開始餵
I have to wait till tomorrow.

0:04:30.880,0:04:32.400
# 給它們吃下草就行啦
They can simply have some grass.

0:05:09.620,0:05:11.060
# 你看  這兩個鵝
Look! These two geese...

0:05:12.380,0:05:13.080
# 哎喲
Ayo!

0:05:13.860,0:05:14.640
# 它不肯啊
It doesn't like it.

0:05:15.720,0:05:17.120
# 那麼不聽話
You're so naughty!

0:05:23.440,0:05:24.600
# 它吃草的  這個
It eats grass, this one.

0:05:25.280,0:05:26.780
# 那吃點草  這裡有草
Alright, then have some grass. Here's some grass.

0:05:29.840,0:05:30.900
# 它不吃
It's not eating.

0:05:34.000,0:05:35.460
# 好啦  我不打擾你啦
Alright! I'm not gonna disturb you anymore.

0:05:35.780,0:05:37.600
# 我不抓你啦  嗯  哎喲
I'll leave you alone. Um! Ayo!

0:05:39.600,0:05:40.940
# 這是 肯定是公的
This is, it must be male.

0:05:41.220,0:05:41.840
# 那麼兇
It's so fierce.

0:05:51.180,0:05:52.300
# 好兇啊  這個鵝
It's really fierce, this goose.

0:05:54.020,0:05:57.240
# 養鵝的話肯定  額  可以防一下那個  黃鼠狼
Keeping geese can certainly, I mean, can prevent the weasels from coming.

0:05:57.840,0:05:59.700
# 這邊黃鼠狼的話  它肯定就不敢來
The weasels nearby certainly don't dare to come,

0:05:59.740,0:06:00.560
# 因為有我
because of the geese.

0:06:01.360,0:06:03.260
# 看那小雞  保護那些小雞
Have a look at the chickens. They protect the chickens.

0:06:11.200,0:06:11.980
# 全跑啦
They've all run away.

0:06:12.220,0:06:13.880
# 你看它們  被我嚇到它們啦
Look! They're all scared by me.

0:06:23.840,0:06:25.740
# 今天兄弟又送一些狗給我
My buddy gave me some puppies again today.

0:06:25.920,0:06:27.300
# 我都養不起我自己啦
I can't even afford my own food now.

0:06:27.340,0:06:28.120
# 還送給我
But he still gave me puppies.

0:06:28.200,0:06:29.480
# 在那邊  我們去看一下
They're over there. Let's go and have a look!

0:06:31.140,0:06:33.080
# 鵝就放在這邊啦  不管它們啦
I'll leave the geese here alone.

0:06:34.820,0:06:35.320
# 你看
Look!

0:06:35.720,0:06:36.780
# 這個寵物狗
This is a pet dog.

0:06:37.280,0:06:38.260
# 就是兄弟送的
They are from my buddy.

0:06:38.660,0:06:40.680
# 養不大的  你看  路這個一模一樣的
They won't get big. Look! He just looks exactly the same as this dog.

0:06:40.780,0:06:41.760
# 長大了就跟這樣
This will be how he looks like when he grows up.

0:06:41.940,0:06:42.640
# 那麼  那麼
It's so, it's so,

0:06:43.000,0:06:43.860
# 那麼不好看
so ugly.

0:06:44.260,0:06:44.820
# 是不是
Am I right?

0:06:45.100,0:06:45.760
# 像不像你
Does he look like you?

0:06:46.860,0:06:47.480
# 像不像
Does he?

0:06:49.040,0:06:49.680
# 好像啊
Yea, of course!

0:06:50.340,0:06:51.960
# 看  長大了就不好看啦
As he grows up, he is now no longer cute.

0:06:52.140,0:06:53.500
# 你還小的時候好可愛哦
You were really cute when you were still a puppy.

0:06:56.340,0:06:57.160
# 爪子也很利
His claws are really sharp too.

0:07:00.060,0:07:00.560
# 你看
Look!

0:07:01.500,0:07:02.320
# 這小狗
This puppy...

0:07:06.180,0:07:07.560
# 哎呀  夠大
Aya! He's big.

0:07:08.700,0:07:10.100
# 這些好像漂亮一點哦
These seem to be prettier.

0:07:10.200,0:07:10.780
# 你看  這個
Look! This one,

0:07:11.080,0:07:12.060
# 這好像不一樣的
this one seems to be a bit different.

0:07:19.040,0:07:19.980
# 這個好靚  這個
This is beautiful, this one.

0:07:24.400,0:07:25.160
# 你看  這個
Look! This one...

0:07:26.060,0:07:26.900
# 看一下你
Let me have a look at you.

0:07:29.340,0:07:30.860
# 哎呀  這個好靚  這個
Aya! This is really beautiful, this one.

0:07:34.380,0:07:34.880
# 你看
Look!

0:07:35.160,0:07:36.000
# 這個靚  這個
She's beautiful, isn't she?

0:07:36.880,0:07:38.460
# 它爪子好長啊  爪子
Her claws are really long, her claws.

0:07:39.580,0:07:40.940
# 這個爪子好  好長
The claws are really, really long.

0:07:48.000,0:07:48.920
# 嗯  走開一點
Um! Go 'way!

0:07:51.380,0:07:52.340
# 這個也靚  這個
This is also beautiful, this one.

0:07:53.140,0:07:53.780
# 你看  這個
Look! This one...

0:07:58.280,0:07:58.940
# 這個靚
this one is beautiful.

0:08:00.540,0:08:01.700
# 要不就放在這裡吧
Shall I just leave them here?

0:08:02.180,0:08:03.060
# 全部放到這裡
Yea, leave them all here.

0:08:03.480,0:08:04.000
# 所以
So,

0:08:05.300,0:08:07.440
# 哪個粉絲想要的  這來  這來
any fans want them? Come here, come here,

0:08:07.760,0:08:08.480
# 自提哦
and pick one.

0:08:08.920,0:08:10.100
# 發快遞發不了的
I can't courier them to you.

0:08:11.700,0:08:13.160
# 誰要就誰帶回去
Whoever wants them can come and take home with you.

0:08:13.960,0:08:15.640
# 暫時先放到我這裡養著
They'll be staying here with me for the time being.

0:08:18.780,0:08:19.760
# 還有獠牙
He even has tusks.

0:08:21.420,0:08:22.180
# 好可愛哦
So cute!

0:08:25.860,0:08:26.800
# 很聽話的哦
He's a very good puppy, you know.

0:08:27.380,0:08:28.500
# 誰要誰拿去
Come and take him with you.

0:08:36.120,0:08:37.720
# 嗯  這隻怎麼那麼瘦  這個
Um? Why is this one so skinny, this one.

0:08:42.180,0:08:44.480
# 嘴巴好大啦  很能吃的哦   這樣的狗
She has a very big mouth! A puppy with a such a big mouth is always a big eater.

0:08:47.120,0:08:48.460
# 一臉無辜的看著我
She stares at me with her eyes filled with innocence.

0:08:51.780,0:08:52.480
# 沒事
No worries.

0:09:03.700,0:09:05.160
# 這兩隻好靚   這兩隻
These two are really beautiful, these two.

0:09:09.340,0:09:10.160
# 藍眼睛
Blue eyes

0:09:11.420,0:09:12.120
# 黑鼻子
Black nose

0:09:18.780,0:09:20.060
# 很靚的哦  這兩隻哦
These two are really really beautiful.

0:09:23.960,0:09:25.160
# 它毛好乾淨啊
His coat is very clean.

0:09:26.000,0:09:27.380
# 要天天給它洗澡才行
I'll need to bathe him every day.

0:09:32.520,0:09:36.280
# 它這個毛  跟  跟原來不一樣的  比較長的這個毛  (註︰「原來」應該是指其他，但我不幫他詮釋了)
His hair is, is, is different from the original one. His hair is a bit longer.

0:09:39.960,0:09:42.200
# 心跳得好快呀  生怕我不要它
His heart is beating very fast. He worries that I might throw him away.

0:09:43.020,0:09:43.720
# 要你
I won't.

0:09:47.880,0:09:48.540
# 小狗
Puppy

0:09:50.000,0:09:51.420
# 好靚呀  它這個小狗
It's really beautiful, this puppy.

0:10:00.540,0:10:01.880
# 好無辜的眼神
A pair of eyes full of innocence

0:10:03.100,0:10:04.200
# 兄弟不要它啦
My buddy doesn't want them anymore.

0:10:04.980,0:10:05.780
# 不要我要
I'll have them.

0:10:06.860,0:10:07.960
# 還養得起你們
I can still afford having you guys.

0:10:11.320,0:10:11.840
# 你看
Look!

0:10:12.740,0:10:13.520
# 很乖呀
A good puppy

0:10:29.240,0:10:30.640
# 全部躲到這裡面來啦
They're all hiding over there.

0:10:32.000,0:10:33.400
# 給點東西給它吃一下
Let me give them some food.

0:10:38.540,0:10:40.220
# 你看  這個狗都跟他們玩
Look! This dog likes being with them.

0:10:41.280,0:10:42.420
# 總共8條哦
There are eight in total.

0:10:43.440,0:10:43.940
# 8條
Eight puppies

0:10:49.360,0:10:50.140
# 放在這裡先
Let them stay here first,

0:10:50.380,0:10:51.180
# 看誰要的
and see who wants them.

0:10:51.940,0:10:53.200
# 誰要的把它領回去
Anyone who wants them, come and take one with you.

0:10:53.600,0:10:55.000
# 額  點給果子給你們吃
Eh! I have some fruits for you.

0:10:56.020,0:10:56.700
# 要不要
You want some?

0:11:00.220,0:11:01.580
# 吃草的  這個狗
He eats grass, this puppy.

0:11:02.020,0:11:04.060
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.

0:11:09.900,0:11:12.040
# 耳朵不一樣的  你看  這個
Their ears are not the same. Look! This one.

0:11:14.300,0:11:15.520
# 小時候很可愛的
He was really cute when he was small.

0:11:15.640,0:11:17.120
# 長大了成這樣子啦
But that's how he looks now.
