### ISSUE TITLE
【美食作家王刚】滑肉汤 - https://youtu.be/VMT5n4cko1w

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#976]
**视频链接**：https://youtu.be/VMT5n4cko1w

视频时长3:03，预计发布时间为北京时间4月30日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“滑肉汤”的家常做法，口感嫩滑汤鲜味美，值得一学

简介
同学们好，今天教大家一道传统小吃“滑肉汤”，
其重点在于肉的处理，要做到不脱浆，最后成汤清亮。
这样做出来的肉特别嫩滑，故而得名“滑肉汤”，
没有尝试过的朋友有机会一定要自己试试，
是一道简单但又显功夫的一道好菜！

本期菜品：【滑肉汤】
【主料】
猪前腿肉（约300克）
【辅料】
鸡蛋（1个）
红薯淀粉（约300克）
丝瓜（1条）
红薯粉条（适量）
生姜（1小块）
小葱（几根）
植物油（少许）
青花椒（几颗）
【调味料】
食用盐（适量）
胡椒粉（少许）
料酒（适量）

字幕
0:00:00.300,0:00:01.380
哈喽大家好 我是王刚

0:00:01.380,0:00:02.680
本期视频我跟大家分享

0:00:03.080,0:00:04.240
滑肉汤的做法

0:00:04.440,0:00:06.360
首先我们准备前腿肉一块（约300克）

0:00:06.500,0:00:08.775
将肉切成3毫米左右的厚片备用

0:00:08.775,0:00:10.475
同学们最好选择前腿肉

0:00:10.475,0:00:12.600
这样成菜之后肉不绵比较嫩

0:00:12.800,0:00:14.075
下一步开始腌制

0:00:14.075,0:00:15.725
碗中加入食用盐1勺（约1.5克）

0:00:16.075,0:00:17.475
加入少许胡椒粉

0:00:17.925,0:00:19.275
加入适量的料酒

0:00:19.950,0:00:21.775
加入鸡蛋1个搅拌均匀

0:00:27.650,0:00:30.050
加入红薯淀粉1小把搅拌均匀备用（约50克）

0:00:30.150,0:00:32.575
同学们搅拌的时候可以适当的摔打

0:00:36.000,0:00:38.800
然后另外准备一个碗加入适量的红薯淀粉（约250克）

0:00:38.875,0:00:40.925
再加入适量的开水搅拌均匀

0:00:40.975,0:00:43.450
同学们这一步必须加入现烧开的开水

0:00:46.650,0:00:49.300
拌匀之后倒入装肉的碗中搅拌均匀即可

0:00:49.400,0:00:52.050
加开水兑红薯粉的目的是增加其粘性

0:00:52.050,0:00:54.625
这样可以使其下锅的时候不容易脱浆

0:00:58.175,0:00:59.625
下一步开始准备辅料

0:00:59.825,0:01:02.950
准备丝瓜1条刮掉表皮之后切成滚刀块备用

0:01:02.950,0:01:06.600
不喜欢丝瓜的同学可以用豌豆尖或者绿色的蔬菜

0:01:10.450,0:01:12.275
再加入适量的红薯粉条备用

0:01:14.250,0:01:16.075
准备生姜1小块拍散备用

0:01:16.450,0:01:18.550
最后准备小葱几根挽成结备用

0:01:19.775,0:01:21.025
下一步开始制作

0:01:21.950,0:01:24.075
锅烧热之后加入少许的植物油

0:01:25.300,0:01:27.675
油温烧热之后加入几颗青花椒爆锅

0:01:28.650,0:01:30.300
然后加入准备好的姜葱

0:01:30.900,0:01:33.450
略炒之后加入适量的清水开大火烧开

0:01:40.100,0:01:43.300
大火烧开之后将处理好的前腿肉依次下入锅中

0:01:50.125,0:01:52.125
然后再撇去浮沫烧1分钟

0:02:00.525,0:02:03.025
中途加入准备好的丝瓜和红薯粉条

0:02:08.325,0:02:10.950
烧至1分钟之后再捡去小葱丢弃不用

0:02:15.075,0:02:16.425
然后开始调味

0:02:17.325,0:02:19.275
锅中加入食用盐2小勺（约5克）

0:02:21.950,0:02:23.250
加入少许胡椒粉

0:02:24.000,0:02:25.775
调好味之后即可出锅上菜

0:02:33.620,0:02:36.200
一道口感爽滑的滑肉汤就制作完成

0:02:47.340,0:03:02.720
下面开始技术总结
第一，最好选择前腿肉或者里脊肉制作，这样成菜更嫩
第二，挂糊最好用开水调过的红薯粉
第三，肉下锅的时候必须保持水开的状态否则容易脱浆
滑肉汤的技术总结完毕


```

**Comment by Kevinzheng5** [comment]
认领

**Comment by Kevinzheng5** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“滑肉汤”的家常做法，口感嫩滑汤鲜味美，值得一学
Chef Wang teaches you: Home-style “Tender Pork Soup”. Juicy and tender, savory and delicious. Worth a try! 
简介
同学们好，今天教大家一道传统小吃“滑肉汤”，其重点在于肉的处理，要做到不脱浆，最后成汤清亮。这样做出来的肉特别嫩滑，故而得名“滑肉汤”，没有尝试过的朋友有机会一定要自己试试，是一道简单但又显功夫的一道好菜！
Hey guys, today I’ll share a traditional snack “Tender Pork Soup”. The critical part is the pork preparation to make sure the coat stays on and then the soup stays clear. Pork cooked this way is extra tender and that is the reason the dish got its name. If you haven’t had it before, you must have a try! It’s a simple but tricky dish!

本期菜品：【滑肉汤】【Tender Pork Soup】
【主料】【Ingredients】
猪前腿肉（约300克）Pork picnic ham (about 300 grams)
【辅料】【Minor Ingredients】
鸡蛋（1个）One egg
红薯淀粉（约300克）Sweet potato starch (About 300 grams) 
丝瓜（1条）One loofah
红薯粉条（适量）Sweet potato vermicelli
生姜（1小块）Ginger
小葱（几根）Green onions
植物油（少许）Vegetable oil
青花椒（几颗）Green Sichuan peppercorn
【调味料】【Seasoning】
食用盐（适量）Salt
胡椒粉（少许）Pepper
料酒（适量）Chinese cooking wine

字幕
0:00:00.300,0:00:01.380
哈喽大家好 我是王刚
Hi guys, it’s Wang Gang

0:00:01.380,0:00:02.680
本期视频我跟大家分享
Today I’ll share

0:00:03.080,0:00:04.240
滑肉汤的做法
The recipe of “Tender Pork Soup”

0:00:04.440,0:00:06.360
首先我们准备前腿肉一块（约300克）
First we prepare a piece of picnic ham (about 300 grams)

0:00:06.500,0:00:08.775
将肉切成3毫米左右的厚片备用
Cut it to 3 millimeter slices

0:00:08.775,0:00:10.475
同学们最好选择前腿肉
The picnic ham is the best for the dish

0:00:10.475,0:00:12.600
这样成菜之后肉不绵比较嫩
The texture is tender enough

0:00:12.800,0:00:14.075
下一步开始腌制
Then let’s marinate the pork

0:00:14.075,0:00:15.725
碗中加入食用盐1勺（约1.5克）
Put a teaspoon of salt into the bowl

0:00:16.075,0:00:17.475
加入少许胡椒粉
Then some pepper

0:00:17.925,0:00:19.275
加入适量的料酒
Some Chinese cooking wine

0:00:19.950,0:00:21.775
加入鸡蛋1个搅拌均匀
Add an egg and mix it well

0:00:27.650,0:00:30.050
加入红薯淀粉1小把搅拌均匀备用（约50克）
Put about 50 grams of sweet potato starch and mix it well

0:00:30.150,0:00:32.575
同学们搅拌的时候可以适当的摔打
During mixing, toss the pork too

0:00:36.000,0:00:38.800
然后另外准备一个碗加入适量的红薯淀粉（约250克）
Then get another bowl and put in about 250 grams of starch

0:00:38.875,0:00:40.925
再加入适量的开水搅拌均匀
Put in some boiling water and stir well

0:00:40.975,0:00:43.450
同学们这一步必须加入现烧开的开水
The water must be boiling hot

0:00:46.650,0:00:49.300
拌匀之后倒入装肉的碗中搅拌均匀即可
Then pour the starch into the pork bowl

0:00:49.400,0:00:52.050
加开水兑红薯粉的目的是增加其粘性
The boiling water will make the starch liquid more sticky 

0:00:52.050,0:00:54.625
这样可以使其下锅的时候不容易脱浆
So it stays on the pork when cooking

0:00:58.175,0:00:59.625
下一步开始准备辅料
Next let’s get the minor ingredients ready

0:00:59.825,0:01:02.950
准备丝瓜1条刮掉表皮之后切成滚刀块备用
Peel one loofah. Roll and cut it to pieces

0:01:02.950,0:01:06.600
不喜欢丝瓜的同学可以用豌豆尖或者绿色的蔬菜
You can also use bean sprouts or other veggies instead

0:01:10.450,0:01:12.275
再加入适量的红薯粉条备用
Add some sweet potato vermicelli

0:01:14.250,0:01:16.075
准备生姜1小块拍散备用
Crush a small piece of ginger

0:01:16.450,0:01:18.550
最后准备小葱几根挽成结备用
Last, get a few green onions and tie them together

0:01:19.775,0:01:21.025
下一步开始制作
Let’s start cooking

0:01:21.950,0:01:24.075
锅烧热之后加入少许的植物油
Heat up the wok and put in some vegetable oil

0:01:25.300,0:01:27.675
油温烧热之后加入几颗青花椒爆锅
When the oil is hot, put the green Sichuan peppercorn in there

0:01:28.650,0:01:30.300
然后加入准备好的姜葱
Then drop the ginger and green onions

0:01:30.900,0:01:33.450
略炒之后加入适量的清水开大火烧开
Stir fry and then pour the water in and bring it to boil

0:01:40.100,0:01:43.300
大火烧开之后将处理好的前腿肉依次下入锅中
When it’s boiling, get the pork in

0:01:50.125,0:01:52.125
然后再撇去浮沫烧1分钟
Get rid of the scum and then boil for one minute

0:02:00.525,0:02:03.025
中途加入准备好的丝瓜和红薯粉条
Add the loofah and vermicelli in the meantime

0:02:08.325,0:02:10.950
烧至1分钟之后再捡去小葱丢弃不用
After a minute, take the green onions off

0:02:15.075,0:02:16.425
然后开始调味
Next, let’s season the soup

0:02:17.325,0:02:19.275
锅中加入食用盐2小勺（约5克）
Two spoons of salt

0:02:21.950,0:02:23.250
加入少许胡椒粉
Some pepper

0:02:24.000,0:02:25.775
调好味之后即可出锅上菜
After seasoning, it’s ready

0:02:33.620,0:02:36.200
一道口感爽滑的滑肉汤就制作完成
A “Tender Pork Soup” with smooth and tender texture, done

0:02:47.340,0:03:02.720
下面开始技术总结
第一，最好选择前腿肉或者里脊肉制作，这样成菜更嫩
Now let’s conclude the technical points. First, use the picnic ham or the tenderloin for the juicy texture
第二，挂糊最好用开水调过的红薯粉
Second, mix the starch with boiling water for the pork coat
第三，肉下锅的时候必须保持水开的状态否则容易脱浆
Third, the water must be boiling when we drop the pork. Otherwise the coat will come off
滑肉汤的技术总结完毕
That’s all the points for the “Tender Pork Soup”
