### ISSUE TITLE
[华农兄弟] 华农兄弟给小胖狗洗个澡顺便给它穿个漂亮的衣服 - https://youtu.be/HUVQnIgITIg

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#979]
https://youtu.be/HUVQnIgITIg
<p>&#35270;&#39057;&#21457;&#24067;&#20110; April 29, 2020 at 11:56AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/HUVQnIgITIg

#华农兄弟：给小胖狗洗个澡，顺便给它穿个漂亮的衣服
#Huanong Brothers: We give Chubby Bear a bath and then dress him up in pretty clothes.

0:00:00.000,0:00:03.440
# 大家好  今天好熱啦  帶釔狗去洗一下澡  你看
Hi everyone. It's really hot today. Let's take the puppy to have a bath. Look!

0:00:03.620,0:00:05.360
# 它都不洗澡  不講衛生
He never takes a bath, so unhygienic.

0:00:06.620,0:00:08.740
# 現在還不願意去  拉它去它都不願意去
He still doesn't want to go. I'm pulling him but he still doesn't want to move.

0:00:09.060,0:00:09.620
# 走
Just go!

0:00:10.140,0:00:11.660
# 去 帶你去河邊 走
Go! I'm taking you to the riverside. Let's go!

0:00:14.800,0:00:15.300
# 走
Go!

0:00:23.060,0:00:24.760
# 快點走  快點  走
C'mon, go! C'mon, let's go!

0:00:25.100,0:00:26.580
# 你看  它不肯去
Look! He doesn't want to go.

0:00:27.120,0:00:28.400
# 拉它去它都不肯去
He's simply not moving no matter how hard I pull.

0:00:28.680,0:00:29.980
# 等下我丟到你河裡去
Don't make me throw you into the river!

0:00:30.240,0:00:31.160
# 還不快點  來
Hurry up! C'mon!

0:00:32.400,0:00:33.280
# 一身都是
You're covered with,

0:00:34.180,0:00:35.240
# 那個  泥土
I mean, with dirt.

0:00:38.600,0:00:39.100
# 走
Go!

0:00:50.900,0:00:52.960
# 這小狗它都不願意去洗澡的
This puppy doesn't want to take a bath at all.

0:00:55.380,0:00:58.180
# 要講衛生  不衛生講怎麼行
Hygiene is important. How can you be that unhygienic?

0:00:58.880,0:00:59.380
# 走啦
Let's go!

0:01:00.000,0:01:00.720
# 快點
Hurry up!

0:01:08.560,0:01:09.580
# 你看  這狗
Look! This dog,

0:01:10.560,0:01:12.360
# 從出生到現在都沒洗過澡
has never had a bath since his birth.

0:01:13.740,0:01:14.960
# 太髒了它身上
He's so dirty.

0:01:16.040,0:01:17.640
# 剛好借了兄弟一點點這個
My buddy just lent me a tiny little bit of, this is,

0:01:18.780,0:01:19.680
# 洗狗液
dog shampoo

0:01:24.120,0:01:25.080
# 舒不舒服
Does it feel good?

0:01:26.580,0:01:27.340
# 舒服吧
Good, isn't it?

0:01:32.720,0:01:34.540
# 它身上  還粘了
Something get stuck, stuck on his body.

0:01:35.040,0:01:36.100
# 粘了石頭  (註︰語序關係無法直譯，唯有稍稍改動說法)
These are rocks.

0:01:36.840,0:01:38.100
# 粘了石頭在這裡
The rocks get stuck on his body.

0:01:40.420,0:01:41.260
# 粘了個
The rocks,

0:01:41.760,0:01:42.420
# 石頭
get stuck on his body.

0:01:45.780,0:01:48.120
# 你看  那麼多沐浴露放上去  泡都沒有的
Look! There's hardly any foam in spite of the huge amount of shampoo.

0:01:50.120,0:01:52.060
# 說明就很髒啦  它身上
That means he is really dirty, all over the body.

0:01:59.960,0:02:01.380
# 沒事噠  過來
No worries! Come here!

0:02:04.840,0:02:05.660
# 它不肯
He doesn't like it.

0:02:07.800,0:02:09.380
# 不肯也要洗呀 不肯
Like it or not, I'm bathing you today.

0:02:10.040,0:02:10.780
# 那麼髒
You're so dirty!

0:02:15.680,0:02:16.860
# 再洗洗  再搞點
Wash again, more shampoo.

0:02:41.280,0:02:43.180
# 你看 它老是想跑
Look! He always wants to run away.

0:02:43.740,0:02:45.000
# 這樣怎麼行
How can it be?

0:02:47.600,0:02:48.220
# 下來
Get down!

0:02:48.940,0:02:49.520
# 等下我
Don't make me,

0:02:52.420,0:02:54.060
# 等下我  揍你的哦
don't make me beat you up, got it?

0:02:55.360,0:02:56.220
# 那麼不聽話
What a naughty boy!

0:03:02.060,0:03:02.900
# 還有好多泡
There's still a lot of foam.

0:03:12.560,0:03:14.080
# 你看  現在洗的差不多了
Look! We're almost done.

0:03:16.600,0:03:18.340
# 菜葉子都有洗到這裡來
A veggie leaf is splashed here.

0:03:19.340,0:03:20.880
# 你看  這裡還有一片菜葉子
Look! Here's a veggie leaf.

0:03:23.440,0:03:25.300
# 可以了吧  那麼乾淨了
Isn't it good? You're so clean now.

0:03:25.580,0:03:26.720
# 你還嫌棄
How disgraceful you are!

0:03:27.760,0:03:28.440
# 不可以叫
No yelping!

0:03:34.020,0:03:34.620
# 好啦
Alright!

0:03:35.480,0:03:36.140
# 洗乾淨啦
He's very clean now.

0:03:37.560,0:03:39.680
# 你這邊有那麼多泡泡沒洗
There's still a lot of foam in this side.

0:03:47.840,0:03:48.880
# 都沒洗過澡
It's your first bath.

0:03:49.860,0:03:51.140
# 知道你身上有多髒嗎
Do you have any idea how dirty you were?

0:03:52.460,0:03:53.880
# 你看  我把它放啦
Look! I'm gonna take off the leash.

0:03:54.500,0:03:56.020
# 等  等一下讓它乾了之後
I'll, I'll put it on again,

0:03:56.800,0:03:57.820
# 我們再把它抓來
when he's dried.

0:03:58.660,0:04:00.220
# 好  回家  上去
Alright! Let's go home! Go up there!

0:04:01.760,0:04:03.240
# 等下它乾了之後就好啦
Everything is done after he's dried.

0:04:08.600,0:04:09.600
# 走  回家
C'mon! Let's go home!

0:04:31.800,0:04:33.040
# 你看 把這個狗
Look! We're gonna dress up the dog,

0:04:33.940,0:04:35.760
# 把個狗給它穿一下女裝
dress up the dog in girl's clothing.

0:04:37.140,0:04:38.420
# 我們穿女裝
If the clothes are on us,

0:04:39.620,0:04:41.380
# 太嚇人啦  嘿嘿嘿
it's too scary. Ha ha ha!

0:04:42.380,0:04:42.900
# 受不了
Horrible!

0:04:44.740,0:04:45.900
# 剛好套在頭上來
I can put it on through his head.

0:04:46.760,0:04:48.600
# 你看 這樣就靚了吧
Look! Isn't it beautiful?

0:04:49.540,0:04:50.580
# 可以啦  就這樣就可以啦
Alright! It's fine now.

0:04:54.260,0:04:55.020
# 這樣就可以啦
It's fine now.

0:04:55.740,0:04:56.960
# 這還有一個  還有一個裙子
One more. We have a skirt too.

0:05:06.320,0:05:07.500
# 給它套下來
Tuck it into the skirt.

0:05:12.380,0:05:13.400
# 這個裙子
What a nice skirt!

0:05:23.320,0:05:23.980
# 帥吧
Handsome boy!

0:05:37.260,0:05:39.080
# 別動  別動 等一下就好了
Don't move. Don't move. It will be finished in a second,

0:05:39.480,0:05:40.460
# 等一下就好了
just one more second.

0:05:46.300,0:05:47.360
# 這個小姑娘
This is a lady.

0:05:48.520,0:05:50.180
# 很漂亮啊  哦  你看一下
So pretty. Oh! Take look!

0:05:51.040,0:05:51.740
# 你兒子
You son,

0:05:52.500,0:05:54.160
# 這是你兒子哦  變成這樣子啦
this is your son. This is his new look.

0:05:58.940,0:06:00.160
# 它正面多好看
He looks really nice in the front.

0:06:04.620,0:06:05.760
# 過來  看一下
Come here! Take a look!

0:06:07.340,0:06:08.500
# 可以哦 這樣
It's not bad, c'mon!

0:06:10.180,0:06:11.900
# 比以前漂亮多啦
He's so much prettier than before.

0:06:16.300,0:06:18.680
# 它裙子不適合它  它老是踩
The skirt doesn't fit him well. He's always stepping on it.

0:06:26.940,0:06:28.260
# 它媽都不認識它了
His mom can't even recognize him.

0:06:31.960,0:06:33.280
# 誒  怎麼掉了
Ey? Why is it dropped?

0:06:35.200,0:06:35.760
# 過來
Come here!

0:06:42.640,0:06:43.640
# 揍你哦  等下
I'm gonna beat you up!

0:06:51.280,0:06:52.700
# 你看  這下它就方便啦
Look! He feels much more comfortable now.

0:07:00.640,0:07:01.960
# 不可以  搞掉
No! Don't take it off!

0:07:03.100,0:07:03.840
# 不可以搞掉
Don't take it off!

0:07:04.720,0:07:05.440
# 再看一下
Let me watch for a while.

0:07:10.760,0:07:12.880
# 可以  這個  這個套裝
This, this suit is really not bad.

0:07:14.180,0:07:14.940
# 絕對是
It's undoubtedly,

0:07:15.420,0:07:16.380
# 最漂亮的
the prettiest.

0:07:17.220,0:07:17.720
# 看
Look!

0:07:18.480,0:07:19.120
# 不要動
Don't move!

0:07:19.880,0:07:20.380
# 誒呦
Eyo!

0:07:20.860,0:07:21.360
# 壞得很
Bad boy!

0:07:21.480,0:07:21.980
# 過來
Come here!

0:07:24.060,0:07:24.960
# 腳上這個才靚
The ones of the feet are the most beautiful!

0:07:29.920,0:07:31.120
# 很委屈  是不是
You suffered a lot, didn't you?

0:07:31.760,0:07:32.820
# 有甚麼好委屈的
It's not a suffering at all.

0:07:33.600,0:07:35.860
# 你不委屈怎麼辦  委屈我是吧
But if it's not you, then who? You want it be us?

0:07:37.020,0:07:38.060
# 你委屈一下就好啦
A little bit of your suffering can do so much good.

0:07:43.560,0:07:45.340
# 我穿女裝  會嚇到你的
You would be terrified if I dress up in girl's clothing.

0:07:46.500,0:07:47.360
# 你穿一下
So you're a better option.

0:07:48.360,0:07:49.860
# 你看一下  它很配合了
Have a look! He's so cooperative.

0:07:51.040,0:07:51.560
# 是不是
Aren't you?

0:07:52.000,0:07:52.780
# 好配合啊
You're so cooperative.

0:07:54.300,0:07:57.220
# 今天  今 今  今天  今天買肉給你吃
Today, to, to, today, today, you'll have meat.

0:08:01.300,0:08:01.800
# 好啦
Alright!

0:08:02.200,0:08:02.760
# 自由啦
You're free now!

0:08:08.900,0:08:09.400
# 你看
Look!

0:08:09.780,0:08:10.875
# 他頭也不回
He's not looking back,

0:08:10.875,0:08:11.875
# 他頭也不回
not looking back at all!
