### ISSUE TITLE
【美食作家王刚】 鱼香肉丝 - https://youtu.be/wOtheXhqOAI

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#982]
**视频链接**：https://youtu.be/wOtheXhqOAI

视频时长7:57，预计发布时间为北京时间5月1日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长分享：“鱼香肉丝”的家常做法，味道巴适又下饭，正宗川味！

简介
朋友们好，今天和大家分分享一道广为流传的川菜“鱼香肉丝”，之前就有和大家讲过何为“鱼香”，在这里再解释一下，所谓鱼香并不是因为有鱼的味道，而是用四川传统烧鱼的配料调料的味道，这也就是为什么“鱼香肉丝”“鱼香茄条”等菜中没有鱼的原因。本期视频给大家介绍的是鱼香肉丝广为流传的家常做法，可以自由发挥配上自己喜欢的菜，如果想学后厨版本的鱼香肉丝可以点击链接：正宗传统老式鱼香肉丝：https://www.youtube.com/watch?v=TpR9-9CNxAY 广为流传的川味鱼香肉丝 https://www.youtube.com/watch?v=68v5mGdE978

字幕
0:00:00.275,0:00:01.025
哈喽大家好 

0:00:01.050,0:00:03.399
今天我伯爷又有一块肉没有卖完

0:00:03.400,0:00:05.825
今天我们来炒一个鱼香肉丝 家庭版的

0:00:06.200,0:00:08.026
煮好了这样切（肉）要散噶

0:00:08.100,0:00:08.600
嗯

0:00:11.675,0:00:16.125
我们这样一片一片的这样片开了再切丝

0:00:20.150,0:00:24.725
嘿 切这个肉片你的技术还来得到火

0:00:25.475,0:00:27.075
这个很简单

0:00:27.275,0:00:32.500
很简单 没整（切）过的整不到这么薄

0:00:32.775,0:00:36.448
这是厨师刀工的必修之课

0:00:36.450,0:00:37.225
哦

0:00:38.400,0:00:41.525
这哈子把它横过来直接切丝丝

0:00:42.675,0:00:44.525
切起好长根哦

0:00:44.850,0:00:48.500
打斜刀撒 肯定你打竖刀切起就长了哦

0:00:49.800,0:00:51.475
好 现在肉丝切好了

0:00:52.000,0:00:57.050
这个一斤的肉切出来还是不少哦你看

0:00:57.300,0:00:58.450
那当然了

0:00:59.000,0:01:01.900
好 我们现在开始腌肉 先把肉腌了

0:01:02.575,0:01:04.850
我们肉丝的话这个盐一定要少放一点

0:01:05.025,0:01:08.275
放多了的话它会跟其他的味道抢味

0:01:09.000,0:01:13.000
然后再放点料酒 料酒也不宜太多

0:01:13.425,0:01:17.975
然后我们给它抓一下 因为家庭做的话就简简单单的是吧

0:01:19.525,0:01:20.675
你还是要打蛋啊

0:01:20.950,0:01:22.000
要打蛋

0:01:23.675,0:01:25.450
然后再打一个全蛋 

0:01:26.000,0:01:27.800
家庭里面没有必要只放蛋清 

0:01:28.000,0:01:31.440
你如果只放蛋清的话那这个蛋黄干什么呢 

0:01:31.440,0:01:34.150
蛋黄就只有丢掉 丢掉就浪费了

0:01:38.550,0:01:40.650
好 略微抓一下

0:01:41.050,0:01:45.575
然后再放跟蛋黄等量的干淀粉

0:01:45.950,0:01:47.675
淀粉也不可以太多 

0:01:48.825,0:01:50.200
再给它抓一下

0:01:52.850,0:02:00.425
这个抓匀了之后再放一点油 油放进去给它保一下

0:02:02.000,0:02:07.000
油放进去之后里面的水份不会被蒸发出来 就是把它封锁住了

0:02:07.150,0:02:12.350
待会儿下锅的时候这些肉丝也不会全部粘连在一起

0:02:12.475,0:02:14.500
现在就给它轻轻地捞一下

0:02:20.075,0:02:21.150
好 这下就可以了

0:02:21.150,0:02:24.250
简单版本的肉丝就腌好了

0:02:24.325,0:02:26.775
这个腌法特别适合家庭用

0:02:28.050,0:02:30.650
有很多粉丝说这个鱼香肉丝为什么没有鱼

0:02:30.825,0:02:34.850
我想跟你们说的就是这个鱼香肉丝并不是里面一定要有鱼

0:02:34.850,0:02:43.000
它只是说以前这个菜吧 是用做鱼的辅料和肉丝一起炒

0:02:49.625,0:02:50.975
然后我们来切这个木耳

0:02:51.075,0:02:53.275
木耳我们切得时候最好把它卷起来

0:02:54.375,0:02:56.925
卷起来切更均匀

0:03:01.050,0:03:03.675
这样子切起跟海带丝样

0:03:03.925,0:03:04.475
是

0:03:06.175,0:03:08.875
然后切这个莴笋

0:03:09.300,0:03:11.750
加莴笋其实就是配它的绿色

0:03:12.175,0:03:14.625
有青有绿有黑有白

0:03:15.050,0:03:16.100
还有红的

0:03:16.275,0:03:16.725
嗯

0:03:19.125,0:03:21.800
莴笋可以适当的长一点 因为它会软

0:03:24.250,0:03:26.150
好了 现在切点红萝卜

0:03:33.500,0:03:34.925
好 配料就配好了

0:03:34.975,0:03:36.300
现在再切一点料头

0:03:37.125,0:03:40.050
我们准备了一点泡椒 我伯爷自己泡的

0:03:41.025,0:03:44.040
他不能吃辣 所以就选了一个大的 大的就不辣

0:03:44.150,0:03:45.525
这个海椒就没得好辣的

0:03:46.725,0:03:48.475
然后横着把它切碎

0:03:51.225,0:03:52.125
辣椒切好了

0:03:54.300,0:03:56.325
大蒜我们给它剁碎

0:03:59.150,0:04:02.550
鱼香肉丝里面大蒜的比例是姜的3倍

0:04:08.725,0:04:10.450
然后我们再拍一块姜

0:04:13.275,0:04:18.365
这个姜还不是要配的合适啊 是夹（涩）口的就不好干

0:04:18.450,0:04:18.975
是

0:04:19.925,0:04:20.450
好

0:04:23.125,0:04:26.050
我们料也配好了 辅料也切完了

0:04:26.250,0:04:27.700
现在就还要调一个汁

0:04:27.900,0:04:29.575
我们现在在碗里加一点盐

0:04:30.425,0:04:33.500
然后加几勺白糖 

0:04:35.400,0:04:40.300
糖的话可以稍微多一些 大概有30克

0:04:40.700,0:04:46.875
然后我们加一点醋 醋的话跟糖基本上是1:1

0:04:47.875,0:04:50.850
再加点生抽中和一下这个味道

0:04:52.600,0:04:54.425
然后再加一点点水

0:04:56.400,0:04:59.575
最后再加点这个干淀粉给它搅拌均匀

0:05:01.100,0:05:02.275
好 可以了

0:05:03.100,0:05:04.700
来嘛 四伯爷帮我拿过来一哈

0:06:10.200,0:06:12.768
加入少许明油

0:06:43.375,0:06:44.400
尝哈看 四伯爷

0:06:44.725,0:06:45.450
试哈看嘛

0:06:45.825,0:06:47.175
很下饭这个菜

0:06:51.125,0:06:55.675
有点酸有点甜有点辣有点咸有点鲜

0:06:55.725,0:06:56.325
真的啊

0:06:56.550,0:06:57.125
嗯

0:06:58.150,0:06:58.675
好干

0:07:01.450,0:07:03.800
最入味的就是这个红萝卜

0:07:04.475,0:07:05.250
你吃出来没

0:07:05.400,0:07:06.075
红萝卜吗

0:07:06.125,0:07:06.450
嗯

0:07:11.225,0:07:11.800
安逸

0:07:18.325,0:07:22.775
我们这个鱼香肉丝最大的一个特点就是很下饭

0:07:22.900,0:07:25.150
因为它酸酸甜甜的又有点辣味

0:07:25.375,0:07:29.200
这几个（配菜）味道吃起还多舒服吃起

0:07:39.975,0:07:42.700
安逸 这个味道舒服

0:07:45.200,0:07:46.650
好 本期视频就到这里

0:07:46.725,0:07:50.950
大家可以尝试一下 看一看我之前拍的鱼香肉丝

0:07:51.050,0:07:55.575
但是这个的话就是一个家常菜 就是在家里面自己炒一炒可以


```

**Comment by immoonancient** [comment]
@iamatrollatrollisme 请前来认领

**Comment by iamatrollatrollisme** [comment]
认领

**Comment by iamatrollatrollisme** [comment]
厨师长分享：“鱼香肉丝”的家常做法，味道巴适又下饭，正宗川味！
Chef Wang Shares: Authentic Sichuan Homestyle “Shredded Pork with Garlic Fish Sauce”, goes great with rice

简介
朋友们好，今天和大家分分享一道广为流传的川菜“鱼香肉丝”，之前就有和大家讲过何为“鱼香”，在这里再解释一下，所谓鱼香并不是因为有鱼的味道，而是用四川传统烧鱼的配料调料的味道，这也就是为什么“鱼香肉丝”“鱼香茄条”等菜中没有鱼的原因。本期视频给大家介绍的是鱼香肉丝广为流传的家常做法，可以自由发挥配上自己喜欢的菜，如果想学后厨版本的鱼香肉丝可以点击链接：正宗传统老式鱼香肉丝：https://www.youtube.com/watch?v=TpR9-9CNxAY 广为流传的川味鱼香肉丝 https://www.youtube.com/watch?v=68v5mGdE978

Dear friends, today I am going to share with you a very popular Sichuan dish “Shredded Pork with Garlic Fish Sauce”, I have told you before why we call this sauce “garlic fish sauce”, I am going to explain it a bit here, we call it fish sauce is not because it tastes like fish, it is because this is the sauce we traditionally use in Sichuan Cuisine to cook fish, this is why “Shredded Pork with Garlic Fish Sauce” and “Eggplant with Garlic Fish Sauce” and other dishes do not have fish in the dish. In this video I am going to share with you a very popular homestyle recipe, you can add any other ingredients if you see fit, if you would like to learn the professional restaurant recipe please see the previous video through the link here: 

Traditional Sichuan style Shredded Pork with Garlic Fish Sauce recipe:
https://www.youtube.com/watch?v=TpR9-9CNxAY


Popular Sichuan style Shredded Pork with Garlic Fish Sauce recipe: https://www.youtube.com/watch?v=68v5mGdE978

字幕
0:00:00.275,0:00:01.025
哈喽大家好 
Hello everyone

0:00:01.050,0:00:03.399
今天我伯爷又有一块肉没有卖完
Today my uncle has a piece of pork that he did not sell

0:00:03.400,0:00:05.825
今天我们来炒一个鱼香肉丝 家庭版的
Today we can make a homestyle Sichuan style Shredded Pork with Garlic Fish Sauce

0:00:06.200,0:00:08.026
煮好了这样切（肉）要散噶
If you slice (the meat) this way it might become loose once cooked

0:00:08.100,0:00:08.600
嗯
Yeah

0:00:11.675,0:00:16.125
我们这样一片一片的这样片开了再切丝
We first slice the pork like this then cut then into julienne shape

0:00:20.150,0:00:24.725
嘿 切这个肉片你的技术还来得到火
Hey, the way you cut this meat shows your knife skill is very good

0:00:25.475,0:00:27.075
这个很简单
This is very easy

0:00:27.275,0:00:32.500
很简单 没整（切）过的整不到这么薄
Very easy? You can not slice it this thin if you do not practice

0:00:32.775,0:00:36.448
这是厨师刀工的必修之课
Knife skill is the basic of a chef

0:00:36.450,0:00:37.225
哦
Okay

0:00:38.400,0:00:41.525
这哈子把它横过来直接切丝丝
Now we put the meat side way to cut them into julienne shape 

0:00:42.675,0:00:44.525
切起好长根哦
This is very long

0:00:44.850,0:00:48.500
打斜刀撒 肯定你打竖刀切起就长了哦
Cut it sideways, you slice it vertically it will be long

0:00:49.800,0:00:51.475
好 现在肉丝切好了
Okay now the meat is cut

0:00:52.000,0:00:57.050
这个一斤的肉切出来还是不少哦你看
500g of pork is a decent amount

0:00:57.300,0:00:58.450
那当然了
Yes of course

0:00:59.000,0:01:01.900
好 我们现在开始腌肉 先把肉腌了
Okay, now let’s marinate the pork

0:01:02.575,0:01:04.850
我们肉丝的话这个盐一定要少放一点
For the pork, we need to be careful and not putting too much salt in there

0:01:05.025,0:01:08.275
放多了的话它会跟其他的味道抢味
If you put too much it will overwhelm other flavors

0:01:09.000,0:01:13.000
然后再放点料酒 料酒也不宜太多
Then we add some Chinese cooking wine, we should not put too much

0:01:13.425,0:01:17.975
然后我们给它抓一下 因为家庭做的话就简简单单的是吧
Then we mix them well, because this is homestyle dish we will do it the easy way

0:01:19.525,0:01:20.675
你还是要打蛋啊
Are you adding eggs?

0:01:20.950,0:01:22.000
要打蛋
Yes, I am adding egg

0:01:23.675,0:01:25.450
然后再打一个全蛋 
Then adding a whole egg

0:01:26.000,0:01:27.800
家庭里面没有必要只放蛋清 
Homestyle recipe no need to add egg white only

0:01:28.000,0:01:31.440
你如果只放蛋清的话那这个蛋黄干什么呢 
What are you going to do with the yolk?

0:01:31.440,0:01:34.150
蛋黄就只有丢掉 丢掉就浪费了
All you can do is throw it away, it is wasteful

0:01:38.550,0:01:40.650
好 略微抓一下
Okay now we mix it a little more

0:01:41.050,0:01:45.575
然后再放跟蛋黄等量的干淀粉
Adding some corn starch, about the same amount as the egg yolk

0:01:45.950,0:01:47.675
淀粉也不可以太多 
We can not put too much corn starch either

0:01:48.825,0:01:50.200
再给它抓一下
Now mix it a little more

0:01:52.850,0:02:00.425
这个抓匀了之后再放一点油 油放进去给它保一下
Once we mix it well, we add some oil to wrap them up

0:02:02.000,0:02:07.000
油放进去之后里面的水份不会被蒸发出来 就是把它封锁住了
Once we add the oil the moisturizer will not vaporize, oil can wrap it up and lock the water

0:02:07.150,0:02:12.350
待会儿下锅的时候这些肉丝也不会全部粘连在一起
Later on, when we add the shredded meat into the wok, they will not stick together

0:02:12.475,0:02:14.500
现在就给它轻轻地捞一下
Now we pick them up a little bit

0:02:20.075,0:02:21.150
好 这下就可以了
Okay, now we are done

0:02:21.150,0:02:24.250
简单版本的肉丝就腌好了
Easy version meat marinate is finished

0:02:24.325,0:02:26.775
这个腌法特别适合家庭用
This kind of marinating approach is very good for family cooking

0:02:28.050,0:02:30.650
有很多粉丝说这个鱼香肉丝为什么没有鱼
Lots of fans are asking why is this Sichuan style Shredded Pork with Garlic Fish Sauce does not have fish

0:02:30.825,0:02:34.850
我想跟你们说的就是这个鱼香肉丝并不是里面一定要有鱼
I just want to tell you that this dish does not need fish

0:02:34.850,0:02:43.000
它只是说以前这个菜吧 是用做鱼的辅料和肉丝一起炒
It is because back then, we use the ingredient to cook the cook to stir fry the pork

0:02:49.625,0:02:50.975
然后我们来切这个木耳
Now let’s slice the wood ear mushroom

0:02:51.075,0:02:53.275
木耳我们切得时候最好把它卷起来
While slicing the wood ear mushroom, it’s better if we curl them up

0:02:54.375,0:02:56.925
卷起来切更均匀
You can slice them more evenly if you curl them up

0:03:01.050,0:03:03.675
这样子切起跟海带丝样
It looks like seaweed slices 

0:03:03.925,0:03:04.475
是
Yes

0:03:06.175,0:03:08.875
然后切这个莴笋
Now we are slicing some celtuce

0:03:09.300,0:03:11.750
加莴笋其实就是配它的绿色
Adding celtuce is just to add some green color

0:03:12.175,0:03:14.625
有青有绿有黑有白
We got some green, some black and some white

0:03:15.050,0:03:16.100
还有红的
And red

0:03:16.275,0:03:16.725
嗯
Yeah

0:03:19.125,0:03:21.800
莴笋可以适当的长一点 因为它会软
We can slice celtuce a little longer because it gets soft

0:03:24.250,0:03:26.150
好了 现在切点红萝卜
Okay, now we slice some carrot

0:03:33.500,0:03:34.925
好 配料就配好了
Okay, now all other ingredients are ready

0:03:34.975,0:03:36.300
现在再切一点料头
Now we prepare some aromatics

0:03:37.125,0:03:40.050
我们准备了一点泡椒 我伯爷自己泡的
We prepared some pickled chili, my uncle made it himself

0:03:41.025,0:03:44.040
他不能吃辣 所以就选了一个大的 大的就不辣
He can not really eat too spicy, so I am going to pick a large one, large chili is not spicy

0:03:44.150,0:03:45.525
这个海椒就没得好辣的
Yeah, this chili is not very spicy

0:03:46.725,0:03:48.475
然后横着把它切碎
Now we put them side ways and chop them finely

0:03:51.225,0:03:52.125
辣椒切好了
Now we finish preparing the chili

0:03:54.300,0:03:56.325
大蒜我们给它剁碎
Now we mince the garlic

0:03:59.150,0:04:02.550
鱼香肉丝里面大蒜的比例是姜的3倍
In Shredded Pork with Garlic Fish Sauce the amount of garlic is 3 times as much as the ginger

0:04:08.725,0:04:10.450
然后我们再拍一块姜
Then as add a piece of ginger

0:04:13.275,0:04:18.365
这个姜还不是要配的合适啊 是夹（涩）口的就不好干
We need to pick the right ginger, otherwise it will taste dry

0:04:18.450,0:04:18.975
是
Yes

0:04:19.925,0:04:20.450
好
Okay

0:04:23.125,0:04:26.050
我们料也配好了 辅料也切完了
Now we prepare both all other ingredients and aromatics

0:04:26.250,0:04:27.700
现在就还要调一个汁
Now we need to make the sauce

0:04:27.900,0:04:29.575
我们现在在碗里加一点盐
Now we are adding a little salt in the bowl

0:04:30.425,0:04:33.500
然后加几勺白糖 
Then adding a few tablespoons of sugar

0:04:35.400,0:04:40.300
糖的话可以稍微多一些 大概有30克
We can add more sugar, about 30g

0:04:40.700,0:04:46.875
然后我们加一点醋 醋的话跟糖基本上是1:1
The we add some vinegar, the ratio of vinegar and sugar is pretty much 1:1

0:04:47.875,0:04:50.850
再加点生抽中和一下这个味道
Then adding some light soy sauce to neutralize the taste

0:04:52.600,0:04:54.425
然后再加一点点水
Then add some water

0:04:56.400,0:04:59.575
最后再加点这个干淀粉给它搅拌均匀
At last we add some corn starch and mix it well

0:05:01.100,0:05:02.275
好 可以了
Okay now we are good to go

0:05:03.100,0:05:04.700
来嘛 四伯爷帮我拿过来一哈
Come here, Uncle help me get that 

0:06:10.200,0:06:12.768
加入少许明油
Now we add some oil

0:06:43.375,0:06:44.400
尝哈看 四伯爷
Have a taste uncle

0:06:44.725,0:06:45.450
试哈看嘛
Try it out

0:06:45.825,0:06:47.175
很下饭这个菜
It goes very well with rice

0:06:51.125,0:06:55.675
有点酸有点甜有点辣有点咸有点鲜
It is a little sour, sweet, spicy, salty and savory

0:06:55.725,0:06:56.325
真的啊
Really

0:06:56.550,0:06:57.125
嗯
Yeah

0:06:58.150,0:06:58.675
好干
Tasty

0:07:01.450,0:07:03.800
最入味的就是这个红萝卜
All the flavors are in the carrot

0:07:04.475,0:07:05.250
你吃出来没
Did you taste it

0:07:05.400,0:07:06.075
红萝卜吗
You mean carrot

0:07:06.125,0:07:06.450
嗯
Yes

0:07:11.225,0:07:11.800
安逸
Nice

0:07:18.325,0:07:22.775
我们这个鱼香肉丝最大的一个特点就是很下饭
One thing about this dish is that it goes extremely well with rice

0:07:22.900,0:07:25.150
因为它酸酸甜甜的又有点辣味
Because it is sweet and sour as well as a little spicy

0:07:25.375,0:07:29.200
这几个（配菜）味道吃起还多舒服吃起
And the other ingredients also taste very good

0:07:39.975,0:07:42.700
安逸 这个味道舒服
Nice the dish is very delicious

0:07:45.200,0:07:46.650
好 本期视频就到这里
Okay, this is all for today’s video

0:07:46.725,0:07:50.950
大家可以尝试一下 看一看我之前拍的鱼香肉丝
You can try all other recipes for this same dish

0:07:51.050,0:07:55.575
但是这个的话就是一个家常菜 就是在家里面自己炒一炒可以
But for this recipe is more suitable for making at home, totally a homestyle dish
