### ISSUE TITLE
【美食作家王刚】精炼猪油 - https://youtu.be/vPpDzuRt86k

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#983]
**视频链接**：https://youtu.be/vPpDzuRt86k

视频时长5:02，预计发布时间为北京时间5月2日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“精炼猪油”的家常做法，满满的小技巧，必须学习收藏了

简介
同学们好，今天和大家分享“精炼猪油”的方法，这样炼出来的猪油不仅雪白并且香味浓郁，是炒青菜时蔬最佳的拍档，并且炼油剩下的油渣真的特别的香！（相信是不少朋友小时候的回忆，逢年过节家长炼油的时候最期待的就是能吃上些油渣，包括我自己）并且现代饮食习惯以植物油脂为主，其实有些时候加入些动物脂肪也能适当调节营养构成，希望大家喜欢。

“猪板油”是猪肚子里独立的肥膘，主要应该是为了保护脏器，大家如果有兴趣可以看我四伯解猪的视频，链接在此：https://www.youtube.com/watch?v=FdtJVcmFVWI 也欢迎专业人士（学医或者兽医）来给大家介绍一下猪板油是什么。

本期菜品【精炼猪油】
【主料】
猪板油（约2500克）
【辅料】
大葱（约250克）
生姜（约150克）
【调味料】
食用盐（约3克）
青花椒（适量）
料酒（适量）

字幕
0:00:00.320,0:00:01.500
哈喽大家好我是王刚

0:00:01.500,0:00:03.240
本期视频我给大家分享如何

0:00:03.720,0:00:05.020
精炼猪油

0:00:05.280,0:00:09.400
首先我们准备一副猪板油大约2500克左右

0:00:09.625,0:00:12.200
通常来说猪越大板油则越多

0:00:12.325,0:00:15.875
然后小心地剔除多余的瘦肉和隐藏在边上的淋巴

0:00:27.700,0:00:30.686
去除杂质和淋巴之后将猪油切成小块备用

0:00:30.686,0:00:33.000
同学们大约切成麻将大小即可

0:00:47.200,0:00:48.800
下一步开始准备辅料

0:00:49.525,0:00:51.600
准备半斤大葱切成小段备用

0:00:58.675,0:01:01.125
准备2大块生姜切成姜片备用（约150克）

0:01:01.125,0:01:04.325
同学们姜葱是用于炼猪油时加入增香去除异味

0:01:09.650,0:01:11.650
最后我们准备瓦罐器具1个

0:01:14.750,0:01:16.175
加入适量的食用盐（约3克）

0:01:19.275,0:01:20.850
再加入适量的青花椒

0:01:20.900,0:01:23.800
这一步的目的是延长猪油装在里面的保质期

0:01:24.050,0:01:25.325
下一步开始制作

0:01:25.750,0:01:28.175
首先我们在锅中加入适量的清水

0:01:30.800,0:01:33.400
然后加入切好的猪油首次焯水1分钟

0:01:33.850,0:01:37.100
同学们时间的计算方法必须是水开之后的1分钟

0:01:37.175,0:01:40.025
这一步的目的是去除板油中的血渍和杂质

0:01:47.775,0:01:49.150
1分钟之后捞出备用

0:01:58.375,0:02:00.425
然后锅中重新加入适量的清水

0:02:00.550,0:02:02.800
再次将猪油下锅焯水1分钟

0:02:08.925,0:02:10.825
中途加入适量的料酒去腥

0:02:10.900,0:02:13.300
这一步可以有效的去除板油的异味

0:02:17.300,0:02:19.275
焯水1分钟之后捞出备用

0:02:26.625,0:02:27.875
下一步开始炼(猪)油

0:02:28.450,0:02:30.650
锅洗干净之后加入1碗纯净水

0:02:35.325,0:02:37.850
然后将猪油下锅转中小火炼10分钟

0:02:38.275,0:02:39.800
此过程分为3个阶段

0:02:39.800,0:02:41.550
第一阶段是前3分钟

0:02:41.700,0:02:43.750
这一步是去除猪油中的水份

0:02:43.875,0:02:47.105
所以此时会有大量的水份蒸发锅中冒白烟

0:02:47.200,0:02:49.550
同学们锅里面的油脂此时是乳白色

0:02:57.000,0:03:00.200
第二阶段是6分钟之后锅中的蒸汽明显减少

0:03:00.200,0:03:02.625
然后锅中的油脂逐渐变成透明色

0:03:11.050,0:03:14.725
在第二阶段也就是熬制6分钟之后加入切好的姜葱下锅

0:03:15.000,0:03:17.916
此时开始进入第三阶段出油增香

0:03:29.325,0:03:32.150
熬制9分钟油渣和姜葱会变成金黄色（油脂明亮）

0:03:32.250,0:03:35.325
然后将油脂取出放入装有盐和花椒的器具中

0:03:47.000,0:03:49.475
剩余的油渣我们继续小火熬1分钟

0:04:01.275,0:04:04.050
1分钟之后将油渣倒出挤干油水即可

0:04:11.725,0:04:14.500
同学们此时的油渣可以撒上白糖直接吃

0:04:14.775,0:04:17.000
也可以用于炒蔬菜或者炖汤

0:04:17.240,0:04:19.900
熬制好的猪油待冷却之后即可保存

0:04:47.120,0:05:01.320
下面开始技术总结
第一，熬制猪油必须小火否则很容易老
第二，猪油的吸附力比植物油更强所以炒蔬菜会更香
第三，猪油常温保存最好不超过90天
炼猪油的技术总结完毕


```

**Comment by Yibing-Du** [comment]
Bot, please upload
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“精炼猪油”的家常做法，满满的小技巧，必须学习收藏了
Wang Gang Teaches You: Refined pork fat at home and other useful tricks
简介
Introduction
同学们好，今天和大家分享“精炼猪油”的方法，这样炼出来的猪油不仅雪白并且香味浓郁，是炒青菜时蔬最佳的拍档，并且炼油剩下的油渣真的特别的香！（相信是不少朋友小时候的回忆，逢年过节家长炼油的时候最期待的就是能吃上些油渣，包括我自己）并且现代饮食习惯以植物油脂为主，其实有些时候加入些动物脂肪也能适当调节营养构成，希望大家喜欢。
Hello everyone, today I'm sharing the recipe of preparing pork fat. The pork fat will be white and flavorful when we add it to stir-fried vegetables, and we'll also end up having some nice, crispy fat, which tastes great! (I'm sure many of you remember that flavor from childhood when you look forward to having some of this when your parents prepare the pork fat for festivals, me included). Now people are used to eating more vegetable oils, but sometimes adding animal fats will also be nutritious, so I hope you like this.
“猪板油”是猪肚子里独立的肥膘，主要应该是为了保护脏器，大家如果有兴趣可以看我四伯解猪的视频，链接在此：https://www.youtube.com/watch?v=FdtJVcmFVWI 也欢迎专业人士（学医或者兽医）来给大家介绍一下猪板油是什么。
We're using a special kind of lard that's in the belly area used to protect the organs in the abdomen, if you're interested, here's a video of Si Bo dissecting a pig: https://www.youtube.com/watch?v=FdtJVcmFVWI. If you're a medical professional or a vet and know about what it is exactly, feel free to comment below and explain to us! 

本期菜品【精炼猪油】
【主料】
Main ingredients
猪板油（约2500克）
Lard (around 2500g)
【辅料】
Minor ingredients
大葱（约250克）
Green onions (around 250g)
生姜（约150克）
Ginger (around 150g)
【调味料】
Seasoning
食用盐（约3克）
Salt (around 3g)
青花椒（适量）
Green Sichuan peppercorn
料酒（适量）
Chinese cooking wine

字幕
0:00:00.320,0:00:01.500
哈喽大家好我是王刚
Hello everyone, this is Wang Gang
0:00:01.500,0:00:03.240
本期视频我给大家分享如何
In today's video, I'll share the recipe for
0:00:03.720,0:00:05.020
精炼猪油
Refining pork fat
0:00:05.280,0:00:09.400
首先我们准备一副猪板油大约2500克左右
First, we prepare around 2500g of lard
0:00:09.625,0:00:12.200
通常来说猪越大板油则越多
A fatter pig will have a bigger piece of lard
0:00:12.325,0:00:15.875
然后小心地剔除多余的瘦肉和隐藏在边上的淋巴
Then we carefully remove the extra meat and the hidden lymph on the side
0:00:27.700,0:00:30.686
去除杂质和淋巴之后将猪油切成小块备用
After removing the extra parts, cut the lard into small pieces and set them aside
0:00:30.686,0:00:33.000
同学们大约切成麻将大小即可
The size of a Mahjong card will be good enough
0:00:47.200,0:00:48.800
下一步开始准备辅料
Now let's prepare the minor ingredients
0:00:49.525,0:00:51.600
准备半斤大葱切成小段备用
Prepare 250g of green onions and cut them into shorter pieces
0:00:58.675,0:01:01.125
准备2大块生姜切成姜片备用（约150克）
Prepare two pieces of ginger and slice them (around 150g)
0:01:01.125,0:01:04.325
同学们姜葱是用于炼猪油时加入增香去除异味
Ginger and green onion adds extra flavor and removes the bad taste
0:01:09.650,0:01:11.650
最后我们准备瓦罐器具1个
Now we prepare a jug
0:01:14.750,0:01:16.175
加入适量的食用盐（约3克）
Add 3g of salt
0:01:19.275,0:01:20.850
再加入适量的青花椒
Then add some green Sichuan peppercorn
0:01:20.900,0:01:23.800
这一步的目的是延长猪油装在里面的保质期
This is to let the pork fat last longer
0:01:24.050,0:01:25.325
下一步开始制作
Now start preparing the pork fat
0:01:25.750,0:01:28.175
首先我们在锅中加入适量的清水
First add some water to the wok
0:01:30.800,0:01:33.400
然后加入切好的猪油首次焯水1分钟
THen add the cutted lard to parboil for a minute
0:01:33.850,0:01:37.100
同学们时间的计算方法必须是水开之后的1分钟
This means a minute after the water boils
0:01:37.175,0:01:40.025
这一步的目的是去除板油中的血渍和杂质
This is to remove the blood and impurities from the lard
0:01:47.775,0:01:49.150
1分钟之后捞出备用
Take it out after a minute
0:01:58.375,0:02:00.425
然后锅中重新加入适量的清水
Then add some water to the wok again
0:02:00.550,0:02:02.800
再次将猪油下锅焯水1分钟
And parboil for another minute
0:02:08.925,0:02:10.825
中途加入适量的料酒去腥
Add some Chinese cooking wine midway to remove the bad taste
0:02:10.900,0:02:13.300
这一步可以有效的去除板油的异味
This is helpful to remove the bad smell
0:02:17.300,0:02:19.275
焯水1分钟之后捞出备用
Parboil for a minute and take it out
0:02:26.625,0:02:27.875
下一步开始炼(猪)油
Now let's refine the pork fat
0:02:28.450,0:02:30.650
锅洗干净之后加入1碗纯净水
Rinse the wok and add a bowl of water
0:02:35.325,0:02:37.850
然后将猪油下锅转中小火炼10分钟
Add the pork fat and turn to medium-low heat for 10 minutes
0:02:38.275,0:02:39.800
此过程分为3个阶段
This process has three stages
0:02:39.800,0:02:41.550
第一阶段是前3分钟
The first lasts for 3 minutes
0:02:41.700,0:02:43.750
这一步是去除猪油中的水份
This is to remove the water from the fat
0:02:43.875,0:02:47.105
所以此时会有大量的水份蒸发锅中冒白烟
So now you'll see lots of water vapour
0:02:47.200,0:02:49.550
同学们锅里面的油脂此时是乳白色
And the fat should be milky white in the wok
0:02:57.000,0:03:00.200
第二阶段是6分钟之后锅中的蒸汽明显减少
The second stage is 6 minutes after we start, you see less steam
0:03:00.200,0:03:02.625
然后锅中的油脂逐渐变成透明色
Then the fat also turns transparent in the wok
0:03:11.050,0:03:14.725
在第二阶段也就是熬制6分钟之后加入切好的姜葱下锅
Now, meaning 6 minutes after we start, add cutted gingers and green onions
0:03:15.000,0:03:17.916
此时开始进入第三阶段出油增香
Now we enter the third stage in which the oil comes out and we start to smell it
0:03:29.325,0:03:32.150
熬制9分钟油渣和姜葱会变成金黄色（油脂明亮）
After 9 minutes, gingers, green onions, and the crispy fat all turns golden (the fat looks bright)
0:03:32.250,0:03:35.325
然后将油脂取出放入装有盐和花椒的器具中
Then we pour the fat out to the jar with salt and peppercorn
0:03:47.000,0:03:49.475
剩余的油渣我们继续小火熬1分钟
We continue to heat the remaining crispy fat on low heat for a minute
0:04:01.275,0:04:04.050
1分钟之后将油渣倒出挤干油水即可
After a minute, take it out and get rid of the oil
0:04:11.725,0:04:14.500
同学们此时的油渣可以撒上白糖直接吃
Now we can eat it with some sugar
0:04:14.775,0:04:17.000
也可以用于炒蔬菜或者炖汤
Or use it to stir-fry vegetables or make soups
0:04:17.240,0:04:19.900
熬制好的猪油待冷却之后即可保存
We wait until the pork fat cools down to store it
0:04:47.120,0:05:01.320
下面开始技术总结
第一，熬制猪油必须小火否则很容易老
第二，猪油的吸附力比植物油更强所以炒蔬菜会更香
第三，猪油常温保存最好不超过90天
炼猪油的技术总结完毕
Now we summarize the key tips
First of all, we need to use low heat
Secondly, compared to vegetable oil, pork fat tastes better with stir-fried vegetables because it can be better absorbed
Thirdly, you'd better finish the pork fat within 90 days if it's kept under room temperature
Above is all for Refined Pork Fat
