### ISSUE TITLE
[雪鱼] 牛肉夹烧饼+猪头肉 -https://youtu.be/2XW6REyKoTU

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#985]
**视频链接**：https://youtu.be/2XW6REyKoTU

请帮忙先翻字幕，标题简介还没有准备好，发布前我自己翻译下标题简介，然后联系小组同学帮忙修改完善，谢谢。

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）


简介

字幕
1
00:00:01,750 --> 00:00:03,800
山东·济南

2
00:00:21,775 --> 00:00:23,725
烧饼夹牛肉

3
00:00:26,300 --> 00:00:29,300
济南四月的清晨 还是有些清冷的

4
00:00:29,600 --> 00:00:31,925
这样的温度 适合吃个有能量的早餐

5
00:00:32,525 --> 00:00:34,075
今天雪鱼来到回民街

6
00:00:34,275 --> 00:00:36,700
咱尝一尝这边的烧饼夹牛肉

7
00:00:37,800 --> 00:00:40,050
大姐 这个多少钱一个

8
00:00:40,575 --> 00:00:41,225
10块钱

9
00:00:41,350 --> 00:00:43,075
拿两个就行

10
00:00:58,975 --> 00:01:01,975
大哥 是刚才面已经揉完了 卖完了吗

11
00:01:01,975 --> 00:01:03,056
卖完了

12
00:01:04,500 --> 00:01:06,800
一天就卖这么一缸面是吧   对对

13
00:01:11,425 --> 00:01:13,800
你看 像揉面 剁牛肉都是大哥自己来

14
00:01:14,300 --> 00:01:16,750
而像烤烧饼都是让大姐来上

15
00:01:17,225 --> 00:01:19,850
两个人分工真的是很明确

16
00:01:58,750 --> 00:02:00,625
先炕再烤

17
00:02:00,625 --> 00:02:03,850
上面是不抹油的（会用油擦一下铁板）

18
00:02:48,000 --> 00:02:50,400
看我们买的10块钱一个的牛肉夹馍

19
00:02:51,225 --> 00:02:53,625
肉都要冒出来了

20
00:02:55,000 --> 00:02:57,950
在寒冷的清晨 看着冒着热气的牛肉

21
00:02:58,175 --> 00:03:00,250
真的是特别舒服

22
00:03:01,775 --> 00:03:02,975
芝麻还好多

23
00:03:03,075 --> 00:03:06,633
这么闻着就是 面香味和牛肉的香味特别浓郁

24
00:03:06,950 --> 00:03:08,400
我要先吃一口了

25
00:03:11,425 --> 00:03:12,600
好咸啊

26
00:03:15,200 --> 00:03:17,200
牛肉 汤汁特别多

27
00:03:18,025 --> 00:03:19,900
咬一口不会觉得噎着

28
00:03:20,500 --> 00:03:22,800
牛肉是五香的 酱香的

29
00:03:23,025 --> 00:03:27,425
把它剁成细末 细丝夹在烧饼里

30
00:03:27,650 --> 00:03:29,890
烧饼夹牛肉 分量这么重

31
00:03:29,890 --> 00:03:31,490
我觉得不仅我能吃饱

32
00:03:31,490 --> 00:03:34,090
像一个大汉 也能吃得饱的

33
00:03:38,475 --> 00:03:42,775
现在快7点了 后面的烧饼夹牛肉忙碌起来了

34
00:03:42,775 --> 00:03:47,700
大姐 牛肉烧饼作为早餐 顾客一般都买几个

35
00:03:47,850 --> 00:03:49,325
这个不一定

36
00:03:49,750 --> 00:03:55,250
买最多的时候 有的人一买二三十个 十来个 这情况每天都有

37
00:03:55,475 --> 00:03:58,625
因为他们都知道这是用的鲜牛肉 现宰的活牛

38
00:03:59,175 --> 00:04:03,550
进口的和我这牛肉相差15块钱吧

39
00:04:04,875 --> 00:04:07,125
现在我买的牛肉32块钱一斤

40
00:04:07,475 --> 00:04:09,075
平时买36块钱一斤

41
00:04:09,500 --> 00:04:10,825
这个就是 一般来说

42
00:04:10,925 --> 00:04:12,750
你要是长期在这个地方能干下去

43
00:04:12,825 --> 00:04:16,775
就必须得讲诚信 必须讲质量 必须讲味道

44
00:04:17,350 --> 00:04:19,500
因为现在人花钱他就是说

45
00:04:19,600 --> 00:04:24,600
你再深的巷子 只要味道好 他也愿意来

46
00:04:32,000 --> 00:04:35,725
大姐早上8点收摊

47
00:04:37,950 --> 00:04:41,025
下午4点 山东济南

48
00:04:45,800 --> 00:04:47,575
大叔 猪头肉多少钱了

49
00:04:47,575 --> 00:04:49,275
38元一斤

50
00:04:50,600 --> 00:04:53,325
行 20块钱的猪头肉

51
00:04:53,925 --> 00:04:55,950
 我给你称

52
00:04:58,650 --> 00:05:00,050
来 少来点吧

53
00:05:00,050 --> 00:05:02,300
行 好好好

54
00:05:02,300 --> 00:05:03,775
这都没有了 卖完了

55
00:05:04,025 --> 00:05:05,900
不是4点开始营业吗

56
00:05:06,275 --> 00:05:10,675
3点半 他们都挨着号排队

57
00:05:13,150 --> 00:05:16,500
顾客：顺着这个味道就找来了

58
00:05:19,050 --> 00:05:23,900
俺这老汤都多少年了吧 精华全在汤里的

59
00:05:24,175 --> 00:05:25,775
都是您们两个人在这边干吗  是的

60
00:05:27,200 --> 00:05:29,925
对 这是猪头肉

61
00:05:30,250 --> 00:05:33,225
我先掀开你看看

62
00:05:34,775 --> 00:05:36,875
猪头肉怎么卖的   38元一斤 但是都卖完了

63
00:05:37,200 --> 00:05:39,750
大叔一直吆喝着卖完了卖完了

64
00:05:46,175 --> 00:05:49,183
开始干的时候还是小鲜肉

65
00:05:49,183 --> 00:05:51,350
现在成大叔级了

66
00:05:54,775 --> 00:05:56,300
一般几点出来

67
00:05:57,025 --> 00:05:59,025
不到4点

68
00:06:02,125 --> 00:06:05,325
你要想买肠子 两点半就得来 想买大肠

69
00:06:06,850 --> 00:06:10,000
不排个前三四名的买不上大肠

70
00:06:10,000 --> 00:06:11,842
买大肠得两点半来吗

71
00:06:12,150 --> 00:06:14,050
大肠做的少 买的人多

72
00:06:15,075 --> 00:06:17,400
如果不是2点半来  那也需要早来

73
00:06:17,400 --> 00:06:19,000
他不是四点出摊吗

74
00:06:19,257 --> 00:06:20,707
提前排队

75
00:06:22,525 --> 00:06:25,650
我说想吃肥肠 猪尾巴这些的必须早来

76
00:06:26,700 --> 00:06:27,916
这一共有多少种

77
00:06:28,075 --> 00:06:31,425
生肉 250斤 20多种肉

78
00:06:33,775 --> 00:06:35,250
来给我弄点肉汤

79
00:06:35,550 --> 00:06:37,530
这下好了 不仅肉得抢着买

80
00:06:37,650 --> 00:06:39,550
大家连汤都不放过

81
00:06:46,650 --> 00:06:48,082
这个老汤回去怎么吃

82
00:06:48,150 --> 00:06:51,275
喝面条 吃米饭都行

83
00:06:53,375 --> 00:06:55,750
炖豆腐 炸豆腐

84
00:06:57,175 --> 00:06:59,075
还有炒鸡蛋

85
00:07:04,300 --> 00:07:05,700
做卤肉确实累

86
00:07:05,700 --> 00:07:10,225
早上3点就起床 你说的是实在话

87
00:07:10,450 --> 00:07:12,275
 太累了 年轻人吃不了这个苦

88
00:07:12,550 --> 00:07:14,925
虽然说 卖得快 但是背后累

89
00:07:18,675 --> 00:07:20,150
你得去要货

90
00:07:20,550 --> 00:07:22,750
要完货再清理

91
00:07:22,950 --> 00:07:25,775
再煮再炖出来 卤出来

92
00:07:26,075 --> 00:07:28,325
炖肉好弄 主要是收拾干净

93
00:07:32,350 --> 00:07:36,425
你看心了吗 都切开 把有血的地方收拾掉

94
00:07:37,375 --> 00:07:40,025
你看这耳朵是一个个都得烙猪毛

95
00:07:42,750 --> 00:07:45,375
就是清理费事

96
00:07:45,975 --> 00:07:49,325
这次咱们是买的20块钱的猪头肉还有10块钱的猪肝

97
00:07:50,050 --> 00:07:52,500
可以看到这个小摊上 人特别多

98
00:07:52,800 --> 00:07:54,500
叔叔阿姨也很健谈

99
00:07:54,725 --> 00:07:59,500
这么一个小的摊 但是感觉到烟火气息特别浓重

100
00:07:59,600 --> 00:08:02,550
好多老顾客 其实也不仅是来买肉吃

101
00:08:02,850 --> 00:08:05,125
还有的时候 也顺带聊聊天

102
00:08:05,350 --> 00:08:09,725
还有专程来要老汤 下面条 下米饭的

103
00:08:25,275 --> 00:08:27,600
今天的这份猪头肉是偶遇到的

104
00:08:27,875 --> 00:08:29,925
没想到 阿姨和叔叔这么健谈

105
00:08:30,050 --> 00:08:33,350
让我们整个的拍摄都充满了欢声笑语

106
00:08:33,900 --> 00:08:35,525
我去的时候只剩了半匹猪头

107
00:08:35,550 --> 00:08:38,225
我后面的人 就没有人再能够买到猪头肉了

108
00:08:39,275 --> 00:08:41,675
我戴着口罩都能闻到猪头肉的香味

109
00:08:42,350 --> 00:08:46,325
我们看一看 猪头肉到底有什么奇妙的地方

110
00:08:46,350 --> 00:08:50,425
能够让这么多的顾客 一直心心念念到

111
00:08:52,100 --> 00:08:53,875
不过 叔叔这边没有给我们切

112
00:08:54,750 --> 00:08:58,825
猪头肉 这边是瘦的 这边就是肥的

113
00:08:59,100 --> 00:09:00,450
很明显

114
00:09:07,700 --> 00:09:10,750
我觉得猪头肉 除了有点咸还是很不错的

115
00:09:11,800 --> 00:09:14,325
肉 炖得软烂

116
00:09:15,375 --> 00:09:17,700
就是嚼一嚼就能够咽得下去这一种

117
00:09:18,850 --> 00:09:21,075
我用手 轻轻地一掰

118
00:09:21,925 --> 00:09:26,500
不管是肥肉还是瘦肉 都很容易把它掰扯掉

119
00:09:29,750 --> 00:09:32,525
看到肉的纹理了吗

120
00:09:32,625 --> 00:09:34,650
这个肉不用吃就会很香

121
00:09:34,800 --> 00:09:38,125
刚才师傅说嘛 很多人都是闻着味就过来了

122
00:09:41,525 --> 00:09:43,225
吃猪头肉 一定要肥瘦搭配

123
00:09:43,500 --> 00:09:46,000
瘦的呢 就是这种咸香味十足

124
00:09:46,325 --> 00:09:49,275
带点肥的呢 又嫩 又有汤汁

125
00:09:49,450 --> 00:09:52,125
两个搭配在一起 就是极好的

126
00:09:52,375 --> 00:09:54,600
我感觉在吃肉的时候 很多人在注视着我

127
00:09:55,300 --> 00:09:58,125
我是全场的焦点


```

**Comment by shuaisoserious** [comment]
认领

**Comment by shuaisoserious** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）


简介

字幕
1
00:00:01,750 --> 00:00:03,800
山东·济南
Jinan. Shandong
2
00:00:21,775 --> 00:00:23,725
烧饼夹牛肉
Shaobing(baked, layered flatbread) with beef
3
00:00:26,300 --> 00:00:29,300
济南四月的清晨 还是有些清冷的
It’s still a little bit cold in the early morning in April of Jinan 
4
00:00:29,600 --> 00:00:31,925
这样的温度 适合吃个有能量的早餐
It’s time to eat an energy breakfast under temperature like this
5
00:00:32,525 --> 00:00:34,075
今天雪鱼来到回民街
Xue yu come to Muslim street today
6
00:00:34,275 --> 00:00:36,700
咱尝一尝这边的烧饼夹牛肉
Let’s try Shaobing with beef 
7
00:00:37,800 --> 00:00:40,050
大姐 这个多少钱一个
Old sis, how much is it?
8
00:00:40,575 --> 00:00:41,225
10块钱
10 yuan
9
00:00:41,350 --> 00:00:43,075
拿两个就行
I want two Shaobing with beef
10
00:00:58,975 --> 00:01:01,975
大哥 是刚才面已经揉完了 卖完了吗
Brother, is it sold out because you finish knead the dough?
11
00:01:01,975 --> 00:01:03,056
卖完了
Yes, it is 
12
00:01:04,500 --> 00:01:06,800
一天就卖这么一缸面是吧   对对
Only sell a vat of dough every day? right
13
00:01:11,425 --> 00:01:13,800
你看 像揉面 剁牛肉都是大哥自己来
Brother do the work of knead dough and chop beef by him own
14
00:01:14,300 --> 00:01:16,750
而像烤烧饼都是让大姐来上
And big sis do the work of bake 
15
00:01:17,225 --> 00:01:19,850
两个人分工真的是很明确
The division of their work between them is clear
16
00:01:58,750 --> 00:02:00,625
先炕再烤
Fry it before roast 
17
00:02:00,625 --> 00:02:03,850
上面是不抹油的（会用油擦一下铁板）
There is not a lot oil on the big pan (they will smear some oil on the big pan)
18
00:02:48,000 --> 00:02:50,400
看我们买的10块钱一个的牛肉夹馍
Look the shaobing with beef
19
00:02:51,225 --> 00:02:53,625
肉都要冒出来了
Beef is about coming out
20
00:02:55,000 --> 00:02:57,950
在寒冷的清晨 看着冒着热气的牛肉
Look at the beef with hot air in the cold early morning
21
00:02:58,175 --> 00:03:00,250
真的是特别舒服
Pretty comfortable 
22
00:03:01,775 --> 00:03:02,975
芝麻还好多
With plenty sesames
23
00:03:03,075 --> 00:03:06,633
这么闻着就是 面香味和牛肉的香味特别浓郁
Very strong smells of shaobing and beef when you smell it
24
00:03:06,950 --> 00:03:08,400
我要先吃一口了
I’m going to have one bite
25
00:03:11,425 --> 00:03:12,600
好咸啊
Very salty
26
00:03:15,200 --> 00:03:17,200
牛肉 汤汁特别多
juicy beef
27
00:03:18,025 --> 00:03:19,900
咬一口不会觉得噎着
It won’t choke you with one bite of beef
28
00:03:20,500 --> 00:03:22,800
牛肉是五香的 酱香的
The beef is five spiced favor  
29
00:03:23,025 --> 00:03:27,425
把它剁成细末 细丝夹在烧饼里
Minced beef in shaobing
30
00:03:27,650 --> 00:03:29,890
烧饼夹牛肉 分量这么重
With huge amount
31
00:03:29,890 --> 00:03:31,490
我觉得不仅我能吃饱
I think not only me can get full
32
00:03:31,490 --> 00:03:34,090
像一个大汉 也能吃得饱的
A strong man gets full too
33
00:03:38,475 --> 00:03:42,775
现在快7点了 后面的烧饼夹牛肉忙碌起来了
It’s about 7 am and they start get busy now
34
00:03:42,775 --> 00:03:47,700
大姐 牛肉烧饼作为早餐 顾客一般都买几个
Big sis, how many shaobing with beef customers buy as their breakfast as usual?
35
00:03:47,850 --> 00:03:49,325
这个不一定
It depends
36
00:03:49,750 --> 00:03:55,250
买最多的时候 有的人一买二三十个 十来个 这情况每天都有
Someone buy twenty or thirsty shaobing with beef at most, it happens everyday
37
00:03:55,475 --> 00:03:58,625
因为他们都知道这是用的鲜牛肉 现宰的活牛
Because they knew that it made by fresh beef, freshly slaughtered cattle 
38
00:03:59,175 --> 00:04:03,550
进口的和我这牛肉相差15块钱吧
Imports beef is cost 15 yuan more than my beef
39
00:04:04,875 --> 00:04:07,125
现在我买的牛肉32块钱一斤
Now my beef is 32 yuan every catty
40
00:04:07,475 --> 00:04:09,075
平时买36块钱一斤
36 yuan every catty as regularly
41
00:04:09,500 --> 00:04:10,825
这个就是 一般来说
usually
42
00:04:10,925 --> 00:04:12,750
你要是长期在这个地方能干下去
If you want work here in a long time
43
00:04:12,825 --> 00:04:16,775
就必须得讲诚信 必须讲质量 必须讲味道
You must be integrity with good quality and good favor 
44
00:04:17,350 --> 00:04:19,500
因为现在人花钱他就是说
Because now customer pay their money for quality of food
45
00:04:19,600 --> 00:04:24,600
你再深的巷子 只要味道好 他也愿意来
He will come and eat even if the place is far and hard to looking for
46
00:04:32,000 --> 00:04:35,725
大姐早上8点收摊
Big sis close their stall at 8 am
47
00:04:37,950 --> 00:04:41,025
下午4点 山东济南
4 pm. Jinan. Shandong
48
00:04:45,800 --> 00:04:47,575
大叔 猪头肉多少钱了
Uncle, how much for pig’s head meat
49
00:04:47,575 --> 00:04:49,275
38元一斤
38 yuan for every catty
50
00:04:50,600 --> 00:04:53,325
行 20块钱的猪头肉
Okay, I want 20 yuan of pig’s head meat
51
00:04:53,925 --> 00:04:55,950
 我给你称
I weight it
52
00:04:58,650 --> 00:05:00,050
来 少来点吧
Okay, less of it
53
00:05:00,050 --> 00:05:02,300
行 好好好
okay
54
00:05:02,300 --> 00:05:03,775
这都没有了 卖完了
All sold out
55
00:05:04,025 --> 00:05:05,900
不是4点开始营业吗
Isn’t it open at 4 pm?
56
00:05:06,275 --> 00:05:10,675
3点半 他们都挨着号排队
They start line up at 3:30 pm
57
00:05:13,150 --> 00:05:16,500
顾客：顺着这个味道就找来了
Customer: I come here for follow the smell
58
00:05:19,050 --> 00:05:23,900
俺这老汤都多少年了吧 精华全在汤里的
You can see how old my soups are, the essence is all in the soup
59
00:05:24,175 --> 00:05:25,775
都是您们两个人在这边干吗  是的
Only you two work here? yeah
60
00:05:27,200 --> 00:05:29,925
对 这是猪头肉
Yeah, this is pork head meat
61
00:05:30,250 --> 00:05:33,225
我先掀开你看看
Let me open for you to see it
62
00:05:34,775 --> 00:05:36,875
猪头肉怎么卖的   38元一斤 但是都卖完了
How much for pig’s head meat? 38 yuan for every catty, but all sold out now
63
00:05:37,200 --> 00:05:39,750
大叔一直吆喝着卖完了卖完了
Uncle keep shouting “sold out” “sold out”
64
00:05:46,175 --> 00:05:49,183
开始干的时候还是小鲜肉
when the business start, he was young
65
00:05:49,183 --> 00:05:51,350
现在成大叔级了
But now he become an uncle
66
00:05:54,775 --> 00:05:56,300
一般几点出来
What time it open usually?
67
00:05:57,025 --> 00:05:59,025
不到4点
Less than 4 pm
68
00:06:02,125 --> 00:06:05,325
你要想买肠子 两点半就得来 想买大肠
Come at 2:30 if you want buy large intestine 
69
00:06:06,850 --> 00:06:10,000
不排个前三四名的买不上大肠
You need rank in the top three or four to buy large intestine
70
00:06:10,000 --> 00:06:11,842
买大肠得两点半来吗
I need to come at 2:30 pm?
71
00:06:12,150 --> 00:06:14,050
大肠做的少 买的人多
Less large intestine but a lot of people want it
72
00:06:15,075 --> 00:06:17,400
如果不是2点半来  那也需要早来
You need come earlier
73
00:06:17,400 --> 00:06:19,000
他不是四点出摊吗
Isn’t he open at 4 pm?
74
00:06:19,257 --> 00:06:20,707
提前排队
Line up before it open
75
00:06:22,525 --> 00:06:25,650
我说想吃肥肠 猪尾巴这些的必须早来
Come earlier if you want intestine or pig’s tail 
76
00:06:26,700 --> 00:06:27,916
这一共有多少种
How many types of neat over there?
77
00:06:28,075 --> 00:06:31,425
生肉 250斤 20多种肉
250 catties of raw pork and more than 20 types of pork
78
00:06:33,775 --> 00:06:35,250
来给我弄点肉汤
Get me some pork soup
79
00:06:35,550 --> 00:06:37,530
这下好了 不仅肉得抢着买
Not only pork in rush to buy it
80
00:06:37,650 --> 00:06:39,550
大家连汤都不放过
Same as pork soup as well
81
00:06:46,650 --> 00:06:48,082
这个老汤回去怎么吃
What we eat with the old soup in home?
82
00:06:48,150 --> 00:06:51,275
喝面条 吃米饭都行
With noodle and rice is fine
83
00:06:53,375 --> 00:06:55,750
炖豆腐 炸豆腐
Stewed tofu and fried tofu
84
00:06:57,175 --> 00:06:59,075
还有炒鸡蛋
And fried eggs
85
00:07:04,300 --> 00:07:05,700
做卤肉确实累
It makes me tired to make pickled pork
86
00:07:05,700 --> 00:07:10,225
早上3点就起床 你说的是实在话
Must get up at 3 am, be honestly
87
00:07:10,450 --> 00:07:12,275
 太累了 年轻人吃不了这个苦
Too tired, young people cannot suffer like us
88
00:07:12,550 --> 00:07:14,925
虽然说 卖得快 但是背后累
Even it sold fast but behind it is suffer
89
00:07:18,675 --> 00:07:20,150
你得去要货
You need to buy pork
90
00:07:20,550 --> 00:07:22,750
要完货再清理
And clean it
91
00:07:22,950 --> 00:07:25,775
再煮再炖出来 卤出来
Boil it before stewing it, and then pickle it
92
00:07:26,075 --> 00:07:28,325
炖肉好弄 主要是收拾干净
Stew meat is easy, the point is clean it up
93
00:07:32,350 --> 00:07:36,425
你看心了吗 都切开 把有血的地方收拾掉
You see the heart? Cut it and clean the blood
94
00:07:37,375 --> 00:07:40,025
你看这耳朵是一个个都得烙猪毛
You see, you need to burn the hair of pork ear off
95
00:07:42,750 --> 00:07:45,375
就是清理费事
It really takes time to clean it
96
00:07:45,975 --> 00:07:49,325
这次咱们是买的20块钱的猪头肉还有10块钱的猪肝
We bought 20-yuan pig’s head meat and 10-yuan pork liver
97
00:07:50,050 --> 00:07:52,500
可以看到这个小摊上 人特别多
You can notice there are lots of customers surround the stall
98
00:07:52,800 --> 00:07:54,500
叔叔阿姨也很健谈
Uncle and aunt are also very talkative
99
00:07:54,725 --> 00:07:59,500
这么一个小的摊 但是感觉到烟火气息特别浓重
Such a small booth but with street food feel
100
00:07:59,600 --> 00:08:02,550
好多老顾客 其实也不仅是来买肉吃
Many old customers not only for buying pork
101
00:08:02,850 --> 00:08:05,125
还有的时候 也顺带聊聊天
Also, they come for talking by the way
102
00:08:05,350 --> 00:08:09,725
还有专程来要老汤 下面条 下米饭的
Someone coming for old soup to eat with noodle and rice
103
00:08:25,275 --> 00:08:27,600
今天的这份猪头肉是偶遇到的
We are very lucky to have the last pig’s head meat
104
00:08:27,875 --> 00:08:29,925
没想到 阿姨和叔叔这么健谈
Unexpectedly, aunt and uncle are so talkative
105
00:08:30,050 --> 00:08:33,350
让我们整个的拍摄都充满了欢声笑语
Make our whole shooting with full of fun
106
00:08:33,900 --> 00:08:35,525
我去的时候只剩了半匹猪头
There only half of pig’s head meat left when I come
107
00:08:35,550 --> 00:08:38,225
我后面的人 就没有人再能够买到猪头肉了
People who are behind me not able to get pig’s head meat
108
00:08:39,275 --> 00:08:41,675
我戴着口罩都能闻到猪头肉的香味
I can smell the smell of pig's head meat even if I’m wearing a mask
109
00:08:42,350 --> 00:08:46,325
我们看一看 猪头肉到底有什么奇妙的地方
Let’s take a look how delicious the pig’s head meat is
110
00:08:46,350 --> 00:08:50,425
能够让这么多的顾客 一直心心念念到
Why it makes so many customers miss 
111
00:08:52,100 --> 00:08:53,875
不过 叔叔这边没有给我们切
But uncle did not cut it for us
112
00:08:54,750 --> 00:08:58,825
猪头肉 这边是瘦的 这边就是肥的
Pig’s head meat, this is lean, there is fatty
113
00:08:59,100 --> 00:09:00,450
很明显
Very obviously 
114
00:09:07,700 --> 00:09:10,750
我觉得猪头肉 除了有点咸还是很不错的
I think pig’s head meat is pretty good except a little bit salty
115
00:09:11,800 --> 00:09:14,325
肉 炖得软烂
Meat stewed very soft
116
00:09:15,375 --> 00:09:17,700
就是嚼一嚼就能够咽得下去这一种
I can swallow it by chewing it a bit
117
00:09:18,850 --> 00:09:21,075
我用手 轻轻地一掰
I use my hand and gently break it
118
00:09:21,925 --> 00:09:26,500
不管是肥肉还是瘦肉 都很容易把它掰扯掉
it’s easy to pull it off Whether it’s fat or lean
119
00:09:29,750 --> 00:09:32,525
看到肉的纹理了吗
See the texture of pork
120
00:09:32,625 --> 00:09:34,650
这个肉不用吃就会很香
????????????
121
00:09:34,800 --> 00:09:38,125
刚才师傅说嘛 很多人都是闻着味就过来了
Uncle said that many customers following the smell 
122
00:09:41,525 --> 00:09:43,225
吃猪头肉 一定要肥瘦搭配
Eat pig’s head meat must be fatty and lean
123
00:09:43,500 --> 00:09:46,000
瘦的呢 就是这种咸香味十足
Lean meat is salty and fragment 
124
00:09:46,325 --> 00:09:49,275
带点肥的呢 又嫩 又有汤汁
Fatty is soft and juicy
125
00:09:49,450 --> 00:09:52,125
两个搭配在一起 就是极好的
It’s a good combo to put fatty and lean together 
126
00:09:52,375 --> 00:09:54,600
我感觉在吃肉的时候 很多人在注视着我
I feel people stared me when I’m eating
127
00:09:55,300 --> 00:09:58,125
我是全场的焦点
I am the focus of the crowd
