### ISSUE TITLE
[老饭骨] 大爷凉面- https://youtu.be/S169ctV_Dvc

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#989]
**视频链接**：https://youtu.be/S169ctV_Dvc

抖音链接：https://v.douyin.com/w3bkcn
YouTube 视频目前处于私享状态无法访问，请参照抖音视频

视频时长6:03 发布时间5月6日10:00PM

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•大爷凉面】酸、甜、咸、辣、香的家常怪味凉面！到底有几个味儿？！夏日必备的开胃小吃！|老饭骨

简介
小友们好，现在天气慢慢转热了，容易没有胃口。
大爷今天带来一道开胃爽口的怪味凉面，想有什么味儿，就有什么味儿！
大家可以根据自己的口味来调整酱汁，定制你专属的口味！
这个酱做好了还可以拿来做怪味粉皮和怪味鸡丝。
做酱汁的时候注意咱加酱油的时候要慢慢加，这样芝麻酱才润！
这期视频还有好多知识点，包括怎么提高面的筋度，辣椒油怎么做才不会糊，
小友们快来视频里寻找答案吧！

字幕
1
00:00:00,000 --> 00:00:01,520
怪味面

2
00:00:01,520 --> 00:00:03,800
想什么味 有什么味

3
00:00:03,800 --> 00:00:06,040
这就是怪味的特点

4
00:00:06,040 --> 00:00:09,520
麻酱

5
00:00:09,520 --> 00:00:11,040
先加酱油

6
00:00:11,040 --> 00:00:13,880

7
00:00:13,880 --> 00:00:17,880
酱油最好用生抽是吧 生抽就行

8
00:00:17,880 --> 00:00:20,960
有的颜色喜欢重一点

9
00:00:20,960 --> 00:00:24,120
可以略微的加一点老抽

10
00:00:24,120 --> 00:00:27,680
加酱油要少慢慢加

11
00:00:27,680 --> 00:00:32,360
要不然油一分离芝麻酱就不润了

12
00:00:32,360 --> 00:00:34,280
一点一点加

13
00:00:34,280 --> 00:00:36,440

14
00:00:36,440 --> 00:00:40,600
这个和好以后能保存 搁在冰箱里头

15
00:00:40,600 --> 00:00:43,560
十天半个月没问题

16
00:00:43,560 --> 00:00:47,720
但要切忌的就是葱姜蒜现吃现拌

17
00:00:47,720 --> 00:00:49,320
把葱姜蒜放到里头

18
00:00:49,320 --> 00:00:50,960
搁半个月就不行了

19
00:00:50,960 --> 00:00:54,920
变味了就 有点臭葱烂蒜味

20
00:00:54,920 --> 00:00:57,160
这酱油差不多了

21
00:00:57,160 --> 00:01:00,960
搁点醋（米醋） 醋根据自己的喜好

22
00:01:00,960 --> 00:01:02,000

23
00:01:02,000 --> 00:01:03,960
可多可少

24
00:01:03,960 --> 00:01:06,600
我们这个怪味就是

25
00:01:06,600 --> 00:01:09,080
你想有什么味就有什么味

26
00:01:09,080 --> 00:01:12,200
说有酸味 那就是里边有醋

27
00:01:12,200 --> 00:01:16,200
你看这稀稠 差不多了

28
00:01:16,200 --> 00:01:18,360
好了 放盐

29
00:01:19,360 --> 00:01:21,920
盐也别太多

30
00:01:21,920 --> 00:01:23,920
大约十克

31
00:01:23,920 --> 00:01:25,960
少来一点味精

32
00:01:25,960 --> 00:01:28,440
这花椒也要根据自己的喜好

33
00:01:28,440 --> 00:01:31,080
有的说我是爱吃麻的 就多放点

34
00:01:31,080 --> 00:01:35,840
花椒味可出来了 这是昨天现焙的

35
00:01:35,840 --> 00:01:35,880

36
00:01:35,880 --> 00:01:37,440
略微要放点糖

37
00:01:37,440 --> 00:01:39,160

38
00:01:39,160 --> 00:01:42,440
我们要放点香油 香油不少

39
00:01:42,440 --> 00:01:46,160
吃面得有油 没油它香不了

40
00:01:46,160 --> 00:01:47,680

41
00:01:47,680 --> 00:01:50,360
这都好了吧 这还准备芝麻

42
00:01:50,360 --> 00:01:52,920
这芝麻买的是熟芝麻

43
00:01:52,920 --> 00:01:57,080
这也别太多 太多了也油大

44
00:01:57,080 --> 00:01:58,760
今天调这些正好是

45
00:01:58,760 --> 00:02:00,800
我中午和大妈的午饭

46
00:02:00,800 --> 00:02:03,280
今天调的没调那么多

47
00:02:03,280 --> 00:02:06,720
第二个环节 切点小料

48
00:02:06,720 --> 00:02:08,960
切点小葱花

49
00:02:08,960 --> 00:02:12,080
这个怪味是多种味道的合成

50
00:02:12,080 --> 00:02:14,080
有的人说我爱吃小米辣

51
00:02:14,080 --> 00:02:15,440
我不爱搁辣椒油

52
00:02:15,440 --> 00:02:18,320
这里边搁点小米辣 葱花

53
00:02:18,320 --> 00:02:22,280
姜 爱吃姜的可以多搁点

54
00:02:22,280 --> 00:02:25,800
不爱吃的少搁 再不吃就可以不搁

55
00:02:25,800 --> 00:02:28,680
不搁就没这味了

56
00:02:28,680 --> 00:02:30,920
这个汁兑好以后有多用

57
00:02:30,920 --> 00:02:37,360
怪味凉面 怪味粉皮 怪味鸡丝

58
00:02:37,360 --> 00:02:41,200
那个也挺好吃 白斩鸡

59
00:02:41,200 --> 00:02:44,040
煮好了 买两大鸡腿一煮

60
00:02:44,040 --> 00:02:45,680
煮完了切成条

61
00:02:45,680 --> 00:02:50,200
怎么让你一说 立马就来食欲

62
00:02:50,200 --> 00:02:53,960
关键是味儿 姜米

63
00:02:53,960 --> 00:02:55,000
蒜末

64
00:02:55,000 --> 00:02:59,640
黄瓜 面条的黄瓜要切细

65
00:02:59,640 --> 00:03:02,760
炒菜的黄瓜要切粗一点

66
00:03:02,760 --> 00:03:05,560
黄瓜丝切好了

67
00:03:05,560 --> 00:03:08,360
咱把这汁再调调啊

68
00:03:08,360 --> 00:03:10,760
这怪味儿什么叫标准

69
00:03:10,760 --> 00:03:13,480
我给大家简单的说说

70
00:03:13,480 --> 00:03:17,080
闻 一闻着就香

71
00:03:17,080 --> 00:03:18,360
然后味觉

72
00:03:18,360 --> 00:03:21,320
我想葱姜味 有

73
00:03:21,320 --> 00:03:22,520
酱油味 有

74
00:03:22,520 --> 00:03:24,040
咸鲜味 有

75
00:03:24,040 --> 00:03:26,560
一尝 后面还有点胡椒

76
00:03:26,560 --> 00:03:28,520
到嗓子上还有点微辣

77
00:03:28,520 --> 00:03:30,560
然后到嗓子眼儿还有点小酸

78
00:03:30,560 --> 00:03:32,440
这就是怪味的特点

79
00:03:32,440 --> 00:03:35,040
想什么味 有什么味

80
00:03:35,040 --> 00:03:36,760
吃面条就得硬面

81
00:03:36,760 --> 00:03:38,640
有的面可能筋度不够

82
00:03:38,640 --> 00:03:40,960
稍微往里边可以放点盐

83
00:03:40,960 --> 00:03:44,760
用凉水和 和的硬一点 然后手擀

84
00:03:44,760 --> 00:03:49,120
面擀好了 大爷给切一下

85
00:03:49,120 --> 00:03:52,520
我擀的 大妈擀的

86
00:03:52,520 --> 00:03:56,400

87
00:03:56,400 --> 00:04:00,920
瞧这认真劲儿的 一气呵成

88
00:04:00,920 --> 00:04:02,600
左撇子还挺溜

89
00:04:02,600 --> 00:04:05,920

90
00:04:05,920 --> 00:04:07,400
抖了抖了

91
00:04:07,400 --> 00:04:10,160

92
00:04:10,160 --> 00:04:14,080
这叫一板儿面

93
00:04:14,080 --> 00:04:17,240
水开了 下锅了

94
00:04:17,240 --> 00:04:20,800
你看大爷家常备的 还备了辣椒油

95
00:04:20,800 --> 00:04:24,240
辣椒油也跟网友说一下

96
00:04:24,240 --> 00:04:27,920
先用点香油把这辣椒面给它和一下

97
00:04:27,920 --> 00:04:30,040
咱们家都吃的差不多了

98
00:04:30,040 --> 00:04:32,360
剩一碗底了 就你们吃的

99
00:04:32,360 --> 00:04:33,080

100
00:04:33,080 --> 00:04:35,600
完了以后把油烧热

101
00:04:35,600 --> 00:04:39,360
面好了 搁点什么油 花生油

102
00:04:39,360 --> 00:04:42,840
我们要再搁点香油 把油烧热

103
00:04:42,840 --> 00:04:46,720
烧热以后往那辣椒面里一呲

104
00:04:46,720 --> 00:04:50,760
呲第一勺的时候 你要看这油的温度

105
00:04:50,760 --> 00:04:55,840
如果这油温过热 呲第二勺的时候

106
00:04:55,840 --> 00:04:57,960
等这油温晾一晾 再呲

107
00:04:57,960 --> 00:04:59,440

108
00:04:59,440 --> 00:05:03,120
要不然它就糊了

109
00:05:03,120 --> 00:05:05,560
这是最简单的呲红油的方法

110
00:05:05,560 --> 00:05:06,760
一勺一勺的搁

111
00:05:06,760 --> 00:05:09,080
不要一下子都搁进去 那就糊了

112
00:05:09,080 --> 00:05:10,280

113
00:05:10,280 --> 00:05:14,080
这个味儿还真是挺冲的

114
00:05:14,080 --> 00:05:20,400
经过腌制以后 蒜香葱香非常香

115
00:05:20,400 --> 00:05:23,360
咱们今天就按份儿走 黄瓜丝

116
00:05:23,360 --> 00:05:26,200

117
00:05:26,200 --> 00:05:30,360
这是大爷的 一会再给大妈盛一碗

118
00:05:30,360 --> 00:05:32,120
为什么不先给我盛

119
00:05:32,120 --> 00:05:35,120
不是 这展示啊 要搁点辣椒啊

120
00:05:35,120 --> 00:05:37,160

121
00:05:37,160 --> 00:05:39,520
把汁儿往上一浇

122
00:05:39,520 --> 00:05:41,960
来点辣椒油

123
00:05:41,960 --> 00:05:44,520
有的喜欢吃热乎点的

124
00:05:44,520 --> 00:05:46,400
可以把辣椒面搁这上头

125
00:05:46,400 --> 00:05:48,840
拿热油呲

126
00:05:48,840 --> 00:05:52,680
大妈给照一相 咱们上菜了

127
00:05:52,680 --> 00:05:55,720
家有大厨 就是幸福


```

**Comment by WuStevenShengyang** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•大爷凉面】酸、甜、咸、辣、香的家常怪味凉面！到底有几个味儿？！夏日必备的开胃小吃！|老饭骨
State Banquet Master Chef: Sour, sweet, salty, spicy, fragrant "Strange Flavor Noodle". Delicious appetizing dish. 

简介
小友们好，现在天气慢慢转热了，容易没有胃口。
Hey friends, now it's getting hot, it is easy to lose appetite.
大爷今天带来一道开胃爽口的怪味凉面，想有什么味儿，就有什么味儿！
Today, Da Ye will teach you an appetizing noodle dish, which contains all types of flavors.
大家可以根据自己的口味来调整酱汁，定制你专属的口味！
You can customize the dressing base on your own preference!
这个酱做好了还可以拿来做怪味粉皮和怪味鸡丝。
This dressing can also be used to make rice noodle or shredded chicken.
做酱汁的时候注意咱加酱油的时候要慢慢加，这样芝麻酱才润！
Remember, we must gradually add soy sauce when making the dressing. This will make the dressing smooth.
这期视频还有好多知识点，包括怎么提高面的筋度，辣椒油怎么做才不会糊，
We will also teach you how to make chewy noodle and chili oil.
小友们快来视频里寻找答案吧！
Look for those in this video!

字幕
1
00:00:00,000 --> 00:00:01,520
怪味面
Strange flavor noodle.

2
00:00:01,520 --> 00:00:03,800
想什么味 有什么味
It has all the flavor you can possibly think of.

3
00:00:03,800 --> 00:00:06,040
这就是怪味的特点
This is the uniqueness of this flavor.

4
00:00:06,040 --> 00:00:09,520
麻酱
Sesame sauce.

5
00:00:09,520 --> 00:00:11,040
先加酱油
We add soy sauce first,

7
00:00:13,880 --> 00:00:17,880
酱油最好用生抽是吧 生抽就行
Light soy sauce is recommended.

8
00:00:17,880 --> 00:00:20,960
有的颜色喜欢重一点
However, if you prefer darker color,

9
00:00:20,960 --> 00:00:24,120
可以略微的加一点老抽
you can add a little bit dark soy sauce.

10
00:00:24,120 --> 00:00:27,680
加酱油要少慢慢加
We will add soy sauce gradually,

11
00:00:27,680 --> 00:00:32,360
要不然油一分离芝麻酱就不润了
otherwise it will separate from the sesame sauce.

12
00:00:32,360 --> 00:00:34,280
一点一点加
Gradually.

14
00:00:36,440 --> 00:00:40,600
这个和好以后能保存 搁在冰箱里头
Once we are done making the sesame dressing, it can be stored in the fridge

15
00:00:40,600 --> 00:00:43,560
十天半个月没问题
up to 15 days.

16
00:00:43,560 --> 00:00:47,720
但要切忌的就是葱姜蒜现吃现拌
However, we won't add spring onion, ginger, and garlic into it until we need to eat the sauce.

17
00:00:47,720 --> 00:00:49,320
把葱姜蒜放到里头
If you put them along with the sesame sauce into the fridge.

18
00:00:49,320 --> 00:00:50,960
搁半个月就不行了
It won't last as long.

19
00:00:50,960 --> 00:00:54,920
变味了就 有点臭葱烂蒜味
It will stink.

20
00:00:54,920 --> 00:00:57,160
这酱油差不多了
This much soy sauce should be enough.

21
00:00:57,160 --> 00:01:00,960
搁点醋（米醋） 醋根据自己的喜好
Add some rice vinegar

23
00:01:02,000 --> 00:01:03,960
可多可少
base on your preference.

24
00:01:03,960 --> 00:01:06,600
我们这个怪味就是
This so called "strange flavor"

25
00:01:06,600 --> 00:01:09,080
你想有什么味就有什么味
has all the flavor you can possibly think of.

26
00:01:09,080 --> 00:01:12,200
说有酸味 那就是里边有醋
You can taste sourness, because we have added vinegar into it.

27
00:01:12,200 --> 00:01:16,200
你看这稀稠 差不多了
This stickiness is good.

28
00:01:16,200 --> 00:01:18,360
好了 放盐
Okay, let's add salt.

29
00:01:19,360 --> 00:01:21,920
盐也别太多
Not not too much.

30
00:01:21,920 --> 00:01:23,920
大约十克
Around 10g.

31
00:01:23,920 --> 00:01:25,960
少来一点味精
A little bit of food MSG.

32
00:01:25,960 --> 00:01:28,440
这花椒也要根据自己的喜好
Add Sichuan peppercorn also base on your own preference.

33
00:01:28,440 --> 00:01:31,080
有的说我是爱吃麻的 就多放点
If you love numb flavor, add more.

34
00:01:31,080 --> 00:01:35,840
花椒味可出来了 这是昨天现焙的
Those peppercorns smell so good. They are freshly roasted yesterday.

36
00:01:35,880 --> 00:01:37,440
略微要放点糖
We need to add a little bit sugar.

38
00:01:39,160 --> 00:01:42,440
我们要放点香油 香油不少
Sesame oil is a key ingredient.

39
00:01:42,440 --> 00:01:46,160
吃面得有油 没油它香不了
Delicious noodle needs oil.

41
00:01:47,680 --> 00:01:50,360
这都好了吧 这还准备芝麻
Is everything prepared? We still need sesame seeds.

42
00:01:50,360 --> 00:01:52,920
这芝麻买的是熟芝麻
This is cooked sesame seeds.

43
00:01:52,920 --> 00:01:57,080
这也别太多 太多了也油大
But don't add too much, it will be too oily.

44
00:01:57,080 --> 00:01:58,760
今天调这些正好是
Those are

45
00:01:58,760 --> 00:02:00,800
我中午和大妈的午饭
me and my wife's lunch.

46
00:02:00,800 --> 00:02:03,280
今天调的没调那么多
Not too much food honestly.

47
00:02:03,280 --> 00:02:06,720
第二个环节 切点小料
Now, we will prepare some other ingredient.

48
00:02:06,720 --> 00:02:08,960
切点小葱花
Slice some spring onions.

49
00:02:08,960 --> 00:02:12,080
这个怪味是多种味道的合成
This "strange flavor" combines many others flavors.

50
00:02:12,080 --> 00:02:14,080
有的人说我爱吃小米辣
If you like Xiaomila chili pepper,

51
00:02:14,080 --> 00:02:15,440
我不爱搁辣椒油
but you don't like red chili oil,

52
00:02:15,440 --> 00:02:18,320
这里边搁点小米辣 葱花
you can add some Xiaomila and chopped spring onions.

53
00:02:18,320 --> 00:02:22,280
姜 爱吃姜的可以多搁点
If you love ginger, you can add more ginger.

54
00:02:22,280 --> 00:02:25,800
不爱吃的少搁 再不吃就可以不搁
If you don't like ginger, you can add less or even none.

55
00:02:25,800 --> 00:02:28,680
不搁就没这味了
There's going to be no flavor if you don't add ginger.

56
00:02:28,680 --> 00:02:30,920
这个汁兑好以后有多用
This dressing is versatile.

57
00:02:30,920 --> 00:02:37,360
怪味凉面 怪味粉皮 怪味鸡丝
You can make noodle, rice noodle, or shredded chicken with it.

58
00:02:37,360 --> 00:02:41,200
那个也挺好吃 白斩鸡
Baizhan Chicken (cold boiled chicken) is also a good accompany with this dressing.

59
00:02:41,200 --> 00:02:44,040
煮好了 买两大鸡腿一煮
Boil the chicken drumsticks, 

60
00:02:44,040 --> 00:02:45,680
煮完了切成条
slice them.

61
00:02:45,680 --> 00:02:50,200
怎么让你一说 立马就来食欲
I am getting hungry.

62
00:02:50,200 --> 00:02:53,960
关键是味儿 姜米
The key is the flavor, minced ginger,

63
00:02:53,960 --> 00:02:55,000
蒜末
minced garlic,

64
00:02:55,000 --> 00:02:59,640
黄瓜 面条的黄瓜要切细
and cucumber, finely sliced cucumber.

65
00:02:59,640 --> 00:03:02,760
炒菜的黄瓜要切粗一点
You will need to slice it thicker if you are instead making a fried dish.

66
00:03:02,760 --> 00:03:05,560
黄瓜丝切好了
We have finely sliced the cucumber.

67
00:03:05,560 --> 00:03:08,360
咱把这汁再调调啊
Let's further season the dressing.

68
00:03:08,360 --> 00:03:10,760
这怪味儿什么叫标准
What is a good "strange flavor"?

69
00:03:10,760 --> 00:03:13,480
我给大家简单的说说
I will tell you briefly.

70
00:03:13,480 --> 00:03:17,080
闻 一闻着就香
It should smell fragrant,

71
00:03:17,080 --> 00:03:18,360
然后味觉
And,

72
00:03:18,360 --> 00:03:21,320
我想葱姜味 有
it has the flavor of spring onion, ginger

73
00:03:21,320 --> 00:03:22,520
酱油味 有
soy sauce,

74
00:03:22,520 --> 00:03:24,040
咸鲜味 有
salt and fresh.

75
00:03:24,040 --> 00:03:26,560
一尝 后面还有点胡椒
After you take a sip, it has some peppercorn aftertaste,

76
00:03:26,560 --> 00:03:28,520
到嗓子上还有点微辣
spiciness,

77
00:03:28,520 --> 00:03:30,560
然后到嗓子眼儿还有点小酸
and even some sourness.

78
00:03:30,560 --> 00:03:32,440
这就是怪味的特点
This is the uniqueness of this "strange flavor".

79
00:03:32,440 --> 00:03:35,040
想什么味 有什么味
It has all the flavor you can possibly think of.

80
00:03:35,040 --> 00:03:36,760
吃面条就得硬面
The dough has to be hard.

81
00:03:36,760 --> 00:03:38,640
有的面可能筋度不够
Otherwise it won't be as chewy.

82
00:03:38,640 --> 00:03:40,960
稍微往里边可以放点盐
We can add a little bit salt.

83
00:03:40,960 --> 00:03:44,760
用凉水和 和的硬一点 然后手擀
Use cold water to harden it, and hand roll it.

84
00:03:44,760 --> 00:03:49,120
面擀好了 大爷给切一下
The dough is done, let Da Ye slice it.

85
00:03:49,120 --> 00:03:52,520
我擀的 大妈擀的
This is my noodle; this is my wife's.

87
00:03:56,400 --> 00:04:00,920
瞧这认真劲儿的 一气呵成
So clean.

88
00:04:00,920 --> 00:04:02,600
左撇子还挺溜
Left-handed Da Ye is quite skillful.

90
00:04:05,920 --> 00:04:07,400
抖了抖了
I choked, whoops.

92
00:04:10,160 --> 00:04:14,080
这叫一板儿面
This is a board of noodle.

93
00:04:14,080 --> 00:04:17,240
水开了 下锅了
Water is boiling. We can add the noodles in.

94
00:04:17,240 --> 00:04:20,800
你看大爷家常备的 还备了辣椒油
See, Da Ye always has red chili oil in his house.

95
00:04:20,800 --> 00:04:24,240
辣椒油也跟网友说一下
As for this chili oil,

96
00:04:24,240 --> 00:04:27,920
先用点香油把这辣椒面给它和一下
we need to mix sesame oil with paprika first.

97
00:04:27,920 --> 00:04:30,040
咱们家都吃的差不多了
We are almost running out of chili oil.

98
00:04:30,040 --> 00:04:32,360
剩一碗底了 就你们吃的
You guys ate all of it.

100
00:04:33,080 --> 00:04:35,600
完了以后把油烧热
After mixing paprika and sesame oil.

101
00:04:35,600 --> 00:04:39,360
面好了 搁点什么油 花生油
Noodles are done. Add some peanut oil into the pan.

102
00:04:39,360 --> 00:04:42,840
我们要再搁点香油 把油烧热
Along with some sesame oil, and heat them up.

103
00:04:42,840 --> 00:04:46,720
烧热以后往那辣椒面里一呲
Then pour all the oil into the mixed paprika.

104
00:04:46,720 --> 00:04:50,760
呲第一勺的时候 你要看这油的温度
You have to watch the temperature the first time you add oil.

105
00:04:50,760 --> 00:04:55,840
如果这油温过热 呲第二勺的时候
If it is too hot,

106
00:04:55,840 --> 00:04:57,960
等这油温晾一晾 再呲
wait until the oil cools and add further.

108
00:04:59,440 --> 00:05:03,120
要不然它就糊了
Otherwise, it will burn.

109
00:05:03,120 --> 00:05:05,560
这是最简单的呲红油的方法
This is the easiest way to make chili oil.

110
00:05:05,560 --> 00:05:06,760
一勺一勺的搁
Add the hot oil gradually.

111
00:05:06,760 --> 00:05:09,080
不要一下子都搁进去 那就糊了
It will burn if you dump all of them in once.

113
00:05:10,280 --> 00:05:14,080
这个味儿还真是挺冲的
This flavor is quite strong.

114
00:05:14,080 --> 00:05:20,400
经过腌制以后 蒜香葱香非常香
After marinating, the garlic and spring onion flavor is really fragrant.

115
00:05:20,400 --> 00:05:23,360
咱们今天就按份儿走 黄瓜丝
This is today's ration. Add the cucumber slices.

117
00:05:26,200 --> 00:05:30,360
这是大爷的 一会再给大妈盛一碗
This is Da Ye's. I will give my wife her ration.

118
00:05:30,360 --> 00:05:32,120
为什么不先给我盛
Why don't you give me first.

119
00:05:32,120 --> 00:05:35,120
不是 这展示啊 要搁点辣椒啊
No, this is to show the audience. I will add some paprika on top.

121
00:05:37,160 --> 00:05:39,520
把汁儿往上一浇
Pour the dressing in.

122
00:05:39,520 --> 00:05:41,960
来点辣椒油
Some chili red oil.

123
00:05:41,960 --> 00:05:44,520
有的喜欢吃热乎点的
If you like hot food,

124
00:05:44,520 --> 00:05:46,400
可以把辣椒面搁这上头
you can put some paprika on top.

125
00:05:46,400 --> 00:05:48,840
拿热油呲
and pour in some hot oil.

126
00:05:48,840 --> 00:05:52,680
大妈给照一相 咱们上菜了
Let's take a picture.

127
00:05:52,680 --> 00:05:55,720
家有大厨 就是幸福
Good chef, good life.
