### ISSUE TITLE
【美食作家王刚】乡下懒人排骨，分辨排骨是否油腻 - https://youtu.be/Ut8tvgryQ9U

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#990]
**视频链接**：https://youtu.be/Ut8tvgryQ9U

视频时长6:44，预计发布时间为北京时间5月4日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
给四伯爷做“懒人排骨”，四伯爷分享如何智斗“热心摊主”，看如何分辨排骨油腻与否

简介
朋友们好，之前教大家做“懒人烧排骨”的视频被四伯看到了，所以他特意留了一扇排骨也想尝尝懒人排骨什么味道，并且也借此机会来教大家一个辨别排骨油腻与否的小技巧，在买排骨的时候务必看一下排骨背面的油膜有没有撕掉，有些不热心的摊主可能有的时候会把油膜留着来压秤。四伯今天杀的是头老猪，个头非常大，所以排骨有些老，按平时烧40分钟应该可以脱骨，如果喜欢吃脱骨软烂一些的朋友可以适当延长炖煮的时间。

字幕
0:00:00.300,0:00:01.028
嗨喽大家好

0:00:01.121,0:00:02.751
今天我们做一个懒人排骨

0:00:03.364,0:00:07.109
然后这个是我四伯爷上午没有（卖）专门留起来的

0:00:07.144,0:00:09.028
他今天跟大家分享一个小技巧

0:00:09.121,0:00:10.231
来嘛 四伯爷

0:00:11.271,0:00:12.242
咋子搞啊

0:00:12.450,0:00:12.890
安

0:00:12.959,0:00:13.907
你说咋个搞啊

0:00:14.358,0:00:16.647
你说的都嘛 你说这块油是你故意留在上面的安

0:00:16.647,0:00:19.664
你看 很多猪不像这块排骨

0:00:19.745,0:00:23.445
你看我把它搞来就像百分之八十的那种排骨

0:00:24.312,0:00:26.369
这里面这个朦朦（膜）啊

0:00:26.936,0:00:29.600
你们买排骨你们必须要看到这个

0:00:30.578,0:00:32.739
这个朦朦拿来就没意义得

0:00:32.786,0:00:34.034
这个肥朦朦

0:00:34.670,0:00:35.468
就是肥油嘛 

0:00:35.514,0:00:36.855
啊 肥油嘛

0:00:37.375,0:00:39.803
这冷了就没得那么好抓得了

0:00:41.040,0:00:41.815
要刚刚

0:00:41.930,0:00:43.560
 要刚刚杀出来的时候

0:00:45.653,0:00:51.283
你们买排骨有多少人还不知道这个有的摊主他会把肥油留在上面

0:00:51.329,0:00:53.606
这个排骨吃起来非常腻

0:00:53.710,0:00:57.306
看嘛 很多他就懂不起 你看嘛这一层

0:00:59.294,0:01:00.000
这层肥油噶

0:01:00.092,0:01:04.023
这肥油刮来只有丢 我们屠宰场头

0:01:04.774,0:01:10.173
大家买排骨吃感觉很腻的话估计就是这层油给你留在上面了

0:01:10.462,0:01:14.023
以后你们买排骨要看一下反面这一面

0:01:14.092,0:01:18.150
不要有油的 有油的话要摊主把它给你撕掉

0:01:18.601,0:01:19.976
你这不好整哦

0:01:19.976,0:01:20.751
不好整就算了

0:01:21.086,0:01:23.433
你看嘛这撕了就看得到这个肉

0:01:23.942,0:01:26.173
没撕朦就看不到这个肉

0:01:26.323,0:01:27.988
一哈吃得完啊

0:01:28.404,0:01:29.394
吃不完打包

0:01:32.335,0:01:33.664
大块大块的砍咯

0:01:34.566,0:01:35.167
可以

0:01:42.289,0:01:43.826
呀 好粗一根的

0:01:44.265,0:01:47.410
好 我们这个排骨就这样切大块一点

0:01:47.514,0:01:48.718
下面来准备一下配料

0:01:48.718,0:01:48.756
那么大一块的啊

0:01:48.756,0:01:49.765
那么大一块的啊

0:01:49.953,0:01:51.360
烧出来它要缩 四伯爷

0:01:51.734,0:01:53.156
柠檬直接切片片

0:01:55.410,0:01:57.236
好酸哦 我都闻到酸了

0:01:58.247,0:01:58.883
可以

0:01:59.225,0:02:00.819
好 再切一块姜

0:02:02.474,0:02:05.095
然后再来几根葱

0:02:05.729,0:02:08.527
给它卷起来就可以了

0:02:09.484,0:02:10.692
我去拿个盆盆来

0:02:11.045,0:02:14.315
我们把这个切好的全部丢进去

0:02:16.053,0:02:17.790
然后调这个（料汁）

0:02:19.101,0:02:20.662
直接拿可乐来烧

0:02:21.354,0:02:22.857
我们这个直接放可乐

0:02:23.416,0:02:28.114
因为这个既甜 然后烧出来比较香

0:02:28.453,0:02:32.916
它这个可乐的话本身就有焦糖 也不用去调色

0:02:34.889,0:02:36.524
稍微多放一点可乐

0:02:37.069,0:02:37.879
加点盐巴

0:02:37.879,0:02:39.764
四伯爷你看到 比较神奇哈

0:02:40.029,0:02:44.374
我们这个盐放下去它又会重新冒泡

0:02:45.198,0:02:47.290
哦哟 跟烧的开水样

0:02:49.072,0:02:51.163
你们要说这个有多简单 就这么简单

0:02:51.281,0:02:54.388
然后我们再抓两把这个白糖下去

0:02:56.318,0:02:58.247
大概的话30克左右

0:02:59.013,0:03:01.590
然后直接这个倒进去这两个烧在一起就是

0:03:01.767,0:03:03.947
哦 好简单

0:03:04.020,0:03:05.257
所以叫懒人呢

0:03:05.567,0:03:07.025
嘿嘿 懒人安逸

0:03:07.363,0:03:09.352
四伯爷你吃了还是要变懒人的哦

0:03:09.602,0:03:12.253
我吃了二天变懒了 老子还要找你的麻烦

0:03:12.842,0:03:14.109
锅中加入适量的清水

0:03:18.247,0:03:20.250
然后将排骨冷水下锅焯水 

0:03:24.256,0:03:26.391
加入适量的料酒去腥

0:03:41.340,0:03:43.681
将调好的料汁倒入锅中

0:03:48.114,0:03:50.044
再将排骨下锅开大火烧开

0:04:04.668,0:04:06.745
烧开之后再撇去浮沫 

0:04:10.721,0:04:13.357
好 这哈就开小火慢慢烧

0:04:13.961,0:04:18.085
把这个水烧干 烧干了就可以了

0:04:25.552,0:04:26.450
好了没有

0:04:27.334,0:04:29.175
没有 我把这个捡了

0:04:35.670,0:04:38.718
把汤汁收浓就可以起锅了

0:04:42.651,0:04:43.416
差不多了

0:05:00.986,0:05:05.007
尝哈我的懒人排骨 看你吃了变不变懒

0:05:05.184,0:05:06.259
嘿嘿

0:05:08.410,0:05:09.793
整没整脱骨的哦

0:05:10.589,0:05:10.898
嗯

0:05:11.413,0:05:12.459
啃得动不哦

0:05:13.269,0:05:14.020
啃得动

0:05:15.979,0:05:19.263
点都不腻 虽然有点肥的都不腻

0:05:21.001,0:05:21.796
啃得动不嘛

0:05:22.783,0:05:23.571
干是好干

0:05:25.051,0:05:26.185
就是没烧脱骨

0:05:26.435,0:05:27.142
有点硬 噶

0:05:27.275,0:05:27.746
嗯

0:05:28.821,0:05:34.064
如果你们喜欢吃硬一点的话可以少烧一点时间

0:05:34.904,0:05:36.877
要是想吃软一点就多放点可乐

0:05:40.706,0:05:42.857
我的牙口不好就只有慢慢地啃

0:05:44.403,0:05:44.963
好吃

0:05:51.060,0:05:55.169
其实这个就是简单版本的糖醋排骨

0:05:55.493,0:05:58.247
比如没有放醋的话是放柠檬汁代替醋

0:05:58.615,0:06:01.973
然后糖的话就没有放那么多

0:06:06.332,0:06:11.119
就是说特别简单嘛 适合不怎么费精力的人做

0:06:11.163,0:06:12.371
所以叫做懒人排骨

0:06:13.107,0:06:15.095
懒人排骨 安逸

0:06:17.054,0:06:17.511
不干了

0:06:18.100,0:06:22.357
我们这个菜没有放一滴油 就是因为排骨它自己会出油

0:06:24.757,0:06:26.686
这个脆骨才好干

0:06:28.144,0:06:31.708
脆生生的 你们牙口好吃起就安逸得很

0:06:37.849,0:06:38.998
好了 本期视频就到这里

0:06:38.998,0:06:39.028
拜拜

0:06:39.028,0:06:39.352
拜拜

0:06:39.720,0:06:40.913
你们伯爷的牙齿咬不动 


```

**Comment by Hackerry** [comment]
认领

**Comment by Hackerry** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
给四伯爷做“懒人排骨”，四伯爷分享如何智斗“热心摊主”，看如何分辨排骨油腻与否
Cook "Lazy Man's Pork Ribs" for Uncle. Uncle shares what makes pork ribs too greasy.

简介
朋友们好，之前教大家做“懒人烧排骨”的视频被四伯看到了，所以他特意留了一扇排骨也想尝尝懒人排骨什么味道，并且也借此机会来教大家一个辨别排骨油腻与否的小技巧，在买排骨的时候务必看一下排骨背面的油膜有没有撕掉，有些不热心的摊主可能有的时候会把油膜留着来压秤。四伯今天杀的是头老猪，个头非常大，所以排骨有些老，按平时烧40分钟应该可以脱骨，如果喜欢吃脱骨软烂一些的朋友可以适当延长炖煮的时间。
Hello, everyone! Uncle wants to try "Lazy Man's Pork" after seeing our tutorial video, so he brought some spareribs. He also wants to share with you a tip when buying ribs: look for a layer of fat under the ribs. Some not-so-welcome butchers may leave the fat as additional weight. Today's ribs are from an aging hog, and therefore are not so tender. Usually 40 minutes' cooking can produce fall-out-of-bone ribs. You can cook for longer if you like tenderer ribs.

字幕
0:00:00.300,0:00:01.028
嗨喽大家好
Hello, everyone!

0:00:01.121,0:00:02.751
今天我们做一个懒人排骨
Today we'll cook "Lazy Man's Pork Ribs".

0:00:03.364,0:00:07.109
然后这个是我四伯爷上午没有（卖）专门留起来的
Uncle kept these spareribs from his morning market sale.

0:00:07.144,0:00:09.028
他今天跟大家分享一个小技巧
He wants to share a tip with you today.

0:00:09.121,0:00:10.231
来嘛 四伯爷
Here, Uncle.

0:00:11.271,0:00:12.242
咋子搞啊
What should I say?

0:00:12.450,0:00:12.890
安
Eh?

0:00:12.959,0:00:13.907
你说咋个搞啊
Where do I start?

0:00:14.358,0:00:16.647
你说的都嘛 你说这块油是你故意留在上面的安
You said you intentionally kept this oily layer on.

0:00:16.647,0:00:19.664
你看 很多猪不像这块排骨
You see, many ribs don't look like this one.

0:00:19.745,0:00:23.445
你看我把它搞来就像百分之八十的那种排骨
If I remove this, it will look like 80 percent of ribs you see.

0:00:24.312,0:00:26.369
这里面这个朦朦（膜）啊
The membrane here.

0:00:26.936,0:00:29.600
你们买排骨你们必须要看到这个
Before you buy ribs, you must check whether it is there.

0:00:30.578,0:00:32.739
这个朦朦拿来就没意义得
It is useless.

0:00:32.786,0:00:34.034
这个肥朦朦
This greasy stuff.

0:00:34.670,0:00:35.468
就是肥油嘛 
It's fat.

0:00:35.514,0:00:36.855
啊 肥油嘛
Yes, just fat.

0:00:37.375,0:00:39.803
这冷了就没得那么好抓得了
Difficult to remove now it's cold.

0:00:41.040,0:00:41.815
要刚刚
It should be removed...

0:00:41.930,0:00:43.560
 要刚刚杀出来的时候
Be removed right after kill.

0:00:45.653,0:00:51.283
你们买排骨有多少人还不知道这个有的摊主他会把肥油留在上面
You know some butchers they don't remove this fat.

0:00:51.329,0:00:53.606
这个排骨吃起来非常腻
And the ribs taste greasy.

0:00:53.710,0:00:57.306
看嘛 很多他就懂不起 你看嘛这一层
See? Some don't know about this fact. It's all because of this layer.

0:00:59.294,0:01:00.000
这层肥油噶
This layer of fat.

0:01:00.092,0:01:04.023
这肥油刮来只有丢 我们屠宰场头
This fat is just waste at our slaughterhouse.

0:01:04.774,0:01:10.173
大家买排骨吃感觉很腻的话估计就是这层油给你留在上面了
Greasy ribs are very likely because of this layer of fat.

0:01:10.462,0:01:14.023
以后你们买排骨要看一下反面这一面
So you should check the bottom side when shopping for ribs.

0:01:14.092,0:01:18.150
不要有油的 有油的话要摊主把它给你撕掉
Let the butcher remove this fat if you see it.

0:01:18.601,0:01:19.976
你这不好整哦
It's difficult to remove.

0:01:19.976,0:01:20.751
不好整就算了
Let it be.

0:01:21.086,0:01:23.433
你看嘛这撕了就看得到这个肉
You can see the meat now.

0:01:23.942,0:01:26.173
没撕朦就看不到这个肉
Before we can't see the meat.

0:01:26.323,0:01:27.988
一哈吃得完啊
Isn't it too much for one meal?

0:01:28.404,0:01:29.394
吃不完打包
We can store the rest.

0:01:32.335,0:01:33.664
大块大块的砍咯
Chop in big chunks?

0:01:34.566,0:01:35.167
可以
Sure.

0:01:42.289,0:01:43.826
呀 好粗一根的
Yay! This one is big.

0:01:44.265,0:01:47.410
好 我们这个排骨就这样切大块一点
OK. We leave ribs in those big chunks.

0:01:47.514,0:01:48.718
下面来准备一下配料
Now we prepare the seasoning ingredients.

0:01:48.718,0:01:48.756
那么大一块的啊
Keep them that big?

0:01:48.756,0:01:49.765
那么大一块的啊
Keep them that big?

0:01:49.953,0:01:51.360
烧出来它要缩 四伯爷
They will shrink once cooked, Uncle.

0:01:51.734,0:01:53.156
柠檬直接切片片
Slice some lemon.

0:01:55.410,0:01:57.236
好酸哦 我都闻到酸了
I can smell the sourness.

0:01:58.247,0:01:58.883
可以
Good.

0:01:59.225,0:02:00.819
好 再切一块姜
Now cut some ginger.

0:02:02.474,0:02:05.095
然后再来几根葱
Get some scallions.

0:02:05.729,0:02:08.527
给它卷起来就可以了
Wrap them around into a knot.

0:02:09.484,0:02:10.692
我去拿个盆盆来
I'll get a bowl.

0:02:11.045,0:02:14.315
我们把这个切好的全部丢进去
Put everything in.

0:02:16.053,0:02:17.790
然后调这个（料汁）
Now we prepare the sauce.

0:02:19.101,0:02:20.662
直接拿可乐来烧
I'm going to use coke.

0:02:21.354,0:02:22.857
我们这个直接放可乐
We use coke

0:02:23.416,0:02:28.114
因为这个既甜 然后烧出来比较香
because of its sweetness and flavor.

0:02:28.453,0:02:32.916
它这个可乐的话本身就有焦糖 也不用去调色
Coke has caramel that also colors food.

0:02:34.889,0:02:36.524
稍微多放一点可乐
A little bit more.

0:02:37.069,0:02:37.879
加点盐巴
Add some salt.

0:02:37.879,0:02:39.764
四伯爷你看到 比较神奇哈
Uncle, look. It's going to be interesting.

0:02:40.029,0:02:44.374
我们这个盐放下去它又会重新冒泡
Bubbles will appear once I add salt.

0:02:45.198,0:02:47.290
哦哟 跟烧的开水样
Wow, looks like it's boiling.

0:02:49.072,0:02:51.163
你们要说这个有多简单 就这么简单
Don't believe it? It's this simple.

0:02:51.281,0:02:54.388
然后我们再抓两把这个白糖下去
We add two handful of white sugar.

0:02:56.318,0:02:58.247
大概的话30克左右
About 30g.

0:02:59.013,0:03:01.590
然后直接这个倒进去这两个烧在一起就是
Then it's just a matter of cooking them together.

0:03:01.767,0:03:03.947
哦 好简单
Oh, that's easy.

0:03:04.020,0:03:05.257
所以叫懒人呢
That's why it's called a Lazy Man's dish.

0:03:05.567,0:03:07.025
嘿嘿 懒人安逸
Hehe, lazy man. Nice!

0:03:07.363,0:03:09.352
四伯爷你吃了还是要变懒人的哦
Uncle if you eat, you are going to become lazy.

0:03:09.602,0:03:12.253
我吃了二天变懒了 老子还要找你的麻烦
If I become lazy, you will be in trouble.

0:03:12.842,0:03:14.109
锅中加入适量的清水
Add water into the wok.

0:03:18.247,0:03:20.250
然后将排骨冷水下锅焯水 
Then put in ribs with cold water and boil.

0:03:24.256,0:03:26.391
加入适量的料酒去腥
Add some cooking wine to remove the stinky smell of pork.

0:03:41.340,0:03:43.681
将调好的料汁倒入锅中
Pour the prepared sauce into the wok.

0:03:48.114,0:03:50.044
再将排骨下锅开大火烧开
Then add ribs and boil over high heat.

0:04:04.668,0:04:06.745
烧开之后再撇去浮沫 
When boiling, remove the floating foams.

0:04:10.721,0:04:13.357
好 这哈就开小火慢慢烧
Good. Now we cook using low heat.

0:04:13.961,0:04:18.085
把这个水烧干 烧干了就可以了
Evaporate all the liquid and then it's done.

0:04:25.552,0:04:26.450
好了没有
It's ready?

0:04:27.334,0:04:29.175
没有 我把这个捡了
No, just picking these out.

0:04:35.670,0:04:38.718
把汤汁收浓就可以起锅了
Thicken the liquid and we are ready.

0:04:42.651,0:04:43.416
差不多了
Good enough.

0:05:00.986,0:05:05.007
尝哈我的懒人排骨 看你吃了变不变懒
Have a taste. See if you will be lazy.

0:05:05.184,0:05:06.259
嘿嘿
Hehe.

0:05:08.410,0:05:09.793
整没整脱骨的哦
It's not as tender as falling-off-the-bone.

0:05:10.589,0:05:10.898
嗯
Yes.

0:05:11.413,0:05:12.459
啃得动不哦
Is it chewy?

0:05:13.269,0:05:14.020
啃得动
Not so much.

0:05:15.979,0:05:19.263
点都不腻 虽然有点肥的都不腻
Not greasy at all. Even for the fat meat.

0:05:21.001,0:05:21.796
啃得动不嘛
Having trouble chewing?

0:05:22.783,0:05:23.571
干是好干
It's very dry.

0:05:25.051,0:05:26.185
就是没烧脱骨
But not tender.

0:05:26.435,0:05:27.142
有点硬 噶
A little bit hard?

0:05:27.275,0:05:27.746
嗯
Yes.

0:05:28.821,0:05:34.064
如果你们喜欢吃硬一点的话可以少烧一点时间
If you like chewy ribs, use less time cooking.

0:05:34.904,0:05:36.877
要是想吃软一点就多放点可乐
Add more coke if you want tender ribs.

0:05:40.706,0:05:42.857
我的牙口不好就只有慢慢地啃
My teeth stop me from eating. I have to take slow bites.

0:05:44.403,0:05:44.963
好吃
Yummy.

0:05:51.060,0:05:55.169
其实这个就是简单版本的糖醋排骨
This is simpler-version Sweet & Sour Pork Ribs.

0:05:55.493,0:05:58.247
比如没有放醋的话是放柠檬汁代替醋
Only we used lemon juice instead of vinegar.

0:05:58.615,0:06:01.973
然后糖的话就没有放那么多
And added not so much white sugar.

0:06:06.332,0:06:11.119
就是说特别简单嘛 适合不怎么费精力的人做
It's super easy to cook. Suitable for those who don't want to spend much time cooking.

0:06:11.163,0:06:12.371
所以叫做懒人排骨
That's why the name for it.

0:06:13.107,0:06:15.095
懒人排骨 安逸
Lazy Man's Pork Ribs. Nice!

0:06:17.054,0:06:17.511
不干了
I'm good.

0:06:18.100,0:06:22.357
我们这个菜没有放一滴油 就是因为排骨它自己会出油
We don't use any cooking oil, because the ribs contain much oil.

0:06:24.757,0:06:26.686
这个脆骨才好干
Gristle must be delicious.

0:06:28.144,0:06:31.708
脆生生的 你们牙口好吃起就安逸得很
They are crispy. Your teeth are good. You can enjoy.

0:06:37.849,0:06:38.998
好了 本期视频就到这里
Ok. This is all for this video.

0:06:38.998,0:06:39.028
拜拜
Bye bye.

0:06:39.028,0:06:39.352
拜拜
Bye bye.

0:06:39.720,0:06:40.913
你们伯爷的牙齿咬不动 
The ribs are too hard for your Uncle's teeth.
