### ISSUE TITLE
[华农兄弟] 华农兄弟场里长了好多菜苗挖点到其它地方种 - https://youtu.be/ueklkpgrC7Q

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#996]
https://youtu.be/ueklkpgrC7Q
<p>&#35270;&#39057;&#21457;&#24067;&#20110; May 1, 2020 at 11:02PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/ueklkpgrC7Q

#华农兄弟：场里长了好多菜苗，挖点到其它地方种
#Huanong Brothers: A lot of seedlings are growing in our site. We dig up some of them and plant them at another place.

0:00:00.000,0:00:03.220
# 大家好  你看  這裡有幾棵這個  攀蒲苗
Hi everyone! Look! Here are some, this kind of, pumpkin seedlings.

0:00:04.300,0:00:07.360
# 我挖到下面去種哦   要不然就被雞踩死啦
I'm gonna dig them out and plant them down there. Otherwise the chickens would step on them.

0:00:15.020,0:00:15.940
# 這個挖出來
Let me dig it out.

0:00:21.420,0:00:22.400
# 這也有一棵
Here's another one.

0:00:27.720,0:00:28.460
# 4棵
Four,

0:00:29.780,0:00:30.860
# 種4棵就夠啦
planting four would be enough.

0:00:47.340,0:00:48.680
# 就種這幾棵就夠啦
I'll plant only these seedling here.

0:00:51.320,0:00:53.720
# 這還有西紅杮哦  西紅杮我也種一棵
Here are also tomatoes. I'm gonna plant one tomato there too.

0:00:54.840,0:00:56.720
# 這西紅杮好大棵了  現在
This tomato is really big now.

0:00:57.500,0:00:59.580
# 這兩棵都比較大的  把它挖過去
These two are larger than the others. Let me take them there.

0:01:01.140,0:01:02.320
# 好  就種這幾棵
Alright! I'll plant these over there.

0:01:03.300,0:01:05.000
# 我們不挖走的話就沒有啦
Nothing would be left if we keep them here.

0:01:08.340,0:01:09.700
# 是不是有個葛根
Is here a kudzu root?

0:01:18.420,0:01:19.040
# 沒有
No

0:01:23.600,0:01:24.720
# 搞到下面去種
Let me plant them down there.

0:01:34.280,0:01:35.000
# 這裡種
Let me plant,

0:01:35.620,0:01:36.840
# 種兩棵番茄
plant two tomatoes here.

0:01:38.160,0:01:39.020
# 這裡來種
Plant them here.

0:01:57.200,0:01:59.100
# 你看  這些  這番茄我看它長得
Look! These, these tomatoes, I think they're really,

0:01:59.680,0:02:00.980
# 長勢是最大的
their growth is much ahead of the others.

0:02:09.160,0:02:10.920
# 嗯  還有一棵 哎喲
Um? There should be one more. Ayo!

0:02:12.320,0:02:13.520
# 我以為壓死啦
I thought it was crushed.

0:02:14.260,0:02:15.120
# 沒壓死
No, it isn't.

0:02:32.320,0:02:34.660
# 這樣  雙胞胎  剛好它們有伴
They are twins from now on. It's good that they have a buddy,

0:02:36.020,0:02:36.820
# 一人一邊
and have their own share of space.

0:02:37.760,0:02:38.940
# 等下我過來澆一下水
I'll pour some water here in a while.

0:02:39.800,0:02:41.380
# 再種一棵攀蒲  這裡
Let me plant a pumpkin as well, here.

0:02:45.740,0:02:47.120
# 我把它攀蒲種在這裡
I'll plant the pumpkin here.

0:03:02.160,0:03:04.140
# 攀蒲肯定會長很多攀蒲出來的
Pumpkins, I'm sure that there will be a lot of pumpkins.

0:03:12.220,0:03:13.500
# 可以  先種在這裡
Yup. Let me plant them here first.

0:03:18.880,0:03:20.800
# 到時候到秋天的時候就好多
Later, in autumn, there will be a lot,

0:03:21.700,0:03:22.740
# 好多東西吃
a lot of good food.

0:03:23.760,0:03:24.680
# 又有攀蒲
Not only pumpkins,

0:03:25.180,0:03:26.280
# 又有西紅杮
but also tomatoes.

0:03:52.880,0:03:54.000
# 再種好一棵
So one more is planted.

0:03:54.720,0:03:55.800
# 這裡再種一棵
Let me plant one more here.

0:04:13.460,0:04:14.840
# 嗯  又種好一棵
Um! Another one is planted.

0:04:19.220,0:04:20.400
# 這裡可以種一棵
I can plant one more here.

0:04:40.760,0:04:42.460
# 這個攀蒲是以前那個豬
These pumpkins are grown from the seeds,

0:04:43.180,0:04:44.380
# 吃剩下的那個籽
in the leftover of the pigs,

0:04:45.940,0:04:46.760
# 長出來啦
which used to be here.

0:04:48.440,0:04:49.260
# 最後一棵
The last one

0:04:52.720,0:04:53.980
# 嗯  等下澆一下水
Um! Let me pour some water in a while.

0:04:59.560,0:05:00.840
# 有個刺啊  這裡
A splinter

0:05:04.120,0:05:06.280
# 好啦  已經種下去啦
Alright! So they're all planted.

0:05:06.600,0:05:07.760
# 給它們澆一下水
I'll pour some water here.

0:05:12.060,0:05:12.780
# 拿個盆子來  (註︰結果他拿來了一個桶，我是不會為他更正的)
Let me fetch a pot.

0:05:39.840,0:05:40.460
# 夠啦
It's enough.

0:05:41.200,0:05:42.480
# 這裡還有那麼多
Here's still a lot.

0:05:56.680,0:05:57.360
# 好啦
Alright!

0:05:59.960,0:06:01.000
# 到時候我們就有  (註︰「到時候」譯作"later"較合適，但若把"later"放在前面又不太自然，放在後面又不合這裡的情景和分句，所以改了一下)
In a few months, we can,

0:06:02.040,0:06:02.940
# 攀蒲吃啦
enjoy our pumpkins.

0:06:05.940,0:06:07.960
# 這上次種的那個蘭花都活啦
The orchids that I planted last time is now growing pretty well.
